### ISSUE TITLE
virt-viewer no longer supporting spice consoles

### ISSUE THREAD

**Issue by spoon1331** [void-linux/void-packages#10014]
### System

* xuname:  
Void 4.19.29_1 x86_64 GenuineIntel uptodate rFF
* package:  
virt-viewer-8.0_1

Sorry if I've raised this against the wrong package... Wasn't sure if it should be against virt-viewer or one of the spice packages, so thought I'd start here :)

### Expected behavior
Should be able to connect to consoles of vms with spice graphics

### Actual behavior
Unable to connect to consoles of vms with spice graphic types

### Steps to reproduce the behavior
Install virt-viewer, and try to connect to spice console. This fails with "Unsupported graphic type 'spice'"

**Comment by spoon1331** [comment]
Looks like /usr/bin/virt-viewer no longer links to /usr/lib/libspice-client-gtk-3.0.so.5.0.0:

$ ldd /usr/bin/virt-viewer|grep spice
$

**Comment by CameronNemo** [comment]
@Cogitri I think it needs spice-protocol in makedepends

**Comment by Cogitri** [comment]
Ack, automagic deps are fun :P

Thanks for notifying here.

**Comment by Cogitri** [comment]
Hum, that should be pulled in by spice-devel already.

**Comment by Cogitri** [comment]
Ah, dev deps on spice-gtk are messed up, fixing now. Something which automatically scanned for those would be nice.
