### ISSUE TITLE
Package Request:  dwarves 

### ISSUE THREAD

**Issue by Piping** [void-linux/void-packages#10100]
Hi, is it possible to pack a new packages to void?

It is called  dwarves  in debian.

It is a set of utilities that help programmer to analyze the memory structure of the code.

Link to release and Packages. https://packages.debian.org/search?keywords=dwarves

**Comment by maxice8** [comment]
Please use the title used for other Package requests.

Include a link to their project homepage and available tarballs.

The project needs to have tagged releases.

**Comment by Piping** [comment]
@maxice8 updated!

**Comment by Piping** [comment]
Thank you so much!! I love void and all your people!!!
