### ISSUE TITLE
firefox is built without rust-simd

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#10129]
Just a reminder for the next round of firefox builds.
Setting `--enable-rust-simd` is probably worth doing.

**Comment by maxice8** [comment]
firefox update is available

**Comment by jnbr** [comment]
I'm aware and will push it later today but without the simd change. I wait for the next major release for this to avoid massive patches.

**Comment by jnbr** [comment]
`--enable-simd` doesn't work with `rustc >= 1.33`
