### ISSUE TITLE
Package request: transmission-seq

### ISSUE THREAD

**Issue by whoizit** [void-linux/void-packages#10134]
I have long successfully used the `transmission` sequential patch on Arch for many years. 
https://github.com/Mikayex/transmission
https://aur.archlinux.org/packages/transmission-sequential-cli/

- Can I add this patch (fork) to Void with pkgname transmission-seq?
https://github.com/transmission/transmission/compare/2.9x...Mikayex:2.9x-seq.patch

- Or can I add option with compiling with this patch to `transmission`? 

Officially this will never be added, [cause](https://github.com/transmission/transmission/wiki/Can-I-sequence-the-files-I-download#why-is-this-feature-not-implemented-in-transmission)

this feature is optional and by default it's turned off, so u can turn-on or turn-off it for any torrent

**Comment by Cogitri** [comment]
IMHO we shouldn't endorse something upstream explicitly tells us not to.

**Comment by whoizit** [comment]
you added ZFS to the Void, but it will never be added to the vanilla kernel, sounds like same things (upstream explicitly tells us not to)

**Comment by maxice8** [comment]
They are not the same thing, ZFS was added because:

- There is a huge demand
- Its upstream status is due to license issues, not "Because it makes the overall swarm's health worse."
- The usage of ZFS does not harm other users of Linux, The usage of sequential harms other users of a torrrent.
