### ISSUE TITLE
Package Request: distrobuilder

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#10140]
https://github.com/lxc/distrobuilder
> System container image builder for LXC and LXD

https://brauner.github.io/2018/02/27/lxc-removes-legacy-template-build-system.html
> So the templates will be replaced by distrobuilder as the preferred way to build LXC and LXD images locally.

**Comment by maxice8** [comment]
No releases apparently

**Comment by ndowens** [comment]
@Johnnynator This exists in repo now

**Comment by Johnnynator** [comment]
Added in cd8a61427b9ce9fb79600abc94ad2cce3ca3ed7c
