### ISSUE TITLE
Unable to build SPL/ZFS modules

### ISSUE THREAD

**Issue by zdykstra** [void-linux/void-packages#1017]
### System

* xuname:  
Void 4.17.6_1 x86_64 GenuineIntel notuptodate hold DFF

* package:  
spl-0.7.9_1
zfs-0.7.9_1

### Expected behavior

Installing ZFS and SPL should result in the DKMS system successfully building kernel modules for the installed kernels.

### Actual behavior

The DKMS configure phase for SPL fails, with the following snippet in the SPL config.log.

```
configure:12546: cp conftest.c build && make modules -C /lib/modules/4.17.6_1/build EXTRA_CFLAGS=-Werror-implicit-function-declaration   M=/var/lib/dkms/spl/0.
7.9/build/build 
cc1: error: incompatible gcc/plugin versions
cc1: error: fail to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so
cc1: error: incompatible gcc/plugin versions
cc1: error: fail to initialize plugin ./scripts/gcc-plugins/latent_entropy_plugin.so
make[1]: *** [scripts/Makefile.build:319: /var/lib/dkms/spl/0.7.9/build/build/conftest.o] Error 1
make: *** [Makefile:1571: _module_/var/lib/dkms/spl/0.7.9/build/build] Error 2
```
### Steps to reproduce the behavior

Attempt to build SPL and ZFS DKMS modules against Kernel 4.17.6_1

This seems to be from [this](https://github.com/void-linux/void-packages/commit/1308e0a703c4e42a441a41fd9a9cfff347f7de1d) commit.

**Comment by chneukirchen** [comment]
This will require a kernel bump due to gcc changes.

Or we finally drop these nonsense plugins.

**Comment by pullmoll** [comment]
I'm also suffering from that gcc plugin stuff. Have a Toshiba Satellite C70D-B here which needs broadcom-wl-dkms for its WIFI. I'm all for dropping the gcc plugins or turning them into an option, default off.

**Comment by zdykstra** [comment]
Is anything else but an xbump and adding [ci skip] to the PR needed for rebuilding kernels? I can open one for linux4.17 if that's the case - I'd love to see a rebuild so I can do a local ZFS root install.

**Comment by pullmoll** [comment]
We should rather update to 4.17.8. However the builders are really, really busy building gcc, libGL, qt5 and a couple of other things.

**Comment by pullmoll** [comment]
This should be solved by linux4.17-4.17.9, no?

**Comment by zdykstra** [comment]
For at least linux4.17, this is resolved.
