### ISSUE TITLE
gtk-engine-murrine: no 32bit package?

### ISSUE THREAD

**Issue by QuadPiece** [void-linux/void-packages#10225]
The template for `gtk-engine-murrine` contains `lib32disabled=yes`. So there's no 32bit library for murrine. Packages such as `pcsx2` which are only packaged in 32-bit form seem to break or be extremely buggy without murrine.

I tried building a 32bit package myself with xtools. But I couldn't find any documentation on how to build multilib packages. Removing `lib32disabled=yes` from the template and running `./xbps-src pkg gtk-engine-murrine-32bit` compiled something. But the resulting file was named `gtk-engine-murrine-0.98.2_6.x86_64.xbps`, so it appears to be 64-bit and wants to overwrite my existing `gtk-engine-murrine` package upon installing.

Is there any special reason why `gtk-engine-murrine` doesn't get built for multilib? It's a fairly critical package for many gtk applications. (EDIT: Assuming you're using a murrine theme of course)

**Comment by maxice8** [comment]
32bit packages are made out of packages built for i686

**Comment by QuadPiece** [comment]
I understand that, but I don't find any documentation for cross-building i686 packages. Or do I need a fully i686 environment to make 32-bit packages with xbps-src?

**Comment by maxice8** [comment]
On Mon, Mar 25, 2019 at 06:49:59AM -0700, Dominik V. Salonen wrote:
> I understand that, but I don't find any documentation for cross-building i686 packages. Or do I need a fully i686 environment to make 32-bit packages with xbps-src?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/10225#issuecomment-476205306

xbps-src -a i686 pkg <pkgname> should be enough as far as i remember.

**Comment by Duncaen** [comment]
```
./xbps-src -m masterdir-i686 binary-bootstrap i686
./xbps-src -m masterdir-i686 pkg gtk-engine-murrine
```

**Comment by QuadPiece** [comment]
Thank you, I managed to build a 32-bit version of the package and get it installed now.

**Comment by Cogitri** [comment]
I suppose we should enable lib32 for gtk-engine-murrine anyway?

**Comment by Duncaen** [comment]
Not sure why it was disabled: e41e4ca5109f01edd5375f0f34b71845e4c36cfb

**Comment by QuadPiece** [comment]
32bit applications look fine for me now, without gtk errors filling the terminal due to my murrine theme. So as far as I can tell, building gtk-engine-murrine for 32bit works fine, no issues that are obvious at least.

**Comment by maxice8** [comment]
Well we can try enabling it again
