### ISSUE TITLE
Package Request: Virtual Wifi/Net Backend

### ISSUE THREAD

**Issue by KalleDK** [void-linux/void-packages#10264]
I'm currently adding iwd as an optional option to the NetworkManager template, and can't decide what the correct way to handle wpa_supplicant in that case.

1) Keep it as a dependency - and simply have users manually force an ignore. This feels wrong
2) Remove the dependency if iwd is enabled - This feels wrong as wpa_supplicant and iwd both could be the backend now - but only one should be used.
3) Virtual package - as I understand this could solve the problem. Have wpa_supplicant as the default package and have iwd replace it if installed.
4) Add iwd as dependency if enabled and add a default option that if disabled removed wpa_supplicant as dependency
5) ??? Another way that I don't know of

Thanks for the help :)

( Just to clarify if iwd is not enabled it has to depend on wpa_supplicant, if iwd is enabled it can use either one of them and here the depend should be changed from wpa_supplicant to the virtual package)

**Comment by maxice8** [comment]
just add a dependency on iwd

**Comment by Cogitri** [comment]
Yup, we can't ensure that wpa_supplicant isn't installed anyway (conflicting with it sounds supoptimal) and NM still automatically uses w_s even if iwd is installed due to iwd support still being very much experimental.

**Comment by KalleDK** [comment]
> just add a dependency on iwd

I thought of that too, but that doesn't really solve the problem as the package would then depend on wpa_supplicant and iwd.

This is kinda a problem due to NM using wpa_supplicant if it is installed.

**Comment by KalleDK** [comment]
> Yup, we can't ensure that wpa_supplicant isn't installed anyway (conflicting with it sounds supoptimal) and NM still automatically uses w_s even if iwd is installed due to iwd support still being very much experimental.

Yeah I agree that it shouldn't be marked as conflicting - it's more a way to allow iwd to be the only installed without forcefully ignore/remove wpa_supplicant.

Hense the reason to have NM depend on wpa_supplicant if it is not build with iwd and only depend on the virtual package if it is.

It just feels wrong, that if you prefer iwd over wpa_supplicant you have to add wpa_supplicant to ignorepkg and/or force remove it afterwards.

**Comment by KalleDK** [comment]
Connman is gonna have the same "problem".

**Comment by Cogitri** [comment]
> It just feels wrong, that if you prefer iwd over wpa_supplicant you have to add wpa_supplicant to ignorepkg and/or force remove it afterwards.

IMHO we should ask upstream to handle this then, as about every solution to this seems very dissatisfactory.

>  the reason to have NM depend on wpa_supplicant if it is not build with iwd and only depend on the virtual package if it is.

What if you want to have another WiFi Manager installed at the same time (e.g. because NM doesn't work with your connection for whatever reason) which pulls in wpa_supplicant?

Really, upstream should provide a way to flat out disable wpa_supplicant (at runtime?)

**Comment by KalleDK** [comment]
> IMHO we should ask upstream to handle this then, as about every solution to this seems very dissatisfactory.
> 
The "bug" with NM using wpa_supplicant if installed is upstreams problem, that I agree with

> What if you want to have another WiFi Manager installed at the same time (e.g. because NM doesn't work with your connection for whatever reason) which pulls in wpa_supplicant?
> 
That I would say is working as intended - again that NM uses wpa_supplicant if it's installed is upstreams problem.

What about the new 4th suggestion, that would at least enable people to build and install it without the need to patch the template?
`./xbps-src -o iwd,~wpa_supplicant pkg NetworkManager`

This would still allow your example with another WiFi Manager that pulls wpa_supplicant.

**Comment by KalleDK** [comment]
My thoughts were just that you could add 
`provides=wifi-backend`
to both wpa_supplicant and iwd and have wpa_supplicant be the default one.

Then fx have base-system depend on wifi-backend. That should still install wpa_supplicant if the users doesn't do anything, but would allow for replacing the "wifi-backend"?

Again if a WiFi Manager only works with wpa_supplicant then that should be the dependency in that package and not wifi-backend.

**Comment by maxice8** [comment]
have `virtualpkg=wpa_supplicant:iwd` in `/etc/xbps.d/wifipkg.conf`

All requests for installing wpa_supplicant will be re-routed to iwd and wpa_supplicant can be removed.
