### ISSUE TITLE
Naming convention for font packages

### ISSUE THREAD

**Issue by pltrz** [void-linux/void-packages#10269]
I would like to clarify and reconcile the naming conventions for font packages. Many are inconsistent and follow different styles. It is not mentioned in Manual.md.

I am aware that packages in this repo usually retain the upstream naming unless absolutely necessary. Almost all packages tend to be consistent with this except for fonts.

Some existing examples:

- font uses exactly same as upstream
- font prepends/appends with `font` (currently the most common)
- font prepends or appends `ttf` or `otf`

**Comment by maxice8** [comment]
What is there to clarify ? packages that got it wrong got it wrong and will stay like that, new packages should use the format described in Manual.md

**Comment by Cogitri** [comment]
Yup, as we've seen with libvpx renaming packages doesn't go well

**Comment by pltrz** [comment]
I understand the concerns with renaming, I'll remind that libvpx and others that have been headaches have all been packages which are required as dependencies to other essential packages. Fonts are dead simple and are dependencies for no packages, so it should be relatively smooth

Is there a long-term goal in place for this kind of situation? These will simply stay strays forever?

Some are being merged using the prepended `font-` as I described above, such as #6964, #9851 and #9842. These examples are not using the format described in Manual.md, yet they are not having the style described in Manual.md enforced.

**Comment by maxice8** [comment]
> Is there a long-term goal in place for this kind of situation? 

No

> These will simply stay strays forever?

Yes

**Comment by Duncaen** [comment]
>  Fonts are dead simple and are dependencies for no packages, so it should be relatively smooth

**Comment by pltrz** [comment]
> That is not the issue, font packages are even harder to rename because nothing would pull them in to the transaction.

I see, then I was mistaken about that.

Nonetheless I'd like to know how this will move forward in the future.

Manual.md says packages should follow upstream, yet most font packages follow the format `font-<name>`. Moreover, new packages pulled in are following this convention, as I mentioned previously.

If it's desired that packages follow this convention or any other convention, I believe it should be made clear in Manual.md, and should be enforced/verified on pull requests for the sake of consistency.
