### ISSUE TITLE
hp-setup crash

### ISSUE THREAD

**Issue by DBLouis** [void-linux/void-packages#10268]
### System

* xuname:  
  Void 4.19.31_1 x86_64 GenuineIntel uptodate rFF
* package:  
  hplip-3.19.1_1

### Expected behavior

No crash

### Actual behavior

Crash:

Traceback (most recent call last):
  File "/usr/bin/hp-setup", line 426, in <module>
    ppds = cups.getSystemPPDs()
  File "/usr/share/hplip/prnt/cups.py", line 329, in getSystemPPDs
    path = os.path.join(cups_ppd_path, ppd)
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)

### Steps to reproduce the behavior

Run hp-setup and select USB as connection type.

**Comment by DBLouis** [comment]
Link to the issue on Launchpad: https://bugs.launchpad.net/hplip/+bug/1821740

**Comment by jnbr** [comment]
same as #10814, fixed in 687e3c21c6cacf52b18782a30f43b9883b098b21
