### ISSUE TITLE
Attempt to remove boot when removing kernel

### ISSUE THREAD

**Issue by ErinVoid** [void-linux/void-packages#1028]
### System
* xuname:  
Lenovo x230
* package:  
 linux4.16-4.16.18_1

### Expected behavior
Not to attempt to remove /boot/
### Actual behavior
Removing kernel via xbps-remove attempts to remove /boot/
### Steps to reproduce the behavior
Remove kernel package.

It would seem illogical removing any kernel package attempts to remove /boot/ as:
a) doing so makes a system unbootable
b) it will (or should) always fail
Whereas checking /boot/ exists and creates if doesn't when installing does make sense.

**Comment by cr6git** [comment]
https://github.com/voidlinux/void-packages/issues/7229

https://github.com/voidlinux/void-packages/issues/8753

https://github.com/voidlinux/void-packages/issues/8899
