### ISSUE TITLE
Package request: pim-data-exporter

### ISSUE THREAD

**Issue by no2spam** [void-linux/void-packages#10314]
KMail -> Tools -> Import/Export KMail data feature doesn't work. 

The following notification is displayed:
"Could not start "PIM Setting Exporter" program. Please check your installation."

The KDE PIM Setting Exporter package is missing from Void Linux repository

_Originally posted by @no2spam in https://github.com/void-linux/void-packages/pull/9492#issuecomment-477311181_

**Comment by Johnnynator** [comment]
https://github.com/void-linux/void-packages/commit/4adce0ec50e5dc72a1a73c8cb1e5384211c82220
