### ISSUE TITLE
Package Request: Zulu OpenJDK (musl)

### ISSUE THREAD

**Issue by jaredculp** [void-linux/void-packages#10333]
https://www.azul.com/downloads/zulu/zulu-download-alpine

I've tried creating a template for this but am having issues (noob) and haven't been able to find documentation.

**Comment by oscarandrea** [comment]
It would interest me too, I would use void musl if only it had at least one jdk for java.
In addition to the project you mentioned for musl: https://www.azul.com/downloads/zulu-community/?&os-linux&architecture-x86-64-bit&package-jdk
also exists: https://openjdk.java.net/projects/portola/

**Comment by Johnnynator** [comment]
We now have OpenJDK 11 packaged for musl. I don't think there is much of an advantage in packaging a prebuilt Zulu OpenJDK.
