### ISSUE TITLE
Package Request: electricsheep

### ISSUE THREAD

**Issue by silvernode** [void-linux/void-packages#10348]
# Electric Sheep
![electric sheep logo](https://dl2.macupdate.com/images/icons256/13096.png?d=1488315181)  

### Description:
Crowd sourced screensaver providing abstract visualizations created by the community. Electric Sheep is well known and goes back 20 years with support still going to this day.  

### Resources:
Main Website: https://electricsheep.org
Source: https://github.com/scottdraves/electricsheep
Build Instructions: https://github.com/scottdraves/electricsheep/wiki/Compiling

### Comments:
It's amazing nobody has packaged this already! If I thought of it back when I had more time on my hands I would have at least tried. Hopefully someone else agrees with me that electric sheep needs to be packaged. From what I have seen in skimming the build instructions, packaging shouldn't be too hard.

**Comment by knusbaum** [comment]
This program has no releases. In addition, it depends on a library called GLee, which appears to be unmaintained and has a broken website. I found *some* version of it on github, but that may not be a good source. 

It also seems to require work-arounds for newer versions of its dependencies. Although there are recent commits, it seems some larger work needs to be done on it. It's possible these work-arounds can be incorporated into the build steps, but I wasn't able to get the build to work. You can see Arch's build troubles in the comments here: https://aur.archlinux.org/packages/electricsheep/

Regardless, I did some work to get it to build, but ran into weird linking issues with lua. If someone wants to continue the work to get electric sheep to build, feel free. My guess is that it's not a good candidate for the repos, but you can probably get the package to build locally. 

I'll paste my templates below. Sorry, but I've not cleaned them up at all.

srcpkgs/electricsheep/template
```
# Template file for 'electricsheep'
pkgname=electricsheep
version=4949c31cfd
revision=1
wrksrc=electricsheep-4949c31cfdb0d4363cfa726aa3aa8325e540773f
build_wrksrc=client_generic
#create_wrksrc=yes
#only_for_archs="i686 x86_64"
build_style=gnu-configure
#configure_args=""
#make_build_args=""
#make_install_args=""
#conf_files=""
#make_dirs="/var/log/dir 0755 root root"
hostmakedepends="unzip base-devel"
makedepends="wxWidgets-devel ffmpeg-devel lua-devel libcurl-devel
libpng-devel libXrender-devel flam3-devel libgtop-devel boost-devel
tinyxml-devel libfreeglut-devel glee"
depends=""
short_desc="infinite evolving crowdsourced artwork "
maintainer="Kyle Nusbaum <knusbaum+void@sdf.org>"
license="GPL-2"
homepage="http://electricsheep.org"
distfiles="https://github.com/scottdraves/electricsheep/archive/4949c31cfdb0d4363cfa726aa3aa8325e540773f.zip"
checksum=e05270ff4441e06a969d8ad827e828c542ee875e1277c7e116b57ccdfcaf4e72

pre_configure() {
	./autogen.sh
}

do_build() {
    make CXXFLAGS+="-DUSE_NEW_FFMPEG_API=1 -DGL_GLEXT_PROTOTYPES -lpthread"
}
```

srcpkgs/flam3/template
```
# Template file for 'flam3'
pkgname=flam3
version=3.1.1
revision=1
#wrksrc=
#create_wrksrc=yes
#only_for_archs="i686 x86_64"
build_style=gnu-configure
#configure_args=""
#make_build_args=""
#make_install_args=""
#conf_files=""
#make_dirs="/var/log/dir 0755 root root"
hostmakedepends="base-devel libpng-devel libxml2-devel libjpeg-turbo-devel"
makedepends="zlib-devel"
depends=""
short_desc="original fractal flame renderer and genetic language"
maintainer="Kyle Nusbaum <knusbaum+void@sdf.org>"
license="GPL-3.0"
homepage="https://flam3.com/"
distfiles="https://github.com/scottdraves/flam3/archive/v${version}.tar.gz"
checksum=afcd4af13897740e34f6ae1f3061bbfbda9c1dd5df3ecc9f57141c985d35d19d

flam3-devel_package() {
	short_desc+=" - development files"
	depends="${sourcepkg}>=${version}_${revision}"
	pkg_install() {
		vmove usr/include
		vmove "usr/lib/*.a"
		vmove usr/lib/pkgconfig
	}
}
```

srcpkgs/glee/template
```
# Template file for 'glee'
pkgname=glee
version=cc956c52d4
revision=1
wrksrc=glee-cc956c52d42339d564d4d4bf846d1f973c4c5edc
#create_wrksrc=yes
#only_for_archs="i686 x86_64"
build_style=cmake
#configure_args=""
#make_build_args=""
#make_install_args=""
#conf_files=""
#make_dirs="/var/log/dir 0755 root root"
hostmakedepends="unzip base-devel"
makedepends="MesaLib-devel"
depends=""
short_desc="free cross-platform extension loading library for OpenGL"
maintainer="Kyle Nusbaum <knusbaum+void@sdf.org>"
license="GPL-3.0"
homepage="https://github.com/chadaustin/glee"
distfiles="https://github.com/chadaustin/glee/archive/cc956c52d42339d564d4d4bf846d1f973c4c5edc.zip"
checksum=6a4acea76d90a02496df120e7eac5147b846199a0c5268f3141ec3ae4203a005

pre_install() {
	# cmakelists requires lower-case readme.txt
	cp Readme.txt readme.txt
}
```

**Comment by silvernode** [comment]
Hey thanks for trying! It's a shame the process isn't easier but it is what
it is. It's not a big deal to me if it's only a local package but even
maintaining that could be annoying. I suppose if Nobody else wants to give
this a shot I can try with my limited knowledge and if that fails then I
will just close the request.

**Comment by maxice8** [comment]
Due to the problems mentioned above.
