### ISSUE TITLE
xmlrpc-c needs rebuild with gcc-7.3.0_4

### ISSUE THREAD

**Issue by rsmontero** [void-linux/void-packages#1038]
### System

* xuname:  
```
Void 4.17.6_1 x86_64 GenuineIntel uptodate rFF
```

* package:  
```
[*] xmlrpc-c-1.39.13_1       XML-RPC for C and C++
[*] xmlrpc-c-devel-1.39.13_1 XML-RPC for C and C++ - development files
```

### Expected behavior
NaN

### Actual behavior
Fail to compile xmlrpc-c program  using client libraries after update to gcc-7.3.0_4

### Steps to reproduce the behavior
NaN

The issue is fixed by recompiling the library with latest gcc version. Simply running xbps-src for the xmlrpc-c packages within an up-to-date system and install the resulting binary package solved the issue for me.

**Comment by Gottox** [comment]
cc @pullmoll

**Comment by travankor** [comment]
https://github.com/void-linux/void-packages/commit/3090f48edb6d6d2a411c2dfc5a7c3d669fe95817

https://github.com/void-linux/void-packages/commit/9c22cf2b2b3bf243194349a24d945e081d62b89e

**Comment by rsmontero** [comment]
Great!!! Last packages solved the issue. THANKS!!!!
