### ISSUE TITLE
libinput missing eudev-libudev-devel ?

### ISSUE THREAD

**Issue by biopsin** [void-linux/void-packages#10394]
### System
Linux 4.9.166_1 #1 SMP PREEMPT x86_64 GNU/Linux

* package:  
libinput

### Expected behavior
..finish without issue
### Actual behavior
Dependency libudev found: NO (tried pkgconfig)
meson.build:116:0: ERROR: Dependency "libudev" not found, tried pkgconfig
### Steps to reproduce the behavior
I package inside containers v1.6..so it could be on my end.

> The Meson build system
> Version: 0.50.0
> Source dir: /builddir/libinput-1.13.0
> Build dir: /builddir/libinput-1.13.0/build
> Build type: native build
> Project name: libinput
> Project version: 1.13.0
> Appending CFLAGS from environment: '-fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe   '
> Appending LDFLAGS from environment: '-Wl,-z,relro -Wl,-z,now -Wl,--as-needed    '
> Appending CPPFLAGS from environment: '   '
> Native C compiler: cc (gcc 8.3.0 "cc (GCC) 8.3.0")
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Fetching value of define "static_assert" : _Static_assert
> Header <dirent.h> has symbol "versionsort" : YES
> Header <errno.h> has symbol "program_invocation_short_name" : YES
> Has header "xlocale.h" : NO
> Checking if "locale.h" links: YES
> Header <sys/ptrace.h> has symbol "PTRACE_ATTACH" : YES
> Found pkg-config: /usr/bin/pkg-config (0.29.2)
> Did not find CMake 'cmake'
> Found CMake: NO
> Dependency libudev found: NO (tried pkgconfig)
> 
> meson.build:116:0: ERROR: Dependency "libudev" not found, tried pkgconfig
> 
> A full log can be found at /builddir/libinput-1.13.0/build/meson-logs/meson-log.txt
> => ERROR: libinput-1.13.0_1: do_configure: '${meson_cmd} --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/bin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc
> --localstatedir=/var --sharedstatedir=/var/lib --buildtype=plain --auto-features=enabled --wrap-mode=nodownload -Db_lto=true -Db_ndebug=true -Db_staticpic=true ${configure_args} . ${meson_builddir}' exited with 1
> => ERROR:   in do_configure() at common/build-style/meson.sh:108
>

**Comment by maxice8** [comment]
Doesn't make sense since eudev-libudev-devel is present there.

```
$ xbps-query -Rx libinput-devel --fulldeptree
libgcc-8.3.0_1
glibc-2.29_2
mtdev-1.1.5_2
mtdev-devel-1.1.5_2
eudev-libudev-3.2.7_2
eudev-libudev-devel-3.2.7_2
libuuid-2.33.1_2
libblkid-2.33.1_2
libmount-2.33.1_2
libuuid-devel-2.33.1_2
liblzma-5.2.4_2
dbus-libs-1.12.12_1
expat-2.2.6_1
expat-devel-2.2.6_1
dbus-devel-1.12.12_1
libffi-3.2.1_5
libffi-devel-3.2.1_5
libstdc++-8.3.0_1
libpcre-8.43_1
libpcrecpp-8.43_1
bzip2-1.0.6_14
bzip2-devel-1.0.6_14
zlib-1.2.11_3
libelf-0.176_1
glib-2.60.0_1
libgudev-232_2
libwacom-0.32_1
elfutils-devel-0.176_1
zlib-devel-1.2.11_3
libblkid-devel-2.33.1_2
libmount-devel-2.33.1_2
pcre-devel-8.43_1
libglib-devel-2.60.0_1
libgudev-devel-232_2
libwacom-devel-0.32_1
libevdev-1.6.0_1
libinput-1.13.0_1
libevdev-devel-1.6.0_1
```

**Comment by maxice8** [comment]
wfm but it is better we be explicit about it

**Comment by maxice8** [comment]
I made so libinput explicitly depends on eudev-libinput-devel
