### ISSUE TITLE
dina-font not currectly setup. Xft name isn't working.

### ISSUE THREAD

**Issue by zamlz** [void-linux/void-packages#10390]
### System

* xuname:  
```
Void 5.0.5_1 x86_64 GenuineIntel uptodate rFF
```
* package:  
```
dina-font-2.93_1 Monospace bitmap font, primarily aimed at programmers
```

### Expected behavior
Should install correctly and use Xft style naming. Specifically in the `.xresources` file,
```
*font: xft:dina:size=10
```

### Actual behavior
Is unable to use it.

### Steps to reproduce the behavior
Try to load font using Xft notation.
I should also mention that the xft notation works when I setup the Dina font myself in `$HOME/.fonts`. Not sure why, but maybe the package is not being setup correctly? Here is my font dir for reference.
```
.fonts
└── Dina-PCF
    ├── DinaBold10.pcf
    ├── DinaBold8.pcf
    ├── DinaBold9.pcf
    ├── DinaBoldItalic10.pcf
    ├── DinaBoldItalic8.pcf
    ├── DinaBoldItalic9.pcf
    ├── DinaItalic10.pcf
    ├── DinaItalic8.pcf
    ├── DinaItalic9.pcf
    ├── DinaMedium10.pcf
    ├── DinaMedium8.pcf
    └── DinaMedium9.pcf
```

**Comment by maxice8** [comment]
wfm on alacritty. (looks horrible but i guess that is par for the course)

**Comment by zamlz** [comment]
? Not sure what you mean. Is there any information you want me to retrieve?

**Comment by zamlz** [comment]
Here is a bit some pictures to describe what im talking about (For my lemonbar output).

**What it should look like (my manual install of the font)**
![2019-03-31-121523_186x24_scrot](https://user-images.githubusercontent.com/10750027/55293803-2bc19580-53af-11e9-9fb4-e0cb6b5ee760.png)

**What the package installs**
![2019-03-31-121639_278x18_scrot](https://user-images.githubusercontent.com/10750027/55293804-2bc19580-53af-11e9-9cb8-dab29dcef265.png)

**Default lemonbar font if it can't find the font**
![2019-03-31-121725_181x21_scrot](https://user-images.githubusercontent.com/10750027/55293805-2bc19580-53af-11e9-9239-26c45beff4e9.png)

**Comment by maxice8** [comment]
Hey, what is the version of freetype you're using on gentoo ?

**Comment by zamlz** [comment]
Running `freetype-config --version` gives me `22.0.16`.

**Comment by maxice8** [comment]
On Wed, Apr 03, 2019 at 06:15:49PM -0700, Amlesh Sivanantham wrote:
> Running `freetype-config --version` gives me `22.0.16`.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/10390#issuecomment-479713182

i mean the version of the package that gentoo uses, Void is on 2.10.0

**Comment by maxice8** [comment]
anyways i reverted to the last version, please check to see if it is fixed.

**Comment by zamlz** [comment]
Okay so the freetype version is 2.9.1.

And still the same error with the font.

**Comment by maxice8** [comment]
That is worrying, i reverted dina-font to use the same distfiles as Arch Linux and tried with both freetypes.

**Comment by maxice8** [comment]
Ok i fixed it, please update your system to recieve the new version of freetype-2.9.1_3 and re run fc-cache -fv.

The problem was fc-cache failing to register lots of bitmap fonts.

**Comment by maxice8** [comment]
![image](https://user-images.githubusercontent.com/30738253/55614921-84ed4880-5764-11e9-8139-6aefd8010fe6.png)

**Comment by zamlz** [comment]
YES! Its fixed. Thank you @maxice8! Could we also bump dina to 2.93 while we are at it?

**Comment by maxice8** [comment]
On Fri, Apr 05, 2019 at 05:32:26PM +0000, Amlesh Sivanantham wrote:
> YES! Its fixed. Thank you @maxice8! Could we also bump dina to 2.93 while we are at it?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/10390#issuecomment-480358657

I can try but i cannot promise that it will continue working. If i make a PR can you test it ?

**Comment by zamlz** [comment]
Sure! I can try that. Though, it may take a while to test it myself, but this also gives me the opportunity to setup the xbps-src environment locally right? I should probably learn how to do all this if I want to make packages for void in the future.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by zamlz** [comment]
Well seeing as how the latest version of dina is back in repo, I'll close this issue now.
