### ISSUE TITLE
libGL/nvidia template libglx.so symlink mix?

### ISSUE THREAD

**Issue by biopsin** [void-linux/void-packages#1040]
#libGL ..post_install()
ln -s libglx-xorg.so ${DESTDIR}/usr/lib/xorg/modules/extensions/libglx.so
#nvidia ..do_install()
ln -sf libglx.so.${version} ${DESTDIR}/usr/lib/xorg/modules/extensions/libglx.so

also notice libglx-xorg.so is missing and first symlink fails when libGL is installed last. (x64_glibc)

**Comment by maxice8** [comment]
nvidia replaces libGL when installed

**Comment by biopsin** [comment]
True, but update MESA after and symlink gets overwritten again.
lrwxrwxrwx 1 root root   14 Jul 18 08:15 libglx.so -> libglx-xorg.so (missing)
-rwxr-xr-x 1 root root  14M Jun 16 07:34 libglx.so.390.67

**Comment by Duncaen** [comment]
With the current packages you are not supposed to have mesa `libGL` and `nvidia-libs` installed at the same time.

**Comment by biopsin** [comment]
I'm still testing  libGL/libglvnd/nvidia  by maxice8, sorry for not being clear, but
neverless one game I play require glu which depends on mesa and so this mixup eventually happens even with the current packages, however only libGL and libglapi is installed in my case.

**Comment by biopsin** [comment]
Cleanup, reverted to normal repo packages. Upon installing nvidia-libs, Mesa-libs got removed and symlink to functioning libglx retained. Glu package does no longer pull in mesa either..
closed
