### ISSUE TITLE
gvfs: Remove gnome-online-accounts dependency

### ISSUE THREAD

**Issue by b1scu1t** [void-linux/void-packages#10416]
### System

* xuname:  
 `Void 4.14.108_1 x86_64 GenuineIntel notuptodate rF`
* package:  
  `gvfs-1.40.0_1 `

### Expected behavior
Install just `gvfs` without `gnome-online-accounts`
### Actual behavior
It also installs `libgdata` and `gnome-online-accounts` which also has `webkt2gtk` as its dependency. However, `gvfs` can function without`gnome-online-accounts` unless `gvfs-goa` is installed.
```
glibc>=2.29_1
glib>=2.18.0_1
gcr>=3.3.92_1
libsecret>=0.10_1
libnfs>=4.0.0_1
polkit>=0.99_1
libgudev>=230_1
gnome-online-accounts>=3.2.0_1
libgdata>=0.17.9_1
avahi-libs>=0.6.25_1
avahi-glib-libs>=0.6.25_1
libsoup>=2.34.0_1
libarchive>=3.1.2_1
fuse>=2.8.1_1
udisks2>=1.93.0_1
libbluray>=1.0.0_1
libxml2>=2.7.0_1

```
### Steps to reproduce the behavior
`sudo xbps-install -S gvfs`

**Comment by maxice8** [comment]
I made a PR and tagged you in it, please test it.
