### ISSUE TITLE
Signal-Desktop-1.21.1_1 update to 1.23.2_1 fails due broken icon extraction

### ISSUE THREAD

**Issue by MvomEndt** [void-linux/void-packages#10438]
### System

* xuname:  
Void 4.19.32_1 x86_64 GenuineIntel notuptodate rrrmFFFF
* package:  
Signal-Desktop-1.23.2_1 

### Expected behavior
Updating via xbps-install -Su should run through
### Actual behavior
Update fails with:
[*] Running transaction tasks
Signal-Desktop-1.21.1_1: updating to 1.23.2_1 ...
Signal-Desktop-1.23.2_1: unpacking ...
ERROR: Signal-Desktop-1.23.2_1: [unpack] failed to extract file `./usr/share/icons/hicolor/48x48/apps/signal.png/icon_48.png': Not a directory
ERROR: Signal-Desktop-1.23.2_1: [unpack] failed to extract files: Not a directory
ERROR: Signal-Desktop-1.23.2_1: [unpack] failed to unpack files from archive: Not a directory
### Steps to reproduce the behavior
Rerunning update gave the same result.
Renaming the existing signal.png in the 48x48 folder let the update continue till the next icon.

**Comment by MvomEndt** [comment]
I guess there is something odd with the default paths for signal since the last upgrade?
It now seems to expect to put icons for all resolutions into one folder instead, of what seems to be usual with my voidlinux installation - having them structured by resolution, then program.

**Comment by Cogitri** [comment]
Thanks for reporting, messed that up during the upgrade :c 

I've opened a PR which corrects the behavior.
