### ISSUE TITLE
Security related daemons uninstalled

### ISSUE THREAD

**Issue by Chocimier** [void-linux/void-packages#10465]
@Vaelatern, @Duncaen, others

Do you think it is ok to uninstall security related daemons from systems running Void, without even telling user that will be done?
See ebtables and arptables #10294.
Do you think it is ok to implicitly uninstall any software that people explicitly installed in order to use it?

If you think it is ok, please say so, which means that Void is targetted only to people know of every commit to packages repository before interacting with package manager, or who do not care whether they can still use computer after update.

If you don't think so, please change package removal process so that user will be aware of removing packages before they are gone.
The flaw was raised at least three months ago #6443.
Solution is ready since three weeks ago #9745, but functional software is still removed from systems in disguise of revbump update.

**Comment by Duncaen** [comment]
I think this change was not ready to be merged, lately many packages get removed/switched to "removed packages" which introduces issues like this one and other issues.

I think removing packages should require multiple "ok's".

I don't think this is limited to "security related daemons", but removing packages in general.

**Comment by knusbaum** [comment]
Sorry if my PR caused issues. I know this is a more general issue, but I'm happy to do the work to revert my PR if that's desirable.

**Comment by ericonr** [comment]
This has been solved with the addition of `removed-packages`.
