### ISSUE TITLE
New cyclic dependency

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#10473]
Some update reintroduced a dependency cycle: `cargo` -> `libgit2` -> `git` -> `libsecret` -> `vala` -> `graphviz` -> `librsvg` -> `cargo`
To me it seems `libgit2` depending on `git` in the host is not necessary because the former builds w/o the latter?

**Comment by pullmoll** [comment]
Oops. The inner cycle is still there after that change: `vala` -> `graphviz` -> `librsvg`.

**Comment by Cogitri** [comment]
Either build librsvg with ~vala or build your vala without valadoc

**Comment by CameronNemo** [comment]
Or make valadoc a separate source package !

**Comment by pullmoll** [comment]
@CameronNemo your suggestion is probably the best.
My local solution was to add a build option `rsvg` to `graphviz` which defaults to no, i.e. builds `graphviz` without support for `SVG`, and later on force build it with `-o rsvg`.

**Comment by CameronNemo** [comment]
Working on valadoc right now. I have to build the whole heckin thing, oh well.

**Comment by jnbr** [comment]
should be fixed by #10488
