### ISSUE TITLE
qutebrowser crashes with qt5-5.10.1_11

### ISSUE THREAD

**Issue by Gottox** [void-linux/void-packages#1051]
### System

* xuname:
  Void 4.17.6_1 x86_64 GenuineIntel uptodate rrrrmdF
* package:
  qutebrowser-1.4.1_1

### Expected behavior

Qutebrowser should show a window

### Actual behavior

crashes with `segfault`.

### Steps to reproduce the behavior

1. Make sure `qt5-5.10.1_11` is installed
2. start qutebrowser

### Additional information

The issue can be worked around by downgrading to `qt5-5.10.1_9`.

cc @pullmoll any idea?

**Comment by Gottox** [comment]
I suspect this is caused by #983

**Comment by pullmoll** [comment]
I'm up to date with official packages and qutebrowser works here, so I can't reproduce and debug the package :(

**Comment by Gottox** [comment]
Rebuilding `qt5-webkit` solved the issue for me, but I'm still affected by #1033.

**Comment by pullmoll** [comment]
I'd then suggest to revbump qt5-webkit and all (not yet rebuilt) dependencies of libGL to get libGL go with the CXX11 ABI.

**Comment by Gottox** [comment]
should be fixed with 85bbcec3ca3729f3294dd2cc495c7d308e01247f
