### ISSUE TITLE
[WSL] qt5: libQt5Core.so.5 missing

### ISSUE THREAD

**Issue by Nexolight** [void-linux/void-packages#10521]
So whenever I try to open systemsettings5 and some other apps that use qt5 it yields an error about a shared library that was not found but does in fact exist:

`systemsettings5: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory`

```
ls -lisa /usr/lib/libQt5Core.so*
1407374884408040    0 lrwxrwxrwx 1 root root      20 Feb 10 12:45 /usr/lib/libQt5Core.so -> libQt5Core.so.5.11.3
1407374884408039    0 lrwxrwxrwx 1 root root      20 Feb 10 12:45 /usr/lib/libQt5Core.so.5 -> libQt5Core.so.5.11.3
1407374884408038    0 lrwxrwxrwx 1 root root      20 Feb 10 12:45 /usr/lib/libQt5Core.so.5.11 -> libQt5Core.so.5.11.3
1125899907697413 5376 -rwxr-xr-x 1 root root 5197768 Feb 10 12:45 /usr/lib/libQt5Core.so.5.11.3
```
I was able to fix it by issuing this command:

`sudo strip --remove-section=.note.ABI-tag /usr/lib/libQt5Core.so.5`

I have no clue what is going on and of curse I tried many things on different systems. I cannot recall every logline from my memory but I will leave this here and hope someone investigates.

### System

* xuname:  
  Void 4.4.0-17134-Microsoft x86_64 GenuineIntel uptodate rFF
* package:  
  systemsettings-5.15.3.2_1 (and many more)

### Expected behavior

The command systemsettings5 opens the respective window

### Actual behavior

This error is shown:
`systemsettings5: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory`

### Steps to reproduce the behavior
Install systemsettings5 with dependencies on a fresh installation and try to execute it from terminal. 
*I'm on WSL but I ran into this issue on multiple systems since years.*

**Comment by Duncaen** [comment]
https://github.com/Microsoft/WSL/issues/3023
