### ISSUE TITLE
Package Request: OnionShare

### ISSUE THREAD

**Issue by yilmzfurkan** [void-linux/void-packages#10533]
### **Description:**
OnionShare is an open source tool for securely and anonymously sending and receiving files using Tor onion services. It works by starting a web server directly on your computer and making it accessible as an unguessable Tor web address that others can load in Tor Browser to download files from you, or upload files to you. It doesn't require setting up a separate server, using a third party file-sharing service, or even logging into an account.

Unlike services like email, Google Drive, DropBox, WeTransfer, or nearly any other way people typically send files to each other, when you use OnionShare you don't give any companies access to the files that you're sharing. So long as you share the unguessable web address in a secure way (like pasting it in an encrypted messaging app), no one but you and the person you're sharing with can access the files.

### **Links:**
GitHub: https://github.com/micahflee/onionshare
Website: https://onionshare.org/

**Comment by maxice8** [comment]
```
# Template file for 'onionshare'
pkgname=onionshare
version=2.0
revision=1
archs=noarch
build_style=python3-module
pycompile_module="onionshare"
pycompile_dirs="/usr/share/nautilus-python/extensions"
hostmakedepends="python3-setuptools"
# Missing
# altgraph
# ans1crypto
# macholib
# pefile
# PyQt5-sip
depends="python3-cffi python3-chardet python3-click python3-cryptography
 python3-Flask python3-future python3-idna python3-itsdangerous
 python3-Jinja2 python3-MarkupSafe python3-pycparser python3-pycryptodome
 python3-PyQt5 python3-pysocks python3-requests python3-six python3-stem
 python3-urllib3 python3-Werkzeug"
short_desc="Share files anonymously and securely"
maintainer="maxice8 <thinkabit.ukim@gmail.com>"
license="GPL-3.0-or-later"
homepage="https://onionshare.org/"
distfiles="https://github.com/micahflee/onionshare/archive/v${version}.tar.gz"
checksum=528ceb6234ecacabe51080e351c2e8f205cbf08cdfcfddc418586d578baa030e

conf_files="/etc/apparmor.d/local/*"

post_install() {
	vmkdir etc/apparmor.d
	vcopy "apparmor/*" etc/apparmor.d/
}
```
