### ISSUE TITLE
Elogind 241 broken on musl

### ISSUE THREAD

**Issue by Cogitri** [void-linux/void-packages#10573]
This causes e.g. GNOME to be broken on *-musl. Confirmed by me and a few other users.

To test with old elogind on x86_64-musl: `xbps-install --repository=https://exp.exqa.de -fS elogind libelogind elogind-devel`

See https://github.com/elogind/elogind/issues/130

@Gottox

**Comment by Yamakuzure** [comment]
The differences to v239.4 are very slim. However, two changes might cause this.

Here are two patches to reverse each. Please, if you can, try out each individually and both together.

1. https://gist.github.com/Yamakuzure/d6b3eb2b0406229129aa7bfcf08212a4
2. https://gist.github.com/Yamakuzure/502c0b0df770db50de24f635250cc4f1

**Comment by xtraeme** [comment]
@Yamakuzure I can confirm both patches are required to unbreak musl. Tested and running on my x86_64-musl system.

**Comment by Cogitri** [comment]
Can't test, am unavailable for the next two weeks due to holidays :)

**Comment by Gottox** [comment]
I can't see how `reverse_CLOSE_ON_EXEC_removal.patch` changes the behavior of the program. Afaiu it only avoids dangling file descriptors after exec.

**Comment by Gottox** [comment]
I can confirm, that these patches fix Gnome on musl.

**Comment by prspkt** [comment]
This fixes elogind on musl for me as well.

**Comment by Cogitri** [comment]
Nice :)
