### ISSUE TITLE
Package Request: vscodium

### ISSUE THREAD

**Issue by Itamiko** [void-linux/void-packages#10582]
Would love to have this package since this version will use the latest of vscode but with MIT license

also disables the telemetry build flag.

[Github Link](https://github.com/VSCodium/vscodium)

**Comment by Cogitri** [comment]
Don't we already disable telemetry in our vscode @shizonic ?

**Comment by maxice8** [comment]
On Fri, Apr 05, 2019 at 12:20:25AM -0700, Rasmus Thomsen wrote:
> Don't we already disable telemetry in our vscode @shizonic ?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/10582#issuecomment-480174356

iirc Void Linux doesn't touch default telemetry, only on Firefox i think.

**Comment by shizonic** [comment]
@Cogitri It was disabled earlier but I was asked to remove the patch.

**Comment by Cogitri** [comment]
Ah, alright.

**Comment by Cogitri** [comment]
IMHO maybe we should abandon VSCode all together then and knly package VSCodium?

**Comment by maxice8** [comment]
> IMHO maybe we should abandon VSCode all together then and knly package VSCodium?

Sounds good by me @void-linux/pkg-committers

**Comment by shizonic** [comment]
Fine for me too. But we should be aware of adding the ms store url anyway to be able to download extensions.

**Comment by Cogitri** [comment]
Yup

**Comment by Hoshpak** [comment]
So from what I understand, this is just a custom build configuration which is then offered as a binary package? As much as I dislike all that electron stuff, can't we just adjust our vscode build configuration to our liking and keep building from source?

**Comment by shizonic** [comment]
Correct. This was exactly what I had before and was asked to remove... ;)

**Comment by maxice8** [comment]
@shizonic there is a vscode update available, please add vscodium configuration to it.

**Comment by JasMich** [comment]
Anyone interested in merging?

**Comment by Duncaen** [comment]
Not really, merging binary packages is bad because they would lock our repos when we update a dependency with a shared library bump and we can't rebuild the binary package.

**Comment by JasMich** [comment]
I see. If I would create a version to build from source?

**Comment by Duncaen** [comment]
This might be possible if we can get shared electron packages like arch linux has.
Building whole chromium just for this one package is a no go, because it adds a lot of maintenance burden in regard of patching and build time.

**Comment by shizonic** [comment]
If there is enough interest, I'll try to package electron.

**Comment by JasMich** [comment]
Please do! I would kindly like to contribute.

**Comment by ProjectMoon** [comment]
A shared electron package would be useful for other things that need it (e.g. riot-desktop).

**Comment by shizonic** [comment]
> A shared electron package would be useful for other things that need it (e.g. riot-desktop).

Feel free to package it.

**Comment by Cogitri** [comment]
FWIW I recently made a MR for it for Alpine. It does compile now, but SIGSEGVs on musl. Maybe it'll work on glibc for you though: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/7310

**Comment by shizonic** [comment]
Thank you. I'll give it a shot asap.

**Comment by Johnnynator** [comment]
I just gave it a try and got vscode on both glibc and musl running. I will post a PR later after cleaning some things up.
@Cogitri Intresting that it didn't work on Alpine, the only patch I added for Void was for glibc and no other changes to patches.

https://i.imgur.com/emvLfe4.png

**Comment by Cogitri** [comment]
Nice! :)

Apparently it _does_ work on Alpine, but electron likes to crash on XWayland (so it only works on X11). Do you happen to use X11, @Johnnynator ?

**Comment by Johnnynator** [comment]
Yeah, I was running on X11.

**Comment by Johnnynator** [comment]
But works also fine with Plasma wayland

**Comment by Cogitri** [comment]
Huh, weird, it crashes for me like this with GNOME Wayland: https://github.com/electron/electron/issues/9662#issuecomment-62211440

Can you maybe give me your electron x86_64 musl package so I can test if that works on Alpine too?

**Comment by shizonic** [comment]
Vscode natively on musl ?! A dream becomes true ... !

**Comment by Johnnynator** [comment]
@Cogitri https://void.johnnynator.dev/electron/ has the binary , also I forgot to mention, I removed a system zlib patch for the time since it somehow broke the build system (would be suprised if that actually "fixed" anything)

**Comment by Cogitri** [comment]
Hm, seems like that SIGSEGVs for me too when I do `/usr/lib/electron7/electron`

**Comment by Cogitri** [comment]
Sorry to clutter the issue with that, but can you maybe give me a VSCode package too, @Johnnynator 😅

**Comment by shizonic** [comment]
Guess you are talking about a musl version? @Cogitri

**Comment by Cogitri** [comment]
Yup

**Comment by shizonic** [comment]
@Cogitri Have you seen this:
https://github.com/Johnnynator/void-packages/commit/e51b6a1fe705d1986448bc6d735bfe00b09550d5

**Comment by Johnnynator** [comment]
@Cogitri https://void.johnnynator.dev/electron/ has now everything I have build so far (also a test repo for everyone who is intrested)

**Comment by shizonic** [comment]
@Johnnynator You are awesome! Thanks a lot. I would adapt it for my current vscode 1.45.0 PR if you like.

**Comment by Johnnynator** [comment]
> @Johnnynator You are awesome! Thanks a lot. I would adapt it for my current vscode 1.45.0 PR if you like.

Feel free to do so.

**Comment by shizonic** [comment]
This includes electron itself ?

**Comment by ericonr** [comment]
Ping?

**Comment by Hierosme** [comment]
Look Microsoft do not like a lot

When i try to install the Python plugins, the installation success but at run i got it message:

```
Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.


  Code: -32603 
```
Like Each time with Microsoft, we make opensource but only for kill our concurents....

may be add the open-vsx repot, it contain a Python support

https://www.gitpod.io/blog/open-vsx


inside ./resources/app/product.json

```
"serviceUrl": "https://open-vsx.org/vscode/gallery",
"itemUrl": "https://open-vsx.org/vscode/item"
```

Hope it can help
