### ISSUE TITLE
Sway using both setuid and elogind

### ISSUE THREAD

**Issue by ii8** [void-linux/void-packages#10594]
### Packages: 
-  *sway-1.0_1*
-  *wlroots-0.5.0_1*

### Expected behavior
Sway should rely on either logind OR setuid

### Actual behavior
suid is set on the sway executable at install
AND
wlroots is compiled with logind enabled

**Comment by CameronNemo** [comment]
I wish there were an easy way to apply hooks for special permissions (caps, setuid/setgid).

**Comment by xtraeme** [comment]
fixed long ago
