### ISSUE TITLE
Package Request: Emby

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#10599]
Name: `Emby`
Description: `Emby brings together your personal videos, music, photos, and live television. (Media Server)`
URL: https://emby.media/about.html
Source: https://github.com/MediaBrowser/Emby
Releases: https://github.com/MediaBrowser/Emby.Releases/archive/

Arch PKGBUILD: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/emby-server

**Comment by CameronNemo** [comment]
There is an open source fork called jelly fin.

**Comment by CameronNemo** [comment]
Jellyfin has fairly sensible Debian packaging [here](https://github.com/jellyfin/jellyfin/tree/master/deployment/debian-package-x64/pkg-src).

**Comment by anarchomoh** [comment]
Have requested Jellyfin already in https://github.com/void-linux/void-packages/issues/6684

**Comment by Anachron** [comment]
I‘ll try to package Emby myself.

**Comment by anarchomoh** [comment]
Thanks Anachron, would love to use open source exclusively and Jellyfin devs are working very rapidly.
