### ISSUE TITLE
Package Request: Tiled

### ISSUE THREAD

**Issue by linkert** [void-linux/void-packages#10595]
https://github.com/bjorn/tiled
https://www.mapeditor.org/

> Tiled is a general purpose tile map editor for all tile-based games, such as RPGs, platformers or Breakout clones.
>
> Tiled is highly flexible. It can be used to create maps of any size, with no restrictions on tile size, or the number of layers or tiles that can be used. Maps, layers, tiles, and objects can all be assigned arbitrary properties. Tiled's map format (TMX) is easy to understand and allows multiple tilesets to be used in any map. Tilesets can be modified at any time.

I'm sure there are a lot of folks that want this in the repos.

**Comment by maxice8** [comment]
Template i stopped working on 

```
# Template file for 'tiled'
pkgname=tiled
version=1.2.3
revision=1
build_style=qmake
hostmakedepends="qt5-host-tools"
makedepends="qt5-devel qt5-declarative-devel zlib-devel"
short_desc="Flexible level editor"
maintainer="maxice8 <thinkabit.ukim@gmail.com>"
license="GPL-2.0-or-later"
homepage="https://www.mapeditor.org/"
distfiles="https://github.com/bjorn/tiled/archive/v${version}.tar.gz"
checksum=4d12cb3d867524dafb19eaee57f505ecfd826d8975fb6f737f1692dd6ac5c003
```

**Comment by HenriDellal** [comment]
Latest version:
```
# Template file for 'tiled'
pkgname=tiled
version=1.8.4
revision=0
build_style=qmake
make_build_args="-nostartfiles"
configure_args="projects.Tiled.useRPaths:false"
hostmakedepends="qt5-host-tools"
makedepends="qt5-devel qt5-declarative-devel zlib-devel"
short_desc="Flexible level editor"
maintainer="Maintainer <maintainer@mail.com>"
license="GPL-2.0-or-later"
homepage="https://www.mapeditor.org/"
distfiles="https://github.com/bjorn/tiled/archive/v${version}.tar.gz"
checksum=60d98f0845ffe967cc6eb75f49a20bd61a06c5e9b5488b3ec1ef7a0737410ebf
```

**Comment by paper42** [comment]
@HenriDellal could you open a PR?

**Comment by HenriDellal** [comment]
@paper42 Sorry, I can't as I don't want to maintain the package.
