### ISSUE TITLE
firefox-66.0.2_2 broken

### ISSUE THREAD

**Issue by DirectorX** [void-linux/void-packages#10597]
### System

* xuname:  
Void 4.19.33_1 x86_64 GenuineIntel uptodate hold rrmFFFFFFFFFFFF

* package: 
    * firefox-66.0.2_2

### Expected behavior

Firefox starts successfully

### Actual behavior
```
 ~  /usr/bin/firefox
XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
/usr/lib/firefox/libxul.so: undefined symbol: FT_Palette_Select
Couldn't load XPCOM.
```

**Comment by jnbr** [comment]
There was a problem in scheduling the rebuild. Should be fixed with 66.0.2_3.
Please re-open if it isn't.

**Comment by AaronM04** [comment]
I am getting a slightly different error with firefox-66.0.3_2:

```
PCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
libvpx.so.5: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

**Comment by jnbr** [comment]
Fix it with reinstalling libvpx5: `xbps-install -f libvpx5`.
See herre for more details: https://github.com/void-linux/void-packages/issues/10013

**Comment by AaronM04** [comment]
That worked. Thank you!
