### ISSUE TITLE
Package Request: Plex Media Server

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#10601]
URL: https://www.plex.tv/
Description: `Plex Media Server`
Release: https://www.plex.tv/media-server-downloads/#plex-media-server

The client is already packaged: https://github.com/void-linux/void-packages/blob/e866a7ee299f80a652219e510a16fd561eb356e4/srcpkgs/plex-media-player/template
Arch PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=plex-media-server

**Comment by Anachron** [comment]
More information on how to get `Plex Media Server` working: https://www.reddit.com/r/voidlinux/comments/b9qmzu/media_server_options/ek8kb34/

**Comment by CameronNemo** [comment]
Is this libre?

**Comment by Anachron** [comment]
No sadly it's not.

**Comment by anarchomoh** [comment]
can I request a re-open? It fails to build from source:
=> ERROR: cannot convert shebang, set python_version
=> ERROR: plex-media-server-1.15.3.876_3: pre-pkg_03-rewrite-python-shebang: 'find "${PKGDESTDIR}" -type f -print0' exited with 1
=> ERROR:   in hook() at common/hooks/pre-pkg/03-rewrite-python-shebang.sh:19
=> ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
=> ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:232
=> ERROR:   in main() at common/xbps-src/libexec/xbps-src-prepkg.sh:47

**Comment by maxice8** [comment]
Open a FTBFS issue
