### ISSUE TITLE
yarn packages does not add yarnpkg alias for yarn

### ISSUE THREAD

**Issue by paldepind** [void-linux/void-packages#10600]
### Expected behavior

The `yarn` packages should add `yarnpkg` as an alias for Yarn. When Yarn is installed from npm or on other distributions a `yarnpkg` alias is included for the `yarn` command. Several programs depend on this alias being available and they currently fail on Void Linux.

For reference, the package for Arch Linux includes the following line to create the alias.

```
ln -s /usr/lib/node_modules/yarn/bin/yarn.js "$pkgdir"/usr/bin/yarnpkg
```

### Actual behavior

The `yarnpkg` alias is not included.

### Steps to reproduce the behavior

1/ Install the `yarn` packages.
2/ The command `yarn` is in path but `yarnpkg` does not exist.

**Comment by paldepind** [comment]
Thanks a lot for the fix @maxice8 :+1:

**Comment by maxice8** [comment]
On Sat, Apr 06, 2019 at 01:20:54AM -0700, Simon Friis Vindum wrote:
> Thanks a lot for the fix @maxice8 :+1: 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/10600#issuecomment-480485621

welcome
