### ISSUE TITLE
Nemo File Manager - Unable to open as root from right click menu

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#10650]
### System

* xuname:  
  Void 4.19.33_1 x86_64 GenuineIntel notuptodate rrmFFFFF
* package:  
  Nemo 4.0.6

### Expected behavior
Open a new window as root user
### Actual behavior
No window launches
### Steps to reproduce the behavior
right click in Nemo normal user window and click 'open as root'

**Comment by maxice8** [comment]
problably a lack of default policykit.

![image](https://user-images.githubusercontent.com/30738253/55676674-40ba8f00-58af-11e9-9ea2-69870fb15c23.png)

**Comment by anarchomoh** [comment]
Not sure how I can set that up. installed polkit and and the result is still the same ...no root window.

**Comment by b1scu1t** [comment]
Do you have a [polkit agent](https://wiki.archlinux.org/index.php/Polkit#Authentication_agents) installed?
Like `polkit-gnome` or `mate-polkit`?

**Comment by anarchomoh** [comment]
Yes, I have polkit-gnome installed.

**Comment by biopsin** [comment]
Is this still a problem with nemo-4.6.5?

**Comment by ericonr** [comment]
I could reproduce with 4.8.x from my PR...

Not sure how to solve this.

**Comment by ericonr** [comment]
OK, I could get it to launch the password prompt by messing with some polkit stuff, but not launch a new instance.

**Comment by biopsin** [comment]
I can't test this, but is polkit-gnome-authentication-agent-1 confirmed running in background?

**Comment by ericonr** [comment]
Yes, since it prompted me for a password. Just need to find out why it doesn't then launch a new nemo instance.
