### ISSUE TITLE
IBus fails to install Python sitelib file

### ISSUE THREAD

**Issue by xelxebar** [void-linux/void-packages#10675]
### System

```
$ xuname
Void 4.19.32_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFFFFFFF1

$ xbps-query -p pkgver ibus
ibus-1.5.20_1
```

### Expected behavior

As far as I can tell, a vanilla install of ibus from source copies the following file:

```
bindings/pygobject/gi/overrides/IBus.py
```

into the relevant Python sitelib directories:

```
${py2_sitelib}/gi/overrides/
${py3_sitelib}/gi/overrides/
```

### Actual behavior

However, the xbps package fails to do this.

### Comments

I stumbled upon this while attempting to package up a couple ibus engines. For reference, the bug report ibus/ibus#2052 is of essentially the same issue. There it claims the problem is how OP's distro packages ibus.

My understanding of automake and ibus is quite slim, but groveling around the Makefiles and macro stuff, it looks like `bindings/pygobject/Makefile.am` controls `IBus.py` installation, which requires `ENABLE_PYTHON2` to be set.

I tried recompiling ibus with `---enable-python2` and `--enable-python-library` set, but to no avail. As a quick and dirty workaround, I tried manually copied over `IBus.py`, and it does get my ibus engines up and running, but I'd really like a proper fix, so I can share the packages.

### Gratia

Anyway, thanks in advance!

**Comment by xelxebar** [comment]
@maxice8
As usual, you rock!

**Comment by maxice8** [comment]
On Sun, Apr 07, 2019 at 11:22:21PM -0700, xelxebar wrote:
> @maxice8
> As usual, you rock!
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/10675#issuecomment-480699241

Welcome

**Comment by xelxebar** [comment]
Just compiled this locally and noticed that only `py2_sitelib` is getting `IBus.py`.

In the resolution to ibus/ibus#2052, the main thrust is that python3 needs it as well. One commenter mentions that the vanilla install does set that up correctly. Is it at all clear how to make that happen? I suppose a manual `vcopy` would also do the trick.
