### ISSUE TITLE
[FTBFS] python-efl

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#10680]
After the update to efl-1.22.0 python-efl-1.21.0 fails to build. There is no update for the latter yet.
```
efl/eo/efl.eo.c: In function '__pyx_pf_3efl_2eo_4event_global_freeze_count_get':
efl/eo/efl.eo.c:1872:36: error: too many arguments to function 'efl_event_global_freeze_count_get'
   __pyx_t_1 = __Pyx_PyInt_From_int(efl_event_global_freeze_count_get(((Eo const *)efl_object_class_get()))); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 74, __pyx_L1_error)
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This may also break (have broken) current enlightenment. I did not verify it, only realized python-efl won't build anymore.

**Comment by DaveMDS** [comment]
Hi, the new python-efl release, matching the efl 1.22 one, will be released tomorrow. Updating should then fix your issue.
regards
