### ISSUE TITLE
clang installation fails

### ISSUE THREAD

**Issue by neoklis** [void-linux/void-packages#10695]
Hi

Tried to install clang and clang-analyzer after updating installation but failed:
`[1208]> sudo xbps-install clang clang-analyzer`
`MISSING: libllvm7-7.0.1_5`
`Transaction aborted due to unresolved dependencies.`
Thanks

Best regards

Neok

**Comment by maxice8** [comment]
https://build.voidlinux.org/waterfall

Please wait

**Comment by Jackojc** [comment]
It seems like it failed?

**Comment by neoklis** [comment]
It wants libllvm7-7.0.1_5 but it is now libllvm7-7.0.1_6
`[1945]> xbps-query -Rs libllvm`
`[-] libllvm3.9-3.9.1_4 Low Level Virtual Machine (3.9.x series) - runtime library`
`[-] libllvm6.0-6.0.1_4 Low Level Virtual Machine (6.0.x series) - runtime library`
`[*] libllvm7-7.0.1_6   Low Level Virtual Machine - runtime library`

**Comment by Jackojc** [comment]
Seems to be working now.

**Comment by jnbr** [comment]
it should work now, reopen of there are still issues

**Comment by neoklis** [comment]
Yes, it works, thanks!
