### ISSUE TITLE
Package request: osu!lazer

### ISSUE THREAD

**Issue by agausmann** [void-linux/void-packages#10776]
Name: osu!lazer

Description: The next version of osu!, a popular rhythm game.

URL: https://osu.ppy.sh

Source: https://github.com/ppy/osu

Releases: https://github.com/ppy/osu/releases

Willing to help develop and maintain.
Blocks on #10773 as a build dependency.

**Comment by maxice8** [comment]
Ping, dependency has been merged.

**Comment by maxice8** [comment]
> Willing to help develop and maintain.

Please, Void is a FOSS project, the only way to get something is working on it, paying someone or convincing someone to work on it.

**Comment by AGausmann** [comment]
Thanks, I've been following the dotnet progress and am still interested in eventually doing this, but this doesn't seem to be in high demand except by myself. Once I have some time to dedicate I will get it done.

**Comment by xythz** [comment]
Would like to see this packaged :)

**Comment by Johnnynator** [comment]
> Would like to see this packaged :)

Probably won't happen any time soon since it requires .NET Core, which is FAR from easy to package. (Without any upstream changes nearly impossible)

**Comment by aquaspy** [comment]
Well, they have a AppImage now, but seems like it requires openssl

**Comment by FirstZero** [comment]
> Well, they have a AppImage now, but seems like it requires openssl

yes, and just like with the .Net Core package the env variable `CLR_OPENSSL_VERSION_OVERRIDE=46` should mae it work

**Comment by autoteelar** [comment]
the appimage works fine for me and i do not have openssl, i think it has to do with this which i have done 

https://www.reddit.com/r/voidlinux/comments/ho2asw/for_those_who_cant_open_osu_lazer_appimage_do_this/

i would love to have this in the void repositories, especially with auto updating and now with peppy getting so close to actually finishing the game and replacing the windows standard client

**Comment by autoteelar** [comment]
> > Would like to see this packaged :)
> 
> Probably won't happen any time soon since it requires .NET Core, which is FAR from easy to package. (Without any upstream changes nearly impossible)

hmm it might work with mono maybe

**Comment by begss** [comment]
I wrote a [custom automation script](https://git.sr.ht/~begs/uso) that builds [osu!](https://github.com/ppy/osu) from source. It includes some workarounds to make osu! work on Musl.
