### ISSUE TITLE
Package request: RethinkDB

### ISSUE THREAD

**Issue by Itamiko** [void-linux/void-packages#10775]
> RethinkDB is the first open-source scalable database built for realtime applications. It exposes a new database access model -- instead of polling for changes, the developer can tell the database to continuously push updated query results to applications in realtime. RethinkDB allows developers to build scalable realtime apps in a fraction of the time with less effort.

[RethinkDb Github](https://github.com/rethinkdb/rethinkdb)

**Comment by maxice8** [comment]
Fails to build with --allow-fetch
