### ISSUE TITLE
Package Request: rtAudio

### ISSUE THREAD

**Issue by eamoc** [void-linux/void-packages#10788]
Name: RtAudio

Description: A set of C++ classes that provide a common API for realtime audio input/output
URL: https://www.music.mcgill.ca/~gary/rtaudio/

Source: https://github.com/thestk/rtaudio

Releases: 
This packages exists in most other distributions and is useful as a dependency in a lot of realtime audio applications

**Comment by eamoc** [comment]
Will help packaging and maintaining if required

**Comment by eamoc** [comment]
So this (will) / (will not) be included then?

**Comment by maxice8** [comment]
https://github.com/void-linux/void-packages/commit/3c7febecc9ba02ce1cc04546a13efabc3b5c689b

**Comment by eamoc** [comment]
Cool :-)
