### ISSUE TITLE
Travis CI builds no longer setting default en_US.UTF-8 locale.

### ISSUE THREAD

**Issue by xelxebar** [void-linux/void-packages#10815]
### Overview

While trying to figure out why my #10764 is failing, I did some digging around, and noticed that the Tavis glibc builds are no longer generating locales. This looks to have begun sometime between #10583 and #10624. On IRC @Duncaen informed me that there was a switch to docker in this time.

I suspect this is symptomatic of a larger issue, the troubleshooting of which is beyond me. However, @Duncaen mentioned to me that the problem might be `common/xbps-src/shutils/chroot.sh` failing to be called.

**Comment by maxice8** [comment]
#10818 is an experimental fix
