### ISSUE TITLE
`hplip` setup fails

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#10814]
### System

* xuname:  
  *Void 5.0.7_1 x86_64 AuthenticAMD uptodate rrrdFFFF*
* package:  
  *hplip*

### Expected behavior
`hp-setup` should be able to download and install specific PPDs for a network connected printer.
In my case `LaserJet Pro 200 color MFP M276n`
### Actual behavior
`hp-setup` downloads and verifies the PPD, then fails to install it printing the following error:
```
Traceback (most recent call last):
  File "/bin/hp-setup", line 426, in <module>
    ppds = cups.getSystemPPDs()
  File "/usr/share/hplip/prnt/cups.py", line 329, in getSystemPPDs
    path = os.path.join(cups_ppd_path, ppd)
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
### Steps to reproduce the behavior

`xbps-install -S hplip`
`sudo hp-setup`

### Also tried
I tried updating to `hplip-3.19.3` yet the error is still the same.

**Comment by jnbr** [comment]
`cups.getSystemPPDs()` requires a `cups/model` directory in one of the entries from
`prop.ppd_search_path = '/usr/share;/usr/local/share;/usr/lib;/usr/local/lib;/usr/libexec;/opt;/usr/lib64'`

I think the `hplip` template should have `make_dirs=/usr/share/cups/model 0755 root root` but I don't have a HP printer to verify.

**Comment by pullmoll** [comment]
I'll try here.

**Comment by pullmoll** [comment]
@jbr thank you. This helped and I can install / upgrade the PPD again.
