### ISSUE TITLE
links -g doesn't work - add `--with-x`

### ISSUE THREAD

**Issue by lpvm** [void-linux/void-packages#1082]
### System
# xuname                                                                                                  
Void 4.16.14_1 x86_64 GenuineIntel uptodate rrmFFFFFFF

* package:  
links-2.16_1

### Expected behavior
`links -g`  should work for a graphical display under X

### Actual behavior
$ links -g http://www.google.com                                                       
Could not initialize any graphics driver. Tried the following drivers:                                                   
fb:                                                                                                                      
Could not get VT mode.

### Steps to reproduce the behavior
just issue the command

It seems that the `--with-x` config option should be enabled.
https://forum.voidlinux.eu/t/browser-links-graphical-mode-error/6251/2

**Comment by newbluemoon** [comment]
I think this behaviour is deliberately, because if configured with `--with-x` I guess a lot of X dependencies were pulled in and this would be contradictory to having a small system without X, but still be able to browse the web.

But perhaps it could be added as a build option?

**Comment by maxice8** [comment]
@newbluemoon i'm willing to merge a off-by-default x11 build_option

**Comment by newbluemoon** [comment]
@maxice8 Ok, I’ll prepare a PR.

**Comment by newbluemoon** [comment]
@maxice8 Done. :)

@lpvm I hope this works for you. :)

**Comment by lpvm** [comment]
I'm only reading this now, my `git pull origin master` didn't get any modification yet.
The option you've taken is that if someone wants the X11 support has to rebuild the package and has a build option for it, correct?  If so, every time there's some modification, a user has to rebuild it.

Another option could be to have two separate packages, a links text only, as it is now, and another fat one with X11 support, just like `vim` and `vim-x11`.  And maybe a third one for the frame buffer support only, although I'm not sure if the number of dependencies justifies this option.
