### ISSUE TITLE
Package Request: DreamChess

### ISSUE THREAD

**Issue by speden** [void-linux/void-packages#1084]
DreamChess is an open source chess game. It comes with its own engine called Dreamer.

Dependencies: CMake, bison, flex, SDL 2.0, SDL_image 2.0, SDL_mixer 2.0, pugixml and GLEW.

https://github.com/dreamchess/dreamchess

Thanks. Speden aka Saptech.

**Comment by steinex** [comment]
Not straightforward. 0.2.0 is the latest stable (from 2015) but that won't build due to mxml in Void too new. 0.2.1-rc2 (also from 2015) builds (the template below uses -rc2) but does not run. Probably also due to an mxml issue.

I won't try this further, if anyone is interested this is what I got.

```
# Template file for 'dreamchess'
pkgname=dreamchess
version=0.2.1
revision=1
wrksrc=${pkgname}-${version}-RC2
#create_wrksrc=yes
#only_for_archs="i686 x86_64"
build_style=gnu-configure
#configure_args=""
#make_build_args=""
#make_install_args=""
#conf_files=""
#make_dirs="/var/log/dir 0755 root root"
hostmakedepends="bison flex"
makedepends="SDL2_image-devel SDL2_mixer-devel glew-devel pugixml-devel mxml-devel"
depends=""
short_desc="A 3D, OpenGL chess game with a moderately strong chess engine"
maintainer="Frank Steinborn <steinex@nognu.de>"
license="GPL-3.0-or-later"
homepage="https://www.dreamchess.org/"
distfiles="https://github.com/${pkgname}/${pkgname}/releases/download/${version}-RC2/${pkgname}-${version}-RC2.tar.gz"
checksum=a26c7281819c2e84525523d13b076301b3746ff06e484642881a9ebe5138dd94
```

**Comment by Johnnynator** [comment]
@steinex You probably have to use SDL instead of SDL2.

**Comment by newbluemoon** [comment]
@Johnnynator is right. Was just about to reply. But also SDL-devel is necessary (needs sdl-config). With those changes I can play the game. ;)

**Comment by steinex** [comment]
Feel free to submit.

**Comment by Anachron** [comment]
This is slightly offtopic but if you are looking for a good chess community/program I would head over to https://lichess.org/
