### ISSUE TITLE
browserpass: is split in multiple repos

### ISSUE THREAD

**Issue by teldra** [void-linux/void-packages#10860]
From the github repo: Browserpass was rewritten from scratch and split in two repositories.
Browser extension: https://github.com/browserpass/browserpass-extension
Native host app: https://github.com/browserpass/browserpass-native

**Comment by Johnnynator** [comment]
resolved with https://github.com/void-linux/void-packages/commit/f2fdfb1dda5c0d27d6def981f730a09837b3f68b
