### ISSUE TITLE
Package Request: bbswitch-dkms

### ISSUE THREAD

**Issue by Dotz0cat** [void-linux/void-packages#10871]
Link to github page:
https://github.com/Bumblebee-Project/bbswitch

**Comment by DirectorX** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/bbswitch/template

https://wiki.voidlinux.org/Bumblebee

Are We already have this in our repo?

**Comment by maxice8** [comment]
Already in the repos
