### ISSUE TITLE
[patchage] fails with a symbol lookup error

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#1088]
### System

* xuname:  Void 4.17.6_1 x86_64 GenuineIntel uptodate r
* package:  patchage-1.0.0_2

### Expected behavior

patchage runs and shows its GUI

### Actual behavior

`patchage: symbol lookup error: patchage: undefined symbol: _ZN4Ganv4PortC2ERNS_6ModuleERKSsbj`

### Steps to reproduce the behavior

Install patchage, invoke patchage

**Comment by axm2** [comment]
I am also having this issue with polybar

**Comment by CameronNemo** [comment]
the symbol with polybar is `_ZN4Json5ValueC1ERKSs`
