### ISSUE TITLE
man 8 nft crashed

### ISSUE THREAD

**Issue by congdanhqx** [void-linux/void-packages#10892]
### System

* xuname:  
  Void 5.0.7_1 x86_64 GenuineIntel uptodate rFFFF

* package:  
  - nftables 0.9.0_3
  - mdocml 1.14.5_1

```
% xbps-alternatives -g man -l
man
 - mdocml (current)
  - man:/usr/bin/mandoc
  - whatis:/usr/bin/mandoc
  - apropos:/usr/bin/mandoc
  - man.1:/usr/share/man/man1/mandoc-man.1
  - whatis.1:/usr/share/man/man1/mandoc-whatis.1
  - apropos.1:/usr/share/man/man1/mandoc-apropos.1
 - man-db
  - man:/usr/bin/mandb-man
  - whatis:/usr/bin/mandb-whatis
  - apropos:/usr/bin/mandb-whatis
  - man.1:/usr/share/man/man1/mandb-man.1
  - whatis.1:/usr/share/man/man1/mandb-whatis.1
  - apropos.1:/usr/share/man/man1/mandb-apropos.1
```

### Expected behavior

- `man 8 nft` should show manual of nft

### Actual behavior

 - `man 8 nft` crashed
 - `mandb-man 8 nft` works correctly

### Steps to reproduce the behavior

     % xbps-alternatives -g man -s mdocml
     % man 8 nft

**Comment by congdanhqx** [comment]
workaround: #10891

**Comment by congdanhqx** [comment]
My quick investigation shows `mdocml` failed to render
empty cells in last row of table.

```
% cat /tmp/test.1
.TS
allbox;
l | l.
T{
x
T}      T{
T}
T{
x
T}      T{
T}
.TE
```

**Comment by xtraeme** [comment]
Hopefully the mandoc devs will find this...

**Comment by Duncaen** [comment]
This crash was mentioned in https://github.com/void-linux/void-packages/issues/9868 and mandoc devs are aware.
