### ISSUE TITLE
LIRC on RPi 3 B+ does not work with IR receivers connected via GPIO

### ISSUE THREAD

**Issue by Leon-Plickat** [void-linux/void-packages#10905]
I tried using a IR receiver connected to the GPIO ports of the Pi, but was unable to get the LIRC driver to work.

I followed the steps described on [this website](http://alexba.in/blog/2013/01/06/setting-up-lirc-on-the-raspberrypi/). Other website describe a similar procedure to get IR via GPIO working, so I believe this is the correct way. As basically all Pi related information on the internet, it assumes one is using Raspbian. However it should still apply to every distribution whichs kernel has the correct driver.

I tried both: Doing exactly as described in the article as well as adapting it to void (meaning things like creating `/etc/modules-load.d/lirc.conf` instead of modifying `/etc/modules`). But `/dev/lirc0` never appeared.

Appearently, the LIRC driver in the kernel needs to patched in order for it to work with GPIO, [as described on the website of the author of mentioned patch](http://aron.ws/projects/lirc_rpi/).

Since someone on Reddit (from where I was referred to here) mentioned that they got LIRC to work with an USB IR receiver on the Pi, I believe that the default LIRC drivers are in voids kernel, however as the user space tools of LIRC are not packaged in void aarch64, I am tempted to believe that the patch is also not applied to the driver.

Is my assumption, that the version of LIRC patched to work with the GPIO ports of the Pi is not included in voids aarch64 kernel, correct? Or am I missing something? And if this is the case, is there any way of getting LIRC to work with a IR receiver connected via GPIO?

**Comment by xtraeme** [comment]
Just find where the changes are and add the patches to the rpi-kernel pkg.

**Comment by Anachron** [comment]
Turns out v4l is used nowadays for IR communication, the package should already be installed (`v4l-utils`).
One needs to add the following options to /boot/config.txt:

```
dtoverlay=gpio-ir,gpio_pin=17
```

Where gpio_pin is the Pin used for communication with the IR. 

Example: https://miro.medium.com/max/1400/1*A2gpUDLyOx903dVUStHFTA.jpeg

I've connected mine to the GPIO number 17, so that's what I enabled.
Reboot, then you have /dev/lirc0 and can run `# rc-keytable` and receive:

```
# LC_ALL=C ir-keytable
Found /sys/class/rc/rc1/ with:
        Name: vc4
        Driver: cec
        Default keymap: rc-cec
        Input device: /dev/input/event1
        Supported kernel protocols: cec
        Enabled kernel protocols: cec
        bus: 30, vendor/product: 0000:0000, version: 0x0001
        Repeat delay = 0 ms, repeat period = 125 ms
Found /sys/class/rc/rc0/ with:
        Name: gpio_ir_recv
        Driver: gpio_ir_recv
        Default keymap: rc-rc6-mce
        Input device: /dev/input/event0
        LIRC device: /dev/lirc0
        Supported kernel protocols: lirc rc-5 rc-5-sz jvc sony nec sanyo mce_kbd rc-6 sharp xmp imon
        Enabled kernel protocols: lirc rc-5 rc-5-sz jvc sony nec sanyo mce_kbd rc-6 sharp xmp imon
        bus: 25, vendor/product: 0001:0001, version: 0x0100
        Repeat delay = 500 ms, repeat period = 125 ms
```

Now you can test your remote via `sudo ir-keytable -c -p all -t`.

**Comment by zdykstra** [comment]
I'm a bit late here, but I've started packaging `lirc` in https://github.com/zdykstra/void-packages/tree/lirc/srcpkgs/lirc . I've gone this route because the remote I want to use is unsupported by the devinput layer, so I had to create a custom profile with `irrecord`.  The package has only been tested on `x86_64`.

**Comment by Anachron** [comment]
@zdykstra are you saying that even with a custom keymap your device cannot be used?
I'm curious now, what type of device are you using?

Hint for the googlers:
`/usr/lib/udev/rc_keymaps/` is the new path to the `rc_keymap`s now.

**Comment by zdykstra** [comment]
Much to my disappointment, that's right.  The remote doesn't speak any of the IR protocols that the devinput layer supports.

`ir-keytable -v -t -p rc-5,rc-5-sz,jvc,sony,nec,sanyo,mce_kbd,rc-6,sharp,xmp,imon,rc-mm`

I had to use LIRC to make a custom remote protocol, where it can discover the gaps between pulses, how they're terminated, etc. It's a remote for a piece of stereo equipment.
