### ISSUE TITLE
aqemu: v0.9.3 released from TBK's fork

### ISSUE THREAD

**Issue by go2null** [void-linux/void-packages#11056]
### System

* xuname:  
  `Void 4.19.34_1 x86_64 GenuineIntel uptodate rrFFF`
* package:  
  `aqemu-0.9.2_1`

### Expected behavior

Running an image should work.

### Actual behavior

Get following errors
```
Error #1
(qemu-system-x86_64:5189): dbind-WARNING **: 06:53:52.966: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken. 

Error #2
qemu-system-x86_64: Invalid parameter 'vlan' 
```

The image does not run.

### Steps to reproduce the behavior

1. Create an image
2. Run the image

### Notes

The [original](https://github.com/tobimensch/aqemu) repo has stalled since 2017.  KBH has [forked](https://github.com/TBK/aqemu) the repo and has just released [v0.9.3.](https://github.com/TBK/aqemu/releases/tag/v0.9.3)

**Comment by flexibeast** [comment]
i'd be happy to make the packaging changes necessary to use TBK's fork, as the `Invalid parameter 'vlan'` issue with the currently-packaged version makes it unusable for me.

i just cloned [TBK's repo](https://github.com/TBK/aqemu) and compiled, and was able to successfully use the resulting `aqemu` binary to start a VM .

Is/are there any reason(s) to not use TBK's fork for the `aqemu` package?

**Comment by flexibeast** [comment]
(cc: @xtraeme as package maintainer.)

Update: i've just modified the `aqemu` template to use the current release of TBK's fork, and was able to compile, install and run it successfully.

If there are no reasons to not use TBK's fork as the Void `aqemu` package, i can submit a PR
containing the relevant template changes.

**Comment by flexibeast** [comment]
i've just found one potential reason to not use TBK's fork: TBK hasn't enabled GitHub's "Issues" functionality for that repo.

@TBK: Is your fork something you're willing and able to provide user support for? (Fair enough if not!)

**Comment by ericonr** [comment]
The switch happened.
