### ISSUE TITLE
nvidia-dkms broken for 32bit

### ISSUE THREAD

**Issue by ruegerjr** [void-linux/void-packages#1108]
### System

* xuname:  
Void 4.17.6_1 i686 GenuineIntel uptodate rFF
* package:  
nvidia(-dkms) 390.67_1

### Expected behavior
Successful install of nvidia kernel modules
### Actual behavior
Failure to install

**Comment by ruegerjr** [comment]
Nvidia does not provide uvm submodule for its 32-bit drivers, and I suspect has not for 2 years or more?  Therefore the dkms.conf provided in Void package, which includes uvm submodule, breaks the installation of nvidia-dkms for i686 or i686-musl.

Proposed solutions:
<1> Eliminate support for i686 and i686-musl in Void nvidia package since it is broken (less preferred)

<2> Split nvidia package, providing a dkms.conf without uvm for i686 and i686-musl.

<3> Maintain one package with a conditional to choose installation of one of two different dkms.conf versions depending on $ARCH.

**Comment by Hoshpak** [comment]
fixed by #1938
