### ISSUE TITLE
Update Request: pgadmin

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#11082]
### System

* xuname:  
Void 4.19.34_1 x86_64 GenuineIntel uptodate rrrmFFFFFF
* package:  
pgadmin3

### Expected behavior
pgadmin to be on a more recent version ([4.5](https://www.pgadmin.org/docs/pgadmin4/dev/release_notes_4_5.html)).

### Actual behavior
pgadmin is still on version 3.

### Steps to reproduce the behavior
xbps-install pgadmin3

**Comment by Anachron** [comment]
@maxice8 when I update the package can I name it to pgadmin and make it conflict with pgadmin3? I'm not sure why we need a version number in the package name.

**Comment by maxice8** [comment]
On Thu, Apr 18, 2019 at 08:57:08AM +0000, Anachron wrote:
> @maxice8 when I update the package can I name it to pgadmin and make it conflict with pgadmin3? I'm not sure why we need a version number in the package name.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/11082#issuecomment-484415278

needs version number if you want to provide multiple versions of pgadmin

**Comment by Anachron** [comment]
I'd rather not have multiple version numbers but I'm also not sure whether we want to break peoples installation like this.

**Comment by maxice8** [comment]
On Thu, Apr 18, 2019 at 02:01:28AM -0700, Anachron wrote:
> I'd rather not have multiple version numbers but I'm also not sure whether we want to break peoples installation like this. 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/11082#issuecomment-484416676

pgadmin3 installs stuff in /usr/share/pgadmin3 and /usr/bin/pgadmin3

pgadmin4 does away with versioned directories for contents ?

**Comment by Anachron** [comment]
based on `pkg/pip/build.sh` it installs stuff to a version specific folder as well. Ok, I'll create another package for `pgadmin4` but it`s quite bad because `pgadmin` keeps getting a new major version yearly.

**Comment by maxice8** [comment]
On Thu, Apr 18, 2019 at 02:13:37AM -0700, Anachron wrote:
> based on `pkg/pip/build.sh` it installs stuff to a version specific folder as well. Ok, I'll create another package for `pgadmin4` but it`s quite bad because `pgadmin` keeps getting a new major version yearly.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/11082#issuecomment-484420567

Sounds like an yearly chore

**Comment by Anachron** [comment]
I'm about to package `pgadmin4` right now but I'm having trouble because a lot has changed since `pgadmin3`.

The new app is written in Python using `flask` and has quite a lot of dependencies where many of them are not packaged: https://github.com/postgres/pgadmin4/blob/master/requirements.txt

Not packaged:
```
Flask-Gravatar
Flask-HTMLmin
Flask-Mail
Flask-Migrate
Flask-Paranoid
Flask-Principal
Flask-Security
Flask-SQLAlchemy
htmlmin
speaklater
sshtunnel
```

Do I have to package all of  them to be able to package `pgadmin4`? I'm asking myself why we don't have a system to list python packages as deps (like `python_depends`) and those will be installed from `pip` automatically?

**Comment by damadmai** [comment]
I already tried to package it but could not finish it:
https://github.com/damadmai/void-packages/commit/ec6f9d64369a22f2a2f3236405cca0ee6971ddad

**Comment by Anachron** [comment]
Closing this as I currently have no interest in the new `pgadmin` rewrite. It's terrible.
