### ISSUE TITLE
Package Request: nvidia-docker

### ISSUE THREAD

**Issue by voidlinux4life** [void-linux/void-packages#11084]
https://github.com/NVIDIA/nvidia-docker

NVIDIA designed NVIDIA-Docker in 2016 to enable portability in Docker images that leverage NVIDIA GPUs. It allowed driver agnostic CUDA images and provided a Docker command line wrapper that mounted the user mode components of the driver and the GPU device files into the container at launch.

https://devblogs.nvidia.com/gpu-containers-runtime/

The list of prerequisites for running nvidia-docker 2.0 is described below.
For information on how to install Docker for your Linux distribution, please refer to the Docker documentation.
- GNU/Linux x86_64 with kernel version > 3.10
- Docker >= 1.12
- NVIDIA GPU with Architecture > Fermi (2.1)
- NVIDIA drivers ~= 361.93 (untested on older versions)

https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)

**Comment by nuxion** [comment]
Hi! I tried this branch to install `nvidia-docker` package. It was succesfully installed but when I run the basic test command:
`docker run --gpus all nvidia/cuda:12.0-base nvidia-smi` 
it's fail with:
```
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container: context canceled
```
I don't have any problem running nvidia-smi outside docker context:
```
nvidia-smi
Sun May  1 16:29:02 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:03:00.0  On |                  N/A |
|  0%   49C    P0    32W / 120W |    290MiB /  6144MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       989      G   /usr/libexec/Xorg                 157MiB |
|    0   N/A  N/A      4028      G   firefox                           120MiB |
|    0   N/A  N/A      4759      G   alacritty                           8MiB |
```
I tested different versions of nvidia/cuda image (9, 10 and 11) , none of them worked. Any idea or sugestion? Thanks in advance for making this package available.
