### ISSUE TITLE
Package Request: OpenSnitch

### ISSUE THREAD

**Issue by PrinceKael** [void-linux/void-packages#11093]
OpenSnitch is a GNU/Linux port of the Little Snitch application firewall from Mac.

A demonstration video of OpenSnitch is available: https://invidio.us/watch?v=UjRYdusvXik

Official Site: https://www.opensnitch.io/
Github: https://github.com/evilsocket/opensnitch/

**Comment by maxice8** [comment]
Homepage is dead, has no releases.
