### ISSUE TITLE
ruler-0.1.0_1 gives me 'free(): invalid pointer', exit code 134 

### ISSUE THREAD

**Issue by paoloschi** [void-linux/void-packages#11118]
### System

* xuname:  
  Void 5.0.6_1 x86_64 GenuineIntel notuptodate rFFF
* package:  
  ruler-0.1.0_1

### Expected behavior
_ruler_ is a daemon that I plan to run from ~/.xinitrc

    ruler &

### Actual behavior
Started the X session, I found that I did not have a _ruler_ process running.
When executed in the terminal, _ruler_ immediately exits with error 134 printing:
```
$ ruler 
free(): invalid pointer
Annullato
```

### Steps to reproduce the behavior
_ruler_ man says:

> ruler reads its configuration file from $XDG_CONFIG_HOME/ruler/rulerrc
> by default, or from the command line if specified. If $XDG_CONFIG_HOME
> is not defined, $HOME/.config/ruler/rulerrc is used.

so, as a starting point, I downloaded and saved the example configuration
https://raw.githubusercontent.com/tudurom/ruler/master/rulerrc
as `$HOME/.config/ruler/rulerrc`
at this point by executing _ruler_ I only get the above error

**Comment by maxice8** [comment]
We believe this has been fixed with ruler-0.1.0_2
