### ISSUE TITLE
povray: crash with "illegal instruction"

### ISSUE THREAD

**Issue by DBLouis** [void-linux/void-packages#11125]
### System

* xuname:  
  *Void 4.19.35_1 x86_64 GenuineIntel uptodate F*
* package:  
  *povray-3.7.0.8_3*

### Expected behavior
```
$ povray
...doing stuff...
```
### Actual behavior
```
$ povray
Illegal instruction
```
### Steps to reproduce the behavior
Install povray and run it with or without parameters

**Comment by DBLouis** [comment]
Running with valgrind works

**Comment by maxice8** [comment]
Works here on x86_64

**Comment by DBLouis** [comment]
I have a ivy bridge i5-3210M

**Comment by maxice8** [comment]
povray passes -march=native
