### ISSUE TITLE
Package Request: DockSTARTer

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#11145]
DockSTARTer helps you get started with home server apps running in Docker. https://dockstarter.com/
The github website is: 
https://github.com/GhostWriters/DockSTARTer
thanks!

**Comment by Anachron** [comment]
This is just a collection of terribly ineffective shell scripts. I think one better sets up docker without these from the official docs.

**Comment by anarchomoh** [comment]
Ok, thanks for reviewing. I will withdraw it.
