### ISSUE TITLE
Chromium fails to render any page after MUSL update

### ISSUE THREAD

**Issue by Vintodrimmer** [void-linux/void-packages#11149]
### System

* xuname:  
 *Void 5.0.7-chrysalis x86_64-musl GenuineIntel uptodate rFFF*
* package:  
  *chromium-72.0.3626.121_1*
  *musl-1.1.22_1*

### Expected behavior
Being able to use browser as usual

### Actual behavior
"Aw, Snap" for any page, including settings and all others.
All the plugins crash.
Following console output:
```
[3362:3362:0419/093750.620973:ERROR:browser_dm_token_storage_linux.cc(101)] Error: /etc/machine-id contains 0 characters (32 were expected).
[3362:3402:0419/093750.660591:ERROR:bus.cc(396)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[3396:3396:0419/093750.699017:ERROR:vaapi_wrapper.cc(324)] vaInitialize failed: unknown libva error
[3396:3396:0419/093750.746183:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0324
Received signal 11 SEGV_MAPERR 000000010144
  r8: fefefefefefefeff  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000034
 r12: 00005630b05ceae4 r13: 00007ffc1deda0c0 r14: 00007ffc1ded9ff8 r15: 00005630b06463a0
  di: 0000000000000000  si: 00007ffc1ded9ea0  bp: 00007ffc1ded9fd0  bx: 0000000000000144
  dx: 000000000000006d  ax: 0000000000010000  cx: 0000000000010144  sp: 00007ffc1ded9fc0
  ip: 00005630a9b2e172 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000010144
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[3362:3373:0419/093750.850498:ERROR:service_manager_context.cc(291)] Attempting to run unsupported native service: /usr/lib/chromium/chrome_renderer.service
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0324
Received signal 11 SEGV_MAPERR 000000010144
  r8: fefefefefefefeff  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000034
 r12: 00005630b05ceae4 r13: 00007ffc1deda0c0 r14: 00007ffc1ded9ff8 r15: 00005630b0646240
  di: 0000000000000000  si: 00007ffc1ded9ea0  bp: 00007ffc1ded9fd0  bx: 0000000000000144
  dx: 000000000000006d  ax: 0000000000010000  cx: 0000000000010144  sp: 00007ffc1ded9fc0
  ip: 00005630a9b2e172 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000010144
[end of stack trace]
Calling _exit(1). Core file will not be generated.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0324
Received signal 11 SEGV_MAPERR 000000010144
  r8: fefefefefefefeff  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000034
 r12: 00005630b05ceae4 r13: 00007ffc1deda0c0 r14: 00007ffc1ded9ff8 r15: 00005630b06462c0
  di: 0000000000000000  si: 00007ffc1ded9ea0  bp: 00007ffc1ded9fd0  bx: 0000000000000144
  dx: 000000000000006d  ax: 0000000000010000  cx: 0000000000010144  sp: 00007ffc1ded9fc0
  ip: 00005630a9b2e172 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000010144
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

### Steps to reproduce the behavior
1. Update musl to 1.1.22
2. Launch Chromium
![2019-04-19-09:42:30-screenshot](https://user-images.githubusercontent.com/13390601/56413470-e4c91080-6287-11e9-9b23-85a48ad46345.png)

I have the same issue on another machine that uses everything vanilla, such as default kernel and full `base-system` as it's base.
Clearing cache and settings didn't help.
Rebuilding it with `xbps-src` didn't help either.
Somewhat similar behaviour also appears on firefox, where launching a YouTube video crashes the page, but I'm not sure it's related.

**Comment by monbZ** [comment]
Same happened to me today. I use Icecat and almost all of my tabs crashed. Installed chromium to see if that was Icecat problem but was same as on screenshots @Vintodrimmer. I had to reboot to windows and search for solution.
I was in disabled JS state (Icecat options and had 30-40 open tabs) mostly youtube but thru invidio.us which doesn't need JS to run. On first try thought it was JS problem or GNULibre JS blocker (non-free JS blocker).

**Comment by jnbr** [comment]
Musl started to use `SYS_membarrier`. This isn't covered by the chromium sandbox yet.

**Comment by botcoder** [comment]
On firefox, file:/// view was notably broken, but it is all fixed now with the revert on bc0dbb230d.

**Comment by jnbr** [comment]
This was worked around by reverting musl (bc0dbb230df1bdc282d54f4ca97e54db3de7ad5a).
Real fixes are in ead8adf51cf57e3258019a6dbb61154b47b685e8 and 69a2cf27191d101d77a97fe151f2e39421fab348.

**Comment by dm17** [comment]
@Vintodrimmer @jnbr Is this recurring for you? Only happening for me in chromium and the chromium devs said to use the debug symbols, which we don't have for on musl... Curious about your experience.

**Comment by jnbr** [comment]
@dm17 I'm not using it currently but in any case, your problem is very likely unrelated to this issue.
I recommend to open a new issue and provide more details, including everything the issue template requires and any console output from chromium, like it was done for this issue.
