### ISSUE TITLE
webki2gtk: FTBFS on i686 requires SSE2

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#11162]
webkit2gtk now requires SSE2 support and thus fails to build on i686. Since SSE2 support was introduced with the Pentium 4 and I think the current i686 baseline is the Pentium Pro architecture, it is not currently supported.

Since webkit2gtk is an important package for the Gnome desktop, this means many packages will be broken on i686 sooner or later. I don't think patching the package to build without SSE2 would be feasible so I see three options:

1) Remove the package and all revdeps on i686, the architecture is on its way out and not worth the effort (note: this will also mean fewer 32bit packages, I don't know if it would affect anything that is currently used)
2) Raise the i686 baseline, possibly up to the Pentium 4, most CPUs running i686 today will support the extensions as they are either "modern" 32 bit CPUs (like the Intel Atoms) or in fact 64 bit CPUs running a 32 bit OS. This would however break Void for people running it on older CPUs.
3) Enable SSE2 just for this package. This would break webkit2gtk and all revdeps for people using older CPUs while still allowing them to use the base system along with the packages that don't depend on webkit2gtk which would be really ugly as well.

**Comment by Cogitri** [comment]
> Raise the i686 baseline, possibly up to the Pentium 4, most CPUs running i686 today will support the extensions as they are either "modern" 32 bit CPUs (like the Intel Atoms) or in fact 64 bit CPUs running a 32 bit OS. This would however break Void for people running it on older CPUs.

Sounds good to me, Fedora did the same in Fedora 29 and other distros already phase out i686.

**Comment by Cogitri** [comment]
FWIW setting `-DHAVE_SSE2_EXTENSIONS` does 3. (breaks runtime for sse2 but fixes build)

**Comment by Cogitri** [comment]
I think we can just enable sse2 for webkit2gtk, it depends on gst-plugins-base1 which is built with sse2 anyway.

**Comment by Hoshpak** [comment]
In this case feel free to PR. I would still like to continue the discussion if should we keep the current (base works, some packages most likely broken on older CPUs) state though. @void-linux/pkg-committers

**Comment by Hoshpak** [comment]
Btw I forgot to mention that there is of course a fourth option but I think it would be more effort than it's really worth since it would require another builder: Remove the packages that require SSE2 from i686 and keep it at the Pentium Pro base level. Create a new architecture at the Pentium 4 base level and offer it as an option for people using CPUs that support it.

**Comment by Cogitri** [comment]
4) seems like a lot of work with only a very, very limited set of people who'd use it.
