### ISSUE TITLE
Improve vsed performance?

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#11238]
The commit https://github.com/void-linux/void-packages/commit/673504e52457b17bc9e8c0a3fefe3eae10d19d60 introduces vsed and a way how to recognize non-working or not-working-anymore issues with seds. 

The way this is currently handled is that for each and every sed there will be one call to sha256sum before and after each regex on each file. 

Since the vsed script does not error out on issues I suggest to once call sha256sum for all files before and after each regex and then use the diff of those to generate files not modified. Not sure how much faster this is but I believe it could be quite a bit depending on how excessive vsed is used.

**Comment by maxice8** [comment]
That is by design to know exactly which regex stops working at whatever file.

**Comment by Anachron** [comment]
You will still have this information when you check all files before and after each regex. You just diff it at another time for all files.

**Comment by Anachron** [comment]
Should be solved by https://github.com/void-linux/void-packages/commit/bbce69f036a3553380ce0cf14baee44d872d58d1
