### ISSUE TITLE
Proposal: use SPDX License Expressions

### ISSUE THREAD

**Issue by Piraty** [void-linux/void-packages#11240]
At times it happens that a piece of packaged software has more that a single license or the users can choose between licenses.
As is, Void Linux uses `,` to enumerate multiple licenses in the `license=` field in package templates, but that's not accurate.
Since SPDX identifiers are enforced for +1y now whenever templates are changed or added, i propose Void  complies to ~the full~ the SPDX standard even more and enforces the use of [SPDX License Expressions](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60) (including `AND` and `OR`).

Full spec: https://spdx.org/spdx-specification-21-web-version

**Comment by Anachron** [comment]
The ... full ... spec?

Not sure about you but I‘ve skipped over you and saw tons and tons of stuff we don‘t really need/want and/or can easily add to xbps.

I suggest maybe adding the AND & OR stuff but complying to the full spec looks overkill.

**Comment by jnbr** [comment]
What would be the benefit of figuring out the exact license for every package?
This looks like a lot of work to me.
IMO, we should be only as specific as necessary to comply with upstream licenses and spend remaining time on technical issues.

Of course, if upstream provides a SPDX license expression, there is nothing wrong with using it.

**Comment by Piraty** [comment]
thanks @Anachron , full spec is indeed overkill. My proposal only relates to license syntax.

@jnbr: obvious benefit is a better distinction in case a template lists 4 SPDX identifiers but it's unclear what conditions exist.

@maxice8: ping
