### ISSUE TITLE
godot-template is missing

### ISSUE THREAD

**Issue by kartikynwa** [void-linux/void-packages#11241]
[Install message](https://github.com/void-linux/void-packages/blob/master/srcpkgs/godot/INSTALL.msg) from the package `godot`:

```
If you want to export your games, you should either
install godot-templates or download it from
godotengine.org . If godot-template should not be 
available, just open an issue on GitHub.
```

**Comment by codingHahn** [comment]
That is an old message. I think I removed it for 3.0, but somehow it slipped back in when somebody updated for 3.1. In the meantime, you can install the export templates through Godot directly. You can find it in the "Editor" submenu

**Comment by kartikynwa** [comment]
Looks like it can be closed then right?
