### ISSUE TITLE
Package Request: Tianocore/OVMF

### ISSUE THREAD

**Issue by jcgruenhage** [void-linux/void-packages#11243]
For UEFI support in virtual machines, we need OVMF. More info at https://github.com/tianocore/tianocore.github.io/wiki/OVMF

**Comment by teldra** [comment]
solved by #11392

**Comment by concatime** [comment]
Please close this issue.

**Comment by hartwork** [comment]
It seem like #11392 has not been merged — correct? @jcgruenhage If that's true, please re-open this issue so that https://github.com/hartwork/grub2-theme-preview has a chance to work on EFI hardware running Void Linux (while it already works fine on Gentoo, Arch, Debian, Fedora). Thank you!

**Comment by Animeshz** [comment]
@hartwork The qemu seems to include all the necessary files for UEFI firmware to boot, can you please review it? https://github.com/void-linux/void-packages/pull/29074#issuecomment-1009308697

**Comment by hartwork** [comment]
@Animeshz `/usr/share/qemu/edk2-x86_64-code.fd` looks like it could be the right file but I don't be able to test this myself economically with an installation of Void. If someone could confirm that `G2TP_OVMF_IMAGE=/usr/share/qemu/edk2-x86_64-code.fd grub2-theme-preview [..]` works on Void in practice and without it it doesn't, I can add that patch to the auto-detection at https://github.com/hartwork/grub2-theme-preview/blob/master/grub2_theme_preview/__main__.py#L375-L384 for Void.

**Comment by Animeshz** [comment]
@hartwork yeah it does work, though I had to introduce some changes, namely,

```diff
diff --git a/grub2_theme_preview/__main__.py b/grub2_theme_preview/__main__.py
index 15c31b1..d40ecaa 100644
--- a/grub2_theme_preview/__main__.py
+++ b/grub2_theme_preview/__main__.py
@@ -525,8 +525,8 @@ def _inner_main(options):
                     run_command.append('-full-screen')
                 if is_efi_host:
                     run_command += [
-                        '-bios',
-                        omvf_image_path,
+                        '-drive',
+                        'if=pflash,format=raw,file=' + omvf_image_path
                     ]
 
                 print('INFO: Please give GRUB a moment to show up in QEMU...')
```

With the old `-bios` option, it was `qemu: could not load PC BIOS '/usr/share/qemu/edk2-x86_64-code.fd'`.

I believe I found this format of specifying uefi image from [this article](https://krinkinmu.github.io/2020/10/11/efi-getting-started.html).
