### ISSUE TITLE
Package Request: Tautulli

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#11267]
Github Website: 
https://github.com/Tautulli/Tautulli
Website:
https://tautulli.com/

Thanks!

**Comment by Anachron** [comment]
Are you using the plex-media-server package?

I‘ll try to package this once I‘m back from Holiday. (this weekend)

**Comment by anarchomoh** [comment]
Yep, built it from source. 🙂

**Comment by Anachron** [comment]
Awesome. If you have any issues with my template please let me know!

For now I‘ve realized that the service file does not completely work. I‘ll send a fix for it once I‘m back home.
