### ISSUE TITLE
polkit: polkitd segfault on ppc

### ISSUE THREAD

**Issue by stenstorp** [void-linux/void-packages#11274]
### System
  iBook G4 - Mid 2005
  PowerPC G4 7447A 1.42GHz
  1.5GB RAM

* xuname:  
  Void 4.19.36_1 ppc  uptodate FFFF
* packages:  
  polkit-0.115_3
  mozjs52-52.9.0_3

### Expected behavior
  Polkitd running as normal.

### Actual behavior
  Polkitd segfaulting with message in dmesg like:
```
[14144.676236] polkitd[15297]: segfault (11) at 124 nip 37e51fc lr 37e51e0 code 1 in libmozjs-52.so.0[3670000+9a0000]
[14144.676248] polkitd[15297]: code: 48639ef5 9421ffe0 7c0802a6 93a10014 429f0005 93c10018 7fc802a6 93e1001c 
[14144.676256] polkitd[15297]: code: 3fde0086 7c3f0b78 90010024 3bde6ae4 <80630000> 48636781 7c7d1b79 40820024 
```

### Steps to reproduce the behavior
  Build polkit and mozjs52 with xbps-src
  Install polkit
  enable polkitd with `ln -s /etc/sv/polkitd /var/service`

I'm not totally convinced that this is purely a polkit issue as the error message mentions libmozjs.
While I am the main person working on ppc32, I'm a bit out of my depth here and any direction would be appreciated.

**Comment by pullmoll** [comment]
FWIW it's the same with ppc64, which is not yet in the repos, and AFAIR also with ppc64-musl. I wanted to debug the segfault in mozjs52 but got distracted trying to move my changes to void-ppc64.
In short: it seems to be a problem on all powerpc* BE targets mozjs.

**Comment by pullmoll** [comment]
Perhaps this gives some insight: I ran `./xbps-src check mozjs52` on my G5 and this is the (last lines) of the output:
```
/builddir/firefox-52.9.0esr/_virtualenv/bin/python /builddir/firefox-52.9.0esr/config/check_vanilla_allocations.py libjs_static.a
TEST-UNEXPECTED-FAIL | check_vanilla_allocations.py | 'memalign' present in Unified_cpp_memory_mozalloc0.o
check_vanilla_allocations.py: Source lines with allocation calls:
check_vanilla_allocations.py: Accurate in unoptimized builds; jsutil.cpp expected.
check_vanilla_allocations.py: operator new[](unsigned long) called at /builddir/firefox-52.9.0esr/js/src/jsutil.cpp:118
check_vanilla_allocations.py: operator new(unsigned long) called at /builddir/firefox-52.9.0esr/js/src/jsutil.cpp:115
check_vanilla_allocations.py: memalign called at /builddir/firefox-52.9.0esr/js/src/jsutil.cpp:119
check_vanilla_allocations.py: memalign called at /builddir/firefox-52.9.0esr/memory/mozalloc/mozalloc.cpp:176
make[1]: *** [Makefile:53: check-vanilla-allocations] Error 1
make[1]: Leaving directory '/builddir/firefox-52.9.0esr/js/src/js/src'
make: *** [/builddir/firefox-52.9.0esr/config/rules.mk:1504: check] Error 2
```

**Comment by stenstorp** [comment]
I got the same too. Though I wouldn't worry too much about that, I got that same error on x86_64.

**Comment by pullmoll** [comment]
I stumbled across this https://lists.freedesktop.org/archives/polkit-devel/2019-January/000587.html
I don't know anything about polkit and thus if trying to not use mozjs52 (aka SpiderMonkey) at all makes any sense for Void's polkitd. I will however try to use install a patched polkit on my G5 ppc64 setup to see if that makes dbus work without polkitd segfaulting.

**Comment by xtraeme** [comment]
Seriously if we can disable this... ffs

**Comment by pullmoll** [comment]
Now polkitd does no longer crash in mozjs52 but it does not work either.
Entering a lxde session now gives me an error message box which tells me:
```
Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1:
GDbus.Error: org.freedesktop.DBus.Error.Spawn.ChildSignaled:
Process org.freedesktop.PolicyKit1 received signal 5
```
I'm clueless what the js backend for polkit does or needs and what this message means, so trying to get rid of js is perhaps utter nonsense.

**Comment by stenstorp** [comment]
Looks like Solus is using a mozjs-free fork of polkit: https://dev.getsol.us/source/polkit/repository/master/
and have been since 2017. It's version 0.113 and uses a different config syntax but it seems to work well for them. Maybe an option?

**Comment by stenstorp** [comment]
After update to polkit 0.116 using mozjs60, very similar error as the first time but mentions `libpthread-2.29.so` instead of `libmozjs-52.so.0`
