### ISSUE TITLE
Bomi: Errors upon Loading

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#11287]
### System

* xuname:  
Void 4.19.36_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFFFF

* package:  Bomi 0.9.11_12

### Actual behavior
![bomi](https://user-images.githubusercontent.com/32918255/56625104-0ad32400-667f-11e9-9af4-bbbdde805eb7.png)

### Steps to reproduce the behavior
click bomi on menu

**Comment by st3r4g** [comment]
happens on my system too

**Comment by unspecd** [comment]
[Notification: bomi is unmaintained](https://github.com/ashinan/bomi/issues/540).

**Comment by paper42** [comment]
bomi was removed from the repositories
