### ISSUE TITLE
Package Request: Insomnia REST Client

### ISSUE THREAD

**Issue by Itamiko** [void-linux/void-packages#11311]
> Cross-platform HTTP and GraphQL Client https://insomnia.rest

MIT license

[github link](https://github.com/getinsomnia/insomnia)

**Comment by danielmatsumoto** [comment]
pelase

**Comment by caioalonso** [comment]
I'll give this a try.

**Comment by mohad12211** [comment]
what's the status on this? I see that #34646 wasn't reviewed
