### ISSUE TITLE
textosaurus 0.9.12 released on 22 Mar

### ISSUE THREAD

**Issue by paoloschi** [void-linux/void-packages#11319]
I know that reminders about updated packages are not welcome but it's been over a month since this one... 
we currently have `pkgver: textosaurus-0.9.11_1`
https://github.com/martinrotter/textosaurus/releases

**Comment by Hoshpak** [comment]
It's part of our update check: https://alpha.de.repo.voidlinux.org/void-updates/void-updates_2019-04-25.txt

That it hasn't been updated yet either means that no one got around to update it yet or there's no interest in updating it. Feel free to PR an update to the template.

**Comment by Kelvino9** [comment]
textosaurus 0.9.13 is out. Are there chances for this program to be update or should this package better be dropped from the repository?

**Comment by Hoshpak** [comment]
Please create a PR for the update.
