### ISSUE TITLE
 Package Request: Reiser4

### ISSUE THREAD

**Issue by bugcrazy** [void-linux/void-packages#11312]
ReiserFS is obsolete, the new Reiser4 has support for kernel 5 and 4.

https://github.com/edward6/reiser4

https://sourceforge.net/projects/reiser4/files/reiser4-utils/reiser4progs/

https://sourceforge.net/projects/reiser4/files/reiser4-utils/libaal/

https://sourceforge.net/projects/reiser4/files/reiser4-for-linux-5.x/

https://sourceforge.net/projects/reiser4/files/reiser4-for-linux-4.x/

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=reiser4progs

https://wiki.archlinux.org/index.php/Reiser4

**Comment by bobertlo** [comment]
I got templates built for reiser4progs and libaal. Would void accept these even though they require a patched kernel? I didn't think about that before I started.

**Comment by protonesso** [comment]
Don't forget to patch the kernels

**Comment by Hoshpak** [comment]
No, patched kernels won't be accepted. We try to keep our kernel as vanilla as possible.

**Comment by CameronNemo** [comment]
Can reiser4 do dkms?

**Comment by bobertlo** [comment]
Yeah, I was definitely not trying to ask about a patched Kernel as part of Void. I would have no desire to do that even if it were a possibility. Debian/Ubuntu ship the userspace programs and do not provide any kernel builds themselves. The code seems to be maintained and builds on all platforms so I'll submit them if there aren't objections to including these tools.

It looks like the only way to use the drivers is to full on patch the kernel. Rumors are this will not go mainline without a corporate sponsor. The company behind this is now funded solely by DARPA.

**Comment by bugcrazy** [comment]
There are examples of how to build Reiser4 in the vanilla kernel in OpenSuse!

https://build.opensuse.org/package/show/home:doiggl/kernel-reiser4

https://build.opensuse.org/package/show/home:doiggl/kernel-vanilla

https://build.opensuse.org/package/view_file/home:doiggl/kernel-vanilla/kernel-vanilla.spec?expand=1

**Comment by bobertlo** [comment]
I'm closing this since the programs have been merged and it seems to be agreed void will not provide patched kernels.
