### ISSUE TITLE
Package Request: unar

### ISSUE THREAD

**Issue by kozross** [void-linux/void-packages#11339]
Currently, the only way to uncompress RAR archives is to get ``unrar`` from nonfree. [``unar``][1] is an open-source decompressor for RARs, which is packaged on several other distros, and would be really nice to have.

[1]: https://theunarchiver.com/command-line

**Comment by abenson** [comment]
TheUnarchiver doesn't provide a versioned tarball, and I can't easily determine the current version from the zip file. I think that's a blocker to getting this packaged.

**Comment by bobertlo** [comment]
@abenson I found a bitbucket repo with tagged releases from the arch PKGBUILD, and have a pretty much finished a template.

@kozross p7zip is another common open source package that handles RAR btw ;)

**Comment by abenson** [comment]
@bobertlo I just found [that bitbucket](https://bitbucket.org/kosovan/theunarchiver/), too, and it's owned by [the founder of MacPaw](https://tech.eu/profiles/18205/macpaw-ukraine/) so I vote it's pretty legitimate.

**Comment by kozross** [comment]
@bobertlo Thank you so much for packaging this! Additionally, p7zip doesn't handle rar by default - you need to install (what appears to be) a nonfree package to do it, and it doesn't come up for me when I ``xbps-query`` for it.

**Comment by Hoshpak** [comment]
package has been merged.
