### ISSUE TITLE
libguestfs: missing directory /usr/lib/guestfs causes `update-libguestfs-appliance` to fail

### ISSUE THREAD

**Issue by ackalker** [void-linux/void-packages#11345]
### System

* xuname:  
  Void 4.19.36_1 x86_64 GenuineIntel notuptodate rrrrmdFFFFFFFF

* package:  
  libguestfs-1.40.2_1

### Expected behavior

After a fresh installation of this package, running `update-libguestfs-example` as root should download and install a binary guestfs appliance on the system, without generating any errors.

### Actual behavior

```
# update-libguestfs-appliance 

Downloading binary appliance v1.32.0 for libguestfs ... 

--2019-04-26 15:18:17--  http://libguestfs.org/download/binaries/appliance/appliance-1.32.0.tar.xz
Resolving libguestfs.org... 46.43.9.215, 2001:41c9:1:422::215
Connecting to libguestfs.org|46.43.9.215|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://download.libguestfs.org/binaries/appliance/appliance-1.32.0.tar.xz [following]
--2019-04-26 15:18:17--  http://download.libguestfs.org/binaries/appliance/appliance-1.32.0.tar.xz
Resolving download.libguestfs.org... 46.43.9.215, 2001:41c9:1:422::215
Reusing existing connection to libguestfs.org:80.
HTTP request sent, awaiting response... 200 OK
Length: 120487416 (115M) [application/x-xz]
Saving to: ‘appliance-1.32.0.tar.xz’

appliance-1.32.0.tar.xz 100%[==============================>] 114.91M  46.1MB/s    in 2.5s    

2019-04-26 15:18:20 (46.1 MB/s) - ‘appliance-1.32.0.tar.xz’ saved [120487416/120487416]

Checking checksum ... appliance-1.32.0.tar.xz: OK

Extracting binary appliance files to /usr/lib/guestfs:
tar: /usr/lib/guestfs: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```
### Steps to reproduce the behavior

* After installing the package, run `update-libguestfs-appliance` as root.

### Workaround

* Manually creating the directory `/usr/lib/guestfs` and re-running `update-libguestfs-appliance` as root allows it to continue without errors.

**Comment by ackalker** [comment]
I assume that adding `/usr/lib/guestfs` to `make_dirs` in the template could fix this, but perhaps it is better if the files in this directory were preserved when the package is uninstalled. Any ideas on this are very welcome.

**Comment by sgn** [comment]
We don't remove non-empty directories created with `mkdirs` trigger up on uninstallation.

So, `make_dirs="/usr/lib/guestfs 0755 root root"` should be fine.
