### ISSUE TITLE
kmail akonadi

### ISSUE THREAD

**Issue by no2spam** [void-linux/void-packages#11347]
### System

* xuname:  
 Void 4.19.36_1 x86_64 GenuineIntel uptodate rrrmFFFF
* package:  
  kmail 18.12.3_2
  akonadi5 19.04.0_1

### Expected behavior
kmail starts
### Actual behavior
kmail won't start and display error:

    kmail: symbol lookup error: /usr/lib/libKF5AkonadiContact.so.5: undefined symbol: _ZN9KContacts12ContactGroup4dataEj

### Steps to reproduce the behavior
Perform system update sudo xbps-install -Suv and run kmail

###Additional info
**nm output**
    nm -D /usr/lib/libKF5AkonadiContact.so.5 | grep _ZN9KContacts12ContactGroup4dataEj
                 U _ZN9KContacts12ContactGroup4dataEj

**ldd output **

    ldd -r /usr/lib/libKF5AkonadiContact.so.5
        linux-vdso.so.1 (0x00007ffd8ccf9000)
        libKF5AkonadiWidgets.so.5 => /usr/lib/libKF5AkonadiWidgets.so.5 (0x00007f3c83074000)
        libKF5XmlGui.so.5 => /usr/lib/libKF5XmlGui.so.5 (0x00007f3c82f4c000)
        libKF5ContactEditor.so.5 => /usr/lib/libKF5ContactEditor.so.5 (0x00007f3c82eca000)
        libKF5Prison.so.5 => /usr/lib/libKF5Prison.so.5 (0x00007f3c82eb2000)
        libKF5AkonadiCore.so.5 => /usr/lib/libKF5AkonadiCore.so.5 (0x00007f3c82c21000)
        libKF5Contacts.so.5 => /usr/lib/libKF5Contacts.so.5 (0x00007f3c82a86000)
        libKF5KIOWidgets.so.5 => /usr/lib/libKF5KIOWidgets.so.5 (0x00007f3c82923000)
        libKF5KIOCore.so.5 => /usr/lib/libKF5KIOCore.so.5 (0x00007f3c8274d000)
        libKF5Mime.so.5 => /usr/lib/libKF5Mime.so.5 (0x00007f3c826ee000)
        libKF5TextWidgets.so.5 => /usr/lib/libKF5TextWidgets.so.5 (0x00007f3c826a5000)
        libKF5IconThemes.so.5 => /usr/lib/libKF5IconThemes.so.5 (0x00007f3c8265f000)
        libKF5ConfigWidgets.so.5 => /usr/lib/libKF5ConfigWidgets.so.5 (0x00007f3c82602000)
        libKF5Codecs.so.5 => /usr/lib/libKF5Codecs.so.5 (0x00007f3c825bf000)
        libKF5DBusAddons.so.5 => /usr/lib/libKF5DBusAddons.so.5 (0x00007f3c825a7000)
        libKF5I18n.so.5 => /usr/lib/libKF5I18n.so.5 (0x00007f3c82554000)
        libKF5CoreAddons.so.5 => /usr/lib/libKF5CoreAddons.so.5 (0x00007f3c824b3000)
        libKF5Completion.so.5 => /usr/lib/libKF5Completion.so.5 (0x00007f3c82474000)
        libKF5WidgetsAddons.so.5 => /usr/lib/libKF5WidgetsAddons.so.5 (0x00007f3c82304000)
        libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007f3c81cab000)
        libKF5ConfigGui.so.5 => /usr/lib/libKF5ConfigGui.so.5 (0x00007f3c81c85000)
        libKF5ConfigCore.so.5 => /usr/lib/libKF5ConfigCore.so.5 (0x00007f3c81c19000)
        libQt5DBus.so.5 => /usr/lib/libQt5DBus.so.5 (0x00007f3c81b82000)
        libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007f3c815f7000)
        libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007f3c810fd000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f3c80ef5000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f3c80edb000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f3c80d1a000)
        libKF5ItemModels.so.5 => /usr/lib/libKF5ItemModels.so.5 (0x00007f3c80cd2000)
        libQt5Sql.so.5 => /usr/lib/libQt5Sql.so.5 (0x00007f3c80c86000)
        libKF5AkonadiPrivate.so.5 => /usr/lib/libKF5AkonadiPrivate.so.5 (0x00007f3c80be4000)
        libKF5WindowSystem.so.5 => /usr/lib/libKF5WindowSystem.so.5 (0x00007f3c80b91000)
        libKF5ItemViews.so.5 => /usr/lib/libKF5ItemViews.so.5 (0x00007f3c80b54000)
        libQt5PrintSupport.so.5 => /usr/lib/libQt5PrintSupport.so.5 (0x00007f3c80add000)
        libKF5Attica.so.5 => /usr/lib/libKF5Attica.so.5 (0x00007f3c80a15000)
        libKF5GlobalAccel.so.5 => /usr/lib/libKF5GlobalAccel.so.5 (0x00007f3c809f1000)
        libQt5Xml.so.5 => /usr/lib/libQt5Xml.so.5 (0x00007f3c809b2000)
        libQt5Network.so.5 => /usr/lib/libQt5Network.so.5 (0x00007f3c80816000)
        libKF5Service.so.5 => /usr/lib/libKF5Service.so.5 (0x00007f3c8075d000)
        libqrencode.so.4 => /usr/lib/libqrencode.so.4 (0x00007f3c80552000)
        libdmtx.so.0 => /usr/lib/libdmtx.so.0 (0x00007f3c8053a000)
        libKF5JobWidgets.so.5 => /usr/lib/libKF5JobWidgets.so.5 (0x00007f3c80510000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f3c803ca000)
        libKF5Crash.so.5 => /usr/lib/libKF5Crash.so.5 (0x00007f3c803bf000)
        libKF5AuthCore.so.5 => /usr/lib/libKF5AuthCore.so.5 (0x00007f3c8039f000)
        libacl.so.1 => /usr/lib/libacl.so.1 (0x00007f3c80196000)
        libKF5SonnetUi.so.5 => /usr/lib/libKF5SonnetUi.so.5 (0x00007f3c80160000)
        libKF5SonnetCore.so.5 => /usr/lib/libKF5SonnetCore.so.5 (0x00007f3c80128000)
        libQt5Svg.so.5 => /usr/lib/libQt5Svg.so.5 (0x00007f3c800d1000)
        libKF5Archive.so.5 => /usr/lib/libKF5Archive.so.5 (0x00007f3c80091000)
        libKF5GuiAddons.so.5 => /usr/lib/libKF5GuiAddons.so.5 (0x00007f3c80072000)
        /lib/ld-linux-x86-64.so.2 (0x00007f3c83225000)
        libQt5X11Extras.so.5 => /usr/lib/libQt5X11Extras.so.5 (0x00007f3c8006b000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f3c80048000)
        libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f3c7fff5000)
        libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f3c7ff7e000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f3c7ff49000)
        libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f3c7fe44000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f3c7fc2b000)
        libicui18n.so.63 => /usr/lib/libicui18n.so.63 (0x00007f3c7f753000)
        libicuuc.so.63 => /usr/lib/libicuuc.so.63 (0x00007f3c7f386000)
        libpcre2-16.so.0 => /usr/lib/libpcre2-16.so.0 (0x00007f3c7f305000)
        libdouble-conversion.so.1 => /usr/lib/libdouble-conversion.so.1 (0x00007f3c7f2ef000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f3c7f2ea000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f3c7f1c3000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f3c7f082000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f3c7f058000)
        libxcb-keysyms.so.1 => /usr/lib/libxcb-keysyms.so.1 (0x00007f3c7f053000)
        libssl.so.46 => /usr/lib/libssl.so.46 (0x00007f3c7f001000)
        libcrypto.so.44 => /usr/lib/libcrypto.so.44 (0x00007f3c7ee28000)
        libattr.so.1 => /usr/lib/libattr.so.1 (0x00007f3c7ec23000)
        libbz2.so.1 => /usr/lib/libbz2.so.1 (0x00007f3c7ea13000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f3c7e7ed000)
        libglapi.so.0 => /usr/lib/libglapi.so.0 (0x00007f3c7e7b9000)
        libdrm.so.2 => /usr/lib/libdrm.so.2 (0x00007f3c7e7a3000)
        libxcb-glx.so.0 => /usr/lib/libxcb-glx.so.0 (0x00007f3c7e786000)
        libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007f3c7e781000)
        libxcb-dri2.so.0 => /usr/lib/libxcb-dri2.so.0 (0x00007f3c7e77a000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f3c7e765000)
        libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x00007f3c7e55f000)
        libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x00007f3c7e558000)
        libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x00007f3c7e352000)
        libxcb-dri3.so.0 => /usr/lib/libxcb-dri3.so.0 (0x00007f3c7e34c000)
        libxcb-present.so.0 => /usr/lib/libxcb-present.so.0 (0x00007f3c7e347000)
        libxcb-sync.so.1 => /usr/lib/libxcb-sync.so.1 (0x00007f3c7e33d000)
        libxshmfence.so.1 => /usr/lib/libxshmfence.so.1 (0x00007f3c7e13a000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f3c7defe000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f3c7de31000)
        libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f3c7de0c000)
        libicudata.so.63 => /usr/lib/libicudata.so.63 (0x00007f3c7c21e000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f3c7c1a8000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f3c7c1a1000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f3c7c199000)
undefined symbol: _ZN9KContacts12ContactGroup4dataEj    (/usr/lib/libKF5AkonadiContact.so.5)
undefined symbol: _ZN9KContacts12ContactGroup16contactReferenceEj       (/usr/lib/libKF5AkonadiContact.so.5)
undefined symbol: _ZNK9KContacts12ContactGroup4dataEj   (/usr/lib/libKF5AkonadiContact.so.5)

**Comment by Johnnynator** [comment]
It should work again after the update to 19.04.0

**Comment by no2spam** [comment]
Yes it's working. Thank you so much!
