### ISSUE TITLE
qbittorent

### ISSUE THREAD

**Issue by jieppu** [void-linux/void-packages#1136]
### System

* xuname:  
  Void 4.17.6_1 x86_64 GenuineIntel notuptodate rrrFFFFF
* package:  
  qbittorent 4.1.1

### Expected behavior
to work
### Actual behavior
crash after few second
### Steps to reproduce the behavior
start it

### output console

Stack trace:
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x7c530  [0x7f8f529fd530]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1fe18b  [0x7f8f52b7f18b]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x167844  [0x7f8f52ae8844]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x15d086  [0x7f8f52ade086]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x16d16b  [0x7f8f52aee16b]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x3039c7  [0x7f8f52c849c7]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1c61b6  [0x7f8f52b471b6]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0xced4f  [0x7f8f52a4fd4f]
  /usr/lib/libpthread.so.0 : ()+0x7568  [0x7f8f50619568]
  /usr/lib/libc.so.6 : clone()+0x3f  [0x7f8f4f9eb52f]
Erreur de segmentation

**Comment by installkari** [comment]
I'm not sure what the core issue was, but removing ~/.local/share/data/qBittorrent/BT_backup got it working once again for me.  This is where your torrent information is kept, so I recommend moving it somewhere case this doesn't work for you.

**Comment by jieppu** [comment]
now i have that

*** Error in `qbittorrent': corrupted size vs. prev_size: 0x00007f8f9400a480 ***


*************************************************************
Please file a bug report at http://bug.qbittorrent.org and provide the following information:

qBittorrent version: v4.1.1

Caught signal: SIGABRT
Stack trace:
  /usr/lib/libc.so.6 : gsignal()+0x110  [0x7f8fc0f36920]
  /usr/lib/libc.so.6 : abort()+0x17d  [0x7f8fc0f37ffd]
  /usr/lib/libc.so.6 : ()+0x769dd  [0x7f8fc0f789dd]
  /usr/lib/libc.so.6 : ()+0x7d06c  [0x7f8fc0f7f06c]
  /usr/lib/libc.so.6 : ()+0x7e444  [0x7f8fc0f80444]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1b85b6  [0x7f8fc41445b6]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1c61b6  [0x7f8fc41521b6]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0xced4f  [0x7f8fc405ad4f]
  /usr/lib/libpthread.so.0 : ()+0x7568  [0x7f8fc1c24568]
  /usr/lib/libc.so.6 : clone()+0x3f  [0x7f8fc0ff652f]
Abandon

**Comment by octoghost** [comment]
#1115

**Comment by dutsky** [comment]
yeah. will be fixed, after libtorrent-rasterbar update and rebuilding qbittorrent

**Comment by jieppu** [comment]
got it
