### ISSUE TITLE
Cross build gir-1.0 install path

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#11367]
Now that cross building with `gobject-introspection` a.k.a. `gir` basically works for all target architectures thanks to @q66 , there is a problem. The resulting `*.gir` files for the `*-devel` subpackages should be installed in `${DESTDIR}/usr/share/gir-1.0`, yet they are installed in `${DESTDIR}/usr/${XBPS_CROSS_TRIPLET}/usr/share/gir-1.0`.

For `polkit` I added a hack to move `gir-1.0` up the path but of course the real fix is elsewhere.

I believe this is a host `${DESTDIR}` or `${PKGDESTDIR}` which is inserted into the install path, and which is wrong for a cross install. If anyone knows where to look for that one I'd be thankful for your help.

**Comment by pullmoll** [comment]
Out of despair I pushed a temporary and ugly workaround: https://github.com/void-linux/void-packages/commit/f7107d38eb07806450ec596d91015d204780f166
There has to be a cleaner way to solve the problem.

**Comment by xtraeme** [comment]
fixed long ago
