### ISSUE TITLE
Enhancement: PCManFM GTK3

### ISSUE THREAD

**Issue by kehak** [void-linux/void-packages#11360]
PCManFM is currently linked against GTK2. For those moving to wayland (sway), GTK2 does not support hi-dpi and results in blurry fonts. Using Thunar isn't as good an alternative as it depends on xfconf, xfce4-panel, dbus and many XFCE libraries.

Using GTK3 can be trivialy set with `./configure --with-gtk=3` instead of `--with-gtk=2`.

I propose we could either:
- Drop GTK2 and make PCManFM use GTK3 by default
- Provide both GTK2 and GTK3 PCManFM packages, like Arch does

* package:  pcmanfm-1.3.1

**Comment by teldra** [comment]
Suggestion: https://github.com/void-linux/void-packages/commit/29ae7c2458ad12b28cb76ca69ffffe06f1ac9f6e

Is this correct? @Gottox

**Comment by Gottox** [comment]
lxpanel links against libfm-gtk.so.4, therefore it needs to be rebuild with gtk3 too.

**Comment by teldra** [comment]
Is it enough, to rebuild lxpanel with gtk3 or do I have to convert all lxde templates with gtk3? It seems to me, as it is mixed in srcpkgs.

**Comment by Gottox** [comment]
It must be converted.

**Comment by teldra** [comment]
Done. Can be closed.
