### ISSUE TITLE
Package Request: glrpt and mlrpt Meteor-M2 LRPT decoders

### ISSUE THREAD

**Issue by neoklis** [void-linux/void-packages#11431]
Hi

Hope I am doing this right ;-)

I recently completed the development of "glrpt" and "mlrpt" which are decoders of LRPT weather images, transmitted by the Russian Meteor-M2 satellite. They quickly became a big success as apparently there are no other similar apps for the purpose, not for Linux anyway. 

I had a lot of requests for support by people who needed help to compile and install these in their computers, and I also had requests to add support for Airspy SDR's. For this purpose Airspy donated an R2 and a Mini and eventually I switched to SoapySDR to have a uniform SDR API.

Well, I am only saying all this because I think its good for Void to include these apps in the xbps repository, as Arch Linux has already done, since I have had reports from interested Windoze users, who installed Linux for the first time so they could use them. I also was told by some that they tried Void Linux but could not run glrpt or mlrpt because (they thought) Void didn't have the necessary dependencies.

I am sure they failed only because of luck of experience, expecting a plug-and-play type of installation, e.g. they did not realize they have to manually install dependencies. For these reasons I am suggesting here that glrpt and mlrpt be included in the Void packages. They are on my websites under the menu:

Weather Imaging->Meteor-M LRPT Receivers 

https://www.qsl.net/5b4az/index.html
http:/www.5b4az.org/index.html 

neoklis

**Comment by pullmoll** [comment]
I tried to package your glrpt and saw your `Makefile.am` contains several things which are broken or plain wrong:
+ You should use `install` instead of `mkdir` and `cp` to create directories in `$(DESTDIR)` and to install documentation and manual pages.
+ You cannot expect `logname` to return anything useful in a chroot which Void uses to build packages. I would even say you should not even try to mess with the building user's files at all. This is nothing a user can expect or would want you to do.

The following patch would adjust that:
```
No messing with "logname" as we build in a chroot with no user
and this is nothing a "make install" should do anyway.
Also use install instead of mkdir and cp.

--- Makefile.am 2018-12-11 08:35:39.000000000 +0100
+++ Makefile.am 2019-05-02 13:10:58.829842728 +0200
@@ -50,21 +50,12 @@
          cp files/$(PACKAGE).png $(DESTDIR)/usr/share/pixmaps/; \
        fi; \
        if !(test -d $(DESTDIR)/usr/share/doc/$(PACKAGE)); then \
-         mkdir $(DESTDIR)/usr/share/doc/$(PACKAGE)/; \
+         install -d -m755 $(DESTDIR)/usr/share/doc/$(PACKAGE); \
        fi; \
-       if test -d doc/; then \
-         cp -r doc/* $(DESTDIR)/usr/share/doc/$(PACKAGE)/; \
-         cp -r doc/$(PACKAGE).1.gz $(DESTDIR)/usr/share/man/man1/; \
-       fi; \
-       if !(test -d /home/`logname`/$(PACKAGE)); then \
-         cp -r $(PACKAGE) /home/`logname`/; \
-       else \
-      echo "\033[1;33mSaving /home/`logname`/$(PACKAGE)/$(PACKAGE).glade to /home/`logname`/$(PACKAGE)/
$(PACKAGE).glade.bak\033[m"; \
-      mv /home/`logname`/$(PACKAGE)/$(PACKAGE).glade /home/`logname`/$(PACKAGE)/$(PACKAGE).glade.bak; \
-         cp $(PACKAGE)/$(PACKAGE).glade /home/`logname`/$(PACKAGE); \
-      echo "\033[1;33mSaving /home/`logname`/$(PACKAGE)/$(PACKAGE)rc to /home/`logname`/$(PACKAGE)/$(PA
CKAGE)rc.bak\033[m"; \
-         mv /home/`logname`/$(PACKAGE)/$(PACKAGE)rc /home/`logname`/$(PACKAGE)/$(PACKAGE)rc.bak; \
-         cp $(PACKAGE)/$(PACKAGE)rc /home/`logname`/$(PACKAGE); \
+       if !(test -d $(DESTDIR)/usr/share/man/man1); then \
+         install -d -m755 $(DESTDIR)/usr/share/man/man1; \
        fi; \
-       chown -R `logname`:`logname` /home/`logname`/$(PACKAGE);
-
+       if test -d doc/; then \
+         install -m644 doc/* $(DESTDIR)/usr/share/doc/$(PACKAGE)/; \
+         install -m644 doc/$(PACKAGE).1.gz $(DESTDIR)/usr/share/man/man1/; \
+       fi;
```
```

**Comment by neoklis** [comment]
OK, thank you for the comments. I taught myself programming so my knowledge on this sort of subject is limited, mainly because I was relying on the old glade-2 to auto prepare the package. I will have a good look and make the changes in a few days, once I finish with chores that accumulated due to a recent operation.

neoklis

**Comment by neoklis** [comment]
For some reason the patch fails and in any case I should not have made this request, so I will close it I think.

Thanks
