### ISSUE TITLE
bind: should be built without seccomp

### ISSUE THREAD

**Issue by lonwillett** [void-linux/void-packages#11436]
### System

* xuname:  Void 5.0.10_1 x86_64-musl GenuineIntel/PV uptodate hold rrnFFFFFF
* package:  bind-9.11.6_1

### Expected behavior
Works
### Actual behavior
I have had repeated issues with bind and seccomp.  The latest...
Message:
2019-04-30T05:57:44.14997 kern.notice: [735346.896514] audit: type=1326 audit(1556603864.148:10): auid=4294967295 uid=800 gid=800 ses=4294967295 pid=17441 comm="named" exe="/usr/bin/named" sig=31 arch=c000003e syscall=302 compat=0 ip=0x7f7283c632c4 code=0x0
Then it fails to work correctly: some threads die, behaviour is erratic.
### Steps to reproduce the behavior
I admit that I have not figured out precisely what the problem is. Possbily related to using musl instead of glibc. However, the problems disappear when I build bind without seccomp support. And when I googled for similar things, I found:
  https://gitlab.isc.org/isc-projects/bind9/issues/93
So it appears to me that there is no real reason to enable the seccomp support in bind. It will be disappearing anyway, and provides little improvement in security.

**Comment by CameronNemo** [comment]
Okay then. Perhaps we can ship AppArmor policy.

**Comment by ericonr** [comment]
It no longer has seccomp.
