### ISSUE TITLE
[Package Request] --pdf-engine for pandoc: xelatex/lualatex/pdflatex

### ISSUE THREAD

**Issue by Kratacoa** [void-linux/void-packages#11430]
It seems to be impossible to convert any files into .pdf given that these tools are unavailable.

**Comment by TeddyDD** [comment]
You have to install some LaTeX distribution like `texlive2018`. It contains everything you need to output PDFs.

**Comment by Bluedrack28** [comment]
I have the same issues with pandoc, I don't have a pdf-engine. Anybody can help ?

**Comment by Kratacoa** [comment]
> I have the same issues with pandoc, I don't have a pdf-engine. Anybody can help ?

Don't know if you're still looking, but it's now documented in the [Void Linux Handbook](https://docs.voidlinux.org/config/texlive.html)

**Comment by shmalebx9** [comment]
Tectonic is in the repos and works fine as a pdf engine.
