### ISSUE TITLE
Package request:  Calamares

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#11440]
[Calamares](https://github.com/calamares/calamares)
When packaged, maybe we could use it as the default installer for Void.

**Comment by Hoshpak** [comment]
The last time something like this was discussed, the general feeling was that we shouldn't add any installers to the repository.

**Comment by Rigwarl88** [comment]
> The last time something like this was discussed, the general feeling was that we shouldn't add any installers to the repository.

Why? Isn't calamares good for the development of this distro ??
