### ISSUE TITLE
KDE Frameworks, Applications and Plasma are outdated

### ISSUE THREAD

**Issue by Sarkasper** [void-linux/void-packages#1145]
https://www.kde.org/announcements/kde-frameworks-5.48.0.php

https://www.kde.org/announcements/announce-applications-18.04.3.php

https://www.kde.org/announcements/plasma-5.13.3.php

**Comment by Hoshpak** [comment]
@Sarkasper feel free to create a PR to update those packages ;-)

**Comment by Chocimier** [comment]
There are PRs already:
https://github.com/void-linux/void-packages/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+18.04.3
https://github.com/void-linux/void-packages/pull/891

**Comment by maxice8** [comment]
Should be fixed, if there are packages that need updating don't be afraid to make a pull request
