### ISSUE TITLE
Flatpak apps take a long time to start

### ISSUE THREAD

**Issue by krathalan** [void-linux/void-packages#11456]
### System

* xuname:  Void 4.19.37_1 x86_64 GenuineIntel uptodate rFF
* package:  flatpak-1.2.4_2

### Expected behavior
Applications installed via flatpak should start just as quickly as applications installed via xbps.

### Actual behavior
Applications installed via flatpak take a long time to start, but once they're open they are responsive. Opening a flatpak from the command line (e.g. `flatpak run org.gnome.eog`) produces a long stall, then an output of:

"F: Can't find a11y bus: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.a11y.Bus': timed out (service_start_timeout=120000ms)

(eog:2): dbind-WARNING \*\*: 20:23:57.015: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown"

Then the app starts. The "long stall" time before opening takes approximately 30 seconds.

The only other instance of this issue I could find was a comment on reddit. https://www.reddit.com/r/voidlinux/comments/anxi8a/void_is_now_listed_on_the_flatpaks_setup_page/efxntqh/

### Steps to reproduce the behavior
1. Install flatpak with `sudo xbps-install -S flatpak` as per [documentation](https://wiki.voidlinux.org/Flatpak).
2. Install any app, e.g. `flatpak install -y flathub org.gnome.eog`
3. Attempt to start it

**Comment by Anachron** [comment]
Is dbus running?

**Comment by krathalan** [comment]
Interestingly I reinstalled Void today (many times) so I could have my drive be encrypted. I no longer have this issue. dbus *is* running.
