### ISSUE TITLE
firefox: toolkit.telemetry.enabled locked to true

### ISSUE THREAD

**Issue by espectalll** [void-linux/void-packages#11493]
[According to Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1422689), Firefox uses `toolkit.telemetry.enabled` to collect "somewhat more information" about a web browser's activity and report it back to Mozilla. It should only be enabled on beta, aurora, and nightly builds, and it's always a locked setting. However, on the stable builds delivered by Void, `toolkit.telemetry.enabled` is set to `true`.

Take into account that data reporting is (theoretically?) disabled because of the build settings, and so Firefox tells the user in `about:preferences`.

**Comment by jnbr** [comment]
Telemtry is disabled (see #11517) for our firefox builds so this is not an issue.

**Comment by espectalll** [comment]
I know it's disabled and I said so. It would tho, at the very least, give peace of mind. I should also check on whenever logs are kept locally when telemetry is disabled.
