### ISSUE TITLE
Missing IceWM-Components to use the full ‘ice-session’-funktions

### ISSUE THREAD

**Issue by sass432** [void-linux/void-packages#11533]
Since the new revice of the icewm-development there are no systray-funktions in the taskbar, configured over ‘startup-shell’ in ./home/USER/.icewm-directory to open gui's like wicd-client, redshift-gtk, volumeicon, ....
The usual void-repository-installation of ‘icewm’ seems to be incomplete.
There are no icetray, icesound or iceicons components in /usr/bin/.

**Comment by pullmoll** [comment]
I'm updating to version 1.5.4 and AFAICT there is no `iceicons` binary. It seems as if `icetray` is actually `icewmtray`. This one is built but not installed by `make install`. I'll add it to the install using xbps-src `vbin ...` command.
For `icesound` there were dependencies missing: `libao-devel`, `libsndfile-devel` and, as a dependecy of this, `alsa-lib-devel`. We don't have `esound` or `esd` packaged. Once the update is there, please report whether it works for you.

**Comment by sass432** [comment]
Thank you, very much,

But now I have the problem:

(==) Using system config directory "usr/share/X11/xorg.conf.d" 
icewmbg: Can’t open display:
:0. X must be running and $DISPLAY set.ng.40.373: redshift-gtk: Fatal IO error 2 
(Datei oder Verzeichnis nicht gefunden) on X server
:0. Gdk-Message: 19:55:16.916: volumeicon: Fatal IO error 2 (Datei oder Verzeichnis nicht gefunden) on X server
:0. spacefm: Fatal IO error 2 (Die Ressource ist zur Zeit nicht verfügbar) on X server
:0. (II) Server terminated successfully (0). Closing log file.

**Comment by sass432** [comment]
Thank you, very much,

But now I have the problem in my boot-report:

`(==) Using system config directory "usr/share/X11/xorg.conf.d"
icewmbg: Can’t open display:
:0. X must be running and $DISPLAY set.ng.40.373: redshift-gtk: Fatal IO error 2
(Datei oder Verzeichnis nicht gefunden) on X server
:0. Gdk-Message: 19:55:16.916: volumeicon: Fatal IO error 2 (Datei oder Verzeichnis nicht gefunden) on X server
:0. spacefm: Fatal IO error 2 (Die Ressource ist zur Zeit nicht verfügbar) on X server
:0. (II) Server terminated successfully (0). Closing log file.
@sass432`

Tray tries to start but I only see black squares instead of tray-icons.

**Comment by pullmoll** [comment]
When quoting console output please use a triple backtick before and after the output.
I don't know what else may be wrong with your system. I tried icewm here and it seems to work when launched from `lxdm`. Do you use a display manager? Which one? If you use `startx` instead, are you sure your `$HOME/.xinitrc` is correct?
Please elaborate on the details of your configuration.
And in any case it seems more of a problem with your setup rather than the package, but I cannot really judge on this because of my lack of experience with window managers like `icewm`.
