### ISSUE TITLE
Package request: Waterfox

### ISSUE THREAD

**Issue by kaidenshi** [void-linux/void-packages#11549]
https://github.com/MrAlex94/Waterfox

I realize that Waterfox was previously submitted and closed, and I read the discussion in the Abrowser request. However, I'd like to point out that Waterfox is not "just another Firefox fork", and that it may be relevant to Void users for two significant reasons. One, the developer has stripped out privacy-invading "features" from Firefox including all telemetry. Two, Waterfox allows the user to continue using legacy plugins. I feel these reasons merit including Waterfox as a package. Thank you for your consideration.

**Comment by jnbr** [comment]
Are there any advantages over icecat which is already packaged?

**Comment by Anachron** [comment]
Please search before opening new feature requests:
https://github.com/void-linux/void-packages/issues/515
https://github.com/void-linux/void-packages/issues/2735

**Comment by Anachron** [comment]
> One, the developer has stripped out privacy-invading "features" from Firefox including all telemetry. 
https://restoreprivacy.com/firefox-privacy/

>Two, Waterfox allows the user to continue using legacy plugins. I feel these reasons merit including Waterfox as a package. Thank you for your consideration.
https://github.com/Rob--W/enablelegacy-firefox-addons

Close? :-D

**Comment by the-maldridge** [comment]
We have a standing moratorium on browsers and a limit of only one firefox per repo per user.  Thank you for your interest, but this will not be dealt with inside the packages repo.  You are of course free to maintain your own local templates for software that does not meet our policies for repo inclusion.

**Comment by kaidenshi** [comment]
I understand, thank you. 

@jnbr Icecat is a no-go for me personally due to LibreJS breaking sites I rely on, but it may be a good fit for other Waterfox users making the move to Void. 

To anyone else who uses Waterfox and came to this issue in a search for the package: It's trivial to run it on Void (or any Linux) by extracting the binary tarball to a sensible place (I use /opt) and symlinking the executable from there to /usr/bin. You'll have to handle creating a .desktop file or otherwise adding it to your WM/DE's menu, and you'll have to stay on top of updates by following the Waterfox blog and manually updating to new releases, but it will work fine otherwise.

**Comment by jnbr** [comment]
It's not that hard to disable LibreJS in Icecat:

![ic](https://user-images.githubusercontent.com/21270245/57372397-d5a5f600-7195-11e9-93e1-0094043537fd.png)
