### ISSUE TITLE
Package Request: next

### ISSUE THREAD

**Issue by transitracer** [void-linux/void-packages#11564]
[next](https://next.atlas.engineer) is a webkit-based browser with emacs-like keybindings and configuration, built on Common Lisp.

As far as I can tell, actually versioned source releases are only made on their [github repository](
https://github.com/atlas-engineer/next/releases) so that would have to be upstream here, because the actual upstream git repo hosted on their site seems to be nothing more than exposing the [filesystem the of the repo](https://source.atlas.engineer/public/next/)

**Comment by transitracer** [comment]
There may be a need to change the package name to something like `next-browser`, as seen with `next-browser-git` in the AUR, as next is a relatively commonplace name and I wouldn't be surprised if another package already existed (if not in the void package repository, in other distributions') and it would probably be best not to cause confusion

**Comment by congdanhqx** [comment]
> As far as I can tell, actually versioned source releases are only made on their [github repository](https://github.com/atlas-engineer/next/releases) so that would have to be upstream here, because the actual upstream git repo hosted on their site seems to be nothing more than exposing the [filesystem the of the repo](https://source.atlas.engineer/public/next/)

The source code is also available on their  site.
Albeit, they don't provide the tar ball release on their site.

The source code on their site must be retrieve with git.
The tagged source code could be taken by the tag.

**Comment by transitracer** [comment]
@congdanhqx I wasn't aware that was a possibility (or at least, a reasonable one) when packaging something. That should be preferred, if that's the case.

**Comment by Duncaen** [comment]
`xbps-src` has no mechanism to cache git clones, using the github archives is preferred.

**Comment by renatoaguiar** [comment]
I have an old WIP branch with the version 1.2.0: https://github.com/renatoaguiar/void-packages/blob/next/srcpkgs/next/template

I remember being able to build and install the package, but the browser was still too unstable. I may try again with latest version when I have some time. Anyway, it is available to anyone who doesn't want to wait :)

**Comment by 0x0f0f0f** [comment]
They release a tarball now. I'll try to build it now.

**Comment by 0x0f0f0f** [comment]
packaged next in #14747

**Comment by 0x0f0f0f** [comment]
can close issue now
