### ISSUE TITLE
VirtualBox: Windows7 guest stopped working

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#11563]
### System

* xuname:  
  *Void 5.0.13_1 x86_64 AuthenticAMD uptodate rrrdFFFFFF*
* package:  
  *virtualbox-ose-6.0.6_1*

### Expected behavior

Being able to to use my years old *.vbox and *.vdi files, or at least be able to boot Win7 installer ISO.

### Actual behavior

Neither my installed Win7 nor the Windows7 installer ISO will work. They print a message about the ACPI being incompatible and stop "to avoid damage to my software". The stop code is 165 (0x000000a5).

### Steps to reproduce the behavior

Try to boot a Win7 installer ISO in VirtualBox 6.0.6 perhaps?

I tried various combinations of # of virtual cores, RAM, PCIIX3 and ICH9 chipsets, accelerator modes. I found no combination that works.

I can use the same *.vdi files in qemu, but of course that invalidates my license because Microsoft thinks this is a different machine. *sigh*

Any ideas or similar reports yet?

**Comment by Hoshpak** [comment]
Possibly related upstream bug report: https://www.virtualbox.org/ticket/18628

**Comment by pullmoll** [comment]
Yeah, seems to be the same problem though the description is a bit scarce.

**Comment by congdanhqx** [comment]
Possibly related to acpica/acpica#462

**Comment by pullmoll** [comment]
Oh, yes. Thanks for the pointer. I'll give it a try.

**Comment by congdanhqx** [comment]
On May 11, 2019 5:31:26 PM UTC, "Jürgen Buchmüller" <notifications@github.com> wrote:
>Oh, yes. Thanks for the pointer. I'll give it a try.

The linked pull request works for me. I think it's worth a try.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pullmoll** [comment]
Solved and merged the acpica update.
