### ISSUE TITLE
qtcreator-4.9 language server support plugin

### ISSUE THREAD

**Issue by basiliscos** [void-linux/void-packages#11607]
### System

* xuname:  

Void 4.19.40_1 x86_64 GenuineIntel uptodate rrrmFFFFF

* package:  

`qtcreator-4.9.0_1`

### Expected behavior

There should be plugin available for LanguageServer, but in void there is no such a plugin. I assume, that it is just not build

The plugin should be available according to 

https://doc.qt.io/qtcreator/creator-language-servers.html

**Comment by Chocimier** [comment]
It's LanguageClient what qt creator includes and I see it there. In what step of linked instruction do you encounter problems?

**Comment by basiliscos** [comment]
I missed the plugin somehow. Thanks for helping and sorry for incovenience!
