### ISSUE TITLE
New IceWM-package with obsolete components.

### ISSUE THREAD

**Issue by sass432** [void-linux/void-packages#11619]
Since the new development of icewm, I miss my usual and till this time funktionable icons, configured over the executabe startup-script.
﻿The desktop funktions of spacefm are funktionable, but instead of "volumeicon" and "redshift-gtk-icon" there appears empty black squares.
In between I didn't change my voidlinux system-config's or my .xinitrc with the exec-icewm-session-option.

So I researched and found the supposed underlying cause of this problem with the help of a IceWM-unity-member:
[_https://github.com/bbidulock/icewm/issues/344_](url)
**"﻿The default IceWM configure uses an internal systray, which works fine for me for the applications you mention. The "external" systray of the Void package template for IceWM is no longer supported by us."**
[_https://github.com/void-linux/void-packages/blob/master/srcpkgs/icewm/template_](url)
**"I don't understand the reasons they keep on using the external tray as it had problems and is no longer tested by us!"**

So how will this be continued?

**Comment by pullmoll** [comment]
Well, I have never used IceWM myself and if there is noone voting against it, I guess we can just remove the `configure_args`  option `-DCONFIG_EXTERNAL_TRAY=ON` and revbump the package.

**Comment by pullmoll** [comment]
https://github.com/void-linux/void-packages/commit/afd388bee3466fd040f4a5854a2ad80c67aa47ad

**Comment by sass432** [comment]
Thank you very much!
That was the solution of the problem!
I use IceWM since many years and I don't want any different Environments.
It's stable fast, light and simple to use and together with void, spacefm and udevil perfect for my old laptop, because I don't miss any features. In my opinion it's the best KISS-foundation.
And now - with your help - it's a little bit more perfect!
