### ISSUE TITLE
Fails to deactivate LVM/LUKS volumes on shutdown

### ISSUE THREAD

**Issue by abenson** [void-linux/void-packages#11618]
### System

xuname:  Void 5.0.12_1 x86_64 GenuineIntel uptodate rrmFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

package:  runit-void-20180623_2

### Expected behavior

The system shuts down without errors.

### Actual behavior

Deactivation of volume group and deactivation of crypt volume fail because the / filesystem is still in use.

### Steps to reproduce the behavior

Make sure root (/) is on an LVM or LUKS volume. On shutdown, the system umounts all filesystems except root (/), which is [mounted readonly](https://github.com/void-linux/void-runit/blob/master/3#L48). Because it is still mounted, [`deactivate_vgs`](https://github.com/void-linux/void-runit/blob/master/3#L54) and [`deactivate_crypt`](https://github.com/void-linux/void-runit/blob/master/3#L55) fail.

There's no harm in these failing, as the filesystems are already unmounted and synced. Could these steps be skipped for volumes that contain the root filesystem?

**Comment by Duncaen** [comment]
This is more a void-runit issue, not sure why you not opened an issue there.
See https://github.com/void-linux/void-runit/issues/16, its similar.
