### ISSUE TITLE
Package Request: Insect

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#11628]
https://github.com/sharkdp/insect

**Comment by tranzystorek-io** [comment]
This project doesn't meet our [Package Requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements) criteria. While it could be argued it is compiled, packages available via `npm install -g` have little value as system-wide installations, and Void has no notable precedent for packaging those AFAIK.

**Comment by notramo** [comment]
I have found some Rust based alternatives.
https://github.com/PaddiM8/kalker
https://github.com/printfn/fend

These might provide different feature sets, but there are some overlap.

**Comment by tranzystorek-io** [comment]
@notramo fend is now available!

**Comment by mhmdanas** [comment]
Insect is not maintained anymore and has been succeeded by [Numbat](https://numbat.dev) ([source](https://github.com/sharkdp/insect#note-please-consider-using-the-follow-up-project-instead-numbat)), which [just got added to the Void repos](https://github.com/void-linux/void-packages/pull/46176).
