### ISSUE TITLE
kodi crashes on launch

### ISSUE THREAD

**Issue by realiddqd** [void-linux/void-packages#1164]
### System

* xuname:  
  Void 4.17.9_1 x86_64 AuthenticAMD uptodate rrrmFFF
* package:  
  kodi-17.6_2
### Expected behavior
Entertain
### Actual behavior
Disappoint
### Steps to reproduce the behavior
Install kodi, launch kodi.

> $ kodi
/usr/lib/kodi/kodi.bin: symbol lookup error: /usr/lib/kodi/kodi.bin: undefined symbol: _ZNK6TagLib6String6to8BitEb

**Comment by Hoshpak** [comment]
kodi needs to be rebuild because taglib has already been rebuilt without gcc4 compatibility. A rebuild of kodi is part of #1138 .
