### ISSUE TITLE
Package Request: Guix package manager

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#11666]
# Package
Guix package manager

# Build instructions
https://www.gnu.org/software/guix/manual/en/html_node/Binary-Installation.html

**Comment by CameronNemo** [comment]
https://www.gnu.org/software/guix/manual/en/html_node/Requirements.html#Requirements

Actual build instructions.

**Comment by yopito** [comment]
requires guile 2.2. See issue #6418

**Comment by VoidNoire** [comment]
> requires guile 2.2. See issue #6418

So it seems we've recently gotten [Guile 2.2.7](https://github.com/void-linux/void-packages/commit/b4e0222e7f0eb48c0b37cbd65870edb24c7821ab#diff-6431e96f16377b59fdc4f8a5c8e526a536dd7ea2222388e768c84179a9c5bf65), so it should be possible to package this now, right?

**Comment by jgarte** [comment]
We'd need guile 3.0.8 as of today.
