### ISSUE TITLE
Package Request: GCC 9.1

### ISSUE THREAD

**Issue by Jackojc** [void-linux/void-packages#11663]
Just wondering if there is any plan or progress on GCC 9.1.

**Comment by pullmoll** [comment]
I'm currently testing bootstrapping with gcc-9.1.0. I'll push the updated packages [onto my fork's master branch](https://github.com/pullmoll/void-packages) as soon as the base system and cross compilers are built:
- [x] bootstrap
- [x] base-voidstrap
- [ ] base-devel
- [ ] base-system
- [ ] cross-aarch64-linux-gnu
- [ ] cross-aarch64-linux-musl
- [ ] cross-arm-linux-gnueabi
- [ ] cross-arm-linux-gnueabihf
- [ ] cross-arm-linux-musleabi
- [ ] cross-arm-linux-musleabihf
- [ ] cross-armv7l-linux-gnueabihf
- [ ] cross-armv7l-linux-musleabihf
- [ ] cross-i686-linux-musl
- [ ] cross-i686-pc-linux-gnu
- [ ] cross-mips-linux-musl
- [ ] cross-mips-linux-muslhf
- [ ] cross-mipsel-linux-musl
- [ ] cross-mipsel-linux-muslhf
- [ ] cross-powerpc-linux-gnu
- [ ] cross-powerpc-linux-musl
- [ ] cross-powerpc64-linux-gnu
- [ ] cross-powerpc64-linux-musl
- [ ] cross-powerpc64le-linux-gnu
- [ ] cross-powerpc64le-linux-musl
- [ ] cross-vpkg-dummy
- [ ] cross-x86_64-linux-musl
- [ ] cross-x86_64-w64-mingw32
- [ ] gcc-multilib

**Comment by Gottox** [comment]
Sidenote: Currently theres a [corruption issue](https://bugzilla.kernel.org/show_bug.cgi?id=203573) with bcache and newer linux kernels.

**Comment by pullmoll** [comment]
@Gottox that is certainly a show stopper.

I'm currently looking at how to reinstatiate a part of the former patch `musl-ada.patch` which is missing. The `cross-*musl*` compilers cannot build `gcc-9.1.0` because of an unresolved symbol `getpt(3)`...

**Comment by pullmoll** [comment]
For those who want to do some testing, specifically the bcache corruption issue, you can use https://misc.voidlinux.de/iso/.

**Comment by pullmoll** [comment]
Having trouble to build `qt5-5.11.3`:
```
+ /builddir/qt-everywhere-src-5.11.3/qtbase/configure -top-level -confirm-license -opensource -prefix /usr -bindir /usr/lib/qt5/bin -datadir /usr/share/qt5 -headerdir /usr/include/qt5 -sysconfdir /etc/xdg -plugindir /usr/lib/qt5/plugins -docdir /usr/share/doc/qt5 -importdir /usr/lib/qt5/imports -translationdir /usr/share/qt5/translations -examplesdir /usr/share/qt5/examples -archdatadir /usr/lib/qt5 -accessibility -fontconfig -icu -openssl-linked -dbus-linked -no-pch -no-strip -nomake examples -optimized-qmake -no-use-gold-linker -system-libjpeg -system-libpng -system-zlib -system-sqlite -system-harfbuzz -no-webengine-embedded-build -webengine-icu -webengine-ffmpeg -webengine-opus -webengine-webp -webengine-pepper-plugins -webengine-printing-and-pdf -webengine-proprietary-codecs -webengine-pulseaudio -webengine-spellchecker -webengine-webrtc -webengine-geolocation -webengine-v8-snapshot -silent
Creating qmake...
/builddir/qt-everywhere-src-5.11.3/qtbase/src/corelib/global/qrandom.cpp: In static member function 'static void QRandomGenerator::SystemAndGlobalGenerators::securelySeed(QRandomGenerator*)':
/builddir/qt-everywhere-src-5.11.3/qtbase/src/corelib/global/qrandom.cpp:455:62: error: no matching function for call to 'std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>::mersenne_twister_engine(QRandomGenerator::SystemGenerator&)'
  455 |         new (&rng->storage.engine()) RandomEngine(self()->sys);
      |                                                              ^
In file included from /usr/include/c++/9.1/random:49,
                 from /builddir/qt-everywhere-src-5.11.3/qtbase/src/corelib/global/qrandom.h:45,
                 from /builddir/qt-everywhere-src-5.11.3/qtbase/src/corelib/global/qrandom.cpp:43:
/usr/include/c++/9.1/bits/random.h:530:9: note: candidate: 'template<class _Sseq, class> std::mersenne_twister_engine<_UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f>::mersenne_twister_engine(_Sseq&)'
  530 |         mersenne_twister_engine(_Sseq& __q)
      |         ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/9.1/bits/random.h:530:9: note:   template argument deduction/substitution failed:
/usr/include/c++/9.1/bits/random.h: In substitution of 'template<class _Sseq, class _Engine, class _Res, class _GenerateCheck> using __is_seed_seq = std::__and_<std::__not_<std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, _Engine> >, std::is_unsigned<typename _Sseq::result_type>, std::__not_<std::is_convertible<_Sseq, _Res> > > [with _Sseq = QRandomGenerator::SystemGenerator; _Engine = std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>; _Res = unsigned int; _GenerateCheck = void]':
/usr/include/c++/9.1/bits/random.h:491:8:   required by substitution of 'template<class _UIntType, long unsigned int __w, long unsigned int __n, long unsigned int __m, long unsigned int __r, _UIntType __a, long unsigned int __u, _UIntType __d, long unsigned int __s, _UIntType __b, long unsigned int __t, _UIntType __c, long unsigned int __l, _UIntType __f> template<class _Sseq> using _If_seed_seq = typename std::enable_if<std::__detail::__is_seed_seq<_Sseq, std::mersenne_twister_engine<_UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f>, _UIntType>::value>::type [with _Sseq = QRandomGenerator::SystemGenerator; _UIntType = unsigned int; long unsigned int __w = 32; long unsigned int __n = 624; long unsigned int __m = 397; long unsigned int __r = 31; _UIntType __a = 2567483615; long unsigned int __u = 11; _UIntType __d = 4294967295; long unsigned int __s = 7; _UIntType __b = 2636928640; long unsigned int __t = 15; _UIntType __c = 4022730752; long unsigned int __l = 18; _UIntType __f = 1812433253]'
/usr/include/c++/9.1/bits/random.h:528:32:   required from here
/usr/include/c++/9.1/bits/random.h:197:13: error: no type named 'result_type' in 'struct QRandomGenerator::SystemGenerator'
  197 |       using __is_seed_seq = __and_<
      |             ^~~~~~~~~~~~~
/usr/include/c++/9.1/bits/random.h:519:7: note: candidate: 'std::mersenne_twister_engine<_UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f>::mersenne_twister_engine(std::mersenne_twister_engine<_UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f>::result_type) [with _UIntType = unsigned int; long unsigned int __w = 32; long unsigned int __n = 624; long unsigned int __m = 397; long unsigned int __r = 31; _UIntType __a = 2567483615; long unsigned int __u = 11; _UIntType __d = 4294967295; long unsigned int __s = 7; _UIntType __b = 2636928640; long unsigned int __t = 15; _UIntType __c = 4022730752; long unsigned int __l = 18; _UIntType __f = 1812433253; std::mersenne_twister_engine<_UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f>::result_type = unsigned int]'
  519 |       mersenne_twister_engine(result_type __sd)
      |       ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/9.1/bits/random.h:519:43: note:   no known conversion for argument 1 from 'QRandomGenerator::SystemGenerator' to 'std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>::result_type' {aka 'unsigned int'}
  519 |       mersenne_twister_engine(result_type __sd)
      |                               ~~~~~~~~~~~~^~~~
/usr/include/c++/9.1/bits/random.h:516:7: note: candidate: 'std::mersenne_twister_engine<_UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f>::mersenne_twister_engine() [with _UIntType = unsigned int; long unsigned int __w = 32; long unsigned int __n = 624; long unsigned int __m = 397; long unsigned int __r = 31; _UIntType __a = 2567483615; long unsigned int __u = 11; _UIntType __d = 4294967295; long unsigned int __s = 7; _UIntType __b = 2636928640; long unsigned int __t = 15; _UIntType __c = 4022730752; long unsigned int __l = 18; _UIntType __f = 1812433253]'
  516 |       mersenne_twister_engine() : mersenne_twister_engine(default_seed) { }
      |       ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/9.1/bits/random.h:516:7: note:   candidate expects 0 arguments, 1 provided
/usr/include/c++/9.1/bits/random.h:461:11: note: candidate: 'constexpr std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>::mersenne_twister_engine(const std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>&)'
  461 |     class mersenne_twister_engine
      |           ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/9.1/bits/random.h:461:11: note:   no known conversion for argument 1 from 'QRandomGenerator::SystemGenerator' to 'const std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>&'
/usr/include/c++/9.1/bits/random.h:461:11: note: candidate: 'constexpr std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>::mersenne_twister_engine(std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>&&)'
/usr/include/c++/9.1/bits/random.h:461:11: note:   no known conversion for argument 1 from 'QRandomGenerator::SystemGenerator' to 'std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>&&'
make: *** [Makefile:314: qrandom.o] Error 1
=> ERROR: qt5-5.11.3_6: do_configure: 'CC="cc" CXX="c++" CPP="cpp" LD="c++" AR="ar" AS="as" NM="nm" OBJDUMP="objdump" STRIP="strip" RANLIB="ranlib" CFLAGS="$XBPS_CFLAGS" CXXFLAGS="$XBPS_CXXFLAGS" CPPFLAGS="$XBPS_CPPFLAGS" LDFLAGS="$XBPS_LDFLAGS" LFLAGS="$XBPS_LDFLAGS" ${wrksrc}/configure ${opts}' exited with 2
=> ERROR:   in do_configure() at srcpkgs/qt5/template:405
```
Now that's a lengthy error description.

**Comment by pullmoll** [comment]
Interesting detail for the [Red Hat Bugzilla – Bug 1708315](https://bugzilla.redhat.com/show_bug.cgi?id=1708315):

If I look at Void's `gcc-8.3.0` built `linux4.19-4.19.44_1` module `bcache.ko` there is no symbol `bch_bkey_dump` **at all**. Compiled with `gcc-9.1.0` that symbol is indeed there in the `bcache.ko`. You can inspect both using e.g. `Cutter` which is what I did.

Since the function `bch_bkey_dump` is `static` it looks as if `gcc-8.3.0` has optimized it away because it decided the condition when it would be called will never occur. `gcc-9.1.0` OTOH decided to include it and, as we can see in the above bugreport, it is indeed called.

I think the problem could be a result of different handling of partially initialized structs between gcc8 and gcc9 and in this specific case the two declarations of
```
extern const struct btree_keys_ops bch_btree_keys_ops;
extern const struct btree_keys_ops bch_extent_keys_ops;
```
which can be found in `drivers/md/bcache/extents.h`.

In the file `drivers/md/bcache/extents.c` the `const struct btree_keys_ops bch_btree_keys_ops = {…` defines just some of the fields and, specifically **not** the `is_extent = false,` which would apply here. In the `const struct btree_keys_ops bch_extents_keys_ops = {…` more fields are initialized (all?) and `.is_extents = true` is there.

I don't know what happens to an unspecified struct member of type bool. My guess is the default initialization value should be `false` but is this really how it is?

**Comment by pullmoll** [comment]
Another strange thing is the only call to `bch_bkey_dump` is from `drivers/md/bcache/bset.c:31` and there an `#ifdef CONFIG_BCACHE_DEBUG` is around that code. This macro is not defined in our `x86_64-dotconfig` and consequently it is not set in either in the `/boon/config-4.19.44_1` files of the kernel builds.
This explains why `gcc-8.3.0` decided to drop the static `bch_key_dump` function but why does `gcc-9.1.0` not do the same?

**Comment by pullmoll** [comment]
An interesting answer related to the question whether unnamed struct members are initialized can be found here https://stackoverflow.com/questions/330793/ in the comment https://stackoverflow.com/a/37701574/

Specifically ISO/IEC 9899:2011 and ISO/IEC 9899:2018 are said to retain the paragraph 9 statement:

> Except where explicitly stated otherwise, for the purposes of this subclause unnamed members of objects of structure and union type do not participate in initialization. **Unnamed members of structure objects have indeterminate value even after initialization.**

So if gcc9 implemented ISO/IEC 9899:2011 and ISO/IEC 9899:2018 verbatim one would hope the https://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html statement

> Omitted field members are implicitly initialized the same as objects that have static storage duration.

still holds true. Other C99 compliant compilers may not initialize the unnamed struct members as gcc8 did and, let's hope, gcc9 still does. If gcc9 does not, well...

**Comment by pullmoll** [comment]
FWIW explicitly initializing the other struct members in `const struct btree_key_ops bch_btree_key_ops = {…` doesn't change a thing. I initialized a bcache device created from a 16GB backing device (`/dev/vdb1`) and a 1GB cache device (`/dev/vdb2`) as [described here](https://wiki.archlinux.org/index.php/Bcache). I can then do `mkfs.ext4 -L bcache /dev/bcache0` and immediately checking it with `e2fsck /dev/bcache0` corrupts it immediately.

**Comment by pullmoll** [comment]
I tried to enable the D language with the update and I added some new subpackages to `gcc`:
+ `gcc-gdc` contains `/usr/bin/gdc` the GNU D compiler
+ `libgd` contains `/usr/lib/libgdruntime.so.76.3.0` and symlink `/usr/lib/libgdruntime.so.76`
+ `libdg-devel` contains `/usr/lib/libgdruntime.{so,a}` and `/usr/lib/gcc/<triplet>/<ver>/include/d/*`
+ `libgphobos` contains `/usr/lib/libgphobos.so.76.0.3`, symlink `/usr/lib/libgphobos.so.76`, and `/usr/lib/libgphobos.spec`
+ `libgphobos-devel` contains `/usr/lib/libgphobos.{so,a}`

I'll also add [`gdmd`](https://github.com/D-Programming-GDC/GDMD) as a new package to my fork.
The idea is it should then be pssible to bootstrap `dmd` with the help of `gdmd`.

**Comment by pullmoll** [comment]
I just read [Linux 5.1.12 fixed two bugs in bcache](https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.1.12). I'll be testing if bcache works now in the next days.

**Comment by pullmoll** [comment]
Good news: the bcache bugs seem to be solved with `linux4.19-4.19.53_1`. I could create and use bcache devices with btrfs and subvolumes without problems.

I'll create two live ISOs for `x86_64` for testers to run in a VM or on bare hardware. I'll upload them to [my gcc91 repo's live directory](https://repo.voidlinux.de/gcc91/live).

It would also be interesting to have people test a mixture of packages from our main repo and (some) packages built with gcc-9.1.0, installed from https://repo.voidlinux.de/gcc91/, to see if and how well especially packages linking against libstdc++ play together.

**Comment by Jackojc** [comment]
Awesome, thanks @pullmoll !
