### ISSUE TITLE
cross-arm-linux-gnueabihf-libc: missing symlink from /usr/arm-linux-gnueabihf/lib -> usr/lib

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#11693]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *cross-arm-linux-gnueabihf-libc-0.30_1*

### Expected behavior
Have this symlink as with e.g. `cross-aarch64-linux-gnu-libc`
### Actual behavior
```
arm-linux-gnueabihf-gcc test.c
/usr/lib/gcc/arm-linux-gnueabihf/8.3.0/../../../../arm-linux-gnueabihf/bin/ld: cannot find /lib/libc.so.6 inside /usr/arm-linux-gnueabihf
/usr/lib/gcc/arm-linux-gnueabihf/8.3.0/../../../../arm-linux-gnueabihf/bin/ld: cannot find /lib/ld-linux-armhf.so.3 inside /usr/arm-linux-gnueabihf
collect2: error: ld returned 1 exit status
```

**Comment by pullmoll** [comment]
These are in `cross-arm-linux-gnueabihf-libc`. I cannot tell if they should be in the main pkg because AFAIS they are also on `cross-aarch64-linux-gnu-libc` and not in `cross-aarch64-linux-gnu`?

**Comment by Johnnynator** [comment]
> cross-arm-linux-gnueabihf-libc

Yep, they should be in there, nevertheless they are in neither of the packages

**Comment by pullmoll** [comment]
FWIW with my testing of `gcc-9.1.0` bootstrapping and building packages I see that the package `cross-arm-linux-gnueabihf-libc-0.31_1.x86_64.xbps` contains both symlinks.

**Comment by xtraeme** [comment]
This should be already fix, please reopen if issue still exists
