### ISSUE TITLE
memtest86+: Hardlocks on systems with more than 4GB of RAM (packaging/compilation issue, upstream build works fine)

### ISSUE THREAD

**Issue by Veyrdite** [void-linux/void-packages#11691]
### System
Systems tried:

* Gigabyte P67A-UD3R-B3 + i5-3470S 
* HP Elite 8200 + i5-2500

DDR3 modules used in tests:

* 2x2GB 1600 Ripjaws
* 2x2GB 1333 Microns
* 2x4GB 1333 Samsung
* 1x2GB 1333 Kingston

xuname from one system used: Void 4.19.42_1 x86_64 GenuineIntel notuptodate FFFFFFFFFFF (probably not relevant, kernel is not loaded when bug occurs)

package version: memtest86+-5.01_5

### Behaviour

Memtest86+ 5.01 from the official memtest86+ website: works fine
Memtest86 4.3.7 from the official memtest86 website: works fine
**Memtest86+ 5.01 from the void repos: freezes during the first test if more than 4GB of DIMMs are installed.**

This arbitrary % is completely repeatable and depends on the order + sizes of the DIMMs installed.

Only tested on Sandy and Ivy bridge DDR3 motherboards (see motherboards + processors at top of this report).

### Steps to reproduce the behavior

1. xbps-install memtest86+
2. Boot into it using either grub2 or syslinux (both have been tested)
3. Wait for the % of the very first test to progress until full CPU lockup (usually takes <5 seconds)

(note that the '+' still blinking on the screen is a red herring, this is a 'flashing text' non-OS (GPU?) feature, not an indicator of activity in the test)

To test the official version of memtest86+: download it to your /boot directory and modify your grub/syslinux config to list it.  Don't try and use the pre-made ISOs or bootable USBs, they have really poor system compatibility.

To test the official version of memtest86: its USB-bootable versions have very good compatibility, use them.

### Misc context

Void compiles memtest86+ from source, somewhere in this process the bug is being created or uncovered.  Compare the binaries:
```
179K /boot/memtest86+    (from void repos)
147K /boot/officialmemtest.bin  (from memtest86+ website)
```

**Comment by yopito** [comment]
Thanks for this detailed issue. I'll take a loop asap (my workstation is currently broken)

**Comment by Frosty-J** [comment]
After wasting an afternoon, I can confirm this also affects Ubuntu 21.04's MemTest86+ and Haswell.

Same behaviour with the blinking `+` and all. Fails after 1 second on test 2 with SMP disabled and after 36 seconds on test 1 with SMP enabled.

I downloaded 5.31b from memtest.org, burned it to a CD (a waste but was easiest) and that version was fine.

PC: HP 800 G1 TWR
BIOS: The latest - 02.78 Rev.A
CPU: Intel i7-4770
RAM: Various 4GB 1600MHz DDR3 sticks in different slots and both single-channel and dual-channel configurations: Kingston 9905403-496.A00LF, Hynix HMT351U6CFR8C-PB, Micron 8JTF51264AZ-1G6E1

**Comment by Veyrdite** [comment]
I can confirm this bug still occurs for me.

@Frosty-J N.B. memtest.org != memtest86+, different product.

FWIW memtest86+'s "bootable" images never seem to work as well as memtest's unless you put a bootloader (eg grub or syslinux) in front of them.  I've been using the official memtest86+ bin by copying the void-memtest entry in my bootloader config and just editing the filename it points to.

**Comment by Frosty-J** [comment]
Isn't the one at memtest.org MemTest86+? It has the same name and version numbers, and is identical in both appearance and function.

**Comment by yopito** [comment]
thanks for this detailed report.
I can't give a try to memtest 5.01 since musl libc on my system.
however, my WIP memtest 5.31b Void package is still working fine, I've just restested it (see https://github.com/void-linux/void-packages/pull/21179)
Would you mind give a try ?
This means building this package by yourself from source using branch https://github.com/yopito/void-packages/tree/memtest.5.31b .
I also might crossbuild this package for you (either glibc or musl) and provide it to you prefer (unofficial package ATM).

**Comment by Veyrdite** [comment]
> Isn't the one at memtest.org MemTest86+? It has the same name and version numbers, and is identical in both appearance and function.

Woops sorry yes you are right.  memetest86.com is the commercial one.

@yopito I would have thought that memtest doesn't use an external libc?  I'll make a build once I have some more spare time.

**Comment by leahneukirchen** [comment]
I tried Void memtest a few weeks ago with 48G ram and it froze after a few seconds too.

**Comment by leahneukirchen** [comment]
Any good reason we just don't ship upstream binaries?

**Comment by leahneukirchen** [comment]
Just checked this on my machine, the upstream binary works fine indeed. Unless someone is very interested in fixing the toolchain, I'd suggest to use upstream binary instead and not compile ourselves.

**Comment by yopito** [comment]
I agree to package upstream binary instead of building from source if it works better.
I'll give a try to package it this way.

**Comment by yopito** [comment]
package binary memtest (see PR above). Could you give a try ?
