### ISSUE TITLE
Running `sudo sudo` drops user into root

### ISSUE THREAD

**Issue by Sweets** [void-linux/void-packages#1179]
### System

* xuname:  
  * `Void 4.16.14_1 x86_64 GenuineIntel uptodate r`
* package:  
  * sudo (<=1.8.23)

### Expected behavior

Usage should be output.

### Actual behavior

User is dropped into the root account, similar to running `sudo su`.

### Steps to reproduce the behavior

Run `sudo sudo` on a void installation.

Other distributions do not result in this behavior, refer below for tested distributions.

Arch Linux (sudo 1.8.23)

![image](https://user-images.githubusercontent.com/13605846/43174266-c2a21966-8f7e-11e8-8163-ec54df6a27e5.png)

Xubuntu (sudo 1.8.21)

![image](https://user-images.githubusercontent.com/13605846/43174337-1bc34b0a-8f7f-11e8-8c50-e407c78caa7f.png)

Gentoo (sudo 1.8.22)

![image](https://user-images.githubusercontent.com/13605846/43174342-2f2d8228-8f7f-11e8-888a-99e6f6435b5b.png)

Void (sudo 1.8.23)

![image](https://user-images.githubusercontent.com/13605846/43174239-993f33ba-8f7e-11e8-8553-05a3c9677431.png)

**Comment by Duncaen** [comment]
The `sudo` in void is build with `--enable-noargs-shell`, not sure why and what the benefits or downsides are.

Its already happening if you just run `sudo`, the same as `sudo -s`.

**Comment by Sweets** [comment]
```
--enable-noargs-shell: This switch allows sudo to run a shell if invoked with no arguments.
```

Source: http://www.linuxfromscratch.org/blfs/view/6.3/postlfs/sudo.html

**Comment by knusbaum** [comment]
Does this cause issues? I actually kind of like the idea. I'd only worry about it causing incompatibilities with scripts written on other distros, but I'm not sure what those would be. `sudo` isn't used inside scripts much at all, as far as I can tell.

**Comment by pcallycat** [comment]
I don't think there's any inherent harm in it, if you've access to run processes as root through sudo anyway, then sudo -s will get you a root shell as well.  The option saves a couple of keystrokes i guess.  As far as script incompatibilites, it would be odd for a script to run sudo from sudo anyway.
