### ISSUE TITLE
Package Request: Budgie Desktop

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#11815]
Github Website:
https://github.com/solus-project/budgie-desktop

**Comment by Anachron** [comment]
I think we should wait for the rewrite:

https://github.com/solus-project/budgie-desktop/blob/master/README.md#move-to-gtk4

However I‘m also interested in Budgie so maybe I‘ll create a sandbox template to play with.

**Comment by CameronNemo** [comment]
https://dev.getsol.us
