### ISSUE TITLE
`mypaint-brushes>=2.0` is incompatible with `gimp`.

### ISSUE THREAD

**Issue by kartikynwa** [void-linux/void-packages#11839]
### System

* xuname:  Void 4.19.44_1 x86_64 GenuineIntel
* package:  gimp, mypaint-brushes

### Description

Gimp currently doesn't support `mypaint-brushes>=2.0`. `mypaint-brushes-1.3.0` works fine. I suggest removing `mypaint-brushes` from the dependency since Gimp works fine without it. We could also add a `mypaint-brushes1.3` package or people who need it can build it themselves.

**Comment by biopsin** [comment]
Revert to [this commit](https://github.com/void-linux/void-packages/tree/021ade318254672f37ab6be61cf0f1a5aaf552ca/srcpkgs/mypaint-brushes)

**Comment by Chocimier** [comment]
Ok core team, I need advice on how to fix that.

The desired way is to add `mypaint-brushes1` and make gimp depend on that, but:
* sometimes xbps fails moving files between packages (libvpx case was most impressive)
* this is against current best practice of giving new name to new version, not the old one

The other way could be to revert mypaint-brushes to 1.3 and introduce mypaint-brushes2 for mypaint, but then users would need to manually find and install newer version for using with mypaint.

**Comment by jnbr** [comment]
> The desired way is to add mypaint-brushes1 and make gimp depend on that, but:

makes sense

> sometimes xbps fails moving files between packages (libvpx case was most impressive)

The filepaths in `mypaint-brushes` contain the version (2.0 or 1.0) so there are no conflicts in this case.

> this is against current best practice of giving new name to new version, not the old one

I wouldn't call this a best practice because:

> but then users would need to manually find and install newer version for using with mypaint.

So yes, just add `mypaint-brushes1`, shouldn't cause any problems and we can remove it when gimp moves forward to the current version without moving stuff again.
