### ISSUE TITLE
Switch from Python2 to Python3 by default.

### ISSUE THREAD

**Issue by Jackojc** [void-linux/void-packages#11855]
Are there any plans to phase out Python2 support by default for Void? The end of life for Python2 is fast approaching and most things have been ported to Python3 by now. Other distros seem to be able to use Python3 by default with no issues.

**Comment by Johnnynator** [comment]
Void doesn't really have a "default" python version, the `/usr/bin/python` symlink points to whatever Python version was installed first and can be changed with `xpbs-alternatives(1)`. And no we don't have any time plan yet to phase out Python 2, so far it is just a gradual process to get Python 2 only packages to Python 3, but there are still roughly over 100 Python 2 only packages in the repo. (If not more)

**Comment by Jackojc** [comment]
Understandable, thank you for clearing it up.
