### ISSUE TITLE
Package Request: papirus-folders

### ISSUE THREAD

**Issue by DarthWound** [void-linux/void-packages#11887]
**Papirus-Folders** is a script from the Papirus Team to change folders color.
`papirus-folders -C color` to change, `papirus-folders -D` to go back to default _(blue)_.

Homepage: [link](https://github.com/PapirusDevelopmentTeam/papirus-folders)
Releases: [link](https://github.com/PapirusDevelopmentTeam/papirus-folders/releases)
AUR package _(if it helps)_: [link](https://aur.archlinux.org/packages/papirus-folders-git)
Requires: _papirus-icon-theme_ package

---

Thanks!

**Comment by benalb** [comment]
https://github.com/void-linux/void-packages/pull/11913

**Comment by Hoshpak** [comment]
has been merged
