### ISSUE TITLE
vscode: live share plugin from market place needs openssl to work

### ISSUE THREAD

**Issue by lalincedeldeserto** [void-linux/void-packages#11926]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
Void 4.19.45_1 x86_64 GenuineIntel uptodate rrFF

* package:  
  *affected package(s) including the version*
vscode live-share from microsoft (search into vscode market place)

I installed correctly from the marketplace live-share plugin but it doesn't start because it needs openssl.

File log:
[liveshare-log.zip](https://github.com/void-linux/void-packages/files/3217031/liveshare-log.zip)

A screenshot to the extension:
![image](https://user-images.githubusercontent.com/33136381/58331045-8b30a480-7e38-11e9-88b3-298ccbb261fc.png)

**Comment by Duncaen** [comment]
Not sure what we can or do about it, this is third party code installed from a third party package manager.

**Comment by Johnnynator** [comment]
https://github.com/MicrosoftDocs/live-share

**Comment by lalincedeldeserto** [comment]
Thank you guys, I hope someone would solve the problem in the nearest future :smile: 
@Johnnynator thank you for having modified the tag in my report issue :+1: 
I know this is a third party software so it's not easy to solve because as @Duncaen said, it's closed source (I thought that it was entirely opened :disappointed_relieved: )

**Comment by lalincedeldeserto** [comment]
There's a little trick to may it work, but I haven't proofed any connection.
Thanks to a person, just do this:
open a terminal and paste:
sudo ln -s libssl.so.46 /usr/lib/libssl.so.1.0.0

**Comment by Johnnynator** [comment]
There is no guaranteed on ABI compatibility between LibreSSL and OpenSSL, if it would work now it could break after every LibreSSL update.

**Comment by lalincedeldeserto** [comment]
Not working now

**Comment by vdo** [comment]
This fixes the issue in my environment (Void Linux with libressl)
```
export CLR_OPENSSL_VERSION_OVERRIDE=46
```

**Comment by obunden** [comment]
@Johnnynator Can this issue be closed since it can't be solved on our end?

**Comment by lalincedeldeserto** [comment]
Dear @obunden, the problem still remains not solved. I don't think there's a standard solution to be applied. The only thing you can do is to turn around the problem through some tricks (that may not work because of some incompatibilities).
This issue cannot be solved because, if I'm not wrong, the sources code of this module is not open.

**Comment by ericonr** [comment]
An OpenSSL switch is likely to happen soon. Since any other trick is bound to break easily, I'm closing this.
