### ISSUE TITLE
NetworkManager stderr spam

### ISSUE THREAD

**Issue by Henry-Wilson** [void-linux/void-packages#11928]
### System

* xuname:  
`Void 4.19.45_1 x86_64 GenuineIntel uptodate rFFF`

* package:  
`NetworkManager-1.16.0_2`

### Expected behavior
Configure network settings well and NOT print to stderr from `nm-dispatcher` via `dbus`

### Actual behavior
Configure network settings well and print to stderr from `nm-dispatcher` via `dbus`

### Steps to reproduce the behavior
1) Install `NetworkManager` as listed on the wiki
2) Connect to a network (`nmtui` works)
3) reboot into non-graphical environment - `agetty`
4) You should see a spam of messages from `nm-dispatcher` just after the login prompt shows up. This makes it very difficult to understand that the login is ready, and it looks bad.

### My workaround
To fix this, I edited `/etc/dbus-1/system.d/nm-dispatcher.conf` to change the second rule of the second rule of the second policy from `<allow send_destination="org.freedesktop.nm-dispatcher"/>` to `<deny send_destination="org.freedesktop.nm-dispatcher"/>`

Perhaps this is unprofessional or nonstandard. I don't know. I believe that what it does is cause `dbus` to deny `nm-dispatcher` the permission to send system messages, thus preventing them from making it all the way to stderr and messing up my login prompt.

**Comment by CameronNemo** [comment]
Sounds like you neutered the entire nm dispatcher functionality.

**Comment by Henry-Wilson** [comment]
Huh, I'd not have known that. I've certainly never had a particular or direct use for nm-dispatcher. That said, I don't like having my computer set up oddly. Is there a way that I can get the dispatcher to send its messages elsewhere than stderr, rather than just disabling it?

**Comment by Roswell-1947** [comment]
Does a syslog daemon not take care of this?
https://docs.voidlinux.org/config/services/logging.html

**Comment by Henry-Wilson** [comment]
I'll have to see what happens with that. I'll get back to you shortly.

**Comment by Henry-Wilson** [comment]
Holy cow, that's great. Did I miss this on the wiki, or should we add it somewhere? This seems to general to put in the nm article, but perhaps a mention of it?

**Comment by Henry-Wilson** [comment]
I see the page on the wiki. Would it be inappropriate to add a link to it on the network configuration page, and anywhere else the programs discussed would benefit from this?
