### ISSUE TITLE
virtualbox-ose: update to 6.0.8 fails to build kernel modules. 

### ISSUE THREAD

**Issue by yilmzfurkan** [void-linux/void-packages#11931]
### System
Void Linux x86_64 XFCE
* package:  virtualbox-ose
  *virtualbox-ose 6.0.8*
It both failed on linux4.19 and linux5.0
### Expected behavior
Latest virtualbox-ose should be able to build/install kernel modules successfully. 
### Actual behavior
It fails to build DKMS.
### Steps to reproduce the behavior
Just fetch the latest updates "sudo xbps-install -Su"

**Comment by abenson** [comment]
Same with 5.1.x. Error with all three is (aside from the version):

~~~
Error!  Build of vboxnetadp.ko failed for: 4.19.45_1 (x86_64)
~~~

What's confusing to me is that that module seems to be compiling just fine?

~~~
=== Building 'vboxnetadp' module ===
make[1]: Entering directory '/var/lib/dkms/virtualbox-ose/6.0.8/build/vboxnetadp'
make V= CONFIG_MODULE_SIG= -C /lib/modules/5.1.3_1/build M=/var/lib/dkms/virtualbox-ose/6.0.8/build/vboxnetadp SRCROOT=/var/lib/dkms/virtualbox-ose/6.0.8/build/vboxnetadp -j8 modules
make[2]: Entering directory '/usr/src/kernel-headers-5.1.3_1'
  CC [M]  /var/lib/dkms/virtualbox-ose/6.0.8/build/vboxnetadp/linux/VBoxNetAdp-linux.o
  CC [M]  /var/lib/dkms/virtualbox-ose/6.0.8/build/vboxnetadp/VBoxNetAdp.o
  LD [M]  /var/lib/dkms/virtualbox-ose/6.0.8/build/vboxnetadp/vboxnetadp.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /var/lib/dkms/virtualbox-ose/6.0.8/build/vboxnetadp/vboxnetadp.mod.o
  LD [M]  /var/lib/dkms/virtualbox-ose/6.0.8/build/vboxnetadp/vboxnetadp.ko
make[2]: Leaving directory '/usr/src/kernel-headers-5.1.3_1'
make[1]: Leaving directory '/var/lib/dkms/virtualbox-ose/6.0.8/build/vboxnetadp'
~~~

**Comment by abenson** [comment]
Ah, it looks like 6.0.8 installs to `misc/`, the old (and I presume expected) path is `updates/`.

**Comment by abenson** [comment]
@Hoshpak Any ideas?

**Comment by pullmoll** [comment]
```
/var/lib/dkms/virtualbox-ose/6.0.8/build/vboxdrv/SUPDrvTracer.o: warning: objtool: .text+0x7: indirect jump found in RETPOLINE build
```
This is the error I see here in `/var/lib/dkms/virtualbox-ose/6.0.8/build/make.log`.

**Comment by Hoshpak** [comment]
Sorry, I didn't test the dkms modules this time before pushing. Arch already had a patch for the issue. I tested it and will push it.

**Comment by pullmoll** [comment]
NP @Hoshpak thanks for finding and pushing that patch :-)
Have a good time!
