### ISSUE TITLE
Texlive 2019 issues with xetex and CJK fonts

### ISSUE THREAD

**Issue by KRSHK** [void-linux/void-packages#11963]
### System

* xuname:  
  *Void 4.19.46_1 x86_64 GenuineIntel uptodate rrFF*

* package:  
  *texlive-bin-2019_1*

### Expected behavior

When compiling with ```xelatex``` a ```.tex``` file using CJKfonts from local ```.fonts``` directory, using ```xecjk``` package, it has to produce a pdf.

### Actual behavior

Since I reboot after important update, the same process give :
```
kpathsea: Running mktextfm rmplus/OT
/opt/texlive/2019/texmf-dist/web2c/mktexnam: Could not map source abbreviation  for OT.
/opt/texlive/2019/texmf-dist/web2c/mktexnam: Need to update ?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input OT
This is METAFONT, Version 2.7182818 (TeX Live 2019) (preloaded base=mf)


kpathsea: Running mktexmf OT
! I can't find file `OT'.
<*> \mode:=ljfour; mag:=1; nonstopmode; input OT

Please type another input file name
! Emergency stop.
<*> \mode:=ljfour; mag:=1; nonstopmode; input OT

Transcript written on mfput.log.
grep: OT.log: Aucun fichier ou dossier de ce type
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input OT' failed to make OT.tfm.
kpathsea: Appending font creation commands to missfont.log.


! Package fontspec Error: The font "rmplus" cannot be found.

For immediate help type H <return>.
 ...

l.25 ...infont{rmplus}[Script=CJK, Language=Japanese]
                                                  {rounded-mplus-1p-regular}

```

### Steps to reproduce the behavior
You need ```xetex``` and ```xecjk``` installed, and use the minimal example below:
```
\documentclass[9pt]{article}
\usepackage{%
     fontspec,%
     xeCJK%
 }

\setmainfont{Latin Modern Mono} %your favorite font
\setCJKmainfont{rmplus}[Script=CJK, Language=Japanese]{rounded-mplus-1p-regular}
 %your favorite CJK font, hre rounded M+ 1p regular

\begin{document}
test
{\CJKfamily{rmplus} テスト}
\end{document}
```

### More
I discovered it after trying to use upTex. I had to install new packages with ```tlmgr``` and reboot.
I tought I made some mess with mapping and everything else, so I reinstalled from scratch voidlinux. The result is the same.

**Comment by svenper** [comment]
If a system update is involved, have you tried regenerating formats etc?
```
sudo mktexlsr
sudo fmtutil --sys --all
sudo updmap --sys --syncwithtrees
sudo updmap --sys
```

My impressions:

```
\setCJKmainfont{rmplus}[Script=CJK, Language=Japanese]{rounded-mplus-1p-regular}
```
 looks wrong, there should be only one font name, i.e. one of
```
\setCJKmainfont[Script=CJK, Language=Japanese]{‹name›}
\setCJKmainfont{‹name›}[Script=CJK, Language=Japanese]
```

and there is no need for 
```
\CJKfamily{rmplus}
```
since script should be detected automatically by unicode range.

This works for me:™

```
\documentclass{article}
\usepackage{fontspec,xeCJK}
\setmainfont{SourceSerifPro-Regular.otf}[Path=/tmp/]
\setCJKmainfont{SourceHanSerif-Regular.otf}[Path=/tmp/,Script=CJK,Language=Japanese]
\begin{document}
test テスト
\end{document}
```

I would recommend asking on [tex.stackexchange.com](https://tex.stackexchange.com), that's where the TeX devs hang out.

**Comment by ericonr** [comment]
We have newer texlive packages and the reporter hasn't responded, closing.
