### ISSUE TITLE
package request: `samba-4.X` for samba

### ISSUE THREAD

**Issue by leonardlorenz** [void-linux/void-packages#11983]
### System

* xuname:  
 Void 4.19.45_1 x86_64 GenuineIntel uptodate rrmFFFF
* package:  
  ~~winbindd~~
  samba-4.X

### Expected behavior
winbindd is available in /etc/sv

### Actual behavior
winbindd is not available in /etc/sv

https://www.ubuntuupdates.org/package/core/xenial/main/updates/winbind

**Comment by Hoshpak** [comment]
winbindd is part of the `samba` package:

```
# xlocate /usr/bin/winbind
samba-3.6.25_14	/usr/bin/winbindd
samba-3.6.25_14	/usr/bin/winbindd
```

**Comment by leonardlorenz** [comment]
Huh, interesting. It seems to be available as a shell command in my $PATH, but the service for it doesn't exist, like for example on Ubuntu or other distributions.

```Bash
λ ls /etc/sv | grep winbind
λ 
λ which winbindd
/bin/winbindd
```

I'll dig into this more.

**Comment by Hoshpak** [comment]
I'm closing this since it's effectively an update request and everyone is well aware that our samba version is outdated.
