### ISSUE TITLE
[Request] Powershell package

### ISSUE THREAD

**Issue by haboutnnah** [void-linux/void-packages#11993]
### System

* xuname:  Void 4.19.46_1 x86_64 GenuineIntel uptodate rFFF
* package:  
powershell

### Expected behavior

`# xbps-install powershell` or `pwsh` to work

### Actual behavior

Neither exists

### Steps to reproduce the behavior

N/a

**Comment by Folling** [comment]
Could we get an update on this request? Either a rejection or whether it'd be desired so that a PR can be raised.

**Comment by classabbyamp** [comment]
i don't see any reason why it wouldn't be added, but i do see that it needs dotnet, which is not packaged yet
