### ISSUE TITLE
glibc-32bit: ld-linux.so.2 moved

### ISSUE THREAD

**Issue by mmnmnnmnmm** [void-linux/void-packages#12003]
### System

* xuname:  
  *Void 4.19.46_1 x86_64 AuthenticAMD notuptodate rrrmDFFFFFFFFF*
* package:  
  *glibc-32bit-2.29_4*

### Expected behavior
Running steam should work.

### Actual behavior
Steam reports that libc.so.6 does not exist.

### Steps to reproduce the behavior
Install `glibc-32bit-2.29_4` and run steam.  This may affect other 32bit progams.

### Extra
ld-linux.so.2 has been moved into a directory of the same name.
I expect that steam is looking for `/lib/ld-linux.so.2` but is finding the directory instead.

    glibc-32bit-2.29_3      /usr/lib/ld-linux.so.2 -> /usr/lib32/ld-2.29.so

    glibc-32bit-2.29_4	/usr/lib/ld-linux.so.2/ld-linux.so.2 -> /usr/lib32/ld-2.29.so

**Comment by pullmoll** [comment]
This seems to be due to `common/hooks/pre-pkg/05-prepare-32bit.sh:159`
```
        mkdir -p ${destdir32}/usr/lib{,32}/${f%/*}/
```
which was added on 2019-04-13 by @maxice8. The `srcpkgs/glibc/template` has `lib32symlinks="ld-linux.so.2"` so there's no `/` in `$f` here.

**Comment by pullmoll** [comment]
Should be fixed with https://github.com/void-linux/void-packages/commit/998aac300abce57662e745f94632ac2177a88c82 and https://github.com/void-linux/void-packages/commit/a5f1853bb623c3fac87b8c625ec5952a8e1dfbc8
