### ISSUE TITLE
GIMP crash at start up (musl)

### ISSUE THREAD

**Issue by makmm** [void-linux/void-packages#12042]
### System

* xuname:  
  ```
  [~]$ sudo xuname
  Void 5.1.5_1 x86_64-musl AuthenticAMD notuptodate rFFF
  ```
* package:  
  `gimp-2.10.10_2`

### Expected behavior

GIMP starts up correctly.

### Actual behavior

```
[~]$ gimp
GIMP-Mensaje: Falló al cargar algunas tipografías: # failed to load some typographies(?):

- /usr/share/gimp/2.0/fonts/

gimp: fatal error: Segmentation fault
```

### Steps to reproduce the behavior

Start GIMP.

**Comment by jnbr** [comment]
Works for me. Can you update your system and try again?

**Comment by xtraeme** [comment]
I think the issue is that he's missing a font that gimp expects...

**Comment by xtraeme** [comment]
Hmm I was wrong, it's crashing for me too.

**Comment by xtraeme** [comment]
Ok, found the issue. It works with LANG=C, there's something wrong in the internalization with musl.

**Comment by makmm** [comment]
I already deleted that install xD, but I'm pretty sure I was on es_AR UTF-8.
