### ISSUE TITLE
Krita Python Plugin Manager

### ISSUE THREAD

**Issue by necronoise** [void-linux/void-packages#12055]
### System

* xuname: Void 4.19.46_1 x86_64 GenuineIntel uptodate rrrmFFFFF
* package: krita-4.2.0_1

### Expected behavior
![image](https://user-images.githubusercontent.com/28832216/58700577-d38b1d80-8376-11e9-800b-7c72645819dd.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/28832216/58700603-e7cf1a80-8376-11e9-99e7-20ba83f328a8.png)

_"If you don’t see the scripter plugin, make sure you are using an up-to-date version of Krita."_ https://docs.krita.org/en/user_manual/python_scripting/introduction_to_python_scripting.html

There is no Python Plugin Manager in the Krita (void repo) but in the appimage has. Without it I can't be hable to use _ten brushes python extension_. https://www.reddit.com/r/krita/comments/bv1jy4/shortcut_eraser_brush/

### Steps to reproduce the behavior
Start Krita.
Settings > Configure Krita...

**Comment by Johnnynator** [comment]
It should be built, can you install `python3-PyQt5` and check if it works afterwards?

**Comment by necronoise** [comment]
> It should be built, can you install `python3-PyQt5` and check if it works afterwards?

I installed and still not working.

_[*] Configuring unpacked packages
sip-4.19.13_3: configuring ...
python3-sip-PyQt5-4.19.13_3: installed successfully.
python3-PyQt5-5.11.3_3: configuring ...
Byte-compiling python3.6 code for module PyQt5...
Updating ldconfig(8) cache...
ldconfig: /usr/lib/libtinfo.so.5 não é um link simbólico

ldconfig: /usr/lib/libncurses.so.5 não é um link simbólico

python3-PyQt5-5.11.3_3: installed successfully.

1 downloaded, 3 installed, 0 updated, 3 configured, 0 removed._

**Comment by Johnnynator** [comment]
Ok, I will look into it next week.

**Comment by necronoise** [comment]
> Ok, I will look into it next week.

Its working now, thank you so much guys!
