### ISSUE TITLE
provide boot image for raspberry pi 3 b+

### ISSUE THREAD

**Issue by catastrop** [void-linux/void-packages#12067]

**Comment by the-wrench99** [comment]
The images for the pi3 work just fine on mine, even with the touchscreen kit

**Comment by catastrop** [comment]
This page [ https://voidlinux.org/download ] doesn't have any entry for raspberry pi 3 but this page [ https://alpha.de.repo.voidlinux.org/live/current ] has.

**Comment by pullmoll** [comment]
So can we close this again?

**Comment by catastrop** [comment]
You should update this page [ https://voidlinux.org/download ].

**Comment by Hoshpak** [comment]
Feel free to create a PR:

https://github.com/void-linux/void-linux.github.io
