### ISSUE TITLE
Package Request: MelonDS

### ISSUE THREAD

**Issue by 0xJes** [void-linux/void-packages#12076]
MelonDS is a NintendoDS emulator

> The goal is to do things right and fast, akin to blargSNES (but hopefully better). But also to, you know, have a fun challenge :)

https://github.com/Arisotura/melonDS

**Comment by abenson** [comment]
I've opened an issue for melonDS to start tagging releases. Once they do, it can be packaged here.

**Comment by JesMJM** [comment]
The developer is tagging releases now.
