### ISSUE TITLE
request: ``php-pdo-sqlite``, and other pdo drivers

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [void-linux/void-packages#12075]
currently, the ``php-sqlite`` package is just a sublink to the ``php`` package.

running ``phpinfo();`` shows that no PDO drivers exist, even after enabling the pdo sqlite and sqlite extensions in ``/etc/php.ini``

**Comment by Hoshpak** [comment]
Did you install the `php-sqlite` package? After installing the package and enabling the extension in php.ini, I get the following on my system:

```
PDO

PDO support => enabled
PDO drivers => sqlite

pdo_sqlite

PDO Driver for SQLite 3.x => enabled
SQLite Library => 3.28.0
```

**Comment by ThatNerdyPikachu** [comment]
that looks to have fixed it, thanks~
