### ISSUE TITLE
Package request: Nheko

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#12086]
https://github.com/Nheko-Reborn/nheko

**Comment by Hoshpak** [comment]
The package was in the repository once but was removed because the previous upstream abandoned the project. If anyone wishes to add the package again, the previous template could be a good starting point.

**Comment by Hoshpak** [comment]
fore reference:

6f323d077aa13529dcde602e90fd42ce3cd371b8

**Comment by not-chicken** [comment]
> for reference:
> 
> [6f323d0](https://github.com/void-linux/void-packages/commit/6f323d077aa13529dcde602e90fd42ce3cd371b8)

Thanks for the reference. Got it working on my machine by modifying old templates. Will test it over the weekend before opening a pr.

Dropping off this comment here so that others don't waste their time on this.
