### ISSUE TITLE
Package Request: gvfs-trash

### ISSUE THREAD

**Issue by lalincedeldeserto** [void-linux/void-packages#12096]
gvfs-trash isn't in void repos, could you add it?
It's needed in atom to remove files directly using its UI.

**Comment by Hoshpak** [comment]
gvfs-trash is deprecated and other distributions already removed it, I don't think we should add it to our repository. Atom will upgrade to electron v3 as documented in https://github.com/atom/atom/issues/17452 which uses the proper API and will work again without `gvfs-trash`.

**Comment by lalincedeldeserto** [comment]
Thank you @Hoshpak, I didn't know it's deprecated. I close this package request.
