### ISSUE TITLE
vim arbitrary code execution via modeline

### ISSUE THREAD

**Issue by congdanhqx** [void-linux/void-packages#12152]
See https://github.com/numirias/security/blob/master/doc/2019-06-04_ace-vim-neovim.md

neovim is also effected by this vulnerable but it's fixed in 0.3.7

**Comment by CameronNemo** [comment]
Why do we not just disable this dumpster fire of a feature?

**Comment by congdanhqx** [comment]
On 2019-06-04 16:40:13 -0700, Cameron Nemo wrote:
> Why do we not just disable this dumpster fire of a feature?

modeline is useful for setting filetype, encoding, spacing,
we can't disable modelineexpr until v8.1.1366

**Comment by fosslinux** [comment]
#12154 closes this
