### ISSUE TITLE
Anyone opposed to dropping runtime dhclient dependency for NetworkManager

### ISSUE THREAD

**Issue by thomas-t-w** [void-linux/void-packages#12167]
NetworkManager has a built in dhcp server which I have been using for a few days now. It seems to be faster and more reliable in band steering senarios. I have tested on a few networks, one being Eduroam which uses wpa2 enterprise and I haven't had troubles. I would propose that the runtime dependency only be dropped and the default still be left at dhclient. If dhclient isn't installed. if a user installed NetworkManager, they will get the built-in dhcp server by default because NetworkManager falls back to that. If the user installs dhclient, they will get that because it is set by default which makes it easy if someone runs into a problem which I don't expect but it is obviously possible. If a user has dhclient installed and they want the dhcp server built into NetworkManager, they clearly know what they are doing and can change it manually in NetworkManagers config. Any opposed to this change? I will leave this open for a few days and close it if I don't hear anything and open a pull request with the change.

**Comment by thomas-t-w** [comment]
I forgot to give info on how to test. See this wiki article. https://wiki.archlinux.org/index.php/NetworkManager#DHCP_client
set dhcp=internal in NetworkManagers config files.
Or you can do what I did: xbps-remove -F dhclient.

**Comment by thomas-t-w** [comment]
Sorry, I made a stupid mistake in my first message. I meant dhcp client not dhcp server.

**Comment by xtraeme** [comment]
:+1:
