### ISSUE TITLE
Package request: Postman

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#12168]
https://www.getpostman.com/

**Comment by LVKILL** [comment]
install Postman in any distro:
su -
gzip -d Postman-linux-x64-6.4.4.tar.gz
tar -xvf Postman-linux-x64-6.4.4.tar
mv Postman/ /opt/postman
chmod +x /opt/postman/Postman
ln -s /opt/postman/Postman /usr/local/bin/postman

CREATE DESKTOP ENTRY:
vim /usr/share/applications/postman.desktop
AND PUT THIS:

[Desktop Entry]
Encoding=UTF-8
Name=Postman
Comment=Postman
Exec=postman %U
Icon=/opt/postman/app/resources/app/assets/icon.png
Terminal=false
Type=Application
Categories=GNOME;Application;Development;
StartupNotify=true

**Comment by LVKILL** [comment]
i  use in my void it's fine

**Comment by sistematico** [comment]
> https://www.getpostman.com/

Here we go..
https://github.com/sistematico/void-packages/blob/main/srcpkgs/postman/template

**Comment by Duncaen** [comment]
> Why the "electron" label with a sick emoji? Are Electron apps banned from Void?

They are usually not easily packagable, most PRs that never get merged for electron apps just repackage binaries for x86_64+glibc, which is not acceptable for multiple reasons. Rerpacking binaries for open source software is bad practice and especially bad for things like electron which has a ton of dependencies, that would potentially lock our repository to a specific version that we can't update until the electron repackage is rebuild by upstream.
