### ISSUE TITLE
brltty: file /etc/brlapi.key should be created upon package install with random contents

### ISSUE THREAD

**Issue by thomas-t-w** [void-linux/void-packages#12173]
I don't know how this should be implemented into a build script and which program we should use to get the random text. I guess it goes into post_install()? If someone tells me which program would  be best to use to generate the random string, I will try to implement it.
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package: brltty6.0_1
  *affected package(s) including the version*

### Expected behavior
If the file is created, programs like orca screen reader can use the brltty api to display text on a braille display. https://en.wikipedia.org/wiki/Refreshable_braille_display
### Actual behavior
I had to create this file manually and add text to it.
### Steps to reproduce the behavior
Install brltty package.

**Comment by Hoshpak** [comment]
I don't think using the same random string for all installations would be appropriate, wouldn't it? I think this should better be done in an `INSTALL` script as a post action. This way is is executed by xbps after package installation on the local system. You can look at existing scripts like e.g. `trousers` to see how such a script should be implemented. Arch already has a script for their package manager which could be adapted to our needs: https://git.archlinux.org/svntogit/packages.git/tree/trunk/brltty.install?h=packages/brltty They use the `mcookie` command from `util-linux` to create the random text.

**Comment by CMB** [comment]
@ericonr Yes, this ticket is still applicable.

BTW here's how you can test for the problem locally.
Install brltty and python3-brlapi.  Start the runit service.  It should
start even if you don't have a braille display and haven't done any
configuration.  Run:

    python3 -c 'import brlapi ; brlapi.Connection()'

If there's no readable /etc/brlapi.key file, you'll get a traceback
complaining about it.

Probably we want to do what Arch does here: a brlapi group owning that
file, with 0640 permissionss.
