### ISSUE TITLE
Package request: gcolor3

### ISSUE THREAD

**Issue by EvilHowl** [void-linux/void-packages#12310]
https://www.hjdskes.nl/projects/gcolor3/

`gcolor3` is a much better and newer version of the old and deprecated `gcolor2` that we have.

**Comment by Duncaen** [comment]
Added it, with wayland support breaks it, but gcolor3 wayland support is broken anyways.
https://github.com/void-linux/void-packages/commit/efcd72df5b9d24a9dc9ec27adf4e8efeb8a6d62c
https://github.com/void-linux/void-packages/commit/131f1c221e41710ab2e77f76e1e5a73ba1ac9376
