### ISSUE TITLE
VirtualBox: Error -610 in supR3HardenedMainInitRuntime!

### ISSUE THREAD

**Issue by alekstj** [void-linux/void-packages#1236]
### System

* xuname:  Void 4.17.9_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFF
  *output of ``xuname`` (part of xtools)*
* package:  virtualbox-ose-5.2.12_1
  *affected package(s) including the version*

### Steps to reproduce the behavior
`~ > VirtualBox                                                                                     
VirtualBox: Error -610 in supR3HardenedMainInitRuntime!
VirtualBox: dlopen("/usr/lib/virtualbox/VBoxRT.so",) failed: <NULL>

VirtualBox: Tip! It may help to reinstall VirtualBox.
~ > lsmod | grep vbox                                                                              
vboxpci                28672  0
vboxnetflt             32768  0
vboxnetadp             28672  0
vboxdrv               442368  3 vboxpci,vboxnetadp,vboxnetflt
~ > cat /etc/group | grep vbox                                                                     
vboxusers : x : 986 : alekstj
`

**Comment by cr6git** [comment]
https://github.com/void-linux/void-packages/pull/1193

The update to 5.2.16 fixed the issue for me.
