### ISSUE TITLE
Update Riot-desktop

### ISSUE THREAD

**Issue by Bendodroid** [void-linux/void-packages#12393]
### System

* xuname:  
  Void 5.1.8_1 x86_64 GenuineIntel uptodate rF
* package:  
  `riot-desktop 1.0.8`

Could the maintainer of this package please consider upgrading it from the mid-april version to the recent version `1.2.1`, released about 11 days ago?

Thanks in advance

**Comment by Hoshpak** [comment]
Please don't create update requests, the package is covered by our automatic update check: https://alpha.de.repo.voidlinux.org/void-updates/void-updates_2019-06-11.txt

The fastest way to make an update happen is to create a PR for it.

**Comment by Bendodroid** [comment]
Thanks for the info, won't happen again.
