### ISSUE TITLE
Linux-4.19.50 Boots to a black screen

### ISSUE THREAD

**Issue by HadetTheUndying** [void-linux/void-packages#12412]
### System

* xuname:  Void 5.1.9_1 x86_64 AuthenticAMD uptodate rrrmFFFFFF
* package:  linux-4.19.49, linux-4.19.50
  *affected package(s) including the version*

### Expected behavior
When I boot i usually immediatelly have video output of runit starting up the system and then starting lightdm
### Actual behavior
I never get any video output after the bootloader, the screen remains blank and i have to manually power down my machine, I cannot get into any tty sessions, ect.
### Steps to reproduce the behavior
N/A

I will note that my imgs for 4.19.48 and 5.1,x work fine

**Comment by pullmoll** [comment]
What type is the graphics adapter in your machine?

**Comment by HadetTheUndying** [comment]
AMD RX VEGA 56/64

**Comment by pullmoll** [comment]
You could perhaps search a a `linux5.1-5.1.x` kernel's `dmesg` output for amdgpu command line suggestions:
```
sudo dmesg | grep amdgpu
```
I don't know whether you could or should specify a module option for `amdgpu.si_support` or `amdgpu.cik_support`. Source: [Arch Linux wiki](https://wiki.archlinux.org/index.php/AMDGPU) where some more hints can be found also.

**Comment by HadetTheUndying** [comment]
I'm not having any issues for video output on the 5.1.x  branch of the kernels right now, I'm haivn issues with the past two 4.19.x issues, I can't even get tty in those, I can still boot into 4.19.48 but anything above that i'm getting just a dead black screen and my Motherboard+CPU don't have onboard video so there's now ay of me figuring out what the issue is with that. Nothing meaingful in dmesg about the issues to my knowledge.

**Comment by pullmoll** [comment]
Hmm.. sorry, if the newer kernels provide no hints as to what may be needed for the 4.19 branch I guess you'll have to stick with 5.1.x for now. Fortunately 5.1.x will become the default kernel rather sooner than later /methinks.

**Comment by HadetTheUndying** [comment]
Yeah i certainly hope so. Thanks for the help but yeah i can't figure it out either.

**Comment by pullmoll** [comment]
Since we cannot do much, if anything, on our side of the game, I'll just close this.
