### ISSUE TITLE
doctl package without binaries (wrong build?)

### ISSUE THREAD

**Issue by dan-santana** [void-linux/void-packages#12441]
Currently the `doctl` package only contains a `/usr/share/licenses/doctl/LICENSE.txt` file, so it seems there might be some error in the package's template file.

ping @Noah-Huppert

**Comment by Noah-Huppert** [comment]
Reproduced locally.  

Will fix.

**Comment by Noah-Huppert** [comment]
Fixing, sorry for the deal.

**Comment by Noah-Huppert** [comment]
Gave it a good first try. Ran into some issues. Will continue after work tomorrow.

**Comment by Noah-Huppert** [comment]
I believe I have fixed the issue https://github.com/void-linux/void-packages/pull/13130

**Comment by dan-santana** [comment]
The package is working now, thank you!
