### ISSUE TITLE
zfs: requires `python` to build dkms modules

### ISSUE THREAD

**Issue by emacsomancer** [void-linux/void-packages#12465]
On a clean install, I was unable to get ZFS DKMS modules to build.  They would fail with all kernels; `/var/lib/dkms/zfs/0.8.0/build/config.log` shows:  https://paste.debian.net/1087905/

However, after installing `python` (to check `arc_summary` in case it revealed anything odd), ZFS DKMS built successfully. 

(I know 0.8.0 changed some things from python2 over to python3; whether this is relevant, I'm not sure.)

**Comment by Hoshpak** [comment]
I have both versions of python installed and zfs detects both and decides to use python3 so it's safe to say it works with that.

**Comment by emacsomancer** [comment]
@Hoshpak: it looks like I've only `python3` installed at the moment on the relevant machine. But it seems to require some version of python at any rate.

**Comment by Vaelatern** [comment]
Thanks for catching this, my systems had python so I missed it.

**Comment by emacsomancer** [comment]
@Vaelatern Yeah, it's really only likely to arise on a newly-installed minimal Void setup, as otherwise python is likely to be already installed. Of course, this exact configuration arises when doing a fresh install, which is why I ran into it.
