### ISSUE TITLE
mesa-at-dri-32bit: vulkan icd file not present

### ISSUE THREAD

**Issue by HadetTheUndying** [void-linux/void-packages#12484]
### System

* xuname:  Void 5.1.9_1 x86_64 AuthenticAMD uptodate rrrmDFFFFFFF

* package:  mesa-ati-dri-32bit-19.0.6_1
  *affected package(s) including the version*

### Expected behavior
When Installing the package a 32-bit icd should be placed in 
/usr/share/vulkan/icd.d/
### Actual behavior
No file is placed in the directory it can be manually created point to:
"/usr/lib32/libvulkan_radeon.so"
But some applications will still complain about it and you'll have to manually specify on a per-application basis with VK_ICD_FILENAMES=/path/to/radeon_icd.i686.json(or whatever you've named it)

### Steps to reproduce the behavior
Install the package.

**Comment by kaewhyes** [comment]
I am also experiencing the same issue. A 32-bit icd is not being created on my system.

**Comment by Hoshpak** [comment]
#3293
