### ISSUE TITLE
wicd[-curses]: list index out of range patch

### ISSUE THREAD

**Issue by hereforthebugs** [void-linux/void-packages#12485]
### System

* xuname:  
  Void 4.19.50_1 x86_64 GenuineIntel uptodate rF
* package:  
wicd 1.7.4

### Expected behavior
wicd-curses should allow me to select a network to connect to
### Actual behavior
a python `IndexError: list index out of range` occurs exactly as shown in these two threads that have produced patches that are applied to ![other distros, 2nd item under 2016-01-24](https://ubuntu.pkgs.org/16.04/ubuntu-universe-i386/wicd_1.7.4+tb2-1_all.deb.html)
https://www.linuxquestions.org/questions/slackware-14/wicd-curses-list-index-out-of-range-errors-4175572204/
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812224

Patches have been made it seems, but are not included in void as any use of wicd-curses as of now results in the IndexError.

**Comment by Hoshpak** [comment]
Could you directly create a PR to add the necessary patch?
