### ISSUE TITLE
python3-jupyter: conflicting dependencies

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#12487]
### System

* xuname:  
  Void 5.1.6_1 x86_64-musl GenuineIntel uptodate rrFFFFFFFFFFFFFFFFFFFF
* package:  
python3-jupyter_console
python3-ipython
python3-prompt_toolkit2
python3-prompt_toolkit1

python3-jupyter_console depends on python3-ipython and python3-prompt_toolkit1
python3-ipythonnow depends on python3-prompt_toolkit2
python3-prompt_toolkit1 and python3-prompt_toolkit2 conflict witch each other
change happened in a8d9679d7ad4577838fddb7fe744a60b353b8b11

So systems with python3-jupyter installed can't be upgraded anymore and python3-jupyter can't be installed on other systems.

**Comment by Hoshpak** [comment]
The best way forward seems to be to update `python3-jupyter_console` to 6.0.0 which explicitely requires a 2.x version of prompt_toolkit.

**Comment by daniel-eys** [comment]
Exactly. I'm actually doing this right now to fix this again.
(I split out python3-jupyter_console from python-jupyter_console and update python3-jupyter_console to 6.0.0.)
