### ISSUE TITLE
qupzilla1 fails to load

### ISSUE THREAD

**Issue by avoidr** [void-linux/void-packages#1249]
`qupzilla1-1.8.9_9` fails to load:

```
$ qupzilla
qupzilla: symbol lookup error: /usr/lib/libQupZilla.so.1: undefined symbol: _ZN8Hunspell3addERKSs
```

**Comment by cr6git** [comment]
Probably needs a rebuild after the update of `hunspell` ? https://github.com/void-linux/void-packages/pull/1077
