### ISSUE TITLE
vpnc-0.5.3_6 breaks with iproute2 >= 5.0.0 (and maybe >= 4.10.0)

### ISSUE THREAD

**Issue by pudiva** [void-linux/void-packages#12507]
I was trying to use *vpnc-0.5.3_6* and got this:

```
Error: either "to" is duplicate, or "uid" is a garbage.
```

Then I found some people saying that it came from *iproute2* and indeed downgrading from **5.0.0** to **4.9.0** resolved the issue. I remember **4.10.0** breaking as well, but I may have messed the build so must try again to be sure.

It seems to be coming from the **/etc/vpnc/vpnc-script** file. I'll try to submit a patch.

**Comment by jnbr** [comment]
You could try to use `/usr/libexec/vpnc-scripts/vpnc-script` from the `vpnc-scripts` package.
