### ISSUE TITLE
gscan2pdf needs pdftk!

### ISSUE THREAD

**Issue by sass432** [void-linux/void-packages#12517]
Hallo,

I installed the **"gscan2pdf"** from the official repositories of voidlinux. During the start sequence the programm opens a message, that it needs **"pdftk"** for the _pdf-encryption_.
But **"pdftk"** is not aviable in the official repositories of voidlinux.
Please can you add this tool for the unrestricted funktion of **"gscan2pdf"**!

Thank you for help!

**Comment by misuchiru03** [comment]
I don't know if this would happen. gcc-java used to be part of the `gcc` package, but has been removed from `gcc` and will no longer be maintained; it is required for `pdftk` to be built.  You can try your hand at making a template to build yourself, or if someone is nice and get it for you, that'd be cool. But I think most will turn that down unless they have a vested interest in the product as well.

Archlinux has a few PKGBUILD templates to view in relation to pdftk:
[pdftk](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pdftk)
[gcc-gcj-ecj](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gcc-gcj-ecj) -- required by pdftk
[gcc6](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gcc6) -- required by pdftk and gcc-gcj-ecj

You can use the PKGBUILD as a direction to go for your template creation for these packages (package names may differ, just verify names in the void repo).

**Comment by emacsomancer** [comment]
@sass432 as a quick work-around, you could install `pdftk` via [Nix's standalone package manager](https://nixos.org/nix/manual/). I tried this, and can confirm it works with Void's `gscan2pdf`.

**Comment by Hoshpak** [comment]
We won't be able to re-add pdftk to the official repository so it either needs to be installed by alternate means or just ignore the warning.
