### ISSUE TITLE
Riot Desktop doesn't work

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#12513]
### System

* xuname:  
  `Void 4.19.44_1 x86_64 GenuineIntel uptodate rFFFFFFFF`
* package: 
  `riot-desktop-1.2.1_1`, also with custom build of `1.2.2-rc.1`

### Expected behavior
The *Riot Desktop* window shows up.
### Actual behavior
It throws a `TypeError`, and then does nothing. It can be terminated by two <key>Ctrl</key>+<key>C</key>.
### Steps to reproduce the behavior
Start *Riot Desktop* in a terminal.

**Comment by Hoshpak** [comment]
Upstream issue: https://github.com/vector-im/riot-web/issues/9562
