### ISSUE TITLE
package request: youtube-dl-gui

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#12559]
youtube-dl-gui
https://github.com/MrS0m30n3/youtube-dl-gui

**Comment by daniel-eys** [comment]
Unfortunately, this project is Python2-only. There are open [pull-requests](https://github.com/MrS0m30n3/youtube-dl-gui/pull/350) for a Python3-migration, but the author seems to have [abandoned](https://github.com/MrS0m30n3/youtube-dl-gui/issues/380) the project.

There seems to be a [fork](https://github.com/axcore/tartube), which is still in alpha state.
Maybe `qytdl`, which is already packaged, could act as an alternative.

**Comment by Zig-03** [comment]
>  Maybe `qytdl`, which is already packaged, could act as an alternative.

It isn't as flexible as youtube-dl-gui. You can't download mp3 only files or choose a custom video quality.

**Comment by daniel-eys** [comment]
I see. I'm sorry but I highly doubt youtube-dl-gui will be packaged as Void has stopped accepting new Python2-only packages (Python2 EOL starting with 2020).
The fork mentioned above seems promising, but as upstream says, is still in alpha state.

**Comment by biopsin** [comment]
EOL, please close
