### ISSUE TITLE
Package request: iasl and bison - needed for building Coreboot ROMs

### ISSUE THREAD

**Issue by Zig-03** [void-linux/void-packages#12596]
> https://www.coreboot.org/Build_HOWTO
> Requirements
> iasl (for targets with ACPI support)
> bison (for regenerating parsers)

I'm sorry I don't know where the source code for these two packages resides, and I can't link to them.

**Comment by xtraeme** [comment]
both are available: `acpica-utils (iasl)` and `bison`

**Comment by Zig-03** [comment]
> both are available: `acpica-utils (iasl)` and `bison`

Thank you. It would be great to have `iasl` at least mentioned in `acpica-utils`'s description. So that others can find it just by searching for `iasl`. Would that be doable?
I also need to install `build-essential` but I can't find it in the repos under this name, tho I'd assume it exists under a different one?

**Comment by pullmoll** [comment]
@Zig-03 you should install `xtools`; it contains a tool `xlocate`. Update to the latest locate database with `xlocate -S` and you can then search for `iasl` like this:
```
$ xlocate /usr/bin/iasl
acpica-utils-20190509_1	/usr/bin/iasl
acpica-utils-20190509_1	/usr/bin/iasl
```
BTW I don't know why it is listed twice (at least for me :)
