### ISSUE TITLE
Package Request: obfs4proxy

### ISSUE THREAD

**Issue by yilmzfurkan** [void-linux/void-packages#12599]
**Description:**

For countries where Tor is censored this is an important package which helps people to bypass the censorship. Adding these lines to torrc:
```
UseBridges 1
Bridge <your obfs4 bridge>
ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy managed
```
<s>The only problem looks like they do not tag releases. If its a requirement for Void Linux. I can request them to tag releases in their repository. Let me know.</s>

**Links:**

Upstream: https://gitweb.torproject.org/pluggable-transports/obfs4.git
Gitlab: https://gitlab.com/yawning/obfs4

**Comment by Hoshpak** [comment]
It seems to be properly tagged, you can fetch the tarballs via gitlab, e.g. https://gitlab.com/yawning/obfs4/-/archive/obfs4proxy-0.0.11/obfs4-obfs4proxy-0.0.11.tar.bz2

should be the current version.

**Comment by yilmzfurkan** [comment]
@Hoshpak oh right, sorry. I looked only the releases tab on Gitlab.

**Comment by daniel-eys** [comment]
I'm going to take a look at this if nobody is already working on this.
There are signed sources here: https://people.torproject.org/~yawning/releases/obfs4proxy/
so I'm going to use those.

**Comment by Anachron** [comment]
Honestly since TOR is US government funded it‘s completely useless to use TOR. It just allows them to filter most stuff better as it unites networks from all around the world to a single point of control.

How anybody can use such security related software and not care about this is beyond me.

**Comment by daniel-eys** [comment]
I see your concerns, but we shouldn't turn this issue into a Tor vs US debate.

**Comment by Anachron** [comment]
Sorry, I wasn‘t trying to argue that packaging it should not be done but I kinda think TOR is useless because of the reasons stated above, plus I know a lot of people don‘t know about the things I talked about.

**Comment by daniel-eys** [comment]
Btw. the template is ready: https://github.com/daniel-eys/void-packages/commit/f7ab0591408b1194e387ce15c43a5751fa3ff799
I'm just waiting for the musl-builders to be back up such that Travis works properly again.
