### ISSUE TITLE
Conflict: python3-prompt_toolkit1-1.0.15_3 with python3-prompt_toolkit2_2.0.9_3

### ISSUE THREAD

**Issue by zamlz** [void-linux/void-packages#12636]
### System

* xuname:  
```
CONFLICT: python3-prompt_toolkit1-1.0.15_3 with python3-prompt_toolkit2-2.0.9_3 in transaction (matched by python3-prompt_toolkit2)
Transaction aborted due to conflicting packages.
Void 4.19.50_1 x86_64 AuthenticAMD uptodate rrFF
```
* package:  
```
python3-prompt_toolkit1-1.0.15_3
python3-prompt_toolkit2_2.0.9_3
```

### Expected behavior
When running `sudo xbps-install -Su` I should be able to update the system cleanly.

### Actual behavior
```
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...
CONFLICT: python3-prompt_toolkit1-1.0.15_3 with python3-prompt_toolkit2-2.0.9_3 in transaction (matched by python3-prompt_toolkit2)
Transaction aborted due to conflicting packages.
```

### Steps to reproduce the behavior
Unsure may be because of the packages I have installed, but its when I try to update as mentioned in the __Expected behaviour__ section.

**Comment by CameronNemo** [comment]
What is the result of `xbps-query -m | grep prompt_toolkit`?

**Comment by zamlz** [comment]
That command gives me no output because I never manually installed it. If I use the `-l` flag instead, here is what I get.
```
ii python3-prompt_toolkit1-1.0.15_3        Python3 library for building powerful interactive command lines
```

**Comment by jnbr** [comment]
There currently is no easy way to fix this.

I assume you have `python3-jupyter` installed. The dependencies `python3-jupyter_console` and `python3-ipython` where switched from `python3-prompt_toolkit1` to `python3-prompt_toolkit2`.

The simplest workaround would be to remove `python3-jupyter` and all dependencies with `xbps-remove -R python3-jupyter`, then make sure `python3-prompt_toolkit1` isn't installed anymore, update your system and reinstall `python3-jupyter`.

**Comment by zamlz** [comment]
Yeah I had `python3-ipython`. The workaround still worked. Appreciate it @jnbr!!
