### ISSUE TITLE
podman: unpacks files into /destdir

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#12631]
podman-1.4.2 installs most files into `/destdir`. See `xbps-query -Rf podman`

@CameronNemo

**Comment by Duncaen** [comment]
That might be a good candidate for a lint check in https://github.com/void-linux/void-packages/blob/master/common/hooks/pre-pkg/99-pkglint.sh#L66.

**Comment by CameronNemo** [comment]
@jnbr man files only as far as I can tell

**Comment by jnbr** [comment]
true

**Comment by CameronNemo** [comment]
#12632

**Comment by CameronNemo** [comment]
#12633

**Comment by CameronNemo** [comment]
this can be closed

**Comment by jnbr** [comment]
thank you
