### ISSUE TITLE
Package Request: pp

### ISSUE THREAD

**Issue by TeddyDD** [void-linux/void-packages#12659]
https://adi.tilde.institute/pp/index.html

Coudn't resist, this seems to be really useful tool. We should pester author to add some versioning info tho.

**Comment by TeddyDD** [comment]
okay, author added the version number to release

**Comment by abenson** [comment]
Under `build_style` add `make_use_env=yes`. The template will still fail on cross build, and it needs some work. 

Please open this as a pull request, it'll be easier to track and comment.

**Comment by SolitudeSF** [comment]
can be closed?
