### ISSUE TITLE
Failed to download `linux5.1-5.1.15_1' package

### ISSUE THREAD

**Issue by shumvgolove** [void-linux/void-packages#12691]
`sudo xbps-install -Su` gives this error:
```
[*] Downloading packages
ERROR: [trans] failed to download `linux5.1-5.1.15_1' package from `https://alpha.de.repo.voidlinux.org/current/musl': Not Found
Transaction failed! see above for errors.
```

**Comment by xtraeme** [comment]
This is an infrastructure issue... the xbps repodata archives shouldn't be synchronized before the .xbps archives...

Let's see if the admins fix this :-)

**Comment by shumvgolove** [comment]
Okay, this is fixed. Thanks!
