### ISSUE TITLE
Package Request: citra

### ISSUE THREAD

**Issue by august-0** [void-linux/void-packages#12690]
A Nintendo 3DS Emulator.
**Github Repo:** https://github.com/citra-emu/citra

**Comment by Chocimier** [comment]
There is no release here too.

**Comment by Oreo639** [comment]
Releases are here:
https://github.com/citra-emu/citra-nightly

The repo update very frequently though.
(There can be multiple updates in one day)

Citra's officially recommended method of installation is through flatpak
https://flatpak.citra-emu.org/

**Comment by Chocimier** [comment]
citra-nightly are nightly builds, not stable releases suitable to package. Looks like it need to wait until authors decide to release stable version.

**Comment by Nathan-MV** [comment]
``Releases``
Citra has two main release channels: Nightly and Canary.

The [Nightly](https://github.com/citra-emu/citra-nightly) build is based on the master branch, and contains already reviewed and tested features.

The [Canary](https://github.com/citra-emu/citra-canary) build is based on the master branch, but with additional features still under review. PRs tagged canary-merge are merged only into the Canary builds.

**Comment by paper42** [comment]
They didn't tag a single stable release in the 3 years this issue has been opened, so I think we should just close it.

**Comment by ahesford** [comment]
This definitely looks like a project with no intention to support a stable packaging model.
