### ISSUE TITLE
Package Request: flutter

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#12749]
https://flutter.dev/

**Comment by Anachron** [comment]
Source is here: https://flutter.dev/docs/development/tools/sdk/releases?tab=linux#linux

**Comment by ndgnuh** [comment]
Has anyone working on this yet?

**Comment by RossComputerGuy** [comment]
I added Flutter to my fork's repo (https://github.com/ExpidusOS/packages/blob/d4b35ba2cafb48503c996cdb553725cdafd32d72/srcpkgs/flutter/template). Hopefully this can be a basis of upstream support. I haven't built it yet though.

**Comment by Animeshz** [comment]
Any updates? Should I try adding it?

**Comment by zzaba** [comment]
Yes, please.

**Comment by anddam** [comment]
> Any updates? Should I try adding it?

TBH I ended up just cloning upstream repo at a stable branch and added its bin/ subdirectory to my PATH. Easier to manage version swiches this way.

**Comment by mhmdanas** [comment]
There seems to be some work over at Alpine Linux to package Flutter from source: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/44347

Predictably, it doesn't look trivial at all.

**Comment by zen0bit** [comment]
any update?

Looks like Alpine already packaged to edge repo,
 a moth ago..
