### ISSUE TITLE
Package wol is missing for aarch64

### ISSUE THREAD

**Issue by DBLouis** [void-linux/void-packages#12742]
The package `wol` is missing for aarch64, `xbps-query -Rs wol` returns nothing.
I do not see any architecture blacklist in the [template file](https://github.com/void-linux/void-packages/blob/master/srcpkgs/wol/template).
So why is it not available?

xuname:  Void 4.19.49_1 aarch64  uptodate rFF

**Comment by jnbr** [comment]
Looks like the aarch64 builders never picked it up. Likely because they were introduced after the last update of wol.

**Comment by DBLouis** [comment]
Maybe someone should check that no other packages have the same issue, because I am pretty sure that this is not the first I cannot found on aarch64. But this time I really needed it so I built it myself.

**Comment by xtraeme** [comment]
@DBLouis run `xbps-checkvers -s -D /path/to/void-packages` to see which ones are missing.

**Comment by DBLouis** [comment]
This print all packages, however without the `-s` I get:
```
cross-vpkg-dummy 0.30_1 0.31_1 cross-vpkg-dummy https://mirrors.dotsrc.org/voidlinux/current
font-symbola 11.00_1 12.00_1 font-symbola https://mirrors.dotsrc.org/voidlinux/current
ispc 1.9.2_3 1.10.0_1 ispc https://mirrors.dotsrc.org/voidlinux/current
pcb 4.1.3_1 4.2.0_1 pcb https://mirrors.dotsrc.org/voidlinux/current
```
