### ISSUE TITLE
weston fails without weston-launch

### ISSUE THREAD

**Issue by kanyck** [void-linux/void-packages#12754]
### System
 Void 4.19.56_1 x86_64 GenuineIntel uptodate rF
* package:  
weston-6.0.1_1

### Expected behavior
Weston runs on `weston` command

### Actual behavior
```
fatal: drm backend should be run using weston-launch binary. or your system should provide the logind D-bus API.
fatal: failed to create compositor backend.
```
### Steps to reproduce the behavior
Issue` weston` command. Actually I'm trying to make [this](https://github.com/ehough/docker-kodi) work, so weston-launch won't help (which is working fine, BTW).

This may be relevant:
https://gitlab.freedesktop.org/wayland/weston/issues/204

**Comment by Duncaen** [comment]
We can't fix this, this works as expected afaik.
Maybe you can run `weston` without `weston-launch` if you install `elogind`.
Without `logind`, weston has no permissions to open/take over the drm device, this is where `weston-launch` comes into the mix to provide this functionality without logind.

**Comment by kanyck** [comment]
Of course I've installed elogind, dbus-elogind, dbus-elogind-libs.
But if it's built with
`systemd-login support        no` 
so this behavior is expected and may be fixed as per link I provided.

**Comment by Duncaen** [comment]
Hm I see, this is more a request of getting elogind enabled by default for the weston package.
elogind support in weston is currently a build option which is disabled by default (`./xbps-src -o elogind pkg weston`).

**Comment by kanyck** [comment]
Maybe it's reasonable not to change defaults but add `weston-elogind` instead.

**Comment by mviereck** [comment]
I would assume that a build with elogind option enabled would not cause a problem if weston (or weston-launch)  is started without elogind. Or am I wrong?
If enabling the elogind build option is not a problem, it would be great if it will become a default.

Background: For my project [x11docker](https://github.com/mviereck/x11docker) I need to run `weston &`in background. This works well e.g. on Debian. But `weston-launch &` fails, it insists to be started in foreground.

**Comment by xtraeme** [comment]
If you expect `weston` to run you'll need elogind... otherwise the setuid one `weston-launch`.

There's no issue here.

**Comment by mviereck** [comment]
> If you expect weston to run you'll need elogind [ ... ] There's no issue here.

The issue here is that the weston built in void does not have elogind support enabled. Or did that change meanwhile?

**Comment by xtraeme** [comment]
`./xbps-src -o elogind pkg weston`

**Comment by mviereck** [comment]
So you suggest a custom rebuild of weston? Ok, thanks!

**Comment by xtraeme** [comment]
This is what build options are for
