### ISSUE TITLE
nginx http/2 aarch64 musl issue

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#12814]
### System

* xuname:  
  `Void 4.19.49_1 aarch64-musl  uptodate rFF`
* package:  
  * `nginx-1.16.0_2`

### Expected behavior

enable http2, get successful response

### Actual behavior

```
-bash-5.0# curl https://hostname
curl: (16) Error in the HTTP2 framing layer
```

### Steps to reproduce the behavior

install nginx, enable http2, curl/go to the link

[![asciicast](https://asciinema.org/a/KFE7ZjTHBm3p4qdlKubCBLqPF.svg)](https://asciinema.org/a/KFE7ZjTHBm3p4qdlKubCBLqPF)

**Comment by shumvgolove** [comment]
Can confirm.

**Comment by makmm** [comment]
@shumvgolove aarch64 musl too?

**Comment by shumvgolove** [comment]
**@makmm** Yeah.

**Comment by makmm** [comment]
Please fix :3

**Comment by paper42** [comment]
I can not reproduce this bug, the original author is a ghost and this issue is 2 years old, closing.

**Comment by Duncaen** [comment]
yes pretty sure this was the same issue resolved in https://github.com/void-linux/void-packages/issues/30945.
