### ISSUE TITLE
gst1-python{,3} file collision

### ISSUE THREAD

**Issue by nonchip** [void-linux/void-packages#12810]
xbps-update refuses to install a file collision for `libgstpython.so` because of python2/3 coexistence.

### System

* xuname:  
  `Void 5.1.5_1 x86_64 AuthenticAMD notuptodate rrrrmmnFFFFFFF`
* package:  
  * `gst1-python3-1.16.0_1`
  * `gst1-python-1.16.0_1`

### Expected behavior

this is a weird template, but i guess i'd expect it to not collide :stuck_out_tongue_closed_eyes: 

also i'd kinda expect libgstpython (which is a gstreamer binding for python, not a python interpreter for gstreamer) to live inside the python folders, not the gstreamer folders... this would also fix the collision because python2/3 have separate module folders.

### Actual behavior

```
ERROR: gst1-python3-1.16.0_1: file `/usr/lib/gstreamer-1.0/libgstpython.so' already installed by package gst1-python-1.16.0_1.
```

### Steps to reproduce the behavior

```bash
sudo xbps-install -Su
```

**Comment by Johnnynator** [comment]
Mopidy doesn't fully support Python 3 yet  https://github.com/mopidy/mopidy/issues/779
So just dropping the py2 package as the easy version is not possible :(

Also the location of the lib is correct and to my knowledge can't be changed. But I need to check for which situations exactly they are needed. e.g. Arch is just deleting the python2 `libgstpython.so'`

**Comment by nonchip** [comment]
for the record i didn't mean to say the location is maintained incorrect (as in: different from what the developer chose), rather it seems logically wrong, because most other python packages are in `/usr/lib/python${version}/`. because `libgstpython.so` is not a library for use by gstreamer, but by python (to talk to gstreamer).

**Comment by paper42** [comment]
gst1-python was removed in eafbbfa5f0304df8a7ed291252bd3fd140b6e2e0
