### ISSUE TITLE
amdgpu randomly crashing with  linux5.1.16

### ISSUE THREAD

**Issue by HadetTheUndying** [void-linux/void-packages#12853]
### System

* xuname: 
Void 5.1.16_1 x86_64 AuthenticAMD notuptodate hold rrrmFFFFFFFFF 

* package: linux5.1.16 

### Expected behavior
No Random Crashing.

### Actual behavior
Occassionally the screen will go corrupted and just lock up it then spams tty with these errors
[54948.226250] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
### Steps to reproduce the behavior
Running a game it just happens randomlly I forgot to take a picture of the screen corruption but it's the standard pixelated rainbow stuff. Restarting the Display Manager got me back into the display manager but it's still spamming tty.

I'll attach the full output of dmesg
[dmesg.log](https://github.com/void-linux/void-packages/files/3365018/dmesg.log)

**Comment by HadetTheUndying** [comment]
Not to spam but here's dmesg from 5.1.15
[dmesgfor5.1.15.log](https://github.com/void-linux/void-packages/files/3365024/dmesgfor5.1.15.log)

**Comment by Hoshpak** [comment]
There's not much we can do about it other than waiting for the kernel developers to release a fix. There's also another issue with Vega cards that keeps 5.1 from becoming the default kernel. If it hasn't already been done, you could report the issue upstream. Other than that, I suggest you downgrade to 4.19 which is still the default kernel version. If you are adventourus, you could also compile 5.2-rc7 yourself and test if that works any better.

**Comment by HadetTheUndying** [comment]
I can't downgrade because I can't even get Kernel 4.19.x to boot into tty after 4.19.48. 

I misunderstood your previous request for dmesg output on my bug report regarding that and you closed the issue before i could re-read it and followthrough. The second dmesg log i attached it what you requested for that bug report.

**Comment by Hoshpak** [comment]
Now that 5.2 is out and in the repository, you could try that version if it works any better for you. If you have the time and CPU power to build the kernel again and again, you could also grab either the 4.9.x or 5.1.x stable branches and run git bisect against it to determine what commit is causing the issues for you.

**Comment by HadetTheUndying** [comment]
I'll give 5.2 a shot. I'll also see about bisecting what changed when I have time this weekend, I'll keep this open for now if that's alright

**Comment by HadetTheUndying** [comment]
Updating this issue with dmesg output. Will see if i can reproduce in Kernel 5.2 tomorrow.
[dmesg.txt](https://github.com/void-linux/void-packages/files/3396641/dmesg.txt)

**Comment by HadetTheUndying** [comment]
appears to not be present in Kernel 5.2 looks like it might also be related to the latest firmware, closing.

**Comment by HadetTheUndying** [comment]
nevermind it's still happening

**Comment by HadetTheUndying** [comment]
Final Reply sorry for the spam, this is an xorg problem, I have no had this happen since switching to wayland, i have no idea what the cause is anymore or what instruction xorg is sending that amdgpu doesn't like.

**Comment by HadetTheUndying** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=109955 looks to be not releated to Void, so i'm closing this again will wait for a patch
