### ISSUE TITLE
Package Request: searx

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#12888]
https://github.com/asciimoo/searx

> Privacy-respecting metasearch engine

Dependencies:
https://github.com/asciimoo/searx/blob/master/requirements.txt

> certifi==2019.3.9
> flask-babel==0.12.2
> flask==1.0.2
> idna==2.8
> jinja2==2.10.1
> lxml==4.3.3
> pygments==2.1.3
> pyopenssl==19.0.0
> python-dateutil==2.8.0
> pyyaml==5.1
> requests[socks]==2.22.0

**Comment by silvernode** [comment]
I can get behind this request! I run my own searx instance and have done so for over a year. It's a fantastic project to aggregate queries from a bunch of search engines while keeping things private.. Having his in Void would allow users to get an instance of searx deployed quick and easy. If this gets packaged, to the best of my knowledge Void Linux would be the first and only distro to have searx in it's repositories.

**Comment by FollieHiyuki** [comment]
@silvernode you have update on this?
Look at their requirements, we only needs `python3-pyyam` and `python3-langdetect` as well

**Comment by silvernode** [comment]
> @silvernode you have update on this?
> Look at their requirements, we only needs `python3-pyyam` and `python3-langdetect` as well

I will take a look again. They did switch to python 3 since this request and it looks easier now

**Comment by FollieHiyuki** [comment]
Nice. I'm willing to take the tester role if you open a PR.
