### ISSUE TITLE
Default keyboard shortcuts of Spectacle (screenshot utility) do not work on KDE Plasma

### ISSUE THREAD

**Issue by glaubersm** [void-linux/void-packages#12887]
### System

* xuname:  
  Void 5.1.16_1 x86_64 GenuineIntel notuptodate rrFFF

* package:
  spectacle 19.04.2_1

### Expected behavior
all default shortcuts (print, shift+print, meta+print and meta+shift+print
work.

### Actual behavior
nothing happens when you press any default shortcut (print, shift+print, meta+print and meta+shift+print)

### Steps to reproduce the behavior
start kde plasma session
press any shortcut mentioned above

I also noticed that Spectacle does not open when I click on its shortcut 
in the apps launcher. Run "spectacle" in terminal opens Spectacle and it works as expected.

**Comment by Johnnynator** [comment]
Can you provide the output of `qdbus org.kde.Spectacle / StartAgent`?

**Comment by glaubersm** [comment]
Here is the output:

`qdbus: could not find a Qt installation of ''`

**Comment by Johnnynator** [comment]
Can you try installing `qt5-tools`? I think that package is the missing piece.

**Comment by glaubersm** [comment]
All shortcuts work as expected after I install qt5-tools package.
