### ISSUE TITLE
i2pd symbol lookup error

### ISSUE THREAD

**Issue by non-Jedi** [void-linux/void-packages#1289]
### System

* xuname:  
  *Void 4.17.9_1 x86_64 GenuineIntel uptodate rrFF*
* package:  
  *i2pd-2.15.0_4*

### Expected behavior

i2pd starts as expected.

### Actual behavior

```
adam: [~] $ i2pd
i2pd: symbol lookup error: i2pd: undefined symbol: _ZNK5boost15program_options22error_with_option_name23substitute_placeholdersERKSs
```

### Steps to reproduce the behavior

Run `i2pd` in any terminal emulator.

This problem started after updating Void yesterday. Before yesterday, I had been on vacation for a week and had not updated in that time.

**Comment by maxice8** [comment]
should be fixed by https://github.com/void-linux/void-packages/commit/adfb036ae3eaba8b39e059b60ccb4fb532f95238
