### ISSUE TITLE
Package Request: qbittorrent-nox

### ISSUE THREAD

**Issue by gorkoda1** [void-linux/void-packages#1290]
the package qbittorrent doesn't contain qbittorrent-nox (on i686 atleast).
a runit service would also be highly appreciated.
https://github.com/qbittorrent/qBittorrent/wiki/Running-qBittorrent-without-X-server.

**Comment by maxice8** [comment]
it is available in the repos now thanks to @pullmoll

**Comment by gorkoda1** [comment]
thanks everyone for taking their time

**Comment by pullmoll** [comment]
I did not write a runit service as I don't know whether or not it should be run as a system user and what config defaults to use. If you want to add a service, please create a PR for qbittorrent-nox.
