### ISSUE TITLE
Package Request: nvidia 32-bit libraries

### ISSUE THREAD

**Issue by tuxbay** [void-linux/void-packages#12923]
I'm trying to run the latest version of my tax software, but WINE seems to require OpenGL in order to run it. I vaguely remember that the nvidia installer asks whether to install the 32-bit libraries on x64 machines, but there does not seem to be a corresponing -32bit xbps package.

### System

* xuname:  Void 5.0.21_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFFFF
* package:  nvidia-libs 430.14_2

### Expected behavior

The program starts.

### Actual behavior

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  199
  Current serial number in output stream:  198

### Steps to reproduce the behavior

wine .wine/drive_c/Program\ Files/WISO/Steuersoftware\ 2019/WISO2019.EXE

**Comment by Hoshpak** [comment]
`nvidia-libs-32bit` from the multilib repository should do the trick.

**Comment by tuxbay** [comment]
Thanks for the quick response. I was looking for a package with this name, but I did not have the multilib-nonfree repository enabled. Fixed now. Sorry for the noise.
