### ISSUE TITLE
xbps-src breakages after e4984d01ea049e7cde260fc1a05d61fbdd403180

### ISSUE THREAD

**Issue by q66** [void-linux/void-packages#12992]
I added these as inline comments in e4984d01ea049e7cde260fc1a05d61fbdd403180 already but just for better tracking

1) something in this broke sort-dependencies; see https://gist.github.com/q66/265129ca7a2075a09cc153ae13055771 - this should only print out packages in the input list (or at least that's how it behaved previously) - it doesn't make sense as it is right now because that makes it useless for cases it was useful for previously (as this includes all the host as well as target build deps, so you can't use it to say, cross-rebuild specific packages of a repo correctly)

2) xbps-src now passes `-i` to `checkvers` and other utils when remote repos are skipped, which is incorrect because then it will not respect local repos; that results in cross-compilation with `-N` and `-r` being broken, because it will not attempt to use `hostdir/binpkgs` for host packages like it did till now (they're specified in repos-local.conf)

3) additionally, this is not a bug in `xbps-src` but rather in `xbps` itself - `xbps-remove -o` does not remove all autoinstalled packages, which this revision seemingly tried to workaround by running it twice, but i've had cases where it's needed to run it as many as 5 or 6 times to actually remove all autodeps; it also doesn't try to workaround correct removal of autocrossdeps.

@xtraeme

**Comment by xtraeme** [comment]
Fixed a while ago...
