### ISSUE TITLE
Unresolved dependencies for telegram-desktop

### ISSUE THREAD

**Issue by rc-05** [void-linux/void-packages#12993]
### System

* xuname:  
  Void 5.2.0_1 x86_64 AuthenticAMD uptodate rFF
* package:  
  * telegram-desktop-1.7.14_1

### Expected behavior
The package should install the latest qt5 version with all the dependencies required.

### Actual behavior
Installation is aborted due to unresolved dependencies.

### Steps to reproduce the behavior
```
[raf@void ~]$ sudo xbps-install -Su telegram-desktop
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
MISSING: qt5>=5.11.3<5.11.4
Transaction aborted due to unresolved dependencies.
```

_Notes: I've also tried to install qt5 and telegram-desktop separately but to no avail._

**Comment by Johnnynator** [comment]
Yes this is intended. Will be resolved within the next few hours. The builders are working on it
