### ISSUE TITLE
Dracut message on system boot

### ISSUE THREAD

**Issue by shumvgolove** [void-linux/void-packages#13024]
`Void Linux 5.0.21_1`
When Void Linux boots, TTY shows this line:
```
//lib/dracut/hooks/pre-mount/10-resume.sh: line 20: echo: write error: Invalid argument rw, relatime
```
Things I've tried:
- `xbps-reconfigure -f linux5.0`
- `dracut -f -H`
- Searching in Dracut repository for `10-resume.sh` – [here](https://github.com/dracutdevs/dracut/blob/bca1967c90967d5453d8b215ff28552776e4fcb3/modules.d/95resume/parse-resume.sh#L78)

Search gave me [this](https://bugzilla.redhat.com/show_bug.cgi?id=872878) result (not really useful tho).

**Comment by zdykstra** [comment]
What's your /proc/cmdline value, and what filesystem are you using?

**Comment by shumvgolove** [comment]
`[root@local ~]# /proc/cmdline`
```
BOOT_IMAGE=/boot/vmlinuz-5.0.21_1 root=UUID=bf9295b9-21f1c-4cd9-acef-44faeee4cc82 ro loglevel=4 slub_debug=P page_poison=1
```
`[root@local ~]# df -Th`
```
Filesystem     Type      Size  Used Avail Use% Mounted on
devtmpfs       devtmpfs  3.9G     0  3.9G   0% /dev
tmpfs          tmpfs     3.9G     0  3.9G   0% /dev/shm
tmpfs          tmpfs     3.9G  756K  3.9G   1% /run
/dev/sdf3      ext4       30G  2.0G   27G   8% /
cgroup         tmpfs     3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sdf2      vfat     1022M  148K 1022M   1% /boot/efi                  
/dev/sdf4      ext4       84G   57M   84G   1% /home
tmpfs          tmpfs     3.9G     0  3.9G   0% /tmp
```

**Comment by shumvgolove** [comment]
After updating system packages, TTY shows 6 entries of `scandir: No such file or directory` besides dracut message.

**Comment by Duncaen** [comment]
Run `xbps-pkgdb -a` to see if there are some missing files, links or hashsum mismatches.

**Comment by shumvgolove** [comment]
Nope. Nothing shows.

**Comment by shumvgolove** [comment]
Following [this guide](https://wiki.voidlinux.org/Install_Void_Linux_onto_a_USB_Stick) I've installed another Void system into USB stick. `scandir` and `dracut` error messages still persist. Maybe it somehow connected that dracut uses `/proc/self/mountinfo`?

**Comment by PillTime** [comment]
This happens to me too. (I use [this]() to guide myself, might be helpful).
I installed both the glibc version and the musl version on VirtualBox in the exact same way:
- The line `//lib/dracut/hooks/pre-mount/10-resume.sh: line 20: echo: write error: Invalid argument rw, relatime` only shows up in the musl version.
- The `scandir` errors show up in both versions.

**Comment by shumvgolove** [comment]
Happy to report that with recent updates `scandir` messages is gone, however `dracut` message still hanging there.

**Comment by PillTime** [comment]
I know this is old but I think I found a way to solve this.
If you don't want hibernation, you can just add `omit_dracutmodules+="resume"` to your dracut config and regenerate your initramfs.
If you do want hibernation, edit the file `/usr/lib/dracut/modules.d/95resume/resume.sh` and change the line
```
echo "${maj%,}:$min"> /sys/power/resume)
```
 to 
```
echo $maj:$min | tr -d , > /sys/power/resume)
```
.
It's a bit of a hack (and I don't know if it'll persist through an update), but it works.

**Comment by ericonr** [comment]
Out of curiosity, I imagine you don't get the same issue if you set `noresume` in the kernel cmdline, right?

That looks more like a possible dracut bug than anything else. Have you tried reporting it to upstream? Could be useful.

**Comment by PillTime** [comment]
Using `noresume` also works.
Yeah I guess it's a dracut problem. Something with [its echo command](https://git.kernel.org/pub/scm/boot/dracut/dracut.git/tree/modules.d/95resume/resume.sh#n20) causes an invalid argument error somehow.
Doing `ls -lH /dev/sda3 | (read x x x x maj min x; echo "${maj%,}:$min")` manually gives the expected output, so I'm not sure what's the problem, but using `echo $maj:$min | tr -d ,` solves it.
Not really sure how to report the bug. Never had to do it outside of github.

**Comment by ericonr** [comment]
It's likely the mailing list at the bottom here: https://dracut.wiki.kernel.org/index.php/Main_Page

Do you use IRC? They seem to have a channel on freenode. You might be able to discuss it a bit there, but I would definitely recommend using the mailing list instead. If you can create a git diff with your change, that will likely be even better.

**Comment by PillTime** [comment]
Alright, thanks. I've sent a bug report to the mailing list.
I guess this issue can be closed since it's a dracut problem.

**Comment by ericonr** [comment]
Should be okay to track it here, if you want. Specially if we need to update because of the fix or anything.

**Comment by foopub** [comment]
I realise this is a dracut issue, hence not the best place to bring it up but they've been sleeping on the bug for a while.

First of all, why not stat? Seems way more reasonable than the spaghetti ls parse:

`(stat "$resume" -c %t:%T > /sys/power/resume)>/.resume` 

Surely I'm missing something?? Putting just `stat "$resume" -c %t:%T` in resume.sh in the file prints the maj:min numbers on just fine on the other hand :thinking: 

That said, I tried using that but now I get stat write error :sweat_smile:

**Comment by foopub** [comment]
This is very weird. I did some testing and, while it functions just fine 
`(stat "$resume" -c %t:%T | tr -d , > /sys/power/resume)>/.resume`  gives tr: write error
`(stat "$resume" -c %t:,%T | tr -d , > /sys/power/resume)>/.resume`  no error

**Comment by ahesford** [comment]
Herewith, a couple of observations:
- The write error is not from `stat`, `tr` or anything like that. It's the kernel rejecting the values you're trying to write to `/sys/power/resume`.
- The output of the `ls` scrape is *not* the same as that from `stat`. `ls` prints device types in decimal, but `stat` prints hex values:
```
% ls -lH /dev/watchdog
crw------- 1 root root 10, 130 Jan 25 23:43 /dev/watchdog

% stat /dev/watchdog -c '%t:%T'
a:82
```
- Sometimes these sysfs writes are finicky, and a terminating newline can cause a problem. In the original `ls` scrape, you can try `echo -n` to suppress the new line. In the `stat` version, you can use `tr -d '\n'`.

**Comment by foopub** [comment]
> Herewith, a couple of observations:
> 
>     * The write error is not from `stat`, `tr` or anything like that. It's the kernel rejecting the values you're trying to write to `/sys/power/resume`.
> 
>     * The output of the `ls` scrape is _not_ the same as that from `stat`. `ls` prints device types in decimal, but `stat` prints hex values:
> 
> 
> ```
> % ls -lH /dev/watchdog
> crw------- 1 root root 10, 130 Jan 25 23:43 /dev/watchdog
> 
> % stat /dev/watchdog -c '%t:%T'
> a:82
> ```
> 
>     * Sometimes these sysfs writes are finicky, and a terminating newline can cause a problem. In the original `ls` scrape, you can try `echo -n` to suppress the new line. In the `stat` version, you can use `tr -d '\n'`.

Aight, good points! It seems the kernel won't accept wrong values in the correct format either. Running `stat $resume -c %t:%T | tr -d '\n'` inside the script actually prints 0:0 (instead of 8:3 which is my swap file) and is also rejected.

Perhaps the stem of the issue is $resume pointing to the wrong thing?

**Comment by foopub** [comment]
Welp... It turns out `/sys/power/resume` can take a path format too, i.e. /dev/sda3

`(readlink -fn $resume > /sys/power/resume)>/.resume` is by far the best solution.
