### ISSUE TITLE
Power management does not work on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [void-linux/void-packages#13030]
### System

* xuname:  
Void 5.1.16_1 x86_64 GenuineIntel notuptodate rrFFF
* package:  
powerdevil 5.16.3
--

### Expected behavior
all power management settings work
### Actual behavior
none power management setting works.
This problem does not occur on X11 session.
### Steps to reproduce the behavior
use Void with KDE Plasma desktop environment and SDDM login manager
start Wayland session (select "Plasma (Wayland)" in login manager)
right click on battery icon in systray, select "Configure Power saving..."
set the timeout to turn off your screen, the timeout to suspend your system and the action
triggered when you press the power button.
Result: no settings take effect

**Comment by travankor** [comment]
Cannot reproduce, everything works fine here.

I don't have sddm but am using elogind, make sure to turn off acpid since elogind mostly replaces acpid.

**Comment by glaubersm** [comment]
Turning off acpid solved the problem with the power management. Thanks,
But now I have another problem: I replaced consolekit with elogind and now pulseaudio stops working randomly. No sound through the speakers.

**Comment by glaubersm** [comment]
I forgot to say that pulseaudio stops working after relogin.
For example, I resart plasma session, play an audio with some player
and the audio works. Then I close the player, I try to play another audio with
another player then I can't listen anything through my speakers.
Pulseaudio works again after reboot.
Pulseaudio was working fine with consolekit2.

**Comment by travankor** [comment]
No idea, sorry. I don't use pulseaudio but didn't experience that when I (briefly) tried pulse out. Usually your problem happens when you're using plain ALSA without a sound server. Maybe try kmix with pulseaudio?

**Comment by xtraeme** [comment]
Can't reproduce, please reopen if the problem still exists
