### ISSUE TITLE
lyx fails to start

### ISSUE THREAD

**Issue by scaramacai** [void-linux/void-packages#1304]
### System

* xuname:  
  *Void 4.17.6_1 x86_64-musl GenuineIntel/KVM uptodate rF)*
* package:  
  *lyx-2.3.0_2*

xbps-query lyx gives the following
architecture: x86_64-musl
build-date: 2018-03-17 23:36 CDT
filename-sha256: 4fac6edbb3484e67ad161e6c873dfb994f5df9ac740848d1ba619bdaefb6bfa3
filename-size: 18MB
homepage: http://www.lyx.org/Home
install-date: 2018-07-30 09:57 CEST
install-msg: 807B
install-script: 960B
installed_size: 60MB
license: GPL-2
maintainer: Juan RP <xtraeme@voidlinux.eu>
metafile-sha256: 8a4d6beb1086a9855fb60b1ad8e9b4e3a86863fc913ab496012c65697b0c4581
pkgver: lyx-2.3.0_2
remove-script: 958B
repository: https://repo.voidlinux.eu/current/musl
shlib-requires:
	libmythes-1.2.so.0
	libenchant.so.1
	libhunspell-1.6.so.0
	libmagic.so.1
	libz.so.1
	libQt5Svg.so.5
	libQt5Widgets.so.5
	libQt5Gui.so.5
	libQt5Core.so.5
	libstdc++.so.6
	libgcc_s.so.1
	libc.so
short_desc: The Document Processor WYSIWYM Editor & Latex frontend
source-revisions: lyx:7131fa4809
state: installed

### Expected behavior
Should work flat
### Actual behavior
Fails to start, giving the following errors:
Error relocating /usr/bin/lyx: _ZN8Hunspell3addERKSs: symbol not found
Error relocating /usr/bin/lyx: _ZN8Hunspell6removeERKSs: symbol not found
### Steps to reproduce the behavior
Just install lyx and launch from a terminal

**Comment by maxice8** [comment]
should be fixed by https://github.com/void-linux/void-packages/commit/9d3092cc81d74bbf8431d53d54e603067ff965f1
