### ISSUE TITLE
Package Request: srs

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#13114]
Homepage: https://github.com/ossrs/srs

Description:
> SRS is an industrial-strength live streaming cluster, with the best conceptual integrity and the simplest implementation.

License: MIT
Source: https://github.com/ossrs/srs/releases

**Comment by knusbaum** [comment]
If if upstream wants to remove stuff like this, I'll package it. I don't really want to patch around it. Someone else is free to.
https://github.com/ossrs/srs/blob/6e6e996bbaee73473f2ace76b7cb45a065368e7c/trunk/auto/depends.sh#L383-L397
```
#####################################################################################
# check the os.
#####################################################################################
# user must specifies something what a fuck, we suppport following os:
#       centos/ubuntu/osx,
#       cross build for embeded system, for example, mips or arm,
#       directly build on arm/mips, for example, pi or cubie,
#       export srs-librtmp
# others is invalid.
if [[ $OS_IS_UBUNTU = NO && $OS_IS_CENTOS = NO && $OS_IS_OSX = NO && $SRS_EXPORT_LIBRTMP_PROJECT = NO ]]; then
    if [[ $SRS_PI = NO && $SRS_CUBIE = NO && $SRS_CROSS_BUILD = NO ]]; then
        echo "what a fuck, os not supported."
        exit 1
    fi
fi

```

**Comment by Anachron** [comment]
Yeah nevermind... this is unacceptable.
