### ISSUE TITLE
 nodejs-9.10.0_2.x86_64: All npm calls fail due to missing module

### ISSUE THREAD

**Issue by bchociej** [void-linux/void-packages#1313]
### System

* xuname:  
  Void 4.14.18_1 x86_64 GenuineIntel notuptodate rDFFFFFF - My only suggested update is the bad nodejs version; everything else is up to date.
* package:  
  nodejs-9.10.0_2.x86_64.xbps

### Expected behavior
`npm` calls should work correctly

### Actual behavior
`npm` calls always result in this error:

```# npm i
module.js:545
    throw err;
    ^

Error: Cannot find module 'is-fullwidth-code-point'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/string-width/index.js:4:28)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

### Steps to reproduce the behavior
1. Run apparently any `npm` command with nodejs-9.10.0_2.x86_64.xbps installed
2. See the above error

I reproduced this error after removing and reinstalling the bad version. Downgrading to nodejs-9.4.0_2.x86_64.xbps fixes the problem.

**Comment by chneukirchen** [comment]
Is this related to the overlong paths?

**Comment by bchociej** [comment]
I'm not sure what you're referring to. The package directory `/usr/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/string-width/node_modules/is-fullwidth-code-point` exists but is empty. Whereas other global packages have the same dependency (at even deeper filesystem depth) and the directory there is not empty.

**Comment by julio641742** [comment]
@bchociej The file path [1] is 127 characters long is affected by  [void-linux/xbps#2](https://github.com/void-linux/xbps/issues/2)

**Comment by jtl999** [comment]
Would've have been nice to know this is a known bug. 

Prevents me from updating riot-desktop and some other things I need.

**Comment by maxice8** [comment]
should be fixed by https://github.com/void-linux/void-packages/commit/692edab29ad2a3a8c1a462af8d6f88f7ce36aa28
