### ISSUE TITLE
Updates for the Minecraft package?

### ISSUE THREAD

**Issue by Wychmire** [void-linux/void-packages#13139]
This is not a package request.

The current minecraft template installs the fifth iteration of the minecraft launcher. Minecraft is up to it's seventh iteration and is considerably different from the fifth, especially in that it uses Electron instead of whatever it used before (java?). You can take a look at the visual difference by looking at this [image of the older launcher](https://gamepedia.cursecdn.com/minecraft_gamepedia/a/a5/Launcher-1.6.png) and [this one of the newer launcher](https://gamepedia.cursecdn.com/minecraft_gamepedia/7/76/2019Launcher.png)

As long as the fifth launcher is available from the URL it uses I feel like it should still be installable since it's electron free and still works great, but maybe that's just me being nostalgic? 

I've already written a working template which I've installed and am using. I've pushed it to the [minecraft-launcher branch](https://github.com/Wychmire/void-packages/tree/minecraft-launcher/srcpkgs/minecraft-launcher) in my fork.

So my thinking was either
1. The `minecraft` package sticks around as-is and the new launcher is added as `minecraft-launcher` or,
2. The `minecraft` package is updated to use the new launcher and the old one is **a)** renamed to `minecraft-legacy`, `minecraft-launcher-legacy` or something similar or **b)** deleted.

Thoughts?

**Comment by Wychmire** [comment]
Both #14268 and #14221 are related to this.

**Comment by toluschr** [comment]
I think 1) would be the best solution. However the `minecraft` package could be changed a little too. It does not have a .desktop file and the dependency `openjdk-jre` is missing.

**Comment by Wychmire** [comment]
There isn't a dependency on `openjdk-jre` since you can also use `oracle-jre`. It's mentioned in the INSTALL.msg file.
Something like this should work to let the user choose which JRE they want (though they'd have to custom build it if they wanted oracle-jdk)
```
[...]
depends="[...] $(vopt_if openjdk "openjdk-jre") $(vopt_if oracle "oracle-jre")"
[...]

build_options="openjdk"
build_options="oracle"

desc_option_openjdk="Use openjdk-jre as the jre dependency"
desc_option_oracle="Use oracle-jre as the jre dependency"

build_options_default="openjdk"
vopt_conflict openjdk oracle

[...]
```

**Comment by Johnnynator** [comment]
You should take a look at virtual deps` depends="virtual?java-runtime"` is probably what you are searching, this would default to openjdk-jre, but would also be satisfied by `oracle-jre`

**Comment by Wychmire** [comment]
That's much, much cleaner. Thanks for letting me know about that!

**Comment by Wychmire** [comment]
I'd hate to limit people to an electron app when there's an alternative but if that's the route this ends up going I think definitely the name should be `minecraft-launcher` to match the tar file. 

Based on my personal testing it looks like the legacy minecraft launcher just doesn't work for 1.14.4. 1.14.3 and back seem to work no problem.

My ideal path would be changing the current `minecraft` package's description to including something like (legacy launcher) and adding a note about how from 1.14.4 onwards it doesn't work well inside the INSTALL.msg file and making `minecraft-launcher` the maintained electron version.

It seems a little unlikely Void is high enough on the radar for Mojang to bother. IIRC the only reason Arch got it's official AUR package is because one of the minecraft folks uses Arch and is maintaining the package.

**Comment by MattTreadwell** [comment]
Good point. I can work on a`minecraft-legacy` package with updated dependencies, install message, and proper licensing. IMO, it seems a bit misleading to have the `minecraft` package not even work on the latest version.

**Comment by Chocimier** [comment]
`minecraft` got removed, MultiMC is suggested alternative.
