### ISSUE TITLE
efibootmgr: post-remove kernel hook error when removing old kernel package

### ISSUE THREAD

**Issue by ackalker** [void-linux/void-packages#13133]
### System

* xuname:  
  Void 5.1.17_1 x86_64 GenuineIntel uptodate rrrrmdFFFFFFFFF
* package:  
  efibootmgr-17_3

### Expected behavior

When removing old kernel package (using for instance `vkpurge rm`), the post-install kernel hooks should finish without any errors due to bugs.

### Actual behavior

When I removed an old kernel on my system using `vkpurge rm`, the 50-efibootmgr post-install kernel hook produced the error: `efibootmgr: option requires an argument -- 'b'`

### Steps to reproduce the behavior

- On a system with multiple kernel packages installed, use `xbps-remove` or `vkpurge rm` to remove a kernel package version which is in the same `major.minor` range but older than the latest installed version in that range.

**Comment by ackalker** [comment]
Output of running `vkpurge rm ...` on my system last afternoon:

```
# vkpurge rm 4.19.57_1
Removing kernel 4.19.57_1...
Running pre-remove kernel hook: 10-dkms...
dkms: removing: nvidia 430.14 (kernel-4.19.57_1) (x86_64)
dkms: removing: virtualbox-ose 6.0.8 (kernel-4.19.57_1) (x86_64)
Removing /boot/vmlinuz-4.19.57_1...
Removing /usr/lib/modules/4.19.57_1...
Running post-remove kernel hook: 20-dracut...
Running post-remove kernel hook: 50-efibootmgr...
efibootmgr: option requires an argument -- 'b'
efibootmgr version 17
usage: efibootmgr [options]
	-a | --active         sets bootnum active
	-A | --inactive       sets bootnum inactive
	-b | --bootnum XXXX   modify BootXXXX (hex)
	-B | --delete-bootnum delete bootnum
	-c | --create         create new variable bootnum and add to bootorder
	-C | --create-only	create new variable bootnum and do not add to bootorder
	-D | --remove-dups	remove duplicate values from BootOrder
	-d | --disk disk       (defaults to /dev/sda) containing loader
	-r | --driver         Operate on Driver variables, not Boot Variables.
	-e | --edd [1|3|-1]   force EDD 1.0 or 3.0 creation variables, or guess
	-E | --device num      EDD 1.0 device number (defaults to 0x80)
	-g | --gpt            force disk with invalid PMBR to be treated as GPT
	-i | --iface name     create a netboot entry for the named interface
	-l | --loader name     (defaults to "\EFI\void\grubx64.efi")
	-L | --label label     Boot manager display label (defaults to "Void Linux (GRUB2)")
	-m | --mirror-below-4G t|f mirror memory below 4GB
	-M | --mirror-above-4G X percentage memory to mirror above 4GB
	-n | --bootnext XXXX   set BootNext to XXXX (hex)
	-N | --delete-bootnext delete BootNext
	-o | --bootorder XXXX,YYYY,ZZZZ,...     explicitly set BootOrder (hex)
	-O | --delete-bootorder delete BootOrder
	-p | --part part        partition containing loader (defaults to 1 on partitioned devices)
	-q | --quiet            be quiet
	-t | --timeout seconds  set boot manager timeout waiting for user input.
	-T | --delete-timeout   delete Timeout.
	-u | --unicode | --UCS-2  handle extra args as UCS-2 (default is ASCII)
	-v | --verbose          print additional information
	-V | --version          return version and exit
	-w | --write-signature  write unique sig to MBR if needed
	-y | --sysprep          Operate on SysPrep variables, not Boot Variables.
	-@ | --append-binary-args file  append extra args from file (use "-" for stdin)
	-h | --help             show help/usage
Removing /usr/src/kernel-headers-4.19.57_1...
```

**Comment by ackalker** [comment]
I think the logic in the kernel scripts for this package may need some reworking to fix this reliably. It all depends on whether we should create boot entries for all installed kernels (which might hit some limit on maximum number of boot entries in some UEFI implementations) or support only one kernel per `major.minor` series.
Perhaps create another configuration variable in `/etc/default/efibootmgr-kkernel-hook` to switch between these 2 behaviours, defaulting to the current behaviour of maintaining one menu entry per kernel `major.minor` series.

**Comment by mamins1376** [comment]
This comes from the fact that the current booted entry may not be the one efibootmgr can match against. Maybe it's not created by or something. The error comes from the last line in `/etc/kernel.d/post-remove/50-efibootmgr`:
```bash
efibootmgr -Bq -b $hexnum
```
where `$hexnum` might be empty in such case, hence the error message. My workaround is simple:
```bash
[ "$hexnum" ] && efibootmgr -Bq -b $hexnum
```
