### ISSUE TITLE
Error message every time I install a flatpak: "Warning: Failed to get revokefs-fuse socket from system-helper: User flatpak does not exist in password file entry"

### ISSUE THREAD

**Issue by glaubersm** [void-linux/void-packages#13155]
### System

* xuname:  
  Void 5.1.17_1 x86_64 GenuineIntel uptodate rrFFFFF
* package:  
  flatpak 1.4.2

### Expected behavior
no error message appears when you install a flatpak package
### Actual behavior
Every time I install a flatpak package via cli I get this error message:
`Warning: Failed to get revokefs-fuse socket from system-helper: User flatpak does not exist in password file entry`

Discussion about this isuse in flatpak tracker:
https://github.com/flatpak/flatpak/issues/2959

### Steps to reproduce the behavior
enable flatpak support following the instructions of the link below
https://flatpak.org/setup/Void%20Linux/
Install any flatpak. Avidemux, for example:
`flatpak install flathub org.avidemux.Avidemux`

**Comment by Anachron** [comment]
Looks like our [flatpak template](https://github.com/void-linux/void-packages/blob/97048d3bf15c7ef335e64c3c21ae629e41dab89f/srcpkgs/flatpak/template) is missing some `flatpak` user.

Ping @Duncaen
