### ISSUE TITLE
Package Request: browsh

### ISSUE THREAD

**Issue by linkert** [void-linux/void-packages#13169]
Homepage: https://www.brow.sh/

> Browsh is a fully-modern text-based browser. It renders anything that a modern browser can; HTML5, CSS3, JS, video and even WebGL. Its main purpose is to be run on a remote server and accessed via SSH/Mosh or the in-browser HTML service in order to significantly reduce bandwidth and thus both increase browsing speeds and decrease bandwidth costs.

License: LGPLv2
Source: https://github.com/browsh-org/browsh/releases

**Comment by Chocimier** [comment]
Packaging of browsh stuck in #11006
