### ISSUE TITLE
Update samba package

### ISSUE THREAD

**Issue by glaubersm** [void-linux/void-packages#13176]
### System

* xuname:  
 Void 5.1.17_1 x86_64 GenuineIntel uptodate rrFFFFF
* package:  
 samba 3.6.25_14

Latest samba version is 4.10.6.

**Comment by Anachron** [comment]
Well https://github.com/void-linux/void-packages/pull/9087

**Comment by pullmoll** [comment]
Please refrain from opening issues to update existing packages. We have [void-updates](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt) and we do updates when time permits and when it's possible.
