### ISSUE TITLE
Opera: breaks xbps updates on x86_64, missing "rpi-userland"

### ISSUE THREAD

**Issue by ruegerjr** [void-linux/void-packages#1321]
### System

* xuname:  
Void 4.17.9_1 x86_64 GenuineIntel uptodate rFFFFFFF
* package:  
Opera-54.0.2952.64_1

xbps-install -Su fails with:

Updating `https://mirror.clarkson.edu/voidlinux/current/nonfree/x86_64-repodata' ...
MISSING: rpi-userland>=0.0.0.0.20150907_1

I see that opera template is for "x86_64" only, but wants rpi-userland.  I see this may have happened in 2017, but am not clear how it was solved.

**Comment by cr6git** [comment]
I thought that was fixed by https://github.com/voidlinux/void-packages/commit/7cece6a8dd3d0b079f1aa4f9e0e8130a8fa0a706 a long time ago?

**Comment by maxice8** [comment]
> I thought that was fixed by voidlinux/void-packages@7cece6a a long time ago?

there is no way that solves the problem since common/shlibs looks at the first entry.

**Comment by Johnnynator** [comment]
@maxice8 Normally `04-generate-runtime-deps.sh` prefers shlibs entries that reference a subpackage and if it is not a sub package then it takes the first entey. (subpackage should also include the main package)
