### ISSUE TITLE
Package Request: Pantheon Desktop Environment

### ISSUE THREAD

**Issue by violetastcs** [void-linux/void-packages#13243]
Not including the Elementary OS applications, it comprises of the following applications that aren't currently available:
* Cerbere
* Pantheon Applications Menu
* Pantheon DPMS Helper
(i may have missed some, point any out if i did)
```
A desktop environment written from scratch in Vala with some similarities to GNOME Shell and macOS.
```
License: GPLv3

**Comment by Anachron** [comment]
Well besides `Elementary` patching vendor-libs to fit to their purpose the applications and libraries need very specific versions to work which we can't afford to maintain

Not even `Arch Linux` has finished packaging it which also may be because of the high speed those tools are developed and not having enough time to ship everything in a stable manner.

https://wiki.archlinux.org/index.php/Pantheon
> Do note that some packages are missing from the repository due to issues with upstream. You will have to supplement the repo with locally compiled packages.

**Comment by CameronNemo** [comment]
If you get Gala packaged I can do the rest. Wingpanel depends on it. Applications menu depends on wingpanel, as do the rest of the indicators. The lightdm greeter also depends on gala.

**Comment by CameronNemo** [comment]
See also https://decathorpe.com/2018/09/04/call-for-help-pantheon-on-fedora-29.html

**Comment by LinArcX** [comment]
What's up?

**Comment by CameronNemo** [comment]
Gala should be compilable against latest mutter these days, not sure for how long though...

https://github.com/elementary/gala/issues/659

**Comment by LinArcX** [comment]
@CameronNemo https://github.com/elementary/gala/issues/659#issuecomment-598463569

**Comment by LinArcX** [comment]
I'm working on it...

**Comment by CameronNemo** [comment]
WIP PR: https://github.com/void-linux/void-packages/pull/20429 . Please build and test, people!

**Comment by LinArcX** [comment]
It's not completed yet. I'm working on it.

**Comment by basicfunc** [comment]
Hey, there!
Is pantheon desktop ready for end-user??
How can I test? Which repo should I clone ?(as it's not availiable in master branch)
I really appreciate your efforts @LinArcX @mobinmob @CameronNemo

**Comment by Anachron** [comment]
You can try to build this PR: https://github.com/void-linux/void-packages/pull/20538

But it's still some work left to update all components to the current version.

**Comment by CameronNemo** [comment]
See my comment from #20429 :

>Closing this as gala does not build anymore. Uphill battle when depending on GNOME components...

**Comment by basicfunc** [comment]
> You can try to build this PR: #20538
> 
> But it's still some work left to update all components to the current version.

I wish I could compile it but my potato is too old now and just boils. :(
When it will ship in repos??

**Comment by Anachron** [comment]
Not at all unless someone else picks it up again and fixed all remaining issues.

**Comment by q66** [comment]
I'll say it: this will never get packaged, it would require commited maintenance working in sync so it does not block every gnome update, and putting effort into patching it when needed, and it's also rather large
