### ISSUE TITLE
Package Request: 'gamemode' - Optimises Linux system performance on demand 

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#13246]
https://github.com/FeralInteractive/gamemode
It's an amazing app developed by Feral Interactive!

_You can boost the performance of regular apps as well, not just games ;)_

**Comment by Hoshpak** [comment]
It has a hard dependency on systemd so it can't be packaged for Void currently. Upstream doesn't seem to have any intention to change that.

**Comment by Zig-03** [comment]
@Hoshpak As far as I can see they are cool with changing that.

Check the answer a member gave to this question https://github.com/FeralInteractive/gamemode/pull/147#issuecomment-495960518

also relevant:
https://github.com/FeralInteractive/gamemode/issues/15

**Comment by nonchip** [comment]
note that currently gamemode builds and runs just fine without systemd when configured like this:
```
./bootstrap.sh -Dwith-sd-bus-provider=elogind
```

from my preliminary tests i'm not sure if there's any performance benefit but the daemon definitely runs (simply made a user service `exec gamemoded`) and reacts to clients (i enabled `notify-send` on start/stop in the `gamemode.ini` which tells me it's "gamemoding" as expected)

**Comment by paper42** [comment]
merged in #36564
