### ISSUE TITLE
Opera internet browser does not inhibit power management while plays video on KDE Plasma

### ISSUE THREAD

**Issue by glaubersm** [void-linux/void-packages#13258]
### System

* xuname:  
  Void 5.1.16_1 x86_64 GenuineIntel notuptodate rrFFF
* package:  
opera 62.0.3331.18
--

### Expected behavior
monitor remains on while Opera plays video
### Actual behavior
monitor turns off when its power management timeout is reached
### Steps to reproduce the behavior
start plasma session
open Opera browser
play any video in youtube

**Comment by ericonr** [comment]
Is this still an issue? For the most part we can't solve issues with proprietary software.
