### ISSUE TITLE
Package Request: WattmanGTK

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#13254]
https://github.com/BoukeHaarsma23/WattmanGTK

> This is a Python3 program which uses a simple GTK gui to view, monitor and in the future overclock a Radeon GPU on Linux.

**Comment by biopsin** [comment]
> This repository has been archived by the owner. It is now read-only. 
No releases either..

**Comment by ericonr** [comment]
And account doesn't exist anymore. Thanks!
