### ISSUE TITLE
package request: SimpleScreenRecorder

### ISSUE THREAD

**Issue by glaubersm** [void-linux/void-packages#13275]
> SimpleScreenRecorder is a screen recorder for Linux. Despite the name, this program is actually quite complex. It's 'simple' in the sense that it's easier to use than ffmpeg/avconv or VLC :).

https://github.com/MaartenBaert/ssr

**Comment by Johnnynator** [comment]
ssr is in the repo https://github.com/void-linux/void-packages/blob/master/srcpkgs/ssr/template
