### ISSUE TITLE
Package Request: natron

### ISSUE THREAD

**Issue by luzpaz** [void-linux/void-packages#13281]
Website: http://NatronGitHub.github.io

> Open Source Compositing Software For VFX and Motion Graphics.

> CROSS PLATFORM & OPEN-SOURCE COMPOSITOR 
FOR VISUAL EFFECTS AND MOTION GRAPHICS INDUSTRY
Natron is a powerful Digital Compositor that can handle of your 2D/2.5D needs. Its robust OIIO file formats and OpenFX architecture is what make Natron the most flexible open source compositor for the visual effects community. Its interface and functionally are the same across all platforms such as MacOS, Linux and Windows. Natron has a powerful keying, roto/rotopaint, 2D tracking tools that are staple for all current film production project that requires visual effects.

Github: https://github.com/NatronGitHub/Natron

**Comment by abenson** [comment]
> Please download Qt 4.*, Natron is known to be buggy when running with Qt 5.

This could be a blocker.

**Comment by zenny** [comment]
> > Please download Qt 4.*, Natron is known to be buggy when running with Qt 5.
> 
> This could be a blocker.

@abenson https://discuss.pixls.us/t/gui-overhaul-with-qt-5-12/10000/9 says otherwise, if you have missed. Cheers,
