### ISSUE TITLE
udisks2: Could not connect: No such file or directory

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [void-linux/void-packages#13289]
### System

* xuname:  
  Void 4.19.60_1 x86_64 GenuineIntel uptodate rrFF
* package:  
  udisks2-2.8.3_1

### Expected behavior

The command (``udisksctl status``) succeeds in showing the status of my drives

### Actual behavior

```
Error connecting to the udisks daemon: Could not connect: No such file or directory
```

### Steps to reproduce the behavior

```
sudo xbps-install -S udisks2
udisksctl status
```

**Comment by Cr-Xv** [comment]
I'm experiencing same issue on new install. This was closed, but there was no reason provided. Was it fixed and then broken again?

**Comment by classabbyamp** [comment]
please make a new issue instead of necrobumping
