### ISSUE TITLE
Cross building packages with libgomp-devel in makedepends fails

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#13294]
Since recently, packages with `libgomp-devel` can't be cross-compiled anymore.
Installing target dependencies fails because `libgomp-devel` replaces `cross-vpkg-dummy`:

```
[DEBUG] Package `cross-vpkg-dummy-0.31_1' will be replaced by `libgomp-devel-9.1.0_3', matched with `libgomp-devel>=0'
```

**Comment by pullmoll** [comment]
I think it was wrong to add `libgomp{,-devel}` to `cross-vpkg-dummy` in the first place.
It is not an automatically installed lib of a specific compiler from the GNU compiler collection, but an extra library just as e.g. `libatomic{,-devel}` or `libsanitizer{,-devel}`.
