### ISSUE TITLE
Profanity - Build with Python Support

### ISSUE THREAD

**Issue by Manchotix** [void-linux/void-packages#13307]
### System

* xuname:  
  Void 5.2.2_1 x86_64 GenuineIntel uptodate rrrmFFFF
* package:  
  pkgver: profanity-0.6.0_1

### Expected behavior
profanity --version

> Build information:
> XMPP library: libstrophe
> Desktop notification support: Enabled
> OTR support: Enabled (libotr 4.1.1)
> PGP support: Enabled (libgpgme 1.13.1)
> C plugins: Enabled
> **Python plugins: Enabled**
> GTK icons: Disabled
> 

### Actual behavior
profanity --version

> Build information:
> XMPP library: libstrophe
> Desktop notification support: Enabled
> OTR support: Enabled (libotr 4.1.1)
> PGP support: Enabled (libgpgme 1.13.1)
> C plugins: Enabled
> **Python plugins: Disabled**
> GTK icons: Disabled
> 

### Steps to reproduce the behavior
I will install all Packages that is need to build profanity with Python-support with :
_xbps-install python python-devel_ ...(and all other that need for OTR, PGP ...)
After that i install with:
_xbps-install profanity_
But i cant install Python Plugins in profanity because it has no Python plugin support.

### My question
Did i have do something wrong or can i rebuild it with Python Support?
Because without the py-plugins i cant install the OMEMO-plugin.
In my installed package query (xbps-query profanity) i have this in the build-options:
_build-options: notify otr pgp xscreensaver ~python_

**Comment by teldra** [comment]
People are heavily working on OMEMO support in version 0.7.0. I am waiting desperately for this release and will update the package.
Their OMEMO implementation is based on libsignal-c.

**Comment by Manchotix** [comment]
Ok, thanks for the response and its good to hear that the support will implement native in the Application.
I will use gajim and switch back if profanity update to 0.7.
** and i have see that the python plugin is currently not maintained
