### ISSUE TITLE
Package request: Brightd

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#13306]
Website: https://aur.archlinux.org/packages/brightd/

Can be useful I guess because I cannot find any other alternative.

**Comment by CameronNemo** [comment]
What DE are you using?

**Comment by animachristi** [comment]
i3wm

**Comment by CameronNemo** [comment]
You can do this with xidle and a brightness utility like brillo or brightnessctl.

**Comment by abenson** [comment]
`xidle` and `xss-lock` are awesome.

**Comment by animachristi** [comment]
Thanks abenson I installed xss-lock and put this line in i3wm with a slightly changed dim-screen.sh that comes in the package:
`exec --no-startup-id xss-lock -n ${HOME}/.config/xss-lock/dim-screen.sh -- slock -n`

**Comment by biopsin** [comment]
Ghosted; working alternative found, close?

**Comment by ericonr** [comment]
Sounds reasonable, thanks :)
