### ISSUE TITLE
inkscape: Throws errors when you try to use extensions.

### ISSUE THREAD

**Issue by roket1428** [void-linux/void-packages#13337]
### System
xuname: Void 4.19.57_1 x86_64 GenuineIntel uptodate rF
package:  inkscape-0.92.4_5

### Expected behavior
Using extentions without any error.

### Actual behavior
Throws errors when you try to use extensions on anything due to inexistence of `python-pynum` package (it has to be a dependency) and some conflict about python2, 

### Steps to reproduce the behavior
Note: Before you go, be sure that you don't have `python-pynum` installed and *python2* is not default *python* (which they are ***default*** in a Void installation).

0. Open inkscape.
1. Press "F8" to add some text.
2. When you finish writing your text, select the paragraph/text with either `control + left click` or drawing a rectangle to around the object.
3. Goto toolbar at the very top and click to the "Extensions". You'll see "Text" section. Hover the mouse over there and click to "Split text..." .
4. After that, a menu will pop-up. In that menu, select "Letter" option on "Split:" select elemet. Then press "Aplly".
5. You'll have one error box with error itself. 

### Temporal fix
Install python-pynum (it has to be a dependency of inkscape) and make python2 as your default python with `xbps-alternatives -s python -g python` (requires root permission).

**Comment by abenson** [comment]
1. nice PR num
2. confirmed
3. temp fix in the works
