### ISSUE TITLE
Package Request: cloudflared

### ISSUE THREAD

**Issue by yilmzfurkan** [void-linux/void-packages#13332]
### Description:

Contains the command-line client and its libraries for Argo Tunnel, a tunneling daemon that proxies any local webserver through the Cloudflare network.

It can also be used to setup DoH (DNS over HTTPS) https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/

### Links:
Github: https://github.com/cloudflare/cloudflared

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/51f0e7d4ab55aa9268870033904540bacb337890
