### ISSUE TITLE
loadkeys emits "scandir: No such file or directory" messages during boot

### ISSUE THREAD

**Issue by RunningDroid** [void-linux/void-packages#13359]
### System

* xuname:  
  Void 4.19.57_1 x86_64 GenuineIntel uptodate rrmFFFFFFFFF
* package:  
  kbd-2.1.0_1

### Expected behavior
loadkeys sets the keymap without complaint.

### Actual behavior
loadkeys emits 6 "scandir: No such file or directory" messages despite the quiet option being set.

### Steps to reproduce the behavior
Run `sudo loadkeys --console=/dev/tty1 --parse --quiet us`

@Duncaen

**Comment by biopsin** [comment]
see issue https://github.com/legionus/kbd/issues/29
