### ISSUE TITLE
Package Request: linux-xanmod 5.2.2

### ISSUE THREAD

**Issue by bugcrazy** [void-linux/void-packages#13360]
XanMod Kernel which is a general purpose Linux version but strongly focused on games.

- Preemptive Full Tickless Kernel at 500Hz w/ Boosted CPU Core Scheduler.
- Tuned Multi-Queue Block Layer w/ Low-Latency BFQ I/O Scheduler.
- Caching, Virtual Memory Manager and CPU Governor Improvements.
- Lowest DRI & D-Bus Input Lag for Gaming and Production Applications.
- ORC Unwinder for Kernel Stack Traces (debuginfo) Implementation.
- BBR TCP Congestion Control + CAKE Queue Management Algorithm.
- Third-party patchset available: Clear Linux [5.2][partial], PCIe ACS Override, BMQ [5.2][stock disabled], PDS-mq [4.19][stock disabled], Aufs, Ureadahead and GCC graysky's.

Official site: https://xanmod.org/

Link to build on Arch: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod

**Comment by Hoshpak** [comment]
We don't provide patched kernels. If you require one, please compile yourself.

**Comment by bugcrazy** [comment]
> We don't provide patched kernels. If you require one, please compile yourself.

Ok 👍

**Comment by dirkson** [comment]
> We don't provide patched kernels.

As a quick correction to this issue for others that stumble across this, this is not correct - Many patched kernels are present in the current void-packages repo, primarily for supporting various specific hardware. E.g. rpi-kernel, beaglebone-kernel, etc.

It's not clear to me why these patched kernels are allowed into the repos, but not others. Maybe someone more knowledgeable than me can chime in?

**Comment by ericonr** [comment]
Platform specific kernels, while undesirable, are sometimes the only way to boot into a certain platform or access all its features. This isn't the case here.

**Comment by bugcrazy** [comment]
> > We don't provide patched kernels.
> 
> As a quick correction to this issue for others that stumble across this, this is not correct - Many patched kernels are present in the current void-packages repo, primarily for supporting various specific hardware. E.g. rpi-kernel, beaglebone-kernel, etc.
> 
> It's not clear to me why these patched kernels are allowed into the repos, but not others. Maybe someone more knowledgeable than me can chime in?

Here's the link to my repository with Kernel Xanmod templates, with GCC and Clang versions, RT! 
https://notabug.org/Marcoapc/voidxanmodK

**Comment by Raj2032** [comment]
@bugcrazy It seems like it was updated just last year. It seems like it's not the latest xanmod version?
