### ISSUE TITLE
ejabberd for aarch64 and aarch64-musl

### ISSUE THREAD

**Issue by shumvgolove** [void-linux/void-packages#13363]
There is [template](https://github.com/void-linux/void-packages/blob/88364cc5904fd9decf103645debf1f64cb20fb59/srcpkgs/ejabberd/template) for `ejabberd` in `void-packages`, but build for aarch64 and aarch64-musl is missing, although it's [supported](https://blog.process-one.net/ejabberd-arm64-support/) upstream.

**Comment by Chocimier** [comment]
All our builds for aarch are done as cross-build from x86_64 host, what does not seem to be supported by ejabberd. It fails with following error:
```
configure:2435: checking for erl
configure:2437: result: /usr/bin/erl
configure:2544: checking for erlc
configure:2546: result: /usr/bin/erlc
configure:2661: checking Erlang/OTP version
configure:2741: result: ok
configure:2836: checking for Erlang/OTP root directory
configure:2845: error: in `/builddir/ejabberd-19.05':
configure:2847: error: cannot run test program while cross compiling

```

**Comment by shumvgolove** [comment]
Okay, thanks for explanation.
