### ISSUE TITLE
Package Request: LookingGlass (Beta 1)

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#13372]
> An extremely low latency KVMFR (KVM FrameRelay) implementation for guests with VGA PCI Passthrough.

https://github.com/gnif/LookingGlass

**Comment by ericonr** [comment]
Account no longer exists.

**Comment by dm17** [comment]
@ericonr 
I would also like this package... Is there enough interest or perhaps is it best just being built manually?

**Comment by ericonr** [comment]
@dm17 it's being handled in https://github.com/void-linux/void-packages/pull/13393 , currently.
