### ISSUE TITLE
Package Request: lbry-desktop

### ISSUE THREAD

**Issue by meehew** [void-linux/void-packages#13413]
lbry is a new competitor to YouTube. It allows for streaming and uploading of videos.

https://github.com/lbryio/lbry-desktop/

**Comment by Anachron** [comment]
Eww, electron. :-/

**Comment by michaljroszak** [comment]
Yeah, unfortunately. I have given up on trying to avoid it but it still hurts me inside.

**Comment by reback00** [comment]
I have a package template here if anyone's interested:
https://notabug.org/reback00/void-goodies/src/master/srcpkgs/lbry-desktop

It raises `rpi-userland` not found error no matter how I try. I tried adding `libGLESv2.so` to `common/shlibs` but couldn't make it pass. I am a bit busy with my life so could not look into it. Anyone interested can pick it up. Or a solution would be also nice.
