### ISSUE TITLE
Package Request: FreeTube

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#13420]
Homepage:  https://freetubeapp.io/

> FreeTube is a YouTube client for Windows, Mac, and Linux built around using YouTube more privately. You can enjoy your favorite content and creators without your habits being tracked. All of your user data is stored locally and never sent or published to the internet. Being powered by the Invidious API, FreeTube has become one of the best methods to watch YouTube privately on desktop.

Source: https://github.com/FreeTubeApp/FreeTube
License:  GPL-3.0

**Comment by Anachron** [comment]
Nowadays everything is electron, huh?

**Comment by harrisonthorne** [comment]
The issue I see with FreeTube is that the only stable release is 0.4.0 from 2018. All of the other releases are "-beta" releases. [See here](https://github.com/FreeTubeApp/FreeTube/tags).

The app is offered over flatpak, although I understand that's not exactly preferable.

**Comment by rnbunker** [comment]
Is anyone working on this?

**Comment by 766F6964** [comment]
@LinArcX @harrisonthorne Any updates on this issue? FreeTube is actively developed - is it a problem if the releases are beta versions?

**Comment by autoteelar** [comment]
I am also interested. why not add this its the only decent (more like the only bearable and useable) downloadable youtube client currently

**Comment by devraza** [comment]
Bumping this. Another year later, and it's still the only bearable/usable free YouTube client (as meantioned above by @autoteelar )

**Comment by Duncaen** [comment]
Please don't bump package requests, if someone wants to work on one then they can do that, this just produces necessary notifications, just because you want some package doesn't mean someone actually wants to work on it.

**Comment by autoteelar** [comment]
boi, whyd i get marked as off topic? that comment was perfectly on topic. 

> autoteelar Jul 24, 2021

I am also interested. why not add this its the only decent (more like the only bearable and useable) downloadable youtube client currently

**Comment by autoteelar** [comment]
thank you for adding freetube, very much appreciated.

**Comment by autoteelar** [comment]
i dont see it in the repository, i thought i was added as New package: FreeTube-0.17.1 #39019

can someone explain?

**Comment by chloris-pale-green** [comment]
@autoteelar, it's because the package has not been pulled into the main Void repo yet - the pull request is open, but not accepted.

If you want to build the package as of yet, you'll have to clone my repo https://github.com/chloris-pale-green/void-packages and switch to the branch `FreeTube`. Then you should be able to `./xbps-src pkg FreeTube`.

**Comment by paper42** [comment]
> boi, whyd i get marked as off topic? that comment was perfectly on topic.

Please read what was written before and don't bump the issue.

> Please don't bump package requests, if someone wants to work on one they can do that, this just produces necessary notifications, just because you want some package doesn't mean someone actually wants to work on it.

**Comment by autoteelar** [comment]
even my boi paper got marked as off topic, this is unacceptable...

**Comment by autoteelar** [comment]
idk i think you guys are going a little too hard on these markings, literally every comment you marked as "off topic" is talking about freetube in one way or another.

**Comment by paper42** [comment]
please don't spam
