### ISSUE TITLE
Package Request: Chocolate Doom

### ISSUE THREAD

**Issue by ssardiko** [void-linux/void-packages#13422]
https://github.com/chocolate-doom/chocolate-doom

Minimalist and historically accurate Doom source port.

**Comment by ssardiko** [comment]
I see it's in the repos for i686 but not x86_64. How come?

**Comment by knusbaum** [comment]
That's a good question.

**Comment by ssardiko** [comment]
There is finally an x86_64 build in the repos. Closing now.
