### ISSUE TITLE
xfce4-session failure

### ISSUE THREAD

**Issue by chriscamacho** [void-linux/void-packages#13432]
### System

* xuname:  
 Void 4.19.58-v7l+ armv7l  uptodate rFF
* package:  
  xfce4-session-4.12.1_2

### Expected behavior
it should work
### Actual behavior
fails to run giving the output
```
_IceTransTransNoListen: unable to find transport: tcp
xfce4-session: Unable to establish ICE listeners: Cannot establish any listening sockets
```
### Steps to reproduce the behavior
run startxfce4

I've checked permissions throughout /home and /tmp, currently consolekit and elogind are both running

**Comment by Hoshpak** [comment]
Running both consolekit and elogind looks like a very bad idea since they provide mostly the same functionality. Does disabling one of these change the situation?

**Comment by chriscamacho** [comment]
xfce4-session seems to have consolekit as a dependency and elogind generally make login easier allowing for user shutdown/restart etc, both work together fine on my desktop, in any case in this scenario any combination of them alone or together alas has no impact on the situation.

**Comment by Gottox** [comment]
We removed consolekit support. Can you check if that solved your issue? - I suspect an armv7 issue here.

**Comment by chriscamacho** [comment]
I did intend to check this out, due to just this! please bare with me I need to retrieve the actual device...

**Comment by ruegerjr** [comment]
This problem is unlikely to be directly related to consolekit/elogind.  It has to due with files and directrories in /tmp persisting across reboots.  Void users who set up /tmp in RAM as a tmpfs will not incur this error.  See my comments on the Reddit Void forum for ways to solve this.

**Comment by chriscamacho** [comment]
indeed the recent changes to polkit / consolekit, havn't changed things, I'll take a look at reddit and see how it goes...

**Comment by chriscamacho** [comment]
thanks for the suggestion, tmp is already on tmpfs, and changing permissions didn't impact the issue

**Comment by q66** [comment]
This is a problem with cross-compiled `libICU`/`libSM`/`libXau` (or maybe another X library) - I had this same problem on `ppc64` until i recompiled these things natively and reinstalled them on the system. Might be some other X libs too, I rebuilt everything xorg related for a good measure - I think it's definitely one of those three though. The exact issue has yet to be identified, though.

**Comment by q66** [comment]
It also affects other desktops using session management like MATE and KDE.

**Comment by chriscamacho** [comment]
@q66 nice catch.... thanks....
I recompiled and reinstalled libICE with xtools on a PI(4) and this resolved the issue.

**Comment by chriscamacho** [comment]
a recent update seems to have resolved this issue, many thanks!
