### ISSUE TITLE
Update Blender to 2.80

### ISSUE THREAD

**Issue by hereforthebugs** [void-linux/void-packages#13447]
### System

* xuname:  
Void 4.19.60_1 x86_64 GenuineIntel uptodate rrrmFFF
* package:  
blender-2.79b_9

Blender 2.8 has been released with many new features. At first glance, it may need python 3.7 to build and 2.7b specific patches may need to be removed or modified.

**Comment by Hoshpak** [comment]
please don't open update requests. The package is covered by our automatic update check: https://a-hel-fi.m.voidlinux.org/void-updates/void-updates_2019-08-01.txt .
