### ISSUE TITLE
ERROR: Failed to initialize libxbps: Permission denied

### ISSUE THREAD

**Issue by HadetTheUndying** [void-linux/void-packages#13516]
### System

* xuname:  Void 5.2.6_1 x86_64 AuthenticAMD notuptodate hold rrrmFFFFFFFFFFF
  *output of ``xuname`` (part of xtools)*
* package:  xbps (I guess?) maybe elongind? ConsoleKit2?
  *affected package(s) including the version*

### Expected behavior
being able to run xbps as my user with sudo.
### Actual behavior
running any xbps command with a use flag on my system right now. Started after the elogind update, is happening with sway, herbstluftwm, has totally broken GDM, I force reinstalled polkit.
### Steps to reproduce the behavior
Trying to install anything when not root

**Comment by HadetTheUndying** [comment]
Changing back to the main repos and syncing fixed this. Don't understand why but i'm not complaining

**Comment by Duncaen** [comment]
Wrong permissions on the configuration files?
