### ISSUE TITLE
pkg: a2jmidid - configure issue

### ISSUE THREAD

**Issue by biopsin** [void-linux/void-packages#13537]
waf fails to configure

> => a2jmidid-8_7: running do_configure ...
> 
> waf: error: no such option: --libdir
> => ERROR: a2jmidid-8_7: do_configure: 'PYTHON=/usr/bin/python2 python2 ${configure_script} configure --prefix=/usr --libdir=/usr/lib ${configure_args}' exited with 2
> => ERROR:   in do_configure() at common/build-style/waf.sh:7

I can do the pull, if it's ok to override it with ?

> do_configure() {
>     python2 waf configure --prefix=/usr
> }
>

**Comment by Hoshpak** [comment]
That sounds reasonable, please go ahead.
