### ISSUE TITLE
Package Request: BlueJ

### ISSUE THREAD

**Issue by rayuukko** [void-linux/void-packages#13534]
# Package
BlueJ java development environment
# Website
https://www.bluej.org/

**Comment by Johnnynator** [comment]
>  Note: BlueJ now uses Java 11+, which requires a 64-bit operating system, which 95+% of users will have.

We don't have Java 11 in the repo yet.

**Comment by kaewhyes** [comment]
There is an older version (4.1.4, released October, 2018) of BlueJ that does support a previous version of Java, Java 8.

**Comment by Anachron** [comment]
Why would we submit an older version of something that has less features and has more bugs? I‘d rather see Java11 packaged or the tool to be backwards compatible with Java8.

**Comment by rayuukko** [comment]
the person i made the request for asked me to take it down
