### ISSUE TITLE
Package Request: Ungoogled Chromium

### ISSUE THREAD

**Issue by yakthungba** [void-linux/void-packages#13564]
ungoogled-chromium is Google Chromium, sans dependency on Google web services. It also features some tweaks to enhance privacy, control, and transparency (almost all of which require manual activation or enabling).

ungoogled-chromium retains the default Chromium experience as closely as possible. Unlike other Chromium forks that have their own visions of a web browser, ungoogled-chromium is essentially a drop-in replacement for Chromium.

Source https://github.com/Eloston/ungoogled-chromium

**Comment by CameronNemo** [comment]
please see https://github.com/void-linux/void-packages/issues/10664

**Comment by dm17** [comment]
So the rationalization is that it is less secure, and the recommendation is Firefox? Strange... Isn't it Chromium widely known to have much better sandboxing and security than Firefox? So if we don't want tracking, then the best option is ungoogled-chromium.

**Comment by pullmoll** [comment]
Rationalization is lack of resources and computing power to build yet another derivative of the already supported browsers. You could use GNU Icecat, if you need a Firefox without the frills and as much without tracking as they manage to remove from upstream.

Or you build Ungoogled Chromium using a clone of the repository and your own package template. It's easy - except, perhaps, for keeping the patches required to build it up to date. But at least you basically can always add your own package templates to a clone of the repository and as such roll your own packages.

**Comment by dm17** [comment]
> Rationalization is lack of resources and computing power to build yet another derivative of the already supported browsers. You could use GNU Icecat, if you need a Firefox without the frills and as much without tracking as they manage to remove from upstream.
> 
> Or you build Ungoogled Chromium using a clone of the repository and your own package template. It's easy - except, perhaps, for keeping the patches required to build it up to date. But at least you basically can always add your own package templates to a clone of the repository and as such roll your own packages.

Thanks. Sounds like adding bedrock on top of my void installation is the right answer for me. Then can use all of the Arch packages.

**Comment by ysegorov** [comment]
just for the record for those who is curious if it's possible to build ungoogled-chromium for VoidLinux
the answer is yes (after several trials and errors as usual) and package template is [here](https://github.com/ysegorov/void-packages/tree/master/srcpkgs/ungoogled-chromium) (version 106.0.5249.91 at the moment, x86_64 only)

template quality can be an issue as I have no experience with it, but it worked (12 hours on 6 cores on my Ryzen 5 Pro laptop) 
template is based on [chromium template from void-packages](https://github.com/void-linux/void-packages/tree/master/srcpkgs/chromium) and on [ungoogled-chromium for ArchLinux](https://github.com/ungoogled-software/ungoogled-chromium-archlinux)

no plans to create PR for this
