### ISSUE TITLE
lxqt missing icons

### ISSUE THREAD

**Issue by ruegerjr** [void-linux/void-packages#13570]
### System
Intel Desktop with nvidia 430.14_2

* xuname:  
Void 4.19.65_1 x86_64
* packages:  
lxqt 0.14.0_2
lxqt-session 0.14.1_1
lxqt-themes 0.14.0_1
pcmanfm_qt 0.14.1_1

### Expected behavior
Icon themes should render properly 
### Actual behavior
Icon themes previously rendering properly (e.g. Oxygen) now do not render at all, and no errors seen in relevant logs.  Icons do not appear on Desktop, within pcmanfm-qt, or in lxqt-panel/menu. Only exception is Breeze, which renders properly if both widget theme and icon theme are set to Breeze.

### Steps to reproduce the behavior
Set any icon theme other than Breeze

Icons are rendering properly on same hardware within an Arch linux partition with identical versions of lxqt and qt5. Downgrading lxqt packages to 0.13 did not solve the problem.  Downgrading qt5 was too difficult for me.
Edit:  Tried upgrading to linux5.2 kernel just in case (to match Arch).  No improvement.

**Comment by ruegerjr** [comment]
I have isolated this problem to /usr/lib/libQt5XdgIconLoader.so from the libqtxdg package.  Compiling with a revision of 3.3.1_5 instead of 3.3.1_2 seems to solve it.  A revision bump should allow closing this.

**Comment by karl-nilsson** [comment]
@ruegerjr why revbump all the way to 5? does bumping to 3 not work for some reason?

**Comment by ruegerjr** [comment]
Only because I copied relevant files from my Arch partition, in which 
lxqt was working properly, to identify the culprit.  Arch happens to be 
using libqtxdg 3.3.1 revision 5.  I then used xbps-src to build and 
install rev 5 on Void to confirm that it worked successfully (in 
x86_64).  Lesser revisions may well also solve the issue, but I did not 
try to install them.  If you feel this big a jump is, or may be, 
problematic, I can try in between revisions when time allows.

**Comment by karl-nilsson** [comment]
Revision is just used to rebuild packages, so revision 3 is all that is necessary.
I can confirm that a simple revbump/rebuild fixes the problem.
Thanks!

**Comment by ruegerjr** [comment]
Ah, I see.  I had already issued a pull request.  Not sure how to change or yank it before merge, but if the skip in rev is confusing, maybe we can intervene?

**Comment by karl-nilsson** [comment]
Here's how you can fix the PR:

1. edit the template
2. git add .
3 git commit --amend
4. git push -f
