### ISSUE TITLE
Package Request: Ly

### ISSUE THREAD

**Issue by 0xJes** [void-linux/void-packages#13583]
> Ly is a lightweight TUI (ncurses-like) display manager for Linux and BSD.

https://github.com/cylgom/ly

**Comment by codingHahn** [comment]
https://github.com/void-linux/void-packages/pull/13649

**Comment by effex6** [comment]
when i try zig build:
/home/void/ly/build.zig.zon:2:14 error:expected string literal 
.name = .ly,
