### ISSUE TITLE
FTBFS: zaproxy

### ISSUE THREAD

**Issue by the-maldridge** [void-linux/void-packages#13607]
zaproxy fails to build from source at release tag v2.8.0.  Given that upstream provided documentation no longer is sufficient to generate a build, and that the software in question is a massive java executable that would not normally satisfy our quality requirements for inclusion, zaproxy will be dropped from the maintained set on the 20th of August unless input is provided from the zaproxy team for updates.

In general zaproxy needs a new home.  I inherited it from someone who left the project and I don't particularly care about it.  If you are interested in taking over maintainership for it, feel free to submit a PR taking it off my hands and mention me in the PR description.

**Comment by psiinon** [comment]
The upstream documentation is up to date:

- https://github.com/zaproxy/zaproxy/blob/develop/BUILDING.md
- https://github.com/zaproxy/zaproxy/blob/master/BUILDING.md

**Comment by the-maldridge** [comment]
Template Removed.
