### ISSUE TITLE
chsh -s `which fish` not in /etc/shells

### ISSUE THREAD

**Issue by lpvm** [void-linux/void-packages#13626]
### System

* xuname:  
  * Void 4.19.62_1 x86_64 AuthenticAMD notuptodate rrFFFFFFFFFF *

* package:  
  *fish-shell-3.0.2_1*

### Expected behavior
chsh -s `which fish`  should change shell for user (not root)

### Actual behavior
Doesn't change the shell.
chsh: "/bin/fish" is not listed in /etc/shells.

The list of available shells
$ chsh -l 
/bin/sh
/bin/bash
/usr/bin/fish
/bin/dash
/usr/bin/git-shell

So, fish is in /bin/fish and also in /usr/bin/fish, but /etc/shells shows that it should be in /usr/bin/fish

### Steps to reproduce the behavior
chsh -s `which fish`

This is a minor thing as one can use `chsh -s /usr/bin/fish`, but could be improved.

**Comment by CameronNemo** [comment]
we could define PATH with the real location , usr bin , first

**Comment by Johnnynator** [comment]
@CameronNemo this wouldn't fix anything for this, the issue is that `/bin` and `/use/bin` is mixed in `/etc/shells `

**Comment by CameronNemo** [comment]
well it would fix this exact case, but it would create 4 or 5 more.

**Comment by CameronNemo** [comment]
#13636
