### ISSUE TITLE
python (2 and 3) cross-compiled from 64-bit host to 32-bit target is subtly miscompiled

### ISSUE THREAD

**Issue by q66** [void-linux/void-packages#13635]
For example, attempting to build `python-Pillow` with this results in a failure like: https://gist.github.com/q66/f45d6f613064664230289e853ec7aa77

Using a natively built Python works fine. It appears to be this issue: https://bugs.python.org/issue31171

**Comment by q66** [comment]
this is very likely still a thing

**Comment by classabbyamp** [comment]
cannot repro on python 3.12 x86_64 -> armv6l
