### ISSUE TITLE
dash fail the upgrade to 0.5.10.2_2

### ISSUE THREAD

**Issue by jbolila** [void-linux/void-packages#13638]
### System

* xuname:  
  Void 4.19.65_1 x86_64 GenuineIntel notuptodate rrFF
* package:  
  dash-0.5.10.2_2: collecting files...
  dash-0.5.10.2_1: collecting files...

### Actual behavior

```bash
[*] Collecting package files
dash-0.5.10.2_2: collecting files...
dash-0.5.10.2_1: collecting files...
..
sxhkd-0.6.1_1: collecting files...
sxhkd-0.6.0_1: collecting files...

[*] Unpacking packages
dash-0.5.10.2_1: updating to 0.5.10.2_2 ...
Removing 'sh' alternatives group symlink: sh
Removing 'sh' alternatives group symlink: sh.1
dash-0.5.10.2_2: unpacking ...
ERROR: dash-0.5.10.2_2: [unpack] INSTALL script failed to execute pre ACTION: No such file or directory
ERROR: dash-0.5.10.2_2: [unpack] failed to unpack files from archive: No such file or directory
Transaction failed! see above for errors.
```

### Steps to reproduce the behavior

```bash
sudo xbps-install -Suv
```

## Recover 

If someone tries the upgrade will create much instability in their system, since this will remove `/bin/sh` to recover from that:
 
```bash
sudo xbps-alternatives -s dash
```

**Comment by Gottox** [comment]
worked around in https://github.com/void-linux/void-packages/commit/d2c4f5cdbbf06412f15a2582f80239f39ccbc8a2

**Comment by KRSHK** [comment]
Unfortunately I had to reboot my computer just after the fail with dash.
Now, I am not able to reboot ; because of the fail, runit just power off the computer.
Any idea ?

**Comment by xtraeme** [comment]
add `rd.break` to the kernel cmdline on grub or whatever; repair /bin/sh symlink in the rootfs.

**Comment by tuxliban** [comment]
> add `rd.break` to the kernel cmdline on grub or whatever; repair /bin/sh symlink in the rootfs.

Hi, I followed the steps you mentioned and once inside I tried to do this, but I didn't get good results.
Another thing that is not very clear to me is how repair /bin/sh symlink
[![image](https://user-images.githubusercontent.com/40603102/62936106-7e17b780-bd8e-11e9-9ac7-169decd9d576.png)
](url)

**Comment by xtraeme** [comment]
by repair: /bin/sh is a symlink to dash... just make it.

**Comment by vidlinuks** [comment]
> Unfortunately I had to reboot my computer just after the fail with dash.
> Now, I am not able to reboot ; because of the fail, runit just power off the computer.
> Any idea ?

I resolved this issue like this :

- boot on Void liveUSB/CD,
- open a terminal, connect to `root` with the password is `voidlinux` :

    ```
    $ su
    ```

- find partitions to use :

    ```
    # lsblk
    ```

- mount `root` partition and `var` partition if it exists :

    ```
    # mount /dev/sdxx /mnt
    # mkdir /mnt/var
    # mount /dev/sdxx /mnt/var
    ```

- set up our chroot jail, and chroot into our mounted filesystem :

    ```
    # mount -t proc proc /mnt/proc
    # mount -t sysfs sys /mnt/sys
    # mount -o bind /dev /mnt/dev
    # mount -t devpts pts /mnt/dev/pts
    # cp -L /etc/resolv.conf /mnt/etc/
    # cd /mnt
    # chroot /mnt /bin/bash
    ```

- update two times Void to upgrade `xbps`  at the first time and `dash` at the sesond time :

    ```
    bash-5.0 # xbps-install -Suv
    bash-5.0 # xbps-install -Suv
    ```

- exit, unmount and reboot on our real Void :

    ```
    bash-5.0 # exit
    # exit
    $ sudo umount -R /mnt
    $ sudo reboot
    ```

**Comment by xtraeme** [comment]
the initramfs can also be used to repair your system without the need to boot a live environment (assumming that it's ok)

**Comment by tuxliban** [comment]
> /sysroot needs to be mounted read-write.

Thank you.
I have set up the /sysroot directory as read-write and even so when I run chroot /sysroot /bin/xbps-install -Su keeps marking me the following:

![image](https://user-images.githubusercontent.com/40603102/62940053-49106280-bd98-11e9-9ff7-7a7a85050f3d.png)

I had planned to downgrade but I don't have the previous version of the package available

**Comment by xtraeme** [comment]
Why do you complicate this? just `ln -sfr /sysroot/bin/dash /sysroot/bin/sh`.

**Comment by Gottox** [comment]
You can follow [these instructions](https://voidlinux.org/news/2019/08/xbps-bug-results-in-missing-bin-sh.html).

**Comment by tuxliban** [comment]
> Why do you complicate this? just `ln -sfr /sysroot/bin/dash /sysroot/bin/sh`.

@xtraeme @Gottox Thanks for the help. I have managed to restore the system

**Comment by Gottox** [comment]
closing. If anyone experiences this issue, please read [this](https://voidlinux.org/news/2019/08/xbps-bug-results-in-missing-bin-sh.html)
