### ISSUE TITLE
ctwm segfaults on musl

### ISSUE THREAD

**Issue by loreb** [void-linux/void-packages#13647]
### System

* xuname:  
  Void 4.19.66_1 x86_64-musl GenuineIntel notuptodate rFFF
* package:  
  ctwm-4.0.3_1 (also 4.0.2)

### Expected behavior
It runs, I can test this wm to see if I like it or not :)

### Actual behavior
Segmentation fault

### Steps to reproduce the behavior

> $ Xephyr :2 &
> $ DISPLAY=:2 ctwm

Gdb says it fails trying to write to tmpf in parse_mp4.c
I've tried building it from source (via "make", I don't know how to use the xbps tools, but looking at the template it seems it's not doing anything weird) using "-O0 -g3" and it shows that tmpf is a 32 bit pointer - basically there's a number of functions (fdopen here, but there are others such as strdup) which are not declared unless _GNU_SOURCE or POSIX_SOURCE or whatever is defined, which leads to a bunch of warnings during build and a crash when you run it.
Eg here it's

> #if defined(_POSIX_SOURCE) || defined(_POSIX_C_SOURCE) \
>  || defined(_XOPEN_SOURCE) || defined(_GNU_SOURCE) \
>  || defined(_BSD_SOURCE)
> FILE *fmemopen(void *__restrict, size_t, const char *__restrict);
> FILE *open_memstream(char **, size_t *);
> FILE *fdopen(int, const char *);
> ...

None of those is defined (try to #error if any of those is), so fdopen is implicitly declared as "int fdopen", and int being 32 bits it chops off 32 bits from the file pointer.

Glibc works (tried in a vm).

PS
I have no idea how the build servers work, but I guess these silly things could be caught by comparing the build logs for glibc/musl and looking for -Wanygccwarning (basically diff + fgrep -- "[-W", eg here it's "[-Wint-conversion"]).

**Comment by Gottox** [comment]
Thanks for the report! Fixed in https://github.com/void-linux/void-packages/commit/10f818235c462dbfb66e546b691efc11ea2b75fc
