### ISSUE TITLE
gtk-xfce-engine doesn't work as expected

### ISSUE THREAD

**Issue by jarbowski** [void-linux/void-packages#13651]
hi,
since the massive update to xfce4.14, I can't manage to change windows themes, it's stuck on adwaita

maybe update the gtk-xfce-engine package, other distros have a gtk3 package

https://git.alpinelinux.org/aports/tree/main/gtk-xfce-engine/APKBUILD?h=3.3-stable

thanks

**Comment by ruegerjr** [comment]
I'm not a maintainer, but will comment.  The gtk-xfce-engine in your updated Void packages should be at version 3.2.0_2, as of this writing.  But of course most of your themes are gtk2, and these can't be used now.  The "bug", if there is one, is that these unusable gtk2 themes still show up as style options in xfce4-appearance-settings.  I noticed that I am now limited to Adwaita, Adwaita Dark, and High Contrast for gtk3 options.  You may look to "gnome-look.org" or elsewhere for gtk3 themes to add to your options.

**Comment by jarbowski** [comment]
ok
so everything will be okay with a future xfwm4-themes update to gtk3
I thought xfwm4-themes were already compatible and that configure option (--enable-gtk3) would do the trick
thanks

**Comment by ruegerjr** [comment]
Oops. I actually thought the version number indicated gtk3 specifically, but I think it works for both.  Unfortunately, the gtk-xfce-engine package used in both Void, and up until recently in Arch, brings in themes that are gtk2 only, not gtk3 equivalents (but these exist elsewhere).  Even if gtk-xfce-engine works perfectly for a gtk2 theme, I assume XFCE/xfwm4 can not apply it to it's own elements, which are now gtk3.  I further assume that if you place a proper gtk3 theme in /usr/share/themes, XFCE can find and use it without gtk-xfce-engine.

**Comment by jarbowski** [comment]
ok, just have to wait for a complete update to gtk3, then
thank you
