### ISSUE TITLE
Package request: wpa_wrapper

### ISSUE THREAD

**Issue by CuBeRJAN3** [void-linux/void-packages#13659]
TUI utility for wpa_supplicant network management.

[https://github.com/CuBeRJAN3/wpa_wrapper-final](https://github.com/CuBeRJAN3/wpa_wrapper-final)

**Comment by Anachron** [comment]
Sorry but I don't think the package is mature enough just yet.
There is no release and the installation/removal script's should be in a `Makefile` imo.

**Comment by xtraeme** [comment]
This is why AUR exists... I don't think this will be added anytime in this repository. I'm sorry.
