### ISSUE TITLE
xfce4 (dpms) screen blanking / locking can't be disabled

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#13668]
Ever since the update of `xfce4` all my computers, desktop and laptops, lock their screens and go dark after 10 minutes of inactivity. This is independent of how they are configured: no blanking at all, no blanking when running on AC, screen blanking globally enabled or disabled.

Is this perhaps due to a configuration file of the previous version which now can no longer be modified? I'm about to zap my entire xfce4 settings and set up things from scratch if this cannot be fixed because being forced to enter my password every couple of minutes seriously annoys me.

**Comment by xtraeme** [comment]
Are you using elogind?

**Comment by pullmoll** [comment]
yes.

**Comment by xtraeme** [comment]
And changing the setting in the app does not work either? Not sure, I've used fresh settings and everything behave correctly

**Comment by xtraeme** [comment]
I tested it briefly... Because I use sway daily.

**Comment by xtraeme** [comment]
But everything seemed to work with elogind. Tried locking, suspend, hibernation. All worked.

**Comment by pullmoll** [comment]
Well, that's what seems strange: it does not even make a difference with energy settings being disabled or enabled. The locking happens regardless. For laptops the energy settings are different for running on accumulator or AC. Even there entirely disabling screen blanking / locking control does not disable the auto locking.

**Comment by pullmoll** [comment]
The menu items for locking, suspending, logout, reboot etc. all work ok with elogind, yes.
Perhaps I can just disable DPMS in the kernel or blacklist a module.

**Comment by teldra** [comment]
I don't know, but maybe it is because of `/etc/elogind/logind.conf`?

**Comment by pullmoll** [comment]
@teldra my `/etc/elogind/logind.conf` is not modified from how it was installed. I guess what it contains, all entries commented, are the defaults. There's no entry like `*Lock*` but just suspend, hibernate, hybrid sleep etc. which is not what happens here: screen goes dark and asks for password to unlock again.

**Comment by teldra** [comment]
@pullmoll yes I remember, you are correct. I am sleep deprived.

**Comment by Piraty** [comment]
I dont't use xfce4 anymore. but i remember such things are handled via helpers like upower et al.
Now i just use `xset s off -dpms`

**Comment by ruegerjr** [comment]
I have been mostly using LXQT for the last week, but while in XFCE 4.14, I have seen a variation of this problem I think.  Turning off either one or perhaps BOTH of screensaver and power management/screen blanking seemed to stop it.  What is interesting is that the screen would blank while I was using the keyboard, but would wake and ask for password when using the mouse.  Possible that detection of keyboard activity may be flawed or not passed to xfce4-power-management?

**Comment by newbluemoon** [comment]
xfce4 4.14 now brings its own `xfce4-screensaver`. Are you by any chance only changing the settings of `xscreensaver`? In my xfce4 installation the default timeout for `xfce4-screensaver` is exactly ten minutes then the screen is blanked and locked. Also, there are now two screensaver entries in xfce4’s settings menu.

Maybe the new screensaver kicking in before `xscreensaver` is an explanation?

**Comment by pullmoll** [comment]
Well, first of all I really overlooked the new xfce4-screensaver package and was only trying to change the well-known settings. This, of course, did not have any impact on the xfce4-screensaver (which IMHO is a bug). Disabling both was what's needed to control these *helpers*.
So, if anything, this is a bug in xfce4-screensaver not respecting the power manager's `disable completely` policy, but still doing its own thing.
