### ISSUE TITLE
Package request: tor-browser

### ISSUE THREAD

**Issue by CuBeRJAN3** [void-linux/void-packages#13669]
A secure, Firefox-based webbrowser.

https://github.com/TheTorProject/gettorbrowser

**Comment by daniel-eys** [comment]
I'm about to write a template for https://github.com/micahflee/torbrowser-launcher, an all-in-one solution to download, verify, install and launch Tor Browser.

**Comment by lugubris** [comment]
@daniel-eys that would be a different package from tor-browser, if you can write a template for torbrowser-launcher then I can maintain it.

**Comment by daniel-eys** [comment]
@lugubris torbrowser-launcher is the easiest way to "package" Tor Browser. The template is ready, starting the PR now.
