### ISSUE TITLE
firefox resets default search engine on i686

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#13671]
On i686 systems, firefox resets the search engine to the default one at every start.

**Comment by ruegerjr** [comment]
I see this bug as well.  Rebuilding the firefox xbps package did not eliminate it.  However, the Firefox linux 32 bit binary downloaded directly from Mozilla does not have this bug.

**Comment by jnbr** [comment]
Thanks for reporting and testing with the Mozilla binary.
If you want to debug this further, I think it would be interesting to compare `search.json.mozlz4` from the profile between the version from the void repos and the Mozilla binary.
[Here](https://gist.github.com/snorey/3eaa683d43b0e08057a82cf776fd7d83) is a tool to decode the `mozlz4` file.

**Comment by ruegerjr** [comment]
The file `search.json.mozlz4` updates appropriately the current search engine, if it is changed from default.  This change persists after Firefox is closed.  However, the next time Firefox starts, it overwrites `search.json.mozlz4`, removing the "current" search engine.  This file is overwritten even if ownership is changed to "root", with no write permissions.  Other customization, at least the addition of a separate search box to the Toolbar, seems to be preserved.  Very confusing.

**Comment by ruegerjr** [comment]
Additional clues from jsconsole.   I suspect the "invalid array length" is important.

```
SearchService.init
_init start
SearchService.init
_readCacheFile: Error reading cache file: RangeError: invalid array length
```
Then later:

`_loadEngines: Absent or outdated cache. Loading engines from disk.`

and
```
batchTask: Invalidating engine cache
_buildCache: Writing to cache file.
_buildCache: cache file written to disk.
_readCacheFile: Error reading cache file: RangeError: invalid array length

```

**Comment by jnbr** [comment]
>  I suspect the "invalid array length" is important

I looked a bit into further. 
It seems, that the lz4 deciding in `OS.File.read()` fails on i686.
It works for the same file on x86_64.

**Comment by jnbr** [comment]
Correction: it's not the lz4 decoding but `OS.File.stat().size` which is off by 2^44
