### ISSUE TITLE
edb-debugger complain about plugins directory

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#13719]
### System

* xuname: Void 4.19.66_1 x86_64 GenuineIntel notuptodate rDDDDF

### Expected behavior
Hi. i tried to install edb-debugger [from repo](https://github.com/void-linux/void-packages/blob/f4fbe8d5f6cc339145a7d68a574a2edf8f1d8876/srcpkgs/edb-debugger/template
).
After successfully installation, when i run it, it complains about absence plugins directory. BTW, i decided to install it manually:
https://github.com/eteran/edb-debugger#cmake
Now, everything works. But i don't understand why it's not working via xbps?

Edit: Also before compilation, i installed some *-devel packages:
- boost-devel
- capstone-devel
- graphviz-devel
- qt5-devel
- qt5-svg-devel
- qt5-xmlpatterns-devel

@q66 

### Steps to reproduce the behavior
Just install edb-debugger from terminal with xbps. and see what happens!

**Comment by jnbr** [comment]
I pushed an update which fixes the default plugin path.
The wrong plugin path is stored in a config file, so you might have to reset it.
For this, go to Options -> Preferences -> Directories and set `Plugin Directory` to `/usr/lib/edb`
