### ISSUE TITLE
 Package request: Spyder

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#1372]
Hi,
I would like to propose new package called Spyder, it is very useful IDE and almost all of the dependencies are already in repos. Here is their website: https://www.spyder-ide.org/

**Comment by xue44** [comment]
Spyder can be donloaded by pip, but to put it in repo, I have to add

- [ ] Rope
- [ ] Qtawesome
- [ ] Qtpy
- [ ] Numpydoc
- [ ] Cloudpickle
- [ ] Spyder-kernels

I'll probably start tomorrow.

**Comment by xue44** [comment]
```
#Template file for 'python-rope'
pkgname=python-rope
version=0.10.7
revision=1
noarch=yes
wrksrc="rope-${version}"
build_style=python-module
pycompile_module="rope.py"
hostmakedepends="python python3"
depends="python"
maintainer="xue <xue44@protonmail.com>"
license="GPL-2"
homepage="https://github.com/python-rope/rope"
short_desc="Python refactoring library"
distfiles="https://github.com/python-rope/rope/archive/${version}.tar.gz"
checksum=4426d16686774f2b3d0431e5e54e7e261eab967e9e50e0af7fdaf95436057d74
 
python3-rope_package() {
    noarch=yes
    depends="python3"
    pycompile_module="rope.py"
    short_desc="${short_desc/Python2/Python3}"
    pkg_install() {
        vmove usr/lib/python3*
    }
}
```
+ ln -s for python3. It is my first pkg, could somebody verify it?
The rest should go the same, coz every dependency is a python library.
There is know issue that it won't compile on python 3.7 but right now it works quite well

**Comment by atisharma** [comment]
bump
