### ISSUE TITLE
xorg-server: default Xwrapper.config forces Xorg to always run as root

### ISSUE THREAD

**Issue by r00tman** [void-linux/void-packages#13754]
Is there a reason we keep `needs_root_rights = yes` in `/etc/X11/Xwrapper.config`, when we can change it to `needs_root_right = auto`? The latter would allow Xorg.wrap to drop root privileges if it detects that KMS is supported.

### System

* xuname:  
  Void 5.1.21_1 x86_64-musl GenuineIntel uptodate rF
* package:  
  xorg-server-1.20.5_1

### Expected behavior
Xorg.wrap drops root privileges if all cards support KMS

### Actual behavior
Xorg always runs as root.

### Steps to reproduce the behavior
Use default Xwrapper.config

**Comment by zdtcd** [comment]
In my experience, change `needs_root_rights` to `auto` requires adding user into `input` group to use the keyboard, mouse. We need to figure out which user should be added, and how.

**Comment by ericonr** [comment]
The only "safe" way this can work is by building xorg with `elogind` support by default, which I don't think will ever happen.

Can add a docs entry about it, maybe.
