### ISSUE TITLE
Package Request: cevelop

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#13767]
The C++ IDE for professional developers:
https://www.cevelop.com

**Comment by Johnnynator** [comment]
>You may not disclose, publish, translate, rent, lease, transfer, export or otherwise make the Software available in any form, to any person or entity, except as expressly licensed herein. You may not reverse engineer, decompile or disassemble the Software.

This strictly disallows to package it.

**Comment by LinArcX** [comment]
However, it can't be in non-free repo?
Like spotify or other non free packages.

**Comment by Johnnynator** [comment]
> @Johnnynator However, it can't be in non-free repo?
> Like spotify or other non free packages.

Spotify is a ugly hack that normally shouldn't be done in the first place, the correct way would be to create a restricted template that wouldn't end in repo since builders don't build restricted templates.

**Comment by LinArcX** [comment]
Ok. spotify was just an example. my question is, cevelop can't be in non-free repo?

**Comment by Johnnynator** [comment]
> Ok. spotify was just an example. my question is, cevelop can't be in non-free repo?

non-free is about software that is still allowed to be redistributed e.g., nvidia drivers, steam), cedevelop strictly forbids this.
