### ISSUE TITLE
'i2pd' funktions not working ?!

### ISSUE THREAD

**Issue by sass432** [void-linux/void-packages#13781]
The official repositories of voidlinux are presenting **'i2pd'** since a long time.
But how can I use it? How can I start it executable?
I am not able to use the funktions of it!
The instructions of the main link
[](https://i2pd.readthedocs.io/en/latest/user-guide/run/#starting-stopping-and-reloading-configuration))
don't work?
Or do I do something wrong?
Is there anyone with experience about that tool?

**Comment by Duncaen** [comment]
This is an issue tracker not a support forum.

**Comment by Duncaen** [comment]
This is an issue tracker not a support forum.
