### ISSUE TITLE
Building gcc fails with circular dependencies.

### ISSUE THREAD

**Issue by gravicappa** [void-linux/void-packages#13782]
### System

Ubuntu with xbps-src set up by [manual](https://github.com/void-linux/void-packages/blob/master/README.md#using-xbps-src-in-a-foreign-linux-distribution).
* void-packages:
  7a59e00e2d0e268b59821165c7458c442fb666a6
* package: 
  - gcc-9.1.0_3
  - glibc-2.30_1
  - python3-3.6.9_1

### Actual behavior

  There is a circular dependencies between gcc, glibc and python3.

### Steps to reproduce the behavior

```
  ./xbps-src zap
  ./xbps-src bootstrap
  ./xbps-src -C -E -N pkg base-files
```

I suspect that this is unintended use of xbps-src, but not sure.

**Comment by xtraeme** [comment]
Can't reproduce, please reopen if the problem still exists
