### ISSUE TITLE
mupdf: mupdf-gl broken copy-paste

### ISSUE THREAD

**Issue by svenper** [void-linux/void-packages#13871]
### System

* xuname:  
  Void 5.2.9_1 x86_64-musl GenuineIntel uptodate hold rrnFFFFFFFFF
* package:  
  mupdf-1.16.1_1

### Expected behavior

mupdf-gl copy-paste works as in version 1.13 (primary, not selection, unlike mupdf-x11)

### Actual behavior

clipboard only works isolated inside mupdf-gl

### Steps to reproduce the behavior

attempt to copy or paste between mupdf-gl and another X program

### More details

seems related to an upstream bug:

> There are two separate viewers on linux: mupdf-x11 and mupdf-gl.
>
> It appears that mupdf-x11 has a bug where what is highlighted isn't what is copied.
>
> Selecting by lines is specific to mupdf-gl. This viewer only sets the clipboard at the moment, so ^V should paste the content, rather than middle-click. I think this is an oversight, we should also be setting the primary selection on X11.
>
> However, since you mention not being able to copy the selection at all, you should be aware that you MUST build with OUR copy of FreeGLUT. The standard system FreeGLUT does NOT have copy & paste support. We have added clipboard support to our fork of FreeGLUT. I have tried to get our additions adopted upstream, but the maintainers are slow to respond, so please use our version of freeglut when building mupdf.
>
> [– upstream bug](https://bugs.ghostscript.com/show_bug.cgi?id=699079)

**Comment by jpmenil** [comment]
I doubt this is the same bug, as the fix have been included in release 1.13.0

**Comment by wangp** [comment]
Copy-paste will only work if mupdf-gl is built against the bundled copy of FreeGLUT, which adds the  functions glutSetClipboard and glutGetClipboard.
