### ISSUE TITLE
libllvm10 causes segfaults on cross targets

### ISSUE THREAD

**Issue by chriscamacho** [void-linux/void-packages#13896]
### System

* xuname:  
Void 4.19.66-v8-fc5826fb999e-p4-bis+ aarch64  uptodate rFFF
* package:  
 llvm8-8.0.0_7

### Expected behavior
various programs (2048-qt glxgears and probably more) should run

### Actual behavior
a message is displayed
No available targets are compatible with triple "x86_64-unknown-linux-gnu"
followed by a seg fault

### Steps to reproduce the behavior
boot a raspberry pi4 with a 64 bit kernel, using aarch64 root fs, recompile libICE (won't work otherwise), startX and run for example 2048-qt

recompiling llvm8 on actual hardware even with 4 jobs is a 16 hour job! I used -march=native

**Comment by chriscamacho** [comment]
some output from gcc on pi4 in case its useful 
``
$ gcc -march=native -E -v - </dev/null
Using built-in specs.
COLLECT_GCC=gcc
Target: aarch64-linux-gnu
Configured with: /builddir/gcc-9.1.0/configure --with-arch=armv8-a --host=aarch64-linux-gnu --with-build-sysroot=/usr/aarch64-linux-gnu --enable-sjlj-exceptions=no --enable-vtable-verify --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --libexecdir=/usr/lib --libdir=/usr/lib --enable-threads=posix --enable-__cxa_atexit --disable-multilib --with-system-zlib --enable-shared --enable-lto --enable-plugins --enable-linker-build-id --disable-werror --disable-nls --enable-default-pie --enable-default-ssp --enable-checking=release --disable-libstdcxx-pch --with-isl --with-linker-hash-style=gnu --disable-libunwind-exceptions --disable-target-libiberty --enable-languages=c,c++,lto,fortran,ada
Thread model: posix
gcc version 9.1.0 (GCC) 
COLLECT_GCC_OPTIONS= '-E' '-v' '-mlittle-endian' '-mabi=lp64' '-march=armv8-a+crc'
 /usr/lib/gcc/aarch64-linux-gnu/9.1.0/cc1 -E -quiet -v - -mlittle-endian -mabi=lp64 -march=armv8-a+crc
ignoring nonexistent directory "/usr/lib/gcc/aarch64-linux-gnu/9.1.0/../../../../aarch64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/aarch64-linux-gnu/9.1.0/include
 /usr/local/include
 /usr/lib/gcc/aarch64-linux-gnu/9.1.0/include-fixed
 /usr/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "<stdin>"
COMPILER_PATH=/usr/lib/gcc/aarch64-linux-gnu/9.1.0/:/usr/lib/gcc/aarch64-linux-gnu/9.1.0/:/usr/lib/gcc/aarch64-linux-gnu/:/usr/lib/gcc/aarch64-linux-gnu/9.1.0/:/usr/lib/gcc/aarch64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/aarch64-linux-gnu/9.1.0/:/usr/lib/gcc/aarch64-linux-gnu/9.1.0/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS= '-E' '-v' '-mlittle-endian' '-mabi=lp64' '-march=armv8-a+crc'

**Comment by chriscamacho** [comment]
sorry markup....

**Comment by CameronNemo** [comment]
similar to #13732

**Comment by chriscamacho** [comment]
@CameronNemo yes, I posted #13727 before I realized what was actually causing it (ie libllvm)

**Comment by ericonr** [comment]
@chriscamacho is this working for more recent llvm?

**Comment by ericonr** [comment]
Btw if this is closed, close #13727 too.

**Comment by ericonr** [comment]
Seems like it's an issue with how mesa is built, that it's pulling in wrong shaders. This has been confirmed in LLVM10.

**Comment by q66** [comment]
confirmed the issue

it's a problem with llvm itself, recompiling llvm10 on native aarch64 fixes mesa without rebuilding mesa

particualarly, this is a problem with the llvmpipe driver; native hardware drivers (e.g. radeonsi) work fine
