### ISSUE TITLE
polkit: does not work with consolekit anymore

### ISSUE THREAD

**Issue by Nicop06** [void-linux/void-packages#13944]
### System

* xuname:
  *Void 4.19.67_1 x86_64 AuthenticAMD uptodate rrrrmdFFFFFFFFFFF*
* package:  
  polkit-0.116

It seems that the option `--enable-libsystemd-login=no` was removed from the configure args of polkit, following the merge of `polkit` and `polkit-elogind`. This means that `polkit`it not able to detect the session when using consolekit and denies any permission I request. Adding the aforementioned option to the template files solves the issue.

**Comment by Hoshpak** [comment]
What functionality exactly are you missing? For me it was shutdown/reboot in the lxqt-leave menu. However that stopped working before that change since the polkit update before that seemed to have removed support or rules for that. It could easily be restored by putting the right polkit rules in place.

**Comment by Nicop06** [comment]
Indeed, this is one of the effects of this issue. To be more precise, the session menu of most desktop environment uses a DBUS call to know if the current user is authorized to reboot, shutdown, suspend the computer. This call will basically check the polkit rule without actually performing the action. For instance, here is the call sent to check if you can shutdown the computer:

```
$ dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.CanStop
method return time=1566820236.690266 sender=:1.3 -> destination=:1.17493 serial=74 reply_serial=2
   boolean false
```

Because this call returns false, you are not allowed to perform this action as a regular user so the entry is removed from the menu. This is because polkit is now compiled with `systemd` support on void, which is quite ironic for a distribution that does not support systemd. By logging how `polkit` is called, get the following log:

```
$ tail /var/log/socklog/secure/current
2019-08-26T11:52:55.94005 authpriv.notice: Aug 26 12:52:55 polkitd[1125]: /etc/polkit-1/rules.d/10-log.rules:2: action=[Action id='org.freedesktop.consolekit.system.stop']
2019-08-26T11:52:55.94018 authpriv.notice: Aug 26 12:52:55 polkitd[1125]: /etc/polkit-1/rules.d/10-log.rules:3: subject=[Subject pid=16399 user='YOUR_USER' groups=YOUR_GROUPS seat=null session=null local=false active=false]
```

As you can see, the current session is null and inactive. This means that you are not allowed to performed priviledged operations.

This log was obtained by adding the following rule taken from the `polkit` man page and adapted a little.

```
// /etc/polkit-1/rules.d/10-log.rules
polkit.addRule(function(action, subject) {
    polkit.log("action=" + action);
    polkit.log("subject=" + subject);
});
```

When disabling systemd support in `polkit`, it will default to `consolekit`, which means your session will be correctly detected.You will then get the following subject:

```
subject=[Subject pid=16399 user='YOUR_USER' groups=YOUR_GROUPS seat=null session=null local=true active=true]
```

It does fix the issue, but I am still puzzled as of why the session and seat are null. I will need to perform further investigation to get to the bottom of it. Considering systemd is now standard on linux I am guessing consolekit support has been depleted. Maybe the best solution to this issue is switch to elogind, the standalone implementation is systemd-logind service.

**Comment by Hoshpak** [comment]
Indeed, it was decided that elogind is now the default session tracker for Void Linux. This was prompted by a change in polkit which made ConsoleKit2 no longer work in the default configuration. I was sceptic regarding that decision but found it hard to argue for keeping a project that is virtually dead upstream (though still used by other distributions) as the default.

ConsoleKit2 is still there and can still be used instead of elogind but it requires some manual configurations and should not be expected to work out of the box.

**Comment by Nicop06** [comment]
Hum, it seems that I missed the news then. We should then update the documentation to remove ConsoleKit2: https://docs.voidlinux.org/config/xorg/session-management.html

In my particular case I guess I will move away from seat management. The only reason I had that is so that I can reboot my computer without password from the local session but not from the ssh unless I enter a password to avoid accidentally stopping my machine. However, being the only user of this machine, rebooting over SSH doesn't without password doesn't seem to be a big deal, and I can remotely boot my computer anyway.

**Comment by CameronNemo** [comment]
Just use an input keyboard logger to spawn an event.

**Comment by obunden** [comment]
So should this be closed since ConsoleKit seems to be on the way out and is unmaintained?

**Comment by Hoshpak** [comment]
Let's leave it open for a while, I think it should be reflected in the documentation that consolekit is not expected to work out of the box any more and needs manual intervention. I will prepare an update to the documentation.

**Comment by xtraeme** [comment]
consolekit2 is not supported anymore, use elogind.
