### ISSUE TITLE
LyX configuration does not work without python

### ISSUE THREAD

**Issue by scaramacai** [void-linux/void-packages#1399]
### System

* xuname:  
  *Void 4.17.6_1 x86_64-musl GenuineIntel/KVM uptodate rF*
* package:  
  *lyx-2.3.0_3*

### Expected behavior
LyX should configure without problems, hence it should depend on python.
Initial installation finishes with an error. Moreover, the reconfigure item in the menu does not work, since LyX internally calls a python script for configuration.

I'm nwe to Void and I admit that I don't know the Void policy about this kind of problem, but, although LyX in principle could be manually configured, since a menu item exists, that calls a python procedure, in my opinion python should be installed. Furthermore, python is used in other scripts in LyX.

### Actual behavior
In my box, without python, configuration does not work. 
### Steps to reproduce the behavior
Install LyX without python

**Comment by cr6git** [comment]
````
$ lyx

Looking for python v2.x or 3.x ...
Warning: No python v2.x or 3.x binary found.

Systemcall.cpp (278): Systemcall: 'python -tt "/usr/share/lyx/configure.py" --binary-dir="/usr/bin/"' did not start!
Systemcall.cpp (279): error The process failed to start. Either the invoked program is missing, or you may have insufficient permissions to invoke the program.

````
