### ISSUE TITLE
Calcurse problem: Nov. 3, 2019

### ISSUE THREAD

**Issue by Henry-Wilson** [void-linux/void-packages#13990]
### System

* xuname:  
  *Void 4.19.68_1 x86_64 GenuineIntel uptodate rFFF*
* package:  
  *calcurse 4.5.0*

### Expected behavior
  Display all dates correctly, with no inconsistencies in day-of-the-week labeling and no duplications.

### Actual behavior
  The date Nov. 3, 2019 is duplicated, appearing identically on both a Sunday and a Monday, causing the rest of the dates in the month of November to be shifted forward one day of the week.

### Steps to reproduce the behavior
  To make this apparent, move the cursor in the calendar pane to Nov. 3.
  You will see other effects if you should schedule a repeating appointment on a Monday, to begin before Nov. 3 and end after Nov. 3.
  All of the date numbers will be correct; the discrepancy will be in the rightward day-of-the-week shift in the calendar pane.

**Comment by lugubris** [comment]
This bug was reported to calcurse mailing list and a patch is available here: https://github.com/lfos/calcurse/commit/d6fd07785fe8072e6bbadc173e9d6a2e73efdcdd

Will be fixed in next calcurse update or if someone applies the patch.

**Comment by lugubris** [comment]
https://github.com/void-linux/void-packages/pull/13995
