### ISSUE TITLE
ffmpegthumbnailer: Missing thumbnailer entry

### ISSUE THREAD

**Issue by mamins1376** [void-linux/void-packages#14003]
### System

* xuname:  Void 4.19.67_1 x86_64-musl AuthenticAMD notuptodate hold rrnFFFF
* package:  ffmpegthumbnailer-2.2.0

### Expected behavior

`/usr/share/thumbnailers/ffmpegthumbnailer.thumbnailer` should exist.

### Actual behavior

But it does not; therefore file managers can not use it to generate thumbnails.

### Steps to reproduce the behavior

1. Install both `ffmpegthumbnailer` and `pcmanfm`.
2. Navigate to a directory where there is a video
3. A generic video icon is displayed instead of video thumbnail.

### Solution

The corresponding file exists under `dist/ffmpegthumbnailer.thumbnailer` in the package's source tarball. Build script should copy that into `/usr/share/thumbnailers`.

I myself can fix this and submit the pull request. Just wanted to be sure if this behavior is considered a bug or not.

**Comment by Hoshpak** [comment]
Please go ahead and create a PR.
