### ISSUE TITLE
Redshift for Wayland

### ISSUE THREAD

**Issue by yakthungba** [void-linux/void-packages#14013]
Hello,

I think it would be helpful for wayland users to have this package in official repo.

As mentioned in Sway github [wiki](https://github.com/swaywm/sway/wiki#Redshift), this is a fork of redshift by Minus7 with Wayland wlr-gamma-control protocol support.

The package is referred to as redshift-wlr.

Source https://github.com/minus7/redshift/tree/wayland

**Comment by Johnnynator** [comment]
We don't add unstable in development packages/forks that don't even have releases. There is a open pr to redshift https://github.com/jonls/redshift/pull/663 and once it is merged and has a tagged release you will see it here.
