### ISSUE TITLE
perl6: Non avoidable exception when running the compiler

### ISSUE THREAD

**Issue by streaksu** [void-linux/void-packages#14014]
### System
* xuname:  
  `Void 5.2.10_1 x86_64 AuthenticAMD uptodate rF`
* package:  
  `perl6, involving rakudo-2019.07.1_1`

### Expected behavior
`perl6` working, reporting info in a `--help` or doing its normal compilation process.

### Actual behavior
Typing `perl6` in a console, no matter the used shell or combination of flags, will report `
Unhandled exception: While looking for '/usr/share/perl6/runtime/perl6.moarvm': no such file or directory
` rendering the program useless.

### Steps to reproduce the behavior
Just typing `perl6` in the console.

**Comment by xtraeme** [comment]
Can't reproduce, please reopen if the problem still exists
