### ISSUE TITLE
iptables service run file expects GNU behavior of getopt_long (used by iptables-restore)

### ISSUE THREAD

**Issue by fritschy** [void-linux/void-packages#1403]
### System
* xuname:  Void 4.13.4-moo x86_64-musl GenuineIntel/KVM notuptodate r
* package:  iptables-1.6.2

### Problem Description
/etc/sv/iptables/run uses the -w option for iptables-restore. However, the option was added to the command _after_ the rule dump. This works fine on glibc systems, but musl does not implement permutation of the given argv to getopt*.

> GNU getopt permutes argv to pull options to the front, ahead of non-option arguments. musl and the POSIX standard getopt stop processing options at the first non-option argument with no permutation.

_From https://wiki.musl-libc.org/functional-differences-from-glibc.html_

The change in question is 2d2bfb8785fb912e9e0f42ed00b438383d357b1f.

### Expected behavior
The service should restore the iptables rule set.

### Actual behavior
The service is restarted (and fails) again and again by runsv.

### Steps to reproduce the behavior
Use iptables service to restore rules on a musl system.

**Comment by Nicop06** [comment]
Indeed, thank you @cr6git. I will try to fix that asap. I just need to install a musl void linux VM as I am using glibc.
