### ISSUE TITLE
Package Request : ksnip

### ISSUE THREAD

**Issue by thespectaculardonut** [void-linux/void-packages#14052]
Ksnip is a Qt based cross-platform screenshot tool that provides many annotation features for your screenshots. 
[https://github.com/DamirPorobic/ksnip](https://github.com/DamirPorobic/ksnip)

Personally i'd think it would be a great thing to add as installing something like spectacle for kde or lxqt drags in too many dependencies.

**Comment by Johnnynator** [comment]
kColorPicker doesn't yet provide a tagged release (a dep of ksnip). I opened a Issue for that on their Github page https://github.com/DamirPorobic/kColorPicker/issues/2
