### ISSUE TITLE
Package request: linux-libre

### ISSUE THREAD

**Issue by mahaer-mahmud** [void-linux/void-packages#14062]
Linux, the kernel developed and distributed by Linus Torvalds et al, contains non-Free Software, i.e., software that does not respect your essential freedoms, and it induces you to install additional non-Free Software that it doesn't contain. Even after allegedly moving all firmware to a separate project as of release 4.14, Linux so-called "sources" published by Mr Torvalds still contain non-Free firmware disguised as source code.

GNU Linux-libre is a project to maintain and publish 100% Free distributions of Linux, suitable for use in Free System Distributions, removing software that is included without source code, with obfuscated or obscured source code, under non-Free Software licenses, that do not permit you to change the software so that it does what you wish, and that induces or requires you to install additional pieces of non-Free Software.

Website: https://www.fsfla.org/ikiwiki/selibre/linux-libre/

If this is added, people can install a 100% free operating system with Void Linux. No longer do they have to deal with binary blobs.

**Comment by Hoshpak** [comment]
we don't provide modified kernel versions.

**Comment by mahaer-mahmud** [comment]
So then how do I install the free kernel?

**Comment by Hoshpak** [comment]
Fetch the sources, configure it, install it. How you would install any custom kernel. You could also fork the void-packages repository and create your own template for linux-libre based on one of the existing kernel templates and compile it if you would like to install it via the package manager.

**Comment by mahaer-mahmud** [comment]
How do I create a Void Linux package?
