### ISSUE TITLE
marble5 misplaced file

### ISSUE THREAD

**Issue by no2spam** [void-linux/void-packages#14060]
### System

* xuname:  
  *Void 4.19.66_1 x86_64 AuthenticAMD uptodate rrrmFFFF*
* package:  
  *marble5-19.08.0_1*

### Expected behavior
marble.knrsc should be placed at /etc/xdg/ directory
### Actual behavior
file is placed at /usr/etc/xdg/ directory
### Steps to reproduce the behavior
install the package

**Comment by Chocimier** [comment]
What will start to work after move?

**Comment by no2spam** [comment]
I can't notice the difference in functionality. Maybe the file is unnecessary then.
I came across this file while browsing /usr .  I've noticed that a new folder /usr/etc appeared which seemed to be out of place.

**Comment by ndowens** [comment]
I agree, /usr/etc doesn't seem right

**Comment by Chocimier** [comment]
Looks like defect in extra-cmake-modules, I proposed patch to upstream.
