### ISSUE TITLE
`glibc-devel` lacks `stropts.h`

### ISSUE THREAD

**Issue by SolitudeSF** [void-linux/void-packages#14173]
Other distros (arch, gentoo) have `/usr/include/stropts.h`, `/usr/include/sys/stropts.h` and `/usr/include/bits/stropts.h` in some glibc related package. i dont know if others are missing, thats just the ones i stumbled on when compiling stuff.

**Comment by Duncaen** [comment]
Looks like it was removed in `glibc-2.30` https://sourceware.org/ml/libc-alpha/2019-08/msg00029.html, arch linux is still on `2.29`.

**Comment by SolitudeSF** [comment]
ah, ok.
