### ISSUE TITLE
Package request: pkgtop

### ISSUE THREAD

**Issue by lugubris** [void-linux/void-packages#14180]
* package:  https://github.com/keylo99/pkgtop

pkgtop is an interactive package manager & resource monitor tool designed for the GNU/Linux.

**Comment by flexibeast** [comment]
The README for `pkgtop` says:

> You can use pkgtop if you have one of the package managers listed below.
>
> pacman
> apt
> zypper, rpm
> dnf, rpm

XBPS isn't listed, so could you explain how this software would be useful on a Void system?

**Comment by lugubris** [comment]
Alexis @ 2019-09-03 10:01 UTC:

> The README for `pkgtop` says:
>
>> You can use pkgtop if you have one of the package managers listed below.
>>
>> pacman
>> apt
>> zypper, rpm
>> dnf, rpm
>
> XBPS isn't listed, so could you explain how this software would be useful on a Void system?

@Alexis, xbps supported was merged to master. Probably the maintainer
forgot to update the readme, https://github.com/keylo99/pkgtop/pull/19
--
                                Lugubris
