### ISSUE TITLE
aws-cli: outdated boto dependency

### ISSUE THREAD

**Issue by teotwaki** [void-linux/void-packages#14253]
### System

* xuname:  
  *Void 4.19.68_1 x86_64 GenuineIntel uptodate rF*
* package:  
  *aws-cli-1.16.231_1*

### Expected behavior

`aws configure` should prompt the user to setup the CLI tool. Example:

```
$ aws configure
AWS Access Key ID [None]: accesskey
AWS Secret Access Key [None]: secretkey
Default region name [None]: us-west-2
Default output format [None]:
```

### Actual behavior

```
$ aws configure

Credential named assume-role-with-web-identity not found.
```

### Steps to reproduce the behavior

- Update to the latest available `aws-cli` package
- Run `aws configure`

### Cause

This appears to be due to an outdated version of botocore (https://github.com/aws/aws-cli/issues/4371). AWS Support recommends to upgrade botocore to version >=1.12.201. Currently `python3-botocore-1.12.148_1` is pulled instead.

/cc @leahneukirchen

**Comment by leahneukirchen** [comment]
Try with 1.12.223.

**Comment by bobertlo** [comment]
@teotwaki has this issue resolved for you with the newer versions? It is working for me with the example you provided.

**Comment by teotwaki** [comment]
@bobertlo I switched to the pypi-provided version of aws-cli instead of the xbps one to solve this issue for me, just reported it here for completeness/others.

**Comment by bobertlo** [comment]
Ok. Sorry about that. I will watch this closer. Someone bumped aws-cli without bumping botocore at some point. I was away for a while but will try to update this more regularly (but probably not daily ;)

**Comment by bobertlo** [comment]
Another note is I tested this on a different box that had aws installed from pip and the dependencies were all screwy after I removed just aws. python is the worst ;) otherwise I think this can be closed.
