### ISSUE TITLE
package request: arangodb

### ISSUE THREAD

**Issue by roket1428** [void-linux/void-packages#14255]
* source: https://github.com/arangodb/arangodb
* description: ArangoDB is a native multi-model database with flexible data models for documents, graphs, and key-values. Build high performance applications using a convenient SQL-like query language or JavaScript extensions.
* why: Because there's no sane and free nosql database in official void repos.

**Comment by CameronNemo** [comment]
Not sure if this will be the most fruitful route. Look at all of the database systems, including orientdb, postgresql, couchdb, mysql and mariadb, most are out of date.

You could try a container with a persistent volume configured.

**Comment by roket1428** [comment]
> Not sure if this will be the most fruitful route. Look at all of the database systems, including orientdb, postgresql, couchdb, mysql and mariadb, most are out of date.
> 
> You could try a container with a persistent volume configured.

I know but you know, it would be nice to void also supports web devs.
