### ISSUE TITLE
firefox 69 fails build with some options disabled

### ISSUE THREAD

**Issue by svenper** [void-linux/void-packages#14269]
### System

* xuname:  
  firefox-69.0_1: broken, unresolvable shlib `libdbus-glib-1.so.2'
Transaction aborted due to unresolved shlibs.
dmesg: read kernel buffer failed: Operation not permitted
Void 5.2.11_1 x86_64-musl GenuineIntel uptodate hold rrnFFFFFFFFFFF
* package:  
  firefox-69.0_1

### Expected behavior

Firefox can either build without dbus, or does not have dbus optional.

### Actual behavior

Firefox does not build without these template options. References to `dbus::Error::empty`, `dbus::connection::Connection::get_private`, `dbus::connection::Connection::conn_from_ptr`, `dbus::watch::WatchList::new`, etc. fail. Lots of lines of 
```
/usr/bin/ld: DWARF error: mangled line number section (bad file number)
```

Building firefox on my machine is quite slow so I've yet to find exactly what build options cause the fail but it looks like dbus based on the log.

[end of log](https://gist.githubusercontent.com/svenper/93c4ff5f5b78cead49c482ce091abcd2/raw)

### Steps to reproduce the behavior

```
./xbps-src pkg firefox -o alsa,~dbus,~pulseaudio,~sndio,~startup_notification,~wayland,~xscreensaver
```

**Comment by Duncaen** [comment]
`--disable-dbus` was removed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1561207

**Comment by dylanaraps** [comment]
> --disable-dbus was removed.

This is false. `--disable-dbus` is still supported.

What happened in Firefox 69 was a **regression**, it's a bug that `--disable-dbus` still lets through a `dbus` related component. 

I have written a patch for it here and Firefox builds fine **without** `dbus` afterwards: https://github.com/kisslinux/repo/blob/master/extra/firefox/patches/firefox-69-no-dbus.patch

**Comment by svenper** [comment]
@dylanaraps thanks for the info! I was able to apply [your v72 patch](https://github.com/kisslinux/repo/blob/35fd7ff2fe1ec6f814bfc40c6d7122404af70088/extra/firefox/patches/firefox-72-no-dbus.patch) to Void after stripping one path level. Was there anything in particular that caused you to downgrade to the ESR version?

**Comment by dylanaraps** [comment]
Firefox (and Chromium) are hard to maintain and each year this issue gets worse and worse. Firefox started taking up a lot of my time as each release broke *something*. 

Swapping to the ESR means a singe big (and breaking) release a year with minor security fixes throughout. Much easier to maintain and it allows me to dedicate more time elsewhere. 

The ESR has also enabled me to ship a `firefox-bin` package to users which enables them to avoid building `rust`, `nodejs`, `gtk2`, `python2` and Firefox every so often.

I also don't know what the future holds for Firefox and staying behind the main releases gives me some breathing room regarding `dbus`, `alsa` (still working), etc.

**Comment by svenper** [comment]
@dylanaraps did you ever encounter this error or have an idea what could cause it?

```text
collect2: fatal error: ld terminated with signal 9 [Killed]
```

I'm trying to build Void's 76.0.1_1 with the only change being adding [your latest patch](https://github.com/kisslinux/repo/blob/5ad83189aba96dc7f70830a21f4110fc5163c779/extra/firefox/patches/no-dbus.patch). 75 worked

**Comment by dylanaraps** [comment]
Interesting. I can't personally reproduce this at all. It builds fine here. Tried having a look at what build flags we use, etc?

**Comment by Duncaen** [comment]
checked dmesg for oom kill?

**Comment by pullmoll** [comment]
This is usually a sign of `ENOMEM`.

**Comment by svenper** [comment]
What exactly are we looking for?

<details>
  <summary>sudo dmesg | grep -Ei 'memory|oom|mem\b'</summary>

```dmesg
[21662.540805] IPDL Background invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
[21662.540832]  oom_kill_process.cold+0xb/0x10
[21662.540836]  out_of_memory+0x1a1/0x440
[21662.540954] Mem-Info:
                mapped:4134 shmem:4208 pagetables:7889 bounce:0
[21662.540966] Node 0 active_anon:3227628kB inactive_anon:645436kB active_file:196kB inactive_file:224kB unevictable:16776kB isolated(anon):256kB isolated(file):0kB mapped:16536kB dirty:0kB writeback:8kB shmem:16832kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[21662.541050] 0 pages HighMem/MovableOnly
[21662.541053] Tasks state (memory values in pages):
[21662.541054] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[21662.541294] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=ld,pid=4869,uid=1000
[21662.541308] Out of memory: Killed process 4869 (ld) total-vm:11085876kB, anon-rss:3796320kB, file-rss:4kB, shmem-rss:0kB, UID:1000 pgtables:20292kB oom_score_adj:0
[21664.624082] oom_reaper: reaped process 4869 (ld), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
</details>

**Comment by Duncaen** [comment]
> ```
> [21662.541308] Out of memory: Killed process 4869 (ld) total-vm:11085876kB, anon-rss:3796320kB, file-rss:4kB, shmem-rss:0kB, UID:1000 pgtables:20292kB oom_score_adj:0
> ```

Yes was killed because your system did run out of memory.

**Comment by svenper** [comment]
After clearing some space I was able to build! Still confusing though, is that I have 8GB RAM plus 8GB swap. Am I reading the `total-vm:11085876kB` correctly that it killed at 11GB? I probably ran out of disk space but the swap file should be a fixed size anyway, so why this error?

```text
$ free
              total        used        free      shared  buff/cache   available
Mem:        8122788      423424     6753304      283556      946060     7065116
Swap:       8323068        4444     8318624
```

**Comment by ericonr** [comment]
Is this issue still relevant?

**Comment by svenper** [comment]
not as of 81.0.1, I haven't built later ones yet however

**Comment by ericonr** [comment]
Feel free to reopen if you experience the issue again.

Thanks!
