### ISSUE TITLE
nvidia340-dkms fails to build

### ISSUE THREAD

**Issue by VoidDuck** [void-linux/void-packages#14273]
### System
* xuname:  
  Void 4.19.69_1 x86_64 GenuineIntel uptodate rF
* package:  
  nvidia340-dkms-340.107_3

### Expected behavior
The kernel module should be built and installed

### Actual behavior
The build fails with following error message:
`ERROR: Kernel configuration is invalid
include/generated/autoconf.h or include/config/auto.conf are missing.
Run 'make oldconfig && make prepare' on kernel src to fix it.`

Running `make oldconfig && make prepare` gives an error as well:
`scripts/kconfig/conf  --syncconfig Kconfig
scripts/Makefile.build:45: arch/x86/entry/syscalls/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/x86/entry/syscalls/Makefile'.  Stop.
make: *** [arch/x86/Makefile:245: archheaders] Error 2`

### Steps to reproduce the behavior
Install nvidia340

**Comment by Hoshpak** [comment]
It works fine here. Are you sure the kernel headers are installed properly?

**Comment by VoidDuck** [comment]
linux4.19-headers package is installed. May there be some manual task needed for the headers to be installed properly?

You can see my complete log if it cans help you.
[make.log](https://github.com/void-linux/void-packages/files/3586559/make.log)

**Comment by Hoshpak** [comment]
Please check your `/usr/bin/cc` symlink. If it points to clang or any other compiler that is not gcc, use xbps-alternatives to set it back to gcc. The errors look like the wrong compiler is used to build the kernel module.

**Comment by VoidDuck** [comment]
You're right! It works fine now. Thank you.

**Comment by VoidDuck** [comment]
Seems not to work with linux5.2 (which just became default). Here is my log again.
[make.log](https://github.com/void-linux/void-packages/files/3595625/make.log)

**Comment by Hoshpak** [comment]
That is indeed an issue with the package. nvidia340 was only tested on i686 up to now and this architecture doesn't have the uvm module. I will see if I can find a way to patch this once I have time to test myself.
