### ISSUE TITLE
Package request: drumgizmo

### ISSUE THREAD

**Issue by luzpaz** [void-linux/void-packages#14279]
Website: https://www.drumgizmo.org  
git repo:  http://git.drumgizmo.org/drumgizmo.git  
Latest stable: 0.9.17  
Changelog: https://drumgizmo.org/wiki/doku.php?id=changelog:drumgizmo-0.9.17

> DrumGizmo is an open source, multichannel, multilayered, cross-platform drum plugin and stand-alone application. It enables you to compose drums in midi and mix them with a multichannel approach. It is comparable to that of mixing a real drumkit that has been recorded with a multimic setup.

> Features include:

> Stand-alone, Lv2 and VSTi versions available
Open drumkit file format, allowing the community to create their own drumkits
Drum velocity, allowing for several different hit velocities for each drum
Multichannel output, making it possible to mix it just the way you would a real drumkit
Optional built-in humanizer, analyzing the midi notes, adjusting velocities on-the-fly
Stand-alone midi renderer, generating .wav files, 1 for each channel
Stand-alone midi input, making it possible to use DrumGizmo as a software sampler for an electronic drumkit

**Comment by luzpaz** [comment]
Latest stable: 0.9.18.1
Changelog: https://drumgizmo.org/wiki/doku.php?id=changelog:drumgizmo-0.9.18.1

**Comment by uzr123x** [comment]
good one, I second this

**Comment by biopsin** [comment]
I have started on the template and it builds for x86_64-glibc
https://github.com/biopsin/void-packages/commit/9644c2356927789c26758dbec675142c59960f9e

However I still need to figure out why the standalone is missing and I have not tested any other arches..
I will also actually test the lv2 plugin in Reaper in near future.
Any suggestion or comments to improve the template is always welcome.

**Comment by timsofteng** [comment]
any updates about it?

**Comment by biopsin** [comment]
@timsofteng sorry Im no longer interested in the plug, got other tools I prefer.
