### ISSUE TITLE
Package Request : Gnumed

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#14306]
Home Page : http://wiki.gnumed.de/bin/view/Gnumed/WebHome
Source Code Download : http://wiki.gnumed.de/bin/view/Gnumed/InstallerGuideHomeShort
Github Repo : https://github.com/ncqgm/gnumed

I'm not sure if this will be approved but it'll make my future school related work for easier so hopefully it'll be approved to be added. Also i bit of a note but would it be possible to add the client & the server version of it?

**Comment by Itamiko** [comment]
I could work on this today. but the client & server servers will be separated packages.

**Comment by thespectaculardonut** [comment]
Thanks, this will be very helpful, i don't want to be forced into using windows just for one program.

**Comment by luzpaz** [comment]
the hyperlinks in https://github.com/void-linux/void-packages/issues/14306#issue-490698232 are borked

**Comment by thespectaculardonut** [comment]
Does this mean i should  redo the links on this and my other package request for qtile? I checked it out and my links for qtile are also borked.

**Comment by Johnnynator** [comment]
Just edit your post to fix them. Just remove all the markdown around them, github normally handles them good enough.

**Comment by thespectaculardonut** [comment]
Alright then.

**Comment by thespectaculardonut** [comment]
I removed the markdown formatting.

**Comment by luzpaz** [comment]
JFYI, markdown links are formatted like this `[example](https://example.com)`

**Comment by thespectaculardonut** [comment]
Ok, thanks.
