### ISSUE TITLE
Package Request : qtile

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#14373]
https://github.com/qtile/qtile

A small, flexible, scriptable tiling window manager written in Python

http://www.qtile.org/

I was thinking of changing my workflow from xfce to qtile and i checked it was not in the repositories nor was their a past package request or current pull request that i could see.

**Comment by CarDGee** [comment]
This is a old request, but I was wondering if there are any plans to package qtile on void?
Apart from gentoo and arch there isn't much love to this window manager that is very actively developed.
It would be great to have it on void (fill the void :) ).

**Comment by paper42** [comment]
@CarDGee As I mentioned in #14638, if someone creates a new PR, I am interested in reviewing (and then potentially merging) it.

**Comment by CarDGee** [comment]
@paper42  Thank you for replying, with version 0.18.0 qtile brings wayland support so along with python3-xcffib that I managed to create a template to newest version we would also need to package pywayland and pywlroots along with qtile of course, and so far I have been unsuccessfull.

**Comment by paper42** [comment]
> @paper42 Thank you for replying, with version 0.18.0 qtile brings wayland support so along with python3-xcffib that I managed to create a template to newest version we would also need to package pywayland and pywlroots along with qtile of course, and so far I have been unsuccessfull.

If you have some specific issues, we can try helping you in #voidlinux on libera.chat
