### ISSUE TITLE
gstreamer1: libgstreamer-1.0.so.0.1600.0-gdb.py references wrong path

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#14409]
### System

* xuname:  
  *x86_64-musl
* package:  
  *gstreamer1-1.16.0_1*

### Expected behavior

gdb not throwing an error while loading
`/usr/share/gdb/auto-load/usr/lib/libgstreamer-1.0.so.0.1600.0-gdb.py`

### Actual behavior
smth like
`gst_gdb no found`

### Steps to reproduce the behavior
Install gstreamer1 and gdb
`gdb /usr/bin/gst-inspect-1.0`

This behavior stems from the fact that `gst_dbg` is located in `/usr/share/glib-2.0/gdb` but `libgstreamer-1.0.so.0.1600.0-gdb.py` searches in `/usr/share/gstreamer-1.0/gdb`

**Comment by ericonr** [comment]
@Johnnynator I can not reproduce this... Is it still an issue?

**Comment by Johnnynator** [comment]
Is fixed.
