### ISSUE TITLE
Cross Compile Exec Error

### ISSUE THREAD

**Issue by sammerry** [void-linux/void-packages#14456]
### System

* xuname:  
Void 5.2.14_1 x86_64 GenuineIntel uptodate rrFF
* package:  
xbps-src binary-bootstrap armv7l

### Expected behavior
`xbps-src binary-bootstrap armv7l` runs the same as x86 `xbps-src binary-bootstrap`

### Actual behavior
after successfully installing dependencies i get the following error during reconfigure
```
0 downloaded, 64 installed, 0 updated, 64 configured, 0 removed.
=> Installed bootstrap successfully!
ERROR Failed to execute command /void-packages/xbps-src (Exec format error)
```

### Steps to reproduce the behavior
run the following command
`./xbps-src binary-bootstrap armv7l`

**Comment by Piraty** [comment]
how is that supposed to work?
`./xbps-src <binary->bootstrap <arch>` sets up a masterdir/chroot for the given arch (or the one you run on, if none is given).
you can't run arm code on an x86 (at least not in this chroot with xbps-src. qemu would be an option but that's not supported currently).

What you're probably after is `./xbps-src -a <arch>` if you intend to crosscompile from x86 to arm

**Comment by sammerry** [comment]
thanks
