### ISSUE TITLE
Chromium cannot determine default browser on KDE Plasma

### ISSUE THREAD

**Issue by daunknownfox2010** [void-linux/void-packages#14457]
Under a fresh install of KDE Plasma in combination with Chromium, it seems Chromium cannot determine the default browser under the KDE Plasma environment (I have also tested it with LXQt installed alongside KDE Plasma, it seems to work there oddly enough).

### System

* xuname:  
  *Void 5.2.14_1 x86_64 AuthenticAMD*
* package:  
  *chromium-76.0.3809.132_1*

### Expected behavior

Chromium should be able to determine the default browser that is set.

### Actual behavior

Chromium cannot determine the default browser ("Chromium cannot determine or set the default browser") on the Settings page.

### Steps to reproduce the behavior

Use the KDE Plasma desktop and open Chromium. Navigate to the Settings page and look under "Default browser", you should see it cannot determine the default browser.

**Comment by Johnnynator** [comment]
Turns out, the problem is simply that `xdg-settings` is not compatible with dash, that issue wasn't caused by neither chromium nor KDE Plasma.
