### ISSUE TITLE
Couple of issues with NVIDIA and ibus

### ISSUE THREAD

**Issue by EmonHaque** [void-linux/void-packages#14464]
Is there ways to solve [these](https://www.youtube.com/watch?v=-ACMsE1wJ6U) issues?

**Comment by Johnnynator** [comment]
Can you please write out these issues, I'm not going to watch a 10 minute Video in the hope I catch the right details.

**Comment by EmonHaque** [comment]
It'll definitely take way more than 10 min to read and understand! There's no better way than an audio-visual content to explain these precisely. I'd posted a couple of these issues earlier [Here](https://unix.stackexchange.com/questions/532001/ibus-input-method-doesnt-work-in-code-oss) and [here](https://unix.stackexchange.com/questions/531255/trouble-with-nvidia-optimus)!

**Comment by Johnnynator** [comment]
Yep, and you should do one ticket per issue, so a) we can properly tack them, b) others know that they are already reported. c) text is way easier to search d) less bandwidth.

**Comment by EmonHaque** [comment]
Ok! I'll try Void next year again, if I be alive, to see the progress of Void team in mitigating these issues.

Thanks.

**Comment by Johnnynator** [comment]
> Ok! I'll try Void next year again, if I be alive, to see the progress of Void team in mitigating these issues.

You know, all here are just volunteers, so if you want to see issues fixed, the least minimum is to make a half decent bug report, a Video is always only a addition to a bug report if visualizing helps, but never the bug report itself.. I did take a look at the first minute of the vid, yep systemsttings5 is chrashing, why? IDK. There is no helpful indication and everything that would help resolving this is missing, no information at what it is printing to stdout/stderr, not backtrace, nothing that would help at all.

**Comment by EmonHaque** [comment]
Thanks again for your reply.

I don't know much about Linux and IDK how to get those stderr? A month ago when I first tried void, I'd seen [vlc player crashed](https://unix.stackexchange.com/questions/531774/vlc-player-crashes) too but this time it worked, don't know how! My main issue is ibus input on Code-OSS and NVIDIA. I usually write my documents in latex nowadays on Code-OSS with LatexWorkshop plugin and sometime record screen with obs with NVENC. 

After that systemsettings crash, on that video I've shown, I can write multilingual documents in libreoffice-writer and kate using ibus BUT I can't on Code-OSS. I also have shown how did I install NVIDIA and how it messes up the build-in GPU and Intel HD no longer works if I install NVIDIA. 

I think I'd use Void instead of Arch if NVIDIA and ibus worked properly, I'm on linux since end of June this year and to me Void is next best to Arch.
