### ISSUE TITLE
pax-utils as a dependency to base-minimal in musl edition

### ISSUE THREAD

**Issue by am11** [void-linux/void-packages#14489]
### System

* xuname:  
`Void 4.9.184-linuxkit x86_64-musl GenuineIntel uptodate rF`

* package:  
base-minimal

### Expected behavior
A base installation of Void Linux, in both glibc and musl-libc editions, has the tool called ldconfig, which helps applications and other tools to find out which system libraries are installed.

`ldconfig` does pretty much nothing on musl-libc based systems. The alternative is scanelf for musl-libc, which pax-utils package provides.

In minimal Alpine Linux installation, pax-utils is included. The expectation from Void Linux (musl-libc edition) is also to have pax-utils as part of minimal install (docker scenario).

### Actual behavior

There is no usable tools available in base-minimal for system-library introspection.

### Steps to reproduce the behavior

glibc case

```sh
docker run -it voidlinux/voidlinux dash # glibc edition

ldconfig -NvX
# lists the installed system libraries
```

musl-libc

```sh
docker run -it voidlinux/voidlinux-musl dash # glibc edition

ldconfig -NvX
# returns nothing
# it's pretty much a no-op on musl, alternative is 'scanelf'

scanelf
dash: 2: scanelf: not found

xbps-install -S
xbps-install pax-utils

scanelf --ldpath -BF '%f'
# lists the installed system libraries
```

**Comment by Piraty** [comment]
```
$ xbps-query -o /usr/bin/ldconfig
musl-1.1.23_2: /usr/bin/ldconfig -> /usr/bin/true (link)
```

**Comment by leahneukirchen** [comment]
Closing, this is not necessary for a base-minimal setup.

**Comment by am11** [comment]
Even a minimum system should have a library introspection utility. The docker image of alpine base is 
12.3 times smaller than Void musl (5.58MB vs. 68.6MB), and it contains pax-utils in base system, because it is deemed as a fundamental component. Maybe something else can be dropped from base minimal, instead of pax-utils?
