### ISSUE TITLE
ncurses-base as dependency to nano and bash/ncurses-libs

### ISSUE THREAD

**Issue by am11** [void-linux/void-packages#14488]
### System

* xuname:  

`Void 4.9.184-linuxkit x86_64-musl GenuineIntel uptodate rF`

* package:  

`bash-5.0.009_1`
`nano-4.4_1`

### Expected behavior

With `base-minimal` (voidlinux-musl docker e.g.), when we install bash or nano, these packages should install ncurses-base package for the software to function.

### Actual behavior

After some googling and figuring out, it appears that the `ncurses-base` (and more granually, what Alpine Linux ports calls `ncurses-terminfo-base`) package is the one which is missing.

### Steps to reproduce the behavior

nano:

```sh
docker run -it voidlinux/voidlinux-musl dash

# inside the container
xbps-install -S
xbps-install -y nano

nano
# terminates with:
Error opening terminal: xterm.

# to fix the error
xbps-install ncurses-base

nano # it works!
```

bash:

```sh
docker run -it voidlinux/voidlinux-musl dash

# entered the container
xbps-install -S
xbps-install -y bash

bash
# entered bash

# type something and press ENTER
ls
# type something again and press ENTER
cd
# now press UP and UP, it looks like:
cdls
#instead of
ls

# similarly, back arrow key to navigate cursor does not move the caret.
# also, BACKSPACE renders spaces instead of erasing the character at caret.
# etc.

# to fix these issues
xbps-install ncurses-base

# exit and reenter bash to get the keybindings behave correctly
```

**Comment by zdtcd** [comment]
I don't think bash should depend on ncurses, since bash can be used for non-interactive session, which is the main use case of docker image.

**Comment by xtraeme** [comment]
Well, I agree. A build option possibly maybe

**Comment by ericonr** [comment]
I'm not sure this can be solved at all. A minimal container doesn't want to have ncurses-base
/

**Comment by sgn** [comment]
On 2021-01-29 19:03:35-0800, Érico Nogueira Rolim <notifications@github.com> wrote:
> I'm not sure this can be solved at all. A minimal container doesn't want to have ncurses-base

My opinion is this is not a bug, working as intended.

**Comment by ericonr** [comment]
This has also been expressed on IRC.

**Comment by am11** [comment]
Well, I am not following IRC, neither have I asked to modify minimal container. I thought this is just a case of `nano` package missing `checkdepends="ncurses-base"` line to avoid "Error opening terminal: xterm." as described in the top post.

**Comment by Duncaen** [comment]
But where would this end, would we add `ncurses-base` to everything that depends on ncurses i.e. util-linux because of cfdisk?

The point is that `ncurses-base` is part of the `base-system` to avoid that, `base-minmal` doesn't have it to avoid blowing up the size for containers that are not going to be used interactively.

**Comment by am11** [comment]
Conversely, if the rationale behind existing packages with explicit dependency on `ncurses-base` (i.e. [`newsboat`](https://github.com/void-linux/void-packages/blob/2635aeec82926d6228fef8e8622cf2d583a1b400/srcpkgs/newsboat/template#L12) and [`pick`](https://github.com/void-linux/void-packages/blob/df7ebc36a9ffb208a0d60da58a98a2c4936b1735/srcpkgs/pick/template#L9)) is that they do not function without this dependency, then I think `nano` also qualifies.

**Comment by Duncaen** [comment]
You are right, the dependency should be removed from those packages. They don't depend on `ncurses-base` they depend on a definition for the used terminal which can not be expressed as dependency.
