### ISSUE TITLE
Package Request: ibus-libthai

### ISSUE THREAD

**Issue by foxmean** [void-linux/void-packages#14513]
* IBus-LibThai:  
IBus-LibThai is a Thai input method engine for IBus, based on the LibThai
library.
* package upstream:  
Git: https://github.com/tlwg/ibus-libthai
FTP: ftp://linux.thai.net/pub/thailinux/software/libthai

### Expected behavior
For Adding Thai keyboard on IBUS

**Comment by sirn** [comment]
I think this can be closed #15801

**Comment by foxmean** [comment]
Thank you @sirn
