### ISSUE TITLE
chsh USERNAME does not work on musl

### ISSUE THREAD

**Issue by CMB** [void-linux/void-packages#14631]
Attempting a "chsh USERNAME" as root under the musl variant of Void
Linux changes root's shell, rather than USERNAME's shell.  I do not have
the same problem on glibc.  I've reproduced this on two systems so far,
the latest being fully upgraded about 20 minutes ago.

FWIW, I have only tried with x86.

**Comment by CMB** [comment]
Note that chsh reports that it changed the shell for USERNAME, though
in reality it has changed the shell for root.

**Comment by xtraeme** [comment]
Lmao rofl

**Comment by steinex** [comment]
This was fixed with https://github.com/void-linux/void-packages/commit/abbf0a33c7f75a5948b729ebd5438a3c63d5106a
