### ISSUE TITLE
`libappindicator-devel` depend on `libdbusmenu-glib-devel`

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#14684]
### System

* xuname:  
```
dmesg: read kernel buffer failed: Operation not permitted
Void 5.2.17_1 x86_64 GenuineIntel notuptodate rrDDDDFF
```

* package:  
libappindicator-devel

### Expected behavior
I'm developing a gtk application and using libappindicator. So, i installed: `libappindicator-devel` and when i want to build the project via cmake, it says:

>  -- Checking for modules 'gtk+-3.0;appindicator3-0.1'
> --   Package 'dbusmenu-glib-0.4', required by 'appindicator3-0.1', not found

So after that i installed libdbusmenu-glib-devel persoanally and now everything works fine. pleas add `libdbusmenu-glib-devel` to list of dependencies of `libappindicator-devel`.

**Comment by LinArcX** [comment]
Why you [add](https://github.com/void-linux/void-packages/commit/56ac452814c7ac74a445027a47e99429c88e06fc#diff-41446c5c55cbad943f56d7af242403e5R32) `gtk+3-devel`?

**Comment by Hoshpak** [comment]
It's listed as dependency in the pkg-config file:

```
Requires: dbusmenu-glib-0.4 gtk+-3.0
```
