### ISSUE TITLE
XFCE (4.14) PolicyKit Agent Error 

### ISSUE THREAD

**Issue by userx-bw** [void-linux/void-packages#14689]
4.12 actaully.

after install of void-live-x86_64-20181111-xfce.iso then the post update to everything in the system, gaining xfce 4.14. 

I rebooted then got the xfce polkit error, was locked out of gaining wifi access both in root and user log ins, basiclly everything polkilt-1 deals with in xfce was revoked in root and user with wheel group. I had to reinstall and am currentlly in this new install adding another desktop for a backup. WindowMaker. 

https://github.com/void-linux/void-packages/issues/13511
followed that off my iPhone, and the 'fix' did not work. which lead me to re-installing this OS again and posting this.

**Comment by Jetba** [comment]
To fix the issue, you may either install elogind or start XFCE4 with ConsoleKit. This seems to be related to commit https://github.com/xfce-mirror/xfce4-session/commit/f3fcf5ed8aabf1a252be50c37a90b014bb813966, but I am not absolutely certain.

I think the image ships with older version of XFCE4 which still launches ConsoleKit on start.

**Comment by userx-bw** [comment]
11-Nov-2018 05:00  that is how old they are, they need to be updated for sure. I installed xfce one on the ssd I also got in this laptop  after I freed up some space for it, and it just kept hanging up in the middle of boot, so I deleted that one, got lxqt and that one just locks up all of the time while in the WindowManger (openbox). I'm getting really disappointed in Void.  J.S. 

You can prob close this bug issuse as I'll never know if that fix is a  fix or not. again, the iso's really need to be updated, I remember back when they use to be updated more often... cheer!
