### ISSUE TITLE
Package Request[spotify-adblock-linux]

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#14683]
Spotify adblocker for Linux :
https://github.com/abba23/spotify-adblock-linux

**Comment by bobertlo** [comment]
There is no release and we don't make git based packages.

**Comment by bobertlo** [comment]
Also, the single open issue is about their account being deleted after using this...

**Comment by LinArcX** [comment]
1. I ask them to provide a release version.
2. How? I use it without any problem. Do you lose your account after using it?

**Comment by bobertlo** [comment]
2. seems anecdotal. If they make a release you or I could package it.
