### ISSUE TITLE
weechat issues on aarch64-musl

### ISSUE THREAD

**Issue by emacsomancer** [void-linux/void-packages#14725]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
````
MISSING: weechat-2.6_2
Transaction aborted due to unresolved dependencies.
Void 4.19.73_1 aarch64-musl  uptodate rrFFFF
````
* package:  
  *affected package(s) including the version*
 weechat-2.6_1 / weechat-2.6_2
### Expected behavior
weechat-2.6_1: doesn't mysteriously crash
weechat-2.6_2: is able to be installed
### Actual behavior
weechat-2.6_1: mysteriously crashes - see https://github.com/weechat/weechat/issues/1405
weechat-2.6_2: won't install/update, gives error:
````
MISSING: weechat-2.6_2
Transaction aborted due to unresolved dependencies.
````
### Steps to reproduce the behavior
weechat-2.6_1: run weechat, wait for crash - see https://github.com/weechat/weechat/issues/1405
weechat-2.6_2: update via `xbps-install -Su`

**Comment by emacsomancer** [comment]
Ok, now the update to weechat-2.6_2 has become available.

But....it still crashes after a few minutes just like weechat-2.6_1

**Comment by emacsomancer** [comment]
I think it is somehow tied to aarch64-musl. At least, running Guix's weechat-2.6 on the same device with the same weechat config (on top of my Void install) doesn't crash. (I suppose libressl is another possible difference.)

Since I connect from all of my devices to weechat running on a rpi, I don't really end up testing other flavours of Void's weechat - has anyone had issue on x86_64 ?

**Comment by Duncaen** [comment]
> has anyone had issues on x86_64?

No, this should work fine and armv7l-musl works fine too.
Best would be to get a coredump and then look at the backtrace with gdb.

**Comment by emacsomancer** [comment]
> > has anyone had issues on x86_64?
> 
> No, this should work fine and armv7l-musl works fine too.
> Best would be to get a coredump and then look at the backtrace with gdb.

unfortunately, it's unrevealing: https://github.com/weechat/weechat/files/3640015/crash.txt

**Comment by zdtcd** [comment]
Worse, my gdb crashed when tried to print backtrace.

**Comment by xtraeme** [comment]
is this still broken?

**Comment by sgn** [comment]
I'm running weechat 2.7.1 on aarch64-musl.
Idling there from 21 Feb 2020.

weechat 2.7.0 also works fine.

**Comment by xtraeme** [comment]
@sgn thanks for the info. Closing
