### ISSUE TITLE
hugo-0.58.2_1 breaks live preview

### ISSUE THREAD

**Issue by 0x0f0f0f** [void-linux/void-packages#14754]
### System

* xuname:  Void 5.2.17_1 x86_64 GenuineIntel uptodate rrFFF
  
* package:  hugo-0.58.2_1
  
### Expected behavior
Running `hugo serve -D` and opening web page correctly displays post index folders. 
 
### Actual behavior
Preview is broken. Paths like `/posts/` should be correctly previewed but instead hugo returns an empty HTML page with status code 200 on GET request.

### Steps to reproduce the behavior
Clone [hugo repository](https://github.com/gohugoio/hugo)
`cd` into `hugo/examples/blog/`
run `hugo serve -D`
open browser at `localhost:1313/post`

**Comment by kartikynwa** [comment]
Live preview works fine for me. Erroneous result in the example COULD BE from the change in [hugo-0.58.0](https://github.com/gohugoio/hugo/releases/tag/v0.58.0): 

> `home.Pages` now behaves like all the other sections, see #6240. If you want to list all the regular pages, use `.Site.RegularPages`.

**Comment by 0x0f0f0f** [comment]
Closing since issue is related to hugo and not to the void package.
