### ISSUE TITLE
Can't show progress-bar for a qml app when using Imagine theme.

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#14782]
If you run a qt program that uses [imagine theme](https://doc.qt.io/qt-5/qtquickcontrols2-imagine.html), the progressbar-animation can't show to the user.

### System
* xuname:  
```
dmesg: read kernel buffer failed: Operation not permitted
Void 5.2.17_1 x86_64 GenuineIntel uptodate rrDDDDDFFF
```
* package:  
  `qt5-graphicaleffects`

### Expected behavior
Show progress bar of imagine theme properly(Qt).

### Actual behavior
Now, it only shows a black progress-bar.

### Steps to reproduce the behavior
For example, you can install [kindd](https://github.com/void-linux/void-packages/pull/14780) and run it from terminal. It uses internally imagine-theme and progress bar.

Full error:
```
 Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Could not attach Keys property to:  LinArcxDialog_QMLTYPE_57(0x5558aebd4ae0)  is not an Item
file:///usr/lib/qt5/qml/QtQuick/Controls.2/Imagine/ProgressBar.qml:85:52: QML AnimatedImage: Error Reading Animated Image File qrc:/qt-project.org/imports/QtQuick/Controls.2/Imagine/images/progressbar-animation.webp
```

Edit: I tested this package before in arch, and it worked properly there. may be there is a bug in packaging: __qt5-graphicaleffects__.

**Comment by xtraeme** [comment]
Looks like Qt::AA_EnableHighDpiScaling needs to be set somewhere...

**Comment by LinArcX** [comment]
@xtraeme 
It was set:
https://github.com/LinArcX/Kindd/blob/master/modules/core/main.cpp#L6

But it's not the problem. Because before, i saw that message too.
I think the problem related to qt5-graphicaleffects package.

**Comment by Johnnynator** [comment]
Can't reproduce it locally :(

https://i.imgur.com/H5nNdPz.png

**Comment by LinArcX** [comment]
@Johnnynator 
No, go to main page, select a usb device and .iso file and select "Convert/Copy" button. after that you should see a black progress bar like this:
[![Screenshot-from-2019-09-28-16-48-07.png](https://i.postimg.cc/G2gxCh0L/Screenshot-from-2019-09-28-16-48-07.png)](https://postimg.cc/KkLM7bvw)

**Comment by Johnnynator** [comment]
As I said, works on my machine
![fine for me](https://i.imgur.com/hfqVqPL.png)

**Comment by xtraeme** [comment]
Hmmm suspicious minds haha

**Comment by ericonr** [comment]
Couldn't be reproduced and didn't receive more information from reporter.
