### ISSUE TITLE
exfat-dkms Install Fails At Build (As does removal, to clean up files left behind)

### ISSUE THREAD

**Issue by antonio-malcolm** [void-linux/void-packages#14813]
### System

* xuname:  
  Void 5.2.17_1 x86_64 GenuineIntel notuptodate rrFF

* package:  
  exfat-dkms 1.2.8 revision 5

### Expected behavior
Successful build of the exfat kernel module

### Actual behavior
Kernel module build fails, and leaves behind files:

make log:
`
DKMS make.log for exfat-1.2.8 for kernel 5.2.17_1 (x86_64)
Sun 29 Sep 2019 03:46:07 AM PDT
make -C /lib/modules/5.2.17_1/build M=/var/lib/dkms/exfat/1.2.8/build modules
make[1]: Entering directory '/usr/src/kernel-headers-5.2.17_1'
  CC [M]  /var/lib/dkms/exfat/1.2.8/build/exfat_core.o
/var/lib/dkms/exfat/1.2.8/build/exfat_core.c: In function 'fs_error':
/var/lib/dkms/exfat/1.2.8/build/exfat_core.c:1760:64: error: 'MS_RDONLY' undeclared (first use in this function); did you mean 'IS_RDONLY'?
 1760 |  else if ((opts->errors == EXFAT_ERRORS_RO) && !(sb->s_flags & MS_RDONLY)) {
      |                                                                ^~~~~~~~~
      |                                                                IS_RDONLY
/var/lib/dkms/exfat/1.2.8/build/exfat_core.c:1760:64: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:279: /var/lib/dkms/exfat/1.2.8/build/exfat_core.o] Error 1
make[1]: *** [Makefile:1597: _module_/var/lib/dkms/exfat/1.2.8/build] Error 2
make[1]: Leaving directory '/usr/src/kernel-headers-5.2.17_1'
make: *** [Makefile:35: all] Error 2
`

Subsequently, `xbps-remove -Ryv` fails to remove files left behind, under `/var/lib/dkms`.

### Steps to reproduce the behavior
run `xbps-install -Suv exfat-utils`
then...
run `xbps-remove -Ryv exfat-utils`

**Comment by Hoshpak** [comment]
I don't expect this to be fixed and don't have any interest in the exfat drivers myself. I just want to leave this here for people running into the issue:

It currently looks like linux 5.4 will provide an official exfat driver although in the staging directory for now. This could potentially be enabled in our builds. There is a fuse module available from https://github.com/relan/exfat which is packaged as `fuse-exfat` and could serve as an alternative. A more recent version derived from the Samsung code is available at https://github.com/arter97/exfat-linux. This one could potentially be packaged to provide a working kernel module for the 5.2 and 5.3 kernels which are currently left without one. Someone would have to do the packaging though.

**Comment by ahesford** [comment]
Closing because our modern kernels ship with built-in ExFAT support.
