### ISSUE TITLE
CONFLICT: llvm8-8.0.1_1 with llvm9-9.0.0_1 in transaction (matched by llvm9>=0)

### ISSUE THREAD

**Issue by basiliscos** [void-linux/void-packages#14811]
### System

* xuname:  

```
xuname
CONFLICT: llvm8-8.0.1_1 with llvm9-9.0.0_1 in transaction (matched by llvm9>=0)
Transaction aborted due to conflicting packages.
Void 5.2.17_1 x86_64 GenuineIntel uptodate rrrmFFFFF
```

* package:  

`llvm`

### Expected behavior

update packages via `xbps-install -Su`

**Comment by jnbr** [comment]
Please provide the output of `xbps-install -Su --debug --verbose`.

**Comment by basiliscos** [comment]
https://gist.github.com/basiliscos/7ed2dc5ad31337ca3a651e9375079f02

**Comment by jnbr** [comment]
Thanks

**Comment by basiliscos** [comment]
Thank you, seems solved!
