### ISSUE TITLE
Migrate to notabug.org

### ISSUE THREAD

**Issue by mahaer-mahmud** [void-linux/void-packages#14835]
## Why I think we should abandon GitHub and move to NotABug.org
You may feel tempted to use GitHub since it's the most popular website for code hosting... you should think twice, however. GitHub has a couple of issues with itself. The free software alternative ``notabug.org`` gets rid of those issues.

1. GitHub does not allow some countries to use its service  
For example, [look at what they did to Iranian developers](https://medium.com/@d.aliyamini/microsoft-enters-github-banned-iranian-developers-843f7c60a146). GitHub is doing this because the state government is anti-American, and does not fit Microsoft's pro-American agenda. In reality, most Iranian developers are innocent people who would not decline to meet an American. Based on this, it seems GitHub will ban other countries with crazy governments but good people (for example, Indonesia). So if you don't condone developer discrimination, don't develop on GitHub.  
2. GitHub is not free (as in freedom) software  
Since GitHub is not free software, it does not respect your four freedoms. It can mess with you whatever it wants, even if it's harmful to the developer, so as long as it benefits the company.  
3. GitHub may not be secure  
I get it, you're not looking for state-of-the-art encryption here. But since GitHub's owned by the big Microsoft, the big security agencies can judge you based on your activity. And they can treat you unfairly; as far as I know, these agencies aren't required to follow the constitution.

Thankfully, at least one of those reasons made you switch to ``notabug.org``. If you do switch, it would be a big benefit to you, as you are using a service oriented to the hacker and not the corporation.

However, if you don't have the nerve to go to ``notabug.org``, go to ``codeberg.org``, go to a Gitea instance, or set up your own.

Thank you for your time.

**Comment by Anachron** [comment]
We use much more than just issues from github if you havent noticed.

The only real alternative would be gitlab, but it was decided against because its too much work for no gain.

**Comment by mahaer-mahmud** [comment]
> We use much more than just issues from github if you havent noticed.
> 
> The only real alternative would be gitlab, but it was decided against because its too much work for no gain.

What can I use to make the Void maintainers switch to ``notabug.org``?

And why would gaining freedom be too much work?

**Comment by Anachron** [comment]
@mahaer-mahmud well if you create an infrastructure at `notabug.org` which automatically tests builds on all Void supported platforms and returns this build status to the platform into the PR, allow people to login via their github login data and trigger builds for the [Void BuildBot]https://build.voidlinux.org) once the PRs are merged and all that for completely free now and forever, then I guess it would be a start so we can look if we get everything else that we need working too.

**Comment by mahaer-mahmud** [comment]
@Anachron What do you mean by 'platform' and 'PR'?

**Comment by Anachron** [comment]
`Platform` = Architecture + LIBC-Variant. Like `x86_64-glibc` and `aarch64-musl`, for example.
`PR`: Pull Request. (See https://github.com/void-linux/void-packages/pulls)
