### ISSUE TITLE
alacritty: INSTALL fails on aarch64-musl

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#14851]
### System

* xuname:  
  *aarch64-musl* 
* package:  
  *alacritty-terminfo-0.3.3_1*

### Expected behavior
alacritty-terminfo correctly installing and running tic
### Actual behavior
alacritty-terminfo doesn't have a INSTALL file and alacritty ones fails with
```tic: Sorry, -e can't be used without -I or -C``` on aarch64-musl
### Steps to reproduce the behavior
```xbps-install alacritty``` to get the error

**Comment by m3tav3rse** [comment]
Fixed in #16943
