### ISSUE TITLE
Package request: PyGObject

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/void-packages#14968]
Needed for Python 3 support in Xpra 3.

> PyGObject is a Python package which provides bindings for GObject based libraries such as GTK, GStreamer, WebKitGTK, GLib, GIO and many more.

https://pygobject.readthedocs.io/en/latest/

**Comment by Hoshpak** [comment]
Isn't it already packaged as `python3-gobject`?

**Comment by ndowens** [comment]
@leahneukirchen

**Comment by leahneukirchen** [comment]
Indeed, must have overseen it.
