### ISSUE TITLE
Package request: something like build-essential

### ISSUE THREAD

**Issue by mithodin** [void-linux/void-packages#14969]
I'm trying to build coreboot on my void linux installation, but I'm having a lot of trouble hunting down all the software I need because it just suggests to install a meta-package like debian's build-essential, which, as far as I can tell, does not exist on void. Having something like that would make the life of anyone who's trying to compile software so much easier.

**Comment by Hoshpak** [comment]
The package is called `base-devel` in Void.

**Comment by mithodin** [comment]
Oh thank god. I've googled for like half an hour without finding anything.
