### ISSUE TITLE
chromium: crash on every type of page

### ISSUE THREAD

**Issue by svenper** [void-linux/void-packages#14980]
### System

* xuname:  
  `Void 5.2.18_1 x86_64-musl GenuineIntel uptodate hold rrnFFFFFFFFFFF`
* package:  
  `chromium-77.0.3865.90_1`

### Expected behavior

Navigation works as in 76.0.3809.132_1

### Actual behavior

Every type of page crashes immediately. [See log](https://gist.github.com/svenper/308cb10e6f3d3709bea82bf44d04d9c2/raw).

### Steps to reproduce the behavior

Open a new tab page
Go to `chrome://settings/`
Go to `file:///home/`
Go to `https://example.com`

**Comment by prspkt** [comment]
This is also reproducible on my end x86_64-musl with the same `seccomp-bpf failure` log evidenced above.

**Comment by jnbr** [comment]
fixed with eb4dde2b0ae2d66aa2142a1eadf1d267433f68a5
