### ISSUE TITLE
libjbig2dec: breaks mupdf with message "undefined symbol: jbig2_ctx_new"

### ISSUE THREAD

**Issue by hereforthebugs** [void-linux/void-packages#15053]
### System

* xuname:  
  * Void 5.2.18_1 x86_64 GenuineIntel uptodate rFFFF
* package:  
  * libjbig2dec 0.17
  *  mupdf 1.16.1_1

### Issue
After upgrading from libjbig2dec 0.16_1 to libjbig2dec 0.17, mupdf crashes with the message: 'mupdf: symbol lookup error: mupdf: undefined symbol: jbig2_ctx_new'

**Comment by Hoshpak** [comment]
#15034
