### ISSUE TITLE
Package request: android-sdk

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#15108]
Google Android SDK:
https://developer.android.com/studio/releases/sdk-tools.html

**Comment by kirillrdy** [comment]
According to this https://developer.android.com/studio/releases/sdk-tools.html

"SDK Tools package is deprecated and no longer receiving updates. Instead, please use the new command-line tools package."

**Comment by sgn** [comment]
On 2020-10-29 17:38:42-0700, kirillrdy <notifications@github.com> wrote:
> According to this https://developer.android.com/studio/releases/sdk-tools.html
> 
> "SDK Tools package is deprecated and no longer receiving updates. Instead, please use the new command-line tools package."

AFAIU,
They're no long provides prebuilts source for those tools.
Which is irrelevant to us, since we build the package ourselves.

I'll look into update android-tools to 30.0.x since I'll got a new
Android soon.

-- 
Danh
