### ISSUE TITLE
Intellij Idea Community Edition 2019.2.3_1 can't find JDK classes

### ISSUE THREAD

**Issue by obunden** [void-linux/void-packages#15163]
### System

* xuname:  
Void 5.2.18_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFF

* package:  
intellij-idea-community-edition-2019.2.3_1

### Expected behavior
Normal start of the application

### Actual behavior
I get this error message,
JDK Required: JDK classes seem to be not on IDEA classpath.
Please ensure you run the IDE on JDK rather than JRE.

Same problem happens on a clean new user.

### Steps to reproduce the behavior
Run 'idea'

**Comment by Chocimier** [comment]
see https://github.com/void-linux/void-packages/pull/11736#issuecomment-509367711

**Comment by obunden** [comment]
@Chocimier Thanks that fixes it. So this should be filed as an issue for the openjdk package? Couldn't find any issues about it. Kinda strange that this has gone relatively unnoticed, surely other java apps must be affected? I must say that I really love void, but production stuff seems like a better fit for other distros where newer java versions and dotnet are more reliable and available.

Hopefully we will catch up :+1:

**Comment by obunden** [comment]
Using xbps-alternatives -g java -s openjdk also fixes this problem. Tried it on a new installation.

**Comment by ericonr** [comment]
Is this still an issue?

**Comment by Chocimier** [comment]
Closing as fixed.
