### ISSUE TITLE
pulseeffects: remove ConsoleKit2 as dependency?

### ISSUE THREAD

**Issue by b1scu1t** [void-linux/void-packages#15183]
### System

* xuname:  
` Void 5.2.17_1 x86_64 GenuineIntel notuptodate rrrmFFFFF`
* package:  
`pulseeffects-3.2.3_3`

### Expected behavior
Install and use pulseeffects without the ConsoleKit2 dependency.

### Actual behavior
ConsoleKit2 is roped in with the `pulseeffects` package, although `pulseaudio` doesn't need it, and apparently neither does `pulseeffects` according to a Reddit post [here](https://www.reddit.com/r/voidlinux/comments/c954df/pulseeffects_without_consolekit2/).

### Steps to reproduce the behavior
sudo xbps-install -S pulseeffects

To add to this, I had adopted `elogind` as a session manager, given that ConsoleKit2 was being dropped. With ConsoleKit2 being roped in, it automatically starts as a daemon with elogind; I don't think two session managers should run simultaneously.

I've also manually killed the daemon, and `pulseeffects` functions without it.

**Comment by ruegerjr** [comment]
Not knowing what's in pulseeffects, it is possible that it still utilizes consolekit2 without the daemon being activated by runit.  At the risk of breakage, you might try keeping pulseeffects but forcefully removing consolekit2 and see if pulseeffects still works as expected.  If so, consolekit2 could be dropped as a dependency.
`sudo xbps-remove -F ConsoleKit2`

**Comment by b1scu1t** [comment]
Yep, I've tested `pulseeffects-3.2.3_3` with `ConsoleKit2` forcefully removed, today.
It works normally.
I've also launched it in the terminal, besides the warnings for the Delay and Maximizer plugins (which I believe is normal behavior, as I haven't installed the dependencies for those features in particular), it works perfectly.

**Comment by b1scu1t** [comment]
I've tested this with both `mpv` and `firefox-esr`.
