### ISSUE TITLE
Steam doesn't install all packages that are needed on x86_64

### ISSUE THREAD

**Issue by obunden** [void-linux/void-packages#15197]
### System

* xuname:  
  Void 5.2.18_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFFF
* package:  
  steam-1.0.0.61_1

### Expected behavior
Steam starts without errors
### Actual behavior
Steam displays this error message:
Error: You are missing the following 32-bit libraries, and Steam may not run:
libstdc++.so.6
libstdc++.so.6
libstdc++.so.6
libstdc++.so.6
libgcc_s.so.1
libstdc++.so.6
libstdc++.so.6
libgcc_s.so.1
libstdc++.so.6
libgcc_s.so.1
libdrm.so.2
### Steps to reproduce the behavior
Launch 'steam'

### Further information
This can be solved by installing installing libstdc++-32bit (it pulls in libgcc-32bit) and libdrm-32bit from the multlilib repo.

**Comment by obunden** [comment]
I'm new to the build system so I have no clue how this should be handled. Does anyone know why steam is a "64-bit" package? I thought the steam client didn't use 64-bit at all. It feels like it belongs in void-repo-multilib-nonfree.

**Comment by zdtcd** [comment]
The steam in our repo is just a script and a bootstrap tarball that will download real software distribution from Valve.

The bootstrap (32 bit) will then download the correct 64 bit version if your system is x86_64.

steam shouldn't be listed in multilib or i686 only, because it needs to pull xz, curl, etc.. to download and extract the software.

**Comment by obunden** [comment]
I know about the message, I have the requrired libraries installed for my card (proprietary nvidia). It doesn't pull in the other libraries that I mentioned. I tried uninstalling the packages and removing all orphans, and then install everything again but that didn't help.

nvidia-stable-libs-32bit doesn't seem to be a thing anymore, couldn't find it in the repos. Don't think it causes the problem but maybe it should be left out of the message?

**Comment by Hoshpak** [comment]
Indeed, that's horribly outdated and should be removed or updated. Since the nvidia package versions change all the time (we have 340 and 390 now), perhaps it would be best to just tell people to install the 32bit package that matches the nvidia driver version they are already using.

**Comment by xtraeme** [comment]
The steam `INSTALL.msg` file was updated a while ago, this contains uptodate info.
