### ISSUE TITLE
Cargo: FTBFS

### ISSUE THREAD

**Issue by bobertlo** [void-linux/void-packages#15203]
The bug has been fixed that the libc package was held back for, and now that older version breaks dependencies. It builds fine for `x86-64` and `x86_64-musl` with the restriction removed, but I am not going to try to bump the package with everything else going on here, and it's probably not worth rebuilding to fix the build.

@q66 just an FYI on what I found.

**Comment by q66** [comment]
Considering the 0.39 update removes that already, you can just close this
