### ISSUE TITLE
Package Request: spotify-tui

### ISSUE THREAD

**Issue by Jackojc** [void-linux/void-packages#15219]
Fairly recent project but looks quite promising, would be curious to know if it is possible to add. It is made with rust and I believe current releases are only verified to work on Mac if that's an issue.
https://github.com/Rigellute/spotify-tui

**Comment by CameronNemo** [comment]
hi from HN

**Comment by Jackojc** [comment]
what?

**Comment by CameronNemo** [comment]
hmm I assumed, perhaps wrongly, that these requests stemmed from this Hacker News thread. https://news.ycombinator.com/item?id=21179190

**Comment by Jackojc** [comment]
Oh, I came from reddit.
