### ISSUE TITLE
virtualbox-ose-guest on x86_32

### ISSUE THREAD

**Issue by dinama** [void-linux/void-packages#15242]
### System

* xuname:  

voidlinux 32bit on  virtualbox

void 5.2.19_1 i686 GeniueIntel/KVM uptodate 

* package:  

virtualbox-guest & virtualbox-guest-dkms 

### Expected behavior

install virtualbox-guest & virtualbox-guest-dkms  5.2.2 or 6.0.10

### Actual behavior

can't install because . depend version conflict

virtualbox-ose-guest | 5.2.2 
virtualbox-ose-guest-dkms | 6.0.10

**Comment by Hoshpak** [comment]
Indeed, the package needs to be removed from the repository.

**Comment by Hoshpak** [comment]
@void-linux/void-ops virtualbox-ose-* needs to be removed from the i686 repository

**Comment by xtraeme** [comment]
```
[juan@/home/juan/projects/void-linux/void-packages/masterdir-i686 /]$ xbps-query -Rs virtualbox
[-] virtualbox-ose-5.2.2_2            General-purpose full virtualizer for x86 hardware
[-] virtualbox-ose-dkms-6.1.2_1       General-purpose full virtualizer for x86 hardware - kernel module sources for dkms
[-] virtualbox-ose-guest-5.2.2_2      General-purpose full virtualizer for x86 hardware - guest utilities
[-] virtualbox-ose-guest-dkms-6.1.2_1 General-purpose full virtualizer for x86 hardware - guest addition module source for dkms
[-] virtualbox-ose-dbg-5.2.2_2        General-purpose full virtualizer for x86 hardware (debug files)
[-] virtualbox-ose-guest-dbg-5.2.2_2  General-purpose full virtualizer for x86 hardware - guest utilities (debug files)
[juan@/home/juan/projects/void-linux/void-packages/masterdir-i686 /]$
```

The repos are still full of obsolete packages...

**Comment by xtraeme** [comment]
@void-linux/void-ops

**Comment by ericonr** [comment]
This is listed in #23575
