### ISSUE TITLE
Thunar/Xfce4-power-manager/xfce4-notifyd - xfce4-panel no longer optional?

### ISSUE THREAD

**Issue by b1scu1t** [void-linux/void-packages#15288]
### System

* xuname:  
  `Void 4.19.77_1 x86_64 GenuineIntel uptodate rrrmFFFFF`

* package:  
  `Thunar-1.8.9_1`
  `xfce4-notifyd-0.4.4`
  `xfce4-power-manager-1.6.5_2`
  `xfce4-screenshooter-1.9.6_1_2`

### Expected behavior
Can install either one of the aforementioned packages without `xfce4-panel`.

### Actual behavior
As of the recent update to xfce4.14, `xfce4-panel` was no longer an optional dependency; it became a hard dependency for all of the aforementioned packages, despite them being independent the `xfce4-panel`.

### Steps to reproduce the behavior
`sudo xbps-install -S Thunar`

**Comment by Hoshpak** [comment]
This is because the packages link against a shared library in the xfce4-panel package. We should probably split the library into a separate packages so people don't have to install the whole panel as a dependency.

**Comment by Piraty** [comment]
#13979

**Comment by Hoshpak** [comment]
so time to reopen and merge this PR?
