### ISSUE TITLE
mpv: green tilt in the video

### ISSUE THREAD

**Issue by shumvgolove** [void-linux/void-packages#15294]
`linux5.2, musl, system up to date`

Playing any video with `mpv` produces green tilt in the video.

`.config/mpv/mpv.conf`
```
gpu_context=wayland
profile=gpu-hq
scale=ewa_lanczossharp 
cscale=ewa_lanczossharp
```
Commenting out `cscale=ewa_lanczossharp` solves the issue, but everything worked fine until recent updates.

**Comment by obunden** [comment]
I'm just taking a guess here, but this should probably reported upstream somewhere.

Seems like there has been very little changes in mpv and the biggest change in void seems to be that that the package got rebuilt against ffmpeg-4.2.

If your card supports vulkan you could try gpu_context=waylandvk and see if you get the same problem. Don't know if it's relevant but you should probably post your video card / drivers, it might be useful.

Also check and see which video output is used in mpv, I imagine it is 'gpu' but have a look. This message from the mpv manual might also shed some light on the issue:

```
Quality reduction with hardware decoding

In theory, hardware decoding does not reduce video
quality (at least for the codecs h264 and HEVC).
However, due to restrictions in video output APIs, as
well as bugs in the actual hardware decoders, there
can be some loss, or even blatantly incorrect results.

In some cases, RGB conversion is forced, which means
the RGB conversion is performed by the hardware
decoding API, instead of the shaders used by --vo=gpu.
This means certain colorspaces may not display
correctly, and certain filtering (such as debanding)
cannot be applied in an ideal way. This will also
usually force the use of low quality chroma scalers
instead of the one specified by --cscale. In other
cases, hardware decoding can also reduce the bit depth
of the decoded image, which can introduce banding or
precision loss for 10-bit files.
```

**Comment by shumvgolove** [comment]
I've got RX590 and `amdgpu` driver loaded. Setting `gpu_context=waylandvk` makes no difference. And yeah, video output is `gpu`.

**Comment by obunden** [comment]
Ok, probably some quirk with the hardware/driver. I don't have wayland/musl and I'm on nvidia proprietary drivers so can't really test it further. I read that --vf=format=rgba might fix colors in mpv, other than that I don't know what more can be done. Hope you find a solution that works for you.

**Comment by paoloschi** [comment]
well, probably just a repeated typo here but I get an error in mpv log if I set `gpu_context=`: the correct option name is `gpu-context=` whit a _hyphen_  instead of a _underscore_

```
Error parsing option gpu_context (option not found)
/home/user/.config/mpv/mpv.conf:24: setting option gpu_context='auto' failed.

```

**Comment by shumvgolove** [comment]
Yeah, repeated typo, sorry.

**Comment by obunden** [comment]
Yeah you are absolutely right. Did --vf=format=rgba do anything @shumvgolove?

**Comment by shumvgolove** [comment]
Oh! `--vf=format=rgba` indeed fixes the issue and mpv outputs this:
```
[autoconvert] Converting yuv420p -> rgba
AO: [alsa] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 rgba
```
More on topic: [mpv issue](https://github.com/mpv-player/mpv/issues/4340)

**Comment by shumvgolove** [comment]
I think we can close this now as it not problem with Void.
