### ISSUE TITLE
Linux 4.17 includes SPECK

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#1538]
Read about it here: [NSA’s Encryption Algorithm in Linux Kernel is Creating Unease in the Community](https://itsfoss.com/nsas-encryption-algorithm-in-linux-kernel-is-creating-unease-in-the-community/)

### System

* xuname:  Void 4.17.12_1 x86_64 GenuineIntel uptodate rrrmFFFFF
* package:  linux4.17

### Description

Starting with the Linux Kernel 4.17 the questionable SPECK algorithm (developed by the NSA) was pushed by Google to find it's place into the latest release and will be extended in the linux 4.18 release.

Just a heads up for people who don't know! You can blacklist this kernel module with:

> If it doesn’t exist already, create /etc/modprobe.d/blacklist.conf file and add the following lines to it:
> ``
> blacklist CONFIG_CRYPTO_SPECK
> ``

**Comment by Gottox** [comment]
```
~ grep SPECK /boot/config-*     
/boot/config-4.17.12_1:# CONFIG_CRYPTO_SPECK is not set
/boot/config-4.17.4_1:# CONFIG_CRYPTO_SPECK is not set
/boot/config-4.17.5_1:# CONFIG_CRYPTO_SPECK is not set
/boot/config-4.17.6_1:# CONFIG_CRYPTO_SPECK is not set
/boot/config-4.17.9_1:# CONFIG_CRYPTO_SPECK is not set
/boot/config-4.18.0rc7_1:# CONFIG_CRYPTO_SPECK is not set
```
