### ISSUE TITLE
Ardour: installing package doesn't create .desktop file

### ISSUE THREAD

**Issue by b1scu1t** [void-linux/void-packages#15426]
### System

* xuname:  
  `Void 4.19.77_1 x86_64 GenuineIntel notuptodate rrrmFFFFF`

* package:  
  `ardour-5.12_3`

### Expected behavior
Installing the `ardour` package would include a .desktop file for application menus. (Given that it is a QT GUI).

### Actual behavior
The .desktop file isn't included or installed.

### Steps to reproduce the behavior
`sudo xbps-install -S ardour`

**Comment by obunden** [comment]
It doesn't matter this time but it's probably good practice to update your system before posting an issue. That way the devs know that you are not on a old version. I think you are right it seems like the icon needs to be manually installed.

See https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ardour-git for reference

**Comment by b1scu1t** [comment]
It seems like `xuname` must be run as root, to return accurate results.
`Void 4.19.79_1 x86_64 GenuineIntel uptodate rrrmFFFFF`
I've seen the PKGBUILD. 
Arch seems to 'manually' add .desktop files to their packages. 
Or make a script with `gendesk`, to generate a .desktop file during the `makepkg() `phase.

**Comment by tibequadorian** [comment]
@sgn this can now also be closed

**Comment by sgn** [comment]
Thanks
