### ISSUE TITLE
Package request: libredwg

### ISSUE THREAD

**Issue by luzpaz** [void-linux/void-packages#15489]
> GNU LibreDWG is a free C library to handle DWG files. It aims to be a free replacement for the OpenDWG libraries. DWG is the native file format of AutoCAD. GNU LibreDWG is based on LibDWG, originally written by Felipe Castro.

Current version: https://github.com/LibreDWG/libredwg/releases/tag/0.9  
Changelog: https://raw.githubusercontent.com/LibreDWG/libredwg/master/NEWS  
License: GPLv3

**Comment by ndowens** [comment]
I'll take a look at this tomorrow

**Comment by abenson** [comment]
I started working on it [here](https://github.com/abenson/void-packages/commit/c9a03f1b3b1ed3b9c6ffeb55b6c26bf5e32324a9)

**Comment by ndowens** [comment]
This can be closed: @810f312
