### ISSUE TITLE
Nautilus requires /etc/ld.so.cache to generate thumbnails

### ISSUE THREAD

**Issue by Oreo639** [void-linux/void-packages#15482]
### System

* xuname:  Void 5.2.21_1 x86_64-musl GenuineIntel uptodate rF
  *output of ``xuname`` (part of xtools)*
* package:  nautilus-3.34.0_1
  *affected package(s) including the version*

### Expected behavior
Generates thumbnails with all the proper thumbnailers installed just like any other file manager.

### Actual behavior
Thumbnail generation fails.

### Steps to reproduce the behavior
Fresh install of voidlinux.
Install nautilus.

According to [this issue](https://github.com/clearlinux/distribution/issues/701)
It can be fixed by creating `/etc/ld.so.cache`, which did fix it for me. This file should probably be automatically generated by the package in the post install script.

**Comment by charbelnicolas** [comment]
I'm having this problem even though the ld.so.cache folder already exists...

**Comment by xtraeme** [comment]
Omg

**Comment by Oreo639** [comment]
Err, not folder. It should be a file, my bad.
I believe you can fix it by running `sudo ldconfig`.

**Comment by charbelnicolas** [comment]
My bad, I was able to solve this by increasing the 10 MB file cap for thumbnail generation to something else.

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/81660495-8ce4e500-945a-11ea-8f7f-ddfc069fdfa5.png)

Thumbnail is not displayed in google drive mounted folder in nautilus. However they are displayed in **photos** folder.

**Comment by Oreo639** [comment]
Preferences > Search & Preview > Thumbnails

**Comment by Oreo639** [comment]
I'm closing this as I haven't run into this on a different fresh install and I am not sure if it is still a problem.

**Comment by nazar2sfive** [comment]
@Oreo639 you were right . Needed to change Preferences > Search & Preview > Thumbnails > 
**Show all files.**
![image](https://user-images.githubusercontent.com/12841320/81763037-f4984000-94ed-11ea-9d15-7a41f897ed12.png)
