### ISSUE TITLE
gcc-multilib does not build 32-bit binaries

### ISSUE THREAD

**Issue by foxlet** [void-linux/void-packages#15513]
### System

* xuname:  Void 5.2.21_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFF
* package:  gcc-multilib

### Expected behavior
Program compiles properly.

### Actual behavior
```
checking whether gcc -m32 works... no

configure: error: Cannot build a 32-bit program, you need to install 32-bit development libraries.
```
### Steps to reproduce the behavior
Compile any application with the `-m32` flag using GCC.

**Comment by Hoshpak** [comment]
caused by #12990

**Comment by xtraeme** [comment]
Fixed
