### ISSUE TITLE
Thunar is outdated.

### ISSUE THREAD

**Issue by h0ttentot** [void-linux/void-packages#1552]
Thunar is already on 1.8.1 (June 2018), but Void has the 1.6.15 on the repositores.

It's weird because i can find the 1.8.1 version on the https://voidlinux.org/packages/ search (for x86_64), but when i update my xbps, it's not there yet. The 32bit and devel packages are updated, but the main 64 bit is not.

**Comment by Hoshpak** [comment]
```
=> Registering xfdesktop-4.12.4_2.x86_64.xbps into /host/binpkgs ...
index: added `Thunar-1.8.1_1' (x86_64).```

https://build.voidlinux.eu/builders/x86_64_builder/builds/10680/steps/shell_3/logs/stdio
