### ISSUE TITLE
[FTBFS] apache-ant: disfile unavaible

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#15580]
```
=> apache-ant-1.10.5_1: fetching distfile 'apache-ant-1.10.5-src.tar.xz'...
http://mirror.dkd.de/apache/ant/source/apache-ant-1.10.5-src.tar.xz: Not Found
```

**Comment by ndowens** [comment]
Hmm it is fetching for me:
=> apache-ant-1.10.7_1: fetching distfile 'apache-ant-1.10.7-src.tar.xz'...
apache-ant-1.10.7-src.tar.xz: [4171KB 0%] 195MB/s ETA: 00m00s
apache-ant-1.10.7-src.tar.xz: [4171KB 2%] 234KB/s ETA: 00m40s
apache-ant-1.10.7-src.tar.xz: [4171KB 12%] 356KB/s ETA: 00m14s
apache-ant-1.10.7-src.tar.xz: [4171KB 18%] 307KB/s ETA: 00m13s
apache-ant-1.10.7-src.tar.xz: [4171KB 23%] 284KB/s ETA: 00m12s
apache-ant-1.10.7-src.tar.xz: [4171KB 28%] 271KB/s ETA: 00m12s
apache-ant-1.10.7-src.tar.xz: [4171KB 31%] 245KB/s ETA: 00m12s
apache-ant-1.10.7-src.tar.xz: [4171KB 34%] 222KB/s ETA: 00m13s
apache-ant-1.10.7-src.tar.xz: [4171KB 36%] 205KB/s ETA: 00m14s
apache-ant-1.10.7-src.tar.xz: [4171KB 38%] 190KB/s ETA: 00m14s
apache-ant-1.10.7-src.tar.xz: [4171KB 39%] 177KB/s ETA: 00m15s
apache-ant-1.10.7-src.tar.xz: [4171KB 41%] 166KB/s ETA: 00m15s
apache-ant-1.10.7-src.tar.xz: [4171KB 42%] 157KB/s ETA: 00m15s
apache-ant-1.10.7-src.tar.xz: [4171KB 43%] 142KB/s ETA: 00m16s
apache-ant-1.10.7-src.tar.xz: [4171KB 44%] 135KB/s ETA: 00m17s
apache-ant-1.10.7-src.tar.xz: [4171KB 44%] 130KB/s ETA: 00m18s
apache-ant-1.10.7-src.tar.xz: [4171KB 46%] 125KB/s ETA: 00m18s

**Comment by Johnnynator** [comment]
I just forgot to close this one. I fixed it with a965ea620e04cef6f2511fb22ac6fca217d93ef3
