### ISSUE TITLE
Codeblocks missing contrib plugins

### ISSUE THREAD

**Issue by pcallycat** [void-linux/void-packages#1561]
### System

* xuname:  
  **Void 4.17.12_1 x86_64 GenuineIntel uptodate rFF
* package:  
  **codeblocks-17.12

Codeblocks package is built without the --with-contrib-plugins option enabled, resulting in wxsmith as well as other plugins not being included in the package.  Not sure if this is intentional or not, but adding the option to the template could be a convenience for some.

**Comment by pcallycat** [comment]
Here's a patch to add the requisite dependencies, and enable the building of all plugins.

[codeblocks.patch.txt](https://github.com/void-linux/void-packages/files/2271063/codeblocks.patch.txt)

**Comment by youngjinpark20** [comment]
will make the edits necessary

**Comment by youngjinpark20** [comment]
https://github.com/void-linux/void-packages/pull/6725
