### ISSUE TITLE
Use Universal Ctags instead of Exhuberant Ctags

### ISSUE THREAD

**Issue by stacyharper** [void-linux/void-packages#15689]
Hello there,

Archlinux repositories uses by default universal ctags as the ctags package.

Is this a possibility for the void linux package repository?

I can take time to do the PR if you feels it's okay :)

BB !

**Comment by jnbr** [comment]
Packaging universal ctags would require a released version. It looks like there is none.

**Comment by Eluminae** [comment]
Arf, good point. Arch use a specific commit but this seems not a convenient way...

**Comment by Eluminae** [comment]
Okay, it seems there is no plan for releases.

I'd like to package universal ctags using commit references.
How do you feels about it ? If it seems okay, should we replace ctags or create another universal-ctags package ?

**Comment by Hoshpak** [comment]
We generally do not accept packages using git commits instead of released versions into the repository.
