### ISSUE TITLE
Switching C++ Compilers with xbps-alternatives

### ISSUE THREAD

**Issue by schmidh** [void-linux/void-packages#15714]
### System

* c++ --version:  
  *c++ (GCC) 9.2.0*
*Copyright (C) 2019 Free Software Foundation, Inc.*
*This is free software; see the source for copying conditions.  There is NO*
*warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.*
* gcc-9.2.0_1:  
  *clang-9.0.0_2*

### Expected behavior
I would love to set the default C++ compiler to clang++ using xbps-alternatives.
### Actual behavior
Trying to set alternative C++ compilers is not possible as there is no alternative group for c++.
/usr/bin/c++ is not a link and actually a regular file being part of the gcc package. There is an alternative group for cc. Many build tools like e.g. CMake use cc and c++ to compile source code.

**Comment by jnbr** [comment]
In retrospect, the cc alternative group created more problems then it solved.
I don't think we should repeat this for c++ (even though the impact might be smaller).
Most build systems use the `CXX` environment variable, which, in my opinion, makes more sense then changing `/usr/bin/c++`.

**Comment by schmidh** [comment]
Thanks for your reply! Ok.
