### ISSUE TITLE
Can't update system due to missing libevent>=2.1.11_1

### ISSUE THREAD

**Issue by PrinceKael** [void-linux/void-packages#15726]
As of today I can't seem to update my system at all. I keep getting the error below, I haven't installed anything new and I update daily.

It looks like something is requiring libevent-2.1.11 while the repo only has 2.1.10_2. It could be a new Firefox update because I saw someone on Reddit have a similar issue.

### System
Kernel: 5.2.21_1
Arch: x86_64 glibc
Repos: multilib, multilib-nonfree, nonfree
### Expected behavior
Update the system with `sudo xbps-install -Su`

### Actual behavior
```
MISSING: libevent>=2.1.11_1
Transaction aborted due to unresolved dependencies.
```

**Comment by Hoshpak** [comment]
There's a huge rebuild still ongoing, status at https://build.voidlinux.org/waterfall . Please wait until all builders are finished (green status) before updating again.
