### ISSUE TITLE
libevent firefox dependency

### ISSUE THREAD

**Issue by capnhawkbill** [void-linux/void-packages#15735]
### System

* xuname:  
MISSING: libevent>=2.1.11_1 
Transaction aborted due to unresolved dependencies. 
Void 5.3.7_1 x86_64 AuthenticAMD uptodate rrFF 

* package:  
  *affected package(s) including the version*
firefox 69

Firefox has a version of libevent as dependecy which isn't in the repo.
Firefox wants libevent >= 2.1.11_1 but the newest version in the repo is 2.1.10

**Comment by Hoshpak** [comment]
There's a huge rebuild still ongoing, status at https://build.voidlinux.org/waterfall . Please wait until all builders are finished (green status) before updating again.
