### ISSUE TITLE
xbps-install -Su fails. Some xtools fail too.

### ISSUE THREAD

**Issue by Henry-Wilson** [void-linux/void-packages#15744]
### System

* xuname:  
```
MISSING: libevent>=2.1.11_1
Transaction aborted due to unresolved dependencies.
dmesg: read kernel buffer failed: Operation not permitted
Void 5.2.21_1 x86_64 GenuineIntel uptodate rFFF

```
* package:  
`XBPS: 0.56 API: 20190621 GIT: UNSET`

### Expected behavior
XBPS tools should function, update my packages, etc.

### Actual behavior
running xbps-install -Su (or xi -u) prints: 
```
[*] Updating `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
MISSING: libevent>=2.1.11_1
Transaction aborted due to unresolved dependencies.
```

### Steps to reproduce the behavior
Run `xbps-install -Su`

**Comment by Hoshpak** [comment]
There's a huge rebuild for libevent still ongoing, status at https://build.voidlinux.org/waterfall . Please wait until all builders are finished (green status) before updating again.

**Comment by Henry-Wilson** [comment]
Ah, thanks for letting me know! Sorry to inflate your issues page.

**Comment by Hoshpak** [comment]
Don't worry about it. I probably should have put up an issue instead of just closing the ones that arrived. I did so now in #15745 and hope people arriving on the issues page now will find it.

**Comment by Henry-Wilson** [comment]
Yeah I did search open issues just to make sure. Didn't think to search closed.
