### ISSUE TITLE
installing matplotlib could fail

### ISSUE THREAD

**Issue by scaramacai** [void-linux/void-packages#15751]
xbps-install python-matplotlib python3-matplotlib fails with
transaction error
I succeeded in installing packages by issuing separate commands (python3 first, but did not try the reverse):
xbps-install python3-matplotlib
xbps-install python-matplotlib

### System

* xuname:  
  *Void 5.2.21_1 x86_64-musl GenuineIntel uptodate rF*
* package:  
  *python-matplotlib-2.2.4_2*
 *python3-matplotlib-3.1.1_1*

### Expected behavior
xbps-install python-matplotlib python3-matplotlib should work correctly
### Actual behavior
It fails with errors: it seems that some file already installed by python-matplotlib are
also in python3-matplotlib
### Steps to reproduce the behavior
xbps-install python-matplotlib python3-matplotlib

**Comment by st3r4g** [comment]
It tries to install both versions of the `matplotlib-data` subpackage, which contains many files that are the same. Apparently `replaces="python-matplotlib-data<3.0.0"` is not enough when installing as part of the same transaction.

**Comment by scaramacai** [comment]
Today the same (or similar) problem reappeared. 
xbps-install -Suv upgraded the python3 version of matplotlib and removed python-matplotlib-data.
After that I was able to re-install by using xbps-install python-matplotlib-data, but this is  very annoying.

**Comment by st3r4g** [comment]
Did the python2 version of matplotlib stop working properly when `python-matplotlib-data` got removed?

**Comment by scaramacai** [comment]
[root@xxxxxx ~]# xbps-remove python-matplotlib-data
python-matplotlib-data-2.2.4_2 (remove) breaks installed pkg `python-matplotlib-2.2.4_2'
Transaction aborted due to unresolved dependencies.

**Comment by ericonr** [comment]
python-matplotlib is no longer a package
