### ISSUE TITLE
Package Request: SourceHut

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#15784]
Homepage: https://sourcehut.org/

> This suite of open source tools is the software development platform you've been waiting for. We've taken the wisdom of the most successful open-source communities and turned it into a platform of efficient engineering tools.
> 
>     Composable Unix-style mini-services
>     Powerful APIs and webhooks
>     Secure, reliable, and safe
>     Absolutely no tracking or advertising
>     All features work without JavaScript
>     100% free and open source software

Source: https://git.sr.ht/~sircmpwn/?search=sr.ht
License: [GNU AFFERO GENERAL PUBLIC LICENSE](https://git.sr.ht/~sircmpwn/git.sr.ht/tree/master/LICENSE)

**Comment by humaidq** [comment]
Would like to note that there are Debian builds, may be helpful to see how it is packaged.
https://git.sr.ht/~dlax/sr.ht-debbuilds

**Comment by anjandev** [comment]
I will try to package this.

**Comment by Anachron** [comment]
@anjandev have you reached a working package yet?
