### ISSUE TITLE
lksctp-tools does not install header files

### ISSUE THREAD

**Issue by schmidh** [void-linux/void-packages#15817]
### System

* xuname:  
  *Void 5.2.21_1 x86_64 AuthenticAMD notuptodate rrFFF*
* package:  
  *lksctp-tools 1.0.18*

### Expected behavior
Should install **sctp.h** in /usr/include/netinet
### Actual behavior
Installs **sctp.h.in** in /usr/include/netinet
### Steps to reproduce the behavior
sudo xbps-install lksctp-tools

**Comment by Johnnynator** [comment]
We do have split files only needed for development split into `-devel` packages. But `lksctp-tools-devel` names the header wrong (`.in` suffix) https://github.com/sctp/lksctp-tools/issues/27
