### ISSUE TITLE
Emacs-GTK freezes system

### ISSUE THREAD

**Issue by Spowmtom** [void-linux/void-packages#15911]
### System

* xuname:  
  Void 5.3.7_1 x86_64 GenuineIntel uptodate rFF
* package:  
  emacs-gtk2-26.3_1
  emacs-gtk3-26.3_1

### Expected behavior
When launching Emacs GTK with the command `emacs`, I expect the program to open in a new window and to work like Emacs should. 

### Actual behavior
When launching Emacs GTK with the command `emacs`, it freezes up my whole X session. i am unable to start, pause, resume, kill or even use anything. I can move my mouse though, but I've heard that some people can't. I can't kill my window manager (i3) or startx from a new TTY, I need 
to kill emacs from a new TTY. 
Emacs does work in terminal mode with `emacs -nw`.

### Steps to reproduce the behavior
1. Get my exact version of Void Linux
2. Install emacs-gtk2-26.3_1 or emacs-gtk3-26.3_1 with the XBPS package manager
3. Launch Emacs

Thank you for your time and hard work. ❤️

Edit: I am using i3wm

**Comment by Hoshpak** [comment]
I can't reproduce this with LxQT and openbox so it sounds like it is either an issue specific to the window manager or possibly arises with a specific graphics driver. Could you please test with another WM and specify which GPU and graphics driver you are using?

**Comment by leahneukirchen** [comment]
Use `dbus-launch emacs`.

**Comment by Spowmtom** [comment]
> Use `dbus-launch emacs`.

It works! Emacs-gtk3 works flawlessly, now!

**Comment by leahneukirchen** [comment]
I think this is an upstream bug.

**Comment by gspe** [comment]
This problem happened to me too.
But it was a new clean install of void Linux I've discovered that problem happens just after I've installed Thumar file manager.
Before Thunar I can just run emacs and it start immediately, after installing Thunar the whole system hung.

**Comment by gspe** [comment]
> Use `dbus-launch emacs`.

I've found that the problem is that emacs-gtk require dbus and if you use a wm instead of dm you should launch your wm of choice with `dbus-launch wm` like `dbus-launch i3` or  `dbus-launch awesome` etc. in this way all other apps works like expected like Thunar or Pacmfm etc.

**Comment by xtraeme** [comment]
So that the issue is due to dubs-launch being in PATH?

**Comment by gspe** [comment]
no it's just a configuration error when someone use a window manager instead of desktop environment.
I'm using awesome wm and I've solved all my problem just changing `awesome.desktop` to

```
[Desktop Entry]
Name=awesome dbus
Comment=Highly configurable framework window manager (dbus)
Exec=dbus-launch awesome
Type=Application
```

**Comment by xtraeme** [comment]
This is weird anyway. The emacs guys should take a look at this issue and fix it. It's really weird.

**Comment by ericonr** [comment]
https://docs.voidlinux.org/config/session-management.html#d-bus tries to cover dbus stuff. Do we need more docs about it?

**Comment by gspe** [comment]
Correct configuration of D-Bus is not an easy task, information are not very clear and in some case in contradiction this is true in every distribution not only in void, for example look at this long mail from debian mailing list https://lists.debian.org/debian-devel/2016/08/msg00554.html

In my opinion Void D-Bus documentation doesn't provide enough information about how an user have to correctly start an user session bus.
I've taken inspiration from kde, https://github.com/KDE/plasma-workspace/blob/af44f2cc79fb816e31ea125141e75abb66320602/startkde/plasma-dbus-run-session-if-needed, and now I'm starting my sway with a wrapper script, `/usr/bin/sway-run.sh` with this content:

 ```
#!/bin/sh

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# D-Bus
# If the session bus is not available it is spawned and wrapper round our program
# Otherwise we spawn our program directly
drs=
if [ -z "${DBUS_SESSION_BUS_ADDRESS}" ]
then
    drs=dbus-run-session
fi

# Environment
# Imports sway desktop enviroments
set -a
. /etc/sway/env
set +a

exec ${drs} sway "$@"
 ```

So having some examples on how to start a dbus user session will be very nice.

Another idea would be to have some sane default configuration for window manager in addiction to the standard one, for example add the sway wrapper script so a medium user can easily start a sway session but advanced user can start sway session as he likes.

**Comment by ericonr** [comment]
For general interest, this ties in with #28036

**Comment by ericonr** [comment]
Does the freeze still happen, though? Cause otherwise this should be closed and new issues opened (or discussion moved to #28036)

**Comment by gspe** [comment]
I think that can be closed.
Since I started to launch window manager with `dbus-run-session` everything works fine.

**Comment by ericonr** [comment]
If it still freezes the whole system without a running dbus session, that is 100% a bug.

**Comment by ericonr** [comment]
FWIW, I couldn't reproduce it myself.

**Comment by gspe** [comment]
I've quickly tested without start dbus session in advance with wayland based wm, sway and hikari, and emacs gtk3 is launched correctly.
