### ISSUE TITLE
libreoffice metapackage should not include langpacks

### ISSUE THREAD

**Issue by VoidDuck** [void-linux/void-packages#15957]
The libreoffice metapackage comes with an arbitrary selection of langpacks. Why? Just like it is with firefox, most users will know they have to install their corresponding langpack and not like having useless ones installed.

### System
* xuname:  
  *Void 5.3.7_1 x86_64 GenuineIntel uptodate rrFF*
* package:  
  *libreoffice-6.2.5.2_2*

**Comment by Johnnynator** [comment]
> Why?

LibreOffice used not to be split, it was only split quite recently in https://github.com/void-linux/void-packages/commit/49df276324fb6359614a83cde6f6e3995ee8e65f and the default lnaguage deps were sed to assure that it won't break any existing setups and would require no manual intervention.
