### ISSUE TITLE
realtek firmware loading failure

### ISSUE THREAD

**Issue by vikigenius** [void-linux/void-packages#16046]
### System

* xuname:  
  ``Void 5.3.8_1 x86_64 AuthenticAMD notuptodate rrFFFF``
* package: 
  ``wifi-firmware-1.3.3``

### Expected behavior
The system should load the correct firmware

### Actual behavior
After booting I note the following warnings in dmesg.log:

```
[    2.908424] rtl8821ae 0000:21:00.0: enabling device (0000 -> 0003)
[    2.924343] rtl8821ae: Using firmware rtlwifi/rtl8812aefw.bin
[    2.924349] rtl8821ae: Using firmware rtlwifi/rtl8812aefw_wowlan.bin
[    2.924467] rtl8821ae 0000:21:00.0: Direct firmware load for rtlwifi/rtl8812aefw_wowlan.bin failed with error -2
[    2.924508] rtl8821ae 0000:21:00.0: Direct firmware load for rtlwifi/rtl8812aefw.bin failed with error -2
[    2.924648] rtlwifi: Loading alternative firmware rtlwifi/rtl8821aefw.bin
[    2.924654] rtlwifi: Loading alternative firmware rtlwifi/rtl8821aefw.bin
[    2.926082] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[    2.926403] rtlwifi: rtlwifi: wireless switch is on
```

My wifi is working perfectly fine, but the problem is some of these error messages are overflowing to the boot screen when i try to login:

``rtl8821ae: Polling FW ready fail!! REG_MCUFWDL:0x00070706``
This message prints 3-4 times and keeps interrupting me when I login.

How can I stop stop these warnings or at least try to prevent them from overflowing to the boot screen?

**Comment by ericonr** [comment]
Is this issue still happening?

You might be able to boot with `quiet` in the kernel command line to avoid these messages...

**Comment by vikigenius** [comment]
Can't reproduce this anymore, closing. Could have been an update, could be that I got a new laptop.
