### ISSUE TITLE
flatpak-builder: missing deps?

### ISSUE THREAD

**Issue by StreetStrider** [void-linux/void-packages#16053]
It seemes that `flatpak-builder` misses deps:
`elfutils`, `patch`.

I've tried to use flatpak-builder. It's hard to distinguish between errors related to build process and to package itself, but it seemes, that this deps are inherent to any build process with flatpak. Threads on the internet confirms that in other systems flatpak depends on them.

### System
* xuname: Void 5.2.21_1 x86_64 GenuineIntel notuptodate rrFF
* package:  flatpak-builder-1.0.9_1

### Steps to reproduce the behavior
Build with `flatpak-builder` which involves anything more complex than building an empty app and involves patches.

**Comment by kawaiiamber** [comment]
> Threads on the internet confirms that in other systems flatpak 
Where?

**Comment by StreetStrider** [comment]
If you google something like `flatpak-builder elfutils` you see them. Some of them: https://github.com/flatpak/flatpak-builder/issues/92, https://github.com/flatpak/flatpak-builder/issues/261, https://gitlab.gnome.org/GNOME/polari/-/issues/34.

https://archlinux.org/packages/extra/x86_64/flatpak-builder/

**Comment by kawaiiamber** [comment]
I don't use flatpak; if you think there are missing dependencies, I'd go ahead and make a PR to add them to the template.

**Comment by StreetStrider** [comment]
I don't know flatpak well either. I just noticed that the only time I've tried to use it there was an issues, so I think that may be worth mentioning in tracker.

**Comment by thegarlynch** [comment]
Please make the PR, it happen to me also

**Comment by kawaiiamber** [comment]
> Please make the PR, it happen to me also

Is this still an issue?
