### ISSUE TITLE
./xbps-src -m emptymaster -H emptyhost bootstrap failed

### ISSUE THREAD

**Issue by sgn** [void-linux/void-packages#16097]
bootstrap failed because `xbps-src` doesn't build `libgo` but the generated gcc package depends on libgo
```
=> ERROR: pkg-config-0.29.2_2: failed to install 'gcc-9.2.0_1' dependency! (error 19)
MISSING: libgo>=9.1.0_1
```

**Comment by ametisf** [comment]
right now gcc-9.2.0_3 fails to build (configure) with

`configure: error: GNAT is required to build ada`

**Comment by q66** [comment]
this was fixed in https://github.com/void-linux/void-packages/commit/5f43c8c00d20b8e2124fce292e8a241b6ee646cd
