### ISSUE TITLE
Package update request: couchdb

### ISSUE THREAD

**Issue by revington** [void-linux/void-packages#1610]
[https://couchdb.apache.org/](https://couchdb.apache.org/)

Couchdb team no longer support 1.x. Please upgrade to 2.x branch.

**Comment by arete** [comment]
Hi, i try to update couchdb at time of release 2.0.x.
The problem is failure for cross compile.
I now for try for 2.20.

**Comment by revington** [comment]
@arete thank you very much. Just let me know if there is something I can help with.

**Comment by arete** [comment]
@revington hi, this is the branch for couchdb 2.2.0. you
can clone, build and tst localy.
Is work fine for x64, try to fix for cross compile.

**Comment by revington** [comment]
Hi @arete, do you mean this branch https://github.com/arete/void-packages/tree/couchdb2.2.0 ?

**Comment by arete** [comment]
yes , is correect, my bad missing link!

**Comment by revington** [comment]
Hi @arete , you need to update your branch with the changes made yesterday to bzip2. At the moment it does not start in my computer.

**Comment by revington** [comment]
hi @arete can you merge your changes? the package works great for me

**Comment by arete** [comment]
,
isbuild fine for x86_64, but fails for  cross build.
try to fix the cross build and createull request.
regards

**Comment by maxice8** [comment]
Sadly couchdb depends on an old version of erlang, there isn't much we can do besides wait
