### ISSUE TITLE
Ruby-devel mkmf missing on some distros

### ISSUE THREAD

**Issue by Eluminae** [void-linux/void-packages#16104]
Hello there.

I'm working on https://github.com/void-linux/void-packages/pull/15889 and I'm stuck on this.

Some distros can't compile ruby-jaro_winkler. The ruby-devel dependency seems to be enough for some distros but not for others.

What am I missing ?

It seems the mkmf lib is provided by ruby-devel.

```
$ sudo xbps-query -f ruby-devel | grep mkmf
/usr/lib/ruby/2.6.0/mkmf.rb
```

**Comment by Duncaen** [comment]
It looks like its using the hosts ruby when cross compiling.
If this is correct and should be used you should add `ruby-devel` to `hostmakedepends` and not `makedepends`.

**Comment by Eluminae** [comment]
It seems to work ! Ty !
