### ISSUE TITLE
neomutt problem with 20191102 version

### ISSUE THREAD

**Issue by rapha8l** [void-linux/void-packages#16100]
### System

* xuname:  
Void 5.3.8_2 x86_64 GenuineIntel uptodate rrrmFFFFF

* package:  
neomutt 20191102

Hi, since last update, I get a "realloc(): invalid next size" when launching neomutt that crashes instantly neomutt.
I can't even get a debug trace
This config was working perfectly before upgrade, and mutt is fine with the same config

Thanks

**Comment by rapha8l** [comment]
seems like this is causing the crash : 

mailboxes ! + `\                                                                                                                                                                                       
for file in ~/Maildir/.*; do \                                                                                                                                                                         
     box=$(basename "$file"); \                                                                                                                                                                        
     if [ ! "$box" = '.' -a ! "$box" = '..' -a ! "$box" = '.customflags' \                                                                                                                             
      -a ! "$box" = '.subscriptions' ]; then \                                                                                                                                                         
      echo -n "\"+$box\" "; \                                                                                                                                                                          
      fi; \                                                                                                                                                                                            
done`

**Comment by flatcap** [comment]
Fixed in neomutt/neomutt@b486e37c1
There should be a new release at the end of the week.

**Comment by rapha8l** [comment]
Thanks Flatcap !
