### ISSUE TITLE
Package Request: git-filter-repo

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/void-packages#16117]
> git filter-repo is a versatile tool for rewriting history, which includes capabilities I have not found anywhere else. It roughly falls into the same space of tool as git filter-branch but without the capitulation-inducing poor performance, with far more capabilities, and with a design that scales usability-wise beyond trivial rewriting cases.

https://github.com/newren/git-filter-repo

**Comment by AluisioASG** [comment]
Might be worth waiting a bit for https://github.com/newren/git-filter-repo/issues/11, as it should make packaging trivial.

**Comment by ndowens** [comment]
commit#b0d33beb69ca57b6e7e653ca92ec9f981e89bc18

**Comment by Johnnynator** [comment]
@ndowens You don't need to add a hashsign before the commithash. Just writing b0d33be will have Github recognize it and convert it to a link.

**Comment by Johnnynator** [comment]
b0d33be
