### ISSUE TITLE
How to request package update?

### ISSUE THREAD

**Issue by gmoneymagna** [void-linux/void-packages#16112]
Hey guys quick question sorry I am new to this. I see the post header telling me to visit 

https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt

Instead of submitting a package update request. However the package I am requesting is not on that list. How do I submit a request properly?

Thanks,
Garrett

**Comment by Johnnynator** [comment]
If it is missing either just update it yourself and open a PR. Or open a issue. That comment is mainly to reduce the noise of needless opened update request of packages that are already known to be outdated.

**Comment by Hoshpak** [comment]
I think this has been answered. Please either open a new issue for the broken update check of the package in question or a PR to update it.
