### ISSUE TITLE
Travis CI times out and build fails

### ISSUE THREAD

**Issue by reback00** [void-linux/void-packages#16113]
### System
(Not relevant)

### Expected behavior
Being able to pass the build of my [`textadept`](https://github.com/void-linux/void-packages/pull/15627) package and packages by others (which are failing without any reason) without problems.

### Actual behavior
Build fails [randomly](https://github.com/void-linux/void-packages/pull/15627#issuecomment-549231300) even if I push the same code.

I went through the PRs done by others. It seems builds longer than 10 minutes are sure to fail: [https://imgur.com/03flUd7](https://imgur.com/03flUd7)
The only recent build that passed (while writing this) was `rxvt-unicode` and `anydesk` which turned out Green _probably_ because the build completed in less than 10 minutes. This is my basic understanding, I'm not sure about that.

### Steps to reproduce the behavior
Force pushing my package `textadept` does not pass the build.

Pushing almost any package which takes more than 10 minutes to build, should raise this issue.

**Comment by reback00** [comment]
Example fail [log](https://travis-ci.org/void-linux/void-packages/jobs/606980548?utm_medium=notification&utm_source=github_status):
```
...
=> textadept-10.6_1: installing host dependencies: autoconf-2.69_7 automake-1.16.1_2 libtool-2.4.6_4 wget-1.20.3_2 unzip-6.0_12 pkg-config-0.29.2_2 glib-devel-2.62.2_1 ncurses-6.1_4 ...
=> textadept-10.6_1: installing target dependencies: gtk+-devel-2.24.32_3 ncurses-devel-6.1_4 ...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by Johnnynator** [comment]
See #16111
