### ISSUE TITLE
No output has been received in the last 10m0s

### ISSUE THREAD

**Issue by Eluminae** [void-linux/void-packages#16111]
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

https://github.com/void-linux/void-packages/pull/15889

Is this a common problem ? Should we just restart the build ? It seems to works on my machine.

I also find another MR https://github.com/void-linux/void-packages/pull/15627 that seems to suffer from this.

**Comment by reback00** [comment]
Oh! I wrote another issue for this #16113
We wrote at the same time. Maybe that's why I did not see your issue.

I noticed that builds usually fail when they exceed 10 minutes. Is that true for your builds as well?

**Comment by Eluminae** [comment]
Yeah this is funnyi ! :D

Some other distros build exceed the 10 minutes. I really dunno what make this build to fail. The build not seems to be that long.

**Comment by ndowens** [comment]
It is currently the travis-ci builder issue right now, I am not sure what is wrong and I have no access, but it started last night

**Comment by Eluminae** [comment]
There is some issues reported on the travis community website as https://travis-ci.community/t/no-output-in-the-last-10-minutes-issue/5000/3

They speak about cache size. Maybe this can help

**Comment by obunden** [comment]
KInda wish that it was possible to switch to a build environment that didn't place restrictions that makes it hard to get reliable build tests (log size/length, build time). Has there been any talk about using azure pipelines or git actions when it becomes stable? I'm sure that there are other alternatives that I don't know about.

**Comment by reback00** [comment]
> There is some issues reported on the travis community website as https://travis-ci.community/t/no-output-in-the-last-10-minutes-issue/5000/3

That's a good find! Well, on the page there is a [suggestion](https://travis-ci.community/t/no-output-in-the-last-10-minutes-issue/5000/5) to clear cache:

> My issue was due to a Travis cache that grew too large. Clearing the cache and rebuilding seemed to do the trick.
> 
> Cache size is visible in “More options > Caches”.

I tried "More options" menu but there is no "Caches" option. I even signed in with GitHub on travis-ci website, but no luck. I guess only the mods have the ability to clear cache.

**Comment by Johnnynator** [comment]
Travis seems to be back for normal. None of the last builds did exhibit this behavior.
