### ISSUE TITLE
package: calibre 4.2.0 - Failure in Document Conversions

### ISSUE THREAD

**Issue by schmidh** [void-linux/void-packages#16146]
### System

* xuname:  
  dmesg: read kernel buffer failed: Operation not permitted
  Void 5.3.8_2 x86_64 AuthenticAMD uptodate rrFFFFFF*
* package:  
  *  % xbps-query calibre
architecture: x86_64
build-date: 2019-10-21 13:57 UTC
changelog: https://raw.githubusercontent.com/kovidgoyal/calibre/master/Changelog.yaml
filename-sha256: 3e474cba8e79c486786558c0dce680dfd6702dd8f91adca4e440e4c79b2ecec4
filename-size: 23MB
homepage: https://calibre-ebook.com
install-date: 2019-11-05 16:40 CET
install-script: 1256B
installed_size: 59MB
license: GPL-3.0-only
maintainer: bra1nwave <bra1nwave@protonmail.com>
metafile-sha256: 03a011ad43075a1cf611e60a501ec1c37c1234b35121efdf6be55de1ac07e533
pkgver: calibre-4.2.0_1
remove-script: 1251B
repository: https://alpha.de.repo.voidlinux.org/current
shlib-requires:
        libpython2.7.so.1.0
        libusb-1.0.so.0
        libc.so.6
        libz.so.1
        libcrypto.so.45
        libhunspell-1.7.so.0
        libstdc++.so.6
        libgcc_s.so.1
        libm.so.6
        libmtp.so.9
        libicui18n.so.64
        libicuuc.so.64
        libQt5Widgets.so.5
        libQt5Gui.so.5
        libQt5Core.so.5
        libGL.so.1
        libpthread.so.0
        libfontconfig.so.1
        libfreetype.so.6
        libgthread-2.0.so.0
        libglib-2.0.so.0
        libQt5DBus.so.5
        libpodofo.so.0.9.6
        libchm.so.0
short_desc: Ebook management application
source-revisions: calibre:8234ff96616
state: installed*

### Expected behavior
I want to convert a document to pdf.

### Actual behavior
Conversion crashes.

### Steps to reproduce the behavior
Open calibre, select `Quick Start Guide`, right-click `Convert Books`, `Convert Individually`. Select `Output Format` `PDF`. Then press `OK` button.

When running calibre with `export QT_DEBUG_PLUGINS=1` it prints out following messages:

```
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
Cannot load library /usr/lib/calibre/calibre/plugins/libheadless.so: (/usr/lib/calibre/calibre/plugins/libheadless.so: undefined symbol: _ZN11QFontEngine22lockedAlphaMapForGlyphEj6QFixedNS_11GlyphFormatERK10QTransformP6QPoint, version Qt_5_PRIVATE_API)
QLibraryPrivate::loadPlugin failed on "/usr/lib/calibre/calibre/plugins/libheadless.so" : "Cannot load library /usr/lib/calibre/calibre/plugins/libheadless.so: (/usr/lib/calibre/calibre/plugins/libheadless.so: undefined symbol: _ZN11QFontEngine22lockedAlphaMapForGlyphEj6QFixedNS_11GlyphFormatERK10QTransformP6QPoint, version Qt_5_PRIVATE_API)"
qt.qpa.plugin: Could not find the Qt platform plugin "headless" in "/usr/lib/calibre/calibre/plugins"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: headless (from /usr/lib/calibre/calibre/plugins), wayland-org.kde.kwin.qpa, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

**Comment by bra1nwave** [comment]
I'm looking into it. The ebook viewer also doesn't work.

Anyway thanks for reporting!

**Comment by Hoshpak** [comment]
looks like it needs a rebuild against the new qt5 version.

**Comment by bra1nwave** [comment]
Yeah, but the ebook viewer still doesn't work (even with the [archlinux patch](https://git.archlinux.org/svntogit/community.git/tree/trunk/calibre-qt-5.13.2.patch?h=packages/calibre))
