### ISSUE TITLE
Question: shlib SONAME dependencies

### ISSUE THREAD

**Issue by innerspacepilot** [void-linux/void-packages#16200]
Hello!
I want to make a package, which depends on my own library, instead of the FIRST one defined in common/shlibs
Is there a way to do it?

**Comment by ndowens** [comment]
Not an expert by no means, but maybe try LDFLAGS="-L(PATH_TO_YOUR_LIBRARY)" ? that way it might link to it

**Comment by innerspacepilot** [comment]
@ndowens I mean resulting package has dependency on wrong package, based on common/shlibs

**Comment by abenson** [comment]
Why does your library conflict with another package?

**Comment by innerspacepilot** [comment]
I've made kodi package for orange pi, which uses proprietary libEGL.so, but resulting package has dependency to rpi-userland (which is for raspberry pi) which is wrong.  How can I make it depend on different library which provides libEGL.so?

**Comment by st3r4g** [comment]
Maybe set `noverifyrdeps` or `skiprdeps` and manually specify the right package in `depends`

**Comment by xtraeme** [comment]
The correct way is adding a new entry to common/shlibs. See libGL

**Comment by innerspacepilot** [comment]
@xtraeme I tried it and it doesn't work because it just adds the first one. But If I place my lib first it will break other packages.
Code in `common/hooks/pre-pkg/04-generate-runtime-deps.sh:121` just takes the first one.

**Comment by ericonr** [comment]
The suggested solution by @st3r4g is what we have available, and if this should be changed a new issue should be opened. Regarding specifically libEGL stuff, I believe we don't want to support any new OpenGL impls that aren't compatible with glvnd.
