### ISSUE TITLE
Possibly invalid path in gcr-prompter .desktop-file

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#16217]
### Expected behavior
It supposed to not have any errors at all.

### Actual behavior
Even on a fresh install of void and newly installing menulibre I get a parsing error about gcr-prompter has not been found in the PATH.

### Steps to reproduce the behavior
Basically just install menulibre and you should see it for yourself.

**Comment by ericonr** [comment]
No longer an issue.
