### ISSUE TITLE
libgeoip: remove dependency on geoip-data

### ISSUE THREAD

**Issue by user318** [void-linux/void-packages#16216]
Hello,

Currently libgeoip depends on geoip-data. But as I understand, data is not strictly required for the lib - you can get your own data anywhere. So now, for example, when I try to install nginx on a small system, I get this:

```
geoip-data install   -                 20171002_2             25MB 
libgeoip   install   -                 1.6.12_1               56KB 
nginx      install   -                 1.16.1_1               347KB 
```
As you can see geoip-data takes up a huge part of packages install even if I do not need it. I think it is a bad practice and geoip-data should be removed from the dependencies of libgeoip.

**Comment by xtraeme** [comment]
You can `ignore` the `geoip-data` pkg dependency easily with xbps:

```
# echo "ignorepkg=geoip-data" > /etc/xbps.d/99-custom.conf
```

**Comment by user318** [comment]
@xtraeme Thank you for the tip, it is useful! But isn't this a redundant dependency anyway?

**Comment by xtraeme** [comment]
I'm not sure, what would happen if geoip-data is not there?

**Comment by user318** [comment]
Lib wouldn't stop working. But you need to feed it with some data for it to do something meaningful, of course. It's like what would your image viewer do if there were no images around. geoip-data is a pack of Maxmind's lite databases, as I can see. One may not want to use all of those together, but only one of them. Alternatively one could use paid version of Maxmind's database or any other geoip database provider out there. So, yes, geoip-data may be of use in some cases, but there are also many cases when it is useless or overkill.
