### ISSUE TITLE
Package request: kwrite

### ISSUE THREAD

**Issue by kotoko** [void-linux/void-packages#16319]
Homepage: https://kde.org/applications/utilities/org.kde.kwrite
Source: https://cgit.kde.org/kate.git
License: LGPL-2.1+

Kate is already available as a package, so adding kwrite should be easy.

**Comment by Hoshpak** [comment]
It's already available in the kate5 package:

```
# xlocate /usr/bin/kwrite
xlocate: database outdated, please run xlocate -S.
kate5-19.08.0_1	/usr/bin/kwrite
kate5-19.08.0_1	/usr/bin/kwrite
```

**Comment by kotoko** [comment]
Oooh... Thanks!
