### ISSUE TITLE
mpv symbol lookup error

### ISSUE THREAD

**Issue by benalb** [void-linux/void-packages#16379]
* xuname:  
 Void 5.3.10_1 x86_64 GenuineIntel uptodate rrFFFFFFFFFFFF
* package:  
mpv-0.30.0_2

### Expected behavior
play media
### Actual behavior
exit with the message:
"mpv: symbol lookup error: /usr/lib/libshaderc_shared.so.1: undefined symbol: _ZN7glslang8TProgram5mapIOEPNS_14TIoMapResolverE"
### Steps to reproduce the behavior
launch mpv from terminal. 

#edit  
As instructed in #voidlinux 
xdowngrade /var/cache/xbps/glslang-7.11.3214_1.x86_64.xbp
wiil fix it.

**Comment by snglth** [comment]
I can reproduce it
