### ISSUE TITLE
enlightenment: provides wayland session .desktop on non wayland builds

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#16399]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *enlightenment-0.23.1_1*

### Expected behavior
No wayland session option on my DM
`/usr/share/wayland-sessions/enlightenment.desktop` no getting packaged
### Actual behavior
`/usr/share/wayland-sessions/enlightenment.desktop` *exists*
### Steps to reproduce the behavior
`xbps-install enlightenment`

**Comment by q66** [comment]
fixed in 0.24.1
