### ISSUE TITLE
IceWM-Session start crashes!

### ISSUE THREAD

**Issue by sass432** [void-linux/void-packages#16409]
Hallo,
Since the last Void-Updates IceWM-Session-xstart crashes with flickering Desktop-Icons and Toolbar
I am thankfull for help!

**Comment by ndowens** [comment]
Does it output any kind of error after crash?

**Comment by sass432** [comment]
No. It just flickers for a few seconds and after that erverything seems to be normal. but after I installed of 'xorg-apps' a yellow window opened and gave
me the information of an icewm-crash with the posibility to continue or to break the icewm-session-start without a useful information, whats the reason of crash.

**Comment by st3r4g** [comment]
Cannot reproduce (x86_64-musl, Intel graphics)

**Comment by ndowens** [comment]
Not sure, but I am preparing an update. Then you can test it and see if it works for you after it gets committed.

**Comment by sass432** [comment]
Thank you for your attempt to help and this icewm-update. 
But I found out, that the flickering had nothing to do with icewm.
It appears, when I activate nodm, so I think this is the problem.
With this I can close this issue!
