### ISSUE TITLE
Package Request: ProtonMail-Bridge

### ISSUE THREAD

**Issue by gmoneymagna** [void-linux/void-packages#16457]
I would like to request the ProtonMail-Bridge gui app.

https://aur.archlinux.org/packages/protonmail-bridge/

I do not see it on the list of packages being worked on. I have tried the hydroxide package, but it wont work and needs to be updated and I don't mind using the protonmail-bridge as I have used that in the past.

Thank you,
G

**Comment by jnbr** [comment]
See https://github.com/void-linux/void-packages/issues/8051

**Comment by gmoneymagna** [comment]
Okay makes sense! I guess I'll make a new post to request and update to the hydroxide package. Thanks!

**Comment by jnbr** [comment]
hydroxide is already packaged.

**Comment by salifm** [comment]
@jnbr ProtonMail Bridge is not open source and licensed under GPL3. Please reopen this issue

**Comment by ericonr** [comment]
Don't revive old issues, make new ones. And it's a package already, just restricted - which could change.

If it's the bridge in #22559 , that one is a pain.
