### ISSUE TITLE
Nvidia is being bumped to 440.31, but we need libglvnd for Optimus laptops

### ISSUE THREAD

**Issue by grand0rbiter** [void-linux/void-packages#16476]
I saw [here](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt) that 440.31 will be in the repos and this version finally has Optimus (and Vulkan) support.

But in order for this to work, libglvnd needs to be there so both *GL libraries can coexist. It builds fine in musl now, but it is not in the repos.

Is there any news about this?

**Comment by st3r4g** [comment]
#16497

**Comment by st3r4g** [comment]
@xtraeme can be closed

**Comment by xtraeme** [comment]
glvnd has been merged, and optimus support is already working.
