### ISSUE TITLE
nextcloud-client: enable e2e

### ISSUE THREAD

**Issue by kernle32dll** [void-linux/void-packages#16489]
The nextcloud-client package was introduced via https://github.com/void-linux/void-packages/pull/14069. In it, e2e was disabled, as libreSSL was missing required functionality.

However, via https://github.com/libressl-portable/openbsd/commit/8dcdd9bfaa8127f035a1ac832c80a381df82b816 (landed in void via https://github.com/void-linux/void-packages/pull/16124) this now should no longer be the case.

Related to this is https://github.com/nextcloud/desktop/issues/738

Can someone try to enable E2E, and see if it works now? I lack time and experience with the void linux build infrastructure to do this myself.

CC @yopito as creator of the package

**Comment by yopito** [comment]
Thanks for pointing this. I will check next week.

**Comment by yopito** [comment]
commit https://github.com/libressl-portable/openbsd/commit/8dcdd9bfaa8127f035a1ac832c80a381df82b816 is not included in libreSSL 3.0.2 release: 
```
$ xbps-query -o /usr/include/openssl/rsa.h
libressl-devel-3.0.2_1: /usr/include/openssl/rsa.h (regular file)

$ head -n 1 /usr/include/openssl/rsa.h 
/* $OpenBSD: rsa.h,v 1.40 2019/06/05 15:41:33 gilles Exp $ */
```
have to wait for next release of libreSSL (including include rsa.h, v > 1.44 - CVS revision)

**Comment by kernle32dll** [comment]
Uh, my bad.... Sorry!

**Comment by yopito** [comment]
PR #25287 fix this issue.

**Comment by yopito** [comment]
this issue has been fixed

**Comment by ericonr** [comment]
Thanks!
