### ISSUE TITLE
Package Request: cherrytree

### ISSUE THREAD

**Issue by cwross** [void-linux/void-packages#16502]
Requesting a package for Cherrytree, "a hierarchical note taking application, featuring rich text and syntax highlighting, storing data in a single xml or sqlite file."

Source available here: https://www.giuspen.com/cherrytree/#downl

Thank you!

**Comment by ndowens** [comment]
Looks like there is already a package available https://github.com/void-linux/void-packages/blob/3996884c7220172d0e9dcede571b5cf8bd7cda33/srcpkgs/cherrytree/template

**Comment by cwross** [comment]
Oops; I don't know how I managed to miss that... apologies and thank you!
