### ISSUE TITLE
Remove some low-res fonts from xorg-fonts

### ISSUE THREAD

**Issue by PaperMountainStudio** [void-linux/void-packages#16573]
### Description
Package `xorg` has a dependency `xorg-fonts` which ships too low-res fonts. For example when first installing firefox, fonts are ugly. I think this is confusing to new users and should be changed.

### Steps to reproduce the behavior
```sh
xbps-install xorg firefox
```
and start firefox for example on <https://github.com/void-linux/void-packages/>

**Comment by svenper** [comment]
Perhaps they could be installed but blacklisted by default in fontconfig.

**Comment by mvf** [comment]
Do we have any evidence that the `xorg-fonts` actually override prettier fonts? I'd reckon you're just missing the website's preferred font and the ugly bitmap font is just the last resort before it's tofu time. Example from one popular website:
```
font-family: Georgia, "Times New Roman", Times, serif;
```
On a system with just `xorg` and `firefox` (i.e. with no `Georgia` and `Times New Roman` matches), this will fall back to the `Times` bitmap font. You can verify this on your end:
1. In Firefox, navigate to an affected website
2. Press `Ctrl+Shift+C` and select an element that looks bad to you
3. To the right of the Web Developer Toolbar that should have popped up, check the "Font" tab and note the effective font
4. Check the font with `fc-match`. It will likely be a PCF (i.e. bitmap) font, e.g.:
```
$ fc-match Times
timR12-ISO8859-1.pcf.gz: "Times" "Regular"
```
Removing this fallback font won't help. You need to install a better match for the font families requested by the website. For best-looking results and least headache, the restricted `msttcorefonts` package is a good start. It's a Windows world out there...

**Comment by PaperMountainStudio** [comment]
According to someone on IRC (I don't know who, sorry), Firefox tries to use bitmap fonts first, then falls back to TTF/OTF fonts. So by removing bitmap fonts we can make it use the better fonts.

**Comment by PaperMountainStudio** [comment]
You are almost right, but:
If we have a font family definition like this:
```css
body {
    font-family: ...,Helvetica,Arial,sans-serif,...
}
```
and we have _xorg-fonts_ installed, first match will be _Helvetica_ (ugly):
![2](https://user-images.githubusercontent.com/23639164/70552161-1e34f000-1b79-11ea-92b3-9b17028d7840.png)
fontconfig matches to one of the low-res fonts
![3](https://user-images.githubusercontent.com/23639164/70550491-20497f80-1b76-11ea-870f-473a87e86de7.png)
if all fonts except _dejavu-fonts-ttf_ are uninstalled, the site matches fonts on _sans-serif_ which is dejavu sans
![4](https://user-images.githubusercontent.com/23639164/70550502-250e3380-1b76-11ea-8423-a5ee09a7cb9d.png)
![5](https://user-images.githubusercontent.com/23639164/70550511-28092400-1b76-11ea-838b-18d169b22f20.png)
I think we shouldn't include fonts most people will never need. If people need them, they can always install them manually.

**Comment by mvf** [comment]
As you have shown, removing the bitmap font merely causes Firefox to move on to the next, less preferred font family, which may or may not have a TTF/OTF match. This might improve your personal out of the box Firefox experience on your particular system/locale/website/display, but Firefox is not the only app out there.

These fonts have been bundled with X11 since time immemorial and apps rely on them. Some of them don't even support TTF/OTF. For instance, `xcalc` pulled in via `xorg`'s `xorg-apps` dependency will no longer be able to display π.

**Comment by xtraeme** [comment]
I think theres a way to raise priority in fontconfig...

**Comment by xtraeme** [comment]
There's no need to remove anything. As previous comment said. Some apps expect those old and ugly fonts...

**Comment by PaperMountainStudio** [comment]
whoops, sorry

**Comment by xtraeme** [comment]
This is not a proper solution, closing this.

**Comment by gf3** [comment]
> This is not a proper solution, closing this.

what is the proper solution? is there another discussion elsewhere?

**Comment by atisDu** [comment]
sudo ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/ from this thread https://www.reddit.com/r/voidlinux/comments/izm3xb/firefox_ugly_fonts/

**Comment by alexmozaidze** [comment]
> `sudo ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/`
Thank you! Before I ran this command, Firefox didn't render those low-res fonts at all.
