### ISSUE TITLE
ERROR: krita-4.2.7.1_1: couldn't verify distfiles, exiting...

### ISSUE THREAD

**Issue by nashimus** [void-linux/void-packages#16592]
### System

* xuname:  
  Void 5.3.10_1 ppc64le PowerNV uptodate FFFF
* package:  
  krita-4.2.7.1

### Expected behavior
  Package krita.
### Actual behavior
```
=> krita-4.2.7.1_1: verifying checksum for distfile 'krita-4.2.7.1.tar.gz'... 
=> ERROR: SHA256 mismatch for 'krita-4.2.7.1.tar.gz:'
3ed29fd9d8e067def55e703fc55312815c21041d274727e228bdbe0478c09c3d
=> ERROR: krita-4.2.7.1_1: couldn't verify distfiles, exiting...
```
### Steps to reproduce the behavior
```
./xbps-src pkg krita -j96
```
### Additional information
md5sum does match that of md5sums.txt of download source:
http://ftp5.gwdg.de/pub/linux/kde/stable/krita/4.2.7.1/

```
void-packages$ md5sum hostdir/sources/krita-4.2.7.1/krita-4.2.7.1.tar.gz 
50779e05d71062fe74cef7fa60fb6a89  hostdir/sources/krita-4.2.7.1/krita-4.2.7.1.tar.gz
```
Contents of 
http://ftp5.gwdg.de/pub/linux/kde/stable/krita/4.2.7.1/md5sum.txt
```
...
50779e05d71062fe74cef7fa60fb6a89  krita-4.2.7.1.tar.gz
...
```

**Comment by nashimus** [comment]
@Johnnynator do you have a moment to look at this?

https://github.com/void-ppc/void-packages/commit/2a52ff9226ac83235526765bb20824284d373127

Thanks!

**Comment by ndowens** [comment]
@nashimus I just did xgensum -i krita and it came back fine. You may can solve this if you do: rm -rf hostdir/sources/*

**Comment by Johnnynator** [comment]
We are using `sha256` and not `md5` for checksums. But yes it seems like KDE has replaces the tarball with a different one (once again...). I will look onto it later and update the template.
