### ISSUE TITLE
Update of alsa-utils fails with "directory not empty" error message

### ISSUE THREAD

**Issue by divanosport** [void-linux/void-packages#16596]
Hello!

This update alsa-utils (1.1.9_1 -> 1.2.1_1) fails with this error message:

"ERROR: alsa-utils-1.2.1_1: [unpack] failed to extract file `./etc/sv/alsa/supervise': Directory non vuota
ERROR: alsa-utils-1.2.1_1: [unpack] failed to extract files: Directory non vuota
ERROR: alsa-utils-1.2.1_1: [unpack] failed to unpack files from archive: Directory non vuota
Transaction failed! see above for errors."

Directory non vuota means directory not empty.

### Expected behavior

Should update wthout errors I guess.

### Actual behavior

Error outlined above.

### Steps to reproduce the behavior

sudo xbps-install -Suv

**Comment by sgn** [comment]
Could you check if your `/etc/sv/alsa/supervise` is a link to `/run/runit/supervise.alsa`?

If it's, then this is a bug.
If it's NOT, then I guess you has tempered with it. Please relink

**Comment by divanosport** [comment]
I see, I might have tampered with it some time ago because I was having audio issues.

I uninstalled alsa-utils, removed /etc/sv/alsa/supervise, and installed alsa-utils again without problems. Thanks for the tip.

**Comment by sgn** [comment]
Please close this issue then
