### ISSUE TITLE
/usr/bin/cc missing

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#16768]
Currently, when doing a system upgrade, `/usr/bin/cc` might be missing afterwards.

**Temporary workaround:**
`xbps-install -f gcc` will re-create the missing symlink.

This happened in the attempt to get rid of the alternatives group for `cc`  (ca12899c1357449fcbcd29cfc3442e641698be90). 

@void-linux/pkg-committers The build-servers are affected as well, so if possible, avoid pushing things until this is resolved.

**Comment by Duncaen** [comment]
I purged all the chroots a few times, added a really bad patch to xbps to work around it and purged the chroots again.
Should be good to go now, still needs a proper fix tho.

**Comment by xtraeme** [comment]
The real issue is ordering: alternatives need to be updated before trans start...

**Comment by jnbr** [comment]
Closing this, as it seems like there is no impact on the repositories and no one complained about it.
A proper fix should be done / discussed in xbps.
