### ISSUE TITLE
linux5.3.13_1 Building DKMS module for nvidia-390.132 fails

### ISSUE THREAD

**Issue by yilmzfurkan** [void-linux/void-packages#16778]
Latest update of the linux5.3 (linux5.3.13_1) fails to build DKMS module for nvidia-390.132
```
[*] Configuring unpacked packages
linux5.3-5.3.13_1: configuring ...
Executing post-install kernel hook: 10-dkms ...
Available DKMS module: nvidia-390.132.
Available DKMS module: virtualbox-ose-6.0.14.
Available DKMS module: wireguard-0.0.20191012.
Building DKMS module: nvidia-390.132... FAILED!
```

**Comment by Hoshpak** [comment]
Please check if /usr/bin/cc points to gcc. If it does and it still doesn't work, please post the error message produced by the compiler.

**Comment by yilmzfurkan** [comment]
Thanks @Hoshpak as always you are really helpful! I checked /usr/bin/cc and it was pointed to clang (probably because I needed clang to build something and when I installed clang it had overwritten it?) Fixed it with `sudo ln -sf /usr/bin/gcc /usr/bin/cc` and after that I have run `sudo xbps-reconfigure -f linux5.3 ` everything works fine now.
