### ISSUE TITLE
xorg-server: missing symlink to /usr/bin/X11

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#1682]
### System

* xuname:  
  Void 4.17.14_1 x86_64 GenuineIntel uptodate rrmDDDDDDDDDDDDDDDDDDDDDFFFFF

* package:  
  xorg-server-1.20.1_1

### Expected behavior

After updating to xorg-server-1.20.1_1 I expected my DM (lxdm) to start

### Actual behavior

It failed to start xorg because /usr/bin/X was missing. I had to create a symlink to /usr/bin/Xorg manually. startx also fails to execute.

### Steps to reproduce the behavior

Install xorg-server-1.20.1_1, run startx.

**Comment by Hoshpak** [comment]
PR #1680

**Comment by maxice8** [comment]
should be fixed by #1680
