### ISSUE TITLE
icedtea-web-1.6.2_1 looks for wrong java bin

### ISSUE THREAD

**Issue by kozachynskyi** [void-linux/void-packages#16835]
### System

* xuname:  
Void 5.3.13_1 x86_64 GenuineIntel uptodate rrrrmmnFFFF
* package:  
icedtea-web-1.6.2_1
openjdk8-8u232b09_1
openjdk8-jre-8u232b09_1

### Expected behavior
javaws works

### Actual behavior
icedteaweb looks for wrong java. This is an error message I receive:

/bin/javaws: line 98: /usr/lib/jvm/openjdk/jre/bin/java: No such file or directory

### Steps to reproduce the behavior

Install icedtea-web and try to run javaws or itweb-settings

**Comment by Johnnynator** [comment]
Should be fixed with https://github.com/void-linux/void-packages/commit/034c46e4f5eb40f8af58ddb76817cd06057024b2

**Comment by kozachynskyi** [comment]
New version, "icedtea-web-1.6.2_2" handled the problem. Thank you @Johnnynator
