### ISSUE TITLE
New i3blocks package miss /usr/libexec/i3blocks with scripts

### ISSUE THREAD

**Issue by rapha8l** [void-linux/void-packages#16854]
* xuname:  
Void 5.3.13_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFF

* package:  
scripts that were part of the package are now missing (in /usr/libexec/i3blocks), it leads to non working checks

Thanks

**Comment by abenson** [comment]
Upstream moved all of the scripts to [i3blocks-contrib](https://github.com/vivien/i3blocks-contrib). Waiting on the [matching release](https://github.com/vivien/i3blocks-contrib/issues/251) before it can be packaged.

**Comment by teldra** [comment]
https://github.com/void-linux/void-packages/pull/16787 working on it.

**Comment by rapha8l** [comment]
thanks !

**Comment by rapha8l** [comment]
Hi,
Just for information, scripts in /usr/libexec/i3blocks are 644 and not executable
Thanks

**Comment by teldra** [comment]
sry. my bad overlooked it completely. should be fixed in https://github.com/void-linux/void-packages/pull/16935

**Comment by rapha8l** [comment]
thanks again !
