### ISSUE TITLE
Package Request: meek-client 0.34

### ISSUE THREAD

**Issue by mamins1376** [void-linux/void-packages#16866]
Homepage: https://trac.torproject.org/projects/tor/wiki/doc/meek
Sources: https://gitweb.torproject.org/pluggable-transports/meek.git/
License: CC0-1.0

**Comment by ndowens** [comment]
https://termbin.com/08ou See if it works fine Not sure how it is used, so I can't really test it

**Comment by mamins1376** [comment]
@ndowens I tried to package this already but torproject.org is blocked in Iran, so can't really test it.

**Comment by daniel-eys** [comment]
@mamins1376 You might be interested in the package `obfs4proxy` which is already available in void.
From their manpage:

>obfs4proxy implements the obfuscation protocols obfs2, obfs3,
>ScrambleSuit (client only), meek (client only) and obfs4.

**Comment by daniel-eys** [comment]
Haven't tested the meek client of obfs4proxy though.
Some more info from the initial implementation commit:

>This is a meek client only implementation, with the following
>differences with dcf's `meek-client`:
>
> - It is named `meek_lite` to differentiate it from the real thing.
> - It does not support using an external helper to normalize TLS
>   signatures, so adversaries can look for someone using the Go
>   TLS library to do HTTP.
> - It does the right thing with TOR_PT_PROXY, even when a helper is
>   not present.
>
>Most of the credit goes to dcf, who's code I librerally cribbed and
>stole.  It is intended primarily as a "better than nothina" option
>for enviornments that do not or can not presently use an external
>Firefox helper.
