### ISSUE TITLE
Package request: UW-imap

### ISSUE THREAD

**Issue by stacyharper** [void-linux/void-packages#16880]
Repo: https://github.com/uw-imap/imap

**Comment by Eluminae** [comment]
We'll have problems cause UW-imap seems to only build with openssl

**Comment by ndowens** [comment]
Where is the actual upstream download location. Seems to be a mirror that imports patches from what looks like an RPM distro and link on that page gives a 404 on the Washington univ. page

**Comment by ndowens** [comment]
There isn't really a release on the GH page; just seems to host patches for it, and the "upstream" URL, washington.edu/imap is a 404

**Comment by Eluminae** [comment]
Yeah this imap server seems to not be reliable...
I dunno what happen with the washington url.

**Comment by Eluminae** [comment]
I got unfortunately not much solution to have a mh maiboxes imap server.
