### ISSUE TITLE
julia-1.3.0 version bump

### ISSUE THREAD

**Issue by XVilka** [void-linux/void-packages#16888]
The Void version is old. Current stable version is 1.3.0:

## Current stable release: v1.3.0 (Nov 25, 2019)

- https://github.com/JuliaLang/julia/releases/tag/v1.3.0
- https://github.com/JuliaLang/julia/releases/download/v1.3.0/julia-1.3.0.tar.gz

## New language features

-    Support for Unicode 12.1.0 (#32002).
-    Methods can now be added to an abstract type (#31916).
-    Support for unicode bold digits and double-struck digits 0 through 9 as valid identifiers (#32838).
-    Added the syntax var"#str#" for printing and parsing non-standard variable names (#32408).

## Multi-threading changes

-    New experimental Threads.@spawn macro that runs a task on any available thread (#32600).
-    All system-level I/O operations (e.g. files and sockets) are now thread-safe. This does not include subtypes of IO that are entirely in-memory, such as IOBuffer, although it specifically does include BufferStream. (#32309, #32174, #31981, #32421).
-    The global random number generator (GLOBAL_RNG) is now thread-safe (and thread-local) (#32407).
-    New Channel(f::Function, spawn=true) keyword argument to schedule the created Task on any available thread, matching the behavior of Threads.@spawn (#32872).
-    Simplified the Channel constructor, which is now easier to read and more idiomatic julia. Use of the keyword arguments csize and ctype is now discouraged (#30855, #32818).

**Comment by Duncaen** [comment]
Void has a script that notifies us about outdated packages, there is no need to open a issue for that especially if its just two days old.

https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt
