### ISSUE TITLE
visualboyadvance-m invalid pointer

### ISSUE THREAD

**Issue by chriscamacho** [void-linux/void-packages#1688]
### System

* xuname:  
  Void 4.17.14_1 x86_64 GenuineIntel uptodate rrrmF
* package:  
  vba-m-2.1.0_2

### Expected behavior
  it would work

### Actual behavior
  after a rom has been loaded I see the following error message on the console

(visualboyadvance-m:3831): Gtk-CRITICAL **: 14:13:02.304: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed
*** Error in `visualboyadvance-m': free(): invalid pointer: 0x00005599703d36a0 ***
Aborted

the roms were previously working with this package version and also with a slightly more up to date version compiled from github

### Steps to reproduce the behavior

run the program, load a "rom"

**Comment by thypon** [comment]
I personally cannot reproduce the bug.

**Comment by mvf** [comment]
No crashes here either. But sound only works when `libopenal-devel` is installed manually, since otherwise `libopenal.so` can't be `dlopen`ed.

**Comment by chriscamacho** [comment]
okay... this seems to have resolved itself (presumably with an update?) - without need for recompile or reinstall (depending which version I run) wish I knew what it was tho....
