### ISSUE TITLE
FTBFS: NetworkManager for ppc64le{,-musl}

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#16882]
Some build script seems to be erroneously modifying the `XBPS_TARGET_QEMU_MACHINE` environment or picking up a wrong value because builds fail with this error:
```
env -i GI_TYPELIB_PATH=/builddir/NetworkManager-1.18.2/build/libnm LD_LIBRARY_PATH=/builddir/NetworkManager-1.18.2/build/libnm sh -c '/usr/bin/qemu-ppc64-static -L /usr/powerpc64le-linux-gnu /usr/powerpc64le-linux-gnu/bin/python3' /builddir/NetworkManager-1.18.2/libnm/generate-setting-docs.py --lib-path /builddir/NetworkManager-1.18.2/build/libnm --gir libnm/NM-1.0.gir --output libnm/nm-property-docs.xml
/usr/powerpc64le-linux-gnu/bin/python3: Invalid ELF image for this architecture
```
So it tries to use `/usr/bin/qemu-ppc64-static` while it should be `/usr/bin/qemu-ppc64le-static`.
Any idea what could be causing this, perhaps the meson cross build style?

I tried `echo "XBPS_TARGET_QEMU_MACHINE: $XBPS_TARGET_QEMU_MACHINE"` in `pre_configure()` and there it is `ppc64le` as expected...

I see `common/build-style/meson.sh` sets `_MESON_CPU_FAMILY=ppc64` for both, `ppc64le` and `ppc64`. Is this intentional and correct?

**Comment by pullmoll** [comment]
The reason why it fails is the line `_MESON_CPU_FAMILY=ppc64` for the case `ppc64le*)`. After changing that to `_MESON_CPU_FAMILY=ppc64le` the build succeeds.

**Comment by pullmoll** [comment]
https://github.com/void-linux/void-packages/commit/0d23f73635d8d5b96e832387b9e578bba4014cd4

**Comment by Johnnynator** [comment]
The change is wrong. Read https://mesonbuild.com/Reference-tables.html#cpu-families

> Those porting from autotools should note that meson does not add endianness to the name of the cpu_family. For example, autotools will call little endian PPC64 "ppc64le", meson will not, you must also check the .endian() value of the machine for this information.

**Comment by Johnnynator** [comment]
I'm more wondering how meson did even figure out to use qemu since in your case the exe_wrapper should not be set. You can try fixing it by adding `qemu` to the build_helper.

**Comment by pullmoll** [comment]
Ok, I'll try that here.

**Comment by pullmoll** [comment]
BTW It's the `/usr/bin/g-ir-scanner-qemuwrapper` which expands `${XBPS_TARGET_QEMU_MACHINE}` to `ppc64` instead of `ppc64le` in this case. I don't see where this environment variable would be changed, though. Except if perhaps the file `common/cross-profiles/ppc64.sh` would be included instead of `ppc64le.sh` depending on how `_MESON_CPU_FAMILY` was set up.

**Comment by pullmoll** [comment]
I have no clue yet how to really fix this or why it works with the ppc64le family name despite the description at https://mesonbuild.com/Reference-tables.html#cpu-families which tells not to specify endianess in the CPU family name.

**Comment by Johnnynator** [comment]
The cross-gir patch for NetworkManager needed a update for ppc64le. The `/usr/bin/g-ir-scanner-qemuwrapper` was not the cu;culprit and used the correct qemu binary.

**Comment by Johnnynator** [comment]
See https://github.com/void-linux/void-packages/commit/ea3114ae55990b8e824a2d68d14796c25355b2d6
