### ISSUE TITLE
lxc: does not work with recent cgroups changes

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#16918]
Current release of LXC is broken. upstream recommends cherry-picking patches. The patches they cherry pick for the LXD snap are listed here: https://github.com/lxc/lxd-pkg-snap/blob/latest-candidate/snapcraft.yaml#L530

**Comment by ndowens** [comment]
My LXC seems fine, what was your's doing. I could start/stop/exec

**Comment by CameronNemo** [comment]
@ndowens kernel version? details in https://github.com/lxc/lxd/issues/6463

**Comment by ndowens** [comment]
5.3.11
