### ISSUE TITLE
nvidia: broken with linux5.4

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#16924]
The nvidia kernel module fails to compile with linux 5.4 citing missing or invalid Module.symvers which is there. The issue was fixed in Version 430.64 according to the changelog so the package needs to be updated.

**Comment by st3r4g** [comment]
See https://github.com/void-linux/void-packages/pull/15849 for why it wasn't updated before. Is the suggested workaround acceptable?

**Comment by Hoshpak** [comment]
Yes, I think so. It's the only way currently to do it without losing the i686 compatibility package.

**Comment by st3r4g** [comment]
ok, I'll open a PR then.

**Comment by gmorenz** [comment]
Did #16981 fix this?
