### ISSUE TITLE
virtualbox-ose: broken with linux5.4

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#16925]
virtualbox-ose fails to compile the kernel modules via dkms with linux5.4. According to https://www.virtualbox.org/ticket/18945 the kernel version will be supported by version 6.1 so we have to wait for that to be released or the changes to be backported to a 6.0.x release.

**Comment by amak79** [comment]
Gentoo has a patch available: https://gitweb.gentoo.org/repo/gentoo.git/tree/app-emulation/virtualbox-modules/files/virtualbox-modules-6.0.14-kernel-5.4_rc6.patch

**Comment by Hoshpak** [comment]
Thanks, I will test that.

**Comment by yilmzfurkan** [comment]
VirtualBox 6.1 just released :tada: https://www.virtualbox.org/wiki/Changelog-6.1
