### ISSUE TITLE
nvidia340: broken with linux5.4

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#16923]
nvidia340 fails to compile the kernel module via dkms and complains about missing Makefiles. I suspect that the use of `SUBDIRS` is the culprit since the 5.3 Makefile already warns against using that when compiling the module:

```
Makefile:213: ================= WARNING ================
Makefile:214: 'SUBDIRS' will be removed after Linux 5.3
Makefile:215: 
Makefile:216: If you are building an individual subdirectory
Makefile:217: in the kernel tree, you can do like this:
Makefile:218: $ make path/to/dir/you/want/to/build/
Makefile:219: (Do not forget the trailing slash)
Makefile:220: 
Makefile:221: If you are building an external module,
Makefile:222: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:223: ==========================================
```

The package needs to be patched or updated if nvidia releases a compatible version.

**Comment by st3r4g** [comment]
An update is available: https://www.nvidia.com/Download/driverResults.aspx/156163/en-us

**Comment by newbluemoon** [comment]
Just to add: Tested #17999 with kernels 5.4, 5.3, and 4.19 on i686, everything works so far. :)
