### ISSUE TITLE
xorgproto fails upgrade due to conflicting file with libXvMC-devel

### ISSUE THREAD

**Issue by haunma** [void-linux/void-packages#16937]
### System

* xuname:  
Void 5.2.18_1 x86_64-musl GenuineIntel notuptodate rrnFF

* package:  
xorgproto-2019.2_1

### Expected behavior
Package upgrades without error.

### Actual behavior
xbps-install fails to upgrade the package, with the error
```
xorgproto-2019.2_1: collecting files...
ERROR: xorgproto-2019.2_1: file `/usr/include/X11/extensions/vldXvMC.h' already installed by package libXvMC-devel-1.0.12_1.
Transaction failed! see above for errors.
```
This is preventing me from updating anything else on my system.

### Steps to reproduce the behavior
xbps-install -Su

**Comment by haunma** [comment]
A workaround is to first remove the package libXvMC-devel, then complete the system upgrade.  After the update is complete, re-installing libXvMC-devel succeeds, strangely.

**Comment by st3r4g** [comment]
> A workaround is to first remove the package libXvMC-devel, then complete the system upgrade. After the update is complete, re-installing libXvMC-devel succeeds, strangely.

It's because conflicting files are only checked within a transaction. It's still not good because the file has been replaced by the last one you installed (`libXvMC-devel`). Run `sudo xbps-pkgdb -a` and you should see it complaining about `xorgproto`.
