### ISSUE TITLE
Update Request: Samba

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#1693]
The samba in Voids repos is still `3.6.25`, however the current version is `4.8.3`.

Right now some clients cannot access my shares anymore since SMB3 is required for up-to-date windows computers. 

https://github.com/void-linux/void-packages/blob/4e73c26f56504ee1ef1884204cf53a24c0bd21e9/srcpkgs/samba/template

**Comment by arete** [comment]
hi,
this is old pull request for samba4
https://github.com/voidlinux/void-packages/pull/6601

**Comment by fosslinux** [comment]
see #2334 (a new pull request of https://github.com/voidlinux/void-packages/pull/6601)

**Comment by arete** [comment]
hi
i have samba4 branch build fine on x64, try to fix cross build.
https://github.com/arete/void-packages/tree/samba4

**Comment by Anachron** [comment]
@maxice8 why has this been closed without comment?

**Comment by maxice8** [comment]
On Tue, Feb 19, 2019 at 10:05:29PM -0800, Anachron wrote:
> @maxice8 why has this been closed without comment?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/1693#issuecomment-465437875

There is an open PR for it

**Comment by Gottox** [comment]
https://github.com/void-linux/void-packages/pull/2334
