### ISSUE TITLE
missing driver "amdgpu/navi14_gpu_info.bin" in linux 5.4

### ISSUE THREAD

**Issue by CoolOhm** [void-linux/void-packages#16967]
I am trying to run a new Navi 14 Amd GPU on the 5.4 kernel and getting the dollowing error on dmesg when it tires to load up:
```

[    3.067292] [drm] initializing kernel modesetting (NAVI14 0x1002:0x7340 0x1462:0x12A5 0xC1).
[    3.092584] [drm] add ip block number 2 <navi10_ih>
[    3.092608] amdgpu 0000:03:00.0: Direct firmware load for amdgpu/navi14_gpu_info.bin failed with error -2
[    3.092610] amdgpu 0000:03:00.0: Failed to load gpu_info firmware "amdgpu/navi14_gpu_info.bin"
```

apparently the kernel cant find "amdgpu/navi14_gpu_info.bin" to load for the card, even though it can recognize the card.

this error can be reproduced by trying to load the driver for the device.

The missing driver bug is consistent with the output of "lspci -k" which lists a kernel module but no driver:
```
03:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500 / 5500M] (rev c1)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 12a5
        Kernel modules: amdgpu
```

Is there some other package I need to update or is this a kernel issue? I have the latest package for amdgpu installed.

**Comment by st3r4g** [comment]
It's missing the firmware, which should be provided by `linux-firmware-amd`. I see the file on https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/amdgpu, so I suppose it is enough to update the package to latest version `20191022`.

**Comment by CoolOhm** [comment]
Yeah, that looks correct. I'll see what I can do.
