### ISSUE TITLE
FTBFS: cross-{aarch64,powerpc64,powerpc64le}-linux-gnu

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#17023]
The three cross compilers fail to successfully finish `_glibc_build()` because of a warning about a wrong attribute alias for `__gettimeofday` which eventually results in an error. 

I could solve the problem by adding `-Wno-attribute-alias` to the `export CFLAG="...` line in the templates in the `_glibc_build()` functions.

I still wonder how the most recent update of the cross compilers could succeed, or whether some updated dependency led to this problem.
Perhaps someone can try and see whether we really need this, i.e. if building the three cross compilers fails out of the box for you as well.

**Comment by ametisf** [comment]
I was able to reproduce this issue OOTB and adding `-Wno-attribute-alias` fixed it.

**Comment by q66** [comment]
This was unnecessary, I fixed this issue for all the ppc toolchains (but not the ARM) as a part of my recent rebuild... by adding `--disable-werror` to `glibc` build

**Comment by q66** [comment]
I reverted those, added `--disable-werror` for `aarch64` as well, and removed the now-unneeded explicit `-Wno-error` as well. That one should've caught the issue originally as I would've expected, but I think an update in dependencies changed ordering of those flags, making this not propagate correctly. Now it should be fixed always.

**Comment by xtraeme** [comment]
You are right. Ive got some new ideas to make xbps-src more reliable. Coming soon 👌

**Comment by xtraeme** [comment]
The goal is to make it that simple to be able to write it in your fav lang.
