### ISSUE TITLE
Gmsh depends on a lot of -devel packages.

### ISSUE THREAD

**Issue by scaramacai** [void-linux/void-packages#17086]
### System

* xuname:  Void 5.3.13_1 x86_64-musl GenuineIntel uptodate rF
  *output of ``xuname`` (part of xtools)*
* package:  gmsh-4.4.1_1
  *affected package(s) including the version*

### Expected behavior
gmsh should not need devel packages

### Actual behavior
[root@vxxxxx ~]# xbps-install gmsh
54 packages will be downloaded:
  blas-devel-3.8.0_2 lapack-devel-3.8.0_2 alsa-lib-devel-1.2.1_1 
  expat-devel-2.2.9_1 dbus-devel-1.12.16_1 eudev-libudev-devel-3.2.9_1 
  libusb-devel-1.0.23_1 libusb-compat-0.1.5_7 
  libusb-compat-devel-0.1.5_7 libogg-devel-1.3.4_1 
  libvorbis-devel-1.3.6_4 libflac-devel-1.3.3_1 sqlite-devel-3.30.1_1 
  libsndfile-devel-1.0.28_3 fftw-devel-3.3.8_2 
  libsamplerate-devel-0.1.9_1 xorgproto-2019.2_1 
  libxshmfence-devel-1.3_2 xtrans-1.4.0_1 xcb-proto-1.13_2 
  libXdmcp-devel-1.1.3_1 libXau-devel-1.0.9_1 libxcb-devel-1.13.1_2 
  libX11-devel-1.6.9_1 libXext-devel-1.3.4_1 libXxf86vm-devel-1.1.4_3 
  libXfixes-devel-5.0.3_3 libXdamage-devel-1.1.5_1 
  libpciaccess-devel-0.16_1 libdrm-devel-2.4.100_1 libOSMesa-19.2.5_1 
  MesaLib-devel-19.2.5_1 glu-devel-9.0.1_1 libasyncns-devel-0.8_9 
  libXi-devel-1.7.10_1 libXtst-devel-1.2.3_2 pulseaudio-devel-13.0_1 
  sndio-devel-1.6.0_1 libxkbcommon-devel-0.9.1_1 wayland-devel-1.17.0_1 
  wayland-protocols-1.18_1 libuuid-devel-2.34_4 libICE-devel-1.0.10_2 
  libSM-devel-1.2.3_1 libXcursor-devel-1.2.0_1 libXinerama-devel-1.1.4_1 
  libXScrnSaver-devel-1.2.3_1 libXrender-devel-0.9.10_2 
  libXrandr-devel-1.5.2_1 Vulkan-Headers-1.1.127_1 
  vulkan-loader-1.1.127_1 SDL2-devel-2.0.10_1 gmp-devel-6.1.2_1 
  gmsh-4.4.1_1 
54 packages will be installed:
  blas-devel-3.8.0_2 lapack-devel-3.8.0_2 alsa-lib-devel-1.2.1_1 
  expat-devel-2.2.9_1 dbus-devel-1.12.16_1 eudev-libudev-devel-3.2.9_1 
  libusb-devel-1.0.23_1 libusb-compat-0.1.5_7 
  libusb-compat-devel-0.1.5_7 libogg-devel-1.3.4_1 
  libvorbis-devel-1.3.6_4 libflac-devel-1.3.3_1 sqlite-devel-3.30.1_1 
  libsndfile-devel-1.0.28_3 fftw-devel-3.3.8_2 
  libsamplerate-devel-0.1.9_1 xorgproto-2019.2_1 
  libxshmfence-devel-1.3_2 xtrans-1.4.0_1 xcb-proto-1.13_2 
  libXdmcp-devel-1.1.3_1 libXau-devel-1.0.9_1 libxcb-devel-1.13.1_2 
  libX11-devel-1.6.9_1 libXext-devel-1.3.4_1 libXxf86vm-devel-1.1.4_3 
  libXfixes-devel-5.0.3_3 libXdamage-devel-1.1.5_1 
  libpciaccess-devel-0.16_1 libdrm-devel-2.4.100_1 libOSMesa-19.2.5_1 
  MesaLib-devel-19.2.5_1 glu-devel-9.0.1_1 libasyncns-devel-0.8_9 
  libXi-devel-1.7.10_1 libXtst-devel-1.2.3_2 pulseaudio-devel-13.0_1 
  sndio-devel-1.6.0_1 libxkbcommon-devel-0.9.1_1 wayland-devel-1.17.0_1 
  wayland-protocols-1.18_1 libuuid-devel-2.34_4 libICE-devel-1.0.10_2 
  libSM-devel-1.2.3_1 libXcursor-devel-1.2.0_1 libXinerama-devel-1.1.4_1 
  libXScrnSaver-devel-1.2.3_1 libXrender-devel-0.9.10_2 
  libXrandr-devel-1.5.2_1 Vulkan-Headers-1.1.127_1 
  vulkan-loader-1.1.127_1 SDL2-devel-2.0.10_1 gmp-devel-6.1.2_1 
  gmsh-4.4.1_1 

Size to download:               18MB
Size required on disk:         108MB
Space available on disk:       440GB

### Steps to reproduce the behavior
Try to "xbps-install gmsh" on a system without -devel libraries

**Comment by ndowens** [comment]
hostmakedepends="gcc-fortran blas-devel lapack-devel SDL2-devel
 $(vopt_if mesh 'hdf5-devel fltk-devel') gmp-devel"
depends="python blas-devel lapack-devel SDL2-devel
 $(vopt_if mesh 'hdf5-devel fltk-devel') gmp-devel"

Seems gmsh doesn't directly depend on many -devel packages, but indirectly from the others pulls in more.

**Comment by ndowens** [comment]
Ok seems I can for now get rid of the FORTRAN dep, as cmake file says if blas or lapack is not found then we need FORTRAN.

**Comment by ndowens** [comment]
I’ve removed dependence on FORTRAN which might reduce by small amount.

**Comment by scaramacai** [comment]
Still I cannot understand why should I install, for example, pulseaudio-devel to have gmsh working???

**Comment by ndowens** [comment]
I understand but they are indirect dependencies

**Comment by ndowens** [comment]
@scaramacai This new PR should solve the large dependencies.

**Comment by scaramacai** [comment]
Thank you. I'll check as soon as it is available in the repository.

**Comment by scaramacai** [comment]
After a quick read to the xbps-src manual I suggest you try changing
_depends=..._ to _makedepends=..._

**Comment by ndowens** [comment]
Looks like they need to be in depends possibly as it has linkage to what is in depends

**Comment by scaramacai** [comment]
Unfortunately I have no access to a Void box, these day. However this patch sounds good. I'll check it asap. Thank you very much

**Comment by xtraeme** [comment]
I tested this myself, by checking some examples/demos. Let me know if something does not work!
