### ISSUE TITLE
Conflicting /usr/include/dwarf.h

### ISSUE THREAD

**Issue by phf** [void-linux/void-packages#17130]
### System

* xuname:  
  Void 5.3.14_1 x86_64 GenuineIntel/KVM uptodate rFF
* package:  
  libdwarf-devel-20191104_1
  elfutils-devel-0.176_1

### Expected behavior

One or the other package owns /usr/include/dwarf.h

### Actual behavior

Both own /usr/include/dwarf.h and install over each other without warning

### Steps to reproduce the behavior

[root@void ~]# xbps-pkgdb -a
ERROR: libdwarf-devel: hash mismatch for /usr/include/dwarf.h.
ERROR: libdwarf-devel: files check FAILED.
[root@void ~]# xbps-install -f libdwarf-devel

Name           Action    Version           New version            Download size
libdwarf-devel reinstall 20191104_1        20191104_1             -

Size required on disk:        1099KB
Space available on disk:        17GB

Do you want to continue? [Y/n] y

[*] Verifying package integrity
libdwarf-devel-20191104_1: verifying RSA signature...

[*] Collecting package files
libdwarf-devel-20191104_1: collecting files...
libdwarf-devel-20191104_1: collecting files...

[*] Unpacking packages
libdwarf-devel-20191104_1: unpacking ...

[*] Configuring unpacked packages
libdwarf-devel-20191104_1: configuring ...
libdwarf-devel-20191104_1: installed successfully.

0 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.
[root@void ~]# xbps-pkgdb -a
ERROR: elfutils-devel: hash mismatch for /usr/include/dwarf.h.
ERROR: elfutils-devel: files check FAILED.
[root@void ~]# xbps-install -f elfutils-devel

Name           Action    Version           New version            Download size
elfutils-devel reinstall 0.176_1           0.176_1                -

Size required on disk:        1408KB
Space available on disk:        17GB

Do you want to continue? [Y/n] y

[*] Verifying package integrity
elfutils-devel-0.176_1: verifying RSA signature...

[*] Collecting package files
elfutils-devel-0.176_1: collecting files...
elfutils-devel-0.176_1: collecting files...

[*] Unpacking packages
elfutils-devel-0.176_1: unpacking ...

[*] Configuring unpacked packages
elfutils-devel-0.176_1: configuring ...
elfutils-devel-0.176_1: installed successfully.

0 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.
[root@void ~]# xbps-pkgdb -a
ERROR: libdwarf-devel: hash mismatch for /usr/include/dwarf.h.
ERROR: libdwarf-devel: files check FAILED.

**Comment by ndowens** [comment]
Verified this happens to me as well.
