### ISSUE TITLE
LLVM: undefined symbol: _ZN4llvm23EnableABIBreakingChecksE

### ISSUE THREAD

**Issue by tzoz** [void-linux/void-packages#17155]
### System
Void 5.3.11_1 x86_64 GenuineIntel uptodate rrFFFFFFFFFFF

Package(s):
llvm
libllvm9

### Problem
Certain programs linking with LLVM require this symbol. It appears that due to the way LLVM is built that this symbol cannot be linked for use with these programs. Is there any insight as to why this is the case?

**Comment by xtraeme** [comment]
is this still an issue? can you reproduce it?

**Comment by ericonr** [comment]
Hi there! Could you please check if this still happens with `llvm10`?

**Comment by tzoz** [comment]
I believe this was fixed some time ago with the `llvm9` package. I'll report back if I still encounter this issue.

**Comment by ericonr** [comment]
Cool! If you can verify that it isn't happening anymore, please close the issue then c:
