### ISSUE TITLE
Puppet binary fails to run

### ISSUE THREAD

**Issue by kotoko** [void-linux/void-packages#17162]
I can not make puppet work. I want to create small, simple `*.pp` file and run `puppet apply`.

### System
* xuname:  `Void 4.14.157_1 x86_64 GenuineIntel uptodate rFFF`
* package:  `puppet-6.11.1_1`

### Expected behavior
Puppet binary works. Puppet commands do something.

### Actual behavior
Puppet binary always returns error: `cannot load such file -- concurrent`.

### Steps to reproduce the behavior
```
sudo -su root
xbps-install puppet
cd /usr/lib/ruby/vendor_ruby/../../..//lib
ln -s libfacter.so.3.14.5 libfacter.so
puppet help
```
Output:
```
cannot load such file -- concurrent
```

**Comment by ndowens** [comment]
Looking into fixing this

**Comment by kotoko** [comment]
Finally I have some free time to check. It works now. Thanks!
