### ISSUE TITLE
Firefox 71 breaks various extensions

### ISSUE THREAD

**Issue by q66** [void-linux/void-packages#17201]
Upstream issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1601424

Cause is a gcc miscompilation, see https://bugzilla.mozilla.org/show_bug.cgi?id=1601707

There is no patch for this yet. The workarounds in second link are for something else, see last comment ("Thanks. I think dom/localstorage/ActorsParent.cpp needs also some care to get extensions working.")

**Comment by LinArcX** [comment]
Seems fixed in Firefox 71.0.2
