### ISSUE TITLE
Update broken - libglapi-32bit-19.2.7_1 (update) breaks installed pkg `libGL-32bit-19.2.5_1'

### ISSUE THREAD

**Issue by edn9** [void-linux/void-packages#17220]
### System

* xuname:  
> libglapi-32bit-19.2.7_1 (update) breaks installed pkg `libGL-32bit-19.2.5_1'
> Transaction aborted due to unresolved dependencies.
> Void 5.3.14_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFF

* package:  
> libglapi-32bit-19.2.7_1 (update) breaks installed pkg `libGL-32bit-19.2.5_1'

### Expected behavior
Update my system.
### Actual behavior
> libglapi-32bit-19.2.7_1 (update) breaks installed pkg `libGL-32bit-19.2.5_1'
### Steps to reproduce the behavior
> sudo xbps-install -Suvy

### More info:
https://pastebin.com/2fJesRJe

**Comment by xtraeme** [comment]
Please run `xbps-install -und 2>&1|wgetpaste -s bpaste` to see details

**Comment by xtraeme** [comment]
Looks like the `bpaste` service is down or whatever, use another service in `wgetpaste`

**Comment by xtraeme** [comment]
https://github.com/void-linux/void-packages/commit/927f17347f9c646047c65312c8e8ce1ad88b7832

**Comment by xtraeme** [comment]
wait until mesa is rebuilt again, and then let's see if it's fixed.

**Comment by st3r4g** [comment]
@xtraeme does the fix also pull in `mesa-32bit`? It's required for everything working properly.

**Comment by xtraeme** [comment]
@st3r4g 

```
[juan@leysa void-packages]$ xbps-query -RX mesa
mesa-ati-dri-19.2.7_1
mesa-intel-dri-19.2.7_1
mesa-nouveau-dri-19.2.7_1
mesa-opencl-19.2.7_1
mesa-vmwgfx-dri-19.2.7_1
[juan@leysa void-packages]$
```

**Comment by xtraeme** [comment]
Ok, new mesa is ready. A simple `xbps-install -Suv` should work now.

**Comment by xtraeme** [comment]
This should be fixed now. Please speak up

**Comment by st3r4g** [comment]
> ```
> [juan@leysa void-packages]$ xbps-query -RX mesa
> mesa-ati-dri-19.2.7_1
> mesa-intel-dri-19.2.7_1
> mesa-nouveau-dri-19.2.7_1
> mesa-opencl-19.2.7_1
> mesa-vmwgfx-dri-19.2.7_1
> [juan@leysa void-packages]$
> ```

hmm maybe those users who needed to manually install `mesa-lib32` too didn't have any dri drivers installed?

**Comment by xtraeme** [comment]
@st3r4g the mesa pkg didn't exist before so it's unlikely that there's a name conflict.

**Comment by xtraeme** [comment]
@st3r4g and I didn't rename `MesaLib-devel` because we would have to rebuild lots of packages due to dependencies in -devel pkgs... you know

**Comment by xtraeme** [comment]
@st3r4g that's why I've used "virtual pkgs"

**Comment by Bridouz** [comment]
Fixed for me.

**Comment by xtraeme** [comment]
thanks for reporting, cheers

**Comment by st3r4g** [comment]
@xtraeme I think we must also remove libGL, libEGL and libGLES from remote repo index otherwise new installs and builds involving GL are broken

**Comment by st3r4g** [comment]
because the presence of a real libGL breaks the virtual pkg mechanism, it is preferred over the new libglvnd provider

**Comment by st3r4g** [comment]
```
[stefano@NUC ~]<0>$ xbps-query -Rs 'libE?GL' --regex
[-] libEGL-19.2.5_1            Free implementation of the EGL API - runtime
[-] libGL-19.2.5_1             Graphics library similar to SGI's OpenGL
[-] libGLES-19.2.5_1           Free implementation of the OpenGL|ES 1.x and 2.x API
```
packages which depend e.g. on libGL find the real package before the libglvnd provider

**Comment by edn9** [comment]
@xtraeme so, this command `xbps-install -und 2>&1|wgetpaste -s bpaste` did not work and I have no idea "use another service" mean. I removed the `mesa-intel-dri` and then I was able to update my system, thank you for your service.

**Comment by st3r4g** [comment]
the problem of libGL, libEGL and libGLES still on remote repo index is being worked on.
