### ISSUE TITLE
Bug: cli-visualizer immediately aborts upon being started.

### ISSUE THREAD

**Issue by haydenhv** [void-linux/void-packages#17222]
### System
* xuname:  
  * Void 5.3.14_1 x86_64-musl GenuineIntel uptodate rF
* package:  
  * cli-visualizer

### Expected behavior
The program should start and act as a visualizer using ncurses.

### Actual behavior
The program immediately aborts open being called by the shell, idependantly of any configuration files (tried with and without).
fish-shells' output: `fish: “cli-visualizer” terminated by signal SIGABRT (Abort)`
bash's output: `Aborted`

### Steps to reproduce the behavior
1. Install the program with xbps-install.
2. Open a terminal emulator.
3. Start the program by executing cli-visualizer.

**Comment by ndowens** [comment]
Do you have ncurses-devel installed?

**Comment by bertronika** [comment]
I've experienced the same problem. The solution was compiling the package with xbps-src and manually installing it. Haven't altered any build files.

**Comment by haydenhv** [comment]
@ndowens 
Yes, I have ncurses-devel installed

**Comment by q66** [comment]
Try running it with `LC_ALL=C`. I tried to trace it and it has to do with a locale-related thrown C++ exception.

**Comment by haydenhv** [comment]
Yep, LC_ALL=C does the trick.
