### ISSUE TITLE
firefox fails to play music on soundcloud

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#17236]
### System

* xuname:  Void 5.3.14_1 x86_64 GenuineIntel uptodate rrrdFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

* package:  firefox-71.0_1

### Expected behavior

Play a song.

### Actual behavior

Song loads, but never plays.

### Steps to reproduce the behavior

Try to play any song. This is with a fresh profile, ublock and umatrix disabled, and tracking protections disabled.

**Comment by Anachron** [comment]
FF71 has general sound issues which I reported here: https://github.com/void-linux/void-packages/issues/17142

(I first thought it was video related)

**Comment by CameronNemo** [comment]
Issues seem to be clear in 71.0_2
