### ISSUE TITLE
nvidia340 broken, unresolvable shlib `libnvidia-ml.so.1'

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#17251]
### System

* xuname:  
Void 5.3.12_1 i686 GenuineIntel uptodate rrDDFFF
* package:  
  - nvidia340-340.107_6

### Expected behavior
Being able to update the system

### Actual behavior
The system update fails with the error mentioned above. I manually updated all nvidia340-* packages to the current revision.
### Steps to reproduce the behavior
1. Install nvidia340
2. Try to update the system

If I manually remove the nvidia340 package and try to update, xbps wants to remove nvidia340-libs and install libglvnd instead. Since nvidia340 does not support glvnd, I don't want that. libnvidia-ml.so.1 is in fact listed in the shlib_provides of the nvidia340-libs package so xbps should be able to resolve it.

**Comment by xtraeme** [comment]
Please provide the output of xbps-install und

**Comment by st3r4g** [comment]
I think we should add `replaces="libglvnd"` in the template.

**Comment by Hoshpak** [comment]
https://gist.github.com/Hoshpak/edfcebb8270099f9c68ea4886ca73f0a

**Comment by xtraeme** [comment]
nvidia340-libs should provide/replace libGL/GLES/EGL instead

**Comment by xtraeme** [comment]
I see. Ilibglvnd is added indirectly via libEGL.so hmmm.

**Comment by xtraeme** [comment]
How come that you've got Mesa and nvidia340?

**Comment by xtraeme** [comment]
nvidia340 does not support glvnd. So that it still needs to replace those libs and libglx in xorg-server

**Comment by xtraeme** [comment]
That wasn't handled in my branch because I couldn't test... Next time let me know :)

**Comment by xtraeme** [comment]
That's why Arch removed nvidia340...

**Comment by st3r4g** [comment]
also I don't know why `nvidia340` doesn't currently install it's own libEGL and libGLES, it should.

**Comment by st3r4g** [comment]
so it can be a provider of all three.

**Comment by xtraeme** [comment]
Because this version does not support EGL/GLES AFAIK

**Comment by xtraeme** [comment]
If it does then the pkg needs to be fixed

**Comment by st3r4g** [comment]
are you sure? I checked and the files were there.

**Comment by xtraeme** [comment]
Cool. So we know now how to fix it

**Comment by xtraeme** [comment]
Please be my guest. I'm on phone

**Comment by st3r4g** [comment]
```
-rwxr-xr-x  1 stefano stefano 965K May 25  2018 libEGL.so.340.107
-rw-r--r--  1 stefano stefano  654 May 25  2018 libGL.la
-rwxr-xr-x  1 stefano stefano 1.3M May 25  2018 libGL.so.340.107
-rwxr-xr-x  1 stefano stefano  47K May 25  2018 libGLESv1_CM.so.340.107
-rwxr-xr-x  1 stefano stefano  61K May 25  2018 libGLESv2.so.340.107
```

**Comment by xtraeme** [comment]
Great. So please do this: update provides/replaces and install them

**Comment by xtraeme** [comment]
This still won't work because libglx.so in xorg-server needs to be replaced...

**Comment by st3r4g** [comment]
We need to put it in another folder and override ModulePath as in nvidia390

**Comment by xtraeme** [comment]
Sounds good 👌

**Comment by st3r4g** [comment]
@Hoshpak the kernel driver's exact name is just "nvidia", right?

**Comment by Hoshpak** [comment]
Yes

**Comment by st3r4g** [comment]
My PR won't automatically solve the issue, it will still be required to do the following:
```
sudo xbps-remove nvidia340 # Allows libglvnd to be installed
sudo xbps-install -Su
sudo xbps-install nvidia340
```
