### ISSUE TITLE
vpm package

### ISSUE THREAD

**Issue by jjzmajic** [void-linux/void-packages#17273]
Ahoy maintainers! Just switched to your wonderful distro, and [vpm](https://github.com/netzverweigerer/vpm) has been helping a lot in the transition.

I'd like to make my first little contribution by packaging it, but first I wanted to make sure it would fall within the project guidelines.

I think vpm really helps. It's sort of like apt for apt-get, apt-cache, etc. It's really noob friendly, and a great addition to void packages imho. But I also understand if you do not want to endorse 3rd party wrappers. Kind of how Arch does not support AUR helpers in its repos. Or perhaps you're going the Debian route and wish to make an official wrapper.

Would you be willing to accept a vpm PR?

Thanks again for this wonderful distro. Using it felt like I was switching from Windows again. A breath of fresh *nix.

PS: I really hope an official wrapper is in the stars for void; xbps is really intuitive for long-time pacman users, but it's kind of verbose to type, and seems to confuse those from single-command package managers like zypper for example, at least based on the slant.com "cons", and most of the YouTube reviews I've seen. Something like what git does with subcommands actually being different commands entirely, to which git dispatches arguments would ease a lot of the confusion I feel. And the shortest unambiguous acronym situation cuts down on a lot of the typing.

**Comment by ndowens** [comment]
I am no maintainer but I don’t see why it would be an issue IMO. Especially since we have apt/dpkg/portage/nix in repo

**Comment by axm2** [comment]
@netzverweigerer mentioned he would be open to maintaining. Maybe talk to him before you open a pr
https://github.com/netzverweigerer/vpm/issues/4

**Comment by jjzmajic** [comment]
@axm2 thanks for letting me know! I'll reach out

**Comment by netzverweigerer** [comment]
Hi there, I was on vacation hence took me some time to keep track here. Super happy to see so much interest in vpm. @jjzmajic We should get in touch. :-)

**Comment by xtraeme** [comment]
#19231
