### ISSUE TITLE
gvfs-32bit depends on old libgpgme-32bit

### ISSUE THREAD

**Issue by sunnaryt** [void-linux/void-packages#17292]
### System

* xuname:  
Void 5.3.15_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFF
* package:  
gvfs-32bit-1.42.2_1

### Expected behavior
install
### Actual behavior
unresolvable dependency
### Steps to reproduce the behavior
try to install gvfs-32bit

gvfs-32bit-1.42.2_1 depends on libgpgme-32bit-1.13.1_1, but the latest is libgpgme-32bit-1.13.1_2, so the dependency isn't resolved and the package is uninstallable 

@Gottox

**Comment by ericonr** [comment]
I think the `gvfs` package should be completely disabled for multilib stuff, maybe.
