### ISSUE TITLE
Package request: Cal/Carddav Server

### ISSUE THREAD

**Issue by teldra** [void-linux/void-packages#1729]
https://github.com/jelmer/xandikos
https://www.davical.org/installation.php
https://github.com/sabre-io/Baikal
one of this maybe?

**Comment by Duncaen** [comment]
Maybe https://kristaps.bsd.lv/kcaldav/

**Comment by CameronNemo** [comment]
`radicale` is already packaged!

**Comment by teldra** [comment]
Since there is radicale, which seems to be lightweight, i close this issue.
