### ISSUE TITLE
FTBFS: cargo

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#17339]
`cargo` fails to build because the shipped version of libgit2-sys is `0.10.2` now and our patched `0.9.1` does no longer work. I was not able to fix the template to use the shipped version instead.

**Comment by pullmoll** [comment]
Now I could build cargo after updating `_libgit2_ver=0.9.2` and changing the 2nd checksum to `61e1329785a2957721b28ec7d13c22749553f67179d7dde8e5793c4872eec48a`. Since I am not sure this is all that's required I am not going to push this as an update but leave it to the knowing @void-linux/pkg-committers .

**Comment by q66** [comment]
That's weird, because we pin libgit2-sys to the precise version.
