### ISSUE TITLE
sddm and Consolekit

### ISSUE THREAD

**Issue by Hoshpak** [void-linux/void-packages#1742]
continuation of https://github.com/voidlinux/void-packages/issues/8048

@the-maldridge since you fell victim to a netsplit on freenode before I could reply, here are my current findings:

sddm-0.18.0 still doesn't work with ConsoleKit2 out of the box. It correctly detects the ConsoleKit interface but then the process stalls until it is terminated without any error messages, the DM is not launched.

I had more luck after trying to compile sddm with the changes proposed in https://github.com/sddm/sddm/pull/923 . The patched sddm binary sucessfully launches with ConsoleKit2 running and elogind absent. The shutdown and reboot buttons in sddm work and I can launch a lxqt session from sddm. I don't know if there's any other functionality to test for ConsoleKit. With these patches, sddm-0.18.0 works more or less the same way 0.15.0 did before.

**Comment by the-maldridge** [comment]
I'm assuming you're referring to 0.15.0_3 and 0.18.0 here?

**Comment by Hoshpak** [comment]
indeed.

**Comment by the-maldridge** [comment]
Well it looks like the best case is still waiting another 6 months for sddm to get around to making a release with the fix in it.  They aren't particularly fast about pushing releases.

**Comment by CameronNemo** [comment]
hmm where are we at with this. AFAIK sddm now uses elogind only.

**Comment by the-maldridge** [comment]
wow this has been sitting for quite a long time.  I've completely lost state on this, care to fill me on on your thoughts @CameronNemo ?

**Comment by obunden** [comment]
Looks like alpine linux is using it with only elogind so we should be able to do it also? Since ConsoleKit isn't maintained anymore it is the right way to go I guess?

https://git.alpinelinux.org/aports/tree/community/sddm/APKBUILD

**Comment by the-maldridge** [comment]
Sounds like it should be fine, just needs to actually be done.

**Comment by Hoshpak** [comment]
Indeed, if they just removed the broken Consolekit detection that would be great. The status quo of our sddm package is that it only works with elogind but does not break completely when ConsoleKit2 is present but just ignores it instead.

**Comment by the-maldridge** [comment]
What do you think about making it conflict with ConsoleKit2?  It doesn't really, but would fix this problem to a degree.  My understanding is that ConsoleKit2 is also abandoned.

**Comment by Hoshpak** [comment]
I think conflicts should be reserved for cases where there is an actual conflict, not just software that doesn't work well with each other. However since sddm also has other issues and I switched to lxdm a long time ago, I pretty much don't care about the package anymore.

**Comment by Piraty** [comment]
Closing, as ConsoleKit2 is obsolete (#13474)
