### ISSUE TITLE
`libcrypto45` dependency error blocks builds (e.g. dmenu, st, i3status)

### ISSUE THREAD

**Issue by wngrtn** [void-linux/void-packages#17498]
### System

* xuname:  
  Void 5.3.16_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFF
* packages:  
  probably a general issue, tried: dmenu-4.9, st-0.8.2, i3status-2.13

### Expected behavior

`./xbps-src pkg dmenu` should run without problems.

### Actual behavior

All three packages above fail to build with the same dependency error:

```
libcrypto45-3.0.2_1 (update) breaks installed pkg `libressl-2.9.2_1'
libcrypto45-3.0.2_1 (update) breaks installed pkg `libtls19-2.9.2_1'
libssl47-3.0.2_1 (update) breaks installed pkg `libressl-2.9.2_1'
libssl47-3.0.2_1 (update) breaks installed pkg `libtls19-2.9.2_1'
```

I only get this behaviour on one of my two machines. Both are up-to-date x64 systems.

### Steps to reproduce the behavior

Change to `void-packages` root dir, then:

```
./xbps-src pkg dmenu
```

**Comment by ndowens** [comment]
Mine does not do this. Make sure you do ./xbps-src bootstrap-update

**Comment by wngrtn** [comment]
`./xbps-src bootstrap-update` did it. Thanks!

I am relatively new to Void and I hadn't come across it in the documentation.
