### ISSUE TITLE
Plase consider pango downgrade

### ISSUE THREAD

**Issue by jfriesse** [void-linux/void-packages#17595]
Pango 1.44 removed support for bitmap fonts in BDF/PCF format. Solution is to convert these fonts to OTB format, but results are not perfect (https://bugzilla.redhat.com/show_bug.cgi?id=1753295) and also there is no "standard" way how to make such conversion happen. For example helvetica converted using `fonttosfnt` gets monospaced and `fontforge` result has weird spacing too.

Issue is about ether downgrade package or create new package (something like pango142) until ether:
- harfbuzz gets support for BDF/PCF
- proper way is found how to convert PCF/BDF into OTB and standard X fonts are shipped in OTB format

Of course I could lock package from upgrading, but I would rather like to see some longer term solution.

**Comment by pullmoll** [comment]
I updated `fonttosfnt` with the upstream patches after 1.0.5 at least.
This makes at least the following commands
```
/usr/share/fonts/X11/misc/ $ fonttosfnt -b -o terminusn.otb ter-*n.pcf.gz
/usr/share/fonts/X11/misc/ $ fonttosfnt -b -o terminusb.otb ter-*b.pcf.gz
mkdir /usr/share/fonts/terminus-otb
mv terminus*.otb /usr/share/fonts/terminus-otb/
mkfontdir /usr/share/fonts/terminus-otb
```
work for me.

**Comment by jfriesse** [comment]
@pullmoll Thanks for comment. I've tried following:
```
$ fonttosfnt -b -o helvo.otb helvO*bdf
$ fonttosfnt -b -o helvb.otb helvB*bdf
$ fonttosfnt -b -o helvr.otb helvR*bdf
```

And then changed `/etc/fonts/fonts.conf` to point only to directory with `helv*.otb` files. Attached is result. 
![helv-test](https://user-images.githubusercontent.com/733814/71102869-72635400-21b9-11ea-8953-3bfef245618c.png)

as you can see, helvetica gets monospaced, even with patches.

**Comment by pullmoll** [comment]
You could perhaps try with the `-m 2` parameter of `fonttosfnt`. It is not recommended according to `fonttosfnt(1)` man page while it may have to do with the resulting spacing?

**Comment by jfriesse** [comment]
@pullmoll Thank you for the hint. `-m 2` makes helvetica proportional, but spacing between letters is still pretty off.

1.44 with font converted:
![helv-144](https://user-images.githubusercontent.com/733814/71154179-3bce1d80-223b-11ea-8070-e8ba98031bd0.png)

and (for comparsion) 1.42 with pcf:
![helv-142](https://user-images.githubusercontent.com/733814/71154198-45f01c00-223b-11ea-9eb7-7edb8d5c5d13.png)

(right now I'm ignoring height which is incorrect, but that would be matter of taste. But width spacing is just off).

**Comment by pullmoll** [comment]
I see more packages failing to build due to the update of `pango-1.44.7`:
+ pangox-compat fails (I have a patch #17566 , but this is not well tested)
+ pygtk fails for similar reasons, i.e. long deprecated and now removed functions or structures

So I second to revert pango to a version prior to removal of the the bitmap font support.

**Comment by Duncaen** [comment]
I'm fine with downgrading, imho there is nothing that makes the new version desirable at the moment and we could just for other distributions to come up with an acceptable solution.

**Comment by pullmoll** [comment]
Let's see if this solves the issues: https://github.com/void-linux/void-packages/commit/5c7ae8cb2b721501f436f4f4f803ead5bd233226

**Comment by jfriesse** [comment]
@pullmoll @Duncaen Thank you guys for quick resolution of the issue!
