### ISSUE TITLE
prometheus

### ISSUE THREAD

**Issue by i4o** [void-linux/void-packages#17599]
### System

* xuname:  
  * ``Void 5.3.15_1 x86_64 GenuineIntel uptodate rFF``*
* package:  
  *prometheus version 2.14.0*

### Expected behavior

Opening localhost:9090 is redirecting to `/graph` where it should show UI

### Actual behavior

error reading base template: open web/ui/templates/_base.html

### Steps to reproduce the behavior

 * `xbps-install prometheus`
 * use browser to open GUI of prometheus on <EXTERNAL_IP>:9090

`prometheus` is build with embedded libraries and version info. `xbps-install`-ed build is missing version info or build info  and embedded web/ui/templates ( probably embedded in original binary during build phase ). 

When I did replace package provided binary with downloaded prometheus binary from their [website](https://prometheus.io/download/) it fixed issue.

**Comment by xtraeme** [comment]
Assigned to the package maintainer

**Comment by Vaelatern** [comment]
fixed
