### ISSUE TITLE
libxml/xmlversion.h: No such file or directory

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#17611]
### System

* xuname:  
`dmesg: read kernel buffer failed: Operation not permitted
Void 5.3.8_2 x86_64 GenuineIntel notuptodate rrDDDFFF`
* package:  
 `libxml2-devel`

### Expected behavior
Compile project that use `libxml2-devel` correctly.

### Actual behavior
Can't find header files when i want to build my sample project.

### Steps to reproduce the behavior
Hi. i'm trying to create a crawler using `curlpp` and `libxml`. This is my project:
https://github.com/LinArcX/mgr

Tip 1: you have to install `cmake`, `curlpp-devel`, `libxml++-devel` and `libxml2-devel`, then compile the project with cmake.

Tip 2: This is my cmake output: https://gist.github.com/LinArcX/6f3fd0b0f0383661541e45f9231a2617

**Comment by ndowens** [comment]
Use FLAG=-I/usr/include/libxml2

**Comment by ndowens** [comment]
Install xtools that way you can use xlocate to find files

**Comment by LinArcX** [comment]
Yeah, i know about that. thank you.
