### ISSUE TITLE
liblldb.so present in lldb-devel and missing from shlibs

### ISSUE THREAD

**Issue by asiekierka** [void-linux/void-packages#17649]
Affects lldb/lldb-devel 9.0.0_4.

It appears liblldb.so is missing from common/shlibs, while being necessary for packaging of intellij-idea-community-edition 2019.3+. Oddly, it is present in the "lldb-devel" package, while liblldb.so.9 and liblldb.so.9.0.0 are present in "lldb" - made more curious by the fact the Python library symlink in "lldb" points to and expects liblldb.so. I'm not the maintainer, but I think that specific symlink should be in the "lldb" package (as opposed to "lldb-devel") and mentioned in the common/shlibs list.

**Comment by pullmoll** [comment]
Not oddly, but intentionally `*.so`  symbolic links are (always) in the `*-devel` packages.
When building a project which depends on e.g. `liblldb.so` the symbolic links is resolved and the actual linking is against the link's target. By looking at `common/shlibs` and finding e.g. `liblldb.so.9 lldb-devel-9.0.0_4` then `xbps-src` knows what library to depend on.

When building `intellij-idea-community-edition-2019.3+` a `makedepends` which contains `lldb-devel` should work this way and the resulting binary should depend on `/usr/lib/liblldb.so.9` not on `/usr/lib/liblldb.so`.

**Comment by asiekierka** [comment]
The problem is, the IDEA package (as well as PyCharm) is built based on JetBrains' binary release, not the source code repository. As most of it is Java code, there is little reason to build from source - except for those specific, small binaries used by specific parts of functionality.

**Comment by ericonr** [comment]
The package has been updated multiple times already, so I believe thsi has been fully solved.
