### ISSUE TITLE
supertux2: cannot start levels

### ISSUE THREAD

**Issue by VoidDuck** [void-linux/void-packages#17655]
Since a recent update, supertux levels refuse to start. The menu and level maps work fine, but when you press Enter to start a level, nothing happens.

### System
* xuname:  
  *Void 5.3.18_1 x86_64 GenuineIntel uptodate rrFF*
* package:  
  *supertux2-0.6.1_1*

**Comment by PaperMountainStudio** [comment]
I can not replicate this.

**Comment by VoidDuck** [comment]
I deleted ~/local/share/supertux2 and it works now. It seems like the update from 0.6.0 to 0.6.1 has broken some compatibility.

**Comment by xtraeme** [comment]
upstream issue
