### ISSUE TITLE
gotop needs dependancys

### ISSUE THREAD

**Issue by bgkillas** [void-linux/void-packages#17673]
make so gotop installs what ever font it needs to actually handle the graph
![image](https://user-images.githubusercontent.com/55570525/71301711-e431ce00-2370-11ea-804c-fae68769b4fd.png)

**Comment by PaperMountainStudio** [comment]
Even if gotop had a font dependency, we can not make sure it is used in the terminal emulator. I think dependency like this would be pointless. What is the font you are using? It looks like dejavu which works for me.

**Comment by bgkillas** [comment]
o it could be a terminal error weird
