### ISSUE TITLE
kiwix-tools: kiwix-serve doesn't work

### ISSUE THREAD

**Issue by PaperMountainStudio** [void-linux/void-packages#17686]
### System

* xuname: 
Void 5.4.5_1 x86_64-musl GenuineIntel uptodate rrnDFFFFFFF
* package:  
kiwix-tools-3.0.1_3

### Expected behavior
`kiwix-serve` serves the wiki

### Actual behavior
```sh
$ kiwix-serve
Error relocating /bin/kiwix-serve: _ZN5kiwix5splitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKc: symbol not found
$
```
### Steps to reproduce the behavior
1. install `kiwix-tools`
2. run `kiwix-serve`

this is not a musl specific issue, I tried it on a glibc machine and the error is still there

**Comment by Johnnynator** [comment]
https://github.com/void-linux/void-packages/commit/0569541c01097c973b45b020c0eec867915d7b60

**Comment by PaperMountainStudio** [comment]
thanks :+1:
