### ISSUE TITLE
nvidia-libs missed libGL.

### ISSUE THREAD

**Issue by kasymovga** [void-linux/void-packages#17681]
### System

* xuname:  
  Void 5.3.18_1 x86_64 AuthenticAMD uptodate rrrrmmnFFFFFFF
* package:  
  nvidia

### Expected behavior
Working 3D acceleration with libGL provided from nvidia driver.

### Actual behavior
Broken 3D acceleration with libGL provided from mesa package.

### Steps to reproduce the behavior
Buy nvidia card, install nvidia driver.

**Comment by xtraeme** [comment]
Need more info

**Comment by kasymovga** [comment]
which exactly info you need?

**Comment by kasymovga** [comment]
actually it looks like /usr/lib/libGL.so is libglvnd file. anyway when i run opengl application they get mesa software opengl instead of nvidia

**Comment by kasymovga** [comment]
and there is no any libGL provided by nvidia-libs

**Comment by kasymovga** [comment]
I think it was broken here: https://github.com/void-linux/void-packages/commit/fe7dd52d82923bc19852eae675317f7477e27ec7

**Comment by xtraeme** [comment]
It's not broken. More info of what fails. This is the guay making and testing those changes. So I'm sure its not broken.

**Comment by kasymovga** [comment]
GL_VENDOR: VMware, Inc.
GL_RENDERER: llvmpipe (LLVM 9.0, 128 bits)
GL_VERSION: 3.1 Mesa 19.2.7

This is what i get in opengl applications. Looks like completely broken. Also nvidia-libs missed libGL.so files.

**Comment by xtraeme** [comment]
Something is wrong in your system. xbps-pkgdb is your friend
