### ISSUE TITLE
kubernetes-helm: update to 3.0.2.

### ISSUE THREAD

**Issue by mar1n3r0** [void-linux/void-packages#17729]
Trying to update helm to latest stable and facing unexpected difficulties:

`=> python-2.7.16_2: installing host dependencies: pkg-config-0.29.2_2 ...
=> python-2.7.16_2: installing target dependencies: libffi-devel-3.2.1_6 readline-devel-8.0.001_1 gdbm-devel-1.18.1_1 libressl-devel-2.9.2_1 expat-devel-2.2.9_1 sqlite-devel-3.30.1_1 bzip2-devel-1.0.8_1 zlib-devel-1.2.11_3 ...
=> python-2.7.16_2: removing autodeps, please wait...
=> ERROR: python-2.7.16_2: failed to install 'libffi-devel-3.2.1_6' dependency! (error 19)
libcrypto45-2.9.2_1 (update) breaks installed pkg `libarchive-3.4.0_2'
libcrypto45-2.9.2_1 (update) breaks installed pkg `libressl-3.0.2_1'
libssl47-2.9.2_1 (update) breaks installed pkg `libressl-3.0.2_1'
libtls19-2.9.2_1 (update) breaks installed pkg `libressl-3.0.2_1'
Transaction aborted due to unresolved dependencies.
=> ERROR: Please see above for the real error, exiting...
`

Seems related to this one:
#11959

> update your masterdir and try again:

> ./xbps-src remove-autodeps

> ./xbps-src bootstrap-update

> it looks like libressl in the chroot is one version behind but the build dependencies it's trying to install depend on the latest one

> xbps doesn't update packages to satisfy dependencies like that so it trips on itself here

Any ideas what else can be tried to proceed building ?

**Comment by ndowens** [comment]
Are you building from xbps-src or installing from xbps-install ?

**Comment by mar1n3r0** [comment]
> Are you building from xbps-src or installing from xbps-install ?

Building from xbps-src

**Comment by ndowens** [comment]
Updating ./xbps-src bootstrap-update should fix that

**Comment by mar1n3r0** [comment]
Yeah actually having tried it again the issue has gone away replaced by the issue reported by Travis CI: #17736 
```
=> ERROR: kubernetes-helm-3.0.2_1: do_build: 'TARGETS="linux/${_go_target_arch} linux/${_go_host_arch}" make bootstrap build-cross APP="..." LDFLAGS="-X k8s.io/helm/pkg/version.Version=v${version} -X k8s.io/helm/pkg/version.BuildMetadata="' exited with 2
=> ERROR:   in do_build() at srcpkgs/kubernetes-helm/template:54
```

**Comment by ndowens** [comment]
It doesn’t do this on other builds? I’d just nuke it and do a clean
bootstrap if it was me to see if that helped

**Comment by mar1n3r0** [comment]
Haven't tested with other builds. What do you mean by "clean" bootstrap ?

**Comment by mar1n3r0** [comment]
@knusbaum would you mind taking a look since you seem to have quite a lot of builds of this package behind your back ?

**Comment by knusbaum** [comment]
I ran into issues building 3.0 out of the box. They've changed some things between 2 and 3, so my assessment was that the template likely needed some significant changes.

I haven't taken the time to look closer yet, but I'll try and look into it some time this week or next.

**Comment by xtraeme** [comment]
[-] kubernetes-helm-3.1.0_1 Kubernetes Package Manager

please reopen if the issue still exists
