### ISSUE TITLE
Can not run sshguard as a service

### ISSUE THREAD

**Issue by kotoko** [void-linux/void-packages#17728]
### System

* xuname:  `Void 5.3.18_1 X86_64 GenuineIntel uptodate rFFF`
* packages:
  * `sshguard-2.4.0_1`
  * `openssh-8.1p1_1`
  * `socklog-2.1.0_5`

### Expected behavior
You can start sshguard service using `sv` command.

### Actual behavior
`sv` command times out and kills process.

### Steps to reproduce the behavior
Assuming you have already running ssh server. I am using socklog as logger.
```
$ xbps-install sshguard
$ ln -s /etc/sv/sshguard-socklog /var/service
$ sv up sshguard-socklog
timeout: down: sshguard-socklog: 1s, normally up, want up
```

### Comment
So it looks like sshguard is running as normal program without forking/going to background by itself. It is running as long as executable is executing. On the other hand `sv` expects that all commands end within few seconds or it fails. I did experiment and run as root `sshguard` and tested with failed login attempt to ssh server. It worked as expected (banned me). So it is just problem with running.

Second thing I noticed is that there is passed `-l` (small L) as parameter which is no longer supported. I think there is mandatory file `/etc/sshguard.conf` for configuration.

**Comment by xtraeme** [comment]
Sounds like it's forking

**Comment by CameronNemo** [comment]
From `/usr/bin/sshguard`:

```
eval $tailcmd | $libexec/sshg-parser | \
    $libexec/sshg-blocker $flags | $BACKEND &
```

does runit allow nesting log dirs within log dirs? if so you may be able to get runit to set those pipes up on your behalf.

**Comment by kotoko** [comment]
I fixed my problem. It turned out that `iptables` (service in runit) was not running. When deleted check for it from `/etc/sv/sshguuard-socklog/run`, sshguard run successfully. 

In my opinion the biggest fail was that runit did not show any useful information. I would expect to see some kind of tip that dependency was at fault here. Somehow check for iptables timed out?

You can close issue.

**Comment by kotoko** [comment]
I don't know if I'm right, but I guess that because runit does not have a concept of dependencies `iptables check` was waiting until service `iptables` is started.
