### ISSUE TITLE
Cyclic dependency

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#17751]
This one is problematic especially for `i686-musl` where there is no remote repo:
`curl` -> `nghttp2` -> `cmake` -> `curl`
Can be solved only by e.g. cross compiling `curl` for `i686-musl` from `x86_64-musl`.

**Comment by xtraeme** [comment]
we could use the internal curl in cmake as a workaround

**Comment by Johnnynator** [comment]
Doesn't nghttp2 also support a configure style build system instead of cmake?
