### ISSUE TITLE
Package Request: godot-mono

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#17767]
Hey! Godot has a C# enabled variant that uses mono. Currently on the Godot project site they are separate so I'd presume that separate packages would be the way to go. I have some prior experience with writing build scripts (`PKGBUILDs` and `ebuilds`), and I heard that Void is similar to Arch in some regard, so if you could point me to some documentation I'd also be willing to draft a pull request! Thanks.

**Comment by ndowens** [comment]
https://github.com/void-linux/void-packages/blob/master/Manual.md

**Comment by mustaqimM** [comment]
Is it not the same package but with [mono](https://docs.godotengine.org/en/stable/development/compiling/compiling_with_mono.html#doc-compiling-with-mono) support [enabled](https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_basics.html#setting-up-c-for-godot)? You need append the required flag among other things

**Comment by RoundDuckKira** [comment]
I may do something about this and bring in a package
