### ISSUE TITLE
Can't find cdk.h

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#17793]
Hello. i want to test a ncurses app that uses [cdk](https://invisible-island.net/cdk) internally:
https://github.com/lnkgyv/cdk_examples

But i can't find __cdk.h__:
```
╰ make           
gcc -o calendar calendar.c -lncurses -lcdk
In file included from calendar.c:1:
calendar.h:4:10: fatal error: cdk.h: No such file or directory
    4 | #include <cdk.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:11: calendar] Error 1
```
Also i didn't see any cdk package in void repo and i tried to look for this header file via `xlocate`:
`╰ xlocate cdk.h `

But it could not find anything.

**Comment by ndowens** [comment]
It's not in the repo, but you could package it or install it locally.

**Comment by LinArcX** [comment]
Ok. i'll create new issue and request a pckage for it.
