### ISSUE TITLE
KiCAD step 3D rendering

### ISSUE THREAD

**Issue by groundstack** [void-linux/void-packages#17818]
### System

* xuname:  
  Void 5.3.18_1 x86_64-musl GenuineIntel notuptodate rF
* package:  
  KiCAD

### Expected behavior
From PCBnew, pressing alt-3 should see a 3D view of the board with populated components, linked to individual step files.
### Actual behavior
Only displays bare PCB or board populated with WRL components.
### Steps to reproduce the behavior

Open pcbnew, select any component, press 'E' , go to 3D tab and link a step file for this package. During selection you should see a preview of the package which is not visible.

### Probable cause

Looking at template file on github:

-DKICAD_USE_OCE=OFF

This setting may need to be enabled if I remember correctly.

**Comment by groundstack** [comment]
I recompiled the kicad package with OCE option enabled and the packages now are viewable.

Changes on template file:

makedepends=
I removed ooct-devel and added oce-devel

then changed 'configure_args' -DKICAD_USE_OCE=OFF to ON.

I recompiled with xbps-src and installed.

This is template file as I used today: 

# Template file for 'kicad'
pkgname=kicad
version=5.1.5
revision=1
build_style=cmake
configure_args="-DKICAD_BUILD_VERSION=${version} -DKICAD_SCRIPTING=ON
 -DKICAD_SCRIPTING_MODULES=ON -DKICAD_SCRIPTING_WXPYTHON=ON
 -DKICAD_SCRIPTING_ACTION_MENU=ON  -DBUILD_GITHUB_PLUGIN=ON -DKICAD_USE_OCE=ON
 -DKICAD_SPICE=$(vopt_if spice ON OFF)"
hostmakedepends="pkg-config swig wxWidgets-devel"
makedepends="wxWidgets-devel wxPython-devel python-devel glew-devel cairo-devel
 libressl-devel boost-devel libcurl-devel glm oce-devel libgomp-devel
 $(vopt_if spice ngspice-devel)"
depends="wxPython"
short_desc="Electronic schematic and PCB design software"
maintainer="Steve Prybylski <sa.prybylx@gmail.com>"
license="GPL-3.0-or-later"
homepage="http://kicad-pcb.org"
distfiles="https://launchpad.net/${pkgname}/${version%%.*}.0/${version}/+download/${pkgname}-${version}.tar.xz"
checksum=80625a1da876e1be683dc08268fe43fe67bb704e841e977431f7a82bdc096474
build_options="spice"
build_options_default="spice"

CXXFLAGS="-std=c++17"

if [ "$CROSS_BUILD" ]; then
        hostmakedepends+=" python wxPython"
        configure_args+=" -DPYTHON_SITE_PACKAGE_PATH=${XBPS_CROSS_BASE}/${py2_sitelib}
         -DPYTHON_DEST=${py2_sitelib}"
fi

pre_configure() {
        if [ "$CROSS_BUILD" ]; then
                CXXFLAGS+=" $(wx-config --cxxflags)"
        fi
}

**Comment by xtraeme** [comment]
Please provide a proper path via Pull Request.

Thanks!
