### ISSUE TITLE
package request: linux-hardened kernel

### ISSUE THREAD

**Issue by martindamianfernandez** [void-linux/void-packages#17830]
Minimal supplement to upstream Kernel Self Protection Project changes. Features already provided by SELinux + Yama and archs other than multiarch arm64 / x86_64 aren't in scope. Only tags have stable history. Shared IRC channel with KSPP: irc.freenode.net ##linux-hardened

http://github.com/anthraxx/linux-hardened

**Comment by q66** [comment]
https://github.com/void-linux/void-packages/issues/14062#issuecomment-526480363
