### ISSUE TITLE
libratbag missing dependencies

### ISSUE THREAD

**Issue by Kozova1** [void-linux/void-packages#17843]
### System

* xuname:  
```
Void 5.4.5_1 x86_64 GenuineIntel notuptodate rrrmFFFF
```
* package:  
  libratbag-0.12_2

### Expected behavior
ratbagctl launches without errors
### Actual behavior
crashes due to missing `ecodes` and `evdev` python modules
### Steps to reproduce the behavior
install libratbag and launch it

**Comment by bra1nwave** [comment]
Cannot reproduce the error. Please give the full log.

**Comment by Kozova1** [comment]
After running `xbps-install -Su` to update the errors went away.

**Comment by q66** [comment]
this is becaues of the python 3.6->3.8 migration, xbps can't really track it easily for you for noarch python modules and therefore a full system upgrade was necessary to get it solved.

**Comment by xtraeme** [comment]
Yeah, this is it. Mainly because `depends="foo"` gets transformed to `run_depends="foo>=0"` ... russian rulet
