### ISSUE TITLE
Erlang built with -o x11 link error

### ISSUE THREAD

**Issue by lbolla** [void-linux/void-packages#1785]
### System

* xuname:  
  Void 4.17.14_1 x86_64 GenuineIntel uptodate rFFF
* package:  
  erlang-21.0

### Expected behavior
Compiled with `-o x11` should link with `wx` libraries and it should run graphical applications, like `observer:start()`.

### Actual behavior
`observer:start()` doesn't work and throws an error like:
```=CRASH REPORT==== 15-Aug-2018::07:49:14.974426 ===
  crasher:
    initial call: observer_wx:init/1
    pid: <0.83.0>
    registered_name: observer
    exception exit: {{load_driver,"undefined symbol: _ZThn704_N17wxGenericListCtrl31GetSizeAvailableForScrollTargetERK6wxSize"},
                     [{wxe_server,start,1,[{file,"wxe_server.erl"},{line,65}]},
                      {wx,new,1,[{file,"wx.erl"},{line,115}]},
                      {observer_wx,init,1,
                                   [{file,"observer_wx.erl"},{line,98}]},
                      {wx_object,init_it,6,
                                 [{file,"wx_object.erl"},{line,372}]},
                      {proc_lib,init_p_do_apply,3,
                                [{file,"proc_lib.erl"},{line,249}]}]}
      in function  wx_object:init_it/6 (wx_object.erl, line 385)
    ancestors: [<0.81.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: [{'_wx_object_',{observer_wx,'_wx_init_'}}]
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 292
  neighbours:
```

### Steps to reproduce the behavior

Compile with:
```
./xbps-src clean erlang
./xbps-src pkg -o x11 erlang
sudo xbps-install --repository=hostdir/binpkgs erlang
```
Then run with:
```
erl
observer:start().
```

**Comment by cr6git** [comment]
https://github.com/void-linux/void-packages/issues/983

**Comment by pullmoll** [comment]
See https://github.com/void-linux/void-packages/commit/6a205c5b3e95f0b03feace864514610b7ef5a072

**Comment by lbolla** [comment]
I've pulled, run `xi -u`, rebuilt `erlang` with the above commands, installed it, but I am still getting the same error.

**Comment by lbolla** [comment]
Tried to rebuild `wxWidgets` from source, but it fails withe the below dependency error:
```liblzma-5.2.4_2 (update) breaks installed pkg `xz-5.2.4_1'```

**Comment by pullmoll** [comment]
Did you try a `./xbps-src bootstrap-update`? I think the x86_64 repo is ok.
I just now tried here:
```
$ ./xbps-src zap
$ ./xbps-src binary-bootstrap
$ ./xbps-src pkg wxWidgets
```
and it started downloading dependencies and is now building.
You could perhaps try to remove `./hostdir/repocache` in case you have broken packages in there.

**Comment by lbolla** [comment]
@pullmoll Thanks, with your suggestions I managed to build `wxWidgets`, but `erlang` is still throwing the same error. I am afraid I may be doing something wrong. Are you able to reproduce the issue I see or not?

**Comment by cr6git** [comment]
I see the error:
````
$ erl
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Eshell V10.0  (abort with ^G)
1> observer:start().
Fatal Error: Mismatch between the program and library build versions detected.
                                                                              The library used 3.0 (wchar_t,compiler with C++ ABI 1011,wx containers,compatible with 2.8),
                                                     and your program used 3.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 2.8).
                                 Aborted
````

Rebuild `wxWidgets` with [this patch](https://git.archlinux.org/svntogit/packages.git/tree/trunk/make-abicheck-non-fatal.patch?h=packages/wxgtk) fixed the issue for me!

**Comment by cr6git** [comment]
@lbolla nice tool, btw.

**Comment by newbluemoon** [comment]
It works for me (without the patch) when I recompile wxWidgets with gcc 8.2.

**Comment by lbolla** [comment]
@newbluemoon Can you please detail the steps to get it working? I feel like
I'm doing something wrong.


---
Lorenzo Bolla
https://lbolla.info

**Comment by newbluemoon** [comment]
@lbolla First I built erlang as you described above. Of course, I got the same error.
Then I just re-build wxWidgets with

    ./xbps-src pkg wxWidgets

installed it and then `observer:start().` worked.

**Comment by newbluemoon** [comment]
I think the problem here is that the wxWidgets in the repo was built with gcc 7.3 (ABI 1011) and your local erlang with gcc 8.2 (ABI 1013). Hence the mismatch. However, no idea why your local rebuild of wxWidgets didn’t work.

**Comment by cr6git** [comment]
@newbluemoon ok, I just rebuilt `wxWidgets` (without patch) and `erlang` and that worked for me.
However, now `audacity` is complaining about `wxWidgets` ...
````
$ audacity
Fatal Error: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1011,wx containers,compatible with 2.8).
Aborted
````

**Comment by Johnnynator** [comment]
@cr6git wxWidgets and everything that depends on wxWidget would be a rebuild.

**Comment by newbluemoon** [comment]
@cr6git See my post above. It’s just the other way around then. :)
@Johnnynator s/be/need/ ? ;)

I think everything wxWidgets should be rebuilt to fix this mismatch.

**Comment by Johnnynator** [comment]
@newbluemoon Yep, I should proofread what I write sometimes :D.
I will prepare a PR to rebuilt anything if that is OK.

**Comment by newbluemoon** [comment]
@Johnnynator No objections. :)

**Comment by Johnnynator** [comment]
@newbluemoon I opened a PR. Currently compiling everything locally to test whether it will work fine.

**Comment by lbolla** [comment]
Thanks! Recompiling wxWidgets and Erlang did fix the issue.
