### ISSUE TITLE
Xcompose doesn't work with Firefox 71

### ISSUE THREAD

**Issue by emacsomancer** [void-linux/void-packages#17891]
### System

* xuname:  
  *Void 5.4.6_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFFFF*
* package:  
  *firefox-71.0_3*

### Expected behavior
[Xcompose](https://wiki.debian.org/XCompose) works as expected. E.g. having defined a compose key, pressing `<Compose> <e> <'>` generates the character `é`. This worked in prior versions of Firefox on Void. It works in other applications on Void, including other web-browsers e.g. Chromium. It works in Firefox 71 on Arch Linux.

### Actual behavior
Xcompose doesn't work in Firefox, though it works everywhere else. So pressing `<Compose> <e> <'>` ignores the compose key and just results in `e'`

### Steps to reproduce the behavior
Set the compose key  (e.g. `xmodmap -e "keysym Alt_R = Multi_key"`), open Firefox, press `<Compose> <e> <'>`.

**Comment by arp242** [comment]
It works for me; I do have this in my zshrc:

    export GTK_IM_MODULE=xim         # Make compose key work
    export QT_IM_MODULE=xim

I forgot the exact details as I added this years ago, but I think I added it to fix it in Firefox.

**Comment by emacsomancer** [comment]
It was some sort of configuration issue specific my Firefox (probably userChrome?). A refresh resolved it.
