### ISSUE TITLE
nushell 0.7.0 update

### ISSUE THREAD

**Issue by jcgruenhage** [void-linux/void-packages#17921]
This is not a package update request, but a small reminder what needs to be done when updating nushell to 0.7.0. I'm maintaining that package, but I'm on vacation right now and it's a slightly larger undertaking than the regular old version bump so I won't do it now.

 - [x] update nushell itself
 - [ ] package the individual plugins
 - [ ] create metapackages for "default set of plugins", "all stable plugins", "all unstable plugins" and "all plugins"

src: https://www.nushell.sh/blog/2019/12/18/nushell-0_7_0.html

**Comment by shabahengam** [comment]
nushell updated to 0.7.0 about 9 days ago [17704](https://github.com/void-linux/void-packages/pull/17704)

**Comment by jcgruenhage** [comment]
Okay, that checks the first box

**Comment by jcgruenhage** [comment]
(although 0.7.1 needs to be done too)

**Comment by ericonr** [comment]
This is certainly stale at the moment :P 

Feel free to reopen if you want to get back on it!
