### ISSUE TITLE
aarch64 is staged / python3-pyenet is not removed from repos

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#17930]
aarch64 repo is still staged from python 3.8 transition. It looks like the old python3-pyenet package is still around in the aarch64 repo, even though it was removed and converted to an empty noarch meta package. this is blocking many packages from being unstaged.

**Comment by abenson** [comment]
[For  reference](https://github.com/void-linux/void-packages/commit/a111b2b5e1d9f98b0767aa8aab3052ded2e2ba8c)

**Comment by CameronNemo** [comment]
Thought about re-adding the package, but that seems like a bad idea:

```diff
+nocross="compiles for the host architecture when cross-compiling"
```

e27fde981f6508c5f52d4561794edeb904c5716f

**Comment by st3r4g** [comment]
`aarch64` is now unstaged.
