### ISSUE TITLE
missing clang manpages

### ISSUE THREAD

**Issue by BrandonIrizarry** [void-linux/void-packages#17935]
### System

* output of xuname:  
Void 5.3.18_1 x86_64 GenuineIntel uptodate rF
* package:  
 clang version 9.0.1 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /bin

### Expected behavior
`man clang` should pull up a manpage.
### Actual behavior
The man page doesn't exist.
### Steps to reproduce the behavior
Type `man clang` at the terminal, after having installed it.

Also, the output of `xbps-query -Rs man | grep page`:

[-] docbook2x-0.8.8_5                        DocBook converter to UNIX manpage and GNU Texinfo format
[-] go-md2man-2.0.0_1                        Convert md to manpages
[\*] man-pages-5.04_1                         Linux Documentation Project (LDP) manual pages
[\*] man-pages-devel-5.04_1                   Linux Documentation Project (LDP) manual pages - development pages
[\*] man-pages-posix-2013a_4                  Manual pages about POSIX systems
[\*] mdocml-1.14.5_3                          The mandoc UNIX manpage compiler toolset
[-] pod2mdoc-0.2_2                           Convert perl documentation (POD) into man pages (mdoc)
[-] ruby-manpages-0.6.1_2                    Gem to add man pages support to ruby gems
[-] ruby-ronn-0.7.3_2                        Strick markdown-like format for manpages
[-] scdoc-1.10.0_1                           Tool for generating roff manual pages
[-] taizen-0.0.0.20180808_4                  Browse mediawiki pages from the command line
[-] texi2mdoc-0.1.2_2                        Convert Texinfo documentation into man pages (mdoc)
[-] txt2man-1.6.0_1                          Converts text to man page
[-] xman-1.1.5_1                             Manual page display program for the X Window System
[-] xmltoman-0.4_1                           Convert XML to man pages in groff format or html

**Comment by leahneukirchen** [comment]
This requires figuring out the proper cmake defines, which I'm currently failing at.

**Comment by ndowens** [comment]
> This requires figuring out the proper cmake defines, which I'm currently failing at.

Currently, I am trying BUILD_DOCS but that may not make manpages

**Comment by ericonr** [comment]
I think what you want is

```diff
diff --git a/srcpkgs/llvm11/template b/srcpkgs/llvm11/template
index 12ecb4bdc4..6746ed6644 100644
--- a/srcpkgs/llvm11/template
+++ b/srcpkgs/llvm11/template
@@ -11,7 +11,9 @@ configure_args="
  -DLLVM_LINK_LLVM_DYLIB=ON
  -DLLVM_ENABLE_RTTI=ON
  -DLLVM_ENABLE_FFI=ON
- -DLLVM_BINUTILS_INCDIR=/usr/include"
+ -DLLVM_BINUTILS_INCDIR=/usr/include
+ -DLLVM_INCLUDE_DOCS=ON
+ -DLLVM_BUILD_DOCS=ON"
 hostmakedepends="groff perl python3 zlib-devel libffi-devel swig"
 makedepends="python3-devel zlib-devel libffi-devel libedit-devel
  libxml2-devel binutils-devel libatomic-devel"
```
