### ISSUE TITLE
gdm/gnome3 is broken

### ISSUE THREAD

**Issue by romulasry** [void-linux/void-packages#17965]
### System

* xuname:  
dmesg: read kernel buffer failed: Operation not permitted
Void 5.4.6_1 x86_64 AuthenticAMD uptodate rrrmFFFF
* package:  
 gdm 3.31.1 gnome-shell 3.31.1

### Expected behavior
It should start

### Actual behavior
Doesn't start

### Steps to reproduce the behavior

Open up gdm or gnome (in lxdm for example)

**Comment by Piraty** [comment]
you don't provide much information. it works here (gdm + gnome)

**Comment by Piraty** [comment]
No anwer, closing
