### ISSUE TITLE
latest update broke urxvt

### ISSUE THREAD

**Issue by loreb** [void-linux/void-packages#1798]
### System

* xuname:  
  Void 4.17.14_1 x86_64-musl GenuineIntel uptodate r
* package:  
  rxvt-unicode-9.22_7 and/or rxvt-unicode-terminfo-9.22_7

### Expected behavior
open a terminal

### Actual behavior
panic: locale.c: 893: Unexpected character in locale name '2E.

### Steps to reproduce the behavior

Run urxvt under a locale containing a dot (0x2e), say en_US.UTF8; LANG=C works.
Also installing/upgrading gives some diagnostics about terminfo, not sure if it's relevant:

```
rxvt-unicode-terminfo-9.22_7: configuring ...
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 57, col 20, terminal 'rxvt-unicode': unknown capability 'kDC5'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 58, col 19, terminal 'rxvt-unicode': unknown capability 'kDC6'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 59, col 17, terminal 'rxvt-unicode': unknown capability 'kDN'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 60, col 18, terminal 'rxvt-unicode': unknown capability 'kDN5'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 62, col 20, terminal 'rxvt-unicode': unknown capability 'kIC5'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 63, col 19, terminal 'rxvt-unicode': unknown capability 'kIC6'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 65, col 21, terminal 'rxvt-unicode': unknown capability 'kEND5'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 66, col 20, terminal 'rxvt-unicode': unknown capability 'kEND6'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 68, col 21, terminal 'rxvt-unicode': unknown capability 'kFND5'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 69, col 20, terminal 'rxvt-unicode': unknown capability 'kFND6'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 71, col 21, terminal 'rxvt-unicode': unknown capability 'kHOM5'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 72, col 20, terminal 'rxvt-unicode': unknown capability 'kHOM6'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 74, col 19, terminal 'rxvt-unicode': unknown capability 'kLFT5'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 76, col 21, terminal 'rxvt-unicode': unknown capability 'kNXT5'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 77, col 20, terminal 'rxvt-unicode': unknown capability 'kNXT6'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 79, col 21, terminal 'rxvt-unicode': unknown capability 'kPRV5'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 80, col 20, terminal 'rxvt-unicode': unknown capability 'kPRV6'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 82, col 19, terminal 'rxvt-unicode': unknown capability 'kRIT5'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 83, col 17, terminal 'rxvt-unicode': unknown capability 'kUP'
"usr/share/terminfo/r/rxvt-unicode.terminfo", line 84, col 18, terminal 'rxvt-unicode': unknown capability 'kUP5'
2 entries written to /usr/share/terminfo
rxvt-unicode-terminfo-9.22_7: installed successfully.

```

**Comment by maxice8** [comment]
can't reproduce here, runs fine

**Comment by chneukirchen** [comment]
Same, please show a dump of your environment variables.

**Comment by loreb** [comment]
LS_COLORS=no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.svgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.bz2=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.svg=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:
LANG=en_US.UTF-8
DISPLAY=:0
OLDPWD=/home/lorenzo
EDITOR=nvim
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
XTERM_SHELL=/bin/bash
USER=lorenzo
ENV=/home/lorenzo/.shinitrc
DESKTOP_SESSION=fluxbox
LC_COLLATE=C
PWD=/home/lorenzo
MANPAGER=/usr/bin/less -s
HOME=/home/lorenzo
BROWSER=chromium --incognito %s
XTERM_VERSION=XTerm(334)
MAIL=/var/spool/mail/lorenzo
WINDOWPATH=7
TERM=xterm
SHELL=/bin/bash
SHLVL=2
WINDOWID=4194317
LOGNAME=lorenzo
XAUTHORITY=/home/lorenzo/.Xauthority
PATH=/home/lorenzo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
XTERM_LOCALE=en_US.UTF-8
_=/usr/bin/env

The warnings actually come from installing rxvt-unicode-terminfo, done as root from a tty, env:
MAIL=/var/spool/mail/root
USER=root
HOME=/root
OLDPWD=/root
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
LOGNAME=root
TERM=linux
LC_COLLATE=C
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
LANG=en_US.UTF-8
LS_COLORS=no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.svgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.bz2=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.svg=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:
SHELL=/bin/sh
PWD=/tmp


Let me know if you need anything else.

**Comment by chneukirchen** [comment]
The warnings are unrelated and harmless.

I cannot reproduce this with a dot at all... I have the same locale and it works fine.

**Comment by chneukirchen** [comment]
Does the same happen if you only run `perl` ?

**Comment by loreb** [comment]
It seems locale.c is part of perl...
$ grep -i rx .Xresources
URxvt*fading: 17
URxvt.perl-ext-common: confirm-paste,digital-clock,selection-to-clipboard,tabbed

But renaming .Xresources, logging out and coming back makes no difference (I don't have .Xdefaults)

**Comment by loreb** [comment]
plain "perl", no.

**Comment by loreb** [comment]
LANG=foo urxvt
panic: locale.c: 893: Unexpected character in locale name '3B.
0x3b is ";", now I'm a bit puzzled :)

**Comment by chneukirchen** [comment]
Here, I get 
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "en_US.UTF-8",
	LC_COLLATE = "C",
	LANG = "foo"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```
and it still shows a terminal.

**Comment by loreb** [comment]
LC_CTYPE="en_US.UTF-8" LANG=foo perl => nothing, just waits for input
Are you running musl or glibc? (musl here) I was thinking of setting up a vm to see if I can at least reproduce it there, I didn't touch anything about perl/urxvt's installation

**Comment by loreb** [comment]
:)

In a glibc vm, I see the warnings (good to know they are harmless) but urxvt runs fine.
In a musl vm, same as on my laptop.

Unless you have a better idea, tomorrow I'll try rebuilding perl with some extra printf;
failing that, xterm works.

**Comment by chneukirchen** [comment]
```
Breakpoint 7, S_emulate_setlocale (category=6, 
    locale=0x7ffff7ffb940 <buf> "foo;C;C;C;C;C", index=6, 
    is_index_valid=<optimized out>) at locale.c:882
882	        while (s < e) {
(gdb) p s
$1 = 0x7ffff7ffb940 <buf> "foo;C;C;C;C;C"
```

then it trips over the first `;`

**Comment by chneukirchen** [comment]
Ok, the problem is that musl setlocale returns a string like that, which is POSIX conforming, but Perl assumes it can parse it somehow.

**Comment by chneukirchen** [comment]
Oh, FreeBDS uses a similar format as musl, but `/` as separator.

**Comment by loreb** [comment]
Good find.

2x good in fact because musl has only barebones localization/i18n at the moment,
so I hope people shouldn't be bothered too much by the workaround.

The perl source code does mention that "Without querylocale, this code uses the glibc (as of this writing)
         * syntax for representing that, but that is not a stable API, and
         * other platforms do it differently, so we have to handle all cases
         * ourselves".

Musl: "The format of
	 * this string is unspecified, and only the following code, which
	 * performs both the serialization and deserialization, depends
	 * on the format, so it can easily be changed if needed"

I guess the long term solution is either to teach perl what to do is there's no '=' before the ';' or to have musl be glibc compatible -- 2nd option sounds easier, but I'll trust your judgement.

Freebsd has querylocale(), so if I'm reading correctly this code is ifdef'd out in that case.
I never heard of querylocale before, so I have no idea if it makes sense to ask the musl people to implement it - afaict it's BSD specific, and netbsd doesn't have it yet.

Thank you for the detective work!

**Comment by chneukirchen** [comment]
I think I've found a simple fix, testing now.

**Comment by khwilliamson** [comment]
querylocale is also on Darwin and other systems.  My view is that it's a mistake that it's not in POSIX.
