### ISSUE TITLE
Package Request: into-ledger

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#17983]
Source: https://github.com/manishrjain/into-ledger
License: [MIT](https://github.com/manishrjain/into-ledger/blob/master/LICENSE)
> Most efficient and accurate tool to categorize and import expenses into ledger

**Comment by ndowens** [comment]
Has no releases available.

**Comment by Anachron** [comment]
Huh, you're right, I haven't checked. Sorry. Closing.
