### ISSUE TITLE
rust: need permission from rust core team to use the trademark

### ISSUE THREAD

**Issue by Gottox** [void-linux/void-packages#18008]
Currently we use rust and cargo trademarks without the permission of the rust core team. As stated [in the media-guide](https://www.rust-lang.org/policies/media-guide):

> Distributing a modified version of the Rust programming language or the Cargo package manager and calling it Rust or Cargo requires explicit, written permission from the Rust core team. We will usually allow these uses as long as the modifications are (1) relatively small and (2) very clearly communicated to end-users.

I'm reaching out to the rust core team.

**Comment by protonesso** [comment]
:^)

**Comment by Gottox** [comment]
https://github.com/rust-lang/core-team/issues/4
