### ISSUE TITLE
fotoxx says exiftool and xdg-utils are missing. But they are not. x86_64

### ISSUE THREAD

**Issue by imrn** [void-linux/void-packages#18038]
fotoxx complains with the following and exits. It displays a similar dialog
on X too. Both exiftool and xdg-utils are available on the system.

```
bash-5.0# fotoxx
program exe: /usr/bin/fotoxx 
build date/time: Dec  1 2019 11:21:14 
fotoxx home: /home/x/.fotoxx 
start fotoxx Sat Jan  4 21:38:32 
maps folder: missing 
language: en_US 
fotoxx-19.20 
GTK version: 3.24.13 
Please install missing programs:
 exiftool (or libimage-exiftool-perl)
 xdg-utils 
quit 

(fotoxx:9392): Gtk-CRITICAL **: 21:38:38.254: gtk_main_quit: assertion main_loops != NULL failed
Fotoxx normal exit 

```

**Comment by ndowens** [comment]
That is weird, have you updated lately? Looking at the template, fotoxx does have exiftool and xdg-utils as depends.

**Comment by imrn** [comment]
Both exiftool and xdg-utils are available on the system.
They are installed as dependency fotoxx.
I can call then on command line. No problem here.

But fotoxx says they are missing.

**Comment by ndowens** [comment]
⋊> ~ on master ⨯ fotoxx                                                                                           14:30:40
program exe: /usr/bin/fotoxx
build date/time: Dec  1 2019 11:21:14
fotoxx home: /home/ndowens/.fotoxx
start fotoxx Sat Jan  4 14:30:42
maps folder: missing
language: en_US
fotoxx-19.20
GTK version: 3.24.13
Raw Therapee not installed
growisofs not installed
ffmpeg and Totem not installed
Panorama Tools (Hugin) not installed
file not found: doc changelog


I don't get that error

**Comment by imrn** [comment]
Well, my setup/installation is straight forward one without any customization or anything like that. fotoxx and its dependencies is installed only by "xbps-install fotoxx". Nothing special, nothing fancy and it doesn't work. :(

**Comment by ndowens** [comment]
I've submitted a PR #18045 to update fotoxx, you could try and see if it would work for you.

**Comment by sgn** [comment]
Maybe you did a partial update, and fotoxx requires a newer version of those tools?
Have you tried to update all softwares?

**Comment by imrn** [comment]
I've succesfully issued 'xbps-install -Su' command 2 times since reporting this issue.
(Last one is 10 minutes before this comment.) Nothing changed.

**Comment by ndowens** [comment]
It's not in the repo at this moment. I was meaning you could build the
pending one using xbps-src after pulling the PR from github.

**Comment by imrn** [comment]
I'm now using fotoxx-20.04_1 without problems. Thank you.
