### ISSUE TITLE
Update linux-firmware to 20191220.6871bff

### ISSUE THREAD

**Issue by hereforthebugs** [void-linux/void-packages#18057]
iwlwifi firmware fails on kernels >=5.4.X and needs to be updated.

**Comment by Hoshpak** [comment]
Is this possible the same issue as #18384 ? The error description is a bit sparse and from the discussion I read it seems that most iwlwifi issues stemmed from the driver changes, not the firmare. I have updated the firmware to the current stable version nonetheless which is a bit older than the git commit arch is using. Could you please update the kernel and firmware packages once the builders are finished with it and confirm if the issue still persists for you?
