### ISSUE TITLE
docker not available on aarch64

### ISSUE THREAD

**Issue by ThatsNoMoon** [void-linux/void-packages#18062]
### System

* xuname:  
  `Void 4.19.89_2 aarch64  uptodate rFF`
  Installation on raspberry pi as per the wiki instructions
* package:  
  `docker 19.03.5`

### Expected behavior
`xbps-install docker` installs `docker`; `docker` visible on https://voidlinux.org/packages/ under aarch64
### Actual behavior
`docker` is not found, despite #16430
### Steps to reproduce the behavior
Install void on a raspberry pi, attempt to install `docker`

**Comment by Duncaen** [comment]
Its marked no cross (all aarch64 packages are cross compiled, we don't have native builders for it). The linked PR allows to build it natively on aarch64 using xbps-src.

**Comment by ThatsNoMoon** [comment]
Thanks @Duncaen, that makes sense.

Is there a specific reason docker can't be cross-compiled?

**Comment by Duncaen** [comment]
golang in general should support it, but dockers build system seems to be a lot more complex than just `go get`.
There is no specific issue linked, and I think this has always been the case and the initial merge PR was in the old repository so the history if the PR is lost.

You can try it by removing `nocross=yes` and trying to cross compile it `./xbps-src -a aarch64 pkg docker`, but I'm certain that there are going to be some issues that need to be fixed.

**Comment by xtraeme** [comment]
docker is already available in aarch64.

**Comment by jsumners** [comment]
How do we get this included in the default repos?

**Comment by jsumners** [comment]
@sgn how would I test this? Fetch the PR to an x86_64 machine and attempt to build the package with `-a aarch64`?

**Comment by ericonr** [comment]
Exactly that.

**Comment by jsumners** [comment]
Okay. I will try to get to it over the weekend.

**Comment by sgn** [comment]
On 2020-09-03 07:31:03-0700, James Sumners <notifications@github.com> wrote:
> @sgn how would I test this? Fetch the PR to an x86_64 machine and
> attempt to build the package with `-a aarch64`?

Yes, and use the binary to run docker on aarch64 machine.
I'm not a heavy user of docker (I prefer podman, anyway).
