### ISSUE TITLE
Chromium breaks with last kernel and last nvidia drivers

### ISSUE THREAD

**Issue by rapha8l** [void-linux/void-packages#18068]
### System

* xuname:  

Void 5.4.8_1 x86_64 GenuineIntel uptodate rrrmFFFFF
nvidia-440.44_2 
chromium-79.0.3945.88_1
Chromium dies with (even with --disable-gpu, and all ~/.config/chromium removed)

> 

> [17315:17315:0106/112311.534635:ERROR:platform_thread_posix.cc(129)] pthread_create: Argument invalide (22)
> [17315:17315:0106/112311.534677:ERROR:shutdown_signal_handlers_posix.cc(202)] Failed to create shutdown detector task.
> [17338:17338:0106/112311.583038:ERROR:vaapi_wrapper.cc(418)] vaInitialize failed (ignore if using Wayland desktop environment): unknown libva error
> Received signal 11 SEGV_MAPERR 000000000000
> #0 0x55582ac5f879 <unknown>
> #1 0x55582aba5113 <unknown>
> #2 0x55582ac5f3f1 <unknown>
> #3 0x7f84252a3120 <unknown>
> #4 0x7f8420bc43e1 __strlen_avx2
> #5 0x55582875c6d1 <unknown>
> #6 0x555828752728 <unknown>
> #7 0x55582875b52c <unknown>
> #8 0x55582ed20bb5 <unknown>
> #9 0x55582c028fad <unknown>
> #10 0x55582ed1f1c3 <unknown>
> #11 0x55582a6d9d1e <unknown>
> #12 0x55582a7074dd <unknown>
> #13 0x55582a6d8371 <unknown>
> #14 0x555827df72ff ChromeMain
> #15 0x7f8420a8cdeb __libc_start_main
> #16 0x555827df71aa _start
>   r8: 0000555833b6404e  r9: 0000000000000000 r10: 0000555833c40de0 r11: 0000000000000000
>  r12: 00007ffd0271b530 r13: 00007ffd0271b4fc r14: 0000000000000000 r15: 00007ffd0271b510
>   di: 0000000000000000  si: 0000000000000000  bp: 00007ffd0271b1e0  bx: 0000000000000000
>   dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffd0271aff8
>   ip: 00007f8420bc43e1 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
>  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> [17354:17354:0106/112311.635207:ERROR:vaapi_wrapper.cc(418)] vaInitialize failed (ignore if using Wayland desktop environment): unknown libva error
> Received signal 11 SEGV_MAPERR 000000000000
> #0 0x556c80a5a879 <unknown>
> #1 0x556c809a0113 <unknown>
> #2 0x556c80a5a3f1 <unknown>
> #3 0x7f14f4cc8120 <unknown>
> #4 0x7f14f05e93e1 __strlen_avx2
> #5 0x556c7e5576d1 <unknown>
> #6 0x556c7e54d728 <unknown>
> #7 0x556c7e55652c <unknown>
> #8 0x556c84b1bbb5 <unknown>
> #9 0x556c81e23fad <unknown>
> #10 0x556c84b1a1c3 <unknown>
> #11 0x556c804d4d1e <unknown>
> #12 0x556c805024dd <unknown>
> #13 0x556c804d3371 <unknown>
> #14 0x556c7dbf22ff ChromeMain
> #15 0x7f14f04b1deb __libc_start_main
> #16 0x556c7dbf21aa _start
>   r8: 0000556c890df04e  r9: 0000000000000000 r10: 0000556c891bbde0 r11: 0000000000000000
>  r12: 00007ffcc3d1e0f0 r13: 00007ffcc3d1e0bc r14: 0000000000000000 r15: 00007ffcc3d1e0d0
>   di: 0000000000000000  si: 0000000000000000  bp: 00007ffcc3d1dda0  bx: 0000000000000000
>   dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffcc3d1dbb8
>   ip: 00007f14f05e93e1 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
>  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> [17341:17350:0106/112311.650271:ERROR:nss_util.cc(283)] After loading Root Certs, loaded==false: NSS error code: -8018
> [17388:17388:0106/112311.693675:ERROR:vaapi_wrapper.cc(418)] vaInitialize failed (ignore if using Wayland desktop environment): unknown libva error
> Received signal 11 SEGV_MAPERR 000000000000
> #0 0x55c3c8c35879 <unknown>
> #1 0x55c3c8b7b113 <unknown>
> #2 0x55c3c8c353f1 <unknown>
> #3 0x7f5cd9459120 <unknown>
> #4 0x7f5cd4d7a3e1 __strlen_avx2
> #5 0x55c3c67326d1 <unknown>
> #6 0x55c3c6728728 <unknown>
> #7 0x55c3c673152c <unknown>
> #8 0x55c3cccf6bb5 <unknown>
> #9 0x55c3c9ffefad <unknown>
> #10 0x55c3cccf51c3 <unknown>
> #11 0x55c3c86afd1e <unknown>
> #12 0x55c3c86dd4dd <unknown>
> #13 0x55c3c86ae371 <unknown>
> #14 0x55c3c5dcd2ff ChromeMain
> #15 0x7f5cd4c42deb __libc_start_main
> #16 0x55c3c5dcd1aa _start
>   r8: 000055c3d129604e  r9: 0000000000000000 r10: 000055c3d1372de0 r11: 0000000000000000
>  r12: 00007ffd3dff90e0 r13: 00007ffd3dff90ac r14: 0000000000000000 r15: 00007ffd3dff90c0
>   di: 0000000000000000  si: 0000000000000000  bp: 00007ffd3dff8d90  bx: 0000000000000000
>   dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffd3dff8ba8
>   ip: 00007f5cd4d7a3e1 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
>  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> [17315:17452:0106/112311.754475:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [17315:17452:0106/112311.754596:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [17315:17452:0106/112311.754686:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
> [17431:17431:0106/112311.759303:ERROR:vaapi_wrapper.cc(418)] vaInitialize failed (ignore if using Wayland desktop environment): unknown libva error
> Received signal 11 SEGV_MAPERR 000000000000
> #0 0x55b30520e879 <unknown>
> #1 0x55b305154113 <unknown>
> #2 0x55b30520e3f1 <unknown>
> #3 0x7f2c00e86120 <unknown>
> #4 0x7f2bfc7a73e1 __strlen_avx2
> #5 0x55b302d0b6d1 <unknown>
> #6 0x55b302d01728 <unknown>
> #7 0x55b302d0a52c <unknown>
> #8 0x55b3092cfbb5 <unknown>
> #9 0x55b3065d7fad <unknown>
> #10 0x55b3092ce1c3 <unknown>
> #11 0x55b304c88d1e <unknown>
> #12 0x55b304cb64dd <unknown>
> #13 0x55b304c87371 <unknown>
> #14 0x55b3023a62ff ChromeMain
> #15 0x7f2bfc66fdeb __libc_start_main
> #16 0x55b3023a61aa _start
>   r8: 000055b30c94504e  r9: 0000000000000000 r10: 000055b30ca121d0 r11: 0000000000000000
>  r12: 00007ffe0274b920 r13: 00007ffe0274b8ec r14: 0000000000000000 r15: 00007ffe0274b900
>   di: 0000000000000000  si: 0000000000000000  bp: 00007ffe0274b5d0  bx: 0000000000000000
>   dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffe0274b3e8
>   ip: 00007f2bfc7a73e1 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
>  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> [17477:17477:0106/112311.926388:ERROR:vaapi_wrapper.cc(418)] vaInitialize failed (ignore if using Wayland desktop environment): unknown libva error
> Received signal 11 SEGV_MAPERR 000000000000
> #0 0x55d80ad12879 <unknown>
> #1 0x55d80ac58113 <unknown>
> #2 0x55d80ad123f1 <unknown>
> #3 0x7ff6bca00120 <unknown>
> #4 0x7ff6b83213e1 __strlen_avx2
> #5 0x55d80880f6d1 <unknown>
> #6 0x55d808805728 <unknown>
> #7 0x55d80880e52c <unknown>
> #8 0x55d80edd3bb5 <unknown>
> #9 0x55d80c0dbfad <unknown>
> #10 0x55d80edd21c3 <unknown>
> #11 0x55d80a78cd1e <unknown>
> #12 0x55d80a7ba4dd <unknown>
> #13 0x55d80a78b371 <unknown>
> #14 0x55d807eaa2ff ChromeMain
> #15 0x7ff6b81e9deb __libc_start_main
> #16 0x55d807eaa1aa _start
>   r8: 000055d81230d04e  r9: 0000000000000000 r10: 000055d8123da1d0 r11: 0000000000000000
>  r12: 00007ffd5f315b40 r13: 00007ffd5f315b0c r14: 0000000000000000 r15: 00007ffd5f315b20
>   di: 0000000000000000  si: 0000000000000000  bp: 00007ffd5f3157f0  bx: 0000000000000000
>   dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffd5f315608
>   ip: 00007ff6b83213e1 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
>  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> libpng warning: iCCP: known incorrect sRGB profile
> libpng warning: iCCP: known incorrect sRGB profile
> [17632:17632:0106/112312.037520:ERROR:vaapi_wrapper.cc(418)] vaInitialize failed (ignore if using Wayland desktop environment): unknown libva error
> Received signal 11 SEGV_MAPERR 000000000000
> #0 0x55adbe46e879 <unknown>
> #1 0x55adbe3b4113 <unknown>
> #2 0x55adbe46e3f1 <unknown>
> #3 0x7fd930b5d120 <unknown>
> #4 0x7fd92c47e3e1 __strlen_avx2
> #5 0x55adbbf6b6d1 <unknown>
> #6 0x55adbbf61728 <unknown>
> #7 0x55adbbf6a52c <unknown>
> #8 0x55adc252fbb5 <unknown>
> #9 0x55adbf837fad <unknown>
> #10 0x55adc252e1c3 <unknown>
> #11 0x55adbdee8d1e <unknown>
> #12 0x55adbdf164dd <unknown>
> #13 0x55adbdee7371 <unknown>
> #14 0x55adbb6062ff ChromeMain
> #15 0x7fd92c346deb __libc_start_main
> #16 0x55adbb6061aa _start
>   r8: 000055adc57fb04e  r9: 0000000000000000 r10: 000055adc58c81d0 r11: 0000000000000000
>  r12: 00007ffe1b0aa5b0 r13: 00007ffe1b0aa57c r14: 0000000000000000 r15: 00007ffe1b0aa590
>   di: 0000000000000000  si: 0000000000000000  bp: 00007ffe1b0aa260  bx: 0000000000000000
>   dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffe1b0aa078
>   ip: 00007fd92c47e3e1 efl: 0000000000010283 cgf: 002b000000000033 erf: 0000000000000004
>  trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
> [17315:17324:0106/112312.042110:FATAL:gpu_data_manager_impl_private.cc(990)] The display compositor is frequently crashing. Goodbye.
> #0 0x55d1ea912879 <unknown>
> #1 0x55d1ea868abc <unknown>
> #2 0x55d1e893ed01 <unknown>
> #3 0x55d1e8940fa4 <unknown>
> #4 0x55d1e8942c12 <unknown>
> #5 0x55d1e875be41 <unknown>
> #6 0x55d1eb1bc5ee <unknown>
> #7 0x55d1eaa36740 <unknown>
> #8 0x55d1eb1c0a98 <unknown>
> #9 0x55d1eb1c1bed <unknown>
> #10 0x55d1eaa32926 <unknown>
> #11 0x55d1eaa4dd8e <unknown>
> #12 0x55d1eaa4e068 <unknown>
> #13 0x55d1eaa4d6d0 <unknown>
> #14 0x55d1e8446dd9 <unknown>
> #15 0x55d1e844696c <unknown>
> #16 0x55d1e844321d <unknown>
> #17 0x55d1e8438db5 <unknown>
> #18 0x55d1e844b1da <unknown>
> #19 0x55d1ea927ded <unknown>
> #20 0x7fc2d8242a9f <unknown>
> #21 0x7fc2d82431df event_base_loop
> #22 0x55d1ea9281cc <unknown>
> #23 0x55d1ea8c3b09 <unknown>
> #24 0x55d1ea89c3f7 <unknown>
> #25 0x55d1e8770c84 <unknown>
> #26 0x55d1ea8d3a2b <unknown>
> #27 0x55d1ea92a95e <unknown>
> #28 0x7fc2d923bf27 start_thread
> #29 0x7fc2d4b06e0f __GI___clone
> 
> Received signal 6
> #0 0x55d1ea912879 <unknown>
> #1 0x55d1ea858113 <unknown>
> #2 0x55d1ea9123f1 <unknown>
> #3 0x7fc2d9247120 <unknown>
> #4 0x7fc2d4a45931 __GI_raise
> #5 0x7fc2d4a2f55b __GI_abort
> #6 0x55d1ea911225 <unknown>
> #7 0x55d1ea868fbe <unknown>
> #8 0x55d1e893ed01 <unknown>
> #9 0x55d1e8940fa4 <unknown>
> #10 0x55d1e8942c12 <unknown>
> #11 0x55d1e875be41 <unknown>
> #12 0x55d1eb1bc5ee <unknown>
> #13 0x55d1eaa36740 <unknown>
> #14 0x55d1eb1c0a98 <unknown>
> #15 0x55d1eb1c1bed <unknown>
> #16 0x55d1eaa32926 <unknown>
> #17 0x55d1eaa4dd8e <unknown>
> #18 0x55d1eaa4e068 <unknown>
> #19 0x55d1eaa4d6d0 <unknown>
> #20 0x55d1e8446dd9 <unknown>
> #21 0x55d1e844696c <unknown>
> #22 0x55d1e844321d <unknown>
> #23 0x55d1e8438db5 <unknown>
> #24 0x55d1e844b1da <unknown>
> #25 0x55d1ea927ded <unknown>
> #26 0x7fc2d8242a9f <unknown>
> #27 0x7fc2d82431df event_base_loop
> #28 0x55d1ea9281cc <unknown>
> #29 0x55d1ea8c3b09 <unknown>
> #30 0x55d1ea89c3f7 <unknown>
> #31 0x55d1e8770c84 <unknown>
> #32 0x55d1ea8d3a2b <unknown>
> #33 0x55d1ea92a95e <unknown>
> #34 0x7fc2d923bf27 start_thread
> #35 0x7fc2d4b06e0f __GI___clone
>   r8: 0000000000000000  r9: 00007fc2cca2cea0 r10: 0000000000000008 r11: 0000000000000246
>  r12: 00007fc2b4046790 r13: 00007fc2cca2e168 r14: 0000000000000084 r15: 0000000000000000
>   di: 0000000000000002  si: 00007fc2cca2cea0  bp: 00007fc2cca2d0f0  bx: 00007fc2cca39700
>   dx: 0000000000000000  ax: 0000000000000000  cx: 00007fc2d4a45931  sp: 00007fc2cca2cea0
>   ip: 00007fc2d4a45931 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
>  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
> [end of stack trace]
> Calling _exit(1). Core file will not be generated.
>

**Comment by toluschr** [comment]
Same on my system. However, I tried installing chromium in a VirtualBox VM and it doesn't work in there either.

**Comment by lpsyk** [comment]
Could you try to install libva-vdpau-driver as a workaround ?
I had this issue, and it worked for me.

**Comment by toluschr** [comment]
@lpsyk Thank you so much. It worked for me too!

**Comment by rapha8l** [comment]
Indeed, it works also for me
Thanks ! @lpsyk

**Comment by Unixware** [comment]
sadly does not work for me (virtual box) libva-vdpau-driver installed too, bit train wreck build.

**Comment by xtraeme** [comment]
is this still an issue? can you reproduce it?

**Comment by ericonr** [comment]
Is this issue still relevant?

**Comment by toluschr** [comment]
> Is this issue still relevant?

No. I just setup a new system and chromium worked flawlessly out of the box.

**Comment by ericonr** [comment]
Ok, closing for now.

Feel free to reopen or open another issue, if anything else appears.
