### ISSUE TITLE
Is binary-bootstrap missing from packages?

### ISSUE THREAD

**Issue by ruegerjr** [void-linux/void-packages#18079]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *affected package(s) including the version*

**Comment by ndowens** [comment]
No, it is part of xbps-src itself. It's not in the repo.

**Comment by ruegerjr** [comment]
Apologies.  It was apparently missing from my git-cloned xbps-src repository.  Likely temporary, but I will report if not resolved when running git clone again.

**Comment by ndowens** [comment]
If you have ran binary-bootstrap once, it won't let you do it again, unless
you zap the dir. You can run bootstrap-update to update the local sources.

**Comment by ruegerjr** [comment]
Understood.
