### ISSUE TITLE
common/hooks/do-fetch/00-distfiles.sh: contents checksum broken

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#18070]
With the switch to `bsdtar` the evaluation of contents checksums (i.e. the ones starting with `@`) is broken. One example is `libaom`. Trying to build it gives the error:
```
=> libaom-1.0.0.1_2: verifying contents checksum for distfile 'v1.0.0-errata1.tar.gz'... bsdtar: Can't specify both -t and -x
```

`bsdtar` as opposed to `tar` does not support `-x extract` together with `-t list`, yet the commands are like `$TAR_CMD xf $filename $TAR_CMD_STDOUT`.

I think we need to get rid of the `TAR_CMD_STDOUT="--list"` vs. `TAR_CMD_STDOUT="--to-stdout"` and rather have the type of command (extract or list) for `bsdtar` and `tar` as part of some `TAR_CMD_STDOUT`

For `bsdtar` that could be `TAR_CMD_STDOUT="bsdtar --list"`, and for GNU `tar` that could be `TAR_CMD_STDOUT="tar --extract --to-stdout"`.

For the single case where there is no redirection from the tar output to stdout, in line 98, then `TAR_CMD="bsdtar"` or `TAR_CMD="tar"` should be defined.

I could try to fix that but perhaps @xtraeme knows better how to fix this and beats me to it?

**Comment by pullmoll** [comment]
Err, actually `--list` for `bsdtar` is wrong. We need the entire contents of the tarball's files chained together to feed into `$XBPS_DIGEST_CMD`, so that should be option `-O`!?

**Comment by xtraeme** [comment]
@pullmoll you are right, --list is wrong, bsdtar supports -O,--to-stdout like GNU tar.

**Comment by pullmoll** [comment]
I already have a fix along the lines described above. Some more testing and I'll push it.

**Comment by xtraeme** [comment]
@pullmoll feel free to fix this; in this case TAR_CMD_STDOUT is useless, we can use --to-stdout anywhere

**Comment by xtraeme** [comment]
omg wrong click :-)
