### ISSUE TITLE
Package Request: localepurge

### ISSUE THREAD

**Issue by imrn** [void-linux/void-packages#18125]
localepurge is a debian utility to reclaim sizable disk space by removing installed but unused localization related files, 

https://packages.debian.org/sid/localepurge
http://manpages.ubuntu.com/manpages/eoan/man8/localepurge.8.html

**Comment by ndowens** [comment]
I don't know that this would work here, it seems to need:
dpkg-reconfigure localepurge"

**Comment by imrn** [comment]
No. It does not require package installer help.
I've been a debian and then arch user before coming to void.
I've been using localepurge from command line on debian and arch.

https://aur.archlinux.org/packages/localepurge/

**Comment by imrn** [comment]
As I've been looking around and found this: Poorman's localepurge for arch:
https://scarpino.dev/posts/localepurge-the-arch-way.html
Interesting idea.

This is something related to xbps. It may provide hook/mask dir
like /etc/xbps/noinstall.d/ in which we can drop our "do not install"
definitions. It is in fact far better to not to install unnecessary files.
Anyway this is something futuristic. If there is an interest then I can
open a "feature request" for xbps too.

For now, lets focus on localepurge.

**Comment by xtraeme** [comment]
Sounds good

**Comment by ericonr** [comment]
`noextract` has been implemented in XBPS and this is no longer an issue.
