### ISSUE TITLE
Feature Request: xbps - "do_not_install/extract" mask for files of installed packages

### ISSUE THREAD

**Issue by imrn** [void-linux/void-packages#18142]
Please provide something like /etc/xbps/noinstall.d/
to prevent xbps installing certain files of packages.

Initial usage will most probably be to prevent installation of unused locale related files. They occupy important disk space.

The very basic idea is here:
https://github.com/void-linux/void-packages/issues/18125#issuecomment-572675667

**Comment by Johnnynator** [comment]
The correct repo for such issues would be the xbps one. There is already a open Issue for such a feature.
https://github.com/void-linux/xbps/issues/165
