### ISSUE TITLE
Package Request: spotifyd

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#18162]
Void already offers spotify-tui in its repositories, so it would make sense to offer [spotifyd](https://github.com/Spotifyd/spotifyd) as well, which is a daemon for streaming from Spotify. This would allow one to stream music without requiring any proprietary clients.

The only potential issue is that Rust can't use proc_macros when it's running in musl systems. I don't know much about Void's build infrastructure, are the builds for the musl repos done with musl systems?

Offering this daemon would especially help musl users, due to the impossibility of compiling it in their own systems.

**Comment by Eluminae** [comment]
There already is a request for spotifyd https://github.com/void-linux/void-packages/issues/15218

I'm following this too, the mr still is stuck. Let's be patient, @abenson seems on it.

**Comment by ericonr** [comment]
I have no idea what happened, because I had actually searched for spotify in both issues and pull requests, and hadn't found it. Sorry! Should I close this one, then?

**Comment by Eluminae** [comment]
Np it happens. :)  Yes I guess you can close this one and subscribe to the other one. Have a nice day !

**Comment by abenson** [comment]
I'm working on it -- having issues with `aarch64-musl` and getting it to support dbus/etc.

**Comment by ericonr** [comment]
Got it, good luck! Let me know if there's anything I can do (I have tried building it on my Manjaro installation, will see what happens when I transfer it to Void).
