### ISSUE TITLE
Package Request: wdisplays

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#18161]
Seeing as Void offers a great base for a Wayland based desktop session, especially those based on wlroots (Sway and Wayfire), it would be interesting to have an easy way to setup several monitors. [wdisplays](https://github.com/cyclopsian/wdisplays) can be used for that, and it has a very intuitive interface.

**Comment by ndowens** [comment]
I will try to package this.

**Comment by ericonr** [comment]
Oh, I see! If it gets a release, should I bump this issue? Or is there someone tracking it already?

**Comment by ndowens** [comment]
Bump as probably no one else is watching

**Comment by cyclopsian** [comment]
I just released 1.0 of wdisplays, so it can be packaged when ready.

**Comment by ericonr** [comment]
@cyclopsian awesome, thanks!
