### ISSUE TITLE
python-xdg actually is python-pyxdg

### ISSUE THREAD

**Issue by Eluminae** [void-linux/void-packages#18172]
Hello there,

I'm trying to package a python module named remhind but it depends on the xdg python module. I can't package this dependency cause there already is a python-xdg. python-xdg install the pyxdg module.

Is there a way to "rename" cleanly a void package ? Is it a good idea ? Do I have alternatives to fix my dependency issue ?

Thanks a lot ! Kiss

**Comment by Chocimier** [comment]
> Is there a way to "rename" cleanly a void package? Is it a good idea ?

This shouldn't be necessary.

> Do I have alternatives to fix my dependency issue ?

Just using it should be enough, maybe you misused py2 version `python-xdg` instead of `python3-xdg`?
If this won't work, you can push wip pull request.

**Comment by CameronNemo** [comment]
There are two separate packages.

https://github.com/takluyver/pyxdg

https://github.com/srstevenson/xdg

We have a policy of renaming python modules like pygtk or pyxdg to python-gtk or python-xdg. But someone can still publish actual gtk or xdg modules that are different.

**Comment by xtraeme** [comment]
not an issue, please reopen if you think so
