### ISSUE TITLE
Firefox 72 segfaults

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#18179]
### System

* xuname:  
Void 5.4.10_1 x86_64 GenuineIntel notuptodate rrrmDFFFFF
* package:  
firefox-72.0.1_1

### Expected behavior
Firefox to launch

### Actual behavior
Crashes instantly with "Speicherzugriffsfehler" (segfault)

### Steps to reproduce the behavior
Launch firefox

### STRACE
https://gist.github.com/Anachron/cd8c7a05b2eaa1a36cc866f15e46a958

**Comment by Duncaen** [comment]
The strace log is useless, it only followed one process even the stderr output would be more interesting.

**Comment by Anachron** [comment]
No output other than "Speicherzugriffsfehler".

**Comment by niklasnisbeth** [comment]
I had the same issue but it went away after updating the rest of the system. I don't know the underlying cause, unfortunately.

**Comment by qcc-na** [comment]
This is also happening for me.

**Comment by qcc-na** [comment]
Any ideas?  This is super annoying.  Mine has not gone away after updating.

**Comment by Duncaen** [comment]
No one provided any useful logs or backtraces with firefox-dbg.

**Comment by Johnnynator** [comment]
You both have `sqlite-replication` installed?

**Comment by qcc-na** [comment]
@Johnnynator 
```
$ sudo xbps-query -Rs sqlite-replication
[*] sqlite-replication-3.29.0_2             Replication Enabled SQL Database Engine in a C Library
```
@Duncaen Sorry I haven't heard of  firefox-dbg and I don't see it in the repos.

**Comment by xtraeme** [comment]
xbps-query does not need root perms...

**Comment by Johnnynator** [comment]
Should be "fixed" with 74e013276dad78b4870ddec031aa843fff8e6b0e

**Comment by qcc-na** [comment]
@xtraeme Thanks, but its just habit

**Comment by xtraeme** [comment]
Really? I'm intrigued with this issue...

**Comment by qcc-na** [comment]
As a user I xbps-install much more often than I xbps-query, sudo and xbps is just kind of muscle memory for me.

**Comment by Johnnynator** [comment]
Firefox has a runtime check if the `sqlite` library that is in use is the exact same version as the one it was compiled against. ( https://hg.mozilla.org/mozilla-central/file/tip/storage/mozStorageService.cpp#l209 ). `sqlite-replication` was a different version than `sqlite` therefore the check failed and firefox called `MOZ_CRASH`

**Comment by xtraeme** [comment]
omg

**Comment by qcc-na** [comment]
Firefox works again after updating to the newest sqlite thank you for being a hero. @Johnnynator

**Comment by Anachron** [comment]
Please make sure to make a note to always update sqllite with firefox from now on.

**Comment by Duncaen** [comment]
Please make sure to supply backtraces whenever you report an issue from now on.

**Comment by Anachron** [comment]
I've rephrased my sentence.

**Comment by Duncaen** [comment]
You don't understand the issue, even if you rephrase it more politely its wrong.

**Comment by Anachron** [comment]
The issue here was a missing backtrace as not everybody was able to reproduce it and now Johnny found the issue meanwhile because I have no clue how to make a backtrace or use the mozilla debugger and had no time yet to get into it.

**Comment by Johnnynator** [comment]
> The issue here was a missing backtrace as not everybody was able to reproduce it and now Johnny found the issue meanwhile because I have no clue how to make a backtrace or use the mozilla debugger and had no time yet to get into it.

Smth like this can be done to get a backtrace, output will be in bt.log. The issue was quite obvious after looking at the backtrace for this, since it pointed to `MOZ_CRASH("SQLite Version Error");`, it would have been faster if someone had provided a backtrace before me.

```
# xbps-install -S void-repo-debug
# xbps-install -S firefox-dbg gdb
$ gdb firefox
(gdb) run
(gdb) set logging file bt.log
(gdb) set logging on
(gdb) bt full
(gdb) quit
```

**Comment by qcc-na** [comment]
Did not know about the debug repo, thanks for sharing.

**Comment by Anachron** [comment]
This is fixed.
