### ISSUE TITLE
txt files handled by xbps-src aren't cleaned

### ISSUE THREAD

**Issue by Chocimier** [void-linux/void-packages#18190]
If template downloads txt file, it is copied into builddir and then not removed, e.g. scons or emacs-ess.

Handling of txt should be changed to copy into wrksrc, or removed, or together with skip_extraction replaced with new variable that hold (distfile, path relative to wrksrc) pairs. Last one would be handy for many cases where XBPS_SRCDISTDIR is accessed currently.

Suggestions?

**Comment by pullmoll** [comment]
Where do you want the txt files removed? The sources directory should keep a copy of them together with the sha256 symbolic link so they can be re-used and found later on by the same or other packages using them.

Or do you say they are not removed from `$wrksrc'? That would be a bug because $wrksrc should always be removed after building and packaging or checking.

**Comment by Duncaen** [comment]
> Or do you say they are not removed from `$wrksrc'? That would be a bug because $wrksrc should always be removed after building and packaging or checking.

or outside of `$wrksrc`, which is expected, I usually use `create_wrksrc=yes` and `build_wrksrc` for multiple distfiles so I don't have to care about cleaning up correctly.

**Comment by pullmoll** [comment]
Perhaps we should avoid such leftovers by removing everything below `builddir` and not just `$wrksrc` on success. I don't know for how long the `builddir/.xbps-*` directories are expected to live, though.

**Comment by Chocimier** [comment]
> use create_wrksrc=yes and build_wrksrc for multiple distfiles

Nice pattern. It is documented, but, undeservedly, unpopular. It may be enough to use it and require defined create_wrksrc to copy txts then.

**Comment by Chocimier** [comment]
Resolved by requiring to set create_wrksrc in #19053.
