### ISSUE TITLE
python a dependency of xfce for no reason

### ISSUE THREAD

**Issue by bgkillas** [void-linux/void-packages#18236]
i belive that useless dependency should not be there all of these i can uninstall and works perfectly fine (from my testing) besides libxfce4ui that breaks stuff so why are these dependency here 
![image](https://user-images.githubusercontent.com/55570525/72207031-a4876f00-3462-11ea-9645-5b6b6bc212da.png)

**Comment by ruegerjr** [comment]
I am not a maintainer here, but do not understand your  post.  The statement ,

> "besides libxfce4ui that breaks stuff so why are these dependency  here"

makes no sense at all.  Despite your "testing", libxfce4ui is a core part of XFCE4, not some add-on.
**thunar** requires it
**xfce4-pane1** requires it
**xfce4-session** requires it
**xfce4-settings** requires it
**xfdesktop** requires it
**xfwm4** requires it.
I could go on, but you get the point.  Breaking python-gobject and libxfce4ui by removing python breaks the XFCE4 desktop environment.

**Comment by q66** [comment]
fwiw, it's true the dependency shouldn't be there; as far as i can see, python is needed by `glade3` for one of its plugins, but said plugin is not shipped in `libgladeui3`, but rather in `glade3` itself; therefore the `python-gobject` runtime dependency should be on `glade3` (and it should be updated for python3)

**Comment by ruegerjr** [comment]
Thanks, and I understand.  My reading of the post seemed to imply that libxfce4ui was detrimental and could/should be left out.  That is what I took issue with.

**Comment by sgn** [comment]
glade 3 could be built with python 3.
I had written an update for a while, but it doesn't work now.

I'll look into update it.

**Comment by sgn** [comment]
Here is the PR: https://github.com/void-linux/void-packages/pull/17766

**Comment by sgn** [comment]
I fixed the broken build for armv6hf-musl.
We can drop python 2 dependency once it's merged
