### ISSUE TITLE
Linux 5.4.10_2 can't boot

### ISSUE THREAD

**Issue by Eluminae** [void-linux/void-packages#18233]
Hello there ! Got a little problem today

In one of my machines, linux 5.4.10_1 boot but not the 5.4.10_2

I don't think this is a grub problem cause I still can boot 5.4.10_1 but maybe the machine setup is important.

This machine is mounted using LVM on LUKS. It is probably related cause my other pc still boot.

```
$ lsblk
NAME
sda
└─crypthdd
  └─hddvg-home
nvme0n1
├─nvme0n1p1
├─nvme0n1p2
└─nvme0n1p3
  └─luks-4c477d16-5ff7-4b97-9c23-d0ba73d71e7e
    ├─ssdvg-root
    └─ssdvg-swap
```
```
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 slub_debug=P pci=nomsi page_poison=1 rd.vconsole.keymap=fr rd.lvm=1 rd.luks.uuid=4c477d16-5ff7-4b97-9c23-d0ba73d71e7e rd.luks.crypttab=1 rd.luks.timeout=180 boot=UUID=1b652115-ca90-4ba4-819f-4bd79bcc00c7 root=UUID=973685ed-ac1e-48fa-bd82-d156cc80a12a resume=UUID=ac8e07e0-257a-484e-8a41-ec2b76251ea5"
```

I normally am prompted for the luks key and then, the key for the second disk is available to mount the home partition. 

I don't really know what informations you should need. Feel free to ask !

Ty a lot, kiss

**Comment by newbluemoon** [comment]
Any chance you ran out of space on the partition where your `/boot` is located?

**Comment by Eluminae** [comment]
I don't think so. This is a dedicated partition and it is not full yet. When /boot ran out of space, the dracut hook got issues. Here, everything went well. I tried to `xbps-reconfigure -f linux5.4` and it just worked

**Comment by Eluminae** [comment]
Okay, totally my bad. That was the missing space left error.
