### ISSUE TITLE
cross-arm-none-eabi fail to link

### ISSUE THREAD

**Issue by herveq** [void-linux/void-packages#1824]
### System
Void 4.16.9_1 x86_64-musl GenuineIntel notuptodate hold rrrnF
package cross-arm-none-eabi

Hi all

I have been playing with a compiler gcc-arm-none-eabi-4_9-2015q2-20150609 
from launchpad.net for stm32, since many months. I had to compile it to run
on Void Linux musl. For the discussion, I call it REF1.

Recently, I discovered the Void Linux package cross-arm-none-eabi and I
thought it could serve the same purpose as REF1. So I installed it, modified
my test project makefile to use it. I call it REF2.

The compiler looks to work fine, but the linker complains about:
undefined reference to `memcpy'
undefined reference to `strlen'...

That is like a missing library. REF2 libraries are installed in
/usr/arm-none-eabi/usr/lib that has exactly the same structure as my
REF1/arm-none-eabi/usr/lib

For a test, I replaced REF2/arm-none-eabi/usr/lib with 
REF1/arm-none-eabi/usr/lib. And then the link succeeded, that means
REF2/libs are bad formatted. Some tests on libs:

REF1 lib/libc_nano.a
ls -l /home8/gnuarm/arm-none-eabi/arm-none-eabi/lib/libc_nano.a
-rw-r--r-- 1 hq hq 4090018 Feb 17  2017 /home8/gnuarm/arm-none-eabi/arm-none-eabi/lib/libc_nano.a
ar x /home8/gnuarm/arm-none-eabi/arm-none-eabi/lib/libc_nano.a
nm lib_a-memcpy.o
00000000 t $a
00000010 N $d
00000000 T memcpy

REF2 arm-none-eabi/usr/lib/libc_nano.a
ls -l /usr/arm-none-eabi/usr/lib/libc_nano.a
-rw-r--r-- 2 root root 561896 Jul 28 07:13 /usr/arm-none-eabi/usr/lib/libc_nano.a
ar x /usr/arm-none-eabi/usr/lib/libc_nano.a
nm lib_a-memcpy.o
nm: lib_a-memcpy.o: no symbols

The REF2 libs are 7 times smaller than REF1 and provide no symbols!

Did you strip too much the objects before making the libraries ?.

**Comment by pullmoll** [comment]
That's probably a question for @teajay-fr who created and maintains this package as I did not run any tests with it myself. The template may require a `nostrip=yes`.

The package needs to be updated to gcc-8.2.0 rather sooner than later, which also is when we should test the result.

**Comment by teajay-fr** [comment]
That could very well be that the lib_nano hasn't been build correctly, or stripped too much.
I will have a look into this issue when I fix the compilation for gcc-8.2.0.
Could you send me a sample with which I could reproduce the issue you are facing ?

**Comment by herveq** [comment]
Ok
I commented 2 lines in the template:
#       find ${DESTDIR}/${_sysroot}/usr/lib \( -name "*.a" -or -name "*.o" \) -exec ${_triplet}-strip '{}' \;
#       find ${DESTDIR}/usr/lib/gcc/${_triplet}/${_gcc_version} \( -name "*.a" -or -name "*.o" \) -exec ${_triplet}-strip '{}' \;

generated a package, tested and  the link succeeded.
But the binary do not run. So I got my answer: this package is not suited for stm32!

For stm32, there is a need for some flags like mcpu=cortex-m3, ... and may be a special package.

So don't worry too much, the old compiler is still running, upgrade to gcc-8.2,  think about a new package or not. I will try to the necessary  flags in REF1.

I can make a sample code available on my web site.

**Comment by teajay-fr** [comment]
This should be fixed with pull request #5907

**Comment by sirikid** [comment]
@herveq could you try to build your project now, with the updated toolchain?

**Comment by sirikid** [comment]
Empty account with one activity -- this pr. I guess we'll never get feedback from him.
