### ISSUE TITLE
missing libjack-devel

### ISSUE THREAD

**Issue by VoidDuck** [void-linux/void-packages#18250]
Hello,

I need to build qjackctl from source, because the version from the void repository comes without ALSA sequencer support (I don't know why by the way).

Although jack, jack-devel and libjack are installed, qjackctl refuses to build telling me the jack library cannot be found. I looked for a possibly existing libjack-devel package in the repository but there is nothing like that. I suppose it is missing.

I had no problem building qjackctl a few months ago on another void system. I tried to build the same version I did at that time and it failed as well, so I'm sure the problem comes from void, where something must have changed since then.

### System

* xuname:  
  *Void 5.4.10_2 x86_64 GenuineIntel uptodate rF*
* package:  
  *libjack-1.9.14_1*

**Comment by Duncaen** [comment]
its `jack-devel`, its either their build system that is broken or you are missing things like `pkg-config`.

**Comment by newbluemoon** [comment]
Just a hunch, but did you forget to sync your local void-packages repository with the latest upstream master (e.g. something like `git pull upstream master`)? Otherwise xbps-src would try to pull in outdated versions that had been updated in the meantime and don’t exist anymore...

**Comment by VoidDuck** [comment]
I was indeed missing `pkg-config`. Sorry for the inconvenience.
