### ISSUE TITLE
Package request: the Vee One Suite (synthv1, samplv1, drumkv1, padthv1)

### ISSUE THREAD

**Issue by uzr123x** [void-linux/void-packages#18267]
rncbc's Qtractor and Qsynth already are in the repository, it would be great to have the Vee One Suite (synthv1, a subtractive synthesizer, samplv1, a sampler synthesizer, drumkv1, a drum-kit sampler and padthv1, an additive synthesizer) as well!
https://synthv1.sourceforge.io
https://samplv1.sourceforge.io
https://drumkv1.sourceforge.io
https://padthv1.sourceforge.io

**Comment by xtraeme** [comment]
really

**Comment by userabc123xyz** [comment]
they are simple, compact synths that fill in essential synthesizer niches. And they're all developed together as a suite. I think it's the best option if one needs a basic synth collection.
