### ISSUE TITLE
Package Request: photoflow

### ISSUE THREAD

**Issue by luzpaz** [void-linux/void-packages#18293]
> A fully non-destructive photo retouching program providing a complete RAW image editing workflow

Website: http://aferrero2707.github.io/PhotoFlow/  
Github: https://github.com/aferrero2707/PhotoFlow  
Installation: http://aferrero2707.github.io/PhotoFlow/install.html  
https://github.com/aferrero2707/PhotoFlow#downloading-and-compiling  
Development Blog: http://photoflowblog.blogspot.fr/

**Comment by Piraty** [comment]
giving up on photoflow for now, as their currently bundled librawspeed doesn't build with with gcc9 and using the latest release of it instead doesn't work that easily as well

**Comment by Piraty** [comment]
photoflow development stagnated
