### ISSUE TITLE
Package request: lxd-lts 3.0.1

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#1830]
[Announcement](https://discuss.linuxcontainers.org/t/lxd-3-4-has-been-released/2445)

New dependencies:

* https://github.com/CanonicalLtd/dqlite

* https://github.com/CanonicalLtd/go-dqlite/issues/13

* https://github.com/CanonicalLtd/candid (possibly optional, can't tell)

Not sure about versions needed (latest release/git/etc).

**Comment by iaroki** [comment]
I can't build it successfully with `build_style=go`. This new deps messed things up and require additional steps to compile custom sqlite/dqlite before build everything else.

**Comment by CameronNemo** [comment]
Maybe we could work on packaging dqlite, although it depends on a sizeable [changeset for sqlite](https://github.com/mackyle/sqlite/compare/version-3.24.0...CanonicalLtd:replication). Could be easier to wait and see if the changes are added first.

In the meantime, we should have a supported version of lxd in void. Might I suggest the LTS release?

**Comment by CameronNemo** [comment]
@iaroki I think we can use the same style of template for 3.4 too. The tarballs have a dist folder with all of the necessary dependencies, so we just need to short circuit the go build style's `go get` step.
