### ISSUE TITLE
[Bug] sqlite-replication replacing sqlite.

### ISSUE THREAD

**Issue by Duncaen** [void-linux/void-packages#18310]
As noticed in https://github.com/void-linux/void-packages/issues/18179, sqlite-replication which is the dependency of exactly one package (dqlite) replaces the system sqlite and therefor sqlite for all installed programs.
There is really no point in providing a patched version of sqlite just for this one package, it should either statically link the patched sqlite or use a different soname.

@CameronNemo

**Comment by CameronNemo** [comment]
Alpine appears to be modifying the lib prefix (see [here](https://gitlab.alpinelinux.org/alpine/aports/blob/master/testing%2Flxd%2FAPKBUILD#L129)). Alternatively I can try to patch the pkgconfig files, right?

**Comment by CameronNemo** [comment]
Was not sure on how to switch the soname, so went for the separate libdir solution and linked using that in dqlite and lxd. Please give feedback for #18327.
