### ISSUE TITLE
xbps-src bootstrap not working

### ISSUE THREAD

**Issue by bgkillas** [void-linux/void-packages#18354]
![picture](https://user-images.githubusercontent.com/55570525/72653459-fcd5d980-3958-11ea-8cb3-7dae5a2b0de2.png)

**Comment by Piraty** [comment]
This should
* have information about the used build host
* a log formatted correctly so everyone can enjoy readable text
* the full command that leads to this error

**Comment by xtraeme** [comment]
not enough info
