### ISSUE TITLE
Package request: mint-y-icons mint-y-theme

### ISSUE THREAD

**Issue by bgkillas** [void-linux/void-packages#18357]
i tried to make it here 
https://github.com/void-linux/void-packages/pull/18352
but i seem to not be able to for mint-y-theme since you have to build it and to build it you need sass and i cant find sass

**Comment by vpzomtrrfrt** [comment]
Looks like sassc *is* packaged, is that what you're looking for?

**Comment by bgkillas** [comment]
ruby sass or something not sassc

**Comment by ahesford** [comment]
Themes and icons do not meet the standard in our [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality_requirements).
