### ISSUE TITLE
xbps-src - unexpected masterdir cleanup

### ISSUE THREAD

**Issue by biopsin** [void-linux/void-packages#18363]
Heya, maybe I'm doin it wrong lately so sorry for the fuzz..
know I saw Duncan posting a remark somewhere about this sometime ago but I can't find it and I can't seem to find the actual merge that change this behavour.

### Expected behavior
Leave masterdir alone until a successfull pkg unless -C

### Actual behavior
cleans masterdir between manual stages "extract -> build -> install -> ..."
xbps-src -f build will clean masterdir and all manual edits are therefore lost inbetween.

makes it hard to test and resolve different issues in different stages when masterdir gets clean every time :D

**Comment by xtraeme** [comment]
Should be fixed in master, see 0ad3adfb0b9b59ec091ef708dddad0518d66ba6a

**Comment by xtraeme** [comment]
`-C` preserves `builddir` `destdir` and `autodeps`.

I verified this with master, so that it's already fixed.

**Comment by biopsin** [comment]
Thank you chief!!
