### ISSUE TITLE
ansible: odd DEFAULT_MODULE_PATH

### ISSUE THREAD

**Issue by jirib** [void-linux/void-packages#18418]
### System

* xuname:  
`Void 5.4.13_2 x86_64 GenuineIntel notuptodate rF`
* package:  
`ansible-2.9.2_2`

### Expected behavior

i expect DEFAULT_MODULE_PATH point to a system directory which has installed ansible plugins

### Actual behavior
```
# ansible --version
ansible 2.9.2
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /sbin/ansible
  python version = 3.8.1 (default, Dec 23 2019, 13:11:45) [GCC 9.2.0]

# ls /usr/share/ansible/plugins/modules
ls: cannot access '/usr/share/ansible/plugins/modules': No such file or directory
```

### Steps to reproduce the behavior

```
ls $(ansible --version | sed -n '/search path/s/.*, '\''\(.*\)'\'']/\1/p')

```

**Comment by xtraeme** [comment]
assigned to the pkg maintainer

**Comment by jirib** [comment]
BTW I use ansible from pip now and it shows this:

```
$ ansible --version
ansible 2.9.4
  config file = /home/jiri/.ansible.cfg
  configured module search path = ['/home/jiri/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jiri/.python3/lib/python3.8/site-packages/ansible
  executable location = /home/jiri/.python3/bin/ansible
  python version = 3.8.1 (default, Dec 23 2019, 13:11:45) [GCC 9.2.0]
```
My problem has started as problem with aws_ec2 inventory plugin which I could never make working with ansible from Void but it works fine with ansible from pip.

**Comment by zdykstra** [comment]
Are you using [aws_ec2](https://docs.ansible.com/ansible/latest/plugins/inventory/aws_ec2.html) from upstream?  What specific errors do you get when running a playbook in -vvv mode with the xbps packaged Ansible ?

[Local modules](https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html#adding-a-module-locally) seems to indicate that this is an upstream default location, with nothing actually added there by default. On a Debian host (installed via pip) and an Ubuntu host (installed via upstream dpkgs), those directories don't exist by default.

**Comment by jirib** [comment]
Sorry for delayed answer. I can't reproduce with ansible 2.9.10.

```
$ /usr/bin/ansible-inventory -i env/prod/ --list 2>&1 | jq '._meta.hostvars | ."10.72.4.110".placement'
{
  "availability_zone": "eu-west-3a",
  "group_name": "",
  "region": "eu-west-3",
  "tenancy": "default"
}
```
