### ISSUE TITLE
Package request: palemoon

### ISSUE THREAD

**Issue by Chexier** [void-linux/void-packages#18425]
Pale Moon is an Open Source, Goanna-based web browser, focusing on efficiency and customization.
https://www.palemoon.org/

**Comment by q66** [comment]
This has been requested and rejected before, with the stance being 1) we don't want more Firefox forks 2) palemoon branding issues (see the openbsd incident) making packaging it even less likely...

**Comment by Kokokokoka** [comment]
If one reads openbsd issue well enough, one can see what was wrong in porting. gentoo has a nice and working port. also, afaik the attitude changed over the past. I can provide a package, if anyone cares to upstream it.

**Comment by ashpooljh** [comment]
@Kokokokoka: I'm in no position to further advocate for upstreaming this package, but I'd like to keep it handy in a local repo for personal use. In case you were successful in packaging it for xbps, would you be so kind as to share the template in this thread?
