### ISSUE TITLE
inetutils-whois simply just doesn't work

### ISSUE THREAD

**Issue by shahab-vahedi** [void-linux/void-packages#18445]
### System

* xuname: 
  Void 5.4.12_1 x86_64 GenuineIntel notuptodate rFF

* package:  
  inetutils-whois-1.9.4_10
  iana-etc-20190504_1

### Expected behavior
```
> whois 4.2.2.4
...
NetRange:       4.0.0.0 - 4.127.255.255
CIDR:           4.0.0.0/9
...
```
### Actual behavior
```
> whois 4.2.2.4
getaddrinfo: Servname not supported for ai_socktype
```
### Steps to reproduce the behavior
Have `inetutils-whois` and `iana-etc` installed just the way they are, and you will bump into the error message shown in *Actual behavior*.

### How I fixed it for myself
By adding the following lines into my `/etc/services`:
```
whois              43/tcp
whois              43/udp
```

### Note
I am not sure in which package this fix should end up, `inetutils-whois` or `iana-etc`. I think latter is the case. I wanted to submit a patch but then I noticed that `iana-etc` uses an `update.sh` to fetch its `protocols` and `services`. Is it OK if I change `update.sh` to add those lines to `services` if they are not there?

**Comment by leahneukirchen** [comment]
I'd prefer to patch inetutils to use nicname to find this service. (But it's annoying legacy aliases don't show up in the official IANA assignments.)
