### ISSUE TITLE
mkfs -t jfs wants to read my answer before printing the question (silly bug)

### ISSUE THREAD

**Issue by loreb** [void-linux/void-packages#18499]
### System

* xuname:  
  Void 5.4.13_2 x86_64-musl GenuineIntel uptodate rFFF
* package:  
  jfsutils-1.1.15_2

### Expected behavior
mkfs -t jfs foo.img asks me if I really really want to destroy foo.img or /dev/sdXN (Y/N)

### Actual behavior
I have to press Y, **then** the question comes up - they forgot to fflush stdout :)

### Steps to reproduce the behavior
Run it on musl, glibc happens to work for some weird reason

**Comment by Gottox** [comment]
Ah, that bug.
