### ISSUE TITLE
Waybar: tray not visible

### ISSUE THREAD

**Issue by dinama** [void-linux/void-packages#18491]
### System

* xuname:  Void 5.4.13_2 x86_64 GenuineIntel notuptodate rrFF
* package:  Waybar-0.9.0_1

### Expected behavior

"modules-right": ["tray"] 

### Actual behavior

only warning in log:

 [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity

**Comment by damneq** [comment]
I think it depends on the app, pidgin doesn't show up in my tray either while telegram-desktop does

**Comment by dinama** [comment]
> I think it depends on the app, pidgin doesn't show up in my tray either while telegram-desktop does

im using telegram-desktop and i not see tray on waybar 
bash_profile:

```
export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=Unity
exec sway

```

sway config

```
bar {
    swaybar_command waybar
}
```

waybar

```
 "modules-right": ["tray",
```

**Comment by damneq** [comment]
Well, that's weird, could you give me your waybar config and style.css files so I can look into it?

**Comment by damneq** [comment]
Also, did it work in the earlier version of Waybar?

**Comment by dinama** [comment]
may be problem not in waybar - swaybar also not show tray icons

**Comment by damneq** [comment]
Do you have libappindicator installed, as waybar is asking for it?

**Comment by dinama** [comment]
problem solved after restarting sway!
