### ISSUE TITLE
Blender 2.80 is broken, may be a wider python problem.

### ISSUE THREAD

**Issue by sanderboer** [void-linux/void-packages#18567]
### System
* xuname:  
Void 5.4.14_1 x86_64 GenuineIntel notuptodate rrrmFFF
* package:  
blender-2.80_1 3D graphics creation suite

### Expected behavior
Open blender 2.8, select the default cube, add subdivision surface modifier, see the surface be subdivided. 

### Actual behavior
No surface is subdivided. No errors are given, not in program not in the terminal. Blender works normally and other modifiers work as expected, but the subdiv modifier remains inert.

### Steps to reproduce the behavior
Open blender 2.8, select the default cube, add subdivision surface modifier.

During blender install, there are some python byte-compie warnings, for instance:
`
Byte-compiling python code in /usr/share/blender/2.80/scripts...
/usr/share/blender/2.80/scripts/addons/add_curve_extra_objects/add_curve_aceous_galore.py:109: SyntaxWarning: "is" with
a literal. Did you mean "=="?
`

I deleted the pyc files in /usr/share/blender, but this changed nothing.

On a maybe related note, I am having issues getting the python bindings for ifcopenshell to compile correctly.

If anybody could give me pointers on how to proceed or on how investigate this matter further, I would appreciate that.

thx.
S

**Comment by Johnnynator** [comment]
Currently working on updating to 2.81a, Will take a look at this,

**Comment by sanderboer** [comment]
I just got a reply on the blender dev list that this behavior is due to the absence of the opensubdiv libraries.

Also, 2.82 is in beta now, maybe skip 2.81 ?

s


On 26 January 2020 14:32:35 CET, John Zimmermann <notifications@github.com> wrote:
>Currently working on updating to 2.81a, Will take a look at this,
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/void-linux/void-packages/issues/18567#issuecomment-578502275

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.
