### ISSUE TITLE
fwupd: /sys/firmware/efi/efivars was not mounted

### ISSUE THREAD

**Issue by dawidpotocki** [void-linux/void-packages#18612]
### System

* xuname:
  `Void 5.4.15_1 x86_64 GenuineIntel notuptodate rFFF`
* package:
  `fwupd-1.3.6_1`

### Expected behavior

fwupd is able to update firmware, efivars are mounted.

### Actual behavior

When I'm doing `$ fwupdmgr get-devices`, I get
`Update Error:        /sys/firmware/efi/efivars was not mounted`
Then when I try updating with `# fwupdmgr update`, I get
```
No upgrades for System Firmware: is not updatable
No upgrades for UEFI Device Firmware: is not updatable
No upgrades for UEFI Device Firmware: is not updatable
```

### Fix

The problem is that efivars are not mounted by Void. Doing something like this
will fix this issue.

```
$ sudo mount -t efivarfs efivarfs /sys/firmware/efi/efivars
```

After this, it should work just fine

```
$ sudo fwupdmgr get-updates
$ fwupdmgr get-devices
```

efivars have to be mounted as RW, not RO.
Since `/sys/firmware/efi/efivars` isn't immutable prior to kernel 4.5, doing
something like `rm -rf` on it can brick the device.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ed8b0de5a33d2a2557dce7f9429dca8cb5bc5879

### Steps to reproduce the behavior

1. Install `fwupd`
2. Run `fwupdmgr get-devices`
3. Run `fwupdmgr update` as root

**Comment by xtraeme** [comment]
void-runit must be updated to mount this correctly

**Comment by xtraeme** [comment]
Thanks for the heads up, we neeed to fix this asap

**Comment by xtraeme** [comment]
@void-linux/pkg-committers be my guest

**Comment by leahneukirchen** [comment]
I tried this on my system but it still doesn't find things to update (tho there are), any ideas what else could be missing?

**Comment by xtraeme** [comment]
Maybe there are no updates?

**Comment by Hoshpak** [comment]
I tried it on my system as well. I used fwupdmgr in the past to update a Logitech unifying receiver and it also detects the two SSDs in the system. Efivars is now mounted manually:

```
# mount | grep efivars
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,relatime)
```

But still I get:

```
├─System Firmware:
│     Device ID:           1d70a31dd3ff0941761550a38436fc990c6c3ff0
│     Current version:     0.0.11
│     Minimum Version:     0.0.11
│     Vendor:              ASUS (DMI:American Megatrends Inc.)
│     Update Error:        /sys/firmware/efi/efivars was not mounted
│     GUID:                7039436b-6acf-433b-86a1-368ec2ef7e1f
│     Device Flags:        • Internal device
│                          • Requires AC power
│                          • Needs a reboot after installation
│                          • Cryptographic hash verification is available
```

So either something else is required or the firmware cannot be updated via fwupdmgr. In that case the error message would be misleading.

The update command shows me:

```
# fwupdmgr update
No upgrades for Unifying Receiver: current version is RQR12.10_B0032: RQR12.10_B0032=same, RQR12.08_B0030=older, RQR12.07_B0029=older
```

So it only considers the Unifying receiver but not the other three devices. This could be because though they could theoretically be updated via fwupdmgr, there's no firmware for these devices on the server. The get-releases command shows that there are no releases for either of the SSDs and that UEFI is not updateable.

**Comment by dawidpotocki** [comment]
Hi, it looks like the issue is fixed?

```
$ mount -l | grep efivarfs
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)

# fwupdmgr update
• Thunderbolt Controller has no available firmware updates
• Samsung SSD 860 EVO M.2 1TB has no available firmware updates
• System Firmware has the latest available firmware version
• UEFI Device Firmware has the latest available firmware version
• UEFI Device Firmware has the latest available firmware version
• UEFI Device Firmware has no available firmware updates
• UEFI Device Firmware has no available firmware updates
```

**Comment by dawidpotocki** [comment]
Didn't get any reply and I believe that it's fixed. Closing.
