### ISSUE TITLE
Package request: genymotion

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#18645]
Simplify your Android tests with flexible, commitment-free pricing:
https://www.genymotion.com/

Edit1: I know it's not a free software, but we can add it to non-free repo.

Edit2: [Arch PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=genymotion).

**Comment by ericonr** [comment]
Gone with #20072
