### ISSUE TITLE
krusader: misplaced "rotate preview panel clockwise" button in 2.7.2

### ISSUE THREAD

**Issue by f3l-x** [void-linux/void-packages#18672]
in the latest krusader release 2.7.2 the button for rotating the preview panel is misplaced.
Instead of appearing beside the show panel button it is sitting somewhere in the address bar.
In 2.7.1 everything was fine, i have checked opensuse tumbleweed, too,  and there the 2.7.2 looks fine.
There has been a failure in the Travis CI Build for 2.7.2, maybe this is the reason?

**Comment by Chocimier** [comment]
Can't see this issue, but this version made address bar half-width for me, what rebuild fixes. Please check with 2.7.2_2 when it will appear.

**Comment by f3l-x** [comment]
Perfect, looks good now.
Thank you very much!
