### ISSUE TITLE
base-files update failure

### ISSUE THREAD

**Issue by chriscamacho** [void-linux/void-packages#18690]
### System

* xuname:  
  Void 5.4.16_1 x86_64 GenuineIntel notuptodate rrrmFFFF
* package:  
  base-files-0.140_12

### Expected behavior
That it would install without error
### Actual behavior
base-files-0.140_12: unpacking ...
Creating system directories/symlinks...
ERROR: base-files-0.140_12: [unpack] failed to extract file `./usr/lib64': Directory not empty
ERROR: base-files-0.140_12: [unpack] failed to extract files: Directory not empty
ERROR: base-files-0.140_12: [unpack] failed to unpack files from archive: Directory not empty
Transaction failed! see above for errors.

### Steps to reproduce the behavior
xbps-install -Su

**Comment by xtraeme** [comment]
Really? Try with bash -x

**Comment by chriscamacho** [comment]
-x ?

**Comment by Duncaen** [comment]
What is the output of `ls -lsa /usr/`?

**Comment by xtraeme** [comment]
Running it as root?

**Comment by chriscamacho** [comment]
yes.... running as root

**Comment by chriscamacho** [comment]
> [chris@chris-N150CU ~]$ ls -lsa /usr/
total 260
  4 drwxr-xr-x  11 2402   30   4096 Jan 31 15:42 .
  4 drwxr-xr-x  17 2402   30   4096 Apr 24  2012 ..
 72 drwxr-xr-x   2 2402   30  69632 Jan 31 15:38 bin
 12 drwxr-xr-x  99 2402   30  12288 Jan 29 22:42 include
128 drwxr-xr-x 116 2402   30 126976 Jan 31 15:38 lib
 20 drwxr-xr-x  13 root root  20480 Jan 31 15:38 lib32
  4 drwxr-xr-x   2 2402   30   4096 Apr 24  2012 lib64
  4 drwxr-xr-x  19 root root   4096 Jan 30 23:43 libexec
  4 drwxr-xr-x   8 2402   30   4096 Apr 24  2012 local
  0 lrwxrwxrwx   1 root root      3 Jan 31 14:35 sbin -> bin
  4 drwxr-xr-x 167 root root   4096 Jan 22 14:58 share
  4 drwxr-xr-x  11 root root   4096 Jan 30 10:41 src

**Comment by xtraeme** [comment]
Omg

**Comment by Duncaen** [comment]
So for some reason you have a directory at `/usr/lib64`.

**Comment by chriscamacho** [comment]
oh crap its....
```
ls lib64
libCg.so  libCgGL.so
```

**Comment by Duncaen** [comment]
This is not something that xbps itself can solve, it doesn't do `rm -rf /usr/lib64` because well there could be user data.

**Comment by chriscamacho** [comment]
how can I fix lib64  where does it symlink

**Comment by Duncaen** [comment]
```
0 lrwxrwxrwx  1 root  root  3 Jan 31 15:35 /usr/lib64 -> lib
```

**Comment by chriscamacho** [comment]
made lib64 sym link manually and xbps-install -f base-files all looks good - sorry for the noise it was a 3rd party lib install I should have looked at the script......!
