### ISSUE TITLE
gqrx: Segmentation fault

### ISSUE THREAD

**Issue by beardyjay** [void-linux/void-packages#18697]
### System

* xuname:  **Void 5.4.16_1 x86_64 GenuineIntel uptodate rrmFF**
* package:  **gqrx**

### Expected behavior

Program to launch 

### Actual behavior

Segmentation fault when trying to lanuch the program. 

> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-beardyjay'
gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.13.5
built-in source types: file fcd rtl rtl_tcp uhd hackrf rfspace airspy
Resampling audio 96000 -> 48000
BookmarksFile is /home/beardyjay/.config/gqrx/bookmarks.csv
[INFO] [UHD] linux; GNU C++ version 9.2.0; Boost_107200; UHD_3.14.1.1-0-unknown
Segmentation fault (core dumped)

### Steps to reproduce the behavior

* sudo xbps-install gqrx
* gqrx

**GDB output**

`Thread` 15 "gqrx" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc77fe700 (LWP 11095)]
0x00007ffff796b9e9 in boost::asio::detail::scheduler::shutdown() () from /usr/lib/libgnuradio-blocks-3.7.13.5.so.0.0.0

(gdb) bt
#0  0x00007ffff796b9e9 in boost::asio::detail::scheduler::shutdown() () from /usr/lib/libgnuradio-blocks-3.7.13.5.so.0.0.0
#1  0x00007ffff4776991 in ?? () from /usr/lib/libuhd.so.3.14.1
#2  0x00007ffff497882f in ?? () from /usr/lib/libuhd.so.3.14.1
#3  0x00007ffff431b96a in ?? () from /usr/lib/libuhd.so.3.14.1
#4  0x00007ffff481ec27 in ?? () from /usr/lib/libuhd.so.3.14.1
#5  0x00007ffff481f901 in ?? () from /usr/lib/libuhd.so.3.14.1
#6  0x00007ffff48209af in ?? () from /usr/lib/libuhd.so.3.14.1
#7  0x00007ffff4700ee2 in ?? () from /usr/lib/libuhd.so.3.14.1
#8  0x00007ffff4987eaa in ?? () from /usr/lib/libuhd.so.3.14.1
#9  0x00007ffff46f6aa9 in ?? () from /usr/lib/libuhd.so.3.14.1
#10 0x00007ffff5c6118f in __pthread_once_slow (once_control=0x5555559a6578, init_routine=0x7ffff608f3f0 <__once_proxy>)
    at pthread_once.c:116
#11 0x00007ffff49874ad in ?? () from /usr/lib/libuhd.so.3.14.1
#12 0x00007ffff609023f in ?? () from /usr/lib/libstdc++.so.6
#13 0x00007ffff5c58f27 in start_thread (arg=<optimized out>) at pthread_create.c:479
#14 0x00007ffff5d6de0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95`

**Comment by bra1nwave** [comment]
I'm looking into it
