### ISSUE TITLE
connman-1.37 should install connman-dbus.conf and connman-polkit.conf

### ISSUE THREAD

**Issue by basiliscos** [void-linux/void-packages#18713]
### System

* xuname:  

Void 5.4.16_1 x86_64 GenuineIntel notuptodate rrrmFFFFF

* package:  

connman-1.37_3

### Expected behavior

no annoying dbus messages like

```
2020-02-01T18:59:33.746456+03:00 localhost dbus-daemon\[773\]: \[system\] Rejected send message, 3 matched rules; type="method\_call", sender=":1.29" (uid=1000 pid=1597 comm="telegram-desktop ") interface="net.connman.Manager" member="GetTechnologies" error name="(unset)" requested\_reply="0" destination="net.connman" (uid=0 pid=888 comm="connmand -n ")
```

the tools like `connman-gtk`, `cmst` should work without root priveledges

### Actual behavior

userland network configuration tools not work from user

### Steps to reproduce the behavior

just install connman and launch `connman-gtk`

I have found the advice here https://stackoverflow.com/questions/26280616/connman-running-from-within-the-source-code-repository

when I just copied `connman-dbus.conf` and `connman-polkit.conf` into `/etc/dbus-1/system.d/` everything went fine.

**Comment by fiebertraum** [comment]
didnt solve my problem,

**Comment by basiliscos** [comment]
which one? did u tried to reboot?

**Comment by Val6789** [comment]
I have the same problem. The proposed fix dit not work.

**Comment by kedodrill** [comment]
Make sure that you add your current user to the `network` group. You should then be able to run all the connman commands as that user.

**Comment by apvodney** [comment]
I had this same problem, none of the connman clients could connect to connman unless they were run as root. I installed `polkit` and made no other configuration changes aside from my user being a member of the `network` group, and it resolved the issue.

I would venture to guess just adding `polkit` to the dependencies of the `connman` package should fix this.
