### ISSUE TITLE
php cannot load imagick module: undefined symbol: add_next_index_zval

### ISSUE THREAD

**Issue by mithodin** [void-linux/void-packages#18765]
When I install the php-imagick module from the official repos, php can't load the module because of a missing symbol. However, if I build the module locally using xbps-src and install that version, it loads fine.

### System
* xuname: Void 5.4.16_1 x86_64 GenuineIntel/VM uptodate rrFFF
* package:  php-imagick-3.4.3_5

### Expected behavior
Load the imagick module by placing extension=imagick.so into php.ini

### Actual behavior
Php tries to load the library, but fails, saying
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/lib/php/modules/imagick.so (/usr/lib/php/modules/imagick.so: undefined symbol: add_next_index_zval), /usr/lib/php/modules/imagick.so.so (/usr/lib/php/modules/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

### Steps to reproduce the behavior
Install and activate php-imagick

**Comment by xtraeme** [comment]
php-imagick needs to be rebuilt

**Comment by mithodin** [comment]
The same goes for php-apcu, apparently.

**Comment by mindaugasvcs** [comment]
The same is for php_event.dll

**Comment by ericonr** [comment]
Please open a new issue if you're facing a similar issue.
