### ISSUE TITLE
musl openssh format-overflow

### ISSUE THREAD

**Issue by tleydxdy** [void-linux/void-packages#18818]
### System

* xuname:  
  `Void 5.4.17_1 x86_64-musl GenuineIntel uptodate rrnFFF`
* package:  
  `openssh-8.1p1_2`

### Expected behavior
Build pass
### Actual behavior
Build error at 
```
sftp-server.c:869
sftp-server.c:1341
```
because of `-Werror=format-overflow=`
### Steps to reproduce the behavior
`./xbps-src -N pkg openssh`

**Comment by pullmoll** [comment]
I can not confirm.
For me openssh-8.1p1_2 builds with my home grown repository for x86_64-musl and i686-musl w/o errors.

**Comment by tleydxdy** [comment]
turns out it's because of `-O3` :(
