### ISSUE TITLE
mdocml build fails at configure

### ISSUE THREAD

**Issue by tleydxdy** [void-linux/void-packages#18816]
### System

* xuname:  
  `Void 5.4.17_1 x86_64-musl GenuineIntel uptodate rrnFFF`
* package:  
  `mdocml-1.14.5_3`

### Expected behavior
Build pass
### Actual behavior
Build fails with 
```
make: echo: No such file or directory
```
Line 44 in `builddir/mandoc-1.14.5/configure` seems to be causing it
### Steps to reproduce the behavior
```
./xbps-src -N pkg mdocml
```

**Comment by leahneukirchen** [comment]
This is because PATH is empty, so `echo` cannot be found.  I wonder how this ever worked.

Perhaps @ischwarze has an idea?

**Comment by leahneukirchen** [comment]
```
23:59:07      <leah2> make 4.3 doesnt seem to spawn a shell
23:59:15      <leah2> if you force a shell with > /dev/stdout, it works
```

**Comment by tleydxdy** [comment]
where do I put that?

**Comment by ischwarze** [comment]
I think adding that printf/env/make line to automatically detect the default compiler that make(1) uses on the system was a bad idea, i tried to be too clever when writing that.  It's not the first time that line is causing portability issues.

I think for the next mandoc release, i'll simply set CC=cc by default - after all, POSIX specifies cc(1) - and ask people who want to use a particular compiler to set CC in configure.local.  Besides, most ANSI C compilers ought to work anyway, so finding the best one shouldn't even be all that important.

**Comment by xtraeme** [comment]
Yeah, sounds good

**Comment by ischwarze** [comment]
Committed:
https://cvsweb.bsd.lv/mandoc/configure#rev1.72
https://cvsweb.bsd.lv/mandoc/configure.local.example#rev1.37
Thanks for reporting and investigating, and thanks to Juan for confirming the idea.
