### ISSUE TITLE
j: broken: binaries missing

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/void-packages#18857]
j-901.e_2 does not contain the j binaries!

```
% xls j |grep lib
/usr/share/j/system/main/stdlib.ijs
```

@xelxebar

**Comment by xelxebar** [comment]
That's bad. `xbps-query -Rf j | grep lib` gives me the same; however, nuking <hostdir>/binpkgs and rebuilding locally, this is what I see and what we want in the repo:

```
$ xls j | grep lib
/usr/lib/j/j64/jconsole
/usr/lib/j/j64/libj.so
/usr/lib/j/j64avx/jconsole
/usr/lib/j/j64avx/libj.so
/usr/lib/j/j64avx2/jconsole
/usr/lib/j/j64avx2/libj.so
/usr/share/j/system/main/stdlib.ijs
```

 I do vaguely remembered that the build scripts exit without error if given the wrong parameters. Setting `jplatform=foo j64x=bar' confirms this.

My guess is that, on the machine/cluster that builds for the main repo, the `do_build` is degrading to a noop. `/usr/lib/j` gets populated from `<wrksrc>/bin`, the latter being where the build outputs reside. This would create an empty `/usr/lib/j` which ends up getting elided in the final packaging phase.

That said, are the build logs still hanging around? Grepping for `no case for those parameters` would confirm the above hypothesis.

**Comment by leahneukirchen** [comment]
Fixed.
