### ISSUE TITLE
Package break: libgcc and libstdc++ break libcilkrts?

### ISSUE THREAD

**Issue by The-BigDaddy** [void-linux/void-packages#1889]
### System info

`uname -a`: Linux void 4.17.14_1 #1 SMP PREEMPT Sat Aug 11 18:42:04 UTC 2018 x86_64 GNU/Linux

### Effected packages

* libgcc-8.2.0_1 (and 32-bit package)

* libstdc++-8.2.0_1 (and 32-bit package)

* libcilkrts-7.3.0_4 (and 32-bit package)

### How it happenend

IRC, I think `libcilkrts` is apart of the `gcc-multilib` package. Now what I installed that for, I don't know. Anyway all I did was run a simple update with `sudo xbps-install -Svu`, and in the past 24 some-odd hours this error has still been shown

    libgcc-8.2.0_1 (update) breaks installed pkg `libcilkrts-7.3.0_4'
    libgcc-32bit-8.2.0_1 (update) breaks installed pkg `libcilkrts-32bit-7.3.0_4'
    libstdc++-8.2.0_1 (update) breaks installed pkg `libcilkrts-7.3.0_4'
    libstdc++-32bit-8.2.0_1 (update) breaks installed pkg `libcilkrts-32bit-7.3.0_4'
    Transaction aborted due to unresolved dependencies.

So I'm not sure if anyone has seen this and/or attempted to fix this. Haven't seen anything regarding `gcc-multilib` or `libcilkrts` in the PRs, so I thought I'd report this just in case.

**Comment by pullmoll** [comment]
gcc-multilib needs a revbump after I removed libcilkrts, which was removed from gcc-8.2.0

**Comment by pullmoll** [comment]
Should be solved now. Closing.
