### ISSUE TITLE
linux5.5: consider switching from PREEMPT to PREEMPT_VOLUNTARY

### ISSUE THREAD

**Issue by ahesford** [void-linux/void-packages#18940]
I'm opening this issue to start a discussion about switching the generic kernel config from full PREEMPT to PREEMPT_VOLUNTARY. The kernel configuration documents suggest using PREEMPT for a low-latency desktop and disabling preemption for a server. The suggested use case for PREEMPT_VOLUNTARY is just a "desktop".

PREEMPT_VOLUNTARY adds explicit preemption points in the kernel that allow syscalls to be interrupted [[1]](https://www.linuxtopia.org/online_books/linux_kernel/kernel_configuration/re152.html). Full PREEMPT takes this a step further by allowing interruption between the explicit points. This comes at the cost of runtime overhead and a corresponding reduction in processing throughput [[2]](https://www.linuxtopia.org/online_books/linux_kernel/kernel_configuration/re153.html). The desired effect of these options is to make the system appear more responsive by interrupting other tasks more frequently.

There is an objective reason for favoring the switch in the near term; the ZFS kernel module attempts to use preemptible RCU symbols when PREEMPT is configured in the kernel, and these symbols have been marked GPL-only for Linux 5.5. The ZFS modules installed by the Void package will not build against 5.5. When PREEMPT_VOLUNTARY is configured, the kernel uses TREE_RCU instead of PREEMPT_RCU, and the ZFS modules build as expected.

In the long term, I expect the ZoL crowd will fix the compatibility and this motivation will be moot. The remaining question is whether PREEMPT_VOLUNTARY is a more generic option for the stock Void kernel. Attempting to answer this question probably amounts to fighting a holy war. Nevertheless, there may be value in asking it.

I've been asked to provide some benchmarks (e.g., Phoronix Test Suite) to support the proposed switch. To meaningfully measure the tradeoff between latency and throughput as a result of the change in preemption configuration will be difficult or impossible. In any case, the benchmarks will almost certainly favor a particular use case that may or may not be relevant to any specific user. Some people have tried; see [this Raspberry Pi discussion](https://github.com/raspberrypi/linux/issues/1216) that includes some simple timing tests, or [this benchmark using cyclictest and sockperf](https://www.codeblueprint.co.uk/2019/12/23/linux-preemption-latency-throughput.html).

Other distributions use a variety of defaults:
1. Like Void, [Arch Linux](https://git.archlinux.org/svntogit/packages.git/tree/trunk/config?h=packages/linux) uses PREEMPT and a 1000 Hz tick.
2. Ubuntu uses PREEMPT_VOLUNTARY with a 250 Hz tick. Ubuntu also offers alternative kernel packages with different preemption models.
3. The aforementioned Raspberry Pi discussion indicates that their default is PREEMPT_VOLUNTARY with a 100 Hz tick.
4. [Debian](https://packages.debian.org/sid/kernel/linux-config-5.4), like Ubuntu, uses PREEMPT_VOLUNTARY with a 250 Hz tick.

As PREEMPT_VOLUNTARY seems to be a tradeoff between throughput and latency, it seems like a prime candidate for generic kernel configs, where the intended audience will have diverse needs and may not be best served by the fully preemptible kernel. Whether the tick rate should be reduced from 1000 Hz to a lower value is a separate issue.

**Comment by jrigg** [comment]
Not a dev, but I suspect the number of gamers and multimedia users on Void far exceeds the number of ZFS users. For the former, PREEMPT and 1000 Hz tick have definite advantages.

**Comment by q66** [comment]
I was never able to see much of a difference in responsiveness between `PREEMPT_VOLUNTARY` and `PREEMPT` tbh.

BTW, the non-x86 kernels are generally configured to use `PREEMPT_VOLUNTARY` (with 250 Hz tick) already. Also when I was configuring the PowerPC kernels, it turned out that using `PREEMPT` results in the kernels not booting at all on a fair amount of machines... that said, I'm not seeing any responsiveness issues on those either.

**Comment by ahesford** [comment]
> Not a dev, but I suspect the number of gamers and multimedia users on Void far exceeds the number of ZFS users. For the former, PREEMPT and 1000 Hz tick have definite advantages.

I agree that using full PREEMPT probably provides benefit to gamers. The multimedia benefits depend on the kind of multimedia work being done. Time-sensitive transcoding operations may actually be helped by switching to PREEMPT_VOLUNTARY (or even PREEMPT_NONE) because the reduced emphasis on low latency will not steal computational time from the transcoding operation. (This is more obvious in resource-constrained environments like the [Raspberry Pi](https://github.com/raspberrypi/linux/issues/1216#issuecomment-163200058).)

The ZFS issue brought my attention to this configuration, but it is not the primary motivator for the change. Like I said, I'm sure ZFS on Linux upstream will work around this latest salvo in the GPL/CDDL wars. The real question is where the center of mass is for Void users. Are most of them gamers that will be sensitive to the latency benefits of PREEMPT, are most of them interested in computational throughput that will be sensitive to the throughput costs of PREEMPT (and, to a lesser extent, PREEMPT_VOLUNTARY), or are the centrally clustered or uniformly distributed? The generic kernel ought to target that center of mass as best as possible.

**Comment by ahesford** [comment]
> I was never able to see much of a difference in responsiveness between `PREEMPT_VOLUNTARY` and `PREEMPT` tbh.
> 
> BTW, the non-x86 kernels are generally configured to use `PREEMPT_VOLUNTARY` (with 250 Hz tick, 100 for aarch64) already. Also when I was configuring the PowerPC kernels, it turned out that using `PREEMPT` results in the kernels not booting at all on a fair amount of machines... that said, I'm not seeing any responsiveness issues on those either.

This seems to argue in favor of switching to PREEMPT_VOLUNTARY. Anecdotally, on a Ryzen 5 3600 six-core (twelve-thread) system, I've seen no unacceptable latency using a custom 5.5.2_2 config that uses PREEMPT_VOLUNTARY and HZ_250 while watching a (software-decoded) 3840x1920@30fps VP9 video (generally burning around 100% CPU) from YouTube and playing a 256 kbps AAC audio stream through cmus while typing this response and doing some mousing around during a 12-thread [cyclictest]( https://git.kernel.org/pub/scm/linux/kernel/git/clrkwllms/rt-tests.git) latency benchmark. The *maximum* latency measurements on each core during this testing was, in **micro**sec:

    1189, 1113, 1067, 884, 766, 166, 150, 142, 135, 128, 118, 78

while the average latencies were all 1 or 2 microsec.

Again, this is one anecdote. Everybody will have a unique story.

**Comment by travankor** [comment]
Clear Linux uses PREEMPT_VOLUNTARY, too.

Also should consider setting CONFIG_NO_HZ_FULL for 64-bit arches.

**Comment by xtraeme** [comment]
more info: https://www.kernel.org/doc/html/v5.5/timers/no_hz.html

**Comment by xtraeme** [comment]
@travankor I'm curious, what does clearlinux use for HZ?

**Comment by xtraeme** [comment]
I don't have any objection against PREEMPTY_VOLUNTARY and HZ=250 if it does not make a reasonable difference.

Why HZ=250? because this would make our kernels use shared options between archs.

**Comment by travankor** [comment]
They have it set to 1000HZ but they only support x86_64

**Comment by xtraeme** [comment]
I've been running a kernel with PREEMPT_VOLUNTARY for some hours already and didn't notice any measurable difference.

**Comment by q66** [comment]
```
1. Never omit scheduling-clock ticks (CONFIG_HZ_PERIODIC=y or CONFIG_NO_HZ=n for older kernels). You normally will -not- want to choose this option.
2. Omit scheduling-clock ticks on idle CPUs (CONFIG_NO_HZ_IDLE=y or CONFIG_NO_HZ=y for older kernels). This is the most common approach, and should be the default.
3. Omit scheduling-clock ticks on CPUs that are either idle or that have only one runnable task (CONFIG_NO_HZ_FULL=y). Unless you are running realtime applications or certain types of HPC workloads, you will normally -not- want this option.
```

Sounds like our config is correct already.

**Comment by ahesford** [comment]
In another uncontrolled and non-rigorous test, I ran PowerTOP on a Dell XPS 15 9575 laptop with the stock configuration (PREEMPT and HZ=1000) and never saw fewer than 700 wakeups per second when doing nothing else on the system. With PREEMPT_VOLUNTARY and HZ=250, the same idle observation generally stays below 700 wakeups per second, and sometimes falls as low as 400/sec.

**Comment by q66** [comment]
It is known that a soft-realtime kernel with high tick rate will have a negative effect on battery life/power usage.... it's a tradeoff

**Comment by jrigg** [comment]
Just tested 5.4.18 with PREEMPT_VOLUNTARY and 256 Hz tick on my audio workstation (4-core 2.5GHz Athlon II, x86_64 glibc). I get audible dropouts even at maximum jackd latency (21.3 ms at 48kHz sample rate) on a typical multitrack mix session which runs without a problem on the current standard Void kernel.

That said, I'm aware this is a niche application and compiling a custom kernel is not a problem for me.

**Comment by xtraeme** [comment]
@jrigg try with HZ=300 instead

**Comment by xtraeme** [comment]
I think the x86 default (HZ=1000) is good enough, just switching to PREEMPT_VOLUNTARY should be enough for zfs.

**Comment by jrigg** [comment]
More tests on audio workstation:
PREEMPT_VOLUNTARY with 300 Hz: Fewer dropouts than 250 Hz, but still a lot.
PREEMPT_VOLUNTARY with 1000 Hz: Still a few dropouts, too many to be usable.
PREEMPT with 1000 Hz: No dropouts.

**Comment by q66** [comment]
audio workstation is a niche case that calls for `CONFIG_PREEMPT`... the tick rate won!'t actually make too much of a difference

**Comment by ahesford** [comment]
Closing: PREEMPT_VOLUNTARY has been changed for x86_64 and i386 in linux5.5 and ZFS builds as expected.
