### ISSUE TITLE
named service start-up

### ISSUE THREAD

**Issue by kagalle** [void-linux/void-packages#18961]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
Void 5.4.17_1 x86_64 AuthenticAMD notuptodate rFF
* package:  
  *affected package(s) including the version*
bind-9.11.13_1

### Expected behavior
service starts
### Actual behavior
service fails to start, process left in defunct state
### Steps to reproduce the behavior
In a just installed and updated system, I found that running named using the -g switch directly from the command line worked, but from the sv script, was failing with defunct.
I changed the -f switch -g in /etc/sv/named/run

mkdir -p /var/run/named || exit 1
chown named:named /var/run/named || exit 1
exec named -u named -g -c /etc/named/named.conf

and sv start named worked.

**Comment by ericonr** [comment]
Did you have a syslog daemon running? I think `named` with `-f` would require one.
