### ISSUE TITLE
`nix-shell -p hello`, does not work.

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#18970]
### System

* xuname:  
Void 5.4.15_1 x86_64 GenuineIntel notuptodate hold rrDDDFFF
* package:  
  nix-2.3.2_2  

### Expected behavior
I want to see a properly working __hello__ example of nix package manager without any issue.

### Actual behavior
After installing nix package, if you try to use: `nix-shell -p hello`, it'll produce this error:
```
warning: Nix search path entry '/home/linarcx/.nix-defexpr/channels' does not exist, ignoring
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13
```
If you try it with __sudo__:
`error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13`

Also, whenever you want to login again, you'll we see this message:
Also when i restart and login again in my system, it says:
```
mkdir: cannot create directory '/nix/var/nix/profiles/per-user/linarcx': Permission denied
WARNING: bad ownership on /nix/var/nix/profiles/per-user/linarcx
```

### Steps to reproduce the behavior
1. Install nix package
2. re-login

**Comment by LinArcX** [comment]
cc @xtraeme

**Comment by xtraeme** [comment]
How about reading about its usage? Their documentation is good.

**Comment by xtraeme** [comment]
If you tried to run it via sudo means that you didn't read anything about it. This is now how things work

**Comment by xtraeme** [comment]
If you expect someone to give you step by step instructions I won't be that guy

**Comment by LinArcX** [comment]
You mean here:
https://nixos.org/nix/manual/#chap-installation

But it gives me errors:
```
╰   sh <(curl https://nixos.org/nix/install) --no-daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2399  100  2399    0     0   2403      0 --:--:-- --:--:-- --:--:--  2401
downloading Nix 2.3.2 binary tarball for x86_64-linux from 'https://nixos.org/releases/nix/nix-2.3.2/nix-2.3.2-x86_64-linux.tar.xz' to '/tmp/nix-binary-tarball-unpack.iXZZCLO5FP'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.1M  100 15.1M    0     0   373k      0  0:00:41  0:00:41 --:--:--  418k
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
/proc/self/fd/11: failed to unpack 'https://nixos.org/releases/nix/nix-2.3.2/nix-2.3.2-x86_64-linux.tar.xz'
```

If you mean this part:
https://nixos.org/nix/manual/#ch-basic-package-mgmt

I got these errors:
```
 nix-channel --update                      
unpacking channels...
while setting up the build environment: executing '/usr/bin/bash': No such file or directory
builder for '/nix/store/b8l4jqfrjdpb1mji2p162bbw98zia0lp-nixpkgs-20.03pre211998.57ed5db343f.drv' failed with exit code 1
error: build of '/nix/store/b8l4jqfrjdpb1mji2p162bbw98zia0lp-nixpkgs-20.03pre211998.57ed5db343f.drv' failed
```
error: program '/usr/bin/nix-env' failed with exit code 100

**Comment by yopito** [comment]
Read the log you copy/paste: you probably missing `xz` (case #1) and `bash`  (case #2)

**Comment by LinArcX** [comment]
> Read the log you copy/paste: you probably missing `xz` (case #1) and `bash` (case #2)

So, what can I do?

**Comment by mephistopheles-8** [comment]
I also had issues getting Nix to work out-of-the box on Void. 

The problems with `bash` and `xz` stem from those programs not being linked in the Nix sandbox.  I temporarily added `build-use-sandbox=false` to `/etc/nix/nix.conf` before running `nix-channel --update`.    

There is an option, `build-sandbox-paths`, that may be of interest.  Mine is set to the following, but I've only done limited testing and have not verified that it matters:

    build-sandbox-paths = /bin/sh=/bin/sh /usr/bin/bash=/usr/bin/bash /usr/bin/bzip2=/usr/bin/bzip2 /usr/bin/env=/usr/bin/env /usr/bin/gzip=/usr/bin/gzip /usr/bin/mkdir=/usr/bin/mkdir /usr/bin/mv=/usr/bin/mv /usr/bin/tar=/usr/bin/tar /usr/bin/tr=/usr/bin/tr /usr/bin/xz=/usr/bin/xz

The following might be relevant:
https://github.com/NixOS/nix/issues/3337
https://github.com/NixOS/nix/issues/2673
https://github.com/asppsa/archlinux-nix

**Comment by kmltdr** [comment]
I had exactly the same problem, but thanks to @mephistopheles-8's suggestion, I managed to run hello example. What I did:
- add myself to `nixbld` group
- enable nix-daemon: `ln -s /etc/sv/nix-daemon/ /var/service/`
- add `build-use-sandbox = false` to `/etc/nix/nix.conf `
- add nixpkgs-unstable channel: `nix-channel --add http://nixos.org/channels/nixpkgs-unstable nixpkgs`

**Comment by xtraeme** [comment]
@kmltdr thanks for the info, I've updated the pkg to set `build-use-sandbox = false` for now.
