### ISSUE TITLE
Enable PDF support in cups

### ISSUE THREAD

**Issue by MagicRB** [void-linux/void-packages#19017]
### System

* xuname: Void 5.4.18_1 x86_64 AuthenticAMD uptodate rrrrmmnFFFF
* package:  CUPS 2.3.1 

### Expected behavior

Being able to use `lp` to print a pdf directly

### Actual behavior

`lp` says pdfs are not suported
`lpr: Unsupported document-format "application/pdf".`

### Steps to reproduce the behavior

Install CUPS, attempt to print a pdf using the `lp` command line utility

### Solution

From what I read adding the `--enable-pdftops` to CUPS configure script should solve this problem.

**Comment by Piraty** [comment]
i added cups-pdf some time ago, does that suit you?
if cups is capable on its own, then cups-pdf is obsolete. i'll look into this

**Comment by MagicRB** [comment]
I stumbled upon an arch thread where they were discussing exactly this, when I get home I'll find it

**Comment by MagicRB** [comment]
Found it, https://bbs.archlinux.org/viewtopic.php?id=70393 . also cups is refusing to print a PDF, I'm thinking these two things might be related

**Comment by Piraty** [comment]
that info is long outdated, current cups' configure doesn't have an option called `--enable-pdftops`.
My findins show however that `pdftops` is part of `cups-filters`, maybe your setup lacks that package?

**Comment by MagicRB** [comment]
Might be true, though I no longer use void linux, I switched away when the repos died, or at least they died on all my computers. I'll be reinstalling soon, so I'll give void a try once again

**Comment by Piraty** [comment]
feel free to re-open if you have issues.

**Comment by tuxslack** [comment]
**How to print to PDF printer in Void Linux?**

$ uname -r
**6.12.21_1**


$ xbps-query -l | grep cups-
ii cups-2.4.11_1                                    Common Unix Printing System
ii cups-devel-2.4.11_1                              Common Unix Printing System - development files
ii cups-filters-2.0.0_1                             OpenPrinting CUPS Filters
ii cups-pdf-3.0.1_1                                 PDF printer for cups
ii libcups-2.4.11_1                                 Common Unix Printing System - client runtime shared libraries
ii libcups-32bit-2.4.11_1                           Common Unix Printing System - client runtime shared libraries (32bit)
ii python3-cups-2.0.4_2                             Python3 CUPS bindings



sudo lpadmin -x cups-pdf


sudo find /usr/share/cups -iname "*.ppd"
/usr/share/cups/model/CUPS-PDF_opt.ppd
/usr/share/cups/model/CUPS-PDF_noopt.ppd


lpadmin -p cups-pdf -E -v cups-pdf:/ -P /usr/share/cups/model/CUPS-PDF_opt.ppd
lpadmin: Printer drivers are deprecated and will stop working in a future version of CUPS.


$ lp -d cups-pdf 1.txt
id de requisição é cups-pdf-487 (1 arquivo(s))


**The generated file is a blank PDF**

$ ls ~/PDF/
