### ISSUE TITLE
can't find or install claws-mail-dbg

### ISSUE THREAD

**Issue by haheute** [void-linux/void-packages#1905]
### System

* xuname:  
  Void 4.17.14_1 x86_64-musl AuthenticAMD notuptodate rF
* package:  
 claws-mail-dbg-3.17.0

### Expected behavior
`sudo xbps-install claws-mail-dbg` installs the package 

### Actual behavior
Package 'claws-mail-dbg' not found in repository pool.

### Steps to reproduce the behavior
The package search on the void website finds the package, but xbps not.
help

**Comment by maxice8** [comment]
```
$ xbps-query -Rs claws-mail
[-] claws-mail-3.17.0_1             The user-friendly, lightweight, and fast email client
[-] claws-mail-devel-3.17.0_1       The user-friendly, lightweight, and fast email client - development files
[-] claws-mail-32bit-3.17.0_1       The user-friendly, lightweight, and fast email client (32bit)
[-] claws-mail-devel-32bit-3.17.0_1 The user-friendly, lightweight, and fast email client - development files (32bit)
[-] claws-mail-dbg-3.17.0_1         The user-friendly, lightweight, and fast email client (debug files)
```

did you enable debug repos ?

**Comment by haheute** [comment]
omg. you're right. it works
