### ISSUE TITLE
xbps-src -E desc wrong (or behavior (?))

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#19057]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *affected package(s) including the version*

### Expected behavior
Behavior and desc to match

### Actual behavior
`-E` only compiles a package if it isn't in local AND remote repos
Desc only talk about local repos.
https://github.com/void-linux/void-packages/blob/master/xbps-src#L154

**Comment by xtraeme** [comment]
Looks like desc needs to be updated

**Comment by ericonr** [comment]
Ping?

**Comment by Johnnynator** [comment]
This is still the case. Description and behavior doesn't match.

**Comment by Duncaen** [comment]
hmm I prefer the current behavior, is the documented behavior any useful in cases where its not also used with `-N`?

**Comment by Johnnynator** [comment]
> hmm I prefer the current behavior, is the documented behavior any useful in cases where its not also used with `-N`?

It helped me to prevent building successful packages twice without having to revbump them when testing if a change in a different package was breaking. So yeah at least I had my usecase.

I do not really care about which behavior we pick.

**Comment by paper42** [comment]
fixed in #34559
