### ISSUE TITLE
scanmem: split cli from gui?

### ISSUE THREAD

**Issue by toluschr** [void-linux/void-packages#19098]
# System

* xuname:  
  `Void 5.4.18_1 x86_64 AuthenticAMD notuptodate rrrrmmnFFFFFFFF`
* package:  
  `scanmem>=0`

### Expected behavior
Since `scanmem` is meant for analyzing memory and debugging, I don't want `GameConqueror`, which is meant for cheating bundled with it. I don't really need the ui anyways.

### Actual behavior
Installing `scanmem` installs `GameConqueror`

### Steps to reproduce the behavior
`# xbps-install scanmem`

I just want to hear other peoples opinion on this and if creating a pull-request is necessary.

**Comment by mvf** [comment]
I have no stake in `scanmem`, but I agree that `GameConqueror` should be a separate package, particularly since it would be `noarch`. If you do decide to submit a PR, you can make it even more compelling by also switching to Python 3.

**Comment by gspe** [comment]
@toluschr maybe this can be closed now
