### ISSUE TITLE
Package request: pam_ssh_agent_auth

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#19109]
Pam module for sudo authentication based on ssh-agent:
[https://packages.gentoo.org/packages/sys-auth/pam_ssh_agent_auth](https://packages.gentoo.org/packages/sys-auth/pam_ssh_agent_auth)
[https://github.com/dfberger/pam-ssh-agent-auth](https://github.com/dfberger/pam-ssh-agent-auth)
[https://sourceforge.net/projects/pamsshagentauth/](https://sourceforge.net/projects/pamsshagentauth/)

**Comment by classabbyamp** [comment]
done in #20656
