### ISSUE TITLE
Package request: diffoscope

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/void-packages#19153]
https://diffoscope.org/

> In-depth comparison of files, archives, and directories.

Useful for debugging reproducible builds.

**Comment by Chocimier** [comment]
Let's see.

**Comment by Anachron** [comment]
Source: https://salsa.debian.org/reproducible-builds/diffoscope
License: https://salsa.debian.org/reproducible-builds/diffoscope/blob/master/COPYING
Deps: https://salsa.debian.org/reproducible-builds/diffoscope#external-dependencies

@Chocimier if you don't create a PR I'll give myself a try.

**Comment by Chocimier** [comment]
How much time do I have?

**Comment by Chocimier** [comment]
Resolved by #19191.
