### ISSUE TITLE
Package request: Trinity Desktop Environment

### ISSUE THREAD

**Issue by kasesag** [void-linux/void-packages#19243]
TDE website:
https://www.trinitydesktop.org/
Arch Linux PKGBUILDs:
https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD

**Comment by Chocimier** [comment]
Inclusion of qt3 into repository is unlikely.

**Comment by kpvsky** [comment]
@Chocimier but there's a fork called tqt3 that's still maintained and used by this desktop environment. So you don't have to rely on an old and officially unsupported qt3. 

tqt3 - https://mirror.git.trinitydesktop.org/cgit/tqt3/

**Comment by xtraeme** [comment]
Right, as @kpvsky pointed out TDE maintains the qt3 sw. I'd like to see TDE in void :-)

**Comment by xtraeme** [comment]
Because I've got good feelings when I talk about KDE3 :-)

**Comment by BenEvolent333** [comment]
Has this been assigned? I might take a look at it if not

**Comment by kpvsky** [comment]
@BenEvolent333 I don't think so.

**Comment by ScrelliCopter** [comment]
I'm curious about this too so I'm going to see if I can get a build happening, will post here if it goes anywhere.

**Comment by ScrelliCopter** [comment]
Status update:
I have the packages [here](https://wiki.trinitydesktop.org/How_to_Build_TDE_Core_Modules) up to `tdebase` building and running core applications with a few features turned off, you can check the current progress [here](https://github.com/ScrelliCopter/void-packages/commits/trinity).
I haven't tested running a full desktop environment yet, I'll report back if I do get that working & with more details on what I have and haven't gotten to work.

**Comment by kpvsky** [comment]
Maybe I'll try to continue packaging that software to xbps. Also, the newer version of TDE has been released some time ago.

**Comment by ScrelliCopter** [comment]
@kpvsky I'm late, but feel free to use my progress as a base. Iirc I left it because it's a lot of work to get everything else working and probably in a state that the core team would find acceptable, and the only member of the core team who was interested was Juan who is long gone.

**Comment by nipos** [comment]
Is there still interest in getting this to work?
I really want a systemd-free Linux with Trinity on my Raspi 400.
I may be able to look into it and finish the port if there's still interest in getting this merged.
Beware,I'm totally new to Void Linux (coming from Manjaro KDE),but the packaging tools look pretty good so I think I could possibly get it to work.

**Comment by Vistaus** [comment]
TDE is an amazing desktop, in my experience, so it would be great to have it on Void. So I 100% support this request.

**Comment by kasesag** [comment]
Sorry for my late response, but I want to clarify that I don't have any interest anymore in getting this to work since I don't use void anymore on desktop. Maybe there are other people who would like to get the latest TDE running under void linux.

**Comment by thenktor** [comment]
There is a new Trinity release available: https://wiki.trinitydesktop.org/Release_Notes_For_R14.1.0

**Comment by michael-db** [comment]
After happily using void for some time, KDE was upgraded to KDE 6 (it's still called kde5, which is misleading) which broke things and cost me hours. I still can't save my session, regardless of whether I choose X11 or Wayland.

This has been a serial issue with KDE. I recall a previous x.0 release (probably KDE 4.0) which was totally unusable but had been bundled into a distro I tried. When I complained I was chastised by the KDE people for expecting an X.0 release to be stable! KDE upgrades are mostly about pointless visual fluff (disrgarding things that broke, I don't notice any functional improvement that's relevant to me) and never to be trusted. The only thing I can be grateful for is that I didn't hit this [shocking rm -rf / issue](https://linuxiac.com/usage-of-plasma-6-global-themes-may-pose-serious-risks/).

Unfortunately, I have too many other things to take this on now, but I hereby add my vote to those who would love to see Trinity on void.

**Comment by michael-db** [comment]
Unless you think it's worth packaging for your own benefit, I wouldn't go just by my comment, Kacper, especially if you don't think it will be accepted as an official package. No one else has commented on this issue this year and I'm used to being in a minority.

(And I'm not entitled to ask others for things like this: I do have several open source contributions "planned" but they seem to get indefinitely displaced by other priorities.)

**Comment by UncleSlacky** [comment]
Another vote for Trinity to be packaged for Void! I already use it on some machines via Exe GNU/Linux (Devuan+TDE) and Q4OS Trinity (Debian+TDE) and I'd expect TDE to fly on Void. I've even tried to build it myself for Solus but I'm no expert in building stuff on Linux.

**Comment by Elibord** [comment]
TDE is pretty good, and I want to see this in Void. I support this

**Comment by chabotc95** [comment]
Another vote from me.

**Comment by manipuladordedados** [comment]
Will be nice.

**Comment by Duncaen** [comment]
There is no voting, if someone wants to contribute it they can.
