### ISSUE TITLE
Package request: Ark - archiver (update to 18.08)

### ISSUE THREAD

**Issue by MirceaMx** [void-linux/void-packages#1925]
Please update Ark - the Qt / KDE archiver to 18.08 as it contains lots of bug fixes with the new release.

**Comment by Johnnynator** [comment]
There are a lot packages to be updates with every KDE application release. You should give use more time to test and update everything before opening a issue.

**Comment by MirceaMx** [comment]
Thought you updated all. Well.closing the issue.
