### ISSUE TITLE
maxima ships precompiled binary linked against glibc

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#19289]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *maxima-5.43.2_1*

### Expected behavior
`/usr/share/maxima/5.43.2/share/test_encodings/escape-double-quote` should be compiled from source and not being the precompiled glibc one.

### Actual behavior
```
# xbps-install maxima
maxima-5.43.2_1: broken, unresolvable shlib `libc.so.6'
Transaction aborted due to unresolved shlibs.
```
### Steps to reproduce the behavior

@jbgg

Reported on reddit: https://old.reddit.com/r/voidlinux/comments/ewhhoa/musl_sys_upgrade_wants_glibc_by_mistake/

**Comment by Johnnynator** [comment]
Debian just removes the file in question and doesn't ship it at all.

**Comment by jbgg** [comment]
Fixed on https://github.com/void-linux/void-packages/pull/25068
