### ISSUE TITLE
linux5.5 Building DKMS module for nvidia-390.132 fails

### ISSUE THREAD

**Issue by xscd** [void-linux/void-packages#19301]
### System
Void Linux x86_64 (xfce)
* xuname:  
Void 5.4.20_1 x86_64 GenuineIntel uptodate rrFFF
* package:  
linux5.5-5.5.4_1
nvidia390-390.132_5
nvidia390-dkms-390.132_5(?)
### Expected behavior
Building and installing nvidia390 DKMS module fine for linux5.5
### Actual behavior
Building fails. 
![Image of Fail](https://files.catbox.moe/ekzsl9.png)
### Steps to reproduce the behavior
1) Install linux5.5-headers
2) Install linux5.5
3) Building fails for nvidia390

Not sure but possible patch: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/nvidia-390xx&id=6c41272fb5c78271bdea7d19de1463487a600da2

**Comment by Chocimier** [comment]
Linux 5.5 is removed by now, module works for 5.8, 5.9 support is worked on.
