### ISSUE TITLE
"plank" dock projects a persistent shadow  [bug]

### ISSUE THREAD

**Issue by edo0** [void-linux/void-packages#19313]
### System

* xuname:  
  *Void 5.4.20_1 x86_64 GenuineIntel uptodate rrFFF*
* package:  
  *plank 0.11.89*

My setup comprises vanilla LXQt, with the substitution of Openbox with xfwm4. All the rest is pretty much default stack.

### Actual behavior
As you can see in the pictures at the bottom, a shadow is cast, parallel to the dock. The same is seen regardless of the "theme" or "position" settings of the dock, and superpose to any programme window.

### Steps to reproduce the behavior
Installing plank, running plank.

I have no clue as to what could cause this behaviour.
I will be very grateful to anyone who will help me troubleshoot this bug.
Thank you!

![01](https://user-images.githubusercontent.com/16632292/74885248-ff1ebf80-536c-11ea-8dae-0ee6a7056cb3.png)
![02](https://user-images.githubusercontent.com/16632292/74885254-03e37380-536d-11ea-86a7-47ec9f0f65f0.png)
![03](https://user-images.githubusercontent.com/16632292/74885258-05ad3700-536d-11ea-85c6-67c91f44fb59.png)

**Comment by goleo108** [comment]
@edo0 that bug is specific to xfce, you need to disable xfwm's shadows, it's not a distro-specific problem, so instead you need to bug xfce team

**Comment by xtraeme** [comment]
upstream issue
