### ISSUE TITLE
Package Request: Pycharm for musl

### ISSUE THREAD

**Issue by Frick-David** [void-linux/void-packages#19319]
Hey huge fan of Void! This is my repo of choice.

I am using the musl based distro. I noticed the libc version has pycharm community.
Is there any chance musl can get it as well?

**Comment by Johnnynator** [comment]
If someone wants to work on it, try to just compile the binaries, not the full IDE. The fun thing with Jetbrains IDE is, that the build system likes fetching random binaries (called "JBR") linked against GLIBC, and patching that behavior is probably a gigantic pain.

**Comment by asiekierka** [comment]
JBR is just JetBrains's fork of OpenJDK, which the Void-packaged versions of JetBrains's IDEs do not use as far as I know.

**Comment by Frick-David** [comment]
Shame to hear that :(  I was hoping it could be a quick project :(

Side-note:
Is that the same case for steam?

Thanks for the feedback,
David

**Comment by protonesso** [comment]
Use flatpak?

2020年2月20日(木) 23:43 David Frick <notifications@github.com>:

**Comment by Johnnynator** [comment]
> Side-note: Is that the same case for steam? Thanks for the feedback, David

Steam is proprietary, nothing we can do to get it on Musl directly, you can use some kind of chroot, like flatpak.

**Comment by Frick-David** [comment]
Thanks. I will use flatpak!
