### ISSUE TITLE
Network issues with dell e6330

### ISSUE THREAD

**Issue by shnaps** [void-linux/void-packages#19340]
I'm using an old laptop with an even older wifi card.
Here is _lspci -k_ for it
> 02:00.0 Network controller: Broadcom Inc. and subsidiaries BCM4313 802.11bgn Wireless Network Adapter (rev 01)
>Subsystem: Dell Device 0015
>Kernel driver in use: bcma-pci-bridge

Current kernel version 
>5.4.21_1

I have been using brcmsmac as a driver all the time. But it stopped working for last couple linux 5.4.* kernels(my guess). Not sure about the precise date but laptop been working at the end of january(25-31). 
So basically it just stops sending/receiving packets and I'm getting 100% packets lost. Happening every 2 minutes. Restart/driver reload helps temporally only for the next couple minutes. 
Changing drivers from brcmsmac to wl(broadcom-wl-dkms) helps to restore internet and stop packets loss. But in a long term perspective, it is unusable(it doesn't see wifi networks). 
To make this driver work I need to :
>1. rmmod wl
> 2. modprobe brcmsmac
> 3. rmmod brcmsmac
> 4. modprobe wl

After that I'll see all the networks.

**Comment by Anachron** [comment]
Did you report upstream already?

**Comment by shnaps** [comment]
No. Should I?

**Comment by shnaps** [comment]
Send a message to the mailing list. At the same time, is there any way to help me without now? Or should I just wait for upstream devs to respond?

**Comment by ericonr** [comment]
Is this still an issue? Most you can do is keep using an older kernel, which carries its own risks.
