### ISSUE TITLE
python3-pylint: outdated on aarch64

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#19364]
### System

* xuname:  Void 5.5.0_1 aarch64 Unknown uptodate rFF
* package:  python3-pylint-2.4.4_2

### Expected behavior

package version matches xbps-src version

### Actual behavior

noarch package is out of date

### Steps to reproduce the behavior

xbps-query -R python3-pylint on aarch64

**Comment by Chocimier** [comment]
It's because dependency python3-typed-ast does not compile in aarch.

**Comment by sgn** [comment]
python3-typed-ast is able to be cross-compiled, now.

**Comment by Chocimier** [comment]
Resolved, thanks sgn.
