### ISSUE TITLE
jrnl: Source wrong?

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#19438]
Is there a reason why https://github.com/maebert/jrnl is being used for the `jrnl` source?
The original source is here: https://github.com/jrnl-org/jrnl

@travankor

**Comment by travankor** [comment]
>Is there a reason why https://github.com/maebert/jrnl is being used for the jrnl source?

They created a new org for the project and the original author's repo became a fork.

I haven't had the time to maintain the package and would rather pass the maintainership of this package to someone else. @Anachron feel free to update the package and maintain it.

**Comment by Anachron** [comment]
I've written my own `jrnl` in `$SHELL`, someone else gotta step in and update it.

**Comment by Anachron** [comment]
Closing, not interested in this monster of python code for a simple journal.
