### ISSUE TITLE
Electrum cannot be launched via GUI

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#1944]
### System

* xuname:  
Void 4.17.14_2 x86_64 AuthenticAMD notuptodate hold rrrrmmnDDFF
* package:  
Electrum 3.2.2_1

### Expected behavior
Program launches
### Actual behavior
Program does not launch
### Steps to reproduce the behavior
click on the app entry in the menu (in my case - LXQT)
App can be launched via terminal but I receive an error message:
[ecc] warning: libsecp256k1 library not available, falling back to python-ecdsa

**Comment by cr6git** [comment]
https://github.com/spesmilo/electrum/issues/4300
