### ISSUE TITLE
gnutls: unbound

### ISSUE THREAD

**Issue by qfwqqtemp** [void-linux/void-packages#19445]
gnutls since 936c09e depends on unbound dns server.
Is it really needed?

**Comment by Piraty** [comment]
I just thought the same...
@xtraeme what about making that a build_option? (and then, how to handle the entry in common/shlibs ?)

**Comment by xtraeme** [comment]
two ways are possible:

- create `libunbound` subpkg
- create a build option and make `DANE` optional (disabled by default)

**Comment by Piraty** [comment]
of course. but how to handle the conditional entry in common/shlibs? https://github.com/void-linux/void-packages/commit/936c09e4d5c3d2371571cf20a6eb39afac7dd3c9#diff-7fcb25a51d826a40c7a5859f48aac092R239

**Comment by xtraeme** [comment]
@Piraty there's no need to handle the conditional entry. If gnutls is built with DANE the shared library will be used, otherwise it will be ignored.

**Comment by qfwqqtemp** [comment]
Closed by #19572
