### ISSUE TITLE
[HELP] GHC 8.8.2

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/void-packages#19464]
GHC 8.8.2 is part of new Stackage LTS 15.

I currently don't have time to maintain my Haskell packages, so help would be appreciated.

**Comment by q66** [comment]
Since we maintain only one `ghc` in the repo and we strictly use system `ghc`, this would probably involve making sure every haskell package in the repo can build with the updated version...

**Comment by slotThe** [comment]
@leahneukirchen I suppose this can be closed now that #20365 got merged.

**Comment by leahneukirchen** [comment]
Yes, thanks to everyone that helped!
