### ISSUE TITLE
/bin/sh: symbol lookup error: /usr/lib/spotify-adblock.so: undefined symbol: dlerror

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#19494]
### System

* xuname:  
`Void 5.4.15_1 x86_64 GenuineIntel notuptodate hold rrDDDFFF`

### Expected behavior
Working without any issue.(Actually it worked before, about two month ago)

### Actual behavior
It throws an error.

### Steps to reproduce the behavior
1. Install [spotify-adblock-linux](https://github.com/void-linux/void-packages/blob/3a5299491cbd739943d756951ff0757eb667e445/srcpkgs/spotify-adblock-linux/template) package.
2. Run it from terminal: (with LD_PRELOAD)
```
╰ env LD_PRELOAD=/usr/lib/spotify-adblock.so spotify
/bin/sh: symbol lookup error: /usr/lib/spotify-adblock.so: undefined symbol: dlerror
```

**Comment by xtraeme** [comment]
you are the maintainer of this pkg, how come that you don't fix this yourself?

**Comment by LinArcX** [comment]
I don't know how fix it.

**Comment by dmilith** [comment]
Ripgrep /usr/lib, likely you need to add libdl.so to LD_PRELOAD or sth like that

**Comment by NeelChotai** [comment]
Does `$ LD_PRELOAD=/usr/local/lib/spotify-adblock.so spotify` work?

**Comment by LinArcX** [comment]
@dmilith i added /usr/lib to LD_LIBRARY_PATH:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib`
And run the command again. But still get same error.
