### ISSUE TITLE
opensmtpd *silently* switched mbox=>maildir breaking existing setups

### ISSUE THREAD

**Issue by loreb** [void-linux/void-packages#19535]
... at least mine that is :)

Anyway as part of the recent opensmtpd security upgrades smtpd.conf went from mbox to maildir without warning, which breaks at least my usage of having opensmtpd for local mail only (basically cron) that gets read & quickly discarded with mailx while actual mail is handled some other way.

I would have expected a warning if there's any regular file in /var/mail/.

PS
Sorry for not filling in the exact version, I'm not at the appropriate computer at the moment.

**Comment by xtraeme** [comment]
Assigned to maintainer

**Comment by leahneukirchen** [comment]
Changing the default configuration is an upstream maintainer decision, if you change the config back delivery to mbox will work (and your config is preserved of course).
