### ISSUE TITLE
Package Request: soundkonverter

### ISSUE THREAD

**Issue by MirceaMx** [void-linux/void-packages#1961]
That is soundkonverter with a 'k' as it has more features over the regular 'soundconverter'. Thank You.
Tried to package it and it seems to have all dependencies still...I failed :(

**Comment by maxice8** [comment]
Please post your template so people that want to work on it already have a jump-off point

**Comment by MirceaMx** [comment]
Template (test) :+1: 

'' # Template file for 'soundkonverter'
pkgname=soundkonverter
version=3.0.1
revision=1
#wrksrc=
#create_wrksrc=yes
#only_for_archs="i686 x86_64"
build_style=gnu-configure
#configure_args=""
#make_build_args=""
#make_install_args=""
#conf_files=""
#make_dirs="/var/log/dir 0755 root root"
hostmakedepends="autoconf gettext-devel intltool automake libtool pkg-config"
makedepends="cmake pkgconfig cdparanoia-devel unzip update-desktop-files"
depends=""
short_desc="soundKonverter is a front-end to various audio converters"
maintainer=" <>"
license="GPL-3.0-or-later"
homepage="https://github.com/dfaust/soundkonverter"
distfiles="https://launchpad.net/soundkonvertertrunk/${version}/+download/${pkgname}-${version}.tar.xz"
checksum=d8ea8eac14b7f662ead1749e8935ef90e9c7925ddb9f55c4589c2f8925aa0d83
''

**Comment by maxice8** [comment]
triple backticks ```

```
like this
```

**Comment by MirceaMx** [comment]
Done

**Comment by MirceaMx** [comment]
-edit-

**Comment by ReiLucio** [comment]
@MirceaMx ` not '

**Comment by MirceaMx** [comment]
@ReiLucio How about now?
