### ISSUE TITLE
update failing due to "MISSING: poppler>=0.67.0_1" but doesn't tell me why it wants to update

### ISSUE THREAD

**Issue by nonchip** [void-linux/void-packages#1963]
```
$ sudo xbps-install -Su
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/debug/x86_64-repodata' ...
MISSING: poppler>=0.67.0_1
MISSING: poppler>=0.67.0_1
Transaction aborted due to unresolved dependencies.
```
It doesn't even tell me which package tries to depend on or blocks this so i could temporarily version-lock it 0.o

according to `xbps-query -Rs poppler` most of the associated packages, but not the main one (which is still on `0.63.0_2`) have the required version, i wonder if it just never made it through the buildfarm?

**Comment by maxice8** [comment]
poppler is currently being updated please wait

**Comment by maxice8** [comment]
https://build.voidlinux.eu/waterfall can be checked for status on building

**Comment by maxice8** [comment]
x86_64 build of poppler is done

**Comment by maxice8** [comment]
this should be fixed
