### ISSUE TITLE
msbuild-bin breaks after update

### ISSUE THREAD

**Issue by derrickcreamer** [void-linux/void-packages#19641]
### System

* xuname:  
Void 5.4.23_1 x86_64 AuthenticAMD notuptodate rrrmFFFFF

* package:  
msbuild-bin-16.5_1

### Expected behavior
Files installed to /usr/lib/mono.

### Actual behavior
Files installed to /usr/lib/lib/mono causing package to not work correctly.

### Steps to reproduce the behavior
Do a typical package installation using xbps-install. Can also verify file locations with xbps-query -Rf msbuild-bin.

The /usr/lib/lib/mono location is not correct and does not reflect the usual working configuration, nor does it reflect the result of rebuilding this package from source.

Anecdotally, this problem MIGHT only appear on certain void repos. I believe I'm connecting to alpha.de.repo.voidlinux.org while another user reported this issue on US repos.

**Comment by ahesford** [comment]
I can confirm that the existing binary package seems to inappropriately install files in `/usr/lib/lib/mono`. Building the package with `xbps-src` seems to produce expected behavior. Maybe this was a glitch in the buildbot?
