### ISSUE TITLE
Package Request: mdless

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#19829]
> mdless is a utility that provides a formatted and highlighted view of Markdown files in Terminal

Source: https://github.com/ttscoff/mdless
License: [MIT](https://github.com/ttscoff/mdless/blob/develop/LICENSE)
Build-Style: [RakeFile](https://github.com/ttscoff/mdless/blob/develop/Rakefile)

**Comment by classabbyamp** [comment]
would `mdcat` work for you?

**Comment by Anachron** [comment]
Yep, closing.
