### ISSUE TITLE
clang-9  unknown argument -fstack-clash-protection on xbps-src  chroot

### ISSUE THREAD

**Issue by dinama** [void-linux/void-packages#19839]
Can't prepare package which using clang for build because shell `common/environment/configure/hardening.sh` set ` "-fstack-clash-protection -D_FORTIFY_SOURCE=2"`  as  default CFLAGS. 

And  compilation broken:

```
FAILED: CMakeFiles/cmTC_a2b73.dir/testCCompiler.c.o     
/usr/lib/ccache/bin/clang   -fstack-clash-protection -D_FORTIFY_SOURCE=2 \
  -mtune=generic -O2 -pipe -o CMakeFiles/cmTC_a2b73.dir/testCCompiler.c.o \
    -c testCCompiler.c

    clang-9: error: unknown argument: '-fstack-clash-protection'
```

This workaround on <package>/template locally resolve this problem:

```
export CFLAGS=$(sed 's/-fstack-clash-protection//g' <<<$CFLAGS) 
export CXXFLAGS=$(sed 's/-fstack-clash-protection//g' <<<$CXXFLAGS)

```

**Comment by Duncaen** [comment]
Something like the following in the template should be fine:
```
export CFLAGS="${CFLAGS/-fstack-clash-protection/}"
```

**Comment by dinama** [comment]
> Something like the following in the template should be fine:
> 
> ```
> export CFLAGS="${CFLAGS/-fstack-clash-protection/}"
> ```

yes, now i, using `export CFLAGS=$(sed 's/-fstack-clash-protection//g' <<<$CFLAGS) `
if it workaround is legal for package - then issue notabug 
ps. option `-fstack-clash-protection` became in clang11

**Comment by Duncaen** [comment]
There are a few packages that do something like this, if this is the only way to build it then sure.
But use bash substitutions instead of forking sed.

**Comment by xtraeme** [comment]
Hmm not sure if it should be closed. I think I can improve this one.
