### ISSUE TITLE
ziglang - zig - Update possible?

### ISSUE THREAD

**Issue by schmidh** [void-linux/void-packages#19849]
There is a serious bug in version 0.5.0 which makes zig mostly unusable:

[Parse error when anonymous literal is the first element in an array](https://github.com/ziglang/zig/issues/3679)

Would it be possible to update the zig package with the bug fixed?

**Comment by xtraeme** [comment]
do they have a released version?

**Comment by schmidh** [comment]
No, that's the problem. (I know the release policy of Void Linux.)

**Comment by xtraeme** [comment]
well, if they've got a patch we can merge it

**Comment by schmidh** [comment]
No, not really. No patch. I think we just have to wait for the next release. In the meantime I do a manual installation. Thanks for your quick reply!

**Comment by xtraeme** [comment]
I can't do much otherwise, let's wait for the next release.

Thanks for the heads up :-)
