### ISSUE TITLE
kdeconnect: update to 1.4-2

### ISSUE THREAD

**Issue by GitHubPiotr** [void-linux/void-packages#19840]

**Comment by Hoshpak** [comment]
we don't accept update requests. Feel free to create a PR to update the package.

**Comment by jkoderu-git** [comment]
> we don't accept update requests. Feel free to create a PR to update the package.

Then how can I flag a package as out of date as happens on arch?

I don't have the knowledge to fix the build or packaging errors on a new version of the package but I would like to bring the availability of a new version to attention so someone can work on it. For example I am waiting for an update for Blender and its dependencies and I don't know if anyone is interested, #22561 got closed recently.

I read @Hoshpak comment now so I am sorry for opening #22774.
