### ISSUE TITLE
Gnumeric Tool Bar Icons

### ISSUE THREAD

**Issue by leetnc** [void-linux/void-packages#20011]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*

* package:  gnumeric-1.12.46_1,  adwaita-icon-theme-3.34.3_1

### Steps to reproduce the behavior - xbps-install gnumeric,   execute gnumeric,  observe icons

xbps-install adwaita-icon-theme      resolved the problem.
Maybe adwaita-icon-theme needs to be an install dependency for gnumeric ?

This is my first visit to GitHub, so hope I did not mug the process too badly.

**Comment by ericonr** [comment]
gtk+3 now depends on adwaita-icon-theme by default :)
