### ISSUE TITLE
Package request: XMIND

### ISSUE THREAD

**Issue by 0xatul** [void-linux/void-packages#20089]
Please add xmind to void repos. 
link: https://github.com/xmindltd/xmind

**Comment by Anachron** [comment]
Can't be distributed unless XMIND specifically grants permission:

https://www.xmind.net/terms/

> You agree not to distribute in any medium any part of the Site without XMind’s prior written authorization.

**Comment by Eloitor** [comment]
https://github.com/xmindltd/xmind is no longer available...
