### ISSUE TITLE
Racket 7.6 & Racket 7.6 CS

### ISSUE THREAD

**Issue by mkohlhaas** [void-linux/void-packages#20087]
@thypon 

Racket 7.6 is out and Racket CS (Chez Scheme) is now production ready. Do you think we could have both available as Void Linux packages?

Kind regards,
Michael

**Comment by codingHahn** [comment]
I updated the package the last time. Do you want to try it yourself?

Could you link to Racket CS? I have never heard of it.

**Comment by mkohlhaas** [comment]
Hi Nick, thanks for your feedback. I'll try on this weekend if I can find time.

**Comment by codingHahn** [comment]
If you have any questions, just ask them here. I am happy to help. :)

**Comment by mkohlhaas** [comment]
Thanks!

**Comment by mkohlhaas** [comment]
Somebody beat me to the punch! :-)
