### ISSUE TITLE
Steam package requires multilibs glibc-32bit, mesa-32bit, and mesa-dri-32bit to run.

### ISSUE THREAD

**Issue by seisatsu** [void-linux/void-packages#20102]
### System

* xuname:  
  *Void 5.4.25_1 x86_64 AuthenticAMD notuptodate rrrrmdFFFFF*
* package:  
  *steam-1.0.0.61_7*

### Expected behavior
The `steam` executable should start after installing.

### Actual behavior
* When starting without glibc-32bit installed from multilibs, steam produces an error popup saying that the 32bit libc libraries are required to start.
* When starting without mesa-32bit or mesa-dri-32bit, a popup error warns that "glXChooseVisual failed".
* When starting with mesa-32bit but not mesa-dri-32bit, steam segfaults.

### Steps to reproduce the behavior
Install the steam package without installing the required multilibs packages, then attempt to run.

### Suggested solution
Move steam to the multilibs repository and require the necessary multilibs packages.

**Comment by codingHahn** [comment]
You are right. Steam should function right after installation. But to my knowledge, the multilib repo gets populated automatically. i do not know how hard or feasible it is to change this process just for steam. There already is an install massage that tells you what you have to do.

**Comment by Supersonic112** [comment]
Small addition: just switched to Voidlinux yesterday, I also had to install `libglvnd-32bit` before Steam would run beyond something that looked like the following (admittedly rather old) issue: https://github.com/ValveSoftware/steam-for-linux/issues/3951

**Comment by codingHahn** [comment]
@xtraeme Is it possible to 'require' a package from a multilib repo?

**Comment by ericonr** [comment]
Creating dependencies on the `-32bit` packages seems to just work, one big issue is that it creates a dependency on the current multilib system, which we'd like to change (see #27337 ).

**Comment by ericonr** [comment]
Since we want to move in that direction and we currently provide an INSTALL.msg, I will be closing this.

**Comment by Vistaus** [comment]
I don't understand why this issue is closed as it's still relevant. I installed Void yesterday, so it's a 100% clean install, yet this issue still arose.

**Comment by Duncaen** [comment]
Because it required dependencies from a repository that is not enabled by default and also introduces build dependencies on x86_64 builds that require a i686 chroot.
Steam requires manual setup, nothing is going to change that because it would require hacks/workarounds that no other package would require.
