### ISSUE TITLE
ppp: silently breaks on musl

### ISSUE THREAD

**Issue by lemmi** [void-linux/void-packages#20150]
`ppp` silently breaks on musl:

https://gist.github.com/lemmi/56bf7a72a13e6a232bbd98ffaf200f2f#file-gistfile1-txt-L63-L98

quick fix: 
`sed -i "/^#define HAVE_SYS_CDEFS_H 1/d" pppd/plugins/rp-pppoe/config.h`
With this cdefs.h won't be included and it compiles fine.
I have no idea, why this doesn't interrupt the build process.

What's the proper solution here?

**Comment by sgn** [comment]
Our project provides `sys/cdefs.h` for musl by `musl-legacy-compat`.

Proper solution is patching it and report to upstream. Meanwhile,
```
makedepend+="musl-legacy-compt"
```
