### ISSUE TITLE
libksysguard: KSysGuard library was compiled without QtWebEngineWidgets

### ISSUE THREAD

**Issue by toluschr** [void-linux/void-packages#20180]
It says `please contact your distribution`, so I did. I'm also willing to fix this myself by submitting a PR.

### System

* xuname:  `Void 5.4.25_1 x86_64 AuthenticAMD notuptodate rrrrmmnFFFFFFFFFFFF`
* package:  `libksysguard`

### Expected behavior
Clicking 'Detailed Memory Information' opens a window with additional memory information.

### Actual behavior
The `Detailed Memory Information` option in `ksysguard` doesn't work.
![Issue](https://user-images.githubusercontent.com/44272603/76943967-80cc2380-6900-11ea-84e5-c8140288a572.png)

### Steps to reproduce the behavior
Install `ksysguard`, right click any process and select `Detailed Memory Information`

**Comment by Johnnynator** [comment]
Feel free to submit a PR, but make sure that you add webengine as a buildoption and only enable it on systems that have it (disable for Bigendian and 32bit cross compiled arch's)

**Comment by Johnnynator** [comment]
Resolved in 1e711a1e0bcd22a3100e8d2ff7188a7ca71b5f4d
