### ISSUE TITLE
xrdb - can't open include file

### ISSUE THREAD

**Issue by iio7** [void-linux/void-packages#20207]
### System

* xuname:  Linux Void 5.4.26_1
* package:  xorg-7.6_5

### Expected behavior

Be able to include files in .Xresources.

### Actual behavior

Can't open include files

### Steps to reproduce the behavior

Create a basic `.Xresources` and an include file.

```
$ cat .Xresources
XTerm*termName: xterm-256color
XTerm*utf8: 1
XTerm*renderFont: true
XTerm*faceName: "Liberation Mono":size=9:antialias=true:autohint=true
XTerm*borderWidth: 0
XTerm*autohint: true
XTerm*locale: true
XTerm*metaSendsEscape: true
XTerm*backarrowKey: false
XTerm*bellIsUrgent: false
XTerm*cursorBlink: false
XTerm*vt100.saveLines: 10000
XTerm*selectToClipboard: true
XTerm*ScrollKey: true
#include "colortheme.Xresource"
```

The include file:

```
$ cat colortheme.Xresource
#define base00 #282828
#define base01 #3c3836
#define base02 #504945
#define base03 #665c54
#define base04 #bdae93
#define base05 #d5c4a1
#define base06 #ebdbb2
#define base07 #fbf1c7
#define base08 #fb4934
#define base09 #fe8019
#define base0A #fabd2f
#define base0B #b8bb26
#define base0C #8ec07c
#define base0D #83a598
#define base0E #d3869b
#define base0F #d65d0e
*.foreground:   base05
#ifdef background_opacity
*.background:   [background_opacity]base00
#else
*.background:   base00
#endif
*.cursorColor:  base05
*.color0:       base00
*.color1:       base08
*.color2:       base0B
*.color3:       base0A
*.color4:       base0D
*.color5:       base0E
*.color6:       base0C
*.color7:       base05
*.color8:       base03
*.color9:       base08
*.color10:      base0B
*.color11:      base0A
*.color12:      base0D
*.color13:      base0E
*.color14:      base0C
*.color15:      base07
*.color16:      base09
*.color17:      base0F
*.color18:      base01
*.color19:      base02
*.color20:      base04
*.color21:      base06
```

Then load Xresources:

```
$ xrdb .Xresources
.Xresouces:15: error: Can't open include file "colortheme.Xresource"
```

I have the identical setup running on multiple Linux distributions and on FreeBSD where it works so I suspect a bug somewhere.

**Comment by iio7** [comment]
I just figured out that it requires the full path `/home/foo/` to work here. On Arch, Ubuntu and FreeBSD I can do it without as includes starts from the home folder.

**Comment by iio7** [comment]
It is also demonstrated here without a full path: https://wiki.gentoo.org/wiki/X_resources

**Comment by iio7** [comment]
Actually I believe this is a bug, it's supposed to read from the home path.

**Comment by pullmoll** [comment]
/methinks this is a bug or flaw in how the package `mcpp` parses the `.Xresources` file. In case other distributions use e.g. the regular GNU cpp as preprocessor this may explain why it works without prepending the full path, because (most probably) `/usr/bin/cpp` looks for include files in the current directory. **This is just a wild guess, though.**

We could perhaps circumvent this problem if we passed `-I$HOME` to the call to `/usr/bin/mcpp` somehow, I just don't know how to achieve that.

**Comment by pullmoll** [comment]
Just read your most recent post and can confirm it by looking at the source. Various command line arguments for `xrdb` are forwarded to the C preprocessor and specifically `-I` is passed along.

**Comment by iio7** [comment]
Yes, `-I` solves the problem. I think I'm just gonna close this one as it works well.
