### ISSUE TITLE
xaos: Segmentation fault

### ISSUE THREAD

**Issue by kmltdr** [void-linux/void-packages#20222]
### System

* xuname:  
`Void 5.4.26_1 x86_64 GenuineIntel uptodate rrFFFF`
* package:  
`xaos-3.6_6`

### Expected behavior
It works
### Actual behavior
```
$ xaos
Segmentation fault
```
Also window flashes for a split second.
### Steps to reproduce the behavior
Install and run xaos

**Comment by yopito** [comment]
works fine here with musl (`Void 5.4.26_1 x86_64-musl GenuineIntel uptodate rrnFF`).

Could you provides more details by running with `strace` or `gdb`  ?

**Comment by kmltdr** [comment]
Sure https://gist.github.com/kmltdr/5863320ae5821e1c138aec4058063472

**Comment by yopito** [comment]
Thanks for strace output but not enough.   
Can you provide the same with `gdb` this way:
```
$ gdb /bin/xaos
[...]
(gdb) run
[...]
(gdb) bt
```

**Comment by kmltdr** [comment]
https://gist.github.com/kmltdr/aa38389a5a7fd2172f83cdecc202a4d9

**Comment by yopito** [comment]
I'm sorry, I'm probably not clever enough to diagnose.  
Just one point: does you cpu provides sse/sse2 ? could you output `/proc/cpuinfo` (only one processor).  
help rescue: ping @pullmoll and @leahneukirchen

**Comment by xtraeme** [comment]
He should install dbg pkgs to make the gdb stack trace useful

**Comment by yopito** [comment]
update: on IRC, sebu confirms same this issue on glibc.  
He/her also rebuilt package with gcc 9.3: same issue.  
work fine for him with xaos 3.7, he/her will provides a PR with this package' update.
stay tune.

**Comment by leahneukirchen** [comment]
4fba79baf2

**Comment by sebu06** [comment]
can confirm 3.7 solbes the issue

**Comment by xtraeme** [comment]
cool, thanks @leahneukirchen
