### ISSUE TITLE
[BUG] Package 'hplip-gui': printer funktion

### ISSUE THREAD

**Issue by sass432** [void-linux/void-packages#20233]
my used printer: HP-Deskjet F4580

installed: 'hplip-gui' with all needed dependences

added User-Group: wheel, lp, storage

enabled deamons: dbus, cupsd, cups-browsed

toolbox-printer-identification positive

issue: job queue control: Printer permanent stopped or paused	

report '$ hp-check -t':
·	warning: void distro is not found in AUTH_TYPES
·	missed dependences, not found or not installed

scan-funktion is still working, but only with the trick:
# touch /usr/share/cups/model && nano /usr/share/cups/model
→	prop.ppd_search_path = '/usr/share;/usr/local/share;/usr/lib;/usr/local/lib;/usr/libexec;/opt;/usr/lib64'﻿
# chmod 0755 /usr/share/cups/model

**Comment by biopsin** [comment]
Is this still a issue with 3.21.10 ? - looking inside the template the `/usr/share/cups/model` is a directory..

**Comment by biopsin** [comment]
@sass432 ..anyways I welcome you to review PR[#37287](https://github.com/void-linux/void-packages/pull/37287)
