### ISSUE TITLE
libglvnd-devel fails to install when nvidia340 is installed

### ISSUE THREAD

**Issue by BouncyMaster** [void-linux/void-packages#20252]
### System

* xuname:  
  ``Void 5.4.26_1 x86_64 AuthenticAMD uptodate rrrmFFF``

### Expected behavior
glfw-devel should install successfully.
### Actual behavior
``glfw-devel-3.3.2_1`` doesn't install, instead i get:

``nvidia340-340.108_3: broken, unresolvable shlib `libnvidia-ml.so.1'``
``Transaction aborted due to unresolved shlibs.``
### Steps to reproduce the behavior
I use the proprietary drivers ``nvidia340``, ``glfw`` seems to install.

### Edit:
Made a clean Live USB install and installed ``nvidia340`` then tried ``glfw-devel``, same error.

**Comment by st3r4g** [comment]
Can reproduce, `glfw-devel` is pulling `libglvnd-devel` which for some reason is trying to replace `nvidia340-libs` with `libglvnd`. Instead, you should be able to have `libglvnd-devel` and `nvidia340-libs` installed.
Trying to install `nvidia340` and `libglvnd-devel` in the same transaction seems to succeed... I did this:
```
xbps-remove nvidia340
xbps-install libglvnd
xbps-install nvidia340 libglvnd-devel
```
Now you should be able to install things that depend on `libglvnd-devel`, such as `glfw-devel`. I suspect this is a bug in the virtualpkg mechanism...

**Comment by xtraeme** [comment]
hmm

please paste output of `xbps-install -nd glfw-devel`

**Comment by BouncyMaster** [comment]
Output of ``xbps-install -nd glfw-devel``
[debug.txt](https://github.com/void-linux/void-packages/files/4363107/debug.txt)

**Comment by st3r4g** [comment]
I think this happens because there's no match here:
```
if (foundvpkg && xbps_match_virtual_pkg_in_dict(curpkgd, reqpkg)) {
        /*
        * Check if required dependency is a virtual package and is satisfied
        * by an installed package.
        */
        xbps_dbg_printf_append(xhp, "[virtual] satisfied by `%s'.\n", pkgver_q);
        continue;
}
```
`nvidia340-libs` has `provides=libglvnd-1.3.0_1`, which won't get matched by the `depends="${sourcepkg}-${version}_${revision}"` in `libglvnd-devel` , because the current version is not `1.3.0_1`. Still unsure how to solve...

**Comment by st3r4g** [comment]
The situation before the switch to libglvnd was:
```
MesaLib-devel_package() {
	depends="... libGL>=${version}_${revision} ..."

nvidia340-libs_package() {
	provides="libGL-${version}_${revision}"
```
which worked just because nvidia versions are higher than mesa versions... It makes zero sense to compare them, maybe this hack was introduced as a workaround for this issue...

**Comment by st3r4g** [comment]
Until this is fixed properly, create as root the file `/etc/xbps.d/ignore.conf` with contents:
```
ignorepkg=libglvnd
```
This should prevent `libglvnd` to try to replace `nvidia340-libs`

**Comment by ericonr** [comment]
No longer relevant, nvidia340 has been removed.
