### ISSUE TITLE
OpenVPN does not install scripts to /etc/openvpn

### ISSUE THREAD

**Issue by AbsolutelyLudicrous** [void-linux/void-packages#20262]
### System

* xuname:  
  *xuname: `Void 5.4.15abigail3 x86_64 AuthenticAMD uptodate rFF`, uname -a: `Linux hiigara 5.4.15abigail3 #8 SMP PREEMPT Mon Feb 3 20:49:38 EST 2020 x86_64 GNU/Linux`*
* package:  
  *openvpn 2.4.8, possibly NetworkManager-openvpn 1.8.0?*

### Expected behavior

NetworkManager imports and starts the .ovpn file like it should.

Running `sudo openvpn whatever.ovpn` manually establishes a VPN connection

### Actual behavior

```
bash-5.0$ sudo openvpn file.ovpn 
Password: 
Options error: --up script fails with '/etc/openvpn/update-resolv-conf': No such file or directory (errno=2)
Options error: Please correct this error.
Use --help for more information.
```
After some more investigation, it looks like the openvpn-2.4.8 package doesn't provide anything in /etc at all.

```
bash-5.0$ tar tf /var/cache/xbps/openvpn-2.4.8_1.x86_64.xbps
./props.plist
./files.plist
./usr/share/man/man8/openvpn.8
./usr/share/examples/openvpn/xinetd-server-config
./usr/share/examples/openvpn/xinetd-client-config
./usr/share/examples/openvpn/tls-office.conf
./usr/share/examples/openvpn/tls-home.conf
./usr/share/examples/openvpn/static-office.conf
./usr/share/examples/openvpn/static-home.conf
./usr/share/examples/openvpn/server.conf
./usr/share/examples/openvpn/openvpn-startup.sh
./usr/share/examples/openvpn/openvpn-shutdown.sh
./usr/share/examples/openvpn/office.up
./usr/share/examples/openvpn/loopback-server
./usr/share/examples/openvpn/loopback-client
./usr/share/examples/openvpn/home.up
./usr/share/examples/openvpn/firewall.sh
./usr/share/examples/openvpn/client.conf
./usr/share/examples/openvpn/README
./usr/share/doc/openvpn/management-notes.txt
./usr/share/doc/openvpn/README.mbedtls
./usr/share/doc/openvpn/README.down-root
./usr/share/doc/openvpn/README.auth-pam
./usr/share/doc/openvpn/README.IPv6
./usr/share/doc/openvpn/README
./usr/share/doc/openvpn/Changes.rst
./usr/share/doc/openvpn/COPYRIGHT.GPL
./usr/share/doc/openvpn/COPYING
./usr/lib/openvpn/plugins/openvpn-plugin-down-root.so
./usr/lib/openvpn/plugins/openvpn-plugin-auth-pam.so
./usr/bin/openvpn
```

### Steps to reproduce the behavior

Install the latest openvpn package onto a fresh system.

**Comment by travankor** [comment]
From what I understand, this in intended behavior. Void's OPVN does not want to provide external scripts.

**Comment by benn13** [comment]
Sorry but i have installed openvpn and I cannot start openvpn service,it is just not there it seems.
and there`s no /etc/openvpn.
how do I enable its service and use it?
I am coming from tumbleweed and it just worked there.thank you.

**Comment by l40m** [comment]
That is an intended behavior. You need to create the folder, download a script inside and rename it with the requested filename, which is ``update-resolv-conf``. Follow this guide: https://protonvpn.com/support/linux-vpn-setup/

Quoting:
> Please ensure that the resolv-conf script is properly downloaded on your device by using the following commands:

>``sudo wget "https://raw.githubusercontent.com/ProtonVPN/scripts/master/update-resolv-conf.sh" -O "/etc/openvpn/update-resolv-conf"``

>``sudo chmod +x "/etc/openvpn/update-resolv-conf""``

**Comment by dm17** [comment]
I'm not sure why this should be expected or default behavior... Was just looking around myself for a while to fix this. It feels wrong when the ```/etc/openvpn``` doesn't even exist. Perhaps not an issue with sane default on Void but rather openvpn.

**Comment by ericonr** [comment]
We can add a `make_dirs` line to the openvpn template for `/etc/openvpn`, as a start.

**Comment by subnut** [comment]
For anybody who stumbles upon this issue, the link given above by @l40m has now been changed to https://protonvpn.com/support/linux-openvpn
