### ISSUE TITLE
NetworkManager: wrong meson exe_wrapper for mips*hf

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#20281]
I don't know how this can happen as we have not set this value anywhere, but this is what happens when trying to build `NetworkManager` for `mips*`:
```
[682/692] Generating nm-property-docs.xml with a custom command.
FAILED: libnm/nm-property-docs.xml 
env -i GI_TYPELIB_PATH=/builddir/NetworkManager-1.22.6/build/libnm LD_LIBRARY_PATH=/builddir/NetworkManager-1.22.6/build/libnm sh -c '/usr/bin/qemu-mipselhf-static -L /usr/mipsel-linux-muslhf /usr/mipsel-linux-muslhf/bin/python3' /builddir/NetworkManager-1.22.6/libnm/generate-setting-docs.py --lib-path /builddir/NetworkManager-1.22.6/build/libnm --gir libnm/NM-1.0.gir --output libnm/nm-property-docs.xml
/builddir/NetworkManager-1.22.6/libnm/generate-setting-docs.py: /usr/bin/qemu-mipselhf-static: No such file or directory
```

See it tries to use a `qemu-mipselhf-static` which does not exist. The correct arch to use here is `qemu-mipsel-static` and it is what can be found in `common/cross-profiles/mipselhf.sh`:
```
XBPS_TARGET_QEMU_MACHINE="mipsel"
```
I even tried to explicitly set `-Dexe_wrapper=qemu-${XBPS_TARGET_QEMU_MACHINE}-static` in `NetworkManager`'s `configure_args` yet it insists to use the wrong name.

I really wonder where this wrapper name is constructed, it seems from the cross triplet by stripping `-linux-musl`,  and why`this happens.

**Comment by sgn** [comment]
Have you tried added `build_helper=qemu` to the template,
that helper will set exe_wrapper into the xbps_meson.cross

**Comment by sgn** [comment]
It comes from fix-cross-gir.patch
