### ISSUE TITLE
Remove wireshark-gtk from the repos

### ISSUE THREAD

**Issue by leonardlorenz** [void-linux/void-packages#20308]
`xbps-install -S wireshark-gtk` returns this
```
The wireshark GTK interface is no longer provided by Void Linux,
and it will be fully removed from the repos on 2019-06-09.
```

**Comment by keshto** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/wireshark/template#L67 I believe that this is the case already?

**Comment by leonardlorenz** [comment]
I see. Though I thought removing a package means literally removing it from the official repositories. When I `xbps-query -Rs wireshark-gtk` it still shows up.

**Comment by ericonr** [comment]
It is still being built. Someone probably forgot to remove the package. I made a PR for it.
