### ISSUE TITLE
Package Request: Paperless

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#20306]
https://github.com/the-paperless-project/paperless

> Scan, index, and archive all of your paper documents 

Source: https://github.com/the-paperless-project/paperless
License: [GPL-3.0](https://github.com/the-paperless-project/paperless/blob/master/LICENSE)

**Comment by classabbyamp** [comment]
project is now archived, with this fork recommended instead: https://github.com/jonaswinkler/paperless-ng

**Comment by Anachron** [comment]
Closing, see https://github.com/void-linux/void-packages/issues/41124
