### ISSUE TITLE
Package Request: spek

### ISSUE THREAD

**Issue by kartikynwa** [void-linux/void-packages#20314]
Spek is an acoustic spectrum analyser written in C and C++. It uses FFmpeg libraries for audio decoding and wxWidgets for the GUI.

- Project page: http://spek.cc
- Github page: https://github.com/alexkay/spek

I tried writing a template from scratch but it doesn't compile since I am unfamiliar with how build systems work and I suck. I was able to build the program locally. [Link to my broken template.](https://github.com/kartikynwa/void-packages/blob/spek/srcpkgs/spek/template)

**Comment by not-chicken** [comment]
It doesn't build because it needs patches to build with latest ffmpeg.
This fork is better suited for inclusion imo : https://github.com/withmorten/spek-alternative

```
# Template file for 'spek-alternative'
pkgname=spek-alternative
version=0.8.2.3
revision=1
build_style=gnu-configure
hostmakedepends="pkg-config automake intltool libtool"
makedepends="ffmpeg-devel gettext-devel wxWidgets-devel"
depends="ffmpeg"
short_desc="Acoustic spectrum analyser"
maintainer="Kartik Singh <kartik.ynwa@gmail.com>"
license="GPL-3.0-or-later"
homepage="https://github.com/withmorten/spek-alternative"
distfiles="https://github.com/withmorten/spek-alternative/archive/${version}.tar.gz"
checksum="007ba4b84a310b078e378aa84c8e80783db5821437a757a488c3ecec377e6b2a"

pre_configure() {
	./autogen.sh
}
```

Built and run on x86_64

**Comment by kartikynwa** [comment]
Thank you very much for this @not-chicken
