### ISSUE TITLE
libpoppler89 version mismatch? (90)

### ISSUE THREAD

**Issue by svenper** [void-linux/void-packages#20342]
### System

* xuname:  
  `Void 5.4.25_1 x86_64-musl GenuineIntel uptodate hold rrnFFFFFFFFFF`
* package:  
  `libpoppler89-0.80.0_1`

### Expected behavior

libpoppler89 has version 89 library, libpoppler90 has 90, etc.

```text
$ xbps-query -Rf libpoppler89
/usr/lib/libpoppler.so.89.0.0
/usr/lib/libpoppler.so.89 -> /usr/lib/libpoppler.so.89.0.0
```

### Actual behavior

libpoppler89 has library version 90

```text
$ xbps-query -Rf libpoppler89
/usr/lib/libpoppler.so.90.0.0
/usr/lib/libpoppler.so.90 -> /usr/lib/libpoppler.so.90.0.0
```

### Steps to reproduce the behavior

```text
$ xbps-query -Rf libpoppler89
```

**Comment by xtraeme** [comment]
I guess someone updated it accidentally... heh

**Comment by ericonr** [comment]
No longer an issue, and upstream can organize their shlibs mostly as they wish.

Thansk for bringing it up and the initial work on the poppler update :)
