### ISSUE TITLE
Purge libllvm3.9 from repos

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#20357]
We no longer have a template for `libllvm3.9` so we need to purge this package to get rid of staging. Also `icecat` should be purged as it can not be built with current `rust` and is quite outdated anyway.

**Comment by Chocimier** [comment]
I guess this is the issue @the-maldridge refers to as "shlibs problems" in defend of emptying packages over dropping template. If so, [automatically unindexing](https://github.com/void-linux/xbps-bulk/pull/2) packages with dropped template solves this issue as well.

**Comment by the-maldridge** [comment]
This is one of a handful of issues, but is the most pressing one.  It is 1AM here so I don't trust myself to run commands against the builders as root and not screw something up, but I'll handle it in the morning if no-one has gotten to it by then.  

I'm not 100% sure the linked PR is safe in all cases, so I'd like to review further before adopting it as the solution for the future.  I do however think that intent based packaging is probably the way to go.  Ideally it would check intent in both directions and handle missing packages as well.

**Comment by Duncaen** [comment]
Removed both.

**Comment by pullmoll** [comment]
Merci.
