### ISSUE TITLE
fwupd: rebuild package

### ISSUE THREAD

**Issue by kernle32dll** [void-linux/void-packages#20363]
Request to rebuild `fwupd`.

The updated libgusb 0.3.4 (0f961602b93d8ea8a930cc60362eeb8e5a344f57) is binary incompatible with 0.3.3, and causes https://github.com/fwupd/fwupd/issues/1805. Rebuilding `fwupd` with libgusb 0.3.4 should fix it.

Edit: More context: https://github.com/hughsie/libgusb/commit/377917fed85476d615f72279d0c97bc391d0f191

**Comment by ericonr** [comment]
You can make a PR changing the revision of the template, that should force a rebuild. It would also allow you to test the change locally before commiting. Otherwise I can do it later (should be pretty simple, too).
