### ISSUE TITLE
xbps-src: does not recognize a git-worktree as a git-repo

### ISSUE THREAD

**Issue by Piraty** [void-linux/void-packages#20393]
### Expected behavior
xbps-src doesn't care if run from the main repo or a worktree
### Actual behavior
xbps-src complains about not being run from a git repository a lot during builds.
```
fatal: not a git repository: <...>
```

I'm not 100% sure it leads to fatal build errors, but I remember to see build failures happen in worktrees which didn't occur when building in the main repo (I have yet to find a case to prove this); this might have been related to incorrect SOURCE_DATE_EPOCH derivation or similar...

### Steps to reproduce the behavior
```
cd void-packages

branch=random-branch
main_repo="$(pwd)"

git branch $branch ; git worktree add /tmp/VOID-$branch $branch
cd /tmp/VOID-$branch $branch

# bootstrap using main hostdir (to not fetch binary-bootstrap again)
XBPS_HOSTDIR="$main_repo/hostdir" ./xbps-src binary-bootstrap
./xbps-src pkg which
```

**Comment by sgn** [comment]
Worktree create by `git-worktree(1)` will use a file named `.git`, contains:

    gitdir: $XBPS_DISTDIR/.git/worktrees/<worktree-name>

In chroot, we couldn't navigate to that path, hence the errors.

We could fix this by mounting outer `$XBPS_DISTDIR` to inner

**Comment by Piraty** [comment]
is the chroot really required to know if there's a git directory? @xtraeme ?

**Comment by sgn** [comment]
On 2020-04-09 01:13:10-0700, Piraty <notifications@github.com> wrote:
> is the chroot really required to know if there's a git directory? @xtraeme ?

There're 2 information xbps-src needs to get from git:

- `SOURCE_DATE_EPOCH` (`common/environment/setup/git.sh`),
  this can be work-around by calculate it from outside,
  then export into chroot
- `gitrev` metadata for the package
  (`common/hooks/post-install/05-generate-gitrevs.sh`),
  this will be run in `pkg` step,
  we can work-around by calculate it from outside of chroot, export
  into chroot.

After done all this steps, we no longer need git inside chroot,
thus, `chroot-git` packages is no longer required, and, can be removed
from base-chroot.

-- 
Danh

**Comment by sgn** [comment]
Partial fixed. The repo in git-worktree doesn't install into sub-repo, though.
I tend to think it's a feature, though.
