### ISSUE TITLE
Clipit (clipboard manager) is broken. Please update the package to 1.4.5

### ISSUE THREAD

**Issue by AngryPhantom** [void-linux/void-packages#20402]
Please, could someone fix **clipit** clipboard manager? Sorry, I don't know who's the maintainer so please tag him if you know.

### Steps to reproduce the behavior
1. Install Void MATE
2. Install Clipit
3. Add it to your autostart session (System -> Preferences -> Personal -> Startup Applications)

### Expected behavior
Clipit should start within the session

### Actual behavior
It doesn't work. What's more interesting, it doesn't start even via Alt+F2 (Run Application).
There will be no errors in .xsession-errors. I even edited /etc/xdg/autostart/clipit-startup.desktop adding MATE to «OnlyShowIn» string. Nothing.

But... it starts from the console without any error/issue!

And here is the commit which is (ta-dah!) in the [git repo](https://github.com/CristianHenzel/ClipIt/pull/90/commits/45e46d03b3ff315b5b380004d85fb499b4c139db) since 2018!

In the main.c:

`if (!isatty(fileno(stdin)))`

returns -1

In order to fix that we should remove pipe check or `return -1`.

The thing is that the maintainer here takes the **archive** ([v1.4.4.tar.gz](https://github.com/CristianHenzel/ClipIt/archive/v1.4.4.tar.gz)) **which doesn't contain the above mentioned commit**. He should simply clone the git I guess.

Thank you in advance! Stay safe, cheers.

**Comment by flexibeast** [comment]
Void does not accept non-release versions (e.g. based on the state of a repository at a random commit) into the Void package repos, so the package cannot currently be updated. Try asking the ClipIt maintainer to tag a new release.

**Comment by ericonr** [comment]
@AngryPhantom given that this means Clipit is broken in a certain situation, and that upstream has a fix for it, if you can make a patch for the current version that fixes the issue, you can probably make a pull request which will be accepted. Void accepts patches from unreleased versions if it makes sense to do so, which I think thise case qualifies.

**Comment by AngryPhantom** [comment]
@ericonr I'm really sorry, I was born very very far from maths, programming, etc. It was hinted by the people from our Russian Linux forum. I've just pointed this out here. I was wondering who is the maintainer of Clipit and/or who can tag him in order to see this issue. Anyway, thank you for your feedback.

**Comment by ericonr** [comment]
@Gottox could you take a look at this, please?

**Comment by Gottox** [comment]
Looking into it.

**Comment by AngryPhantom** [comment]
ClipIt got updated/tagged yesterday. Waiting for the package! :)

**Comment by AngryPhantom** [comment]
Oh, and use `configure_args="--with-gtk3"` in its template, please. The default ./configure will throw errors and stop compiling.

**Comment by AngryPhantom** [comment]
Sorry for bumping. Any update? Any maintainer here? :(

**Comment by ericonr** [comment]
@AngryPhantom would you like to make a PR for it?

**Comment by AngryPhantom** [comment]
@ericonr Will it make any change if the maintainer doesn't answer an update request? I'm afraid I'm too noob to make a PR, I'm just an average user...

**Comment by ericonr** [comment]
@AngryPhantom it definitely will make a difference! The maintainer might not have had time to make the update, but other people can review your Pull Request and merge it. Opening a PR definitely helps in getting your changes in Void :)

**Comment by Noah-Huppert** [comment]
@AngryPhantom just submitted a PR with 1.4.5

**Comment by AngryPhantom** [comment]
Oh, thanks!
