### ISSUE TITLE
Package Request: Zoom

### ISSUE THREAD

**Issue by jalelegenda** [void-linux/void-packages#20404]
https://zoom.us/support/download

A Linux client for Zoom meetings.

**Comment by Duncaen** [comment]
We are not allowed to redistribute binaries per license.
It is already in the repository as [restricted](https://docs.voidlinux.org/xbps/repositories/restricted.html) package [srcpkgs/zoom/template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/zoom/template).
