### ISSUE TITLE
freetype: Shouldn't subpixel rendering be disabled by default?

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#2042]
As I was working on a patch to add an option to enable subpixel rendering on FreeType, I saw that the repo already ships a patch file that activates it **by default**.  ClearType-based subpixel rendering is covered by Microsoft patents and shouldn't be enabled by default, [as stated by the documentation](https://github.com/winlibs/freetype/blob/master/devel/ftoption.h#L108-L121).

As I remember, ClearType-related patents should expire in 2019 or so; when it happens, FreeType should be able to activate it on default builds, as they did for subpixel hinting.  For now, one could adopt the solution I told above, with an option for subpixel rendering, disabled by default.

I don't know your position about this, but I thought this concern should be raised.

**Comment by chneukirchen** [comment]
People claimed these patents expired already, and Debian used to apply that patch fine.

Apparently it's not needed since 2.8.1 however. Someone please test this.

Prior issue: https://github.com/voidlinux/void-packages/issues/2864

**Comment by skrps** [comment]
Just looking at the source, there are basically 3 source files affected by `FT_CONFIG_OPTION_SUBPIXEL_RENDERING`: `ftsmooth.c`, `ftlcdfil.c` and `ftobjs.c`.  Comparing those files from 2.9.1 and 2.8.1, one can see that indeed much of the code related to this option was removed, but there remains code for [LCD filtering](http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/src/base/ftlcdfil.c) and [subpixel rendering itself](http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/src/smooth/ftsmooth.c).  In fact, [the documentation states](https://www.freetype.org/freetype2/docs/reference/ft2-lcd_filtering.html) that, without `FT_..._SUBPIXEL_RENDERING`, LCD filtering functions turn into no-op, which is also the case for 2.8.1.

**Comment by chneukirchen** [comment]
I mean it's not needed as in "it looks good enough without".

**Comment by skrps** [comment]
Oh, ok.  I can test it and give an answer until this weekend.
