### ISSUE TITLE
Package Request: realtime-privileges

### ISSUE THREAD

**Issue by jarbowski** [void-linux/void-packages#20449]
hi,
i find the arch solution simple and efficient for realtime audio.
hope you'll agree.
thanks

https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/realtime-privileges

**Comment by daniel-eys** [comment]
The `jack` package includes those realtime audio settings (udev-rules, limits).

**Comment by jarbowski** [comment]
oups, I missed the udev rule
thanks
