### ISSUE TITLE
No package contains the crypttab manpages

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#20452]
### Expected behavior

Some version of https://www.freedesktop.org/software/systemd/man/crypttab.html should be available in the system, possibly in the cryptsetup package.

### Actual behavior

No such man page is available.

### Steps to reproduce the behavior

`xbps-query -Ro crypttab` contains results only from `base-files` and configuration systems.

**Comment by sgn** [comment]
https://manpages.debian.org/buster/cryptsetup-run/crypttab.5.en.html#ON_DIFFERENT_CRYPTTAB_FORMATS
> Please note that there are several independent cryptsetup wrappers with their own crypttab format.

If cryptsetup themselves don't provides `crypttab(5)`, we needs to figure out what options they provide.

The link you provided is specified for systemd, I don't use crypttab at all even if I use FDE (except /boot)

**Comment by ericonr** [comment]
Oh yeah, I know it's systemd specific, but it was the first result when I searched for the documentation. I will take a look and see where the cryptsetup package comes from. It would probably be preferable to have the man pages come from upstream, right?

**Comment by ericonr** [comment]
At least on Manjaro, crypttab man file comes from systemd. cryptsetup doesn't have manpages for crypttab.

At least on my system, it's dracut that interprets the crypttab, but given that it's a project supposed to be used with systemd, they probably didn't feel the need to write their own version of the documentation. We can try to curate the parts of the documentation that are universal and the ones that pertain only to systemd.

DragonFlyBSD has their own man page for crypttab https://man.bsd.lv/DragonFly-5.6.1/crypttab

**Comment by daniel-eys** [comment]
crypttab is done by the distribution's init system, so runit in void's case.
Void's crypttab wrapper is an awk script (`/etc/runit/crypt.awk`), where you can read, what cryptsetup options are wrapped.
For the documentaion of those options, see `man 8 cryptsetup`.

**Comment by ericonr** [comment]
@daniel-eys given that runit isn't really update anymore (which is fair), is there any place the docs could go to? I feel like requiring that people read an AWK script of all things to configure their crypttab kind of sucks :/

**Comment by daniel-eys** [comment]
@ericonr Sorry, I should have been more precise. I meant void's runit init scripts, so this repo https://github.com/void-linux/void-runit. This would be the place for such a manpage.

**Comment by ericonr** [comment]
All right, that sounds great! I will open an issue there and try to write a man page too. Thanks!

**Comment by ericonr** [comment]
I will close this one because it doesn't pertain to this repo anymore.
