### ISSUE TITLE
vivaldi: Not built from source

### ISSUE THREAD

**Issue by toluschr** [void-linux/void-packages#20460]
### System
As far as I'm aware, the Vivaldi browser is partly open source.
https://vivaldi.com/source/

The package in the repositories uses a binary instead of building from source. Is there a reason for this?

I saw that the versions of the binary and the source code don't match.
Is a new package (perhaps `vivaldi-source`) needed?

* xuname:  
  Void 5.5.13_1 x86_64 AuthenticAMD notuptodate rrrrmmnFFFFFFFFFFFFF
* package:  
  vivaldi

### Expected behavior
Vivaldi is available in the repositories.

### Actual behavior
Vivaldi is a restricted package and not built from source.

**Comment by Johnnynator** [comment]
Building it from source would still require it to be restricted, except you wanna fork it, remove all branding, etc... Nobody here as any interest in doing this.

**Comment by toluschr** [comment]
Makes sense
