### ISSUE TITLE
Package request: firefox-developer-edition

### ISSUE THREAD

**Issue by ardadem** [void-linux/void-packages#20490]
https://www.mozilla.org/tr/firefox/developer/
Firefox Developer Edition has useful tools for web developers. Can we get this into repo?

**Comment by Chocimier** [comment]
We distribute stable versions only, and this is testing line.

> Mozilla’s pre-release versions of Firefox (which are distributed through channels such as Nightly, Beta, Developer Edition and TestFlight) are development platforms frequently updated with experimental features and studies.

~ https://www.mozilla.org/en-US/privacy/firefox/#pre-release

**Comment by thegarlynch** [comment]
Wait, this should not really become actual reason right ? firefox developer edition comes with a whole set of features

**Comment by Duncaen** [comment]
We don't have the resources to maintain and build more and even faster moving versions of firefox.

**Comment by autoteelar** [comment]
> Wait, this should not really become actual reason right ? firefox developer edition comes with a whole set of features

i agree with this guy, im sure someone out there is willing to update it
