### ISSUE TITLE
strawberry: missing translations

### ISSUE THREAD

**Issue by VoidDuck** [void-linux/void-packages#20547]
Hello,

The Strawberry music player is missing its translations. The program will only run in English and the language selector is not present in the settings panel.

I tried the same Strawberry version on Solus Linux and the translations as well as the language switcher are available.

### System

* xuname:  
  *Void 5.4.28_1 x86_64 GenuineIntel uptodate rF*
* package:  
  *strawberry-0.6.8_2*

**Comment by xtraeme** [comment]
Missing gettext

**Comment by q66** [comment]
will fix
