### ISSUE TITLE
re-enabling statx support on coreutils

### ISSUE THREAD

**Issue by ailiop-git** [void-linux/void-packages#20556]
Commit 9cd29dcf7e ("coreutils: disable statx() support on glibc.") disabled detection of statx support as a workaround, due to the kernel>=v4.11 requirement that breaks travis.

Restoring statx support in coreutils would be nice, as stat (1) and ls are able to report inode birth times only via statx.

@xtraeme not sure what the plan with travis is, but would it make sense to create a base-minimal-travis that depends on a coreutils-compat (or something, maybe a subpkg) that disables statx? That way we can re-enable it on coreutils so that base-system is not impacted.

**Comment by xtraeme** [comment]
Seriously this is bullshit

**Comment by ailiop-git** [comment]
so what is the issue with travis anyway? the config is pointing to bionic, which should run a recent enough kernel to support statx.

**Comment by xtraeme** [comment]
See xbps issues

**Comment by ailiop-git** [comment]
I assume you meant https://travis-ci.org/github/void-linux/xbps/jobs/669154357.

Ok, so in that case can we just build xbps on travis with `dist: bionic` and get rid of the workarounds?

**Comment by xtraeme** [comment]
Try it yourself

**Comment by ailiop-git** [comment]
https://travis-ci.org/github/ailiop-git/xbps/builds/669887920

**Comment by xtraeme** [comment]
hmm cool, can you please submit a PR in xbps? and then we can reactivate statx in coreutils.

**Comment by xtraeme** [comment]
@ailiop-git merged, thanks. Do you want to make the coreutils PR?

**Comment by Johnnynator** [comment]
Just as a note, we still have linux3.16 and linux4.9. And I think coreutils should work with them, as long as we still provide them.

**Comment by pullmoll** [comment]
Perhaps create a coreutils-legacy package which disables the statx(2) check and is built at the same time?

**Comment by ailiop-git** [comment]
hmm do we have any testing on those older kernels? I'd suspect there may be further problems with glibc being built on newer kernels and autodetecting features that are not necessarily available on a 3.16 kernel for example.

**Comment by pullmoll** [comment]
I do not test the 3.16 kernel, just make sure it can be built. I don't actually know if we have any users of this version.

**Comment by xtraeme** [comment]
Someone with glibc please test linux3.16.

**Comment by pullmoll** [comment]
linux3.16 does not even boot on my (recent) hardware.
I'll try to catch any log but currently cannot test it here.

**Comment by xtraeme** [comment]
I'll test it, but I'm using musl and there shouldn't be any difference. glibc might have issues as @ailiop-git mentioned above.

**Comment by ailiop-git** [comment]
3.16 doesn't seem to be booting at all (getting stuck in early boot process after decompress/parsing ELF, and/or cold-rebooting). I can try to debug it later on a VM if there's still interest in having this kernel around, let me know.

3.18, 4.9 boot fine, and coreutils doesn't complain with statx enabled (glibc silently fallsback to stat).

BTW 3.18 isn't LTS upstream (@pullmoll should we consider dropping it?)

**Comment by xtraeme** [comment]
rofl my system reboots instantly after loading the initramfs

**Comment by xtraeme** [comment]
looks like 3.16 is completely broken, let's remove it.

**Comment by pullmoll** [comment]
Same here. I can not get a single log output :-P *agree to remove*
I wonder who requested it and never reported back that it didn't work.

**Comment by xtraeme** [comment]
@pullmoll as @ailiop-git mentions above the -legacy subpkg isn't required at all.

**Comment by pullmoll** [comment]
@ailiop-git 3.18? We don't have that or do we?
3.16 worked when I added it and perhaps a couple of version more.
@xtraeme ok, then let's merge @ailiop-git PR.

**Comment by xtraeme** [comment]
@ailiop-git linux3.18 was removed long ago from void-packages but looks like the binpkgs are still there. The void official repos are full of obsolete/removed pkgs...

**Comment by xtraeme** [comment]
I mentioned this issue lots of times to the admins in charge but nobody made any action...

**Comment by xtraeme** [comment]
this is on musl:

```
[-] linux3.16-3.16.82_1                       Linux kernel and modules (3.16 series)
[-] linux3.16-headers-3.16.82_1               Linux kernel and modules (3.16 series) - source headers for 3rd party modules
[-] linux3.18-3.18.124_1                      The Linux kernel and modules (3.18 series)
[-] linux3.18-headers-3.18.124_1              The Linux kernel and modules (3.18 series) - source headers for 3rd party modules
[-] linux4.14-4.14.172_1                      Linux kernel and modules (4.14 series)
[-] linux4.14-headers-4.14.172_1              Linux kernel and modules (4.14 series) - source headers for 3rd party modules
[-] linux4.19-4.19.113_1                      Linux kernel and modules (4.19 series)
[-] linux4.19-headers-4.19.113_1              Linux kernel and modules (4.19 series) - source headers for 3rd party modules
[-] linux4.4-4.4.215_1                        The Linux kernel and modules (4.4 series)
[-] linux4.4-headers-4.4.215_1                The Linux kernel and modules (4.4 series) - source headers for 3rd party modules
[-] linux4.9-4.9.215_1                        Linux kernel and modules (4.9 series)
[-] linux4.9-headers-4.9.215_1                Linux kernel and modules (4.9 series) - source headers for 3rd party modules
[-] linux5.2-5.2.21_1                         Linux kernel and modules (5.2 series)
[-] linux5.2-headers-5.2.21_1                 Linux kernel and modules (5.2 series) - source headers for 3rd party modules
[-] linux5.3-5.3.18_1                         Linux kernel and modules (5.3 series)
[-] linux5.3-headers-5.3.18_1                 Linux kernel and modules (5.3 series) - source headers for 3rd party modules
[-] linux5.4-5.4.29_1                         Linux kernel and modules (5.4 series)
[-] linux5.4-headers-5.4.29_1                 Linux kernel and modules (5.4 series) - source headers for 3rd party modules
[-] linux5.5-5.5.14_1                         Linux kernel and modules (5.5 series)
[-] linux5.5-headers-5.5.14_1                 Linux kernel and modules (5.5 series) - source headers for 3rd party modules
[*] linux5.6-5.6.2_1                          Linux kernel and modules (5.6 series)
[-] linux5.6-headers-5.6.2_1                  Linux kernel and modules (5.6 series) - source headers for 3rd party modules
```

**Comment by ailiop-git** [comment]
same on glibc, i suppose infra needs a xbps-rindex -c crontab or something along those lines.

**Comment by pullmoll** [comment]
In case I wouldn't clean my repo on each update, I'd see ENOSPC more often.
Currently I am at 917GB of binary packages for all arches and the noarch brach ... yay.

**Comment by xtraeme** [comment]
rofl almost 1TB :-)

I've tested 4.4 and 4.9 successfully, obviously those kernels don't support sway... but I'm using xorg successfully.

```
[juan@leysa ~]$ uname -a
Linux leysa 4.9.215_1 #1 SMP PREEMPT Sun Mar 1 08:33:53 UTC 2020 x86_64 GNU/Linux
[juan@leysa ~]$
```

**Comment by xtraeme** [comment]
I'm going to remove linux3.16, @pullmoll ok?

**Comment by pullmoll** [comment]
@xtrame go ahead.

**Comment by xtraeme** [comment]
done, @ailiop-git did you test coreutils stat(1) with statx on 4.4/4.9 then?

**Comment by xtraeme** [comment]
I just updated all kernels to the latest version, just in case :-)

**Comment by ailiop-git** [comment]
Linux ash 4.4.215_1 #1 SMP PREEMPT Sun Mar 1 08:34:51 UTC 2020 x86_64 GNU/Linux

$ strace -fe statx,fstat stat -t /
statx(AT_FDCWD, "/", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, 0x7fff1d37dda0) = -1 ENOSYS (Function not implemented)
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(0x88, 0), ...}) = 0
/ 4096 8 41ed 0 0 801 2 17 0 0 1585834498 1582119865 1582119865 0 4096
+++ exited with 0 +++

Linux ash 4.9.215_1 #1 SMP PREEMPT Sun Mar 1 08:33:53 UTC 2020 x86_64 GNU/Linux

$ strace -fe statx,fstat stat -t /
statx(AT_FDCWD, "/", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, 0x7fff1d37dda0) = -1 ENOSYS (Function not implemented)
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(0x88, 0), ...}) = 0
/ 4096 8 41ed 0 0 801 2 17 0 0 1585834498 1582119865 1582119865 0 4096
+++ exited with 0 +++

Linux ash 5.4.23_1 #1 SMP PREEMPT Sat Feb 29 10:14:39 UTC 2020 x86_64 GNU/Linux

$ strace -fe statx stat -t /
statx(AT_FDCWD, "/", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFDIR|0755, stx_size=4096, ...}) = 0
/ 4096 8 41ed 0 0 801 2 17 0 0 1585834498 1582119865 1582119865 1524685643 4096
+++ exited with 0 +++

@xtraeme looks OK, falling back to fstat in both 4.{4,9} (same stat binary, compiled against latest glibc on 5.4, statx enabled).

**Comment by xtraeme** [comment]
cool, thanks.

**Comment by xtraeme** [comment]
https://github.com/void-linux/void-packages/commit/0010d6d3e63b86eef3c8af05af2e19b7f8465744

merged, thanks!
