### ISSUE TITLE
mesa-20.0.3_1 Error starting CAESES

### ISSUE THREAD

**Issue by sebu06** [void-linux/void-packages#20565]
### System

* xuname:  
  Void 5.5.13_1 x86_64 GenuineIntel uptodate rrrrmdFFFF
* package:  
  mesa-20.0.3_1

### Expected behavior
Up to Mesa 19.3.4_1 I was able to run CAESES (proprietary CAD system) without any problems. With the current Mesa-libs, CAESES fails to start.

### Actual behavior
The following error message appears:
`libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/xorg/modules/drivers)`
`libGL error: failed to load driver: iris`
`libGL error: MESA-LOADER: failed to open iris (search paths /usr/lib/xorg/modules/drivers)`
`libGL error: failed to load driver: iris`
`libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/xorg/modules/drivers)`
`libGL error: failed to load driver: swrast`
`QGLTempContext: Unable to create GL context.`
`init glwindow: context not valid!`
`[xcb] Unknown sequence number while processing queue`
`[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called`
`[xcb] Aborting, sorry about that.`
`CAESES: xcb_io.c:260: poll_for_event: Assertion !xcb_xlib_threads_sequence_lost' failed.`

By looking at the strace info, Mesa 19.3.4_1 loads:

`[pid 28187] openat(AT_FDCWD, "/usr/lib/xorg/modules/drivers/tls/i965_dri.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)`
`[pid 28187] openat(AT_FDCWD, "/usr/lib/xorg/modules/drivers/i965_dri.so", O_RDONLY|O_CLOEXEC) = 19`

whereas Mesa 20.0.3_1 loads:

`[pid 26302] openat(AT_FDCWD, "/usr/lib/xorg/modules/drivers/tls/swrast_dri.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)`
`[pid 26302] openat(AT_FDCWD, "/usr/lib/xorg/modules/drivers/swrast_dri.so", O_RDONLY|O_CLOEXEC) = 19`

`[pid 26302] openat(AT_FDCWD, "/usr/lib/xorg/modules/drivers/tls/iris_dri.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)`
`[pid 26302] openat(AT_FDCWD, "/usr/lib/xorg/modules/drivers/iris_dri.so", O_RDONLY|O_CLOEXEC) = 20`

If necessary, I can provide full strace output for both mesa versions, but maybe this is enough to point into the right direction. I tried modesetting and xf86-video-intel - no difference.

Thanks for the help, 
Sebastian

**Comment by xtraeme** [comment]
what GPU is it?

**Comment by sebu06** [comment]
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 08)
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)

**Comment by sebu06** [comment]
btw: glxgears runs fine using the iris driver

**Comment by st3r4g** [comment]
`MESA_LOADER_DRIVER_OVERRIDE=i965 ./CAESES` should tell the loader to load the old driver.
If this has no effect, another way is to create the following configuration file in `~/.drirc` (per user) or `/etc/drirc` (system-wide):
```
<driconf>
  <device driver="loader" kernel_driver="i915">
    <option name="dri_driver" value="i965" />
  </device>
</driconf>
```

**Comment by sebu06** [comment]
Thanks - that helped.
