### ISSUE TITLE
virtualbox-ose-dkms: Build fails using linux5.6

### ISSUE THREAD

**Issue by toluschr** [void-linux/void-packages#20576]
### System

* xuname:  
  Void 5.6.2_1 x86_64 AuthenticAMD notuptodate rrrmFFFFFFFFFFFFFFFFF
* package:  
  virtualbox-ose-dkms-6.1.4_1

### Expected behavior
Building works

### Actual behavior
Building doesn't work

### Steps to reproduce the behavior
Use kernel 5.6

It works fine with the following patches:
https://www.virtualbox.org/changeset/83471/vbox
https://www.virtualbox.org/changeset/83473/vbox
https://www.virtualbox.org/changeset/83484/vbox

**Comment by toluschr** [comment]
I will just build experimental version from https://www.virtualbox.org/wiki/Testbuilds

**Comment by xtraeme** [comment]
This is still valid.
