### ISSUE TITLE
Should ConsoleKit2 be removed?

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#20577]
[ConsoleKit2](https://github.com/ConsoleKit2/ConsoleKit2) hasn't received any updates since 2017, which is quite worrying for a piece of software with that big of a scope. Its functionality has been superseded by elogind, and the only docs page that still refers to it is the one for session management under Xorg (which can be updated).

Running `xbps-query -RX ConsoleKit2` on armv6l-musl returned only `ConsoleKit2-devel` and `ulatencyd` (which hasn't been updated in a while either), so it shouldn't be a dependency for anything.

**Comment by xtraeme** [comment]
I mentioned this like 200 times in 3 months already...

The official voidlinux xbps repositories are full of obsolete/removed pkgs that aren't anymore in void-packages.

If any of  the admins in the @void-linux/void-ops group would run:

```
$ xbps-rindex -a repo
$ xbps-rindex -c repo
$ xbps-rindex -r repo
```

for any arch/repo, required size will be greatly reduced and there won't be broken packages.

I'm not an admin so the only thing I can do is mentioning this fact for the 200th time.

**Comment by xtraeme** [comment]
Just to be safe, the script should do:

```
for f in ${archs}; do
    XBPS_ARCH=$f xbps-rindex -a repo/*.xbps
done

for f in ${archs}; do
    export XBPS_ARCH=$f
    xbps-rindex -c repo
    xbps-rindex -r repo
done
```

**Comment by ericonr** [comment]
Just found c2b89d6bff8 and its parent commit, sorry. Should I keep the issue open till it's removed?

Thanks for the quick response, though. I will try to update the docs accordingly.

**Comment by Duncaen** [comment]
I clean the repositories regularly, but its also required to remove the package files that need to be purged.
Without a list I can run the cleanup script daily and nothing will change.

**Comment by xtraeme** [comment]
https://github.com/void-linux/void-infrastructure/blob/master/ansible/roles/buildmaster/templates/xbps-clean-repos.sh.j2

is this file used anywhere?

**Comment by xtraeme** [comment]
I don't know how the infra works really, the only thing I could do is trying to cleanup/update this script.

**Comment by xtraeme** [comment]
@Duncaen what list are you talking about?

**Comment by xtraeme** [comment]
@Duncaen are you saying that maybe `xbps-rindex` might need `-n/--dry-run` ?

**Comment by Duncaen** [comment]
Yes variations of it with the right architectures for each build server.

I did run those scripts [8 days ago](https://github.com/void-linux/void-packages/issues/20357#issuecomment-603858079) to clean the libllvm3.9 stuff.

But I need to rm the xbps archives to actually get those things out of the repo.

**Comment by xtraeme** [comment]
this script is missing some archs and repos, afaik.

**Comment by Duncaen** [comment]
removing the template from the xbps-src repository will leave the package archives behind, `xbps-rindex` doesn't know if the template still exists or not.

**Comment by xtraeme** [comment]
but we do have `xbps-checkvers -e` now:

```
     -e, --removed
         List packages present in repos, but not in distdir.  Srcver is a
         question mark for them.
```

**Comment by xtraeme** [comment]
@Duncaen I see what you are saying, we just need to improve the clean script to use `xbps-checkvers -e` as well.

**Comment by xtraeme** [comment]
```
[juan@leysa void-packages]$ xbps-checkvers -D $PWD -e --format="%n"|wc -l
320
[juan@leysa void-packages]$
```
on x86_64-musl

**Comment by xtraeme** [comment]
```
[masterdir-x86_64 /]$ xbps-checkvers -D /void-packages -e --format="%n"|wc -l
558
```
on x86_64 glibc

**Comment by Duncaen** [comment]
this includes debug and 32bit packages...

**Comment by xtraeme** [comment]
right, all them should be removed

**Comment by xtraeme** [comment]
@Duncaen I'm updating the clean script

**Comment by the-maldridge** [comment]
The file you linked above is in use.  void-linux/void-infrastructure#58 is to update it.  It needs to be templated for specific archs to clean since it has to run in 3 different places.  If you send a PR for an updated clean script, I can make sure the rest of the things around it are updated and it gets installed in the right places.

**Comment by xtraeme** [comment]
@the-maldridge ok, working on it.

**Comment by xtraeme** [comment]
@the-maldridge what do you mean by "It needs to be templated for specific archs to clean" ?

**Comment by the-maldridge** [comment]
Since the clean has to be run from an authoritative location, it can only clean things that that location is authoratative for.  In the current version there's an ARCHS variable up at the top, which needs to be set to "armv6l armv7l x86_64 i686" in one place "aarch64 aarch64-musl" in another, and "armv7l-musl armv6l-musl x86_64-musl" in a third.

**Comment by xtraeme** [comment]
ok

**Comment by xtraeme** [comment]
done, https://github.com/void-linux/void-infrastructure/pull/62

**Comment by ericonr** [comment]
Can I leave the missing archs here? Using ConsoleKit2 as the diagnosis for their status, the archs that haven't been updated:

* aarch64: glibc and musl
* armv6l and armv7l: musl
* x86_64: musl

**Comment by Chocimier** [comment]
Moved to aggregate issue.
