### ISSUE TITLE
lazarus dependencies pulls in libQt5Pas but not libQt5Pas-devel

### ISSUE THREAD

**Issue by chriscamacho** [void-linux/void-packages#20655]
### System

* xuname:  
  Void 5.5.15_1 x86_64 GenuineIntel uptodate rrrrmdFFFFF
* package:  
  lazarus-2.0.2_1

### Expected behavior
 Lazarus requires the -devel version of the libQt5Pas package in order to compile anything using a form...

### Actual behavior
when trying to "run" a project you see
linker: /usr/bin/ld: cannot find -lQt5Pas

### Steps to reproduce the behavior
install lazarus, "run" a project

**Comment by ericonr** [comment]
The `qt5pas-devel` package has a lot of dependencies itself. Can simple projects still work without that?
