### ISSUE TITLE
Attempting a system upgrade creates a package collision with qt5 and qt5-styleplugins

### ISSUE THREAD

**Issue by Max-FT** [void-linux/void-packages#20662]
### System

* xuname:  
Void 5.4.29_1 x86_64 GenuineIntel uptodate rFFF
* packages:  
  *qt5-5.14.2_2, qt5-styleplugins-5.0.0_11*

### Expected behavior
Uneventful update of the system
### Actual behavior
Upgrade errors with

[*] Updating repository `http://lysator7eknrfl47rlyxvgeamrv7ucefgrrlhk7rouv3sna25asetwid.onion/pub/voidlinux/current/x86_64-repodata' ...
x86_64-repodata: 1661KB [avg rate: 371KB/s]
[*] Updating repository `http://lysator7eknrfl47rlyxvgeamrv7ucefgrrlhk7rouv3sna25asetwid.onion/pub/voidlinux/current/nonfree/x86_64-repodata' ...
qt5-5.14.2_2 in transaction breaks installed pkg `qt5-styleplugins-5.0.0_11'
Transaction aborted due to unresolved dependencies.
### Steps to reproduce the behavior
Run 'sudo torsocks xbps-install -Su' or 'sudo xbps-install -Su' as the same issue persists on the default mirrors too.

**Comment by bugcrazy** [comment]
Packages need to be rebuilt, using the new q5 libraries, the packages are in conflict, still use the old libraries!

doas  xbps-install -S falkon  libksysguard   ksysguard  qupzilla
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...
MISSING: qt5-declarative-5.13.2_2

**Comment by flexibeast** [comment]
The build server is working on a Qt5 upgrade, which is taking quite some time. Check the waterfall for status updates: https://build.voidlinux.org/waterfall

**Comment by Max-FT** [comment]
Thanks @flexibeast, figured it was being built, but wanted to file an issue just to make sure

**Comment by xtraeme** [comment]
```
[juan@leysa ~]$ xbps-query -Rx qt5-styleplugins|grep qt5
qt5-core>=5.14.2<5.14.3
qt5-dbus>=5.14.1_1
qt5-gui>=5.14.1_1
qt5-widgets>=5.14.1_1
[juan@leysa ~]$
```
not an issue, just wait until the builders finish.
