### ISSUE TITLE
problems with zfs-0.8.3_2

### ISSUE THREAD

**Issue by emacsomancer** [void-linux/void-packages#20673]
### System

* xuname:  
Linux sushoma 5.4.29_1 #1 SMP PREEMPT Wed Apr 1 10:52:40 UTC 2020 x86_64 GNU/Linux
* package:  
zfs-0.8.3_2, linux4.14

### Expected behavior
Properly rebuild dkms modules. 
### Actual behavior
Dies while building DKMS module. Even worse, this means it doesn't try to rebuild DKMS modules for other kernels (ideally a DKMS module dying in some fashion shouldn't stop the other modules from building...especially since all of the old ZFS DKMS modules get removed first)
```
sudo xbps-reconfigure -f linux4.19 linux5.4
linux4.19: configuring ...
Executing post-install kernel hook: 10-dkms ...
Available DKMS module: acpi_call-1.2.0.
Available DKMS module: wireguard-1.0.20200401.
Available DKMS module: zfs-0.8.3.
Building DKMS module: acpi_call-1.2.0... done.
Building DKMS module: wireguard-1.0.20200401... done.
Building DKMS module: zfs-0.8.3... killed
```
### Steps to reproduce the behavior
Install new `zfs-0.8.3_2` or reconfigure `linux4.14`

**Comment by xtraeme** [comment]
Killed rofl

**Comment by emacsomancer** [comment]
> Killed rofl

It wasn't killed via user input, either the first time this occurred via `sudo xbps-install -Su` or via `sudo xbps-reconfigure -f linux4.14`.

**Comment by ahesford** [comment]
The `zfs-0.8.3_2` DKMS builds for me with `linux4.14-414.174_1` on x86_64. Your text references `linux4.14`, but your output refers to `linux4.19`. I've had no problems building against either. Can you reconcile the difference and see if there is a DKMS build log in `/var/lib/dkms/zfs/0.8.3/build/make.log` that explains the error?

**Comment by emacsomancer** [comment]
> The `zfs-0.8.3_2` DKMS builds for me with `linux4.14-4.14.174_1` on x86_64. Your text references `linux4.14`, but your output refers to `linux4.19`. I've had no problems building against either. Can you reconcile the difference and see if there is a DKMS build log in `/var/lib/dkms/zfs/0.8.3/build/make.log` that explains the error?

I was eventually able to get them to build, and so I didn't see anything in the DKMS build log after that. I'll keep an eye on it and re-open if I have something definitive.
