### ISSUE TITLE
NVIDIA 440.64 broken (linux-lts 4.14.174_1)

### ISSUE THREAD

**Issue by nbmvoid** [void-linux/void-packages#20676]
I have tried with xbps-reconfigure -f nvidia-dkms and didn't work either

xbps-reconfigure -f nvidia-dkms
nvidia-dkms: configuring ...
DKMS module 'nvidia-440.64' already added, skipping.
Building DKMS module 'nvidia-440.64' for kernel-4.14.174_1... FAILED!
DKMS module 'nvidia-440.64' failed to build, please check /var/lib/dkms for errors in the log file.
Regenerating initramfs, please wait...
nvidia-dkms: configured successfully.

DKMS make.log for nvidia-440.64 for kernel 4.14.174_1 (x86_64)
Sun 05 Apr 2020 02:08:14 PM -03
make[1]: Entering directory '/usr/src/kernel-headers-4.14.174_1'
  SYMLINK /var/lib/dkms/nvidia/440.64/build/nvidia/nv-kernel.o
  SYMLINK /var/lib/dkms/nvidia/440.64/build/nvidia-modeset/nv-modeset-kernel.o
 CONFTEST: hash__remap_4k_pfn
 CONFTEST: set_pages_uc
 CONFTEST: list_is_first
 CONFTEST: set_memory_uc
 CONFTEST: set_memory_array_uc
 CONFTEST: acquire_console_sem
 CONFTEST: console_lock
 CONFTEST: ioremap_cache
 CONFTEST: ioremap_wc
 CONFTEST: acpi_walk_namespace
 CONFTEST: sg_alloc_table
 CONFTEST: pci_get_domain_bus_and_slot
 CONFTEST: get_num_physpages
 CONFTEST: efi_enabled
 CONFTEST: pde_data
 CONFTEST: proc_remove
 CONFTEST: pm_vt_switch_required
 CONFTEST: xen_ioemu_inject_msi
 CONFTEST: phys_to_dma
 CONFTEST: get_dma_ops
 CONFTEST: write_cr4
 CONFTEST: of_get_property
 CONFTEST: of_find_node_by_phandle
 CONFTEST: of_node_to_nid
 CONFTEST: pnv_pci_get_npu_dev
 CONFTEST: of_get_ibm_chip_id
 CONFTEST: node_end_pfn
 CONFTEST: pci_bus_address
 CONFTEST: pci_stop_and_remove_bus_device
 CONFTEST: pci_remove_bus_device
 CONFTEST: register_cpu_notifier
 CONFTEST: cpuhp_setup_state
 CONFTEST: dma_map_resource
 CONFTEST: backlight_device_register
 CONFTEST: timer_setup
 CONFTEST: pci_enable_msix_range
 CONFTEST: do_gettimeofday
 CONFTEST: kernel_read
 CONFTEST: kernel_write
 CONFTEST: kthread_create_on_node
 CONFTEST: of_find_matching_node
 CONFTEST: dev_is_pci
 CONFTEST: dma_direct_map_resource
 CONFTEST: tegra_get_platform
 CONFTEST: flush_cache_all
 CONFTEST: vmf_insert_pfn
 CONFTEST: address_space_init_once
 CONFTEST: kbasename
 CONFTEST: vzalloc
 CONFTEST: wait_on_bit_lock_argument_count
 CONFTEST: bitmap_clear
 CONFTEST: usleep_range
 CONFTEST: radix_tree_empty
 CONFTEST: radix_tree_replace_slot
 CONFTEST: pnv_npu2_init_context
 CONFTEST: cpumask_of_node
 CONFTEST: drm_dev_unref
 CONFTEST: drm_reinit_primary_mode_group
 CONFTEST: get_user_pages_remote
 CONFTEST: get_user_pages
 CONFTEST: drm_gem_object_lookup
 CONFTEST: drm_atomic_state_ref_counting
 CONFTEST: drm_driver_has_gem_prime_res_obj
 CONFTEST: drm_atomic_helper_connector_dpms
 CONFTEST: drm_connector_funcs_have_mode_in_name
 CONFTEST: drm_framebuffer_get
 CONFTEST: drm_gem_object_get
 CONFTEST: drm_dev_put
 CONFTEST: drm_connector_for_each_possible_encoder
 CONFTEST: is_export_symbol_gpl_of_node_to_nid
 CONFTEST: is_export_symbol_present_swiotlb_map_sg_attrs
 CONFTEST: is_export_symbol_present_swiotlb_dma_ops
 CONFTEST: is_export_symbol_present_kthread_create_on_node
 CONFTEST: acpi_op_remove
 CONFTEST: outer_flush_all
 CONFTEST: file_operations
 CONFTEST: proc_ops
 CONFTEST: ktime_get_raw_ts64
 CONFTEST: ktime_get_real_ts64
 CONFTEST: file_inode
 CONFTEST: kuid_t
 CONFTEST: dma_ops
 CONFTEST: swiotlb_dma_ops
 CONFTEST: noncoherent_swiotlb_dma_ops
 CONFTEST: vm_fault_has_address
 CONFTEST: backlight_properties_type
 CONFTEST: vm_insert_pfn_prot
 CONFTEST: vmf_insert_pfn_prot
 CONFTEST: vm_ops_fault_removed_vma_arg
 CONFTEST: vmbus_channel_has_ringbuffer_page
 CONFTEST: device_driver_of_match_table
 CONFTEST: device_of_node
 CONFTEST: node_states_n_memory
 CONFTEST: kmem_cache_has_kobj_remove_work
 CONFTEST: sysfs_slab_unlink
 CONFTEST: address_space
 CONFTEST: backing_dev_info
 CONFTEST: mm_context_t
 CONFTEST: vm_fault_t
 CONFTEST: drm_bus_present
 CONFTEST: drm_bus_has_bus_type
 CONFTEST: drm_bus_has_get_irq
 CONFTEST: drm_bus_has_get_name
 CONFTEST: drm_driver_has_legacy_dev_list
 CONFTEST: drm_driver_has_set_busid
 CONFTEST: drm_crtc_state_has_connectors_changed
 CONFTEST: drm_init_function_args
 CONFTEST: drm_helper_mode_fill_fb_struct
 CONFTEST: drm_master_drop_has_from_release_arg
 CONFTEST: drm_driver_unload_has_int_return_type
 CONFTEST: drm_atomic_helper_crtc_destroy_state_has_crtc_arg
 CONFTEST: drm_crtc_helper_funcs_has_atomic_enable
 CONFTEST: drm_mode_object_find_has_file_priv_arg
 CONFTEST: dma_buf_owner
 CONFTEST: drm_connector_list_iter
 CONFTEST: drm_atomic_helper_swap_state_has_stall_arg
 CONFTEST: drm_driver_prime_flag_present
 CONFTEST: drm_gem_object_has_resv
 CONFTEST: dom0_kernel_present
 CONFTEST: nvidia_vgpu_hyperv_available
 CONFTEST: nvidia_vgpu_kvm_build
 CONFTEST: nvidia_grid_build
 CONFTEST: nvidia_grid_csp_build
 CONFTEST: pm_runtime_available
 CONFTEST: drm_available
 CONFTEST: drm_atomic_available
 CONFTEST: is_export_symbol_gpl_refcount_inc
 CONFTEST: is_export_symbol_gpl_refcount_dec_and_test
 CONFTEST: drm_alpha_blending_available
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-frontend.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-pci.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-acpi.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-cray.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-dma.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-i2c.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-mempool.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-mmap.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-p2p.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-pat.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-procfs.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-usermap.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-vm.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/nv-vtophys.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/os-interface.o
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/os-mlock.o
In file included from /var/lib/dkms/nvidia/440.64/build/nvidia/os-interface.c:17:
/var/lib/dkms/nvidia/440.64/build/common/inc/nv-time.h: In function 'nv_gettimeofday':
/var/lib/dkms/nvidia/440.64/build/common/inc/nv-time.h:38:21: error: passing argument 1 of 'do_gettimeofday' from incompatible pointer type [-Werror=incompatible-pointer-types]
   38 |     do_gettimeofday(tv);
      |                     ^~
      |                     |
      |                     struct nv_timeval *
In file included from ./include/linux/ktime.h:272,
                 from ./include/linux/timer.h:6,
                 from ./include/linux/workqueue.h:9,
                 from ./include/linux/srcu.h:34,
                 from ./include/linux/notifier.h:16,
                 from ./include/linux/memory_hotplug.h:7,
                 from ./include/linux/mmzone.h:782,
                 from ./include/linux/gfp.h:6,
                 from ./include/linux/mm.h:10,
                 from /var/lib/dkms/nvidia/440.64/build/common/inc/nv-pgprot.h:17,
                 from /var/lib/dkms/nvidia/440.64/build/common/inc/nv-linux.h:20,
                 from /var/lib/dkms/nvidia/440.64/build/nvidia/os-interface.c:15:
./include/linux/timekeeping.h:19:45: note: expected 'struct timeval *' but argument is of type 'struct nv_timeval *'
   19 | extern void do_gettimeofday(struct timeval *tv);
      |                             ~~~~~~~~~~~~~~~~^~
  CC [M]  /var/lib/dkms/nvidia/440.64/build/nvidia/os-pci.o
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:326: /var/lib/dkms/nvidia/440.64/build/nvidia/os-interface.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1544: _module_/var/lib/dkms/nvidia/440.64/build] Error 2
make[1]: Leaving directory '/usr/src/kernel-headers-4.14.174_1'
make: *** [Makefile:81: modules] Error 2

**Comment by xtraeme** [comment]
nvidia-440.64_2 added support for linux5. 6

**Comment by nbmvoid** [comment]
Then I might need to downgrade to nvidia-440.64_1
thanks

**Comment by xtraeme** [comment]
Well, that was our version.

**Comment by xtraeme** [comment]
440.82 from nvidia released.

**Comment by nbmvoid** [comment]
440.82_1 works perfectly with 4.14.174_1
thanks!!
