### ISSUE TITLE
Python3 can't import anything from PyQt5 (breaks Qutebrowser)

### ISSUE THREAD

**Issue by ianayl** [void-linux/void-packages#20710]
### System

* xuname:  
  ``Void 5.4.27_1 x86_64 GenuineIntel uptodate rFFFFF``
* package:  
  - ``python3-PyQt5-5.13.2_2``
  - ``qutebrowser-1.10.1_1``

### Expected behavior
This command
```sh
$ python3 -c 'import PyQt5.QtCore'
```
should just work without any issues? Importing anything from PyQt5 should just work
### Actual behavior
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
```
Python starts to freak out instead and tells me this file doesn't exist. Any programs using PyQt5, **such as qutebrowser**, breaks, returning
```
Fatal error: PyQt5.QtCore is required to run qutebrowser but could not be imported! Maybe it's not installed?

The error encountered was:
libQt5Core.so.5: cannot open shared object file: No such file or directory

Please search for the python3 version of PyQt5.QtCore in your distributions packages, or see https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc

If you installed a qutebrowser package for your distribution, please report this as a bug.
```
Granted though, even if I installed PyQt5, the file `libQt5Core.so.5` doesn't actually exist. Running
```sh
$ find / | grep Qt5Core
```
produces:
```
/usr/lib/libQt5Core.so.5.14
/usr/lib/libQt5Core.so.5.14.2
```
Now, I won't lie, I'm not very good with this stuff, but I think this means that `libQt5Core.so.5.14` should actually be `libQt5Core.so.5`?
### Steps to reproduce the behavior
Just install ``python3-PyQt5-5.13.2_2`` (I think this is the latest version) and try running ``python3 -c 'import PyQt5.QtCore'``, it should complain about no `libQt5Core.so.5`

Thank you for your time btw, I appreciate the help

**Comment by q66** [comment]
works here:

```
q66@rimi: /home/q66$ python3 -c 'import PyQt5.QtCore'
q66@rimi: /home/q66$ xbps-query -f qt5-core
/usr/lib/libQt5Core.so.5.14.2
/usr/lib/libQt5Core.so -> /usr/lib/libQt5Core.so.5.14.2
/usr/lib/libQt5Core.so.5 -> /usr/lib/libQt5Core.so.5.14.2
/usr/lib/libQt5Core.so.5.14 -> /usr/lib/libQt5Core.so.5.14.2
q66@rimi: /home/q66$ file /usr/lib/libQt5Core.so.5
/usr/lib/libQt5Core.so.5: symbolic link to libQt5Core.so.5.14.2
q66@rimi: /home/q66$ file /usr/lib/libQt5Core.so.5.14  
/usr/lib/libQt5Core.so.5.14: symbolic link to libQt5Core.so.5.14.2
q66@rimi: /home/q66$ file /usr/lib/libQt5Core.so.5.14.2
/usr/lib/libQt5Core.so.5.14.2: ELF 64-bit LSB shared object, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, interpreter /lib/ld64.so.2, for GNU/Linux 3.17.0, BuildID[sha1]=921524d4a50fc4039cc04e3946af6a55c2453226, stripped
```

**Comment by ianayl** [comment]
ohhhh, crap, so I'm actually dumb. I thought it was a python issue, so I uninstalled and reinstalled python qt stuff over and over again, turns out it was my qt5 stuff that was screwed up, not python qt stuff.

Well, thanks a lot man, that was dumb, sorry for this "issue"
