### ISSUE TITLE
glibc and rpcsvc-proto /usr/bin/rpcgen conflict

### ISSUE THREAD

**Issue by Duncaen** [void-linux/void-packages#20728]
Both packages provide `/usr/bin/rpcgen`, some packages use `rpcsvc-proto` in `hostmakedepends` to be able to build on musl.

I think it should be removed from glibc, put into a sub package or use alternatives.

**Comment by svenper** [comment]
I take it from [the readme](https://raw.githubusercontent.com/thkukuk/rpcsvc-proto/master/README) that it should be possible to replace this package with glibc:

> This package contains rpcsvc proto.x files from glibc, which are
missing in libtirpc. Additional it contains rpcgen, which is needed
to create header files and sources from protocol files.
This package is only needed, if glibc is installed without the
deprecated sunrpc functionality and libtirpc should replace it.

**Comment by ericonr** [comment]
Is this still an issue? Maybe the obsolete RPC removal from glibc took `rpcgen` with it.

**Comment by ahesford** [comment]
Our current glibc package does not seem to include rpcgen, so I think this issue resolved itself.
