### ISSUE TITLE
[FTBFS] mysql cross build (ppc64)

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#20741]
It fails after `[  9%] Built target GenYaccEmbeddedSource` here.
Already tried to add a line `bison --update sql/sql_yacc.yy` because that file gave a warning.

The real problem is, as always with cmake it seems, very well hidden and the error message tells exactly nothing (Error 2) - at least to me.

```
make: *** [Makefile:180: all] Error 2
=> ERROR: mysql-5.6.43_3: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/cmake.sh:73
```

**Comment by q66** [comment]
native build works fine here

i encountered something similar before (bison/flex having messed up output) and the reason was them being miscompiled somehow, if you're using your own packages, i'd rebuild `bison` and then `flex` with `-f` and try again

**Comment by pullmoll** [comment]
That didn't help but twiddling with the build rules for host vs. target binaries fixed it.
