### ISSUE TITLE
fwupdate: no longer buildable, abandoned upstream

### ISSUE THREAD

**Issue by sgn** [void-linux/void-packages#20776]
```
./xbps-src pkg fwupdate
```

is no longer buildable with gcc-9

It's abandoned upstream: https://github.com/rhboot/fwupdate/pull/136

**Comment by keshto** [comment]
What is the action item you would like?

**Comment by sgn** [comment]
On 2020-04-09 15:04:47-0700, Krsna Mahapatra <notifications@github.com> wrote:
> What is the action item you would like?

Just remove it.

**Comment by keshto** [comment]
Ok, will get a MR out.

**Comment by vimalamp** [comment]
I removed it: 
https://github.com/void-linux/void-packages/pull/20859
