### ISSUE TITLE
acpid and elogind don't play well with suspend

### ISSUE THREAD

**Issue by keshto** [void-linux/void-packages#20780]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
`Void 5.6.2_1 x86_64 GenuineIntel uptodate rFF`
* package:  
  *affected package(s) including the version*
```
elogind  (243.4_2)  [elogind-243.4_2]
libelogind  (243.4_2)  [libelogind-243.4_2]
acpid  (2.0.32_1)  [acpid-2.0.32_1]
```

### Expected behavior
Opening the laptop lid resumes the system
### Actual behavior
It wakes, but then suspends again almost instantly
### Steps to reproduce the behavior
There is a conflict between acpid and elogind. In /etc/acpi/handler.sh if we comment out the `zzz` things work as expected.
```
...
    button/lid)
        case "$3" in
                close)
                        # suspend-to-ram
                        logger "LID closed, suspending..."
                        #zzz
                        ;;
                open)   logger "LID opened" ;;
                *) logger "ACPI action undefined (LID): $2";;
        esac
        ;;
    *)
...
```
It seems that elogind (guessing from dmesg messages) is suspending before `zzz` is called and then when the lid opens `zzz` gets executed resulting in the suspend.

**Comment by keshto** [comment]
@xtraeme pinging you in

**Comment by xtraeme** [comment]
There's no issue here, elogind provides the acpid functionality... you shouldn't have both services enabled at the same time.

**Comment by keshto** [comment]
Only had acpid enabled, but I guess elogind gets started by something else. Removing acpid and adding elogind does indeed fix the conflict, but now suspend takes a good 10+seconds after the lid is closed to kick in and I will debug that further. Maybe there should be a conflict warning in elogind if acpid is enabled/running?

**Comment by keshto** [comment]
Closing as this is a documentation/user error/packaging request. Let me know if there is anything I can do to make this clearer.

**Comment by travankor** [comment]
void-docs is the right place to open an issue... btw the long suspend time with logind affects all systemd distros if you do some searching.

**Comment by ericonr** [comment]
@travankor do you think this could be documented in the session management part?

@keshto can you open an issue for it?

**Comment by keshto** [comment]
@ericonr https://github.com/void-linux/void-docs/pull/210
