### ISSUE TITLE
megatools: stable version doesn't work anymore

### ISSUE THREAD

**Issue by kartikynwa** [void-linux/void-packages#20820]
Mega.nz changed their link format which renders the current stable version (1.10.2) broken.

This is fixed in the experimental version of the software which the author suggests using on [the project's homepage](https://megatools.megous.com/), emphasis mine:

> For the most bleeding edge version of megatools with all the latest features and bugfixes see the experimental directory. Static builds for Windows and various Linux architectures are provided. **Unless you have reasons to run something else, this is the recommended version**.

I have created a template for the experimental builds [HERE](https://github.com/kartikynwa/void-packages/blob/megatools/srcpkgs/megatools/template). But I don't know Void's policy on this so I wanted to ask if it is acceptable before filing a PR. Please let me know what the consensus is.

**Comment by ericonr** [comment]
AFAIK Void doesn't like using non released software. Is there even a tentative "semi-stable" tag for commits after the fix?
