### ISSUE TITLE
Regression in Mumble 1.3.0_3 

### ISSUE THREAD

**Issue by Max-FT** [void-linux/void-packages#20858]
### System

* xuname:  
  *Void 5.6.2_1 x86_64 GenuineIntel uptodate rFFF*
* package:  
  *Mumble 1.3.0_3*

### Expected behavior
Mumble starts up in a second or so (on a SATA SSD)

### Actual behavior
Significantly delayed start up, due to mumble trying to connect to the JACK daemon when it isn't installed w/ output

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
exec of JACK server (command = "/usr/bin/jackd") failed: No such file or directory
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<W>2020-04-10 18:04:11.864 JackAudioSystem: unable to open client due to 2 errors:
<W>2020-04-10 18:04:11.864 JackAudioSystem: JackFailure - overall operation failed
<W>2020-04-10 18:04:11.864 JackAudioSystem: JackServerFailed - unable to connect to the JACK server
### Steps to reproduce the behavior
Upgrade to mumble 1.3.0_3

**Comment by ScrelliCopter** [comment]
Looks like Mumble 1.3.0 always tries to connect to JACK on startup regardless of backend settings.
Seems this was fixed upstream in https://github.com/mumble-voip/mumble/pull/3990 in master.
I'll try patching 1.3.0 with this change and see if it fixes the problem.
