### ISSUE TITLE
Why aren't some graphics packages built for armv6l? (Broken dependencies in packages due to this)

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#20861]
### System

Void 4.19.113_1 armv6l-musl Unknown uptodate rFFFFF

### Expected behavior

All the packages necessary for a proper graphical session should be available for this arch.

### Actual behavior

At least these packages aren't built for it:

* complete `mesa-dri` subpackage (the VC4 driver is excluded)
* `xorg-server-xwayland` subpackage

Not building `xorg-server-xwayland` for it made it necessary to include an architecture check in `plasma-workspace`. This check isn't included in `sway`, making it impossible to install sway on armv6l, because it can't find the `xorg-server-xwayland` dependency.

One option is adding the same compatibility check to the `sway` package and others; another options is making some sort of external check for it, to avoid duplication; another (and IMO the best one) is fully removing the restriction on building `xorg-server-xwayland` to make it available for all archs (I don't know if there's an issue with that).

The lack of a complete `mesa-dri` package for armv6l makes it impossible to have a hardware accelerated session, even though the VC4 driver is fully supported by Mesa and works on an armv6l device. I have built it with the VC4 driver.

This restriction also led to some weird result with the armv6l repositories, where the `mesa-vc4-dri` package is still listed, even though it can't be installed due to mismatched dependencies. (For that matter, the dbg package for armv7l is also out dated).

I can make PRs for these issues, because I have already made some of the necessary changes in order to build these packages in my system.

**Comment by st3r4g** [comment]
As for mesa, it seems that after version `17.1.8` (so in August 2017) the `vc4` driver was excluded from `armv6l` (the old package is still in the repo because someone forgot to purge it). If it works for you know it should be enabled.
The `armv7l` `mesa-vc4-dri-dbg` package should just be removed, we transitioned to a unified `mesa-dri` package, the debugging symbols are in `mesa-dri-dbg`
