### ISSUE TITLE
cmake build style doesn't allow to choose source dir

### ISSUE THREAD

**Issue by yopito** [void-linux/void-packages#20878]
### System

* xuname:  Void 5.4.31_1 x86_64-musl GenuineIntel uptodate rrnFF

* package:  packaging shiboken2 update to 5.14.2 (WIP)

### Expected behavior

want to use cmake with sources of a subdir of $wkrsrc via `-S` cmake flag:
```
[...]
wrksrc="${_pkgname}"
build_style=cmake
configure_args=" ... -S sources/shiboken2"
[...]
```
### Actual behavior

`-S <subdir>` has no effect.

### Additional details

xbps-src append "`../`" to cmake arguments unconditionally.  
Resulting command is something like `cmake (args) -S sources/shiboken2 ../`

So cmake uses sources of ${wrksrc}/build/.. instead of ${wrksrc}/sources/shiboken2/

Implied by `common/build-style/cmake.sh` on sed expression L63:

```
    60          # Override flags: https://gitlab.kitware.com/cmake/cmake/issues/19590
    61          CFLAGS="${CFLAGS/ -pipe / }" CXXFLAGS="${CXXFLAGS/ -pipe / }" \
    62                  cmake ${cmake_args} ${configure_args} $(echo ${cmake_builddir}|sed \
    63                          -e 's|[^/]$|/|' -e 's|[^/]*||g' -e 's|/|../|g')
    64
```
### Workaround

My current workaround: adding subdir to $wrksrc:

```
wrksrc="${_pkgname}/sources/shiboken2"
build_style=cmake
configure_args=" ... "  # removed " -S sources/shiboken2 "
[...]
```
... that makes xlint nervous:
```
srcpkgs/shiboken2/template:7: wrksrc should be a top-level directory
```

**Comment by pullmoll** [comment]
Can't you use `build_wrksrc="sources/shiboken2"` here?

**Comment by yopito** [comment]
nope: need to manage source dir at the configure step, not the build one.

**Comment by xtraeme** [comment]
so let's modify `build-style/cmake.sh` then!

**Comment by pullmoll** [comment]
Despite its name `build_wrksrc` is a modifier for all steps, not just build. See `common/xbps-src/shutils/common.sh` and there `ch_wrksrc()` which is called from every `run_step()`.

**Comment by yopito** [comment]
I was not aware of that.  
But within its `do_configure()` , cmake.sh (re)changes current dir to $cmake_builddir, so `build_wrksrc` is is not relevant in this case:

```
$ cat -n common/build-style/cmake.sh 
     1  #
     2  # This helper is for templates using cmake.
     3  #
     4  do_configure() {
     5          local cmake_args=
     6          [ ! -d ${cmake_builddir:=build} ] && mkdir -p ${cmake_builddir}
     7          cd ${cmake_builddir}
     8
[...]
```

**Comment by pullmoll** [comment]
Hmm... I think it's just that instead of `:=build` there should be something like `$PWD/build` which would then create the `build` directory below the possible `build_wrksrc`sub-directory inside `$wrksrc`, or just below `$wrksrc`. Anyway, this should be fixed in a way that doesn't complicate things :)

**Comment by yopito** [comment]
my bad !  
As suggested by @pullmoll : `build_wrksrc` is working perfectly fine in this case.

FTR, my `template` is now:
```
[...]
wrksrc="${_pkgname}"
build_wrksrc="sources/shiboken2"
build_style=cmake
configure_args="(args not specific to this issue)"
[...]
```

... let's close this non-issue
