### ISSUE TITLE
Package request: K-Games

### ISSUE THREAD

**Issue by toluschr** [void-linux/void-packages#20892]
The games made by KDE (https://kde.org/applications/games) feature some old games, including Tetris, Pacman, Bomberman, Minesweeper and others.
I'd like to have them included in the repos beside the GNOME-Games and am willing to create the packages myself. Is there a need for them?

**Comment by Hoshpak** [comment]
I don't think there's a specific need for them however some people will certainly appreciate having them available. Some of them are already packaged. If you feel like it, please go ahead and create PRs for the packages.
