### ISSUE TITLE
iwd: stderr spam to tty1

### ISSUE THREAD

**Issue by aajonusonline** [void-linux/void-packages#20912]
Same behavior as [#11928](https://github.com/void-linux/void-packages/issues/11928)

### Proposed change
Adding `> /dev/null 2>&1` to the last line of `iwd`'s `run` script seems to sovle the problem

from
`exec /usr/libexec/iwd ${OPTS}`
to
`exec /usr/libexec/iwd ${OPTS} > /dev/null 2>&1`

**Comment by ericonr** [comment]
Does this still allow logging?

**Comment by aajonusonline** [comment]
No idea, but that's what they do in NetworkManager. Is there a solution that will allow logging? I personally don't care about logging, I just don't want the tty to be spammed.

**Comment by ericonr** [comment]
That's fair. I will take a look at my setup to see how it works.

**Comment by NeelChotai** [comment]
Submitted a pull for this (#21353), definitely preferable to changing the run file every update.

**Comment by NeelChotai** [comment]
Fixed in 0de1920.
