### ISSUE TITLE
Can't update system(or possibly do anything xbps related) due to missing "poppler" package

### ISSUE THREAD

**Issue by vuksavic** [void-linux/void-packages#2092]
### System
This is what xuname gave me today:
`
MISSING: poppler>=0.68.0_1
MISSING: poppler>=0.68.0_1
Transaction aborted due to unresolved dependencies.
dmesg: read kernel buffer failed: Operation not permitted
Void 4.17.17_1 x86_64-musl GenuineIntel uptodate rrnF
`
### Expected behavior
Normal packages updates, also general normal system behavior.

### Actual behavior
`
[vuk@t420s:~]% sudo xbps-install -Syuv  
[*] Updating `https://repo.voidlinux.eu/current/musl/x86_64-musl-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/musl/nonfree/x86_64-musl-repodata' ...
Found Adapta-3.94.0.120_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found cups-filters-1.21.0_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found gdbm-1.18_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found gparted-0.32.0_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found libX11-1.6.6_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found libX11-devel-1.6.6_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found libblockdev-2.19_2 (update) in repository https://repo.voidlinux.eu/current/musl
Found libcups-filters-1.21.0_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found libdrm-2.4.94_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found libopenjpeg2-2.3.0_2 (update) in repository https://repo.voidlinux.eu/current/musl
Found libwmf-0.2.8.4_18 (update) in repository https://repo.voidlinux.eu/current/musl
Found linux4.17-4.17.18_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found linux4.17-headers-4.17.18_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found poppler-glib-0.68.0_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found poppler-utils-0.68.0_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found qt5ct-0.36_1 (update) in repository https://repo.voidlinux.eu/current/musl
Found xbps-triggers-0.108_1 (update) in repository https://repo.voidlinux.eu/current/musl
MISSING: poppler>=0.68.0_1
MISSING: poppler>=0.68.0_1
Transaction aborted due to unresolved dependencies.
[vuk@t420s:~]% 
`
Also during typing this some more errors popped out, all just require updating poppler, which when i try to install it shows that it's already installed.
### Steps to reproduce the behavior
I suppose this happens I try to do anything xbps related, but I'm not sure

**Comment by vuksavic** [comment]
...does poppler needs to be updated again?

**Comment by maxice8** [comment]
currently being rebuilt, please be patient.

https://build.voidlinux.eu/waterfall

**Comment by vuksavic** [comment]
Awesomesauce, sorry for the panic.
