### ISSUE TITLE
Restructure dependencies on elogind 

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#20930]
As was agreed when writing the Wayland docs page, elogind is a requirement for a safe wayland session. Therefore, should we make elogind a dependency of the wayland package itself?

Packages like Sway currently have it as a build option, defaulting to a setuid binary instead. Cage, on the other hand, doesn't enable setuid, so it definitely requires elogind (at least in its current state). However, Cage currently doesn't list elogind as a dependency, so if you try to simply install it and run it (without looking at the docs), it will error out due to missing capabilities. Even running as root doesn't work, because then it can't drop privileges properly.

Making elogind a dependency for wayland seems like it would be the best solution for all cases. I would even make a case for an INSTALL message telling the user to enable the service and restart their device (or just log in and out, idk. Whenever I enable elogind I have to reboot for it to work).

Tagging @Duncaen, because you made the case for elogind being a requirement for Wayland.

**Comment by st3r4g** [comment]
It is indeed recommended in https://github.com/swaywm/sway/wiki/Running-Sway-without-systemd
I wouldn't add it to the `wayland` package, but to each compositor individually, because libwayland only requires `XDG_RUNTIME_DIR` to be set (both client and server need to know the socket path).

**Comment by ericonr** [comment]
What other way of setting up `XDG_RUNTIME_DIR` would you suggest? I feel like adding elogind to all the compositors instead of to their common library (which is the part that actually reqiuires `XDG_RUNTIME_DIR`) is duplicated effort. In this case whoever packages another wayland compositor will have to know to add it as a dependency. Just now I realized we'd also have to update Wayfire.

And Wayland also requires privileges for DRM master. Is there any compositor that somehow bypasses this without setuid?If there isn't, elogind is necessary for wayland to be useful, so it should be a dependency.

**Comment by travankor** [comment]
FWIW, the creator of sway does not use elogind (or systemd).

That said, wlroots-based compositors should have consistent behaviour wrt elogind or setuid.

>Cage, on the other hand, doesn't enable setuid, so it definitely requires elogind (at least in its current state).

I think setuid was only recently added to cage.

**Comment by st3r4g** [comment]
> What other way of setting up `XDG_RUNTIME_DIR` would you suggest?
Well, if you want to follow the XDG spec pedantically there is no simple manual way that I know, because iirc it requires login aware stuff like creating the folder at first user login and deleting it after the last log out. But I don't think this actually matters so much for `libwayland`, it's just a way to have a standard path where to put/discover the socket. It's not even a strict `libwayland` requirement, it's just the only convention used in practice. Maybe someone in the future writes a stripped down elogind-like program that only sets `XDG_RUNTIME_DIR`, idk...
> And Wayland also requires privileges for DRM master
You can actually become DRM master without root privileges, if no one is already master (i.e. you launch from console). But then you can't drop master (don't ask me why... DRM API is like this). So technically it's possible to write such Wayland compositor, but it can't do VT switching.

I don't think adding it to each compositor is a lot of duplication, but anyway just my 2 cents let's see other opinions

**Comment by ericonr** [comment]
@travankor at least for the sway package, setting setuid for it is determined by the template. Do you mean that Cage has only recently gained the capability of being setuid? Because the package definitely doesn't set it.

@st3r4g I actually really like the idea of adding elogind as a dependency of wlroots. GNOME and KDE already require elogind, so the only compositor that wouldn't require it is weston, AFAIK. Have you ever used it?

**Comment by st3r4g** [comment]
`weston` on void uses `weston-launch` by default, so a setuid binary. So again the user must set up `XDG_RUNTIME_DIR` in some way. `weston` is meant for testing and not for regular use though.

**Comment by travankor** [comment]
To be more explicit than my previous response, I don't think `wlroots`, a library, should have a runtime dependency on elogind. Implement it on a per-template basis; there only are a handful of wlroots compositors and you can use `xbps-query -RX wlroots` to find all of them.

Furthermore, even though I am currently using elogind, I don't think it's a good solution for several reasons. setuid is not a problem if privs are dropped correctly. The ideal solution would be a much, more lightweight session manager written in a safe language. So, I think an alternative to elogind should be supported in an official capacity by `xbps-src`.

`XDG_RUNTIME_DIR` can be setup like any other environment variable so I don't understand the issue.

**Comment by xtraeme** [comment]
@travankor XDG_RUNTIME_DIR is not just a simple location... elogind does more than just setting this var. Read about it!

**Comment by travankor** [comment]
You can set `XDG_RUNTIME_DIR=/run/user/$USER` in shell and it works. You don't need elogind for this.

**Comment by Duncaen** [comment]
Its not about setting the environment variable, its about creating the directory.

**Comment by st3r4g** [comment]
As I said before, basically the point is that the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) sets specific requirements tied to logins for this folder... but for how it is used by Wayland compositors it doesn't really matter, it just has to exist (with the right perms).

**Comment by ericonr** [comment]
I think discussing this in matters of `XDG_RUNTIME_DIR` won't necessarily lead us anywhere. The most important point for this is the existence or not of setuid binaries.

In order to not break users' setups, elogind could be a (direct or not) dependency of Sway, and then setuid could be removed from Sway's build script (or made a build option at least). The way it currently works, `cage` isn't setuid and requires elogind to run, and `wayfire` even includes an [`INSTALL.msg`](https://github.com/void-linux/void-packages/blob/master/srcpkgs/wayfire/INSTALL.msg) telling the user to install elogind. It doesn't make sense that these packages don't directly depend on elogind.

**Comment by travankor** [comment]
I don't think there is a problem with removing the default setuid.

I made some notes on how to run `wlroots` compsitors without elogind here https://github.com/void-linux/void-docs/pull/195.

I guess people that don't want elogind would have to use
`ignorepkg=elogind` and setuid manually then?

**Comment by travankor** [comment]
Also does the `elogind` service actually work without dbus? My understanding is that elogind is dbus-activated so what's the service file for?

**Comment by ericonr** [comment]
I saw your PR! The one issue I have with it in this context is that if you don't have elogind nor setuid on the binary nor CAP_SYS_ADMIN (capabilities require one more dependency, though), then you can't start the compositor, unless you add setuid by hand.

Making setuid a build option would work out well, I think. Depend on elogind or make the binary setuid. Given that to use a build option you have to build the package yourself, `ignorepkg` shouldn't even be necessary.

I will test elogind without dbus and get back to you.

Finally, I don't know if as a distro we want to push elogind as the solution for most problems. If you guys feel it shouldn't be, I'd advocate then for including the build_option snippet in all the compositors, so they become setuid binaries. I will take a look at PopCorn.voidlinux.org to see if I can figure out how many people use any of the wlroots based compositors and if they have elogind there too.

**Comment by ericonr** [comment]
@travankor it appears elogind usually can be started from the dbus without issue. The reason for enabling its service is that there can be issues derived from it not running when the system was started. It's basically "if you experience an issue with elogind, try to enable it at startup first".

**Comment by travankor** [comment]
@ericonr I created a PR to hopefully resolve this issue. The consus (not sure about this honestly?) seems like they want elogind, so I switched that on by default and made everything available from a build style.

I will update void-docs based on whatever is agreed upon and merged.

**Comment by travankor** [comment]
>it appears elogind usually can be started from the dbus without issue. The reason for enabling its service is that there can be issues derived from it not running when the system was started. It's basically "if you experience an issue with elogind, try to enable it at startup first".

So, do you still need dbus?

This should be documented preferably. Also issues like https://github.com/void-linux/void-packages/issues/20780 should be documented, too.

**Comment by ericonr** [comment]
@travankor from what I understand, you always need dbus. Enabling the elogind service is optional, but it's the best route to be sure stuff works correctly.

**Comment by travankor** [comment]
Discussion in [wlroots](https://github.com/swaywm/wlroots/issues/2232) for removing some setuid parts (potentially all?).

**Comment by st3r4g** [comment]
Interesting. I don't get why they're saying that CAP_SYS_ADMIN is needed for handling input.

**Comment by maxice8** [comment]
If you want to create XDG_RUNTIME_DIR, the creator of Nosh has https://github.com/void-linux/void-packages/blob/master/srcpkgs/pam_rundir/template (which i packaged i believe)

**Comment by ericonr** [comment]
@maxice8 that might have been due to a lack of knowledge regarding how to setup `pam_rundir` (as well as its existence). I can look into adding it to the docs. Thanks for the suggestion!

**Comment by maxice8** [comment]
It should be pretty straightforward, it is a PAM module, you edit /etc/pam.d/login and add it to `session`. [manpage](https://github.com/jjk-jacky/pam_rundir/blob/master/pam_rundir.pod).

It can be quite buggy at times, it used to not work for me in case i had a sudden reboot (like power cut or overheating)

**Comment by travankor** [comment]
https://git.sr.ht/~kennylevinsen/seatd

This was mentioned in IRC, but just posting here for visibility.

**Comment by SevereOverfl0w** [comment]
There's also rundird being worked on which does roughly the same thing as pam_rundir.  I think a package will be incoming for that soon enough too.  Along with seatd, it's plenty to run wayland compositors.

**Comment by st3r4g** [comment]
Now that `wlroots` uses `libseat`, it doesn't make sense to force an elogind dependency anymore. It is up to the user to choose the backend he prefers (elogind or seatd).

**Comment by ericonr** [comment]
I will leave this open to remind myself to check if the docs have all the necessary info.

**Comment by ericonr** [comment]
I'd appreaciate input in https://github.com/void-linux/void-docs/pull/534 . Closing this now.
