### ISSUE TITLE
Package Request: geonkick

### ISSUE THREAD

**Issue by jarbowski** [void-linux/void-packages#20957]
hi,
geonkick is a very good percussion synthesizer available as standalone or as plugin
thanks

https://github.com/geontime/geonkick

**Comment by biopsin** [comment]
Nice find. (Needs GUI toolkit Redkite @ https://github.com/iurie-sw/redkite).
Btw are we not allowed to distribute vst3 plugs, I see none in repo?

**Comment by jarbowski** [comment]
I don't think so, it's not free. The only way to have vst3 support for all would be to pull a nonfree template of vst3sdk (like google-chrome and adobe-flash-plugin) and build it locally with xbps-src, I guess

**Comment by biopsin** [comment]
So we have the option updating all templates, adding a VST build_option in templates, just not enabling it by default? Only missing at this point is a vst3sdk template, ..huhu got my weekend project cut out ;)

**Comment by not-chicken** [comment]
@biopsin You can take templates from here as a starting point. https://github.com/not-chicken/void-packages/tree/kick

**Comment by biopsin** [comment]
@not-chicken; nice, will take a look, tnx
