### ISSUE TITLE
python3-rdflib issue

### ISSUE THREAD

**Issue by jarbowski** [void-linux/void-packages#20956]
Void 4.14.175_1 x86_64 GenuineIntel uptodate rrrmFFFFFF

Byte-compiling python3.8 code for module rdflib...
usr/lib/python3.8/site-packages/rdflib/plugins/memory.py:354: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if triple is None or triple is (None,None,None):
usr/lib/python3.8/site-packages/rdflib/plugins/memory.py:354: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if triple is None or triple is (None,None,None):
Updating ldconfig(8) cache...
python3-rdflib-4.2.2_3: installed successfully.

Thanks

**Comment by Chocimier** [comment]
Please report upstream, there is nothing to do by us.
