### ISSUE TITLE
DVD-Video playback is broken

### ISSUE THREAD

**Issue by VoidDuck** [void-linux/void-packages#20965]
Hello,

I cannot play video DVDs anymore. I have the same problem on two different machines, one running Xfce, the other running Plasma, and two different video players (VLC and Parole). The player crashes everytime I try to play the disc.

Parole output:
`libdvdnav: *** pgci_ut handle is NULL ***`
`Segmentation fault`

VLC output:
`[00007fb22c001120] dvdnav demux error: *** pgci_ut handle is NULL ***`
`Segmentation fault`

* xuname:  
  *Void 5.4.31_1 x86_64 GenuineIntel uptodate rF*
* package:  
  *libdvdnav-6.1.0_1*

**Comment by jarbowski** [comment]
same here
downgrade to libdvdread-6.0.2 for the moment
libdvdread-6.1.1 may fix this

**Comment by Hoshpak** [comment]
The changelog suggests it. The package has been updated. Please check if the issue is resolved for you after updating the packages.

**Comment by jarbowski** [comment]
everything is okay now

**Comment by VoidDuck** [comment]
It works fine indeed. Thank you for updating.
