### ISSUE TITLE
Package Request: stk

### ISSUE THREAD

**Issue by jarbowski** [void-linux/void-packages#20970]
hi,
this is an audio synthesis toolKit written in c++
optionally required by lmms (add some instruments), csound and sc3-plugins
thanks

https://github.com/thestk/stk

**Comment by pullmoll** [comment]
There you go.

**Comment by jarbowski** [comment]
thank you very much
but to be effective, lmms, csound and sc3-plugins have to be edited (certainly libstk-devel in makedepends) and rebuild

**Comment by pullmoll** [comment]
Hmm.. I'm working on getting i686 built and thinking about what to do with the `./rawwaves` data. Probably add them to a `stk-data` subpackage with `archs=noarch`.

**Comment by pullmoll** [comment]
`lmms` and `csound` are done, but `sc3-plugins` is using git clone and it's a little messy :-)
I'm trying to fetch the package all submodules as distfiles, moving them to where they are expected. Only `nova-tt` is not (yet) found. Perhaps I need to add the `supercollider` package itself and put `nova-tt` in that package's `external_libraries`.

**Comment by pullmoll** [comment]
Done.

**Comment by jarbowski** [comment]
lmms complaigns about stk. attempts to find rawwaves dir in  /usr/share/stk/rawwaves like in arch's pkgbuild
better than a stk-data subpackage?
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/stk

**Comment by jarbowski** [comment]
@pullmoll 
so stk-data should be a lmms dependency? or an INSTALL file in lmms installation to warn about stk-data and to keep it really optionnal?

**Comment by pullmoll** [comment]
I also realized this now. Will push yet another update soon.
