### ISSUE TITLE
Package request: gh

### ISSUE THREAD

**Issue by gbrlsnchs** [void-linux/void-packages#20987]
It would be nice to have the [official GitHub CLI](https://github.com/cli/cli) in the repos. :smiley_cat: 

I'll try to open a pull request whenever I have time, but if someone wants to do it first, it'll be awesome.

Thanks for the hard work everybody.

**Comment by xtraeme** [comment]
```
[juan@leysa void-packages]$ xbps-query -R github-cli
architecture: x86_64-musl
changelog: https://github.com/cli/cli/releases
filename-sha256: a5ed7bc2e2c7b7e2bc895bef47b8ec8b7b19f555cfe0b902a06fd7397c80e167
filename-size: 8547KB
homepage: https://cli.github.com
installed_size: 20MB
license: MIT
maintainer: shizonic <realtiaz@gmail.com>
pkgname: github-cli
pkgver: github-cli-0.6.4_1
repository: /mnt/storage/hostdir/binpkgs
run_depends:
	musl>=1.1.21_1
shlib-requires:
	libc.so
short_desc: GitHub CLI tool
source-revisions: github-cli:0c14b6f9b7
[juan@leysa void-packages]$
```

**Comment by gbrlsnchs** [comment]
Wow, my bad, really. I might have seen it the first time I searched but didn't think it was the official, since the description don't say so.

@xtraeme Maybe the description should be changed. It's a minor detail, but helps identifying it as the official tool. I might do it when I have free time. Thanks again!

**Comment by xtraeme** [comment]
```
$ xbps-query -Rs cli.github.com -p homepage
github-cli-0.6.4_1: https://cli.github.com (/mnt/storage/hostdir/binpkgs)
$
```
There's nothing to improve here, use xbps-query(1) features!

**Comment by gbrlsnchs** [comment]
@xtraeme Yeah, I still have a lot to learn from Void tools. Thank you very much!
