### ISSUE TITLE
binpkg is being created, waiting for 1s...

### ISSUE THREAD

**Issue by svenper** [void-linux/void-packages#21020]
Inspired by [#2368](https://github.com/void-linux/void-packages/issues/2368#issuecomment-553584051)

### System

* xuname:  
  Void 5.4.32_1 x86_64-musl GenuineIntel uptodate hold rrnFFFFFFFFF
* package:  
  texlive2020-exec [[WIP]](https://github.com/svenper/void-packages/blob/texlive/srcpkgs/texlive2020-exec/template) (which package should be irrelevant but repro timing is hard)

### Expected behavior

The dviout-util subpkg packages just like the others. `.lock` files are reset when repackaging.

### Actual behavior

```text
=> WARNING: texlive2020-exec-dviout-util-2020.0_1: binpkg is being created, waiting for 1s...
=> WARNING: texlive2020-exec-dviout-util-2020.0_1: binpkg is being created, waiting for 1s...
=> WARNING: texlive2020-exec-dviout-util-2020.0_1: binpkg is being created, waiting for 1s...
...
```

```text
$ ls -lA srcpkgs/texlive2020-exec-dviout-util
lrwxrwxrwx 1 $USER $USER 16 2020-04-15 07:13 srcpkgs/texlive2020-exec-dviout-util -> texlive2020-exec
```
```text
$ file masterdir.*/upperdir/destdir/texlive2020-exec-dviout-util-2020.0/opt/texlive/2020/bin/xbps/*
masterdir.XXXXOjegIa/upperdir/destdir/texlive2020-exec-dviout-util-2020.0/opt/texlive/2020/bin/xbps/chkdvifont: ELF 64-bit LSB shared object, x86-64, version 1
(SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, BuildID[sha1]=90500c98f88a4080a71af02d436761b77333fec3, stripped
masterdir.XXXXOjegIa/upperdir/destdir/texlive2020-exec-dviout-util-2020.0/opt/texlive/2020/bin/xbps/dvispc:     ELF 64-bit LSB shared object, x86-64, version 1
(SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, BuildID[sha1]=9149d0fb093ea6de295d49249568a7a422b98551, stripped
```

There was a `.lock` file from previous build cancelled midway through packaging. Removing it fixed the problem.

```text
rm /var/cache/xbps-src/binpkgs/texlive/texlive2020-exec-dviout-util-2020.0_1.x86_64-musl.xbps.lock
```

### Steps to reproduce the behavior

Package a package, but cancel it while packaging. Then package again.
```text
./xbps-src -H /var/cache/xbps-src pkg -t -f texlive2020-exec
```

**Comment by abenson** [comment]
The .lock file is created when packaging. If you interrupted it at some point (ctrl-c), the lock file remains. I'm not sure there's a way to clean up the .lock file (maybe a trap of some sort?).

**Comment by Noah-Huppert** [comment]
Proposing this change: https://github.com/void-linux/void-packages/pull/24191. It traps and removes the lock file.

**Comment by ericonr** [comment]
Closing in a commit missed the hook.

Thanks noah :)
