### ISSUE TITLE
GNU make-4.2 has issues with musl (glob)

### ISSUE THREAD

**Issue by xtraeme** [void-linux/void-packages#21089]
If any of you have noticed why linux5* builds are so slow with musl currently it's due to GNU make when it was downgraded to 4.2.

This version contains an obsolete glob implementation that is used by default with musl (see configure) that makes building linux5* with -jX not parallelize jobs as it should.

Try with current void make (4.2.x) `./xbps-src -jX linux5.6` and then compare with make 4.3.

Fix: update GNU glob implementation for 4.2 or update again to 4.3.

Your choice! I don't really care because I've fixed this on my tree...

**Comment by pullmoll** [comment]
Well, I do care because when building many thousand *-musl packages here it makes a difference :)
Can you confirm the make-4.3 fnmatch and glob injection helps? It seems so to me because when I build e.g. `linux5.6-5.6.5` for `x86_64-musl` in a `x86_64-musl` chroot it really uses 30 threads.

**Comment by travankor** [comment]
@xtraeme @pullmoll Appreciate the work you both do!

Thank you, jefe 👍

**Comment by xtraeme** [comment]
@pullmoll wouldn't be better to update make to 4.3 and fix the issues with those two pkgs instead?

**Comment by pullmoll** [comment]
If anyone wants to do that, i.e. fix Aegisub and openjdk9-bootstrap with make-4.3, sure.
This PR is meant as a workaround in case no one cares - /me has sufficient other things on the list.

**Comment by Gottox** [comment]
Is there a minimized testcase for that? I'm currently on LTE only, so I'd really like to avoid traffic intensive builds :D

**Comment by xtraeme** [comment]
We don't know yet, but the only thing to trigger it is with linux5.x. I think linux4.x is not affected. I couldn't investigate what's the real reason.

**Comment by q66** [comment]
you can't "fix the issues with these two pkgs" as this is literally a regression in make, a bug.

**Comment by xtraeme** [comment]
right, but rather than downgrading why do not fix the issues?

**Comment by q66** [comment]
feel free to
