### ISSUE TITLE
System freezez after coming out of suspend...

### ISSUE THREAD

**Issue by MirceaMx** [void-linux/void-packages#2114]
### System
Void-Linux with KDE Plasma runing on Lenovo laptop G50-70 (Intel i3, 4GB RAM, Intel...everything -GPU, WiFi)
* xuname:  
dmesg: read kernel buffer failed: Operation not permitted
Void 4.17.17_1 x86_64 GenuineIntel notuptodate rrDDFF

  *output of ``xuname`` (part of xtools)*
dmesg: read kernel buffer failed: Operation not permitted
Void 4.17.17_1 x86_64 GenuineIntel notuptodate rrDDFF

### Expected behavior
System should come out of suspend

### Actual behavior
System completely freezes after coming out of suspend. Have to hold the power button 5 sec to reboot 

### Steps to reproduce the behavior
Suspend

**Comment by Hoshpak** [comment]
linux4.18 is also available in the repository, just not the default kernel yet. Could you install it and try if it changes the situation?

**Comment by MirceaMx** [comment]
Can't install it/test. (see screenshot)
![linux4 18error](https://user-images.githubusercontent.com/40819799/44622934-77690980-a8cb-11e8-9e22-8c07f02957eb.png)

**Comment by Hoshpak** [comment]
please try `xbps-install -S linux4.18` as root on the command line. I wouldn't trust octoxbps with things like this.

**Comment by MirceaMx** [comment]
Screenshot attached:

![image](https://user-images.githubusercontent.com/40819799/44622975-34f3fc80-a8cc-11e8-9f9e-eed70e3b7ef3.png)

**Comment by Hoshpak** [comment]
Theoretically, these libs are consistent in the repository. I have no issues with these on my systems. Does `xbps-install -Su` produce the same error?

**Comment by MirceaMx** [comment]
Yes it does. Going to try something to fix it. BTW I just woke up my system from suspend. And it froze. So I put my system on suspend and kept it like that for 2 hours then I woke it and all went fine. Then I put it again on suspend for several hours, woke it and...it froze.

**Comment by MirceaMx** [comment]
Yes it does. Going to try something to fix it. BTW I just woke up my system from suspend. And it froze. So I put my system on suspend and kept it like that for 2 hours then I woke it and all went fine. Then I put it again on suspend for several hours, woke it and...it froze.

**Comment by MirceaMx** [comment]
Solved the errors by reinstalling 'dmraid' since the error was raid related. I don't think it's kernel related. And how can I test / reproduce it if it happens randomly!? In any case, upgraded the kernel (4.17) several times and every time the issue was still there...

**Comment by MirceaMx** [comment]
Solved the errors by reinstalling 'dmraid' since the error was raid related. I don't think it's kernel related. And how can I test / reproduce it if it happens randomly!? In any case, upgraded the kernel (4.17) several times and every time the issue was still there...

**Comment by MirceaMx** [comment]
xuname:
Void 4.18.5_1 x86_64 GenuineIntel uptodate rrDDFF

**Comment by MirceaMx** [comment]
Seems to work fine with kernel 4.18 .
