### ISSUE TITLE
cutter: it's not built with any decompiler unlike the official AppImage package

### ISSUE THREAD

**Issue by howtologinquickwiththirtyninecharacters** [void-linux/void-packages#21159]
### System

* xuname:  
  *Void 5.4.33_2 x86_64 GenuineIntel uptodate rrFFFFFF*
* package:  
  *cutter-1.10.2_2*

### Expected behavior

Cutter has at least one decompiler in the dropdown menu (this is the default behavior of the official releases, you can get the AppImage to test that from [here](https://github.com/radareorg/cutter/releases))

### Actual behavior

The decompiler dropdown is disabled and displays no options.

### Steps to reproduce the behavior

1. Install `cutter`
2. Run it (the executable is called `Cutter` with an uppercase C)
3. Select any file (let's use `/bin/cat` as an example)
4. Click Open
5. Click Ok on the analysis screen
6. Select the Decompiler tab on the bottom (if it is not visible click on the Windows menu and enable it)
7. Confirm that the Decompiler dropdown menu on the bottom right is empty (the official AppImage display Ghidra as the default decompiler)

**Comment by ericonr** [comment]
@jnbr take a look at https://cutter.re/docs/building.html#cmake-building-options

You will need to pull the submodules into the build, it seems.

**Comment by jnbr** [comment]
Thanks. I will take a look at it at the weekend, so if you need it urgently, feel free to give it a go.

**Comment by ericonr** [comment]
@howtologinquickwiththirtyninecharacters do you have `ghidra` installed on your system? A system package doesn't have to contain the same things an appimage does, because we can choose to install, or not, `ghidra` from the repos. Let me know if you can use it from there c:

@jnbr pretty sure my link was wrong, their issue is something else.

**Comment by jnbr** [comment]
Even if it's possible to install ghidra, a plugin would still be needed to use it from inside cutter.
After looking at how this plugin would have to be built, I decided not to package it, anyone feel free to give it a try.

**Comment by howtologinquickwiththirtyninecharacters** [comment]
@ericonr I'm sorry for replying so late, I missed the email notification. I don't have it installed but I can install it if necessary.
