### ISSUE TITLE
alacritty: Missing dependency libXi

### ISSUE THREAD

**Issue by kaistian** [void-linux/void-packages#21158]
### System

* xuname:  
  Void 5.4.13_1 x86_64 GenuineIntel uptodate rFF
* package:  
  alacritty-0.4.2_2

### Expected behavior

Alacritty to start

### Actual behavior
```
$ alacritty
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libXi.so.6: cannot open shared object file: No such file or directory); opening library failed (libXi.so: cannot open shared object file: No such file or directory)" })', /host/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.0/src/platform_impl/linux/mod.rs:569:9
```
### Steps to reproduce the behavior

1. Install `xorg-minimal` and `alacritty`
2. Try to start alacritty

### Fix

Installing `libXi` and Alacritty starts.

**Comment by jnbr** [comment]
Thank you for reporting the issue, it is fixed now, `alacritty-0.4.2_3` depends on `libXi`.

**Comment by unifxfoe** [comment]
How did you download the libXi dependency?

**Comment by ericonr** [comment]
@unifxfoe it's a package, simply `libXi`.
