### ISSUE TITLE
m4, texinfo build failure

### ISSUE THREAD

**Issue by fosslinux** [void-linux/void-packages#21163]
### System

* xuname:  Void 5.6.3_1 x86_64 GenuineIntel uptodate rrFFF

* package:  
m4-1.4.18, texinfo-6.7

### Expected behavior

`m4` builds correctly.

### Actual behavior

`m4` fails with:

```
make[2]: Entering directory '/builddir/m4-1.4.18/doc'
  MAKEINFO m4.info
/builddir/m4-1.4.18/build-aux/missing: line 81: makeinfo: command not found
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
         You might want to install the Texinfo package:
         <http://www.gnu.org/software/texinfo/>
         The spurious makeinfo call might also be the consequence of
         using a buggy 'make' (AIX, DU, IRIX), in which case you might
         want to install GNU make:
         <http://www.gnu.org/software/make/>
make[2]: *** [Makefile:1535: m4.info] Error 127
make[2]: Leaving directory '/builddir/m4-1.4.18/doc'
make[1]: *** [Makefile:1572: install-recursive] Error 1
make[1]: Leaving directory '/builddir/m4-1.4.18'
make: *** [Makefile:1867: install] Error 2
```

Adding texinfo to hostmakedepends results in:

```
Making install in doc
make[2]: Entering directory '/builddir/m4-1.4.18/doc'
  MAKEINFO m4.info
utf8 "\xAB" does not map to Unicode at /usr/share/texinfo/Texinfo/ParserNonXS.pm line 1796, <FH> line 4254.
utf8 "\xAB" does not map to Unicode at /usr/share/texinfo/Texinfo/ParserNonXS.pm line 1796, <FH> line 4255.
Malformed UTF-8 character (fatal) at /usr/share/texinfo/Texinfo/ParserNonXS.pm line 3531.
```

### Steps to reproduce the behavior

clone void-packages.

`./xbps-src -N pkg m4` or revbump texinfo and m4 and `./xbps-src pkg m4`.

**Comment by rovenmacorp** [comment]
This error exists because `texinfo` is not added to the package definition as a build dependency. You will also get a second error when you add it. And this is because `texinfo`'s input encoding now UTF-8 by default and `m4.texi`'s not. You can solve this problem add `pre_build` section like this.

`pre_build() {
     sed -i '1 i @documentencoding ISO-8859-1' doc/m4.texi
}`

See at: [https://github.com/dankelley/gri/issues/15#issuecomment-544980426](url)

**Comment by fosslinux** [comment]
Well, the texinfo thing - since m4 is a bootstrap package, texinfo is meant to be on the host system. I guess that was just a problem with my setup.

That seems like it will work - I'll add that to the template and  PR. Thanks! I'll close this issue when the PR is merged.

**Comment by fosslinux** [comment]
Thought it was fixed, apparently not.... need to find a way to disable it for the bootstrap.

**Comment by LostGhost1** [comment]
One "fix" would be removing doc, tests and checks from the list of directories that Make recursively visits. To do so, they would need to be removed from the file Makefile.in at line 1509.

**Comment by sgn** [comment]
Yeah, this is not fixed.

**Comment by sgn** [comment]
Fixed https://github.com/void-linux/void-packages/commit/66bf185310ef656f05f8b9c24fb58470e8f27a8f
