### ISSUE TITLE
dhcpcd connection refused

### ISSUE THREAD

**Issue by LamaRaz** [void-linux/void-packages#21234]
in addition to the apparmor issues the recent update also seems to break it in a tty logged in as root

`ps_dostop: Connection refused`

downgrading this crap fixed the problem

was only able to find a single reference to my problem by someone else: https://bbs.archlinux.org/viewtopic.php?id=254935

**Comment by Vaelatern** [comment]
this is with apparmor installed?

**Comment by LamaRaz** [comment]
no apparmor, it's a fresh system with nothing but lvm2 and crypsetup with efi

**Comment by LamaRaz** [comment]
does not seem to be related to root
same problem with a normal user

first 'ip a' shows no ip for wlan0 despite /var/service/dhcpcd-wlan0

then sudo dhcpcd wlan0 shows the connection refused

**Comment by LamaRaz** [comment]
solution:

`dhcpcd -4`

from https://bbs.archlinux.org/viewtopic.php?id=254888

confirmed as working for me

**Comment by Vaelatern** [comment]
it disables ipv6

**Comment by Piraty** [comment]
i start my systems with `cmdline= ... ipv6.disable=1` and had to add `ipv4only` to /etc/dhcpcd.conf, else it crashed after getting a lease from the router

**Comment by xtraeme** [comment]
try dhcpcd-9.0.2

**Comment by Piraty** [comment]
clearly an upstream issue

**Comment by ErinVoid** [comment]
Have been having random dhcpcd issues on a standard-ish x64 musl install. Works one minute, not the next. Added noarp to dhcpcd.conf and the issue disappeared at the same time but cannot validate it was specifically that.

**Comment by Piraty** [comment]
i can confirm that dhcpcd-9.0.2 solves it. it no longer requires `ipv4only` in the conf file to work.

probably https://github.com/rsmarples/dhcpcd/commit/717e0411669be2f39460c7fb3952f55024883485
