### ISSUE TITLE
Manual.md: Add list of packages that should be rebuilt after bootstrap.

### ISSUE THREAD

**Issue by fosslinux** [void-linux/void-packages#21232]
From https://github.com/void-linux/void-packages/pull/21226, there was a longish discussion about the entire bootstrap process.

As a newbie to `./xbps-src bootstrap`, I did not know that you should be rebuilding packages after `./xbps-src bootstrap`. @pullmoll suggested " We should put up a list of packages which need to be rebuilt after a bootstrap, probably in the Manual.md section about bootstrapping."

I agree with this. I have no idea what these packages are however...

cc/ @pullmoll @xtraeme

**Comment by pullmoll** [comment]
The easiest and safest way actually is to rebuild the entire chroot. This ensures that nothing is missed which could potentially go wrong with packages being built with different options in case the chroot is not yet ready.

That is, after `./xbps-src bootstrap` is done and you have a bootstrapped chroot ready in your `masterdir`, remove all packages that were created (I think `rm -rf masterdir/binpkgs/*` or whererever you defined the masterdir with the `-m` option) and build `base-chroot` with your bootstrapped environment:
`./xbps-src -N pkg base-chroot`.

After this is done, you can then `./xbps-src binary-bootstrap` and everything should work as expected.
Also only after this step you should try to cross build `base-chroot` for other architectures like:
`./xbps-src -a i686 -N pkg base-chroot`.

**Comment by pullmoll** [comment]
The bootstrap process details should perhaps be described in a `void-docs` section for developers.
I think `Manual.md` is not the right place to go into such detail thus closing this issue.
