### ISSUE TITLE
Firefox directory list views broken by multiprocess setting or dconf

### ISSUE THREAD

**Issue by svenper** [void-linux/void-packages#21245]
(split off from #12885 since the separate password field bug was fixed)

# System

* xuname:  
  Void 5.4.33_2 x86_64-musl GenuineIntel uptodate hold rrnFFFFFFFFF
* package:  
  firefox-75.0_1

### Expected behavior

directory list views are not broken by dconf or browser.tabs.remote.autostart

### Actual behavior

directory list views are broken by dconf or browser.tabs.remote.autostart

### Steps to reproduce the behavior

1. uninstall dconf
2. restart firefox and navigate to `file:///` or `ftp://*` (e.g. ftp://ftp.fr.debian.org/)
3. install dconf
4. 2\.
5. disable browser.tabs.remote.autostart in about:config
6. 2\.

**Comment by jnbr** [comment]
I can reproduce the crash with `file:///` crashing.

**Comment by jnbr** [comment]
In my case, the problem is due to the sandbox not allowing / crashing on `SYS_fork`.
You can test if it's the same for you by setting `security.sandbox.content.syscall_whitelist` in `about:config` to `57`.

**Comment by svenper** [comment]
Same here! :detective:

**Comment by jnbr** [comment]
Ok, thanks for testing. I'll prepare a proper fix.
