### ISSUE TITLE
variable substitution in depends for subpkg

### ISSUE THREAD

**Issue by svenper** [void-linux/void-packages#21252]
### System

* xuname:  
  Void 5.4.33_2 x86_64-musl GenuineIntel uptodate hold rrnFFFFFFFFFF
* package:  
  python-hyper-h2-3.1.1_2

### Expected behavior

variable substitution works in subpkg depends

### Actual behavior

variable substitution in subpkg depends results in empty depends 

### Steps to reproduce the behavior

(should probably be double slash `${depends//...` for global replace but that's irrelevant for this issue)

```text
$ grep -E '\bdepends=' srcpkgs/python3-hyper-h2/template
depends="python python-hpack python-hyperframe"
        depends="${depends/python/python3}"
$ xbps-query -Rx python3-hyper-h2
$
```

**Comment by Chocimier** [comment]
Interesting that depends, unlike short_desc is unset here, but I would change template rather than xbps-src because it's bad for searchability of python3-* usage.

Also this seems to be only template doing this.
