### ISSUE TITLE
MISSING: clang-32bit>=9.0.0_1

### ISSUE THREAD

**Issue by sburris0** [void-linux/void-packages#21285]
### System

* xuname:  

> MISSING: clang-32bit>=9.0.0_1
> Transaction aborted due to unresolved dependencies.
> Void 5.4.33_2 x86_64 AuthenticAMD uptodate rrrmFFFF

* package:  
  *affected package(s) including the version*
clang-32bit>=9.0.0_1

When I try to update my system with `# xbps-install -Su`, the transaction is blocked by clang-32bit.
> MISSING: clang-32bit>=9.0.0_1
> Transaction aborted due to unresolved dependencies.

I can't see any reference to clang-32bit in this repository or in a reverse dependency search with `xbps-query -X clang-32bit`, or `xbps-query -Rs clang-32bit`. Force reinstalling clang didn't help.

**Comment by abenson** [comment]
I had to remove `mesa-opencl-32bit`. It looks at some point that lib32 was disabled for clang.

**Comment by sburris0** [comment]
Works for me.

**Comment by abenson** [comment]
Not sure why `mesa-opencl-32bit` exists... Note, the xbps-query weren't working because the package doesn't exist. I'm confused as to why it suddenly stopped working, because it should've never worked.
