### ISSUE TITLE
Organization requirements

### ISSUE THREAD

**Issue by xtraeme** [void-linux/void-packages#21299]
I think the current state of void related to who decides what to push or not is a tragedy. This needs to be improved for the sake of us and all users.

I really think that before someone pushes a change there need to be some requirements:

- For package updates being updated by the current maintainer, no review necessary.
- For package updates without soname bumps, at least get the change reviewed by 2 people.
- For new packages at least get change reviewed by 2 people.
- For package updates with soname bumps, at least get the changes reviewed by 5 people.
- For xbps-src changes, at least get the changes reviewed by 5 people.
- For reverts, at least get the ok from 5 people.

Otherwise this is just anarchy...

@void-linux/pkg-committers

**Comment by xtraeme** [comment]
myself included! as long as EVERYBODY respect the same rules!

**Comment by Duncaen** [comment]
I think if we could come up with a list or a rule for packages that are "high maintenance", getting multiple OKs is a good idea, for most packages I think getting 3 OKs is just going to get 

3 or 5 OKs are required if the package...
* ... is part of base-system.
* ... is a core component of desktop environments.
* ... has over N reverse dependencies.

**Comment by xtraeme** [comment]
I like you suggestion @Duncaen 

Maybe we can relax simple changes to 2 OKs

**Comment by xtraeme** [comment]
That means no unverified pushes without reviews, this includes @thypon @Vaelatern (among others).

**Comment by leahneukirchen** [comment]
If I can't bump my own packages, I'm out. I have enough bureaucracy in my life.

**Comment by xtraeme** [comment]
@leahneukirchen I agree. I think we should add:

- maintainers are free to push anything related to the pkgs they maintain

**Comment by xtraeme** [comment]
@leahneukirchen this is just a proposal! when everybody agrees to the terms we can make it effective.

**Comment by xtraeme** [comment]
I have relaxed the requirements.

**Comment by leahneukirchen** [comment]
I think I would prefer a per-package/subsystem CODEOWNERS approach to get explicit approval.

**Comment by xtraeme** [comment]
So at least get OK from current pkg maintainer or codeowner (if applicable) ?

**Comment by xtraeme** [comment]
I also think that there are lots of packages with maintainer that do not maintain them! this means if maintainer does not answer in 1 week, submitter can be the current maintainer.

**Comment by xtraeme** [comment]
This is what FreeBSD/ports does and I think it's good.

**Comment by sgn** [comment]
- I'm OK with the relaxing for non-critical package
- I think those packages in bootstrap list or the one that have equivalent in bootstrap should be reviewed by more people. E.g: I don't want to push nss, git out when noone else tested it. If that package was written by that maintainer, it's a different story.
- For the security update, I don't think we should wait. Fast track is OK to me.
- If the package is causing broken in buildbot, I expect someone fast-track either a fix, revert (with at least some testing) or make it broken.

**Comment by sgn** [comment]
Does github have something to notify if a comment or post was modified?
I didn't see the change in OP, at first. I mostly look into my mailbox.

**Comment by xtraeme** [comment]
@sgn I think it doesn't.

**Comment by xtraeme** [comment]
@void-linux/pkg-committers please speak up. We can get a consensus when all committers agree to the terms.

**Comment by xtraeme** [comment]
I agree with @sgn comments

**Comment by xtraeme** [comment]
When the consensus is agreed by all committers I'll create a new file explaining the rules.

**Comment by pullmoll** [comment]
I though Void Linux was the primary example for (working) anarchy, no? :-P

Anyway, I don't think we need 2 reviews for new packages. As long as a new package doesn't conflict with existing packages (no name clash) and does not conflict or want to provide alternatives, a contributor should be free to add it. This has been helpful when preparing other new packages which require not yet existing dependencies (libraries, compilers, ...).

If a new package contains `conflicts=` or `alternatives=` it should be reviewed.

Other than that I also agree with @sgn.

**Comment by xtraeme** [comment]
ok, I agree with @pullmoll

**Comment by Vaelatern** [comment]
I only agree to restrictions on the bootstrap set. Everything else is just additional rules for the sake of rules.

**Comment by xtraeme** [comment]
ok, let's continue with more opinions.

**Comment by q66** [comment]
I don't think we need a new set of rules. How about fixing your own problems before implying there are issues with the system first?

**Comment by xtraeme** [comment]
My issues are mine. This is not about my issues, it's about issues related to this organization that I started.

**Comment by xtraeme** [comment]
The same organization that people think I'm not able to comment! if I didn't start it you weren't commenting it... so let's relax.

**Comment by Anachron** [comment]
I hope it's ok if I join the discussion.
As a Contributor for nearly two years now I want to give my 2 cents to this topic.

1.) I don't think it's beneficial for anybody to get personal here. 
2.) I don't see how being a code owner/organization starter gives the permission to push things the Community/other Maintainers are not OK with. This is just provoking issues along the road.
3.) Enforcing new rules may be a direction to go here, as long as all maintainers and contributors are in the same boat. Else we end up loosing useful resources which is quite contra-productive.
4.) As far as I can tell the issue is just becoming bigger because you, @xtraeme, disagree how things are handled?
5.) Last but not least, don't [become insulting](https://github.com/void-linux/xbps/issues/275#issuecomment-619071620). Please keep the discussion to a civilized tone.

**Comment by xtraeme** [comment]
let's continue with your stupid rules, I don't give a fuck

**Comment by Anachron** [comment]
@xtraeme please cool down and come back once you have a clear picture of whats happening. Your treatment of other contributors is in no regard ok. 

Void is your idea, we get it. But that doesnt change that everybody should be treated fair and respectful.

**Comment by Mothrakk** [comment]
@xtraeme don't let these trannies tell you what to do, it's your project, if they don't like it they can fuck off or fork it

**Comment by rugalash** [comment]
All of you dweebs should calm down and just go about your business, stop obsessing over how and why others do what they do.

**Comment by the-maldridge** [comment]
Aaand locked to contributors.
