### ISSUE TITLE
No man page for picom

### ISSUE THREAD

**Issue by MrLazerbean** [void-linux/void-packages#21294]
### System

* xuname:  
  Void 5.4.34_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFFF
* package:  
  picom-8_1
### Expected behavior
`man picom` opens the man page for picom
### Actual behavior
`man picom` returns an error "No entry for picom found in the manual"
### Steps to reproduce the behavior
Install picom
Run `man picom`

**Comment by not-chicken** [comment]
Will be fixed by #21257

**Comment by sgn** [comment]
Fixed by #21257
