### ISSUE TITLE
kdeconnect-related MIME error

### ISSUE THREAD

**Issue by emacsomancer** [void-linux/void-packages#21311]
### System

* xuname:  
  *Void 5.6.7_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFFFFFFF*
* package:  
  *kdeconnect-20.04.0_1*

### Expected behavior
no errors messages
### Actual behavior
Every update of the MIME database generates a complaint:

`Error in file "usr/share/applications/org.kde.kdeconnect_open.desktop": "*/*" is an invalid MIME type ("*" is an unregistered media type)`

### Steps to reproduce the behavior
install `kdeconnect`, update system.

**Comment by Anonymo** [comment]
I get this but on Fedora when installing Teamviewer.

**Comment by moonlitht** [comment]
> I get this but on Fedora when installing Teamviewer.

me too 
you have soloved it ？

**Comment by emacsomancer** [comment]
@moonlitht For kdeconnect, it was solved by https://github.com/void-linux/void-packages/commit/17060bfa012b12896d3d7ec502caa154af6135b4 (which properly specifies Mimetype). I suspect teamviewer needs a similar change.

**Comment by imbezol** [comment]
I see this when trying to update Zoom on Ubuntu as well.
sudo dpkg -i zoom_amd64.deb 
(Reading database ... 374036 files and directories currently installed.)
Preparing to unpack zoom_amd64.deb ...
Unpacking zoom (5.0.413237.0524) over (5.0.413237.0524) ...
run post uninstall script, action is upgrade ...
Setting up zoom (5.0.413237.0524) ...
run post install script, action is configure...
Error in file "/usr/share/applications/org.kde.kdeconnect_open.desktop": "*/*" is an invalid MIME type ("*" is an unregistered media type)

**Comment by Johnnynator** [comment]
This is not support for Ubuntu/Fedora/whatever distro you are running. Report such issues with the Distribution you are using.
