### ISSUE TITLE
XBPS install of openjdk fails

### ISSUE THREAD

**Issue by Mirodin** [void-linux/void-packages#2133]
### System

* system:
  *LXQT version
  *kernel: 4.17.19_1
* package:  
  *openjdk-jre 8u182b00_1

### Expected behavior
Install succeeds.

### Actual behavior
Installation of openjdk works fine but it seems to create an empty `bin` inside `usr/lib/jvm/openjdk` which causes openjdk-jre installattion to fail:

```
ERROR: openjdk-jre-8u182b00_1: [unpack] failed to extract file `./usr/lib/jvm/openjdk': Directory not empty
ERROR: openjdk-jre-8u182b00_1: [unpack] failed to extract files: Directory not empty
ERROR: openjdk-jre-8u182b00_1: [unpack] failed to unpack files from archive: Directory not empty

```

### Steps to reproduce the behavior

1. Fresh install of void lxqt version
2. Run `xbps-install -uS` and restart to get up to date
3. Run `xbps-install -S openjdk openjdk-jre`

**Comment by ruegerjr** [comment]
Interesting. 
xbps-install openjdk                           (succeeds, installs openjdk-jre as dependency)
xbps-install openjdk-jre openjdk        (succeeds)
xbps-install openjdk openjdk-jre        (fails)

It appears in the last case that openjdk installation initially creates "/usr/lib/jvm/openjdk" directory BEFORE openjdk-jre has a chance to be extracted. 

For now, you may try (as root):
xbps-remove -RvyF openjdk openjdk-jre
rm -r /usr/lib/jvm
xbps-install  openjdk

This should install openjdk-jre successfully as well

**Comment by Mirodin** [comment]
I already solved this for me by `sudo rmdir /usr/lib/jvm/openjdk/bin` which succeeds since the directory is empty. Afterwards installation of openjdk-jre works fine. Just opened the issue since it seems to be a bug/misconfiguration of openjdk.

**Comment by obunden** [comment]
There doesn't seem to be any issues with the current version of openjdk that I can see. Has anyone else been able to reproduce this? Think we would've recieved a lot more reports about this if it was still wide spread.

**Comment by Mirodin** [comment]
I am not on my machine and do not use any Java applications right now so I can not comment if this still persists.

**Comment by Byebyesky** [comment]
I've been able to reproduce this on my new void linux install just today.
I installed void linux, updated with ``xbps-install -Su`` and went on installing a few things. Then I installed openjdk and jre with this command: ``sudo xbps-install -S openjdk openjdk-jre`` which caused the above error.
Cinnamon version with kernel 4.18.17_1

**Comment by xtraeme** [comment]
This should be fixed already, please reopen if the issue still exists.
