### ISSUE TITLE
Update pipewire to 3.2

### ISSUE THREAD

**Issue by SamHSmith** [void-linux/void-packages#21352]
Hi I have been trying to update all the gnome packages to 3.36 and so far it has been going okay. I did hit a snag when needing to bump pipewire to 3.2. I don't have the xbps-src knowlage to properly do it so I was wondering if someone else could update it for me? Once it has been updated I can help contribute to updating gnome packages.

**Comment by toluschr** [comment]
I've been doing the same, but for me `gnome-session` doesn't start because of some gsettings error. Could you send me your template files?

**Comment by SamHSmith** [comment]
@toluschr There's no point in me sending my template files since I never got it to build. I followed the dependency chain and got stuck on pipewire. The template file is quite complicated since pipewire provides alsa, pulseaudio and jack .so files for applications to link to. And on top of that 3.0 saw the addition of a central server that I think needs additional setup.

I would be happy to take over maintainership of pipewire. Maybe @maxice8 could onboard me?

**Comment by not-chicken** [comment]
It is currently blocked by xdg-desktop-portal #20413, and the previous maintainer has moved on to another distribution.

**Comment by maxice8** [comment]
@SamHSmith I am no longer in Void Linux

**Comment by SamHSmith** [comment]
@not-chicken Fantastic. I will wait for that then before doing the gnome stuff.
