### ISSUE TITLE
linux5.6 unavailable on i686

### ISSUE THREAD

**Issue by mithodin** [void-linux/void-packages#21369]
5.6 has been available on x86_64 (and some other archs) for a few weeks now, but not on i686. Is there a specific reason for this, or has it simply been forgotten?

**Comment by Hoshpak** [comment]
I rather looks like the person creating the template didn't bother to create a config for the architecture. Someone has to do that and PR it for the kernel to become available.

**Comment by mithodin** [comment]
Well, is there documentation available for how the config is supposed to look like? Just enable all the modules? I have a grand whopping one i686 machine, so I'm not sure a config that works for me(TM) would be sufficient as a general template.

**Comment by Hoshpak** [comment]
New configs are generally created using `make oldconfig` over an earlier config (5.5 would be best to use in that case). The new options should mostly be set according to the existing x86_64 config. If there are options specific to the i686 architecture, I would look into the documentation on how to set them oder go with the defaults. The resulting configuration should be tested on physical hardware by locally compiling the package and giving it a test run on the target machine before creating a PR.

**Comment by mithodin** [comment]
Right. I'll give it a go then.

**Comment by mithodin** [comment]
Hey, thanks a lot! I had not found the time yet to do it myself.
