### ISSUE TITLE
Linux5.x series: Enable CONFIG_CIFS_SMB_DIRECT

### ISSUE THREAD

**Issue by apaul50** [void-linux/void-packages#21374]
Hello,

I noticed CONFIG_CIFS_SMB_DIRECT is disabled in kernel 5.x series, and I was wondering if it was intentional or not. SMB2 and SMB311 used to be enabled in 4.x series.

Thanks,

**Comment by Hoshpak** [comment]
Looking at the history it looks like it was experimental at first and we don't enable experimental features. It stayed disabled because no one needed it up to now and no one noticed that it's no longer experimental. I don't see a problem with enabling it now.

**Comment by apaul50** [comment]
Thank you for clarification.
I'd be interested by enabling it, so I edit the subject of this issue so it could be flagged as a request.

Thanks !

**Comment by pullmoll** [comment]
I'm working on enabling it for linux5.4-5.4.36; currently building for all targets.

**Comment by apaul50** [comment]
Thanks !
xbps-query -Rs linux5 doesn't show me 5.4.36 yet (I'm still stuck with linux5.4-5.4.35_1, running x64). But I could test it as soon it is available.

Since it's replacing SMB2 and SMB311, this module is needed when mounting cifs version >1. For instance I think mounting a Windows 10 share would require it.

Thanks for your work :) !

**Comment by q66** [comment]
Are you sure? As it looks to me this option is fairly niche stuff about using SMB over RDMA/infiniband.

**Comment by apaul50** [comment]
@q66 After reading the description again, you may be right... I'm really confused. Since I recently switched on kernel 5.4.33, I'm not able to mount my office smb share (vers 2.0). If I boot on 4.19.114 I can mount it (provided I explicitly specify vers=2.0 option).

Watching the config file, I noticed CONFIG_CIFS_SMB311 wasn't present in 5.4 series, and maybe thought too fast it was replaced by CONFIG_CIFS_SMB_DIRECT... SMB311 seems to be merged in CONFIG_CIFS actually...

Guys, I'm really confused and ashamed... I've wasted your time... my apologies...

**Comment by q66** [comment]
I mean, it's still good to enable it as it has its uses, but it will not fix your problem, you will have to find the real cause

**Comment by apaul50** [comment]
Yes indeed. No problem, I will investigate further.

**Comment by apaul50** [comment]
Hello,
It was obvious, but I can now definitely confirm this module has no concern about issues mounting v2+ smbshares. As I said above, I'll investigate.

I don't really know what to do with this issue since I'm unable to test it... Is it ok too close?

Thanks !

**Comment by ericonr** [comment]
Sure, feel free to open another issue if you still have issues.
