### ISSUE TITLE
Package request: vkBasalt

### ISSUE THREAD

**Issue by RibalGZ** [void-linux/void-packages#21427]
A vulkan post processing layer 
Source: https://github.com/DadSchoorse/vkBasalt
Release: https://github.com/DadSchoorse/vkBasalt/releases/tag/v0.3.1

**Comment by HadetTheUndying** [comment]
The instructions appear to state that it's not intended to be installed systemwide. Have you tried building it locally yet?

**Comment by ericonr** [comment]
Has been packaged.
