### ISSUE TITLE
[Package Request]: Texmaker

### ISSUE THREAD

**Issue by marek-lach** [void-linux/void-packages#21457]
An advanced LaTex editor with auto-completion, and an outline.
**Source code**: https://www.xm1math.net/texmaker/texmaker-5.0.4.tar.bz2
**Dependencies**: Qt toolkit (version >= 5.7; gcc, clang and/or msvc.

**Comment by not-chicken** [comment]
```
[~]$ xbps-query -Rs Texmaker
[-] texmaker-5.0.4_1    Free cross-platform LaTeX editor
[-] texstudio-2.12.22_1 Powerful Tex/LaTeX editor based on texmaker
```
It's available! :D
