### ISSUE TITLE
ulatencyd package is broken due to missing ConsoleKit2 dependency

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#21482]
I'm not entirely certain on how to proceed in this case, because it seems the package can still work as is, just requires a rebuild and some rework on the current service files, which depend on consolekit.

@thypon I believe you're the maintainer for this one, right?

**Comment by ericonr** [comment]
Has to do with #21484, too.

**Comment by abenson** [comment]
`ulatencyd` is [abandoned](https://github.com/poelzi/ulatencyd/blob/master/README.md#what-is-ulatency) upstream.

> None the less, my author abondend me because he thinks he has more important things to do. Please adopt me.

In any case, it's [broken](https://github.com/void-linux/void-packages/blob/596250e4ea9b50881e249518e02bd2b7a5aee7c8/srcpkgs/ulatencyd/template#L18) and won't build as is.

> broken="missing symbols in procps-ng (user_from_uid, group_from_gid)"

**Comment by ericonr** [comment]
I went by the part right before it, especially considering we don't have systemd:

> I'm bitrotten but otherwise ok, my design is sound and if I'm running and not getting into a fistfight with systemd, the system runs as smooth as never before.

Think we should remove it or just leave as is?

**Comment by abenson** [comment]
I'm in favor of removing it.

**Comment by ericonr** [comment]
Made a PR
