### ISSUE TITLE
NetworkManager: Improve polkit rules

### ISSUE THREAD

**Issue by flexibeast** [void-linux/void-packages#21578]
Opening this issue based on https://github.com/void-linux/void-docs/issues/135.

It seems the NM package might need to include a file `/etc/polkit-1/rules.d/50-org.freedesktop.NetworkManager.rules` with permissions 644. Is/are there any reasons to not do so?

cc: @Gottox as maintainer

**Comment by Gottox** [comment]
In general it should be fine to allow a network group to have access to NetworkManager. But one small questions though, elogind is capable to set the permissions too, is there a reason to not rely on this machanism?

**Comment by flexibeast** [comment]
@Gottox:

Good question! My experience thus far has been that a number of users would prefer not to have to install and use elogind (cf. e.g. the Wayland + elogind discussions), for a variety of reasons, including the size and complexity of its codebase: `sloccount(1)` reports almost 120,000 lines of C, which creates a large attack surface.

My feeling is that we might need a project-wide decision on whether we support non-elogind-based setups. Although DEs like GNOME certainly require elogind, people can use NM outside of DEs, so such a decision would help us decide whether or not the NM package needs to be changed.

**Comment by Gottox** [comment]
Good point. I think adding the file is fine👍
