### ISSUE TITLE
Profanity Python dependency version uplift

### ISSUE THREAD

**Issue by ErinVoid** [void-linux/void-packages#21587]
* package:  
  profanity 0.81

Can this be adjusted/rebuilt to have Python3 as a dependency rather than the current Python2 please. It is possible, see #https://github.com/profanity-im/profanity/issues/825. Thank you.

**Comment by sgn** [comment]
@ailiop-git, I'll push https://github.com/sgn/void-packages/commit/a2db04e5098f35e8e14f1b1e7ac1f2f695f766d7 if you don't have objection:
```diff
diff --git a/srcpkgs/profanity/template b/srcpkgs/profanity/template
index 2dccec1bd3..ec940d98d1 100644
--- a/srcpkgs/profanity/template
+++ b/srcpkgs/profanity/template
@@ -1,15 +1,17 @@
 # Template file for 'profanity'
 pkgname=profanity
 version=0.8.1
-revision=1
+revision=2
 build_style=gnu-configure
 configure_args="$(vopt_enable notify notifications) $(vopt_enable otr)
 $(vopt_enable pgp) $(vopt_enable python python-plugins) $(vopt_enable plugins)
-$(vopt_with xscreensaver) $(vopt_enable omemo) $(vopt_enable gtk icons) $(vopt_enable cplugins c-plugins)"
-hostmakedepends="pkg-config $(vopt_if python python-devel) $(vopt_if gtk gtk+-devel)"
+$(vopt_with xscreensaver) $(vopt_enable omemo) $(vopt_enable gtk icons)
+$(vopt_enable cplugins c-plugins) ac_cv_prog_PYTHON_CONFIG_EXISTS=yes
+PYTHON_VERSION=3"
+hostmakedepends="pkg-config $(vopt_if python python3-devel) $(vopt_if gtk gtk+-devel)"
 makedepends="libcurl-devel libglib-devel libstrophe-devel readline-devel
  $(vopt_if notify libnotify-devel) $(vopt_if otr 'libotr-devel libgcrypt-devel')
- $(vopt_if pgp gpgme-devel) $(vopt_if python python-devel) $(vopt_if gtk gtk+-devel)
+ $(vopt_if pgp gpgme-devel) $(vopt_if python python3-devel) $(vopt_if gtk gtk+-devel)
  $(vopt_if xscreensaver libXScrnSaver-devel) $(vopt_if omemo 'libsignal-protocol-c libgcrypt-devel')"
 checkdepends="cmocka-devel"
 short_desc="Console based XMPP client"
@@ -23,8 +25,8 @@ export LIBS="-lm"
 
 case "$XBPS_TARGET_MACHINE" in
 	arm*)
-		export PYTHON_CPPFLAGS="-I${XBPS_CROSS_BASE}/${py2_inc}"
-		export PYTHON_EXTRA_LIBS="-L${XBPS_CROSS_BASE}/usr/lib -lpython${py2_ver}" ;;
+		export PYTHON_CPPFLAGS="-I${XBPS_CROSS_BASE}/${py3_inc}"
+		export PYTHON_EXTRA_LIBS="-L${XBPS_CROSS_BASE}/usr/lib -lpython${py3_ver}" ;;
 esac
 
 # Package build options
```

**Comment by ailiop-git** [comment]
i'm really not using python (or python plugins for profanity), but i suppose given that python2 is being EOLed it wouldn't generally hurt to switch to 3, and your patch appears to at least build (at least on x86_64/glibc).

Keep in mind though that the change may of course break any plugins that are written/compatible with only python2 (we don't package profanity-plugins, but still).

So the question here is @ErinVoid why is it necessary to switch to python3? AFAIU profanity-plugins are written in python2. If there is no use for them, we may as well completely disable the python dependency on this package.

**Comment by ErinVoid** [comment]
Thanks for the replies. 

@ailiop-git Apart from Python2 is EoL and it would be the only application on my PC requiring it, just personal preference. However, from [https://profanity-im.github.io/plugins.html](url) it confirms the Profanity can be complied with Python 2 or 3 and the plugins should run with either. It would be very useful to have the OMEMO support.

> Profanity may be compiled against Python 2 or Python 3, so plugins should be able to work with both, the future library can be used in most cases. 

One question, for my curiosity, why is gtk mentioned on a CLI application?

Merci.

**Comment by ailiop-git** [comment]
> Apart from Python2 is EoL and it would be the only application on my PC requiring it, just personal preference. However, from [https://profanity-im.github.io/plugins.html](url) it confirms the Profanity can be complied with Python 2 or 3 and the plugins should run with either. 

If you are using plugins and can confirm that it is working with python 3, then I have no objections. As mentioned, we could also consider disabling python by default if people aren't using the functionality (and still merge the v3 support).

> It would be very useful to have the OMEMO support.

It's by default built, and doesn't depend on python. I'd actually ask again if anyone is using it (I'd think OTR is more popular), and otherwise disable it by default.

> One question, for my curiosity, why is gtk mentioned on a CLI application?

Seems to be a dependency to the tray functionality [1], but I'd be all for disabling this by default.

[1] https://profanity-im.github.io/guide/latest/reference.html#tray

**Comment by sgn** [comment]
On 2020-05-04 10:44:27-0700, ailiop-git <notifications@github.com> wrote:
> > Apart from Python2 is EoL and it would be the only application on my PC requiring it, just personal preference. However, from [https://profanity-im.github.io/plugins.html](url) it confirms the Profanity can be complied with Python 2 or 3 and the plugins should run with either. 
> 
> If you are using plugins and can confirm that it is working with
> python 3, then I have no objections. As mentioned, we could also
> consider disabling python by default if people aren't using the
> functionality (and still merge the v3 support).

I think it'll be better to push it out and wait to see if anyone
complains.

-- 
Danh

**Comment by teldra** [comment]
> > It would be very useful to have the OMEMO support.
> 
> It's by default built, and doesn't depend on python. I'd actually ask again if anyone is using it (I'd think OTR is more popular), and otherwise disable it by default.

OMEMO should left turned on. Many XMPP Clients offer OMEMO support. Some exclusively (Conversations, Gajim, Dino..) In profanity its supported via libsignal-c library.
Profanity v0.8.x was mostly about implementing OMEMO.

**Comment by ErinVoid** [comment]
From what everyone is writing, just an uplift to Python3 would be ideal. Leaving everything else as-is, i.e. Python support in, including OMEMO (and OTR even though more and more apps no longer support it) and gtk.

@ailiop-git thanks for clarifying about gtk. Just curious as trying to improve my software/dev understanding.

Thank you all for being involved and making this happen.
