### ISSUE TITLE
Package request: grub-btrfs

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#21581]
Include BTRFS snapshots at boot options in GRUB menu.
https://github.com/Antynea/grub-btrfs

**Comment by Morgareth99** [comment]
# Template file for 'grub-btrfs'
pkgname=grub-btrfs
version=4.3
revision=1
archs="x86_64"
build_style=gnu-makefile
depends="btrfs-progs grub"
short_desc="Include btrfs snapshots in GRUB boot options"
maintainer="Morgareth <morgareth@tutanota.com>"
license="GPL-3.0-or-later"
homepage="https://github.com/Antynea/grub-btrfs"
distfiles="https://github.com/Antynea/grub-btrfs/archive/${version}.tar.gz"
checksum=6692008326136371bb48fd2a4da0f44e8395413a999862007db6db77543c1f77

**Comment by ericonr** [comment]
Wouldn't it be better to make a PR for it as well? That way you can put the template through CI as well.

**Comment by anjandev** [comment]
I was trying out this package on my void system and wrote a package for it two months ago. I wasnt going to submit but I saw this request. It seems that the other post hasnt submitted a PR so I sent my patch with a PR. Best wishes!

**Comment by Morgareth99** [comment]
> I was trying out this package on my void system and wrote a package for it two months ago. I wasnt going to submit but I saw this request. It seems that the other post hasnt submitted a PR so I sent my patch with a PR. Best wishes!

# Template file for 'grub-btrfs'
pkgname=grub-btrfs
version=4.3
revision=1
build_style=gnu-makefile
depends="btrfs-progs grub"
short_desc="Include btrfs snapshots in GRUB boot options"
maintainer="Morgareth <morgareth@tutanota.com>"
license="GPL-3.0-or-later"
homepage="https://github.com/Antynea/grub-btrfs"
distfiles="https://github.com/Antynea/grub-btrfs/archive/${version}.tar.gz"
checksum=6692008326136371bb48fd2a4da0f44e8395413a999862007db6db77543c1f77

post_install() {
    vinstall ${FILESDIR}/41_snapshots-btrfs 755 /etc/grub.d/41_snapshots-btrfs
}

**Comment by anjandev** [comment]
Do you want to maintain this package instead of me? If so, I have no
problem. Please send a pull request with your patch overwriting my
grub-btrfs package.

**Comment by sgn** [comment]
Hi Anjan,

On 2020-05-27 23:32:37-0700, Anjan Momi <notifications@github.com> wrote:
> 
> Do you want to maintain this package instead of me? If so, I have no
> problem. Please send a pull request with your patch overwriting my
> grub-btrfs package.

Your template installed `/etc/grub.d/41_snapshots-btrfs`
I don't know why we need to install it in post_install.

Minor problem that I've just recognized:

- /etc/default/grub-btrfs/config should be conf_files
- /usr/lib/systemd/system shouldn't exist
- depends+="btrfs-progs"

I would be happy to have you check it and confirm it's correct.

I'm fine with write the change myself if you can confirm my understand
is correct.

If you create PR for them, I'll merge it.

-- 
Danh

**Comment by anjandev** [comment]
All those changes sound reasonable. Please change the package as
required. =)

Thanks for checking over my work.
