### ISSUE TITLE
qutebrowser with webkit backend crashing on musl

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#21617]
### System

* xuname:  
  *Void 5.4.38_1 x86_64-musl GenuineIntel notuptodate rrFFFFFFFFFFFFF*
* package:  
  *qutebrowser-1.11.0_1*
  *python3-PyQt5-webkit-5.13.2_2*
 *qt5-webkit-5.212.0_7*

### Expected behavior
Not segfaulting

### Actual behavior
```
Error compiling builtin: 
Fatal error compiling builtin function 'apply':
```
backtrace: http://ix.io/2kNQ

### Steps to reproduce the behavior
install `qutebrowser` and `python3-PyQt5-webkit` and start `qutebrowser --backend webkit`

**Comment by ericonr** [comment]
This is now working for me without issues, except the backend's own limitations.

**Comment by Johnnynator** [comment]
Yeah, I fixed it some time ago.
