### ISSUE TITLE
Early termination of the sctd daemon.

### ISSUE THREAD

**Issue by chefuik** [void-linux/void-packages#21650]
### System

* xuname:  
  *Void 5.4.38_1 x86_64-musl GenuineIntel uptodate rrnFF*
* package:  
  *sct-0.5_1*

### Expected behavior
the sctd daemon after running continues to work
### Actual behavior
the sctd daemon after starting ends with message:
"logger: socket /dev/log: No such file or directory
logger: socket /dev/log: No such file or directory"
### Steps to reproduce the behavior
run in terminal:
```
chefuik@void:~$ sctd
logger: socket /dev/log: No such file or directory
logger: socket /dev/log: No such file or directory
```

**Comment by Duncaen** [comment]
Not sure how we can solve that, sctd uses logger which now for some reason hard fails if there is n syslog daemon running.

https://docs.voidlinux.org/config/services/logging.html#syslog

**Comment by chefuik** [comment]
thanks for reply,
```
# xbps-install -S socklog-void
# ln -s /etc/sv/{socklog-unix,nanoklogd} /var/service
```
solves the issue.
