### ISSUE TITLE
Package request: wayvnc

### ISSUE THREAD

**Issue by MatthiasGrandl** [void-linux/void-packages#21660]
https://github.com/any1/wayvnc

Very handy tool for `Sway` and other `wlroots` based compositors. Would love to see it packaged.

**Comment by martnnw** [comment]
guess this was closed by either:
https://github.com/void-linux/void-packages/pull/24008
or:
https://github.com/void-linux/void-packages/pull/23884

**Comment by ericonr** [comment]
Indeed!
