### ISSUE TITLE
ghostscript does not include cups device support on armv6-musl and probably others

### ISSUE THREAD

**Issue by klarasm** [void-linux/void-packages#21662]
I discovered this when trying to set up a print server on a Raspberry PI 1 model B. Cups complains of `unknown device: cups` It seems that ghostscript is not built with cups device support, as can be seen below.

Using `xbps-query ghostscript` on my x86_64 desktop system shlib-requires include `libcups.so.2` which is not included on the Raspberry Pi. I compiled ghostscript for x86_64, x86_64-musl, armv6l, armv6l-musl, aarch64, aarch64-musl and only the x86_64 version seems to link to `libcups.so.2`. I have posted the results of xbps-query on ghostscript for the targets below.

I also included the build log for armv6l-musl and the log for the failed cups job.

### System

* xuname:  `Void 4.19.115_1 armv6l-musl Unknown uptodate rrnFFF`
* package: ghostscript-9.52_1 cups-2.3.1_1 (indirectly)

### Expected behavior
Executed on a x86_64 desktop:
```
$ gs -h | grep cups
   chp2200 cif cljet5 cljet5c cljet5pr coslw2p coslwxl cups declj250 deskjet
$ echo $?
0
$
```
### Actual behavior
Executed on  a Raspberry Pi 1 model B
```
$ gs -h | grep cups
$ echo $?
1
$
```
### Steps to reproduce the behavior
Install ghostscript and execute `gs -h | grep cups` on Raspberry Pi 1 model B.

### Attached files
```
$ for i in x86_64 x86_64-musl armv6l armv6l-musl aarch64 aarch64-musl; do XBPS_ARCH=$i xbps-query -Ri --repository=. ghostscript; done
```
[xbps-query-ghostscript.txt](https://github.com/void-linux/void-packages/files/4583308/xbps-query-ghostscript.txt)

```
$ ./xbps-src -a armv6l-musl pkg ghostscript 2>&1 > build-ghostcript_armv6-musl.log
```
[build-ghostscript_armv6l-musl.log](https://github.com/void-linux/void-packages/files/4594138/build-ghostscript_armv6l-musl.log)

```
# cat error_log | grep Job\ 6
```
[cups-error.log](https://github.com/void-linux/void-packages/files/4583416/cups-error.log)

EDIT: corrected the cross-compiled build log for armv6l-musl

**Comment by ericonr** [comment]
Do you have bandwidth to compile it locally? It'd be interesting to find out if the issue stems from cross compiling or something else. I think I can try it later, if you can't.

**Comment by klarasm** [comment]
I can try, but it may take a while as the Raspberry Pi 1 is not very powerfull.

**Comment by ericonr** [comment]
I have a rasp zero only :/

Perhaps @Duncaen could aid here?

**Comment by klarasm** [comment]
The locally built package seems to include cups device support, and it also links against libcups.so.2 so it might be a problem with the cross-compilation as you said. I'll attach the build logs as well.

[xbps-query-ghostscript-rpi-local.txt](https://github.com/void-linux/void-packages/files/4590084/xbps-query-ghostscript-rpi-local.txt)
[build-ghostscript-rpi1-local.log](https://github.com/void-linux/void-packages/files/4590086/build-ghostscript-rpi1-local.log)

**Comment by klarasm** [comment]
Sorry, seems I included the wrong build log for the cross-compilation for armv6-musl. I have updated with the correct one now

**Comment by klarasm** [comment]
I tried building with `./xbps-src -a armv6l-musl -C pkg ghostscript`. I found something interesting in the ghostscript Makefile:
```
# Define install location for 'cups' device/filter support    
CUPSLIBS=
CUPSLIBDIRS=
CUPSSERVERBIN=
CUPSSERVERROOT=
CUPSDATA=
CUPSPDFTORASTER=0

SHARE_LCUPS=1
LCUPS_NAME=cups
LCUPSSRCDIR=./cups
LCUPSBUILDTYPE=
CUPS_CC=$(CC)

SHARE_LCUPSI=1
LCUPSI_NAME=cupsimage
LCUPSISRCDIR=./cups
CUPS_CC=$(CC)
```

If I build with `./xbps-src -C pkg ghostscript` I get this instead:
```
# Define install location for 'cups' device/filter support    
CUPSLIBS=cups
CUPSLIBDIRS=
CUPSSERVERBIN=/usr/lib/cups
CUPSSERVERROOT=/etc/cups
CUPSDATA=/usr/share/cups
CUPSPDFTORASTER=1

SHARE_LCUPS=1
LCUPS_NAME=cups
LCUPSSRCDIR=./cups
LCUPSBUILDTYPE=
CUPS_CC=$(CC)

SHARE_LCUPSI=1
LCUPSI_NAME=cupsimage
LCUPSISRCDIR=./cups
CUPS_CC=$(CC)
```

**Comment by klarasm** [comment]
This might be related:[6773c53b1af42eacc01075a5926632fad48887f3](https://github.com/void-linux/void-packages/commit/6773c53b1af42eacc01075a5926632fad48887f3).
This however makes me think that's not the case (from the armv6l-musl build log):
```
   cups: Enable support for CUPS (ON)
```

**Comment by klarasm** [comment]
Okay, so I undid the changes from that commit and fixed some resulting conflcts and ghostscript now seems to link with libcups.so.2. The changes are here: [b52d79b8d9e367f1fc2dbd23e137d8fc88fd5927](https://github.com/klarasm/void-packages/commit/b52d79b8d9e367f1fc2dbd23e137d8fc88fd5927).

[build-ghostscript_armv6l-musl-modified-template.log](https://github.com/void-linux/void-packages/files/4594663/build-ghostscript_armv6l-musl-modified-template.log)
[xbps-query-ghostscript_armv6l-musl-modified-template.txt](https://github.com/void-linux/void-packages/files/4594667/xbps-query-ghostscript_armv6l-musl-modified-template.txt)

**Comment by klarasm** [comment]
Hmm. The Makefile still looks like this with the modified template:
```
# Define install location for 'cups' device/filter support
CUPSLIBS=
CUPSLIBDIRS=
CUPSSERVERBIN=
CUPSSERVERROOT=
CUPSDATA=
CUPSPDFTORASTER=0

SHARE_LCUPS=1
LCUPS_NAME=cups
LCUPSSRCDIR=
LCUPSBUILDTYPE=
CUPS_CC=$(CC)

SHARE_LCUPSI=1
LCUPSI_NAME=cupsimage
LCUPSISRCDIR=
CUPS_CC=$(CC)
```

**Comment by klarasm** [comment]
(sorry for spamming, accidentally closed the issue earlier)
Ok, this is interesting. With the modified template the x86_64 Makefile also looks like this (seems I also missed an important line earlier):
```
# Define install location for 'cups' device/filter support                                                
CUPSLIBS=
CUPSLIBDIRS=
CUPSSERVERBIN=
CUPSSERVERROOT=
CUPSDATA=
CUPSPDFTORASTER=0

SHARE_LCUPS=1
LCUPS_NAME=cups
LCUPSSRCDIR=
LCUPSBUILDTYPE=
CUPS_CC=$(CC)

SHARE_LCUPSI=1
LCUPSI_NAME=cupsimage
LCUPSISRCDIR=
CUPS_CC=$(CC)

CUPSCFLAGS= -DSHARE_LCUPS=$(SHARE_LCUPS) -DSHARE_LCUPSI=$(SHARE_LCUPSI)
```

With original template (x86_64):
```
# Define install location for 'cups' device/filter support                                                  
CUPSLIBS= cups
CUPSLIBDIRS=
CUPSSERVERBIN=/usr/lib/cups
CUPSSERVERROOT=/etc/cups
CUPSDATA=/usr/share/cups
CUPSPDFTORASTER=1

SHARE_LCUPS=1
LCUPS_NAME=cups
LCUPSSRCDIR=./cups
LCUPSBUILDTYPE=
CUPS_CC=$(CC)

SHARE_LCUPSI=1
LCUPSI_NAME=cupsimage
LCUPSISRCDIR=./cups
CUPS_CC=$(CC)

CUPSCFLAGS= -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_RESTRICT=1 -DUSE_LIBPAPER  -DSHARE_LCUPS=$(SHARE_LCUPS) -DSHARE_LCUPSI=$(SHARE_LCUPSI)
```

So it seems my change instead breaks build for x86_64 non-cross as well.

**Comment by fosslinux** [comment]
Let me confirm - when you cross build for `armv6l-musl`, it does show cups support to be on?

**Comment by klarasm** [comment]
> Let me confirm - when you cross build for `armv6l-musl`, it does show cups support to be on?

The xbps-src build option is turned on as per the build logs, but the generated Makefile does not seem to include it.

**Comment by ericonr** [comment]
@klarasm found the time to get a fix c:

**Comment by klarasm** [comment]
@ericonr Great, thank you! I can confirm this fixes the issue. I will close this issue once the commit is merged.
