### ISSUE TITLE
FTBTS Error: Plex Media Server

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#21732]
### System

* xuname:  
  Void 5.4.38_1 x86_64 GenuineIntel uptodate rrmFFFFF
* package:  
 plex-media-server-1.15.3.876_3
### Expected behavior
Build from source
### Actual behavior
FTBTS Error
=> ERROR: cannot convert shebang, set python_version
=> ERROR: plex-media-server-1.15.3.876_3: pre-pkg_03-rewrite-python-shebang: 'find "${PKGDESTDIR}" -type f -print0' exited with 1
=> ERROR:   in hook() at common/hooks/pre-pkg/03-rewrite-python-shebang.sh:19
=> ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
=> ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:232
=> ERROR:   in main() at common/xbps-src/libexec/xbps-src-prepkg.sh:47
### Steps to reproduce the behavior
./xbps-src pkg plex-media-server

**Comment by not-chicken** [comment]
Needs `python_version=2`
CC @Anachron

**Comment by mrhieu059** [comment]
> Needs `python_version=2`
> CC @Anachron

I already installed python2, which config file do I have to put this `python_version=2` in?

**Comment by not-chicken** [comment]
> I already installed python2, which config file do I have to put this `python_version=2` in?

In the template file, see the linked PR.
