### ISSUE TITLE
Linux IOMMU Support cuase system freeze on boot

### ISSUE THREAD

**Issue by martindamianfernandez** [void-linux/void-packages#21767]
### System

* xuname: Void 4.19.121_1 x86_64-musl GenuineIntel uptodate FF4
  xuname: Void 4.19.121_1 x86_64 GenuineIntel uptodate FF
  *output of ``xuname`` (part of xtools)*
* package: linux4.19, linux5.4.39 and may be many more kernels.
*affected package(s) including the version*

### Expected behavior
hangs igp on boot 
### Actual behavior
when use kernel parameter intel_iommu=off system boots and work fine so far.
many laptops happen, and some desktops

### Steps to reproduce the behavior
just basic installation tide to hardware specs.

**Comment by travankor** [comment]
What hardware are you using?

**Comment by martindamianfernandez** [comment]
very large list to desribe working a technical support. 
this happen on laptops mostly skylake's, xeons v5.

**Comment by ericonr** [comment]
@martindamianfernandez I made a PR documenting it here https://github.com/void-linux/void-docs/pull/265, what do you think?

**Comment by ericonr** [comment]
Documented, changing is WONTFIX afaik.
