### ISSUE TITLE
Package request: signal-cli

### ISSUE THREAD

**Issue by facadeproof** [void-linux/void-packages#21762]
For those not wanting to use `electron` in their systems, [signal-cli](https://github.com/AsamK/signal-cli) is a command line and dbus interface for Signal. This would allow other clients such as [scli](https://github.com/isamert/scli) to work. 

A pull request was opened #13208 but hasn't been merged since last year.

**Comment by Piraty** [comment]
well, we have PR #13208 already, no need to request this package.
