### ISSUE TITLE
Error when packaging mesa with -o ~wayland

### ISSUE THREAD

**Issue by BouncyMaster** [void-linux/void-packages#21808]
* system:
 `./xbps-src binary-bootstrap`
* package:  
  `mesa (20.0.6)`

### Expected behavior
Compiling mesa with `./xbps-src -o ~wayland pkg mesa`  will package the program successfully.
### Actual behavior
* The first issue is that it also packages `clang` and `llvm` when only requesting mesa.
* After compiling `clang` and `llvm` i get these errors:
```
meson.build:306:4: ERROR: Problem encountered: Invalid argument list given to -Dplatforms
and
ERROR:   in do_configure() at common/build-style/meson.sh:95
```
There were more errors but they were obstructed when i accidentaly resized the terminal.

Output of `/builddir/mesa-20.0.6/build/meson-logs/meson-log.txt`
[meson-log.txt](https://github.com/void-linux/void-packages/files/4605401/meson-log.txt)

Also there is my etc/conf:
```
XBPS_CFLAGS="-O2 -march=znver1 -pipe"
XBPS_CXXFLAGS="${XBPS_CFLAGS}"
```

**Comment by Duncaen** [comment]
> * The first issue is that it also packages clang and llvm when only requesting mesa.

xbps-src always uses the version of a dependency it has a template for, your clone is most likely outdated and uses llvm9 for clang while the void repositories contain clang build with llvm10.

**Comment by st3r4g** [comment]
Maybe there is a misplaced comma?
Try to change `$(vopt_if wayland wayland),`
into `$(vopt_if wayland wayland,)`

**Comment by BouncyMaster** [comment]
> Maybe there is a misplaced comma?
> Try to change `$(vopt_if wayland wayland),`
> into `$(vopt_if wayland wayland,)`

After updating the local repo and moving the comma `mesa` was packaged succesfully, thanks.

**Comment by st3r4g** [comment]
The comma thing is a bug, so you can send a PR to fix it if you want

**Comment by BouncyMaster** [comment]
Will do

**Comment by st3r4g** [comment]
Don't bump the revision, so we avoid to rebuild
