### ISSUE TITLE
Recommended udev rules for android-tools

### ISSUE THREAD

**Issue by pbui** [void-linux/void-packages#21850]
### System

* xuname:  

Void 5.4.40_1 x86_64 GenuineIntel uptodate rDDDDDDDDDDDFFFFFF  

* package:  
  
android-tools

### Expected behavior

To properly access usb devices (ie. phones) with adb, it is recommended that we have the udev rules from the following location:

https://github.com/M0Rf30/android-udev-rules/blob/master/51-android.rules

To make use of these rules, the user should be in the `adbusers` group.

### Steps to reproduce the behavior

We can probably just include this file in a separate `android-udev` package like Arch does:

https://www.archlinux.org/packages/community/any/android-udev/

**Comment by pbui** [comment]
@ericonr Should be straightforward to package if you are interested.

**Comment by ericonr** [comment]
Good, they have releases! If you want to package them, go for it :)

Otherwise I think I can get to it on the weekend.

**Comment by Piraty** [comment]
ping

**Comment by ericonr** [comment]
I can try this weeked, then :p

**Comment by rien** [comment]
@ericonr I hope you don't mind, but I've created a PR with the rules list over at #23284.

**Comment by ericonr** [comment]
No worries, thanks for getting to it c:

**Comment by PaperMountainStudio** [comment]
I think users will have to run udevadm control --reload-rules and adb kill-server or reboot. Should this be added as a post-install message?

**Comment by ericonr** [comment]
@PaperMountainStudio I don't think so. The message would have to be added to all packages that ship udev rules, which would quickly become a mess.

**Comment by sgn** [comment]
A trigger would be better, no?

**Comment by rien** [comment]
I can't find a package which does something similar. But this looks like something which could be automated in xbps instead of package-specific triggers? (E.g. if xbps changed a file in `/etc/udev/` or `/usr/lib/udev/`, it could reload udevd).

**Comment by ericonr** [comment]
I'm not sure that's possible. Most triggers take the package name and some exported variable to determine what they are going to do.

**Comment by sgn** [comment]
On 2020-06-29 05:30:24-0700, Érico Nogueira Rolim <notifications@github.com> wrote:
> I'm not sure that's possible. Most triggers take the package name
> and some exported variable to determine what they are going to do.

The question is who will do it ;)

-- 
Danh

**Comment by dm17** [comment]
Anything special one needs to do on void? I remember being able to get this to work before, but I can't remember how. adb devices (with & without sudo) is not showing anything (yes I've killed & started adb server).

**Comment by ericonr** [comment]
@dm17 installing the udev rules package and restarting or running `udevadm trigger` should be enough...

**Comment by dm17** [comment]
> @dm17 installing the udev rules package and restarting or running `udevadm trigger` should be enough...

Thanks; I figured it out. It was actually that I needed to enable USB debugging on the android side.
