### ISSUE TITLE
PHP: Uncaught Error: Class 'SQLite3' not found

### ISSUE THREAD

**Issue by ILadis** [void-linux/void-packages#21852]
### System

* xuname:  `Void 4.19.118_1 armv7l Unknown uptodate rF`
* package:  `php-7.4.5_1`, `php-sqlite-7.4.5_1`

### Actual behavior
I'm trying to get the PHP SQLite3 extension to work on my Raspberry PI. I installed the above packages and enabled the extension in `/etc/php/php.ini` by uncommenting `;extension=sqlite3`.

Executing `php -m` does **not** list sqlite as a PHP module.
Executing `php -i` does **not** mention any SQLite3 support.

### Expected behavior
SQLite3 should work after installing `php-sqlite-7.4.5_1` and enabling the extension in `/etc/php/php.ini`.

### Steps to reproduce the behavior
Install the above packages, enable SQLite3 extension and run `php -r 'new SQLite3("db");'`:

```
PHP Fatal error:  Uncaught Error: Class 'SQLite3' not found in Command line code:1
Stack trace:
#0 {main}
  thrown in Command line code on line 1
```

**Comment by newbluemoon** [comment]
Just did an install on my up-to-date RPi armv7l-musl and aarch64-musl. Running the command above succeeded. No error reported, an empty 'db' was created and `php -m` does report sqlite support.

On armv7l, however, it failed as above. I don’t have other systems to test handy right now.

It seems the cross built php does work, at least for musl systems. So what’s different on glibc systems?

**Comment by ILadis** [comment]
I tried some other extensions and these did not work as well. So it does not seem to be a SQLite exclusive issue.

I also tried compiling `php` myself on the RPi by cloning this repository and running `./xbps-src pkg php`. The package build without any errors and after installing it, everything worked as expected.

**Comment by newbluemoon** [comment]
I think I found the solution, please test #22019 if it works for you.

**Comment by ILadis** [comment]
I installed the updated version `php-7.4.5_2` on my RPi and can confirm it's working now. Thanks for fixing!

**Comment by prog98** [comment]
if you use xampp or ... first close xampp or ...
go to this directori : xampp > php > php.ini ( find this file php.ini on php folder)
and open php.ini file with notepad
and search SQLite3
and remove ; this line ;extension=sqlite3
so finaly be extension=sqlite3
and save file 
end open xampp

sorry my cant good speak english i hope i can help you.

**Comment by JimChristop** [comment]
> if you use xampp or ... first close xampp or ... go to this directori : xampp > php > php.ini ( find this file php.ini on php folder) and open php.ini file with notepad and search SQLite3 and remove ; this line ;extension=sqlite3 so finaly be extension=sqlite3 and save file end open xampp
> 
> sorry my cant good speak english i hope i can help you.

It worked, a thumbs up from me, good job!
