### ISSUE TITLE
Paper-Icon-Theme: broken icons

### ISSUE THREAD

**Issue by Lolzen** [void-linux/void-packages#21895]
https://github.com/mydongistiny/paper-icon-theme-git/blob/master/0001-Paper-scalable-fix-svg-namespace-definitions.patch

**Comment by pullmoll** [comment]
Errr... looking at the URL for xmlns:osb it seems that this site has been hijacked some time after 2009.

**Comment by Lolzen** [comment]
um.. okay. i don't pretend i understand, i just wanted to report it and found the link posted.
I guess it's a security risk, if so you're free to remove the link.

**Comment by ericonr** [comment]
Maybe updating to a git revision is necessary, they seem to have fixed upstream.

**Comment by Lolzen** [comment]
> Maybe updating to a git revision is necessary, they seem to have fixed upstream.

I've gone forth and built the theme from git sources with xbps-src (tho i suck at templates) and can confirm that.
