### ISSUE TITLE
subversion qt cyclic dependency

### ISSUE THREAD

**Issue by fosslinux** [void-linux/void-packages#21906]
Yet another! AFAICT, this seems to be restricted to musl, as I don't recall this on my glibc build...

```
=> ERROR: Build-time cyclic dependency subversion(host), kdelibs4support(host), kcoreaddons(host), extra-cmake-modules(host), qt5(host), libinput(host), libwacom(host), librsvg(host), cargo(host), libgit2(host), git(host), subversion(host) detected.
```

**Comment by Johnnynator** [comment]
Can you check if building qt5 without git does work?

**Comment by Chocimier** [comment]
Subversion depending on kdelibs4support create lot of cycles. I'll try to split templates.

**Comment by fosslinux** [comment]
@Johnnynator No, it fails with

```
/usr/bin/ld:QtCore.version:0: syntax error in VERSION script
```

**Comment by Johnnynator** [comment]
That error is probably missing perl in host makedepends

**Comment by fosslinux** [comment]
Well, readding `git` removes the failure...

**Comment by Johnnynator** [comment]
Doesn't git pull in Perl?

**Comment by Chocimier** [comment]
Sent PR with splitted kdelibs4support from subversion.
