### ISSUE TITLE
Unable to login with linux-5.4.40

### ISSUE THREAD

**Issue by mustaqimM** [void-linux/void-packages#21946]
### System

* xuname:  
  ``Void 5.4.39_1 x86_64 GenuineIntel uptodate rrFFFFFFFFFFFF``
* package:  
  `linux-5.4_1`

### Expected behavior
Login normally with non-root user

### Actual behavior
When I enter my username and press `Enter`, I am only able to input a single char of my password before it asks for my username again. This occurs on every few versions of the 5.4 release (even on a completely fresh install). This is the first time on a fresh install on `5.4`.

After reverting to `5.4.39`, I was able to login normally.

### Steps to reproduce the behavior
* Update to 5.4
* Reboot
* Attempt to login

**Comment by furryfixer** [comment]
Are you able to login as root?  Not aware of this being a widespread problem, possibly one due to your specific setup.  Common causes to think about include:
/ or /home partition full or not mounted before login (/etc/fstab not setup correctly)
Improper permissions for your user's home directory
Improper SHELL variable set for your user
Corrupted or improper shell scripts in user home directory, or possible wrong permissions again.

**Comment by fosslinux** [comment]
This sounds suspiciously like `/boot` becomes full and so something weird happens...

**Comment by Anachron** [comment]
@mustaqimM we gotta need more infos here.

**Comment by mustaqimM** [comment]
@Anachron unfortunately that's all I can give to debug at the moment. Actually I re-installed and repartitioned `/boot`; it was close to full, so maybe it was that. I have since changed to 5.6.13.

The only thing that makes me doubt that is that I hardly ever prune the directory with: `vkpurge rm all` and it occurs randomly on versions of `5.4`

**Comment by biopsin** [comment]
@mustaqimM
mind close this as it's outdated and no more relevant.
Thank you

**Comment by ericonr** [comment]
Hm, this may have been hasty... We still ship linux 5.4 as a package.

**Comment by biopsin** [comment]
@ericonr I'm still on 5.4 (on 3 different systems intel&amd) but never experienced any trouble with login.
OP seems to have moved on > 5.6
..but lets see

**Comment by mustaqimM** [comment]
I haven't had this issue since I kept the boot partition size under control by periodically running: `sudo vkpurge rm all`. And at the same time, I have moved to 5.9. I suspect it was the boot partition becoming full as @fosslinux said above

**Comment by ericonr** [comment]
Got it, thank you both.
