### ISSUE TITLE
pdflatex Font not found

### ISSUE THREAD

**Issue by shtayerc** [void-linux/void-packages#22012]
### System
* xuname:  
  Void 5.4.41_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFFF
* package:  
  texlive-bin-2020_1

### Expected behavior
`pdflatex` successfully compiles
### Actual behavior
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-05-14>
(/opt/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/opt/texlive/2020/texmf-dist/tex/latex/base/size10.clo))
(/opt/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def)
(./test.aux) [1{/opt/texlive/2020/texmf-var/fonts/map/pdftex/updmap/pdftex.map}
] (./test.aux) )
!pdfTeX error: /opt/texlive/2020/bin/x86_64-linux/pdflatex (file tcrm1000): Fon
t tcrm1000 at 600 not found
 ==> Fatal error occurred, no output PDF file produced!
```
### Steps to reproduce the behavior
Run `pdflatex test.tex`.

Content of test.tex:
```tex
\documentclass{article}
\begin{document}
\begin{itemize}
    \item Test
\end{itemize}
\end{document}
```

**Comment by Anachron** [comment]
Install the missing font?

**Comment by flexibeast** [comment]
Can't reproduce here; running `pdflatex` on `test.tex` completes successfully.

**Comment by flexibeast** [comment]
Output of `tlmgr search --file tcrm1000 --global`:

    tlmgr: package repository http://mirror.aarnet.edu.au/pub/CTAN/systems/texlive/tlnet (verified)
    ec:
            texmf-dist/fonts/source/jknappen/ec/tcrm1000.mf
            texmf-dist/fonts/tfm/jknappen/ec/tcrm1000.tfm

**Comment by shtayerc** [comment]
`ec` package is already installed.
```
tlmgr: package repository http://ctan.ijs.si/tex-archive/systems/texlive/tlnet (verified)
tlmgr install: package already present: ec
```

**Comment by shtayerc** [comment]
I figured it out. `/opt/texlive/2020/bin` was not in `$PATH` (different shell). I was running pdflatex command directly. After I added it to `$PATH` it works.
