### ISSUE TITLE
[Meta Package Request]: void-installation

### ISSUE THREAD

**Issue by imrn** [void-linux/void-packages#22010]
Reasons:

My Void installation is 3 years old and I'd installed and removed a lot of packages since then. Now, I want to make sure that it again contains all packages of the official Void installation. Some originally installed packages may have been removed during removals and orphan clean ups.

May be official Void installation package set may change over time or I want to be sure that my system follows it or I just want to see the differences.

Or may be I want to perform a fresh manual installation via
"xbps-install -r /install_dir void-installation" without using void-installer.

Probably there will be other use cases and possible flavours. Such as
"void-bare-minimum", "void-embedded", etc

**Comment by Chocimier** [comment]
It's called `base-system`

**Comment by imrn** [comment]
Thanks. Closing.
