### ISSUE TITLE
Request: CONFIG_NVME_HWMON by default in kernels>5.5

### ISSUE THREAD

**Issue by abhocetabhac** [void-linux/void-packages#22024]
Starting with Linux 5.5 it became possible to monitor NVMe temperatures via sysfs/hwmon if CONFIG_NVME_HWMON=yes. Methinks it would be nice to have the feature enabled in Void's mainline kernels. Could it be added, please?

**Comment by ericonr** [comment]
Linux 5.5 is end of life, so that's an option that would make sense to add only to Linux 5.6.
