### ISSUE TITLE
Platform Request: RPI 4 B

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#22023]
Please add `RPI 4 B` support as I plan to get one soon to replace my old `RPI 3 B+` media box.

**Comment by Anachron** [comment]
Ping, is anybody working on this?

**Comment by manneorama** [comment]
@Anachron There is an open PR: https://github.com/void-linux/void-packages/pull/26000

**Comment by Piraty** [comment]
in the works, see #26000
