### ISSUE TITLE
xdm package upgrade wipes out configuration changes

### ISSUE THREAD

**Issue by bwalzer866** [void-linux/void-packages#22090]
### System

* xuname:  
  Void 5.4.30_1 x86_64 AuthenticAMD notuptodate rF
* package:  xdm
  xdm-1.1.12_2

### Expected behavior
Updating the xdm package should not overwrite config files changed by the user.
### Actual behavior
Updating the xdm package _does_ overwrite config files changed by the user.
### Steps to reproduce the behavior
Update the xdm package.

Seriously though, could someone please add the config files to the Void xdm package? This is the list of xdm config files I swiped from the Arch Linux package:

`/etc/X11/xdm/Xaccess`
`/etc/X11/xdm/Xresources/`
`/etc/X11/xdm/Xservers`
`/etc/X11/xdm/xdm-config`
`/etc/pam.d/xdm`
`/etc/X11/xdm/Xsetup_0`
`/etc/X11/xdm/Xsession`

... from [here](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/xorg-xdm).

**Comment by ericonr** [comment]
This is weird. Most of those files are marked as configuration files. @leahneukirchen do you have any idea what's happening?

**Comment by bwalzer866** [comment]
I (the submitter) might of screwed up here. There was a change: #8eb1ee93956023a7fa2e12f3419e0b8c5a2858d7

... which I both missed on on the history and present state somehow. I think I should just quietly close this. Sorry for the bother...

**Comment by ericonr** [comment]
No problem! Glad you worked it out c:
