### ISSUE TITLE
Package Request: Lite

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#22101]
https://github.com/rxi/lite

> A lightweight text editor written in Lua 

License: [MIT](https://github.com/rxi/lite/blob/master/LICENSE)

Would be good to bundle [plugins](https://github.com/rxi/lite-plugins) as well?

**Comment by codingHahn** [comment]
Does the editor support enabling and disabling plugins? If not, we should not bundle them, because then all of them would be loaded at startup, which is not the expected behavior.

**Comment by Anachron** [comment]
No, it doesn't. That one of the points of `lite`. But you can bundle single files.

**Comment by codingHahn** [comment]
ok. So we shouldn't ship plugins then

**Comment by HectorCastelli** [comment]
Should each plugin be provided as a separate package or should they all be bundled as a single package?

As a single package (`xbps-install lite lite-plugins`), it would be easier to install, but the editor would end up loading all or none plugins, going back to the problem @codingHahn  pointed out.

With a per-plugin-package (`xbps-install lite lite-plugins-autoinsert lite-plugins-autowrap ...`) we would have the flexibility, but I'm not sure if it would be problematic to have so many packages flooding the repos for a single tool.

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/194af0f4b8c11606bb1302a76aa69708b109de59
