### ISSUE TITLE
Package Request: libsane-hpaio

### ISSUE THREAD

**Issue by andrzejkepa** [void-linux/void-packages#22158]
this package is needed for working simple-scan 
without this one can't scan
it would be nice to musl version

best regards

**Comment by newbluemoon** [comment]
As far as I remember you have to uncomment `hpaio` in `/etc/sane.d/dll.conf` after installing and configuring hplip. Not sure if this is still valid as I don’t have such a device.

**Comment by newbluemoon** [comment]
Btw: You can use `xlocate` (from xtools-package):
```
$ xlocate hpaio
hplip-3.20.3_1	/usr/lib/sane/libsane-hpaio.so -> /usr/lib/sane/libsane-hpaio.so.1.0.0
hplip-3.20.3_1	/usr/lib/sane/libsane-hpaio.so.1 -> /usr/lib/sane/libsane-hpaio.so.1.0.0
hplip-3.20.3_1	/usr/lib/sane/libsane-hpaio.so.1.0.0
hplip-gui-3.20.3_1	/usr/lib/sane/libsane-hpaio.so -> /usr/lib/sane/libsane-hpaio.so.1.0.0
hplip-gui-3.20.3_1	/usr/lib/sane/libsane-hpaio.so.1 -> /usr/lib/sane/libsane-hpaio.so.1.0.0
hplip-gui-3.20.3_1	/usr/lib/sane/libsane-hpaio.so.1.0.0
```

You’ll probably have to download the hpaio plugin via `hp-setup` or `hp-plugin`.
As the plugin only comes as a binary blob I don’t think it’ll work with musl.
