### ISSUE TITLE
font-iosevka: missing Curly & proportional fonts

### ISSUE THREAD

**Issue by 0n-s** [void-linux/void-packages#22166]
The `font-iosevka` package has Iosevka & Iosevka Slab, but it's missing the newer (>=3.0.0, the current package is 3.0.1 so these should be present) Iosevka Curly, Iosevka Curly Slab & also the quasi-proportional fonts Iosevka Aile, Iosevka Etoile, & Iosevka Sparkle.

**Comment by MatthiasGrandl** [comment]
Yeah I think they should be included as well! Really beautiful typefaces!

**Comment by georgianfire** [comment]
I can add those fonts but I think it may not be a good idea to pack all the variants in a single package since there are so many of them. What about we learn from Arch (https://aur.archlinux.org/packages/?K=ttf-iosevka) and put each variant in a separate package? Maybe even the slab variant should be in a separate package.

Some input on to implement this would be appreciated.

**Comment by MatthiasGrandl** [comment]
@georgianfire mhm will I agree, that putting all of the fonts into one package is pretty bloated, I think the Arch example might be too big of a hassle to maintain...

No strong opinions on this though.

**Comment by linkert** [comment]
Want to hijack this issue. I previously had Iosevka all-over my system gtk, qt, in browser, terminal, file manager, text editor - everything was set to one of the variants term, aile, etoile or sparkle. Then I had the variants locally and manually installed. I did not know until recently that there was an Iosevka package in the repos - was happy to find out there was! However it's, to me, incomplete.

What about a compromise? I get that one does not want the "SS01, SS02, SS..." variants that are supposed to emulate other fonts(? not sure I get the use?) and they probably should be separated. But the core thing that IS Iosevka as an all-in-one - yes please that would be magical.

If someone want all of it:


```font-iosevka-ss:```

- Iosevka SS01, 02, 03, 04 et cetera..


```font-iosevka:```

- Iosevka
	- Iosevka Term
	- Iosevka Fixed
- Iosevka Slab
	- Iosevka Term Slab
	- Iosevka Fixed Slab
- Iosevka Curly
	- Iosevka Term Curly
	- Iosevka Fixed Curly
- Iosevka Curly Slab
	- Iosevka Term Curly Slab
	- Iosevka Fixed Curly Slab
- Iosevka Aile
- Iosevka Etoile
- Iosevka Sparkle

**Comment by Chocimier** [comment]
It's unlikely more variants will be accepted, we are already limiting number of fonts in repo.

**Comment by linkert** [comment]
> It's unlikely more variants will be accepted, we are already limiting number of fonts in repo.

You closed this issue but the issue is not resolved. The font-iosevka package is half a package since half of what the github repo contains is left out.

What's the Void stance on font packages? What's the issue with them?

**Comment by Chocimier** [comment]
> What's the Void stance on font packages?

We think they do not [need](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements) to be packaged as pure data.

> You closed this issue but the issue is not resolved.

Ok, marked as wontfix.

**Comment by linkert** [comment]
> > What's the Void stance on font packages?
> 
> We think they do not [need](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements) to be packaged as pure data.

I would then suggest putting this stance into practice and purging all non-required fonts-, icons- and theme packages (and whatever else might be in the repo that does not fit). That way I won't go all happy when I see a package for Iosevka only to be let down by the fact that it's a dismembered dud of a package.

It's a sound policy and stance which I agree with for the most part - but I could see "popular demand" as an addition - might submit a PR :)
