### ISSUE TITLE
evieext conflicts with xorgproto

### ISSUE THREAD

**Issue by not-chicken** [void-linux/void-packages#22172]
### System

* package:  
  `evieext-1.1.1_2`, `xorgproto-2019.2_1` 

### Expected behavior
No conflicts
### Actual behavior
```
libffi-devel-3.3_2: ERROR: evieext-1.1.1_2: file `/usr/include/X11/extensions/Xeviestr.h' already installed by package xorgproto-2019.2_1.
ERROR: evieext-1.1.1_2: file `/usr/include/X11/extensions/evieproto.h' already installed by package xorgproto-2019.2_1.
```
### Steps to reproduce the behavior
`./xbps-src -aaarch64 pkg at-spi2-core`

### Possible Solution
Remove `evieext`( and the only package that depends on it `libXevie`) from the repos, it's been replaced by `xorgproto` [upstream](https://gitlab.freedesktop.org/xorg/proto/evieproto/-/commit/b834764e393cdc966fa3ac6ca0f004108fd5e4d6).

According to xbps-query only `at-spi2-core` needs `libXevie-devel` , but it isn't listed as a dep by [upstream](https://github.com/GNOME/at-spi2-core/blob/mainline/INSTALL) and I was able to build it without it so `libXevie` should be safe to remove as well.

**Comment by mnabid** [comment]
```
$ xbps-query -RX evieext                                                            
libXevie-devel-1.0.3_7
```

@pullmoll removed `evieext` from makedepends of `libXevie` in a9802e09080c1150cce7a9c494a3fef2198df9bd, but must have forgotten to bump revision. I rebuilt `libXevie` and then `at-spi2-core` builds fine again.

**Comment by ericonr** [comment]
That makes the case for removing `evieext` even better, then.

**Comment by not-chicken** [comment]
@mnabid `libXevie-devel` and looks like even `libXest-devel` are not used while building `at-spi2-core`. So they may be removed from makedepends I guess.
