### ISSUE TITLE
Tagging packages

### ISSUE THREAD

**Issue by anjandev** [void-linux/void-packages#22191]
As discussed on irc, there exists a tags variable for xbps templates:

https://github.com/void-linux/void-packages/blob/master/Manual.md

However, grepping for templates using this tags variable shows very few or no results.

I suggest that we standardize some tags for xbps (ie. games, electron, etc.) and write documentation on how to use `xbps-query` to search for tags in the void repos. Maybe we can add an option for users to `exclude-tags=electron` in their `/etc/xbps.d` so that users can have xbps automatically not suggest electron apps.

Tags can help us document pages like this: https://wiki.voidlinux.org/Games and help generally in users discovering new applications.

**Comment by xmksv** [comment]
I second this, it could be very useful.

**Comment by GithubPrankster** [comment]
Also interested in this. Letting the user customize their query down to certain wished features is quite the useful thing.

**Comment by ericonr** [comment]
For the record, the machinery for tagging seems to be there:

```
architecture: x86_64
filename-sha256: fc9d82788efcf54692652b8b44afe8061e21662987e8368386b099571a9bbf80
filename-size: 10MB
homepage: https://github.com/arduino/arduino-cli
install-date: 2020-05-23 23:08 -03
installed_size: 22MB
license: GPL-3.0-or-later
maintainer: Jasper Chan <jasperchan515@gmail.com>
metafile-sha256: 755adddd4961301658f24bb18f34a3454c2d33e28535a5ff8d6606ee8d22ef5e
pkgname: arduino-cli
pkgver: arduino-cli-0.10.0_2
repository: /home/ericonr/void/void-packages/hostdir/binpkgs/arduino
run_depends:
	glibc>=2.29_1
shlib-requires:
	libpthread.so.0
	libc.so.6
short_desc: Arduino command line interface
state: installed
tags: embedded arduino
```

**Comment by anjandev** [comment]
It would be useful to add to `xlint` a check to see if each template the
person has changed has at least one "primary" tag which we can define.

This would allow us to eventually tag the entire repository
incrementally as packages update rather than requiring massive effort
on the part of maintainers.

Of course, we first need to decide on tags.

**Comment by ericonr** [comment]
Tagging incrementally would be better than all at once, indeed. I'm not against this idea, but I'm not a maintainer either. There might be reasons against this.

It would make sense to have a "permitted tags" list drafted as well.

```
compiler
base-system
games (game?)
dev
x11
wayland
graphics
art
...
```

**Comment by Anachron** [comment]
I would expect tags to be written in a singular format.
A permitted tag list can easily be solved by a `xlint` grep.

My suggestion: Start with bigger topics (like `compiler`, `window-manager`, `game` etc) and then maybe split them up/specify those later, if needed.

**Comment by travankor** [comment]
Is there a consensus to have every package tagged?

**Comment by flexibeast** [comment]
i'd be interested in the opinions of @void-linux/pkg-committers on this.

**Comment by Vaelatern** [comment]
We have tags. I don't know what they'd get us that descriptions and pkgnames don't.

**Comment by ericonr** [comment]
As a simple example, a search for "game" doesn't give me `xonotic`. I don't think this justifies the whole endeavor, but it's an example, I think.

**Comment by Vaelatern** [comment]
Then I imagine the following guidance.

If you think your package should show up in a search, but the search term isn't in the package name or description, then feel free to add it as a tag.

There is no reason to tag most packages most times.

**Comment by Duncaen** [comment]
I don't think because the name or description already contains the tag would be a good reason to not use the tag.

The whole idea is to have a standardized set of tags to help without categorizing packages so you can discover new packages without vague search terms that might not be part of the description.

**Comment by Vaelatern** [comment]
So you are in favor of a tagging effort, Duncaen?

**Comment by pullmoll** [comment]
I tend to agree with @Duncaen while I would not myself take time to work on tagging. There are certainly Void users who would like to contribute by adding tags to a list of packages.

Perhaps such a list can be established as a shared document which everyone can edit, or as a file in a separate repository where PRs can be submitted to add or modify entries for the per package tag list.

I only fear the noise that generates in my mailbox :)

**Comment by leahneukirchen** [comment]
I'd recommend looking at Debian for an idea of a taxonomy instead of starting from scratch.

**Comment by anddam** [comment]
> There is no reason to tag most packages most times.

I do agree with the loose tagging system this seems to hint at, where a maintainer can add a tag but not every package needs to have at least one, even less a _primary_ one.

I figure every rigid taxonomy scheme is bound to find its platypus at some point in the future, you just cannot see it now. With a loose tagging you apply two or three tags, no priority there, and you are done.

Just my two eurocents.

**Comment by motorto** [comment]
So I took a look at the [Debian tagging system](https://packages.debian.org/about/debtags) as recommended by @leahneukirchen  and this are the ones they use: 

<details>
    <summary><u>Debian Tag System</u> (<i>click to expand</i>)</summary>
    

* accessibility
* admin
* biology
* culture
* devel
* field
* game
* hardware
* implemented-in
* interface
* iso15924
* junior
* made-of
* mail
* network
* office
* privacy
* protocol
* role
* science
* scope
* security
* sound
* special
* suite
* system
* uitoolkit
* use
* web
* works-with
* works-with-format
* x11

</details>

I took some inspiration and created this tag system that I found that is the best one but still leaves some cases behind like for example where should linux-kernel be tagged as ? (maybe a kernel tag):

<details>
    <summary><u>Proposed Tag System</u> (<i>click to expand</i>)</summary>
    

* accessibility - Accessibility Support
* admin - System Administration
* devel - Software Development
* field/science - maybe one for every field type 
	* astronomy 
	* aviation
	* biology 
	* computer science
	* mathematics 
* game - for games 
* hardware - for hardware drivers 
* junior - apps recommended for young users 
* mail - electronic mail
* network - networking (maybe a field/science type ...)
* office - for office apps
* sound/music - for music apps or sound ones (does pipewire/alsa belong here ??)
* Desktop Environment: 
	* KDE
	* GNOME 
	* XFCE 
	* etc
* X11/Wayland

</details>

What do you guys think ?

**Comment by tibequadorian** [comment]
I think tags like biology, astronomy are not that important.

Tags could also be useful for things like audio plugins where there are LV2, LADSPA, DSSI, VST... plugins which could be tagged as such.

**Comment by motorto** [comment]
I was trying to be the most future proof possible :) 

But I think the best way to discuss this isn't on a pr. It seems hard to
get a consensus this way.

Maybe a file with a super small subset of tags where people can push
Pr's with new tags (with a reason) as needed and get merged if the void
team found necessary ... 

But this would obligate the xlint to force the use of tags on all
templates and eventually as the package gets update all packages
on the repo would have a tag

**Comment by Anachron** [comment]
I agree that we dont need subtags for Science and alike (for now).

I would put DEs and WMs together maybe as "desktop-ui".

Build options are imo not a good fit for tags, because they are... optional.

Also tags shouldnt be enforced or we either end up with a ton more PRs that await moderation or the quality is lacking.

While I can see the use of tags,  it has to be done correctly to give any value.
