### ISSUE TITLE
Package request: Linux-ck

### ISSUE THREAD

**Issue by RoundDuckKira** [void-linux/void-packages#22229]
I really want to see more alternative kernels in the repos, and Linux-ck is one I want to see in particular. It brings in a much more reactive Linux kernel that doesn't lag up the system as much in the chase of throughput. I don't have the expertise to bring in this package myself so that's why I'm requesting it.

https://aur.archlinux.org/linux-ck.git
http://ck.kolivas.org/patches/

**Comment by sgn** [comment]
EWONTFIX  See https://github.com/void-linux/void-packages/issues/14062
