### ISSUE TITLE
FreeCAD crashing

### ISSUE THREAD

**Issue by groundstack** [void-linux/void-packages#22261]
### System

* xuname:  
 Void 5.4.42_1 x86_64-musl GenuineIntel uptodate rFFFFF

* package:  
 freecad-0.18.4_5

### Expected behavior
Show Draft or Arch workbenches

### Actual behavior
Segfault
### Steps to reproduce the behavior
Open FreeCAD and select Draft or Arch workbench

When launched from command line I see this:

FreeCAD 0.18.4, Libs: 0.18.4R5_voidlinux
© Juergen Riegel, Werner Mayer, Yorik van Havre 2001-2019

Cannot find icon: Draft_Line
Cannot find icon: Draft_Wire
Cannot find icon: Draft_Circle
Cannot find icon: Draft_Arc
Cannot find icon: Draft_Ellipse
Cannot find icon: Draft_Polygon
Cannot find icon: Draft_Rectangle
Program received signal SIGSEGV, Segmentation fault.

**Comment by sburris0** [comment]
Confirmed on clean FreeCAD configuration.
Here's a solved issue from a Gentoo ebuild repo with the same thing happening: https://github.com/waebbl/waebbl-gentoo/issues/218

**Comment by yopito** [comment]
far from home. I'll try to fix it ASAP

**Comment by yopito** [comment]
here it is. sorry for delay and thanks @sburris0 for pointing the fix.
