### ISSUE TITLE
Virtualbox: fix for i686 or clean up from repo

### ISSUE THREAD

**Issue by AngryPhantom** [void-linux/void-packages#22282]
### System
Void Linux i686 XFCE, updated, up and running. Free and non-free repos enabled.

* xuname:  
Void 5.4.42_1 i686 AuthenticAMD uptodate rrFFF

* package:  
virtualbox-ose

### Expected behavior
Should install VirtualBox

### Actual behavior
```
user@host: sudo xbps-install virtualbox-ose
MISSING: virtualbox-ose-dkms-5.2.2_2
Transaction aborted due to unresolved dependencies.
```
Ok, let's install the dependency:
```
user@host: sudo xbps-install virtualbox-ose virtualbox-ose-dkms 
MISSING: virtualbox-ose-dkms-5.2.2_2
Transaction aborted due to unresolved dependencies.
```
Okay, let's install the whole bunch:
```
user@host: sudo xbps-install virtualbox-ose virtualbox-ose-dkms virtualbox-ose-guest virtualbox-ose-guest-dkms 
MISSING: virtualbox-ose-dkms-5.2.2_2
Transaction aborted due to unresolved dependencies.
```

Am I missing something, guys? :)

P.S. **virtualbox** and its **dkms** packages are of different versions. Can it be fixed please?

**Comment by Anachron** [comment]
Install virtualbox-ose-dkms first?

**Comment by ericonr** [comment]
This package was updated, so it can't download the `5.2.2_2` version because it doesn't exist anymore. You have to update your package index with `xbps-install -S` first. I'd do an update as well.

**Comment by AngryPhantom** [comment]
@Anachron 
 Yes it can be installed but the very VirtualBox package is outdated. There is a dependency problem.
Probably I have to change the title somehow...
That's what I see in the repo. Check out the versions:

```
[-] virtualbox-ose-5.2.2_2
[*] virtualbox-ose-dkms-6.1.8_1
[-] virtualbox-ose-guest-5.2.2_2
[-] virtualbox-ose-guest-dkms-6.1.8_1
```

So, it's quite logical that when I try to install virtualbox-ose afterwards I get this again:

```
MISSING: virtualbox-ose-dkms-5.2.2_2
Transaction aborted due to unresolved dependencies.
```

It's really strange that virtualbox and its dkms packages are of different versions and how did they get into the repo...

**Comment by AngryPhantom** [comment]
@ericonr 

My system is up to date. Still see this:

```
[-] virtualbox-ose-5.2.2_2
[*] virtualbox-ose-dkms-6.1.8_1
[-] virtualbox-ose-guest-5.2.2_2
[-] virtualbox-ose-guest-dkms-6.1.8_1
```

**Comment by AngryPhantom** [comment]
Ok, I can see that 32-bit is somehow [dropped](https://raw.githubusercontent.com/void-linux/void-packages/master/srcpkgs/virtualbox-ose/template)?

**Comment by ericonr** [comment]
Yeah, seems to be the case. Looking into why. The package should probably removed from the repos, if that's the case.

**Comment by AngryPhantom** [comment]
@ericonr 
Yeah... Well, anyway, I managed to install it from their official .run file. There were some errors like systemct is missing etc., but it works :)

Thanks. Dunno if I should close the issue or not.

P.S. Do you guys know what's in the plans? Should I really think of moving my PCs and servers to x86_64?

**Comment by ericonr** [comment]
Probably? It's really the way moving forward. It was broken in commit 6428dfff, perhaps it's been fixed upstream since then. You could try building it locally to see if it works.

**Comment by AngryPhantom** [comment]
@ericonr 
Ok, thank you. Will try to build and move to x86_64 then. Cheers.

**Comment by ericonr** [comment]
Can you reopen the issue, please? If it's indeed broken, it needs to be cleaned from the repo.

**Comment by AngryPhantom** [comment]
Sorry. Done.

**Comment by ericonr** [comment]
No problem, thanks :)

**Comment by AngryPhantom** [comment]
@ericonr 
So, I've installed on another 64-bit machine all four packages successfully and without errors:
```
virtualbox-ose-6.1.8_1
virtualbox-ose-dkms-6.1.8_1
virtualbox-ose-guest-6.1.8_1
virtualbox-ose-guest-dkms-6.1.8_1
```
Log is [here](https://pastebin.com/raw/c3P61xGw).

Even followed the guide [here](https://wiki.voidlinux.org/VirtualBox) (I have dbus running and also added vboxservice), but:

1) Keep getting errors like desktop [notification](http://0x0.st/ipVg.png) that VBoxClient: kernel service is not running. Exiting. Even rebooted but still see modules loading errors at boot (vboxguest and vboxsf).

2) And where should I find the extensions package (the one you install in VB settings)? Should I download it from the official site?

I'm at a loss a bit :)

**Comment by AngryPhantom** [comment]
@ericonr 
My bad... I've installed two unneeded packages. I've edited my previous message.

**Comment by ericonr** [comment]
@AngryPhantom glad it worked! Can you change the name of the issue to "Virtualbox: fix for i686 or clean up from repo", please? That way people can know what it's about in a glance. I don't have much experience with their build system, so I'm not sure what I'd have to change for it.

**Comment by Chocimier** [comment]
Moved to aggregate issue.
