### ISSUE TITLE
Some dkms modules don't get updated. A little help needed.

### ISSUE THREAD

**Issue by AngryPhantom** [void-linux/void-packages#22307]
# System
Void Linux x86_64, updated, up and running

* xuname: Void 5.4.4**1**_1 x86_64 AuthenticAMD uptodate rrFFF
and
* xuname: Void 5.4.4**2**_1 x86_64 AuthenticAMD uptodate rrFFF

* packages: Recent kernels?

### Steps to reproduce the behavior
I've got two USB WiFi adapters (TL-WN722N and D-Link DWA-131) and I use the github drivers for them since the stock ones are unstable and sometime do not work at all almost in all distros. The [first one](https://github.com/aircrack-ng/rtl8188eus) for TL-WN722N is being compiled with a **dkms-install.sh** script and the module is placed in /lib/modules/5.4.4x_y/updates/.
While the [second one](https://github.com/Mange/rtl8192eu-linux-driver) is installed with a **dkms add .** method (not sure if it differs a lot) and the module is placed in /lib/modules/5.4.42_1/kernel/drivers/net/wireless/realtek/ (as it is defined in the dkms.conf of the driver install config).

The problem is that upon kernel update the driver for TL-WN722N (placed in /lib/modules/5.4.4x_y/updates/) **is updated** by the dkms, while the second one for D-Link DWA-131 (placed in /lib/modules/5.4.42_1/kernel/drivers/net/wireless/realtek/) **is not**.

The thing is that in Debian **both** drivers are placed in /lib/modules/4.19.0-9-amd64/updates/dkms/ and are updated without issues upon every kernel update.

### Expected behavior
Should be updated (?)

Please, help me figure this out. What should be done? Do I have to contact the author of the second driver to make some changes or is there some another way out since in Debian it works OK?

Thank you in advance.

**Comment by ericonr** [comment]
Could you take a look at how the `zfs` and `nvidia` packages configure DKMS? I believe they add themselves and their `dkms.conf` to `/usr/src/<package-name>`. You can check which files are inside a package with `xbps-query -Rf zfs`.

**Comment by AngryPhantom** [comment]
@ericonr 
**nvidia** is placed in /lib/modules/5.4.42_1/kernel/drivers/video and is updated upon kernel updates as well. Dunno about **zfs**, I don't use it, but I guess it is also updated without problems since it comes from Void repos and is properly packaged.
What I'm dealing with here is an issue with [D-Link DWA-131](https://github.com/Mange/rtl8192eu-linux-driver) WiFi USB driver. I just don't know how to force **dkms** make updates every time.

**Comment by ericonr** [comment]
The source as well as the `dkms.conf` files for each? Cause for `nvidia-dkms` it looks like that's all that's needed for it to work.

**Comment by AngryPhantom** [comment]
@ericonr 
Yes, [here](http://0x0.st/ipFJ.png) it is.

**Comment by ericonr** [comment]
that's as far as my knowledge goes. You can try to generate a dracut image and turn on its debugging options to see if it at least knows your driver is there.

**Comment by AngryPhantom** [comment]
Oddly, new 5.4.43_1 kernel updated all my wifi modules. Probably I did something wrong before, I'm not sure. Anyway, I'm closing the issue in order to bother the dev team.
Sorry and thank you for the awesome Void Linux. Keep up the good work!

**Comment by ericonr** [comment]
No problem! Glad it worked out :D
