### ISSUE TITLE
Bookworm

### ISSUE THREAD

**Issue by basiliscoazu** [void-linux/void-packages#22303]
### System

* xuname:  
  *Void 5.6.14_1 x86_64 AuthenticAMD uptodate rrrmFFFF*
* package:  
  *bookworm-1.1.2_3*

### Expected behavior
Work.
### Actual behavior
Dont work
### Steps to reproduce the behavior
[~]$ bookworm
bash: bookworm: orden no encontrada

I'm sorry if that's not how the practice works.
I did a post on rredit and they encouraged me to do it here.
It seems that after that post there was an update of bookwornm and from that date it no longer works.

**Comment by anjandev** [comment]
@basiliscoazu Hi. Bookworm works, it's just the name of the command is not `bookworm`. Try typing `com.github.babluboy.bookworm` into your terminal.

Sometimes the name of the package != the name of the binary. To check what's the name of the binary, run `xbps-query -f <pkgname> | grep bin`.

In this case, I ran and go the following output in my command window:

```
anjan@navi ~> xbps-query -f bookworm | grep bin
/usr/bin/com.github.babluboy.bookworm
```

Cheers!

**Comment by basiliscoazu** [comment]
Thank you. very much,
