### ISSUE TITLE
xlint: homepage should not use variables on CI vs no error when locally ran

### ISSUE THREAD

**Issue by anjandev** [void-linux/void-packages#22339]
### System

* xuname:  
Void 5.6.14_1 x86_64 AuthenticAMD notuptodate rFFFFFFFF

* package:  
  * xtools-0.58_1

### Expected behavior
In my package template, I put the homepage as:
```
homepage="http://www.gnu.org/software/${pkgname}"
```

Running xlint on this file, I should get the same output as the build travis CI check on github.

### Actual behavior

xlint returns no errors. However, Travis returns the following error:
```
Linting srcpkgs/guile/template...
srcpkgs/guile/template:13: homepage should not use variables
```

### Steps to reproduce the behavior
Make a template with a homepage with variables in the homepage variable

Ie. xlint the guile template on your local machine vs. run the CI check on github.

**Comment by ericonr** [comment]
This happens because Travis is using the master branch of xtools instead of a release.

**Comment by ahesford** [comment]
Travis CI fetches the head of the `master` branch of `xtools`. The `xlint` behavior change was committed on May 6. Since no release has been made since that change, the version of `xlint` in the `void-packages` repo is behind.

**Comment by anjandev** [comment]
Ah, I see. Should a release be made soon?

**Comment by ahesford** [comment]
That's up to @leahneukirchen, maintainer of `xtools`.

**Comment by anjandev** [comment]
I see. Maybe I will make a local `xtools-git` template for xtools.

Thanks guys.

**Comment by ericonr** [comment]
I think we can close this one, right?

**Comment by anjandev** [comment]
> I think we can close this one, right?

I didn't want to close because this issue might signal that a new
release of xtools should be made. If the maintainers believe this issue
should be closed, go ahead.

**Comment by leahneukirchen** [comment]
Can do later.

**Comment by leahneukirchen** [comment]
Done in ff0d24a10f.
