### ISSUE TITLE
zfs is including dkms.patch in the package

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#22347]
### System

* xuname: Void 5.6.14_1 x86_64 GenuineIntel notuptodate rrFFFFFFFFFFFFFFFF
* package: zfs-0.8.4_1

### Expected behavior

Files from the patch folder shouldn't be packaged.

### Actual behavior

The zfs package contains the file `dkms.patch`.

### Steps to reproduce the behavior

    xbps-query -Rf zfs | grep "dkms\.patch"

@Vaelatern

**Comment by ahesford** [comment]
#23013

**Comment by ericonr** [comment]
Wee closed
