### ISSUE TITLE
Remove protobuf{18,22} packages from repo

### ISSUE THREAD

**Issue by ahesford** [void-linux/void-packages#22381]
The following packages were removed from `void-packages` in #22175 and should be removed from the repository as well:

- [ ] libprotobuf18
- [ ] libprotobuf18-lite
- [ ] libprotobuf22
- [ ] libprotobuf22-lite
- [ ] libprotoc18
- [ ] libprotoc18-devel
- [ ] libprotoc22
- [ ] protobuf18
- [ ] protobuf18-devel
- [ ] protobuf18-lite

**Comment by ericonr** [comment]
Please move these over to #23575
