### ISSUE TITLE
Clean up repositories to save builders' time (mostly arm)

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#22393]
I'm opening this issue on @sgn 's behalf, from PR #22192 

> Here's the list of packages, all packages are broken in armv[567], except noted:

* Uranium (nocross)
* WoeUSB
* akonadi-calendar
* akonadi-import-wizard
* akregator
* calendarsupport
* cura (nocross)
* eventviews
* falkon
* firefox-esr-i18n (armv[56] + ppc32)
* firefox-i18n (armv[56] + ppc32)
* flowblade
* incidenceeditor
* kalarm
* kmail-account-wizard
* kmailtransport
* korganizer
* libksieve
* mailcommon
* messagelib
* perl-Cairo (nocross)
* perl-Gtk3-SimpleList (nocross)
* pim-data-exporter
* python3-trimesh (nocross)
* qmk (nocross)
* yarn-bin
* yarn

Since armv5 is mentioned, I guess this is relevant for @pullmoll too? Possibly @q66 as well for firefox-i18n stuff.

**Comment by sgn** [comment]
* youtube-viewer

**Comment by sgn** [comment]
Moved to #23575
