### ISSUE TITLE
Azote tries to use python3.6 directory and fails

### ISSUE THREAD

**Issue by PaperMountainStudio** [void-linux/void-packages#22403]
### System

* xuname:  
  *Void 5.6.14_1 x86_64 GenuineIntel notuptodate rrrmDFFFFFFFFFFFFFFFFF*
* package:  
  *azote 1.7.7*

### Expected behavior
runs

### Actual behavior
```
/bin/azote: line 3: cd: /usr/lib/python3.6/site-packages/azote: No such file or directory
/usr/bin/python3: can't open file 'main.py': [Errno 2] No such file or directory
```

### Steps to reproduce the behavior
```
xbps-install -S azote
azote
```

There is a wrapper script specific to void in `[/usr]/bin/azote` which calls azote from `/usr/lib/python3.6/site-packages/azote` location, but it is in `/usr/lib/python3.8/site-packages/azote`.

ping @nwg-piotr

**Comment by nwg-piotr** [comment]
Sorry, I changed my development machine some time ago and have not yet installed Void on it. Thanks for reporting, I'll take care of it this weekend.

**Comment by nwg-piotr** [comment]
#22455

**Comment by PaperMountainStudio** [comment]
thanks
