### ISSUE TITLE
xmonad-contrib: empty package

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#22466]
### System

* xuname:  
  `Void 5.4.43_1 x86_64 AuthenticAMD uptodate rrrdFFFFFFF`
* package:  
  `xmonad-contrib`

### Expected behavior
Should contain a binary or anything at all.

### Actual behavior
Contains just the BSD-3-clause style `LICENSE`.

### Steps to reproduce the behavior

`xbps-query -Rf xmonad-contrib`

I saw this when testing the updated `stack-2.3.1` results.

It could be a problem with `build_style="haskell-stack"` or perhaps with `stack install` which according to the log does nothing. I have no clue what's wrong here.

**Comment by sgn** [comment]
I wonder if we should update `pkglint`'s empty check to check for package has nothing except a LICENSE file.

**Comment by Chocimier** [comment]
qrcodegen has nothing but license too.
