### ISSUE TITLE
Helvetica shouldn't be a bitmap font provided by xorg-fonts-75dpi

### ISSUE THREAD

**Issue by sburris0** [void-linux/void-packages#22477]
### System

* xuname:  
Void 5.4.43_1 x86_64 AuthenticAMD uptodate rrmFF
* package:  
firefox
xorg-fonts

### Expected behavior
Fonts in Firefox should look nice

### Actual behavior
Pages such as https://github.com/void-linux/void-packages have jagged, ugly fonts everywhere.

### Steps to reproduce the behavior
1. Install a font package
2. Open Firefox to a page such as this

### Fix
I found this fix on r/voidlinux: https://www.reddit.com/r/voidlinux/comments/fa9wyk/solution_for_non_antialiased_fonts_in_firefox_and/

The solution is to symlink fontconfig config files then update the font cache.

```
ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/70-no-bitmaps.conf
fc-cache -fv
```

The issue explained on arch wiki, in the context of PDFs: https://wiki.archlinux.org/index.php/Font_configuration#Helvetica_font_problem_in_generated_PDFs

I think that if this can't be fixed with a `post_install()` in a package, then a message following installation or a mention in the handbook would be helpful.

**Comment by abenson** [comment]
I think this should be documented in the handbook.

**Comment by ericonr** [comment]
Oh that's what happened when I installed `xorg-fonts`. I think there should be a `xbps-reconfigure` hook for fonts, would prefer to use that for the config step.

**Comment by nolbap** [comment]
I'm having the same problem on firefox, and disabling bitmap fonts doesn't work for me cause I use terminus fonts for a lot of things, any idea on how could I solve this?

**Comment by georgianfire** [comment]
> I'm having the same problem on firefox, and disabling bitmap fonts doesn't work for me cause I use terminus fonts for a lot of things, any idea on how could I solve this?

The solution here helped me fix the issue on firefox
https://www.reddit.com/r/voidlinux/comments/bcg34x/just_moved_to_void/ekqdh32/

**Comment by StreetStrider** [comment]
I had this issue after each Void system update.
This is what helped me: https://www.reddit.com/r/voidlinux/comments/fa9wyk/solution_for_non_antialiased_fonts_in_firefox_and/
```
ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/70-no-bitmaps.conf
fc-cache -fv
```
