### ISSUE TITLE
Manual question: Quality requirements

### ISSUE THREAD

**Issue by LennyPenny** [void-linux/void-packages#22532]
Hey, 
I want to contribute a package (namely for https://github.com/IBBoard/cawbird)

I started to read the manual to learn how to create a void linux package, but then I stumbled upon the `Quality requirements` section. https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements

I have a few questions as to what is needed to fulfill these. 

1. `System` What kind of software "should" be installed system wide? Another twitter client, choqok, is a package, but could just as well be installed per user. 

2. `Compiled` The software I want to contribute can be compiled, but there also builds from the authors. Does this mean that this requirement is not met?

3. ` Required` The software I want to package is not required by anything, it's an application that you may, or may not use (like the firefox, or choqok packages for example). Lots of packages in void-packages are of that kind. Is this requirement still used?

**Comment by Johnnynator** [comment]
These requirements are independent from each other, and at least 1 of them should be fulfilled.

2. `cawbird` would already fulfill the `compiled` requirement. The requirement comes down that something isn't written in a purely interpreted language or is just a set of backgrounds for your Desktop. That upstream provides some set of binaries doesn't matter, well of them only faltpak would work, but that not for all of our supported architectures.

**Comment by LennyPenny** [comment]
Okay thanks, I just assumed that all would have to be met
