### ISSUE TITLE
IWD doesn't have an ead service

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#22589]
### System

* xuname:  Void 5.6.15_1 x86_64 GenuineIntel notuptodate rrrrmmnFFFFFFFFFFFFFFFFFFF
* package:  iwd-1.7_1

### Expected behavior

IWD should have a service for `ead` (ethernet authentication daemon). https://git.kernel.org/pub/scm/network/wireless/iwd.git/tree/wired/ead.rst

### Actual behavior

There isn't one, even though the executable itself is there in `/usr/libexec/ead`.

---

I can try to get the service going, just making an Issue to track it.

**Comment by abenson** [comment]
Shouldn't this be called and managed by `iwd` itself? Not a separate service?

**Comment by ericonr** [comment]
According to the README, I don't think so:
```
--enable-wired

		Enable installation of Ethernet authentication daemon

		This allows enabling the Ethernet daemon binary ead which
		is then placed into --libexecdir directory.

		With this option the support for 802.1x for wired Ethernet
		connections can be enabled. It provides its own D-Bus
		policy and systemd configuration.
```

**Comment by ericonr** [comment]
Confirmed the need for a service with upstream
