### ISSUE TITLE
mate-terminal fails to run 

### ISSUE THREAD

**Issue by maxice8** [void-linux/void-packages#226]
### System

* xuname:  
  Void 4.16.14_1 x86_64 GenuineIntel uptodate rFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
* package:  
  mate-terminal-1.20.1_2

### Expected behavior

mate terminal runs

### Actual behavior

$ mate-terminal                                                                                                   ~

(mate-terminal:3562): GLib-GIO-ERROR **: 17:24:38.760: Settings schema 'org.mate.interface' is not installed

fish: “mate-terminal” terminated by signal SIGTRAP (Trace or breakpoint trap)

### Steps to reproduce the behavior

- Install mate-terminal
- Run it

**Comment by Johnnynator** [comment]
The solution is in the error message. It need `mate-desktop`.
