### ISSUE TITLE
Missing obstack symbols for arduino-cli binaries on musl

### ISSUE THREAD

**Issue by kqo** [void-linux/void-packages#22616]
### System

* xuname:
  * Void 5.6.2 x86_64-musl GenuineIntel uptodate rrFFFF
* package:
  * arduino-cli
  * gcompat
  * musl-obstack

### Expected behavior

Binaries pulled in by `arduino-cli` which are linked against `glibc` should hopefully work on musl after #22237 (which fixed other missing symbols, thank you for that!).

### Actual behavior

The `arm-none-eabi-g++` binary pulled in by the `arduino:sam` core is still missing symbols from obstack, namely:

```
Error relocating [...]/arduino/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-g++: _obstack_newchunk: symbol not found
Error relocating [...]/arduino/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-g++: obstack_free: symbol not found
Error relocating [...]/arduino/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-g++: _obstack_begin: symbol not found
Error relocating [...]/arduino/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-g++: _obstack_memory_used: symbol not found
```

`gcompat` seems to support building with `musl-obstack`, so I [tried enabling support](https://github.com/void-linux/void-packages/compare/master...kqo:gcompat-arduino) in the template. I can see that `musl-obstack` gets linked in with `-lobstack`, but the binary still can't find the symbols, nor can I with `nm`.

I'm really out of my depth with this, so I'm not sure if this is a `gcompat` problem, something I'm doing wrong with `xbps`, or if I'm just misunderstanding how things are supposed to work.

### Steps to reproduce the behavior

This will bump into the binary needing obstack symbols:
```
$ arduino-cli core update-index
$ arduino-cli core install arduino:sam
$ arduino-cli sketch new test_sketch
$ arduino-cli compile test_sketch --fqbn arduino:sam:arduino_due_x_dbg
```

It's probably quicker to run:
```
$ LD_PRELOAD=/usr/lib/libgcompat.so.0 ldd ~/.local/share/arduino/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-g++
```

**Comment by ericonr** [comment]
Did this ever work for you? If you desperately need arduino stuff, you can try to use it from a glibc chroot or through flatpak, both of which should work fine.

I only ever used the AVR core, so I hadn't hit this issue. I can try to do some testing on it later.

**Comment by kqo** [comment]
No, I've not had the ARM core working on musl before. Thanks for the chroot/flatpack tip, I was going to try patchelf but your ways sound easier.

Thank you for looking into this.

**Comment by ericonr** [comment]
There is a chance this is a `gcompat` limitation. I tried the fix you suggested with obstack, but it didn't work out. I will ask around a bit as well.

**Comment by ericonr** [comment]
Okay, so building `musl-obstack` with dynamic libs enabled and `nostrip=yes`, I can `LD_PRELOAD=/usr/lib/libobstack.so` and not get the obstack errors. But then we are missing the `__strftime_1` symbol.

**Comment by ericonr** [comment]
https://www.openwall.com/lists/musl/2019/05/08/2 so that last error is an error from musl, actually. They should have exported the symbol but didn't.

**Comment by ericonr** [comment]
@kqo very kludgy fix:

- build `musl-obstack` from #22627 
- build a shared library to provide `__strftime_l`. Contents of `main.c`:
```
#include <time.h>

size_t __strftime_l (char *  __restrict a, size_t b, const char *  __restrict c, const struct tm *  __restrict d, locale_t e)
{
	strftime_l(a, b, c, d, e);
}
```
Compile with:
```
gcc -o main.so main.c -shared
```

-  launch `arduino-cli` with a few overloads: `LD_PRELOAD=/usr/lib/libobstack.so:/path/to/main.so arduino-cli compile ...`

**Comment by kqo** [comment]
Thank you again for taking a look at this, your kludgy fix works perfectly.

**Comment by ericonr** [comment]
yay! I think we should leave this one open until it works out of the box (no idea how to proceed with it for now)

**Comment by ericonr** [comment]
@kqo I have a PR to fix it now, it's in #23432

**Comment by 4ntoine** [comment]
I'm still having it (seems to) on alpine-virt with gcompat:
```
asvm-x86-64:~/myapp/bin# ./arduino-cli compile --fqbn "esp32:esp32:nano32" ./sk1/
Error relocating /root/myapp/data/packages/esp32/tools/xtensa-esp32-elf-gcc/1.22.0-97-gc752ad5-5.2.0/bin/xtensa-esp32-elf-g++: obstack_free: symbol not found

Error during build: exit status 127
```

is there any oob solution?

**Comment by Johnnynator** [comment]
First thing, we aren't Alpine, we are Void, so this repo isn't really correct.
But either way the issue is, that musl-obstack doesn't export a `obstack_free` function, only `_obstack_free`.

https://github.com/void-linux/musl-obstack Would be the upstream for `musl-obstack` for both Alpine and Void, you can open an isue there.

**Comment by Johnnynator** [comment]
https://github.com/void-linux/musl-obstack/pull/6

**Comment by 4ntoine** [comment]
@Johnnynator Thanks a lot for your answers! I will definitely look in void-linux distro whether this issue is solved oob to jusut use it instead of alpine.
