### ISSUE TITLE
Notepadqq doesn't open

### ISSUE THREAD

**Issue by glats** [void-linux/void-packages#22628]
### System

* Void 5.4.44_1 x86_64-musl GenuineIntel uptodate rrnFF
* notepadqq-1.4.8_1

### Expected behavior
Open notepadqq to edit files
### Actual behavior
Show an error whiles it's opening.
### Steps to reproduce the behavior
Install notepadqq from the repos
```glats@raphael ~> doas xbps-install notepadqq```
runing:
```
glats@raphael ~> notepadqq
propsReply "Method \"GetAll\" with signature \"s\" on interface \"org.freedesktop.DBus.Properties\" doesn't exist\n"
nmReply "Method \"GetDevices\" with signature \"\" on interface \"org.freedesktop.NetworkManager\" doesn't exist\n"
"Object path cannot be empty"
Error compiling builtin: 
Fatal error compiling builtin function 'apply': fish: 'notepadqq' terminated by signal SIGSEGV (Address boundary error)
```
### Aditonial information
```glats@raphael ~> strace notepadqq``` [strace.txt](http://ix.io/2oov)
```glats@raphael ~> QT_DEBUG_PLUGINS=1 notepadqq ```[debug.txt](http://ix.io/2oow)
I'm using connman instead of networkmanager
Im runing dbus and elogind
```
glats@raphael ~> ls /var/run/runit/runsvdir/current/
agetty-tty1@  agetty-tty3@  agetty-tty5@  connmand@  elogind@    sddm@          sshd@
agetty-tty2@  agetty-tty4@  agetty-tty6@  dbus@      nanoklogd@  socklog-unix@  udevd@
```

**Comment by glats** [comment]
Related: https://github.com/qtwebkit/qtwebkit/issues/708

**Comment by ericonr** [comment]
I couldn't reproduce this... Are you running your WM under DBus? `dbus-run-session i3`, for example.

**Comment by glats** [comment]
The latest version works fine. I think we can close this issue.
