### ISSUE TITLE
gtk+3 build fails (due to gtk-doc => python3?)

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#2268]
I don't know since when this happens. Probably since the update of gtk-doc to 1.29 and python3 a61cd85c38e730eaed109d1f16e514fe22f8b4b2.
A couple of days ago I successfully built gtk+3.
```
Traceback (most recent call last):
  File "/usr/bin/gtkdoc-rebase", line 28, in <module>
    from gtkdoc import common, config, rebase
  File "/usr/share/gtk-doc/python/gtkdoc/rebase.py", line 49
    print(*msg)
          ^
SyntaxError: invalid syntax
make[4]: *** [Makefile:1058: install-data-local] Error 1
make[4]: Leaving directory '/builddir/gtk+-3.22.30/docs/reference/gdk'
make[3]: *** [Makefile:801: install-am] Error 2
make[3]: Leaving directory '/builddir/gtk+-3.22.30/docs/reference/gdk'
make[2]: *** [Makefile:547: install-recursive] Error 1
make[2]: Leaving directory '/builddir/gtk+-3.22.30/docs/reference'
make[1]: *** [Makefile:549: install-recursive] Error 1
make[1]: Leaving directory '/builddir/gtk+-3.22.30/docs'
make: *** [Makefile:722: install-recursive] Error 1
=> ERROR: gtk+3-3.22.30_1: do_install: '${make_cmd} DESTDIR=${DESTDIR} ${make_install_args} ${make_install_target}' exited with 2
=> ERROR:   in do_install() at common/build-style/gnu-configure.sh:38
```

**Comment by pullmoll** [comment]
I reverted gtk-doc to 1.28_3 locally and could build gtk+3 afterwards.
Should we revert the update until the issue is solved, e.g. wait for 1.29.1, or until someone finds a patch?
```
# Template file for 'gtk-doc'
pkgname=gtk-doc
reverts=1.29_1
version=1.28
revision=3
noarch=yes
build_style=gnu-configure
hostmakedepends="docbook-xsl perl pkg-config yelp-tools python"
depends="docbook-xsl libglib-devel perl python-six"
checkdepends="bc glib-devel python-mock"
short_desc="Documentation tool for public library API"
maintainer="Enno Boland <gottox@voidlinux.eu>"
license="GPL-2.0-or-later, GFDL-1.1-or-later"
homepage="http://www.gtk.org/gtk-doc/"
distfiles="${GNOME_SITE}/${pkgname}/${version}/${pkgname}-${version}.tar.xz"
checksum=911e29e302252c96128965ee1f4067d5431a88e00ad1023a8bc1d6b922af5715
```

**Comment by maxice8** [comment]
Just compiled it here with gtk-doc-1.29.

**Comment by pullmoll** [comment]
Strange kind of hiccup I suppose.
I revbumped to 1.29_2 and now it worked here too.
Closing.

**Comment by chneukirchen** [comment]
Sounds like a python2/3 issue.

**Comment by maxice8** [comment]
On Fri, Aug 31, 2018 at 06:05:21AM -0700, Leah Neukirchen wrote:
> Sounds like a python2/3 issue.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/2268#issuecomment-417657795

gtk-doc-1.29 switched to python3 and dropped python-six, was a really weird hiccup pullmoll had since i didn't have any problems compiling gtk+3

**Comment by Hoshpak** [comment]
I encountered the same issue while building a lot of packages from source. The file `/usr/bin/gtkdoc-rebase` had `python2` in the shebang line for my locally built package. The most likely scenario seems to be that the `python` package was installed for another package that had it in `hostmakedepends` and the configure scripts for `gtk-doc` decided to use the older version instead. The package in the repository correctly lists `python3` in the shebang line so it won't cause any issues when building with repository packages. It should be possible to explicitely define the `PYTHON` environment variable to make sure it always uses the correct version when building `gtk-doc`.

**Comment by pullmoll** [comment]
@Hoshpak that sounds very reasonable and would explain why rebuilding gtk-doc *magically* got me rid of the problem. I hadn't looked into the gtkdoc-rebase script but since gtk-doc was built in a (long) row of packages, the scenario you described is most probably what happened here.
