### ISSUE TITLE
haproxy-2.1.5_2 segfaults 

### ISSUE THREAD

**Issue by ii8** [void-linux/void-packages#22684]
### System

* xuname:  
  Void 5.4.44_1 x86_64-musl GenuineIntel/VM uptodate rF
* package:  
 haproxy-2.1.5_2

### Expected behavior
  haproxy works

### Actual behavior
  haproxy will always segfault

### Steps to reproduce the behavior
I have the following configuration in `/etc/haproxy/haproxy.cfg`
```
global
  chroot /var/lib/haproxy
  user haproxy
  group haproxy
  tune.ssl.default-dh-param 2048

defaults
  mode http
  timeout connect 5000ms
  timeout client 50000ms
  timeout server 50000ms
```
With frontends and backends in the config the same thing still happens.

Run haproxy like this, with or without sudo:
```
[me@host ~]$ sudo haproxy -f /etc/haproxy/haproxy.cfg 
Segmentation fault
```

**Comment by sgn** [comment]
Please test #22686
