### ISSUE TITLE
Package request: Zettlr

### ISSUE THREAD

**Issue by foxmean** [void-linux/void-packages#22694]
### Zettlr [ˈset·lər]
A Markdown Editor for the 21st century

* package upstream:
    Git: https://github.com/Zettlr/Zettlr

## Features

- Available in over a dozen languages
- Tight and ever-growing **integration with your favourite reference manager** (such as Zotero or JabRef)
- **Cite with Zettlr** using `citeproc` and your existing literature database
- Four **themes and dark mode support**
- File-agnostic writing: Enjoy **full control over your own files**
- Keep all your notes and texts **in one place** — searchable and accessible
- **Code highlighting** for many languages
- Simple and beautiful **exports** with [Pandoc](https://pandoc.org/), [LaTeX](https://www.latex-project.org/), and [Textbundle](http://textbundle.org/)
- Support for state of the art knowledge management techniques (**Zettelkasten**)
- A revolutionary **search algorithm** with integrated heatmap

## Why I need it?
Because of the Support for the *Zettelkasten* technique

**Comment by georgianfire** [comment]
duplicate: https://github.com/void-linux/void-packages/issues/22146

**Comment by foxmean** [comment]
Oh my bad, so sorry
