### ISSUE TITLE
Update qt5 to 5.15.0

### ISSUE THREAD

**Issue by jkoderu-git** [void-linux/void-packages#22774]
The PKGBUILD in arch linux has some new patches for this version but I am not experienced to review the changes and do the update for void.

@Johnnynator @Duncaen

**Comment by jkoderu-git** [comment]
Thank you for the answer, even if there is a clear indication to not open issue for package updates.

I wonder why some packages are not listed in https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt, I was interested in tbb-devel, OpenSubdiv-devel and openimageio-devel but as this issue I also don't see qt5.

**Comment by Johnnynator** [comment]
Our update check isn't perfect. Qt5 should be an easy fix, but it is hard enough already to not notice a new qt release, so I never bothered fixing the check. Fixed the update check for the other packages.

**Comment by jkoderu-git** [comment]
Many thanks @Johnnynator! For the ksysguard issue too
