### ISSUE TITLE
Fix system monitor applet in ksysguard 5.19.0

### ISSUE THREAD

**Issue by jkoderu-git** [void-linux/void-packages#22802]
In plasma 5.19.0 widgets are empty and after investigating the problem there is a bug in their package. The patch to fix it is https://invent.kde.org/plasma/ksysguard/-/commit/5391f4de.patch but I get errors on applying it. I wrote it in the `patches` subdirectory.

@Johnnynator ideas? You packaged this release

**Comment by Johnnynator** [comment]
The patch is in a prefixed format `- a/ + b/` (`-Np1`), Void uses `-Np0` by default. So you either remove the prefixes from the patch or change the patch arguments in Void to `-Np1`.
