### ISSUE TITLE
Package request: kdepim-addons

### ISSUE THREAD

**Issue by ProjectMoon** [void-linux/void-packages#22805]
This is a request for the `kdepim-addons` package, which allows useful features such as seeing the KDE calendars in the task bar (with Event Calendar or any other calendar plasmoid).

Arch package example: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/kdepim-addons

**Comment by classabbyamp** [comment]
done in #30798
