### ISSUE TITLE
gettext in xbps-src

### ISSUE THREAD

**Issue by vttfreebsd** [void-linux/void-packages#22839]
Hello
The new version of enlightenment 0.24 is not "localized", mo files for other languages than english are missing.
That leaded me to try xbps-src to rebuild enlightenment and I discovered that the gettext package was not installed in the build container.
After adding gettext into the build container and rebuild, I've got a full localized package of enlightenment.
So It should be good to have gettext by default in the bootstrap packages.
Don't know whether this is a issue or a feature request ?
Thanks for reading.
vTT

**Comment by ericonr** [comment]
@q66 new makedepends for enlightenment.
