### ISSUE TITLE
imv and renameutils man pages conflict

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#22856]
imv has `imv.1`, while renameutils has `imv.1 -> icmd.1`. Would it be fine to remove the renameutils one, since it's only a symlink? I noticed it because I'm unable to access the `imv.1` man page in https://man.voidlinux.org/man1/imv.1, even when clicking the link for it.

**Comment by hippi777** [comment]
silent conflicts arent funny as well, but im not sure if this should be an issue for xbps-src or xbps-install, and i think that the former has some mechanisms that arent automatic, but im not really into these to know what...

**Comment by ericonr** [comment]
It is mostly an issue for the user. because if they install both packages one will end up overwriting the other. It also makes me unable to link the man page for `imv` to anyone, unfortunately.

**Comment by sgn** [comment]
> imv has `imv.1`, while renameutils has `imv.1 -> icmd.1`.
> Would it be fine to remove the renameutils one, since it's only a symlink?

`mdocml` can recognise `imv` in `icmd.1` **after** `makewhatis`

> I noticed it because I'm unable to access the `imv.1` man page in https://man.voidlinux.org/man1/imv.1, even when clicking the link for it.

**Comment by ericonr** [comment]
That sounds good enough to me. Will make a PR. Thanks!
