### ISSUE TITLE
How to dualboot Gentoo with void ?

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [void-linux/void-packages#22857]
I have a laptop with dual storage.  **/dev/sda** and **/dev/sdb**
/dev/sda1 is the UEFI boot partition that I created during Gentoo's installation
/dev/sda2 is where Gentoo is installed..ext4

I have partitioned /dev/sdb into one partition /dev/sdb1 ext4 mounted at '/'
Now I want to install void on /dev/sdb1 and dualboot it with Gentoo(both Gentoo and Void showing on GRUB's screen at boot) ... 
My understanding is that, All I have to do to dualboot is to choose /dev/sda when I get to the "select the disk to install the bootloader" page  during void's installation ?

**Comment by ericonr** [comment]
Hi there! Do you have access to either reddit or IRC? They tend to be better places for this sort of question c:

That said,  I'd actually recommend you have two UEFI partitions, one for each drive (if that's still possible). That way you can install the Void bootloader in the one in `sdc`, and have independent drives for each distro (though launching a Grub reconfig should make it so Gentoo and Void can be chosen in the Grub prompt).
