### ISSUE TITLE
Master pdf-editor crashes on startup

### ISSUE THREAD

**Issue by bvdeenen** [void-linux/void-packages#22869]
### System

* xuname:  
  `Void 5.4.44_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFFFF`

* package:  
  `pkgver: master-pdf-editor-5.4.38_1`

### Expected behavior
Starts up
### Actual behavior
crashes on startup
### Steps to reproduce the behavior
```
$> /opt/master-pdf-editor-5/masterpdfeditor5 
/opt/master-pdf-editor-5/masterpdfeditor5: symbol lookup error: /opt/master-pdf-editor-5/masterpdfeditor5: undefined symbol: _ZN10QMutexPool17globalInstanceGetEPKv
```

**Comment by abenson** [comment]
master-pdf-editor uses an API that was removed with a recent version of Qt5. Supposedly this has been fixed in a new version.

**Comment by Johnnynator** [comment]
Which qt5 version do you have installed?

**Comment by bvdeenen** [comment]
```
xbps-query qt5
architecture: x86_64
automatic-install: yes
filename-sha256: 38247e174ef70b1d1875a196bf5425b8be53c4795d4a14b90f0ca25412ba97f3
filename-size: 724B
homepage: https://qt.io/
install-date: 2020-06-05 17:35 CEST
installed_size: 0B
license: GPL-3.0-or-later, LGPL-3.0-or-later
maintainer: Jürgen Buchmüller <pullmoll@t-online.de>
pkgname: qt5
pkgver: qt5-5.14.2_4
replaces:
        qt5-doc<5.6.0
        qt5-quick1<5.6.0
        qt5-quick1-devel<5.6.0
        qt5-webkit<5.6.0
        qt5-webkit-devel<5.6.0
        qt5-enginio<5.7.1
        qt5-enginio-devel<5.7.1
        qt5-plugin-gtk<5.7.1
        qt5-canvas3d<5.13.0
repository: https://alpha.de.repo.voidlinux.org/current
run_depends:
        qt5-dbus>=0
        qt5-gui>=0
        qt5-core>=0
        qt5-widgets>=0
        qt5-network>=0
        qt5-xml>=0
        qt5-test>=0
        qt5-sql>=0
        qt5-concurrent>=0
        qt5-printsupport>=0
        qt5-opengl>=0
short_desc: Cross-platform application and UI framework (QT5)
source-revisions: qt5:40f7308ef9
state: installed
```

**Comment by sgn** [comment]
Do we have the right to redistribute master-pdf-editor?
I've read their license, I think we don't.

**Comment by abenson** [comment]
I think we don't either. I thought it was restricted, but I guess not?

**Comment by Johnnynator** [comment]
> You may transfer the Software to a single recipient on a permanent basis only provided that you retain no copies of the Software (including backup or archival copies) and the recipient agrees to the terms and conditions of this License  .

So yeah, once someone downloads it we need to remove it :D. I don't see anything in the license that would allow us to redistribute it.

Also this commit https://github.com/void-linux/void-packages/commit/5830ce60e922b7dced8157ededda8c995adb3bb9 should allow xbps-src to create a working package. But you need to create it locally yourself.

**Comment by Johnnynator** [comment]
It seems that some other distros also redistribute it: https://repology.org/project/master-pdf-editor/versions but e.g. Gentoo also has it set to what for us is `restricted=yes`.

**Comment by ericonr** [comment]
Has been fixed by using bundled libraries.
