### ISSUE TITLE
Mirror: The creation of a formal request.

### ISSUE THREAD

**Issue by MrLimb** [void-linux/void-packages#22889]
Greetings to the Void community!
I would like to support all of us by making a Tier 2 mirror in the Republic of Kazakhstan! I am going to discuss this question with the local FOSS community in the near future, but I still have several questions that were not found in the documentation. What conditions are required to create a repository mirror? To open a request I have to leave a Void contact (e-mail, jabber etc.) What can I mention there? What features do I have to take into account?
Sincerely, the participant and part of the Linux community of Kazakhstan!

// A duplicate of an existing tweet, I would like to support Void. //

**Comment by ericonr** [comment]
Hi there, that sounds super cool! I think the process will consist mostly of setting up the server to `rsync` stuff from one of the Tier 1 mirrors, but I don't know that much about it.

For my part, when you have it all set up, we will need a PR to add it to the mirrors list in https://github.com/void-linux/void-docs c:

**Comment by jnbr** [comment]
ping @the-maldridge

**Comment by the-maldridge** [comment]
Dunno how I didn't see this.  I'll reply in detail after work today.

**Comment by the-maldridge** [comment]
Running a mirror is pretty straightforward.  All you have to do is setup rsync and keep it reasonably up to date.  If your mirror is going to be exposed outside of your region, this should be noted in the documentation.  If your mirror is internal to your region, i.e. behind some kind of carrier NAT, then this should also be noted.

Please keep in mind that we pay bandwidth for all data sent out from the T1 mirrors.  You can respect this by only mirroring if your use case for your mirror will offset the network throughput consumed by your mirror syncing.

Closing this, but feel free to continue the discussion here.
