### ISSUE TITLE
Telegram Desktop?

### ISSUE THREAD

**Issue by dm17** [void-linux/void-packages#22892]
What happened to telegram desktop source?
https://github.com/void-linux/void-packages/tree/master/srcpkgs/telegram-desktop

It is one point release behind, and wanted to check why.

**Comment by Duncaen** [comment]
Because no one updated it yet.

**Comment by dm17** [comment]
> Because no one updated it yet.

Right, so wondering why it says "Cannot retrieve the latest commit at this time" when going to that link. For example, if I wanted to contribute the newest version :)

**Comment by Duncaen** [comment]
The repository is too big for some github features. If you open a file then github will show you the latest commit.
But not sure how this is relevant.

**Comment by dm17** [comment]
> The repository is too big for some github features. If you open a file then github will show you the latest commit (if its not too long ago).
> But not sure how this is relevant.

Thanks didn't realize that was why. Just clicked the telegram pkg in Void repo and saw that error and thought it might have been deprecated.
