### ISSUE TITLE
hardening.sh - any docs on this?

### ISSUE THREAD

**Issue by dm17** [void-linux/void-packages#22890]
I was referred to your hardening.sh for hardening Void. I guess there is no linux-hardened package on Void, but I don't know what Arch's includes or if there's a need for it on Void.
hardening.sh just applies to the package build process, correct? I'm just making this ticket for myself and others who are looking for a bit more context / docs on Void hardening.

**Comment by Vaelatern** [comment]
What hardening.sh?

**Comment by Vaelatern** [comment]
```
common/environment/install/hardening.sh
common/environment/build/hardening.sh
common/environment/patch/hardening.sh
common/environment/check/hardening.sh
common/environment/configure/hardening.sh
```
Just read them.

**Comment by dm17** [comment]
Right I'm talking about https://github.com/void-linux/void-packages/blob/master/common/environment/configure/hardening.sh they all reference. It is just a script sitting somewhere from the point of view of https://github.com/void-linux/void-packages Docs.

**Comment by Vaelatern** [comment]
Feel free to PR sample documentation if you feel it's necessary. xbps-src internals don't really have a place other than the source for such docs.

**Comment by dm17** [comment]
> Feel free to PR sample documentation if you feel it's necessary. xbps-src internals don't really have a place other than the source for such docs.

PR = peer review, correct?

**Comment by flexibeast** [comment]
@dm17: No, "Pull Request", i.e. "feel free to create a pull request that adds sample documentation".
