### ISSUE TITLE
kate pulls in kwrite

### ISSUE THREAD

**Issue by adojck** [void-linux/void-packages#22914]
### System

* xuname:  
  Void 5.4.46_1 x86_64 GenuineIntel uptodate rrrrmmnFFFF
* package:  
  `kate5-20.04.1_1`

### Expected behavior

When `kate` is installed, `kwrite` should not be installed

### Actual behavior

When I install `kate` I get `kwrite` too

### Steps to reproduce the behavior

Install `kate5`

**Comment by Johnnynator** [comment]
Strictly speaking kwrite is a component of kate, but yeah it could be split out into a sub package.

**Comment by adojck** [comment]
Well while both share Editor Component from KDE, those are still different apps. `kate` has some advanced features, while `kwrite` keeps it minimalistic. Maybe it's same codebase, but in other distros as much as I have seen it is always separate packages. It would be nice to have this on Void Linux too :)

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/89a7bc789874d1d48b8326ed90e3e94a156e987a
