### ISSUE TITLE
kscreen does not save settings between reboots

### ISSUE THREAD

**Issue by adojck** [void-linux/void-packages#22913]
### System

* xuname:  
  Void 5.4.46_1 x86_64 GenuineIntel uptodate rrrrmmnFFFF
* package:  
  `kscreen-5.19.0_1`

### Expected behavior

When I set screen ordering in `kscreen` kcm, I expect it to keep the settings

### Actual behavior

After reboot `kscreen` kcm settings for screen ordering are reset

### Steps to reproduce the behavior

Go to `kscreen` kcm (System Settings -> Display and Monitor -> Display Configuration) and drag screens to re-arrange them. Reboot the system, settings are gone (reset to default).

### Extra
I'm using `nvidia` driver for my GPU, screens are connected via DisplayPorts.

### Edit
This happens now on Arch Linux with Intel iGPU too. I guess it might be a problem within `kscreen` itself. I reported the bug to KDE: https://invent.kde.org/plasma/kscreen/-/issues/1

**Comment by karl-nilsson** [comment]
The exact same behavior happened on my system (x64, glibc, lxqt, amdgpu driver)
Reverting to qt5-5.14.2_5 fixed it.
My guess is the qt update broke kscreen.

**Comment by Johnnynator** [comment]
This issue predates 5.15. Also is lxqt actually using kscreen?

**Comment by karl-nilsson** [comment]
> Also is lxqt actually using kscreen?

Yep:
> Runtime dependencies are Xcursor, qtsvg, KScreen and liblxqt.
https://github.com/lxqt/lxqt-config

**Comment by Johnnynator** [comment]
@karl-nilsson The lxqt related issue should be resolved with 29ebf3517fd0ed5b6ce16b129b65c8075cb15ff5 

I'm aware of the issue adojck reported, but I couldn't reproduce it right now.

**Comment by karl-nilsson** [comment]
@Johnnynator that fixed my problem, thanks!
