### ISSUE TITLE
vscode packing issue

### ISSUE THREAD

**Issue by adojck** [void-linux/void-packages#22912]
### System

* xuname:  
  Void 5.4.46_1 x86_64 GenuineIntel uptodate rrrrmmnFFFF
* package:  
  vscode-1.46.0_1

### Expected behavior

When installing `vscode` package I expect to get Visual Studio Code, with Telemetry and branding

### Actual behavior

When installing `vscode` package I get `code-oss` which is stripped version of Visual Studio Code (OSS version)

### Steps to reproduce the behavior

Install `vscode` and get `code-oss` instead

**Comment by ericonr** [comment]
The `vscode` package is the only one we have. The nonfree version doesn't seem to be available as a Void package. You might want to look into Flatpak for it.

**Comment by abenson** [comment]
Void can't distribute Microsoft's enhanced version of `vscode`.

[License](https://code.visualstudio.com/License/)

> You may not 
> ...
> **share**, **publish**, rent or lease the software, or **provide the software as a stand-alone offering for others to use**.

**Comment by adojck** [comment]
Then I guess package could be renamed to keep it more clear which version it is :) Maybe I could submit one more issue, as a package request, and someone would pack the `vscode` as the `nonfree` version?

**Comment by abenson** [comment]
The policy for Void is to use the upstream name, and the repo name was chosen as `vscode`.

**Comment by adojck** [comment]
Thanks for looking into this. I close this then
