### ISSUE TITLE
temporarily include luks2 patch for grub

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#23022]
Is it possible to temporarily inlcude this patch https://savannah.gnu.org/bugs/?55093 as a patch to Void's GRUB package, so that LUKS2 support is included now, while we wait for a new release of upstream GRUB (which could be months away)?
Thanks.

**Comment by hippi777** [comment]
hi there! :)

i actually really like this idea, but if others wont like the idea enough, then u can check out this:
https://www.reddit.com/r/voidlinux/comments/eo1y08/luks2_support_in_grub/

**Comment by dkwo** [comment]
Hi, that's already useful, thanks.

>
