### ISSUE TITLE
xbps-src try to build dependency instead of pull them from remote

### ISSUE THREAD

**Issue by Eluminae** [void-linux/void-packages#23039]
Hello all,

I got a problem and questioned the irc channel.

Someone tells me to "git pull" but it did not fix my problem.

### Expected behavior

xbps-src pull pre-builded dependency when packaging things

### Actual behavior

xbps-src build dependency using local recipes

### Steps to reproduce the behavior

* git clone git@github.com:void-linux/void-packages.git
* cd void-packages
* curl http://dav.misterbanal.net/b3fb9ef3-4965-4373-988d-b93afdda4adf.1.7.patch | git am
* ./xbps-src binary-bootstrap
* ./xbps-src pkg Dwarf-Therapist

It try to build deps as qt5

Thanks by advance

**Comment by Chocimier** [comment]
What architecture do you build for?

**Comment by Eluminae** [comment]
I am on a x86_64 and I am not cross-building

**Comment by Chocimier** [comment]
qt5 just got updated and is rebuilding now. You can checkout few commits back to have same version in template as in repo.
