### ISSUE TITLE
Package request: loudgain

### ISSUE THREAD

**Issue by thenktor** [void-linux/void-packages#23054]
loudgain is a versatile ReplayGain 2.0 loudness normalizer, based on the EBU R128/ITU BS.1770 standard (-18 LUFS):
https://github.com/Moonbase59/loudgain

**Comment by motorto** [comment]
What is the license off this ,?

**Comment by flexibeast** [comment]
License is [here](https://github.com/Moonbase59/loudgain/blob/master/COPYING), in the COPYING file. Looks like [BSD 2-clause](https://opensource.org/licenses/BSD-2-Clause).

**Comment by motorto** [comment]
Thanks,

Might give this a try and package it myself

**Comment by motorto** [comment]
@thenktor could you please try the binaries and see if its working properly ?

https://github.com/motorto/void-packages/pull/1/commits/c2c898656e0aca33d2b7195ecf60e0c9cdcd0531

**Comment by motorto** [comment]
@thenktor the package as been submitted !
