### ISSUE TITLE
GNU GDB & Guile

### ISSUE THREAD

**Issue by mkohlhaas** [void-linux/void-packages#23051]
Could we support Guile in GDB?

Config option: `with-guile`

Thanks!

**Comment by mkohlhaas** [comment]
Source styling would be cool too.

`--enable-source-highlight`

**Comment by ericonr** [comment]
Do you know which versions of guile it supports?

**Comment by mkohlhaas** [comment]
Hi Érico,

it's version 2.0.

`--with-guile=guile-2.0`

Source highlighting needs the `source-highlight` library.

**Comment by mkohlhaas** [comment]
I was just stealing the `--with-guile=guile-2.0` from our friend Archlinux.

The GNU GDB docs say:

`GDB requires Guile version 2.0 or greater. Older versions are not supported.`
