### ISSUE TITLE
How do I update grub ?

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [void-linux/void-packages#23086]
I see some kernel errors/warnings at boot....
I add the following line to **/etc/default/grub**  : 
GRUB_CMDLINE_LINUX="console=tty12"

right ? and then what commands should I run to update grub ? is it **grub-mkconfig -o /boot/grub/grub.cfg** ?

**Comment by anaggh** [comment]
Have you tried `sudo update-grub` ?

**Comment by Duncaen** [comment]
This is a issue tracker not a support forum, use the subreddit or irc instead.

`grub-mkconfig -o /boot/grub/grub.cfg` is what `update-grub` does.
