### ISSUE TITLE
NVIDIA failing to build for linux5.7

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#23128]
### System 

* xuname:  Void 5.6.18_1 x86_64 GenuineIntel notuptodate rrrrmmnFFFFFFFFFFFFFFFFFFFFFFF
* package: nvidia-dkms-440.82_1 and linux5.7-5.7.4

### Expected behavior

NVIDIA DKMS module builds. https://www.archlinux.org/packages/extra/x86_64/nvidia/ seems to indicate that it should be working.

### Actual behavior

Doesn't build.

### Steps to reproduce the behavior

Have `linux5.7` and `nvidia-dkms` installed, run

```
# xbps-reconfigure -f linux5.7
```

**Comment by chili-b** [comment]
This is affecting me as well.
