### ISSUE TITLE
deepin-movie-reborn and deepin-editor don't start

### ISSUE THREAD

**Issue by gorkawien** [void-linux/void-packages#23133]
### System
Void Linux 64 Bits glibc Plasma
* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  deepin-editor deepin-movie-reborn
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
deepin-editor 1.2.9.1_1
deepin-movie-reborn  5.0.0_1

### Expected behavior
Should start (open a video, editing a file, etc).

### Actual behavior
Don't start
```
probeHwdecInterop "" ""
translatePath after feedback: "/usr/share/libdtk-2.1.1/DWidget/translations/dtkwidget_es"
translatePath after feedback: "/usr/share/deepin-movie/translations/deepin-movie_es"
configPath "/home/jose/.config/deepin/deepin-movie/config.conf"
create config "/home/jose/.config/deepin/deepin-movie/config.conf"
malloc(): invalid size (unsorted)
zsh: abort      deepin-movie
```
```
translatePath after feedback: "/usr/share/libdtk-2.1.1/DWidget/translations/dtkwidget_es"
translatePath after feedback: "/usr/share/deepin-editor/translations/deepin-editor_es"
zsh: segmentation fault  deepin-editor
```

**Comment by Johnnynator** [comment]
fd307ca9db9fef59aad30f1665a74360f3a1a24e and ed95354f3484aac99bda180624f6580f226ba29e should fix both of these issues.

**Comment by gorkawien** [comment]
Thanks you very muchJohnynato!!.
 Great job!!!
