### ISSUE TITLE
bbswitch.ko is installed under the wrong /lib/module/x.x.xx_x directory...

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [void-linux/void-packages#23153]
### System

* package:  
bbswitch-0.8_2

### Expected behavior
I expect the `bbswitch.ko` module to be installed under /lib/modules/5.4.**47**_1

### Actual behavior
The `bbswitch.ko` module is installed in /lib/modules/5.4.**48**_1/
`uname -a` says I am on 5.4.47_1

### Steps to reproduce the behavior
(1) `xbps-install -S bbswitch`

(2) I put "bbswitch" in `/etc/modules-load.d/bbswitch.conf`

(3) I ran `xbps-reconfigure --force linux5.4`

but I get this error at boot:

modprobe: WARNING" module bbswitch not found in directory /lib/modules/5.4.47_1

Also, lsmod does not list bbswitch.

**Comment by abenson** [comment]
If it's building for 5.4.48_1, why not boot that kernel? It won't build for older versions of the kernel, only the latest.

**Comment by ReductoAdAbsurdum** [comment]
I am a n00b so can you tell me how to boot 5.4.48_1 ? and also, why isn't void Linux using the latest kernel automatically ?

**Comment by ReductoAdAbsurdum** [comment]
I upgraded to 5.4.48_1 .... during installation there was an error about bbswitch ..
