### ISSUE TITLE
podman-2.0.0 won't work with apparmor enabled

### ISSUE THREAD

**Issue by the-antz** [void-linux/void-packages#23206]
### System

* xuname:  
Void 5.6.19_1 x86_64 GenuineIntel uptodate rrFF
* package:  
podman-2.0.0_1
maybe containers.image-5.0.0_1

### Expected behavior

Both

`sudo podman run --rm -it hello-world`

and

`podman run --rm -it hello-world`

should print some hello-world messages.

#### ~~Issue 1~~ (fixed in v2.0.1 #23235 )

`sudo podman run --rm -it hello-world`
fails with
`Error: AppArmor profile "container-default" specified but not loaded`

After loading a dummy apparmor profile in complain mode `/etc/apparmor.d/container-default.profile`
```
#include <tunables/global>
profile container-default flags=(complain) {
 #include <abstractions/base>
}
```
running podman as root works as expected.

Related: https://github.com/containers/libpod/issues/6724

We should probably add a container-default.profile to podman (or maybe containers.image?) but I didn't find any example profile in the podman repo.

#### Issue 2

**edit**: https://github.com/containers/libpod/issues/6668

`podman run --rm -it hello-world`
fails with
`Error: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:378: setting rlimits for ready process caused \\\"error setting rlimit type 7: invalid argument\\\"\"": OCI runtime error`

This happens with both apparmor enabled and disabled and might be a different issue.

--

I deleted all container related configs and had them recreate by podman 2 (well actually containers.image) but that didn't have any effect.

### Steps to reproduce the behavior

To load the profile: `apparmor_parser /etc/apparmor.d/container-default.profile`

Otherwise, on an apparmor enabled system, simply:
```
xbps-install podman
podman run --rm -it hello-world
sudo podman run --rm -it hello-world
```
edit: @cameronnemo (ping)

**Comment by CameronNemo** [comment]
>We should probably add a container-default.profile to podman (or maybe containers.image?) but I didn't find any example profile in the podman repo.

No that profile will be automatically generated and loaded by podman. The bug is fixed in containers/common, we just have to wait for a release.

I cannot reproduce the second issue.

**Comment by the-antz** [comment]
Regarding the 2nd issue, I found out that it works when I add `--ulimit host` (https://github.com/containers/libpod/issues/6668).

As this seems to be an upstream bug(s), should I close this issue?

**Comment by CameronNemo** [comment]
If you would like to keep this issue open for the ulimit issue I do not mind. I have not been able to reproduce it though. #23235 should contain the fix for the apparmor issue.

**Comment by the-antz** [comment]
I lost a bit track of this but at least as of podman v2.0.3 both issues are fixed.
