### ISSUE TITLE
Package request: pueue

### ISSUE THREAD

**Issue by VoidNoire** [void-linux/void-packages#23266]
Name: pueue
Source: https://github.com/Nukesor/pueue
License: [MIT](https://github.com/Nukesor/pueue/blob/master/LICENSE)
Dependencies: Not sure, maybe look at ["Dependencies" on it's crates.io page](https://crates.io/crates/pueue).
Description: Pueue is a command-line task management tool for sequential and parallel execution of long-running tasks.

**Comment by VoidNoire** [comment]
Already requested.

**Comment by abenson** [comment]
Closed in 664b0e37e7e72d1de8ad8e9797906cd905376967
