### ISSUE TITLE
Package request: hunter

### ISSUE THREAD

**Issue by VoidNoire** [void-linux/void-packages#23263]
Name: hunter
Source: https://github.com/rabite0/hunter
License: [WTFPL](https://github.com/rabite0/hunter/blob/master/LICENSE)
Dependencies: [See "PREREQUISITES" in README.md](https://github.com/rabite0/hunter/blob/master/README.md)
Description: The fastest file manager in the galaxy!

**Comment by NeelChotai** [comment]
hunter uses the Rust nightly compiler so this won't be possible yet.

**Comment by VoidNoire** [comment]
Right, although there [is an upstream PR](https://github.com/rabite0/hunter/pull/91) that should allow this to be packaged in the future, so I'll leave it opened for now.

**Comment by VoidNoire** [comment]
`nnn` which is already in the repo works well for my purposes so I'm closing this.
