### ISSUE TITLE
lxd-lts complains of undefined symbol in libdqlite.so.0

### ISSUE THREAD

**Issue by lampmerchant** [void-linux/void-packages#23278]
### System

* xuname:  
  Void 5.4.49_1 x86_64 AuthenticAMD uptodate rF
* package:  
  lxd-lts-3.0.3_1

### Expected behavior

lxd service to start as normal.

### Actual behavior

Starting the service, either through runit (`ln -s /etc/sv/lxd /var/service`) or just running `lxd`, produces the following error, then lxd terminates:
`lxd: symbol lookup error: /usr/lib/libdqlite.so.0: undefined symbol: sqlite3_wal_replication_unregister`

### Steps to reproduce the behavior

(as root) `xbps-install lxd-lts` and `lxd`

**Comment by sgn** [comment]
`lxd-lts` is marked broken.

**Comment by sgn** [comment]
`lxd-lts` has released 4.0.2, I'll check if the new version works ;)
