### ISSUE TITLE
Package request: quiterss (Is anyone besides myself interested?)

### ISSUE THREAD

**Issue by toluschr** [void-linux/void-packages#23272]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*: ``Void 5.7.6_1 x86_64 AuthenticAMD uptodate hold rrrmFFFFFFFFFFFFFFFFFFFFFFFF``
* package:  
  *affected package(s) including the version*: ``quiterss-0.19.4_1``

Creating a PR wouldn't make sense if I'm the only one using Void and this software

**Comment by Chocimier** [comment]
there were few PRs for it, so some people want it. You can pick up last one.
