### ISSUE TITLE
clang & rustc crash on aarch64 musl

### ISSUE THREAD

**Issue by sug0** [void-linux/void-packages#23294]
### System

* xuname:  
`Void 4.19.127_1 aarch64-musl Unknown uptodate rFFF`
* package:  
`clang-10.0.0_3`
`rust-1.44.1_1`

### Expected behavior

--

### Actual behavior

Both of these programs were tested, and both crash with a segmentation fault. Some problem with LLVM?

### Steps to reproduce the behavior

Simply attempt to run the executables.

**Comment by ericonr** [comment]
I couldn't reproduce from inside proot/qemu, not sure if this counts for segfaults. Is your `llvm` package in version `10.0.0_3` ?

**Comment by sug0** [comment]
@ericonr Were you using musl? `llvm` is not a dependency of either of them, but `libllvm` is in version `10.0.0_3`.

**Comment by ericonr** [comment]
Yes, I was. And I meant `libllvm` indeed, sorry. Have you verified the packages with `xbps-pkgdb` and tried to update the system?

**Comment by sug0** [comment]
Alright, so, I ran: `xbps-remove -R clang rust cargo`, followed by: `xi clang rust cargo`. I now don't get a segmentation fault, but rather this:

```
: CommandLine Error: Option '' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

**Comment by sug0** [comment]
Both `rustc` and `clang` display the same error message above:
```
[sugo@pj ~]$ clang
: CommandLine Error: Option '' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
[sugo@pj ~]$
[sugo@pj ~]$ rustc
: CommandLine Error: Option '' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

I have `gcc` installed, and it works fine, so the issue stems from LLVM.
```
[sugo@pj ~]$ gcc
gcc: fatal error: no input files
compilation terminated.
```

**Comment by ericonr** [comment]
It is working fine on native `arvm6l-musl` too, so I don't _think_ this is a cross compilation issue. Will have to wait for someone else to comment on it.

**Comment by ericonr** [comment]
Have you actually reinstalled `libllvm` in this? Other packages might have pulled it in, and then it wouldn't have been removed when you tried reinstalling everything.

**Comment by sug0** [comment]
I have a Raspberry Pi 3B+, but I don't think that's the issue at hand, here. As for your second post... I don't quite follow. Anyway, could this be related with the fact there are now some dead packages in XBPS for `libllvm` previous versions, which were not properly removed when upgrading to newer versions?

**Comment by sgn** [comment]
I don't see the error:
- Host: Raspberry Pi 3 Model B Plus Rev 1.3
- OS: Void Linux aarch64
- Kernel: 4.19.122_1
- pkgver: musl-1.1.24_3
- pkgver: clang-10.0.0_3
- pkgver: libllvm10-10.0.0_3
- pkgver: libclang-10.0.0_3
- pkgver: libstdc++-devel-9.3.0_6
- pkgver: libgcc-devel-9.3.0_6

**Comment by sgn** [comment]
@sug0 llvm10 **is** a hard dependency of clang

**Comment by ericonr** [comment]
@sug0 packages like Mesa depend on `libllvm`, so just reinstalling clang and rust might not reinstall `libllvm` too. You can manually reinstall it (`xbps-install -f libllvm10`).

I would run a check to see if all packages are fine, too: `xbps-pkgdb -a`.

**Comment by sug0** [comment]
This fixed the issue: `xbps-install -f clang rust rust-std libllvm10`. Not quite sure why, oh well.

Thanks for the help! @ericonr @sgn

**Comment by Piraty** [comment]
custom (broken) build?

**Comment by Piraty** [comment]
This works
```
#!/bin/sh

export XBPS_TARGET_ARCH=aarch64-musl

root="/tmp/rootfs.void.aarch64-musl"
proot_cmd="proot -q qemu-aarch64-static -R $root"

xbps-install \
	--repository=https://alpha.de.repo.voidlinux.org/current/aarch64 \
	--rootdir="$root" \
	-Sy \
	base-voidstrap bash clang rustup

$proot_cmd sh -c 'echo "hello from aarch64-musl." ; xbps-uhelper arch'
$proot_cmd clang
$proot_cmd rustup
```

**Comment by sgn** [comment]
> @sug0 packages like Mesa depend on `libllvm`, so just reinstalling clang and rust might not reinstall `libllvm` too. You can manually reinstall it (`xbps-install -f libllvm10`).
> 
> I would run a check to see if all packages are fine, too: `xbps-pkgdb -a`.
> 
> Edit: from inside chroot, I do get this error: `error: unable to execute command: Executable "" doesn't exist!`

Hm, can you strace to see which executable `clang` try to exec?

**Comment by ericonr** [comment]
The only thing I could find that could be related to it would be:

```
lstat("/tmp/chroot/usr/lib/gcc/aarch64-linux-musl/9.3/crtn.o", 0x7fff972ca5e0) = -1 ENOENT (No such file or directory)
```

And 

```
[pid 28666] writev(2, [{iov_base="execve(\"/usr/bin/clang\")", iov_len=24}, {iov_base=NULL, iov_len=0}], 2execve("/usr/bin/clang") <unfinished ...>
```

I can't strace from inside the proot, so the output is very polluted.

**Comment by ericonr** [comment]
The complete thing, btw https://0x0.st/iJlX.log

**Comment by ericonr** [comment]
@sgn don't worry, it's fixed. I launched used `proot -r` instead of `proot -R`. Thanks!
