### ISSUE TITLE
nvidia driver issues on 4.17.19_1

### ISSUE THREAD

**Issue by sww1235** [void-linux/void-packages#2330]
### System

* virtual machine in KVM/QUMU with void glibc network install. kernel version 4.17.19_1. GPU passthrough of a GTX1060.

* nvidia binary driver 390.77 from xbps

### Expected behavior

graphics card works after `xbps-install nvidia` and `xbps-install void-repo-nonfree`

### Actual behavior

the driver appears to install fine but on a reboot the machine gets stuck at `loading initramfs` both with recovery and normal grub options.

### Steps to reproduce the behavior

`sudo xbps-install -Sy void-repo-nonfree`
`sudo xbps-install -S nvidia`
`sudo reboot`

### Other notes

The host system of the vm is a void linux musl install running off the intel graphics.

Z370 chipset and intel core i3-8350k with 16GB ram

I have successfully created a windows 10 VM using virt-manager and passed through the GTX1060. I had to edit the xml of the vm and add the "you are not actually running in a vm" settings in order for the windows nvidia driver to work but once I did that everything worked perfectly.

I tried using the exact same config options for my attempted void linux vm but every time I install the drivers in the vm, it locks up and refuses to progress past `loading initramfs` during boot. 

The reason I am attempting to install the nvidia drivers rather than just using the nouveau drivers is that I am having issues with my third monitor not getting any video output. it is detected by xrandr but no actual signal to the display. I am hoping the nvidia drivers fix this issue.

Thank you for your time.

PS. I noticed that the 390 series of nvidia drivers for linux is up to 390.87 now on their website. Is there a reason void is 10 versions behind?

**Comment by sww1235** [comment]
I also tested manually adding the nvidia driver to the initramfs in dracut.conf.d but no dice.

**Comment by cr6git** [comment]
> The reason I am attempting to install the nvidia drivers rather than just using the nouveau drivers is that I am having issues with my third monitor not getting any video output. it is detected by xrandr but no actual signal to the display.

Could it be the same problem as the one described in this patch?

https://git.archlinux.org/svntogit/packages.git/tree/trunk/0001-SNA-fix-PRIME-output-support-since-xserver-1.20.patch?h=packages/xf86-video-intel

**Comment by sww1235** [comment]
@cr6git I do not think so as the screen does not get output even on tty1. I posted about the nouveau issue on their IRC (convo logged [here](https://people.freedesktop.org/~cbrill/dri-log/index.php?channel=nouveau&highlight_names=&date=2018-09-06)) and they seemed to think that a bug was triggering somehow. See convo between imirkin and ToxicSauce

**Comment by cr6git** [comment]
They talked about this commit?

https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=85c5d90fc155d78531efa5d2b02e92aaef7e4b88

Well, let us know if you make any progress...

**Comment by sww1235** [comment]
@cr6git I still want to make sure the nvidia issue gets taken care of regardless of what happens with nouveau. Do you think this would be resoved when kernel 4.18 gets set to recommended?

**Comment by sww1235** [comment]
looks like #2414 updates to 390.87. I can test this again once the package is updated.

**Comment by Hoshpak** [comment]
It might take a few hours until the updated nvidia package hits the repository since the builders are busy buildings kernels, KDE and Gnome updates. You can try the 4.18 kernel any time by installing the `linux4.18` package. It just isn't the default yet because `zfs` does not support it yet.

**Comment by cr6git** [comment]
@sww1235 is it better with 390.87 ?

**Comment by cr6git** [comment]
4.17.19 is history, it's time to close this.
