### ISSUE TITLE
Package request: Defiant browser

### ISSUE THREAD

**Issue by porky11** [void-linux/void-packages#23310]
[Defiant browser](https://github.com/gab-ai-inc/defiant-browser) is a fork of [Brave](https://github.com/brave/brave-browser), so it might be related to [this issue](#5444).

It's difficult to install on voidlinux, since there are no precompiled binaries and when building it from source, which is difficult and lengthy anyway, it fails because of a dependency on older versions of libreSSL.

**Comment by Duncaen** [comment]
No. Not a chance.
