### ISSUE TITLE
nmap does not include ndiff, impossible to compare results

### ISSUE THREAD

**Issue by jirib** [void-linux/void-packages#23321]
as nmap does not include ndiff i can't compare network scan result with previous run. ndiff seems to be python script included with nmap > 4.80, see https://salsa.debian.org/pkg-security-team/nmap/-/blob/debian/master/debian/ndiff.install

### System

* xuname:  
```
Void 5.4.49_1 x86_64 GenuineIntel notuptodate rF
```

* package:  

```
$ xbps-query -S nmap | grep ^pkgver: ;xbps-query -f nmap | grep bin/
pkgver: nmap-7.80_2
/usr/bin/ncat
/usr/bin/nmap
/usr/bin/nping
```
### Expected behavior

ndiff is available

### Actual behavior

i can't compare nmap results with previous run

### Steps to reproduce the behavior

```
xbps-query -f nmap | grep bin/
```

**Comment by abenson** [comment]
It doesn't look like ndiff has been updated to python2, which is now EOL.

**Comment by ericonr** [comment]
Debian has a huge patch to make it Py3, not sure if we want this https://salsa.debian.org/pkg-security-team/nmap/-/commit/a47969f12dd5cfbf2cb520d5b1774abd2d79044e#3a02b372872b4be170a369cfb9ebf3e76e6d9469

**Comment by jirib** [comment]
https://github.com/nmap/nmap/pull/1484

**Comment by jirib** [comment]
If it is not too much work to maintain I would vote for patch, so people can diff network scan results.

**Comment by ericonr** [comment]
Given the nebulous situation around nmap licensing, I don't think we can/should act on this at the moment.

Pinging @Piraty for awareness

**Comment by Piraty** [comment]
giving recent license mess (#27866) i'm not even in the mood to backport this patch (https://github.com/nmap/nmap/pull/1484) if it's merged.
I am however open to pick debian's patch if that works
