### ISSUE TITLE
Consider basing Dolphin-Emu on Beta versions

### ISSUE THREAD

**Issue by sG4ZvHrf** [void-linux/void-packages#23328]
Currently, `dolphin-emu` seems to be based on the 5.0 "Stable" version from over 4 years ago. I would like the package to be based off of the "Beta" version instead. (Current one is [5.0-11991](https://dolphin-emu.org/download/dev/8d4e8314a3dcd8680ae81d91fb7e076b4496b43b/) released roughly 2 months ago)

According to [their website](https://dolphin-emu.org/download/):
>Beta versions are released every month, usually accompanied by a Progress Report article. They are a good balance between the Dolphin development versions and the stable versions.

Reasons for moving to Beta:

- Over the 4 years, various improvements in UI and features have been made, and the emulator no longer resembles that of the original 5.0 release.
- The Stable version has not had a release in over 4 years, and doesn't seem like it will ever be updated. (Until possibly a version 6.0 appears who knows when)
- Beta versions are accompanied with progress reports, making it easy to keep track of what features to expect.
- The other alternative, Development versions, (the version that is advertised on the main page) updates on a daily to hourly basis, making it neigh impossible to keep track of.

Unlike what the name suggests, "Beta" versions essentially seems to function as the Stable releases, and seems to be what distros like Fedora and Solus uses. (And distros like Arch, KaOS, FreeBSD, and NetBSD seems to use some up-to-date Development version, but certainly not the 5.0 Stable release)

**Comment by abenson** [comment]
I'd be more open to this if they tagged releases as such or provided a build-ready tarball for it. I'll take a look into building it and see what people say.

**Comment by sG4ZvHrf** [comment]
They do technically "name" their releases with what seems to be "the number of commits since the release of 5.0".

And from what I can tell, the only real way to find the list of releases is to go to the Download section [here](https://dolphin-emu.org/download/). There have been no official releases since 5.0.

**Comment by ericonr** [comment]
Closed in #28295
