### ISSUE TITLE
Package request: swaylock-effects

### ISSUE THREAD

**Issue by One37** [void-linux/void-packages#23345]
Name: swaylock-effects
Source: [https://github.com/mortie/swaylock-effects](https://github.com/mortie/swaylock-effects)
License: [MIT](https://github.com/mortie/swaylock-effects/blob/master/LICENSE)
Dependencies: See ["compiling-from-source"](https://github.com/mortie/swaylock-effects/blob/master/README.md#compiling-from-source) in README.md
Description: Swaylock-effects is a fork of swaylock which adds built-in screenshots and image manipulation effects like blurring.

**Comment by ericonr** [comment]
If you're interested in trying your hand at packaging it, it should require few changes to the `swaylock` template. You will have to add that it conflicts with `swaylock>=0`, though.

**Comment by travankor** [comment]
search github pr's if you want to save a little time.

**Comment by sgn** [comment]
#19073 is closed?
#23369
