### ISSUE TITLE
NVidia Error when trying to install menulibre for XFCE

### ISSUE THREAD

**Issue by AngryPhantom** [void-linux/void-packages#23364]
## System

* xuname:  
Void 5.4.49_1 x86_64 AuthenticAMD uptodate rrFFFFF

* package:  
**nvidia340**-340.108_3, **menulibre**-2.2.1_2

### Expected behavior
So, I'm running Void + XFCE with NVidia GeForce 9500 GT card. I would like to install **menulibre** (XFCE menu editor) and here is what I get:

### Actual behavior
```
nvidia340-340.108_3: broken, unresolvable shlib `libnvidia-ml.so.1'
Transaction aborted due to unresolved shlibs.
```

### Steps to reproduce the behavior
Install Void XFCE with nvidia340 proprietary drivers
Install menulibre

**Comment by st3r4g** [comment]
Same as #21993 and #20252
Until this is fixed properly, you can create as root the file `/etc/xbps.d/ignore.conf` with contents:
```
ignorepkg=libglvnd
```
This should prevent `libglvnd` to try to replace `nvidia340-libs`

**Comment by AngryPhantom** [comment]
Oh, thanks! Should I close this issue because of duplicates?

**Comment by AngryPhantom** [comment]
@st3r4g Oh, thank you again! Should I close this issue because of duplicates?

**Comment by st3r4g** [comment]
> P.S. Should I also do this?
No, the `ignorepkg` way is better

> Should I close this issue because of duplicates?
Yes please

**Comment by AngryPhantom** [comment]
>No, the ignorepkg way is better

Thanks.
