### ISSUE TITLE
`wayland` is being pulled in as a dependency of `mesa` and `libgbm`

### ISSUE THREAD

**Issue by Kratacoa** [void-linux/void-packages#23389]
#### Packages:  
* xf86-video-intel-2.99.917.899_2
* mesa-dri-20.1.2_1
* mesa-20.1.2_1
* libgbm-20.1_1
* wayland-1.

### Expected behavior
`xf86-video-intel` and `xorg-server` (related to `libgbm`) pulling in only X-related packages 

### Actual behavior
`wayland` breaks in trasaction `mesa-dri` and `libgbm` according to `xbps-remove` 

### Steps to reproduce the behavior
Clean installation of Void Linux with musl.

**Comment by Duncaen** [comment]
Yes, wayland is just the protocol, mesa is built with wayland support.

**Comment by Kratacoa** [comment]
> Yes, wayland is just the protocol, mesa is built with wayland support. There is no good reason to not ship with wayland support by default.

Isn't it redundant/useless for users of X? There is no comfortable way to modularise it?

**Comment by Duncaen** [comment]
There is not and there is not a single distribution I'm aware of that attempts something like that, its just not worth it.

There is a build option in the mesa template to allow you to disable wayland support, if you really want to get rid of less than 200KB, clone this repository and `./xbps-src -o ~wayland pkg mesa`.

**Comment by Kratacoa** [comment]
Oh, I didn't care to check the actual size of the difference between having it and not, I just assumed it would be significant; I beg pardon for my lack of diligence.
Thank you for the swift reply and clarification, I'll close the issue.
