### ISSUE TITLE
New packages request:  Logstash && Kibana

### ISSUE THREAD

**Issue by gorkawien** [void-linux/void-packages#23391]
Logstash:
Tool for managing events and logs
https://www.elastic.co/products/logstash/
Kibana:
Browser based analytics and search dashboard for Elasticsearch
https://www.elastic.co/products/kibana

**Comment by jirib** [comment]
IMO much better than logstash is [vector](https://github.com/timberio/vector), see comparison with logstash. If you already use Grafana, [loki](https://grafana.com/docs/grafana/latest/features/datasources/loki/) seems better alternative.

**Comment by CameronNemo** [comment]
I just use the container images they publish. Allows me to control the version number (ops team at my work are very slow to upgrade software).

**Comment by the-maldridge** [comment]
Elastic has chosen to make their software legally hazardous for us to interact with.  Thank you for your interest in Void, but these packages will not be accepted.
