### ISSUE TITLE
Gajim fails to open with error "Namespace Soup not available"

### ISSUE THREAD

**Issue by Max-FT** [void-linux/void-packages#23424]
# System

* xuname:  
   Void 5.7.7_1 x86_64 GenuineIntel uptodate rFFFF
* package:  
  gajim-1.2.0_1

### Expected behavior
The Application opens as expected 
### Actual behavior
Application fails with

No translations found
Dirs searched: [PosixPath('/usr/local/share'), PosixPath('/usr/share')]
Traceback (most recent call last):
  File "/bin/gajim", line 11, in <module>
    load_entry_point('gajim==1.2.0', 'gui_scripts', 'gajim')()
  File "/usr/lib/python3.8/site-packages/gajim/gajim.py", line 151, in main
    _check_required_deps()
  File "/usr/lib/python3.8/site-packages/gajim/gajim.py", line 46, in _check_required_deps
    import nbxmpp
  File "/usr/lib/python3.8/site-packages/nbxmpp/__init__.py", line 5, in <module>
    gi.require_version('Soup', '2.4')
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Soup not available

### Steps to reproduce the behavior

Attempt to launch Gajim 1.2

**Comment by ericonr** [comment]
Can you try installing `libsoup` or `libsoup-gnome`, if the first one doesn't work?

**Comment by Max-FT** [comment]
libsoup fixes it. I thought it was installed already. My apologies

**Comment by ericonr** [comment]
If you want to reopen the issue or make a PR for, it should probably be a runtime dependency, right? Unless gajim can run without it somehow.

**Comment by Max-FT** [comment]
It appears as if libsoup is not in the dependency tree currently: https://github.com/void-linux/void-packages/blob/master/srcpkgs/gajim/template

**Comment by ericonr** [comment]
@teldra @mobinmob do either of you know about this?

**Comment by mobinmob** [comment]
> @teldra @mobinmob do either of you know about this?

It should be a runtime dependency - runs fine here. I
