### ISSUE TITLE
deepin-picker don't work

### ISSUE THREAD

**Issue by salifm** [void-linux/void-packages#23431]
### System

* xuname:  Void 5.4.50_1 x86_64 GenuineIntel uptodate rrFFF

* package:  deepin-picker-5.0.1_1

### Expected behavior

Expected to see deepin-picker cursor ready to select color from the screen

### Actual behavior

```
(deepin-picker:4538): Gtk-WARNING **: 01:42:56.779: Unable to locate theme engine in module_path: "murrine",

(deepin-picker:4538): Gtk-WARNING **: 01:42:56.779: Unable to locate theme engine in module_path: "murrine",

(deepin-picker:4538): Gtk-WARNING **: 01:42:56.780: Unable to locate theme engine in module_path: "murrine",

(deepin-picker:4538): Gtk-WARNING **: 01:42:56.781: Unable to locate theme engine in module_path: "murrine",
```

and nothing happens and exits with status code 0

### Steps to reproduce the behavior:

Install `deepin-picker` and run `deepin-picker` from terminal application.

And I am using Cinnamon, not Deepin. But that should not be a problem, because it worked on Cinnamon on other distributions.

**Comment by Johnnynator** [comment]
The problem is, that I missed specifying a runtime dep. (qt5integration)
