### ISSUE TITLE
Cannot chvt to tty2 if a framebuffer/kms app is running on tty1

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#23456]
### System

* xuname:  

Void 4.4.189_2 aarch64 Unknown notuptodate rDFFF

* package:  

N/A

### Expected behavior

Should show tty2 login. I confirm this works on systemd based systems.

### Actual behavior

Does not switch tty's. Command works if app is stopped.

### Steps to reproduce the behavior

ssh in and run `sudo chvt 2`. agetty-tty2 is running as a service.

**Comment by ericonr** [comment]
As discussed a long while ago on IRC, this is likely due to some magic that systemd does with vts.

**Comment by travankor** [comment]
@valadaa48  Does elogind work?
