### ISSUE TITLE
Package request: bspwc

### ISSUE THREAD

**Issue by linkert** [void-linux/void-packages#23463]
Name: bspwc *(Binary Space Partitioning Wayland Compositor)*
Website: https://git.sr.ht/~bl4ckb0ne/bspwc
Source: https://git.sr.ht/~bl4ckb0ne/bspwc/tree
License: GPLv3
Dependencies: meson, wlroots, wltrunk
Description: Binary space partitioning wayland compositor based on wltrunk, basically bspwm for wayland :)

**Comment by sirikid** [comment]
Does it already have a release? See [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#getting-your-packages-into-void-by-yourself):
> Please note that we do not accept any packages containing non-release versions, such as specific git- or svn-revisions anymore.

**Comment by linkert** [comment]
> Does it already have a release? See [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#getting-your-packages-into-void-by-yourself):
> 
> > Please note that we do not accept any packages containing non-release versions, such as specific git- or svn-revisions anymore.

Oh! Thank you for the info, had not read this document.

**Comment by classabbyamp** [comment]
> status
> The project is currently abandonned because of a lack of motivation/free time. Feel free to fork the project and keep the name.

river is apparently similar in functionality
