### ISSUE TITLE
Package due to removal: keepassx

### ISSUE THREAD

**Issue by snobknob** [void-linux/void-packages#23502]
Installing `keepassx` through the repos gives the following message:

`keepassx is no longer provided by Void Linux, and will be fully removed from the repos on 2019/03/20`

**Comment by Anachron** [comment]
So? Why open this issue?

**Comment by snobknob** [comment]
I don't know man... Shouldn't someone remove it? It does nothing at all besides printing that message.

**Comment by Anachron** [comment]
How else do you tell users that the software is going to be removed so that they know their setup is going to break soon?

**Comment by ericonr** [comment]
@Anachron I think the point is that the package is already past the listed removal date, which isn't an issue, but they might not know that.

**Comment by snobknob** [comment]
@ericonr Yep, that was I meant. Why isn't it an issue though?

**Comment by ericonr** [comment]
@snobknob it's a small issue, but not a big one. You can just install the package and get the warning that it isn't available anymore. If you'd like to keep the issue open, we are working on some better tools for cleaning up the repos, and this is one of the applications that should go c:

**Comment by snobknob** [comment]
I don't think it's worth it keeping the issue open, but I'm glad you're working to get the repos cleaner. Sorry for the mess, though. I just thoguht it should have been reported.

**Comment by ericonr** [comment]
No worries!

**Comment by Chocimier** [comment]
@Anachron : note that such package is not telling that is going to be removed. It's already gone from your computer and repos when you see that message.
