### ISSUE TITLE
Request: Please include gnome  gnome-menus and  gnome-screensaver as dependency from metapackage "gnome"

### ISSUE THREAD

**Issue by gorkawien** [void-linux/void-packages#23513]
Please include gnome  gnome-menus and  gnome-screensaver as dependency from metapackage "gnome" in order to simplifiy the installation of Gnome.
If possible remove the dependency of eog.,yelp and all the docs.
Change dependency of gdm to lightdm (the system will be lighter).

**Comment by ericonr** [comment]
pinging @not-chicken and @mnabid 

GDM is the supported way of starting GNOME afaik, and most GNOME metapackages around install GDM. It's only 4M installed.

**Comment by mnabid** [comment]
The GNOME metapackages are being restructured in #22936. `gnome-menus` is added as dependency there.

**LightDM isn't part of GNOME**, so it probably wouldn't be included in `gnome` metapackage. (And it shouldn't, in my opinion).
IIRC, GNOME Wayland session doesn't show up in lightdm. You can install `lightdm` manually and use it as default. 

`gnome-screensaver` is very old, and isn't needed anymore (even in `gnome-flashback`, see [#21382 (comment)](https://github.com/void-linux/void-packages/pull/21382#discussion_r432390025) ).

**Comment by gorkawien** [comment]
@ericonr is not about the size. I am building a live iso of Gnome, and i think that the GDM package is causing me trouble with lightdm. and other DMs
The reason to use lightdm is because the RAM drops around 200 -250 MB.
The issue I have noticed is that with another DM the anon login doesnt work, only  root.
I also notice that eog, evince, and file-roller are dependencies.
IMHO this 3 packages should be a dependency , and if they are, also gnome-terminal should be a dependency.
@mnabid  thanks for the information. Is good to know that they are considering including gnome-menus.
Maybe I didn't explain myself clear. My personal opinión is that no DM should be included as dependency in the metapackage (let the user choose).
Also I would also remove the dependencies of eog, file-roller and evince, but of course gnome-menus is more important.
Thanks also for information regarding gnome-screensaver.

**Comment by pullmoll** [comment]
@gorkawien If you're going to build a live ISO you can just not use the `gnome` meta pacakge. Why not list the individual packages you want included with `-p pkg1,pkg2,pkg3, …`?
Or even easier yet: create your own `gnome-live` package in a fork of this repository and list whatever you think belongs there and omit what you don't want. There is no need and certainly no good reason to change what Void's `gnome` meta package contains just for that purpose.

**Comment by ProjectMoon** [comment]
gnome-screensaver should be added to the metapackage. Without it, screen locking does not work.

**Comment by ericonr** [comment]
https://wiki.gnome.org/Attic/GnomeScreensaver says it's archived

https://en.wikipedia.org/wiki/GNOME_Screensaver says it was replaced by functionality combining gdm and gnome.

`gnome-menus` only seems to be used by flashback, not `gnome`.
