### ISSUE TITLE
KeePassXC has rendering issues regarding QPainter not activating properly on installations with NVIDIA graphics

### ISSUE THREAD

**Issue by Max-FT** [void-linux/void-packages#23517]
### System

* xuname:  
  Void 5.7.8_1 x86_64 GenuineIntel uptodate rFFFF
* package:  
  keepassxc-2.6.0_1
### Expected behavior
The painting of widgets is done properly

### Actual behavior
With NVIDIA graphics cards, QPainter fails to properly load with

QPainter::begin: Paint device returned engine == 0, type: 3 QPainter::setCompositionMode: Painter not active

This issue isn't present on devices with intel integrated graphics

### Steps to reproduce the behavior
Launch KeePassXC 2.6.0 with NVIDIA graphics.

**Comment by sburris0** [comment]
Confirmed does not affect AMD systems.

**Comment by b1scu1t** [comment]
Are you sure this is specific to Void's package?
If its not, I could be an upstream issue.

**Comment by Max-FT** [comment]
> Are you sure this is specific to Void's package?
> If its not, I could be an upstream issue.

So, I did some more digging and this issue is apparently caused by a change in DPI scaling within the application. Setting the
environment variable QT_AUTO_SCREEN_SCALE_FACTOR=0 resolves the issue completely.
