### ISSUE TITLE
Compile `ffmpeg` package with `--enable-libaom` to support `av1`

### ISSUE THREAD

**Issue by zenny** [void-linux/void-packages#23538]
Hi,

Void's `ffmpeg` pacakge does not seem to support open sourced high compressed `av` codec.
```
$ ffmpeg -h encoder=libaom-av1
Codec 'libaom-av1' is not recognized by FFmpeg.
```

Would you mind adding `--enable-libaom` to the `ffmpeg` package` as stated at https://trac.ffmpeg.org/wiki/Encode/AV1?

Cheers, and stay safe,
/z

**Comment by ericonr** [comment]
Have you tried the `dav1d` encoder? We ship with that one.

**Comment by q66** [comment]
dude, dav1d is a decoder

**Comment by ericonr** [comment]
Gah I could swear dav1d was the Rust encoder for AV1. I was thinking of https://github.com/xiph/rav1e

**Comment by ericonr** [comment]
Heh, we have a build option for it already. I'm making a PR to enable it, then/

**Comment by jnbr** [comment]
ffmpeg is now built with aom enabled
