### ISSUE TITLE
python3-magic and pass-import problem

### ISSUE THREAD

**Issue by bda65** [void-linux/void-packages#23535]
### System
x86_64 Glibc
* xuname:  
  *Void 5.7.8_1 x86_64 GenuineIntel uptodate rrFFFF
* packages:  
  *python3-magic-0.4.18_1
  *pass-import-3.0_1

### Actual behavior
Import from cvs file (exported from firefox) return this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/pass_import/__main__.py", line 425, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pass_import/__main__.py", line 407, in main
    decryptsource(conf)
  File "/usr/lib/python3.8/site-packages/pass_import/__main__.py", line 260, in decryptsource
    frmt, encoding = get_magics(path)
  File "/usr/lib/python3.8/site-packages/pass_import/tools.py", line 42, in get_magics
    res = magic.detect_from_content(header)
AttributeError: module 'magic' has no attribute 'detect_from_content'
```
### Steps to reproduce the behavior
```
pass import csv file.csv --cols 'url,login,pass'
```

**Comment by bda65** [comment]
It seem to be corrected here [https://github.com/roddhjav/pass-import/issues/103](url)

**Comment by sgn** [comment]
Yes, `pass-import` needs `file-magic` instead of `magic`

**Comment by sgn** [comment]
There's a serious test failure when packaging this. I'll look into it later.

**Comment by bda65** [comment]
Thanks :)
I've patched manually with any test. It work well with firefox import.

**Comment by sgn** [comment]
On 2020-07-13 06:06:10-0700, bda65 <notifications@github.com> wrote:
> Thanks :)
> I've patched manually with any test. It work well with firefox import.

I can publish python3-file-magic right now. And it'll works for you.

But, it's annoying me that detect_from_content on content extracted
from Python scripts count as application/octet-stream

Other two tests also fails, but they report text/x-script.python
Which is correct.

-- 
Danh
