### ISSUE TITLE
Possible package feature: emacs daemon managed with runit

### ISSUE THREAD

**Issue by The-BigDaddy** [void-linux/void-packages#2356]
While I don't know if this is anything killer, but I think that it'd be something interesting to have. 

What one could do is have a directory called `/etc/sv/emacs-daemon` (or just `emacsd`) and in it would be an empty folder named `supervise`, and two scripts: `run` and `finish`. I had these for both earlier, but I failed to actually start the daemon at all.

1. `run`

```
#!/bin/sh
exec emacs --daemon &
```

2. `finish`
```
#!/bin/sh
exec emacsclient -e "(kill-emacs)"
```

I'm not entirely sure why it failed, but it did. There was a message at one point `fail: emacs-daemon: runsv not running`.

Anyway, might be nice to add on the `emacs` package.

**Comment by maxice8** [comment]
services in /etc/sv are system services you need to run a user instance of runsvdir.

the run line should be 

`exec emacs --fg-daemon`

the `&` causes the process to go into background which is wrong and --daemon switch also does that.

> fail: emacs-daemon: runsv not running

that is weird. did you link it to /var/service ? (even tho it is completely wrong to run emacs-daemon as a system service)

> Anyway, might be nice to add on the emacs package.

currently `vsv` only supports adding to /etc/sv and i see no plans to provide runit user instances.

**Comment by The-BigDaddy** [comment]
> `exec emacs --fg-daemon`

Oh that makes more sense after what I just read [here](https://www.gnu.org/software/emacs/manual/html_node/efaq/New-in-Emacs-26.html).

> the & causes the process to go into background which is wrong and --daemon switch also does that.

Ah, that also makes sense.

> that is weird. did you link it to /var/service ? (even tho it is completely wrong to run emacs-daemon as a system service)

> currently sv only supports adding to /etc/sv and i see no plans to provide runit user instances.

You're right. Runit does provide the option to allow for [user control of services](http://smarden.org/runit/faq.html#user), which requires creating a `run` script in `/etc/sv/service-name/log`, something like

```
exec 2>&1
exec chpst -uyour_user runsvdir /home/your_user/service
```
then using `chown` to give user access to the `supervise` subdirectory and it's contents, and then symlinking to `/home/your_user/service`.
 
All which seems smarter to do for the Emacs daemon and also seems more a personal choice. One could do that or just have `emacs --daemon` in their personal `.xinitrc`.

Thank you for feedback, though!

**Comment by maxice8** [comment]
This can be revisited if we ever plan on supporting runit user services.
