### ISSUE TITLE
Package Request: Epson Inkjet Driver 2 (ESC/R-P)

### ISSUE THREAD

**Issue by basiccoderboi** [void-linux/void-packages#23596]
Download Page: 
https://download.ebz.epson.net/dsc/du/02/DriverDownloadInfo.do?LG2=EN&CN2=&DSCMI=115177&DSCCHK=d8d3c64cea10641d35811d933a1c0f6d09423ae7

This package, when compared to epson-inkjet-driver-escpr, has more printers available. According to the website, it supports the following Epson Printers:

EC-4020 Series, EC-4030 Series, EC-4040  Series, EP-50V Series, EP-879A Series, EP-880A Series, EP-881A Series,  EP-882A Series, EP-982A3 Series, ET-15000 Series, ET-16600 Series,  ET-16650 Series, ET-3700 Series, ET-3710 Series, ET-3750 Series, ET-3760  Series, ET-4750 Series, ET-4760 Series, ET-5800 Series, ET-5850 Series,  ET-5880 Series, ET-8700 Series, ET-M1140 Series, ET-M1170 Series,  ET-M1180 Series, ET-M2140 Series, ET-M2170 Series, ET-M3140 Series,  ET-M3170 Series, ET-M3180 Series, EW-M5610FT Series, EW-M630T Series,  EW-M670FT Series, EW-M752T Series, L14150 Series, L15150 Series, L15160  Series, L6160 Series, L6170 Series, L6190 Series, L6550 Series, L6570  Series, L6580 Series, M1140 Series, M1170 Series, M1180 Series, M2140  Series, M2170 Series, M3140 Series, M3170 Series, M3180 Series, PM-520  Series, PX-M270FT Series, PX-M270T Series, PX-M380F, PX-M381FL,  PX-M5080F Series, PX-M5081F Series, PX-M6711FT Series, PX-M6712FT  Series, PX-M680F Series, PX-M7070FX, PX-M7080FX, PX-M7090FX, PX-M7110F,  PX-M7110FP, PX-M780F Series, PX-M781F Series, PX-M791FT Series,  PX-M880FX, PX-M884F, PX-M885F, PX-M886FL, PX-S270T Series, PX-S380,  PX-S381L, PX-S5010 Series, PX-S5080 Series, PX-S7070X, PX-S7090X,  PX-S7110, PX-S7110P, PX-S880X, PX-S884, PX-S885, ST-3000 Series, ST-4000  Series, ST-C8000 Series, ST-M1000 Series, ST-M3000 Series, WF-2860  Series, WF-3720 Series, WF-3730 Series, WF-4720 Series, WF-4730 Series,  WF-4740 Series, WF-7210 Series, WF-7710 Series, WF-7720 Series, WF-7820  Series, WF-7840 Series, WF-C5210 Series, WF-C5290 Series, WF-C5290BA,  WF-C529R Series, WF-C529RB, WF-C5710 Series, WF-C5790 Series,  WF-C5790BA, WF-C579R Series, WF-C579RB, WF-C8190 Series, WF-C8190B,  WF-C8610 Series, WF-C8690 Series, WF-C8690B, WF-C869R Series, WF-C878R  Series, WF-C878RB, WF-C879R Series, WF-C879RB, WF-M5298 Series, WF-M5299  Series, WF-M5799 Series, XP-15000 Series, XP-5100 Series, XP-6000  Series, XP-6100 Series, XP-8500 Series, XP-8600 Series, XP-970 Series

By adding this driver as one of the packages, it will support a lot more printers that what is currently possible with Void Linux.

**Comment by motorto** [comment]
Opening that link returns 
> The page you requested is unavailable

**Comment by basiccoderboi** [comment]
here is the link to the source: 

https://download3.ebz.epson.net/dsc/f/03/00/11/56/43/b1a6f1193e073c4c049da9404806c61052b62419/epson-inkjet-printer-escpr2-1.1.15-1lsb3.2.src.rpm

**Comment by q66** [comment]
the driver is not open source, it won't be accepted in binary form

**Comment by motorto** [comment]
Okay guys updated the package conform discussed on IRC , when you guys have time please review it and tell me what should I change: 
https://github.com/motorto/void-packages/pull/4/files

**Comment by classabbyamp** [comment]
done in #25421
