### ISSUE TITLE
kde5-baseapps is not installable

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#23622]
### System

* package:  kde5-baseapps-20.04.3_1

### Expected behavior

I install it and I get its dependencies.

### Actual behavior

I try to install it and `xbps-install` errors out without any error message. Running with debug generates a huge log:  https://gist.github.com/ericonr/b4be938b806523064008e7c8ce638227

I tried building the meta package locally and got the same error. I also tried installing each application individually and that worked. 

### Steps to reproduce the behavior

`xbps-install kde5-baseapps`

@Johnnynator and @Duncaen, since I think this is some sort of bug in XBPS as well.

**Comment by abenson** [comment]
`dolphin` and `dolphin-plugins` depend on each, and so it breaks when resolving auto deps.

**Comment by abenson** [comment]
Simple test template demonstrates the same issue:

```
# Template file for 'dolphinasadep'
pkgname=dolphinasadep
version=1
revision=1
build_style=meta
depends="dolphin"
short_desc="Dolphin is a dep"
maintainer="Andrew Benson <abenson+void@gmail.com>"
license="GPL-3.0-or-later"
homepage="https://voidlinux.org"
```

**Comment by ericonr** [comment]
Installing `dolphin` separately and then `kde5-baseapps` works, because then XBPS knows how to solve the dependencies. I guess this should be solved somewhere in XBPS.

This is probably the issue in shlibs:

```
libdolphinvcs.so.5 dolphin-plugins-20.04.2_1
```

This library is provided by `dolphin`, not `dolphin-plugins`. Even though `dolphin` provides it, during the build it's found and `dolphin-plugins` is pulled in as a dependency.

**Comment by Johnnynator** [comment]
Yes, that shlib entry is wrong, Should be removed and dolphin rebuild.

**Comment by ericonr** [comment]
@Johnnynator I'm making a PR for it.

**Comment by martindamianfernandez** [comment]
thanks stuff to report right now have got my account again., see you on irc.

**Comment by ericonr** [comment]
@Duncaen what do you think is the best way to solve this?

**Comment by Duncaen** [comment]
Not really sure what exactly the issue is, xbps should handle cyclic dependencies, but I couldn't come up with a test case yet.
That said, xbps-src doesn't support cyclic dependencies and this looks like a mistake.

**Comment by ericonr** [comment]
@Duncaen it definitely is a mistake! #23626 fixes it. Would just be nice if XBPS could have a better error message during an install or better error checking during package creation.

**Comment by Chocimier** [comment]
> mistake

I didn't checked which package contain library when merging plugins, sorry.

While here, I have naive question raising since some time: why do we need `common/shlibs` at all, rather than `04-generate-runtime-deps` querying xbps index for which installed package provides library?

**Comment by Duncaen** [comment]
> While here, I have naive question raising since some time: why do we need common/shlibs at all, rather than 04-generate-runtime-deps querying xbps index for which installed package provides library?

It records the minimum version that provides the SONAME, which makes it easier to downgrade and partially update things.

**Comment by ericonr** [comment]
Perhaps we could add some sanity check when building a package that a shlib specified in common/shlibs actually exists in that package? Are there any cases where that wouldn't happen?

**Comment by Chocimier** [comment]
> It records the minimum version that provides the SONAME, which makes it easier to downgrade and partially update things.

Shlib-requires and shlib-provides could be enough, but yes, it *is* easier this way. Thanks.

**Comment by ericonr** [comment]
This has been fixed.
