### ISSUE TITLE
Package request: palemoon

### ISSUE THREAD

**Issue by qorg11** [void-linux/void-packages#23628]
Source: https://github.com/MoonchildProductions/Pale-Moon
License:  Mozilla Public License v2.0. 

Palemoon is a browser based on an old version of firefox

**Comment by CameronNemo** [comment]
dupe #4130

**Comment by vpzomtrrfrt** [comment]
#4130 is closed, and it doesn't look like it was added

**Comment by Chocimier** [comment]
Palemoon developers do not want us to build with system libraries, and we do not want build with bundled, so it wasn't added. More issues mentioned at https://chocimier.github.io/voidlinux-archive/void-packages:issues:2387.html
