### ISSUE TITLE
Gnome settings requires colord

### ISSUE THREAD

**Issue by ProjectMoon** [void-linux/void-packages#23642]
### System

* xuname:  Void 5.4.51_1 x86_64 GenuineIntel notuptodate hold rrFFFFFFF
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver gnome-desktop-3.34.1_1``

### Expected behavior
GNOME settings "Color" sections works.

### Actual behavior
It crashes when you go to the color section, or refuses to launch if it's already there. Launching `gnome-control-center` from command line complains about missing dependency.

### Steps to reproduce the behavior
Do not have `colord` installed and attempt to launch gnome-settings as above.

Installing `colord` fixes this problem.

**Comment by not-chicken** [comment]
Added in PR https://github.com/void-linux/void-packages/pull/21382#discussion_r418960571 along with a couple other dependencies.

**Comment by ericonr** [comment]
Has been fixed.
