### ISSUE TITLE
Package request: Inter fonts

### ISSUE THREAD

**Issue by handow23** [void-linux/void-packages#23663]
"Inter is a typeface carefully crafted & designed for computer screens."

Website: https://rsms.me/inter/

**Comment by flexibeast** [comment]
The "Quality Requirements" section of the XBPS manual [says](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality_requirements):

> New fonts are welcome if they provide value beyond aesthetics (e.g. they contain glyphs for a script missing in already packaged fonts).

Does this font provide any glyphs for codepoints not otherwise covered?

**Comment by sgn** [comment]
> Does this font provide any glyphs for codepoints not otherwise covered?

Looks like no. It provides glyph for codepoints in private use area. Which I don't like.
