### ISSUE TITLE
Package request: font "Courier Prime Code"

### ISSUE THREAD

**Issue by thenktor** [void-linux/void-packages#23661]
A monospace font for terminal and programming: https://quoteunquoteapps.com/courierprime/ (Note there are also the variants "Courier Prime" and "Courier Prime Sans".

Direct download link: https://quoteunquoteapps.com/courierprime/downloads/courier-prime-code.zip

**Comment by flexibeast** [comment]
The "Quality Requirements" section of the XBPS manual [says](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality_requirements):

> New fonts are welcome if they provide value beyond aesthetics (e.g. they contain glyphs for a script missing in already packaged fonts).

Does this font provide any glyphs for codepoints not otherwise covered?

**Comment by thenktor** [comment]
Thanks for the hint. I don't think there is anything like that font.
