### ISSUE TITLE
Question: Does the base dovecot package include the lmtpd & pop3d plugins?

### ISSUE THREAD

**Issue by Frick-David** [void-linux/void-packages#23676]
I am following some guides to set up a mail server. Almost all of them mention using the dovecot lmtpd plugin as well as the pop3d plugin? Do these come by default in the dovecot package? If not, could someone help me package them? I would be supremely thankful!

**Comment by Anachron** [comment]
Doesn't look like they do. What would your full stack look like? I use OpenSMTPD with dovecot and everything required is packaged.

**Comment by Frick-David** [comment]
So I was following a guide to set up a mailserver with postfix but I switched to follow this [guide](https://poolp.org/posts/2019-09-14/setting-up-a-mail-server-with-opensmtpd-dovecot-and-rspamd/), which like you said, is pretty well self packaged so that this issue is no longer relevant. However, I then run into the issue that I need httpd (which appears to be for OpenBSD only) to get an ssl cert ;/

**Comment by Anachron** [comment]
You normally get ssl certs by either self creating them (libressl) or using a global authority (letsencrypt). Not sure why you are so fixed on httpd.

**Comment by Frick-David** [comment]
So the guide I think I linked uses httpd to get an SSL cert from let's encrypt. I am using traefik which makes getting a generic ssl cert from let's encrypt easy but specific ones a little more difficult. It seems httpd is the easiest way to do a one off and get an ssl cert for a mail server.

David

-------- Original Message --------

**Comment by Anachron** [comment]
We have a lot of tools to get a LE cert, certbot and lego are good ones to start with and easy to use.

**Comment by Frick-David** [comment]
Okay, thanks Ill check em out. Lego looks pretty cool
