### ISSUE TITLE
Broken i915 support in Kernel 5.7

### ISSUE THREAD

**Issue by foxlet** [void-linux/void-packages#23675]
### System

* xuname:  
  Void 5.4.52_1 x86_64 GenuineIntel notuptodate rrrmFFFF
* package:  
  linux5.7_5.7.9_1

System uses the following card:
```
00:02.0 VGA compatible controller [0300]: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller [8086:22b1] (rev 21)
```

### Expected behavior
Xorg displays wallpaper and desktop, can open applications in KDE Plasma.

### Actual behavior
Black screen, no cursor, no keyboard response. Power button works, console framebuffer works.

### Steps to reproduce the behavior
Choose Kernel 5.7.9 in Grub, wait for SDDM to start, black screen.
Earlier 5.4 kernel works normally when chosen.

**Comment by foxlet** [comment]
[dmesg.txt](https://github.com/void-linux/void-packages/files/4950470/dmesg.txt)

**Comment by leahneukirchen** [comment]
Upstream bugs related: https://gitlab.freedesktop.org/search?utf8=%E2%9C%93&snippets=false&scope=issues&repository_ref=&search=%22gpu+hang%3A+ecode+8%3A1%3A85dffffb%22&group_id=2642&project_id=4519

Also seems to appear in 5.6.

**Comment by foxlet** [comment]
Corresponding issue filed on Freedesktop, https://gitlab.freedesktop.org/drm/intel/-/issues/2206

**Comment by fosslinux** [comment]
This explains my current issues. Thanks

**Comment by Gorggg** [comment]
Upgrading to kernel 5.8 fixed this for me where I was experiencing issues with kernel 5.7.

I am on an Intel Celeron N3160 with an Intel HD Graphics 400 GPU:
```
00:02.0 VGA compatible controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller (rev 35)```

**Comment by ericonr** [comment]
Still happening on 5.7?

**Comment by leahneukirchen** [comment]
5.7 is EOL, does it happen on 5.8?

**Comment by tutacat** [comment]
I really think this is a kernel issue, not a Void Linux issue.
On Manjaro with 4th gen Pentium..
_5.7 is still available on my distros repos_
5.6 worked fine, but now EOL, so down to 5.4.
5.7, 5.8, and 5.9 work as stated by op

**Comment by fosslinux** [comment]
It is a kernel issue I have been unable to repro with 5.8...

**Comment by ericonr** [comment]
Is this still present on 5.10?

**Comment by Gorggg** [comment]
> Is this still present on 5.10?

Not for me.
