### ISSUE TITLE
Package Request/ Help Making Template for PARI/GP

### ISSUE THREAD

**Issue by motorto** [void-linux/void-packages#23692]
Source: https://pari.math.u-bordeaux.fr/
License: GPL

PARI/GP is a widely used computer algebra system designed for fast computations in number theory

EDIT:

I started trying to package it myself but I am having some trouble with the checksum , I download the tar.xz and did 

> tar xf <tarball.ext> --to-stdout | sha256sum

But when running I get an error that it can't configure checksum of distfiles, my package template at the moment looks like this: 

```
# Template file for 'pari-gp'
pkgname=pari-gp
version=2.11.4
revision=1
archs="*"
#wrksrc=
#create_wrksrc=yes
build_style=gnu-configure
#configure_args=""
#make_build_args=""
#make_install_args=""
#conf_files=""
#make_dirs="/var/log/dir 0755 root root"
hostmakedepends=""
makedepends=""
depends=""
short_desc="PARI/GP is a widely used computer algebra system designed for fast computations in number theory"
maintainer="André Cerqueira <acerqueira021@gmai.com>"
license="GPL-3.0-or-later"
homepage="https://pari.math.u-bordeaux.fr"
distfiles="https://pari.math.u-bordeaux.fr/pub/pari/unix/pari-2.11.4.tar.gz"
checksum=8f8b4cf6c3af54f74bb3e42929bc195d68563f353bba2a4e6f9c7fc096407a83
```
Any help is welcomed even if its not a positive one !

**Comment by yopito** [comment]
compute `checksum` this way ( is the checksum of the `distfiles` itself):
```
$ sha256sum pari-2.11.4.tar.gz 
bfc88fc4f7352f4840e6e352c72f0369cbea8a45403b1834a6269f3709970b1c  pari-2.11.4.tar.gz
```

**Comment by motorto** [comment]
That solved the issue ! Thanks, now I am getting an error:
`=> ERROR: pari-gp-2.11.4_1: cannot access wrksrc directory [/builddir/pari]`

Well this is turning harder than I tough

**Comment by sgn** [comment]
```sh
# Template file for 'pari'
pkgname=pari
version=2.11.4
revision=1
build_style=configure
configure_script=./Configure
configure_args="--prefix=/usr"
make_build_target=all
hostmakedepends="perl texlive"
makedepends="gmp-devel libX11-devel readline-devel"
short_desc="Fast computations library in number theory"
maintainer="people <ad@dre.ss"
license="GPL-2.0-or-later"
homepage="https://pari.math.u-bordeaux.fr"
distfiles="https://pari.math.u-bordeaux.fr/pub/pari/unix/${pkgname}-${version}.tar.gz"
checksum="bfc88fc4f7352f4840e6e352c72f0369cbea8a45403b1834a6269f3709970b1c"
nocross=yes

post_patch() {
	vsed -i -e 's/ulong/unsigned long/' config/has_sse2.c
}

pre_configure() {
	export LD="$CC"
}

pari-devel_package() {
	short_desc+=" - development files"
	depends="pari-${version}_${revision}"
	pkg_install() {
		vmove usr/include
		vmove "usr/lib/*.so"
	}
}
```

**Comment by motorto** [comment]
Oh uau thanks for it , I still have a lot to learn when it comes to this. Can you commit or you want me to do it ?

**Comment by sgn** [comment]
On 2020-07-22 02:19:17-0700, André Cerqueira <notifications@github.com> wrote:
> Oh uau thanks for it , I still have a lot to learn when it comes to
> this. Can you commit or you want me to do it ?

I need someone, probably you, tests the binary,
I don't use the package myself.

-- 
Danh

**Comment by sgn** [comment]
This is the latest update https://github.com/sgn/void-packages/commit/1e2f6bf9f383a3c86b83505f0e9b4cb09868ee9a

**Comment by motorto** [comment]
I can definitly try the binary for you ! How can I clone your commit into my machine in order to try it ?

**Comment by sgn** [comment]
Inside your clone of void-packages:
```sh
curl -L https://github.com/sgn/void-packages/commit/1e2f6bf9f383a3c86b83505f0e9b4cb09868ee9a.patch |
git am
```

**Comment by motorto** [comment]
Thanks, It seems to be working ! But when compiling the package it gives me this warning.

`=> WARNING: pari-2.11.4_1: libpari-gmp.so.6 not found in common/shlibs!`

I don't know if is something you want to know !

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/commit/121b353b59fde7d7438066e6f7cfac749c337b01

**Comment by dkwo** [comment]
Is it possible to add certain extensions to pari?
When trying to build SageMath, I get that it is not possible to use pari from system package because it misses pari_elldata, pari_galdata, pari_galpol, pari_seadata. (This in turn forbids to use giac from system.)

```
## ----------------------------------------------------- ##
## Checking whether SageMath should install SPKG pari... ##
## ----------------------------------------------------- ##
configure:17312: checking whether any of gmp mpir readline is installed as or will be installed as SPKG
configure:17321: result: no
configure:17326: checking for gp
configure:17344: found /bin/gp
configure:17356: result: /bin/gp
configure:17370: checking for gphelp
configure:17388: found /bin/gphelp
configure:17400: result: /bin/gphelp
configure:17417: checking whether gphelp has access to the documentation
configure:17420: result: yes
configure:17432: checking is pari_elldata installed?
  ***   at top-level: r=ellinit("11a1");r[11]
  ***                   ^---------------------
  *** ellinit: error opening elldata file: `/usr/share/pari/elldata/ell0'.
configure:17439: result: no; cannot use system pari/GP without elldata package
configure:17441: Install elldata package and reconfigure.
configure:17443: Otherwise Sage will build its own pari/GP.
configure:17447: checking is pari_galdata installed?
  ***   at top-level: polgalois(x^8-2)[1]
  ***                 ^-------------------
  *** polgalois: error opening galois file: `/usr/share/pari/galdata/COS8_50_47'.
configure:17454: result: no; cannot use system pari/GP without galdata package
configure:17456: Install galdata package and reconfigure.
configure:17458: Otherwise Sage will build its own pari/GP.
configure:17462: checking is pari_galpol installed?
  ***   at top-level: galoisgetname(12,1)=="C3 : C4"
  ***                 ^------------------------------
  *** galoisgetname: error opening galpol file: `/usr/share/pari/galpol/12/nb'.
configure:17469: result: no; cannot use system pari/GP without galpol package
configure:17471: Install galpol package and reconfigure.
configure:17473: Otherwise Sage will build its own pari/GP.
configure:17477: checking is pari_seadata installed?
  ***   at top-level: poldegree(ellmodulareqn(211)[1])
  ***                           ^----------------------
  *** ellmodulareqn: error opening seadata file: `/usr/share/pari/seadata/sea211'.
configure:17484: result: no; cannot use system pari/GP without seadata package
configure:17486: Install seadata package and reconfigure.
configure:17488: Otherwise Sage will build its own pari/GP.
configure:17492: checking whether hyperellcharpoly bug is fixed
configure:17497: result: yes
configure:17508: checking whether bnfisunit bug of pari 2.11.3 is fixed
configure:17513: result: yes
configure:17750: no suitable system package found for SPKG pari 
```

**Comment by motorto** [comment]
@dkwo  what if you build sagemath first ?

**Comment by dkwo** [comment]
Well, that's the idea :)
Right now it fails building giac (hence the need for pari).
The more I can use from system, the better.

**Comment by motorto** [comment]
Oh I got the message wrong you are trying to build sagemath , but it needs pari is that correct ?

**Comment by dkwo** [comment]
That is correct: it can either take pari from system or build it, but 
the latter is cumbersome/redundant and I'd like to avoid it.

I'm told that these missing pari/gp parts are just data, easy to package.

**Comment by motorto** [comment]
Yeah probably by creating a subpackage pari-extra or something ...

@sgn Could you do it ? If no can I modify your template ?

**Comment by sgn** [comment]
Please go ahead, I'm not using it anyway.

**Comment by motorto** [comment]
Ok I am going to try that tonight !

**Comment by dkwo** [comment]
Thanks.
Looking at Arch Linux corresponding packages can help.

**Comment by motorto** [comment]
@dkwo hey quick question ! Do you have a preference if I create seadata with seadata-big or do you want a separate package for each (big and small)

https://pari.math.u-bordeaux.fr/packages.html

**Comment by dkwo** [comment]
Thank you.
I think seadata-small should suffice.
