### ISSUE TITLE
LLVM  pakage(s) missing tools

### ISSUE THREAD

**Issue by DanPartelly** [void-linux/void-packages#23690]
LLVM llvm-10.0.0_2 package misses at least the following utils : sancov, scan-build,  scan-view. Possibly missing in older versions ones too, but I did not checked. Missing tools are related to sanizer coverage and running static analysis on code bases. 

pkg:
llvm-10.0.0_2

xuname
Void 5.7.9_1 x86_64 GenuineIntel uptodate rrFFF

### expectedl behavior
be bale to run sancov, scan-build,  scan-view tools

### Actual behavior
cant run the flollowing utilites:
sancov, scan-build,  scan-view

### Steps to reproduce the behavior
try to run sancov, scan-build,  scan-view

**Comment by ericonr** [comment]
`sancov` is in `clang-tools-extra`

`scan-build`, `scan-view` are in `clang-analyzer`

You can find this using `xlocate` from the `xtools` package: `xlocate -S; xlocate bin/sancov`

**Comment by DanPartelly** [comment]
Thanks for locating tips !
