### ISSUE TITLE
Package Broken: Mupen64plus glide64mk2

### ISSUE THREAD

**Issue by joeblo1** [void-linux/void-packages#2369]
### System

* xuname:  Void 4.18.5_1 x86_64-musl GenuineIntel uptodate rDDDDDF
  *output of ``xuname`` (part of xtools)*
* package:  mupen64plus    - the glide64mk2 plugin has stopped working
  *affected package(s) including the version*

### Expected behavior
for it to not crash? :P 

### Actual behavior
crashes when trying to open games with it, rice isn't good on some games, only happens with glide64mk2

### Steps to reproduce the behavior
try to use glide64mk2 plugin... sorry I use a front-end, but here's a the output.

```
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         http://code.google.com/p/mupen64plus/  
Mupen64Plus Console User-Interface Version 2.5.0

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.0
UI-Console:             Includes support for Dynamic Recompiler.
Core: Goodname: Army Men - Sarge's Heroes 2 (U) [!]
Core: Name: ARMYMEN SARGE 2     
Core: MD5: 6EEA5C4A6256092ED8F9BA8861C689C6
Core: CRC: B20F73B6 2975FC34
Core: Imagetype: .z64 (native)
Core: Rom size: 8388608 bytes (or 8 Mb or 64 Megabits)
Core: Version: 1444
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console Error: dlopen('/usr/lib/mupen64plus/mupen64plus-video-glide64mk2.so') failed: Error relocating 
/usr/lib/mupen64plus/mupen64plus-video-glide64mk2.so: 
_ZN5boost10filesystem11path_traits7convertEPKcS3_RSbIwSt11char_traitsIwESaIwEERKSt7codecvtIwc11__mbstate_tE: symbol 
not found
UI-Console Error: Specified Video plugin not found: mupen64plus-video-glide64mk2
Core Status: Rom closed.
```

Whenever I try to load the game with mupen64plus-qt it outputs an error about QXcbConnection.

```
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1423, resource id: 14692755, major code: 40 (TranslateCoords), 
minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 1569, resource id: 14692874, major code: 40 (TranslateCoords), 
minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 23770, resource id: 14693358, major code: 40 (TranslateCoords), 
minor code: 0
```

**Comment by Hoshpak** [comment]
Please try to rebuild the package locally and confirm if it resolves the issue. That should at least make it possible to load the plugin again since it currently is built against an incompatible stdc++ ABI. I don't know if this will resolve the QXcbConnection or how serious these messages are, though.

I'm preparing a rebuild of the package in the repository but currently we better wait until the builders have finished the huge icu rebuild.

**Comment by joeblo1** [comment]
Oh jeeze, I thought the icu rebuild was done? v62 came in the updates earlier today, it has to be rebuilt again? :o

**Comment by Hoshpak** [comment]
Many packages have to be rebuilt against the new icu version and because some of them are huge (libreoffice, two firefox versions, qt) it takes several days to get it all done.

**Comment by joeblo1** [comment]
I rebuilt mupen64plus & glide64mk2 seems to work again. Thank you Hoshpak! The Rice plugin shakes really hard in some games, I am greatful I can play games again with glide64mk2!

There are some funny warnings I'm a bit unsure of, they go on like this for forever & I figured I'd at least show you it:

```
Core Warning: ROM Database: Unknown property on line 20
Core Warning: ROM Database: Unknown property on line 29
Core Warning: ROM Database: Unknown property on line 203
Core Warning: ROM Database: Unknown property on line 218
Core Warning: ROM Database: Unknown property on line 243
Core Warning: ROM Database: Unknown property on line 266
Core Warning: ROM Database: Unknown property on line 321
Core Warning: ROM Database: Unknown property on line 445
Core Warning: ROM Database: Unknown property on line 468
Core Warning: ROM Database: Unknown property on line 496
Core Warning: ROM Database: Unknown property on line 544
Core Warning: ROM Database: Unknown property on line 577
Core Warning: ROM Database: Unknown property on line 585
Core Warning: ROM Database: Unknown property on line 598
```
