### ISSUE TITLE
Linux Kernel CONFIG_DEBUG_INFO_BTF by default

### ISSUE THREAD

**Issue by DanPartelly** [void-linux/void-packages#23723]
Please consider changing the default kernel config to include BTF deduplicated type information. The flag is CONFIG_DEBUG_INFO_BTF .  The flag allow the kernel to make available type information to BPF programs, allowing those to introspect kernel structures without resorting to llvm/clang to parse kernel headers as was done in past by iovisor bcc tool for example.  This was iffy at times and broke many times.   BTF allows a lot of introspection into running kernel, making the setting usefull to all kind of ppl from developer to ops and sytem admins.  given this usefulness more and more distros are enabling it by default.  It is a relative recent addition, so the config flag should only be upaded for latest kernel serie (5.7)  and up. 

Note that when using this config, pahole utility becomes a build dependency. 

BTF type info is de-duplicated and greatly reduced in size compared to dwarf.  A primer into its usefulness can be read at:
https://facebookmicrosites.github.io/bpf/blog/2018/11/14/btf-enhancement.html

**Comment by luhann** [comment]
Currently there is a PR to implement this change for 5.7 on x86_64. See  #23534.

**Comment by leahneukirchen** [comment]
Enabled for our platforms in Linux 5.8 now.
