### ISSUE TITLE
libvirt is broken

### ISSUE THREAD

**Issue by FantasyCookie17** [void-linux/void-packages#23724]
### System

* xuname:  
  `Void 5.7.9_1 x86_64-musl AuthenticAMD notuptodate rFFF`
* package:  
  `libvirt-6.5.0_1`

### Expected behavior
Connecting to `qemu:///system` or `qemu+ssh://root@hostname/system` (with `openbsd-netcat` installed) with `virsh` or `virt-manager` should work. QEMU VMs should be booted.

### Actual behavior
Connecting with any of the above hangs indefinitely. QEMU VMs are not started.

### Steps to reproduce the behavior
1. Install libvirt and, optionally, virt-manager. If connecting via SSH, also install openbsd-netcat.
2. Enable and start libvirtd, virtlogd and virtlockd.
3. Try to connect.

**Comment by abenson** [comment]
Is your user in the `libvirt` group?

**Comment by ahesford** [comment]
Connecting to `root@host` should avoid any `libvirt` group issues, but is also a bad idea. Have you tried connecting to `qemu+ssh://user@host/system` for some user in the `libvirt` group?

**Comment by anjandev** [comment]
https://github.com/void-linux/void-docs/pull/217/files

Read line 205 onwards on this patch for instructions to fixing permissions.

**Comment by FantasyCookie17** [comment]
Well, the problem is it doesn't seem to do anything at all. My QEMU VMs that previously worked were not started either and such. So, I'd suppose connecting as a different user wouldn't work, even `virsh list` didn't. However, others on the IRC were not able to reproduce the issue, and I myself have found a solution that works for me (start QEMU VMs manually as individual Runit services), so I'm closing this for now.

**Comment by aldnox** [comment]
I am having this exact same issue as well. My suspicion is libvirt and musl don't play nice together. That could explain why other people on IRC, using glibc, couldn't reproduce the issue. Would be nice to have an actual fix.

**Comment by travankor** [comment]
maybe this? https://gitlab.com/libvirt/libvirt/-/issues/52
