### ISSUE TITLE
Wireguard DKMS module fails to build for kernel 5.7.10_1

### ISSUE THREAD

**Issue by cinerea0** [void-linux/void-packages#23790]
### System

* xuname:  
  *Void 5.7.10_1 x86_64 GenuineIntel notuptodate rFFFFFFFFF*
* package:  
  *wireguard-dkms-1.0.20200712_1*:

### Expected behavior
The wireguard DMS module builds successfully.

### Actual behavior
The wireguard DKMS module does not build successfully. The following is the output from the configuration step after running `xbps-install -S wireguard`:
```
wireguard-tools-1.0.20200513_2: configuring ...
wireguard-tools-1.0.20200513_2: installed successfully.
wireguard-dkms-1.0.20200712_1: configuring ...
Added DKMS module 'wireguard-1.0.20200712'.
Skipping kernel-5.4.51_1. kernel-headers package not installed...
Skipping kernel-5.5.18_1. kernel-headers package not installed...
Skipping kernel-5.6.0_2. kernel-headers package not installed...
Skipping kernel-5.6.19_1. kernel-headers package not installed...
Building DKMS module 'wireguard-1.0.20200712' for kernel-5.7.10_1... FAILED!
DKMS module 'wireguard-1.0.20200712' failed to build, please check /var/lib/dkms
for errors in the log file.
Building DKMS module 'wireguard-1.0.20200712' for kernel-5.7.9_1... FAILED!
DKMS module 'wireguard-1.0.20200712' failed to build, please check /var/lib/dkms
for errors in the log file.
wireguard-dkms-1.0.20200712_1: installed successfully.
wireguard-0.0.20191226_1: configuring ...
wireguard-0.0.20191226_1: installed successfully.
```
A couple things are weird about this. One, it lists kernels (5.4.51, 5.5.18, 5.6.0, 5.6.19) that I have removed with `xbps-remove` and `vkpurge`. Two, there are no logs in the directory it tells me to check.

### Steps to reproduce the behavior
Attempt to install wireguard-dkms while either running or having installed kernel 5.7.10_1.

**Comment by luhann** [comment]
On kernels later than 5.6 wireguard is included with the kernel and it is not necessary to install wireguard, only wireguard-tools should be needed to get up and running.

**Comment by cinerea0** [comment]
You're right, I was able to get my VPN working without wireguard-dkms. Would it be a good idea to include a post-install message alerting users of this, or enforce it only being able to be installed on kernels 5.6 or earlier using the `depends` field in the template?

**Comment by cinerea0** [comment]
After discussion in the PR linked above, we reached a decision that it was best to leave everything how it is and the the short package description inform people where `wireguard-dkms` is needed. Closing because there's nothing more to be done.
