### ISSUE TITLE
Dialog missing in new ISO

### ISSUE THREAD

**Issue by frmoronari** [void-linux/void-packages#23808]
### System
https://alpha.de.repo.voidlinux.org/live/20200722/void-live-x86_64-5.7.10_1-20200722.iso
### Expected behavior
open void-installer on type "void-installer" after ISO boot.
### Actual behavior
received a messagem "ERROR: missing dialog command, exiting . . . "
### Steps to reproduce the behavior
make a usb with a ISO image. boot from USB or
boot from ISO file with qemu/kvm.
type user (root) and password for login.
type void-installer on shell.

**Comment by ericonr** [comment]
@the-maldridge

**Comment by the-maldridge** [comment]
This ISO was released exclusively for use of the autoinstaller, it will not work for manual installs.  This is intentional, and this release image isn't even signed.
