### ISSUE TITLE
Blender VSE not working with libswscale 4.3..something

### ISSUE THREAD

**Issue by egrain** [void-linux/void-packages#23832]
### System
musl 64bit, shouldn't matter though. Had the same issue over at Arch. That's why I went here. 

Also Void's Blender doesn't write a good /tmp/blender.crash.txt. In Arch it says it's because the ...scale.so.something. That's how I knew. In Void it gives you nothing.

Blender VSE crashes when you have a video in the time line or if you see a thumbnail of one in the file manager. 

Here is what I did to fix it: 
sudo xdowngrade libavdevice-4.2.3_5.x86_64-musl.xbps libavfilter-4.2.3_5.x86_64-musl.xbps libswscale-4.2.3_5.x86_64-musl.xbps libavformat-4.2.3_5.x86_64-musl.xbps libavcodec-4.2.3_5.x86_64-musl.xbps libavutil-4.2.3_5.x86_64-musl.xbps libavresample-4.2.3_5.x86_64-musl.xbps libpostproc-4.2.3_5.x86_64-musl.xbps libswresample-4.2.3_5.x86_64-musl.xbps

Here the Arch Issue: https://blenderartists.org/t/blender-crashes-when-opening-video-folder-in-vse-2-83-2/1241877

**Comment by ericonr** [comment]
@Gottox and @mvf ?

**Comment by mvf** [comment]
https://trac.ffmpeg.org/ticket/8747
