### ISSUE TITLE
Package request: Zrythm

### ISSUE THREAD

**Issue by sug0** [void-linux/void-packages#23831]
**Repository:** https://github.com/zrythm/zrythm
**License:** AGPLv3

Zrythm is a novel Digital Audio Workstation (DAW) targeting the mainstream platforms, namely Linux. It's scriptable with Guile, GNU's Scheme implementation, and offers a modern looking interface, with many built in plugins, much like the proprietary alternative FL Studio.

**Comment by Anachron** [comment]
[Already requested](https://github.com/void-linux/void-packages/issues/21236)

**Comment by sgn** [comment]
Dup #21236
