### ISSUE TITLE
[Package Request]: interception tools

### ISSUE THREAD

**Issue by zenny** [void-linux/void-packages#23851]
Hi,

I came across a very nifty tool, `interception` (https://gitlab.com/interception/linux/tools), particularly the verbosity and modularity of the configuration file of `dual-function-keys` (https://gitlab.com/interception/linux/plugins/dual-function-keys) compared to `xcape`.

However, the drawback appears to be the design focused around`systemd` in mind.

Cheers,

**Comment by ericonr** [comment]
The service in the repo is quite simple, just `ExecStart=/usr/bin/nice -n -20 /usr/bin/udevmon -c /etc/udevmon.yaml`

**Comment by ericonr** [comment]
Even if I'm not sure we would like to have something like that in a service.

**Comment by zenny** [comment]
> The service in the repo is quite simple, just `ExecStart=/usr/bin/nice -n -20 /usr/bin/udevmon -c /etc/udevmon.yaml`
> Even if I'm not sure we would like to have something like that in a service

I do agree that there is no need to have this in service. if `ExecStart=/usr/bin/nice -n -20 /usr/bin/udevmon -c /etc/udevmon.yaml` works, that is good enough. Thanks @ericonr

**Comment by ZerdoX-x** [comment]
Can be closed

https://github.com/void-linux/void-packages/commit/e1d8864c755ee9aa2390893702c7110b6ca2f8e2

**Comment by ericonr** [comment]
Oops, thanks!
