### ISSUE TITLE
Remove oracle-{jdk,jre} packages

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#23881]
The binaries for `oracle-{jdk,jre}-8u202` are no longer available for download. Or to be exact: you need to sign in and agree to some license terms in order to get the (old) files. In the end this means our build process can no longer build the packages.

Since OTOH we no longer need oracle jdk to bootstrap opendjdk8 thanks to @q66 I think we should remove the outdated packages, also because they may already be or become an increasing security risk.

**Comment by ericonr** [comment]
#23575

**Comment by Gottox** [comment]
throw it out!

**Comment by Chocimier** [comment]
Removing binary packages already requested in aggregate issue.
