### ISSUE TITLE
Not properly working on WSL 2

### ISSUE THREAD

**Issue by unifxfoe** [void-linux/void-packages#23927]
### Expected behavior

After building alacritty and running the binary I expected it to open

### Actual behavior

It gave me this error:
`thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed', /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/macros.rs:13:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

### Steps to reproduce the behavior

I am using WSL 2 and then followed the procedure on the website to build alacritty but to no avail.

**Comment by ericonr** [comment]
Is wayland or X configured in WSL2? AFAIK it doesn't configure the graphical stuff by default, which alacritty requires.

**Comment by unifxfoe** [comment]
No neither are configured could you outline the steps in which I could do so?

**Comment by ericonr** [comment]
No idea. You are better off googling this stuff, it isn't Void specific.

**Comment by ahesford** [comment]
This does not appear to be an issue with Void packages. If you need help with your particular setup, I recommend you consult the `r/voidlinux` subreddit or the `#voidlinux` IRC channel on Freenode.
