### ISSUE TITLE
Package request: openJDK14 

### ISSUE THREAD

**Issue by 0xatul** [void-linux/void-packages#23940]
java needs some love and updates too :)

**Comment by q66** [comment]
if there's one thing java doesn't need, it's love, dunno about updates

**Comment by sgn** [comment]
We all know what Java needs, it's memory ;)

**Comment by F0Xde** [comment]
Just to add to this, I think it would be best to have the `openjdk` package always refer to the newest release, and then additionally maintain packages for LTS versions (and possibly others, although those are mostly unimportant). 
Right now the situation surrounding Java is kinda bad in that there is only jdk 8 and 11, with both not even being exactly up to date.

**Comment by Filius-Patris** [comment]
There's this PR: https://github.com/void-linux/void-packages/pull/23988
But it was closed by accident?

CC: @sgn
