### ISSUE TITLE
sv-netmout spams status of $NETWORK_MANAGER if gateway ping or mount commands fail

### ISSUE THREAD

**Issue by manneorama** [void-linux/void-packages#23968]
### System

* xuname:  
  Void 5.6.19_1 x86_64 GenuineIntel notuptodate rrmFFFFFF
* package:  
  sv-netmount-0.1_2

### Expected behavior
sv-netmount silently tries to mount network drives

### Actual behavior
sv-netmount's run script spams the OK status of $NETWORK_MANAGER to stdout if any later step fails. In my case, this manifests as wpa_supplicant being up and running while the route is not fully configured. This leads to runit output spamming my login prompt at boot, which then prevents me from logging in at tty1 for an uncomfortable amount of seconds.

### Steps to reproduce the behavior
Probably best reproduced on a wireless LAN but I guess this could happen in any setup where there is a delay between "physical" connection and actual route configuration.

**Comment by manneorama** [comment]
Potential fix in #23969

**Comment by ericonr** [comment]
Fix has been merged
