### ISSUE TITLE
Package Request: language servers (LSP)

### ISSUE THREAD

**Issue by simonhughcom** [void-linux/void-packages#23979]
It would be nice to have language servers from this list (https://langserver.org/) available, or at least the more popular ones. 

I know that the python and go language-servers are already available, but many others seem to still be missing.

**Comment by jnbr** [comment]
I'd say you should find out what exactly you would like to have packaged and hen come up with a pull request or a package request.
Packaging random stuff just in case someone might want to use it seems like a waste of time.
