### ISSUE TITLE
Installing Microsoft Vs Code -> broken package

### ISSUE THREAD

**Issue by DanPartelly** [void-linux/void-packages#23982]
Installing Visual studio code  1 August 2020  09.00 GMT yields a broken package which can't start. 

code-oss 
node[3842]: pthread_create: Invalid argument

**Comment by DanPartelly** [comment]
Not broken , compositor issue

**Comment by Har-nick** [comment]
Would you mind explaining what you did to fix the issue, if you fixed it at all?

**Comment by DanPartelly** [comment]
In my particular case, I had a broken  Xwaylad (due to some experiment I did ). So a simple reinstall of those packagessolved the issue.
