### ISSUE TITLE
Add a notice to rtv about a maintained fork

### ISSUE THREAD

**Issue by PaperMountainStudio** [void-linux/void-packages#23985]
`rtv` is not maintained anymore, but there is a maintained (and packaged) fork called `tuir`. I think it would be helpful to people who are still using rtv to know about this fork. Eventually, `rtv` could be removed from the repositories.

**Comment by ericonr** [comment]
@abenson what do you think? Could `rtv` become a subpackage of `tuir`, even?

**Comment by abenson** [comment]
Yeah, I'm not sure why I didn't do that to begin with.
