### ISSUE TITLE
slstatus broken build

### ISSUE THREAD

**Issue by dax-dev** [void-linux/void-packages#2399]
### System

* xuname:
  Void 4.17.19_1 x86_64 AuthenticAMD uptodate rFF
* package:  
  slstatus-20180106

### Expected behavior
Expected package to build properly

### Actual behavior
Fails during fetch, the archive doesn't exist

### Steps to reproduce the behavior
./xbps-src pkg slstatus

It seems the snapshots don't exist on the suckless git repo. I tried changing `_commit` to the latest commit, but it didn't work.

**Comment by kojicomics** [comment]
Suckless doesn't use cgit anymore, so you have to download tarballs from here: https://dl.suckless.org/

Unfortunatelly, slstatus isn't tagged yet, so there is no version available.

**Comment by maxice8** [comment]
Please ask upstream release a tagged version

**Comment by cr6git** [comment]
Note: they also have a github repository https://github.com/drkhsh/slstatus
