### ISSUE TITLE
Please add fatresize

### ISSUE THREAD

**Issue by daphniz** [void-linux/void-packages#24025]

**Comment by anjandev** [comment]
https://github.com/ya-mouse/fatresize

Is this the program you want?

**Comment by daphniz** [comment]
I'm not quite sure.  The Arch package 

https://www.archlinux.org/packages/community/x86_64/fatresize/

refers to

https://sourceforge.net/projects/fatresize/

I'll see if I can find out more.

**Comment by daphniz** [comment]
Seems to be by the same author.
