### ISSUE TITLE
Alias taskwarrior to task

### ISSUE THREAD

**Issue by sburris0** [void-linux/void-packages#24092]
I was looking to install taskwarrior and couldn't find it, until searching this repo and realizing the package is called "task" with a super generic description - "Command-line todo list manager". 
`taskd` is the package for the Taskwarrior daemon.

I propose that either a `taskwarrior` alias is added to `task`, or that `task`'s description is updated to mention Taskwarrior so that users know that `task` is in fact `taskwarrior`,  and connects to `taskd`.

**Comment by Chocimier** [comment]
We do not invent names. It is name of tarball and command.
Packages can be searched by homepage.

```
$ xbps-query -R -p homepage -s taskwarrior
clog-1.3.0_1: https://taskwarrior.org/docs/clog/ (https://alpha.de.repo.voidlinux.org/current)
task-2.5.1_5: https://taskwarrior.org (https://alpha.de.repo.voidlinux.org/current)
taskd-1.1.0_4: http://taskwarrior.org (https://alpha.de.repo.voidlinux.org/current)
```

**Comment by sburris0** [comment]
Fair enough, I think it would be good to mention taskwarrior in the description still though

**Comment by Noah-Huppert** [comment]
I think the issue at heart here is that it's a little hard to find the Task Warrior package on Void. `xq taskwarrior` and searching `task warrior` in the voidlinux.org/packages search box doesn't discover the `task` package (which are my two go-to lazy ways of finding packages). 

I have opened [a PR on the Task Warrior website](https://github.com/GothenburgBitFactory/tw.org/pull/87) to add the Void package to their downloads page. 

The `taskd` package does actually mention "Task Warrior" making it more searchable. I  made [a PR](https://github.com/void-linux/void-packages/pull/24143) just to plop the words "Task Warrior" into the `task` package.

**Comment by Noah-Huppert** [comment]
Check out https://taskwarrior.org/download/ 😃
Void is on their list now.
