### ISSUE TITLE
Support for screen sharing in Wayland browsers.

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#24102]
Screen sharing in browsers using Wayland should be possible, but it will need some patches and [xdg-desktop-portal-wlr](https://github.com/emersion/xdg-desktop-portal-wlr).

references:
- <https://github.com/emersion/xdg-desktop-portal-wlr/wiki/Screencast-Compatibility>
- <https://github.com/qutebrowser/qutebrowser/issues/5421>

**Comment by PaperMountainStudio** [comment]
PR for Firefox: #23291
PR for xdg-desktop-portal-wlr: #23296

**Comment by ericonr** [comment]
All that's missing is work on merging #23296, so we will be tracking this there.
