### ISSUE TITLE
audacity: Critical Nyquist files missing

### ISSUE THREAD

**Issue by harrisonthorne** [void-linux/void-packages#24118]
### System

* xuname: `Void 5.7.13_1 x86_64 AuthenticAMD uptodate rrrmFFFFF`

* package: `audacity-2.4.1_1`

### Expected behavior

Audacity should install with all bundled Nyquist plugins.

### Actual behavior

It doesn't. Plugins such as "Sound Finder" or "Silence Finder" are missing after install. 

### Steps to reproduce the behavior

Install Audacity (`xi -f audacity`), open Audacity, go to `Analyze` dropdown and click `Add/Remove plug-ins...`. Notice no "Sound Finder" or "Silence Finder". You may also notice a warning about "Critical Nyquist files" missing in Help -> Diagnostics -> Show log.

**Comment by ericonr** [comment]
@leahneukirchen

**Comment by harrisonthorne** [comment]
Within the audacity/audacity repo, it seems that the files in both the `nyquist/` and `plug-ins/` directories aren't being installed. (or I don't know where to find them). But copying the files from those directories manually into `/usr/share/audacity/nyquist/` on my system fixes this issue.
