### ISSUE TITLE
Request Review of `Liquidctl` Package Template and Guidance on Maintaining it

### ISSUE THREAD

**Issue by Frick-David** [void-linux/void-packages#24123]
Hey there voiders,

I am working with the creator of `liquidctl` to get it into a void linux package. The creator provided a template file for me to submit to help get it started. I hope to help maintain and get it going.

The template we have is as follows:
```
# Template file for 'liquidctl'
pkgname=liquidctl
version=1.3.3
revision=1
archs=noarch
build_style=python3-module
hostmakedepends="python3-setuptools"
depends="python3-setuptools python3-usb libusb python3-hidapi python3-docopt"
short_desc="Monitor and control liquid coolers and other devices"
maintainer="David Frick <name@domain>"
license="GPL-3.0-or-later"
homepage="https://github.com/jonasmalacofilho/liquidctl"
distfile="${PYPI_SITE}/l/liquidctl/liquidctl-${version}.tar.gz"
checksum=d13180867e07420c5890fe1110e8f45fe343794549a9ed7d5e8e76663bc10c24

pre_build() {
    # upstream encourages the use of these env vars, at setup.py build time, to
    # customize the output of liquidctl --version
    export DIST_NAME="$(source /etc/os-release && echo "$PRETTY_NAME")"
    export DIST_PACKAGE="$pkgname $version-$revision"
}

post_install() {
	vman liquidctl.8
	for f in docs/*.md; do
		vdoc "$f"
	done
}

# liquidctl can be used as a CLI or as a Python module, but unsure on how to
# split the packages, especially because the CLI is a setuptools script:
# setup.py will generate the actual executable, a Python script that simply
# calls liquidctl.cli.main
python3-liquidctl_package() {
	depends="liquidctl>=${version}_${revision}"
	build_style=meta
	short_desc+=" (transitional dummy package)"
}

# TODO package trezor/cython-hidapi as python3-hidapi
# QUESTION shouldn't python3-usb depend on libusb or another backend?
# QUESTION does Void populate os-release $PRETTY_NAME with something useful?
# QUESTION how should the split be handled?
```

Can I have someone help me review this, finialize it then help me set it up to wear I can maintain it?
That would be much appreciated.

Best,
David

**Comment by ericonr** [comment]
> export DIST_NAME="$(source /etc/os-release && echo "$PRETTY_NAME")"

I don't see any issue with just setting `DIST_NAME="Void Linux"` directly.

I wouldn't split the package at all, tbh.

> # QUESTION shouldn't python3-usb depend on libusb or another backend?

@sgn?

**Comment by sgn** [comment]
> > QUESTION shouldn't python3-usb depend on libusb or another backend?
> 
> @sgn?

Correct, it's my mistake. I added `python3-usb` to support `yubikey-manager` and `yubikey-manager` pulls `libusb` in via `pcsc-ccid`, hence, noone noticed the brokenness, I'll fix it.

Thanks for the ping.

**Comment by Frick-David** [comment]
```
# Template file for 'liquidctl'
pkgname=liquidctl
version=1.3.3
revision=1
archs=noarch
build_style=python3-module
hostmakedepends="python3-setuptools"
depends="python3-setuptools python3-usb libusb python3-hidapi python3-docopt"
short_desc="Monitor and control liquid coolers and other devices"
maintainer="David Frick <name@domain>"
license="GPL-3.0-or-later"
homepage="https://github.com/jonasmalacofilho/liquidctl"
distfile="${PYPI_SITE}/l/liquidctl/liquidctl-${version}.tar.gz"
checksum=d13180867e07420c5890fe1110e8f45fe343794549a9ed7d5e8e76663bc10c24

pre_build() {
    # upstream encourages the use of these env vars, at setup.py build time, to
    # customize the output of liquidctl --version
    export DIST_NAME="Void Linux"
    export DIST_PACKAGE="$pkgname $version-$revision"
}

post_install() {
	vman liquidctl.8
	for f in docs/*.md; do
		vdoc "$f"
	done
}

# setup.py will generate the actual executable, a Python script that simply
# calls liquidctl.cli.main
python3-liquidctl_package() {
	depends="liquidctl>=${version}_${revision}"
	build_style=meta
	short_desc+=" (transitional dummy package)"
}
```
@sgn I should be good to go to add `python3-usb as a dependency correct?

Can I get another review before I PR this?

**Comment by ericonr** [comment]
We don't use noarch anymore.

The comment on the subpackage shouldn't be necessary. That said, why is there a subpackage at all? `python3-liquidctl` doesn't exist as a current package.

(feel free to discuss these in the PR)

**Comment by Frick-David** [comment]
Will make those changes and open a PR.

**Comment by jonasmalacofilho** [comment]
@Frick-David

You may also want update to 1.4.2 and include the provided udev rules and additional documentation.  You can use the [liquidctl<sup>AUR</sup>](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=liquidctl) recipe as a reference.

**Comment by Frick-David** [comment]
This is on hold while I package `python3-hidapi` / `python3-hid.` I thought these were packaged but it appears not and I can not build liquidctl without it. See #19670

**Comment by cat-marin** [comment]
I can't seem to build liquidctl - has anyone been able to get this working recently? I had it working briefly but it broke after an update and I can't get it to build again.

**Comment by juipeltje** [comment]
i'm not sure if i should make a new issue or necrobump this one, but i came across this when i was looking to see if someone had already made a template file for liquidctl, and i decided to update the one in this post to practice making templates.

```
# Template file for 'liquidctl'
pkgname=liquidctl
version=1.13.0
revision=1
build_style=python3-pep517
hostmakedepends="python3-setuptools python3-setuptools_scm python3-wheel"
depends="python3-setuptools python3-usb python3-crcmod python3-hid python3-docopt python3-Pillow python3-smbus libusb"
short_desc="Monitor and control liquid coolers and other devices"
maintainer="juipeltje <joppe4444@outlook.com>"
license="GPL-3.0-or-later"
homepage="https://github.com/jonasmalacofilho/liquidctl"
distfiles="https://github.com/liquidctl/liquidctl/releases/download/v1.13.0/liquidctl-1.13.0.tar.gz"
checksum="ee17241689c0bf3de43cf4d97822e344f5b57513d16dd160e37fa0e389a158c7"

pre_build() {
    # upstream encourages the use of these env vars, at setup.py build time, to
    # customize the output of liquidctl --version
    export DIST_NAME="Void Linux"
    export DIST_PACKAGE="$pkgname $version-$revision"
}

post_install() {
	vman liquidctl.8
	for f in docs/*.md; do
		vdoc "$f"
	done
}
```
liquidctl also requires python3-colorlog to be installed though, which is not in the void repos, so i made a template file for that as well:
```
# Template file for 'python3-colorlog'
pkgname=python3-colorlog
version=6.7.0
revision=1
build_style=python3-module
hostmakedepends="python3-setuptools"
short_desc="Add colours to the output of Python's logging module"
maintainer="juipeltje <joppe4444@outlook.com>"
license="MIT"
homepage="https://pypi.org/project/colorlog/#description"
distfiles="https://files.pythonhosted.org/packages/78/6b/4e5481ddcdb9c255b2715f54c863629f1543e97bc8c309d1c5c131ad14f2/colorlog-6.7.0.tar.gz"
checksum="bd94bd21c1e13fac7bd3153f4bc3a7dc0eb0974b8bc2fdf1a989e474f6e582e5"
```
i'm still a noob when it comes to making templates, so i'm not sure if there's anything else that should be added to the template for the sake of completeness, but they do install succesfully and i got liquidctl running with these. i think the distfiles url in python3-colorlog could be shortened with the pypi site variable, but i'm not entirely sure.
