### ISSUE TITLE
Package request: sof-firmware

### ISSUE THREAD

**Issue by kotoko** [void-linux/void-packages#24162]
Package: `sof-firmware`
Description: Firmware related to audio drivers in linux kernel.
Homepage: https://thesofproject.github.io/latest/introduction/index.html
License (from FAQ):
> Most of the host driver code is dual-licensed BSD or GLPLv2 only (user’s choice). The part of the driver that is GPLv2 only is the Linux integration layer at the top of the driver stack.

I looked shamelessly at [gentoo ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-firmware/sof-firmware/sof-firmware-1.5.1.ebuild) and it looks easy to implement.

After updating my void to linux5.7 audio stopped working. After looking to the output of `dmesg` I'm guessing that I'm missing sof-firmware (not sure). Hence package request.

**Comment by kotoko** [comment]
[Here](https://forums.linuxmint.com/viewtopic.php?f=48&t=311714&sid=66ec8353cda692d136d028b2ae3d977c&start=20) someone mentions that this stuff is new - first release was in April and it suppose to be used primarily in future. I don't know anything more than that.

**Comment by cinerea0** [comment]
I've opened a PR to add this to the repos. It'll be called `sof-bin` instead of `sof-firmware` because of Void's package naming conventions, but it will provide the same files.
