### ISSUE TITLE
Consider new void images / current images don't support Navi 14 GPUs

### ISSUE THREAD

**Issue by robodrew** [void-linux/void-packages#24186]
The kernel that ships with the available void iso files doesn't support Navi 14 GPUs. I have an RX 5500 XT and was not able to boot my system without setting kernel parameters `amd_iommu=off iommu=off amdgpu.noretry=0`

I imagine issues like this are going to crop up with increasing frequency as the images age and new hardware is released. Is it worth releasing new images, at least for the base (non-DE) install?

**Comment by Noah-Huppert** [comment]
Looks like the last images were built November 2019. I just built an x86_64 ISO if you want to try and see if this fixes the problem: https://public.funkyboy.zone/noah/void/void-live-x86_64-5.7.14_1-20200810.iso

PS: this issue is probably better suited for [void-linux/void-mklive](https://github.com/void-linux/void-mklive).

**Comment by robodrew** [comment]
I'll give it a crack tonight and report back, thanks. I imagine it'll boot without issue.

I did think about putting the issue in void-mklive but thought it less of an issue with the tools for making images rather than the age of the packages included with the current images. Do you think I should raise another issue in void-mklive once I've tested out your iso?

**Comment by robodrew** [comment]
I didn't have the time to test it last night, but I did spin it up tonight. Worked like a charm. Booted up without changing any kernel parameters. 

Thanks for taking the time to make the image so I could test it out.

I'm going to close this issue, and make a new one in void-mklive.

**Comment by Noah-Huppert** [comment]
Great! Glad I could help :)
