### ISSUE TITLE
Since runit update, previous power down commands reboot the system now

### ISSUE THREAD

**Issue by D-Nice** [void-linux/void-packages#24207]
### System

* xuname:  
  `Void 5.7.14_1 x86_64 GenuineIntel notuptodate hold rrDDDDFFFF` with old runit
  `Void 5.7.14_1 x86_64 GenuineIntel uptodate hold rrDDDFFFF` with latest runit

* package:  
  `runit-void-20200720_1.x86_64`

### Expected behavior
`poweroff`, `shutdown`, `halt`, with the appropriate flags to lead to a power down, or in the case of touching the power button, as previously, to lead to a power down.

### Actual behavior
All those commands and actions lead to a reboot, and the final init message indicates a reboot was requested.

### Steps to reproduce the behavior
`sudo poweroff` with aforementioned pkg, at least on my system.

Reverting to `runit-void-20190906_3.x86_64` stops this from happening, and there were apparent changes done to how runit handles reboots, but turning everything into a reboot for me does not seem like a desired effect.

Revelant PR: https://github.com/void-linux/void-packages/pull/23668

Additional info:

`runit-void-20190906_3.x86_64` - `ls -l /run/runit/{reboot,stopit}` output:
```
ls: cannot access '/run/runit/reboot': No such file or directory
---x------ 1 root root 0 Aug 10 16:22 /run/runit/stopit
```

`runit-void-20200720_1.x86_64` - `ls -l /run/runit/{reboot,stopit}` output:
```
---------- 1 root root 0 Aug 10 16:39 /run/runit/reboot
---------- 1 root root 0 Aug 10 16:39 /run/runit/stopit
```

**Comment by ericonr** [comment]
By chance, are you holding / no extracting any of the files in the runit-void package? Check `/etc/xbps.d`. If for some reason you're using `/etc/runit/3` from the old the package, the system will indeed reboot by default.

**Comment by D-Nice** [comment]
good point, I indeed am, I'll have a look about merging the two for my system.

**Comment by ahesford** [comment]
Please try a stock `/etc/runit/3` and confirm that everything works before attempting to merge your changes.

**Comment by D-Nice** [comment]
confirmed it works after merging (didn't need to try stock, and my runit/3 doesn't change anything, just had various additions)! Thanks for the help and quick note regarding the issue on my system.

As I have run into this previously, forgetting the various changes I've done (which is my fault), a nice-to-have would be to get a warning in case of hold conflicts, I may be more likely to look into them and resolve them myself, as may be the case with others, unless something like this already happens, in which case knowing it would be useful for future updates.

Anyways, closing this issue, as it was system specific to me and changes I had done.

**Comment by ericonr** [comment]
Any reason you can't use `/etc/rc.shutdown` for these actions instead of a custom `/etc/runit/3`?

**Comment by D-Nice** [comment]
yes, because I need some of these run before services are stopped, among other actions. In fact, one of these is a "rc.pre-shutdown" hook, exactly for that case. Technically, if this was in by default, as some requested, I wouldn't have to use runit/3 and could put most things there.

**Comment by ericonr** [comment]
I don't see any comments in https://github.com/void-linux/void-runit/issues/23 besides some contributors. Do you have ideas for the design, explanations for your use case? Void contributors have limited time and some solutions are hard to come by, help is definitely appreciated. If you have your own version of runit files, an easier way of avoiding issues is by having a custom package that pulls from your repository, that way you can easily check changes made to the void-runit repository and not be caught by surprise.

**Comment by D-Nice** [comment]
I've made comments regarding my specific issue, and one of the reasons why I had to edit runit/3 here.

https://github.com/void-linux/void-runit/issues/16

Please don't read negatively into my comments, in case you may be, I'm highly appreciative of the work and effort, and if anything am sorry I took time from you guys with this issue, as it is my fault for changing configurations users are warned against touching.

Still, a conflict notification would again be a nice to have for me, and maybe others who may put preserve/holds on files.
