### ISSUE TITLE
[Package Request] news_flash_gtk as FeedReader (predecessor) is no longer actively maintained

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#24204]
I tried to prepare a template for this but didn't figure out how to get it working... so I opened this issue instead of a proper PR.

Package: https://gitlab.com/news-flash/news_flash_gtk

My attempt at a template:
```sh
# Template file for news-flash-gtk
pkgname=news_flash_gtk
version=1.0+rc1
_ver="${version/+/-}"
revision=1
wrksrc="${pkgname}-${_ver}"
build_style=meson
build_helper=rust
short_desc="A modern gtk feed-reader written in rust"
hostmakedepends="pkg-config glib-devel cargo"
makedepends="gtk+-devel webkit2gtk-devel libhandy-devel sqlite-devel gettext-devel libressl-devel rust-std"
license="GPL-3.0-only"
maintainer="******************************"
homepage="https://gitlab.com/news-flash/news_flash_gtk"
distfiles="${homepage}/-/archive/1.0-rc1/${pkgname}-${_ver}.tar.gz"
checksum="9c5d65699c9aba582e0c7b453d28e5bf430f449b4e7369958970947164f99ccb"
```
I hope this proves to be useful (even though it is not working). 
Maybe I can learn a thing or two once this is packaged :smile:

**Comment by ericonr** [comment]
It's probably best if you explain what went wrong in the template as well.

**Comment by martnnw** [comment]
```
news_flash_gtk-1.0+rc1_1: do_configure: '${meson_cmd} --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/bin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --buildtype=plain --auto-features=enabled --wrap-mode=nodownload -Db_lto=true -Db_ndebug=true -Db_staticpic=true ${configure_args} . ${meson_builddir}' exited with 1
=> ERROR:   in do_configure() at common/build-style/meson.sh:96
```
This is the error output I got (I don't get it at all). 
But I still tried to define do_configure() so that similar to the build instructions on the GitLab page but got a similar error.

Here are the build instructions:
```sh
meson --prefix=/usr build
ninja -C build
sudo ninja -C build install
```
Meanwhile I updated the template to be easier to edit (added a variable for substitution) See template ^

**Comment by ericonr** [comment]
There must have been some output before that explaining the actual error. Can you show that?

**Comment by martnnw** [comment]
Hold up I probably missing ninja ... right?

**Comment by ericonr** [comment]
No, build style meson implies ninja

**Comment by martnnw** [comment]
Rust linker for the host machine: rustc ld.bfd 2.34
```
Host machine cpu family: x86_64
Host machine cpu: x86_64
Using 'PKG_CONFIG' from environment with value: 'pkg-config'
Did not find pkg-config by name 'pkg-config'
Found Pkg-config: NO
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency glib-2.0 found: NO

meson.build:11:0: ERROR: Pkg-config binary for machine MachineChoice.HOST not found. Giving up.
```

Ok that makes things a lot clearer.

**Comment by ericonr** [comment]
Add `pkg-config` to `hostmakedepends` and you might need `glib-devel` in `makedepends`.

**Comment by martnnw** [comment]
already did it:
Next issue:
```+ cargo build --release --manifest-path=../Cargo.toml
    Updating crates.io index
    Updating git repository `http://gitlab.com/news-flash/news_flash_base.git`
error: failed to get `news-flash` as a dependency of package `news_flash_gtk v0.0.0 (/builddir/news_flash_gtk-1.0-rc1)`

Caused by:
  failed to load source for dependency `news-flash`

Caused by:
  Unable to update http://gitlab.com/news-flash/news_flash_base.git?branch=1-0-0-rc-1

Caused by:
  failed to find branch `1-0-0-rc-1`

Caused by:
  cannot locate local branch '1-0-0-rc-1'; class=Reference (4); code=NotFound (-3)
FAILED: src/com.gitlab.newsflash
/bin/bash /builddir/news_flash_gtk-1.0-rc1/build-aux/cargo.sh .. src/com.gitlab.newsflash /builddir/news_flash_gtk-1.0-rc1/build ''
ninja: build stopped: subcommand failed.
```

it apparently also needed `cargo` and `gettext`

**Comment by ericonr** [comment]
Add `build_helper=rust` and remove `rust` and `cargo` from `hostmakedepends`

**Comment by martnnw** [comment]
I forgot to mention that it requires openssl. However I built it before without xbps-src and it worked fine. I really sorry if that caused any inconvinece. 

here are the actual required dependencies:
devel of `gtk, webkit2gtk, libhandy, sqlite3, gettext and openssl` (replaced openssl-devel with libressl-devel)
I can not believe I missed some of these while writing the template. Never hurts to look twice.
I updated the template above so you can keep track of the changes I made.


New error:
```
+ cargo build --release --manifest-path=../Cargo.toml
/builddir/news_flash_gtk-1.0-rc1/build-aux/cargo.sh: line 24: cargo: command not found
FAILED: src/com.gitlab.newsflash
/bin/bash /builddir/news_flash_gtk-1.0-rc1/build-aux/cargo.sh .. src/com.gitlab.newsflash /builddir/news_flash_gtk-1.0-rc1/build ''
ninja: build stopped: subcommand failed.
=> ERROR: news_flash_gtk-1.0+rc1_1: do_build: '${make_cmd} -C ${meson_builddir} ${makejobs} ${make_build_args} ${make_build_target}' exited with 1
=> ERROR:   in do_build() at common/build-style/meson.sh:122
```

**Comment by ericonr** [comment]
Damn, I was very mistaken, sorry. Keep the build helper, but do like the `fractal` template does for `rust`, `cargo` and `rust-std`.

**Comment by ericonr** [comment]
Also, at this point, you should just open a PR. Make sure to follow the commit naming in `CONTRIBUTING.md`, and go ahead.

**Comment by martnnw** [comment]
I'll do that tomorrow. 
But thank you for your help! Hopefully I'll be able to do it by myself soon.

**Comment by paper42** [comment]
newsflash is now packaged: 0045ad74e93b765a88a9496f795122c6a1ad8598
