### ISSUE TITLE
[Request] Remove polkit, elogind dependencies of fwupd

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#24235]
According to this, fwupd should not require elogind or polkit:

https://github.com/fwupd/fwupd/wiki/fwupd-without-systemd,-elogind-or-ConsoleKit

**Comment by ericonr** [comment]
This could be a build option, but I don't think it should be shipped by default, you'd have to build the package yourself.

**Comment by LamaRaz** [comment]
> This could be a build option, but I don't think it should be shipped by default, you'd have to build the package yourself.

In that case, perhaps offer an additional package just for fwupdtool?

**Comment by dkwo** [comment]
Wouldn't the proposed edit be closes to KISS ideology?

**Comment by ericonr** [comment]
Closing due to account being removed.

@dkwo no, KISS would be keeping it as close to what upstream recommends :)

**Comment by mjk-gh** [comment]
Uhm, the issue has been closed due to the reporting user account has been removed? Well, then I would take that user's place, regarding this issue. Is this comment enough to re-open the issue or should I open a new issue?
