### ISSUE TITLE
FBTFS: qemu

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#24262]
This happens in `do_install()`:
```
mkdir: cannot create directory ‘dtc/libfdt/libfdt.h’: File exists
make: *** [Makefile:538: dtc/libfdt/libfdt.h] Error 1
=> ERROR: qemu-5.0.0_2: do_install: 'make DESTDIR=${DESTDIR} install' exited with 2
=> ERROR:   in do_install() at srcpkgs/qemu/template:81
```

Line 538 of Makefile is:
```
        @mkdir -p $@
```
and it tries to create a directory with the name `dtc/libfdt/libfdt.h` here, not only `dtc/libfdt`.

**Comment by Johnnynator** [comment]
Maybe solved with 040dec83aa8563a9802669a9a163c9e2febc6dc1 ? (Or most likely is)

**Comment by pullmoll** [comment]
Oh. I can try this here.

**Comment by sgn** [comment]
I added `broken` to `qemu` to unblock the build server.
