### ISSUE TITLE
GCC cannot compile 32 bit programs even with libgcc-32bit installed

### ISSUE THREAD

**Issue by 0syf3r** [void-linux/void-packages#24270]
### System

* xuname:  
  `Void 5.7.12_1 x86_64 GenuineIntel uptodate rrmFF`
* package:
  `gcc-9.3.0_6`
  `libgcc-32bit-9.3.0_6`

### Expected behavior
`gcc -m32` works.
### Actual behavior
```
/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/libgcc.a when searching for -lgcc
/bin/ld: cannot find -lgcc
/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/9.3.0/libgcc.a when searching for -lgcc
/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
```
### Steps to reproduce the behavior
Create test.c:
```
int main() { return 0; }
```
Run
`gcc test.c -o test -m32`

**Comment by Duncaen** [comment]
You need `gcc-multilib` not `libgcc-32bit`.

**Comment by 0syf3r** [comment]
What's the difference between 32bit and multilib? Pretty confusing naming scheme if you ask me.

**Comment by ericonr** [comment]
`libgcc-32bit` is the `libgcc` package for i686 made available on x86_64. `gcc-multilib` is the compiler capable of working in a multilib setup.

**Comment by Duncaen** [comment]
`-32bit` are packages/libraries built for 32bit x86. `gcc-multilib` are just split out parts of the x86_64 gcc built for -m32 support.

**Comment by ericonr** [comment]
Also, if you need to link to libgcc you probably need the `libgcc-devel-32bit` package.
