### ISSUE TITLE
[Package Request] libxft-bgra

### ISSUE THREAD

**Issue by skuzzymiglet** [void-linux/void-packages#24292]
https://github.com/uditkarode/libxft-bgra fixes color emoji rendering in libXft. It's available in the AUR already but not on Void.

It's pretty essential to any suckless user, so it would be nice to have it on Void's repos.

I tried building it from Git today, but Xrender pkg-config files were missing

**Comment by q66** [comment]
we don't accept special patched versions of normal packages, either get it fixed in upstream or work around it locally
