### ISSUE TITLE
XBPS_PKG_OPTIONS_<package> isn't working

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#24313]
### Expected behavior

Setting `XBPS_PKG_OPTIONS_execline=static` in `etc/conf` and running `./xbps-src pkg execline` should build a statically linked `execline` package.

### Actual behavior

The package is built normally, as if no option had been selected.

---

Need to take a look through the code to see where the variable is lost.

**Comment by fosslinux** [comment]
Is this even meant to work? I can't find *any* reference to `XBPS_PKG_OPTIONS_package` in the repository.

**Comment by ericonr** [comment]
From `README.md`

```
Permanent global package build options can be set via `XBPS_PKG_OPTIONS` variable in the
`etc/conf` configuration file. Per package build options can be set via
`XBPS_PKG_OPTIONS_<pkgname>`.
```

And from `common/xbps-src/shutils/common.sh`:

```
        _pkgname=${pkgname//[^A-Za-z0-9_]/_}
        eval pkgopts="\$XBPS_PKG_OPTIONS_${_pkgname}"
        if [ -z "$pkgopts" -o "$pkgopts" = "" ]; then
            pkgopts=${XBPS_PKG_OPTIONS}
        fi
```
