### ISSUE TITLE
racer is tracking nightly rust

### ISSUE THREAD

**Issue by faulesocke** [void-linux/void-packages#2437]
The package racer will not build in the recent version any longer since they are now tracking the nightly rust compiler. There are multiple ways to deal with this:

- depend on rustup instead of rust and cargo, and during compilation of racer download a (precompiled!) nightly rust compiler
- package nightly rust
- keep the package in the 2.0.14 version around for some time but drop it eventually - people who require it, can conveniently build it on their own with a single command

I don't feel really good with the first option, since I don't like downloading pre-compiled binaries (even when they are from the same source as the sourcecode is). What are your oppinions?

**Comment by maxice8** [comment]
i'm for option 3.

I have no desire to keep packages that follow unstable releases and it is easy for people that want it to do it.

**Comment by Gottox** [comment]
Going for option 3.
