### ISSUE TITLE
man-pages-devel opens non-specific manpages (e.g. string(3) instead of strstr(3))

### ISSUE THREAD

**Issue by mlugg** [void-linux/void-packages#24434]
### System

* xuname: Void 5.7.14_1 x86_64 AuthenticAMD notuptodate rrrmFFFF
* package: man-pages-devel-5.08_1

(with mdocml-1.14.5_5)

### Expected behavior

`man strstr` (or many other functions present in the string.3 manpage) opens the manpage at `/usr/share/man/man3/strstr.3`.

### Actual behavior

The page at `/usr/share/man/man3/string.3` is opened instead.

### Steps to reproduce the behavior

Install `man-pages-devel` and try to open a manpage for any function which:
- Is documented in string(3)
- Has a name which comes lexicographically after `string` (e.g. `strstr`, `strlen`)

**Comment by ericonr** [comment]
Being looked into in #23108

**Comment by ericonr** [comment]
Fixed in https://github.com/void-linux/void-packages/pull/27360
