### ISSUE TITLE
Libreoffice-writer dependencies outdated for v7

### ISSUE THREAD

**Issue by sburris0** [void-linux/void-packages#24440]
### System
* xuname:  
`Void 5.7.17_1 x86_64 AuthenticAMD uptodate rrrmFFFF`
* package:  
  `libreoffice-writer-7.0.0.3_1`

### Expected behavior
After installing libreoffice-writer, it should run (worked fine in version 6)

### Actual behavior
The splash screen hangs indefinitely.
(May also complain about a missing Java runtime, if one isn't installed)

### Steps to reproduce the behavior
1. Uninstall libreoffice
2. Install libreoffice-writer
3. Try to start `lowriter`
4. Wait forever

**Comment by ericonr** [comment]
@pullmoll

**Comment by pullmoll** [comment]
Looking into it. I didn't notice problems after updating, but you say it's after uninstall/install which I didn't test.

**Comment by pullmoll** [comment]
Works for me. But I also installed `libreoffice-i18n-de`.
Does it work for you after installing at least one i18n package?

**Comment by sburris0** [comment]
@pullmoll 
Just tested it, installing at least one language pack does indeed fix this for me.

**Comment by ericonr** [comment]
Is there a good way of solving this, besides adding several INSTALL msgs for each subpackage that doesn't pull in the `i18n` packages?

Otherwise we should just close the issue.

**Comment by pullmoll** [comment]
I don't think we should add dependencies on a i18n package or an INSTALL.msg to sub packages.
A note in the Void documentation would be useful for those who prefer to install just one of the subpackages.
The average user will probably install the `libreoffice` meta package and not face this *problem*.
Closing because I see no way to easily solve this on the packaging side.

**Comment by anddam** [comment]
> I don't think we should add dependencies on a i18n package 

How so?

Considering the system and the program itself are already in (US) English by default, I —as a non-English speaker— would rather have a _non-strictly-necessary_ dependency on `libreoffice-i18n-en-US`and have a sane setup after installing `libreoffice-writer` than not.
