### ISSUE TITLE
exa command do not include fish completion

### ISSUE THREAD

**Issue by chshbh** [void-linux/void-packages#24498]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
> Void 5.7.18_1 x86_64 GenuineIntel notuptodate rrFFF

* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
> exa-0.9.0_1
### Expected behavior
The exa source code in it's original form contains fish shell completion. While the void-package provides with bash and zsh shell completion, it is missing the same for fish shell.

### Actual behavior
[This](https://github.com/void-linux/void-packages/tree/master/srcpkgs/exa) package do not generate fish completion file and put the [dot]fish file as the `$(whereis fish)/vendor_completions.d/exa.fish`

### Steps to reproduce the behavior
+ `sudo xbps-install -Suyv fish exa`
+ enter `fish` shell
+ hit tab key after typing exa for auto tab completion.

**Comment by ericonr** [comment]
Could you test the linked PR?
