### ISSUE TITLE
qbittorrent-nox: symbol lookup error on launch

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [void-linux/void-packages#24512]
### System

* xuname:  
  Void 5.7.17_1 x86_64 GenuineIntel notuptodate rrFF
* package:  
  qbittorrent-nox-4.2.5_2

### Expected behavior

The program launches

### Actual behavior

```
qbittorrent-nox: symbol lookup error: qbittorrent-nox: undefined symbol: _ZNK10libtorrent5entry4dictB5cxx11Ev
```

### Steps to reproduce the behavior

```
$ sudo xbps-install -S qbittorrent-nox
...

$ qbittorrent-nox
qbittorrent-nox: symbol lookup error: qbittorrent-nox: undefined symbol: _ZNK10libtorrent5entry4dictB5cxx11Ev
```

Additional info:

I have 2 libtorrent libraries in /usr/lib:
```
/usr/lib/libtorrent-rasterbar.so.10.0.0
/usr/lib/libtorrent-rasterbar.so.10
```

`qbittorrent-nox` is linking against `libtorrent-rasterbar.so.10`

**Comment by ericonr** [comment]
Do you know how to build packages using `xbps-src`? Might be a good idea to rebuild qbittorrent and try to install. It probably requires a rebuild. I'm trying it out right now, if it works I can make a PR.

**Comment by pullmoll** [comment]
FWIW I get a similar error for qbittorrent from my repository where I built everything using gcc10. The error here is:
```
qbittorrent: symbol lookup error: qbittorrent: undefined symbol: _ZN10libtorrent5entryC1ESt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES0_NS_3aux12strview_lessESaISt4pairIKS7_S0_EEE
```
I'll rebuild qbittorrent once more, because I think it was built before the libtorrent revbump for libressl-3.1.3, and see if that solves the problem.

**Comment by ericonr** [comment]
@pullmoll rebuilding didn't work for me, it errored out. I'm trying to fix by reverting `libtorret-rasterbar`. Otherwise we might need to patch qbittorrent.

**Comment by ThatNerdyPikachu** [comment]
reverting `libtorrent-rasterbar` might also fix an issue with `deluge` where calls to `libtorrent::move_storage` fail since the bindings signatures don't match the libraries.

maybe.

**Comment by ericonr** [comment]
@ThatNerdyPikachu can you check if this fixes deluge as well? If not, I can rebuild it as well.

**Comment by ThatNerdyPikachu** [comment]
@ericonr Sure thing.

(I should build libtorrent on my end from your repo... right? time to look at docs)

**Comment by ericonr** [comment]
> (I should build libtorrent on my end from your repo... right? time to look at docs)

Technically speaking you can just downgrade the package, it should be in `/var/cache/xbps`... https://docs.voidlinux.org/xbps/advanced-usage.html#via-xdowngrade

**Comment by ThatNerdyPikachu** [comment]
Not in my case... I purge xbps cache daily, for some stupid reason. (I really need to stop doing that.)

**Comment by ThatNerdyPikachu** [comment]
So should I build with that commit reverted + test deluge (and qbittorrent)?

**Comment by ericonr** [comment]
yes! I have already tested qbittorrent, but someone else doesn't hurt.

**Comment by ericonr** [comment]
If you want, you can just clone from my fork directly and use the specific branch.

**Comment by ThatNerdyPikachu** [comment]
Sure.

p.s. does xbps-bootstrap + building a package clutter up the system in any way? or is it contained?

**Comment by pullmoll** [comment]
I also get an error trying to build qbittorrent with the current libtorrent. I guess we should revert the most recent update.

**Comment by ericonr** [comment]
@ThatNerdyPikachu 

> p.s. does xbps-bootstrap + building a package clutter up the system in any way? or is it contained?

Just do

```
$ cd void-packages
$ ./xbps-src binary-bootstrap
$ ./xbps-src pkg libtorrent-rasterbar
$ xi libtorrent-rasterbar # this one comes from xtools
```

It is self contained.

@pullmoll that's what I have in my PR.

**Comment by ThatNerdyPikachu** [comment]
qbit works.
Deluge will need a rebuild before I can confirm it works, how would I go about doing that @ericonr ?

Deluge stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deluge/_libtorrent.py", line 23, in <module>
    import deluge.libtorrent as lt
ModuleNotFoundError: No module named 'deluge.libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/deluged", line 11, in <module>
    load_entry_point('deluge==2.0.3', 'console_scripts', 'deluged')()
  File "/usr/lib/python3.8/site-packages/deluge/core/daemon_entry.py", line 90, in start_daemon
    from deluge.core.daemon import is_daemon_running
  File "/usr/lib/python3.8/site-packages/deluge/core/daemon.py", line 22, in <module>
    from deluge.core.core import Core
  File "/usr/lib/python3.8/site-packages/deluge/core/core.py", line 28, in <module>
    from deluge._libtorrent import LT_VERSION, lt
  File "/usr/lib/python3.8/site-packages/deluge/_libtorrent.py", line 25, in <module>
    import libtorrent as lt
ImportError: /usr/lib/python3.8/site-packages/libtorrent.so: undefined symbol: _ZNK10libtorrent5entry4dictEv
```

**Comment by ThatNerdyPikachu** [comment]
Alright, a rebuild of deluge makes it launch again, testing the move storage functionality now.

**Comment by ThatNerdyPikachu** [comment]
Everything works with #24514.

**Comment by ericonr** [comment]
Great! Thanks for reporting it c:
