### ISSUE TITLE
qbittorrent won't start

### ISSUE THREAD

**Issue by p2501mk** [void-linux/void-packages#24542]
I don't exactly know if libtorrent or libtorrent-rasterbar is the issue.

Expected behaviour: qbittorrent starts.

Current behaviour after update: Startup fails with error

`qbittorrent: symbol lookup error: qbittorrent: undefined symbol: _ZN10libtorrent5entryC1ESt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES0_NS_3aux12strview_lessESaISt4pairIKS7_S0_EEE`

Versions installed

libtorrent-0.13.8_2
libtorrent-rasterbar-1.2.9_1
qbittorrent-4.2.5_2

Note: My first bug report. Please advise for improvements in accuracy.

**Comment by Johnnynator** [comment]
The qbittorrent  and libtorrent-rasterbar version are not the ones that should be in an up to date system, `qbittorrent-4.2.5_3` and `libtorrent-rasterbar-1.2.7_3` would be the current ones. Which arch and repo(mirror) are you using? (Always install `xtools` and add the output from `xuname` to your bug reports).

My guess would be, that you are running `aarch64`, the aarch64 builders are kinda blocked right now, and it can take some time until the changes are in the binary repo.

**Comment by p2501mk** [comment]
Thank you, that's the issue. Xuname alerted me to my system not being up to date. Everythings peachy now!
