### ISSUE TITLE
virtualbox-ose-dkms: fails to build DKMS module on the latest kernel

### ISSUE THREAD

**Issue by FirstZero** [void-linux/void-packages#24551]
* xuname:  
    Void 5.8.5_1 x86_64 AuthenticAMD uptodate rrrrmmnFFFFFFF
* package:  
    virtualbox-ose-6.1.10_2
    virtualbox-ose-dkms-6.1.10_2

### Expected behavior
The DKMS module for virtualbox-ose-6.1.10 is getting built.

### Actual behavior
The DKMS module for virtualbox-ose-6.1.10 is not getting built.
> [*] Configuring unpacked packages
virtualbox-ose-dkms-6.1.10_2: configuring ...
DKMS module 'virtualbox-ose-6.1.10' already added, skipping.
Skipping kernel-5.3.18_1. kernel-headers package not installed...
Building DKMS module 'virtualbox-ose-6.1.10' for kernel-5.8.5_1... FAILED!
DKMS module 'virtualbox-ose-6.1.10' failed to build, please check /var/lib/dkms
for errors in the log file.
virtualbox-ose-dkms-6.1.10_2: installed successfully.

### Steps to reproduce the behavior
Install or rebuild virtualbox-ose-dkms on the latest kernel linux5.8

**Comment by sgn** [comment]
You need `linux5.8-headers` packages, in general, you need to install corresponding for the kernel to build dkms.

**Comment by ericonr** [comment]
> Skipping kernel-5.3.18_1. kernel-headers package not installed...

**Comment by FirstZero** [comment]
Last time I checked I was sure I had it installed..

Checking again I didnt.. lets pretend this didnt happen and close that.

**Comment by FirstZero** [comment]
Alright actually Im going to reopen this because installing the headers didnt fix the issue.
Note that its saying it cant find `kernel-5.3.18_1`. But the installed version by linux5.8-headers/linux5.8 is kernel-5.8.5_1.
I wasnt able to find linux5.3 headers either

**Comment by pullmoll** [comment]
I can confirm that `virtualbox-ose-dkms` fails to build for `linux5.8`. There is no easy solution and `virtualbox-ose-6.1.12` does not fix the problem(s) either. See: https://www.virtualbox.org/ticket/19644
I tried to apply the patches to `virtualbox-ose-6.1.12` but we'd have to patch the kernel also (see local_patches in the linked article).

**Comment by steinex** [comment]
VirtualBox 6.1.14 is out which adds support for Linux 5.8.

**Comment by pullmoll** [comment]
https://github.com/void-linux/void-packages/commit/b3ca34dc8ad283f702c77173290f72eff90fc011
