### ISSUE TITLE
hwids-20200813.1_1: the RSA signature is not valid

### ISSUE THREAD

**Issue by valadaa48** [void-linux/void-packages#24577]
# System

* xuname:  Void 5.8.5-arch1-1 aarch64 GenuineIntel notuptodate rFFFF

* package:  
  *affected package(s) including the version*: hwids-20200813.1_1.noarch.xbps

### Expected behavior

xbps-install completes

### Actual behavior

xbps-install doesn't complete

### Steps to reproduce the behavior

```
bash-5.0# xbps-install -Su hwids
[*] Updating repository `https://alpha.us.repo.voidlinux.org/current/aarch64/aarch64-repodata' ...

Name  Action    Version           New version            Download size
hwids update    20200306_1        20200813.1_1           470KB 

Size to download:              470KB
Size required on disk:        1892KB
Space available on disk:       355MB

Do you want to continue? [Y/n] 

[*] Downloading packages
hwids-20200813.1_1.noarch.xbps.sig: 512B [avg rate: 401KB/s]
hwids-20200813.1_1.noarch.xbps: 470KB [avg rate: 12MB/s]
hwids-20200813.1_1: verifying RSA signature...
ERROR: hwids-20200813.1_1: the RSA signature is not valid!
ERROR: hwids-20200813.1_1: removed pkg archive and its signature.
Transaction failed! see above for errors.
```

**Comment by flexibeast** [comment]
As a data point, i didn't have this package installed, but just now installed it without any errors or issues.

**Comment by valadaa48** [comment]
> As a data point, i didn't have this package installed, but just now installed it without any errors or issues.

Are you on aarch64? I have this same failure on 3 separate machines including another independent user as well.

**Comment by flexibeast** [comment]
Ah, interesting - no, i'm on x86_64 (glibc).

**Comment by fosslinux** [comment]
Something super weird is going on with aarch64; it doesn't seem to be signing packages properly RN. 

https://travis-ci.org/github/void-linux/void-packages/builds/722459342
https://travis-ci.org/github/void-linux/void-packages/jobs/722459346

**Comment by Duncaen** [comment]
This should be resolved for hwids at least, there seems to be some race between aarch64 and aarch64-musl for noarch packages. Both builders have to build the package, but the second to finish sees the there is already the same package and just adds the existing package to its repository index. For some reason in this case, the second (aarch64-musl in this case) overwrote the package that was already indexed for aarch64 so the checksum changed.

The build logs containing both hwids builds:
* https://build.voidlinux.org/builders/aarch64-musl_builder/builds/28519/steps/shell_3/logs/stdio 
* https://build.voidlinux.org/builders/aarch64_builder/builds/28132/steps/shell_3/logs/stdio

**Comment by Chocimier** [comment]
Same problem with eigen.

**Comment by Duncaen** [comment]
```
948 -rw-r--r-- 1 void-repomaster void-repomaster 969231 Jun 11 18:46 /hostdir/binpkgs/aarch64/eigen-3.3.7_2.noarch.xbps
  4 -rw-r--r-- 1 void-repomaster void-repomaster    512 Jun 10 15:10 /hostdir/binpkgs/aarch64/eigen-3.3.7_2.noarch.xbps.sig
```

I removed the old signature, not sure what happened at the time.

**Comment by ericonr** [comment]
Has this been solved?

**Comment by sgn** [comment]
I think let's close this one.
