### ISSUE TITLE
font-tamzen: cannot load font.

### ISSUE THREAD

**Issue by nihilismus** [void-linux/void-packages#24590]
### System

* xuname:  
  `Void 5.6.19_1 x86_64 GenuineIntel uptodate rFFFFFF`
* package:  
  `font-tamzen-1.11.4_1`

### Expected behavior
`xterm` should use the `tamzen` bitmap font when one executes `xterm -fn '-*-tamzen-medium-*-*-*-16-*-*-*-*-*-*-*'`, 
### Actual behavior
`xterm` does not use the `tamzen` bitmap font and prints the message: `xterm: cannot load font "-*-tamzen-medium-*-*-*-16-*-*-*-*-*-*-*"`
### Steps to reproduce the behavior
Execute `xterm -fn '-*-tamzen-medium-*-*-*-16-*-*-*-*-*-*-*'` in a terminal.
### Notes
- `tamzen` bitmap font is installed inside `/usr/share/fonts/misc`
- `/usr/share/fonts/misc` is not part of the *font path* when querying it with `xset q | grep -A 1 'Font Path:'`.
- A workaround is to add `/usr/share/fonts/misc` to the *font path* with `xset fp+ /usr/share/fonts/misc`.
- A solution to this package would be to move the `tamzen` bitmap font from `/usr/share/fonts/misc` to `/usr/share/fonts/X11/misc` since `terminus-font` (another bitmap font) does not present this issue with `xterm` and is installed inside this last directory.

**Comment by devvesa** [comment]
May it be that you have the config `no-bitmaps` enabled on your font configuration?

    file /etc/fonts/conf.d/70-no-bitmaps.conf                                                                                                                                                                 
    /etc/fonts/conf.d/70-no-bitmaps.conf: symbolic link to /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf

If that's so, you can remove the link, but then don't expect Firefox to render pretty fonts. See: https://www.reddit.com/r/voidlinux/comments/izm3xb/firefox_ugly_fonts/

(I have had the same problem)
