### ISSUE TITLE
Package request: fvwm3

### ISSUE THREAD

**Issue by 7185** [void-linux/void-packages#24646]
https://github.com/fvwmorg/fvwm3

Should be very close to the fvwm package. I don't know if we should replace it or create a separate package.
The difficulty is that libbson is needed and I don't think it's packaged yet.

**Comment by abenson** [comment]
> Releases
> None. fvwm3 is in development still. The master branch contains what could be considered stable for now, but even then there are no guarantees of stability.

Once they start making stable releases, it can be packaged for Void.

**Comment by 7185** [comment]
https://github.com/fvwmorg/fvwm3/releases/tag/1.0.0

The README isn't up to date.

**Comment by abenson** [comment]
I just saw that! Thanks.
