### ISSUE TITLE
Raspberry pi 5.x kernel missing memory cgroups

### ISSUE THREAD

**Issue by adrian-bl** [void-linux/void-packages#24657]
### System

* xuname:  
Void 5.4.59_1 armv7l Unknown uptodate rFFFF

* package:  
rpi-kernel-5.4.59_1

### Expected behavior

The 5.4 *rbpi* kernel seems to lack support for memory cgroups: this makes it impossible to run any software which requires `/sys/fs/cgroup/memory` to be present.

This breaks nomad for me, but i suppose that docker would also be affected.

Note that the old 4.19.x kernel supported memory cgroups.

I suppose that adding

```
CONFIG_MEMCG=y
CONFIG_MEMCG_SWAP=y
CONFIG_MEMCG_KMEM=y
```

to the kernel config would be sufficient (this is how the x86_64 kernel is configured).

### Steps to reproduce the behavior

```
$ grep cgroup/memory /proc/mounts | wc -l
0
```

### Expected behavior

```
grep cgroup/memory /proc/mounts
cgroup /sys/fs/cgroup/memory cgroup rw,relatime,memory 0 0
```

**Comment by adrian-bl** [comment]
Thanks ericonr!

Adding

```
cgroup_memory=1 cgroup_enable=memory
```

to cmdline.txt actually fixes the issue:

```
bash-5.0# uname -a
Linux pimpel 5.4.59_1 #1 SMP Wed Sep 2 20:17:25 UTC 2020 armv7l GNU/Linux
bash-5.0# mount|grep mem
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
```

So looks like void is not at fault here and that the kernel defaults just changed (for machines with 'low' amounts of RAM)

**Comment by ericonr** [comment]
@adrian-bl this looks like a short enough instruction. Would you like to add it to void-docs?

**Comment by adrian-bl** [comment]
Sounds good to me:

Would
https://docs.voidlinux.org/installation/guides/arm-devices/index.html

be the right page to add the instructions to?

**Comment by ericonr** [comment]
Preferrably in the platforms page, actually!

**Comment by adrian-bl** [comment]
I've created https://github.com/void-linux/void-docs/pull/504

Turns out that this is actually due to a custom change to the rbpi kernel:
https://github.com/raspberrypi/linux/commit/9b0efcc1ec497b2985c6aaa60cd97f0d2d96d203#diff-f1d702fa7c504a2b38b30ce6bb098744
