### ISSUE TITLE
nvidia 390 fails to build for kernel 5.8

### ISSUE THREAD

**Issue by p2501mk** [void-linux/void-packages#24705]
Both DKMS fail to build for every 5.8 series kernel.

### System

* xuname:  
  Void 5.7.19_1 x86_64 GenuineIntel uptodate rrFFFF
* package:  
  basically every 5.8 series kernel release
* affected package(s) including the version:
  virtualbox-ose-6.1.10_2
  nvidia-390.138

### Expected behavior
 DKMS builds

### Actual behavior
 `Building DKMS module: nvidia-390.138... FAILED!
Building DKMS module: virtualbox-ose-6.1.10... FAILED!`

**Comment by flexibeast** [comment]
Re. Virtualbox, refer to #24551.

**Comment by p2501mk** [comment]
> Re. Virtualbox, refer to #24551.

Yes, but there is no up-to-date version of vbox in the repo yet. Thank you for connecting the issue posts tho. :+1:

**Comment by pullmoll** [comment]
https://github.com/void-linux/void-packages/commit/b3ca34dc8ad283f702c77173290f72eff90fc011

**Comment by p2501mk** [comment]
So all that's left now is the nv DKMS.

**Comment by pullmoll** [comment]
Working on it.

**Comment by pullmoll** [comment]
This turns out to be tricky due to:
```
FATAL: modpost: GPL-incompatible module nvidia-uvm.ko uses GPL-only symbol 'radix_tree_preloads'
```
For the other issues I devised a patch, just in case someone else wants to try.
[nvidia390-linux5.8-patch.zip](https://github.com/void-linux/void-packages/files/5204479/nvidia390-linux5.8-patch.zip)

**Comment by pullmoll** [comment]
For reference see https://bugs.gentoo.org/736513

To me it seems as if it's time to switch from Nvidia to some manufacturer who releases their hardware info for developers to write GPL compatible kernel modules.

**Comment by p2501mk** [comment]
It's awesome to have you on the issue, thanks a lot! I can't switch tho..

**Comment by ericonr** [comment]
You can try using nouveau or just an older kernel, in this case.

**Comment by pullmoll** [comment]
We could try to remove `nvidia-uvm` from the modules built in `nvidia390-dkms`.
This would mean no way to access the GPU for CUDA but then the old(er) cards supported by this driver probably are no target for CUDA anyways.

**Comment by pullmoll** [comment]
https://github.com/void-linux/void-packages/commit/236108d05e1a5c0ebf23215ded57fbef43ff642b

**Comment by pullmoll** [comment]
For me it built on x86_64 however I have no nvidia390 card to test it.
Does it work for you @p2501mk ?

**Comment by p2501mk** [comment]
@pullmoll works like a charm for me  :100: :)
