### ISSUE TITLE
Package Request: Xanmod Kernel

### ISSUE THREAD

**Issue by AngryPhantom** [void-linux/void-packages#24713]
It would be really great to have an option such as a highly responsive kernel with [Xanmod](https://xanmod.org/) patches for a desktop PC.
Would be nice to have a stable 5.4 branch since this kernel has the needed balance of freshness, stability and module/dkms support including such old drivers as nvidia340 (yes, I'm one of the "lucky" users of legacy cards).

The patch is [here](https://github.com/xanmod/linux/releases/download/5.4.62-xanmod1/patch-5.4.62-xanmod1.xz) and should be applied to the bare [5.4](https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.4.tar.xz) kernel with no incremental updates (it already includes them).

The real problem for me (and probably for others too) is that I'm running out of space and/or RAM trying to compile ANY Void kernel. As well as getting errors like [this one](https://hastebin.com/raw/veyifozuli) towards the end of compilation. Probably I'm doing something wrong in the default 5.4 template, I'm not sure. But I've cracked my head trying to compile it to no avail for a couple of days already. And I want to stay with Void Linux without installing Debian or other distro for responsive desktop tasks with this kernel (I used to have it on my Debian desktop in the past and it was fast as a rocket!).

So this is my little cry for help. If it is at all possible. Thank you in advance.

**P.S.** I understand that you will most likely reject 3rd party kernel stuff in the main repo. I will appreciate any help from you, guys, like editing the Void 5.4 kernel template for me and test if it compiles OK.

**Comment by hippi777** [comment]
hi there! :) 

im not sure, but i think the void folks wont include it into the main repo, maybe some1 will make it available in an another repo, but in the worst case u can write a template for downloading the deb/whatever package and mess with that :D i think it should be straightforward... other than that, check out bedrock linux, its a tool to mix distros (for those who know what they are actually doing :D )

btw as void is suitable to be run on a half potato, maybe there are chances for anything like what u wish for... i actually wish for an outcast repo for all those unwanted stuffs, like the git head of grub :D

also, i believe kernel related standpoint is written in the docs, and if i remember correctly then ive seen a xanmod request some months ago, or anything similar...

good luck, have fun, theres no impossible :D

**Comment by AngryPhantom** [comment]
@hippi777 Yes, I'm aware of all that. This is my cry for help as well as some enthusiasts who would create kernel packages. It would be just great. I'm out of resources trying to compile it myself. Kernel thing is a bit heavy for me. I used to do it in the past with Debian with no issues actually. I dunno, probably someone could just **edit the template for me at least** and test if it compiles OK. It would be also nice. I'll do my best and find another and bigger HDD and RAM to make it myself.

**Comment by hippi777** [comment]
i mean u can unpack the deb file (it is a tar archive in reality) and just copy paste what u want :D bedrock stuff doesnt need compilation either, and i think that could be ur best friend to solve this... otherwise i think that editing the existing template should be straightforward (to see what goes where, i think there are more stuffs alongside the kernel) for further guidance, i think reddit would be the place for getting help in things that wont go into the official void packages... and if u really want to compile it urself, then maybe its just a matter of having enough swap space and patience, but i have never played with kernel stuffs so far now, and right now im not really much able to experiment, so my help reaches to something like this far, but i think and hope it can be enough

**Comment by AngryPhantom** [comment]
Sorry, guys. I won't take your time on this issue. At least it has nothing to do with the Package request but more a help and I guess I really don't have enough resources to compile a modern kernel. I'm closing this.

**Comment by bugcrazy** [comment]
> Sorry, guys. I won't take your time on this issue. At least it has nothing to do with the _Package request_ itself but more a cry for help and I guess I really don't have enough resources to compile a modern kernel. I'm closing this. I managed to do a dirty trick by unpacking the Debian Xanmod package and simply copying the files to their respective directories, updated the initramfs, grub and voila! It works.

Here's the link to my repository with Kernel Xanmod templates, with GCC and Clang versions, RT!
https://notabug.org/Marcoapc/voidxanmodK
