### ISSUE TITLE
Package request: dockbarx , xfce4-dockbarx-plugin and xfce4-mixer 

### ISSUE THREAD

**Issue by siduck765** [void-linux/void-packages#24760]
I finally switched void from artix runit , I get all the packages from the repo so far , but there's no dockbar pkg , I need python-wnck and python-staging to build it from src , it'd be great if void provided dockbarx package :< , it adds dock like features to the xfce panel . I dont use pulseaudio , I use alsa but there's no good gui package on the void repo for it , I always used xfce4-mixer on artix which was available via aur and its a good alsa frontend , but its not in the void repos :c , my num / arrow keys dont function well so i cant use alsamixer too , with xfce4-mixer i can change the volume of earphones/speakers on both the sides . Here's a screenshot of xfce-mixer

<img src = "https://raw.githubusercontent.com/siduck765/fullbackup/master/photo_2020-09-08_17-19-57.jpg" >

**Comment by userabc123xyz** [comment]
I second xfce4-mixer

**Comment by siduck765** [comment]
> I second xfce4-mixer

its not in the repos :/

**Comment by flexibeast** [comment]
For those considering working on `xfce4-mixer`, note @furryfixer's [comment on /r/voidlinux](https://old.reddit.com/r/voidlinux/comments/imw0zf/package_request/g443iwy/):

> xfce-mixer was dropped by Xfce in favor of pavucontrol, because they assumed everyone would be using pulseaudio (unfortunately). Since xfce4-mixer has outdated dependencies, it is problematic to get working with newer libraries and the latest gtk3 Xfce.

**Comment by siduck765** [comment]
> For those considering working on `xfce4-mixer`, note @furryfixer's [comment on /r/voidlinux](https://old.reddit.com/r/voidlinux/comments/imw0zf/package_request/g443iwy/):
> 
> > xfce-mixer was dropped by Xfce in favor of pavucontrol, because they assumed everyone would be using pulseaudio (unfortunately). Since xfce4-mixer has outdated dependencies, it is problematic to get working with newer libraries and the latest gtk3 Xfce.

i do know that but it just worked fine when i used artix , there's no alsa gui app on the void repo too :c

**Comment by flexibeast** [comment]
Sure. That's why i wrote "For those considering working on `xfce4-mixer`" - my comment was not addressing you (i assume you're /u/siduck0007, and so you'd already seen /u/furryfixer's comment), but those considering doing the packaging. :-)

If there's a specific ALSA control app you'd like to see added, it would be best to open a separate PR for that, so that it's visible to those who might be willing and able to do the work to add it.

**Comment by siduck765** [comment]
> Sure. That's why i wrote "For those considering working on `xfce4-mixer`" - my comment was not addressing you (i assume you're /u/siduck0007, and so you'd already seen /u/furryfixer's comment), but those considering doing the packaging. :-)
> 
> If there's a specific ALSA control app you'd like to see added, it would be best to open a separate PR for that, so that it's visible to those who might be willing and able to do the work to add it.

gnome-alsamixer should be packaged i think , aumix too

**Comment by furryfixer** [comment]
I have limited experience with it, but "**volumeicon**" is in the repositories, integrates with alsamixer, and may be sufficient for some.

**Comment by mobinmob** [comment]
@siduck765 : Please check qastools. It is already in the repo and qasmixer has a full muxer ui and a systray applet.
I also sent a PR for xfce4-alsa-plugin, for those that want a minimal xfce panel applet: https://github.com/void-linux/void-packages/pull/24793

**Comment by mobinmob** [comment]
> > Sure. That's why i wrote "For those considering working on `xfce4-mixer`" - my comment was not addressing you (i assume you're /u/siduck0007, and so you'd already seen /u/furryfixer's comment), but those considering doing the packaging. :-)
> > If there's a specific ALSA control app you'd like to see added, it would be best to open a separate PR for that, so that it's visible to those who might be willing and able to do the work to add it.
> 
> gnome-alsamixer should be packaged i think , aumix too
They are not maintained...

**Comment by siduck765** [comment]
> @siduck765 : Please check **qastools**. It is already in the repo and **qasmixer** has a full mixer ui and a systray applet.
> I also sent a PR for xfce4-alsa-plugin, for those that want a minimal xfce panel applet: #24793

thanks , building xfce4-alsa-plugin from source got me issues . I'll wait till that package releases

**Comment by userabc123xyz** [comment]
huh, I didn't know they actually stopped maintaining xfce4-mixer in favor of supporting pulseaudio. Yet another reason to drop Xfce. I think about switching to LXDE instead.

**Comment by siduck765** [comment]
> huh, I didn't know they actually stopped maintaining xfce4-mixer in favor of supporting pulseaudio. Yet another reason to drop Xfce. I think about switching to LXDE instead.

xfce4-mixer  works tho , I didnt had any issues with it .

**Comment by userabc123xyz** [comment]
> xfce4-mixer works tho , I didnt had any issues with it .

How exactly did you install it?

**Comment by siduck765** [comment]
> > xfce4-mixer works tho , I didnt had any issues with it .
> 
> How exactly did you install it?

no i meant xfce-mixer worked well in artix , its a dead package but very functional for alsa gui

**Comment by userabc123xyz** [comment]
> no i meant xfce-mixer worked well in artix , its a dead package but very functional for alsa gui
well, 'dead' is a funny word when applied to software

**Comment by siduck765** [comment]
> > no i meant xfce-mixer worked well in artix , its a dead package but very functional for alsa gui
> 
> well, 'dead' is a funny word when applied to software

i mean , the package is no longer maintained , and its just works with aur :<

**Comment by userabc123xyz** [comment]
free software is never dead C-:

**Comment by ericonr** [comment]
xfce4-alsa-plugin has been merged.
