### ISSUE TITLE
anacron fails to start due to missing symbol

### ISSUE THREAD

**Issue by loreb** [void-linux/void-packages#24792]
### System

* xuname:  
  Void5.8.7_1 x86_64-musl
* package:  
  cronie-1.5.5_3 with musl-obstack-1.2_1

### Expected behavior
anacron runs

### Actual behavior

> Error relocating anacron:  obstack_free: symbol not found

### Steps to reproduce the behavior
Update musl-obstack to latest version - https://github.com/void-linux/musl-obstack/commit/91923c732016e2d5021c3992eb1eca7779cf8922 "gets rid of" obstack_free;
If I'm reading the patch correctly obstack_free used to be a function and it's now a macro;
anacron is linked dynamically to the old version, so it tries to call a function that no longer exists.

It seems that upstream now includes obstack (https://github.com/cronie-crond/cronie/commit/fd934a8292805fa29a27c0d9c3ee79d1fc1ea9fc);
just recompiling the master branch from there worked and ran on my machine,
so I expect that simply recompiling should work,
and if not updating worked for me(tm).

Please let me know if there's any problem.

**Comment by ericonr** [comment]
I can make a PR for this in a bit.

**Comment by ericonr** [comment]
Or... you could try to make a PR too :D 

What happens if you revbump the package?

**Comment by ericonr** [comment]
@loreb if you could be so kind as to close this message c:
