### ISSUE TITLE
xbps-src: install a generated xbps package

### ISSUE THREAD

**Issue by LennyPenny** [void-linux/void-packages#24791]
So I'm finishing up my first package template. 
I successfully built it using the `./xbps-src pkg <pkg>` command. 

Is there a way to install the generated `.xbps` file to make sure the package actually installs correctly and runs on my system?

I tried the `./xbps-src install` command but that does not seem to put the built binary into my `/usr/bin` directory. When I use the `-C` option and inspect the local `distdir` directory the binary however is in its `usr/bin` directory.

**Comment by Duncaen** [comment]
`./xbps-src install` runs the install target of the template, i.e. `make install` which puts files into `masterdir/destdir/$pkgname-$version` which is then used to create the binary package.

You can resulting packages using `xbps-install --repository=hostdir/binpkgs` or with `xi` from the `xtools` package, which is a wrapper around `xbps-install` and adds the relative binpkgs repositories on its own.

**Comment by melroy89** [comment]
In my case the command was:

```bash
sudo xbps-install -f --repository=./hostdir/binpkgs/<branch_name> <package_name>
```

Replace both `<branch_name>` as well as the `<package_name>` with your correct names. The `-f` might be needed if its already installed or use `-u` flag to do an update.

I made the command as verbose as possible, so its no longer confusing how to use it.
