### ISSUE TITLE
Package request: cuberite

### ISSUE THREAD

**Issue by handow23** [void-linux/void-packages#24801]
Cuberite is a Minecraft-compatible multiplayer game server that is written in C++ and designed to be efficient with memory and CPU, as well as having a flexible Lua Plugin API. Cuberite is compatible with the Java Edition Minecraft client.

Project page: https://github.com/cuberite/cuberite

**Comment by tibequadorian** [comment]
I think, it doesn't really make sense to package this as it is intended to be executed locally as standalone binary in the server folder like minecraft-server.jar or spigot.jar

**Comment by handow23** [comment]
Yeah, but it doesn't run on a Musl machine. A official Void package could solve the issue.

**Comment by the-maldridge** [comment]
Cuberite doesn't make source releases, so it is not a candidate for Void inclusion.  First convince the cuberite project to make source releases, and then this can be raised again.

**Comment by the-maldridge** [comment]
Upstream doesn't seem to understand how rolling release works.  Closing this until they figure out release management.
