### ISSUE TITLE
Package request: Spek

### ISSUE THREAD

**Issue by absolutelynothinghere** [void-linux/void-packages#24802]
I would like to request the **[Spek](http://spek.cc/)** package, an acoustic spectrum analyzer. Last release is [0.8.2](https://github.com/alexkay/spek/releases/download/v0.8.2/spek-0.8.2.tar.xz) dated February 2013, there was also a 0.8.3 release shortly after but it was solely for Mac OSX. The Spek project is abandoned so the package shouldn't need maintenance or updates beyond the initial commit.

To whoever will pick this up; you might need older versions of ffmpeg, libavcodec, and libavformat to compile Spek. I have tried compiling it on my own and failed miserably.

**Comment by hippi777** [comment]
hi there :)

im not a fan of flatpak and whatever like, but it sounds like a job for such stuffs, but not really for void, cuz the old dependencies... otherwise im not a void representative/decision maker, so take this as a suggestion/prediction :D

**Comment by not-chicken** [comment]
Related #22881

**Comment by absolutelynothinghere** [comment]
@hippi777 Honestly I agree, Spek is small enough to be packaged as an appimage/flatpak, and I would package it myself if I knew how... Sadly I still have a long way to go.

@not-chicken I was not aware Spek Alternative had a pull request, thank you for the heads up! If it got included I will be very happy.

**Comment by tibequadorian** [comment]
I think this can be closed because #22881 was merged @ericonr
