### ISSUE TITLE
virtualbox-ose-guest-dkms-6.1.14_2 download problem

### ISSUE THREAD

**Issue by chris-elvidge** [void-linux/void-packages#24901]
Trying to install a new Trident/Void/Lumina image in virtual box. However:
xbps-install virtualbox-ose-guest-dkms
I get

[*] Downloading packages
ERROR: [trans] failed to download 'virtualbox-ose-guest-dkms-6.1.14_2' signature from 'https://alpha.de.repo.voidlinux.org/current': Not Found
Transaction failed! see above for errors.

xbps-install virtualbox-ose-guest works OK.

On an older Void-MATE install (VOGD v 6.1.10) version 6.1.14_2 does not even appear when I do
xbps-install -Su

**Comment by ericonr** [comment]
Nothing we can act on at the moment.
