### ISSUE TITLE
proot segfault on aarch64-musl

### ISSUE THREAD

**Issue by duncancmt** [void-linux/void-packages#24918]
### System

* xuname:  
`Void 5.7.0_1 aarch64-musl Unknown notuptodate rrDFFFFF`
(`notuptodate` because `xorg-server`>1.20.8_4 <1.20.9_3 is broken)
* package:  
`proot-5.1.0_7`

### Expected behavior

I tried to set up a `glibc` chroot because I've been having big problems with programs segfaulting. (`flatpak`, `gdb`, `pavucontrol`)

```bash
sudo env XBPS_ARCH=aarch64 xbps-install --repository=http://alpha.de.repo.voidlinux.org/current/aarch64 -r /glibc -S base-voidstrap
proot -R /glibc/ /bin/sh
```

I expected to get a shell.

### Actual behavior

```
proot info: pid <REDACTED>: terminated with signal 11
```

See [attached log](https://github.com/void-linux/void-packages/files/5221846/proot.log) for `-v 9` output.

### Steps to reproduce the behavior

See above

### Reference

proot-me/proot#106 does not appear to be applicable. SECCOMP is already disabled
```
$ proot --version
 _____ _____              ___
|  __ \  __ \_____  _____|   |_
|   __/     /  _  \/  _  \    _|
|__|  |__|__\_____/\_____/\____| 5.1.0

built-in accelerators: process_vm = yes, seccomp_filter = no

Visit http://proot.me for help, bug reports, suggestions, patchs, ...
Copyright (C) 2014 STMicroelectronics, licensed under GPL v2 or later.
```
Running with `PROOT_NO_SECCOMP=1` gives identical results.

**Comment by fosslinux** [comment]
Gosh, aarch64-musl seems to be super broken. Care to open another issue about the xorg thing? Can you give a strace log?

**Comment by duncancmt** [comment]
fdbf1993cb8a10136d7555d83ed15abdbe1f5c84 fixed the xorg-server issue. I've updated the top post to reflect that.

```
$ strace -o proot.strace.log proot -R /glibc/ /bin/sh
proot info: pid 5667: terminated with signal 11
```
[proot.strace.log](https://github.com/void-linux/void-packages/files/5249985/proot.strace.log)



```
$ strace --follow-forks -o proot.strace_follow_forks.log proot -R /glibc/ /bin/sh
proot error: ptrace(TRACEME): Operation not permitted
proot error: execve("/usr/bin/sh"): Operation not permitted
proot info: It seems your kernel contains this bug: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1202161
To workaround it, set the env. variable PROOT_NO_SECCOMP to 1.
fatal error: see `proot --help`.
proot error: can't chmod '/tmp/proot-6019-aLbooi': No such file or directory
```
[proot.strace_follow_forks.log](https://github.com/void-linux/void-packages/files/5249988/proot.strace_follow_forks.log)



```
$ strace --follow-forks -o proot.strace_follow_forks_no_seccomp.log env PROOT_NO_SECCOMP=1 proot -R /glibc/ /bin/sh
proot error: ptrace(TRACEME): Operation not permitted
proot error: execve("/usr/bin/sh"): Operation not permitted
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot --help`.
proot error: can't chmod '/tmp/proot-6504-hbEGIB': No such file or directory
```
[proot.strace_follow_forks_no_seccomp.log](https://github.com/void-linux/void-packages/files/5249991/proot.strace_follow_forks_no_seccomp.log)

**Comment by Duncaen** [comment]
If you just want a chroot, I would suggest you to use namespaces (bubblewrap, nsenter, containers etc..., xbps-uunshare) if you want it unprivileged or a normal chroot.
proot is pretty broken by design, not only with aarch64.

**Comment by duncancmt-alt** [comment]
I ended up "solving" this problem by using a variation on the program [detailed on this page](https://blog.w1r3.net/2017/09/23/live-switching-void-linux-from-glibc-to-musl.html) to overlay the glibc `/usr` on top of the rest of the filesystem so that glibc programs work appropriately. I'm a little wary of suid binaries, but this one seems simple enough? I'm not sure if that actually should close this issue, though, because the underlying problem still exists.

**Comment by duncancmt** [comment]
duplicates #25535
