### ISSUE TITLE
qt5-core breaks telegram-desktop

### ISSUE THREAD

**Issue by sug0** [void-linux/void-packages#24938]
### System

* xuname:  
Void 5.8.9_1 x86_64 GenuineIntel uptodate rrrrmmnFFFF
* package:  
telegram-desktop-2.3.2_1
qt5-core-5.15.1_1

### Steps to reproduce the behavior

xbps-install -Su

**Comment by Johnnynator** [comment]
Should be resolved soon, the rebuild for telegram-desktop is already queued. Just takes a bit until the builds are finished.

**Comment by sug0** [comment]
Can confirm it's been resolved
