### ISSUE TITLE
wine, libwine

### ISSUE THREAD

**Issue by teldra** [void-linux/void-packages#24949]
I am not sure, if this is intended: Before wine-5.17_1, libwine was a dependency of wine. Now libwine is an orphan.

### System

* xuname:  
 Void 5.8.9_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFFFFFFFFFF
* package:  
  *affected package(s) including the version*: wine-5.17_1 libwine-5.17_1

### Expected behavior
xbps-remove -o do not want to deinstall libwine
### Actual behavior
xbps-remove -o tries to deinstall libwine
### Steps to reproduce the behavior
update system and run xbps-remove -o

**Comment by teldra** [comment]
ping @Hoshpak

**Comment by sgn** [comment]
They don't link libwine into wine anymore, they `dlopen(2)` instead.
I'll push a fix out.

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/commit/ac3db77f43e34f9fdd7acf55d310b92a3635aae6
