### ISSUE TITLE
linux*: hwmon is not enabled consistently across all architectures

### ISSUE THREAD

**Issue by circhioz** [void-linux/void-packages#24940]
I noticed that defconfigs for `i386` and `x86_64`, differently from the other architectures, come without these options:
```
CONFIG_NVME_HWMON=y
CONFIG_POWER_SUPPLY_HWMON=y
CONFIG_THERMAL_HWMON=y
```
They enable libsensors (hence sensors) to read NVMe temps, ACPI thermal zones and power supply sensors, as it expects them to be exported to the common hwmon sysfs interface.

I was wondering if it was intentional or not (`CONFIG_NVME_HWMON` was already requested in #22024 by another user).

**Comment by leahneukirchen** [comment]
Thanks, will queue for next 5.8.
