### ISSUE TITLE
FYI: gcc10 / gnome-3.38.0 testing

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#24997]
I built new live ISOs with gcc10 compiled packages including the brand new gnome-3.38.0
For the first time the Gnome ISOs actually let you log in to the DE.

If you find spare time to test and see if there are problems which may arise from gcc10 being used to build everything, please d/l and run [one or more of the Live ISOs](https://repo.voidlinux.de/live/) from my site, be it in a VM or hardware.

As a side note I also installed Void on my PBP now using the `void-pinebookpro-20200920.img.xz` available at this URL.
It was a bit tedious to get all things I needed installed but now the `eMMC` has Void w/ xfce4 running instead of Manjaro. I need to try out the patched u-boot and SPI images from the net to try and boot from the m2.SSD which is said to be possible now.

**Comment by ericonr** [comment]
I'm testing out a sample of what I _can_ test! I will leave some notes here, but
I think a few of them are probably relevant for void-mklive instead.

## GNOME on i686-musl

- Booted without issue, lacked fonts for some of the available languages (also lacked language options, overall).
- The final setup screen had a "Start Using void" button, it should probably be "Void".
- `gnome-music` can't launch, missing `grl-tracker3` module: installing tracker3-devel, the only package missing, didn't fix it.
- `gnome-control-center` -> Region & Language -> Formats: segfaults.

**Comment by ericonr** [comment]
i## KDE on i686-musl

- Also booted without issue.
- A bit too barebones, I think. Basically doesn't have any applications beyond Firefox.
- Emoji picker lacking some fonts to show all the emoji available.
- Has more languages available than GNOME, which is nice, but still has font issues for a few of them.
- System Monitor is having issues showing the username of user `(anon)`, so it's showing an arbitrary negative number. Probably a Plasma bug.

## Cinnamon on x86_64-musl

- Boots, but only that. No background, launcher (the bottom bar) crashes when clicked (`FileNotFound` error). Fonts in terminal are screwed.
- After a bit terminal just kind of died and no input was working in X anymore. TTY was fine.
- Unless this is fixed, I don't believe this ISO should be shipped.

## MATE on x86_64

- Boots fine and works well.
- Terminal has a bit too low contrast between font and background, but I'm not sure who's to blame here.
- Overall works fine.
- LXDM theme has bad color defaults and few language options as well (only `en_US`, in this case).

**Comment by pullmoll** [comment]
Well, things which are missing you can just install once you have a network connection.
Sure, the flavors need some work as to what they include.

This is an  issue of what is packaged in `void-mklive` and `build-x86-images.sh.in` or `build-live-images.sh.in` from @q66 's fork of `void-mklive` and my local changes / extensions to that, not an issue of `gcc10` being used to build it all.

For `Cinnamon` on `x86_64-musl` this is probably `cjs` (again) which AFAIR always had issues or just plain crashed.

More interesting is whether or if specific packages that are known to work now when built with gcc9.3 fail when built with gcc10.2. So far in my own tests I had none of that type while I hadn't tested too much.

**Comment by pullmoll** [comment]
New ISOs with (some) more packages preinstalled. For me Cinnamon on x86_64-musl works fine in qemu.

**Comment by ericonr** [comment]
I will try x86_64-musl, I only used the i686-musl one.
