### ISSUE TITLE
Package request: onlyoffice-desktopeditors

### ISSUE THREAD

**Issue by figsoda** [void-linux/void-packages#25017]
Name: onlyoffice-dekstopeditors

License: AGPL-3.0 (GNU Affero General Public License v3.0)

https://github.com/ONLYOFFICE/DesktopEditors

**Comment by gorkawien** [comment]
Just in case i want to share my experience:

I've managed to install onlyoffice-desktopeditors using xdeb:
https://github.com/toluschr/xdeb

**Comment by reback00** [comment]
@gorkawien Thanks for sharing. If I remember correctly, I've done something similar with `ar x`. It works great. But that's from .deb binary builds. I tried once to build from source. Their build instructions are kind of unclear (at least to me).  Clearly out of my league unfortunately.

**Comment by gorkawien** [comment]
@reback00  Thanks also for your hard work!! I use some of your templates for my ISOs!!
There one piece of software that maybe you could assist me:
https://github.com/void-linux/void-packages/issues/25062
I Tried to create a template, but I don't have the necessary knowledge.

**Comment by reback00** [comment]
@gorkawien  Wow. Never thought I had fans! :) Good to know.
I never used sunflower before. But I'll take a look. If I'm lucky I may get all the PRs this year too from void linux for #hacktoberfest like [previous year](https://www.reddit.com/r/voidlinux/comments/dkwpvr/yaaayyy_i_completed_this_years_hacktoberfest_with/). That would be something awesome.

**Comment by betsonet** [comment]
Onlyoffice exists as an [Appimage](https://appimage.github.io/ONLYOFFICE/) and I use it without problems.

**Comment by figsoda** [comment]
Thanks guys, but I don't use void any more so I am closing this.
