### ISSUE TITLE
A question about libjack and LV2 devel files

### ISSUE THREAD

**Issue by userabc123xyz** [void-linux/void-packages#25015]
I'm trying to compile synthv1 on Void, and ./configure gives me: 
configure: WARNING: *** JACK library not found.
configure: WARNING: *** LV2 header files not found.

1) I already have libjack installed on my system - is this the correct package, or some devel package is also required?
2) I have no idea what package can provide LV2 headers

can someone help?

**Comment by daniel-eys** [comment]
Void has a convenient tool called `xlocate` from the `xtools` package, which can help you locate files.
Like so:
```
xlocate /usr/include/jack
xlocate /usr/include/lv2
```
So the packages you are missing are `jack-devel` and `lv2`.
