### ISSUE TITLE
gimp-2.10.20: Change `python_version` to `3`?

### ISSUE THREAD

**Issue by kartikynwa** [void-linux/void-packages#25025]
Python 2 is approaching EOL and I am pretty sure GIMP should work fine with Python 3. Right now, I don't have `python2` installed and I get warning messages like so:

```
GIMP-Warning: Bad interpreter referenced in interpreter file /usr/lib/gimp/2.0/interpreters/pygimp.interp: /usr/bin/python2
```

**Comment by ahesford** [comment]
At least two plugins I've checked in `gimp-python` (the only two I've checked, actually) are py2-only. I don't know enough about GIMP to know how `pygimp.interp` plays with these plugins, but I'm loath to change `pygimp.interp` without ensuring that the `gimp-python` contents work with the same interpreter.

**Comment by eli-schwartz** [comment]
Python plugin support for gimp requires python2 pygtk and in no way can ever be built against python3. Gimp plugins that don't use python, but rather C or scheme or whatever, don't depend on either python2 or python3...

I don't comprehend the rush to use some unpredictable "let's try building gimp with python3 and see if it falls over horribly". Upstream does NOT support doing this on the 2.x branch, but gimp 3.0 will be fully ported to python3 and pygobject, so why not just wait until then?
