### ISSUE TITLE
[Package Request]: Microsoft Teams?

### ISSUE THREAD

**Issue by marek-lach** [void-linux/void-packages#25032]
I really do wish this wasn't necessary, but due to COVID19 many schools and workplaces require it.

Packages are officially only available for DEB, or RPM (https://docs.microsoft.com/en-us/microsoftteams/get-clients#linux), I am frankly not even sure if, or how it could be packaged for Void, or for that matter, how the AUR package works: https://aur.archlinux.org/packages/teams.

Someone could perhaps figure this one out.

_License:_ custom

**Comment by ericonr** [comment]
https://github.com/void-linux/void-packages/commit/2226a4750b768adb2ac06d5f1698bdaa9671c262

**Comment by ericonr** [comment]
It's been added, but it can't be distributed, so you have to build locally yourself.
