### ISSUE TITLE
Package request: GreenWithEnvy

### ISSUE THREAD

**Issue by illusioon** [void-linux/void-packages#25043]
GWE is a GTK system utility designed to provide information, control the fans and overclock your NVIDIA video card
and graphics processor.

Project page: https://gitlab.com/leinardi/gwe
Release: https://gitlab.com/leinardi/gwe/-/releases
License: GNU General Public License v3.0

**Comment by Frick-David** [comment]
I think I built this from source and it works fine. Would be a super useful package.

**Comment by illusioon** [comment]
Solved it was add: https://github.com/void-linux/void-packages/commit/500dc11caf8a847135bc75fc810fe4218422233f
