### ISSUE TITLE
gstreamer using sndiosink even when sndio is not installed

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#25044]
https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/823

### System

* xuname:  `Void 5.7.0_1 aarch64 Unknown uptodate rFFFF`
* package:  
    * gstreamer1-1.16.2_1
    * gst-plugins-bad1-1.16.2_10
    * gst-plugins-good1-1.16.2_2
    * gst-plugins-ugly1-1.16.2_2
    * gst-plugins-base1-1.16.2_1

### Expected behavior

gst-play-1.0 works and sends audio to the appropriate sink

### Actual behavior

gst-play-1.0 sends audio to sndiosink, which is not prepared to handle any formats

### Steps to reproduce the behavior

Install mpv, quodlibet, and gst-libav on a vanilla aarch64 system. Try using gst-play-1.0.

**Comment by CameronNemo** [comment]
@Duncaen should this sink be split into a separate package?

**Comment by Duncaen** [comment]
I guess that would make sense, not sure why no one else run into this issue, does it not use some kind of fallback and priority mechanism?

**Comment by CameronNemo** [comment]
No idea why I am only hitting it on my aarch64 installation and not on my x86_64 installation. The plugin sets itself to the highest priority, but I would think it should be ignored if sndio is not installed. That is not happening in my case, so currently I just have a noextract rule.

**Comment by Duncaen** [comment]
Looking at the patch it says:
```
/* prefer sndiosink over pulsesink (GST_RANK_PRIMARY + 10) */
```
this seems wrong, the patch comes straight from openbsd where this makes more sense.

**Comment by ericonr** [comment]
Fixed by removing sndio build option from defaults.
