### ISSUE TITLE
Can't update new Void installation, or live image.

### ISSUE THREAD

**Issue by joeblo1** [void-linux/void-packages#2511]
### Expected behavior
to be able to update packages after installation

### Actual behavior
can't update packages, couldn't sync repos on live image

### Steps to reproduce the behavior
try a live image

Every time I try to update a newly installed void-linux - on live image or after installation on HDD, it does this to me:

[*] Updating `https://repo.voidlinux.eu/current/musl/x86_64-musl-repodata' ...
Certificate verification failed for /CN=vm1.a-lej-de.m.voidlinux.org
SSL_connect returned 1
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/musl/x86_64-musl-repodata': Operation not permitted

I have no idea how I am supposed to solve this. I can't downgrade any packages because there's nothing to downgrade to.... How do I get this thing working? I scp'ed the ca-certificates .xbps file, but I have no way to install it without xdowngrade.

**Comment by joeblo1** [comment]
Is there a way I can install a .xbps package without xdowngrade? Is there a way it can be done with xbps-install? I can't install anything until I solve this error.

**Comment by jnbr** [comment]
Is your system time set correct? Else certificate verification can fail.

**Comment by Johnnynator** [comment]
You can get `xdowngrade` from here https://github.com/chneukirchen/xtools

**Comment by joeblo1** [comment]
How Johnnynator? I can't even git clone.

**Comment by joeblo1** [comment]
The time was off by 15 minutes so it stopped me from updating.... lol. never knew that could happen. 
Sorry. I thought this was something that could be affecting all new installations or something, figured it could be urgent. I've never seen a package manager stop working because of the time... thank you very much jnbr.

**Comment by Johnnynator** [comment]
`xbps-uhelper fetch https://raw.githubusercontent.com/chneukirchen/xtools/master/xdowngrade` ( or curl/wget if this is installed ) and you can try to fatch https://repo.voidlinux.eu/current/ca-certificates-20180409_2.noarch.xbps manually.

**Comment by Johnnynator** [comment]
Afaik `/usr/share/xbps.d/`. `xbps-query -f xbps | grep conf` should also give you the list of all config files.

**Comment by jnbr** [comment]
On 09/07/2018 05:21 PM, joeblo1 wrote:
> Where's the repo config located if you don't mind my asking? Will make things easier if anyone finds this while googling.
> 

`etc/xbps.d`, defaults are in `/usr/share/xbps.d`.
See also `man xbps.d`.
