### ISSUE TITLE
thin_dump segfaults on aarch64-musl

### ISSUE THREAD

**Issue by duncancmt-alt** [void-linux/void-packages#25125]
Yet another report in my "PACKAGE segfaults on aarch64-musl" series. See also #24783 #24785 and #24918 (more to come, I'm sure). I regret that I am posting this from a different account. I am currently locked out of my usual machine due to a bug in LVM2 (which I hope is unrelated to the issue at hand). See [this thread on the lvm-linux mailing list](https://www.redhat.com/archives/linux-lvm/2020-September/msg00088.html) and [this bug open upstream](https://bugzilla.redhat.com/show_bug.cgi?id=1882483).

But hopefully that's all unrelated.

### System

* xuname:  
  `Void 5.7.0_1 aarch64-musl Unknown uptodate rFF`
* package:  
  `thin-provisioning-tools-0.8.5_1`

### Expected behavior
```
# thin_dump /dev/null
<no segfault, maybe an error message or something?>
```

### Actual behavior
```
# thin_dump /dev/null
Segmentation fault
```

### Steps to reproduce the behavior
See above

### Other remarks

I've [uploaded a tarball](https://drive.google.com/file/d/1RnUFlSMmFph5JXxenDJ1PhuCLV9xelAc/view?usp=sharing) containing the relevant binary, shared libraries, and core dump. I regret that I cannot provide a backtrace, but `gdb` is broken on aarch64-musl (see #24785 ).

Something appears to be seriously wrong with aarch64-musl. If anyone could provide some insight into what's broken, I would be greatly appreciative. Otherwise, I think a reasonable person may conclude that despite documentation otherwise, aarch64-musl is *not* actually supported on void (or at least, it's barely usable what with how many broken packages there are)

**Comment by ericonr** [comment]
> If anyone could provide some insight into what's broken, I would be greatly appreciative.

I believe the current theory is that there are issues with any unwinding actions. That's as far as I understand the issue, sorry.

**Comment by duncancmt** [comment]
> I believe the current theory is that there are issues with any unwinding actions.

That's very interesting. Is there anything more that I can do to help debug this problem? What do you mean by "unwinding actions"? Exception handlers in C++? If I could run `gdb`, I would debug it further myself. If there's further discussion about this bug in another thread/forum, I would be happy to assist.

It may also be of interest, I have posted another report in a similar vein, but one that has a very simple command-line difference between the working and the non-working case #25531

**Comment by ericonr** [comment]
> Exception handlers in C++?

That and probably `libunwind` as well. We talked about it on IRC a bit (`#xbps` on freenode).

Regarding this specific bug, is it straceable?

**Comment by sgn** [comment]
@duncancmt ~This simple C++ program crashed on `aarch64-musl`, MCVE identified. `gdb` itself uses exception, so gdb couldn't help. Please don't report more issues with this kind of problem until we fixed it. 
Instead, you can make a big issue about aarch64-musl and merge everything there. Thanks

```cpp
#include <string>
#include <stdexcept>

int main(int argc, char **argv) {
	try {
		throw std::runtime_error("hello");
	} catch (const std::exception& e) {
	}
	return 0;
}
```

**Comment by duncancmt** [comment]
Excellent!

> Please don't report more issues with this kind of problem until we fixed it.
> Instead, you can make a big issue about aarch64-musl and merge everything there.

Yep! I'll open a new issue with the subject "Exception handling and unwinds segfault on aarch64-musl" and close all these issues as duplicates.

**Comment by duncancmt-alt** [comment]
duplicates #25535
