### ISSUE TITLE
RSA signature invalid for linux 5.8.12_1

### ISSUE THREAD

**Issue by iceaway** [void-linux/void-packages#25148]
I just installed Void Linux in a VirtualBox VM, and when I try to update my system I get a lot of errors about RSA signatures not being valid. Running xbps-install -Svu several times in a row installed more and more packages, but now I am stuck at installing linux5.8-5.8.12_1. It says:
ERROR: linux-5.8-5.8.12_1: the RSA signature is not valid!
ERROR: linux-5.8-5.8.12_1: removed the pkg archive and its signature.

### System
VirtualBox 6.1.14

* xuname:  
Void 5.3.9_1 x86_64 GenuineIntel/KVM notuptodate rFFF
* package:  
Linux 5.8-5.8.12_1

### Expected behavior
Package should be installed without error.

### Actual behavior
Packege not installed due to invalid RSA signature

### Steps to reproduce the behavior
run xbps-install -Sv linux

**Comment by iceaway** [comment]
I just made a complete reinstall of Void just to see if anything would change, but unfortunately not. However, when doing the first xbps-install -Su after the install, I get the same RSA signature error for multiple other packages. I was able to resolve that by running xbps-install <packagename>. This does not work for the Linux kernel however.

**Comment by ericonr** [comment]
Have you verified the image you're using? What does `xbps-pkgdb` say when run?

**Comment by iceaway** [comment]
> 
> 
> Have you verified the image you're using? What does `xbps-pkgdb -a` say when run?

Yes, I checked the sha256sum and the signature, both came out OK. 
```
$ signify-openbsd -C -p void-release-20191109.pub -x sha256.sig void-live-x86_64-20191109.iso
Signature Verified
void-live-x86_64-20191109.iso: OK

$ sha256sum -c --ignore-missing sha256.txt
void-live-x86_64-20191109.iso: OK
```

But the output of that command does not look very good:
```
ERROR: base-files: unexistent file /etc/issue
ERROR: base-files: conf files check FAILED
ERROR: e2fsprogs: hash mismatch for /usr/share/locale/tr/LC_MESSAGES/e2fsprogs.mo.
ERROR: e2fsprogs: files check FAILED
```

**Comment by iceaway** [comment]
I think I may have been a victim of this issue: https://forums.virtualbox.org/viewtopic.php?f=6&t=100000

I turned off Hyper-V and now I'm able to install the package upgrades.
