### ISSUE TITLE
openjdk11: libjvm.so inside java.base.jmod isn't stripped

### ISSUE THREAD

**Issue by Logarithmus** [void-linux/void-packages#25183]
`/lib/jvm/openjdk11/lib/server/libjvm.so` is stripped and is only 18 MiB in size, but `libjvm.so` which is bundled inside `java.base.jmod` is whopping 573 MiB (JMOD is a bit smaller thanks to compression being used)!
As you can see, in Arch Linux [jdk11-openjdk](https://www.archlinux.org/packages/extra/x86_64/jdk11-openjdk/) is only 76 MB, but the same package in Void is 352 MiB. Currently I'm investigating why the library is stripped in Arch but not in Void by comparing PKGBUILD and template. I'll appreciate any help.

### System

* xuname:  
  `Void 5.8.11_1 x86_64-musl GenuineIntel notuptodate rrnFFFFF`
* package:  
  `openjdk11-11.0.9+4_1`

### Expected behavior
libjvm.so and other libraries should be stripped before including into JMOD
### Actual behavior
libjvm.so and other libraries inside JMOD aren't stripped
### Steps to reproduce the behavior
`sudo xbps-install openjdk11`
`jmod extract /lib/jvm/openjdk11/jmods/java.base.jmod`

**Comment by Logarithmus** [comment]
Finally, after looking through the package build log, I found the reason of this issue. It's this [commit](https://github.com/void-linux/void-packages/commit/a70c1810192f9e71d5a3fb8044565db8cac1e2da).
I don't know what's the purpose of this wrapper. Maybe it's intent is to save time and avoid stripping the same file 2 times?

**Comment by ericonr** [comment]
It's to allow us to collect debug info when stripping the file. When the build system strips it, we lose that opportunity.

**Comment by Logarithmus** [comment]
@ericonr I guess that debug info is used to create *-dbg packages? OK, so the solution would be to unpack *.jmod files after build, then strip the libraries, and finally create jmods again.

**Comment by leahneukirchen** [comment]
I guess it makes sense to properly strip this here, the data should end up in `/usr/lib/debug/usr/lib/jvm/openjdk11/lib/server/libjvm.so` already?

**Comment by Logarithmus** [comment]
Ok, so how to override this strip-wrapper?

**Comment by SevereOverfl0w** [comment]
At the risk of hijacking, something I've just discovered may be relevant: the dbg symbols don't work for openjdk.

```
/tmp/profilerissue 5m 29s
❯ gdb /usr/lib/jvm/openjdk11/lib/server/libjvm.so                           
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/jvm/openjdk11/lib/server/libjvm.so...

warning: the debug information found in "/usr/lib/jvm/openjdk11/lib/server/libjvm.debuginfo" does not match "/usr/lib/jvm/openjdk11/lib/server/libjvm.so" (CRC mismatch).


warning: the debug information found in "/usr/lib/debug//usr/lib/jvm/openjdk11/lib/server/libjvm.debuginfo" does not match "/usr/lib/jvm/openjdk11/lib/server/libjvm.so" (CRC mismatch).

(No debugging symbols found in /usr/lib/jvm/openjdk11/lib/server/libjvm.so)
```

It's searching  /usr/lib/jvm/openjdk11/lib/server/libjvm.so for debug symbols, instead of /usr/lib/debug.

**Comment by leahneukirchen** [comment]
Tagging @classabbyamp our local JVM expert... ;)

**Comment by classabbyamp** [comment]
Ok, so:

- dbg doesn't work because jdk11 is built with `--with-native-debug-symbols=none`
	- this should work with `internal`, and xbps-src should strip them correctly (tested with jdk17 and gdb)
- I currently don't see any way to strip inside the jmods
- alpine ships jmods as a subpackage, but with `--with-native-debug-symbols=none`
- arch leaves all debug info and jmods in the main jdk package and does not set any debug-related configure options (not sure how they have such a small package size?)

personally I think subpackaging them is the best option for now.

**Comment by Logarithmus** [comment]
@classabbyamp how do Alpine maintainers manage to strip jmods? https://pkgs.alpinelinux.org/package/edge/community/x86_64/openjdk17-jmods
Judging by the package size, I think it's stripped.

**Comment by classabbyamp** [comment]
they build with no debug symbols at all, I believe
