### ISSUE TITLE
maxima: rebuild package with last sbcl

### ISSUE THREAD

**Issue by jbgg** [void-linux/void-packages#25221]
Sbcl has been rebuilt but maxima depends on them. So now the maxima is broken, please rebuild maxima with last version commit of sbcl.

Thanks.

**Comment by jbgg** [comment]
This issue can be avoided if `--enable-sbcl-exec` is added to `./configure`, because it creates a executable.
It should be added?

**Comment by ericonr** [comment]
I guess that would decouple the maxima package from sbcl a bit more? If so, that'd be great.

Sorry for the confusion!

**Comment by ericonr** [comment]
If you make a PR for it, please remember to add that option only for the `sbcl` build option :)
