### ISSUE TITLE
Bug: Korganizer does not start without mysqld which is not installed with it

### ISSUE THREAD

**Issue by Frick-David** [void-linux/void-packages#25252]
I ran 'xbps-install korganizer' and said yes.
It gave me an error on start up about not connecting to the akonadi personal information service. I read around on the internet and quite a few users said to restart mysqld.
However, korganizer did not install it as a dependecy.
To get the program to work, I have to run `xbps-install mysql`, select yes then start mysqld as a service with
`ln -s /etc/sv/mysqld /var/service/`
and then it worked.
I am submitting this as a bug with the package, as mysql should probably be a dependency.

Let me know what you think,
Best,
David

**Comment by Frick-David** [comment]
Also, I am unsure if `kdepim-runtime` is installed by default with korganizer. I was having the same issue listed here and this fixed it: See
https://forums.opensuse.org/showthread.php/527179-Is-kOrganizer-ical-import-broken-in-42-3

**Comment by b1scu1t** [comment]
Korganizer works with either `mysqld` or `sqlite3`.
I don't believe having `mysqld` as hard dependency is a good idea.
Maybe a message should be displayed, alerting the user to install either one of the two?

**Comment by Frick-David** [comment]
okay fair enough. I can say that installing the package for it off the bat did not work for me. Is `sqlite3` installed by default on void such that it should work out of the box?-

**Comment by sgn** [comment]
I think it would be simple enough to make Korganizer depends on sqlite?
A lot of users have one or more of those packages installed `nss` (via `firefox`, `chromium`), `webkit2gtk`, `python3`, `mpd`, `gnupg2`, and `fwupd`. Those packages all pulls `sqlite` in.

**Comment by Frick-David** [comment]
Does void not also come with `python3` installed by default? It is interesting that I have `python3` installed (python developer), yet Korganizer did not detect `sqlite`. I would assume I also have `sqlite` installed as well.

**Comment by b1scu1t** [comment]
You are correct. It seems that you must manually specify the database back-end in `~/.config/akonadi/akonadiserverrc`.
It's set to 'Q**MYSQL**'  by default.
Check here for more info: https://wiki.archlinux.org/index.php/KDE#SQLite

Akonadi also supports PostgreSQL, apparently.
