### ISSUE TITLE
wayfire: missing desktop file

### ISSUE THREAD

**Issue by glats** [void-linux/void-packages#25260]
### System

* xuname: Void 5.8.12_2 x86_64-musl GenuineIntel notuptodate rrnFF
* package: wayfire-0.5.0_1

### Expected behavior

After install the package should create a file on wayland-sessions folder like: /usr/share/wayland-sessions/wayfire.desktop

### Actual behavior

doesn't createl anything

### Steps to reproduce the behavior

xbps-install wayfire

**Comment by ericonr** [comment]
Can confirm it's missing... Not sure why it didn't install, will try to fix.

**Comment by ericonr** [comment]
heh, it's not installed by meson. I'm adding a build option as well, then.
