### ISSUE TITLE
xbps-update -Su error on python3-pycparser-2.19_3

### ISSUE THREAD

**Issue by p2501mk** [void-linux/void-packages#25269]
Regular morning xbps-update -Su errors out on above mentioned package.
### System

* xuname:  
  Void 5.8.12_2 x86_64 GenuineIntel notuptodate rrFFFF
* package:  
  python3-pycparser-2.19_3

### Expected behavior

update running smoothly

### Actual behavior

`[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...

Name                       Action    Version           New version            Download size
fontmanager                update    0.7.7_1           0.7.9_1                - 
libgexiv2                  update    0.12.0_2          0.12.1_1               - 
libxkbcommon               update    0.10.0_1          1.0.1_1                - 
libxkbcommon-x11           update    0.10.0_1          1.0.1_1                - 
linux5.8                   update    5.8.12_2          5.8.13_1               - 
linux5.8-headers           update    5.8.12_2          5.8.13_1               - 
python3-pip                update    20.2.3_1          20.2.3_2               - 
python3-setproctitle       update    1.1.10_6          1.1.10_7               - 
run-parts                  update    4.11.1_1          4.11.2_1               - 
python3-sabyenc3           install   -                 4.0.2_1                - 
python3-cheetah3           install   -                 3.2.5_1                - 
python3-ply                install   -                 3.11_3                 - 
python3-pycparser          install   -                 2.19_3                 - 
python3-cffi               install   -                 1.14.3_1               - 
python3-cryptography       install   -                 3.1_1                  - 
python3-feedparser         install   -                 5.2.1_7                - 
python3-configobj          install   -                 5.0.6_7                - 
python3-more-itertools     install   -                 8.5.0_1                - 
python3-jaraco             install   -                 1.0_1                  - 
python3-jaraco.functools   install   -                 3.0.1_1                - 
python3-Cheroot            install   -                 8.3.1_2                - 
python3-tempora            install   -                 2.0.0_2                - 
python3-portend            install   -                 2.5_3                  - 
python3-zc.lockfile        install   -                 2.0_3                  - 
python3-jaraco.classes     install   -                 3.1.0_1                - 
python3-jaraco.text        install   -                 3.2.0_1                - 
python3-jaraco.collections install   -                 3.0.0_1                - 
python3-CherryPy           install   -                 18.6.0_1               - 
python3-notify2            install   -                 0.3.1_1                - 
sabnzbd                    update    2.3.9_1           3.0.2_1                - 
sip                        update    4.19.24_1         4.19.24_2              - 

python3-pycparser-2.19_3: unpacking ...
ERROR: python3-pycparser-2.19_3: [unpack] failed to extract file `./usr/lib/python3.8/site-packages/pycparser/ply': folder not empty
`

xbps-pkgdb -m hold is not stopping the behavior

**Comment by Duncaen** [comment]
Any chance you installed some python packages with pip and its now resulting in the file conflict?

**Comment by p2501mk** [comment]
I've indeed got a ton of packages according to `pip list`. How do I know which one is causing the conflict?

**Comment by Duncaen** [comment]
pycparser, but its hard to tell if there are going to be more conflicts.
Generally its better to use pip in virtual envs or as user into the $HOME directory.

I guess you could uninstall all globally installed pip packages and then use `xbps-pkgdb -a` to see if it removed some files managed by xbps and then reinstall those with `xbps-install -f pkgname`.

**Comment by p2501mk** [comment]
Okay thanks, that bit about pip is good to know. I bet I installed something as root.

I was lazy and moved all files in that directory to a tmp one, xbps-update worked after that. Files in that dir got recreated with the update so in the end I don't know what caused the hang.

**Comment by Anachron** [comment]
Thats why I only install pkgs from non-xbps to a local directory. I do this with python, go, nodejs, ruby etc.

**Comment by p2501mk** [comment]
I guess I should do the same, then. Thanks for the hint! :3
