### ISSUE TITLE
Manual pages for some Tcl commands not accessible

### ISSUE THREAD

**Issue by msiism** [void-linux/void-packages#25285]
### System

* xuname: 
 ``Void 5.8.13_1 x86_64 GenuineIntel uptodate rF``
* package:  
``tcl-8.6.10_2``

### Problem description

Running ``man 3tcl expr``, ``man 3tcl file``, or ``man 3tcl join`` should turn up the manual page for the respective Tcl command, just as, e.g., running ``man 3tcl clock`` would.

But it doesn't. Instead, I get the manual pages for expr(1), file(1), and join(1), respectively.

Further testing suggests that this problem occurs with all Tcl commands that have a command of the same name in section 1 of the manual.

**Comment by ericonr** [comment]
You can access them with `man n expr`. Now as for why that's happening, I'm not sure.

**Comment by roarde** [comment]
The man command processed "3tcl" as a page-entry to search for, which matches with man's documentation.      
       `man -s n expr` displays the page for tcl's expr command. Section "n" is the default and usual place for tcl-command documentation. The man command will try using arguments as sections until the *first* one fails, then it and the remainder are taken to be pages to be searched for, and the first one found, rather than the first one listed in arguments, is displayed.  It found the *page* expr(1) first, so it didn't continue to look for the *page* for 3tcl. All proper. `man -s tcl3 expr` says "No entry for expr in section 3tcl of the manual"; also proper.         
            
We have tcl commands in section n, and the page for the installed binary tclsh in section 1; most usual, and by default. Tcl *libraries* are pulled off into the tcl-devel package along with their manpages in section 3.

Debian does histrionics with shell, sed, make, and patch to shove all the pages, *installed tclsh binary included*, into a created "3tcl". Confusion is normal, given that.

**Comment by roarde** [comment]
`man 3tcl clock` turns up clock(n) for the same, correct reason. The existing clock(n) page is turned up (provided makewhatis has run) before the non-existent 3tcl page. `man 3tcl clock` correctly comes up empty.

**Comment by msiism** [comment]
> Debian does histrionics with shell, sed, make, and patch to shove all the pages, _installed tclsh binary included_, into a created "3tcl". Confusion is normal, given that.

That's where I learned the habit then. Thanks for the clarification.
