### ISSUE TITLE
Package request: JetbrainsMono (Font)

### ISSUE THREAD

**Issue by unihernandez22** [void-linux/void-packages#25306]
## [JetBrains Mono](https://www.jetbrains.com/lp/mono/). A typeface for developers.
It’s free & open source.

**Comment by sgn** [comment]
Font = Close

**Comment by unihernandez22** [comment]
> Font = Close

What?!?!

**Comment by Anachron** [comment]
Fonts wont be added unless they provide extras other fonts dont have. The reason is: You can easily put your custom fonts in the fonts user directory to install any font you want.

**Comment by developer1-vd** [comment]
i wanted it but the other method is actually kinda me
