### ISSUE TITLE
Miniflux hard postgresql dependency

### ISSUE THREAD

**Issue by chilledfrogs** [void-linux/void-packages#25342]
Hello all,

I noticed that the `miniflux` package has a hard runtime dependency on `postgresql`, which is indeed required, but that doesn't account for versioned packages of `postgresql` which are also supported (I for instance use `postgresql12` and will soon upgrade to `postgresql13` on the server I want to install it to). I can't seem to find a way to edit the template file to make it work for any of the supported packages, so am I blind or is this genuinely impossible for the moment?

**Comment by ahesford** [comment]
This could be resolved by declaring a virtual package that all PostgreSQL versions may provide, but I am not a Postgres user and don't know if this is a reasonable approach in general. Others should weigh in.

In the meantime, if you want to work around the hard dependency, add `ignorepkg=postgres` to a conf file in `/etc/xbps.d` (see [xbps.d(5)](https://man.voidlinux.org/xbps.d.5)) and install whichever version you prefer.

**Comment by jnbr** [comment]
While it is true that miniflux needs a postgresql database, the specific version does not matter and there is also no need for it to be on the same host as miniflux itself.
I think the simpler and better solution in this case is to make miniflux not depend on postgresql.
This way, we can avoid all the pitfalls virtual packages come with.
