### ISSUE TITLE
Ulauncher depends python3-gobject

### ISSUE THREAD

**Issue by unihernandez22** [void-linux/void-packages#25374]
Add python3-gobject to Ulauncher run dependencies.

**Comment by biopsin** [comment]
Tried to build from current template, 
```
ERROR: Python module gi not found
ERROR: Python module gi not found
ERROR: Python module xdg.BaseDirectory not found
ERROR: Python module Levenshtein not found
ERROR: Python module gi not found
ERROR: Python module gi not found
ERROR: Python module ResultItem not found
ERROR: Python module gi not found
ERROR: Python module xdg.BaseDirectory not found
ERROR: Python module gi not found
ERROR: Python module gi not found
ERROR: Python module dbus not found
ERROR: Python module dbus.service not found
ERROR: Python module dbus.mainloop.glib not found
ERROR: Python module pyinotify not found
ERROR: Python module websocket not found
ERROR: Python module gi not found
```
Had to move all python3-* to makedepends to fix the errors, however I could not find a fix for
`ERROR: Python module ResultItem not found` unshure which module it's in..

**Comment by unihernandez22** [comment]
> Had to move all python3-* to makedepends to fix the errors, however I could not find a fix for
> `ERROR: Python module ResultItem not found` unshure which module it's in..
@biopsin 

I think that package is [datastore](https://pypi.org/project/datastore/)

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/commit/01af9f22da307a241f6c944fe6b40e7e68ae32ea
