### ISSUE TITLE
Please add "hacktoberfest" tag/topic

### ISSUE THREAD

**Issue by reback00** [void-linux/void-packages#25383]
I just got an email describing changes for Hacktoberfest this year. They've changed the rules. Now, repositories have to manually opt-in in order to accept entries for Hacktoberfest. Either (a) a "hacktoberfest" tag/topic can be added to accept all PRs on the repo or (b) add a "hacktoberfest-accepted" tag to each PR to be accepted (which is probably impractical for this repo with so many PRs).

The email has these changes highlighted:

> After working closely with our friends at GitHub, we are happy to introduce measures that are brand new to Hacktoberfest 2020.
> 1. Pull requests can be made in any __participating__ GitHub-hosted repositories/projects.
> 
> 2. Maintainers can opt-in to participate by [classifying their projects with the hacktoberfest topic](https://www.youtube.com/watch?v=FxBv4FMcDgo&ab_channel=DigitalOcean).
> 
> 3. Your pull requests will count toward your participation if they are in a repository with the hacktoberfest topic and once they have been merged, approved by a maintainer or labelled as hacktoberfest-accepted.
> 
> 4. Additionally, any pull request with the hacktoberfest-accepted label, submitted to any public GitHub repository, with or without the hacktoberfest topic, will be considered valid for Hacktoberfest.
> All valid pull requests prior to Oct 3 (when these rules were introduced) will be honored and counted toward completion of Hacktoberfest.
> 
> __[Learn more](https://hacktoberfest.digitalocean.com/hacktoberfest-update) about the changes we've made that will affect your participation.__

I participated in previous year's Hacktoberfest with [PRs only from this repo](https://www.reddit.com/r/voidlinux/comments/dkwpvr/yaaayyy_i_completed_this_years_hacktoberfest_with/). So please add the "hacktoberfest" tag/topic so that many like me can try this year with this repo.

**Comment by Zeinok** [comment]
it is already there.

**Comment by reback00** [comment]
Oops, my bad! I saw in the hacktoberfest dashboard that my PRs were not being accepted and that it said it has something to do with the repo not opting in to hacktoberfest. I guess it will update later then.
