### ISSUE TITLE
zathura: incompatible jbig2dec header and library versions

### ISSUE THREAD

**Issue by Kratacoa** [void-linux/void-packages#25438]
When outputting certain PDF files, zathura gives me the following errors:
``` 
warning: jbig2dec error: incompatible jbig2dec header (0.18) and library (0.19) versions (segment -1)
error: cannot allocate jbig2 context
```
With the result being a blank PDF file being reproduced.  
Not sure if it's a build problem, or if it's upstream.

### System

* xuname:  
Void 5.8.14_1 x86_64-musl GenuineIntel uptodate rrnFFF
* package:  
zathura-0.4.7_1, using zathura-pdf-mupdf-0.3.6_1

**Comment by Kratacoa** [comment]
@lemmi , if it's not a Void problem I'll report it to the official repository.

**Comment by Anachron** [comment]
Can you create a minimal example and post it here?

**Comment by lemmi** [comment]
This is the first time I see this error. I'd assume the error doesn't appear with poppler? Personally I stopped using the mupdf backend a long time ago since it had been the cause of multiple issues in the past. 
That said: If you can provide an example, maybe we can dig something up.

**Comment by Kratacoa** [comment]
The file I used is [hosted here](https://files.catbox.moe/umg1h8.pdf).

**Comment by lemmi** [comment]
As expected it works with poppler. Mupdf throws the same error. I'm rebuilding all the direct dependencies locally, maybe a simple revbump takes care of this.

**Comment by lemmi** [comment]
Rebuilding a bunch of dependencies worked. I'll revbump these packages and this should solve the issue.

**Comment by lemmi** [comment]
@Kratacoa update is through. Can you confirm it working?

**Comment by Kratacoa** [comment]
Yep, works just fine. Thank you :)  
I'll close the issue.

**Comment by lemmi** [comment]
Thanks for reporting.
