### ISSUE TITLE
libguestfs error: cannot find any suitable libguestfs supermin (...)

### ISSUE THREAD

**Issue by rapha8l** [void-linux/void-packages#25457]
### System

* xuname:  
Void 5.8.14_1 x86_64 GenuineIntel notuptodate rrrmFFFF

* package:  
libguestfs-1.42.0_3

libguestfs-test-tool                                                                                                                                                                 1 < 16:07:38
     ************************************************************
     *                    IMPORTANT NOTICE
     *
     * When reporting bugs, include the COMPLETE, UNEDITED
     * output below in your bug report.
     *
     ************************************************************
SELinux: sh: 1: getenforce: not found
guestfs_get_append: (null)
guestfs_get_autosync: 1
guestfs_get_backend: direct
guestfs_get_backend_settings: []
guestfs_get_cachedir: /var/tmp
guestfs_get_hv: /usr/bin/qemu-system-x86_64
guestfs_get_memsize: 768
guestfs_get_network: 0
guestfs_get_path: /usr/lib/guestfs
guestfs_get_pgroup: 0
guestfs_get_program: libguestfs-test-tool
guestfs_get_recovery_proc: 1
guestfs_get_smp: 1
guestfs_get_sockdir: /tmp
guestfs_get_tmpdir: /tmp
guestfs_get_trace: 0
guestfs_get_verbose: 1
host_cpu: x86_64
Launching appliance, timeout set to 600 seconds.
libguestfs: launch: program=libguestfs-test-tool
libguestfs: launch: version=1.42.0
libguestfs: launch: backend registered: unix
libguestfs: launch: backend registered: uml
libguestfs: launch: backend registered: direct
libguestfs: launch: backend=direct
libguestfs: launch: tmpdir=/tmp/libguestfsP6oTn4
libguestfs: launch: umask=0022
libguestfs: launch: euid=3392
libguestfs: error: cannot find any suitable libguestfs supermin, fixed or old-style appliance on LIBGUESTFS_PATH (search path: /usr/lib/guestfs)
libguestfs: closing guestfs handle 0x55efbcd0bc50 (state 0)
libguestfs: command: run: rm
libguestfs: command: run: \ -rf /tmp/libguestfsP6oTn4

**Comment by benalb** [comment]
As root, you must create the "/usr/lib/guestfs" directory and run update-libguestfs-appliance. 
Then,  probably will fail, because of [this](https://github.com/void-linux/void-packages/pull/25686).
You can wait to the PR to be merged and update, or as a workaround edit the update-libguestfs-appliance script.

**Comment by rapha8l** [comment]
thanks, I did it, and it worked

**Comment by benalb** [comment]
Please, close the issue. :)

**Comment by sjhaleprogrammer** [comment]
why close this ?

**Comment by classabbyamp** [comment]
probably because it was fixed

don't necrobump old issues
