### ISSUE TITLE
Can't upgrade WINE to v5.19_1

### ISSUE THREAD

**Issue by chilledfrogs** [void-linux/void-packages#25523]
### System

* xuname:  
  Void 5.8.13_1 x86_64 GenuineIntel uptodate rrrrmdFFFFFFF
* package:  
  `wine-common`

### Expected behavior
Should get upgraded along with all other WINE components to 5.19_1

### Actual behavior
```
MISSING: wine-common>=5.19_1
Transaction aborted due to unresolved dependencies.
```

### Steps to reproduce the behavior
Just a simple system upgrade

Considering that `wine-common` is a subpackage of `wine` by the looks of it, I'm wondering if it's a repo bug or something on my side since they should all remain in sync...

**Comment by sug0** [comment]
I can reproduce.
![](https://u.sicp.me/jxjxj.png)

**Comment by chilledfrogs** [comment]
Indeed, just checked with a local build with `./xbps-src`, seems to be a repo update problem

**Comment by ev-ermakov** [comment]
```sh
$ xuname 
Void 5.8.14_1 x86_64-musl GenuineIntel uptodate rFFFFF
```
Can't reproduce.

**Comment by sug0** [comment]
@ev-ermakov Could you please run the following?
```
$ xbps-query -R wine | grep pkgver && xbps-query -R wine-32bit | grep pkgver
```
The 64-bit version of wine installs for me, too; unfortunately, the 32-bit version doesn't. The repository data for the 64-bit version is outdated, as of the time of my writing.

**Comment by ev-ermakov** [comment]
@sug0, Yeah, there is only 32-bit version:
```sh
$ xbps-query -R wine | grep pkgver && xbps-query -R wine-32bit | grep pkgver
pkgver: wine-5.19_1
```

**Comment by ahesford** [comment]
This is a consequence of a large update that is being processed and holding back the availability of the new `wine-common`. It should be resolved soon.

**Comment by sug0** [comment]
Solved.
