### ISSUE TITLE
[package request] MusE - A Digital Audio Workstation

### ISSUE THREAD

**Issue by uzr123x** [void-linux/void-packages#25520]
A nice free DAW for GNU/Linux that's been around for decades, I think it fills in the niche of an all-around workstation, unlike other popular FLOSS sequencers that excel in some limited areas but can be deficient in other regards.
https://muse-sequencer.github.io

**Comment by userabc123xyz** [comment]
you forgot to add a 'request' label to my issue (-:

**Comment by ericonr** [comment]
Closed in #25526
