### ISSUE TITLE
XBPS actions from xbps-src are added to syslog

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#25534]
### Expected behavior

Building a package with xbps-src doesn't add multiple entries to syslog, so `svlogtail xbps` only includes entries run on the actual system.

### Actual behavior

Building a package with xbps-src adds multiple entries to syslog, unnecessarily polluting `svlogtail xbps` output.

---

I'm not sure what the correct place for fixing this is? Perhaps a flag for XBPS to not store info in syslog.

**Comment by Duncaen** [comment]
https://github.com/void-linux/void-packages/blob/63f45dc7400894ceca8053e387e37196797448a2/common/xbps-src/shutils/chroot.sh#L131

**Comment by ericonr** [comment]
Any idea why I would still be getting syslog entries, then?

**Comment by ericonr** [comment]
`binary-bootstrap` -> entries in syslog

`xbulk pam` -> installs deps, then removes them

**Comment by Duncaen** [comment]
I guess it just gets deleted on the first use again:
https://github.com/void-linux/void-packages/blob/63f45dc7400894ceca8053e387e37196797448a2/common/xbps-src/shutils/chroot.sh#L195

**Comment by ericonr** [comment]
Oh wow! Ok. I will try to make a PR to fix that, then. Thanks for finding where it happens.
