### ISSUE TITLE
Package Request: xow

### ISSUE THREAD

**Issue by infinitelytimelesstech** [void-linux/void-packages#25532]
A tool that allows people to use the Xbox Wireless USB Adaptor from Microsoft to connect an Xbox One controller wirelessly on Linux with rumble support. Github page is [here](https://github.com/medusalix/xow). The developer's github page states that it requires systemd, but I've got it running as a simple runit service for some time now. Would love to see this in the void repos.

Example xow runit service:
`#!/bin/sh
sudo -u nobody /usr/local/bin/xow`

EDIT: Appropriate udev rules are also needed: (/etc/udev/rules.d/50-xow.rules)
`# Make dongles and uinput accessible to all users
SUBSYSTEM=="usb", ATTRS{idVendor}=="045e", ATTRS{idProduct}=="02e6", MODE:="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="045e", ATTRS{idProduct}=="02fe", MODE:="0666"
KERNEL=="uinput", SUBSYSTEM=="misc", MODE:="0666"`

**Comment by Fxzzi** [comment]
Bumping this. Would be greatly appreciated.

**Comment by MIvanchev** [comment]
IMO this can be closed, xone is already in Void and is recommened over xow even by the latter's devs.
