### ISSUE TITLE
apparmor: invalid capability net_bind_service (and others)

### ISSUE THREAD

**Issue by the-antz** [void-linux/void-packages#25548]
### System

* xuname:  `Void 5.8.14_1 x86_64 GenuineIntel notuptodate rrDDFF`
* packages: `apparmor-2.13.4_3` and `libapparmor-2.13.4_3`

The `notuptodate` is because I downgraded to (lib)armor-2.13.4_2 which fixes the issue, the other packages are all current.

On the latest version the included rules result in errors like `invalid capability net_bind_service`. Apparmor seems to not know about any capabilities.

The latest revbump 7938b2d5effc247ea0d04a0e3d8faabdd115bcfc only removed the `noarch` keyword but it's rebuild with python 3.9 which seems to silently result in a broken package. It seems there was a similar issue in the past, see https://gitlab.com/apparmor/apparmor/-/issues/74.

**Comment by ahesford** [comment]
I think your linked issue describes the problem. See #25550. This seems unrelated to the Python bump, except for incidentally triggering a rebuild with the empty headers.
