### ISSUE TITLE
dhclient: service leaks logs to runsvdir

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#25558]
### System

* xuname: `Void 5.8.12_2 x86_64 GenuineIntel uptodate rFF`
* package: dhclient-4.4.2_2

### Expected behavior

do not log to stderr

### Actual behavior

dhclient sends logs to stderr

### Steps to reproduce the behavior

run dhclient

**Comment by ericonr** [comment]
Should be a matter of adding a logger to the service?
