### ISSUE TITLE
apparmor chronyd profile is broken

### ISSUE THREAD

**Issue by PaperMountainStudio** [void-linux/void-packages#25572]
### System

* xuname:  
  *`Void 5.8.14_1 x86_64 GenuineIntel notuptodate hold rrrmDDDDDDDDDDDDDFFFFFFFFFFFFFFFFFF`*
* package:  
  *``chrony-4.0_1``

### Expected behavior
```
%: sudo chronyd -n -u chrony

```
### Actual behavior
```
%: sudo chronyd -n -u chrony
Fatal error : Could not open /var/run/chrony/chronyd.pid : Permission denied
```
### Steps to reproduce the behavior
- install and setup apparmor
- enforce chronyd rule - `aa-enforce chronyd`
- `sv stop chronyd`
- `sudo chronyd -n -u chrony`

**Comment by CameronNemo** [comment]
AFAICT we do not ship an AppArmor profile for chronyd.

* `xlocate '^/etc/apparmor.d/.*chrony.*'`
* `grep -ri chrony srcpkgs/apparmor/` in void-packages
* checked the chrony package for any apparmor profiles
* `find . -name '*chrony*'` in the upstream AppArmor repository

**Comment by PaperMountainStudio** [comment]
huh? I would have sworn that I didn't download it from an external source, but it seems like that's the case, sorry
