### ISSUE TITLE
libfido2: missing udev rules?

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#25603]
I'm unable to use `libfido2` with my u2f usb key (yubikey), because it misses the corresponding `udev` rules. Those rules are instead provided by the older `libu2f-host`, with which my usb key works fine. I can try to add those myself, although I'm not sure how to do it exactly, as the new package uses cmake while old one gnumake. Does that make sense to you?

**Comment by CameronNemo** [comment]
What is the issue here? That the udev rules are shipped in libu2f-host? That is expected behavior AIUI.

**Comment by dkwo** [comment]
The issue here is that udev rules are absent in the newer `libfido2`.

**Comment by sgn** [comment]
> The issue here is that udev rules are absent in the newer `libfido2`.

Sorry if I missed anything, but what wrong with installing both? They aren't conflicts.

**Comment by dkwo** [comment]
My understanding is that libfido2 supersedes libu2f-host, so even though 
there are no conflicts, it should be possible to only use the first and 
have everything working; also consider that the github of libfido2 has 
more updated udev rules, and it suggests to install those.

That's why I think the libfido2 template should be modified accordingly, 
perhaps also including hidapi as a dependence.

**Comment by sgn** [comment]
Hm, perhaps we can split the udev rules into its own package and let `libfido2` and `libu2f-host` depends on it.

**Comment by sgn** [comment]
#25646

**Comment by dkwo** [comment]
@sgn Thanks a lot, that should work.
I'm not really sure, but do you think `libfido2` should also depend on `hidapi-devel`?

**Comment by sgn** [comment]
That depends on leah2's opinion, you should ask them on IRC, they're more active there.
I don't care much about `hidapi-devel` since I don't use anything that requires it.

**Comment by dkwo** [comment]
I see.
I tried the updated package, and it works for me without `hidapi`, so for the moment I'm happy.
Thanks.
