### ISSUE TITLE
Package Request - Bisq

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#2560]
Hi
Could I please request Bisq to be packaged for Void?
The Github source code link is: https://github.com/bisq-network/exchange/archive/v0.8.0.tar.gz
The website is at: https://bisq.network/ or https://github.com/bisq-network/bisq
Thanks.

**Comment by cr6git** [comment]
For this to work you will need [OpenJFX](https://wiki.openjdk.java.net/display/OpenJFX/Main), which is not in Void repository.

Regards.
