### ISSUE TITLE
mozjs38-38.8.0_6: broken, unresolvable shlib `.....

### ISSUE THREAD

**Issue by freedomrun** [void-linux/void-packages#2561]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*

mozjs38-38.8.0_6: broken, unresolvable shlib `libicui18n.so.59'
mozjs38-38.8.0_6: broken, unresolvable shlib `libicuuc.so.59'
Transaction aborted due to unresolved shlibs.

* package:  
  *affected package(s) including the version*

xbps-query -x mozjs38
glibc>=2.25_1
icu-libs>=59.1_1
nspr>=4.8_1
zlib>=1.2.3_1
libstdc++>=4.4.0_1
libgcc>=4.4.0_1

### Expected behavior
system update
### Actual behavior
system update: halted
### Steps to reproduce the behavior
sudo xbps-install -Suv

**Comment by maxice8** [comment]
mozjs38 was removed on 25th of June 2018.

Remove from the system.

**Comment by fosslinux** [comment]
@maxice @freedomrun close please 😃

**Comment by freedomrun** [comment]
sudo xbps-remove -y mozjs38  (helps :+1:  ) thank you.
Is there a place where those changes can be tracked (like FreeBSD UPDATING file)?
Best regards
