### ISSUE TITLE
Package request : docklike-plugin

### ISSUE THREAD

**Issue by siduck** [void-linux/void-packages#25661]
docklike-plugin is a xfce panel plugin that lets you pin apps and use the panel like a dock.
https://github.com/nsz32/docklike-plugin

**Comment by mobinmob** [comment]
It has no releases  but is seems very nice.

**Comment by siduck76** [comment]
yeah Ive compiled it from src and it works , will make a package soon.

**Comment by MLito747** [comment]
so is the package already in the repo?

**Comment by siduck** [comment]
> so is the package already in the repo?

No,  I compiled it from the source!

**Comment by MLito747** [comment]
Will it be available on the repo?
![image](https://user-images.githubusercontent.com/94821482/147630025-84350e4a-f813-4663-b576-bd71adde5530.png)

**Comment by siduck** [comment]
> Will it be available on the repo? ![image](https://user-images.githubusercontent.com/94821482/147630025-84350e4a-f813-4663-b576-bd71adde5530.png)

We need to ask it's creator to make releases

**Comment by classabbyamp** [comment]
done in 4384718b0361de66efda66444a1526e140f88725
