### ISSUE TITLE
mypaint-2.0.0_1 missing link '/usr/lib/mypaint/lib/_mypaintlib.so'

### ISSUE THREAD

**Issue by abhocetabhac** [void-linux/void-packages#25739]
Package 'mypaint-2.0.0_1' does not create link file '/usr/lib/mypaint/lib/_mypaintlib.so' to '/usr/lib/mypaint/lib/_mypaintlib.cpython-38-x86_64-linux-gnu.so'. Consequently, mypaint fails to start up.

The makeshift solution is to manually create the link:
'sudo ln -s ./_mypaintlib.cpython-38-x86_64-linux-gnu.so /usr/lib/mypaint/lib/_mypaintlib.so'.

**Comment by sgn** [comment]
Looks  like noone else uses `mypaint` :-p This is broken for about 1 year :-p
