### ISSUE TITLE
"man 3 syslog" shows syslog(2)

### ISSUE THREAD

**Issue by loreb** [void-linux/void-packages#2575]
### System

* xuname:  
  Void 4.18.6_1 x86_64-musl GenuineIntel uptodate rF
* package:  
  mdocml-1.14.4_1

### Expected behavior
man 3 something shows something(3)

### Actual behavior
**sometimes** it's ok, **sometimes** it shows something(2)

### Steps to reproduce the behavior
$ cd /usr/share/man; for i in *.3; do j=${i%.3}; test -e ../man2/$j.2&&man 3 $j; done

I tried to reproduce in a glibc vm since I'm using musl, and it didn't reproduce at first,
but manually running /etc/cron.daily/makewhatis made the bug appear.

Edit: if you have poxis manpages installed, man 3p syslog works.

**Comment by chneukirchen** [comment]
I can reproduce on glibc, will talk to upstream.

**Comment by chneukirchen** [comment]
I think the reason is that klogctl(3) links to this page and this creates confusion.

**Comment by loreb** [comment]
Ok thank you!
