### ISSUE TITLE
lxc-4.0.4_1 with both gnupg 1.x and 2.x

### ISSUE THREAD

**Issue by brdelphus** [void-linux/void-packages#25750]
### System

* xuname:  
  Void 5.8.16_1 x86_64 GenuineIntel uptodate rFFF

* package: 
  *affected package(s) including the version*: lxc-4.0.4_1

### Expected behavior
the ability to use download template to download os container templates
### Actual behavior
ERROR: Unable to fetch GPG key from keyserver
### Steps to reproduce the behavior
lxc-create -n mycontainer -t download -- --dist voidlinux --release current --arch x86_64

Further investigation shows me that the gpg option --receive-keys was -recv-keys on gnupg 1.x 
reason why it fails to store necessary keys, not sending pull requests cos I am not familiar with 
(we either specify which version of gnupg to be used, or check gpg simlinks to match template)

Thank you

**Comment by brdelphus** [comment]
Just tried using gpg version 1.x and it doesn't work, so I believe it should be forced to use the gpg2 binary instead of gpg as is hardcoded on lxc-download template

**Comment by CameronNemo** [comment]
the download template is shipped as-is from upstream. you may need to write a patch to make it use the gpg2 binary.

**Comment by ericonr** [comment]
@CameronNemo Anything we can act on? Maybe patch the template?

**Comment by paper42** [comment]
/usr/bin/gpg is now gpg2
