### ISSUE TITLE
python-pandas checksum changed

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#2577]
I didn't want to *fix* it without confirmation. The new checksum is `fc829f9014fc756511cba878179811322514c5cb8dcbf39b02062f80f1f6170f` xbps-src tells me.

**Comment by maxice8** [comment]
can confirm

**Comment by pullmoll** [comment]
IMO we should let @asergi decide if the change is legitimate.

**Comment by asergi** [comment]
Here's the diff:
```diff
diff -r pandas-0.23.4.old/pandas/_version.py pandas-0.23.4/pandas/_version.py
23c23
<     git_refnames = " (tag: v0.23.4, 0.23.x)"
---
>     git_refnames = " (tag: v0.23.4)"                                 
```
