### ISSUE TITLE
Can't view webp images with feh, sxiv even though imlib2 should provide webp support

### ISSUE THREAD

**Issue by kartikynwa** [void-linux/void-packages#25795]
### System

* xuname:  `Void 5.8.16_1 x86_64 GenuineIntel uptodate hold rrrmFFFFFFFFFFFFFFF`
* package:  
  - `imlib2-1.7.0_2`
  - `feh-3.5_1`
  - `sxiv-26_1`

### Expected behavior
`feh`, `sxiv` should be able to open webp images since `imlib2` provides `/usr/lib/imlib2/loaders/webp.so`. For example, this should work:

```
curl https://www.gstatic.com/webp/gallery/1.webp | feh -
```

### Actual behavior
`feh` fails with the message: `feh WARNING: /tmp/feh_stdin_iWj0N5 - No Imlib2 loader for that file format`

### Steps to reproduce the behavior

```bash
xbps-install -Sf feh curl
curl https://www.gstatic.com/webp/gallery/1.webp | feh -
```

### Note

Installing [this](https://github.com/gawen947/imlib2-webp) makes it possible to open webp files. But it overwrites the `webp.so` installed by xbps.

**Comment by PaperMountainStudio** [comment]
works on my system with feh, sxiv and imv

**Comment by kartikynwa** [comment]
> works on my system with feh, sxiv and imv

What's your arch and libc?

**Comment by ericonr** [comment]
I think `imv` uses a different loader, I don't even have `imlib2` installled.

**Comment by ericonr** [comment]
That said, `feh` on x86_64-musl does work with that image.

`feh image.webp` works; `feh < image.webp` gives me the `No Imlib2 loader for that file format` error`, and opens a random image that's in the current directory; and `feh - < image.webp` also works.

**Comment by q66** [comment]
paste the output of `ldd` on the broken `webp.so`

**Comment by ericonr** [comment]
On glibc, it fails when doing `feh - < file`, but not if I open it directly.

```
[chroot] /tmp > ldd /lib/libwebp.so.7
        linux-vdso.so.1 (0x00007fff08f51000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fa5e4f7e000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fa5e4f5d000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fa5e4d9a000)
        /lib/ld-linux-x86-64.so.2 (0x00007fa5e514f000)
```

**Comment by kartikynwa** [comment]
Hmm seems like the following work:

- `feh 1.webp`
- `feh < 1.webp`
- `cat 1.webp | feh`

But these don't work:

- `feh - < 1.webp`
- `cat 1.webp | feh -`

So looks like the `webp.so` work fine. It's just the loader choosing to load it that is at fault. So the issue seems to not be with the packaging. Let me know if I should close the issue.

**Comment by ericonr** [comment]
Wow, talk about inconsistent behavior.

**Comment by kartikynwa** [comment]
But the git repo I mentioned earlier handles `feh < 1.webp` and `cat 1.webp | feh` properly. I will just file an issue with imlib2.

**Comment by kartikynwa** [comment]
> Wow, talk about inconsistent behavior.

Actually I might have misinterpreted. `feh < 1.webp` and `cat 1.webp | feh` don't work and, AFAIK, they shouldn't. They just lead to `feh` opening up the whole folder and `1.webp` happens to be in it.
