### ISSUE TITLE
spotify does not download but still installs

### ISSUE THREAD

**Issue by waynevanson** [void-linux/void-packages#25806]
### System

* xuname:
  `Void 5.8.16_1 x86_64 GenuineIntel uptodate rrFFF`
* package:
  `spotify-1.1.26_1`

### Expected behavior

`sudo xbps-install -y spotify` installs spotify with spotify.

### Actual behavior

Spotify is "installed" in the sense that it can be removed with `sudo xbps-remove -y spotify`.
It downloads to about 18% for me and then throws the error below.
```sh
$ sudo xbps-install spotify
Password:

Name    Action    Version           New version            Download size
spotify install   -                 1.1.26_1               -

Size required on disk:          229B
Space available on disk:        63GB

Do you want to continue? [Y/n]

[*] Verifying package integrity
spotify-1.1.26_1: verifying RSA signature...

[*] Collecting package files
spotify-1.1.26_1: collecting files...

[*] Unpacking packages
spotify-1.1.26_1: unpacking ...

[*] Configuring unpacked packages
spotify-1.1.26_1: configuring ...
looking up repository.spotify.com
connecting to repository.spotify.com:80
connecting to 99.84.199.56
requesting http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.26.501.gbe11e53b-15_amd64.deb
http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.1.26.501.gbe11e53b-15_amd64.deb: (null)
Failed downloading spotify client
ERROR: spotify-1.1.26_1: [configure] INSTALL script failed to execute the post ACTION: Operation not permitted
Transaction failed! see above for errors.
```

### Steps to reproduce the behavior
1. `sudo xbps-install -Suy`
1. `sudo xbps-install -y spotify`

**Comment by ericonr** [comment]
`spotify` is not a package we can distribute, so we used to ship a `INSTALL` script that downloaded it on the user machine. For a better solution, we have turned the package into a `restricted` one, which you should build locally.

Spotify has probably removed the old version from their website, the new one is 1.1.42.

**Comment by waynevanson** [comment]
Thank you for explaining this :)

update version #25663
enable restricted #23576
