### ISSUE TITLE
Kicad's pcbnew is missing an empty footprint library

### ISSUE THREAD

**Issue by xyzz** [void-linux/void-packages#25828]
### System

* xuname:  Void 5.8.16_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFF
* package:  kicad-footprints-5.1.7_1

### Expected behavior

No error is generated when attempting to place a footprint

### Actual behavior

An error is displayed:

```
Errors were encountered loading footprints:
Footprint library path "/usr/share/kicad/modules/Connector_Multicomp.pretty" does not exist
```

After clicking "ok", I can use pcbnew fine. The error is only displayed once per session.

### Steps to reproduce the behavior

1. Open `pcbnew`
1. Press `o`, click on empty pcb area

It looks like `Connector_Multicomp.pretty` is missing, which is supposed to be an empty folder according to https://gitlab.com/kicad/libraries/kicad-footprints/-/tree/master/Connector_Multicomp.pretty

**Comment by ericonr** [comment]
I can take a look at this over the weekend, if you don't know of a solution by then.

**Comment by xyzz** [comment]
Thanks, it's no big deal since it's just an error msg which goes away after the first time, doesn't look like affects anything.

**Comment by ericonr** [comment]
Ok, while building kicad I noticed that the folder was empty, and therefore being removed from the package :)

**Comment by ericonr** [comment]
Should be fixed in the PR above, thanks for the report!
