### ISSUE TITLE
Anki: Sound and video on cards will not function until mpv or mplayer is installed

### ISSUE THREAD

**Issue by My9xVm** [void-linux/void-packages#25848]
### System

* package:  
  * anki-2.1.15_3
  * mpv-0.32.0_4

### Expected behavior

Can play audio

### Actual behavior

Can't play audio

### Steps to reproduce the behavior

Open anki with mpv as audio backend

### Additional info

https://github.com/ankitects/anki/commit/ccd715013609133c55e83924734efa78abc03326

**Comment by fosslinux** [comment]
I believe this is a wontfix, we don't want to unnecessarily install mpv or mplayer when it is not needed -- maybe a message in INSTALL would be nice though

**Comment by ericonr** [comment]
anki itself could show an error message, perhaps?

**Comment by My9xVm** [comment]
I installed mpv, but anki can't find mpv.

see https://anki.tenderapp.com/discussions/ankidesktop/38186-mpvprocesserror-unable-to-start-process
