### ISSUE TITLE
nextcloud client main window does not open

### ISSUE THREAD

**Issue by manfredu** [void-linux/void-packages#25877]
### System

Void 5.8.16_1 x86_64 GenuineIntel notuptodate rrFFFFF

nextcloud-client-3.0.2_1

### Expected behavior

With the right button a menu opens with the following options:

"Hauptfenster öffen" (Open main window)
"Einstellungen" (Settings)
"Nextcloud beenden" (Close nextcloud)

Expected behavoior:

All three options work.

### Actual behavior

The first option does not work. Nothing happens, there is also no error message.

This is a problem e.g. in case of conflicts because it is not possible the see which files are in conflict.

The other two options do work fine.

### Steps to reproduce the behavior

Open the menu of the nextcloud client by clicking on the nc icon in the taskbar with the right mouse button. Click on the first option and a window should open.

**Comment by yopito** [comment]
hello, can't reproduce: fine here (x86_64 musl).   
Did you restarted the nextcloud applet once you've upgraded to 3.0.2 ?

**Comment by manfredu** [comment]
This already happened with the previous version. Mmh, maybe this is caused the desktop environment. I'm using Project Trident with DE Lumina, which is based on fluxbox.

**Comment by manfredu** [comment]
Ok, I could solve it. I had to install the package qt5-graphicaleffects. So this needs to be added as dependency. 

(S.a. https://github.com/nextcloud/desktop/issues/2390)
