### ISSUE TITLE
[RFC] Update NetworkManager

### ISSUE THREAD

**Issue by codingHahn** [void-linux/void-packages#25891]
We currently ship NetworkManager 1.22. Since then, 1.24 with OWE/Enhanced Open has been released.

Are there any blocking issues on updating NetworkManager to 1.24 or 1.26?

**Comment by not-chicken** [comment]
Needs libnma(#24497) and I guess modifications to https://github.com/void-linux/void-packages/blob/master/srcpkgs/NetworkManager/patches/fix-cross-gir.patch

**Comment by cinerea0** [comment]
@codingHahn #24497 has been merged, so the only thing left is the fix-cross-gir patch.

**Comment by codingHahn** [comment]
Ok. I'll see if I find time next weekend

**Comment by codingHahn** [comment]
Took a bit longer than I anticipated. The PR is here https://github.com/void-linux/void-packages/pull/27502

**Comment by ericonr** [comment]
PR is open, this will now be tracked there.
