### ISSUE TITLE
kodi-addon-pvr-zattoo update is crashing

### ISSUE THREAD

**Issue by teldra** [void-linux/void-packages#25912]
I encounter some problems when updating `kodi-addon-pvr-zattoo` to 18.1.21.
The update is necessary, because of the changes by zattoo: There is no login possible with the old version of this addon.

`kodi` uses `rapidjson`.
It can either use systems `rapidjson-1.1.0_3` or build its own (`rapidjson-1.1.0`).
At the moment, it is using systems `rapidjson`.

`kodi-addon-pvr-zattoo` needs `rapidjson`.
With systems `rapidjson`, it is crashing at runtime (after entering credentials for zattoo).

With the one provided by `kodi`, its working:
I removed `rapidjson` from makedepends in the templates of `kodi` and `kodi-addon-pvr-zattoo`.
I built `kodi`s rapidjson explicitly via template file (added `make PREFIX=/usr -C tools/depends/target/rapidjson`) and cluttered masterdir. With this cluttered masterdir I built `kodi-addon-pvr-zattoo` and it is not crashing at runtime.

I tried to build `kodi` with `-DENABLE_INTERNAL_RapidJSON=ON` and its fetching `rapidjson` from them.
Build is mostly fine, but at ~70-80% of the build, something (`JSONVariantWriter.cpp`) fails, saying it cant find some *.h `rapidjson` normally provides at `masterdir/builddir/xbmc-18.9-Leia/build/build/include/rapidjson/`. (`prettywriter.h` and `reader.h`)

I tried to patch `rapidjson` with upstream patch from `kodi`s repo and set `-DRAPIDJSON_HAS_STDSTRING=ON` and use it without success.

Can someone help?

Ressources:
https://github.com/xbmc/xbmc/tree/Leia/tools/depends/target/rapidjson

**Comment by Hoshpak** [comment]
I have removed the patch that seemed to cause the issues (at least it made the rapidjson test suite fail) from our rapidjson package. A rebuild for kodi and the addon is currently running. Please verify if the new addon version works for you with the recompiled packages. If you are interested in taking maintainership of the zattoo addon, feel free to do so as I have no interest in the addon.

**Comment by teldra** [comment]
Thank you very much. I did not thought, that this patch was the problem.
The addon is working as intended and I take maintainership.
