### ISSUE TITLE
Update request: Anki-2.1.4

### ISSUE THREAD

**Issue by natemonster321** [void-linux/void-packages#2591]
Anki 2.0.x will not be receiving updates anymore, and 2.1.x is the new stable release.

**Comment by CameronNemo** [comment]
I created a pull request, please test

**Comment by tsudoko** [comment]
Doesn't work out of the box.

```
~ $ anki
Traceback (most recent call last):
  File "/usr/bin/anki", line 3, in <module>
    import aqt
ModuleNotFoundError: No module named 'aqt'
~ $ PYTHONPATH=/usr/share/anki anki
Traceback (most recent call last):
  File "/usr/bin/anki", line 3, in <module>
    import aqt
  File "/usr/share/anki/aqt/__init__.py", line 14, in <module>
    from aqt.qt import *
  File "/usr/share/anki/aqt/qt.py", line 42, in <module>
    raise Exception("Anki only supports Qt 5.9.x at this time.")
Exception: Anki only supports Qt 5.9.x at this time.
```

**Comment by CameronNemo** [comment]
List of issues with 2.1.4:

- [ ] requires pyaudio module, which is not packaged
- [ ] no longer looks in `/usr/share/anki` for internal modules [(relevant change)](https://github.com/dae/anki/commit/de6ee8819fbdef100e7cd66bcfb9fbcaa1de7110)
- [ ] explicitly checks for Qt 5.9, while 5.10 is packaged in Void

**Comment by CameronNemo** [comment]
See #2733
