### ISSUE TITLE
VSCode: (code-oss:28525): Pango-ERROR **: 13:19:31.389: Harfbuzz version too old (1.4.2)

### ISSUE THREAD

**Issue by Borys64** [void-linux/void-packages#25934]
### System

* xuname:  
 Void 5.8.16_1 i686 GenuineIntel notuptodate rrFFF
* package:  
 vscode-1.21.0_1

### Expected behavior
Starting a session of Visual Studio Code
### Actual behavior
The editor no longer opens after a full system upgrade. I have `harfbuzz` and `pango` installed and updated to the latest versions available - to no avail. I have also tried removing the package completely and reinstalling it multiple times. 
```BASH
$ code-oss --verbose
node[28515]: pthread_create: Invalid argument
(code-oss:28525): Pango-ERROR **: 13:19:31.389: Harfbuzz version too old (1.4.2)
```
### Steps to reproduce the behavior
Use `vscode-1.21.0_1` on i686 architecture.

**Comment by Borys64** [comment]
Same issue occurs when `atom-1.26.1_1` is used. I've also tried to reinstall `pango` and `harfbuzz`, but they're a prerequisites of `gtk+3` which might put the system at risk of breakage.

**Comment by ericonr** [comment]
Hmm, you're probably out of luck. The `vscode` template has been moved to using system electron and it's on version 1.50.1, but it's broken for 32bit platforms. You can try to build it locally by removing the broken line, but I don't know what will happen.

I would recommend trying to download it from their official website, perhaps. Chances are it might be broken there as well.

**Comment by ericonr** [comment]
Either way, you could try updating the system as well. One of the `notuptodate` packages might be relevant.

**Comment by Borys64** [comment]
Okay, thank you for your help, I'll look into building it myself.
