### ISSUE TITLE
transmission depends on qt5 on aarch64-musl, but not on x86_64-glibc

### ISSUE THREAD

**Issue by PaperMountainStudio** [void-linux/void-packages#25962]
### System

* xuname:  
  *Void 5.4.59_1 aarch64-musl Unknown notuptodate rDDDDDFF*
* package:  
  *transmission-3.00_3*

### Expected behavior
ran on x86_64-glibc, but I would expect similar output on aarch64-musl
```
> xbps-query -Rx transmission
glibc>=2.29_1
zlib>=1.2.3_1
libssl48>=3.1.1_1
libcrypto46>=3.1.1_1
libcurl>=7.19_1
libevent>=2.1.11_1
```
### Actual behavior
dependencies on aarch64-musl:
```
> xbps-query -Rx transmission
zlib>=1.2.3_1
libssl48>=3.1.1_1
libcrypto46>=3.1.1_1
libcurl>=7.19_1
libevent>=2.1.11_1
musl>=1.1.21_1
qt5-widgets>=5.15.0_1
qt5-network>=5.15.0_1
qt5-dbus>=5.15.0_1
qt5-gui>=5.15.0_1
qt5-core>=5.15.0_1
libstdc++>=4.4.0_1
libgcc>=4.4.0_1
```
### Steps to reproduce the behavior
`xbps-query -Rx transmission` on aarch64-musl

**Comment by ahesford** [comment]
Good catch.
