### ISSUE TITLE
Update request: Terminator v1.91

### ISSUE THREAD

**Issue by paoloschi** [void-linux/void-packages#2599]
we have 
```
$ xbps-query terminator
[...]
build-date: 2016-11-26 08:16 UTC
homepage: http://gnometerminator.blogspot.de/
pkgver: terminator-1.0_2
short_desc: Tiling terminal emulator application
[...]
```
at [homepage](http://gnometerminator.blogspot.de/) version 1.91 appears as the most recently released (on 26th February 2017)

**Comment by maxice8** [comment]
Those are release candidates for 2.0

**Comment by paoloschi** [comment]
ah... thank you, I didn't get that.
sorry for the noise...

**Comment by paoloschi** [comment]
...but isn't it strange then that the 'ultra conservative' _current stable_ __Debian stretch__ is already at v1.90?
https://packages.debian.org/stretch/terminator

I'm not going to insist for a Void update, just curious to better understand Void directives....
Personally, I've manually unpacked in /opt the 1.91 that I can use without installation: many bugs that I endured in v1.0 have been fixed.....

**Comment by maxice8** [comment]
ok, if someone makes a PR notify me and i will merge it.

I can work at this in a later time.
