### ISSUE TITLE
Cannot compile cmake with `-N` option

### ISSUE THREAD

**Issue by RossComputerGuy** [void-linux/void-packages#26032]
### System

* xuname:  `Void 5.8.16_1 x86_64 AuthenticAMD uptodate rrrrmmnFFFFF`
* package:  `cmake-3.18.2_2`

### Expected behavior
CMake should be able to compile without relying on itself

### Actual behavior
`xbps-src` reports a cyclical dependency error between cmake and cmake.

### Steps to reproduce the behavior
`./xbps-src -N -j 16 pkg cmake`

**Note**: I'm compiling cmake with `-N` for the OS I'm building that is based on Void Linux.

**Comment by sgn** [comment]
On 2020-10-31 15:49:31-0700, Tristan Ross <notifications@github.com> wrote:
> 
> ### System
> 
> * xuname:  `Void 5.8.16_1 x86_64 AuthenticAMD uptodate rrrrmmnFFFFF`
> * package:  `cmake-3.18.2_2`
> 
> ### Expected behavior
> CMake should be able to compile without relying on itself
> 
> ### Actual behavior
> `xbps-src` reports a cyclical dependency error between cmake and cmake.
> 
> ### Steps to reproduce the behavior
> `./xbps-src -N -j 16 pkg cmake`
> 
> **Note**: I'm compiling cmake with `-N` for the OS I'm building that is based on Void Linux.

Please upload your build log.
CMake shouldn't require cmake to build.
It requires cmake-bootstrap instead.

-- 
Danh

**Comment by sgn** [comment]
Anyway, when you're starting a fork of Void Linux, you should start the bootstrap process first ;)

**Comment by RossComputerGuy** [comment]
I did run `./xbps-src binary-bootstrap` first. Then I removed everything from `srcpkgs` so I can add in what I only need.

**Comment by ericonr** [comment]
You should start with `./xbps-src bootstrap` if you want to start from zero.

**Comment by sgn** [comment]
On 2020-10-31 16:47:47-0700, Tristan Ross <notifications@github.com> wrote:
> I did run `./xbps-src binary-bootstrap` first.

If it's binary-bootstrap, you'll use VoidLinux's for bootstrap
compiler. Which is another trusting trust problems ;)

> Then I removed everything from `srcpkgs` so I can add in what I only need.

I guess you started doing that long time ago.

Could you check if your "common/environment/build-style/cmake.sh"
matches with ours?

We've changed not long ago because bootstrapping ccache requires
cmake, too.

-- 
Danh

**Comment by RossComputerGuy** [comment]
That script is out of date on mine, but with `xbps-src bootstrap` I'm getting a problem with glibc:
```
=> glibc-2.30_1: installing target dependencies: kernel-libc-headers-4.19.0_2 ...
=> glibc-2.30_1: skipping check (XBPS_CHECK_PKGS is disabled) ...
=> glibc-devel-2.30_1: running pre-install hook: 00-lib32 ...
=> glibc-devel-2.30_1: running pre-install hook: 02-script-wrapper ...
=> glibc-devel-2.30_1: running pre-install hook: 98-fixup-gir-path ...
=> glibc-devel-2.30_1: running pkg_install ...
mv: cannot stat '/home/ross/ExpidusOS/void-packages/masterdir/destdir//glibc-2.30/usr/include': No such file or directory
=> ERROR: glibc-devel-2.30_1: pkg_install: 'mv ${_destdir}/$files ${_pkgdestdir}/${_targetdir}' exited with 1
=> ERROR:   in _vmove() at common/environment/setup/install.sh:232
=> ERROR:   in _noglob_helper() at common/environment/setup/install.sh:12
=> ERROR:   in pkg_install() at srcpkgs/glibc-devel/template:195
```

**Comment by sgn** [comment]
That's weird, we're always doing a full bootstrap from zero (in developers' machine) when updating any packages in base-chroot. Can you remove everything and try again? (Since you removed everything and add only what you need, your maybe broken and unsupported ;) )

**Comment by RossComputerGuy** [comment]
I removed everything and added only what `xbps-src bootstrap` said it needed and this message now shows up for `glibc`:
```
=> Transformed bash script: /home/ross/ExpidusOS/void-packages/masterdir/destdir//glibc-2.30/usr/bin/ldd.
=> glibc-devel-2.30_1: running pre-install hook: 00-lib32 ...
=> glibc-devel-2.30_1: running pre-install hook: 02-script-wrapper ...
=> glibc-devel-2.30_1: running pre-install hook: 98-fixup-gir-path ...
=> glibc-devel-2.30_1: running pkg_install ...
=> glibc-devel-2.30_1: running post-install hook: 00-compress-info-files ...
   Compressing info file: /usr/share/info/libc.info-2...
   Compressing info file: /usr/share/info/libc.info-15...
   Compressing info file: /usr/share/info/libc.info-12...
   Compressing info file: /usr/share/info/libc.info-13...
   Compressing info file: /usr/share/info/libc.info-8...
   Compressing info file: /usr/share/info/libc.info-6...
   Compressing info file: /usr/share/info/libc.info-14...
   Compressing info file: /usr/share/info/libc.info-11...
   Compressing info file: /usr/share/info/libc.info-3...
   Compressing info file: /usr/share/info/libc.info-10...
   Compressing info file: /usr/share/info/libc.info-17...
   Compressing info file: /usr/share/info/libc.info...
   Compressing info file: /usr/share/info/libc.info-1...
   Compressing info file: /usr/share/info/libc.info-4...
   Compressing info file: /usr/share/info/libc.info-7...
   Compressing info file: /usr/share/info/libc.info-5...
   Compressing info file: /usr/share/info/libc.info-9...
   Compressing info file: /usr/share/info/libc.info-16...
=> glibc-devel-2.30_1: running post-install hook: 00-lib32 ...
=> glibc-devel-2.30_1: running post-install hook: 00-uncompress-manpages ...
=> glibc-devel-2.30_1: running post-install hook: 01-remove-localized-manpages ...
=> glibc-devel-2.30_1: running post-install hook: 01-remove-misc ...
=> glibc-devel-2.30_1: running post-install hook: 02-remove-libtool-archives ...
=> glibc-devel-2.30_1: running post-install hook: 02-remove-perl-files ...
=> glibc-devel-2.30_1: running post-install hook: 02-remove-python-bytecode-files ...
=> glibc-devel-2.30_1: running post-install hook: 03-remove-empty-dirs ...
=> glibc-devel-2.30_1: running post-install hook: 04-create-xbps-metadata-scripts ...
=> ERROR: glibc-devel: unknown trigger info-files, aborting!
```

**Comment by sgn** [comment]
> => ERROR: glibc-devel: unknown trigger info-files, aborting!

Check your `srcpkgs/xbps-triggers/files` ;)

Anyway, from now on, each questions will NOT be answered without payment ;)

**Comment by RossComputerGuy** [comment]
Okay adding the `xbps-triggers` fixes that error but the previous error is back.

**Comment by sgn** [comment]
> Okay adding the `xbps-triggers` fixes that error but the previous error is back.

Remove everything and try again. 100 bucks accounted.

**Comment by q66** [comment]
we don't provide support for self-inflicted errors in random forks, sorry

**Comment by RossComputerGuy** [comment]
@sgn I already did that and got that error

@q66 Is there someone where I can ask for help when I get errors for making a Void Linux based distro?

**Comment by RossComputerGuy** [comment]
I got glibc to compile now.

**Comment by sgn** [comment]
> I got glibc to compile now.

Congrats, you still owe me 100 bucks ;)

**Comment by RossComputerGuy** [comment]
```
=> ccache-4.0_1: building [cmake] (dependency of base-chroot) for x86_64...
   [host] cmake-bootstrap-3.18.2_1: found (/home/ross/ExpidusOS/void-packages/hostdir/binpkgs)
   [target] libzstd-devel-1.4.5_1: found (/home/ross/ExpidusOS/void-packages/hostdir/binpkgs)
   [target] zlib-devel-1.2.11_3: found (/home/ross/ExpidusOS/void-packages/hostdir/binpkgs)
=> ccache-4.0_1: installing host dependencies: cmake-bootstrap-3.18.2_1 ...
=> ccache-4.0_1: installing target dependencies: libzstd-devel-1.4.5_1 zlib-devel-1.2.11_3 ...
=> ccache-4.0_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> ccache-4.0_1: running pre-configure hook: 01-override-config ...
=> ccache-4.0_1: running pre-configure hook: 02-script-wrapper ...
=> ccache-4.0_1: running do_configure ...
-- Ccache version: 4.0
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  please install libzstd or use -DZSTD_FROM_INTERNET=ON (missing:
  ZSTD_INCLUDE_DIR ZSTD_LIBRARY) (Required is at least version "1.1.2")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findzstd.cmake:48 (find_package_handle_standard_args)
  CMakeLists.txt:57 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ross/ExpidusOS/void-packages/masterdir/builddir/ccache-4.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/ross/ExpidusOS/void-packages/masterdir/builddir/ccache-4.0/build/CMakeFiles/CMakeError.log".
=> ERROR: ccache-4.0_1: do_configure: 'CFLAGS="${CFLAGS/ -pipe / }" CXXFLAGS="${CXXFLAGS/ -pipe / }" cmake ${cmake_args} ${configure_args} $(echo ${cmake_builddir}|sed 			-e 's|[^/]$|/|' -e 's|[^/]*||g' -e 's|/|../|g')' exited with 1
=> ERROR:   in do_configure() at common/build-style/cmake.sh:6
```
And now libzstd isn't found for ccache. I've pulled the latest commits and merged them in to be sure.

**Comment by RossComputerGuy** [comment]
```
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  please install libzstd or use -DZSTD_FROM_INTERNET=ON (missing:
  ZSTD_INCLUDE_DIR ZSTD_LIBRARY) (Required is at least version "1.1.2")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findzstd.cmake:48 (find_package_handle_standard_args)
  CMakeLists.txt:57 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ross/void-packages/masterdir/builddir/ccache-4.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/ross/void-packages/masterdir/builddir/ccache-4.0/build/CMakeFiles/CMakeError.log".
=> ERROR: ccache-4.0_1: do_configure: 'CFLAGS="${CFLAGS/ -pipe / }" CXXFLAGS="${CXXFLAGS/ -pipe / }" cmake ${cmake_args} ${configure_args} $(echo ${cmake_builddir}|sed 			-e 's|[^/]$|/|' -e 's|[^/]*||g' -e 's|/|../|g')' exited with 1
=> ERROR:   in do_configure() at common/build-style/cmake.sh:62
```
Okay, this error happens with upstream.

**Comment by sgn** [comment]
The ccache error is valid bug. https://github.com/void-linux/void-packages/pull/26039

**Comment by RossComputerGuy** [comment]
Alright, I merged in the fix for my repo but now I'm getting a utf8 error with ca-certificates:
```
=> ca-certificates-20200601_2: running do-pkg hook: 00-gen-pkg ...
=> Creating ca-certificates-20200601_2.x86_64.xbps for repository /home/ross/ExpidusOS/void-packages/hostdir/binpkgs ...
xbps-create: ERROR: cannot write ./usr/share/ca-certificates/mozilla/NetLock_Arany_=Class_Gold=_Főtanúsítvány.crt to archive: Can't translate pathname './usr/share/ca-certificates/mozilla/NetLock_Arany_=Class_Gold=_Főtanúsítvány.crt' to UTF-8
=> ERROR: Failed to created binary package: ca-certificates-20200601_2.x86_64.xbps!
```
I checked the pull requests and other issues, seems like nobody else has reported it. Yet again, this is an upstream issue:
```
=> ca-certificates-20200601_2: running pre-pkg hook: 999-collected-rdeps ...
   libressl>=2.2.4_2 run-parts>=0
=> ca-certificates-20200601_2: running do-pkg hook: 00-gen-pkg ...
=> Creating ca-certificates-20200601_2.x86_64.xbps for repository /home/ross/void-packages/hostdir/binpkgs ...
xbps-create: ERROR: cannot write ./usr/share/ca-certificates/mozilla/NetLock_Arany_=Class_Gold=_Főtanúsítvány.crt to archive: Can't translate pathname './usr/share/ca-certificates/mozilla/NetLock_Arany_=Class_Gold=_Főtanúsítvány.crt' to UTF-8
=> ERROR: Failed to created binary package: ca-certificates-20200601_2.x86_64.xbps!
```

**Comment by sgn** [comment]
On 2020-11-01 07:30:20-0800, Tristan Ross <notifications@github.com> wrote:
> Alright, I merged in the fix for my repo but now I'm getting a utf8 error with ca-certificates:
> ```
> => ca-certificates-20200601_2: running do-pkg hook: 00-gen-pkg ...
> => Creating ca-certificates-20200601_2.x86_64.xbps for repository /home/ross/ExpidusOS/void-packages/hostdir/binpkgs ...
> xbps-create: ERROR: cannot write ./usr/share/ca-certificates/mozilla/NetLock_Arany_=Class_Gold=_Főtanúsítvány.crt to archive: Can't translate pathname './usr/share/ca-certificates/mozilla/NetLock_Arany_=Class_Gold=_Főtanúsítvány.crt' to UTF-8
> => ERROR: Failed to created binary package: ca-certificates-20200601_2.x86_64.xbps!
> ```
> I checked the pull requests and other issues, seems like nobody else has reported it. Yet again, this is an upstream issue:
> ```
> => ca-certificates-20200601_2: running pre-pkg hook: 999-collected-rdeps ...
>    libressl>=2.2.4_2 run-parts>=0
> => ca-certificates-20200601_2: running do-pkg hook: 00-gen-pkg ...
> => Creating ca-certificates-20200601_2.x86_64.xbps for repository /home/ross/void-packages/hostdir/binpkgs ...
> xbps-create: ERROR: cannot write ./usr/share/ca-certificates/mozilla/NetLock_Arany_=Class_Gold=_Főtanúsítvány.crt to archive: Can't translate pathname './usr/share/ca-certificates/mozilla/NetLock_Arany_=Class_Gold=_Főtanúsítvány.crt' to UTF-8
> => ERROR: Failed to created binary package: ca-certificates-20200601_2.x86_64.xbps!
> ```

Please report your filesystem, and locale?

Anyway, I think we set xbps-src with LC_ALL=C.UTF-8 and en_US.UTF-8

-- 
Danh

**Comment by RossComputerGuy** [comment]
I am using ext4 and I'm using the same locale but it seems the installer didn't export `LANG` or `LC_ALL`.

**Comment by RossComputerGuy** [comment]
Exporting `LANG` fixed it, and `xbps-src  bootstrap` finished with no errors now.

**Comment by sgn** [comment]
> Exporting `LANG` fixed it,

We still need to figure out why `LANG` wasn't set in `bootstrap`.

> and `xbps-src bootstrap` finished with no errors now.

Congrats on finishing `stage0`, you'll need to do at least 2 more full rebuild for a usable bootstrap ;)
https://github.com/void-linux/void-packages/issues/25604#issuecomment-709349377

**Comment by RossComputerGuy** [comment]
That sounds like fun :smile:
