### ISSUE TITLE
Package Request: cinelerra-gg

### ISSUE THREAD

**Issue by RibalGZ** [void-linux/void-packages#2604]
The Good Guy branch seems to be the best one:
https://cinelerra-cv.org/download_gg.php

**Comment by abenson** [comment]
I'll take a look at it. Seems like a nice project.

**Comment by kojicomics** [comment]
They've moved the project.
See: https://www.cinelerra-gg.org/downloads/

**Comment by Chocimier** [comment]
Tracking at #24084
