### ISSUE TITLE
[RFC] Drop mysql in favor of only having mariadb

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#26051]
Our current MySQL version is ancient, nobody cares about it and it probably has a ton of CVEs,
but we link like everything against libmysqlclient instead of libmariadbclient.
Mariadb, while not updated with every release, is maintained far better than our MySQL packatge.

**Comment by ericonr** [comment]
Is mariadb sufficiently source compatible? Or would we need new patches for Qt and others?

**Comment by Johnnynator** [comment]
> Is mariadb sufficiently source compatible? Or would we need new patches for Qt and others?

Mariadb does it's best at keeping it compatible and all packages should work fine ootb. Quite a few distros don't even ship MySQL and only mariadb (e.g. Arch and Debian).

**Comment by leahneukirchen** [comment]
Go for it.
