### ISSUE TITLE
drawterm: canlock errors (posix-generic/tas.c) on x86_64

### ISSUE THREAD

**Issue by ashpooljh** [void-linux/void-packages#26109]
### System

* xuname: `Void 5.8.17_1 x86_64 GenuineIntel uptodate hold rmFFFFFFFFFFFF`
* package: `drawterm-0.0.20200619_1`

### Expected behavior

`drawterm` works normally. No error messages (e.g. `canlock: corrupted 0x2`) are printed. 

### Actual behavior

Upon authenticating on a CPU server the background of the terminal window starts filling up with error messages. All the messages are of the same type:
```
canlock: corrupted 0xXX
```
where `XX` is replaced by a different hexadecimal number each time. An example of this behavior can be observed on the attached screenshot:

![image](https://user-images.githubusercontent.com/14354287/98026286-f1866880-1e1b-11eb-8f5c-93085199fada.png)

These messages can appear when any input is sent to the terminal (e.g. typing commands, moving and creating windows, etc). It is barely possible to use the terminal without interruption, since the messages will obstruct any windows created.

### Steps to reproduce the behavior

* Run `drawterm` as built by the Void Linux project on x86_64 arch
* Authenticate on a 9front CPU server
* Run `rio` (done from `lib/profile` in my case)
* Do pretty much anything

**Comment by ashpooljh** [comment]
@Gottox @q66 please take a look.

**Comment by q66** [comment]
should be fixed now, please test just in case

**Comment by ashpooljh** [comment]
Fixed, thanks
