### ISSUE TITLE
OpenVPN cannot connect with server using AES-256-CBC cipher

### ISSUE THREAD

**Issue by reedts** [void-linux/void-packages#26100]
### System

* xuname:  
  *Void 5.8.18_1 x86_64 GenuineIntel uptodate hold rrrmDFFFFF*
* package:
  *openvpn-2.4.9_3*

### Expected behavior
OpenVPN should be able to connect to server using cipher AES-256-CBC
### Actual behavior
OpenVPN fails with error:
```
Tue Nov  3 10:21:38 2020 us=722261 Cipher algorithm 'aes-256-cbc' not found
Tue Nov  3 10:21:38 2020 us=722275 Cipher aes-256-cbc not supported
Tue Nov  3 10:21:38 2020 us=722282 Exiting due to fatal error
```

### Steps to reproduce the behavior
Use `cipher aes-256-cbc` in your `config.ovpn` and try to start `openvpn --config config.ovpn`

Full log of `openvpn --verb 4 --config /etc/openvpn/config.ovpn`:
[ovpn.txt](https://github.com/void-linux/void-packages/files/5480342/ovpn.txt)

**Comment by cryptorick** [comment]
I'm seeing this too.  Thanks for opening this issue, @reedts
