### ISSUE TITLE
New Travis pricing, are we affected?

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#26120]
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).

> You will not need to change your build definitions when you are pointed to the new plan

>When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.

>We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment.

**Comment by ericonr** [comment]
We are affected, as we use about 2000 minutes per day; the free trial is way below what we need. A move to GitHub Actions is being studied, as seen in #26095 .

**Comment by Anachron** [comment]
So Github allows us to have as long and as many builds as we need? Or how bad is this?

**Comment by uzr123x** [comment]
Have you studied not being on GitHub at all? C;

**Comment by Anachron** [comment]
So what free build system and development platform would you suggest?

**Comment by ericonr** [comment]
> So Github allows us to have as long and as many builds as we need? Or how bad is this?

Seems so. Not sure there is a catch.

**Comment by anjandev** [comment]
@Anachron sourcehut has very good CI system. builds.sr.ht. Even if you keep the rest of void development (issues, pull requests, git repo) on github, you can use dispatch.sr.ht to build github pull requests and github commits on builds.sr.ht.

See: https://man.sr.ht/dispatch.sr.ht/

**Comment by Duncaen** [comment]
We would 100% crush sourcehut with our PRs.

**Comment by anjandev** [comment]
Ya definitely...I would ask Drew before doing it. He may or may not be up for it.

**Comment by Duncaen** [comment]
Its just not an option, we require build times that is worth hundreds of dollars of cloud services, there is no chance their infrastructure would be ready for this or they would be able to provide as much free resources as we got from travis or going to get from github.

**Comment by ericonr** [comment]
This is no longer relevant.
