### ISSUE TITLE
Package Request: meli

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#26132]
https://git.meli.delivery/meli/meli

> BSD/Linux terminal email client with support for multiple accounts and Maildir / mbox / notmuch / IMAP / JMAP.

License: [GPL 3.0](https://git.meli.delivery/meli/meli/src/branch/master/COPYING)

It's a rust/cargo program.

**Comment by Logarithmus** [comment]
See https://github.com/void-linux/void-packages/pull/26551

**Comment by ericonr** [comment]
Being closed as outlined in https://github.com/void-linux/void-packages/pull/26551#issuecomment-763946603
