### ISSUE TITLE
wlogout doesn't work with runit right now

### ISSUE THREAD

**Issue by rupansh** [void-linux/void-packages#26146]
### System

* xuname:  
  *Void 5.8.18_1 x86_64 GenuineIntel uptodate rFFFF*
* package:  
  *affected package(s) including the version*: ``wlogout-1.1.1_1``

### Expected behavior
Shutdown and reboot should work

### Actual behavior
Shutdown and reboot expects systemctl
`sh: 1: systemctl: not found`
and thus doesnt work

### Steps to reproduce the behavior
`wlogout`
click reboot/shutdown/hibernate

**Comment by rupansh** [comment]
Possible fix: Ship with our own default config that uses runit instead

**Comment by ericonr** [comment]
Not exactly ideal, because the runit solutions would require `sudo` or `doas` (or even `pkexec`)  to gain privileges, and that's very varied. I would suggest switching to depending on `elogind` and using `loginctl <action>`.

**Comment by rupansh** [comment]
> Not exactly ideal, because the runit solutions would require `sudo` or `doas` (or even `pkexec`) to gain privileges, and that's very varied. I would suggest switching to depending on `elogind` and using `loginctl <action>`.

Well a unified solution for all users would be nice. Ideally we should avoid adding dependencies that arent used by all wayland users

**Comment by ericonr** [comment]
That's true.

@travankor thoughts?

**Comment by travankor** [comment]
How does this sound?

1) Switch the files in `/etc/` to `loginctl <action>` 
2) Don't add elogind as a dependency since xbps does not handle optional dependencies

>Expected behavior
Shutdown and reboot should work

By the way, you can add custom commands to your dotfiles `~/.config/wlogout` as per the manpage.

**Comment by rupansh** [comment]
> How does this sound?
> 
>     1. Switch the files in `/etc/` to `loginctl <action>`
> 
>     2. Don't add elogind as a dependency since xbps does not handle optional dependencies
Not really ideal but yeah i couldnt come up with anything else. It should print a warning about it too

> > Expected behavior
> > Shutdown and reboot should work
> 
> By the way, you can add custom commands to your dotfiles `~/.config/wlogout` as per the manpage.
Thanks

**Comment by ericonr** [comment]
@travankor ping? I like your suggestion.
