### ISSUE TITLE
Perl error 

### ISSUE THREAD

**Issue by qorg11** [void-linux/void-packages#26192]
After updating perl to 5.32 I get this error with almost every perl program (even cpan):

```
> lainsafecli perl-5.30.3_2.x86_64.xbps
Zlib.c: loadable library and perl binaries are mismatched (got handshake key 0xcd00080, needed 0xed00080)
```
Tried downgrading to perl 5.30 but i couldn't since much packages depends on perl 5.32 and i don't want to break anything

**Comment by ericonr** [comment]
I don't know anything about the ecosystem, but that looks like something that was compiled for an older Perl.

**Comment by ericonr** [comment]
Please include the information from the issue report template, it helps with diagnosing this.

**Comment by qorg11** [comment]
So how can i fix that

**Comment by qorg11** [comment]
### System

* xuname:  
Void 5.8.18_1 x86_64 GenuineIntel uptodate rrmFF

* package:  
perl-5.32.0_1

### Expected behavior
Run the software normally
### Actual behavior
Gives an error like this: `Zlib.c: loadable library and perl binaries are mismatched (got handshake key 0xcd00080, needed 0xed00080)
`
### Steps to reproduce the behavior

Run any perl program that requires Zlib

**Comment by ericonr** [comment]
hm, I didn't manage to reproduce... I can run `cpan` just fine.

Can you try to remove/rename `~/.cpan` and see what happens?

**Comment by qorg11** [comment]
I removed `~/.cpan` and I still get that error  
I can run `cpan` without errors, but cannot use it (To install modules)

**Comment by ericonr** [comment]
`install CPAN` inside `cpan` also worked.

Do note I am very lost on Perl stuff. If you can give me an explicit command to try out I might be able to better help you.

**Comment by qorg11** [comment]
Nope, still got that error...

**Comment by zdykstra** [comment]
If `lainsafecli` wasn't installed by xbps, you'll need to rebuild and reinstall that program. Can you explain how you installed it?

**Comment by qorg11** [comment]
It is my own piece of software, I installed it by *literally* installing it dependences (with xbps) and copying it to /bin. But also packages installed with xbps (cpan and straw-viewer) give the same error

**Comment by q66** [comment]
run `xbps-pkgdb -a`, check for any errors

**Comment by zdykstra** [comment]
What's your include path?

`perl -e "print qq(@INC)"` 

You have an older library in one of your paths.

**Comment by qorg11** [comment]
`/home/qorg/perl5/lib/perl5 /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl`

the ~/perl5 directory does not exist

**Comment by zdykstra** [comment]
What do you see when you execute: `perl -MLWP::UserAgent -e'print $_ . " => " . $INC{$_} . "\n" for keys %INC'` ? You most likely have a library that was manually installed/built against 5.30, which is now broken with 5.32 installed.

**Comment by qorg11** [comment]
```
LWP/UserAgent.pm => /usr/share/perl5/vendor_perl/LWP/UserAgent.pm
HTTP/Status.pm => /usr/share/perl5/vendor_perl/HTTP/Status.pm
Time/Local.pm => /usr/share/perl5/core_perl/Time/Local.pm
HTTP/Response.pm => /usr/share/perl5/vendor_perl/HTTP/Response.pm
Carp.pm => /usr/share/perl5/core_perl/Carp.pm
HTTP/Date.pm => /usr/share/perl5/vendor_perl/HTTP/Date.pm
warnings.pm => /usr/share/perl5/core_perl/warnings.pm
overload.pm => /usr/share/perl5/core_perl/overload.pm
LWP/Protocol.pm => /usr/share/perl5/vendor_perl/LWP/Protocol.pm
HTTP/Headers.pm => /usr/share/perl5/vendor_perl/HTTP/Headers.pm
constant.pm => /usr/share/perl5/core_perl/constant.pm
overloading.pm => /usr/share/perl5/core_perl/overloading.pm
Exporter.pm => /usr/share/perl5/core_perl/Exporter.pm
HTTP/Message.pm => /usr/share/perl5/vendor_perl/HTTP/Message.pm
URI.pm => /usr/share/perl5/vendor_perl/URI.pm
LWP/MemberMixin.pm => /usr/share/perl5/vendor_perl/LWP/MemberMixin.pm
Sub/Util.pm => /usr/lib/perl5/core_perl/Sub/Util.pm
base.pm => /usr/share/perl5/core_perl/base.pm
List/Util.pm => /usr/lib/perl5/core_perl/List/Util.pm
LWP.pm => /usr/share/perl5/vendor_perl/LWP.pm
HTTP/Request.pm => /usr/share/perl5/vendor_perl/HTTP/Request.pm
strict.pm => /usr/share/perl5/core_perl/strict.pm
Scalar/Util.pm => /usr/lib/perl5/core_perl/Scalar/Util.pm
XSLoader.pm => /usr/share/perl5/core_perl/XSLoader.pm
URI/Escape.pm => /usr/share/perl5/vendor_perl/URI/Escape.pm
warnings/register.pm => /usr/share/perl5/core_perl/warnings/register.pm
Try/Tiny.pm => /usr/share/perl5/vendor_perl/Try/Tiny.pm
parent.pm => /usr/share/perl5/core_perl/parent.pm
```

**Comment by zdykstra** [comment]
Since `lainsafecli` only depends on LWP::UserAgent, I've installed that on an x86_64 machine. I'm able to run the program without any issues, so this looks to be localized to your machine. The default include path should also have '.' in it. Are you sure you don't have a custom library installed somewhere in $CWD when invoking `lainsafecli`, or in ~/perl5 ?

**Comment by qorg11** [comment]
I've tried to run `lainsafecli` as a different user and directories. still get the error. @INC has .  but i don't think i have a custom library in my $CWD. ~/perl5 does not exist

**Comment by zdykstra** [comment]
Okay, lets try this:

`perl -e 'for $entry (@INC) { print "$entry\n" }' | xargs -n1 --replace=blah find blah -name Zlib.so -exec md5sum {} \;`

With `perl-LWP` installed on a current x86_64 machine, I have a single Zlib.so in my `@INC`.

```
bash-5.0# perl -e 'for $entry (@INC) { print "$entry\n" }' | xargs -n1 --replace=blah find blah -name Zlib.so -exec md5sum {} \;
34e5b109b425d729cab67bd5d7dc6657  /usr/lib/perl5/core_perl/auto/Compress/Raw/Zlib/Zlib.so
```

**Comment by qorg11** [comment]
I got this:
```
perl -e 'for $entry (@INC) { print "$entry\n" }' | xargs -n1 --replace=blah find blah -name Zlib.so -exec md5sum {} \;
d3834150c498896e146887640b0217b5  /usr/lib/perl5/site_perl/auto/Compress/Raw/Zlib/Zlib.so
34e5b109b425d729cab67bd5d7dc6657  /usr/lib/perl5/core_perl/auto/Compress/Raw/Zlib/Zlib.so
```
So I copied `/usr/lib/perl5/core_perl/auto/Compress/Raw/Zlib/Zlib.so` to ` /usr/lib/perl5/site_perl/auto/Compress/Raw/Zlib/Zlib.so`

That fixed the issue. Thanks!

**Comment by zdykstra** [comment]
The modules installed in ` /usr/lib/perl5/site_perl/auto` were put there likely by cpan. They should be removed, allowing the system modules in ` /usr/lib/perl5/core_perl/auto` to take win. This way you won't hit the issue again on a system perl upgrade.
