### ISSUE TITLE
ocaml-lablgtk2 is missing lablgladecc2

### ISSUE THREAD

**Issue by FoxySeta** [void-linux/void-packages#26235]
### System
* xuname:  
  *Void 5.8.18_1 x86_64 AuthenticAMD uptodate rrrmFFFF*
* package: 
  *ocaml-lablgtk2-2.18.10_2
### Expected behavior
`lablgladecc2` gets executed correctly.
### Actual behavior
`bash: lablgladecc2: command not found`
### Steps to reproduce the behavior
`$ lablgladecc2`

**Comment by ericonr** [comment]
@raedwulf any idea?
