### ISSUE TITLE
Linux kernel 5.18: Enable CONFIG_KEYBOARD_APPLESPI as module

### ISSUE THREAD

**Issue by thenktor** [void-linux/void-packages#26241]
Recent Void Linux live cd with kernel 5.8.18 is missing support for Apple hardware. The kernel config says `# CONFIG_KEYBOARD_APPLESPI is not set` but it is needed to access keyboard and trackpad in Apple MacBooks built 2015 and after. 

See also: https://cateee.net/lkddb/web-lkddb/KEYBOARD_APPLESPI.html and https://github.com/roadrunner2/macbook12-spi-driver

**Comment by ericonr** [comment]
Do you know if it works fine as a separate module?

**Comment by thenktor** [comment]
Yes, at least in KDE Neon live system:
```
neon@neon:/boot$ grep -i apple config-5.4.0-52-generic 
CONFIG_APPLE_PROPERTIES=y
CONFIG_DEV_APPLETALK=m
CONFIG_KEYBOARD_APPLESPI=m
CONFIG_MOUSE_APPLETOUCH=m
CONFIG_SENSORS_APPLESMC=m
CONFIG_BACKLIGHT_APPLE=m
CONFIG_HID_APPLE=m
CONFIG_HID_APPLEIR=m
CONFIG_USB_APPLEDISPLAY=m
CONFIG_APPLE_GMUX=m
```
