### ISSUE TITLE
Raspberry Pi: unable to make kernel 5.x scripts

### ISSUE THREAD

**Issue by ILadis** [void-linux/void-packages#26257]
### System

* xuname:  
  `Void 4.19.127_3 armv7l Unknown notuptodate hold rFFF`
* package:  
  `rpi-kernel-headers-5.4.68_1`

### Expected behavior
Upon running `make scripts` from inside `/usr/src/rpi-kernel-headers-5.*` all kernel scripts should be compiled.

Output of `make scripts`:

```
  HOSTCC  scripts/dtc/flattree.o
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/dtc/data.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/dtc/util.o
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTLD  scripts/dtc/dtc
  HOSTCC  scripts/genksyms/genksyms.o
  HOSTCC  scripts/genksyms/parse.tab.o
  HOSTCC  scripts/genksyms/lex.lex.o
  HOSTLD  scripts/genksyms/genksyms
  HOSTCC  scripts/recordmcount
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/pnmtologo
  HOSTCC  scripts/conmakehash
  HOSTCC  scripts/sortextable
  HOSTCC  scripts/asn1_compiler
  HOSTCC  scripts/extract-cert
```

### Actual behavior
Some kernel scripts do not get compiled. No errors occur when running `make scripts` but when I try to compile a kernel module/driver from source it complains about a missing kernel script:

```
Building modules, stage 2.
  MODPOST 1 modules
/bin/sh: 1: scripts/mod/modpost: not found
make[2]: *** [scripts/Makefile.modpost:94: __modpost] Error 127
```

If I then try to explicitly run `make` in `/usr/src/rpi-kernel-headers-5.*/scripts/mod` I get the following error:

```
make: *** No rule to make target '/devicetable-offsets.s', needed by '/devicetable-offsets.h'.  Stop.
```

I do not know if that is the only script that can not be compiled. There may be more missing.

### Steps to reproduce the behavior
Run `cd /usr/src/rpi-kernel-headers-5.* && make scripts` and check if `scripts/mod/modpost` gets compiled.

In order to successfully compile the kernel scripts I had to also install the following development tools:  
`make`, `flex`, `gcc`, `libressl-devel`

**Comment by Anachron** [comment]
Why don't you use xbps-src for compiling packages?

**Comment by ILadis** [comment]
I dont' want to compile a package but rather build another/external kernel module for the current available kernel. I'd compare that with having to install a `devel` package in order to include its header files an compile it against the available system library.

I'd also like to mention that I could compile the kernel scripts with the `rpi-kernel-headers-4.19.127` just fine.

**Comment by fosslinux** [comment]
@Piraty @pbui ?

**Comment by pbui** [comment]
Should have been addressed in: https://github.com/void-linux/void-packages/pull/24846

**Comment by pbui** [comment]
@ILadis Upstream kernel no longer builds `modpost` with the `make scripts` target... so we now have to do `make prepare0`.  The commit referenced above, should have updated `dkms` to do so.

**Comment by Piraty** [comment]
#24846 is merged, please make sure you have `xbps-triggers-0.118_1` and `dkms-2.8.3_3`.

Reopen if the issue persists

**Comment by Piraty** [comment]
ah now i realize what your issue is: building your module manually
take a look here at why modpost is not build with `make scripts` target. (complain upstream :D): https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=60df1aee2aecb53efb4218b4dfdf7d6c80a5a3de

**Comment by ILadis** [comment]
Thanks you all for your support.

Building the target `make prepare0` instead of `make scripts` has solved my issue. Now all required kernel scripts get compiled.
