### ISSUE TITLE
slstatus not being fetched correctly

### ISSUE THREAD

**Issue by platerza** [void-linux/void-packages#2625]
**This is a simple matter of updating the template file for `slstatus`.**

### System

* xuname:  
  `Void 4.18.7_1 x86_64 GenuineIntel uptodate rFF`
* package:  
  `slstatus`

### Expected behavior

`slstatus` should fetch and install via `xbps-src`.

### Actual behavior

`slstatus` fails to retrieve the package tarball.

message reads:
`=> ERROR: slstatus-20180106_1: failed to fetch slstatus-*.tar.gz`

### Steps to reproduce the behavior

1. set up the `xbps-src` environment
`$ git clone https://github.com/void-linux/void-packages`
`$ cd void-packages`
`$ ./xbps-src binary-bootstrap`

2. use `xbps-src` to fetch and build the package
`$ ./xbps-src pkg slstatus`

**Comment by Hoshpak** [comment]
#2399
