### ISSUE TITLE
[fwupd] failed to find module 'platform-integrity'

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#26274]
Fwupd installs module configuration files in /etc/modules-load.d

fwupd-msr.conf
fwupd-platform-integrity.conf

The first module loads, but the second does not.

modprobe: FATAL: Module platform-integrity not found in directory /lib/modules/5.9.6_1

```
xuname
Void 5.9.6_1 x86_64-musl GenuineIntel uptodate hold rrnFFFF
```

**Comment by q66** [comment]
it shouldn't really matter, the module does not exist yet in linux kernel (seems to be under review right now) but having the file there shouldn't break anything

**Comment by dkwo** [comment]
I see, you're probably right.
