### ISSUE TITLE
Linux 4.18 kernel panic

### ISSUE THREAD

**Issue by lbolla** [void-linux/void-packages#2628]
### System

* xuname:  
  Void 4.17.19_1 x86_64 GenuineIntel uptodate rFFF

* package:  
  linux-4.18

### Expected behavior
Kernel starts as expected

### Actual behavior
I get a kernel panic on startup with message:
`Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)`

Starting kernel 4.17.19 works.

I noticed that Grub's `/boot/grub/grub.cfg` is different between 4.17 series and 4.18.
E.g.
```
                echo    'Loading Linux 4.17.19_1 ...'
                linux   /vmlinuz-4.17.19_1 root=/dev/mapper/pool-root ro  loglevel=4 slub_debug=P page_poison=1 rd.auto=1 cryptdevice=/dev/sda2 root=/dev/mapper/pool-root
                echo    'Loading initial ramdisk ...'
                initrd  /initramfs-4.17.19_1.img
```
but
```
                echo    'Loading Linux 4.18.6_1 ...'
                linux   /vmlinuz-4.18.6_1 root=/dev/mapper/pool-root ro single 
        }
```
Note the missing `initrd`  command.
I tried to run `grub-mkconfig` manually and nothing changed.
`/initramfs` files are present in `/boot` for all images.

### Steps to reproduce the behavior
Just `xi -u` the latest kernel.

**Comment by Hoshpak** [comment]
This usually happens when /boot runs out of disk space while generating the initrd. Please check that enough disk space is available and regenerate the initrd with `xbps-reconfigure -f linux4.18`.

**Comment by lbolla** [comment]
Thanks! That seems indeed to be the case. Is there a recommended way to drop obsolete kernel images from `/boot`?

**Comment by Hoshpak** [comment]
Yes, it's the `vkpurge` script that comes in the base-files package. It can either remove specific kernel versions or all obsolete (= not the currently running kernel, not held by an installed linux package) kernels.

**Comment by lbolla** [comment]
Thanks, that did the trick.
