### ISSUE TITLE
Linux 5.9 missing speakup modules that were enabled in 5.8

### ISSUE THREAD

**Issue by joey-commits** [void-linux/void-packages#26319]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  Linux 5.9.6_1
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
When the espeakup package is installed, speech should be available when starting its service.
### Actual behavior
No speech is heard. This is because speakup modules moved out of staging in 5.9 to another area of the kernel  (drivers/accessibility) and this was missed in the Void build.
### Steps to reproduce the behavior

1. Start the computer with espeakup service and notice that no speech is heard.

**Comment by ericonr** [comment]
It seems I missed this, because we had accessibility toggled off in the config, so I wasn't even prompted for speakup configuration. I'm enabling it for all kernels, but it will only be present in the next update, ok?

**Comment by ericonr** [comment]
Fixed with dd6e2bb4062c1a4cfdde121dd2bc3675d61cb629

**Comment by joey-commits** [comment]
Thanks so much for fixing this. It can definitely be tricky to keep track of these config options when they move around or are renamed in new kernels. Waiting to rebuild 5.9 for the repos until a new kernel release is fine because I know kernel builds take a long time on the build servers. I can use 5.8 or build my own kernel until then. I really want to emphasize how much I appreciate your quick help on this fix. For me as a blind person, I guess no Speakup is like a video card that doesn't work for someone who can see, and I will probably sleep a bit better at night seeing this move out of staging.

**Comment by ericonr** [comment]
> Waiting to rebuild 5.9 for the repos until a new kernel release is fine because I know kernel builds take a long time on the build servers.

There's a chance it was picked up by the builders with 5.9.8, if you're up to trying it out once it's built.

> I will probably sleep a bit better at night seeing this move out of staging.

That's really nice! It's great when projects get better about their accessibility, and this looks like a very interesting addition.

> For me as a blind person, I guess no Speakup is like a video card that doesn't work for someone who can see

Really glad I could help, then :)
