### ISSUE TITLE
[Package Request] RHVoice

### ISSUE THREAD

**Issue by zenny** [void-linux/void-packages#26349]
### Package Name
RHVoice

### Package Source
https://github.com/Olga-Yakovleva/RHVoice

### Application
TTS (text-to-speech)

### Rationale
Better sounds than espeak and flite

### Licenses
LGPL, GPL, CC

**Comment by zenny** [comment]
Hi, I am trying to build RHvoice package from the source (https://github.com/Olga-Yakovleva/RHVoice). Just saw an AUR build (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rhvoice) and tried to make an xbps-src template. See http://ix.io/2Edy. Any inputs to make it compatible appreciated! Thanks!

```
# Template file for 'rhvoice-git'
pkgname=rhvoice-git
version=1.2.3.r37.2dc35bc
revision=1
build_style=gnu-configure
configure_args="--disable-multilib
 --disable-bootstrap
 --disable-lto
 --enable-checking=release
 --enable-host-shared
 --enable-languages=jit"
hostmakedepends="git scons speech-dispatcher portaudio libao"
makedepends="libpulse"
short_desc="Free and open source speech synthesizer for Russian and other languages. (development version"
maintainer="null"
license="GPL-3.0-or-later"
homepage="https://github.com/Olga-Yakovleva/RHVoice"
distfiles="${pkgname%-git}::'git+https://github.com/Olga-Yakovleva/RHVoice.git')"
checksum=SKIP
provides=("${pkgname%-git}")
conflicts=("${pkgname%-git}")
backup=('etc/RHVoice/RHVoice.conf')
wrksrc="rhvoice-${version}"

version() {
        cd "$srcdir/${pkgname%-git}"
        printf "%s" "$(git describe --long | sed 's/\([^-]*-\)g/r\1/;s/-/./g')"
}

build() {
        cd "$srcdir/${pkgname%-git}"
        scons prefix="/usr" sysconfdir="/etc" CPPFLAGS="$CPPFLAGS" CCFLAGS="$CFLAGS" \
              LINKFLAGS="$LDFLAGS"
}

package() {
        cd "$srcdir/${pkgname%-git}"
        mkdir -p "${pkgdir}/usr/lib/speech-dispatcher-modules"
        scons install DESTDIR="${pkgdir}" prefix="/usr" sysconfdir="/etc" \
              CPPFLAGS="$CPPFLAGS" CCFLAGS="$CFLAGS" LINKFLAGS="$LDFLAGS"
        ln -s "/usr/bin/sd_rhvoice" "${pkgdir}/usr/lib/speech-dispatcher-modules/sd_rhvoice"
}
```

**Comment by ericonr** [comment]
Void tries not to merge git packages; do you think they have a chance of doing actual releases?

Have you tried using this template? As is, it won't work at all, as far as I can tell. I'd recommend using `build_style=scons` for starters, and checking out other templates that use it for a suggested template structure.

**Comment by zenny** [comment]
> Void tries not to merge git packages; do you think they have a chance of doing actual releases?
> 
> Have you tried using this template? As is, it won't work at all, as far as I can tell. I'd recommend using `build_style=scons` for starters, and checking out other templates that use it for a suggested template structure.

I tried with the following template to build from the stable repo:

```
# Template file for 'rhvoice'
pkgname=rhvoice
version=1.2.3
revision=1
wrksrc="RHVoice-${version}"
build_style=scons
depends="speech-dispatcher libpulseaudio"
makedepends="scons portaudio libao"
optdepends="'portaudio: for portaudio backend' 'libao: for ao backend'"
backup="etc/RHVoice/RHVoice.conf"
short_desc="Free and open source speech synthesizer for Russian and other languages"
maintainer="/dev/null"
license="GPL-3.0-or-later"
homepage="https://github.com/Olga-Yakovleva/RHVoice"
distfiles="https://github.com/Olga-Yakovleva/RHVoice/archive/${version}.tar.gz"
checksum=d104f20dc75fcd133d21751a6e894d34b423e12e4784350b4b9573c727fb71cd


build() {
        cd "$wrksrc/RHVoice-${version}"
        scons prefix="/usr" sysconfdir="/etc" CPPFLAGS="$CPPFLAGS" CCFLAGS="$CFLAGS" \
              LINKFLAGS="$LDFLAGS"
}

package() {
        cd "$wrksrc/RHVoice-${version}"
        mkdir -p "${pkgdir}/usr/lib/speech-dispatcher-modules"
scons install DESTDIR="${pkgdir}" prefix="/usr" sysconfdir="/etc" \
              CPPFLAGS="$CPPFLAGS" CCFLAGS="$CFLAGS" LINKFLAGS="$LDFLAGS"
        ln -s "/usr/bin/sd_rhvoice" "${pkgdir}/usr/lib/speech-dispatcher-modules/sd_rhvoice"
}
```

It builds the package, but there is no `/usr/bin/sd_rdvoice` found after installation of the package. :( Any input?

**Comment by ericonr** [comment]
We don't use `pkgdir`, we use `DESTDIR`.

**Comment by zenny** [comment]
> We don't use `pkgdir`, we use `DESTDIR`.

Thanks @ericonr. 

I replaced all instances of  `pkgdir` with `DESTDIR`, 

```
# Template file for 'rhvoice'
pkgname=rhvoice
version=1.2.3
revision=1
wrksrc="RHVoice-${version}"
build_style=scons
depends="speech-dispatcher libpulseaudio"
makedepends="scons portaudio libao"
optdepends="'portaudio: for portaudio backend' 'libao: for ao backend'"
backup="etc/RHVoice/RHVoice.conf"
short_desc="Free and open source speech synthesizer for Russian and other languages"
maintainer="/dev/null"
license="GPL-3.0-or-later"
homepage="https://github.com/Olga-Yakovleva/RHVoice"
distfiles="https://github.com/Olga-Yakovleva/RHVoice/archive/${version}.tar.gz"
checksum=d104f20dc75fcd133d21751a6e894d34b423e12e4784350b4b9573c727fb71cd


build() {
        cd "$wrksrc/RHVoice-${version}"
        scons prefix="/usr" sysconfdir="/etc" CPPFLAGS="$CPPFLAGS" CCFLAGS="$CFLAGS" \
              LINKFLAGS="$LDFLAGS"
}

package() {
        cd "$wrksrc/RHVoice-${version}"
        mkdir -p "${DESTDIR}/usr/lib/speech-dispatcher-modules"
scons install DESTDIR="${DESTDIR}" prefix="/usr" sysconfdir="/etc" \
              CPPFLAGS="$CPPFLAGS" CCFLAGS="$CFLAGS" LINKFLAGS="$LDFLAGS"
        ln -s "/usr/bin/sd_rhvoice" "${DESTDIR}/usr/lib/speech-dispatcher-modules/sd_rhvoice"

```

Also, appended following 3 lines to `common/shlibs`

```
$ rg libRHVoice common/shlibs
3997:libRHVoice.so.5 rhvoice-1.2.3_1
3998:libRHVoice_audio.so.2 rhvoice-1.2.3_1
3999:libRHVoice_core.so.4 rhvoice-1.2.3_1
```

The package gets built, but it does not behave as expected (no `RHVoice` binary nor `sd_rhvoice` installed) after running ` $ sudo xbps-install --repository=hostdir/binpkgs rhvoice`. No errors either.

**Comment by ericonr** [comment]
@zenny is this still necessary given work on https://github.com/void-linux/void-packages/pull/27193 on espeak-ng?

The `build` and `package` functions aren't doing anything, void uses `do_build` and `do_install` for this functionality. You don't really need them, though. Just make `post_install` with 

```
ln -s "../lib/speech-dispatcher-modules/sd_rhvoice" "${DESTDIR}/usr/bin/sd_rhvoice"
```

and you should be good.

**Comment by zenny** [comment]
> @zenny is this still necessary given work on #27193 on espeak-ng?
> 

Yep, because espeak-ng produces robotic voice whereas rhvoice has more natural output.

> The `build` and `package` functions aren't doing anything, void uses `do_build` and `do_install` for this functionality. You don't really need them, though. Just make `post_install` with
> 
> ```
> ln -s "../lib/speech-dispatcher-modules/sd_rhvoice" "${DESTDIR}/usr/bin/sd_rhvoice"

I shall try and get back.

> ```
> 
> and you should be good.
