### ISSUE TITLE
Libreoffice writer icon mouseovers

### ISSUE THREAD

**Issue by installkari** [void-linux/void-packages#2636]
### System

* xuname:  
  *Void 4.9.124_1 x86_64 GenuineIntel uptodate rrrmDFF*
* package:  
  *libreoffice-6.1.0.3_2*

### Expected behavior
Mouseover displays text and icon without flashing
### Actual behavior
Icon and mouseover text flicker
### Steps to reproduce the behavior
1. Open any libreoffice suite
2. Hover over any of the options represented by icons such as bold, italics, underline, etc.

**Comment by pullmoll** [comment]
I don't see that here. What's the package which you downgraded?

**Comment by CoolOhm** [comment]
I am also having this problem after a recent update. When I mouseover any icon in any libreoffice program, the icon flickers and no text shows up.


Not sure what is causing it.

**Comment by pullmoll** [comment]
I suspect it's rather a graphics driver issue because I still don't see this effect.
What kind of graphics adapters do you use?

**Comment by CoolOhm** [comment]
I have 
    lspci |grep -i graph
    00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)

**Comment by kozachynskyi** [comment]
Tested on libreoffice-6.3.3.2_1. Doesn't seem to be a problem any more. 
@CoolOhm @installkari Do you still have the problem? 

Suggest to close in 2 Weeks if no feedback is given.

**Comment by kozachynskyi** [comment]
@pullmoll Shell we close this issue?
