### ISSUE TITLE
sof-firmware doesn't install alsa-ucm-conf, a necessary package for sof audio driver initialization

### ISSUE THREAD

**Issue by lane-brain** [void-linux/void-packages#26419]
Hi! After getting an X1C7 last year I became very familiar with issues relating to poor support for the audio chipset in the snd_hda_intel driver. Proper support was being taken up by Intel's sof audio driver project, and since the end of 2019 it has come a long way. The drivers work how you'd expect any other driver to work provided the firmware blobs are installed, which they are by default on at least ubuntu based distros.

I recently installed Void and expected that I'd be able to install the sof-firmware in the official repo and be good to go, but still couldn't initialize the card, it kept falling back on snd_hda_intel. Audio playback works fine on that driver, but it has no support for the directional mic on the laptop which is especially a problem in these times. The way things stand, it could lead to the illusion that the proper audio driver is being loaded when actually this is a regression from the state of the art support of the chipset.

Luckily, I spent a lot of time diagnosing this issue when info was scarce and was quickly able to determine why sof couldn't initialize, it has to do with sof needing the ucm topology config files put out by alsa. I wrote a template to pull the current alsa-ucm-conf release and install its contents to /usr/share/alsa/, which fixed the issue upon installation.

Initially I was worried that Void's pulseaudio wouldn't be able to handle it because it remains on the 13.0 release, because ucm2 was only properly supported by the new code supposed to debut in 14.0. However it appears that this part of the code may have been backported in advance of the new release, as autodetection of the sof module with working playback/capture was smooth and worked exactly like you'd expect.

I would recommend that sof-firmware be updated to include a new alsa-ucm-conf package as a dependency. I can create a PR for my alsa-ucm-conf template after I polish the template, but I wanted to submit this issue beforehand because it was so trivial to package this that I wondered whether there may have been some reason why sof-firmware was packaged but not alsa-ucm-conf that I wasn't aware of. 

(PS, for what its worth, I'm using a custom kernel because void doesn't compile in support for the Comet Lake chipset for its kbuild and primarily because I do audio production and need the low-latency patchset. Rest assured, everything I've stated is reproducible on the stock kernel.)

### System
* xuname:  
  Void 5.9.8-xanmod1_1 x86_64 GenuineIntel notuptodate rFFFFFFFFF
* package:  
  sof-firmware-1.5.1_1

### Expected behavior
Installing sof-firmware should install all packages necessary to properly load the sof kernel modules.

### Actual behavior
Because the alsa ucm topologies are not installed, sof kernel drivers cannot successfully initialize.

### Steps to reproduce the behavior
Install sof-firmware, `modprobe snd_sof_pci`. Or after a fresh reboot, `sudo dmesg | grep sof`.

**Comment by cinerea0** [comment]
FYI, there's also an issue with the `sof-firmware` package that's supposed to be solved in #26003, but it hasn't been merged yet for unknown reasons. If you could let me know where those 'alsa-ucm-conf' files are supposed to be installed, I can write up a template for it and include it in the previously mentioned PR before it gets merged.

**Comment by lane-brain** [comment]
Here is my template, it was based off of your template for `sof-firmware`. 

One last word, in my troubleshooting last year I learned that pulseaudio makes use of these ucm config files to autoconfigure detected cards, I'm not sure what decision would be proper to make considering dependencies on pulseaudio because in certain cases it still works out of the box without the ucm conf files. For example, using snd_hda_intel I had speakers working but no mic, but that driver doesn't fully support my laptop's dsp so that's to be expected. But definitely they should be deps for sof-firmware.

```
# Template file for 'alsa-ucm-conf'
pkgname=alsa-ucm-conf
version=1.2.4
revision=1
archs="i686* x86_64*"
depends="alsa-lib"
wrksrc=${pkgname}-${version}
short_desc="ALSA Use Case Manager topology configurations"
maintainer="lane-brain <lane@mailbox.org>"
license="BSD-3-Clause"
homepage="https://github.com/alsa-project/alsa-ucm-conf"
distfiles="https://www.alsa-project.org/files/pub/lib/${pkgname}-${version}.tar.bz2"
checksum=2c3b535c77dcb9aaf62a61f4f8324f1ab184162f105f7ec9ed1e37c742fcd340

do_install() {
    cd ${wrksrc}
    find ucm2 -type f -iname "*.conf" -exec install -vDm 644 {} "${DESTDIR}/usr/share/alsa/"{} \;
    find ucm2 -type l -iname "*.conf" -exec cp -dv {} "${DESTDIR}/usr/share/alsa/"{} \;
    install -vDm 644 README.md -t "${DESTDIR}/usr/share/doc/${pkgname}"
    install -vDm 644 ucm2/README.md -t "${DESTDIR}/usr/share/doc/${pkgname}/ucm2"
    vlicense LICENSE
}
```

**Comment by cinerea0** [comment]
@lane-brain Thank you for getting the template mostly done, that helps a lot! I do have a question: Where exactly are the configuration files supposed to be installed? Based on your script it looks like they're being installed in the `/usr/share/alsa` directory, but based on what I've read on how ALSA sources these files it makes more sense that they should all go in a `/usr/share/alsa/ucm2` directory, right?

**Comment by lane-brain** [comment]
the way the package is right now it does install into /usr/share/alsa/ucm2. the structure of the archive is that the root folder contains the ucm2 folder.  probably the install scripting can be simplified a bit, the distfile is pretty simple it has a lot of folders each containing 1-2 files each

**Comment by cinerea0** [comment]
Understood. I've packaged `alsa-ucm-conf` in the PR linked above if you want to check it out!
