### ISSUE TITLE
wideland-maps source not found

### ISSUE THREAD

**Issue by sgn** [void-linux/void-packages#26421]
@pullmoll It seems like source distfiles was fetched from your server.

**Comment by pullmoll** [comment]
Changed the template to use https instead of http. The file was/is still there, just not via http.

**Comment by q66** [comment]
why rebuild if the file didn't change?

**Comment by pullmoll** [comment]
To make sure it really can be built by others but me.

**Comment by sgn** [comment]
Actually, we could remove `noarch` with the rebuilds.

**Comment by pullmoll** [comment]
Yes, I forgot about dropping noarch.
