### ISSUE TITLE
firefox 83.0 won't load pages on aarch64-musl

### ISSUE THREAD

**Issue by duncancmt** [void-linux/void-packages#26639]
### System

* xuname:  
  `Void 5.7.0_1 aarch64-musl Unknown uptodate hold rrFFFFF`
* package:  
  `firefox-83.0_1`

### Expected behavior

```
$ firefox 'http://example.com'
```
example.com loads

### Actual behavior

```
$ firefox 'http://example.com'
```
white screen, loading icon never goes away

### Steps to reproduce the behavior

I uninstalled all my extensions; the behavior was unchanged. I created a new profile; even the "Welcome to Firefox" page that opens on first launch did not load.

**Comment by ericonr** [comment]
@jnbr

**Comment by jnbr** [comment]
Oops, looks like I broke the sandbox with the last update.
I try to fix this asap, until then, you can set the value for key `security.sandbox.content.syscall_whitelist` to `25`.

**Comment by duncancmt** [comment]
Thanks for the workaround. Good to know it's not just me.

**Comment by jnbr** [comment]
No problem, you should reset the syscall_whitelist after updating to the patched version (I'll merge it soon).
Out of curiosity: did it work with firefox-82 or did you only try 83?
I'm surprised this did not cause issues before.

**Comment by duncancmt** [comment]
I had `82.0.3_1` installed previously (and a number of other versions prior to that). It worked _fine_ before, but tabs and sometimes the entire browser would become unresponsive.

**Comment by duncancmt** [comment]
Do you have any idea why the repos aren't syncing? Neither the change from this nor #26638 have shown up yet.

**Comment by jnbr** [comment]
firefox build has not finished yet (first attempt failed for some reason).
For the other one, I don't know the reason.
