### ISSUE TITLE
musl toolchains should reject TEXTRELs

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#26641]
### Expected behavior

Given that musl's runtime linker doesn't support TEXTRELs, the linkers used to build packages for musl targets (both cross and native) should be configured to error out at build time when they find TEXTRELs.

### Actual behavior

Issues like #26638 happen. The linker should have caught it.

### Steps to reproduce the behavior

Cross build `rclone` without #26640 and run `readelf -d /path/to/rclone` to see the TEXTREL. The linker didn't complain.

**Comment by Hello71** [comment]
binutils configure --textrel-check=error, or =warning + package build system check. dunno which one is more appropriate for void

**Comment by Hello71** [comment]
actually, no, binutils already enables textrel-check on i386, so it only needs the build system to check for it.
