### ISSUE TITLE
gnome-disk-image-mounter fails to mount ISO on linux5.8

### ISSUE THREAD

**Issue by Oreo639** [void-linux/void-packages#26672]
### System

* xuname:  Void 5.8.18_1 x86_64 GenuineIntel notuptodate rrrmFFFFFFFFFFFF
  *output of ``xuname`` (part of xtools)*
* package:  `gnome-disk-utility-3.38.0_1` `linux5.8-5.8.18_1`
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
gnome-disk-image-mounter mounts iso file.

### Actual behavior
gnome-disk-image-mounter returns error:
```
Error attaching disk image:
GDBus.Error:org.freedesktop.UDisks2.Error.Failed: Error waiting for loop object after creating '/dev/loop0': Timed out waiting for object (udisks-error-quark, 0)
```

### Steps to reproduce the behavior
Install gnome-disk-utility.
Boot linux5.8.
Attempt to mount ISO using gnome-disk-image-mounter.

#### Note:
Attempting to use gnome-disk-image-mounter with linux5.6 works fine and I can't test linux5.7.

**Comment by sgn** [comment]
Does it work with linux 5.9?

**Comment by Oreo639** [comment]
Yes.
