### ISSUE TITLE
Package request: JabRef

### ISSUE THREAD

**Issue by TeddyDD** [void-linux/void-packages#267]
JabRef: https://www.jabref.org/ Bibliography manager

**Comment by abenson** [comment]
It depends on non-free software (parts of JavaFX that are not available in OpenJDK's OpenJFX), so I doubt it'll be packaged.

You should be able to download the JAR they provide, install void-repo-nonfree and then install oraclejre and run it that way.

**Comment by TeddyDD** [comment]
Oh, I thought OpenJDK is fully open source. Thanks for the info :)
