### ISSUE TITLE
ncurses-term file conflicts

### ISSUE THREAD

**Issue by ahesford** [void-linux/void-packages#26700]
The `ncurses-term` package ships some terminfo databases that conflict with files installed by terminal-specific packages:
- `alacritty-terminfo`
- `dvtm`
- `fbterm`
- `st-terminfo`

The `fbterm` package installs the compiled `/usr/share/terminfo/f/fbterm` directly, which is an outright conflict with a matching file in `ncurses-term`. The other three install source files (`*.info`) that do not directly conflict, but the `INSTALL` scripts compile these and overwrite corresponding files in `ncurses-term`; the `REMOVE` scripts of these packages remove the files.

This, at least, causes unnecessary noise in `xbps-pkgdb -a` output when both `ncurses-term` and terminal-specific packages are installed. More problematic is the potential breakage or degradation that may result when installing or reinstalling `ncurses-term`, which can replace newer databases that might be required by terminal emulators.

There doesn't appear to be a good way to handle this gracefully and automatically. I work around this issue for `alacritty` by adding XBPS `noextract` rules for `/usr/share/terminfo/a/alacritty{,-direct,+common}`. One possibility would be installing similar rules in `/usr/share/xbps.d` in each package that installs terminal-specific files, but not sure what happens on for `xbps<0.58`.

**Comment by ericonr** [comment]
Older XBPS isn't really supported, right?

We could look into configuring `ncurses-term` to remove those? It might be the best solution, since the upstream terminfo files should be the correct ones.

**Comment by ahesford** [comment]
Having to know in `ncurses-term` which files are offered by other packages (which may, over time, come and go) seems like an uglier solution than adding `noextract` rules to the specific packages, but I don't have a strong conviction.

**Comment by ericonr** [comment]
They are all really ugly solutions IMO, but changing `ncurses-term` would be the more correct one. If that correctness is worth it, idk.

Something like remove the bad files from `ncurses-term` and then make it depend on all the terminfo subpackages.

We could look into how other distros manage this.

**Comment by ahesford** [comment]
Arch and Alpine both do the opposite. The ncurses package provides these terminfo files. The alacritty packages in both decline to manually copy and compile the provided terminfo. The dvtm packages in both explicitly remove the terminfo after installation. I didn't bother looking at the other two.

I'm ok with removing the specific terminfo packages, letting them pull in ncurses-term instead. I'm also okay with noextract rules in the individual packages because they don't require specific knowledge. It's just a way to say, "I don't care who provides these files, I take precedence so don't allow anybody else to overwrite these." Going the other direction, removing specific files from ncurses because we want to defer to the specific packages, requires too much special casing and distributed knowledge for my taste.

**Comment by ericonr** [comment]
The idea of making sub packages and having ncurses-term depend on them would probably break bootstrapping, unless we make ncurses-term a separate package instead of a sub package.

**Comment by ahesford** [comment]
There's no great solution here, and I'm just using urxvt these days anyway.

**Comment by ericonr** [comment]
I'm just assigning myself so I can find it more easily if some great idea ever shines on me.
