### ISSUE TITLE
xbps-src throws an error of unknown trigger

### ISSUE THREAD

**Issue by d9d6ka** [void-linux/void-packages#26717]
### System

* xuname:  Void 5.9.11_1 i686 GenuineIntel uptodate rF
* package: xbps-src

### Expected behavior
Custom package is created.

### Actual behavior
I'm trying to build a custom package for `st`, but I can't copy a `.desktop` file to `/usr/share/applications`.
`xbps-src pkg st` aborts with the error `unknown trigger update-desktopdb` while executing `04-create-xbps-metadata-scripts` hook.

### Steps to reproduce the behavior
I've cloned `void-packages` and called `xbps-src binary-bootstrap`.
I've deleted all folders from `srcpkgs` except `st` & `st-terminfo`.
I've used the template file in [template.zip](https://github.com/void-linux/void-packages/files/5602012/template.zip).
Specifically, I've added `vinstall ${FILESDIR}/st.desktop 644 usr/share/applications` to the `post_install` function.

**Comment by biopsin** [comment]
Can't reproduce..print the /builddir/.xbps-st/do_install.log

**Comment by d9d6ka** [comment]
Sure
```
mkdir -p /destdir//st-0.8.4/usr/bin
cp -f st /destdir//st-0.8.4/usr/bin
chmod 755 /destdir//st-0.8.4/usr/bin/st
mkdir -p /destdir//st-0.8.4/usr/share/man/man1
sed "s/VERSION/0.8.4/g" < st.1 > /destdir//st-0.8.4/usr/share/man/man1/st.1
chmod 644 /destdir//st-0.8.4/usr/share/man/man1/st.1
Please see the README file regarding the terminfo entry of st.
cp -f st.desktop /usr/share/applications
```

**Comment by biopsin** [comment]
ah [update-desktopdb](https://github.com/void-linux/void-packages/blob/65ee7c07820ab9ec4b10586f2b9f4db8a7047588/Manual.md#triggers_update_desktopdb)

> It is automatically added to packages that have /usr/share/applications available as a directory.
I suppose the trigger is not needed in your template then

**Comment by Duncaen** [comment]
> I've deleted all folders from srcpkgs except st & st-terminfo.

This is not supported, it looks up the xbps-triggers package to verify that the hook exist.
Deleting all packages from the repository breaks a lot more things like dependency checks.

**Comment by d9d6ka** [comment]
> > I've deleted all folders from srcpkgs except st & st-terminfo.
> 
> This is not supported, it looks up the xbps-triggers package to verify that the trigger exist.
> Deleting all packages from the repository breaks a lot more things like dependency checks.

Maybe that's the case. I always try to keep as little extra files as possible...
I'll check it in couple of hours whether it works.

**Comment by Duncaen** [comment]
Its 100% the case, xbps-src needs the tree of all involved packages to function normally, including all dependencies of the package you build and their dependencies and all the packages that are required to setup and update the masterdir.

Here is the exact place where the error happens, it looks up the xbps-triggers source package to verify that the trigger it tries to include exist:
https://github.com/void-linux/void-packages/blob/e4be86c27ee37a394017ea4b7c7db23e89c04a78/common/hooks/post-install/04-create-xbps-metadata-scripts.sh#L317-L320

https://github.com/void-linux/void-packages/blob/795429f1a44cb0b84e3af1197c68b880aae86098/xbps-src#L543

**Comment by d9d6ka** [comment]
Yep, it works, my fault!
Thanks and sorry for wasting your time!

**Comment by jirutka** [comment]
I just ran into the same problem. How can the users create repository for their own templates?
