### ISSUE TITLE
libjson-c with musl is not found

### ISSUE THREAD

**Issue by ne-vlezay80** [void-linux/void-packages#26726]
* package:  frr/libcrytsetup/<self>

Package libjson-c is not found, if the system used musl library, beacuse of don't installeng frr package.

**Comment by ericonr** [comment]
Can you explain what you are trying to do? What command are you running, and what are the error messages, if any?

I'm on a musl system and I have `json-c` installed...

**Comment by ne-vlezay80** [comment]
You trying install frr from void linux:

https://ipfs.io/ipfs/QmQo4rQ6m6DgRwKuprmMTtHzQ3q5DoePpshp6FN192yEN6

**Comment by ericonr** [comment]
Can you update your system (`xbps-install -Su`) and then try to install `frr`?

**Comment by ne-vlezay80** [comment]
Update system is solve the problem

**Comment by ericonr** [comment]
Great! Is it ok to close the issue, then?

**Comment by ericonr** [comment]
I will add this case to https://docs.voidlinux.org/xbps/troubleshooting/common-issues.html as well, since we apparently don't cover it
