### ISSUE TITLE
Package Request: Legendary is a free and open-source Epic Games Launcher alternative.

### ISSUE THREAD

**Issue by TjayNL** [void-linux/void-packages#26750]
Is there an option to add **Legendary** to the repo?

**What is Legendary?**
Legendary is a free and open-source Epic Games Launcher alternative.

**Github repository**
https://github.com/derrod/legendary

**Comment by ericonr** [comment]
There was #22000 already if @not-chicken wants to revisit?

**Comment by not-chicken** [comment]
Yeah I still use it.

**Comment by TjayNL** [comment]
maybe this is a stupid question but i'm going to ask it anyway, how can i install it?

`sudo xbps-install legendary`

doesn't seem to work.

**Comment by ericonr** [comment]
@TjayNL after building it, you can install with `xi legendary`. `xi` comes from the `xtools` package.

**Comment by Piraty** [comment]
cf25250e2b771d10c25c5c685a1c761dcd8397dd
