### ISSUE TITLE
lurch / libomemo: 12-byte IVs patch

### ISSUE THREAD

**Issue by Neustradamus** [void-linux/void-packages#26757]
Hello @void-linux, @leahneukirchen,

Here:
- https://github.com/void-linux/void-packages/tree/master/srcpkgs/lurch

Can you add the missing 12-byte IVs patch:
- https://github.com/gkdr/libomemo/pull/27

Explaination:
- https://github.com/gkdr/libomemo/issues/24

Thanks in advance.

**Comment by Neustradamus** [comment]
@leahneukirchen: Thanks a lot for your quick change! :)

**Comment by eli-schwartz** [comment]
Note this is based on https://github.com/xsf/xeps/pull/894 which got NACKed by the author and closed without merging.

@Neustradamus has proceeded to trick various people into applying this specific patch, including at https://bugs.archlinux.org/task/68766 by claiming it's a critical security vulnerability (the severity got corrected prior to the bug being rejected), and the actual discussion in https://github.com/gkdr/libomemo/issues/24 seems to consist of more or less everyone being mad at @Neustradamus for circumventing actual development processes and pushing, randomly and inconsistently, at select distributors to use downstream patches that are under dispute.

I recommend reverting it and seeking upstream guidance. e.g.

https://github.com/gkdr/libomemo/issues/24#issuecomment-735408224
> please stop pushing downstream changes, it makes the whole situation even more confusing.

**Comment by ericonr** [comment]
@leahneukirchen ^^

**Comment by Neustradamus** [comment]
I confirm the security problem, we need to disable OMEMO Security to talk with Monal users.

Please read all and directly: https://github.com/gkdr/libomemo/issues/24#issuecomment-735294183

Thanks.

**Comment by ericonr** [comment]
From the actually accepted PR, https://github.com/xsf/xeps/pull/903

>   <li>Divide the HKDF output into a 32-byte encryption key, a 32-byte authentication key and a 16 byte IV.</li>

**Comment by leahneukirchen** [comment]
This is for OMEMO 0.4, apparently lurch implements 0.3?

**Comment by ericonr** [comment]
Never mind me, then.

**Comment by Neustradamus** [comment]
I have updated the main description.

All clients must support the OMEMO 0.3.0.

There was not the 0.3.1 badly.

XEP-0384: OMEMO 0.4.0 breaks all, there is a new "urn:xmpp:omemo:1".

OMEMO 0.4.0+ is a new step, I have done a ticket about it.

**Comment by q66** [comment]
> I confirm the security problem, we need to disable OMEMO Security to talk with Monal users.
> 

not being able to use encrypted messaging with users of a single client on iOS is not a security issue, and trying to pass it as one is just completely ridiculous

i vote that we revert this and follow upstream

**Comment by leahneukirchen** [comment]
Lots of other OMEMO 0.3 clients use 12-bit IV too, I don't see the problem here.

**Comment by ericonr** [comment]
From what I understood, those other clients knew how to handle 16-bit IV, which isn't the case for a specific app.

**Comment by Neustradamus** [comment]
Links:
- https://www.google.com/search?q=12+byte+iv
- https://monal.im/blog/omemo-and-french-laws/
- https://github.com/ChatSecure/ChatSecure-iOS#127
- https://monal.im/blog/omemo-is-broken-in-general-across-the-ecosystem/

**Comment by Neustradamus** [comment]
@the-maldridge: I see your revert, why?

The problem is compatibility with all OMEMO 0.3.0 clients.
libomemo 0.7.0 has been released with the fix.
Alpine, Debian, Gentoo, Alt Linux are perfect.

**Comment by the-maldridge** [comment]
Void tracks upstream, not random patches hurled out by persons unaffiliated who try to pass them off as "security" items when they clearly aren't.  If your patch is that important, work with upstream to ship it.

**Comment by Neustradamus** [comment]
It is, look libomemo 0.7.0:
- https://github.com/gkdr/libomemo/releases/tag/v0.7.0

**Comment by Neustradamus** [comment]
The problem is that in Void, there are not 3 packages like other OS:
- axc
- libomemo
- lurch

**Comment by the-maldridge** [comment]
Great, if you look at the timeline you'll see the revert happened before 0.7.0 was cut.  Again, Void's patch policy is not to accept patches from random people on the internet trying to bypass upstream review protocols, and so your patch was reverted.  You are welcome to submit a patch to update the package to the now released version which would be the appropriate way to get the update into Void.  Do note that as this is now OT for this issue and the content of this issue is now resolved, I'm unsubscribed from further notifications.
