### ISSUE TITLE
python: it should be python3 by default

### ISSUE THREAD

**Issue by Logarithmus** [void-linux/void-packages#26779]
I mean, it's the end of 2020, who in the world still use python2? Almost everyone has already migrated to python3. So IMHO we should have `python3` & `python2` packages and `python` meta package, pointing to `python3`.

**Comment by ericonr** [comment]
Not really doable without a mass rebuild of python2 packages, though I am not against it. Might make sense to hold on doing this for python 4, tho :P 

This doesn't solve the issue that packages are still named `python-foo` for python2 and `python3-foo` for python3.

**Comment by ahesford** [comment]
I am against it. Given that we are phasing out Python 2 packages entirely, this problem will eventually resolve itself. Attempting to migrate the legacy `python` package (with or without migrating all `python-*` packages to `python2-*`) will just add chaos and confusion to an ephemeral transition period. Once Python 2 is fully removed, we will just have `python3` and `python3-*` packages.

Closing as WONTFIX, if other members think there is merit in doing this migration, please reopen.
