### ISSUE TITLE
libnma / libnm-gtk upgrade issues

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#26789]
### System

* xuname:  N/A
* package:  libnma

### Expected behavior

Upgrades and runtime for applets works fine

### Actual behavior

Shit is broke. Definitely something wrong with common/shlibs . Might need a dummy metapackage (libnm-gtk) which depends on libnma, or maybe a replaces= line.

### Steps to reproduce the behavior

Upgrading or installing nm-applet should trigger the problem I believe.

**Comment by CameronNemo** [comment]
@cinerea0 @ericonr if y'all do not get this fixed I can take a look (maybe tomorrow)

**Comment by cinerea0** [comment]
There were quite a few packages that got changed in that PR. Should I add `libnma` as a dependency to all of them too to be safe?

**Comment by cinerea0** [comment]
@CameronNemo Now that my PR has been merged, do you think this is okay to close now?

**Comment by ericonr** [comment]
Yup, it was opened because of that issue. Thanks!
