### ISSUE TITLE
vpnc(musl version) cannot connect

### ISSUE THREAD

**Issue by rwx2019** [void-linux/void-packages#26798]
System: x86_64 (musl version)
Package: vpnc version 0.5.3

vpnc cannot connect:
When run it says: "can't initialise tunnel interface: No such file or directory".
/dev/net/tun present in system, but vpnc try find /dev/tun0-254 devices

**Comment by ericonr** [comment]
Is this still an issue?

**Comment by rwx2019** [comment]
Yes. This issue still present.

**Comment by Gottox** [comment]
I'm currently lacking a cisco endpoint where I can verify this behavior.

**Comment by rwx2019** [comment]
No need cisco endpoint for verify:
1.install vpnc

2.set config to:
IPSec gateway 127.0.0.1
IPSec ID test
IPSec secret test
#IKE Authmode hybrid
Xauth username test
Xauth password test

3.and just run: vpnc or strace vpnc

**Comment by rwx2019** [comment]
And You will see the following:
...
wait4(9377, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 9377
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f63baccfa1e}, NULL, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f63baccfa1e}, NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=9377, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
open("/dev/tun0", O_RDWR)               = -1 ENOENT (Нет такого файла или каталога)
open("/dev/tun1", O_RDWR)               = -1 ENOENT (Нет такого файла или каталога)
open("/dev/tun2", O_RDWR)               = -1 ENOENT (Нет такого файла или каталога)
open("/dev/tun3", O_RDWR)               = -1 ENOENT (Нет такого файла или каталога)
open("/dev/tun4", O_RDWR)               = -1 ENOENT (Нет такого файла или каталога)
open("/dev/tun5", O_RDWR)               = -1 ENOENT (Нет такого файла или каталога)
open("/dev/tun6", O_RDWR)               = -1 ENOENT (Нет такого файла или каталога)
open("/dev/tun7", O_RDWR)               = -1 ENOENT (Нет такого файла или каталога)
open("/dev/tun8", O_RDWR)               = -1 ENOENT (Нет такого файла или каталога)
...
open("/dev/tun253", O_RDWR)             = -1 ENOENT (Нет такого файла или каталога)
open("/dev/tun254", O_RDWR)             = -1 ENOENT (Нет такого файла или каталога)
writev(2, [{iov_base="", iov_len=0}, {iov_base="can't initialise tunnel interfac"..., iov_len=33}], 2can't initialise tunnel interface) = 33
writev(2, [{iov_base=": No such file or directory\n", iov_len=28}, {iov_base=NULL, iov_len=0}], 2: No such file or directory
) = 28
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by Gottox** [comment]
Okay, let's try that.

**Comment by Gottox** [comment]
I have an idea what's happening. Dang.

**Comment by Gottox** [comment]
@void-linux/pkg-committers Okay, we need to discuss this. vpnc is basicly foobar on musl. There's a fork of vpnc [here](https://github.com/streambinder/vpnc). This fork is used by alpine for example.

Unfortunately, parts of the build (vpnc-script) is only accessibly from a git-only repository and not part of vpnc itself anymore.

Should we switch to the new upstream? There are no releases yet. Also the template will become messy as we need to git-clone the vpnc-script repository.

**Comment by ericonr** [comment]
We don't need to clone, github allows us to pull a specific commit as an archive.

**Comment by ericonr** [comment]
In https://davidepucci.it/doc/vpnc/ , it mentions that the repository isn't for active development, but mostly for security and bug fixes (and new features others implement, but idk how common those are). In any case, if we switch to it, which seems reasonable, I'd suggest updating to the git tip whenever it gets security fixes.

**Comment by Gottox** [comment]
@ericonr The repository I was speaking of is not on github: git.infradead.org/users/dwmw2/vpnc-scripts.git/

**Comment by Gottox** [comment]
@ericonr Yea, it's still better than our current upstream as the last release was >10y ago.

**Comment by ahesford** [comment]
This seems to work for a snapshot of a specific hash:
```
http://git.infradead.org/users/dwmw2/vpnc-scripts.git/snapshot/<hash>.tar.gz
```

**Comment by ericonr** [comment]
@Gottox Ah, I see. Hmm, https://git.infradead.org/users/dwmw2/vpnc-scripts.git/commit/3885f8bbc4ae03fd6da0ada6de12f7223a59595c seems to work. I grabbed it by clicking "snapshot" in https://git.infradead.org/users/dwmw2/vpnc-scripts.git/commit/3885f8bbc4ae03fd6da0ada6de12f7223a59595c
