### ISSUE TITLE
mlfc: stack smashing detected (mlterm)

### ISSUE THREAD

**Issue by My9xVm** [void-linux/void-packages#26860]
- mlterm-3.9.1_1

```
0 $ mlfc
*** stack smashing detected ***: <unknown> terminated
Aborted
134 $
```

**Comment by ericonr** [comment]
Please follow the issue template and post `xuname` output.

**Comment by My9xVm** [comment]
- Void 5.8.18_1 x86_64 GenuineIntel uptodate rrFF

**Comment by ericonr** [comment]
Ok.

Can you try running it under `strace` or `gdb`? For `strace`, it's as simple as `strace mlfc`.

**Comment by My9xVm** [comment]
strace output: [2.log](https://github.com/void-linux/void-packages/files/5626442/2.log)

```
[root@host user]# ls /usr/share/fonts/SourceHan/
SourceHanMono.ttc  SourceHanSans.ttc  SourceHanSerif.ttc
[root@host user]# sha256sum /usr/share/fonts/SourceHan/*
0c192448de90848f11eb8336876883a9a36dc65b8965e489600cfcc7a67358c1  /usr/share/fonts/SourceHan/SourceHanMono.ttc
8c06d305a45d56fbc81ec67ca0afa552fbae1e69d4d42b49016a9ace677f89d8  /usr/share/fonts/SourceHan/SourceHanSans.ttc
85cc634fa228286ca307803bbb4ca61f61fa821b3ed573f4f07c6f0c064426b5  /usr/share/fonts/SourceHan/SourceHanSerif.ttc
```

- https://github.com/adobe-fonts/source-han-mono/releases
- https://github.com/adobe-fonts/source-han-sans/releases
- https://github.com/adobe-fonts/source-han-serif/releases

**Comment by ericonr** [comment]
I couldn't spot anything out of the ordinary.

Could you try runnning `DEBUGINFOD_URLS="https://debuginfod.s.voidlinux.org" gdb mlfc` ? Once it crashes, try printing the backtrace with `bt full`.

The URL at the beginning is to automatically download debug symbols for the package.

**Comment by My9xVm** [comment]
Now i installed mlterm-dbg.

strace output: [2_new.log](https://github.com/void-linux/void-packages/files/5627077/2_new.log)

```
$ gdb mlfc
```

[gbd_0.log](https://github.com/void-linux/void-packages/files/5627106/gbd_0.log)

```
DEBUGINFOD_URLS="https://debuginfod.s.voidlinux.org" gdb mlfc
```

[gbd_1.log](https://github.com/void-linux/void-packages/files/5627108/gbd_1.log)

GDB verison is 10.1 because i use [this LiveCD](https://repo.voidlinux.de/live/void-live-x86_64-20201124-xfce.iso) reinstalled my system after this issue.

**Comment by My9xVm** [comment]
If i removed /usr/share/fonts/SourceHan/, mlfc works without error.

![1](https://user-images.githubusercontent.com/48840001/100832707-68704a80-3436-11eb-90fc-a0bffec482b1.png)
![2](https://user-images.githubusercontent.com/48840001/100832718-6b6b3b00-3436-11eb-9d99-8ea4d7775f87.png)
![3](https://user-images.githubusercontent.com/48840001/100832719-6d34fe80-3436-11eb-99ef-a9d83bff24a1.png)

**Comment by ericonr** [comment]
That might be a bug that should be reported to `mlterm` instead (or the library that `mlfc` uses?)... Those font files might be too big and/or complex, which it doesn't know how to deal with safely.

**Comment by ericonr** [comment]
Their homepage is http://mlterm.sourceforge.net/ , the GitHub repo is https://github.com/arakiken/mlterm and I believe issues might go in https://sourceforge.net/p/mlterm/bugs/ .

ping @leahneukirchen

**Comment by ericonr** [comment]
@My9xVm ping?

**Comment by My9xVm** [comment]
Sorry, I not login github long time. (because bad net)

Now I used xfce4. It's working for me.

(I can't access sourceforge, thanks firewall.)
