### ISSUE TITLE
enable CONFIG_FONT_TER16x32 on all kernels

### ISSUE THREAD

**Issue by danteissaias** [void-linux/void-packages#26882]
`CONFIG_FONT_TER16x32` enables a larger font (based on `terminus-font`) which is used when the kernel detects a HiDPI display. the default linux console font is extremely small on 4k displays therefore `CONFIG_FONT_TER16x32` being enabled is essentially a must. it also appears that `CONFIG_FONT_TER16x32` is enabled on some architectures not others which also could raise an issue of consistency? (although i'm not sure if this is intentional or not, please correct me if it is) it appears to be enabled on mips, arm etc. but not on x86-64.

**Comment by Piraty** [comment]
66cdf165862ecd9844b0df1c3c7c938a0aae3a83
81b42ca88be353d4b8d112d6ab381821d875f443
