### ISSUE TITLE
Maxima Crash

### ISSUE THREAD

**Issue by Daveed9** [void-linux/void-packages#26935]
### System

* xuname:  Void 5.8.18_1 x86_64 GenuineIntel uptodate rFFF
* package:  maxima-5.44.0_4

### Expected behavior

The program runs.

### Actual behavior

Starting maxima fails with the following message

```
$ maxima 
fatal error encountered in SBCL pid 2272 tid 2272:
core was built for runtime "a-hel-fi-void-buildslave-2020-09-30-18-48-34" but this is "a-hel-fi-void-buildslave-2020-11-29-18-30-04"
```

### Steps to reproduce the behavior

Install the program from the repos. I have tried maxima on two systems with different mirrors and get the same error. Compiling from source works just fine.

**Comment by ericonr** [comment]
@jbgg @leahneukirchen thoughts?

**Comment by leahneukirchen** [comment]
Are you sure you have maxima-5.44.0_4 and not maxima-5.44.0_3? I can reproduce with _3, but we fixed this in _4.

**Comment by Daveed9** [comment]
My appologies — the problem was indeed fixed with _4. Thank you!
