### ISSUE TITLE
[Package Request] Haskell-language-server

### ISSUE THREAD

**Issue by motorto** [void-linux/void-packages#26959]
Been trying to package [haskell language server](https://github.com/haskell/haskell-language-server) for void Linux unsuccessfully.

Here is the errors it gives me:

```
=> Using stack config in stack.yaml.
Stack looks for packages in the directories configured in
the 'packages' and 'extra-deps' fields defined in your stack.yaml
The current entry points to /builddir/haskell-language-server/,
but no .cabal or package.yaml file could be found there.
```

Any help would be appreciated , probably exist a smart way to package it though ! 

EDIT: Forgot to put my [files](https://github.com/motorto/void-packages/commit/49327935646ead028d808bbcb173c962b01c56ac)

**Comment by prez** [comment]
ghcup would be more useful imo.

**Comment by slotThe** [comment]
> ghcup would be more useful imo.

What would a package of ghcup even look like?  We can wrap the shell script, sure, but at that point you could also just execute the shell script...

**Comment by motorto** [comment]
ghcup-hs is interesting didn't know the existence of that !

But the point of it from my understanding is to have a "portable" haskell development environment, it install everything on $HOME/.ghcup , so uninstalling  it's pretty simple. Don't know to what point it's an advantage to have it packaged.

**Comment by slotThe** [comment]
@motorto [ghcide](https://gist.github.com/slotThe/e3351bafe370cf0654814b450137a548)

I'll try to look into HLS directly as soon as I can find the time

**Comment by motorto** [comment]
Thanks @, Appreciate my knowledge of xbps-src doesn't allow me to go further than that :)  

------------
@prez 
ghcup-hs looks interesting , were you able to run their bootstrap script ? It always fail to me, probably a missing dependency ...

**Comment by prez** [comment]
As you mentioned, ghcup is not a shell script. It is a Haskell program serving the same purpose as rustup, so the question whether inclusion in the repositories would make sense is kind of moot. It is also the recommended way to install ghc, cabal and hls. 

Unfortunately I have not yet found the time to experiment with building this myself, however `bootstrap-haskell` doesn't look relevant from a first glance.

**Comment by motorto** [comment]
Ghcup is interesting for sure, and it installs haskell-language-server as an option, I will try to understand what distros ship ghcup besides ubuntu , can't seem to find the source only the dpkg file.

**Comment by slotThe** [comment]
@motorto [haskell-language-server](https://gist.github.com/slotThe/b6d6cc77c96f61d77d0a9a4dd2ca0393)

If you want to add both of these as new packages (with yourself as the maintainer, of course ;) feel free to; I may or may not get to it after the holidays

**Comment by motorto** [comment]
Thanks !! 

Don't know if it is better for you to do it. I probably wont be able to
maintain the package (because of lack of knowledge)
It will probably be just changing the version and/or updating the
stack.yaml to the new version, but if something is introduce that
changes the way the xbps-src builds the package ...

Once again thanks!

**Comment by Chocimier** [comment]
Added in #27961.
