### ISSUE TITLE
How to run INSTALL script with bash

### ISSUE THREAD

**Issue by DBLouis** [void-linux/void-packages#26967]
I want to run the INSTALL script of a package with bash instead of sh. (This is for a personal package not to be PR here)
How can I do that? Setting the hashbang to /bin/bash does not work.

**Comment by sgn** [comment]
Either:

- Ship some bash script with your package and and execute that script during installation
- `bash -c '<bash code here>'`

**Comment by DBLouis** [comment]
I was thinking that xbps must execute the INSTALL script like this `sh <script>` instead of running it as an executable. That's why the hashbang does nothing. Is there a reason for not running as an executable?

**Comment by Duncaen** [comment]
The actual install scripts inside the package is generated, i.e. anything that requires a trigger is added to the script and the `INSTALL` file is just appended to it.

Not using the shebang is probably done, to allow `xbps-install -r foo` without root (which would be required for chroot) to use the shell from the chroot and not from the host system.

**Comment by sgn** [comment]
I guess this is resolved.
