### ISSUE TITLE
NVIDIA 390 driver does not start 5.9.12_2

### ISSUE THREAD

**Issue by devilpower** [void-linux/void-packages#26975]
after installing driver, kernel is in infinite loop at system startup
it just goes back to normal when i uninstall  drivers dkms

**Comment by ericonr** [comment]
I'm not sure that driver actually supports 5.9...

See #26945

**Comment by devilpower** [comment]
i need to install the driver

**Comment by abenson** [comment]
It does not support it. There should be an official release from nvidia for 390 Soon™, but I've been trying to work on patching it. Unfortunately I don't have an i686 system to test with as easy.

**Comment by devilpower** [comment]
GPU I'm using is GT 620 OEM

**Comment by abenson** [comment]
Fixed in b18e5801fc5b32f12b9270267f329f497084b872
