### ISSUE TITLE
Goodvibes needs gst-plugins-good1 package

### ISSUE THREAD

**Issue by marties** [void-linux/void-packages#26980]
### System

* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
goodvibes-0.6_1

### Expected behavior
play radio urls 
### Actual behavior
no sound, error in console
WARN 07:37:56 ../src/core/gv-engine.c: on_bus_message_error(): Gst bus error msg: gst-core-error-quark:12: Aucun gestionnaire d’URI implémenté pour « http ».
WARN 07:37:56 ../src/core/gv-engine.c: on_bus_message_error(): Gst bus error debug: ../gst/playback/gsturidecodebin.c(1408): gen_source_element (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0

### Steps to reproduce the behavior

Goodvibes needs to install gst-plugins-good1 to work

**Comment by ericonr** [comment]
@marties could you make a PR to add this?

**Comment by ericonr** [comment]
I'd argue it could include both `good` and `ugly`, for mp3 support. https://gitlab.com/goodvibes/goodvibes

@mobinmob
