### ISSUE TITLE
zita-at1 fails to start

### ISSUE THREAD

**Issue by jrigg** [void-linux/void-packages#27002]
Tried running zita-at1 (autotune program used for music pitch correction) but it fails to start.

### System
Void x86_64 glibc

* xuname:  

* package: zita-at1-0.6.2_1

### Expected behavior
Start jackd then start zita-at1 and it should  launch

### Actual behavior
Fails with error message:
Can't open '/usr/local/share/zita-at1/notesect.png'

### Steps to reproduce the behavior
Attempt to start zita-at1

The 'missing' file is actually installed in the correct place, but the program is looking in /usr/local instead of /usr. Workaround:
`cd /usr/local/share`
`ln -s /usr/share/zita-at1 zita-at1`

**Comment by ericonr** [comment]
@jrigg could you please try #27003? It should fix this.

Thanks for the great bug report!

**Comment by jrigg** [comment]
> @jrigg could you please try #27003? It should fix this.

That was quick! 

I still need to get familiar with building packages from xbps templates. I've just switched my production DAWs from Debian to Void after testing it on a spare system. The fix looks good, but I'll confirm as soon as I've worked out how to use the build system.

**Comment by ericonr** [comment]
Just take a look at https://github.com/void-linux/void-packages#quick-start

That covers all the steps.

**Comment by ericonr** [comment]
I just checked that it does start up now, so it should be good to go. Update your system in a bit and you'll have it :)

**Comment by jrigg** [comment]
I confirm it starts now. Thanks for the quick fix!
