### ISSUE TITLE
Request: Update gcc to 10.2

### ISSUE THREAD

**Issue by harrisonthorne** [void-linux/void-packages#27013]
I'm trying to build [`yabridge`](https://github.com/robbert-vdh/yabridge), which requires GCC 10+. Version 10 came out in July. Is it possible to get this updated, or are there complications involved with updating it?

**Comment by ericonr** [comment]
See #24258 

We are waiting on the linux5.10 release to update the kernel-libc-headers package and go from there to updating glibc and gcc (I believe that sequence is required because of some weird incompatibilities).

**Comment by ericonr** [comment]
Currently being done.
