### ISSUE TITLE
Tomb 2.8  error line 429, duplicate "getpasspass" output=$(pinentry_assuan_getpassgetpasspass  | pinentry-curses)

### ISSUE THREAD

**Issue by darmon77** [void-linux/void-packages#27138]
### System

* xuname: Void 5.9.13_1  x86_64 GNU/Linux Intel 

* package:  tomb-2.8_1

### Expected behavior
tomb open secreto.tomb -k secreto.tomb.key 
tomb  .  Commanded to open tomb /home/darmon/secreto.tumb
tomb  .  Valid tomb file found: /home/darmon/secreto.tumb
tomb  .  Key is valid.
tomb  .  Mountpoint not specified, using default: /media/secreto
tomb (*) Opening secreto on /media/secreto
tomb  .  This tomb is a valid LUKS encrypted device.
tomb  .  Cipher is "aes" mode "xts-plain64:sha256" hash "sha256"
tomb  .  A password is required to use key /home/darmon/secreto.tomb.key
tomb  .  Password OK.
tomb (*) Success unlocking tomb secreto
tomb  .  Checking filesystem via /dev/loop1
fsck from util-linux 2.36
secreto: clean, 223/127512 files, 57720/509952 blocks
tomb (*) Success opening secreto.tumb on /media/secreto
tomb  .  Last visit by root(0) from /dev/pts/5 on Dennis
tomb  .  on date Mon Dec 14 15:43:14 2020

### Actual behavior
tomb open secreto.tomb -k secreto.tomb.key
tomb  .  Commanded to open tomb /home/darmon/secreto.tomb
tomb  .  Valid tomb file found: /home/darmon/secreto.tomb
tomb  .  Key is valid.
tomb  .  Mountpoint not specified, using default: /media/secreto
tomb (*) Opening secreto on /media/secreto
tomb  .  This tomb is a valid LUKS encrypted device.
tomb  .  Cipher is "aes" mode "xts-plain64:sha256" hash "sha256"
tomb  .  A password is required to use key /home/darmon/secreto.tomb.key
ask_password:59: command not found: pinentry_assuan_getpassgetpasspass 
tomb [W] User aborted password dialog.
tomb [E] No valid password supplied.

### Steps to reproduce the behavior
**error line 429**
 output=$(pinentry_assuan_getpassgetpasspass | pinentry-curses)

**Solution **
output=$(pinentry_assuan_getpass | pinentry-curses)

**Comment by biopsin** [comment]
Yeah needs a update to 2.8.1 as this was fixed in https://github.com/dyne/Tomb/commit/da590fb50e84acfe1e87a872d66915802c719f36

**Comment by ericonr** [comment]
Could you make a PR for it? Should be pretty simple.

**Comment by biopsin** [comment]
well I could do it, however is it fine to ignore these build warnings https://github.com/dyne/Tomb/issues/399
As I'm not a tomb user; I don't want to push something that might brake something write dependent by any chance, knowing my luck in these matters ;p
@diogoleal @darmon77 any chance you would update and test, since one of you are using it?

**Comment by ericonr** [comment]
@biopsin you can make a PR and ask for testers there, too :)

**Comment by darmon77** [comment]
The only difference between the tomb void package and the dyne package is line
429: pkg void 2.8.0= output=$(pinentry_assuan_getpassgetpasspass | pinentry-curses) dyne/Tomb#399
429: pkg dyne 2.8.1= output=$(pinentry_assuan_getpass | pinentry-curses)
771: pkg void 2.8.0= local fd=1
771: pkg dyne 2.8.1= local fd=2
783: pkg void 2.8.0= fd=2
783: pkg dyne 2.8.1= ;; 

Tested in musl and glibc x86_64, all perfect.
Just update the dyne package
