### ISSUE TITLE
pcc doesn't work in glibc

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#27149]
### System

* xuname: Void 5.9.13_1 x86_64 GenuineIntel notuptodate hold rrrrmmnFFFFFFFFFFFFF
* package: pcc-1.1.0.20190420_1

### Expected behavior

Produces a working binary.

### Actual behavior

Even the simplest binary segfaults when first launched.

### Steps to reproduce the behavior

Build

```
int main()
{
        return 0;
}
```

with `pcc main.c` and run it `./a.out`.

**Comment by leahneukirchen** [comment]
Note that `pcc -c` followed by `gcc` for linking only works.

Possibly related: https://pcc.ludd.ltu.narkive.com/GsfwuTd6/sigsegv-in-pcc-produced-executables-on-linux-i686

**Comment by ericonr** [comment]
Would you like to remove broken from it? The situation around `pcc` versions seems fuzzy, so I can't really tell if that fix was supposed to have landed for us at some point...

**Comment by leahneukirchen** [comment]
No, it seems still broken. But this 10 year old thread references the error. :p
