### ISSUE TITLE
void linux booted but doesn't show tty

### ISSUE THREAD

**Issue by ayoubkafi** [void-linux/void-packages#27156]
I installed void-linux without desktop envirement on BISO mode alongside Arch-Linux successfully<br>
I turned on my computer and I choosed Void-GNU/linux from grub it booted
and printed<br>
```
Loading Linux 5.3.9_1 ...
Loading initial ramdisk ...
```
after that I get black screen and it doesn't show me the tty

**Comment by ericonr** [comment]
Any chance you have nvidia graphics?

**Comment by ayoubkafi** [comment]
> Any chance you have nvidia graphics?
No
I have
Intel Core Processor (GPU)
Intel i5 M 520 (4) @ 2.400GHz (CPU)

**Comment by ericonr** [comment]
Can you chroot into the installation using the arch linux installation, and run `xbps-pkgdb -a` inside it?

How did you install it? Installer, chroot install...

If you can, this sort of help works better on reddit or IRC (`#voidlinux` on irc.freenode.net). GitHub issues are mostly for specific packages.

**Comment by ayoubkafi** [comment]
![bg-default](https://user-images.githubusercontent.com/71545968/102130875-b0896700-3e51-11eb-84bb-b1dc4d92446d.png)

**Comment by ayoubkafi** [comment]
![void](https://user-images.githubusercontent.com/71545968/102130926-c1d27380-3e51-11eb-80ee-78428f18ef26.png)

**Comment by ericonr** [comment]
Yeah that one file shouldn't really matter...

Can you show the output of `xbps-query -m` ? If possible, please copy it as text.

What's your kernel command line, if any? Can you try adding `single` to it? That should allow most setups to boot into Void.

**Comment by sgn** [comment]
Can you look into the last log inside `/var/log/dmesg.log`, check if `/var/service` correctly linked to `../run/runit/runsvdir/current`,
contents of `/etc/runit/runsvdir/default`? Also `/var/log/socklog/daemon/current` could be interesting as well.

**Comment by ayoubkafi** [comment]
I have a laptop
I put it into sleep mode after booting void-linux and when I opened tty1 appeared
This is `xbps-query -m` output
```
base-system-0.112_6
cryptsetup-2.2.2_1
grub-i386-efi-2.04_2
grub-x86_64-efi-2.04_2
lvm2-2.02.185_1
mdadm-4.1_2
```
The file `/var/service` is linked to `../run/runit/runsvdir/current` but `../run/runit/runsvdir/current` doesn't exist
This is output of `ls -1 /var/run`
```
blkid
lock
mount
sudo
```

**Comment by fosslinux** [comment]
Do you have a separate /boot partition? Are any of your partitions full?

**Comment by ayoubkafi** [comment]
> Do you have a separate /boot partition? Are any of your partitions full?

I don't have separate /boot parition
I don't think the problem is in booting becaus system was booted 
I put laptop into suspend mode after booting void-linux and when I opened it tty1 appeared

**Comment by ayoubkafi** [comment]
I encountered many problems which I could not find an explanation and I have not encountered them before in archLinux so I decided to delete voidLinux from my device I have installed it again but after a long time, sorry for the inconvenience

**Comment by Anachron** [comment]
Fair enough,- see you again!

**Comment by ayoubkafi** [comment]
Sorry, I think I came back quickly
I forgot to tell you about this error message
`[drm:intel_cpu_fifo_underrun_irq_handler [i915]] *ERROR* CPU pipe A FIFO underrun`
Could this have anything to do with the problem?
