### ISSUE TITLE
[package request] tiny-irc-client

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#27180]
https://github.com/osa1/tiny
With desktop notifications enabled please

Here the arch PKGBUILD exemple:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tiny-irc-client-git

**Comment by FollieHiyuki** [comment]
I have a template here if anyone wants to package it (I don't use IRC). Haven't tested.
The `tls-native` feature is still missing though.
```
# Template file for 'tiny'
pkgname=tiny
version=0.8.0
revision=1
build_style=cargo
configure_args="--features=desktop-notifications"
hostmakedepends="dbus-libs"
makedepends="libressl-devel"
short_desc="Tiny terminal IRC client"
maintainer=""
license="MIT"
homepage="https://github.com/osa1/tiny"
distfiles="https://github.com/osa1/tiny/archive/v${version}.tar.gz"
checksum=acaf0b7c3515bdfd0c80b4a7274aec44d283025c6e40508e450525167f73e447

post_install() {
     vlicense LICENSE
}
```

**Comment by eoli3n** [comment]
Thanks ! As said in the README, desktop notifications are for the moment disabled in releases, it need to be added in build.
I asked for a release with desktop notifications added, in mentioned issue.
