### ISSUE TITLE
Many pycompile_dir definitions use absolute path instead of relative one

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#27188]
### Expected behavior

Installing a package with python files, such as `gdb`, into an alternate root should try to compile the python files in the alternate root.

### Actual behavior

The hook uses the alternate root's python, `usr/bin/python3`, but the GDB template specifies `pycompile_dirs="/usr/share/gdb/python"`, which makes it try to build the system's python files, with the wrong python even. I noticed because I was running xbps-install as a user and it gave me multiple permission errors. Multiple templates have this same issue.

**Comment by Chocimier** [comment]
Given that all other variables take absolute path, I would rather take absolute here too and ensure operating in rootdir, like mkdirs do now.

#27265

**Comment by ericonr** [comment]
Thanks for looking into it.
