### ISSUE TITLE
bootstrap fails for missing debuginfod

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#27190]
A stage0 bootstrap for `x86_64` with `kernel-libc-headers-5.10` finishes w/o errors. ~~Yet you cannot use it for a binary-bootstrap because `gdb` depends on `debuginfod`, a subpkgf of `elfutils`, but `elfutils` is not `bootstrap=yes` and so `debuginfod` is not there.
I think to solve this the `gdb` template should add `debuginfod` to the `build_options_default` iff `$CHROOT_READY` is non zero.~~

It is not `gdb`  but `binutils` which need to explicitly disable debuginfod by `--without-debuginfod` in case `$CHROOT_READY` is zero.

**Comment by q66** [comment]
but gdb is not a bootstrap package

**Comment by pullmoll** [comment]
Hmm, true. I wonder why trying to `./xbps-src -N binary-bootstrap x86_64` failed, though.

**Comment by q66** [comment]
if something is pulling in gdb by accident, it needs to be found and fixed

**Comment by pullmoll** [comment]
Currently redoing the stage0 and will then try to identify the candidate.

**Comment by q66** [comment]
okay, remember that gdb must not even be built, so if it's being built, that is already wrong

**Comment by pullmoll** [comment]
Yeah, I thought it was part of the bootstrap and did the `$CHROOT_READY` shielding for `debuginfod`, but this should then not change a thing.
Also the `bootstrap` itself actually installed the packages, but I then did `./xbps-src zap` and tried the `./xbps-src -N binary-boostrap` as I always did.

**Comment by q66** [comment]
you don't need to binary-bootstrap after bootstrap, what you need to do is remove the binary packages and then build `base-chroot` using the masterdir, *then* zap and binary-bootstrap to proceed to stage 1, and erase the binpkgs again

**Comment by pullmoll** [comment]
Sure, this would have been the next step anyway. I've done it many times. So the difference is I cannot use a set of stage0 packages to do a `binary-bootstrap`. That used to work previously.

**Comment by pullmoll** [comment]
So I'll try the stage1 next.
[stage0-files.txt](https://github.com/void-linux/void-packages/files/5699479/stage0-files.txt)

**Comment by pullmoll** [comment]
Peeking at the stage0 `x86_64-repodata` I see it is the `binutils` referring to `debuginfod`:
```xml
       <key>binutils</key>
        <dict>
                <key>architecture</key>
                <string>x86_64</string>
                <key>filename-sha256</key>
                <string>3618d892f6c72dbfd156649d2777f617e727bd7bd3ca6a89e65c889bd01483d1</string>
                <key>filename-size</key>
                <integer>5650737</integer>
                <key>homepage</key>
                <string>http://www.gnu.org/software/binutils/</string>
                <key>installed_size</key>
                <integer>27194915</integer>
                <key>license</key>
                <string>GPL-3.0-or-later</string>
                <key>maintainer</key>
                <string>Enno Boland &lt;gottox@voidlinux.org&gt;</string>
                <key>pkgver</key>
                <string>binutils-2.34_1</string>
                <key>run_depends</key>
                <array>
                        <string>zlib&gt;=1.2.3_1</string>
                        <string>glibc&gt;=2.29_1</string>
                        <string>libdebuginfod&gt;=0.182_1</string>
                        <string>libstdc++&gt;=4.4.0_1</string>
                        <string>libgcc&gt;=4.4.0_1</string>
                </array>
                <key>shlib-requires</key>
                <array>
                        <string>libz.so.1</string>
                        <string>libdl.so.2</string>
                        <string>libc.so.6</string>
                        <string>libdebuginfod.so.1</string>
                        <string>libstdc++.so.6</string>
                        <string>libgcc_s.so.1</string>
                        <string>libpthread.so.0</string>
                </array>
                <key>short_desc</key>
                <string>GNU binary utilities</string>
        </dict>
```

**Comment by ericonr** [comment]
I have a PR to add that (https://github.com/void-linux/void-packages/pull/26502) but it hasn't been merged yet...

**Comment by pullmoll** [comment]
Um, let me check what I took from your `musl-1.2.0` branch.. *blushes*

**Comment by q66** [comment]
looks like we need to explicitly *disable* `debuginfod` when not `CHROOT_READY` to prevent host system from affecting it then...

**Comment by pullmoll** [comment]
Yes, that should solve the problem.

**Comment by pullmoll** [comment]
For completeness sake 
[stage1-files.txt](https://github.com/void-linux/void-packages/files/5699787/stage1-files.txt)
