### ISSUE TITLE
Package Request: eID-mw

### ISSUE THREAD

**Issue by Sarkasper** [void-linux/void-packages#272]
### System

* xuname:  
  *Void 4.16.14_1 x86_64-musl GenuineIntel uptodate rrn*
* suggested package name and description:  
  *beid-mw: Belgian eID PKCS#11 module*

### Website
https://eid.belgium.be/en/linux-eid-software-installation
### Package on other linux distributions
https://svnweb.freebsd.org/ports/head/security/libbeid/
https://aur.archlinux.org/packages/eid-mw/

**Comment by abenson** [comment]
> Use the Belgian electronic identity card (eID) in Firefox. In addition to this add-on, the eID middleware should also be installed on your computer: download the middleware for your operating system on eid.belgium.be.

You still need this package to use the Firefox add-on.
