### ISSUE TITLE
New libcap-ng package breaks gnome-keyring-daemon and cifs-utils

### ISSUE THREAD

**Issue by lane-brain** [void-linux/void-packages#27216]
It seems that `libcap-ng` 0.8.2 was finally committed to master 10 hours ago. Upon updating to the new package today, I noticed that gnome-keyring-daemon could not launch, giving the following error:
`gnome-keyring-daemon: error dropping process capabilities, aborting'

Research led me to this:
https://bugs.archlinux.org/task/68664

Then to:
https://github.com/stevegrubb/libcap-ng/issues/21

Which then led me to this:
https://github.com/GNOME/gnome-keyring/commit/ebc7bc9efacc17049e54da8d96a4a29943621113#diff-362e1a6b74e7bdbf1d0448cb892b79fe99ff7949c8c7bfd95788e9c5cd70b61b

And it seems also that `cifs-utils` was affected. Here is the commit that fixes their issue with the new libcap-ng.
https://github.com/piastry/cifs-utils/commit/fcef79bc705b70862326e1394dfe77295086bcbb

Merging the patch from gnome-keyring-daemon was all it took to get it back working, so I bumped up the revision and added the patchfile pulled from the commit. Also built the cifs-utils with that repo's commit fixing this issue and included the patch as well.

I've made a branch on my forked repo with the changes. Builds look good on my end. Submitting a pull request.

**Comment by lane-brain** [comment]
PR: https://github.com/void-linux/void-packages/pull/27217/commits/fa4bb383323f3ba2088cf40dde269a1118848e9c

**Comment by ericonr** [comment]
Fixed in https://github.com/void-linux/void-packages/pull/27227 and https://github.com/void-linux/void-packages/pull/27220 , thanks!
