### ISSUE TITLE
[FTBFS] ktoblzcheck

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#27228]
Building `ktoblzcheck` hangs forever for no obvious reason. Trying to strace the `/usr/bin/cmake -P /builddir/ktoblzcheck-1.50/build/src/bankdata/tmp.cmake` process gives no output so it seems to hang in some kind of deadlock.

Killed after 2 hrs: https://misc.voidlinux.de/binpkgs/bad.x86_64/ktoblzcheck

**Comment by Gottox** [comment]
If I run it with `-j 1` it hangs here: 

```
...
=> ktoblzcheck-1.50_1: running do_build ...
Scanning dependencies of target bankdata_de
[  5%] Download raw bank data file to /builddir/ktoblzcheck-1.50/src/bankdata/blz_20201217.txt
```

**Comment by Gottox** [comment]
Hmmm... that seems to be a local problem.

**Comment by pullmoll** [comment]
The download link in [`/builddir/ktoblzcheck-1.50/build/src/bankdata/tmp.cmake`](https://www.bundesbank.de/de/aufgaben/unbarer-zahlungsverkehr/serviceangebot/bankleitzahlen/download---bankleitzahlen-602592) seems to be wrong. I see the HTML page not the raw data which is probably expected.

**Comment by pullmoll** [comment]
This addition in template seems to make it work again:
```

pre_build() {
        vsed -i CMakeLists.txt -e "s;\(set(BANK_WEBSITE_PATH \).*;\1 /resource/blob/602632/f14f786eb69bd57a7
838bf9c8867fb6a/mL/blz-neu-txt-data.txt);"
}
```
But after 2021-03-07 it will probably break again.

**Comment by Gottox** [comment]
I disabled downloading all together: 

```diff
diff --git a/srcpkgs/ktoblzcheck/template b/srcpkgs/ktoblzcheck/template
index 14396134ad..3d21844a13 100644
--- a/srcpkgs/ktoblzcheck/template
+++ b/srcpkgs/ktoblzcheck/template
@@ -1,7 +1,7 @@
 # Template file for 'ktoblzcheck'
 pkgname=ktoblzcheck
 version=1.50
-revision=1
+revision=2
 hostmakedepends="pkg-config python"
 makedepends="python-devel"
 build_style=cmake
@@ -11,6 +11,7 @@ homepage="http://ktoblzcheck.sourceforge.net"
 short_desc="Tool for verification of account numbers and bank codes"
 distfiles="${SOURCEFORGE_SITE}/${pkgname}/${pkgname}-${version}.tar.gz"
 checksum=5cebeb144cd9f3e089325f919150000802aa0ad03aac13b273d797c6933a989f
+configure_args="-DENABLE_BANKDATA_DOWNLOAD=NO"
 
 ktoblzcheck-devel_package() {
        depends="${sourcepkg}>=${version}_${revision}"
```

**Comment by pullmoll** [comment]
You could update to 1.53 ...

**Comment by Gottox** [comment]
I think not downloading is the right way to do anyway, as it makes the pkg reproducable.
