### ISSUE TITLE
[package request] kustomize

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#27230]
Description: Customization of Kubernetes YAML configurations

https://github.com/kubernetes-sigs/kustomize
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kustomize-bin

**Comment by Gottox** [comment]
Isn't that already part of kubectl? `kubectl kustomize --help`

**Comment by eoli3n** [comment]
you're right, i didn't notice that, thanks
