### ISSUE TITLE
broken python package: pastebinit

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#27243]
### System

* xuname:  
  Void 5.9.14_1 x86_64 GenuineIntel/VM notuptodate rrrmFFF
* package:  
  pastebinit-1.5_4

### Expected behavior
pastebinit running and returning a link

### Actual behavior
```
Traceback (most recent call last):
  File "/bin/pastebinit", line 42, in <module>
    release = platform.linux_distribution()[0].lower()
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

### Steps to reproduce the behavior
install package and run 
```
echo "test" | pastebinit -b sprunge.us
```

**Comment by sgn** [comment]
Upstream Report https://bugs.launchpad.net/pastebinit/+bug/1835262

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/pull/27247

**Comment by eoli3n** [comment]
Works, thanks
