### ISSUE TITLE
firefox-i18n-fr installed, firefox still in english

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#27255]
### System

* xuname:  
  Void 5.9.14_1 x86_64 GenuineIntel/VM uptodate rrrmFFF
* package:  
  firefox-i18n-fr-84.0_1

### Expected behavior
firefox defaulty configured in french

### Actual behavior
firefox starts in english, and french is not disponible in languages menu.

### Steps to reproduce the behavior
just install the package.

**Comment by loreb** [comment]
I'm fine with firefox in English, but since nobody replied yet...

The expected behavior is inexcusably wrong - you may not have a shared computer, but they do exist, and it would really annoy other people using the same computer if it happened.

I would also expect the language in the languages menu, but it's not; it CAN be added installing from a file (deep down in /usr/lib/firefox); I have no idea if updates work this way, and the behavior **is** confusing.

**Comment by ericonr** [comment]
Ok, so I've noticed this issue when I was touching Thunderbird, but couldn't figure out what was missing.

It would be nice to fix it, tho.

**Comment by Chocimier** [comment]
Going to addons, then installing translation from disk works for now. No need to repeat on update.

**Comment by ericonr** [comment]
@Chocimier maybe we can add that to docs, at least?

**Comment by travankor** [comment]
>Going to addons, then installing translation from disk works for now. No need to repeat on update.

should the language packages be removed if this is the way forward?

**Comment by eoli3n** [comment]
it seems strange to me that this is so hard to fix. Could it be related to the way the package is build ?
- Archlinux [PKGBUILD](https://github.com/archlinux/svntogit-packages/blob/packages/firefox/trunk/PKGBUILD)
- Void [template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/firefox/template)

In PKGBUILD, some things which could be related to this, that i can't find in template:
- Alllow addon sideload : https://github.com/archlinux/svntogit-packages/blob/packages/firefox/trunk/PKGBUILD#L75
- Use LANG env var : https://github.com/archlinux/svntogit-packages/blob/packages/firefox/trunk/PKGBUILD#L153

**Comment by eoli3n** [comment]
From https://firefox-source-docs.mozilla.org/intl/locale.html#requested-locales
> After the sanitization, the value will be stored in a pref intl.locale.requested.

It seems that PKGBUILD does this as said before.
We can also read:
> If the developer wants to programmatically request the app to follow OS locales, they can assign null to requestedLocales.

**Comment by eoli3n** [comment]
Affects ``firefox-esr`` package too.

**Comment by eoli3n** [comment]
I can't build firefox package with default template: https://x0.at/wFT.txt
```
=> firefox-84.0_1: installing host dependencies: autoconf213-2.13_4 unzip-6.0_14 zip-3.0_6 pkg-config-0.29.2_2 perl-5.32.0_1 python3-3.9.1_1 yasm-1.3.0_2 rust-1.48.0_1 cargo-0.49.0_1 llvm-11.0.0_1 clang-11.0.0_1 nodejs-lts-10-10.23.0_1 cbindgen-0.15.0_1 python-2.7.18_2 nasm-2.15.05_1 which-2.21_3 tar-1.32_3 ...
=> firefox-84.0_1: installing target dependencies: nss-devel-3.59_1 libjpeg-turbo-devel-2.0.6_1 gtk+-devel-2.24.32_3 gtk+3-devel-3.24.24_1 icu-devel-67.1_1 pixman-devel-0.40.0_1 libevent-devel-2.1.12_1 libnotify-devel-0.7.9_1 libvpx-devel-1.9.0_1 libXrender-devel-0.9.10_2 libXcomposite-devel-0.4.5_1 libSM-devel-1.2.3_1 libXt-devel-1.2.0_1 rust-std-1.48.0_1 libXdamage-devel-1.1.5_1 freetype-devel-2.10.4_1 alsa-lib-devel-1.2.4_1 dbus-glib-devel-0.110_1 pulseaudio-devel-14.0_2 libXScrnSaver-devel-1.2.3_1 sndio-devel-1.7.0_3 jack-devel-1.9.16_1 ...
=> firefox-84.0_1: running pre-build hook: 02-script-wrapper ...
=> firefox-84.0_1: running do_build ...
 0:00.68 Failed to parse ccache stats output: secondary config (readonly)         /etc/ccache.conf
 0:05.75 Clobber not needed.
 0:05.76 Adding make options from /builddir/firefox-84.0/.mozconfig
    MOZ_OBJDIR=/builddir/firefox-84.0/obj-x86_64-unknown-linux-gnu
    OBJDIR=/builddir/firefox-84.0/obj-x86_64-unknown-linux-gnu
    FOUND_MOZCONFIG=/builddir/firefox-84.0/.mozconfig
    export FOUND_MOZCONFIG
 0:05.79 /usr/bin/make -f client.mk -s
 0:06.95 Elapsed: 0.83s; From dist/include: Kept 5815 existing; Added/updated 0; Removed 0 files and 0 directories.
 0:07.09 Elapsed: 0.00s; From dist/public: Kept 0 existing; Added/updated 0; Removed 0 files and 0 directories.
 0:07.22 Elapsed: 0.00s; From dist/private: Kept 0 existing; Added/updated 0; Removed 0 files and 0 directories.
 0:07.35 Elapsed: 0.00s; From dist/xpi-stage: Kept 5 existing; Added/updated 0; Removed 0 files and 0 directories.
 0:07.67 Elapsed: 0.19s; From _tests: Kept 577 existing; Added/updated 0; Removed 0 files and 0 directories.
 0:08.23 Elapsed: 0.43s; From dist/bin: Kept 2576 existing; Added/updated 0; Removed 0 files and 0 directories.
 0:08.28 ./buildid.h.stub
 0:08.51 ./source-repo.h.stub
 0:09.69 toolkit/library/rust/force-cargo-library-build
 0:16.38    Compiling xpcom v0.1.0 (/builddir/firefox-84.0/xpcom/rust/xpcom)
 0:31.93 error: could not compile `xpcom`
 0:31.94 Caused by:
 0:31.94   process didn't exit successfully: `/usr/bin/rustc --crate-name xpcom --edition=2018 xpcom/rust/xpcom/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 -C panic=abort -C embed-bitcode=no -C metadata=8e663ebdaf450182 -C extra-filename=-8e663ebdaf450182 --out-dir /builddir/firefox-84.0/obj-x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C linker=/builddir/firefox-84.0/build/cargo-linker -L dependency=/builddir/firefox-84.0/obj-x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/release/deps -L dependency=/builddir/firefox-84.0/obj-x86_64-unknown-linux-gnu/release/deps --extern libc=/builddir/firefox-84.0/obj-x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/release/deps/liblibc-13a0d9a00e0d07bb.rmeta --extern nserror=/builddir/firefox-84.0/obj-x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libnserror-63984d8617426e65.rmeta --extern nsstring=/builddir/firefox-84.0/obj-x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libnsstring-fbc9ba847dbb4634.rmeta --extern thin_vec=/builddir/firefox-84.0/obj-x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libthin_vec-2b13eb11d87d4d8a.rmeta --extern threadbound=/builddir/firefox-84.0/obj-x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/release/deps/libthreadbound-11d58741b2893b0e.rmeta --extern xpcom_macros=/builddir/firefox-84.0/obj-x86_64-unknown-linux-gnu/release/deps/libxpcom_macros-c17705735d405104.so -C opt-level=2 -C debuginfo=2 --cap-lints warn -Cembed-bitcode=yes -C codegen-units=1` (signal: 9, SIGKILL: kill)
 0:31.97 make[4]: *** [/builddir/firefox-84.0/config/makefiles/rust.mk:319: force-cargo-library-build] Error 101
 0:31.97 make[3]: *** [/builddir/firefox-84.0/config/recurse.mk:72: toolkit/library/rust/target] Error 2
 0:31.97 make[2]: *** [/builddir/firefox-84.0/config/recurse.mk:34: compile] Error 2
 0:31.97 make[1]: *** [/builddir/firefox-84.0/config/rules.mk:355: default] Error 2
 0:31.99 make: *** [client.mk:89: build] Error 2
 0:31.99 0 compiler warnings present.
 0:32.20 Failed to parse ccache stats output: secondary config (readonly)         /etc/ccache.conf
=> ERROR: firefox-84.0_1: do_build: './mach build' exited with 2
=> ERROR:   in do_build() at srcpkgs/firefox/template:172
```

**Comment by Anachron** [comment]
`signal: 9, SIGKILL: kill` --> You probably want to check if you're running out of resources.

**Comment by eoli3n** [comment]
Oh ok, i work in a VM, that's why, thanks

**Comment by Chocimier** [comment]
@eoli3n, thanks for findings.
We already have set [intl.locale.requested](https://github.com/void-linux/void-packages/blob/f9c4e6e09cf6f7a63835d70b9039344775530054/srcpkgs/firefox/files/vendor.js#L2) and only missing allow-addon-sideload. (But I do not have enough memory to check either.)

**Comment by ericonr** [comment]
@Chocimier how would adding it work? I can try on thunderbird

**Comment by eoli3n** [comment]
@Chocimier problem will be https://blog.mozilla.org/addons/2020/03/10/support-for-extension-sideloading-has-ended/

**Comment by Chocimier** [comment]
@ericonr, just drop `ac_add_options --allow-addon-sideload` into files/mozconfig.

**Comment by mvf** [comment]
> Going to addons, then installing translation from disk works for now. No need to repeat on update.

On my machines, language packs have to be manually reinstalled for every profile on every `firefox` update via XBPS.

**Comment by ericonr** [comment]
@Chocimier adding that into `files/mozconfig` makes it apply the language from the `LANG` env var, without having to follow any manual steps.

I will open an issue about applying it to all our mozilla stuff, and will include it in #26896

**Comment by pullmoll** [comment]
Oops! I didn't see this before updating firefox-esr to 78.6.1 .. should I stop builds and add that line to mozconfig?

**Comment by Chocimier** [comment]
@jnbr, could you include that change on next update? Thanks!

**Comment by jnbr** [comment]
yes, wil do

**Comment by eoli3n** [comment]
The problem still occurs with latest firefox update (95.0_1)

**Comment by artenaki** [comment]
> I'm fine with firefox in English

I've heard that French people don't like English language.

**Comment by Anachron** [comment]
Yep, it's in english for me as well even though I have german installed. This is a regression.

**Comment by Chocimier** [comment]
Do you see older version of language pack, or none at all on `about:addons`? If former, it's because pack at profile `extensions/` (probably manually installed) hides system one, and need to be removed.

**Comment by Anachron** [comment]
They were disabled because they were incompatible with Firefox 95.
I've clicked the gear icon and did "Check for Updates" and installed the updates and now my firefox is in german language again.

I think maybe it would be good to put this into the INSTALL.msg because this issue pops up quite often recently.

**Comment by eoli3n** [comment]
Upgraded to 95.0.1_1, firefox is in french after the restart. Does anything changed ? Or maybe that's because there is no new files in firefox-i18n ?

**Comment by Anachron** [comment]
Eoli3n did you try my suggestion from Dec 10th?

**Comment by eoli3n** [comment]
I already have that "check for updates" option checked in the gear menu.
But in any cases, firefox-i18n should be able to provide the right files.

**Comment by eoli3n** [comment]
Upgraded to 96, still... please reopen that issue

**Comment by ericonr** [comment]
I think you can reopen it yourself?

I'm using the built-in plugin and it's been working ok, but I'm not sure it's ideal.

**Comment by eoli3n** [comment]
If I ask, that's because I can't...

**Comment by ericonr** [comment]
Sorry, I thought it was always possible to reopen your own issues.

**Comment by Duncaen** [comment]
You could try the latest firefox release, I added some more addon related flags that arch enabled, otherwise I'm not sure how to solve this, maybe we should just drop the i18n packages.

**Comment by eoli3n** [comment]
For posterity https://github.com/void-linux/void-packages/commit/43366049eb57ad4cf7afad2cc05fd99eaf28f440
Already upgraded to that version, I don't remember to manually switch to fr this time, not sure, I will tell the next one :)

**Comment by eoli3n** [comment]
Upgrade to ff 97 = english after restart :cry:

**Comment by Chocimier** [comment]
Again: I am pretty sure it is manually installed translation overriding system one.

In new clean profile, is translation present? (`firefox -P`, then start with new profile. The profile selector is English only.)
If it is, try to remove translation from your main profile and restart browser.

**Comment by eoli3n** [comment]
When I create a new profile and start firefox with it, language is French.

**Comment by eoli3n** [comment]
At each upgrade, I still get the issue.

**Comment by eoli3n** [comment]
I'll try.
But still, why is that not a problem on my arch host ?

**Comment by classabbyamp** [comment]
is this still occurring?

**Comment by eoli3n** [comment]
Nop, thanks
