### ISSUE TITLE
Enable CONFIG_MOUSE_ELAN_I2C_SMBUS and CONFIG_MOUSE_PS2_ELANTECH_SMBUS

### ISSUE THREAD

**Issue by vikigenius** [void-linux/void-packages#27274]
Hi, today when i was browsing my system logs, I just came across these messages.

```
[ 6.596851] psmouse serio1: elantech: The touchpad can support a better bus than the too old PS/2 protocol. Make sure MOUSE_PS2_ELANTECH_SMBUS and MOUSE_ELAN_I2C_SMBUS are enabled to get a better touchpad experience.
```

Would it be possible to enable these kernel options ?

**Comment by ericonr** [comment]
Closed in b5d3cb14da13bc65010de7e62a4627320a8c61dd ,  you will see it in effect next update.

I enabled it for all 5.x kernels.
