### ISSUE TITLE
Can't install the Sublime text 3

### ISSUE THREAD

**Issue by LambLeeg** [void-linux/void-packages#27344]
### System
Void 5.9.14_1 x86_64 GenuineIntel notuptodate rFF
* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
sublime-text3 (nonfree server)
### Expected behavior
installation of the code app, sublime-text3
### Actual behavior
![image](https://user-images.githubusercontent.com/59935189/102853309-1ae16f00-4431-11eb-8673-37f7f40c3c9d.png)

**Comment by abenson** [comment]
The template needs to be updated, but for now you should just be able to install the package from the mirror.

`xbps-install -S void-repo-nonfree ; xbps-install -S sublime_text3`

**Comment by LambLeeg** [comment]
> The template needs to be updated, but for now you should just be able to install the package from the mirror.
> 
> `xbps-install -S void-repo-nonfree ; xbps-install -S sublime-text3`

Thanks, I really installed it from nonfree, thanks to Void community in Telegram. Also, thank you for responding.
