### ISSUE TITLE
Package Request : Abrowser

### ISSUE THREAD

**Issue by r0m3chco** [void-linux/void-packages#2735]
Abrowser (Trisquel's firefox)

https://trisquel.info/en/wiki/abrowser-help

I don't find source, archlinux AUR build this package too..

Thanks!

**Comment by Hoshpak** [comment]
There's already icecat available in the repository which is another unbranded Firefox. I don't think we need another Firefox fork.

**Comment by r0m3chco** [comment]
Icecat is based on firefox ESR, 
Abrowser on firefox

**Comment by Hoshpak** [comment]
Doesn't change the fact that it's yet another firefox fork. No additional forks of either Firefox or Chromium are accepted into the repository.

**Comment by r0m3chco** [comment]
Ok

**Comment by cr6git** [comment]
For the same reason [Waterfox](https://github.com/void-linux/void-packages/issues/515) probably will never be accepted...

**Comment by cr6git** [comment]
> I don't find source, archlinux AUR build this package too..

As you can see, Abrowser in [AUR](https://aur.archlinux.org/packages/abrowser-bin/) is not built from source, it's just a .deb package that is extracted and repackaged...

**Comment by r0m3chco** [comment]
That's right

**Comment by maxice8** [comment]
Considering this is just another Firefox 99% the same thing with some stuff changed and to compound the experience only available as a .deb which is extracted i think it is pretty safe to close this.
