### ISSUE TITLE
 `chez-scheme` can't be used to build `idris2` on `musl` Void

### ISSUE THREAD

**Issue by VoidNoire** [void-linux/void-packages#27378]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
Void 5.9.14_1 x86_64-musl AuthenticAMD uptodate rF
  
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
chez-scheme-9.5.4_1

### Expected behavior
Step 4 of [these steps](https://github.com/idris-lang/Idris2/blob/master/INSTALL.md) to [build `idris2` from source](https://www.idris-lang.org/idris2-src/idris2-latest.tgz) succeeds.

### Actual behavior
Step 4 fails.

### Steps to reproduce the behavior
```Shell
sudo xbps-install -S chez-scheme
curl -O https://www.idris-lang.org/idris2-src/idris2-latest.tgz
tar xf idris2-latest.tgz
cd Idris2-0.2.1
# Step 1 of the `idris2` build steps.
export PATH="$HOME/.idris2/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/.idris2/lib:$LD_LIBRARY_PATH"
# Step 2 of the `idris2` build steps.
make bootstrap SCHEME=scheme
make install
# Step 4 of the `idris2` build steps. Step 3 was skipped since that only applies when step 2 isn't done.
make clean
make all && make install
```
### Other  information
We can confirm that the issue is caused by Void's `chez-scheme` package by using the `chez` package from `nix` instead, which works:

```Shell
sudo xbps-install -S nix
sudo ln -s /etc/sv/nix-daemon /var/service/
sudo sv start nix-daemon
# Add the unstable channel for `nix`.
nix-channel --add https://nixos.org/channels/nixpkgs-unstable
# Get the nix expressions from the channel.
nix-channel --update
# Install the `chez` package with `musl` compatibility.
nix-env -f channel:nixos-unstable -iA pkgsCross.musl64.chez
# Install the `idris2` package with `musl` compatibility.
nix-env -f channel:nixos-unstable -iA pkgsCross.musl64.idris2
curl -O https://www.idris-lang.org/idris2-src/idris2-latest.tgz
tar xf idris2-latest.tgz
cd Idris2-0.2.1
# Step 1 of the `idris2` build steps.
export PATH="$HOME/.idris2/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/.idris2/lib:$LD_LIBRARY_PATH"
# Step 3 of the `idris2` build steps. Step 2 was skipped since we're building with an existing `idris2`.
make all
make install
# Step 4 of the `idris2` build steps.
make clean
make all && make install
```
For convenience, [here's a link to the `chez` nix expression](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/compilers/chez/default.nix). One difference I can see between that and [Void's `chez-scheme` xbps template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/chez-scheme/template) is that the latter's `configure` step doesn't use the `--threads` flag, whereas the former's does, although I'm unsure if that's the cause of the failure.

@leahneukirchen

**Comment by leahneukirchen** [comment]
Please post the error messages, and if you try to reproduce on another system, also do the same steps there (i.e. step 2).

**Comment by leahneukirchen** [comment]
I already get reordering errors on step 2.

**Comment by leahneukirchen** [comment]
We pass thread support via the machine name already.

**Comment by VoidNoire** [comment]
> Please post the error messages, and if you try to reproduce on another system, also do the same steps there (i.e. step 2).

Ah sorry, will do. I'm currently trying to reproduce step 2 with the `nix` set up.

> We pass thread support via the machine name already.

Ah yeah, you're right. That's the "t" in `ta6le`, right?

**Comment by leahneukirchen** [comment]
> Ah yeah, you're right. That's the "t" in `ta6le`, right?

Yes.

**Comment by VoidNoire** [comment]
> I already get reordering errors on step 2.

Ah it's the same for me with the `nix` set up. I guess it's an issue with the `idris2` build process and not with Void's `chez-scheme` package then. Sorry for the hassle! I'll close the issue now.

**Comment by leahneukirchen** [comment]
I think it's related to stdio buffering differences, but yes, this is an upstream topic.
