### ISSUE TITLE
Anki 2.1.4 is broken

### ISSUE THREAD

**Issue by TeddyDD** [void-linux/void-packages#2738]
* xuname: Void 4.17.19_1 x86_64 GenuineIntel uptodate rFFFFFFF
* package: anki-2.1.4_1

#### Problem

Program shoud launch but instead returns error
```
Traceback (most recent call last):
  File "/bin/anki", line 3, in <module>
    import aqt
ModuleNotFoundError: No module named 'aqt'
```

#### Steps to reproduce
- install anki-2.1.4_1
- run Anki from terminal

**Comment by Johnnynator** [comment]
#2733 afaik should fix this. Maybe you could test it.

**Comment by KRSHK** [comment]
I have the same problem. I tried to reinstall it in case, and I got the following

```
Byte-compiling python code in /usr/share/anki/anki...
Compiling /usr/share/anki/anki/mpv.py ...
  File "/usr/share/anki/anki/mpv.py", line 546
    def command(self, *args, timeout=1):
                                   ^
SyntaxError: invalid syntax

Byte-compiling python code in /usr/share/anki/aqt...
Compiling /usr/share/anki/aqt/__init__.py ...
  File "/usr/share/anki/aqt/__init__.py", line 265
    def _run(argv=None, exec=True):
                           ^
SyntaxError: invalid syntax

Compiling /usr/share/anki/aqt/browser.py ...
  File "/usr/share/anki/aqt/browser.py", line 959
    return lambda *, f=args: self.setFilter(*f)
                   ^
SyntaxError: invalid syntax

Updating ldconfig(8) cache...
anki-2.1.4_1: installed successfully.
```

**Comment by cr6git** [comment]
https://github.com/void-linux/void-packages/commit/89115a717183c8712eb8ca2d1887312b31934f52

**Comment by CameronNemo** [comment]
If anyone has tips to fix the byte compilation errors, I am all ears. I haven't dug in because anki appeared to function despite the errors.

**Comment by TeddyDD** [comment]
#2733 fixed this for me, @KRSHK could you check it as well? If everything is ok, I think this can be closed.

**Comment by maxice8** [comment]
Should be fixed by https://github.com/void-linux/void-packages/commit/e22b8204bb744e331e86cd9fdf7b8ed9e2c07078

**Comment by KRSHK** [comment]
The last update fixed everything (the byte compilation errors too)
