### ISSUE TITLE
Default firefox settings

### ISSUE THREAD

**Issue by anjandev** [void-linux/void-packages#27419]
So firefox's default settings are not the most privacy respecting:

- google is the default search engine
- Firefox studies enabled
- Telemetry enabled

All of these dont affect usability of firefox but they do affect privacy a great deal.

The people over at postmarketos have a `mobile-config-firefox` package that is installed automatically when the user installs firefox. 

https://gitlab.com/postmarketOS/mobile-config-firefox

This package changes alot of those settings to be more privacy respecting and I appreciate not having to dig through settings on every new firefox install to change those settings. The user can of course uninstall this package to get a vanilla firefox experience.

I was wondering if we could take a similar approach to firefox in void linux's repositories. 

Thanks for your hard work maintainers!

**Comment by tibequadorian** [comment]
I believe this is a bad idea because packages should be as close to upstream as possible. 
If maintainers consider to add such a package, please do not make it the default.

**Comment by anjandev** [comment]
I think that is a good point. I stopped using gnu icecat because the browser was very much out of date when compared to regular firefox. I just tried it out again and icecat is now 78.6.0. 

Im closing this issue. If you care about these settings and want to protect your privacy, I recommend just installing gnu icecat.

**Comment by Piraty** [comment]
as this is something that needs to be applied to the firefox profiles in your homedir, there's not chance Void will touch that.
there are generators for firefox profiles out there (for example: https://ffprofile.com/) that help you do this

**Comment by q66** [comment]
I think packaging this does not seem too bad, actually 

it seems it does not affect ordinary firefox at all and would be something people can just optionally install
