### ISSUE TITLE
98-fixup-gir-path: ugly hack that needs to be fixed

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#27437]
With @q66 working on cleaning up the lib32/lib64 issues with our cross toolchains and me trying them on my [`musl-1.2.1`](https://github.com/pullmoll/void-packages/commits/musl-1.2.1) branch this old and ugly hack started to fail because the `cp -a` would try to copy a directory over a symbolic link.

I managed to make this hack even uglier, i.e. hacked the ill conceived hack to somehow work again, while really the underlying issue needs to be solved.

See https://github.com/pullmoll/void-packages/commit/b52e90e61300559c45a3e0efee0a10d96097f7fc for the gory details.

I hope someone finds time and is sufficiently skilled to see where the original issue stems from.
/me am not.

Edit: WTF upload MP4 and MOV? Where is github moving to?

**Comment by newbluemoon** [comment]
The culprit seems to be the `INTROSPECTION_GIRDIR` and `INTROSPECTION_TYPELIBDIR` variables in every `Makefile` which are set using the pkg-config-wrapper in `configure` via:
```
INTROSPECTION_GIRDIR=`$PKG_CONFIG --define-variable=datadir="${_GI_EXP_DATADIR}" --variable=girdir gobject-introspection-1.0`
INTROSPECTION_TYPELIBDIR="$($PKG_CONFIG --define-variable=libdir="${_GI_EXP_LIBDIR}" --variable=typelibdir gobject-introspection-1.0)"
```
which adds `$XBPS_CROSS_BASE`.

I don’t really have a solution, just a different hack: run
```
sed -e "s,^\(INTROSPECTION_GIRDIR\s*=\s*\)${XBPS_CROSS_BASE}\(.*\),\1\2," -i $(find . -name Makefile)
sed -e "s,^\(INTROSPECTION_TYPELIBDIR\s*=\s*\)${XBPS_CROSS_BASE}\(.*\),\1\2," -i $(find . -name Makefile)
```
between the `build` and `install` phase; either by replacing the hack in the `98-fixup-gir-path.sh`-hook or e.g. in a custom `pre_install()` (and removing the hook).

I haven’t tested if these variables are relevant for building the package, yet; if not then a clean solution could be adjusting the pkg-config-wrapper to not add `$XBPS_CROSS_BASE` to `girdir` and `typelibdir` queries.

**Comment by pullmoll** [comment]
Thank you @newbluemoon for looking into it. Your stream edits work better than my hack and I'll use the for now.

**Comment by pullmoll** [comment]
And still need to move (other) files which are installed to this wrong path.
The latest patch in [my branch](https://github.com/pullmoll/void-packages/commits/musl-1.2.1) now seems to be working. I can cross build packages which were failing e.g. qscintilla-qt5.

**Comment by pullmoll** [comment]
After seeing many problems arise when the `98-fixup-gir-path` script modified the Makefiles, I went back to copying the wrong path to the correct one.

When I modify the Makefiles this (for some packages) leads to them detecting the modification time being greater than that the configure script and want to re-run autoconf. I already did add `automake` to a few packages but even that sometimes isn't sufficient, and it sometimes leads to the **whole packge** being rebuilt - without `${makejobs}` because it happens in the `do_install()` where there usually is no `${makejobs}` in the make command.

So to make a long story short: there is still no good solution for the problem, just inherently poor workarounds.

**Comment by newbluemoon** [comment]
What about preventing that `$XBPS_CROSS_BASE` ends up in `INTROSPECTION_GIRDIR` and `INTROSPECTION_TYPELIBDIR` in the first place; i.e. not setting `PKG_CONFIG_SYSROOT_DIR` in the pkg-config wrapper when these variables are queried, like e.g. below and removing `98-fixup-gir-path.sh`?

```
diff --git a/common/hooks/pre-configure/02-script-wrapper.sh b/common/hooks/pre-configure/02-script-wrapper.sh
index fe2000af11..2c978c4977 100644
--- a/common/hooks/pre-configure/02-script-wrapper.sh
+++ b/common/hooks/pre-configure/02-script-wrapper.sh
@@ -87,7 +87,10 @@ pkgconfig_wrapper() {
 	cat >>${XBPS_WRAPPERDIR}/${XBPS_CROSS_TRIPLET}-pkg-config<<_EOF
 #!/bin/sh
 
-export PKG_CONFIG_SYSROOT_DIR="$XBPS_CROSS_BASE"
+case \$@ in
+	*--variable=gir*|*--variable=typelib*) ;;
+	*) export PKG_CONFIG_SYSROOT_DIR="$XBPS_CROSS_BASE" ;;
+esac
 export PKG_CONFIG_PATH="$XBPS_CROSS_BASE/usr/lib/pkgconfig:$XBPS_CROSS_BASE/usr/share/pkgconfig\${PKG_CONFIG_PATH:+:\${PKG_CONFIG_PATH}}"
 export PKG_CONFIG_LIBDIR="$XBPS_CROSS_BASE/usr/lib/pkgconfig\${PKG_CONFIG_LIBDIR:+:\${PKG_CONFIG_LIBDIR}}"
 exec /usr/bin/pkg-config "\$@"
```

**Comment by sgn** [comment]
Can I see a list of problematic packages? I tried to build those packages that have `automake` added (reverted, of course) but all of them works :(

**Comment by newbluemoon** [comment]
I used polkit as example. But all packages using gobject-introspection should be affected.

**Comment by ericonr** [comment]
@sgn nemo in cinnamon (#26965 ) is getting errors now

**Comment by pullmoll** [comment]
@ericonr @sgn yes, that's the type of error I have been seeing in my musl-1.2.1 branch.
It obviously starts to appear in master now, too. The latest `98-fixup-gir-path.sh` I have works around this but is still hacky.

I'll try @newbluemoon  's suggestion as soon as I find some time, perhaps tonight.

**Comment by sgn** [comment]
I think we can replace this hack by another hack, e.g. symlink `$DESTDIR//usr/$XBPS_CROSS_TRIPLET/usr` to `/usr` in `pre_install` and remove it in `post_install`.

**Comment by ericonr** [comment]
@sgn's solution seems to work, I will try some more packages here.
