### ISSUE TITLE
volume applet on GNOME, brightness level, and bluetooth

### ISSUE THREAD

**Issue by free-tinker** [void-linux/void-packages#27440]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
gnome-3.38.0_2
### Actual behavior
I can't control volume on the GNOME DE, because there is no volume applet symbol but the level bar does appear.
So I have to control the volume from alsamixer.
The brightness level always got reset after reboot.
Bluetooth back to turned on after reboot.

**Comment by HadetTheUndying** [comment]
How did you install gnome? Which services did you enable after the gnome install? Following the handbookI just did a fresh install in a virtual machine to try to reproduce the behavior with the volume applet but it is there and working correctly.

**Comment by travankor** [comment]
might be fixed with elogind update

**Comment by free-tinker** [comment]
@HadetTheUndying  I was following the handbook for the installation and also for enabling the service (gdm, elogind, dbus). I did the installation on a laptop.
@travankor some say so in a forum.

**Comment by Gottox** [comment]
Can you check if pulseaudio is running correctly?

**Comment by ericonr** [comment]
elogind has been updated as well.

**Comment by free-tinker** [comment]
It works now.
Thank you for responses
