### ISSUE TITLE
KDE4/Qt4 packages present in the repo that were removed from srcpkgs/

### ISSUE THREAD

**Issue by maxice8** [void-linux/void-packages#2746]
And their subpackages.

- [ ] kdepimlibs
- [ ] kdepimlibs-devel
- [ ] kdepim
- [ ] kde
- [ ] baloo
- [ ] baloo-devel
- [ ] baloo-widgets
- [ ] baloo-widgets-devel 
- [ ] kde-runtime
- [ ] kde-runtime-devel
- [ ] kde-baseapps
- [ ] kde-baseapps-devel
- [ ] kuser
- [ ] kdeplasma-addons
- [ ] kdeplasma-addons-devel
- [ ] marble
- [ ] marble-devel
- [ ] kdelibs
- [ ] kdelibs-devel
- [x] libkdcraw
- [x] libkdcraw-devel
- [ ] libkexiv2
- [ ] libkexiv2-devel
- [ ] kdevplatform
- [ ] kdevplatform-devel
- [ ] libkipi
- [ ] libkipi-devel
- [ ] kdegraphics-thumbnailers
- [ ] kdeartwork
- [ ] kate
- [ ] kate-devel
- [ ] kactivities
- [ ] kactivities-devel
- [ ] knemo
- [ ] polkit-kde
- [ ] polkit-kde-agent
- [ ] kde-gtk-config
- [ ] subversion-kwallet-auth
- [ ] lightdm-kde-greeter
- [ ] kde-l10n-ar
- [ ] kde-l10n-bg
- [ ] kde-l10n-bs
- [ ] kde-l10n-ca
- [ ] kde-l10n-cavalencian
- [ ] kde-l10n-cs
- [ ] kde-l10n-da
- [ ] kde-l10n-de
- [ ] kde-l10n-el
- [ ] kde-l10n-engb
- [ ] kde-l10n-es
- [ ] kde-l10n-et
- [ ] kde-l10n-eu
- [ ] kde-l10n-fa
- [ ] kde-l10n-fi
- [ ] kde-l10n-fr
- [ ] kde-l10n-ga
- [ ] kde-l10n-gl
- [ ] kde-l10n-he
- [ ] kde-l10n-hi
- [ ] kde-l10n-hr
- [ ] kde-l10n-hu
- [ ] kde-l10n-ia
- [ ] kde-l10n-id
- [ ] kde-l10n-is
- [ ] kde-l10n-it
- [ ] kde-l10n-ja
- [ ] kde-l10n-kk
- [ ] kde-l10n-km
- [ ] kde-l10n-ko
- [ ] kde-l10n-lt
- [ ] kde-l10n-lv
- [ ] kde-l10n-mr
- [ ] kde-l10n-nb
- [ ] kde-l10n-nds
- [ ] kde-l10n-nl
- [ ] kde-l10n-nn
- [ ] kde-l10n-pa
- [ ] kde-l10n-pl
- [ ] kde-l10n-pt
- [ ] kde-l10n-ptbr
- [ ] kde-l10n-ro
- [ ] kde-l10n-ru
- [ ] kde-l10n-sk
- [ ] kde-l10n-sl
- [ ] kde-l10n-sr
- [ ] kde-l10n-sv
- [ ] kde-l10n-tr
- [ ] kde-l10n-ug
- [ ] kde-l10n-uk
- [ ] kde-l10n-wa
- [ ] kde-l10n-zhcn
- [ ] kde-l10n-zhtw

**Comment by maxice8** [comment]
@void-linux/pkg-committers need someone that can manage the repo indexes to remove these packages.

**Comment by Hoshpak** [comment]
`x86_64*` and `i686` are staging now:

```
Inconsistent shlibs:
  libHalf.so.23 (provided by: ilmbase; used by: kdelibs)
```

This package should be removed as soon as possible.

**Comment by maxice8** [comment]
On Wed, Oct 03, 2018 at 01:08:14AM -0700, Helmut Pozimski wrote:
> `x86_64*` and `i686` are staging now:
> 
> ```
> Inconsistent shlibs:
>   libHalf.so.23 (provided by: ilmbase; used by: kdelibs)
> ```
> 
> This package should be removed as soon as possible.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/2746#issuecomment-426548055

I made a request on #xbps

**Comment by nonchip** [comment]
yup this just broke `-Su`:

```
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/debug/x86_64-repodata' ...
kdelibs-4.14.3_10: broken, unresolvable shlib `libHalf.so.23'
kdelibs-4.14.3_10: broken, unresolvable shlib `libIex-2_2.so.23'
kdelibs-4.14.3_10: broken, unresolvable shlib `libIlmImf-2_2.so.22'
mozjs38-38.8.0_6: broken, unresolvable shlib `libicui18n.so.59'
mozjs38-38.8.0_6: broken, unresolvable shlib `libicuuc.so.59'
Transaction aborted due to unresolved shlibs.
```

**Comment by Johnnynator** [comment]
@nonchip Remove these packages (probably just removing all orphans is probably enough `xbps-remove -o`)

**Comment by nonchip** [comment]
@Johnnynator ok yeah that helped thanks, i keep forgetting about the `-o` switch :P

**Comment by maxice8** [comment]
> yup this fix just broke -Su:

No, these packages weren't present for a long time in the repos and weren't being updated with the rest of the system, they were going to break (and broke actually) with the first shlib bump done.

**Comment by Gottox** [comment]
polkit-kde-agent is a false positive.

**Comment by maxice8** [comment]
This is deprecated in favour of https://github.com/void-linux/void-packages/issues/2854
