### ISSUE TITLE
wxWidgets: missing /usr/include/wx/setup.h (moved)

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#27495]
With one of the recent updates the file `/usr/include/wx/setup.h` is no longer there in `wxWidgets-gtk3-devel`. It moved to `/usr/lib/wx/include/gtk3-unicode-3.0/wx/setup.h` yet packages depending on wxWidgets, e.g. mediainfo or wxPython, want to include just `#include "wx/setup.h"`.

For `wxWidgets-devel` the file is moved to `/usr/lib/wx/include/gtk2-unicode-3.0/wx/setup.h`.

IDK if it would make sense to create a symbolic link to the respective file for both, gtk2 and gtk3, devel versions so that packages depending on either will find `setup.h` where it used to be?

Then the two devel packages would need to conflict, i.e. no dependency on gtk2 **and** gtk3 devel packages in one package.

Or would it be better to add the `/usr/lib/wx/include/gtkX-unicode-3.0/` path to the pkgconfig and/or cmake include paths?

**Comment by pullmoll** [comment]
I just realized it is because of the `/usr/lib32` and `/usr/lib64` split that the header is not found.

**Comment by ericonr** [comment]
Ugh, I hit this the kicad update https://github.com/void-linux/void-packages/pull/28239/checks?check_run_id=1770122209#step:8:212

Will try to fix.

>  /usr/lib/wx/include/gtk2-unicode-3.0/wx/setup.h

I have to say, this location seems a bit wrong.

**Comment by ericonr** [comment]
Indeed you are right about lib64/lib32: `-I /usr/armv7l-linux-musleabihf/lib64/wx/include/gtk3-unicode-3.0 -I /usr/armv7l-linux-musleabihf/include/wx-3.0`

**Comment by ericonr** [comment]
My initial idea is just sed'ing out `lib$wordsize` for `lib`, but idk if that can break something. So I will put it in the kicad PR and we can decide on it/

**Comment by ericonr** [comment]
@pullmoll I've got a solution in #28239 now, let me know what you think.

**Comment by ericonr** [comment]
@pullmoll I think it would be good to patch the non gtk one as well, right?

**Comment by pullmoll** [comment]
@ericonr definitely. The packages should use the `…/lib/wx/include…` path as the specialization to lib32 or lib64 not relevant for the location  of the header file.
