### ISSUE TITLE
RPATH set in qjackctl breaks pw-jack

### ISSUE THREAD

**Issue by st3r4g** [void-linux/void-packages#27494]
### System

* xuname:  
  Void 5.9.16_1 x86_64 AuthenticAMD notuptodate rFFFFFFFF
* package:  
  qjackctl-0.9.0_1

```
$ chrpath -l /usr/bin/qjackctl 
/usr/bin/qjackctl: RPATH=/usr/lib
```
This overrides the effect of adding `/usr/lib/pipewire-0.3/jack` to `LD_LIBRARY_PATH` done by `pw-jack`, so `qjackctl` still links to the `libjack` in `/usr/lib`.

**Comment by sgn** [comment]
It looks like all qmake target suffers from this problem. `qtikz` is another one.

**Comment by st3r4g** [comment]
fixed by #28581

**Comment by sgn** [comment]
@st3r4g Do you have old distfiles for qjackctl?

**Comment by st3r4g** [comment]
I have `qjactctl-0.9.1.tar.gz`

**Comment by sgn** [comment]
checksum for qjackctl 0.9.2 was changed. I'm trying to see what changed.
