### ISSUE TITLE
Localization files in /usr/lib/locale

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#27491]
The correct `localedir` is `/usr/share/locale`, which is respected on all glibc packages. Unfortunately, on musl some packages perform their own detection of what `localedir` to use, due to some really weird mechanisms, and end up putting those files into `/usr/lib/locale`. Since locale data isn't arch specific, it should be stored in `/usr/share`. For multilib systems, this also makes it so locale data only has to be installed once, in `/usr/share`, by the native package.

@q66 scraped his repo for packages with files in `/usr/lib/locale`, which should be fixed, unless there are specific circumstances (`pcsx2` is one such example, since it can't be installed at all on 64-bit systems).

- [x] appdata-tools (removed in 1b2e92128ec7ba97e41bf7f41d91273253bea052)
- [x] ario
- [x] brasero
- [x] desmume #27782 
- [x] dia
- [x] exo
- [x] garcon
- [x] GConf
- [x] gconf-editor
- [x] gdmap
- [x] geeqie
- [x] gimp (can be fixed with 3.0 when it releases, since that supports meson)
- [x] gimp-lqr-plugin
- [x] gmpc
- [x] gnome-doc-utils
- [x] gnome-mime-data
- [x] gnome-mplayer
- [x] gnome-nettool
- [x] gnome-screensaver
- [x] gnome-system-log
- [x] gnumeric
- [x] goocanvas1 (will be removed in #27438 )
- [x] gpicview
- [ ] gtk+
- [x] gtk2-engines
- [x] gtkpod
- [x] gtksourceview2
- [x] gtkspell
- [x] gxmessage
- [x] homebank
- [x] leafpad
- [x] libcryptui
- [x] libglib-static (removed in 2c6bde11ad4fb27a752b8f9d73f928e28fe4934e)
- [x] libgnomecanvas
- [x] libgnome-keyring
- [x] libgpod
- [x] libwnck2
- [x] libxfce4ui
- [x] libxfce4util
- [x] lightdm-gtk-greeter
- [x] lxappearance-obconf
- [x] lxinput
- [x] lxlauncher
- [x] mousepad
- [x] orage
- [x] parcellite
- [x] parole
- [x] pcmanx-gtk2
- [x] pidgin-libnotify
- [x] pidgin-otr
- [x] pidgin-privacy-please
- [x] pmount
- [x] polkit-gnome
- [x] pragha
- [x] ristretto
- [x] seahorse-nautilus
- [x] seahorse-sharing
- [x] spacefm
- [x] Thunar
- [x] thunar-archive-plugin
- [x] thunar-media-tags-plugin
- [x] thunar-volman
- [x] tilp2
- [x] tumbler
- [x] udevil
- [x] ufraw
- [x] uget
- [x] viking
- [x] volumeicon
- [x] vte #27556 
- [x] vte290
- [x] xdg-user-dirs-gtk
- [x] xfburn
- [x] xfce4-appfinder
- [x] xfce4-battery-plugin
- [x] xfce4-clipman-plugin
- [x] xfce4-cpufreq-plugin
- [x] xfce4-cpugraph-plugin
- [x] xfce4-dict
- [x] xfce4-diskperf-plugin
- [x] xfce4-fsguard-plugin
- [x] xfce4-genmon-plugin
- [x] xfce4-mailwatch-plugin
- [x] xfce4-mpc-plugin
- [x] xfce4-netload-plugin
- [x] xfce4-notifyd
- [x] xfce4-panel
- [x] xfce4-places-plugin
- [x] xfce4-power-manager
- [x] xfce4-pulseaudio-plugin
- [x] xfce4-screenshooter
- [x] xfce4-sensors-plugin
- [x] xfce4-session
- [x] xfce4-settings
- [x] xfce4-systemload-plugin
- [x] xfce4-taskmanager
- [x] xfce4-terminal
- [x] xfce4-time-out-plugin
- [x] xfce4-timer-plugin
- [x] xfce4-verve-plugin
- [x] xfce4-wavelan-plugin
- [x] xfce4-weather-plugin
- [x] xfce4-xkb-plugin
- [x] xfconf
- [x] xfdesktop
- [x] xfwm4
- [x] xnoise
- [x] xournal
- [x] xsane

**Comment by newbluemoon** [comment]
I did have a look at geeqie and assume most of the listed packages above share the same issue.
It seems the problems lies in `/usr/share/aclocal/glib-gettext.m4`, line 275:
```
	  AC_TRY_LINK(, [extern int _nl_msg_cat_cntr;
			 return _nl_msg_cat_cntr],
	    [CATOBJEXT=.gmo 
             DATADIRNAME=share],
	    [case $host in
	    *-*-solaris*)
	    dnl On Solaris, if bind_textdomain_codeset is in libc,
	    dnl GNU format message catalog is always supported,
            dnl since both are added to the libc all together.
	    dnl Hence, we'd like to go with DATADIRNAME=share and
	    dnl and CATOBJEXT=.gmo in this case.
            AC_CHECK_FUNC(bind_textdomain_codeset,
	      [CATOBJEXT=.gmo 
               DATADIRNAME=share],
	      [CATOBJEXT=.mo
               DATADIRNAME=lib])
	    ;;
	    *-*-openbsd*)
	    CATOBJEXT=.mo
            DATADIRNAME=share
	    ;;
	    *)
	    CATOBJEXT=.mo
            DATADIRNAME=lib
	    ;;
	    esac])
```

Musl doesn’t have `_nl_msg_cat_cntr`, the test fails, and so `CATOBJEXT` is set to `.mo`.

Then in line 451:
```
if test "x$CATOBJEXT" = "x.mo" ; then
  localedir=`eval echo "${libdir}/locale"`
else
  localedir=`eval echo "${datadir}/locale"`
fi
```

So the translations are put into `libdir`.
Even adding `--localedir=/usr/share/locale` to `configure_args` didn’t change this.

The easiest way to solve this might be to patch `glib-gettext.m4` and just change `${libdir}/locale` to `${datadir}/locale`.
However, no idea if there might me side effects. ;)

**Comment by newbluemoon** [comment]
Patching `glib-gettext.m4` (alone) might not be that good an idea because it would require the package to regenerate the `configure` script which needs all the automake stuff added to `hostmakedepends` etc. It works for geeqie because it has to run an `autogen.sh` in `pre_configure()` and does it anyway.

Would a configure hook scanning for `localdir` in `configure` scripts be any good?

**Comment by sgn** [comment]
Maybe link to `libintl` unconditionally on musl?

**Comment by ericonr** [comment]
I'm very much against forcing `libintl` when it isn't necessary...

@newbluemoon I believe `--with-localedir` was reported to work...

**Comment by newbluemoon** [comment]
At least for geeqie `--with-localedir` doesn’t work either. If it would it could just be added to `common/environment/configure/gnu-configure-args.sh`...

**Comment by ericonr** [comment]
`--with-locale-dir`, actually. Sorry for the confusion.

**Comment by newbluemoon** [comment]
No, doesn’t work with geeqie; `AM_GLIB_DEFINE_LOCALEDIR` doesn’t check if `$localedir` is already set – it just overwrites it regardless. But that might not be the case with the other packages; they might have added some more checks. I’ll do some testing.

**Comment by q66** [comment]
`--with-locale-dir` is specific to xfce stuff

**Comment by sgn** [comment]
`--with-locale-dir` doesn't work for Thunar 4.16.1

**Comment by newbluemoon** [comment]
I tried geeqie, dia, and leafpad. There `$localedir` is always hardcoded in the end. I have some fixes on a per package basis ready for those, but maybe a general approach is desired (maybe thats only feasible for the Xfce stuff)?

**Comment by q66** [comment]
the m4 files causing this should be fixed either way since they may be used for user built stuff and we don't want that in there either

and then for packages we need to fix it on per-package basis (I see no other way) and introduce a pkglint check to add /usr/lib/locale into forbidden directories (except for glibc-locales)

**Comment by sgn** [comment]
For xfce4 stuff, it's defined by `XDT_I18N` from `xfce4-dev-tools`, it can be fixed by `--with-locales-dir=/usr/share/locale`.
For other stuffs, I don't think we can fix in general, except patching `/usr/share/aclocal/glib-gettext.m4` from `glib-devel` and run `autoreconf -fi` for all problematic packages.

**Comment by q66** [comment]
so we should ix `xfce4-dev-tools` as well as `glib-devel`, then for xfce4 packages apply `--with-locales-dir`, for the others we can probably patch the right pattern in their configure scripts, don't have to necessarily re-generate everything

**Comment by sgn** [comment]
Doing this and now I realized that we should just
```sh
vsed -i '/localedir =/s,=.*,= /usr/share/locale,' po/Makefile.in.in
```

**Comment by ericonr** [comment]
@sgn that only fixes install location, not where the programs will search for locale data.

If anything, my fix from #27511 might work better.

**Comment by sgn** [comment]
We need to run `autoreconf -fi` for:
```
-DPACKAGE_LOCALE_DIR=\"$(localedir)\"           \
```

**Comment by sgn** [comment]
I ended up patching more into `glib` https://github.com/void-linux/void-packages/pull/27558/commits/b5a894c02b2d3c5db86d8e5b4d804545bdd7c83c

**Comment by q66** [comment]
we just need to patch configure scripts...

**Comment by Justinizer** [comment]
Gimp patch by ericonr worked for me in #29970

**Comment by sgn** [comment]
I think everything has been done?

**Comment by ericonr** [comment]
It seems `gtk+` has no locale files at all? Why was it in that list? (or did we accidentally remove its locales?)

I guess the plan is to make `usr/locale` an error now?

**Comment by ericonr** [comment]
Or not, pcsx2 requires those files (we could add an override tho)
