### ISSUE TITLE
lm_sensors should include a service

### ISSUE THREAD

**Issue by Mek101** [void-linux/void-packages#27525]
### System

* xuname:  
  Void 5.9.16_1 x86_64-musl AuthenticAMD uptodate rFFFF
* package:  
  lm_sensors-3.6.0_1

### Expected behavior
At the end of the `sensors` setup via `sensors-detect`, the latter prints to enable the `lm_sensors` service to load the appropriate modules at boot time.

### Actual behavior
The output is:
```
Copy prog/init/lm_sensors.init to /etc/init.d/lm_sensors for initialization at boot time.
You should now start the lm_sensors service to load the required kernel modules.
```
Not only the paths are wrong, but there also no sensors service under `/etc/sv/` to start

### Steps to reproduce the behavior
Run the `sensors-detect` command.

**Comment by ericonr** [comment]
The systemd unit is

```
[Unit]
Description=Initialize hardware monitoring sensors

[Service]
EnvironmentFile=/etc/sysconfig/lm_sensors
Type=oneshot
RemainAfterExit=yes
ExecStart=-/sbin/modprobe -qab $BUS_MODULES $HWMON_MODULES
ExecStart=/usr/bin/sensors -s
ExecStop=-/sbin/modprobe -qabr $BUS_MODULES $HWMON_MODULES

[Install]
WantedBy=multi-user.target
```

Looks quite feasible to port to a run script, if you want to try it!

It also has `fancontrol.service` and `sensord.service`, but I think we don't build `sensord`.

**Comment by ericonr** [comment]
Argh, no :/

It's a oneshot... So it would be best to install the `lm_sensors.init` script and tell people to call it in `/etc/rc.local`, assuming that works. Afaik we don't any new oneshot services, since they require using `exec pause` at the end, which is quite the ugly workaround.

**Comment by Mek101** [comment]
What if we put them in [`/etc/modules-load.d/`](https://man.voidlinux.org/modules-load.8)?

**Comment by ericonr** [comment]
Can their utility write a file that works in `/etc/modules-load.d`?

**Comment by Mek101** [comment]
We could either patch it or provide the file with the package

**Comment by ericonr** [comment]
How about try to get it upstream? It should solve the issue for any distro, because a service is really not necessary here.

**Comment by Mek101** [comment]
That would be ideal.
Upstream here: https://github.com/lm-sensors/lm-sensors

**Comment by Mek101** [comment]
We could patch the `sensors-detect` [script](https://github.com/lm-sensors/lm-sensors/blob/master/prog/detect/sensors-detect) to place a file with the modules to load in `/etc/modules-load.d/sensors` (which is just plaintext with a name of a module to load per line).
Unfortunately, I don't know Perl to do it myself :(

**Comment by Mek101** [comment]
Ok, Tested it: not `/etc/modules-load.d/sensors` but `/etc/modules-load.d/sensors.conf`, and after that update initramfs with `xbps-reconfigure -f linux5.11 `

**Comment by ericonr** [comment]
I think it's an ok patch to carry downstream, for now, if you already have it written. It would be nice to PR it upstream, of course.

**Comment by Mek101** [comment]
Unfortunately, I don't have any patch: since I only tested the file streategy and what needs to be done; the modules to load change from system to system and the file must be generated and placed in `/etc/modules-load.d/` by the script linked above.
Perhaps, could you add the tag "Help wanted" to this issue", hoping that someone who knows how to write perl stubles upon it?

**Comment by ericonr** [comment]
Sure, will do.

**Comment by thegarlynch** [comment]
Wait. i do have to configure rc.shutdown too here right ?

**Comment by Mek101** [comment]
You shouldn't need to, since at shutdown the modules will be unloaded anyway

**Comment by thegarlynch** [comment]
Argh, i give up, it is hard to made this fan less noisy. i've tried everything, thermald turns out dptfxtract is not in musl and non gpl. i tried lm_sensors but pwmconfig is errored with "there are no pwm capable sensors installed" (already recompile kernel and include it in modules-load.d)

my windows is less noisy than this

**Comment by Mek101** [comment]
Sir, lm_sensors only displays the sensors data, it doesn't modify or otherwise interact with the fans.

**Comment by thegarlynch** [comment]
Lol, this is XY problem isn't it. i should have just asked

**Comment by Mek101** [comment]
In the appropiate place in the appropiate manner, not in a bug tracking issue regarding a sensor reader command line utility.

**Comment by CatalinCsnMaster** [comment]
Hello! Is this still open? can I contribute?

**Comment by Mek101** [comment]
Of course

**Comment by Mek101** [comment]
Of course

**Comment by Mek101** [comment]
Bump

**Comment by Mek101** [comment]
Bump

**Comment by ericonr** [comment]
@Mek101 do you think we need to keep this open in here? The upstream issue is technically where it should be tracked :/
