### ISSUE TITLE
Is mmlocate.db.5 intended or just a side effect?

### ISSUE THREAD

**Issue by firasuke** [void-linux/void-packages#27526]
Is `mmlocate.db.5` intended or just a side effect for `--program-prefix=m`?

https://github.com/void-linux/void-packages/blob/1a8eeec5feec341a1d4e6a3da296d7a605aa847e/srcpkgs/mlocate/template#L21

**Comment by leahneukirchen** [comment]
It is a sideeffect, but intented. Does it make issues?

**Comment by firasuke** [comment]
Not really, but I was just wondering why it wasn't `mlocate.db.5`.

Perhaps renaming the original source file from `doc/mlocate.db.5` to `doc/locate.db.5` and then modifying the value of `dist_man_MANS` in `Makefile.in` would remove this side-effect.

**Comment by leahneukirchen** [comment]
`man mlocate.db` will work fine, when makewhatis ran.

**Comment by firasuke** [comment]
I see.

Should I proceed to close this issue?
