### ISSUE TITLE
wine-devel-32bit install unresolved dependencies

### ISSUE THREAD

**Issue by floyza** [void-linux/void-packages#27572]
### System

* xuname:  
  Void 5.9.16_1 x86_64 AuthenticAMD uptodate rrrmFFFFF
* package:  
  wine-devel-32bit

On running `sudo xbps-install -Su wine-devel-32bit`, it fails to install with this error message:
```
MISSING: libwine-32bit-5.22_1
Transaction aborted due to unresolved dependencies.
```
It seems that the dependency was not updated to `libwine-32bit-6.0rc4_1`?

**Comment by ericonr** [comment]
`wine-devel-32bit` isn't built any more; I've added it to the clean up list now. If you need to build things with headers for 32bit wine, you're better off using an appropriate i686 chroot (or masterdir from xbps-src, for that matter).
