### ISSUE TITLE
foobillard++: can't find files on start

### ISSUE THREAD

**Issue by HenriDellal** [void-linux/void-packages#27598]
### System

* xuname:  
  Void 5.9.16_1 x86_64 GenuineIntel uptodate rrrmFFFFF
* package:  
  foobillard++-3.42beta_3

### Expected behavior
The game starts
### Actual behavior
The error occurs
```
Foobillard++ seems not to be correctly installed
Cannot find valid data directory
(assuming the current directory contains the data)
Locale file not found: locale/en/foobillard.txt
Cannot open language file - terminating.
```

### Steps to reproduce the behavior

* install `foobillard++`
* run `foobillardplus`

**Comment by ericonr** [comment]
Thanks for opening an issue :)
