### ISSUE TITLE
Package request: imlib2-heic

### ISSUE THREAD

**Issue by DirectorX** [void-linux/void-packages#27597]
https://github.com/vi/imlib2-heic

Loader for HEIC for Imlib2 (i.e. for Feh). Based on libheif.

**Comment by kawaiiamber** [comment]
> # Licence
> imlib2-heic is BSD (3-clause), but it depends on libheif which is LGPL.

I wonder how one would handle the licensing in packaging it.

**Comment by ericonr** [comment]
Dynamically linking an LGPL library should be just fine.

**Comment by kawaiiamber** [comment]
Understood, I made a [WIP] PR [here](https://github.com/void-linux/void-packages/pull/27814). [WIP] mainly because I don't know if I handled the licenses correctly.

**Comment by kawaiiamber** [comment]
So... licensing. While the project is licensed under a BSD 3 Clause license, they don't include an actual LICENSE file in their project. It is, however, included in source files, so I did a little `sed` command to extract that to a license. I'm worried as I'm not a lawyer. There was an issue [here](https://github.com/vi/imlib2-heic/issues/1) about adding a license, I'm just hoping that it's not a "won't fix" issue. I chatted with someone about this, and they said that there is technically no license, making the code non-distrutable. What do you recommend, @ericonr?

**Comment by kawaiiamber** [comment]
Upstream is adding a license, hopefully this means it can be packaged now with `vlicense`.
