### ISSUE TITLE
Request replacing xorg with xenocara,

### ISSUE THREAD

**Issue by FrostKnight** [void-linux/void-packages#27601]
Apparently, its being abandoned, etc... 
But as of now, OpenBSD still seems to support xenocara in light of the news below...

https://www.theregister.com/2020/10/30/x_server_lead_maintainer_declares/

https://ajaxnwnk.blogspot.com/2020/10/on-abandoning-x-server.html

Just my two cents...

I am not a developer, but I wondered if you guys plan to do such.  :)

If not, say so/lock. 

OpenBSD's version though has  many layers of security and protection so I thought you would be interested in xenocara.

**Comment by Johnnynator** [comment]
> OpenBSD's version though has many layers of security and protection so I thought you would be interested in xenocara.

these "layers" come down to features specific to OpenBSD features, like usage of `pledge(2)`. There isn't really any development happening there that would be interesting to use, and xorg still pushes releases with Security fixed (last one was a month ago).
Every fix in xenocara that might be interesting for us will end up in upstream, OpenBSD doesn't see xenocara as a fork.

so a) Xorg isn't fully abandoned yet
and b) xenocara doesn't provide any benefits for linux.

**Comment by FrostKnight** [comment]
Nevermind then, I forgot about those security features only working in OpenBSD...
Well, if you change your mind, I am sure you would do it anyways.

Either way, I thought xorg was abandoned... hmm... nvm then.
