### ISSUE TITLE
armv6 missing from docker

### ISSUE THREAD

**Issue by Mirodin** [void-linux/void-packages#27604]
I never did any work in xbps so I do not know what needs to be done to get a docker package for armv6 processors. I do have an old Pi 1B that I would like to run some simple docker containers on but xbps does not provide me with a docker package for this architecture.

Is there any specific reason for not having this package since [Alpine](https://pkgs.alpinelinux.org/packages?name=docker&branch=edge) has a working package (I tested a few minutes ago)?

**Comment by ericonr** [comment]
We have it arch restriced for some reason... I will try to crossbuild and see if it works fine.

**Comment by ericonr** [comment]
Just pushed, should be available in repo in a bit :)

**Comment by Mirodin** [comment]
Awesome, thanks a lot :)
