### ISSUE TITLE
mlocate: updatedb.conf.5 manpage is a broken symlink

### ISSUE THREAD

**Issue by ScrelliCopter** [void-linux/void-packages#27657]
Problem seems to stem from this line:
https://github.com/void-linux/void-packages/blob/1a8eeec5feec341a1d4e6a3da296d7a605aa847e/srcpkgs/mlocate/template#L22

`man 5 mupdatedb.conf` exists and works fine, however `man 5 updatedb.conf` prints
```
man: outdated mandoc.db lacks updatedb.conf(5) entry, run makewhatis /usr/share/man
man: ERROR: /usr/share/man/man5/updatedb.conf.5: No such file or directory
```
Looking under `/usr/share/man/man5/`, updatedb.conf.5 is a broken symlink to a nonexistent page "mupdatedb.db.5".

This is an obvious typo of mupdatedb.conf.5 right?

**Comment by ericonr** [comment]
Closed in https://github.com/void-linux/void-packages/pull/27700
