### ISSUE TITLE
[Package request] electron-ozone

### ISSUE THREAD

**Issue by simvux** [void-linux/void-packages#27679]
Electron by default (as far as I can tell) is not compiled with ozone support. The void-packages `electron10` package doesn't seem to provide it as a build option either. 

Electron with ozone will make it possible to have _native wayland_ and _pipewire/xdg-desktop-portal screen sharing_ support for electron applications such as Discord by using the systems electron over the bundled version. 

[AUR package](https://aur.archlinux.org/packages/electron-ozone/)

Also worth noting that this would be a lot more useful if #23296 were to be merged

**Comment by ericonr** [comment]
We should probably wait for upstream to support building with ozone cleanly.

@Johnnynator so he can be aware of it.

**Comment by JamiKettunen** [comment]
Is this still an issue nowadays with the AUR package gone, [xdg-desktop-portal-wlr](https://github.com/void-linux/void-packages/tree/master/srcpkgs/xdg-desktop-portal-wlr) available and [electron19](https://github.com/void-linux/void-packages/tree/master/srcpkgs/electron19) packaged?

Btw I think you can still forget about Discord Wayland screensharing as I'm unsure if this has still so far worked anywhere, I'd be happy to be proven wrong however; typically you've had to share screen through the webapp running in a normal browser afaik.

**Comment by classabbyamp** [comment]
pretty sure electron supports ozone now
