### ISSUE TITLE
linux-firmware symlinks

### ISSUE THREAD

**Issue by L3Nya** [void-linux/void-packages#27682]
### System

* xuname:  
Void 5.5.18_1 x86_64-musl AuthenticAMD notuptodate rFFF
* package:  
  *affected package(s) including the version*: ``linux-firmware-20201218_1
``

### Expected behavior
symlinks created according to WHENCE file

### Actual behavior
symlinks aren't created

### Steps to reproduce the behavior
1. install `linux-firmware`(or `linux-firmware-nvidia`/`linux-firmware-intel`/`linux-firmware-network`) package
2. check for symlinks(for example `/usr/lib/firmware/nvidia/gp108/acr -> /usr/lib/firmware/nvidia/gp102/acr`)
3. find out they do not exist
###
Commits where this was changed:
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=1487a8abdbac007463304bd8ee727749765f88b7
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=bdd56173e74ba2c5713cfad0b4a8fe0f3f88c9f6
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=ab69b57c18129b91b2308cdcf81448684b6b9fdd

Based on what I saw, there are other links in WHENCE, not only related to this commits

To fix you just need to add symlink commands

**Comment by ericonr** [comment]
Thanks for bringing this up, I've opened #27817 to fix it.
