### ISSUE TITLE
go packages may have mismatched package names

### ISSUE THREAD

**Issue by vixus0** [void-linux/void-packages#27690]
### Problem

When using the `build_style=go`, package templates may be using a `go_import_path=` that does not match the name of the go package. This could be because the package name changed in the upstream source. The result is a seemingly correct package that was actually built from very old sources thanks to the way go works. I suspect this is mainly likely to happen with go sources that make use of go modules but as that becomes more standard it might become more likely.

For an example, see #27688.

### Mitigations

- Linting: when `go.mod` is present, check that `go_import_path=` is set to the name defined there.
- `build-style/go.sh`: (better, imo) set the value of `go_import_path=` to the module name defined in `go.mod`.

**Comment by ericonr** [comment]
Once more #28847

I believe this can be detected when `git` is added to `hostmakedepends`, since it's what Go uses to download the old version of the module. Will try to go through templates for this.

**Comment by vixus0** [comment]
Bumping while we wait for #28895.
