### ISSUE TITLE
conflict between rpi3-firmware and linux-firmware-broadcom

### ISSUE THREAD

**Issue by xaltsc** [void-linux/void-packages#27722]
### System

* xuname: 
   `Void 5.9.16_1 aarch64-musl GenuineIntel uptodate rF` (inside a chroot)
* package:  
  `rpi3-firmware-20170113_1`, `linux-firmware-broadcom-20201218_1` and therefore `rpi3-base-0.1_3`

### Expected behavior
`xbps-install rpi3-base rpi3-firmware` installs both packages as intended.

### Actual behavior
XBPS installs both packages until it fails with the following error:
```
ERROR: rpi3-firmware-20170113_1: file `/usr/lib/firmware/brcm/brcmfmac43430-sdio.bin' already installed by package linux-firmware-broadcom-20201218_1.
```

It's possible to work around this by installing `rpi3-firmware` before `rpi3-base`, but, as @ericonr said, this is due to a bug in XBPS.

### Steps to reproduce the behavior
- `xbps-install rpi3-base rpi3-firmware`

**Comment by ericonr** [comment]
Sorry for the confusion, `rpi3-firmware` was removed in 4a487cf40bbec87ab88a2c709ba5079a63fe0e4f, and `rpi3-base` in ddc8991d7d5487e5842488b9778965a1ffa99536. You're supposed to always use `rpi-base` and `rpi-firmware` (at least for now).
