### ISSUE TITLE
[Package request] Jamulus

### ISSUE THREAD

**Issue by 38github** [void-linux/void-packages#27738]
Application: Jamulus (https://github.com/corrados/jamulus)
Dependencies that I know of: qt5, jack, 

Jamulus is a realtime/low latency online jamming application that is in my opinion amazing. If you are a musician I personally believe that you should try it. It is that good in my opinion! It features both a client and a headless server. If built as a single package you can still start the server with extra commands but then needs unnecessary deps.

Sorry for not remembering how to properly write a request.

**Comment by kawaiiamber** [comment]
It might be worth noting that the project is actually officially hosted on source forge. Anyways, here was my attempt:
```sh
# Template file for 'jamulus'
 pkgname=jamulus
 version=3.6.2
 revision=1
 build_style=qmake
 configure_args="Jamulus.pro"
 wrksrc="Jamulus${version}"
 makedepends="qt5-declarative-devel jack-devel qjackctl"
 short_desc="Play music online. With friends. For free."
 maintainer="KawaiiAmber <japaneselearning101@gmail.com>"
 license="GPL-2.0-only"
 homepage="https://jamulus.io/"
 distfiles="https://phoenixnap.dl.sourceforge.net/project/llcon/Jamulus/3.6.2/Jamulus-${version}.tar.gz"
 checksum=86d38f7d22b49720a79a246918cb8f16a690bbc7d6cbc8707e93694bab1a074c
```
However, `xbps-src` returns with
```
Project MESSAGE: Jack Audio Interface Enabled.
Project ERROR: jack development package not found
```
For some reason, it doesn't seem to detect the development files in the `jack-devel` package. I could try making a [WIP] PR, but I'm not sure if that's really appropriate to do. I'm pretty new here and don't know if trying to PR a failing package is seen as bad or not, so I just pasted my template here.

**Comment by 38github** [comment]
Thank you for being on it so quickly. Strange that it could not find some of the jack dev files.

**Comment by 38github** [comment]
Does it need qjackctl to build?

**Comment by kawaiiamber** [comment]
qjackctl is already in the `makedepends`, it's the last one I listed

**Comment by 38github** [comment]
I was asking (as a non-developer though) because I haven't seen elsewhere that it needs that package when being built. I can be wrong though (extreme probability).

**Comment by kawaiiamber** [comment]
I got recommended dependencies and build instructions from [here](https://jamulus.io/wiki/Installation-for-Linux). It's not required.
> # Qjackctl: Optional, but recommended
> QjackCtl is a utility to help you set up the Jack audio server (installed as part of the dependencies above).

**Comment by 38github** [comment]
Thank you for making it clear to me.

**Comment by kawaiiamber** [comment]
No problem. At any rate, it seems like the main issue is the jack developement files aren't being detected by qmake.

**Comment by 38github** [comment]
@sletz @falkTX I do not know if you have used Void Linux and I am pretty sure you haven't seen any of the compiling output but do you maybe know why qmake do not detect jack's development files? Thanks in advance!

**Comment by 38github** [comment]
@jkoderu-git I found that you have had something to do with Void Linux' jack package so maybe you have an idea?

**Comment by kawaiiamber** [comment]
It looks like `pkg-config` was needed in `hostmakedepends` for package tracking (I probably should have guessed that, oops). I made a PR [here](https://github.com/void-linux/void-packages/pull/27843) that is passing locally on my musl machine and passing the CI checks, check it out if you want ~

**Comment by 38github** [comment]
Thank you for all the hard work, kawaiiamber!
