### ISSUE TITLE
License is not correct for phpMyAdmin

### ISSUE THREAD

**Issue by williamdes** [void-linux/void-packages#27798]
https://github.com/void-linux/void-packages/blob/25f75fa3024ad571439c8ce37055f784c415157b/srcpkgs/phpMyAdmin/template#L10

phpMyAdmin is GPL-2.0 **only**

https://github.com/phpmyadmin/phpmyadmin/blob/98e74e3af835b6d0de987530d6e897f5ce6ef46c/composer.json#L14
https://github.com/phpmyadmin/phpmyadmin/blob/98e74e3af835b6d0de987530d6e897f5ce6ef46c/package.json#L7

Thanks for packaging phpMyAdmin !

**Comment by williamdes** [comment]
cc @Francesco149

**Comment by williamdes** [comment]
Also an update to 5.0.4 could be done at the same time ;)

**Comment by the-maldridge** [comment]
Good catch.  We're in the middle of a large GCC rebuild at the moment, but this can be patched once the dust has settled on that.
