### ISSUE TITLE
Skylake CPU cannot enter package states lower than PC3

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#27806]
On my Thinkpad T460s (i5-6300U), even after running `powertop --auto-tune`, the package cannot go below pc3 state. This seems specific to Void, as on Arch Linux it can go below that.
```
$ xuname
Void 5.10.5_1 x86_64-musl GenuineIntel uptodate hold rrnDDFFF
```
```
$ sudo powertop --auto-tune
Password:
modprobe cpufreq_stats failedLoaded 147 prior measurements
RAPL device for cpu 0
RAPL Using PowerCap Sysfs : Domain Mask f
RAPL device for cpu 0
RAPL Using PowerCap Sysfs : Domain Mask f
Devfreq not enabled
glob returned GLOB_NOMATCH
To show power estimates do 192 measurement(s) connected to battery only
Leaving PowerTOP
```
Incidentally, I've been trying to use Arch Linux kernel in Void, with the final goal of pinning this powertop issue down to some kernel config difference between Arch and Void, but while I can successfully build it (after changing some part about signing modules, vary GCC version and add `zstd` as `hostmakedepends`), when I try to boot it fails at decrypting the partition, with
```
encrypted_key: failed to alloc_cypher (-2)
modprobe: ERROR: could not insert 'dm_crypt': Unknown symbol in module, or unknown parameter (see dmesg)
device-mapper: table: 254:0: crypt: unknown target type
device-mapper: reload ioctl on  failed: Invalid argument
```
Does anyone know what I'm missing?
Thanks.

**Comment by abenson** [comment]
> kernel config difference

Why not just compare the kernel configurations?

**Comment by ericonr** [comment]
You're probably getting conflicts between the `/usr/lib/modules` folders.

How did you determine you weren't entering states below PC3 ?

**Comment by ericonr** [comment]
Fow what it's worth, I have a diff in https://gist.github.com/ericonr/a49d4fa9980aab0a5862a2c50bec6c3a

The only difference that I think could apply is ` SATA_MOBILE_LPM_POLICY 3 -> 0`, which means

```
config SATA_MOBILE_LPM_POLICY
	int "Default SATA Link Power Management policy for mobile chipsets"
	range 0 4
	default 0
	depends on SATA_AHCI
	help
	  Select the Default SATA Link Power Management (LPM) policy to use
	  for mobile / laptop variants of chipsets / "South Bridges".

	  The value set has the following meanings:
		0 => Keep firmware settings
		1 => Maximum performance
		2 => Medium power
		3 => Medium power with Device Initiated PM enabled
		4 => Minimum power

	  Note "Minimum power" is known to cause issues, including disk
	  corruption, with some disks and should not be used.
```

**Comment by abenson** [comment]
I'm currently building a kernel with this change to test on my X270, which has the same CPU as the T460s mentioned earlier and seems to be in the same boat.

**Comment by abenson** [comment]
C2 (pc2)    6.8%
    C3 (pc3)    0.1%
    C6 (pc6)   58.2%
    C7 (pc7)   55.7%

That seems to have been it!

**Comment by dkwo** [comment]
Wow, many thanks @ericonr for your quick and to the point reply and to @abenson for testing.
I looked at the diff before, but was unable to pinpoint the relevant lines.
I was testing the pc states with powertop.
I will also build with the suggested change later and report, just to confirm.
As far as building Arch kernel, that may not be necessary anymore, but I may come back to it later just for fun.

**Comment by dkwo** [comment]
Even with the proposed modification
```
$ cat config-5.10.6_2 | grep SATA_MOBIL
CONFIG_SATA_MOBILE_LPM_POLICY=3
$ xuname
Void 5.10.6_2 x86_64-musl GenuineIntel uptodate hold rrnDDFFF
```
and after running `powertop --auto-tune` and `powertop --calibrate`, I still cannot get below pc3 state. I tested from tty, with many services stopped. Could it be tlp is interfering with this?

**Comment by dkwo** [comment]
@abenson may I ask if you're also using `musl`?

**Comment by abenson** [comment]
I'm neither using musl nor tlp on the tested systems.

**Comment by dkwo** [comment]
Thanks. I tried disabling `tlp`, still not good. Will try soon with a `glibc` install.

**Comment by dkwo** [comment]
I can confirm the suggested fix works with `glibc` install.
Thanks again.

**Comment by travankor** [comment]
Would be interesting to find out what is different for musl.

**Comment by dkwo** [comment]
I still have musl on my machine (at least until grub 2.06 comes out), so 
I can run some tests.
Do you have any ideas?

**Comment by dkwo** [comment]
I stand corrected: with the new kernel config, also in musl it can reach pc9 power state.
I'm not sure why I missed it before.
