### ISSUE TITLE
wget - This version does not have support for IRIs

### ISSUE THREAD

**Issue by jirib** [void-linux/void-packages#27813]
Hi,

I used `wget` to do mirror of a web and owner created probably some filenames with windows-1252 encoding, this caused problem and it seems way to go is to use "IRI" support in wget for convertion.

### System

* xuname:  

```
Void 5.9.14_1 x86_64 GenuineIntel notuptodate rrrdFFF
```

* package:  
```
wget-1.21_1
```
### Expected behavior

IIUC IRI support is must if handling issues with filenames encoding. `+ivi` should be part ov `wget -V`.

### Actual behavior

```
$ wget -V | head -4
GNU Wget 1.21 built on linux-gnu.

-cares +digest -gpgme +https +ipv6 -iri +large-file -metalink +nls 
+ntlm +opie -psl +ssl/openssl 

$ wget --local-encoding=utf-8 --restrict-file-names=nocontrol https://www.google.com
This version does not have support for IRIs
```

### Steps to reproduce the behavior

```
$ wget --local-encoding=utf-8 --restrict-file-names=nocontrol https://www.google.com
This version does not have support for IRIs

$ wget -V | head -4 # should be with +iri
```

**Comment by ericonr** [comment]
Will be fixing it in a bit, it should be using `libidn2`.
