### ISSUE TITLE
Package request: edid-decode

### ISSUE THREAD

**Issue by jsumners** [void-linux/void-packages#27934]
https://git.linuxtv.org/edid-decode.git/about/

Currently, Void offers the `read-edid` package sourced from http://polypux.org/projects/read-edid/. Unfortunately, this tool is woefully out-of-date and does not actually parse modern edid files. I was able to clone the `edid-decode` source, install the `gcc` package, and build the tool successfully. The result is the following printed out the complete information where `parse-edid` (from the `read-edid` package) did not:

```
./edid-decode < /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-HDMI-A-1/edid
```

**Comment by ericonr** [comment]
I've reached out to them about tagging a release, which would be a requirement for packaging this. Let's see how it goes.

**Comment by jsumners** [comment]
👍

**Comment by CtrlC-Root** [comment]
I would also find this useful. I see there are no tags on the repository at the moment. @ericonr Did they ever respond to you?

**Comment by classabbyamp** [comment]
`di-edid-decode` from `libdisplay-info` works
