### ISSUE TITLE
libpulseaudio-pipewire-0.3.17_1: severely out of date

### ISSUE THREAD

**Issue by endigma-4426** [void-linux/void-packages#27935]
### System

* xuname:  Void 5.9.16_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFFF
* package: libpulseaudio-pipewire-0.3.17_1

### Expected behavior

the pulseaudio lib is up to date and does not cause a dependency issue

### Actual behavior

```
[*] Updating repository `https://mirror.clarkson.edu/voidlinux//current/x86_64-repodata' ...
[*] Updating repository `https://mirror.clarkson.edu/voidlinux//current/multilib/nonfree/x86_64-repodata' ...
[*] Updating repository `https://mirror.clarkson.edu/voidlinux//current/multilib/x86_64-repodata' ...
[*] Updating repository `https://mirror.clarkson.edu/voidlinux//current/nonfree/x86_64-repodata' ...
MISSING: libpipewire-0.3.17_1
Transaction aborted due to unresolved dependencies.
```

the lib is out of date and causes a dependency issue, pipewire is on 0.3.19 now.

### Steps to reproduce the behavior

try installing the software with an updated system

### Fix

update the package

### Issue

I tried finding the package under srcpkg to fix it myself with a PR, but this package appears not to be in the repo.

**Comment by q66** [comment]
`pipewire` replaces `libpulseaudio-pipewire`
