### ISSUE TITLE
anki doesn't support anymore ibus-anthy

### ISSUE THREAD

**Issue by KRSHK** [void-linux/void-packages#2794]
### System

* xuname:  
  *Void 4.18.7_2 x86_64 GenuineIntel uptodate rrrmFFFF*
* package:  
  *anki-2.1.4_3*
  *ibus-1.5.19_1*
  *ibus-anthy-1.5.10_1*

### Expected behavior
When switching language with <shift><space>, I can write in Japanese
(worked well in anki 2.0.52)

### Actual behavior
Nothing happens, it works for all the gtk application.
Unfortunately, I have no other Qt5 application.

**Comment by CameronNemo** [comment]
Can you test with `env QT_IM_MODULE=ibus anki`? I would also suggest testing with other Qt5 applications. If that does not work you may wish to file an issue with https://github.com/ibus/ibus-anthy.

**Comment by mvf** [comment]
Working fine over here with these environment variables:
```
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
```
I recommend switching to the superior Mozc backend though.

**Comment by KRSHK** [comment]
@mvf I got the same in my .xinitrc, but I still have the same issue.
I had to downgrade to the previous version to use it.

**Comment by mvf** [comment]
Hm, sounds like an issue with your `qt5` then. Which is odd because IBus support is shipped with the `qt5` package itself. For starters you could check if the IBus plugin is loaded:

- Start Anki 2.1
- Find the PID of Anki's `python3` process, e.g.:
```
$ ps x|grep anki
 9857 pts/3    tl     0:00 /usr/bin/python3 /usr/bin/anki
```
- List Anki's loaded platform input contexts:
```
$ grep platforminput /proc/9857/maps
7f8bc892d000-7f8bc8959000 r-xp 00000000 fe:00 2490549                    /usr/lib/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
7f8bc8959000-7f8bc8b58000 ---p 0002c000 fe:00 2490549                    /usr/lib/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
7f8bc8b58000-7f8bc8b5a000 r--p 0002b000 fe:00 2490549                    /usr/lib/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
7f8bc8b5a000-7f8bc8b5b000 rw-p 0002d000 fe:00 2490549                    /usr/lib/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
```
If the `grep` produces no output, the plugin is not loaded.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
@ KRSHK never gave feedback about the question if the IBus plugin is loaded (`grep` output).

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=941018

**Comment by CameronNemo** [comment]
looks like a different issue. debian bug references regression from z.19 to z.21. This bug was wiled against z.19.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Side information:
On Debian 10 some modifications where done and JabRef works again witih ibus-anthy. But Anki (2.1.15) still not working.
