### ISSUE TITLE
github-actions: constrain PR's to cancel old duplicate actions

### ISSUE THREAD

**Issue by waynevanson** [void-linux/void-packages#27972]
Here's a non-hypothetical example.

- I created a PR for a new package, github actions trigger.
- I made a small change in the dependencies and force pushed to the origin, github actions trigger again.

There are now 2 actions running, using resources. I went to go cancel the first one, but was unable to due to permissions.

An ideal solution is that when a force push is applied, it creates a new github action and the old one is deleted.
I'm unsure if this is even possible.

**Comment by ericonr** [comment]
Doesn't it automatically kill the previous action? I remember observing such a behavior.

**Comment by waynevanson** [comment]
I don't think so. Here are the actions: https://github.com/void-linux/void-packages/actions?query=branch%3Apackage%2Fwally-cli

> Doesn't it automatically kill the previous action?

Perhaps force pushes skip this behavior. They use the commit as an identifier, so maybe because it can't tell what the previous commit was it does not know what it can and cannot cancel.

This is more of a quality of life change for the inexperience contributors or for when accidents happen.

**Comment by ericonr** [comment]
Ugh, seems I could reproduce it:

https://github.com/void-linux/void-packages/actions/runs/537279192 and https://github.com/void-linux/void-packages/actions/runs/537280306 , just a few seconds apart.
