### ISSUE TITLE
zsh completion system broken after latest 5.6.2 update

### ISSUE THREAD

**Issue by vuksavic** [void-linux/void-packages#2799]
On musl, upon trying to autocomplete a file address zsh returned the following:

`[vuk@t420s:~]% ls -a /us[TAB]_arguments:325: command not found: comparguments
`

where [TAB] is where i pressed the tab button to engage the completion

The update removed all of the "obsolete" entries from the past version(5.5.1), such as the help folder, all *.so files, and I think the completion settings and recordings too.

**Comment by chneukirchen** [comment]
I can't reproduce this in a musl chroot.

Note that you need to restart all running zsh instances after an upgrade (always has been this way).
