### ISSUE TITLE
not working voice chats in tdesktop

### ISSUE THREAD

**Issue by L3Nya** [void-linux/void-packages#28001]
### System

* xuname:  
  `Void 5.5.18_1 x86_64-musl AuthenticAMD notuptodate rFFFF`
* package:  
  *affected package(s) including the version*: `tg_owt-0.0.0.1_1` (and subsequently `telegram-desktop-2.5.1_1`)

### Expected behavior
when you join voice chat in telegram desktop it connects and just works
### Actual behavior
when you join voice chat in telegram desktop it connects endlessly

### cause
![image](https://user-images.githubusercontent.com/47749563/104879367-a1686e00-5955-11eb-8ba3-b69ec5c77545.png)
it's last line of log, then it repeats, so it's problem with openssl likely due to libressl patch
in patch there are just removed dtls1.2 support, if it's libressl. and there are some incompatibility between DTLS and TLS.

**Comment by ericonr** [comment]
@Johnnynator 

One more point to OpenSSL :P

**Comment by Johnnynator** [comment]
Which Client did the other end use? 
I only ever tested this between telegram-desktop clients (both OpenSSL <-> LibreSSL and LibreSSL <-> LibreSSL) and it did work fine.

**Comment by L3Nya** [comment]
> Which Client did the other end use?
> I only ever tested this between telegram-desktop clients (both OpenSSL <-> LibreSSL and LibreSSL <-> LibreSSL) and it did work fine.

I think you confused group voice calls with private. private calls works fine, but voice calls don't work at all.

**Comment by Johnnynator** [comment]
> @Johnnynator
> 
> > Which Client did the other end use?
> > I only ever tested this between telegram-desktop clients (both OpenSSL <-> LibreSSL and LibreSSL <-> LibreSSL) and it did work fine.
> 
> I think you confused group voice calls with private. private calls works fine, but voice calls don't work at all.

You didn't mention that it is about group chats in a singe word. I didn't even think about that they exist.

**Comment by L3Nya** [comment]
> > @Johnnynator
> > > Which Client did the other end use?
> > > I only ever tested this between telegram-desktop clients (both OpenSSL <-> LibreSSL and LibreSSL <-> LibreSSL) and it did work fine.
> > 
> > 
> > I think you confused group voice calls with private. private calls works fine, but voice calls don't work at all.
> 
> You didn't mention that it is about group chats in a singe word. I didn't even think about that they exist.

Voice calls is not voice chats and telegram uses this term to talk about group calls. Ok, no matter. They do exist and they doesn't work.

**Comment by Johnnynator** [comment]
Resolved with 32caeec70fe84b56c33c68e071d8e48f52715c5b
