### ISSUE TITLE
Package request: Barnard

### ISSUE THREAD

**Issue by uber97** [void-linux/void-packages#28033]
[Barnard](https://github.com/neuling/barnard) is a third-party TUI client for Mumble.

**Comment by skuzzymiglet** [comment]
There haven't been any releases on Barnard as far as I can see

**Comment by ericonr** [comment]
Since there aren't actual releases, and we can't track every package in existence, I will be closing this for now. Feel free to reopen once the situation changes (you can also point them at this issue if you wish to ask for a release).

Using a fork with 0 stars also feels a bit sketchy.
