### ISSUE TITLE
[tracking issue] glibc 2.32 32-bit seccomp breakages

### ISSUE THREAD

**Issue by q66** [void-linux/void-packages#28034]
- [x] `firefox`
- [x] `firefox-esr` and `thunderbird` (doesn't actually appear to be affected, but it should be)
- [x] `openssh`
- [x] `chromium`
- [x] `qt5-webengine`
- [x] `electron*`

more to be added if found

**Comment by Johnnynator** [comment]
#28043 for electron packages (builds are running, will test tomorrow)

**Comment by ericonr** [comment]
Done and nothing else's been reported.
