### ISSUE TITLE
Packages request: Nitter and Bibiliogram

### ISSUE THREAD

**Issue by uber97** [void-linux/void-packages#28032]
Hi. I'm requesting the packaging of [Nitter](https://github.com/zedeus/nitter) and [Bibliogram](https://sr.ht/~cadence/bibliogram/), two known proxies and alternative front-ends for Twitter and Instagram, respectively.

**Comment by ericonr** [comment]
Neither of those seem to have actual releases.

**Comment by ericonr** [comment]
Since there aren't actual releases, and we can't track every package in existence, I will be closing this for now. Feel free to reopen once the situation changes (you can also point them at this issue if you wish to ask for a release).
