### ISSUE TITLE
seafile-cli broken

### ISSUE THREAD

**Issue by WasabiPizza** [void-linux/void-packages#28041]
### System

* xuname:  
  Void 5.10.8_1 x86_64-musl GenuineIntel uptodate rrnFF
* package:  
  seafile-cli-7.0.10_1

Just running `seaf-cli` should produce the error.
I thought it was fixed running `pip install -U future` (thanks to who helped me on irc, can't remeber the name sorry) but now, when I try running `seaf-cli sync ...` I get:

``` 
Starting to download ...
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 88, in _get_transport
    transport = self._pool.get(False)
  File "/usr/lib/python3.9/queue.py", line 168, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/seaf-cli", line 983, in <module>
    main()
  File "/bin/seaf-cli", line 979, in main
    args.func(args)
  File "/bin/seaf-cli", line 680, in seaf_sync
    seafile_rpc.clone(repo,
  File "/usr/lib/python3.9/site-packages/pysearpc/client.py", line 126, in newfunc
    ret_str = self.call_remote_func_sync(fcall_str)
  File "/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 100, in call_remote_func_sync
    transport = self._get_transport()
  File "/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 90, in _get_transport
    transport = self._create_transport()
  File "/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 83, in _create_transport
    transport.connect()
  File "/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 47, in connect
    self.pipe.connect(self.socket_path)
ConnectionRefusedError: [Errno 111] Connection refused
```

Thanks!

**Comment by ericonr** [comment]
That looks really weird... Can you run `strace -o logfile.txt <program>` and paste that somewhere (a github gist works)? (assuming it doesn't have anything sensitive).

**Comment by ericonr** [comment]
btw, @yopito

**Comment by WasabiPizza** [comment]
I guess I should just upload the file, hopefully this works. Thanks @ericonr.
[logfile.txt](https://github.com/void-linux/void-packages/files/5838874/logfile.txt)

**Comment by ericonr** [comment]
```
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/home/nero/seafile/seafile-data/seafile.sock"}, 46) = -1 ECONNREFUSED (Connection refused)
madvise(0x56399f529000, 184320, MADV_DONTNEED) = 0
write(2, "Traceback (most recent call last"..., 35) = 35
write(2, "  File \"/usr/lib/python3.9/site-"..., 93) = 93
```

looks relevant. The folder itself definitely exists, since `open("/home/nero/seafile/seafile-data/id", O_RDONLY|O_CLOEXEC) = 3
` succeeds. I think it's missing something that creates the actual socket, though. Are you sure the software is being operated correctly? Maybe you need to launch some other program as well?

**Comment by WasabiPizza** [comment]
Well 4 days ago I did the same and it worked fine, I'm just synchronizing another folder so I expected it to work.
Also, the first time that I tried running `seaf-cli` I got this error https://i.imgur.com/kSK2Qk7.png, not sure if it's somehow related.

**Comment by sgn** [comment]
`pip install -U future` Please don't. Use system python3-future instead.

**Comment by yopito** [comment]
thanks for report.
Looks like upstream fixed it (commit https://github.com/haiwen/libsearpc/commit/b0079d2a0c3ce0cb4698a162498b108244726912). I'm working on it.

**Comment by yopito** [comment]
NB: with the new package (see PR above), no additional pyhon module is required.

**Comment by WasabiPizza** [comment]
Thanks @yopito! Just updated and it works fine now.

**Comment by yopito** [comment]
You're welcome. Sorry for this bug.
