### ISSUE TITLE
gnuchess segfaults on first move

### ISSUE THREAD

**Issue by ben-cooper** [void-linux/void-packages#28044]
### System

* xuname:  
  Void 5.10.8_1 x86_64-musl AuthenticAMD uptodate rrnFFFF
* package:  
  gnuchess-6.2.7_1

### Expected behavior

The program should be able to play a game of chess with me.

### Actual behavior

The program is able to detect illegal moves, but after I play the first move, it segfaults after thinking about what to play.  It renders my move correctly on the text board, however.  This behaviour is also present when using the program `gnome-chess`.

```
GNU Chess 6.2.7
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
White (1) : e4
1. e4

black  KQkq  e3

r n b q k b n r 
p p p p p p p p 
. . . . . . . . 
. . . . . . . . 
. . . . P . . . 
. . . . . . . . 
P P P P . P P P 
R N B Q K B N R 
 
Thinking...
Segmentation fault
```

### Steps to reproduce the behavior

1. Run `gnuchess`
2. Play any legal move  (such as e4)

Please let me know if you need any more information.
Thanks for looking at this!

**Comment by ericonr** [comment]
Just wait for the update to hit the repository (or build it yourself). Should be fixed now :)

Thanks for the bug report/

**Comment by ben-cooper** [comment]
That's great to hear.  Thanks for getting back to me so quickly.
