### ISSUE TITLE
[package request] PREEMPT_RT patched Linux kernel 

### ISSUE THREAD

**Issue by uzr123x** [void-linux/void-packages#28046]
preempt_rt kernel is indispensable for anyone who wants to use their PC as a workstation for pro audio and music creation, or any other tasks that require real-time kernel capabilities.
https://wiki.linuxfoundation.org/realtime/documentation/howto/applications/preemptrt_setup

**Comment by q66** [comment]
we don't ship extra kernels except when needed for hardware support
