### ISSUE TITLE
redo with xbps-src

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#28050]
Does `xbps-src` support using `redo` instead of `make`?
Say either the one which is packaged in Void, or [goredo](http://www.goredo.cypherpunks.ru).
Thanks.

**Comment by Anachron** [comment]
You can clean the builddir using the `./xbps-src clean` action:

```
clean [pkgname]
    Removes auto dependencies, cleans up <masterdir>/builddir and <masterdir>/destdir.
    If <pkgname> argument is specified, package files from <masterdir>/destdir and its
    build directory in <masterdir>/buiddir are removed.
```

As always, make sure to read the manual/help.

**Comment by dkwo** [comment]
Ehm, what are you talking about?

https://cr.yp.to/redo.html

**Comment by Anachron** [comment]
You can replace the `make_cmd` to use `redo` instead of `make`, but that requires manual intervention for all your `templates`.

**Comment by dkwo** [comment]
I see, after the edit it makes sense.
What I had in mind is the possibility (for certain templates) to use `redo` instead of `make` (not necessarily all of them).

**Comment by dkwo** [comment]
I guess one option is to add it as a `build-style`, right?

**Comment by q66** [comment]
build-styles are only added if something needs them
