### ISSUE TITLE
Cannot cross-compile libevent for armv5tel-musl

### ISSUE THREAD

**Issue by lfdebrux** [void-linux/void-packages#28103]
### System

* xuname:  Void 5.10.8_1 x86_64-musl GenuineIntel/VM notuptodate rF
* package:  libressl-devel, libevent, nghttp2, curl, elfutils, binutils, gcc

### Expected behavior

Running `./xbps-src -a armv5tel-musl libevent` builds and installs `libevent`

### Actual behavior

Build does not start due to issue installing libressl-devel as libssp is missing:

```
=> xbps-src: cleaning up / masterdir...
=> libevent-2.1.12_1: removing autodeps, please wait...
=> libevent-2.1.12_1: removing autocrossdeps, please wait...
=> libevent-2.1.12_1: building [gnu-configure] for armv5tel-musl...
   [target] libressl-devel-3.1.5_2: found (/host/binpkgs)
   [runtime] libressl-devel-3.1.5_2: found (/host/binpkgs)
   [runtime] libevent-2.1.12_1: not found (self, ignored)
=> libevent-2.1.12_1: installing target dependencies: libressl-devel-3.1.5_2 ...
=> libevent-2.1.12_1: removing autodeps, please wait...
=> libevent-2.1.12_1: removing autocrossdeps, please wait...
=> ERROR: libevent-2.1.12_1: failed to install 'libressl-devel-3.1.5_2' dependency! (error 19)
MISSING: libssp>=4.4.0_1
MISSING: libssp>=4.4.0_1
MISSING: libssp>=4.4.0_1
MISSING: libssp>=4.4.0_1
Transaction aborted due to unresolved dependencies.
=> ERROR: Please see above for the real error, exiting...
```

This is particularly annoying because libssp is part of the gcc package, which depends on libevent transitively, so there is a circular dependency. I end up with the same issue trying to build any package in the dependency chain from gcc to libevent.

Strangely however I can build libressl-devel without issues using `./xbs-src -a armv5tel-musl pkg libressl`.

### Steps to reproduce the behavior

On Void Linux x86_64-musl, clone void-packages, install bootstrap and try to build libevent targeting armv5tel-musl.

**Comment by pullmoll** [comment]
This has bitten me not too long ago as well. The `(error 19)` is the only indication that there is indeed a cyclic dependency and we need to identify and eliminate it.

**Comment by Johnnynator** [comment]
Shouldn't `libssp` be listed in `cross-vpkg-dummy` since it is provided by the cross toolchain? This is also the reason why `libressl` compiles but xbps refues to install it.

**Comment by pullmoll** [comment]
I think you are right @Johnnynator . And `cross-vpkg-dummy` needs an update for gcc10 anyway as it lists the gcc9 gcc ada libraries.

**Comment by q66** [comment]
only on musl, there is no libssp in glibc crosstoolchains

**Comment by q66** [comment]
anyway, i will fix this along with other things

**Comment by q66** [comment]
okay, that should be updated now (will take a while to propagate since builders are still busy)

**Comment by lfdebrux** [comment]
Thank you for looking into this!

I am getting the same error even after checking out the latest version, do I have to wait for @q66 's changes to propagate?

@pullmoll that's strange, if I try to cross compile base-chroot I get the same error, as libevent gets pulled in.

**Comment by lfdebrux** [comment]
Update: after rebuilding cross-pkg-vdummy I can build libevent

**Comment by RossComputerGuy** [comment]
Huh, I get this same error with `unbound` when I try compiling for aarch64.

**Comment by Xlaits** [comment]
I am also having this issue with `unbound`, but building for armv5tel.
