### ISSUE TITLE
Update Requests: EFL and Phyton-EFL

### ISSUE THREAD

**Issue by Boebbele** [void-linux/void-packages#28104]
is it possible to update this 2 packages?
EFL 1.24.4 --> 1.25.1
Phyton-EFL 1.23.0 --> 1.25.0

https://www.enlightenment.org/download

Many many thanks!

**Comment by Anachron** [comment]
Normally we dont do update-requests, is there a specific reason for it? (CVE, crash, etc)

**Comment by Boebbele** [comment]
oh sorry I didn't know.  should I close the thread?
i have a problem with efreetd and the iconcache.  it works in archlinux with the latest version of EFL and Phyton-EFL.  hence the hope that it would be the same in voidlinux.

**Comment by Boebbele** [comment]
applies of course to the enlightenment desktop. efreetd runs under high CPU load and a lot of RAM.  however, the icon cache is often not recognized and the icons are not displayed under enlightenment.

**Comment by ericonr** [comment]
@Boebbele would you be willing to test the packages if I make a PR? I don't use enlightenment myself, so I don't believe I can test adequately.

**Comment by Boebbele** [comment]
yes of course, with great pleasure!

**Comment by ericonr** [comment]
@Boebbele please test #28501

**Comment by Boebbele** [comment]
Okay. I will test it this weekend. Thank you!

**Comment by Boebbele** [comment]
Have I to so this: ln -s for efl-devel? In void-GitHub  ist this for old efl-version.

**Comment by ericonr** [comment]
I don't think I touched the symlink... It should just work.

**Comment by Boebbele** [comment]
Yes it works!!! Perfektly! Great Job! Thank you! My system works great with this Update.  I will keep testing it.
