### ISSUE TITLE
[rfc] reproducible builds

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#28113]
Has Void considered to adopt reproducible builds?
Given the infrastructure already in place, how hard would it be?
Thanks.

https://reproducible-builds.org
https://wiki.archlinux.org/index.php/Reproducible_Builds

**Comment by ericonr** [comment]
> Given the infrastructure already in place, how hard would it be?

Very, someone(s) would have to finance a machine only for this, and setup and run the infrastructure for actually triggering builds according to some criteria. Archiving old packages would also be a big burden.

If you have improvements to packages and/or the build system to improve the reproducibility of packages, do feel free to PR/suggest them. Our kernels were made reproducible a while ago, for example. But I don't think we have human time or machine resources for full on testing distro reproducibility.

**Comment by dkwo** [comment]
I see, thanks for explaining.

**Comment by dm17** [comment]
I'm down to help crowd fund this.

**Comment by dm17** [comment]
I was reading over a conversation in the #voidlinux Libera channel and found it interesting that reproducible builds could be easier to create & manage due to the simplicity & design of Void's build system (as compared to others that have already accomplished reproducibility).
