### ISSUE TITLE
Deadbeef: please update due to a regression

### ISSUE THREAD

**Issue by AngryPhantom** [void-linux/void-packages#28140]
Please update Deadbeef to version 1.8.6 (or at least 1.8.5) since there is a regression that got fixed (some mp3 files were playing only 5 sec of audio and then stopped). Anyway, the latest release is 1.8.6. So, it would be really nice to have it in the repo.

Unfortunately, I'm not an expert in xbps-src, otherwise I'd posted a pull request. I tried compiling the latest version but I'm getting errors and don't know how to fix them. Probably because it needs clang or some other new dependency, I'm not sure.

I'm using a "half-baked" 1.8.4 version of it (1.8.3 from repo + author's patch/fix). That was the last one that I managed to compile myself without issues.

Thank you in advance. Cheers.

**Comment by biopsin** [comment]
Tested build against v1.8.6
so far fails to build without https://github.com/DeaDBeeF-Player/mp4p

```
Making all in external
make[2]: Entering directory '/builddir/deadbeef-1.8.6/external'
make[2]: *** No rule to make target 'mp4p/src/mp4p.c', needed by 'mp4p/src/libmp4p_a-mp4p.o'.  Stop.

```

**Comment by ericonr** [comment]
@AngryPhantom can you point at the patch? We could include it temporarily until someone figures out packaging the new version.

**Comment by AngryPhantom** [comment]
@ericonr 
Phew, took me a while to figure out where was it. Should be this [commit](https://github.com/DeaDBeeF-Player/deadbeef/commit/f024da21f02b1d40ecb6df115b6f4def7b0626c6).

**Comment by AngryPhantom** [comment]
P.S. Strange that there was a [pull request](https://github.com/void-linux/void-packages/pull/26175) that was closed but deadbeef didn't get the update to 1.8.4. How is it possible?

**Comment by biopsin** [comment]
probably it failed building for i686 and no atemts to resolve it or maybe closed by mistake

**Comment by AngryPhantom** [comment]
@biopsin Got it, thanks.

**Comment by ericonr** [comment]
Done in 6fb62e2a8636e8356425587665d847bd8b000bb4
