### ISSUE TITLE
w3m: The man page is in German

### ISSUE THREAD

**Issue by xinnna** [void-linux/void-packages#28146]
### System

* xuname:  
  Void 5.10.9_1 x86_64 GenuineIntel uptodate rFFF
* package:  
  `w3m`

### Expected behavior

`man w3m` displays the man page for `w3m` in English.

### Actual behavior

the man page is in German.

### Steps to reproduce the behavior

`man w3m`

**Comment by Anachron** [comment]
Can you give us your locale setup? (Env-Vars)

**Comment by ericonr** [comment]
Are you using `mdocml`? I couldn't reproduce this locally.

**Comment by xinnna** [comment]
I apologize for the delayed response.

I also have the English manual in `/usr/share/man/man1`.

My locale setup:
`xinnna@void ~ $: locale
LANG=tr_TR.UTF-8
LC_CTYPE="tr_TR.UTF-8"
LC_NUMERIC="tr_TR.UTF-8"
LC_TIME="tr_TR.UTF-8"
LC_COLLATE=C
LC_MONETARY="tr_TR.UTF-8"
LC_MESSAGES="tr_TR.UTF-8"
LC_PAPER="tr_TR.UTF-8"
LC_NAME="tr_TR.UTF-8"
LC_ADDRESS="tr_TR.UTF-8"
LC_TELEPHONE="tr_TR.UTF-8"
LC_MEASUREMENT="tr_TR.UTF-8"
LC_IDENTIFICATION="tr_TR.UTF-8"
LC_ALL=
xinnna@void ~ $: locale -a
C
POSIX
en_US.utf8
tr_TR.utf8`

I do have `mdocml` installed. I didn't know it was part of the `base-system` metapackage.

**Comment by ericonr** [comment]
Ok, I could reproduce it; without running `makewhatis -a` after installing `w3m`, I got the english man page. After running that, I got the german manpage (on glibc) and the japanese man page (on musl).
