### ISSUE TITLE
dante: sockd does not run in musl because `sched_getscheduler`/`sched_setscheduler` are not available in musl.

### ISSUE THREAD

**Issue by xoich** [void-linux/void-packages#28180]
Running `sockd` will result in this error:
```
/usr/bin/sockd
Jan 24 19:08:24 (1611511704.111253) sockd[21539]: error: 
serverinit(): sched_getscheduler(2): failed to retrieve current cpuscheduling policy: Function not implemented
````
The cause is that dante `configure` script mistakenly believes those functions are available. To make it work, after `./configure` I had to manually set `#define HAVE_SCHED_SETSCHEDULER 0` in `include/autoconf.h`. I'm not sure this is the best solution, but it solves the issue.

**Comment by ericonr** [comment]
@xoich would you mind testing https://github.com/void-linux/void-packages/pull/28184 and seeing if it fixes it for you completely?
