### ISSUE TITLE
Nvidia fails to install, when installed, doesn't work

### ISSUE THREAD

**Issue by goosewood** [void-linux/void-packages#282]
### System

* xuname:  
  Void 4.16.14_1 x86_64 GenuineIntel uptodate rr
* package:  
  nvidia 390.67_1

### Expected behavior
Installs smoothly. After installation, no driver issue/less issues that nouveau
### Actual behavior
Package fails as documents [here](https://github.com/voidlinux/void-packages/issues/14052). 
When using the work around proposed in at issue, xorg refuses to run with fatal error
```shell
(EE) no screens found(EE)
```
Sidenote, only one monitor prints the tty

Also of note, on unistall (i.e. returning to nouveau driver) no glx engine is installed (many programs returning glx_init() not found)
### Steps to reproduce the behavior
Install nvidia package on non-free
Work around to actually install the package
```shell
xinit
# fails
sudo xbps-remove -RF nvidia # returning to free drivers
sudo init 6 
# anything that needs openGL to work
```

Sorry for the rambling issue, kinda was in the irc channel for about a day and didn't get too far (but ran into a lot of silly errors that should probably be fixed)

**Comment by abenson** [comment]
To return to the free drivers, you need to reinstall libGL and libEGL. [Wiki](https://wiki.voidlinux.eu/Proprietary_Video_Drivers#Switching_back_to_the_open_source_drivers_2)

**Comment by goosewood** [comment]
My Xorg log doesn't even seem to be using the right drivers...
[Xorg.0.log](https://github.com/void-linux/void-packages/files/2125429/Xorg.0.log)

**Comment by alexjacobson95** [comment]
> @abenson Doing that method gives error "unresolvable shlib `libEGL.so.1'" on some packages. When forced, still doesn't even work...
> I'm not trying to return to free packages actually, I get "run-to-kernel panics" with them (I have a 10 series card), I more just want to get the non-free ones to work

I think you might be running into the same problem I've been having. I have a 10 series card too. Check out these for some insite:
https://github.com/voidlinux/void-packages/issues/14052
https://www.reddit.com/r/voidlinux/comments/aaowf0/bumblebee_issue_nvidia_still_on/

**Comment by abenson** [comment]
Since Void is now on 410.x, has the issues with the 10-series been solved?

**Comment by goosewood** [comment]
Hey, would love to test for you but I ended up getting fed up with the issue and distrohopped to Gentoo. Next time I try out void on this machine I'll see if they work.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by obunden** [comment]
@Johnnynator 
It's been over a year and no new information has surfaced regarding this. Can this be closed since the nvidia drivers have seen plenty of upgrades and the system in general? If this is still a thing someone will eventually speak up is my guess.
