### ISSUE TITLE
nostrip=yes in a template means the nopie lint doesn't even run

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#28203]
As can be seen in

https://github.com/void-linux/void-packages/blob/b4f67689a1455dcf3f8ac061214d77ddf8a634a5/common/hooks/post-install/06-strip-and-debug-pkgs.sh#L62

`nostrip=yes` makes it so nothing is actually checked.

I'm looking into this because I want to plug a check for textrels into this loop, but it won't do anything for `nostrip` packages.

**Comment by Johnnynator** [comment]
https://github.com/void-linux/void-packages/blob/b4f67689a1455dcf3f8ac061214d77ddf8a634a5/common/hooks/post-install/06-strip-and-debug-pkgs.sh#L62-L64
^ like this ?
