### ISSUE TITLE
pycharm: Unsupported Java Version

### ISSUE THREAD

**Issue by benalb** [void-linux/void-packages#28246]
### System

* xuname:  
  Void 5.10.10_1 x86_64 GenuineIntel uptodate rrrmDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
* package:  
  pycharm-community-2020.3.2_1

### Expected behavior
  launch pycharm and begin to create awesome python programs.

### Actual behavior
Unsupported Java Version
Java 11 or newer is required to run the IDE.
Please contact support at https://jb.gg/ide/critical-startup-errors

Your JRE: 1.8.0_272-b02 amd64 (Void)
/usr/lib/jvm/java-1.8-openjdk/jre

### Steps to reproduce the behavior
 Install pycharm-community and try it.

**Comment by ericonr** [comment]
You probably need openjdk11 and to select it with xbps-alternatives.

**Comment by benalb** [comment]
xbps-query -s jdk
[*] openjdk-jre-8u999_1     OpenJDK Java Development Kit (meta) - runtime components
[*] openjdk11-11.0.9+4_1    OpenJDK Java Development Kit
[*] openjdk8-jre-8u272b02_1 OpenJDK Java Development Kit (version 8) - runtime components

xbps-alternatives -l|grep jdk|grep current
 - openjdk8-jre (current)
 - openjdk11 (current)

**Comment by Chocimier** [comment]
Study `set -x; . /usr/bin/pycharm`, paste here if unsure what's wrong.

**Comment by benalb** [comment]
`sudo xbps-remove -R openjdk-jre` did the trick, but I do not know why. I'm closing the issue, and will do more test in a VM. Thanks.
