### ISSUE TITLE
[Package request] ruffle

### ISSUE THREAD

**Issue by kawaiiamber** [void-linux/void-packages#28280]
ruffle - Flash emulator written in the rust language
homepage: https://ruffle.rs
So far, only action script 2 can be emulated, but emulation for action script 3 is being worked on. This project seems way better than lightspark or gnash.

**Comment by Johnnynator** [comment]
They do not have any stable releases yet, and we do not package nightly releases.

**Comment by kawaiiamber** [comment]
> They do not have any stable releases yet, and we do not package nightly releases.

Ah, I see. Should I close issue and re-open once there's a release?

**Comment by ericonr** [comment]
Please do so, we want to avoid tracking the release status of every single requested package.

**Comment by rgally** [comment]
Ruffle has [stable releases](https://github.com/ruffle-rs/ruffle/releases/tag/v0.2.0) now! So that's nice.
