### ISSUE TITLE
xuname says notuptodate even when system is up to date when not run as root

### ISSUE THREAD

**Issue by lfdebrux** [void-linux/void-packages#28322]
### System

* xuname:  Void 5.10.11_1 x86_64-musl GenuineIntel notuptodate rF (but I am up to date)
* package:  xtools-0.62_1

### Expected behavior

When I have just run `xbps-install -Su` xuname does not say `notuptodate`, even if I'm not running it as root.

### Actual behavior

```
$ sudo xbps-install -u
$ xuname
Do you want to import this public key? [Y/n]
Void 5.10.11_1 x86_64-musl GenuineIntel notuptodate rF
```

### Steps to reproduce the behavior

I believe the problem is related to the output of `xbps-install -Mun`, which when not run as root asks about importing a public key:

```
$ xbps-install -Mun
`https://alpha.de.repo.voidlinux.org/current/musl' repository has be
en RSA signed by "Void Linux"
Fingerprint: 60:ae:0c:d6:f0:95:17:80:bc:93:46:7a:89:af:a3:2d
Do you want to import this public key? [Y/n]
```

If I run `sudo xbps-install -Mun` then no message is printed, and then if I run `sudo xuname` then it correctly reports that my system is up to date.

**Comment by Johnnynator** [comment]
This sounds like a permission issue.
Can you provide the output of `sudo xbps-pkgdb xbps` and `ls -l /var/db/xbps/keys/`

**Comment by lfdebrux** [comment]
@Johnnynator `sudo xbps-pkgdb xbps` produces no output 🤔 

I get permission denied if I do `ls -l /var/db/xbps/keys` without sudo, with sudo I can see there are two files:

```
total 6
-rw------- 1 root root 1410 Jan 28 18:15 3d:b9:c0:50:41:a7:68:4c:2e:
2c:a9:a2:5a:04:b7:3f.plist
-rw-r--r-- 1 root root 1410 Jan 28 04:25 60:ae:0c:d6:f0:95:17:80:bc:
93:46:7a:89:af:a3:2d.plist
```

**Comment by Anachron** [comment]
Permissions should be

```
$ ls -l /var/db/xbps/keys
-rw-r--r-- 1 root root 1410  1. Mai 2017  3d:b9:c0:50:41:a7:68:4c:2e:2c:a9:a2:5a:04:b7:3f.plist
-rw-r--r-- 1 root root 1410 28. Jan 06:41 60:ae:0c:d6:f0:95:17:80:bc:93:46:7a:89:af:a3:2d.plist
```

You are missing permissions on the `3d:b9:c0:50:41:a7:68:4c:2e:2c:a9:a2:5a:04:b7:3f.plist` file.

**Comment by Duncaen** [comment]
The directory should also be readable by others, thats why it tries to import the key that is already readable.

**Comment by lfdebrux** [comment]
Okay, ran the following commands to update the permissions:

```
# chmod 644 /var/db/xbps/keys/*
# chmod 755 /var/db/xbps/keys
```

`xuname` now works as expected. Thanks for the help! 

Not sure how the permissions got messed up but never mind.
