### ISSUE TITLE
Gnome installation fails 

### ISSUE THREAD

**Issue by randomusero8** [void-linux/void-packages#28349]
Gnome fails to start on a fresh installation following the full disk encryption guide. The appropriate pkgs are installed and enabled (dbus, elogind, gnome, gdm) but gnome does not start when enabling the gdm service.

If I use the void-installer script and install and enable all the same pkgs and services, gnome will start fine.

So it seems to be something with the disk encryption guide install that makes gnome not work. Is this possible?

**Comment by ericonr** [comment]
Did you figure it out?

**Comment by randomusero8** [comment]
I thought I did, but I did not.

**Comment by Gottox** [comment]
Can you provide more information on what exactly does not work and are there any logs or further information which could help? - I can't read much more than "Does not work" from your PR.

**Comment by randomusero8** [comment]
After installation following the FDE guide runit is not installed. Even after installing it there still are problems with other things not working. Following the chroot guide results in a usable system. 

So I have everything working now, but from my experience there is something wrong with the FDE guide that results in a unusable system.
