### ISSUE TITLE
A bunch of configure args passed to bind are wrong/useless

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#28351]
### Expected behavior

Running configure for `bind` doesn't show unrecognized options.

### Actual behavior

Running configure for `bind` gets me:

```
Unrecognized options:
    --enable-threads, --enable-atomic, --enable-ipv6, --with-randomdev, --with-ecdsa, --with-eddsa, --without-gost, --enable-openssl-hash, --enable-fetchlimit, --enable-sit, --enable-seccomp, --with-geoip
```

I have removed seccomp, because it lead to a misleading build option in package metadata, but haven't touched the others.

### Steps to reproduce the behavior

`./xbps-src configure bind`

**Comment by heliocat** [comment]
I just did a survey of the removed options:
--enable-atomic - removed 9.13.3 (commit 5024)
--enable-ipv6 - made default 9.14
--enable-openssl-hash - removed 9.14, default was already yes
--enable-seccomp - removed 9.13.0 (commit 4898)
--enable-sit - removed 9.11, replaced with DNS COOKIE option in configs (commit 4152)
--enable-threads - on-threaded support removed 9.13.3 (commit 5011)
--with-geoip - marked as obsolete in 9.16
--with-randomdev - removed 9.13.0 (commit 4936)
--without-gost - GOST support removed 9.13.1 (commit 4961)
--enable-fetchlimit - removed pre-bind9
--with-ecdsa - comes from openssl availability (removed 9.14)
--with-eddsa - comes from openssl availability (removed 9.14)
