### ISSUE TITLE
[RFC] Add a tools directory?

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#28371]
While maintaining void-packages, a lot of people have written small tools/scripts to help with simple tasks. There is a part of `xtools`, for example, that's only useful inside void-packages (unlike, for example, `xi` or `xls`).

I'm proposing a `tools/` directory to which we could move some of xtools (moving `xlint` to void-packages has even been discussed a few times, since it'd make it possible to add new variables to templates in a single go; `xrevbump` and `xsubpkg` are also not very useful outside of void-packages).

Further, there are small scripts like @Johnnynator's one for handling git submodules, @Chocimier's for detecting cycles in dependencies and @Piraty's for launching multiple builds at the same time. I'd also put forward the one I have to check what I have installed from packages listed in void-updates, so I have an idea of what I can easily test.

Ping @leahneukirchen

**Comment by leahneukirchen** [comment]
I'm fine with moving `xlint`, indifferent on the others.

**Comment by ahesford** [comment]
If this happens, https://github.com/ahesford/xbps-cycles should go in there too.

**Comment by fosslinux** [comment]
Can this be closed?

**Comment by ericonr** [comment]
@fosslinux we've added cycles specifically, but haven't talked about moving `xlint` or similar yet. I guess we can close for now, and revisit when someone does the porting and opens a PR.
