### ISSUE TITLE
Cargo fails to compile

### ISSUE THREAD

**Issue by RossComputerGuy** [void-linux/void-packages#28372]
### System

* xuname:  `Void 5.10.10_1 x86_64 AuthenticAMD uptodate rrrrmmnFFFFF`
* package:  
  *affected package(s) including the version*: cargo-0.49.0_1

### Expected behavior
Cargo should be packages

### Actual behavior
```
error[E0283]: type annotations needed
   --> src/cargo/util/config/de.rs:530:63
    |
530 |                 seed.deserialize(Tuple2Deserializer(1i32, env.as_ref()))
    |                                                               ^^^^^^ cannot infer type for struct `std::string::String`
    |
    = note: cannot satisfy `std::string::String: AsRef<_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0283`.
error: could not compile `cargo`

To learn more, run the command again with --verbose.
=> ERROR: cargo-0.49.0_1: do_build: './cargo build --release ${cargs}' exited with 101
=> ERROR:   in do_build() at srcpkgs/cargo/template:10
```

### Steps to reproduce the behavior
`./xbps-src pkg cargo`

**Comment by ericonr** [comment]
Could reproduce.

**Comment by RossComputerGuy** [comment]
I've found a promising looking patch - https://github.com/alexcrichton/cargo/commit/f097d02ea62111493b9f06d096a94dfddd020415

**Comment by RossComputerGuy** [comment]
I tested the patch myself and it works. I'll submit a PR with this patch.

**Comment by RossComputerGuy** [comment]
https://github.com/void-linux/void-packages/pull/28373 fixed
