### ISSUE TITLE
Package request: Non DAW

### ISSUE THREAD

**Issue by marek-lach** [void-linux/void-packages#28370]
**About:** A DAW, stable under heavy loads, with a more digestible user interface.

**Repository:** **_edit:_** last posted sources are here: https://git.kx.studio/non/non

**License:** GNU General Public License v2.0

**Why?** Useful as something just in-between the power of Audacity, and Ardour.

**Comment by biopsin** [comment]
Also how the dependecy https://github.com/original-male/ntk (fltk fork with patches) should be treated, as submodule? since there has not been any official release yet.

**Comment by jrigg** [comment]
There have been official releases of NTK, non-timeline, non-mixer and non-sequencer in the last few days. The web site has not been uopdated to show this yet.  Tagged releases can be downloaded from GitHub:
https://github.com/original-male/non
https://github.com/original-male/ntk

**Comment by jrigg** [comment]
Looks like Non is no longer mirrored at GitHub. It can be downloaded from the project's official git repo:
https://git.tuxfamily.org/non/non.git
https://git.tuxfamily.org/non/fltk.git

Note that the fltk.git here is actually NTK (which was originally forked from FLTK).

**Comment by sburris0** [comment]
Now it can't be downloaded from there either?

**Comment by ericonr** [comment]
The homepage seems to exist https://non.tuxfamily.org/wiki/Downloads

**Comment by jrigg** [comment]
The mailing list is gone too. I've emailed Jonathan Liles to try and find out what's going on. I'll report back if I get a reply.

**Comment by jrigg** [comment]
It doesn't look good. Jonathan has removed public access to Non DAW code due to the way the NSM fork was done (and I can't say I blame him).

**Comment by biopsin** [comment]
I guess issue resolved, link to NTK (https://github.com/falkTX/ntk)

**Comment by jrigg** [comment]
The issue has not been resolved. The linked NTK repo is a clone that FalkTX made just before the original Non repos were closed down. The last official release of non DAW, including non-session-manager, is unavailable. The previous official release is very out of date now.
