### ISSUE TITLE
albert 0.14.22 and later is both non-free (source-available) and copyright-infringing

### ISSUE THREAD

**Issue by eli-schwartz** [void-linux/void-packages#28394]
https://github.com/albertlauncher/albert/commit/18018c8f7b7dbbc366420c24ba1209bbda1f5267 removed the GPL license. New terms are, apparently,

> I explicitly allow packagers for linux distributions to package and distribute this software (note this applies only for the core app and library since the plugins may have their own licenses) if their distribution is avalailable free (no cost) for everybody. Modifications/patches have to come back upstream. You must not distribute a modified version of this software. Rationale is that I dont want users to run other peoples code in my name, i.e. protect users in a sense that they can check upstream to see what they get. Further this also avoids the potentially malicious ppas.

Unfortunately, a fair amount of code in the software was contributed by other people, under the original GPL terms, and cannot be included in a non-GPL work.

Ref:
https://bugs.archlinux.org/task/69366
https://github.com/albertlauncher/albert/issues/765#issuecomment-771086409

Recommendation:

Drop it like a hot potato.

(Alternatively, downgrade it and freeze it to an old version.)

**Comment by ericonr** [comment]
@Johnnynator and @q66 were the last to touch this in any capacity, ahesford only did the python 3.9 bump.
