### ISSUE TITLE
Package Request: Add ntfs3 driver from paragon as dkms

### ISSUE THREAD

**Issue by Rajalolxd** [void-linux/void-packages#28395]
for reference https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ntfs3-dkms

**Comment by ericonr** [comment]
What are its advantages compared to `ntfs-3g`?

**Comment by ericonr** [comment]
That's not a DKMS package, that's a collection of patches from the kernel ML frankensteined into a DKMS package. Upstream has not seen fit to make a proper package out of it, we are not going to be making it into a package ourselves, sorry.
