### ISSUE TITLE
libopenal: missing dependency

### ISSUE THREAD

**Issue by RossComputerGuy** [void-linux/void-packages#28427]
### System

* xuname:  `Void 5.10.12_1 x86_64 AuthenticAMD notuptodate rrrrmmnFFFFF`
* package:  `libopenal-1.21.0_1`

### Expected behavior
`libopenal` should be packaged

### Actual behavior
```
=> libopenal-1.21.0_1: building [cmake] (dependency of gst-plugins-bad1) for x86_64...
   [host] pkg-config-0.29.2_2: found (/host/binpkgs)
   [host] cmake-3.19.3_1: found (/host/binpkgs)
=> ERROR: libopenal-1.21.0_1: target dependency 'fmpeg-devel' does not exist!
```
I think this is a typo but I'm just making sure.

### Steps to reproduce the behavior
`./xbps-src pkg libopenal`

**Comment by FollieHiyuki** [comment]
Definitely a typo in the template. I have no issue building this package.

**Comment by ericonr** [comment]
```
makedepends="zlib-devel alsa-lib-devel pulseaudio-devel SDL2-devel ffmpeg-devel
 jack-devel $(vopt_if sndio sndio-devel)"
```

Please check the original source before opening an issue.
