### ISSUE TITLE
Distfiles for x265 can't be accessed

### ISSUE THREAD

**Issue by RossComputerGuy** [void-linux/void-packages#28424]
### System

* xuname:  `Void 5.10.12_1 x86_64 AuthenticAMD notuptodate rrrrmmnFFFFF`
* package:  `x265-3.4_1`

### Expected behavior
The do-fetch step should finish

### Actual behavior
```
=> x265-3.4_1: installing host dependencies: nasm-2.15.05_1 nasm-2.15.05_1 cmake-3.19.3_1 ...
=> x265-3.4_1: running do-fetch hook: 00-distfiles ...
=> x265-3.4_1: fetching distfile 'x265_3.4.tar.gz'...
https://bitbucket.org/multicoreware/x265/downloads/x265_3.4.tar.gz: Not Found
=> ERROR: x265-3.4_1: failed to fetch x265_3.4.tar.gz.
```

### Steps to reproduce the behavior
`./xbps-src -N pkg x265`

**Comment by ericonr** [comment]
They seem to have removed it.

It's the same link that http://x265.org/v3-4-is-released/ has

There is this repo https://bitbucket.org/multicoreware/x265_git/src/master/ but it doesn't contain a 3.4 release. You will have to use our distfile cache for now.

**Comment by RossComputerGuy** [comment]
Alright, what's the link for it on the distfile cache?

**Comment by ericonr** [comment]
The README explains how to use a distfiles mirror, just look for it.

**Comment by ericonr** [comment]
Anyway, we need to find a new upstream, maybe? idk

**Comment by RossComputerGuy** [comment]
Alright and yeah, let's keep this issue open until we find a better mirror

**Comment by RossComputerGuy** [comment]
https://bitbucket.org/multicoreware/x265_git/get/3.4.tar.gz would this work?

**Comment by RossComputerGuy** [comment]
```sh
_commit="a4f320054d67"
wrksrc="multicoreware-x265_git-${_commit}"
distfiles="https://bitbucket.org/multicoreware/x265_git/get/${version}.tar.gz"
checksum=7f2771799bea0f53b5ab47603d5bea46ea2a221e047a7ff398115e9976fd5f86
```
I changed these variables and it builds for me.

**Comment by ericonr** [comment]
Ah nice, it isn't listed in downloads but the tag is still there. https://bitbucket.org/multicoreware/x265_git/downloads/?tab=downloads and https://bitbucket.org/multicoreware/x265_git/downloads/?tab=tags .

It seems they moved from mercurial to git, and made a new repo for it. Arch is still using the mercurial repo and they will fail to fetch the package.

Please make a PR to fix.

**Comment by RossComputerGuy** [comment]
Yeah, I'll make a PR with it.

**Comment by RossComputerGuy** [comment]
I've opened the PR: https://github.com/void-linux/void-packages/pull/28426
