### ISSUE TITLE
Module signing

### ISSUE THREAD

**Issue by anon-lestat** [void-linux/void-packages#28440]
* xuname:  
  Void 5.4.94_1 x86_64-musl GenuineIntel uptodate rDFFF
* package:  
linux5.4.94_1

### Expected behavior
Enable enforced module signing and system boots without allowing unsigned modules.
### Actual behavior
Linux doesnt start 
### Steps to reproduce the behavior
Make these changes in kernel config before compiling:
CONFIG_MODULE_SIG=y
CONFIG_MODULE_SIG_ALL=y
CONFIG_MODULE_SIG_SHA1=y
CONFIG_MODULE_SIG_HASH="sha1"
Compile, Package and install the kernel.

Add module.sig_enforce=1 to boot parameters,
Start the system.

The kernel config used: https://notabug.org/anonymous-lestat/Void-Hardened-Kernel/src/master/x86_64-dotconfig-custom

**Comment by anon-lestat** [comment]
Kernel is tainted which means modules didnt get signed.

**Comment by ahesford** [comment]
You are building a custom kernel, this is not a Void issue.
