### ISSUE TITLE
Avogadro: no engines loaded

### ISSUE THREAD

**Issue by sburris0** [void-linux/void-packages#28458]
### System

* xuname:  
Void 5.10.12_1 x86_64 AuthenticAMD uptodate rrrmFFFFF
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
avogadro-1.2.0_8

### Expected behavior
Should start without warnings and not have missing ui elements

### Actual behavior
On startup a "No engines loaded. It is unlikely this application will function correctly. Please correct this error." message appears. Many options and tools are missing from the UI making it impossible to draw molecules.

### Steps to reproduce the behavior
1. Install and run avogadro

This is likely due to a missing dependency.

**Comment by ericonr** [comment]
Hm, are you `ignorepkg`ing `removed-packages`? `avogadro` has been removed from Void, since it depended on Qt4, which has been EoL for a long while.

**Comment by sburris0** [comment]
I actually don't even know how to do that. I know removed-packages is definitely installed.

**Comment by ericonr** [comment]
It will, because it hasn't been cleaned from the repository. But it should no longer be installable.
