### ISSUE TITLE
baresip: module alsa.so: No such file or directory

### ISSUE THREAD

**Issue by KozakIvan** [void-linux/void-packages#28498]
### System

* xuname:  
Void 5.10.13_1 x86_64 GenuineIntel notuptodate rFFFF
* package:  
baresip-0.6.5_2

when run baresip an error appears
dl: mod: /usr/lib/baresip/modules/alsa.so (/usr/lib/baresip/modules/alsa.so: cannot open shared object file: No such file or directory)
module alsa.so: No such file or directory

**Comment by ericonr** [comment]
There definitely isn't an `alsa.so` file in the package, and I'm not sure there should be one...

@Johnnynator 

Anyway, maybe the package should also be rebuilt for libdir changes.
