### ISSUE TITLE
vboot-utils: please update

### ISSUE THREAD

**Issue by ackalker** [void-linux/void-packages#28507]
The `vboot-utils` package version is very, very old (dating back to somewhere in 2016) and is missing some important new features and fixes.
Please update the package.

**Comment by ackalker** [comment]
The package version in Void Linux corresponds to upstream Git tag `release-R89-13729.B` dated 2015-07-09, while the latest upstream release is tagged `release-R89-13729.B` dated 2021-01-08.

**Comment by the-maldridge** [comment]
Note that the issue template says specifically not to open requests for updates as [we have a script for that](http://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt)

**Comment by ackalker** [comment]
@the-maldridge The package template directory doesn't have an `update` file in it so the script will never flag this package as outdated. The link you gave proves this.

**Comment by ackalker** [comment]
Thanks for the quick response!
