### ISSUE TITLE
Packages present in the repos but not in srcpkgs/

### ISSUE THREAD

**Issue by maxice8** [void-linux/void-packages#2854]
Tested from available in x86_64

- Filtered against provides= (xbps-query -RS '' -p provides | grep $pkg)
- Ignore 32bit packages
- Ignore packages that have the proto string due to xorgproto and all the proto stuff

---

- [ ] ccnet
- [ ] ccnet-devel
- [ ] ccnet-python

**Comment by maxice8** [comment]
Done with.

```
$ cat /home/terran/bin/find-removed-packages
#!/bin/sh
list="$(mktemp)"
xbps-query -Rs '' -p provides | cut -d ' ' -f2 > "$list"
get_all_pkgs() {
	xbps-query -Rs '' | cut -d ' ' -f2 | while read -r pkg
	do
		[ -z "${pkg##*proto*}" ] && continue
		[ -z "${pkg##*32bit*}" ] && continue
		xbps-uhelper getpkgname "$pkg"
	done
}
get_all_pkgs | while read -r pkg
do
	grep -q "$pkg" "$list" && continue
	if [ ! -e srcpkgs/"$pkg"/template ]
	then
		echo "$pkg"
	fi
done
```

**Comment by maxice8** [comment]
@asergi can confirm python-related packages ? (specially the python3.4 ones)

Need @Gottox @Duncaen @Vaelatern or @the-maldridge to confirm and effect the removal.

**Comment by asergi** [comment]
All `python3.4-*` packages can be nuked.

**Comment by maxice8** [comment]
Thanks

**Comment by the-maldridge** [comment]
Here's the filesystem list for python3.4: http://ix.io/1nXl, once confirmed I'll queue the removals and clean task.

**Comment by maxice8** [comment]
On Sun, Sep 30, 2018 at 01:45:57PM -0700, Michael Aldridge wrote:
> Here's the filesystem list for python3.4: http://ix.io/1nXl, once confirmed I'll queue the removals and clean task.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/2854#issuecomment-425750696

LGTM

**Comment by maxice8** [comment]
@Gottox lets nuke ? :D

**Comment by maxice8** [comment]
@Gottox didn't even notice, nice work :D , just 3 remain

**Comment by Gottox** [comment]
I nuked them last week already ;)

**Comment by maxice8** [comment]
On Sun, Oct 14, 2018 at 12:54:41PM -0700, Enno Boland wrote:
> ```
> python-zc.lockfile-1.3.0_1
> python3-zc.lockfile-1.3.0_1
> volume_key-python-0.3.12_1
> ```
> Those are the remainders?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/2854#issuecomment-429656973

volume_key-python exists

**Comment by Gottox** [comment]
Should now be gone. I'm checking the list on musl and aarch builders now.

**Comment by Gottox** [comment]
Close, reopen if we mssed something.

**Comment by Chocimier** [comment]
Indexes other than x86_64 still contain removed packages. These need to be removed to make indexes ready to use in repology:

gst-plugins-ugly on musl_armv6l-musl
rfkill on musl_armv6l-musl
wxGTK on musl_armv6l-musl
wxGTK-devel on musl_armv6l-musl
gst-plugins-ugly on musl_armv7l-musl
rfkill on musl_armv7l-musl
wxGTK on musl_armv7l-musl
wxGTK-devel on musl_armv7l-musl
gst-plugins-ugly on musl_x86_64-musl
rfkill on musl_x86_64-musl
transfig on musl_x86_64-musl
wxGTK on musl_x86_64-musl
wxGTK-devel on musl_x86_64-musl

… but there are also others:

akonadi
akonadi-devel
alsa-lib-python
caja-CopyAgent
ccnet
ccnet-devel
ccnet-python
ceph
crystal-bin
fcitx-qt5
fcitx-qt5-devel
filteraudio-devel-git
filteraudio-git
flao
flow
fswatch-devel
gcc-c++
geis-python3.4
geoclue
geoclue-devel
glew19
glew19-devel
gmock
gmock-devel
go-cross-darwin
go-cross-freebsd
go-cross-linux
go-cross-windows
grantlee
grantlee-devel
gst-editing-services
gst-editing-services-devel
gst-plugins-bad-devel
gst-plugins-base
gst-plugins-base-devel
gst-plugins-good
gstreamer
gstreamer-devel
gtk2-vnc-python
gwenhywfar-qt
hexchat-python
icecat-devel
icecat-i18n-be
kdegraphics-strigi-analyzer
kfilemetadata
kfilemetadata-devel
libappstream-builder
libappstream-glib
libbson-devel
libcilkrts
libcilkrts-devel
libcrypto37
libcrypto38
libcrypto41
libcrypto42
libcrypto43
libfm-qt5
libfm-qt5-devel
libfwupd
libhunspell1.7
libixion11
libixion11-devel
libkcapi
libkcapi-devel
libllvm3.8
libllvm4.0
libllvm5.0
libmediaart2
libmediaart2-devel
libmega
libmega-devel
libmongoose
liborcus11
liborcus11-devel
libpam-google-authenticator
libpyside-python3.4
libpyside-python3.4-devel
libqtelegram-ae
libqtelegram-ae-devel
libshiboken-python3.4
libshiboken-python3.4-devel
libspa-lib
libspa-lib-devel
libssl38
libssl39
libssl43
libssl44
libssl45
libtls10
libtls11
libtls15
libtls16
libtls17
libupower-glib1
libxbps-beta
libxbps-beta-devel
lumina-devel
mate-polkit-devel
megacmd
megatools-devel
mozjs17
mozjs17-devel
mozjs38
mozjs38-devel
mutt-kz
nautilus-CopyAgent
newsbeuter
nvidia304-libs
nvidia304-opencl
panda
pflask-git
phorward-devel
php-mcrypt
phpMyAdmin
platform
platform-devel
poppler-qt4
poppler-qt4-devel
python3.4-gobject
python3.4-PyQt4
python3.4-PyQt4-dbus
python3.4-PyQt4-phonon
python3.4-pyside
python3.4-pyside-phonon
python3.4-shiboken
python3-pytest-cov
python-webkit
qt5-enginio
qt5-enginio-devel
qt5-plugin-gtk
R-cran-lattice
rpm-devel
rpm-python
strigi
strigi-devel
TelegramQML
TelegramQML-devel
telepathy-qt
telepathy-qt-devel
telepathy-qt-farstream
uwsgi-python3.4
uzbl-tabbed
valadoc
vulkan-validation-layers
webkitgtk
webkitgtk2
webkitgtk2-devel
webkitgtk-devel
xbps-beta
xfce4-mixer
xombrero
xproto
xsoldier
yaml
znc-python3.4

**Comment by Chocimier** [comment]
Can you @Gottox @Duncaen @the-maldridge remove packages from non-x86_64? If you can, i'll regenerate list, as one from prevoius post became outdated. Removal will make Void ready to inclusion into Repology.

**Comment by maxice8** [comment]
From the script above:

```
ccnet
ccnet-devel
ccnet-python
goffice0.8-devel
libapp-devel
libcrypto43
libhunspell
libssl45
libtls17
mtxclient-devel
pkgconf-devel
python3-pytest-cov
rpm-python
uzbl-tabbed
```

**Comment by jnbr** [comment]
if `libcrypto43` gets removed, `linux4.17` should be removed as well

**Comment by Gottox** [comment]
I'm scheduling the removal for later today.

**Comment by Gottox** [comment]
@jnbr #5367

**Comment by Chocimier** [comment]
Thanks! Here is a current list:

akonadi
akonadi-devel
alsa-lib-python
caja-CopyAgent
ccnet
ccnet-devel
ccnet-python
ceph
crystal-bin
fcitx-qt5
fcitx-qt5-devel
filteraudio-devel-git
filteraudio-git
flao
flow
fswatch-devel
gcc-c++
geis-python3.4
geoclue
geoclue-devel
glew19
glew19-devel
gmock
gmock-devel
go-cross-darwin
go-cross-freebsd
go-cross-linux
go-cross-windows
goffice0.8-devel
grantlee
grantlee-devel
gst-editing-services
gst-editing-services-devel
gst-plugins-bad-devel
gst-plugins-base
gst-plugins-base-devel
gst-plugins-good
gst-plugins-ugly
gstreamer
gstreamer-devel
gtk2-vnc-python
gwenhywfar-qt
hexchat-python
icecat-devel
icecat-i18n-be
kdegraphics-strigi-analyzer
kfilemetadata
kfilemetadata-devel
libapp-devel
libappstream-builder
libappstream-glib
libbson-devel
libcilkrts
libcilkrts-devel
libcrypto37
libcrypto38
libcrypto41
libcrypto42
libcrypto43
libfm-qt5
libfm-qt5-devel
libfwupd
libhunspell
libixion11
libixion11-devel
libkcapi
libkcapi-devel
libllvm3.8
libllvm4.0
libllvm5.0
libmediaart2
libmediaart2-devel
libmega
libmega-devel
libmongoose
liborcus11
liborcus11-devel
libpam-google-authenticator
libpyside-python3.4
libpyside-python3.4-devel
libqtelegram-ae
libqtelegram-ae-devel
libshiboken-python3.4
libshiboken-python3.4-devel
libspa-lib
libspa-lib-devel
libssl38
libssl39
libssl43
libssl44
libssl45
libtls10
libtls11
libtls15
libtls16
libtls17
libump-devel-git
libupower-glib1
libxbps-beta
libxbps-beta-devel
lumina-devel
mate-polkit-devel
megacmd
megatools-devel
mozjs17
mozjs17-devel
mozjs38
mozjs38-devel
mtxclient-devel
mutt-kz
nautilus-CopyAgent
newsbeuter
nvidia304-libs
nvidia304-opencl
panda
pflask-git
phorward-devel
php-mcrypt
phpMyAdmin
pkgconf-devel
platform
platform-devel
poppler-qt4
poppler-qt4-devel
python3.4-gobject
python3.4-PyQt4
python3.4-PyQt4-dbus
python3.4-PyQt4-phonon
python3.4-pyside
python3.4-pyside-phonon
python3.4-shiboken
python3-pytest-cov
python-webkit
qt5-enginio
qt5-enginio-devel
qt5-plugin-gtk
R-cran-lattice
rfkill
rpm-devel
rpm-python
strigi
strigi-devel
TelegramQML
TelegramQML-devel
telepathy-qt
telepathy-qt-devel
telepathy-qt-farstream
transfig
uwsgi-python3.4
uzbl-tabbed
valadoc
vulkan-validation-layers
webkitgtk
webkitgtk2
webkitgtk2-devel
webkitgtk-devel
wxGTK
wxGTK-devel
xbps-beta
xfce4-mixer
xombrero
xproto
xsoldier
yaml
znc-python3.4

And a script to generate it:
```
#!/bin/sh
repos="x86_64 armv6l armv7l i686 nonfree/armv6l nonfree/armv7l nonfree/i686 nonfree/x86_64 multilib/x86_64 multilib/nonfree/x86_64 musl/armv6l-musl musl/armv7l-musl musl/x86_64-musl musl/nonfree/armv6l-musl musl/nonfree/armv7l-musl musl/nonfree/x86_64-musl aarch64/aarch64-musl aarch64/aarch64 aarch64/nonfree/aarch64-musl aarch64/nonfree/aarch64 aarch64/nonfree/x86_64"

templates="$(mktemp)"
inrepo="$(mktemp)"

ls "$(xdistdir)/srcpkgs" | sort > "$templates"

for i in $repos; do
	filename="$(echo "$i" | tr / _)"
	wget -q -O "$filename-repodata.tar.xz" "https://alpha.de.repo.voidlinux.org/current/$i-repodata"
	tar xf "$filename-repodata.tar.xz"
	grep -Po '^\t<key>\K.+(?=</key>)' index.plist
done | sed 's/-32bit//' | sort -u > "$inrepo"

comm -31 "$templates" "$inrepo"
rm "$templates" "$inrepo"
```

**Comment by Chocimier** [comment]
Any progress?

**Comment by Gottox** [comment]
yes :)
