### ISSUE TITLE
FTBFS: rkt

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#28554]
### System
* package:  
  * `rkt-1.30.0`

### Expected behavior

It to compile

### Actual behavior

https://void.johnnynator.dev/logs/openssl/x86_64/bad/rkt.txt

```
=> rkt-1.30.0_2: running do_build ...
stage1/rootfs.mk:20: stage1/usr_from_coreoskvmhostsrcfly/usr_from_coreoskvmhostsrcfly.mk: No such file or directory
make: *** No rule to make target 'stage1/usr_from_coreoskvmhostsrcfly/usr_from_coreoskvmhostsrcfly.mk'.  Stop.
make: *** Waiting for unfinished jobs....
=> ERROR: rkt-1.30.0_2: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/gnu-configure.sh:13
```

@thypon Do you have any needs for this package or plans to fix it?

The project is considered ended upstream and I would propose to just remove it from the Void repo.

**Comment by thypon** [comment]
Yeah we should remove that.

**Comment by ericonr** [comment]
At least docker2aci is also related to rkt, and should probably be removed... It's even been archived https://github.com/appc/docker2aci

@thypon could you take a look if there are any more packages we should remove?

**Comment by thypon** [comment]
yeah, this one too, should be removed
