### ISSUE TITLE
Package request: gmnisrv

### ISSUE THREAD

**Issue by sburris0** [void-linux/void-packages#28574]
Source: https://git.sr.ht/~sircmpwn/gmnisrv
Description: a server for the gemini protocol
License: GPLv3

**Comment by ericonr** [comment]
This doesn't work on LibreSSL, but we *are* switching to OpenSSL. If it works with 1.1.1, should be mostly ok to package.

**Comment by kawaiiamber** [comment]
> This doesn't work on LibreSSL, but we _are_ switching to OpenSSL. If it works with 1.1.1, should be mostly ok to package.

VOID is switching to OpenSSL?

**Comment by cinerea0** [comment]
Wasn't there some discussion that stated there was going to be a freeze on new gemini packages?

**Comment by cinerea0** [comment]
This project doesn't appear to use tagged releases, so I don't think it meets Void's packaging requirements.

**Comment by ericonr** [comment]
> This project doesn't appear to use tagged releases, so I don't think it meets Void's packaging requirements.

Indeed it doesn't. Unless upstream is on the cusp of a release, which afaik they aren't, I don't think we should track their status indefinitely. Closing.
