### ISSUE TITLE
pari-seadata: fix vcopy

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#28608]
Dear @sgn and @motorto ,
compared to what was working for me in #24946 it seems `seadata` and `seadata-big` should have `vcopy data/seadata/sea* usr/share/pari/seadata` not `vcopy data/seadata/sea* usr/share/pari`.
Otherwise, if you issue `poldegree(ellmodulareqn(211)[1])` it will fail.
Do you want me to open a pr?
Thanks.

**Comment by motorto** [comment]
Hum weird , I will look into it.
Meanwhile if it fixes your issue open a PR !
