### ISSUE TITLE
kiwix-tools: undefined symbol

### ISSUE THREAD

**Issue by IcedQuinn** [void-linux/void-packages#28615]
### System

* xuname:  Void 5.10.13_1 x86_64 GenuineIntel notuptodate rrFF
* package:  kiwix-tools-3.1.2_1

### Expected behavior

`kiwix-serve` should fail because it was given no command line arguments.

### Actual behavior

```
kiwix-serve: symbol lookup error: kiwix-serve: undefined symbol: _ZN5kiwix5splitERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_b
```

### Steps to reproduce the behavior

- Install `sudo xbps-install kiwix-tools`
- `kiwix-serve`

**Comment by ericonr** [comment]
Should be fixed in master. Thanks for reporting.

For the record, most of these can be solved with a simple rebuild, if you want to open a PR / fix them locally before it's fixed in void-packages.

**Comment by IcedQuinn** [comment]
```
Usage:
	kiwix-serve [OPTIONS] ZIM_PATH+
	kiwix-serve --library [OPTIONS] LIBRARY_PATH
```
:+1:
