### ISSUE TITLE
Kicad pcbnew complains about wxPython version

### ISSUE THREAD

**Issue by xyzz** [void-linux/void-packages#28613]
### System

* xuname:  
Void 5.10.14_1 x86_64 AuthenticAMD uptodate rrrrmdFFFFFFFFF
* package:  
kicad-5.1.9_1
wxPython4-4.0.7_2

### Expected behavior

No warning message is displayed

### Actual behavior

When starting pcbnew (either standalone or from kicad), the following warning message is displayed:

![image](https://user-images.githubusercontent.com/1065521/107446263-0c980100-6b0c-11eb-8770-9a8c098ea970.png)

### Steps to reproduce the behavior

Open `pcbnew`. Or run `python -c "import wx"`, it doesn't seem caused by kicad but rather by wxpython it imports.

**Comment by ericonr** [comment]
I hate WX :P 

Will be pushing a revbump in a bit, thanks.
