### ISSUE TITLE
[RFC] Add glibc-unstable to reduce the chance of premature updates

### ISSUE THREAD

**Issue by Gottox** [void-linux/void-packages#2862]
After repeated issues with nearly every glibc release I'd like to add an unstable glibc package that is updated with every release. The original glibc package is updated after a few weeks without any major issue. This gives the user the chance to check for major errors, report them and rollback the system.

**Comment by chneukirchen** [comment]
Not really complete if new builds don't use the new libc features too.

Also we waited a month for this glibc update and I knew the electron fallout from Arch but thought these fancy things would have had upsteam updates already.

**Comment by CameronNemo** [comment]
Why not have a testing channel? glibc can't be the only update that has potential for breakage...

**Comment by Cogitri** [comment]
> Why not have a testing channel?

+1, would be a lot of work though...

**Comment by Gottox** [comment]
@chneukirchen valid argument
