### ISSUE TITLE
renderdoc cannot run remote server on android

### ISSUE THREAD

**Issue by xyzz** [void-linux/void-packages#28630]
### System

* xuname:  
Void 5.10.14_1 x86_64 AuthenticAMD uptodate rrrrmdFFFFFFFFF
* package:  
renderdoc-1.10_1

### Expected behavior

No error is displayed and remote server runs.

### Actual behavior

When trying to connect to a device, an error message is displayed
![image](https://user-images.githubusercontent.com/1065521/107542486-3ac22300-6b96-11eb-8cdb-6aaf04a2300e.png)

### Steps to reproduce the behavior
Start qrenderdoc with a debuggable android device attached. On bottom left select the android device:
![image](https://user-images.githubusercontent.com/1065521/107542695-7361fc80-6b96-11eb-9366-0d57ea814979.png)
it will try to connect for a while then display the above error message.
![image](https://user-images.githubusercontent.com/1065521/107542793-8d9bda80-6b96-11eb-8a7f-c7c8c9d17dde.png)

**Comment by ericonr** [comment]
@faulesocke since you were the last one to touch this package, could you take a look?

**Comment by faulesocke** [comment]
Try go to Tools->Settings->Android and set your Android SDK and JDK paths correctly.

**Comment by xyzz** [comment]
I've done that, I'm pretty sure the issue is that the apk isn't packaged in void:

```
% xbps-query -f renderdoc      
/etc/vulkan/implicit_layer.d/renderdoc_capture.json
/usr/bin/qrenderdoc
/usr/bin/renderdoccmd
/usr/include/renderdoc.h
/usr/lib/librenderdoc.so
/usr/share/applications/renderdoc.desktop
/usr/share/doc/renderdoc/LICENSE.md
/usr/share/doc/renderdoc/README
/usr/share/doc/renderdoc/magic
/usr/share/icons/hicolor/scalable/mimetypes/application-x-renderdoc-capture.svg
/usr/share/licenses/renderdoc/LICENSE.md
/usr/share/menu/renderdoc
/usr/share/mime/packages/renderdoc-capture.xml
/usr/share/pixmaps/renderdoc-icon-16x16.xpm
/usr/share/pixmaps/renderdoc-icon-32x32.xpm
/usr/share/thumbnailers/renderdoc.thumbnailer
```

meanwhile with renderdoc downloaded from https://renderdoc.org/stable/1.12/renderdoc_1.12.tar.gz it has these files:
```
./share/renderdoc/plugins/android/org.renderdoc.renderdoccmd.arm64.apk
./share/renderdoc/plugins/android/org.renderdoc.renderdoccmd.arm32.apk
```

And this is the output from renderdoc log window:

```
Core 1463 11:59:24 android.cpp(380) Log Checking for server APK in /usr/lib/plugins/android/
Core 1463 11:59:24 android.cpp(380) Log Checking for server APK in /usr/lib/../share/renderdoc/plugins/android/
Core 1463 11:59:24 android.cpp(380) Log Checking for server APK in /usr/lib/../plugins/android/
Core 1463 11:59:24 android.cpp(380) Log Checking for server APK in /usr/lib/../../build-android/bin/
Core 1463 11:59:24 android.cpp(380) Log Checking for server APK in /usr/lib/../../build-android-arm32/bin/
Core 1463 11:59:24 android.cpp(380) Log Checking for server APK in /usr/lib/../../../../../build-android/bin/
Core 1463 11:59:24 android.cpp(380) Log Checking for server APK in /usr/lib/../../../../../build-android-arm32/bin/
Core 1463 11:59:24 android.cpp(394) Error APK folder missing! RenderDoc for Android will not work without it. Build your Android ABI in build-android in the root to have it automatically found and installed.
Core 1463 11:59:24 android.cpp(1020) Error Failed to install RenderDoc server app
```
