### ISSUE TITLE
xpdf: lacks a .desktop entry

### ISSUE THREAD

**Issue by Val6789** [void-linux/void-packages#28664]
### System

* package:  xpdf-4.03_1

### Expected behavior

The xpf package should include a .desktop entry to associate .pdf files with the xpdf reader.

### Actual behavior

No .desktop entry exists in /usr/share/applications

### Steps to reproduce the behavior

    xbps-install xpdf

**Comment by maop** [comment]
While we wait for the maintainer, you can add the following to your ~/.local/share/applications/xpdf.desktop

```
[Desktop Entry]
Name=xpdf
GenericName=PDF viewer
Comment=View PDF files
Exec=xpdf %f
Icon=xpdf
Terminal=false
Type=Application
MimeType=application/pdf;application/x-pdf;application/x-gzpdf;application/x-bzpdf;application/x-xzpdf;application/x-lzpdf;
Categories=Viewer;Graphics;
Keywords=Viewer;Graphics;
```

source: https://salsa.debian.org/debian/xpdf/-/blob/master/debian/xpdf.desktop

**Comment by BoxMan7** [comment]
Can any maintainer please add a .desktop entry for xpdf as it should be? xpdf is meant to be a gui pdf viewer like okular and its desktop entry is still missing to this day for some reason...

**Comment by classabbyamp** [comment]
it's not our place as the downstream to add a desktop file. ask the developers of xpdf to add it

**Comment by BoxMan7** [comment]
Thanks for the info. I notified the xpdf dev(s?) just now about this issue and will keep you updated the moment I get a reply. I thought that this was a downstream issue considering that Arch linux also packages xpdf with a desktop entry despite the fact that it tries to be as upstream as possible according to their wiki.

**Comment by BoxMan7** [comment]
A dev replied to me and said that they'll include a desktop file. Didn't say when so I suppose it will be there in its next release.
