### ISSUE TITLE
Correcting my wrong doing PR

### ISSUE THREAD

**Issue by biopsin** [void-linux/void-packages#2866]
Sorry guys, I hoped I had my act going right.. but nope.
Would someone mind make the actual template file and not file it as a folder,
I don't have write permission to fix this..
[PR2844](https://github.com/void-linux/void-packages/commit/a6accf667b2cf3c238f31ed6cd468e79eaf84b2a)

**Comment by jnbr** [comment]
Fixed.
You can avoid such mistakes by testing the package before making a pull request.

**Comment by biopsin** [comment]
I test locally, but use git-web to add the PR, I just need to pay attention as this is the second time I make this silly mistake.
Thank you for the help, I really hate make other people clean up after me.

**Comment by cr6git** [comment]
@jnbr sorry.
