### ISSUE TITLE
Packages can't depend on package-$version

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#28665]
See 0961351b5226020b44bc8f1426310112c9151055

`util-linux` shouldn't have to be revbumped every time `util-linux-libs` is, or vice versa. Changes that only affect one of the packages should allow us to revbump only one of them, but that currently isn't possible, because `util-linux` has `util-linux-libs-${version}_${revision}` in `depends`. The ABI is unlikely to change between revisions (we even depend on it not changing between versions). Therefore, it should be possible to depend on `util-linux-libs-${version}`, which currently results in the package not being found: `=> ERROR: util-linux-2.36.1_2: target dependency 'util-linux-libs-2.36.1' does not exist!`.

It would be nice to define a mechanism for depending on a specific *version* of a package, without caring about specific revision. I believe other templates could also be improved if such a mechanism becomes available.

**Comment by Chocimier** [comment]
> define a mechanism for depending on a specific version

`util-linux-libs>=${version}_1<${version}_999` is close enough.
