### ISSUE TITLE
Package request: lantern

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#28699]
Fast, reliable and secure access to the open internet:
https://github.com/getlantern/lantern

**Comment by noarchwastaken** [comment]
Note that it is non-free, uses a freemium payment model, and has ads for its crypto... I don't think it should be in the repository.

**Comment by ahesford** [comment]
@noarchwastaken says it best; not going to happen.

**Comment by the-maldridge** [comment]
This exceeds the gut-check-sketchiness factor of enough maintainers to be closed.  Thank you for your interest, but at this time Void's recommendation is to install this package without the use of XBPS.
