### ISSUE TITLE
firefox: firefox-wayland script doesn't set env variable correctly

### ISSUE THREAD

**Issue by 666666t** [void-linux/void-packages#28715]
### System

- Package: firefox-85.0.1_1

### Expected behavior
- [`firefox-wayland`](https://github.com/void-linux/void-packages/blob/master/srcpkgs/firefox/files/firefox-wayland) command script is (presumably) meant to set the `MOZ_ENABLE_WAYLAND=1` variable when calling firefox, to run as a native wayland program rather than under XWayland.

### Actual behavior
- Script does not specify the variable, instead containing the string `MOZ_ENABLE_WAYLAND=`, resulting in firefox still running under XWayland unless script is manually modified. 

### Steps to reproduce the behavior

`xbps-install -S firefox`
`firefox-wayland`

**Comment by st3r4g** [comment]
iirc it used to work, maybe the behavior changed

**Comment by ericonr** [comment]
It used to work, yeah. Feel free to open a PR, but I don't think it's worth rebuilding firefox for it... So probably best to just leave the change there so it's picked up next update / revbump.

**Comment by ericonr** [comment]
Will be fixed in #29097

**Comment by Piraty** [comment]
it has beed argued about some time ago to even drop that wrapper script and let wayland users deal with their env on their own

**Comment by ericonr** [comment]
@Piraty we ended up not adding it to thunderbird for this reason, but now that it's there I think it's okay to keep shipping for firefox...
