### ISSUE TITLE
skype segfaults on start

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#2871]
### System

* xuname:  
  Void 4.18.8_1 x86_64 AuthenticAMD notuptodate rrDFF*
  Void 4.18.7_1 x86_64 AuthenticAMD notuptodate rrDFF*
  Void 4.17.19_1 x86_64 AuthenticAMD notuptodate rrDFF*
* package:  
  *skype-8.29.76.43_1*, *skype-8.29.76.42_1*, *skype-8.29.76.19_1*

### Expected behavior

Skype should start

### Actual behavior

Dies with a segfault, e.g.:
```
[   43.470625] skypeforlinux[1123]: segfault at d20020 ip 0000000000d20020 sp 00007ffc06a15518 error 15 in skypeforlinux[200000+1602000]
[   43.470653] Code: Bad RIP value.
```

### Steps to reproduce the behavior

Update system, install void-repo-nonfree and skype, try to start skype.

Note: Skype used to work until recently, i.e. late afternoon yesterday, so it's perhaps one of the packages which were updated on 2018-09-17?

I downgraded skype to the two previous versions but all show the same problem now.

**Comment by Johnnynator** [comment]
Isn't Skype using a electron base? If yes I would suspect it is broken because of the new glibc.

**Comment by pullmoll** [comment]
I don't use it myself and have no clue what it depends upon.
My girlfriend told me it doesn't work on her laptops and I could verify on my box that it's indeed broken.
I'll take a look at dependencies and try to rebuild (some of) them.

**Comment by Johnnynator** [comment]
Just verfied locally, it is the glibc update. It works fine with a downgraded glibc. Updating it to `8.30.76.41` will probably help.

**Comment by pullmoll** [comment]
Thanks @Johnnynator I could start it on my box, but it still doesn't run on the laptops where it used to run before ;-P

There a log message can be read in `$HOME/.config/skypeforlinux/logs/skype-startup.log` which reads:
```
dbus[1273]: dbus message iterator has already been closed, or is uninitialized or corrupt
  D-Bus not built with -rdynamic so unable to print a backtrace
Server response: <?xml version="1.0" encoding="UTF-8"
```
On my box, where I never ran it before, it starts up... 
I don't know what to make of this log message :(

**Comment by Johnnynator** [comment]
I don't know what causes this. 
I only just noticed that the x.x.76.x versions seem to be the unstable. (And we always shipped unstable instead of stable). `8.30.0.50` would be the newest stable version. I will take a look at using that and also fix the update check.

**Comment by pullmoll** [comment]
Thank you for your efforts. They are very much appreciated.

**Comment by Johnnynator** [comment]
@pullmoll https://forum.voidlinux.org/t/solved-latest-skype-wont-start/6864 It seems that skype needs elogind for some reason

**Comment by pullmoll** [comment]
D'OH! That's it. I had elogind installed and it was missing on the laptops.
