### ISSUE TITLE
Current live-DVD's won't update due to mozjs.so switch

### ISSUE THREAD

**Issue by p-kraszewski** [void-linux/void-packages#28779]
### System

Fresh installation of `void-live-x86_64-20191109-mate.iso`.

### Expected behavior

`xbps-install -Su` proceeds correctly

### Actual behavior

`xbps-install -Su` is terminated due to problems with `mozjs60`:

```
`gjs-1.58.1_1`: broken, unresolvable shlib `libmozjs.so.60'
`polkit-*`: broken, unresolvable shlib `libmozjs.so.60'
Transaction aborted due to unresolved shlibs.
```
(I didn't note the version of `polkit`, but it must be one pre-installed, as `gjs` is)

### Steps to reproduce the behavior

* Fresh install `void-live-x86_64-20191109-mate.iso` (I suppose any flavor installing `polkit` would be affected).
* Try `xbps-install -Su`

### Workaround

* Remove all packages depending on `mozjs60`
* Perform `xbps-install -Su`
* Re-install removed packages

#### or

Install from `void-live-x86_64-20191109.iso`, do `xbps-install -Su` and *then* install everything user needs.

### Fix

Re-generate installation ISOs with fresh packages.

**Comment by powerelastic** [comment]
Same issue here. On a new installation, except it isn't only when xbps-install -Su is used. It happens when I try to install anything, whether as root or by using sudo. It happens with and without graphical installation too

**Comment by ericonr** [comment]
What you can do temporarily is add `ignorepkg=removed-packages` to `/etc/xbps.d/pkgs.conf`

**Comment by p-kraszewski** [comment]
@powerelastic Yes, for me `xbps-install` was globally broken, too. Hopefully, being trained on Gentoo I knew the drill :)

@ericonr Is there any info, what **exactly** `removed-packages.xbps` is and how it interacts with system? Assuming your workaround does what _I mean_ it does (that is updates some sort of explicit package blacklist), it might be relatively safe to include a flag in `xbps-install` to temporarily disable `removed-packages` parsing altogether. 

I see 2 problems here: 
* there might be a better error message indicating that installed software depends on package marked for hard-removal and a hint for your workaround.
* there might be a bug in dependency resolving algorithm causing early termination

**Comment by Chocimier** [comment]
What's happening here is that when new xbps version is available (and there is newer than in images), xbps wants update itself in separate, small transaction other than updating rest of system. At the same time it adds all revdeps of xbps, being base-system, and all their dependencies (removed-packages between them) making transaction not small anymore and causing conflicts.

We could remove mozjs60 and mozjs52 from removed-packages for now if there are no file conflicts and updates will actually work, and try to make xbps' transaction smaller for longer term.

**Comment by p-kraszewski** [comment]
@Chocimier Thank you for a detailed insight. Dzięki.

I assume I can roll my own installer ISO using `void-mklive`. Which packages should be added to make it suitable to run `void-install` which will automatically install a specific DE? I already have pizza-with-everything almost 3GB live Void-KDE image, but I can't install a fresh OS with it.

**Comment by powerelastic** [comment]
Not a solution or problem development, just a post to say I understand a lot more now
@ Chocimier . Ahhh that explains a great deal. I have to say that in almost 18 months of using Void. This is the first issue I have encountered.  Ironically it happened just as I was installing Void for another person to show them how great it is. 
Isn't that always how life is?
Great posts from all of you and I'm sure, from what all of you have written I can work a workaround from your ideas and I know it will get solved at the dev level.
