### ISSUE TITLE
Package Request: Wine-Staging

### ISSUE THREAD

**Issue by doonoo** [void-linux/void-packages#28807]
Regular wine is cool, but I need wine-staging to play certain games (SA:MP). So if you could add it to the repo any chance you get it would be greatly appreciated.

**Comment by ericonr** [comment]
We do have staging, but only for local builds. Build wine with `./xbps-src -o staging pkg wine` and install it with `xi -f wine libwine`.

This was decided because it isn't stable software, so we don't want to shipt it.

**Comment by doonoo** [comment]
`wine client error:0: version mismatch 689/688.
Your wine binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?`

**Comment by Duncaen** [comment]
```
./xbps-src -m masterdir-i686 binary-bootstrap i686
./xbps-src -m masterdir-i686 -o staging pkg wine
./xbps-src -o staging pkg wine
```
