### ISSUE TITLE
remove xf86-video-intel from xorg-video-drivers dependencies

### ISSUE THREAD

**Issue by user318** [void-linux/void-packages#28864]
Hello,

Modern xorg works with Intel video cards normally with buil-in "modesetting" driver. So xf86-video-intel is not required, and even more - after updating the kernel (most probably) from 5.9 to 5.10.17 I noticed problems with graphics like glitches in some parts of the screen.
When I started googling if someone had also experienced the same problem, that is how I knew that xf86-video-intel was the source of the problem [1]. Removing the module file (intel_drv.so) helped and my graphics is working well under 5.10.17 now.
But the proble is I actually can not remove the "xf86-video-intel" package, because it is listed in dependencies for "xorg-video-drivers", which is itself listed in dependencies for "xorg" package. So I think it is reasonable to remove "xf86-video-intel" from the depenencies of "xorg-video-drivers".
Maybe "xf86-video-intel" is actually helpful for something and not that bad, but it can cause problems and is a hard dependency to "xorg". I think something have to be done with that.

[1] https://bbs.archlinux.org/viewtopic.php?id=263330

**Comment by arp242** [comment]
There was a discussion on Reddit about this a while ago too: https://www.reddit.com/r/voidlinux/comments/fs8anw/suggestion_remove_xf86videointel_driver_from/

**Comment by FollieHiyuki** [comment]
There is `xorg-minimal` if you don't want it to be installed. Then you can grab other packages from `xorg` meta-package to fit your need.
I see no problem on this. Even when you already installed `xorg`. You can force uninstall a package with 1 line in `xbps.conf`

**Comment by arp242** [comment]
The issue isn't that there aren't ways to not install this package, but that it's a bad default for many (most?) users. Installing it means Xorg will use it, but for many cards it's a "bad" driver and can cause all sorts of strange problems.

**Comment by ericonr** [comment]
The only issue with removing it is that people who clean up orphans will lose it, and they might rely on it.

Otherwise, mode setting has been recommended for a long time for Intel, so this doesn't sound too unreasonable.
