### ISSUE TITLE
Package request: Shortwave

### ISSUE THREAD

**Issue by MPC7500** [void-linux/void-packages#28886]
**About:** Find and listen to internet radio stations

**Repository:** https://gitlab.gnome.org/World/Shortwave (with build instructions in the README.md file)

**License:** GNU General Public License v3.0

**Why?** Because the predecessor GRadio does not work anymore. See here: https://github.com/void-linux/void-packages/pull/27873

**Comment by Bnyro** [comment]
Can be closed as https://github.com/void-linux/void-packages/pull/44058 is merged
