### ISSUE TITLE
ffmpeg-dbg package doesn't contain debug symbols

### ISSUE THREAD

**Issue by fkaa** [void-linux/void-packages#28931]
### System

* xuname: Void 5.10.16_1 x86_64 AuthenticAMD notuptodate rrrmdDFFFFFF
* package: ffmpeg-dbg-4.3.1_6

### Expected behavior
FFmpeg binaries (ffmpeg, ffplay, ffprobe) from the ffmpeg-dbg package should contain debug symbols.

### Actual behavior
The binaries from the ffmpeg-dbg package are already stripped. The build process of FFmpeg creates a stripped binary and one with debug symbols with a `_g` suffix. See https://ffmpeg.org/faq.html#Why-are-the-ffmpeg-programs-devoid-of-debugging-symbols_003f for more details.

### Steps to reproduce the behavior
1. Install ffmpeg-dbg
2. Run `gdb ffmpeg` which declares no debug symbols were found

**Comment by ericonr** [comment]
They could just respect CFLAGS set in the environment, which is just reasonable, but I guess that's not an option.

Thanks for bringing this up, I will try to fix it. Though we do have a strip wrapper that just echos stuff and should have caught this...

**Comment by sgn** [comment]
Please test #28954
