### ISSUE TITLE
Error: xbps-src: failed to install base-chroot!

### ISSUE THREAD

**Issue by Zed08** [void-linux/void-packages#28950]
I am trying to make a hardened kernel for void on linux5.4.xx. This process worked on linux5.4.94 and 5.4.96, not working now when trying linux5.4.98. Doing ./xbps-src binary-bootstrap and it gives me this;

ERROR: [trans] failed to download `kernel-libc-headers-5.10.4_1' signature from `https://alpha.de.repo.voidlinux.org/current/musl': Operation timed out
Transaction failed! see above for errors.
=> ERROR: xbps-src: failed to install base-chroot!

I have tried different mirrors and no change to error.

Below are the commands I am using; again it errors on the ./xbps-src binary-bootstrap

git clone git://github.com/void-linux/void-packages.git
cd void-packages
./xbps-src binary-bootstrap
./xbps-src fetch linux5.4
Copy patchs to srcpkgs/linux5.4/patches
./xbps-src patch linux5.4
./xbps-src configure linux5.4
./xbps-src build linux5.4
./xbps-src pkg linux5.4

Am I doing something wrong or is something missing in the repo?

Thanks for all the hard work, I'm lovin the VOID

**Comment by sgn** [comment]
You're using your own kernel. You're on your own.

**Comment by ericonr** [comment]
This is something wrong with your connection, I can download the package just fine. If you can install it on your system, you can just copy the package from `/var/cache/xbps` to `hostdir/repocache-x86_64-musl/` and try again.

**Comment by Zed08** [comment]
@ericonr Thank you. I tried that and didnt work. I am reinstalling Void and trying again
