### ISSUE TITLE
./xbps-src binary-bootstrap signature issue

### ISSUE THREAD

**Issue by Zed08** [void-linux/void-packages#28960]
Hello. No custom anything this time. Just trying to git clone and then binary bootstrap, different mirrors do not change issue, Here are the steps

1- git clone git://github.com/void-linux/void-packages.git
2- cd void-packages
3- ./xbps-src binary-bootstrap

doing the ./xbps-src binary-bootstrap it does not have the signatures for the below files, i have tried on 2 computers at separate locations, all of the blow I can download manually so it is not a network error, please help. 

kernel-libc-headers install   -                 5.10.4_1               1201KB 
musl                install   -                 1.1.24_6               1364KB 
musl-devel          install   -                 1.1.24_6               653KB 
xbps-triggers       install   -                 0.119_1                9.8KB 
base-files          install   -                 0.141_7                57KB 
binutils-doc        install   -                 2.35.1_4               634KB 
zlib                install   -                 1.2.11_3               43KB 
jansson             install   -                 2.13.1_1               28KB 
libgcc              install   -                 10.2.1pre1_3           49KB 
libstdc++           install   -                 10.2.1pre1_3           662KB 
libev               install   -                 4.33_1                 31KB 
libcrypto46         install   -                 3.1.5_2                818KB 
libssl48            install   -                 3.1.5_2                152KB 
c-ares              install   -                 1.17.1_1               44KB 
nghttp2             install   -                 1.42.0_1               657KB 
libssh2             install   -                 1.9.0_2                104KB 
libzstd             install   -                 1.4.8_1                374KB 
libcurl             install   -                 7.75.0_1               269KB 
musl-fts            install   -                 1.2.7_3                7596B 
libdebuginfod       install   -                 0.183_2                10KB 
binutils            install   -                 2.35.1_4               5613KB 
libgcc-devel        install   -                 10.2.1pre1_3           1351KB 
libstdc++-devel     install   -                 10.2.1pre1_3           2311KB 
libssp              install   -                 10.2.1pre1_3           6975B 
libssp-devel        install   -                 10.2.1pre1_3           7745B 
gcc                 install   -                 10.2.1pre1_3           58MB 
libada              install   -                 10.2.1pre1_3           5529KB 
libada-devel        install   -                 10.2.1pre1_3           1476KB 
gcc-ada             install   -                 10.2.1pre1_3           4803KB 
attr                install   -                 2.4.48_1               7544B 
patch               install   -                 2.7.6_4                91KB 
acl                 install   -                 2.2.53_1               14KB 
sed                 install   -                 4.8_1                  218KB 
findutils           install   -                 4.8.0_1                503KB 
diffutils           install   -                 3.7_1                  326KB 
make                install   -                 4.3_3                  496KB 
gzip                install   -                 1.10_1                 70KB 
libcap              install   -                 2.48_1                 19KB 
gmp                 install   -                 6.2.1_1                252KB 
coreutils           install   -                 8.32_4                 3129KB 
libmagic            install   -                 5.39_1                 333KB 
file                install   -                 5.39_1                 19KB 
liblzma             install   -                 5.2.5_1                82KB 
liblz4              install   -                 1.9.3_1                63KB 
bzip2               install   -                 1.0.8_1                49KB 
bsdtar              install   -                 3.5.1_1                452KB 
ccache              install   -                 4.2_1                  440KB 
libtls20            install   -                 3.1.5_2                27KB 
libressl            install   -                 3.1.5_2                266KB 
run-parts           install   -                 4.11.2_1               10KB 
ca-certificates     install   -                 20210119_1             134KB 
libarchive          install   -                 3.5.1_1                342KB 
libxbps             install   -                 0.59.1_3               137KB 
xbps                install   -                 0.59.1_3               108KB 
mpfr                install   -                 4.1.0_1                1423KB 
ncurses-base        install   -                 6.2_4                  29KB 
ncurses-libs        install   -                 6.2_4                  315KB 
ncurses             install   -                 6.2_4                  150KB 
libreadline8        install   -                 8.1.000_1              140KB 
chroot-bash         install   -                 5.1.004_1              567KB 
chroot-grep         install   -                 3.3_1                  95KB 
chroot-gawk         install   -                 5.0.1_1                284KB 
chroot-distcc       install   -                 3.3.3_1                62KB 
chroot-util-linux   install   -                 2.32.1_2               291KB 
chroot-git          install   -                 2.30.0_1               1513KB 
base-chroot         install   -                 0.66_3                 706B

Each one of the files says this fro the appropriate 

ERROR: [trans] failed to download `kernel-libc-headers-5.10.4_1' signature from `https://alpha.de.repo.voidlinux.org/current/musl': Operation timed out
Transaction failed! see above for errors.
=> ERROR: xbps-src: failed to install base-chroot!

**Comment by ericonr** [comment]
So it can't download `.sig` for any of the files? Does `./xbps-src binary-bootstrap x86_64` spit out the same errors? (remember to `rm -r masterdir/` before testing.

**Comment by Zed08** [comment]
I changed machines and networks and it works now. Not sure why it worked 2 weeks ago and does not now but I will use the other machine for the time being.

Thank you all for help
