### ISSUE TITLE
Package Request: rbw

### ISSUE THREAD

**Issue by uber97** [void-linux/void-packages#28973]
Description: rbw is a unofficial command line client for Bitwarden.
 
Official repo: https://git.tozt.net/rbw/about/
GitHub mirror: https://github.com/doy/rbw

**Comment by uber97** [comment]
> I'm working on this however I was brick walled by a Rust bug, waiting for it to be fixed then I will finish this off

Keep us updated!

**Comment by caughtquick** [comment]
I'll actually give it a try in the next day or two to see if it's fixed. For now I just have it installed using cargo `cargo install rbw`

**Comment by caughtquick** [comment]
error still exists, can't do much about it @uber97 :(, i would just install it from cargo for now

**Comment by caughtquick** [comment]
If anyone wants to tackle this they can, I don't have the time or experience to do so currently.

```
error[E0658]: const generics are unstable
 --> /host/cargo/registry/src/github.com-1ecc6299db9ec823/arrayvec-0.7.0/src/utils.rs:6:15
  |
6 | impl<T, const N: usize> MakeMaybeUninit<T, N> {
  |               ^
  |
  = note: see issue #74878 <https://github.com/rust-lang/rust/issues/74878> for more information
```

**Comment by paper42** [comment]
This means it needs newer rust than what's in the repositories.
