### ISSUE TITLE
Package Request: pulseeffects 5.x

### ISSUE THREAD

**Issue by floyza** [void-linux/void-packages#29006]
The new pulseeffects version 5.0 changed it to use pipewire instead of pulseaudio. The old pulseeffects package should still be kept for use with pulseaudio.
Github: https://github.com/wwmm/pulseeffects

**Comment by FollieHiyuki** [comment]
Is the legacy pulseaudio branch still in development?
If not, I think we should just make an update, and inform users about the pulseaudio deprecation. Otherwise should we make a separated package with `replaces` option like `pulseeffect-pipewire`?

**Comment by ericonr** [comment]
> Is the legacy pulseaudio branch still in development?

Supposedly not, from when I last looked at the project. But as distributors I think the correct policy would be to create a new package (especially since upstream should have renamed :P).

**Comment by floyza** [comment]
They do have a legacy branch where they plan on back-porting security fixes here: https://github.com/wwmm/pulseeffects/tree/pulseaudio-legacy

**Comment by paper42** [comment]
This issue can be closed, pulseeffects 5 is now in the repositories.
