### ISSUE TITLE
Package request: cloud-utils

### ISSUE THREAD

**Issue by jirib** [void-linux/void-packages#29058]
[*cloud-utils*](https://github.com/canonical/cloud-utils/) is a useful set of utilities for interacting with a cloud, handy especially `cloud-localds` to generate nocloud seed image for VM using *cloud-init*.

**Comment by jirib** [comment]
Closing old bugs, no interest to "fix" it.

**Comment by akhiljalagam** [comment]
@classabbyamp @paper42 
need help converting this package to void linux template.  
https://github.com/archlinux/svntogit-community/blob/packages/cloud-utils/trunk/PKGBUILD

sample:
```
# Template file for 'cloud-utils'
pkgname=cloud-utils
version=0.33
revision=1
archs="x86_64"
build_style=gnu-makefile
short_desc="Useful set of utilities for interacting with a cloud (meta package)"
license="GPL-3.0-or-later"
homepage="https://github.com/canonical/cloud-utils/"
distfiles="https://github.com/canonical/cloud-utils/archive/refs/tags/${version}.tar.gz"
checksum=338770d637788466aacfcbcec17a8d0046f92a13cc3b25fce8fceadb02a7339f
```

**Comment by classabbyamp** [comment]
#51364
