### ISSUE TITLE
musescore adopt (change maintainer) ?

### ISSUE THREAD

**Issue by yopito** [void-linux/void-packages#29061]
current's maintainer email address is invalid as of today [1] 

ping contributors on this package: want to maintain it ?
@tibequadorian  @Bridouz @mobinmob  @q66 @bra1nwave 

On my own, I'm using it and currently have a look on updating it to 3.6.2
as using this software, I'm ok to maintain it if no one willing to.

[1] : `host mx2.comcast.net[2001:558:fe21:2a::6] said: 550 5.1.1 Not our Customer (in reply to RCPT TO command)`

**Comment by tibequadorian** [comment]
I probably don't know enough about Qt. Also last time I looked Musescore 3.6 was incompatible with Qt5.15 https://musescore.org/en/node/315557, don't know if that changed in the meantime...

**Comment by tibequadorian** [comment]
I'll see if I can get it updated, then probably feel confident enough to adopt it :D

**Comment by yopito** [comment]
you're welcome. the idea is avoiding leftware ;)

**Comment by mobinmob** [comment]
I cannot maintain medium to big qt programs unfortunately.
