### ISSUE TITLE
udevd + iwd: Error changing net interface name wlan0 to wlp6s0: Device or resource busy

### ISSUE THREAD

**Issue by tomekw** [void-linux/void-packages#29079]
On system startup

### System

iwd-1.11_1

### Expected behavior

No error message

### Actual behavior

Error message: `Error changing net interface name wlan0 to wlp6s0: Device or resource busy`

### Steps to reproduce the behavior

Configure iwd service.

**Comment by ericonr** [comment]
Documented here https://docs.voidlinux.org/config/network/iwd.html#troubleshooting

**Comment by tomekw** [comment]
Oh, how did I miss that? Thanks!
