### ISSUE TITLE
Can't update nghttp2 - missing signature from mirror

### ISSUE THREAD

**Issue by snobknob** [void-linux/void-packages#29090]
### System

* xuname:  
  ``Void 5.10.18_1 x86_64 GenuineIntel notuptodate rFFF``
* package:  
``nghttp2-1.42.0_1``

### Expected behavior
Package should update when using mirror (specifically https://mirror.clarkson.edu/voidlinux/).
### Actual behavior
Package doesn't update, printing the following error message:
``ERROR: [trans] failed to download `nghttp2-1.43.0_1' signature from `https://mirror.clarkson.edu/voidlinux/current': Not Found``
### Steps to reproduce the behavior
Run
``# xbps-install -u nghttp2``
when using the specified mirror.

**Comment by snobknob** [comment]
As expected, changing to the main mirror fixes the issue. But I'll keep it open since the mirror is still missing the signature.

**Comment by ericonr** [comment]
Yes, I had the same thing earlier today. This is a 3rd party mirror, so we are unfortunately unable to trigger a sync, and it's our suspicion that they only sync daily, which made a race condition in package upload apparent.

We'll mostly have to wait, unless you have contact info we can use to try and improve the setup? :)

**Comment by snobknob** [comment]
Unfortunately, I don't have any info. Guess we'll just have to wait then.
