### ISSUE TITLE
electron{9,10}: broken on musl

### ISSUE THREAD

**Issue by selfisekai** [void-linux/void-packages#29105]
### System

* xuname:  `Void 5.10.19_1 x86_64-musl AuthenticAMD uptodate rF`
  *output of ``xuname`` (part of xtools)*
* package:  `vscode-1.53.2_1`
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
Run the VS Code

### Actual behavior
```
[laura@suzumiya ~]$ code-oss
Warning: 'app' is not in the list of known options, but still passed to Electron/Chromium.
```

### Steps to reproduce the behavior
- `sudo xbps-install -S vscode`
- `code-oss`

**Comment by Johnnynator** [comment]
my guess would be that electron 9 is the usual culprit. I really should find some time to get it more reliably on musl. Can you check if running just `electron9` would result in a segfault? It probably will.

**Comment by selfisekai** [comment]
it does after printing the help contents

**Comment by ericonr** [comment]
electron10 can work on musl, it's just random luck that makes it work or not. For the record, running `electron10` segfaults when I'm using an external monitor but works when I'm on my laptop's built-in one.

@fosslinux was looking into it, but we didn't reach any conclusion.

**Comment by fosslinux** [comment]
Oh, another person! Can you test if `electron10` also results in a segfault? I haven't had much time to look into it recently, but I have a couple of ideas, let me enumerate some of them for everyone.

- I am almost sure this is an issue with the difference between TLS (thread local storage) in musl and glibc. See https://wiki.musl-libc.org/design-concepts.html.
- https://www.openwall.com/lists/musl/2021/02/03/1 seems to be related.
- To test: `-femulated-tls`: This will slow it down but may fix it.

It is *not* a stack-size issue, I am almost completely sure of this, I expanded the stack using pthread and also set a very high default stack size when building.

**Comment by selfisekai** [comment]
@fosslinux `electron10` segfaults, but `element-desktop` works fine tho...
I installed glibc void because of this issue (+ no JetBrains support for musl), so I guess I won't be really helpful anymore

**Comment by fosslinux** [comment]
Same as my experience, essentially; thanks for the datapoint, it alone is helpful.

**Comment by selfisekai** [comment]
MATE with Xorg

**Comment by kawaiiamber** [comment]
> electron10 can work on musl, it's just random luck that makes it work or not. For the record, running `electron10` segfaults when I'm using an external monitor but works when I'm on my laptop's built-in one. `element-desktop` just works (for me).
> 
> @fosslinux was looking into it, but we didn't reach any conclusion.

The `element-desktop` package works for me, as well. But, the `vscode` package produces the exact same behaviour as @selfisekai on my musl machine. `electron10` seg faults for me, too.

**Comment by git-bruh** [comment]
> Oh, another person! Can you test if `electron10` also results in a segfault? I haven't had much time to look into it recently, but I have a couple of ideas, let me enumerate some of them for everyone.
> 
>     * I am almost sure this is an issue with the difference between TLS (thread local storage) in musl and glibc. See https://wiki.musl-libc.org/design-concepts.html.
> 
>     * https://www.openwall.com/lists/musl/2021/02/03/1 seems to be related.
> 
>     * To test: `-femulated-tls`: This will slow it down but may fix it.
> 
>     * Also another test, we can see if applying this patch https://www.openwall.com/lists/musl/2021/02/17/3 to musl helps at all (but we wouldn't want that in our musl package until it is merged into upstream).
> 
> 
> It is _not_ a stack-size issue, I am almost completely sure of this, I expanded the stack using pthread and also set a very high default stack size when building.

It was indeed a TID caching related issue, see this [patch](https://gitlab.alpinelinux.org/alpine/aports/-/blob/be2a047681e607a97c6378a3ce070e2a44b61e43/community/chromium/musl-tid-caching.patch) for a hacky fix.

[discussion](https://gitlab.alpinelinux.org/alpine/aports/-/issues/13579#note_224393)
[crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=1309235)

**Comment by fosslinux** [comment]
not fixed

**Comment by selfisekai** [comment]
electron 9 is EOL since 2021-03-02, electron 10 is EOL since 2021-05-25, the latest electron version in repositories is 13 which is EOL since 2022-01-31

**Comment by mjeveritt** [comment]
Seems stalled, but I'm confused as to why .. chromium definitely now [has] builds for musl-libc ?!

(ref. https://github.com/electron/electron/issues/9662 )

**Comment by mjeveritt** [comment]
This may also be (tangentially?) related - https://twitter.com/octaforge/status/1304858423234908160 from @q66

**Comment by q66** [comment]
this is long fixed

**Comment by sistematico** [comment]
Sorry for necro-bumping this issue, but i'm still having this exact same warning(I know, it's just a warning) with glibc version, code-oss is runing fine BTW.
