### ISSUE TITLE
Package request: gst-plugins-ugly-32bit

### ISSUE THREAD

**Issue by ukbeast** [void-linux/void-packages#29118]
This is the only plugin for gstreamer that works on wine is missing for mpeg2 support for older Japanese visuals on wine.
Steins Gate for example.
https://appdb.winehq.org/objectManager.php?sClass=version&iId=32254

with mpeg2, you don't need to do the workaround.

**Comment by ericonr** [comment]
Fixed with bf3ccf4ccf2c9c29bf87fd049543895d685245e2
