### ISSUE TITLE
Updating xbps itself will fail

### ISSUE THREAD

**Issue by smorimoto** [void-linux/void-packages#29158]
I don't know if this only happens during clean install, but we get this error: https://github.com/am11/VoidWSL/pull/5/checks

**Comment by sgn** [comment]
Would you mind add verbose flag to `xbps-install`?

**Comment by Duncaen** [comment]
The error is at https://github.com/am11/VoidWSL/pull/5/checks#step:5:101 probably related to lib64 stuff.

**Comment by ericonr** [comment]
> /bin/sh: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory

@smorimoto you need to be sure the `/usr/lib64 -> /usr/lib` symlink exists.

**Comment by smorimoto** [comment]
All went well with 20210218: https://github.com/am11/VoidWSL/pull/5/checks

**Comment by Duncaen** [comment]
In general the pipeline step should try to update xbps itself first and then a full system update, since the current xbps version will not do a full update when a xbps update is available:

`xbps-install -Suy xbps; xbps-install -Suy`

**Comment by smorimoto** [comment]
I remember that when I tried that in a previous release, the environment was broken after `xbps-install -Suy xbps`.

**Comment by ericonr** [comment]
The previous images had a very unfortunate issue where they removed those symlinks for reasons unknown to mankind. Because we hacked glibc, it worked, but it was kind of accidental. The new images should have it all sorted out.

**Comment by smorimoto** [comment]
Oh, it's fine as long as it works with the latest release. Thanks!
