### ISSUE TITLE
Skype segfaults when joining a call

### ISSUE THREAD

**Issue by jchook** [void-linux/void-packages#29164]
### System

* xuname:  
  Void 5.10.19_1 x86_64 GenuineIntel uptodate rrFFF
* package:  
  skype-8.69.0.77_1

### Expected behavior

Able to make and receive calls.

### Actual behavior

Unable to make or receive calls on Skype. Seeing a segfault in the logs.

```
skypeforlinux[7244]: segfault at 1500200030 ip 00007fa8548510d0 sp 00007fa84c352200 error 4 in libpthread-2.32.so[7fa85484d000+f000]
Code: ff ff 48 8d 0d 41 b7 00 00 ba a7 01 00 00 48 8d 35 c7 b5 00 00 48 8d 3d f6 b4 00 00 e8 09 c1 ff ff 66 0f 1f 84 00 00 00 00 00 <8b> 47 10 89 c2 81 e2 7f 01 00 00 83 e0 7c 0f 85 7c 00 00 00 53 48
```

Manually upgrading the package template to `version=8.69.76.76` has the same issue, but results in a different segfault:

```
traps: skypeforlinux[18213] general protection fault ip:7f2cb33a0214 sp:7f2ca81c3ad8 error:0 in slimcore.node[7f2cb0ef8000+2e3e000]
```

Downgrading to skype-8.67.0.96_1 resolves the issue.

### Steps to reproduce the behavior

1. Launch skype
2. Attempt to start or join a call
3. See that Skype fails to join the call, with no GUI error message.

**Comment by jchook** [comment]
If I had to guess the problem I would guess the find/replace on a binary:

```sh
	vsed -i usr/bin/skypeforlinux -e "s;share/;lib/;g"
```

**Comment by ericonr** [comment]
If you have a patch that fixes it (specifically, the symlink route seems very simple to follow), please PR it.

@mobinmob for awareness.

**Comment by mobinmob** [comment]
@jchook Thank you for the report. I think using the rpm as a distfile makes more sense.

**Comment by mobinmob** [comment]
> If I had to guess the problem I would guess the find/replace on a binary:
> 
> ```shell
> 	vsed -i usr/bin/skypeforlinux -e "s;share/;lib/;g"
> ```

It is a shellscript, not a binary ;)

**Comment by mobinmob** [comment]
I cannot replicate the problem @jchook - no idea why :(

**Comment by jchook** [comment]
Hm, thanks for trying @mobinmob. I have a hard time reproducing this issue on a fresh VM.

Somehow I got one "general protection fault", similar to this, where the call failed with a loading animation and then dumped me out to the login screen. Now calls to the VM seem to work fine lol. No idea why.

```
2021-03-05T23:00:56.12863 kern.info: [ 226.306155] traps: skypeforlinux[1437] general protection fault ip:7ffa673a0214 sp:7ffa64972ad8 error:0 in slimcore.node[7ffa64ef8000+2e3e000]
```

Here's roughly what I tried...

1. Install void base on a new VM (I used libvirt / virt-manager)
2. Boot VM and login as root
3. Install some software

```sh
xbps-install -Suy
xbps-install -Suy xorg i3 i3status dmenu alacritty void-repo-nonfree void-socklog
xbps-install -S
xbps-install skype

ln -s /etc/sv/socklog-unix /var/services/
ln -s /etc/sv/nanoklogd /var/services/
```

4. Logout and log-in as a non-root user
5. Set-up X11

```sh
echo "i3" > ~/.xinitrc
startx
```

6. Launch skype + login
7. Initiate a voice call from another account + device

I did futz around with `xbps-reconfigure` and installing intel microcode, as well as dbus... perhaps related, but I feel kinda stumped now.

**Comment by ericonr** [comment]
Any update here?

**Comment by mobinmob** [comment]
@ericonr I was not able to replicate the issue. There is a PR ( https://github.com/void-linux/void-packages/pull/30917 ) for the latest verson of skype - it works for me, but anypne that wants to test is welcome ofc...

**Comment by jchook** [comment]
Latest Skype works for me, thank you.
