### ISSUE TITLE
asciidoc 9.0.5 archive changed? 

### ISSUE THREAD

**Issue by admnd** [void-linux/void-packages#29186]
See my comment here => https://github.com/void-linux/void-packages/commit/2e5fa9df28aef074c7616fbbb98015ac522958df#commitcomment-47765119

Fixed by  `xgensum -f -i srcpkgs/asciidoc `

However once "fixed", the downloaded archive does not hold the correct path vs what lies in the template file....

Template says:` wrksrc=${pkgname}-py3-${version}`
tarball archive has: `asciidoc-py-9.0.5/`

Has the intended tar file been replaced by upstream?

**Comment by ericonr** [comment]
That's usually the case. I really hate when upstream does this :/

**Comment by ericonr** [comment]
They renamed the repository so `-py3` points now to `-py`.

**Comment by ericonr** [comment]
Closed in 2782c9053a5cead342c4f0b989ddeb6ddf01a873
