### ISSUE TITLE
Package `0ad` didn't work

### ISSUE THREAD

**Issue by sisungo** [void-linux/void-packages#29193]
### System

* xuname:  
  Void 5.10.18_1 x86_64-musl GenuineIntel uptodate FF
* package:  
  0ad-0.0.23b_5

### Expected behavior
Background music plays, displays the background photo. Text is well-rendered.
### Actual behavior
No background music playing, a pure-black photo is playing instead of the right background photo. Text is rendered as block(called `tofu`)s.
### Steps to reproduce the behavior
 - Install package `0ad` via command `xbps-install 0ad`.
 - Start `0ad` by any way: command `0ad` or by desktop files.

**Comment by q66** [comment]
looks like 0ad was not picked up by the musl builder but 0ad-data was, so there was a mismatch; it has been rebuilt now so try updating and check again

**Comment by sisungo** [comment]
SOLVED.
