### ISSUE TITLE
Staging repo keeps all packages on wait

### ISSUE THREAD

**Issue by maxice8** [void-linux/void-packages#292]
Just commited a reubild of wkhtmltopdf that unstages a lot of stuff from aarch64* https://github.com/void-linux/void-packages/commit/6ff7661b76bf4a88244679aa10e378724390ab7d , is it by design for it to keep all packages, even ones with no relation to the shlib, on hold while the shlib inconsistency is not fixed ?

**Comment by chneukirchen** [comment]
That's how it works currently, but I agree it's very annoying.

**Comment by Gottox** [comment]
We can come up with a more advanced algorithm, but apart from the stage deadlock we experienced with 0.52 it works pretty well imho.

Please reopen the issue in xbps. Closing here.

**Comment by maxice8** [comment]
On Tue, Jul 31, 2018 at 10:50:22AM -0700, Enno Boland wrote:
> We can come up with a more advanced algorithm, but apart from the stage deadlock we experienced with 0.52 it works pretty well imho.
> 
> Please reopen the issue in xbps. Closing here.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/292#issuecomment-409309598

done
