### ISSUE TITLE
Package 'grass' : GRASS GUI not working

### ISSUE THREAD

**Issue by nezos** [void-linux/void-packages#29209]
### System

* xuname:  Void 5.10.19_1 x86_64 AuthenticAMD uptodate rFFFF
* package:  grass-7.6.1_4

### Expected behavior
Executing grass76 should start the GUI of the program

### Actual behavior
Starting GRASS GIS...
WARNING: GRASS GUI not found. Please check your installation.
Switching to text based interface mode.

### Steps to reproduce the behavior
$ sudo xbps-install grass
$ grass76

### Causes
I have found two causes:
a) /usr/bin/grass76 has at line 105 hardcoded a path for the lib files that does not exist as it is different than that of the installation
b) if I understood correctly, it requires wxpython v2

### Probable solution
Upgrade version to the latest, I have found a fork by @Nyx70   https://github.com/Nyx70/void-packages/blob/qgis/srcpkgs/grass/

**Comment by jcobban** [comment]
How exactly do I "upgrade to latest version"  As far as I can tell I have installed the latest version for Ubuntu Linux.

**Comment by classabbyamp** [comment]
ask an ubuntu forum. we are not ubuntu users here.
