### ISSUE TITLE
[Package Request] Update Blender to 2.92

### ISSUE THREAD

**Issue by kawaiiamber** [void-linux/void-packages#29214]
Blender version 2.92 released [here](http://download.blender.org/source) has many new features I'd like to use. For example, the geometry node editor, among others.

**Comment by biopsin** [comment]
blocking https://github.com/void-linux/void-packages/pull/27808

**Comment by abenson** [comment]
> Don't request update of package. We have a script for that. https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt . However, a quality pull request may help.
