### ISSUE TITLE
failed to open i686-repodata archive on update

### ISSUE THREAD

**Issue by Tcll** [void-linux/void-packages#29255]
first off, sorry if this is the wrong repository, I'm not exactly sure where to post this because it's more a general voidlinux/xbps-repo issue...
secondly this is not a void-updates request, I can't even install packages currently. ;)

to explain the issue, I've done a fresh local install (network (preferred) can't install grub) of voidlinux-i686 2018-11-11 (can't burn newer ISOs to CD-R, and PC can't boot USB)

I couldn't install an upgraded installation from the live image, so I figured I'd upgrade from the install...
but `sudo xbps-install --debug --verbose -Su` reports alpha.de i686-repodata cannot be opened...
would switching to alpha.us work, or are there issues with that as well??

**Comment by ericonr** [comment]
2018 ISOs require https://docs.voidlinux.org/xbps/troubleshooting/static.html

**Comment by ericonr** [comment]
Closing for now, since that covers the issue. You might want to open an issue in void-mklive about making the ISOs burnable once more, but idk what's involved.

**Comment by Tcll** [comment]
thanks, I'll do just that ;)
