### ISSUE TITLE
glslang is ancient

### ISSUE THREAD

**Issue by Rajalolxd** [void-linux/void-packages#29262]
needs to be updated

**Comment by ericonr** [comment]
As the issue template says, we have a script to check for updates, and the package is shown there. No one has been able to get to this package, or are unaware of issues in the current version. Please at least specify those in any update request, instead of just saying the package is outdated.

**Comment by Rajalolxd** [comment]
Vkd3d needs --quiet to be build, which the current Version doesnt have
