### ISSUE TITLE
Chromium package contains non-free components (Widevine)

### ISSUE THREAD

**Issue by selfisekai** [void-linux/void-packages#29273]
### System

* xuname: `Void 5.10.19_1 x86_64 AuthenticAMD uptodate rrmFF`
  *output of ``xuname`` (part of xtools)*
* package: `chromium-88.0.4324.182_1` 
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
A package downloaded from outside of the nonfree repository should not contain/download non-free components

### Actual behavior
Chromium downloads the Widevine component and uses it, which is not really transparent to the user.
![image](https://user-images.githubusercontent.com/11798442/110215944-a903b800-7eac-11eb-82b4-90ead6423f65.png)
![image](https://user-images.githubusercontent.com/11798442/110216334-dd787380-7eae-11eb-8fba-9830627671f2.png)

### Steps to reproduce the behavior
- `xbps-install chromium`
- `chromium`
- open `chrome://components` and force an update of Widevide CDM, or just wait until it gets triggered itself
- try playing a Widevine-protected video, like here: https://bitmovin.com/demos/drm

**Comment by ericonr** [comment]
Afaik this is a *feature* for anyone who wants to play netflix or similar. I'm not sure we'd like to disable it...

**Comment by selfisekai** [comment]
I don't really have a problem with an _option_ to use Widevine, if it is either a package from the nonfree repository, or it's transparent to the user (like in Firefox, which explicitly asks the user if they want to install and enable the Widevine add-on) 
![image](https://user-images.githubusercontent.com/11798442/110222152-82f00f00-7ed0-11eb-9aca-c47a7830506f.png)

Placing Chromium, which does this automatically, in a free repository, creates an illusion of using free software.

**Comment by q66** [comment]
this is an upstream decision, we generally don't override upstream decisions

we also don't adhere to strict free software guidelines, so requirements from the likes of FSF are entirely irrelevant to us

**Comment by ptrcnull** [comment]
I don't think the issue is about FSF or any other guidelines; it's just not cool that a supposedly open-source package downloads a backdoor from Google, considering that it's possible to disable it, as [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=%23960454](Debian package maintainers) have been able to do it.

**Comment by q66** [comment]
hm, i guess this is simple enough

probably worth adding into https://github.com/void-linux/void-packages/pull/29205

**Comment by ericonr** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=%23960454#54 <-- can we be sure it won't be introducing new bugs?

**Comment by q66** [comment]
well, installing `chromium-widevine` is probably already the preferrable way to get the plugin and then you won't get autoupdates at all (but it updates together with chromium)

**Comment by ericonr** [comment]
AFAIK we have kept `chromium-widevine` mostly for qutebrowser uers :p

From a supply chain perspective, the package is indeed better, but I think most chromium users will be relying on the convenience of the automatic download (I know I was).

**Comment by q66** [comment]
shrug, my platform doesn't have widevine or proprietary plugins in the first place, so i'll let the more qualified people decide here
