### ISSUE TITLE
Proper action for libtls: /etc/ssl/cert.pem

### ISSUE THREAD

**Issue by sgn** [void-linux/void-packages#29299]
- libtls and all of its dependents looks for certs file in `/etc/ssl/cert.pem`
- OpenSSL provides the symlink at `/etc/ssl/certs.pem`
- Old our LibreSSL provides a symlink to `certs.pem` in `/etc/ssl/cert.pem`

In order to make our users' system work, I've provided a temporary fix at ee34f60ecb, (libtls: ship /etc/ssl/cert.pem, 2021-03-08).
I'm not sure if it could be qualified as a permanent fix, or we should patch libtls source to change `cert.pem` into `certs.pem`.
My naive grep in `apps/nc` and `tls` yields 12 occurences of `cert.pem`.

**Comment by sgn** [comment]
@void-linux/pkg-committers

**Comment by q66** [comment]
could patch `DEFAULT_CA_FILE` in `tls/Makefile.am`

**Comment by ericonr** [comment]
Have we reached a decision?

**Comment by sgn** [comment]
A patch in Makefile.am seems straight-forward.
