### ISSUE TITLE
ppp package is 7 years old, 2.4.7 -> 2.4.9

### ISSUE THREAD

**Issue by jirib** [void-linux/void-packages#29313]
Void Linux uses 7 yeard old `ppp` package, there have been a lot of improvements in this package since then.

```
# xbps-query -Rp pkgver ppp
ppp-2.4.7_14
```

See https://ppp.samba.org/README.html

BTW, I updated Alpine Linux [PPPoE](https://wiki.alpinelinux.org/wiki/PPP) page, if somebody would like to adopt it for Void docs, feel free.

**Comment by the-maldridge** [comment]
Don't request update of package. We have a script for that. https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt . However, a quality pull request may help.
