### ISSUE TITLE
[Package request] Update webrtc-audio-processing to 1.0

### ISSUE THREAD

**Issue by FollieHiyuki** [void-linux/void-packages#29315]
Upstream changed to use `meson` build style.
Source: https://gitlab.freedesktop.org/pulseaudio/webrtc-audio-processing

Blocker: I believe they use Abseil libraries (https://github.com/abseil/abseil-cpp). So we need to package that first.

**Comment by the-maldridge** [comment]
Don't request update of package. We have a script for that. https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt . However, a quality pull request may help.
