### ISSUE TITLE
constraints disabled in openntpd after the switch to openssl

### ISSUE THREAD

**Issue by 4ricci** [void-linux/void-packages#29347]
### System

* xuname:
  Void 5.10.20_1 x86_64 GenuineIntel uptodate rrFFFFFF
* package:
  openntpd-6.2p3_8 and #27053

### Expected behavior
If constraints are enabled in `/etc/ntpd.conf`, then `ntpctl -s status` should print something like:
```
4/4 peers valid, constraint offset 0s, clock synced, stratum 3
```
`xbps-query -x openntpd` should print:
```
ca-certificates>=0
glibc>=2.32_1
libtls>=3.2.4_1
```

### Actual behavior
`ntpctl -s status` says nothing about constraints:
```
4/4 peers valid, clock synced, stratum 3
```
and the package does not depend on libtls at runtime.

I was able to link openntpd against libtls (and enable contraints support) by adding opennssl-devel to makedepends. I think that the configure script relies on some part of openssl/libressl that is not included in our standalone libtls to detect the latter, but I'm not sure about the correct way to fix that.

This is the build log with the actual template:
```
[...]
=> openntpd-6.2p3_8: installing target dependencies: libtls-devel-3.2.4_2 ...
[...]
checking for library containing tls_config_set_ca_mem... no
checking for tls_config_set_ca_mem... no
checking if tls_write takes 3 arguments... no
[...]
  CC       ntpd-constraint-disabled.o
[...]
=> openntpd-6.2p3_8: running pre-pkg hook: 04-generate-runtime-deps ...
   SONAME: libm.so.6 <-> glibc>=2.32_1
   SONAME: libc.so.6 <-> glibc>=2.32_1
[...]
=> openntpd-6.2p3_8: running pre-pkg hook: 999-collected-rdeps ...
   ca-certificates>=0 glibc>=2.32_1
[...]
```
and this is with makedepends including openssl-devel:
```
[...]
=> openntpd-6.2p3_8: installing target dependencies: libtls-devel-3.2.4_2 openssl-devel-1.1.1j_2 ...
[...]
checking for library containing tls_config_set_ca_mem... -ltls
checking for tls_config_set_ca_mem... yes
checking if tls_write takes 3 arguments... yes
[...]
  CC       ntpd-constraint.o
[...]
=> openntpd-6.2p3_8: running pre-pkg hook: 04-generate-runtime-deps ...
   SONAME: libm.so.6 <-> glibc>=2.32_1
   SONAME: libtls.so.20 <-> libtls>=3.2.4_1
   SONAME: libc.so.6 <-> glibc>=2.32_1
[...]
=> openntpd-6.2p3_8: running pre-pkg hook: 999-collected-rdeps ...
   ca-certificates>=0 glibc>=2.32_1 libtls>=3.2.4_1
[...]
```

**Comment by ericonr** [comment]
Maybe we need to fix/add a pkg-config file for libtls? I believe @Johnnynator had to fix another build adding openssl-devel as well.

@leahneukirchen thoughts?
