### ISSUE TITLE
Undocumented xbps-src commands

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#29363]
These commands aren't in the help output. They should be removed or documented:

- remove-destdir (seems to be the same as remove, so I'd consider removing)
- show-pkg-var-dump
- show-pkg-var
- dbulk-dump

**Comment by Duncaen** [comment]
I don't think each of those commands need to be documented in the help/usage, its already pretty big and there is no point in knowing `dbulk-dump` from a users perspective who is not trying to build tooling around xbps-src.
Same goes for the `show-pkg-var` they do the same thing as `dbulk-dump` but with a "looser" output format.

`remove-destdir` looks like just an alias for `remove`, I don't see the harm in keeping it for compatibility.

**Comment by ericonr** [comment]
I'm ok with keeping remove-destdir, but for the others it helps to have usage information as well as what the command does without having to read and understand code. Also helps with discoverability...
