### ISSUE TITLE
`git` install fails due to incorrect `perl-Net-SMTP-SSL` version

### ISSUE THREAD

**Issue by go2null** [void-linux/void-packages#2938]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
  - cannot install `xtools` due to same error as trying to install `git`.
```
uname -a
Linux bradbury 4.18.8_1 #1 SMP PREEMPT Sun Sep 16 04:42:29 UTC 2018 x86_64 GNU/Linu
```
* package:  
```
perl-IO-Socket-SSL  install   -                 2.059_1                127KB 
git                 install   -                 2.19.0_1               4456KB 
xtools              install   -                 0.52_1                 17KB
```  

### Expected behavior
`xbps-install git` should get correct versions of dependencies and install correctly.

### Actual behavior
`sudo xbps-install -d git` yields the following

```
[DEBUG] git-2.19.0_1: requires dependency 'perl-Net-SMTP-SSL>=0': not installed.
[DEBUG] perl-Net-SMTP-SSL-1.04_1: finding dependencies:
[DEBUG]  perl-Net-SMTP-SSL-1.04_1: requires dependency 'perl>=0': installed `perl-5.28.0_2'.
[DEBUG]  perl-Net-SMTP-SSL-1.04_1: requires dependency 'perl-IO-Socket-SSL>=0': not installed.
[DEBUG]  perl-IO-Socket-SSL-2.059_1: finding dependencies:
```

However, `perl-IO-Socket-SSL` is at version `2.060`.
* https://github.com/void-linux/void-packages/blob/master/srcpkgs/perl-IO-Socket-SSL/template
* https://alpha.de.repo.voidlinux.org/current

Hence the error
```
ERROR: [trans] failed to download `perl-IO-Socket-SSL-2.059_1' package from `https://alpha.de.repo.voidlinux.org/current': Not Found
```

### Steps to reproduce the behavior
- provided above

**Comment by Duncaen** [comment]
Is the repository synchronized?

e.g. `xbps-install -S git` or a full system update before installing git?

**Comment by go2null** [comment]
same result.
```
sudo xbps-install -Su git
...
[*] Downloading binary packages
SSL_connect returned 5
ERROR: [trans] failed to download `perl-IO-Socket-SSL-2.059_1' package from `https://alpha.de.repo.voidlinux.org/current': Operation not permitted
```

**Comment by go2null** [comment]
>full system update
This is a new install on Void (although the latest ISO is [void-live-i686-20171007-xfce.iso](https://alpha.de.repo.voidlinux.org/live/current/))

**Comment by go2null** [comment]
Guess there were some changes, or the changes got propagated to the mirrors for it works now.  Pulls the correct `2.060` version.
