### ISSUE TITLE
qpaeq (from pulseaudio package) is missing some dependencies

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#29405]
### System

* xuname:  
  *Void 5.11.4_1 x86_64 AuthenticAMD notuptodate rrDDDDFFFF*
* package:  
  *affected package(s) including the version*: ``pulseaudio-14.2_2``

### Expected behavior
```
%: qpaeq
~~working~~
```
### Actual behavior
```
%: qpaeq
There was an error importing needed libraries
Make sure you have qt5 and dbus-python installed
The error that occurred was:
	No module named 'dbus.mainloop.pyqt5'
```
### Steps to reproduce the behavior
* install pulseaudio (without having python3-PyQt5-dbus installed)
* run qpaeq

Similar error is probably raised when the system doesn't have PyQt5 or python3-dbus. qpaeq should be a subpackage depending on python3-dbus, python3-PyQt5 and python3-PyQt5-dbus.

**Comment by ericonr** [comment]
I don't think this can happen, otherwise we get a dependency loop (pulseaudio requires PyQt5, which requires qt5, which requires pulseaudio).

**Comment by noarchwastaken** [comment]
> I don't think this can happen, otherwise we get a dependency loop (pulseaudio requires PyQt5, which requires qt5, which requires pulseaudio).

If we split qpaeq subpackage, can this be avoided?

**Comment by ericonr** [comment]
Only if it's made into a separate template, but I'd rather avoid that.
