### ISSUE TITLE
cmake files misplaced in opencolorio-1.10_2

### ISSUE THREAD

**Issue by datenwolf** [void-linux/void-packages#2944]
### System

* xuname:  
  Void 4.18.8_1 x86_64 GenuineIntel notuptodate rrrmdFFF

* package:  
  opencolorio-1.1.0_2

### Expected behavior

- `*.cmake` files being placed in …-devel subpackage
- a tidy `/usr` directory without misplaced files.

### Actual behavior

- `*.cmake` files part of non …-devel package

    ~/ % xbps-query -f opencolorio | grep cmake
    /usr/OpenColorIOConfig.cmake
    /usr/cmake/OpenColorIO-release.cmake
    /usr/cmake/OpenColorIO.cmake

- `OpenColorIOConfig.cmake` placed in `/usr`

    ~/ % xbps-query -o /usr/OpenColorIOConfig.cmake 
    opencolorio-1.1.0_2: /usr/OpenColorIOConfig.cmake (regular file)

**Comment by maxice8** [comment]
I have pushed a fix against my repository and will push here once Travis indicates all builds are ok

**Comment by maxice8** [comment]
```
>>> opencolorio-devel
4a5,7
> /usr/lib/cmake/OpenColorIO/OpenColorIO-release.cmake
> /usr/lib/cmake/OpenColorIO/OpenColorIO.cmake
> /usr/lib/cmake/OpenColorIO/OpenColorIOConfig.cmake
>>> opencolorio
1d0
< /usr/OpenColorIOConfig.cmake
4,5d2
< /usr/cmake/OpenColorIO-release.cmake
< /usr/cmake/OpenColorIO.cmake
```
