### ISSUE TITLE
wine: wine-32bit cannot build with the staging patchset enabled

### ISSUE THREAD

**Issue by kostadin04** [void-linux/void-packages#29456]
### System

* xuname:  
  Void 5.11.6_1 x86_64 AuthenticAMD uptodate rFFFFFFFF

* package:  
  wine-32bit-6.3_1 libwine-32bit-6.3_1

### Expected behavior

The packages compile correctly 

### Actual behavior

The build fails with the following messages:

configure: WARNING: unrecognized options: --with-sysroot, --with-libtool-sysroot
checking build system type... x86_64-unknown-linux-gnu
checking host system type... i686-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for i686-pc-linux-gnu-gcc... i686-pc-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether i686-pc-linux-gnu-gcc accepts -g... yes
checking for i686-pc-linux-gnu-gcc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether i686-pc-linux-gnu-c++ accepts -g... yes
checking for i686-pc-linux-gnu-cpp... i686-pc-linux-gnu-cpp
checking for i686-pc-linux-gnu-ld... i686-pc-linux-gnu-ld
checking for the directory containing the Wine tools... configure: error: you must use the --with-wine-tools option when cross-compiling.
=> ERROR: wine-6.3_1: do_configure: '${configure_script} ${configure_args}' exited with 1
=> ERROR:   in do_configure() at common/build-style/gnu-configure.sh:8

### Steps to reproduce the behavior

1. git clone --depth=1 https://github.com/void-linux/void-packages
2. cd void-packages
3. ./xbps-src binary-bootstrap
4. ./xbps-src pkg -o staging -a i686 wine

**Comment by Duncaen** [comment]
Don't cross compile for i686, use a i686 masterdir instead.

```
./xbps-src -m masterdir-i686 binary-bootstrap i686
./xbps-src -o staging -m masterdir-i686 pkg wine
```

**Comment by kostadin04** [comment]
My bad for not reading the whole README. That solved it, thanks!
