### ISSUE TITLE
wine: 32-bit WINEPREFIX cannot find any 32-bit GStreamer plugins

### ISSUE THREAD

**Issue by KynikossDragonn** [void-linux/void-packages#29451]
### System

* xuname:  
Void 5.10.22_1 x86_64 GenuineIntel notuptodate hold rrrmFFFFF
* package:  
wine-32bit-6.3_1 libwine-32bit-6.3_1 gstreamer1-32bit-1.18.3_1

### Expected behavior
Within a 32-bit WINEPREFIX Any 32-bit executable that makes use of DirectShow (`quartz.dll`, etc) for streamed media should beable to find the lib32 location for the multilib gstreamer-plugins-base1/good1/bad1-32bit libraries installed in the system wide `/lib32/gstreamer-1.0/` path.

### Actual behavior
Wine's GStreamer based `quartz.dll` fails to find any plugins at all and fails to playback anything that required such. Exporting `GST_PLUGIN_SYSTEM_PATH=/lib32/gstreamer-1.0` seems to work as a workaround.

### Steps to reproduce the behavior

1. Install wine and dependencies.
2. Install 32-bit GStreamer and multilib plugins.
3. Create a 32-bit WINEPREFIX.
4. Attempt to run anything that needs to use quartz.dll to access streamed media codecs. (Really any executable that uses DirectShow)

**Comment by ukbeast** [comment]
What game requires the codecs?
I have gotten some luck from the  K-Lite Codec Pack.

**Comment by KynikossDragonn** [comment]
@ukbeast I only have two games with this problem currently.

1. TES IV: Oblivion requires GStreamer plugins for MP3 to have functioning music, oddly enough, it does not require it for the voice acting or any sounds that are played as MP3.
2. Earth 2150 requires MP2 audio support in GStreamer to playback music at all.

Most of the games I play have built in support and don't touch DirectShow (quartz.dll) at all though. Freelancer is a good example of this in particular. The game uses MP3 contained within RIFF WAV files for the music, voice acting and some (not all) of the sound effects.

gst-plugins-ugly1 has no 32-bit multilib so this causes a lot of problems with Wine's GStreamer usage, but that's already been a issue opened here. #29118

**Comment by ericonr** [comment]
From configuring gstreamer, I see `#define PLUGINDIR "/usr/lib32/gstreamer-1.0"`, so I'd assume it has the correct plugin path...

**Comment by KynikossDragonn** [comment]
Okay, I don't know why or how but after testing the problematic games after re-installing all packages involved (wine, gstreamer, gstreamer-plugins-base/good/bad), it's suddenly working properly.

I'm just going to write this off as a embarrassing fluke, closing the issue since everything's suddenly working after that.
