### ISSUE TITLE
Openjdk11 cannot launch on armv6

### ISSUE THREAD

**Issue by TheEdward162** [void-linux/void-packages#29457]
### System

Either of these freshly unpacked armv6l targets:
* https://alpha.de.repo.voidlinux.org/live/current/void-rpi-musl-PLATFORMFS-20210218.tar.xz
* https://alpha.de.repo.voidlinux.org/live/current/void-rpi-PLATFORMFS-20210218.tar.xz

Package `openjdk11-11.0.5+10_4`

### Expected behavior
`java` runs java VM and lets me do java things

### Actual behavior
```
$ java
Error occurred during initialization of VM
Server VM is only supported on ARMv7+ VFP
```

### Steps to reproduce the behavior
1. get armv6 void (both glibc and musl)
2. `xbps-install openjdk11`
3. `java`

As a side note: I am able to get [Zulu OpenJDK11 build](https://www.azul.com/downloads/zulu-community/?architecture=arm-32-bit-hf&package=jdk) running on the glibc target

**Comment by ericonr** [comment]
What ARM device do you have? We can try to get the build info from Zulu and use in our build, maybe.

**Comment by TheEdward162** [comment]
I'm running it on Raspberry Pi Zero W Rev 1.1:
```
$ cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 9000c1
Serial		: 00000000a5aff9b9
Model		: Raspberry Pi Zero W Rev 1.1
```

Additionally I also tried AdoptOpenJDK arm32 build in the meantime but it just segfaults.

**Comment by classabbyamp** [comment]
I can confirm there seems to be an incompatibility, at least in the configuration void ships:
- https://forums.raspberrypi.com/viewtopic.php?t=232680
- https://forums.raspberrypi.com/viewtopic.php?t=323376
- https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255662
