### ISSUE TITLE
DEAD distfiles and homepage

### ISSUE THREAD

**Issue by sgn** [void-linux/void-packages#29465]
- [x] alure
- [x] traverso

**Comment by ericonr** [comment]
- [ ] slmenu

**Comment by Johnnynator** [comment]
https://repology.org/repository/void_x86_64/problems

Repology also does homepage check, also lists a few 404

**Comment by amak79** [comment]
- [ ] hfsprogs

```
=> hfsprogs-540.1.linux3_8: fetching distfile 'diskdev_cmds-540.1.linux3.tar.gz'...
http://cavan.codon.org.uk/~mjg59/diskdev_cmds/diskdev_cmds-540.1.linux3.tar.gz: Not Found
```

**Comment by caughtquick** [comment]
@not-chicken do you know what should be done about traverso as the only place I could find any downloads was a sketchy site that didn't appear to even support linux on the downloads.

**Comment by caughtquick** [comment]
@benalb and for Slmenu I can't seem to find any files at all for it

**Comment by not-chicken** [comment]
> @not-chicken do you know what should be done about traverso as the only place I could find any downloads was a sketchy site that didn't appear to even support linux on the downloads.

I guess we could switch to https://sources.voidlinux.org/, but I personally don't use this tool anymore and neither does http://popcorn.voidlinux.org/ show any installs. [git repo](http://git.savannah.nongnu.org/cgit/traverso.git) is also inactive since 2 years.

So I'm removing it in #30715

**Comment by benalb** [comment]
> @benalb and for Slmenu I can't seem to find any files at all for it

Seems bitbucket site is gone, I've got a .zip of the site here, and, as I assume I'm the only user of the package, I will move it to my private repo and will remove from void.

**Comment by ericonr** [comment]
@Gottox I was looking into removing the musl workaround we have for `drbd-utils` (voidlinux.de is down), but I can't download the current version at all. From https://linbit.com/linbit-software-download-page-for-linstor-and-drbd-linux-driver/#drbd I assume we need to update to 9.17.0 or something like that.

**Comment by Johnnynator** [comment]
> drbd-utils

It is still in the ppc repo source cache https://sources.voidlinux-ppc.org/drbd-utils-9.12.1/drbd-utils-9.12.1.tar.gz
