### ISSUE TITLE
Package request: fcitx5

### ISSUE THREAD

**Issue by noarchwastaken** [void-linux/void-packages#29499]
[fcitx5](https://github.com/fcitx/fcitx5): Next generation of fcitx

The currently packaged fcitx4 runs on XWayland on Wayland compositors. Due to that, it has problems following the text cursor in Wayland apps. Fcitx5 solves that problem by supporting Wayland natively.

Note that the [backends](https://fcitx-im.org/wiki/Install_Fcitx_5) also need to be packaged.

More references on Arch Wiki: https://wiki.archlinux.org/index.php/Fcitx5

**Comment by sgn** [comment]
What is your favourite IME? Without any IME, it's useless.

**Comment by noarchwastaken** [comment]
> What is your favourite IME? Without any IME, it's useless. (Question in order to package together)

[fcitx5-rime](https://github.com/fcitx/fcitx5-rime). I mentioned that the IMEs(backends) need to be packaged as well.

I couldn't find any documentation about building it by hand, so it might be a problem...
