### ISSUE TITLE
podman: Add `fuse-overlayfs` to `depends`

### ISSUE THREAD

**Issue by kartikynwa** [void-linux/void-packages#29491]
Hello.

podman tries to default to overlayfs as the default storage driver and falls back to vfs if it's not available. While podman functions fine with vfs, it has the downside of eating up an inordinate amount of space. On my VPS, upon doing a `podman-compose pull` on a Wordpress compose file, it consumed 15GB of space until there was none left.

For reference, Arch installs it as a runtime dependency and it's a suggested package while installing podman in Debian.

Just throwing an idea against the wall so feel free to close the issue if it's not deemed necessary.

Thanks.

**Comment by ericonr** [comment]
This sounds like a reasonable idea to me. @CameronNemo what do you think?

**Comment by ahesford** [comment]
Also tagging @bougyman to weigh in.

**Comment by CameronNemo** [comment]
It is not strictly necessary to function. That said it is a tiny dependency and I have it installed everywhere I have podman installed. Sounds reasonable to include as a dep.

**Comment by kartikynwa** [comment]
Filed a PR while we wait for others to weigh in. #29505

**Comment by kartikynwa** [comment]
This is done. Thanks everyone.
