### ISSUE TITLE
Problem with stremio-shell

### ISSUE THREAD

**Issue by gilbertoferreira** [void-linux/void-packages#29507]
### System

* xuname:  
xuname 
Void 5.11.6_1 x86_64 AuthenticAMD uptodate rrmFFFF* package:  
 xbps-query -p pkgver stremio-shell 
stremio-shell-4.4.120_2

### Expected behavior
I expected that works properly
### Actual behavior
After opened the program, I get a errors amd a blank screen.

stremio
QtWebEngine::initialize() called with QCoreApplication object already created and should be call before. This is depreciated and may fail in the future.
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
ScreenSaver::retrieveState
ScreenSaver::retrieveState timeout: 0, interval: 600, preferBlanking:1, allowExposures:1
[cplayer] mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Wed Dec  9 15:27:44 UTC 2020
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.51.100
[cplayer]    libavcodec      58.91.100
[cplayer]    libavformat     58.45.100
[cplayer]    libswscale      5.7.100
[cplayer]    libavfilter     7.85.100
[cplayer]    libswresample   3.7.100
[cplayer] FFmpeg version: 4.3.2
[cplayer] 
[cplayer] Configuration: waf configure --prefix=/usr --libdir=/usr/lib --confdir=/etc/mpv --docdir=/usr/share/examples/mpv --enable-cdda --enable-dvbin --enable-dvdnav --enable-libarchive --enable-libmpv-shared --enable-alsa --disable-caca --enable-jack --enable-lcms2 --enable-lua --disable-openal --enable-pulse --disable-sdl2 --disable-vapoursynth --enable-vdpau --enable-vulkan --enable-shaderc --enable-wayland --enable-x11 --zshdir=/usr/share/zsh/site-functions
[cplayer] List of enabled features: 52 alsa asm build-date cdda cplayer cplugins debug-build drm dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vt.h vulkan wayland wayland-protocols x11 xv zlib
[cplayer] Waiting for scripts...
[cplayer] Set property: vo="libmpv" -> 1
[cplayer] Set property: gpu-hwdec-interop="auto" -> 1
[cplayer] Set property: cache-default=15000 -> -3
[cplayer] Set property: cache-backbuffer=15000 -> -3
Warning: option --cache-secs is deprecated and might be removed in the future (will use unlimited time).
[cplayer] Set property: cache-secs=10 -> 1
[cplayer] Set property: audio-client-name="Stremio" -> 1
[cplayer] Set property: title="Stremio" -> 1
[cplayer] Set property: audio-fallback-to-null="yes" -> 1
[cplayer] Set property: audio-client-name="Stremio" -> 1
[cplayer] Set property: title="Stremio" -> 1
[osd/libass] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 2.7.4 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Done loading scripts.
qrc:/main.qml:160:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qml: Loading web UI from URL: https://app.strem.io/shell-v4.4/#?loginFlow=desktop
qml: Stremio Shell version: 4.4.120
qml:  **** Completed. Loading Autoupdater ***
qml: Auto-updater: skipping, possibly not running an installed app?
[libmpv_render] GL_VERSION='4.6 (Compatibility Profile) Mesa 20.3.4'
[libmpv_render] Detected desktop OpenGL 4.6.
[libmpv_render] GL_VENDOR='AMD'
[libmpv_render] GL_RENDERER='AMD Radeon R7 Graphics (CARRIZO, DRM 3.40.0, 5.11.6_1, LLVM 11.0.0)'
[libmpv_render] GL_SHADING_LANGUAGE_VERSION='4.60'
[libmpv_render] Loaded extension GL_NV_vdpau_interop.
[libmpv_render] GL_*_swap_control extension missing.
[libmpv_render] Testing FBO format rgba16f
[libmpv_render] Using FBO format rgba16f.
[libmpv_render] No advanced processing required. Enabling dumb mode.
[libmpv_render] Loading hwdec driver 'vaapi-egl'
[libmpv_render/vaapi-egl] VAAPI hwdec only works with OpenGL or Vulkan backends.
[libmpv_render] Loading failed.
[libmpv_render] Loading hwdec driver 'drmprime-drm'
[libmpv_render/drmprime-drm] Failed to retrieve DRM fd from native display.
[libmpv_render] Loading failed.
[2046:2046:0316/091145.210750:ERROR:network_service_instance_impl.cc(286)] Network service crashed, restarting service.
qml: render process terminated with code 1002 and status: -1

### Steps to reproduce the behavior

Open the program stremio-shell and get the error. Doesn't matter if stremio-server are up or not.
(It's work very well in Ubuntu flavors but I want to continue use Void LInux. Please help! Thanks)
My system:
Operating system: void
KDE Plasma version: 5.21.2
KDE Frameworks version: 5.80.0
Qt Version: 5.15.2
Kernel version: 5.10.23_1
Operating system type: 64-bit
Graphics platform: X11
Processors: 4 × AMD A12-9720P RADEON R7, 12 COMPUTE COLORS 4C + 8G
Memory: 15.2 GiB of RAM
Graphics processor: AMD Radeon R7 Graphics

**Comment by mobinmob** [comment]
Seem to work fine here (no blank screen) - on a much older system :)

**Comment by gilbertoferreira** [comment]
Well with void linux doesn't work here. In fact, need to back to KDE Neon which works. 
I don't understand. Months ago when I tried Void Linux for the first time stremio works perfect.Now this issue.
Any way, I use KDE Neon for now.
Thanks
