### ISSUE TITLE
net-snmp does not bring an /etc/sv/snmpd entry

### ISSUE THREAD

**Issue by bcookatpcsd** [void-linux/void-packages#29508]
there seems to be no snmpd/run script.. 

I made this.. 

`#!/bin/sh
[ ! -e /etc/snmp/snmpd.conf ] && exit 1
exec /usr/sbin/snmpd -f -p /run/snmpd.pid -LSwd -Lf /dev/null
`
My 0.02

*disclaimer*
I've used this snmpd string for myself, check the args for yourself please..

**Comment by FollieHiyuki** [comment]
I don't use `net-snmp`, but you can make a PR adding the run script. Maybe something like this:
```
srcpkgs/net-snmp/files/snmpd/run
-----------------------------------
#!/bin/sh

[ -r conf ] && . ./conf

[ ! -e /etc/snmp/snmpd.conf ] && exit 1
exec /usr/sbin/snmpd ${OPTS:=-f -LSwd -Lf} -p /run/snmpd.pid
```
Put in there what you think are a sane default args.
User can always change the args to their liking inside `/etc/sv/snmpd/conf`

**Comment by ericonr** [comment]
@bcookatpcsd are you interested in making a PR for this package? @FollieHiyuki's suggestion looks good.
