### ISSUE TITLE
foot: Add PGO build option

### ISSUE THREAD

**Issue by travankor** [void-linux/void-packages#29526]
[PGO optimization](https://codeberg.org/dnkl/foot/src/branch/master/doc/benchmark.md) speed foot up by a significant amount. Add a build option that [enables PGO ](https://codeberg.org/dnkl/foot/src/branch/master/INSTALL.md#user-content-partial-pgo) during build.

**Comment by ericonr** [comment]
Definitely not on by default, since PGO is affected by the CPU that's being used.

**Comment by dnkl** [comment]
> since PGO is affected by the CPU that's being used.

It's actually not. PGO counts functions and branches executed, and helps re-organize the code; it clusters "hot" functions, to improve cache locality. It can also re-arrange code within a function to make the "normal" path the fast path (i.e. placing the not-often executed branches at e.g. the end of the function). But PGO in itself does not emit CPU specific instructions, nor does it depend on CPU-specific knowledge for e.g. instruction scheduling.

Over at nix, @sternenseemann has been able to do reproducable PGO builds. That is, builds on different systems produce identical output. I can't for my life find the issue, or comment, where I saw this, but pretty sure sterni can fill in the details, if needed.

Oh, and as a bonus, PGO builds tend to be smaller (in binary size) than regular release builds. This is _at least_ true for LTO builds (which I strongly recommend building foot with, with or without PGO).

**Comment by sternenseemann** [comment]
I can configure that building foot with PGO can be reproducible, i. e. I can reproduce the exact hash of the binary package produced by our builders on two different local machines (at different times). This also leads me to [believe that a reproducible gcc with PGO is possible](https://github.com/NixOS/nixpkgs/pull/112928#issuecomment-809336063), but most likely very hard to get to work.

The only thing necessary to achieve a reproducible foot build is generating the random inputs which are used for profiling while building using a [fixed seed](https://github.com/NixOS/nixpkgs/blob/43b257365c2c73fc31421e9b28dde1166d75506a/pkgs/applications/terminal-emulators/foot/default.nix#L62).

**Comment by ericonr** [comment]
Not stale. @ifreund do you have anything in effect for this? I think I had a branch attempting it a while back

**Comment by ifreund** [comment]
@ericonr nope, I haven't tried to implement this yet.
