### ISSUE TITLE
separate package for tools in pulseaudio which are useful for pipewire

### ISSUE THREAD

**Issue by gt7-void** [void-linux/void-packages#29576]
For instance: my setup depends on `pactl` which works with `pipewire`. I couldn't find another tool which can replace some of the functionality of `pactl` (e.g. I use `pactl info`, `pactl list short sinks`, `pactl set-default-sink`, `pactl list short sink-inputs`, `pactl move sink-input`, etc. I guess some or all of those can be replaced combining `pw-dump`, `jq` and `pw-cli`, but it's a chore)

Installing pulseaudio is a pain because it's sometimes difficult to avoid having it autolaunch, etc.

As an example, debian has a `pulseaudio-utils` package (https://packages.debian.org/sid/pulseaudio-utils) which contains:
```
  paplay - Playback a WAV file via a PulseAudio sink.
  pacat - Cat raw audio data to a PulseAudio sink.
  parec - Cat raw audio data from a PulseAudio source.
  pacmd - Connect to PulseAudio's built-in command line control interface.
  pactl - Send a control command to a PulseAudio server.
  padsp - /dev/dsp wrapper to transparently support OSS applications.
  pax11publish - Store/retrieve PulseAudio default server/sink/source
                 settings in the X11 root window.
```

I would be content with `pactl`, the others (`paplay`, `pacat`, `parec`) seem to have equivalent included with pipewire (`pw-play`, `pw-cat`, `pw-record`). I don't know about `padsp` or what `pax11publish` is supposed to do. I know `pacmd` does _not_ work with `pipewire`.

**Comment by FollieHiyuki** [comment]
I would suggest using external tools like `pulsemixer` or `pamixer` if you intend to use `pipewire` for it pulseaudio backend.
They require some scripting to be on par with `pactl`, but I find it reasonably better than splitting `pulseaudio`.

**Comment by gt7-void** [comment]
Functionality of `pactl` I miss (not available in `pulsemixer` or `pamixer` afaict):
 - print the default sink: `pactl info  | sed -ne 's/^Default Sink: //p'`
 - print the default source: `pactl info  | sed -ne 's/^Default Source: //p'`
 - set default sink/source: `pactl set-default-{sink,source} ...`
 - list sink-sources: `pactl list short sink-inputs`
 - list source-outputs: `pactl list short source-outputs`
 - move sink-inputs/source-outputs: `pactl move-{sink-input,source-output} ...`


For example: here's a script I use a lot from a hotkey. It cycles the default sink through the available sinks, and also moves all the sink-inputs to the new default sink. Very handy to switch from speakers to headphones, etc.
```
#! /bin/sh

default_sink="$(pactl info | sed -ne 's/^Default Sink: //p')"
sinks="$(pactl list short sinks | awk '{print $2}')"

next="$(printf "%s\n%s\n" "$sinks" "$sinks" | grep -A1 -m1 "$default_sink" | tail -1)"

pactl set-default-sink "$next"

inputs="$(pactl list short sink-inputs | awk '{print $1}')"
for i in $inputs ; do
    pactl move-sink-input $i $next
done
```

In any case, the point is that some of the tools that ship with `pulseaudio` are useful with pipewire, and not obviously replaced (`some scripting` is not good enough, I guess I could replace `pactl` with "some scripting" 
just as much as I could replace this comment with smoke signals).

**Comment by ericonr** [comment]
I have

```
autospawn=no
```

in my `~/.config/pulse/client.conf` file, and it's always stopped pulse autospawning for me. I'd rather document this in void docs than split the package, but it's not a strong opinion. What do you think?

**Comment by gt7-void** [comment]
Documenting seems always a good idea. I was just reading `pulse-client.conf(5)` and I see there's also the option `daemon-binary`, I wonder if setting `daemon-binary=/usr/bin/pipewire-pulse` would work.

Installing `pulseaudio` also brings `rtkit` to the system. I've no idea what it does, I noticed that (a) pipewire does not depend on rtkit and it works fine without it being installed (b) if rtkit is installed, then it will launch itself when running pipewire.

**Comment by CameronNemo** [comment]
rtkit is used to obtain "real-time" permissions as an unprivileged user. Pipewire can use it, although there appears to be no breakage without it. Perhaps some higher latency.

**Comment by st3r4g** [comment]
Relevant info: https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Migrate-PulseAudio
Looks like `pactl` is the only useful one, and not all functionality has a native equivalent, so I think it would be good to extract it into a standalone subpackage (kinda similar to `glxinfo`). Of course `pulseaudio` would then depend on `pactl`.

**Comment by noarchwastaken** [comment]
I prefer to just package all the `utils`, as what Debian does. Things like `paplay` could be useful for playing audio in the command line. The entire `utils` suite is ~280KB installed, which is still more lightweight than ~6MB for the `pulseaudio` package.

**Comment by st3r4g** [comment]
> I prefer to just package all the utils, as what Debian does.

Fair enough. Pipewire could implement more functionality in the future and make other tools useful, who knows.
