### ISSUE TITLE
Issue with pipewire bluetooth (cant connect to paired device)

### ISSUE THREAD

**Issue by Eluminae** [void-linux/void-packages#29570]
### System

An up to date voidlinux

* xuname:  
  *Void 5.10.23_1 x86_64 GenuineIntel uptodate rrrmFFFF*
* package:  
  *pipewire-0.3.23_1*
  *bluez-5.55_1*

### Expected behavior

Having pipewire + bluez setup, I should be able to connect my bluetooth headphone and use it

### Actual behavior

```
[bluetooth]# connect 98:xx:3D:A6:xx:1C
Attempting to connect to 98:xx:3D:A6:xx:1C
Failed to connect: org.bluez.Error.Failed
```

The exact same command with pulseaudio instead of pipewire works like a charm.

### Steps to reproduce the behavior

```
$ sudo xbps-install pipewire bluez
$ sudo ln -s /etc/sv/bluetoothd /var/service/
$ pulseaudio -k # make sure pulseaudio is stopped
$ sudo vim /etc/pipewire/pipewire.conf # make sure to uncomment both context.exec at the end
$ pipewire & # or in another terminal
$ bluetoothctl
[bluetooth]# power on
[bluetooth]# scan on
...
[bluetooth]# pair xx:xx:xx:xx:xx:xx
...
# here you will be connected a very short time then disconnected
[bluetooth]# connect xx:xx:xx:xx:xx:xx
Attempting to connect to xx:xx:xx:xx:xx:xx
Failed to connect: org.bluez.Error.Failed
```

I already tries to remove then re-pair the bluetooth device, or make any kind of combinaison. I got two devices that got the exact same issue. I got the issue with two different machines. Anyway, it works very well with pulseaudio.

Pipewire log this line very early

```
[E][000000903.740297][bluez-monitor.c:572 sm_bluez5_monitor_start()] can't load api.bluez5.enum.dbus: No such file or directory
```

I think maybe it miss something to works correctly with bluez through dbus.

**Comment by ericonr** [comment]
I believe @paper42 uses bluetooth with PW... Requesting help :p 

I can't find that `api.bluez5.enum.dbus`  file anywhere, not sure it's actually necessary...

**Comment by st3r4g** [comment]
do you have `libspa-bluetooth`?

**Comment by Eluminae** [comment]
precise and effective. perfect ! :+1:
