### ISSUE TITLE
Atom package version still broken

### ISSUE THREAD

**Issue by Mirodin** [void-linux/void-packages#2958]
### System

* xuname: Void 4.18.8_1 x86_64 AuthenticAMD uptodate rFF
* package: atom-1.26.1_1

### Expected behavior
`xbps-install -S atom` should pull and install a working version. However starting Atom fails due to missing files which is caused by to long file names.

### Actual behavior
Atom package still affected by https://github.com/void-linux/xbps/issues/2. See forum https://forum.voidlinux.org/t/atom-1-26-1-1-no-gui/5471.

### Steps to reproduce the behavior
Install atom package via xbps.

Should be fixed by rebuilding the package with a recent XBPS version which has this bug fixed.

**Comment by rowbawts** [comment]
Has this been resolved as I'm still having this issue and would like to resolve it if I can.
