### ISSUE TITLE
Create a specific package for OpenLDAP tools

### ISSUE THREAD

**Issue by Ypnose** [void-linux/void-packages#296]
### System

* xuname:  
  Void 4.14.49_1 x86_64 GenuineIntel notuptodate rr
* package:  
  ii openldap-2.4.45_4               OpenLDAP (Lightweight Directory Access Protocol)

### Expected behavior

Could you create a separate package for all ldap* tools included in OpenLDAP packages?

### Actual behavior

Installing the full OpenLDAP suite, only to be able to use tools like ldapsearch or ldapadd is kinda annoying.

Thanks for you help, folks!
Regards :kiss:

**Comment by Ypnose** [comment]
Thanks for your help @maxice8. Looking forward to see the the pull request merged!

**Comment by maxice8** [comment]
done

**Comment by Ypnose** [comment]
Thanks folks!
