### ISSUE TITLE
aarch64* exec format error post base-chroot install

### ISSUE THREAD

**Issue by waynevanson** [void-linux/void-packages#29603]
### System

* xuname:  
  *output of `Void 5.10.24_1 x86_64 GenuineIntel notuptodate rFFFFFF` (part of xtools)*
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior

Should install in the masterdir without any errors.

Because of the error, I cannot natively build aarch64* packages.

### Actual behavior
```sh
0 downloaded, 65 installed, 0 updated, 65 configured, 0 removed.
=> xbps-src: installed base-chroot successfully!
ERROR Failed to execute command /void-packages/xbps-src (Exec format error)
```
### Steps to reproduce the behavior

```sh
git clone git@github.com:void-linux/void-packages
cd void-packages
./xbps-src -m masterdir-aarch64 binary-bootstrap aarch64
```

**Comment by sgn** [comment]
Work as expected, you're expected to either:
- cross compiling; or
- failing at this step, copy `/usr/bin/qemu-aarch64-static` into `$MASTERDIR/usr/bin`, enable binfmts support outside of chroot, and reconfigure your `$MASTERDIR` (in theory, we can do this automatically, if `qemu-aarch64-static` is available outside of chroot, and binfmts is enabled, the qemu-aarch64-static could be fetch from some remote, but binfmts must be enabled by local `root` account).

**Comment by waynevanson** [comment]
I don't quite understand. When I use any other arch excluding aarch64*, I don't get this problem. 

I'm using contributing a package template that doesn't cross compile (uses `haskell-stack`). I feel there shouldn't be any fluffing around to get something like this to work, as I've followed the instructions in the `README.md` for native compilation on a different arch.

`qemu-aarch64-static` is available in my `"$PATH"`.
I copied to both masterdirs and the output is still the same.

> enable binfmts support outside of chroot
> ... and reconfigure your $MASTERDIR

How could I go about this? I'm unsure of what the commands required.

**Comment by sgn** [comment]
On 2021-03-19 22:41:49-0700, Wayne Van Son ***@***.***> wrote:
> I don't quite understand. When I use any other arch excluding aarch64*, I don't get this problem. 

What's the other arches? x86_64-musl and i686, I guess.
They can run natively in x86_64 ;)

> 
> I'm using contributing a package template that doesn't cross compile
> (uses `haskell-stack`). I feel there shouldn't be any fluffing
> around to get something like this to work, as I've followed the
> instructions in the `README.md` for native compilation on
> a different arch.

Just mark it's as nocross.

> 
> `qemu-aarch64-static` is available in my `"$PATH"`.
> I copied to both masterdirs and the output is still the same.

cp /usr/bin/qemu-aarch64-static $MASTERDIR/usr/bin/qemu-aarch64-static

> 
> > enable binfmts support outside of chroot
> > ... and reconfigure your $MASTERDIR
> 
> How could I go about this? I'm unsure of what the commands required.

xbps-install bintfmt-support
update-binfmts

-- 
Danh
