### ISSUE TITLE
Connmanctl not functioning at all

### ISSUE THREAD

**Issue by mattheusroxas** [void-linux/void-packages#29653]
### System

* xuname:  
  `Void 5.10.25_1 x86_64 AuthenticAMD uptodate rFFFFFFF`
* package:  
  `connman-1.39_1`

### Expected behavior
Do literally anything asides from `help`

### Actual behavior
Returns the error: 
`Error getting services: Rejected send message, 3 matched rules; type="method_call", sender=":1.71" (uid=1000 pid=6198 comm="connmanctl ") interface="net.connman.Manager" member="GetServices" errorError getting peers: Rejected send message, 3 matched rules; type="method_call", sender=":1.71" (uid=1000 pid=6198 comm="connmanctl ") interface="net.connman.Manager" member="GetPeers" error name=Error getting technologies: Rejected send message, 3 matched rules; type="method_call", sender=":1.71" (uid=1000 pid=6198 comm="connmanctl ") interface="net.connman.Manager" member="GetTechnologies" error name="(unset)" requested_reply="0" destination="net.connman" (uid=0 pid=6085 comm="connmand -n ")
`

## Once all interfering services are disabled; dhcpd; wpa_supplicant
`connmanctl`
Use any option that isn't `help`
Error returns

**Comment by FollieHiyuki** [comment]
What do you mean like `not functioning at all` :)

Have you enabled the `connmand` service after disable all the other `dhcpd, wpa_supplicant, ...`?

**Comment by mattheusroxas** [comment]
Of course, I didn't include it in the issue because I thought it would be assumed that I did already.

**Comment by mattheusroxas** [comment]
I mean, it's not working at all. Practically everything except `help` gives the same error.

**Comment by FollieHiyuki** [comment]
Can you show us the output of `sv status /var/service/*`. It still seems like something is interfering the service.

**Comment by mattheusroxas** [comment]
Returns:
`run: /var/service/acpid: (pid 1159) 7594s
run: /var/service/agetty-hvc0: (pid 14389) 4s
run: /var/service/agetty-hvsi0: (pid 14391) 4s
run: /var/service/agetty-tty1: (pid 1175) 7594s
run: /var/service/agetty-tty2: (pid 1167) 7594s
run: /var/service/agetty-tty3: (pid 1169) 7594s
run: /var/service/agetty-tty4: (pid 1183) 7594s
run: /var/service/agetty-tty5: (pid 1178) 7594s
run: /var/service/agetty-tty6: (pid 1184) 7594s
run: /var/service/chronyd: (pid 1174) 7594s
run: /var/service/dbus: (pid 1186) 7594s
run: /var/service/dhcpcd: (pid 1165) 7594s
run: /var/service/elogind: (pid 1180) 7594s
run: /var/service/sshd: (pid 1162) 7594s
run: /var/service/tlp: (pid 1158) 7594s
run: /var/service/transmission-daemon: (pid 1173) 7594s
run: /var/service/udevd: (pid 1181) 7594s
run: /var/service/uuidd: (pid 1161) 7594s
run: /var/service/wpa_supplicant: (pid 1157) 7594s
`
Sorry for the super late reply, I've been pretty busy.

**Comment by FollieHiyuki** [comment]
Those services are normal.
Another question: is your user in `network` group?

1 side note: you should not enable both `elogind` and `acpid` daemons. See [here](https://docs.voidlinux.org/config/power-management.html#elogind)

**Comment by mattheusroxas** [comment]
No my user wasn't, that was the issue. Thanks for the help and the tip!
