### ISSUE TITLE
gcc and libada-devel

### ISSUE THREAD

**Issue by unspecd** [void-linux/void-packages#29678]
### System

* xuname:  
  *Void 5.10.25_1 x86_64-musl GenuineIntel uptodate rrrnFFFFFFFFFFF*
* package:
  *gcc-10.2.1pre1_3*

### Expected behavior
```console
$ xbps-query --repository=$(xdistdir)/hostdir/binpkgs -f gcc | grep /ada  # empty output
```
### Actual behavior

```console
$ xbps-query --repository=$(xdistdir)/hostdir/binpkgs -f gcc | grep /ada
/usr/lib/gcc/x86_64-linux-musl/10.2/plugin/include/ada/gcc-interface/ada-tree.def
```
Note that this file should be in the `libada-devel` package.

### Steps to reproduce the behavior
```console
$ ./xbps-src -o ~ada pkg gcc
```

**Comment by ericonr** [comment]
Is this a "cleanliness" issue or does it also break something?

**Comment by sgn** [comment]
On 2021-03-23 20:09:28-0700, Érico Nogueira Rolim ***@***.***> wrote:
> Is this a "cleanliness" issue or does it also break something?

It breaks base-chroot for ~ada.
