### ISSUE TITLE
I can listen other users sound

### ISSUE THREAD

**Issue by ayoubkafi** [void-linux/void-packages#29714]
### System

* xuname:  
  * Void 5.10.17_1 x86_64 GenuineIntel notuptodate rrFFF
* package:  
  * pulseaudio-14.2_2

### Expected behavior
pulseaudio audio should run in the active user tty
### Actual behavior
pulseaudio play audio on any tty even it doesn't have a user logged on
### Steps to reproduce the behavior
Play an audio clip and switch between ttys

**Comment by ericonr** [comment]
Are you using the pulseaudio service? Otherwise I don't think this should happen...

Do you have elogind installed?

**Comment by ayoubkafi** [comment]
Yes

> Are you using the pulseaudio service? Otherwise I don't think this should happen...
> 
> Do you have elogind installed?

Yes I'm using pulseaudio service
i installed it after I saw your comment

**Comment by sgn** [comment]
On 2021-03-25 03:23:51-0700, ayoubkafi ***@***.***> wrote:
> Yes
> 
> > Are you using the pulseaudio service? Otherwise I don't think this should happen...
> > 
> > Do you have elogind installed?
> 
> Yes I'm using pulseaudio service
> i installed it after I saw your comment

Please don't run pulseaudio as root

**Comment by ayoubkafi** [comment]
> On 2021-03-25 03:23:51-0700, ayoubkafi ***@***.***> wrote: Yes > Are you using the pulseaudio service? Otherwise I don't think this should happen... > > Do you have elogind installed? Yes I'm using pulseaudio service i installed it after I saw your comment
> Please don't run pulseaudio as root

The default command for running pulseaudio with runit is  `exec pulseaudio --system` but this is doesn't work with so I replaced it with `exec pulseaudio --daemonize=no` and this works
Should I use something else

**Comment by oynqr** [comment]
Don't run pulseaudio as a service. If you use a display manager it should start automatically.

**Comment by ayoubkafi** [comment]
I removed pulseaudio from /var/service but pulseaudio still start automatically when I play video
before playing videos pulseaudio wasn't running

**Comment by ericonr** [comment]
Yes. PulseAudio autostarts when something wants it.

**Comment by ayoubkafi** [comment]
> Yes. PulseAudio autostarts when something wants it.

So can I disable this setting? How I can prevent it from playing audio in other users session?

**Comment by ericonr** [comment]
When it's autostarted as the user it shouldn't continue playing when you switch to another user's session... At least it doesn't, in my experience.

I'm not sure how to debug further, sorry.

**Comment by ayoubkafi** [comment]
I tried to debug pulseaudio, when i switch between ttys i see this message
`D: [pulseaudio] module-udev-detect.c: /dev/snd/controlC0 is accessible: yes`
I thought it was a permissions issue and I got out of the audio and video group then the problem gon
