### ISSUE TITLE
No StartTLS with Kmail

### ISSUE THREAD

**Issue by Justinizer** [void-linux/void-packages#29739]
### System

* xuname:  
  * Void 5.11.9_1 x86_64 GenuineIntel uptodate rrrmFFFFFF
* package:  
  * kmail-20.12.3_1

### Expected behavior
* Should receive e-mail over StartTLS
### Actual behavior
* Throws error: `SASL(-4): no mechanism available: No worthy mechs found`
### Steps to reproduce the behavior
* Use Kmail and connect to an E-mail Server over StartTLS (Port: 143) with plain mechanism per IMAP. The server is using ECC certificates based on letsencrypt.
* I checked kmail with another system (ArchLinux and Debian) and used thunderbird on VoidLinux to exclude errors based on server. On ArchLinux and Debian KMail works.
(Personally I think that the SASL Plugin for PLAIN is missing)

**Comment by Johnnynator** [comment]
The problem was the missing sasl plugins. Added a hard dep of kimap to them now. (Also done like that in Debian)
https://github.com/void-linux/void-packages/commit/0e4d43b5ab7c13652fac5175b6e1be1650530551
