### ISSUE TITLE
qt5: fails to build

### ISSUE THREAD

**Issue by unspecd** [void-linux/void-packages#29732]
### System
* xuname:  
  *Void 5.10.25_1 x86_64-musl GenuineIntel uptodate rrrnFFFFFFFFFFF*
* package:  
  *qt5-5.15.2_4*

### Expected behavior
qt5 compiles and packages successfully.

### Actual behavior
```console
$ ./xbps-src pkg qt5
…
=> qt5-gui-5.15.2_4: running pre-install hook: 98-fixup-gir-path ...
=> qt5-gui-5.15.2_4: running pkg_install ...
mv: cannot stat '/destdir//qt5-5.15.2/usr/lib/libQt5XcbQpa.so*': No such file or directory
=> ERROR: qt5-gui-5.15.2_4: pkg_install: 'mv ${_destdir}/$files ${_pkgdestdir}/${_targetdir}' exited with 1
```

### etc/conf
```sh
XBPS_CFLAGS+=" -march=native -mtune=native"
XBPS_CXXFLAGS="${XBPS_CFLAGS}"
XBPS_CCACHE=yes
XBPS_MAKEJOBS=4
XBPS_DEBUG_PKGS=yes
```

**Comment by ericonr** [comment]
Have you tried not adding to `XBPS_CFLAGS` and/or setting `XBPS_TARGET_{C,CXX}FLAGS`?

**Comment by unspecd** [comment]
> Have you tried not adding to `XBPS_CFLAGS`

Yes. In this case, the error does not happen.
🤔
