### ISSUE TITLE
Why no new kernels available for armv7l?

### ISSUE THREAD

**Issue by Logarithmus** [void-linux/void-packages#29747]
It seems that the latest available kernel for `armv7l` is `linux5.5`. What's the reason?
I've just installed Void Linux on Orange Pi. I used very hacky way of doing that. Firstly I installed Armbian on my microSD card, after that I deleted everything except `/boot` & `/usr/lib/modules`, and finally I unpacked ROOTFS tar.xz archive into the card.

Then I tried to install kernel properly (instead of using Armbian's one), and sadly didn't find linux5.11 in the repo.

**Comment by sgn** [comment]
Because noone is boring enough to provide a configuration for newer kernel. If you can come up with one, feel free to make a PR.
