### ISSUE TITLE
[MUSL] Cannot view image thumbnails in Nautilus

### ISSUE THREAD

**Issue by nek0bit** [void-linux/void-packages#29767]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  nautilus-3.38.2_1
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
Thumbnails show up.

### Actual behavior
Thumbnails do not show up. `~/.cache/thumbnails/fail` is the only directory I see.

### Steps to reproduce the behavior
Fresh-install
/home directory transferred, cleaned up .config file, came from void, gentoo, and back on void. First time every using GNOME.

**Comment by nek0bit** [comment]
Bad solution: Install `dolphin`, view the directory with images. And it gets generated. I do not want to do this.

**Comment by nek0bit** [comment]
**Temporary fix:** `touch /etc/ld.so.cache`
There is a more permanent fix by modifying the bubblewrap source code and changing the cache. Could we do something about this?

**Comment by ericonr** [comment]
So what you're saying is:

- nautilus creates thumbnails by launching a program inside a bubblewrap sandbox
- bubblewrap fails because it can't make the glibc specific file `/etc/ld.so.cache` available inside the sandbox
- you don't get thumbnails

This is hilarious, but it should also be a simple fix.

**Comment by nek0bit** [comment]
> This is hilarious, but it should also be a simple fix.

haha, yep, pretty crazy. Although I bet a patch instead of just adding the file would be cleaner.

**Comment by ericonr** [comment]
Oh, I meant that creating a patch shouldn't be too hard :)

Thanks for the investigation, though :D

**Comment by ericonr** [comment]
@nek0bit as a warning, see the commit message:

> Users will have to remove the "failed generation" cache from ~/.cache/thumbnails/fail/ for nautilus to reattempt thumbnail generation of previously visited directories.

**Comment by nek0bit** [comment]
wonderful work!
