### ISSUE TITLE
Spotify install error (again -I see it has happened before)

### ISSUE THREAD

**Issue by MirceaMx** [void-linux/void-packages#2977]
### System

* xuname:  
  Void 4.18.9_1 x86_64 GenuineIntel notuptodate rFFFF
* package:  
 Spotify 1.0.88_3 -outdated

### Expected behavior
sudo xbps-install -Su spotify

### Actual behavior
**ERROR: spotify-1.0.88_3: [configure] INSTALL script failed to execute the post ACTION: Operation not permitted
**
### Steps to reproduce the behavior
_sudo xbps-install -Su spotify_

**Comment by maxice8** [comment]
The relevant error mesage 

The package is so outdated that the debfile isn't available anymore

```
looking up repository.spotify.com
connecting to repository.spotify.com:80
requesting http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.88.353.g15c26ea1-14_amd64.deb
http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.88.353.g15c26ea1-14_amd64.deb: Not Found
Failed downloading spotify client
ERROR: spotify-1.0.88_3: [configure] INSTALL script failed to execute the post ACTION: Operation not permitted
```

The solution to me seems someone stepping up to maintaining it but to be honest using the flatpak seems all around better

**Comment by MirceaMx** [comment]
The Flatpak does not have many ... features. Like (I'm on KDE Plasma btw) hovering the name in the taskbar and skipping next/previous...
Currently using a Firefox addon for Spotify web. In any case I would maintain it but I don't know how. I tried modifying the template but can't find the place to download the .deb package...don't know how, can't figure out...

**Comment by cr6git** [comment]
@MirceaMx could you test my pull request for the new version ?

**Comment by MirceaMx** [comment]
@cr6git It dosen't seem to work. So what I did was use your template to create spotify-1.0.89_1.x86_64.xbps which is 2 KiB in size meaning it's not working as the size is way to small.

**Comment by maxice8** [comment]
On Fri, Sep 21, 2018 at 07:29:31PM +0000, MirceaMx wrote:
> @cr6git It dosen't seem to work. So what I did was use your template to create spotify-1.0.89_1.x86_64.xbps which is 2 KiB in size meaning it's not working as the size is way to small.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/2977#issuecomment-423646926

Please install and test the package

**Comment by MirceaMx** [comment]
I'm trying now...

**Comment by MirceaMx** [comment]
spotify-client_1.0.89.313.g34a58dea-5_amd64.deb: 98MB [avg rate: 9434KB/s]
spotify-client_1.0.89.313.g34a58dea-5_amd64.deb: OK
spotify-1.0.89_1: installed successfully.

Seems to be **working**

**Comment by MirceaMx** [comment]
![image](https://user-images.githubusercontent.com/40819799/45902482-3f33e880-bdef-11e8-9a47-f031c7558dbd.png)

**Comment by MirceaMx** [comment]
**working**

**Comment by maxice8** [comment]
Next time please try and install the package before claiming it doesn't work because of the size of the generated package.

**Comment by MirceaMx** [comment]
I understand. It downloaded the .deb post install. Did not anticipate that. Sorry. Hope there won't be a _next time_

**Comment by unihernandez22** [comment]
I have this error now
