### ISSUE TITLE
Consider switching to zlib-ng

### ISSUE THREAD

**Issue by Logarithmus** [void-linux/void-packages#29782]
`zlib-ng` is basically a faster & cleaner version of `zlib`. `zlib` folks are too conservative and refuse to take optimizations into upstream. So other folks decided to create `zlib-ng`.
`zlib-ng` devs claim it's 4x faster for compression & 2x for decompression than ordinary `zlib`.
Here are tbenchmark results: https://github.com/zlib-ng/zlib-ng/discussions/871

About 2 weeks ago, after extensive testing & fuzzing, zlib-ng 2.0.0 has been released, the first stable version: https://github.com/zlib-ng/zlib-ng/releases/tag/2.0.0

`zlib-ng` can act as a drop-in replacement for `zlib` when built with `ZLIB_COMPAT` flag.
I'm using `zlib-ng` for more than a week being symlinked to `/usr/lib/libz.so.1` without any problems.

See also: https://github.com/void-linux/void-packages/pull/29544

**Comment by ericonr** [comment]
Beyond even the ABI concerns, the API concerns (for example issues when building NSS) make this a very hard sell. `zlib` being a low maintenance package that is easy to build and carries little maintenance burden are big advantages that trump most performance concerns.
