### ISSUE TITLE
Packaging python poetry

### ISSUE THREAD

**Issue by non-Jedi** [void-linux/void-packages#29799]
I'm attempting to update the python3-matrix-nio package I'm the maintainer for, however the build system has switched to require poetry. At this time, I have no desire to become the maintainer for a new poetry package.

I guess the way forward is to remove the python3-matrix-nio and pantalaimon packages unless somebody is willing to become the maintainer of poetry? Or would it be acceptable to package poetry and instantly mark it as orphaned?

**Comment by sgn** [comment]
On 2021-03-27 20:29:54-0700, Adam B ***@***.***> wrote:
> I'm attempting to update the python3-matrix-nio package I'm the
> maintainer for, however the build system has switched to require
> poetry. At this time, I have no desire to become the maintainer for
> a new poetry package.
> 
> I guess the way forward is to remove the python3-matrix-nio and
> pantalaimon packages unless somebody is willing to become the
> maintainer of poetry? Or would it be acceptable to package poetry
> and instantly mark it as orphaned?

How about use distfiles from PyPI?
Upstream provides a tarball for setuptools there.

**Comment by non-Jedi** [comment]
> How about use distfiles from PyPI? Upstream provides a tarball for setuptools there.

Wasn't aware of that option. I'll go ahead and use it.
