### ISSUE TITLE
intel-gmmlib package requires more CPU features than Void baselineand is compiled with -march=corei7

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#29801]
Reported by @sgn on IRC.

Per https://github.com/intel/gmmlib/blob/2072b0d1e8ba2cba2f94bc2c1fda89d6e457a50b/Source/GmmLib/Linux.cmake :

```
    # General optimization options
    -march=${GMMLIB_MARCH}
    -mpopcnt
    -msse
    -msse2
    -msse3
    -mssse3
    -msse4
    -msse4.1
    -msse4.2
    -mfpmath=sse
    -finline-functions
    -fno-short-enums
    -Wa,--noexecstack
    -fno-strict-aliasing
    # Common defines
    -DUSE_MMX
    -DUSE_SSE
    -DUSE_SSE2
    -DUSE_SSE3
    -DUSE_SSSE3
```

`GMMLIB_MARCH` is set to `corei7` by default, but we can fix that with `configure_args`. What I also worry about are all the `-msse*` switches, since afaik they can affect generated code that isn't directly using compiler intrinsics for them.

**Comment by tornaria** [comment]
It seems, according to https://github.com/intel/gmmlib#supported-platforms, that the supported graphic devices already imply the cpu supports all that.

**Comment by ericonr** [comment]
It seems `corei7` is mostly equivalent to nehalem:

```
  {"corei7", PROCESSOR_NEHALEM, CPU_NEHALEM, PTA_NEHALEM},
```

I don't know if it makes sense to force a different target, then - `corei7` probably generates slightly better code here than `x86_64` would. Maybe we it might just be enough to document these constraints in the template itself. Thanks for the hint!
