### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID in Voidlinux browsers

### ISSUE THREAD

**Issue by lpvm** [void-linux/void-packages#29888]
### System
* xuname:  
Void 5.11.9_1 x86_64 AuthenticAMD uptodate rrFFFFFFFFFFF

When visiting  https://tranquilidade.pt there's an error with the certificate NET::ERR_CERT_AUTHORITY_INVALID

When visiting the website from some other systems, there's no problem.
On the IRC channel I was told that this has to do with debian certificates.
The problem seems to arise when the OS is debian.

**Comment by ericonr** [comment]
I managed to open it now...

**Comment by lpvm** [comment]
I still can't and at least two other people of the #voidlinux on Freenode couldn't open, too.

**Comment by abenson** [comment]
I have not managed to open it without the warning, both on Void and on Debian.

**Comment by biopsin** [comment]
No error with built palemoon, opens fine

**Comment by ericonr** [comment]
This seems to have to do with the portuguese gov using some outdated certs they didn't have time to update; not sure how to proceed from here :)

**Comment by lpvm** [comment]
Tranquilidade is an insurance company, doesn't belong to the State.

**Comment by sgn** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1703090

Please expect NSS 3.64 soon. Sorry that I didn't push nss 3.63.1 ontime.

**Comment by sgn** [comment]
In short: the CA requested to turn off their CA trusting bit in https://bugzilla.mozilla.org/show_bug.cgi?id=1692094
but they found out that some of their customer still relies on it.

**Comment by lpvm** [comment]
Thank you @sgn .
