### ISSUE TITLE
MariaDB 10.1.48 is no longer supported by upstream

### ISSUE THREAD

**Issue by arp242** [void-linux/void-packages#29881]
The current version of MariaDB in Void is 10.1.48; the 10.1 series is a pretty old release series from 2015, which isn't too terrible in itself, but support [ended in Oct 2020](https://mariadb.org/about/#maintenance-policy); the 10.1.48 release they did in November is the [last release they will do](https://mariadb.com/kb/en/mariadb-10148-release-notes/).

Having an old unsupported release of MariaDB probably does more harm than good; the last 10.1.48 release fixed three CVEs. Unless someone steps up to update this to a supported version (I don't use MariaDB myself and just had to test a few compatibility things so I'm not volunteering, sorry 😅), I propose that this package be removed from Void for the time being.

There is an unfinished WIP patch to update it to 10.5.x in #25618.

**Comment by Veganizer** [comment]
Try it here:
https://github.com/void-linux/void-packages/pull/30143

If someone knows how to fix cross-compiling ... Help would be recommended. :-)

**Comment by Veganizer** [comment]
Should work now. :-) Hope they will push it to upstream!

**Comment by Johnnynator** [comment]
ab007f508110d61a2631a691714bf3ea3280658b
