### ISSUE TITLE
missing icons in adwaita

### ISSUE THREAD

**Issue by TeddyDD** [void-linux/void-packages#2989]
### System

* xuname:  
  Void 4.17.19_1 x86_64 GenuineIntel uptodate rFFFFFFFFF
* package:  
 adwaita-icon-theme-3.28.0_1, adwaita-icon-theme-3.30.0_1

### Expected behavior

Gtk based programs should work

### Actual behavior
Programs that use Gtk are crashing. Firefox crashes when file dialog is opened. Peek and Glade crashes on start. 
```
(peek:30444): Gtk-WARNING **: 03:33:01.200: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

File image-missing.png exist:
```
ls -la /usr/share/icons/Adwaita/16x16/status/image-missing.png
-rwxr-xr-x 1 root root 405 09-09 17:47 /usr/share/icons/Adwaita/16x16/status/image-missing.png*
```

### Steps to reproduce the behavior
- run Gtk app from terminal

**Comment by cr6git** [comment]
No, no problem for me.

**Comment by TeddyDD** [comment]
All right, it was broken on my end, `/usr/share/mime` or `/usr/share/mime-info` had bad permission set

**Comment by ErinVoid** [comment]
This has occurred on two of my laptops and affects more than just Adwaita. See [this forum link](https://forum.voidlinux.org/t/gtk-icons-not-displaying/6958/6). Seems to be the phantom umask issue reappearing.

**Comment by necronoise** [comment]
> This has occurred on two of my laptops and affects more than just Adwaita. See [this forum link](https://forum.voidlinux.org/t/gtk-icons-not-displaying/6958/6). Seems to be the phantom umask issue reappearing.

Forum is dead, I also have the same problem.

**Comment by TeddyDD** [comment]
For the record: this happened to me again today :thinking:
