### ISSUE TITLE
Package Request: Boxxy Font and Openspades Game

### ISSUE THREAD

**Issue by klaus1488** [void-linux/void-packages#2991]
1) the boxxy font by some guy nicknamed caffeinebasedlifeform: [link here](https://github.com/Tecate/bitmap-fonts/tree/master/bitmap/boxxy) and [here](https://aur.archlinux.org/packages/bdf-boxxy/) 

2) a very fun open-source FPS multiplayer game called openspades: [link here](https://github.com/yvt/openspades)

**Comment by Hoshpak** [comment]
working on Openspades

**Comment by cr6git** [comment]
There aren't any releases for boxxy font.

**Comment by Johnnynator** [comment]
@Hoshpak I have openspades already

**Comment by Johnnynator** [comment]
https://github.com/Johnnynator/void-packages/tree/openspades

I still have to fix licensing. You can work on that

**Comment by skrps** [comment]
Original link for boxxy font "announcement": https://bbs.archlinux.org/viewtopic.php?pid=958529#p958529

As the repository pointed by OP is an unofficial repository, releases aren't to be expected.

Dropping the `.pcf` file into `~/.local/share/fonts/` should be enough for that case; it's what I'm doing with the [Siji font](https://github.com/stark/siji), while the author doesn't [tag](https://github.com/stark/siji/issues/12) a [release](https://github.com/stark/siji/issues/9).

**Comment by cr6git** [comment]
> Dropping the .pcf file into ~/.local/share/fonts/ should be enough for that case

it's fine, no need to create a package just for this...
