### ISSUE TITLE
ffmpeg libvpx ABI mismatch with libvpx6-1.10.0_1

### ISSUE THREAD

**Issue by w1kl4s** [void-linux/void-packages#29941]
### System

* xuname:  
  Void 5.11.11_1 x86_64 AuthenticAMD uptodate hold rrrrmmnDFFFF
* package:  
  libvpx6-1.10.0_1, ffmpeg-4.3.2_1

ffmpeg with libvpx6-1.10.0_1 seems to cause a ABI version mismatch:
`[libvpx-vp9 @ 0x55c640248fc0] Failed to initialize encoder: ABI version mismatch`

downgrading to libvpx6-1.9.0_1 fixes this issue - seems to be caused by ffmpeg built against older version. Rebuilding ffmpeg with new libvpx should fix the issue.

**Comment by ericonr** [comment]
Ah, thanks! I had heard about it but hadn't managed to find what exactly changed.

@Johnnynator do you know why only ffmpeg seems to be affected?

**Comment by ericonr** [comment]
Btw, how did you get the error to appear? I couldn't generate it...

**Comment by w1kl4s** [comment]
Simply running `ffmpeg -i something.mp4 -c:v libvpx out.webm` does it for me - works when downgraded to 1.9, spits out ABI mismatch when upgraded to 1.10.
