### ISSUE TITLE
Update wireless-regdb

### ISSUE THREAD

**Issue by ab932** [void-linux/void-packages#2999]
https://github.com/void-linux/void-packages/blob/4a00d41d3d4757f443b56899010f420f718a4672/srcpkgs/crda/template#L6

This is causes recent kernels to fail to find /lib/firmware/regulations.db when loading cfg80211

[  220.774252] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  220.774267] cfg80211: failed to load regulatory.db

See here: https://patchwork.kernel.org/patch/10128825/

**Comment by maxice8** [comment]
@thypon seems like Arch uses snapshots of crda from https://git.kernel.org/pub/scm/linux/kernel/git/mcgrof/crda.git/

**Comment by ab932** [comment]
I think it might make sense to connect crda and wireless-regdb as two packages.
I'm not sure what you are referring to by mentioning Arch but this is the wireless-regdb package in Arch:
https://www.archlinux.org/packages/core/any/wireless-regdb/

**Comment by maxice8** [comment]
> I think it might make sense to connect crda and wireless-regdb as two packages.

wireless-regdb is fetched during building of the crda package, see distfiles=

**Comment by ab932** [comment]
Yes, I am aware of that. I'm saying it might make sense to break off wireless-regdb into a separate package.

**Comment by maxice8** [comment]
On Sat, Sep 22, 2018 at 01:11:51PM -0700, ab932 wrote:
> Yes, I am aware of that. I'm saying it might make sense to break off wireless-regdb into a separate package.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/2999#issuecomment-423770092

They are a circular dependency as far as i know

**Comment by thypon** [comment]
@ab932 I would like to wait for a stable release of the new `crda` before updating both. The error shown are non fatal and the wifi will continue to work even without the newer `crda`.

**Comment by cr6git** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892229

It looks like Debian takes care of this by applying some pacthes for [4.18.8](https://sources.debian.org/patches/linux/4.18.8-1/debian/wireless-disable-regulatory.db-direct-loading.patch/) and [4.19-rc4](https://sources.debian.org/patches/linux/4.19%7Erc4-1%7Eexp1/debian/wireless-disable-regulatory.db-direct-loading.patch/).

**Comment by maxice8** [comment]
The maintainer of the package is aware and has answered
