### ISSUE TITLE
`python3 setup.py cython` segfaults on i686

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#30008]
`python3-3.9.3_1` - given that CI in the pygame PR worked, I'm fairly confident it was due to 3.9.3.

Examples:

- https://build.voidlinux.org/builders/i686_builder/builds/31605/steps/shell_3/logs/stdio
- #29744 

Just `python3 setup.py build` works, but `cython` makes it segfault.

@ahesford

**Comment by ahesford** [comment]
A backport gone wrong: https://pythoninsider.blogspot.com/2021/04/python-394-hotfix-is-now-available.html

The fix is in 3.9.4 and will be merged shortly.
