### ISSUE TITLE
Android File Transfer

### ISSUE THREAD

**Issue by free-tinker** [void-linux/void-packages#30013]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
I want to transfer file to my android phone, so i installing android-file-transfer package.
Usually, the phone can be found in file manager.
### Actual behavior
But I got nothing. My phone does appear on lsusb as MTP mode. I had reboot but still doesn't work.

**Comment by FollieHiyuki** [comment]
Have you install `android-udev-rules`?
Then if it still doesn't work, go into the rule file and manually change the line with the series of your phone.
[Arch Wiki](https://wiki.archlinux.org/index.php/MTP) for reference.

**Comment by Anachron** [comment]
Yeah this is too less information to be able to help you.
Make sure udev picks up your device and the permissions to access your phone are on your local user.
Also check your kernel messages and see what lsusb and such report.

**Comment by free-tinker** [comment]
@FollieHiyuki I did. I follow the gvfs-mtp method. The device is mounted on file manager, but when i open it, it says location is unmountable.

@Anachron dmesg shows no problem. It is mounted but when i click on it, it says location is unmountable.
[21422.700471] usb 1-1: New USB device strings: Mfr=2, Product=3, SerialNumber=4
[21422.700475] usb 1-1: Product: GT-I9082
[21422.700478] usb 1-1: Manufacturer: Samsung
[21422.700480] usb 1-1: SerialNumber: 4100aa0d01e74000
[21426.772542] usb 1-1: USB disconnect, device number 13
[21427.025264] usb 1-1: new high-speed USB device number 14 using xhci_hcd
[21427.153768] usb 1-1: New USB device found, idVendor=04e8, idProduct=6860, bcdDevice= 4.00
[21427.153777] usb 1-1: New USB device strings: Mfr=2, Product=3, SerialNumber=4
[21427.153780] usb 1-1: Product: GT-I9082
[21427.153782] usb 1-1: Manufacturer: Samsung
[21427.153785] usb 1-1: SerialNumber: 4100aa0d01e74000

**Comment by free-tinker** [comment]
I'm sorry
I mean 'Location is not mountable'

**Comment by free-tinker** [comment]
Volume(0): GT I9082
  Type: GProxyVolume (GProxyVolumeMonitorMTP)
  ids:
   unix-device: '/dev/bus/usb/001/024'
  activation_root=mtp://Samsung_GT-I9082_4100aa0d01e74000/
  themed icons:  [phone]
  symbolic themed icons:  [phone-symbolic]  [phone]
  can_mount=1
  can_eject=0
  should_automount=1

**Comment by FollieHiyuki** [comment]
`gvfs-mtp` doesn't work for me either (the machine doesn't recognize the phone as a USB device) but `android-file-transfer` does, so I don't bother fixing it. And I suggest only use 1 of the 2 methods.
For `android-udev-rules` you need to add your phone rule to `/etc/udev/rules.d/`. Here is an example of mine:
```
SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", ATTR{idProduct}=="6860", MODE="0666", OWNER="users", ENV{ID_MTP_DEVICE}="1", SYMLINK+="libmtp"
```

**Comment by free-tinker** [comment]
It works now.
Thank you for your responses
