### ISSUE TITLE
libinput 1.17.1_1 update causes Firefox to instantly select the first option on right click

### ISSUE THREAD

**Issue by pyramidhead52** [void-linux/void-packages#30049]
The new 1.17.1 update of libinput package sometimes causes Firefox to instantly select the first option on right click actions. It's all fine on 1.16.4.

**Package:** libinput
**Version:** 1.17.1_1 (1.16.4_1 is fine)
**WM:** bspwm

**Comment by ericonr** [comment]
This might be an X only thing :/

Can you share details about your device? Touchpad/mouse etc?

**Comment by pyramidhead52** [comment]
**Device:** Huawei Matebook D 14 AMD Ryzen 5 3500u

I'm just using my touchpad's two finger right click function, no mouse.

```
sudo dmesg | grep touchpad

input: ELAN2204:00 04F3:3109 Touchpad as /devices/platform/AMDI0010:01/i2c-11/i2c-ELAN2204:00/0018:04F3:3109.0001/input/input13
input: ELAN2204:00 04F3:3109 Touchpad as /devices/platform/AMDI0010:01/i2c-11/i2c-ELAN2204:00/0018:04F3:3109.0001/input/input16
```

```
cat /etc/X11/xorg.conf.d/30-touchpad.conf

Section "InputClass"
	Identifier "libinput touchpad catchall"
	MatchIsTouchpad "on"
	MatchDevicePath "/dev/input/event*"
	Driver "libinput"
	Option "Tapping" "on"
	Option "NaturalScrolling" "true"
EndSection
```

I've downgraded to 1.16.4 and it works just fine. I think it's related to these 1.17 changes:

https://www.phoronix.com/scan.php?page=news_item&px=Libinput-1.17-Released

**Comment by ericonr** [comment]
Out of curiosity, have you tried without that config file?

**Comment by pyramidhead52** [comment]
I just tried, the problem persists without that config file.

**Comment by NeelChotai** [comment]
Setting `ui.context_menus.after_mouseup` to `true` in `about:config` should fix it.
