### ISSUE TITLE
The python3-pip package is broken.

### ISSUE THREAD

**Issue by Uiyx** [void-linux/void-packages#30048]
### Expected behavior
The pip3 command to work
### Actual behavior
which: no pip3 in (/home/kris/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin)
### Steps to reproduce the behavior
xbps-install python3-pip
which pip3

**Comment by ericonr** [comment]
Hi! Did you close this because `pip` exists? It might be better by python guidelines to have `pip3` as well, so we could consider it.
