### ISSUE TITLE
orientdb has moved to different hosting and doesn't provide the old version anymore

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#30041]
https://www.orientdb.com points at https://orientdb.org , but I can't find the version of the package we use (2.2.29). Would suggest either updating or removing the package.

@bougyman

**Comment by digitalagedragon** [comment]
Looks like they have [a GH repo](https://github.com/orientechnologies/orientdb) that does contain tags for historical releases. 2.2.29 is on there, but it's also a major release and 3 years old by now so it probably makes sense to update.

**Comment by digitalagedragon** [comment]
https://github.com/digitalagedragon/void-packages/commit/22c7d3f972a7400711c72c3f9423077d878dc7c3 would get it on 3.1.11, which does appear to work (to the level of "you can start the server up and screw around with the demo database," at least.)

The only question I'd have is whether going from 2.x to 3.x would be a problem.

**Comment by ericonr** [comment]
Maybe they have a porting document we could use? Does the service also work with that version?

I think people using this should be relatively aware of their stuff, so an update would be noticed anyway, and they'd probably know where to look for such info anyway, so if you can't find it I still think it's worth the update.

**Comment by digitalagedragon** [comment]
http://orientdb.com/docs/3.0.x/release/3.0/Upgrading-to-OrientDB-3.0.html says 3.x is pretty backwards-compatible at least.

Per http://orientdb.com/docs/3.0.x/release/Upgrade.html, though, it sounds like they consider moving an existing installation from 2.x to 3.x to require some degree of manual intervention? Not sure.

**Comment by ericonr** [comment]
I think these are all natural evolutions of the language, and not something that needs to be mentioned in an `INSTALL.msg`. So I'd go ahead with the simple update.
