### ISSUE TITLE
Can't fine glib-compile-resources

### ISSUE THREAD

**Issue by rivanfebrian123** [void-linux/void-packages#30066]
Hi there! I really love void linux for its performance. It runs smoothly on my old gen i3 laptop.

First off, I'm a GTK theme developer and I wanna give it support for Void Linux theme instalation, but I got stuck at `glib-compile-resources`. I couldn't find it on Google or in https://sources.voidlinux.org/. I also tried to install `glib-2xxx` but got no luck. Can you help me, please?

**Comment by FollieHiyuki** [comment]
Try installing `glib-devel`.
And you can check what package has the file you want with `xlocate` tool from `xtools` package.

**Comment by sgn** [comment]
Closing, solution provided by FollieHiyuki

**Comment by rivanfebrian123** [comment]
> Try installing `glib-devel`.
> And you can check what package has the file you want with `xlocate` tool from `xtools` package.

Thanks for your solution! :D
