### ISSUE TITLE
Sway isn't opening 

### ISSUE THREAD

**Issue by doonoo** [void-linux/void-packages#30115]
![20210409_165759](https://user-images.githubusercontent.com/18385494/114239975-ca950b00-9954-11eb-878a-cffbe4c3ea69.jpg)
I linked elogind and now this happened. I don't know what I'm doing wrong?

**Comment by ericonr** [comment]
Are both `dbus` and `elogind` services enabled? I'd suggest a restart.

**Comment by doonoo** [comment]
> Are both `dbus` and `elogind` services enabled? I'd suggest a restart.

Yes sir it is

**Comment by noarchwastaken** [comment]
Try installing polkit... From what I can find online, elogind stopped working without polkit.

**Comment by travankor** [comment]
>Try installing polkit... From what I can find online, elogind stopped working after an update, and it worked again for me after installing polkit.

Adding build option `-Dpolkit=false` could be the workaround for this, then.

**Comment by doonoo** [comment]
> Try installing polkit... From what I can find online, elogind stopped working after an update, and it worked again for me after installing polkit.
> 
> https://www.reddit.com/r/voidlinux/comments/l2pbdz/sway_freeze_after_update/

Thanks, this worked.

**Comment by noarchwastaken** [comment]
This seems to be fixed in upstream release 246.10:

https://github.com/elogind/elogind/releases/tag/v246.10

**Comment by noarchwastaken** [comment]
Ah, unfortunately, the polkit support fix in 246.10 broke it entirely:

https://github.com/elogind/elogind/issues/206

should we wait for the next release?

**Comment by noarchwastaken** [comment]
I just built `elogind` with `-Dpolkit=false` today, and the problem is still there...

**Comment by Duncaen** [comment]
`elogind` was reverted to `elogind-246.9.2_2` in 2ca69e335b.

**Comment by deepaknegilachu** [comment]
# with seatd

sudo xbps-install seatd 
useradd -aG _seatd <username> 
sudo ln -s /etc/sv/seatd /var/service

and then add this in bash_profile or zprofile(for zsh):

if test -z "${XDG_RUNTIME_DIR}"; then
    export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
    if ! test -d "${XDG_RUNTIME_DIR}"; then
        mkdir "${XDG_RUNTIME_DIR}"
        chmod 0700 "${XDG_RUNTIME_DIR}"
    fi
fi

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
export MOZ_ENABLE_WAYLAND=1 

# with elogind 
add this this on bash_profile or zprofile:

export LIBSEAT_BACKEND="logind"
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
export MOZ_ENABLE_WAYLAND=1

**Comment by ignamartinoli** [comment]
Is this problem still presented?
