### ISSUE TITLE
Gnome Terminal Title

### ISSUE THREAD

**Issue by free-tinker** [void-linux/void-packages#30173]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
gnome-terminal-3.40.0_1
firejail-0.9.64.4_1

### Expected behavior
The terminal title back to "Terminal"
### Actual behavior
my gnome terminal title freeze after using firejail.
example: firejail icecat.
then the terminal title become "firejail icecat" even after firejail stopped.

**Comment by ericonr** [comment]
Can you share xuname output? Or at least `xbps-uhelper arch`.

**Comment by darmon77** [comment]
The icecat profile in firejail is the firefox-common.profile 
I am using firejail on a musl system and I don't have the problem you mention.
try to reproduce the behavior you indicate in xorg and wayland 
also run firecfg and log out and then try to run icecat
`➜  ~ icecat
Reading profile /etc/firejail/icecat.profile
Reading profile /etc/firejail/firefox-common.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-devel.inc
Reading profile /etc/firejail/disable-exec.inc
Reading profile /etc/firejail/disable-interpreters.inc
Reading profile /etc/firejail/disable-programs.inc
Reading profile /etc/firejail/whitelist-common.inc
Reading profile /etc/firejail/whitelist-runuser-common.inc
Reading profile /etc/firejail/whitelist-var-common.inc
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Parent pid 18707, child pid 18708
Warning: cannot find /var/run/utmp
Warning: An abstract unix socket for session D-BUS might still be available. Use --net or remove unix from --protocol set.
Warning: cleaning all supplementary groups
Warning: /sbin directory link was not blacklisted
Warning: /usr/sbin directory link was not blacklisted
Warning: cleaning all supplementary groups
Seccomp list in: !chroot, check list: @default-keep, prelist: unknown,
Child process initialized in 253.11 ms
JavaScript error: resource://activity-stream/lib/Screenshots.jsm, line 127: TypeError: cache is undefined
JavaScript error: resource://activity-stream/lib/Screenshots.jsm, line 127: TypeError: cache is undefined
JavaScript error: resource://activity-stream/lib/Screenshots.jsm, line 127: TypeError: cache is undefined
JavaScript error: resource://activity-stream/lib/Screenshots.jsm, line 127: TypeError: cache is undefined
JavaScript error: resource://activity-stream/lib/Screenshots.jsm, line 127: TypeError: cache is undefined

Parent is shutting down, bye...
`

**Comment by free-tinker** [comment]
@ericonr 
~ xbps-uhelper arch
x86_64

@darmon77 i'm using wayland. I don't know why its happen. I just don't get the "Terminal" word back and changed to "firejail..." command on my gnome-terminal title.

**Comment by Gottox** [comment]
Can this behavior be reproduced on other terminals than gnome-terminal?

**Comment by paper42** [comment]
I think this is an upstream bug, firejail doesn't seem to clear the title when it exits. You can try running these two commands:
```
printf "\033]0;title\007"
printf "\033]0;\a"
```
The first one sets the title, the second one, which firejail doesn't use, resets it to default. Please open an issue upstream @free-tinker.

**Comment by free-tinker** [comment]
@Gottox I don't know yet. Which other terminal can be used on gnome wayland ?

@paper42 How to open issue upstream ? I'm a newbie. I'm sorry.

**Comment by paper42** [comment]
@free-tinker no worries, go to their [github repository](https://github.com/netblue30/firejail/) and create a new issue there just like you did here. Describe what is happening and link this issue.

**Comment by free-tinker** [comment]
@paper42 ok. Thank You for the detail explanation. I'm very appreciate it. 


Thank you for all the responses.

**Comment by ericonr** [comment]
For reference https://github.com/netblue30/firejail/issues/4197
