### ISSUE TITLE
Image not authentic

### ISSUE THREAD

**Issue by thehornydragon** [void-linux/void-packages#30174]
Hello,

I've just downloaded void-live-x86_64-20210218-xfce.iso, and have gone through the following steps as recommended on the download page:

Downloaded the sha256sum.sig, sha256sum.txt, and the void-release-20210218.pub files for verification.

Installed the signifiy-openbsd package (on Ubuntu 20.04 LTS, from the default repository).

Ran the following command: signify-openbsd -C -p ./void-release-20210218.pub -x ./sha256sum.sig ./void-live-x86_64-20210218-xfce.iso

Expected outcome: Signature Verified
./void-live-x86_64-20210218-xfce.iso: OK

Actual outcome: Signature Verified
./void-live-x86_64-20210218-xfce.iso: FAIL

sha256sum.sig/.txt were downloaded from here: https://alpha.de.repo.voidlinux.org/live/current/

void-release-20210218.pub was downloaded from here:
https://raw.githubusercontent.com/void-linux/void-packages/master/srcpkgs/void-release-keys/files/void-release-20210218.pub

**Comment by thehornydragon** [comment]
Just done a quick Google search as well, it appears I'm not the only one experiencing this issue: https://www.reddit.com/r/voidlinux/comments/ltqi3b/issues_verifying_the_new_20210218_current_release/

**Comment by ericonr** [comment]
Hi! Can you explain the solution you found? It might help others who come across this issue.
