### ISSUE TITLE
make SDDM use keyboard layout specified in rc.conf

### ISSUE THREAD

**Issue by paulhersch** [void-linux/void-packages#30186]
* package:  
  *affected package(s) including the version*: ``sddm-0.19.0_3``

### Expected behavior
SDDM uses the de-latin1 keyboard specified in rc.conf

### Actual behavior
SDDM uses the standard american layout and I mistype my password at least once

### Steps to reproduce the behavior
Use unconfigured sddm, set it as login manager and start the system i guess

Sadly I am not that good with shell scripting so I can't contribute to the runscript

**Comment by Veganizer** [comment]
Hello paulhersch,

this is a common problem with sddm. ArchLinux got the same problem.
My suggestion is to edit "/usr/share/sddm/scripts/Xsetup" as a workaround:

```bash
#!/bin/sh
# Xsetup - run as root before the login dialog appears
setxkbmap de
```

**Comment by paulhersch** [comment]
Ok will do that, thanks for the workaround!
