### ISSUE TITLE
Fails to boot live USB to install Void Linux

### ISSUE THREAD

**Issue by henrikstroem** [void-linux/void-packages#30181]
The base image (also tried with several of the flavor images) cannot boot the live image for installation on Lenovo Thinkpad T450. The machine can boot other Linux distros: Alpine, PopOS, Ubuntu, Artix, Arch, and anything else I have tried.

### Expected behavior
Pressing F12 at boot shows the boot menu; selecting the USB stick should boot the live image.

### Actual behavior
- After selecting the USB stick in the boot menu, the screen goes black, and the Lenovo logo appears (as when the power comes on).
- After a few seconds, the screen goes black again, and then the Lenovo logo reappears.
- After a few seconds, the grub menu of the previously installed OS appears.

### Steps to reproduce the behavior
- Download image https://alpha.de.repo.voidlinux.org/live/current/void-live-x86_64-20210218.iso
- Follow instructions to write USB: dd bs=4M if=void-live-x86_64-20210218.iso of=/dev/sdb
- Insert USB into Lenovo T450 and turn on
- Press F12 to enter the boot menu
- Select the USB stick

**Comment by ericonr** [comment]
Is it a UEFI machine? I think we don't work with strict UEFI systems (or something to that effect).

**Comment by henrikstroem** [comment]
The machine supports the following modes:

- UEFI
- UEFI + Legacy
- Legacy Only

Based on the comment from @ericonr I tried to set the machine to Legacy Only - that solved the problem.
Thanks a lot.
