### ISSUE TITLE
Just want to clarify some things for beginner.

### ISSUE THREAD

**Issue by p0txky** [void-linux/void-packages#30187]
You only need to ./xbps-src binary-bootstrap once and use ./xbps-src bootstrap-update after pulling things?

when removing pkg that has not been installed, just rm the sources and binpkg in hostdir?

when updating you need to remove it from repo and ./xbps-src pkg <package> and install again?

**Comment by ericonr** [comment]
You usually only need `binary-bootstrap`, the build system will update the masterdir when you try to build something.

> when removing pkg that has not been installed, just rm the sources and binpkg in hostdir?

You don't need to remove sources, only if you want to clear space. Removing binpkg is reasonable.

> when updating you need to remove it from repo and ./xbps-src pkg and install again?

No, if the `version` or `revision` has changed, the new package will be created and can be installed with `xi -u` (from `xtools`), no manual steps.
