### ISSUE TITLE
Package that install files into non-standard location

### ISSUE THREAD

**Issue by sgn** [void-linux/void-packages#30183]
- [ ] Maelstrom-3.0.7_1	/usr/games
- [ ] ardour-6.6_1	/usr/etc
- [ ] atf-0.21_4	/usr/tests
- [ ] avr-binutils-2.32_1	/usr/x86_64-unknown-linux-gnu
- [ ] avr-libc-2.0.0_4	/usr/avr
- [ ] beancount-2.3.0_2	/usr/elisp
- [ ] bftpd-5.6_1	/usr/etc
- [ ] bftpd-5.6_1	/usr/var
- [ ] gromit-mpx-1.3.1_1	/usr/etc
- [ ] inspircd-3.8.1_2	/usr/apparmor
- [ ] ispc-1.15.0_1	/usr/examples
- [x] jwm-settings-manager-2.1.5_1	/usr/usr
- [ ] kyua-tests-0.13_2	/usr/tests
- [ ] lcov-1.15_1	/usr/etc
- [ ] lltag-0.14.6_3	/usr/etc
- [ ] msp430-toolchain-3.05.00.00_2	/usr/msp430
- [ ] netrek-client-cow-3.3.2_1	/usr/games
- [ ] nm-tray-0.4.3_2	/usr/etc
- [ ] papis-0.11.1_1	/usr/etc
- [ ] python3-vispy-0.6.1_4	/usr/etc
- [ ] rofs-filtered-1.7_2	/usr/etc
- [ ] rygel-0.40.0_1	/usr/none
- [ ] spectrwm-3.4.1_2	/usr/etc
- [ ] thc-hydra-9.1_2	/usr/etc
- [ ] vimpager-2.06_3	/usr/etc
- [ ] wmii-3.9.2_6	/usr/etc
- [ ] wpgtk-6.1.3_2	/usr/etc
- [ ] xbps-tests-0.59.1_5	/usr/tests
- [ ] inspircd-3.8.1_2        /usr/logrotate
- [ ] EmptyEpsilon-2020.11.23_3       /usr/script_reference.html

**Comment by ericonr** [comment]
I think `avr-libc` and `msp430` are fine, since they are toolchains? What do you think?

**Comment by SadieCat** [comment]
>inspircd-3.8.1_2 /usr/apparmor

If you update InspIRCd to the latest release it should not install files to weird locations anymore.
