### ISSUE TITLE
Icecat always in remove action while updating

### ISSUE THREAD

**Issue by free-tinker** [void-linux/void-packages#30199]
### System

* xuname:  
[~]-> xbps-uhelper arch
x86_64
  *output of ``xuname`` (part of xtools)*
* package:  icecat-78.6.1_1
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
Not being removed.
### Actual behavior
When I updating with xbps-install -Syu, icecat action state always in remove.
So I have to reinstall the icecat package after update.

**Comment by sgn** [comment]
Yes, we removed `icecat`. See 80815e7ec8

**Comment by Chocimier** [comment]
Just like sgn said. If you want icecat, use build from authors: https://www.gnu.org/software/gnuzilla/#downloads .
