### ISSUE TITLE
Gnome 40 sleep issue and zoomed in screen

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#30196]
### Expected behavior
Laptop should wake from suspend.
Screen should scale to monitor resolution.

### Actual behavior
Trying to wake from suspend does nothing. A force power off is necessary.
On a 1440p monitor the screen is zoomed in to a 1080p area, cutting off part of the screen. 

### Steps to reproduce the behavior
Update to Gnome 40, try to suspend machine. Plug into a 1440p monitor.

I'm using musl if that matters.

Thanks!

**Comment by Gottox** [comment]
Cannot reproduce. What's the output of xuname? Also could you provide some information on the hardware? Especially which processor and graphics card.

**Comment by randomusero8** [comment]
Void 5.11.13_1 x86_64-musl GenuineIntel uptodate rrnFFF. Its a dell laptop with a i7 8565u and intel integrated graphics. Thanks!

**Comment by notthewave** [comment]
Same Problem
Thinkpad x230t 
- Intel® Core™ i5-3320M CPU @ 2.60GHz × 4 
- Intel® HD Graphics 4000 (IVB GT2)

I found that the monitor problem does not occur if the bigger Display is recognized first (on display-server startup).
My monitor seems to display a 1366x768 (size of the latop display) cutout of the actual resolution (1680x1050).

As far as the wake from sleep problem goes, if I switch to tty7 I get back to `gdm` but it seems to be a fresh session (no blurred wallpaper)

**Comment by ergpopler** [comment]
Same issue on Thinkpad X230, musl, again.
I have no zooming problems -- just the sleeping problem. 
i5 3320M CPU
Intel HD graphics 4000

**Comment by sreehax** [comment]
same on thinkpad x1 carbon gen7 (latest packages, musl)

**Comment by ericonr** [comment]
Anyone here who could open an issue with upstream? I suspect this would go under either `gnome-shell` or `mutter`, but that's just a guess.

**Comment by ergpopler** [comment]
Reported to Gnome upstream.

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4148

**Comment by notthewave** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3941
maybe related issue for zoomed in secondary monitor

**Comment by randomusero8** [comment]
Has anyone found any workarounds? The linked issues don't seem to have gone anywhere.
