### ISSUE TITLE
Bluetooth Turned on After Reboot

### ISSUE THREAD

**Issue by free-tinker** [void-linux/void-packages#30247]
### System

* xuname:  
x86_64
  *output of ``xuname`` (part of xtools)*
* package:  
bluez-5.58_1
gnome-bluetooth-3.34.5_1
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
Bluetooth off after reboot.
### Actual behavior
Bluetooth turned on after reboot while rfkill softblock the bluetooth and AutoEnable in /etc/bluetooth/main.conf false.
But with those condition, when i turned it off, it can't turned back on.

**Comment by Anachron** [comment]
Well did you enable the bluetoothd service?

**Comment by free-tinker** [comment]
I did

**Comment by free-tinker** [comment]
Solved with local script
