### ISSUE TITLE
Login at TTY2

### ISSUE THREAD

**Issue by free-tinker** [void-linux/void-packages#30258]
### System

* xuname:
x86_64
  *output of ``xuname`` (part of xtools)*
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
TTY1 still logged in and in gnome wayland session.
### Actual behavior
I was login at TTY1 through gdm. After that, I move to TTY2 cli login session. But, when I switch back to TTY1, it turned to cli mode, logged out and written "bgscan simple : Failed to enable signal strength monitoring".

**Comment by paper42** [comment]
gdm uses tty7 and starts its session on tty8 by default, try looking there

**Comment by free-tinker** [comment]
Thank you. It is there.
may I close this ?
