### ISSUE TITLE
Package Request: Lightcord 0.1.5

### ISSUE THREAD

**Issue by gorkawien** [void-linux/void-packages#30290]
Lightcord is a simple and customizable client for Discord. It includes BandagedBD, Glasstron and a discord.js-like api.
Source: https://github.com/Lightcord/Lightcord
License:MIT
Pro: An improved free Discord client.

**Comment by Anachron** [comment]
Don't we love all these electron packages? :smile:

**Comment by Vapourium** [comment]
You should probably close this, it redistributes discord's source code.

**Comment by q66** [comment]
uses ancient electron, violates discord ToS
