### ISSUE TITLE
some basic need

### ISSUE THREAD

**Issue by deepaknegilachu** [void-linux/void-packages#30342]
am using void on my laptop there is no service for brightness restore at boot ( brillo not working) , dbus does not work in xorg automatically i have to modify xinitrc or lightdm for dbus ( which is so tideous ) , if i use lxdm then xorg  launching with dbus but polkit agent wont work ! kindly resolve this comman issues ! i have  amd radeon cpu /gpu : thanks for making VoidLinux

**Comment by FollieHiyuki** [comment]
Could you verify these?
1. Is your user in `video` group?
2. `brillo` works for me here. But you need to store the brightness value first (`-O` option) then use `-I` to restore it. There is no need for a service though you can easily run this at boot manually.
3. "dbus does not work in xorg automatically" --> Have you enabled the dbus service? Not really necessary with some xorg WM/DE but you can always use `dbus-launch` or `dbus-run-session` as normal user.
4. "polkit agent won't work" --> Have you installed 1 of the agents from the repo?

**Comment by deepaknegilachu** [comment]
yes am on video group
sorry i didn,t check brillo man but i got a runit service for that from someone github it save brightness at var and restore at boot 

yes i use mate-polkit and its working with 
"if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS";
then
	eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi"

if i put this line in .xinitrc for startx or /etc/lightdm/xsession file for lightdm

without above line am not able to mount usb and andriod device in pcmanfm 

i think polkit agent depend upon dbus also

thanks for taking time !
