### ISSUE TITLE
docker: "docker-init": executable file not found in $PATH

### ISSUE THREAD

**Issue by pudiva** [void-linux/void-packages#30341]
### System

* xuname:  
  *Void 5.11.13_1 x86_64 GenuineIntel uptodate rrrrmdFFFF*
* package:  
  *docker-20.10.5_2*

### Expected behavior

stuff working

### Actual behavior

```
$ docker-compose run --name wscef wscef
WARNING: The TZ variable is not set. Defaulting to a blank string.
Creating network "wscef-docker_default" with the default driver
Creating wscef-docker_wscef_run ... done
Error response from daemon: exec: "docker-init": executable file not found in $PATH
```

### Steps to reproduce the behavior

Follow steps at:  
https://github.com/farribeiro/wscef-docker

### My observations

* docker pkg template used to mention `docker-init`, but it no longer does after  9b3c344a79a1930062ec7a0df22882f3a04127ec was merged
* `xlocate docker-init` and `grep -R docker-init .` on my local void-packages repo, both returned nothing
* reinstalling docker and docker-cli didn't help

**Comment by pudiva** [comment]
@thypon @ahesford, @endigma and @radiden :point_up:
and also: are the maintainers autistic? I hope it's not biggotry :point_down:
> Packaged with Autism :)

https://pwa.cya.cx/

**Comment by endigma** [comment]
> @thypon @ahesford, @endigma and @radiden 
> and also: are the maintainers autistic? I hope it's not biggotry 
> 
> > Packaged with Autism :)
> 
> https://pwa.cya.cx/

Don't worry, diagnosed here making a little fun.

**Comment by pudiva** [comment]
> > and also: are the maintainers autistic? I hope it's not biggotry
> 
> Don't worry, diagnosed here making a little fun. We use the silly site for a few things, nothing hateful at all.

cool :)

**Comment by pudiva** [comment]
I can confirm that reverting 9b3c344a79a1930062ec7a0df22882f3a04127ec brings back `docker-init` and fix (this) issue.

**Comment by ericonr** [comment]
https://github.com/archlinux/svntogit-community/blob/992efbc7d9d12e1db0e430e95e226c49e5c39a06/trunk/PKGBUILD#L105 and https://git.alpinelinux.org/aports/tree/community/docker/APKBUILD#n128 use `tini-static` as the source for `docker-init`, it seems.

**Comment by ericonr** [comment]
So it would seem we are missing the part where do that manually, which probably used to be done by some manner of script in the previous version of the packages.

**Comment by endigma** [comment]
I don't have this issue, could you send more details about your error case? docker-init isn't a command provided by docker-cli. If you need this binary, I suggest implementing it as a separate package. We don't pull in tini-static or tini at all because this isn't really necessary for most people.

**Comment by thypon** [comment]
> @thypon @ahesford, @endigma and @radiden :point_up:
> 
> and also: are the maintainers autistic? I hope it's not biggotry :point_down:
> 
> > Packaged with Autism :)
> 
> 
> 
> https://pwa.cya.cx/

Seems it was took over =)

**Comment by endigma** [comment]
> Seems it was took over =)
Not sure what you mean, we still actively maintain the package. I just disagree with the adding of docker-init, so I haven't done it myself.

**Comment by thypon** [comment]
> > Seems it was took over =)

I was cited, seems like I'm not the maintainer of this package anymore from the last change.

**Comment by endigma** [comment]
Oh, my mistake, I just noticed after I posted.

**Comment by ericonr** [comment]
The old `docker` package provided `docker-init`, so this is technically a regression.

**Comment by thypon** [comment]
Maybe a diff pass on package files would help in managing these kind of regressions.

**Comment by endigma** [comment]
Although technically a regression, adding a dependency for feature parity's sake seems excessive to me. It's not like we already have the tini binary and aren't installing it. This could easily be a docker-tini package with the same amount of effort.

**Comment by thypon** [comment]
If breaking changes are introduced for some users, it is a good practice to add an install message on how to install the missing part.

**Comment by endigma** [comment]
I can't actively participate in this discussion any further, as its approaching 4 am here, but whatever is decided as the optimal route I'll implement tomorrow if not done already.

**Comment by thypon** [comment]
🥵 tini in a separated package
🥶 docker install message
🤢 tini in docker main package

**Comment by ahesford** [comment]
The right course of action is to add a package for tini that restores the missing functionality and have the `docker` meta pull in the new package as a dependency.

It was bad to break people's workflows with this change and an oversight on my part to merge without tini.

**Comment by ahesford** [comment]
@thypon, please accept my apology for missing the maintainer change among the restructuring of the package. I hope you will reclaim the packages if you wish.

@endigma and @radiden, in the future, please seek approval from existing maintainers before you replace their names.

**Comment by pudiva** [comment]
Good afternoon, voiders.

After I reverted  9b3c344a79a1930062ec7a0df22882f3a04127ec locally, I started getting:

```
$ docker start -i -a wscef
setpriv: libcap-ng is too old for "all" caps
```

I didn't investigate much, but might be related to #26188 and me updating recently linux to 5.11?

Also tried to update docker to upstream and copy just the `docker-init` binary from my reverted build, but still got the error.

Maybe @ericonr knows what to do?

**Comment by ericonr** [comment]
That looks like something wrong with `setpriv` from inside the container, I think...

Our setcaps doesn't even have that error anymore.

**Comment by sgn** [comment]
@thypon @ahesford Sorry, it was me who removed your name from maintainer field. At the time, I reworked `docker`, I didn't know your real name and email. Please accept my apology.

For the `docker-init`, I think we can reintroduce it as a separated package and let's `docker` depends on it.
It's a tiny binary, we ain't aimed to be a minimalist distro, let's not worry about space.

**Comment by endigma** [comment]
> @endigma and @radiden, in the future, please seek approval from existing maintainers before you replace their names.

Understood, we took over maintainer because the package was almost a year and several versions out of date, and required being totally rewritten. Hope the previous maintainer doesn't mind.

If the conclusion is that tini should be included, I'll implement that today.

**Comment by thypon** [comment]
```

**Comment by thypon** [comment]
```
commit 9c3de52a7a584750ebb2be2a5572d944725a1379
Author: Érico Rolim <erico.erc@gmail.com>
Date:   Sat Nov 14 14:11:30 2020 -0300

    srcpkgs/: remove go from hostmakedepends for packages with
    build_style=go.

commit a033077175fd60900340b1fe7a5194a381befb82
Author: Andrea Brancaleoni <abc@pompel.me>
Date:   Fri Feb 5 23:04:48 2021 +0000

    docker: update to 19.03.15.
```

Over an year in non faster-than-light traveling humans is a couple of months. I don't care about maintaining; it's completely ok for me if someone wants to keep updating docker. Just please stop acting like somebody is attacking you personally.
It's just a bug, maintaining free software is just an unpaid responsibility.

**Comment by endigma** [comment]
I didn't mean to act attacked, I don't feel that way. We'll fix the issue today and push a new package docker-init/tini and add it as a meta depend to docker. Should it be docker-tini or docker-init?

**Comment by ahesford** [comment]
The package should be called `tini` to confirm to our naming conventions.

**Comment by endigma** [comment]
> The package should be called `tini` to confirm to our naming conventions.

@ahesford 
Isn't this a bit misleading? tini does not just exist to be named `docker-init`, if someone wished to package tini for use on the host in the future, this would be a naming conflict.

**Comment by pudiva** [comment]
> That looks like something wrong with `setpriv` from inside the container, I think...
> 
> Our `setpriv` doesn't even have that error anymore.
> 
> But yes, it would be caused by the kernel version.

@ericonr you were, right, I updated the debian version on the Dockerfile and it now works with the reverted pkg. Thanks for the insight.

**Comment by endigma** [comment]
For now I'm going to have the tini package install `tini` and `tini-static`, as well as `docker-init` (tini-static). I'm not sure if a symlink will work, but I'll test.

**Comment by Skaytacium** [comment]
Any updates on this? still don't see a tini/docker-init package.

**Comment by endigma** [comment]
We made the additions in a PR, still no merge. They haven't told us why.

**Comment by Skaytacium** [comment]
Yep, I did see that. Interesting, this is quite a small change, and its just been on hold for 2 weeks.

**Comment by pudiva** [comment]
I guess this can be closed now

**Comment by hholst80** [comment]
Please re-open this.  I cannot understand how this could be allowed to pass through.  docker-init must be shipped with the core docker package.  If that is via direct shipping it or a required dependency is immaterial but it must work out of the box to pass --init to docker run otherwise the installation is broken.

Ping @pudiva

**Comment by classabbyamp** [comment]
docker does depend on tini:
```
$ xbps-query -Rx docker
docker-cli>=24.0.2_1
moby>=0
tini>=0
```

**Comment by endigma** [comment]
@hholst80 If you are experiencing some sort of issue here it would be best not to necro, this is 2 years closed now. You need to install the metapackage if you want all the components, docker is not shipped monolithically anymore I think due to the usefulness of remote docker daemons.
