### ISSUE TITLE
mako problems on systems without elogind

### ISSUE THREAD

**Issue by anubhavkini** [void-linux/void-packages#30428]
### System

* xuname:  
  `Void 5.11.15_1 x86_64 GenuineIntel notuptodate rrFFFF`
* package:  
  `mako-1.4.1_1`

### Expected behavior
`makoctl reload` should reload the mako config file.
### Actual behavior
```
$ makoctl reload
/bin/makoctl: 19: busctl: not found
```
### Steps to reproduce the behavior
* Install `mako` without `elogind` and run it.
* Run `makoctl reload`.
### Other
`mako` can now be built with [basu](https://github.com/emersion/basu) instead of  elogind
https://github.com/emersion/mako/commit/805663cc76e0a58dc67c60b0df43170d5e489615
maybe we can have `mako-basu` for systems without elogind

**Comment by ericonr** [comment]
It would be better to directly package `basu` and use it by default, IMO. Unless the `elogind` integration brings something to the table.

**Comment by st3r4g** [comment]
> Unless the `elogind` integration brings something to the table.

From the README:

> systemd, elogind or basu (for the sd-bus library)

so no

**Comment by FollieHiyuki** [comment]
I already package `basu`, but we have to wait for the next release of `mako`
```
# Template file for 'basu'
pkgname=basu
version=0.2.0
revision=1
build_style=meson
configure_args="-Dwerror=false"
hostmakedepends="gperf"
short_desc="Library for sd-bus extracted from systemd"
maintainer=""
license="LGPL-2.1-or-later"
homepage="https://github.com/emersion/basu"
distfiles="https://github.com/emersion/basu/releases/download/v${version}/basu-${version}.tar.gz"
checksum=e2fda9b69fc6c4530173fcf8db94c29aa5f3ed932d948cc6a31892623cde5e4b

basu-devel_package() {
        short_desc+=" - development files"
        depends="${pkgname}-${version}_${revision}"
        pkg_install() {
                vmove usr/include
                vmove usr/lib/pkgconfig
                vmove "usr/lib/*.so"
        }
}
```

**Comment by itsanubhavkini** [comment]
New [release](https://github.com/emersion/mako/releases/tag/v1.5) is out.
