### ISSUE TITLE
Picard Musicbrainz crash session under wayland

### ISSUE THREAD

**Issue by alice-OooO** [void-linux/void-packages#30425]
### System

* xuname:  
  *Void 5.11.15_1 x86_64-musl GenuineIntel uptodate rF*
* package:  
  *picard-2.5_2*

### Expected behavior

Musicbrainz launches without issues

### Actual behavior

Under wayland the app don't work, the current session crash, under Xorg the app works.
It seems to me this issues appeared after updating to Gnome 40.

After logging back into a session a core.XXXXX file is available but I don't know how to get information from it.
`$ file core.XXXXX` indicate that the file is created by /usr/bin/Xwayland

**Comment by paper42** [comment]
I can not reproduce this bug on GNOME 40 with glibc. What is `$QT_QPA_PLATFORM` set to? According to your description, picard is using xorg (XWayland) instead of Wayland, do you want that?

**Comment by alice-OooO** [comment]
Okay, I've found the problem... I don't understand why the package qt5-wayland was not installed on my system ?! everything was working before the day I upgraded to gnome 40, sorry sometimes answers are so easy that we don't even think to it.

**Comment by paper42** [comment]
@alice-OooO GNOME 40 is unlikely the cause, but there was a big xwayland update, so it's possible it is a regression. Could you try downgrading xwayland and testing it? Maybe it's an upstream bug.

**Comment by alice-OooO** [comment]
I don't have any older version on /var/cache/xbps and I don't know how to downgrade in this situation :/
