### ISSUE TITLE
cairo-dock won't pull the recently changed dependencies

### ISSUE THREAD

**Issue by eth0OS** [void-linux/void-packages#30456]
### System

* xuname:  Void 5.11.15_1 x86_64 AuthenticAMD notuptodate rrrmDFFFFFFFFF
  *output of ``xuname`` (part of xtools)*
* package:  cairo-dock-plugins-3.4.1_14
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior

Since the commit 8d643c6 that replaced the dependency of the cairo-dock-plugins package from vte290 to vte3, my system is unable to update, giving the following error "cairo-dock-plugins-3.4.1_14: broken, unresolvable shlib `libvte2_90.so.9'".

I´ve tried removing cairo-dock-plugins and vte290 package, I already have vte3-0.64.0_1 and vte3-devel-0.64.0_1 installed. But everytime I try to install cairo-dock-plugins package it tries to pull vte290 again.

I believe it is due the fact this last commit didn't bumped the revision number of the template, so the package is not getting compiled with the new dependencies. 

### Actual behavior

The package still expects vte290 to be installed instead of vte3.

### Steps to reproduce the behavior

Try update the system with cairo-dock-plugins installed, it will give an error message about vte290, or try to install cairo-dock-plugins, it will ask to pull vte290 eventhough it got removed from the deps list.

**Comment by ericonr** [comment]
Yes. that is exactly the case, thanks for the investigation!
