### ISSUE TITLE
[nm-tray] Icon not included at compile?

### ISSUE THREAD

**Issue by tooManyArguments** [void-linux/void-packages#30453]
### System

* xuname:  
  *Void 5.11.16_1 x86_64 GenuineIntel uptodate rrrmFFFF
* package:  
  *affected package(s) including the version*: nm-tray-0.4.3_2

### Expected behavior
Icon is visible
### Actual behavior
There is no icon
### Steps to reproduce the behavior
launch nm-tray in any way.
Output:
```
[kroot@void build]$ nm-tray
QSystemTrayIcon::setVisible: No Icon set
^C
```

**Comment by tooManyArguments** [comment]
No idea why, but now the icon is suddenly there, might have been solved by some other package i installed. Version is still the same:
nm-tray-0.4.3_2

**Comment by ericonr** [comment]
You probably installed some icon package, the package itself doesn't seem to contain any icons.
