### ISSUE TITLE
Package Request : libcudart.so.11.0

### ISSUE THREAD

**Issue by knassar702** [void-linux/void-packages#30466]
```
$ sudo xbps-query -Rs libcudart
no output
```

**Comment by ericonr** [comment]
Please link the homepage of the project, explain a bit what it does, and explain why you need it.

And just as a tip, no need to use `sudo` to run `xbps-query`.

**Comment by Veganizer** [comment]
Seems to belong to the cuda-toolkit, which isn't opensource. It is a precompiled binary under the cutom nvidia license...

**Comment by knassar702** [comment]
hello @ericonr

Home: https://helpmanual.io/man7/libcudart/ 
Download : https://developer.nvidia.com/cuda-92-download-archive

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/issues/20077
