### ISSUE TITLE
Go back to vendored LLVM in Julia

### ISSUE THREAD

**Issue by ahesford** [void-linux/void-packages#30490]
Even though I lobbied for building Julia 1.5 against our system LLVM package, Julia 1.6 is now broken on i686 because it requires patches to LLVM that we don't provide. Furthermore, when Void moves to LLVM 12, Julia will be the only dependant of LLVM 11; there's no value in keeping a separate system package just to support Julia. At this point, switching back to vendored LLVM will ease the maintenance burden and restore i686 support.

@non-Jedi, would you mind moving the Julia package to vendored LLVM?

**Comment by non-Jedi** [comment]
Sure thing. I'll make sure to make the switch back to vendored llvm when I get around to packaging version  1.6.1.

**Comment by q66** [comment]
considering this is holding up switching to LLVM 12, sooner would be better

**Comment by non-Jedi** [comment]
I'll get to it today.
