### ISSUE TITLE
ERROR: Failed to mount / private (Invalid argument)

### ISSUE THREAD

**Issue by kyx0r** [void-linux/void-packages#30496]
Hi I am trying to build a package in void linux chroot (because I don't use void as my main system but I need it to test packages) 

First I had problems with my kenel not supporting the for the ```unshare``` command
CONFIG_NAMESPACES
CONFIG_IPC_NS
CONFIG_UTS_NS
CONFIG_USER_NS

After fixing that, the error became something saying (permission denied)

Then I run these commands:

```
chown root:<xbuilder> $(which xbps-uchroot)
chmod 4750 $(which xbps-uchroot)
usermod -a -G <xbuilder> root
```

And now the error is 
ERROR: Failed to mount / private (Invalid argument)

Please help me, I don't care about user permissions I run everything as root. Permissions are bloat, that I don't care about. I just want to get stuff done and move on with my day. Please stop making this harder than it needs to be and make the root do everything I need, without all this user group bullshit. 

If you can't fix your xbps-src script, then just take a look at this issue here: I need someone to test this bug in the package

https://github.com/kiss-community/repo-community/issues/331

Thank you very much.

**Comment by kyx0r** [comment]
Here is a detailed log of what is going on
[ERROR.LOG](https://github.com/void-linux/void-packages/files/6372528/ERROR.LOG)

**Comment by kyx0r** [comment]
Here is another one. Remember that I run void in chroot so that may be the cause of this problem. 

[x.LOG](https://github.com/void-linux/void-packages/files/6372538/x.LOG)

**Comment by sgn** [comment]
> I don't care about user permissions I run everything as root. Permissions are bloat, that I don't care about.
I don't care about KISS Linux, and I don't care if my system is bloat. Sorry.

**Comment by kyx0r** [comment]
@sgn You don't care that your webkit2gtk package for musl is bugged??? We are using the same patch-set. Did you even read what that issue said?? I tested the latest binary builds of webkit today and they are bugged, I am trying to get the void package to build so that I can further solve the damn bug! Wake up! I wanted to see if the bug persists on the latest git commit here in void linux. But this xbps-src script does not work for me (in chroot?), which is a road block. This is the first time I ever tried using this script to build something from source and I have a clear problem in this setup. So you are not even going to bother to look if I did anything wrong when trying to use this script, ok but now you don't care whether your webkit package is bugged or not? On what jurisdiction are you closing the issue, if you are not competent to take a look at it maybe someone else from maintainers will.

**Comment by kyx0r** [comment]
@q66 I would like to bring this to your attention. You seem to be the maintainer of the webkit, since I am physically blocked from being able to compile void's stuff myself, can you please look into this problem? 

Thanks,

**Comment by Chocimier** [comment]
xbps-src creates chroot so it won't when used inside chroot. Running as root won't work either.
Also RTF README, it tells how to use it outside Void.

**Comment by q66** [comment]
the issue was closed because you using xbps-src wrong is not our problem

i suggest you stop being an entitled brat

**Comment by kyx0r** [comment]
Funny how you are more concearned about me being entitled brat more than the series of technical problems and limitations that I have presented you with. Alas I conclude that xbps-src is not a very user freedom respecting software, as I can't do the things I expect to work normally with any kind of software. BTW, I did read the README and followed it step by step, however it still did not work and gave me some certificate verification error on download, which I am not even going to bother with (and no that was not because my clock is out of sync). 

If you ever get this thing working in TempleOS let me know. Thanks :)

**Comment by ericonr** [comment]
Thanks for the (indirect) bug report regarding webkit, but otherwise the discussion seems to have devolved. I suggest approaching projects with less entitlement, next time; maintainers are also people.

You are free to fix `xbps-src` to work however you wish it, and you don't even have to send the changes back to us. BSD-2-Clause is not a restrictive license.

**Comment by sgn** [comment]
Work for me! I guess it works ootb for me because I'm using a bloated-musl-installation?
![1](https://user-images.githubusercontent.com/42673067/116116504-6bb9ea80-a6e5-11eb-9229-b5978a2ea9ea.png)
![2](https://user-images.githubusercontent.com/42673067/116116513-6f4d7180-a6e5-11eb-9f8c-44f2518cb733.png)

**Comment by q66** [comment]
FWIW, the webkit bug is long known and there were various efforts to fix it over the years, with none of them getting it quite right (including my most recent attempt)

but, on the positive side - i now have a patch that fixes it fully (no thanks to you though - i'm currently deploying webkit for someone and coincidentally i was tracking down the same bug), so i'll push it into void once i've cleaned it up

**Comment by kyx0r** [comment]
That's great news! Thank you!
