### ISSUE TITLE
Failed to download 'tiff-4.2.0_2': Not Found

### ISSUE THREAD

**Issue by HudsonLarge** [void-linux/void-packages#30498]
ERROR: [trans] failed to download 'tiff-4.2.0_2' package from 'https://alpha.de.repo.voidlinux.org/current/musl': Not Found
Transaction failed! see above for errors. 

Issue occurred on a fresh install with musl when attempting to install firefox. Also occurs when attempting to install Chromium or any other graphical web browser. Issue occurs reguardless of flags applied to xbps. I assume tiff-4.2.0_2 simply needs to be readded to the repo.

**Comment by ericonr** [comment]
You need to update your repodata, the package has been updated.

`sudo xbps-install -S tiff`

**Comment by HudsonLarge** [comment]
Thank you for your assistance.
