### ISSUE TITLE
No sound on xps 17 9700 - need new kernel flags?

### ISSUE THREAD

**Issue by gronka** [void-linux/void-packages#30508]
### System
Void 5.11.16_1 x86_64 GenuineIntel uptodate rrFF

sof-firmware-1.7_1
pulseaudio-14.2_3

### Issue
I have no sound on this laptop. pavucontrol only shows DummyOutput. Previously to get sound users had to install a newer kernel with new pulseaudio and sof-firmware package.

I recently created an issue in regards to this and it was suggested the relevant kernel flags need to be used:
https://github.com/maaarghk/soundwire-dkms/issues/5

The very last comment here lists what may be the correct flags. I haven't tested them, but I verified they are missing from my /proc/config.gz:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976791#35

```
$ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
    Default ALSA Output (currently PulseAudio Sound Server)
hdmi:CARD=NVidia,DEV=0
    HDA NVidia, HDMI 0
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=1
    HDA NVidia, HDMI 1
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=2
    HDA NVidia, HDMI 2
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=3
    HDA NVidia, HDMI 3
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=4
    HDA NVidia, HDMI 4
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=5
    HDA NVidia, HDMI 5
    HDMI Audio Output
hdmi:CARD=NVidia,DEV=6
    HDA NVidia, HDMI 6
    HDMI Audio Output
```

**Comment by gronka** [comment]
these appear to be the required settings

CONFIG_SND_SOC_INTEL_USER_FRIENDLY_LONG_NAMES=y
CONFIG_SND_SOC_INTEL_SOUNDWIRE_SOF_MACH=m
CONFIG_SND_SOC_RT1308=m

if there's a tutorial for building a custom kernel on void i'll try it myself; I'm on an encrypted disk so I don't care to explore too much on my own

**Comment by ericonr** [comment]
We have `CONFIG_SND_SOC_RT1308_SDW=m` in our configs already, but not `CONFIG_SND_SOC_RT1308` by itself.

`CONFIG_SND_SOC_INTEL_SOUNDWIRE_SOF_MACH` needs to be enabled and I think it will "unlock" `CONFIG_SND_SOC_RT1308`.

`CONFIG_SND_SOC_INTEL_USER_FRIENDLY_LONG_NAMES` is just a user experience thing, and I don't think we should enable it.

```
config SND_SOC_INTEL_USER_FRIENDLY_LONG_NAMES
	bool "Use more user friendly long card names"
	help
	  Some drivers report the I/O configuration to userspace through the
	  soundcard's long card name in the control user space AP. An unfortunate
	  side effect is that this long name may also be used by the GUI,
	  confusing users with information they don't need.
	  This option prevents the long name from being modified, and the I/O
	  configuration will be provided through a different component interface.
	  Select Y if userspace like UCM (Use Case Manager) uses the component
	  interface.
	  If unsure select N.
```

Re. how to build a kernel, just edit the config in `srcpkgs/linux5.12/files/x86_64-dotconfig`, `./xbps-src pkg -f linux5.12` and `xi -f linux5.12`.

**Comment by gronka** [comment]
@ericonr Thanks. I greatly appreciate how active you are on this github. Where did you get this nice description of that kernel option?

**Comment by ericonr** [comment]
:)

> Where did you get this nice description of that kernel option?

From `sound/soc/intel/boards/Kconfig` in the kernel source tree.

**Comment by gronka** [comment]
> Re. how to build a kernel, just edit the config in `srcpkgs/linux5.12/files/x86_64-dotconfig`, `./xbps-src pkg -f linux5.12` and `xi -f linux5.12`

1) When I try this, the changes do not propagate to `/proc/config.gz`. Sorry for being a noob - I think it's reinstalling 5.13 from the repos instead of from the local folder

2) How do I use multiple cores to compile?
