### ISSUE TITLE
Package request: poetry-core

### ISSUE THREAD

**Issue by kwshi** [void-linux/void-packages#30551]
Purpose: Support Python packages built using Poetry (via PEP 517).

The Python community is moving increasingly towards [Poetry](https://python-poetry.org/) as a de-facto project management/build tool (I have no stats to back this claim up, only speculation based on an increasing number of blog posts I have seen about Poetry, as well as my own pleasant experiences with it).  Together with [PEP 517](https://www.python.org/dev/peps/pep-0517/), this trend means that

- several existing Python packages are migrating from `setup.py`-based builds to PEP517+Poetry builds (e.g., see #29799),
- new Python projects are likely to be created from scratch using Poetry (and therefore built using Poetry as well).

Not supporting Poetry would mean that it will be difficult to upgrade certain Python projects that have migrated to Poetry (e.g. #29799) as well as new projects created with Poetry.  One popular example of such a library is [tomlkit](https://github.com/sdispater/tomlkit), which has 300+ stars on GitHub.

As far as I can tell, the existing Void packages repo does not yet support Poetry-based builds.  The _infrastructure_ is already in place: PEP517 build configurations are supported via `build_style="python3-pep517"`; the missing part is the Poetry _builder_ itself, namely [`poetry-core`](https://github.com/python-poetry/poetry-core), which is loaded by the PEP517 build runner when a project specifies Poetry as the build backend ([example](https://github.com/sdispater/tomlkit/blob/d34a1fe7494aac74e1f0ccdb993c4ee2f8e4f305/pyproject.toml#L67-L69)) and therefore needs to be present as a build-time dependency.

That means the only thing that needs to be done to support (a vast & popular collection of, and likely even more so in the coming years) Poetry-based Python packages is to add the `poetry-core` Python package.

Note that `poetry-core` is _not_ the same as the [Poetry CLI](https://github.com/python-poetry/poetry/), which is an interactive/user-friendly frontend to managing Poetry-based projects.  [Only `poetry-core`, which is a lightweight, zero-dependency library, _not_ the CLI, is needed for building via PEP517.](https://github.com/python-poetry/poetry-core#why-is-this-required)

**Comment by eli-schwartz** [comment]
The python3-pep517 build style just runs pip, see commit 2dff49c420b27baf6a6dce30891237b9485bfd81

PyPI release tarballs created with `poetry build -f sdist` should have a setup.py generated for compat purposes, which lets you use the more common setup.py build style; getting distfiles via github archives will not get you an sdist and therefore you won't have that setup.py either. You'll just have development sources.

On the flip side, sometimes upstreams don't include their testsuite in PyPI sdists (they should!) which may be a compelling argument to use github archives.

**Comment by kwshi** [comment]
Added in https://github.com/void-linux/void-packages/commit/0f451e9da9da17af4f3f49958b1bab52f4d078ac.
