### ISSUE TITLE
Proposed changes to community versions of JetBrains IDE

### ISSUE THREAD

**Issue by progrestian** [void-linux/void-packages#30577]
1. Community versions of JetBrains IDE (`intellij-idea-community-edition` and `pycharm-community`) are currently marked as nonfree, but their licenses are Apache-2.0, even in their template files. We should add them to the main repo.

2. The naming scheme is inconsistent. `pycharm-community` is already correct, but upstream called `intellij-idea-community-edition` simply as `intellij-community`. I don't know if xbps can handle a package name change or not, or even if the change is a good thing (scripts may break, etc.).

**Comment by Chocimier** [comment]
1. They are recompressed binaries, so being in nonfree is not unreasonable. If one want to change templates to build fully from source, and build will take acceptable time, I'm for moving to main repo.
2. Renaming is possible when necessary, but not that nice. It needs keeping transitional package of old name in repo long enough for everybody to update, then transitional package stays installed until one manually marks new package as explicitly installed and removes old one. Not worth it for "consistency between two packages" reason.

**Comment by Johnnynator** [comment]
A full source build of intellij 2 years ago was close.to insanity and gradle did still pull a ton of external binaries. The only feasible part would be to just build the native components from.source but not the java stuff.

**Comment by progrestian** [comment]
Ah, I see the reason why things are as it is now. I'll close the issue then.
