### ISSUE TITLE
virtualbox-ose-guest-6.1.18 fails compiling on kernel 5.11

### ISSUE THREAD

**Issue by rapha8l** [void-linux/void-packages#30591]
### System

* xuname:  
Void 5.10.32_1 x86_64 GenuineIntel uptodate rrrmFFFF

* package:  
virtualbox-ose-guest-dkms-6.1.18_3

Fails to compile
make.log attached

Thanks

[make.log](https://github.com/void-linux/void-packages/files/6404364/make.log)

**Comment by rapha8l** [comment]
Related : 
https://bugs.launchpad.net/ubuntu/+source/virtualbox/+bug/1915900

**Comment by ericonr** [comment]
Fixed in #30585, I hope. Feel free to reopen otherwise.

**Comment by rapha8l** [comment]
thanks !
