### ISSUE TITLE
Crystal 0.24 is outdated

### ISSUE THREAD

**Issue by TeddyDD** [void-linux/void-packages#306]
Crystal 0.25 has been released. It would be nice to have it in the repo :)
Ping @LVMBDV

**Comment by maxice8** [comment]
Not to sound like an asshole but:

- We know that, we have an version checking system so we can get updates

crystal  0.24.1 -> 0.24.2  https://crystal-lang.org/  
crystal  0.24.1 -> 0.25.0  2018-06-12                 https://crystal-lang.org/

- The best way to get an updated version is to do it yourself and push to the repo

**Comment by LVMBDV** [comment]
The package being outdated was mentioned in the [crystal gitter](https://gitter.im/crystal-lang/crystal) a couple days ago. I think @rocx might update the package soon, they tried but it needed more work than just upping the version numbers.

My void install died the night before a local CTF so I had to get something else up and running shortly so I switched to Debian. I was meaning to switch back but I became even busier after that event. I tried to set up a package dev workflow with containers but I couldn't get it to work smoothly either. I want to get back into it but I just don't have the time for the moment. Sorry.

**Comment by TeddyDD** [comment]
> The best way to get an updated version is to do it yourself and push to the repo 

I used to notify maintainer first but it seems not a thing in a Void. I can close this issue if you want @maxice8

> tried but it needed more work than just upping the version numbers

Yeah, it seems that bootstrap compiler is downloaded from Github now + probably other changes. I'll try to dig into it soon, busy af right now.

**Comment by notramo** [comment]
@maxice8 Why can't we use the official binary release? I tried to compile [tbrand/neph](https://github.com/tbrand/neph) with it (Crystal `0.25.1`), and it worked without problems.
At least it would be better to have the precompiled releases until compiling will work than having `0.24.1` which can't compile a lot of up-to-date Crystal projects, so it is nearly useless.
