### ISSUE TITLE
how to install proprietary  video codecs in vivaldi for view html5 video?

### ISSUE THREAD

**Issue by kloun** [void-linux/void-packages#30614]
subj. I use latest vivaldi  from repo and html 5 video don't play. eg  https://rutube.ru/video/328d6efbdf16df23c1a8b8de53479d10/

**Comment by FollieHiyuki** [comment]
https://help.vivaldi.com/desktop/media/html5-proprietary-media-on-linux/

This doesn't work?

**Comment by sincorchetes** [comment]
Good afternoon,

I recently installed Vivaldi 5.2* and It does not support privative codecs. What's wrong?

**Comment by sincorchetes** [comment]
I could solve copying 
```
sudo cp /usr/lib64/slack/libffmpeg.so /opt/vivaldi/lib
```
lol
