### ISSUE TITLE
No midi music playback in Doomretro

### ISSUE THREAD

**Issue by josephreynolds1** [void-linux/void-packages#30635]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
Void 5.11.16_1 x86_64 GenuineIntel uptodate rFFFFF

* package:  
  *affected package(s) including the version*: 
doomretro-4.0.9_1
fluidsynth-2.2.0_1
soundfont-fluid-3.1_4
alsa-lib-1.2.4_2
SDL2_mixer-2.0.4_3

### Expected behavior

Midi music plays in game

### Actual behavior

Midi music in game is not playing.

```
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 1481.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
Note: Illegal Audio-MPEG-Header 0x00000000 at offset 25926.
Note: Trying to resync...
Note: Hit end of (available) data during resync.
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8545:(snd_pcm_recover) underrun occurred
```

### Steps to reproduce the behavior

Install doomretro package, install fluidsynth and soundfont-fluid

set soundfont in profile

SDL_SOUNDFONTS=/usr/share/soundfonts/FluidR3_GM.sf2

Play game doomretro doom.wad

**Comment by ericonr** [comment]
@benalb any idea?

**Comment by benalb** [comment]
It's a known  [bug](https://github.com/bradharding/doomretro/issues/639), as a workaround, a file with pre-recorded music can be used.

**Comment by Barbaross93** [comment]
In addtion to specifying $SDL_SOUNDFONTS, I had to install `libfluidsynth` in order for music to work.

**Comment by ericonr** [comment]
I don't think there's anything actionable for us.
