### ISSUE TITLE
Package Request: iceweasel-uxp

### ISSUE THREAD

**Issue by mrnhmath** [void-linux/void-packages#3066]
https://wiki.hyperbola.info/doku.php?id=en:project:iceweasel-uxp

**Comment by maxice8** [comment]
I don't see benefit in adding yet another browser the costs of maintaining are high and the benefits very low

**Comment by maxice8** [comment]
I don't see benefit in adding yet another browser the costs of maintaining are high and the benefits very low

**Comment by paoloschi** [comment]
...and it is for this kind of benefits that for the time being in Void I use PaleMoon as web browser.
(I am also convinced that those who choose a distro like Void should not ignore such fundamental differences compared to the dominant browsers but it is not this place for such a discussion...)
I would like to make this point instead: the reasons why Palemoon has not been packaged concern only issues of copyrights and licenses, I do not remember it was for reasons related to too much maintenance work ...is that correct?
Before reading this issue I knew nothing about Iceweasel-uxp
Palemoon and Iceweasel-uxp both seem now to be aimed at achieving common goals for users with the same needs/expectations...
If Iceweasel-uxp is totally focused on Linux while Palemoon spends a lot of development time on the Windows front, I too would much prefer to switch from Palemoon to Iceweasel-uxp!
Iceweasel-uxp not posing licensing issues could then replace in full the past requests already brought about Palemoon, going to satisfy all users who do not see these browsers as "yet another browser" understood as mere duplicate of Firefox & C.????
Thank you mrnhmath for your involvement!...

**Comment by Johnnynator** [comment]
>I would like to make this point instead: the reasons why Palemoon has not been packaged concern only issues of copyrights and licenses, I do not remember it was for reasons related to too much maintenance work ...is that correct?

Licensing was the reason why the effort was fully stopped without any further discussions, but even before it was not fully clear if it will be merged.

**Comment by mrnhmath** [comment]
I appreciate all the input on the matter.

**Comment by paoloschi** [comment]
Thanks Johnnynator and Hoshpak: when I wrote this morning I certainly did not have clear in mind all the implications and difficulties that you have here so well described...
But seems to me unfortunate that, in the need to restrict the offer, there are never the conditions to rule out at least one between Firefox and Chromium to give space to a more user-respectful alternative. I hope this consideration is not taken as a controversy but just the general remark it wants to be: there are so many distributions to meet every particular liking of users but, as for the web browser, practically on 100% of cases the alternative is only among these 2 shining examples of insecure bloatware even when the peculiarities of that distribution clearly go in opposite directions...

**Comment by johnny-mac** [comment]
@paoloschi do you have a template for palemoon? I've been working on one, also trying to make one for seamonkey.

**Comment by paoloschi** [comment]
> @paoloschi do you have a template for palemoon?

currently I'm still using Palemoon solely but no, I don't have my own template: for each new public release I download the pre-compiled official tarball.
Since major release v28.x I see further javascript security restrictions that are however also blocking the operation of some PM official add-ons (an example: `Reader View`) as well as the drag&drop in my local pages with JS not risky that I was able to use before (...) 
I briefly tested `otter-browser` -already in the repository- which I like but which causes me quite a bit of annoying garbage on the GUI in the area of the side panel (...??..I'll have to ask upstream about this)
