### ISSUE TITLE
nextcloud-client: segfault on launch

### ISSUE THREAD

**Issue by noarchwastaken** [void-linux/void-packages#30713]
### System

* xuname:  Void 5.11.18_1 x86_64 GenuineIntel uptodate rrFFFFFFFFFF
  *output of ``xuname`` (part of xtools)*
* package:  nextcloud-client-3.2.0_1
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior

A window should open.

### Actual behavior

It segfaults on launch.

```
[1]    26795 segmentation fault  nextcloud
```

### Steps to reproduce the behavior

1. Install nextcloud-client
2. run `nextcloud`

### backtrace

<details>
<pre><code>
$ gdb -q nextcloud
Reading symbols from nextcloud...
Reading symbols from /usr/lib/debug//usr/bin/nextcloud...
(gdb) run
Starting program: /usr/bin/nextcloud
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[New Thread 0x7fffe50fc640 (LWP 32045)]
[New Thread 0x7fffdef6e640 (LWP 32046)]
[New Thread 0x7fffde76d640 (LWP 32047)]
[New Thread 0x7fffddf6c640 (LWP 32048)]
[New Thread 0x7fffdd735640 (LWP 32049)]
[New Thread 0x7fffce936640 (LWP 32050)]
[New Thread 0x7fffce135640 (LWP 32051)]
[New Thread 0x7fffcd934640 (LWP 32052)]
[New Thread 0x7fffcd133640 (LWP 32053)]
[New Thread 0x7fffcc932640 (LWP 32054)]
[New Thread 0x7fffc25bf640 (LWP 32055)]
[New Thread 0x7fffc1dbe640 (LWP 32056)]
[New Thread 0x7fffc15bd640 (LWP 32057)]
[New Thread 0x7fffc0dbc640 (LWP 32058)]
[New Thread 0x7fff9bfff640 (LWP 32059)]
[New Thread 0x7fff9a906640 (LWP 32061)]
[Detaching after fork from child process 32062]
[Detaching after fork from child process 32063]
[Detaching after fork from child process 32064]
[New Thread 0x7fff9a105640 (LWP 32067)]
[New Thread 0x7fff99904640 (LWP 32068)]
[New Thread 0x7fff99103640 (LWP 32069)]
[New Thread 0x7fff98902640 (LWP 32070)]
[New Thread 0x7fff83fff640 (LWP 32071)]
[New Thread 0x7fff837fe640 (LWP 32072)]
[New Thread 0x7fff82ffd640 (LWP 32073)]
[New Thread 0x7fff827fc640 (LWP 32074)]
[New Thread 0x7fff81ffb640 (LWP 32075)]
[New Thread 0x7fff817fa640 (LWP 32076)]
[New Thread 0x7fff80ff9640 (LWP 32077)]
[New Thread 0x7fff67fff640 (LWP 32078)]
[New Thread 0x7fff677fe640 (LWP 32079)]
[New Thread 0x7fff66ffd640 (LWP 32080)]

Thread 1 "nextcloud" received signal SIGSEGV, Segmentation fault.
0x00007fffee9dd090 in QScreen::geometry() const () from /usr/lib/libQt5Gui.so.5
(gdb) backtrace
#0  0x00007fffee9dd090 in QScreen::geometry() const () from /usr/lib/libQt5Gui.so.5
#1  0x000055555568b51e in OCC::OwncloudWizard::centerWindow (this=this@entry=0x5555561e47a0) at ../src/gui/wizard/owncloudwizard.cpp:119
#2  0x000055555568cf82 in OCC::OwncloudWizard::OwncloudWizard (this=0x5555561e47a0, parent=<optimized out>) at ../src/gui/wizard/owncloudwizard.cpp:113
#3  0x000055555563cdb0 in OCC::OwncloudSetupWizard::OwncloudSetupWizard (this=0x55555620f7a0, parent=<optimized out>) at ../src/gui/owncloudsetupwizard.cpp:45
#4  0x0000555555640730 in OCC::OwncloudSetupWizard::runWizard (obj=0x7fffffffe1b0, amember=0x555555725509 "1slotownCloudWizardDone(int)", parent=0x0)
    at ../src/gui/owncloudsetupwizard.cpp:77
#5  0x000055555561321b in OCC::Application::slotCheckConnection (this=0x7fffffffe1b0) at ../src/gui/application.cpp:468
#6  0x00007fffee178f61 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#7  0x00007fffef0ae17f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007fffee14cf3a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#9  0x00007fffee14f971 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#10 0x00007fffee1a4c93 in ?? () from /usr/lib/libQt5Core.so.5
#11 0x00007fffee7666fb in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#12 0x00007fffee7669a8 in ?? () from /usr/lib/libglib-2.0.so.0
#13 0x00007fffee766a5f in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#14 0x00007fffee1a431f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#15 0x00007fffee14b8eb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#16 0x00007fffee153b70 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#17 0x000055555560f0a9 in main (argc=<optimized out>, argv=0x7fffffffe180) at ../src/gui/main.cpp:191
(gdb)
</code></pre>
</details>

**Comment by noarchwastaken** [comment]
nvm; it's fixed by upstream commit <https://github.com/nextcloud/desktop/commit/aadee15008ca4974e542f3fb6ca1694592d9e6fe>.

I will keep this issue open until upstream cuts a point release and Void gets it though.

**Comment by ericonr** [comment]
That looks easy to backport as a patch for our package. Should be simple to do, unless a release is imminent.
