### ISSUE TITLE
caja: fails to start with falsely missing dependency

### ISSUE THREAD

**Issue by HenriDellal** [void-linux/void-packages#30761]
### System

* xuname:  
  * Void 5.11.18_1 x86_64 GenuineIntel notuptodate rrrmFFFFF
* package:  
  * `caja-1.24.1_1`

### Expected behavior
`caja` starts normally.

### Actual behavior
Start fails with error: `caja: error while loading shared libraries: libexempi.so.8: cannot open shared object file: No such file or directory`.

`exempi` package is present on my system (version 2.5.0_1) and it provides `libexempi.so.8`.

### Steps to reproduce the behavior
- install `caja` package;
- run `caja` command from terminal.

Mentioning @skmpz as caja maintainer

**Comment by skmpz** [comment]
I currently have no issues using 5.11.17_1 and caja 1.24.1.

Can you ensure that both libexempi.so.8 and libexempi.so.8.0.0 are present in /usr/lib?

**Comment by HenriDellal** [comment]
I checked it and the files are missing, though `xbps-query exempi` output shows amongst other things

```
shlib-provides:
	libexempi.so.8
```

**Comment by HenriDellal** [comment]
Fixed with force-reinstalling exempi
