### ISSUE TITLE
xscreensaver package needs perl as a dependency

### ISSUE THREAD

**Issue by pezcurrel** [void-linux/void-packages#30818]
### System

* xuname:  
Void 5.11.18_1 x86_64 GenuineIntel uptodate rrFF
* package:  
xscreensaver-6.00_1

Xscreensaver should depend on perl, since it relies on perl scripts; eg: when running a screensaver that needs to display text (eg phosphor) xscreensaver tries to run ``/usr/libexec/xscreensaver/xscreensaver-text``, but it fails, so (eg) phosphor displays only an error message.

**Comment by ericonr** [comment]
@leahneukirchen

**Comment by ericonr** [comment]
Arch also pulls in a dependency to `perl-LWP`: https://archlinux.org/packages/extra/x86_64/xscreensaver/
