### ISSUE TITLE
All versions of 32-bit ARM Go compliers use software floating point.

### ISSUE THREAD

**Issue by ejolson2005** [void-linux/void-packages#30827]
### System
Void 32-bit ARMv6 and ARMv7 versions of the Go compiler.  
### Expected behavior
The Go compiler will use hardware float by default for 32-bit ARMv7 platform and maybe even the ARMv6 platform.
### Actual behavior
The Go compiler packages are built without specifying GOARM=7 or GOARM=6 and apparently default to ARMv5 compatibility.
### Steps to reproduce the behavior
Compile any program that uses floating point and check performance.
### Possible fix
The Alpine Linux build scripts case things as
```
armel)  export GOARCH="arm" GOARM=5 ;;
armhf)  export GOARCH="arm" GOARM=6 ;;
armv7)  export GOARCH="arm" GOARM=7 ;;
```
which seems like a good idea to avoid everything defaulting to GOARM=5.

**Comment by ejolson2005** [comment]
Another work around is to set the environment variable
```
$ export GOARM=7
```
before compiling anything on the ARMv7 version of Void Linux.

**Comment by ericonr** [comment]
That should definitely be fixed. You can look into `common/environment/build-style/go.sh` to see how the setup works and tweak it.

**Comment by ericonr** [comment]
Hm, are you sure?

https://github.com/void-linux/void-packages/blob/6387c58f4e77b52f06280ef2aa5191160a5f67d4/common/environment/build-style/go.sh#L23-L25

How did you test this?
