### ISSUE TITLE
Bug: gufw does not start

### ISSUE THREAD

**Issue by el-christianito** [void-linux/void-packages#30914]
### System

* xuname:  
Void 5.11.18_1 x86_64 AuthenticAMD uptodate hold rrrmFFFFFFFFF

* package:
gufw-21.04.0_2, potentially libwpe-1.10.0_2 or webkit2gtk-2.32.1_1

### Expected behavior
gufw GUI shows on screen

### Actual behavior
warning displayed and nothing starts
```
** (gufw.py:20206): WARNING **: 13:56:16.898: Failed to load shared library 'libwebkit2gtk-4.0.so.37' referenced by the typelib: libwpe-1.0.so.1: cannot open shared object file: No such file or directory
/usr/lib/python3.9/site-packages/gufw/gufw/view/gufw.py:117: Warning: cannot retrieve class for invalid (unclassed) type 'void'
  self.web_content = WebKit2.WebView()
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gufw/gufw.py", line 30, in <module>
    gufw = Gufw(controler.get_frontend())
  File "/usr/lib/python3.9/site-packages/gufw/gufw/view/gufw.py", line 79, in __init__
    self._set_objects_name()
  File "/usr/lib/python3.9/site-packages/gufw/gufw/view/gufw.py", line 117, in _set_objects_name
    self.web_content = WebKit2.WebView()
TypeError: could not get a reference to type class
```
The file does definitely exist under /usr/lib:
![bugticket_gufs](https://user-images.githubusercontent.com/9352289/118360092-620a0100-b586-11eb-8a27-7a8adba49934.png)

### Steps to reproduce the behavior
`sudo gufw`

**Comment by ericonr** [comment]
`gufw` seems really glitchy but I can kind of make it work with `sudo -E gufw-pkexec`

**Comment by el-christianito** [comment]
Thank you for the quick reply. Unfortunately, it doesn't work for me. Same error:
```
chris@void-desktop ~ % sudo -E gufw-pkexec
Password: 

** (gufw.py:3851): WARNING **: 18:33:04.111: Failed to load shared library 'libwebkit2gtk-4.0.so.37' referenced by the typelib: libwpe-1.0.so.1: cannot open shared object file: No such file or directory
/usr/lib/python3.9/site-packages/gufw/gufw/view/gufw.py:117: Warning: cannot retrieve class for invalid (unclassed) type 'void'
  self.web_content = WebKit2.WebView()
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gufw/gufw.py", line 30, in <module>
    gufw = Gufw(controler.get_frontend())
  File "/usr/lib/python3.9/site-packages/gufw/gufw/view/gufw.py", line 79, in __init__
    self._set_objects_name()
  File "/usr/lib/python3.9/site-packages/gufw/gufw/view/gufw.py", line 117, in _set_objects_name
    self.web_content = WebKit2.WebView()
TypeError: could not get a reference to type class
```

Do you have some special environment variables set which get preserved?

**Comment by ericonr** [comment]
I don't think so, I needed `-E` due to display variables I think.

No idea what your error is about :/

**Comment by el-christianito** [comment]
Oy, the `xbps-pkgdb -a` resulted in quite some list of errors. :astonished: Thank you for the hint! 
Probably this is the result of some rollback I did a few weeks ago. It will take me some time to fix all of these errors. I'll get back as soon as I'm done and tried again.

**Comment by el-christianito** [comment]
I'm done fixing most pkgdb errors. Those problems were indeed related to the rollback a few weeks ago. Seems that I should better include the package DB when doing so.

Anyways, after reinstalling `libwpe`, the problem was solved. gufw is running without any issues again.

Thank you very much for your help and the right hint!
