### ISSUE TITLE
not found vpcs on gns3

### ISSUE THREAD

**Issue by xlwyx** [void-linux/void-packages#30926]
Hi, Void community..

https://i.imgur.com/ILqYjjL.png; In this image, vpcs not worked on gns3 after I had installed gns3-server gns3-gui putty dynamips ubridge vpcs.

my mail: xx_xarehnass_x@yahoo.com

**Comment by ericonr** [comment]
@tsndqst could you take a look?

**Comment by tsndqst** [comment]
@ericonr @xlwyx I can take a look but I can't focus on this until this evening.

@xlwyx Is this a new install or did you upgrade from an earlier version?

**Comment by xlwyx** [comment]
Is new instalation and vpcs not found on /bin/vpcs. But, with Void terminal start, vpcs well. Into gns3 not worked

    On Monday, 17 May 2021, 07:57:39 GMT-5, Tim Sandquist ***@***.***> wrote:  
 
 


@ericonr @xlwyx I can take a look but I can't focus on this until this evening.

@xlwyx Is this a new install or did you upgrade from an earlier version?

**Comment by tsndqst** [comment]
vpcs is a separate package from gns3-server.  Try installing it with `xbps-install -Su vpcs`.

**Comment by tsndqst** [comment]
Sorry @xlwyx, I just reread your original comment and I see you did install vpcs.  I am looking into this more now.
Are there logs that you can share?  gns3-server logs to stdout I believe.  In the project directory there should be logs for vpcs and ubridge in `~/GNS3/projects/untitled/project-files/vpcs`.

**Comment by xlwyx** [comment]
On Mon, May 17, 2021 at 18:24, Tim Sandquist ***@***.***> 
wrote:
> —
Yesss..  on 
~/GNS3/projects/untitled/project-files/vpcs/556163df-8f50-437e-95cd-11cfe6acedd0/ 
show me one log.
You can do help me ...?
How to do I solve it...?
I use AgarimOS (Void Linux derivated) and my AgarimOS is updated.

**Comment by xlwyx** [comment]
See it: <https://i.imgur.com/ZpCpvz3.png>;  
<https://i.imgur.com/zNVbvPV.png>

**Comment by tsndqst** [comment]
does the vpcs.log file have anything in it?
There is a GitHub [issue](https://github.com/GNS3/gns3-gui/issues/3110#issuecomment-768105648) with the same error message as you report. It looks like that particular issue was fixed but perhaps there is another case that was not solved by the fix.

Is the vpcs process running

I am having trouble reproducing the issue as my `vpcs` command fails with a segfault.  I'll keep trying but I'm not sure how long it will take to figure out.

Perhaps you can switch from VPCS to ipterm or another end device in the mean time.
