### ISSUE TITLE
Use -doc tarballs for notcurses 

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#31059]
Instead of requiring `pandoc` for any of the archs, notcurses publishes a tarball with prebuilt docs, `nocurses-docs`. Can be obtained from https://github.com/dankamongmen/notcurses/releases and should be used in order to provide docs for all builds of the library.

@mobinmob

**Comment by mobinmob** [comment]
I know, it is what I did originally:
https://github.com/void-linux/void-packages/pull/26292
I am not going to change that - feel free to do it.
