### ISSUE TITLE
system-accounts fails to create group with --rootdir=

### ISSUE THREAD

**Issue by maxice8** [void-linux/void-packages#3115]
```
# xbps-install -f  --rootdir=/var/lib/machines/void2 chrony 2>&1

Name   Action    Version           New version            Download size
chrony reinstall 3.4_1             3.4_1                  - 

Size required on disk:         495KB
Space available on disk:       187GB

Do you want to continue? [Y/n] 

[*] Downloading binary packages

[*] Verifying package integrity
chrony-3.4_1: verifying RSA signature...

[*] Running transaction tasks
chrony-3.4_1: unpacking ...

[*] Configuring unpacked packages
chrony-3.4_1: configuring ...
Failed to create chrony () system group!
chrony-3.4_1: installed successfully.

0 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.
```

**Comment by CameronNemo** [comment]
I have worked around this with user namespaces. The lxc package has a neat little command called `lxc-usernsexec`. I think [buildah](https://github.com/containers/buildah) has got something similar.

**Comment by maxice8** [comment]
Sounds nice but i have no clue how this applies to this specific bug

**Comment by Duncaen** [comment]
```
[pid 21943] write(2, "Password: ", 10)  = 10
[pid 21943] read(0,
```

**Comment by maxice8** [comment]
Thanks for the help, solved.

**Comment by maxice8** [comment]
> in usr/libexec/xbps-triggers/system-accounts, but for some reason this is using the hosts PAM authentication too.

Reading upon shadow issues and PRs on github i saw that this is by design, would be nice to have something like `systemd-sysuser --root=.` that manipulates the files directly
