### ISSUE TITLE
[package request] gopass-jsonapi

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#31155]
https://github.com/gopasspw/gopass-jsonapi

It is useful to configure [gopassbridge](https://github.com/gopasspw/gopassbridge#connect-to-gopass) which lets web browser use gopass password store

**Comment by kuhnchris** [comment]
Weird that nobody has taken this on yet - #38246

**Comment by eoli3n** [comment]
Thanks for this, I'll test

**Comment by paper42** [comment]
packaged, closing
