### ISSUE TITLE
kernel 5.12 breaks xorg

### ISSUE THREAD

**Issue by rapha8l** [void-linux/void-packages#31164]
### System

* xuname:  
Void 5.11.22_1 x86_64 GenuineIntel uptodate rrrmFFFF

* package:  
linux5.12-5.12.7_1

### Expected behavior
Normal login with X

### Actual behavior
X server dies

Works perfectly with linux5.11, and breaks only when booting with 5.12

xsession-errors log :

```
(connman-ui-gtk:1770): dbind-WARNING **: 21:38:09.652: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
WARNING: No icon found in path: 'dialog-information'
X connection to :0 broken (explicit kill or server shutdown).
X connection to :0 broken (explicit kill or server shutdown).
XIO:  fatal IO error 2 (No such file or directory) on X server ":0"
      after 98 requests (98 known processed) with 0 events remaining.
X connection to :0 broken (explicit kill or server shutdown).
X connection to :0 broken (explicit kill or server shutdown).
XIO:  fatal IO error 2 (Aucun fichier ou dossier de ce type) on X server ":0"
      after 39 requests (39 known processed) with 0 events remaining.
i3: Cannot open display
feh ERROR: Can't open X display. It *is* running, yeah?
Unable to init server: Could not connect: Connection refused
Unable to init server: Impossible de se connecter : Connection refused

```

Thanks

**Comment by ericonr** [comment]
What does `xbps-pkgdb -a` say?

Can you share more info? What your hardware is, your `~/.xinit`, the full Xorg log from `/var`?

**Comment by rapha8l** [comment]
Hello, here is the Xorg log, not very informative, the xbps-pkgdb -a which may be more interesting, my .xinitrc and what I autostart with i3
Thanks

[Xorg.0.log](https://github.com/void-linux/void-packages/files/6562055/Xorg.0.log)
[xbps-pkgdb.txt](https://github.com/void-linux/void-packages/files/6562060/xbps-pkgdb.txt)
[xinitrc.txt](https://github.com/void-linux/void-packages/files/6562070/xinitrc.txt)
[i3-config.txt](https://github.com/void-linux/void-packages/files/6562300/i3-config.txt)

**Comment by ericonr** [comment]
Have you tried reinstalling `linux5.12`? It should fix that error.

**Comment by rapha8l** [comment]
I reinstalled
After a few investigations, any dm broke, but it was due to a picom config
strangely my scripts having DISPLAY=:0 don't work anymore, but work if commented
dwm (no special config) and pekwm crashed too, but not awesome or herbstluftwm
Thanks

**Comment by rapha8l** [comment]
Also I'm using intel driver

**Comment by abenson** [comment]
How are you starting your window manager?  your `.xinitrc` doesn't start a window manager, so if its being used (i.e. via `startx`) Xorg won't stay running.

**Comment by abenson** [comment]
I also just noticed your xuname doesn't match the complained about package?

**Comment by rapha8l** [comment]
hi,
strange for the xuname
On my side, things seem to be ok, even on the display variable
Thanks
