### ISSUE TITLE
Certificate verification failure, cannot fetch some distfiles

### ISSUE THREAD

**Issue by newbluemoon** [void-linux/void-packages#31161]
When trying to fetch the distfiles for `sonic-visualiser` and `vamp-plugin-sdk` there is a certificate verification failure:
```
=> sonic-visualiser-4.3_1: fetching distfile 'sonic-visualiser-4.3.tar.gz'...
Certificate verification failed for /jurisdictionC=GB/businessCategory=Government Entity/serialNumber=1989-08-02/C=GB/ST=Tower Hamlets/L=Bethnal Green/O=Queen Mary University of London/CN=code.soundsoftware.ac.uk
SSL_connect returned 1
https://code.soundsoftware.ac.uk/attachments/download/2786/sonic-visualiser-4.3.tar.gz: Operation not permitted
=> ERROR: sonic-visualiser-4.3_1: failed to fetch sonic-visualiser-4.3.tar.gz.
```
```
=> vamp-plugin-sdk-2.10.0_1: fetching distfile 'vamp-plugin-sdk-2.10.0.tar.gz'...
Certificate verification failed for /jurisdictionC=GB/businessCategory=Government Entity/serialNumber=1989-08-02/C=GB/ST=Tower Hamlets/L=Bethnal Green/O=Queen Mary University of London/CN=code.soundsoftware.ac.uk
SSL_connect returned 1
https://code.soundsoftware.ac.uk/attachments/download/2691/vamp-plugin-sdk-2.10.0.tar.gz: Operation not permitted
=> ERROR: vamp-plugin-sdk-2.10.0_1: failed to fetch vamp-plugin-sdk-2.10.0.tar.gz.
```

It seems there is a problem with `code.soundsoftware.ac.uk`. However, the files can be downloaded without error using firefox or chromium. So the issue might lie with `ca-certificates`.

**Comment by ericonr** [comment]
I can reproduce it, and `ca-certificates` doesn't seem to have new commits that I could find.

`curl` gets the same errors :/

**Comment by RossComputerGuy** [comment]
I'm having the same problem, trying to bootstrap is annoying and I cannot leave it alone. This error happens with like 90% of packages and seriously needs to be fixed.

**Comment by RossComputerGuy** [comment]
Turns out Debian's is outdated, we should use `nss` to provide `ca-certificates`. This is exactly what Arch Linux.

**Comment by ericonr** [comment]
Sounds reasonable to open a proposal to switch. @leahneukirchen @sgn thoughts?

**Comment by RossComputerGuy** [comment]
If we do go ahead and replace ca-certificates with an `nss` provided one, we will have to have Arch Linux's `ca-certificates-utils` package added in. However, it might be possible to combine both the utils package and `nss`+`ca-certificates` subpackage.

**Comment by RossComputerGuy** [comment]
I've got the `nss` + `ca-certificates` package implemented in my fork. If going ahead, I can open a PR for adding it.

**Comment by ericonr** [comment]
The best way to start a discussion is opening a PR. I think @sgn was looking into this as well.

**Comment by sgn** [comment]
Hm, the problem is not our `ca-certificates`, https://code.soundsoftware.ac.uk is signed by an intermediate certfificates, which in turn signed by `QuoVadis Root CA 2 G3`, our current ca-certificates has that root certs already.

However, https://code.soundsoftware.ac.uk doesn't send the full certificate chain, so neither openssl nor curl can verify.
You can confirm by:
```sh
{
    curl -L http://trust.quovadisglobal.com/quovadiseuropeevsslcag1.crt |
        openssl x509 -inform DER -outform PEM
    openssl s_client -showcerts -servername code.soundsoftware.ac.uk -connect code.soundsoftware.ac.uk:443 </dev/null
} >fullchain.pem
openssl verify fullchain.pem
```

Solution:
- Each of those servers should send the full chain; or
- Changing out libfetch to inspect certificate and download the intermediate certificates.

**Comment by sgn** [comment]
> Turns out Debian's is outdated, we should use `nss` to provide `ca-certificates`. This is exactly what Arch Linux does.

The root certs for `code.soundsoftware.ac.uk` is there, Debian's ca-certificates is outdated, but it's irrelevant.

> If we do go ahead and replace ca-certificates with an `nss` provided one, we will have to have Arch Linux's `ca-certificates-utils` package added in. However, it might be possible to combine both the utils package and `nss`+`ca-certificates` subpackage.

 We don't need to go with RedHat route. My proposal works just fine.

**Comment by sgn** [comment]
I think nothing we can do in void-packages. Closing?

**Comment by ericonr** [comment]
If even curl doesn't support this use case, I don't see why libfetch should. They should fix the server.

I think we should find a better mirror for the files or mirror them ourselves before closing the issue, though.

**Comment by sgn** [comment]
> If even curl doesn't support this use case, I don't see why libfetch should. They should fix the server.

curl puts it in TODO list. Given the length of TODO list, I think it will take some time.
https://github.com/curl/curl/blob/bfbde883af33397943df68a3ae01847a634d33bf/docs/TODO#L117

https://github.com/curl/curl/issues/2793

> I think we should find a better mirror for the files or mirror them ourselves before closing the issue, though.

Agree!

**Comment by newbluemoon** [comment]
Arch fetches the sources for sonic-visualiser from bintray.com (cf. https://github.com/archlinux/svntogit-community/blob/packages/sonic-visualiser/trunk/PKGBUILD), but I don’t think it’s an official mirror.

**Comment by leahneukirchen** [comment]
bintray is dead.

**Comment by newbluemoon** [comment]
Debian is still at sonic-visualiser-4.2, but upstream is at 4.3, so maybe self-mirroring the sources in question is the best option?
