### ISSUE TITLE
love: alignment problem (+ reference to possible patch)

### ISSUE THREAD

**Issue by ralvgh** [void-linux/void-packages#31234]
### System

* xuname: Void 5.11.22_1 i686 GenuineIntel uptodate rFF

* package:  love-11.3_1
 
### Expected behavior

According to "Making a Game" on [love2d-wiki/Getting Started](https://love2d.org/wiki/Getting_Started) a window opens with text "Hello World".

### Actual behavior

An error message is displayed instead saying

    Error

    wrap_Math.lua:35: Cannot push love object to Lua: unexpected alignment (pointer is 0x02263fe8 but alignment should be 16)

    Traceback

    [C]: in function '_getRandomGenerator'
    wrap_Math.lua:35: in main chunk
    [C]: at 0xb7b63480
    [C]: in function 'require'
    [C]: in function 'xpcall'
    [C]: in function 'xpcall'

### Steps to reproduce the behavior
 
     $ mkdir getting.started && cd getting.started
     $ cat > main.lua
     function love.draw()
         love.graphics.print("Hello World", 400, 300)
     end
     
     zip -9 -r getting.started.love .
     
     /usr/bin/love getting.started.love

### Possible patch

Using a [patch written by pgimeno](https://www.love2d.org/forums/viewtopic.php?p=234660#p234660) on [love-11.3-linux-i686.tar.gz](https://github.com/love2d/love/releases/download/11.3/love-11.3-linux-i686.tar.gz) the problem vanishes for me.

**Comment by ericonr** [comment]
@ralvgh could you make a PR importing the patch? It sounds reasonable to me...

**Comment by tallero** [comment]
patch doesn't work for me
