### ISSUE TITLE
busybox: does not include mdev applet

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#3124]
### System

* xuname:  Void 4.18.8_1 x86_64 GenuineIntel uptodate rFFFFFFFFFFFFFFFFF
* package:  busybox-1.29.3_1

### Expected behavior

Invoking `busybox uevent mdev` would result in new netlink events being processed.

### Actual behavior

`mdev: applet not found`

### Steps to reproduce the behavior

Invoke `busybox mdev`.

**Comment by cr6git** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/busybox/files/busybox.dotconfig#L627

**Comment by CameronNemo** [comment]
It is yes by default, I'm not sure why we would have to set the config.

https://git.busybox.net/busybox/tree/util-linux/mdev.c#n10

**Comment by Duncaen** [comment]
I'm not sure how useful this would be, maybe we could add another subpackage with more features enabled for a full system replacement and keep the default busybox as a package for most basic utilities.

**Comment by CameronNemo** [comment]
Maybe the NTP daemon can be in that package too.

**Comment by maxice8** [comment]
addressed by busybox-1.30.1 changes
