### ISSUE TITLE
Package request: ProtonVPN GUI

### ISSUE THREAD

**Issue by anubhavkini** [void-linux/void-packages#31255]
**Homepage**
https://protonvpn.com/

**Source**
https://github.com/ProtonVPN/linux-app

**Description**
 Official ProtonVPN Linux app

**License**
GPL-3.0

**Comment by FollieHiyuki** [comment]
Oh they finally released the source code. I will try to package this next week.

We have `protonvpn-cli` which is the deprecated community version. Wonder whether we should change it to use the official source, or keeping it as legacy and package 2 new apps (official cli + gui).

**Comment by Gottox** [comment]
Isn't that just an OpenVPN frontend?

**Comment by FollieHiyuki** [comment]
It is true. But it makes connecting to servers quite easier.

I'm using OpenVPN directly, and it feels tedious when importing downloaded profiles.

**Comment by FollieHiyuki** [comment]
@anubhavkini you want to make the PR? I give up half way through because of the deps (protonvpn-gui -> protonvpn-cli -> python3-gnupg -> gnupg) and I don't want 2 gpg package in my machine.
My progress so far: https://github.com/FollieHiyuki/void-packages/tree/protonvpn
