### ISSUE TITLE
Package request : Pangolin desktop

### ISSUE THREAD

**Issue by rapha8l** [void-linux/void-packages#31257]
Hi,

This desktop coming from DalhiaOs, a fork of Fuchsia Os, runs on Linux, but needs flutter, it seems nice
https://github.com/dahliaOS/pangolin_desktop
Thanks

**Comment by cinerea0** [comment]
This would require Flutter, and by extension Dart, in order to be built. Neither of these are packaged because building them from source is extremely convoluted.

**Comment by rapha8l** [comment]
ok thanks, I didn't image it was so complicated
