### ISSUE TITLE
lesstif is not maintained since 2012 and should be replaced with LGPL'd Motif

### ISSUE THREAD

**Issue by asiekierka** [void-linux/void-packages#3125]
As per [the project's own website](http://lesstif.sourceforge.net/), lesstif, the project to reimplement Motif under the LGPL, is no longer maintained as Motif itself is now available under the LGPL.

As such, I feel it is rational to work on replacing lesstif with Motif inside Void Linux.

Does anyone have any objections?

**Comment by Vaelatern** [comment]
Agreed.

**Comment by asiekierka** [comment]
Right. I'll get to work, then. Thank you!

**Comment by maxice8** [comment]
ping

**Comment by maxice8** [comment]
motif seems to be very hostile to cross compiling

**Comment by ericonr** [comment]
@abenson managed to figure it out :)
