### ISSUE TITLE
Request mpv+ffmpeg video hw decode on rpi (+ patches)

### ISSUE THREAD

**Issue by akce** [void-linux/void-packages#31268]
I'd love it if mpv could play video on raspberry pi's using the hardware.

To that end, i've got a [branch](https://github.com/akce/void-packages/tree/mpv%2Bffmpeg-hwdec) that makes those mods.

There's two steps needed: first ffmpeg needs to be modded and then mpv.

This is an issue, rather than a pull request because it touches on two packages and i don't know how to go about making this request.

Please advise if this is a change that you'd like to incorporate.

I've tested watching video on an rpi model 3b+ running armv7l.

I've built packages for armv6l successfully.

And i've built ffmpeg and mpv for x86_64, just to ensure that my changes didn't break those builds.

**Comment by ericonr** [comment]
I think accepting these is unlikely, since ideally we'd like to move away from depending on `rpi-userland` for things.

Maybe as a build option that isn't enabled by default. And it'd be a single PR.

**Comment by akce** [comment]
Thanks for looking into this @ericonr.
I'm afraid that `rpi-userland-devel` is required at build-time as turning on these video hw decode flags adds dependencies to libs provided by that package. Or is there an alternate way to do this?
But always enabling `rpi` in the `mpv` template was a mistake. Thanks for pointing that out - I've force pushed the correction.
Does this look better now for a PR?

**Comment by q66** [comment]
you shouldn't need mmal

things should work as they are with v4l2m2m (e.g. with mpv `--hwdec=v4l2m2m-copy`

mmal needs proprietary libraries and we're not going to build proprietary-backed board-specific stuff into the default packages 

these are also never going to work on musl and so on

**Comment by akce** [comment]
Oh i see. Many thanks for the extra info @q66 - i'm so very surprised that i haven't come across v4l2m2m before. Anyway, I'll move to using that instead.
