### ISSUE TITLE
Firefox rendering issues since 89.0 update

### ISSUE THREAD

**Issue by Gottox** [void-linux/void-packages#31294]
The font does not resize when zooming with `Ctrl`+`+` and is much too small for hidpi displays.

Site: facebook.com

![image](https://user-images.githubusercontent.com/1056976/120881304-5c756900-c5d0-11eb-879d-096468749e86.png)

**Comment by Gottox** [comment]
If I remove the font family via devtools the font is scaled correctly.

**Comment by lonwillett** [comment]
I'm also seeing issues with a large number of websites (github included). Turning off the option "Allow pages to choose their own fonts, instead of your selections above" is my workaround, but I would like a proper fix, or at least an understanding of what is going wrong.

**Comment by egorenar** [comment]
I have the same issue.

**Comment by marmeladema** [comment]
Same issue for me too.
![firefox_font_issue](https://user-images.githubusercontent.com/1629419/120885701-29d46c00-c5e2-11eb-88be-d24be672ed55.png)

**Comment by Oreo639** [comment]
What is the output of `xbps-query -Rs xorg-fonts`?
This has been an issue for a long while.

**Comment by Gottox** [comment]
@Oreo639 thanks for the hint, but this issue is unrelated to configuration.

**Comment by Gottox** [comment]
@lonwillett @marmeladema github is actually fine for me.

**Comment by Gottox** [comment]
workaround:
```
xbps-remove font-adobe-100dpi font-adobe-75dpi xorg-fonts
```

**Comment by Cnoob41** [comment]
I have the same issue, everything was fine before I upgraded firefox to version 89. My github is messed up too.

**Comment by lonwillett** [comment]
> What is the output of `xbps-query -Rs xorg-fonts`?

[*] xorg-fonts-7.6_5 Modular Xorg Fonts

> Hasn't this been an issue for a long while?

It's new with ff 89 for me. Where I've looked, it seems like  some of the fonts from font-adobe-* don't work; and probably others.

> (If you remove xorg-fonts and all of it's dependencies, the issue should go away.)
> 
> This section was added to the void handbook specifically because of this issue:
> https://docs.voidlinux.org/config/graphical-session/fonts.html

That does seem to work; i.e. disabling bitmap fonts with fontconfig; i.e. enabling the 70-no-bitmaps.conf for fontconfig. Although it seems like a bit of a heavy-handed kludge. (Or it should be the default configuration).

**Comment by egorenar** [comment]
> What is the output of `xbps-query -Rs xorg-fonts`?
> Hasn't this been an issue for a long while?
> (If you remove xorg-fonts and all of it's dependencies, the issue should go away.)
> 
> This section was added to the void handbook specifically because of this issue:
> https://docs.voidlinux.org/config/graphical-session/fonts.html

Thanks, this helps.

**Comment by hervyqa** [comment]
Guys, try this at home

```
ln -sf /usr/share/fontconfig/conf.avail/10-hinting-slight.conf /etc/fonts/conf.d/
ln -sf /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf /etc/fonts/conf.d/
ln -sf /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf /etc/fonts/conf.d/
ln -sf /usr/share/fontconfig/conf.avail/50-user.conf /etc/fonts/conf.d/
ln -sf /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/
```

**Comment by stnby** [comment]
Can we guys revert this broken version of Firefox back?

**Comment by Duncaen** [comment]
> Can we guys revert this broken version of Firefox back?

No, this version fixes security issues we are not going to revert a browsers version because some font setups are broken.

**Comment by stnby** [comment]
> > Can we guys revert this broken version of Firefox back?
> 
> No, this version fixes security issues we are not going to revert a browsers version because some font setups are broken.

I can't even read your reply on that browser :D

**Comment by arp242** [comment]
Also see: #25584

Installing the fixed fonts generally causes issues because some software may select them with the font selection wizandry, and has for years. It's not really a new issue or unique to Firefox 89 as such, although Firefox probably could fix it, it'll probably break somewhere sooner or later again.

I'm not sure if installing them by default in xorg/xorg-fonts is still a good default, as was mentioned in the other issue. Maybe some old stuff like `xeyes` or whatnot might break though, but I doubt many people will care and we can add dependencies if need be. There's also some other stuff like `xterm` that's a bit more common; I don't know what its defaults are these days.

Either way, doing some work on that seems like the best long-term fix.

**Comment by arp242** [comment]
And another: #16573

**Comment by Unixware** [comment]
just FYI there is no such issue with the dev version of the firefox (version 90)..

**Comment by Duncaen** [comment]
> just FYI there is no such issue with the dev version of the firefox (version 90)..

Is this actually comparable because you've build it with the same system dependencies void uses or does it mozillas binary that statically links a lot of things?

**Comment by Unixware** [comment]
nope its the one from Mozilla...

**Comment by sirn** [comment]
For anything getting this issue after 89.0, this seems to be a regression in Firefox upstream caused by a new default. Turning off `gfx.e10s.font-list.shared` fixed the issue in my case. See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1714318

**Comment by HadetTheUndying** [comment]
> gfx.e10s.font-list.shared

How do i get to this setting as I can't find it by searching in Firefox's search in settings?

**Comment by Duncaen** [comment]
`about:config`

**Comment by mtbc** [comment]
Looks to be fixed in 89.0.1 - https://bugzilla.mozilla.org/show_bug.cgi?id=1714282
Sorry if I missed something in above discussion, it's too tiny for me to read!

**Comment by ahesford** [comment]
Is this matter resolved with newer Firefox packages?

**Comment by stnby** [comment]
> Is this matter resolved with newer Firefox packages?

Seems like, we can probably close this issue.

**Comment by Anachron** [comment]
Are you talking about [this](https://github.com/void-linux/void-packages/issues/31294#issuecomment-864532071) workaround or [this](https://github.com/void-linux/void-packages/issues/31294#issuecomment-858921154)?

Or even [this](https://github.com/void-linux/void-packages/issues/31294#issuecomment-855526254) or [this](https://github.com/void-linux/void-packages/issues/31294#issuecomment-855212048) one?

**Comment by StreetStrider** [comment]
It happens for me today. The solution was to disable bitmap fonts as described here: https://www.reddit.com/r/voidlinux/comments/fa9wyk/solution_for_non_antialiased_fonts_in_firefox_and/
```
ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/70-no-bitmaps.conf
fc-cache -fv
```
