### ISSUE TITLE
glib: build-time cyclic dependency

### ISSUE THREAD

**Issue by unspecd** [void-linux/void-packages#31319]
```console
$ ./xbps-src -a ppc64le-musl -NE pkg base-system
…
ERROR: Build-time cyclic dependency elfutils(ppc64le-musl), libmicrohttpd(ppc64le-musl), gnutls(ppc64le-musl), p11-kit(ppc64le-musl), glib(ppc64le-musl), elfutils(ppc64le-musl) detected.
```

This is most likely due to this commit: 7377f185fc1c230ea1c5169971e27be71249f566.
https://github.com/void-linux/void-packages/blob/7377f185fc1c230ea1c5169971e27be71249f566/srcpkgs/p11-kit/template#L9-L10

**Comment by ericonr** [comment]
This was fixed in 0ab4214314cf0d95836c473c6b6cde6553dcf1d7

Lots of folks picked up on it close to each other :D
