### ISSUE TITLE
Two missing dependencies for nyxt(libfixposix-devel and gst-libav)

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#31323]
### System

* xuname:  Void 5.11.22_1 x86_64 GenuineIntel notuptodate hold rFF
  *output of ``xuname`` (part of xtools)*
* package:  nyxt
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
It should run without any error and also play youtube videos.

### Actual behavior
It doesn't run and doesn't play youtube videos.

### Steps to reproduce the behavior
Install the package provided by void-packages. If you run nyxt from terminal, you'll see something like this:

> 
> ↳ nyxt
> Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
>                                     {1000FB0103}>:
>   Error opening shared object "libfixposix.so":
>   libfixposix.so: cannot open shared object file: No such file or directory.
> 
> Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1000FB0103}>
> 0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
>   ~A." {1000660283}> #<unused argument> :QUIT T)
> 1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
>   ~A." {1000660283}>)
> 2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
>   ~A." {1000660283}>)
> 3: (ERROR "Error opening ~:[runtime~;shared object ~:*~S~]:
>   ~A." "libfixposix.so" "libfixposix.so: cannot open shared object file: No such file or directory")
> 4: (SB-SYS:DLOPEN-OR-LOSE #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libfixposix.so" :NAMESTRING "libfixposix.so" :HANDLE NIL :DONT-SAVE NIL))
> 5: (SB-ALIEN::TRY-REOPEN-SHARED-OBJECT #S(SB-ALIEN::SHARED-OBJECT :PATHNAME #P"libfixposix.so" :NAMESTRING "libfixposix.so" :HANDLE NIL :DONT-SAVE NIL))
> 6: (SB-SYS:REOPEN-SHARED-OBJECTS)
> 7: (SB-IMPL::FOREIGN-REINIT)
> 8: (SB-IMPL::REINIT T)
> 9: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
> 10: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
> 11: (SB-IMPL::START-LISP)
> 
> unhandled condition in --disable-debugger mode, quitting

So please add these dependencies to nyxt package:

gst-libav (For youtube videos)
libfixposix-devel (for running nyxt without any error at startup)

**Comment by egorenar** [comment]
I'm not sure about gst-libav, doesn't webkit depend on it ?
But libfixposix-devel is definitely missing.

**Comment by ericonr** [comment]
Fixed in linked PR, thanks.
