### ISSUE TITLE
Package php-fpm tries to use user and group http

### ISSUE THREAD

**Issue by LeamHall** [void-linux/void-packages#31422]
When the apache2 package uses the "_apache" user.

### Expected behavior

Package uses/creates needed user and group.

### Actual behavior

 php-fpm fails to start because it cannot find the user and group "http". 

```
ERROR: [pool www] cannot get uid for user 'http'
ERROR: FPM initialization failed

ERROR: [pool www] cannot get gid for group 'http'
ERROR: FPM initialization failed
```

### Steps to reproduce the behavior

Install and run php-fpm.
Check the error logs.

**Comment by ericonr** [comment]
A solution that was floated around in IRC is setting the `php-fpm` user/group to `_apache`, but that would break use cases without apache, so it isn't a proper solution. Alternatively, `apache` could be made to use `http` user.

Or maybe we just need `php-fpm` to also create the `http` user?

**Comment by LeamHall** [comment]
I am not a web person nor have I ever built my own Linux distro. My ideas are just ideas, I'm not sure if they are any good.

What permissions does php-fpm need? Does it need write access to the web directories? Does it need the UID/GID of whatever is serving httpd?

Changing Apache at this point would be a bit of work, and established servers might have an issue. I'm not sure how many sites are using the php-fpm package, but it might be fewer than are using Apache or Nginx. 

If php-fpm just needs read access to the web files, then it could just test for read file/execute directory access on the installed package's ServerRoot. The php-fpm package could then use whatever UID/GID it wanted, and create. If it must use an httpd server's UID/GID, then it may need to search for whatever is installed, and default to http.

**Comment by the-eater** [comment]
While maybe a bit "rude" this is something that the user themselves have to configure imo and is not really something Void can do anything about since e.g. nginx and apache2 or whatever FastCGI server you use will have a different user,

we only could fix this if we unite all our web server users under www but idk if that's exactly desired

**Comment by LeamHall** [comment]
**the-eater**, your comment is not rude at all. No worries. My main concern is ERROR projects the image that the program did something Void could not handle. Is there a way for the FPM install to check for existing httpd accounts, or to post a response that FPM needs to be owned by the httpd process owner? Does it actually need that? I don't know the program.
