### ISSUE TITLE
Plasma - Font Management, the shared library was not found

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#31434]
### System

* xuname:  
  *Void 5.11.22_1 x86_64-musl GenuineIntel uptodate rFF*
* package:  
  *affected package(s) including the version*: ``plasma-desktop-5.22.0_2``

### Expected behavior

Font management appears.

### Actual behavior

Font management does not appear.

![Screenshot_20210612_170518](https://user-images.githubusercontent.com/45872139/121772588-6aaf2080-cba0-11eb-8ad7-3000a0639f46.png)

### Steps to reproduce the behavior

Update to plasma 5.22.0

**Comment by hervyqa** [comment]
Hi @Johnnynator

**Comment by Johnnynator** [comment]
There is an upstream patch available. Will push a fix in a bit.

**Comment by hervyqa** [comment]
woow. thank youuu @Johnnynator
