### ISSUE TITLE
[Feature request] Enabling appmenu (Global Menu) in Firefox 89

### ISSUE THREAD

**Issue by MPC7500** [void-linux/void-packages#31466]
Is it possible to merge the patch-set of the AUR for Firefox to the Void repository?
https://aur.archlinux.org/packages/firefox-appmenu/

**Comment by Duncaen** [comment]
We usually don't patch in features unless its really necessary. This patches is 5k lines long and we are already heavily patching firefox to just get it running on all platforms, I don't think adding more and even bigger patches is a good idea.

**Comment by ericonr** [comment]
Agreed. We have 691 lines of build fixes, 5k lines on top that will have to be rebased ever so often for something that mozilla upstream already removed for *some* reason doesn't sound good to me.

Closing for now.
