### ISSUE TITLE
telegram-desktop should install qt5-styleplugins

### ISSUE THREAD

**Issue by dm17** [void-linux/void-packages#31501]
I didn't have dbus working properly because I wasn't starting my window manager using dbus-launch (I didn't realize that). I had a work around ```TDESKTOP_USE_GTK_FILE_DIALOG=1``` in ```/etc/environment``` to get a proper file dialog in telegram-desktop. When I got dbus working properly this work around stopped working (crapping file dialog without search came back). I also got this warning when launching telegram:
``` Telegram-WARNING ** Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset. This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.```

So I checked to see which package qgtk2 is provided by and found: ```qt5-styleplugins```. Now that I have installed that telegram-desktop's file dialog works fine again. Perhaps it should be installed automatically?
Thanks!

**Comment by ericonr** [comment]
@Johnnynator 

I guess you can make a PR as well :)

**Comment by Johnnynator** [comment]
No `qt5-styleplugins` isn't a dep whatsoever. The "Warning" is normal.

So your actual issue was, that the file menu isn't working ootb without dbus?

**Comment by ericonr** [comment]
@dm17 ping on issue

**Comment by dm17** [comment]
> @dm17 ping on issue

Sorry I forgot. One of these got it working again:
```
TDESKTOP_USE_GTK_FILE_DIALOG=1
TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY=1
QT_QPA_PLATFORMTHEME=gtk3
```

Haven't messed with them since
