### ISSUE TITLE
dependants of libnma need to be rebuilt at each libnma update

### ISSUE THREAD

**Issue by curiousgay** [void-linux/void-packages#31510]
```nm-connection-editor: /usr/lib/libnma.so.0: version `libnma_1_8_28' not found (required y nm-connection-editor)```

**Comment by ericonr** [comment]
@cinerea0 sounds good?

@curiousgay if you could open a PR to revbump them and add a comment to `libnma` about this requirement, that'd be great.

**Comment by cinerea0** [comment]
Just making sure, does this mean that after every `libnma` update, all of the packages that depend on it need a revbump? If so, I can update the `libnma` template with that comment. I can also cover the dependent packages if curiousgay doesn't feel up to it.

**Comment by sgn** [comment]
@curiousgay What is your version of `libnma`, `libnma_1_8_28` is provided by `libnma-1.8.30_3`

**Comment by sgn** [comment]
And, I can run `nm-connection-editor` fine just now!

**Comment by curiousgay** [comment]
@sgn strange, I had the same version today, I guess it's caused by me automatically pulling network-manager-applet-devel, I've seen the error because there already was some shared library in the path, but anyway I'm using ConnMan now
@cinerea0 yes, please do it, I'm busy preparing to move to city this week

**Comment by sgn** [comment]
`network-manager-applet-devel` shouldn't be used, it should be purged from repo.

So, no action should be done.
