### ISSUE TITLE
Mutter downgrade RSA signature is not valid

### ISSUE THREAD

**Issue by thegarlynch** [void-linux/void-packages#31535]
### System

* package:  
  *affected package(s) including the version*: mutter 40.1.1

### Expected behavior
It works

### Actual behavior
mutter-40.1_1: verifying RSA signature...
ERROR: mutter-40.1_1: the RSA signature is not valid!
ERROR: mutter-40.1_1: removed pkg archive and its signature.

### Steps to reproduce the behavior
sudo vpm up or xbps-install -Su mutter

**Comment by ahesford** [comment]
This should be fixed by https://github.com/void-linux/void-packages/commit/432c319069613644905f8b9fb1830ab9d28e8b0d and will hit your local mirror soon.
