### ISSUE TITLE
clifm

### ISSUE THREAD

**Issue by deepaknegilachu** [void-linux/void-packages#31557]
hi  void team 

please consider adding clifm to repo.

**Comment by FollieHiyuki** [comment]
Can you provide links to the source code, the home page, licenses, etc..

I can look into packaging it if it meets the quality requirements, and is interesting to maintain.

**Comment by deepaknegilachu** [comment]
source "https://github.com/leo-arch/clifm/tree/master/src"

homepage "https://github.com/leo-arch/clifm"


lisense "https://github.com/leo-arch/clifm/blob/master/LICENSE"

**Comment by FollieHiyuki** [comment]
You can ask the author to support musl.

**Comment by ericonr** [comment]
Not very keen on packaging this https://github.com/leo-arch/clifm/blob/dcc5bb09b4969a45df15dfe908418a74f40a2a9e/src/main.c#L366
