### ISSUE TITLE
When installing any gnome application, a warning about obsolete paths appears.

### ISSUE THREAD

**Issue by Resoluto** [void-linux/void-packages#31568]
I tried to install some gnome packages like nautilus and gnome-shell and both are path warning.

## This is the warning when installing nautilus:

`Refreshing GSettings database from usr/share/glib-2.0/schemas... Aviso: Esquema “org.freedesktop.ibus” possui caminho “/desktop/ibus/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.freedesktop.ibus.general” possui caminho “/desktop/ibus/general/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.freedesktop.ibus.general.hotkey” possui caminho “/desktop/ibus/general/hotkey/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.freedesktop.ibus.panel” possui caminho “/desktop/ibus/panel/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.freedesktop.ibus.panel.emoji” possui caminho “/desktop/ibus/panel/emoji/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.locale” possui caminho “/system/locale/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.proxy” possui caminho “/system/proxy/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.proxy.http” possui caminho “/system/proxy/http/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.proxy.https” possui caminho “/system/proxy/https/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.proxy.ftp” possui caminho “/system/proxy/ftp/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.proxy.socks” possui caminho “/system/proxy/socks/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
done.`

## This is the warning when installing gnome-shell:

`Refreshing GSettings database from usr/share/glib-2.0/schemas... Aviso: Esquema “org.freedesktop.ibus” possui caminho “/desktop/ibus/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.freedesktop.ibus.general” possui caminho “/desktop/ibus/general/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.freedesktop.ibus.general.hotkey” possui caminho “/desktop/ibus/general/hotkey/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.freedesktop.ibus.panel” possui caminho “/desktop/ibus/panel/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.freedesktop.ibus.panel.emoji” possui caminho “/desktop/ibus/panel/emoji/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.crypto.pgp” possui caminho “/desktop/gnome/crypto/pgp/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.locale” possui caminho “/system/locale/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.proxy” possui caminho “/system/proxy/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.proxy.http” possui caminho “/system/proxy/http/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.proxy.https” possui caminho “/system/proxy/https/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.proxy.ftp” possui caminho “/system/proxy/ftp/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
Aviso: Esquema “org.gnome.system.proxy.socks” possui caminho “/system/proxy/socks/”. Caminhos iniciando com “/apps/”, “/desktop/” ou “/system/” são obsoletos.
done.`

Warnings appear when Update MIME database. This is normal ?

**Comment by paper42** [comment]
This is normal and can be ignored.

**Comment by sgn** [comment]
Please report them to upstream. This is normal.
