### ISSUE TITLE
Any support for rootless docker ? 

### ISSUE THREAD

**Issue by thegarlynch** [void-linux/void-packages#31566]
https://docs.docker.com/engine/security/rootless/

**Comment by CameronNemo** [comment]
Did you try it and hit any issues?

**Comment by thegarlynch** [comment]
I try it, but i prefer the package to be downloaded with simple xbps to update

**Comment by Duncaen** [comment]
Have you tried setting up the docker package? All the requirements should be met, nothing should not make it work if you configure it accordingly.

**Comment by thegarlynch** [comment]
Did i have to made new package and push it ? or is it already working with current docker package in void repo

**Comment by Duncaen** [comment]
No its part of docker.

**Comment by thegarlynch** [comment]
rootless docker instruction requires new docker package installed, as it mention here https://docs.docker.com/engine/security/rootless/

**Comment by Duncaen** [comment]
The install section refers to the normal docker package. But ok, lets just say its not supported and someone has to try it out, fix and document how to set it up.

**Comment by thegarlynch** [comment]
Sorry, i think i have warped view about how docker-rootless worked. Even if we go debian way a.k.a making docker-rootless-installer available on ``/bin/``  and automatically put systemd service for rootless docker. Void runit still didn't have a conventional way to run user service.

**Comment by zdykstra** [comment]
There are step-by-step directions to running rootless docker with out systemd in the link you've provided. There are [user-level services in Void](https://docs.voidlinux.org/config/services/user-services.html). It looks like it should "just work" on Void.

**Comment by thegarlynch** [comment]
Ok. i finally get it work. 

```sh
#!/bin/sh

export USER="<<user>>"
export HOME="/home/<<user>>"

exec chpst -u "<<user>>" env XDG_RUNTIME_DIR="/run/user/1000" env DOCKER_HOST="unix:///run/user/1000/docker.sock" env PATH="/home/<<user>>/bin:$PATH" /home/<<user>>/bin/dockerd-rootless.sh
```

also, set /etc/security/pam_env.conf

```
DOCKER_HOST     DEFAULT=unix:///${XDG_RUNTIME_DIR}/docker.sock
PATH            DEFAULT=${HOME}/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
```

if only runit is able to run a service only after login (with USER and HOME environment being set). i could made a package out of this
