### ISSUE TITLE
`ibus-setup` requires python3-gobject

### ISSUE THREAD

**Issue by avoidr** [void-linux/void-packages#3156]
`ibus-setup` does not start unless `python3-gobject` is installed.
```
$ ibus-setup
Traceback (most recent call last):
  File "/usr/share/ibus/setup/main.py", line 33, in <module>
    from gi import require_version as gi_require_version
ModuleNotFoundError: No module named 'gi'
```

package: `ibus-1.5.19_1`

**Comment by cr6git** [comment]
No, no problem for me on x86_64-musl.
`ibus` already depends on `python-gobject`, see the [template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/ibus/template#L15)...

**Comment by Johnnynator** [comment]
@cr6git `python-gobject` is wrong it has to be `python3`

**Comment by avoidr** [comment]
@Johnnynator has got it right.

I use x86_64-musl, too.

**Comment by avoidr** [comment]
If anybody is doing this, #3157 is related. I see `librsvg` in the `ibus` template, so maybe that belongs here and not `ibus-hangul`? However, `ibus-setup` works fine for me without `librsvg`, but `ibus-setup-hangul` does not work for me without it.

**Comment by cr6git** [comment]
@maxice8 what do you think about this issue?

**Comment by asergi** [comment]
`python2` was disabled by this [commit](https://github.com/void-linux/void-packages/commit/45af6655ff7c96045872c78909a5b3a04de844b4), but the dependencies are still the same.

**Comment by CameronNemo** [comment]
Is this still an issue?

**Comment by avoidr** [comment]
Yes, this is still an issue. The correct/missing dependency is `python3-gobject`.

**Comment by CameronNemo** [comment]
AFAIK the package was changed to use python2. Is this not the case?

**Comment by avoidr** [comment]
Sorry, indeed, I missed a revbump. `ibus-setup` now works with `python3-gobject` not installed.
