### ISSUE TITLE
okular with speech-dispatcher support

### ISSUE THREAD

**Issue by zenny** [void-linux/void-packages#31608]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
```
$ xuname
Void 5.4.124_1 x86_64 AuthenticAMD uptodate hold rrrmFFFFF
```
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
```
$ xbps-query -p pkgver okular
okular-21.04.2_1
```
### Expected behavior

Okular ought to detect the TTS engine under `Settings-> Configure Okular -> Accessibility -> Text-to-Speech engine` when engines like espeak, mimic or rhvoice  are installed.

### Actual behavior
 `Settings-> Configure Okular -> Accessibility -> Text-to-Speech engine`  is unselectable in okular.

### Steps to reproduce the behavior

1. Install okular and TTS engines:

`xbps-install -S okular espeak mimic speech-dispatcher qt5-speech python3-PyQt5-multimedia qt5-multimedia`

2. Open okular
3. Go to `Settings-> Configure Okular -> Accessibility -> Text-to-Speech engine` 
4. You would see something like below in the screenshot:

![pic-selected-210622-1048-48](https://user-images.githubusercontent.com/1653166/122894671-b0f64380-d347-11eb-93be-21f4fa13a951.png)

A relevant post related to rhvoice is in #26349 and in https://github.com/RHVoice/RHVoice/discussions/320

**Comment by zenny** [comment]
@Johnnynator Would you mind having a look? Thanks in advance.

**Comment by Johnnynator** [comment]
The issue should be, that our current qt5 build misses speech dispatcher (and flite) support. Which honestly makes Qt TextToSpeech pretty useless.
I will add the speech dispatcher and flite plugins with the next qt5 release.

**Comment by Johnnynator** [comment]
I added `qt5-speech-plugin-speechd` and `qt5-speech-plugin-flite` subpackages to `qt5-speech`. Installing `qt5-speech-plugin-speechd` should resolve your problem

**Comment by zenny** [comment]
> I added `qt5-speech-plugin-speechd` and `qt5-speech-plugin-flite` subpackages to `qt5-speech`. Installing `qt5-speech-plugin-speechd` should resolve your problem

@Johnnynator Thanks for your prompt feedback and action. :+1: 

BTW, I could not figure out one use a TTS engine to use with `speech-dispatcher`  in `okular` with the new plugin you contributed to which is equivalent to ` spd-say -e -o rhvoice -w`!

**Comment by Johnnynator** [comment]
> BTW, I could not figure out one use a TTS engine to use with `speech-dispatcher` in `okular` with the new plugin you contributed to which is equivalent to ` spd-say -e -o rhvoice -w`!

Take a look at `spd-conf` or `~/.config/speech-dispatcher/speechd.conf`
