### ISSUE TITLE
Latte Dock doesn't work anymore on Plasma 5.22, need to update to 0.9.12

### ISSUE THREAD

**Issue by hrqmonteiro** [void-linux/void-packages#31613]
![test22222](https://user-images.githubusercontent.com/17055027/122949284-e9028400-d351-11eb-9fcf-00a6010c2c6d.png)

It just doesn't work anymore, the package is too old. Needs to be updated to 0.9.12

And Latte is impossible to compile from source, so the users of Void need the package to be updated.

**Comment by ericonr** [comment]
I don't think that version is out yet? I only see 0.9.11 in https://phabricator.kde.org/source/latte-dock/tags/master/

> And Latte is impossible to compile from source

What do you mean by this?

@gspe

**Comment by Johnnynator** [comment]
https://download.kde.org/stable/latte-dock/latte-dock-0.9.12.tar.xz

0.9.12 does exist
