### ISSUE TITLE
Aegisub-3.2.2_12 doesn't load any audio

### ISSUE THREAD

**Issue by pudiva** [void-linux/void-packages#31637]
### System

```
$ xuname
Void 5.12.10_1 x86_64 GenuineIntel uptodate rrrrmdFFFFFF
$ xbps-query -p pkgver Aegisub
Aegisub-3.2.2_12
$ xbps-query -p pkgver libffms2
libffms2-2.40_1
```
### Expected behavior

Opening mp4, avi, mov, wav, mp3 or anything else that has audio should work.

### Actual behavior

FFmpeg says there are no audio frames:

![image](https://user-images.githubusercontent.com/1148648/123142234-1c780800-d451-11eb-83b4-c2f1b460cd4f.png)

> None of the available audio providers have a codec available to handle
> the selected file.
> 
> The following providers were tried:
> 
> FFmpegSource: Failed to open audio track: Audio track contains no
> audio frames

### Steps to reproduce the behavior

Run Aegisub and try to open a file that has audio in it (such as mp4, avi, mov, wav, mp3, ...)

**Comment by ericonr** [comment]
We should consider moving to https://github.com/wangqr/Aegisub

**Comment by pudiva** [comment]
> We should consider moving to https://github.com/wangqr/Aegisub

I just built that fork and it works. I'll put a template together soon. :)

**Comment by pudiva** [comment]
Just FYI, I'm working on packaging the wangqr fork, but it hasn't been easy. I'll post a PR as soon as possible. ;)

**Comment by ericonr** [comment]
Feel free to make a WIP PR, if you have specific questions.

**Comment by pudiva** [comment]
I just submitted a PR: #32162
