### ISSUE TITLE
[RFC] Split php package into php7 and php8

### ISSUE THREAD

**Issue by the-eater** [void-linux/void-packages#31678]
Currently we only provide one leading php version which is currently pinned at php 7.4 (the latest supported version of php 7)

this has generally not been a problem since the migration from php 5.6 to php 7.0 was rather painless, however with php 8 this is not as painless and because of new features and changes in behavior loads of projects may or will be broken.

but php 8 is currently the leading version (and also i want to play with it) and waiting for adoption seems a bit misguided and annoying for everyone (me) wanting to adopt php 8.

To resolve this situation I am proposing the following

- [ ] Move `php` to `php7`
- [ ] Create xbps-alternatives group for php which symlinks the correct folders and binaries
- [ ] Create new `php8` package
- [ ] Copy and move all php extensions to `php7` and `php8` prefixed packages (these are `xdebug`, `php-apcu`, `php-ast`, `php-igbinary` and `php-imagick`)
- [ ] Provide a wrapper script for `pecl` (from the new `pear` package) (`pecl7` and `pecl8`) which sets the correct program suffix for compiling pecl extensions

both php versions will have matching postfixes e.g. `php7` will provide `php7` and it's config files will live in `/etc/php7` etc.

If we do migration of `php` -> `php7` correctly there should be no conflicts, we can move the `/etc/php` to `/etc/php7` directory if present.

php packages directly affected:

`phpMyAdmin` and `ampache`: DIY hosting package, so can be kept an exercise to the reader
`phoronix-test-suite`: We need to check for php8 support, if there is none we can pin and patch it to use php7
`composer`: Works on both php7 and php8 so can be kept as is
`pear` (replaces php-pear): Works on both php7 and php8 and can be mostly kept as is except the pecl part, which is explained in my TODO list
`php-*`: Are all bundled extensions with the exception of the items listed above, but these can all be migrated alike php
`xdebug`: Non-bundled extension but can me migrated alike the other extensions

Before I do any of this I would like some feedback if this the correct way forward or if there's a better way to do so

/cc @paper42 (because you raised this issue)

Fuck I am basically back at doing the shit I did at my first job

**Comment by Chocimier** [comment]
Sounds good with exception of

> move the `/etc/php` to `/etc/php7`

This is breaking change for people who maintain configuration in /etc/php, same for custom modules in /usr.
Similar postgresql upgrade was done by leaving old series under old name and paths, until it reach EOL.

**Comment by the-eater** [comment]
I was thinking of making that folder part of the xbps-alternatives, so it stays consistent for everything?

**Comment by the-eater** [comment]
I will say that it's the part I have most trouble with getting a good solution for. the config has no breaking changes and can be carried over from php7 -> php8 and once we go EOL it might be desirable to just copy it over to give an easy transition

**Comment by Duncaen** [comment]
> I was thinking of making that folder part of the xbps-alternatives, so it stays consistent for everything?

With configuration files if they are changed xbps won't delete the configuration file and therefor won't be able to delete the directory, xbps would not error out because it currently does not take alternatives into account for file checks, but if it would do that it would simply error out saying that the "type" of `/etc/php` changed from directory to symlink, but it is not able to delete the directory because it contains files not removed by any package.

**Comment by the-eater** [comment]
> With configuration files if they are changed xbps won't delete the configuration file and therefor won't be able to delete the directory. xbps would not error out because it currently does not take alternatives into account for file checks.

you're gonna want to kill me but, 
that's something quite easily resolved in a INSTALL script right?

**Comment by Duncaen** [comment]
Thats tricky, not exactly sure how it would behave, if you move it in pre-INSTALL into a place where xbps did not consider the file previously as configuration file and then might just overwrite it.

https://github.com/void-linux/xbps/blob/4a5eb8dc87cf08ad919ec6602ef5a70e8514710c/lib/package_config_files.c#L127

**Comment by Chocimier** [comment]
What usage scenarios are targeted?

Running at most one php at same time?
Running both at same time with same config file (looks limiting, as there are include_path and extension_dir there)?
Running both at same time with different config files?

**Comment by the-eater** [comment]
:heavy_check_mark: Running at most one php at same time?
:heavy_multiplication_x: Running both at same time with same config file (looks limiting, as there are include_path and extension_dir there)?
:heavy_check_mark: Running both at same time with different config files?

running both at the same time with same config file would cause issues

There's case you want to run php7 and php8 alongside when e.g. developing for a platform that hasn't migrated yet to php8

**Comment by jonagoldman** [comment]
Any hope to get this merged? 
I have being building PHP 8.0 from source since its release (November 2020) but always struggled to get a perfect build.
Version 8.1 is coming soon and would love to finally have at least version 8.0 straight from Void.
Thanks.

**Comment by MrFastDie** [comment]
Same for me. I work on a daily basis with PHP and I would love to get this in the repositories. Are there any hopes for it to happen?

**Comment by jchook** [comment]
> Before I do any of this I would like some feedback if this the correct way forward or if there's a better way to do so

You could publish a separate PHP repository, e.g. structured similar to [Ondřej Surý's](https://deb.sury.org/).

Then the main void-packages repository can keep it simple, ideally updating to PHP 8.x before [28 Nov 2021](https://www.php.net/supported-versions.php).

**Comment by jchook** [comment]
Note PHP 7 will be EOL in less than a year from now

**Comment by TinfoilSubmarine** [comment]
Has there been any progress on this? I'd like to help out with this if anything is needed. I had a PHP app that required 8.0 so I manually updated the needed packages and am using them successfully.
