### ISSUE TITLE
Service "deluged" won't get/set its config files from /var/lib/deluge/.config/deluge but from /root/.config/deluge

### ISSUE THREAD

**Issue by jfcolom** [void-linux/void-packages#31690]
### System

* package:  
  *deluge-2.0.3_10

### Expected behavior

`deluged` service should start up with `deluge` system user, and therefore, get/set its configuration files from  /var/lib/deluge/.config/deluge

### Actual behavior

It is starts with `root` and, therefore, it gets/sets the configuration from /root/.config/deluge. As it cannot write there after that, there are some permission errors and it does not start properly.

### Workaround

In `/etc/sv/deluged/run`, replace

`exec deluged -d -U deluge -g deluge ${OPTS} 2>&1`

by

`exec chpst -u deluge:deluge deluged -d -U deluge -g deluge ${OPTS} 2>&1`

**Comment by sgn** [comment]
I think we can go further to move config to `/var/lib/deluge`, without `.config/deluge` part. Please check.

**Comment by jfcolom** [comment]
Thanx!

**Comment by q66** [comment]
this is a bad fix, it broke my use case (i override the user it is started as, with /etc/sv/deluged/conf, but the chpst to unprivileged user means it can't change user on its own later)

**Comment by q66** [comment]
@sgn the proper fix is to keep things as they were, but pass `-c /var/lib/deluge` before `${OPTS}`

**Comment by sgn** [comment]
Maybe this https://github.com/void-linux/void-packages/pull/32357

**Comment by sgn** [comment]
Hm, keep things as it were shouldn't work at all https://github.com/deluge-torrent/deluge/commit/d08c3f72e94a3a2b440b5a1a36dd8f7f8641d4fa

**Comment by jfcolom** [comment]
``deluged`` is now getting its configuration from /var/lib/deluge/.config instead of /var/lib/deluge/.config/deluge
This breaks ``deluge-web`` service or, at any rate creates some inconsistency, as deluge-web gets its configuration from /var/lib/deluge/.config/deluge.

**Comment by sgn** [comment]
> `deluged` is now getting its configuration from /var/lib/deluge/.config instead of /var/lib/deluge/.config/deluge
> This breaks `deluge-web` service or, at any rate creates some inconsistency, as deluge-web gets its configuration from /var/lib/deluge/.config/deluge.
> 
> Workaround: in /etc/sv/deluged/run, set the configuration path
> ` exec deluged -d -U deluge -g deluge -c /var/lib/deluge/.config/deluge ${OPTS} 2>&1`

Fixed, :( programming is hard.

**Comment by jfcolom** [comment]
Thanks
