### ISSUE TITLE
"GNOME Fonts" has no desktop launcher

### ISSUE THREAD

**Issue by rivanfebrian123** [void-linux/void-packages#31730]
### System

* xuname:  
  * Void 5.12.13_1 x86_64-musl GenuineIntel notuptodate rFF
* package:  
  * gnome-font-viewer

### Expected behavior
**EDIT:** It has the launcher

### Actual behavior
**EDIT:** No launcher

### Steps to reproduce the behavior
**EDIT:** Install the package

**Comment by not-chicken** [comment]
`gnome-font-viewer`?

**Comment by rivanfebrian123** [comment]
Oh yeah, you're right. That was confusing tho...

I thought `gnome-font-viewer` is just the viewer (installer) for individual font because it's already installed in my system, but it has no launcher. 

![Screenshot from 2021-07-01 14-18-41](https://user-images.githubusercontent.com/6300910/124083083-a8081f00-da77-11eb-9d65-81639a4b1f5b.png)

![Screenshot from 2021-07-01 14-18-51](https://user-images.githubusercontent.com/6300910/124083645-52804200-da78-11eb-95e1-d0d360d1fa58.png)

I think I need to update this issue

**Comment by rivanfebrian123** [comment]
Thank you guys!
