### ISSUE TITLE
usbguard missing directory preventing service to start up. resulting in any usb to be recognized automatically.

### ISSUE THREAD

**Issue by wibed** [void-linux/void-packages#31768]
### System

* xuname:  
Void 5.12.10_1 x86_64-musl AuthenticAMD notuptodate rrFFF

* package:  
pkgver: usbguard-1.0.0_3

### Expected behavior
after install, started service running seamlessly

### Actual behavior
fails silently in the background

### Steps to reproduce the behavior
xbps-install -Syu usbguard
ln -s /etc/sv/usbguard /var/service/
sv restart usbguard

the error message indicates a missing directory in /etc/usbguard
/etc/usbguard/IPCAccessControl.d

the installation candidate does not setup this directory by itself.

### WORKAROUND
just create the directory as root and usbguard will start as expected

**Comment by amak79** [comment]
This is caused by `xbps-src` removing empty directories during post-install.
```
=> usbguard-1.0.0_3: running post-install hook: 03-remove-empty-dirs ...
=> WARNING: usbguard-1.0.0_3: removed empty dir: /var/log/usbguard
=> WARNING: usbguard-1.0.0_3: removed empty dir: /var/log
=> WARNING: usbguard-1.0.0_3: removed empty dir: /var
=> WARNING: usbguard-1.0.0_3: removed empty dir: /etc/usbguard/IPCAccessControl.d
```
I fixed this by adding the directory to `make_dirs`. The template already does this for `/var/log/usbguard`. I can make a pull request, but I would like to get a comment from a dev first.
