### ISSUE TITLE
Package request: qt5-linguist

### ISSUE THREAD

**Issue by unresolvedsymbol** [void-linux/void-packages#31810]
I see more and more projects using this dependency, and almost every other distro has this in their main repos. Fortunately some will blow it off as a warning but unfortunately some aren't as lenient.

**Comment by sgn** [comment]
Which Qt5 tools do you mean? Did you mean `linguist`, which is provided by `qt5-tools`?

**Comment by unresolvedsymbol** [comment]
@sgn Ahh, you're correct. I wasn't aware it was included in that, as I was thinking of the package available on RHEL-based distros.
