### ISSUE TITLE
Different plasma-shell patch version 

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#31839]
### System

* xuname:  
  *Void 5.12.14_1 x86_64 GenuineIntel uptodate rFF*
* package:  
  *affected package(s) including the version*: ``plasma-desktop-5.22.2_1``

### Expected behavior
same version `5.22.2`

`plasma-desktop-5.22.2_1`
`plasmashell 5.22.2`

### Actual behavior
`plasma-desktop-5.22.2_1`
but `plasmashell 5.22.1` (patch version is `.1` not `.2`)

![Screenshot_20210707_140047](https://user-images.githubusercontent.com/45872139/124715114-ce710300-df2c-11eb-99fb-cd02d21df0ad.png)

![2021-07-07_13-28](https://user-images.githubusercontent.com/45872139/124715766-89010580-df2d-11eb-8434-c733db70a696.png)

![2021-07-07_13-26](https://user-images.githubusercontent.com/45872139/124714981-a386af00-df2c-11eb-8d24-d1b9db94a6eb.png)

### Steps to reproduce the behavior
update latest kde plasma from repo

**Comment by Johnnynator** [comment]
Yeah, a I'm aware. This was a problem with the 5.22.2 upstream tarballs (and they fixed it in 5.22.2.1, but I don't see the point in recompiling everything just to get a version number correct)

The reported version number will also be correct again with 5.22.3 once it is in the Void repos.
