### ISSUE TITLE
Package Request: ROOT

### ISSUE THREAD

**Issue by uncomfyhalomacro** [void-linux/void-packages#31833]
#### Description

C++ data analysis framework and interpreter from CERN. It is an open-source data analysis framework used by high energy physics and others.

#### Homepage

https://root.cern/

#### LICENSE

[LGPL2](https://github.com/root-project/root/blob/master/LICENSE)

**Comment by jchook** [comment]
In the meantime looks like there's an up-to-date [Docker Hub image](https://hub.docker.com/r/rootproject/root) for ROOT

**Comment by BenJarg** [comment]
#34647

**Comment by jchook** [comment]
Also see the nvidia-docker PR https://github.com/void-linux/void-packages/pull/33059

**Comment by classabbyamp** [comment]
added in #34647
