### ISSUE TITLE
shotcut: No parameter controls visible for filters

### ISSUE THREAD

**Issue by klardotsh** [void-linux/void-packages#31830]
### System

* xuname:   Void 5.12.13_1 x86_64 AuthenticAMD notuptodate rrrmFFFFF
* package:  shotcut-21.01.29_1

### Expected behavior

Filters have controls to control parameters, for example, using the latest AppImage from upstream:

![screenshot-2021-07-06-02:11:11Z](https://user-images.githubusercontent.com/799439/124532155-d01fb700-ddc4-11eb-8656-993d413a7339.png)

### Actual behavior

No controls visible:

![screenshot-2021-07-06-02:07:51Z](https://user-images.githubusercontent.com/799439/124532097-b1b9bb80-ddc4-11eb-989b-4140f235c175.png)

### Steps to reproduce the behavior

Create a new project, add a clip, attempt to add any video filter to that clip. So far none that I've tried have any parameters, but if I save the project and reopen in the AppImage version, I can tweak those parameters. I don't see any log output indicating a failure to load a resource, and `ldd /usr/bin/shotcut` output shows no missing sofiles.

**Comment by paper42** [comment]
It works for me, so it's probably a missing runtime dependency.

**Comment by Johnnynator** [comment]
The missing dependency is `qt5-quickcontrols`

**Comment by klardotsh** [comment]
Thanks, folks!
