### ISSUE TITLE
Package Request: Sneedacity

### ISSUE THREAD

**Issue by rnbunker** [void-linux/void-packages#31845]
Sneedacity is an Audacity fork, without the telemetry, but also fixing many bugs, having an efficient development team

Project Home: [Sneedacity on GitHub](https://github.com/Sneeds-Feed-and-Seed/sneedacity)
License: GNU General Public License Version 2 and up

**Comment by sgn** [comment]
Why do you feel the need for VoidLinux to have this package included when you ain't using Void?

**Comment by sgn** [comment]
The consensus is we don't package fork.

**Comment by Vaelatern** [comment]
Unfortunately this is an expansion of the problem we have with browsers. We avoid bringing in forks of browsers since our builders would just spend all day doing that.

Until the project is more than "An Audacity fork with X, Y, Z", any template would probably be ignored.

**Comment by rnbunker** [comment]
> Why do you feel the need for VoidLinux to have this package included when you ain't using Void?

???
How do you want to know I am not using Void?

**Comment by Duncaen** [comment]
>  but also fixing many bugs, having an efficient development team

They did not fix anything and its just a bunch of trolls that updated the readme and some static assets.

This really does not deserve to be even discussed.
