### ISSUE TITLE
Fritzing package is too old (2016)

### ISSUE THREAD

**Issue by rivanfebrian123** [void-linux/void-packages#31850]
### System

* xuname:  
  * Void 5.12.14_1 x86_64-musl GenuineIntel notuptodate rFFF
* package:  
  * Fritzing-0.9.3b_5

### Expected behavior
Have the latest version of Fritzing: https://blog.fritzing.org/2021/02/23/new-fritzing-release-096

### Actual behavior
Still have the old one (2016)

![Screenshot from 2021-07-08 15-51-25](https://user-images.githubusercontent.com/6300910/124892813-67268200-e004-11eb-8d88-e6f57db32a6e.png)

### Steps to reproduce the behavior
```bash
git clone git://github.com/void-linux/void-packages.git
cd void-packages
./xbps-src binary-bootstrap
echo XBPS_ALLOW_RESTRICTED=yes >> etc/conf
xi Fritzing
```

**Comment by ahesford** [comment]
From the issue template:
> Don't request update of package. We have a script for that. https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt . However, a quality pull request may help.

**Comment by rivanfebrian123** [comment]
Sorry, didn't read that carefully :D
