### ISSUE TITLE
Package Request: ideviceinstaller

### ISSUE THREAD

**Issue by paoloschi** [void-linux/void-packages#3189]
__ideviceinstaller__ is a tool to interact with the installation_proxy 
of an iOS device allowing to install, upgrade, uninstall, archive, restore
and enumerate installed or archived apps.
https://github.com/libimobiledevice/ideviceinstaller

a little dated but still valid, needed to operate _mounts_ as described here: https://wiki.archlinux.org/index.php/IOS#Manual_mounting
all other necessary packages are already in the repository, only ideviceinstaller is missing

**Comment by paoloschi** [comment]
Well... I have never purchased (and never will) an apple product. My request was on behalf of a third party (an acquaintance that I'm re-educating, taking him -one step at a time- towards Void Linux ;-)). 
As soon as it will be possible to install ideviceinstaller with xbps-installer, I will ask and report here.

**Comment by cr6git** [comment]
@paoloschi it's done.

**Comment by paoloschi** [comment]
Nothing negative to report: the program runs as expected (the version released 1.1.0 prints an output well different formatted than the code now in master but still adequate to the functions required in the ArchWiki guide).
We have not been able to try the totality of the functions offered by the program but even if there were issues, I think these should be reported upstream rather than imputing them to the build obtained with your template....
Thank you so much for accepting and resolving my request!
