### ISSUE TITLE
acpi_call-dkms-1.2.0.3: fixing of script 'turn_off_gpu.sh'

### ISSUE THREAD

**Issue by abhocetabhac** [void-linux/void-packages#31901]
acpi_call-dkms-1.2.0.3

In script '/usr/share/acpi_call/turn_off_gpu.sh', the line

result=$(cat /proc/acpi/call)

causes a warning that spoils the functioning: "bash: line 41: warning: command substitution: ignored null byte in input¨.

The following amendment solves the issue:

result=$(cat /proc/acpi/call | tr '\0' '\n')

**Comment by ahesford** [comment]
Please submit this issue to acpi_call upstream. The script is just an example designed to help detect the right call; there's not a lot of value in Void maintaining a patch.
