### ISSUE TITLE
Cannot run Vulkan Instance

### ISSUE THREAD

**Issue by Eluminae** [void-linux/void-packages#31922]
Hello there,

I had a working setup with Vulkan some monthes ago and I now got issues:

```
$ vulkaninfo 
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 0.  Skipping ICD.
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at ../vulkaninfo/vulkaninfo.h:666:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
```

I'v followed https://docs.voidlinux.org/config/graphical-session/graphics-drivers/amd.html

Here is my packages :

```
$ sudo xbps-query -l | grep amd
ii amdvlk-2021.Q2.6_2                          AMD Open Source Driver For Vulkan
ii amdvlk-32bit-2021.Q2.6_2                    AMD Open Source Driver For Vulkan (32bit)
ii linux-firmware-amd-20210511_1               Binary firmware blobs for the Linux kernel - AMD CPU/GPU microcode
ii xf86-video-amdgpu-19.1.0_2                  Xorg AMD Radeon RXXX video driver (amdgpu kernel module)
$ sudo xbps-query -l | grep vulkan
ii vulkan-loader-1.2.178_1                     Vulkan Installable Client Driver (ICD) loader
ii vulkan-loader-32bit-1.2.178_1               Vulkan Installable Client Driver (ICD) loader (32bit)
```

My GPU is a AMD R 280 X.

Radeontop seems to works and display my GPU informations.

Does anyone can help me ?

```
$ uname -ra
Linux terminator 5.12.14_1 #1 SMP 1625102948 x86_64 GNU/Linux
```

```
$ ls /usr/share/vulkan/icd.d/
amd_icd32.json  amd_icd64.json
```

```
lspci -k
...
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
	Subsystem: ASUSTeK Computer Inc. Device 3004
	Kernel driver in use: amdgpu
...
```

**Comment by Johnnynator** [comment]
Generally it is recommended to use `mesa-vulkan-radeon` over `amdvlk`.
I will take a look later where amdvlk breaks without having mesa installed.

**Comment by Eluminae** [comment]
I had issues with `mesa-vulkan-radeon` and I findout that using `amdvld` and removing `mesa-vulkan-radeon` solved them. It may changed with time

**Comment by Eluminae** [comment]
It looks like installing `mesa-vulkan-radeon` and removing `amdvld` fixed my issue

**Comment by biopsin** [comment]
@Eluminae  Please close if its resolved?

**Comment by Johnnynator** [comment]
@biopsin This is only a "workaround" and doesn't fix the issue that amdvlk doesn't work standalone (or smth else). So no keep open.

**Comment by Johnnynator** [comment]
Ok, the issue is simple, amdvlk only supports `RX` cards, a `Radeon HD 7970/8970 OEM / R9 280X` is too old.
