### ISSUE TITLE
Intermittent bug in Firefox 88+ on x64/musl

### ISSUE THREAD

**Issue by thamesynne** [void-linux/void-packages#31933]
### System

* xuname:  Void 5.11.22_1 x86_64-musl GenuineIntel notuptodate rFF
* package:  firefox-89.0.2_1             (but has been observed since at least Firefox 88)
* X server: Xvnc provided by tigervnc-1.10.1_3

### Expected behavior

Not the actual behaviour...

### Actual behavior

When right clicking to bring up a context menu, or dropping down a selection box, occasionally Firefox will spawn a new process, which doesn't do anything useful but does block at least Firefox, and sometimes the entire X server. Manually killing this process unfreezes everything, allowing the session to continue.

No error output appears from Firefox to suggest what's gone wrong.

Other than the fact that it results from Firefox dropping down a menu, I can see no pattern to why it occurs. Sometimes it happens with every 3rd or 4th right click, sometimes an entire session will pass without it happening.

I have greated a 32-bit glibc chroot and tested Firefox-i686 in that environment; the bug does not seem present there. Has Firefox grown an incompatibility with musl?

### Steps to reproduce the behavior

Bug is intermittent - see above.

(I apologise for not being able to provide more detail.)

**Comment by ericonr** [comment]
Doesn't seem to be an issue on Wayland, fwiw.

**Comment by dkwo** [comment]
I'm seeing a similar behaviour since today.
It now spawns hundreds of processes in htop.

**Comment by thamesynne** [comment]
First, i do a `ps ax | grep fire`; that gives me a list of candidates.  Usually there are just two with the command line 'firefox' (without any options), and between them are lots of subprocesses with very long command lines full of options. Mostly it's the one with the higher PID that needs killing - unless there are no subprocesses between those two; then the PIDs have wrapped and the lower one needs to be killed.

I think that heuristic has only steered me wrong once, and I was in a hurry that time.

(Having said which, I've only used the 32-bt glibc version since I created this bug report, and that doesn't exhibit the problem at all.)

**Comment by dkwo** [comment]
Thanks.
Something fun: today I'm using laptop as docked to external monitor, and I'm not able to reprodue the issue, which was happening all the time while on laptop only.
Could this have to do with some weird interaction firefox/xorg/drm-intel?

**Comment by vincele** [comment]
I have the same problem (for monthes now), and tried a few things to overcome it.
* self compiled-firefox, same bug happen.
* self compiled-firefox, stripped of a lot of things, same bug happen.

During those monthes, I got a few Void firefox updates, none fixed the problem.

Yesterday, I tried a x86_64-glibc chroot, and I've yet to see that bug showing up. On the musl system it randomly happens, sometimes instantly (at the first right-click that opens a contextual menu, in-html-page or on the FF UI itself)

**Comment by dkwo** [comment]
hmm, maybe try to exclude profile, by renaming firefox profile to e.g. firefox-old.
I can only say that I've never seen this issue on wayland (river), so maybe you could give that a try?

**Comment by vincele** [comment]
I'll continue to test with the glibc chroot to be sure. Then we'll see if I want to dig into this issue further.

**Comment by vincele** [comment]
BTW, someone on reddit reported something that looks like this:
https://www.reddit.com/r/voidlinux/comments/12fp1uf/firefox_frequently_freezes/

**Comment by snark-attack** [comment]
I reported that on Reddit, as announced I join this discussion. 
Void 6.2.8_1 x86_64-musl GenuineIntel uptodate rrnFF
firefox-111.0.1_1
xorg-server-21.1.8_1
dwm-6.4 (this is compiled w/o any patches)

btw: as of now, I also have problems using thunderbird and chromium
thunderbird-102.6.1_3
chromium-111.0.5563.64_1

**Comment by vincele** [comment]
My workaround:
* install chroot somewhere via xvoidstrap or rootfs tarball
* chroot into it as root
* install firefox & some fonts
* use `bwrap` (void bubblewrap) to launch firefox from the chroot (add `--bind /home /home` to the bwrap invokation to get access to your profile and .Xauthority)

**Comment by casualtyface** [comment]
Apologies, but has anyone discovered a workaround or solution for this issue?

**Comment by vincele** [comment]
@casualtyface, I see at least 2 different proposed workarounds in the few messages above (wayland & glibc chroot).

The problem with workarounds (that work) is that you then will not pursue proper bug fixing.

BTW, I can tell that I have not met that bug since using the glibc chroot, not even once. And there were a few firefox & other updates since Apr 9.
