### ISSUE TITLE
The path towards Ruby 3

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/void-packages#31955]
I would like to update Ruby to the new major release 3, and I'd rather not provide a package for 2.7 anymore.

This results in the following implications:
- According to Arch, they have 2.7 around for: facter, hiera, puppet, vagrant
- According to upstream, vagrant 2.2.17 should support Ruby 3.
- The puppet-related packages were not touched since 2019 (by @ndowens), which suggests they are not used.
- Only Puppet 7.8 has experimental support for Ruby 3.

Therefore I'll prepare a PR for Ruby 3 which removes Puppet, unless someone is interested in updating and maintaining them. All other uses of Ruby in Void should work with Ruby 3.

**Comment by kotoko** [comment]
I personally use puppet and wanted to show a workaround if someone else want to use puppet on void (with missing puppet in xbps repository).

1. First install ruby. After installation command `gem` will become available.

```
xbps-install ruby
```

2a. If you want install puppet system-wide run:

```
gem install puppet
```

And add this to your .bashrc file:

```
GEM_BIN_PATH=`(gem env | grep 'EXECUTABLE DIRECTORY' | sed --quiet "s/.*EXECUTABLE DIRECTORY: \(.*\)/\1/p")`"/bin"
export PATH="$GEM_BIN_PATH:$PATH"
```

2b. If you want to install in current user home directory run:

```
gem install --user-install puppet
```

And add this to your .bashrc file:

```
GEM_BIN_PATH=`(gem env | grep 'USER INSTALLATION DIRECTORY' | sed --quiet "s/.*USER INSTALLATION DIRECTORY: \(.*\)/\1/p")`"/bin"
export PATH="$GEM_BIN_PATH:$PATH"
```

3. Restart your shell. Done!

**Comment by Animeshz** [comment]
Thanks @kotoko! I needed puppet, but wasn't sure of using ruby-gem as it was nowhere mentioned in the docs, seems like latest puppet runs perfectly fine with gem.
