### ISSUE TITLE
Affiliation with ExpidusOS?

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#32019]
Hey,

I've come across https://expidusos.com/ while looking for PinePhone distros and wondered if we have any affiliation or connection to the project?

Maybe its worth contacting the project team and talk about hardware support, since that project plans to target more devices in the future?

https://wiki.expidusos.com/index.php/Supported_Devices

**Comment by sgn** [comment]
> I've come across https://expidusos.com/ while looking for PinePhone distros
> and wondered if we have any affiliation or connection to the project?

No, whatsoever,

> Maybe its worth contacting the project team and talk about hardware support,

@RossComputerGuy is there,

> since that project plans to target more devices in the future?

I don't trust his work ;)

**Comment by Anachron** [comment]
Why are we closing this? 

I think it can be beneficial to work together to support more devices for Void Linux.

**Comment by sgn** [comment]
Reopen as your will.

**Comment by paper42** [comment]
Void already supports the Pinephone. Other devices would probably have only 1 user and might require some device specific packages (custom kernel, uboot, etc.), so including them in Void wouldn't make much sense (even the Pinephone kernel in repositories is old). Having those packages in a separate repository like what ExpidusOS does would make more sense, but:

* it should be transparent (not have huge commits touching multiple packages with commit message "fix")
* it should upstream changes where possible

There are people interested in Void on a Pinephone, I know at least about @jcgruenhage and me, git log will probably tell you more. I have some updated packages in my own repository (the pinephone kernel, phosh, squeekboard...), but I wasn't able to properly test them yet, so I didn't make a PR.

**Comment by RossComputerGuy** [comment]
ExpidusOS has different goals than Void Linux. Void is only used as it's design is easier for cross compiling. More devices are supported because the OS is meant to support phones and desktops. Void is primarily a desktop OS. ExpidusOS also ships with a minimum set of packages in the repository because it is expected that users will use the application marketplace. A good analogy is Debian vs Ubuntu with their goals and intended users.

**Comment by Chocimier** [comment]
Neither party is interested, closing thread.
