### ISSUE TITLE
Blender does not find opencolorio (also at compiletime)

### ISSUE THREAD

**Issue by notthewave** [void-linux/void-packages#32012]
Blender does not find opencolorio and therefore filmic cant be used. I tried to find the cause of this problem and discovered that it's disabled at compile time because opencolorio-devel is not found. It's enabled in the template, though.

* xuname:  
  *Void 5.12.17_1 x86_64-musl GenuineIntel uptodate rDFFFF*
* package:  
  *affected package(s) including the version*: ``blender-2.93.0_1``

### Expected behavior
Blender finds opencolorio and can use the filmic

### Actual behavior
Blender does not find opencolorio and filmic can't be used
reports:
```
Color management: using fallback mode for management
Color management: Error could not find role data role.
```
on startup
### Steps to reproduce the behavior
run blender in the Terminal
look  at the output and see if the same errors are reported
to test filmic go to the Properties panel -> Render properties tab -> Colormamagement and see if there is a filmic option in the hamburger menus.

**Comment by biopsin** [comment]
Confirmed `Color management: scene view "Filmic" not found, setting default "Standard".`

**Comment by notthewave** [comment]
https://github.com/notthewave/void-packages/blob/opencolorio/srcpkgs/opencolorio/template
I worked on it a bit. compiles but fails with:
```
=> ERROR: opencolorio-2.0.1_1: /builddir directory is not allowed, remove it!
=> ERROR: opencolorio-2.0.1_1: cannot continue with installation!
```

**Comment by biopsin** [comment]
@notthewave I have updated https://github.com/biopsin/void-packages/commits/patch-1, its still a PITA to get it right; see if you can make something out of it..
also forgot to update shlibs for libOpenColorIO.so.2.0 opencolorio-2.0.2_1
conflog@https://p.teknik.io/xTnbp

**Comment by notthewave** [comment]
https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/1314

**Comment by notthewave** [comment]
https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1516 just got merged

**Comment by notthewave** [comment]
https://github.com/void-linux/void-packages/pull/32166

**Comment by notthewave** [comment]
New relase just droped:
https://github.com/AcademySoftwareFoundation/OpenColorIO

**Comment by notthewave** [comment]
I tried to compile the newest version but I get:
`ninja: error: loading 'build.ninja': No such file or directory`

**Comment by notthewave** [comment]
What sould we do with ilmbase? Its now in openexr and Imath. Remove it? Arch seems to have done just that.
I packaged Imath and updated openexr - but there seems to be something wrong with pytring cmake options 
when compiling opencolorio it complains:
```
/usr/bin/ld: /usr/lib/libpystring.a(pystring.cpp.o): warning: relocation against `_ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE' in read-only section `.text.unlikely'
/usr/bin/ld: /usr/lib/libpystring.a(pystring.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVSt9basic_iosIcSt11char_traitsIcEE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/OpenColorIO/CMakeFiles/OpenColorIO.dir/build.make:2741: src/OpenColorIO/libOpenColorIO.so.2.1.1] Error 1
make[1]: *** [CMakeFiles/Makefile2:1590: src/OpenColorIO/CMakeFiles/OpenColorIO.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
