### ISSUE TITLE
Issues in updating less to version 590_1

### ISSUE THREAD

**Issue by arun5309** [void-linux/void-packages#32030]
### System

* xuname:  
  
```
Void 5.12.17_1 x86_64 GenuineIntel notuptodate rrrmFFFF
```

* package:  

```  
less-581.2_1 
```
(this is working fine, having issues in updating it to version 590_1)

### Expected behavior

When, I run

```
sudo xbps-install -Su 
```

or
 
```
sudo xbps-install -Su less
```

I expect the less package to update (I already have it installed on my system). But it is showing me an error related to signature not found. Other, packages are updating fine (I updated pdfsandwich and xen-libs today without any issues).

### Actual behavior

Ouput of running

```
sudo xbps-install -Su less
```

```
Password: 
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...

Name Action    Version           New version            Download size
less update    581.2_1           590_1                  122KB 

Size to download:              122KB
Size required on disk:         320KB
Space available on disk:       608GB

Do you want to continue? [Y/n] y

[*] Downloading packages
ERROR: [trans] failed to download `less-590_1' signature from `https://alpha.de.repo.voidlinux.org/current': Not Found
Transaction failed! see above for errors.
```

### Steps to reproduce the behavior

run the command

```
sudo xbps-install -Su less
```

Thanks in advance! Also, this is my first time raising an issue here. So, my sincere apologies if I have failed to follow any of the contributing guidelines.

**Comment by ericonr** [comment]
https://voidlinux.org/news/2021/07/signing-disruption.html we are aware of it, but the fix has to wait.

No worries, it was an ok issue ;)
