### ISSUE TITLE
LXDE glibc iso appears to be  missing crda for wifi support

### ISSUE THREAD

**Issue by zzzghunter** [void-linux/void-packages#32138]
This issue is for the LXDE iso dated 18 Feb 2021 for the glibc edition 

### Expected behavior
Connect laptop wireless adapter to router

### Actual behavior
NetworkManager claims wifi is out of range. (When I am next to router)

dmesg reports an issue with wireless regulartory database

### Steps to reproduce the behavior
Iso installed on a laptop.
Update system packages
Install NetworkManager and enable that service, remove dhcpd service.

Use NetworkManager to input wifi passphrase

wifi then fails as above

#################
Installing crda resolved my issue

Forum post refers
https://www.reddit.com/r/voidlinux/comments/oom0lp/lxde_iso_appears_to_be_missing_crda

2) At this stage, this is a request to add a package to a future LXDE iso. No urgency expected.
I may be wrong. Feel free to tell me what parts of a dmesg you need to see or do you need to see a full message, when I remove crda?

3) I use Australian wifi and my actual device is a Intel Centrino Advanced N 6205
believed to be code named Taylor Peak

I am not a coder just an end user. 

thanks for reading

**Comment by sgn** [comment]
Your kernel version? `crda` isn't required in kernel 4.15+ See https://git.kernel.org/pub/scm/linux/kernel/git/mcgrof/crda.git/commit/?id=f4ef2531698fb9ba006e8b31a223b3269be8bc7c

**Comment by zzzghunter** [comment]
thanks for quick reply. First iso live k is 5.10.17-1 and this morning update over reboot is 5.12.19-1

As I do not disagree with your assertion, the fact that I needed crda suggests that specific iso was missing the firmware that includes the crda stuff. I do not know which one that is.

Luckily I did not clear my cache and the only fw updates are of the form
linux-firmware-something
and something is either amd, broadcom, intel, network and nvidia

dmesg suggests that my kernel module iwlwifi but I can see no update for that in my cache.

Lets close this now that I know a little more thanks

**Comment by sgn** [comment]
I said in kernel 4.15+, `crda` package is not required, because it's part of kernel. I didn't said firmware isn't necessary.

In normal situation, when you install `base-system`, those firmwares should be pulled by default, except when you're one of those minimalistic people, who purges every single packages from their system.

Your device is: Intel Centrino Advanced N 6205, so you need linux-firmware-network installed.
