### ISSUE TITLE
Any plans on updating Krita? (As seen (or not) on the forum)

### ISSUE THREAD

**Issue by MirceaMx** [void-linux/void-packages#3215]
Krita 4.1.3 has been released a while ago. Any plans on updating it? You can read the [announcement here](https://krita.org/en/item/krita-4-1-3-released/).

**Comment by MirceaMx** [comment]
Well? Any plans? The update was released 3 days ago!

**Comment by cr6git** [comment]
Yes, I'm working on it right now.
It takes time to build, please be patient.
You shouldn't have closed the issue.

**Comment by MirceaMx** [comment]
Sorry for closing the issue. Thank you.

**Comment by cr6git** [comment]
done.
