### ISSUE TITLE
Error while updating znc

### ISSUE THREAD

**Issue by kartikynwa** [void-linux/void-packages#32175]
### System

* xuname:  `Void 5.12.19_1 x86_64-musl GenuineIntel/VM uptodate hold rFFF`

* package:  `znc-1.8.2_6`

### Expected behavior

This happened when I ran an update using `sudo xbps-install -Su`. I think `znc` was being updated from `znc-1.8.2_5` to `znc-1.8.2_6`. I would have expected the update to run smoothly.

### Actual behavior

I received this error:

```
znc-1.8.2_5: updating to 1.8.2_6 ...
znc-1.8.2_6: unpacking ...
ERROR: znc-1.8.2_6: [unpack] failed to extract file `./etc/sv/znc/supervise': Directory not empty
ERROR: znc-1.8.2_6: [unpack] failed to extract files: Directory not empty
ERROR: znc-1.8.2_6: [unpack] failed to unpack files from archive: Directory not empty
Transaction failed! see above for errors.
```

### Steps to reproduce the behavior

I am not sure about this. Maybe try updating znc? I tried updating twice and got the same error.

### Notes

To update anyway, what I did was `sudo sv down znc`, then `sudo rm -r /etc/sv/znc/supervise` and then update. Had to reboot but `znc` worked fine post that.

There is this file in the `znc` folder in `srcpkgs`:

```
void-packages on  master
❯ ls -l srcpkgs/znc/files/znc/log/run
lrwxrwxrwx 1 kartik kartik 16 May 29 11:17 srcpkgs/znc/files/znc/log/run -> /usr/bin/vlogger*
```

Maybe this is the culprit? I am not sure.

EDIT: Nvm many packages have this file. Seems like it is not relevant to the problem.

**Comment by Duncaen** [comment]
This file has always been a symlink, for some reason it was deleted on your system (this has to be done by you, xbps nor runit would do that) and runit created the directory when it started the service and is now unable to change it back to a symlink because it does not delete user data out of directories.
