### ISSUE TITLE
GHC/Stack build failures on i686

### ISSUE THREAD

**Issue by ahesford** [void-linux/void-packages#32221]
First noticed building darcs:
https://build.voidlinux.org/builders/i686_builder/builds/33610/steps/shell_3/logs/stdio

Marking that broken to clear the log jam, it also tripped up on debug-me:
https://build.voidlinux.org/builders/i686_builder/builds/33611/steps/shell_3/logs/stdio

This seems like a widespread problem.

cc: @slotThe

**Comment by ericonr** [comment]
91261208422efc2ec7aabad986b4674849c1fc9e and 2a36c42b211b845b4667726559a3d3eb9dac496b will have to be reverted once this is fixed.

**Comment by ericonr** [comment]
```
02:43 <Solid> ahesford, q66: well that's not good...
02:46 <Solid> apparently this is an issue with lukko and one has to compile cabal with `-ofd-locking`
02:47 <Solid> meaning we'd probably need to re-build cabal and patch in the respective json template ( https://github.com/haskell/cabal/blob/master/bootstrap/linux-8.10.4.json#L183 ) (they now also have a template for 8.10.4, so we can get rid of the patch for 8.10.1 and just use that)
02:48 <Solid> ghcup already seems to distributive this alternative bindist ( https://gitlab.haskell.org/haskell/ghcup-hs/-/commit/7e0f839ff8f91cb7cfc78eaa57782bc1af30dc4b ) and it seems to work
02:48 <Solid> (I'm writing this here because I'm really swamped with work for the next few weeks and so I don't think I'll have the time to actually build and test this; sorry!)
```

**Comment by slotThe** [comment]
Ah, good point, we should also keep track of this here.

Some relevant issues for further information:

  - https://gitlab.haskell.org/ghc/ghc/-/issues/17950
  - https://github.com/haskellari/lukko/issues/15
  - https://github.com/haskell/cabal/issues/6602
  - https://github.com/haskell/cabal/issues/7313
  - https://github.com/commercialhaskell/stack/issues/5589
