### ISSUE TITLE
yambar is compiled without the wayland backend

### ISSUE THREAD

**Issue by FoundOne** [void-linux/void-packages#32248]
### System
x86_64-musl

* xuname:  
  Void 5.12.19_1 x86_64-musl GenuineIntel notuptodate rF
* package:  
  yambar-1.6.2_1
### Expected behavior
`yambar --backend=wayland` should launch yambar with wayland backend.
### Actual behavior
It ends with:
`err: bar/bar.c:393: yambar was compiled without the Wayland backend`

### Steps to reproduce the behavior
Look Expected behaviour.

**Comment by ericonr** [comment]
Ok, found the issue, will push fix in a bit. But it correctly uses the wayland backend if you don't specify anything.
