### ISSUE TITLE
ngspice broken package

### ISSUE THREAD

**Issue by Zappleberry** [void-linux/void-packages#32251]
### System

* xuname:  
  * Void 5.12.19_1 x86_64 GenuineIntel notuptodate rrmFFF
* package:  
  * ngspice-33_1

### Expected behavior

ngspice package to provide the binaries and files to run spice decks.

### Actual behavior

No ngspice binary provided. Only binary provided is cmpp (Code Model PreProcessor for Xspice)

### Steps to reproduce the behavior

* install ngspice via ``xbps-install ngspice``
* Try to run spice deck.

### Additional Debug information

running ``find / 2>&1 | grep -i ngspice`` does not return anything helpful or any binaries.

Output of ``xbps-query -Rf ngspice``
```
/usr/bin/cmpp
/usr/lib/libngspice.so.0.0.0
/usr/lib/ngspice/analog.cm
/usr/lib/ngspice/digital.cm
/usr/lib/ngspice/spice2poly.cm
/usr/lib/ngspice/table.cm
/usr/lib/ngspice/xtradev.cm
/usr/lib/ngspice/xtraevt.cm
/usr/share/licenses/ngspice/COPYING
/usr/share/man/man1/cmpp.1
/usr/share/ngspice/dlmain.c
/usr/share/ngspice/scripts/ciderinit
/usr/share/ngspice/scripts/devaxis
/usr/share/ngspice/scripts/devload
/usr/share/ngspice/scripts/setplot
/usr/share/ngspice/scripts/spectrum
/usr/share/ngspice/scripts/spinit
/usr/lib/libngspice.so.0 -> /usr/lib/libngspice.so.0.0.0
```

Forcing a reinstall does not help.

Typically ngspice provides a binary in ``/usr/bin/``

**Comment by mtboehlke** [comment]
I took a look at how Arch Linux packages ngspice.  It looks like if you want both the binary and the shared libraries, you need to build it with two passes, configure and make once for the share objects first, and then configure and make for the bins, but it won't let you do both in just one pass.

I am not sure the right way to do this in void's build system, though.

**Comment by ericonr** [comment]
There isn't really a clean one. Maybe a `post_configure` that runs configure from inside a subdir? Not sure.

**Comment by mtboehlke** [comment]
I put in a PR to resolve this, but it's my first attempt at contributing, so any constructive feedback would be most welcome.

**Comment by ericonr** [comment]
Looking good, I made an initial review.
