### ISSUE TITLE
[Package Request] Xorg with xf86-video-amdgpu requires llvm7, which was removed

### ISSUE THREAD

**Issue by ParzivalWolfram** [void-linux/void-packages#32293]
### System

* xuname:  
  Void 5.12.19_1 x86_64 uptodate rrrmFFFFF
* package:  
  xorg-server-1.20.13_1
  xf86-video-amdgpu-19.1.0_2
  mesa-dri-21.1.6_1

### Expected behavior
Xorg starts as normal on boot
### Actual behavior
Xorg starts and dies in an infinite loop due to lack of `libLLVM-7.so.1` as seen in multiple lines as follows:

`MESA-LOADER: failed to open radeonsi: libLLVM-7.so.1: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri)`

(with `radeonsi`, `kms_swrast` and `swrast` drivers all failing to load in the same manner) and an assertion error as follows: 

`Xorg: /usr/include/xorg/privates.h:121: dixGetPrivateAddr: Assertion 'key->initialized' failed.`

### Steps to reproduce the behavior
- Install Void with any DE that includes Xorg
- Install `xf86-video-amdgpu`
- Reboot

(Note: Xorg works totally fine in software mode if `xf86-video-amdgpu` and `mesa-dri` are not installed.)

**Comment by HadetTheUndying** [comment]
I am unable to recreate this. Have you tried running `xbps-reconfigure` on the effected packages?

**Comment by ParzivalWolfram** [comment]
I have, it didn't help any. I've worked around the issue with Bedrock.

**Comment by ericonr** [comment]
What does `xbps-pkgdb -a` say?

**Comment by ParzivalWolfram** [comment]
(note the `xfce4-terminal` missing dependency is intentional, i've replaced it with terminator and haven't figured out how to ignore package dependencies)

```ERROR: xf86-input-wacom: dependency not satisfied: xserver-abi-input-24_1
ERROR: xf86-video-amdgpu: dependency not satisfied: xserver-abi-video-24_1
ERROR: xfce4: dependency not satisfied: xfce4-terminal>=0.8.10
ERROR: xf86-input-evdev: dependency not satisfied: xserver-abi-input-24_1
ERROR: xf86-input-libinput: dependency not satisfied: xserver-abi-input-24_1
ERROR: xf86-input-synaptics: dependency not satisfied: xserver-abi-input-24_1
ERROR: xf86-input-vmmouse: dependency not satisfied: xserver-abi-input-24_1

**Comment by ericonr** [comment]
Do you by any chance have a locally built mesa installed in `/usr/local/lib`?

Do you now have `xorg-server` installed?

**Comment by ParzivalWolfram** [comment]
I have nothing installed that was manually compiled, and I have xorg-server
installed, yes.

**Comment by ericonr** [comment]
I suppose I will need a strace output to understand where it's trying and failing to load llvm7. Are you sure you aren't holding back any packages? Check `xbps-query -H`

**Comment by ParzivalWolfram** [comment]
This was a clean install 20 minutes before it broke, so i'd assume i'm not
holding any packages back. As for strace output, that may take a while, as
I had to have *something* that worked on my machine for work, so i've
reinstalled Debian. I backed up my installation, though, so I can probably
reproduce it in a few days.

**Comment by ericonr** [comment]
It's just that no package currently in repos can depend at all on llvm7, so there's something wonky that even tries to use it...

**Comment by ParzivalWolfram** [comment]
Turns out `tar` made every file in the backup 0 bytes, and I can't get it
to extract properly, so I guess we'll never know.

**Comment by ericonr** [comment]
Is there anything we can still act on this issue, then?

**Comment by ParzivalWolfram** [comment]
Not really, no. I can't reproduce either. Probably best to close this.

**Comment by ericonr** [comment]
Ok, thanks.

Let us know if you hit any other issues ;)
