### ISSUE TITLE
chromium: Jitsi Meet not loadable in Wayland-native mode (BUS_ADRERR)

### ISSUE THREAD

**Issue by klardotsh** [void-linux/void-packages#32313]
### System

* xuname:  `Void 5.12.17_1 x86_64 AuthenticAMD notuptodate rrrmFFFFFF`
* package:  `chromium-91.0.4472.114_1`

### Expected behavior

Can join an AV conference on Jitsi Meet (or other WebRTC platforms) when running Chromium with the Wayland backend (read: not in XWayland, the default, which works fine here).

### Actual behavior

![screenshot-2021-08-03-21:35:38Z](https://user-images.githubusercontent.com/799439/128089543-398337ac-aca0-4ed2-bc7f-2dff0ccf8052.png)

```
Received signal 7 BUS_ADRERR 7f7af406f000
#0 0x55cfe7147db9 (/usr/lib/chromium/chromium+0x4623db8)
#1 0x55cfe70b8843 (/usr/lib/chromium/chromium+0x4594842)
#2 0x55cfe7147961 (/usr/lib/chromium/chromium+0x4623960)
#3 0x7f7b2bd9e900 (/usr/lib/libpthread-2.32.so+0x138ff)
#4 0x55cfe803ff81 (/usr/lib/chromium/chromium+0x551bf80)
#5 0x55cfe802993e (/usr/lib/chromium/chromium+0x550593d)
#6 0x55cfe8027ab6 (/usr/lib/chromium/chromium+0x5503ab5)
#7 0x55cfe4688624 (/usr/lib/chromium/chromium+0x1b64623)
#8 0x55cfe468a034 (/usr/lib/chromium/chromium+0x1b66033)
#9 0x55cfeb6b9a3e (/usr/lib/chromium/chromium+0x8b95a3d)
#10 0x55cfeb6b9747 (/usr/lib/chromium/chromium+0x8b95746)
#11 0x55cfeb6b898f (/usr/lib/chromium/chromium+0x8b9498e)
#12 0x55cfe71593bf Received signal 7 BUS_ADRERR 7f7adc396800
#0 0x55cfe7147db9 (/usr/lib/chromium/chromium+0x4623db8)
#1 0x55cfe70b8843 (/usr/lib/chromium/chromium+0x4594842)
#2 0x55cfe7147961 (/usr/lib/chromium/chromium+0x4623960)
#3 0x7f7b2bd9e900 (/usr/lib/libpthread-2.32.so+0x138ff)
#4 0x55cfe803ff81 (/usr/lib/chromium/chromium+0x551bf80)
#5 0x55cfe802993e (/usr/lib/chromium/chromium+0x550593d)
#6 0x55cfe8027ab6 (/usr/lib/chromium/chromium+0x5503ab5)
#7 0x55cfe4688624 (/usr/lib/chromium/chromium+0x1b64623)
#8 0x55cfe468a034 (/usr/lib/chromium/chromium+0x1b66033)
#9 0x55cfeb6b9a3e (/usr/lib/chromium/chromium+0x8b95a3d)
#10 0x55cfeb6b9747 (/usr/lib/chromium/chromium+0x8b95746)
#11 0x55cfeb6b898f (/usr/lib/chromium/chromium+0x8b9498e)
#12 0x55cfe71593bf (/usr/lib/chromium/chromium+0x46353be)
#13 0x7f7b2bd93eae start_thread
#14 0x7f7b27d5c2ff __GI___clone
  r8: 0000000000061800  r9: 0000000000000138 r10: 0000000000000280 r11: 0000000000000280
 r12: 000055cfe803ff70 r13: 0000000000000000 r14: 00007f7af4151800 r15: 0000000000000001
  di: 00007f7af4151840  si: 00007f7adc396800  bp: 00007f7af7ffaff0  bx: 00007f7adc396800
  dx: 0000000000061800  ax: 0000000000000000  cx: 000055cfe803ff70  sp: 00007f7af7ffaff0
  ip: 000055cfe803ff81 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 00007f7adc396800
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

### Steps to reproduce the behavior

- Run Chromium in Wayland+Ozone mode (in my case, I'm running in Sway): `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland`
- Go to [Jitsi](https://meet.jit.si)
- Hit `Start Meeting` to join a random empty call
- Crash occurs seemingly when Jitsi attempts to access the camera and/or microphone, not totally sure which, or whether it's the access to the camera/microphone causing the problem, or Chromium is failing to pop up the permission request. Not really sure how to go about narrowing down the search here, either, though admittedly I'm filing this during the workday so I'm kinda going quickly :)

**Comment by fosslinux** [comment]
I have seen this before, and it is not ozone limited, all wayland DM/WMs do this.

**Comment by sburris0** [comment]
This happens to me on Firefox / sway as well.

**Comment by klardotsh** [comment]
Interesting - I've never had issues with FF+Sway... I wonder what the difference in our setups might be to lead to that

**Comment by sburris0** [comment]
I encountered what appears to be the same issue with Google Meet.
Does this also happen in Chromium?

**Comment by klardotsh** [comment]
This ticket is all about Chromium, yeah.

Decided to try this again today and I get a new issue: rather than a tab or browser crash, it just locks the entire browser, seemingly when trying to init the webcam. Almost nothing in the logs:

```
[0913/135532.847572:ERROR:scoped_ptrace_attach.cc(37)] process not stopped
[0913/135532.847640:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
[0913/135532.847662:ERROR:scoped_ptrace_attach.cc(27)] ptrace: No such process (3)
```
