### ISSUE TITLE
VirtualBox breaks with Kernel 5.13

### ISSUE THREAD

**Issue by jonagoldman** [void-linux/void-packages#32327]
Support for Kernel 5.13 was added in VirtualBox 6.1.26 but current available version in Void is 6.1.20 so it breaks.

VirtualBox needs no be updated to latest 6.1.26 to work in Kernel 5.13

**Comment by ericonr** [comment]
I can open a PR to update it. Could you test my PR?

**Comment by jonagoldman** [comment]
@ericonr sure!

**Comment by jonagoldman** [comment]
I tried to compile virtualbox-ose updating the template version and sha but it fails.

In step:
```
=> virtualbox-ose-6.1.26_1: running do_configure ...
```

I get the error:

```
Checking for Qt5: ./configure: line 1566: * 100 + : syntax error: operand expected (error token is "* 100 + ")
=> ERROR: virtualbox-ose-6.1.26_1: do_configure: './configure --disable-docs --disable-java --enable-vde --disable-python --disable-kmods --nofatal --enable-webservice' exited with 1
=> ERROR:   in do_configure() at srcpkgs/virtualbox-ose/template:40
```

**Comment by ericonr** [comment]
Check out #32328

**Comment by ericonr** [comment]
I need help there with the thing that fails after that configure step is fixed.

**Comment by jonagoldman** [comment]
Built successfully locally.

**Comment by ericonr** [comment]
@jonagoldman did you install and run it?

**Comment by jonagoldman** [comment]
Yes, installed and running without issues.

**Comment by ericonr** [comment]
Thanks, appreciated!

**Comment by jonagoldman** [comment]
Thanks to you!
