### ISSUE TITLE
Chromium crash on close

### ISSUE THREAD

**Issue by Bleznudd** [void-linux/void-packages#32321]
### System

* xuname:  
`Void 5.12.19_1 x86_64 AuthenticAMD notuptodate hold rrrrmmnDFFFFFFFFFFF`
* package:  
`chromium-91.0.4472.114_1`

### Expected behavior

Closing the window does not freeze the system

### Actual behavior

Closing the window does freeze the system

### Steps to reproduce the behavior

Open a Chromium window and then close it. The system will freeze and it will need a reboot.

**Comment by mvf** [comment]
Are you on NVidia? If so, this likely duplicates #32241. See that ticket for a workaround.

**Comment by Bleznudd** [comment]
My bad, I was unable to find that issue.
Indeed I'm on nvidia and this is a duplicate.

Many thanks
