### ISSUE TITLE
obs: enable building browser source

### ISSUE THREAD

**Issue by Lolzen** [void-linux/void-packages#32356]
Since obs 27.0 obs is able to be built with browser source for feature parity with windows in terms of panel docks (for example integrated twitch chat in within obs)
i only "tested" this by building my own portable version of obs. I can use the exact same config file interchangibly between the portable build and the official package from the void repos, as expected.

`wget https://cdn-fastly.obsproject.com/downloads/cef_binary_4280_linux64.tar.bz2
tar -xjf ./cef_binary_4280_linux64.tar.bz2
git clone --recursive https://github.com/obsproject/obs-studio.git
cd obs-studio
mkdir build && cd build
cmake -DUNIX_STRUCTURE=0 -DCMAKE_INSTALL_PREFIX="${HOME}/obs-studio-portable" -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="../../cef_binary_4280_linux64" ..
make -j4 && make install`
as seen [here](https://github.com/obsproject/obs-studio/wiki/Install-Instructions#linux-portable-mode-all-distros)

**Comment by paper42** [comment]
Duplicate of #23685, feel free to comment there if something changed.
