### ISSUE TITLE
Update to Java 11 (LTS)

### ISSUE THREAD

**Issue by SevereOverfl0w** [void-linux/void-packages#3237]
A continuation of https://github.com/voidlinux/void-packages/issues/10255

I attempted this originally, and struggled as it was far beyond my capabilities. I wanted to open an issue to help track the upgrade's progress.

**Comment by Hoshpak** [comment]
I have been working on this myself a bit and got a working build of openjdk11. The first issue I encountered was that it (as java always does) needs a jdk to bootstrap which needs to be either version 10 or 11. So i went with the binary openjdk builds provided by oracle which leads to the next issue, it is only provided for x86_64 currently so I could only build the package for that architecture and even i686 would be left without a current java version.

Previously the jre has been part of the jdk build so we could package it separately. This seems to be no longer the case although all components that make up the jre are still contained in the jdk. I wonder if we should copy these components into a subpackae to create a pseudo-jre (if possible) or provide just an jdk package and have people install that regardless if they want to develop java applications or just run them.

**Comment by espectalll** [comment]
I wonder if it can be ported to Musl this time around? After all, there's been preview builds for Musl Linux since Java 9 if I recall correctly.

**Comment by Johnnynator** [comment]
> I wonder if it can be ported to Musl this time around? After all, there's been preview builds for Musl Linux since Java 9 if I recall correctly.

Openjdk 11 doesn't have an official musl build. They postponed it to Java 12.

> The Alpine Linux build previously available on this page was removed as of JDK 11 GA. It’s not production-ready because it hasn’t been tested thoroughly enough to be considered a GA build. Please use the early-access JDK 12 Alpine Linux build in its place.

**Comment by espectalll** [comment]
I'm aware, that's why I said "preview builds". Considering that previously there was no interest in packaging non-LTS Java releases tho, I'm worried Musl Void won't get any Java until version 17 on 2021.

**Comment by ninewise** [comment]
@Hoshpak mind sharing your work?

**Comment by Hoshpak** [comment]
Of course not, I uploaded the templates to a new branch: https://github.com/Hoshpak/void-packages/tree/openjdk11

Those have been lying around on my system for some time, I haven't tested if they still work.

**Comment by ninewise** [comment]
Great, thanks.

**Comment by SevereOverfl0w** [comment]
I am interested in progressing this.

- I personally think we should mirror upstream in terms of package shape, so a single jdk seems fine by me.
- How does the Void packages team feel about using a bootstrap JDK vs packaging Java 9 & 10 first using jdk8.
- Feels odd that x86_64 bootstrap jdk can't build i386 jdk, that seems like something that could work.

**Comment by SevereOverfl0w** [comment]
I've managed to throw together an oracle-jdk-11 package. I wanted a new package so that it would allow switching between 8 & 11.

@Gottox I notice that oracle-jdk has a "replaces" line in it, why is that? It forces the oracle-jdk-11 to be removed.

**Comment by Hoshpak** [comment]
Is a bootstrap jdk available that supports i686, x86_64, aarch64, armv6l, armv7l, ppc64 with its flavours, ppc and each with a musl variant? I am not aware of a project providing this.

The i686 and x86_64 stuff is more a restriction of xbps-src than of the jdk. i686 packages are built on an x86_64 host but within a i686 masterdir so it can't execute x86_64 binaries. Changing this to allow mixed builds would require a redesign of xbps-src,

**Comment by asiekierka** [comment]
If possible, I'd like to help this effort myself. I do not think Void should have only a single JDK version, as there are many projects still dependent on Java 8 (both in development and in production), even now that Java 11 is the new LTS release.

**Comment by SevereOverfl0w** [comment]
@asiekierka I started a PR for Oracle JDK, and it's in need of some more experienced guidance.

If you want to package OpenJDK, I think you have to bootstrap it, although you could bootstrap with Oracle JDK 11 potentially.

**Comment by knusbaum** [comment]
If I'm reading this right, once we have oracle-jdk-11, we can bootstrap openjdk.
The oracle jdk PR is here: https://github.com/void-linux/void-packages/pull/8634 
@SevereOverfl0w will you have time to address comments there? If not, I can look at carrying your work forward.

Otherwise, is this also a viable bootstrapping method? https://github.com/void-linux/void-packages/pull/8009

**Comment by SevereOverfl0w** [comment]
Please take over my PR

Thu Aug 01 23:19:33 GMT+02:00 2019 Kyle Nusbaum <notifications@github.com>:

**Comment by q66** [comment]
I plan to attempt a fully from-source bootstrap so that we don't need to rely on any oracle jdk or a binary copy of openjdk, but i will need some more time with that.

**Comment by knusbaum** [comment]
@q66 That would be great. I had no luck with the binary oracle JDK bootstrap, but I have a mostly working from-source openjdk that's bootstrapped from the binary openjdk. If I manage to get some time to test it, I'll put up a PR at least for others to look at. I don't think it's merge-ready yet, and I haven't tested cross-compile builds at all.

**Comment by q66** [comment]
Alpine has this already, they use gcj to bootstrap jdk6 (i think it can directly bootstrap jdk7 too, so that should be enough for us), then use jdk7 to bootstrap jdk8, proceed all the way up to 11. It's a bit of a pain but it should be workable (note that alpine is already musl based)

**Comment by knusbaum** [comment]
Do you plan to then have separate packages for jdk7 through jdk11?

**Comment by q66** [comment]
yeah, there's no other way around it

**Comment by knusbaum** [comment]
That is actually kind of nice. I've needed to test things with multiple JDKs before, so it will be nice to have the option.

**Comment by kozachynskyi** [comment]
@knusbaum Can this issue be closed?

**Comment by knusbaum** [comment]
Yes, this can be closed.
