### ISSUE TITLE
Wayland display server "forgets" to wake up my notebook screen

### ISSUE THREAD

**Issue by rivanfebrian123** [void-linux/void-packages#32455]
### System

![Screenshot from 2021-08-11 17-55-47](https://user-images.githubusercontent.com/6300910/129017528-0f6d5657-2fd0-418f-a040-a1ae666915c7.png)

* xuname:  
  * Void 5.13.9_1 x86_64-musl GenuineIntel uptodate rrFFF

* package:  
  * mesa-21.1.6_2
  * wayland-1.19.0_1
  * gdm-40.0_1
  * gnome-40.0_1

### Expected behavior
It should wake up my screen

### Actual behavior
Can't wake it up. So I need to blindly enter my password and press enter to get into my DM (GNOME on Xorg), or go to tty1 and then go back to tty7 and move my cursor

### Steps to reproduce the behavior
Install GNOME and get into the login screen (GDM), and wait for several minutes, or login with GNOME on Wayland and wait for several minutes
,

**Comment by paper42** [comment]
This might be an amdgpu bug in 5.13, downgrading to 5.12 should help. 5.14 already has the fix.

**Comment by h4xor666** [comment]
Yep I have the same issue, albeit slightly different behavior, on 5.12.
