### ISSUE TITLE
Cyclic dependency: perl-HTML-Parser <-> perl-HTTP-Message

### ISSUE THREAD

**Issue by 4ricci** [void-linux/void-packages#32468]
`perl-HTTP-Message` is a check dependency of `perl-HTML-Parser`,
`perl-HTML-Parser` is a runtime and build dependency of `perl-HTTP-Message`.

When updating both packages (<https://github.com/4ricci/void-packages/pull/31>), `./xbps-src -Q pkg perl-HTTP-Message` returns the error:
```
=> ERROR: Build-time cyclic dependency perl-HTML-Parser(host), perl-HTTP-Message(host), perl-HTML-Parser(host) detected.
```

`./xbps-src -Q pkg perl-HTML-Parser` returns the error:
```
=> ERROR: Build-time cyclic dependency perl-HTTP-Message(host), perl-HTML-Parser(host), perl-HTTP-Message(host) detected.
```

**Comment by ericonr** [comment]
I think the correct path forward would be disabling tests for `perl-HTML-Parser` (or see if they can run without `perl-HTTP-Message`. Otherwise this means bootstrap is broken when tests are enabled, and we want to make bootstrap with tests possible.

**Comment by Chocimier** [comment]
On the contrary, I think cycles due to checkdepends are better than not testing package at all. In case like here, one can first build package(s) locally without tests, than rebuild with tests enabled.

**Comment by dkwo** [comment]
I also had to deal with the same issue here https://github.com/void-linux/void-packages/pull/32229

**Comment by q66** [comment]
i think not testing is better because if tests are not cyclic, they can be properly automated (we could even have the builders run them eventually) while if you allow cycles they can't (and tests on stuff like this are mostly meaningless either way, i see no reason to let a few rare cases break it)

**Comment by q66** [comment]
also i think checkdepends are in general a poor idea because it means that your build environment differs if you're running tests vs if you're not

while ideally the build environment should only ever be affected by build options

**Comment by dkwo** [comment]
Then, shall we treat checkdepends just as (host)makedepends, regardless of whether we are permorming tests or not?
