### ISSUE TITLE
MISSING: qt5-core-5.15.3+20210429_3

### ISSUE THREAD

**Issue by pudiva** [void-linux/void-packages#32472]
### System

```
# xuname
MISSING: qt5-core-5.15.3+20210429_3
Transaction aborted due to unresolved dependencies.
Void 5.12.13_1 x86_64 GenuineIntel uptodate rrrrmdFFFFFF
```

### Expected behavior

Pkgs updated.

### Actual behavior

Pkgs not updated.

### Steps to reproduce the behavior

```
# xbps-install -Su
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/debug/x86_64-repodata' ...
MISSING: qt5-core-5.15.3+20210429_3
Transaction aborted due to unresolved dependencies.
```

**Comment by Duncaen** [comment]
There is a big rebuild ongoing https://build.voidlinux.org/waterfall, the repository is staged until those builds are finished.
Staging does not work over multiple repositories so a package in either multilib or nonfree pulls in a dependency on a package that is not yet published.

**Comment by pudiva** [comment]
Cool! Thanks for explaining! :sparkles:

**Comment by pudiva** [comment]
Hello, voiders.

I tried to update here today and I'm still getting this same error message.

I looked on the waterfall today and it looks like it's done for x86_64 and i686, so it should be working, right?

**Comment by Duncaen** [comment]
There were still some packages that needed to be removed from the index, its unstaged now and should sync to all mirrors pretty fast, alpha.de.repo already works now.

**Comment by pudiva** [comment]
Yes, it's working now! Thanksss! :sparkling_heart: :sparkling_heart: :sparkling_heart:
