### ISSUE TITLE
[RFC] systemd service files

### ISSUE THREAD

**Issue by Duncaen** [void-linux/void-packages#32481]
Currently there is no policy on systemd files, some packages ship them and some delete them.

There is an open issue about removing them #32154 and a hook for automatically removal was discussed there.

I personally would prefer to keep them as a reference point for services.

**Comment by ericonr** [comment]
It doesn't really take space, so that's fair. My only issue is that it might give an appearance of lax packaging policy and standards, since the files are "useless". I don't think that matters much.
