### ISSUE TITLE
`libvirt` hangs on connecting

### ISSUE THREAD

**Issue by sisungo** [void-linux/void-packages#32561]
### System

* xuname:  
  Void 5.13.10_1 x86_64-musl GenuineIntel uptodate FF
* package:  
  *affected package(s) including the version*: `libvirt-7.6.0_1`

### Expected behavior
Tools using `libvirt` can connect to the daemon well

### Actual behavior
All tools hangs on connecting to `qemu:///system`. `virt-manager`'s status is always `QEMU/KVM -- Connecting`, and `virsh -c qemu:///system` hangs without output. (last syscall: `poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 2, -1`)

### Steps to reproduce the behavior
1. Enable services: `libvirtd`, `virtlogd` and `virtlockd`.
2. Execute `virsh -c qemu:///system` or `virt-manager`
3. They hangs.

**Comment by paper42** [comment]
I can not reproduce this.
* were you following the handbook? https://docs.voidlinux.org/config/containers-and-vms/libvirt.html
* are all required services running? dbus, libvirtd, virtlogd, virtlockd

**Comment by sisungo** [comment]
- Yes. I was following.
 - All required services are running.

**Comment by leper** [comment]
@ericonr it was, but that patch was removed in 4fc633808bf814d5a3874304da6840e7c9cb242. However I can verify that #32727 fixes the issue for me.
