### ISSUE TITLE
xbps update fail

### ISSUE THREAD

**Issue by leetnc** [void-linux/void-packages#32592]
### System

* xuname:  

* package:  xbps-install -u xbps
 

### Expected behavior
xbps-install -u xbps  would download and install xbps update
### Actual behavior
xbps-install -u xbps actually fails with:
ERROR: [trans] failed to download `removed-packages-0.1_49' signature from `https://alpha.de.repo.voidlinux.org/current': Not Found

### Steps to reproduce the behavior

# xbps-install -u xbps

Name             Action    Version           New version            Download size
glibc            update    2.30_1            2.32_2                 - 
libcrypto1.1     install   -                 1.1.1k_1               - 
libssl1.1        install   -                 1.1.1k_1               - 
libarchive       update    3.4.3_2           3.5.1_2                - 
libxbps          update    0.59.1_2          0.59.1_5               - 
xbps             update    0.59.1_2          0.59.1_5               - 
removed-packages install   -                 0.1_49                 3235B 
linux5.10        install   -                 5.10.58_1              86MB 
linux-base       install   -                 2021.07.21_1           593B 
linux-lts        install   4.14_2            5.10_1                 561B 
base-system      update    0.113_2           0.114_1                846B 

Size to download:               86MB
Size required on disk:         129MB
Space available on disk:        12GB

Do you want to continue? [Y/n] 

[*] Downloading packages
ERROR: [trans] failed to download `removed-packages-0.1_49' signature from `https://alpha.de.repo.voidlinux.org/current': Not Found
Transaction failed! see above for errors.

**Comment by ericonr** [comment]
Update with `-Su`, removed packages is now at revision 50.

**Comment by leetnc** [comment]
Argg....a careless mistake on my part.    Working fine now !   Thanks.
