### ISSUE TITLE
eudev will be depreciated, I suggest migrating to smdev

### ISSUE THREAD

**Issue by bugcrazy** [void-linux/void-packages#32661]
The Gentoo project will depreciate eudev, this will harm musl distros and that do not use systemd.

https://github.com/gentoo-mirror/gentoo/blob/4a7df7c965fa8c251e32ef1d82ffad43bcf9436f/2021-08-24-eudev-retirement/2021-08-24-eudev-retirement.en.txt#L45

I suggest migrating to smdev, because it is simple to maintain and have sample pkgbuilds, smdev runs with runit and libeudev-zero!  
https://aur.archlinux.org/packages/?K=phkr&SeB=m

**Comment by ericonr** [comment]
There are a few mdev implementations bouncing around, but at the moment we are definitely sticking with what's been released from eudev already.

**Comment by Duncaen** [comment]
udev/eudev is pretty much in maintenance mode anyways, we should be able to maintain it without problems tbh, the there have been ~10 commits in the last few years.

**Comment by mikoxyz** [comment]
I'm quite late to the party (and quite possibly also necroposting,) but would migrating to systemd's udev (which is what Gentoo will be doing) be viable going forward?

**Comment by ericonr** [comment]
It's been considered. However, given that Alpine and Deviant are maintaining eudev in a joint venture, it might be unnecessary.

**Comment by kmk3** [comment]
@ericonr commented [on Nov 11](https://github.com/void-linux/void-packages/issues/32661#issuecomment-966065576):

> It's been considered. However, given that Alpine and Deviant are maintaining
> eudev in a joint venture, it might be unnecessary.

Interesting.  For future reference, from eudev's [README.md](https://github.com/eudev-project/eudev/blob/76cac0781501f73e8273659365e0f12d41b7a353/README.md):

> This is a project started by Gentoo developers and testing was initially
> being done mostly on OpenRC.  We welcome contribution from others using a
> variety of system initializations to ensure eudev remains system
> initialization and distribution neutral.  On 2021-08-20 Gentoo decided to
> abandon eudev and a new project was established on 2021-09-14 by Alpine,
> Devuan and Gentoo contributors (a-z order).

Current project URL: <https://github.com/eudev-project/eudev>
