### ISSUE TITLE
mesa-dri-dbg is inconsistent with mesa-dri

### ISSUE THREAD

**Issue by datenwolf** [void-linux/void-packages#32788]
### System

* xuname:  Void 5.13.13_1 x86_64 GenuineIntel notuptodate rrrrrmmdnFFFFF
* package:  mesa-dri-dbg-21.2.1_1

### Expected behavior
mesa-dri-dbg should contain debug information for all shared objects shipped in mesa-dri

### Actual behavior
mesa-dri-dbg contains only a subset of debug files:

```
~/ %  xbps-query -f mesa-dri
/usr/lib/dri/crocus_dri.so
/usr/lib/dri/i830_dri.so
/usr/lib/dri/i915_dri.so
/usr/lib/dri/i965_dri.so
/usr/lib/dri/iris_dri.so
/usr/lib/dri/kms_swrast_dri.so
/usr/lib/dri/libgallium_dri.so
/usr/lib/dri/libmesa_dri_drivers.so
/usr/lib/dri/nouveau_dri.so
/usr/lib/dri/nouveau_vieux_dri.so
/usr/lib/dri/r200_dri.so
/usr/lib/dri/r300_dri.so
/usr/lib/dri/r600_dri.so
/usr/lib/dri/radeon_dri.so
/usr/lib/dri/radeonsi_dri.so
/usr/lib/dri/swrast_dri.so
/usr/lib/dri/virtio_gpu_dri.so
/usr/lib/dri/vmwgfx_dri.so
/usr/lib/dri/zink_dri.so
/usr/lib/gallium-pipe/pipe_crocus.so
/usr/lib/gallium-pipe/pipe_iris.so
/usr/lib/gallium-pipe/pipe_nouveau.so
/usr/lib/gallium-pipe/pipe_r300.so
/usr/lib/gallium-pipe/pipe_r600.so
/usr/lib/gallium-pipe/pipe_radeonsi.so
/usr/lib/gallium-pipe/pipe_swrast.so
/usr/lib/gallium-pipe/pipe_vmwgfx.so

~/ %  xbps-query -f mesa-dri-dbg
/usr/lib/debug/usr/lib/dri/libgallium_dri.so
/usr/lib/debug/usr/lib/dri/libmesa_dri_drivers.so
/usr/lib/debug/usr/lib/gallium-pipe/pipe_crocus.so
/usr/lib/debug/usr/lib/gallium-pipe/pipe_iris.so
/usr/lib/debug/usr/lib/gallium-pipe/pipe_nouveau.so
/usr/lib/debug/usr/lib/gallium-pipe/pipe_r300.so
/usr/lib/debug/usr/lib/gallium-pipe/pipe_r600.so
/usr/lib/debug/usr/lib/gallium-pipe/pipe_radeonsi.so
/usr/lib/debug/usr/lib/gallium-pipe/pipe_swrast.so
/usr/lib/debug/usr/lib/gallium-pipe/pipe_vmwgfx.so
```

### Steps to reproduce the behavior
Install mesa-dri and mesa-dri-dbg and compare their set of files.

**Comment by q66** [comment]
not necessarily a problem, gallium drivers are all hardlinks to a single megadriver, so that is what you get debug files of

**Comment by datenwolf** [comment]
I think the debug packages should create matching hardlinks for the debug symbol files, so that debuggers have an easier time picking them up.

**Comment by st3r4g** [comment]
iirc the debugger picked the right one automatically...

**Comment by datenwolf** [comment]
For me it didn't. I had to place the correct hardlinks manually. With that done, things got picked up properly.

For your amusement: https://twitter.com/datenwolf/status/1433020708414689280 and https://twitter.com/datenwolf/status/1433020702274330630
