### ISSUE TITLE
ufw does not reenable after reboot. Fix is provided.

### ISSUE THREAD

**Issue by JohnTill123** [void-linux/void-packages#32795]
### System
* xuname:  Void 5.13.13_1 x86_64 GenuineIntel/VM uptodate rFF
* package:  ufw-0.36_4

### Expected behavior
After installing ufw and enabling it, it will be "active" and remain "active" after a reboot.

### Actual behavior
ufw is only active until a reboot, then it is "inactive" until it is manually enabled by the user.

### Steps to reproduce the behavior
Install  ufw as follows:
#xbps-install ufw
#xbps-reconfigure ufw
#ufw enable
#reboot 

#ufw status returns "inactive"

### FIX:  
$cd /etc/runit/runsvdir
$sudo ln -s /etc/sv/ufw ufw
This creates a symbolic link in the "/etc/runit/runsvdir" pointing to the "/etc/sf/ufw" directory where is the "run" file.

**Comment by paper42** [comment]
> ### Expected behavior
> After installing ufw and enabling it, it will be "active" and remain "active" after a reboot.

Is this the default behavior on other Linux distributions? Ubuntu also uses a oneshot service to start ufw on boot, but in contrast to Void they seem to auto-enable it.

> ```  
> $ cd /etc/runit/runsvdir
> $ sudo ln -s /etc/sv/ufw ufw
> ```

Is there a reason why you are not using /var/service/ to enable services?

**Comment by ericonr** [comment]
Maybe we should document this need in docs, but we have a clear policy of not making runtime changes to user's systems; that includes auto enabling services like firewall, same way we don't restart sshd after updates.

We can consider documenting this in void-docs or a `README.voidlinux` file for the package.

**Comment by ericonr** [comment]
(or patching ufw to link the service)

**Comment by q66** [comment]
intended behavior, you are expected to enable your services yourself
