### ISSUE TITLE
Vault UI is not available in this binary.

### ISSUE THREAD

**Issue by FatmanUK** [void-linux/void-packages#32807]
### System
$ xuname
Void 5.3.9_1 x86_64 GenuineIntel notuptodate rrrrmmnFFFFFFFFF

$ xbps-query -p pkgver vault
vault-1.8.1_1

### Expected behavior
Web UI loads.

### Actual behavior
Error: "Vault UI is not available in this binary."

### Steps to reproduce the behavior
\# xbps-install vault
Follow Hashicorp tutorial to learn Vault and start the service.
Connect to localhost:8200 with curl or Chromium.

Similar issues:
https://github.com/Homebrew/brew/issues/7614 (but I'm not using homebrew, I'm using server mode and I unsealed manually)
https://discuss.hashicorp.com/t/official-hashicorp-tap-for-homebrew/4327 (again not using homebrew)

I'm trying to fork the package but I have a lot of learning to do about go packages. I'm hoping you'll be able to fix this trivially.

**Comment by ericonr** [comment]
https://github.com/hashicorp/vault/blob/72124753858535347a05a2d140b480cad12fd222/Makefile#L39 so we need to add `ui` to build tags. Which is done by passing args as done here: https://github.com/hashicorp/vault/blob/72124753858535347a05a2d140b480cad12fd222/scripts/build.sh#L60
