### ISSUE TITLE
armv6l armv7l kernel version behind others ?

### ISSUE THREAD

**Issue by Cooky-12** [void-linux/void-packages#32806]
Hi, I'm new to void, want install void on some arm board.
I search kernel on https://voidlinux.org/packages, but found armv6l and armv7l doesn' have latest kernel version ( old 5.4 ).
May I ask is that normal ?

**Comment by Duncaen** [comment]
The generic kernels are basically unused, most platforms have their own kernel builds. Someone with a device that works with the generic arm kernel can update the configuration, but so far nobody cared enough or the hardware simply does not exist.

**Comment by Cooky-12** [comment]
> The generic kernels are basically unused, most platforms have their own kernel builds. Someone with a device that works with the generic arm kernel can update the configuration, but so far nobody cared enough or the hardware simply does not exist.

Some arm board don't have official kernel ( e.g. orangepi  ... ), I simplely install archlinux rootfs ( with latest kernel ) and edit uboot script to load corresponding dtb to boot.

Thanks, I will compile kernel my self.
