### ISSUE TITLE
Split graphviz binaries that pull graphics libraries and X11

### ISSUE THREAD

**Issue by tornaria** [void-linux/void-packages#32826]
The current graphviz package pulls in heavy dependencies (fonts, cairo, gd, gtk, X11, etc), but includes some simple command line binaries that are often used to build documentation for other packages (e.g. `dot`).

I wonder if it makes sense to split the simple command line binaries from the more complex X11 stuff.

If there's agreement that this is a good thing, I can volunteer to research a good way to split it and make a PR.

**Comment by dkwo** [comment]
It makes sense from the math libraries point of view.

**Comment by leahneukirchen** [comment]
I fear this is not so easy, all graphics output (except for raw PS) will need cairo/pango/harfbuzz etc already, not sure pulling out the GTK part is worth it.

**Comment by tornaria** [comment]
The core plugin for dot seems to support eps, fig, ps, svg, may be good enough to build documentation.

The gd plugin seems to support jpeg, png, etc. However /usr/lib/graphviz/libgvplugin_gd.so is linked to libcairo. I wonder if it's possible to separate the gd plugin from the cairo plugin.

In any case, cairo doesn't seem that bad, and it seems to also support pdf, so that may be a reasonable place to split. I'd be happy if I can install graphviz without pango, gtk, gdk, etc.

**Comment by leahneukirchen** [comment]
Most docs like with doxygen want PNG. Also GD will pull in pangocairo, and cairo pulls in various X11 stuff already.

But feel free to make a PR.

**Comment by tornaria** [comment]
Closed by #32939.
