### ISSUE TITLE
[RFC] Using virtualpkg to pin a kernel version

### ISSUE THREAD

**Issue by tornaria** [void-linux/void-packages#32833]
Suppose I want to pin my kernel to 5.10, which is the latest LTS.

I can configure
```
virtualpkg=linux:linux5.10
virtualpkg=linux-headers:linux5.10-headers
```
in xbps.d. This works fine in the sense that `linux5.10` will be installed instead of `linux5.13` and it is future proof (contrary to `virtualpkg=linux5.13:linux5.10` which will break when kernel is switched to 5.14).

However, this results in the `linux-base` package as orphan. Of course, I can just change `linux-base` to manual and be done with it, but if I forget this could lead to a broken system and it is more steps to document (and since this is not documented, I don't know if something will change in the future that breaks my system).

I wonder if it would make sense to have a different meta package, say `linux-kernel`, whose only purpose is to depend on `linux${version}`, just like `linux-headers` only purpose is to depend on `linux${version}-headers`.

Then `linux` would be a meta package that depends on `linux-kernel` and `linux-base` (or the actual dependencies as linux-base might become superfluous), and linux kernel version can be pinned easily with virtualpkgs as above. This seems robust enough to be documented in the manual, etc.

---

In fact, it seems the current `linux-base` pkg could just be renamed `linux` adding `linux-kernel` dependency, and the current `linux` could just be renamed `linux-kernel`, keeping `linux-headers` as a subpkg of `linux-kernel`.

**Comment by ericonr** [comment]
My current plan with linux-base was to document removing `linux` and marking it manual, then choosing your preferred version for the kernel. There's an open issue about it in the void-docs repo. Do you think that's too error prone?

**Comment by tornaria** [comment]
I just noticed that with `virtualpkg=linux-headers:linux5.10-headers`, when I install a package depending on `linux-headers` (say, `dkms`) it will force-reinstall `linux5.10-headers`. Is that a bug in `xbps-install`, or my misunderstanding?

The alternative would be to `ignorepkg=linux-headers` and then one can install/remove whatever version.

**Comment by Chocimier** [comment]
> it will force-reinstall `linux5.10-headers`

Yes, this is known, reported bug.

Isn't virtualpkg unreliable in general, especially compared to installing your own `linux` pkg spin?

**Comment by tornaria** [comment]
> My current plan with linux-base was to document removing `linux` and marking it manual, then choosing your preferred version for the kernel. There's an open issue about it in the void-docs repo. Do you think that's too error prone?

Not too error prone, but if I'm not missing anything the way I propose is one step less.

1. current solution
  - `ignorepkg=linux`
  - mark `linux-base` manual
  - remove `linux`
  - install `linux5.10`
  
2. my proposal
  -`ignorepkg=linux-kernel`
  - remove `linux-kernel`
  - install `linux5.10`

Not a big difference. Better imo would be if `virtualpkg=linux-kernel:linux5.10` followed by `xi -u` would be all that's needed.

**Comment by tornaria** [comment]
Point is: you don't have to mess with `linux` and `linux-base` which having different dependencies are a little bit less obvious to understand. You only mess with `linux-kernel` which is defined to be JUST a meta dependency to a particular kernel version and you replace it with a different kernel version.
