### ISSUE TITLE
How to reconfigure perl on Void Linux - Or is there a perl-devel package ?

### ISSUE THREAD

**Issue by aaFn** [void-linux/void-packages#32857]
Hello @leahneukirchen , I am trying to get an Apache server running with mod_perl on a Void Linux instance, to be able to call Perl from Apache.
This DSO module is not included in the packages, so I am then trying to compile it, using instructions at https://perl.apache.org/docs/2.0/user/install/install.html

However, it fails with error
```
mod_perl does not currently support multiplicity without ithreads.
Please recompile Perl with -Duseithreads and -Dusemultiplicity
```

And indeed, doing `perl -V:useithreads -V:usemultiplicity` shows that one is configred, but not the other (and mod_perl asks for none, or both, but not the intermediate situation):
```
useithreads='define';
usemultiplicity='undef';
```

So I need to reconfigure / re-compile the distributed perl version, using:
```
  % ./Configure -des -Uusethreads  (or   % ./Configure -des -Dusethreads -Dusemultiplicity)
  % make && make test && make install

```

However, there is no such command in the distributed package, and apparently no perl-devel package is available.
Do you have an advice or better view on how to achieve this ?

Thanks in advance, aaFn.

**Comment by leahneukirchen** [comment]
Yes, our Perl is built without multiplicity and changing that would result in a complete rebuild of all Perl packages. We can consider it for the next big rebuild maybe, I'll have to check what other distros do. IIRC it results in a performance overhead too.

**Comment by aaFn** [comment]
Correct, I also hear there are performance implications, but primarily related to threads as I get it, not to multiplicity itself (so we already have that impact in). Or let me know if I am wrong.

For now I took 2.0.34 sources from CPAN, recompiled and installed as a second perl instance in /usr/local + redirected by symlink all things like /usr/bin/perl, /usr/bin/cpan, /usr/lib/libperl.so* to my instance in /usr/local - since I cannot remove the perl xbps package because it is required by apache and other packages.

I re-compiled with no thread support at all (`-Uusethreads`), with apache in prefork mode, and with mod_perl built as dynamic module (=> using libperl.so) .. works well 🙂

I find that dual install method a bit awkard though, especially after I found out that whatever order is specified in $PATH, bash seems to always and blindly complete unqualified commands like `perl -v` `to /sbin/perl -v`, therefore bypassing my $PATH order !! (although `which perl` rightfully says `/usr/local/bin/perl` ..) !!
Not sure which mechanism is acting there, but this leaves a bad taste in my mouth.

If you see a better way, let me know.

Else yes, and in support of LAMP on Void Linux https://gist.github.com/adnan360/045d1e4c7619a1e1a9e779d6d35cca92, it would be good to modify our Perl packages with either `-Uusethreads` for no thread at all, or both `-Duseithreads -Dusemultiplicity`, so that it is easy to use mod_perl, and its persistent `ModPerl::Registry / ModPerl::RegistryPrefork` feature for performance.

**Comment by leahneukirchen** [comment]
According to the mod_perl documentation, mpm_prefork + Perl with only ithreads should work too; can you verify it doesn't?

**Comment by aaFn** [comment]
Yes, I checked already. This is why I came here 😁 :

Agree with you that https://perl.apache.org/docs/2.0/user/install/install.html#Prerequisites is ambiguous and seems to state that they don't care ...

But fact is that the command
`perl Makefile.PL MP_APXS=/usr/bin/apxs MP_APR_CONFIG=/sbin/apr-1-configMP_AP_CONFIGURE="--with-mpm=prefork"
`
does fail, with the error message I copied in my initial post at top, with that somewhat cryptic message. To make sure I opened their make generation code, and could confirm they want either none, or both, but not one of them.

And when I do (to force NO_THREADS)
`perl Makefile.PL MP_APXS=/usr/bin/apxs MP_APR_CONFIG=/sbin/apr-1-config MP_NO_THREADS=1 MP_AP_CONFIGURE="--with-mpm=prefork"`
that fails also in the same way ... so no choice but to recompile Perl with either none or both ... and I don't dare to touch their code to force things, as I am not sure of what is checked at later steps + things do not seem to be coded in a robust way on that side.

**Comment by leahneukirchen** [comment]
Ok, so it seems like perl-cross always sets usemultiplicity to undef, and we need to override this (with regular ./Configure, it should have been picked up by default).

Let's keep this in mind for the next rebuild; I don't think this niche application justifies a rebuild on its own.

**Comment by aaFn** [comment]
Agree. Meanwhile I am wroking aroundwithout too much hassle anyway, and learning a few things in the process, which is always good :-D

**Comment by leahneukirchen** [comment]
We could change this for the 5.36 rebuild, opinions?

**Comment by aaFn** [comment]
On my side, I am ok of course, and if you need me to test anything, let me know.

**Comment by leahneukirchen** [comment]
To be revisited for Perl 5.36.0/1.
