### ISSUE TITLE
Package Request: Hardened Malloc

### ISSUE THREAD

**Issue by apirusKde** [void-linux/void-packages#32913]
Please provide the *GrapheneOS hardened malloc* package, compiled with these flags so that it doesnt break app compatibility such as xorg, browsers, etc. (These are the flags that whonix *KICKSECURE'S BUILD* uses when it builds the hardened malloc) Without them everything would break because of linux. 

 dh_auto_build -- libhardened_malloc.so CONFIG_NATIVE=false CC=$(CC) CONFIG_SLAB_QUARANTINE_RANDOM_LENGTH=0 CONFIG_SLAB_QUARANTINE_QUEUE_LENGTH=0 CONFIG_GUARD_SLABS_INTERVAL=8

**Comment by apirusKde** [comment]
Also make it automatically set /etc/lib.so.preload file to this: /usr/lib/libhardened_malloc.so/libhardened_malloc.so

To be able to use it after installation. 

Or even better, make it replace the default malloc upon installation

**Comment by apirusKde** [comment]
Nice article, another reference to help you implement the package: 
https://madaidans-insecurities.github.io/guides/linux-hardening.html#hardened-malloc

**Comment by apirusKde** [comment]
Also this package could be used by default in void linux (it is used in kicksecure whonix by default) . Performance loss is none/~1%, no breakages. (When compilled with those flags)

**Comment by q66** [comment]
we're not going to change the default malloc

for musl mallocng in 1.2.x already obsoletes this anyway as far as I know, and if you want a better allocator in glibc, take it up with glibc

**Comment by apirusKde** [comment]
Well for musl it might be obsolete, but i would like it implemented in the glibc version
