### ISSUE TITLE
steam package error

### ISSUE THREAD

**Issue by apirusKde** [void-linux/void-packages#32928]
The steam package's shortcut points to /usr/bin/steam %u. That file doesnt exist there but is instead installed to ~/.local/share/.steam, ~/.steam Even after running steam.sh manually i couldnt fix it. I didnt want to bother too much with it.

**Comment by ericonr** [comment]
What shortcut do you mean? The desktop file?

How did you install steam? You should def have that executable.

**Comment by apirusKde** [comment]
Yes, the .desktop file points to that location. When ive ls /usr/bin no steam file was there. Ive got an error upon launch of steam, saying that the runtime could not be found, along those lines. Then a second error when typing bash steam.sh (home folder file), says that no setup.sh file is present(in some directory). I then went to that directory and setup.sh is there. Typed bash setup.sh and it looked like it did its job, extracted something, but still steam isnt functioning When ive deleted the steam folders from /home, then when executing the .desktop steam shortcut again, the folders reappear.

**Comment by apirusKde** [comment]
Also ive installed it through xbps, normally

**Comment by apirusKde** [comment]
I have just reinstalled void linux, and installed steam. It works as intended, normally now. I dont understand what has went wrong the first time. Closing the thread
