### ISSUE TITLE
flatpak package error

### ISSUE THREAD

**Issue by apirusKde** [void-linux/void-packages#32929]
Applications installed with flatpak, (without the --user flag, ive seen that has resolflved someones issue on a forum) they wont open at all. 
When run from the terminal i get this error: 
error: ldconfig failed, exit status 256

**Comment by paper42** [comment]
Please fill in the issue template

**Comment by ericonr** [comment]
Please show the specific application you're using and mention any changes you've made to your system. I use flatpak regularly and it works fine, so we need more info.

**Comment by ericonr** [comment]
And generally speaking you should install things with `--user`.

**Comment by apirusKde** [comment]
Ive installed org.valvesoftware.Steam and Librewolf. I will try in a moment to install apps with the --user flag. If that works, you should then update the docs

**Comment by paper42** [comment]
I install flatpak applications system wide and everything works fine. I just tried librewolf and it worked without a problem. Did you modify your system somehow? Are you using alternative package managers (bedrock, nix, guix, etc.)? Are you ignoring some packages with `ignorepkg=`?

**Comment by apirusKde** [comment]
I am using xbps. Also i might have used octoxbps, the gui frontend but that most likely isnt the problem. Did you install it with the --user flag? Im gonna retry to install it in a moment, and will report back to you. I have just reinstalled void linux because ive messed up my system

**Comment by apirusKde** [comment]
Works upon reinstallation of void linux. Closing
