### ISSUE TITLE
chromium package error

### ISSUE THREAD

**Issue by apirusKde** [void-linux/void-packages#32930]
When launched, chromium says that some Api is missing and some features will be unavailable, at the top bar. It has presumably been compiled excluding it.
So it makes the chromium web store not to work great, and you are unable to log in with a google account (which is a good thing) .
My question is, if youre compiling it with some tweaks, why not include the ungoogled chromium's patchset by default? (You can still choose to not remove every google feature, but the bromite patches, the 0 phoning home, etc. are really great and should be the default in void linux in a browser)

**Comment by Duncaen** [comment]
We don't want patched browsers, the features are enabled because google disabled the apis.
