### ISSUE TITLE
mesa-ati-dri-32bit does not provide ICD File

### ISSUE THREAD

**Issue by ethragur** [void-linux/void-packages#3293]
### System

* system:
  Void 4.18.10_1 x86_64 AuthenticAMD uptodate hold rrrmFFFFF
  Radeon RX 570 Series (POLARIS10, DRM 3.26.0, 4.18.10_1, LLVM 6.0.1)
* package:  
  mesa-ati-dri-32bit-18.2.1_1

### Expected behavior

The x86_64 Package contains the file /usr/share/vulkan/icd.d/radeon_icd.x84_64.json, which is needed for running vulkan application.
Installing the multilib version of this package should also provide this file for 32bit. (/usr/share/vulkan/icd.d/radeon_icd.x86.json)

### Actual behavior

The multilib package (mesa-ati-dri-32bit) does not provide the file for 32bit vulkan (/usr/share/vulkan/icd.d/radeon_icd.x86.json), therefore using 32bit vulkan applications does not work out of the box.

### Steps to reproduce the behavior

Install the packages needed for 32bit vulkan: (mesa-ati-dri-32bit, vulkan-loader-32bit) and run a 32bit vulkan application (for example a 32bit windows executable with DXVK). 
![2018-10-02-091051_448x242_scrot](https://user-images.githubusercontent.com/9322165/46334133-34fdbf80-c623-11e8-8410-65fdd728de43.png)

After creating the file "/usr/share/vulkan/icd.d/radeon_icd.x86.json" with the following content:
`{
    "ICD": {
        "api_version": "1.1.70",
        "library_path": "/usr/lib32/libvulkan_radeon.so"
    },
    "file_format_version": "1.0.0"
}`
Starting the application works

**Comment by HadetTheUndying** [comment]
This issue is still present

**Comment by Johnnynator** [comment]
Question to myself, is lib32 an existant folder/symlink on i686 Void, if yes fixing this issue is adding the 32bit ICD to lib32filenames else we need to go the nvidia approach and only specify the lib filename and not the full path in the .ICD file.

This issue also affects AMDVLK

**Comment by HadetTheUndying** [comment]
I have no been able to fix this other than manually creating the file, the issue has been prsent in mesa and amdvlk for over 6 months now it appears.

**Comment by HadetTheUndying** [comment]
Can we get some context on the reference please? That's a lot ot read through.
