### ISSUE TITLE
Package Request: openjdk-17

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#32942]
Would be nice to include a newer java runtime thing, for compatibility with newer compiled java .jar's

**Comment by SevereOverfl0w** [comment]
I just started looking at this to try and kick it off.  It looks like we'll need to build 16 first (and presumably therefore, 15, 14, 13 and 12).

**Comment by raedwulf** [comment]
@SevereOverfl0w @sgn : I've started work on this, but idk how much time I can spend to polish this up... #34390

**Comment by HadetTheUndying** [comment]
> @SevereOverfl0w @sgn : I've started work on this, but idk how much time I can spend to polish this up... #34390

I'll take a look at your work tomorrow. I'd be willing to help get this working but I also do not have time to maintain it if it's going to be super involved.
