### ISSUE TITLE
Package request: font-jost

### ISSUE THREAD

**Issue by thenktor** [void-linux/void-packages#32963]
### About
_Jost*_ is an original font created by _indestructible type*_. It is inspired by 1920s German sans-serifs. Jost* aims to keep the attitude of Futura rather than the exact design. Futura was designed to be functional in its day, and in that spirit, Jost* aims to be as functional as possible in the digital era. For that reason it deviates from the exact designs of Paul Renner, favoring, for example, a larger x-height or more balanced capital forms. It also includes some features which would not have been possible in the era of Futura. 

### Website
https://indestructibletype.com/Jost.html

### Fonts
https://github.com/indestructible-type/Jost

### Why?
Because it looks great :smile:

**Comment by paper42** [comment]
From [Quality Requirements in Manual.md](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements):
> New fonts may be accepted if they provide value beyond aesthetics (e.g. they contain glyphs for a script missing in already packaged fonts).

Does this font provide value beyond just looking nice? If not, installing the font manually is really easy - downloading and extracting an archive to a specific directory.

**Comment by thenktor** [comment]
Sorry, probably no additional glyphs. Missed that. Thanks!
