### ISSUE TITLE
ncurses-devel doesn't work with pkg-config

### ISSUE THREAD

**Issue by LAC-Tech** [void-linux/void-packages#32987]
### System

* xuname:  
  Void 4.4.0-19041-Microsoft x86_64 GenuineIntel/VM notuptodate rFF
* package:  
  ncurses-devel-6.2_4

### Expected behavior
` pkg-config --print-provides ncurses`
should return output

Note that ` pkg-config --print-provides ncursesw` works as expected.

### Actual behavior
Package ncurses was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncurses.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncurses' found

### Steps to reproduce the behavior
xbps-install ncurses-devel
xbps-install pkg-config
pkg-config --print-provides ncurses

**Comment by LAC-Tech** [comment]
rcf from the IRC channel recommended this patch. I'm brand new to void so can't comment.

https://rcf.sdf.org/pb/t/f578b109

**Comment by q66** [comment]
not a bug (see linked PR)
