### ISSUE TITLE
easyeffects-6.1.0_1: Equalizer not working

### ISSUE THREAD

**Issue by thenktor** [void-linux/void-packages#32991]
### System

* xuname:  Void 5.13.18_1 x86_64 GenuineIntel uptodate rFF
* package: easyeffects-6.1.0_1

### Expected behavior
All filters should work

### Actual behavior
Equalizer does not work

### Infos
It seems there is a missing dependency. Easyeffects says it uses *Linux Studio Plugins* for the equalizer, but I cannot see any *lsp* package installed or in repository.
Furthermore when starting Easyeffects a lot of messages appear:
```txt
[...]
(easyeffects:18912): easyeffects-WARNING **: 11:26:39.890: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr port symbol not found: ftr_15

(easyeffects:18912): easyeffects-WARNING **: 11:26:39.891: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr port symbol not found: fmr_15

(easyeffects:18912): easyeffects-WARNING **: 11:26:39.891: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr port symbol not found: sr_15

(easyeffects:18912): easyeffects-WARNING **: 11:26:39.895: lv2_wrapper: http://lsp-plug.in/plugins/lv2/para_equalizer_x32_lr port symbol not found: fr_16
[...]
```

**Comment by paper42** [comment]
EasyEffects uses many different projects for its plugins, not having all of them is not a problem, because each plugin page tells you what to install. The issue here is that we don't have lsp-plugins packaged yet, but there has been some work - #29932 and #31664, so you can build it from the PRs for now.

**Comment by thenktor** [comment]
I've downloaded the lv2 binary distribution from https://lsp-plug.in/?page=download and copied the files to `/usr/local/lib64/lv2/lsp-plugins.lv2`. This fixes the equalizer for me.
