### ISSUE TITLE
texlive-bin should install the infraonly scheme by default

### ISSUE THREAD

**Issue by balejk** [void-linux/void-packages#33048]
Currently `texlive-bin` packages use the `small` scheme by default (as defined by the build options in the templates), which installs about three hundred packages. As this action is executed immediately on installation by the `INSTALL` script, it is not possible to set any options and in my case the closest mirror is detected incorrectly which results in the installation taking up to 25 minutes.

It would make more sense to me if the post-install hook installed as little as possible, which should be provided by the `infraonly` scheme, so that the user could install only the TeX packages he is interested in (for example I don't require LaTeX and so always uninstall it with `tlmgr` anyway after the installation of the `texlive-bin` package finishes) and possibly make some changes to settings beforehand, such as manually selecting a TeX Archive mirror.

I can open a pull request if this is approved.

**Comment by st3r4g** [comment]
> As this action is executed immediately on installation by the `INSTALL` script, it is not possible to set any options and in my case the closest mirror is detected incorrectly which results in the installation taking up to 25 minutes.

I had this issue once, worked around it by using `--unpack-only` and continuing manually. But it was a mess because I couldn't set the package state to configured, and any system update tried to reinstall it. So I'm interested in this.

This would add, in most cases, just one command `tlmgr install scheme-xyz` to have a working install, right?

**Comment by balejk** [comment]
> This would add, in most cases, just one command `tlmgr install scheme-xyz` to have a working install, right?

Basically. To have even more fine-grained control over what will be installed, one could instead specify collections (`tlmgr show collections`) or even individual packages, although this is probably impractical, unless one uses TeX for something very specific.

**Comment by balejk** [comment]
@leahneukirchen Any thoughts on this or shall I close it?

**Comment by leahneukirchen** [comment]
Sorry, I must have missed this. Sounds reasonable, I'll check it out.

**Comment by balejk** [comment]
Thanks!
