### ISSUE TITLE
Package Request: river

### ISSUE THREAD

**Issue by subsetpark** [void-linux/void-packages#33060]
A dynamic tiling Wayland window manager. 

https://github.com/ifreund/river

**Comment by kkga** [comment]
There are no tagged releases yet, so if you want this to be packaged potentially, you'll have to ask for a tagged release upstream.

**Comment by Duncaen** [comment]
You probably don't have to ask, the maintainer is already contributing to void and they would have packaged it already if its ready.

**Comment by ifreund** [comment]
As duncaen says, I (the river maintainer) use and contribute to void linux. I'll package river myself once I tag the first 0.1.0 release upstream. There's not much blocking that release aside from my finite amount of free time currently.

**Comment by kkga** [comment]
Looks like a package is coming out soon? https://isaacfreund.com/blog/river-intro/
I've been wanting to try it for a while.

**Comment by ifreund** [comment]
Yep, It's late here and I'm off to sleep. I should have time to put up a void-packages PR tomorrow.

**Comment by ifreund** [comment]
River is now included in #29288.
