### ISSUE TITLE
Package Request: dav1d

### ISSUE THREAD

**Issue by maxice8** [void-linux/void-packages#3310]
Not really, just got interest and will keep this here until it gets a proper release

http://www.jbkempf.com/blog/post/2018/Introducing-dav1d
https://code.videolan.org/videolan/dav1d

**Comment by cr6git** [comment]
````
# Template file for 'dav1d'
pkgname=dav1d
version=0.0.0.20180929
revision=1
_commit=fc6eae6e51e3a3e914c807697a781bff702fbaea
wrksrc="dav1d-${_commit}"
build_style=meson
short_desc="Cross-platform Decoder, focused on speed and correctness"
maintainer="local <root@localhost>"
license="BSD-2-Clause"
homepage="https://code.videolan.org/videolan/dav1d"
distfiles="${homepage}/-/archive/${_commit}/dav1d-${_commit}.tar.bz2"
checksum=1d4454f47c8834ab0e9cc0f6eb1aa5685907e36ab96013f614f7bb4aee1136f1

case "$XBPS_TARGET_MACHINE" in
	i686*|x86_64*) hostmakedepends="nasm";;
esac

post_install() {
	vlicense COPYING
}

dav1d-devel_package() {
	depends="${sourcepkg}>=${version}_${revision}"
	short_desc+=" - development files"
	pkg_install() {
		vmove usr/include
		vmove usr/lib/pkgconfig
		vmove "usr/lib/*.so"
	}
}
````

**Comment by maxice8** [comment]
On Tue, Oct 02, 2018 at 01:00:00PM +0000, cr6git wrote:
> ````
> # Template file for 'dav1d'
> pkgname=dav1d
> version=0.0.0.20180929
> revision=1
> _commit=fc6eae6e51e3a3e914c807697a781bff702fbaea
> wrksrc="dav1d-${_commit}"
> build_style=meson
> short_desc="Cross-platform Decoder, focused on speed and correctness"
> maintainer="local <root@localhost>"
> license="BSD-2-Clause"
> homepage="https://code.videolan.org/videolan/dav1d"
> distfiles="${homepage}/-/archive/${_commit}/dav1d-${_commit}.tar.bz2"
> checksum=1d4454f47c8834ab0e9cc0f6eb1aa5685907e36ab96013f614f7bb4aee1136f1
> 
> case "$XBPS_TARGET_MACHINE" in
> 	i686*|x86_64*) hostmakedepends="nasm";;
> esac
> 
> post_install() {
> 	vlicense COPYING
> }
> 
> dav1d-devel_package() {
> 	depends="${sourcepkg}>=${version}_${revision}"
> 	short_desc+=" - development files"
> 	pkg_install() {
> 		vmove usr/include
> 		vmove usr/lib/pkgconfig
> 		vmove "usr/lib/*.so"
> 	}
> }
> ````
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/3310#issuecomment-426263953

No need, i will wait for a stable release, it is just something of interest

**Comment by cr6git** [comment]
@maxice8 no problem. :+1:

**Comment by maxice8** [comment]
this is done
