### ISSUE TITLE
build package mysql-workbench-community cmake get error

### ISSUE THREAD

**Issue by bastomiadi** [void-linux/void-packages#33123]
### System

* xuname:  
  Void 5.13.19_1 x86_64 GenuineIntel notuptodate rrFFFFF
* package:  
  mysql-workbench-community
### Expected behavior
Can Build from src
### Actual behavior
error when build with cmake
### Steps to reproduce the behavior

- i make a new dir inside : ~/workspace/void-packages/srcpkgs : sudo mkdir mysql-workbench-community
- then inside that folder, i make a new file 'template' with : sudo nano template : 

pkgname=mysql-workbench-community
version=8.0.26
revision=1
wrksrc=${pkgname}-${version}-src
build_style=cmake
short_desc="MySQL Workbench is a unified visual tool for database architects, developers, and DBAs"
maintainer="Bastomi Adi Nugroho <bastomiadi@gmail.com>"
license="GPL-2.0-or-later, GPL-3.0-or-later"
homepage="https://www.mysql.com/products/workbench"
distfiles="https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-${version}-src.tar.gz"
checksum="529e385af60a4956045c4533e85f7d6e306230668497ba3e69d032e7c0eaecf8"

- i goto ~/workspace/void-packages/, and execute : ./xbps-src pkg -f mysql-workbench-community
- but get error : 
❯ ./xbps-src pkg -f mysql-workbench-community
=> xbps-src: updating repositories for host (x86_64)...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/nonfree/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/debug/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> mysql-workbench-community-8.0.26_1: removing autodeps, please wait...
=> mysql-workbench-community-8.0.26_1: building [cmake] for x86_64...
   [host] cmake-3.21.1_1: found (https://alpha.de.repo.voidlinux.org/current)
   [host] ninja-1.10.2_2: found (https://alpha.de.repo.voidlinux.org/current)
=> mysql-workbench-community-8.0.26_1: installing host dependencies: cmake-3.21.1_1 ninja-1.10.2_2 ...
=> mysql-workbench-community-8.0.26_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> mysql-workbench-community-8.0.26_1: running pre-configure hook: 01-override-config ...
=> mysql-workbench-community-8.0.26_1: running pre-configure hook: 02-script-wrapper ...
=> mysql-workbench-community-8.0.26_1: running do_configure ...
CMake Error: The current CMakeCache.txt directory /builddir/mysql-workbench-community-8.0.26-src/build/CMakeCache.txt is different than the directory /home/milosz/Projects/workbench/master-itch/src/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/builddir/mysql-workbench-community-8.0.26-src/CMakeLists.txt" does not match the source "/home/milosz/Projects/workbench/master-itch/src/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
=> ERROR: mysql-workbench-community-8.0.26_1: do_configure: 'CFLAGS="-DNDEBUG ${CFLAGS/ -pipe / }" CXXFLAGS="-DNDEBUG ${CXXFLAGS/ -pipe / }" cmake ${cmake_args} ${configure_args} ${wrksrc}/${build_wrksrc}' exited with 1
=> ERROR:   in do_configure() at common/build-style/cmake.sh:67

![Screenshot from 2021-09-26 02-39-37](https://user-images.githubusercontent.com/13336571/134784189-bf242348-a1c5-444b-b292-1256f101aa4d.png)

**Comment by Chocimier** [comment]
Tarball they published shouldn't contain build/ directory. You would need to remove it before doing anything else.
Not an issue with xbps.

**Comment by bastomiadi** [comment]
So, i must try another method.
