### ISSUE TITLE
Package Request: himalaya (mail client)

### ISSUE THREAD

**Issue by timsofteng** [void-linux/void-packages#33154]
Hello.
Is it possible to prepare package for this mail client?

https://github.com/soywod/himalaya

**Comment by paper42** [comment]
#32548

**Comment by kkga** [comment]
great client, using it every day, so I'd love to see the PR merged too :)

**Comment by paper42** [comment]
#32548 is now merged

**Comment by timsofteng** [comment]
> great client, using it every day, so I'd love to see the PR merged too :)

hope it will have tui soon

**Comment by timsofteng** [comment]
> #32548 is now merged

may I close it?
