### ISSUE TITLE
Iwd doesn't connect to the wifi after s3 resume

### ISSUE THREAD

**Issue by timsofteng** [void-linux/void-packages#33175]
### System

* xuname:  
  Void 5.13.19_1 x86_64 GenuineIntel notuptodate rrFFF
* package:  
  iwd-1.18_1

### Expected behavior
Should automatically starts after suspend and resume.

### Actual behavior
Iwd doesn't automatically reconnect to wi-fi network after s3 resume. 
`sudo sv restart iwd` helps.

### Steps to reproduce the behavior
1. Sway wm.
2. dhcpd, acpid, seatd, iwd services enabled.
3. `zzz`.
4. Wake your system.

**Comment by ScrelliCopter** [comment]
I'm affected by this too, worked fine under 1.17_1.

**Comment by markstos** [comment]
It's also a problem on Arch Linux with `iwd 1.22`.

**Comment by markstos** [comment]
I documented the config I use to have `iwd` automatically restarted upon resume, which seems to be working for me:

https://unix.stackexchange.com/a/688246/20239

If there's no harm in restarted `iwd` upon resume, a version of the idea could be shipped with the package. This could be done by patching the shipped `iwd.service` file or shipping a drop-in unit which lives the original systemd service file intact, but adds a `After=` and `WantedBy=` directive to cause the service to be restarted after suspend.
