### ISSUE TITLE
Bug: Native system notifications doesn't work in Chromium (sway)

### ISSUE THREAD

**Issue by timsofteng** [void-linux/void-packages#33181]
### System

* xuname:  
  *Void 5.13.19_1 x86_64 GenuineIntel notuptodate rrFFF*
* package:  
  *chromium-94.0.4606.61_1*
### Expected behavior
Should sent notifications throw native system notification (mako in this case)

### Actual behavior
Send chromium own notifications.

### Steps to reproduce the behavior
1. Wayland, sway.
2. Enable dbus and seatd services.
3. Open chromium with flag `--enable-native-notifications`.
4. Try to send notifications with any site. (e.g  [this](https://www.bennish.net/web-notifications.html).

### Additional info.
Here is error from terminal which I guess inform about trouble with connection to DBus.
`Failed to call method: org.freedesktop.DBus.NameHasOwner: object_path= /org/freedesktop/DBus: unknown error type:`

**Comment by codingHahn** [comment]
Have you started any software to show notifications, for example dunst?

**Comment by timsofteng** [comment]
> Have you started any software to show notifications, for example dunst?

Sure.
Mako.
Telegram works fine with mako notifications.

Btw, if I invoke
`dbus-launch chromium --enable-native-notifications`
it works.

**Comment by Duncaen** [comment]
Both your issues sound like they are related to the dbus session bus not being setup correctly.

**Comment by timsofteng** [comment]
> Both your issues sound like they are related to the dbus session bus not being setup correctly.

Maybe. I don't know.
I just wanna figure out.
