### ISSUE TITLE
Goodix Touchscreen support?

### ISSUE THREAD

**Issue by fiatisdead** [void-linux/void-packages#33277]
Hi, 
I'm new to Void, a friend introduced last week and also mentioned work ongoing with PlagueOS.
I just come to test the void-live-x86_64-musl-20210218-mate.iso but noticed touchscreen isnt working. 

This works out the box on Ubuntu Mate 20.04.1 LTS and I wonder if you can add support for Goodix Touchscreen or whether you can point me in the right direction to try to get it working. Hardware: GPD P2 Max

My plan is to move from Ubuntu Mate as daily driver to Void Linux hopefully if I can get everything working.

**Comment by fiatisdead** [comment]
> It should be working, I think... Our kernels have `CONFIG_TOUCHSCREEN_GOODIX=m`. Can you try `modprobe goodix` to see if it does anything?

It returns nothing.

**Comment by biopsin** [comment]
what does `lsmod | grep goodix` show after loading the module?

**Comment by fiatisdead** [comment]
`lsmod | grep goodix` returns:
goodix                 32768  0

`sudo dmesg` returns:

```
4.351333] usb 1-7: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    4.369687] Goodix-TS i2c-GDIX1002:00: supply AVDD28 not found, using dummy regulator
[    4.369726] Goodix-TS i2c-GDIX1002:00: supply VDDIO not found, using dummy regulator
[    4.370131] Goodix-TS i2c-GDIX1002:00: i2c test failed attempt 1: -121
[    4.392201] Goodix-TS i2c-GDIX1002:00: i2c test failed attempt 2: -121
[    4.415552] usb 2-3.3: reset SuperSpeed Gen 1 USB device number 3 using xhci_hcd
[    4.456656] r8152 2-3.3:1.0: load rtl8153a-4 v2 02/07/20 successfully
[    4.481447] r8152 2-3.3:1.0 eth0: v1.11.11
[    4.500219] Goodix-TS i2c-GDIX1002:00: i2c test failed attempt 1: -121
[    4.522265] Goodix-TS i2c-GDIX1002:00: i2c test failed attempt 2: -121
[    4.544040] Goodix-TS i2c-GDIX1002:00: I2C communication failure: -121
[    4.544663] Goodix-TS: probe of i2c-GDIX1002:00 failed with error -121
[    4.553892] usb 1-1.2: new high-speed USB device number 5 using xhci_hcd
```

**Comment by biopsin** [comment]
did not dig futher but [[bug](https://bugzilla.kernel.org/show_bug.cgi?id=209061)] seems unresolved

**Comment by fiatisdead** [comment]
I believe [this may ](https://github.com/torvalds/linux/commit/a0bf06dc51dbbc5ad182b1bcf4d879db8d297c5e) fix the issue but I unfortunately don't have the knowledge and skills to be able to work out what to do to apply this patch. 
Any help would be very much appreciated.

**Comment by biopsin** [comment]
@fiatisdead You'll have to help yourself as no one has the hardware.
Start with https://github.com/void-linux/void-packages#quick-start, then
save the patch in ..void-packages/srcpkgs/linux5.XX/patches and build the kernel with xbps-src
and install from ..void-packages/hostdir/binpkgs
