### ISSUE TITLE
Lxdm and other login manager/display manager 

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#33317]
I am a french user of VoidLinux and unfortunately the keybord is always set in us disposition ! I tried a lot of things to solve that problem like create a configuration file for x11 but nothing worked. Then, i tried to use other display manager (lightdm, sddm, gdm ) and always the same problem even if when the system starts i see that runit set the keyboard in fr. 

Thanks again

**Comment by tnut** [comment]
The runit service will set the keyboard in fr for the non graphical console.  The installer will not set the keyboard for the X server / Wayland. You need to google for that. This problem is the result of a lack of documentation on the subject. Nothing is mention.

**Comment by paper42** [comment]
This issue is not relevant for this repository. If you believe this should be mentioned in the documentation, please open an issue in void-docs. If this should be fixed in the installer (which might make sense for the XFCE version, but might be a bit confusing), please open an issue in void-mklive.
