### ISSUE TITLE
bitlbee-discord - bug with latest glib - needs updating

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#33412]
`Void 5.13.19_1 x86_64 AuthenticAMD uptodate rrFFF`

package: `bitlbee-discord-0.4.3_1`

A change in glib has broken this release as discussed here: sm00th/bitlbee-discord/issues/226 . 

Just tested with the latest build and it resolves this issue.

**Comment by shikhar13012001** [comment]
is this issue still open ? Can I work on this ?

**Comment by ericonr** [comment]
I don't think anyone's started working on it yet. Feel free!

**Comment by shikhar13012001** [comment]
> I don't think anyone's started working on it yet. Feel free!

that's great, Could you brief me on the targeted files and summary what should I do?
