### ISSUE TITLE
Solaar udev rules are not applied

### ISSUE THREAD

**Issue by Meister1593** [void-linux/void-packages#33422]
### System

* xuname:  
  Void 5.13.19_1 x86_64 AuthenticAMD notuptodate rrrmFFFFF
* package:  
  Solaar-1.0.6_1

### Expected behavior
 When running program for first time, you might only see error message (example bellow) once about re-plugging your usb dongle for mouse and afterwards it shouldn't say about that, allowing detection and working with mouse properly
### Actual behavior
 When running program it always shows error message bellow, and you can't do much because of it.
![image](https://user-images.githubusercontent.com/7141787/136538008-1b138a22-de73-43a5-84d2-884e5152019e.png)

### Steps to reproduce the behavior
1. Install Solaar
2. Open Solaar
3. Error message appears every time

or

1. Install Solaar
2. Reload and trigger udev rules (`udevadm control --reload-rules && udevadm trigger`)
3. Open Solaar
4. Error message appears every time

### Potential clues
I thought that rules were not applied because of some issues with app itself, but looking at Solaar's archive contents (it had rules.d with rules), this is not the case.
But then i checked out where rules actually are installed in system, and they went into `/usr/share/solaar/udev-rules.d/42-logitech-unify-permissions.rules` instead of `/usr/lib/udev/rules.d/42-logitech-unify-permissions.rules`

After that i configured udev to run with debug logging (probably not needed) and tested with udevadm the same device (`/dev/hidraw3`), it gave me a list of rules that it reads and there was no `/usr/share/solaar/udev-rules.d` path

Lastly, i checked maybe package had this - and it did, in [this](https://github.com/void-linux/void-packages/commit/5ff792f86eab693bbe649de9ae8864e3b6449c3c#diff-d076aad4591896aba208d138d3ba5b10b6b2a0c0311dcc2e9937f54c6f300d25) commit it had copying rules to proper path (as well as [here](https://github.com/void-linux/void-packages/blob/dd122baf86f513f326cb6d99657c12d8785bef75/srcpkgs/Solaar/template). But then at [this](https://github.com/void-linux/void-packages/blob/c33c5bc603b00c75e936e72300642d6fb84dcbdd/srcpkgs/Solaar/template) commit this has been changed and important rule copying just got deleted.
Was it intentional or just a mistake?

**Comment by NeelChotai** [comment]
Not sure why the udev rules were removed, they're not installed by setup.py so far as I can tell, maybe there were before. The reason they exist in `share` is probably because of https://github.com/pwr-Solaar/Solaar/blob/b3c3ad02c8f00c685b77ad85a3ac907d204d60a2/setup.py#L26

I'm opening an MR to add the udev rules back and update the version.
