### ISSUE TITLE
RetroArch 1.7.5 – Released! - Update?

### ISSUE THREAD

**Issue by MirceaMx** [void-linux/void-packages#3353]
Here is the [release info](https://www.libretro.com/index.php/retroarch-1-7-5-released/) (updated 24H ago).

**Comment by maxice8** [comment]
Make a PR updating it or wait for someone to do it.

we have void-updates to tell us about package updates 

```
retroarch             1.7.3 -> 1.7.4                  http://www.libretro.com/                                                   
retroarch             1.7.3 -> 1.7.5                  2018-10-02                                                                 http://www.libretro.com/
```

**Comment by MirceaMx** [comment]
I'm sorry but I don't know what "PR" (only Public Relations comes to mind).
