### ISSUE TITLE
Chromium CFI

### ISSUE THREAD

**Issue by anon-lestat** [void-linux/void-packages#33579]
Chromium on void linux has broken CFI with LLVM 12.0.1.

As illustrated by its template starting with line 225:
# segfaults with llvm-12.0.1
		'is_cfi=false'
		'use_thin_lto=false'
		'use_cfi_icall=false'
		'chrome_pgo_phase=0'

Even if it cant be compiled as of now, fixing it would be extremely beneficial for users who self-compile, because CFI is a very significant and important feature.

**Comment by q66** [comment]
if it's not an actual build option, it's not supported

**Comment by anon-lestat** [comment]
@q66 wdym its not an actual build option? Its supposed to be there but LLVM is breaking it.

**Comment by q66** [comment]
it's not an xbps-src build option (maybe learn about those before talking shit behind my back on discord), so we don't support it, we don't and can't support random combos that users might patch in and we are also not responsible for compiler crashes that arise from unsupported configurations

**Comment by anon-lestat** [comment]
@q66 okay so. I wasnt talking shit haha, i called u a bastard sure and im sorry if you took it the wrong way but i didnt mean it to be insulting. CFI comes with chromium [link](https://www.chromium.org/developers/testing/control-flow-integrity).

U can see them being disabled in chromium template line 225 because atm llvm breaks it. 

chromium template starting line 225:
segfaults with llvm-12.0.1
	'is_cfi=false'
	'use_thin_lto=false'
	'use_cfi_icall=false'
	'chrome_pgo_phase=0'

**Comment by anon-lestat** [comment]
https://github.com/archlinux/svntogit-packages/commit/bfe890af9382031a5ea33e7552385952cd0f8077

arch for example

**Comment by q66** [comment]
it's disabled because it's broken, and supported on exactly 1 architecture and 1 compiler, and requires the whole thing to be built with LTO, and additionally you're using a libc officially unsupported by chromium

so, this is a wontfix from our side
