### ISSUE TITLE
Package Request: Clevis

### ISSUE THREAD

**Issue by Barbaross93** [void-linux/void-packages#33636]
[Clevis](https://github.com/latchset/clevis) is an automated encryption framework allowing encryption through various methods such as TANG, TPM 2.0, and Shamir secret sharing. Additionally, clevis can be used to bind one of these methods to automatic decryption of LUKS volumes through udisks2 and more notably, dracut.

Personally, I'd love to use this for auto-decryption of my luks drive through my TPM 2.0, of which I'm unaware of any tools already serving this purpose in the repos (trousers is specifically for TPM 1.2).

**Comment by jhe2** [comment]
I have created a [PR for clevis](https://github.com/void-linux/void-packages/pull/51359).

**Comment by classabbyamp** [comment]
#51359
