### ISSUE TITLE
hplip: incompatibility with python3.10

### ISSUE THREAD

**Issue by alandiwix** [void-linux/void-packages#33700]
See https://bugs.launchpad.net/hplip/+bug/1933973
There are several issues in hplip codebase, the one I encounter personally is:
```
Scanning...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/share/hplip/scan/sane.py", line 548, in run
    st, t = self.dev.readScan(readbuffer)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Reading data: [\       
```
The error
```
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```
is common among those. Some other distributions managed to solve that, Fedora's patch for example:
https://launchpadlibrarian.net/546031954/hplip-pyssizet_clean.patch
Is it possible to do the same in Void?

**Comment by alandiwix** [comment]
@ericonr would be nice if someone else could fix this.

**Comment by ahesford** [comment]
Should be closed in https://github.com/void-linux/void-packages/commit/6f33e3848d8d0df38e722ba480ad662ff490e646.
