### ISSUE TITLE
[RFC] kernel-libc-headers policy

### ISSUE THREAD

**Issue by ericonr** [void-linux/void-packages#33729]
We currently keep kernel-libc-headers stuck to the latest LTS kernel release. Is there any reason we can't update it for each kernel release, besides the time it takes to build cross toolchains?

**Comment by q66** [comment]
why would we do that?

**Comment by ericonr** [comment]
So users and programs can take advantage of advancements in `linux` more easily, like the addition of landlock and such.

**Comment by q66** [comment]
in that case, worry about updating musl first
