### ISSUE TITLE
Broken and missing options for qemu package

### ISSUE THREAD

**Issue by flupe** [void-linux/void-packages#33728]
### System

* xuname:  Void 5.13.19_1 x86_64 GenuineIntel uptodate rFFFFFFF
* package:  qemu

### Expected behavior

Disabling all options at build should work fine.

### Actual behavior

There is [a typo in the template file](https://github.com/void-linux/void-packages/blob/master/srcpkgs/qemu/template#L72), which fails to build when the `jack` option is disabled.

### Steps to reproduce the behavior

```
./xbps-src -o ~jack pkg qemu
```
---------

A lot of options are still missing, like the ability to not depend on `pulseaudio`, `bluetooth`, `X11` and the likes. More generally, I think it would be beneficial to have a `qemu-headless` version will all options disabled. I would be willing to work on a PR if need be.

**Comment by leahneukirchen** [comment]
I would like to propose a different solution: Qemu 6 supports `--enable-modules`, which allows splitting Qemu into two dozen packages so you can install exactly what you need (currently an install is over 1GB...).

E.g. Alpine does this: https://git.alpinelinux.org/aports/tree/community/qemu/APKBUILD
yielding: https://pkgs.alpinelinux.org/package/edge/community/x86_64/qemu

cc @Hoshpak.

**Comment by ScrelliCopter** [comment]
Since the typo is my fuckup I submitted a PR to address it.
+1 for Leah's proposal

**Comment by Hoshpak** [comment]
Splitting the package into modules sounds good to me. However I don't use any VMs on my Void machines these days anymore and doubt that I will have time to take a deeper look into this at least until the end of the year. If anyone's interested in preparing and testing the necessary changes, please do so. It also would be fine if anyone wanted to permanently take over maintenance of the package.
