### ISSUE TITLE
python3-nose not functional with python 3.10

### ISSUE THREAD

**Issue by TinfoilSubmarine** [void-linux/void-packages#33788]
### System

* xuname:  
  Void 5.13.19_1 x86_64 AuthenticAMD notuptodate rrmFFFFFFFFFFFFFFFFF
* package:  
  *affected package(s) including the version*: ``python3-nose-1.3.7_7``, ``python3-pytest-6.2.5_2``

### Expected behavior
I should be able to install `python3-nose` and run `import nose`, or run `./xbps-src pkg python3-pytest -Q` and have tests run successfully.

### Actual behavior
When importing in REPL:
```
Python 3.10.0 (default, Oct  9 2021, 12:07:44) [GCC 10.2.1 20201203] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/usr/lib/python3.10/site-packages/nose/core.py", line 153
    print "%s version %s" % (os.path.basename(sys.argv[0]), __version__)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```
When testing `python3-pytest`: <see attached log>
[pkg-python3-pytest.txt](https://github.com/void-linux/void-packages/files/7428572/pkg-python3-pytest.txt)

### Steps to reproduce the behavior
1. Install `python3-nose`
2. run `import nose` in python REPL.

OR
1. Build `python3-pytest` with xbps-src with testing enabled: `./xbps-src pkg python3-pytest -Q`

**Comment by Johnnynator** [comment]
Imo we should just drop it, I don't think nose is valuable enough to patch it and nothing depends on it at runtime

**Comment by ahesford** [comment]
Let's keep this around awhile longer. There are still some packages that use `python3-nose` for testing and I don't want to break their checks. I will drop `python-nose` since no templates mention the Py2 package and will fix `python3-nose` for now.
