### ISSUE TITLE
[BIKESHED] curl license file location

### ISSUE THREAD

**Issue by the-maldridge** [void-linux/void-packages#33781]
In re-imagining what build infrastructure around xbps-src looks like, having the ability to run lots of things inside the ethereal chroot becomes appealing.  Everything I've wanted to do so  far has worked, but for doing an HTTP post of files it would be ideal to have curl in the chroot.  Thoughts on adding a `chroot-curl` ?

**Comment by sgn** [comment]
> IYou can't install `curl` afterwards if it hasn't been built yet

libcurl is in stage 2 chroot, so it's built definitely.

If we want to provide it in builders, we can put current `curl` binary somewhere not in `$PATH`?

**Comment by sgn** [comment]
Anyway, I notice license is distributed with `curl` package instead of `libcurl` package. So, we're doing copyright infringement by distribute `libcurl` without the copyright notice and condition?

**Comment by q66** [comment]
not particularly, arguably it's not required to ship the license files at all (e.g. Alpine does not ship them, with the claim being that the SPDX tags are enough)

but even then, the distribution of the software includes all subpackages, it should not be necessary to include the license in all of them

**Comment by sgn** [comment]
> but even then, the distribution of the software includes all subpackages, it should not be necessary to include the license in all of them

I'm not advocate to include the license in all of them, but ship the license with libcurl instead of curl

**Comment by ericonr** [comment]
> I'm not advocate to include the license in all of them, but ship the license with libcurl instead of curl

I think that's reasonable.
