### ISSUE TITLE
Transaction failed

### ISSUE THREAD

**Issue by sdfdfsfda** [void-linux/void-packages#33825]
bluez-5.62_2: unpacking ...
ERROR: bluez-5.62_2: [unpack] failed to extract file `./etc/sv/bluetoothd/log/supervise': Directory not empty
ERROR: bluez-5.62_2: [unpack] failed to extract files: Directory not empty
ERROR: bluez-5.62_2: [unpack] failed to unpack files from archive: Directory not empty
Transaction failed! see above for errors.

**Comment by Duncaen** [comment]
https://github.com/void-linux/void-packages/issues/33815
