### ISSUE TITLE
kodi VAAPI MPEG2 error

### ISSUE THREAD

**Issue by quicktrick** [void-linux/void-packages#33844]
Hello!

I have the same MPEG2 error in the Kodi log as described in this issue at the LibreELEC repository:  
[\[BUG\] Intel VAAPI and Hardware mpeg2video decoding not working](https://github.com/LibreELEC/LibreELEC.tv/issues/4732)

```
ERROR : VAAPI/vpp vaCreateConfig error: the requested VAProfile is not supported (12)
```

They somehow corrected this bug by fixing the Intel driver. I have no such error in the Kodi log on LibreELEC 10.0.

And could you please update the Kodi package to v.19.2 or 19.3?

**Comment by Goorzhel** [comment]
> And could you please update the Kodi package to v.19.2 or 19.3?
#34083
