### ISSUE TITLE
Godot: SkeletonIK behavior differs from official builds

### ISSUE THREAD

**Issue by curiousjunior** [void-linux/void-packages#33848]
### System

* xuname:  
  Void 5.13.19_1 x86_64 GenuineIntel notuptodate rrrmFFF
* package:  
  godot-3.3_2

### Expected behavior

No distortion in Godot 3.3.4 downloaded from either official site or Steam.

### Actual behavior

Each individual bone in the chain rotates by 180 degrees causing the mesh to distort when moving the target node forward, backward or left/right depending on the roll value set in Blender, I think this bug is caused by not using built-in copies of libraries.
![backward](https://user-images.githubusercontent.com/79333625/139588709-024801bb-4573-46bc-a73a-1c66a6c80ab7.png)
![forward](https://user-images.githubusercontent.com/79333625/139588723-c2b18f34-1695-4cc3-9cd3-10421c7db177.png)

### Steps to reproduce the behavior

[Godot project](https://github.com/void-linux/void-packages/files/7449037/iktest.tar.gz)
[Armature and model in Blender](https://github.com/void-linux/void-packages/files/7449039/blend.tar.gz)

**Comment by ericonr** [comment]
Can you try updating the void package to see if that's enough to fix it? I can look into creating a PR if not, then you only need to test it.
