### ISSUE TITLE
noise-repellent not found by Ardour

### ISSUE THREAD

**Issue by notthewave** [void-linux/void-packages#33854]
### System

* xuname:  
*Void 5.13.19_1 x86_64-musl GenuineIntel uptodate rDFFFFFFFFFFFFFFF*
* package:  
  *affected package(s) including the version*: ``noise-repellent-0.1.5_1``

### Expected behavior
noise-repellent is present in the correct directories after install

### Actual behavior
noise-repellent is not present after install

### Steps to reproduce the behavior
install noise-repellent
do ``xlocate noise-repellent``
see if output returns nothing

**Comment by notthewave** [comment]
@Breavyn

**Comment by paper42** [comment]
> install noise-repellent do `xlocate noise-repellent` see if output returns nothing

`xlocate` searches in the list of all files in default repositories, you probably wanted to use `xbps-query -f <pkgname>` which shows files installed by a package. 

This package is not supposed to install a binary, it's just an lv2 plugin:

void:
```
%: xbps-query -Rf noise-repellent
/usr/nrepel.lv2/manifest.ttl
/usr/nrepel.lv2/nrepel.so
/usr/nrepel.lv2/nrepel.ttl
```

arch:
```
/usr/lib/lv2/nrepel.lv2/manifest.ttl
/usr/lib/lv2/nrepel.lv2/nrepel.so
/usr/lib/lv2/nrepel.lv2/nrepel.ttl
/usr/share/doc/noise-repellent/README.md
```

Is it possible to move /usr/nrepel.lv2 to /usr/lib/lv2 like it's done in Arch? @Breavyn

**Comment by notthewave** [comment]
Oh ok. Ardour does not find it that way.

**Comment by paper42** [comment]
> Oh ok. Ardour does not find it that way.

@notthewave `mv /usr/nrepel.lv2 /usr/lib/lv2/` If this fixes your issue, could you submit a PR?

**Comment by Breavyn** [comment]
> Is it possible to move /usr/nrepel.lv2 to /usr/lib/lv2 like it's done in Arch?

They were in the correct location in previous versions. Seems that it has been fixed [upstream](https://github.com/lucianodato/noise-repellent/issues/68), but no release has been tagged since.

**Comment by paper42** [comment]
> [Relevant patch](https://github.com/lucianodato/noise-repellent/commit/7f5a8fbef48fed75b9168509a4e3f985ae878988#diff-30d8f6be6320feeacf686be94f48c70869b52630e01ea625f0f15adc0d57c3e4) if we want to float another one for this package.

Just putting mv to post_install() should be enough.

**Comment by notthewave** [comment]
But is it removed that way with xbps-remove?

**Comment by notthewave** [comment]
#33856
