### ISSUE TITLE
cura support blocker broken

### ISSUE THREAD

**Issue by zlice** [void-linux/void-packages#33867]
### System

* xuname:
`Void 5.14.3 x86_64 AuthenticAMD uptodate hold rrrmFFFFFFFF`
  
* package:
`cura-4.11.0_2`

### Expected behavior

Support blocker works

### Actual behavior

Support blocker breaks on Void, works with AppImage

### Steps to reproduce the behavior

- Open stl file
- select part
- press `E` or select "support blocker"
- select part to block supports

### Crash

> 
> 2021-11-02 08:44:13,588 - DEBUG - [MainThread] cura.CuraApplication.run [853]: Booting Cura took 2.735138416290283 seconds
> 2021-11-02 08:44:13,588 - DEBUG - [JobQueueWorker [1]] cura.Machines.ContainerTree.run [174]: Started background loading of MachineNodes
> 2021-11-02 08:44:13,592 - DEBUG - [MainThread] cura.Machines.MachineErrorChecker._rescheduleCheck [155]: New error check scheduled.
> 2021-11-02 08:44:13,616 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [33]: Updating CustomQualityProfilesDropDownMenuModel.
> 2021-11-02 08:44:13,622 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [62]: Updating QualityProfilesDropDownMenuModel.
> 2021-11-02 08:44:13,829 - DEBUG - [MainThread] cura.Machines.Models.CustomQualityProfilesDropDownMenuModel._update [33]: Updating CustomQualityProfilesDropDownMenuModel.
> 2021-11-02 08:44:13,830 - DEBUG - [MainThread] cura.Machines.Models.QualityProfilesDropDownMenuModel._update [62]: Updating QualityProfilesDropDownMenuModel.
> 2021-11-02 08:44:13,880 - DEBUG - [MainThread] UM.Qt.QtRenderer._initialize [210]: Support for Vertex Array Objects: True
> 2021-11-02 08:44:13,882 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [112]: Initialized OpenGL subsystems.
> 2021-11-02 08:44:13,882 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [113]: OpenGL Version:  4.6 (Core Profile) Mesa 21.2.5
> 2021-11-02 08:44:13,882 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [114]: OpenGL Vendor:   AMD
> 2021-11-02 08:44:13,883 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [115]: OpenGL Renderer: AMD Radeon RX 5700 (NAVI10, DRM 3.42.0, 5.14.3, LLVM 12.0.1)
> 2021-11-02 08:44:13,883 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [116]: GLSL Version:    4.60.0
> 2021-11-02 08:44:13,883 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/uranium/resources/shaders/default.shader]...
> 2021-11-02 08:44:13,885 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/uranium/resources/shaders/selection.shader]...
> 2021-11-02 08:44:13,886 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/uranium/resources/shaders/select_face.shader]...
> 2021-11-02 08:44:13,888 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/uranium/resources/shaders/default.shader]...
> 2021-11-02 08:44:13,889 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/uranium/resources/shaders/composite.shader]...
> 2021-11-02 08:44:13,891 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/cura/resources/shaders/overhang.shader]...
> 2021-11-02 08:44:13,894 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/cura/resources/shaders/striped.shader]...
> 2021-11-02 08:44:13,899 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/cura/resources/shaders/transparent_object.shader]...
> 2021-11-02 08:44:13,902 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/cura/resources/shaders/striped.shader]...
> 2021-11-02 08:44:13,903 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/cura/resources/shaders/xray.shader]...
> 2021-11-02 08:44:13,904 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/cura/resources/shaders/xray_composite.shader]...
> 2021-11-02 08:44:13,907 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/uranium/resources/shaders/default.shader]...
> 2021-11-02 08:44:13,908 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/cura/resources/shaders/grid.shader]...
> 2021-11-02 08:44:13,910 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/uranium/resources/shaders/platform.shader]...
> 2021-11-02 08:44:13,916 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/cura/resources/shaders/xray.shader]...
> 2021-11-02 08:44:14,090 - DEBUG - [JobQueueWorker [1]] cura.Machines.ContainerTree.run [185]: All MachineNode loading completed
> 2021-11-02 08:44:14,132 - INFO - [MainThread] cura.Machines.MachineErrorChecker._setResult [214]: Error check finished, result = False, time = 0.5s
> 2021-11-02 08:44:14,539 - INFO - [MainThread] cura.CuraApplication.readLocalFile [1760]: Attempting to read file file:///tmp/mag_side.stl
> 2021-11-02 08:44:14,540 - INFO - [JobQueueWorker [2]] STLReader.STLReader.load_file [61]: Using legacy code to load STL data.
> 2021-11-02 08:44:14,542 - DEBUG - [JobQueueWorker [2]] UM.Mesh.MeshData.calculateNormalsFromVertices [558]: Calculating normals took 0.00018095970153808594 seconds
> 2021-11-02 08:44:14,542 - DEBUG - [JobQueueWorker [2]] STLReader.STLReader._read [105]: Loaded a mesh with 1476 vertices
> 2021-11-02 08:44:14,544 - DEBUG - [JobQueueWorker [2]] UM.Mesh.MeshData.approximateConvexHull [505]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0012967586517333984 seconds. 128 input vertices. 128 output vertices.
> 2021-11-02 08:44:14,552 - DEBUG - [JobQueueWorker [2]] UM.FileHandler.ReadFileJob.run [83]: Loading file took 0.0 seconds
> 2021-11-02 08:44:14,554 - DEBUG - [JobQueueWorker [2]] UM.Mesh.MeshData.approximateConvexHull [505]: approximateConvexHull(target_count=1024) Calculating 3D convex hull took 0.0012121200561523438 seconds. 128 input vertices. 128 output vertices.
> 2021-11-02 08:44:14,557 - DEBUG - [MainThread] UM.Operations.OperationStack.push [72]: <UM.Operations.AddSceneNodeOperation.AddSceneNodeOperation object at 0x7f0f0fd41fc0>, took 0ms
> 2021-11-02 08:44:14,561 - DEBUG - [MainThread] UM.Operations.OperationStack.push [72]: GroupedOp.(#=2) RotateOp.(node=<CuraSceneNode object: 'mag_side.stl'>,rot.=Q<0.0,0.0,0.0,w=4.0>) TranslateOp.(node=<CuraSceneNode object: 'mag_side.stl'>,trans.=<0.000,0.000,0.000>), took 0ms
> 2021-11-02 08:44:14,758 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/cura/resources/shaders/transparent_object.shader]...
> 2021-11-02 08:44:16,825 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/uranium/resources/shaders/toolhandle.shader]...
> 2021-11-02 08:44:19,166 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [60]: Loading [/usr/share/cura/resources/shaders/camera_distance.shader]...
> 2021-11-02 08:44:19,191 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
> 2021-11-02 08:44:19,192 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
> 2021-11-02 08:44:19,192 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/lib/python3.10/site-packages/UM/Qt/Bindings/MainWindow.py", line 186, in mousePressEvent
> 2021-11-02 08:44:19,192 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self._mouse_device.handleEvent(event)
> 2021-11-02 08:44:19,192 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/lib/python3.10/site-packages/UM/Qt/QtMouseDevice.py", line 25, in handleEvent
> 2021-11-02 08:44:19,192 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.event.emit(e)
> 2021-11-02 08:44:19,192 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/lib/python3.10/site-packages/UM/Signal.py", line 219, in emit
> 2021-11-02 08:44:19,192 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     self.__performEmit(*args, **kwargs)
> 2021-11-02 08:44:19,192 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/lib/python3.10/site-packages/UM/Signal.py", line 332, in __performEmit
> 2021-11-02 08:44:19,192 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     func(dest, *args, **kwargs)
> 2021-11-02 08:44:19,192 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/lib/python3.10/site-packages/UM/Controller.py", line 397, in event
> 2021-11-02 08:44:19,192 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     if self._active_tool and self._active_tool.event(event):
> 2021-11-02 08:44:19,193 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/lib/cura/plugins/SupportEraser/SupportEraser.py", line 91, in event
> 2021-11-02 08:44:19,193 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     picked_position = picking_pass.getPickedPosition(event.x, event.y)
> 2021-11-02 08:44:19,193 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/lib/python3.10/site-packages/cura/PickingPass.py", line 93, in getPickedPosition
> 2021-11-02 08:44:19,193 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     distance = self.getPickedDepth(x, y)
> 2021-11-02 08:44:19,193 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "/usr/lib/python3.10/site-packages/cura/PickingPass.py", line 81, in getPickedDepth
> 2021-11-02 08:44:19,193 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:     distance = output.pixel(px, py) # distance in micron, from in r, g & b channels
> 2021-11-02 08:44:19,193 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: TypeError: arguments did not match any overloaded call:
> 2021-11-02 08:44:19,193 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   pixel(self, QPoint): argument 1 has unexpected type 'float'
> 2021-11-02 08:44:19,193 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   pixel(self, int, int): argument 1 has unexpected type 'float'
> 2021-11-02 08:44:23,956 - DEBUG - [MainThread] cura.AutoSave._onTimeout [64]: Autosaving preferences, instances and profiles took 0.025233745574951172 seconds
> 2021-11-02 08:44:30,773 - ERROR - [MainThread] cura.CrashHandler._sendCrashReport [436]: Exception: SentrySDK is not available and the report could not be sent.
> 2021-11-02 08:44:30,774 - ERROR - [MainThread] cura.CrashHandler._sendCrashReport [436]: NoneType: None

**Comment by karl-nilsson** [comment]
I'm able to reproduce the bug on my system. 
Cura's next release is due soon, so I'll revisit this when that happens.

**Comment by karl-nilsson** [comment]
The same issue is present in Cura 4.12. I'm debugging it now.

**Comment by karl-nilsson** [comment]
I've patched the bug, and opened an issue upstream.
https://github.com/Ultimaker/Cura/issues/10785

**Comment by zlice** [comment]
You da bomb.

Can close this if you want (or leave it for tracking).

**Comment by karl-nilsson** [comment]
The 4.12 PR was just merged. I'll keep the issue open until you confirm it works for you.

**Comment by zlice** [comment]
Perfect. Thanks again.
