### ISSUE TITLE
MultiMC SHA256 mismatch, couldn't verify distfiles

### ISSUE THREAD

**Issue by Protrikk** [void-linux/void-packages#33861]
### System
Void 5.14.14_1 x86_64 AuthenticAMD notuptodate rrFFFF
MultiMC-0.6.12_3

### Expected behavior
Package compiles correctly

### Actual behavior
...
=> MultiMC-0.6.12_3: verifying checksum for distfile '0.6.12.tar.gz'... 
=> ERROR: SHA256 mismatch for '0.6.12.tar.gz:'
9be496910e53a7e07454b6c4433cf6d540a3c3fea01762ac3390f19a001cb4c9
=> MultiMC-0.6.12_3: verifying checksum for distfile 'multimc-0.6.1.tar.gz'... OK.
=> MultiMC-0.6.12_3: verifying checksum for distfile 'multimc-3.tar.gz'... OK.
=> ERROR: MultiMC-0.6.12_3: couldn't verify distfiles, exiting...

### Steps to reproduce the behavior
Trying to build multimc with xbps-src ( ./xbps-src pkg MultiMC )
###
Sorry if im doing something wrong and it's actually on an issue on my side, I did a reinstall few days ago and it fails now.

**Comment by HadetTheUndying** [comment]
Looks like one of the checksums is invalid. specifically looks to the the first checksum. I can make a PR for it tonight. but you should just be able to delete the first checksum in the template and replace it with the correct hash.

**Comment by HadetTheUndying** [comment]
This issue can be closed. My PR to fix this issue has been merged.

**Comment by Protrikk** [comment]
> Looks like one of the checksums is invalid. specifically looks to the the first checksum. I can make a PR for it tonight. but you should just be able to delete the first checksum in the template and replace it with the correct hash.

Sorry I didnt notice the response earlier, thanks for the help :heart:
