### ISSUE TITLE
Package Request: helix

### ISSUE THREAD

**Issue by jgarte** [void-linux/void-packages#33881]
https://helix-editor.com/

**Comment by cinerea0** [comment]
If this were to be packaged, it would have to wait until after we update the version of Rust in the repos to the latest available. Right now helix requires the 2021 edition of Rust, which came out just recently in October.

**Comment by cinerea0** [comment]
I did end up creating a template for helix, but be warned, it's a doozy: https://gist.github.com/cinerea0/e338ffb15791586574066a99455ff1c6. All of the independent distfiles mean that this template will never get accepted as it is, but if https://github.com/helix-editor/helix/pull/1536 gets merged the repetition can be removed and the template might be accepted.

**Comment by klardotsh** [comment]
Couldn't an argument be made that the independent distfiles are just a cost of doing business? IMO the value of packaging the tool is probably worth the template being a bit verbose until/if that linked PR merges.

**Comment by auronandace** [comment]
Looks like the next release is going to do away with the git submodules thanks to this:

https://github.com/helix-editor/helix/pull/1659

**Comment by classabbyamp** [comment]
done in #36429
