### ISSUE TITLE
[RFC] Using pkgconf instead of pkg-config

### ISSUE THREAD

**Issue by Cogitri** [void-linux/void-packages#3391]
I propose to use pkgconf instead of pkg-config for building. pkgconf has some advantages to pkg-config:

* It's still actively maintained (on https://git.dereferenced.org/pkgconf/pkgconf)
* It generally is faster than pkg-config...
* ...while providing a more accurate dependency graph (which prevents excessive overlinking)

Other distros such as Arch, Fedora, Mageia and most of the BSDs already use pkg-conf. Also see the Arch ML for their thread about this topic: https://lists.archlinux.org/pipermail/arch-dev-public/2018-May/029252.html

**Comment by maxice8** [comment]
+1 for me i can start working on it

**Comment by maxice8** [comment]
@void-linux/pkg-committers

**Comment by Cogitri** [comment]
Sorry, what's the status on this?

**Comment by maxice8** [comment]
@Gottox when (and how) will we change to pkgconf ?

**Comment by maxice8** [comment]
I Have started automatically replacing pkg-config with pkgconf on hostmakedepends= on my script https://github.com/maxice8/meltryllis/commit/c402020b9662042ac26c66fba2845575dbcdb320

**Comment by maxice8** [comment]
I'd like to revert this:

pkgconf is not bug compatiable with pkg-config, it prefixes all values returned by `pkg-config --variable` with PC_SYSROOT_DIR prefixed, pkg-config itself requires the ${pc_sysrootdir} variable to be in the .pc file itself this massively breaks most packages cross compilation. That behavior is not in line with the spec.

Doesn't help that pkgconf upstream moved to self-hosting and closed their issue section so i can't search if someone raised that issue up or not and what their response is.

pkg-config is good enough and doesn't break cross packages and follows the spec.

**Comment by the-maldridge** [comment]
sgtm

**Comment by maxice8** [comment]
On Sun, Feb 24, 2019 at 06:14:39PM -0800, Michael Aldridge wrote:
> sgtm
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/3391#issuecomment-466848171

Taking this comment as opportunity to answer by mail (comfier).

I'm not against it but some problems need to be solved:

- the wrappers need to be rewritten to deal with it while not breaking pkg-config.
- gobject-introspection needs changes to cope with it. We rely on behavior from the spec to do some magic funky stuff to get cross gir working.
- Vala problably as well.

**Comment by Johnnynator** [comment]
Packages that are broken (when Cross compiling, misses every pacakge that depends on libX11):

Not compiling:
- [ ] libX11 https://gist.github.com/Johnnynator/b964d709f77ea187c9a06958abc2571d

Wrong install paths
- [ ] fuse3
- [ ] lastpass-cli
- [ ] ndctl
- [ ] pcsc-acsccid
- [ ] pcsc-ccid
- [ ] udftools

**Comment by ericonr** [comment]
Is it still intended to get this working?

**Comment by Cogitri** [comment]
As noted in https://github.com/void-linux/void-packages/issues/3391#issuecomment-466848064 this has been reverted.

**Comment by ericonr** [comment]
@Cogitri do you think the issue can be closed, then? Or is it still a possibility?

**Comment by Logarithmus** [comment]
@ericonr what about reconsidering `pkgconf`? Are there only 7 packages broken? If yes then maybe it's better to try fixing them instead of keeping to use technically inferior `pkg-config`?

**Comment by ericonr** [comment]
I sure don't want to deal with the churn and take care of fixing any bugs that may appear. And don't revive old issues.

**Comment by Logarithmus** [comment]
@ericonr OK, seems like there are many packages which will be broken by `pkgconf`:
>this massively breaks most packages cross compilation. That behavior is not in line with the spec.

It would be nice tho either to fix `pkgconf` to make it match the spec in this aspect or to alter `./xbps-src` to not to rely on this behaviour. But someone has to do this dirty job :( Certainly, not anytime soon.
