### ISSUE TITLE
virtualbox-ose: Kernel Driver fails to load

### ISSUE THREAD

**Issue by HadetTheUndying** [void-linux/void-packages#33920]
### System

* xuname:  Void 5.13.19_1 x86_64 AuthenticAMD notuptodate rrmFFFFFFFFFFFFFFFFF
  *output of ``xuname`` (part of xtools)*
* package:  virtualbox-ose-6.1.26_1
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
VirtualBox is able to boot a VM.
### Actual behavior
```
Kernel driver not installed (rc=-1908)

The VirtualBox Linux kernel driver is either not loaded or not set up correctly. Please try setting it up again by executing

'/sbin/vboxconfig'

as root.

If your system has EFI Secure Boot enabled you may also need to sign the kernel modules (vboxdrv, vboxnetflt, vboxnetadp, vboxpci) before you can load them. Please see your Linux system's documentation for more information.

where: suplibOsInit what: 3 VERR_VM_DRIVER_NOT_INSTALLED (-1908) - The support driver is not installed. On linux, open returned ENOENT.
```
### Steps to reproduce the behavior
Install `virtualbox-ose` and try to setup a VM.

**Comment by egorenar** [comment]
I'm seeing the same issue with Linux kernel `5.15.9_1`

**Comment by egorenar** [comment]
Re-nstallation of the drivers and reboot helped. sorry for the noise.

**Comment by Vistaus** [comment]
Not working on 5.16 either. I get the exact same error message.
