### ISSUE TITLE
noto-font-cjk conflicts with google-font-ttf

### ISSUE THREAD

**Issue by YourDoge** [void-linux/void-packages#3393]
### System

* xuname:  
  *Void 4.18.8_1 x86_64 GenuineIntel notuptodate rFFF*
* package:
  *noto-fonts-cjk-20170601_1*
  *google-fonts-ttf*

### Expected behavior
noto-fonts-cjk should be able to be installed on top of google-fonts-ttf

### Actual behavior
noto-fonts-cjk isnt aable to be installed on top of google-fonts-ttf

### Steps to reproduce the behavior
Install google-fonts-ttf then try installing noto-fonts-cjk

**Comment by cr6git** [comment]
I think you're right.

**Comment by cr6git** [comment]
@pbui
