### ISSUE TITLE
Package request: GNOME Flashback

### ISSUE THREAD

**Issue by shizonic** [void-linux/void-packages#3394]
Source: https://gitlab.gnome.org/GNOME/gnome-flashback
Could be adapted from: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/gnome-flashback

**Comment by Cogitri** [comment]
Will work on this soon-ish

**Comment by shizonic** [comment]
@Cogitri Thanks!

In the meanwhile I did some tests by myself. It's still totally WIP and at the moment a lot of cleanup is required but it's build successfully:
https://github.com/shizonic/void-packages/commit/df636b9f2534cbd501524104a447ffdc211f10a0

So I would like to work on it further but I am open for suggestions.

Furthermore gnome-flashback has metacity as dependency and this package needs to be build too.

Let me know what you think.
