### ISSUE TITLE
XBPS_FETCH_CMD leakage

### ISSUE THREAD

**Issue by maxice8** [void-linux/void-packages#3399]
### System

* xuname:  Void 4.18.10_1 x86_64 GenuineIntel notuptodate rrmFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
  *output of ``xuname`` (part of xtools)*
* package: xbps-src 
  *affected package(s) including the version*

### Expected behavior

All packages compile successfully

### Actual behavior

XBPS_FETCH_CMD leaks into another package build

### Steps to reproduce the behavior

1. rm -rf hostdir/sources/perl-Curses
2. add perl-Curses to hostmakedepends= of `asciiquarium`
3. xrevbump 'bump' perl-Curses
4. ./xbps-src build asciiquarium

xbps-src sees perl-Curses needs to be rebuilt and goes fetch the source code but since it already sourced `asciiquarium` template it uses the XBPS_FETCH_CMD from it which uses wget.

```
=> asciiquarium-1.1_3: building ...
   [host] wget-1.19.5_1: found (https://alpha.de.repo.voidlinux.org/current)
   [host] perl-Curses-1.36_2: not found.
   [runtime] perl>=0: found perl-5.28.0_2 (https://alpha.de.repo.voidlinux.org/current)
   [runtime] perl-Term-Animation>=0: found perl-Term-Animation-2.6_2 (https://alpha.de.repo.voidlinux.org/current)
   [runtime] perl-Curses>=0: found perl-Curses-1.36_1 (https://alpha.de.repo.voidlinux.org/current)
=> perl-Curses-1.36_2: building [perl-module] (dependency of asciiquarium) ...
   [host] perl-5.28.0_2: found (https://alpha.de.repo.voidlinux.org/current)
   [target] perl-5.28.0_2: found (https://alpha.de.repo.voidlinux.org/current)
   [target] ncurses-devel-6.1_2: found (https://alpha.de.repo.voidlinux.org/current)
=> perl-Curses: building [perl-module] (dependency of asciiquarium) ...
=> perl-Curses-1.36_2: installing host dependency 'perl-5.28.0_2' ...
=> perl-Curses-1.36_2: installing target dependency 'perl-5.28.0_2' ...
=> perl-Curses-1.36_2: installing target dependency 'ncurses-devel-6.1_2' ...
=> perl-Curses-1.36_2: running do-fetch hook: 00-distfiles ...
=> perl-Curses-1.36_2: fetching distfile 'Curses-1.36.tar.gz'...
flock: failed to execute wget: No such file or directory
=> ERROR: perl-Curses-1.36_2: failed to fetch Curses-1.36.tar.gz.
```

**Comment by CameronNemo** [comment]
Affected packages:

- [ ] asciiquarium
- [ ] ipe
- [ ] catalyst
- [ ] gpm
- [ ] kaitai-struct-compiler
- [ ] soulseekqt
