### ISSUE TITLE
Tigervnc 1.12

### ISSUE THREAD

**Issue by bern-coder** [void-linux/void-packages#34001]
https://github.com/TigerVNC/tigervnc/releases/tag/v1.12.0

https://github.com/TigerVNC/tigervnc/archive/v1.12.0.tar.gz

**Comment by dotnetfox** [comment]
For those who are planning to update the package to this version, be aware of the following:
- pam-devel has to be added to makedepends.
- CMake throws deprecation warnings at you.
- CMake cannot find pam-devel while other packages with the same building style, in fact, are able to find and build with it (maybe implementation of checks is different?). The check is implemented this way:
```
# Check for PAM library
if(UNIX AND NOT APPLE)
  check_include_files(security/pam_appl.h HAVE_PAM_H)
  set(CMAKE_REQUIRED_LIBRARIES -lpam)
  check_function_exists(pam_start HAVE_PAM_START)
  set(CMAKE_REQUIRED_LIBRARIES)
  if(HAVE_PAM_H AND HAVE_PAM_START)
    set(PAM_LIBS pam)
  else()
    message(FATAL_ERROR "Could not find PAM development files")
  endif()
endif()
```

If someone is able to solve this "issue" with CMake (more like insanity) and finds this information helpful in some way, then you have my thanks.
