### ISSUE TITLE
File conflict between cmark and python3-commonmark

### ISSUE THREAD

**Issue by travankor** [void-linux/void-packages#34007]
### System

* xuname:
  Void 5.10.73_1 x86_64 GenuineIntel uptodate hold rrrmDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
* package:
  `cmark-0.30.2_1` and `python3-commonmark-0.9.1_2`

### Expected behavior
No file conflicts

### Actual behavior
File conflicts

```
xbps-query -Rf cmark
/usr/bin/cmark
...
xbps-query -Rf python3-commonmark
/usr/bin/cmark
...
```

### Steps to reproduce the behavior
```
xbps-query -Rf cmark
xbps-query -Rf python3-commonmark
```

**Comment by ericonr** [comment]
Thoughts on preference? Are the command line flags similar?

I can see a case for alternatives or just renaming the script from the python package.

**Comment by ericonr** [comment]
(assuming python3-commonmark is depended on by other packages, having it conflict would be far from ideal)

**Comment by bobertlo** [comment]
arch just renamed the python3-commonmark binary to `/usr/bin/py3-cmark` fwiw. I really think between the two noone is installing python3-commonmark to use that `cmark` cli.

If the commands were separate from the libraries I doubt this conflict would come up often, but with both packages providing libraries it's not a great situation.

**Comment by ericonr** [comment]
I think we usually spell out "python3-" in these executable names, but if other distros uses py3 it might help to go with the flow. I will check them out.

**Comment by bobertlo** [comment]
Yeah, that was just an example I was also thinking python3 might be more appropriate.

I noticed alpine and fedora both appear to have this conflict. I really don't think anyone will have an issue about the filename, but I could see someone installing both of these packages.
