### ISSUE TITLE
qemu-system-sparc64 broken on musl

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#34025]
### System

* xuname:  
  * smth, smth musl*
* package:  
  * `qemu-6.1.0_3`

### Expected behavior

qemu-system-sparc should not block the startup of virt-manager

---

Right now qemu-system-sparc does not exit with the libvirt testing parameters stuff, qemu-system-ppc also had this problem in the past.

One solution would be to split qemu package into smaller packages, since most users will most likely be interested only in a small subset of then, so annunrrlated breakage won't affect them.

**Comment by leahneukirchen** [comment]
See https://github.com/void-linux/void-packages/issues/33728#issuecomment-959840960 but someone needs to do it...
