### ISSUE TITLE
Python extension fails to start in vs code

### ISSUE THREAD

**Issue by RicArch97** [void-linux/void-packages#34033]
### System

* xuname:  Void 5.13.19_1 x86_64 AuthenticAMD uptodate rrrmFFFF
* package:  vscode-1.62.1_1

### Expected behavior
The Python extension should start and work as expected.

### Actual behavior
Extension fails with the following error: `[ms-python.python]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-python.python`

This also happened on version `1.62.0` I've also tried multiple versions of the extension, with the same result.

I've downloaded the binary (proprietary) version of vs code from the Microsoft website to try and reproduce it in there, but I was able to start the Python extension there without any problems, which is the reason for me to post this issue here.

### Steps to reproduce the behavior
Install the official Python extension by Microsoft from the extensions, open a Python file, and check the runtime status after restarting vs code.

**Comment by Johnnynator** [comment]
I added `ms-python.python` to the packages that can use the `proposed-api` so that error shouldn't show up anymore.
