### ISSUE TITLE
linux5.15: boot process _seems_ stuck at "loading initramfs ..."

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/void-packages#34035]
With 5.15, my boot process _seems_ stuck at "loading initramfs ...", although if I input the encryption password, then it proceeds as usual.
By reading https://bbs.archlinux.org/viewtopic.php?pid=2001959 , I wonder whether this is caused by `SYSFB_SIMPLEFB`.

_Originally posted by @dkwo in https://github.com/void-linux/void-packages/issues/33857#issuecomment-966302757_

**Comment by leahneukirchen** [comment]
Note that we have the modules mentioned in https://bugs.archlinux.org/task/72645 already...

**Comment by dkwo** [comment]
Indeed.
If it matters, I'm using `booster` initramfs generator (it's currently a pr in void), but from the forum post, it seems at least also mkinitcpio also has it, not sure about dracut.
I wonder if this new config option triggers some previously hidden kernel bug or race condition..
Would it be possible to disable it just for 5.15.2, to see if this is the culprit, without me recompiling void's kernel :) ?

**Comment by leahneukirchen** [comment]
The thread suggests you need to add your fb drivers to the initrd. Please post which hardware you use.

**Comment by leahneukirchen** [comment]
@dkwo try https://vuxu.org/~leah/tmp/linux5.15-5.15.1_1.x86_64.xbps which is built with CONFIG_SYSFB_SIMPLEFB=n, else same config.

**Comment by chili-b** [comment]
I might be experiencing the same problem (booting 5.15.1 hangs at "loading initial ramdisk"). I'm running on an intel cpu with the proprietary microcode from the `intel-ucode` package and an nvidia gpu with the proprietary drivers from the `nvidia` package. I do *not* have this problem on my thinkpad x200, which boots with no issues under linux 5.15.1 although it did seem to take a little longer than normal before advancing past "loading initial ramdisk" (this could just be my imagination)

**Comment by leahneukirchen** [comment]
Feel free to try the kernel package linked above to check if it's SIMPLEFB.

Alternatively, try adding `nvidia nvidia_modeset nvidia_uvm nvidia_drm` as modules to your initramfs.

**Comment by dkwo** [comment]
@leahneukirchen Could you build the `musl` version? sorry I forgot to mention
```
$ xuname
Void 5.15.1_1 x86_64-musl GenuineIntel uptodate rrnFFFFFF
```
My hardware is a thinkpad T460s, with intel cpu and integrated graphics.
Do you know what I should add to the initramfs?

**Comment by leahneukirchen** [comment]
I think you can install it on musl just as well, or just extract ./boot/vmlinuz-5.15.1_1

For intel you need `i915` afaiu.

**Comment by dkwo** [comment]
Thank you, adding the `i915` module to initram works.
```
$ xdowngrade linux5.15-5.15.1_1.x86_64.xbps
index: ignoring linux5.15-5.15.1_1, unmatched arch (x86_64)
index: 0 packages registered.
/bin/xdowngrade: failed to register all 1 packages.
```
So let me try extract it, just for the sake of science. :)

**Comment by dkwo** [comment]
If I just extract and move to boot the file `vmlinuz`, then the boot process goes past "loading initram...", but then it drops a shell later on, presumably due to being non-musl. Thus I think the config option SYSFB_SIMPLEFB is responsible for that, and adding a module to initram as you suggested fixes the issue.
Thanks.

**Comment by leahneukirchen** [comment]
The kernel certainly doesn't care which libc you use. ;)

But ok, we have a workaround now for intel, but not yet confirmed for Nvidia nor AMD.

I still think a plain old kernel should just display anything, so maybe reverting SYSFB_SIMPLEFB is the better way. Opinions?

**Comment by zdykstra** [comment]
Requiring video modules to be in the initramfs will for sure break some people using ZFSBootMenu. In particular, some cards don't soft-reinit after a new kernel has been launched via kexec. We are forced to blacklist `amdgpu`, `i915`, `nvidia` and `radeon` in the 'stage 1' kernel/initramfs, so that the video card can be cleanly initialized by the final kernel.

I'd like to see the same behavior as all previous kernels retained, as that does seem to be a safer default.

**Comment by newbluemoon** [comment]
My i686 box with nvidia390 and 5.15.2 is also stuck. Rebuilding the kernel with `CONFIG_SYSFB_SIMPLEFB=n` solved it and everything works as it should. No modules need to be added to the initramfs.

No problems with `CONFIG_SYSFB_SIMPLEFB=y` on i686-musl and nouveau as well as i686 and x86_64-musl with AMD.
