### ISSUE TITLE
dbeaver no desktop entry KDE Plasma

### ISSUE THREAD

**Issue by russnes** [void-linux/void-packages#34040]
### System
glibc with KDE Plasma

* xuname:  
  $ xuname
Void 5.13.19_1 x86_64 GenuineIntel notuptodate rrrmFFF
* package:  
  $ xbps-query -p pkgver dbeaver
dbeaver-21.2.4_1

### Expected behavior
dbeaver appears in the application launcher

### Actual behavior
it doesn't. Have to start it with command `dbeaver`

### Steps to reproduce the behavior
Open Application Launcher
search for "dbeaver"

**Comment by Johnnynator** [comment]
> This is an issue on your end. I just installed it on my machine and it starts from my application launcher (rofi). I'm running i3wm, but I doubt it has anything to do with the window manager.

This isn't an issue on his end. Dbeaver doesn't provide a .desktop file therefore no desktop entry in any Application launcher.

I take an educated guess and assume that your rofi is configured to just pick binaries in `$PATH` instead of `.desktop` files in `$XDG_DATA_DIRS`.

**Comment by paper42** [comment]
@ar-jan

**Comment by ar-jan** [comment]
It looks like the desktop entry should be generated by Maven. I'm not familiar with how this works, but it looks like the configuration comes from [here](https://github.com/dbeaver/dbeaver/blob/devel/product/community/DBeaver.product).

On my system I found an entry `~/.local/share/applications/_usr_lib_dbeaver_.desktop` containing:

```
[Desktop Entry]
Name=DBeaver
Exec=/usr/lib/dbeaver/dbeaver %u
NoDisplay=true
Type=Application
MimeType=x-scheme-handler/eclipse+command;
```

I don't know where the `NoDisplay=true` comes from.

Any suggestions how to handle this? I also see in DBeaver's issue queue they've had problems with packaging the desktop entry multiple times.

To patch this in the meantime, make the entry look like:

```
[Desktop Entry]
Name=DBeaver
Exec=/usr/lib/dbeaver/dbeaver %u
Icon=/usr/lib/dbeaver/icon.xpm
Type=Application
MimeType=x-scheme-handler/eclipse+command;
```
and run `sudo update-desktop-database ~/.local/share/applications/`.

**Comment by ar-jan** [comment]
Desktop entry is present now, this can be closed.
