### ISSUE TITLE
Gnome Completely Locks up When icons on Favorites Are Moved

### ISSUE THREAD

**Issue by Joeyalbo007** [void-linux/void-packages#3407]
### System

* xuname:  
  Void 4.18.11_1 x86_64 GenuineIntel uptodate rFFF
* package:  
Gnome

### Expected behavior
Move any app icon on favorites bar or in applications menu.
### Actual behavior
Gnome stops working if you move any app icon on favorites.
### Steps to reproduce the behavior
Try to change the order of the apps on the favorites bar or open an app in another workspace by dragging it.

**Comment by Cogitri** [comment]
Can reproduce, but only gnome-shell itself freezes. I guess this isn't the right place to report this though, please report this upstream at https://gitlab.gnome.org/GNOME/gnome-shell

**Comment by Gottox** [comment]
Can reproduce.

**Comment by Gottox** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/issues/632 - could it be this issue?

**Comment by ericonr** [comment]
@Gottox or @not-chicken can this one be closed?

**Comment by not-chicken** [comment]
I'd say yep. It's marked as fixed upstream and I can't reproduce it.
