### ISSUE TITLE
minio

### ISSUE THREAD

**Issue by IcedQuinn** [void-linux/void-packages#34089]
The package seems to be out of date but also subtly broken.

There is a post-install note on the console to edit a config json file. This config json file is no longer used by the version of minio (it replaces the file with a .deprecated and seemingly ignores it) which is presently packaged.

To complicate things further there has been a license+big GUI change in Minio. It has gone from Apache to AGPL which may be bothersome to some users.

Some action items to consider:
- Post-install script should not point user toward config files that appear to no longer be used
- Is a major license change needing ex. renaming the package to avoid accidental crossgrading
- What to do about minio preferring ex. access keys be passed in environment variables instead of the config.json

**Comment by dotnetfox** [comment]
@arete?

**Comment by arete** [comment]
Hi i try to update the package with the new license  and inform the License change in install message.
