### ISSUE TITLE
protobuf-c: binary disabled during cross-compiling

### ISSUE THREAD

**Issue by natrys** [void-linux/void-packages#34084]
I was building a nocross package (postgis) on aarch64, where the build somewhat confusingly failed because a dependency (protobuf-c) was missing its binary.

It appears that building the compiler binary was disabled for cross-compilation in the template, with reasoning being:

```
# buildprocess calls compiler while building, disable it on cross build
build_options="protoc"
desc_option_protoc="Build protoc-c compiler"
if [ -z "$CROSS_BUILD" ]; then
	build_options_default="protoc"
fi
```

But I wonder if this is not a problem any more. To test, I have cross-compiled it with `protoc` option enabled on x86_64 host, and it seemed to build and then work fine on aarch64 target. Upstream issue tracker had resolved number of cross-compilation related issues since this, and I think this is expected to be fine now. Perhaps someone else can verify.

**Comment by ericonr** [comment]
if it's working, should be fine to remove the build option and just always build it, imo.

@ahesford
