### ISSUE TITLE
Firefox ignores system DNS setting

### ISSUE THREAD

**Issue by DottoDev** [void-linux/void-packages#34097]
Firefox should use the system DNS, but Mozilla has an agreement with Cloudflare to force the usage of the Cloudflare DNS Servers.
Possible Change:
add **pref("network.trr.mode", 5);** to _files/vendor.js_

### System

* xuname:  
  Void 5.13.19_1 x86_64 GenuineIntel uptodate rrmFF
* package:  
  firefox-94.0_1 

### Expected behavior
Firefox should use the System DNS

### Actual behavior
Firefox ignores the system settings and uses Cloudflare DNS Server

### Steps to reproduce the behavior
Change the /etc/resolv.conf file to a non Cloudlfare nameserver and do a dns lookup in firefox using a site like www.dnsleaktest.com. It will still show a cloudflare dns server as the DNS Server.

**Comment by Duncaen** [comment]
Users can configure firefox on about:preferences how they like I don't think completely disabling DoH is a good idea, they are not forcing the usage of Cloudflare, they default to it and there is a choice in the settings between Cloudflare, NextDNS, bring your own DoH or not using DoH.

**Comment by DottoDev** [comment]
> Users can configure firefox on about:preferences how they like. I don't think completely disabling DoH is a good idea, they are not forcing the usage of Cloudflare, they default to it and there is a choice in the settings between Cloudflare, NextDNS, bring your own DoH or not using DoH.

It has no negative impact turned off because it still defaults to cloudflare but it has a negative impact on the user if he changes the system dns server without checking the dns firefox uses. Also the ignorance of system-level dns settings of firefox is not something many users know about. And isn't DoH still on, as long as the box "Enable DNS over HTTPS" in the settings is checked. This flag should just allow the user to disable DoH by just unchecking the box "Enable DNS over HTTPS"

**Comment by Duncaen** [comment]
This flag disables DoH afaiu and "Enable DNS over HTTPS" can already be unchecked no?

**Comment by DottoDev** [comment]
It can be unchecked but it has no effect

**Comment by Duncaen** [comment]
Do you have anything supporting that claim?

**Comment by DottoDev** [comment]
With correct /etc/resolv.conf firefox uses this DNS Servers
Both times with the box "Enable DNS over HTTPS" unchecked
With trr.mode = 2
https://pasteboard.co/cEvSOOMyahLq.png

With trr.mode = 5
https://pasteboard.co/WPvMivdYkg9n.png

The Problem is with the default, 2, Firefox ignores the settings of /etc/resolv.conf which should be used

**Comment by Duncaen** [comment]
I don't see where "2" would be the default. The source defines options "2" and "3" as user defined and the default is "0":
https://searchfox.org/mozilla-central/search?q=network.trr.mode&path=
