### ISSUE TITLE
Package Request: Please, a sudo alternative with regex support

### ISSUE THREAD

**Issue by pfr-dev** [void-linux/void-packages#34101]
Project URL: https://github.com/edneville/please

README.md copypasta:

> The aim is to allow admins to delegate accurate least privilege access with ease. There are times when what is intended to be executed can be expressed easily with a regex to expose only what is needed and nothing more.
>
>The idea is to help you admin your box without giving users full root shells, just because that is easier. Most admins have experience of regex in one form or another, so lets configure access that way.
>
>I saw regex but don't like regex. No problem, you can still use please without regex using `exact_` counterparts, or treat each field/property as plain text, and escape control characters `?(){}[]+` etc. Most of the regex match statements have `exact` counterparts.
>
>Please is written with memory safe rust. Traditional C memory unsafety is avoided, logic problems may still exist. Logic problems would exist in both systems, but I choose the smaller problem set.

**Comment by paper42** [comment]
#31430

**Comment by pfr-dev** [comment]
No worries, I'll see if I can bootsratp it manually. 
Cheers
