### ISSUE TITLE
HandBrake

### ISSUE THREAD

**Issue by artenaki** [void-linux/void-packages#34100]
HandBrake video encoder was released in version 1.4.2. Please update.
https://github.com/HandBrake/HandBrake/releases

**Comment by Duncaen** [comment]
We have a system to notify about outdated packages, opening issues doesn't help unless the system in place does not detect it.

https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt

**Comment by artenaki** [comment]
You built HandBrake 1.4. Thank you. However, colorimetry filter requires ffmpeg with --enable-libzimg option.
ffmpeg 4.4 from Void Linux doesn't have this option.
http://underpop.online.fr/f/ffmpeg/help/zscale.htm.gz
https://voidlinux.org/packages/?arch=x86_64&q=zimg
In general, HandBrake works, except for this filter. But that was one of the reasons I wanted to try out new version of HandBrake.
