### ISSUE TITLE
dunst broke (removed) command line color arguments

### ISSUE THREAD

**Issue by zlice** [void-linux/void-packages#34112]
### System

* xuname:  `Void 5.15.1 x86_64 AuthenticAMD notuptodate hold rrrmFFFFFFFFFF`

* package:  `dunst-1.7.1_1`

### Expected behavior

`dunst .... -frame_color #123456` changes colors when a notification hits

### Actual behavior

default colors

### Comments

This was upgraded 3 days ago but breaks current functionality. Not sure if there were any reasons for the upgrade but it breaks one-line setups. Functionality may be added back (with 2 dashes instead of 1) but it hasn't happened in 27 days.

Not sure if reverting back to 1.6.1 is an option.

void pr https://github.com/void-linux/void-packages/pull/34074

dunst issue https://github.com/dunst-project/dunst/issues/940

**Comment by ericonr** [comment]
Reverting should be easy, assuming there weren't new features added that people rely on...

**Comment by ct0br0** [comment]
I built 1.6.1 and put the pkg on hold.

See some wayland stuff - https://github.com/dunst-project/dunst/blob/master/CHANGELOG.md

**Comment by zlice** [comment]
I built 1.6.1 and put the pkg on hold.

See some wayland stuff - https://github.com/dunst-project/dunst/blob/master/CHANGELOG.md

**Comment by ericonr** [comment]
Issue with reverting is that it would mean the package would be kept at an older version forever, I find it hard for upstream to go back in this decision.

**Comment by biopsin** [comment]
Can't this be defined in dunstrc as

```
[test]
	appname = "info"
	background = "#9dbc8e"
	foreground = "#ffffff"
```

and then called with dunstify -a info "Blabla" "Blabla" -r 1800

**Comment by tibequadorian** [comment]
Upstream closed their issue and this is not a downstream issue.

**Comment by zlice** [comment]
they did...sad it's basically left open

**Comment by tibequadorian** [comment]
Maybe you could pass the config per command-line like this?
```
dunst -conf - <<EOF
... (config options here) ...
EOF
```

**Comment by zlice** [comment]
doesn't work

```
dunst -mouse_left_click do_action -mouse_middle_click close_all -mouse_right_click close_current -notification_height 40 -history_len 5 -confg - <<EOF
  [global]
    icon_position = off
  [frame]
    color = "#ff0000"
EOF
```

**Comment by zlice** [comment]
and now the repo must be updating bc i cant rebuild the old version -.-

**Comment by tibequadorian** [comment]
I mean that you write all the command line arguments in config file format like
```
dunst -conf - <<EOF
  [global]
    icon_position = off
    mouse_left_click = do_action
    mouse_middle_click = close_all
    mouse_right_click = close_current
    height = 40
    history_length = 5
    frame_color = "#ff0000"
EOF
```

**Comment by zlice** [comment]
that doesn't look like the example cfg i found, mustve been an old version. thanks ill give it a go!

**Comment by tibequadorian** [comment]
Yes, I changed it according to the dunst manual and it works for me with the current version 1.8.1

**Comment by zlice** [comment]
Yep mine is in the same file i had it before. lil ghetto but it works
