### ISSUE TITLE
efivarfs vs sysfs-efivars

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#34117]
I was trying to understand better how efi variables works.
I realised our kernel has both the old and new version, which leads to displaying two sets of efi variables:
```
$ ls /sys/firmware/efi/vars/
Display all 141 possibilities? (y or n)
$ ls /sys/firmware/efi/efivars/
Display all 139 possibilities? (y or n)
```
This is due to having both options:
```
CONFIG_EFI_VARS=y
CONFIG_EFIVAR_FS=y
```
According to Arch wiki, the first one should be avoided.
> UEFI Runtime Variables Support (old efivars sysfs interface - /sys/firmware/efi/vars). This option should be disabled to prevent any potential issues with both efivarfs and sysfs-efivars enabled.

Can anyone clarify what the correct thing to do is here, and whether we should set `CONFIG_EFI_VARS=n`?
Thanks.

**Comment by dkwo** [comment]
Also according to https://lkml.org/lkml/2013/4/16/473 , the older option is deprecated.

**Comment by dkwo** [comment]
@leahneukirchen Do you think we could set `CONFIG_EFI_VARS=m` or unset it, in the next 5.15 kernel update?

**Comment by leahneukirchen** [comment]
Will queue, yes.
