### ISSUE TITLE
aminal: upstream doesn't exist

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#34139]
### System

* package:  
  *affected package(s) including the version*: ``aminal-0.8.7_1``

### Expected behavior

the aminal package builds fine

### Actual behavior

I get an error while trying to download the distfiles, the homepage and source for distfiles - https://github.com/liamg/aminal redirects to https://github.com/liamg/darktile which has a different versioning scheme.

### Steps to reproduce the behavior
```
./xbps-src pkg aminal
```

@SolitudeSF

**Comment by cinerea0** [comment]
@paper42 This has been fixed; it just wasn't closed automatically because whoever merged my PR did it in a way GitHub didn't like.
