### ISSUE TITLE
Lutris missing dependency I think

### ISSUE THREAD

**Issue by lavitt** [void-linux/void-packages#34158]
### System

* xuname:  Void 5.13.19_1 x86_64 GenuineIntel notuptodate rrrrmmnFFFFFFF
  *output of ``xuname`` (part of xtools)*
* package:  lutris-0.5.9.1_1
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
launching
### Actual behavior
not launching
### Steps to reproduce the behavior
try to launch

I believe it depends on python3-pillow-simd-7.1.2_3, but this isn't listed as a dependency (xbps-query -v -R -x lutris). It wouldn't run until I installed that at least.

**Comment by Anachron** [comment]
Can you strace it?

**Comment by ericonr** [comment]
@lavitt feel free to open a PR fixing this :)

**Comment by colourfuloctopus** [comment]
It does not run for me either. Running Lutris -d produces 
`/usr/lib/python3.10/site-packages/PIL/Image.py:114: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 8.4.0
Pillow version: 7.1.2
  warnings.warn(str(v), RuntimeWarning)
/usr/lib/python3.10/site-packages/PIL/Image.py:114: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 8.4.0
Pillow version: 7.1.2
  warnings.warn(str(v), RuntimeWarning)
Traceback (most recent call last):
  File "/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 43, in <module>
    from lutris.gui.installerwindow import InstallerWindow
  File "/usr/lib/python3.10/site-packages/lutris/gui/installerwindow.py", line 16, in <module>
    from lutris.installer import interpreter
  File "/usr/lib/python3.10/site-packages/lutris/installer/interpreter.py", line 14, in <module>
    from lutris.installer.installer import LutrisInstaller
  File "/usr/lib/python3.10/site-packages/lutris/installer/installer.py", line 13, in <module>
    from lutris.services import SERVICES
  File "/usr/lib/python3.10/site-packages/lutris/services/__init__.py", line 7, in <module>
    from lutris.services.dolphin import DolphinService
  File "/usr/lib/python3.10/site-packages/lutris/services/dolphin.py", line 5, in <module>
    from PIL import Image
  File "/usr/lib/python3.10/site-packages/PIL/Image.py", line 96, in <module>
    raise ImportError(
ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: 8.4.0
Pillow version: 7.1.2`

**Comment by mvf** [comment]
Works for me (`lutris-0.5.9.1_1` on `x86_64` like the OP). I don't have `python3-pillow-simd` installed, only `python3-Pillow-8.4.0_1`, and `lutris` depends on it.

**Comment by paper42** [comment]
```
ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: 8.4.0
Pillow version: 7.1.2
```
python3-Pillow which lutris has in dependencies is on version 8.4.0, python3-pillow-simd is on version 7.1.2, but it is supposed to replace python3-Pillow, so both packages shouldn't be able to exist next to each other. Make sure you don't have python3-pillow-simd installed through xbps or pip.

**Comment by HadetTheUndying** [comment]
It sounds to me like you may have run `pip` as sudo at some point you might be able to track down some issues running `xbps-pkgdb -a`

**Comment by paper42** [comment]
@colourfuloctopus's issue is a user error and @lavitt's issue is not reproducible by anyone else, could you provide more information about your system? Please try replacing python3-pillow-simd with python3-Pillow. Are you using pip? Is the output of `xbps-pkgdb -a` clean?

**Comment by paper42** [comment]
This issue is not reproducible, so it's most likely a user error and the original author doesn't respond. Feel free to reopen this if it keeps happening.
