### ISSUE TITLE
python3-matplotlib-3.5.0_1: ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by st3r4g** [void-linux/void-packages#34171]
### System

* xuname:  
Void 5.13.19_1 x86_64 AuthenticAMD notuptodate hold rrdDFFFFFFFFFF
* package:  
python3-matplotlib-3.5.0_1

### Actual behavior
```
Traceback (most recent call last):
  File "/home/stefano/.pythonstartup", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3.10/site-packages/matplotlib/__init__.py", line 105, in <module>
    from packaging.version import parse as parse_version
ModuleNotFoundError: No module named 'packaging'
```
### Steps to reproduce the behavior
`import matplotlib.pyplot as plt`

**Comment by st3r4g** [comment]
New matplotlib needs `python3-packaging` in `depends`? @ahesford

**Comment by ahesford** [comment]
Thanks for bringing this to my attention. Dependencies have been reconciled in 215dc273c8b5cba59cc743dd3d550de7368f59df.
