### ISSUE TITLE
Package newer python-language-server and remove the old one

### ISSUE THREAD

**Issue by jgarte** [void-linux/void-packages#34192]
This is the new fork that is being maintained: https://github.com/python-lsp/python-lsp-server

See: https://github.com/palantir/python-language-server/issues/935 and #34180.

**Comment by foopub** [comment]
If you're up for it you should have a go at making the template for the python-lsp-server package and just make a pull request. I've been using python-lsp-server installed with pip so haven't really had the motivation, but I don't mind having a go at it tomorrow. 

@k4leg seeing as you're the maintainer of `python3-language-server`, what do you think?

**Comment by jgarte** [comment]
I might not be able to work on it for a week or so. It depends on when I find the free time. Feel free to try it.

**Comment by camoz** [comment]
BTW it would be cool if the new packge could be named exactly like the project `python-lsp-server`, and not `python3-lsp-server` or something... that makes it easier to find.

**Comment by paper42** [comment]
> BTW it would be cool if the new packge could be named exactly like the project `python-lsp-server`, and not `python3-lsp-server` or something... that makes it easier to find.

On void, all python3 packages are prefixed with python3-, prefix python- would mean it's a Python 2 package.

**Comment by camoz** [comment]
Oh ok. Is there any chance this will be changed in the future? Python 2 is EOL for over two years now... No pressure, just curious. :)

**Comment by Duncaen** [comment]
> Oh ok. Is there any chance this will be changed in the future? Python 2 is EOL for over two years now... No pressure, just curious. :)

No renaming packages is a pain and doing this again if there is a python4 or something like that would be annoying.

**Comment by camoz** [comment]
AIUI Python 4 is unlikely to happen at all, but I understand that people are spoiled from the 2->3 transition... It just seems unfortunate to me that if you search for the official project names like `python-lsp-server` or the current `python-language-server`, you get no results.

Also, why is renaming packages a pain? Isn't there a `replaces=` field in templates?

**Comment by Duncaen** [comment]
> Also, why is renaming packages a pain? Isn't there a `replaces=` field in templates?

This just makes xbps replace the other package if the replacing package is being installed, i.e. through a dependency.
If you've manually installed `python3-foo` and nothing depends on it that would pull in the new package name with the `replaces` directive, it will never be installed or replace any package.

This can not be changed as this is also used by some packages that act as an alternative for another package, i.e. nvidia used to replace the mesa libgl implementations, so by installing nvidia you can replace the open source implementation, without having to force break and uninstall the opensource implementation first.

The only alternative to this is to use "transaction dummy packages", i.e. a meta package with the old name and a higher version that depends on the new package name which then in turn replaces the old name.
But this is kinda buggy in the current xbps release and drops the manual/automatic install mode sometimes.

But that is also not a nice solution and would require us to ship 937 dummy packages for who knows how long until everyone updated their system.

Its simply not worth it with the current solutions to rename all those packages.

**Comment by camoz** [comment]
Understood, thank you for the nice explanation, appreciated!
