### ISSUE TITLE
[Question] Hosting my own private mirror with only the packages I need

### ISSUE THREAD

**Issue by WilliamBehrens** [void-linux/void-packages#34205]
I'm wanting to create my own custom mirror for void packages as I want to add a custom base-system and kernel but I don't think it would really be something to commit into the main void-packages repo. Something that I can't seem to find a direct answer too strangely is if it's possible to have multiple packages mirrors at once. So if I have my own custom repo hosted on my network and still be able to install packages from the main void repo. Another thing that isn't really documented if multiple repos is a thing is if each mirror has to host ALL of the packages in the main void repo or even if they just require the dependancies of the custom packages(like if I have a custom version of glew do I need to host my own version of glu or can glu be pulled from the main mirror to compile glew). I was hoping to be able to remove all the packages I'm not using to reduce the storage requirement of the mirror basically.

**Comment by HadetTheUndying** [comment]
You could just clone the repo and build the packages locally? 

There's also documentation about what you're asking here:

https://docs.voidlinux.org/xbps/repositories/custom.html

**Comment by WilliamBehrens** [comment]
Well the thing is I don't want to have to build everything from source

**Comment by HadetTheUndying** [comment]
> Well the thing is I don't want to have to build everything from source

I'm not really sure what you want then? If you're hosting custom packages/patch sets or restricted packages on your own server for example they're still going to need to be built and signed. 

Like for example hosting on a VPS you would still have to build the packages for the custom repo.

**Comment by WilliamBehrens** [comment]
I mean I want to be able to pull down a pre-compiled version of a package from the main void mirrors to compile the custom packages on my mirror

**Comment by Duncaen** [comment]
Just host a caching http proxy, here is an nginx example: https://gist.github.com/Duncaen/645f119544a65ad0fd32e0e0400e22a3.
