### ISSUE TITLE
Raspberry pi 4 Repo Connection Issue

### ISSUE THREAD

**Issue by Codythedragonrude** [void-linux/void-packages#34211]
I decided to give void linux for raspberry pi 4 a try but i could not figure it out 
Even void-installer was not working so i figured i would try to update it using xbps-install -Syyu as root 
When it looks for the repo it outputs a transient error that basically translates to unable to find the repository 

Am i doing stuff wrong? 
The lack of documentation on how to actually setup the rpi 4 makes it hard to know

**Comment by paper42** [comment]
Set the system time: https://docs.voidlinux.org/installation/guides/arm-devices/index.html#system-time

**Comment by Codythedragonrude** [comment]
> Set the system time: https://docs.voidlinux.org/installation/guides/arm-devices/index.html#system-time

still fails to fetch the repo file with a transient resolver failure

**Comment by Codythedragonrude** [comment]
here is a picture from my display of what i'm getting regardless of what i've done including setting the time right 
i'm just going to close this as it seems like an issue that is making me not even want to try to use void on a raspberry pi to be honest
![Screenshot_20211123_172808](https://user-images.githubusercontent.com/47878493/143139369-e9693fb0-6243-44f4-9a39-0ba6cf88e89c.png)

**Comment by paper42** [comment]
Does DNS name resolution work on your pi?
For faster response you might want to ask on IRC or Reddit, there are usually people who can quickly help you. Github issues are not the best.
By the way you might want to read about the syntax of xbps-install, it's not pacman, nothing related to your issue though.
