### ISSUE TITLE
libreoffice-calc-7.1.3.2_4: Cannot Launch LibreOffice Calc

### ISSUE THREAD

**Issue by fkoap** [void-linux/void-packages#34304]
### System

* xuname:  `Void 5.15.5_1 x86_64 AuthenticAMD uptodate rF`
* package:  *affected package(s) including the version*: `libreoffice-calc-7.1.3.2_4`

### Expected behavior
`sudo xbps-install -u libreoffice-calc` should install LibreOffice Calc and it should be launch-able.

### Actual behavior
`sudo xbps-install -u libreoffice-calc` provides the `libreoffice` command and fails to launch with error: ` terminate called after throwing an instance of 'com::sun::star::uno::RuntimeException' `. If installing the entirety of `libreoffice` (or maybe `libreoffice-base`) is required to run LibreOffice Calc, it should not be install-able separately, or dependencies must be pulled in. Also, JRE is required for LibreOffice. When I installed `libreoffice-calc`, JRE wasn't pulled in as a dependency. The error that I included was *after* installing `openjdk8-jre` separately.

### Steps to reproduce the behavior
* Run `sudo xbps-install -u libreoffice-calc`
* Try launching LibreOffice Calc

**Comment by parallelistic** [comment]
Can confirm libreoffice-calc is missing a jre dependency, but i also do not think it would be smart to include one (for obvious reasons)

[this](https://ask.libreoffice.org/t/is-it-possible-to-install-only-writer-and-calc/55664/3) is why you're unable to use libreoffice-calc by itself, whether or not libreoffice-calc should require libreoffice packages as dependencies is another question entirely, i personally do not know how xbps would handle circular dependencies.

**Comment by ericonr** [comment]
Do you have any installed language packs? They are needed to launch the applications, afaik.

Re. Java, I hadn't realized it was necessary now. We can consider adding a virtual dependency.

**Comment by parallelistic** [comment]
> Do you have any installed language packs? They are needed to launch the applications, afaik.
> 
> Re. Java, I hadn't realized it was necessary now. We can consider adding a virtual dependency.

Language pack isn't enough, I tried installing that too

**Comment by ericonr** [comment]
Can you confirm what package made it work? I know it works locally...

**Comment by parallelistic** [comment]
> Can you confirm what package made it work? I know it works locally...

I haven't been able to get it to work without the big package, I think the point is that libreoffice-calc and the like are meant to be modules / extensions, not standalone.

**Comment by Chocimier** [comment]
installing `-base` help here

**Comment by parallelistic** [comment]
> installing `-base` help here

are you sure? iirc I had base installed too...
I'll check tommorow.

**Comment by ericonr** [comment]
I have #34272 going, it would be nice to include any changes directly.

**Comment by fkoap** [comment]
I installed `libreoffice-base`; it still doesn't work. Here is a screenshot of the dependencies when I try to install `libreoffice`:

![libreoffice](https://user-images.githubusercontent.com/95037049/143973598-de8be736-30b2-4de0-9edd-399c06545a72.png)

My point is that installing `libreoffice-calc` separately should ideally not be possible *if* all the `libreoffice` packages are required for it to run, and they *aren't* pulled in as dependencies. This makes it very confusing.

**Comment by ericonr** [comment]
I get your point, we are trying to investigate what exactly is missing so we can fix the packages.

Can you confirm that installing `libreoffice` makes it work, then?

**Comment by sgn** [comment]
`-calc` needs `-writer`. `-writer` doesn't need `-calc`, I think

**Comment by fkoap** [comment]
@ericonr Yes, I confirm. Installing `libreoffice` makes it work.

**Comment by sgn** [comment]
@ericonr 
```diff
diff --git a/srcpkgs/libreoffice/template b/srcpkgs/libreoffice/template
index 6ea455c5c0..076389c007 100644
--- a/srcpkgs/libreoffice/template
+++ b/srcpkgs/libreoffice/template
@@ -540,7 +540,7 @@ libreoffice-common_package() {
 
 libreoffice-base_package() {
 	short_desc+=" - Database frontend"
-	depends="libreoffice-common>=${version}_${revision}"
+	depends="libreoffice-writer>=${version}_${revision}"
 	noverifyrdeps=yes
 	pkg_install() {
 		_split base
@@ -549,7 +549,7 @@ libreoffice-base_package() {
 
 libreoffice-calc_package() {
 	short_desc+=" - Spreadsheet"
-	depends="libreoffice-common>=${version}_${revision}"
+	depends="libreoffice-writer>=${version}_${revision}"
 	noverifyrdeps=yes
 	pkg_install() {
 		_split calc
@@ -558,7 +558,7 @@ libreoffice-calc_package() {
 
 libreoffice-draw_package() {
 	short_desc+=" - Drawing application"
-	depends="sane libreoffice-common>=${version}_${revision}"
+	depends="sane libreoffice-writer>=${version}_${revision}"
 	noverifyrdeps=yes
 	pkg_install() {
 		_split draw
@@ -585,7 +585,7 @@ libreoffice-gnome_package() {
 
 libreoffice-impress_package() {
 	short_desc+=" - Presentation application"
-	depends="libreoffice-common>=${version}_${revision}"
+	depends="libreoffice-writer>=${version}_${revision}"
 	noverifyrdeps=yes
 	pkg_install() {
 		_split impress
@@ -616,7 +616,7 @@ libreoffice-kit_package() {
 
 libreoffice-math_package() {
 	short_desc+=" - Equation editor"
-	depends="libreoffice-common>=${version}_${revision}"
+	depends="libreoffice-writer>=${version}_${revision}"
 	noverifyrdeps=yes
 	pkg_install() {
 		_split math
```
