### ISSUE TITLE
ldd is broken in default install (missing dependency on bash)

### ISSUE THREAD

**Issue by twpayne** [void-linux/void-packages#34319]
### System

* xuname:  
  `Void 5.4.0-86-generic x86_64 GenuineIntel uptodate rF`
* package:  
  *affected package(s) including the version*: Sorry, I could not find out which package provides `/usr/sbin/ldd`.

### Expected behavior

`ldd --version` prints a version number and copyright notice.

### Actual behavior

`ldd --version` fails with the error:

```
/bin/sh: 1: ldd: not found
```

### Steps to reproduce the behavior

With Docker:

```console
$ docker run -it voidlinux/voidlinux:latest /bin/sh
# ldd
/bin/sh: 1: ldd: not found
```

### Explanation

`/usr/sbin/ldd` is a bash script:
```console
$ head -n 1 /usr/sbin/ldd
#!/bin/bash
```
By default, `bash` is not installed, so `/usr/sbin/ldd` fails with the "not found" error shown above.

### Possible fixes

1. Install `/bin/bash` as part of the base system.
2. Modify `/usr/sbin/ldd` to use `/bin/sh` instead of `/bin/bash`, as `/bin/sh` is part of the base system.

Please let me know if you need any further information.

**Comment by ericonr** [comment]
`ldd` is provided by glibc, which can be verified with `xbps-query -o /usr/bin/ldd`. It's, unfortunately, a shell script that uses bashisms (because glibc upstream is very stubborn), but, due to circular dependencies, we can't make `glibc` depend on `bash` (and well, for most usages of `glibc`, you won't use `ldd` anyway).

I'm not sure this is fixable at all.

**Comment by ericonr** [comment]
Also, the dockerhub images are no longer used, I recommend moving to https://github.com/void-linux/void-docker/pkgs/container/void-linux

**Comment by ericonr** [comment]
>  affected package(s) including the version: Sorry, I could not find out which package provides /usr/sbin/ldd.

I see your mistake now: `/usr/bin` is the canonical directory, everything else is a symlink to it. So packages own file under that hierarchy, not `/usr/sbin`.

**Comment by twpayne** [comment]
Thank you for the explanations. Feel free to close this issue if it's not fixable.

**Comment by illiliti** [comment]
Bash-free ldd -> https://github.com/gkisslinux/sh-alternatives
