### ISSUE TITLE
Can we please keep firefox-esr-78 available for the forseeable future?

### ISSUE THREAD

**Issue by datenwolf** [void-linux/void-packages#34328]
I just noticed that `firefox-esr` got bumped to version 91.3.0 since my last full system upgrade. Now personally my experiences with the 9x versions of Firefox were a bugfest. All of the bugs I did encounter also manifested for other users and are accounted for and confirmed in the Firefox bugzilla bugtracker.

Unfortunately those are not minor things. There are UI bugs like attempting to type in the search bar randomly focusing a different UI element. Tabbar height miscalculated if website titles make use of Unicode codepoints that require to use fonts with a different base height. Typing long text into multiline edits cause segfault tab crashes. WebGL no longer works properly, etc., etc.

After months of enduring those bugs without them being resolved I downgraded back to firefox-esr-78. For the time being I've put that package on hold on my systems. But it'd be nice if we could have this specific version being available until the structural issues of Firefox development have been resolved.

**Comment by q66** [comment]
firefox 78 is EOL, and considering we don't keep various firefox forks in the repository either, I see no reason to make an exception in this case...

if you have issues with newer FF, that's something to be reported to mozilla, not here
