### ISSUE TITLE
Package Request: TrenchBroom

### ISSUE THREAD

**Issue by r-malon** [void-linux/void-packages#34338]
**TrenchBroom** is a modern cross-platform level editor for Quake-engine based games.

https://trenchbroom.github.io/
https://github.com/TrenchBroom/TrenchBroom/blob/master/Build.md

**Comment by kedodrill** [comment]
This is a duplicate of https://github.com/void-linux/void-packages/issues/31317.
Also I have a PR up https://github.com/void-linux/void-packages/pull/33354.
