### ISSUE TITLE
MultiMC is missing

### ISSUE THREAD

**Issue by RossComputerGuy** [void-linux/void-packages#34377]
### System

* xuname:  Void 5.13.19_1 x86_64 AuthenticAMD uptodate rrrrrmmdnFFFFFF

### Expected behavior

MultiMC should be able to install.

### Actual behavior

MultiMC is not found, yet debug package exists.

### Steps to reproduce the behavior
```
sudo xbps-install MultiMC
```
**or**
```
sudo xbps-install MultiMC-dbg
```

**Comment by dotnetfox** [comment]
I could not find MultiMC in the repository, nor its debug package.

According to the template file of MultiMC, it has the `restricted` variable set, meaning that this package cannot appear in the void repository by any means; you have to build it yourself using xbps-src.

If that is what you have tried to do, please describe the steps you have taken to build this package.

**Comment by q66** [comment]
https://github.com/void-linux/void-packages/issues/32950

**Comment by RossComputerGuy** [comment]
> I could not find MultiMC in the repository, nor its debug package.
> 
> According to the template file of MultiMC, it has the `restricted` variable set, meaning that this package cannot appear in the void repository by any means; you have to build it yourself using xbps-src.
> 
> If that is what you have tried to do, please describe the steps you have taken to build this package.

Ah, that explains why I can't find it. However, I have no idea why only the debug package is available.
