### ISSUE TITLE
appmenu-gtk-module: missing schema file

### ISSUE THREAD

**Issue by HiPhish** [void-linux/void-packages#34419]
### System

* xuname: `Void 5.15.6_1 x86_64 AuthenticAMD notuptodate rrmFFF`
* package:
  * `appmenu-gtk-module-0.7.6_1`
  * `appmenu-gtk3-module-0.7.6_1`

### Expected behavior
The GTK module should work.

### Actual behavior
The module does not work, starting an application prints the following to standard output:

```
$ gimp
(gimp:20057): GLib-GIO-ERROR **: 01:13:46.321: Settings schema 'org.appmenu.gtk-module' is not installed
```

Manually adding the schema file from the upstream repository to `/usr/share/glib-2.0/schemas/` and then executing `sudo glib-compile-schemas` fixes the issue.

I don't know much about XBPS, but from this I figure that the schema file should be copied over as part of the installation process and that the schema compilation needs to be carried out. If someone can point me in the right direction I could give a try fixing the build script.

**Comment by dtreffenstaedt** [comment]
The schema definition is part of the package `vala-panel-appmenu`.

It could be made a dependency of the relevant packages. There might be a better way to go about it though.

**Comment by HiPhish** [comment]
*bump* to prevent the issue from being closed automatically

**Comment by NinjaCowboy** [comment]
bump

Without `vala-panel-appmenu` installed, GTK2 apps will not start at all, so it needs to be a dependency.
