### ISSUE TITLE
Dragonly Mail Agent: wrong file ownership of config files

### ISSUE THREAD

**Issue by thenktor** [void-linux/void-packages#34431]
### System

* xuname:  
  Void 5.13.19_1 x86_64-musl GenuineIntel notuptodate rF
* package:  
  dma-0.13_3

### Expected behavior
One should be able to send mail as non root user.

### Actual behavior
Sending mail fails:
```
# mail -s "A mail sent using mailx" test@example.com
hello world
.
EOT
send-mail: can not open auth file `/etc/dma/auth.conf': Permission denied
```

### Problem and solution
Both conf files in /etc/dma are owned by `root:root`, but actually they should be owned by `root:mail`.

**Comment by loreb** [comment]
Just a quick note - you must uncomment the AUTHPATH line in /etc/dma/dma.conf or you won't be able to reproduce the bug.

**Comment by loreb** [comment]
bump

**Comment by loreb** [comment]
bump...
