### ISSUE TITLE
Package request: lua-language-server

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#34436]
https://github.com/sumneko/lua-language-server

**Comment by motorto** [comment]
I tried to create a package for this ... But currently the releases don't include the git submodules required ... 

Even arch (the only distro that I found with Lua-language-server packaged) seems to use the git version ...

Git packages are not accepted in void. 

 @paper42, what do you think ? Is there any way to circumvent this submodules issue ?
