### ISSUE TITLE
urxvt keeps asking to verify paste

### ISSUE THREAD

**Issue by zlice** [void-linux/void-packages#34442]
* xuname:
  `Void 5.15.1 x86_64 AuthenticAMD uptodate hold rrrmFFFFFFFFFFF`
* package:  
  `rxvt-unicode-9.30_1`

### Expected behavior

Was pasting without verify warning until a week or few ago

### Actual behavior

![paste_verify](https://user-images.githubusercontent.com/8009811/145402368-d1e5de68-9c21-4101-97d2-73c066d6d4cf.png)

Putting `URxvt.perl-ext-common: default` in .Xdefaults or .Xresources worked for maybe a day, now it does not, but I don't think urxvt updated.

### Steps to reproduce the behavior

 - highlight text somewhere
 - Open a terminal
 - Middle mouse click to paste in terminal

**Comment by loreb** [comment]
It's buried in the manpage, see if it works...
```
The default set includes the "selection", "option-popup", "selection-popup", "readline", "searchable-scrollback" and "confirm-paste" extensions
```

until very recently confirm-paste wasn't included, so you should replace "default" with "default,-confirm-paste" (notice the '-') to load the default extensions minus confirm-paste.

I tested it a couple of times and it worked for me (tm).

**Comment by zlice** [comment]
My bad, stamp my forehead with RTFM.

Thanks.

**Comment by xlotlu** [comment]
I don't think this should be closed. Yes, RTFM-ing is a solution, but this behaviour as a default is still unwarranted and unexpected.

After having gotten annoyed enough to STFW in order to fix it for myself, I think `confirm-paste` should be removed from `default`.

**Comment by paper42** [comment]
I don't think this is our issue, Void doesn't patch upstream defaults and from what I can tell, other distributions also don't change this behavior.

**Comment by zlice** [comment]
Agree with paper. It's just one of those stupid "security" features most people prolly don't want but you have to live with. At least it's here for someone to find the solution.

**Comment by MarcWeber** [comment]
My view:
- urxvt is not a default of user friendly distros anyway, is it?
- open source should be getting out of the way, not into the way. Cause not getting your job done has a cost, too.
- When it matters (eg irssi) they have their own checks
- I am aware of copying from the net could be dangerous (so is loosing time). So maybe it should be the responsibility of providing/receiving sides to step into the way.
Pasting 3 lines into a shell is a common pattern.

Have you ever seen a PC "Do you want to switch on the speakers could be loud?" ;-)

But maybe a link to this issues would be enough to have people find the solution fast and control their own ~/.X11defaults file.

But the most annoying thing is that if you copy paste 3 lines from an urxvt terminal you get one line instead then ! So the behavior might even change in an unexpected way. I have been using version 9.31.

**Comment by loreb** [comment]
@MarcWeber they fixed the one line thing, now it's "y/n/p" instead of "y/n" ('y' squeezes lines together while 'p' does what you want)
