### ISSUE TITLE
We should use constant uids and gids for system accounts.

### ISSUE THREAD

**Issue by CMB** [void-linux/void-packages#345]
The system_accounts variable in xbps templates does let you do this, but
nobody ever seems to use it.  Really, we should.  As things stand now,
uids and gids for system users are a bit random.  This is both fragile
and possibly insecure, especially in the event of package uninstalls
or reinstalls.

**Comment by Duncaen** [comment]
https://wiki.debian.org/AccountHandlingInMaintainerScripts#Account_deletion

My vote goes to not automatically deleting users and maybe changing the shell and some comment to indicated that they were removed.

**Comment by Vaelatern** [comment]
Agreed with Duncaen. If we would just not remove accounts, so the old system account just sticks around, that would be satisfactory to me.

**Comment by CMB** [comment]
Agreed, not removing accounts seems like the way to go.
