### ISSUE TITLE
`./xbps-src zap` permission error after compiling with golang

### ISSUE THREAD

**Issue by b-l-a-i-n-e** [void-linux/void-packages#34505]
After compiling a program with golang, a masterdir/tmp/go directory is created with files in it that can only only be removed as root.

``./xpbs-src zap`` then complains about permissions like below

```
rm: cannot remove '/home/b/void-packages/masterdir/tmp/go/pkg/mod/golang.org/x/net@v0.0.0-20190328230028-74de082e2cca/dns/dnsmessage/example_test.go': Permission denied
rm: cannot remove '/home/b/void-packages/masterdir/tmp/go/pkg/mod/golang.org/x/net@v0.0.0-20190328230028-74de082e2cca/dns/dnsmessage/message_test.go': Permission denied
rm: cannot remove '/home/b/void-packages/masterdir/tmp/go/pkg/mod/golang.org/x/net@v0.0.0-20190328230028-74de082e2cca/dns/dnsmessage/message.go': Permission denied
rm: cannot remove '/home/b/void-packages/masterdir/tmp/go/pkg/mod/golang.org/x/net@v0.0.0-20190328230028-74de082e2cca/PATENTS': Permission denied
```

**Comment by b-l-a-i-n-e** [comment]
`sudo rm -rf masterdir/tmp` fixes it, but to avoid sudo permissions we may need to do something like

`chmod -R 777 masterdir/tmp` in the zap command

**Comment by b-l-a-i-n-e** [comment]
Potential fix here:
https://github.com/void-linux/void-packages/pull/34506

**Comment by paper42** [comment]
That is a solution, but a much cleaner approach would be to add `-modcacherw` to the go build style to make the files writeable

**Comment by b-l-a-i-n-e** [comment]
@paper42 do you mean adding the GOFLAGS check in the actual build_style (common/build-style/go.sh) or adding the flag to the specific package that was causing the issue?

For my particular issue I was not using the go build-style because the package I want to install is not in the normal go package format, I need to run a script to start the go compilation
