### ISSUE TITLE
Package Request: rbenv

### ISSUE THREAD

**Issue by b-l-a-i-n-e** [void-linux/void-packages#34501]
Tool to compile and install versions of ruby
https://github.com/rbenv/rbenv
https://github.com/rbenv/ruby-build

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rbenv
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ruby-build

**Comment by b-l-a-i-n-e** [comment]
https://github.com/void-linux/void-packages/pull/34504
https://github.com/void-linux/void-packages/pull/34500

**Comment by Chocimier** [comment]
Please do not open package requests for packages sent in PR right away.
