### ISSUE TITLE
Scribus is bugged

### ISSUE THREAD

**Issue by notthewave** [void-linux/void-packages#34510]
### System

* xuname:  
  *Void 5.15.7_1 x86_64-musl GenuineIntel uptodate rrDFFFFFFFFFFFFFFFFFF*
* package:  
  *affected package(s) including the version*: ``scribus-1.5.7_6``

### Expected behavior
- dropdown menus stay within the screen area
- the font menu is displayed normally

### Actual behavior
- dropdown go past the screen edge
- when selecting a font, the menu has graphical glitches

### Steps to reproduce the behavior
- open one of the dropdown menus
- choose a font when editing text

This happens on X as well as in Wayland

Also why ship development releases?

**Comment by paper42** [comment]
The only dropdown menu which behaves a bit weird is the "Select the image preview quality". The dropdown menu appears horizontally in the middle of the screen instead of right next to the dropdown. Otherwise I can not reproduce this on XWayland and Wayland under GNOME.

> Also why ship development releases?

1.5.7 is a stable release, what do you mean by development releases?

**Comment by notthewave** [comment]
https://www.scribus.net/downloads/stable-branch/
https://www.scribus.net/downloads/unstable-branch/

I tested on sway and dwm

**Comment by notthewave** [comment]
so on dwm drop down menus work but the font menu still has graphical glitches

**Comment by notthewave** [comment]
ok so the glitch thing is related to the choosen theme. Some work others don't

**Comment by notthewave** [comment]
this seems to be an issue related to wlroots

**Comment by notthewave** [comment]
@paper42 sure scribus was running with wayland and not xwaland? Because weston has the same problem.

**Comment by notthewave** [comment]
strangely it does not happen anymore. Seems like an update fixed it...
