### ISSUE TITLE
Chicken: csc seems broken - missing chicken.h?

### ISSUE THREAD

**Issue by Melchizedek6809** [void-linux/void-packages#34570]
### System
* xuname:  
  *Void 5.15.7_1 x86_64-musl AuthenticAMD uptodate rF
* package:  
  *chicken-5.3.0_1

### Expected behavior
An executable image of the program

### Actual behavior
Trying to compile a hello world program with `csc` returns the following error:
```
test.c:8:10: fatal error: chicken.h: No such file or directory
    8 | #include "chicken.h"
      |          ^~~~~~~~~~~
compilation terminated.

Error: shell command terminated with non-zero exit status 256: 'gcc' 'test.c' -o 'test.o' -c  -fno-strict-aliasing -fwrapv -DHAVE_CHICKEN_CONFIG_H -DC_ENABLE_PTABLES -Os -fomit-frame-pointer -I/usr/include/chicken
```

### Steps to reproduce the behavior
The above error message was produced when trying to compile the following scheme program:
```
(display "Test\n")
(exit 0)
```
Running it via `csi test.scm` works just as expected, but when trying to compile it via `csc test.scm` I get the above error. I also tested the same program on another system running Debian and there it produced a working binary to make sure it's not something related to the source or my invocation of csc.

**Comment by paper42** [comment]
Installing `chicken-devel` should fix this issue.

**Comment by Melchizedek6809** [comment]
Thank you, now things seem fine! Do you know if there is a particular reason for `csc` to be shipped without the necessary headers? Seems confusing to me.

**Comment by ericonr** [comment]
Presumably because you can run your code with `chicken` without compiling it.

Maybe we should consider moving `csc` to the `chicken-devel` package, that way, if someone needs to compile something, they will install `chicken-devel` already.
