### ISSUE TITLE
Package request: i915g

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#34595]
Current versions of wlroots based compositors require Gallium driver for i915 supported cards. The classic i915 driver lacks features needed by wlroots.

AUR template: https://aur.archlinux.org/packages/mesa-i915g/

**Comment by tsndqst** [comment]
@notramo I have i915g working on my EeePC (32bit netbook) with this change: https://github.com/void-linux/void-packages/pull/34620
I haven't done much testing with it though.

**Comment by classabbyamp** [comment]
done a while ago
