### ISSUE TITLE
sbt has no source code

### ISSUE THREAD

**Issue by HiPhish** [void-linux/void-packages#34597]
Please correct me if I'm wrong, but it looks to me like the `sbt` package template simply downloads the pre-compiled sbt binary and copies it in place. Does this really belong into the Free Void packages? I mean "technically" we have the source code, we just cannot compile it without already having sbt, so eventually we have to download some binary release. That makes sbt non-free at least in spirit if not technically in my opinion.

**Comment by loreb** [comment]
You're right; and I tried installing it in a vm, running "sbt" even in an empty directory will download all sorts of dependencies from the internet...

A couple of possible solutions (in alphabetical order):
1. build.sh - run the tool, say in a vm, write down the steps required to compile and hack together a stupid shell script that does exactly that
2. debian - they package it successfully at https://packages.debian.org/sid/sbt
3. go - when the go package rewrote its compiler in go (used to be in C), void added the go1.12-bootstrap package, something like that could be done (and it looks to me that it's basically what they are doing in debian, plus patches to avoid the "download from the internet" step)
4. history - check the project's history, they must have started with maven or gradle or whatever, so one should be able to build some ancient version and use that... you get the idea.

My impression from toying with it for 5 minutes is that I'm glad that I'm not a scala programmer and I can leave the problem to somebody else.

PS
Good job noticing!

**Comment by q66** [comment]
this is intended, packaging it from source just to end up at the same compiled bytecode is too much effort of questionable purpose
