### ISSUE TITLE
Update: AntiMicro

### ISSUE THREAD

**Issue by johnny-mac** [void-linux/void-packages#3462]
Hello, the maintainer of antimicro might like to know that active development has moved to
https://github.com/juliagoda/antimicro
https://aur.archlinux.org/packages/antimicro/
I believe this contains a fix for QT5.11, either that or it is in the 'antimicro' PKGBUILD in the AUR.

**Comment by Hoshpak** [comment]
@7185

**Comment by 7185** [comment]
Thanks, I didn't notice that at all!

**Comment by johnny-mac** [comment]
Strange how it breaks Qt4 support in Void, I have it working in Qt4 on Arch.

**Comment by 7185** [comment]
Support for Qt4 is being removed, I just read the [release notes](https://github.com/juliagoda/antimicro/releases).
It's compiled against Qt5 in Void so it will work anyway, I'm just implying that it's a breaking change and not a minor update.

About the patch, all I did was copying it from AUR, it removes the `-Werror` flag but it probably would be better to just fix the warnings in the code.
As far as I'm concerned, this fork seems to be a little unpolished for now.
I'd prefer to wait for a [wider adoption across distributions](https://repology.org/metapackage/antimicro/versions) or at least a more polished version.

**Comment by johnny-mac** [comment]
Understood 7185, I'll let you know how things go.
