### ISSUE TITLE
Why does `elogind` not depend on `dbus-elogind` but `dbus`?

### ISSUE THREAD

**Issue by camoz** [void-linux/void-packages#34675]
Hi,

I noticed that the package `elogind` does not depend on `dbus-elogind` but `dbus`. Is there a specific reason for this? (I'm new to non-systemd distros so I'm just learning the relationships between those things etc...)

Thanks.

**Comment by camoz** [comment]
bump

**Comment by Duncaen** [comment]
It would introduce a loop, maybe it shouldn't depend on dbus?
