### ISSUE TITLE
Remove packages `dbus-x11` and `dbus-elogind-x11`?

### ISSUE THREAD

**Issue by camoz** [void-linux/void-packages#34678]
The program `dbus-launch` along with its man page is split from `dbus` and `dbus-elogind` into `dbus-x11` and `dbus-elogind-x11`, respectively.

`dbus-launch` does not seem to be X11-specific though, it is just a "Utility to start a message bus from a shell script" (from the manpage). It can also be used with wayland compositors for example.

So, is the split really necessary? What advantages does it have?

**Comment by atahanacar** [comment]
I think a split is necessary, but not like it is right now. I think the X11 specific packages should add a 80-dbus.sh to the xinitrc config. For example, Artix puts this file to /etc/X11/xinit/xinitrc.d/ directory: https://gitea.artixlinux.org/packagesD/dbus-runit/src/branch/master/x86_64/extra/80-dbus.sh

By doing this, you don't have to use dbus-launch explicitly in your .xinitrc.
