### ISSUE TITLE
Package Request: rsv

### ISSUE THREAD

**Issue by waynevanson** [void-linux/void-packages#34695]
> The runit sv command rewritten in rust with additional features
> - https://github.com/JojiiOfficial/rsv

Won't build until this is in (broken): https://github.com/JojiiOfficial/rsv/pull/10

Alternatively, apply the patches manually.

**Comment by paper42** [comment]
#27399

**Comment by ram02z** [comment]
Clap 3.0.0-rc8 is incompatible with the current rust version anyway.

**Comment by waynevanson** [comment]
Looks like it was closed in #27399
