### ISSUE TITLE
Missing dependency for Krita

### ISSUE THREAD

**Issue by jlneder** [void-linux/void-packages#34699]
Krita needs some of  `qt5-plugin-mysql`, `qt5-plugin-odbc`, `qt5-plugin-pgsql`, `qt5-plugin-sqlite` or `qt5-plugin-tds` to run. The dependency is missing.
I tested with `qt5-plugin-sqlite`, but i guess it should work with any of the above.
* xuname:  
Void 5.15.11_1 x86_64-musl AuthenticAMD uptodate rFFFFFFFFFFFF
* package:  
krita-5.0.0_1

**Comment by ericonr** [comment]
sqlite seems like a reasonable default.

Ping @Johnnynator or I can push with sqlite tomorrow.
