### ISSUE TITLE
wine always fails to load ws2_32.dll on musl

### ISSUE THREAD

**Issue by Hello71** [void-linux/void-packages#34707]
see https://gitlab.alpinelinux.org/alpine/aports/-/issues/13249, wine needs https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/wine/rpath.patch, otherwise wine 6.19+ always crashes and silently misbehaves before then. i checked it was broken on void musl about 4 weeks ago, didn't re-check since then but probably still broken.

**Comment by Hello71** [comment]
to reproduce, i did roughly `xbps-install -S wine; wine cmd` in a new Docker container.

**Comment by HadetTheUndying** [comment]
This should be pretty easy to fix with the patch already available. I can try to fix it up unless you want to open a PR for it. Were you able to get it to build and work with the patch using `xbps-src`?

**Comment by Hello71** [comment]
I didn't try because I don't know how to use xbps-src because I don't use void :)

**Comment by ericonr** [comment]
Thanks for the warning, I followed it some on IRC but didn't have the opportunity to act on it.
