### ISSUE TITLE
Audacity ABI Mismatch

### ISSUE THREAD

**Issue by jlneder** [void-linux/void-packages#34701]
* xuname:  
Void 5.15.11_1 x86_64-musl AuthenticAMD uptodate rFFFFFFFFFFFF
* package:  
audacity-2.4.1_2

Audacity needs recompilation, without it there is an abi mismatch:
```
23:14:18: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 2.8).
```

**Comment by tibequadorian** [comment]
How to reproduce this issue? Please fill out the issue template.
