### ISSUE TITLE
amdgpu problems on linux5.15

### ISSUE THREAD

**Issue by irrationalnumber** [void-linux/void-packages#34751]
### System

* xuname:  Void 5.10.88_1 x86_64 AuthenticAMD uptodate rF
  *output of ``xuname`` (part of xtools)*
* package:  linux5.15-5.15.11_1
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
A usable computer when using the default kernel. 

### Actual behavior
The computer is unbearably slow even when using tty. Downgrading the kernel fixes the problem. I also get more amdgpu dmesg errors on linux5.15.

linux5.15 dmesg errors (this is the version that doesn't work properly):
[    0.000000] AMD-Vi: [Firmware Bug]: : IOAPIC[130] not in IVRS table
[    0.000000] AMD-Vi: [Firmware Bug]: : IOAPIC[131] not in IVRS table
[    0.000000] AMD-Vi: [Firmware Bug]: : IOAPIC[132] not in IVRS table
[    0.000000] AMD-Vi: Disabling interrupt remapping
[    2.053428] [drm:retrieve_link_cap [amdgpu]] *ERROR* retrieve_link_cap: Read receiver caps dpcd data failed.
[    2.331931] [drm:smu_v11_0_i2c_xfer.cold [amdgpu]] *ERROR* Received I2C_NAK_7B_ADDR_NOACK !!!
[    2.332342] [drm:smu_v11_0_i2c_xfer [amdgpu]] *ERROR* WriteI2CData() - I2C error occurred :1
[    2.332514] [drm:amdgpu_ras_eeprom_init [amdgpu]] *ERROR* Failed to read EEPROM table header, res:-5
[    5.178029] wil6210 0000:04:00.0 (unnamed net_device) (uninitialized): wil_if_pcie_enable: 3 MSI mode failed, try 1 MSI

linux5.10 dmesg errors (this version works fine):
[    0.000000] AMD-Vi: [Firmware Bug]: : IOAPIC[130] not in IVRS table
[    0.000000] AMD-Vi: [Firmware Bug]: : IOAPIC[131] not in IVRS table
[    0.000000] AMD-Vi: [Firmware Bug]: : IOAPIC[132] not in IVRS table
[    0.000000] AMD-Vi: Disabling interrupt remapping
[    2.481088] [drm:retrieve_link_cap [amdgpu]] *ERROR* retrieve_link_cap: Read dpcd data failed.
[    3.872768] wil6210 0000:04:00.0 (unnamed net_device) (uninitialized): wil_if_pcie_enable: 3 MSI mode failed, try 1 MSI

### Steps to reproduce the behavior
Use linux5.15

**Comment by leahneukirchen** [comment]
Does 5.14 work?

**Comment by Vistaus** [comment]
I cannot reproduce this. Everything is super speedy and fluent over here. Maybe 5.16 will fix your issue as it contains a lot of AMDGPU optimizations.
