### ISSUE TITLE
[RFC] Ideas for check and CI

### ISSUE THREAD

**Issue by tornaria** [void-linux/void-packages#34766]
I'm listing here some random ideas for check and CI.\

From https://github.com/void-linux/void-packages/pull/34469#issuecomment-991778989:

 - have an option `[check-skip]` that works as `[ci-skip]` but instead of skipping the whole CI it will run it without `-Q`.

From https://github.com/void-linux/void-packages/pull/34469#issuecomment-1002142459:
Random ideas:
 - maybe we should fill issues for failing tests, so it's documented (e.g. when revbump, to know it's not an issue introduced by the lib update)
 - maybe have a way to indicate that some checks are expected to fail for certain archs. For instance, I'd mark bogofilter and inkscape as xfail for x86_64-musl. The check step would still run, but it wouldn't stop with an error on failure so the CI can keep going. E.g. `check_xfail="x86_64-musl"`.
 - maybe have a way to indicate that some checks should be skipped for certain archs. For instance, I'd mark gnuradio to skip checks for i686 so the CI wouldn't get stuck on a loose test. E.g. `check_skip="i686"`.

Policy could be to comment any `check_xfail` or `check_skip` with an issue number where it is well documented.

More random thoughts:
 - maybe useful to have an option for CI such that a failure on check doesn't stop; the pkg step would be run anyway. The whole thing would still show a failure at the end but at least one would know the packaging step runs ok.
 - similarly, if one package fails, keep building the rest (as long as its dependencies didn't fail on build or pkg). Print a complete and concise report at the end about which steps (build/check/pkg) failed for which pkgs, and still give error if anything failed.
 - I wonder if it would be possible to have "dynamic" steps in a CI job, I mean: instead of having one step "Build and check packages" have one separate step for each pkg that is built so it's easy to see logs for each pkg individually
 - Another question: would -t work in the CI? Would it make sense to run using it so building of one pkg doesn't affect building of others (avoid the libgomp issue). If -t doesn't work, could zap the masterdir between pkgs.

**Comment by paper42** [comment]
> * have an option `[check-skip]` that works as `[ci-skip]` but instead of skipping the whole CI it will run it without `-Q`.

Tests can be skipped with `make_check=ci-skip` in the template if they don't work in CI or `make_check=extended`.

> maybe have a way to indicate that some checks are expected to fail for certain archs. For instance, I'd mark bogofilter and inkscape as xfail for x86_64-musl. The check step would still run, but it wouldn't stop with an error on failure so the CI can keep going. E.g. check_xfail="x86_64-musl".

> maybe have a way to indicate that some checks should be skipped for certain archs. For instance, I'd mark gnuradio to skip checks for i686 so the CI wouldn't get stuck on a loose test. E.g. check_skip="i686".

This can already be done:
```
case "$XBPS_TARGET_MACHINE" in
	# reason
	i686*) make_check=no ;;
esac
```

It doesn't make much sense to run the tests, but then ignore the result, so I think not running tests is good enough for us.

> Policy could be to comment any check_xfail or check_skip with an issue number where it is well documented.

`$make_check` should always have a comment explaining why it's needed and can link to an upstream issue. `xlint` check for a comment and will throw an error when it's not there which makes the lint step in CI fail.
