### ISSUE TITLE
Package Request : labwc wayland compositor

### ISSUE THREAD

**Issue by gitpubber** [void-linux/void-packages#34782]
https://github.com/johanmalm/labwc

A Wayland stacking compositor . It is a wlroots-based stacking compositor aiming to be light-weight and independent, with a focus on simply stacking windows well and rendering some window decorations.

**Comment by paper42** [comment]
#33669

**Comment by notthewave** [comment]
#35017

**Comment by notthewave** [comment]
#35875

**Comment by uni-dos** [comment]
Any update on this?
