### ISSUE TITLE
nyxt: please add `gst-plugins-bad1` as dependency

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#34781]
### System

* xuname: 
 Void 5.15.11_1 x86_64 GenuineIntel notuptodate hold rFF
* package:  
  nyxt

### Expected behavior
Nyxt should open websites that need gst-* plugins.

### Actual behavior
https://github.com/atlas-engineer/nyxt/issues/1909

### Steps to reproduce the behavior
Install nyxt from the repository. Go to: https://kiwiirc.com/nextclient/irc.libera.chat/nyxt

**Comment by tibequadorian** [comment]
This is a good first issue!

**Comment by paper42** [comment]
vimb has the same issue

**Comment by averycoolbean** [comment]
by the looks of it the crashing has actually been resolved in webkitgtk 2.34.4, so uh, i guess this has been resolved by now

**Comment by averycoolbean** [comment]
so i just noticed we're still on 2.34, so i guess time to just backport those patches
