### ISSUE TITLE
qutebrowser does not start properly

### ISSUE THREAD

**Issue by balejk** [void-linux/void-packages#34797]
### System

* xuname:  
Void 5.15.12_1 x86_64-musl GenuineIntel uptodate rFFFF
* package:  
qutebrowser-2.4.0_1

### Expected behavior
qutebrowser starts and loads the startup/last open page.

### Actual behavior
In approximately two in three attempts, qutebrowser only displays blank white page and is unable to load any other page too (requested with `:open`) - detailed description can be found [here](https://github.com/qutebrowser/qutebrowser/issues/6926).

### Steps to reproduce the behavior
Launch qutebrowser.

**Comment by KSPAtlas** [comment]
I'm on glibc and have an issue with qutebrowser freezing my graphics.

**Comment by balejk** [comment]
@KSPAtlas Is this with the NVIDIA Noveau drivers by any chance? If so (and even if not), you might try to tinker with the QtWebEngine settings, in particular I'd try changing `qt.force_software_rendering` to see if it works with any of the [available options](https://www.qutebrowser.org/doc/help/settings.html#qt.force_software_rendering).

**Comment by balejk** [comment]
This seems to have ceased to happen, but I'm unable to tell why - until recently I have been running `qutebrowser` with `qt.chromium.low_end_device_mode` set to `always`, `qt.force_software_rendering` set to `software-opengl` and active `qt.workarounds.remove_service_workers` and with these settings the issue went away, however I have not been successful in attempts to pinpoint which particular setting helped (by only employing a subset of them). Currently I only have the `software-opengl` option set because without it I experience a different issue, the original one however does not occur anymore.
