### ISSUE TITLE
Cannot cross-compile gettext

### ISSUE THREAD

**Issue by lfdebrux** [void-linux/void-packages#34810]
### System

* xuname:  
  *Void 5.11.22_1 x86_64-musl GenuineIntel notuptodate rFFF*
* package:  
  *gettext-0.21_4*

### Expected behavior

`./xbps-src -a <target> configure gettext` runs successfully.

### Actual behavior

The pre-configure step fails with error

```
=> gettext-0.21_4: running pre_configure ...
... ( lines omitted)
configure.ac:25: error: AC_INIT should be called with package and version arguments
: gl_AM_INIT_AUTOMAKE is expanded from...
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:25: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
=> ERROR: gettext-0.21_4: pre_configure: 'autoreconf -fi' exited with 1
=> ERROR:   in pre_configure() at srcpkgs/gettext/template:42
```

I've tried this with various targets, the error is always the same.

I noticed that for this template the pre-configure step only happens when cross-compiling:

https://github.com/void-linux/void-packages/blob/2f4626f2c85e16e77a63b379e03c533adbdea9b9/srcpkgs/gettext/template#L39-L42

If the command to run `autoreconf` is removed from the template then the configure completes successfully, and the package can be built and run without any issues that I've seen.

**Comment by lfdebrux** [comment]
The step to run `autoreconf -fi` was added back in 2013 for version 0.18.3 of gettext:

https://github.com/void-linux/void-packages/commit/17f6ad8b9c9319c46820941e7fbae3f73ddcb20a

There isn't and detail in the commit message why running autoreconf is needed, I` tried googling 'gettext autoreconf' but couldn't find anything relevant. Googling 'gettext cross-compile' also didn't suggest that autoreconf is needed. There's also nothing about in the package `INSTALL` doc, either [then](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=INSTALL;h=671b157a6429121883c370dbfd80f4b09217cb26;hb=147dbca63d56e784ae0bfdf4e8174c110c384ec6) or [now](https://git.savannah.gnu.org/gitweb/?p=gettext.git;a=blob;f=INSTALL;h=671b157a6429121883c370dbfd80f4b09217cb26;hb=eb83efc3b58d690d444da0b82c3ecf36a54f28ac).

**Comment by ericonr** [comment]
Can you specify the target you're using?

The most likely thing is that their pre generated configure script had issues for cross which were fixed by re generating them. It's possible that no longer applies.

**Comment by lfdebrux** [comment]
@ericonr 

I was compiling for targets `i686-musl` and `armv5tel-musl`. Same result for both, error running `autoreconf`, compilation went fine. I also tried with `i686` and `x86_64`, also got the same error.

I'm not sure the target makes a difference, it just seems like running autoreconf doesn't work in the gettext source directory? I didn't try running autoreconf on a glibc system though, I guess that could make a difference?

**Comment by ericonr** [comment]
Ok, I can reproduce this locally.

I think it has to do with the automake updates... Fixing this in their build system would be ideal, but I'm not sure I'd like to delve inside :P 

If you'd like to create a PR to remove the autoreconf, that sounds reasonable.
