### ISSUE TITLE
ghc: FTBFS

### ISSUE THREAD

**Issue by copyleftie** [void-linux/void-packages#3481]
### System

* xuname:  
 `Void 4.18.11_blackbox x86_64 GenuineIntel uptodate rFFFF`
* package:  
 `ghc-8.4.3_1`

### Expected behavior
`xbps-src build ghc` should work

### Actual behavior
The build fails very late while `make`ing documentation, as shown here. [ghc.log](https://github.com/void-linux/void-packages/files/2452128/ghc.log) I cannot produce a full log at the moment (I'm working on that now).

### Steps to reproduce the behavior
`xbps-src build ghc`

**Comment by maxice8** [comment]
Closing this as ghc was updated recently. Please re-open if issue persists
