### ISSUE TITLE
Cannot find epson-inkjet-printer-escpr2 package, even with nonfree repository enabled

### ISSUE THREAD

**Issue by tjk918** [void-linux/void-packages#34855]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
Void 5.15.11_1 x86_64 GenuineIntel uptodate rrFFFFF

* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``
epson-inkjet-printer-escpr2 1.1.24 (name and version found in template file)

### Expected behavior
Expected package ``epson-inkjet-printer-escpr2`` to be avaliable in void repos since it is listed in this repository under srcpkgs
I have the nonfree repo enabled, it doesn't show up on the void linux package directory on ``voidlinux.org`` either

### Actual behavior
Package cannot be listed using xbps-query or on the voidlinux.org/packages/ website

### Steps to reproduce the behavior
``xbps-query epson-inkjet-printer-escpr2``

epson-inkjet-printer-escpr lacks support for newer printers. epson-inkjet-printer-escpr2 supports newer printers, but lacks support for the printers supported by epson-inkjet-printer-escpr.

**Comment by ericonr** [comment]
Closing since there isn't anything to act on.
