### ISSUE TITLE
A few SDL2 packages are missing statically linked libraries

### ISSUE THREAD

**Issue by Toasterbirb** [void-linux/void-packages#35087]
### System

* xuname:  
  Void 5.15.12_1 x86_64 AuthenticAMD notuptodate rrrmFFFFF
* package:  
  * SDL2_image-2.0.5_2
  * SDL2_net-2.0.1_3
  * SDL2_ttf-2.0.15_1
  * SDL_image-1.2.12
  * SDL_mixer-1.2.12_14
  * SDL_net-1.2.8_6
  * SDL_sound-1.0.3_7
  * SDL_ttf-2.0.11_7
 
(list might not be complete)

### Expected behavior
\*-devel package would contain static-linked libraries (*.a files)

### Actual behavior
Only dynamically linked libraries are included

**Comment by jobbautista9** [comment]
Hi, it seems this issue is still relevant, `libSDL2_ttf.a` doesn't exist in the `SDL2_ttf-devel` package. I'm using the musl version of Void Linux. Meanwhile in Debian [it exists](https://packages.debian.org/sid/amd64/libsdl2-ttf-dev/filelist).
