### ISSUE TITLE
Enable VAAPI in chromium ozone wayland

### ISSUE THREAD

**Issue by gitpubber** [void-linux/void-packages#35080]
Hello @Duncaen ,

I am using sway and chromium. I mentioned you because you maintain chromium package.

Currently, VAAPI can only be used in chromium Ozone X11(opt-in) . It is not possible to use VAAPI in Wayland because they haven't enabled yet.

But, this patch 
https://aur.archlinux.org/cgit/aur.git/plain/0001-ozone-wayland-add-VA-API-support.patch?h=chromium-wayland-vaapi
enables VAAPI in Ozone wayland. It will be Opt-in , i.e, it will not be enabled by default (user must manually enable it via chromium flags). It will not cause any degradation in other aspects whatsoever.

Context:
https://www.reddit.com/r/swaywm/comments/rxrccc/wayland_hardware_acceleration_in_chromium/

https://aur.archlinux.org/packages/chromium-wayland-vaapi/

Thank you very much

**Comment by Duncaen** [comment]
I'm not interested in adding patches that I don't want to test or fix on later updates. If someone else would like to take over chromium and provide updates in a timely manner that is fine with me.

**Comment by gitpubber** [comment]
@Duncaen , I am perfectly fine with you maintaining this package.you are doing great job. i just wanted this patch to get merged. i am fine if you don't merge.
