### ISSUE TITLE
Package request: `python3-opencv`

### ISSUE THREAD

**Issue by rivanfebrian123** [void-linux/void-packages#35086]
We already have `opencv`, but its not integrated yet to `python3`

**Comment by Chocimier** [comment]
Isn't libopencv-python3 what you need?

**Comment by rivanfebrian123** [comment]
@Chocimier Yeah, surprisingly, it is. Why it has different naming convention tho?

**Comment by paper42** [comment]
That's the naming convention for subpackages and this is a subpackage of opencv - https://github.com/void-linux/void-packages/blob/master/srcpkgs/opencv/template
