### ISSUE TITLE
Split mumble and murmur packages

### ISSUE THREAD

**Issue by TalviT** [void-linux/void-packages#35110]
Currently the murmur package links to mumble.
Since I want to run murmur on a headless server, I would prefer not to have to install the qt5 packages.
Unfortunately I have no experience to build packages myself, but I found that the mumble documentation provides a list of build flags in which client build can be disabled:
https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/cmake_options.md#client

**Comment by oynqr** [comment]
Murmur depends on qt5, there's no way around that. If you want a headless alternative, try uMurmur.

**Comment by paper42** [comment]
> Murmur depends on qt5, there's no way around that. If you want a headless alternative, try uMurmur.

That might be true, but also we can avoid 200MB (from 546MB) of dependencies if we don't make it depend on mumble, because mumble pulls in GTK3 and all its dependencies.

**Comment by paper42** [comment]
murmur now doesn't depend on mumble
