### ISSUE TITLE
Discord Support For Musl

### ISSUE THREAD

**Issue by JuniorSuperTux** [void-linux/void-packages#35132]
### System

* xuname:  
  Void 5.15.14_1 x86_64-musl GenuineIntel notuptodate rFF
* package:  
  discord-0.0.16_2

### Expected behavior
Puts Discord in local repo
### Actual behavior
```
=> xbps-src: updating repositories for host (x86_64-musl)...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/nonfree/x86_64-musl-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/debug/x86_64-musl-repodata' ...
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> discord-0.0.16_2: removing autodeps, please wait...
=> ERROR: discord-0.0.16_2: this package cannot be built for x86_64-musl.
```
### Steps to reproduce the behavior
```
./xbps-src pkg discord
```

**Comment by Johnnynator** [comment]
Not feasible, discord downloads libs at runtime that are linked against glibc, and patching their code is against their tos.

So to actually see this happen two things would have to happen
a) Discord allowing third party/modified  clients
b) Discord open sourcing their client.

**Comment by melroy89** [comment]
Discord really really need to change their license.
