### ISSUE TITLE
Setting default command line options in etc/conf isn't working

### ISSUE THREAD

**Issue by lfdebrux** [void-linux/void-packages#35139]
### System

* xuname:  `Void 5.11.22_1 x86_64-musl GenuineIntel uptodate rFFF`
* package:  `xbps-src`

### Expected behavior

Setting an option in `etc/conf` should have the same effect as calling `xbps-src` with a command line parameter, as documented in `xbps-src`:

https://github.com/void-linux/void-packages/blob/5f589a9962d7871deedbaa3d3e92751ace5ef1d6/xbps-src#L365-L367

### Actual behavior

Some options don't have any effect. I think this is because they get lost when the chroot is entered, because they aren't added to `XBPS_OPTIONS` or `$XBPS_MASTERDIR/etc/xbps/xbps-src.conf`.

### Steps to reproduce the behavior

For example, if I want to avoid adding `-a armv5tel-musl` to the command line every time:

1. Checkout latest version of void-linux/void-packages
2. Add file `etc/conf` with contents `XBPS_CROSS_BUILD=armv5tel-musl`
3. Run `xbps-src pkg base-files`

I expect it to build a package for `armv5tel-musl`, instead it builds a package for `x86_64-musl` (the native arch).

**Comment by Chocimier** [comment]
No variables other than documented in etc/defaults.conf are expected to have effect on xbps-src.
In particular, setting `XBPS_CROSS_BUILD` from config file would break building host dependencies needed for cross built packages.

Your best option is to create a separate script containing `./xbps-src -a armv5tel-musl "$@"`.

**Comment by lfdebrux** [comment]
I see. Thanks for explaining that!
