### ISSUE TITLE
Bug: udevd error calling EVIOCSKEYCODE

### ISSUE THREAD

**Issue by LeamHall** [void-linux/void-packages#35133]
### System
* xuname:  
Void 5.13.19_1 x86_64 GenuineIntel notuptodate rFF

### Expected behavior

No udev errors on boot.

### Actual behavior

[   11.136077] udevd[658]: Error calling EVIOCSKEYCODE on device node '/dev/input/event2' (scan code 0xc022d, key code 103): Invalid argument
[   11.136651] udevd[658]: Error calling EVIOCSKEYCODE on device node '/dev/input/event2' (scan code 0xc022e, key code 108): Invalid argument

### Steps to reproduce the behavior
dmesg |grep -i error

**Comment by lukeflo** [comment]
Already an older issue. But if it is still pending, there maybe a solution. Had a similar issue and was able to solve it. Just have a [look](https://github.com/eudev-project/eudev/issues/281).
