### ISSUE TITLE
Package Request: Czkawka (find file duplicates with perceptual hashes)

### ISSUE THREAD

**Issue by notthewave** [void-linux/void-packages#35145]
https://qarmin.github.io/czkawka/

https://github.com/qarmin/czkawka/releases/tag/4.0.0
https://github.com/qarmin/czkawka

**Comment by sirkhancision** [comment]
Made a [template](https://github.com/void-linux/void-packages/commit/eb93abb6fed9205e0c77c9036537f8169189e4bb) for it, but we gotta wait for Rust to be updated (#42130) before the package can be built.
