### ISSUE TITLE
ping not useable by user

### ISSUE THREAD

**Issue by LeamHall** [void-linux/void-packages#35142]
### System

* xuname:  

Void 5.13.19_1 x86_64 GenuineIntel notuptodate rFF

* package:  

iputils-20210722_1

### Expected behavior

ping 127.0.0.1
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.025 ms

--- 127.0.0.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.025/0.025/0.025/0.000 ms

### Actual behavior

No return for non-root user, error code 2.

### Steps to reproduce the behavior

ping anything as a user.

**Comment by Duncaen** [comment]
The capabilities might be missing for some reason assuming its iputils, try `xbps-reconfigure -f iputils`.

**Comment by LeamHall** [comment]
That did it, thanks!
