### ISSUE TITLE
glow stopped displaying colors properly with a pager

### ISSUE THREAD

**Issue by borjator** [void-linux/void-packages#35168]
### System

* xuname:  
  *Void 5.15.9_1 x86_64 GenuineIntel uptodate rFFFFF*
* package:  
  *glow-1.4.1_1*

### Expected behavior

`glow -p` displays formatted Markdown with colors in my pager (less)

### Actual behavior

It shows a lot of color codes without interpreting them:
`ESC[38;5;228;48;5;63;1mESC[0mESC[38;5;228;48;5;63;1mESC[0m  ESC[38;5;228;48;5;63;1m ESC[0mESC[38;5;228;48;5;63;1mHelloESC[0mESC[38;5;228;48;5;63;1m ESC[0mESC[38;5;252mESC[38;5;252m`

### Steps to reproduce the behavior

1. Create a simple Markdown file: `echo "# Hello" > hello.md`
2. Display it with glow with a pager: `glow -p hello.md`

I'm not completely sure if this is a glow bug since I've tried a bunch of different things:

- The previous version of _glow_
- Older versions of _less_ (my favourite pager)
- I can confirm the same happens with _most_ my second favourite pager
- I've tried to use a different terminal (_xterm_ instead of _xst_)
- I tested using a different `TERM` environment variable just in case

Anything else I could try?

**Comment by demostanis** [comment]
less by default does not interpret escape sequences. Try setting the `LESS='-R'` environment variable:
`LESS='-R' glow -p index.md`
It works fine too if you don't pass `-p`.

**Comment by borjator** [comment]
Thank you! That fixed the issue for me.

It's weird because I had an alias for less `alias less="less -R"` and that was working previously.
