### ISSUE TITLE
Package Request: exfatprogs

### ISSUE THREAD

**Issue by carbongreat13** [void-linux/void-packages#35172]
- Upstream URL: https://github.com/exfatprogs/exfatprogs
- Latest release page: https://github.com/exfatprogs/exfatprogs/releases/tag/1.1.3
- LICENSE: [GPLv2](https://github.com/exfatprogs/exfatprogs/blob/master/COPYING)
# Incentive
The current Linux kernel is able to access exfat without FUSE.
It would be nice if userspace programs could also use the non-FUSE version.

**Comment by classabbyamp** [comment]
done in #32744
