### ISSUE TITLE
bug: Failed to execute default Terminal Emulator

### ISSUE THREAD

**Issue by LeamHall** [void-linux/void-packages#35197]
### System

Sorry, can't run a terminal to cut and past from. X86-64 Void Linux, just patched.

Running XFCE

### Expected behavior

 Click terminal icon, get a terminal.

### Actual behavior

Error message popup: Failed to execute default Terminal Emulator. Input/output error.

### Steps to reproduce the behavior

Try to open terminal under XFCE.

**Comment by paper42** [comment]
Due to #32076 the system didn't fully update, @LeamHall used a script to update the system and didn't check the logs. This resulted in libicu being updated, but many of its dependants not which broke many applications.
