### ISSUE TITLE
bug: XFCE PolicyKit Agent

### ISSUE THREAD

**Issue by LeamHall** [void-linux/void-packages#35198]
### System

Sorry, no terminal. See issue 35197.

### Expected behavior

Login to XFCE.

### Actual behavior

Get "XFCE PolicyKit Agent" error. "Error initializing authority: Error calling StartServiceByName for org.freedesktop.PolicyKit1: Launch helper exited with unknown return code 127"

### Steps to reproduce the behavior

Login with XFCE.

**Comment by paper42** [comment]
Is this on the xfce live iso or after installation from it? Or is this after a base installation and installing xfce4? How are you starting xfce? You can run the commands required for the System part in a tty (ctrl-alt-f2).

**Comment by LeamHall** [comment]
This is an existing node with XFCE as the primary login window manager. Have been running Void on it daily, for some time. This morning's update broke things, last update was a week ago.  

Oh, here's a funny. I can ctl-alt-f1, run xuname into a file, chmod the file, and then open it with Mousepad. Some applications work, like Mousepad and Firefox. Some don't. Anyway:

Void 5.13.19_1 x86_64 GenuineIntel notuptodate rFF

The "notuptodate" doesn't inspire confidence, since I just did an update. Here's the working part of the script I use for updates.

###
date=`date +%Y%m%d`
logfile="/var/tmp/xbps-install_Suvy_${date}.log"

# Removes old kernels.
vkpurge rm all > $logfile 2>&1

# Updates, and keeps a log.
xbps-install -Suvy >> $logfile 2>&1

# Lets the system quiesce.
sleep 10

# Removes old packages that are no longer needed.
xbps-remove -O >> $logfile 2>&1

# updates the CA certificates
update-ca-certificates >> $logfile 2>&1

# Updates the locate db.
updatedb >> $logfile 2>&1

###

**Comment by paper42** [comment]
same issue as #35197
