### ISSUE TITLE
Libvirt 8.0 don't work? 

### ISSUE THREAD

**Issue by Naia-love** [void-linux/void-packages#35208]
### System

* xuname:  
  ``Void 5.15.11_1 x86_64 AuthenticAMD notuptodate rrrrmmnDFFFFFFFFFF``
* package:  
  libvirt-8.0.0_1

### Expected behavior

To run after upgrading it

### Actual behavior

after upgrading it and restarting pc, libvirtd service start on crash, when trying to run ``libvirtd`` directly it give me this error:
```
❯ libvirtd
2022-01-23 19:49:57.635+0000: 12789: info : libvirt version: 8.0.0
2022-01-23 19:49:57.635+0000: 12789: info : hostname: home
2022-01-23 19:49:57.635+0000: 12789: error : virModuleLoadFile:53 : 内部エラー: Failed to load module '/usr/lib64/libvirt/connection-driver/libvirt_driver_network.so': /usr/lib/libvirt.so.0: version `LIBVIRT_PRIVATE_7.10.0' not found (required by /usr/lib64/libvirt/connection-driver/libvirt_driver_network.so)
```
which imply that said module didn't get updated to use libvirt 8? not idea how that can happen

### Steps to reproduce the behavior
I just upgrade libvirt from 7.10 to 8

(edit: I confirm that downgrading to libvirt 7.10 make it work again)

**Comment by paper42** [comment]
I can not reproduce this, somehow you ended up with only half of the package updated, try updating the whole system and make sure you don't have any ignorepkg, noextract or preserve options that could interfere in your config. After the full system update, please run `xbps-pkgdb -a` to check for broken packages on the system.

**Comment by abenson** [comment]
The service needs to be restarted after update.

**Comment by Naia-love** [comment]
oh sorry i forgot I had this opened. I fixed it, I had a bug with my ldconfig, kinda hard to explain but it was my fault sorry ahah ^^'

**Comment by zenny** [comment]
I needed to restart the service after updating to v8.10. of libvirt (a simple `sv restart libvirtd` worked wonders). It was otherwise giving an error related connection to the libvirt-storage as stated in http://ix.io/3RlZ. Cheers,
