### ISSUE TITLE
xbps-src: XBPS_MAKEJOBS does not take value when set in CLI

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-packages#35223]
### System

* xuname: Void 5.15.14_1 x86_64 AuthenticAMD notuptodate rrFFFFFFFFFFFFFFF

### Expected behavior

```
$ XBPS_MAKEJOBS=12345 ./xbps-src show-var XBPS_MAKEJOBS
12345
```
or
```
$ export XBPS_MAKEJOBS=12345
$ ./xbps-src show-var XBPS_MAKEJOBS
12345
```

### Actual behavior

```
$ XBPS_MAKEJOBS=12345 ./xbps-src show-var XBPS_MAKEJOBS
# takes value from etc/conf
12
```
or
```
$ export XBPS_MAKEJOBS=12345
$ ./xbps-src show-var XBPS_MAKEJOBS
# takes value from etc/conf
12
```
If no value was set in `etc/conf`:
```
$ XBPS_MAKEJOBS=12345 ./xbps-src show-var XBPS_MAKEJOBS
# empty
```

### Steps to reproduce the behavior

see above.

**Comment by Chocimier** [comment]
Documented ways to set jobs number are flag and etc/conf entry.
What makes you expect env var to set it?

**Comment by classabbyamp** [comment]
not sure, but someone else also ran into this when testing #34989

**Comment by Chocimier** [comment]
Ok, so this is just misunderstanding. Env var is not meant to work. I can leave it open as feature request, but I don't think it is good idea to multiply inputs.

**Comment by abenson** [comment]
If you want to set it on the command line, use the `-j` flag.

     `$ ./xbps-src -j 8 pkg bigpackage`

**Comment by classabbyamp** [comment]
yes that was [discovered](https://github.com/void-linux/void-packages/pull/34989#issuecomment-1014878030)
