### ISSUE TITLE
Request: Wasabi

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#35228]
- Upstream: https://wasabiwallet.io/
- Latest release: https://github.com/zkSNACKs/WalletWasabi/releases/tag/v1.1.13.0

Wasabi is a privacy-focused Bitcoin wallet.

**Comment by kawaiiamber** [comment]
The project needs .NET 6.0 SDK. The most recent PR for dotnet ( [32974](https://github.com/void-linux/void-packages/pull/32974) ) was recently closed. So, it looks like it will be a while before this is doable - packaging wasabi, since dotnet SDK is a requirement.
