### ISSUE TITLE
Is the "Find binary packages" on the Void website dead?

### ISSUE THREAD

**Issue by carbongreat13** [void-linux/void-packages#35231]
[The package search page](https://voidlinux.org/packages/) will show libressl that has already been removed.
On the other hand, [1password](https://github.com/void-linux/void-packages/tree/master/srcpkgs/1password), which should exist, does not show up.
Why is this?

**Comment by Duncaen** [comment]
1password is a restricted package, its only available to build, not as binary package. Most likely because the license does not allow redistribution.

libressl and other packages might have been removed from the source repository, but they are not automatically removed from the repository index.
