### ISSUE TITLE
Request: op(1Password CLI)

### ISSUE THREAD

**Issue by carbongreat13** [void-linux/void-packages#35230]
- Releases: https://app-updates.agilebits.com/product_history/CLI
- License: Proprietary(closed-source)

**Comment by motorto** [comment]
@carbongreat13 Could you please test my pr on your machine and leave some feedback ? 

#35426

**Comment by ahesford** [comment]
Closing as WONTFIX. 1password-cli is a single executable that you can just grab from the web and leave in `~/bin`.
