### ISSUE TITLE
Cannot delete Dracut

### ISSUE THREAD

**Issue by carbongreat13** [void-linux/void-packages#35242]
### System
* package:  linux-base

I can't remove dracut because linux-base depends on dracut.
I want to remove dracut and use mkinitcpio instead.
Could you please fix the dependency?
In Arch Linux, there is a virtual package called initramfs, and there are three to choose from: dracut, mkinitcpio, and bootster.

**Comment by Duncaen** [comment]
https://docs.voidlinux.org/xbps/advanced-usage.html?highlight=ignorepkg#ignoring-packages
