### ISSUE TITLE
build firefox without dbus?

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#35259]
I wonder if it would make any sense for Void to build firefox without dbus support, namely
`build_options_default="alsa jack pulseaudio xscreensaver sndio wayland"`,
which would not pull in dbus as a dependency (as it happens for chromium, incidentally).
The same one could say for thunderbird.

Are there important drawbacks in doing this?
@Duncaen

**Comment by Duncaen** [comment]
Other dependencies pull in dbus already, there is no point in regressing features just to get rid of the dbus toplevel dependency.

**Comment by dkwo** [comment]
You're right, basically thorugh at-spi2-atk in gtk+3 (though e.g. kiss builds without).
I'll try the ignorepkg=dbus option as you suggest.
Thank you!

**Comment by biopsin** [comment]
@dkwo  remember also no dbus and at-spi2-atk also hinders the suspend of dpms while video playback, 
so I had to disabled dpms when whatching videos longer then my set xorg offtime.
