### ISSUE TITLE
[Package request] Muttwizard

### ISSUE THREAD

**Issue by MPC7500** [void-linux/void-packages#35330]
**About:** Muttwizard is a tool that automatically sets up a neomutt-based minimal email system.

**Website:** https://muttwizard.com/
**Repository:** https://github.com/lukesmithxyz/mutt-wizard

**License:** GNU General Public License v3.0

**Why?** Easy way to setup Mutt/ NeoMutt

**Comment by motorto** [comment]
Hi could you please test this pr #35694 ?

**Comment by motorto** [comment]
Probably not the easiest way but I would do:

```sh
git clone https://github.com/void-linux/void-packages.git
cd void-packages 
./xbps-src binary-bootstrap
wget https://github.com/void-linux/void-packages/pull/35697.diff
git apply 35697.diff
./xbps-src pkg mutt-wizard
xi mutt-wizard #assuming that you have xtools installed if not, xbps-install xtools
```

**Comment by MPC7500** [comment]
Thanks! I tried it. It looks good. Working so far. I also installed pam-gnupg, but this is an optional package anyway. Thanks again for your help

**Comment by motorto** [comment]
It will close after the pr gets merged. thanks for your help

**Comment by MPC7500** [comment]
It isn't still not merged.

**Comment by dataCobra** [comment]
Hey @MPC7500,

since the old PR got closed I'll create a new one and get it merged.

**Comment by dataCobra** [comment]
Hey @MPC7500,

I've created the PR #38615.

Could you please test it and give me feedback?

You can do it via the explanation @motorto already gave.

**Be sure to change the `35697.diff` to `38615.diff`.**

**Comment by paper42** [comment]
This is a shell script, so it doesn't meet quality requirements
