### ISSUE TITLE
Mattermost-Desktop doesn't launch

### ISSUE THREAD

**Issue by tunefish777** [void-linux/void-packages#35338]
### System

* xuname:  
  Void 5.15.17_1 x86_64 GenuineIntel notuptodate rrrrmmnFFFF
* package:  
  *affected package(s) including the version*: mattermost-desktop-4.6.0_1

### Expected behavior
Mattermost application launches successfully

### Actual behavior
Application doesn't launch. Terminal shows the following error message:
```electron7: symbol lookup error: electron7: undefined symbol: hb_subset_input_set_drop_hints```

### Steps to reproduce the behavior
- Install the package
- Try to launch it from a terminal

**Comment by Duncaen** [comment]
We have no control over mattermost, there is nothing we can do about them using an old electron version that requires a unstable and removed function from harfbuzz.
