### ISSUE TITLE
jupyterlab doesn't work out of the box

### ISSUE THREAD

**Issue by tornaria** [void-linux/void-packages#35341]
### Steps to reproduce the behavior

1. install package `jupyterlab`
2. run `jupyter-lab` in a terminal (as a regular user fwiw)
3. an error pops up both in the terminal and in a browser:
```
[E 2022-02-01 09:38:05.353 LabApp] JupyterLab application assets not found in "/usr/share/jupyter/lab"
[E 2022-02-01 09:38:05.353 LabApp] Please run `jupyter lab build` or use a different app directory
```

I was able to workaround by creating my own app directory as follows:
```
$ mkdir ~/lab
$ jupyter lab build --app-dir=~/lab
```
and then run jupyter lab as
```
$ jupyter lab --app-dir=~/lab
```

Beware: this will take some time and bring up (download I guess?) ~400M of nodejs stuff. I'm not sure one would want to ship that inside the xbps, maybe give some warning or instructions to the user?

Cc: @dkwo

**Comment by dkwo** [comment]
Indeed, with a local `app-dir`, it seems to work fine, after first (re)build.

**Comment by tornaria** [comment]
> Indeed, with a local `app-dir`, it seems to work fine, after first (re)build.

If the system-wide app-dir will never work (except for root) maybe it's possible to configure it to use a default user appdir, do they have a standard location for that?

In such a way that it's enough to run `jupyter lab build` as the error suggests.

**Comment by dkwo** [comment]
From the docs: The application directory can be overridden using the `--app-dir` command-line option in any of the JupyterLab commands, or by setting the `JUPYTERLAB_DIR` environment variable.

Arch wiki suggests to use
`export JUPYTERLAB_DIR=$HOME/.local/share/jupyter/lab`

What is the correct way to encode this into the package?

**Comment by ahesford** [comment]
The best way to make this a default is probably to add shell snippets to `/etc/profile.d`, which should be picked up by most users. (And those that don't will have overridden default behavior and should know enough to configure what they need.)

**Comment by dkwo** [comment]
I tried to do as suggested, please take a look.
