### ISSUE TITLE
[package request] SwayNotificationCenter

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#35360]
A simple notification daemon with a GTK gui for notifications and the control center for sway.

https://github.com/ErikReider/SwayNotificationCenter

**Comment by motorto** [comment]
Could you please test my pr as well ?

**Comment by LinArcX** [comment]
Any update?

**Comment by motorto** [comment]
Inside this PR: #35862, there is a template I made it worked fine last time it my tests didn't want to maintain the package so I closed the PR. 

If you want to test the test my pr and possible update it, and push it here (and maybe maintain the package), feel free to use my template

**Comment by akhiljalagam** [comment]
https://github.com/void-linux/void-packages/pull/40099

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/55bf1190e2eecc34d99ed501e2fab11fa30e90ea
