### ISSUE TITLE
Chromium seemingly has incomplete dependencies

### ISSUE THREAD

**Issue by bluej99** [void-linux/void-packages#35387]
### System

* xuname:  
  *Void 5.15.19_1 x86_64*
* package:  
  *chromium-97.0.4692.99_1*

### Expected behavior
Chromium should contain all of its dependencies and should start with the flag --ozone-platform-hint=auto on a wayland-only machine
### Actual behavior
a trace/breakpoint error
### Steps to reproduce the behavior
install chromium and run it on the command line
### SOLUTION
I tried everything, put my user in all possible groups, updated fontconfigs, etc. The actual solution was to have Electron13 installed on my system. This happened by accident as I happened to install vscode this morning, which depends on Electron13. Now, chromium starts without a hitch on wayland natively. Running xbps-query -x chromium does NOT have Electron as a dependency. I can create a PR if others can confirm this issue.

**Comment by abenson** [comment]
I do not have `electron13` installed and I've had no issues with `chromium`, so I'm unsure of this.

**Comment by bluej99** [comment]
> I do not have `electron13` installed and I've had no issues with `chromium`, so I'm unsure of this.

This is what others also told me. I'm not sure where I screwed up. I've decided to keep electron13 installed just for this reason
