### ISSUE TITLE
greetings: vb aka vb-linux

### ISSUE THREAD

**Issue by zen0bit** [void-linux/void-packages#35407]
(It isnt really issue I hope)
# I am forking Void linux
 and I hope for great cooperation with void devs

Which I offer from the start..

Why I do that?

1. I love void
2. I want branded void linux for desktop on x86_64 platform
3. I want more people use void linux instead of different OS
4. Help promote excellent void linux
5. help promote privacy, security and federation
6. help promote GNU/linux and FOSS in general
7. help create FOSS world bigger
8. because I can
9. have fun
10. learn  

@zen0bit from @oSoWoSo
https://osowoso.xyz/vb.html

PS: If void devs or anyone have some suggestion, help, advice etc..
	 Throw them to me...

I will keep updated this if void dont mind
so you know what I am doing with your grandchild

If you are interested
...
stay in touch...

**Comment by Duncaen** [comment]
Ok, we don't endorse third party repositories,

**Comment by zen0bit** [comment]
I dont wanna fork it at a start, but you (not personally and no offence) force me to do it...

PS: I get that our scopes are littlebit different but I wanna help you create void better
	I see vb-linux as testing branch of void linux
	I wanna push hopefully most changes back to you because I am gratefull
		 WHAT YOU DOING FOR ALL OF US
	And we are creating open source software together so ...
	(I dont't fully understand all licenses yet so I choosed EUPL 1.2 for start which looks to me good but we can discuss this)

**Comment by paper42** [comment]
We appreciate all meaningful contributions, but let's use issues in Void repositories for issues in Void Linux. This is not an issue and not in Void Linux.
