### ISSUE TITLE
nvidia470: erroneous rdep on nvidia-libs

### ISSUE THREAD

**Issue by 123randomuser321** [void-linux/void-packages#35408]
### System

* xuname:  
  *Void 5.15.19_1 x86_64 AuthenticAMD notuptodate rrrrmmnFFFFFF* (notuptodate since a manual partial update had to be performed)
* package:  
  *nvidia470-470.103.01_1*

### Expected behavior
``xbps-install -S nvidia470`` installs nvidia470 and its dependencies without hiccup

### Actual behavior
``xbps-install -S nvidia470`` tries to pull in nvidia-libs as dependency of nvidia470;
xbps then aborts the installation process because the files contained in nvidia470-libs and nvidia-libs conflict

### Steps to reproduce the behavior
``xbps-install -S nvidia470``
``xbps-query -Rx nvidia470`` --> Both nvidia470-libs and nvidia-libs are listed

**Comment by motorto** [comment]
@abenson Need some help here cant find any reference to nvidia-libs on the nvidia-470 template ...

**Comment by Chocimier** [comment]
=> nvidia470-470.103.01_1: running pre-pkg hook: 04-generate-runtime-deps ...
       SONAME: libnvidia-ml.so.1 <-> nvidia-libs>=346.47_1
