### ISSUE TITLE
Git without perl

### ISSUE THREAD

**Issue by UsernameRandomlyGenerated** [void-linux/void-packages#35419]
I saw the similar thread on reddit about having git without perl in repos and the explanation from Duncaen, but what if we turn it around and just add git-core subpackage that will not have all the perl dependencies? The main git package will still pull perl and work fine but we'll also have "core" one for people who want to save a little bit of space and/or network usage after fresh install.

**Comment by sgn** [comment]
You can install `chroot-git` and `alias git=chroot-git` for minimalist ;)

**Comment by sgn** [comment]
anyway, not a promise, but when Git switch to use built in (`git add -i`)[1], git without perl could be discussed again.

1: https://lore.kernel.org/git/pull.1087.git.1638281655.gitgitgadget@gmail.com/

https://lore.kernel.org/git/pull.1087.git.1638281655.gitgitgadget@gmail.com/
