### ISSUE TITLE
dnote-cli: dnote: command not found: dnote

### ISSUE THREAD

**Issue by shizonic** [void-linux/void-packages#3541]
### System

* xuname:  
  * Void 4.18.12_2 x86_64 GenuineIntel uptodate rrFFFFFFF
* package:  
  * dnote-cli-0.4.4_1

### Expected behavior
The binary file `dnote` is executable after installation.

### Actual behavior
The binary can't be found.

### Steps to reproduce the behavior
1. Install the `dnote-cli` package using xbps-install
2. Try execute `dnote` on the shell

**Comment by maxice8** [comment]
the binary is called `cli`

**Comment by shizonic** [comment]
@maxice8 Okay got this. But it's a little bit confusing. `cli` could be everything...

**Comment by maxice8** [comment]
On Mon, Oct 08, 2018 at 12:34:27AM -0700, shizonic wrote:
> @maxice8 Okay got this. But it's a little bit confusing. `cli` could be everything...
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/3541#issuecomment-427743650

Looking at their github it seems that they use dnote instead of cli, i'll see what i can do

**Comment by shizonic** [comment]
@maxice8 Okay thanks!
