### ISSUE TITLE
Segmentation fault with latest nvidia driver

### ISSUE THREAD

**Issue by Le0xFF** [void-linux/void-packages#35411]
### System

* xuname:  
  ``Void 5.15.19_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFFFF``
* package:  
  ``nvidia-510.47.03_1``

### Expected behavior
`xbps-install -S nvidia` installs `nvidia` package without any problem as it was until yesterday.

### Actual behavior
Once installed and after a reboot, Xorg crashes with segmentation fault and all I have is just a black screen.
[Xorg.0.log.old.log](https://github.com/void-linux/void-packages/files/8005483/Xorg.0.log.old.log)
[Xorg.0.log](https://github.com/void-linux/void-packages/files/8005480/Xorg.0.log)
[lxdm.log](https://github.com/void-linux/void-packages/files/8005485/lxdm.log)

### Steps to reproduce the behavior
`xbps-install -S nvidia`

Maybe it could be an hardware plus software related issue?
I'm using nVidia GTX1080 and Mate DE.

**Comment by motorto** [comment]
Does old.log correspond to a previous working version (aka before updating the drivers) ? 

Could you please downgrade the nvidia drivers and check if it is working properly ? (just uninstall nvidia, and install nvidia470) 

On Xorg.0.log.old.log logs it seems to be loading the nouvaeu driver as well 

```
[     6.656] (II) LoadModule: "nvidia"
[     6.657] (II) Loading /usr/lib64/xorg/modules/drivers/nvidia_drv.so
[     6.671] (II) Module nvidia: vendor="NVIDIA Corporation"
[     6.671] 	compiled for 1.6.99.901, module version = 1.0.0
[     6.671] 	Module class: X.Org Video Driver
[     6.672] (II) LoadModule: "nouveau"
[     6.672] (II) Loading /usr/lib64/xorg/modules/drivers/nouveau_drv.so
[     6.676] (II) Module nouveau: vendor="X.Org Foundation"
[     6.676] 	compiled for 1.20.10, module version = 1.0.17
[     6.676] 	Module class: X.Org Video Driver
[     6.676] 	ABI class: X.Org Video Driver, version 24.1
```

**Comment by Le0xFF** [comment]
> Does old.log correspond to a previous working version (aka before updating the drivers) ?

No, both file are freshly generated at boot, I deleted the old log right before a reboot and both files were created

&nbsp;

> Could you please downgrade the nvidia drivers and check if it is working properly ? (just uninstall nvidia, and install nvidia470)

Right now I can't, due to #35408 

&nbsp;

> it seems to be loading the nouvaeu driver as well

I really never noticed that? Should I disable it or something like that?

**Comment by notthewave** [comment]
try again e35838cd50f2a6ac0ff7e7d8c136ecfef4f886ee apprently fixed this.

**Comment by Le0xFF** [comment]
Yeah I can confirm the issue is gone!
