### ISSUE TITLE
Docker environment to build and test new packages

### ISSUE THREAD

**Issue by erezgeva** [void-linux/void-packages#35410]
Hi,

I work on a new library.
And I wish to write a template for my new library and test in on a void Linux system.
That is to compile and package it.
My goal is to provide the template file so any user that wishes to package the new library, can use the template, for this propose.

My problem is that I can not manage to set such an environment.
In order to test and build I must compile the void-packages bootstrap.
This process take few hours and always fail on the GCC compilation.

Why wouldn't you provide a Docker image with the void-packages bootstrap already built. So we can simply write our package template file and test it.

Later other users and the void-Linux contributors can simply use it.

Thanks
  Erez

**Comment by Chocimier** [comment]
Use `binary-bootstrap`.

**Comment by erezgeva** [comment]
Links? Documents?

**Comment by Duncaen** [comment]
> Why wouldn't you provide a Docker image with the void-packages bootstrap already built. So we can simply write our package template file and test it.

We already provide a repository with the packages build.
By doing `./xbps-src binary-boostrap` instead of `./xbps-src bootstrap` you don't have to build anything.
https://github.com/void-linux/void-packages#quick-start

**Comment by erezgeva** [comment]
Thanks

**Comment by erezgeva** [comment]
You use namespaces and 'prctl - operations on a process or thread'
And you ask not to use 'root'.
All of this overhead make the build impossible to work in docker.
I understand why adding them, but make them mandatory make the task very hard to accomplish.
And I will not install a system that I can not check on Docker or Virtual machine first.
Nor will I recommend it.
Speed is important, but a distribution need to be flexible and work on different environments.
And no, building packages should be simple and **NOT** bump with
`ERROR unshare (Operation not permitted)`
And
`ERROR: prctl SECBIT_NOROOT (Operation not permitted)`

**Comment by Chocimier** [comment]
In VMs Void works perfectly fine. For using xbps-src in a foreign Linux distribution or in docker refer to documentation linked previously.

**Comment by erezgeva** [comment]
Look on the https://github.com/void-linux/void-packages#chroot-methods
- xbps-uunshare(1) (default)
- xbps-uchroot(1)
- bwrap(1) link to another site.
 
As for foreign, it is nice.
But I need to use container like docker.
The reason is that I can later use continuous integration on a GIT based server.
That create all relevant packages, for testing or for distribution.

However I can not create void using xbps-src.

xbps-src should works in a container same as dpkg-buildpackage, rpmbuild and archlinux makepkg.
No namespaces, no root user, no prctl, and no setgid.
And no third parties tools, please.

**Comment by Duncaen** [comment]
Its simply not how xbps-src works, the core idea is that builds happen in clean and reproducible environments and not on the host system.

If you really want to build packages using xbps-src in docker without allowing nested namespaces and uid maps, check how the github CI is setup, by creating temporary containers containing the build environment and invoke xbps-src in a way that it allows to use the container as build environment.
https://github.com/void-linux/void-packages/blob/master/.github/workflows/build.yaml

**Comment by erezgeva** [comment]
I do not want to build on the host system.
Docker container are the best clean and reproducible environments there is.
The link you send looks interesting.
It run
https://github.com/void-linux/void-packages/blob/master/common/travis/build.sh
It does not seems to have options to disable unshare or uchroot.
But looks like something in the environment is different.
Is it possible to use this Docker?

**Comment by Anachron** [comment]
Just create a script to prepare the build env inside the docker container on start. 

You can create a non-root user, clone void-packages and run binary-bootstrap. 

Then create /tmp/bootstrapped (or alike) so you know when its finished and run your builds inside.

(Of course, if you make a persistant container you gotta pull from remote origin). 

Maybe I'm missing the point here?

**Comment by erezgeva** [comment]
This is what I do.
Yet when I run 
`./xbps-src pkg`
I get errors on namespace.
I do not understand. Are there different xbps-src applications?
Is there a configuration that cause the xbps-src to use xbps-uunshare/xbps-uchroot or skip them.
Why don't their is a simple instructions / a docker container that I can use and build my package.
I yet do not receive an answerer.

**Comment by paper42** [comment]
> Yet when I run
> ./xbps-src pkg
> I get errors on namespace.

xbps-src creates a directory with a minimal void system, the state of this system is defined (more or less) by HEAD. The package is then built in this "container" which uses namespaces, so you can't run that nested inside another container without taking extra steps (if that's possible).
Alternatively, you can use the ethereal chroot style which uses symlinks to emulate a chroot without actually changing the root, but this destroys the container. For documentation on this, see common/chroot-style/ethereal.sh and the way CI is set up that was already linked before.

@Anachron missed the point of this issue, please ignore that comment

**Comment by Anachron** [comment]
Indeed I was confused but I get it now. The problem is we chroot to build cleanly, but this takes extra permissions inside the container. 

So maybe we could create another chroot-style which doesnt need it and doesnt destroy the container. I'll see what I can come up with.

**Comment by erezgeva** [comment]
Thanks.
Yes, Debian for example uses fakeroot,
The purpose is to create an archive with files with root permissions.

**Comment by Duncaen** [comment]
We removed fakeroot support because it was exceptionally broken and resulted in random build failures.

**Comment by Anachron** [comment]
> We removed fakeroot support because it was exceptionally broken and resulted in random build failures.

That was in 2014, no? https://github.com/void-linux/void-packages/commit/d75238b0d807302344f5ed7df2b9aa541cae3544

Or did we try `fakeroot` again after that but still had issues?

**Comment by bruceloco** [comment]
What about chroot?
I have a debian install on the target - chromebook arm64
create urandom nodes that map to debian /dev/urandom(otherwise git fails)
chroot into the void install
created a user which i added to the xbuilder group
./xbps-src bootstrap gives me

ERROR unshare (Operation not permitted)

I don't even know if this is an error or just some leftover hang from some irrelevant check

**Comment by classabbyamp** [comment]
see the readme, you can run xbps-src on debian directly, because the build environment is a chroot/container already:

> If `xbps-uunshare` does not work because of lack of `user_namespaces(7)` support, try other [chroot methods](https://github.com/void-linux/void-packages#chroot-methods).

https://github.com/void-linux/void-packages#foreign

**Comment by bruceloco** [comment]
> see the readme, you can run xbps-src on debian directly, because the build environment is a chroot/container already:
> 
> > If `xbps-uunshare` does not work because of lack of `user_namespaces(7)` support, try other [chroot methods](https://github.com/void-linux/void-packages#chroot-methods).
> 
> https://github.com/void-linux/void-packages#foreign

Yeah, i followed that, the CHROOT is now fine 
except now i get the prctl SECBIT_NOROOT (Operation not permitted)
example
./xpbs-src pkg linux6.2 
ERROR: prctl SECBIT_NOROOT (Operation not permitted)
