### ISSUE TITLE
Support for Nvidia OptiX in Blender 3.0

### ISSUE THREAD

**Issue by vanessa-vd98** [void-linux/void-packages#35456]
### System

* xuname:  
Void 5.15.19_1 x86_64 AuthenticAMD uptodate rrDFFF

* package:  
  *affected package(s) including the version*: blender-3.0.0_4

### Bug
There is no option for choosing the Nvidia Optix ray tracing engine in the build in Void's repo. Only CUDA is available. But in the same system, if I download the official build from blender.org, both CUDA and OptiX is available.

Before I updated, Blender 2.9 also had the option but it is not available in in the latest 3.0 version. A similar issue was reported to Blender's official bug tracker here: https://developer.blender.org/T93901

![no-optix](https://user-images.githubusercontent.com/99168064/152745330-609ae109-dde4-476f-b273-77f8fdf38612.png)

**Comment by notthewave** [comment]
the cuurent blender package in the repo has multiple issues. I would advise using the offical tar.gz's or the flatpak for now.
Here are some problems:
- opencolorio does not work (no filmic ACES etc)
- Eevee glitches (https://reddit.com/r/voidlinux/comments/shhsan/mesa_213e_glitchy_and_artifacts_in_blender3d_does/)
- no embree 
- outdated tbb openexr etc.
