### ISSUE TITLE
Package request: siggo (CLI client for Signal)

### ISSUE THREAD

**Issue by ElDifinitivo** [void-linux/void-packages#35461]
CLI client for Signal Messenger [https://github.com/derricw/siggo](https://github.com/derricw/siggo) as there isn't any available as of yet in the repos.

I'd contribute with a PR but it's dependent on `signal-cli`, and there already seems to be a PR to have it included [#13208](https://github.com/void-linux/void-packages/pull/13208). Also despite the README for `siggo` mentioning a dependency on `libmatthew-java`, it seems that from signal-cli-0.6.8 onward [it isn't required](https://github.com/void-linux/void-packages/pull/22223).

**Comment by Piraty** [comment]
siggo has halted development.
