### ISSUE TITLE
Firefox becomes unresponsive after a while

### ISSUE THREAD

**Issue by meator** [void-linux/void-packages#35460]
### System

* xuname:  *Void 5.15.19_1 x86_64 GenuineIntel uptodate rrrmdFFFFFFF*
* package:  *firefox-96.0.2_1*

### Expected behavior
Firefox working normally.
### Actual behavior
When I leave Firefox running for a while, everything stops working. I can't create or close tabs by clicking the buttons nor by using keyboard shortcuts, I can't open links, I can't use buttons, I can't edit the URL bar... Apart from that, everything else works normally. I can switch tabs, links I hover over get highlighted, I can even create and close tabs via right-clicking the tab bar... It's really weird.
### Steps to reproduce the behavior
I'm not aware of anything special on my system that could cause this. I have tried to run Firefox with all extentions disabled and the problem occurred again. I can reproduce this by using Firefox in general. If there are any log files or some information that could help diagnose the problem, I can post it here.

**Comment by ram02z** [comment]
I have this same issue actually. I thought it was a coincidence but it has happened to me quite a few times. If there is anything I can do to diagnose this issue, please let me know.

**Comment by cinerea0** [comment]
This is happening to me too, count me in if testing needs to be done.

**Comment by Vistaus** [comment]
Can't reproduce this.

But maybe one of you could test https://github.com/void-linux/void-packages/pull/35509 to see if it's fixed in that new version.

**Comment by ram02z** [comment]
> Do you all use Intel Hardware/Acceleration? It was reported to cause Problems in #35433 and after awhile it did for me too. Might be the/an issue, would be interesting your Hardware specs lined up

Nope I am using an AMD Ryzen CPU.

**Comment by wertz14** [comment]
I remember Firefox having this issue since the mid 2000s. It was criticized a lot by older users used to software that could run for years without issue because of this. A librewolf AppImage I'm running has the same behavior, so I don't think this is a packaging or void problem at all.

**Comment by Vistaus** [comment]
> > Can't reproduce this.
> > But maybe one of you could test #35509 to see if it's fixed in that new version.
> 
> Still the same issue unfortunately.

Strange. I too use a Ryzen and I can't reproduce this, not even on Firefox 96 or 98 for that matter.

**Comment by ram02z** [comment]
> > > Can't reproduce this.
> > > But maybe one of you could test #35509 to see if it's fixed in that new version.
> > 
> > Still the same issue unfortunately.
> 
> Strange. I too use a Ryzen and I can't reproduce this, not even on Firefox 96 or 98 for that matter.

Typically it occurs when I have lots of instances of Firefox open. Not an OOM issue though.

**Comment by zlice** [comment]
https://bugzilla.mozilla.org/buglist.cgi?quicksearch=freeze

https://bugzilla.mozilla.org/show_bug.cgi?id=1751121

They have had a slew of problems over the last few years, getting worse and worse. I'm on nightly 99, 95-97 were trash for me, constantly crashing and hanging w/o crash window or dbg output, UI glitches and freezes. Still getting some in 99 but...ever since the announcement of them not making money a while back it's been a bumpy ride. I really don't think it's Void/linux related. Windows users are reporting similar issues in some cases.

**Comment by Vistaus** [comment]
In that case, this issue can be closed as it indeed doesn't seem Void-related.

**Comment by meator** [comment]
I can also confirm that the issue is still occurring, even with *firefox-97.0_1*. I'm using Intel hardware. I find interesting that Firefox worked flawlessly before. Firefox doesn't crash, doesn't have any UI glitches... Apart from problems I described earlier, Firefox is working flawlessly.

It once happened when I only had one instance of Firefox open that had only three tabs open, which means that this issue doesn't occur only under heavy load (and I had only few terminals open and a irc client, so Firefox should have had enough system resources.).

It is very possible that this isn't Void's fault. I'll try to look at the Firefox bugzilla. https://bugzilla.mozilla.org/show_bug.cgi?id=1751121 says that it occurs under heavy loads, which means that this could be a different issue, but who knows?

**Comment by meator** [comment]
I have switched to firefox-esr because I require reliable internet browsing and everything is working so far.

**Comment by Vistaus** [comment]
> I have switched to firefox-esr because I require reliable internet browsing and everything is working so far.

According to earlier bug reports and testimonials, this issue has been present for years and thus should be present in Firefox ESR as well.

**Comment by jdnumm** [comment]
I can confirm that firefox-esr has the same behavior. Most time it occurs after wake up from sleep.

**Comment by meator** [comment]
> I can confirm that firefox-esr has the same behavior. Most time it occurs after wake up from sleep.

I have been using firefox-esr for a while now and the issue doesn't occur anymore. Are you sure this is the same issue?

**Comment by jdnumm** [comment]
> I have been using firefox-esr for a while now and the issue doesn't occur anymore. Are you sure this is the same issue?

Think so, have the problem one or two times a day. This morning I had a web call and keep browse in another window, then everything gets unusable slow.

**Comment by AviKav** [comment]
Does this occur with Mozilla's builds of FF?

**Comment by zlice** [comment]
FWIW - they may have someone looking into some related freezing finally. [1766136](https://bugzilla.mozilla.org/show_bug.cgi?id=1766136) & [1758561](https://bugzilla.mozilla.org/show_bug.cgi?id=1758561)

**Comment by zlice** [comment]
sharing this because it baffled me and there's still no reason of 'why'

an empty `~/.local/share/fonts` triggers font rebuilds that cause firefox to crap out, chug, and in some cases (bookmarks and context menus for me) crash

**Comment by biopsin** [comment]
On one of my mediastations with -esr Im combating this for a loong time and it still crash if I dont disable webgl.
- https://bugzilla.mozilla.org/show_bug.cgi?id=1726588
- https://bugzilla.mozilla.org/show_bug.cgi?id=1743505
