### ISSUE TITLE
Bluetooth not working in kernel 5.16.7

### ISSUE THREAD

**Issue by RicArch97** [void-linux/void-packages#35464]
### System

* xuname:  
  Void 5.16.7_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFFF
* package:  
  Linux 5.16.7_1

### Expected behavior
Bluetooth is able to register default controller

### Actual behavior
The following kernel errors in `dmesg`;
```
Bluetooth: hci0: Reading Intel version command failed (-110)
Bluetooth: hci0: command 0xfc05 tx timeout
```
running `bluetoothctl` with the `list` command shows no available controllers. 
I have the Gigabyte X570 Aorus Master motherboard, which I believe has Intel's AX200 chip for Wifi and Bluetooth.
Bluetooth wasn't a problem with previous kernels so pretty sure it's kernel related.

### Steps to reproduce the behavior
1. Boot kernel 5.16.7
2. Check `dmesg` or `bluetoothctl list`

**Comment by quentin-z80** [comment]
Same issue here on my Thinkpad P15s Gen2.

`[    3.876228] Bluetooth: Core ver 2.22
[    3.876236] NET: Registered PF_BLUETOOTH protocol family
[    3.876237] Bluetooth: HCI device and connection manager initialized
[    3.876239] Bluetooth: HCI socket layer initialized
[    3.876240] Bluetooth: L2CAP socket layer initialized
[    3.876242] Bluetooth: SCO socket layer initialized
[    4.138745] thinkpad_acpi: rfkill switch tpacpi_bluetooth_sw: radio is unblocked
[    5.403489] Bluetooth: hci0: Device revision is 0
[    5.403491] Bluetooth: hci0: Secure boot is enabled
[    5.403492] Bluetooth: hci0: OTP lock is enabled
[    5.403492] Bluetooth: hci0: API lock is enabled
[    5.403492] Bluetooth: hci0: Debug lock is disabled
[    5.403493] Bluetooth: hci0: Minimum firmware build 1 week 10 2014
[    5.403494] Bluetooth: hci0: Bootloader timestamp 2019.40 buildtype 1 build 38
[    5.404926] Bluetooth: hci0: Found device firmware: intel/ibt-0041-0041.sfi
[    5.404958] Bluetooth: hci0: Boot Address: 0x100800
[    5.404959] Bluetooth: hci0: Firmware Version: 134-39.21
[    6.686324] Bluetooth: hci0: Waiting for firmware download to complete
[    6.686474] Bluetooth: hci0: Firmware loaded in 1251509 usecs
[    6.686547] Bluetooth: hci0: Waiting for device to boot
[    6.713724] Bluetooth: hci0: Device booted in 26566 usecs
[    6.714176] Bluetooth: hci0: Found Intel DDC parameters: intel/ibt-0041-0041.ddc
[    6.716583] Bluetooth: hci0: Applying Intel DDC parameters completed
[    6.719597] Bluetooth: hci0: Firmware timestamp 2021.39 buildtype 1 build 31878
[    6.790500] Bluetooth: hci0: Failed to read codec capabilities (-56)
[    6.791502] Bluetooth: hci0: Failed to read codec capabilities (-56)
[    6.792499] Bluetooth: hci0: Failed to read codec capabilities (-56)
[    6.793499] Bluetooth: hci0: Failed to read codec capabilities (-56)
[    6.794500] Bluetooth: hci0: Failed to read codec capabilities (-56)
[    6.795489] Bluetooth: hci0: Failed to read codec capabilities (-56)
[   38.054019] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   38.054022] Bluetooth: BNEP filters: protocol multicast
[   38.054105] Bluetooth: BNEP socket layer initialized
`

**Comment by Vistaus** [comment]
No issue on my Minisforum HX90 with the 5.16.7 kernel. Bluetooth is working fine for me.

**Comment by RicArch97** [comment]
> Running an Intel 9560 without issues, gonna try on another machine with an AX210 real quick.

Tested it on my Thinkpad T470 just now in which I installed the AX210 as well, and have the same issue there. That one is running Arch Linux instead of Void Linux.

I guess we just have to wait for a fix in one of the next versions of this kernel

**Comment by oynqr** [comment]
That's weird. My AX210 works just fine, on a T450 with Void.

**Comment by Vistaus** [comment]
Sorry, forgot to mention it the other day, but I too have a AX200. No issues on 5.16.7 whatsoever.
