### ISSUE TITLE
request to update sfeed from 1.0 to 1.2

### ISSUE THREAD

**Issue by hiltjo** [void-linux/void-packages#35521]
Please update sfeed from 1.0 to 1.2. It has many improvements.
sfeed_curses is merged inside the sfeed repository and so the separate sfeed_curses package can be deprecated.

The current maintainer doesn't seem to respond by e-mail for whatever reason (1.1 request was ignored).

For maintainers, this feed can be useful to track releases:
https://git.codemadness.org/sfeed/tags.xml

Concept template for 1.2:

# Template file for 'sfeed'
pkgname=sfeed
version=1.2
revision=1
build_style=gnu-makefile
make_use_env=compliant
make_install_args="MANPREFIX=/usr/share/man"
makedepends="ncurses-devel"
depends="curl ncurses"
short_desc="RSS and Atom parser"
maintainer="someone"
license="ISC"
homepage="https://git.codemadness.org/sfeed"
distfiles="https://codemadness.org/releases/sfeed/sfeed-${version}.tar.gz"
checksum=7d3cdaf8dcc6582f6655330f82f8a57ca37c4b9c84ff995b09b7b7fb9fe58b58
conflicts="sfeed_curses"
provides="sfeed_curses-0.1_1"

post_install() {
        vlicense LICENSE
        vdoc README
}

**Comment by paper42** [comment]
> Don't request update of package. We have a script for that. https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt . However, a quality pull request may help.

`update-check` detects 1.2, so we know about this update. Please don't open issues to request package updates unless the old version is broken. We require updates to be tested on void and this template is wrong, a PR would allow us to properly review this. If someone converts this issue to a proper PR, we will review it and when all feedback is addressed, merge it. Let's use PRs for patches and issues for issues.
