### ISSUE TITLE
Package request: latexmk

### ISSUE THREAD

**Issue by timsofteng** [void-linux/void-packages#35626]
Tool for pdf compilation from tex.

https://github.com/gingerhot/latexmk

**Comment by dkwo** [comment]
I think we already have it, at least as part of texlive
```
$ xlocate latexmk
fish-shell-3.3.1_1      /usr/share/fish/completions/latexmk.fish
python3-Sphinx-4.2.0_1  /usr/lib/python3.10/site-packages/sphinx/texinputs/latexmkjarc_t
python3-Sphinx-4.2.0_1  /usr/lib/python3.10/site-packages/sphinx/texinputs/latexmkrc_t
texlive-20210325_2      /usr/bin/latexmk -> /usr/share/texmf-dist/scripts/latexmk/latexmk.pl
texlive-20210325_2      /usr/share/texmf-dist/scripts/latexmk/latexmk.pl
texlive-core-2021.58710_1       /usr/share/texmf-dist/scripts/arara/rules/arara-rule-latexmk.yaml
texlive-core-2021.58710_1       /usr/share/texmf-dist/scripts/make4ht/extensions/make4ht-ext-latexmk_build.lua
texlive-core-2021.58710_1       /usr/share/texmf-dist/tex/latex/asymptote/latexmkrc
texlive-core-2021.58710_1       /usr/share/texmf-dist/tlpkg/tlpobj/latexmk.tlpobj
```

**Comment by dkwo** [comment]
Agreeed. The correct project homepage is https://personal.psu.edu/~jcc8/software/latexmk/ though (version 4.76).

**Comment by dkwo** [comment]
What is the purpose of having this outside of texlive?

**Comment by timsofteng** [comment]
I personally need it for vimtex compiling:

https://github.com/lervag/vimtex#configuration

I use tectonic as backed but I guess it would be helpful to have latexmk as well. Correct me please if I'm wrong.

**Comment by dkwo** [comment]
Interesting, I was not aware of that.
Then having `latexmk` as separate pkg would make sense.

**Comment by timsofteng** [comment]
And maybe it would be nice to have some `tex` fonts in repo which supports cyrillic text...
Can't find...

**Comment by vutunganh** [comment]
Is this the issue you have in mind?

    https://github.com/lervag/vimtex/issues/2280

From what I'm reading, vimtex author (justifiably) does not want to integrate continuous compilation with tectonic, see these relevant comments https://github.com/lervag/vimtex/issues/2280#issuecomment-994005073, https://github.com/lervag/vimtex/issues/2280#issuecomment-994009179. The reason being that there is no way for vimtex to know the compilation status from the watch mode of tectonic.

**Comment by dkwo** [comment]
Yes, and you are right: at the moment is not a viable option to drop latexmk.
