### ISSUE TITLE
Building unbound fails

### ISSUE THREAD

**Issue by RossComputerGuy** [void-linux/void-packages#35672]
I tried this on my fork for ExpidusOS **and** a completely clean clone of this repository. I ran `./xbps-src -N -j32 -a aarch64 pkg base-system` and after a few hours, I was met with number 19 error in `xbps-src`. This happens while building unbound which is needed somewhere for GCC.
```
=> unbound-1.15.0_1: installing target dependencies: libevent-devel-2.1.12_2 expat-devel-2.4.4_1 libsodium-devel-1.0.18_1 ...
=> unbound-1.15.0_1: removing autodeps, please wait...
=> unbound-1.15.0_1: removing autocrossdeps, please wait...
=> ERROR: unbound-1.15.0_1: failed to install target dependencies! (error 19)
MISSING: libssp>=4.4.0_1
Transaction aborted due to unresolved dependencies.
=> ERROR: Please see above for the real error, exiting...
```

**Comment by Chocimier** [comment]
You should `bootstrap` before building base-system, did you?

Showing log with order of all packages build would help a lot to identify issue.

**Comment by RossComputerGuy** [comment]
Yes, I bootstrapped. The log is too long to scroll down but I know unbound is needed by GCC.

**Comment by RossComputerGuy** [comment]
[This is the output](https://pastebin.com/GprG1H2a).

**Comment by RossComputerGuy** [comment]
I ran the script I made to sync it yesterday.

**Comment by RossComputerGuy** [comment]
I tested this yesterday on a clean pull and both upstream and my fork are affected.

**Comment by Chocimier** [comment]
Can't find libspp in dep tree of unbound.

Please show output with tip of https://github.com/Chocimier/void-packages-org/commits/debug-xbps-install applied.

**Comment by Anachron** [comment]
You did modify this line two days ago though:

+		--enable-libssp \

That may be the culprit.

**Comment by Chocimier** [comment]
Reverting build style is not enough, you need to throw away all packages built since the change.

**Comment by RossComputerGuy** [comment]
I did rebuild everything after reverting it

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by RossComputerGuy** [comment]
That's the wrong GCC package. And that's how it is set up upstream.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by q66** [comment]
not a void bug, please don't report issues specific to your fork into void-packages

**Comment by RossComputerGuy** [comment]
I am using the same bootstrap I used to build x86_64.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by RossComputerGuy** [comment]
But this happens upstream

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Chocimier** [comment]
Then show us the error that happens without influence of your fork with debug info taken with what I posted above.
What you posted up to now is not an Void problem.

**Comment by RossComputerGuy** [comment]
https://pastebin.com/z4VSSB4V I just got off work and used the debug info and got these results.

**Comment by Anachron** [comment]
@RossComputerGuy like already said 3 times now... is the build directory and everything else clean?

Maybe clone the directory somewhere else and run another bootstrap from there and try to build again.

(Why is it so hard to debug this with you... you're barely helping)

**Comment by RossComputerGuy** [comment]
Yes, I cleaned **everything**.

**Comment by RossComputerGuy** [comment]
Recompiling it from scratch for the 3rd time with debug. Will have the results in about 2 hours.

**Comment by Anachron** [comment]
We're talking about a build based off void-linux/void-packages, right?

**Comment by RossComputerGuy** [comment]
Yes, with debug.

**Comment by RossComputerGuy** [comment]
> ```
> => libsodium-1.0.18_1: running pre-pkg hook: 03-rewrite-python-shebang ...
> => libsodium-1.0.18_1: running pre-pkg hook: 04-generate-runtime-deps ...
>    SONAME: libssp.so.0 <-> libssp>=4.4.0_1
>    SONAME: libpthread.so.0 <-> glibc>=2.32_1
>    SONAME: libc.so.6 <-> glibc>=2.32_1
> => libsodium-1.0.18_1: running pre-pkg hook: 05-prepare-32bit ...
> => libsodium-1.0.18_1: running pre-pkg hook: 06-shlib-provides ...
>    SONAME libsodium.so.23 from /usr/lib/libsodium.so.23.3.0
> => libsodium-1.0.18_1: running pre-pkg hook: 90-set-timestamps ...
> => libsodium-1.0.18_1: setting mtimes to Fri Feb 18 04:40:10 PM UTC 2022
> => libsodium-1.0.18_1: running pre-pkg hook: 99-pkglint-subpkgs ...
> => libsodium-1.0.18_1: running pre-pkg hook: 99-pkglint ...
> => libsodium-1.0.18_1: running pre-pkg hook: 999-collected-rdeps ...
>    libssp>=4.4.0_1 glibc>=2.32_1 
> => libsodium-devel-1.0.18_1: running do-pkg hook: 00-gen-pkg ...
> => Creating libsodium-devel-1.0.18_1.aarch64.xbps for repository /host/binpkgs/debug-xbps-install ...
> => libsodium-devel-1.0.18_1: running post-pkg hook: 00-register-pkg ...
> => libsodium-1.0.18_1: running do-pkg hook: 00-gen-pkg ...
> => Creating libsodium-1.0.18_1.aarch64.xbps for repository /host/binpkgs/debug-xbps-install ...
> => libsodium-1.0.18_1: running post-pkg hook: 00-register-pkg ...
> => Registering new packages to /host/binpkgs/debug-xbps-install
> index: added `libsodium-1.0.18_1' (aarch64).
> index: added `libsodium-devel-1.0.18_1' (aarch64).
> index: 96 packages registered.
> ```
I think this is the cause of the libssp error.

**Comment by Chocimier** [comment]
Okay, reproduced.

```sh
git worktree add ../libssp
cd ../libssp
echo XBPS_MAKEJOBS=$(( $(nproc) - 1 )) > etc/conf
./xbps-src binary-bootstrap
./xbps-src pkg libsodium -a aarch64 -N
```

```
=> libsodium-1.0.18_1: running pre-pkg hook: 04-generate-runtime-deps ...
   SONAME: libssp.so.0 <-> libssp>=4.4.0_1
   SONAME: libpthread.so.0 <-> glibc>=2.32_1
   SONAME: libc.so.6 <-> glibc>=2.32_1
```

**Comment by Xlaits** [comment]
Is there any word on this? This has been driving me bonkers for at least a week now.

**Comment by RossComputerGuy** [comment]
@Xlaits Same, I've tried several fixes. None of them worked so I had to submitted this issue.

**Comment by Xlaits** [comment]
I've been trying other methods while I have been waiting, as I am rather impatient. I'm getting close, but it's only because of outside toolchains and not actually having xbps-src working.

**Comment by Chocimier** [comment]
@paper42 suggested to add `--disable-ssp` to libsodium configure_args.
@RossComputerGuy, could you check if this solves your issue?

**Comment by Xlaits** [comment]
I can confirm that --disable-ssp did not fix my issues at least.

**Comment by Chocimier** [comment]
> I can confirm that --disable-ssp did not fix my issues at least.

Okay. Please remove your hostdir/binpkgs, build again and link here full build log.
