### ISSUE TITLE
Leap second data in tzdata ‘right’ timezones considered invalid by coreutils and Chrony

### ISSUE THREAD

**Issue by dpk** [void-linux/void-packages#35715]
### System

* xuname:  
Void 5.10.92_1 aarch64-musl Unknown uptodate rF
* package:  
tzdata-2021e_1
coreutils-8.32_4
chrony-4.2_1

### Expected behavior

```shell
$ TZ=right/UTC date -d 'Dec 31 2008 23:59:60'
Wed Dec 31 23:59:60 UTC 2008
```

(Test case from the chrony man page)

### Actual behavior

```
date: invalid date ‘Dec 31 2008 23:59:60’
```

This causes Chrony to reject the `leapsectz right/UTC` configuration directive, thus `CLOCK_TAI` on Void is always = UTC, at least when using Chrony. Presumably NTPd also doesn’t know where to get leap second data from, because there doesn’t seem to be any in Void.

The `/usr/share/zoneinfo/leapseconds` file I’ve seen on other systems is also missing, which could be related.

**Comment by dkwo** [comment]
We have
`install -m444 -t ${DESTDIR}/usr/share/zoneinfo iso3166.tab zone1970.tab zone.tab`
while e.g. Arch has
`install -m644 -t "${pkgdir}"/usr/share/zoneinfo iso3166.tab leap-seconds.list zone1970.tab zone.tab SECURITY # zone.tab is depricated and will go soon`
Have you tried building with the latter?

**Comment by dpk** [comment]
Hmm, curious. Indeed, sha1sum confirms the actual binary data files `/usr/share/zoneinfo/right/UTC` are identical on Arch and on Void, both with the 2021e release of the tz database. However, putting `leap-seconds.list` in place does not make a difference.

**Comment by dpk** [comment]
I’ve updated the report to reflect the actual symptoms, which seemingly don’t have the cause I thought they did

**Comment by dkwo** [comment]
the command you mention works fine in arch linux.
something seems wrong with the way we package tzdata and tzutils,
but I could not fix it yet (also, i do not see why we package them
separately.) see also the refs in gentoo's package, in particular
https://mm.icann.org/pipermail/tz/2015-February/022024.html

**Comment by paper42** [comment]
@sgn

**Comment by sgn** [comment]
This is not a bug of `tzutils` or `tzdata`.
It's different in implementation of libc.
On a glibc system:
```sh
$ TZ=right/UTC date -d 'Dec 31 2008 23:59:60'
Wed Dec 31 11:59:60 PM UTC 2008
```
