### ISSUE TITLE
[Package Request] wezterm

### ISSUE THREAD

**Issue by arun5309** [void-linux/void-packages#35721]
WezTerm is a GPU-accelerated cross-platform terminal emulator and multiplexer written by [@wez](https://github.com/wez/) and implemented in [Rust](https://www.rust-lang.org/).

https://wezfurlong.org/wezterm/index.html

**Comment by jbenden** [comment]
PR #36903 is pending approval and merge.

**Comment by eoli3n** [comment]
Great ! Thanks
