### ISSUE TITLE
[Package request] jc

### ISSUE THREAD

**Issue by paoloschi** [void-linux/void-packages#35804]
> jc JSONifies the output of many CLI tools and file-types for easier parsing in scripts.
> This allows further command-line processing of output with tools like jq or jello by piping commands...
> The jc parsers can also be used as python modules. In this case the output will be a python dictionary, or list of dictionaries, instead of JSON

https://github.com/kellyjonbrazil/jc

**Comment by abenson** [comment]
Closed in a743b68955d080ecb0741dca9c8234351fafcd99.

**Comment by paoloschi** [comment]
note that for parsing XML files, `jc` also depends on the `python3-xmltodict` package:

```
$ curl -s 'https://www.w3schools.com/xml/note.xml' | jc --xml
jc:  Error - Parser issue with xml:
             LibraryNotInstalled: The xmltodict library is not installed.
             If this is the correct parser, try setting the locale to C (LANG=C).
             For details use the -d or -dd option. Use "jc -h --xml" for help.
```

after installed `python3-xmltodict`:

```
$ curl -s 'https://www.w3schools.com/xml/note.xml' | jc --xml
{"note":{"to":"Tove","from":"Jani","heading":"Reminder","body":"Don't forget me this weekend!"}}
```

**Comment by abenson** [comment]
Sorry about that, it's been fixed.
