### ISSUE TITLE
Pkg request: SteamCMD

### ISSUE THREAD

**Issue by Barbaross93** [void-linux/void-packages#35812]
Just a request to include [SteamCMD](https://developer.valvesoftware.com/wiki/SteamCMD) , a command line version of the steam client. This would be highly beneficial for those running headless servers and for people with low end hardware who can't handle the normal client well.

**Comment by tibequadorian** [comment]
Is there an upstream release?

**Comment by tibequadorian** [comment]
It has no versioned release and probably doesn't meet the [Quality Requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements). It is easier to download it from the site you provided and just run the script.

**Comment by Barbaross93** [comment]
Ah, bummer :( I figured since a few other distros have packaged it, it should be within the realm of possibilities. I'll go ahead and close this then.
