### ISSUE TITLE
dnsmasq: disable dbus

### ISSUE THREAD

**Issue by zlice** [void-linux/void-packages#35826]
### System

* xuname:  Void 5.16.10 x86_64 AuthenticAMD notuptodate hold rrrmFFFFFFFFFFF
* package:  dnsmasq-2.86_1

### Expected behavior

dnsmasq without dbus installed should not have `--enable-dbus` in service

### Actual behavior

dnsmasq with `--enable-dbus` ends up filling memory over days/weeks with dbus errors (since it's not running)

### Steps to reproduce the behavior

default service runs with `exec dnsmasq -k --enable-dbus -u dnsmasq -g dnsmasq 2>&1` although `dbus` is not installed (over 500MB in a week)

### Comments

Sent e-mail to them. Not sure if there's a way to mod the template to dynamically remove `--enable-dbus` in the meantime. (probably is)

**Comment by biopsin** [comment]
Not in the template unless build own, but maybe add test for dbus in the run file..

**Comment by zlice** [comment]
like `exec dnsmasq -k $(if bs here then '--enable-dbus' ; else '' ; fi) -u dnsmasq -g dnsmasq 2>&1` ?

**Comment by zlice** [comment]
**run**
```
#!/bin/sh
mkdir -p /var/lib/misc
if [ -L /var/service/dbus ] ; then dbus='--enable-dbus' ; else dbus='' ; fi
exec dnsmasq -k $dbus -u dnsmasq -g dnsmasq 2>&1
```

**Comment by Duncaen** [comment]
We make services configurable like: 

```
#!/bin/sh
mkdir -p /var/lib/misc
[ -r ./conf ] && . ./conf
exec dnsmasq -k ${OPTS:---enable-dbus -u dnsmasq -g dnsmasq} 2>&1
```

The user can then create `/var/service/dnsmasq/conf` with i.e. `OPTS="-u dnsmasq -g dnsmasq"`.
