### ISSUE TITLE
bzlib.h (bzip2) not in repository

### ISSUE THREAD

**Issue by ZyxerZyxani** [void-linux/void-packages#35872]
Hello. I tried to build some package from git that requires bzip2 ( https://github.com/centricular/bzip2 ). I installed all the packages that could have it but to no avail.

**Comment by paper42** [comment]
The package is bzlib2-devel, -devel packages usually contain development files for building.
```
> xlocate bzlib.h
bzip2-devel-1.0.8_1	/usr/include/bzlib.h
```
