### ISSUE TITLE
sshd does not accept connections when running on a 32-bit host

### ISSUE THREAD

**Issue by amak79** [void-linux/void-packages#35913]
### System

* xuname:  
Void 5.10.92_1 armv7l Unknown uptodate rFFFF
* package:  
openssh-8.9p1_1

The client (amd64) outputs the following message when attempting a connection:
```
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
Connection reset by 192.168.0.8 port 22
```
The server (armv7l) will log the following:
```
[  750.684869] audit: type=1326 audit(1646192346.110:2): auid=4294967295 uid=99 gid=99 ses=4294967295 pid=557 comm="sshd" exe="/usr/bin/sshd" sig=31 arch=40000028 syscall=414 compat=0 ip=0x76bbcbd8 code=0x0
```
Applying the patch from the upstream bug and building openssh locally fixes the issue. Upstream bug: https://bugzilla.mindrot.org/show_bug.cgi?id=3396

**Comment by ZyxerZyxani** [comment]
If I recall correctly this was an issue in a somewhat recent update. It has been fixed in newer updates. 

Not sure where I found it but Debian had same issue, 32-bit server did not accept 64-bit client. It was fixed in a recent version. Maybe the repos need to update the sshd package?
