### ISSUE TITLE
Package request: Yabridge (Windows VST2 & VST3 bridge) 

### ISSUE THREAD

**Issue by 38github** [void-linux/void-packages#35926]
Since my Void Linux musl gets amazing latency under Pipewire I would love to use it some with my favourite Windows audio plugins but the (in my opinion) amazing Yabridge only provide a Ubuntu binary.

https://github.com/robbert-vdh/yabridge

The github page mentions these as necessary to build Yabridge:

To compile yabridge, you'll need [Meson](https://mesonbuild.com/index.html) and the following dependencies:

> GCC 10+[*](https://github.com/robbert-vdh/yabridge#building-ubuntu-18.04)
> A Wine installation with winegcc and the development headers. The latest commits contain a workaround for a winelib [compilation issue](https://bugs.winehq.org/show_bug.cgi?id=49138) with Wine 5.7+.
> Boost version 1.66 or higher[*](https://github.com/robbert-vdh/yabridge#building-ubuntu-18.04)
> libxcb
> The following dependencies are included in the repository as a Meson wrap:
>
> [bitsery](https://github.com/fraillt/bitsery)
> [function2](https://github.com/Naios/function2)
> [tomlplusplus](https://github.com/marzer/tomlplusplus)
>Version 3.7.3 of the [VST3 SDK](https://github.com/robbert-vdh/vst3sdk) with some [patches](https://github.com/robbert-vdh/yabridge/blob/master/tools/patch-vst3-sdk.sh) to allow Winelib compilation

**Comment by brihadeesh** [comment]
This appears to be somewhat straightforward - I'll take this up soon although I'm still not clear about handling subpackages and this has five of them. Would anyone happen to know if they will be handled by xbps-src/build scripts?

**Comment by ajtcode71** [comment]
Ive just finished the templates.. Im just testing and will submit PR shortly

**Comment by ajtcode71** [comment]
PR for yabridge and yabridgectl submitted.

**Comment by 38github** [comment]
> PR for yabridge and yabridgectl submitted.

You are my hero!
