### ISSUE TITLE
mesa/ libGL 18.2.2_2

### ISSUE THREAD

**Issue by jieppu** [void-linux/void-packages#3597]
### System

* xuname: Void 4.18.12_2 x86_64 GenuineIntel notuptodate rrDFFFFF
cpu i5
no GPU

* package: plasmashell  /  sddm  maybe more

### Expected behavior
a working sddm greeter
a normal desktop

### Actual behavior
sddm show white screen with full brightness
plasmashell try to start but it's only  white square on top right of 1/4 of the screen.
 and crash.

downgrade to18.2.2_1 fix it

### Steps to reproduce the behavior
upgrade  mesa-*-dri / libGL/ libGLES / mesalib / libgbm/ ...
up to 18.2.2_2

**Comment by maxice8** [comment]
Please be more specific on steps

**Comment by jieppu** [comment]
SORRY  was a false alert.
just a cache problem.
i remember last time you had to compile many time in a row those packages, i had the same issue.
