### ISSUE TITLE
Package request: pyright

### ISSUE THREAD

**Issue by camoz** [void-linux/void-packages#36003]
Pyright is a fast python language server and it's pretty popular these days.

Official website/repo: https://github.com/microsoft/pyright

> Q: What is the long-term plan for Pyright?
> 
> A: Pyright is an officially-supported Microsoft type checker for Python. It will continue to be developed and maintained as an open-source project under its original MIT license terms. The Pyright extension for VS Code is a reference implementation and is not guaranteed to be fully functional or maintained long-term.

The current only python LS packaged by voidlinux is unmaintained upstream (palantir), but there is an issue to package its replacement: https://github.com/void-linux/void-packages/issues/34192

**Comment by classabbyamp** [comment]
f201b29d26e0b591fbe2a81c36a9480a83c5670d
