### ISSUE TITLE
Separate nerdfonts package

### ISSUE THREAD

**Issue by timsofteng** [void-linux/void-packages#36024]
Hello. I'm using only one don't from nerdfonts package. Is it possible to separate this package to smaller ones to have ability to install fonts independently?

**Comment by Anachron** [comment]
Cant you just copy the one font file you use to the local fonts directory?

**Comment by paper42** [comment]
It would be nice to have nerd-fonts split to multiple smaller packages because the nerd-fonts-ttf is currently 1.6GB, but that would be 61 subpackages which I think is a bit too much. It would be a maintenance burden on updates because some fonts may be added and some dropped.
