### ISSUE TITLE
rust: cross build broken on armv*hf-musl

### ISSUE THREAD

**Issue by Gottox** [void-linux/void-packages#3605]
In the last few days we made huge steps forward to get a cross (and native non-x86) environment for rust.

@Cogitri, @jnbr, and I fixed all glibc platforms and aarch64 for both musl and glibc. The only platforms that remained broken are **armv6hf-musl** and **armv7hf-musl**.

The error occurs during cross building while linking rustc. It seems that libunwind is built with a wrong configuration. As noted in https://github.com/rust-lang/rust/blob/1.29.1/src/libunwind/libunwind.rs#L178, _Unwind_GetIP is implemented as a macro which is handled below the comment. As you can see in the buildlog, the linker complains about the missing function which indicates, that at https://github.com/rust-lang/rust/blob/1.29.1/src/libunwind/libunwind.rs#L96 the wrong branch is taken.

 https://gist.github.com/Gottox/ebb16c18150b5d6daec7c67daaacd4b4

**Comment by Cogitri** [comment]
Well, the easiest way to find out is removing the supposedly wrong branch, I guess :D 
https://gist.githubusercontent.com/Cogitri/3877c5ef3a08a8ad68a26a7b81d2df21/raw/b5fed95dbb0ccb2d970a12aefb906fb8f1f1461e/diff

Currently building with this - not that I actually want to use it, but it'd be good to know if it's actually caused by this.

**Comment by Gottox** [comment]
wouldn't that break the stage1 compiler?

**Comment by Cogitri** [comment]
Hm, I've reversed the logic of that function and it still returns the same error, I start doubting that the error actually comes from that...
https://gist.github.com/48ed2b3a37f3184aba866a3d2e1f7f98

**Comment by Duncaen** [comment]
I looked into it again but couldn't find a better explanation.
there is `backtrace-sys/libbacktrace`, but I think the files that actually use `_Unwind_GetIP{,Info}` are not actually used.

I don't have a machine to do test builds, so what I found was by looking at the sources.
Maybe a comparison between builds armv7 with glibc and musl would be interesting.

**Comment by jnbr** [comment]
Comparing the libstd-xxx.so files on glibc and musl shows that in both cases the correct branch is taken in `libunwind/libunwind.rs`. The problem is, that musl additionally links against `_unwind_GetIP` which comes from `unwind()` from `src/vendor/backtrace-sys/src/libbacktrace/backtrace.c`.

**Comment by Duncaen** [comment]
The difference is that default include path order is different in musl and glibc.
Musl builds use libunwinds `unwind.h` and glibc builds use the `unwind.h` file provided by gcc.

They both provide the same api/prototypes, except that `libgcc_s.so` does not provide some functions (`_Unwind_GetIP` being one of them) for arm and defines a macro instead.
This is not directly a problem for other architectures where `libgcc_s.so` provides all the defined functions but still a mess and I don't really know how to work around it.

There are a few possible solutions I can think of:
* Get rid of libunwind entirely if this would be possible.
* Rename the header in libunwind.
* Use `#include_next <unwind.h>` in libunwinds header, but this would still mean glibc and musl builds use different header files.

**Comment by jnbr** [comment]
libunwind wasn't used before rust-1.28. Re-adding some old patches should make it work without again. Waiting for the build to complete ...

**Comment by Duncaen** [comment]
Nice I got the same feedback from musls freenode channel and a patch https://github.com/smaeul/rust/commit/e3b90583112fd59255406f245db1856e0c21dab3

**Comment by jnbr** [comment]
we're currently building rust without `crt-static`, also `bootstrap/sanity.rs` errors out if there is no `libunwind.a`
