### ISSUE TITLE
rpc-virtqemud segfault

### ISSUE THREAD

**Issue by gilbertoferreira** [void-linux/void-packages#36061]
### System
voidlinux 
* xuname:  
 Void 5.16.11_1 x86_64 AuthenticAMD uptodate rrrmFFFFF

* package:  
libvirt-8.1.0_1
virt-manager-3.2.0_2

### Expected behavior
rename/delete vm from virt-manager panel
### Actual behavior
crash with:
Error deleting virtual machine 'NETHSERVER': erro interno: soquete de cliente está fechado

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1356, in delete
    self._backend.undefineFlags(flags)
  File "/usr/lib/python3.10/site-packages/libvirt.py", line 3219, in undefineFlags
    raise libvirtError('virDomainUndefineFlags() failed')
libvirt.libvirtError: Final do arquivo ao ler dados : Erro de entrada/saída

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/delete.py", line 190, in _async_delete
    self._delete_vm(vm)
  File "/usr/share/virt-manager/virtManager/delete.py", line 318, in _delete_vm
    vm.delete()
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1360, in delete
    self._backend.undefine()
  File "/usr/lib/python3.10/site-packages/libvirt.py", line 3182, in undefine
    raise libvirtError('virDomainUndefine() failed')
libvirt.libvirtError: erro interno: soquete de cliente está fechado

Adicionalmente, existem erros ao remover certos dispositivos de armazenamento: 

and 

rpc-virtqemud[2857]: segfault at 18 ip 00007f4dd0258cba sp 00007f4dd1b728e0 error 4 in libvirt_driver_qemu.so[7f4dd01d5000+113000]
[  221.763924] Code: a4 01 0f 84 78 03 00 00 4c 89 f7 e8 b0 e8 f7 ff 85 c0 0f 88 a8 02 00 00 48 8b 45 b8 48 8b b0 80 00 00 00 48 8b 86 b0 02 00 00 <48> 8b 78 18 48 85 ff 0f 84 41 01 00 00 e8 94 fd f7 ff 48 89 45 c0

### Steps to reproduce the behavior
Install virt-manager
Create a VM
Install SO in that created VM
Try to rename or delete the VM and you get the error!

**Comment by Francisco-Galindo** [comment]
I am having the same problem: #35996 
Downgrading `libvirt` to 8.0.0 seems to solve the problem, so it is version 8.1.0 at fault. Maybe it's got something to do with the way the new version is packaged? I haven't been able to try on another distribution, so I don't really know if that's the case.

**Comment by Johnnynator** [comment]
https://github.com/archlinux/svntogit-community/commit/8a1721c188eecbfb336eb349a5ec138283b9735a

Arch is importing a patch for most likely this issue. Putting this here as reference, either someone beats me to making a PR for this or I'll do it this evening.
