### ISSUE TITLE
podman: cmd/rootlessport and completions missing

### ISSUE THREAD

**Issue by lemmi** [void-linux/void-packages#36095]
For rootless networking to work, podman ships a new [`rootlessport`](https://github.com/containers/podman/tree/main/cmd/rootlessport) command.
Also completions aren't installed anymore.
@CameronNemo

**Comment by CameronNemo** [comment]
hmm I guess the rootlessport command is for requests going into the namespace? I definitely tested outgoing.

re: completions. eek. would appreciate some help there. they are generated by the binary...
