### ISSUE TITLE
Building fails on aarch64-musl: usbip

### ISSUE THREAD

**Issue by teldra** [void-linux/void-packages#361]
### System

* xuname:  
  Void 4.14.48_1 aarch64-musl  notuptodate rFF

* package:  
  usbip-4.16.2_1

### Expected behavior
Build successful.

### Actual behavior
Fails building:
> => usbip-4.16.2_1: installing target dependency 'slang-devel-2.3.2_2' ...                           
> => linux-tools-4.16.2_1: running pre-build hook: 02-script-wrapper ...                              
> => linux-tools-4.16.2_1: running do_build ...
> [...]
>   BUILD:   Doing 'make -j4' parallel build
>   SUBDIR   Documentation
>   XMLTO    perf-kallsyms.1
>   XMLTO    perf-inject.1
>   XMLTO    perf-mem.1
>   XMLTO    perf-record.1
> Assertion failed: !"sizeof lock obj" (posix-lock.c: get_lock_object: 118)
> /usr/bin/xmlto: line 613:  9330 Aborted                 "/usr/bin/xsltproc" --nonet --xinclude --param passivetex.extensions '1' -o "/tmp/xmlto.sFxF9Y/perf-kallsyms.proc" "/tmp/xmlto-xsl.9gXrjN" "/builddir/linux-4.16.2/tools/perf/Documentation/perf-kallsyms.xml"
> make[2]: *** [Makefile:272: perf-kallsyms.1] Error 134
> make[2]: *** Waiting for unfinished jobs....
> Assertion failed: !"sizeof lock obj" (posix-lock.c: get_lock_object: 118)
> /usr/bin/xmlto: line 613:  9333 Aborted                 "/usr/bin/xsltproc" --nonet --xinclude --param passivetex.extensions '1' -o "/tmp/xmlto.Pyg8Yx/perf-mem.proc" "/tmp/xmlto-xsl.beZw8s" "/builddir/linux-4.16.2/tools/perf/Documentation/perf-mem.xml"
> Assertion failed: !"sizeof lock obj" (posix-lock.c: get_lock_object: 118)
> /usr/bin/xmlto: line 613:  9329 Aborted                 "/usr/bin/xsltproc" --nonet --xinclude --param passivetex.extensions '1' -o "/tmp/xmlto.4WFPvV/perf-inject.proc" "/tmp/xmlto-xsl.qbAZ6e" "/builddir/linux-4.16.2/tools/perf/Documentation/perf-inject.xml"
> make[2]: *** [Makefile:272: perf-mem.1] Error 134
> make[2]: *** [Makefile:272: perf-inject.1] Error 134
> Assertion failed: !"sizeof lock obj" (posix-lock.c: get_lock_object: 118)
> /usr/bin/xmlto: line 613:  9331 Aborted                 "/usr/bin/xsltproc" --nonet --xinclude --param passivetex.extensions '1' -o "/tmp/xmlto.2XMpFo/perf-record.proc" "/tmp/xmlto-xsl.E06OMd" "/builddir/linux-4.16.2/tools/perf/Documentation/perf-record.xml"
> make[2]: *** [Makefile:272: perf-record.1] Error 134
> make[1]: *** [Makefile.perf:704: man] Error 2
> make: *** [Makefile:110: man] Error 2
> => ERROR: linux-tools-4.16.2_1: do_build: 'make ${makejobs} CC=$CC LD=$LD CFLAGS="$CFLAGS" EXTRA_CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" WERROR=0 DESTDIR=${DESTDIR} prefix=/usr lib=lib/perf NO_GTK2=1 NO_SDT=1 PERF_VERSION=${version}_${revision} all man' exited with 2
> => ERROR:   in do_build() at srcpkgs/linux-tools/template:39

### Steps to reproduce the behavior
./xbps-src pkg usbip (on aarch64)

**Comment by mvf** [comment]
The problem is that `libgpg-error` binaries are broken on `aarch64-musl` (and also on `aarch64`) due to a compile-time issue during cross builds (only). See voidlinux/void-packages#14281

**Comment by teldra** [comment]
Thank you. That solves the problem for me.
