### ISSUE TITLE
package request python3-smbus

### ISSUE THREAD

**Issue by numerys** [void-linux/void-packages#36156]
### System

RPi 4 CM + CM4 IO board

```Void 5.10.92_1 aarch64 Unknown notuptodate rF```

### Expected behavior

```xbps-install -Su python3-smbus```

### Actual behavior

```Package 'python3-smbus' not found in repository pool.```

### Steps to reproduce the behavior

```xbps-install -Su python3-smbus```

**Comment by 0x5c** [comment]
I have a PR in the works for that, see https://github.com/void-linux/void-packages/pull/36304
