### ISSUE TITLE
`loginctl suspend` doesn't work properly on rootless Xorg.

### ISSUE THREAD

**Issue by aintyourcat** [void-linux/void-packages#36183]
### System

* xuname:  
  Void 5.15.26_1 x86_64 AuthenticAMD notuptodate rFFF
* package:  
  xorg-server-21.1.3_3

### Expected behavior
Laptop goes to sleep immediately when `loginctl suspend` issued & wake up properly when triggered (e.g a key on the keyboard pressed).

### Actual behavior
Laptop still awake for about 30 seconds with a blank screen before goes to sleep, moreover it kills Xorg when woken up.

Services status: [global_services.txt](https://github.com/void-linux/void-packages/files/8280891/global_services.txt),  [user_services.txt](https://github.com/void-linux/void-packages/files/8280892/user_services.txt)
Xorg's log: [Xorg.0.log](https://github.com/void-linux/void-packages/files/8280895/Xorg.0.log)
xinitrc: [xinitrc.txt](https://github.com/void-linux/void-packages/files/8280910/xinitrc.txt)

Notes:
1. The laptop is not even goes to sleep when I'm using this xinitrc: https://github.com/aintyourcat/dotfiles/blob/8e17830e68d1a45e367bf0af14d18835b03321c1/x/.config/X11/xinitrc#L19 (The only difference with the previous one is on the specified line).
2. `loginctl suspend` works fine on xorg-server installed from the repo, which requires the "needs_root_rights" key set to "yes" in /etc/X11/Xwrapper.config, however when I accidentaly run the same command with the same Xwrapper.config on the manually compiled xorg-server (which makes it's running as root) the issue is persist.
3. Similar issue i found: https://libredd.it/r/voidlinux/comments/nndnja/xorg_with_elogind_support_breaks_suspend_to_ram/.
4. My current workaround is to not run `loginctl suspend` but `zzz` and config elogind to ignore ACPI events like explained in: https://docs.voidlinux.org/config/power-management.html#elogind 

### Steps to reproduce the behavior
1. Install xorg-server with the elogind build option enabled via `xbps-src`.
6. Verify it: `xbps-query -p build-options xorg-server`.
7. Make sure that:
   - The "needs_root_rights" key equals to "no" in /etc/X11/Xwrapper.config.
   - The dbus & elogind services is running.
8. Start Xorg, in my case via `startx`.
9. Make sure the user which Xorg is running as isn't root: `ps -o user $(pgrep Xorg)`.
10. Run `loginctl suspend`.

**Comment by deepaknegilachu** [comment]
it also crashing sway on laptop while lid's events 
and seatd working perfectly fine
