### ISSUE TITLE
Package request: rust-nightly

### ISSUE THREAD

**Issue by Animeshz** [void-linux/void-packages#36197]
Its useful to have it so to build packages depending on it in future. I don't know its viable or not, if not please close the issue.

I was just planning to package up [eww](https://github.com/elkowar/eww) (gtk widget system).

**Comment by TinfoilSubmarine** [comment]
You can use rustup for this to make your own templates for your own use, but I don't think any packages built with an unstable rust will be accepted.

**Comment by q66** [comment]
sorry, no
