### ISSUE TITLE
Pull Request template text typo between [skip CI] and [ci skip]

### ISSUE THREAD

**Issue by jdnumm** [void-linux/void-packages#36263]
The Pull Request template text says [skip CI] but I think it should be [ci skip] (like in the documentation)
```

<!-- Note: If the build is likely to take more than 2 hours, please [skip CI](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#continuous-integration)
and test at least one native build and, if supported, at least one cross build.
Ignore this section if this PR is not skipping CI.
-->
```

**Comment by paper42** [comment]
Using `[ci skip]` even in a comment might cause every PR to skip CI. `[skip CI](https://...)` is a markdown syntax for links and has nothing to do with `[ci skip]`.

**Comment by tibequadorian** [comment]
Maybe we could write "please skip CI as described in https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#continuous-integration" to avoid confusion?

**Comment by tibequadorian** [comment]
I think this can be closed then.
