### ISSUE TITLE
Firefox window does not have an icon since firefox 98

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#36294]
### System

* xuname:  
  *Void 5.16.11_1 x86_64 GenuineIntel uptodate rFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF*
* package:  
  *``firefox-98.0_1``*

### Expected behavior
When I click on the firefox icon on the dock, a firefox window opens, has the correct icon and I get a dot under the firefox icon on the dock which indicates that firefox is open.

### Actual behavior
When I click on the firefox icon on the dock, a firefox window opens, has the default icon and I **don't** get a dot under the firefox icon on the dock.
![image](https://user-images.githubusercontent.com/23639164/159674899-8a7b00bf-6a67-47bc-8372-81138bc36619.png)

This worked before b1265c886f263e8508c18389c011cfc757bd09c8 - firefox 98.0.
I tried using a .desktop file from arch, but it didn't help.

### Steps to reproduce the behavior
* install GNOME or probably any other (wayland?) DE
* install firefox
* start firefox

cc @Duncaen

**Comment by hervyqa** [comment]
in kde (x11) panel the same thing happened.

![Screenshot_20220324_065705](https://user-images.githubusercontent.com/45872139/159815533-aea46afa-6a95-4eae-ac1a-ba105bba818e.png)

**Comment by oreo639** [comment]
Seems to be a similar issue to this:
https://www.reddit.com/r/gnome/comments/twhsqi/comment/i3fsvll/?utm_source=share&utm_medium=web2x&context=3

As mentioned there, you should be able to work around this by adding `StartupWMClass=firefox-default` to `firefox.desktop` and that works for me. Not sure if this is the correct fix?

**Comment by paper42** [comment]
![image](https://user-images.githubusercontent.com/23639164/162281298-f35c18e2-f57b-4aa5-a710-3a56f40f3a7e.png)

Hmm, while it is better, it's not completely solved. The old icon has a name Firefox Web Browser, the new one is Firefox, so I had to re-add the shortcut. That said, I think it would be more confusing to change wm_name again, so I am closing this.
