### ISSUE TITLE
Can not cross compile for armv5tel due to libssp cyclical dependancy

### ISSUE THREAD

**Issue by Xlaits** [void-linux/void-packages#36355]
### System

* xuname:  
Void 5.15.26_1 x86_64 AuthenticAMD uptodate rrrrmmnFFFFFFF
* package:  
  unbound > libssp

### Expected behavior
package build and cross compile for armv5tel
### Actual behavior
=> ERROR: unbound-1.15.0_1: failed to install target dependencies! (error 19)
MISSING: libssp>=4.4.0_1
Transaction aborted due to unresolved dependencies.
=> ERROR: Please see above for the real error, exiting...
### Steps to reproduce the behavior
./xbps-src -j4 -a armv5tel -N pkg base-system

**Comment by Chocimier** [comment]
That's same as #35672.

**Comment by Xlaits** [comment]
> That's same as #35672.

Ahh, that doesn't come up in any searches for some reason.
