### ISSUE TITLE
[Package request] wlroots-eglstreams

### ISSUE THREAD

**Issue by ilovecringe** [void-linux/void-packages#36373]
NVIDIA users can only use sway with the wlroots-eglstreams (fork of wlroots). In Arch Linux it is in the AUR, in Void Linux it is not. Please add it, at least until the NVIDIA drivers work correctly with sway
https://github.com/git-bruh/wlroots-eglstreams

**Comment by wael444** [comment]
for this i suggest you have a look at the already existing wlroots template and just modify it

**Comment by paper42** [comment]
This is a fork of an existing project which we don't generally accept especially when it's a library like this. nvidia495+ should support the GBM backend, so this shouldn't be necessary.
