### ISSUE TITLE
[RFC]: multiple entries in $changelog

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#36387]
Some projects have two sources for $changelog - one from the master/main branch for rcs, alphas, betas and first releases in a series and one from a maintenance branch for patch releases. This is mostly visible in GNOME projects, but other projects also use this strategy.

Sometimes the maintenance branch doesn't exist until it's needed which means that if we decide to use the maintenance branch for the changelog, it will be a 404 link until they create the branch (#36353).

This can be solved with allowing multiple entries in the $changelog field.

**Comment by classabbyamp** [comment]
would this require a change in xbps?

**Comment by classabbyamp** [comment]
it actually works out of the box already I think, I did it [here](https://github.com/void-linux/void-packages/pull/39519/files#diff-11fc585109075e469edb63113f3894a59934d9926c4f2d5242f616f0dc65327dR15-R16) having completely forgotten about this issue

**Comment by paper42** [comment]
I don't think this is a good idea to have two changelogs, one for the maintenance branch and one for master anymore. I can easily just comment out the one that doesn't apply for that release. Having both would mean users would have to figure out which one contains the changelog for the current version.
