### ISSUE TITLE
wireplumber: request for bundling runit service with the package

### ISSUE THREAD

**Issue by Animeshz** [void-linux/void-packages#36393]
The pipewire and derivatives provides runit services for various replacements, a runit wireplumber service will be beneficial to integrate with the pipewire better.

Currently even if we put it on something like .xinitrc, as soon as pipewire is restarted or so, it gets disconnected and hence exits, so needs manual run to get it working again, which sometimes is just irritating. A service manager is responsible for automatically restarting the service if it exits and let one service depend on other services easily.

**Comment by gbrlsnchs** [comment]
> +1 for this issue, I had to get wire plumber running and it was a royal pain. Pipewire worked as a service, but wire plumber was unhappy unless everything was run as my user. If someone were able to write a good service (and ideally add a pipewire section to the handbook detailing how all of this and desktop portal worked together) it would be a dream.

I couldn't make `wireplumber` work (while `pipewire-media-session` works flawlessly), but maybe I can help with the desktop portal you mentioned, in case you're using `xdg-desktop-portal-wlr`.

Basically you only need to install it and make sure you import the correct variables to the dbus session. I've got this in my WM's init script:
```
dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
```
Here both `WAYLAND_DISPLAY` and `XDG_CURRENT_DESKTOP` are previously set to something that makes sense Wayland-wise.

**Comment by subnut** [comment]
Added in https://github.com/void-linux/void-packages/commit/9f50345e006a3620a6142ffce4023229f8d42d7c

**Comment by antaxiom** [comment]
I got wireplumber working without needing to add any dbus variables (though
this would've been good to know), but I did have to start the script
through my DE (I'm currently using gnome and therefore
xdg-desktop-portal-gtk, but I tried on wlr compositors as well) as opposed
to running it as a service. I actually had to run pipewire and desktop
portal through the script as well to get them all playing nicely. I'll keep
this in mind if I do ever have to set this up again, but hopefully a
service will make this irrelevant.

**Comment by ahesford** [comment]
As noted at https://docs.voidlinux.org/config/media/pipewire.html and in the service scripts themselves, we do not recommend the pipewire (or, now, wireplumber) system services for regular use. However, if you know why you need the system services and what you're doing with them, have at it. These three system services work as expected for me.
