### ISSUE TITLE
Package request: OctoPrint

### ISSUE THREAD

**Issue by teldra** [void-linux/void-packages#364]
https://github.com/foosel/OctoPrint

**Comment by Johnnynator** [comment]
I did Create a [template]( https://gist.github.com/Johnnynator/092f1399074955b4e87bf5bd79c017cd) for OctoPrint. But we are missing a lot of dependencies in the repo atm.
```
# missing python3-PyYAML>=3.10,<3.11
# missing python3-Flask-Principal>=0.3.5,<0.4
# missing python3-sarge==0.1.4
# missing python3-pylru>=1.0.9,<1.1
# missing python3-pkginfo>=1.2.1,<1.3
# missing python3-semantic_version>=2.4.2,<2.5
# missing python3-awesome-slugify>=1.6.5,<1.7
# missing python3-chainmap>=1.0.2,<1.1
# missing python3-scandir>=1.3,<1.4
# missing python3-futures>=3.1.1,<3.2
# missing python3-emoji>=0.4.5,<0.5
# missing python3-monotonic>=1.3,<1.4
# missing python3-frozendict>=1.2,<1.3
```

**Comment by ndowens** [comment]
> I did Create a [template](https://gist.github.com/Johnnynator/092f1399074955b4e87bf5bd79c017cd) for OctoPrint. But we are missing a lot of dependencies in the repo atm.
> Missing dependencies:
> 
> - [ ] python3-PyYAML>=3.10,<3.11
> - [ ] python3-Flask-Principal>=0.3.5,<0.4
> - [ ] python3-sarge==0.1.4
> - [ ] python3-pylru>=1.0.9,<1.1
> - [ ] python3-pkginfo>=1.2.1,<1.3
> - [ ] python3-semantic_version>=2.4.2,<2.5
> - [ ] python3-awesome-slugify>=1.6.5,<1.7
> - [ ] python3-chainmap>=1.0.2,<1.1
> - [ ] python3-scandir>=1.3,<1.4
> - [ ] python3-futures>=3.1.1,<3.2
> - [ ] python3-emoji>=0.4.5,<0.5
> - [ ] python3-monotonic>=1.3,<1.4 #422
> - [ ] python3-frozendict>=1.2,<1.3 #432
> 
> OctoPrint still depends on python2 and void-linux doesn't want to include any new python2 only packages.
> I can continue working on this once a python3 compatible version is released

Looks like it supports it now

**Comment by teldra** [comment]
I close this issue, because there are too many needed libs with specific version numbers.
