### ISSUE TITLE
Inconsistent Firefox binary naming

### ISSUE THREAD

**Issue by rivanfebrian123** [void-linux/void-packages#36404]
### System

* xuname: Void 5.15.30_1 x86_64 GenuineIntel notuptodate rrmFFFFFFFFFFFF
* package: firefox-98.0_1

### Expected behavior
The binary name should be like the previous one (it's either `firefox` or `firefox-bin` AFAIK)

### Actual behavior
It just suddently changed it's name to `firefox-default`

### Steps to reproduce the behavior
Update your Firefox (or system as a whole)

**Comment by Duncaen** [comment]
I don't see a binary named `firefox-default`.

**Comment by wael444** [comment]
i think what they mean is that WM_CLASS for firefox has now become 
```
WM_CLASS(STRING) = "Navigator", "firefox-default"
```

**Comment by paper42** [comment]
This probably causes #36294

**Comment by rivanfebrian123** [comment]
@Duncaen sorry, haven't check that.

I guess we need some patches. Another dirty fix with `sed`, maybe?

**Comment by wael444** [comment]
> @Duncaen sorry, haven't check that.
> 
> I guess we need some patches. Another dirty fix with `sed`, maybe?

```
~ $ xbps-query -f firefox | grep bin
/usr/bin/firefox-wayland
/usr/bin/firefox -> /usr/lib/firefox/firefox
/usr/lib/firefox/firefox-bin -> /usr/lib/firefox/firefox
```

**Comment by paper42** [comment]
5a91e8625aa189a87904ac97c6f98441ee3fd4aa and see #36294

**Comment by rivanfebrian123** [comment]
Thank you so much, @Duncaen!
