### ISSUE TITLE
Package request: kio-fuse

### ISSUE THREAD

**Issue by QuadPiece** [void-linux/void-packages#36431]
Repo: [kio-fuse](https://github.com/KDE/kio-fuse)

kio-fuse provides fuse compatibility for kio. Without this package non-KDE applications generally cannot access remote files via tings like the dolphin manager.

For example if you use the dolphin file manager to access a server over sftp and then attempt to play a video file with mpv, it will fail if kio-fuse is not available.

**Comment by classabbyamp** [comment]
duplicate of #34071
