### ISSUE TITLE
[Package request] Electron 17+

### ISSUE THREAD

**Issue by atk** [void-linux/void-packages#36451]
Homepage: https://electronjs.org/ / https://github.com/electron/electron
Description: Runtime for desktop applications written in node/chromium
License: MIT

This request is for an updated version of electron; currently we're at 13, but more recent versions of vscode and other apps require a newer version.

**Comment by RicArch97** [comment]
To add to this, updating to at least Electron 17.3.1 would allow to make use of the Wayland Ozone backend in VS Code according to https://github.com/microsoft/vscode/issues/146349. The Wayland backend in Chromium 98 is very usable so that would be a big plus for Electron apps that can make use of Electron 17.3.1 or higher.

**Comment by cevdetardaharan** [comment]
We have to update electron 13 to electron 17+ because code-oss is not running under wayland.

**Comment by JamiKettunen** [comment]
Here's what I previously tried to come up with for `electron18`, someone feel free to continue work based on this: [electron18.tar.gz](https://github.com/void-linux/void-packages/files/8550350/electron18.tar.gz)

All the patches were modified (didn't apply anymore), updated (e.g. all chromium patches against `srcpkgs/chromium`) and dropped (if already applied upstream) as needed.

My system doesn't have nearly enough resources for me to keep working on that quickly enough as even extraction takes about 5 minutes each time and then I'd essentially have to wait for chromium to build and fix any and all issues that may arise during that. Besides I already have plenty of other projects which I'd rather work on than build chromium over and over again ;)

**Comment by JamiKettunen** [comment]
https://github.com/microsoft/vscode/commit/678d130 (`chore: update to electron 18`) is now merged, we can only expect further breakages on older versions of Electron starting with VS Code 1.69.0 release due next month (July).

**Comment by atk** [comment]
It already seems to break the terminal, but since we don't have a newer electron version, I cannot confirm that fixes it.
