### ISSUE TITLE
onedrive client is out-of-date and needs to be updated

### ISSUE THREAD

**Issue by abraunegg** [void-linux/void-packages#36515]
### System
N/A

### Expected behavior
onedrive package = 2.4.16

### Actual behavior
onedrive package = 2.4.13

### Steps to reproduce the behavior
N/A

**Comment by paper42** [comment]
> Don't request update of package. We have a script for that. https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt . However, a quality pull request may help.

**Comment by kalocsaibotond** [comment]
I know I am little late, but I made the PR:
https://github.com/void-linux/void-packages/pull/62156 .
