### ISSUE TITLE
Request: Enable --with-native-compilation compilation flag in emacs

### ISSUE THREAD

**Issue by dimethyltriptamine** [void-linux/void-packages#36543]
Emacs introdouced native lisp compilation in 28.1. However with the Void package you can't use this feature as it is not enabled: 

![1649237640](https://user-images.githubusercontent.com/53711069/161947252-d24d78fc-6794-475e-b407-a05f4d62adf6.png)

### System

* xuname:  Void 5.15.32_1 x86_64 GenuineIntel uptodate rrmFF

* package:  emacs-common-28.1_1

### Expected behavior

Emacs should compile the lisp code to native code.

### Actual behavior
It says that emacs wasn't compiled with `--with-native-compilation`

### Steps to reproduce the behavior

Open any elisp file in emacs and run `M-x emacs-lisp-native-compile-and-load`

**Comment by governorgoat** [comment]
Depends on libgccjit being packaged, which is being tracked in https://github.com/void-linux/void-packages/pull/28785
