### ISSUE TITLE
Cronie 1.6 Regression: Weekday Ranges 1-5 not working anymore

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#36554]
The 1.6.0 update https://github.com/void-linux/void-packages/commit/2a09b7589ed31f72d9f96d1524ace401851d2967
has a regression https://github.com/cronie-crond/cronie/commit/62e53f1cdb9c1e12a01ee7814c92cd937d50328d
that should be backported.

Else, entries like these are not possible anymore:

```
*/5   *   * * 1-5 <SOME_COMMAND>
```

**Comment by paper42** [comment]
cc @governorgoat @leahneukirchen
