### ISSUE TITLE
runit: Remove zsh completions

### ISSUE THREAD

**Issue by foopub** [void-linux/void-packages#36593]
The file https://github.com/void-linux/void-packages/blob/master/srcpkgs/runit/files/_sv seems unnecessary as better completions are provided by the default https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_runit (which seems to have been created only a few months after in 2014... weird no one has noticed until now)

**Comment by foopub** [comment]
https://github.com/void-linux/void-packages/pull/28790
https://github.com/void-linux/runit/pull/15
also seem relevant, but the template does seem to use the version provided in the files here:
```
	vinstall ${FILESDIR}/_sv 644 usr/share/zsh/site-functions
```

Any point opening the same issue in the void runit repo?

**Comment by RunningDroid** [comment]
Sorry for bumping a stale issue, but I wanted to point out that (after https://github.com/void-linux/runit/pull/15 is merged) neither completion is better than the other (IMO.)
The completion from zsh-users has prettier prompts, but it doesn't ignore `$SVDIR` when using `sudo`\*.
The completion that we (will) ship with runit (that we apparently have 2 copies of) ignores `$SVDIR` when using `sudo`\*, but it has relatively minimalist prompts.
The good news is that the licenses between the two completions [appears to be](https://en.wikipedia.org/wiki/License_compatibility#/media/File:Floss-license-slide-image.svg) compatible, runit is licensed BSD-3-CLAUSE & the zsh-users completion appears to be licensed MIT, so we (aka void-linux/runit) can copy the fancy prompts but I don't think they can copy the `sudo`\* detection without re-licensing their completions.

\*:and `su -c`, and `doas`

**Comment by leahneukirchen** [comment]
+1 for removing our completion.
