### ISSUE TITLE
libfprint0: Seems like it replaces libfprint package, and xbps-remove fails to remove either of package once installed libfprint0.

### ISSUE THREAD

**Issue by Animeshz** [void-linux/void-packages#36629]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)* `Void 5.16.18_1 x86_64 GenuineIntel uptodate rFFFFFFFF`
* package:  
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

```
libfprint-1.94.0_1
libfprint0-1.0_2
```

### Expected behavior & Actual behavior

`xbps-query -O` should not display libfprint as automatically installed orphan packages, it should rather display libfprint0 as it. `xbps-remove` should not assume libfprint is replaced by libfprint0.

```
  ~ >>> xbps-query -O
libfprint-1.94.0_1

  ~ >>> sudo xbps-remove -Ro
fprintd-1.94.0_1: broken, unresolvable shlib `libfprint-2.so.2'
Transaction aborted due to unresolved shlibs.

  ~ >>> sudo xbps-remove -R libfprint0
libfprint0-1.0_2 in transaction breaks installed pkg `fprintd-1.94.0_1'
Transaction aborted due to unresolved dependencies.
```

### Steps to reproduce the behavior
With nice running system with fprintd/libfprint, install libfprint0.

**Comment by wael444** [comment]
i cannot seem to see that `libfprint` is on the orphan packages list for me.

```
ephemera ~ $ xbps-query -p state libfprint
installed
ephemera ~ $ xbps-query -p state fprintd
installed
ephemera ~ $ xbps-query -p state libfprint0 
installed
ephemera ~ $ xbps-query -O
ephemera ~ $
```

however,
```
# xbps-remove -R libfprint0
libfprint0-1.0_2 in transaction breaks installed pkg `fprintd-1.94.0_1'
Transaction aborted due to unresolved dependencies.
```
