### ISSUE TITLE
profanity crashes st when I press alt+right too many times.

### ISSUE THREAD

**Issue by jgarte** [void-linux/void-packages#36637]
profanity xmpp client crashes st terminal when I press alt+right too many times.

How should I debug this?

**Comment by wael444** [comment]
you look at st's stderr.

 >  alt+right
 
 i assume this resizes the st window.
in that case i am unable to reproduce. works for me.

**Comment by jgarte** [comment]
@wael444 wae how did you install st and profanity?

> you look at st's stderr.

how do I do that?

**Comment by wael444** [comment]
from another terminal you can launch
`st 2>&1 > log`
after st crashes there would be a file called `log`.
Paste its contents here.

**Comment by jgarte** [comment]
@wael444 

```
 λ st -o st-log
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  5951
  Current serial number in output stream:  6050
```

**Comment by jgarte** [comment]
Thanks for clarifying that
