### ISSUE TITLE
base-files-0.142_11: /run must not be a directory

### ISSUE THREAD

**Issue by sakhmatd** [void-linux/void-packages#36634]
### System

* xuname:  
```
Void 5.13.19_1 x86_64 GenuineIntel notuptodate rrrmFFFFF
```
* package:  
```
base-files-0.142_11
```

### Expected behavior
Should install as normal.

### Actual behavior
Displays the following output before exiting:
```
Name       Action    Version           New version            Download size
base-files update    0.142_11          0.142_12               -

Size required on disk:         239KB
Space available on disk:        81GB

Do you want to continue? [Y/n] y

[*] Verifying package integrity
base-files-0.142_12: verifying RSA signature...

[*] Collecting package files
base-files-0.142_12: collecting files...
base-files-0.142_11: collecting files...

[*] Unpacking packages
base-files-0.142_11: updating to 0.142_12 ...
base-files-0.142_12: unpacking ...
Creating system directories/symlinks...
/run must not be a directory, exiting!
ERROR: base-files-0.142_12: [unpack] INSTALL script failed to execute pre ACTION: Operation not permitted
ERROR: base-files-0.142_12: [unpack] failed to unpack files from archive: Operation not permitted
Transaction failed! see above for errors.
```

### Steps to reproduce the behavior
`xbps-install -f base-files` or `xbps-install -Suv`. 
Currently prevents me from a full upgrade.

Due to /run being needed by runit and various daemons, I can't temporarily remove/move the folder to see if it helps the package install (Device or resource busy on attempt).
Here are the current contents of /run:
```
agetty.reload  blkid     cups  docker     lock  lvm    runit  sshd.pid  udev  utmp
avahi-daemon   bluealsa  dbus  initramfs  log   mount  samba  sudo      user  xtables.lock
```

**Comment by Duncaen** [comment]
The error message is wrong, its about `/var/run` which should be a symlink and not a directory. It does not automatically delete /var/run to replace it since that would require recursively deleting files in it, which we can't really do, it contains user data and deleting that automatically at runtime might be bad.
So deleting /var/run and replacing it with a symlink to `../run` would be the solution to it.

**Comment by sakhmatd** [comment]
That indeed helps, thanks! 

However, the error message is indeed very misleading and probably should be changed.
