### ISSUE TITLE
Opening an upload form in firefox crashes dwm

### ISSUE THREAD

**Issue by jgarte** [void-linux/void-packages#36636]
Opening an upload form in firefox crashes dwm.

How should I debug this?

It doesn't happen with qt and qtbrowser.

**Comment by RicArch97** [comment]
This sounds like an issue with DWM rather than Firefox.

**Comment by wael444** [comment]
> Opening an upload form in firefox crashes dwm.

doesn't happen for me. 

> How should I debug this?

try having a look at Xorg logs or dwm stderr.

**Comment by wael444** [comment]
Close this one as well. I suggest you go to to r/suckless subreddit and report this issue there.
As this doesn't relate to void packages either.

And if it is that Firefox crashes, try another WM or DE.
if it crashes there then there is something wrong with your system or Firefox. Its likely your system.

**Comment by tibequadorian** [comment]
Don't open issues to ask for help @jgarte. We have a subreddit and an IRC for that.

**Comment by zlice** [comment]
sharing this because it baffled me and there's still no reason of 'why'

an empty ~/.local/share/fonts triggers font rebuilds that cause firefox to crap out, chug, and in some cases (bookmarks and context menus for me) crash

**Comment by wael444** [comment]
cant reproduce your issue
