### ISSUE TITLE
musl-legacy-compat not needed by rpm

### ISSUE THREAD

**Issue by ismaell** [void-linux/void-packages#36668]
The include of `<error.h>` is superfluous. See https://github.com/rpm-software-management/rpm/commit/d8eee23e1f2d944a9bcef5044d43808ba21bb83a.

https://github.com/void-linux/void-packages/blob/8850c6af5594ba93e2e811000cc1dcdd6bb5f5e8/srcpkgs/rpm/template#L29-L31

**Comment by Chocimier** [comment]
Thanks for working with upstream. Change in Void will need to wait for new tagged release of rpm.

**Comment by Chocimier** [comment]
Patch was accepted to 4.18 branch but not 4.17, let's keep waiting.
