### ISSUE TITLE
Kodi Crash - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#36688]
### System

* xuname:  
Void 5.15.32_1 x86_64 GenuineIntel uptodate rrrrrmmdnFFFFFFF

* package:  
kodi-19.4_1

### Expected behavior
Play media content normally

### Actual behavior
Crashes with below error:

libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib64/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva info: va_openDriver() returns 0
Segmentation fault (core dumped)

### Steps to reproduce the behavior
Enter any installed Addonn of Kodi

Flatpak Kodi works with the below output on the same system:
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/r600_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/r600_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/GL/lib/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_12
libva info: va_openDriver() returns 0

**Comment by wael444** [comment]
when playing a video, it works i think.
```
ephemera ~ $ xbps-query -p pkgver kodi
kodi-19.4_1
ephemera ~ $ kodi
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib64/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
```
i played a video through the Movies tab.

**Comment by anarchomoh** [comment]
Hi Wael

Yes, drivers are all installed and Kodi works when I run the Flatpak version. Must be a drivers issue though because yours is a Nvidia card and works normally.  Mine is a ATI Radeon card.

**Comment by Anachron** [comment]
I receive this message as well but no crash.

Can you maybe `strace` kodi?

**Comment by anarchomoh** [comment]
Thanks Anachron, attached
[strace.txt](https://github.com/void-linux/void-packages/files/8637474/strace.txt)
