### ISSUE TITLE
Request: package nnn with gitstatus

### ISSUE THREAD

**Issue by ElDifinitivo** [void-linux/void-packages#36693]
### System

* xuname: `Void 5.15.32_1 x86_64 AuthenticAMD uptodate rrmFFFFFFFFFFFFF`
* package: `nnn-4.4_1`

Specifically with this diff: [https://github.com/jarun/nnn/blob/master/patches/gitstatus/mainline.diff](https://github.com/jarun/nnn/blob/master/patches/gitstatus/mainline.diff).

It becomes incredibly useful in vim/nvim when using an nnn plugin as a file-picker as a replacement for nerdtree to see the git status for project files. It adds a `-G` flag to `nnn` to enable git status symbols. An example of how it looks can be seen [here](https://github.com/luukvbaal/nnn.nvim#git-status).

**Comment by paper42** [comment]
> A [patch framework](https://github.com/jarun/nnn/tree/master/patches) hosts sizable user-submitted patches which are subjective in nature.

I don't think it's a good idea to make the void nnn package use a user submitted patch in the default build.

**Comment by tibequadorian** [comment]
> I don't think it's a good idea to make the void nnn package use a user submitted patch in the default build.

Agree with that. However I think it would be okay to add a build option in the template that enables this patch as it is done in our [dmenu template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/dmenu/template) already.

**Comment by Duncaen** [comment]
No the build option is a bad idea, if someone wants to maintain their own patched builds they can simply drop their patches into the patches directory, some package mantainer deciding that they should add patches for their usecase as build option is the wrong approach and belongs into their own fork/package.

**Comment by tibequadorian** [comment]
Does that mean we should drop the fuzzymatch patch in dmenu?
