### ISSUE TITLE
request: 3 packages to fix hardcoded icons

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#36727]
https://github.com/Foggalong/hardcode-fixer a bash script, depends on `curl` and `sudo`
https://github.com/BlueManCZ/SIF a python script for steam games, depends on `xdotool`, `python3-gobject`, `python3-vdf` and `python3-requests`
https://github.com/bilelmoussaoui/Hardcode-Tray needs packaging dependencies

*didn't expect ctrl+space to create issue instead of going to next line*

**Comment by Duncaen** [comment]
1. is a backdoor

2 and 3 should be opened as separate issues.

**Comment by mhmdanas** [comment]
@Duncaen sorry if it's obvious, but where's the backdoor? I didn't find anything in the issue tracker that mentions any such backdoor.
