### ISSUE TITLE
zlib: Fetch error when building

### ISSUE THREAD

**Issue by vutunganh** [void-linux/void-packages#36720]
### System

* xuname: `Void 5.15.34_1 x86_64-musl GenuineIntel uptodate rrnFFF`
* package: `zlib-1.2.12_2`

### Expected behavior

zlib builds successfully.

### Actual behavior

```
$ ./xbps-src pkg zlib
=> xbps-src: updating repositories for host (x86_64-musl)...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/x86_64-musl-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/nonfree/x86_64-musl-repodata' ...
[*] Updating repository `https://alpha.de.repo.voidlinux.org/current/musl/debug/x86_64-musl-repodata' ...
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> zlib-1.2.11_4: removing autodeps, please wait...
=> zlib-1.2.11_4: building [configure] for x86_64-musl...
   [runtime] zlib-1.2.11_4: not found (self, ignored)
=> zlib-1.2.11_4: running do-fetch hook: 00-distfiles ...
=> zlib-1.2.11_4: fetching distfile 'zlib-1.2.11.tar.gz'...
http://www.zlib.net/zlib-1.2.11.tar.gz: Not Found
=> ERROR: zlib-1.2.11_4: failed to fetch zlib-1.2.11.tar.gz.

```

### Steps to reproduce the behavior

Try building zlib.

`./xbps-src pkg zlib`

### Fix

I discovered that the reason this fails is that the homepage requires https. I provide a fix in [this PR](https://github.com/void-linux/void-packages/pull/36719).

**Comment by oreo639** [comment]
The reason is because you are trying to build zlib in an outdated repo.
The version that is currently packaged is `1.2.12` but the one you are trying to build `1.2.11`. The latter release was removed from the website.
You can do `git pull https://github.com/void-linux/void-packages/` to update the repo.

**Comment by vutunganh** [comment]
Oh, you are right. Somehow I missed this. Thanks.
