### ISSUE TITLE
tlmgr not working in texlive

### ISSUE THREAD

**Issue by tornaria** [void-linux/void-packages#36738]
Reported by @Eloitor in #36452.
```
$ tlmgr
Can't locate TeXLive/TLConfig.pm in @INC (you may need to install the TeXLive::TLConfig module) (@INC contains: /texmf-dist/scripts/texlive /tlpkg /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/share/texmf-dist/scripts/texlive/tlmgr.pl line 60.
BEGIN failed--compilation aborted at /usr/share/texmf-dist/scripts/texlive/tlmgr.pl line 60.
```

This seems to be caused by a change to `tlmgr.patch` in 7184064103c7812856e9bd1ba5eaa6d697d01331, namely `$Master` is used (in a `BEGIN` block) before it's set.

CC: @fosslinux

**Comment by Eloitor** [comment]
I can try to fix this.
The value of master should be set to  "/usr/share/texmf-dist"  here, right? https://github.com/void-linux/void-packages/blob/7184064103c7812856e9bd1ba5eaa6d697d01331/srcpkgs/texlive/patches/tlmgr.patch#L59

**Comment by nsajko** [comment]
This seems like it may be related to the tlmgr issues described here: https://wiki.archlinux.org/title/TeX_Live
