### ISSUE TITLE
blender doesn't have GMP compiled in

### ISSUE THREAD

**Issue by chriscamacho** [void-linux/void-packages#36751]
blender-3.0.0_4

### Expected behavior
able to do things like CSG without the mesh getting messed up (using "exact" CSG solver) This makes blender significantly less useful for practical modeling.

### Actual behavior
can only CSG with the fast solver (often resulting in broken meshes)

### Steps to reproduce the behavior
do a CSG operation between two meshes, ensure the "exact" button is pressed and take note of the warning

**Comment by Idesmi** [comment]
It should suffice to add `-DWITH_GMP=ON` to configure_args, and `gmp-devel` to makedepends.

**Comment by oreo639** [comment]
> It should suffice to add `-DWITH_GMP=ON` to configure_args, and `gmp-devel` to makedepends.

WITH_GMP is ON by default.
Also, `ldd /usr/bin/blender`:
```
...
	libtasn1.so.6 => /usr/lib/libtasn1.so.6 (0x00007f069ed45000)
	libnettle.so.8 => /usr/lib/libnettle.so.8 (0x00007f069ecfd000)
	libhogweed.so.6 => /usr/lib/libhogweed.so.6 (0x00007f069ecb4000)
	libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f069ec37000)
	libpostproc.so.55 => /usr/lib/libpostproc.so.55 (0x00007f069ec15000)
	libavresample.so.4 => /usr/lib/libavresample.so.4 (0x00007f069ebf4000)
	libbs2b.so.0 => /usr/lib/libbs2b.so.0 (0x00007f069ebec000)
...

```

**Comment by Idesmi** [comment]
ldd recursively lists dependencies of libraries.

The package that contains the headers for GMP, instead, isn't automatically pulled by anything. I hold a bare understanding of it all myself, anyway.

I compiled successfully with GMP support on x86_64-glibc, `makedepends+="gmp-devel gmpxx-devel"`.

**Comment by oreo639** [comment]
> ldd recursively lists dependencies of libraries.
> 
> The package that contains the headers for GMP, instead, isn't automatically pulled by anything. I hold a bare understanding of it all myself, anyway.
> 
> I compiled successfully with GMP support on x86_64-glibc, `makedepends+="gmp-devel gmpxx-devel"`.

Ah. Thanks.

**Comment by oreo639** [comment]
Bump as issue isn't resolved yet.

**Comment by chriscamacho** [comment]
meant to get here sooner, this is now fixed - thanks guys...
