### ISSUE TITLE
kde: wrong search path in kcmshell5

### ISSUE THREAD

**Issue by dezifit** [void-linux/void-packages#36778]
### System
* xuname:  
 Void 5.16.20_1 x86_64 AuthenticAMD

* package:  
 kde-cli-tools-5.24.3_1

### Expected behavior
`kcmshell5 kcm_pulseaudio` should open a working instance of the audio device test

### Actual behavior
kf.coreaddons: "Could not load plugin from kcm_pulseaudio: The shared library was not found."

/usr/lib/qt5/plugins/kcms/kcm_pulseaudio.so isn't in the search path, see attached excerpt of kcmshell started with `strace`.

### Steps to reproduce the behavior
* start kcmshell5 in console
* try to test audio output

### Additional information
Even if kcm_pulseaudio is linked to the correct path, it fails to play any test sound. [Reported upstream](https://bugs.kde.org/show_bug.cgi?id=451995), closed as downstream issue.

**Comment by dezifit** [comment]
@Johnnynator
Is the audio device test working for you? There are other users having the same issue, see this [post](https://teddit.net/r/voidlinux/comments/vgbvad/systemsettings5_kcm_pulseaudio_could_not_load/) on reddit. If my description is confusing or relevant data is missing, please let me know.

**Comment by Johnnynator** [comment]
Can you retest with updated plasma? I do not remember ever having this problem myself.

**Comment by dezifit** [comment]
Still happens with latest Plasma (5.25.3) and KDE (5.96.0). Only difference is the new error message (as adverticed by Ismael Asensio from upstream).
