### ISSUE TITLE
qt5: regression - undefined symbol gst_gl_display_wayland_new_with_display

### ISSUE THREAD

**Issue by dezifit** [void-linux/void-packages#36780]
### System

* xuname:  
Void 5.16.20_1 x86_64 AuthenticAMD
* package:  
qt5-multimedia-5.15.3+20220222_1
gst-plugins-good1-qt5-1.20.1_1

### Expected behavior
Working multimedia player in QT5/QML

### Actual behavior
no service found for - "org.qt-project.qt.mediaplayer"

Starting with `QT_DEBUG_PLUGINS=1` shows:
Cannot load library /usr/lib/qt5/plugins/mediaservice/libgstmediaplayer.so: (/usr/lib/qt5/plugins/mediaservice/../../../libQt5MultimediaGstTools.so.5: undefined symbol: gst_gl_display_wayland_new_with_display)
QLibraryPrivate::loadPlugin failed on "/usr/lib/qt5/plugins/mediaservice/libgstmediaplayer.so" : "Cannot load library /usr/lib/qt5/plugins/mediaservice/libgstmediaplayer.so: (/usr/lib/qt5/plugins/mediaservice/../../../libQt5MultimediaGstTools.so.5: undefined symbol: gst_gl_display_wayland_new_with_display)"

### Steps to reproduce the behavior
Try to play a video from QML, for example with minimal code from [qmlbook](https://qmlbook.github.io/ch12-multimedia/multimedia.html) 

### Additional information
Last update of `gstreamer1` (from `1.18.5_2` to `1.20.1_1`) causes undefined symbols in `qt5-multimedia`, same QML code worked before without issues.

**Comment by paper42** [comment]
> ### Steps to reproduce the behavior
> 
> Try to play a video from QML, for example with minimal code from [qmlbook](https://qmlbook.github.io/ch12-multimedia/multimedia.html)

Can we reproduce this issue on a package in void repositories?

**Comment by dezifit** [comment]
Sort of. `qt5-declarative` contains `qml`, a interpreter for qml files. Save the following code to a file `play.qml`:
```
import QtQuick 2.4
import QtMultimedia 5.0    

VideoOutput {
   anchors.fill: parent
   fillMode: VideoOutput.PreserveAspectFit
   source: player

   MediaPlayer {
       id: player
       autoPlay: true
       onStatusChanged: {if (status==MediaPlayer.EndOfMedia) play();}
	source: "video.mp4"
   }
}
```
Adjust the source or copy a video to the same directory and start with: `qml play.qml`.
I'm using QtMultimedia to display a video in the sddm login screen, but this requires a sddm theme.

**Comment by Johnnynator** [comment]
a31e7d0c9cf780b4cb3964162263e1578fb521b4

**Comment by q66** [comment]
This was wrong, the correct fix was to rebuild gst-plugins-base with wayland winsys enabled, qt5 should have never been rebuilt. I bumped it again
