### ISSUE TITLE
libgdal - Please update package and enable python bind

### ISSUE THREAD

**Issue by gabriel-russo** [void-linux/void-packages#36816]
## Update
Please, update package libgdal and subpackages from 3.0.4 (released in 2020-01-28) to 3.4.2 (current release)

## Feature
According to [Pypi GDAL page](https://pypi.org/project/GDAL/#building-as-part-of-the-gdal-library-source-tree) you can also have the GDAL Python bindings built as part of a source build by specifying `--with-python` as part of your configure line. 

If it's possible, make a Configure option to enable python bindings build in libgdal package.

## Python bind in libgdal-3.0.4 template

` # Template file for 'libgdal'`
...
`configure_args=" ... --with-python"`
`makedepends="... python-devel python-setuptools"`
`python_version=2`
...
For some reason i can't put it working with python3, any future success i will report it here.

**Comment by Chocimier** [comment]
Worked on at https://github.com/void-linux/void-packages/pull/31687 .

**Comment by gabriel-russo** [comment]
> Worked on at #31687 .

[commit a1a7df1acd39dcb4cf66846864c1b5294ec8b2d0](https://github.com/void-linux/void-packages/pull/31687/commits/a1a7df1acd39dcb4cf66846864c1b5294ec8b2d0) from @ar-jan works like a charm, why not replace libgdal from master branch with his version?

**Comment by classabbyamp** [comment]
> why not replace libgdal from master branch with his version?

that will happen once the PR is ready to be merged, looks like there are still a few issues to solve first.

**Comment by ar-jan** [comment]
Issue #31687 is stuck on libgdal cross compile no longer working. I'm afraid I don't know how to fix it and I haven't been able to get help. Cross compile did work in the PR earlier, but something somewhere in Void's build process seems to have changed because the same versions that used to compile no longer get built.

**Comment by sgn** [comment]
On 2022-07-27 02:52:37-0700, Arjan ***@***.***> wrote:
> Issue #31687 is stuck on libgdal cross compile no longer working.
> I'm afraid I don't know how to fix it and I haven't been able to get
> help. Cross compile did work in the PR earlier, but something
> somewhere in Void's build process seems to have changed because the
> same versions that used to compile no longer get built.

I will look into it.

-- 
Danh

**Comment by kruceter** [comment]
libgdal has been updated via #40225.

Python binding have also been added.
