### ISSUE TITLE
Package request: gamescope

### ISSUE THREAD

**Issue by 0-st** [void-linux/void-packages#36869]
https://github.com/Plagman/gamescope
Replaces steamos-compositor

**Comment by TeddyDD** [comment]
I tried, but I gave up. 

[diff.txt](https://github.com/void-linux/void-packages/files/9003858/diff.txt)

Fails on this error ¯\\\_(ツ)\_/¯
```


../subprojects/libliftoff/test/libdrm_mock.c:117:6: error: variable 'ret' set but not used [-Werror=unused-but-set-variable]
  117 |  int ret;
      |      ^~~
cc1: all warnings being treated as errors
```

**Comment by classabbyamp** [comment]
> cc1: all warnings being treated as errors
looks like they have `-Werror` set somewhere in their build cripts

**Comment by birb7** [comment]
lol, i might just be one of the first to get it to work on void. i just needed to addend "-devel" to a lot of the meson build dependencies ("libseat-devel", "libXdamage-devel", etc.) worked flawlessly and still figuring out tweaks for the best balance between upscaling.

**Comment by TeddyDD** [comment]
I managed to create draft template for gamescope: https://github.com/TeddyDD/void-packages-1/tree/add-gamescope

**Comment by KF-Art** [comment]
> I tried, but I gave up.
> 
> [diff.txt](https://github.com/void-linux/void-packages/files/9003858/diff.txt)
> 
> Fails on this error ¯\_(ツ)_/¯
> 
> ```
> 
> 
> ../subprojects/libliftoff/test/libdrm_mock.c:117:6: error: variable 'ret' set but not used [-Werror=unused-but-set-variable]
>   117 |  int ret;
>       |      ^~~
> cc1: all warnings being treated as errors
> ```

Using ` -Wno-unused-but-set-variable` to `libliftoff` `meson.build` seems to correct it. I made a patch for that.

```
diff -ruN a/meson.build b/meson.build
--- a/meson.build	2023-03-05 12:36:15.000000000 -0600
+++ b/meson.build	2023-03-09 21:04:10.598647298 -0600
@@ -23,6 +23,7 @@
 
 	'-Wno-missing-braces',
 	'-Wno-unused-parameter',
+    '-Wno-unused-but-set-variable',
 ]), language: 'c')
 
 liftoff_inc = include_directories('include')
```

**Comment by HadetTheUndying** [comment]
> I managed to create draft template for gamescope: https://github.com/TeddyDD/void-packages-1/tree/add-gamescope

Sorry to necro this issue but did you decide this wasn't worth maintaining? I noticed you never opened a PR, I'm wondering if there's any issues you ran into before i give it a go?

**Comment by jaminW55** [comment]
What is the status of this package?

**Comment by mdkcore0** [comment]
can we close this issue, since https://github.com/void-linux/void-packages/pull/48354 was merged?
