### ISSUE TITLE
How to handle broken sources

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#36895]
I was asking myself if we should run a script periodically (like check-updates) that checks if the source is still available?

**Comment by Anachron** [comment]
Should we maybe create a script that automatically catches missing sources and notifies us?

@q66 @leahneukirchen @ahesford @abenson

**Comment by Anachron** [comment]
Seems like a local issue with my `ISP` or `VPS` provider. I will investigate further.

Problem stands: How do we handle gone sources?

**Comment by leahneukirchen** [comment]
Loads fine here, and virtual hosting is nothing new either.

We have copies of old tarballs on https://sources.voidlinux.org/openbox-3.6.1/ and else use Debian as a fallback.

Ideally they'd add the tarballs to the releases of course.

**Comment by Anachron** [comment]
Yeah I figured it's on my end, read my third reply. I'm still debugging. 

Nonetheless, I think a script to watch for broken links cannot hurt in the future.

**Comment by 4ricci** [comment]
> Nonetheless, I think a script to watch for broken links cannot hurt in the future.

It shouldn't be too hard. Something like this will verify the hashes too (but also download a lot of stuff):
```sh
rm -rf hostdir/sources
for i in $(find srcpkgs -name template | cut -d / -f 2); do
        ./xbps-src -I fetch "$i" >/dev/null 2>&1 || echo "$i: broken distfiles"
done
```

This one will just check if the the server returns a successfull status code:
```bash
for pkg in $(find srcpkgs -name template | cut -d / -f 2); do
        unset homepage changelog distfiles
        source srcpkgs/"$pkg"/template 2>/dev/null
        for i in $homepage $changelog $distfiles; do
                if ! curl --silent --location --head --fail -o /dev/null "$i"; then
                        echo "$pkg: url $i is broken"
                fi
        done
done
```
