### ISSUE TITLE
Firefox sndio tips are hard to find

### ISSUE THREAD

**Issue by Vaelatern** [void-linux/void-packages#369]
I just updated to FF 60, and my audio broke. I feel like we should have a single list of settings needed to make sound work on FF.

So here is the list! I know I'm missing things. Please comment to add.

```
media.cubeb.backend       sndio

```

**Comment by maxice8** [comment]
from the wiki https://wiki.voidlinux.eu/Sndio#Using_Firefox_with_Sndio.5B1.5D

```
security.sandbox.content.read_path_whitelist /home/<username>/.aucat_cookie
security.sandbox.content.write_path_whitelist /home/<username>/.aucat_cookie
```

**Comment by Duncaen** [comment]
```
media.cubeb.sandbox;false
```

Since 60.

**Comment by maxice8** [comment]
Should this be added to docs.voidlinux.org ?

**Comment by maxice8** [comment]
Closing as it is now on docs.voidlinux.org, and will be added there in the future
