### ISSUE TITLE
libcurl-7.83.0_1 signature not found

### ISSUE THREAD

**Issue by solutionroute** [void-linux/void-packages#36906]
xbps-src is failing to build any package; also failing to initialize a new void-packages clone.

### Expected behavior

xbps-src should a) build packages and/or b) binary-bootstrap initialize  a fresh void-packages clone

### Actual behavior

ERROR: [trans] failed to download `libcurl-7.83.0_1' signature from `https://repo-us.voidlinux.org/current': Not Found
Transaction failed! see above for errors.
=> ERROR: xbps-src: failed to install base-chroot!

### Steps to reproduce the behavior

Affecting repo-us and alpha repos, I did not check the others; assuming the same.

**Comment by TheEgghead27** [comment]
This issue seems to also apply to non-build `xbps-install` updates/installs of cURL too, seems to be linked to commit [`aa2c2db`](https://github.com/void-linux/void-packages/commit/aa2c2db45c304b05f37433ebef4511f38189c25d).

**Comment by classabbyamp** [comment]
There were some issues within the void infra earlier, should be fixed now

**Comment by paper42** [comment]
This should be fixed now
