### ISSUE TITLE
Chromium 101.0.4951.41 displays a transparent 1 pixel bar at the top

### ISSUE THREAD

**Issue by sug0** [void-linux/void-packages#36980]
### System

* xuname:  `Void 5.15.36_1 x86_64 AuthenticAMD uptodate hold rrrmFFFFFFFFFF`
* package:  `chromium-101.0.4951.41_1`

### Expected behavior

The X windows below chromium (including the root window) should not be displayed when chromium is focused and in view.

### Actual behavior

A completely transparent 1 pixel high bar is displayed across the top of the chromium window, right after the toolbar. Check the picture below (I made the background of `about:blank` black, so it is more apparent).

### Steps to reproduce the behavior

This behavior is present in any usage of `chromium-101.0.4951.41_1`.

---

![](https://pomf2.lain.la/f/820cbr.png)

**Comment by RicArch97** [comment]
Might be your theme? Everything looks fine for me

**Comment by dmarto** [comment]
Can't reproduce. Can you try with default chrome settings?
![2022-05-05_16-59](https://user-images.githubusercontent.com/1244744/166940136-03c3c09b-fbea-46d8-a0fe-c551fc1012bd.png)

**Comment by sug0** [comment]
@dmarto The `classic` theme does not display the transparent bar. It's the `GTK+` version that does.

**Comment by dmarto** [comment]
@sug0 my screenshots are with the `GTK+` version. I now tested with the `Classic` as well, still can't reproduce it.
