### ISSUE TITLE
 postgis became unusable

### ISSUE THREAD

**Issue by basiliscos** [void-linux/void-packages#3701]
### System

* xuname:  Void 4.18.12_2 x86_64 GenuineIntel notuptodate rrrmFFF
* package:  postgis

### Expected behavior

insert geospatial data into postgres

### Actual behavior

fails with error

```
2018-10-12T11:49:21.061494+03:00 localhost postgres: #011B072F0650411AAD1A3750905C415729EC1A2C065041F081971B50905C41AE1FCF322C065041FE775A884D905C41FFB20A8A290650416117F56E4D905C41068BBF9D29065041BE72004E4B905C41D38CFD1B01065041670E87D949905C4126A037EC00065041DE0AD4FC4E905C41', 1308, 66741, NULL, NULL, 34321758, 2, 4200549.69603614975, 7487800.58233274985, '...', 19, NULL, NULL, NULL, NULL, NULL);
2018-10-12T11:52:10.984608+03:00 localhost postgres: ERROR:  could not access file "$libdir/postgis-2.4": No such file or directory at character 213
```

**Comment by cr6git** [comment]
Could you please update your system, and describe precisely how to reproduce the error.
Thanks.

**Comment by basiliscos** [comment]
```
# xuname 
Void 4.18.12_2 x86_64 GenuineIntel uptodate rrrmFFF

echo 'SELECT PostGIS_Full_Version();' | psql -U dev -h 127.0.0.1 my_db_test
ERROR:  could not access file "$libdir/postgis-2.4": No such file or directory
CONTEXT:  SQL statement "SELECT public.postgis_lib_version()"
PL/pgSQL function postgis_full_version() line 25 at SQL statement
```

`postgis` extension is activated on `my_db_test` :`

```
 CREATE EXTENSION postgis
  SCHEMA public
  VERSION "2.4.4";
```

**Comment by Johnnynator** [comment]
```
 CREATE EXTENSION postgis
  SCHEMA public
  VERSION "2.4.4";
```
the version in the repo is `2.5.0` and not `2.4.4`

**Comment by basiliscos** [comment]
My packages were up-to-date, i.e. `postgis-2.5.0_2`. 

However, the data in PG, seems a bit outdated.

I changed the extension version via pg-admin to 2.5.0, and then it started to work fine.

Should we close the issue?

**Comment by Johnnynator** [comment]
> My packages were up-to-date, i.e. `postgis-2.5.0_2`.
> 
> However, the data in PG, seems a bit outdated.
> 
> I changed the extension version via pg-admin to 2.5.0, and then it started to work fine.
> 
> Should we close the issue?

If it works after updating the version number in your own config then I would consider this solved.

**Comment by basiliscos** [comment]
thanks everybody!
