### ISSUE TITLE
etr 0.8.1_1 - X Error of failed request:  BadRRCrtc

### ISSUE THREAD

**Issue by duskull88** [void-linux/void-packages#37038]
----------- Extreme Tux Racer 0.8.1 ----------------
----------- (C) 2010-2021 Extreme Tux Racer Team  --------

X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
  Crtc id in failed request: 0x0
  Serial number of failed request:  67
  Current serial number in output stream:  67

Thank you

**Comment by loreb** [comment]
I tried using void/musl and I couldn't reproduce, everything just worked.

**Comment by duskull88** [comment]
> 

True I tried installing etr on a fully updated fresh install on both glibc and musl, it works fine, so the issue lies somewhere else. Thanks!
