### ISSUE TITLE
vala-panel-appmenu missing dependencies

### ISSUE THREAD

**Issue by sm-idk** [void-linux/void-packages#37064]
### System

* xuname:  Void 5.15.36_1 x86_64 AuthenticAMD uptodate rrrrrmmdnFFFFFFFF
  *output of ``xuname`` (part of xtools)*
* package:  vala-panel-appmenu-0.7.6_2
  *affected package(s) including the version*: ``xbps-query -p pkgver <pkgname>``

### Expected behavior
Package should pull `libdbusmenu-gtk3`, `libdbusmenu-qt5` alongside just `libdbusmenu-glib` so all windows that want to use the appmenu functionality will work with `vala-panel-appmenu` out of the box. (possible that it needs `appmenu-gtk-module`, `appmenu-gtk3-module` and `appmenu-registrar` along with it, but i didn't test that out yet)
### Actual behavior
None of the packages are dependencies of the `vala-panel-appmenu` package, making `vala-panel` and `vala-panel-appmenu` have the same functionality
### Steps to reproduce the behavior
```sh
# xbps-install vala-panel-appmenu
$ vala-panel -p appmenu #This will not work
```
```sh
# xbps-install vala-panel-appmenu libdbusmenu-gtk3 libdbusmenu-qt5
$ vala-panel -p appmenu #This will work as intended
```

**Comment by glaulher** [comment]
appmenu doesn't work without below steps in xfce:

add in /etc/environment:

export GTK_MODULES=appmenu-gtk-module

install:

appmenu-gtk-module appmenu-gtk3-module
appmenu-register

and resolve a bug in schemes:
create org.appmenu.gtk-module.gschema.xml in

/usr/share/glib-2.0/schemas/

contents:

```javascript
<?xml version="1.0" encoding="UTF-8"?>
<schemalist>
  <schema id="org.appmenu.gtk-module" path="/org/appmenu/gtk-module/">
    <key name="blacklist" type="as">
      <summary>Application blacklist</summary>
      <description>List of applications where appmenu-gtk-module should be disabled.</description>
      <default>['anjuta','freeciv', 'freeciv-gtk2', 'freeciv-gtk3', 'glade','gwyddion']</default>
    </key>
    <key name="whitelist" type="as">
      <summary>Application whitelist</summary>
      <description>List of applications where appmenu-gtk-module should be enabled.</description>
      <default>[]</default>
    </key>
    <key name="always-show-inner-menu" type="b">
      <summary>Always show menus in application</summary>
      <description>If this is enabled, menus will not removed from applications even if registrar found. Useful for HUD-only usage.</description>
      <default>false</default>
    </key>
  </schema>
</schemalist>
```
load as root:
glib-compile-schemas  /usr/share/glib-2.0/schemas/

**Comment by sgn** [comment]
not reproducible
