### ISSUE TITLE
lagrange: illegal instruction

### ISSUE THREAD

**Issue by benalb** [void-linux/void-packages#37098]
### System

* xuname:  
  Void 5.15.36_1 x86_64 GenuineIntel uptodate rrmFFFFF

* package:  
  lagrange-1.13.4_1

### Expected behavior
Open a window with the lagrange gemini gemini

### Actual behavior
[benalb@r61 ~]$
lagrange 
Lagrange: A Beautiful Gemini Client
Illegal instruction

### Steps to reproduce the behavior
launch the program. 
The previous version works ok

**Comment by paper42** [comment]
could you test if 966bc8c97c3a5b8269d60eeb9de08f74e0910e21 (lagrange-0.13.4_2) fixes your issue?

**Comment by benalb** [comment]
fixed, thanks
