### ISSUE TITLE
Package request: nvidia-open

### ISSUE THREAD

**Issue by nvidiaLinuxUser** [void-linux/void-packages#37123]
https://github.com/NVIDIA/open-gpu-kernel-modules

**Comment by hervyqa** [comment]
Pkgbuild archlinux https://github.com/archlinux/svntogit-packages/blob/packages/nvidia-open/trunk/PKGBUILD

**Comment by nvidiaLinuxUser** [comment]
Any updates? 🙄

**Comment by mvf** [comment]
There's no stable release yet to package yet. The open-source kernel driver 515.43.04 is currently in alpha (for desktop use) [^1] and requires matching userspace components that are in beta [^2].
[^1]: https://developer.nvidia.com/blog/nvidia-releases-open-source-gpu-kernel-modules/
[^2]: https://www.nvidia.com/download/driverResults.aspx/187826/en-us

**Comment by nvidiaLinuxUser** [comment]
515.48.07 was released today as the first open source stable NVIDIA driver. I hope to see it in the repositories soon (:

**Comment by abenson** [comment]
I'll look at making it an option.  For now, I think we'll continue to ship the proprietary kernel modules due to their wider hardware support.

> The proprietary flavor supports the GPU architectures Maxwell, Pascal, Volta, Turing, Ampere, and forward.
> 
> The open flavor of kernel modules supports Turing, Ampere, and forward. The open kernel modules cannot support GPUs before Turing, because the open kernel modules depend on the GPU System Processor (GSP) first introduced in Turing.

https://us.download.nvidia.com/XFree86/Linux-x86_64/515.48.07/README/kernel_open.html

**Comment by nvidiaLinuxUser** [comment]
It would be nice.

**Comment by abenson** [comment]
Out of curiosity, what GPU do you have, and are you on an Optimus system?

**Comment by nvidiaLinuxUser** [comment]
I am using desktop GTX 1660 Super

**Comment by nvidiaLinuxUser** [comment]
Is there any progress?

**Comment by wael444** [comment]
currently i am trying (i have no deep knowledge of DKMS or void-packages) to package this and have no clue how to make it build the modules if it requests a existing kernel
```
 [ nvidia            ]  CC           ../common/uproc/os/libos-v2.0.0/debug/logdecode.c
 [ nvidia            ]  CC           _out/Linux_x86_64/g_nvid_string.c
 [ nvidia            ]  LD           _out/Linux_x86_64/nv-kernel.o
 [ nvidia            ]  OBJCOPY      _out/Linux_x86_64/nv-kernel.o
make[1]: Leaving directory '/builddir/open-gpu-kernel-modules-515.49.06/src/nvidia'
cd kernel-open/nvidia/ && ln -sf ../../src/nvidia/_out/Linux_x86_64/nv-kernel.o nv-kernel.o_binary
make -C kernel-open modules
make[1]: Entering directory '/builddir/open-gpu-kernel-modules-515.49.06/kernel-open'
make[2]: Entering directory '/builddir/open-gpu-kernel-modules-515.49.06/kernel-open'
make[2]: *** /lib/modules/5.18.9_1/build: No such file or directory.  Stop.
make[2]: Leaving directory '/builddir/open-gpu-kernel-modules-515.49.06/kernel-open'
make[1]: *** [Makefile:82: modules] Error 2
make[1]: Leaving directory '/builddir/open-gpu-kernel-modules-515.49.06/kernel-open'
make: *** [Makefile:50: modules] Error 2
=> ERROR: nvidia-open-515.49.06_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
=> ERROR:   in do_build() at common/build-style/gnu-makefile.sh:14
```

**Comment by nvidiaLinuxUser** [comment]
> currently i am trying (i have no deep knowledge of DKMS or void-packages) to package this and have no clue how to make it build the modules if it requests a existing kernel
> 
> ```
>  [ nvidia            ]  CC           ../common/uproc/os/libos-v2.0.0/debug/logdecode.c
>  [ nvidia            ]  CC           _out/Linux_x86_64/g_nvid_string.c
>  [ nvidia            ]  LD           _out/Linux_x86_64/nv-kernel.o
>  [ nvidia            ]  OBJCOPY      _out/Linux_x86_64/nv-kernel.o
> make[1]: Leaving directory '/builddir/open-gpu-kernel-modules-515.49.06/src/nvidia'
> cd kernel-open/nvidia/ && ln -sf ../../src/nvidia/_out/Linux_x86_64/nv-kernel.o nv-kernel.o_binary
> make -C kernel-open modules
> make[1]: Entering directory '/builddir/open-gpu-kernel-modules-515.49.06/kernel-open'
> make[2]: Entering directory '/builddir/open-gpu-kernel-modules-515.49.06/kernel-open'
> make[2]: *** /lib/modules/5.18.9_1/build: No such file or directory.  Stop.
> make[2]: Leaving directory '/builddir/open-gpu-kernel-modules-515.49.06/kernel-open'
> make[1]: *** [Makefile:82: modules] Error 2
> make[1]: Leaving directory '/builddir/open-gpu-kernel-modules-515.49.06/kernel-open'
> make: *** [Makefile:50: modules] Error 2
> => ERROR: nvidia-open-515.49.06_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 2
> => ERROR:   in do_build() at common/build-style/gnu-makefile.sh:14
> ```

If I am not mistaken, you need to export KERNEL_UNAME. [Here's how it's done in KISS Linux](https://github.com/kiss-community/grepo/blob/master/nvidia/nvidia/build).

**Comment by wael444** [comment]
the way `xbps-src` works is it is built in a chroot or a different system from the host system.
doing this is impossible,

kiss(1) and makepkg(1) both use the host system as the builder.

**Comment by wael444** [comment]
it seems i am getting somewhere:
```
~  $ doas dkms install -m nvidia-open -v 515.49.06                                 

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j6 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=5.18.9_1 modules...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.18.9_1 (x86_64)
Consult /var/lib/dkms/nvidia-open/515.49.06/build/make.log for more information.
```
i am building manually for logging.
```make
make[1]: Entering directory '/usr/src/kernel-headers-5.18.9_1'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 10.2.1 20201203
  You are using:           cc (GCC) 10.2.1 20201203
make[2]: *** No rule to make target '/var/lib/dkms/nvidia-open/515.49.06/build/nvidia/nv-kernel.o_binary', needed by '/var/lib/dkms/nvidia-open/515.49.06/build/nvidia/nv-kernel.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1838: /var/lib/dkms/nvidia-open/515.49.06/build] Error 2
make[1]: Leaving directory '/usr/src/kernel-headers-5.18.9_1'
make: *** [Makefile:82: modules] Error 2
```

**Comment by wael444** [comment]
i have managed to make a shitty but working template:
https://github.com/wael444/void-packages/commit/8d548ccda6cc67f9689bc0094eec7dadd1138827

**Comment by nvidiaLinuxUser** [comment]
It has been a long time since I opened this issue. I have switched to a other distro. I am closing this, if anyone needs the nvidia-open package, create a new issue.

**Comment by wael444** [comment]
hi @nvidiaLinuxUser , nice that we both switched lol
