### ISSUE TITLE
search to find any template already created in github

### ISSUE THREAD

**Issue by ayoubelmhamdi** [void-linux/void-packages#37142]
anyone can create a `template` that describes how to build a `package` automatically  
some contributors store our `template` in github like that
```
github.com/name1/repo1/srcpkgs/vim/template
github.com/name2/repo2/srcpkgs/neovim-qt/template
github.com/name2/repo2/srcpkgs/neovide-bin/template
github.com/name2/repo2/srcpkgs/the-neovide/template
...
```
- so my question is how can I search for it, 
- when I try to find the `template`, that does not in the official [repo][1],  like `neovide`, `brave...`   
using this phrase  `neovide path=srcpkgs/*/template` ,  
 I get nothing, but this is [there][2] files for `neovide` in `github`
- How can I customize my search to find any `template` already created in `github`

  [1]: https://github.com/void-linux/void-packages
  [2]: https://github.com/sug0/voided-packages/blob/master/srcpkgs/neovide/template

**Comment by Duncaen** [comment]
```
path:srcpkgs/brave filename:template
path:srcpkgs/neovide filename:template
```
