### ISSUE TITLE
ansible requires older resolvelib

### ISSUE THREAD

**Issue by Uroc327** [void-linux/void-packages#37163]
The current `ansible-5.6.0_1` on xbps is installed with a too recent `python3-resolvelib`, causing an error when calling `ansible-galaxy` [ansible-collections/community.digitalocean#132](https://github.com/ansible-collections/community.digitalocean/issues/132).

To fix this, ansible requires `resolvelib<0.6.0`.

**Comment by paper42** [comment]
@jcgruenhage

**Comment by jcgruenhage** [comment]
Will be resolved with ansible-core 2.13, because it has been fixed upstream. I can't find much info on pairing ansible 5.x with ansible-core 2.13, so I'm hesitant to update ansible-core before ansible 6.0.0 comes out in a few weeks anyway.

**Comment by jcgruenhage** [comment]
#37758 has been merged, this is fixed. @paper42 can you close this?
