### ISSUE TITLE
Package request: keyd

### ISSUE THREAD

**Issue by Barbaross93** [void-linux/void-packages#37175]
I recently stumbled upon [keyd](https://github.com/rvaiya/keyd), a sweet and simple keyboard daemon similar to kmonad. I've made a template that works, but I don't think I did things "properly", notably the usage of `make_use_env` and the manual install of the needed quirk file for libinput. If there is interest, I'll go ahead and make a PR provided I can get some feedback.

Here's the template:
```
# Template file for 'keyd'
pkgname=keyd
version=2.4.0
revision=1
build_style=gnu-makefile
make_use_env="1"
short_desc="Key remapping daemon for linux"
maintainer="Barbaross <cullenrss@gmail.com>"
license="MIT"
homepage="https://github.com/rvaiya/keyd"
distfiles="https://github.com/rvaiya/keyd/archive/refs/tags/v${version}.tar.gz"
checksum=100007894ac4fa6e95f5de5c2fe992c8b00e68d9df76c4bcdd8402a29d7b4058

post_install() {
	vlicense LICENSE
	vinstall ${wrksrc}/keyd.quirks 644 usr/share/libinput 30-keyd.quirks
}
```

**Comment by classabbyamp** [comment]
I'd definitely suggest making the PR whether there's interest from others or not.

Just a couple notes from what I see here:
- `make_use_env=yes`
- `vinstall` assumes the first argument is in `$wrksrc`, so it shouldn't need to be specified
- if it's supposed to be run as a system-wide service, adding a runit service for it would probably be useful

**Comment by Barbaross93** [comment]
Thanks for the tips @classabbyamp ! I forgot to mention one other problem I ran into: the project's make file tries to create the group `keyd` but fails. Do you know whats the proper way to fix this?

Technically, you could run keyd as a user service provided the user is part of the `keyd` group so I'm not sure if it makes sense to create a runit service.

**Comment by classabbyamp** [comment]
you can use `system_groups` to have xbps create the group when stealing the package, but you may need to patch it out of the build files too

**Comment by Barbaross93** [comment]
Excellent, thanks! I'll make a PR soon.

**Comment by classabbyamp** [comment]
done in #37195
