### ISSUE TITLE
Fix vscode Github sign-in

### ISSUE THREAD

**Issue by EdoardoLaGreca** [void-linux/void-packages#37202]
Code OSS (package `vscode`) is not able to sign-in using Github because of a missing URL handler. The URL handler in question is provided by a file in `/usr/share/applications` called `code-oss-url-handler.desktop`. I got that file from the [respective Arch Linux package](https://archlinux.org/packages/community/x86_64/code/) but it is provided from the official repo as well (see [this file](https://github.com/microsoft/vscode/blob/main/resources/linux/code-url-handler.desktop)).

Other than that, it is necessary to set the default application for the specific MIME type using the command below

```
xdg-mime default code-oss-url-handler.desktop x-scheme-handler/code-oss
```

Thanks to @toluschr for [his comment](https://github.com/MicrosoftDocs/live-share/issues/3057#issuecomment-671072052) in a related issue.

**Comment by paper42** [comment]
@atk

**Comment by atk** [comment]
@shizonic

**Comment by EdoardoLaGreca** [comment]
was this actually completed?

**Comment by atk** [comment]
The issue is no longer reproducible. I guess an update fixed it accidentially.

**Comment by EdoardoLaGreca** [comment]
good to know
