### ISSUE TITLE
Please Add Basic Essential Apps like Webcamoid,Thonny and VS Codium to the Repo..

### ISSUE THREAD

**Issue by CapeCrusader321** [void-linux/void-packages#37239]
It is sad that important,famous and open-source apps like VS Codium, Thonny and webcamoid isnt available in Void Repo or xbps-src, with flatpak they dont work normally, they need to be native package to function smoothly, Void Team must instantly add such important apps to repos...

**Comment by paper42** [comment]
We have vscode, but I have never heard about the other apps.

**Comment by CapeCrusader321** [comment]
Are You Serious ?? Thonny is a Default Python IDE For Raspberry Pi and a good IDE for beginners, VS Codium is e complete open-source version of VS Code which contains Microsoft Telemetry and Webcamoid is a full-fledged Replacement for cheese, Void team must have them in  their repos.

**Comment by paper42** [comment]
We are only talking about a bunch of ones and zeros, no need to get emotional about that.

Our vscode has telemetry disabled, you can find information about that in the template and a dozen of other issues requesting vscodium.

**Comment by q66** [comment]
have you considered that maybe they are not as important and essential as you think

**Comment by CapeCrusader321** [comment]
Thanks to all for checking out, i have downloaded the telemetry free VS Code from repos and made thonny run fine, they all are working fine. Closing this....
