### ISSUE TITLE
Package request: eww

### ISSUE THREAD

**Issue by justleoo** [void-linux/void-packages#37234]
how can i add a package having it for wayland and xorg?
pkg: `eww`

**Comment by classabbyamp** [comment]
that package [requires rust nightly](https://elkowar.github.io/eww/#prerequisites), so it is probably not packagable as-is. However, it should be fairly straightforward to build and install yourself following the instructions in the link.

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/656a120f83a162ab46d16da1982f40dbfaa61088
