### ISSUE TITLE
mariadb-client has symlinks to binaries from the mariadb package

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#37282]
### System

* xuname:  `Void 5.15.41_1 x86_64 AuthenticAMD notuptodate rFFFFFFFFFFFF`
* package:  mariadb-client-10.5.10_2 mariadb-10.5.10_2

### Expected behavior

Install mariadb-client, and use the client.

### Actual behavior

mariadb-client package has files like `/usr/bin/mysql -> /usr/bin/mariadb`, but not the destination of the symlink or even a dependency on the mariadb package which actually has the binary.

### Steps to reproduce the behavior

Install mariadb-client without mariadb and try to use mysqldump, for example.

**Comment by classabbyamp** [comment]
pretty much the entire `-client` package is symlinks to stuff not in that package (plus manpages). seems like those packages should either be merged or depend on the main package.
