### ISSUE TITLE
Timeshift new upstream repo

### ISSUE THREAD

**Issue by 10leej** [void-linux/void-packages#37364]
[teejee2008 is no longer going to be maintaining timehistf](https://github.com/teejee2008/timeshift/commit/9d614d5e2e20cb4486b4f4becf7f60c5cd0dea1a) and the Linux Mint Team is taking it over

New Repo: https://github.com/linuxmint/timeshift

**Comment by abenson** [comment]
> This repo will continue to be available in the future, but will only see bug fixes and minor changes.

For now we'll keep tracking the original author's project, until Mint's diverges enough and teejee2008's is left behind.
