### ISSUE TITLE
fontconfig: font directories modified after indexing

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#37367]
### System

* xuname:  
  * ``Void 5.16.20_1 x86_64 GenuineIntel uptodate FFFFFFFF``
* package:  
  * ``fontconfig-2.13.1_3``

### Expected behavior
When font directories are indexed, they should only be read. They should not be modified, as one of the purposes of indexing font directories is to detect font updates and if directories are modified upon being indexed, erroneous font updates will be reported.

### Actual behavior
Every time fontconfig indexes existing font directories, if a font directory is empty and writable by the user under which the indexing is performed, its modified time is updated.

This breaks the font update detection feature of fontconfig since if indexing font directories results in some of them being modified, fontconfig will report font updates after each index instead of reporting only actual changes to the available fonts.

Additionally, this cause the font cache at ``~/.cache/fontconfig/`` to become populated with redundant data as updates are detected and cached when no actual changes have taken place.

### Steps to reproduce the behavior
1. Install ``fontconfig``
2. Create a font directory which is user-writable such as ``~/.local/share/fonts`` and ensure it is empty.
3. Inspect the modified timestamp on the directory (``stat ~/.local/share/fonts``)
4. Do something which indexes font directories such as running ``fc-list``
5. Inspect the modified timestamp on the directory again (``stat ~/.local/share/fonts``) and see that it has been changed.

**Comment by Duncaen** [comment]
Is this a void linux issue or a upstream issue?

**Comment by chili-b** [comment]
Not sure. I opened an issue upstream, but there has been no response. What I *do* know is that I can reproduce this issue on multiple void installs, but not on debian or ubuntu.
