### ISSUE TITLE
nix-channel --update crashes on musl

### ISSUE THREAD

**Issue by loreb** [void-linux/void-packages#37382]
### System

* xuname:  
  Void 5.10.117_1 x86_64-musl GenuineIntel uptodate rFFF
* package:  
  nix-2.8.1_1

### Expected behavior
It works as usual

### Actual behavior
```
$ nix-channel --update
unpacking channels...
RT34
$ echo $?
162
$ strace nix-channel --update
(...)
vfork()
+++ killed by SIGRT_2 +++
RT34
```

### Steps to reproduce the behavior

Run the above on a musl machine.

To make it more interesting, if you stop the nix-daemon service,
log in as root, and run /etc/sv/nix-daemon/run by hand the behavior changes:
nix-daemon starts to spew many, many, *many* messages saying that it accepted a connection from $pid until it runs out of memory while keeping tens of thousands of nix-daemon processes alive (or zombies?); I have no idea if adding substantially more memory would help, but I know at least that this used to work before.

The bug happens the exact same way with the newly released 2.9.0 (I believe - I had to fiddle with the `--with-sandbox-shell` option to get it to compile for some reason).

`grep -R SIGRT` in the nix sources doesn't return any result, so I guess it's in some dependency (boost?)

Any help is greatly appreciated.

edit:
it makes no difference on my machine (or a vm), but in case you've never used nix before,
you're supposed to first enable the nix-daemon service and then,
as an unprivileged user, subscribe to a nix channel (`nix-channel --add https://nixos.org/channels/nixpkgs-unstable`) before trying to update.
AND maybe do it from a fresh login to pick up on /etc/profile.d/nix*.sh

**Comment by paper42** [comment]
I can not reproduce this on aarch64-musl
```
%: nix-channel --update
unpacking channels...
created 0 symlinks in user environment
%: echo $?
0
```

**Comment by loreb** [comment]
@paper42 thank you; for some reason I can boot alpine/debian/ubuntu under qemu-system-aarch64 but not void...
Just out of curiosity (it makes no difference here, both on real hw/freshly installed vm) - did you enable the nix-daemon service & subscribe to a channel before? The command is `nix-channel --add https://nixos.org/channels/nixpkgs-unstable`.
Sorry I forgot to add those, I'm editing the original message

**Comment by xiarenfan** [comment]
Can be used
```sh
sh <(curl -L https://nixos.org/nix/install) --no-daemon
```
to avoid the problem

**Comment by loreb** [comment]
> Can be used
> 
> ```shell
> sh <(curl -L https://nixos.org/nix/install) --no-daemon
> ```
> 
> to avoid the problem

Witchcraft! :)

TBH I kinda gave up because currently I'm only using it for a game and that SIGRT apparently comes from the Bohem garbage collector; does the bug happen on your computer as well?

**Comment by xiarenfan** [comment]
> > Can be used
> > ```shell
> > sh <(curl -L https://nixos.org/nix/install) --no-daemon
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to avoid the problem
> 
> Witchcraft! :)
> 
> TBH I kinda gave up because currently I'm only using it for a game and that SIGRT apparently comes from the Bohem garbage collector; does the bug happen on your computer as well?

The error did happen on my computer，I think it's nix-daemon's service issue.because it's service only `/var/service/nix-daemon`
```sh
exec nix-deamon
``` 
but i try `sv status nix-daemon`
```sh
down nix-daemon: 0s, normally up ,want up
```

**Comment by loreb** [comment]
@xiarenfan not what I see, nix-daemon (from xbps-install) is up but running commands fails; try looking at runsvdir (`ps auxww|grep runsvdir`) or the syslog for clues (if the version you're trying to run is the one from nixos.org it's because you need to modify its $PATH).

The command you suggested works even if installed with `--daemon`, but there's a catch...
```
$ file ./store/xdlpraypxdimjyfrr4k06narrv8nmfgh-nix-2.11.1/bin/nix
./store/xdlpraypxdimjyfrr4k06narrv8nmfgh-nix-2.11.1/bin/nix: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /nix/store/scd5n7xsn0hh0lvhhnycr9gx0h8xfzsl-glibc-2.34-210/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=4c07925e180f9517c88c38492c85b966acfb251c, not stripped
```

The binary from nixos.org works because it is a glibc binary that ships its own glibc -to verify, run `ldd $(which nix)` and notice the libc symbols that fail to resolve.

**Comment by vincele** [comment]
Still happens on:

    # xuname
    Void 6.1.31_1 x86_64-musl AuthenticAMD uptodate rrnFFFFFFFF

    # xbps-query -Rs nix-2
    [*] nix-2.11.0_5 Purely functional package manager

    # sv status nix-daemon
    run: nix-daemon: (pid 17445) 1804s; run: log: (pid 17444) 1804s

**Comment by vincele** [comment]
@paper42 : does the above reproduction make the "needs-testing" tag removable ?

**Comment by vincele** [comment]
This is probably musl-related, as I don't have the error in a x86_64 glibc chroot.

    $ nix-channel --update
    error: creating directory '/nix/store/.links': Permission denied

Which looks normal as I don't have /nix in the chroot

**Comment by loreb** [comment]
Oh sorry I misunderstood - yes, nix+glibc works fine

**Comment by loreb** [comment]
FWIW newer versions of nix require newer version of json-c++ and rapidcheck; I built the latest release at https://github.com/loreb/void-packages/tree/nix2.16.0 and `nix-channel --update` still fails the same way on musl (didn't test glibc).

**Comment by classabbyamp** [comment]
postgresql13 needs to be removed from the repos, the template is removed. I've started that process

**Comment by loreb** [comment]
Oh great thank you
