### ISSUE TITLE
Package Request: alacarte

### ISSUE THREAD

**Issue by johnny-mac** [void-linux/void-packages#3740]
This one needs nothing & is good-to-go as-is. Much better than menulibre in my humble opinion.
```
# Template file for 'alacarte'
pkgname=alacarte
version=3.11.91
revision=1
build_style=gnu-configure
hostmakedepends="autoconf automake gnome-common intltool gettext-devel
 glib-devel pkg-config python docbook-xsl"
makedepends="gnome-menus-devel python-gobject-devel libxslt-devel
 gtk+3-devel"
depends="desktop-file-utils hicolor-icon-theme gnome-menus"
short_desc="GNOME Menu-editor"
maintainer="Johnny-Mac <johnny-mac@linuxmail.org>"
license=GPL-2.0-or-later
homepage="http://www.gnome.org/"
distfiles="https://github.com/gnome/${pkgname}/archive/${version}.tar.gz"
checksum=ea2810b917ca6f4fc8694683b893d008bdb2fb7cd5ce503917a4828c3f282605
pre_configure() {
        ./autogen.sh
}
```

**Comment by cr6git** [comment]
You have the template, why don't you open a pull request?

**Comment by abenson** [comment]
Yes, a PR would make it easier to comment on the template and it'll go through Travis at least.

**Comment by johnny-mac** [comment]
Sorry, I can't figure out how to work git. Somebody can submit these if they'd like, I've done all the work.... Don't care if its submitted under a different maintainers name, that's totally fine. I've tried and tried with git, I cannot figure out how to make it work the way I want it to.... Seems like too much trouble for doing something so simple.

**Comment by cr6git** [comment]
@johnny-mac about git, perhaps [this comment](https://github.com/voidlinux/void-packages/pull/4875#issuecomment-252489270) would help you ;)

**Comment by linkert** [comment]
How are we doing with this? Tried out MenuLibre, some sketchy things going down with it and I thought I'd try this Alacarte instead but did not find it in the repos. Either you @johnny-mac learn this git stuff or I have to :) I'm a total noob at git and really do not want to maintain anything.

**Comment by maxice8** [comment]
> How are we doing with this?

Like it is always done on Void, the people that want it, do it, or get someone else to do it for them.

**Comment by linkert** [comment]
> > How are we doing with this?
> 
> Like it is always done on Void, the people that want it, do it, or get someone else to do it for them.

The other night I was about to dive head first into this. Took a minute until I felt my brain taking damage by what I was reading. It's too abstract for me haha!

**Comment by maxice8** [comment]
Last release was 5 years ago.

**Comment by linkert** [comment]
> Last release was 5 years ago.

I mean no disrespect but I have to ask, what relevance does the update frequency have when it comes to a fulfilled menu editor that works flawlessly? Installed it on xubuntu the other day and it's a fantastic menu editor - not a single hick up opposed to my experience with MenuLibre which is updated frequently and yet needs workarounds when using it for XFCE.
