### ISSUE TITLE
How to update the rust-bootstrap package?

### ISSUE THREAD

**Issue by JuniorSuperTux** [void-linux/void-packages#37432]
https://github.com/void-linux/void-packages/pull/37430#issuecomment-1148410605

In this pull request, I'm trying to update the starship package which requires a newer version of rust to build. I don't know how to update rust-bootstrap to `1.59.0` since it isn't in https://repo-default.voidlinux.org/distfiles (the template fetch from there). This is my first time here and I don't know what to do. How should I update the rust-bootstrap package?

**Comment by Chocimier** [comment]
Solved in #37232.
