### ISSUE TITLE
org.gnome.DiskUtility.desktop not executing "gnome-disks" executable through an App Launcher, yet using a custom gendesk .desktop file works fine, CLI as well works

### ISSUE THREAD

**Issue by TeusLollo** [void-linux/void-packages#37555]
### System

* xuname:  
Void 5.15.45_1 x86_64 GenuineIntel uptodate rFFFF
* package:  
gnome-disk-utility-41.0_1

### Expected behavior
"org.gnome.DiskUtility.desktop" file located into "/usr/share/applications" should execute the "gnome-disks" executable when selected through a given App Launcher Application compatible with freedesktop.org specifications, thus launching the Gnome-Disks App. 

### Actual behavior
"org.gnome.DiskUtility.desktop" file located into "/usr/share/applications" fails completely with no error messages when selected into a given App Launcher Application ("wofi" in my current case, with "sway" WM).

Yet, executing the "gnome-disks" executable through CLI works perfectly, and the App itself works perfectly too. 

Also, I went ahead, and utilized "gendesk" to create a custom .desktop file which I put into "~/local/share/applications". I can confirm that such a custom .desktop file WORKS perfectly, and have in fact been using it for a few months already (Hence why I forgot to report before).

Code of MY custom .desktop file, created through "gendesk", and located into "~/local/share/applications", is as follows:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=Disks-Gnome
Comment=Disks-Gnome
Exec=gnome-disks
Icon=/home/username/.local/share/applications/FlatDisks.png
Terminal=false
StartupNotify=false
Categories=Application;
```

My custom .desktop file, aside from missing localization tags, also misses the "DBusActivatable=true" parameter which I found into "org.gnome.DiskUtility.desktop" file located into "/usr/share/applications", yet I presume this is not very relevant to the issue at hand. 

This has been happening for a few months already (My custom .desktop works fine, thus I forgot to report in the meantime), and has been happening on three separate machines to boot, all with manual install only. App Launcher is currently "wofi" with "sway" WM, but months ago I also saw this happening with "rofi", on "openbox" WM.  

### Steps to reproduce the behavior

Simply select the "org.gnome.DiskUtility.desktop" (Tag-named to "Disks" if App Launcher can read such tags, and is configured to do so) into a given freedesktop.org-compatible App Launcher (This has been happening both with "wofi" and "rofi" on me), and it will NOT execute the "gnome-disks" executable, thus NOT launching the Gnome-Disks App. 

However, executing "gnome-disks" through the CLI, or otherwise utilizing a custom .desktop file created through "gendesk" as mentioned above, both launch the App just fine. 

Maybe some post-install MIME update is missing? This has been happening also on a very recent (Less than 4 weeks) manual Void Install.

**Comment by paper42** [comment]
Could you test if you can still reproduce this issue with gnome-disks-utility 42.0?

**Comment by TeusLollo** [comment]
@paper42 
Here's the report:

1) Yes, the issue still appears identically with package gnome-disk-utility-42.0_1 installed

2) The solution I provided above (Custom .desktop file, created through "gendesk", and located into "~/local/share/applications") still works perfectly

3) There was NOT a need to rebuild such custom .desktop file. The latter has been working with both the previous and the current gnome-disk-utility package versions with NO modifications/rebuilds whatsoever

4) Everything stated above in the bug report is still valid. Only thing which has changed was the package update to gnome-disk-utility-42.0_1 (Aside from further updates of dependencies/unrelated packages in the meantime, of course)

5) I can testify that the gnome-disk-utility app otherwise works perfectly

Thanks for your concern.

**Comment by paper42** [comment]
I can not reproduce this, `dex /usr/share/applications/org.gnome.DiskUtility.desktop` runs fine, `desktop-file-validate /usr/share/applications/org.gnome.DiskUtility.desktop` is clean and running Disks with `wofi --show drun` also works fine.

**Comment by paper42** [comment]
> DbusActivatable: A boolean value specifying if D-Bus activation is supported for this application. If this key is missing, the default value is false. If the value is true then implementations should ignore the Exec key and send a D-Bus message to launch the application. See D-Bus Activation for more information on how this works. Applications should still include Exec= lines in their desktop files for compatibility with implementations that do not understand the DBusActivatable key.

It seems like your system is missing the dbus user session, but wofi tries to launch gnome-disks with a dbus message.
I think this is a bug in wofi - wofi should fall back to just running Exec when the dbus user session is not available.

**Comment by paper42** [comment]
It expects a dbus user session, so you should replace `exec <wm>` in your .xinitrc with `exec dbus-run-session <wm>` (or an equivalent of that), but it's still a bug.

**Comment by paper42** [comment]
I don't think we can do anything with this, this seems to be an upstream wofi issue.

**Comment by bileslav** [comment]
@TeusLollo, here's the missing part:

`dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP`

It should be executed after those variables initialized, e.g. inside `~/.config/river/init` in my case.

I really lazy to elaborate now. Also ATM I can't use Google Translate to correctly formulate, so I'm sorry for anything. IIRC, sway docs had some information about this.

Hope this will help someone.
