### ISSUE TITLE
unknown: X11 apps break, have to manually run mkfontdir & mkfontscale

### ISSUE THREAD

**Issue by Veyrdite** [void-linux/void-packages#37565]
### System

* xuname:  Void 5.15.45_1 x86_64 GenuineIntel uptodate rFFFFFFFFFFF
* package:  unknown

### Problem

Today I ran xbps-install -Su and everything seemed fine until I restarted Xorg.  Then several issues started occurring:

* i3bar displayed the wrong font
* urxvt wouldn't launch (it couldn't find my font)
* xfontsel wouldn't launch ("Warning: Unable to load any usable ISO8859 font")

Reinstalling encodings, font-misc-misc, fontconfig and xorg-fonts had no impact on the problem, even after restarting Xorg.

### Fix

As per https://old.reddit.com/r/voidlinux/comments/ubv7nc/getting_badname_named_color_or_font_does_not/ (I am NOT the op, but I had the same issue today and their fix worked)

```
# cd /usr/share/fonts/X11/misc
# mkfontdir
# mkfontscale
(now restart xorg, however you do that on your system)
```

**Comment by classabbyamp** [comment]
what was installed/updated when you ran `xbps-install -Su`? If you have a [syslog](https://docs.voidlinux.org/config/services/logging.html) set up, it would show in the syslog output.

**Comment by icp1994** [comment]
Facing the same problem. Although I'm in wayland, vivaldi is run under XWayland and the fonts are messed up in some places, especially in the tabbar. [xbps-cache-tail.txt](https://github.com/void-linux/void-packages/files/8912546/xbps-cache-tail.txt)
