### ISSUE TITLE
Package request: GNUnet

### ISSUE THREAD

**Issue by fluentpwn** [void-linux/void-packages#37575]
Current available version on x86_64 musl libc 0.12.2_4, while current version is 0.17.1. Update please

**Comment by paper42** [comment]
> \

**Comment by fluentpwn** [comment]
> > \

I don't quite understand which script and how to use it. Is there any information about it?

**Comment by paper42** [comment]
> > > 
> 
> I don't quite understand which script and how to use it. Is there any information about it?

There is no point in reporting that a package is outdated, we know about it from the linked file. And the file is generated every day by running ./xbps-src update-check on every package.
