### ISSUE TITLE
Qt5 updates will require some Qt5 Apps to be rebuilt against newer versions

### ISSUE THREAD

**Issue by TeusLollo** [void-linux/void-packages#37598]
### Is this a new report?

Yes

### System Info

Void 5.15.47_1 x86_64 GenuineIntel uptodate rFFFF

### Package(s) Affected

corectrl-1.2.3_2

### Expected behaviour

Recent updates of Qt5 libraries apparently broke several depending packages that must be rebuilt for it, which should otherwise work. 

### Actual behaviour

Qt5-based applications currently crash due to the recent update of Qt5 libraries. When launching CoreCtrl, for example, here's the output I get:

[17-06-22 14:20:26.361][W] vulkaninfo command failed
Cannot mix incompatible Qt library (5.15.2) with this library (5.15.4)
zsh: IOT instruction  corectrl

Fairly self-explanatory. 

An user on reddit con also confirm that VirtualBox has also been broken:
https://reddit.com/r/voidlinux/comments/ve9gky/todays_qt5_updates_broke_virtualbox/

### Steps to reproduce

1 Update a given x86_64 Void Linux system with the most recent Qt5 libraries into repositories. 
2 Try to launch CoreCtrl (Or, more likely, most qt5 applications which have not been rebuilt against newer libraries)
3 See failure-to-launch outputs for yourself

I presume at least some applications will need to be rebuilt for the newer qt5 libraries. 
Just dropping this bug report here, feel free to remove if it's felt inappropriate and/or pestering. 

Thanks for all your work, devs!

**Comment by paper42** [comment]
@Johnnynator

**Comment by paoloschi** [comment]
packages __FeatherPad__ and __qterminal__ are also affected
```
$ featherpad
Cannot mix incompatible Qt library (5.15.2) with this library (5.15.4)
Annullato

$ qterminal
Cannot mix incompatible Qt library (5.15.2) with this library (5.15.4)
Annullato
```

**Comment by Johnnynator** [comment]
https://github.com/void-linux/void-packages/commit/d91549bb2a873e6679b79b17db6a065b46935c34

Did you guys use qt5-styleplugins? (I haven't checked yet if other qt5 plugins are also affected, styleplugins is always, just forgot about it in advance)

**Comment by paoloschi** [comment]
> Did you guys use qt5-styleplugins?

yes, I use it and in fact after just now removing it, the two programs I reported are running without error!

**Comment by RicArch97** [comment]
Can confirm rebuilding `qt5-styleplugins` fixes the issues for me as well

**Comment by TeusLollo** [comment]
I'm confirming that, after most recent qt5-styleplugins update, package corectrl-1.2.3_2 has been fixed, and is now fully-functional. 
Damn, I didn't expect for qt5-styleplugins to be this nuclear.

@Johnnynator 
I didn't have a VirtualBox setup before Qt5 updates, so I can't confirm if VirtualBox (Reported on reddit by others) has been fixed. 
Do you want me to close this, or do you believe there are risks of more Qt5 packages affected, and will need more reports?

**Comment by paoloschi** [comment]
It seems that the same occurrence was repeated today....

**Comment by JamiKettunen** [comment]
@paoloschi Thanks for the report! `qt5-styleplugins` was not only rebuilt but also restricted to a specific `qt5` runtime dependency version with 8232af3e5c01fb4b653ec10cb98ace1faff27ed9 which should at least prevent breaking runtime in the future (as it'll just prevent you from upgrading if `qt5-styleplugins` wasn't also bumped).
