### ISSUE TITLE
libmbedcrypto breaking some apps

### ISSUE THREAD

**Issue by CaptainDrewBoy** [void-linux/void-packages#37665]
(notes with an asterix are largely anecdotal and people smarter than me can probably think of reasons to disregard them)

mpv and qutebrowser won't start for me anymore, both citing an `error while loading shared libraries: /usr/lib64/libmbedcrypto.so.3: file too short`
The cited file does exist, but is empty. I have `mbedtls` installed, but Void's version appears to be out of date from upstream.
\* I have also had difficulties getting apps to register mic input, but I can't tell if these are related.
\* I suspect, but don't have the technical know-how to prove, that this is related to a recent update that pulled `librist` onto my system, which depends on `mbedtls`.

**Comment by HadetTheUndying** [comment]
I tried to verify this on my own, but it is not reproducible on my system. However after talking in IRC it does appear the LTS version has changed. I'm unsure if it's related.

**Comment by sgn** [comment]
Please run `xbps-pkgdb -a` and check if there is any problems in your machine.

**Comment by CaptainDrewBoy** [comment]
> Please run `xbps-pkgdb -a` and check if there is any problems in your machine.

Produces no output. I *was* having some output before in relation to `arc-theme`, but after fixing them, and reconfiguring `mbedtls` and the apps that wouldn't work, nothing changed.

**Comment by CaptainDrewBoy** [comment]
> How about: `ls -al /usr/lib/libmbedcrypto*`

`-rwxr-xr-x 1 root root  0 Feb 20 00:15 /usr/lib/libmbedcrypto.so.2.16.12
lrwxrwxrwx 1 root root 24 Feb 20 00:15 /usr/lib/libmbedcrypto.so.3 -> libmbedcrypto.so.2.16.12`
As far as I can tell these files are empty.

**Comment by sgn** [comment]
`/usr/lib/libmbedcrypto.so.2.16.12` if this file is empty, `xbps-pkgdb` should report an errors.
Are you sure you install `mbedtls` correctly?

**Comment by CaptainDrewBoy** [comment]
> I can not reproduce this, the file is not empty on my system. What's the output of xuname on your system? Please use the bug issue template next time when reporting bugs.

Firstly, sorry for not using the template.
xuname gives `Void 5.15.47_1 x86_64 GenuineIntel uptodate rrrmFFFFFF`


> `/usr/lib/libmbedcrypto.so.2.16.12` if this file is empty, `xbps-pkgdb` should report an errors. Are you sure you install `mbedtls` correctly?

`mbedtls` was pulled in as a dependency for something pretty quickly after I setup my system iirc. I've never really messed with its installation, xbps has just managed it for me.

**Comment by sgn** [comment]
I meant, are you sure, `sudo xbps-pkgdb -a` reports no errors? With an empty `/usr/lib/libmbedcrypto.so.2.16.12`, it should report some error like:
```
ERROR: linux5.15: hash mismatch for /boot/vmlinuz-5.15.47_1.
```
Your installation is somewhat broken, and you should be told that.

**Comment by CaptainDrewBoy** [comment]
> I meant, are you sure, `sudo xbps-pkgdb -a` reports no errors? With an empty `/usr/lib/libmbedcrypto.so.2.16.12`, it should report some error like:
> 
> ```
> ERROR: linux5.15: hash mismatch for /boot/vmlinuz-5.15.47_1.
> ```
> 
> Your installation is somewhat broken, and you should be told that.

I swear this wasn't popping up before, but I ran this command again to triple check and now there is more output.
```ERROR: mbedtls: hash mismatch for /usr/lib/libmbedcrypto.so.2.16.12.
ERROR: mbedtls: hash mismatch for /usr/lib/libmbedtls.so.2.16.12.
ERROR: mbedtls: hash mismatch for /usr/lib/libmbedx509.so.2.16.12.
ERROR: mbedtls: files check FAILED.
ERROR: openjdk8: alternatives group jdk symlink /usr/bin/java has wrong target.
ERROR: openjdk8: alternatives group jdk symlink /usr/bin/jjs has wrong target.
ERROR: openjdk8: alternatives group jdk symlink /usr/bin/keytool has wrong target.
ERROR: openjdk8: alternatives group jdk symlink /usr/bin/orbd has wrong target.
ERROR: openjdk8: alternatives group jdk symlink /usr/bin/pack200 has wrong target.
ERROR: openjdk8: alternatives group jdk symlink /usr/bin/policytool has wrong target.
ERROR: openjdk8: alternatives group jdk symlink /usr/bin/rmid has wrong target.
ERROR: openjdk8: alternatives group jdk symlink /usr/bin/rmiregistry has wrong target.
ERROR: openjdk8: alternatives group jdk symlink /usr/bin/servertool has wrong target.
ERROR: openjdk8: alternatives group jdk symlink /usr/bin/tnameserv has wrong target.
ERROR: openjdk8: alternatives group jdk symlink /usr/bin/unpack200 has wrong target.```

**Comment by sgn** [comment]
OK. So, only `mbedtls` is broken. Please re-install that package: `sudo xbps-install -yff mbedtls`

**Comment by CaptainDrewBoy** [comment]
It would appear that fixed my issue.
Which is weird, because I tried reinstalling `mbedtls` before filing the issue.
Maybe one of the flags were different?
Whatever, it's fixed now. Thank you for all the help.
