### ISSUE TITLE
[Cinnamon] Segmentation fault

### ISSUE THREAD

**Issue by trourance** [void-linux/void-packages#37723]
### Is this a new report?

Yes

### System Info

Void 5.15.50_1 x86_64 GenuineIntel notuptodate rFFF

### Package(s) Affected

cinnamon-control-center-5.2.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://bugs.gentoo.org/840317
https://github.com/linuxmint/cinnamon/issues/10616

### Expected behaviour

No segmentation fault

### Actual behaviour

Segmentation fault

### Steps to reproduce

$ cinnamon-settings network

**Comment by classabbyamp** [comment]
can you test https://github.com/void-linux/void-packages/pull/37732 ?

**Comment by trourance** [comment]
It works like a charm. Thanks
