### ISSUE TITLE
plasma-desktop requires gtk4?

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#37738]
### Is this a new report?

Yes

### System Info

Void 5.15.50_1 x86_64-musl GenuineIntel uptodate rFFFFF

### Package(s) Affected

`gtk4-4.6.5_1`, `ibus-1.5.26_1`, `plasma-desktop-5.24.5_1`

### Expected behaviour

`plasma-desktop` shouldn't need `gtk4`

### Actual behaviour

currently i'm using kde plasma, but why should i install gtk4?

```
~ doas xbps-remove gtk4
gtk4-4.6.5_1 in transaction breaks installed pkg `ibus-1.5.26_1'
Transaction aborted due to unresolved dependencies.
~ xbps-query -X gtk4
ibus-1.5.26_1
~ xbps-query -X ibus
plasma-desktop-5.24.5_1
~ xbps-query -x plasma-desktop | grep ibus
ibus>=1.4.99.20120917_1
```

### Steps to reproduce

1. kde plasma installed.
2. update, `doas xbps-install -Su`

**Comment by paper42** [comment]
I don't think this is a bug, ibus used to have only gtk2 and gtk3 IM modules, but now it also has a gtk4 module. Why is gtk4 dependency an issue, but gtk2 and gtk3 isn't?

**Comment by hervyqa** [comment]
You're right, I meant just to ask. i think after update there is no app from gtk4, but after updated there is Icon Browser (`gtk4-icon-browser`). currently in kde can't (or still in development) set up gtk4 app ui view.

**Comment by oreo639** [comment]
From a package consistency point of view, it would probably make sense to move IconBrowser4 to gtk4-demo like PrintEditor4 and WidgetFactory4.

**Comment by paper42** [comment]
gtk+3 also has icon browser in the main package. Either way, this is not an issue
