### ISSUE TITLE
After recent upgrade, void lands at `dracut>` prompt

### ISSUE THREAD

**Issue by zenny** [void-linux/void-packages#37757]
Hi,

Context:

- Non-root-zfs (ext4) on a separate drive
- Mirrored zpool which is accessible
- The machine does not boot beyond dracut.

An upgrade two days back brought the kernel from booting and now inaccessible.

1. Prior to the `dracut` prompt it asks to enable `rd.debug`. I use the open sourced radeon driver for the graphics card as follows:
```
" $ lspci | grep VGA
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Caicos [Radeon HD 6450/7450/8450 / R5 230 OEM]
```
How can I fix the issue?

2. However, it seems similar to https://github.com/void-linux/void-packages/issues/37667

But the machine is not accessible beyond the dracut prompt. How can one append `omit_dracutmodules+=" zfs "` to `/etc/dracut.conf.d/zfs.conf` (proposed by @zdykstra in https://github.com/void-linux/void-packages/issues/37667#issuecomment-1165599150 and endorsed by @ahesford in  https://github.com/void-linux/void-packages/issues/37667#issuecomment-1165688484and regenerate the init file?

Cheers,
/z

**Comment by zenny** [comment]
> This is definitely a duplicate of #37667. Unfortunately, the only way to fix your initramfs is to grab a live image (I prefer [hrmpf](https://github.com/leahneukirchen/hrmpf)), mount your root and `/boot`, chroot in, add the change to the Dracut configuration, and then regenerate all initramfs images. (The easiest way to do that is `xbps-reconfigure -f zfs`.)

@ahesford  Thanks for confirming and your useful input.

Meanwhile, I have booted into pop_os22.04  installed on different partition07 in the same drive and mounted the void /root and /boot partition (both installed on single partition6). Is the following right way to do the same stuff in chrooted environment? If not, I appreciate your input.

```
mount /dev/sdd6 /mnt/voidrootboot
mount --bind /sys/ /mnt/voidrootboot/sys/
mount --bind /proc/ /mnt/voidrootboot/proc/
mount --bind /dev/ /mnt/voidrootboot/dev/
chroot /mnt/voidrootboot
xbps-reconfigure -f zfs
```
Thanks in advance.

**Comment by zenny** [comment]
> You may need to replace the `--bind` with `--rbind` for the `/dev` mount if anything about the Dracut rebuild needs `/dev/pts`, but otherwise this should work fine.

@ahesford Back to void. :D Thanks for your inputs. The culprit was handled with your help. Thanks.

However, I did the following to ease those who come across the same issue.

1. Mounted the HDD partition void root and boot: 
```
sudo mkdir -p /mnt/voidrootboot
sudo mount /dev/sdd6 /mnt/voidrootboot
```
2. Mounted `dev, sys, proc` of the host/rescue OS  for dracut operation:
```
sudo mount --bind /sys/ /mnt/voidrootboot/sys/
sudo mount --bind /proc/ /mnt/voidrootboot/proc/
sudo mount --rbind /dev/ /mnt/voidrootboot/dev/
```
Please note that dracut needs /dev to be recursively mounted for the use of /dev/pts. Kudos to @ahesford for this hint.

4. Chrooted into the mounted partition:
```
chroot /mnt/voidrootboot
```
5. Make necessary changes:
`echo 'omit_dracutmodules+=" zfs "' > /etc/dracut.conf.d/zfs.conf`

Please do not skip the space around the module name, `zfs`. 

6. Rebuild initramfs:
```
sudo xbps-reconfigure -f zfs
```

7. Successfully built and good to go. Back to voidlinux. :D

**Comment by ihameed** [comment]
> This is definitely a duplicate of #37667. Unfortunately, the only way to fix your initramfs is to grab a live image (I prefer [hrmpf](https://github.com/leahneukirchen/hrmpf)), mount your root and `/boot`, chroot in, add the change to the Dracut configuration, and then regenerate all initramfs images. (The easiest way to do that is `xbps-reconfigure -f zfs`.)

I had (and worked around locally before discovering https://github.com/void-linux/void-packages/issues/37667) this same problem. I didn't have any spare bootable media handy to use for a recovery image. Another way to get your full multi-user setup running so that you can rebuild this initramfs shell script convolution is to manually `mount /dev/path/to/my/root/volume /sysroot` in the dracut recovery shell. Then type `exit`. Startup should resume normally.
