### ISSUE TITLE
Package request: Update Rclone to version 1.58.1

### ISSUE THREAD

**Issue by circulocuadrado** [void-linux/void-packages#37767]
### Package name

Rclone

### Package homepage

https://rclone.org/

### Description

Repository is outdated with version v1.57.0

( I dont know if I have to request this update using another option. Let me know if I am wrong. )

![Screenshot_2022-06-30_11-11-49](https://user-images.githubusercontent.com/107956387/176786970-92ea1028-7a81-4f6b-9edc-8c6551a845db.png)
.

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by Chocimier** [comment]
Don't request an update of a package, [We have a script for that](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.
