### ISSUE TITLE
Package request: libfcitx-qt6

### ISSUE THREAD

**Issue by leesongun** [void-linux/void-packages#37798]
### Package name

libfcitx-qt6

### Package homepage

https://github.com/fcitx/fcitx-qt5

### Description

libfcitx-qt6 adds fcitx support for Qt6 programs. It shares repository with libfcitx-qt5.

### Does the requested package meet the quality requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by sgn** [comment]
Hello, `fcitx` is possibly dead. Please use `fcitx5` instead.

**Comment by leesongun** [comment]
My experience with fcitx5 (fcitx5-hangul specifically) was quite buggy, problems including compositing being one keystroke behind what I type. After some search, I think this problem is not unique to me. ([Source](https://www.nemonein.xyz/2022/01/6265/))

**Comment by sgn** [comment]
Ah, I see.

Strangely, I experienced this problem with both `fcitx` and `fcitx5`. I only know some Vietnamese, Chinese, Japanese and English, so I guess it varies.

I will look into updating `libfcitx-qt5` and adding `libfcitx-qt6`

**Comment by leesongun** [comment]
Thank you for understanding! :)

**Comment by sgn** [comment]
@leesongun please help to test #37898
