### ISSUE TITLE
package qt5-speech-devel : wrong so numbering in Qt5TextToSpeechConfig.cmake

### ISSUE THREAD

**Issue by yopito** [void-linux/void-packages#37815]
### Is this a new report?

Yes

### System Info

Void 5.15.47_1 x86_64-musl GenuineIntel notuptodate hold rrnDFFFFFFFF

### Package(s) Affected

qt5-speech-devel-5.15.4_1

### Expected behaviour

file `/usr/lib/cmake/Qt5TextToSpeech/Qt5TextToSpeechConfig.cmake` is supposed to point "release" 5.15.4

### Actual behaviour

file `/usr/lib/cmake/Qt5TextToSpeech/Qt5TextToSpeechConfig.cmake` is pointing release 5.15.2  instead of 5.15.4:

```
[packages]$ xbps-query -R --cat /usr/lib/cmake/Qt5TextToSpeech/Qt5TextToSpeechConfig.cmake qt5-speech-devel | cat -n | grep 5.15
     8	set(Qt5TextToSpeech_VERSION_STRING 5.15.2)
    56	        "${_qt5TextToSpeech_install_prefix}/include/qt5/QtTextToSpeech/5.15.2"
    57	        "${_qt5TextToSpeech_install_prefix}/include/qt5/QtTextToSpeech/5.15.2/QtTextToSpeech"
   100	                5.15.2 ${_Qt5TextToSpeech_FIND_VERSION_EXACT}
   201	    _populate_TextToSpeech_target_properties(RELEASE "libQt5TextToSpeech.so.5.15.2" "" FALSE)
   206	    # In Qt 5.15 the glob pattern was relaxed to also catch plugins not literally named Plugin.
```
Edit: we are talking of this package
```
$ xbps-query -R qt5-speech-devel
architecture: x86_64-musl
filename-sha256: 3e0f2a9b8715d1e396135f124aade17dc462926bff0903f4cb3ab141a928d818
filename-size: 9474B
homepage: https://qt.io/
installed_size: 35KB
license: GPL-3.0-or-later, LGPL-3.0-or-later
maintainer: John <me@johnnynator.dev>
pkgname: qt5-speech-devel
pkgver: qt5-speech-devel-5.15.4_1
repository: https://repo-default.voidlinux.org/current/musl
...
source-revisions: qt5-speech:45d6e214b9
```

### Steps to reproduce

rebuild `python2-pyside2` package. I did not formally checked it since I'm working on 5.15.5's packaging of `python2-pyside2`.

ping @Piraty

**Comment by yopito** [comment]
BTW, It seems that upstream provide 5.15.5 now ?
I see git tag v5.15.5-lts-lgpl (https://invent.kde.org/qt/qt/qtspeech/-/commits/v5.15.5-lts-lgpl), don't know if it's relevant.

**Comment by yopito** [comment]
ah: `srcpkgs/qt5-speech/files/Qt5TextToSpeechConfig.cmake` is installed instead of the one from source.

**Comment by Piraty** [comment]
d112bdca320414a5caf5638f28d7ca73906ea4a5
