### ISSUE TITLE
xbps-src show-build-deps breaks with version restrictions

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#37837]
For example openocd has jimtcl in makedepends, but it's version restricted: `jimtcl-devel>=0.81_1<=0.81_9999`
```
%: ./xbps-src show-build-deps openocd
=> ERROR: openocd-0.11.0+1_1: dependency 'jimtcl-devel>=0.81_1<=0.81_9999' does not exist!
```
show-build-deps should understand version restrictions and not throw an error.

**Comment by Duncaen** [comment]
Its simply not allowed in `hostmakedepends` or `makedepends` they always depend on the version we have the template for.
