### ISSUE TITLE
Package request: 7zip

### ISSUE THREAD

**Issue by rilysh** [void-linux/void-packages#37875]
### Package name

7zip

### Package homepage

https://sourceforge.net/projects/sevenzip/files/7-Zip/

### Description

7-Zip is an open source file archiver, supports compression and decompression including 7z, xz bzip2, zip, gzip, tar out of the box.

### Does the requested package meet the quality requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by wael444** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/p7zip/template

do you mean this is a GUI 7z?

**Comment by wael444** [comment]
> This can replace p7zip, which is now outdated and abandoned.

wait what? oh my god it is, last update 2007-02-04
i will try to get this into a package asap

**Comment by wael444** [comment]
i had tried to take a look at the source in it, seems it is quite difficult and doesnt have a straight forward makefile
you might have to have a if for every architecture as it has binary builds for 4 architectures

**Comment by classabbyamp** [comment]
binary builds are not something we'd want in the repos if source is available
