### ISSUE TITLE
Gnome-shell high cpu usage together with ibus-daemon

### ISSUE THREAD

**Issue by Haagen-Dazs** [void-linux/void-packages#37959]
### Is this a new report?

Yes

### System Info

Void 5.18.9_1 x86_64 AuthenticAMD uptodate FFF

### Package(s) Affected

gnome-shell-42.3_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://gitlab.gnome.org/GNOME/gnome-shell/-/raw/gnome-42/NEWS
https://github.com/archlinux/svntogit-packages/commit/98764bf87ae868c1654e55689b47880542087609

I believe this was fixed in 42.3.1, using this version on arch on the same machine and cpu usage is normal

### Expected behaviour

minimal cpu usage in idle

### Actual behaviour

high cpu usage in idle

### Steps to reproduce

1. update system
2. login (wayland session)
3. htop

![image](https://user-images.githubusercontent.com/43646927/178133179-ab3c26dd-0c39-4567-90ad-374271b2d9a3.png)

**Comment by oreo639** [comment]
> Does a report exist for this bug with the project's home (upstream) and/or another distro?

We already apply that patch. That is for a different issue (which resulted in typing suggestions not appearing in the ibus popup).

If you create a new user account, do you still have the same issue?
Also, does this occur over a period of time or immediately after logging in?

**Comment by Haagen-Dazs** [comment]
I tested it with htop using gnome-terminal and the cpu usage is low, apparently this issue happens only with kitty terminal.

**Comment by oreo639** [comment]
Ah, you are right.

https://github.com/kovidgoyal/kitty/issues/5105
