### ISSUE TITLE
Include "qt5-svg" as a dependency of PolyMC.

### ISSUE THREAD

**Issue by TeknosQuet** [void-linux/void-packages#37960]
### Is this a new report?

Yes

### System Info

Void 5.18.9_1 x86_64 GenuineIntel uptodate rFFFFFFF

### Package(s) Affected

PolyMC-1.3.2_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

N/A

### Expected behaviour

When opening PolyMC, everything including the icons should show up in the launcher.
![image](https://user-images.githubusercontent.com/40285364/178133719-d98104a3-dd9c-49ee-aa01-106c09b869d2.png)
![image](https://user-images.githubusercontent.com/40285364/178133720-143d218d-6d3e-4a90-9d4d-4cfb87436e8f.png)

### Actual behaviour

After opening PolyMC, the vast majority of icons are missing. Installing `qt5-svg` fixes the issue.
![image](https://user-images.githubusercontent.com/40285364/178133696-7a8cd6bd-e811-43f1-867d-15468ccb5f48.png)
![image](https://user-images.githubusercontent.com/40285364/178133702-7c16c3df-82f8-4b42-ba6b-7373a62e8919.png)

### Steps to reproduce

1. Install PolyMC doing `sudo xbps-install PolyMC`.
2. Open PolyMC.
3. The launcher pops up with a lack of PolyMC icons (if you do not have the qt5-svg package).

**Comment by paper42** [comment]
@oynqr
