### ISSUE TITLE
Package request: 

### ISSUE THREAD

**Issue by InfRandomness** [void-linux/void-packages#37961]
### Package name

llvm

### Package homepage

https://github.com/llvm/llvm-project

### Description

The package already exists, but it was to track and eventual upgrade to 14.0.6

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by InfRandomness** [comment]
I could work on this upgrade

**Comment by hervyqa** [comment]
Don't request an update of a package, [We have a script for that](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.

**Comment by InfRandomness** [comment]
> Don't request an update of a package, [We have a script for that](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.

My bad, I didn't know :grimacing:
