### ISSUE TITLE
`Package request:` GNOME Extension Manager

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#37976]
### Package name

extension-manager

### Package homepage

https://github.com/mjakeman/extension-manager

### Description

A native tool for browsing, installing, and managing GNOME Shell Extensions.

Written with GTK 4 and libadwaita.

The tool supports:

    Browsing and searching extensions from extensions.gnome.org
    Installation and Removal
    Enabling and Disabling
    Updating in-app
    Screenshots & Images
    Ratings & Comments
    Translations

### Does the requested package meet the quality requirements?

System, Required

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/05ac8a473c0e7dc9fba8669a7a79d9b69c3289f2
