### ISSUE TITLE
SHA256 mismatch for python-2.7.18.5

### ISSUE THREAD

**Issue by lfdebrux** [void-linux/void-packages#37978]
### Is this a new report?

No

### System Info

Void 5.15.41_1 x86_64-musl GenuineIntel uptodate rFFFF

### Package(s) Affected

python-2.7.18.5_1

### Expected behaviour

The shasum in `srcpkgs/python/template` matches the hash of the downloaded binary.

### Actual behaviour

I get the following error:

```
=> python-2.7.18.5_1: verifying checksum for distfile 'v2.7.18.5.tar.gz'...
=> ERROR: SHA256 mismatch for 'v2.7.18.5.tar.gz:'
e5e80ae00e20994150f2acfe4acfc541cbe6e4e77d334e1e7f9f33f303ab89ba
=> ERROR: python-2.7.18.5_1: couldn't verify distfiles, exiting...
```

### Steps to reproduce

1. Get latest void-packages repo
2. `./xbps-src fetch python`

**Comment by lfdebrux** [comment]
I'm not sure how this happened, but I note that the last change to the python template (https://github.com/void-linux/void-packages/commit/1c93498810ba791da5d01d89913a883f0bce6cdf) was 12 days ago, while the relevant tag on the upstream repo (https://github.com/ActiveState/cpython/releases/tag/v2.7.18.5) was according to GitHub updated 10 days ago.

So maybe the release was updated for some reason? No idea how to check why it was though, or whether it was supposed to be.

**Comment by sgn** [comment]
Only change is vendor expat:
```
M	cpython-2.7.18.5/Modules/expat/ascii.h
M	cpython-2.7.18.5/Modules/expat/asciitab.h
M	cpython-2.7.18.5/Modules/expat/expat.h
M	cpython-2.7.18.5/Modules/expat/expat_external.h
M	cpython-2.7.18.5/Modules/expat/iasciitab.h
M	cpython-2.7.18.5/Modules/expat/internal.h
M	cpython-2.7.18.5/Modules/expat/latin1tab.h
M	cpython-2.7.18.5/Modules/expat/nametab.h
M	cpython-2.7.18.5/Modules/expat/pyexpatns.h
M	cpython-2.7.18.5/Modules/expat/siphash.h
M	cpython-2.7.18.5/Modules/expat/utf8tab.h
M	cpython-2.7.18.5/Modules/expat/winconfig.h
M	cpython-2.7.18.5/Modules/expat/xmlparse.c
M	cpython-2.7.18.5/Modules/expat/xmlrole.c
M	cpython-2.7.18.5/Modules/expat/xmlrole.h
M	cpython-2.7.18.5/Modules/expat/xmltok.c
M	cpython-2.7.18.5/Modules/expat/xmltok.h
M	cpython-2.7.18.5/Modules/expat/xmltok_impl.c
M	cpython-2.7.18.5/Modules/expat/xmltok_impl.h
M	cpython-2.7.18.5/Modules/expat/xmltok_ns.c
```

Not worth a rebuild, but checksum must be changed.

**Comment by sgn** [comment]
3dd253ed422f6eabb56daea8b41077edf912cd64
