### ISSUE TITLE
`Package request:` GNOME Console

### ISSUE THREAD

**Issue by pc00per** [void-linux/void-packages#37975]
### Package name

gnome-console

### Package homepage

https://gitlab.gnome.org/GNOME/console

### Description

A minimal terminal for GNOME
Console is supposed to be a simple terminal emulator for the average user to carry out simple cli tasks and aims to be a ‘core’ app for GNOME/Phosh
We are not however trying to replace GNOME Terminal/Tilix, these advanced tools are great for developers and administrators, rather Console aims to serve the casual linux user who rarely needs a terminal

### Does the requested package meet the quality requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment]
We are waiting for a stable release and for them to important bugs: #36445

**Comment by rivanfebrian123** [comment]
OOT: Well, we got some additional works to do: https://medium.com/@fulalas/gnome-42-the-nonsense-continues-7d96c3287f7

**Comment by paper42** [comment]
> OOT: Well, we got some additional works to do: https://medium.com/@fulalas/gnome-42-the-nonsense-continues-7d96c3287f7

We will switch the default terminal emulator in GNOME to gnome-console when it's ready and gnome-terminal will be available for forseeable future.

**Comment by pc00per** [comment]
> OOT: Well, we got some additional works to do: https://medium.com/@fulalas/gnome-42-the-nonsense-continues-7d96c3287f7

This is truely bad. They introduced console as a new terminal, but without libadwaita & GTK4... XD

**Comment by classabbyamp** [comment]
done in #36445
