### ISSUE TITLE
Anki is out of date. Why?

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#37981]
Hi. The latest version of anki is `2.1.54`:
https://github.com/ankitects/anki/releases/tag/2.1.54

But the version in void repo is: `2.1.15`

Why we didn't upgrade this package to the latest version? Is there any technical issue?

**Comment by akhiljalagam** [comment]
IMO, You can just update the version number and checksum in anki/template and create a PR.

**Comment by paper42** [comment]
Don't request an update of a package, [We have a script for that](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help. Updating anki is not trivial because of their build system.

**Comment by alexscarter** [comment]
Hello, I'm curious if this is still the case with Anki v25. I noticed they mentioned in [25.07.4](https://github.com/ankitects/anki/releases/tag/25.07.4) that they changed the way anki is packaged, but I'm not certain if that makes it easier to update as a void package. Either way, it's extremely easy to run their installer on void, and I found no issues on x86_64 glibc.

**Comment by sgn** [comment]
It's extremely easy to run any installer on anything. I can even run M$FT Office Installer ;)

**Comment by Datastreamx** [comment]
I've been trying to make a package for this but it keeps failing at various stages. Anki's way of building is weird from a package manager perspective imo. In some tests it assumes that the tests are run as nonroot but xbps is root. It uses ninja but has a rust build runner in it that also runs python tests and builds and cargo runs. Oh and it also use npm in there. 
Their documentation on how to make a package are nonexistent. It says to do ./ninja and it'll be fine but even if you do that locally, it never spits out a compiled thing you could reasonably package. Did I mention that none of their dependencies are really mentioned anywhere clearly? You have to sleuth through multiple cargo and pyproject tomls to figure out but they also generate tomls on the fly so the only real way is to try to build and see it fail on something then add that as a dependency, rinse n repeat.

The documentation on building it from git is basically use "./run" or "./ninja"

Their official line is to use the precompiled package and just run ./install.sh from that. But that is not how void wants things. 
(That's not how any distro wants it to be.) It wants to compile from source so it can handle musl and the like.

What I've been seeing is that other distros have struggled with anki for years as well. 

Their new way of building might be easier but it's still not easy.

Might just cheat and look at how they do it on arch, assuming they've made a package for it by now. Arch is usually fastest.

**Comment by nazaradeh** [comment]
Hey all, I opened a PR to finally get an update to anki in. I'd appreciate any reviews to help get this in sooner!

https://github.com/void-linux/void-packages/pull/61528
