### ISSUE TITLE
`Package request:` Ventoy - Bootable USB Solution

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#37999]
### Package name

ventoy

### Package homepage

https://github.com/ventoy/Ventoy/releases

### Description

Ventoy is an open source tool to create bootable USB drive for ISO/WIM/IMG/VHD(x)/EFI files.
With ventoy, you don't need to format the disk over and over, you just need to copy the ISO/WIM/IMG/VHD(x)/EFI files to the USB drive and boot them directly.
You can copy many files at a time and ventoy will give you a boot menu to select them ([screenshot](https://www.ventoy.net/en/screenshot.html)).
You can also browse ISO/WIM/IMG/VHD(x)/EFI files in local disks and boot them.
x86 Legacy BIOS, IA32 UEFI, x86_64 UEFI, ARM64 UEFI and MIPS64EL UEFI are supported in the same way.
Most types of OS supported (Windows/WinPE/Linux/ChromeOS/Unix/VMware/Xen...)

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by wael444** [comment]
i had tried to package this but got distracted looking at how bad the shell scripting was.
i will attempt to package this.

but i will say its a maybe this would get accepted.

**Comment by pc00per** [comment]
> packages are preferred to be built from source

Preferred but not mandatory right. It's the same old discussion with browsers & office suites, caz they consume huge time to build from source. Ventoy might be a small application. But because it's a headache to package from source, why not package the binary...

**Comment by wael444** [comment]
i really don't have a choice. guess i can do a binary package..

**Comment by wael444** [comment]
disabling stripping the packages and having `nopie=yes` doesn't help with the binaries.

i need a higher up to choose:
+ should this be compiled from source or to be binary?
+ should the parts of ventoy (Web,GUI,QT5) be split into seperate packages?

**Comment by pc00per** [comment]
> should this be compiled from source or to be binary?

If you have time & patience, why not ;b
> should the parts of ventoy (Web,GUI,QT5) be split into seperate packages?

Probably **should**.
If you have difficulty packaging it, it's okay anyways. This ain't that important as of now.

**Comment by classabbyamp** [comment]
> Preferred but not mandatory right

if the source is available, it's almost mandatory

**Comment by wael444** [comment]
@classabbyamp ,

https://github.com/ventoy/Ventoy/blob/master/DOC/BuildVentoyFromSource.txt

building from source requires building grub, musl, dietlibc,aarch64-uclibc, from source and putting them in the ventoy source directory, how would we go about building this for x86_64 anyway?

**Comment by Ved-un** [comment]
Why create a package if there are working binary?
https://www.ventoy.net/en/download.html

**Comment by pc00per** [comment]
> Why create a package if there are working binary? https://www.ventoy.net/en/download.html

Caz package maintainers think sticking towards application sources help users thinking they using legit software.
I think this misconception of source only packaging should go away when we have precompiled binaries from author's source pages.

**Comment by classabbyamp** [comment]
> Why create a package if there are working binary?

1. **compatibility**: void has musl, which almost no upstream creates binaries for, and sometimes upstream-created binaries will link to different versions of libraries than void has (or statically link to them, which is largely a waste of space)
2. **hardening and optimisation**: void enables a set of compiler flags that ensure packages have certain optimisations, hardening measures, and compatibility with all possible targets
3. **ease of use for users**: having a package in the repos means users don't have to manually deal with updates aside from `xbps-install -Su`
4. **trust**: users don't have to decide whether they trust the binaries from some random dev's download page if they choose to trust the maintainers of their distro

**Comment by pc00per** [comment]
@classabbyamp You forgot the main reason. Skipping binary uploads into void's servers which'll probably free their load & bandwidth.

**Comment by classabbyamp** [comment]
https://github.com/ventoy/Ventoy/issues/2795
