### ISSUE TITLE
vscode closes (or crashes?) when clicking the "File" tab 

### ISSUE THREAD

**Issue by RicArch97** [void-linux/void-packages#38005]
### Is this a new report?

Yes

### System Info

Void 5.18.9_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFFFFFFFFFFF

### Package(s) Affected

vscode-1.69.0_1

### Expected behaviour

Clicking the "File" tab opens it's respective menu

### Actual behaviour

vscode closes or crashes. I couldn't find anything related to a crash in the logs under `~/.config/Code - OSS`, though.

### Steps to reproduce

1. Open code-oss
2. Click the "File" tab top left

**Comment by brxken128** [comment]
I can confirm this is reproducible, and I've detailed/shown a little more of the issues in my post [here](https://github.com/void-linux/void-packages/pull/36991#issuecomment-1180691444).

I can provide logs and such if required - anything to help out.

**Comment by RicArch97** [comment]
Apparently all those Electron processes stick around after the crash, i only noticed when about 30% of my 32GB ram was left-over electron19 processes all from accidentally clicking that button haha.

Anyways, @brxken128 to follow up on your [comment](https://github.com/void-linux/void-packages/pull/36991#issuecomment-1180691444), vscode does indeed feel quite sluggish as well. I enabled ozone-wayland hoping it would feel just as smooth and fast as Chromium and Google-Chrome on the Wayland backend, but that wasn't the case unfortunately.

Anyways, i just tested vscode 1.69 on an other machine which runs arch linux, and there were no issues there. However, i use the binary package directly from microsoft. I wonder if that's a better approach, since it comes bundled with it own electron version (18.3.5)

**Comment by negativeExponent** [comment]
@brxken128 replying from your comment, im using bspwm, so the issue is not exclusive to gnome.

**Comment by brxken128** [comment]
This is quite an odd issue, maybe it's something regarding the electron version jump?

> However, i use the binary package directly from microsoft

I don't agree that this would be a good solution for the long-term, although it'd be enough to get people on their feet I suppose. Provided VSCodium itself (from their repo) still runs fine, I'll probably end up using that (and recommending it to others).

For more information about my setup:

* Proprietary Nvidia drivers
* glibc
* Kernel `5.18.9_1`
* X11
* Vscode 1.66 works fine (but rust-analyzer requires 1.67 or above)
* gnome 42

I can provide logs or anything if required.

**Comment by sink666** [comment]
I started having the same issue after updating my system yesterday. currently on:
- gnome 42.2
- wayland
- kernel 5.18.9_1
- electron19-19-19.0.8_1
- glibc

I could provide relevant logs on request or zip up the whole folder and send it along. nothing seems to have been dumped though.

**Comment by atk** [comment]
Was able to reproduce myself; I rarely use the command line. @shizonic, do you have any ideas?

**Comment by RicArch97** [comment]
Good solution in the meantime is getting VSCodium from GitHub, which is also FOSS, if you really want to use version 1.69. Could even use `xdeb` to create an xbps package from the `.deb` and install that, if you prefer that.

**Comment by shizonic** [comment]
> Good solution in the meantime is getting VSCodium from GitHub, which is also FOSS, if you really want to use version 1.69. Could even use `xdeb` to create an xbps package from the `.deb` and install that, if you prefer that.

I did already package it in the past but prebuilt binaries aren't that welcome for the void devs. Which is understandable.

**Comment by shizonic** [comment]
I updated vscode to 1.69.1 and rebuilt it with the mentioned electron fixes: https://github.com/void-linux/void-packages/pull/38035. This works for me without any issues.

**Comment by shizonic** [comment]
@Johnnynator Indeed. Big thx from me too of course!

@negativeExponent We have to rebuild anyway due the update to 1.69.1.
