### ISSUE TITLE
Package request: apple-fonts

### ISSUE THREAD

**Issue by Erennedirlo** [void-linux/void-packages#38013]
### Package name

apple-fonts

### Package homepage

https://aur.archlinux.org/apple-fonts.git

### Description

Can you please make the package for apple-fonts, it has great apple fonts such as SF Mono. From what i saw, there isn't any package for that on Void Linux.

### Does the requested package meet the quality requirements?

Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment]
> ### Does the requested package meet the quality requirements?
> 
> Compiled

Fonts are not compiled and this is would be a nonfree and restricted package.

> New fonts may be accepted if they provide value beyond aesthetics (e.g. they contain glyphs for a script missing in already packaged fonts).

I don't think this meets quality requirements, does it?

> ### Is the requested package released?
> 
> Yes

I don't think they have releases.

**Comment by hervyqa** [comment]
> I don't think this meets quality requirements, does it?
> 
> > ### Is the requested package released?
> > 
> > Yes
> 
> I don't think they have releases.

right. it's like `msttcorefonts` package

**Comment by misuchiru03** [comment]
Checking Apple's site, if I am not mistaken, it's not only nonfree, but far more restrictive:

> * "A. Limited License. Subject to the terms of this License, you may use the Apple Font solely for creating mock-ups of user interfaces to be used in software products running on Apple’s iOS, iPadOS, macOS or tvOS operating systems, as applicable. The foregoing right includes the right to show the Apple Font in screen shots, images, mock-ups or other depictions, digital and/or print, of such software products running solely on iOS, iPadOS, macOS or tvOS. Your use of the Apple Font shall also be subject to any specific use restrictions with respect thereto as set forth in the Apple Font or Apple’s Human Interface Guidelines.
> 
> 
> 
> You may use this Apple Font only for the purposes described in this License and **only if you are a registered Apple Developer, or as otherwise expressly permitted by Apple in writing."

If I am mistaken on the legaleze above, forgive me.

**Comment by classabbyamp** [comment]
agree on that assessment
