### ISSUE TITLE
php-7.4.30_2 missing gd extension in php.ini

### ISSUE THREAD

**Issue by Preferencesoft** [void-linux/void-packages#38028]
In the file, `php.ini` there is the **gd2** extension, but it does not correspond to the `php-gd` package. Could you possibly add  the **gd** extension (or replace **gd2** by **gd**):

    ;extension=gd
    ;extension=gd2

Thanks in advance.

**Comment by Preferencesoft** [comment]
It's up to you.

**Comment by Preferencesoft** [comment]
The **gd2** module does not exist in the packages and I couldn't tell if it's another version of the  module. I just needed **gd** and noticed this inconsistency in the `php.ini` where there is no reference to **gd**.

**Comment by classabbyamp** [comment]
I believe the reason why it's called `gd2` in php 7.4 is because that's what the windows dll was called until php 8.0 (when the naming was unified on all platforms). Not sure how the php.ini is generated but I bet there's some bad logic there.
