### ISSUE TITLE
Polybar won't start and won't build

### ISSUE THREAD

**Issue by Swomp2** [void-linux/void-packages#38046]
### Is this a new report?

Yes

### System Info

Void 5.18.9_1 x86_64 AuthenticAMD notuptodate FFF

### Package(s) Affected

polybar-3.6.3_1 jsoncpp-devel-1.9.4_2 jsoncpp-1.9.4_2

### Expected behaviour

I think that the bar can replace i3status.

### Actual behaviour

The bar gives this error message:
`error while loading shared libraries: libjsoncpp.so.24: cannot open shared object file: No such file or directory`

If I change libjsoncpp.so to libjsoncpp.so.24 like that:
`sudo mv /usr/lib/libjsoncpp.so /usr/lib/libjsoncpp.so.24`
and try to build or start polybar I've got this issue:
`polybar: error while loading shared libraries: libjsoncpp.so.24: cannot open shared object file: Error 40`

### Steps to reproduce

1. Installation
2. Execution
3. Fail
4. Attempt to fix
5. Nothing

**Comment by oreo639** [comment]
> If I change libjsoncpp.so to libjsoncpp.so.24 like that:
> `sudo mv /usr/lib/libjsoncpp.so /usr/lib/libjsoncpp.so.24`

Do not do that. `libjsoncpp.so` is only for use when compiling, `libjsoncpp.so.24` is for use when running the application. (`libjsoncpp.so` is a symbolic link to `libjsoncpp.so.24` so if you rename it it will never be able to be resolved)

I cannot reproduce this issue.
Try `# xbps-install -f jsoncpp jsoncpp-devel`
You can use `# xbps-pkgdb -a` to verify the status of your other packages.

**Comment by Swomp2** [comment]
> Do not do that. `libjsoncpp.so` is only for use when compiling, `libjsoncpp.so.24` is for use when running the application. (`libjsoncpp.so` is a symbolic link to `libjsoncpp.so.24` so if you rename it the link will just link to itself)
> 
Oh, I didn't know

> I cannot reproduce this issue. Try `# xbps-install -f jsoncpp jsoncpp-devel` You can use `# xbps-pkgdb -a` to verify the status of your other packages.
This works, thank you.
