### ISSUE TITLE
Package request: geekbench

### ISSUE THREAD

**Issue by Erennedirlo** [void-linux/void-packages#38095]
### Package name

geekbench

### Package homepage

https://www.geekbench.com/

### Description

Geekbench/Geekbench 5 is a cpu benchmarking tool. It is used across many different benchmarking websites.
<img width="1088" alt="Geekbench-windows-download-free-pc" src="https://user-images.githubusercontent.com/80172441/179349872-53767269-3a9c-4e59-ac47-c65fd1b260bb.png">

### Does the requested package meet the quality requirements?

Compiled

### Is the requested package released?

Yes

**Comment by tranzystorek-io** [comment]
This looks like proprietary software with paid licenses, I don't think we package these.

**Comment by Anachron** [comment]
This requires a license ... no?
