### ISSUE TITLE
Blender 3D - Wayland Support 

### ISSUE THREAD

**Issue by jdnumm** [void-linux/void-packages#38128]
### Is this a new report?

Yes

### System Info

Void 5.18.11_1 x86_64 

### Package(s) Affected

blender-3.0.0_4

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

There is a document with additional information here:

https://developer.blender.org/T90676
    
I think `WITH_GHOST_WAYLAND` should set on build time.

### Expected behaviour

Support Wayland

### Actual behaviour

Runs under X11

### Steps to reproduce

1. Install and run under Wayland

**Comment by classabbyamp** [comment]
based on how that issue describes the current state of blender, it seems that this might cause issues/weird behaviour on X:

![image](https://user-images.githubusercontent.com/5366828/179627441-5c8e7650-c6f7-4dd0-8213-98e9ab6eca9c.png)

first line is the default, second line is not possible for the distro package, third line seems like the way to go.

IMO, I think we can't do much until the proposed solution is implemented, allowing us to enable both compile-time flags and allowing wayland users to select it at runtime.

Maybe someone who uses blender and knows more about it can shed some light on this.

**Comment by NiseVoid** [comment]
As far as I can tell blender 3.4 should have fixed the issue of not being able to support both X11 and wayland at the same time, and it looks like it released just under a month ago.

Setting the `WITH_GHOST_WAYLAND` flag on the build might be all that's needed, since I have locally built blender by modifying the template to add the wayland one and remove any conflicting flags (which were X11 and GLEW iirc). I also needed to add some wayland related depends and makedepends.

I am however not sure if there would be any other issues with updating blender.  I assume that at the very least the paches would have to be updated.

**Comment by mhmdanas** [comment]
I don't know if it's related to me running Wayland (Sway) or not, but I get this error when I try to run Blender:

```console
$ blender
EGL Error (0x3009): EGL_BAD_MATCH: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a valid surface).
EGL Error (0x3009): EGL_BAD_MATCH: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a valid surface).
EGL Error (0x3009): EGL_BAD_MATCH: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a valid surface).
EGL Error (0x3009): EGL_BAD_MATCH: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a valid surface).
EGL Error (0x3009): EGL_BAD_MATCH: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a valid surface).
EGL Error (0x3009): EGL_BAD_MATCH: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a valid surface).
EGL Error (0x3009): EGL_BAD_MATCH: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a valid surface).
EGL Error (0x3009): EGL_BAD_MATCH: Arguments are inconsistent (for example, a valid context requires buffers not supplied by a valid surface).
Warning: No OpenGL vendor detected.
Writing: /tmp/blender.crash.txt
fish: Job 1, '/bin/blender' terminated by signal SIGSEGV (Address boundary error)
```

Here are the contents of /tmp/blender.crash.txt:

```
# Blender 3.4.1, Unknown revision

# backtrace

# Python backtrace
```

Any idea how I can fix this?

**Comment by Channpyae** [comment]
I got the same output as mhmdanas. You guys know how to fix it?

**Comment by JetpackJackson** [comment]
I'm getting the same output, how do we fix it?

**Comment by Channpyae** [comment]
> I'm getting the same output, how do we fix it?

I tested version 3.3, 3.4 LTS and 3.6 LTS zip files on linux(both manjaro and arch)(wayland). It runs well. The problem starts from version 4. I think version 4 is not stable yet. I'm running on cpu, btw.
