### ISSUE TITLE
MongoDB broken by recent update

### ISSUE THREAD

**Issue by localhost** [void-linux/void-packages#3812]
MongoDB has the library WiredTiger as a dependency. A recent change in either of the packages or build templates broke MongoDB when using WiredTiger as an engine, because it depends on having a verbose flag available in `wiredtiger_open`.

Therefore we have to add `--enable-verbose` to the WiredTiger compilation flags.

See pull request #3811

**Comment by seisatsu** [comment]
Confirmed on my end.

**Comment by Gottox** [comment]
Please retry.
