### ISSUE TITLE
pipewire-0.3.55_2 required changes to /etc/sv/pipewire-pulse for systemwide pipewire-pulse to work

### ISSUE THREAD

**Issue by datenwolf** [void-linux/void-packages#38189]
After updating to pipewire-0.3.55_2 `pipewire-pulse` unconditionally sets `chmod("/run/pulse", 0700);` thereby shutting out any PA client not running as `PID == _pipewire`. To mitigate this I changed `/etc/sv/pipewire-pulse/run` to this:

```
#!/bin/sh
# this service is experimental and most setups should start pipewire as a user,
# for further information, please refer to the handbook
if [ -d /run/pulse ] ; then
	chown 0:_pipewire /run/pulse
	chmod 1775 /run/pulse
else
	install -m 1775 -g 0 -o _pipewire -d /run/pulse
fi
umask 002
export PULSE_RUNTIME_PATH=/run/pulse
exec chpst -u _pipewire:_pipewire pipewire-pulse
```

Using this runit `run` script things work again; in my case this means I can listen to music with systemwide MPD, while having a simultaneous separate Work-from-Home user session running with WebEx meetings audio *and* OBS running as my main user recording everything (i.e. I *want* the different sessions to share audio!)

**Comment by paper42** [comment]
@st3r4g @lemmi

**Comment by lemmi** [comment]
In the recent versions, the default `pipewire-pulse.conf` added a call to `pactl`. Removing that also solves the permissions problem. 
```bash
cp /usr/share/pipewire/pipewire-pulse.conf /etc/pipewire/pipewire-pulse.conf
```
Then comment out the line 
```
{ path = "pactl"        args = "load-module module-always-sink" }
```

**Comment by classabbyamp** [comment]
we no longer ship a pipewire-pulse system service
