### ISSUE TITLE
Package request: Airspy HF+

### ISSUE THREAD

**Issue by BT-Justice** [void-linux/void-packages#38198]
### Package name

airspyhf

### Package homepage

https://github.com/airspy/airspyhf

### Description

Airspy HF+ is a high-performance SDR which offers HF coverage between 0.5 kHz - 31 MHz and VHF coverage between 60 MHz - 260 MHz.

https://airspy.com/airspy-hf-discovery/

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
are the `airspy`, `libairspy`, or `SoapyAirspy` packages not compatible with the airspy HF+?

**Comment by BT-Justice** [comment]
No they are not.  The Airspy HF+ is an entirely different SDR.  Actually there are two models, but the airspyhf software works for both.
