### ISSUE TITLE
Package request: Gqrx

### ISSUE THREAD

**Issue by BT-Justice** [void-linux/void-packages#38199]
### Package name

gqrx

### Package homepage

https://github.com/gqrx-sdr/gqrx/releases

### Description

This needs updated badly.  The latest version is 2.15.9.  The current Void version is 2.14.4.

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
please don't make package requests for updates. it's update is also currently in-progress in #35049
