### ISSUE TITLE
SoapySDR outdated

### ISSUE THREAD

**Issue by neoklis** [void-linux/void-packages#38238]
Hi

SoapySDR is now at version 0.8.2 upstream, and I am having trouble compiling a package that depends on
version >= 0.8.0. Void version is still 0.7.2.

Could we please have an upgraded package in the repository?

Thanks!

**Comment by paper42** [comment]
from the issue template:
>  #### Don't request an update of a package,
>  [We have a script for that](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.
