### ISSUE TITLE
Package request: Vita3k

### ISSUE THREAD

**Issue by Nathan-MV** [void-linux/void-packages#38299]
### Package name

vita3k

### Package homepage

https://github.com/Vita3K/Vita3K

### Description

PlayStation Vita emulator

### Does the requested package meet the quality requirements?

Compiled

### Is the requested package released?

No

**Comment by paper42** [comment]
> ### Is the requested package released?
> 
> Yes

Is it? I only see one continuous tag they use for CI.

**Comment by paper42** [comment]
then it doesn't meet our quality requirements
