### ISSUE TITLE
Package request: Bottles

### ISSUE THREAD

**Issue by Nathan-MV** [void-linux/void-packages#38295]
### Package name

bottles

### Package homepage

https://github.com/bottlesdevs/Bottles

### Description

Easily manage wine and proton prefix creating bottles using preconfigured environments or create your own with a GTK interface

### Does the requested package meet the quality requirements?

Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment]
there are two closed PRs about Bottles: #27066, #35282
