### ISSUE TITLE
Package request: fastfetch

### ISSUE THREAD

**Issue by Nathan-MV** [void-linux/void-packages#38293]
### Package name

fastfetch

### Package homepage

https://github.com/LinusDierheimer/fastfetch

### Description

fastfetch is a neofetch-like tool for fetching system information and displaying them in a pretty way. It is written in c to achieve much better performance. It also uses mechanisms like multithreading and caching to finish as fast as possible.

### Does the requested package meet the quality requirements?

Compiled

### Is the requested package released?

Yes

**Comment by tranzystorek-io** [comment]
This is unlikely to be added to void due to quality requirements (see https://github.com/void-linux/void-packages/pull/31361).

YOu can still use the tamplate from my PR if you want 🙂

**Comment by hervyqa** [comment]
> This is unlikely to be added to void due to quality requirements (see #31361).
> 
> You can still use the template from my PR if you want slightly_smiling_face

i tried to compile version 1.6.1 in musl, but it failed.
@tranzystorek-io 

```
[15/79] Building C object CMakeFiles/libfastfetch.dir/src/common/networking.c.o
FAILED: CMakeFiles/libfastfetch.dir/src/common/networking.c.o 
/usr/bin/cc -DFF_HAVE_DBUS=1 -DFF_HAVE_DCONF=1 -DFF_HAVE_EGL=1 -DFF_HAVE_GIO=1 -DFF_HAVE_GLX=1 -DFF_HAVE_IMAGEMAGICK7=1 -DFF_HAVE_LIBPCI=1 -DFF_HAVE_OPENCL=1 -DFF_HAVE_OSMESA=1 -DFF_HAVE_RPM=1 -DFF_HAVE_SQLITE3=1 -DFF_HAVE_VULKAN=1 -DFF_HAVE_WAYLAND=1 -DFF_HAVE_X11=1 -DFF_HAVE_XCB=1 -DFF_HAVE_XCB_RANDR=1 -DFF_HAVE_XFCONF=1 -DFF_HAVE_XRANDR=1 -DFF_HAVE_ZLIB=1 -I/builddir/fastfetch-1.6.1/build -I/builddir/fastfetch-1.6.1/src -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/dconf -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/xfce4/xfconf-0 -I/usr/include/ImageMagick-7 -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2    -fdebug-prefix-map=/builddir/fastfetch-1.6.1=. -Wall -Wextra -Wconversion -flto -fno-fat-lto-objects -std=gnu11 -MD -MT CMakeFiles/libfastfetch.dir/src/common/networking.c.o -MF CMakeFiles/libfastfetch.dir/src/common/networking.c.o.d -o CMakeFiles/libfastfetch.dir/src/common/networking.c.o -c /builddir/fastfetch-1.6.1/src/common/networking.c
/builddir/fastfetch-1.6.1/src/common/networking.c: In function 'ffNetworkingGetHttp':
/builddir/fastfetch-1.6.1/src/common/networking.c:29:24: error: storage size of 'timev' isn't known
   29 |         struct timeval timev;
      |                        ^~~~~
/builddir/fastfetch-1.6.1/src/common/networking.c:29:24: warning: unused variable 'timev' [-Wunused-variable]
ninja: build stopped: subcommand failed.
=> ERROR: fastfetch-1.6.1_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 1
=> ERROR:   in do_build() at common/build-style/cmake.sh:85
xbps-rindex: cannot read repository data: No such file or directory
```

**Comment by tranzystorek-io** [comment]
@hervyqa there's a musl incompatibility for older 32bit time structs, seems this should be addressed upstream

**Comment by LinusDierheimer** [comment]
Author of fastfetch here, just discovered this issue.

1.6.2 and higher does compile with musl now.

Also i wouldn't consider fastfetch a simple clone of neofetch, as it has features neofetch is lacking. It also is better in detecting some things. And mainly it is a lot faster, for example putting it in .bashrc etc is much more sane than neofetch, which would noticeable impact shell start time.

**Comment by brian6932** [comment]
Any chance of this getting revived?

**Comment by Bnyro** [comment]
I think that adding this package should be reconsidered due to the fact that `neofetch` (which seems to be the only real alternative that's currently in the repositories) is unmaintained for 3 years and additionally got archived some days ago.

Neofetch will no longer work on compatibility with anything coming to the Linux world in the future and might be a potential stability issue.

**Comment by hervyqa** [comment]
I think PR #38310 should be reopened.
