### ISSUE TITLE
Package request: yuzu-mainline

### ISSUE THREAD

**Issue by Nathan-MV** [void-linux/void-packages#38297]
### Package name

yuzu-mainline

### Package homepage

https://github.com/yuzu-emu/yuzu-mainline

### Description

Nintendo Switch emulator

### Does the requested package meet the quality requirements?

Compiled

### Is the requested package released?

Yes

**Comment by JamiKettunen** [comment]
There is a [really unfortunate amount of vendoring](https://github.com/yuzu-emu/yuzu-mainline/blob/master/.gitmodules) through the use of 17 git submodules :/
I wonder how many of these can be dropped in favor of using system versions without side effects

**Comment by JamiKettunen** [comment]
I should mention that however not ideal for now there is a [`org.yuzu_emu.yuzu`](https://flathub.org/apps/details/org.yuzu_emu.yuzu) flatpak available through Flathub which also [seems to track yuzu-mainline](https://github.com/flathub/org.yuzu_emu.yuzu) releases pretty closely.

**Comment by TrueTechie** [comment]
> There is a [really unfortunate amount of vendoring](https://github.com/yuzu-emu/yuzu-mainline/blob/master/.gitmodules) through the use of 17 git submodules :/ I wonder how many of these can be dropped in favor of using system versions without side effects

Looking at the [AUR](https://aur.archlinux.org/packages/yuzu) and [Solus](https://dev.getsol.us/source/yuzu/repository/master/) packages, this is possible with patching and compile time arguments.

**Comment by ahesford** [comment]
Given that upstream cuts a release every night, this software is not really suitable for packaging in Void.
