### ISSUE TITLE
Package request: Obsidian

### ISSUE THREAD

**Issue by Nathan-MV** [void-linux/void-packages#38348]
### Package name

obsidian

### Package homepage

https://github.com/obsidianmd/obsidian-releases

### Description

Obsidian is a powerful knowledge base on top of a local folder of plain text Markdown files.

### Does the requested package meet the quality requirements?

Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
> Obsidian is not open source software and this repo DOES NOT contain the source code of Obsidian

this, the restrictions in the [EULA](https://obsidian.md/eula), and it being an electron app make it unlikely to be packagable.

I'd recommend using the appimage they provide on the releases page of that repository.

**Comment by TeddyDD** [comment]
I recommend flatpak version, this way you don't have to update it manually.
