### ISSUE TITLE
qt5 downloads error

### ISSUE THREAD

**Issue by Merkosas** [void-linux/void-packages#38356]
ERROR: [trans] failed to download `qt5-printsupport-5.15.4+20220606_1' signature from `https://repo-default.voidlinux.org/current': Not Found
Transaction failed! see above for errors.

ERROR: [trans] failed to download `qt5-core-32bit-5.15.4+20220606_1' signature from `https://repo-default.voidlinux.org/current/multilib': Not Found
Transaction failed! see above for errors.

**Comment by classabbyamp** [comment]
wait a little bit and try again

**Comment by Merkosas** [comment]
Ok, is fine now :+1:
