### ISSUE TITLE
Package request: NordVPN

### ISSUE THREAD

**Issue by BT-Justice** [void-linux/void-packages#38358]
### Package name

nordvpn

### Package homepage

https://nordvpn.com/download/linux/

### Description

NordVPN app for Linux.

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by BT-Justice** [comment]
https://github.com/void-linux/void-packages/issues/11356

I see this was attempted a couple of years ago, but so much has changed since then.  NordVPN is easy to install on Debian, Ubuntu, and Fedora now.

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/pull/21099#issuecomment-752357850

I agree with this. nord, like most vpn services, provides openvpn and wireguard configs that should work with the existing openvpn and wireguard packages on void, without the risk of incompatibilities.

**Comment by BT-Justice** [comment]
Wouldn't you have to add each VPN server config to these programs for NordVPN to work?  That would be time-consuming and a pain to manage.

https://nordvpn.com/servers/tools/

This makes using the actual NordVPN a better option IMO as it does all of this automatically..
