### ISSUE TITLE
Package update: luasec / lua51-luasec / lua52-luasec / lua53-luasec / lua54-luasec to LuaSec 1.2.0

### ISSUE THREAD

**Issue by Neustradamus** [void-linux/void-packages#38369]
### Package name

luasec / lua51-luasec / lua52-luasec / lua53-luasec / lua54-luasec

### Package homepage

https://github.com/brunoos/luasec

### Description

Can you update LuaSec?

LuaSec 1.2.0 has been released with Channel Binding for TLS 1.3 support...
- https://github.com/brunoos/luasec/releases/tag/v1.2.0
- https://github.com/brunoos/luasec/blob/master/CHANGELOG

Thanks in advance.

cc: @Johnnynator, @sgn, @Chocimier, @q66, @mobinmob, @Duncaen, @jnbr, @diogoleal, @ebfe, @Vaelatern, @uggedal.

### Does the requested package meet the quality requirements?

Required

### Is the requested package released?

Yes

**Comment by Chocimier** [comment]
do it yourself.
