### ISSUE TITLE
Package request: lua52-luasocket / lua53-luasocket / lua54-luasocket

### ISSUE THREAD

**Issue by Neustradamus** [void-linux/void-packages#38371]
### Package name

luasocket / lua52-luasocket / lua53-luasocket / lua54-luasocket

### Package homepage

https://github.com/lunarmodules/luasocket

### Description

Can you add LuaSocket for Lua 5.2, 5.3, 5.4?
There is a very old for Lua 5.1.

LuaSocket 3.0.1 has been released (3.0.0 several years after 2.0.2):
- https://github.com/lunarmodules/luasocket/releases

Thanks in advance.

cc: @q66, @Chocimier, @uggedal.

### Does the requested package meet the quality requirements?

Required

### Is the requested package released?

Yes

**Comment by Chocimier** [comment]
Please stop, you are establishing record of entitlement towards Void maintainers, all being volunteers.

- asking us to update on #38369, despite issue form telling you to not: "Don't request an update of a package, [We have a script for that](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help."
- doing it within 2 hours from release by upstream 
- tagging dozen of uninterested people
- continuing spam despite polite rejection of your original issue

is not acceptable behavior.
