### ISSUE TITLE
Package request: Booster

### ISSUE THREAD

**Issue by Nathan-MV** [void-linux/void-packages#38393]
### Package name

booster

### Package homepage

https://github.com/anatol/booster

### Description

Faster than dracut and mkinitcpio.

### Does the requested package meet the quality requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment]
#29434

**Comment by Anachron** [comment]
[Done](https://github.com/void-linux/void-packages/commit/14d62d90f784d5b42c3fab20878de56de2547f05)
