### ISSUE TITLE
KiCad Eagle import 

### ISSUE THREAD

**Issue by lemmi** [void-linux/void-packages#3839]
Just stumbled upon http://kicad-pcb.org/blog/2018/10/KiCad-5.0.1-Release/
@faulesocke thought I let you know to keep an eye out for 5.0.2.

**Comment by faulesocke** [comment]
Hmm my PR for 5.0.1 is already gone through. Perhaps we should just wait and see if anyone has problems with it and if that's the case we can still roll back to 5.0.0 or patch the thing manually (which I would prefer).

**Comment by faulesocke** [comment]
We should keep this issue open until 5.0.2 comes out so that people can come here and report problems.

**Comment by faulesocke** [comment]
The fixing commit probably is https://git.launchpad.net/kicad/commit/?h=5.0&id=e34dc4abb1a793fb01e757d27710bca17afd909b

**Comment by luzpaz** [comment]
Should this issue be closed ?
