### ISSUE TITLE
Package request: Huion-driver

### ISSUE THREAD

**Issue by magnusshtebner** [void-linux/void-packages#38404]
### Package name

huion-driver

### Package homepage

https://github.com/emanuele/huion-driver

### Description

Driver for graphic tablets and graphic displays from huion in Linux

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by hervyqa** [comment]
isn't that a fork of digimend. after all, the commit was 8 years ago. I recommend using the digimend driver.

see https://github.com/void-linux/void-packages/pull/33349

**Comment by magnusshtebner** [comment]
> 

Thanks a lot, didn't know about this before!

**Comment by paper42** [comment]
this project has 0 stars on github and is just an old version of digimend
