### ISSUE TITLE
Package request: rpcs3

### ISSUE THREAD

**Issue by magnusshtebner** [void-linux/void-packages#38409]
### Package name

rpcs3

### Package homepage

https://github.com/rpcs3

### Description

ps3 emulator available for linux

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
> Please note that our version increases are landmarks and not stable builds
Always download the latest build from https://rpcs3.net/download
>
> Note: These are NOT stable builds. RPCS3 is a rolling release software without stable builds. These are random tags we do from time to time. Do NOT use the branch from these tags to package RPCS3.

**Comment by paper42** [comment]
We require stable releases
