### ISSUE TITLE
Package request: Etcher

### ISSUE THREAD

**Issue by magnusshtebner** [void-linux/void-packages#38413]
### Package name

etcher

### Package homepage

https://github.com/balena-io/etcher

### Description

A good application for burning images of Linux and Unix-like systems to CD / USB device

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/issues/9386#issuecomment-703182300
