### ISSUE TITLE
Package request: mujs

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#38450]
### Package name

mujs

### Package homepage

https://github.com/ccxvii/mujs

### Description

MuJS is an embedded C Javascript interpreter needed to build mpv player with javascript support.

### Does the requested package meet the quality requirements?

Required

### Is the requested package released?

Yes

**Comment by dkwo** [comment]
I've added it here https://github.com/void-linux/void-packages/pull/37912 as a dependency, perhaps you can give it a try.

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/mujs/template
