### ISSUE TITLE
Package request: cask

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#38471]
### Package name

cask

### Package homepage

https://cask.readthedocs.io/en/latest/

### Description

Cask is a project management tool for Emacs Lisp to automate the package development cycle; development, dependencies, testing, building, packaging and more.

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by sgn** [comment]
This is not compiled package. It's a shell wrapped around emacs scripts.

**Comment by Eloitor** [comment]
https://github.com/cask/cask/blob/master/Makefile#L30
I thought it needed compilation.

**Comment by sgn** [comment]
It uses emacs to compile emacs script to emacs bytecode, which isn't really compiling.

**Comment by Eloitor** [comment]
Okay, thanks. I didn't know.
