### ISSUE TITLE
[xarchiver] update to 0.5.4.18 broke left mouse button double clicks | upstream-maintainer already fixed this

### ISSUE THREAD

**Issue by TeusLollo** [void-linux/void-packages#38487]
### Is this a new report?

Yes

### System Info

Void 5.15.59_1 x86_64 GenuineIntel uptodate rFFFF

### Package(s) Affected

xarchiver-0.5.4.18_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

This is not a Void-specific concern, it actually is a regression introduced by the upstream maintainer, as detailed here:

_https://github.com/ib/xarchiver/issues/148_

The maintainer eventually fixed the issue himself with this commit:

_https://github.com/ib/xarchiver/commit/5d18fd23e8242678dbe47c232bc60b47f8fd75b0_

Hence, a simple package update should fix this. 

### Expected behaviour

xarchiver-0.5.4.18_1 is a GUI-based GTK3 App meant to allow seamless navigation into supported archive formats, along with further tooling. 

Particularly, it is supposed to support mouse-based navigation, as to allow file/directory moving, and file opening with MIME-defined selected Apps, from inside its own GUI.

### Actual behaviour

Just install package xarchiver-0.5.4.18_1 and try to open any supported archive format, assuming proper back-ends have also been installed. 

Double-click with the left mouse button is non-functional, hence navigating archive-contained files and directories is impossible utilizing the left mouse button. Thus the left mouse button CANNOT be utilized to perform file moving, and file opening with MIME-defined selected Apps.

Workarounds are utilizing the middle-button and/or keyboards for navigation purposes, but this is both counter-intuitive and mostly defeating the advantages of utilizing a GUI-based App.

This is NOT intended, as confirmed by the upstream maintainer here:

_https://github.com/ib/xarchiver/issues/148#issuecomment-1145796302_

### Steps to reproduce

1 Install xarchiver-0.5.4.18_1

2 Open a format-compatible archive (Remember also to install proper archive back-ends), preferably containing at least one file and one directory

3 Notice how navigating directories, and manipulating files, into the archive GUI, is impossible utilizing left double-clicking

4 This is valid only when attempting to grab/open/move individual files and directories with left double-clicking. 
Left double-clicking actually works when utilizing bar-based tooling, while right double-clicking and middle-clicking still work as well

5 This is NOT by design, as this commit confirms: _https://github.com/ib/xarchiver/commit/5d18fd23e8242678dbe47c232bc60b47f8fd75b0_

A package update should fix this, given how the upstream-maintainer already fixed this. Relevant links have been provided above.
 
This is technically NOT a package request, but a BUG REPORT, since there's in fact a bug, confirmed by non-void users, hence why I did a bug report. 

YET, the simplest fix will require executing a package update from upstream. 

Thanks for all your work in advance.

**Comment by classabbyamp** [comment]
> Hence, a simple package update should fix this.

0.5.4.18 is the latest version so we'll need to backport the fix you identified until a proper release is tagged

**Comment by classabbyamp** [comment]
can you [test](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#testing-pull-requests) #38495 for me and let me know if it works?

**Comment by paper42** [comment]
> Sorry, I forgot this is not Arch :)

Arch also packages stable versions of packages and not random git revisions.

**Comment by classabbyamp** [comment]
ok I was able to test and confirm this. Dunno what's up with those git errors, that's super werid.
