### ISSUE TITLE
Package request: Sublime-Text

### ISSUE THREAD

**Issue by g-h-97** [void-linux/void-packages#38489]
### Package name

Sublime-Text

### Package homepage

https://www.sublimetext.com/

### Description

Sublime text editor.

### Does the requested package meet the quality requirements?

Required

### Is the requested package released?

Yes

**Comment by paper42** [comment]
already packaged twice (v3 and v4)

**Comment by g-h-97** [comment]
> already packaged twice (v3 and v4)
Any idea why was it removed ? As far as I can tell it's not available on free neither non-free musl repos !

**Comment by paper42** [comment]
It was not removed, it is still available, but only in the glibc nonfree repositories because it's proprietary and their binaries are linked against glibc like most proprietary applications.

**Comment by g-h-97** [comment]
Oh, I see. I'll try to get it running using nix then.
Thanx @paper42, I appreciate you time,
