### ISSUE TITLE
glibc-locales isn't installed with base-* packages

### ISSUE THREAD

**Issue by dataCobra** [void-linux/void-packages#38482]
### Is this a new report?

Yes

### System Info

Void 5.18.14_1 x86_64 GenuineIntel uptodate FF

### Package(s) Affected

base-minimal-0.3_1, base-system-0.114_1

### Expected behaviour

The package glibc-locales is also necessary for glibc-systems and should therefore be installed.

### Actual behaviour

The package glibc-locales is only installed for musl-systems.

### Steps to reproduce

Freshinstall of Void with base packages in glibc environment.

**Comment by paper42** [comment]
glibc-locales is only available in glibc repositories, so it can not be installed on musl systems. On glibc systems it's a dependency of base-system, base-voidstrap and base-minimal, so it will be installed there.

**Comment by dataCobra** [comment]
Hey @paper42,

I see that my bugreport is a bit misleading now after I realized that I read the case statement
wrong...

The bugreport is still active because glibc-locales didn't get installed on two freshinstalls I
did yesterday and today. With usage of the official documentation (Installation via chroot).

Here's my documentation about what I've done before I checked for glibc-locales:
The `#` are only  german comments for my purposes.

```
* # Erstellung der LVs und Einrichtung der Dateisysteme
  # Verschluesselung des VG mit den LVs
  mkfs.vfat -F32 /dev/sda1
  mkfs.ext4 -L boot /dev/sda2
  cryptsetup luksFormat /dev/sda3
  cryptsetup luksOpen /dev/sda3 crypto
  pvcreate /dev/mapper/crypto
  vgcreate vgVoid /dev/mapper/crypto
  lvcreate -n root -L 16G vgVoid
  lvcreate -n swap -L 8G vgVoid
  lvcreate -n var -L 12G vgVoid
  lvcreate -n home -L 42G vgVoid
  mkfs.ext4 -L root /dev/vgVoid/root
  mkfs.ext4 -L var /dev/vgVoid/var
  mkfs.ext4 -L home /dev/vgVoid/home
  mkswap -L swap /dev/vgVoid/swap
* # Anlegen der Umgebung
  mkdir -v /mnt/root
  mount -v /dev/vgVoid/root /mnt/root
  mkdir -v /mnt/root/var
  mount -v /dev/vgVoid/var /mnt/root/var
  mkdir -v /mnt/root/home
  mount -v /dev/vgVoid/home /mnt/root/home
  mkdir -v /mnt/root/boot
  mount -v /dev/sda2 /mnt/root/boot
  mkdir -v /mnt/root/boot/efi
  mount -v /dev/sda1 /mnt/root/boot/efi
  swapon /dev/vgVoid/swap
* # Installation von VoidLinux
  REPO=https://repo-fi.voidlinux.org/current
  ARCH=x86_64
  mkdir -p /mnt/root/var/db/xbps/keys
  cp /var/db/xbps/keys/* /mnt/root/var/db/xbps/keys/
* XBPS_ARCH=$ARCH xbps-install -S -r /mnt/root -R "$REPO" base-minimal
```

**Comment by dataCobra** [comment]
I've tested both base-minimal and base-system.

**Comment by paper42** [comment]
I don't think that's possible, `xbps-query -x base-minimal/system` shows glibc-locales, does it also show it for you? How are you checking if glibc-locales are installed?

**Comment by dataCobra** [comment]
---
> I don't think that's possible, `xbps-query -x base-minimal/system` shows glibc-locales, does it also show it for you? How are you checking if glibc-locales are installed?

I've looked for `/etc/default/libc-locales` to uncomment my locales but it wasn't there.

So I've checked with `xbps-query -l` and it didn't show up there.
I installed the package manual.

The problem occurred on both, a physical and a virtual machine.

When I do check with your command `glibc-locales>=0` does show up indeed.

**Comment by dataCobra** [comment]
Hey @paper42,

After I tried a new fresh install glibc-locales is indeed a dependencie thats going to be
installed. I've no idea what I do wrong on the first two machines.

I'll close this issue for now and comeback if I encounter the problem again.

Sorry for the noise and thanks for the fast replies.

Regards,
Ben
