### ISSUE TITLE
efibootmgr weird output

### ISSUE THREAD

**Issue by TegarOk** [void-linux/void-packages#38492]
### Is this a new report?

Yes

### System Info

Void 5.10.109_1 x86_64 AuthenticAMD notuptodate rrmFFFFF

### Package(s) Affected

efibootmgr-18_1

### Expected behaviour

When execute efibootmgr -v on terminal, the output should be something like this:

`Boot0002* Void Linux 5.18       HD(XXXXXX)r.o.o.t.=XXXXXXX .q.u.i.e.t. .s.p.l.a.s.h. .r.w. .r.a.d.e.o.n...s.i._.s.u.p.p.o.r.t.=.0. .a.m.d.g.p.u...s.i._.s.u.p.p.o.r.t.=.1. .a.m.d.g.p.u...d.p.m.=.1. .a.m.d.g.p.u...g.p.u._.r.e.c.o.v.e.r.y.=.2. .a.p.p.a.r.m.o.r.=.1. .n.e.t...i.f.n.a.m.e.s.=.0. .i.o.m.m.u.=.p.t. .a.m.d._.i.o.m.m.u.=.1. .a.c.p.i._.e.n.f.o.r.c.e._.r.e.s.o.u.r.c.e.s.=.l.a.x. .i.n.i.t.r.d.=.\.i.n.i.t.r.a.m.f.s.-.5...1.8...1.1._.1...i.m.g.`

### Actual behaviour

But on the latest version. efibootmgr didnt report something like that, instead like this:
`Boot0002* Void Linux 5.18       VenHw(99e275e7-75a0-4b37-a2e6-c5385e6c00cb)72006f006f0074003d005a00460053003d005a004600530052002f0056006f00690064002000710075006900650074002000730070006c00610073006800200072007700200072006100640065006f006e002e00730069005f0073007500700070006f00720074003d003000200061006d0064006700700075002e00730069005f0073007500700070006f00720074003d003100200061006d0064006700700075002e00640070006d003d003100200061006d0064006700700075002e006700700075005f007200650063006f0076006500720079003d0032002000610070007000610072006d006f0072003d00310020006e00650074002e00690066006e0061006d00650073003d003000200069006f006d006d0075003d0070007400200061006d0064005f0069006f006d006d0075003d003100200061006300700069005f0065006e0066006f007200630065005f007200650073006f00750072006300650073003d006c0061007800200069006e0069007400720064003d005c0069006e0069007400720061006d00660073002d0035002e00310038002e00310031005f0031002e0069006d006700`

### Steps to reproduce

1. Open terminal
2. launch "efibootmgr -v"
3. Weird Output
4. Done

**Comment by sgn** [comment]
Take that to RedHat instead: https://github.com/rhboot/efibootmgr/commit/8ec3e9dedb3cb62f19847794012420b90f475398

**Comment by sgn** [comment]
Anyway, this is also weird:
```
Boot0002* Void Linux 5.18 HD(XXXXXX)r.o.o.t.=XXXXXXX .q.u.i.e.t. .s.p.l.a.s.h. .r.w. .r.a.d.e.o.n...s.i._.s.u.p.p.o.r.t.=.0. .a.m.d.g.p.u...s.i._.s.u.p.p.o.r.t.=.1. .a.m.d.g.p.u...d.p.m.=.1. .a.m.d.g.p.u...g.p.u._.r.e.c.o.v.e.r.y.=.2. .a.p.p.a.r.m.o.r.=.1. .n.e.t...i.f.n.a.m.e.s.=.0. .i.o.m.m.u.=.p.t. .a.m.d._.i.o.m.m.u.=.1. .a.c.p.i._.e.n.f.o.r.c.e._.r.e.s.o.u.r.c.e.s.=.l.a.x. .i.n.i.t.r.d.=.\.i.n.i.t.r.a.m.f.s.-.5...1.8...1.1._.1...i.m.g.
```
Since that optional data should be gone through `ucs2_to_utf8` before writing down. Are you passing anything else? Or your locale?

**Comment by TegarOk** [comment]
> What is your locale?
I was chroot to my older system on the other drive. I dont know about the locale if i chroot, but im using en_US.UTF-8 for all system when booting (Same as Host right now).

**Comment by sgn** [comment]
This is decision from upstream, so not much we can do. I think you can workaround by: `efitbootmgr -uv`
Which translate the optional data to utf-8 and get a better output.

**Comment by TegarOk** [comment]
Yeah i just read the upstream from efibootmgr itself.
Thanks for information.
Im gonna close the issue.

**Comment by sgn** [comment]
I meant can you use `efibootmgr -uv`? It will give you nicer output?

**Comment by TegarOk** [comment]
> I meant can you use `efibootmgr -uv`? It will give you nicer output?

Yeah you are right about that, but i never use -u option before cuz i dont know about that option.
