### ISSUE TITLE
Package request: AppImage Launcher

### ISSUE THREAD

**Issue by magnusshtebner** [void-linux/void-packages#38497]
### Package name

AppImageLauncher

### Package homepage

https://github.com/TheAssassin/AppImageLauncher

### Description

This program allows you to integrate appimage packages into your system. For example, such applications as librewolf, etcher, rpcs3 and others.

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by paper42** [comment]
duplicate of #26702
