### ISSUE TITLE
godot 3.5: Font rendering in editor broken.

### ISSUE THREAD

**Issue by chili-b** [void-linux/void-packages#38526]
### Is this a new report?

Yes

### System Info

Void 5.18.16_1 x86_64 GenuineIntel uptodate FFFFFFFFFF

### Package(s) Affected

godot-3.5_1

### Expected behaviour

Font rendering in the editor should work.

### Actual behaviour

Font rendering in the editor is broken:
![image](https://user-images.githubusercontent.com/21281636/183323515-56d42543-7c57-41be-bee3-2b10342d9d03.png)

Godot writes the following error message:
```
ERROR: Unknown font format.
   at: _load (scene/resources/dynamic_font.cpp:178)
```
here is the relevant line in godot's source: https://github.com/godotengine/godot/blob/3.5-stable/scene/resources/dynamic_font.cpp#L178

### Steps to reproduce

1. Install Godot 3.5
2. Open the editor

**Comment by classabbyamp** [comment]
this might actually be a harfbuzz issue, someone else is reporting an issue with another program related to harfbuzz

**Comment by chili-b** [comment]
> this might actually be a harfbuzz issue

Maybe this is unrelated, but downgrading to Godot 3.4 makes the problem go away. Would that still happen if it were a problem with harfbuzz?

**Comment by Relected** [comment]
hi, i am the dude who updated godot from 3.4 to 3.5, i am actively looking for ways to fix this very problem, it appears that the freetype engine doesnt recognize some font formats upon startup and i am now recompiling the engine either with new up-to-date libraries or with built in ones

if you would like to contact me to provide more info to solve this problem contact me on Discord at rTerm#7406
