### ISSUE TITLE
Pipewire and Pipewire Pulse Not Properly Configured for Autostarting

### ISSUE THREAD

**Issue by TrueTechie** [void-linux/void-packages#38541]
### Is this a new report?

Yes

### System Info

Void 5.18.16_1 x86_64 GenuineIntel uptodate FFFFFFF

### Package(s) Affected

pipewire-0.3.56_1

### Expected behaviour

The package places its autostart files in the XDG standard location `/etc/xdg/autostart` and thus start automatically without intervention by the user when installed. However, this would require the `pipewire-pulse` desktop file (and ideally the binary and other configuration tools, for organization sake) to be placed in separate, conflicting package since `pipewire` can also be used alongside `pulseaudio`.

### Actual behaviour

The two autostart files `pipewire.desktop` and `pipewire-pulse.desktop` are located in `/usr/share/applications` which has nothing to do with auto-starting applications, only listing them in menus and application runners.

### Steps to reproduce

1. Install the package `pipewire`
2. Log out from or otherwise restart desktop environment
3. Log back in, audio server does not automatically start

**Comment by paper42** [comment]
> The package places its autostart files in the XDG standard location /etc/xdg/autostart and thus start automatically without intervention by the user when installed.

Automatically starting pipewire on behalf of the user is a bad idea and we won't do it.

> However, this would require the pipewire-pulse desktop file (and ideally the binary and other configuration tools, for organization sake) to be placed in separate, conflicting package since pipewire can also be used alongside pulseaudio.

That's not pretty and would be confusing to new users coming from other distributions. We chose to not enable pipewire (and pipewire-pulse) automatically for the user and we document a common way to start pipewire here: https://docs.voidlinux.org/config/media/pipewire.html.

> The two autostart files pipewire.desktop and pipewire-pulse.desktop are located in /usr/share/applications which has nothing to do with auto-starting applications, only listing them in menus and application runners.

They are have `NoDisplay=true` set, so they shouldn't show up in application runners.

**Comment by TrueTechie** [comment]
> Automatically starting pipewire on behalf of the user is a bad idea and we won't do it.
Okay... Could you elaborate on the "bad idea" part? I might be missing something here but Pulse is started automatically in the same manner and it hasn't caused any issues.
> ...we document a common way to start pipewire here: https://docs.voidlinux.org/config/media/pipewire.html.
Oh, I didn't know that document was updated recently.
> They are have NoDisplay=true set, so they shouldn't show up in application runners.
Sorry, I meant that the standard for the directory is for application runners. Miscommunication on my part.

**Comment by paper42** [comment]
> > Automatically starting pipewire on behalf of the user is a bad idea and we won't do it.

> Okay... Could you elaborate on the "bad idea" part? I might be missing something here but Pulse is started automatically in the same manner and it hasn't caused any issues.

Pulse being autostarted is also not ideal. If you want to switch to pipewire or just stop it, it's not easy.
