### ISSUE TITLE
libreoffice: libharfbuzz.so.0: undefined symbol: FT_Get_Transform

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#38545]
### Is this a new report?

Yes

### System Info

Void 5.18.16_1 x86_64 AuthenticAMD uptodate FFFFFFF

### Package(s) Affected

libreoffice-7.3.3.2_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

-

### Expected behaviour

libreoffice can be run.

### Actual behaviour

libreoffice failed to run.

```
➜  ~ libreoffice
/usr/lib/libreoffice/program/soffice.bin: symbol lookup error: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Transform
```

### Steps to reproduce

1. sudo xbps-install -Su
2. sudo reboot
3. libreoffice

**Comment by oreo639** [comment]
> <quinq> Allright, got it working
> <quinq> Three things
> <quinq> 1/ loffice is broken with openjdk8
> <quinq> 2/ you need to remove $HOME/.config/libreoffice/4/user/config/javasettings_Linux_X86_64.xml
> <quinq> 3/ you need to reset JAVA_HOME

(openjdk8 includes its own libfreetype)

**Comment by hervyqa** [comment]
> > <quinq> 3/ you need to reset JAVA_HOME

how to reset? JAVA_HOME is empty.
```
[l7@studio ~]$ echo $JAVA_HOME

[l7@studio ~]$ 
```

**Comment by oreo639** [comment]
It should be set by `/etc/profile.d/openjdk.sh` based on which version of java you have set as your default in xbps-alternatives.

**Comment by paper42** [comment]
quinq on IRC found that the java version is saved when used once, remove $HOME/.config/libreoffice/4/user/config/javasettings_Linux_X86_64.xml

**Comment by hervyqa** [comment]
thank you 👍🏻
switch to jdk11 works again

```
doas xbps-install -S openjdk11
rm -rfv ~/.config/libreoffice/4/user/config/javasettings_Linux_X86_64.xml
doas xbps-alternatives -s openjdk11
```

![Screenshot_20220809_172855](https://user-images.githubusercontent.com/45872139/183626836-ad5e2df1-5034-4a6d-835e-38d9ac5256d3.png)

**Comment by classabbyamp** [comment]
rebuilding openjdk8 with the new freetype fixed it, should be in the repos soon

**Comment by hervyqa** [comment]
> rebuilding openjdk8 with the new freetype fixed it, should be in the repos soon

It's work with openjdk8.
Fixed: https://github.com/void-linux/void-packages/commit/4a2c3c68b9f4636ea725865932f79795be55d73c
