### ISSUE TITLE
Mate Desktop Declares Hard Dependency On Pulseaudio

### ISSUE THREAD

**Issue by TrueTechie** [void-linux/void-packages#38542]
### Is this a new report?

Yes

### System Info

Void 5.18.16_1 x86_64 GenuineIntel uptodate FFFFFFF

### Package(s) Affected

mate-1.26.0_1 mate-settings-daemon-1.26.0_1

### Expected behaviour

You can install and use the Mate desktop without installing/using `pulseaudio` (say,  using `pipewire-pulse`) as you can on Arch and Fedora.

### Actual behaviour

Installing the package requires `alsa-plugins-pulseaudio`, unlike Arch which has this as an optional dependency.

### Steps to reproduce

1. Install `mate`, more specifically `mate-settings-daemon`
2. See that transaction includes the `pulseaudio` package

**Comment by classabbyamp** [comment]
did #38544 fix this?

**Comment by paper42** [comment]
yes
