### ISSUE TITLE
Dovecot package is broken in various ways

### ISSUE THREAD

**Issue by TwinkleToes777** [void-linux/void-packages#38551]
### Is this a new report?

Yes

### System Info

Void 5.18.16_1 x86_64 AuthenticAMD/VM uptodate rFFF

### Package(s) Affected

dovecot-2.3.19.1_1

### Expected behaviour

Expected config to be automatically put in /etc/dovecot
Expected it to work after starting

### Actual behaviour

/etc/dovecot folder did not get created
It did not start because it complained about 'dovecot' user not being found
after I created 'dovecot' user manually, it complained about file permission issue when I tried to connect over IMAP:
```
Error: auth-worker: net_connect_unix(auth-worker) in directory /run/dovecot failed: Permission denied (euid=5006(dovecot) egid=5006(dovecot) missing +r perm: /run/dovecot/auth-worker, dir owned by 0:0 mode=0755)
```
When I tried to fix file permissions, it undoes my change every time the service is restarted and errors again.

### Steps to reproduce

1. sudo xbps-install -y dovecot, sudo ln -s /etc/sv/dovecot /var/service, sudo sv up dovecot
2. Observe it causing error for 'dovecot' user not found (visible in htop)
3. Try setup some imap account on dovecot and connect to it, observe it having file permission issue after enabling logging (log_path = /var/log/dovecot.log in /etc/dovecot/dovecot.conf)

**Comment by Anachron** [comment]
I use `dovecot` on my `VPS` and I have both the `docevot` user and the configs. 

Can you reproduce it on a clean install/VM/container?

For me it sounds like it didn't get installed properly. Do you have the install logs somewhere?

**Comment by TwinkleToes777** [comment]
I'm glad it works for you, I am using a VPS too.

here are the install logs (I uninstalled and installed again):

```
[*] Verifying package integrity
mit-krb5-libs-1.18.3_2: verifying RSA signature...
dovecot-2.3.19.1_1: verifying RSA signature...

[*] Collecting package files
mit-krb5-libs-1.18.3_2: collecting files...
dovecot-2.3.19.1_1: collecting files...

[*] Unpacking packages
mit-krb5-libs-1.18.3_2: unpacking ...
dovecot-2.3.19.1_1: unpacking ...

[*] Configuring unpacked packages
mit-krb5-libs-1.18.3_2: configuring ...
mit-krb5-libs-1.18.3_2: installed successfully.
dovecot-2.3.19.1_1: configuring ...
Updated _dovecot system user.
Updated _dovenull system user.
dovecot-2.3.19.1_1: installed successfully.
```

**Comment by Anachron** [comment]
So you're saying `grep 'dovecot' /etc/passwd` returns nothing?
And you have no example configs for dovecot inside `/usr/share/examples/dovecot`? (You need to copy them yourself to `/etc`)

**Comment by TwinkleToes777** [comment]
`grep 'dovecot' /etc/passwd` returns:
`_dovecot:x:992:991:_dovecot unprivileged user:/var/empty:/sbin/nologin`
which is _dovecot, not dovecot, and it errors on not finding dovecot user specifically

I was not aware that I have to copy configs myself, sorry about that.

**Comment by Anachron** [comment]
Ah I installed `dovecot` before https://github.com/void-linux/void-packages/commit/b49fd851309d6593fbb6fb8ae191f796a98ee96a probably, so that's why I have

```
grep 'dovecot' /etc/passwd
dovecot:x:994:993:dovecot unprivileged user:/var/chroot:/sbin/nologin
_dovecot:x:991:990:_dovecot unprivileged user:/var/empty:/sbin/nologin
```

Can you redact your config and paste it here?

Because for example this is inside `/usr/share/examples/dovecot/conf.d/10-master.conf`:

```
# Login user is internally used by login processes. This is the most untrusted
# user in Dovecot system. It shouldn't have access to anything at all.
#default_login_user = dovenull

# Internal user is used by unprivileged processes. It should be separate from
# login user, so that login processes can't disturb other processes.
#default_internal_user = dovecot
```

**Comment by TwinkleToes777** [comment]
Thank you, that was the problem. I was using a config from ubuntu and it had the user configured as `dovecot`, I thought it may be the problem, but after searching the configs, I did not notice any usage of the wrong user, but now I see it's there in `10-master.conf`

So this was not a bug and just my fault, but I hope this closed issue will help someone else solve their problem in the future.

**Comment by Anachron** [comment]
Glad you solved this, enjoy `Void Linux`!

**Comment by d3jv** [comment]
> Because for example this is inside `/usr/share/examples/dovecot/conf.d/10-master.conf`

I only have `dovecot.conf`, `mkcert.sh` and `dovecot-openssl.cnf` in the examples directory with my installation. Is the `conf.d` directory supposed to be there or is it the one from ubuntu?

**Comment by classabbyamp** [comment]
don't bump old, closed issues
