### ISSUE TITLE
musl: update to 1.2.3. What needs to be done to get the update? (time_t)

### ISSUE THREAD

**Issue by dataCobra** [void-linux/void-packages#38584]
I've just discovered that musl is still on 1.1.24 and even got reverted from 1.2.0.

I've read a PR that I was not able to find again about the problems with changes to time_t.

What needs to be done to get the latest release working with void-linux and the packages?

**Comment by Johnnynator** [comment]
Roughly put, the ABI for 32bit system will change, so we need a full rebuild of these repos. Xbps (and xbps-src) do lack support for enforcing that all installed packages are with the new ABI.

Partially support is getting implemented in this xbps pr: https://github.com/void-linux/xbps/pull/331

**Comment by q66** [comment]
in any case, opening more issues about it won't get it done
