### ISSUE TITLE
Package request: bash-language-server

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#38606]
### Package name

bash-language-server

### Package homepage

https://github.com/bash-lsp/bash-language-server

### Description

A language server for Bash

Bash language server implementation based on [Tree Sitter](https://github.com/tree-sitter/tree-sitter) and its [grammar for Bash](https://github.com/tree-sitter/tree-sitter-bash) and supports [explainshell](https://explainshell.com/) and [shellcheck](https://www.shellcheck.net/).

### Does the requested package meet the quality requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/pull/42818
