### ISSUE TITLE
[Feature request] Integration between xbps and plasma-discover!

### ISSUE THREAD

**Issue by gilbertoferreira** [void-linux/void-packages#38646]
Helle there.

Recentely I had used Alpine Linux which is a wonderful systemd-free distro.
The way they could integrate their package manager, apk to plasma-discover, was awesome.
So I wonder if VoidLinux could do something familiar, since plasma-discover can also be use as gui to install flatpak as well.

Thanks

**Comment by classabbyamp** [comment]
this would require packagekit support added to xbps, I believe

**Comment by classabbyamp** [comment]
void-linux/xbps#503
