### ISSUE TITLE
PolyMC Depends On Old Version of Java

### ISSUE THREAD

**Issue by TrueTechie** [void-linux/void-packages#38645]
### Is this a new report?

Yes

### System Info

Void 5.18.17_1 x86_64 GenuineIntel uptodate FFFFF

### Package(s) Affected

PolyMC-1.4.1_1

### Expected behaviour

The package recommends a version of Java compatible with the latest version of Minecraft on installation. After this, when launching a profile with the latest version of Minecraft, there is no error or need to manually install a later version of Java via `xbps`

### Actual behaviour

The package recommends Java version 11, far from the necessary versions 17 or 18 for running a modern version of Minecraft. I'll see about creating a PR to change this.

### Steps to reproduce

1. Install the package
2. Start the application
3. Set a Java runtime (default being 11)
4. Set up a Minecraft profile and launch
5. Note the launch fails requesting Java version 17 or 18

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/pull/38648#issuecomment-1214188332
