### ISSUE TITLE
ldns: 1.8.2 update is broken when enabling DNSSEC

### ISSUE THREAD

**Issue by sbiberhofer** [void-linux/void-packages#38669]
### Is this a new report?

Yes

### System Info

Void 5.18.11_1 x86_64 GenuineIntel uptodate rrFFF

### Package(s) Affected

ldns-1.8.2_1, libldns-1.8.2_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Not yet (at least to my knowledge).

### Expected behaviour

`drill -D` and `ssh` with host key verification over DNS (using SSHFP) to work as usual. :(

### Actual behaviour

Using `drill -D` or `ssh` with `VerifyHostKeyDNS yes` results in an assert failure, regardless of the target domain:

```
% drill -D www.google.com
drill: ./rdata.c:26: ldns_rdf_size: Assertion `rd != NULL' failed.
zsh: IOT instruction  drill -D www.google.com
```

### Steps to reproduce

1. Upgrade to 1.8.2
2. Try to resolve any domain name with `drill -D`, e.g. `drill -D www.google.com`

**Comment by paper42** [comment]
I can reproduce this, cc @leahneukirchen

**Comment by leahneukirchen** [comment]
Reported upstream, will revert for now.
