### ISSUE TITLE
Update Request: khal

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#3867]
### System

* xuname:  
* package:  khal_0.9.9.20180918

### Expected behavior
Khal to launch

### Actual behavior
Khal fails to launch with error
`Failed to find (autogenerated) version.py. This might be due to using GitHub's tarballs or svn access. Either clone from GitHub via git or get a tarball from PyPI.`

### Steps to reproduce the behavior
Just try to launch khal.

### Source
The issue is probably caused by using the git commit and not a release here:
https://github.com/void-linux/void-packages/blob/b20b5f8f586196587e5f52ceb167cc48f8f0e5aa/srcpkgs/khal/template#L19

There is a new update that can be used instead
https://github.com/pimutils/khal/releases/tag/v0.9.10

**Comment by Anachron** [comment]
Thanks guys!

**Comment by asergi** [comment]
Thanks to everyone involved for the quick update.
