### ISSUE TITLE
Audacity "Mismatch between the program and library build versions detected"

### ISSUE THREAD

**Issue by jconnolly837** [void-linux/void-packages#38679]
### Is this a new report?

Yes

### System Info

Void 5.18.17_1 x86_64 GenuineIntel uptodate rFFFFF

### Package(s) Affected

audacity-2.4.1_2

### Expected behaviour

Audacity launches and operates as intended. 

### Actual behaviour

Audacity outputs a "Mismatch between the program and library build versions detected" error. 

```
[james@Void9020 ~]$ audacity
01:28:28: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 2.8).
[james@Void9020 ~]$
```

### Steps to reproduce

1. Have a Void system with recently updated packages.
2. Try to lauch Audacity. 
3. See error instead of Audacity window if launched through the terminal. See nothing if launched through the DE/icon/.desktop/etc...

**Comment by paper42** [comment]
#34701

**Comment by jconnolly837** [comment]
Turns out there were zombie Audacity processes running. After rebooting, Audacity was able to start, but still showed the same error in the terminal.
