### ISSUE TITLE
equivalent of `exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK` in void linux.

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#38698]
Hello.

I installed wayfire and I want to use flameshot in it.

There is a problem that I described here:
https://github.com/flameshot-org/flameshot/discussions/2871#discussioncomment-3403388

@mmahmoudian said that I can use this:
https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md

All errors are gone, but still, I can't take any screenshots. I wondered how can I run these lines in void linux:

```
exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK
exec hash dbus-update-activation-environment 2>/dev/null && \
     dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK
```

**Comment by motorto** [comment]
This : https://github.com/emersion/xdg-desktop-portal-wlr/wiki/%22It-doesn't-work%22-Troubleshooting-Checklist#runit

**Comment by CameronNemo** [comment]
you probably just need `dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK`

**Comment by LinArcX** [comment]
@CameronNemo No, it's not working.

**Comment by motorto** [comment]
@LinArcX in case you didn't saw my link inside there there is this command: 

"exec dbus-update-activation-environment DISPLAY I3SOCK SWAYSOCK WAYLAND_DISPLAY"

And I could confirm that this command does the equivalent to what you want
