### ISSUE TITLE
Critical: Error: No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#38699]
### Is this a new report?

Yes

### System Info

Void 5.18.16_1 x86_64 GenuineIntel notuptodate hold rFF

### Package(s) Affected

ksnip-1.9.2, wayfire-0.7.3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

[866](https://github.com/ksnip/ksnip/issues/866)

### Expected behaviour

ksnip should take screenshots properly on wayfire.

### Actual behaviour

whenever i run ksnip from shell and try to capture screenshot, it says:
```
↳ ksnip
Critical: Unknown wayland platform, using default wayland Image Grabber.
Warning: Unable to find any translation files for ksnip.
Warning: Unable to find any translation files for kImageAnnotator.
Warning: Wayland does not support QWindow::requestActivate()
Warning: Wayland does not support QWindow::requestActivate()
Warning: This plugin does not support setting window opacity
Critical: Error: No such interface “org.freedesktop.portal.Screenshot” on object at path /org/freedesktop/portal/desktop
```I

### Steps to reproduce

1. run ksnip from your shell.

**Comment by paper42** [comment]
This doesn't sound like a bug, but just a wrong setup. Do you have xdg-desktop-portal-wlr?

**Comment by LinArcX** [comment]
Yes, these packages installed on my machine:

1. xdg-desktop-portal
2. xdg-desktop-portal-wlr
3. xdg-desktop-portal-kde

**Comment by vutunganh** [comment]
At least for sway, I also have to manually start them (`/usr/libexec/xdg-desktop-portal{,-gtk,-wlr} --replace`) for things to work.

**Comment by classabbyamp** [comment]
may need to configure portals https://docs.voidlinux.org/config/graphical-session/portals.html
