### ISSUE TITLE
Package request: Amberol

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#38739]
### Package name

Amberol

### Package homepage

https://gitlab.gnome.org/World/amberol

### Description

A small and simple sound and music player that is well integrated with GNOME.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

No

**Comment by paper42** [comment]
this is still in beta, NACK for now

**Comment by chrysos349** [comment]
#44057

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/amberol/template
