### ISSUE TITLE
PyBluez is not up to date with python 3.10.

### ISSUE THREAD

**Issue by ysftaha** [void-linux/void-packages#38730]
### Is this a new report?

Yes

### System Info

Void 5.18.17_1 x86_64 GenuineIntel uptodate rrFFFFF

### Package(s) Affected

python3-bluez-0.23_2

### Expected behaviour

importing bluetooth module in a python3.10 script works.

### Actual behaviour

```sh
$ /bin/cat foo.py
#!/bin/python3
import bluetooth
$ /bin/python3 foo.py
Traceback (most recent call last):
  File "/home/u/tmp/Bluetooth_Headset_Battery_Level/test.py", line 2, in <module>
    import bluetooth
ModuleNotFoundError: No module named 'bluetooth'
$
```

### Steps to reproduce

NOTE: similar issue closed in 2019 #1509

1. download the latest python3-bluez
2. import bluetooth in a python script
3. run script

P.S. pybluez lives in /usr/lib/python3.9/site-packages/PyBluez-0.23-py3.9.egg-info (notice the 3.9 not 3.10 yet)

**Comment by icp1994** [comment]
`python3-bluez` was [removed](https://github.com/void-linux/void-packages/commit/5957216b89b88d124a84e5d5045e183bf16a71aa). There was a PR for [restoring](https://github.com/void-linux/void-packages/pull/33626) it and a relevant ongoing [discussion](https://github.com/void-linux/void-packages/pull/36640).
