### ISSUE TITLE
Segmentation Fault in nvi cedit

### ISSUE THREAD

**Issue by chase-net** [void-linux/void-packages#38741]
### Is this a new report?

Yes

### System Info

Void 5.18.17_1 x86_64-musl GenuineIntel notuptodate hold rFFF

### Package(s) Affected

nvi-1.81.6_17

### Expected behaviour

The user can edit the colon command line history in a buffer after pressing the cedit character.

### Actual behaviour

There is a segmentation fault while editing the colon command line history.

### Steps to reproduce

1. Start nvi. `EXINIT= vi`
2. Set the cedit character. `:set cedit=v`
3. Activate command editing with that character. `:v`
4. Insert text and return to normal mode.
5. Segmentation fault.

**Comment by sgn** [comment]
Fixed by https://github.com/void-linux/void-packages/commit/ecffd21dac2c0e49747242dafa7e706c894cf6d5
