### ISSUE TITLE
[[:space:]] and [[:blank:] character classes not working as expected in nvi

### ISSUE THREAD

**Issue by chase-net** [void-linux/void-packages#38742]
### Is this a new report?

Yes

### System Info

Void 5.18.17_1 x86_64-musl GenuineIntel notuptodate hold rFFF

### Package(s) Affected

nvi-1.81.6_17

### Expected behaviour

Searching should match space and tab characters when using the POSIX character classes [:space:] and [:blank:].

### Actual behaviour

[:space:] and [:blank:] seem to match the [:alnum:] character class.

### Steps to reproduce

1. Start vi. `EXINIT= vi`
2. Insert some text including spaces and alphanumeric characters and return to normal mode. `ia b c d<esc>`
3. Search for the character classes [:space:] or [:blank:]. `/[[:space:]]`
4. Cycle through matches with `n`.

**Comment by abenson** [comment]
This isn't a Void issue, this should be brought up with [`nvi` upstream](https://repo.or.cz/nvi.git).  

FWIW the behavior on Void's `nvi` seems consistent with other distributions (tested on Debian).

**Comment by sgn** [comment]
Yes, `nvi` uses nvi bundled `regexp(3)` not libc's one. It can't be compiled with libc's `regexp(3)` at least with musl, since it uses `REG_STARTEND` which is an BSD-extension.

**Comment by sgn** [comment]
Anyway, the character classes has been fix.

**Comment by chase-net** [comment]
It seems this was fixed in the upstream as well. The latest snapshot compiles without patches and has this and #38741 fixed.

**Comment by sgn** [comment]
> It seems this was fixed in the upstream as well. The latest snapshot compiles without patches and has this and #38741 fixed.

Ask them for a release, then.
Quoting https://repo.or.cz/nvi.git/blob/HEAD:/README.1st#l1

> This is a development version of nvi.
> Use at your own risk.

For this bug, it can be traced easily, but #38741 is hard to trace.

**Comment by chase-net** [comment]
> Ask them for a release, then.

Will do. Thank you for the patches.
