### ISSUE TITLE
Sound is not working because CONFIG_SND_HDA_INTEL_HDMI_SILENT_STREAM is not set

### ISSUE THREAD

**Issue by medanisjbara** [void-linux/void-packages#38755]
### Is this a new report?

Yes

### System Info

Void 5.18.17_1 x86_64 AuthenticAMD uptodate rFF

### Package(s) Affected

linux5.18-5.18.17_1

### Expected behaviour

Sound should work out of the box.

### Actual behaviour

`alsamixer` didn't detect my sound card.  
But when using another kernel (e.g. [arch's zen kernel](https://archlinux.org/packages/extra/x86_64/linux-zen/) ) and everything was working fine.  
After checking the differences in `lsmod` and looking through both configs. I was able to find the module `snd_hda_intel_hdmi` present in the kernel that had sound working. And void's kernel config contained this.
```
# CONFIG_SND_HDA_INTEL_HDMI_SILENT_STREAM is not set
```
I tried rebuilding the kernel with void linux's config file (from `/proc/config.gz`) with that option both enabled and disabled. And I can confirm that enabling it does solve my problem. 

### Steps to reproduce

* Buy a computer with the same hardware as mine.
* Install void linux (I installed void for the first time only a couple of days ago).
* Use `alsamixer` or try to get sound working in any way (using the default kernel that comes with void.

PS: Thank you for this amazing distribution!!!!

**Comment by icp1994** [comment]
I had similar problem on my laptop which got fixed after installing `sof-firmware` and `alsa-ucm-conf`.

**Comment by medanisjbara** [comment]
@icp1994 Unfortunately, I just tried installing that, and it didn't work. I even went through the trouble of booting archlinux from a usb using voidlinux's kernel and installing `linux-firmware` and `alsa-firmware` (I didn't know about the packages you just provided. But I knew something else that might've worked so I tried it).  
I had no luck with both firmwares. Yet enabling that single option in the kernel configuration just solves my issue (at least temporarily).

So I believe this is a kernel problem. Not a firmware problem.

I booted void linux with the default void kernel (To gather some information about this) and sound didn't work even when I rebooted to the custom kernel. It just died. Looking at `dmesg`. There was this section that appeared at boot (and every time I try to `rmmod snd_hda_intel && modprobe snd_hda_intel`.)
```
[  396.917687] pcieport 0000:00:01.1: Data Link Layer Link Active not set in 1000 msec
[  396.917756] snd_hda_intel 0000:01:00.1: can't change power state from D3cold to D0 (config space inaccessible)
[  396.917885] snd_hda_intel 0000:01:00.1: Disabling MSI
[  396.917900] snd_hda_intel 0000:01:00.1: Handle vga_switcheroo audio client
[  396.917915] snd_hda_intel 0000:01:00.1: VGA controller is disabled
[  396.917917] snd_hda_intel 0000:01:00.1: Delaying initialization
[  396.929024] snd_hda_codec_realtek hdaudioC1D0: autoconfig for ALC285: line_outs=1 (0x14/0x0/0x0/0x0/0x0) type:speaker
[  396.929028] snd_hda_codec_realtek hdaudioC1D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[  396.929030] snd_hda_codec_realtek hdaudioC1D0:    hp_outs=1 (0x21/0x0/0x0/0x0/0x0)
[  396.929031] snd_hda_codec_realtek hdaudioC1D0:    mono: mono_out=0x0
[  396.929032] snd_hda_codec_realtek hdaudioC1D0:    inputs:
[  396.929032] snd_hda_codec_realtek hdaudioC1D0:      Mic=0x19
[  396.929033] snd_hda_codec_realtek hdaudioC1D0:      Internal Mic=0x12
[  397.589500] input: HD-Audio Generic Mic as /devices/pci0000:00/0000:00:08.1/0000:05:00.6/sound/card1/input18
[  397.589720] input: HD-Audio Generic Headphone as /devices/pci0000:00/0000:00:08.1/0000:05:00.6/sound/card1/input19
```
And then booting void with arch's `linux-zen` just fixed the problem again.

My assumption is that voidlinux's default kernel saves some faulty value somewhere which my custom kernel (void's config with `CONFIG_SND_HDA_INTEL_HDMI_SILENT_STREAM` enabled) is enable to overwrite. Hens the `can't change power state from D3cold to D0` in dmesg.  
My assumption is based on the existence of a [bug](https://wiki.archlinux.org/title/Backlight#Backlight_is_always_at_full_brightness_after_a_reboot_with_amdgpu_driver) where a value is not saved correctly which might cause problems but I am no expert.  
For all I know, enabling the option mentioned in the title fixes the problem as long as the last booted kernel is not the defaut kernel (the one who has that option not set).

Before I finish. I believe I should provide some hardware specifications. So here is the output of `lspci`
```
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne Root Complex
00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne IOMMU
00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:01.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe GPP Bridge
00:01.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:02.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:02.4 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge
00:08.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
00:08.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus
00:08.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir Internal PCIe GPP Bridge to Bus
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 51)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 51)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 0
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 1
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 2
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 3
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 4
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 5
00:18.6 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 6
00:18.7 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 7
01:00.0 VGA compatible controller: NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] (rev ff)
01:00.1 Audio device: NVIDIA Corporation Device 10fa (rev ff)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 16)
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8822CE 802.11ac PCIe Wireless Network Adapter
04:00.0 Non-Volatile memory controller: Solid State Storage Technology Corporation Device 9100 (rev 03)
05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev c7)
05:00.2 Encryption controller: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) Platform Security Processor
05:00.3 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
05:00.4 USB controller: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne USB 3.1
05:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] ACP/ACP3X/ACP6x Audio Coprocessor (rev 01)
05:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h/19h HD Audio Controller
06:00.0 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 81)
06:00.1 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 81)
```

**Comment by mvf** [comment]
`CONFIG_SND_HDA_INTEL_HDMI_SILENT_STREAM` just sets the default for a module parameter:
```
$ modinfo -p snd-hda-codec-hdmi | grep silent
enable_silent_stream:Enable Silent Stream for HDMI devices (bool)
```
To enable the parameter, run the following and reboot:
```
$ echo 'options snd-hda-codec-hdmi enable_silent_stream=1' | sudo tee /etc/modprobe.d/snd-hda-codec-hdmi.conf
```
Instead of rebooting, you can also try reloading any `snd-hda*` modules, but YMMV with that.

In any case, once the `snd-hda-codec-hdmi` module is `modprobe`d again, the parameter should be enabled:
```
$ cat /sys/module/snd_hda_codec_hdmi/parameters/enable_silent_stream
Y
```
The parameter is even runtime-switchable, although YMMV with that too:
```
$ echo 1 | sudo tee /sys/module/snd_hda_codec_hdmi/parameters/enable_silent_stream
1
```
You guessed it, `echo 0` to switch it off again.

**Comment by sgn** [comment]
5.19 has `CONFIG_SND_HDA_INTEL_HDMI_SILENT_STREAM`
