### ISSUE TITLE
ffmpeg: compile with nvdec

### ISSUE THREAD

**Issue by nvidiaLinuxUser** [void-linux/void-packages#38782]
NVDEC is the only hardware video acceleration available for NVIDIA graphics cards in Wayland. Please compile ffmpeg with nvdec support ([I think](https://github.com/archlinux/svntogit-packages/blob/20d3dd9476bf9bfd77eed044e2e1302bc846671c/trunk/PKGBUILD#L174) we need the `--enable-nvdec` flag).

https://github.com/void-linux/void-packages/issues/37469

**Comment by sgn** [comment]
We enabled VDPAU, this table should it should support NVIDIA https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by dataCobra** [comment]
Hey @sgn,

I've modified the template to enable nvdec.

Should I create a PR so @nvidiaLinuxUser can test it?

**Comment by nvidiaLinuxUser** [comment]
@sgn [VDPAU does not work in Wayland.](https://forums.developer.nvidia.com/t/wayland-information-for-r515-beta-release/214275#:~:text=The%20VDPAU%20library%2C%20used%20for%20hardware%20accelerated%20video%20decoding%20and%20presentation%2C%20does%20not%20have%20native%20Wayland%20support%20and%20does%20not%20work%20with%20Xwayland.)

**Comment by sgn** [comment]
So, that's fine. I don't have NVIDIA and I don't care much about Wayland, since Wayland is still have a working input method support, so I don't care much about those stuffs :-p You can try if it works.

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/pull/38829
