### ISSUE TITLE
`google-fonts-ttf` bugs out with regard to `AdobeBlank-Regular.ttf`

### ISSUE THREAD

**Issue by endigma** [void-linux/void-packages#38802]
### Is this a new report?

Yes

### System Info

Void 5.18.17_1 x86_64 AuthenticAMD notuptodate rFFFFF

### Package(s) Affected

google-fonts-ttf-20210628_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://aur.archlinux.org/packages/ttf-google-fonts-git (ctrl+f `blank`)

### Expected behaviour

The package should do `sudo rm -fr /usr/share/fonts/TTF/AdobeBlank-Regular.ttf` during the install process, this font is broken. https://aur.archlinux.org/packages/ttf-google-fonts-git#comment-574519 could also be a fix if included.

### Actual behaviour

`google-fonts-ttf` includes `/usr/share/fonts/TTF/AdobeBlank-Regular.ttf` which when installed breaks CJK (? other) character rendering in at least chrome, firefox (? others).

### Steps to reproduce

1. Install `google-fonts-ttf`
2. Open firefox/chromium
3. Visit yandex or google translate or deepl and translate `hello` to chinese simplified
4. Do it again after `sudo rm -fr /usr/share/fonts/TTF/AdobeBlank-Regular.ttf` (it will fix it)

**Comment by endigma** [comment]
Confirmed this bit
```xml
<selectfont>
    <rejectfont>
      <pattern>
        <patelt name="family">
          <string>Adobe Blank</string>
        </patelt>
      </pattern>
    </rejectfont>
  </selectfont>
  ```
  
  from [AUR comment](https://aur.archlinux.org/packages/ttf-google-fonts-git#comment-574519) fixes the issue.

**Comment by sgn** [comment]
I don't see broken Chinese characters.

**Comment by sgn** [comment]
Here are head of alphabetically sorted of fonts:
```
ABeeZee:style=Italic
ABeeZee:style=Regular
Abel:style=Regular
Abhaya Libre ExtraBold,Abhaya Libre:style=Regular,ExtraBold
Abhaya Libre Medium,Abhaya Libre:style=Regular,Medium
Abhaya Libre SemiBold,Abhaya Libre:style=Regular,SemiBold
Abhaya Libre:style=Bold
Abhaya Libre:style=Regular
Abril Fatface:style=Regular
Abyssinica SIL:style=Regular
Acme:style=Regular
Actor:style=Regular
Adamina:style=Regular
Adobe Blank:style=Regular
Advent Pro,Advent Pro ExtraLight:style=ExtraLight,Regular
Advent Pro,Advent Pro Light:style=Light,Regular
Advent Pro,Advent Pro Medium:style=Medium,Regular
Advent Pro,Advent Pro SemiBold:style=SemiBold,Regular
Advent Pro,Advent Pro Thin:style=Thin,Regular
Advent Pro:style=Bold
Advent Pro:style=Regular
Aguafina Script:style=Regular
Akaya Kanadaka:style=Regular
Akaya Telivigala:style=Regular
Akronim:style=Regular
Aksara Bali Galang:style=Regular
Aladin:style=Regular
Alata:style=Regular
Alatsi:style=Regular
Aldrich:style=Regular
Alef:style=Bold
Alef:style=Regular
Alegreya
Alegreya
```

**Comment by sgn** [comment]
d064d6c6da
