### ISSUE TITLE
Package request: eww

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#38800]
### Package name

eww

### Package homepage

https://github.com/elkowar/eww

### Description

Elkowars Wacky Widgets is a standalone widget system made in Rust that allows you to implement your own, custom widgets in any window manager.

![image](https://user-images.githubusercontent.com/45872139/185762924-a94db42d-a499-4edb-9fe3-8d7a26965179.png)
![img2](https://raw.githubusercontent.com/druskus20/eugh/master/polybar-replacement/.github/preview.png)

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
duplicate #37234
