### ISSUE TITLE
Klavaro segfaults on `musl`, Wayland

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#38815]
### Is this a new report?

Yes

### System Info

Void 5.18.9_1 x86_64-musl GenuineIntel uptodate rFFF

### Package(s) Affected

klavaro

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No.

### Expected behaviour

The program starts properly.

### Actual behaviour

Segfault.

### Steps to reproduce

1. Open terminal.
2. Launch `klavaro`

**Comment by sgn** [comment]
Can't reproduce
![Screenshot_2022-08-22_19-13-19](https://user-images.githubusercontent.com/42673067/185918562-5e70b7c3-8f7b-4126-8f68-ab2bc7a2a617.png)

**Comment by sgn** [comment]
Can you somehow post the error and/or backtrace?

**Comment by notramo** [comment]
It works when I set the `$GDK_BACKEND = x11` environment variable. But it crashes with Wayland backend.

**Comment by sgn** [comment]
Run with `sway`, too, not reproducible. I don't set any environment.
