### ISSUE TITLE
My system clock is four minutes behind. How do I fix it?

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#38918]
### Is this a new report?

Yes

### System Info

Void 5.18.19_1 x86_64 GenuineIntel uptodate hold rFF

### Package(s) Affected

openntpd

### Expected behaviour

When i login to my machine, it should report the correct time.log in

### Actual behaviour

It's 4 minutes behind. For example, if right now it is 14:20, my machine will show 14:16. I should manually restart openntpd service to fix this problem.

I'm using openntpd as "Network Time Protocol" implementation, but even switching to chrony has the same issue.

### Steps to reproduce

Just install openntpd and enable it's service.its

**Comment by Anachron** [comment]
Did you try to manually update it via https://wiki.archlinux.org/title/OpenNTPD#Error_adjusting_time ?

**Comment by LinArcX** [comment]
Why should i update it manually every time I restart my computer?

No, it's not working:

```
↳ sudo ntpd -d
Password:
ntpd: ntpd already running
```

As I said before, I can fix the issue by restarting the `openntpd` service, but I don't want to do that. It should work without manual intervention!

**Comment by Anachron** [comment]
So anything in the system log showing whats wrong with it? Or does it even believe it's uptodate?

Also would be good to disable the service and run it manually and increase verbosity until its figured out.

**Comment by sgn** [comment]
IIUC, `ntpd` tries to avoid drastically drift in time, I don't really know about `openntpd` but for chrony I think there're slew mode and step mode. Sometime your local clock's frequency isn't stable, too.

**Comment by LinArcX** [comment]
I figured out how to solve it without manual intervention. It's not an ideal solution, but... it's working for me.

Just add this line to the end of `visudo`:
`linarcx ALL=(ALL) NOPASSWD: /usr/bin/sv`

And put this line to .xinitrc:
`sudo sv restart openntpd`

**Comment by Duncaen** [comment]
That `NOPASSWD` rule basically gives you root right:

```
$ cat ~/sv/dwm/check
#!/bin/sh
id >&2
exit 0
$ sudo sv check ~/sv/dwm/
uid=0(root) gid=0(root) groups=0(root)
ok: run: /home/duncan/sv/dwm/: (pid 7389) 1133558s
```

If restarting openntpd later works, then there is probably an issue with the inital run, check the logs.
