### ISSUE TITLE
[tracking] Builds failing in *_patch()

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#38922]
Most of these happen because we used to ignore whitespace issues, but we don't do that anymore since 7b4119df5cbc0cc37348164a10c88a32910009d8. These packages can be fixed by applying the patch manually with `patch -Nlp1` and then generating the patch again.

- [x] GraphicsMagick
- [x] ck
- [x] dmg2img
- [x] exfat-dkms related PR: https://github.com/void-linux/void-packages/pull/38937
- [x] freeipmi
- [x] jfsutils
- [x] libtar
- [x] moc
- [x] pdfgrep
- [x] uwsgi
- [x] xzoom
- [x] yeahwm

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/pull/38937

**Comment by paper42** [comment]
everything fixed
