### ISSUE TITLE
radicale: owner mismatch for config and runit service

### ISSUE THREAD

**Issue by lemmi** [void-linux/void-packages#38923]
### Is this a new report?

Yes

### System Info

Void 5.18.19_1 x86_64-musl GenuineIntel/KVM uptodate rFF

### Package(s) Affected

radicale-3.1.8_1

### Expected behaviour

Radicale continues to work after an update or install without a `chown radicale:radicale /etc/radicale/*`

### Actual behaviour

`xbps-install` reset the owner in `/etc/radicale/*` to `root:root`. Together with the supplied permission, `radicale` started via the `runit` service isn't allowed to read the config and fails.

### Steps to reproduce

1. Install or update radicale
2. Use the provided runit service
3. breaks

**Comment by lemmi** [comment]
@teldra 
A possible solution I can think of is to not provide the config in `/etc/radicale`, but only have an example config in `/usr/share/example/radicale`.
I don't know why exactly the owner is reset or how to keep it. Maybe someone else has an idea.

**Comment by teldra** [comment]
Sry, for late answer.

I see the problem, when stopping to manage files in `/etc/radicale` now, existent config files will be deleted.

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/pull/49476
