### ISSUE TITLE
Can't install xz

### ISSUE THREAD

**Issue by davisi3** [void-linux/void-packages#38946]
Void 5.18.17_1 x86_64 
Hi! This is what I got when I try to install `xz`. System is updated 10min. before posting this issue. 

`liblzma-5.2.5_1 in transaction breaks installed pkg 'liblzma-devel-5.2.5_2' `
Transaction aborted due to unresolved dependencies.`

**Comment by Duncaen** [comment]
`liblzma-5.2.5_1` is really old, do you have some outdated local repo, using a dead mirror?

**Comment by davisi3** [comment]
Nope. I have no local repos. If I want to remove liblzma, I got this:

liblzma-5.2.5_2 in transaction breaks installed pkg `gdb-12.1_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `gimp-2.10.30_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `grub-2.06_2'
liblzma-5.2.5_2 in transaction breaks installed pkg `imlib2-1.9.0_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `karchive-5.96.0_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `kmod-30_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `libarchive-3.6.1_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `libavcodec-4.4.2_3'
liblzma-5.2.5_2 in transaction breaks installed pkg `libelf-0.187_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `libkmod-30_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `liblzma-devel-5.2.5_2'
liblzma-5.2.5_2 in transaction breaks installed pkg `libmagick-7.1.0.46_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `libxml2-2.9.13_3'
liblzma-5.2.5_2 in transaction breaks installed pkg `libzip-1.9.2_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `openttd-1.10.3_5'
liblzma-5.2.5_2 in transaction breaks installed pkg `python3-3.10.6_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `tiff-4.4.0_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `tor-0.4.7.10_1'
liblzma-5.2.5_2 in transaction breaks installed pkg `xen-libs-4.14.1_6'
Transaction aborted due to unresolved dependencies.

**Comment by Duncaen** [comment]
Just post the full `xbps-install -vd -S xz`, now you suddenly have the latest version of `liblzma`.

**Comment by davisi3** [comment]
https://0x0.st/o9FR.txt

**Comment by Duncaen** [comment]
So there is no issue?

**Comment by davisi3** [comment]
Yes. This command fixed it.

**Comment by Duncaen** [comment]
Ok, sync your repository `-S` if you want to install something.

**Comment by classabbyamp** [comment]
xi is roughly equivalent to xbps-install -S, yes

**Comment by paper42** [comment]
It is not the same though, xi will add your local repositories and consider them during the transaction which van easily break it if you have something old in your binpkgs.

If some docs say xi = xbps-install -S, it should be fixed.
