### ISSUE TITLE
Package request: update Zig to 0.9.1+

### ISSUE THREAD

**Issue by hiltjo** [void-linux/void-packages#38968]
### Package name

zig

### Package homepage

https://ziglang.org/

### Description

Please update Zig to the latest version.

Noticed while trying to compile Mepo, an OSM map viewer: https://git.sr.ht/~mil/mepo

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by paper42** [comment]
> Don't request update of package. We have a script for that. https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt . However, a quality pull request may help.

Please read the issue template you are filling out next time, zig is blocked on an llvm update.
