### ISSUE TITLE
`renderdoc` needs updating

### ISSUE THREAD

**Issue by OrichalcumCosmonaut** [void-linux/void-packages#38970]
The version of RenderDoc currently packaged is quite out-of-date; version 1.12 was released on 2021-01-28, almost 2 years ago.  It isn’t mentioned anywhere in https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt either.  The latest version is 1.21, released 2022-07-28.

**Comment by Johnnynator** [comment]
Interesting, the update check did work last in [void-updates_2022-05-28.txt](https://alpha.de.repo.voidlinux.org/void-updates/void-updates_2022-05-28.txt)

**Comment by Johnnynator** [comment]
The date after does have 1500 less entries, might be a more general issue.

**Comment by Johnnynator** [comment]
_log.txt also lists roughly 1000 more packages with `NO VERSION found`

**Comment by Duncaen** [comment]
Its github ratelimiting resulting in the versions only being found sometimes.

**Comment by OrichalcumCosmonaut** [comment]
Looks to have been fixed by <https://github.com/void-linux/void-packages/commit/4e19a5050962a0dc49f7becb8b846c0f4f07cb6f>.
