### ISSUE TITLE
dkms v3.0.6 does not create /var/lib/dkms which is needed to build dkms modules

### ISSUE THREAD

**Issue by tdm4** [void-linux/void-packages#39066]
### Is this a new report?

Yes

### System Info

Void 5.18.19_1 x86_64 GenuineIntel notuptodate rFFFF

### Package(s) Affected

dkms-3.0.6_1

### Expected behaviour

When dkms is installed fresh with version 3.0.6_1 it's supposed to create a /var/lib/dkms directory which is required for building DKMS modules.

### Actual behaviour

/var/lib/dkms is not created when package is installed fresh.

See this pull request: https://github.com/void-linux/void-packages/commit/efe694ed366e77a281c6e4745bc7e14ff686af3b

srcpkgs/dkms/template line 28:
-     vinstall dkms_dbversion 644 var/lib/dkms

(Line is removed -- this breaks a fresh install because it never creates /var/lib/dkms)

### Steps to reproduce

1. Fresh install of Void Linux
2. Install dkms
3. Try installing any -dkms package
4. DKMS fails to create the module

**Comment by tdm4** [comment]
Sorry forgot to mention original committer: @subnut

**Comment by ahesford** [comment]
Is the existence of the directory sufficient to resolve the issue?

**Comment by paper42** [comment]
> Is the existence of the directory sufficient to resolve the issue?

We discussed this on IRC and `mkdir /var/lib/dkms` solved it for @tdm4

**Comment by ahesford** [comment]
Please ping me if the latest revision doesn't resolve this issue.

**Comment by subnut** [comment]
Sorry. I honestly didn't realize that packages also created directories.

Lesson learnt. I won't make the same mistake in the future.

Thank you @tdm4 for digging into the root cause and pinging me.
