### ISSUE TITLE
zfs package fails to add dkms module

### ISSUE THREAD

**Issue by averycoolbean** [void-linux/void-packages#39087]
### Is this a new report?

Yes

### System Info

Void 5.18.19_2 x86_64-glibc

### Package(s) Affected

zfs-2.1.5_2

### Expected behaviour

package should add, build and install the zfs dkms module

### Actual behaviour

it fails with the simple error `Failed to add DKMS module: 'zfs-2.1.5'...` followed by the contrary `zfs: configured successfully.`

as a result the kernel module is missing, as youd expect

ive also noticed that if i manually try to use `dkms add` it returns `Error! No write access to DKMS tree at /var/lib/dkms`, which is probably related but im not smart enough to figure out how and what causes the issue

### Steps to reproduce

i am word for word following the zfsbootmenu single disk uefi instructions here: https://github.com/zbm-dev/zfsbootmenu/wiki/Void-Linux---Single-disk-UEFI
except using the latest kernel included with the base-system package (5.18) and nano for the text editor which really shouldnt be causing this

**Comment by paper42** [comment]
Does /var/lib/dkms exist? If not, update your system and it should be created which should fix this issue.

**Comment by averycoolbean** [comment]
no, it didnt, i probably should have mentioned that, nevertheless its working fine now, even without manually updating (ignoring how my laptop sounds like its about to take off like a helicopter cause it's compiling the module)

still strange that an issue that happened on 2 seperate install attempts in a row just ceased but whatever
