### ISSUE TITLE
Latest static XBPS not available in default repo

### ISSUE THREAD

**Issue by Haagen-Dazs** [void-linux/void-packages#39103]
### Is this a new report?

Yes

### System Info

Void 5.18.19_1 x86_64 AuthenticAMD uptodate FFF

### Package(s) Affected

xbps-static-latest.x86_64-musl.tar.xz

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No.

### Expected behaviour

Download latest static tarball `xbps-static-latest.x86_64-musl.tar.xz` from default repo https://repo-default.voidlinux.org/static/

### Actual behaviour

Missing file.

### Steps to reproduce

1. Go to default repo https://repo-default.voidlinux.org/static/
2. Compare to mirror https://void.cijber.net/static/
3. Verify that default repo misses latest static xbps package

**Comment by mhmdanas** [comment]
It seems to be there, at least now.
