### ISSUE TITLE
AQEMU segmentation fault

### ISSUE THREAD

**Issue by johna23-lab** [void-linux/void-packages#39101]
### Is this a new report?

Yes

### System Info

Void 5.18.19_1 x86_64 Genuine Intel

### Package(s) Affected

aqemu-0.9.4_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

"aqemu Segmentation fault" in google
https://forums.freebsd.org/threads/aqemu-segmentation-fault.85437/
https://github.com/tobimensch/aqemu/issues/92
etc..

### Expected behaviour

Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppcemb" element!

AQEMU Warning [30] >>>
Sender: void QEMU_IMG_Thread::Parse_Info( int exitCode, QProcess::ExitStatus exitStatus )
Message: QRegExp With Cluster Size Not Matched

And runs the GUI

### Actual behaviour

AQEMU Warning [2]
Sender: bool Emulator::Load( const QString &path )
Message: No "qemu-system-ppcemb" element!
Segmentation fault (core dumped)Segmentation fault (core dumped)

### Steps to reproduce

xbps-install aqemu
aqemu
Run the wizard to choose the qemu binary, then ... Segmentation fault (core dumped)

How to fix it
Grab this fork with the fix
(the fix)
https://github.com/nikitamos/aqemu/commit/dc19121a923c71eed248cd6310b9b06ec0af6abe

sudo xbps-install  qt5-devel libvncserver-devel git gcc pkg-config meson
git clone https://github.com/nikitamos/aqemu
cd aqemu
meson builddir
cd builddir
ninja
strip aqemu
./aqemu

And now the program works

**Comment by classabbyamp** [comment]
(note: fix is also PR'd but not yet merged https://github.com/tobimensch/aqemu/pull/116)

**Comment by ErinVoid** [comment]
Is this going to get fixed or another qemu gui frontend be provided?

**Comment by classabbyamp** [comment]
libvirt/virt-manager is another qemu frontend that exists
