### ISSUE TITLE
rpi400 no longer boots after kernel update 5.10 -> 5.15

### ISSUE THREAD

**Issue by TwinkleToes777** [void-linux/void-packages#39138]
### Is this a new report?

Yes

### System Info

Void 5.15.something glibc, rpi400

### Package(s) Affected

rpi4-kernel I think

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Not that I am aware of.

### Expected behaviour

To boot as usual and show something on the monitor.

### Actual behaviour

Does not boot, monitor stays black, it doesn't even get to the part of connecting to the monitor.

### Steps to reproduce

All I did is sudo xbps-install -Su, it installed 5.15 kernel, I rebooted and I got this problem.

Sorry for little information, as it cannot boot, I cannot execute any commands on it.

Another thing that may matter is I boot from SSD.

**Comment by TwinkleToes777** [comment]
Downloading rpi4 rootfs glibc and replacing my /boot content with its /boot content made it able to boot again, but back to kernel 5.10

**Comment by classabbyamp** [comment]
could you test booting from an SD card?

**Comment by Anachron** [comment]
Probably related:

https://github.com/raspberrypi/linux/issues/4930

**Comment by classabbyamp** [comment]
maybe, but the revert that should fix that issue is in the current rpi4-kernel release

**Comment by Anachron** [comment]
True, I guess we need to wait for OP to give us some more information and provide us with some error logs, `/boot/config.txt` and alike.

**Comment by classabbyamp** [comment]
@TwinkleToes777 , can you test #39442 ? just `xbps-install -R https://devspace.voidlinux.org/abby/rpi-merge -Su`

**Comment by TwinkleToes777** [comment]
> @TwinkleToes777 , can you test #39442 ? just `xbps-install -R https://devspace.voidlinux.org/abby/rpi-merge -Su`

Thank you! It works. :)

**Comment by enjewneer** [comment]
I had the same issue as @TwinkleToes777 but on my RPi4B. @classabbyamp's PR fixed it for me as well

**Comment by enjewneer** [comment]
> I had the same issue as @TwinkleToes777 but on my RPi4B. @classabbyamp's PR fixed it for me as well

Actually, not quite. Rebooting leads to the same issue as I was having before - black screen

**Comment by enjewneer** [comment]
> I had the same issue as @TwinkleToes777 but on my RPi4B. @classabbyamp's PR fixed it for me as well

I spoke too soon. Rebooting leads to the same issue as I was having before - black screen

**Comment by classabbyamp** [comment]
are you booting from an sd card or usb?

**Comment by enjewneer** [comment]
> are you booting from an sd card or usb?

Botting from USB. Works fine with the 20210930 void-rpi4 image so long as I change the root argument to /dev/sda2 in /boot/cmdline.txt. When I xbps-install -Su either from default repo or from yours, it does not boot. If I place /boot back on a SD card, I can then boot from sda2.

**Comment by classabbyamp** [comment]
does this work? https://github.com/raspberrypi/linux/issues/5123#issuecomment-1216350165

**Comment by enjewneer** [comment]
> does this work? [raspberrypi/linux#5123 (comment)](https://github.com/raspberrypi/linux/issues/5123#issuecomment-1216350165)

No, this doesn't work. I've substituted the VID/PID for my SATA-USB3 bridge. Same boot to black. I've tried it with a number of different bridges and storage mediums as well. I also tried using the RPi's USB2 ports and still no boot.

**Comment by classabbyamp** [comment]
hmm. I think it would be best to make a bug report upstream (and please link it here so I can track it too), because I don't know what's up.

**Comment by kenrap** [comment]
Is my PR related to this? #43600
