### ISSUE TITLE
teams exits if some one on call shares their screen

### ISSUE THREAD

**Issue by lokeshmohanty** [void-linux/void-packages#39131]
### Is this a new report?

Yes

### System Info

Void 5.18.19_1 x86_64 AuthenticAMD notuptodate rFFFF

### Package(s) Affected

teams-bin-1.5.00.10453_1

### Expected behaviour

I should be able to see the screen share of the other person on call

### Actual behaviour

The app exits if some one shares their screen

### Steps to reproduce

1. Start a call with some one.
2. Ask them to share their screen (tab or mobile).

**Comment by lokesh1197** [comment]
I tried to download teams-1.5.00.10453-1.x86_64.rpm package. Using rpmextract and running it works.

**Comment by Anachron** [comment]
Could you attach an error log from running it in the console or maybe even an strace?

**Comment by lokesh1197** [comment]
I tried unpacking the deb file(same one from template) using the same command in the template and even that works fine. So there is no problem with the deb package but with the template itself.

> Could you attach an error log from running it in the console or maybe even an strace?

```
Error while parsing hooks JSON. Error: "ENOENT: no such file or directory, open '/home/lokesh/.config/Microsoft/Microsoft Teams/hooks.json'"
(node:19643) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:19643) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ecsSettingsUpdated listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:19643) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 appInitialized listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
[19755:0916/203139.479431:FATAL:proc_util.cc(36)] Check failed: . : No such file or directory (2)
Server response:
Server response:
[19839:0916/203142.649213:FATAL:proc_util.cc(36)] Check failed: . : No such file or directory (2)
```
This is output during the call. If you need any extra information then please let me know.

**Comment by classabbyamp** [comment]
> `/home/lokesh/.config/Microsoft/Microsoft Teams/hooks.json`

does this file exist?

**Comment by lokesh1197** [comment]
`hooks.json` doesn't exist. I tried adding it with `{}` inside it. Still didn't work.

The current error that I get after adding `hooks.json` is reduced to 
```
[27460:0919/093012.245519:FATAL:proc_util.cc(36)] Check failed: . : No such file or directory (2)
```
Seems that some archlinux users are also facing this issue [https://answers.microsoft.com/en-us/msteams/forum/all/can-not-open-teams-app/9a9b90de-ee01-4d95-a226-36790e6b8811](https://answers.microsoft.com/en-us/msteams/forum/all/can-not-open-teams-app/9a9b90de-ee01-4d95-a226-36790e6b8811).

I tried searching for this online but all I found was that it was something related to chromium. So I installed chromium but still didn't get that file `proc_util.cc` and installing chromium didn't fix it.

**Comment by sgn** [comment]
It tried to open current directory: `.` but failed.
https://source.chromium.org/chromium/chromium/src/+/main:sandbox/linux/services/proc_util.cc;drc=098756533733ea50b2dcb1c40d9a9e18d49febbe;l=36

**Comment by Anachron** [comment]
Does this do anything? CnPed from learn.microsoft.com

> According to your error message, it seems your file location is missing hook.json file.
> 
> Based on my research, I found some customer also met this issue in Windows. But the error message is the same as yours. So you could try to follow these steps to see if it works for you:
> 
> 1)Close any instances of Microsoft Teams running.
> 2)Navigate to the following path: /home/gerry.creager/.config/Microsoft/Microsoft Teams
> 3)Create a json file called hooks.json
> 4)Add the following line to the newly created file: {“enableProcessIntegrityLevel”: false}
> 5)Save and close the file, then reopen Teams client.

**Comment by lokesh1197** [comment]
Followed it. Still getting the same error. I think I need to get the `proc_util.cc` file somehow but I don't know where to get it from.

Terminal Output:
```
(node:31847) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:31847) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ecsSettingsUpdated listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:31847) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 appInitialized listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
[31955:0925/133938.319047:FATAL:proc_util.cc(36)] Check failed: . : No such file or directory (2)
Server response:
Server response:
[32036:0925/133941.378786:FATAL:proc_util.cc(36)] Check failed: . : No such file or directory (2)
Server response:
Server response:
[32325:0925/134020.318487:FATAL:proc_util.cc(36)] Check failed: . : No such file or directory (2)
Server response:
Server response:
[32344:0925/134021.246870:FATAL:proc_util.cc(36)] Check failed: . : No such file or directory (2)
Server response:
Server response:
```

**Comment by sgn** [comment]
> Followed it. Still getting the same error. I think I need to get the `proc_util.cc` file somehow but I don't know where to get it from.

https://source.chromium.org/chromium/chromium/src/+/main:sandbox/linux/services/proc_util.cc;drc=098756533733ea50b2dcb1c40d9a9e18d49febbe;l=36

**Comment by fanyx** [comment]
Instead of crashing the entire app, other people's screen shares just stay black for me. It displays their profile picture in the center but the app itself stays alive and the call works fine otherwise.

I'm seeing the same logs, as well.

**Comment by lokesh1197** [comment]
@sgn I am not able identify where to place that file. And seeing /usr/lib/teams, I saw that it has an executable named chrome-sandbox. So likely there is some dependency on chromium. 

I am currently not able to debug it as I don't have sufficient knowledge and also lack the time at the moment. For now I am using the flatpak version as the direct launch from deb file was slow(gets slower and hangs frequently). I will come back to this once I get comfortable with void-linux. The issue can be closed if no one else currently focused on it.

Thanks for the suggestions

**Comment by classabbyamp** [comment]
you don't place that file anywhere, it's the part of the chromium source where the error originates

**Comment by lokesh1197** [comment]
@classabbyamp oh then any suggestions for me to try?

**Comment by Clos3y** [comment]
Should this issue be closed now since Microsoft have dropped Linux support for Teams? cf #42403 and #42449
