### ISSUE TITLE
[RFC] xbps repository for internal xbps-src and bootstrap packages

### ISSUE THREAD

**Issue by Duncaen** [void-linux/void-packages#39166]
It might be nice to create a xbps repository for packages that are supposed to be used by xbps-src only, like `-bootstrap` packages and maybe `chroot-*` packages.

This would avoid them showing up in default repository and avoids users installing `chroot-*` packages due to virtual packages by accident.

We would add `repository="bootstrap"` to templates and add that repository to the repository pool in `xbps-src`.

**Comment by classabbyamp** [comment]
+1, I would really like this for all the jdk bootstrap pkgs

**Comment by ahesford** [comment]
This is a great idea.

**Comment by Duncaen** [comment]
This has been implemented.
