### ISSUE TITLE
Package request: libXft 2.3.5

### ISSUE THREAD

**Issue by Cloufish** [void-linux/void-packages#39202]
### Package name

libXft 2.3.5

### Package homepage

https://gitlab.freedesktop.org/xorg/lib/libxft

### Description

Following many issues with rendering emojis and crashes for suckless software I think It's crucial to update this package 
https://github.com/void-linux/void-packages/issues/36637

It would even make request for libXft-bgra unnecessary because version 2.3.5 already supports it 
https://github.com/void-linux/void-packages/issues/24292

The template is ready to use: https://pastebin.com/raw/uHdXStNG
However, `dos2unix` might be required to get rid of '\r' newlines

Good vibrations

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by paper42** [comment]
> Don't request an update of a package, [We have a script for that](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.
