### ISSUE TITLE
problem with lutris on muscl systems 

### ISSUE THREAD

**Issue by abdulAttya** [void-linux/void-packages#39210]
### Is this a new report?

Yes

### System Info

Void 5.18.19_1 x86_64-musl GenuineIntel uptodate rFF

### Package(s) Affected

lutris

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

I found a (kinda) similar problem on this link
https://github.com/nix-community/pypi2nix/issues/110

### Expected behaviour

to run lutris (lol)

### Actual behaviour

`Traceback (most recent call last): File "/bin/lutris", line 52, in <module> from lutris.gui.application import Application # pylint: disable=no-name-in-module File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 39, in <module> from lutris.game import Game, export_game, import_game File "/usr/lib/python3.10/site-packages/lutris/game.py", line 17, in <module> from lutris.config import LutrisConfig File "/usr/lib/python3.10/site-packages/lutris/config.py", line 7, in <module> from lutris import settings, sysoptions File "/usr/lib/python3.10/site-packages/lutris/sysoptions.py", line 440, in <module> get_locale_choices() File "/usr/lib/python3.10/site-packages/lutris/sysoptions.py", line 37, in get_locale_choices locales = system.get_locale_list() File "/usr/lib/python3.10/site-packages/lutris/util/system.py", line 434, in get_locale_list with subprocess.Popen(['locale', '-a'], stdout=subprocess.PIPE) as locale_getter: File "/usr/lib/python3.10/subprocess.py", line 969, in init self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'locale'`

### Steps to reproduce

1 use voidlinux muscl
2 install lutris
3 run lutris
4 go to reddit and ask about the problem

**Comment by classabbyamp** [comment]
can you edit this to paste the traceback in a way that preserves the newlines? also use 3 backticks to surround it to make it a code block, which will also help with readability
