### ISSUE TITLE
Deadbeef xbps-src question (bugreport?)

### ISSUE THREAD

**Issue by AngryPhantom** [void-linux/void-packages#39228]
Sorry, guys, just couldn't find a way to contact you.

I just saw that you, @ScrelliCopter and @ericonr, updated Deadbeef player to [version 1.8.8](https://github.com/void-linux/void-packages/blob/master/srcpkgs/deadbeef/template). I'm not here to ask for a version bump, but to ask a question:

I want to update it myself with xbps-src to version **1.9.1**. In the template there are two commits (besides the main deadbeef release .tar.gz): **apbuild_commit** and **mp4p_commit**. Should I also _find_ these archives somewhere or what?

And yes, I can't update deadbeef myself. _Always couldn't_. Just don't know why? I'm going crazy. So, probably a bugreport. Or, maybe, it's the author's fault, idk.

I always get this:

```
=> ERROR: deadbeef-1.9.1_1: do_configure: '${configure_script} ${configure_args}' exited with 1
=> ERROR:   in do_configure() at common/build-style/gnu-configure.sh:8
```

P.S. Also found in the logs this:

`configure: error: Clang is required to build DeaDBeeF. Please check the README file.`

Any help would be greatly appreciated. And btw, how can I ask for a version bump?

```
Don't request an update of a package, We have a script for that:
https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt
```

How do I use it?

Thank you in advance.

**Comment by ahesford** [comment]
The best places to ask for general help about updating packages are the #voidlinux IRC channel on libera.chat and the [Void subreddit](https://www.reddit.com/r/voidlinux/).
