### ISSUE TITLE
How to select level compression zstd in xbps.-src?

### ISSUE THREAD

**Issue by johna23-lab** [void-linux/void-packages#39232]
It is possible to select the level compression in xbps-src? in this case (and more) we can save more than the 50%

 48M cross-x86_64-linux-musl-0.34_3.x86_64.tar.zst (using zstd --ultra -22 parameters)
110M cross-x86_64-linux-musl-0.34_3.x86_64.xbps (the original file)

**Comment by classabbyamp** [comment]
it's not possible because it's [hardcoded in xbps](https://github.com/void-linux/xbps/blob/master/bin/xbps-create/main.c#L1046)

**Comment by johna23-lab** [comment]
Thanks for the tip i modified the file 
xbps-create/main.c

And changed this section

if (compression == NULL || strcmp(compression, "zstd") == 0) {
		archive_write_add_filter_zstd(ar);
		archive_write_set_options(ar, "compression-level=22");
-
But if i make the package using the "xbps-create" it uses the level 22 and i get much better compression, but if i make the package using the xbps-src and the template i get the "normal" (low) compression.

The idea is that you can choose the level of compression (as a new option) with the xbps-src, e.g:
xbps-src -lc (level compression) 22 pkg template

**Comment by Chocimier** [comment]
> if i make the package using the xbps-src and the template i get the "normal" (low) compression.

xbps-src uses xbps installed inside masterdir, not the system one. You need to drop patch into srcpkgs/xbps/patches, build xbps with xbps-src and recreate masterdir.
