### ISSUE TITLE
Package request: ncspot

### ISSUE THREAD

**Issue by 1204-Wu-Brian** [void-linux/void-packages#39240]
### Package name

ncspot

### Package homepage

https://github.com/hrkfdn/ncspot

### Description

Cross-platform ncurses Spotify client written in Rust, inspired by ncmpc and the likes. 

It is a Spotify client with a much easier setup and configuration than spotifyd+spotify-tui

Requirements:
`dbus`, `libncurses`, `libssl`
`libpulse `(or portaudio, if built using the PortAudio backend)
`libxcb `(if built with the clipboard feature)
`ueberzug `(if built with the cover feature)

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment]
https://github.com/void-linux/void-packages/pull/33600
