### ISSUE TITLE
Package request: Cisco Packet Tracer

### ISSUE THREAD

**Issue by Positive205** [void-linux/void-packages#39294]
### Package name

cisco-packet-tracer

### Package homepage

https://www.netacad.com/courses/packet-tracer

### Description

Practice building simple and complex networks.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by Anachron** [comment]
https://www.netacad.com/courses/packet-tracer/faq#02

We cant package this, it's auth protected and old versions are automatically deleted on every new release:

https://www.netacad.com/courses/packet-tracer/faq#07
