### ISSUE TITLE
mame causes x86_64 builder to die when linking

### ISSUE THREAD

**Issue by maxice8** [void-linux/void-packages#3934]
https://build.voidlinux.eu/builders/x86_64_builder/builds/12462/steps/shell_3/logs/stdio

Linking takes over 4 hours and causes build.voidlinux.eu to be unresponsive since NGINX is swapped out and so everyone using the default xbps-src mirrors is locked out for 4 hours unless they switch.

**Comment by maxice8** [comment]
@pullmoll

**Comment by pullmoll** [comment]
I guess we need to specify `nodebug=yes` for all architectures then.
That reduces the memory footprint a lot and was already required for i686*.

**Comment by chneukirchen** [comment]
I think this is due to LTO being enabled by default.
