### ISSUE TITLE
Package request: Dooble

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#39353]
### Package name

dooble

### Package homepage

https://textbrowser.github.io/dooble/

### Description

Dooble, the scientific browser. Minimal, cute, and unusually stable.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by Eloitor** [comment]
This is what I tried so far:

```
# Template file for 'dooble'
pkgname=dooble
version=2022.06.15
revision=1
#wrksrc=
#create_wrksrc=yes
build_style=gnu-makefile
hostmakedepends="qt5-qmake"
makedepends="qt5-charts-devel qt5-webengine-devel qt5-webchannel-devel qt5-location-devel"
short_desc="Dooble, the scientific browser. Minimal, cute, and unusually stable"
maintainer="Eloi Torrents <elotor@disroot.org>"
license="GPL-3.0-or-later"
homepage="https://textbrowser.github.io/dooble/"
distfiles="https://github.com/textbrowser/dooble/archive/refs/tags/${version}.tar.gz"
checksum=3af9a06c477f9317cf279389bd66237109fa205fb5526f4df7909250dc2c8e41

do_configure() {
  qmake -o Makefile dooble.pro
}
```

I don't know what license code to put, and this template gives me this error: https://pastebin.com/erFsw630

**Comment by sgn** [comment]
Use qmake build-style. Not sure if it works ootb. If not maybe `CFLAGS=-fPIC` and `CXXFLAGS=-fPIC`

**Comment by Eloitor** [comment]
Thank you now my template is
```
# Template file for 'dooble'
pkgname=dooble
version=2022.06.15
revision=1
build_style=qmake
configure_args="dooble.pro"
hostmakedepends="qt5-qmake"
makedepends="qt5-charts-devel qt5-webengine-devel qt5-webchannel-devel qt5-location-devel"
depends=""
short_desc="Dooble, the scientific browser. Minimal, cute, and unusually stable"
maintainer="Eloi Torrents <elotor@disroot.org>"
license="GPL-3.0-or-later"
homepage="https://textbrowser.github.io/dooble/"
distfiles="https://github.com/textbrowser/dooble/archive/refs/tags/${version}.tar.gz"
checksum=3af9a06c477f9317cf279389bd66237109fa205fb5526f4df7909250dc2c8e41
```
Now the compilation works fine but the installation phase don't.
https://pastebin.com/8hd1dqPh

**Comment by sgn** [comment]
> make: Nothing to be done for 'install'.

Their `*.pro` file is broken. Please write a `do_install` function and install manually.

**Comment by Eloitor** [comment]
Thank you, now my template works, but I don't know which license to put
https://github.com/void-linux/void-packages/pull/39405

**Comment by sgn** [comment]
> Thank you, now my template works, but I don't know which license to put #39405

https://github.com/textbrowser/dooble/blob/master/Source/dooble_main.cc#L2-L25 `BSD-3-Clause`
