### ISSUE TITLE
wireplumber-0.4.11_2 [unpack] failed to extract file [....]

### ISSUE THREAD

**Issue by 38github** [void-linux/void-packages#39362]
### Is this a new report?

Yes

### System Info

Void 5.18.19_1 x86_64 GenuineIntel notuptodate rFF

### Package(s) Affected

wireplumber-0.4.11_2

### Expected behaviour

Unpack and succeed.

### Actual behaviour

wireplumber-0.4.11_2: unpacking ...
ERROR: wireplumber-0.4.11_2: [unpack] failed to extract file `./etc/sv/wireplumber/supervise': Directory not empty
ERROR: wireplumber-0.4.11_2: [unpack] failed to extract files: Directory not empty
ERROR: wireplumber-0.4.11_2: [unpack] failed to unpack files from archive: Directory not empty
Transaction failed! see above for errors.

### Steps to reproduce

1. sudo xbps-install -Su
2. I choose 'Yes' to install the packages
3. It starts the process.
4. Fails

**Comment by paper42** [comment]
Similar to https://github.com/void-linux/void-packages/issues/33815, follow what's written in that issue to fix this. In this case I think this is just a user error, supervise was never a directory in the package.

**Comment by 38github** [comment]
> I think this is just a user error

I did not created that directory but I solved it by removing the /etc/sv/wireplumber/supervise folder. Thank you for the help.
