### ISSUE TITLE
Easyeffects missing package lsp-plugins?

### ISSUE THREAD

**Issue by 38github** [void-linux/void-packages#39439]
When I used Easyeffects, and added an equalizer, nothing happened when I adjusted the bands. I looked up if lsp-plugins was missing and discovered that the package lsp-plugins is not available on Void Linux.

Is this why the equalizer does nothing?

**Comment by paper42** [comment]
duplicate of https://github.com/void-linux/void-packages/issues/32991

**Comment by 38github** [comment]
Do you think it is legit to remove Easyeffects since it is mostly a placebo application at the moment?

**Comment by paper42** [comment]
Definitely no. Even if we don't have lsp-plugins installed, there is a lot of plugins that use different packages.

**Comment by Elvyria** [comment]
I have a [draft](https://github.com/Elvyria/voids-package-nightmare/blob/main/srcpkgs/lsp-plugins/template) for a template if someone's interested in maintaining.

**Comment by paper42** [comment]
#33672 #31664 #29932
