### ISSUE TITLE
bind: -g option disables logging

### ISSUE THREAD

**Issue by TitaniumHocker** [void-linux/void-packages#39440]
Hey!
Current [runit file](https://github.com/void-linux/void-packages/blob/master/srcpkgs/bind/files/named/run#L5) for `bind` disables all logging with `-g` option:
```
# man named | grep -- -g
       -g     This option runs the server in the foreground and forces all
                logging to stderr.
```
So it's impossible to config logging with default `bind` configuration. Is there any reason for that or maybe it's just a mistake?

**Comment by TitaniumHocker** [comment]
Sorry, I found that standard bind logging is [broken in void](https://github.com/void-linux/void-packages/commit/6041f96bef58174255e6db66428a3c866e59dab6)

**Comment by sgn** [comment]
You can enable socklog service for logging.
