### ISSUE TITLE
Package request: fim

### ISSUE THREAD

**Issue by jose1711** [void-linux/void-packages#39483]
### Package name

fim

### Package homepage

https://www.nongnu.org/fbi-improved/

### Description

FIM is a lightweight universal image viewer, mostly for Linux (but not only).  
FIM aims to be a highly customizable and scriptable image viewer for users who are comfortable with software like the VIM text editor (see [this minitutorial](https://www.nongnu.org/fbi-improved/#tutorial_vim)) or the Mutt mail user agent (see [this minitutorial](https://www.nongnu.org/fbi-improved/#tutorial_mutt)).  
It has been developed with Linux in mind, but can be built to run on several Unix systems or even on MS-Windows.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/fim/template
