### ISSUE TITLE
ZFS DKMS build fails on freshly installed system

### ISSUE THREAD

**Issue by drichline** [void-linux/void-packages#39539]
### Is this a new report?

Yes

### System Info

Void 5.19.10_1 x86_64 GenuineIntel/VM uptodate rFF

### Package(s) Affected

zfs-2.1.5_3

### Expected behaviour

I installed a fresh Void system, updated with xbps-install -Su, rebooted into kernel 5.19 (also tested with linux-lts, same result), and attempted to install ZFS. 

### Actual behaviour

On installing (and reinstalling) ZFS, this is the end of the xbps output:
```zfs-2.1.5_3: configuring ...
Added DKMS module 'zfs-2.1.5'.
Skipping kernel-5.13.19_1. kernel-headers package not installed...
Building DKMS module 'zfs-2.1.5' for kernel-5.19.10_1... Killed
```
Manually building with the DKMS module (sudo dkms build zfs/2.1.5) ended with a segmentation fault in gcc and the attached [make.log](https://github.com/void-linux/void-packages/files/9682842/make.log) file. 

### Steps to reproduce

(Please note, this is my first time using void. I reinstalled and tried again to make sure it wasn't a fluke)
1. Install a fresh void system (tried with both local and netinstall)
2. Sync/update system and reboot
3. xbps-install zfs
4. DKMS fails, even on kernels <5.18

**Comment by ahesford** [comment]
I can't reproduce this using the [ZFSBootMenu test environment](https://github.com/zbm-dev/zfsbootmenu/tree/master/testing) modified to install `linux5.19` and its headers.

I recommend you run `xbps-pkgdb -a` to confirm that everything on your system is as expected.

**Comment by ahesford** [comment]
The mtime mismatch would be expected if `/boot` is, *e.g.*, on a FAT file system. What is your CPU?

**Comment by drichline** [comment]
I'm so sorry, all this troubleshooting was entirely self-inflicted: my VM had 512 MB of memory with no swap, which was not enough to compile the module. Thank you again for all the help 💜

> The mtime mismatch would be expected if `/boot` is, _e.g._, on a FAT file system. What is your CPU?

It was MBR/vfat so I wouldn't have to mess with EFI boot. The CPU is GenuineIntel Skylake (i5-10210U)
