### ISSUE TITLE
libunistring: `u32_move` segfaults on musl

### ISSUE THREAD

**Issue by tranzystorek-io** [void-linux/void-packages#39624]
### Is this a new report?

Yes

### System Info

Void 5.19.10_1 x86_64-musl GenuineIntel/VM uptodate FF

### Package(s) Affected

libunistring-1.0_1

### Expected behaviour

Tests for the `boxes` project run correctly

### Actual behaviour

One of the tests segfaults (https://github.com/ascii-boxes/boxes/issues/103#issuecomment-1264611505)

### Steps to reproduce

On a x86_64-musl void system (e.g. `ghcr.io/void-linux/void-linux:latest-full-x86_64-musl`):

1. `xbps-install bison flex libunistring-devel pcre2-devel xxd git base-devel`
2. `git clone https://github.com/ascii-boxes/boxes`
3. `cd boxes && make && make test`

**Comment by tranzystorek-io** [comment]
Same scenario run on alpine doesn't cause a segfault, which suggests our build of `libunistring` might be flawed.

**Comment by sgn** [comment]
Their code is broken, not our libunistring:
```diff
diff --git a/src/Makefile b/src/Makefile
index e1a1827..5b38eab 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -14,6 +14,7 @@
 
 
 CC         = gcc
+CFLAGS_ADDTL = -O0 -g -pipe
 
 OUT_DIR    = ../out
 SRC_DIR    = ../src
@@ -65,7 +66,6 @@ debug: flags_$(BOXES_PLATFORM) | $(OUT_DIR)
 
 boxes: $(ALL_OBJ) | check_dir
 	$(CC) $(LDFLAGS) $^ -o $@ -lunistring -lpcre2-32
-	if [ "$(STRIP)" = "true" ] ; then strip $@ ; fi
 
 boxes.static: $(ALL_OBJ) | check_dir
 	$(CC) $(LDFLAGS) $^ -o $(BOXES_EXECUTABLE_NAME) -l:libunistring.a -l:libpcre2-32.a
diff --git a/src/remove.c b/src/remove.c
index c4dae4b..4346edb 100644
--- a/src/remove.c
+++ b/src/remove.c
@@ -986,7 +986,7 @@ int remove_box()
                         (int) (input.lines[j].num_chars - c + 1), (int) input.lines[j].posmap[c]);
             #endif
             u32_move(input.lines[j].mbtext, input.lines[j].mbtext + input.lines[j].posmap[c],
-                     input.lines[j].num_chars - c + 1);  /* +1 for zero byte */
+                     input.lines[j].num_chars - input.lines[j].posmap[c] + 1);  /* +1 for zero byte */
             input.lines[j].num_chars -= c;
         }
     }

```
