### ISSUE TITLE
ffmpeg fails at pkg_install stage

### ISSUE THREAD

**Issue by ysk81** [void-linux/void-packages#39648]
### Is this a new report?

Yes

### System Info

Void 5.19.10_1 x86_64

### Package(s) Affected

ffmpeg-4.4.2_3

### Expected behaviour

Default flags and configure options used. So, .xbps package built was expected.

### Actual behaviour

(exit 1) at ffplay-4.4.2_3 pkg_install stage with "No such file or directory" error.

```
=> ffplay-4.4.2_3: running pkg_install ...
mv: cannot stat '/destdir//ffmpeg-4.4.2/usr/bin/ffplay': No such file or directory
=> ERROR: ffplay-4.4.2_3: pkg_install: 'mv ${DESTDIR}/$files ${PKGDESTDIR}/${_targetdir}' exited with 1
=> ERROR:   in _vmove() at common/environment/setup/install.sh:219
=> ERROR:   in _noglob_helper() at common/environment/setup/install.sh:12
=> ERROR:   in pkg_install() at srcpkgs/ffplay/template:216
```

### Steps to reproduce

xbps-src -N pkg ffmpeg

**Comment by classabbyamp** [comment]
does it work if you xbps-src clean and try again?

**Comment by ysk81** [comment]
> does it work if you xbps-src clean and try again?

yes done it twice. again. same. double slashes at "/destdir//ffmpeg-4.4.2/" looks suspicous to me.

**Comment by classabbyamp** [comment]
an empty directory name is elided, the double slash is fine

**Comment by paper42** [comment]
I can reproduce

**Comment by classabbyamp** [comment]
was actually failing to enable ffplay at configure because the sdl2 version check was failing
