### ISSUE TITLE
firefox: significantly slower than Mozilla's .tar release

### ISSUE THREAD

**Issue by noarchwastaken** [void-linux/void-packages#39652]
### Is this a new report?

Yes

### System Info

Void 5.19.10_1 x86_64 GenuineIntel uptodate rrmFFFFFFFFFFFFFF

### Package(s) Affected

firefox-105.0.1_1

### Expected behaviour

The `firefox` package should run about as fast as the one from mozilla.org.

### Actual behaviour

I tested the two different builds of Firefox:
- With entirely new profiles
- With my daily profile that has anti-fingerprinting tweaks and loaded with addons

And the package from Void repository runs consistently slower than the "Official" release, both in synthetic benchmarks:
![image](https://user-images.githubusercontent.com/72779101/193509215-d08a75e3-eebd-4476-b411-f8cb55238c6f.png)
![image](https://user-images.githubusercontent.com/72779101/193509256-6e8f4c5c-c812-4b29-8f14-7f7282368fd1.png)

and in subjective terms, such as pages loading slower.

### Steps to reproduce

1. Install Firefox from the `firefox` package as well as from https://www.mozilla.org/en-US/firefox/all/#product-desktop-release
2. Browse the web and pay attention to performance differences

**Comment by dmarto** [comment]
Got curious, decided to test it for myself. 

VOID XBPS
![2022-10-03_13-54](https://user-images.githubusercontent.com/1244744/193560870-ab9e9c3d-3c59-4369-8d5d-34ed760b832e.png)

MOZILLA
![2022-10-03_13-52](https://user-images.githubusercontent.com/1244744/193560909-2f27e2a1-9f89-4695-8202-83d6860995d4.png)

**Comment by Duncaen** [comment]
Yes, we don't have enough build resources to do profile guided optimizations.
