### ISSUE TITLE
Package request: Tuner

### ISSUE THREAD

**Issue by MechDR** [void-linux/void-packages#39706]
### Package name

Tuner

### Package homepage

https://github.com/louis77/tuner

### Description

It's a radio streaming app similar to Shortwave. Now that Shortwave is no longer maintained, this seems like a good alternative. Everything that's needed to compile it is already in the default Void repository.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by tranzystorek-io** [comment]
Made https://github.com/tranzystorek-io/void-packages/blob/tuner/srcpkgs/tuner/template but my pipewire config won't work so I wouldn't mind someone testing this on pulse or even stealing from me :P

**Comment by MechDR** [comment]
> EDIT: the package works now, but I don't use gnome so would rather not maintain it

Would you like me to maintain it? I use it regularly ;).

**Comment by tranzystorek-io** [comment]
If you'd like, go ahead! In case you need some guidance, Me and other maintainers can help you on the [#voidlinux](ircs://irc.libera.chat/#voidlinux) IRC channel

**Comment by MechDR** [comment]
Yeah, I will probably need some help, I'm kinda new to packaging, though I managed to make a template for AnyDesk x86 and it works, based on the maintainer's old work, but still, it was just modding the template to make it work :).

Thanks :).

So, do I clone it, then push changes from local to my clone repo, then to main, or... :)... kinda new as you can see xD.

**Comment by tranzystorek-io** [comment]
Take a look at https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md, but in a nutshell:

1. Fork the void-packages repo
2. On the fork, create a new branch, e.g. `tuner`
3. Copy over my template and change the `maintainer` to yourself
4. Push that branch to your fork and create a PR to this origin void-packages repo

**Comment by MechDR** [comment]
Oh, OK, thanks :). Will read the text and thanks for the help :).

**Comment by Eloitor** [comment]
@tranzystorekk I couldn't find your template, do you have it somewhere?

**Comment by tranzystorekk** [comment]
@Eloitor I must have deleted that branch when I was doing some clean up, sorry!

**Comment by MechDR** [comment]
@Eloitor I still have it in my repo.

https://github.com/MechDR/void-packages/blob/tuner/srcpkgs/tuner/template

**Comment by Eloitor** [comment]
I'll maintain it then, thanks!

**Comment by MechDR** [comment]
They might not accept it, it uses `libsoup2` and the app hasn't seen any updates in a year, so there are no plans to switch to `libsoup3`.

**Comment by MechDR** [comment]
In case anyone needs it.

````
# Template file for 'tuner'
pkgname=tuner
version=1.5.1
revision=1
build_style=meson
hostmakedepends="glib gettext pkg-config vala"
makedepends="geoclue2-devel geocode-glib-libsoup2-devel glib-devel libglib-devel
 granite-devel gst-plugins-bad1-devel gstreamer1-devel gtk+3-devel json-glib-devel
 libgee08-devel libsoup-devel"
depends="gst-plugins-good1 gst-libav"
short_desc="GNU/Linux app to discover and play internet radio stations"
maintainer="someone <someone@some.one>"
license="GPL-3.0-or-later"
homepage="https://github.com/louis77/tuner"
# In case the original project and releases are deleted from GitHub, uncomment the
# line below and comment out the line after that.
#distfiles="https://web.archive.org/web/20240412222507if_/https://codeload.github.com/louis77/${pkgname}/tar.gz/refs/tags/${version}>${pkgname}-${version}.tar.gz"
distfiles="https://github.com/louis77/${pkgname}/archive/refs/tags/${version}.tar.gz>${pkgname}-${version}.tar.gz"
checksum="bbb5e7c97da1ee495651d85aca33c2fe58daba81906ae247e12b6a41b1ed7592"

post_extract() {
	# Patch for meson >= 1.3.0
	sed -i 's@pkgconfig@pkg-config@g' com.github.louis77.tuner.yml
	# Cosmetic version patches
	sed -i 's@1.5.0@1.5.1@g' data/com.github.louis77.tuner.appdata.xml.in
	sed -i 's@1.5.0@1.5.1@g' src/Application.vala
	sed -i 's@1.5.0@1.5.1@g' meson.build
}
````
