### ISSUE TITLE
Package request: Electrum Personal Server (EPS)

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#39723]
### Package name

electrum-personal-server

### Package homepage

https://github.com/chris-belcher/electrum-personal-server

### Description

The [Bitcoin Wiki](https://en.bitcoin.it/wiki/Electrum#Electrum_Personal_Server) explains the role of EPS in detail:

> Electrum Personal Server has a different approach to a normal server. It is intended to be used by a single person only. Instead of creating a database of every transaction and address ever used on the bitcoin blockchain, Electrum Personal Server only tracks the user's own wallets. This allows it to be much more efficient with resources, it does not need any extra data files and is compatible with [Bitcoin Core](https://en.bitcoin.it/wiki/Bitcoin_Core)'s pruning feature.
>
> Electrum Personal Server is probably the best way to combine Electrum's feature-richness (hardware wallet integration, multi-signature, [seed phrase](https://en.bitcoin.it/wiki/Seed_phrase), etc) with a [full node](https://en.bitcoin.it/wiki/Full_node)'s strong security and privacy.

I'd like this package to be managed by xbps, since it has features other servers lack support.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by thatfatblackcat** [comment]
Can someone explain me why isn't there still any comment? If there's something I missed, please let me know.

**Comment by paper42** [comment]
> Can someone explain me why isn't there still any comment? If there's something I missed, please let me know.

Nobody was interested in this package enough to leave a useful comment or open a PR to include the package. We are all volunteers and package requests do not say what we have to do, they are just leads that can be used to see if there are people interested in having the package.

**Comment by thatfatblackcat** [comment]
I understand you're all volunteers, and you're also doing a great job. There are more packages here on void than on the main arch repos. I know EPS is a niche package, and not nearly as popular as some wm, but for a small group of people it's necessary. I'm going to keep this issue open for people to discuss in the future. Thank you for the answer.
