### ISSUE TITLE
apache-ant fails building

### ISSUE THREAD

**Issue by ysk81** [void-linux/void-packages#39753]
### Is this a new report?

Yes

### System Info

Voild 5.19.13_1 x86-64

### Package(s) Affected

apache-ant-1.10.12_1

### Expected behaviour

auto download "ftp://ftp.software.ibm.com/software/awdtools/netrexx/NetRexx.zip" file during build amd complete building pkg.

### Actual behaviour

build script fails with sha-256 checksum mismatch error for file "ftp://ftp.software.ibm.com/software/awdtools/netrexx/NetRexx.zip".
Tried to download file via wget and figured the downloaded size is twice the reported file size from ftp server.
Tried again with --no-passive-ftp and this time size was correct.
Coppied the downloaded file to /buildder/apache-ant-1.10.12/?/.ant/tempcache/
and ran ./xbps-src -N pkg apache-ant again.
This time build was successfull. 
So, if we can have build script to not use passive ftp, the problem might be solved.

### Steps to reproduce

xbps-src -N pkg apache-ant

**Comment by frankenstein91** [comment]
I have a problem with the same ZIP file
ftp://ftp.software.ibm.com/software/awdtools/netrexx/NetRexx.zip

```
BUILD FAILED
/opt/ant-src/fetch.xml:405: sun.net.ftp.FtpLoginException: Invalid username/password
	at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:341)
	at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:790)
	at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:699)
	at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:689)

```

**Comment by lchrennew** [comment]
> I have a problem with the same ZIP file ftp://ftp.software.ibm.com/software/awdtools/netrexx/NetRexx.zip
> 
> ```
> BUILD FAILED
> /opt/ant-src/fetch.xml:405: sun.net.ftp.FtpLoginException: Invalid username/password
> 	at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:341)
> 	at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:790)
> 	at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:699)
> 	at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:689)
> ```

Same problem

**Comment by echuber2** [comment]
Hi, I ran into the same problem somewhere else and I saw this issue in a search. It looks like apache ant has fixed this in their upstream:

https://github.com/apache/ant/commit/541a1d2448af3e95134f79a970a608403deab00a

**Comment by classabbyamp** [comment]
no longer FTBFS
