### ISSUE TITLE
Broken atom and nodejs-lts (xbps-create?)

### ISSUE THREAD

**Issue by solbjorn** [void-linux/void-packages#398]
I've finally found a reason why atom and nodejs-lts packages are broken for now.

When running `xbps-src install <pkgname>`, both applications works correctly from destdir. But somehow several files and directories are missing from _.xbps_ package after packaging is done. This can be seen through `diff -aurq destdir <extracted package dir>`, I summarized output for both pkgs here: https://gist.github.com/solbjorn/38319acac00d932d301414e7d19847f8

As I understand, it happens inside _xbps-create_. Can't see any logics on skipping files, maybe it's because of too long filepaths or smth like this.
Both uunshare and uchroot styles are affected. I also don't understand why nodejs (stable version) doesn't suffer from that.

**Comment by nachisan** [comment]
May have something to do with https://github.com/void-linux/xbps/issues/2

**Comment by solbjorn** [comment]
@nachisan, yep, both issues describe the same problem.

**Comment by alexjarosch** [comment]
@Gottox just committed a fix for this issue (https://github.com/void-linux/xbps/commit/3ef932de2f86b239bc7b0d5d3b8784b3c2ebdb74). I am time constrained today, can you @solbjorn check if atom works now. Else I check on Monday.

**Comment by solbjorn** [comment]
@alexjarosch, yep, I've already seen, but unfortunately have Void only at work and could check at least on Monday too.

**Comment by alexjarosch** [comment]
@broughjt Basically you need to:

1. clone the latest xbps repo
2. compile and install under /usr (with --prefix=/usr in the configure)
3. make sure your system is using the new xbps with the fix of Gottox
4. clone this repo
5. modify the atom template to use 1.28.1 (I have troubles right now with the 1.26.1 version of atom)
6. make the install package with xbps-src
7. install that packages and check if everything is there.

I am currently working down the list with limited time, but you are welcome to try!

**Comment by alexjarosch** [comment]
I was able to confirm that the new version of @Gottox fixes the atom issue, see https://github.com/void-linux/xbps/issues/2

**Comment by alexjarosch** [comment]
Just made a pull request to update atom to 1.28.1 (https://github.com/void-linux/void-packages/pull/759). This should work soon again. Gottox schedules a new release of xbps soon (https://github.com/void-linux/xbps/issues/2).

**Comment by solbjorn** [comment]
I confirm that nodejs-9.10.0_2 and atom-1.28.2_1 locally built with xbps-0.53_4 are fully workable now. The only things left are to bump versions/revisions of affected packages and rebuild them with Buildbot -- and we're done here.
