### ISSUE TITLE
able to mark package orphans as normall installed ?

### ISSUE THREAD

**Issue by superiums** [void-linux/void-packages#39808]
as there is an option to remove package orphans, we could clear unused dependencies easily.

but sometimes , there is something useful. could i keep them away from orphans (mark them as installed independently).

#### example
after i installed wayland, i removed xorg.
but i keeped **the video drivers** and something else which was installed by xorg.
i don't want these packages to be removed by ` xbps-remove -o `.

**Comment by classabbyamp** [comment]
[`xbps-pkgdb -m manual`](https://man.voidlinux.org/xbps-pkgdb#m,)
