### ISSUE TITLE
Missing supervise file when installing bluez

### ISSUE THREAD

**Issue by y-mx-b** [void-linux/void-packages#39811]
### Is this a new report?

Yes

### System Info

Void 5.19.13_1 x86_64-musl GenuineIntel uptodate rFF

### Package(s) Affected

bluez-5.65_1

### Expected behaviour

Expected `/run/runit/supervise.bluetoothd` and `/run/runit/supervise.bluetoothd-log` to be created. 

### Actual behaviour

`/etc/sv/bluetoothd/supervise` and `/etc/sv/bluetoothd/log/supervise` are dangling symlinks.

### Steps to reproduce

```
$ sudo xbps-install bluez
...
$ sudo sv up bluetoothd
warning: bluetoothd: unable to open supervise/ok: file does not exist
```

**Comment by Duncaen** [comment]
`runsv` follows the symlink and creates the directory. You probably haven't enabled the service `ln -s /etc/sv/bluetoothd /var/service/`.

**Comment by y-mx-b** [comment]
> `runsv` follows the symlink and creates the directory, `/run` is a temporary file system, they have to be created at runtime. Something else is wrong with your system.

Any clues what could be wrong? I didn't have any troubles setting Bluetooth up on Void Linux on a different laptop. I followed the same procedure, installing `dbus` and `bluez` and symlinking the stuff in `etc/sv/` to `var/service`, but `bluetoothd` isn't starting up.

**Comment by Duncaen** [comment]
No idea, not enough info. check the symlink, check the if the runsv process started. Maybe try unlinking and relinking.

**Comment by y-mx-b** [comment]
It seems the runsv process for bluetoothd isn't being started for some reason. Unlinking and relinking doesn't help. Also, is `/var/service` supposed to be symlinked to `/etc/sv/dbus`? That just seems odd to me. From what I could gather in the [Services and Daemons] page, it looks like it should be symlinked to `/etc/runit/runsvdir/current` instead? Symlinking there seems to run the daemon.

**Comment by Duncaen** [comment]
Yes that symlink is wrong, you probably overwrote it while trying to enable dbus.

```
xbps-install -f  runit
````

**Comment by y-mx-b** [comment]
Thank you, everything's working again now! That was such a silly mistake on my part hahah.
