### ISSUE TITLE
Package request: zen-kernel (linux-zen)

### ISSUE THREAD

**Issue by orowith2os** [void-linux/void-packages#39842]
### Package name

linux-zen

### Package homepage

https://liquorix.net/ https://zen-kernel.org

### Description

The Zen kernel is a modified Linux kernel, meant to include things that the normal Linux kernel doesn't so as to improve the desktop experience, such as a scheduler set to make the desktop feel more responsive at the cost of increased power usage.

Looking at the linux-libre package request, it was denied due to Void not shipping modified kernels in 2019. Could an exception be made for this package?

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by Anachron** [comment]
I don't think something has changed since https://github.com/void-linux/void-packages/issues/5105#issuecomment-455458790, https://github.com/void-linux/void-packages/issues/14062#issuecomment-526480363 and https://github.com/void-linux/void-packages/issues/32916#issuecomment-917366821.
