### ISSUE TITLE
python3-matplotlib-3.6.0_1: ModuleNotFoundError: No module named 'contourpy'

### ISSUE THREAD

**Issue by tornaria** [void-linux/void-packages#39845]
### Is this a new report?

Yes

### System Info

Void 5.19.10_1 x86_64

### Package(s) Affected

python3-matplotlib-3.6.0_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Not a bug, upstream says:
```
For packagers, this release contains some changes to dependencies:

  * Python 3.8 is now required.
  * NumPy 1.19 is now required.
  * The ContourPy package is now required for contouring.
```
(https://discourse.matplotlib.org/t/matplotlib-announce-ann-matplotlib-3-6-0/23129)

So this should be fixed just by packaging `python3-contourpy`, presumably without the need to change matplotlib itself.

### Expected behaviour

A contour object is created and can be shown:
```
...
>>> ax.contourf(X, Y, Z, levels=levels)
<matplotlib.contour.QuadContourSet object at 0x7f8e831ebd60>
>>> 
>>> plt.show()
```

This actually works after downgrading to `python3-matplotlib-3.5.3_1`

### Actual behaviour

Example from https://matplotlib.org/stable/plot_types/arrays/contourf.html#sphx-glr-plot-types-arrays-contourf-py
```
$ python
Python 3.10.7 (main, Sep  7 2022, 15:23:13) [GCC 10.2.1 20201203] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
>>> import numpy as np
>>> 
>>> plt.style.use('_mpl-gallery-nogrid')
>>> 
>>> # make data
>>> X, Y = np.meshgrid(np.linspace(-3, 3, 256), np.linspace(-3, 3, 256))
>>> Z = (1 - X/2 + X**5 + Y**3) * np.exp(-X**2 - Y**2)
>>> levels = np.linspace(Z.min(), Z.max(), 7)
>>> 
>>> # plot
>>> fig, ax = plt.subplots()
>>> 
>>> ax.contourf(X, Y, Z, levels=levels)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/matplotlib/__init__.py", line 1423, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/usr/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 6382, in contourf
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/matplotlib/contour.py", line 794, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/matplotlib/contour.py", line 1419, in _process_args
    import contourpy
ModuleNotFoundError: No module named 'contourpy'
```

### Steps to reproduce

Try the example from https://matplotlib.org/stable/plot_types/arrays/contourf.html#sphx-glr-plot-types-arrays-contourf-py

**Comment by misuchiru03** [comment]
Building the template for contourpy.
Going to work through some testing in a bit.

**Comment by misuchiru03** [comment]
#39857

I tested it and it seemed to work for me. Give it a shot and let me know.

**Comment by classabbyamp** [comment]
69fbfa0b3ea2bd2b0159769d9be563151bbe42c1
