### ISSUE TITLE
gzdoom: fatal error: only SDL 2.0.6 or later is supported

### ISSUE THREAD

**Issue by Vulldozer** [void-linux/void-packages#39849]
### Is this a new report?

Yes

### System Info

Void 5.19.13_1 x86_64 AuthenticAMD notuptodate rDDFFFFFFF

### Package(s) Affected

gzdoom-4.7.1_1, SDL2-2.24.0_1, SDL2-devel-2.24.0_1

### Expected behaviour

gzdoom requires SDL2-2.0.6 or later to work, and it is packaged with a dependency for the latest SDL2 (2.24.0_1 at the time of writing this).
after installing gzdoom and making sure SDL2 is up to date, running the gzdoom command or launching it elsewhere should start the game.

### Actual behaviour

after running gzdoom and picking an any iwad file you get an error and it exits.
fatal error: only SDL 2.0.6 or later is supported.

gzdoom can't run the game with the latest version of SDL2, but after a downgrade to SDL2-2.0.22 using the xdowngrade tool the issue is fixed and the game works.

### Steps to reproduce

1. install gzdoom `xbps-install -Su gzdoom`
2. run `gzdoom`
3. pick any iwad file (if you don't have any, you can get the freedoom iwad a libre/free iwad).
4. see error.

**Comment by oreo639** [comment]
Here is why:
https://github.com/ZDoom/gzdoom/commit/2c69afa1187f55c2634c67c3ece47d89fd1b4f67

**Comment by sgn** [comment]
Seem to be fixed in gzdoom 4.8. You can help pkg it. Meanwhile, I'll backport the fix.
