### ISSUE TITLE
Conky not compiling

### ISSUE THREAD

**Issue by stroudmw** [void-linux/void-packages#39860]
### Is this a new report?

Yes

### System Info

Kernel: 5.19.13_1 arch: x86_64 bits: 64 Desktop: Xfce     v: 4.16.1 Distro: Void Linux 5.19.13_1 Glibc

### Package(s) Affected

conky 1.13.1

### Expected behaviour

I expected ./xbps-src pkg conky to compile

### Actual behaviour

I get the following error when running ./xbps-src pkg conky

=> cmake-3.24.1_1: installing target dependencies: expat-devel-2.4.8_1 libarchive-devel-3.6.1_1 libcurl-devel-7.84.0_2 libuv-devel-1.43.0_1 ncurses-devel-6.3_2 rhash-devel-1.4.3_2 jsoncpp-devel-1.9.4_2 ...
=> cmake-3.24.1_1: removing autodeps, please wait...
=> ERROR: cmake-3.24.1_1: failed to install target dependencies! (error 19)
ncurses-libs-6.3_2 in transaction breaks installed pkg `ncurses-6.3_3'
Transaction aborted due to unresolved dependencies.
=> ERROR: Please see above for the real error, exiting...

### Steps to reproduce

cd void-packages
./xbps-src pkg conky

**Comment by sgn** [comment]
Sync your `xbps-src` repository please. Maybe pkg `ncurses` after that. Anyway, why're you building conky

**Comment by stroudmw** [comment]
Thanks. I ended up removing void-packages and running git clone again. 
Conky compiles without issue. My apologies!

**Comment by paper42** [comment]
`git pull` would probably be enough to fix this
