### ISSUE TITLE
Package request: Litexl (lightweight text editor)

### ISSUE THREAD

**Issue by superiums** [void-linux/void-packages#39861]
### Package name

litexl

### Package homepage

https://github.com/lite-xl/lite-xl

### Description

Lite XL is  a lightweight text editor written mostly in Lua — it aims to provide something practical, pretty, small and fast easy to modify and extend, or to use without doing either.

The aim of Lite XL compared to lite is to be more user friendly, improve the quality of font rendering, and reduce CPU usage.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by onli** [comment]
Just as a note: The current master did indeed compile without issues for me, and the requirements all did exist in the void repo. 2.1 should be a good candidate for a package. Maybe the plugins could be added as well, as geany-plugins does for geany?

**Comment by superiums** [comment]
hi, 2.1 released yesterday.

**Comment by tranzystorek-io** [comment]
> Maybe the plugins could be added as well, as geany-plugins does for geany?

I'm afraid the plugins repo isn't versioned so we can't do it as cleanly as geany does, at least not until upstream decide to do sth about that.

**Comment by biopsin** [comment]
[Oftopic] heh, if only all other applications I rely on could be this sexy, thank you for the heads up!
