### ISSUE TITLE
Godot is missing pulseaudio support, cannot play audio smoothly on PipeWire

### ISSUE THREAD

**Issue by nyanpasu64** [void-linux/void-packages#39936]
### Is this a new report?

Yes

### System Info

Void 5.19.14_1 x86_64 GenuineIntel uptodate rFFFFFFFFF

### Package(s) Affected

godot-3.5_1 (technically outdated, 3.5.1 is out upstream but not in void-packages)

### Expected behaviour

Godot plays audio without stutters, mixed with audio from PipeWire apps. This is achieved by Flathub Godot on Void Linux.

### Actual behaviour

Godot is built with `pulseaudio=no` (https://github.com/void-linux/void-packages/blob/master/srcpkgs/godot/template), leaving it with only an ALSA backend.

- When it outputs to the system ALSA device, it prevents PipeWire apps from playing audio simultaneously.
- When it outputs to the alsa-pipewire package set as the default ALSA device, audio stutters continuously. (Is this a pipewire-alsa or a godot bug, and should it be reported there? PipeWire upstream discourages using ALSA's pipewire plugin, saying to prefer the PulseAudio API instead.)

Is there a technical packaging reason I'm unaware of, that `pulseaudio=no` is necessary?

### Steps to reproduce

1. Install and run PipeWire. Optionally install `alsa-pipewire` and run `sudo ln -s /usr/share/alsa/alsa.conf.d/50-pipewire.conf /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/`
2. Run Godot and start a game that plays audio.
3. Try to play audio from another PipeWire app while audio is playing.

**Comment by paper42** [comment]
> Is there a technical packaging reason I'm unaware of, that pulseaudio=no is necessary?

There probably isn't, feel free to submit a PR with a fix.

**Comment by nyanpasu64** [comment]
Should I submit the PulseAudio backend and update to 3.5.1 in a single PR?

**Comment by classabbyamp** [comment]
> Should I enable the PulseAudio backend and update to 3.5.1 in a single PR (from https://github.com/void-linux/void-packages/compare/master...nyanpasu64:void-packages:godot-update-pulse)?

sure! 

> Also is there any dependency to be added, beyond `makedepends="pulseaudio-devel"`? (I'm guessing Godot is smart enough to pick the ALSA backend if PulseAudio isn't running? IDK. And why does `xbps-query godot` print `run_depends` but the list is not in the template?)

it may. inspect the output of `xbps-src configure godot`, it will probably tell you if it's missing

> Also what does https://github.com/void-linux/void-packages/blob/master/srcpkgs/godot/update do?

it changes some of the default settings for the update checker, see [here](https://github.com/void-linux/void-packages/blob/master/Manual.md#updates)

**Comment by paper42** [comment]
> And why does xbps-query godot print run_depends but the list is not in the template?)

They are detected automatically: https://github.com/void-linux/void-packages/blob/master/Manual.md#runtime-dependencies
