### ISSUE TITLE
Package request: SRWare Iron

### ISSUE THREAD

**Issue by MechDR** [void-linux/void-packages#39931]
### Package name

iron

### Package homepage

https://www.srware.net/

### Description

An open source Chrome build with telemetries removed. Mainly, it's one of the few Chromium based browsers that's not Chrome and offers 32-bit builds of the browser. There's only Ubuntu packages available. I tried `ldd` on the binary, didn't report any missing binaries, it ran just fine extracted from the Debian package.

That being said, the browser did ran, but can't load a single page, it just reports that it "can't open this page" (Error 256)... don't know what the problem might be...

Download links:

https://www.srware.net/downloads/iron.deb
https://www.srware.net/downloads/iron64.deb

### Does the requested package meet the package requirements?

System, Required

### Is the requested package released?

Yes

**Comment by paper42** [comment]
We do not package any chromium or firefox forks, see the tens of package requests for ungoogled chromium, iridium browser, brave, waterfox, librewolf, etc.

**Comment by MechDR** [comment]
OK, no prob, cool, but why is that? Some legal stuff?

**Comment by classabbyamp** [comment]
additionally, iirc void's chromium has telemetry removed and supports i686

**Comment by MechDR** [comment]
@classabbyamp Hm, that's good to know, so it's basically Chrome minus telemetries, like Iron, mentioned above, correct?

**Comment by MechDR** [comment]
@classabbyamp Well, I tried it, it does install, but doesn't run...

`[1013/175205.778539:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[1013/175205.779052:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
fish: Job 1, 'chromium' terminated by signal SIGILL (Illegal instruction)
`
