### ISSUE TITLE
linux: tcp congestion and optimizations

### ISSUE THREAD

**Issue by tetsumaki** [void-linux/void-packages#39951]
Hello everyone,

I've been using Void Linux for a long time now, and I found that the kernel was not optimized in an optimal way.

Void Linux uses the following settings:

```ini
net.ipv4.tcp_available_congestion_control = reno
net.core.default_qdisc = pfifo_fast
net.ipv4.tcp_congestion_control = reno
```

Most distributions (Rocky/Arch) use the following settings:

```ini
net.ipv4.tcp_available_congestion_control = cubic bbr
net.core.default_qdisc = fq_codel
net.ipv4.tcp_congestion_control = cubic
```

Alpine use the following settings:

```ini
net.ipv4.tcp_available_congestion_control = reno cubic
net.core.default_qdisc = pfifo_fast
net.ipv4.tcp_congestion_control = cubic
```

I think the best setting though is this (Rocky/Arch):

```ini
net.ipv4.tcp_available_congestion_control = cubic bbr
net.core.default_qdisc = fq_codel
net.ipv4.tcp_congestion_control = cubic
```

BBR is very good, but still in alpha, you have to give the user the choice to apply it.

Whatever happens, the kernel should be optimized, and the user should be allowed to change via sysctl.

The discussion is open (fq/fq_codel/sch_fq/cak, reno/bbr and others optimizations).

My english is not perfect ;)

Some links :
- https://github.com/google/bbr/blob/master/README
- https://wiki.archlinux.org/title/sysctl#Enable_BBR
- https://www.cyberciti.biz/cloud-computing/increase-your-linux-server-internet-speed-with-tcp-bbr-congestion-control/
- https://github.com/systemd/systemd/issues/9725
- https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/linux/trunk/config
- https://raw.githubusercontent.com/void-linux/void-packages/master/srcpkgs/linux5.19/files/x86_64-dotconfig

**Comment by sgn** [comment]
> BBR is very good, but still in alpha, you have to give the user the choice to apply it.
> 
> Whatever happens, the kernel should be optimized,
> and the user should be allowed to change via sysctl,
> which is not the case now.

What is your problem when you're changing?
```
# modprobe tcp_bbr
# sysctl -w net.ipv4.tcp_congestion_control=bbr
```

works for me

**Comment by sgn** [comment]
If you want to do it automatically at boot:

```sh
# cat /etc/modules-load.d/tcp-congestion.conf
tcp_bbr
# cat /etc/sysctl.d/tcp-congestion.conf
net.ipv4.tcp_available_congestion_control=bbr
```



> Hi, I think the default configuration should be changed to use cubic and not reno.

That's subjective. You have the option to change to anything you want.

**Comment by tetsumaki** [comment]
Yes, i already use fq_codel / bbr.
I'm talking about the default configuration.

**Comment by sgn** [comment]
> Yes, i already use fq_codel / bbr. I'm talking about the default configuration.

I don't understand, your first message is "Whatever happens, the kernel should be optimized, and the user should be allowed to change via sysctl."?

**Comment by tetsumaki** [comment]
> > Yes, i already use fq_codel / bbr. I'm talking about the default configuration.
> 
> I don't understand, your first message is "Whatever happens, the kernel should be optimized, and the user should be allowed to change via sysctl."?

This is a bad translation, my bad.
And the module was not loaded, so it was not visible. on my paste.

**Comment by sgn** [comment]
I changed congestion control to cubic, it will available through new linux5.19 and linux6.0
Other kernels will follow suites.

**Comment by dtaht** [comment]
did you change the qdisc to fq_codel?

If boxes like this have sufficient horsepower, cake is actually the best thing going (IMHO, being one of the authors of both)
