### ISSUE TITLE
obs: segfault (wayland)

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#39987]
### Is this a new report?

Yes

### System Info

`Void 6.0.1_1 x86_64 AuthenticAMD uptodate FFFFFFF`

### Package(s) Affected

`obs-28.0.3_1`

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

-

### Expected behaviour

runs normally before plasma 5.26. after system upgrade obs can't run on wayland. but on x11 it works fine.
I think it needs to be rebuilt.

### Actual behaviour

```
➜  ~ obs
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb.

fish: Job 1, 'obs' terminated by signal SIGABRT (Abort)
```

### Steps to reproduce

- `doas xbps-install -S obs`
- open `obs`

**Comment by paper42** [comment]
install qt6-wayland

**Comment by hervyqa** [comment]
> install qt6-wayland

thanks. it works. 👍🏻

![Screenshot_20221016_185528](https://user-images.githubusercontent.com/45872139/196034128-cf6bc0d5-e777-4741-816c-b6ced6c61c21.png)

**Comment by paper42** [comment]
Still I think it shouldn't segfault, but that might be an upstream issue.
