### ISSUE TITLE
Waiting to connect to bluetoothd...dbus

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#40011]
### Is this a new report?

Yes

### System Info

Void 5.19.16_1 x86_64 GenuineIntel notuptodate hold rFF

### Package(s) Affected

bluez, dbus

### Expected behaviour

`bluetoothctl` should work properly.

### Actual behaviour

Whenever i wanted to run `bluetoothctl`, it throws this error:
```
↳ bluetoothctl
Waiting to connect to bluetoothd...dbus[18807]: arguments to dbus_connection_get_object_path_data() were incorrect, assertion "connection != NULL" failed in file dbus-connection.c line 5921.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted
```

### Steps to reproduce

I wanted to enable Bluetooth on my void Linux, there are the steps that I followed:
https://docs.voidlinux.org/config/bluetooth.html

**Comment by sgn** [comment]
Just want to check, are both bluetoothd and dbus service up?
```
sv status dbus bluetoothd
```
Is there any errors in dmesg?

**Comment by LinArcX** [comment]
Oh, I don't know why this happened. Just reinstalled dbus and bluez, and everything now works.
