### ISSUE TITLE
Azote Self-Terminating With A ModuleNotFoundError

### ISSUE THREAD

**Issue by TeusLollo** [void-linux/void-packages#40029]
### Is this a new report?

Yes

### System Info

Void 5.15.74_1 x86_64 GenuineIntel uptodate rFFFF

### Package(s) Affected

azote-1.9.5_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

None known.

### Expected behaviour

Azote is a "_Wallpaper & color manager for Sway, i3 and other WMs_".

It operates as a GTK3 application handling wallpapers and backgrounds for compatible window managers, by operating as a front-end for various WM-compatible tools. It also features a built-in previewing tool and photo gallery, and a built-in color manager

### Actual behaviour

I didn't notice Azote was not executing at first (Latest package update https://github.com/void-linux/void-packages/pull/39033#issue-1359088098), since I have scripts handling wallpapers through the _swaybg_  tool (Hence, I mostly keep Azote for kicks). 

Some days ago, however, I tried running Azote through its .desktop file, and nothing happened. 

I subsequently resorted to the terminal, and I got the following as output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/azote/main.py", line 20, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```
Since I don't recall experiencing any byte-compiling errors upon python3.10 updates (Or any other python3.10 error, for that matter), I can't tell if this should be considered a missing dependency, or a packaging error, or even a coding error in _main.py_ (I doubt the latter, unless latest python3.10 dropped some components)

Either way, Azote was working some months ago, yet, as the latest update, it ends with the output above. 

Cache was cleaned, thus I can't revert to the older version.

### Steps to reproduce

1. Install Azote through xbps-install from official repos
2. Type Azote in a terminal emulator, preferably having a supported WM on the back-end
3. Experience the ModuleNotFoundError for yourself.

**Comment by classabbyamp** [comment]
does it still happen if you install `python3-setuptools`?

**Comment by hochata** [comment]
Hi, this issue came back at some point and it is present on master.
