### ISSUE TITLE
PolyMC package removal

### ISSUE THREAD

**Issue by kotajacob** [void-linux/void-packages#40028]
There's been a [recent storm in the minecraft launcher](https://www.pcgamer.com/minecraft-launcher-project-spins-out-of-control-after-dev-hijacks-it-to-fight-leftist-queer-ideology/) world. PolyMC, a very popular launcher which we package, has been hijacked by a (previously mostly inactive) maintainer who has banned all other maintainers in a supposed act of "purging leftist queer ideology".

The other maintainers, and [many others in the community](https://twitter.com/modrinth/status/1582093129641234432?cxt=HHwWgMDQnbbU3PQrAAAA)  are urging everyone whom had PolyMC installed to remove it immediately as it may be used to spread malware in the very near future.

The maintainers who were banned have forked the project and it now exists as PrismLauncher here: https://github.com/PrismLauncher/PrismLauncher

The code is basically the same as PolyMC, but with a few additional fixes already merged and of course the name change and original maintainers being restored. I'm perfectly happy to submit any package updates, but I wasn't sure if we should put in a package removal PR for polymc followed by a package creation for prism? Or if we should simply update the download URLs in polymc to point towards prism?

**Comment by classabbyamp** [comment]
we are already tracking this. in #40014 the bad (old) upstream meta server was replaced by one run by prism.

the package itself will probably be renamed/updated when prism creates their first release

**Comment by kotajacob** [comment]
Woops! Didn't see that PR. Great to hear, thanks!
