### ISSUE TITLE
Regression: pdf.js-2.16.105_1 broken with qutebrowser-2.5.2_1

### ISSUE THREAD

**Issue by ahesford** [void-linux/void-packages#40061]
### Is this a new report?

Yes

### System Info

Void 5.15.63_1 x86_64 GenuineIntel notuptodate rFFFFFFFFFFFFFFFFFFF

### Package(s) Affected

pdf.js-2.16.105_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

None noted

### Expected behaviour

Visiting [a sample PDF](https://raw.githubusercontent.com/mozilla/pdf.js/master/examples/learning/helloworld.pdf) in qutebrowser should show an action dialog that presents `Ctrl+p` as an option to view the PDF with `pdf.js`. Choosing this option should open a new window with the `pdf.js` UI and a "Hello World" document displayed.

cc: @heittpr 

### Actual behaviour

Although the `pdf.js` UI is displayed, the content array is completely empty. Only the dark gray background is visible. Opening the qutebrowser web console with key combination `wIh` shows the following stack trace:

```
pdf.js:4213
Uncaught TypeError: key.split(...).at is not a function
    at new KeyboardManager (pdf.js:4213)
    at Function.<static_fields_initializer> (pdf.js:4369)
    at Array.Object.defineProperty.value (pdf.js:4342)
    at __w_pdfjs_require__ (pdf.js:19477)
    at Array.Object.defineProperty.value (pdf.js:3737)
    at __w_pdfjs_require__ (pdf.js:19477)
    at Array.Object.defineProperty.value (pdf.js:3562)
    at __w_pdfjs_require__ (pdf.js:19477)
    at Array.Object.defineProperty.value (pdf.js:1119)
    at __w_pdfjs_require__ (pdf.js:19477)
    
viewer.js:4333
Uncaught ReferenceError: require is not defined
    at Array.Object.defineProperty.value (viewer.js:4333)
    at __webpack_require__ (viewer.js:16331)
    at Array.pdfjsLib (viewer.js:1499)
    at __webpack_require__ (viewer.js:16331)
    at viewer.js:16367
    at viewer.js:16546
    at viewer.js:16548
    
viewer.html?filename=tmptkbvwf5m_helloworld.pdf&file=&source=https://raw.githubusercontent.com/mozilla/pdf.js/master/examples/learning/helloworld.pdf:466
Uncaught TypeError: Cannot read property 'set' of undefined
    at HTMLDocument.<anonymous> (viewer.html?filename=tmptkbvwf5m_helloworld.pdf&file=&source=https://raw.githubusercontent.com/mozilla/pdf.js/master/examples/learning/helloworld.pdf:466)
```

Downgrading to `pdf.js-2.14.305_1` fixes the problem.

### Steps to reproduce

1. `xbps-install qutebrowser pdf.js`
2. `qutebrowser "https://raw.githubusercontent.com/mozilla/pdf.js/master/examples/learning/helloworld.pdf"`
3. Press `Ctrl+p` to show broken PDF viewer
4. Press `wIh` to open the browser debug view, then choose the `Console` from the tabs to see the stack trace.

**Comment by heittpr** [comment]
Relevant issue: https://github.com/qutebrowser/qutebrowser/issues/7335. There's a [workaround](https://github.com/qutebrowser/qutebrowser/issues/7335#issuecomment-1213153686) using a greasemonkey userscript .

pdf.js offers a [legacy build](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#legacy-build) to support older browsers. We could package it separately ([like arch](https://archlinux.org/packages/community/any/pdfjs-legacy/)) or add it as a build option to the current package.

**Comment by heittpr** [comment]
We could also add it as a subpackage, not sure what the best approach would be here.

**Comment by ahesford** [comment]
Is there significant value in the new version? What does it offer beyond 2.14.305?

**Comment by ahesford** [comment]
After reading more about this, I suppose the more appropriate question is what value the non-legacy build offers over the legacy one. If there is a reason for the non-legacy build, two packages might be appropriate.

**Comment by heittpr** [comment]
`2.16.105` has quite a lot of bugfixes ([changelog](https://github.com/mozilla/pdf.js/releases)) since we skipped `2.15.349`. According to https://github.com/mozilla/pdf.js/issues/15457#issuecomment-1250369604 `2.14.305` is no longer supported.

**Comment by ahesford** [comment]
Let's move discussion about a resolution to #40078.
