### ISSUE TITLE
Package request: Iosevka Comfy

### ISSUE THREAD

**Issue by Haagen-Dazs** [void-linux/void-packages#40081]
### Package name

iosevka-comfy

### Package homepage

https://git.sr.ht/~protesilaos/iosevka-comfy

### Description

Custom build of Iosevka with different style and metrics than the default.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by paper42** [comment]
> New fonts may be accepted if they provide value beyond aesthetics (e.g. they contain glyphs for a script missing in already packaged fonts).

That's not this case.
