### ISSUE TITLE
Additional Build Option Request: base-system, doas instead of sudo

### ISSUE THREAD

**Issue by carbongreat13** [void-linux/void-packages#40087]
I prefer to use doas. Therefore, I would like to remove sudo from my system.
Could you please add a build option to base-system to provide an option to rely on doas instead of sudo?

**Comment by classabbyamp** [comment]
you can already do this with, e.g., `echo ignorepkg=sudo > /etc/xbps.d/no-sudo.conf`

this can work better than a build option because you'll still get updates for `base-system` normally

**Comment by paper42** [comment]
We could also add an option to use iwd instead of wpa_supplicant, linux-lts/mainline instead of linux, etc. ignorepkg is the proper solution here
