### ISSUE TITLE
VeraCrypt is not free.

### ISSUE THREAD

**Issue by carbongreat13** [void-linux/void-packages#40093]
VeraCrypt is a mixture of code licensed under Apache-2.0 and code licensed under TrueCrypt-3.0.
Users of VeraCrypt are not free to choose between the two licenses; it is not a multi-license, like Firefox.

TrueCrypt-3.0 is a nonfree license. Therefore, you must mark VeraCrypt as nonfree.

**Comment by classabbyamp** [comment]
can you be more specific as to how TrueCrypt-3.0 is a nonfree licence?

**Comment by carbongreat13** [comment]
> can you be more specific as to how TrueCrypt-3.0 is a nonfree licence?


>This license is nonfree for several reasons. It says that if you don't understand the license you may not use the program. It puts conditions on allowing others to run your copy. It puts conditions on separate programs that “depend on” Truecrypt. The trademark condition applies to “associated materials”. 
https://www.gnu.org/licenses/license-list.html.en

**Comment by carbongreat13** [comment]
https://web.archive.org/web/20131029185711/http://projects.opensource.org/pipermail/license-discuss/2013-October/001313.html

**Comment by sgn** [comment]
Yes, VeraCrypt is nonfree.
