### ISSUE TITLE
Add Build Option: cinnamon, Disable NetworkManager

### ISSUE THREAD

**Issue by carbongreat13** [void-linux/void-packages#40092]
Cinnamon can be built without NetworkManager by adding the build option `-Ddisable_networkmanager=true`.
This is useful for those who do not use NetworkManager.

**Comment by paper42** [comment]
What does disabling networkmanager mean? Is that the same as not installing NetworkManager?

**Comment by carbongreat13** [comment]
https://github.com/void-linux/void-packages/blob/e3ed78427e0539c2ce0608cc82a7d9be8e3faf40/srcpkgs/cinnamon/template#L19

Cinnamon depends includes network-manager-applet.
You can remove network-manager-applet from depends by adding -Ddisable_networkmanager=true.
See also [Gentoo's USE flag](https://gitweb.gentoo.org/repo/gentoo.git/tree/gnome-extra/cinnamon/cinnamon-5.2.7-r4.ebuild).

**Comment by paper42** [comment]
So this is equivalent to ignorepkg.

**Comment by sgn** [comment]
```meson
has_nm = not get_option('disable_networkmanager')
if has_nm
    # only ever used in *.js via gi import
    dependency('libnm')
endif
```

Just `ignorepkg`. There's no good in a build options.
