### ISSUE TITLE
libpwquality no working on musl

### ISSUE THREAD

**Issue by szorfein** [void-linux/void-packages#40104]
### Is this a new report?

Yes

### System Info

Void 5.19.13_1 x86_64-musl GenuineIntel/KVM notuptodate rFF

### Package(s) Affected

libpwquality-1.4.4_1

### Expected behaviour

    passwd username
    New password:
    BAD password: the password fails the dictionary check
    Retype new password:

### Actual behaviour
    
    passwd user
    passwd: Module is unknown
    passwd: password unchanged

The lib exist:

    ls /usr/lib/security | grep pwquality
    pam_pwquality.so

### Steps to reproduce

1. xbps-install -S libpwquality
2. vim /etc/pam.d/passwd
```txt
password required pam_pwquality.so retry=2 
password required pam_unix.so sha512 shadow nullok rounds=20000
```
3. passwd user

**Comment by sgn** [comment]
Confirmed:
```cpp
#include <dlfcn.h>
#include <stddef.h>
#include <stdio.h>

int main(int argc, char **argv) {
        if (argc != 2) return 255;
        void *h = dlopen(argv[1], RTLD_NOW);
        if (h == NULL) {
                printf("dlopen: %s\n", dlerror());
                return 1;
        }
        return 0;
}
```
```
$ ./a.out /usr/lib/security/pam_pwquality.so
dlopen: Error relocating /usr/lib/security/pam_pwquality.so: fgetpwent_r: symbol not found
```
