### ISSUE TITLE
Package request: pdfarranger

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#40138]
### Package name

pdfarranger

### Package homepage

https://github.com/pdfarranger/pdfarranger

### Description

Helps merge or split PDF documents and rotate, crop and rearrange pages

https://github.com/void-linux/void-packages/pull/34216

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by tranzystorek-io** [comment]
https://github.com/tranzystorek-io/void-packages/blob/pdfarranger/srcpkgs/pdfarranger/template up for grabs

**Comment by Eloitor** [comment]
Thank you
