### ISSUE TITLE
linux 6.0.3_1 : no sound card (hda intel)

### ISSUE THREAD

**Issue by rapha8l** [void-linux/void-packages#40150]
### Is this a new report?

Yes

### System Info

Void 6.0.3_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFFFFF

### Package(s) Affected

linux6.0-6.0.3_1 

### Expected behaviour

sound card should be detected (it does with 6.0.2_1)

### Actual behaviour

no sound card detected 

lspci -v | grep -A7 -i "audio" 
00:1f.3 Multimedia audio controller: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller (rev 20)
	Subsystem: Lenovo Device 3834
	Flags: bus master, fast devsel, latency 32, IRQ 168, IOMMU group 15
	Memory at 603d1c8000 (64-bit, non-prefetchable) [size=16K]
	Memory at 603d000000 (64-bit, non-prefetchable) [size=1M]
	Capabilities: [50] Power Management version 3
	Capabilities: [80] Vendor Specific Information: Len=14 <?>
	Capabilities: [60] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Kernel driver in use: sof-audio-pci-intel-tgl

### Steps to reproduce

reboot in 6.0.3_1, no soundcard

**Comment by zarMarco** [comment]
same problem with same audio card

**Comment by paper42** [comment]
According to @dataCobra this should be fixed after 6.0.4.

**Comment by sgn** [comment]
Can you test 6.0.5?

**Comment by zarMarco** [comment]
I can test if you want
