### ISSUE TITLE
python3-bluez still at Python 3.9, python interpreter can't find bluetooth module

### ISSUE THREAD

**Issue by rubin55** [void-linux/void-packages#40238]
### Is this a new report?

Yes

### System Info

Void 5.19.16_1 x86_64 AuthenticAMD uptodate rrmFFFF

### Package(s) Affected

python3-bluez-0.23_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No.

### Expected behaviour

```
Python 3.10.8 (main, Oct 12 2022, 01:35:49) [GCC 10.2.1 20201203] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bluetooth
>>>
```

### Actual behaviour

```
Python 3.10.8 (main, Oct 12 2022, 01:35:49) [GCC 10.2.1 20201203] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bluetooth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bluetooth'
```

### Steps to reproduce

1. install python3, observe you obtain python 3.10.x
2. install python3-bluez
3. ls /usr/lib/python3.9/site-packages, observe this is the only module there
4. ls /usr/lib/python3.10/site-packages, observe it contains lots of packages
5. try to import bluetooth with python 3.10, observe it not finding the module

**Comment by sgn** [comment]
5957216b89

Anyway, bluetooth has been supported natively in CPython from Python 3.10, but we didn't enable it.
It'll be available from our build of Python 3.11 which should be available next Monday.
