### ISSUE TITLE
check-file-conflicts in CI: `column: command not found`

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#40287]
Since https://github.com/leahneukirchen/xtools/commit/5c5aa1daa36a022a404ef9fede2ca21c628e7694 xlocate uses column which doesn't seem to be available in the container which results in this error message:
```
Cloning into bare repository '/github/home/.cache/xlocate.git'...
warning: templates not found in /usr/share/git-core/templates
/tmp/bin/xlocate: line 91: column: command not found
No conflicts found in /github/home/hostdir/binpkgs /github/home/hostdir/binpkgs/nonfree
```

**Comment by classabbyamp** [comment]
i think this should be solved in xlocate with a `command -v column` test

**Comment by classabbyamp** [comment]
https://github.com/leahneukirchen/xtools/pull/270
