### ISSUE TITLE
Package request: nvidia-settings

### ISSUE THREAD

**Issue by retq1** [void-linux/void-packages#40294]
### Package name

nvidia-settings

### Package homepage

https://github.com/NVIDIA/nvidia-settings

### Description

A tool for configuring the Nvidia graphics driver. Allows you to set the necessary parameters for the driver.

A vital package, why didn't you add it earlier? As an Nvidia graphics card owner, I can't use the distribution without this package.

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

Yes

**Comment by dataCobra** [comment]
> A vital package, why didn't you add it earlier? As an Nvidia graphics card owner, I can't use the distribution without this package.

This is a great tool and it would be nice to have it. But that you can't use the distribution without it, is not true. You just need to setup X11 properly.

I'll try to create a pkg. :+1:

**Comment by retq1** [comment]
Thank you so much!
I'm relatively newbie to Linux, and I'm attracted to Void. So far I have little experience with X11

**Comment by retq1** [comment]
> > A vital package, why didn't you add it earlier? As an Nvidia graphics card owner, I can't use the distribution without this package.
> 
> This is a great tool and it would be nice to have it. But that you can't use the distribution without it, is not true. You just need to setup X11 properly.
> 
> I'll try to create a pkg. 👍

Thank you so much!
I'm relatively newbie to Linux, and I'm attracted to Void. So far I have little experience with X11

**Comment by furryfixer** [comment]
Please close this issue.  nvidia-settings is not a separate "package".  It is included with the nvidia driver.  It is functional only for X11, not Wayland.  If typing the command from a terminal command line gives a "command not found" error, please reinstall your nvidia driver package.
