### ISSUE TITLE
the right way to start a WM session of wayland

### ISSUE THREAD

**Issue by superiums** [void-linux/void-packages#40313]
there'are 2 ways to start a WM session for sway/wayfire/...
no matter start the WM from tty manually, or let DM load the session for WM, or start a command by DM.
1. run sway/wayfire directly.
2. run sway/wayfire by dbus: `dbus-launch wayfire`

i am using greetd and tui-greeter.
## Way 1, launch WM directly
all things works but except gvfs. 
- gvfs fails
thunar report the gvfs was not work currectly, and there's no vols appear in left panel of thunar.
for tracering the issue, all of them report an GLIB error.
for example , this is the report of gvfs debug , using comomand GVFS_DEBUG=1 $(find /usr/lib* -name gvfsd 2>/dev/null) --replace 2>&1 | tee gvfsd.log :

```
(process:14320): GLib-GObject-CRITICAL **: 11:21:21.921: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(process:14320): GLib-GIO-CRITICAL **: 11:21:21.924: g_volume_monitor_get_mounts: assertion 'G_IS_VOLUME_MONITOR (volume_monitor)' failed

(process:14320): GLib-GObject-WARNING **: 11:21:21.924: invalid (NULL) pointer instance

(process:14320): GLib-GObject-CRITICAL **: 11:21:21.924: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:14320): GLib-GObject-WARNING **: 11:21:21.924: invalid (NULL) pointer instance

(process:14320): GLib-GObject-CRITICAL **: 11:21:21.924: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```
- obs-studio works in this way.

## Way 2, lauch WM by dbus

if i use this command to let the DM start the WM
```
cmd='tuigreet -cmd dbus-launch wayfire'
```
or type ` dbus-launch wayfire` in tty

- gvfs  works.

- but obs-studio can't take screen record (no `capture screen source (pipewire)` appears), cant' start virtual camera.

```
error: Failed to inhibit: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: on path org.freedesktop.portal.Inhibit object not found“/org/freedesktop/portal/desktop”interface
```
- some program fails, like celluloid
can't be started by GUI, both in thunar or wofi.
but can be started by terminal,  with the same error reported above.
all packages like xdg-desktop-portal ,  xdg-desktop-portal-wlr already installed.

**Comment by superiums** [comment]
> does it work with dbus-run-session instead of dbus-launch?

it acts like dbus-launch.

**Comment by superiums** [comment]
and I found another thing, 
- if start WM directly, fcitx5-rime **NOT work** in chromium.
- if start WM with dbus-launch , fcitx5-rime **works** in chromium.

**Comment by classabbyamp** [comment]
you have the dbus system service enabled too?

these softwares may require XDG_RUNTIME_DIR, do you use elogind/dumb_runtime_dir/pam_rundir?

**Comment by superiums** [comment]
yes, i have the dbus service enabled.
XDG_RUNTIME_DIR is run/user/1000

i have dbus-daemon and elogind-daemon runing in ps.

every service keep default after install, except elogind. i removed this from /var/service because i use greetd, greetd will report "elogind service is already launched" error if not remove it. seems elogind was started by greetd. also, i have seen this ps runing after remove.

i don't use dumb_runtime_dir/pam_rundir.

**Comment by fspkwon** [comment]
yeah this is pretty much the same exact situation im in, im trying to use weston compositor to check issues
with labwc/wlroots on gentoo .... im having dbus issues using tuigreet/greetd... which it says is for WAYLAND
SPECIFIC DESKTOPS.... but its fundamentally an oxymoron.. XDG specifically says its X, just like XCB is X
so running vkcube.. see it says xcb in there? like the?
