### ISSUE TITLE
Cannot mix incompatible Qt library (5.15.2) with this version (5.15.5)

### ISSUE THREAD

**Issue by relativelySunnySun5** [void-linux/void-packages#40341]
### Is this a new report?

Yes

### System Info

Void 5.19.17_1 x86_64 GenuineIntel uptodate FFFFF

### Package(s) Affected

lxqt-config-1.1.0_1

### Expected behaviour
It launches and works properly

### Actual behaviour

From terminal:
[####@####]: lxqt-config-file-associations 
Cannot mix incompatible Qt library (5.15.2) with this library (5.15.5)
zsh: IOT instruction  lxqt-config-file-associations

From _lxqt-config_:
Nothing launched, but rest of _lxqt-config_ works fine

### Steps to reproduce

1. Launch _lxqt-config_
2. Launch _lxqt-config-file-associations_ via clicking on "File Associations"

**Comment by sgn** [comment]
Rebuild `libqtxdg` fixes the problem. Please wait until python3 rebuild has been done.

**Comment by sgn** [comment]
In the meantime, you can pull #40362 and rebuild locally.
