### ISSUE TITLE
Package request: jd

### ISSUE THREAD

**Issue by paoloschi** [void-linux/void-packages#40356]
### Package name

jd

### Package homepage

https://github.com/josephburnett/jd

### Description

jd is a commandline utility and Go library for diffing and patching JSON and YAML values.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by tranzystorek-io** [comment]
https://github.com/tranzystorek-io/void-packages/blob/jd/srcpkgs/jd/template up for grabs

**Comment by TeddyDD** [comment]
Adopted
