### ISSUE TITLE
How to build rust / cargo for i686-musl

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#4042]
With more and more packages requiring rust and/or cargo to be built, we are (I am) facing the problem that the official repository does not provide a rust and cargo binary for i686-musl.

AFAIK there is no description telling how the x86_64-musl package(s) were built and I don't know how I could possibly provide i686-musl binaries myself.

Could someone who knows the details describe the steps required to *bootstrap* rust for i686-musl?

**Comment by chneukirchen** [comment]
The easiest way is to get a rust glibc binary and fiddle enough glibc into your musl root, I guess.

**Comment by pullmoll** [comment]
Uh, ok, I somehow had expected there was a way to start with an ancient rust built from C/C++ and continue until current.

**Comment by jnbr** [comment]
> Uh, ok, I somehow had expected there was a way to start with an ancient rust built from C/C++ and continue until current.

I haven't tried it but this should be possible with [mrustc](https://github.com/thepowersgang/mrustc).

**Comment by Cogitri** [comment]
Uhh...cross building doesn't work? Because if it did you could generate an initial tarball that way. Or I can do that and upload the dist tarball of that somewhere

**Comment by pullmoll** [comment]
@Cogitri how would I cross build across libc borders? I didn't follow the recent rust / cargo updates close enough so I may haved missed if and how that is possible now.

**Comment by Cogitri** [comment]
Cross building rust should just work, even across different libcs, at least I remember accidentally compiling from x86_64->x86_64-musl.

**Comment by pullmoll** [comment]
A cross built `rust` for `i686-musl` doesn't work for me. I used `x86_64-musl` environment to cross compile for `i686-musl` and I simply added a `i686-musl` case to the `rust' and `cargo` templates to set the `_host_triplet=i686-unknkown-linux-musl`.

This is the error output when trying to build librsvg:
```
error: process didn't exit successfully: `rustc -vV` (exit code: 1)
--- stdout
rustc 1.29.2
binary: rustc
commit-hash: unknown
commit-date: unknown
host: i686-unknown-linux-musl
release: 1.29.2

--- stderr
error: couldn't load codegen backend "/usr/lib/rustlib/i686-unknown-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so": "Error relocating /usr/lib/rustlib/i686-unknown-linux-musl/codegen-backends/librustc_codegen_llvm-llvm.so: crc32: symbol not found"

```

**Comment by Cogitri** [comment]
> @jnbr Perhaps we can (should try to) create rust-bootstrap and / or cargo-bootstrap packages using mrustc to become independent of 3rd party binaries and the whacky circular updating of x86_64-musl rust/cargo.

To be honest, it's not "whacky". Personally, I'd prefer to not deviate from (rust) upstream here and just follow their bootstrapping procedure instead of adding yet another factor where stuff can go wrong.

Also, the runtime error you experience on i686-musl seems unrelated to that. Does libz not provide crc32 on i686-musl, or does rust simply not link against it?

**Comment by jnbr** [comment]
I like the idea of being able to bootstrap rust. A problem of `mrustc` is, that it builds a `rustc-1.19` and building a new version of rust requires at least the previous version of `rustc` and `cargo`. So bootstrapping the current version 1.30 from `mrustc` would require 10 intermediate versions.

**Comment by Cogitri** [comment]
Yeah, right now it just doesn't seem worth the effort to use mrustc when the current rust building process is OK.

**Comment by pullmoll** [comment]
I think I misread mrustc's supported rust version as 1.29 .. building more than 10 intermediate versions is definitely not an option.
