### ISSUE TITLE
marvin: login required for download

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-packages#40452]
it's already restricted, should it be removed or kept?

https://chemaxon.com/marvin

https://download.chemaxon.com/marvin

**Comment by classabbyamp** [comment]
cc: maintainer @fusion809

**Comment by fusion809** [comment]
It is possible to use a URL that doesn't require login to download the files. Check out my AUR package for instance https://aur.archlinux.org/packages/marvin. I don't use Void anymore, so I can't really maintain this package anymore, so if you want to delete feel free.
