### ISSUE TITLE
Package request: gtkgreet

### ISSUE THREAD

**Issue by BlindRepublic** [void-linux/void-packages#40458]
### Package name

gtkgreet

### Package homepage

https://git.sr.ht/~kennylevinsen/gtkgreet

### Description

Gtk Greeter for greetd

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by JamiKettunen** [comment]
Seems there hasn't been a new release since 0.7, so the template in #20873 would still be relevant whoever wants to pick this up. [`greetd` is also in repos now](https://github.com/void-linux/void-packages/tree/master/srcpkgs/greetd) :)

**Comment by otommod** [comment]
Looks like it was added last week (https://github.com/void-linux/void-packages/commit/1a60d25261c78c1adfdaf689dfb4046e151a7538).
