### ISSUE TITLE
Smplayer Does Not Depend on MPV

### ISSUE THREAD

**Issue by TrueTechie** [void-linux/void-packages#40456]
### Is this a new report?

Yes

### System Info

Void 5.19.17_1 x86_64 GenuineIntel uptodate FFFFFF

### Package(s) Affected

smplayer-22.7.0_1, mpv-0.34.1_2

### Expected behaviour

The package installs `mpv`, a runtime dependency in order to actually play videos with the application.

### Actual behaviour

`mpv` is not installed and attempting to play a video results in an error.

### Steps to reproduce

1. Install `smplayer`
2. Launch `smplayer`
3. Open a video file with the application

**Comment by ahesford** [comment]
Closing for the same reason as #40457: we don't have a good mechanism to support optional dependencies, and neither `mplayer` and `mpv` is really a hard dependency on its own.
