### ISSUE TITLE
plex-media-server: remove?

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-packages#40462]
- added in 2019, never updated since (latest version is 1.29.x, package is on 1.15.x)
- python 2
- no usage reports on popcorn

cc: maintainer @Anachron

**Comment by Anachron** [comment]
Thanks for the ping, I don't use this package anymore. 

I am fine with removing it, not even sure it works anymore.

**Comment by abenson** [comment]
`plex-media-player` could be removed, too.  It's no longer supported and apparently no longer works, either.
