### ISSUE TITLE
Package request: linux-lts

### ISSUE THREAD

**Issue by retq1** [void-linux/void-packages#40474]
### Package name

Linux LTS 5.15.78

### Package homepage

https://kernel.org/

### Description

Kernel with long-term support.

Hi guys. The Void repository already has a linux-lts package, but an old version 5.10. I would like volunteers to update it to the latest version 5.15.78.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
5.10 is not unsupported, see https://kernel.org

**Comment by retq1** [comment]
> 5.10 is not unsupported, see https://kernel.org
> 
> ![image](https://user-images.githubusercontent.com/5366828/201438649-c4d66567-8d56-4017-8624-03e95417aecd.png)

Why not update it?

**Comment by retq1** [comment]
up

**Comment by retq1** [comment]
There is version 5.15 in the repository, but not as part of the Linux lts package

**Comment by retq1** [comment]
I think you could fix it, but for now I think you should close this issue
