### ISSUE TITLE
OBS28 (QT6) crashing Mutter/Gnome shell 42.4 in Wayland

### ISSUE THREAD

**Issue by yurifuko** [void-linux/void-packages#40481]
### Is this a new report?

Yes

### System Info

Void 6.0.8_1 x86_64 GenuineIntel uptodate FF

### Package(s) Affected

mutter-42.4_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

**issue:**
https://gitlab.gnome.org/GNOME/mutter/-/issues/2390
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5919

**the MRs:**
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2636
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2592

### Expected behaviour

no crash

### Actual behaviour

clicking outside of QT6 dropdown combo box crashes gnome, this is apparently patched upstream in gnome (latest 42 & 43)
this happens only in wayland

I can still reproduce this even on new installs with all packages updated to latest

### Steps to reproduce

1. login to gnome (42.4) wayland session
2. launch OBS28
3. open any dropdown combo list box
4. click outside the dropdown
5. crashes mutter/shell, throwback to gdm

**Comment by classabbyamp** [comment]
do you have qt6-wayland installed?

**Comment by yurifuko** [comment]
> do you have qt6-wayland installed?

hi,
of course, since this is needed to get obs n' such to even launch when installed native 
(honestly `qt6-wayland` should be a dependency of `obs`)

the issue occurs for both native install and flatpak of obs (qt6 packages)
and seems to be a thing only for gnome/mutter

upstream gnome apparently has this fixed (linked issues and MRs above)
not sure how I should've reported this so I just made an issue here, sorry if that was the wrong way

**Comment by sgn** [comment]
> (honestly `qt6-wayland` should be a dependency of `obs`)

I don't have `qt6-wayland`, but `obs` still can start for me (xfce anyway).

**Comment by yurifuko** [comment]
> > (honestly `qt6-wayland` should be a dependency of `obs`)
> 
> I don't have `qt6-wayland`, but `obs` still can start for me (xfce anyway).

it's only needed when running in wayland session (obs is wayland native too)

**Comment by paper42** [comment]
Feel free to submit a PR with the patch to 42, I can not reproduce this and updating GNOME to 43 will take a while.

**Comment by paper42** [comment]
> it's only needed when running in wayland session (obs is wayland native too) otherwise it won't start unless ran with xwayland

This is one of the dependencies you have to install on your own because they are only useful under some conditions. The handbook covers this in the Wayland section. The only catch here is that you might have had obs and qt5-wayland when obs used qt5 and now with an update, qt6-wayland wasn't installed.

**Comment by HadetTheUndying** [comment]
> > it's only needed when running in wayland session (obs is wayland native too) otherwise it won't start unless ran with xwayland
> 
> This is one of the dependencies you have to install on your own because they are only useful under some conditions. The handbook covers this in the Wayland section. The only catch here is that you might have had obs and qt5-wayland when obs used qt5 and now with an update, qt6-wayland wasn't installed.

Any chance this needs to be added to the doc or post install message similar to what you get when you install steam?

**Comment by HadetTheUndying** [comment]
Also I can confirm this crash. Just happened to me

**Comment by oreo639** [comment]
Does https://github.com/void-linux/void-packages/pull/40652 work?

**Comment by oreo639** [comment]
Does https://github.com/void-linux/void-packages/pull/40652 work for you?

**Comment by paper42** [comment]
GNOME was updated to 42.6, can you still reproduce this?

**Comment by yurifuko** [comment]
hi, I cannot reproduce the crash anymore on 42.6
this issue can probably be closed
