### ISSUE TITLE
Package request: libjxl

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#40552]
### Package name

libjxl

### Package homepage

https://github.com/libjxl/libjxl

### Description

JPEG XL (.jxl) is a new royalty-free image file format. It supports [lossy compression mode](https://docs.krita.org/en/general_concepts/file_formats/lossy_lossless.html#lossless-compression) designed for photographs similar to the [JPEG](https://docs.krita.org/en/general_concepts/file_formats/file_jpeg.html#file-jpeg) file format, and also [lossless compression mode](https://docs.krita.org/en/general_concepts/file_formats/lossy_lossless.html#lossless-compression) similar to formats like [PNG](https://docs.krita.org/en/general_concepts/file_formats/file_png.html#file-png). In addition, it also supports saving animations with multiple frames like [GIF](https://docs.krita.org/en/general_concepts/file_formats/file_gif.html#file-gif).

```
* JPEGXL (required version >= 0.7.0), JPEG XL is a royalty-free raster-graphics file format that supports both
  lossy and lossless compression and is experimentally supported by Chrome, Firefox, and Edge.,
  <https://github.com/libjxl/libjxl>                                     
  Required by the Krita JPEG-XL filter
```

### Does the requested package meet the package requirements?

System, Compiled, Required

### Is the requested package released?

Yes

**Comment by oreo639** [comment]
https://github.com/void-linux/void-packages/pull/31397
