### ISSUE TITLE
Data loose on lvm after reboot

### ISSUE THREAD

**Issue by superiums** [void-linux/void-packages#40589]
i have two ext4 logical volum, one normal, one with luks crypt.
one day i found all data on luks lost. but the lv can be mounted normally, and fsck found no err.
i reformated it with luksFormat and mkfs.ex4. then tried seral times to write, and found:
- before reboot, everything goes right. write ok, read ok, size ok.
- after reboot, everything has gone, even folders, the volum seems newly formatted. 
- even exec `sync ` command, everything lost after reboot most time, only once the folder was kept.
- if write in arch instead of voidLinux, the files was kept , could be seen in both arch and void.
- if write something in voidLinux again, write ok, read ok, but after reboot, everything lost., **including the existing files**.
- fsck found no err.

all these situation happens in both luks lv and normal lv.

## additional

- my void system and home was also on lvm, but never loose.
- the normal lv which loose data was newly formatted in void. before this action, it works ok in other system.
- these volum was mounted manually without fstab.
- i usually mount volums to /dev/shm/xxx

## versions
- void linux, kernel 5.19.17_1 
- wayland
- wayfire 0.7.3
- thunar 4.6.11
- foot 1.13.1
- lvm2-2.02.187_2
- libllvm12-12.0.1_4
- cryptsetup-2.5.0_1

**Comment by ahesford** [comment]
You should probably post your `/etc/crypttab` and clarify what you mean by "mount point i usually use `/dev/shm/xxx`". None of your physical disks or LVM devices should be in `/dev/shm`.

**Comment by superiums** [comment]
> You should probably post your `/etc/crypttab` and clarify what you mean by "mount point i usually use `/dev/shm/xxx`". None of your physical disks or LVM devices should be in `/dev/shm`.

i mean i usually do like this:
```
sudo mount /dev/mapper/vg-lv3   /dev/shm/lv3

```

my lv was not listed in `/etc/crypttab`

**Comment by superiums** [comment]
> You should probably post your `/etc/crypttab` and clarify what you mean by "mount point i usually use `/dev/shm/xxx`". None of your physical disks or LVM devices should be in `/dev/shm`.

i mean i usually do like this:
```
sudo mount /dev/mapper/vg-lv3   /dev/shm/lv3

```
sorry for my unclear description.
my lv was not listed in `/etc/crypttab`

**Comment by ahesford** [comment]
Why are you mounting things under `/dev/shm`? That's ill advised.

**Comment by superiums** [comment]
> Why are you mounting things under `/dev/shm`? That's ill advised.

aha, got it ! this is the reason which caused the issue.
i've tried to mount lv to /media/xxx, and it never loose now.

i mount it to /dev/shm/xxx for temp use, usuallay i use /dev/shm as temp directory.
before use void linux, in arch, there's no problem in this way. 
but seems in voidLinux it works in different way from other os .

i'm now interesting with why mount to /dev/shm/xxx will cause data loose.

**Comment by sgn** [comment]
Do you have `elogind` installed and enabled?

**Comment by ahesford** [comment]
`/dev/shm` is used by the shared-memory interface and not intended for direct use by users. In general, you should never mount thing inside `/dev`.

**Comment by superiums** [comment]
> Do you have `elogind` installed and enabled?

yes , elogind was installed, and started.
but the service was not enabled.
maybe started by greetd.

**Comment by sgn** [comment]
`/dev/shm` is for SHared Memory IPC, it will be cleaned up up on logging out. https://github.com/systemd/systemd/issues/2039

**Comment by superiums** [comment]
> `/dev/shm` is for SHared Memory IPC, it will be cleaned up up on logging out. [systemd/systemd#2039](https://github.com/systemd/systemd/issues/2039)

yeh, files in it will be cleaned.
but mount device to it , data is not saved in it. 
in arch , no data will loose if do the same thing.

**Comment by sgn** [comment]
Noone care if it's a normal directory or mount-point:

https://github.com/systemd/systemd/blob/d9338387d94ad611233cf0753801eefccfda432a/src/shared/clean-ipc.c#L221-L300

Re: arch and Ubuntu, I don't know your configuration, I can't comment.
