### ISSUE TITLE
Akregator crashes on launch

### ISSUE THREAD

**Issue by AlexKurisu** [void-linux/void-packages#40633]
### Is this a new report?

Yes

### System Info

Void 6.0.9_1 x86_64 GenuineIntel uptodate FFFFF

### Package(s) Affected

akregator-22.08.2_1

### Expected behaviour

Run Akregator successfully

### Actual behaviour

Akregator crashes on launch with the following error:
```
Cannot mix incompatible Qt library (5.15.5) with this library (5.15.7)
Aborted
```

### Steps to reproduce

1. Run akregator

**Comment by classabbyamp** [comment]
cc @Johnnynator

**Comment by AlexKurisu** [comment]
Looks like not all qt5 packages were updated

**Comment by AlexKurisu** [comment]
Seems like i found the problem: `qt5-speech` was forgotten

**Comment by Johnnynator** [comment]
db12cef431cfa666fc2fd2fb1c2459a872e9a993
