### ISSUE TITLE
Krita is broken

### ISSUE THREAD

**Issue by sug0** [void-linux/void-packages#40647]
### Is this a new report?

Yes

### System Info

Void 6.0.9_1 x86_64 AuthenticAMD uptodate hold rrrmFFFFFFFFFFF

### Package(s) Affected

krita-5.0.8_2

### Expected behaviour

Regular program startup.

### Actual behaviour

Krita crashes upon startup with the following debug message:
```
Cannot mix incompatible Qt library (5.15.5) with this library (5.15.7)
Aborted
```
Updating to [5.1.3](https://github.com/KDE/krita/releases/tag/5.1.3) might fix the issue.

### Steps to reproduce

Start krita from a terminal window, to attain debug info. It should crash immediately.

**Comment by AlexKurisu** [comment]
Cannot reproduce, Krita works fine for me.
xuname: `Void 6.0.9_1 x86_64 GenuineIntel uptodate FFFFF`

**Comment by sgn** [comment]
wayland or X11?

**Comment by sug0** [comment]
x11

**Comment by sug0** [comment]
hm interesting. looks like a system reboot fixed the issue :s
