### ISSUE TITLE
Dracut zstd initramfs

### ISSUE THREAD

**Issue by Visone-Selektah** [void-linux/void-packages#40651]
Hi!
I'm trying to create my initramfs with zstd compression, to do so I added 
`compression="zstd"` to `/etc/dracut.conf.d/foo.conf` but neater installing kernels or runing dracut by hand the initramfs is created.
Also I tried to use `xbps-reconfigure -f foo` with the same result.
I build the kernel with that option enabled, also have zstd installed (I use btrfs with zstd compression)
Any ideas?
Thanks!!

**Comment by ahesford** [comment]
Does running `dracut` manually provide any useful output? Make sure you aren't running with `-q`/`--quiet`  and, if that doesn't produce anything useful, try `-v`/`--verbose`.

**Comment by Visone-Selektah** [comment]
Hi!
Always gives the same error, `/bin/dracut: line 2176: zstd: command not found`
It doesn't matter if I use config or running it manually

**Comment by Duncaen** [comment]
Install the `zstd` package?

**Comment by Visone-Selektah** [comment]
Hi!
I have it installed, I use btrfs with zstd compression

**Comment by ahesford** [comment]
Somehow I doubt btrfs relies on the zstd executable to do its encryption. If you don't see `/usr/bin/zstd` in response to

    which zstd

or

    command -v zstd

then you don't have the `zstd` package installed or your installation is corrupt.

**Comment by sgn** [comment]
> Hi! I have it installed, I use btrfs with zstd compression

btrfs doesn't require zstd installed to use zstd compression, it's zstd module from kernel.
Please install `zstd` package.
