### ISSUE TITLE
Ryzen 7000 iGPU requires newer linux-firmware-amd

### ISSUE THREAD

**Issue by wangp** [void-linux/void-packages#40674]
Hi, sorry for requesting a package update but I think opening an issue here will help other people.

The Ryzen 7000 series integrated GPU requires a newer linux-firmware version. With the current version in the repository, linux-firmware 20220411, the display will be stuck in a text mode (showing the last error messages) but it will not update. I believe the machine is otherwise running as Ctrl-Alt-Del works. You can also boot with the `nomodeset` option but the `amdgpu` driver will not work.

I'm now testing with linux-firmware 20221109. The iGPU works correctly with that version.

**Comment by icp1994** [comment]
https://github.com/void-linux/void-packages/pull/37081
