### ISSUE TITLE
Kalendar fails on startup

### ISSUE THREAD

**Issue by HiPhish** [void-linux/void-packages#40680]
### Is this a new report?

Yes

### System Info

Void 6.0.9_1 x86_64 AuthenticAMD uptodate rrmFFFFFF

### Package(s) Affected

kalendar-22.04.1_1

### Expected behaviour

The application is supposed to start up

### Actual behaviour

The application fails with the following message:

```
kalendar: symbol lookup error: kalendar: undefined symbol: _ZN15CalendarSupport19collectionFromIndexERK11QModelIndex
```

### Steps to reproduce

1. Enter `kalendar` on the shell

**Comment by paper42** [comment]
631c65575e93758dc95de2ab61bca9f84e7e0055
