### ISSUE TITLE
hostname not affect xauth

### ISSUE THREAD

**Issue by superiums** [void-linux/void-packages#40687]
i've changed hostname, but xauth still use the default one.

```
shvo@magicVo ~> hostname
magicVo
sme@magicVo ~> xauth list
void-live.lan/unix:0  MIT-MAGIC-COOKIE-1  3e8e37eee545c707b9461fd7f1a36c41
```

**Comment by superiums** [comment]
already rebooted.

**Comment by ahesford** [comment]
Are you have problems with X11? Having a stale entry in `.Xauthority` isn't *ipso facto* a problem.

**Comment by superiums** [comment]
> Are you have problems with X11? Having a stale entry in `.Xauthority` isn't _ipso facto_ a problem.

yeh, i have removed all xorg pkgs and using wayland and xwayland only.
check xauth for sometimes some program could not find the display.

maybe this is not a problem, i report it for the further stronger build for the void team.
