### ISSUE TITLE
Decrypting key for luks root partition fails with recent kernel/dracut

### ISSUE THREAD

**Issue by mithodin** [void-linux/void-packages#40703]
### Is this a new report?

Yes

### System Info

Void 5.19.10_1 x86_64 GenuineIntel uptodate rrFFFFFFFF

### Package(s) Affected

linux-6.0_1, dracut-053_5, gnupg-2.3.8_1

### Expected behaviour

gnupg is used at boot time to decrypt a key that is configured via the grub commandline with rd.luks.key to decrypt my root filesystem.

### Actual behaviour

The root filesystem fails to decrypt because the key file fails to decrypt.

### Steps to reproduce

1. Create a small partition holding a gpg-encrypted key file "root.key.gpg" for the root drive, which is luks encrypted
2. Put the private key capable of decrypting this key onto a yubikey.
3. Configure dracut to use this key at boot time via the grub commandline rd.luks.key=/root.key.gpg:UUID=<root fs UUID>
4. Add add_dracutmodules+=" crypt-gpg " to /etc/dracut.conf
5. Boot the computer with the yubikey plugged in

I have an initramfs with linux-5.19.10_1 where the process works fine. It used to work fine for many kernel versions, in fact. But starting with linux-5.19.15, the decryption fails. The root cause seems to be that gpg fails to decrypt the key file. On the rescue shell, I have confirmed that
 - gpg is able to access the yubikey (gpg --card-status lists it and gpg --edit-card shows the properties correctly)
 - gpg fails to decrypt the key file, giving only the message "unexpected error". Adding --verbose yields no additional information.

I'm at a loss where to go from here. I'm not even sure which of the involved components introduced the failure.

**Comment by sgn** [comment]
Can you check if the `gpg` inside your `5.19.10` initramfs is `gnupg` v1 or v2?

**Comment by mithodin** [comment]
it is gpg v2 in both cases. The 5.19.10 initramfs is running version 2.3.7, whereas the broken initramfs has 2.3.8

**Comment by sgn** [comment]
When you break into initramfs, please:
```
mkdir -p ${HOME}/.gnupg
echo "log-file /tmp/gpg.log" >>/tmp/gpg.conf
echo "log-file /tmp/gpg-agent.log" >>/tmp/gpg.conf
gpgconf --kill gpg-agent
```

After that, try to decrypt the luks key again, then show us the log.

**Comment by mithodin** [comment]
Sorry, it turns out I'm a dumbass. I didn't notice before that the device that holds the keys does not show up with the new kernel version. It's a micro sd card and with the working initramfs it shows up as /dev/mmcblk0, but not with the newer kernel.

**Comment by classabbyamp** [comment]
something changed in a recent version that made emmc storage not show up anymore, for some reason. see here: https://old.reddit.com/r/voidlinux/comments/y03b8b/baytrail_stopped_booting_after_updating_to_519/isgg847/

**Comment by mithodin** [comment]
@classabbyamp that's it. It's fixed :-D Thank you!
For anyone else looking for a solution: Add a file named mmc.conf (could be or any other name you like) in /etc/dracut.conf.d/ with these contents:
```
add_drivers+=" mmc_core mmc_block "
```
