### ISSUE TITLE
openmw: gdb required for crash logs

### ISSUE THREAD

**Issue by ernieIzde8ski** [void-linux/void-packages#40721]
### Is this a new report?

Yes

### System Info

Void 6.0.9_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFFFFFF

### Package(s) Affected

openmw-0.47.0_2

### Expected behaviour

OpenMW should be able to generate somewhat detailed crash logs with `gdb` when fatal errors occur. For example, typing `coe 100000 100000` into the console on a vanilla game can generate the following crash log: [https://pastebin.com/NjPHFgsJ](https://pastebin.com/NjPHFgsJ)

### Actual behaviour

Unless `gdb` is already installed, OpenMW is incapable of generating a crash log. A sample from `~/.config/openmw/openmw-crash.log`:

```
*** Fatal Error ***
 (signal 6)
Address: 0x3e800003985

System: Linux vivec 6.0.9_1 #1 SMP PREEMPT_DYNAMIC Fri Nov 18 16:45:48 UTC 2022 x86_64

Executing: gdb --quiet --batch --command=/tmp/gdb-respfile-pfN1ac

Failed to create a crash report. Please make sure that 'gdb' is installed and present in PATH then crash again.
Current PATH: /home/ernie/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
```

### Steps to reproduce

1. Run openmw
2. Do something to cause a fatal crash (entering `coe 100000 100000` onto the in-game console, accessible via backtick by default, should work)
3. Observe `~/.config/openmw/openmw-crash.log`

**Comment by loreb** [comment]
I see exactly the same, so I guess that "needs-testing" can go away.

**Comment by paper42** [comment]
I think the error message is clear enough and gdb should not be added to dependencies.

**Comment by dataCobra** [comment]
`gdb` is not necessary as a dependency for `openmw`. It's more of an __optional__ package to make sure that reports can be generated.

I agree with paper42, the error message is self-explanatory and a `xbps-install gdb` after reading the error message is not a big problem. :+1:

**Comment by ernieIzde8ski** [comment]
sure, makes sense to me
