### ISSUE TITLE
Wezterm ask for Jetbrains Mono Font

### ISSUE THREAD

**Issue by AgarimOSLinux** [void-linux/void-packages#40736]
### Is this a new report?

Yes

### System Info

Void x86_64

### Package(s) Affected

wezterm-20221119_1

### Expected behaviour

It should work fine without JetbrainsMono font.

### Actual behaviour

Wezterm complaint about JetbrainsMono font. Its almos impossible to use the terminal emulator without installing this font.
Once installed the font it works as usual.
There were another font that i guess i had it installed in my system.

My opinion: rebuild it without any font dependency and with fonts.patch (no font included in package). Everybody has several fonts in their machines.

Also you could use again the font.patch again like in the former version.

Otherwise you could create new packages from the missing fonts. I don't think is a good idea.

### Steps to reproduce

1) Start wezterm
2) Execute a command (like update the system).
3) New windows with error opens.

**Comment by classabbyamp** [comment]
cc @jbenden

**Comment by voidscuttle** [comment]
I'm experiencing something similar but a bit different.
1. Launching wezterm without a wezterm config file does not work and produces this: 

```
ERROR  mux::connui > Configuration Error: Unable to load a font specified by your font=wezterm.font('JetBrains Mono', {weight="Regular", stretch='Normal', style=Normal}) configuration. Fallback(s) are being used instead, and the terminal may not render as intended. See https://wezfurlong.org/wezterm/config/fonts.html for more information
ERROR  wezterm_gui::frontend > Failed to create window: failed to get font metrics!?: obtaining metrics for font_size=12 @ dpi 96: unable to load font idx 1!?
```
2. Launching wezterm with a config file with a different font (e.g. Iosevka) specified launches the terminal as expected and runs normal commands. However when attempting to run a command prefixed with doas (I would assume sudo is the same but I do not have it installed to test) results in the command hanging and a second wezterm window spawns with this error repeated over and over: 

```
Unable to load a font matching one of your font_rules: wezterm.font('JetBrains
Mono', {weight="Regular", stretch='Normal', style=Normal}). Fallback(s) are
being used instead, and the terminal may not render as intended. See https://
wezfurlong.org/wezterm/config/fonts.html for more information
```

**Comment by jbenden** [comment]
When wezterm is built without font support, it needs to use `monospace`. At least that's the current thought that I'm testing out...

**Comment by jbenden** [comment]
I just posted a PR for this!
