### ISSUE TITLE
tracebox is not maintained

### ISSUE THREAD

**Issue by kruceter** [void-linux/void-packages#40751]
The package of interest was last modified in 2018 ([1]).

Also uses libcrafter which became unmaintained at least officially ([2]).

Another concerning factor to be wary of is the build failure (see issue #39960).

Since no upstream changes had been made since 2018 and its maintainers are inactive too, removal of the package from the repository may be the solution.

I would like to know your opinions on the matter.

[1]: https://github.com/tracebox/tracebox
[2]: https://github.com/pellegre/libcrafter

**Comment by Duncaen** [comment]
There are probably hundreds of packages that haven't been updated in 4 years but are still being used.
Its probably enough to set `-std=c++14` to keep the package building.

**Comment by kruceter** [comment]
> Its probably enough to set `-std=c++14` to keep the package building.

You have my gratitude, Duncan. This definitely lets the package live a little longer.
