### ISSUE TITLE
tlmgr is broken because Perl can't find TLConfig.pl

### ISSUE THREAD

**Issue by Rowaaaaan** [void-linux/void-packages#40830]
### Is this a new report?

Yes

### System Info

Void 6.0.9_1 x86_64 GenuineIntel uptodate rrrmFFFFFF

### Package(s) Affected

texlive-20210325_4

### Expected behaviour

`tlmgr` in general should be working. For instance, `tlmgr update --all` should update the packages in my local repository.

### Actual behaviour

Doing any kind of action with `tlmgr` will output the following:
```
Can't locate TeXLive/TLConfig.pm in @INC (you may need to install the TeXLive::TLConfig module) 
(@INC contains: 
/texmf-dist/scripts/texlive/TeXLive/TLConfig.pm /texmf-dist/scripts/texlive /tlpkg 
/usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl
/usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/share/texmf-dist/scripts/texlive/tlmgr.pl line 61.

BEGIN failed--compilation aborted at /usr/share/texmf-dist/scripts/texlive/tlmgr.pl line 61.
```

### Steps to reproduce

1. Enter `tlmgr` --it doesn't matter what action you use.
2. Get the error.

**Comment by Rowaaaaan** [comment]
I did some digging into the script myself to see what the problem was, since I'm not sure if this is a texlive issue or a Perl issue. 

From line 41:
```perl
BEGIN {
  # make subprograms (including kpsewhich) have the right path:
  $bindir = $Master;
  $ENV{"PATH"} = "$bindir:$ENV{PATH}";

  $::installerdir = $Master;  # for config.guess et al., see TLUtils.pm

  # make Perl find our packages first:
  unshift (@INC, "$Master/tlpkg");
  unshift (@INC, "$Master/texmf-dist/scripts/texlive");
...
use TeXLive::TLConfig;
use TeXLive::TLPDB;
```
The error occurs at line 61, where tlmgr uses the TLConfig:
```perl
use TeXLive::TLConfig;
```
The confusing part is how the error says that it can't find TLConfig @INC, which is at `/usr/share/texmf-dist/scripts/texlive`, despite the fact that `TLConfig.pm` _is_ in `/usr/share/texmf-dist/scripts/texlive/TeXLive`
![image](https://user-images.githubusercontent.com/82100519/204500041-eb3c5857-f128-4bb8-9bb2-4349125460d5.png)

So, I tried hardcoding the absolute path to `TLConfig.pm`, by adding the line:
```perl
unshift (@INC, "$Master/texmf-dist/scripts/texlive/TeXLive/TLConfig.pm");
```
and `tlmgr` still throws the exact same error

**Comment by nsajko** [comment]
This issue seems to be a dupe: https://github.com/void-linux/void-packages/issues/36738

**Comment by classabbyamp** [comment]
when you use `texlive` you shouldn't be using `tlmgr`. if you want to use `tlmgr`, use `texlive-bin`. see https://docs.voidlinux.org/config/texlive.html for info about the difference
