### ISSUE TITLE
rawtherapee: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by crocusino** [void-linux/void-packages#40917]
### Is this a new report?

Yes

### System Info

Void 6.0.10_1 x86_64 AuthenticAMD uptodate FF

### Package(s) Affected

rawtherapee-5.8_1

### Expected behaviour

The program is expected to run.

### Actual behaviour

Trying to run:
```
rawtherapee
rawtherapee: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory
```

There is `libjpeg.so.8` now and not `libjpeg.so.62`

`ldd /usr/bin/rawtherapee` says it is linked against `libjpeg.so.8` and does not claim any missing dep:

```
libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007f8ea3944000)
```

### Steps to reproduce

try to run `rawtherapee`

**Comment by kruceter** [comment]
I am unable to reproduce this issue.

`Void 5.15.78_1 x86_64-musl GenuineIntel uptodate hold rFFFFFFF`

![2022-12-05-180621_1365x768_scrot](https://user-images.githubusercontent.com/116987897/205670806-410e400c-ba98-422a-b2a7-b7fdc659093a.png)

**Comment by crocusino** [comment]
What does `ldd /usr/bin/rawtherapee` say about libjpeg?

What version of `libjpeg-turbo` do you have? (mine is `libjpeg-turbo-2.1.4_1`)

**Comment by sgn** [comment]
Can you help to install `strace`, then:
```
strace /usr/bin/rawtherapee 2>/tmp/strace.log
```

And post the `/tmp/strace.log` file?

**Comment by sgn** [comment]
I guess your `rawtherapee` tries to `dlopen` a pre-compiled plugins that was compiled for Debian/Ubuntu.

**Comment by crocusino** [comment]
Strange, when run under strace, it "works". When tried again (without strace), it gives the same error.

The strace log is here: [https://0x0.st/ok58.log](https://0x0.st/ok58.log)

Otherwise I have no tweaks in xbps / void. Recent installation - up to date at the moment.

**Comment by crocusino** [comment]
I am closing this bug report - not relevant anymore. The void's  /usr/bin/rawtherapee seems to truly work fine. The rawtherapee that had these strange libjpeg issues was an old build of mine. After some time with testing void I changed from bash to oksh and all my old settings thus came into effect (PATH to custom builds...) and that's all in it. I am sorry for this fuss.
