### ISSUE TITLE
build LanguageTool from source

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#40910]
I just found out that [the template of LanguageTool](https://github.com/void-linux/void-packages/tree/master/srcpkgs/LanguageTool) uses a compiled distribution of the software. Is it preferable to rewrite the template to build the software from a released source? https://github.com/languagetool-org/languagetool/tags

**Comment by mhmdanas** [comment]
It's probably a good idea, yeah.

**Comment by Eloitor** [comment]
Waiting for #42390
