### ISSUE TITLE
python3-lxml should depend on python3-cssselect

### ISSUE THREAD

**Issue by rubin55** [void-linux/void-packages#40941]
### Is this a new report?

Yes

### System Info

Void 6.0.10_1 x86_64 AuthenticAMD uptodate rrmFFFF

### Package(s) Affected

python3-lxml-4.9.0_1

### Expected behaviour

I install python3-lxml. Python3-lxml contains lxml/cssselect.py. When that is used, it in turn depends on python3-cssselect. I expect python3-lxml to correctly depend on python3-cssselect.

### Actual behaviour

[rubin@THINK lessfilter-pygmentize (master)]$ python main.py 
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/lxml/cssselect.py", line 13, in <module>
    import cssselect as external_cssselect
ModuleNotFoundError: No module named 'cssselect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rubin/Syncthing/Source/Other/lessfilter-pygmentize/main.py", line 8, in <module>
    from lxml.cssselect import CSSSelector
  File "/usr/lib/python3.11/site-packages/lxml/cssselect.py", line 15, in <module>
    raise ImportError(
ImportError: cssselect does not seem to be installed. See http://packages.python.org/cssselect/

### Steps to reproduce

1. install python3-lxml
2. use lxml/cssselect.py
3. observe traceback
4. install python3-cssselect
5. observe working

**Comment by sgn** [comment]
`cssselect` is an optional dependency not a hard dependency. If you need it, install it. Other people don't.

**Comment by sgn** [comment]
https://github.com/lxml/lxml/blob/lxml-4.8.0/setup.py#L76-L80
