### ISSUE TITLE
mosh 1.4.0_2 doesn't update utmp

### ISSUE THREAD

**Issue by sbromberger** [void-linux/void-packages#40972]
### Is this a new report?

Yes

### System Info

Void 5.19.0-26-generic x86_64 AuthenticAMD uptodate FF

### Package(s) Affected

mosh_1.4.0_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

there were a few old bug reports, but nothing current.

### Expected behaviour

Mosh, when linked with libutempter, is supposed to write entries into utmp when connections are made. I have built mosh from source and also installed the package, and neither method logs to utmp.

### Actual behaviour

I can confirm via strace that libutempter.so is being opened, but utmp is not being accessed.

### Steps to reproduce

1. `xbps-install mosh`
2. `mosh <host>`
3. `w` or `who`

**Comment by vincele** [comment]
Is this another instance of the bug that was fixed here: https://github.com/void-linux/void-packages/pull/40988 ?

**Comment by paper42** [comment]
this should be fixed now
