### ISSUE TITLE
[rfc] native aarch64 builders

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#40980]
Cross-compilation is subtle.

1. any mainteiners interested? @leahneukirchen @classabbyamp @paper42 
2. any users interested in supporting this?
3. hardware suggestions

I'd be happy to donate some money to purchase hardware,
if you think it's doable and enough people are interested.

**Comment by Eloitor** [comment]
I'm interested in this as a user. I would like to use void in my pinephone. I tried to create a [template for osmin](https://github.com/void-linux/void-packages/pull/37298) (an OSM app) but it failed to build for aarch64.

**Comment by dkwo** [comment]
Compiling natively is fine, but you'd have to rebuild lots of subtly miscompiled stuff first, like qmake, libtool, etc, and build stuff like sagemath yourself, while having aarch64 as a first-class citizen (i.e. native) would avoid all of this.

**Comment by leahneukirchen** [comment]
I think the main problem is getting adequate hardware as an aarch64 builder, as server-grade aarch64 systems are still quite expensive; and most of them cannot run armv7 code, so it can't be a builder for both archs.

Also this merely shifts the burden of fixing cross-compiling to the other architectures.

**Comment by leahneukirchen** [comment]
An rpi 4 is not fast enough to keep up as a full builder.

**Comment by dkwo** [comment]
>  But if some cross-compiled packages in the build chain are broken, that complicates matters a lot.

Exactly, see `libtool`, possibly `qmake`.

**Comment by dkwo** [comment]
@leahneukirchen How about an M1 Mac mini from Apple?

**Comment by leahneukirchen** [comment]
Doesn't run armv7 code either. Probably fast enough, may need external storage.

Not sure if the different page size is problematic.

**Comment by dkwo** [comment]
Page size affects a few packages (I assume that https://github.com/AsahiLinux/docs/wiki/Broken-Software also applies in the reverse way), among them zig; many have already been already.
@leahneukirchen Would you be interested in receiving something like that as a gift, provided enough people contribute?

**Comment by paper42** [comment]
It is simple to modify xbps-src to use qemu, just an example:
```patch
--- a/common/xbps-src/shutils/chroot.sh
+++ b/common/xbps-src/shutils/chroot.sh
@@ -160,7 +160,7 @@ chroot_handler() {
 
     if [ "$action" = "chroot" ]; then
         $XBPS_COMMONDIR/chroot-style/${XBPS_CHROOT_CMD:=uunshare}.sh \
-            $XBPS_MASTERDIR $XBPS_DISTDIR "$XBPS_HOSTDIR" "$XBPS_CHROOT_CMD_ARGS" /bin/xbps-shell
+            $XBPS_MASTERDIR $XBPS_DISTDIR "$XBPS_HOSTDIR" "$XBPS_CHROOT_CMD_ARGS" /usr/bin/qemu-aarch64-static /bin/bash /bin/xbps-shell
         rv=$?
     else
         env -i -- PATH="/usr/bin:$PATH" SHELL=/bin/sh \
@@ -178,7 +178,7 @@ chroot_handler() {
             ${XBPS_ALT_REPOSITORY:+XBPS_ALT_REPOSITORY=$XBPS_ALT_REPOSITORY} \
             $XBPS_COMMONDIR/chroot-style/${XBPS_CHROOT_CMD:=uunshare}.sh \
             $XBPS_MASTERDIR $XBPS_DISTDIR "$XBPS_HOSTDIR" "$XBPS_CHROOT_CMD_ARGS" \
-            /void-packages/xbps-src $XBPS_OPTIONS $action $pkg
+            /usr/bin/qemu-aarch64-static /bin/bash /void-packages/xbps-src $XBPS_OPTIONS $action $pkg
         rv=$?
     fi
 

```
```sh
echo XBPS_CHROOT_CMD=bwrap >> etc/conf
./xbps-src binary-bootstrap -m maarch aarch64-musl
cp /usr/bin/qemu-aarch64-static maarch/usr/bin/
./xbps-src -m maarch pkg libtool
./xbps-src -m maarch pkg ntl
```
This assumes bubblewrap, qemu-user-static and binfmt are available on the host. It would have to be improved if it was meant to be merged to void-packages and it's very slow.

**Comment by leahneukirchen** [comment]
> Would you be interested in receiving something like that as a gift, provided enough people contribute?

I don't have resources to run this myself locally atm.

**Comment by BikyAlex** [comment]
>any users interested in supporting this?
I'm willing to buy a Honeycomb LX2K and run it 24/7, I have been looking into it for a few years. Would that fit the bill for compiling aarch64, aarch64-musl, armv7 and armv7-musl? It's a NXP LX2160A 16x A72 cores aarch64 CPU.

I would love to contribute to Void some processing horsepower for native building arm packages. Some packages, like libreoffice are marked as non-cross-compileable. But I don't know how I'd be sharing it with Void devs, I'd like to share Void LXC containers for each architecture, but if really necessary, I could share access to the box itself, but I'd have to split my network and put it in a DMZ or something.

**Comment by dkwo** [comment]
Can anyone clarify: does current Void's infrastructure (buildbot etc) allow adding native aarch64 builders, sponsored by @BikyAlex or others? is there any obstruction?

**Comment by Duncaen** [comment]
We can just integrate some random never seen before users hardware into our build infrastructure.

**Comment by dkwo** [comment]
How about shipping hardware to a maintainer? Can this be discussed, or is it also excluded similar to money donations?

It seems RK3588 could be good enough, and e.g. an Orange Pi 5 Plus board is sold on Amazon for 150$. I'd be willing to buy it and ship it to a maintainer, if that can be used as a builder.

**Comment by BikyAlex** [comment]
Huh, q66 applied for Oregon aarch64 builders? Nice. I really wish Void had a bit more love for aarch64. I would also be willing to buy SBCs and send them to contributors, but that will count as donations, and I doubt any of the people working on void want to get in legal trouble. Most (all?) of them are doing a work of love here.

That said, can't force anyone to just maintain aarch64 packages and the many that cannot cross-compile, will be found to be broken when compiling on aarch64.
