### ISSUE TITLE
Upgrading packages with breaking changes

### ISSUE THREAD

**Issue by zlice** [void-linux/void-packages#40998]
Wanted to test something in ffmpeg 5.1.2 out. Upgrading `shlibs` and the `template` work, however it appears that `libavresample` was deprecated. And xbps complains about trying to upgrade anything with `libavutil` that relied on it.

```
xbps-install -fu --repository=.
libavutil-5.1.2_1 in transaction breaks installed pkg `libavresample-4.4.3_2'
libavutil-5.1.2_1 in transaction breaks installed pkg `libavresample-32bit-4.4.3_2'
Transaction aborted due to unresolved dependencies.
```

Is there a good way to upgrade? I could force dependency removal but that doesn't seem clean or like what a common update would do.

I only see ffmpeg packages directly used by this on a remove so I'm not sure if anything using ffmpeg relies on it.

**Comment by zlice** [comment]
Thanks. Think that solves it. Though I forgot all the deps complain about shlibs and stop the install.

I guess follow up, should I make a PR? I doubt anybody is hurting for ffmpeg-5 and I imagine it may break things.

**Comment by paper42** [comment]
https://github.com/void-linux/void-packages/pull/36315

**Comment by zlice** [comment]
Think I found a better answer to the original question. `srcpkgs/removed-packages/template` looks to be the proper way to remove packages.
