### ISSUE TITLE
Incremental compilation support (xbps-src)?

### ISSUE THREAD

**Issue by Animeshz** [void-linux/void-packages#41008]
I don't know if this is a valid issue, but compiling big projects like kernel/chromium etc. takes a while, and without cache preservation they take forever to build different versions.

If there could be a incremental compilation support in xbps-src as it already creates a stateful `masterdir`, it could really boost few aspects, such as testing for issues in different versions, and [producing patches](https://www.reddit.com/r/voidlinux/comments/z0mfbh/xbpssrc_creating_patches_for_a_new_package) for them.

Let me know your thoughts!

**Comment by Animeshz** [comment]
One way could be to link `masterdir/pkgname-pkgver/` to a local git repository via a cli-option, which could let it to use the git-tags for the version information and checkouts.

**Comment by Animeshz** [comment]
I know we can use multithreading, but applying a few line change patch from internet and building kernel again still takes about 30 minutes or so, while that could take a file compilation and merge final output with a small linking process (a few seconds?)...

**Comment by Animeshz** [comment]
Compilers are self sufficient to handle incrementals, we just gotta preserve the build files for them somehow. That doesn't looks like a big architectural change to me...

**Comment by Anachron** [comment]
Did you try it with the settings @classabbyamp suggested?

Because XBPS_CCACHE=yes is responsible for caching build artifacts.

**Comment by Animeshz** [comment]
Ah yes, sorry for the late reply, the `-C` actually just keeps the package there at the build directory (I think like `xbps-src install` instead of `xbps-src pkg`), but if you add the patches or do something else it wouldn't rebuild the package. If you really want to build the package introducing a small change you gotta again clean the directory, extract, patch, and finally fully-build (no incremental).

**Comment by paper42** [comment]
You don't have to do that, any step can be run again with `-f`, but patch and install are not repeatable, so you will have to manually apply the patch/unpatch it (because patching once patched sources obviously won't work) or use -t and remove destdir if you want to run those more than once.

**Comment by Anachron** [comment]
Of course you have to rebuild after patching. But even that should be much faster with ccache because a patch wouldnt touch every file most likely.

How do you suggest this should work?

**Comment by paper42** [comment]
Running `build` after patching a file should do an incremental build with most regular build systems. It will be faster than ccache, but it won't work if `$version` is updated because then $wrksrc is different, ccache will work in both cases.
