### ISSUE TITLE
qucs install fails

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#41088]
### Is this a new report?

Yes

### System Info

Void 6.0.12_1 x86_64 GenuineIntel uptodate rFFF

### Package(s) Affected

qucs-0.0.19

### Expected behaviour

`sudo xbps-install -S qucs` installs qucs.

### Actual behaviour

```
$ sudo xbps-install -S qucs
[*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
MISSING: qt>=4.5.3_1
Transaction aborted due to unresolved dependencies.
```

### Steps to reproduce

1. Try to install qucs.

**Comment by Eloitor** [comment]
It seems that this package is removed from the repos but it keeps appearing in https://voidlinux.org/packages/

**Comment by paper42** [comment]
It is removed, we don't have qt4 anymore

**Comment by Eloitor** [comment]
Then it shouldn't appear in https://voidlinux.org/packages/?arch=x86_64&q=qucs, right?

**Comment by paper42** [comment]
Binary packages are not automatically removed from repositories when the template is removed, so they will show up in repositories.
