### ISSUE TITLE
dbus pkg-config file sets incorrect include directory

### ISSUE THREAD

**Issue by Owenlaw222** [void-linux/void-packages#41102]
### Is this a new report?

Yes

### System Info

Void 6.0.12_1 x86_64 AuthenticAMD uptodate FFFFFFF

### Package(s) Affected

dbus-devel-1.14.4_1

### Expected behaviour

When calling `pkg_check_modules(dbus REQUIRED "dbus-1")` in a cmake file the `dbus_INCLUDE_DIRS` variable should be set to `/usr/include/dbus-1.0/dbus` as that is where the headers are located.

### Actual behaviour

When calling `pkg_check_modules(dbus REQUIRED "dbus-1")` the include directory variable is instead set to the path `/usr/include/dbus-1.0/usr/lib64/dbus-1.0/include` which does not exist.

### Steps to reproduce

1. Call `pkg_check_modules(dbus REQUIRED "dbus-1")` in a cmake file
2. Call `message(DEBUG ${dbus_INCLUDE_DIRS})` following the previous call
3. Note that the path which is returned is not valid

**Comment by sgn** [comment]
```sh
$ pkg-config --cflags dbus-1
-I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include
$ grep dbus_INCLUDE_DIRS CMakeCache.txt 
dbus_INCLUDE_DIRS:INTERNAL=/usr/include/dbus-1.0;/usr/lib64/dbus-1.0/include
```

It's a list of 2 directories. Fix your `CMakeLists.txt`
