### ISSUE TITLE
Package request: lapce

### ISSUE THREAD

**Issue by andreisou** [void-linux/void-packages#41175]
### Package name

lapce

### Package homepage

https://github.com/lapce/lapce

### Description

A modern open source code editor in Rust

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by icp1994** [comment]
https://github.com/void-linux/void-packages/pull/39261 https://github.com/void-linux/void-packages/pull/40970

**Comment by zen0bit** [comment]
#41355
