### ISSUE TITLE
Package request: tapper 

### ISSUE THREAD

**Issue by kzkin** [void-linux/void-packages#41187]
### Package name

tapper

### Package homepage

http://kbd-tapper.sourceforge.net/en.html

### Description

A keyboard layout switcher for X Window System and Wayland. Tapper selects specified keyboard layout when user 'taps' specified key. It always 'selects' layouts and never 'toggles' them.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by kzkin** [comment]
arch PKGBUILD example

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/issues/22404
