### ISSUE TITLE
binutils-2.35.Package request: 

### ISSUE THREAD

**Issue by malv-c** [void-linux/void-packages#41204]
### Package name

binutils

### Package homepage

not needed

### Description

2.39 make larger bin than 2.35 so how can i build and use it here ???

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

Yes

**Comment by paper42** [comment]
This is not an issue, if you are asking how to downgrade a package, please read the appropriate section in the handbook or ask in the appropriate place.

**Comment by malv-c** [comment]
Michael to "downgrade" in void-packages is not the same as with pkgdb
so here is the correct place to ask about it
as not docu/imple/mented with xbps-src it is an issue here.

Le mar. 20 déc. 2022 à 22:36, Michal Vasilek ***@***.***> a
écrit :

**Comment by paper42** [comment]
Could you explain why you want void-packages to downgrade binutils to 2.35? Every single package seems to build and work fine and it is part of the toolchain, so I am not sure that's even possible. We definitely do not want to do it without a very good reason.
I am not sure what you want void-packages to document. Documenting reverting a commit and checking out at a specific commit hash is not in scope of void-packages and fixing all of the other packages to properly work with the old version is not something that can be documented.

**Comment by malv-c** [comment]
re
as i wrote 2.35 give smaller binary executables
as i want to rebuild all packages with -Os -flto and elses then sstrip of
https://github.com/BR903/ELFkickers to remove unused space on it before
install on my devices
as you wrote that in void-packages individual packages are not handled the
issue is on the design...
thanks Michael

Le mer. 21 déc. 2022 à 09:02, Michal Vasilek ***@***.***> a
écrit :

**Comment by paper42** [comment]
Do you have a comparison between packages built with each version? We will definitely not downgrade a core package like this just because one user prefers it. Void may not be the best choice for you, I think that the space saved by using an old version will be tiny if any and not splitting docs and manpages to subpackages will be a much bigger issue.

**Comment by malv-c** [comment]
not yet i have to install an other void os and extract your build
process from void-packages before
anyway i didn't ask for a downgrade in the distro yet
split docs and manpages sound horrible
...
