### ISSUE TITLE
Package request: Outguess (Image/Audio Stenography Tool) 

### ISSUE THREAD

**Issue by n3v3rde4d** [void-linux/void-packages#41217]
### Package name

steghide 

### Package homepage

https://steghide.sourceforge.net/

### Description

Steghide is a steganography program that is able to hide data in various kinds of image- and audio-files. The color- respectivly sample-frequencies are not changed thus making the embedding resistant against first-order statistical tests.

### Does the requested package meet the package requirements?

System, Compiled, Required

### Is the requested package released?

Yes

**Comment by Eloitor** [comment]
It seems that there is a known way to get the secrets hidden with steghide: https://github.com/b4shfire/stegcrack 
Do you know a better alternative?

**Comment by n3v3rde4d** [comment]
What is this alternative way that you speak of? I was hoping to use this package with another program on my system.

**Comment by Eloitor** [comment]
I mean another steganography program which uses a better algorithm. Is there any reason you need steghide specifically? With which program do you want to use it?

**Comment by n3v3rde4d** [comment]
I would like to use the program with "tomb" which has been my on-the-fly encryptlion replacment. Use the of full capabilities of "tomb" I would need "steghide" and "cloakifiy". Both programs enable the use of tomb options for hiding encrypted volume/keys this can be seen on their webpage under the section..."Deniable, but easy to remember, key storage"--[](https://dyne.org/software/tomb/)

**Comment by n3v3rde4d** [comment]
also regarding the stenography tools the only one that I've identified that is availble in the repo is stegsnow

**Comment by Eloitor** [comment]
Tomb is just a shell script, so in theory you could replace steghide with another tool. I found [outguess](https://github.com/resurrecting-open-source-projects/outguess) which is similar. I can package it when I have time.

By the way, [stegseek](https://github.com/RickdeJager/stegseek) can find messages hidden with steghide in minutes.

**Comment by n3v3rde4d** [comment]
You're right in theory I should be able to modify the script to use "outguess" (thank you btw for making aware of the tool) If you could commit the pacakge that would be greatly appreciated!! Sorry for the late respose I had holiday stuff to attend to, please lelt me know what I can do to assist OR where I should be looking out for the package commit

**Comment by n3v3rde4d** [comment]
Just for clarity is this issue still open becuase the package is still in the process of being commited to the VoidLinux package repository?

**Comment by n3v3rde4d** [comment]
I'm not sure if I should close this issue...?--I still can't seem to access "Outguess" in the void repository although it says the packaged has been tagged and pushed.  I have yet to see official confirmation or comment that the package is available.

**Comment by paper42** [comment]
The state of the pull request is open, not merged. So it has not been merged to repositories and you can not install it without compiling it on your own with xbps-src.

**Comment by n3v3rde4d** [comment]
Thank you for the calrification, I've been trying to get this tool working for my void security project--I was just wanting to know where things stood as of today.

**Comment by paper42** [comment]
You can follow the instructions in README.md to build the package from that PR, it's quite easy to do.

**Comment by n3v3rde4d** [comment]
I'll goahead and give it a shot--should I post questions I have on PR comment chain if I run into issues?

**Comment by paper42** [comment]
please use the #voidlinux:libera.chat IRC channel, it will be quicker there and it's meant for questions like this

**Comment by n3v3rde4d** [comment]
Understood thank you!
