### ISSUE TITLE
Qbittorrent stopped working

### ISSUE THREAD

**Issue by SolitudeSF** [void-linux/void-packages#4124]
After last qbittorrent update (or boost rebuild, cant remember now), qbittorrent started crashing on start.
```
Caught signal: SIGSEGV
Stack trace:
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x17c615  [0x7f3a7dc1c615]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x2f5f63  [0x7f3a7dd95f63]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1cfc03  [0x7f3a7dc6fc03]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0xe68bf  [0x7f3a7db868bf]
  /usr/lib/libpthread.so.0 : ()+0x7c63  [0x7f3a7b758c63]
  /usr/lib/libc.so.6 : clone()+0x3f  [0x7f3a7aaef9bf]
```
Im not sure if this is upstream issue

**Comment by maxice8** [comment]
Installed and it started fine here

**Comment by SolitudeSF** [comment]
ok, guess im taking this to upstream then.

**Comment by SolitudeSF** [comment]
actually, it only crashes when you have added at least one torrent and then it crashes after inconsistent time.

**Comment by be404err** [comment]
x86_64

```
Caught signal: SIGSEGV
Stack trace:
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x17c125  [0x7fddddeef125]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x17ddc5  [0x7fddddef0dc5]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0x1cfc03  [0x7fddddf42c03]
  /usr/lib/libtorrent-rasterbar.so.9 : ()+0xe68bf  [0x7fdddde598bf]
  /usr/lib/libpthread.so.0 : ()+0x7c63  [0x7fdddba2bc63]
  /usr/lib/libc.so.6 : clone()+0x3f  [0x7fdddadc29bf]
Segmentation fault
```
Previous version qbittorrent-4.1.3_1 was working fine and _2 segfault right after add any torrent.

**Comment by Ophidiophobia** [comment]
Looks like problem is that boost and libtorrent-rasterbar are compiled using C++14 mode and qbittorrent sticks to C++11 mode and causes ABI incompabilities. 

https://github.com/qbittorrent/qBittorrent/issues/9485

I removed CONFIG += c++11 in src/src.pro of qbittorrent and then it compiled and ran fine so far.
