### ISSUE TITLE
void-socklog: ucspi is configured to use tcpsvd which doesn't exist.

### ISSUE THREAD

**Issue by sbromberger** [void-linux/void-packages#41300]
### Is this a new report?

Yes

### System Info

Void 6.0.13_1 x86_64 AuthenticAMD uptodate FF

### Package(s) Affected

void-socklog

### Expected behaviour

`socklog-conf ucspi-tcp nobody log` creates a ucspi-tcp configuration for socklog, but the `/etc/sv/socklog-ucspi/run` script refers to `tcpsvd`:

```
exec tcpsvd -vllogserver -unobody 0 "$PORT" socklog ucspi TCPREMOTEIP
```
which doesn't exist (as far as I can tell) for Void. Using `tcpserver` from s6-networking or from ucspi-tcp might work.

I expected the default installation of socklog-ucspi to reference a utility that exists on my system (or that can be installed).

### Actual behaviour

```
bash-5.1# head /var/log/socklog-ucspi-tcp/main/current
@4000000063a9c4ee2b51dddc ./run: 4: exec: tcpsvd: not found
@4000000063a9c4ef2b67cb24 ./run: 4: exec: tcpsvd: not found
@4000000063a9c4f02b843494 ./run: 4: exec: tcpsvd: not found
```

### Steps to reproduce

1. `xbps-install socklog-void xtools` (if not present)
2. `socklog-conf ucspi-tcp nobody log`
3. `head /var/log/socklog-ucspi-tcp/main/current`
4. `xlocate tcpsvd`

**Comment by kruceter** [comment]
I could reproduce the issue.

According to `socklog-conf(8)`,

> socklog-conf arranges for tcpsvd(1) to run socklog(8) under the uid
> and gid of acct and to listen on the TCP socket 0.0.0.0:10116.

tcpsvd(1) comes from http://smarden.org/ipsvd/index.html. Either ipsvd has to be packaged or socklog should be patched to use a different piece of software as well.
