### ISSUE TITLE
Package request: omxplayer

### ISSUE THREAD

**Issue by uti5** [void-linux/void-packages#41369]
### Package name

omxplayer

### Package homepage

https://github.com/popcornmix/omxplayer

### Description

Video player that doesn't require X11 and is optimized for Raspberry Pi.  It is available for armv7l but not for aarch64.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by zlice** [comment]
This was a package, but was recently removed.

**Comment by classabbyamp** [comment]
vlc is built with this enabled on arm
