### ISSUE TITLE
akonadi5 service fails to start with current qt5

### ISSUE THREAD

**Issue by ernieIzde8ski** [void-linux/void-packages#41360]
### Is this a new report?

Yes

### System Info

Void 6.0.15_1 x86_64 AuthenticAMD uptodate rrmFFFFFFFFFFF

### Package(s) Affected

akonadi5-22.08.2_1 qt5-5.15.7+20221119_1

### Expected behaviour

`akonadictl start` should be able to start the akonadi server

### Actual behaviour

akonadi recognizes that the current qt5 library is incompatible and exits with code 0

```
[1 0] ernie@vivec% akonadictl start
org.kde.pim.akonadictl: Starting Akonadi Server...
org.kde.pim.akonadictl:    done.
[1 0] ernie@vivec% Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
org.kde.pim.akonadiserver: Starting up the Akonadi Server...
Cannot mix incompatible Qt library (5.15.5) with this library (5.15.7)
org.kde.pim.akonadicontrol: ProcessControl: Application "/usr/bin/akonadiserver" stopped unexpectedly ( "Fallo en el proceso" )
org.kde.pim.akonadicontrol: Application '/usr/bin/akonadiserver' crashed! 1 restarts left.
org.kde.pim.akonadiserver: Starting up the Akonadi Server...
Cannot mix incompatible Qt library (5.15.5) with this library (5.15.7)
org.kde.pim.akonadicontrol: ProcessControl: Application "/usr/bin/akonadiserver" stopped unexpectedly ( "Fallo en el proceso" )
org.kde.pim.akonadicontrol: Application '/usr/bin/akonadiserver' crashed! 0 restarts left.
org.kde.pim.akonadiserver: Starting up the Akonadi Server...
Cannot mix incompatible Qt library (5.15.5) with this library (5.15.7)
org.kde.pim.akonadicontrol: ProcessControl: Application "/usr/bin/akonadiserver" stopped unexpectedly ( "Fallo en el proceso" )
org.kde.pim.akonadicontrol: Application '/usr/bin/akonadiserver' crashed too often. Giving up!
```

### Steps to reproduce

1. Enter `xbps-install -Su && xbps-install akonadi5` into your favorite shell
2. Enter `akonadictl start`
3. Observe failure

**Comment by AlexKurisu** [comment]
Cannot reproduce, starts fine on my machine. `xuname`: `Void 6.0.15_1 x86_64 GenuineIntel uptodate FFFFF`

**Comment by oreo639** [comment]
> Cannot reproduce, starts fine on my machine

I can. That error usually just means it needs to be rebuilt which I can confirm fixes the issue.

**Comment by oreo639** [comment]
It has been rebuilt https://github.com/void-linux/void-packages/commit/119495d8d261f1a9ee0c363e1d0a3b8617f7e047
