### ISSUE TITLE
CI on own fork always fails because the branch is out of date albeit it isn't

### ISSUE THREAD

**Issue by steinex** [void-linux/void-packages#41376]
### Is this a new report?

Yes

### System Info

Void 6.1.1_1 x86_64 AuthenticAMD notuptodate hold rrrmDFFFFFFFFFFF

### Package(s) Affected

no specific package

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/steinex/void-packages/pull/230
https://github.com/steinex/void-packages/pull/227

### Expected behaviour

CI should run as usual.

### Actual behaviour

To check if my package builds for all archs, I always open a PR on my own branch first for QA. This stopped working with the problem:
```
Error: Your branch is too out of date. Please rebase on upstream and force-push.
Error: Process completed with exit code 1.
```

This does only happen on my own branch, if I push directly to void-packages everything is fine.

### Steps to reproduce

1. Prepare a PR
2. Push to own branch
3. See CI failing

**Comment by classabbyamp** [comment]
is the master branch on your fork up-to-date with the master branch of the main repo?

you could also try running parts of this script manually locally: https://github.com/void-linux/void-packages/blob/master/common/travis/changed_templates.sh

**Comment by steinex** [comment]
Yes, the master branch of my fork is up-to date. The script you mentions gives nothing besides

```
Changed packages:
```

So I assume that means there are no changed between my fork and master.

**Comment by classabbyamp** [comment]
hm not in a spot to debug this atm but it appears to be cloning your fork as the master branch and the pr branch so that shouldn't be an issue. maybe someone else can find the issue

**Comment by Chocimier** [comment]
changed_templates.sh uses FETCH_HEAD, which after full clone is set to random branch rather than master

**Comment by classabbyamp** [comment]
maybe switching that line to `git merge-base master "$tip"` would work?

**Comment by steinex** [comment]
> maybe switching that line to `git merge-base master "$tip"` would work?

I gave this a try. Unfortunately it didn't change anything.
