### ISSUE TITLE
4.14 Kernel have missing module

### ISSUE THREAD

**Issue by Axisar** [void-linux/void-packages#41454]
### Is this a new report?

Yes

### System Info

Void 4.14.295_1 x86_64 GenuineIntel notuptodate FF

### Package(s) Affected

linux4.14-4.14.295_1

### Expected behaviour

have to have no warning

### Actual behaviour

depmod: WARNING: could not open modules.builtin.modinfo at /var/tmp/dracut.ybtxYZ/initramfs/lib/modules/4.14.295_1: No such file or directory

### Steps to reproduce

Just install this kernel and boot using it.

**Comment by paper42** [comment]
Do you have linux4.14-headers installed?

**Comment by Axisar** [comment]
looks like i got this warning without linux4.14-headers installed
cant find the way to test it with installed headers

**Comment by paper42** [comment]
xbps-reconfigure -f linux4.14 I think, but this is expected if you don't have headers

**Comment by Axisar** [comment]
maybe i`m wrong. I got this in process of compiling dkms nvidia module which is have dependency of linux headers.

**Comment by paper42** [comment]
> maybe i`m wrong. I got this in process of compiling dkms nvidia module which is have dependency of linux headers.

linux-headers is a metapackage that points to the default kernel's headers - currently linux6.0-headers, if you are using a different kernel, you will need its headers.
