### ISSUE TITLE
plank doesen't show open applications

### ISSUE THREAD

**Issue by pianoforte33** [void-linux/void-packages#41468]
### Is this a new report?

Yes

### System Info

Void 6.0.15_1 x86_64 GenuineIntel uptodate FF

### Package(s) Affected

libwnck-43.0_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://www.reddit.com/r/voidlinux/comments/103hne0/plank_doesent_show_open_applications/
https://bbs.archlinux.org/viewtopic.php?id=280016

### Expected behaviour

when I open an application I expect its icon to appear on the dock

### Actual behaviour

when I open an application its icon does not appear in the dock
![Istantanea_2023-01-05_12-33-37](https://user-images.githubusercontent.com/79628894/210771053-6cdf6433-cd2e-48d8-bea1-95a76135d204.png)

### Steps to reproduce

1. I open an application
2. it is not shown in the dock

**Comment by karlk79** [comment]
Can confirm I get this error on a GLIBC and a MUSL Void Linux builds. Downgrading to 40.1 solves the issue.

[code]
plank
[CRITICAL 15:36:27.836563] [Wnck] wnck_set_client_type: changing the client type is not supported.
[WARN 15:36:27.961646] [Preferences:192] '/usr/share/plank/themes/Matte/dock.theme' is read-only!
[WARN 15:36:27.961879] [Preferences:378] Missing key 'TopRoundness' for group 'PlankTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.961918] [Preferences:378] Missing key 'BottomRoundness' for group 'PlankTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.961956] [Preferences:378] Missing key 'LineWidth' for group 'PlankTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962040] [Preferences:378] Missing key 'OuterStrokeColor' for group 'PlankTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962076] [Preferences:378] Missing key 'FillStartColor' for group 'PlankTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962112] [Preferences:378] Missing key 'FillEndColor' for group 'PlankTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962177] [Preferences:378] Missing key 'InnerStrokeColor' for group 'PlankTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962264] [Preferences:378] Missing key 'ItemPadding' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962299] [Preferences:378] Missing key 'IndicatorSize' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962349] [Preferences:378] Missing key 'UrgentBounceHeight' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962387] [Preferences:378] Missing key 'LaunchBounceHeight' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962423] [Preferences:378] Missing key 'FadeOpacity' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962457] [Preferences:378] Missing key 'ClickTime' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962491] [Preferences:378] Missing key 'UrgentBounceTime' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962527] [Preferences:378] Missing key 'LaunchBounceTime' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962561] [Preferences:378] Missing key 'ActiveTime' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962595] [Preferences:378] Missing key 'SlideTime' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962630] [Preferences:378] Missing key 'FadeTime' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962663] [Preferences:378] Missing key 'HideTime' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962697] [Preferences:378] Missing key 'GlowSize' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962731] [Preferences:378] Missing key 'GlowTime' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962765] [Preferences:378] Missing key 'GlowPulseTime' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962799] [Preferences:378] Missing key 'UrgentHueShift' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962833] [Preferences:378] Missing key 'ItemMoveTime' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:27.962885] [Preferences:378] Missing key 'BadgeColor' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Matte/dock.theme' - using default value
[WARN 15:36:28.107815] Unable to get org.ayatana.bamf matcher: Error calling StartServiceByName for org.ayatana.bamf: Process org.ayatana.bamf exited with status 139
[CRITICAL 15:36:28.118602] [GLib-GIO] g_dbus_proxy_set_default_timeout: assertion 'G_IS_DBUS_PROXY (proxy)' failed
[WARN 15:36:28.118635] [GLib-GObject] invalid (NULL) pointer instance
[CRITICAL 15:36:28.131745] [GLib-GObject] g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[WARN 15:36:28.131792] [GLib-GObject] invalid (NULL) pointer instance
[CRITICAL 15:36:28.146327] [GLib-GObject] g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[WARN 15:36:28.146389] [GLib-GObject] invalid (NULL) pointer instance
[CRITICAL 15:36:28.158034] [GLib-GObject] g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[WARN 15:36:28.158081] [GLib-GObject] invalid (NULL) pointer instance
[CRITICAL 15:36:28.166762] [GLib-GObject] g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[WARN 15:36:28.166781] [GLib-GObject] invalid (NULL) pointer instance
[CRITICAL 15:36:28.180091] [GLib-GObject] g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[WARN 15:36:28.180142] [GLib-GObject] invalid (NULL) pointer instance
[CRITICAL 15:36:28.190775] [GLib-GObject] g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
[WARN 15:36:28.212040] [TrashDockItem:35] GSettingsSchema 'org.gnome.nautilus.preferences' not found
[CRITICAL 15:36:28.226740] [GLib-GIO] g_dbus_proxy_call_sync_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed
[WARN 15:36:28.227641] Failed to get running applications: 
[CRITICAL 15:36:28.229504] [GLib] g_error_free: assertion 'error != NULL' failed
[WARN 15:36:28.247938] (Services/Matcher.c:299):plank_matcher_active_launchers: runtime check failed: (_tmp3_ != NULL)
[CRITICAL 15:36:28.257921] [GLib-GIO] g_dbus_proxy_call_sync_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed
[WARN 15:36:28.258466] Failed to register favorites: 
[CRITICAL 15:36:28.260412] [GLib] g_error_free: assertion 'error != NULL' failed
[WARN 15:36:30.683348] Creating surface took WAY TOO LONG (34ms), enabled downscaling for this cache!
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection. (t=0.821146) [GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
[2023-01-05T20:36:36Z ERROR glean_core::metrics::ping] Invalid reason code startup for ping background-update
[2023-01-05T20:36:36Z ERROR glean_core::metrics::ping] Invalid reason code startup for ping newtab
JavaScript warning: moz-extension://580bc946-c75f-4270-8e1c-39d667d1f9a0/background.js, line 0: Successfully compiled asm.js code (total compilation time 9ms)
[WARN 15:36:40.629137] Creating surface took WAY TOO LONG (30ms), enabled downscaling for this cache!
[WARN 15:36:40.730662] Creating surface took WAY TOO LONG (88ms), enabled downscaling for this cache!
[WARN 15:36:40.774258] Creating surface took WAY TOO LONG (31ms), enabled downscaling for this cache!
JavaScript error: resource://gre/modules/XULStore.jsm, line 58: Error: Can't find profile directory.

[/code]

**Comment by paper42** [comment]
This should be fixed now in libwnck 42.0_2
