### ISSUE TITLE
Lxpanel not working properly due to lxappearance-obconf

### ISSUE THREAD

**Issue by karlk79** [void-linux/void-packages#41479]
### Is this a new report?

Yes

### System Info

Void 6.1.1_1 x86_64-musl GenuineIntel uptodate hold rDDDDFFFFF

### Package(s) Affected

lxappearance-obconf-0.2.3_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

no

### Expected behaviour

lxpanel should be a full bar, it instead is half a bar.

### Actual behaviour

lxpanel is half a bar instead of a full bar.

### Steps to reproduce

1. install LXDE
2. boot LXDE
3. to fix the problem, lxappearance-obconf is uninstalled and obconf is installed.

**Comment by kruceter** [comment]
I can confirm this issue. The bar definitely spreads on half of the screen.

I am inclined to assume this problem is upstream-related.
