### ISSUE TITLE
Package request: Emscripten

### ISSUE THREAD

**Issue by DirtyVoid** [void-linux/void-packages#41614]
### Package name

Emscripten

### Package homepage

https://github.com/emscripten-core/emscripten

### Description

It compiles C and C++ code to wasm

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by tranzystorek-io** [comment]
According to https://github.com/emscripten-core/emscripten/blob/main/docs/packaging.md#dependencies emscripten requires a "top-of-tree" build of LLVM which seems like a no-go

**Comment by DirtyVoid** [comment]
It seems like a cool project. when you say it seems like a no-go, it makes me think you are uncertain if it is a go or no go but to you it appears to be a no go. Arch, Ubuntu and others already have it but I will close the issue. You can open it later when you can be certain if it is a go.

**Comment by tranzystorek-io** [comment]
@DirtyVoid I meant it's unlikely to be accepted (unless they start supporting stable), I don't think closing this request is necessary.

Especially with LLVM, we already have a fair bit of difficulty keeping the version fresh, so having to build potentially arbitrary revisions for each bump of emscripten doesn't seem sustainable.
