### ISSUE TITLE
"python3-charset-normalizer" package Installation Error

### ISSUE THREAD

**Issue by Rasquirrel** [void-linux/void-packages#41668]
### Error installing the _python3-charset-normalizer-2.1.11_

[*] Downloading packages
ERROR: [trans] failed to download `python3-charset-normalizer-2.1.1_1' signature from `https://repo-default.voidlinux.org/current/musl': Not Found
Transaction failed! see above for errors.

**Comment by classabbyamp** [comment]
do `xbps-install -S` and try again, that package was updated to 3.0.1 2 days ago

**Comment by Rasquirrel** [comment]
Thank you very much and sorry for the inconvenience. I always forget to update before installing something. Thank you very much for your patience with me!
