### ISSUE TITLE
Package request: gum

### ISSUE THREAD

**Issue by Kratacoa** [void-linux/void-packages#41688]
### Package name

gum

### Package homepage

https://github.com/charmbracelet/gum

### Description

Gives access to [Bubbles](https://github.com/charmbracelet/bubbles) and [Lip Gloss](https://github.com/charmbracelet/lipgloss) interface to improve upon shell scripts.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by tranzystorek-io** [comment]
https://github.com/tranzystorek-io/void-packages/blob/gum/srcpkgs/gum/template up for grabs

**Comment by tranzystorekk** [comment]
Can be closed: https://github.com/void-linux/void-packages/pull/42804
