### ISSUE TITLE
Virtualbox VMs freeze on shutdown and vboxservice doesn't run

### ISSUE THREAD

**Issue by ar-jan** [void-linux/void-packages#41681]
### Is this a new report?

Yes

### System Info

Void 6.1.4_1 x86_64 AuthenticAMD uptodate rFFFFFFFFFFFFFFFF

### Package(s) Affected

virtualbox-ose-7.0.4_1

### Expected behaviour

Virtualbox should start VMs *and* fully shut them down.

vboxservice should (presumably) be up / be able to be started.

### Actual behaviour

I can start Virtualbox, and start a VM. But, they do not shut down properly; the only way is to kill the process.

The vboxservice also does not function correctly:

    sudo sv status vboxservice
    down: vboxservice: 1s, normally up, want up
    sudo sv start vboxservice
    timeout: down: vboxservice: 1s, normally up, want up

The first time I tried (re)starting the vboxservice, I also noticed errors like these in dmesg (similar to #38967):

> [19333.120503] vboxdrv: 0000000000000000 VMMR0.r0
> [19333.201284] vboxdrv: 0000000000000000 VBoxDDR0.r0
> [20997.979622] vboxdrv: 0000000000000000 VMMR0.r0
> [20998.055403] vboxdrv: 0000000000000000 VBoxDDR0.r0
> [20998.154311] EMT-0[16682]: segfault at 0 ip 00007f68f5c4db7f sp 00007f68d24f8868 error 4 in libc.so.6[7f68f5b7d000+f7000] likely on CPU 3 (core 4, socket 0)

    sudo bash /etc/sv/vboxservice/run
    VBoxService: error: VbglR3Init failed with rc=VERR_FILE_NOT_FOUND

With strace I notice that `/dev/vboxguest` does not exist, and also `/etc/ld.so.preload`:

<summary>

`sudo strace -f -s128 -o virtualbox.txt VBoxService -fvvv`
<details>

> 7199  execve("/usr/bin/VBoxService", ["VBoxService", "-fvvv"], 0x7ffcb074bab8 /* 17 vars */) = 0
> 7199  brk(NULL)                         = 0x559cd64c7000
> 7199  access("/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
> 7199  openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
> 7199  newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=97467, ...}, AT_EMPTY_PATH) = 0
> 7199  mmap(NULL, 97467, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f270b687000
> 7199  close(3)                          = 0
> 7199  openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
> 7199  read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\243\2\0\0\0\0\0@\0\0\0\0\0\0\0\330\232\343\0\0\0\0\0\0\0\0\0@\08\0\16\0@\0G\0F\0\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0\20\3\0\0\0\0\0\0\20\3\0\0\0\0\0\0\10\0\0\0\0\0\0\0\3\0\0\0\4\0\0\0"..., 832) = 832
> 7199  pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0\20\3\0\0\0\0\0\0\20\3\0\0\0\0\0\0\10\0\0\0\0\0\0\0\3\0\0\0\4\0\0\0@<\32\0\0\0\0\0@<\32\0\0\0\0\0@<\32\0\0\0\0\0 \0\0\0\0\0\0\0 \0\0\0\0\0\0\0 \0\0\0\0\0\0\0\1\0\0\0\4\0\0\0\0\0\0\0\0\0\0\0"..., 784, 64) = 784
> 7199  newfstatat(3, "", {st_mode=S_IFREG|0755, st_size=14920856, ...}, AT_EMPTY_PATH) = 0
> 7199  mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f270b685000
> 7199  pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0\20\3\0\0\0\0\0\0\20\3\0\0\0\0\0\0\10\0\0\0\0\0\0\0\3\0\0\0\4\0\0\0@<\32\0\0\0\0\0@<\32\0\0\0\0\0@<\32\0\0\0\0\0 \0\0\0\0\0\0\0 \0\0\0\0\0\0\0 \0\0\0\0\0\0\0\1\0\0\0\4\0\0\0\0\0\0\0\0\0\0\0"..., 784, 64) = 784
> 7199  mmap(NULL, 2002320, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f270b49c000
> 7199  mmap(0x7f270b4c5000, 1396736, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x29000) = 0x7f270b4c5000
> 7199  mmap(0x7f270b61a000, 360448, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17e000) = 0x7f270b61a000
> 7199  mmap(0x7f270b672000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1d5000) = 0x7f270b672000
> 7199  mmap(0x7f270b678000, 52624, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f270b678000
> 7199  close(3)                          = 0
> 7199  mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f270b499000
> 7199  arch_prctl(ARCH_SET_FS, 0x7f270b499740) = 0
> 7199  set_tid_address(0x7f270b499a10)   = 7199
> 7199  set_robust_list(0x7f270b499a20, 24) = 0
> 7199  rseq(0x7f270b49a060, 0x20, 0, 0x53053053) = 0
> 7199  mprotect(0x7f270b672000, 16384, PROT_READ) = 0
> 7199  mprotect(0x559cd635e000, 16384, PROT_READ) = 0
> 7199  mprotect(0x7f270b6d1000, 8192, PROT_READ) = 0
> 7199  prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
> 7199  munmap(0x7f270b687000, 97467)     = 0
> 7199  getrandom("\x9c\xd8\x0b\xd4\x46\x5b\xf7\x96", 8, GRND_NONBLOCK) = 8
> 7199  brk(NULL)                         = 0x559cd64c7000
> 7199  brk(0x559cd64e8000)               = 0x559cd64e8000
> 7199  openat(AT_FDCWD, "/usr/lib64/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
> 7199  newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=3048928, ...}, AT_EMPTY_PATH) = 0
> 7199  mmap(NULL, 3048928, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f270b000000
> 7199  close(3)                          = 0
> 7199  getpid()                          = 7199
> 7199  rt_sigaction(SIGRT_29, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
> 7199  rt_sigaction(SIGRT_29, {sa_handler=0x559cd62dc490, sa_mask=~[RTMIN RT_1], sa_flags=SA_RESTORER, sa_restorer=0x7f270b4db240}, NULL, 8) = 0
> 7199  futex(0x7ffc0957cfac, FUTEX_WAIT_BITSET, 4042322160, NULL, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
> 7199  rt_sigprocmask(SIG_BLOCK, [ALRM], NULL, 8) = 0
> 7199  rt_sigaction(SIGRT_29, {sa_handler=0x559cd62dc490, sa_mask=~[RTMIN RT_1], sa_flags=SA_RESTORER, sa_restorer=0x7f270b4db240}, {sa_handler=0x559cd62dc490, sa_mask=~[KILL STOP RTMIN RT_1], sa_flags=SA_RESTORER, sa_restorer=0x7f270b4db240}, 8) = 0
> 7199  getpriority(PRIO_PROCESS, 0)      = 20
> 7199  rt_sigaction(SIGRT_1, {sa_handler=0x7f270b522ea0, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x7f270b4db240}, NULL, 8) = 0
> 7199  rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
> 7199  mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f270a7ff000
> 7199  mprotect(0x7f270a800000, 8388608, PROT_READ|PROT_WRITE) = 0
> 7199  rt_sigprocmask(SIG_BLOCK, ~[], [ALRM], 8) = 0
> 7199  clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7f270afff990, parent_tid=0x7f270afff990, exit_signal=0, stack=0x7f270a7ff000, stack_size=0x7fff80, tls=0x7f270afff6c0} => {parent_tid=[7200]}, 88) = 7200
> 7199  rt_sigprocmask(SIG_SETMASK, [ALRM], NULL, 8) = 0
> 7200  rseq(0x7f270affffe0, 0x20, 0, 0x53053053 <unfinished ...>
> 7199  futex(0x7f270afff990, FUTEX_WAIT_BITSET|FUTEX_CLOCK_REALTIME, 7200, NULL, FUTEX_BITSET_MATCH_ANY <unfinished ...>
> 7200  <... rseq resumed>)               = 0
> 7200  set_robust_list(0x7f270afff9a0, 24) = 0
> 7200  rt_sigprocmask(SIG_SETMASK, [ALRM], NULL, 8) = 0
> 7200  getpriority(PRIO_PROCESS, 0)      = 20
> 7200  sched_getparam(0, [0])            = 0
> 7200  sched_getscheduler(0)             = 0 (SCHED_OTHER)
> 7200  sched_getparam(7200, [0])         = 0
> 7200  sched_getscheduler(7200)          = 0 (SCHED_OTHER)
> 7200  getpriority(PRIO_PROCESS, 0)      = 20
> 7200  setpriority(PRIO_PROCESS, 0, -1)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, -2)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, -3)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, -4)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, -5)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, -6)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, -7)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, -8)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, -9)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, -10) = 0
> 7200  setpriority(PRIO_PROCESS, 0, -11) = 0
> 7200  setpriority(PRIO_PROCESS, 0, -12) = 0
> 7200  setpriority(PRIO_PROCESS, 0, -13) = 0
> 7200  setpriority(PRIO_PROCESS, 0, -14) = 0
> 7200  setpriority(PRIO_PROCESS, 0, -15) = 0
> 7200  setpriority(PRIO_PROCESS, 0, -16) = 0
> 7200  setpriority(PRIO_PROCESS, 0, -17) = 0
> 7200  setpriority(PRIO_PROCESS, 0, -18) = 0
> 7200  setpriority(PRIO_PROCESS, 0, -19) = 0
> 7200  setpriority(PRIO_PROCESS, 0, -20) = 0
> 7200  getpriority(PRIO_PROCESS, 0)      = 40
> 7200  setpriority(PRIO_PROCESS, 0, 0)   = 0
> 7200  getpriority(PRIO_PROCESS, 0)      = 20
> 7200  setpriority(PRIO_PROCESS, 0, 1)   = 0
> 7200  setpriority(PRIO_PROCESS, 0, 2)   = 0
> 7200  setpriority(PRIO_PROCESS, 0, 3)   = 0
> 7200  setpriority(PRIO_PROCESS, 0, 4)   = 0
> 7200  setpriority(PRIO_PROCESS, 0, 5)   = 0
> 7200  setpriority(PRIO_PROCESS, 0, 6)   = 0
> 7200  setpriority(PRIO_PROCESS, 0, 7)   = 0
> 7200  setpriority(PRIO_PROCESS, 0, 8)   = 0
> 7200  setpriority(PRIO_PROCESS, 0, 9)   = 0
> 7200  setpriority(PRIO_PROCESS, 0, 10)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, 11)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, 12)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, 13)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, 14)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, 15)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, 16)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, 17)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, 18)  = 0
> 7200  setpriority(PRIO_PROCESS, 0, 19)  = 0
> 7200  getpriority(PRIO_PROCESS, 0)      = 1
> 7200  setpriority(PRIO_PROCESS, 0, 0)   = 0
> 7200  getpriority(PRIO_PROCESS, 0)      = 20
> 7200  getpriority(PRIO_PROCESS, 0)      = 20
> 7200  setpriority(PRIO_PROCESS, 0, 19)  = 0
> 7200  mmap(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7f2709ffe000
> 7200  mprotect(0x7f2709fff000, 8388608, PROT_READ|PROT_WRITE) = 0
> 7200  mmap(NULL, 134217728, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x7f2701ffe000
> 7200  munmap(0x7f2701ffe000, 33562624)  = 0
> 7200  munmap(0x7f2708000000, 33546240)  = 0
> 7200  mprotect(0x7f2704000000, 135168, PROT_READ|PROT_WRITE) = 0
> 7200  rt_sigprocmask(SIG_BLOCK, ~[], [ALRM], 8) = 0
> 7200  clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7f270a7fe990, parent_tid=0x7f270a7fe990, exit_signal=0, stack=0x7f2709ffe000, stack_size=0x7fff80, tls=0x7f270a7fe6c0} <unfinished ...>
> 7201  rseq(0x7f270a7fefe0, 0x20, 0, 0x53053053 <unfinished ...>
> 7200  <... clone3 resumed> => {parent_tid=[7201]}, 88) = 7201
> 7201  <... rseq resumed>)               = 0
> 7200  rt_sigprocmask(SIG_SETMASK, [ALRM],  <unfinished ...>
> 7201  set_robust_list(0x7f270a7fe9a0, 24 <unfinished ...>
> 7200  <... rt_sigprocmask resumed>NULL, 8) = 0
> 7201  <... set_robust_list resumed>)    = 0
> 7200  futex(0x7f270a7fe990, FUTEX_WAIT_BITSET|FUTEX_CLOCK_REALTIME, 7201, NULL, FUTEX_BITSET_MATCH_ANY <unfinished ...>
> 7201  rt_sigprocmask(SIG_SETMASK, [ALRM], NULL, 8) = 0
> 7201  getpriority(PRIO_PROCESS, 0)      = 1
> 7201  setpriority(PRIO_PROCESS, 0, 20)  = 0
> 7201  setpriority(PRIO_PROCESS, 0, 0)   = 0
> 7201  rt_sigprocmask(SIG_BLOCK, ~[RT_1], NULL, 8) = 0
> 7201  madvise(0x7f2709ffe000, 8368128, MADV_DONTNEED) = 0
> 7201  exit(0)                           = ?
> 7201  +++ exited with 0 +++
> 7200  <... futex resumed>)              = 0
> 7200  setpriority(PRIO_PROCESS, 0, 0)   = 0
> 7200  sched_setscheduler(0, SCHED_OTHER, [0]) = 0
> 7200  sched_setparam(0, [0])            = 0
> 7200  sched_setscheduler(7200, SCHED_OTHER, [0]) = 0
> 7200  rt_sigprocmask(SIG_BLOCK, ~[RT_1], NULL, 8) = 0
> 7200  madvise(0x7f270a7ff000, 8368128, MADV_DONTNEED) = 0
> 7200  exit(0)                           = ?
> 7199  <... futex resumed>)              = 0
> 7200  +++ exited with 0 +++
> 7199  getpriority(PRIO_PROCESS, 0)      = 20
> 7199  readlink("/proc/self/exe", "/usr/bin/VBoxService", 4067) = 20
> 7199  openat(AT_FDCWD, "/usr/lib64/gconv/gconv-modules.cache", O_RDONLY) = -1 ENOENT (No such file or directory)
> 7199  openat(AT_FDCWD, "/usr/lib64/gconv/gconv-modules", O_RDONLY|O_CLOEXEC) = 3
> 7199  newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=3916, ...}, AT_EMPTY_PATH) = 0
> 7199  read(3, "# GNU libc iconv configuration.\n# Copyright (C) 1997-2022 Free Software Foundation, Inc.\n# This file is part of the GNU C Librar"..., 4096) = 3916
> 7199  read(3, "", 4096)                 = 0
> 7199  close(3)                          = 0
> 7199  openat(AT_FDCWD, "/usr/lib64/gconv/gconv-modules.d", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
> 7199  newfstatat(3, "", {st_mode=S_IFDIR|0755, st_size=4096, ...}, AT_EMPTY_PATH) = 0
> 7199  getdents64(3, 0x559cd64cb8e0 /* 3 entries */, 32768) = 96
> 7199  openat(AT_FDCWD, "/usr/lib64/gconv/gconv-modules.d/gconv-modules-extra.conf", O_RDONLY|O_CLOEXEC) = 4
> 7199  newfstatat(4, "", {st_mode=S_IFREG|0644, st_size=53974, ...}, AT_EMPTY_PATH) = 0
> 7199  read(4, "# GNU libc iconv configuration.\n# Copyright (C) 1997-2022 Free Software Foundation, Inc.\n# This file is part of the GNU C Librar"..., 4096) = 4096
> 7199  read(4, "B1002//\tJUS_I.B1.002//\nmodule\tJUS_I.B1.002//\t\tINTERNAL\t\tISO646\t\t2\nmodule\tINTERNAL\t\tJUS_I.B1.002//\t\tISO646\t\t2\n\nalias\tISO646-KR//\t"..., 4096) = 4096
> 7199  read(4, "59-5//\nalias\tISO_8859-5//\t\tISO-8859-5//\nalias\tISO8859-5//\t\tISO-8859-5//\nalias\tISO88595//\t\tISO-8859-5//\nalias\tCYRILLIC//\t\tISO-885"..., 4096) = 4096
> 7199  read(4, "59-16//\t\tINTERNAL\t\tISO8859-16\t1\nmodule\tINTERNAL\t\tISO-8859-16//\t\tISO8859-16\t1\n\n#\tfrom\t\t\tto\t\t\tmodule\t\tcost\nalias\tT.61//\t\t\tT.61-8BI"..., 4096) = 4096
> 7199  read(4, "-SE-A\t1\nmodule\tINTERNAL\t\tEBCDIC-FI-SE-A//\tEBCDIC-FI-SE-A\t1\n\n#\tfrom\t\t\tto\t\t\tmodule\t\tcost\nalias\tCSEBCDICFR//\t\tEBCDIC-FR//\nalias\tEBC"..., 4096) = 4096
> 7199  read(4, "97\t\t1\n\n#\tfrom\t\t\tto\t\t\tmodule\t\tcost\nalias\tCP420//\t\t\tIBM420//\nalias\tEBCDIC-CP-AR1//\t\tIBM420//\nalias\tCSIBM420//\t\tIBM420//\nalias\tOSF1"..., 4096) = 4096
> 7199  read(4, "1\n\n#\tfrom\t\t\tto\t\t\tmodule\t\tcost\nalias\tCP868//\t\t\tIBM868//\nalias\tCP-AR//\t\t\tIBM868//\nalias\tCSIBM868//\t\tIBM868//\nalias\tOSF10020364//\t\t"..., 4096) = 4096
> 7199  read(4, "6//\t\tIBM1046//\nalias\tCP1046//\t\tIBM1046//\nalias\t1046//\t\t\tIBM1046//\nmodule\tIBM1046//\t\tINTERNAL\t\tIBM1046\t\t1\nmodule\tINTERNAL\t\tIBM104"..., 4096) = 4096
> 7199  read(4, "\tto\t\t\tmodule\t\tcost\nalias\tRUSCII//\t\tCP1125//\nalias\tIBM848//\t\tCP1125//\nmodule\tCP1125//\t\tINTERNAL\t\tCP1125\t\t1\nmodule\tINTERNAL\t\tCP112"..., 4096) = 4096
> 7199  brk(0x559cd6509000)               = 0x559cd6509000
> 7199  read(4, "03//\nmodule\tCSN_369103//\t\tINTERNAL\t\tCSN_369103\t1\nmodule\tINTERNAL\t\tCSN_369103//\t\tCSN_369103\t1\n\n#\tfrom\t\t\tto\t\t\tmodule\t\tcost\nalias\tC"..., 4096) = 4096
> 7199  read(4, "\tmodule\t\tcost\nalias\tISO-IR-8-1//\t\tNATS-SEFI//\nalias\tCSNATSSEFI//\t\tNATS-SEFI//\nalias\tNATSSEFI//\t\tNATS-SEFI//\nmodule\tNATS-SEFI//\t\t"..., 4096) = 4096
> 7199  read(4, "IBM1156\t\t1\n\n#\tfrom\t\t\tto\t\t\tmodule\t\tcost\nalias\tIBM-1157//\t\tIBM1157//\nalias\tCP1157//\t\tIBM1157//\nalias\tCSIBM1157//\t\tIBM1157//\nmodule"..., 4096) = 4096
> 7199  read(4, "\t\tIBM1166//\nalias\tCP1166//\t\tIBM1166//\nalias\tCSIBM1166//\t\tIBM1166//\nmodule\tIBM1166//\t\tINTERNAL\t\tIBM1166\t\t1\nmodule\tINTERNAL\t\tIBM11"..., 4096) = 4096
> 7199  read(4, "alias\tROMAN9//\t\tHP-ROMAN9//\nalias\tR9//\t\t\tHP-ROMAN9//\nalias\tHPROMAN9//\t\tHP-ROMAN9//\nmodule\tHP-ROMAN9//\t\tINTERNAL\t\tHP-ROMAN9\t1\nmod"..., 4096) = 726
> 7199  read(4, "", 4096)                 = 0
> 7199  close(4)                          = 0
> 7199  getdents64(3, 0x559cd64cb8e0 /* 0 entries */, 32768) = 0
> 7199  close(3)                          = 0
> 7199  futex(0x7f270b67788c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
> 7199  rt_sigaction(SIGCHLD, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
> 7199  rt_sigaction(SIGCHLD, {sa_handler=0x559cd62e5eb0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_NOCLDSTOP, sa_restorer=0x7f270b4db240}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
> 7199  openat(AT_FDCWD, "/dev/null", O_RDONLY|O_CLOEXEC) = 3
> 7199  fcntl(3, F_GETFD)                 = 0x1 (flags FD_CLOEXEC)
> 7199  close(3)                          = 0
> 7199  openat(AT_FDCWD, "/dev/vboxguest", O_RDWR|O_CLOEXEC) = -1 ENOENT (No such file or directory)
> 7199  write(2, "VBoxService", 11)       = 11
> 7199  write(2, ": ", 2)                 = 2
> 7199  write(2, "error: ", 7)            = 7
> 7199  write(2, "VbglR3Init failed with rc=VERR_FILE_NOT_FOUND", 45) = 45
> 7199  write(2, "\n", 1)                 = 1
> 7199  exit_group(1)                     = ?
> 7199  +++ exited with 1 +++

</details>
</summary>

Also reported by two others here: https://old.reddit.com/r/voidlinux/comments/10a6nla/help_post_virtualbox_freezes/

### Steps to reproduce

1. xi virtualbox-ose virtualbox-ose-dkms virtualbox-ose-guest virtualbox-ose-guest-dkms
2. reboot
3. sudo ln -s /etc/sv/vboxservice /var/service/
4. Start VirtualBox
5. Start a VM
6. Shut down the VM. The VM window greys out and freezes. Only way to close it is to kill the process (resulting in "Aborted" status for the VM).

**Comment by nezos** [comment]
exactly the same issue here after the lastest update

**Comment by asifakonjee** [comment]
I was facing the same issue after the latest update! I downgraded to version 6.1.36 which is working completely fine.

**Comment by egorenar** [comment]
same problem on my machine

**Comment by egorenar** [comment]
i'm fed up with VirtualBox constantly not working, changed to libvirt and everything works :)

**Comment by sgn** [comment]
OK, the qt6 front-end is broken. Changing back to qt5

**Comment by ar-jan** [comment]
Thanks!
