### ISSUE TITLE
Where's clang-tidy?

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#41691]
### Is this a new report?

Yes

### System Info

Void 6.1.4_1 x86_64 GenuineIntel notuptodate hold rFF

### Package(s) Affected

clang

### Expected behaviour

I wasn't sure if should i create a bug report or package request. But I think it's a package issue.

Since clang-tidy is part of the clang, I am surprised that it's not part of the clang installation on the void. (See [arch package](https://archlinux.org/packages/extra/x86_64/clang/files/))

Even I tried `llvm12` and `clang-analyzer`, but they don't have clang-tidy executable.

### Actual behaviour

I need clang-tidy.

### Steps to reproduce

Just install clang and 

`xbps-query -f clang | grep clang-tidy`

Returns nothing, it means clang-tidy is not part of clang package.

**Comment by balejk** [comment]
`clang-tidy` is part of the `clang-tools-extra` package. You can use `xlocate` from the `xtools` package to see which package is a file part of.

**Comment by LinArcX** [comment]
@balejk It's weird since I used `xlocate` but nothing was found. (It's worth mentioning that `xlocate` is updated with `xlocate -S`)

Though if I try: `xlocate /usr/bin/clang-tidy`

It can find it. Thank you.
