### ISSUE TITLE
Package request: NUT Nutrition

### ISSUE THREAD

**Issue by avoidr** [void-linux/void-packages#417]
Nutrition software which uses the USDA database.

http://nut.sourceforge.net/

**Comment by Piraty** [comment]
I'll give it a shot.

**Comment by Piraty** [comment]
I gave up on it, was too uggly to package.

**Comment by Piraty** [comment]
User has to download the food database manually anyway, and since it's just a tcl script with good documentation how to setup, it's not hard to install manually...

**Comment by maxice8** [comment]
Alright
