### ISSUE TITLE
Request for removal: gosh

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/void-packages#41725]
The package `gosh` is orphaned, upstream dead (no update since 2016) and would conflict with the proper upstream binary name for Gauche which is required to write portable scripts in Gauche.

**Comment by classabbyamp** [comment]
I see no forks that have continued development, seems fine to me

> Popularity:
1 usage in 78 reports

**Comment by kruceter** [comment]
https://github.com/void-linux/void-packages/pull/41741.
