### ISSUE TITLE
ueberzug: dead upstream

### ISSUE THREAD

**Issue by icp1994** [void-linux/void-packages#41751]
https://github.com/seebye/ueberzug

Although the distfile is still available and the template packages fine. Relevant arch linux issue: https://bugs.archlinux.org/task/76674

**Comment by ErinVoid** [comment]
The code is available at https://codeberg.org/speedie/ueberzug

**Comment by paper42** [comment]
> The code is available at [codeberg.org/speedie/ueberzug](https://codeberg.org/speedie/ueberzug)

That's a fork from someone who doesn't know python and git. The original code is still up I don't see a reason why switch to another not maintained repository.

**Comment by ErinVoid** [comment]
Isn't the problem the code is not up on the original Github and the author has disowned it?   Yes, the new repo is simply a copy but it does contain the code.

**Comment by icp1994** [comment]
previous releases are still available under [tags](https://github.com/seebye/ueberzug/tags) - that's why it still builds from the template
