### ISSUE TITLE
kcm_touchpad: Error on receiving device list from KWin

### ISSUE THREAD

**Issue by someone13574** [void-linux/void-packages#41773]
### Is this a new report?

Yes

### System Info

Void 6.1.6_1 x86_64-musl GenuineIntel uptodate FF

### Package(s) Affected

plasma-desktop-5.26.3_2

### Expected behaviour

When using plasma system settings and going to "Input Devices/Touchpad" Kde shows touchpad settings

### Actual behaviour

When at the above location Kde shows "No touchpad found" and the console output shows:
`kcm_touchpad: Using KWin+Wayland backend`
`kcm_touchpad: Error on receiving device list from KWin.`

### Steps to reproduce

1. Install Kde for Wayland on a laptop with a touchpad
2. Run `systemsettings5` from the command-line
3. Traverse to `Input Devices / Touchpad`
4. Observe error in command-line output and 'No touchpad found' in place of settings

**Comment by BenjieFiftysix** [comment]
I'm having this issue on a fully updated system. Is there a way to resolve it? I'm also not able to use global shortcuts such as alt+tab and volume keys.

**Comment by someone13574** [comment]
I didn't find a solution and only closed it because I switched to gnome and didn't have a system setup to text any possible solutions. I'll reopen since there are others interested.

**Comment by Johnnynator** [comment]
Are you both on x86_64-musl  ?

**Comment by BenjieFiftysix** [comment]
Oh wow awesome, thanks for fixing that so quickly. I can confirm that both my issues are resolved.
