### ISSUE TITLE
Package Request: Whipper

### ISSUE THREAD

**Issue by UK82** [void-linux/void-packages#4182]
Actively maintained fork of Morituri Audio CD Ripper for providing secure/verifiable extraction via CLI:

https://github.com/whipper-team/whipper

Thanks for considering :-)

**Comment by Johnnynator** [comment]
We currently don't want to add any new python2 only packages. So tit will not be included in the repo until https://github.com/whipper-team/whipper/issues/78  is resolved.

**Comment by st3r4g** [comment]
`whipper` was ported to python3 in https://github.com/whipper-team/whipper/releases/tag/v0.9.0, so this can be reopened.
