### ISSUE TITLE
 Wine 7.22 uses bundled OpenLDAP

### ISSUE THREAD

**Issue by amak79** [void-linux/void-packages#41853]
Just like https://github.com/void-linux/void-packages/issues/34201, Wine 7.22 has bundled OpenLDAP to support PE builds.
- https://www.winehq.org/announce/7.22
- https://gitlab.winehq.org/wine/wine/-/commit/d08d6f51040e18982612658a885af659fbfa4afe

Wine 7.21 has also removed OpenAL:
- https://www.winehq.org/announce/7.21
- https://gitlab.winehq.org/wine/wine/-/commit/45eca854c4fab7e864deebf9a51c74147884ebc8

`xbps` removes both openal and openldap after upgrading from Wine  7.19 to 7.22:
```
# xbps-remove -o

Name            Action    Version           New version            Download size
libldap         remove    2.4.58_1          -                      - 
libldap-32bit   remove    2.4.58_1          -                      - 
libopenal       remove    1.22.2_1          -                      - 
libopenal-32bit remove    1.22.2_1          -                      - 
libsasl         remove    2.1.27_2          -                      - 
libsasl-32bit   remove    2.1.27_2          -                      - 
libsndio        remove    1.9.0_1           -                      - 
libsndio-32bit  remove    1.9.0_1           -                      -
```

**Comment by paper42** [comment]
@Hoshpak

**Comment by Hoshpak** [comment]
What exactly is the issue here? I understand that `libldap-devel` and `libopenal-devel` are now unneccessary in `makedepends` and should be removed from the template to clean it up. The removal of the packages above does seem correct to me since wine doesn't link against them any more. Does the removal cause issues and should thus be compensated by adding one of the libraries manually as a runtime dependency?

**Comment by amak79** [comment]
> What exactly is the issue here? I understand that `libldap-devel` and `libopenal-devel` are now unneccessary in `makedepends` and should be removed from the template to clean it up. 

Sorry I should have elaborated. This issue just serves as a note to remove the deps from the template. I haven't observed any problems with their removal.
