### ISSUE TITLE
rbw shell completion doesn't work

### ISSUE THREAD

**Issue by timsofteng** [void-linux/void-packages#41861]
### Is this a new report?

Yes

### System Info

Void 6.0.15_1 x86_64 GenuineIntel notuptodate hold rDFFFF

### Package(s) Affected

rbw-1.4.3_1

### Expected behaviour

Shell completion should work

### Actual behaviour

Shell competion doesn't work

### Steps to reproduce

Just try to invoke shell completion after `rbw` command

Here is the link on implementation of this in repo:
https://github.com/doy/rbw/issues/18#issuecomment-821937293

**Comment by tranzystorek-io** [comment]
At least the zsh completion works fine for me, is your shell configured correctly?

**Comment by timsofteng** [comment]
Sorry, my bad. Looks like it was some of shell caching issue. Regular completion after rtw works now fine for me.

Do you know is it possible to get completion for passwords items after `rbw get <press tab>`? If rbw doesn't provide it then issue is totally solved.
