### ISSUE TITLE
Package request: linux-lts from 85 to 90 please

### ISSUE THREAD

**Issue by bcookatpcsd** [void-linux/void-packages#41882]
### Package name

linux-lts

### Package homepage

https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.90

### Description

Wondering if there is something that needs to be setup to track the lts branch? 

@classabbyamp seems to have updated it to 5.15

I can't tell from the commits but Dec 22 seems to be when 5.15.85 came out (5.15.85 is what is available as of 1/26/23)

![image](https://user-images.githubusercontent.com/55087301/214848128-11f06eef-d358-4a72-a02b-4bae34e8255a.png)

The update script does not seem to list linux-lts on it:
https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment]
The PR template explicitly says not to open update requests, we know about this. If you have any issues with the current version, please mention them and mention that an update would solve it, but just plain update requests are not really useful.

linux-lts is an empty metapackage that depends on linux5.15 which is the package that should be updated, not linux-lts
