### ISSUE TITLE
acpid clogs syslog with arrow key events

### ISSUE THREAD

**Issue by kruceter** [void-linux/void-packages#41994]
### Is this a new report?

Yes

### System Info

Void 5.15.85_1 x86_64-musl GenuineIntel uptodate hold rFFFFFFFFFFFF

### Package(s) Affected

acpid-2.0.34_1

### Expected behaviour

The package is not (?) supposed to clog syslog with undefined arrow keys.

### Actual behaviour

`acpid` uses `/etc/acpid/handler.sh` to flood syslog with `ACPI group/action undefined: button/<arrow_key> / <DIRECTION>`.

### Steps to reproduce

Use acpid as a runit service.

Reproduce the behavior with `extrace` in case you do not have any system loggers installed.

Now, abuse button keys and see something like this below:

```
19226 /bin/sh /etc/acpi/handler.sh button/down DOWN 00000080 00000000 K
19227 cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq
19228 cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
19229 logger 'ACPI group/action undefined: button/down / DOWN'
```

**Comment by gtryujb** [comment]
[Upstream's diff](https://sourceforge.net/p/acpid2/code/ci/b336c96e32c959ed3df15eaf5669f47ea589d977/tree/input_layer.c?diff=754b49aaa3a936a61a1415747e509f1135a5ce27).
