### ISSUE TITLE
Package request: ncurses-libtinfo-libs-32bit

### ISSUE THREAD

**Issue by rubin55** [void-linux/void-packages#42007]
### Package name

ncurses-libtinfo

### Package homepage

https://invisible-island.net/ncurses/announce.html

### Description

Ncurses is currently available for Void, and also has a 32bit compatibility package. However, this package misses a libtinfo-libs counterpart  like the x86_64 package has.

I would like to run some older, binary software that has all dependencies fulfilled, except a 32bit version of `libtinfo.so.6` 

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by misuchiru03** [comment]
I think we can close this as it's available since May 2020 in #21409

**Comment by classabbyamp** [comment]
would you mind testing #46395? create an i686 masterdir (`xbps-src -m masterdir-i686 binary-bootstrap i686`) and it should build the multilib packages (`xbps-src -m masterdir-i686 pkg ncurses`)
