### ISSUE TITLE
Update request: xtools

### ISSUE THREAD

**Issue by fanyx** [void-linux/void-packages#42027]
### Package name

xtools

### Package homepage

https://git.vuxu.org/xtools/

### Description

The package version of xtools in the current void-repos is 10 months old.
Leah hasn't tagged their code for a clean version release but the code has developed far past the latest release.

Would be great to get the repo package back on the latest codebase.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

No

**Comment by paper42** [comment]
this isn't really a request for this repository, the package will be updated when a new version is tagged
