### ISSUE TITLE
Wayland does not work with GDM and NVIDIA drivers.

### ISSUE THREAD

**Issue by LMFuture-Me** [void-linux/void-packages#42033]
### Is this a new report?

Yes

### System Info

Void 6.1.8_1 x86_64 AuthenticAMD uptodate FFFF

### Package(s) Affected

nvidia-525.85.05_1, gdm-43.0_1

### Expected behaviour

There are options in the lower right corner of GDM, and Wayland can be selected.

### Actual behaviour

There are no options in the lower right corner of GDM.

### Steps to reproduce

1. Install void linux.
2. install GNOME and nvidia driver
3. just like this

**Comment by paper42** [comment]
That's expected, GDM runs with the xorg backend on nvidia graphics cards in some unsupported cases and then doesn't offer wayland sessions. https://gitlab.gnome.org/GNOME/gdm/-/blob/main/data/61-gdm.rules.in
