### ISSUE TITLE
Package request: lswt

### ISSUE THREAD

**Issue by linkert** [void-linux/void-packages#42057]
### Package name

lswt

### Package homepage

https://git.sr.ht/~leon_plickat/lswt

### Description

*"lswt - list Wayland toplevels"* - basically get app_id, class and such. Leon is very involved in the development of the river compositor. ```lswt``` is one application that could replace some of the functionality that ```swaymsg -t get_tree``` offers on the sway-side of things. Personally I'd like to get it through the repos so that I can write a simple *launch or focus* script for my river setup :)

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by icp1994** [comment]
I have been using lswt from my local template - didn't submit it since there was a pending PR which didn't get merged eventually. Since you are interested maybe you can resubmit https://github.com/void-linux/void-packages/pull/34969 without the patch?

**Comment by linkert** [comment]
> I have been using lswt from my local template - didn't submit it since there was a pending PR which didn't get merged eventually. Since you are interested maybe you can resubmit #34969 without the patch?

Well, yeah I should if I could wrap my wrinkle brain around all these tools and concepts

**Comment by linkert** [comment]
> I have been using lswt from my local template - didn't submit it since there was a pending PR which didn't get merged eventually. Since you are interested maybe you can resubmit #34969 without the patch?

I would if I could wrap my wrinkle brain around all the different concepts required to figure out and complete such a process.

**Comment by icp1994** [comment]
Fine, I'll submit mine for now.
