### ISSUE TITLE
Possibly missing shared object file in wireplumber package

### ISSUE THREAD

**Issue by Adailoe** [void-linux/void-packages#42056]
### Is this a new report?

Yes

### System Info

Void 6.1.8_1 x86_64 AuthenticAMD uptodate FFFFFFF

### Package(s) Affected

wireplumber-0.4.13_2

### Expected behaviour

The package might be missing the libwireplumber-module-logind.so - file. 
It is present in the Arch Linux version but not in Void. 

### Actual behaviour

Wireplumber is complaining about that missing file when trying to connect to pipewire and fails to connect.

```
m-lua-scripting ../modules/module-lua-scripting/api/config.c:80:load_components: Failed to open module /usr/lib64/wireplumber-0.4/libwireplumber-module-logind: /usr/lib64/wireplumber-0.4/libwireplumber -module-logind.so: cannot open shared object file: No such file or directory.
Failed to connect to PipeWire
```

The pipewire media-session is not active. ( difference to issue https://github.com/void-linux/void-packages/issues/37683 )

### Steps to reproduce

1. Install wireplumber
2. Change the pipewire-configuration according to https://github.com/void-linux/void-docs/pull/738/files
3. Reboot
4. Open terminal and execute `$ wireplumber`

**Comment by paper42** [comment]
This is expected, wireplumber is not built with logind support

**Comment by Adailoe** [comment]
So wireplumber should be able to connect to pipewire regardless of the complains about that missing file?

**Comment by paper42** [comment]
Yes, that is just a warning

**Comment by oreo639** [comment]
The logind plugin is only needed for multiuser bluetooth support.
