### ISSUE TITLE
Package request: upgrade cinnamon to 5.6.7

### ISSUE THREAD

**Issue by Mas4hmad** [void-linux/void-packages#42066]
### Package name

cinnamon-desktop

### Package homepage

https://github.com/linuxmint/cinnamon

### Description

Cinnamon is a Linux desktop that provides advanced innovative features and a traditional user experience.

The desktop layout is similar to Gnome 2 with underlying technology forked from Gnome Shell. Cinnamon makes users feel at home with an easy-to-use and comfortable desktop experience.

there are packages of cinnamon for void linux. but in better experience, it'll be happy if cinnamon can be updated/upgraded

thanks before

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment]
> Don't request an update of a package, [We have a script for that](https://alpha.de.repo.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.
