### ISSUE TITLE
oracle-jre cannot update

### ISSUE THREAD

**Issue by samschmalz** [void-linux/void-packages#4209]
### System

* xuname:  
  *Void 4.18.16_1 x86_64 AuthenticAMD notuptodate rrrmFFFF*
* package:  
  *oracle-jre 8u192_1, replacing 8u181_1*

### Expected behavior
When running `sudo xbps-install -Syu`, packages including oracle-jre should update
### Actual behavior
oracle-jre produces several errors regarding being unable to remove a directory or upack a file.
### Steps to reproduce the behavior
run `sudo xbps-install -Syu`

Relevant information from command:
```
[*] Running transaction tasks
oracle-jre-8u181_1: updating to 8u192_1 ...
oracle-jre-8u181_1: unregistered 'java' alternatives group
Switched 'java' alternatives group to 'openjdk-jre'
Creating 'java' alternatives group symlink: /usr/bin/java -> /usr/lib/jvm/openjdk/jre/bin/java
Creating 'java' alternatives group symlink: /usr/bin/jjs -> /usr/lib/jvm/openjdk/jre/bin/jjs
Creating 'java' alternatives group symlink: /usr/bin/keytool -> /usr/lib/jvm/openjdk/jre/bin/keytool
Creating 'java' alternatives group symlink: /usr/bin/mkcacerts -> /usr/lib/jvm/openjdk/jre/bin/mkcacerts
Creating 'java' alternatives group symlink: /usr/bin/orbd -> /usr/lib/jvm/openjdk/jre/bin/orbd
Creating 'java' alternatives group symlink: /usr/bin/pack200 -> /usr/lib/jvm/openjdk/jre/bin/pack200
Creating 'java' alternatives group symlink: /usr/bin/policytool -> /usr/lib/jvm/openjdk/jre/bin/policytool
Creating 'java' alternatives group symlink: /usr/bin/rmid -> /usr/lib/jvm/openjdk/jre/bin/rmid
Creating 'java' alternatives group symlink: /usr/bin/rmiregistry -> /usr/lib/jvm/openjdk/jre/bin/rmiregistry
Creating 'java' alternatives group symlink: /usr/bin/servertool -> /usr/lib/jvm/openjdk/jre/bin/servertool
Creating 'java' alternatives group symlink: /usr/bin/tnameserv -> /usr/lib/jvm/openjdk/jre/bin/tnameserv
Creating 'java' alternatives group symlink: /usr/bin/unpack200 -> /usr/lib/jvm/openjdk/jre/bin/unpack200
oracle-jre-8u181_1: unregistered 'java-plugin' alternatives group
Switched 'java-plugin' alternatives group to 'oracle-jre'
Creating 'java-plugin' alternatives group symlink: /usr/lib/mozilla/plugins/libnpjp2.so -> /usr/lib/jvm/oracle-jre/lib/amd64/libnpjp2.so
oracle-jre-8u192_1: unpacking ...
```
Terminal output stops here, and I return to a prompt.  I cannot remove oracle-jre because of other errors that would be resolved by other packages that need to update as well.  I can provide full output upon request.

**Comment by pr310d3r** [comment]
I get this error when I run 

> sudo xbps-install -Su

`[*] Running transaction tasks
oracle-jre-8u181_1: updating to 8u192_1 ...
/tmp/.xbps-script-FoeTL2: 45: .: Can't open usr/lib/jvm/oracle-jre-vars.sh
ERROR: oracle-jre-8u192_1: [remove] REMOVE script failed to execute pre ACTION: Key has expired
ERROR: oracle-jre-8u192_1: failed to remove package: Key has expired
ERROR: oracle-jre-8u192_1: [trans] failed to update package `Key has expired'
`

**Comment by PB-repo** [comment]
ditto

**Comment by pullmoll** [comment]
After deinstalling `oracle-jre` with `sudo xbps-remove -f oracle-jre` you probably need to remove leftovers from previous version in `/usr/lib/jvm/oracle-jre` with `sudo rm -rf /usr/lib/jvm/oracle-jre`.
After cleaning you should be able to `sudo xbps-install -S oracle-jre`.

**Comment by PB-repo** [comment]
sudo xbps-remove -f oracle-jre
sudo rm -rf /usr/lib/jvm/oracle-jre
don't help, the same error, but
sudo rm -f /usr/lib/jvm/oracle-jre-vars.sh
help me and I could install oracle-jre.

**Comment by abenson** [comment]
oracle-jre has been deprecated in favor of openjdk.
