### ISSUE TITLE
fuse2fs not included in e2fsprogs

### ISSUE THREAD

**Issue by danjenson** [void-linux/void-packages#42150]
### Is this a new report?

Yes

### System Info

Void 6.1.9_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFFF

### Package(s) Affected

e2fsprogs-1.46.5_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

It is included in other distros but not Void's: https://github.com/tytso/e2fsprogs/blob/master/misc/fuse2fs.c

### Expected behaviour

It would include fuse2fs, which is required for apptainer.

### Actual behaviour

Not included.

### Steps to reproduce

1. Install
2. `which fuse2fs` -> not present

**Comment by dkwo** [comment]
Adding `fuse-devel` to `makedepends` fixes it for me. Possibly we should add it as a subpackage. I can do that as well as update this pkg @Gottox
