### ISSUE TITLE
Package request: libgcr-3-dev

### ISSUE THREAD

**Issue by sistematico** [void-linux/void-packages#42167]
### Package name

libgcr-3-dev

### Package homepage

https://wiki.gnome.org/Projects/GnomeKeyring

### Description

[libgcr-3-dev](https://packages.debian.org/sid/libgcr-3-dev) is dependency of [surf](https://surf.suckless.org/)[1].

[1] - https://askubuntu.com/a/1141481

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

Yes

**Comment by paper42** [comment]
It's called gcr-devel on Void.

**Comment by sistematico** [comment]
> It's called gcr-devel on Void.

Thank you very, sorry for phony issue.
