### ISSUE TITLE
Package request: agave

### ISSUE THREAD

**Issue by sistematico** [void-linux/void-packages#42190]
### Package name

agave

### Package homepage

https://web.archive.org/web/20170327063642/http://home.gna.org/colorscheme/

### Description

GTK color picker.

Sources: http://ftp.debian.org/debian/pool/main/a/agave/agave_0.4.7.orig.tar.gz
Reference: https://aur.archlinux.org/packages/agave

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by oreo639** [comment]
This is the official github repo:
https://github.com/jonner/agave2/

It is unmaintained since 2008 and new gtk2 packages are not being accepted.
