### ISSUE TITLE
KDE Plasma 5.26.5 or 5.27

### ISSUE THREAD

**Issue by gilbertoferreira** [void-linux/void-packages#42218]
### Package name

plasma-desktop

### Package homepage

www.kde.org

### Description

Any change do update plasma-desktop to newly versions??

Thanks

### Does the requested package meet the package requirements?

System

### Is the requested package released?

No

**Comment by classabbyamp** [comment]
> Don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt).

it will happen in due time, it's up to the maintainer
