### ISSUE TITLE
Package request: circadian

### ISSUE THREAD

**Issue by onli** [void-linux/void-packages#42287]
### Package name

circadian

### Package homepage

https://github.com/mrmekon/circadian

### Description

Circadian is a background daemon/service for triggering suspend/sleep/hibernate automatically when a computer is idle.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/circadian/template
