### ISSUE TITLE
Package request: VSCodium

### ISSUE THREAD

**Issue by carbongreat13** [void-linux/void-packages#42328]
### Package name

VSCodium

### Package homepage

https://vscodium.com/

### Description

VSCodium is a more privacy-friendly fork of VSCode.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/issues/10582#issuecomment-763989684

Our VSCode has all telemetry removed.
