### ISSUE TITLE
[Discussion] Should the pinebookpro-kernel template be retired, or expanded?

### ISSUE THREAD

**Issue by atweiden** [void-linux/void-packages#42333]
@CameronNemo and I have been chatting about [pinebookpro-kernel](https://github.com/void-linux/void-packages/pull/41062#issuecomment-1434123591). In summary:

- An argument could be made to retire the pinebookpro-kernel template
- An argument could be made to expand the pinebookpro-kernel template to include several of the more modern Pinebook Pro patches designed by Manjaro (the semi-official distribution of the Pinebook Pro)
- The latest Manjaro patches for Pinebook Pro have been ported to Arch Linux ARM at [SvenKiljan/archlinuxarm-pbp-packages](https://github.com/SvenKiljan/archlinuxarm-pbp-packages)

I’m interested in knowing what the Void community thinks of either option.

**Comment by paper42** [comment]
I think the pinebookpro-kernel maintainer (who is the most qualified to answer this) already explained it in this thread, am I wrong? https://github.com/void-linux/void-packages/pull/41062

**Comment by sgn** [comment]
If Debian, postmarketOS can make generic kernel works on PBP, I think we should drop pinebookpro-kernel. Just as same as other modded kernel.
