### ISSUE TITLE
Package request: gtk3-classic

### ISSUE THREAD

**Issue by DeadEnthusiasm** [void-linux/void-packages#42398]
### Package name

gtk3-classic

### Package homepage

https://github.com/lah7/gtk3-classic

### Description

Patches to restore GTK3's look & feel reminiscent to earlier versions. With many enhancements such as disabled CSD headers, traditional dialog boxes and file browser improvements.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by paper42** [comment]
This would have to replace the current gtk+3 package on systems (you can only have gtk+3 or this patched version) and we don't accept custom forks like this.
