### ISSUE TITLE
git-cola terminated by signal SIGABRT

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#42429]
### Is this a new report?

Yes

### System Info

Void 5.15.94_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFFFF

### Package(s) Affected

git-cola-4.1.0_2

### Expected behaviour

git-cola runs normally.

### Actual behaviour

```
➜  ~ git-cola
Cannot mix incompatible Qt library (5.15.2) with this library (5.15.7)
fish: Job 1, 'git-cola' terminated by signal SIGABRT (Abort)
```

I think it needs to be rebuilt.

### Steps to reproduce

type in the terminal emulator.

```
git-cola
```

**Comment by sgn** [comment]
`python3-PyQt5` needs to be rebuilt.
