### ISSUE TITLE
teams-bin :  distfiles are missing from Microsoft repos

### ISSUE THREAD

**Issue by unrealjo** [void-linux/void-packages#42449]
### Is this a new report?

Yes

### System Info

Void x86_64-libc

### Package(s) Affected

teams-bin

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Issue is reported here : 
- [ms-teams for linux not available](https://learn.microsoft.com/en-us/answers/questions/1182762/ms-teams-for-linux-not-available)

### Expected behaviour

During build, the team-bin template script will pull out the Debian package as a distfile.

### Actual behaviour

The Debian packages are messing from Microsoft repository

### Steps to reproduce

- Download distfiles

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/issues/42403
