### ISSUE TITLE
Package request: LLVM15

### ISSUE THREAD

**Issue by Nicop06** [void-linux/void-packages#42475]
### Package name

llvm15

### Package homepage

https://www.llvm.org

### Description

LLVM>=15 is needed for RNDA 3 graphics card to work.

I have a change that upgrade it, I just need to clean it up.

### Does the requested package meet the package requirements?

System, Compiled, Required

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
it's in progress (#40821) and please don't request updates
