### ISSUE TITLE
gummiboot broken with linux-mainline

### ISSUE THREAD

**Issue by junkmanner** [void-linux/void-packages#42566]
### Is this a new report?

Yes

### System Info

Void 6.1.14_1 x86_64-musl AuthenticAMD uptodate rFF

### Package(s) Affected

gummiboot-48.1_8, linux6.2-6.2.0_1

### Expected behaviour

The system is supposed to boot up normally.

### Actual behaviour

When trying to boot the system, my computer gets stuck in an infinite loop of the fans spinning up and down. I did a bit of reading around and testing, and if I build the kernel with EFI_HANDOVER_PROTOCOL=y, the computer boots without issue, which leads me to believe the the issue is that gummiboot uses the deprecated efi handover protocol, and therefore cannot boot on linux-mainline where EFI_HANDOVER_PROTOCOL is not set.

### Steps to reproduce

1. Install gummiboot as bootloader
2. Install linux-mainline
3. reboot

**Comment by paper42** [comment]
According to https://gitlab.alpinelinux.org/alpine/aports/-/issues/14679, we can either enable CONFIG_EFI_HANDOVER_PROTOCOL and this will keep working for a while or just remove gummiboot which didn't have a release since it was merged to systemd in 2015.
I would be in favor of removing gummiboot.

**Comment by zdykstra** [comment]
I'd like to see gummiboot limp along for a while, too, if there's nothing else to fill that specific package gap.

**Comment by paper42** [comment]
It might be possible to build systemd-boot from the systemd sources as a separate binary.

**Comment by sonnysighedup** [comment]
One stop-gap measure - which might not work for the OP, but will work for those who just need gummiboot for efi stub - would be to break out the gummiboot-efistub sub-package into its own entity and have it track systemd's version of linuxx64.efi.stub a la [this Arch AUR package](https://aur.archlinux.org/packages/systemd-stub-x64).

I just tried it against the Void repo's 6.2 kernel, and was able to successfully boot a self-signed UEFI kernel image, something which I could only do previously by compiling linux6.2 from xbps-src with CONFIG_EFI_HANDOVER_PROTOCOL=y.

**Comment by junkmanner** [comment]
> One stop-gap measure - which might not work for the OP, but will work for those who just need gummiboot for efi stub - would be to break out the gummiboot-efistub sub-package into its own entity and have it track systemd's version of linuxx64.efi.stub a la [this Arch AUR package](https://aur.archlinux.org/packages/systemd-stub-x64).

While not a solution, this would certainly fill the hole for me. I have no particular affinity for gummiboot as a bootloader. I was simply using it, as it already provided the efistub I was using for UKI.

However, doesn't void require packages to be compiled, meaning this wouldn't be possible to be redistributed through the official mirrors? Gentoo seems to provide systemd-boot as an option for openrc under their [sys-apps/systemd-utils](https://packages.gentoo.org/packages/sys-apps/systemd-utils). Perhaps looking at what they do is an option?
