### ISSUE TITLE
[question] run_depends vs shlib-requires

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#42575]
Why do some packages (e.g. `wlroots` `libinput`) both `run_depends` on `eudev-libudev` and `shlib-requires` `libudev.so.1`?
is there a reason they run-depend explicitly, rather than cleanly via the .so?
if they only did the latter, then anything providing `libudev.so.1` could replace eudev-libudev, as in #42488

**Comment by classabbyamp** [comment]
`common/shlibs` is used to track what shilbs come from which packages and versions. that's used by xbps-src to generate a list of `run_depends` that combines what's in `depends=` with what shlibs are detected. `run_depends` within xbps is used to build the transaction, and `shilb-requires` and `shlib-provides` are used at a later time to check things. depending "cleanly via the .so" doesn't exist

**Comment by dkwo** [comment]
I see, thanks for explaining that. Is there any infra for a package like `libudev-zero` to be installed as a replacement of `eudev` and `eudev-libudev`, besides adding them to `ignorepkg`?

**Comment by dkwo** [comment]
```
# PLEASE NOTE: when multiple packages provide the same SONAME, the first
# one (order top->bottom) is preferred over the next ones.
```
I guess this just means that `xbps-src` picks the top one when generating the `run_depends`.
