### ISSUE TITLE
how to bootstrap gdc?

### ISSUE THREAD

**Issue by rn-gh** [void-linux/void-packages#42673]
I wanted to submit a patch for [`srcpkgs/gcc`](https://github.com/void-linux/void-packages/tree/master/srcpkgs/gcc) to enable GDC, the D language compiler (`--enable-languages=...,d`), and hit a wall (https://gcc.gnu.org/install/prerequisites.html):

> In order to build GDC, the D compiler, you need a working GDC compiler (GCC version 9.4 or later) and D runtime library, ‘libphobos’, as the D front end is written in D.
> 
> Versions of GDC prior to 12 can be built with an ISO C++11 compiler, which can then be installed and used to bootstrap newer versions of the D front end.

How can I make this work? Package (temporarily) gcc-11 + gcc-d-11 and build gcc + gcc-d with it?

**Comment by Chocimier** [comment]
This can work. Our java is built using every release from gcc-buildable 6 to 17.

**Comment by sgn** [comment]
I have a working gdc bootstrap from gcc-11 and ldc built by gdc locally. ldc could be cross-compiled with this gdc, but musl built is still a mess.
