### ISSUE TITLE
[ask] version contain dashes

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#42699]
https://github.com/void-linux/void-packages/blob/master/Manual.md#mandatory-variables

> `version` A string with the package version. Must not contain dashes or underscore and at least one digit is required. Shell's variable substitution usage is not allowed.

i have a problem changing the version of package `R-cran-colorspace` which contains dashes. how to fix it?

https://cran.r-project.org/src/contrib/colorspace_2.1-0.tar.gz

`version=2.1-0`

output result:
```
=> ERROR: version contains invalid character: -
```

**Comment by classabbyamp** [comment]
change it to some other character that isn't _ or -, like + or r, then use parameter expansion for the distfiles, like: `distfiles=https://...${version/r/-}.tar.gz`

**Comment by hervyqa** [comment]
ah i just knew, changed from `2.0r3` to be `2.1r0`.
solved. thank you.
