### ISSUE TITLE
libinput-1.11.1_1 broken

### ISSUE THREAD

**Issue by Piraty** [void-linux/void-packages#427]
### System

* xuname:  
  `Void 4.16.12_2 x86_64 AuthenticAMD uptodate rFFFFFFFFFFFFFFFFF`
* package:  
  `libinput-1.11.1_1`

### Actual behavior
* `libinput list-devices` segfaults,
* basic events like tap are not recognized via `libinput debug-events`
### Steps to fix
downgrade to the last known working version, for example
`xdowngrade /var/cache/xbps/libinput-1.11.0_1.x86_64.xbps`

**Comment by Johnnynator** [comment]
I think this is related to this
https://gitlab.freedesktop.org/libinput/libinput/issues/50

**Comment by Johnnynator** [comment]
Should be fixed now.
