### ISSUE TITLE
[RFC] Use Config Fragments for Kernel Configs

### ISSUE THREAD

**Issue by Gottox** [void-linux/void-packages#4273]
Currently we're shipping dozens of different kernel configs with overlapping features. It would be nice if we could split them into fragments (e.g. arch-specific, platform-specific, and features) so we can enable features of fix platform configuration errors without editing multiple files. Linux ships a "merge_config.sh" script that compiles a config file from multiple fragments.

Resource:
 * https://www.youtube.com/watch?v=J8zxekwYMDY&t=8s
 * [scripts/kconfig/merge_config.sh](https://github.com/torvalds/linux/blob/master/scripts/kconfig/merge_config.sh)

**Comment by CameronNemo** [comment]
I am interested in this for busybox as well. I tried to do something similar in #4296, but it is not as sophisticated as it could be. Obviously the kernel is a priority.
