### ISSUE TITLE
LXC/LXD on btrfs is broken for 6.2 kernel. Upstream lxd 5.11 fixes.

### ISSUE THREAD

**Issue by markmcb** [void-linux/void-packages#42748]
### Is this a new report?

Yes

### System Info

Void 6.2.2_1 x86_64 GenuineIntel uptodate rFFFF

### Package(s) Affected

lxd-5.9_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/lxc/lxd/pull/11333

### Expected behaviour

lxc launch images:archlinux testcreate-arch                                  

... this should create a new Arch Linux container. (OS is irrelevant.)

### Actual behaviour

lxc launch images:archlinux testcreate-arch                                  
Creating testcreate-arch                                                                                
Error: Failed instance creation: Failed creating instance from image: Failed to run: btrfs qgroup create
 0/1868 /var/lib/lxd/storage-pools/default/images/c49a37117b5443dad3226d43b224dae38ff9ccb1694c753d66f377
8e34ff8ec6: exit status 1 (ERROR: unable to create quota group: File exists) 

### Steps to reproduce

1. Install lxd/lxc on a few months old Void
2. Update to 6.2 kernel (with btrfs-progs changes)
3. Try to create a new container

**Comment by classabbyamp** [comment]
cc maintainer @CameronNemo

**Comment by markmcb** [comment]
Further evidence for @CameronNemo if needed, Debian sid cherry-picked from upstream to address this: https://metadata.ftp-master.debian.org/changelogs//main/l/lxd/lxd_5.0.2-3_changelog
