### ISSUE TITLE
Update: qemu

### ISSUE THREAD

**Issue by etosan** [void-linux/void-packages#4275]
### System

* xuname:  
  `Void 4.17.19_2 x86_64 GenuineIntel uptodate rrrdDFFFF`
* package:  
  `qemu-3.0.0_2`

### Expected behavior

SDL video output is not compiled in. I would like to ask maintainer to re-enable sdl2 backend to get sdl screen display on host side. It helps immensely with supervised qemus on multimonitor systems with tiling/scriptable/no window managers. I hope I am not sole user of that feature.

### Actual behavior

Void's qemu now complains about SDL display not being available when specified in shell or in `./run`. This is annoying for ad-hoc spawned vms and outright prevents supervised vms from booting. Maybe it was disabled because of supposed deprecation (not sure)? Still pretty abrupt. I too have trouble determining whether it is only SDL1 support that is being deprecated or SDL as whole (even 2) is being deprecated. When recompiled from void-pkgs with sdl2 option I get no notices.

### Steps to reproduce the behavior

Install qemu and start vm from shell with `-display sdl`.

**Comment by Gottox** [comment]
We can switch back to SDL if the scaling issues are fixed.

**Comment by Hoshpak** [comment]
I created a PR as a basis for further discussion and will test it myself later.

**Comment by Hoshpak** [comment]
@Gottox I found some time to build and test qemu with sdl locally. I couldn't reproduce the scaling issues you had earlier, however I only have a 1920x1080 screen. However as I assumed earlier, gtk and sdl can be enabled at the same time and a user can switch by setting `-display sdl` or `-display gtk` when launching a qemu instance. If now `-display` is specified, qemu defaults to gtk at least on my system. So I think re-enabling sdl would not hurt people currently using gtk while providing an additional option for people wanting to use sdl.

**Comment by etosan** [comment]
As already said, both options can be active at the same time. It seems that on my system too, gtk is preferred automatically, if `-display` is unspecified. I am pretty confident enabling SDL will not cause problems for most users, but I also have only HD screens to test. I would assume there is more SDL users than UHD users, though.
