### ISSUE TITLE
Package request: Python 3 Numba

### ISSUE THREAD

**Issue by budrz55** [void-linux/void-packages#42765]
### Package name

python3-numba

### Package homepage

https://numba.pydata.org/

### Description

JIT compiler that translates a subset of Python and NumPy code into fast machine code.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by tranzystorek-io** [comment]
Unfortunately, this section https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#building-manually makes packaging almost impossible - upstream demands we build a particular variant of LLVM from source and points out that using the system installation of LLVM won't work. Void typically doesn't maintain special versions of dependencies.

**Comment by ahesford** [comment]
Unfortunately, requiring a patched LLVM is a deal-breaker here; this is the same reason we struck Julia from the repo.
