### ISSUE TITLE
Mathjax in jupyter notebook is broken

### ISSUE THREAD

**Issue by tornaria** [void-linux/void-packages#42775]
### Is this a new report?

Yes

### System Info

Void 6.1.15_1 x86_64

### Package(s) Affected

mathjax-3.2.2_1, python3-jupyter-4.7.1_3, python3-jupyter_notebook-6.4.10_2, ...

### Expected behaviour

can use latex in markdown cells on jupyter notebooks.

### Actual behaviour

- opening a jupyter notebook shows an error "Failed to retrieve MathJax from".
- latex in markdown cells will not be rendered
- the jupyter notebook console gives the following error: `[W 16:11:32.933 NotebookApp] 404 GET /static/components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full,Safe&delayStartupUntil=configured (127.0.0.1) 1.140000ms referer=http://127.0.0.1:8888/notebooks/FuO/lab/Untitled.ipynb`

### Steps to reproduce

1. run `jupyter notebook`
2. create a new notebook (python 3)
3. errors mentioned above show up

OTOH, downgrading mathjax to 2.7.9_1 fixes this issue.

Apparently this is an upstream issue (https://github.com/jupyter/notebook/issues/5758)

The other package in void repo that depends on mathjax is calibre. I don't know if calibre can work with mathjax 2.7.4. At least the commit where calibre was updated from 2.7.9 to 3.2.2 (1cbfc88a48d80601904a5121b8c29289aa4115e5) does not mention calibre at all.

cc: @sgn

**Comment by tornaria** [comment]
It seems we already ship a vendored in mathjax 2.7.9 in `python3-nbclassic` and, moreover, updating `python3-jupyter_notebook` to 6.5.3 will use mathjax from this package.

I will work on this and make a PR to update jupyter notebook et al to current versions.

**Comment by sgn** [comment]
IIRC, mathjax 2.7 don't share any files with mathjax 3.x, we can install 2 packages
