### ISSUE TITLE
jupyter notebook cannot start python3 kernel

### ISSUE THREAD

**Issue by Sqvid** [void-linux/void-packages#42793]
### Is this a new report?

Yes

### System Info

Void 6.1.18_1 x86_64 GenuineIntel uptodate rrFFFFF

### Package(s) Affected

python3-jupyter_notebook-6.4.10_3

### Expected behaviour

After installing the package I would expect that `jupyter notebook` brings up the browser and allows me to create a new notebook with the python3 kernel.

### Actual behaviour

The browser opens but there is nothing listed under the "notebooks" option. [Picture example](https://imgur.com/a/ME8XWV9).

[Here is the output log.](https://pastebin.com/raw/4wKGtgN8) To me it looks like the `nbclient` package version needs to be `<0.6.0` but void packages `python3-nbclient-0.7.0_1`.

### Steps to reproduce

1. `# xbps-install -S python3-jupyter_notebook`
2. `$ jupyter notebook`
3. Switch to browser.

**Comment by paper42** [comment]
@dkwo ddefd105ec0ab3cad38310213f7db48b11859dde

**Comment by dkwo** [comment]
it seems to work here
```
$ jupyter notebook 
[I 17:25:27.756 NotebookApp] Jupyter Notebook 6.4.10 is running at:
[I 17:26:08.080 NotebookApp] Creating new notebook in /Documents/Sage
[I 17:26:09.846 NotebookApp] Kernel started: a446b7da-859f-4817-bbb2-6fa70e41bf55, name: python3
[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
```
just to make sure: are we using Python 3 (ipykernel)?

**Comment by dkwo** [comment]
of course updating the ancient python3-jupyter_notebook may be a good idea anyway

**Comment by icp1994** [comment]
Can you install `python3-pip` (if you don't have it already) and run `pip3 check`? That should give an indication if it's a dependency issue or not.

**Comment by Sqvid** [comment]
> it seems to work here
> 
> ```
> $ jupyter notebook 
> [I 17:25:27.756 NotebookApp] Jupyter Notebook 6.4.10 is running at:
> [I 17:26:08.080 NotebookApp] Creating new notebook in /Documents/Sage
> [I 17:26:09.846 NotebookApp] Kernel started: a446b7da-859f-4817-bbb2-6fa70e41bf55, name: python3
> [IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
> ```
> 
> just to make sure: are we using Python 3 (ipykernel)?

I managed to also get it working. Im not exactly sure how but in the process of messing it around i think I've possibly removed a pip package that may have caused the trouble. `pip3 check` still complains with the aformentioned messages but it works. I don't know why the `nbclient` version is no longer a dealbreaker though.

**Comment by icp1994** [comment]
Yeah it's quite old, I have been using it via pipx too. I plan to update it when they land the big update of notebook-v7.
