### ISSUE TITLE
Remove libspotify package

### ISSUE THREAD

**Issue by Sqvid** [void-linux/void-packages#42809]
With libspotify [officially dead](https://developer.spotify.com/community/news/2022/04/12/libspotify-sunset/) for a while now, is it time to remove it from the repos? It is non-functional and even the homepage mentioned in the template 404s. I wouldnt mind submitting a pull request for this but im not sure how. Do I just `git rm`, add it to `removed-packages`, and remove it from `common/shlibs`?

**Comment by icp1994** [comment]
https://github.com/void-linux/void-packages/blob/master/Manual.md#removing-a-package and check the exapmle PRs under https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md
