### ISSUE TITLE
Add support for pkcs11 in strongswan

### ISSUE THREAD

**Issue by kotoko** [void-linux/void-packages#42811]
I have working vpn configuration using certificate that is stored on smartcard on linux mint. I am trying to setup same vpn on void linux. I think the problem is in strongswan that does not have plugin enabled. When I looked at [1] I see there is no plugin `pkcs11` enabled. According to [2] it is necessary to add option `--enable-pkcs11` before compilation.

Please add support for pkcs11 in strongswan.

[1] https://raw.githubusercontent.com/void-linux/void-packages/e21993428f6776a1730f92f23a3189c7c13becc8/srcpkgs/strongswan/template
[2] https://docs.strongswan.org/docs/5.9/plugins/pkcs11.html

**Comment by abenson** [comment]
Can you build and test [this](https://github.com/void-linux/void-packages/pull/43058)?

**Comment by kotoko** [comment]
I need guidance. If you can show me how to build and install I can try.

**Comment by kotoko** [comment]
I can confirm that now my vpn connection is working also on void :)
