### ISSUE TITLE
zfs on musl: Building DKMS module 'zfs-2.1.9' for kernel-6.1.19_1... FAILED!

### ISSUE THREAD

**Issue by egrain** [void-linux/void-packages#42871]
### Is this a new report?

Yes

### System Info

musl 6.1.19_1 #1 SMP PREEMPT_DYNAMIC Wed Mar 15 13:49:56 UTC 2023 x86_64 GNU/Linux

### Package(s) Affected

zfs-2.1.9_1  

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Not sure, seems similar:
https://www.reddit.com/r/voidlinux/comments/9yz777/comment/ea7u041/
https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1683340

### Expected behaviour

Install successfully, not just claim it did.

### Actual behaviour

$ xboxplaystation-install zfs
...
zfs-2.1.9_1: configuring ...
DKMS module 'zfs-2.1.9' already added, skipping.
Building DKMS module 'zfs-2.1.9' for kernel-6.1.19_1... FAILED!
DKMS module 'zfs-2.1.9' failed to build, please check /var/lib/dkms
for errors in the log file.
Regenerating initramfs images using kernel hook 20-initramfs
dracut-install: Failed to find module 'zfs'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.wkwa04/initramfs --kerneldir /lib/modules/6.1.19_1/ -m zfs
dracut: installkernel failed in module zfs
zfs-2.1.9_1: installed successfully.

$ cat /var/lib/dkms/zfs/2.1.9/build/make.log 
DKMS make.log for zfs-2.1.9 for kernel 6.1.19_1 (x86_64)
Sun Mar 19 20:53:34 UTC 2023
make: Entering directory '/var/lib/dkms/zfs/2.1.9/build/module'
make: *** No targets specified and no makefile found.  Stop.
make: Leaving directory '/var/lib/dkms/zfs/2.1.9/build/module'

$ xboxplaystation-query -Rs headers |grep 6.1.19
[*] linux6.1-headers-6.1.19_1                    Linux kernel and modules (6.1 series) - source headers for 3rd party modules

$ ls /boot
config-6.1.19_1  grub  initramfs-6.1.19_1.img  vmlinuz-6.1.19_1

$ xboxplaystation-pkgdb -a     returns nothing.

### Steps to reproduce

1. Have musl (though I haven't actually tested if it works on glibc)
2. doas xbps-install -Su
3. doas xbps-remove -Oo 
4. doas vkpurge rm all
5. doas xbps-install zfs

**Comment by sgn** [comment]
Not reproducible! Please share your dkms build log.

**Comment by egrain** [comment]
All I could find was this /var/lib/dkms/zfs/2.1.9/build/make.log, which I added already.
Is there anything else I have to do to produce one or did I just not find it? Sorry, I just use stuff and make bad xbps console jokes.

**Comment by egrain** [comment]
I tried installing it on another void musl system. Same error. Everything else works fine on that machine though. Qemu, lxc, openvpn, sshd, updates and boots without any issues. I installed both following the chroot documentation. This one 2 years ago. The one where I first encountered the error I installed last December.

I included the install output and /var/lib/dkms/zfs/2.1.9/build/make.log:
[zfs_other_void_musl_box_install_log.txt](https://github.com/void-linux/void-packages/files/11016360/zfs_other_void_musl_box_install_log.txt)

**Comment by sgn** [comment]
`musl 6.1.19_1 #1 SMP PREEMPT_DYNAMIC Wed Mar 15 13:49:56 UTC 2023 x86_64 GNU/Linux` How can you generate this line? This doesn't match with `uname -a`?

**Comment by egrain** [comment]
$ xbps-query -p pkgver zfs; xbps-query -p pkgver linux6.1; xbps-query -p pkgver linux6.1-headers
zfs-2.1.9_1
linux6.1-6.1.19_1
linux6.1-headers-6.1.19_1

$ uname -a | sed -E 's/^Linux\s(\S+)/musl/g'
I saw the dependencies of xtools, and figured only musl was missing, so I replaced the first two words with it.

$ xbps-query -Rs musl |grep \*
[*] musl-1.1.24_15                            Musl C library
[*] musl-fts-1.2.7_4                          Implementation of fts(3) for musl libc

**Comment by sgn** [comment]
How about your `xbps-query -l | grep -v '^ii'`?
Did you try `xbps-reconfigure -f linux6.1`?

**Comment by sgn** [comment]
Maybe try this directly:
```
# dkms build --force -m zfs -v 2.1.9 -k 6.1.9_1
```

**Comment by egrain** [comment]
$ xbps-query -l | grep -v '^ii'
nothing

$ doas xbps-reconfigure -f linux6.1
linux6.1: configuring ...
Executing post-install kernel hook: 10-dkms ...
Available DKMS module: zfs-2.1.9.
Building DKMS module: zfs-2.1.9... FAILED!
Generating kernel module dependency lists... done.
Executing post-install kernel hook: 20-initramfs ...
dracut-install: Failed to find module 'zfs'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.inSxCU/initramfs --kerneldir /lib/modules/6.1.19_1/ -m zfs
dracut: installkernel failed in module zfs
Executing post-install kernel hook: 50-grub ...
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-6.1.19_1
Found initrd image: /boot/initramfs-6.1.19_1.img
Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.
done
linux6.1: configured successfully.

You sure about that last one? Gave me this:
$ doas dkms build --force -m zfs -v 2.1.9 -k 6.1.9_1
Sign command: /lib/modules/6.1.9_1/build/scripts/sign-file
Binary /lib/modules/6.1.9_1/build/scripts/sign-file not found, modules won't be signed
Error! Your kernel headers for kernel 6.1.9_1 cannot be found at /lib/modules/6.1.9_1/build or /lib/modules/6.1.9_1/source.
Please install the linux-headers-6.1.9_1 package or use the --kernelsourcedir option to tell DKMS where it's located.

I added a 1 to 6.1.9:
$ doas dkms build --force -m zfs -v 2.1.9 -k 6.1.19_1
Sign command: /lib/modules/6.1.19_1/build/scripts/sign-file
Binary /lib/modules/6.1.19_1/build/scripts/sign-file not found, modules won't be signed

Warning: The pre_build script is not executable.

Building module:
Cleaning build area...(bad exit status: 2)
make -j12 KERNELRELEASE=6.1.19_1 -C module/...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.1.19_1 (x86_64)
Consult /var/lib/dkms/zfs/2.1.9/build/make.log for more information.

$ find /lib/modules/6.1.19_1/build/scripts/ -iname *sign*
/lib/modules/6.1.19_1/build/scripts/sign-file.c
/lib/modules/6.1.19_1/build/scripts/coccinelle/tests/unsigned_lesser_than_zero.cocci

$ cat /var/lib/dkms/zfs/2.1.9/build/make.log 
DKMS make.log for zfs-2.1.9 for kernel 6.1.19_1 (x86_64)
Mon Mar 20 16:37:30 UTC 2023
make: Entering directory '/var/lib/dkms/zfs/2.1.9/build/module'
make: *** No targets specified and no makefile found.  Stop.
make: Leaving directory '/var/lib/dkms/zfs/2.1.9/build/module'

**Comment by sgn** [comment]
`Warning: The pre_build script is not executable.`

Can you check if `configure` is executable? (It should!)
```
$ ls -al ls -al /var/lib/dkms/zfs/2.1.9/source/configure
-rwxr-xr-x 1 root root 2741513 2023-01-28 17:07 /var/lib/dkms/zfs/2.1.9/source/configure
```

**Comment by egrain** [comment]
$ ls -l /var/lib/dkms/zfs/2.1.9/source/configure
-rwxr-xr-x 1 root root 2741513 Jan 31 20:57 /var/lib/dkms/zfs/2.1.9/source/configure

it is.

**Comment by egrain** [comment]
$ ls -l /var/lib/dkms/zfs/2.1.9/build/configure
-rwxr-xr-x 1 root root 2741513 Jan 31 20:57 /var/lib/dkms/zfs/2.1.9/build/configure

Would have been funny thought if it had been a rights issue again. It's usually one of those.

**Comment by sgn** [comment]
What is your `/bin/sh`? Maybe your can try:
```
doas /bin/bash -x /usr/bin/dkms build --force -m zfs -v 2.1.9 -k 6.1.9_1
```

To see detailed output.

**Comment by egrain** [comment]
Oh, my bad. I didn't check the numbers.
+ error 'Bad return status for module build on kernel: 6.1.19_1 (x86_64)' 'Consult /var/lib/dkms/zfs/2.1.9/build/make.log for more information.'

[6.1.19.txt](https://github.com/void-linux/void-packages/files/11021257/6.1.19.txt)

**Comment by sgn** [comment]
Somehow `[[ -x /var/lib/dkms/zfs/2.1.9/build/configure ]]` is failure, but yours has executable bits. Can you check your `/bin/sh`, or try to run the file directly:
```
cd /var/lib/dkms/zfs/2.1.9/build/ && doas /var/lib/dkms/zfs/2.1.9/build/configure
```

**Comment by egrain** [comment]
$ pwd
/var/lib/dkms/zfs/2.1.9/build

$ ls -l configure
-rwxr-xr-x 1 root root 2741513 Jan 31 20:57 configure

$doas ./configure
doas: ./configure: Permission denied

HA! told you it's a rights issue.
I tried it as root, becuase I thought maybe I configured doas wrong on both machines. Then I realized:
/var type ext4 (rw,nosuid,nodev,noexec,relatime,data=ordered)
and that's of course why it doesn't work on the other box either, because I always have the noexec going for almost everything.

So yeah, this was totally my fault. Sorry for taking up all your time.

**Comment by sgn** [comment]
If you like to mount noexec `/var` that much, you can ask openzfs to run `/bin/sh configure` on `pre_build`.
I'm not sure if they will accommodate your request, though.

**Comment by egrain** [comment]
I can just reboot twice. But I think I'll survive.

I'd rather have someone take a look at the "success" message after xbps-install -Su while half the kernel files I need to boot are missing. Happened to me twice now. Once boot wasn't big enough for two kernels and this time when the DKMS build failed while updating to 6.1.20_1. 

Anyway, thanks again for all your help.
