### ISSUE TITLE
duplicated font packages `font-liberation-ttf` & `liberation-fonts-ttf`

### ISSUE THREAD

**Issue by dmarto** [void-linux/void-packages#42873]
@sgn 

I guess `liberation-fonts-ttf`, needs to be removed/replaced with `font-liberation-ttf` and the files in `pkgsrc/liberation-fonts-ttf/files` moved to `font-liberation-ttf` and installed at the proper location:
```
/etc/fonts/conf.avail/30-liberation-fonts-ttf-mono.conf
/etc/fonts/conf.avail/30-liberation-fonts-ttf-sans.conf
/etc/fonts/conf.avail/30-liberation-fonts-ttf-serif.conf
``` 

---

I am not fully confident in my knowledge of xbps-src `replace` or what will be the proper approach for this, thus an issue and not a PR.

**Comment by sgn** [comment]
Given `font-liberation-ttf` is new, I would keep `liberation-fonts-ttf`. Thanks.
