### ISSUE TITLE
qt5ct,  problems with qt5ct.sh

### ISSUE THREAD

**Issue by furryfixer** [void-linux/void-packages#42891]
Presumably applies to qt6 as well. I would like to further the discussion touched on in ** ##40619** about the desirability of including or activating **"/etc/profile.d/qt5ct.sh**" when installing the qt5ct package.  What brought this to my attention was the failure of icon themes in Plasma5 when started from the user's command line, as opposed to using a login manager.  Having forgotten about my prior installation of qt5ct, it took some time to decipher the problem.

Most login/display managers will reliably set $XDG_CURRENT_DESKTOP, but it will not be set with startx, or startplasma-wayland when a logged-in user starts directly from a tty.  In the latter case, qt5ct.sh will set QT_QPA_PLATFORMTHEME=qt5ct, even though the user is starting KDE Plasma.  This problem will also affect users of LXQT, who also may prefer not setting the theme to qt5ct.

Admittedly, starting Plasma or LXQT without a login manager is an uncommon use case, which is why I am ambivalent about removing qt5ct.sh.   I would just suggest that the pros/cons should be weighed vs. the alternative of asking the user to set QT_QPA_PLATFORMTHEME on their own.

**Comment by classabbyamp** [comment]
you can always set XDG_CURRENT_DESKTOP yourself when doing startx

**Comment by furryfixer** [comment]
> you can always set XDG_CURRENT_DESKTOP yourself

Yes, and/or set QT_QPA_PLATFORMTHEME.
