### ISSUE TITLE
Package request: tdfgo

### ISSUE THREAD

**Issue by usernamer-git** [void-linux/void-packages#42902]
### Package name

tdfgo

### Package homepage

https://github.com/digitallyserviced/tdfgo

### Description

TheDraw font renderer in Go

![tdfgo-help](https://user-images.githubusercontent.com/84246111/226599425-f964d964-b840-43df-90c1-ee95e36d1746.png)
![tdfgo-clock](https://user-images.githubusercontent.com/84246111/226599574-a90b18fb-7cc5-4495-8611-655a9770fee9.png)
![tdfgo-font-dump-verbose](https://user-images.githubusercontent.com/84246111/226602608-f32bc3eb-78d4-4cc5-8e05-98ceade8afe5.png)

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

No

**Comment by paper42** [comment]
> ### Is the requested package released?
> 
> Yes

it doesn't have releases as far as I can tell

**Comment by usernamer-git** [comment]
I was editing at the time you wrote, I had sent without looking.

**Comment by paper42** [comment]
in that case, this currently does not meet our quality requirements
