### ISSUE TITLE
OCR-menu in gscan2pdf not recognizing tesseract but shows GOCR

### ISSUE THREAD

**Issue by numerys** [void-linux/void-packages#42932]
### Is this a new report?

Yes

### System Info

Void 6.1.20_1 x86_64 GenuineIntel uptodate rrrmFFFF

### Package(s) Affected

gscan2pdf-2.13.2_1

### Expected behaviour

I installed gscan2pdf along with tesseract.

    xbps-install -Su gscan2pdf tesseract-ocr-all pdftk

When gscan2pdf is ready to scan it should offer a menu to choose the Tesseract-OCR engine from. A correct menu would look like:

![menuentry](https://user-images.githubusercontent.com/17107201/227005276-83ec88d5-c201-4655-9176-fb1e52883145.png) 

### Actual behaviour

The mentioned menuentry shows GOCR and only GOCR, beside it seems no GOCR package is in the Void [repository](https://voidlinux.org/packages/?arch=x86_64&q=gocr) and misses the Tesseract-entry. It looks like:

![Bildschirmfoto vom 2023-03-22 19-45-56](https://user-images.githubusercontent.com/17107201/227006967-e9049bfa-0437-49f1-b4d9-c42bb3babd4e.png)

### Steps to reproduce

1. Run a desktop environment of your choice
2. Install gscan2pdf and tesseract
    `xbps-install -Su gscan2pdf tesseract-ocr-all pdftk`
3. Attach a supported scanner
4. Run gscan2pdf

A [gscan2pdf.log](https://github.com/void-linux/void-packages/files/11043819/gscan2pdf.log) is attached for documentation. It does show that the a tesseract-engine is found and a gocr-engine is not found.

**Comment by numerys** [comment]
I searched `Tesseract.pm` but could not find a bug. @sgn, @newbluemoon could you take a look?

**Comment by numerys** [comment]
I created a [pull request](https://github.com/void-linux/void-packages/pull/42968) with a corrected patch.

**Comment by Hoshpak** [comment]
fixed in #42968
