### ISSUE TITLE
Package request: clifm

### ISSUE THREAD

**Issue by leo-arch** [void-linux/void-packages#43005]
### Package name

clifm

### Package homepage

https://github.com/leo-arch/clifm

### Description

Unlike most terminal file managers out there, **clifm** replaces the ubiquitous TUI by a shell-like command line interface: all input and interaction is performed via commands.

It provides automatic files listing, files selection, bookmarks, tags, file filters, a zoxide-like directory jumper, directory and commands history, auto-cd and auto-open (via a built-in resource opener), bulk rename, shell commands execution, TAB completion (with deep FZF integration and file previews), fish-like autosuggestions, plugins, and a trash system, among other features.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment]
https://github.com/void-linux/void-packages/issues/31557

**Comment by mhmdanas** [comment]
That line doesn't seem to be present anymore in the latest code, but this is mentioned in https://github.com/leo-arch/clifm/wiki/Introduction#goals:
> Nonetheless, clifm works currently [...] not only on X86_64 architectures, but on i386 and ARM machines as well.

**Comment by leo-arch** [comment]
Hi @paper42. Thanks for your quick reply!

> That line doesn't seem to be present anymore in the latest code

Yes, the OS/architecture restriction is gone

> Nonetheless, clifm works currently [...] not only on X86_64 architectures, but on i386 and ARM machines as well.

Do you need me to remove that line from the docs?
