### ISSUE TITLE
Please install fontconfig file for noto-fonts-cjk

### ISSUE THREAD

**Issue by Dieken** [void-linux/void-packages#43014]
https://github.com/void-linux/void-packages/blob/41be7d0820584455d9be0f196359bd3718f8e72f/srcpkgs/noto-fonts-cjk/template#L26

Debian/Ubuntu/Slackware/Arch/Gentoo/SUSE/Fedora all ship similar file to select correct Noto CJK fonts for different languages:

https://salsa.debian.org/fonts-team/fonts-noto-cjk/-/blob/debian/sid/debian/70-fonts-noto-cjk.conf

Please copy that file from Debian and install as /etc/fonts/conf.d/`70-noto-fonts-cjk.conf`.

Thanks!

**Comment by classabbyamp** [comment]
hm I don't seem to have any issues with the cjk fonts without this. are you having any issues without this file?

**Comment by Dieken** [comment]
> hm I don't seem to have any issues with the cjk fonts without this. are you having any issues without this file?

Without that file, fontconfig will always choose the JP variant for CJK languages because JP is before KR, SC, TC in alphabetic order.

```sh
$ fc-match sans:lang=zh-cn
NotoSansCJK-Regular.ttc: "Noto Sans CJK JP" "Regular"
```

**Comment by classabbyamp** [comment]
ok, makes sense
