### ISSUE TITLE
Package request: hyperland

### ISSUE THREAD

**Issue by superiums** [void-linux/void-packages#43047]
### Package name

hyperland

### Package homepage

https://hyprland.org/

### Description

Hyprland!
A dynamic tiling [Wayland](https://wayland.freedesktop.org/) compositor based on [wlroots](https://way-cooler.org/book/wlroots_introduction.html) that doesn't sacrifice on its looks.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
#37544
