### ISSUE TITLE
[RFC] enable discussions for void-packages

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-packages#43081]
### Pros

- Allows the issue tracker to only contain bug reports and RFCs
- Feature and package requests could be converted to discussions to avoid flooding the issue tracker, and kept in separate categories
- Q & A categories could be used as a general support forum for those who don't want to use reddit
- could also be enabled as ["organisation discussions"](https://github.blog/2022-04-12-whats-new-in-github-discussions-organization-discussions-polls-and-more/#introducing-organization-discussions) so it shows up at the org level
- if a support discussion or feature request rises to the level of a bug report or RFC, it can be converted into an issue

### Cons

- no automatic discussion closing via commits/PRs (`fixes #12345`)
- adds an additional support forum for maintainers to keep track of

@void-linux/pkg-committers 

previous discussion (discussions can now be closed, so there is a difference from then): #36700

**Comment by Duncaen** [comment]
Having discussions for support or questions seems ok and we can move invalid "issues" there instead of just closing them as "not an issue".

I still don't like the idea of moving package requests somewhere else. The forum-like interface encourages users to comment and bump their requests to the top by having pointless discussions or gives the impression that requests with more upvotes would have priority.

**Comment by leahneukirchen** [comment]
Also `Fixes #xxxx` wouldn't work I think.

**Comment by ahesford** [comment]
I prefer GH to Reddit for general support and would like to pin a message on r/voidlinux directing users to GH Discussions. Over time, if Reddit activity died down, I'd probably just stop checking it.

I don't have a strong opinion about moving new-package requests off the issue page, but it would be nice to reduce the issue clutter and highlight actual problems. People might try to game request discussions, but that certainly doesn't bind anybody to taking action. If we don't move new-package requests to discussions, we might get similar benefit from pruning such requests with stale-not after an extended period.

**Comment by classabbyamp** [comment]
> Also `Fixes #xxxx` wouldn't work I think.

as a stop-gap until github implements it, a workflow could be used to close discussions, assuming the api endpoints are there
