### ISSUE TITLE
memtester: fails to fetch

### ISSUE THREAD

**Issue by icp1994** [void-linux/void-packages#43104]
```
» ./xbps-src -I fetch memtester
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> memtester-4.5.1_1: running do-fetch hook: 00-distfiles ...
=> memtester-4.5.1_1: fetching distfile 'memtester-4.5.1.tar.gz' from 'http://pyropus.ca/software/memtester/old-versions/memtester-4.5.1.tar.gz'...
SSL certificate subject doesn't match host pyropus.ca.
http://pyropus.ca/software/memtester/old-versions/memtester-4.5.1.tar.gz: Operation not permitted
=> ERROR: memtester-4.5.1_1: failed to fetch 'memtester-4.5.1.tar.gz'.
```

I have tried changing `distfiles` to `https://pyropus.ca./software/memtester/old-versions/memtester-${version}.tar.gz` but that doesn't work either. Although locally
`curl -v -fsSL "http://pyropus.ca/software/memtester/old-versions/memtester-4.5.1.tar.gz" -O` works.

**Comment by icp1994** [comment]
`https://repology.org/project/memtester/information` shows debian source as the latest non-dead one.

**Comment by classabbyamp** [comment]
what about https://github.com/jnavila/memtester/releases/tag/v4.5.1?

**Comment by icp1994** [comment]
Yes, but it's a mirror which is not updated and also not from the author/maintainer. Is that good for distfiles?

**Comment by classabbyamp** [comment]
debian should be fine too :woman_shrugging:

**Comment by classabbyamp** [comment]
wait, it's right here: https://pyropus.ca./software/memtester/old-versions/
