### ISSUE TITLE
Package request: muon

### ISSUE THREAD

**Issue by CorruptedVor** [void-linux/void-packages#43134]
### Package name

muon

### Package homepage

https://muon.build/

### Description

muon is an implementation of the meson build system in c99 with minimal dependencies.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by icp1994** [comment]
https://github.com/void-linux/void-packages/pull/42232

**Comment by hervyqa** [comment]
#42232 merged. please close this issue.
