### ISSUE TITLE
wine 32bit: couldn't be able to find ntdll.so

### ISSUE THREAD

**Issue by rilysh** [void-linux/void-packages#43132]
### Is this a new report?

Yes

### System Info

Void 6.1.21_1 x86_64 GenuineIntel uptodate rrmFFF

### Package(s) Affected

wine-32bit-8.4_1

### Expected behaviour

32-bit version of wine should run just fine.

### Actual behaviour

Launching wine (32-bit) literally throws that ntdll.so couldn't be found on its path. Running wine (64-bit) with its usual name, wine64 which runs just fine.

#### Message
wine (32-bit)
```
wine: could not load ntdll.so: /usr/libexec/wine/../../lib32/wine/i386-unix/ntdll.so: cannot open shared object file: No such file or directory
```

### Steps to reproduce

1. Enable multilib repositories in Void. Usually with (`xbps-install -Sy void-repo-multilib`)
2. Install wine regardless of its package name, wine-32bit with (`xbps-install -Sy wine-32bit`)
3. Open a terminal and run wine (which will now address 32-bit version of wine)

**Comment by amak79** [comment]
Is `libwine-32bit` installed? With the Wine 8.4 update it was uninstalled with `xbps-remove -o`, so I had to manually install it.

**Comment by rilysh** [comment]
Ah, I see.  Though this is a fresh install of Void (where I installed wine) and seems like libwine-32bit is not packed. I suppose it should be included with wine (32-bit) package. Not sure why they didn't.

Anyway, thanks! It worked.

**Comment by amak79** [comment]
Installing `wine-32bit` should automatically install `libwine-32bit` as well but something broke/changed during the 8.4 update. I think you should re-open this issue so the maintainer can have a look since there could be a problem with the package.

**Comment by amak79** [comment]
@Hoshpak Can you please take a look at this issue?

**Comment by Hoshpak** [comment]
Thanks for the ping. Indeed it looks like the dependency was outodetected previously but isn't any more. I'm working on explicitely adding the dependency with an update to 8.8.
