### ISSUE TITLE
Package request: kvantum-qt6

### ISSUE THREAD

**Issue by JuniorSuperTux** [void-linux/void-packages#43151]
### Package name

kvantum-qt6

### Package homepage

https://github.com/tsujan/Kvantum

### Description

Qt6 component of the Kvantum theme engine

Arch package here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kvantum-qt6-git

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by zlice** [comment]
I updated a bit ago for qt6 https://github.com/void-linux/void-packages/pull/46851

Still have https://github.com/void-linux/void-packages/pull/46850 open
