### ISSUE TITLE
Update Request: Firefox and Firefox ESR 

### ISSUE THREAD

**Issue by 38github** [void-linux/void-packages#43168]
https://ftp.mozilla.org/pub/firefox/releases/111.0.1/source/
https://ftp.mozilla.org/pub/firefox/releases/102.9.0esr/source/

The versions are updated in https://repo-default.voidlinux.org/void-updates/void-updates.txt but have not been compiled for months. What causes this? Regards

**Comment by oreo639** [comment]
It requires llvm15 and an updated Rust, which is being worked on.

https://github.com/void-linux/void-packages/pull/43004
https://github.com/void-linux/void-packages/pull/40821
https://github.com/void-linux/void-packages/pull/42130

Also see https://github.com/void-linux/void-packages/blob/master/.github/ISSUE_TEMPLATE/bug-report.yml:
> Don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.

**Comment by 38github** [comment]
> Also see https://github.com/void-linux/void-packages/blob/master/.github/ISSUE_TEMPLATE/bug-report.yml:
> 
> > Don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.

Thank you for the LLVM 15 information. Regarding the bug report policy I only posted because I found it weird that the packages had not been compiled even though the information I wrote about.

**Comment by oreo639** [comment]
void-updates lists that Mozilla has made a new release of firefox, the version we have it determined by the template:
https://github.com/void-linux/void-packages/blob/master/srcpkgs/firefox/template
