### ISSUE TITLE
Package request: nodejs

### ISSUE THREAD

**Issue by retq1** [void-linux/void-packages#43197]
### Package name

nodejs

### Package homepage

https://nodejs.org/en

### Description

The repositories contain older versions of the nodejs current & lts. The current versions are 19.8.1 and 18.15.0 respectively.

Pls update node to the latest version released.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment]
update requests are not accepted, we know
