### ISSUE TITLE
shotcut should depend on ffmpeg

### ISSUE THREAD

**Issue by oldlaptop** [void-linux/void-packages#43214]
### Is this a new report?

Yes

### System Info

Void 6.1.21_1 x86_64-musl AuthenticAMD notuptodate rF

### Package(s) Affected

shotcut-22.01.30_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Not applicable.

### Expected behaviour

When told to open a variable-frame-rate video file, shotcut offers to convert it to a more sensible format for editing purposes, and attempts to do this with ffmpeg (meaning it attempts to shell out to the binary `/usr/bin/ffmpeg`).

### Actual behaviour

shotcut does not depend directly or indirectly on ffmpeg, meaning it's possible to have it installed without ffmpeg and have the conversion fail. (I've just had the dependencies actually shake out that way for me in a fresh installation.)

### Steps to reproduce

Install shotcut, do not install ffmpeg, attempt to open a variable-frame-rate video file in shotcut, and accept its offer to convert the file to a better format for editing.

**Comment by mhmdanas** [comment]
Can you test https://github.com/void-linux/void-packages/pull/43226? Other than adding the ffmpeg dependency, I also updated shotcut, but I don't use it, so I'd like you to test it as well if possible.

**Comment by oldlaptop** [comment]
Sure; I'll first have occasion to seriously use it later this week.
