### ISSUE TITLE
gcc doesn't build / breaks bootstrap

### ISSUE THREAD

**Issue by Piraty** [void-linux/void-packages#4325]
Using current master (as of 44404df93ee5ba4072e771abfa9b0cce527626d0), building gcc is broken.
This also breaks `./xbps-src bootstrap`.
```
...
configure: error: GNAT is required to build ada
```
related: #4154

@pullmoll

**Comment by pullmoll** [comment]
Using `./xbps-src -o ~ada,gnatboot pkg gcc` should work for now.
If your build host is Void, you can install `gcc-ada` and `libada-devel` in the host.
Generally it should work to have a Ada enabled gcc and gnat in the host.

**Comment by Piraty** [comment]
Thanks @pullmoll , fine with me for now. Bootstrap is still requiring [a lot more](https://github.com/voidlinux/void-packages/issues/11031) anyway...
