### ISSUE TITLE
postgresql-client (and thus postgres) is missing in xbps-alternatives

### ISSUE THREAD

**Issue by soanvig** [void-linux/void-packages#43259]
Postgresql packages are missing each other as alternatives.
Is it expected or just omitted by an accident?

My case is that I have installed postgresql14-client, and postgresql15-client, and there are not appearing in xbps-alternatives, so I have to manually switch between them.

Telling from their package templates they don't have `alternatives` field. Is that right?

I can create appropriate PR after the confirmation, that this is the case.

@Chocimier I think you are the maintainer, so I'm pinging  you

**Comment by Chocimier** [comment]
Cześć,

That's expected but can be changed with 16 series.

Postgresql 9.6 occupied /usr/bin/psql and was removed only a year ago. While it was still in repo, newer series were installed in /usr/lib, as xbps can't yet transactionally replace executable with an alternative. In order for new series to be accessible, profile scripts adding them to PATH exist. Shadowing of newer series by older ones is a mistake, but not too bad.

This setup is still in place to give people time to pull in now-meta postgresql package. As 16 will enter repos well over a year after removal of 9.6, it will be good time to introduce alternatives.

For server, separate services are in place, so this is not a problem.

Another question is why do you want to switch client (continuously, afaiu?), when other options are to remove old package and relogin; call by absolute path; or manipulate PATH in shell rc file?
