### ISSUE TITLE
cross compiling with cargo is broken

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#4328]
Cross compiling packages with build style cargo fails.
Example: [cbindgen](https://travis-ci.org/void-linux/void-packages/builds/449157824)

I haven't found the root of the problem yet but it can be fixed by reverting cargo-0.31.0 to 0.30.0.

**Comment by Gottox** [comment]
Here's the call of the failing command compared to the succeeding one with cargo-0.30. It looks like .cargo/config isn't read while installing.

https://gist.github.com/c5a543d7e3a4ba2246d03df50ae0c3d1

**Comment by jnbr** [comment]
https://github.com/rust-lang/cargo/issues/5850
