### ISSUE TITLE
Missing wx libraries in Erlang package

### ISSUE THREAD

**Issue by lbolla** [void-linux/void-packages#433]
Despite being configured to include wx devel libraries in https://github.com/void-linux/void-packages/blob/master/srcpkgs/erlang/template, no wx_*.so libraries end up in `/usr/lib/erlang/lib/wx-1.8.4/priv`, therefore commands like `debugger:start()` or `observer:start()` fail to run with:
```
2> debugger:start().
=ERROR REPORT==== 26-Jun-2018::18:14:07.646730 ===
ERROR: Could not find 'wxe_driver.so' in: /usr/lib/erlang/lib/wx-1.8.4/priv
...
```

**Comment by cr6git** [comment]
````
makedepends="ncurses-devel unixodbc-devel libressl-devel zlib-devel
 $(vopt_if x11 'wxWidgets-devel glu-devel')"

build_options="x11"
````
Build option, not enabled by default.

**Comment by lbolla** [comment]
Oh, thanks a lot!
