### ISSUE TITLE
ReText won't open after install

### ISSUE THREAD

**Issue by matthew-yates** [void-linux/void-packages#43323]
### Is this a new report?

Yes

### System Info

Void 6.1.21_1 x86_64 GenuineIntel uptodate rrFFF

### Package(s) Affected

ReText-7.2.1_3

### Expected behaviour

ReText window should open.

### Actual behaviour

Starting retext from the command line reveals an error in:

/usr/lib/python3.11/site-packages/ReText/window.py

It states an integer is expected in line 89, but a float is there instead.  I edited line 89 from:

self.splitter.setSizes([self.width() / 5, self.width() * 4 / 5])

to:

self.splitter.setSizes([int(self.width() / 5), int(self.width() * 4 / 5)])

Not sure if that is the correct bug fix, but ReText opens as expected now after making that edit.

### Steps to reproduce

1. xbps-install ReText
2. Try to open ReText from a graphical menu and nothing happens.

**Comment by mhmdanas** [comment]
Confirmed, #43347 fixes this for me (fix was released in ReText 7.2.2).
