### ISSUE TITLE
Bad signature in aarch64 xkeyboard package

### ISSUE THREAD

**Issue by lpvm** [void-linux/void-packages#434]
### System
```
# xuname
Void 4.14.48_1 aarch64  uptodate rF
```

package: `xkeyboard-config-2.24_1`

When installing `xorg-minimal` or `xorg-server`  in a `aarch64` system, the installation process aborts due to:
```
xkeyboard-config-2.24_1: verifying RSA signature...
ERROR: xkeyboard-config-2.24_1: the RSA signature is not valid!
ERROR: xkeyboard-config-2.24_1: removed pkg archive and its signature.
```

Tried both for `repo` and `repo2` repositories.

**Comment by codingHahn** [comment]
@Vaelatern Would a revbump be enough to fix this?

**Comment by Vaelatern** [comment]
Yes, a revbump would force generation of a new signature. Whether it is needed is a different question, @the-maldridge ?

**Comment by maxice8** [comment]
should be solved by https://github.com/void-linux/void-packages/commit/0cc83029cc38746c8f24666351726e0344b0f2ea

**Comment by lpvm** [comment]
The `-2` version was installed, has no errors.
Thanks!
