### ISSUE TITLE
Firefox 112 invisible text

### ISSUE THREAD

**Issue by someone13574** [void-linux/void-packages#43416]
### Is this a new report?

Yes

### System Info

Void 6.1.21_1 x86_64 AuthenticAMD uptodate rrrrmmdnFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
Void 6.1.21_1 x86_64-musl GenuineIntel uptodate rrnFFFFF

### Package(s) Affected

firefox-112.0_1

### Expected behaviour

Text rendering would work as in previous versions.

### Actual behaviour

A number of sites have text which isn't rendering. Some sites I've found which demonstrate this are [Github (as the largest site I've found)](https://github.com/void-linux/void-packages), [common crawl](https://commoncrawl.org/), and a few confirmation emails where the confirmation code is there (I can copy it) but invisible.

I am not sure if this is a Void specific problem but I've not seen any other reports of it so I am leaning in that direction.

### Steps to reproduce

1. Update Firefox to version 112.0
2. Go to [https://github.com/void-linux/void-packages](https://github.com/void-linux/void-packages)
3. Observe invisible text

**Comment by devlocalhost** [comment]
Can confirm, I face it on both sites mentioned

**Comment by Nidrop** [comment]
Can confirm too. 
I downgraded to version 111 through xdowngrade. Everything is fine there. If you want to do the same, you should make a backup of your firefox profile, because it stopped working for me after the downgrade.
I tested version 112 on Arch (through [junest](https://github.com/fsquillace/junest/)). It works fine. So this problem is specific to Void

**Comment by ircurry** [comment]
Having this issue too. I'm not sure if this is any help but I noticed that Vimium-FF (https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/) is also not displaying text. I'm not very familiar with how firefox and addons work but perhaps this could be useful for finding the issue.

**Comment by Adailoe** [comment]
Same here.

I'm not experienced enough to find out which fonts are exactly "broken", but an example (for me) is wikipedia. I can see the text but the headlines are invisible. 
(https://en.wikipedia.org/wiki/Void_Linux)

**Comment by Duncaen** [comment]
> I'm not experienced enough to find out which fonts are exactly "broken", but an example (for me) is wikipedia. I can see the text but the headlines are invisible. (https://en.wikipedia.org/wiki/Void_Linux)

Right click where the headline is and select "Inspect" and select "fonts" in the devtools like in this screenshot on the bottom right https://i.imgur.com/Lsk7FDr.png.

**Comment by Adailoe** [comment]
> > I'm not experienced enough to find out which fonts are exactly "broken", but an example (for me) is wikipedia. I can see the text but the headlines are invisible. (https://en.wikipedia.org/wiki/Void_Linux)
> 
> Right click where the headline is and select "Inspect" and select "fonts" in the devtools like in this screenshot on the bottom right https://i.imgur.com/Lsk7FDr.png.

Thanks! 
My entries in the devtool are the same as yours - except I can't see the headline, only the plain text in the paragraph.

**Comment by Nidrop** [comment]
it seems to be an issue with bitmap fonts rendering. I think it would be possible to reproduce the problem by installing the `xorg-fonts` package

**Comment by SavageMessiah** [comment]
Having the same problem. As a temp workaround you can uncheck `Allow pages to choose their own fonts, instead of your selections above` in the Advanced font settings. That fixes things for me. The default font (for me, at least) is the DejaVu family, so those fonts at least seem to work?

**Comment by ircurry** [comment]
Unchecked allowing pages to use their own fonts and it worked on my end as well and seems to work for all fonts I have installed.

**Comment by Anachron** [comment]
I have the `xorg-fonts` package installed by still have this issue.

This happens for me on https://nitter.net:
`sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji"`

And on https://github.com:
`sans-serif, Helvetica Neue, Helvetica, Arial`

Does not happen on https://community.frame.work:
`Graphik-Regular, sans-serif`

So for me this looks like an issue with `Helvetica,Arial`.

**Comment by Nidrop** [comment]
> I have the xorg-fonts package installed by still have this issue.

I'm sorry if I misled you. I suggested installing the package to those who do **not** have this problem in order to reproduce it.
I didn't have this problem on Arch because I don't have bitmap fonts installed there. Even when I installed them, firefox didn't use them.

**Comment by Adailoe** [comment]
> Having the same problem. As a temp workaround you can uncheck `Allow pages to choose their own fonts, instead of your selections above` in the Advanced font settings. That fixes things for me. The default font (for me, at least) is the DejaVu family, so those fonts at least seem to work?

This works for me too, using DejVu Sans and unchecked the allowance of the pages to use their own fonts.
Some pages look a bit unfamiliar now, but for me this is sufficient as a temporary workaround.

**Comment by PurpleVsGreen** [comment]
This looks like a regression of #31294 and the same workarounds apply.

**Comment by Anachron** [comment]
Are you talking about [this](https://github.com/void-linux/void-packages/issues/31294#issuecomment-864532071) workaround or [this](https://github.com/void-linux/void-packages/issues/31294#issuecomment-858921154)?

Or even [this](https://github.com/void-linux/void-packages/issues/31294#issuecomment-855526254) or [this](https://github.com/void-linux/void-packages/issues/31294#issuecomment-855212048) one?

**Comment by rickalex21** [comment]
Not sure why this is a problem but [uncheck Allow pages to choose their own font](https://support.mozilla.org/en-US/kb/change-fonts-and-colors-websites-use) fixed the problem. This only happens on void, the [void runsv man page](https://man.voidlinux.org/runsv.8) now can be viewed.

**Comment by Anachron** [comment]
@rickalex21 it's a solution because it overrides the webfonts (fonts the websites suggest the browser to use) with your system defined ones which are not broken.

**Comment by fosslinux** [comment]
This [has been fixed upstream](https://bugzilla.mozilla.org/show_bug.cgi?id=1827950).

**Comment by Anachron** [comment]
So if I understood it correctly, [this](https://hg.mozilla.org/mozilla-central/rev/18b8f731cb69) was the issue?

**Comment by Nidrop** [comment]
This patch has been approved for 112.0.2

**Comment by Nidrop** [comment]
@Duncaen I tested version 112.0.2 from the official site. It works fine.
