### ISSUE TITLE
Package request: fastfetch

### ISSUE THREAD

**Issue by gorhatlin** [void-linux/void-packages#43461]
### Package name

fastfetch

### Package homepage

https://github.com/LinusDierheimer/fastfetch

### Description

Like neofetch, but much faster because written in C. Fastfetch is a [neofetch](https://github.com/dylanaraps/neofetch)-like tool for fetching system information and displaying them in a pretty way. It is written mainly in C, with performance and customizability in mind. It also displays more information (like weather you are using Plasma Wayland Session or X11).

Proposed template that builds latest version:

pkgname=fastfetch
version=1.11.0
revision=1
build_style=cmake
configure_args="-DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTS=OFF -DENABLE_SQLITE3=OFF -DENABLE_RPM=OFF -DENABLE_IMAGEMAGICK6=OFF -DENABLE_LIBCJSON=OFF"
pkgdesc="Like Neofetch, but much faster because written in C"
url="https://github.com/LinusDierheimer/fastfetch"
maintainer="Hatch <redefinirani@gmail.com>"
short_desc="Like Neofetch, but much faster because written in C"
homepage="https://github.com/LinusDierheimer/fastfetch"
license="MIT"
depends="gcc"
distfiles="https://github.com/LinusDierheimer/fastfetch//archive/refs/tags/$version.tar.gz"
checksum="900b3c19f56fca59fd90ae2a033f40fec00185f2a0078dabdcc13a27635dd989"
arch="x86_64 armv7 aarch64"
makedepends="cmake dbus dconf ImageMagick libnm libpulseaudio libxcb libXrandr mesa ocl-icd opencl-headers pciutils Vulkan-Headers vulkan-loader wayland xfconf zlib chafa"

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/issues/38293
