### ISSUE TITLE
PM-Utils does not include script to shut down and Wake Network Manager during suspend. without this, roaming networks can slower

### ISSUE THREAD

**Issue by thomas-t-w** [void-linux/void-packages#4346]
### System

* xuname:  Void 4.19.0_3 x86_64 GenuineIntel notuptodate hold rrmFFFF
  *output of ``xuname`` (part of xtools)*
* package:  pm-utils-1.4.1_8
  *affected package(s) including the version*

### Expected behavior
Network Manager should put interfaces to sleep when machine sleeps and wake them back up when the machine resumes
### Actual behavior
Nothing happens.
### Steps to reproduce the behavior
Select sleep from Desktop or close the lid of a portable. Then wake the machine back up.

I am attaching a corrected 55NetworkManager file based on a Ubuntu bug report that I found. Seems the dbus path changed upstream in NetworkManager. I had to add .txt so github would take it. I guess it was dropped from the package heree because it wasn't working.

[55NetworkManager.txt](https://github.com/void-linux/void-packages/files/2539657/55NetworkManager.txt)

**Comment by Cogitri** [comment]
Hum, I suppose you have tested this with ConsoleKit?

**Comment by ericonr** [comment]
pm-utils package has been removed for a long while now, and issue is inactive.
