### ISSUE TITLE
List of packages failing to build due to a missing or broken Cargo.lock

### ISSUE THREAD

**Issue by paper42** [void-linux/void-packages#43482]
- [x] cargo-auditable #43498
- [x] cargo-auditable-bootstrap #43498
- [x] cargo-c #43484
- [x] cargo-license #43493
- [x] geckodriver
- [x] leftwm
- [x] mandown #43483
- [x] ntdsextract2
- [x] openpgp-ca
- [x] openpgp-card-tools
- [x] riff #43477 
- [x] rsClock
- [x] sandboxfs
- [x] stdm
- [x] wezterm

cc @jcgruenhage

**Comment by tranzystorek-io** [comment]
mandown: #43483

**Comment by tranzystorek-io** [comment]
cargo-license: #43493

**Comment by icp1994** [comment]
Maybe we can do a cleanup by adding a `do_configure` to the cargo build style.

```
do_configure() {
     cargo fetch --target ${RUST_TARGET} ${configure_args}
}
```

From the docs of `cargo-fetch`
> If a `Cargo.lock` file is available, this command will ensure that all of the git dependencies and/or registry dependencies are downloaded and locally available. Subsequent Cargo commands will be able to run offline after a cargo fetch unless the lock file changes.
>
> If the lock file is not available, then this command will generate the lock file before fetching the dependencies.

**Comment by tranzystorek-io** [comment]
This would defeat the point of the lockfile PR, which AFAIU was to make the packages that have lockfile problems **more** prominent.

**Comment by icp1994** [comment]
Oh, okay. I thought we are just (re-)generating the lockfile anyway - fex, bandwhich.

**Comment by jcgruenhage** [comment]
I'd like to rename this issue: In some of these cases, the Cargo.lock file is present, but not up to date. In the case of cargo-auditable` for example, it's just a tiny issue around the version number of itself:

```
diff --git a/Cargo.lock2 b/Cargo.lock
index 00969c9e1c..5caabbda1c 100644
--- a/Cargo.lock2
+++ b/Cargo.lock
@@ -72,7 +72,7 @@ dependencies = [
 
 [[package]]
 name = "cargo-auditable"
-version = "0.6.0"
+version = "0.6.1"
 dependencies = [
  "auditable-info",
  "auditable-serde",

```
