### ISSUE TITLE
Samba-4.0 update required for mpd's smbclient

### ISSUE THREAD

**Issue by maxice8** [void-linux/void-packages#4351]
Someone gotta speed this up or MPD-0.21 otherwise smbclient will be disabled.

see #4350

**Comment by arete** [comment]
I have an samb4 branch working on x64
https://github.com/arete/void-packages/tree/samba4
missing is cross-compiling

Il giorno gio 1 nov 2018 alle ore 21:00 maxice8 <notifications@github.com>
ha scritto:

**Comment by maxice8** [comment]
it is disabled
