### ISSUE TITLE
Mate Desktop Environment: caja keep crashing and restarting over and over, probably related to Marco window manager?

### ISSUE THREAD

**Issue by Le0xFF** [void-linux/void-packages#43562]
### Is this a new report?

Yes

### System Info

Void 6.1.25_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFFFF

### Package(s) Affected

caja-1.26.1_1, marco-1.26.1_1, mate-desktop-1.26.0_1

### Expected behaviour

Mate DE was working fine before latest update, which I did yesterday.
I expect it doesn't crash right after system boot.

### Actual behaviour

After login, icons are not shown, mouse icon is a spinning wheel meaning it's trying to run something over and over again and if I try to open Caja file manager, it shows a window for one second and it crashes after that.

I found someone else on [reddit](https://www.reddit.com/r/voidlinux/comments/12ckmxm/started_having_an_issue_with_mate_this_morning/) having the same problem and the solution I found there works, but not every time.

I'm also attaching `dmesg` output that shows lines related to `caja` and `libmate-desktop` errors, like:

```
[  986.235501] show_signal: 6 callbacks suppressed
[  986.235509] traps: caja[31908] general protection fault ip:7fa47471de61 sp:7ffebdaf0320 error:0 in libmate-desktop-2.so.17.1.4[7fa474716000+29000]
```

[dmesg.log](https://github.com/void-linux/void-packages/files/11293352/dmesg.log)

### Steps to reproduce

1. Install `mate-desktop`, `marco` window manager and `caja` file browser packages.
2. Reboot and login
3. Caja is not working properly, nor the desktop.

**Comment by Le0xFF** [comment]
I think I found bug reports related to the error and what could be done to fix them:
https://lists.debian.org/debian-mate/2023/03/msg00011.html
https://bugs.launchpad.net/ubuntu/+source/caja/+bug/2013138

**Comment by sug0** [comment]
I have the same issue in my system: `Void 6.1.25_1 x86_64 AuthenticAMD uptodate hold rrrmFFFFFFFFFFFF`

**Comment by sug0** [comment]
I have the same issue in my system: `Void 6.1.25_1 x86_64 AuthenticAMD uptodate hold rrrmFFFFFFFFFFFF`
pinging @skmpz since you're the maintaner of `mate-desktop`

**Comment by skmpz** [comment]
seems to be fixed by this commit https://git.mate-desktop.org/mate-desktop/commit/?id=7b379f54a5b09df007f7e84dabbbc5f8ce9381a9 which is part of 1.26.1 release. Will open a PR for update.

**Comment by Le0xFF** [comment]
> can anyone test this #43615 and confirm that issue is fixed?

Yes, the commit fixed the issue for me. No more loops, crashing or dmesg error about caja.
Thank you so much!

**Comment by sug0** [comment]
Also fixed it for me
```
mate-desktop-1.26.1_1                                      : 2023-04-26 18:20 WEST
```
many thanks! @skmpz
