### ISSUE TITLE
Calibre needs `qt6-wayland` to run under Wayland

### ISSUE THREAD

**Issue by hochata** [void-linux/void-packages#43673]
### Is this a new report?

Yes

### System Info

Void 6.1.25_1 x86_64 GenuineIntel uptodate rFFFFF

### Package(s) Affected

calibre-6.13.0_3

### Expected behaviour

Calibre should launch normally

### Actual behaviour

Crashes with the following message
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: vkkhrdisplay, offscreen, vnc, xcb, minimal, eglfs, minimalegl, linuxfb.

Aborted
```

### Steps to reproduce

1. Start a session with a wayland compositor
2. Install Calibre
3. Try to launch it

Install `qt6-wayland` fixes the issue.

**Comment by paper42** [comment]
this is documented in the Wayland section of the handbook and left to the user
