### ISSUE TITLE
Package request: rust-src

### ISSUE THREAD

**Issue by Zapeth** [void-linux/void-packages#43716]
### Package name

rust-src

### Package homepage

https://github.com/rust-lang/rust

### Description

It looks like the [rust](https://github.com/void-linux/void-packages/blob/master/srcpkgs/rust/template) package is missing the std and core source files that would normally be required for language-servers to provide analysis (ie [rust-analyzer](https://github.com/void-linux/void-packages/blob/master/srcpkgs/rust-analyzer/template)).

I'm not sure what configuration steps would be necessary to provide the source files as a separate package, it seems it might be possible to include them in the build with the [`extended`](https://github.com/rust-lang/rust/blob/98c33e47a495fbd7b22bce9ce32f2815991bc414/config.example.toml#L293) and [`tools`](https://github.com/rust-lang/rust/blob/98c33e47a495fbd7b22bce9ce32f2815991bc414/config.example.toml#L303-L312) settings in the rust `config.toml`.

Alpine also provides the source files as a separate package (https://pkgs.alpinelinux.org/package/edge/community/x86_64/rust-src), but I don't know how much can be gleaned from their template, if anything.

Sidenote: `rust-analyzer` currently doesn't work out of the box with the `rust` package due to the missing sources, setting up this package and adding it as an optional dependency to `rust-analyzer` should hopefully fix that.

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

Yes

**Comment by tranzystorek-io** [comment]
The `rust` package is almost exclusively for building void's rust packages, for development purposes you'll want to use rustup. I'm guessing rust-analyzer can be configured to use sources from there.

**Comment by Zapeth** [comment]
> The rust package is almost exclusively for building void's rust packages

Yes, thats why I suggested it as a separate package

> for development purposes you'll want to use rustup

I'd prefer sticking to the distro-packaged variants if possible (rust-dbg and rust-doc were also accepted as separate packages)

**Comment by classabbyamp** [comment]
> The rust package is almost exclusively for building void's rust packages

generally yes, but there is also the case of platforms which rustup doesn't support but void does

**Comment by tranzystorek-io** [comment]
Sounds reasonable, I can prepare a PR then

**Comment by classabbyamp** [comment]
let's just include it in the next rust update

**Comment by tranzystorek-io** [comment]
Pending addition in #44220

**Comment by Zapeth** [comment]
Installed and tested with rust-analyzer, which indeed seems to work out of the box now, thanks
