### ISSUE TITLE
Package request: nwg-look

### ISSUE THREAD

**Issue by tactical-snail** [void-linux/void-packages#43742]
### Package name

nwg-look

### Package homepage

https://github.com/nwg-piotr/nwg-look

### Description

Lxappearance alternative for wlroots compositors (sway, wayfire, river, etc) written in Go.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by shnaps** [comment]
https://github.com/void-linux/void-packages/pull/40111
