### ISSUE TITLE
wine-32bit still reports version 8.3, even though 8.7 is supposedly installed

### ISSUE THREAD

**Issue by camthesaxman** [void-linux/void-packages#43740]
### Is this a new report?

Yes

### System Info

Void 6.1.15_1 x86_64 GenuineIntel notuptodate hold rrrmDFFFFFF

### Package(s) Affected

wine-32bit-8.7_1

### Expected behaviour

wine and wine-32bit are both version 8.7_1, so `wine --version` and `wine64 --version` should both report version 8.7. Because of this, I cannot run winecfg or any programs in wine. The following error appears.
```
wine client error:0: version mismatch 762/761.
Your wine binary was not upgraded correctly,
or you have an older one somewhere in your PATH.
Or maybe the wrong wineserver is still running?
```

### Actual behaviour

`wine --version` (the 32-bit one) reports `wine-8.3` even though I have version 8.7_1 installed. `wine64 --version` does in fact report `wine-8.7`.

### Steps to reproduce

1. Remove both the wine and wine-32bit packages if installed. `xbps-remove wine wine-32bit`
2. Install them again. `xbps-install -S` followed by `xbps-install wine wine-32bit`
3. Attempt to run `winecfg`. You cannot due to a version mismatch.
4. Run `wine --version` and `wine64 --version`. The versions are different somehow.

**Comment by classabbyamp** [comment]
can't repro this
```
$ wine --version
wine-8.7
$ wine64 --version
wine-8.7
$ xbps-query -s wine
[*] wine-8.7_1            Run Microsoft Windows applications
[*] wine-32bit-8.7_1      Run Microsoft Windows applications (32bit)
```

**Comment by camthesaxman** [comment]
After updating wine-libs, it works correctly. Sorry.
