### ISSUE TITLE
puzzles' help files missing.

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#43759]
### Is this a new report?

Yes

### System Info

Void 6.0.12_1 x86_64-musl GenuineIntel uptodate rFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

### Package(s) Affected

puzzles-20230404.2499eb4_1

### Expected behaviour

Opening the help of a puzzle from the package should display the help.

### Actual behaviour

An error message: "Help file is not installed"

### Steps to reproduce

1. Install puzzles
2. Open any puzzle, for example puzzles-solo.
3. Go to help -> contents

**Comment by icp1994** [comment]
Yeah and the icons too. Updated my PR to include them.
