### ISSUE TITLE
gns3 : could not start vpcs

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#43766]
### Is this a new report?

Yes

### System Info

Void 6.1.25_1 x86_64 GenuineIntel uptodate rrrmFFFF

### Package(s) Affected

ubridge

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

nop

### Expected behaviour

vpcs to start in gns3 without error

### Actual behaviour

When I try to start a vpcs, i get that error
![vpcs](https://user-images.githubusercontent.com/14223657/236568684-7d698128-5b6e-476d-b9d8-f1d20fe8af35.png)

### Steps to reproduce

1. install gns3-gui, gns3-server, ubridge, vpcs
2. run gns3
3. add a vpcs
4. start it

**Comment by eoli3n** [comment]
Running vpcs, directly in a shell works :

```bash
$ vpcs

Welcome to Virtual PC Simulator, version 0.8b
Dedicated to Daling.
Build time: Aug 21 2017 11:25:22
Copyright (c) 2007-2015, Paul Meng (mirnshi@gmail.com)
All rights reserved.

VPCS is free software, distributed under the terms of the "BSD" licence.
Source code and license can be found at vpcs.sf.net.
For more information, please visit wiki.freecode.com.cn.

Press '?' to get help.

VPCS[1]> 
```

**Comment by eoli3n** [comment]
[Official documentation](https://docs.gns3.com/docs/getting-started/installation/linux) asks to add user to the ``ubridge`` group.
ubridge is installed but no ubridge group exists on my system.

```
$ xbps-query ubridge
architecture: x86_64
filename-sha256: 4011c4a1e278371ccd7b9e3a259b37e4065d06d693618334980e3811fee6538d
filename-size: 33KB
homepage: https://github.com/GNS3/ubridge
install-date: 2023-05-05 22:45 CEST
install-script: 711B
installed_size: 80KB
license: GPL-3.0-or-later
maintainer: Cameron Nemo <cam@nohom.org>
metafile-sha256: 211fdfdafbde75023efcb6f447d6e573a07d8697399a387e9a6bd5bb4c758bbc
pkgname: ubridge
pkgver: ubridge-0.9.18_2
repository: https://repo-default.voidlinux.org/current
run_depends:
	glibc>=2.36_1
	iniparser>=4.1_1
	libpcap>=1.1.1_1
shlib-requires:
	libc.so.6
	libiniparser.so.1
	libpcap.so.1
short_desc: Bridge for UDP tunnels, Ethernet, TAP and VMnet interfaces
source-revisions: ubridge:f50f428fbe
state: installed

$ grep ubridge /etc/group

$
```

**Comment by sgn** [comment]
Does it work if you:
```
setcap cap_net_admin,cap_net_raw=ep /usr/bin/ubridge
```

**Comment by eoli3n** [comment]
Tried and nop, same error when running vpcs
