### ISSUE TITLE
mysql_install_db does not know the correct MariaDB installation directory

### ISSUE THREAD

**Issue by llunacb** [void-linux/void-packages#43777]
### Is this a new report?

Yes

### System Info

Void 6.1.25_1 x86_64 AuthenticAMD notuptodate rrDDFFFF

### Package(s) Affected

mariadb-10.5.10_4

### Expected behaviour

A database can be successfully created without passing a `--basedir` option.

### Actual behaviour

The command gives an error:

`FATAL ERROR: Could not find //share/mysql/fill_help_tables.sql`

Considering what the path searched for looks like, beginning with `//share`, it would seem that the `/usr` part of the path has been removed somehow, maybe due to the way the program is compiled. The error can be fixed by specifying a `--basedir` option with a value of `/usr`.

### Steps to reproduce

```
$ mysql_install_db --datadir=/tmp/mariadb_test

FATAL ERROR: Could not find //share/mysql/fill_help_tables.sql
(...)

$ mysql_install_db --datadir=/tmp/mariadb_test --basedir=/usr

Installing MariaDB/MySQL system tables in '/tmp/mariadb_test' ...
(...)
```

**Comment by classabbyamp** [comment]
can you [test](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#testing-pull-requests) #43794 ?

**Comment by llunacb** [comment]
> can you [test](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#testing-pull-requests) #43794 ?

it works, thanks!
