### ISSUE TITLE
docker-cli package miss dockerd runit service

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#43780]
### Is this a new report?

Yes

### System Info

Void 6.1.25_1 x86_64 GenuineIntel uptodate rrrmFFFFF

### Package(s) Affected

docker-cli-23.0.5_1

### Expected behaviour

Beeing able to start dockerd, without creating runit service myself.

### Actual behaviour

No dockerd, so docker is not working out of the box

### Steps to reproduce

1. xbps-install -S docker
2. sudo sv start dockerd
3. xbps-query -f docker-cli | grep dockerd
```
/usr/share/man/man8/dockerd.8
```

**Comment by paper42** [comment]
The issue here is only that the dockerd manpage is in the docker-cli package. dockerd is provided by moby

**Comment by eoli3n** [comment]
ok thanks
