### ISSUE TITLE
Package request: Nvidia Open source drivers

### ISSUE THREAD

**Issue by aadi58002** [void-linux/void-packages#43804]
### Package name

nvidia-open

### Package homepage

https://github.com/NVIDIA/open-gpu-kernel-modules

### Description

Offical Nvidia open source drivers.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
previous discussion https://github.com/void-linux/void-packages/issues/37123

**Comment by xHyroM** [comment]
What about now? They seems pushing it.
