### ISSUE TITLE
Qt applications stop reacting to mouse events on big endian systems

### ISSUE THREAD

**Issue by Vogtinator** [void-linux/void-packages#43811]
To fix https://bugreports.qt.io/browse/QTBUG-112526, we also applied your qtbase patch `big-endian-scroll.patch` to openSUSE.
However, we got a bug report that this broke popup menus: When e.g. opening a context menu, the application completely stops reacting to mouse events (internally reported as https://bugzilla.suse.com/show_bug.cgi?id=1211024).

This is because it's missing endianess conversion in `QXcbConnection::xi2SetMouseGrabEnabled`.

You might want to add the missing part manually:

```
@@ -826,6 +828,8 @@ bool QXcbConnection::xi2SetMouseGrabEnabled(xcb_window_t w, bool grab)
                 | XCB_INPUT_XI_EVENT_MASK_TOUCH_UPDATE
                 | XCB_INPUT_XI_EVENT_MASK_TOUCH_END;

+        mask = qToLittleEndian(mask);
+
         for (int id : qAsConst(m_xiMasterPointerIds)) {
             xcb_generic_error_t *error = nullptr;
             auto cookie = xcb_input_xi_grab_device(xcb_connection(), w, XCB_CURRENT_TIME, XCB_CURSOR_NONE, id,

```

or grab the updated patch:

https://build.opensuse.org/package/view_file/home:Vogtinator:qt5.15/libqt5-qtbase/big-endian-scroll.patch?expand=1

CC @q66

**Comment by classabbyamp** [comment]
void-ppc is no longer being developed by q66

**Comment by Vogtinator** [comment]
Then please reassign to someone else or remove the offending patch?

**Comment by classabbyamp** [comment]
sorry I more meant it's not being developed at all. it was an unofficial port.

**Comment by Vogtinator** [comment]
Yeah, in that case you should probably remove the patch.
