### ISSUE TITLE
Package update request: senpai 0.2.0

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#43860]
### Package name

senpai

### Package homepage

https://git.sr.ht/~taiite/senpai/refs/v0.2.0

### Description

Senpai 0.2.0 is out

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by eoli3n** [comment]
@kedodrill

**Comment by classabbyamp** [comment]
> Don't request an update of a package, We have a script for that: https://repo-default.voidlinux.org/void-updates/void-updates.txt

**Comment by kedodrill** [comment]
@eoli3n another option would be to email the package maintainer. I don't think I'm on that list, at least a quick search didn't result in anything. I don't use senpai enough to know there was an update, but I'll bump it here shortly. :)

**Comment by classabbyamp** [comment]
you're not in today's void-updates because senpai was already updated, if you go to an older version, like https://repo-default.voidlinux.org/void-updates/void-updates_2023-05-08.txt, it's there

**Comment by kedodrill** [comment]
> you're not in today's void-updates because senpai was already updated, if you go to an older version, like https://repo-default.voidlinux.org/void-updates/void-updates_2023-05-08.txt, it's there

ahhh okay that makes sense. I completely missed that it was already updated lol
