### ISSUE TITLE
Package request: hwdata

### ISSUE THREAD

**Issue by aadi58002** [void-linux/void-packages#43887]
### Package name

hwdata

### Package homepage

https://github.com/vcrhonek/hwdata

### Description

It replaces the utility from the hwids package which is no longer being actively maintained.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by icp1994** [comment]
It's already there, as [hwids](https://github.com/void-linux/void-packages/blob/master/srcpkgs/hwids/template).

**Comment by aadi58002** [comment]
> It's already there, as [hwids](https://github.com/void-linux/void-packages/blob/master/srcpkgs/hwids/template).
Why is the naming wrong is any rest for it?

**Comment by classabbyamp** [comment]
renaming a package is kinda messy
