### ISSUE TITLE
Cannot see cursor on fresh install

### ISSUE THREAD

**Issue by saltnpepper97** [void-linux/void-packages#43891]
Hello, 

I am very enthusiastic about void linuz. However, there is n issue hindering me from being able to use it at the moment.

I have ran through a fresh install several times before.

However recently, I upgraded my graphics card, and now when I fresh install I am unable to use the cursor.
I have been on Arch Linux for the time being until a fix arises.

I am no professional, but something tells me it has to do with the kernel version shipping currently with void linux (6.1) and the mesa driver version (22.3.5) having some sort of issue with each other.

PC Specs:
Mobo: MSI X570 MEG ACE
CPU: AMD Ryzen 9 5900x
GPU: AMD Radeon 7900 xtx
RAM: 32gb DDR4

**Comment by Clos3y** [comment]
> PC Specs: Mobo: MSI X570 MEG ACE CPU: AMD Ryzen 9 5900x GPU: AMD Radeon 7900 xtx RAM: 32gb DDR4

[Seems to be well documented issues](https://www.google.com/search?q=cursor+not+showing+7900xtx+linux) with the 7900 XTX not showing the cursor, for which the broad solutions seem to be a) use Wayland, or b) [turn on software rendered cursor in xorg.conf](https://www.x.org/archive/X11R6.8.0/doc/ati5.html#20).
