### ISSUE TITLE
Package Request: FreeIPA

### ISSUE THREAD

**Issue by ArmedAviator** [void-linux/void-packages#439]
FreeIPA has both a server and a client for remote authentication/single login networks.

https://www.freeipa.org/page/Downloads

**Comment by CameronNemo** [comment]
I tried to package 389-ds-base but didn't get very far, seems it needs some patching. Can't say I'm up for the challenge of packaging and integrating this behemoth... but here is [my branch](https://github.com/CameronNemo/void-packages/commit/52dec3cb1761ade9e68970bf50c5947098522e79).
