### ISSUE TITLE
How to build debug packages with `xbps-src`?

### ISSUE THREAD

**Issue by Mek101** [void-linux/void-packages#43985]
As per title

**Comment by balejk** [comment]
See the `-g` switch

**Comment by Mek101** [comment]
> See the `-g` switch

Does it also disable optimizations?

**Comment by mhmdanas** [comment]
I'm pretty sure it doesn't disable optimizations, no.

**Comment by Duncaen** [comment]
No, its how the build server builds packages, you can set `XBPS_DEBUG_PKGS=yes` in a [config file](https://github.com/void-linux/void-packages#configuration) to enable it by default.
