### ISSUE TITLE
Package request: pdfsizeopt

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#44081]
### Package name

pdfsizeopt

### Package homepage

https://github.com/pts/pdfsizeopt

### Description

pdfsizeopt is a program for converting large PDF files to small ones, without decreasing visual quality or removing interactive features (such as hyperlinks)

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by sgn** [comment]
> This is a Python 2.x script, it works with Python 2.4, 2.5, 2.6 and 2.7.

**Comment by classabbyamp** [comment]
We don't need any more py2 packages as we try to remove them
