### ISSUE TITLE
Nautilus refresh bug

### ISSUE THREAD

**Issue by krummm** [void-linux/void-packages#44089]
### Is this a new report?

Yes

### System Info

Void 6.1.29_1 x86_64 GenuineIntel uptodate F

### Package(s) Affected

nautilus-44.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://gitlab.gnome.org/GNOME/nautilus/-/issues/2941

### Expected behaviour

Upon deleting selected files, Nautilus should refresh to reflect the correct state of the current directory.

### Actual behaviour

Upon deleting selected files in Nautilus, an equivalent amount of folders will disappear. The files that were chosen and moved to the trash bin will still appear in the directory, if one were to undo this operation the deleted files would appear to duplicate. Only upon a manual refresh will it update to reflect the correct state of the directory.

### Steps to reproduce

1. Create multiple files in a directory that is a parent of other directories
2. Drag to select the newly created files
3. Delete newly created files via either DEL key or context menu

**Comment by krummm** [comment]
A video example of this behavior can be found on the upstream URL listed here.

**Comment by oreo639** [comment]
It does work when building gtk4 with this patch:
https://gitlab.gnome.org/GNOME/gtk/-/commit/4a187d7f1d0f1aea8a5697a50299594ef523faf7

It should also get fixed when gtk4 4.10.4 releases.

**Comment by krummm** [comment]
Closing because 44097 was merged.
