### ISSUE TITLE
Wezterm Unable to load a font monospace

### ISSUE THREAD

**Issue by Sichelmondprinz** [void-linux/void-packages#44193]
### Is this a new report?

Yes

### System Info

Void 6.1.30_1 x86_64 AuthenticAMD uptodate rrFF

### Package(s) Affected

wezterm-20230408_1

### Expected behaviour

If I execute a command like `sudo` that requests a password input with the lock icon next to it, no error should happen and the program should continue like expected.

### Actual behaviour

If I execute a command like `sudo` that requests a password input with the lock icon next to it, a new wezterm window opens with the following error message:

```
Unable to load a font matching one of your font_rules:
wezterm.font('monospace', {weight="Regular", stretch='Normal', style=Normal}).
Fallback(s) are being used instead, and the terminal may not render as
intended. See https://wezfurlong.org/wezterm/config/fonts.html for more
information
```

I can simply close the window and it won't open again for the rest of the current wezterm session. But it'll open again if I close it and re-open it.

### Steps to reproduce

1. Start wezterm in a relatively clean wayland session
2. Run a command with sudo or anything other that shows a password prompt with a lock icon
3. Error window opens

**Comment by Sichelmondprinz** [comment]
My guess is that it's related to this patch:
https://github.com/void-linux/void-packages/blob/master/srcpkgs/wezterm/patches/monospace.patch

and it not finding any font under that name. I temporarily fixed it for my system by replacing "monospace" in that patch with a font present on my system.

"monospace" might get installed by some xorg package, which is missing since my system is wayland based instead.

**Comment by classabbyamp** [comment]
monospace is the alias for whatever default monospace font there is for fontconfig. Idk how wayland and fontconfig interact

**Comment by Sichelmondprinz** [comment]
It seems like manually installing `dejavu-fonts-ttf` fixed this issue.
Making sure there is at least one font available under the name "monospace" when installing/starting wezterm might be a good idea.

Until then I'll close this issue and leave the answer here for other people having the same problem!
