### ISSUE TITLE
Package request: emacs with GUI support on arm7l

### ISSUE THREAD

**Issue by jindamvani** [void-linux/void-packages#44190]
### Package name

emacs

### Package homepage

https://www.gnu.org/software/emacs/

### Description

* An extensible, customizable, [free/libre](https://www.gnu.org/philosophy/free-sw.html) text editor — and more.
* Kindly note,  at present only i686 & x86_64.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by jindamvani** [comment]
> https://github.com/void-linux/void-packages/blob/45929173b0b2bc8875d01854e3b9abe6515e015b/srcpkgs/emacs/template#L31
> 
> arm arches are cross-compiled by default, so you > would need to compile it yourself.

* I tried once, enlightment [de]. It downloaded tons of packages including dev & almost an hour.
* No remote possibilty about availability in repo?

> That said, I would not recommend compiling the package locally in termux/proot-distro. If it even worked in the first place, it would probably take forever and/or cook your phone

**Comment by classabbyamp** [comment]
> * No remote possibilty about availability in repo?

there is no infrastructure set up to compile things natively for arm at the current time

**Comment by jindamvani** [comment]
> > * No remote possibilty about availability in repo?
> 
> there is no infrastructure set up to compile things natively for arm at the current time

aha..... reasonable
