### ISSUE TITLE
qbittorrent-nox WebUI doesn't work

### ISSUE THREAD

**Issue by jeromecst** [void-linux/void-packages#44209]
### Is this a new report?

Yes

### System Info

Void 6.4.0-rc2 x86_64 GenuineIntel notuptodate rFFFFFF

### Package(s) Affected

qbittorrent-nox-4.5.2_1

### Expected behaviour

After starting `qbittorrent-nox`, connecting to the WebUI shows the actual login page

### Actual behaviour

After starting `qbittorrent-nox`, connecting to the WebUI doesn't show the login page, instead the browser downloads a file with a random name, ie `30p0R8xi`, `3bXIUMCi` or `72pPVr1o`

### Steps to reproduce

1. start `qbittorrent-nox` in a terminal
2. open the link localhost:XXXX on the browser
3. notice that the login page never appears

**Comment by sgn** [comment]
Not reproducible.
![image](https://github.com/void-linux/void-packages/assets/42673067/b585a553-b562-4ff7-9602-4bdd5104c9d6)
