### ISSUE TITLE
Package request: font-manager

### ISSUE THREAD

**Issue by maljos** [void-linux/void-packages#44202]
### Package name

font-manager

### Package homepage

https://github.com/FontManager/font-manager

### Description

It has all the information of the fonts installed in the system, such as 3 types of previews, place of installation of the fonts, very complete. Additionally it looks great aesthetically

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by chrysos349** [comment]
@maljos `fontmanager` is in the repo!

**Comment by maljos** [comment]
Ok, no problem. Thanks for you request. You have a happy day
