### ISSUE TITLE
Package Request: Jami

### ISSUE THREAD

**Issue by Seeder101** [void-linux/void-packages#4420]
Ring P2P Communication Tool. 
it's an open source gnu project software. geared toward decentralization with P2P chat and voice system.
you can take a look at the project page : https://jami.net

Thank you in advance.

**Comment by DBLouis** [comment]
This is now called [Jami](https://jami.net/)
I would like to have this too

**Comment by Seeder101** [comment]
> This is now called [Jami](https://jami.net/)
> I would like to have this too

Thanks for the update, I updated the link

**Comment by dextruct0r** [comment]
Yes it's a very good app that it's multi arch on some dristro's but it's tricky to manually compile, so if you could add officially to the repo I and some others would  be really grateful.

**Comment by avoidr** [comment]
Here is the code: https://git.jami.net/savoirfairelinux
This repo: https://git.jami.net/savoirfairelinux/ring-project
This repo pulls the other repos as git submodules. But the releases are all only Android, and I have not actually found any code in the release tarballs. And the releases in the individual subrepos are all years old. So I don't know if that even qualifies.

Here is what Arch is doing:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/jami-daemon
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/libjamiclient
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/jami-gnome

**Comment by Mirodin** [comment]
I too would love to see this on Void, been using it on Android for over a year now.

**Comment by autoteelar** [comment]
me too

**Comment by mika-nl** [comment]
Love to see Jami in Void

**Comment by mika-nl** [comment]
https://git.jami.net/savoirfairelinux/jami-project

**Comment by jgarte** [comment]
> I too would love to see this on Void, been using it on Android for over a year now.

How has it worked for you? Any bugs?

**Comment by Idesmi** [comment]
I would love to have this, but it's hard to package for me.

**Comment by ericonr** [comment]
I might try packaging this over my holidays, assuming they have started making proper releases. Feel free to ping me for reviewing a PR, if anyone makes one.

**Comment by chloris-pale-green** [comment]
Well, it would be about time Void Linux gets something like this in the repos. As [qTox](https://github.com/qTox/qTox) is not actively developed anymore, and getting one's own videoconferencing infrastructure is seriously complicated (compared to chat), we're kinda running out of options for private comms.

I'll give packaging Jami another shot, but expect help requests. My previous attempt was unsuccessful. Let's get it done this time. 😉

**Comment by chloris-pale-green** [comment]
I've almost successfully packaged `jami-daemon`. The build documentation is quite abysmal. I've ripped off most of the build process from Arch. Dependencies compile successfully, the configure step is successful (except some complaining about `dbus`, which can be disabled, if needed), but the `jami-daemon` itself fails to compile. We don't have `libnatpmp` in the repos, if that's desired.

The compile error seems to be about class member naming:

```
=> jami-daemon-20230601_1: running do_build ...
make  all-recursive
make[1]: Entering directory '/builddir/jami-daemon-20230601'
Making all in src
make[2]: Entering directory '/builddir/jami-daemon-20230601/src'
  CXX      buildinfo.lo
  CXX      conference.lo
  CXX      conference_protocol.lo
  CXX      account_factory.lo
  CXX      call_factory.lo
  CXX      preferences.lo
  CXX      manager.lo
  CXX      call.lo
  CXX      gittransport.lo
In file included from /builddir/jami-daemon-20230601/src/media/video/video_input.h:27,
                 from client/videomanager.h:35,
                 from preferences.cpp:58:
/builddir/jami-daemon-20230601/src/media/media_stream.h: In constructor 'jami::MediaStream::MediaStream(const std::string&, AVCodecContext*, int64_t)':
/builddir/jami-daemon-20230601/src/media/media_stream.h:115:33: error: 'AVCodecContext' {aka 'struct AVCodecContext'} has no member named 'ch_layout'; did you mean 'channel_layout'?
  115 |                 nbChannels = c->ch_layout.nb_channels;
      |                                 ^~~~~~~~~
      |                                 channel_layout
/builddir/jami-daemon-20230601/src/media/media_stream.h: In member function 'void jami::MediaStream::update(AVFrame*)':
/builddir/jami-daemon-20230601/src/media/media_stream.h:147:29: error: 'AVFrame' {aka 'struct AVFrame'} has no member named 'ch_layout'; did you mean 'channel_layout'?
  147 |             nbChannels = f->ch_layout.nb_channels;
      |                             ^~~~~~~~~
      |                             channel_layout
In file included from /builddir/jami-daemon-20230601/src/media/media_encoder.h:36,
                 from /builddir/jami-daemon-20230601/src/media/media_recorder.h:27,
                 from /builddir/jami-daemon-20230601/src/media/recordable.h:25,
                 from call.h:32,
                 from call_factory.h:30,
                 from call_factory.cpp:23:
/builddir/jami-daemon-20230601/src/media/media_stream.h: In constructor 'jami::MediaStream::MediaStream(const std::string&, AVCodecContext*, int64_t)':
/builddir/jami-daemon-20230601/src/media/media_stream.h:115:33: error: 'AVCodecContext' {aka 'struct AVCodecContext'} has no member named 'ch_layout'; did you mean 'channel_layout'?
  115 |                 nbChannels = c->ch_layout.nb_channels;
      |                                 ^~~~~~~~~
      |                                 channel_layout
/builddir/jami-daemon-20230601/src/media/media_stream.h: In member function 'void jami::MediaStream::update(AVFrame*)':
/builddir/jami-daemon-20230601/src/media/media_stream.h:147:29: error: 'AVFrame' {aka 'struct AVFrame'} has no member named 'ch_layout'; did you mean 'channel_layout'?
  147 |             nbChannels = f->ch_layout.nb_channels;
      |                             ^~~~~~~~~
      |                             channel_layout
In file included from /builddir/jami-daemon-20230601/src/media/media_encoder.h:36,
                 from /builddir/jami-daemon-20230601/src/media/media_recorder.h:27,
                 from /builddir/jami-daemon-20230601/src/media/recordable.h:25,
                 from call.h:32,
                 from call_factory.h:30,
                 from manager.h:35,
                 from manager.cpp:35:
/builddir/jami-daemon-20230601/src/media/media_stream.h: In constructor 'jami::MediaStream::MediaStream(const std::string&, AVCodecContext*, int64_t)':
/builddir/jami-daemon-20230601/src/media/media_stream.h:115:33: error: 'AVCodecContext' {aka 'struct AVCodecContext'} has no member named 'ch_layout'; did you mean 'channel_layout'?
  115 |                 nbChannels = c->ch_layout.nb_channels;
      |                                 ^~~~~~~~~
      |                                 channel_layout
/builddir/jami-daemon-20230601/src/media/media_stream.h: In member function 'void jami::MediaStream::update(AVFrame*)':
/builddir/jami-daemon-20230601/src/media/media_stream.h:147:29: error: 'AVFrame' {aka 'struct AVFrame'} has no member named 'ch_layout'; did you mean 'channel_layout'?
  147 |             nbChannels = f->ch_layout.nb_channels;
      |                             ^~~~~~~~~
      |                             channel_layout

```

And so on... Any suggestions? Is is sloppy code or does one of our libraries have different variable names in it than on another distro (`ch_layout` vs `channel_layout`)? We don't need to patch the source files to rename them, right? If that's the case, `sed` would probably do the job.

**Comment by chloris-pale-green** [comment]
Renaming  `ch_layout` to `channel_layout` in the code does not work. There seem to be different versions of the `ffmpeg` library with different APIs.

We currently have version 4.4 with [this API](https://ffmpeg.org/doxygen/4.4/structAVCodecContext.html). Struct `AVCodecContext` has a field `uint64_t channel_layout`.

[The `trunk` version](https://ffmpeg.org/doxygen/trunk/structAVCodecContext.html) has another kind of a field: `AVChannelLayout ch_layout`, which seems to be what the Jami code expects. It seems to first appear in `ffmpeg` 5.1. Perhaps an older version of Jami would build ...

**Comment by HanoJing** [comment]
Hey all, I have written a guide on how to build Jami on Void Linux:
https://git.jami.net/savoirfairelinux/jami-client-qt/-/issues/1327

It takes like 20-30 minutes to compile on my machine, but I hope this guide helps some of you if you have enough processing power available and don't want to wait till it's packaged.

**Comment by Chocimier** [comment]
jami-client-qt got tagged as stable few times by now, and it contains server part. I would be fine with merging it.
