### ISSUE TITLE
Package request: FreeCAD aarch64

### ISSUE THREAD

**Issue by NXTler** [void-linux/void-packages#44228]
### Package name

freecad

### Package homepage

https://freecadweb.org/

### Description

FreeCAD is an open source cad Software. It has many features and is great for quickly creating professional parts.
It's also used by many Raspberry Pis (or other mini computers) for CNC related tasks.

This Request is about having FreeCAD as an aarch64 package.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by paper42** [comment]
hdf5 (a dependency of freecad) does not cross compile, you can compile it natively on your own if you want to, but it won't get to repositories unless someone fixes the hdf5 cross build
