### ISSUE TITLE
Package request: font-latinmodern-otf

### ISSUE THREAD

**Issue by eoli3n** [void-linux/void-packages#44259]
### Package name

font-latinmodern-otf

### Package homepage

https://www.gust.org.pl/projects/e-foundry/latin-modern

### Description

https://www.gust.org.pl/projects/e-foundry/latin-modern/download

I'm migrating my moderncv from latex to typst, to be able to get rid of heavy latex packages.
That font is used by the moderncv template, but is packaged in a latex package.
Useful then to package it system-wide.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
> New fonts may be accepted if they provide value beyond aesthetics (e.g. they contain glyphs for a script missing in already packaged fonts).

**Comment by mhmdanas** [comment]
@classabbyamp

@eoli3n mentioned:

> That font is used by the moderncv template, but is packaged in a latex package.

And indeed:

```console
$ xlocate latinmodern
texlive-core-2021.58710_1  /usr/share/texmf-dist/fonts/opentype/public/lm-math/latinmodern-math.otf
texlive-core-2021.58710_1  /usr/share/texmf-dist/tex/context/fonts/mkiv/type-imp-latinmodern.mkiv
```

Since the font is already distributed as part of another package, I think it's okay to package it separately.

**Comment by classabbyamp** [comment]
and have the font in the repos twice?

**Comment by mhmdanas** [comment]
Can't we have texlive-core depend on font-latinmodern-otf and then symlink the font to the necessary location if needed?

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/73a621204c4bdeb501d8c7cdeec7c8e911099ccc
