### ISSUE TITLE
Document the "no firefox fork package" policy

### ISSUE THREAD

**Issue by vincele** [void-linux/void-packages#44281]
I was searching for librewolf to try it, and after a while found the bunch of closed / won't fix issues.

After reading a few of them and seeing the irritation they seem to cause, I then searched into the FAQ to see if this fact is documented in there and did not find anything.

I think this policy (looks like it's not only for firefox) could be documented somewhere, to help alleviate the duplicated issues and questions. And the invitation to use flatpacks instead, could also be explained at the same place.

FYI: I tried the nix package manager on top of void, and its librewolf is usable. Too bad the nix void package is not working on musl x86_64 void (see #37382).

Did I miss something ?

**Comment by mhmdanas** [comment]
This is mentioned in [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/aa13922f5c0aa55184c364c1bbf7075b3b26c0a9/CONTRIBUTING.md):

> Browser forks, including those based on Chromium and Firefox, are generally not accepted.
Such forks require heavy patching, maintenance and hours of build time.

**Comment by mhmdanas** [comment]
Perhaps, but that's where the package requirements happen to be for now.

**Comment by mhmdanas** [comment]
Also, note that the user is pointed to the package requirements in the package request template anyway, so this is a non-issue in that context.
