### ISSUE TITLE
librepcb missing qt5-plugin-sqlite dependency

### ISSUE THREAD

**Issue by ii8** [void-linux/void-packages#44294]
### Is this a new report?

Yes

### System Info

Void 6.1.29_1 x86_64-musl AuthenticAMD notuptodate rFF

### Package(s) Affected

librepcb-0.1.5_1

### Expected behaviour

It should launch without having to separately install qt5-plugin-sqlite.

### Actual behaviour

Newly installed the program reports:
```
[DEBUG-MSG] Load workspace library database... (:0)
[ WARNING ] QSqlDatabase: QSQLITE driver not loaded (:0)
[ WARNING ] QSqlDatabase: available drivers:  (:0)
[EXCEPTION] Invalid database: "/home/murray/LibrePCB-Workspace/v0.1/libraries/cache_v2.sqlite" (sqlitedatabase.cpp:71)
```
and does not launch.

### Steps to reproduce

```
xbps-remove qt5-plugin-sqlite
xbps-install -S librepcb
librepcb
```

**Comment by mhmdanas** [comment]
https://github.com/void-linux/void-packages/pull/44320
