### ISSUE TITLE
Package Request: mitmproxy

### ISSUE THREAD

**Issue by chinarulezzz** [void-linux/void-packages#4432]
A swiss-army knife for debugging, testing, privacy measurements, and penetration testing. It can be used to intercept, inspect, modify and replay web traffic such as HTTP/1, HTTP/2, WebSockets, or any other SSL/TLS-protected protocols

---
Would be nice to have it in repos.
Thanks for considering :)

**Comment by ndowens** [comment]
I will try to work on this one

**Comment by ndowens** [comment]
Following python packages are needed to package

- [ ] brotlipy>=0.7.0,<0.8
- [ ]  h2>=3.0.1,<4
- [ ] hyperframe>=5.1.0,<6
- [ ] ldap3>=2.5,<2.6
- [ ] certifi>=2015.11.20.1
- [ ] pyOpenSSL>=17.5,<18.1
- [ ] pyparsing>=2.1.3,<2.4
- [ ] pyperclip>=1.6.0,<1.8 
- [ ] sortedcontainers>=1.5.4,<2.1
- [ ] wsproto>=0.12.0,<0.13.0

**Comment by chinarulezzz** [comment]
@ndowens Cool. Thank you very much!

**Comment by maxice8** [comment]
ping

**Comment by mcbloch** [comment]
pong

**Comment by mcbloch** [comment]
> Issues become stale 90 days after last activity and are closed 14 days after that. If this issue is still relevant bump it or assign it.

Bump
