### ISSUE TITLE
Outdated dependency libtiff.so.5 in pacakage wps-office

### ISSUE THREAD

**Issue by aritra1911** [void-linux/void-packages#44335]
### Is this a new report?

Yes

### System Info

Void 6.1.31_1 x86_64 GenuineIntel uptodate rrrmFFFF

### Package(s) Affected

wps-office-11.1.0.10920_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No

### Expected behaviour

```
   SONAME: libtiff.so.6 <-> tiff-4.5.0_1
```

libtiff.so.6 is shipped with tiff-4.5.0_1 which should be the one that gets pickup up instead of libtiff.so.5

### Actual behaviour

```
   SONAME: libtiff.so.5 <-> UNKNOWN PKG PLEASE FIX!
```

libtiff.so.5 is pickup up instead which doesn't even exist.

### Steps to reproduce

```sh
$ git checkout b6333d75da
$ ./xbps-src pkg wps-office
```

**Comment by classabbyamp** [comment]
> `$ git checkout b6333d75da`

this is why. you're checking out a commit made prior to when tiff was updated to 4.5.0 (when `libtiff.so.5` became `libtiff.so.6`)

**Comment by aritra1911** [comment]
I believe https://github.com/void-linux/void-packages/commit/b6333d75da484ac64ea84f0c47af6ca54dbfde98 was committed 9 hours ago.

**Comment by classabbyamp** [comment]
because that package does not compile wps office itself (it downloads binaries), we can't do anything about it linking to the old libtiff version

**Comment by aritra1911** [comment]
Maybe someone needs to update it to the latest version which is 11.1.0.11698.

**Comment by paper42** [comment]
maybe a controversial opinion, but I think we shouldn't have packages like this in void-packages at all, we have to rely on them not linking stuff we are moving forward which doesn't always happen. Then this package also doesn't seem well maintained - last void-packages update was in February 2022 and it is packaged as a flatpak on flathub which is much better suited for dealing with ugly proprietary stuff that requires specific versions of libraries than us.

cc @mobinmob - the maintainer

**Comment by mobinmob** [comment]
> Maybe someone needs to update it to the latest version which is 11.1.0.11698. Not sure if that fixes anything.

It does not.

**Comment by sgn** [comment]
Hm, we can provide a libtiff5 package for this, no?

**Comment by alfabuster** [comment]
Have same error. If change in file shlibs

`libtiff.so.6 tiff-4.5.0_1` to `libtiff.so.**5** tiff-4.5.0_1`

Another error

```
=> ERROR: wps-office-11.1.0.10920_2: /usr/lib64 must not exist.
=> ERROR: wps-office-11.1.0.10920_2: cannot continue with installation!
```

Anyone knows how to fix this?

**Comment by alfabuster** [comment]
> I would try `./xbps-src zap` and `./xbps-src binary-bootstrap` again.

Unfortunately, this change nothing.  Same error.

```
 SONAME: libtiff.so.5 <-> UNKNOWN PKG PLEASE FIX!

=> ERROR: wps-office-11.1.0.10920_2: cannot guess required shlibs, aborting!
```

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/pull/47971
