### ISSUE TITLE
Package Request: ngrok

### ISSUE THREAD

**Issue by chinarulezzz** [void-linux/void-packages#4433]
[ngrok](https://ngrok.com/docs) -- secure introspectable tunnels to localhost.

Also would be nice to have it.
Thanks.

**Comment by knusbaum** [comment]
ngrok appears to be a closed-source program distributed as a binary blob.

I'm not a lawyer, but from my reading of their terms of service I don't think void can distribute this from its repository, and even if it could, I don't know that it's a good fit (being a blob).

Anyway, there is a working statically-linked executable available for download on their website.
(I'm not a maintainer, just a friendly contributor)

**Comment by chinarulezzz** [comment]
>ngrok appears to be a closed-source program distributed as a binary blob.

https://github.com/inconshreveable/ngrok

I assume you're talking about ngrok2

**Comment by knusbaum** [comment]
Oh, my mistake.

I followed your link to the ngrok website, and there is no link to the github from there, nor mention of it being an open-source program. In addition, there's no license information anywhere on the site except in the terms of service, which stated that materials obtained through the site were copyrighted and could not be copied or redistributed.
