### ISSUE TITLE
Kdenlive doesn't launch

### ISSUE THREAD

**Issue by motorto** [void-linux/void-packages#44343]
### Is this a new report?

Yes

### System Info

Void 6.3.6_1 x86_64 GenuineIntel uptodate rrFFFF

### Package(s) Affected

kdenlive-23.04.0_1

### Expected behaviour

NA

### Actual behaviour

Package doesn't launch.

```
Missing MLT module: glaxnimate
required to load Lottie animations
```

### Steps to reproduce

1. `xbps-install -S kdenlive`
2. run app

**Comment by Andonome** [comment]
Also `kdenlive` requires `mediainfo` to run, but does not pull it as a dependency.

**Comment by mhmdanas** [comment]
Related: https://github.com/void-linux/void-packages/issues/40689 #41792

**Comment by classabbyamp** [comment]
all the missing MLT modules are optional

when starting, I get a dialog like this:
![image](https://github.com/void-linux/void-packages/assets/5366828/98c30910-7e1d-4643-98fa-41a62b4aff2d)

clicking continue, it will start to launch, then segfault for me.

*however*, if I disable any active stylesheets in `qt5ct`, it *does* launch successfully

![image](https://github.com/void-linux/void-packages/assets/5366828/b9eb883d-126b-4c35-9b8d-52359f983cee)
![image](https://github.com/void-linux/void-packages/assets/5366828/3d4aedff-63d3-4883-9d95-7de45ae8868a)

are you using qt5ct?

**Comment by classabbyamp** [comment]
additionally, try this PR: https://github.com/void-linux/void-packages/pull/44365

**Comment by motorto** [comment]
@classabbyamp thanks but I am not using qt5ct at all. Will try the PR and give feedback

**Comment by LinArcX** [comment]
Hi. sorry to open this issue again. but I got the same error at the beginning.
I don't use KDE. I use DWM Windows manager. and I already have `qt5ct` and `mediainfo` installed on my machine.

**Comment by realcharmer** [comment]
Same here...
```
qrc:/qml/kdenliveclipmonitor.qml: module "org.kde.desktop" is not installed
Segmentation fault
```

**Comment by classabbyamp** [comment]
try installing kf6-qqc2-destkop-style

**Comment by realcharmer** [comment]
Ok, installing `kf6-qqc2-desktop-style` did the trick! Getting warnings now though:

![image](https://github.com/void-linux/void-packages/assets/118818237/f9d66dee-db55-4ee5-bd5b-da5c3ed135c3)

**Comment by classabbyamp** [comment]
not actually required, all MLT modules are optional

**Comment by realcharmer** [comment]
Ok so adding `kf6-qqc2-desktop-style` as a runtime dependency should fix this? I can make a quick PR.
