### ISSUE TITLE
package request: GRUB 2.03 w/ F2FS support

### ISSUE THREAD

**Issue by kyledolichev** [void-linux/void-packages#4436]
I can't seem to get onto the forums, what's up with that? Are the forums down? 

Manjaro has a 'GRUB 2.03' which supports F2FS, this is a highly beneficial filesystem for SSDs. 
Unfortunately I'm no good at writing/converting patch files over, but I can provide as many relevant links as possible. I've been unable to get the patches to work on my own so far, but its probably a fairly easy task.

PKGBUILD for Manjaro's GRUB 2.03
https://github.com/manjaro/packages-core/blob/master/grub/PKGBUILD

Might be some resources in this AUR package also:
https://aur.archlinux.org/packages/grub-f2fs/

I thought F2FS was being added to GRUB's mainline support but it doesn't appear to be working for Void Linux as of yet, nor even Arch Linux it would appear either. GRUB in Manjaro seems to work fine though with F2FS.

**Comment by Cogitri** [comment]
Yes, Arch uses https://aur.archlinux.org/cgit/aur.git/plain/grub-add-f2fs-support-v8.patch?h=grub-f2fs to add f2fs support. I'm really not sure if it's _that_ great of an idea to apply a downstream patch to your bootloader (it sure sucks when it doesn't work), when you can just create a <10MB partition with a more conventional file system to house GRUB.

**Comment by Hoshpak** [comment]
We usually stick close to upstream and don't patch in random features. Just wait for f2fs to be supported upstream, then we can also enable it in our grub builds.

**Comment by Lolzen** [comment]
I'm essentially waiting for the releveant Grub version to be released for my new, clean install so i can truly have an only f2fs system.
I'm assuming i do have to keep waiting for 2.03/2.04, or can i interpret "upstream" as a glimpse of hope to enable the patch which indeed is upstream now to be included sooner?
http://git.savannah.gnu.org/cgit/grub.git/commit/?id=71f9e4ac44142af52c3fc1860436cf9e432bf764
https://www.phoronix.com/scan.php?page=news_item&px=GRUB-Now-Supports-F2FS

**Comment by vitorhugomattos** [comment]
GRUB 2.03 added F2FS support natively, right?
