### ISSUE TITLE
Package request: qtlanguageserver

### ISSUE THREAD

**Issue by JuniorSuperTux** [void-linux/void-packages#44381]
### Package name

qtlanguageserver

### Package homepage

https://github.com/qt/qtlanguageserver

### Description

An implementation of the Language Server Protocol for Qt6

### Does the requested package meet the package requirements?

System, Compiled, Required

### Is the requested package released?

Yes

**Comment by CabrioletDiskette** [comment]
https://github.com/void-linux/void-packages/pull/44628

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/qt6-languageserver/template
