### ISSUE TITLE
rpi-firmware: please update

### ISSUE THREAD

**Issue by lilmike** [void-linux/void-packages#44408]
### Is this a new report?

Yes

### System Info

n/a I don't have access to an rpi with this bug

### Package(s) Affected

rpi-firmware-20220823_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

rpi-firmware prevent booting via usb on the current firmware in void, which is quite out of date. The latest is 20230405. See the original bug report on github: https://github.com/raspberrypi/firmware/issues/1744 and a report on r/voidlinux: https://www.reddit.com/r/voidlinux/comments/11jpcpf/rpi4_latest_rpifirmware_package_cant_boot_via_usb/ or google cached since r/voidlinux is blacked out: https://webcache.googleusercontent.com/search?q=cache:18-DXrKeEEEJ:https://www.reddit.com/r/voidlinux/comments/11jpcpf/rpi4_latest_rpifirmware_package_cant_boot_via_usb/&cd=11&hl=en&ct=clnk&gl=us thanks!

### Expected behaviour

usb booting is broken on pi4 with void's latest rpi firmware

### Actual behaviour

no crash, but booting via usb on rpi4 is not working

### Steps to reproduce

simply trying to boot void via usb on rpi4 with the latest rpi-firmware does not boot

**Comment by classabbyamp** [comment]
There's already a PR that you could test https://github.com/void-linux/void-packages/pull/43600

**Comment by hjozwiak** [comment]
@lilmike BUILT ME AN IMAGE FOR ME TO TEST, AND IT IS CURRENTLY BOOTING FROM usb BASED ON THAT PULL REQUEST.

**Comment by classabbyamp** [comment]
did the image just have the updated rpi-firmware package or also the rpi-kernel and rpi-userland updates?

**Comment by lilmike** [comment]
I did a full update on the image, plus adding in the repository you
built, so if those packages are installed on the image and are in your
repo then they did get updated.

-Michael.




On Tue, Jun 13, 2023 at 09:54:09AM -0700, classabbyamp wrote:
>did the image just have the updated rpi-firmware package or also the rpi-kernel and rpi-userland updates?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/void-linux/void-packages/issues/44408#issuecomment-1589688953
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

-- 
Sorry about the test, it's just a me thing.
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my christmas spirited...
stationary bicycle
