### ISSUE TITLE
Package request: mlton

### ISSUE THREAD

**Issue by cendillion** [void-linux/void-packages#44416]
### Package name

mlton

### Package homepage

http://mlton.org/

### Description

MLton is a whole-program optimizing compiler for the Standard ML programming language. MLton generates small executables with excellent runtime performance, utilizing untagged and unboxed native integers, reals, and words, unboxed native arrays, fast arbitrary-precision arithmetic based on GMP, and multiple code generation and garbage collection strategies. In addition, MLton provides a feature rich Standard ML programming environment, with full support for SML97 as given in The Definition of Standard ML (Revised), a number of useful language extensions, a complete implementation of the Standard ML Basis Library, various useful libraries, a simple and fast C foreign function interface, the ML Basis system for programming with source libraries, and tools such as a lexer generator, a parser generator, and a profiler.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by CabrioletDiskette** [comment]
Got rough template done [943ead04f22f62a7f118955e611ad64610a9a760](https://github.com/CabrioletDiskette/void-packages/commit/943ead04f22f62a7f118955e611ad64610a9a760)

Weird work around needed for one bit. I'll clean it up and make a pr tmrw.

**Comment by CabrioletDiskette** [comment]
PR https://github.com/void-linux/void-packages/pull/44621

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/mlton/template
