### ISSUE TITLE
Package request: swaycwd

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#44499]
### Package name

swaycwd

### Package homepage

https://github.com/manjaro-sway/swaycwd

### Description

There are multiple possible implementations. The Manjaro Sway one is actively used in the Manjaro Sway default install, so I would recommend that.

https://github.com/qiu-x/swaycwd/
This one has a quite relaxed filter, which **could** mean more error possibilities. I didn't test it however.

https://github.com/calebstewart/swaycwd
This one needs `gron` for filtering JSON. The Manjaro Sway one seems to implement this filter using `jq`.

https://github.com/dmnt3rr0r/swaycwd
This one is written in Go, however it doesn't seem to be maintained.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by Duncaen** [comment]
> System, Compiled

Its like a 2 line shell script without the option parsing?

**Comment by notramo** [comment]
Mostly yes.

**Comment by Anachron** [comment]
You havent even described what this package does/is for.

But after checking the first repo I dont even think we need this packaged,- as Duncaen said it's just a few lines of code which would be a good contestant for a local script.
