### ISSUE TITLE
Package request: vectorscan (Portable fork of Intel hyperscan)

### ISSUE THREAD

**Issue by ahall** [void-linux/void-packages#44514]
### Package name

vectorscan

### Package homepage

https://github.com/VectorCamp/vectorscan

### Description

Vectorscan is a high-performance multiple regex matching library. It follows the regular expression syntax of the commonly-used libpcre library, but is a standalone library with its own C API. This is a portable and API compatible fork of Hyperscan from Intel.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by zlice** [comment]
FYI: may want https://github.com/VectorCamp/vectorscan
