### ISSUE TITLE
Package request: Upgrade rspamd to the latest version

### ISSUE THREAD

**Issue by ahall** [void-linux/void-packages#44515]
### Package name

rspamd

### Package homepage

https://github.com/rspamd/rspamd

### Description

There is an older version of rspamd 1.9.5 in our tree, but the latest version is 3.5.0. It would be great if we could also build it with cmake -DENABLE_HYPERSCAN=ON. I am currently building it that way in my personal environment, but it would be great to have proper packages. 

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
>   Don't request an update of a package, We have a script for that: https://repo-default.voidlinux.org/void-updates/void-updates.txt.  However, a quality pull request may help.

**Comment by ahall** [comment]
OK thanks for the info, will look into it :)
