### ISSUE TITLE
wmctrl: sources gone

### ISSUE THREAD

**Issue by zlice** [void-linux/void-packages#44513]
Not sure what this qualifies as, but the sources/distfiles for `wmctrl` seem to be gone.

- xbps template says `https://sites.google.com/site/tstyblo/wmctrl/wmctrl-${version}.tar.gz` but trying to xbps-src fetch that gives me a junk web file

- arch aur/freedesktop say `http://tripie.sweb.cz/utils/wmctrl/` which redirects to `https://www.sweb.cz/utils/wmctrl/` and trying to wget `http://tripie.sweb.cz/utils/wmctrl/dist/wmctrl-1.07.tar.gz` gives a 404 (browser redirects to previous page)

- `https://github.com/dancor/wmctrl` from 15 years ago seems to be on github but also points to `https://github.com/Conservatory/wmctrl` from 5 years ago that mentions the same described above :[

Can open a PR if any source is good, but I'm sure a void team member can just as easily push

**Comment by classabbyamp** [comment]
grab it from [debian](https://packages.debian.org/sid/source/wmctrl): http://deb.debian.org/debian/pool/main/w/wmctrl/wmctrl_1.07.orig.tar.gz
