### ISSUE TITLE
bug: when uninstalling fcitx, permissions on mime database get set to wrong ones

### ISSUE THREAD

**Issue by etosan** [void-linux/void-packages#4455]
### System

* xuname:  `Void 4.18.16_2 x86_64 GenuineIntel uptodate rFF`

* package:  `fcitx-4.2.9.6_3`

### Expected behavior

Everything works.

### Actual behavior

I guess it's called "mime database" or something. Well those things under  `/usr/share/mime` get fucked up permissions breaking almost all gtk apps (I guess gtk is unable to read meta info about icon theme or something).

Error message produced by affected apps is completely useless and off the mark:
`Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png:  bla bla (gdk-pixbuf-error-quark, 3)`

Reinstalling this gem `xbps-install fcitx` fixes it. I guess there might be error in uninstall trigger? 
Even then, umask of `xbps-remove` invoking user is pretty standard:
```
: umask                               
u=rwx,g=rx,o=rx
```
### Steps to reproduce the behavior

  - install fcitx
  - remove fcitx
  - watch world burn

**Comment by maxice8** [comment]
Couldn't reproduce it with OTPClient, Evince and firefox

**Comment by newbluemoon** [comment]
I had a similar problem once, but with some other package. It seems the uninstall trigger doesn’t work correctly under certain circumstances (which I haven’t been able to figure out, yet). And I remember there had been more than one topic related to this on the now gone forum.

It seems there are three variants of the problem:
- `/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache` doesn’t exist
Solution: regenerate via `gdk-pixbuf-query-loaders > /usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache`
- `/usr/share/mime` has the wrong permissions
- `/usr/share/mime/mime.cache` doesn’t exist or is truncated
Solution: regenerate via `update-mime-database /usr/share/mime`

And sometimes it seems that installing/reconfiguring a gtk-package which runs the install trigger can fix the problem, too.
