### ISSUE TITLE
cross-arm-none-eabi-gdb appears to be missing some Python modules

### ISSUE THREAD

**Issue by camthesaxman** [void-linux/void-packages#44594]
### Is this a new report?

Yes

### System Info

Void 6.1.25_1 x86_64 GenuineIntel uptodate hold rrrmFFFFFF

### Package(s) Affected

cross-arm-none-eabi-gdb-12.1_1

### Expected behaviour

The `arm-none-eabi-gdb` command should work correctly without warnings.

### Actual behaviour

arm-none-eabi-gdb throws numerous warnings about Python modules not being found. Most debugging features still work, though there are annoying warnings with every command. The native x86-64 gdb does not exhibit this behavior, but the arm gdb does. Sample output from debugging an ARM kernel in qemu:
```
Python Exception <class 'ModuleNotFoundError'>: No module named '_gdbevents'
arm-none-eabi-gdb: warning:
Could not load the Python gdb module from `/usr/share/gdb/python'.
Limited Python support is available from the _gdb module.
Suggest passing --data-directory=/path/to/gdb/data-directory.
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-unknown-linux-gnu --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kernel.elf...
(gdb) target remote localhost:1234
Remote debugging using localhost:1234
Python Exception <class 'NameError'>: Installation error: gdb._execute_unwinders function is missing
0x00008000 in bootstrap ()
(gdb) stepi
Python Exception <class 'NameError'>: Installation error: gdb._execute_unwinders function is missing
Python Exception <class 'NameError'>: Installation error: gdb._execute_unwinders function is missing
0x00008004 in bootstrap ()
(gdb)
Python Exception <class 'NameError'>: Installation error: gdb._execute_unwinders function is missing
Python Exception <class 'NameError'>: Installation error: gdb._execute_unwinders function is missing
0x00008008 in bootstrap ()
(gdb) q
A debugging session is active.

        Inferior 1 [process 1] will be detached.

Quit anyway? (y or n) y
Detaching from program: /home/void/rpi-baremetal/kernel.elf, process 1
Ending remote debugging.
```

### Steps to reproduce

1. Install cross-arm-none-eabi-gdb.
2. Run arm-none-eabi-gdb.
3. Run some commands in gdb and get spammed with Python errors.

**Comment by CabrioletDiskette** [comment]
Could you try to build it on your system with the latest copy of void-packages? I tried to build on my system and it wouldn't even compile. 

Otherwise I caught this in a brief google search: https://github.com/riscv-software-src/homebrew-riscv/issues/61
So it may be related to python directory's.

**Comment by CtrlC-Root** [comment]
I have run into this as well and here's my understanding of the situation. If the `cross-arm-none-eabi-gdb` and `gdb-common` packages have matching versions then the former will use the Python libraries shipped with the latter at `/usr/share/gdb/python/`. However at the moment on Void Linux the former is 12.X and the latter is 13.X which apparently are incompatible hence the errors above. This prevents you from using most of the Python-based GDB tools with the `cross-arm-none-eabi-gdb` package (ex. [gef](https://github.com/hugsy/gef) ).

I'm not sure the best way to fix this but off the top of my head:

* Build the GDB 12 Python libraries, install them at a separate path than the default, and point GDB to them explicitly using configuration settings.
* Update `cross-arm-none-eabi-gdb` to the same major version as `gdb-common` and `gdb`. Now they can both use the same Python libraries.
