### ISSUE TITLE
docker run --init  must be supported not optional feature

### ISSUE THREAD

**Issue by hholst80** [void-linux/void-packages#44641]
docker-init or a similar process manager is required by docker to function properly. It is not a plugin like buildx or compose rather it's core functionality.

Example:

$ docker run --init hello-world

It is possible to solve this in at least 3 ways. Either to require an init manager and configuring docker to use that (as a virtual required pkg); introducing a hardwired dependency (to tini); or to simply ship tini-static as docker-init in the pkg.

In none of these solutions should tini include a symbolic link to docker-init. tini has no such responsibility and it has a hidden bidirectional dependency between the two packages. Complexity for no reason. I suggest we just ship a docker-init with docker and be done.

I'm happy to make a PR once we are in agreement that the correct fix is to either
1. Remove docker-init from tini
2. Include a bundled docker-init with core docker daemon package,
Or
1. (Same)
2. Require tini and symlink tini-static to docker-init OR custom configuration of dockerd.

I favor the configuration solution the least because I generally don't like the os to be opinionated on daemon config I am fiddling with myself.

**Comment by classabbyamp** [comment]
`docker` already depends on `tini`, and that is the supported way to use docker

**Comment by ahesford** [comment]
It's already been explained twice now that `docker` pulls in `tini`, so there is no need for further action.
