### ISSUE TITLE
nvidia-modeset: Version mismatch: nvidia.ko(410.73) nvidia-modeset.ko(390.87)

### ISSUE THREAD

**Issue by vlur** [void-linux/void-packages#4473]
### System

Void glibc 4.18.16_2

Packages affected:
- nvidia
- nvidia390
- dkms

I'm using the proprietary nvidia drivers provided by xbps. The card is a GTX 1050 Ti. Previous version was 390.87. New version that causes this breakage is 410.73. 

### Expected behavior
Install system upgrades with `xbps-install -Su`, `dkms` builds the drivers. Xorg loads on boot.

### Actual behavior
Driver 410.73 says it fails to build for kernel 4.18.16_1. Log file for this event does not exist in /var/lib/dkms.

dmesg output shows nvidia-modeset: `Version mismatch: nvidia.ko(410.73) nvidia-modeset.ko(390.87)` upon boot at all times, whether `nvidia` packages are installed or not.

`startx` never reaches a graphical environment and hangs on a blank screen until killed from a different tty.

Output from `xbps-install nvidia`:
```
nvidia-dkms-410.73_1: configuring ...
DKMS module 'nvidia-410.73' already added, skipping.
Building DKMS module 'nvidia-410.73' for kernel-4.18.16_1... FAILED!
DKMS module 'nvidia-410.73' failed to build, please check /var/lib/dkms
for errors in the log file.
Building DKMS module 'nvidia-410.73' for kernel-4.18.16_2... done.
Installing DKMS module 'nvidia-410.73' for kernel-4.18.16_2... done.
nvidia-dkms-410.73_1: installed successfully.
nvidia-libs-410.73_1: configuring ...
nvidia-libs-410.73_1: installed successfully.
nvidia-410.73_1: configuring ...
Updating MIME database...
Regenerating initramfs, please wait...
dracut: dracut module 'cifs' depends on 'network', which can't be installed
dracut: dracut module 'cifs' depends on 'network', which can't be installed
nvidia-410.73_1: installed successfully.
```
Checking the log shows no errors for the build for 4.18.16_2. Logs for 4.18.16_1 simply do not exist in /var/lib/dkms.

### Steps to reproduce the behavior
1. xbps-remove -RyvF nvidia nvidia-dkms nvidia-libs nvidia-libs-32bit nvidia-gtklibs dkms
2. xbps-install libGL libEGL libGLES
3. Reboot (version mismatch error still in kernel messages upon reboot)
4. xbps-install nvidia

**Comment by jnbr** [comment]
It fails for `linux4.18.16_1` because this kernel was built with a different revision of gcc.
Make sure you boot `4.18.16_2`, check again and do not worry about `4.18.16_1`.

**Comment by vlur** [comment]
I am booted into 4.18.16_2 for all of this. Should I vkpurge 4.18.16_1?

**Comment by vlur** [comment]
Okay. Nothing changed. I still get the same version mismatch error on boot and during building the driver, and xorg hangs on a blank screen when started.

**Comment by jnbr** [comment]
Have you previously installed the nvidia drivers from a different source then xbps? Check the output of `modinfo nvidia-modeset`.

**Comment by Hoshpak** [comment]
I would manually remove all nvidia modules from `/lib/modules/$(uname -r)` at this point, then ensure that only one version of the nvidia driver is installed at this time and install the modules for that version again with dkms.
