### ISSUE TITLE
youtube-dl has a bug fix that isn't in the latest void package

### ISSUE THREAD

**Issue by habiloid** [void-linux/void-packages#44758]
### Is this a new report?

Yes

### System Info

Void 6.1.34_1 x86_64-musl AuthenticAMD

### Package(s) Affected

youtube-dl-2021.12.17_2

### Expected behaviour

Expect package to down load video from youtube

### Actual behaviour

Fails to download:

youtube-dl --verbose 'https://www.youtube.com/watch?v=a_0xLaSQAQ0'

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=a_0xLaSQAQ0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.4 (CPython) - Linux-6.1.34_1-x86_64-with-libc
[debug] exe versions: ffmpeg 4.4.4, ffprobe 4.4.4
[debug] Proxy map: {}
[youtube] a_0xLaSQAQ0: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/up
date  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest vers
ion; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### Steps to reproduce

1. Try to download a video such as one above
2. It fails
3. If latest version on youtube-dl's github is used (version number is same but bug has been fixed) it works

**Comment by Bnyro** [comment]
You should follow one of the steps described at https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611. We can't just apply a simple patch to it because there have been a lot of changes between the latest release and the commit, that fixes the issue.
I can only recommend using yt-dlp for now.

**Comment by Piraty** [comment]
until upstream youtube-dl tags a new release, you may use yt-dlp, either from Void's repos or pypi.
