### ISSUE TITLE
DKMS Modules Fail to Build on aarch64 - Missing powerpc Headers

### ISSUE THREAD

**Issue by Calandracas606** [void-linux/void-packages#44807]
### Is this a new report?

Yes

### System Info

Void 6.3.10_1 aarch64-musl Unknown uptodate rFF

### Package(s) Affected

linux-headers-6.3_1

### Expected behaviour

installing a package that includes a DKMS module (eg. zfs, wireguard) builds the module successfully

### Actual behaviour

DKMS Module fails to build. Log files mention missing "arch/powerpc/crypto/Kconfig"

### Steps to reproduce

1. xbps-install zfs
2. Error

**Comment by Calandracas606** [comment]
/usr/src/kernel-headers-6.3.10_1/arch/powerpc is missing on aarch64, but this file exists on my x86_64 device

Device is a pinebookpro.
Same issue with aarch64-musl and aarch64-glibc

Linux package (mainline kernel) and Linux-headers are installed
Tested with using pinebookpro-kernel and pinebookpro-kernel-headers and this also fails

On my x86_64-glibc machine, trying to produce an aarch64 image using ./mkplatformfs in void-mklive also fails to build the zfs module with the same error.

**Comment by Calandracas606** [comment]
example when installing zfs (similar errors with other DKMS modules such as Wireguard)                                                            
```                                                                                                                                               
Added DKMS modules 'zfs-2.1.12'.                                                                                                                  
Prepare to build modules for kernel-6.3.10_1... FAILED!                                                                                           
Kernel scripts failed to build, please check /lib/modules/6.3.10_1/build/make.log                                                                 
for errors in the log file.                                                                                                                       
Building DKMS module 'zfs-2.1.12' for kernel-6.3.10_1... FAILED!                                                                                  
DKMS module 'zfs-2.1.12' failed to build, please check /var/lib/dkms                                                                              
for errors in the log file.                                                                                                                       
Regenerating initramfs images using kernel hook 20-initramfs                                                                                      
dracut-install: Failed to find module 'zfs'                                                                                                       
dracut: FAILED: /usr/lib/dracut/dracutinstall -D /var/tmp/dracut.pDCU9N/initramfs --kerneldir /lib/modules/6.3.10_1/ -m zfs                       
dracut: installkernel failed in module zfs                                                                                                        
zfs-2.1.12_1: installed successfully.                                                                                                             
```                                                                                                                                               
                                                                                                                                                  
contents of  /lib/modules/6.3.10_1/build/make.log                                                                                                 
                                                                                                                                                  
```                                                                                                                                               
make: Entering directory '/usr/src/kernel-headers-6.3.10_1'                                                                                       
  SYNC    include/config/auto.conf.cmd                                                                                                            
crypto/Kconfig:1402: can't open file "arch/powerpc/crypto/Kconfig"                                                                                
make[2]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1                                                                                    
make[1]: *** [Makefile:693: syncconfig] Error 2                                                                                                   
make: *** [Makefile:793: include/config/auto.conf.cmd] Error 2                                                                                    
make: Leaving directory '/usr/src/kernel-headers-6.3.10_1'                                                                                        
```                                                          

                                                                                                                                                 
contents of /var/lib/dkms/zfs/2.1.12/build/make.log                                                                                               
                                                                                                                                                  
```                                                                                                                                               
DKMS make.log for zfs-2.1.12 for kernel 6.3.10_1 (aarch64)                                                                                        
Mon Jul 3 00:00:53 EDT 2023                                                                                                                       
make: Entering directory '/var/lib/dkms/zfs/2.1.12/build/module'                                                                                  
make: *** No targets specified and no makefile found. Stop.                                                                                       
make: Leaving directory '/var/lib/dkms/zfs/2.1.12/build/module'                                                                                   
```

**Comment by abenson** [comment]
> similar errors with other DKMS modules such as Wireguard

As a note, `wireguard-dkms` shouldn't be used with any kernel after 5.5.

**Comment by moabeat-berlin** [comment]
I think my comment on [this pull-request](https://github.com/void-linux/void-packages/pull/43600#issuecomment-1722569106) is related.

**Comment by classabbyamp** [comment]
please test: #46332

**Comment by Calandracas606** [comment]
Getting a very similar Makefile error as the one described in #46152 

`linux6.3-6.3.13_2: configuring ...
Executing post-install kernel hook: 10-dkms ...
  SYNC    include/config/auto.conf
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/menu.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
  UPD     include/generated/compile.h
  HOSTCC  scripts/dtc/fstree.o
  HOSTCC  scripts/dtc/dtc.o
  HOSTCC  scripts/dtc/flattree.o
  HOSTCC  scripts/dtc/data.o
  HOSTCC  scripts/dtc/srcpos.o
  HOSTCC  scripts/dtc/treesource.o
  HOSTCC  scripts/dtc/livetree.o
  HOSTCC  scripts/dtc/checks.o
  HOSTCC  scripts/dtc/util.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTCC  scripts/dtc/libfdt/fdt.o
  HOSTCC  scripts/dtc/libfdt/fdt_ro.o
  HOSTCC  scripts/dtc/libfdt/fdt_wip.o
  HOSTCC  scripts/dtc/libfdt/fdt_sw.o
  HOSTCC  scripts/dtc/libfdt/fdt_strerror.o
  HOSTCC  scripts/dtc/libfdt/fdt_rw.o
  HOSTCC  scripts/dtc/libfdt/fdt_empty_tree.o
  HOSTCC  scripts/dtc/libfdt/fdt_addresses.o
  HOSTCC  scripts/dtc/libfdt/fdt_overlay.o
  HOSTCC  scripts/dtc/fdtoverlay.o
  HOSTLD  scripts/dtc/fdtoverlay
  HOSTLD  scripts/dtc/dtc
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/sorttable
  HOSTCC  scripts/asn1_compiler
  HOSTCC  scripts/genksyms/genksyms.o
  HOSTCC  scripts/genksyms/lex.lex.o
  HOSTCC  scripts/genksyms/parse.tab.o
  HOSTLD  scripts/genksyms/genksyms
scripts/Makefile.build:41: arch/arm64/tools/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/arm64/tools/Makefile'.  Stop.
make: *** [arch/arm64/Makefile:179: archprepare] Error 2`
