### ISSUE TITLE
Package request: qemu-system-x86_64

### ISSUE THREAD

**Issue by izzy8799** [void-linux/void-packages#44926]
### Package name

qemu-system-x86_64

### Package homepage

https://www.qemu.org/

### Description

QEMU is a generic and open source machine emulator and virtualizer.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

No

**Comment by Duncaen** [comment]
```
$ xlocate /usr/bin/qemu-system-x86_64
qemu-7.1.0_2  /usr/bin/qemu-system-x86_64
```

**Comment by izzy8799** [comment]
> ```
> $ xlocate /usr/bin/qemu-system-x86_64
> qemu-7.1.0_2  /usr/bin/qemu-system-x86_64
> ```

Sorry, didn't know. Thanks for explaining!
