### ISSUE TITLE
cannot load such file -- puppet/util/command_line

### ISSUE THREAD

**Issue by wastemans** [void-linux/void-packages#44955]
### Is this a new report?

Yes

### System Info

Void 6.3.10_1 x86_64 GenuineIntel/KVM uptodate rFF

### Package(s) Affected

puppet-6.16.0_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

I'm not sure.

### Expected behaviour

Trying to run:
puppet config set server puppetserver --section main

Should work, but there are ruby issues.

### Actual behaviour

I get this error.
cannot load such file -- puppet/util/command_line

# ruby -e 'puts $LOAD_PATH'
/usr/lib64/ruby/site_ruby/3.2.0
/usr/lib64/ruby/site_ruby/3.2.0/x86_64-linux
/usr/lib64/ruby/site_ruby
/usr/lib64/ruby/vendor_ruby/3.2.0
/usr/lib64/ruby/vendor_ruby/3.2.0/x86_64-linux
/usr/lib64/ruby/vendor_ruby
/usr/lib64/ruby/3.2.0
/usr/lib64/ruby/3.2.0/x86_64-linux
#

### Steps to reproduce

1. xbps-install -Sy puppet
2. puppet config set server puppetserver --section main

**Comment by paper42** [comment]
puppet was removed in 2021 f793c29610eb4f772c5f10a72b1d07b4ca0498c8
