### ISSUE TITLE
Package request: Aria2

### ISSUE THREAD

**Issue by tomcup** [void-linux/void-packages#45049]
### Package name

aria2

### Package homepage

https://github.com/aria2/aria2

### Description

a lightweight multi-protocol & multi-source, cross platform download utility operated in command-line. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by Johnnynator** [comment]
Aria2 is in the repo

https://github.com/void-linux/void-packages/tree/master/srcpkgs/aria2
