### ISSUE TITLE
Package sequeler: No provider 'MySQL' installed

### ISSUE THREAD

**Issue by shizonic** [void-linux/void-packages#4507]
### System

* xuname:  
  * Void 4.19.1_1 x86_64 GenuineIntel uptodate rrFFFFFFFFFFFFFFFFFF
* package:  
  * sequeler-0.6.3_1

### Expected behavior
Connection to local mariadb works.

### Actual behavior
Connection can't be established due the error `No provider 'MySQL' installed`

### Steps to reproduce the behavior
Install `sequeler` and try to connect to local running mysql/mariadb database.

**Comment by shizonic** [comment]
@CameronNemo Thanks for the reply. But it didn't work. Just added `libmariadbclient-devel` and `libmysqlclient-devel` to `makedepends` and compiled it. Same error.

**Comment by Hoshpak** [comment]
It's `libgda` that needs to be compiled with mysql support since sequeler uses that to access databases. I will create a PR.

**Comment by shizonic** [comment]
Thank you @Hoshpak
