### ISSUE TITLE
The config files of the Waybar package are overwritten when the package is reinstalled.

### ISSUE THREAD

**Issue by BlitDev** [void-linux/void-packages#45139]
### Is this a new report?

Yes

### System Info

Void 6.3.12_1 x86_64 AuthenticAMD uptodate rFFFFFFFFFF

### Package(s) Affected

Waybar-0.9.20_1

### Expected behaviour

1. Update the package.
2. The package is updated, **the config files remain the same**.

### Actual behaviour

1. Update the package.
2. The package is updated, **the config files overwritten**.

### Steps to reproduce

1. Update the package.
2. Look at the config files in the **/etc/xdg/waybar** (**config** and **style.css**).

**Comment by classabbyamp** [comment]
you should probably be putting your personal config files in one of the other config locations, namely one of:

> - `$XDG_CONFIG_HOME/waybar/config`
> - `~/.config/waybar/config`
> - `~/waybar/config`

(from waybar(5))

it is fixed after 8b189768f2 but that specific update will also remove those config files still, so back them up if they are there.
