### ISSUE TITLE
Package request: gcompris-qt

### ISSUE THREAD

**Issue by Jabolpunki** [void-linux/void-packages#45213]
### Package name

gcompris-qt

### Package homepage

https://gcompris.net/index-en.html

### Description

High quality educational software suite for children aged 2 to 10

### Does the requested package meet the package requirements?

System, Compiled, Required

### Is the requested package released?

Yes

**Comment by Jabolpunki** [comment]
makedepends="qml-box2d qt5-declarative-devel
 qt5-multimedia-devel qt5-sensors-devel qt5-svg-devel
 qt5-tools-devel qt5-xmlpatterns-devel qt5-quickcontrols2-devel qt5-charts-devel"
depends="desktop-file-utils hicolor-icon-theme
 qt5-graphicaleffects qt5-multimedia qt5-quickcontrols qt5-quickcontrols2  qt5-charts qt5-svg"
short_desc="High quality educational software suite for children aged 2 to 10"






checksum=f21aa2ab5c18c388ab6ce5c2af0709a9332e2c84b34a64aa3eec36467f17cd00

**Comment by Chocimier** [comment]
We do have gcompris-qt in repo.
