### ISSUE TITLE
yad

### ISSUE THREAD

**Issue by emacsomancer** [void-linux/void-packages#4522]
### System

* xuname:  
  Void 4.18.17_1 x86_64-musl GenuineIntel uptodate rFFFFFF

* package:  
 `yad` 0.40.3_1

### Expected behaviour
yad is able to be installed
### Actual behavior
won't install, error "MISSING: webkitgtk2>=2.4.8_2"
### Steps to reproduce the behaviour
`sudo xbps-install yad`

This issue is related to the removal of `webkitgtk2` ( https://github.com/void-linux/void-packages/issues/2488 ), which suggests that `yad` has an updated source which uses `webkit2gtk` instead but this package still needs reconfiguring/rebuilding.  See also perhaps https://github.com/void-linux/void-packages/issues/1789 .

**Comment by maxice8** [comment]
@Gottox yad needs removal from the repo index.

Problably keep a package request for when upstream tags a new release

**Comment by Veyrdite** [comment]
I just manually compiled the latest release (40.3, same as the xbps package).  It works fine.

webkitgtk2 is an optional feature.  If webkit2-dev (exact name?) is not detected by autotools then yad is compiled without a dep on it.

**Comment by Hoshpak** [comment]
Is it lacking any important feature if it's compiled without webkit support? If not, there should be no harm in bringing the package back and since at least two users are interested in using it, that would be reason enough for me to do it.

**Comment by paoloschi** [comment]
third user interested here! 
as reported upstream in README:
```
Additionally, you can build yad with the following libraries:
    Webkit - for supporting HTML dialog (http://webkitgtk.org)
```
unless a display/browser HTML element needs to be inserted in the dialog, the yad functionality for building interfaces remains intact even without webkit support

**Comment by Hoshpak** [comment]
@maxice8 @Gottox package removal is now longer necessary as the old revision was replaced with the new one.
