### ISSUE TITLE
xbps-src throws errors on bash

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#45239]
### Is this a new report?

Yes

### System Info

Void 6.3.10_1 x86_64 GenuineIntel uptodate rrFFFFFFF

### Package(s) Affected

xbps-src

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No.

### Expected behaviour

I expect `LANG=C ./xbps-src update-check bsdtar` to throw no errors on bash.

### Actual behaviour

```bash
# LANG=C ./xbps-src update-check bsdtar
/home/lap/var/bldr/gitsrc/common/environment/setup/sourcepkg.sh: line 31: unset: `BASH_FUNC_filew%%': not a valid identifier
/home/lap/var/bldr/gitsrc/common/environment/setup/sourcepkg.sh: line 31: unset: `BASH_FUNC_timer_handle%%': not a valid identifier
/home/lap/var/bldr/gitsrc/common/environment/setup/sourcepkg.sh: line 31: unset: `BASH_FUNC_welcome_prompt_handle%%': not a valid identifier
/home/lap/var/bldr/gitsrc/common/environment/setup/sourcepkg.sh: line 31: unset: `BASH_FUNC_vimw%%': not a valid identifier
/home/lap/var/bldr/gitsrc/common/environment/setup/sourcepkg.sh: line 31: unset: `BASH_FUNC_directory_not_found_handle%%': not a valid identifier
/home/lap/var/bldr/gitsrc/common/environment/setup/sourcepkg.sh: line 31: unset: `BASH_FUNC_shell_prompt_handle%%': not a valid identifier
/home/lap/var/bldr/gitsrc/common/environment/setup/sourcepkg.sh: line 31: unset: `BASH_FUNC_gitw%%': not a valid identifier
/home/lap/var/bldr/gitsrc/common/environment/setup/sourcepkg.sh: line 31: unset: `BASH_FUNC_cdw%%': not a valid identifier
/home/lap/var/bldr/gitsrc/common/environment/setup/sourcepkg.sh: line 31: unset: `BASH_FUNC_command_not_found_handle%%': not a valid identifier
libarchive-3.6.2 -> libarchive-3.7.0

```

### Steps to reproduce

Run `LANG=C ./xbps-src update-check bsdtar` with shell functions inside bashs env.

Issue is because of https://github.com/void-linux/void-packages/commit/6174bd6afde26fbcdf80437ab1653c6dab34099b

@sgn

**Comment by Anachron** [comment]
This is my env:
```sh
...
BASH_FUNC_cdw%%=() {  w=$(which "${1}" 2> /dev/null);
 if test -z "${w}"; then
 printf 'Error: %s could not be found.\n' "${1}" 2>&1;
 return 1;
 fi;
 cd $(dirname "${w}")
}
BASH_FUNC_welcome_prompt_handle%%=() {  clear;
 . ~/etc/sh/colors;
 . /etc/os-release;
 printf "\n  Welcome to ${abl}%s${ars}, ${abl}%s${ars}.\n" "${NAME}" "${USER}"
}
BASH_FUNC_filew%%=() {  w=$(which "${1}" 2> /dev/null);
 if test -z "${w}"; then
 printf 'Error: %s could not be found.\n' "${1}" 2>&1;
 return 1;
 fi;
 file "${w}"
}
...
```

Maybe we should use `compgen -v` here instead.

**Comment by sgn** [comment]
No idea how I can replicate your problem! Where did you put those declaration, and exportation>

**Comment by Anachron** [comment]
Just export some functions inside your `.bash_profile`.

**Comment by Anachron** [comment]
@sgn instead of doing all these variable unsetting, why don't we spawn a clean ENV with the exception of the variables that we specify?

**Comment by sgn** [comment]
We do, but this is in case building a package as a dependency of other packages, the environment variables wasn't unset properly.

We should start a new `xbps-src` process in that case. Not sure how to do it.

**Comment by Anachron** [comment]
That works as well,- thanks!
