### ISSUE TITLE
LibreCAD dimension text not showing up

### ISSUE THREAD

**Issue by gega** [void-linux/void-packages#45270]
### Is this a new report?

Yes

### System Info

Void 6.3.12_1 x86_64 GenuineIntel uptodate rrrmFFFFF

### Package(s) Affected

LibreCAD-2.1.3_5

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Dimensions are not annotated.

I was able to fix it with:

`# ln -s /usr/share/librecad/ /usr/share/librecad/fonts`

Probable cause is that fonts were installed to the wrong location and fonts are not found by LibreCAD.

### Expected behaviour

Dimensions should be rendered properly

### Actual behaviour

Dimension texts are missing (arrows and other parts are rendered correctly)

### Steps to reproduce

- create new dimensions
- observe that no text are rendered
- create the softlink:  ln -s /usr/share/librecad/ /usr/share/librecad/fonts
- restart LibreCAD
- observe that dimension texts are rendered correctly

**Comment by Bnyro** [comment]
could you please test #45286?

**Comment by classabbyamp** [comment]
> could you please test #45286?

doubt it will help as-is if lines 49-51 in the template are wrong

**Comment by Bnyro** [comment]
same, it was more of a question to generally test the update

**Comment by Piraty** [comment]
> doubt it will help as-is if lines 49-51 in the template are wrong

i feel like symlinking the plugins from usr/lib is something that could be improved
