### ISSUE TITLE
Make PolyMC package actually package PolyMC

### ISSUE THREAD

**Issue by xslendix** [void-linux/void-packages#45292]
People have been saying that there has been a takeover. **This is blown out of proportion and it's completely false**. The maintainer, Lennymclennington was the one who started the project and is, and still is, the original owner. He has every right to do whatever he chooses with his project. Another huge misunderstanding is that he will use the project to spread malware. This came from the fact that he owns the meta servers. He has no grudges against anyone and he's not a serial killer, he just wanted a project that focused on the piece of software itself, not what ideology it promotes. For all the reasons above, I would please request a investigation on the current state of the project and for the package to be back in the repositories again. Thank you.

**Comment by sgn** [comment]
OK, let's remove that package,so we won't be pulled to that mess.

**Comment by xslendix** [comment]
If anyone is interested PolyMC is now available here: https://xslendi.xyz/void/x86_64-repodata under the name of `PolyMC-qt5`
