### ISSUE TITLE
Package request: update cage to version 0.1.5

### ISSUE THREAD

**Issue by ShadowFungi** [void-linux/void-packages#45335]
### Package name

cage

### Package homepage

https://www.hjdskes.nl/projects/cage/

### Description

Cage is a kiosk compositor for Wayland.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by Duncaen** [comment]
The issue creation form clearly states:

> Don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.

**Comment by ShadowFungi** [comment]
sorry I missed that, I will keep it in mind for next time.
