### ISSUE TITLE
Feature request: add KDE integration to OwnCloud client

### ISSUE THREAD

**Issue by kikinovak** [void-linux/void-packages#45342]
### Package name

owncloudclient

### Package homepage

https://www.owncloud.org

### Description

Void Linux has a package (`owncloudclient`) for the OwnCloud client in its official repository, which is nice. Unfortunately it is lacking proper KDE integration, which comes under the form of green or blue checkmark on synchronized/unsynchronized folders in the Dolphin file manager. 

For the record, I'm currently running Rocky Linux 8 with KDE from EPEL on my main workstation, and KDE integration works nicely. I built the OwnCloud client from a Fedora SRPM, and KDE integration comes in a separate `owncloud-client-dolphin` package. 

It would be nice to have something similar in Void Linux.

Cheers,

Niki

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
cc @tornaria

**Comment by sgn** [comment]
Please test #45352

**Comment by tornaria** [comment]
> Please test #45352

You didn't give me any time... :shrug:
