### ISSUE TITLE
Package request: Emacs with pgtk for Wayland

### ISSUE THREAD

**Issue by bmp** [void-linux/void-packages#45346]
### Package name

Emacs

### Package homepage

https://www.gnu.org/software/emacs/

### Description

Apologies if this is not the correct place, please do point me to the correct place. I am on Wayland (with fractional scaling) on Void Linux and when I run the default Emacs package from the repos (earlier 28 and 29 as of today), the display in Emacs is blurry. However, when I compile Emacs myself with the option (--with-pgtk) in both Emacs 29 and 30, the blurriness goes away. May I request that either another package with pgtk enabled be added?

1. Emacs 29 without pgtk (from xbps): 
![Screenshot_Emacs29_xbps](https://github.com/void-linux/void-packages/assets/1095177/2a9f36a4-7580-4d4f-9acb-187fd435ba5e)

2. Emacs 30 with pgtk (compiled from source): 
![Screenshot_Emacs30pgtk](https://github.com/void-linux/void-packages/assets/1095177/f0cc916f-6732-4d5a-8170-c198b61e8a94)

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by sgn** [comment]
#45373
