### ISSUE TITLE
Package request: turtl

### ISSUE THREAD

**Issue by liberodark** [void-linux/void-packages#45343]
### Package name

turtl

### Package homepage

 https://turtlapp.com/

### Description

Turtl is secure OSS, collaborative notebook

https://aur.archlinux.org/packages/turtl
https://github.com/turtl/desktop/

Also have see related issue : https://github.com/void-linux/void-packages/issues/4919

### Does the requested package meet the package requirements?

System, Compiled, Required

### Is the requested package released?

Yes

**Comment by Bnyro** [comment]
It already got requested in the linked issue. Why do you create yet an other one?

**Comment by liberodark** [comment]
For give more information but no problem have see the other issue after my issue.
