### ISSUE TITLE
Package request: Update of calibre to 6.23.0

### ISSUE THREAD

**Issue by bmp** [void-linux/void-packages#45404]
### Package name

calibre

### Package homepage

https://calibre-ebook.com

### Description

The current package for Calibre is version=6.17.0. However, Calibre has released version 6.23.0.

Would it be possible to update the template for the same?

Apologies, I tried looking at the [we have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt) link provided in the issue template and couldn't make sense of the list of packages and emails. _Does it mean I have to email the package manager (I am assuming they are maintaining or have maintained it in the past)?_

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by Chocimier** [comment]
"Don't request an update of a package" means: don't request an update of a package. Do the work yourself or wait indefinite time for someone else to do it.

Regards
