### ISSUE TITLE
Package request: python-pywlroots

### ISSUE THREAD

**Issue by justinesmithies** [void-linux/void-packages#45429]
### Package name

python-pywlroots

### Package homepage

https://github.com/flacjacket/pywlroots

### Description

Python binding to the wlroots library using cffi as required by Qtile if you're running it with the Wayland backend

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

Yes

**Comment by sgn** [comment]
No use. `qtile` wants pywlroots 0.15.x which requires wlroots 0.15.x

We have wlroots 0.16, so even if we package pywlroots. You can't use qtile.

**Comment by sgn** [comment]
https://github.com/qtile/qtile/issues/4190

**Comment by mhmdanas** [comment]
> No use. qtile wants pywlroots 0.15.x which requires wlroots 0.15.x

`wlroots0.15` _is_ packaged in Void, can't we just use that?
