### ISSUE TITLE
[RFC] enable `XBPS_STRICT` by default

### ISSUE THREAD

**Issue by mhmdanas** [void-linux/void-packages#45507]
When a `vsed` doesn't apply, they currently print a warning by default, and the build goes on. This can hide potential issues. `xbps-src` does have an `-s` flag, which in that case causes the build to stop at the failing vsed. This flag _is_ passed in the CI, but large PRs skip CI and so authors of those PRs may never notice the now-outdated `vsed`s (see e.g. https://github.com/void-linux/void-packages/issues/42441). Therefore, I propose enabling the "strict" `vsed` behavior by default, and would even go so far as to suggest removing the non-strict behavior, because I honestly don't see its point.

**Comment by mhmdanas** [comment]
I don't know, we might have to do a world rebuild to find out. For what it's worth though, https://github.com/void-linux/void-packages/issues/42441 documented templates with "useless" vseds and most of them were fixed (the checklist is outdated, I believe out of the templates in that issue only qt5 and pulseaudio still have vseds that don't apply).

**Comment by sgn** [comment]
No, please no!

**Comment by mhmdanas** [comment]
Why not?

**Comment by ahesford** [comment]
This seems too heavy handed. Catching these failures in CI is helpful enough.

**Comment by mhmdanas** [comment]
Why do you think it's heavy-handed? 

> Catching these failures in CI is helpful enough.

If they're going to be triggered in the CI anyway, I personally would rather have them caught when building locally rather than getting CI failures later on. Also, like I already mentioned, those failures won't be caught if the CI is skipped (unless you use `-s` locally or check build logs manually).

**Comment by classabbyamp** [comment]
i think `echo XBPS_STRICT=yes >> etc/conf` would work too?

**Comment by mhmdanas** [comment]
Yes, but I don't think it's documented (I actually only stumbled on it while reading `xbps-src`'s code).

**Comment by sgn** [comment]
> Why do you think it's heavy-handed?

You vsed something, it changes, good.
Your other steps run into failure, thus you need to patch.
You patch the software, you run the build again.
BUMPPP, `vsed` reports that it doesn't change anything, and blocks you from doing anything.

No, please no!
