### ISSUE TITLE
Package request: python-dbus-next

### ISSUE THREAD

**Issue by justinesmithies** [void-linux/void-packages#45519]
### Package name

python-dbus-next

### Package homepage

https://github.com/altdesktop/python-dbus-next

### Description

A zero-dependency DBus library for Python with asyncio support.

Please note that this package should be a dependency of the new qtile-wayland package submitted by @sgn .
The Qtile docs show this as a dependency.
https://docs.qtile.org/en/latest/manual/install/index.html

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

Yes

**Comment by sgn** [comment]
Sending notifications with dbus (optional).
