### ISSUE TITLE
Couldn't login from console after update. 

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#45562]
### Is this a new report?

Yes

### System Info

Void 6.1.30_1 x86_64 GenuineIntel uptodate hold rFF

### Package(s) Affected

pam, pam-base

### Expected behaviour

I should log in without any issues.

### Actual behaviour

couldn't log in until i chrooted and commented:

`session    required   pam_lastlog.so       silent`

in:

`/etc/pam.d/system-login`

### Steps to reproduce

update your system.

Try to log in again via the console. you can't. the reason is that this line:

`session    required   pam_lastlog.so       silent`

is not commented in this file: `/etc/pam.d/system-login`

It is worth mentioning that pam-base was also installed on my machine.

I saw this post on the void website: (written in 2020)
https://voidlinux.org/news/2020/12/pam-1.5.1.html

But it's interesting that I faced this issue in 2023!

**Comment by leahneukirchen** [comment]
You claim to use glibc, there pam_lastlog should work fine?

**Comment by LinArcX** [comment]
yes i'm using glibc. no, i couldn't login. until i manually updated that file and commented  pam_lastlog.

**Comment by leahneukirchen** [comment]
Sorry, can reproduce on pam 1.5.3_1. Will be fixed soon!
