### ISSUE TITLE
xdg-document-portal Segmentation Fault

### ISSUE THREAD

**Issue by ohlookitsaaron** [void-linux/void-packages#45591]
### Is this a new report?

Yes

### System Info

Void 6.3.13_1 x86_64-musl GenuineIntel uptodate rFF

### Package(s) Affected

xdg-desktop-portal

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Yes, on Alpine Linux: https://gitlab.alpinelinux.org/alpine/aports/-/issues/14195

### Expected behaviour

xdg-document-portal should start with flatpak apps or with xdg-desktop-portal (to my knowledge) running in the background.

### Actual behaviour

All flatpak apps cannot save any files regardless of flatpak permissions. 

When running /usr/libexec/xdg-document-portal: 
error: fuse stat failed: Socket not connected
Segmentation fault

When starting a flatpak app:
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.Failed: fuse stat failed: Socket not connected

### Steps to reproduce

1. Fresh install of Void Linux musl
2. Install GNOME desktop, enable dbus + gdm services
3. Install flatpak and enable flathub repo
4. Try to download anything from any flatpak web browser or program

**Comment by ahesford** [comment]
Can you try building a local copy of `xdg-desktop-portal` and installing that? No need to change anything.

**Comment by ahesford** [comment]
Please re-open or comment here if the revbump doesn't fix this issue.
