### ISSUE TITLE
GnuCOBOL package with missing dependencies (and outdated)

### ISSUE THREAD

**Issue by GitMensch** [void-linux/void-packages#45612]
### Is this a new report?

Yes

### System Info

current

### Package(s) Affected

gnucobol

### Expected behaviour

full support of all features (this is what this issue is about, the update would likely be handled by the update-script), and up-to-date, you can see both when executing `cobc --info`

Note that the [current template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/gnucobol/template) also doesn't use an official GNU mirror for download but a mirror that is not directly related to the GNU project.

The official homepage would be `url="https://www.gnu.org/software/gnucobol/` , the source would be `distfiles="https://ftp.gnu.org/gnu/${pkgname}/${pkgname}-${version}.tar.xz"` (you may also want to download and verify the signature).

For dependencies you may want to see https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=open-cobol (additional dev dependencies for libxml2 and either cjson or json-c, and for all libraries a runtime dependency in gnucobol-libs)

Also note that if you want a make_check_target, then this would be `make_check_target="checkall"` (doing more or less a `make check` and `make test`).

### Actual behaviour

XML and JSON are likely missing (at least they miss the dependencies in https://github.com/void-linux/void-packages/blob/master/srcpkgs/gnucobol/template), version is at 3.1.2 (3.2 is a month old and as no bug reports so far).

### Steps to reproduce

check with `cobc --info`

**Comment by cinerea0** [comment]
I've opened a PR with an update and added dependencies here: #45629, currently trying to figure out if I can fix crossbuilds. `make_check_target` was carefully chosen, the majority of tests there fail in our build system. If you're interested in helping with testing, you can either checkout the PR (if you know how to use xbps-src), or I can upload the package file and you can install it (if we're using the same architecture and libc).
