### ISSUE TITLE
yt-dlp reports wrong version

### ISSUE THREAD

**Issue by meator** [void-linux/void-packages#45668]
### Is this a new report?

Yes

### System Info

Void 6.3.13_1 x86_64 GenuineIntel uptodate rrrdFFFFFFFFFFFFFF

### Package(s) Affected

yt-dlp-2023.07.06_1

### Expected behaviour

```sh
> yt-dlp --version
2023.07.06
```

### Actual behaviour

```sh
> yt-dlp --version
2023.03.04
```

The program itself reports version `2023.03.04` even though it's from `yt-dlp-2023.07.06_1`. yt-dlp's version detection is possibly faulty (or XBPS version of the package is actually `2023.03.04` but I find that unlikely).

### Steps to reproduce

1. `xbps-install -S yt-dlp`
2. `yt-dlp --version`

**Comment by classabbyamp** [comment]
```
$ xrs yt-dlp
[*] yt-dlp-2023.07.06_1 CLI program to download videos from YouTube and other sites
abi@daedelus ~
$ yt-dlp --version
2023.07.06
```
can't repro. try `xbps-pkgdb yt-dlp`, perhaps you installed an old version with pip somehow?

**Comment by Anachron** [comment]
Yeah, use (`which yt-dlp`) to find the source.

**Comment by meator** [comment]
That's strange. Probably an error on my side. I have tried it in a docker container and I see correct version.

This is from my system:
```
> xbps-query yt-dlp
architecture: x86_64
changelog: https://raw.githubusercontent.com/yt-dlp/yt-dlp/master/Changelog.md
filename-sha256: a34e96987193fff360d1f81a2c16a467f1d157f4c730657b2c246deb0762cc2a
filename-size: 1976KB
homepage: https://github.com/yt-dlp/yt-dlp
install-date: 2023-08-19 08:56 CEST
install-script: 847B
installed_size: 9476KB
license: Unlicense
maintainer: Michal Vasilek <michal@vasilek.cz>
metafile-sha256: f255cce80de516dd003bad20cd2a3fea7fc5357858d48404a02184860ac0d79b
pkgname: yt-dlp
pkgver: yt-dlp-2023.07.06_1
remove-script: 845B
repository: https://repo-default.voidlinux.org/current
run_depends:
	python3>=0
short_desc: CLI program to download videos from YouTube and other sites
source-revisions: yt-dlp:b0e456752f
state: installed
> sudo xbps-pkgdb yt-dlp
> echo $?
0
> /usr/bin/yt-dlp --version
2023.03.04
```

**Comment by meator** [comment]
Not a Void problem, closing.
