### ISSUE TITLE
River is broken en MUSL and can't be built.

### ISSUE THREAD

**Issue by xplshn** [void-linux/void-packages#45688]
### Is this a new report?

Yes

### System Info

Void 6.3.13_1 x86_64 musl

### Package(s) Affected

River

### Expected behaviour

The package should not error

### Actual behaviour

Package errors at do_build() line 31

### Steps to reproduce

Xbps-src -o ~xwayland pkg river

**Comment by dkwo** [comment]
builds fine here
```
./xbps-src -m masterdir-x86_64-musl pkg -o ~xwayland river 
=> Registering new packages to /host/binpkgs
index: added `river-0.2.4_2' (x86_64-musl).
```
```
$ xuname 
Void 6.4.11_1 x86_64 GenuineIntel uptodate rrFFFFFFFFF
```

**Comment by abenson** [comment]
> Package errors at do_build() line 31

It would help if you provided the actual error.

**Comment by ahesford** [comment]
Failed to reproduce here as well. Are you using an outdated void-packages checkout?
