### ISSUE TITLE
Package Request: ncTelegram

### ISSUE THREAD

**Issue by Mashn** [void-linux/void-packages#4571]
[ncTelegram](https://github.com/Nanoseb/ncTelegram) - A ncurses Telegram client developed in Python with the urwid library.

That sounds very nice. It would be interesting to have in the repository.

**Comment by maxice8** [comment]
This also needs `tg` and and `python3-pytg`

`tg` is super annoying since it has nested git submodules

**Comment by maxice8** [comment]
python3-pytg has circular dependencies. can't help there.
