### ISSUE TITLE
Suggestion - Split `helix-grammars` from `helix` package

### ISSUE THREAD

**Issue by Zapeth** [void-linux/void-packages#45828]
The `helix` package by default includes all its compiled treesitter grammars, which take up the majority of the package size (~110MB or  86% of the total size in the latest release, see also https://github.com/helix-editor/helix/issues/6187).

While it is useful to have LSP support for all these languages out of the box, I think it should be up to the user to decide if its worth the extra space, especially since its likely to increase as more languages get added.

So my suggestion would be to split the grammar *.so at `/usr/lib/helix/runtime/grammars` in an extra package `helix-grammars` that depends on `helix`.

**Comment by classabbyamp** [comment]
you could also `noextract=/usr/lib/helix/runtime/grammars`

**Comment by Zapeth** [comment]
Thanks, I wasn't aware of that option. That should also allow a custom selection of grammars that are relevant to the user, so I'll use that for the time being.

I still think a package separation would be more convenient, but if the consensus is that a user configuration is sufficient then feel free to close this issue.

**Comment by Bnyro** [comment]
I'd assume that most users expect Helix to support all the treesitters out of the box as described in the official Helix docs.

If this will be done, we should also add a note about it that shows up when installing the package, or instead make helix depend on helix-grammars, and not vice-versa as described above.

**Comment by mhmdanas** [comment]
> I'd assume that most users expect Helix to support all the treesitters out of the box as described in the official Helix docs.

We could instead have `helix-minimal`, the core editor, and `helix`, which depends on both `helix-minimal` and `helix-grammars`.

**Comment by tranzystorek-io** [comment]
I'd rather avoid making this package more complex than it needs to be, unless it achieves sth more than just size optimization.

**Comment by mhmdanas** [comment]
That's fine with me, but a `vmove` in a new subpackage isn't really that complicated, is it?

**Comment by classabbyamp** [comment]
we don't need to subpackage everything

**Comment by mhmdanas** [comment]
Again, I don't object, I just disagree with the point that this is complicated.

**Comment by Zapeth** [comment]
Then I'll close this, `noextract` is a good enough workaround me.
