### ISSUE TITLE
discount-2.2.7d_1 signature not found

### ISSUE THREAD

**Issue by SpidFightFR** [void-linux/void-packages#45823]
### Is this a new report?

Yes

### System Info

Void 6.4.12_1 x86_64 AuthenticAMD notuptodate rrrmFFFFFF

### Package(s) Affected

discount-2.2.7d_1

### Expected behaviour

The package is supposed to be updated.

### Actual behaviour

[*] Downloading packages
ERROR: [trans] failed to download `discount-2.2.7d_1' signature from `https://mirror.puzzle.ch/voidlinux/current': Not Found
Transaction failed! see above for errors.

### Steps to reproduce

# xbps-install -Su

**Comment by classabbyamp** [comment]
just wait a little bit and try again, there was just a large sync and things may still be getting settled

**Comment by SpidFightFR** [comment]
Indeed it was solved a bit latter, i’ll keep that in mind for next time. Thanks!
