### ISSUE TITLE
Package request: lastpass-cli

### ISSUE THREAD

**Issue by bormosLP** [void-linux/void-packages#45846]
### Package name

lastpass-cli

### Package homepage

https://github.com/lastpass/lastpass-cli

### Description

Command line interface to [LastPass.com](https://lastpass.com/).

The latest version is 1.3.5 which is required to be able to login to LastPass.com. The new release contains certificate updated to the latest cert in use.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
>   Don't request an update of a package, We have a script for that: https://repo-default.voidlinux.org/void-updates/void-updates.txt
> However, a quality pull request may help.
