### ISSUE TITLE
Akonadi stopped working after MariaDB updated to 10.5.10_6

### ISSUE THREAD

**Issue by tedel** [void-linux/void-packages#45859]
### Is this a new report?

Yes

### System Info

Void 6.4.12_1 x86_64 AuthenticAMD notuptodate rrrmFFFFFFFFF

### Package(s) Affected

akonadi5 23.04.2_1

### Expected behaviour

Akonadi should connect to its mysqld configuration and allow users to open Akonadi-enabled applications (Kontact, kMail, kOrganizer, Akregator, kAddressBook).

### Actual behaviour

If I try to open an Akonadi-enabled application, nothing happens.

If I try to open them from Konsole, I get the following error message:

```
/usr/bin/mysqlcheck: Got error: 2013: Lost connection to MySQL server during query when executing 'REPAIR NO_WRITE_TO_BINLOG VIEW ... '
FATAL ERROR: Upgrade failed
org.kde.pim.akonadiserver: Failed to verify database server version
org.kde.pim.akonadiserver: Query error: "MySQL server has gone away QMYSQL: Unable to execute query"
org.kde.pim.akonadiserver: Database error: ""
org.kde.pim.akonadiserver: Shutting down AkonadiServer...
org.kde.pim.akonadicontrol: Application '/usr/bin/akonadiserver' exited normally...
```

I believe KDE PIM applications require an update from 23.04.0_2 to a newer version (23.08.0?)

### Steps to reproduce

1. Update MariaDB
2. Try to open Kontact
3. It does not open.

**Comment by HiPhish** [comment]
Same here, KMail is also affected.
