### ISSUE TITLE
dracut: functionality mismatch (performance enhancement for ssds)

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#45879]
There is a functionality mismatch.

https://github.com/void-linux/void-runit/pull/99

This only helps non-FDE luks.

https://github.com/dracutdevs/dracut/pull/2111/files

This addresses FDE scenario but was never merged.

Patching dracut on the voidlinux side may be a good idea?

**Comment by classabbyamp** [comment]
if dracut upstream didn't want this functionality change, we probably shouldn't diverge

**Comment by jackloomen** [comment]
I patched my dracut file as per that PR and it works.
Required explicit opt in.
