### ISSUE TITLE
encfs: segfaults with older directories

### ISSUE THREAD

**Issue by dezifit** [void-linux/void-packages#45916]
### Is this a new report?

Yes

### System Info

6.3.13_1 x86_64 (glibc)

### Package(s) Affected

encfs-1.9.5_6

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

After the last recent xbps/crypto update encfs now fails to mount some encrypted directories.  While newer ones (having .encfs6.xml) are working, older ones (with .encfs5.xml) are immediately crashing with a segfault:
```
Sep  5 12:35:32 solist kernel: [109292.081871] encfs[2218]: segfault at 78 ip 00007fc3f0f03d74 sp 00007ffecf112760 error 4 in libcrypto.so.3[7fc3f0dd0000+30c000] likely on CPU 5 (core 5, socket 0)
Sep  5 12:35:32 solist kernel: [109292.081888] Code: c3 0f 1f 44 00 00 41 54 55 89 f5 53 48 89 fb 48 81 ec a0 00 00 00 64 48 8b 04 25 28 00 00 00 48 89 84 24 98 00 00 00 48 8b 07 <48> 83 78 78 00 0f 84 c1 00 00 00 66 0f ef c0 0f 29 44 24 40 0f 29
```
There is a [debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014193) describing this problem and [mentioning a mitigation](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014193#35), which involves changes in `/etc/ssl/opensslf.conf`.

I changed the openssl configuration as described (using openssl.cnf.dist as base) and can confirm that it solves the encfs issue. Is a fix for encfs to be expected or what's the best approach in this case (besides avoding encfs altogether):
* applying the config change to openssl.cnf
* using a modified openssl.cnf.dist (as I did)

### Expected behaviour

Old encfs directories should be usable

### Actual behaviour

Trying to mount old encfs directories causes a segfault

### Steps to reproduce

Just access/open a old encrypted folder (using .encfs5.xml) requiring legacy crypto provider

**Comment by sgn** [comment]
Please test #45943

**Comment by dezifit** [comment]
`encfs` in export mode still allows selection of blowfish, which can be used to reproduce the segfault with a new created encrypted directory.

I did a short test of the patched `encfs` with blowfish encryption in new (encfs6) and old format and found no issues.
