### ISSUE TITLE
Package request: vscodium

### ISSUE THREAD

**Issue by brasb** [void-linux/void-packages#45967]
### Package name

vscodium

### Package homepage

https://vscodium.com/

### Description

Xbps only contains Code - OSS, but we should also have VSCodium. The reason for this is that Code - OSS violates the Marketplace's [terms of service](https://cdn.vsassets.io/v/M190_20210811.1/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf):

> Marketplace Offerings are intended for use only with In-Scope Products and Services and you may install and use Marketplace Offerings only with In-Scope Products and Services.

For this reason, VSCodium uses Open VSX instead of the Marketplace. Therefore, I think it is a good idea to include VSCodium in the repository.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

No

**Comment by classabbyamp** [comment]
#42328 #10582 #18314

**Comment by Zeitsperre** [comment]
The ToS argument hasn't been mentioned in the other issues (beyond the suggestion to block MS Marketplace). For more information on why that is important: https://ghuntley.com/fracture/.

I wouldn't mind giving a hand with this effort if it's an acceptable proposition.

**Comment by Vinfall** [comment]
I use VSCodium not just because of the telemetry removal, but also the alternative OpenVSX marketplace. It's still possible to install non-free proprietary extensions with the current `vscode` package which is a no-go for me.

**Comment by sgn** [comment]
> It's still possible to install non-free proprietary extensions with the current `vscode` package which is a no-go for me.

It's possible but noone put a gun into your mouth to force you install it. Just ignore and go on. Any problem with that?

**Comment by Vinfall** [comment]
It's fine as I'll use VSCodium instead just as always. I just find the reason not persuasive enough for the exclusion.

Despite being hilarious, it's also possible to use M$ marketplace on VSCodium by setting certain parameters, but of course no one sane is going to do that by replacing a _safer_ water blaster with a wheel gun in the same way🤷🏼
