### ISSUE TITLE
"linux6.5: configured successfully" without initramfs

### ISSUE THREAD

**Issue by Jipok** [void-linux/void-packages#46006]
### Is this a new report?

Yes

### System Info

Void 6.3.13_1 x86_64 GenuineIntel uptodate rrFFF

### Package(s) Affected

linux6.5-6.5.2_1

### Expected behaviour

It must either build successfully or fail without initramfs.

### Actual behaviour

After update my server couldn't boot due to missing initramfs. How can it be "configured successfully." with such a fatal error?
You can't expect the user to meaningfully review every line of logs for every update.
```
xbps-install -S linux6.5-6.5.2_1 linux6.5-headers-6.5.2_1
[*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/nonfree/x86_64-repodata' ...

Name             Action    Version           New version            Download size
linux6.5         install   -                 6.5.2_1                -
linux6.5-headers install   -                 6.5.2_1                -

Size required on disk:         206MB
Space available on disk:        16GB

Do you want to continue? [Y/n]

[*] Verifying package integrity
linux6.5-6.5.2_1: verifying RSA signature...
linux6.5-headers-6.5.2_1: verifying RSA signature...

[*] Collecting package files
linux6.5-6.5.2_1: collecting files...
linux6.5-headers-6.5.2_1: collecting files...

[*] Unpacking packages
linux6.5-6.5.2_1: unpacking ...
linux6.5-headers-6.5.2_1: unpacking ...

[*] Configuring unpacked packages
linux6.5-6.5.2_1: configuring ...
Executing post-install kernel hook: 10-dkms ...
Available DKMS module: zfs-2.1.12.
Building DKMS module: zfs-2.1.12... FAILED!
Generating kernel module dependency lists... done.
Executing post-install kernel hook: 20-initramfs ...
dracut-install: Failed to find module 'zfs'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.RJG7bp/initramfs --kerneldir /lib/modules/6.5.2_1/ -m zfs
dracut: installkernel failed in module zfs
Executing post-install kernel hook: 50-bootsize ...
Executing post-install kernel hook: 50-efibootmgr ...
Executing post-install kernel hook: 50-grub ...
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-6.5.2_1
Found linux image: /boot/vmlinuz-6.4.15_1
Found initrd image: /boot/initramfs-6.4.15_1.img
Found linux image: /boot/vmlinuz-6.3.13_1
Found initrd image: /boot/initramfs-6.3.13_1.img
Found linux image: /boot/vmlinuz-6.1.51_1
Found initrd image: /boot/initramfs-6.1.51_1.img
Warning: os-prober will not be executed to detect other bootable partitions.
Systems on them will not be added to the GRUB boot configuration.
Check GRUB_DISABLE_OS_PROBER documentation entry.
Adding boot menu entry for UEFI Firmware Settings ...
done
linux6.5-6.5.2_1: installed successfully.
linux6.5-headers-6.5.2_1: configuring ...
linux6.5-headers-6.5.2_1: installed successfully.

0 downloaded, 2 installed, 0 updated, 2 configured, 0 removed.
```

### Steps to reproduce

Just install linux6.5 with zfs.

**Comment by dkwo** [comment]
Building DKMS module: zfs-2.1.12... FAILED!

**Comment by classabbyamp** [comment]
> How can it be "configured successfully." with such a fatal error?

having a hook fail and causing an xbps operation to stop in the middle would be much worse, leading to issues with lots of half-configured packages

> You can't expect the user to meaningfully review every line of logs for every update.

it is kinda important to know what your system is doing, especially for updates. XBPS also puts important messages in the logs for things like breaking changes.

> Building DKMS module: zfs-2.1.12... FAILED!

the current release of ZFS doesn't support 6.5 and i'd suggest sticking to the `linux` or `linux-lts` metapackage when using ZFS, as those are guaranteed to be compatible with ZFS.

**Comment by Jipok** [comment]
> the current release of ZFS doesn't support 6.5

I know. This question is not about ZFS, but about the frustration associated with the inability to boot into the system after a “successful kernel update”. It’s not just the ZFS that can produce an error.

> it is kinda important to know what your system is doing, especially for updates. 

You can't say this seriously. I have my PC and home server. Both with void, both are updated on average once every couple of weeks. The number of logs you propose to view exceeds my ability to meaningfully read the logs. There are much more interesting and productive things in life than reading the logs of the next update simply because somewhere there may be a hint of a malfunction. And I'm sure that about 99.9% of void users, if they look at the update logs, then only briefly and conspicuous things. For example, a message that the kernel is not installed due to errors. At the end of the logs and preferably highlighted in red.

> having a hook fail and causing an xbps operation to stop in the middle would be much worse, leading to issues with lots of half-configured packages

I believe there may be specific cases where ignoring errors is useful. Well then you need at least an exception for the kernel.

**Comment by ahesford** [comment]
This issue is misplaced. A productive discussion on how to manage failed configuration could be had in the XBPS repository but, until some reasonable theory of operation is proposed in the package manager itself, there is nothing for us to do. In fact, [I proposed to honor thee failures](https://github.com/void-linux/void-packages/pull/32120) but withdrew the proposal because there is currently no clean way to handle this.

Yes, unobserved trigger failures are frustrating. Having a bunch of other packages also fail to configure because of it would be worse.

**Comment by Jipok** [comment]
It would be possible to make some kind of patch for update-grub to prevent kernels without initramfs by default. Or any other specific fix for this problem, even if not perfectly beautifully done.
But it's all or nothing. And since the “all” option is too complicated, subject to discussion, and no one wants to take on it, solutions to a specific and important problem are simply ignored and the discussion is closed. This sucks.

**Comment by ahesford** [comment]
The discussion was closed because, as I noted, it was misplaced. The issue you're reporting is that XBPS happily ignores failed post-install triggers when they fail. This is an XBPS issue and should be discussed there.

**Comment by Jipok** [comment]
> The issue you're reporting is that XBPS happily ignores failed post-install triggers when they fail. This is an XBPS issue and should be discussed there.

You are generalizing to a more complex problem. Which few people want to solve. And which can last for years.
Whereas the current problem, in my opinion, requires an urgent solution with some kind of hack. And if I understand correctly, the hack should be located in one of the packages. So this question is open here. Although it is related to the xbps problem you described, it has its own importance because it is the damn kernel and without it you get an unbootable machine.

**Comment by classabbyamp** [comment]
it's not unbootable if you have the previous kernel and initrd still. you can go to the "advanced options for void gnu/linux" submenu in GRUB to boot previous kernels (or you can add `GRUB_DISABLE_SUBMENU=yes` to `/etc/default/grub` and it will show up in the main menu)

**Comment by ahesford** [comment]
Well... it's not open anymore. 🤣

I understand your frustration, but
1) Recovery is easy: reboot and select the last-booted kernel, then fix the problem from there.
2) You were bitten by a ZFS incompatibility with your kernel, but users are expected to understand fundamental aspects of the packages they use, like what kernels are supported with ZFS.
3) I have a really hard time finding sympathy for a person whose response to "you should keep an eye on the update process" is "you can't expect me to do that!"

If you want to propose a sensible workaround for this XBPS problem in the GRUB package, you are free to submit a PR. But the fundamental issue here is with the package manager itself, not with any of the packages in this repository.

**Comment by Duncaen** [comment]
grub will pickup whatever kernel it finds when generating the configuration. Another successful kernel install/update/removal, a dkms module a install/update/removal or a grub update itself will all trigger the grub configuration to be regenerated.

Changing grub doesn't work either since some users might boot a kernel without an initramfs.

**Comment by Jipok** [comment]
> Recovery is easy: reboot and select the last-booted kernel, then fix the problem from there.

For laptop or pc. Not so easy for server.

> You were bitten by a ZFS incompatibility with your kernel, but users are expected to understand fundamental aspects of the packages they use, like what kernels are supported with ZFS.

Well, I’ve had zfs for 4 or 5 years now. But the problem with the update only appeared now. Perhaps earlier I successfully updated with a delay.

> Changing grub doesn't work either since some users might boot a kernel without an initramfs.

Are you sure that there really are such users? If their number does not exceed 5, why not leave a flag/option for them to allow updating with a missing initramfs, and for all others by default throw an error with the appropriate description (including the necessary flag to update the grub anyway)

**Comment by ahesford** [comment]
I thnk your best option would be to `noextract` the GRUB kernel hook, then replace it with your own that checks whether any kernel in `/boot` is missing an initramfs and, if so, abandon the GRUB configuration update.

If you're remotely updating a server and absolutely need it to come back up on a reboot, you should probably defer rebooting until you can get to a console. You should probably also stick with a known-good LTS kernel on systems you need to keep running in your absence.

**Comment by Duncaen** [comment]
> Are you sure that there really are such users? If their number does not exceed 5, why not leave a flag/option for them to allow updating with a missing initramfs, and for all others by default throw an error with the appropriate description (including the necessary flag to update the grub anyway)

Its the upstream grub.d hook (`/etc/grub.d/10_linux`) that generates the configuration file. We generally don't patch in features, especially not if it might break a specific use-case for which we don't know how many users depend on.
