### ISSUE TITLE
Package request: rio 0.0.18

### ISSUE THREAD

**Issue by raphamorim** [void-linux/void-packages#46012]
### Package name

rio

### Package homepage

https://github.com/raphamorim/rio

### Description

A hardware-accelerated GPU terminal emulator powered by WebGPU, focusing to run in desktops and browsers.
 
PR: https://github.com/void-linux/void-packages/pull/44823

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

No

**Comment by Clos3y** [comment]
> PR: https://github.com/void-linux/void-packages/pull/44823

Why put in the request if you know there's a PR waiting to be merged?

**Comment by raphamorim** [comment]
I assumed that since hasn't been merged right, would be ok since isn't my PR.
