### ISSUE TITLE
berry spawn zombie process

### ISSUE THREAD

**Issue by Fremen2001** [void-linux/void-packages#46039]
### Is this a new report?

Yes

### System Info

Void 6.4.15_1 x86_64 GenuineIntel uptodate rFFF

### Package(s) Affected

berry-0.1.12_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

issue already fixed upstream
https://github.com/JLErvin/berry/commit/3501ee006ee9bdddc817fd71750e431b4186a0c7

### Expected behaviour

no zombies allowed

### Actual behaviour

zombie

### Steps to reproduce

launch berry

**Comment by namgo** [comment]
Berry's latest version on github (Oct 2022) predates the patch mentioned (Nov 2022).

I'm somewhat new to package maintenance, is the correct solution to request that the Berry WM maintainer make a new release?

**Comment by Fremen2001** [comment]
the void package is based on berry 0.1.2 release, the patch was added after that and there is no new official release that fix this. Is like backporting fixes from unstable releases.

**Comment by namgo** [comment]
Oh! I might be on the wrong track, we can import the patch provided into the repo until the next official release. Are you comfortable doing this? If not I'll be able to work on it once I'm finished with another issue.
