### ISSUE TITLE
Package request: spacefm 2.1.0

### ISSUE THREAD

**Issue by zen0bit** [void-linux/void-packages#46103]
### Package name

spacefm 2.1.0

### Package homepage

https://github.com/IgnorantGuru

### Description

SpaceFm file manager

Original author not maintaining spacefm anymore.

But here is someone who working on it.
https://github.com/thermitegod/spacefm
 and packaging for gentoo

But can't be contacted. (As far as I know)
@thermitegod

I am looking for way build it on void.

It will need some dependencies not yet in void:

[CLI11](https://github.com/void-linux/void-packages/commit/25206d53e0a6da0c61dca2c4872b4bc70631bfc8) template from @tranzystorek-io  

[zmqpp](https://zeromq.github.io/zmqpp/)

(not released yet) [ztd](https://github.com/thermitegod/ztd)

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
Please don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.
