### ISSUE TITLE
`qt5` applications seem to still depend on `libssl1.1`

### ISSUE THREAD

**Issue by garylaski** [void-linux/void-packages#46123]
### Is this a new report?

Yes

### System Info

Void 6.3.13_1 x86_64 AuthenticAMD notuptodate rFF

### Package(s) Affected

qt5

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://bugreports.qt.io/browse/QTBUG-115146

### Expected behaviour

qt5 applications should work properly without the `libssl1.1` package.

### Actual behaviour

When using qt5 applications, they will not work if the `libssl1.1` package is not installed. A variation of the error will be thrown:
```
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
```

### Steps to reproduce

1. Install a qt5 application that uses OpenSSL  (e.g. `picard`)
2. `openssl-3.x` will be installed (ensure `libssl1.1` is not installed)
3. Try and run application 
5. Install `libssl1.1`
6. Error goes away

**Comment by chrysos349** [comment]
> See error

I couldn't reproduce your error. I installed `picard`. It launched fine. I did a lookup on one song.
`libssl1.1` is NOT installed on my machine.

**Comment by sgn** [comment]
can't reproduce.

`falkon` is a qt5 browser, and doesn't have problem.
