### ISSUE TITLE
Nvidia 535.113.01 boot is stuck on "loading initial ramdisk" with kernel 6.5.4 only.

### ISSUE THREAD

**Issue by SpidFightFR** [void-linux/void-packages#46208]
### Is this a new report?

Yes

### System Info

[can't have it since the kernel won't load - x86_64 GlibC]

### Package(s) Affected

nvidia-535.113.01 linux6.5-6.5.4

### Expected behaviour

The kernel should boot normally.

### Actual behaviour

The boot process hangs on "loading initial ramdisk".
This issue only occurs on linux 6.5.4, linux 6.5.3 is spared from this, it only suffers a LONG loading time.

### Steps to reproduce

1. install linux 6.5.4 kernel
2. install the nvidia module to its latest version
3. the issue happens on next reboot.

**Comment by classabbyamp** [comment]
are you sure it actually generated an initramfs successfully?

**Comment by SpidFightFR** [comment]
> are you sure it actually generated an initramfs successfully?

there were no errors whatsoever, so i believe yes.
plus my boot partition has 800mb of free space, so it can't be full.

**Comment by SpidFightFR** [comment]
I just installed linux6.5-6.5.5, the issue doesn't happen with this kernel. Perhaps it is specific to 6.5.4?

Anyways, issue closed.
