### ISSUE TITLE
Sagemath jupyter notebook not working

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#46261]
### Is this a new report?

Yes

### System Info

Void 6.5.5_1 x86_64 GenuineIntel uptodate rFFFFFFFFFFFFFFFFFFFFFFFFFFFF

### Package(s) Affected

sagemath-10.1_3

### Expected behaviour

```
sage -n jupyter
```

Opens a jupyter notebook.

### Actual behaviour

```
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.1, Release Date: 2023-08-20                    │
│ Using Python 3.11.5. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
Please wait while the Sage Jupyter Notebook server starts...
Traceback (most recent call last):
  File "/usr/lib/sagemath/10.1/bin/sage-notebook", line 32, in __init__
    from notebook.notebookapp import main
ModuleNotFoundError: No module named 'notebook.notebookapp'
The Jupyter notebook is not installed (at least not in this Sage installation).
You can install it by running
  sage -i notebook
Alternatively, you can follow the instructions at
  https://doc.sagemath.org/html/en/installation/launching.html#setting-up-sagemath-as-a-jupyter-kernel-in-an-existing-jupyter-notebook-or-jupyterlab-installation
to use Sage with an existing Jupyter notebook installation.
```

But `sage -i notebook` doesn't work either.

```
Error: unknown option: -i
```

### Steps to reproduce

1. Install `sagemath`.
2. Run `sage -n jupyter`.

**Comment by dkwo** [comment]
could you try #44160 ?

**Comment by Eloitor** [comment]
Thanks! I tried and I got:

```
$ sage -n jupyter
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.1, Release Date: 2023-08-20                    │
│ Using Python 3.11.5. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
Please wait while the Sage Jupyter Notebook server starts...
Traceback (most recent call last):
  File "/usr/lib/sagemath/10.1/bin/sage-notebook", line 32, in __init__
    from notebook.notebookapp import main
ModuleNotFoundError: No module named 'notebook.notebookapp'
The Jupyter notebook is not installed (at least not in this Sage installation).
You can install it by running
  sage -i notebook
Alternatively, you can follow the instructions at
  https://doc.sagemath.org/html/en/installation/launching.html#setting-up-sagemath-as-a-jupyter-kernel-in-an-existing-jupyter-notebook-or-jupyterlab-installation
to use Sage with an existing Jupyter notebook installation.
```

**Comment by dkwo** [comment]
can you test with `jupyter lab` ?

**Comment by Eloitor** [comment]
```
$ jupyter lab
Traceback (most recent call last):
  File "/usr/bin/jupyter-lab", line 5, in <module>
    from jupyterlab.labapp import main
ModuleNotFoundError: No module named 'jupyterlab'
```

I have `jupyterlab` installed.

**Comment by Eloitor** [comment]
Yes it is... I have it working in 2 computers, but it keeps failing in another one. I tried forcing reinstalling jupyter related packages without success...

**Comment by Eloitor** [comment]
I had to force the reinstall of some packages, maybe I had a problem with the update to python 3.12....

**Comment by tornaria** [comment]
> ```
> $ jupyter lab
> Traceback (most recent call last):
>   File "/usr/bin/jupyter-lab", line 5, in <module>
>     from jupyterlab.labapp import main
> ModuleNotFoundError: No module named 'jupyterlab'
> ```
> 
> I have `jupyterlab` installed.

This doesn't make sense, since `/usr/bin/jupyter-lab` and `/usr/lib/python3.12/site-packages/jupyterlab/labapp.py` are both in the same package `jupyterlab`. Do you have all those files?

Unless you are messing with virtual envs, pip, pipx, `PYTHONPATH`, etc.

Maybe try removing everything and reinstalling.

For the time being `sage -n jupyter` doesn't work, but it should be the same as running `jupyter notebook` or `jupyter lab`.

In case this is leftover stuff from a local build, try `xpkg -L` to show if you have packages installed locally  (e.g. maybe you have `jupyterlab` built for python 3.11). Use `xi -f` to force install packages so you get the versions from the void repos.

**Comment by Eloitor** [comment]
Solved, I got this error message:
```
Gtk-Message: 20:21:17.013: Failed to load module "canberra-gtk-module"
```

I reinstalled `libcanberra` and `libcanberra-gtk` and it finally worked. No idea what was happening.

**Comment by narodnik** [comment]
I had to install jupyter, python3-jupyter_notebook and I also [did these commands](https://doc.sagemath.org/html/en/installation/launching.html#setting-up-sagemath-as-a-jupyter-kernel-in-an-existing-jupyter-notebook-or-jupyterlab-installation), then it worked for me.

**Comment by tornaria** [comment]
> I had to install jupyter, python3-jupyter_notebook and I also [did these commands](https://doc.sagemath.org/html/en/installation/launching.html#setting-up-sagemath-as-a-jupyter-kernel-in-an-existing-jupyter-notebook-or-jupyterlab-installation), then it worked for me.

But you shouldn't do that if you use the `sagemath` package in the void repo, which already includes a jupyter kernel spec. Watch out that you don't have an older `sagemath` kernel installed in your home directory as that might override the system one.

System kernels are installed in `/usr/share/jupyter/kernels`, and user kernels are installed in `~/.local/share/jupyter/kernels/`.

Easiest way to try is to run `jupyter console --kernel=sagemath`. This should print the banner for the correct version of sagemath. Inside sage check the value of `SAGE_LOCAL` which should be `/usr` for system install of sagemath, and something else for a sage compiled from sources on your own.

**Comment by tornaria** [comment]
This is what I mean:
```
$ jupyter console --kernel=sagemath
[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
Jupyter console 6.6.3

┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.2, Release Date: 2023-12-03                    │
│ Using Python 3.12.1. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
In [1]: SAGE_LOCAL
Out[1]: '/usr'

In [2]: 
```
