### ISSUE TITLE
Remove remaining crypto currency packages `ardor` and `nxt`

### ISSUE THREAD

**Issue by porky11** [void-linux/void-packages#46274]
I don't like the removal of crypto currency package, especially Monero, but there's one pair of shitcoin packages you forgot to remove: `ardor` and `nxt`

**Comment by Bnyro** [comment]
ardor didn't get touched for 3 years now with any relevant updates, so I agree that it should be removed. Some crypto packages were readded if well maintained, most crypto packages have just been abandoned for a while and hence it didn't make sense to keep them.
nxt doesn't seem to be part of the repos anymore?

**Comment by m3tav3rse** [comment]
nxt is not in void-packages but can be downloaded and installed https://voidlinux.org/packages/?arch=x86_64&q=nxt
