### ISSUE TITLE
guake - vsed in do_check fails

### ISSUE THREAD

**Issue by Requion** [void-linux/void-packages#46288]
Hello,

i saw the subject line mentioned in #46170 . I like Guake and am actively using it, thus i would like to keep it working. Unfortunately my journey with Void and package maintenance just started and i lack the knowledge to fix it myself currently. For this reason, i wanted to provide my findings so far to help fixing the template as good as i can.

From what i could gather so far, the `vsed -i 's/from mock/from unittest.mock/g' guake/tests/test_quick_open.py` line fails because the directory `quake/tests/` does not exist in the tarball downloaded from pypi.org (it is included in the github tarball though). The `distfiles` property was changed from github to pypi in https://github.com/void-linux/void-packages/commit/eee156e480a0f5b5f89e94c9f59bb90e4bdd3cf9 [^1] by @Johnnynator , which, as per Guakes docs, is the correct approach to [build from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

There are multiple options to fix this, which is where i am uncertain about the correct approach.
1. Ask [upstream](https://github.com/Guake/guake) to include the tests in the tarball published on pypi
2. Remove the tests from the template (which were probably added for a reason)
3. Others which i personally see as *too hacky* like sideloading the tests

This said, i am looking forward on any feedback helping to fix the issue and improving my know-how on how to contribute.

Regards
Requion

[^1]: I searched / linked the commit to understand the turn of events, not to point fingers.

**Comment by mhmdanas** [comment]
> Ask upstream to include the tests in the tarball published on pypi

This is probably the most reasonable option, but otherwise option 2 is also fine (though not preferred).

**Comment by Requion** [comment]
I created Guake/guake#2204 to ask if the test can be added to the pypi tarballs or get some more clarification on the *intended* packaging process.
