### ISSUE TITLE
GTK Flatpak Apps no longer apply themes after update ?

### ISSUE THREAD

**Issue by SpidFightFR** [void-linux/void-packages#46311]
### Is this a new report?

Yes

### System Info

Void 6.5.5_1 x86_64 AuthenticAMD uptodate rrmFFFFFFFF

### Package(s) Affected

flatpak-1.15.4_2 flatpak-kcm-5.27.8_1 xdg-desktop-portal-gtk-1.14.1_2

### Expected behaviour

Given we grand read access to `~/.themes` and `~/.icons`, and that we enable a specific env var, the selected theme in the env var should be applied (it was up until recently).

### Actual behaviour

Recently, it stopped working, out of the blue, without any reasons. 

I believe it started happening since flatpak-kcm update, but i might be wrong.
QT apps do work as intended tho, so perhaps it is linked to the xdg gtk portal too?

### Steps to reproduce

1. sudo xbps-install -Su
2. Update flatpak-kcm
3. Theme no longer works on gtk apps :(

**Comment by mayhair** [comment]
See https://github.com/void-linux/void-packages/issues/46317#issuecomment-1742516097 for a fix.

**Comment by SpidFightFR** [comment]
Thank you, @mayhair ! :pray: 

Indeed this solved the issue for me.
If that can help someone, here is my config for Plasma: (this should be located in `~/.config/xdg-desktop-portal/` - for newcomers, to avoid more searching)

<details><summary>kde-portals.conf</summary>

```
[preferred]
# use xdg-desktop-portal-gtk for every portal interface
default=gtk
# except for the xdg-desktop-portal-wlr supplied interfaces
org.freedesktop.impl.portal.Screencast=kde
org.freedesktop.impl.portal.Screenshot=kde
#uses KDE file dialog instead of the gtk file dialog
org.freedesktop.impl.portal.FileChooser=kde
```

</details>

On a sidenote, this would be much appreciated from the xdg desktop portals team to let us *truly* know when such a major change comes up instead of doing it the shady way. :stuck_out_tongue_winking_eye:
