### ISSUE TITLE
GTK3 file chooser doesn't work after upgrading xdg-desktop-portal to 1.18.0_1

### ISSUE THREAD

**Issue by Aicaya** [void-linux/void-packages#46317]
### Is this a new report?

Yes

### System Info

Void 5.15.131_1 x86_64 AuthenticAMD notuptodate rrmDFFFFFFFFFFFF

### Package(s) Affected

xdg-desktop-portal-1.18.0_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

None that I could find.

### Expected behaviour

The file chooser should open when needed.

### Actual behaviour

It works correctly with GTK2, GTK4 and Qt apps, but on GTK3 apps it gives a `Can't open portal file chooser` error.  Forgot to copy the exact message, but the last bit says `No such interface “org.freedesktop.portal.FileChooser” on object at path /org/freedesktop/portal/desktop/`.

Downgrading back to version `1.16.0_2` fixes the issue (hence the `notuptodate` bit of the `xuname` output).

### Steps to reproduce

Test 1:
1. Open a program that uses GTK3 dialogs via the terminal (e.g. Firefox).
2. `Ctrl+O` to open up the file dialog (or go to "File > Open file" on the menu bar).
3. Doesn't open, error shows on terminal.

Test 2 (with zenity):
1. Run `zenity --file-selection` on the terminal.
2. File chooser doesn't pop up, error shows on terminal.

**Comment by MajesticFaucet** [comment]
same issue on `Void 6.1.54 x86_64 AuthenticAMD uptodate rFF`
using `sway` with `xdg-desktop-portal-gtk` and `Thunar` file manager.

file chooser broke after the `xdg-desktop-portal` update.

**Comment by RunningDroid** [comment]
This appears to be a result of `xdg-desktop-portal` requiring configuration as of 1.17.0 (even though they don't explicitly say it in the changelog*).
The intended behavior seems to be that desktop or distro devs will ship a `/usr/share/xdg-desktop-portal/${DESKTOP}-portals.conf` to set the default portals for a desktop or `xdg-desktop-portal` will just fail without a fallback if nothing's configured: https://github.com/flatpak/xdg-desktop-portal/issues/1077

In that issue ibotty provided a snippet that restores the previous behavior when installed to `.config/xdg-desktop-portal/sway-portals.conf`:
```
[preferred]
# use xdg-desktop-portal-gtk for every portal interface
default=gtk
# except for the xdg-desktop-portal-wlr supplied interfaces
org.freedesktop.impl.portal.Screencast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
```
and the documentation for the portal configuration is here: https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst

*: https://raw.githubusercontent.com/flatpak/xdg-desktop-portal/main/NEWS :
```
- Rework how portal implementations are loaded. This new, more robust system
  allows selecting specific backends for specific portals, and layering them
  when necessary. Platforms that provide portals implementation are encouraged
  to provide a suitable configuration file.
```

**Comment by MajesticFaucet** [comment]
> ```
> [preferred]
> # use xdg-desktop-portal-gtk for every portal interface
> default=gtk
> # except for the xdg-desktop-portal-wlr supplied interfaces
> org.freedesktop.impl.portal.Screencast=wlr
> org.freedesktop.impl.portal.Screenshot=wlr
> ```

Thanks, file chooser works after making the config change.

**Comment by mayhair** [comment]
> In that issue ibotty provided a snippet that restores the previous behavior when installed to `.config/xdg-desktop-portal/sway-portals.conf`:
> 
> ```
> [preferred]
> # use xdg-desktop-portal-gtk for every portal interface
> default=gtk
> # except for the xdg-desktop-portal-wlr supplied interfaces
> org.freedesktop.impl.portal.Screencast=wlr
> org.freedesktop.impl.portal.Screenshot=wlr
> ```

I put this text in /usr/share/xdg-desktop-portal/gnome-portals.conf (since I am using GNOME), and it helped solve a related issue where Flatpak applications would not use my system theme and button order.

**Comment by paper42** [comment]
> > In that issue ibotty provided a snippet that restores the previous behavior when installed to `.config/xdg-desktop-portal/sway-portals.conf`:
> > ```
> > [preferred]
> > # use xdg-desktop-portal-gtk for every portal interface
> > default=gtk
> > # except for the xdg-desktop-portal-wlr supplied interfaces
> > org.freedesktop.impl.portal.Screencast=wlr
> > org.freedesktop.impl.portal.Screenshot=wlr
> > ```
> 
> I put this text in /usr/share/xdg-desktop-portal/gnome-portals.conf (since I am using GNOME), and it helped solve a related issue where Flatpak applications would not use my system theme and button order.

wlr and xdg-desktop-portal-wlr is correct only for wlroots based compositors which gnome is not. As far as I know, the last 3 lines should only be necessary on wlroots compositors and it should work ootb without any special config with GNOME.
