### ISSUE TITLE
resythesizer has missing dependency since last update

### ISSUE THREAD

**Issue by habiloid** [void-linux/void-packages#46337]
### Is this a new report?

Yes

### System Info

Void 6.1.34_1 x86_64-musl AuthenticAMD uptodate rFFF

### Package(s) Affected

resynthesizer-2.0.3_1

### Expected behaviour

Package should install

### Actual behaviour

MISSING: libgimp-2.10.34_1
Transaction aborted due to unresolved dependencies

### Steps to reproduce

xbps-install -u resynthesizer

**Comment by classabbyamp** [comment]
resynthesizer was removed with gimp-python. It may be re-added when gimp updates to python 3

**Comment by classabbyamp** [comment]
[resynthesizer has been restored now](https://github.com/void-linux/void-packages/commit/29e17eb85d1985a107ae4850c91e26e40de41e80)
