### ISSUE TITLE
google-chrome ERROR: SHA256 mismatch for EULA

### ISSUE THREAD

**Issue by rickalex21** [void-linux/void-packages#46347]
### Is this a new report?

Yes

### System Info

Void 6.3.13_1 x86_64 AuthenticAMD uptodate rFFFFF

### Package(s) Affected

google-chrome-115.0.5790.110_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

no

### Expected behaviour

Expected to upgrade google-chrome.

### Actual behaviour

=> ERROR: SHA256 mismatch for EULA:
c57f6063f0ef7f6cd0f93cc6004ba86be0df36eca92be054bbb3b424dbd7830c

### Steps to reproduce

xbps-src pkg google-chrome

**Comment by classabbyamp** [comment]
we should really be doing the EULA file like discord and a few other packages (i.e. a file with a link to the current terms)

**Comment by tuxslack** [comment]
**maintainer:** Michael Aldridge <maldridge@voidlinux.org>
**homepage:** https://www.google.com/chrome/
**filename-sha256:** b3417497ae1b375962b121e0b20727c667c689cfdceacc43dd4e94cc32c63fb0
**metafile-sha256:** aa00be5f9546cae372b4eb0ae3b7665023e9fe5e0e85803d4cc5d29fdee423cf

===============================================================

cd ~/void-packages/

git pull && ./xbps-src update-sys

...

=> xbps-src: the following packages must be rebuilt and updated:
 google-chrome
=> xbps-src: building google-chrome-117.0.5938.132_1 ...
=> xbps-src: updating repositories for host (x86_64)...
[*] Updating repository `https://repo-default.voidlinux.org/current/bootstrap/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/nonfree/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/debug/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/bootstrap/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
=> xbps-src: updating software in / masterdir...
=> xbps-src: cleaning up / masterdir...
=> google-chrome-117.0.5938.132_1: removing autodeps, please wait...
=> google-chrome-117.0.5938.132_1: building for x86_64...
   [host] python3-html2text-2020.1.16_5: found (https://repo-default.voidlinux.org/current)
   [host] python3-setuptools-68.2.2_1: found (https://repo-default.voidlinux.org/current)
   [runtime] gtk+3-3.24.38_1: found (https://repo-default.voidlinux.org/current)
=> google-chrome-117.0.5938.132_1: installing host dependencies: python3-html2text-2020.1.16_5 python3-setuptools-68.2.2_1 ...
=> google-chrome-117.0.5938.132_1: running do-extract hook: 00-distfiles ...
=> google-chrome-117.0.5938.132_1: extracting distfile(s), please wait...
=> google-chrome-117.0.5938.132_1: running post_extract ...
google-chrome-eula.html: [93KB 4%] 20KB/s ETA: 00m00s
google-chrome-eula.html: [93KB 21%] 18KB/s ETA: 00m03s
google-chrome-eula.html: [93KB 59%] 27KB/s ETA: 00m01s
google-chrome-eula.html: [93KB 77%] 24KB/s ETA: 00m00s
google-chrome-eula.html: 93KB [avg rate: 31KB/s]
**=> ERROR: SHA256 mismatch for EULA:
c57f6063f0ef7f6cd0f93cc6004ba86be0df36eca92be054bbb3b424dbd7830c
=> ERROR: xbps-src: failed to build google-chrome-117.0.5938.132_1 pkg!**
