### ISSUE TITLE
telegram-desktop

### ISSUE THREAD

**Issue by hholst80** [void-linux/void-packages#46376]
### Is this a new report?

Yes

### System Info

Void 6.3.13_1 x86_64 GenuineIntel notuptodate rrFFFF

### Package(s) Affected

telegram-desktop-4.10.1_2

### Expected behaviour

telegram desktop should start

### Actual behaviour

# telegram-desktop
telegram-desktop: symbol lookup error: /usr/lib64/libglibmm-2.68.so.1: undefined symbol: g_utf8_truncate_middle

### Steps to reproduce

1. install
2. run

**Comment by namgo** [comment]
Is it possible you need to update your system? `g_utf8_truncate_middle` https://gitlab.gnome.org/GNOME/glib/-/merge_requests/3440 was added fairly recently and `glibmm2.68` is versioned I believe.

**Comment by hholst80** [comment]
The issue went away here too after a full system upgrade so probably not a big thing worth digging into. Thanks for checking!
