### ISSUE TITLE
Linux kernel 6.5, 6.6: System not waking up from standby / suspend.

### ISSUE THREAD

**Issue by gc-user** [void-linux/void-packages#46427]
### Is this a new report?

Yes

### System Info

Void 6.3.13_2 x86_64 GenuineIntel uptodate hold rrmDDFFFFFFFFF

### Package(s) Affected

linux / linux6.5 / linux6.6 (maybe linux-headers / linux6.5-headers / linux6.6-header)

### Does a report exist for this bug with the project's home (upstream) and/or another distro?
No. All somewhat comparable reports I came across were either reporting that the system doesn't wake just some of the time, or the waking up itself isn't the problem, but the system freezes after waking up.

### Expected behaviour

The system should wake up from standby / suspend when hitting a key on the keyboard or pressing the power button, but it doesn't.
This happened once in a while with previous kernel versions (<= 6.3), but with kernel v6.5 it happens 100% of the time.

Also: I put linux and linux-headers on hold and updated all the other packages that had updates yesterday, including zfs and linux6.3. No issues with waking up the system from standby with those updates. So, it most probably is linux / linux6.5 that's causing the issue.

### Actual behaviour

The system can't be woken up by hitting a key on the keyboard or pressing the power button from standby / suspend. To be more specific, it's the computer not waking up at all (i.e. the led is still showing standby mode) - it's not the computer waking up but showing a black screen, which apparently is another way of "unsuccessful awakening" from standby.

Comparing kernel logs for kernel 6.1, 6.3, 6.4 vs 6.5 and 6.6, I only noticed so far as common to the behavior, that with kernel 6.5 and 6.5 the kernel doesn't acknowledge that suspend has been initiated.

Messages just before going into s3:

kernel v6.1:
[elogind-daemon] Entering sleep state 'suspend'...
[kernel] PM: suspend entry (deep)

kernel v6.3, v6.4:
[elogind-daemon] Suspending system...
[kernel] PM: suspend entry (deep)

kernel v6.5, v6.6:
[elogind-daemon] Entering sleep state 'suspend'...

-> the message "[kernel] PM: suspend entry (deep)" never shows up in logs with kernels v6.5 and v6.6.

### Steps to reproduce

0. linux / linux-headers was upgraded to kernel 6.5 from 6.3 yesterday., with v6.5.5_2 being the current version of the kernel installed.
1. Update linux / linux-headers (or install kernel 6.5 via installing linux6.5 / linux6.5-headers).
2. Reboot to make the system run kernel 6.5.
3. Send the system to standby / suspend.
4. Try to wake the system up from standby / suspend.
5. Notice (probably) nothing happening = the system (probably) not waking up from standby / suspend.

If it is DE dependent: My system runs xfce.

**Comment by gc-user** [comment]
Additional hardware info:

CPU: Intel Sky Lake
Intel HD onboard graphics

I just retested with the new kernel v6.5.6. The issue is still present, no reaction on hitting a key on internal or external keyboard or the power button (other than hard reset when pushing the button for 7? seconds).

**Comment by Fremen2001** [comment]
I can confirm the above, same kernel 6.5.6_1. On my laptop Dell E7250 after using the standby button the only way to wake it up is by pressing the power button. I'm pretty sure this was the same with older kernels.

**Comment by gc-user** [comment]
I just updated the bug report, as I didn't make it clear that I can't wake up my system by any means, not even by pressing the power button. The only way to use my system again is long-pressing the power button to enforce a hard reset and boot into a boot environment with a kernel that's not v6.5, in my case v6.3.

**Comment by gc-user** [comment]
Update on the issue:

On an older system, but also Thinkpad, resume from standby / suspend works as with earlier kernels.
Tested with kernel v6.5.9_1.

Maybe it's an issue with certain chip sets or something.

The older one is Sanfy Bridge, the newer one Kaby Lake.

**Comment by gc-user** [comment]
Another update:

As per this [thread](https://forum.manjaro.org/t/my-laptop-often-fails-to-resume-from-sleep-no-reaction-on-pressing-keyboard-keys/149656/12), at least one other user has a Kaby Lake system that has this problem, and also, apparently, kernel 6.6 works.
But as (open)zfs isn't yet compatible with kernel 6.6, I hope they backport the changes that fix that problem back into kernel 6.5.

**Comment by 0x5c** [comment]
Also Kaby Lake here, same symptoms on 6.5. I currently keep my laptop on 6.1 (`linux-lts`).

I also have openzfs, so I can't test 6.6. Has the fix in 6.6 been identified? I cannot find an upstream bug report for the issue.

**Comment by gc-user** [comment]
Not sure. There are several mentions of suspend / resume [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/?h=v6.6&showmsg=1), but only one or two might actually include our problem. The others seem too specific for cases that don't apply in my case. But it's still noteworthy how many suspend / resume errors they apparently introduced.

However, 2 of those issues are also mentioned in the [changelog](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.5.10) for kernel 6.5.10. So, I'll be testing that one when it's available for void.

No mention of Kaby Lake, though.

**Comment by 0x5c** [comment]
Hum, all of those seem to be for s2idle "sleep" and ATA HDD sleep bugs

**Comment by gc-user** [comment]
Update after further tests:

Kernel v6.4.16 works.

Kernels v6.5.11 and v6.5.12 don't work

Now that zfs supports kernel 6.6, I tested kernel v6.6.2. Unfortunately, it doesn't work.

**Comment by gc-user** [comment]
Some good news.

I found a workaround: Disabling VT-d in BIOS (Security -> Virtualization) circumvents this bug. Although I dan't know if and how that influences the use of VirtualBox, qemu or virt-manager.

**Comment by 0x5c** [comment]
> Some good news.
> 
> I found a workaround: Disabling VT-d in BIOS (Security -> Virtualization) circumvents this bug. However, I don't know if and how that influences the use of VirtualBox, qemu or virt-manager.

VT-d is virtualisation iommu support, so affects any VM that accesses IO. Not so great

However that find is still very good news, it helps limiting where to search for the bug

**Comment by gc-user** [comment]
Yeah, I'm aware of that. But the question is, what are the real world consequences.
I did a quick queck on a VirtualBox VM. Mouse, keyboard, printer, all there, no problem - apparently they are all virtualized, not directly accessed (which is what the "d" in VT-d stands for, as far as I understand) by the VM. So, the impact isn't that massive for a temporary solution until the kernel team fixes the issue.

**Comment by 0x5c** [comment]
> Yeah, I'm aware of that. But the question is, what are the real world consequences.

Inability to use non-virtualised devices, which is complete breakage for a lot of use-cases, including giving a VM access to an actual GPU.

**Comment by 0x5c** [comment]
Relevant kernel bug report: https://bugzilla.kernel.org/show_bug.cgi?id=218191

There's a proposed fix in there, but it seems a bit dubious it's the proper fix (written for a bug in AMD workstation CPUs, while both cases here are on intel laptops).
Without confirmation that it would be a fix for the right thing, I don't really want to go down the rabbit hole of trying to build it on the affected laptop.

**Comment by gc-user** [comment]
Thanks for the info!
I guess I'll wait until the kernel team has fixed the issue. v6.1 is good enough for me for now.

**Comment by 0x5c** [comment]
@Fremen2001 Is it correct that your bug is that the lid switch does not respond, but the computer wakes back up to the system without a full boot when doing a simple press on the power button? If so that's a different problem.

So there's 2~3 users with the bug here, two with a very similar configuration (Void-built kernels, ZFS, Kaby Lake Intel CPUs, Thinkpads). I'm not sure if the original message in the kernel bugzilla is by @gc-user, if not then that's yet another very similar setup). I'm starting to think it might be (partially) caused by a kernel dotconfig change in Void?

There's the user on the linux mint forums with same CPU family (maybe also Thinkpad?), but problems on Mint and completely different kernel versions.

I wonder what changes to kernel dotconfigs and patches have happened in Mint packaging starting with 6.x and ending at roughly 6.6.

**Comment by gc-user** [comment]
Update:

Seems like the kernel team found the problem that the faulty commit caused and provided a fix. It's labelled "urgent" in their internal email system, so it might be coming with a kernel update not too far off... (maybe 20th of Dec? + how many days until it comes to void - unless one likes to build the kernel oneself)

**Comment by gc-user** [comment]
Good news:

The fix was merged into the upcoming kernel v6.7 by Linus Torvalds on Dec 23rd, and into the upcoming kernel v6.6.9 just a few hours ago. v6.6.9 should be out sometime next week.

**Comment by gc-user** [comment]
So, now that kernel v6.6.9 is out and the bug is fixed, this issue report can be closed.
At least on my system the issue does no longer occur with v6.6.9.
