### ISSUE TITLE
Package Request:v2ray

### ISSUE THREAD

**Issue by YaeMashiro** [void-linux/void-packages#4646]
https://github.com/v2ray/v2ray-core
https://v2ray.com/en/index.html

Project V is a set of tools to help you build your own privacy network over internet. The core of Project V, named V2Ray, is responsible for network protocols and communications. It can work alone, as well as combine with other tools.

**Comment by LinArcX** [comment]
Any update or news?
I really need this package.
Actually i can package softwares.And also i looked at PKGBUILD of this package in aur. But it's too complicated and i don't have any experienct to package go-softwares.

**Comment by ipkalm** [comment]
Hi. Package added. #31653
