### ISSUE TITLE
sudo is not able to set TERMINFO with kitty-0.30

### ISSUE THREAD

**Issue by Sqvid** [void-linux/void-packages#46485]
### Is this a new report?

Yes

### System Info

Void 6.5.5_2 x86_64 GenuineIntel notuptodate rrDFFFFF

### Package(s) Affected

kitty-0.30.1_1, kitty-kitten-0.30.1_1, kitty-shell-integration-0.30.1_1, kitty-terminfo-0.30.1_1

### Expected behaviour

Running a command like `sudo xbps-install -Su` should proceed normally.

### Actual behaviour

`sudo xbps-install -Su` returns with `sudo: sorry, you are not allowed to set the following environment variables: TERMINFO`. 

This does not happen on other terminals and can be fixed by downgrading to `kitty-0.29.2_3`

### Steps to reproduce

1. Update to `kitty*-0.30.1_1`
2. Run `sudo xbps-install -Su`
3. Be sad

**Comment by classabbyamp** [comment]
see https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.shell_integration

**Comment by Sqvid** [comment]
> see https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.shell_integration

Thank you for the reply. Forgive my ignorance but it is not immediately obvious to me how this ties into the error. Are you suggesting disabling shell integration?

**Comment by Sqvid** [comment]
Nevermind, I understand you now! My bad. Setting `shell_integration no-sudo` does fix the issue. Many thanks.
