### ISSUE TITLE
Package request: qtile-extras

### ISSUE THREAD

**Issue by kobzar** [void-linux/void-packages#46496]
### Package name

qtile-extras

### Package homepage

https://qtile-extras.readthedocs.io/en/stable/manual/install.html

### Description

Pack of widgets for Qtile wm

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by kaistian** [comment]
This issue was resolved with https://github.com/void-linux/void-packages/pull/48312
