### ISSUE TITLE
Package request: Incus

### ISSUE THREAD

**Issue by sbromberger** [void-linux/void-packages#46536]
### Package name

incus

### Package homepage

https://github.com/lxc/incus

### Description

Incus is a fork of Canonical's LXD container management system. The lead LXD developer recently joined Incus. Version 0.1 was recently released - it corresponds roughly to LXD 5.18.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by tranzystorekk** [comment]
Can be closed: https://github.com/void-linux/void-packages/pull/47573
