### ISSUE TITLE
Package request: python-lsp-ruff

### ISSUE THREAD

**Issue by ElDifinitivo** [void-linux/void-packages#46560]
### Package name

python-lsp-ruff

### Package homepage

https://github.com/python-lsp/python-lsp-ruff

### Description

python-lsp-ruff is a plugin for python-lsp-server that adds linting, code action and formatting capabilities that are provided by ruff, an extremely fast Python linter written in Rust.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by ElDifinitivo** [comment]
It seems like [ruff-lsp](https://github.com/astral-sh/ruff-lsp) is meant to act as its own language server, while [python-lsp-ruff](https://github.com/python-lsp/python-lsp-ruff) works together with [pylsp](https://github.com/python-lsp/python-lsp-server) as a plugin, which is already in the repo.

Just coming from the perspective of someone who uses [helix](https://github.com/helix-editor/helix/) as their editor, this package would be more beneficial as only one LSP can be active, which allows me to continue to use `pylsp` alongside the capabilities of `ruff`.

**Comment by jlhamilton777** [comment]
Helix can use more than one language server per language now: https://helix-editor.com/news/release-23-10-highlights/#multiple-language-servers. I've been using it with ruff-lsp, which is from the same team that makes ruff.

**Comment by jlhamilton777** [comment]
They are going to add a `ruff server` command to `ruff` that provides an LSP.

https://github.com/astral-sh/ruff/pull/10158

**Comment by classabbyamp** [comment]
ruff lsp is built in now
