### ISSUE TITLE
Package request: radeon-profile

### ISSUE THREAD

**Issue by onli** [void-linux/void-packages#4659]
Website: https://github.com/marazmista/radeon-profile

"Application to read current clocks of ATi Radeon cards (xf86-video-ati, xf86-video-amdgpu)." It actually does more, it allows setting a fancurve and even to overclock. To work best without root rights it also needs https://github.com/marazmista/radeon-profile-daemon.

**Comment by Cogitri** [comment]
Should be closed, #4910 introduced those packages.
