### ISSUE TITLE
prepare-32bit hook fails for meta (sub)packages

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-packages#46612]
### Discussed in https://github.com/void-linux/void-packages/discussions/45987

<div type='discussions-op-text'>

<sup>Originally posted by **SpidFightFR** September  9, 2023</sup>
Hey, i got a question.

I made a pull request to update mesa to version 23.1.6 (https://github.com/void-linux/void-packages/pull/45635), when i was in vacation. Everything went well.
Though yesterday i made a PR for mesa 23.1.7 (https://github.com/void-linux/void-packages/pull/45974), and closed the previous PR, to not flood the Pull requests, but i saw that mesa 23.1.7 i686 build in the workflow failed so i guessed it wasn't ready yet. 

So i reactivated the PR for 23.1.6 which we knew went correctly before i close it. But the same bug for the `Build packages (i686, i686, glibc, linux/386, 1)` workflows happens for no reason:

```
cp: cannot stat '/destdir//mesa-ati-dri-23.1.7/*': No such file or directory
=> ERROR: mesa-ati-dri-23.1.7_1: post-install_80-prepare-32bit: 'cp -a ${PKGDESTDIR}/* ${destdir32}/' exited with 1
=> ERROR:   in hook() at common/hooks/post-install/80-prepare-32bit.sh:64
=> ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
=> ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:262
=> ERROR:   in main() at common/xbps-src/libexec/xbps-src-doinstall.sh:66
```
(this is the error i got for 23.1.7, but 23.1.6  gets the same error)

I'm unsure why it happens, especially for 23.1.6 because, again, it worked before i closed it.

If someone can help, it would be much appreciated.</div>

**Comment by SpidFightFR** [comment]
Just to get the notification, and for tracking purposes, the current PR is https://github.com/void-linux/void-packages/pull/46172
