### ISSUE TITLE
Package request: cycle

### ISSUE THREAD

**Issue by gstor2018** [void-linux/void-packages#4663]
"Cycle is a calendar program for women. Given a cycle length or statistics for several periods, it can calculate the days until menstruation, the days of "safe" sex, the fertile period, and the days to ovulations, and define the d.o.b. of a child. It allows the user to write notes and helps to supervise the reception of hormonal contraceptive tablets. Cycle is written in Python (also wxPython required) and distributed under the GNU General Public License."

http://cycle.sourceforge.net/
https://sourceforge.net/projects/cycle/files/cycle/

**Comment by gstor20l8** [comment]
This updated fork of cycle works on my fresh install of void-live-x86_64-20181111-xfce:

https://github.com/jose1711/cycle
https://github.com/jose1711/cycle/archive/master.zip

I extracted the contents of cycle-master.zip then installed wxpython, and manually copied the application's bitmaps and icons to the locations where the application expect them. The python script then ran without problems:

```
sudo xbps-install -S wxpython
sudo cp -r cycle-master/bitmaps /usr/share/cycle
sudo cp -r cycle-master/icons /usr/share/cycle
cycle-master/cycle.py
```
