### ISSUE TITLE
Building mesa on arm and aarch64 platforms fail

### ISSUE THREAD

**Issue by SpidFightFR** [void-linux/void-packages#46674]
Discussed here https://github.com/void-linux/void-packages/pull/46635

Now mesa builds work for both musl and glibc, even i686, yet it seems the modifications have brought a new issue to #46172:

<details><summary>Error when building for arm and aarch64 platforms</summary>

```
[2474/2653] Linking target src/gallium/targets/opencl/libMesaOpenCL.so.1.0.0
FAILED: src/gallium/targets/opencl/libMesaOpenCL.so.1.0.0 
aarch64-linux-gnu-c++  -o src/gallium/targets/opencl/libMesaOpenCL.so.1.0.0  -L/usr/aarch64-linux-gnu/usr/lib -I/usr/aarch64-linux-gnu/usr/include -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libMesaOpenCL.so.1 -Wl,--whole-archive src/gallium/frontends/clover/libclover.a -Wl,--no-whole-archive -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -fstack-clash-protection -D_FORTIFY_SOURCE=2 -O2 -pipe -march=armv8-a -ffile-prefix-map=/builddir/mesa-23.1.9/build=. -Wl,-rpath,/usr/aarch64-linux-gnu/usr/lib64:/usr/lib -Wl,-rpath-link,/usr/aarch64-linux-gnu/usr/lib64 -Wl,-rpath-link,/usr/lib src/gallium/auxiliary/pipe-loader/libpipe_loader_dynamic.a src/loader/libloader.a src/util/libxmlconfig.a src/util/libmesa_util.a src/util/format/libmesa_format.a src/util/libmesa_util_sse41.a src/c11/impl/libmesa_util_c11.a src/gallium/auxiliary/libgallium.a src/compiler/nir/libnir.a src/compiler/libcompiler.a src/gallium/frontends/clover/libclllvm.a src/gallium/frontends/clover/libclspirv.a src/gallium/frontends/clover/libclnir.a -Wl,--gc-sections -Wl,--version-script /builddir/mesa-23.1.9/src/gallium/targets/opencl/opencl.sym /usr/aarch64-linux-gnu/usr/lib/libz.so -pthread -lm /usr/aarch64-linux-gnu/usr/lib/libzstd.so /usr/aarch64-linux-gnu/usr/lib64/libelf.so /usr/lib/libclang-cpp.so /usr/aarch64-linux-gnu/usr/lib64/libdrm.so /usr/aarch64-linux-gnu/usr/lib64/libexpat.so /usr/aarch64-linux-gnu/usr/lib64/libxcb-randr.so -L/usr/lib -lLLVM-15 -lsensors -L/usr/lib -lLLVM-15 /usr/aarch64-linux-gnu/usr/lib/libLLVMSPIRVLib.so /usr/aarch64-linux-gnu/usr/lib64/libSPIRV-Tools-opt.a /usr/aarch64-linux-gnu/usr/lib64/libSPIRV-Tools.a /usr/aarch64-linux-gnu/usr/lib64/libSPIRV-Tools-link.a -Wl,--end-group
[cc-wrapper] ignoring -L/usr/lib
[cc-wrapper] ignoring -L/usr/lib
/usr/lib/gcc/aarch64-linux-gnu/12.2.0/../../../../aarch64-linux-gnu/bin/ld: /usr/lib/libclang-cpp.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
[2475/2653] Generating src/gallium/frontends/rusticl/rustmod-bindgen-rusticl_opencl_bindings.h with a custom command
ninja: build stopped: subcommand failed.
```

</details>

Is there some kind of patch i can try to make for it to work ?

**Comment by classabbyamp** [comment]
cc @sgn

**Comment by SpidFightFR** [comment]
see the [workflows](https://github.com/void-linux/void-packages/actions/runs/6516336467?pr=46172) for more details

**Comment by sgn** [comment]
Does it work before modification?

**Comment by Johnnynator** [comment]
This failure was to be expected. #46635 only allows to remove some of the sed in the `post_configure` of mesa, the `regenerate` hack I suggested and sed of linking arguments are still needed.

**Comment by SpidFightFR** [comment]
> Does it work before modification?

Yes it used to build everywhere except i686 initially. Now everything aarch64 or arm doesn't work.

**Comment by SpidFightFR** [comment]
> This failure was to be expected. #46635 only allows to remove some of the sed in the `post_configure` of mesa, the `regenerate` hack I suggested and sed of linking arguments are still needed.

Should i re-add the line you suggested into the template, even with the PR being merged?

**Comment by SpidFightFR** [comment]
> This failure was to be expected. #46635 only allows to remove some of the sed in the `post_configure` of mesa, the `regenerate` hack I suggested and sed of linking arguments are still needed.

I will try to re-add  your hack, but atm i have a ton of work on my personal side, so i want to apologize for keeping you waiting

**Comment by zlice** [comment]
https://github.com/void-linux/void-packages/pull/46850 and https://github.com/void-linux/void-packages/pull/46851 seem related. 32bit arm builds have lib64 dir for some reason. Previous qt6ct-0.8 fails the same way with current build packages.

**Comment by SpidFightFR** [comment]
> #46850 and #46851 seem related. 32bit arm builds have lib64 dir for some reason. Previous qt6ct-0.8 fails the same way with current build packages.

it seems a bit different for you, on my side, it's the whole aarch64 and ARM that fails for me, for you, it's only ARM.

**Comment by mhmdanas** [comment]
I think this is fixed now?

**Comment by SpidFightFR** [comment]
My apologies, it is fixed. I will close this issue now.
