### ISSUE TITLE
hplip fails to execute basic commands, most likely due to Python 3.12 update

### ISSUE THREAD

**Issue by slender100** [void-linux/void-packages#46684]
### Is this a new report?

Yes

### System Info

Void 6.5.7_1 x86_64 AuthenticAMD uptodate rFF

### Package(s) Affected

hplip-3.23.3_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No

### Expected behaviour

hplip is supposed to function properly with commands like `hp-setup` or `hp-doctor`, as well as other applications that depend on it, i.e hplip-gui.

### Actual behaviour

Any command outputs with this error:

```py
slender@slender ~]$ hp-setup 
/usr/bin/hp-setup:82: SyntaxWarning: invalid escape sequence '\*'
  ("To specify the port on a multi-port JetDirect:", "--port=<port> (Valid values are 1\*, 2, and 3. \*default)", "option", False),
/usr/bin/hp-setup:86: SyntaxWarning: invalid escape sequence '\*'
  ("Type of queue(s) to install:", "-t<typelist> or --type=<typelist>. <typelist>: print*, fax\* (\*default) (-i mode only)", "option", False)
Traceback (most recent call last):
  File "/usr/bin/hp-setup", line 47, in <module>
    from base.g import *
  File "/usr/share/hplip/base/g.py", line 240, in <module>
    sys_conf = SysConfig()
               ^^^^^^^^^^^
  File "/usr/share/hplip/base/g.py", line 185, in __init__
    ConfigBase.__init__(self, '/etc/hp/hplip.conf')
  File "/usr/share/hplip/base/g.py", line 90, in __init__
    self.read()
  File "/usr/share/hplip/base/g.py", line 131, in read
    self.conf.readfp(fp)
    ^^^^^^^^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
```

### Steps to reproduce

1. Install hp-lip with `sudo xbps-install -Suv hplip`.
2. Run any hplip command like `hp-setup`, for example.
3. Confirm that the same error happens with the one shown in this report.

**Comment by ahesford** [comment]
Are you able to confirm that https://github.com/void-linux/void-packages/pull/46704 resolves the issue?

**Comment by slender100** [comment]
> Are you able to confirm that #46704 resolves the issue?

I am currently unable to update to the latest version:

```
[slender@slender ~]$ sudo xbps-install -Su hplip
[*] Updating repository `https://mirror.clarkson.edu/voidlinux/current/x86_64-repodata' ...
Package 'hplip' is up to date.
[slender@slender ~]$ xbps-query -p pkgver hplip
hplip-3.23.3_3
```

**Comment by ahesford** [comment]
Well, I can at least confirm that neither `hp-setup` nor `hp-doctor` die immediately on launch. If you uncover any additional issues, please reopen this.
