### ISSUE TITLE
playonlinux - asyncore

### ISSUE THREAD

**Issue by Hesnoone** [void-linux/void-packages#46700]
### Is this a new report?

Yes

### System Info

Void 6.5.7_1 x86_64 AuthenticAMD uptodate hold rrrmFFFFF

### Package(s) Affected

playonlinux 4.4_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Reported in: https://www.reddit.com/r/voidlinux/comments/178h6wc/playonlinux_error_message/

### Expected behaviour

It is supposed to start.

### Actual behaviour

Not starting with error message:
Looking for python3... 3.12.0 - selected
/usr/share/playonlinux/python/mainwindow.py:708: SyntaxWarning: invalid escape sequence '\|'
 self.SupprotedIconExt = "All|*.xpm;*.XPM;*.png;*.PNG;*.ico;*.ICO;*.jpg;*.JPG;*.jpeg;*.JPEG;*.bmp;*.BMP\
1.09375
Traceback (most recent call last):
 File "/usr/share/playonlinux/python/mainwindow.py", line 41, in <module>
import options, threading, debug
 File "/usr/share/playonlinux/python/options.py", line 21, in <module>
from asyncore import dispatcher
ModuleNotFoundError: No module named 'asyncore'

### Steps to reproduce

Run playonlinux

**Comment by Taxicletter** [comment]
Is there a solution? I have the same error. 

```
$ playonlinux
Looking for python3... 3.12.2 - selected
/usr/share/playonlinux/python/mainwindow.py:708: SyntaxWarning: invalid escape sequence '\|'
  self.SupprotedIconExt = "All|*.xpm;*.XPM;*.png;*.PNG;*.ico;*.ICO;*.jpg;*.JPG;*.jpeg;*.JPEG;*.bmp;*.BMP\
1.5
Traceback (most recent call last):
  File "/usr/share/playonlinux/python/mainwindow.py", line 41, in <module>
    import options, threading, debug
  File "/usr/share/playonlinux/python/options.py", line 21, in <module>
    from asyncore import dispatcher
ModuleNotFoundError: No module named 'asyncore'
```

**Comment by sgn** [comment]
a423faac8d6 and b0bc3bcd6f1

**Comment by dcharlespyle** [comment]
I had the exact same error. In my case. I fixed it by doing the following:

`sudo apt install python3-pyasyncore`

**Comment by classabbyamp** [comment]
that won't fix it on void
