### ISSUE TITLE
armvl6 version of go package is not compiled for armv6l

### ISSUE THREAD

**Issue by cuqer** [void-linux/void-packages#46717]
### Is this a new report?

Yes

### System Info

Void 6.1.54_1 armv6l Unknown uptodate rFFFF

### Package(s) Affected

go-1.21.1_1

### Expected behaviour

Go package is successfully installed and the command `go` can be run successfully.

### Actual behaviour

When go command is launched, the output is:
job 1, 'go' terminated by signal sigill (illegal instruction)

### Steps to reproduce

1. sudo xbps-install go -y
2. go

**Comment by paper42** [comment]
which CPU and board are you using?

**Comment by cuqer** [comment]
Raspberry Pi Zero

**Comment by cuqer** [comment]
> which CPU and board are you using?

Raspberry Pi Zero

**Comment by Duncaen** [comment]
Seems like in the build style we do set `GOARM=6` for other packages, but in the go build template we only set `GOARCH=arm`.

**Comment by dkwo** [comment]
Do you mind checking if the last commit in #46958 fixes this issue?

**Comment by cuqer** [comment]
If you mean, update the system and try again, I updated the system via:
sudo xbps-install -Syuv, then ran the command go:
fish: Job 1, 'go' terminated by signal SIGILL (Illegal instruction)

**Comment by dkwo** [comment]
No, I meant rebuild go with that commit (the pr is not merged yet).

**Comment by cuqer** [comment]
If you can tell me how I do it then I can test it out. I believe I will
build it on rpi0, isn’t it going to take a long time to compile?

**Comment by dkwo** [comment]
Assuming you're on the machine you want to build for:
```
git clone https://github.com/void-linux/void-packages.git
cd void-packages
./xbps-src binary-bootstrap
git fetch origin pull/46958/head:gopie
git switch gopie
./xbps-src pkg go
```
It did take about 5-10 min on my laptop, but ymmv on the rpi.
If it works, you can leave a comment on that pr.

**Comment by dkwo** [comment]
and then of course install it via `xi go`.
