### ISSUE TITLE
BleachBit fails to start after Python 3.12 update

### ISSUE THREAD

**Issue by MechDR** [void-linux/void-packages#46798]
### Is this a new report?

Yes

### System Info

Void 6.5.7_1 x86_64 GenuineIntel uptodate

### Package(s) Affected

bleachbit-4.4.2_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Not as far as I know.

### Expected behaviour

The app should run, it doesn't.

### Actual behaviour

It doesn't run.

### Steps to reproduce

Run the app, see what happens.

```
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 43, in <module>
    import bleachbit.GUI
  File "/usr/share/bleachbit/__init__.py", line 33, in <module>
    from configparser import RawConfigParser, NoOptionError, SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
```

**Comment by mhmdanas** [comment]
The fix should be pretty simple, I'll submit a PR to patch in a fix and send the patch upstream as well.

**Comment by MechDR** [comment]
> The fix should be pretty simple, I'll submit a PR to patch in a fix and send the patch upstream as well.

Thanks!
