### ISSUE TITLE
Package request: Airshipper

### ISSUE THREAD

**Issue by Dekomoro** [void-linux/void-packages#46797]
### Package name

Airshipper

### Package homepage

https://veloren.net/

### Description

Airshipper is the official Launcher for Veloren. Veloren is a multiplayer voxel RPG written in Rust. It is inspired by games such as Cube World, Legend of Zelda: Breath of the Wild, Dwarf Fortress and Minecraft.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by Dekomoro** [comment]
Source code is located at https://gitlab.com/veloren/airshipper

**Comment by iFoundSilentHouse** [comment]
Airshipper is compiled with nigthly (unstable) build of rust. It's not a Void packaging style unfortunately.
