### ISSUE TITLE
gimp-python & resynthesizer broken

### ISSUE THREAD

**Issue by twilight-sparkle-irl** [void-linux/void-packages#46805]
### Is this a new report?

Yes

### System Info

Void 6.3.13_1 x86_64 GenuineIntel uptodate rrrmFFFFF

### Package(s) Affected

gimp-python-2.10.34_1 resynthesizer-2.0.3_1

### Expected behaviour

Should install, even on latest upgrade

### Actual behaviour

Doesn't install

### Steps to reproduce

1. Attempt to upgrade from a version with resynthesizer installed / install resynthesizer on an up to date system
2. Fail

**Comment by paper42** [comment]
Both packages were removed because they use Python 2, they are just not cleaned from binary repositories yet. If you installed them manually now, xbps will want to uninstall them in the next update that bumps removed-packages.

**Comment by classabbyamp** [comment]
resynthesizer [has been restored](https://github.com/void-linux/void-packages/commit/29e17eb85d1985a107ae4850c91e26e40de41e80) as there is an [officially-blessed non-python2 fork](https://github.com/itr-tert/gimp-resynthesizer-scm) that will suffice [until gimp 3 is released](https://developer.gimp.org/core/roadmap/#gimp-30-development-branch-roadmap) and [resynthesizer's gimp 3/python 3 port](https://github.com/bootchk/resynthesizer/tree/resynthesizer3) is finished.
