### ISSUE TITLE
ffmpeg doesn't support rav1e encoder

### ISSUE THREAD

**Issue by BlitDev** [void-linux/void-packages#46823]
Hi, I tried to use rav1e in ffmpeg, but it said "Unknown encoder 'librav1e'". Also there is no librav1e in ffmpeg encoders list (-encoders).

```ffmpeg -encoders | rg av1``` output:
```
V..... libaom-av1           libaom AV1 (codec av1)
V..... libsvtav1            SVT-AV1(Scalable Video Technology for AV1) encoder (codec av1)
```

**Comment by mhmdanas** [comment]
Is there a reason why you can't use libsvtav1 instead?

**Comment by BlitDev** [comment]
> Is there a reason why you can't/don't want to use libsvtav1 instead?

I've tried to set the crf parameter, but it threw an error:
```
Codec AVOption crf (Select the quality for constant quality mode) specified for output file #0 (test-3.mkv) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
```

My command: ```ffmpeg -i source.mkv -c:v libsvtav1 -crf 30 test-3.mkv```
The crf is actually set at 50 (default value) although I set it at 30.

**Comment by mhmdanas** [comment]
Apparently libaom-av1 supports the crf parameter, could you try that maybe?

**Comment by mhmdanas** [comment]
I'm not aware of any particular reason, if you need rav1e a PR adding rav1e support to ffmpeg may be accepted.

**Comment by ahesford** [comment]
This isn't really an "issue" so much as a configuration choice. As noted, you can always PR support for rav1e if you want to kick off a discussion about whether it should be added.
