### ISSUE TITLE
obs-studio no websocket support

### ISSUE THREAD

**Issue by 10leej** [void-linux/void-packages#46835]
### Is this a new report?

Yes

### System Info

Void 6.5.8_1 x86_64 GenuineIntel uptodate rFFFFFFF

### Package(s) Affected

obs-29.1.3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://obsproject.com/forum/threads/obs-websocket.163107/

This is a know issue regarding the generated tarballs from github, for some reason the tarballs have no websocket support so the only method of enabling the websocket feature is source compiling straight off the git master branch

### Expected behaviour

websocket support should show in Tools on the top menu

### Actual behaviour

Tools menu does not show websockets

### Steps to reproduce

Install obs studio from the standard repository and launch it

**Comment by ahesford** [comment]
As you describe, this isn't a Void bug, but an upstream distribution issue that will work itself out when they provide proper release sources.
