### ISSUE TITLE
grimshot can't be installed with swayfx

### ISSUE THREAD

**Issue by usagi-flow** [void-linux/void-packages#46873]
### Is this a new report?

Yes

### System Info

Void 6.5.8_1 x86_64 GenuineIntel uptodate rrFFF

### Package(s) Affected

grimshot-1.8.1_1

### Expected behaviour

Grimshot installs correctly.

### Actual behaviour

```sh
$ sudo xbps-install grimshot
CONFLICT: swayfx-0.3.2_1 with sway-1.8.1_1 in transaction (matched by sway)
Transaction aborted due to conflicting packages.
```

### Steps to reproduce

1. Install swayfx.
2. Install grimshot.

**Comment by paper42** [comment]
Does grimshot work also with other non-sway wlroots compositors? If yes, the sway dependency can be removed from it which will fix this.

**Comment by sgn** [comment]
Just make `swayfx` provides `sway` is enough, I think
