### ISSUE TITLE
remove cowsay as it promote drug use (bong.cow)

### ISSUE THREAD

**Issue by hholst80** [void-linux/void-packages#46920]
### Is this a new report?

Yes

### System Info

Void x86_64

### Package(s) Affected

cowsay

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

The upstream repository is archived and contains content that the void maintainers does not want.  I assume that Void linux does not promote drug use (smoking crack in a bong pipe is bad, mkay) I think it would be safest for us all if the cowsay package is removed completely.

### Expected behaviour

Void package should be safe to use.

### Actual behaviour

cowsay should follow suite of all other linux distros and remove bong.cow at a minimum or preferably remove it completely, as it is unmaintained by upstream and void package maintainers seems to fall short of keeping security tight.

### Steps to reproduce

1. install cowsay
2. run `cowsay -f bong 'Kids, drugs are cool!'`

**Comment by ahesford** [comment]
If you're going to file bogus issues, at least use proper grammar. Better still, don't file bogus issues.

You should also refrain from comments about what the Void maintainers do or don't want, because you aren't one.

**Comment by classabbyamp** [comment]
1. bongs aren't for crack, they're for weed or tobacco. if you're going to do whataboutism, at least get your facts straight
2. weed is legal where I am 🤷‍♀️
3. this is not a security issue

**Comment by hholst80** [comment]
@classabbyamp do not attempt to go a route where you assume you have your own facts right. you claimed that Fedora had removed both .cow files. They have not. 

It is certainly illegal in most part of europe and the world so your argument that "it is legal here" is for an international user base - quite useless argument and valid only for a subjective user. I subjectively do not think either of these cow files poses any moral concerns, but you have opened up a can of worm here and now you deal with it.

**Comment by hholst80** [comment]
@ahesford your maintainers started political cleanup of open source content that has been just fine for 24 years. That is leftist activism. Is that a good base for void linux? I'd be happy to replace political driven maintainers and do the work myself. I am sure I am both conpetent and would keep void linux free from political BS and focus on technology.

**Comment by ahesford** [comment]
You're sure you're competent? You aren't even competent to make an effective argument on the internet. 🤣

**Comment by sgn** [comment]
> It is certainly illegal in most part of Europe and relevant for it's +500 million people

Are you going to suggest removing
- wine;
- and any alcohol related things

because it's illegal in Islam and its 1.9 billions Muslims people, which is far larger than 500 million European.
