### ISSUE TITLE
[OpenJDK8] Minecraft versions pre-1.13 don't run on native voidlinux.

### ISSUE THREAD

**Issue by SpidFightFR** [void-linux/void-packages#46943]
### Is this a new report?

Yes

### System Info

Void 6.5.9_1 x86_64 AuthenticAMD notuptodate rrmFFFFFFFF

### Package(s) Affected

openjdk8-jre-8u322b04_5

### Expected behaviour

When selecting the required java version (8) with your favorite launcher, Minecraft should start.
I'm using prism, it worked on my previous archlinux install.
It works on flatpak

### Actual behaviour

The game [crashes](https://mclo.gs/niTCX89) before opening the window.
Given the information i have, my best guess is that it's openjdk8 failing here.

### Steps to reproduce

1 - Download your favorite launcher
2 - Download `openjdk8-jre`
3 - Select that openjdk binary as the launch binary (doable either with the cli or your launcher)
4 - The game crashes. :(

**Comment by Johnnynator** [comment]
This is unrelated to OpenJDK. Old Java versions depend on `xrandr` which you probably don't have on your void system installed.

**Comment by SpidFightFR** [comment]
> This is unrelated to OpenJDK. Old Java versions depend on `xrandr` which you probably don't have on your void system installed.

omg... i feel really stupid rn. :sweat_smile: 
thank you so much man ! :pray:
