### ISSUE TITLE
/usr/include/string.h bad basename() prototype

### ISSUE THREAD

**Issue by cazfi** [void-linux/void-packages#46959]
### Is this a new report?

Yes

### System Info

Void 6.5.8_1 x86_64-musl

### Package(s) Affected

glibc-devel-2.36_2

### Expected behaviour

Compiling code that calls basename() works when compiler on C23 mode.

### Actual behaviour

When compiling code that calls basename(char *) under C23 mode, the compile fails as the prototype on /usr/include/string.h does not have any parameters listed.

### Steps to reproduce

1. Have code calling basename() with a proper parameter.
2. Compile it with gcc-13 and -std=c2x

**Comment by sgn** [comment]
```
Void 6.5.8_1 x86_64-musl
Package(s) Affected

glibc-devel-2.36_2
```
??

**Comment by cazfi** [comment]
Yeah, that's likely wrong. It was just what "xlocate /usr/include/string.h" gave, and the form had package as a mandatory field.

**Comment by classabbyamp** [comment]
https://inbox.vuxu.org/musl/6f06bbee-2e89-2ebe-ac18-4541d0696204@huawei.com/T/#u

**Comment by sgn** [comment]
```
The reason for the non-prototype declaration is explained in commit
37bb3cce4598c19288628e675eaf1cda6e96958f:

    omit declaration of basename wrongly interpreted as prototype in C++

    the non-prototype declaration of basename in string.h is an ugly
    compromise to avoid breaking 2 types of broken software:

    1. programs which assume basename is declared in string.h and thus
    would suffer from dangerous pointer-truncation if an implicit
    declaration were used.

    2. programs which include string.h with _GNU_SOURCE defined but then
    declare their own prototype for basename using the incorrect GNU
    signature for the function (which would clash with a correct
    prototype).
```

So, we move `basename` to `#ifdef __cplusplus`?

**Comment by oreo639** [comment]
> So, we move `basename` to `#ifdef __cplusplus`?

That is already the case, the issue here is that C23 removed support for the original k&r style and `int func()` was made from meaning an old k&r declaration to being equivalent to `int func(void)` same as C++.

**Comment by ahesford** [comment]
Given that our currently shipping compiler and musl version don't claim to support (this part of) C23, this seems like expected behavior rather than an actionable bug report.

**Comment by oreo639** [comment]
This issue was fixed upstream: https://github.com/bminor/musl/commit/725e17ed6dff4d0cd22487bb64470881e86a92e7
The patch has been imported to: https://github.com/void-linux/void-packages/pull/45500
