### ISSUE TITLE
kdenlive crashes when clicking anywhere on project bin

### ISSUE THREAD

**Issue by slender100** [void-linux/void-packages#46962]
### Is this a new report?

Yes

### System Info

Void 6.5.8_1 x86_64 AuthenticAMD uptodate rFFF

### Package(s) Affected

kdenlive-23.08.2_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://discuss.kde.org/t/touching-any-video-file-in-my-project-bin-immediately-crashes-kdenlive-23-04/1191/6

The AppImage of kdenlive works fine, and I assume this is the case for the Flatpak or PPA of it as well.

### Expected behaviour

Normally, when clicking in kdenlive's project bin to preview a clip, you can then drag it to add to the project that you currently have open.

### Actual behaviour

Kdenlive will crash if you click anywhere in the project bin, and is (usually) not avoidable.

Output of `gdb kdenlive` is vague, but is thankfully only a few lines:
```
SETTING AUDIO DATA IN MONITOR NOT EMPTY!!!
[Thread 0x7ffd756326c0 (LWP 17600) exited]
[Thread 0x7ffd86e356c0 (LWP 17595) exited]
[Thread 0x7ffd75e336c0 (LWP 17598) exited]
[Thread 0x7ffef85d56c0 (LWP 17594) exited]
[Thread 0x7ffd766346c0 (LWP 17596) exited]
[New Thread 0x7ffef85d56c0 (LWP 17601)]
[New Thread 0x7ffd766346c0 (LWP 17602)]
[New Thread 0x7ffd75e336c0 (LWP 17603)]
MUTEX LOCK!!!!!!!!!!!! setmodel
MUTEX UNLOCK!!!!!!!!!!!! setmodel
MUTEX LOCK!!!!!!!!!!!! loadEffects COUNT:  0
TRACK NOT IN TARGET :  3  =  (3)

Thread 664 "kdenlive" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffd75e336c0 (LWP 17603)]
0x00007fffbcf6ad6b in ?? () from /usr/lib64/mlt-7/libmltavformat.so
(gdb) 
```

Another crash happens by clicking on a webm/mkv file in the project bin:
```
SETTING AUDIO DATA IN MONITOR NOT EMPTY!!!
[Thread 0x7ffd774316c0 (LWP 18372) exited]
[Thread 0x7ffd88c346c0 (LWP 18367) exited]
[Thread 0x7ffd77c326c0 (LWP 18370) exited]
[Thread 0x7ffed63ea6c0 (LWP 18366) exited]
[Thread 0x7ffd784336c0 (LWP 18368) exited]
[New Thread 0x7ffed63ea6c0 (LWP 18373)]
[New Thread 0x7ffd784336c0 (LWP 18374)]
[New Thread 0x7ffd77c326c0 (LWP 18375)]
MUTEX LOCK!!!!!!!!!!!! setmodel
MUTEX UNLOCK!!!!!!!!!!!! setmodel
MUTEX LOCK!!!!!!!!!!!! loadEffects COUNT:  0
TRACK NOT IN TARGET :  3  =  (3)
[matroska,webm @ 0x7fff3c035500] EBML header parsing failed

Thread 658 "kdenlive" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffd77c326c0 (LWP 18375)]
0x00007fff4b4a4970 in ?? () from /usr/lib/libavcodec.so.58
(gdb) 
```

### Steps to reproduce

1. Install the current version of kdenlive in the void repository with `xbps-install -S kdenlive`
2. Add clips to the project bin, and try editing in the application for a bit.
3. Eventually, you will reach a point where kdenlive crashes almost every time when you click on a clip that is in the project bin.

**Comment by Johnnynator** [comment]
Both crashes are happening in `ffmpeg`/`mlt` and not kdenlive. I'm not able to reproduce this with any of the video files I have on hand.
Do you have a file that reliably crashes on your system that you can provide?

**Comment by Luciogi** [comment]
Is it reproduce-able in 23.08.4?

**Comment by slender100** [comment]
I can confirm that the issue has been resolved with the current release. Closing this issue.
