### ISSUE TITLE
GIMP crashing when trying to use Wacom tablet - here's how to make it work again.

### ISSUE THREAD

**Issue by gc-user** [void-linux/void-packages#46975]
As I don't know which package is the culprit, I decided not to create a bug report (aka "Issue") but rather use this free-form report form.

There are reports on GIMP gitlab and reddit to be found that seemingly address this issue.

The other day I re-encountered that issue when trying to use the tablet with GIMP, so I decided to try to get it to work.

First, I tried building the xbps files for the GIMP developer version 2.99.16, but, after adjusting the template and the patch file, it still failed, to I abandoned that idea, as I'm not versed enough to know which build settings to change / create to make it work.

Then I went back to looking for older package of libwacom.

Thanks to zfs, and therefore snapshots, and my own xbps files collections (started years back due to all kinds of regression that showed up in different packages), I had a few versions of that file. And thanks to an older system, I found even more.

Trying to xdowngrade libwacom, I learned that it has dependencies with libinput and kcm-wacomtablet. Trying some older versions with no change, and also trying to downgrade GIMP (the oldest version that worked without having to downgrade a bunch of other dependencies, was 2.10.32), I realized that there are two more packages to consider: xf86-input-libinput and xf86-input-wacom.

Also, the versions of libinput and xf86-input-libinput should be from around the same time frame (as should obviously the others as well), because if they aren't one might end up booting into a system with no keyboard available (internal or external (USB). With zfs and different BEs that's a minor problem, though.

So, after quite a number of reboots, I now found a combination of versions of those packages, that make GIMP work again with my Wacom tablet without any crashes:

libinput: v1.22.0_1
libwacom: v1.12_1
kcm-wacomtablet: v3.2.0_2
xf86-input-libinput: v1.2.1_1
xf86-input-wacom: v1.1.0_1

I don't know which package is ultimately responsible for the crash issue and which ones are just needed in a lower version for the culprit to work.
It might be libwacom or xf86-input-wacomtablet, or both / neither.

Either way, the above setup finally allows me to use GIMP and my tablet again since it stopped working sometime this spring, I guess.

[Update:]

Downgrading xf86-input-wacom to v1.1.0_1 should suffice. Seems to work fine with the other packages being at their respective current version.

[/Update]

**Comment by oreo639** [comment]
If you are familiar with gdb, can you get a gdb backtrace for the gimp crash? (you will need to install `-dbg` packages including `gimp-dbg`)

**Comment by oreo639** [comment]
You can test that by downloading this patch and placing it in the patches folder:
https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/935.patch
https://github.com/void-linux/void-packages/tree/master/srcpkgs/gimp/patches

Then build it using `./xbps-src pkg gimp`

**Comment by gc-user** [comment]
Thanks for your help!

Actually, I tried to build the new version (v2.99.16), but they changed to much that simple adjusting the template file and the patches for v2.10.34 isn't enough. So, that's beyond my capabilities.

But applying the patch you suggested to v2.10.34 worked fine and the resulting package / version doesn't crash anymore with the latest version of xf86-input-wacomtablet.

So, thanks again for the hint.

I'll try to commit the changes...

**Comment by oreo639** [comment]
`v2.99.16` is a beta release for GIMP 3.0.x

**Comment by gc-user** [comment]
Yeah, I got fooled... :-). It looked so "official" on [Gitlab](https://gitlab.gnome.org/GNOME/gimp/-/releases), no "pre-release" label or anything, like on Github...
And my thought was: better a beta that doesn't crash than a stable that does... :-)

**Comment by gc-user** [comment]
PR is out and waiting for approval...

**Comment by gc-user** [comment]
Update:

Gimp 2.10.36 is out since Nov 5th, it fixes this wacom issue.
