### ISSUE TITLE
qt6.60 breaks shotcut

### ISSUE THREAD

**Issue by zlice** [void-linux/void-packages#46991]
### Is this a new report?

Yes

### System Info

Void 6.5.7 x86_64 AuthenticAMD uptodate rFFFFFFFFFF

### Package(s) Affected

shotcut-23.09 mlt7-7.20

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://forum.shotcut.org/t/timeline-went-white-blank-on-linux/41180

https://forum.shotcut.org/t/qt6-v6-6-0-not-supported/41177/2

states that breakage due to qt is on the distro

### Expected behaviour

timeline has clips in it

### Actual behaviour

unusable white timeline. not compatible with qt6.6+

shotcut 23.07.09 and mlt 7.18 seg fault for me and simply won't run

### Steps to reproduce

- build new shotcut/mlt7 https://github.com/zlice/void-packages/tree/shotcut-mlt-bump
- run shotcut

**Comment by Johnnynator** [comment]
Can you test https://github.com/void-linux/void-packages/pull/47020 ? It seems to be working fine, at least for me.

**Comment by zlice** [comment]
opens w/o a white timeline. thanks!
