### ISSUE TITLE
Incorrect installation prefix used for libdwarf*

### ISSUE THREAD

**Issue by Plecra** [void-linux/void-packages#47077]
### Is this a new report?

Yes

### System Info

This is second hand I'm afraid :) 

### Package(s) Affected

libdwarf-20191104_1<=

### Expected behaviour

As I understand it, the package manager is intended to install packages into `/usr/{pkg}`.

### Actual behaviour

A temporary prefix change (to `/usr/local` for development) was accidentally committed, and invalidated other references to files within the template:

https://github.com/void-linux/void-packages/commit/e71de4f927ac6c94a60d654137f209b633fdf660#diff-44ccf69c98ebd40cf6c6b0418e643b2ae811192424b0a2b587999734ecbd4c61L6-R6

The configure_args are missing `--prefix=/usr`. This invalidates the references to the DESTDIR in the `libdwarf-devel_package` here, which means it fails to copy the `{lib}dwarf.h` headers. They're unusable.

https://github.com/void-linux/void-packages/blob/22a8d3612b2fc6b5f0a6d0ba8dfc2aa28de490a7/srcpkgs/libdwarf/template#L29-L31

### Steps to reproduce

1. `xbps-install libdwarf-devel`
2. attempt to use the `libdwarf.h` header. (It should be available as `libdwarf/libdwarf.h` due to https://github.com/void-linux/void-packages/pull/17154)
3. A c compiler wont find it.

**Comment by classabbyamp** [comment]
can't reproduce. update libdwarf(-devel). Also, as this uses the `gnu-configure` build style, `--prefix=/usr` is implicit.

```
$ xbps-query -Rp pkgver libdwarf-devel
libdwarf-devel-20201020_1
$ xbps-query -Rf libdwarf-devel
/usr/include/libdwarf/dwarf.h
/usr/include/libdwarf/libdwarf.h
/usr/lib/libdwarf.a
/usr/lib/libdwarf.so -> /usr/lib/libdwarf.so.1.0.0
