### ISSUE TITLE
Package request: yabsm

### ISSUE THREAD

**Issue by NicholasBHubbard** [void-linux/void-packages#47084]
### Package name

yabsm

### Package homepage

https://github.com/NicholasBHubbard/Yabsm

### Description

yabsm is a btrfs snapshot manager and backup system.

I wrote my own yabsm packages for Slackware and Arch Linux that should be relevant here. Yabsm runs as a cron-style daemon and thus requires a service definition.

Slackware package: https://slackbuilds.org/repository/15.0/system/yabsm/
AUR package: https://aur.archlinux.org/packages/yabsm

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by sug0** [comment]
> YABSM IS DEPRECATED
from the project's readme. the listed alternatives (`btrbk` and `snapper`) are both already packaged in Void.
