### ISSUE TITLE
`jupyter lab` not working in virtual enviroment

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#47135]
### Is this a new report?

Yes

### System Info

Void 6.5.9_1 x86_64 GenuineIntel uptodate rFFFFFFFFFFFFFFFFFFFFFFFFFFF

### Package(s) Affected

sagemath-10.1_4 jupyterlab-4.0.7_1

### Expected behaviour

I can use sagemath in a virtual environment in `jupyter lab`.

### Actual behaviour

I can use sagemath in a virtualenvironment in the repl, but not with `jupyer lab`.

### Steps to reproduce

1. Install `sagemath` and `jupyterlab`
2. Create a python virtual environment: `python3 -m venv /path/to/venv`
3. Activate the virtual environment: `.  /path/to/venv/bin/activate`
4. Run `sage`, output is 
```
$ sage                      
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.1, Release Date: 2023-08-20                    │
│ Using Python 3.12.0. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
/usr/lib/python3.12/site-packages/IPython/core/interactiveshell.py:913: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn(
sage: 
```
After this, sage works as expected.

5. Quit sage with `Control + D`.

6. run `jupyter lab`, and create a new sagemath notebook.

The notebook does not work (computations get stuck forever).
```
/path/to/venv/bin/python3: Error while finding module specification for 'sage.repl.ipython_kernel' (ModuleNotFoundError: No module named 'sage')
```

**Comment by Eloitor** [comment]
Maybe this is easier to debug:

```
$ . /path/to/venv/bin/activate
$ jupyter console --kernel=sagemath
/path/to/venv/bin/python3: Error while finding module specification for 'sage.repl.ipython_kernel' (ModuleNotFoundError: No module named 'sage.repl')
```

**Comment by tornaria** [comment]
Of course this is expected and how venv works afaik:
```
$ python -m venv bad-venv
$ . bad-venv/bin/activate
(bad-venv) $ python -m sage
.../bad-venv/bin/python: No module named sage
(bad-venv) $
```

What you want can be acomplished with `--system-site-packages`:
```
$ python -m venv --system-site-packages good-venv
$ . good-venv/bin/activate
(good-venv) $ python -m sage
.../good-venv/bin/python: No module named sage.__main__; 'sage' is a package and cannot be directly executed
(good-venv) $ jupyter console --kernel=sagemath
[IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
Jupyter console 6.6.3

┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.2.rc4, Release Date: 2023-11-17                │
│ Using Python 3.12.0. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Warning: this is a prerelease version, and it may be unstable.     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
In [1]: 
```

Please check if this works for you. Note that running sage like this is unsupported upstream. They really want you to build the whole kitchen sink.

**Comment by Eloitor** [comment]
This works for me! Thank you. It also works in `jupyter lab`.

**Comment by tornaria** [comment]
> This works for me! Thank you. It also works in `jupyter lab`.

If it's fixed, please close the issue as solved (I don't have permission myself).
