### ISSUE TITLE
udiskie doesn't work on Python 3.12 as distutils has been deprecated

### ISSUE THREAD

**Issue by kutu-dev** [void-linux/void-packages#47165]
### Is this a new report?

Yes

### System Info

Void 6.5.10_1 x86_64 GenuineIntel uptodate rFFFFF

### Package(s) Affected

udiskie-2.5.0_1

### Expected behaviour

The udiskie daemon should start without issues.

### Actual behaviour

Udiskie crash with the error:
```
Traceback (most recent call last):
  File "/usr/bin/udiskie", line 4, in <module>
    from udiskie.cli import Daemon
  File "/usr/lib/python3.12/site-packages/udiskie/cli.py", line 21, in <module>
    import udiskie.mount
  File "/usr/lib/python3.12/site-packages/udiskie/mount.py", line 5, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils'
```

### Steps to reproduce

1. Run `udiskie`
2. It crash

**Comment by icp1994** [comment]
Can you install `python3-setuptools` and try again?

**Comment by kutu-dev** [comment]
It worked. Should I make a PR adding the missing dependency here? It looks like the package is for Python 3.5+ and setuptools is only for Python 3.8+ so I don't know if I should make a issue in the upstream

**Comment by icp1994** [comment]
You you can make a PR here. But since Python 3.7 has reached end-of-life, I don't think upstream would care much if it's not supported.
