### ISSUE TITLE
Missing depedency "libgjc>=6.0.5.0_1"

### ISSUE THREAD

**Issue by Staryvyr** [void-linux/void-packages#47176]
### Is this a new report?

Yes

### System Info

Void 6.5.11_1 x86_64 AuthenticAMD uptodate FF

### Package(s) Affected

pdftk

### Expected behaviour

I've employed

`sudo xbps-installed pdftk`

and expected that this package will become installed by xbps.

### Actual behaviour

Instead of installing the package I've got the message

`Missing: libgcj>=6.0.5.0_1
Transaction aborted due to unresolved dependencies`

So xbps-install cannot find libgcj in the repo
"https://repo-de.voidlinux.org/current"

(while `xbps-query -R glibc` is showing me that the library exists)

### Steps to reproduce

1. Install Void (I have employed the x86_64 image for XFCE glib from 28th of June 2023)
2. Upgrade Void via "sudo xbps-install -Su"
3. Try to install pdftk via "sudo xbps-install pdftk"

**Comment by Staryvyr** [comment]
Pls forget the small remark in parenthesis (I've queried the wrong package).
So libgcj is simply not in above repo.

**Comment by Staryvyr** [comment]
P.P.S: I've checked also other mirrors in partiucular the "default" mirror. Also there libgcj cannot be fount.

**Comment by Johnnynator** [comment]
https://github.com/void-linux/void-packages/commit/b22249b8f0cc4c6d2a97ec1814cc737a8bc8fd10 <- the move to bootstrap broke this and should be reverted? @classabbyamp

**Comment by classabbyamp** [comment]
Hrm yeah I guess

**Comment by classabbyamp** [comment]
seems in newer versions of pdftk, libgcj is no longer necessary: #47189
