### ISSUE TITLE
iwd dependancy issue

### ISSUE THREAD

**Issue by NAHTAIV3L** [void-linux/void-packages#47225]
### Is this a new report?

Yes

### System Info

Void 6.5.10_1 x86_64

### Package(s) Affected

iwd-2.8_1

### Expected behaviour

when you install iwd it should work but it does not install openresolv so it cannot work.

### Actual behaviour

gives issue about resolvconf

### Steps to reproduce

I had iwd and networkmanager installed then I uninstalled networkamanager and couldn't use wifi. I had to chroot into the system to fix it.
all you have to do to fix this issue is add openresolv to the dependencies list of iwd

**Comment by balejk** [comment]
I don't think that there is a reason for this to be a dependency of iwd, much less in Void where only hard dependencies without which the program would not run at all are usually added. I use iwd but have never heard of openresolv before and do not have it installed and yet I am not experiencing any such problems. I think you rather want to look into your iwd configuration or get/properly configure a DHCP daemon.

**Comment by NAHTAIV3L** [comment]
are you manually setting dns servers

**Comment by balejk** [comment]
No, my configuration is handled automatically by dhcpcd.

**Comment by NAHTAIV3L** [comment]
could you explain how to do that it wasnt working automatically for me

**Comment by classabbyamp** [comment]
I think `Network.NameResolvingService` only matters when using the iwd built-in dhcp client (i.e. `General.EnableNetworkConfiguration=true`), and it should default to resolvconf.

https://man.voidlinux.org/iwd.config#Network

@NAHTAIV3L if you were to switch to dhcpcd, you would need to enable the dhcpcd service, I believe, but you shouldn't need to do that if you want to use only iwd.

**Comment by balejk** [comment]
I don't think I have ever made any changes to the default configuration
of either dhcpcd or iwd on my machine, so it should work out of the box
if you have both installed, haven't modified the configuration of either
and don't have any conflicting packages.

In particular, according to the Arch wiki dhcpcd page [1], dhcpcd should
relay DNS configuration to resolvconf if it's available or manage
/etc/resolv.conf directly if it's not.

[1] https://wiki.archlinux.org/title/Dhcpcd#/etc/resolv.conf
