### ISSUE TITLE
Package request: llvm-bolt

### ISSUE THREAD

**Issue by zamazan4ik** [void-linux/void-packages#47226]
### Package name

llvm-bolt

### Package homepage

https://github.com/llvm/llvm-project/blob/main/bolt/README.md

### Description

LLVM BOLT is a binary optimizer - a tool that optimizes your program after the compilation process. More information about that you can read at https://research.facebook.com/publications/bolt-a-practical-binary-optimizer-for-data-centers-and-beyond. Applying BOLT to the binaries helps with achieving better performance for different applications - more information about that you can find at https://github.com/void-linux/void-packages/issues/47215.

Other distros like Fedora and Solus already provide `llvm-bolt` in their repositories: https://repology.org/project/llvm-bolt/versions.

Since LLVM BOLT is a part of the LLVM project, it can be built by simply enabling `bolt` project during CMake configuration. Probably (I do not remember when BOLT was merged into LLVM) BOLT cannot be enabled in the current LLVM 15 version. In this case, we can simply postpone the issue and wait for the LLVM update in Void Linux.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
#46935
