### ISSUE TITLE
installing  perl-LWP does not install perl module HTML::HeadParser (part of HTML-Parser)

### ISSUE THREAD

**Issue by laemeiqu** [void-linux/void-packages#47287]
### Is this a new report?

Yes

### System Info

Void 6.5.11_1 x86_64 GenuineIntel/VM uptodate FF

### Package(s) Affected

perl-LWP

### Expected behaviour

Expect ratings functionality of scriptassist.pl module of irssi to work 

inside irsi:
```
/run scriptassist.pl 
/scriptassist ratings all 

[17:19] ,--[ScriptAssist]
[17:19] | o adv_windowlist.pl [13 votes]
[17:19] | o trackbar.pl       [12 votes]
[17:19] | o scriptassist.pl   [7 votes]
........
```

### Actual behaviour

installing  perl-LWP does not install perl module HTML::HeadParser (part of HTML-Parser)

To get HTML::HeadParser this is what I did:

sudo xbps-install -S cpanminus
sudo cpanm install HTML::HeadParser

After this the scriptassist ratings functionality of irssi worked as it should.

### Steps to reproduce

1. install irssi and perl-LWP
2. go into irssi
3. /run scriptassist
4. /scriptassist ratings all 

You won't get ratings unless you also install HTML::HeadParser from cpan

Installing the voidpackage "perl-HTML-Parser" might also solve the issue. If that is the case then perl-LWP should have perl-HTML-Parser as a dependency.

**Comment by terminaldweller** [comment]
you don't "have to" get perl-html-parser from cpan. getting "perl-HTML-Parser" also works.

Anyways the situation is that [metacpan](https://metacpan.org/pod/LWP) lists HTML::HeadParser as a dependency but the void template only lists that as a checkdependency which means installing perl-LWP will not pull perl-HTML-Parser which includes the HTML::HeadParser module.

So I guess the question is was the choice made intentionally to exclude perl-HTML-Parser as a dependency of perl-LWP?

**Comment by laemeiqu** [comment]
+1 for that question

error message from "/scriptassist ratings all" in irssi if perl-HTML-Parser is missing:
```
Irssi: Fetching ratings failed: Could not find votes script
```
I can confirm that installing "perl-HTML-Parser" works as a solution for me (as an alternative to using cpan).

**Comment by laemeiqu** [comment]
I can confirm that this issue is now fixed. 

I did the following small test : 
I removed perl-HTML-Parser.  Then as expected "/scriptasisst ratings all" stopped working. Then I updated voidlinux which automatically pulled in perl-HTML-Parser (because it is now a dependency of Perl-LWP. Now "/scriptassist ratings all" works again.
