### ISSUE TITLE
Package request: kmplot - kde app to plot graphs

### ISSUE THREAD

**Issue by Luciogi** [void-linux/void-packages#47309]
### Package name

kmplot

### Package homepage

https://apps.kde.org/kmplot/

### Description

KmPlot is a program to plot graphs of functions, their integrals or derivatives. The graphs can be colorized and the view is highly configurable, is scalable, and can be zoomed.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/kmplot/template
