### ISSUE TITLE
`vkpurge rm all` reconfiguring mutiple times

### ISSUE THREAD

**Issue by NAHTAIV3L** [void-linux/void-packages#47354]
Is it possible to make `vkpurge rm all` just run the kernel hooks at the end instead of after every kernel is removed. Doing it every time is very slow

**Comment by Duncaen** [comment]
No kernel hooks are per version. grub or whatever hook you want to avoid is missing either a mechanism to run only on specific kernels or there needs to be a separate new way to have kernel hooks that are not per version.
