### ISSUE TITLE
ranger and lf are not showing image previews with ueberzug

### ISSUE THREAD

**Issue by hogsmead** [void-linux/void-packages#47387]
### Is this a new report?

Yes

### System Info

Void 6.5.12_1 x86_64 AuthenticAMD uptodate FFF

### Package(s) Affected

ueberzug-18.1.9_3, ranger-1.9.3_5

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

The upstream is dead. The issue has been fixed in its active fork.
https://github.com/ueber-devel/ueberzug/issues/15

### Expected behaviour

ranger shows image previews.

### Actual behaviour

ranger shows empty space instead of images.

### Steps to reproduce

1. Use the following config for ranger:
    ```
    set preview_images true
    set preview_images_method ueberzug
    ```
2. Run ranger from st and select an image

**Comment by ahesford** [comment]
Upstream doesn't have an "active fork"; the project page explicitly recommends that the project *not be used*. This should be fixed in ranger by dropping a dead dependency.
