### ISSUE TITLE
Can't install Fritzing: Transaction aborted due to unresolved dependencies.

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#47394]
### Is this a new report?

Yes

### System Info

Void 6.5.7_1 x86_64 GenuineIntel notuptodate hold rFF

### Package(s) Affected

Fritzing

### Expected behaviour

The package should install properly.be installed

### Actual behaviour

This is the output of my terminal when try to install this package:

> [*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
> x86_64-repodata: 1856KB [avg rate: 5729KB/s]
> [*] Updating repository `https://repo-default.voidlinux.org/current/multilib/x86_64-repodata' ...
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-dbus-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-declarative-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-graphicaleffects-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-gui-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-network-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-plugin-sqlite-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-printsupport-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-quickcontrols2-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-sql-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-svg-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-test-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-tools-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-widgets-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-x11extras-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-xml-5.15.7+20221119_7'
> qt5-core-5.15.7+20221119_8 in transaction breaks installed pkg `qt5-xmlpatterns-5.15.7+20221119_7'
> Transaction aborted due to unresolved dependencies.

### Steps to reproduce

`sudo xbps-install -S Fritzing`

**Comment by classabbyamp** [comment]
get your system up to date and try again
