### ISSUE TITLE
Clipboard package is orphaned. What's needed ?

### ISSUE THREAD

**Issue by laemeiqu** [void-linux/void-packages#47455]
### Package name

clipboard

### Package homepage

https://getclipboard.app/

### Description

The Clipboard Project (CB for short) is the oh-so-awesome clipboard manager that's just like a second brain.
It's fast and lightweight, feature packed, and super user friendly.
Do way more on the computer in way less time!

According to https://github.com/Slackadays/Clipboard it should already be in voidlinux but the package seems to be orphaned for some reason.
* https://github.com/void-linux/void-packages/pull/46355
* https://github.com/void-linux/void-packages/commit/f09ef06fa59924b7ea9cac1474db557228503935

Clipboard is more of an nice to have that people might like. 

One potential use case is for people using making podman/docker/distrobox containers based on voidlinux instead of alpine linux. 

There are a few packages for such a use case that alpine provides but voidlinux doesn't such as : clipboard (this one), atuin https://github.com/void-linux/void-packages/pull/40600 and cosign https://github.com/sigstore/cosign

So what is the reason clipboard was orphaned  ? What's needed to bring it back into the repositories ? The package is in need of a new maintainer ?

I'm new to void linux and I like it a lot. Would be nice if voidlinux could become more suitable as a container distro. Please close this issue if it's not helpful to the project.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
"orphaned" just means there is no specific person who has committed to maintaining the package. It does not mean the package is or will be removed.  If someone else wants to commit to maintaining the package, they can do so in accordance with the [contribution guidelines](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#adopting-a-template).

I'm not sure where you're getting the idea that it is no longer in the repositories, it's right there:
```
xbps-query -Rs clipboard
[-] Clipboard-0.8.2_1                  Cut, copy, and paste anything, anywhere, all from the terminal
```

I'm also not sure what this package has to do with void being suitable as a distribution for containers, that seems like a non-sequitur. Void provides [container images](https://voidlinux.org/download/#containers) that anyone is free to use for whatever they want.

**Comment by laemeiqu** [comment]
Thanks for your quick reply.

This is what happens if I try to install clipboard : 
```
user@void-kvm:~$ sudo xbps-install -S clipboard
[*] Updating repository `https://mirrors.servercentral.com/voidlinux/current/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/debug/x86_64-repodata' ...
Package 'clipboard' not found in repository pool.
```
I don't have the non-free repo's enabled but clipboard is under  GPL-3.0 license so that shouldn't matter.

IMHO clipboard would be nice for the use case of container distro's where people might want to install commandline bling tools such as for example referenced here (skip these links if not interested) :
* https://getfleek.dev/docs/bling
* https://github.com/ublue-os/boxkit
* Rawkode Academy - 2023 Top 5 CLI Tools You Need to Know!
https://www.youtube.com/watch?v=TNlDSG1iDW8 

Examples of these kind of bling command line tools are for example:
* comtrya https://www.comtrya.dev/ (not in voidlinux repos)
* clipboard (the one we are talking about now)
* atuin
* direnv
* zoxide
* eza

I was looking into distrobox today and these kind of bling command line tools and that is what inspired me to create this issue.

Blogpost that inspired me : 
https://www.ypsidanger.com/declaring-your-own-personal-distroboxes/

**Comment by classabbyamp** [comment]
package names are case-sensitive, the package's name is `Clipboard`.

**Comment by laemeiqu** [comment]
> package names are case-sensitive, the package's name is `Clipboard`.

Thanks. That helps!

**Comment by dataCobra** [comment]
Hey,

atuin has a PR which is open since november last year because there are some issues which are not so easy to resolv. https://github.com/void-linux/void-packages/pull/40600

Maybe there are also PRs or Issues regarding to the other packages. But I didn't check.
