### ISSUE TITLE
keepassxc installation fails due to missing dependency

### ISSUE THREAD

**Issue by sbromberger** [void-linux/void-packages#47463]
### Is this a new report?

Yes

### System Info

Void 6.5.12_1 x86_64 AuthenticAMD notuptodate rFF

### Package(s) Affected

keepassxc

### Expected behaviour

`xbps-install keepassxc` should install all required dependencies.

### Actual behaviour

`xbps-install keepassxc` exits with the following error:

```

[*] Downloading packages
ERROR: [trans] failed to download `libpcsclite-2.0.0_1' signature from `https://repo-default.voidlinux.org/current': Not Foun
d
Transaction failed! see above for errors.
```

### Steps to reproduce

1. `xbps-install keepassxc`
2. observe failure

**Comment by classabbyamp** [comment]
add -S

**Comment by sbromberger** [comment]
Thanks. Just figured that out. Sorry for the noise.
