### ISSUE TITLE
Geeqie: crashing ("Double free or corruption") when viewing ORF files

### ISSUE THREAD

**Issue by xlq** [void-linux/void-packages#47547]
### Is this a new report?

Yes

### System Info

Void 5.18.11_1 x86_64 AuthenticAMD notuptodate hold rrrmDDDFFFFFF

### Package(s) Affected

geeqie-2.1_2, exiv2-0.28.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/BestImageViewer/geeqie/issues/1201

### Expected behaviour

Should be able to view ORF files - was working before the upgrade of geeqie and exiv2.

### Actual behaviour

Crash when viewing any ORF files in geeqie, or according to the linked issue in geeqie, RAW files from multiple manufacturers.

For now I have performed the following downgrade with xdowngrade, which fixes the problem.
```
Name           Action    Version           New version            Download size                                                                                                                   
geeqie         downgrade 2.1_2             2.1_1                  -                                                                                                                               
exiv2          downgrade 0.28.1_1          0.27.6_1               -                                                                                                                               
libgexiv2      downgrade 0.14.2_1          0.14.0_2               -                                                                                                                               
kfilemetadata5 downgrade 5.112.0_1         5.110.0_1              -                                                     
```

### Steps to reproduce

1. View an ORF file.
2. Crash!

I've attached a (gzipped) ORF file for testing: [P5080089.ORF.gz](https://github.com/void-linux/void-packages/files/13539333/P5080089.ORF.gz)

**Comment by sgn** [comment]
See: https://github.com/BestImageViewer/geeqie/pull/1214
