### ISSUE TITLE
mesa 23.3.0 behaves weird

### ISSUE THREAD

**Issue by devlocalhost** [void-linux/void-packages#47602]
### Is this a new report?

Yes

### System Info

Void 6.6.4_1 x86_64 GenuineIntel uptodate rdFFFFFF

### Package(s) Affected

mesa-23.3.0_1

### Expected behaviour

No crashes, or glitches when hovering mouse on windows on gnome 

### Actual behaviour

Gnome sometimes does not start, crashes, windows behave weirdly (glitches)

### Steps to reproduce

1. Update mesa to 23.3.0
2. Run gnome
3. Gnome might crash or you might see glitches

**Comment by chrysos349** [comment]
@devlocalhost 

It acts weird (more like crashes the whole desktop, really) in my vmware instance of voidlinux too.

I reverted `mesa` and all mesa-related packages to `23.2.1`. All fixed. Do the same.
Search for the previous version of `mesa` et al in `/var/cache/xbps`. Otherwise, you will have to package it manually.
Then use `xdowngrade` from `xtools` package, and hold the downgraded packages with `xbps-pkgdb -m hold <PKG>` for the time being.

P.S. On my real hardware `mesa-23.3.0` works fine, though.

**Comment by devlocalhost** [comment]
> @devlocalhost
> 
> It acts weird (more like crashes the whole desktop, really) in my vmware instance of voidlinux too.
> 
> I reverted `mesa` and all mesa-related packages to `23.2.1`. All fixed. Do the same. Search for the previous version of `mesa` et al in `/var/cache/xbps`. Otherwise, you will have to package it manually. Then use `xdowngrade` from `xtools` package, and hold the downgraded packages with `xbps-pkgdb -m hold <PKG>` for the time being.
> 
> P.S. On my real hardware `mesa-23.3.0` works fine, though.

Yes, it crashes my desktop environment too
Yes, I have already compiled and downgraded mesa, and everything is fine

**Comment by JamiKettunen** [comment]
My flatpak GPU accel also broke with the 23.3 upgrade (RX 6600), downgraded to 23.2.1_2 versions from `/var/cache/xbps` and everything's good again.

**Comment by classabbyamp** [comment]
updating the flatpak GL runtime should fix flatpak

**Comment by devlocalhost** [comment]
Well glad to hear others are facing issued but why hasn't someone reverted mesa back to 23.2.1 since some people are facing issues?

**Comment by JamiKettunen** [comment]
@classabbyamp how does one do that? everything with `flatpak update` is already up-to-date, `flatpak repair --user` doesn't change anything nor does even `flatpak remove org.freedesktop.Platform.GL.default` (and selecting all of the above) and `flatpak update` to reinstall them back

**Comment by classabbyamp** [comment]
not sure, i had an update available for it

**Comment by JamiKettunen** [comment]
in my case the problem appears to be localized to https://flathub.org/apps/com.usebottles.bottles, wonder if there's some bug on their end?
