### ISSUE TITLE
Package request: rust-wasm

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#47674]
### Package name

rust-wasm

### Package homepage

https://www.rust-lang.org/

### Description

WebAssembly targets for rust.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
why not just use rustup?

**Comment by Eloitor** [comment]
It doesn't work for me... I installed it but `rustup` is not available. I use zsh.

**Comment by classabbyamp** [comment]
did you look at what the rustup package contains (`xbps-query -Rf rustup`) and the upstream instructions? you have to initialise it with `rustup-init`

**Comment by Eloitor** [comment]
It tries to install its own rust `error: cannot install while Rust is installed`.
I assumed that it is prefered to install void's rust... 

In alpine linux there is the package: https://pkgs.alpinelinux.org/package/edge/main/x86_64/rust-wasm which worked fine.

**Comment by classabbyamp** [comment]
if you're on glibc it's better to use rustup's toolchain instead of the rust package
