### ISSUE TITLE
nsxiv checksum error

### ISSUE THREAD

**Issue by rickalex21** [void-linux/void-packages#47684]
### Is this a new report?

Yes

### System Info

Void 6.5.13_1 x86_64 GenuineIntel uptodate rFFF

### Package(s) Affected

nsxiv 32

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No.

### Expected behaviour

Build the package without errors.

### Actual behaviour

I think the checksum may need to be updated?

template file updated by me to work:

```text
checksum=49ef1eb775ef6c34f55dada7a3f446c9c5c6773c9e208509ffef27a656338a90
# 12/10/2023 They have not updated the checksum? 
#checksum=09d1d72b3cbcf17a04e26beb5e81acc9495aaba1f8f1be907bdcd8e4e3007db3
```

ERROR as the template file is right now:

```text
=> ERROR: SHA256 mismatch for 'v32.tar.gz:'
49ef1eb775ef6c34f55dada7a3f446c9c5c6773c9e208509ffef27a656338a90
=> ERROR: nsxiv-32_1: couldn't verify distfiles, exiting...
```

### Steps to reproduce

Try building with xbps-src.

**Comment by classabbyamp** [comment]
could just be codeberg changing the way they generate those tarballs. could also be a retag. you could use diffoscope to compare the old and new tarballs (get the old from https://sources.voidlinux.org/nsxiv-32/)

**Comment by rickalex21** [comment]
I don’t know what a diffoscope is.

**Comment by rickalex21** [comment]
@classabbyamp it looks like there are no differences?

I did:

diffoscope dir1 dir2

and also diff -qr

not sure why I’m getting different hashes ?

**Comment by classabbyamp** [comment]
i bet it's just metadata or compression differences. diffoscope knows how to diff archives, so you could diff the tarballs directly instead of extracting

**Comment by rickalex21** [comment]
It gives me a weird comparison:

![](https://i.imgur.com/nULeZY6.png)

**Comment by sgn** [comment]
> Format-specific differences are supported for Gzipped files but no file-specific differences were detected;

They're the same. Probably because of https://lore.kernel.org/git/a812a664-67ea-c0ba-599f-cb79e2d96694@gmail.com/
