### ISSUE TITLE
sagemath: test failures

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#47683]
### Is this a new report?

Yes

### System Info

asahi 6.6 series (apple silicon aarch64)

### Package(s) Affected

sagemath

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

it's important that singular is also rebuilt, as it needs ntl (otherwise, lots of segfaults in sage tests).

### Expected behaviour

pass the testsuite

### Actual behaviour

```
sage -t --warn-long 9.9 --random-seed=152816534303222946788861922984252620675 /usr/lib/python3.12/site-packages/sage/misc/persist.pyx  # 2 doctests failed
sage -t --warn-long 9.9 --random-seed=152816534303222946788861922984252620675 /usr/lib/python3.12/site-packages/sage/misc/inline_fortran.py  # 3 doctests failed
sage -t --warn-long 9.9 --random-seed=152816534303222946788861922984252620675 /usr/lib/python3.12/site-packages/sage/repl/ipython_extension.py  # 4 doctests failed
```
full test output https://paste.c-net.org/CahootsUnicorn or
[sage-test-fail.log](https://github.com/void-linux/void-packages/files/13629727/sage-test-fail.log)

### Steps to reproduce

```
./xbps-pkg singular
./xbps-pkg sagemath
xi singular sagemath
`sage -t --all`
```

**Comment by dkwo** [comment]
@tornaria can you reproduce? suggestions? should i report upstream?

**Comment by tornaria** [comment]
Install `meson` and try again. It's now required by `numpy.f2py` but not listed as a depends neither to numpy nor sagemath. You'll see it's listed in checkdepends for both.

What do you think we should do? Add `meson` to sagemath depends? It's not really necessary unless one needs to use fortran code in sage. OTOH we have `gcc-fortran` as a dependency, so I guess either we add meson or we remove gcc-fortran.

Ideally there would be a "feature" that checks whether f2py is available and working, and then all doctests that depend on this are labeled "# needs fortran" or something like that.

**Comment by dkwo** [comment]
Actually, I do get the exact same failures on `Void 6.6.5_1 x86_64 GenuineIntel uptodate rFFFFFFFFFFFF`.
You're right, installing meson fixes these tests. Thanks.

**Comment by dkwo** [comment]
Shall I open a PR to add meson to sage depends, at least until we discus how to split -devel depends?

**Comment by dkwo** [comment]
fixed in https://github.com/void-linux/void-packages/pull/47712
