### ISSUE TITLE
Package request: Any plans for gcc13?

### ISSUE THREAD

**Issue by KaiJan57** [void-linux/void-packages#47757]
### Package name

gcc

### Package homepage

https://gcc.gnu.org/gcc-13/

### Description

Includes the `format` header that is needed to build recent C++ software such as Hyprland

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
#45500 

please don't open issues requesting updates
