### ISSUE TITLE
Clarify naming conventions for packages with periods in their name

### ISSUE THREAD

**Issue by yousefamar** [void-linux/void-packages#4777]
I was writing a template (my first) for [this CLI tool](https://github.com/todotxt/todo.txt-cli) that happens to have a period in its name. I've seen this before with programs that e.g. have a ".io" as part of their brand. Are periods kept in the name?

Other package managers rename packages like this to something more normal, and indeed the official brew version of this packages is called "todo-txt" rather than "todo.txt-cli".

There seems to be precedent in `srcpkgs` as some packages have a period in them ([here](https://github.com/void-linux/void-packages/blob/master/srcpkgs/AlsaMixer.app/template) and [here](https://github.com/void-linux/void-packages/blob/master/srcpkgs/R-cran-data.table/template)).

Any pointers (or additions to [this section of the manual](https://github.com/void-linux/void-packages/blob/master/Manual.md#programs)) would be much appreciated!

**Comment by CameronNemo** [comment]
We discussed this in #2328

**Comment by sgn** [comment]
Seems like we resolved and accepts dot.
