### ISSUE TITLE
void-update script didn`t find update for mate-desktop (and panel, applets, etc.)

### ISSUE THREAD

**Issue by Ilia1** [void-linux/void-packages#47798]
### Is this a new report?

Yes

### System Info

Void 6.5.13_1 x86_64 GenuineIntel uptodate rrFFFFFF

### Package(s) Affected

mate-desktop

### Expected behaviour

`./xbps-src update-check mate-desktop`
find actual version 1.27.3

### Actual behaviour

`./xbps-src update-check mate-desktop`
mate-desktop-1.26.1 -> mate-desktop-1.26.2

### Steps to reproduce

1. `git clone https://github.com/void-linux/void-packages.git`
2. `./xbps-src update-check mate-desktop`

And also affect to another mate component (panel, applets, terminal etc.)

**Comment by classabbyamp** [comment]
running with `XBPS_UPDATE_CHECK_VERBOSE=yes` shows that they are ignored, probably due to being unstable releases:

```
using mate-desktop/update overrides
fetching https://mate-desktop.org and scanning with (?<!-)\b\Qmate-desktop\E[-_]?((src|source)[-_])?v?\K([^-/_\s]*?\d[^-/_\s]*?)(?=(?:[-_.](?:src|source|orig))?\.(?:[jt]ar|shar|t[bglx]z|tbz2|zip))\b
(folder) fetching https://pub.mate-desktop.org/releases/ and scanning with href=["']?(\Qhttps://pub.mate-desktop.org/releases/\E)?\.?/?\K\Q\E[-_.0-9]*[0-9](|\.x)["'/]
fetching https://pub.mate-desktop.org/releases/1.26/ and scanning with (?<!-)\b\Qmate-desktop\E[-_]?((src|source)[-_])?v?\K([^-/_\s]*?\d[^-/_\s]*?)(?=(?:[-_.](?:src|source|orig))?\.(?:[jt]ar|shar|t[bglx]z|tbz2|zip))\b
fetching https://pub.mate-desktop.org/releases/1.27/ and scanning with (?<!-)\b\Qmate-desktop\E[-_]?((src|source)[-_])?v?\K([^-/_\s]*?\d[^-/_\s]*?)(?=(?:[-_.](?:src|source|orig))?\.(?:[jt]ar|shar|t[bglx]z|tbz2|zip))\b
found version 1.26.0
found version 1.26.1
found version 1.26.2
mate-desktop-1.26.1 -> mate-desktop-1.26.2
found version 1.27.0
ignored 1.27.0 due to *.*[13579].*
found version 1.27.1
ignored 1.27.1 due to *.*[13579].*
found version 1.27.2
ignored 1.27.2 due to *.*[13579].*
found version 1.27.3
ignored 1.27.3 due to *.*[13579].*
```

**Comment by Ilia1** [comment]
On github it`s marked as release
https://github.com/mate-desktop/mate-desktop/releases/tag/v1.27.3
I don`t find info that it unstable release.

**Comment by classabbyamp** [comment]
you'd have to ask @skmpz (https://github.com/void-linux/void-packages/pull/24719), but there's a fair amount of software that uses odd versions = development/beta releases

**Comment by skmpz** [comment]
it's stated in https://en.wikipedia.org/wiki/MATE_(desktop_environment)
```
Note that there are an odd number of versions between each official release. They are treated as versions under development, and are not announced as official releases.
```

**Comment by sgn** [comment]
Correct, odd version is unstable.
