### ISSUE TITLE
epstopdf missing after installing texlive-20210325_7

### ISSUE THREAD

**Issue by nbl0** [void-linux/void-packages#47815]
### Is this a new report?

Yes

### System Info

Void 6.1.55_2 x86_64 AuthenticAMD uptodate rrmFFFFFFFF

### Package(s) Affected

texlive-20210325_7

### Expected behaviour

I want to install **epstopdf** find in texlive-**20210325_7** package by **xlocate**.

### Actual behaviour

**esptopdf** is not installed, it's missing in **/usr/bin/**

### Steps to reproduce

$ sudo xbps-install -Su texlive-20210325_7
$ /usr/bin/epstopdf

**Comment by classabbyamp** [comment]
duplicate of https://github.com/void-linux/void-packages/issues/43674#issuecomment-1563023591
