### ISSUE TITLE
xbps-remove -oO gives: Broken, unresolvable shlib `libpodofo.so.2'

### ISSUE THREAD

**Issue by kotoko** [void-linux/void-packages#47907]
### Is this a new report?

Yes

### System Info

Void 6.5.13_1 x86_64 GenuineIntel uptodate FFF

### Package(s) Affected

calibre-7.1.0_1 krename-5.0.2_3 scribus-1.5.8_13 libpodofo-0.10.3_1 libpodofo0.9.7-0.9.7_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Here is the official instruction saying that I should just wait.
https://docs.voidlinux.org/xbps/troubleshooting/common-issues.html#shlib-errors

### Expected behaviour

I can update system and remove outdated packages without errros.

### Actual behaviour

For the last 3 weeks I am getting this error. I think it is long enough that „just waiting” does not fix the issue. 

Command `/usr/bin/xbps-remove --yes -Oo` produces error:
```
calibre-7.1.0_1: broken, unresolvable shlib `libpodofo.so.2'
krename-5.0.2_3: broken, unresolvable shlib `libpodofo.so.2'
scribus-1.5.8_13: broken, unresolvable shlib `libpodofo.so.2'
Transaction aborted due to unresolved shlibs.
```

### Steps to reproduce

I run these commands to update system:

```
/usr/bin/xbps-install --yes -Su xbps
/usr/bin/xbps-install --yes -Su
/usr/bin/xbps-install --yes -Su
/usr/bin/vkpurge rm all
/usr/bin/xbps-remove --yes -Oo
```

I am using mirrors.dotsrc.org mirror:
```
repository=https://mirrors.dotsrc.org/voidlinux/current
repository=https://mirrors.dotsrc.org/voidlinux/current/nonfree
```

**Comment by Anachron** [comment]
Why are you running these commands which --yes? Are they automated?

You should check what it is doing.

**Comment by kotoko** [comment]
I have script `update.sh` with those lines that I manually run. Are you saying `--yes` could produce this error?

**Comment by Duncaen** [comment]
You should probably not use `--yes`, it makes sense to confirm and verify what xbps is going to do.

The steps to reproduce obviously don't work, what would be more helpful would be a log with `--verbose` and `--debug` flags.

**Comment by kotoko** [comment]
Obviously using `--yes` does not make any difference in reproducing this issue but here is output of `xbps-remove -oO --debug --verbose 2> /tmp/log2.txt`

[log2.txt](https://github.com/void-linux/void-packages/files/13777844/log2.txt)

**Comment by kotoko** [comment]
I am not used to github's web interface - only now I see that sgn made a commit and closed issue. I thought that it was Duncaen that closed issue. Anyway I will wait few days so there is time to build packages and propagate to mirrors and will come back if problem persists.
