### ISSUE TITLE
pam-1.5.3_3: broken, unresolvable shlib `libcrypt.so.1'

### ISSUE THREAD

**Issue by brian6932** [void-linux/void-packages#47912]
### Is this a new report?

Yes

### System Info

Void 6.1.54_1 aarch64 Unknown uptodate hold rFF

### Package(s) Affected

pam-1.5.3_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

🤷 Didn't see anything

### Expected behaviour

xbps-install -Su should work

### Actual behaviour

Doesn't work
```nu
xbps-install --debug --verbose -Su out+err> err
```
err file https://i.alienpls.org/EXA (couldn't paste output `There was an error creating your Issue: body is too long (maximum is 65536 characters).`)

### Steps to reproduce

1. xbps-install -Su

**Comment by classabbyamp** [comment]
0df79cb0813258b7f1b81ef81ebb1bf957ce340d
