### ISSUE TITLE
Running vbin copies only part of AppImages

### ISSUE THREAD

**Issue by WilfSilver** [void-linux/void-packages#47915]
### Is this a new report?

Yes

### System Info

Void 6.6.8_1 x86_64 GenuineIntel notuptodate rFF

### Package(s) Affected

none

### Expected behaviour

While trying to learn how to add my own packages in `xbps-src`, I tried setting up a package with an AppImage (in this case `anytype` as I had installed the app image manually before), with part of the install script (see full template in steps to reproduce) being:

```
  vbin ${XBPS_SRCDISTDIR}/${pkgname}-${version}/${_appimage} anytype
```

I expected this line to copy the AppImage fetched and make it an executable named `anytype`, which then could be run to start the application once properly packaged and installed.

### Actual behaviour

Once installed, and once tried to run I get the output:

```
This doesn't look like a squashfs image.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
```

(which is confusing as `fuse` is a dependency and was installed)

After some investigating, I found that running the AppImage from the `hostdir` started the application without issues.

Running:

```
$ ls -al masterdir/destdir/anytype-0.37.0/usr/bin/anytype hostdir/sources/anytype-0.37.0/Anytype-0.37.0.AppImage
.rwxr-xr-x 188k wilf 26 Dec 22:14  masterdir/destdir/anytype-0.37.0/usr/bin/anytype
.rwxr-xr-x 325M wilf 22 Dec 17:11  hostdir/sources/anytype-0.37.0/Anytype-0.37.0.AppImage
```

Shows that the file sizes are different and I can find no documentation on any weird things `xbps-src` might be doing which could be causing this - but definitely could have missed something obvious.

To double check it was just copying incorrectly, I ran `chroot` and manually copied the file over with `cp` and then packaged and installed it (as shown in steps to reproduce). After doing this, it worked just fine.

I have also tried using: `vinstall`, `vcopy` and `cp` in the `do_install` which all had the same effect, so I'm really confused if I'm just blatantly missing something (especially with the `cp` one).

### Steps to reproduce

1. copy configuration from [my test package](https://github.com/WilfSilver/void-packages/commit/af29c46ad9d8e98b8dca2eb24324a0d61bc4f27f)
2. Run:

  ```sh
  ./xbps-src pkg Anytype
  xi Anytype
  anytype # ERROR
  ```

To successfully install it:

1. copy configuration from [my test package](https://github.com/WilfSilver/void-packages/commit/af29c46ad9d8e98b8dca2eb24324a0d61bc4f27f)

  ```sh
  ./xbps-src install Anytype
  ./xbps-src chroot
  $ cp host/sources/Anytype-0.37.0/Anytype-0.37.0.AppImage destdir/Anytype-0.37.0/usr/bin/anytype
  $ exit
  ./xbps-src pkg Anytype
  xi Anytype
  anytype # success
  ```

**Comment by Johnnynator** [comment]
Just a geuess, does stripping the appimage manually break it?
You could try adding `nostrip` (See `Manual.md` / other templates) and see if it might fix this.

**Comment by WilfSilver** [comment]
Yup thank you! This has fixed the issue
