### ISSUE TITLE
patch nss-mdns musl

### ISSUE THREAD

**Issue by firmwarecostum** [void-linux/void-packages#47917]
### Is this a new report?

Yes

### System Info

no

### Package(s) Affected

nss-mdns

### Does a report exist for this bug with the project's home (upstream) and/or another distro?
nss-mdns-0.15.1

```
#ifndef _NSS_H
#define _NSS_H  1

#include <features.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>

/* Possible results of lookup using a nss_* function.  */
enum nss_status
{
  NSS_STATUS_TRYAGAIN = -2,
  NSS_STATUS_UNAVAIL,
  NSS_STATUS_NOTFOUND,
  NSS_STATUS_SUCCESS,
  NSS_STATUS_RETURN
};

/* Data structure used for the 'gethostbyname4_r' function.  */
struct gaih_addrtuple
  {
    struct gaih_addrtuple *next;
    char *name;
    int family;
    uint32_t addr[4];
    uint32_t scopeid;
  };

#endif

```

### Expected behaviour

no

### Actual behaviour

no

### Steps to reproduce

no

**Comment by classabbyamp** [comment]
is this a package request or something?

**Comment by firmwarecostum** [comment]
> is this a package request or something?

I asked for nss-mdns to be updated

**Comment by classabbyamp** [comment]
1. please don't request package updates, there's already a script that generates a list of available updates: https://repo-default.voidlinux.org/void-updates/void-updates.txt
2. nss-mdns is already up to date (at 0.15.1)
3. nss is not supported on musl
