### ISSUE TITLE
xbps-install -Su fails with "python3-3.12.0_1: broken, unresolvable shlib `libcrypt.so.1'"

### ISSUE THREAD

**Issue by michael-ball** [void-linux/void-packages#47922]
### Is this a new report?

Yes

### System Info

Void 6.1.67-rt20_1 x86_64 GenuineIntel uptodate hold rrrmDFFFF

### Package(s) Affected

python3-3.12.0_1

### Expected behaviour

`xbps-install -Su` completes without error

### Actual behaviour

Running `xbps-install -Su` results in the following error:

```
python3-3.12.0_1: broken, unresolvable shlib `libcrypt.so.1'
Transaction aborted due to unresolved shlibs.
```

### Steps to reproduce

1. On a system with python3 already installed, run `sudo xbps-install -Su`
2. OR try to install python3 with `sudo xbps-install -S python3`

**Comment by michael-ball** [comment]
Ah looks like it's being rebuilt after [6da4516](https://github.com/void-linux/void-packages/commit/6da4516f5d30cbd5ce456a6d52477ef72f052e7a)

**Comment by classabbyamp** [comment]
what mirror? it should be already rebuilt

**Comment by michael-ball** [comment]
This is on the repo-default.voidlinux.org mirror. I'm not seeing the issue when I switch to repo-de.voidlinux.org.

My only package on hold is "cdrdao".

**Comment by Sheape** [comment]
I get the same issue when compiling it from source using the template using the repo-ci.voidlinux.org mirror.
```
Error:  _crypt failed to import: /builddir/python3-3.12.0/build/lib.linux-x86_64-3.12/_crypt.cpython-312-x86_64-linux-gnu.so: undefined symbol: crypt
The necessary bits to build these optional modules were not found:
_tkinter              _uuid                 nis                
To find the necessary bits, look in configure.ac and config.log.

Following modules built successfully but were removed because they could not be imported:
_crypt
```

Im using void-buildroot-glibc:20230904R2 for the docker image

**Comment by Sheape** [comment]
> I get the same issue when compiling it from source using the template using the repo-ci.voidlinux.org mirror.
> 
> ```
> Error:  _crypt failed to import: /builddir/python3-3.12.0/build/lib.linux-x86_64-3.12/_crypt.cpython-312-x86_64-linux-gnu.so: undefined symbol: crypt
> The necessary bits to build these optional modules were not found:
> _tkinter              _uuid                 nis                
> To find the necessary bits, look in configure.ac and config.log.
> 
> Following modules built successfully but were removed because they could not be imported:
> _crypt
> ```
> 
> Im using void-buildroot-glibc:20230904R2 for the docker image

nvm, I forgot to update the submodules that's why it didn't work. All good now!
