### ISSUE TITLE
7zip errors when compressing directories containing broken symlinks

### ISSUE THREAD

**Issue by Samueru-sama** [void-linux/void-packages#47938]
### Is this a new report?

Yes

### System Info

Void 6.6.8_1 x86_64 GenuineIntel uptodate rrrmFFFF

### Package(s) Affected

7zip-23.01_1

### Expected behaviour

Compressing any directory should just work even if it contains a broken symlink

### Actual behaviour

7zip throws file not found errors for the broken symlink that causes file-roller to not create the compressed file while xarchiver gives a warning. 

### Steps to reproduce

For this I used thunar with thunar-archive-plugin and file-roller and xarchiver:

Make a directory, place a broken symlink inside and then try to compress it to 7zip.

This entire reddit thread has video demonstration of the issue on void and also a comparison with the same steps on arch. 

https://old.reddit.com/r/voidlinux/comments/18s3hf0/cant_compress_directories_to_7zip_if_they_contain/

In the end I tested using the 7zip binaries from arch on void and the issue went away.

**Comment by ahesford** [comment]
Comparing to Arch is moot because Arch uses a completely different upstream project.

Rejecting compression when attempting to follow broken symlinks is entirely reasonable. In any case, this is an issue that should be taken upstream.

**Comment by Samueru-sama** [comment]
> Comparing to Arch is moot because Arch uses a completely different upstream project.
> 
> Rejecting compression when attempting to follow broken symlinks is entirely reasonable. In any case, this is an issue that should be taken upstream.

It is not only arch, void is the only distro that I've ever encountered that has this issue. 

And it is not reasonable if it breaks file-roller and xarchiver. Also why does it need to follow the symlink? Is it going to try to take everything in the symlink to compress?

Say I have my steam directory symlinked in home and I try to compress my home dir for backup, I really hope it will not try to compress my entire steam library in the process.

**Comment by ahesford** [comment]
There is no `-l` option in 7zip. You aren't looking at the right command. There *is*, however, an `-snl` switch to "store symbolic links as links", which is probably what you want. This isn't even a bug, it's an error in your expectation.

**Comment by oreo639** [comment]
7zip does not have `-l`. You are confusing p7zip and 7zip, Void does not have p7zip anymore.
https://gitlab.gnome.org/GNOME/file-roller/-/issues/148#note_1382009

With 7zip, you can can use `-snl` to not follow symlinks.

**Comment by classabbyamp** [comment]
we should probably patch file-roller and other software that call 7z assuming it's p7z because of the switch we made

**Comment by Samueru-sama** [comment]
> There is no `-l` option in 7zip. You aren't looking at the right command. There _is_, however, an `-snl` switch to "store symbolic links as links", which is probably what you want. This isn't even a bug, it's an error in your expectation.

Oh I see now, sorry I did `man 7z` on arch but forgot that arch points to p7zip instead.
