### ISSUE TITLE
fwupd refresh fails with "signatures were required, but none supplied"

### ISSUE THREAD

**Issue by haunma** [void-linux/void-packages#47932]
### Is this a new report?

Yes

### System Info

Void 6.7.0-rc6_1 x86_64 AuthenticAMD uptodate rFF

### Package(s) Affected

fwupd-1.9.10

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Google could not find one.

### Expected behaviour

After installing fwupd, it should be possible to check for firmware updates using
`fwupdmgr refresh`
without error.

### Actual behaviour

```
$ sudo fwupdmgr refresh
WARNING: UEFI capsule updates not available or enabled in firmware setup
See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
Updating lvfs
Downloading…             [    \                                  ]
(fwupdmgr:2222): Fwupd-CRITICAL **: 16:25:28.943: fwupd_checksum_guess_kind: assertion 'checksum != NULL' failed
Downloading…             [***************************************]
Failed to update metadata for lvfs: signatures were required, but none supplied
```

### Steps to reproduce

As root,
1.  xbps-install fwupd
2.  fwupdmgr refresh

**Comment by sgn** [comment]
```
$ fwupdmgr refresh
WARNING: UEFI ESP partition not detected or configured
See https://github.com/fwupd/fwupd/wiki/PluginFlag:esp-not-found for more information.
Updating lvfs
Downloading…             [***************************************]
Successfully downloaded new metadata: 5 local devices supported
```

**Comment by haunma** [comment]
Was this a fresh install, running fwupdmgr for ths first time?

I'm sure that it works once the proper keys are installed.  The trouble is, it's not clear how to get to that point.
