### ISSUE TITLE
Package request: cowsql / libcowsql / libcowsql-devel

### ISSUE THREAD

**Issue by sbromberger** [void-linux/void-packages#47941]
### Package name

cowsql / libcowsql / libcowsql-devel

### Package homepage

https://github.com/cowsql/cowsql

### Description

[cowsql](https://cowsql.dev/) (/ˈkaʊ,siːkwəl/ [listen](http://ipa-reader.xyz/?text=%CB%88ka%CA%8A%2Csi%CB%90kw%C9%99l)) is a C library that implements an embeddable and replicated SQL database engine with high availability and automatic failover.

cowsql extends [SQLite](https://sqlite.org/) with a network protocol that can connect together various instances of your application and have them act as a highly-available cluster, with no dependency on external databases.

Cowsql is a required dependency for multiple libraries, including incus (the lxd replacement).

### Does the requested package meet the package requirements?

System, Compiled, Required

### Is the requested package released?

Yes

**Comment by sbromberger** [comment]
See also https://github.com/void-linux/void-packages/pull/47573

**Comment by dkwo** [comment]
of course, since incus is in the repo, these are too.

**Comment by sbromberger** [comment]
Yup - this issue was created prior to the incus package being merged. Closing :)
