### ISSUE TITLE
Version Bump Request: kitty 0.11.1

### ISSUE THREAD

**Issue by The-BigDaddy** [void-linux/void-packages#480]
Not a big deal, but version 0.11.1 is out and has fixed a few things and added since the verson. Have had troubles getting it to work from building from source, so might as well stick to what's in the repos.

https://sw.kovidgoyal.net/kitty/changelog.html

**Comment by newbluemoon** [comment]
It’s already in the pipeline (#188). ;)

**Comment by maxice8** [comment]
There is a PR open for this as noted by @newbluemoon

**Comment by cr6git** [comment]
@The-BigDaddy done.
