### ISSUE TITLE
Package request: Vieb

### ISSUE THREAD

**Issue by simonhughxyz** [void-linux/void-packages#48009]
### Package name

Vieb

### Package homepage

https://github.com/Jelmerro/Vieb

### Description

A vim inspired browser built on top of Electron.
Has regular package releases and licensed under GPL.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/issues/30165
