### ISSUE TITLE
Restructuring/Organizing general Packages etc.

### ISSUE THREAD

**Issue by removewingman** [void-linux/void-packages#48014]
Hello everyone,

in my opinion this repo is way to big and I would like a restructuring. My idea is to do for each category a seperate Repo. As far as my understanding goes it would be relatively easy to add more repositories to xbps. For categories there could be e.g. one for desktop environments, window managers, terminal emulators, wayland, xorg, dev-utils and so much more. The advantages are, because of the organization it is way easier to maintain and to orientate. The only problem that came to my mind is that the xbps-src script needs to be the same in all those repos, but im sure there is a solution to this problem.
The second idea I had was to switch to Gitlab instead of Github because of the group feature in Gitlab you can even better organize your Repos. 
Let me know what you think of the idea.

**Comment by classabbyamp** [comment]
xbps-src needs all packages in the same repo for dependency resolution and other functionality

gitlab is fairly out of the question:

1. (IMO) the UI/UX are awful to the point of giving me a headache whenever I have to use it
2. the amount of compute for CI we get provided free by github would be prohibitively expensive to replace on other platforms

**Comment by removewingman** [comment]
Thanks for the answer, I did not know that with the dependencies what a bummer.

**Comment by removewingman** [comment]
I'm curious could you not provide for each repo one file where every package is listed, and the build script has every file of each repo locks through it and searches for the dependencies, that is how the build script knows in which repo to get the dependencies from, wouldn't that solve the problem? What is the other functionality, so that everything needs to stay in one repo?

**Comment by classabbyamp** [comment]
if you move things into multiple repos, you make any kind of large change (e.g. ones that require rebuilding many packages) much harder. you'd have to coordinate pull requests or pushes between repos, ensure every repo has consistent state, do git actions many times over to sync all the different repos, etc.

it's just harder to manage, and would require significant rework of infrastructure and processes.

**Comment by removewingman** [comment]
In my opinion it would be worth it, as the projects grows in the long run makes it easier. But in the end it is your decision.

**Comment by Duncaen** [comment]
There is absolutely no way it would make anything easier to run in the long run, @classabbyamp has a more in-depth understanding of how this repository works.

Even simple packages have chains of dependencies that go into hundreds of packages, orchestrating changes through multiple git repositories is simply not feasible. Large organization use mono-repos for similar reasons, it just makes everything easier to manage and orchestrate and its not like our repository is that big either, the only big problem is the single large `srcpkgs` directory.
