### ISSUE TITLE
Keybase client cert error. Might need new package build instead of just an update.

### ISSUE THREAD

**Issue by lee2sman** [void-linux/void-packages#48036]
The Keybase dev team made a [mistake](https://github.com/keybase/keybase-issues/issues/4219#issuecomment-1874724687) and a new Keybase client is now needed. If I'm understanding, it's not possible to just update the app (that didn't work for me), but a new build of the latest 6.2.5 release of Keybase is needed.

**Comment by lee2sman** [comment]
I'm not experienced really in packaging but took a first attempt. Unfortunately, getting errors on building with Go.

My attempt at an updated [template](https://gist.github.com/lee2sman/4a49512fc5f7b03948ece92e6516a9cc#file-template) and the packaging build error.

**Comment by ar-jan** [comment]
I ran into the same errors and asked about in the keybase repo: https://github.com/keybase/client/issues/26144. No answer in two months. I've seen others commenting that keybase is basically dead.

**Comment by lee2sman** [comment]
Well they fixed the Windows, Mac and Debian/Ubuntu clients (there's also fedora/red hat, arch aur) but they of course don't directly package for Void themselves.  I'm not great at packaging and don't work in Go. It looks like some of the Go packages repo names have changed and I can't figure out where these are listed. It messes up when downloading some of the crypto libraries, not found in path.

**Comment by ar-jan** [comment]
Yes they're still creating releases, but the general state of the project seems to be going downhill since being acquired by Zoom.

**Comment by lee2sman** [comment]
Came back to this. Still can't get it since I don't really understand Go or the build system as a whole. The main thing appears that some dependencies and paths have changed since the initial template was built.

In response to a build error I tried modifying common/build-style/go.sh in line 59 I'm getting errors thrown from the old "go get" command which should now be "go install". I changed to ```go install -p "$XBPS_MAKEJOBS" -mod="" -x -tags "${go_build_tags}" -ldflags "${go_ldflags}" ${go_package}```. Note that I removed mod flag {go_mod_mode} as I didn't understand how it should be set. 

I'm still getting errors like the following:

```
_build-keybase-xbps/src/github.com/keybase/client/go/client/markup.go:12:2: cannot find package "github.com/PuerkitoBio/goquery" in any of:
	/usr/lib/go/src/github.com/PuerkitoBio/goquery (from $GOROOT)
	/builddir/keybase-6.2.8/_build-keybase-xbps/src/github.com/PuerkitoBio/goquery (from $GOPATH)
```

**Comment by onli** [comment]
Still relevant.

**Comment by lee2sman** [comment]
Yes, unfortunately the same problem. I haven't been able to figure out how to make a usable build. Need someone who groks Go packages/ecosystem and Void.

**Comment by classabbyamp** [comment]
make a PR and we can work through it

**Comment by onli** [comment]
The client seems to work again for me. You worked it out? Awesome, thanks!

Probably this issue can be closed?

**Comment by lee2sman** [comment]
Thanks! I am just waiting for my last pull request to be completed #52055 which I think is needed for new desktop client installs.
