### ISSUE TITLE
Package request: Midori 11.2

### ISSUE THREAD

**Issue by Ilia1** [void-linux/void-packages#48065]
### Package name

midori

### Package homepage

https://github.com/goastian/midori-desktop

### Description

Midori have precompiled package for void. 
But this update difference from previous. It`s now gecko based.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
Please don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.

**Comment by Ilia1** [comment]
Script don`t work, because main repo changed.
I want know best way update package - rename old, rename new, just update. Because this browser only save name and change all another.

**Comment by classabbyamp** [comment]
keep the name and rewrite the template i think

**Comment by AgarimOSLinux** [comment]
@classabbyamp Midori is now based on Floorp (a fork of Firefox ESR). I guess it should be removed from the repos.

**Comment by AgarimOSLinux** [comment]
A prebuilded package from a fork from a fork from Firefox? No thank you.

**Comment by AgarimOSLinux** [comment]
There is a PR to remove it:
https://github.com/void-linux/void-packages/pull/48893

Midori is a browser fork of Floorp fork of Firefox by Astian (also confirmed to me by one the developers):
https://aur.archlinux.org/packages/midori-bin

One of the developers, asked for help in a Telegram channel. I was well explained that he should create a template and make a PR (like everybody else). 

And I am not the person that have to decide to include it or not in the repos.
