### ISSUE TITLE
glibc pinebook pro aarch64: Invalid cross-device link

### ISSUE THREAD

**Issue by atweiden** [void-linux/void-packages#48071]
### Is this a new report?

Yes

### System Info

Void 6.1.9_1 aarch64 Unknown notuptodate hold rFF

### Package(s) Affected

glibc

### Expected behaviour

`glibc` package upgrades succeed.

### Actual behaviour

`glibc` package upgrades fail. Third time this has happened during `glibc` upgrade on pinebook pro.

```
[*] Unpacking packages
libxcrypt-compat-4.4.36_3: unpacking ...
libxcrypt-compat-4.4.36_3: unpacked file `./usr/lib/libcrypt.so.1' (0 bytes)
glibc-2.38_2: updating to 2.38_3 ...
glibc-2.38_3: unpacking ...
glibc-2.38_3: unpacked file `./usr/lib/libthread_db.so' (0 bytes)
glibc-2.38_3: unpacked file `./usr/lib/libresolv.so' (0 bytes)
glibc-2.38_3: unpacked file `./usr/lib/libnss_hesiod.so' (0 bytes)
glibc-2.38_3: unpacked file `./usr/lib/libnss_db.so' (0 bytes)
glibc-2.38_3: unpacked file `./usr/lib/libnss_compat.so' (0 bytes)
glibc-2.38_3: unpacked file `./usr/lib/libmvec.so' (0 bytes)
glibc-2.38_3: unpacked file `./usr/lib/libc_malloc_debug.so' (0 bytes)
glibc-2.38_3: unpacked file `./usr/lib/libanl.so' (0 bytes)
glibc-2.38_3: unpacked file `./usr/lib/libBrokenLocale.so' (0 bytes)
glibc-2.38_3: unpacked file `./usr/lib/getconf/POSIX_V7_LP64_OFF64' (0 bytes)
glibc-2.38_3: unpacked file `./usr/lib/getconf/POSIX_V6_LP64_OFF64' (0 bytes)
glibc-2.38_3: unpacked file `./usr/bin/ld.so' (0 bytes)
ERROR: glibc-2.38_3: [unpack] failed to extract file `./usr/bin/getconf': Invalid cross-device link
ERROR: glibc-2.38_3: [unpack] failed to extract files: Invalid cross-device link
ERROR: glibc-2.38_3: [unpack] failed to unpack files from archive: Invalid cross-device link
Transaction failed! see above for errors.
```

### Steps to reproduce

1. Attempt upgrading glibc on Pinebook Pro

**Comment by classabbyamp** [comment]
what is your partition layout? is `/usr/lib` on a different filesystem than `/usr/bin`?

**Comment by classabbyamp** [comment]
glibc 2.36 has the same hardlink for `/usr/bin/getconf` so not sure why that would cause an issue

**Comment by classabbyamp** [comment]
why?

**Comment by ahesford** [comment]
This may be expected behavior (it certainly isn't surprising, given your atypical mounts), or it could be an issue with the kernel, libarchive. I suggest you try manually unpacking the glibc package over the filesystem structure using both GNU tar and bsdtar to try to gain insight.

Regardless of the outcome, this is definitely not a void-packages issue.
