### ISSUE TITLE
LanguageTool-5.8_1: languagetool fails to run after installation

### ISSUE THREAD

**Issue by algor512** [void-linux/void-packages#48076]
### Is this a new report?

Yes

### System Info

Void 6.6.9_1 x86_64 AuthenticAMD notuptodate F

### Package(s) Affected

LanguageTool-5.8_1

### Expected behaviour

`/bin/languagetool` runs without any error after the installation. 

### Actual behaviour

```
$ /bin/languagetool
/bin/languagetool: line 67: /bin/java: No such file or directory
```

### Steps to reproduce

```
# xbps-install -S LanguageTool
[*] Updating repository `https://repo-fastly.voidlinux.org/current/x86_64-repodata' ...
Package `xbps' already installed.
[*] Updating repository `https://repo-fastly.voidlinux.org/current/x86_64-repodata' ...

Name           Action    Version           New version            Download size
openjdk-common install   -                 1_1                    1588B
openjdk11-jre  install   -                 11.0.22+6_1            46MB
openjdk11      install   -                 11.0.22+6_1            4219KB
LanguageTool   install   -                 5.8_1                  210MB
<...>
$ /bin/languagetool
/bin/languagetool: line 67: /bin/java: No such file or directory
```

**Comment by classabbyamp** [comment]
have you re-logged in since installing languagetool?

what's the output of `xbps-alternatives -lg java`?

**Comment by algor512** [comment]
I'm sorry, but I've resolved the issue.
I use fish shell, and it doesn't use `/etc/profile.d` to initialize environment variables. Hence, I have to manually set `JAVA_HOME` to point to `/usr/lib/jvm/default-jre`. After doing that, languagetool runs successfully.
