### ISSUE TITLE
ERROR: [trans] failed to download `...' signature from `...': Permission denied

### ISSUE THREAD

**Issue by ohoes** [void-linux/void-packages#48105]
### System

- xuname:
Void 6.6.9_1 x86_64-musl GenuineIntel notuptodate rFF

- package:
Any

### Expected behavior

Succesful package install

### Actual behavior

```
ERROR: [trans] failed to download `...' signature from `...': Permission denied
Transaction failed! see above for errors.
```

Steps to reproduce the behavior

`sudo xbps-install -Su`

Other mirrors also seem to be affected.

**Comment by classabbyamp** [comment]
what is the full error message, not abbreviated? what mirror?

**Comment by classabbyamp** [comment]
are there any other messages before that? like something about a certificate maybe?

**Comment by kh0r0t0** [comment]
**

> `thank's it working with me ^^`

**
