### ISSUE TITLE
Cannot connect to libvirt from Virt-Manager

### ISSUE THREAD

**Issue by Calandracas606** [void-linux/void-packages#48133]
### Is this a new report?

Yes

### System Info

Void 6.6.10_1 x86_64-musl GenuineIntel uptodate rFFFFF

### Package(s) Affected

libvirt-9.10.0_1, virt-manager-4.1.0_3

### Expected behaviour

virt-manager connects to libvirt

### Actual behaviour

virt-manager shows "QEMU/KVM - Connecting..."

### Steps to reproduce

1. Enable required services (dbus, libvirtd, virtlockd, virtlogd)
2. Add user to "libvirt" group
3. Sign in as user
4. Launch virt-manager

Suck on "QEMU/KVM - Connecting..."

**Comment by Calandracas606** [comment]
I've tried the fix from this issue with no success: https://github.com/void-linux/void-packages/issues/14721

There are many vague "libvirt isn't working on musl" issues on the internet, but its difficult to identify which ones might be relevant

**Comment by dataCobra** [comment]
Hey, could you start virt-manager from a terminal so you can see that stdout which gets produced by virt-manager?

This could be helpful to understand what might cause the connection issue.

**Comment by Calandracas606** [comment]
When I tried it again to collect logs, it mysteriously worked, despite not having changed anything for several days.

The same day that I submitted this ticked, I followed some troubleshooting as suggested on IRC. 

I tried disabling the libvirtd service, and instead enabling:

- virtlockd
- virtlogd
- virtqemud
- virtstoraged
- virtnetworkd
- virtinterfaced
- virtnodedevd
- virtnwfilterd
- virtsecretd

Initially this did not work, even after several reboots.

Also tried using gnome-boxes, both the void package and flatpak, neither of them worked.

Attaching logs for future reference. [virt-manager.log](https://github.com/void-linux/void-packages/files/13928917/virt-manager.log)

Will close this ticket for now, and it appears to be working.
