### ISSUE TITLE
Support intel-ucode when using mkinitcpio

### ISSUE THREAD

**Issue by basploeger** [void-linux/void-packages#48145]
### Is this a new report?

Yes

### System Info

Void 6.6.10_1 x86_64 GenuineIntel uptodate rrrmFFFFFF

### Package(s) Affected

intel-ucode-20231114_1, mkinitcpio-37_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No. But [this information](https://wiki.archlinux.org/title/microcode#Initrd_images) from Arch Linux is useful for reference.

Arch's intel-ucode package generates the necessary `/boot/intel-ucode.img` [here](https://gitlab.archlinux.org/archlinux/packaging/packages/intel-ucode/-/blob/main/PKGBUILD?ref_type=heads#L22). 

### Expected behaviour

Intel microcode gets loaded in early boot before loading the initramfs produced by mkinitcpio.

### Actual behaviour

Intel microcode does not get loaded as testified by the following console error messages before initramfs gets loaded:

```
TSC_DEADLINE disabled due to Errata; please update microcode to version: 0x52 (or later)
RETBleed: WARNING: Spectre v2 mitigation leaves CPU vulnerable to RETBleed attacks, data leaks possible!
```

These error messages disappear when loading an initramfs produced by dracut, as the intel-ucode package supports dracut already.

### Steps to reproduce

1. Install intel-ucode.
2. [Switch](https://docs.voidlinux.org/config/kernel.html#changing-the-default-initramfs-generator) from dracut to mkinitcpio
3. Reboot

**Comment by basploeger** [comment]
Right, mkinitcpio does not support loading microcode natively, unlike dracut. So we have to load microcode from the boot loader as explained further down on that page: generate /boot/intel-ucode.img and instruct the boot loader to load that image before loading the initramfs. For example, `grub-mkconfig` should auto-detect that image file and add it to the grub config.

**Comment by classabbyamp** [comment]
iirc you can also `cat` the two images into one combined ucode + initrd

**Comment by classabbyamp** [comment]
a solution is in progress in concert with upstream: https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/merge_requests/291

**Comment by classabbyamp** [comment]
microcode support has now been added on mkinitcpio's master branch and will be released with version 38 probably sometime this month.

**Comment by classabbyamp** [comment]
as of mkinitcpio 38, the microcode hook has been released. install the relevant microcode package (`intel-ucode` or `linux-firmware-amd`) and add `microcode` to the `HOOKS` array in `/etc/mkinitcpio.conf`. if the hook is placed after `autodetect`, only microcode for the your host cpu will be added.
