### ISSUE TITLE
alacritty-0.13.1 fails to start

### ISSUE THREAD

**Issue by 0323pin** [void-linux/void-packages#48196]
### Is this a new report?

Yes

### System Info

Void 6.6.10_1 x86_64-musl GenuineIntel uptodate rFFFFF

### Package(s) Affected

ii alacritty-0.13.1_1

### Expected behaviour

Alacritty starts.

### Actual behaviour

```
thread 'main' panicked at /host/cargo/registry/src/index.crates.io-6f17d22bba15001f/xkbcommon-dl-0.4.1/src/x11.rs:59:28:
Library libxkbcommon-x11.so could not be loaded.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps to reproduce

Install alacritty and launch the terminal.

**Comment by 0323pin** [comment]
Installing libxkbcommon-x11 fixes it

**Comment by dataCobra** [comment]
Create PR #48197.
