### ISSUE TITLE
Current version (0.3.2_1) of octoxbps-notifier in repo doesn't show updates

### ISSUE THREAD

**Issue by voiduser123321** [void-linux/void-packages#48200]
### Is this a new report?

Yes

### System Info

Void 6.6.10_1 x86_64 GenuineIntel uptodate rrFFFF

### Package(s) Affected

octoxbps-0.3.2_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/aarnt/octoxbps/issues/37

### Expected behaviour

Octoxbps-notifier icon in tray is supposed to turn red after right-clicking it and selecting "Sync database" in menu.

### Actual behaviour

Octoxbps-notifier icon in tray stays green even after trying to update the database when there are available updates. Also, the database does not get updated.

### Steps to reproduce

1. Right-click the notifier in tray
2. Left-click "Sync database" in the menu
3. Behold the green icon

**Comment by sgn** [comment]
https://github.com/void-linux/void-packages/pull/48221
