### ISSUE TITLE
chocolate-doom's bash completion scripts are man pages instead

### ISSUE THREAD

**Issue by Jjp137** [void-linux/void-packages#48228]
### Is this a new report?

Yes

### System Info

Void 6.1.71_1 x86_64 GenuineIntel uptodate FFFFFFFF

### Package(s) Affected

chocolate-doom-3.0.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

no

### Expected behaviour

The `/usr/share/bash-completion/completions/chocolate-{doom,heretic,hexen,strife}` files should be Bash completion scripts.

### Actual behaviour

The `/usr/share/bash-completion/completions/chocolate-{doom,heretic,hexen,strife}' files are man pages.

This results in unexpected behavior, such as Chocolate Doom suddenly launching, when trying to tab-complete parameters such as WAD file names.

### Steps to reproduce

1. `xbps-install chocolate-doom`
2. `cat /usr/share/bash-completion/completions/chocolate-{doom,heretic,hexen,strife}`
3. Notice that the output looks similar to man pages.

**Comment by classabbyamp** [comment]
4a3efcb8397
