### ISSUE TITLE
Package request: gmp, so that it is *possible* to get Haskell Stack to work in Void aarch64.

### ISSUE THREAD

**Issue by libweirdness** [void-linux/void-packages#48232]
### Package name

GNU GMP Multiple Precision Arithmetic Library

### Package homepage

https://gmplib.org/

### Description

I'm trying to learn Haskell,

and Haskell Stack ( required by "Haskell Programming From 1st Principles" ) REQUIRES that this be installed & comprehensible.

Which is the problem.

As gmp isn't available through xbps, I installed it as root, and that *didn't* work, unfortunately...

https://duckduckgo.com/?q=%22cannot+find%22+%22lgmp%22+error&t=fpas&ia=web

..and you can see the error that I ( & others, in other contexts ) are having.

I'm not competent-enough in geeking to crack this one, without maybe a half-month of digging ( I don't have the requisite understanding, and I'm slow, due to lots of brain injury ), so I'm asking for Void-community's help in this.

Please make Haskell Stack installABLE, see?

( actually, I should perhaps be requesting Haskell Stack, itself, instead of the missing prerequisite for it?

BOTH, please!! : )

IF gmp is required for Haskell Stack, THEN I'm presuming it's *also* required for the other method for installing Haskell, the Haskell Platform method, which I think is GHCup...

Please help us learners "get in" to the learning, even if we're limited to living-in aarch64!

Salut, Namaste, Kaizen, & gratitude, too, eh?

( :

_ /\ _

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/gmp/template
