### ISSUE TITLE
Missing runtime dependency on Qgis (python3-PyQt5-multimedia)

### ISSUE THREAD

**Issue by mgi** [void-linux/void-packages#48262]
### Is this a new report?

Yes

### System Info

Void 6.6.11_1 x86_64 GenuineIntel uptodate rFF

### Package(s) Affected

qgis-3.34.2_1

### Expected behaviour

The python console should start correctly.

### Actual behaviour

Upon starting qgis, there is an error about a not found type in python so the python console fail to start.  Installing python3-PyQt5-multimedia solves this issue.

### Steps to reproduce

Just run qgis.

**Comment by CtrlC-Root** [comment]
I can reproduce this and the suggested fix. Here's the error that shows up for me before I install the missing package:

![image](https://github.com/void-linux/void-packages/assets/4819590/f31d12ec-9e40-4514-8399-76c8b714f1f4)

And in the console:

```
"<font color=\"red\">Couldn't load PyQGIS.<br>Python support will be disabled.</font><br><pre><br>Traceback (most recent call last):<br>&nbsp; File \"<string>\", line 1, in <module><br>&nbsp; File \"/usr/share/qgis/python/qgis/gui/__init__.py\", line 25, in <module><br>&nbsp; &nbsp; from qgis._gui import *<br>RuntimeError: qgis._gui cannot import type '����' from PyQt5.QtCore<br><br></pre>Python version:<br>3.12.1 (main, Dec 26 2023, 18:42:33) [GCC 12.2.0]<br><br>QGIS version:<br>3.34.2-Prizren 'Prizren', exported<br><br>Python path:<br>['/usr/share/qgis/python', '/home/alex/.local/share/QGIS/QGIS3/profiles/default/python', '/home/alex/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/home/alex/.local/lib/python3.12/site-packages', '/usr/lib/python3.12/site-packages']"
```
