### ISSUE TITLE
lxqt-powermanagement doesn't dim the screen nor turn off the monitor when idle timer is supposed to run out

### ISSUE THREAD

**Issue by voiduser123321** [void-linux/void-packages#48265]
### Is this a new report?

Yes

### System Info

Void 6.6.10_1 x86_64 GenuineIntel uptodate rrFFFF

### Package(s) Affected

lxqt-powermanagement-1.4.0_1

### Expected behaviour

Lxqt-powermanagement is supposed to turn off the screen and change the backlight brightness after time specified in "AC Idle time" and "Enable Backlight Change -> Idle time" respectively has passed.

### Actual behaviour

Lxqt-powermanagement never turns off the screen nor changes backlight brightness even when all these options are enabled. However, "Check backlight" button in "Power Management Settings" works as intended. Also, there is no battery icon in system tray.

### Steps to reproduce

1. Go to "LXQt Settings" -> "Session Settings" -> "Basic Settings"
2. Enable "Power Management" in "LXQt Modules" and log out and login back if disabled
3. Go to "LXQt Settings" -> "Power Management" -> "Idle"
4. Enable "Idleness Watcher" and set "When idle on AC" and "AC Idle time" as desired
5. Enable "Backlight Change" and set backlight percentage and "Idle time" as desired
6. Wait for specified time

**Comment by Barba-Q** [comment]
Reproducible - except I still have the battery Icon.

**Comment by voiduser123321** [comment]
> Reproducible - except I still have the battery Icon.

May I inquire, do you run your system on a Thinkpad? Apparenty, there is a [reproducibility crisis with this one](https://github.com/lxqt/lxqt/issues/2519#issuecomment-2040215772), so it would help to rule out hardware issues.

**Comment by voiduser123321** [comment]
Here's some more details about my setup. I'm usually running Xorg as a regular user, via startx, without display manager, using a command in my .xinitrc: exec startlxqt. Nevertheless, the same problem occurs when I run it via lxdm as well. My laptop is a librebooted Thinkpad T400.

This is the output of lxqt-powermanagement when ran from terminal.  

**[user@void ~]$  lxqt-powermanagement
BatteryChanged discharging: false chargeLevel: 99.3812 actionTime: QTime(Invalid)
Inhibit got: 32
Starting idlenesswatcher
"PowerButton" "" ""
"SuspendButton" "" ""
"HibernateButton" "" ""
QDBusConnection: name 'org.freedesktop.UPower' had owner '' but we thought it was ':1.142'
The X11 connection broke (error 2). Did the X11 server die?**

**Comment by voiduser123321** [comment]
Further digging around revealed that I disabled MIT-SCREEN-SAVER extension at one point and forgot about that. Reenabling extension resolved the "bug". Apparently, the joke is on me this time.
