### ISSUE TITLE
Path matters!

### ISSUE THREAD

**Issue by Feay** [void-linux/void-packages#4828]
Your documentation is VAGUE at best and obscured at worst! FIX this!
Add this to your documentation:
one must git clone onto the /  directory so that you end up with /void-packages/

also
chown root:<group> xbps-uchroot does not work nor is documented in a useful way.

Can you please just paste the correct commands?

Further Info:
There is an issue where when I git cloned into another directory other than / such as /rap/
and fallowed all the poor documentation when using /rap/void-packages/./xbps-src pkg nano or any other package i wanted to build it will fail saying it cannot find a C compiler!!! even though i fallowed the instructions and I can see  /rap/void-packages/masterdir/use/bin/ has gcc and g++

so then i asked around and everyone had NO explanation except don't use root account which is silly because your documentation does not spec no root or not, and in general on other distros you want to be root to use a toolchain!

Solution is:
git clone onto /  so that you end up with /void-packages/

it was suggested that do with in the homefolder, but root's homefolder is /root/ but i did not test this scenario

t2SDE  doesn't care where it is and it works just fine! maybe use their code to fix yours?

**Comment by maxice8** [comment]
> one must git clone onto the / directory so that you end up with /void-packages/

not necessary and not recommended

> chown root: xbps-uchroot does not work nor is documented in a useful way.

yeah maybe we can put path to /usr/bin/xbps-uchroot but that makes it useless for people that other paths for it, which are valid since one can just download and extract a xbps tarball.

> Can you please just paste the correct commands?

The correct commands will vary from workflow to workflow it is on the user to know what is necessary to change in our generic provided command to fit his workflow.

> There is an issue where when I git cloned into another directory other than / such as /rap/
and fallowed all the poor documetation when using /rap/void-packages/./xbps-src pkg nano or any other package i wanted to build it will fail saying it cannot find a C compiler!!! even though i fallowed the instructions and I can see /rap/void-packages/masterdir/use/bin/ has gcc and g++

Please post exact chain of commands used

> so then i asked around and everyone had NO explaination except dont use root acount which is silly because your doumentation does not spec no root or not, and ingeneral on other distros you want to be root to use a toolchain!

if you require root to compile stuff you're doing it wrong.

> Solution is:
git clone onto / so that you end up with /void-packages/

That is a poor solution, see below.

> it was suggested that do with in the homefolder, but root's homefolder is /root/ but i did not test this scenerio

use the $HOME of an unprivileged user

> t2SDE doesn't care where it is and it works just fine! maybe use their code to fix yours?

our code and documentation doesn't need to be fixed in regards to what you mention.

**Comment by the-maldridge** [comment]
xbps-src works as described in the manual.  Reading and following the manual is left as an exercise to the user.

**Comment by Feay** [comment]
using these instructions: https://github.com/void-linux/void-packages

chown root:xbuilder xbps-uchroot
chmod 4777 xbps-uchroot
usermod -a -G xbuilder root
usermod -a -G xbuilder voiduser
usermod -a -G xbuilder anon
cd void-packages
$ echo XBPS_CHROOT_CMD=uchroot > etc/conf
((this file is NOT part if a default install using i686 live dvd install
there for >  not >> in my case))


cd /
mkdir rap
cd /rap/
git clone git://github.com/void-linux/void-packages.git
((wait for it to finish))
cd /rap/void-packages/
./xbps-src binary-bootstrap
((wait for it to finish))
./xbps-src pkg nano
(( this fails with error check for c compiler can make executable = no, fails))

solution:
cd /
git clone git://github.com/void-linux/void-packages.git
((wait for it to finish))
cd /void-packages/
./xbps-src binary-bootstrap
((wait for it to finish))
./xbps-src pkg nano
((nano compiles and a package is built!))

putting the real commands??
ok:
this
# chown root:<group> xbps-uchroot
# chmod 4750 xbps-uchroot
# usermod -a -G <group> <user>

should be
# chown root:xbuilder xbps-uchroot
# chmod 4750 xbps-uchroot
# usermod -a -G xbuilder <user>


this
Your user must be added to a special group to be able to use
xbps-uchroot(1) and the executable must be setgid:

# chown root:<group> xbps-uchroot
# chmod 4750 xbps-uchroot
# usermod -a -G <group> <user>

should be read:
_______________________________
Your user must be added to a special group "xbuilder" to be able to
use xbps-uchroot and the executable must be setgid this means a 4byte
chmod sequence 4750 as below:

# chown root:<group> xbps-uchroot
# chmod 4750 xbps-uchroot
# usermod -a -G <group> <user>
__________________________________

delete this confusing line underneath:  NOTE: by default in void you
shouldn't do this manually, your user must be a member of the xbuilder
group.
all info about commands /should/ go before the commands not whilly
nilly and further more this tidbit makes no sense,  you /must/ be
apart if the xbuilder group but this says you /shoudn't/ do this? (add
yourself to the xbuilder group?), and further more the group should be
in the top with in the info not just say " a special group " and never
tell you till later, so my change makes this  line here obsolete!
_________________________________
proot(1)  IS NOT in the i686 repo to install, I can't speak for other
archs so u can't use proot unless you built it any how. but does proot
need to be in the xbuilder's group? does it need to be chmod as well?
doesn't say...seems suspect to being incomplete documentation
______________________________-
but anyhow
so  much is wrong with this documentation! it needs a rewrite. Besides
knowing to find the kernel config.gz and how to extract it to get
kernel compile options to even know if u have namespaces and
such....just wow...that's not explained only that it is a requierment,
I get this needs to be in a " Doing this on a NON void linux section
or some such "
just WOW
Look i am a human so take this as humanist.

**Comment by Duncaen** [comment]
The use of `/void-packages` is an example, change the path to whatever you prefer? I don't even see where its actually using `/void-packages` as an absolute path.

**Comment by Feay** [comment]
## The XBPS source packages collection
This repository contains the XBPS source packages collection to build
binary packages
for the Void Linux distribution.

The included `xbps-src` script will fetch and compile the sources
using it's own mini Linux environment with compilers facilitated by a
special chroot program to build autonomously. It will install its
files into a `fake destdir` then generate XBPS binary packages into a
'binpkgs' directory that can be later installed or queried through the
`xbps-install` or `xbps-query` utilities, respectively.


###Getting started!
This document is split into three main sections, "Using xbps-src with
Void", "Customization & Deep notes" and "Using xbps-src in a foreign
Linux distribution" -found at the bottom of this document.


##Useing xbps-src with Void
### Requirements:
For native Void:
	- xbps >= 0.46
Depending on your Void's kernel either one of the fallowing:
		- `xbps-uunshare' Part of XBPS (The preferred default)
		- `xbps-uchroot` Part of XBPS
 		- `proot`
NOTE: you don't need to be logged in as `root` to use `xbps-src`
 		-  the group xbuilder must exist, usually it does.


#### Pre-Setup Chroot choices:
`xbps-src` requires a utility to chroot and bind mount existing directories
into a `masterdir` that is used as its main `chroot` directory.
`xbps-src` supports
multiple utilities to accomplish this task. `xbps-src` will look for
XBPS_CHROOT_CMD=<wanted chroot> in the 'conf' file located at /etc/ if
not this is missing `xbps-src` will perfer `xbps-uunshare' (citation
needed).

	- `xbps-uunshare' Part of XBPS a  utility that uses `user_namespaces` or
	- `xbps-uchroot` Part of XBPS a utility that uses `namespaces` that
must be chmod with a `setgid` (see below) or
 	- `proot` - utility that implements chroot/bind mounts in user
space, see https://proot-me.github.io/


#### xbps-uunshare
This is the default chroot program `xbps-src` will use, no other
configuration is necessary (maybe).
Part of XBPS it uses `user_namespaces`. If your system does not
support any of the fallowing required kernel options it will fail with
`EINVAL (Invalid argument)`.

This utility requires these Linux kernel options:
- CONFIG\_NAMESPACES
- CONFIG\_IPC\_NS
- CONFIG\_UTS\_NS
- CONFIG\_USER\_NS


#### xbps-uchroot
Part of XBPS a utility that uses `namespaces` instead of
`user_namespaces`. It also must be chmod with a `setgid` bit. If for
some reason it's erroring out as `ERROR clone (Operation not
permitted)`, check that
your user account is a member of the required `xbuilder` group and
that `xbps-uchroot` utility has the
proper permissions and owner/group as explained below.

This utility requires these Linux kernel options:
- CONFIG\_NAMESPACES
- CONFIG\_IPC\_NS
- CONFIG\_PID\_NS
- CONFIG\_UTS\_NS

Setup for xbps-uchroot:
Your user account and `xbps-uchroot` must be added to a special group
'xbuilder', next the
executable must also be chmod with a `setgid` bit, then finally
xbps-uchroot added to the xbps-src /etc/conf file.
	# usermod -a -G xbuilder <user-account-name>
	# chmod 4750 xbps-uchroot
	# chown root:xbuilder xbps-uchroot

To enable it add " XBPS_CHROOT_CMD=uchroot"  to the file named 'conf' in /etc/:
	$ echo XBPS_CHROOT_CMD=uchroot >> etc/conf
or if this file was not already created
	$echo XBPS_CHROOT_CMD=uchroot > etc/conf


#### proot
The `proot` utility implements chroot and bind mounts support
completely in user space,
and can be used if your Linux kernel does not have support for
namespaces. See https://proot-me.github.io/.
for more information.

To enable it add " XBPS_CHROOT_CMD=proot"  to the file named 'conf' in /etc/:
	$ echo XBPS_CHROOT_CMD=proot >> etc/conf


### Setup on native Void the short version:

We will Clone the `void-packages` git repository, install the
bootstrap packages, build a package, and install it. This is the short
version, please read this whole document and consult the wiki on
voidlinux.com. ((Don't forget xbps-src is a script use ./xbps-src))


	$ cd /
or
	$ ~./
	$ git clone git://github.com/void-linux/void-packages.git
	$ cd /void-packages/
	$ ./xbps-src binary-bootstrap

Please review help with all available targets/options. .
	$ ./xbps-src -h
Let's test make a test! Here we build nano, an editor like vi.
	$ ./xbps-src pkg nano
The output will be a binary package we can install:
	$ cd /void-packages/hostdir/binpkgs/
	$ ls
nano should be a .xbps listed something like nano_1.3.0.xbps
Lastly lets install nano for testing
	xbps-install -R /void-packages/hostdir/binpkgs/ nano
	or
	xbps-install --repository /void-packages/hostdir/binpkgs/ nano
Futher Notes:
Be-aware some quirks with a default xbps-install configuration, if the
package built is a lesser version than the online binary repo it will
download it and this can happen! voidlinux.com has search for both
source and binary online repos, use it.
  Please see how to use xbps-install on the voidlinux.com wiki in
addition to the setup and usage cited below.


##Customization and Deep Notes:

### Install the bootstrap packages

The `bootstrap` packages are a set of packages required to build any
available source package in a container. There are two methods to
install the `bootstrap`:

 - `bootstrap`: all bootstrap packages will be built from scratch;
additional utilities are required in the
host system to allow building the `base-chroot` package: binutils,
gcc, perl, texinfo, etc.

 - `binary-bootstrap`: the bootstrap binary packages are downloaded
via XBPS repositories.

If you don't want to waste your time building everything from scratch
probably it's better to use `binary-bootstrap`.

### Configuration

The `etc/defaults.conf` file contains the possible settings that can
be overridden
through the `etc/conf` configuration file for the `xbps-src` utility;
if that file
does not exist, will try to read configuration settings from `~/.xbps-src.conf`.

If you want to customize default `CFLAGS`, `CXXFLAGS` and `LDFLAGS`,
don't override
those defined in `etc/defaults.conf`, set them on `etc/conf` instead i.e:

    $ echo 'XBPS_CFLAGS="your flags here"' >> etc/conf
    $ echo 'XBPS_LDFLAGS="your flags here"' >> etc/conf

Native and cross compiler/linker flags are set per architecture in
`common/build-profiles`
and `common/cross-profiles` respectively. Ideally those settings are
good enough by default,
and there's no need to set your own unless you know what you are doing.

#### Virtual packages

The `etc/defaults.virtual` file contains the default replacements for
virtual packages,
used as dependencies in the source packages tree.

If you want to customize those replacements, copy
`etc/defaults.virtual` to `etc/virtual`
and edit it accordingly to your needs.

### Directory hierarchy

The following directory hierarchy is used with a default configuration file:

         /void-packages
            |- common
            |- etc
            |- srcpkgs
            |  |- xbps
            |     |- template
            |
            |- hostdir
            |  |- binpkgs ...
            |  |- ccache-<arch> ...
            |  |- distcc-<arch> ...
            |  |- repocache ...
            |  |- sources ...
            |
            |- masterdir
            |  |- builddir -> ...
            |  |- destdir -> ...
            |  |- host -> bind mounted from <hostdir>
            |  |- void-packages -> bind mounted from <void-packages>


The description of these directories is as follows:

 - `masterdir`: master directory to be used as rootfs to build/install packages.
 - `builddir`: to unpack package source tarballs and where packages are built.
 - `destdir`: to install packages, aka **fake destdir**.
 - `hostdir/ccache`: to store ccache data if the `XBPS_CCACHE` option
is enabled.
 - `hostdir/distcc-<arch>`: to store distcc data if the `XBPS_DISTCC`
option is enabled.
 - `hostdir/repocache`: to store binary packages from remote repositories.
 - `hostdir/sources`: to store package sources.
 - `hostdir/binpkgs`: local repository to store generated binary packages.

### Building packages

The simplest form of building package is accomplished by running the
`pkg` target in `xbps-src`:

```
$ cd void-packages
$ ./xbps-src pkg <pkgname>
```

When the package and its required dependencies are built, the binary
packages will be created
and registered in the default local repository at `hostdir/binpkgs`;
the path to this local repository can be added to
any xbps configuration file (see xbps.d(5)) or by explicitly appending
them via cmdline, i.e:
	$ cd /void-packages/
	$ xbps-install --repository=hostdir/binpkgs <package name not file name>
	$ xbps-query --repository=hostdir/binpkgs <package name not file name>


By default **xbps-src** will try to resolve package dependencies in this order:

 - If a dependency exists in the local repository, use it (`hostdir/binpkgs`).
 - If a dependency exists in a remote repository, use it.
 - If a dependency exists in a source package, use it.

It is possible to avoid using remote repositories completely by using
the `-N` flag.

> The default local repository may contain multiple *sub-repositories*: `debug`, `multilib`, etc.

### Package build options

The supported build options for a source package can be shown with
`xbps-src show-options`:

    $ ./xbps-src show-options foo

Build options can be enabled with the `-o` flag of `xbps-src`:

    $ ./xbps-src -o option,option1 pkg foo

Build options can be disabled by prefixing them with `~`:

    $ ./xbps-src -o ~option,~option1 pkg foo

Both ways can be used together to enable and/or disable multiple options
at the same time with `xbps-src`:

    $ ./xbps-src -o option,~option1,~option2 pkg foo

The build options can also be shown for binary packages via `xbps-query`:

    $ xbps-query -R --property=build-options foo

> NOTE: if you build a package with a custom option, and that package is available
in an official void repository, an update will ignore those options.
Put that package
on `hold` mode via `xbps-pkgdb`, i.e `xbps-pkgdb -m hold foo` to ignore updates
with `xbps-install -u`. Once the package is on `hold`, the only way to update it
is by declaring it explicitly: `xbps-install -u foo`.

Permanent global package build options can be set via
`XBPS_PKG_OPTIONS` variable in the
`etc/conf` configuration file. Per package build options can be set via
`XBPS_PKG_OPTIONS_<pkgname>`.

> NOTE: if `pkgname` contains `dashes`, those should be replaced by `underscores`
i.e `XBPS_PKG_OPTIONS_xorg_server=opt`.

The list of supported package build options and its description is
defined in the
`common/options.description` file or in the `template` file.

### Sharing and signing your local repositories

To share a local repository remotely it's mandatory to sign it and the
binary packages
stored on it. This is accomplished with the `xbps-rindex` utility.

First a RSA key must be created with `openssl` or `ssh-keygen`:

	$ openssl genrsa -des3 -out privkey.pem 4096

or

	$ ssh-keygen -t rsa -b 4096 -m PEM -f privkey.pem

> Only RSA keys in PEM format are currently accepted by xbps.

Once the RSA private key is ready you can use it to initialize the
repository metadata:

	$ xbps-rindex --sign --signedby "I'm Groot" --privkey privkey.pem
$PWD/hostdir/binpkgs

And then make a signature per package:

	$ xbps-rindex --sign-pkg --privkey privkey.pem $PWD/hostdir/binpkgs/*.xbps

> If --privkey is unset, it defaults to `~/.ssh/id_rsa`.

If the RSA key was protected with a passphrase you'll have to type it,
or alternatively set
it via the `XBPS_PASSPHRASE` environment variable.

Once the binary packages have been signed, check the repository
contains the appropriate `hex fingerprint`:

	$ xbps-query --repository=hostdir/binpkgs -vL
	...

Each time a binary package is created, a package signature must be
created with `--sign-pkg`.

> It is not possible to sign a repository with multiple RSA keys.

### Rebuilding and overwriting existing local packages

If for whatever reason a package has been built and it is available in
your local repository
and you have to rebuild it without bumping its `version` or `revision`
fields, it is possible
to accomplish this task easily with `xbps-src`:

    $ ./xbps-src -f pkg xbps

Reinstalling this package in your target `rootdir` can be easily done too:

    $ xbps-install --repository=/path/to/local/repo -yff xbps-0.25_1

> Please note that the `package expression` must be properly defined to explicitly pick up
the package from the desired repository.

### Enabling distcc for distributed compilation

Setup the slaves (machines that will compile the code):

    # xbps-install -Sy distcc

Modify the configuration to allow your local network machines to use
distcc (e.g. `192.168.2.0/24`):

    # echo "192.168.2.0/24" >> /etc/distcc/clients.allow

Enable and start the `distccd` service:

    # ln -s /etc/sv/distccd /var/service

Install distcc on the host (machine that executes xbps-src) as well.
Unless you want to use the host as slave from other machines, there is no need
to modify the configuration.

On the host you can now enable distcc in the `void-packages/etc/conf` file:

    XBPS_DISTCC=yes
    XBPS_DISTCC_HOSTS="localhost/2 --localslots_cpp=24 192.168.2.101/9
192.168.2.102/2"
    XBPS_MAKEJOBS=16

The example values assume a localhost CPU with 4 cores of which at
most 2 are used for compiler jobs.
The number of slots for preprocessor jobs is set to 24 in order to
have enough preprocessed data for other CPUs to compile.
The slave 192.168.2.101 has a CPU with 8 cores and the /9 for the
number of jobs is a saturating choice.
The slave 192.168.2.102 is set to run at most 2 compile jobs to keep
its load low, even if its CPU has 4 cores.
The XBPS_MAKEJOBS setting is increased to 16 to account for the
possible parallelism (2 + 9 + 2 + some slack).

### Distfiles mirror(s)

In etc/conf you may optionally define a mirror or a list of mirrors to
search for distfiles.

    $ echo 'XBPS_DISTFILES_MIRROR="ftp://192.168.100.5/gentoo/distfiles"'
>> etc/conf

If more than one mirror is to be searched, you can either specify
multiple URLs separated
with blanks, or add to the variable like this

    $ echo 'XBPS_DISTFILES_MIRROR+="
http://repo.voidlinux.de/distfiles"' >> etc/conf

Make sure to put the blank after the first double quote in this case.

The mirrors are searched in order for the distfiles to build a package until the
checksum of the downloaded file matches the one specified in the template.

Ultimately, if no mirror carries the distfile, or in case all
downloads failed the
checksum verification, the original download location is used.

If you use `proot` or `uchroot` for your XBPS_CHROOT_CMD, you may also
specify a local path
using the `file://` prefix or simply an absolute path on your build
host (e.g. /mnt/distfiles).
Mirror locations specified this way are bind mounted inside the chroot
environment
under $XBPS_MASTERDIR and searched for distfiles just the same as
remote locations.

### Cross compiling packages for a target architecture

Currently `xbps-src` can cross build packages for some target
architectures with a cross compiler.
The supported target is shown with `./xbps-src -h`.

If a source package has been adapted to be **cross buildable**
`xbps-src` will automatically build the binary package(s) with a
simple command:

    $ ./xbps-src -a <target> pkg <pkgname>

If the build for whatever reason fails, might be a new build issue or
simply because it hasn't been adapted to be **cross compiled**.


### Remaking the masterdir

If for some reason you must update xbps-src and the `bootstrap-update`
target is not enough, it's possible to recreate a masterdir with two
simple commands (please note that `zap` keeps your
`ccache/distcc/host` directories intact):

    $ ./xbps-src zap
    $ ./xbps-src binary-bootstrap

### Keeping your masterdir uptodate

Sometimes the bootstrap packages must be updated to the latest
available version in repositories, this is accomplished with the
`bootstrap-update` target:

    $ ./xbps-src bootstrap-update

### Building 32bit packages on x86_64

Two ways are available to build 32bit packages on x86\_64:

 - cross compilation mode
 - native mode with a 32bit masterdir

The first mode (cross compilation) is as easy as:

    $ ./xbps-src -a i686 pkg ...

The second mode (native) needs a new x86 `masterdir`:

    $ ./xbps-src -m masterdir-x86 binary-bootstrap i686
    $ ./xbps-src -m masterdir-x86 ...

### Building packages natively for the musl C library

A native build environment is required to be able to cross compile the
bootstrap packages for the musl C library; this is accomplished by
installing them via `binary-bootstrap`:

    $ ./xbps-src binary-bootstrap

Now cross compile `base-chroot-musl` for your native architecture:

    $ ./xbps-src -a x86_64-musl pkg base-chroot-musl

Wait until all packages are built and when ready, prepare a new
masterdir with the musl packages:

    $ ./xbps-src -m masterdir-x86_64-musl binary-bootstrap x86_64-musl

Your new masterdir is now ready to build packages natively for the
musl C library. Try:

    $ ./xbps-src -m masterdir-x86_64-musl chroot
    $ ldd

To see if the musl C dynamic linker is working as expected.

### Building void base-system from scratch

To rebuild all packages in `base-system` for your native architecture:

    $ ./xbps-src -N pkg base-system

It's also possible to cross compile everything from scratch:

    $ ./xbps-src -a <target> -N pkg base-system

Once the build has finished, you can specify the path to the local
repository to `void-mklive`, i.e:

    # cd void-mklive
    # make
    # ./mklive.sh ... -r /path/to/hostdir/binpkgs

## Using xbps-src in a foreign Linux distribution
See the above for details about many of these steps and more!
###Requierments:
Using xbps-src in a foreign Linux distribution:
	- GNU bash
	- xbps >= 0.46
	- git
	- wget
	- xbps's depends not discussed please see (citataion to be added)
Depending on your kernel's namespaces support either one of the fallowing:
		- `xbps-uunshare' Part of XBPS (The preferred default)
		- `xbps-uchroot` Part of XBPS
 		- `proot`

NOTE: you don't need to be logged in as `root` to use `xbps-src`.

xbps-src can be used in any recent Linux distribution matching the CPU
architecture.

To use xbps-src in your Linux distribution use the following
instructions. Let's start downloading the xbps static binaries:

    $ wget http://alpha.de.repo.voidlinux.org/static/xbps-static-latest.<arch>-musl.tar.xz
    $ mkdir ~/XBPS
    $ tar xvf xbps-static-latest.<arch>.tar.xz -C ~/XBPS
    $ export PATH=~/XBPS/usr/bin:$PATH

If your system does not support `user namespaces`, a privileged group
is required to be able to use
`xbps-uchroot` with xbps-src, by default it's set to the `xbuilder`
group, change this to your desired group(also see section Pre-Setup
Chroot choices):

    # chown root:<group> ~/XBPS/usr/bin/xbps-uchroot.static
    # chmod 4750 ~/XBPS/usr/bin/xbps-uchroot.static

Clone the `void-packages` git repository:

    $ git clone git://github.com/void-linux/void-packages

and `xbps-src` should be fully functional; just start the `bootstrap`
process, i.e:

    $ ./xbps-src binary-bootstrap

The default masterdir is created in the current working directory, i.e
`void-packages/masterdir`.

See the rest of this document.
### Contributing

See [Contributing](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md)
for a general overview of how to contribute and the
[Manual](https://github.com/void-linux/void-packages/blob/master/Manual.md)
for details of how to create source packages.

**Comment by Feay** [comment]
Duncan Overbruck
the current readme says:
Clone the void-packages git repository, install the bootstrap packages:

$ git clone git://github.com/void-linux/void-packages.git
$ cd void-packages
$ ./xbps-src binary-bootstrap

you did not read it.
No indication if it cares where it is, but from experience with
failure I know it does!
I am unsure about homefolder but in /  it works as intended, in
/anyotherfolder/ it does not
bootstrap binaries will install fine yes but when u try to build a
package it it failed for me.
so whatever it its perhaps factors beyond you or I but that is what
has happened. An
educated guess is one must git clone on / remember for linux / is a
folder a location.
But surely you all know these things! You're the git people who make commits!
