### ISSUE TITLE
Package request: NvChad

### ISSUE THREAD

**Issue by jaminW55** [void-linux/void-packages#48296]
### Package name

NvChad

### Package homepage

https://github.com/NvChad/NvChad

### Description

Neovim config written in Lua with a beautiful UI and fast startup

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by jaminW55** [comment]
I've actually almost got this one working. It builds without error, but then does not install. I am not entirely certain where I went wrong and I wonder if maybe I need to include something that changes terminal fonts to nerd fonts. Please see the below template:

```
# Template file for 'nvchad'
pkgname=nvchad
version=2.0
revision=1
build_style=fetch
depends="neovim>=0.9.4 xclip"
hostmakedepends="tar"
short_desc="Neovim config written in Lua with a beautiful UI and fast startup"
maintainer="jaminW55 <jaminW55@gmail.me>"
license="GPL-3.0"
homepage="https://github.com/NvChad/NvChad"
distfiles="https://github.com/NvChad/NvChad/archive/refs/tags/v${version}.tar.gz"
checksum=78334f0bd8ec196a827c14ba9e33d2266833249a1916319d60c2ba7e20d6fba7

do_install() {
    # Force extraction of tarball
    tar -xzf "v${version}.tar.gz" -C "${wrksrc}"

    # Navigate to the directory where the source files are extracted
    cd "${wrksrc}/NvChad-${version}"

    # Create Necessary Directories
    vmkdir /usr/share/nvim/runtime
    vmkdir /usr/share/nvchad

    # Copying necessary files
    vcopy init.lua /usr/share/nvchad
    vcopy lua /usr/share/nvchad
    vcopy .stylua.toml /usr/share/nvchad

    # Copy the same files to nvim runtime directory
    vcopy init.lua /usr/share/nvim/runtime
    vcopy lua /usr/share/nvim/runtime
    vcopy .stylua.toml /usr/share/nvim/runtime
}

post_install() {
    echo "To update NvChad, run 'NvChadUpdate' inside neovim."
}
```

**Comment by classabbyamp** [comment]
> Does the requested package meet the package requirements?
> System, Compiled

this is just a set of neovim configs. it does not (and probably *should* not) be installed system-wide for most use-cases, and it is not compiled (it's lua).

you should just [install it like upstream says to](https://nvchad.com/docs/quickstart/install).

**Comment by jaminW55** [comment]
Both Arch and NixOS have this packaged, so I assumed it may be cleaner to set-up via package.

**Comment by classabbyamp** [comment]
the AUR is not arch, it's a free-for-all where anyone can make a package for whatever they want

nix packages many things because they can be hard to install with the way nix is structured
