### ISSUE TITLE
`rust-1.75.02` for `armv7l` and `armv6l-musl` is not found in the default repo

### ISSUE THREAD

**Issue by chrysos349** [void-linux/void-packages#48298]
For some reason `rust-1.75.02` for `armv7l` and `armv6l-musl` wasn't built and is not present in the default repo.

that's why all current prs dependent on it have to build it for `armv7l` and `armv6l-musl` from scratch every time.

**Comment by icp1994** [comment]
Yeah noticed that too in CI. Rust gets built in those arches whenever a cargo project is pushed. I think those repos are [stuck](grafana.voidlinux.org/d/5w8Ft0UGk)

**Comment by classabbyamp** [comment]
repo is staging, should be getting resolved now
