### ISSUE TITLE
Icedtea Web using incorrect path to Java JRE

### ISSUE THREAD

**Issue by CtrlC-Root** [void-linux/void-packages#48328]
### Is this a new report?

Yes

### System Info

Void 6.6.11_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFF

### Package(s) Affected

icedtea-web-1.6.2_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No but previous instance of this bug (which was fixed and is now happening again) reported here:
https://github.com/void-linux/void-packages/issues/16835

### Expected behaviour

Launching a JNLP file with `icedtea-web` package `javaws` script correctly starts the Java application with the currently installed JRE.

### Actual behaviour

The `javaws` script uses a hard-coded path to an out of date JRE which is not available via any current packages so it fails to start the application:

```
alex@tartarus ~/downloads [1]> javaws launch.jnlp
/usr/bin/javaws: line 98: /usr/lib/jvm/java-1.8-openjdk/jre/bin/java: No such file or directory
```

Currently installed Java packages:

```
alex@tartarus ~/downloads [127]> xbps-query -s jdk
[*] openjdk-8u999_1           OpenJDK Java Development Kit (meta)
[*] openjdk-common-2_1        Common files for OpenJDK packages
[*] openjdk17-17.0.10+6_1     OpenJDK Java Development Kit (version 17)
[*] openjdk17-jre-17.0.10+6_1 OpenJDK Java Development Kit (version 17) - runtime components
[*] openjdk8-8u332b05_2       OpenJDK Java Development Kit (version 8)
[*] openjdk8-jre-8u332b05_2   OpenJDK Java Development Kit (version 8) - runtime components
alex@tartarus ~/downloads> xbps-query -s icedtea
[*] icedtea-web-1.6.2_2 Implementation of Java Web Start
```

I'm guessing that script needs to be updated to rely on the alternatives system in order to pick the currently selected JRE binary? Tagging @felix as the package maintainer.

### Steps to reproduce

1. Install the `icedtea-web` package.
2. Locate a JNLP file to test with. A public one is available here: https://cherry.dcs.aber.ac.uk/3dexperiment/launch.html
3. Download the JNLP file.
4. Attempt to run the JNLP file: `javaws launch.jnlp`
5. Observe the issue from the `Actual behaviour` section above.

**Comment by felix** [comment]
Thank you @classabbyamp, I have not used this port for some time.
