### ISSUE TITLE
xbps-src pkg -o ~ broken on zsh?

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#48325]
### Is this a new report?

Yes

### System Info

Void 6.7.1_1 x86_64 GenuineIntel uptodate rFFFFFFFFFFFF

### Package(s) Affected

xbps-src

### Expected behaviour

works fine on e.g. bash

### Actual behaviour

```
$ ./xbps-src -o ~xwayland pkg river 
zsh: no such user or named directory: xwayland
```

### Steps to reproduce

can anyone else reproduce?

**Comment by classabbyamp** [comment]
just quote it

**Comment by classabbyamp** [comment]
fwiw it works fine on zsh for me
