### ISSUE TITLE
What to do if a package version uses a different format than "x.x.x"?

### ISSUE THREAD

**Issue by zDylant** [void-linux/void-packages#48334]
Hello, i'm currently packaging [neko](https://github.com/HaxeFoundation/neko/) but this package dist files use dashes instead of dots: 
`https://github.com/HaxeFoundation/neko/archive/refs/tags/v2-3-0.tar.gz`

Since `version` doesn't allow dashes, i'm using the following workaround, but i want to know if this is allowed or if there is a better way to do it.

```
version="2.3.0"
distfiles="https://github.com/HaxeFoundation/neko/archive/refs/tags/v${version//./-}.tar.gz"
```

**Comment by classabbyamp** [comment]
yes, that's the way to do it
