### ISSUE TITLE
LuaJIT will fail to build in the future

### ISSUE THREAD

**Issue by rfl890** [void-linux/void-packages#48349]
The creator of LuaJIT, Mike Pall, strongly recommends to use rolling releases for LuaJIT instead of the release tarballs that he provides (not for much longer, apparently):
(https://luajit.org/download.html)

> LuaJIT uses rolling releases. There are no release tarballs available for download.
> Please do not use obsolete versions from older tarballs or zip files. Please remove any outdated links to these downloads — **these links will cease to work soon**. 

Currently the LuaJIT package uses one of these outdated links. It will fail to build in the future. Additionally, the version currently in use hasn't been updated for 6 years.

**Comment by classabbyamp** [comment]
we have distfile mirrors at sources.voidlinux.org

**Comment by rfl890** [comment]
I see. On another note will the package be updated to rolling releases or will it continue to stay on the current version?

**Comment by classabbyamp** [comment]
my understanding is the tags like 2.1.ROLLING will be periodically re-tagged as a "rolling" release

**Comment by yoshiyoshyosh** [comment]
I guess if retags do happen then we can just revbump and have it still work
