### ISSUE TITLE
Exec format failure even when using build_helper=qemu?

### ISSUE THREAD

**Issue by zDylant** [void-linux/void-packages#48348]
Hello, while i was cross-compiling [neko](https://github.com/HaxeFoundation/neko/) for aarch64 i found out that the package wouldn't build because of the following error:

```
FAILED: bin/test.n /builddir/neko-2.3.0/build/bin/test.n
cd /builddir/neko-2.3.0/src && LD_LIBRARY_PATH=/builddir/neko-2.3.0/build/bin NEKOPATH=/builddir/neko-2.3.0/build/bin /builddir/neko-2.3.0/build/bin/neko /builddir/neko-2.3.0/build/bin/nekoc.n
tools/test.neko && /usr/libexec/xbps-src/bin/cmake -E copy tools/test.n /builddir/neko-2.3.0/build/bin && /usr/libexec/xbps-src/bin/cmake -E remove tools/test.n
/bin/sh: line 1: /builddir/neko-2.3.0/build/bin/neko: cannot execute binary file: Exec format error
```

From what i know, `Exec format error` means that you are trying to run a binary on the wrong architecture, so my guess was that while cross-building, the package tried to run the output aarch64 binary on x86_64.
With this in mind i tried adding `build_helper="qemu"` to my template, since as the manual says _"sets additional variables for the cmake and meson build styles to allow executing cross-compiled binaries inside qemu."_ but this didn't change anything and i still get the same `Exec format error.`

If it helps somehow, this is the output of using `file` on the binary:
`masterdir/builddir/neko-2.3.0/build/bin/neko: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=0a0af44a623fcda62165dafa047cb407d167f28f, for GNU/Linux 3.7.0, not stripped`

**Comment by sgn** [comment]
You may want to read the commit message of https://github.com/chewing/libchewing/commit/7d8ee49f232fd95776bfe80768467ce62c9253cd

```
In order to do that, the command must start with
a target built by CMake.
```

IOW, this is broken https://github.com/HaxeFoundation/neko/blob/c852db0004dafb21515b51ef0c79fd927a74b005/CMakeLists.txt#L437
