### ISSUE TITLE
Package request: swayr

### ISSUE THREAD

**Issue by witseid** [void-linux/void-packages#48414]
### Package name

swayr

### Package homepage

https://git.sr.ht/~tsdh/swayr

### Description

Swayr is a window switcher (and more) for sway

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by agilexue** [comment]
Hi. This utility greatly improves the experience of using sway. I would be very grateful if it could be found in the repositories.
