### ISSUE TITLE
valgrind: feature request: do not strip symbols

### ISSUE THREAD

**Issue by sbromberger** [void-linux/void-packages#48427]
`valgrind-3.22.0_1` is installed with debug symbols stripped. This makes it impossible to submit bug reports to the valgrind team when it errors. Since valgrind handles its own errors, and having the symbols is a prerequisite for filing an issue with the upstream team, this means that a custom non-stripped binary needs to be built and used for opening up upstream issues.

(Simply using the `valgrind-dbg` package doesn't appear to work.)

Could this package be installed without stripping the debug symbols?

**Comment by classabbyamp** [comment]
based on https://valgrind.org/docs/manual/dist.readme-packagers.html should probably be `nostrip=yes`
