### ISSUE TITLE
Package request: Niri

### ISSUE THREAD

**Issue by Jipok** [void-linux/void-packages#48456]
### Package name

niri

### Package homepage

https://github.com/YaLTeR/niri

### Description

Very cool window manager concept. If you add such binds:
```
    Mod+A     { focus-column-left; }
    Mod+S     { focus-window-or-workspace-down; }
    Mod+W     { focus-window-or-workspace-up; }
    Mod+D     { focus-column-right; }
```
then moving through windows and workspaces can be represented as moving along a grid using WASD (as in games). Which is very convenient and the animation makes everything amazing.
However, the authors' attitude towards X11(`X11 is very cursed`) and the lack of [Xwayland](https://github.com/YaLTeR/niri/wiki/Xwayland) support makes it unsuitable for my use.
Despite the fact that the readme clearly mentions a systemd dependency, I was able to build and run it under void without any problems. For those interested, I will leave my template here:
```
# Template file for 'niri'
pkgname=niri
version=0.1.0
revision=1
#archs="i686 x86_64"
build_style=cargo
hostmakedepends="pkg-config"
makedepends="eudev-libudev-devel libxkbcommon-devel libinput-devel pipewire-devel pango-devel libseat-devel clang libgbm-devel"
depends="eudev-libudev libxkbcommon libinput libpipewire pango libseat libgbm"
short_desc="scrollable-tiling Wayland compositor"
maintainer="Jipok <void@jipok.ru>"
license="GPL-3.0-or-later"
homepage="https://github.com/YaLTeR/niri"
changelog="https://github.com/YaLTeR/niri/releases"
distfiles="https://github.com/YaLTeR/niri/archive/refs/tags/v${version}.tar.gz"
checksum=b26d39e6855de6de581b253d06cbaa375709b00a276626326b745e0d10b0ac70

post_install() {
        vmkdir etc/niri
        vcopy resources/default-config.kdl etc/niri/config.kdl
}
```

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by Eloitor** [comment]
Wow! I wanted something like this for ages!

Nextcloud did not work for me. I solved it by running 

```
#! /usr/bin/sh
export XDG_CURRENT_DESKTOP=niri

# Ensure the session type is set to Wayland for xdg-autostart apps.
export XDG_SESSION_TYPE=wayland

dbus-run-session niri
```
to start niri.

**Comment by Eloitor** [comment]
I did not figure out how to get screenshots working... 

From the default configuration file:
```
// The path is formatted with strftime(3) to give you the screenshot date and time.
```

Maybe there is some missing dependency in the template, but I don't know which...

**Comment by lidgnulinux** [comment]
Do you use musl or glibc ? @Jipok

**Comment by Jipok** [comment]
glibc

**Comment by YaLTeR** [comment]
Hi! Does this help running without systemd? https://github.com/YaLTeR/niri/pull/217

**Comment by Eloitor** [comment]
Nice, I think so. I can package it one this is merged :)

**Comment by Eloitor** [comment]
I just tried it, this time nextcloud worked without any manual adjustment. Great job, thanks!

**Comment by jrvieira** [comment]
i get no apparent problems with `dbus-run-session niri` but I need to `export $(dbus-launch)` before running `niri --session` or else, although by the logs everything seems to be working correctly, i get no graphical output

**Comment by classabbyamp** [comment]
please don't necro-bump issues. make a separate issue or discussion.
