### ISSUE TITLE
Package request: gamescope

### ISSUE THREAD

**Issue by jaminW55** [void-linux/void-packages#48451]
### Package name

gamescope

### Package homepage

https://github.com/ValveSoftware/gamescope

### Description

In an embedded session usecase, gamescope does the same thing as steamcompmgr, but with less extra copies and latency:

    It's getting game frames through Wayland by way of Xwayland, so there's no copy within X itself before it gets the frame.
    It can use DRM/KMS to directly flip game frames to the screen, even when stretching or when notifications are up, removing another copy.
    When it does need to composite with the GPU, it does so with async Vulkan compute, meaning you get to see your frame quick even if the game already has the GPU busy with the next frame.

It also runs on top of a regular desktop, the 'nested' usecase steamcompmgr didn't support.

    Because the game is running in its own personal Xwayland sandbox desktop, it can't interfere with your desktop and your desktop can't interfere with it.
    You can spoof a virtual screen with a desired resolution and refresh rate as the only thing the game sees, and control/resize the output as needed. This can be useful in exotic display configurations like ultrawide or multi-monitor setups that involve rotation.

It runs on Mesa + AMD or Intel, and could be made to run on other Mesa/DRM drivers with minimal work. AMD requires Mesa 20.3+, Intel requires Mesa 21.2+. For NVIDIA's proprietary driver, version 515.43.04+ is required (make sure the nvidia-drm.modeset=1 kernel parameter is set).

If running RadeonSI clients with older cards (GFX8 and below), currently have to set R600_DEBUG=nodcc, or corruption will be observed until the stack picks up DRM modifiers support.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by jaminW55** [comment]
I may start working on this soon, but I'd like to use those program to run certain programs in isolation from my main system; or games with HDR on an X11 session.

**Comment by chrysos349** [comment]
#48354

**Comment by jaminW55** [comment]
> #48354

Neglected to check this time!
