### ISSUE TITLE
All PHP versions with imagick enabled (`extension=imagick`) segfault

### ISSUE THREAD

**Issue by TinfoilSubmarine** [void-linux/void-packages#48500]
### Is this a new report?

Yes

### System Info

Void 6.6.11_1 x86_64 AuthenticAMD uptodate rrmFFFFFFFFFFFFFFFFFFF

### Package(s) Affected

php8.1-imagick-3.7.0_9, php8.2-imagick-3.7.0_9, php8.3-imagick-3.7.0_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/Imagick/imagick/issues/609
https://github.com/Imagick/imagick/issues/636

### Expected behaviour

Using the PHP executable should suceed.

### Actual behaviour

Segfaults immediately no matter what:
```
$ php -a                                                                                             
zsh: segmentation fault  php -a
$ php                                                                                            
zsh: segmentation fault  php
$ php --version                                                                                  
zsh: segmentation fault  php --version                                                                                       
```

### Steps to reproduce

1. Install any php version available in void-packages as well as the relevant imagick (e.g. `xi php8.3-imagick`).
2. Enable imagick in php.ini: `extension=imagick`.
3. Run the `php` executable with any arguments.

**Comment by TinfoilSubmarine** [comment]
As mentioned in [this thread](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109634#c4), these are some options:

> libgomp can be only dlopened in threaded apps if there is still space in the static TLS surplus, which unfortunately some versions of glibc use even for normal TLS rather than just static TLS.
> So, LD_PRELOAD=libgomp.so.1, or link the program with libgomp.so.1 rather than just its libraries, or dlopen it before spawning threads.
> This is how glibc behaves, and unless we want to slow down libgomp extremely, there is nothing that can be done about it on the GCC side.

**Comment by TinfoilSubmarine** [comment]
I also should note that this only started occurring with the update to `libgomp-13.2.0_1`.

**Comment by classabbyamp** [comment]
maybe it needs a rebuild for the new libgomp?

**Comment by TinfoilSubmarine** [comment]
Already tried

**Comment by sgn** [comment]
We may link php to libgomp instead?

**Comment by oreo639** [comment]
The crash occurs in `initialize_env()`  on the following line: https://github.com/gcc-mirror/gcc/blob/releases/gcc-13.2.0/libgomp/env.c#L2062

Importing 15345980633c502f0486a2e40e96224f49134130 in to libgomp does appear to fix the issue for me (adds an if statement before de-referencing).

**Comment by oreo639** [comment]
@TinfoilSubmarine When you are avaliable, can you update and verify that libgomp-13.2.0_2 works for you?

**Comment by TinfoilSubmarine** [comment]
Yep, fixed for me
