### ISSUE TITLE
Old kernel versions not removed properly

### ISSUE THREAD

**Issue by joshuakraemer** [void-linux/void-packages#48511]
### Is this a new report?

Yes

### System Info

Void 6.5.5_2 x86_64 GenuineIntel uptodate rrrrmmnFFFFFFFFFFFFF

### Package(s) Affected

xbps-0.59.2_2

### Expected behaviour

Before each system update, I check for installed kernels with `xbps-query --regex -s '^linux[0-9.]+-[0-9._]+'`, remove old kernel packages with `xbps-remove -Rf linuxX.X` and remove old kernels with `vkpurge rm all`. I expect all old kernels to be removed completely by those commands, including the corresponding header packages.

### Actual behaviour

Despite the procedure described above, old kernels don't seem to be removed properly. After an update carried out today, there are still multiple old header packages installed:
```
% xbps-query --regex -s '^linux[0-9]'
[*] linux6.0-headers-6.0.19_1 Linux kernel and modules (6.0 series) - source headers for 3rd party modules
[*] linux6.1-headers-6.1.71_1 Linux kernel and modules (6.1 series) - source headers for 3rd party modules
[*] linux6.3-headers-6.3.13_2 Linux kernel and modules (6.3 series) - source headers for 3rd party modules
[*] linux6.5-6.5.13_1         Linux kernel and modules (6.5 series)
[*] linux6.5-headers-6.5.13_1 Linux kernel and modules (6.5 series) - source headers for 3rd party modules
[*] linux6.6-6.6.11_1         Linux kernel and modules (6.6 series)
[*] linux6.6-headers-6.6.11_1 Linux kernel and modules (6.6 series) - source headers for 3rd party modules
```

During the update, DKMS modules for 9 kernels have been built (those even include kernel versions for which no headers are installed):
```
nvidia-dkms-535.154.05_1: configuring ...
Added DKMS module 'nvidia-535.154.05'.
Skipping kernel-5.13.19_1. kernel-headers package not installed...
Building DKMS module 'nvidia-535.154.05' for kernel-5.15.60_1... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-5.15.60_1... done.
Skipping kernel-5.19.17_1. kernel-headers package not installed...
Building DKMS module 'nvidia-535.154.05' for kernel-6.0.19_1... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-6.0.19_1... done.
Building DKMS module 'nvidia-535.154.05' for kernel-6.1.46_1... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-6.1.46_1... done.
Building DKMS module 'nvidia-535.154.05' for kernel-6.1.55_2... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-6.1.55_2... done.
Building DKMS module 'nvidia-535.154.05' for kernel-6.1.71_1... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-6.1.71_1... done.
Building DKMS module 'nvidia-535.154.05' for kernel-6.3.13_2... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-6.3.13_2... done.
Building DKMS module 'nvidia-535.154.05' for kernel-6.5.13_1... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-6.5.13_1... done.
Building DKMS module 'nvidia-535.154.05' for kernel-6.5.5_2... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-6.5.5_2... done.
Building DKMS module 'nvidia-535.154.05' for kernel-6.6.11_1... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-6.6.11_1... done.
```

Files in /boot/:
```
config-6.5.13_1
config-6.5.5_2
config-6.6.11_1
efi
grub
initramfs-5.15.60_1.img
initramfs-6.0.19_1.img
initramfs-6.1.46_1.img
initramfs-6.1.55_2.img
initramfs-6.1.71_1.img
initramfs-6.3.13_2.img
initramfs-6.5.13_1.img
initramfs-6.5.5_2.img
initramfs-6.6.11_1.img
vmlinuz-6.5.13_1
vmlinuz-6.5.5_2
vmlinuz-6.6.11_1
```

### Steps to reproduce

1. Check for installed kernels with `xbps-query --regex -s '^linux[0-9.]+-[0-9._]+'`
2. Remove all old kernel packages with `xbps-remove -Rf linuxX.X`
3. Remove all old kernels with `vkpurge rm all`
4. Update system with `xbps-install -Su`
5. Check for old header packages with `xbps-query --regex -s '^linux[0-9.]+-headers'`
6. Check for old kernel files in /boot/

**Comment by Chocimier** [comment]
`vkpurge` removes leftover files, not packages.
`linuxX.X-headers` is separate package, do you run `xbps-remove -o`?
If it still not removed, what keeps it in place - `xbps-query -X linuxX.X-headers`?

**Comment by joshuakraemer** [comment]
@Chocimier, thanks for your comment. I didn't run `xbps-remove -o` (expecting `xbps-remove -Rf` to be sufficient). After running `xbps-remove -o`, the header packages are removed indeed. Afterwards, I've run `vkpurge rm all` again. I now have only the following linux packages installed:
```
% xbps-query --regex -s '^linux[0-9.]+'
[*] linux6.6-6.6.11_1         Linux kernel and modules (6.6 series)
[*] linux6.6-headers-6.6.11_1 Linux kernel and modules (6.6 series) - source headers for 3rd party modules
```

However, if I reconfigure the nvidia package, it still builds 4 DKMS modules:
```
% sudo xbps-reconfigure -f nvidia-dkms
nvidia-dkms: configuring ...
DKMS module 'nvidia-535.154.05' already added, skipping.
Skipping kernel-5.13.19_1. kernel-headers package not installed...
Building DKMS module 'nvidia-535.154.05' for kernel-5.15.60_1... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-5.15.60_1... done.
Skipping kernel-5.19.17_1. kernel-headers package not installed...
Skipping kernel-6.0.19_1. kernel-headers package not installed...
Building DKMS module 'nvidia-535.154.05' for kernel-6.1.46_1... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-6.1.46_1... done.
Building DKMS module 'nvidia-535.154.05' for kernel-6.1.55_2... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-6.1.55_2... done.
Skipping kernel-6.1.71_1. kernel-headers package not installed...
Skipping kernel-6.3.13_2. kernel-headers package not installed...
Skipping kernel-6.5.13_1. kernel-headers package not installed...
Building DKMS module 'nvidia-535.154.05' for kernel-6.6.11_1... done.
Installing DKMS module 'nvidia-535.154.05' for kernel-6.6.11_1... done.
```

There are still 7 initramfs images in /boot:
```
# ls /boot/
config-6.6.11_1
efi
grub
initramfs-5.15.60_1.img
initramfs-6.0.19_1.img
initramfs-6.1.46_1.img
initramfs-6.1.55_2.img
initramfs-6.1.71_1.img
initramfs-6.3.13_2.img
initramfs-6.6.11_1.img
vmlinuz-6.6.11_1
```

**Comment by ahesford** [comment]
Your removal process eliminated various kernels but left their headers installed. As you subsequently upgrade the system and, along with it, various header packages, you leave behind the old headers (by design---that's why vkpurge exists). However, vkpurge looks for actual kernels to identify candidates for removal. Because you've already eliminated the kernels, vkpurge never considers the stray headers for removal.

The fix here is to manually remove these left-behind kernel headers, maybe clean up your DKMS installation, throw away the useless initramfs images and, in the future, remember that any removal of the kernel package should be paired with removal of the corresponding header package.

**Comment by joshuakraemer** [comment]
Thanks, I've manually removed all stray files from /usr/src, /lib/modules and /boot, which has solved the problem for now.
