### ISSUE TITLE
Platform request: ClockworkPI uConsole

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#48533]
It would be nice to have VoidLinux packaged for 

https://www.clockworkpi.com/product-page/uconsole-kit-rpi-cm4-lite

I am planning to get one, I however may most probably need help packaging Void Linux for it.

**Comment by classabbyamp** [comment]
void already supports raspberry pis and should work on a CM4, so it might just be a matter of a different device tree or device tree overlay for the hardware

**Comment by Anachron** [comment]
Probably, we need some drivers and configs from

https://github.com/clockworkpi/uConsole

**Comment by Anachron** [comment]
Closing this for now AS I decided a 20$ Bluetooth keyboard and a tablet/phone stand is both more cheaper and practical to use/carry.

**Comment by bsdelf** [comment]
@Anachron I have successfully built the kernel for uconsole in a void linux way, and created an SD card image. All uconsole hardwares work out of box. I don't have time to cleanup the scripts and write a post to introduce my work yet, if you want to try it out, please refer to my repository together with the official void documentations:
- https://github.com/bsdelf/void-packages/commit/b81757874cbfce90ae331831dd2dc7def5a34a80
- https://docs.voidlinux.org/installation/guides/arm-devices/index.html
- https://docs.voidlinux.org/installation/guides/chroot.html
