### ISSUE TITLE
Amdgpu issues

### ISSUE THREAD

**Issue by ailen-cmd** [void-linux/void-packages#48579]
After a fresh installation I get:

```
amdgpu: Secure display: Generic Failure.
amdgpu: SECUREDISPLAY: query securedisplay TA failed. ret 0x0
```
I tried all kernels from 5.15 to mainline

**Comment by Anachron** [comment]
This is missing almost every information that could be helpful.

Please tell us about your stack. Which display manager, which packages did you install, what errors does dmesg print, where/when did you get these errors, which Hardware are you using, which Installation Method did you use, etc.

**Comment by ailen-cmd** [comment]
> This is missing almost every information that could be helpful.

Yeah. I noticed that the Void Linux version, which is located in the iso, does not have this error. I installed the base image via the voidinstaller script, choosing the local installation method. This error occurred after updating all the packages and I suspect “linux-firmware-amd”. Also, after the update, the GUI does not open at all so I can only use tty. Also after installing the latest kernel, there's only a black screen after booting .
Cpu: Ryzen 5 3500u
Gpu: amd vega 8

**Comment by abhocetabhac** [comment]
Looks like it is a bug: "https://bbs.archlinux.org/viewtopic.php?id=290707&p=3" and "https://gitlab.freedesktop.org/drm/amd/-/issues/3062".

Maintainers, please, update package linux-firmware version 20240220. ("https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tag/?h=20240220")

**Comment by classabbyamp** [comment]
please [test](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#testing-pull-requests): https://github.com/void-linux/void-packages/pull/49256
