### ISSUE TITLE
Guile (2.0) not linking against libguilereadline-v-18.so.18

### ISSUE THREAD

**Issue by xelxebar** [void-linux/void-packages#4859]
### Overview

In PR #3414, @maxice8 added readline support to guile-2.0. At the time it seemed to work; however, recently (as of ae9d6dff) it seems that guile is failing to find the `libguilereadline-v-18.so.18` provided by `libguile`.

### System

```
$ xuname
Void 4.18.17_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFFFFFFF

$ xbps-query -p pkgver guile
guile-2.0.14_5
```

### Expected behavior

```
$ guile -q
scheme@(guile-user)> (use-modules (ice-9 readline))
scheme@(guile-user)>
```

### Actual behavior

```
$ guile -q
scheme@(guile-user)> (use-modules (ice-9 readline))
While compiling expression:
ERROR: In procedure dynamic-link: file: "libguilereadline-v-18", message: "file not found"
scheme@(guile-user)>
```

Indeed, `ldd $(command -v guile)` confirms that the binary isn't linked against said library.

### Notes

Out of curiosity, I tried building guile locally and noticed that it complains about `libguilereadline-v-18.so.18` not being in `common/shlibs`. Adding the necessary entry, while it keeps xbps-src from complaining, didn't seem to fix the linking problem for me:

```
diff --git a/common/shlibs b/common/shlibs
index 8517fda45c..7a52875cd3 100644
--- a/common/shlibs
+++ b/common/shlibs
@@ -1350,6 +1350,7 @@ libamtk-5.so.0 amtk-5.0.0_1
 libdevhelp-3.so.6 devhelp-libs-3.30.0_1
 libunistring.so.2 libunistring-0.9.4_1
 libguile-2.0.so.22 libguile-2.0.9_3
+libguilereadline-v-18.so.18 libguile-2.0.14_5
 libopts.so.25 libopts-5.18.4_6
 libanjuta-3.p
```

Perhaps, I just did something boneheaded?

**Comment by newbluemoon** [comment]
It needs the `libguilereadline-v-18.so` symlink which is in guile-devel, but in this case should probably be better in the (main) guile package itself.

**Comment by xelxebar** [comment]
Oh. That is remarkablely obvious. Thanks for the fix, @newbluemoon!
What's the deal with the missing entry in `common/shlibs`?

**Comment by newbluemoon** [comment]
The entry in `common/shlibs` is only necessary if other packages linked to libguilereadline.so, which isn’t the case so this message/warning can be safely ignored. :)
