### ISSUE TITLE
clang17 does not include header files

### ISSUE THREAD

**Issue by Sqvid** [void-linux/void-packages#48621]
### Is this a new report?

Yes

### System Info

Void 6.6.16_1 x86_64 AuthenticAMD uptodate rrFFFFF

### Package(s) Affected

clang17

### Expected behaviour

Installing clang should pull in the standard library headers so that you can actually compile programs. However `clang17` does not do this (one would need `clang17-devel`).

### Actual behaviour

Clang17 pulls in no headers and as a result cannot be used to compile C/C++ programs. Clang15 is unaffected.

Observe the difference between `xbps-query -Rf clang17` and `xbps-query -Rf clang15`

### Steps to reproduce

1. Install `clang17`
2. Paste the following in `main.c`:

```C
#include <stdio.h>

int main(void) {
	printf("Hello, World!\n");

	return 0;
}
```
3. run `clang main.c`
4. Obtain the error:
```C
In file included from test.c:1:
/usr/include/stdio.h:33:10: fatal error: 'stddef.h' file not found
   33 | #include <stddef.h>
      |          ^~~~~~~~~~
1 error generated.
```
5. Cry.

**Comment by chrysos349** [comment]
this problem is being fixed atm.

**Comment by Calandracas606** [comment]
https://github.com/void-linux/void-packages/pull/48625

Install clang17-devel for the time being

**Comment by Calandracas606** [comment]
This has been fixed
