### ISSUE TITLE
qt5-tools-5.15.11+20231124_1: broken, unresolvable shlib `libclang.so.15'

### ISSUE THREAD

**Issue by kobzar** [void-linux/void-packages#48623]
### Is this a new report?

Yes

### System Info

Linux Void 6.6.16_1 #1 SMP PREEMPT_DYNAMIC Wed Feb  7 19:24:35 UTC 2024 x86_64 GNU/Linux

### Package(s) Affected

qt5-tools-5.15.11+20231124_1

### Expected behaviour

*

### Actual behaviour

*

### Steps to reproduce

╰─  xbps-install -Su                                                                                                 8 (0.755s)
[*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/nonfree/x86_64-repodata' ...
qt5-tools-5.15.11+20231124_1: broken, unresolvable shlib `libclang.so.15'
Transaction aborted due to unresolved shlibs.

**Comment by voiduser123321** [comment]
Can confirm, having the same issue.

**Comment by KynikossDragonn** [comment]
I'm also getting something related to llvm15:
```
libllvm15-32bit-15.0.7_4 in transaction breaks installed pkg `libclang-32bit-15.0.7_3'
libllvm15-32bit-15.0.7_4 in transaction breaks installed pkg `libclang-cpp-32bit-15.0.7_3'
Transaction aborted due to unresolved dependencies.
```

**Comment by classabbyamp** [comment]
we're currently in the middle of making some major changes and updates to llvm, it'd be best to just wait for now

**Comment by kobzar** [comment]
Fixed

**Comment by rice7th** [comment]
Yeah @kobzar I am having the same error 1 momth later after upgrading the system

**Comment by Calandracas606** [comment]
@rice7th which arch?

**Comment by KynikossDragonn** [comment]
I solved it on my end by adding the offending packages to "ignorepkg" and uninstalling them, update, and then install the proper 32-bit packages that were introduced to specifically have llvm 15 and 17 libraries together.

```
ignorepkg=libclang-32bit
ignorepkg=libclang-cpp-32bit
```

**Comment by rice7th** [comment]
@Calandracas606 x86_64.

Anyways, I fixed it by re-running `xbps-install -Su`. Apparently some packages broke during installation.
