### ISSUE TITLE
python3 fails to build

### ISSUE THREAD

**Issue by KaiJan57** [void-linux/void-packages#48698]
### Is this a new report?

Yes

### System Info

Void 6.6.16_1 x86_64-musl GenuineIntel uptodate rFFF

### Package(s) Affected

python3

### Expected behaviour

xbps-src builds python3

### Actual behaviour

python3 build fails with clean masterdir, hostdir; error message:

```
gcc -shared -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -fno-semantic-interposition -fprofile-generate  Modules/zlibmodule.o -L/usr/lib -lz  -o Modules/zlib.cpython-312-x86_64-linux-musl.so
/usr/bin/ld: /usr/lib/libz.a(zutil.o): warning: relocation against `z_errmsg' in read-only section `.text'
/usr/bin/ld: /usr/lib/libz.a(deflate.o): relocation R_X86_64_PC32 against symbol `z_errmsg' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
```

### Steps to reproduce

1. clone void-packages
2. run xbps-src binary-bootstrap
3. run xbps-src pkg python3
4. it fails, even if masterdir and hostdir are cleaned

### Probably related:
[https://github.com/void-linux/void-packages/issues/39467](https://github.com/void-linux/void-packages/issues/39467)

**Comment by chrysos349** [comment]
can't reproduce. i built for `x86_64` and `x86_64-musl` (cross).

**Comment by KaiJan57** [comment]
Yep, just pulled again and it works now
