### ISSUE TITLE
`webkit2gtk` fails to crossbuild for `armv6l-musl`

### ISSUE THREAD

**Issue by chrysos349** [void-linux/void-packages#48747]
### Is this a new report?

Yes

### System Info

Void 6.6.16_1 x86_64 GenuineIntel/VM uptodate hold rrFFFFFF

### Package(s) Affected

webkit2gtk-2.40.0_4

### Expected behaviour

Be able to crossbuild `webkit2gtk` for `armv6l-musl` via `xbps-src`

### Actual behaviour

Crossbuilding gets stuck generating WebKit2WebExtension-4.1.typelib

```
[5855/5860] Building C object Tools/MiniBrowser/gtk/CMakeFiles/MiniBrowser.dir/BrowserWindow.c.o
../Tools/MiniBrowser/gtk/BrowserWindow.c: In function 'browserWindowCreateBackForwardMenu':
../Tools/MiniBrowser/gtk/BrowserWindow.c:257:54: warning: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'guint64' {aka 'long long unsigned int'} [-Wformat=]
  257 |         char *actionName = g_strdup_printf("action-%lu", ++actionId);
      |                                                    ~~^   ~~~~~~~~~~
      |                                                      |   |
      |                                                      |   guint64 {aka long long unsigned int}
      |                                                      long unsigned int
      |                                                    %llu
[5856/5860] Linking C executable bin/MiniBrowser
[5857/5860] Generating WebKit2WebExtension-4.1.gir
[5858/5860] Generating WebKit2WebExtension-4.1.typelib
```

### Steps to reproduce

1. Clone repo, bootstrap, etc.
2. Run `./xbps-src -a armv6l-musl pkg webkit2gtk`
3. Wait till eternity

P.S. Of course, I use clean masterdir.
P.P.S. The latest webkit2gtk has the same problem generating typelib file for armv6l-musl.

**Comment by chrysos349** [comment]
> Updating qemu-user-static to `8.1.5` seems to fix the issue.

Tried `qemu-user-static-8.1.5`.  Unfortunately, it didn't fix the issue.  What else did you do to successfully cross-build `webkit2gtk` for `armv6l-musl`?

**Comment by oreo639** [comment]
Sorry, yeah, I built qemu-user-static with some of the older patches that had been removed. I tried building it with those patches removed to make sure it worked without them, but I ended up building it with the other qemu-user-static.

This is the reason why: https://www.openwall.com/lists/musl/2017/06/21/2
And the patch got removed in the following commit: https://github.com/void-linux/void-packages/commit/147fb2841cdd6532a73009079f73cf0568ada885

**Comment by chrysos349** [comment]
Adding `mmap-mremap-efault.patch` to `qemu` fixed the issue with `webkit2gtk`. Why was this patch removed and the change approved in the first place, I wonder?

Thanks for getting to the bottom of this. I can proceed now.

**Comment by oreo639** [comment]
For the future, don't close the issue until the issue has been fixed in the void-packages repo.

**Comment by chrysos349** [comment]
Will do. Reopened.
