### ISSUE TITLE
`su` segfaults

### ISSUE THREAD

**Issue by balejk** [void-linux/void-packages#48758]
# Is this a new report?

Yes

# System Info

`Void 6.7.4_1 x86_64-musl GenuineIntel uptodate FFFFFFFF`

with `dracut` and `sudo` ignored.

# Package(s) Affected

`util-linux-2.38.1_6`

# Does a report exist for this bug with the project's home (upstream) and/or another distro?

No response

# Expected behaviour

`su -` opens a root shell when correct password is entered.

# Actual behaviour

`su` segfaults.

# Steps to reproduce

Update the system, run `su -`, enter correct password.

---

Downgrading to `util-linux-2.38.1_5` solves the problem. Since the latest revision of the package only changed the manpages, the problem is likely not in the package itself.

**Comment by classabbyamp** [comment]
can you run it in gdb and get a backtrace?

**Comment by sgn** [comment]
Can you run gdb on the corefile and post the backtrace. I don't think `gdb` works with `su`.

**Comment by balejk** [comment]
`# gdb --args su - user` does segfault but `bt` says "No stack". `gdb`
also prints "Detaching after fork from child process <PID>" -- could
that be the reason for the missing backtrace?

Unless I'm doing something wrong (`# ulimit -c unlimited; su - user`,
works for other binaries), there seems to be no core dumped either.

**Comment by sgn** [comment]
Because `su` is `setuid`

**Comment by sgn** [comment]
```
850     in login-utils/su-common.c
(gdb) p args[0]
$4 = 0x555660e5 <error: Cannot access memory at address 0x555660e5>
```

A classic 64 bits pointer truncated to 32 bit int, I think.

**Comment by balejk** [comment]
> Experiencing almost the same.
>
> ```
> su
> Password:
> su: failed to execute /bin/bash: Bad address
> ```

I can confirm that this is the same thing as I am seeing.

**Comment by sgn** [comment]
Fixed, please update and test in a moment.

**Comment by sgn** [comment]
https://github.com/util-linux/util-linux/pull/2615

**Comment by sgn** [comment]
The problem, as shown, is in the package itself, the old revision was compiled by different compilers.

**Comment by balejk** [comment]
> Fixed, please update and test in a moment.

The fix seems to work, thank you very much.

**Comment by oreo639** [comment]
Sorry for not noticing this issue earlier.
Btw for the future, such issues can be mitigated with `XBPS_CFLAGS="-O2 -pipe -Werror=implicit-function-declaration -Werror=implicit-int"` until gcc 14.

**Comment by sgn** [comment]
For `-Werror=implicit-function-declaration -Werror=implicit-int`

https://www.mail-archive.com/autoconf@gnu.org/msg24713.html
https://bugs.gentoo.org/870412

**Comment by sgn** [comment]
Thus, I think in order to have  `-Werror=implicit-function-declaration -Werror=implicit-int`, we need:
- Update autoconf to latest version
- `gnu-configure`'s `do_configure` need `autoreconf -fi`

**Comment by sgn** [comment]
But, even that, tons of autoconf script out there is their own m4 versions. :shrug:

**Comment by oreo639** [comment]
Either way, will have to deal with it in the near future. I'll look in to it more later.

(and yeah, a lot of applications will need their tests updated for ` -Werror=implicit-function-declaration -Werror=implicit-int`, including for example gimp. Fedora is doing a lot of work with testing, previously with ` -Werror=implicit-function-declaration -Werror=implicit-int` and currently with gcc 14. https://fedoraproject.org/wiki/Toolchain/PortingToModernC)
