### ISSUE TITLE
oracle-jre bug not allowing update to finish

### ISSUE THREAD

**Issue by viper968** [void-linux/void-packages#48782]
so because the oracle-jre package is having problems and is unable to be updated nor installed and i originally had it installed before the bug happened xbps is trying to configure it when i run `xbps-install -Su`. Because of this it is not able to fully finish the update of the other packages i need updated, is there a way to exempt oracle-jre from the update or force it to update even if there are errors?

**Comment by classabbyamp** [comment]
what problems?

**Comment by viper968** [comment]
heres the following section from where it states its configuring it to the end where it cancels out:
```
oracle-jre-8u332b05_2: configuring ...
Updating GTK+ icon cache for /usr/share/icons/hicolor...
Updating MIME database...
--2024-02-16 22:08:05--  http://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-linux-x64.tar.gz
Resolving download.oracle.com (download.oracle.com)... 23.63.156.181
Connecting to download.oracle.com (download.oracle.com)|23.63.156.181|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-linux-x64.tar.gz [following]
--2024-02-16 22:08:05--  https://edelivery.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.204.191.68, 2600:1404:ec00:1da7::366, 2600:1404:ec00:1d92::366
Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.204.191.68|:443... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2024-02-16 22:08:05 ERROR 502: Bad Gateway.

./var/tmp/oracle-jre-8u202_1.build/jre.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
ERROR: oracle-jre-8u332b05_2: [configure] INSTALL script failed to execute the post ACTION: Operation not permitted
Transaction failed! see above for errors.

```

and then nothing else is printed even with the other 300+ packages im needing to update/install but cant because this `oracle-jre` bug keeps making the `xbps-install -Su` command fail

**Comment by classabbyamp** [comment]
`oracle-jre` should be a transitional package for `openjdk8` [now](https://github.com/void-linux/void-packages/commit/8f85eae440ab0e0514c0bcabb6f34d4c1a520946). what mirror are you using?
