### ISSUE TITLE
wired-notify : Cargo.lock --locked

### ISSUE THREAD

**Issue by biopsin** [void-linux/void-packages#48794]
### Is this a new report?

Yes

### System Info

Linux voidx 5.10.209_1 #1 SMP UTC x86_64 GNU/Linux

### Package(s) Affected

wired-notify : update to 0.10.4_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Upstream: no
void: https://github.com/void-linux/void-packages/pull/43233

### Expected behaviour

Cargo.lock is updated

I looked at other packages with same issue and while Cargo.lock is supplied in wired-notify I just ran `cargo generate-lockfile` for a successfull build unless there is a bether patch approach?

### Actual behaviour

```
=> wired-notify-0.10.4_1: running do_build ...
error: the lock file /builddir/wired-notify-0.10.4/Cargo.lock needs to be updated but
 was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove th
d flag and use --offline instead.
=> ERROR: wired-notify-0.10.4_1: do_build: '${make_cmd} build --release --locked --ta
ST_TARGET} ${configure_args}' exited with 101
=> ERROR:   in do_build() at common/build-style/cargo.sh:8
```

### Steps to reproduce

./xbps-src pkg wired-notify

**Comment by tranzystorekk** [comment]
this is a common oversight when publishing `cargo packages`, upstream should be notified that the version in `Cargo.toml` doesn't match the one in `Cargo.lock`
