### ISSUE TITLE
TMUX inserting terminal color info into prompt

### ISSUE THREAD

**Issue by OliveThePuffin** [void-linux/void-packages#48807]
### Is this a new report?

Yes

### System Info

Void 6.6.16_1 x86_64 AuthenticAMD notuptodate rrrrmmnDFFFFFF

### Package(s) Affected

tmux-3.4_1, rxvt-unicode-9.31_3

### Expected behaviour

Whenever attaching to a session, or creating a new session, tmux does not inserts any text into the prompt.

For example the prompt should look like:
```
locolhost%
```

### Actual behaviour

Whenever attaching to a session, or creating a new session, tmux inserts this text into the prompt.

For example this text is inserted after the prompt:
```
localhost% 10;rgb:e500/dd00/eb00]11;rgba:0000/0000/0000/aa00
```
This seems to be the terminal background and foreground color.

Note: Everything works fine on tmux version 3.3a_2.
This also doesn't happen on all terminals (eg, xterm is fine)

### Steps to reproduce

Open a Urxvt terminal ($TERM is rxvt-unicode-256color)
create or attach to a tmux session ($TERM should now be tmux-256color)

On my end, I verified that this bug exists in bspwm and xfce4 and in bash and zsh

**Comment by chrysos349** [comment]
I reproduced the issue.
This is a bug in `urxvt`. See here - https://github.com/tmux/tmux/issues/3470

I submitted a pr to fix this issue - #48809
