### ISSUE TITLE
openvpn: should it include a runit service?

### ISSUE THREAD

**Issue by slymattz** [void-linux/void-packages#48834]
### OpenVPN - a debate whether to include a runit service
As many of you might know, OpenVPN can be run either as a server or a client. 

When run as a server, it needs some kind of a trigger that will start it at boot time. The current OpenVPN package does not, however, include a runit service.

When run as a client, it can be either started on boot which would typically require a runit service or it can be executed with the simple command `openvpn /etc/openvpn/yourconfig.conf`. 

In the first two cases, I believe it is justifiable and reasonable to include a runit service. A few years ago, such a proposal wasn't upheld (https://github.com/void-linux/void-packages/pull/17906#issuecomment-569937899). I believe now's a good time to re-address this issue. 

In my opinion, if Void aims to be as good of an option for a desktop as for a server, we require this change to happen. Of course, you can create the appropriate _run_ file manually in _/etc/sv/openvpn_ and you're good to go. However, such an approach seems to be particularly confusing for new users and it is also inconsistent with the fact that many other daemon servers DO have runit services that come along with them.

Therefore, I'd like to raise the question from the heading: should the openvpn package come with a runit service?

**Comment by Duncaen** [comment]
Might make sense to include example services for client and server, resembling `usr/lib/systemd/system/openvpn-client@.service` and `usr/lib/systemd/system/openvpn-server@.service` so users don't blindly enable the service just because they want to use openvpn as a client. 

We've made bad experiences with shipping ready to use system services for things that should most likely not run as the system services, see pipewire and pulseaudio experiences, where unexpected users started to enable those services without knowing that the preferred method of starting them is through some other means.

**Comment by slymattz** [comment]
Enabling OpenVPN through `ln -sv /etc/sv/openvpn /var/service` would do nothing by default as /etc/openvpn does not even exist in Void's OpenVPN package. 

You would have to either 
```
mkdir -p /etc/openvpn
cp /usr/share/examples/openvpn/client.conf /etc/openvpn/openvpn.conf # modify the default script
vim /etc/openvpn/openvpn.conf
# or
cp /path/to/your/config.conf /etc/openvpn/openvpn.conf
```
With no user intervention, OpenVPN won't run. If you have another path pointing to a client/server configuration, you can point to it by:
`echo "CONF_FILE=/path/to/vpn.conf > /etc/sv/openvpn/conf`

As for the pipewire and pulseaudio analogy - I think these are completely different cases as the preferred method for them is, like you say, to be run by a user.

In an OpenVPN config file, you can specify both the user and the group that the process should be run by. As a matter of fact, you can run the process as an unprivileged user (on Debian, for instance, you just insert these lines in your openvpn config):

_/etc/openvpn/openvpn.conf_
```
user nobody
group nogroup
```

**Comment by Duncaen** [comment]
runit would restart the service once a second.

**Comment by slymattz** [comment]
Oh, this I didn't know about :(

**Comment by Duncaen** [comment]
> As for the pipewire and pulseaudio analogy - I think these are completely different cases as the preferred method for them is, like you say, to be run by a user.

Depends, many users probably just use NetworkManager to handle their VPN.

**Comment by slymattz** [comment]
Sure :) What about the server side, though?

**Comment by slymattz** [comment]
Correct me if I'm wrong but what you suggested could also work. Namely, to supply a runnit server somewhere in /usr/share/openvpn. So that you could easily copy it to /etc/sv
