### ISSUE TITLE
ktuberling: desktop entry is not visible

### ISSUE THREAD

**Issue by Luciogi** [void-linux/void-packages#48863]
### Is this a new report?

Yes

### System Info

Void 6.6.17_1 x86_64 GenuineIntel notuptodate rrmFFFFFFFFFFFFFFFFFFF

### Package(s) Affected

ktuberling-23.08.4_1

### Expected behaviour

Desktop entry should be visible

### Actual behaviour

![image](https://github.com/void-linux/void-packages/assets/84625092/21424520-757f-4a21-80e1-71c7ce56f84e)

### Steps to reproduce

1. xbps-install ktuberling
2. open applications menu
3. search "ktuberling" or "tuberling"

**Comment by chrysos349** [comment]
Search for 'Potato Guy'

![Screenshot from 2024-02-21 12-22-34](https://github.com/void-linux/void-packages/assets/63523825/7eeb9d50-4027-4ab2-a7c6-c7b466b641e9)

**Comment by Luciogi** [comment]
> Search for 'Potato Guy'
> 
> ![Screenshot from 2024-02-21 12-22-34](https://private-user-images.githubusercontent.com/63523825/306567395-7eeb9d50-4027-4ab2-a7c6-c7b466b641e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTMxNTMsIm5iZiI6MTcwODUxMjg1MywicGF0aCI6Ii82MzUyMzgyNS8zMDY1NjczOTUtN2VlYjlkNTAtNDAyNy00YWIyLWE3YzYtYzdiNDY2YjY0MWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDEwNTQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMmI1ZWI2OTRjNjU3ODFjNDFiYTc2MjIxZmNhMjVjZDk0ZTMyODQ3ZTNlOGM5MTQ5NzAzYzE0ODgwYTY0MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cHeNjYI02_-2ecyXriOhgTLQ3MTpB6bbgRdDJQ21wBU)

thank you
