### ISSUE TITLE
gdm fails to change screen brightness

### ISSUE THREAD

**Issue by mayhair** [void-linux/void-packages#48876]
### Is this a new report?

Yes

### System Info

Void 6.6.17_1 x86_64 GenuineIntel uptodate FFFFFFFFF

### Package(s) Affected

gdm-44.1_2

### Expected behaviour

It is possible to change the screen brightness via GDM, either by using the brightness keys or the graphical slider.

### Actual behaviour

Pressing the brightness keys or using the slider does nothing, graphically. It does output an error similar to this to socklog:
```
2024-02-22T09:17:48.62989 authpriv.crit: Feb 22 14:17:48 pkexec[2028]: gdm: The value for the SHELL variable was not found in the /etc/shells file [USER=root] [TTY=unknown] [CWD=/var/lib/gdm] [COMMAND=/usr/libexec/gsd-backlight-helper /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight 80]
```
This is peculiar, because executing the same command (`/usr/libexec/gsd-backlight-helper /sys/devices/pci0000:00/0000:00:02.0/drm/card0/card0-eDP-1/intel_backlight [brightness]`), as root and within an interactive shell works with no problems.

### Steps to reproduce

When GDM is set as the display manager, make sure you are logged out.
Then try to change the brightness, either by pressing the brightness keys or by clicking the top-right corner (where the Wi-Fi and battery symbols are) and adjusting the brightness slider.

**Comment by chrysos349** [comment]
In my case, `gdm` behaves the same. So what? Log in, and THEN change the brightness.

I'm not sure this is a bug. 

Of course, if you insist on being able to change the brightness BEFORE logging in, run this command, and restart.

``` bash
$ sudo chsh -s /bin/bash gdm
```

P.S. `pkexec` complains, because by default, `gdm` user has `/sbin/nologin` as its shell (run `grep gdm /etc/passwd` to confirm), which is not in `/etc/shells`. the command above changes the default shell of `gdm` user to `/bin/bash`.

**Comment by mayhair** [comment]
Yeah, changing the gdm user's shell to `/bin/sh` fixes the issue.

> I'm not sure this is a bug.
I'm not sure that this is NOT a bug. GDM has a built-in brightness slider, that logged an error when I tried to use it.

**Comment by ahesford** [comment]
It would probably be better to add `/sbin/nologin` to `/etc/shells` than to give the `gdm` user a real shell.

I recommend making the backlight files writable by some particular group (`video` is a common choice) and add `gdm` to that group. This might avoid the privilege escalation entirely and stop pkexec from complaining.

**Comment by ahesford** [comment]
This is a consequence of configuration choices made in the `gdm` package. While some users may want the brightness slider to work out of the box, other users may not want the `gdm` user to be assigned a valid login shell or may wish to restrict access to brightness. Some configuration may be necessary to get some software features to work as expected.

**Comment by mayhair** [comment]
> This is a consequence of configuration choices made in the `gdm` package. While some users may want the brightness slider to work out of the box, other users may not want the `gdm` user to be assigned a valid login shell or may wish to restrict access to brightness. Some configuration may be necessary to get some software features to work as expected.

Could the steps to let gdm change the brightness at least be listed in the Void Docs? There isn't really any clearly documented way to enable it otherwise.
