### ISSUE TITLE
LibreOffice v7.6.4.1 crashing when trying to print

### ISSUE THREAD

**Issue by gc-user** [void-linux/void-packages#48871]
### Is this a new report?

Yes

### System Info

Void 6.6.17_1 x86_64 GenuineIntel uptodate hold rrmDDDFFFFFFFF

### Package(s) Affected

libreoffice-7.6.4.1_1.x86_64

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://bugs.documentfoundation.org/show_bug.cgi?id=158379

### Expected behaviour

"Print" should open the print dialog and then allow to successfully print.

### Actual behaviour

When trying to print libreoffice crashes.

I tried all libreoffice sub-programs. When starting any of them (having only the default "new document" opening automatically, i.e. no data added) and then trying to open the print dialog, the respective program crashes - either immediately, or, if the dialog opens (writer seems to only crash immediately if the file contains data) "normally", the program crashes when closing the dialog when pressing "cancel".

I rarely print using libreoffice, so I can't say if this version of libreoffice printed ok at one point and only after some other package update (e.g. hplip 3.23.12_1, cups 2.4.7_4) started crashing when trying to print.

Exporting from libreoffice writer as pdf and then printing using e.g. evince works fine.

### Steps to reproduce

1. Open any of the libreoffice prgrams. Preferably writer. No need to open any file, a new, empty document should suffice.
2. Click "File" -> "Print" or Ctrl+P
3. If the program doesn't immediately crash, click "cancel" on the print dialog. Now the program should crash.

**Comment by sgn** [comment]
I can't reproduce. I can print to pdf normally.

**Comment by biopsin** [comment]
Can't reproduce either, print dialog opens and cancels normaly.
Can you start libreoffice from a terminal and see what it prints out?

**Comment by gc-user** [comment]
There are no print-outs when starting from terminal at all.

I also ran it using --backtrace argument and attached the log file. Other than a segmentation fault / warning which might also be "normal", I didn't notice any obvious.

[gdbtrace.log](https://github.com/void-linux/void-packages/files/14377959/gdbtrace.log)


I also started write with the the --safe-mode argument which seems to be the same as renaming ~/.config/libreoffice (which i also did at one point to see if it's some setting, i.e. like using libreoffice for the first time), but that didn't change anything.

**Comment by sgn** [comment]
Can you install `libreoffice-common-dbg` then run with gdb again?

**Comment by sgn** [comment]
And which language are you using?

**Comment by sgn** [comment]
What's your default paper size?

**Comment by sgn** [comment]
https://github.com/LibreOffice/core/commit/c92d01f82f3cbcb504a839cea5852e6c85a1d420

**Comment by sgn** [comment]
https://bugs.documentfoundation.org/show_bug.cgi?id=158379

**Comment by gc-user** [comment]
> Can you install `libreoffice-common-dbg` then run with gdb again?

Here's the log with the dbg package installed:
[gdbtrace 2.log](https://github.com/void-linux/void-packages/files/14384250/gdbtrace.2.log)

**Comment by gc-user** [comment]
> What's your default paper size?

I tried different paper sizes, none of then didn't crash.

**Comment by gc-user** [comment]
> https://bugs.documentfoundation.org/show_bug.cgi?id=158379

Thanks for your efforts and digging!

**Comment by sgn** [comment]
30cccaf7

**Comment by gc-user** [comment]
Cool! Thank you very much!

**Comment by gc-user** [comment]
The update fixes the issue.
Thanks again for the fast resolve!
