### ISSUE TITLE
GNOME evolution fails to launch

### ISSUE THREAD

**Issue by morrismuehl** [void-linux/void-packages#48892]
### Is this a new report?

Yes

### System Info

Void 6.6.17_1 x86_64 GenuineIntel uptodate rrrmDFFFFFF

### Package(s) Affected

evolution-3.48.4_2; evolution-data-server-3.48.4_2  

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://gitlab.gnome.org/GNOME/evolution/-/issues/1845

### Expected behaviour

Package launches

### Actual behaviour

launching evolution produces the following output:

`evolution: symbol lookup error: /usr/lib/libebook-contacts-1.2.so.4: undefined symbol: _ZN4i18n12phonenumbers11PhoneNumberC1ERKS1_`

I believe this could be related to the upstream bug posted above. I briefly tried downgrading `libphonenumber` but it seems like that would require me to downgrade `libprotobuf` as well. 
I do not have the time to investigate this further right now

### Steps to reproduce

launch evolution

**Comment by classabbyamp** [comment]
looks like `evolution-data-server` needs to be rebuilt

**Comment by ahesford** [comment]
Please let us know if #48897 failed to fix your issue.

**Comment by sgn** [comment]
It's still being built.
