### ISSUE TITLE
ERROR: libelogind-252.9_2: SHA256 hash is not valid: No such file or directory

### ISSUE THREAD

**Issue by gc-user** [void-linux/void-packages#48913]
### Is this a new report?

Yes

### System Info

Void 6.6.17_1 x86_64 GenuineIntel uptodate hold rrmDDDDFFFFFFFF

### Package(s) Affected

libelogind-252.9_2

### Expected behaviour

Building libfreerdp-server-2.10.0_3 locally using xbps-src should run through without issues.

### Actual behaviour

When trying to build libfreerdp-server-2.10.0-3 xbps-src fails and gives out the following error message:

ERROR: libelogind-252.9_2: SHA256 hash is not valid: No such file or directory

### Steps to reproduce

1. Try building locally freerdp (it doesn't matter if 2.10.0_3 or 2.11.4_1 nor if it's freerdp or libfreerdp-server)
2. See xbps-src failing with the above error message.

**Comment by chrysos349** [comment]
Can't reproduce. `freerdp-2.11.4` was built without errors.

**Comment by gc-user** [comment]
Found the cause of the issue. /void-packages/hostdir/binpkgs/x86_64-repodata had apparently libelogind-252.9_2.x86_64.xbps listed, but the file was missing, thus the error. Putting the file in that folder and re-indexing the folder fixed the issue.

From the error message and output before it, it seemed as if xbps-src was looking online for the file...
