### ISSUE TITLE
mpv does not build with the vulkan option turned off

### ISSUE THREAD

**Issue by Aicaya** [void-linux/void-packages#48914]
### Is this a new report?

Yes

### System Info

Void 6.1.71_1 x86_64 AuthenticAMD uptodate rrmFFFFFFFFFFFFFF

### Package(s) Affected

mpv-0.37.0_1

### Expected behaviour

Building mpv with vulkan disabled should work.

### Actual behaviour

Build fails due to `libplacebo-devel` only being a dependency when the vulkan option is enabled.

I should note that the previous version of mpv built fine without it, so maybe the dependency is now mandatory?  Don't really know what it does and the pull request merge seems to be recent, which is why I'm writing an issue instead of sending a fix.

### Steps to reproduce

1. `./xbps-src -o ~vulkan pkg mpv`
2. Wait.

**Comment by chrysos349** [comment]
here is the release notes for `mpv-0.37` regarding `libplacebo`. see here - https://github.com/mpv-player/mpv/releases

> This is the first release to unconditionally require libplacebo, but note that the new improved renderer (vo_gpu_next) is not yet the default.
>...
>meson: make libplacebo a required dependency

the template needs to be fixed.
