### ISSUE TITLE
webkit rendering issues

### ISSUE THREAD

**Issue by balejk** [void-linux/void-packages#48952]
## Is this a new report?

Yes

## System Info

Void 6.6.17_1 x86_64-musl GenuineIntel uptodate FFFFF

## Package(s) Affected

`luakit`, although the issue is probably with `webkit2gtk`

## Does a report exist for this bug with the project's home (upstream) and/or another distro?

No.

## Expected behaviour

luakit renders all pages correctly.

## Actual behaviour

Some pages, such as github, freeze and do not respond to window resize, clicks or other things. Refreshing maybe helps a little, but it's hard to tell, because it seems to break almost every time (or it just stays broken through the refresh). The browser itself is responsive and does not print any errors.

## Steps to reproduce

Run luakit, navigate to https://github.com/void-linux/void-packages/issues/, try to do anything, it should freeze soon.

---

Note that everything worked fine before the recent webkit update (even with the updated luakit). At the same time though, I am not able to reproduce this with epiphany, but perhaps that's because that uses GTK4 while luakit GTK3.

It might also be worth noting that I have previously been experiencing similar problems with qutebrowser since the QtWebEngine update to 6.6.

**Comment by oreo639** [comment]
Thanks for reporting, I can reproduce this with luakit on github.com with both 2.3.3 and 2.3.6.

**Comment by chrysos349** [comment]
> I can reproduce this with luakit on github.com with both 2.3.3 and 2.3.6.

The same here.

I reproduced the bug on archlinux (it has the same versions of `luakit` and `webkit2gtk`). The page froze as well, which means the bug is not void-specific. Submit the bug upstream, maybe?

**Comment by chrysos349** [comment]
> the bug is not void-specific.

I tested `luakit-2.3.6` built with `webkit-2.43.3` in ubuntu-24.04 (daily image). The same problem. 
Fedora doesn't package `luakit` at all.

**Comment by balejk** [comment]
Thank you both for looking into this.

I was convinced that this would be a bug with webkit but I am unable to
reproduce it with the MiniBrowser.

@oreo639 I see that you updated nyxt a few days ago. Does that mean that
you are using it? If so, can you please confirm that the problem is not
present there?

**Comment by balejk** [comment]
Thank you for the confirmation. I have reported this upstream [1].

[1] https://github.com/luakit/luakit/issues/1081

**Comment by jlzht** [comment]
It seems that the issue might be related to hardware acceleration policy, setting it to "on-demand", causes this behavior, at least on [luakit](https://github.com/luakit/luakit/issues/1081#issuecomment-1985810924), can someone with webkit based browser that exposes this option confirm if this is the case?

**Comment by balejk** [comment]
I suppose this might as well remain closed, although the problem is
still present with webkit 2.44.2. In addition to that, ever since
updating to this version, touchscreen/touchpad scrolling in luakit has
become laggy for me -- basically there seems to be a noticeable delay
before the page actually moves. I haven't looked into it further.
