### ISSUE TITLE
Update: snes9x 1.57

### ISSUE THREAD

**Issue by johnny-mac** [void-linux/void-packages#4905]
There's an update for Snes9x, version 1.57. Was released 10 days ago & looks like it may have gone unnoticed, so I'm here to mention it :)

**Comment by johnny-mac** [comment]
Looks like theres also an update for PPSSPP - v1.7.2

**Comment by Johnnynator** [comment]
> Looks like theres also an update for PPSSPP - v1.7.2

This one is not tagged as latest release on Github. The Website also lists 1.7.1 as latest. So the .2 seems to be only some Android related changes, so nothing interesting for us.

**Comment by Hoshpak** [comment]
Also both were reported by the update check: https://alpha.de.repo.voidlinux.org/void-updates/void-updates_2018-11-19.txt . There's no need to open issues about it.

**Comment by johnny-mac** [comment]
Ohh, okay Hoshpak. I wasn't aware of how this system works til now. I will keep this in mind.
So you guys get notified for updates to packages, that's good, but when a project ends up dead & active development ends up going somewhere else, you guys don't get notified for that right?
