### ISSUE TITLE
[Renamed] Gutenberg -> Zola

### ISSUE THREAD

**Issue by caemor** [void-linux/void-packages#4909]
Hello,

Gutenberg got renamed to Zola in the new version (see redirect and readme from https://github.com/Keats/gutenberg).

Greetings,
Caemor

**Comment by maxice8** [comment]
Thank for the headsup i'll take a look at it

**Comment by maxice8** [comment]
#4917

**Comment by maxice8** [comment]
The transition was made. Thanks for the headsup.
