### ISSUE TITLE
Package request: uv

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-packages#49140]
### Package name

uv

### Package homepage

https://github.com/astral-sh/uv

### Description

An extremely fast Python package installer and resolver, written in Rust. Designed as a drop-in
replacement for `pip` and `pip-compile`.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/pull/48763

**Comment by balejk** [comment]
The package was added in edddc0dd57ac so this can probably be closed.
