### ISSUE TITLE
Add C.UTF-8 locale to /etc/default/glibc-locales

### ISSUE THREAD

**Issue by beginner3456789** [void-linux/void-packages#49162]
### Is this a new report?

Yes

### System Info

Void 6.7.7_1 x86_64 GenuineIntel uptodate rrFFF

### Package(s) Affectedhttps://sourceware.org/glibc/wiki/Proposals/C.UTF-8

glibc-locales-2.38_5 GNU C library - locale data files

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

commented at https://github.com/archlinux/mkinitcpio/commit/5db56e248463033f3d70f192d517498e906b2569

### Expected behaviour

The mkinitcpio was changed to locale C.UTF-8 except the /etc/default/glibc-locales doesn't have that choice. So I had to add the choice `C UTF-8` to the /etc/default/glibc-locales and now there are no errors with mkinitcpio:
```
$ xbps-reconfigure -f glibc-locales
glibc-locales: configuring ...
Generating GNU libc locales...
  en_US.UTF-8... done.
  en_US.ISO-8859-1... done.
  C.UTF-8... done.
glibc-locales: configured successfully.

```

### Actual behaviour

```
==> Starting build: '6.7.7_1'
  -> Running build hook: [base]
/usr/lib/initcpio/functions: line 838: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: 'bfa'
==> WARNING: Possibly missing firmware for module: 'advansys'
==> WARNING: Possibly missing firmware for module: 'qla1280'
==> WARNING: Possibly missing firmware for module: 'wd719x'
==> WARNING: Possibly missing firmware for module: 'isci'
==> WARNING: Possibly missing firmware for module: 'qed'
==> WARNING: Possibly missing firmware for module: 'qla2xxx'
==> WARNING: Possibly missing firmware for module: 'aic94xx'
==> WARNING: Possibly missing firmware for module: 'xhci_pci'
==> WARNING: Possibly missing firmware for module: 'ums_eneub6250'
  -> Running build hook: [filesystems]
  -> Running build hook: [fsck]
/usr/lib/initcpio/functions: line 838: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: '/boot/initramfs-6.7.7_1.img'
bsdtar: Failed to set default localebsdtar: 
Failed to set default locale
==> Initcpio image generation successful
```

### Steps to reproduce

This problem maybe only affects mkinitcpio and started after updating mkinitcpio from v37.3 to v38 and installing kernel 6.7.7_1. Then downgrading to mkinitcpio 37.7 returned the error free behaviour. Then adding the `C UTF-8` choice to /etc/default/glibc-locales allowed installing mkinitcpio 38 and kernel 6.7.7_1 without the above errors about the "cannot change locale". 

So glibc 2.35 changes about C.UTF-8 need to appear in the locales. This should be easy to fix except I am unsure about the correct syntax for the C.UTF-8 entry in the /etc/default/glibc-locales. For reference: https://sourceware.org/glibc/wiki/Proposals/C.UTF-8

**Comment by classabbyamp** [comment]
already in progress https://github.com/void-linux/void-packages/pull/49146

**Comment by beginner3456789** [comment]
> already in progress #49146

I ran a search for glibc and mkinitcpio before starting this issue and did not find the #49146 issue. Should I close this issue or do something else?

**Comment by oreo639** [comment]
Thanks for pointing out the commit.

> Starting with glibc 2.39, LC_ALL=C.UTF-8 overrides LANGUAGE

That's a little problematic since we are currently using glibc 2.38.

**Comment by beginner3456789** [comment]
OK. Doing nothing...
