### ISSUE TITLE
Compiz broken with libxml2-2.12

### ISSUE THREAD

**Issue by furryfixer** [void-linux/void-packages#49203]
### Is this a new report?

Yes

### System Info

Void 6.6.20_1 x86_64 AuthenticAMD uptodate hold rDFFFF

### Package(s) Affected

compiz-core-0.8.18_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

[https://gitlab.com/compiz/compiz-core/-/merge_requests/175/diffs?commit_id=ea7b3731b1a8a0f2fb7aa765a84374658b67b1b7]

### Expected behaviour

Compiz starts normally when invoked. (works with libxml2 downgrade to 2.11)

### Actual behaviour

Compiz fails to start. When started manually, the following error or similar occurs:

 
> Entity: line 1: parser error : Extra content at the end of the document
>  name="force_independent_output_painting" type="bool"/></screen></core></compiz>
>                                                                                ^
> compiz (core) - Warn: Unable to parse XML metadata

### Steps to reproduce

I suspect anyone using up-to-date package versions of compiz-core and libxml2 will experience the problem.  Upstream has patched this in 8.18 I think, so I suspect Void just needs to rebuild (rev-bump?). Unfortunately, my git skills are limited, so I do not feel comfortable doing a PR myself that likely will need all the packages in compiz-reloaded rebuilt.

**Comment by oreo639** [comment]
Can you verify https://github.com/void-linux/void-packages/pull/49205 works for you?

**Comment by furryfixer** [comment]
I confirm the latest patches resolve the issue for updated x86_64 system, and presumably elsewhere. Thanks.
