### ISSUE TITLE
Package request: OpenJDK8 update, update source

### ISSUE THREAD

**Issue by yjqg6666** [void-linux/void-packages#49216]
### Package name

openjdk8

### Package homepage

https://adoptium.net/temurin/archive/?version=8

### Description

[The old openjdk8 version](https://github.com/void-linux/void-packages/tree/master/srcpkgs/openjdk8)  is using https://hg.openjdk.org/jdk8u/jdk8u/tags and the latest version was released at year 2021. The maintained version can also be found at Eclipse Adoptium. I would like to suggest updating the package source to https://adoptium.net/temurin/archive/?version=8 where the latest version is 8u402 https://github.com/adoptium/temurin8-binaries/releases/tag/jdk8u402-b06 released at January 2024. A new package is needed, or the old openjdk8 package need to be update.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
that is not the same source as we use for openjdk8. we [specifically use](https://github.com/void-linux/void-packages/blob/master/srcpkgs/openjdk8/template#L43-L45) the shenandoah version to get aarch64 support.
