### ISSUE TITLE
Oomox missing files

### ISSUE THREAD

**Issue by Vintodrimmer** [void-linux/void-packages#4925]
### System

* xuname:  
  *Void 4.19.2-chrysalis x86_64 GenuineIntel uptodate rFFFFFF*
* package:  
  *oomox-1.6.2_2 Graphical application for generating color variations of some themes*

### Expected behavior
running `wal -g ...` and getting the colors for the GTK2/3 theme.

### Actual behavior
```
[I] reload: Waiting for Oomox.
/usr/bin/oomox-cli: 3: exec: ./plugins/theme_oomox/gtk-theme/change_c
```

Also, I'm not sure if that's the way it's supposed to be, but there is no theme in the `lxappearance` after the installation.
Should I install the theme itself separately and get the files?

### Steps to reproduce the behavior
!. Take any picture
2. Run `wal` with the `-g` flag
3. Error occurs

**Comment by Vintodrimmer** [comment]
Understood.

**Comment by lucaxvi** [comment]
This has been broken for months now, at this point it should just be removed. There's no point in having an unusable package.
