### ISSUE TITLE
Package request: incus-ui (lxd-ui patched for incus)

### ISSUE THREAD

**Issue by cmspam** [void-linux/void-packages#49268]
### Package name

incus-ui

### Package homepage

https://github.com/canonical/lxd-ui

### Description

incus-ui is a patched version of the lxd web ui, to work with incus.

In order to build it, we would take the source from https://github.com/canonical/lxd-ui then apply patches and sed commands to rebrand it, and to change necessary strings for it to work with incus before compiling it with yarn.  It would then be stored in, let's say /path/to/incus/ui which incusd can reference. These patches are available from https://github.com/zabbly/incus and the way they are applied can be seen [here](https://github.com/zabbly/incus/blob/daily/.github/workflows/builds.yml)

We then need to set the environment variable INCUS_UI=/path/to/incus/ui when the incusd service is run.

We can see nixos's implementation of this, for example, [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/in/incus/ui.nix) 

I find the UI to be incredible useful, and would like to be able to use it in void without having to hack it together myself.

Is this something you would be interested in bringing to void?

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by ahesford** [comment]
We don't take upstream packages and apply patches from other repositories  to "rebrand" and alter their functionality. If somebody starts maintaining a proper project with support for incus, we can consider adding it. In the meantime, there is nothing actionable here.
