### ISSUE TITLE
Error clone void-packages

### ISSUE THREAD

**Issue by tuxslack** [void-linux/void-packages#49339]
$ git -v
git version 2.44.0

$ git clone https://github.com/void-linux/void-packages.git 

Cloning into 'void-packages'...
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 5752 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by iFoundSilentHouse** [comment]
It's something wrong on your side. Try this https://github.com/orgs/community/discussions/48568#discussioncomment-5108608

**Comment by classabbyamp** [comment]
we have no control over github's infrastructure, raise an issue with them.
