### ISSUE TITLE
Current biber and biblatex version incompatibil

### ISSUE THREAD

**Issue by sabrinasomething** [void-linux/void-packages#49347]
### Is this a new report?

Yes

### System Info

Void 6.6.22_1 x86_64 GenuineIntel uptodate rrFF

### Package(s) Affected

bbiber-2.16_3, texlive-bibtexextra-2023.66579_1, texlive-20230313_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Upstream not affected

### Expected behaviour

Compiling a latex file in which biblatex is used to cite should work.

### Actual behaviour

biber returns an error:
```
ERROR - Error: Found biblatex control file version 3.10, expected version 3.7.
This means that your biber (2.16) and biblatex (3.19) versions are incompatible.
```

As can be seen here: https://texdoc.org/serve/biber.pdf/0 2.19 is the correct biber version for biblatex version 3.19

### Steps to reproduce

1. Write a small latex file where biblatex is used to cite something.
2. Try to compile it (for example using latexmk).

**Comment by meator** [comment]
Could you provide a sample LaTeX file (and additional files if necessary) which triggers this error?

**Comment by dkwo** [comment]
maybe just update biber?

**Comment by Clos3y** [comment]
I'm having the same issue. I imagine the aforementioned PR would work but it failed the `i686` build: I'll test it this week if I can.
