### ISSUE TITLE
Package request: Apologies, update xen from 4.14.1 (2020) to 4.18 (2024) [badly need of an update; unpushed pull request of 4.17.2 also present]

### ISSUE THREAD

**Issue by 0x33taji** [void-linux/void-packages#49397]
### Package name

xen

### Package homepage

https://www.xenproject.org/

### Description

xen was last updated in 2020.
Apologies, xen is an orphan@voidlinux.org and is badly in need of an update.

There is an unpushed pull request for 4.17.2 (https://github.com/void-linux/void-packages/pull/47141) here on this repo.

Please feel free to close this issue, if it already on your radar.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
Please don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.

**Comment by 0x33taji** [comment]
@classabbyamp Apologies, I checked the script before filing the issue.
**The script you've linked says the requested package is orphaned, under the heading orphan@voidlinux.org**
And seemingly so, the package has not been updated to the current since 4 years, if I am not mistaken.

While I cannot vouch for quality, there seems to be a pull request for the previous stable release. https://github.com/void-linux/void-packages/pull/47141

*While, I understand you get a lot of issues and pull requests, please do not respond blindly. The previous pull requester seems also to be annoyed by this attitude and left the patch unfulfilled. Thank you for understanding*
