### ISSUE TITLE
Texlive2023-bin fails configuration

### ISSUE THREAD

**Issue by Luc-Saccoccio** [void-linux/void-packages#49398]
### Is this a new report?

Yes

### System Info

Void 6.6.22_1 x86_64 GenuineIntel uptodate FFFF

### Package(s) Affected

texlive2023-bin-2023_1

### Expected behaviour

texlive2023-bin installation ends up with the execution of `/opt/texlive2023-installer/install-tl`, which should install texlive.

### Actual behaviour

The installation ends with
```
Automated TeX Live installation using profile: void.profile
Loading https://mirror.ibcp.fr/pub/CTAN/systems/texlive/tlnet/tlpkg/texlive.tlpdb

=============================================================================
./install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2023
 repository: 2024
Perhaps you need to use a different CTAN mirror?
(For more, see the output of install-tl --help, especially the
 -repository option.  Online via https://tug.org/texlive/doc.)
=============================================================================
texlive2023-bin-2023_1: post-install message:
========================================================================
  To update your TeX Live installation use only the program

  /opt/texlive/2023/bin/<arch>/tlmgr

  where <arch> is:
    - x86_64-linux  ==> x86_64 architecture
    - i386-linux    ==> i386 architecture

  for details see:
  http://www.tug.org/texlive/doc/tlmgr.html#EXAMPLES

  WARNING: To avoid messing up your TeX Live installation, DON'T use
  the installation scripts in /opt/texlive-installer.

  This package only installs TeX Live infrastructure now, not TeX Live itself.
  For a basic installation (previous default), run "tlmgr install scheme-basic".
  For a full installation, run "tlmgr install scheme-full".
========================================================================
texlive2023-bin-2023_1: installed successfully.
```
And none of the actual commands are installed (`tlmgr` or compilers), but the package is registered as "installed successfully".

### Steps to reproduce

Install `texlive2023-bin` on a fresh Void installation.

**Comment by ahesford** [comment]
The install message tells you specifically that this is expected behavior:
> This package only installs TeX Live infrastructure now, not TeX Live itself.
> For a basic installation (previous default), run "tlmgr install scheme-basic".
> For a full installation, run "tlmgr install scheme-full".

**Comment by Luc-Saccoccio** [comment]
I'm sorry, but in theory I should have at least `tlmgr` in my path for me to do that. However, because of that specific part :
```
=============================================================================
./install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2023
 repository: 2024
Perhaps you need to use a different CTAN mirror?
(For more, see the output of install-tl --help, especially the
 -repository option.  Online via https://tug.org/texlive/doc.)
=============================================================================
```
(which is printed by `/opt/texlive2023-installer/install-tl`) I don't even have `tlmgr` to complete the installation. In fact, I don't have the directory `/opt/texlive/2023/bin/<arch>/tlmgr`, I only have `/opt/texlive2023-installer`.

**Comment by ahesford** [comment]
Sorry, I misunderstood. This is definitely broken.

**Comment by Luc-Saccoccio** [comment]
Thanks to leahneukirchen, ([69f3be4](https://github.com/void-linux/void-packages/commit/69f3be434ffac0690751cfbcdc79330aebb7786d)), it now works (although it is needed to completely remove it instead of just update `texlive2023-bin`), and even better, `texlive2024-bin` was packaged ([b229d44](https://github.com/void-linux/void-packages/commit/b229d44b72c6afd082fbef65c7014e2284cf9e17)) !

Thanks a lot :)
