### ISSUE TITLE
libgfortran has unresolved dependency

### ISSUE THREAD

**Issue by tfcolin** [void-linux/void-packages#49409]
### Is this a new report?

Yes

### System Info

Void 6.6.16_1 x86_64-musl GenuineIntel/VM uptodate rFFFF

### Package(s) Affected

libgfortran-12.2.0_4

### Expected behaviour

Install some math packages: blas, lapack, R etc. ,

or

install package libgfortran which is a dependence of the above math packages.

### Actual behaviour

The following is printed on the terminal: 

libgcc-12.2.0_4 in transaction breaks installed pkg `libstdc++-13.2.0_2'
Transaction aborted due to unresolved dependencies.

### Steps to reproduce

xbps-install libgfortran 

or

xbps-install blas lapack R

**Comment by oreo639** [comment]
libgfortran-12.2.0_4 does not exist in the repositories.
What mirror are you using?
What happens if you do `xbps-install -S libgfortran`?

**Comment by tfcolin** [comment]
Solved this problem after I fallback to the official mirror. Thanks. 

The malfunction occurred on this mirror: 

https://repo.jing.rocks/voidlinux/
