### ISSUE TITLE
Openbox becoming unusable? 

### ISSUE THREAD

**Issue by johnny-mac** [void-linux/void-packages#4941]
Has anyone else noticed for network-manager-applet, blueman, and a few other icons(power managers, etc) get messed up when using openbox? I first thought it was LXDE / lxpanel, but then I tried XFCE, and that's when I noticed that if I use openbox, I get the same kind of problems. Does anyone know where openbox's active development is now taking place? Looks like the main github repo is dead.

**Comment by biopsin** [comment]
Sadly no active, but https://github.com/joshdowding/openbox/commits/master has some fixes, unshure if it helps

**Comment by knusbaum** [comment]
I don't think this is an openbox issue. I've been dealing with this on i3 for a few months now. 
Best I can tell, this is some odd GTK issue.

Here are some links I've found:
https://github.com/i3/i3/issues/2325#issuecomment-439568765
https://forum.manjaro.org/t/i3status-system-tray-icons-messed-up-after-update/52987

**Comment by knusbaum** [comment]
@travankor That's what I was hoping, but I haven't looked at how to use xbps-alternatives yet.

**Comment by travankor** [comment]
Can you see if the already packaged `gtk3-nocsd` does anything? This seems like the most important part from the whole mushrooms patchset.

**Comment by steinex** [comment]
To workaround this for i3, a solution is to use i3-gaps and start i3bar with `-t`. Just saying.

**Comment by knusbaum** [comment]
@travankor Just installing `gtk3-nocsd` does not appear to have helped anything.

**Comment by paoloschi** [comment]
> Just installing `gtk3-nocsd` does not appear to have helped anything.

to work it needs these lines in `.xinitrc` , if you not already done that...

```
export GTK_CSD="0"
export LD_PRELOAD="/usr/lib/libgtk3-nocsd.so.0"
```

**Comment by knusbaum** [comment]
I tried that with no success. Was starting i3 with startx.
