### ISSUE TITLE
Package request: fritzing

### ISSUE THREAD

**Issue by U2C9727A4** [void-linux/void-packages#49544]
### Package name

fritzing

### Package homepage

https://github.com/fritzing/fritzing-app

### Description

Fritzing is an electronics design and simulation software.

I know fritzing is already a package in the repos, but it is way too old. the newer >1.0.0 versions are available on the develop branch. Nixpkgs unstable has a >1.0.0 package of fritzing, it may be useful to read that and make a void linux port of it.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by MIvanchev** [comment]
@U2C9727A4 Can you please show me where the source code for the >1.0.0 versions is located?

**Comment by classabbyamp** [comment]
it's in the same place, they just stopped tagging

https://github.com/fritzing/fritzing-app/issues/4086

**Comment by MIvanchev** [comment]
I see, well that's a very odd thing so maybe we should wait until they actually tag something again. To prevent someone releasing 1.x.y a couple of times. for example.

**Comment by 0x5c** [comment]
From other threads online, upstream indicates not wanting to offer Fritzing "for free" anymore[^1][^2][^3], with many justifications like "development sustainability"[^1][^2][^3], and also resisted for quite some time the idea of even syncing the code on Github for each releases[^1][^2][^3]. They also express wanting not to publicly develop on Github anymore for reason of "excessive charges" for "CI"[^2][^3] and "transactions"[^3], and instead have a private repository somewhere else. The "charges" thing is very strange considering public Github repos are the only ones getting free CI, and more than enough of it to power even massive high-frequency repos like [this one](https://github.com/void-linux/void-packages).

As to the "git sync", the code published on git is untagged, and seemingly would not compile a binary of the current version (latest version information it contains is a beta `*.*.*b` number).


[^1]: https://github.com/fritzing/fritzing-app/issues/4070
[^2]: https://forum.fritzing.org/t/can-t-find-source-code/19723
[^3]: https://forum.fritzing.org/t/just-thinking-fritzing-is-actually-not-opensource-anymore/22861

**Comment by classabbyamp** [comment]
Please don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.
