### ISSUE TITLE
lxd-to-incus fails on void linux

### ISSUE THREAD

**Issue by cmspam** [void-linux/void-packages#49542]
### Is this a new report?

Yes

### Package(s) Affected

incus-0.5.1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/lxc/incus/issues/625
https://github.com/lxc/incus/pull/511

### Expected behaviour

The server should be found

### Actual behaviour

"Error: No target server could be found"

### Steps to reproduce

void linux support was added to incus 0.6 upstream, but incus version is stuck at 0.5.1.
This PR updates incus to 0.6 and fixes the issue, but remains unmerged as of yet:
https://github.com/void-linux/void-packages/pull/49265

**Comment by ahesford** [comment]
The fact that the version packaged by Void lacks features found in later versions isn't a bug, and we have mechanisms to track outdated versions that don't require opening issues. In fact, filing issues to complain of outdated packages just distracts maintainers and buries real issues m, so please refrain from doing so in the future.
