### ISSUE TITLE
`sysstat` blocks `fcron` running cron.hourly

### ISSUE THREAD

**Issue by Clos3y** [void-linux/void-packages#49553]
### Is this a new report?

Yes

### System Info

Void 6.6.22_1 x86_64 AuthenticAMD notuptodate rrrmFFFF

### Package(s) Affected

sysstat-12.7.2_1, fcron-3.3.1_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No, not that I can see

### Expected behaviour

`fcron` runs all scripts in `/etc/cron.hourly`

### Actual behaviour

`fcron` runs all scripts alphabetically up to `sysstat`. This process does not terminate, locking `fcron` and preventing the execution of files starting with letters after 's' in `/etc/cron.hourly`.

### Steps to reproduce

0. Install `sysstat`, `fcron`, and setup the `fcron` service and systab crontab.
1. Create a script in `/etc/cron.hourly`.
2. If it comes before 'sysstat' alphabetically, it will be executed when the systab is set to run hourly. If it comes after, it will not execute until around fifty minutes after due to `sysstat` locking.

**Comment by classabbyamp** [comment]
probably caused by https://github.com/sysstat/sysstat/commit/e6592328c3d676a0727d5410ea505282f396bd5e, where an assumption is probably made that the cron daemon runs things in `cron.hourly` asynchronously

**Comment by Clos3y** [comment]
Hmm, adding `&` back in (and running `# fcrontab -z -u systab` followed by a reboot) doesn't fix the issue for me: it's still locked. `fcron` doesn't seem to care if you use `&`, it'll still lock. For example, I just tested 

    while true; do sleep 5; done &

in a test file in `/etc/cron.monthly`, reloaded the system crontab, and then forced `/etc/cron.monthly` to run with `fcrondyn`. `fcron` is still executing and is locked:

    2024-03-27T00:20:08.44950 cron.notice: Mar 27 00:20:08 fcron[3843]: Job '/usr/bin/run-parts /etc/cron.monthly' started for user systab (pid 3844)
    2024-03-27T00:20:46.30541 cron.warn: Mar 27 00:20:46 fcron[1022]:     process already running: systab's '/usr/bin/run-parts /etc/cron.monthly'

Perhaps this is an `fcron` issue specifically?

**Comment by classabbyamp** [comment]
then yeah it's probably fcron. might be interesting to check how another cron daemon reacts to this

**Comment by Clos3y** [comment]
I've tested with `cronie`: if you add the `&` to the script, `cronie` has no problem and will execute the rest. But in its current state without the `&`, the script will lock `cronie` too.

So I think a solution might be to patch `/etc/cron.hourly/sysstat` to reinclude the `&`, but I appreciate the Void ethos is to have upstream fix these things.

**Comment by leahneukirchen** [comment]
Surely cronie runs all jobs in parallel?

**Comment by leahneukirchen** [comment]
But perhaps sysstat should use a /etc/cron.d file, as run-parts from 0hourly will run in sequence (by design).

So sysstat shouldn't be run from cron.hourly.

**Comment by Clos3y** [comment]
> Surely cronie runs all jobs in parallel?

Seemingly not. `cronie` and `fcron` call `run-parts` which, if you execute it on `/etc/cron.hourly`, will take 50 mins to finish due to `sysstat`'s current form.

> But perhaps sysstat should use a /etc/cron.d file, as run-parts from 0hourly will run in sequence (by design).
> 
> So sysstat shouldn't be run from cron.hourly.

Yeah that sounds sensible, so just change these to `etc/cron.d`?
https://github.com/void-linux/void-packages/blob/fc3f3c3707cc096e854dba26d80df1ac390bc411/srcpkgs/sysstat/template#L25-L26

**Comment by leahneukirchen** [comment]
I'm at it, let me test it locally.
