### ISSUE TITLE
widevine package broken?

### ISSUE THREAD

**Issue by Ilia1** [void-linux/void-packages#49595]
### Is this a new report?

Yes

### System Info

Void 6.6.22_1 x86_64 GenuineIntel notuptodate rrFFFFFF

### Package(s) Affected

chromium-widevine

### Expected behaviour

Install widevine library without chromium as dependency

### Actual behaviour

Package chromium-widevine depends from chromium and looks like not contain any library
```
xlocate  widevine
chromium-widevine-116.0.5845.96_1  /usr/share/licenses/chromium-widevine/LICENSE
```
Empty result for command
`xbps-query -f chromium-widevine-116.0.5845.96_1.x86_64.xbps `

### Steps to reproduce

1. xbps-install chromium-widevine
2. This install chromium as depends. But I don`t like install chromium. Library widewine need for example in mellow player.

**Comment by classabbyamp** [comment]
> Empty result for command `xbps-query -f chromium-widevine-116.0.5845.96_1.x86_64.xbps `

because there is no packaged named `chromium-widevine-116.0.5845.96_1.x86_64.xbps`, it's named `chromium-widevine` or `chromium-widevine-116.0.5845.96_1`

that said, there is only a licence file in that package

**Comment by classabbyamp** [comment]
it only contains the licence because the actual files are [downloaded at install-time](https://github.com/void-linux/void-packages/blob/master/srcpkgs/chromium-widevine/INSTALL)

**Comment by Ilia1** [comment]
What about chromium depends? If I`d like install only widevine lib.

**Comment by ahesford** [comment]
Configure XBPS to ignore chromium if you don't want to install it.
