### ISSUE TITLE
GIMP: ibus-rime not work in the text tool

### ISSUE THREAD

**Issue by imapproxy** [void-linux/void-packages#49605]
System info: 
Void 6.5.13_1 x86_64 GenuineIntel uptodate FFFF
xfce desktop (glibc), system all updated.

GIMP info: 2.10.36_1

Input method: 
ibus-rime-1.5.0_1 in ibus 1.5.28_4

Actual behaviour: 
Chinese incapable of being input in GIMP text tool.
Seemingly ibus-rime not triggered, as no response/effect to the switch between English and Chinese.

Expected behaviour:
Chinese can be input in GIMP text tool.
ibus-rime works normally in GIMP like elsewhere in the system. 

Does it exist in other distros?
At least not exist in Artixlinux, EndeavourOS.
GIMP works well with Chinese input in both the distros.

Does it exist for other non-english input methods in ibus?
At least not exist for Arabic and Russian in ibus, not all methods tested. 
Tried typing a few characters in GIMP text layer, the Arabic/Russian characters appeared in success.

Hi, not sure if it is a bug, but it's an itch that cannot be got rid of in daily use.
Much obliged if it be resolved.

**Comment by oreo639** [comment]
You need to install `ibus-gtk+` for ibus to work with gtk+ applications on X11.

**Comment by imapproxy** [comment]
@oreo639  Thanks so much, the help is truly appreciated. So efficacious, all at once it saved the brain and time. I will close this issue.
