### ISSUE TITLE
sysstat cron jobs do not run with fcron

### ISSUE THREAD

**Issue by ericjunkermann** [void-linux/void-packages#49623]
### Is this a new report?

Yes

### System Info

Void 6.6.21_1 x86_64 AuthenticAMD notuptodate hold rFFFF

### Package(s) Affected

sysstat-12.7.5_1 fcron-3.3.1_2

### Expected behaviour

The sysstat cron jobs (now in /etc/cron.d/sysstat) should run normally.

### Actual behaviour

The sysstat cron jobs do not run, and fcron reports an error that /etc/cron.hourly does not exist.

The latter is true because apparently the update of systat removed it (because it was not empty?).

The former is because fcron does not use /etc/cron.d - it contains a script **check_system_crontabs.sh** which is in fcron's upstream repository but is **NOT** distributed - see comments in that file for how to use it (if it was distributed!) - the comments do not say that it overwrites /var/spool/cron/systab.orig and the corresponding binary file which loses the hourly.cron , daily.cron ... which were previously there. Those interval files need to be somewhere else (/etc/fcrontab ?) so that they will still run.

### Steps to reproduce

See above - this is a state of affairs, not an action.

**Comment by Clos3y** [comment]
@leahneukirchen

**Comment by ahesford** [comment]
The fact that `fcron` doesn't support `/etc/cron.d` is a design decision, not a bug. We ship crontab snippets as a convenience, but users are expected to either use a cron daemon that supports them or else implement their own preferred approach to periodic execution.

If running a script we didn't distribute clobbered the system crontab that runs the rest of the scripts in `/etc/cron.*`, restore the file from the package and be more careful about running such scripts in the future.
