### ISSUE TITLE
Package request: nlohmann-json development package

### ISSUE THREAD

**Issue by Dakedres** [void-linux/void-packages#49665]
### Package name

nlohmann-json-devel

### Package homepage

https://github.com/nlohmann/json

### Description

nlohmann/json is a json library for modern C++

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/json-c++/template
