### ISSUE TITLE
inetutils-tftp: Fails to start, returns 1

### ISSUE THREAD

**Issue by Veyrdite** [void-linux/void-packages#4970]
### System

Void 4.17.6_1 x86_64 GenuineIntel uptodate rrrmmnFFFFFFFF
inetutils-tftp-1.9.4_9

### Problem

ftpd (provided bin) dies silently when you try to run it, regardless of the options provided.  Additionally the terminal is left in a semi-broken state (dash automatically fixes this, bash does not, 'reset' does not help).

```
# ftpd
# echo $?
1
# cat
cat: -: Resource temporarily unavailable
```

**Comment by jnbr** [comment]
`inetutils-tftpd` assumes `stdin` to be a socket and should be run under `inetutils-inetd`.
