### ISSUE TITLE
Package request: php-fileinfo

### ISSUE THREAD

**Issue by end3r-man** [void-linux/void-packages#49734]
### Package name

php-fileinfo

### Package homepage

https://www.php.net/

### Description

unable to find php-fileinfo in xbps repo and unable to install its manually

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by RotaryBoot58** [comment]
Isn't it an extension that can be activated in the php .ini file?

**Comment by classabbyamp** [comment]
@TinfoilSubmarine can we enable this?

**Comment by end3r-man** [comment]
> The php.ini file has an extension fileinfo in it but is commented. The documentation says it is enabled by default. enable that extension and see if everything works.
> 
> If everything works you should close your issue. else just reply and I can try to help you with your problem.

sorry, forgot to close the issue
