### ISSUE TITLE
An update to Vala can fix a currently present issue with a package

### ISSUE THREAD

**Issue by SpidFightFR** [void-linux/void-packages#49831]
### Is this a new report?

Yes

### System Info

Void 6.8.5_1 x86_64 AuthenticAMD uptodate rrmFFFFFFF

### Package(s) Affected

vala-0.56.14; gtksourceview5-5.10.0

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

A report exists at the upstream repo, this is where @meator (sorry for the ping) found the solution: https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/353

### Expected behaviour

The package should build.

### Actual behaviour

It doesn't build, gets this error:

<details><summary>Error.log</summary>

```
FAILED: gtksourceview/gtksourceview-5.vapi 
/usr/bin/vapigen --quiet --library=gtksourceview-5 --directory=/builddir/gtksourceview5-5.10.0/build/gtksourceview --pkg=gdk-pixbuf-2.0 --pkg=gio-2.0 --pkg=gtk4 --pkg=pango --pkg=cairo --metadatadir=/builddir/gtksourceview5-5.10.0/gtksourceview /builddir/gtksourceview5-5.10.0/build/gtksourceview/GtkSource-5.gir
GtkSource-5.gir:18586.7-18591.84: warning: Signal `GtkSource.View.smart_home_end' conflicts with property of the same name
GtkSource-5.gir:9812.7-9812.43: error: The type name `Gtk.AccessibleText' could not be found
GtkSource-5.gir:17230.7-17230.43: error: The type name `Gtk.AccessibleText' could not be found

```
</details>

The issue is fixable by **updating `vala` to version `0.56.16`**.
Further testing is advised.

### Steps to reproduce

1. `./xbps-src pkg -Q gtksourceview5`
2. dies :(

**Comment by oreo639** [comment]
Feel free to submit a PR.

**Comment by SpidFightFR** [comment]
> Feel free to submit a PR.

Right now i have many things to do.

I planned to finish updating meson, then update mesa.
If i can find some time, i'll do it afterwards, but nothing's set in the stone.

**Comment by oreo639** [comment]
Alright, no issue.
Also, just for sake of clarification, this issue in this case is outdated bindings: https://gitlab.gnome.org/GNOME/vala/-/commit/2fba23c9fcd7120a3a296d99138cbc611d11ef9f
