### ISSUE TITLE
gnu-efi-libs > 3.0.15 breaks gummiboot build

### ISSUE THREAD

**Issue by rbzchnadm** [void-linux/void-packages#49859]
### Is this a new report?

Yes

### System Info

Void 6.1.83_1 x86_64 GenuineIntel/VM notuptodate rFFF

### Package(s) Affected

gummiboot-48.1_8

### Expected behaviour

Package must be built successfully

### Actual behaviour

```
  CC       src/setup/gummiboot-efivars.o
In file included from /usr/include/efi/efi.h:46,
                 from src/efi/pefile.c:17:
/usr/include/efi/x86_64/efibind.h:99:10: fatal error: stddef.h: No such file or directory
   99 | #include <stddef.h>
      |          ^~~~~~~~~~
In file included from /usr/include/efi/efi.h:46,
                 from src/efi/graphics.c:20:
/usr/include/efi/x86_64/efibind.h:99:10: fatal error: stddef.h: No such file or directory
   99 | #include <stddef.h>
      |          ^~~~~~~~~~
In file included from /usr/include/efi/efi.h:46,
                 from src/efi/util.c:18:
/usr/include/efi/x86_64/efibind.h:99:10: fatal error: stddef.h: No such file or directory
   99 | #include <stddef.h>
      |          ^~~~~~~~~~
In file included from /usr/include/efi/efi.h:46,
                 from src/efi/console.c:18:
/usr/include/efi/x86_64/efibind.h:99:10: fatal error: stddef.h: No such file or directory
   99 | #include <stddef.h>
      |          ^~~~~~~~~~
```

### Steps to reproduce

1. xbps-src -N pkg gummiboot-efistub

---

1. Reverting back gnu-efi-libs to version 3.0.15
2.  xbps-src -N pkg gummiboot-efistub

**Comment by classabbyamp** [comment]
related: https://git.alpinelinux.org/aports/tree/main/gummiboot/APKBUILD#n30

but alpine's solution doesn't appear to work on musl (and it wouldn't work on glibc because stddef.h is provided by gcc, not glibc)

**Comment by classabbyamp** [comment]
gcc provides it but there's `-nostdinc` in the cmdline so I don't think it adds that header automatically
