### ISSUE TITLE
openshot won't start

### ISSUE THREAD

**Issue by fdziarmagowski** [void-linux/void-packages#49973]
### Is this a new report?

Yes

### System Info

Void 6.8.7_1 x86_64 AuthenticAMD uptodate rrmFFFFF

### Package(s) Affected

openshot-3.1.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Problem is Void Linux specific

### Expected behaviour

Should start and run.

### Actual behaviour

Won't start as libopenshot (runtime dependency) is too old. Generates long runtime exception.

As from openshot 3.1.1 release notes:
> min libopenshot dependency to 0.3.2

Locally rebuilding with xbps-src and installing libopenshot 0.3.2 solves the problem

Eventually openshot template is missing appropriate dependency like libopenshot>=0.3.2

### Steps to reproduce

Start the application.

**Comment by biopsin** [comment]
@fdziarmagowski 
is the update working for you?

**Comment by fdziarmagowski** [comment]
@biopsin yes, it works as expected now. Thanks for fixing!
