### ISSUE TITLE
nvidia-powerd service is not working on nvidia driver versions newer than 535.154.05

### ISSUE THREAD

**Issue by xAlpharax** [void-linux/void-packages#50054]
### Is this a new report?

Yes

### System Info

Void 6.8.7_1 x86_64

### Package(s) Affected

nvidia-*

### Expected behaviour

The NVIDIA driver ships with a service for dynamically changing the power cap the GPU has based on load (crucial for MAX Q GPUs). This service is called nvidia-powerd, and it should be up when the system boots.

### Actual behaviour

In driver versions newer than 535.154.05 (see https://github.com/void-linux/void-packages/commits/master/srcpkgs/nvidia for the versions that I am talking about) the nvidia-powerd service is down and refuses to start, or better said, it starts and immediately crashes/stops (what I believe happens)

### Steps to reproduce

1. Make sure to have a version of nvidia newer than 535.154.05
2. Enable the nvidia-powerd service (on GPUs other than MAX Q variants it won't change the power cap, so there isn't supposed to be an effect of it being up or down but you can still see in the following step whether it is working correctly or not)
3. Run `sudo sv status nvidia-powerd` and see that the service is down

**Comment by classabbyamp** [comment]
@abenson

**Comment by xAlpharax** [comment]
I made a rollback branch on my fork to version 535.154.05 (https://github.com/xAlpharax/void-packages/tree/nvidia-powerd-rollback), as this fixes the problem for me (and possibly others). However, I'd like to see if we can make the service work in newer versions.

**Comment by abenson** [comment]
Yeah, I noticed yesterday it had been crashing on my laptop. I'm looking into it.

**Comment by abenson** [comment]
What laptop and GPU model is it?

**Comment by abenson** [comment]
It looks like it might be a `dbus` issue:

```
2024-04-27T22:30:52.77406 daemon.info: Apr 27 17:30:52 /usr/bin/nvidia-powerd[5534]: nvidia-powerd version:1.0(build 1)
2024-04-27T22:30:52.77763 daemon.err: Apr 27 17:30:52 /usr/bin/nvidia-powerd[5534]: Error requesting D-Bus name (Connection ":1.529" is not allowed to own the service "nvidia.powerd.server" due to security policies in the configuration file)
2024-04-27T22:30:52.77770 daemon.err: Apr 27 17:30:52 /usr/bin/nvidia-powerd[5534]: Failed to acquire D-Bus name ((null))
```

I was missing

**Comment by abenson** [comment]
```
GPU 00000000:01:00.0
    GPU Power Readings
        Power Draw                        : 8.38 W
        Current Power Limit               : 100.00 W
        Requested Power Limit             : N/A
        Default Power Limit               : 80.00 W
        Min Power Limit                   : 5.00 W
        Max Power Limit                   : 125.00 W
```

At least on my laptop, it's getting 100W instead of sticking at 80W. I'm sure there's something else I'm missing to get it go the full 125W.

**Comment by xAlpharax** [comment]
> What laptop and GPU model is it?

Acer Nitro 5 2021 with RTX 3070 MAX Q variant (80 watts to 100 watts). `nvidia-smi` isn't able, at least on this model, to statically change the power limit via `nvidia-smi -pl 100` (https://github.com/NVIDIA/open-gpu-kernel-modules/issues/483) so my only viable solution is with the nvidia-powerd service.

**Comment by xAlpharax** [comment]
> It looks like it might be a `dbus` issue:
> 
> ```
> 2024-04-27T22:30:52.77406 daemon.info: Apr 27 17:30:52 /usr/bin/nvidia-powerd[5534]: nvidia-powerd version:1.0(build 1)
> 2024-04-27T22:30:52.77763 daemon.err: Apr 27 17:30:52 /usr/bin/nvidia-powerd[5534]: Error requesting D-Bus name (Connection ":1.529" is not allowed to own the service "nvidia.powerd.server" due to security policies in the configuration file)
> 2024-04-27T22:30:52.77770 daemon.err: Apr 27 17:30:52 /usr/bin/nvidia-powerd[5534]: Failed to acquire D-Bus name ((null))
> ```
> 
> I was missing the dbus configuration for it. It seems to be working now, and I will be pushing the change in #49897.

Thank you for identifying the problem.

**Comment by xAlpharax** [comment]
> 
> ```
> GPU 00000000:01:00.0
>     GPU Power Readings
>         Power Draw                        : 8.38 W
>         Current Power Limit               : 100.00 W
>         Requested Power Limit             : N/A
>         Default Power Limit               : 80.00 W
>         Min Power Limit                   : 5.00 W
>         Max Power Limit                   : 125.00 W
> ```
> 
> At least on my laptop, it's getting 100W instead of sticking at 80W. I'm sure there's something else I'm missing to get it go the full 125W.

Hmmm.. Are you sure it has enough load when checking the max power limit? For me, at least, it changes to the max when i get into `Max Performance Mode` in `nvidia-settings` or when actual compute load is happening that signals to the service it needs more power. Check with `nvtop`.

**Comment by xAlpharax** [comment]
> 
> ```
> GPU 00000000:01:00.0
>     GPU Power Readings
>         Power Draw                        : 8.38 W
>         Current Power Limit               : 100.00 W
>         Requested Power Limit             : N/A
>         Default Power Limit               : 80.00 W
>         Min Power Limit                   : 5.00 W
>         Max Power Limit                   : 125.00 W
> ```
> 
> At least on my laptop, it's getting 100W instead of sticking at 80W. I'm sure there's something else I'm missing to get it go the full 125W.

you may want to look into this, it seems also related to nvidia-smi and nvidia-powerd wattage constraints https://github.com/NVIDIA/open-gpu-kernel-modules/issues/483#issuecomment-1890415595

**Comment by abenson** [comment]
There was no load on the GPU at the time.

**Comment by xAlpharax** [comment]
> There was no load on the GPU at the time. 

Oh, alright, so you reached your 125 Watts. Then, I guess this problem is fixed now?

**Comment by abenson** [comment]
I believe so, I merged the fix with the new version of the driver. Let me know if there are any issues.

**Comment by xAlpharax** [comment]
Sure, unholding the nvidia package on my machine right now and testing it.

**Comment by xAlpharax** [comment]
> I believe so, I merged the fix with the new version of the driver. Let me know if there are any issues.

Forgot to come back to this, it was all great and managed to be fixed perfectly. Thank you! I also learned a lot about how nvidia is packaged. Kudos.
