### ISSUE TITLE
Musikcube: segfaults 

### ISSUE THREAD

**Issue by varuld** [void-linux/void-packages#50063]
### Is this a new report?

Yes

### System Info

Void 6.6.27_1 x86_64-musl

### Package(s) Affected

musikcube-3.0.0_3-musl

### Expected behaviour

Should open the musikcube program :/

### Actual behaviour

The program segfaults when started. I've tested the behavior on a glibc system and have not been able to reproduce it, and a such it seems to be musl related  

### Steps to reproduce

__On a musl system__:
1. install musikcube
2. try to run musikcube from a terminal
3. get segfault

**Comment by sgn** [comment]
Can you get a backtrace?

**Comment by varuld** [comment]
I've tried running it under gdb by following this (https://wiki.ubuntu.com/Backtrace#Generation) guide and I get:
"
GNU gdb (GDB) 14.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from musikcube...
(No debugging symbols found in musikcube)
[?2004h(gdb) [7mhandle SIG33 pass nostop noprint[27m
[C[C[C[C[C[Chandle SIG33 pass nostop noprint
[?2004l
Signal        Stop	Print	Pass to program	Description
SIG33         No	No	Yes		Real-time event 33
[?2004h(gdb) [7mset pagination 0[27m
[C[C[C[C[C[Cset pagination 0
[?2004l
[?2004h(gdb) run
[?2004l
Starting program: /usr/bin/musikcube 
[New LWP 14091]
[New LWP 14092]
[New LWP 14093]
[New LWP 14094]
[New LWP 14095]
[LWP 14094 exited]
[?1049h[22;0;0t[1;104r(B[m[4l[?7h[?1h=[H[2J[?25l[?1000h[New LWP 14096]
[New LWP 14097]
[New LWP 14098]
[New LWP 14099]
[New LWP 14100]
[LWP 14099 exited]
[LWP 14098 exited]
[LWP 14100 exited]
[LWP 14097 exited]

Thread 1 "musikcube" received signal SIGSEGV, Segmentation fault.
__strchrnul (s=0x1 <error: Cannot access memory at address 0x1>, c=c@entry=59) at src/string/strchrnul.c:19
warning: 19	src/string/strchrnul.c: No such file or directory
[?2004h[?2004l
[?2004h(gdb) backtrace full
[?2004l
#0  __strchrnul (s=0x1 <error: Cannot access memory at address 0x1>, c=c@entry=59) at src/string/strchrnul.c:19
        w = <optimized out>
        k = <optimized out>
#1  0x00007ffff7fb3f48 in strchr (s=<optimized out>, c=59) at src/string/strchr.c:5
        r = <optimized out>
#2  0x00007ffff6f0d415 in std::locale::_Impl::_Impl(char const*, unsigned long) () from /lib/libstdc++.so.6
No symbol table info available.
#3  0x00007ffff6f0de4d in std::locale::locale(char const*) () from /lib/libstdc++.so.6
No symbol table info available.
#4  0x00005555556efd2b in ?? ()
No symbol table info available.
#5  0x00005555556f0285 in musik::cube::DirectoryAdapter::DirectoryAdapter() ()
No symbol table info available.
#6  0x00005555556ca529 in musik::cube::LocalLibrarySettingsLayout::LocalLibrarySettingsLayout() ()
No symbol table info available.
#7  0x00005555556e5484 in musik::cube::SettingsLayout::InitializeWindows() ()
No symbol table info available.
#8  0x00005555556e8418 in musik::cube::SettingsLayout::SettingsLayout(cursespp::App&, std::shared_ptr<musik::core::library::MasterLibrary>, musik::core::audio::PlaybackService&) ()
No symbol table info available.
#9  0x00005555556d46a7 in musik::cube::MainLayout::MainLayout(cursespp::App&, musik::cube::ConsoleLogger*, musik::core::audio::PlaybackService&, std::shared_ptr<musik::core::library::MasterLibrary>) ()
No symbol table info available.
#10 0x00005555556a8dfe in std::__shared_ptr<musik::cube::MainLayout, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, cursespp::App&, musik::cube::ConsoleLogger*&, musik::core::audio::PlaybackService&, std::shared_ptr<musik::core::library::MasterLibrary>&>(std::_Sp_alloc_shared_tag<std::allocator<void> >, cursespp::App&, musik::cube::ConsoleLogger*&, musik::core::audio::PlaybackService&, std::shared_ptr<musik::core::library::MasterLibrary>&) ()
No symbol table info available.
#11 0x000055555562b249 in main ()
No symbol table info available.
[?2004h(gdb) infor[K registers
[?2004l
rax            0x0                 0
rbx            0x1                 1
rcx            0x3b                59
rdx            0x0                 0
rsi            0x3b                59
rdi            0x1                 1
rbp            0x7ffff7ffba20      0x7ffff7ffba20 <buf>
rsp            0x7fffffffc820      0x7fffffffc820
r8             0x3d3d3d3d3d3d3d3d  4412750543122677053
r9             0x8080808080808080  -9187201950435737472
r10            0xfefefefefefefeff  -72340172838076673
r11            0x246               582
r12            0x0                 0
r13            0x3d                61
r14            0x1                 1
r15            0x555555bf4020      93824999178272
rip            0x7ffff7fb3f78      0x7ffff7fb3f78 <__strchrnul+24>
eflags         0x10202             [ IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
fs_base        0x55555583e078      93824995287160
gs_base        0x0                 0
[?2004h(gdb) x/16 $pc
[?2004l
0x7ffff7fb3f78 <__strchrnul+24>:	-2080131569	-1400631360	956301312	-1534849080
0x7ffff7fb3f88 <__strchrnul+40>:	1207959552	-167656573	-462092349	16891720
0x7ffff7fb3f98 <__strchrnul+56>:	16843009	1665925377	327895233	-2139047607
0x7ffff7fb3fa8 <__strchrnul+72>:	-2139062144	256671872	-1991718993	-131512112
[?2004h(gdb) thredd[Kad[K[K[Kad apply all backtrace
[?2004l
Thread 7 (LWP 14096 "musikcube"):
#0  unlock (lk=0x7ffff7ffbaf8 <mal+56>) at src/malloc/malloc.c:40
#1  unlock_bin (i=<optimized out>) at src/malloc/malloc.c:53
#2  malloc (n=<optimized out>) at src/malloc/malloc.c:324
#3  0x00007ffff6ef519c in operator new(unsigned long) () from /lib/libstdc++.so.6
#4  0x00007ffff754f77a in ?? () from /lib/libmusikcore.so
#5  0x00007ffff75512be in musik::core::Preferences::GetBool(char const*, bool) () from /lib/libmusikcore.so
#6  0x00007ffff7430199 in void musik::core::PluginFactory::QueryInterface<musik::core::sdk::IAnalyzer, musik::core::PluginFactory::ReleaseDeleter<musik::core::sdk::IAnalyzer> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (musik::core::sdk::IPlugin*, std::shared_ptr<musik::core::sdk::IAnalyzer>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>) () from /lib/libmusikcore.so
#7  0x00007ffff7427ac1 in musik::core::Indexer::RunAnalyzers() () from /lib/libmusikcore.so
#8  0x00007ffff7429318 in musik::core::Indexer::FinalizeSync(musik::core::Indexer::SyncContext const&) () from /lib/libmusikcore.so
#9  0x00007ffff742b154 in musik::core::Indexer::ThreadLoop() () from /lib/libmusikcore.so
#10 0x00007ffff6f234b3 in ?? () from /lib/libstdc++.so.6
#11 0x00007ffff7fb7c0e in start (p=0x7ffff2523790) at src/thread/pthread_create.c:195
#12 0x00007ffff7fc4b5b in __clone () at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC

Thread 6 (LWP 14095 "musikcube"):
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
#1  0x00007ffff7fb6d0f in __syscall_cp_c (nr=202, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=0) at src/thread/pthread_cancel.c:33
#2  0x00007ffff7fb5fef in __futex4_cp (to=<optimized out>, val=2, op=128, addr=0x7ffff2549564) at src/thread/__timedwait.c:24
#3  __timedwait_cp (addr=addr@entry=0x7ffff2549564, val=val@entry=2, clk=clk@entry=1, at=at@entry=0x0, priv=128, priv@entry=1) at src/thread/__timedwait.c:52
#4  0x00007ffff7fb71d7 in __pthread_cond_timedwait (c=0x555555ab64b0, m=0x555555ab6478, ts=0x0) at src/thread/pthread_cond_timedwait.c:100
#5  0x00007ffff742d89b in asio::detail::scheduler::do_run_one(asio::detail::conditionally_enabled_mutex::scoped_lock&, asio::detail::scheduler_thread_info&, std::error_code const&) () from /lib/libmusikcore.so
#6  0x00007ffff74b5d71 in ?? () from /lib/libmusikcore.so
#7  0x00007ffff74c6385 in asio::detail::posix_thread::func<asio::detail::resolver_service_base::work_scheduler_runner>::run() () from /lib/libmusikcore.so
#8  0x00007ffff742c1ff in asio_detail_posix_thread_function () from /lib/libmusikcore.so
#9  0x00007ffff7fb7c0e in start (p=0x7ffff2549790) at src/thread/pthread_create.c:195
#10 0x00007ffff7fc4b5b in __clone () at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC

Thread 4 (LWP 14093 "musikcube"):
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
#1  0x00007ffff7fb6d0f in __syscall_cp_c (nr=202, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=0) at src/thread/pthread_cancel.c:33
#2  0x00007ffff7fb5fef in __futex4_cp (to=<optimized out>, val=2, op=128, addr=0x7ffff25955d4) at src/thread/__timedwait.c:24
#3  __timedwait_cp (addr=addr@entry=0x7ffff25955d4, val=val@entry=2, clk=clk@entry=0, at=at@entry=0x0, priv=128, priv@entry=1) at src/thread/__timedwait.c:52
#4  0x00007ffff7fb71d7 in __pthread_cond_timedwait (c=0x555555aabe18, m=0x555555aafe10, ts=0x0) at src/thread/pthread_cond_timedwait.c:100
#5  0x00007ffff73d27a6 in void std::_V2::condition_variable_any::wait<std::unique_lock<std::recursive_mutex> >(std::unique_lock<std::recursive_mutex>&) () from /lib/libmusikcore.so
#6  0x00007ffff7449668 in musik::core::library::RemoteLibrary::GetNextQuery() () from /lib/libmusikcore.so
#7  0x00007ffff744a4e8 in musik::core::library::RemoteLibrary::ThreadProc() () from /lib/libmusikcore.so
#8  0x00007ffff6f234b3 in ?? () from /lib/libstdc++.so.6
#9  0x00007ffff7fb7c0e in start (p=0x7ffff2595790) at src/thread/pthread_create.c:195
#10 0x00007ffff7fc4b5b in __clone () at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC

Thread 3 (LWP 14092 "musikcube"):
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
#1  0x00007ffff7fb6d0f in __syscall_cp_c (nr=202, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=0) at src/thread/pthread_cancel.c:33
#2  0x00007ffff7fb5fef in __futex4_cp (to=<optimized out>, val=2, op=128, addr=0x7ffff25bb604) at src/thread/__timedwait.c:24
#3  __timedwait_cp (addr=addr@entry=0x7ffff25bb604, val=val@entry=2, clk=clk@entry=0, at=at@entry=0x0, priv=128, priv@entry=1) at src/thread/__timedwait.c:52
#4  0x00007ffff7fb71d7 in __pthread_cond_timedwait (c=0x555555a7ea20, m=0x555555a7eb70, ts=0x0) at src/thread/pthread_cond_timedwait.c:100
#5  0x00007ffff7436eaa in musik::core::library::LocalLibrary::GetNextQuery() () from /lib/libmusikcore.so
#6  0x00007ffff7437118 in musik::core::library::LocalLibrary::ThreadProc() () from /lib/libmusikcore.so
#7  0x00007ffff6f234b3 in ?? () from /lib/libstdc++.so.6
#8  0x00007ffff7fb7c0e in start (p=0x7ffff25bb790) at src/thread/pthread_create.c:195
#9  0x00007ffff7fc4b5b in __clone () at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC

Thread 2 (LWP 14091 "musikcube"):
#0  __cp_end () at src/thread/x86_64/syscall_cp.s:29
#1  0x00007ffff7fb6d0f in __syscall_cp_c (nr=202, u=<optimized out>, v=<optimized out>, w=<optimized out>, x=<optimized out>, y=<optimized out>, z=0) at src/thread/pthread_cancel.c:33
#2  0x00007ffff7fb5fef in __futex4_cp (to=<optimized out>, val=2, op=128, addr=0x7ffff77b99c4) at src/thread/__timedwait.c:24
#3  __timedwait_cp (addr=addr@entry=0x7ffff77b99c4, val=val@entry=2, clk=clk@entry=0, at=at@entry=0x0, priv=128, priv@entry=1) at src/thread/__timedwait.c:52
#4  0x00007ffff7fb71d7 in __pthread_cond_timedwait (c=0x555555a22230, m=0x555555a22260, ts=0x0) at src/thread/pthread_cond_timedwait.c:100
#5  0x00007ffff73cd757 in ?? () from /lib/libmusikcore.so
#6  0x00007ffff6f234b3 in ?? () from /lib/libstdc++.so.6
#7  0x00007ffff7fb7c0e in start (p=0x7ffff77b9aa8) at src/thread/pthread_create.c:195
#8  0x00007ffff7fc4b5b in __clone () at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC

Thread 1 (LWP 14086 "musikcube"):
#0  __strchrnul (s=0x1 <error: Cannot access memory at address 0x1>, c=c@entry=59) at src/string/strchrnul.c:19
#1  0x00007ffff7fb3f48 in strchr (s=<optimized out>, c=59) at src/string/strchr.c:5
#2  0x00007ffff6f0d415 in std::locale::_Impl::_Impl(char const*, unsigned long) () from /lib/libstdc++.so.6
#3  0x00007ffff6f0de4d in std::locale::locale(char const*) () from /lib/libstdc++.so.6
#4  0x00005555556efd2b in ?? ()
#5  0x00005555556f0285 in musik::cube::DirectoryAdapter::DirectoryAdapter() ()
#6  0x00005555556ca529 in musik::cube::LocalLibrarySettingsLayout::LocalLibrarySettingsLayout() ()
#7  0x00005555556e5484 in musik::cube::SettingsLayout::InitializeWindows() ()
#8  0x00005555556e8418 in musik::cube::SettingsLayout::SettingsLayout(cursespp::App&, std::shared_ptr<musik::core::library::MasterLibrary>, musik::core::audio::PlaybackService&) ()
#9  0x00005555556d46a7 in musik::cube::MainLayout::MainLayout(cursespp::App&, musik::cube::ConsoleLogger*, musik::core::audio::PlaybackService&, std::shared_ptr<musik::core::library::MasterLibrary>) ()
#10 0x00005555556a8dfe in std::__shared_ptr<musik::cube::MainLayout, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<void>, cursespp::App&, musik::cube::ConsoleLogger*&, musik::core::audio::PlaybackService&, std::shared_ptr<musik::core::library::MasterLibrary>&>(std::_Sp_alloc_shared_tag<std::allocator<void> >, cursespp::App&, musik::cube::ConsoleLogger*&, musik::core::audio::PlaybackService&, std::shared_ptr<musik::core::library::MasterLibrary>&) ()
#11 0x000055555562b249 in main ()
[?2004h(gdb) quit
[?2004l
[?2004hA debugging session is active.

	Inferior 1 [process 14086] will be killed.

Quit anyway? (y or n) y
[?2004l
"

**Comment by sgn** [comment]
Can you build and test this PR https://github.com/void-linux/void-packages/pull/50144 ?

**Comment by varuld** [comment]
I've build and tested it, and it works
