### ISSUE TITLE
nomacs: error while loading shared libraries: libquazip5.so.1

### ISSUE THREAD

**Issue by basiliscos** [void-linux/void-packages#5011]
### System

-bash-4.4# xuname 
Void 4.18.19_1 x86_64 GenuineIntel uptodate rrrmFFF

* package:  
nomacs-3.12_1

### Expected behavior

app start

### Actual behavior

exits with error

```
nomacs: error while loading shared libraries: libquazip5.so.1: cannot open shared object file: No such file or directory
```

**Comment by maxice8** [comment]
Works fine here

**Comment by basiliscos** [comment]
I just updated system (`xbps-install -Suv`) and still get the error

**Comment by Johnnynator** [comment]
Can you try to run `xbps-install -f quazip`. I suspect that xbps-install did drop some files when updating quazip-qt5 -> quazip.

**Comment by maxice8** [comment]
Seems to be solved
