### ISSUE TITLE
Package request: catnip

### ISSUE THREAD

**Issue by Yakumo-Yukari** [void-linux/void-packages#50139]
### Package name

catnip

### Package homepage

https://github.com/iinsertNameHere/catnip

### Description

It is quite customizable and has possibilities to alter the names and colors of the statistics.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by tranzystorekk** [comment]
See similar neofetch-like package request: https://github.com/void-linux/void-packages/issues/38293, this is unlikely to be accepted.

**Comment by MechDR** [comment]
Would just a working template suffice?
