### ISSUE TITLE
hydrus desktop file

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#50193]
### Is this a new report?

Yes

### System Info

Void 6.6.30_1 x86_64 GenuineIntel uptodate hold rFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

### Package(s) Affected

hydrus-573_1

### Expected behaviour

Updating doesn't produce any warning.

### Actual behaviour

Updating produces the following message:
```
Updating MIME database...
Could not parse file "usr/share/applications/hydrus.desktop": No such file or directory
```

### Steps to reproduce

1. Update
2. Install hydrus

**Comment by classabbyamp** [comment]
```
$ xls hydrus | rg desktop
/usr/lib/hydrus/static/io.github.hydrusnetwork.hydrus.desktop
/usr/share/applications/hydrus.desktop -> ../../lib/hydrus/static/hydrus.desktop
```
https://github.com/void-linux/void-packages/blob/858b9e94276078069f64f828975f1a62853e96e4/srcpkgs/hydrus/template#L41-L42
symlink is wrong

**Comment by Eloitor** [comment]
I'm attempting to use `vinstall` instead here. I'll make a PR at some point.
