### ISSUE TITLE
vte3 and SIXEL image support

### ISSUE THREAD

**Issue by paoloschi** [void-linux/void-packages#50220]
```
/usr/bin/vte-2.91 --version
VTE Application 0.76.0 +BIDI +GNUTLS +ICU -SYSTEMD
```
Since **libsixel** is in the repository, would it be the case to have the **vte3** package compiled to support it or is it not desirable for some reason?

**Comment by sgn** [comment]
SIXEL support was changed multiple time in vte3 and demned unstable by vte themselves https://gitlab.gnome.org/GNOME/vte/-/issues/253,
They eventually removed sixel support in https://gitlab.gnome.org/GNOME/vte/-/commit/e264c6ed36c1a5ada131d5ee781645fff4ce9e78

So, no vte does NOT support sixel!
