### ISSUE TITLE
Package request: dracut-ng (either replacing dracut or as a separate package)

### ISSUE THREAD

**Issue by Katnjia** [void-linux/void-packages#50296]
### Package name

dracut / dracut-ng

### Package homepage

https://github.com/dracut-ng/dracut-ng/

### Description

There's been no real development in the main dracut repo since December last year and the repo is effectively dead.

Previous issue on this: void-linux/void-packages/issues/49750

If there's a specific reason not to move to the new repo for the dracut package, I suggest adding an *-ng version.

### Does the requested package meet the package requirements?

System, Required

### Is the requested package released?

No

**Comment by zdykstra** [comment]
My plan is to switch the Dracut packages to use the dracut-ng upstream. I'm not sure exactly when that will happen; some time in the near future, though.
