### ISSUE TITLE
Waterfall builds for x64 Glibc failed during kde5

### ISSUE THREAD

**Issue by SpidFightFR** [void-linux/void-packages#50302]
Hello everyone i hope you're doing great.

This morning i noticed that builds for x64 after the plasma 6 update failed, seemingly because of a lack of free space left within the builders. 

As a consequence the repo is somewhat stuck in time.
How is that fixable? Is there a way for me to help?

Best regards - Spid

**Comment by SpidFightFR** [comment]
https://build.voidlinux.org/waterfall?show=x86_64_builder

**Comment by classabbyamp** [comment]
we know, we cleaned up some things
