### ISSUE TITLE
qt6ct.sh exports bad value

### ISSUE THREAD

**Issue by ondrejkajinek** [void-linux/void-packages#50304]
### Is this a new report?

Yes

### System Info

Void 6.6.30_1 x86_64

### Package(s) Affected

qt6ct-0.9_1

### Expected behaviour

According to [upstream](https://github.com/trialuser02/qt6ct), correct value is `qt6ct`.

### Actual behaviour

Incorrect value `qt5ct` is present.

### Steps to reproduce

1. Install `qt6ct`
2. Check `/etc/profile.d/qt6ct.sh`
3. Wrong value exported.

**Comment by classabbyamp** [comment]
it's not wrong

https://github.com/trialuser02/qt6ct/blob/55dba8704c0a748b0ce9f2d3cc2cf200ca3db464/README#L37

**Comment by ondrejkajinek** [comment]
My bad, sorry. It turned out missing `QT_QPA_PLATFORM=wayland` in my profile was the issue.
