### ISSUE TITLE
breeze window decoration themes not usable

### ISSUE THREAD

**Issue by rekh127** [void-linux/void-packages#50318]
### Is this a new report?

Yes

### System Info

Void 6.6.30_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFF

### Package(s) Affected

breeze-qt6 breeze-qt5 breeze kde5

### Expected behaviour

The breeze package contains window decoration themes breeze and oxygen and they are select able in settings appearance window decorations and applied by applying breeze master theme with "window decorations selected"

### Actual behaviour

Some files appear to be installed by breeze-qt6 but not breeze-qt5

```
/usr/lib/qt6/plugins/org.kde.kdecoration2/org.kde.breeze.so
/usr/lib/qt6/plugins/org.kde.kdecoration2.kcm/kcm_breezedecoration.so
/usr/share/applications/kcm_breezedecoration.desktop
```
At least with the current install which is plasma 5.27 after the breeze package is updated to this new meta pacakge applying the breeze theme applies the basic Plastik decorations, which is all thats listed in the Window Decorations menu. 

### Steps to reproduce

Install KDE.

**Comment by OoLunar** [comment]
Just updated, no longer able to reproduce. Instead I'm met with a non-functioning system, but at least my window decorations work!

**Comment by Luciogi** [comment]
> Just updated, no longer able to reproduce. Instead I'm met with a non-functioning system, but at least my window decorations work!

do you mean plasma is not starting ?
or system is no booting?

**Comment by rekh127** [comment]
Closing since it was a mid plasma upgrade thing that doesn't repro now
