### ISSUE TITLE
"Favorites" tab in the plasma app launcher stays empty after plasma 6 update

### ISSUE THREAD

**Issue by SpidFightFR** [void-linux/void-packages#50329]
### Is this a new report?

Yes

### System Info

Void 6.8.9_2 x86_64 AuthenticAMD uptodate rrmFFFFFFF

### Package(s) Affected

kde5-6.0.4_2

### Expected behaviour

![Screenshot_20240514_121641](https://github.com/void-linux/void-packages/assets/60798703/e5a169b2-8aae-4c97-b429-d651a8a5f41c)

### Actual behaviour

![image](https://github.com/void-linux/void-packages/assets/60798703/6e98f474-6185-43bd-8f1d-0392c874965e)

### Steps to reproduce

1. Go to the app launcher
2. Add apps to favorite
3. Nothing happens :(

**Comment by Luciogi** [comment]
test by creating new user

**Comment by SpidFightFR** [comment]
> test by creating new user

hey, sorry i'm late.

I just tested with a brand new test user. Same issue.

**Comment by Luciogi** [comment]
Favorite tab is working for me

---

launch `plasmashell --replace` from commandline, it may show any useful information

**Comment by SpidFightFR** [comment]
> Favorite tab is working for me
> 
> launch `plasmashell --replace` from commandline, it may show any useful information

I get a bunch of those errors: 


```
kde.plasma.activitiesstats: PlasmaActivities: Database is not open:  "kactivities_db_resources_140230085799232_readonly" "" QSqlError("", "Driver not loaded", "Driver not loaded")
kde.plasma.activitiesstats: Plasma Activities ERROR: There is no database. This probably means that you do not have the Activity Manager running, or that something else is broken on your system. Recent documents and alike will not work!
kde.plasma.activitiesstats: PlasmaActivities: Database is not open:  "kactivities_db_resources_140230085799232_readonly" "" QSqlError("", "Driver not loaded", "Driver not loaded")
kde.plasma.activitiesstats: Plasma Activities ERROR: There is no database. This probably means that you do not have the Activity Manager running, or that something else is broken on your system. Recent documents and alike will not work!
kde.plasma.activitiesstats: PlasmaActivities: Database is not open:  "kactivities_db_resources_140230085799232_readonly" "" QSqlError("", "Driver not loaded", "Driver not loaded")
kde.plasma.activitiesstats: Plasma Activities ERROR: There is no database. This probably means that you do not have the Activity Manager running, or that something else is broken on your system. Recent documents and alike will not work!
KActivities: FATAL ERROR: Failed to contact the activity manager daemon

```

Yet i do have sqlite installed and kwalletmanagerd....

**Comment by SpidFightFR** [comment]
Alright it's fixed, i just missed `qt6-plugin-sqlite` for some reasons...
Apparently it deals with transactions between qt6/plasma and sqlite, and this kind of stuff are stored in a database.

Perhaps it should be noted as a dependency for kde6 ?

Thanks for the debug command tho it was really handy !

**Comment by classabbyamp** [comment]
922e96f847b776d446541b77aca747d82bd2bb71
