### ISSUE TITLE
Package request: drist

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#50320]
### Package name

drist

### Package homepage

https://dataswamp.org/~solene/page-drist-official-website.html

### Description

Drist is a tool for configuring remote servers in an Unix way.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by paper42** [comment]
this is a single shell script, doesn't fit the quality requirements and was already removed from the repositories because of this years ago
