### ISSUE TITLE
pam-mount: LUKS2 patch wanted

### ISSUE THREAD

**Issue by whoizit** [void-linux/void-packages#5037]
### System

* xuname:  
Void 4.18.19_1 x86_64-musl AuthenticAMD uptodate FF
* package:  
pam-mount

I have same issue, wants patch https://bbs.archlinux.org/viewtopic.php?id=242131

**Comment by maxice8** [comment]
Will work on in the weekend if time allows.

Anyone else feel free to tackle

**Comment by ejigboyakubu229** [comment]
Hello
