### ISSUE TITLE
PlasmaShell segfaults on boot

### ISSUE THREAD

**Issue by OoLunar** [void-linux/void-packages#50393]
### Is this a new report?

Yes

### System Info

Void 6.6.30_1 x86_64 AuthenticAMD uptodate rrrmFFFFFF

### Package(s) Affected

Unknown

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

None found.

### Expected behaviour

- I successfully boot up my laptop
- SDDM's login screen appears
- I successfully login
- My desktop appears (fails)

### Actual behaviour

Once I login through SDDM, my desktop appears for 1-3 seconds before crashing. KCrash appears to try to launch `plasmashell` again as my desktop will appear one more time for another half second before crashing once more. Once everything settles, I am left with a black screen, completely unable to access my system tray or any of my desktop applications.

I am currently able to access my applications through a desktop shortcut. I launch `flameshot` and take a screenshot of my black desktop, attempt to save the file. Once `nemo` prompts me where to save the file, I click "Open location" via the right click menu. Once `nemo` fully launches, I'm able to open up `gnome-terminal` and start `firefox` or whatever other applications I may need.

Ctrl+C and Ctrl+V (copy and paste) are still very unreliable (may be unrelated).
When any application attempts to use `libnotify` (or presumably attempts to send a desktop notification in any sense), the application will freeze before it's forced to be killed by me.
Alt+Tab still works as expected.

### Steps to reproduce

1. Update from KDE5 to KDE6
2. While I did not take any explicit actions, there may be other steps that were performed without my knowledge. While I was upgrading, a lot of packages failed to upgrade due to package conflicts caused by the Void packaging servers not having certain versions of packages available, such as `plasma-nm`. Additionally a lot of packages were removed without my prior knowledge, such as `NetworkManager` and `dialog`. I personally believe this may have significantly contributed to the problem, though I have no proof.

Please let me know if any additional information is required. I am considering switching away from Void to Arch, however I happen to very much enjoy using Void and would prefer to resolve this issue first.

**Comment by OoLunar** [comment]
- [`dmesg.log`](https://github.com/void-linux/void-packages/files/15355440/dmesg.log)
- [`plasmashell.log`](https://github.com/void-linux/void-packages/files/15355443/plasmashell.log)

**Comment by TheDoubleB** [comment]
Can confirm that `systemtray` widget does not work in any way. The `plasma-desktop` update from 5.27.* to 6.0.4 today broke configurations on my desktop, laptop, and in a virtual machine. Only after removing every configuration file relating to `plasma-desktop` (`~/.config/plasma*`) I was able to log into Plasma session, but the moment I tried to add `systemtray` to **anything**, the entire desktop environment crashes, goes blank, and sets up again.

As a side note, I'm wondering whether the lack of `systemtray` widget is preventing volume up, volume down, and mute multimedia buttons from working or the visual volume slider from appearing.

**Comment by TheDoubleB** [comment]
Had a quick glance at the log file for `#voidlinux` Libera.Chat IRC channel and saw a debate from yesterday between two users for whom `systemtray` does not work either. There were mentions of missing icons in `systemtray` from a few days prior, but this one from yesterday mentions specifically `systemtray` not working at all, so we are definitely not alone.

**Comment by bvdeenen** [comment]
I found a fix/cause! plasma 6 depends on `kpipewire`, but my system did not have `pipewire` installed (`kpipewire` apparently does not require `pipewire`). Installing `pipewire` fixes the problem with the system tray. See the [reddit thread](https://www.reddit.com/r/voidlinux/comments/1csvd8e/problems_with_plasma_6/).

**Comment by sgn** [comment]
Added `pipewire` to `kpipewire`'s dependencies.

**Comment by OoLunar** [comment]
> Added `pipewire` to `kpipewire`'s dependencies.

Why does plasma rely on pipe wire in the first place? I personally use pulse audio and have no need for pipe wire. An I misunderstanding something?

**Comment by classabbyamp** [comment]
plasma doesn't rely on pipewire, but kpipewire allows qt applications to interface with pipewire for screensharing and recording in wayland

**Comment by OoLunar** [comment]
Closing as resolved
