### ISSUE TITLE
lsp-plugins not available for aarch64

### ISSUE THREAD

**Issue by 38github** [void-linux/void-packages#50394]
I compiled it and installed using xdowngrade since xi and xbps-install doesn't seem to allow it being install which I guess is because it strangely isn't available for aarch64 but for x86_64 and i686.

**Comment by dkwo** [comment]
it's marked as nocross, so you'd have to compile it yourself for aarch64, see `nocross="Build system doesn't support cross-compilation properly"`

**Comment by classabbyamp** [comment]
if you built it with xbps-src, `xi` should be able to see it

**Comment by 38github** [comment]
> if you built it with xbps-src, `xi` should be able to see it

Strange but no matter what I tried which always works with all the other packages I compile did notwork. It said that it was not inthe repository. I then saw on the site that it is not available for aarch64 and I believethe other ARM architectures so I assumed that xi and xbps-install with --repository somehow looks up firstif it is present in a repo before it installs.
