### ISSUE TITLE
GCC Cross compilation results in linux/errno.h not found

### ISSUE THREAD

**Issue by joe-albanese** [void-linux/void-packages#50434]
### Is this a new report?

Yes

### System Info

Void 6.6.30_1 x86_64 GenuineIntel uptodate rFFFFF

### Package(s) Affected

gcc-13.2.0

### Expected behaviour

Cross compiling GCC for aarch64 using ` ./xbps-src -a aarch64 -N pkg gcc` should build a gcc binary without failing and throwing errors

### Actual behaviour

Compilation runs normally until this error is produced:

`make[2]: Entering directory '/builddir/gcc-13.2.0/build/build-x86_64-pc-linux-gnu/libcpp'
test -f config.h || (rm -f stamp-h1 && make stamp-h1)
make[2]: Leaving directory '/builddir/gcc-13.2.0/build/build-x86_64-pc-linux-gnu/libcpp'
In file included from /usr/aarch64-linux-gnu/usr/include/errno.h:28,
                 from /usr/aarch64-linux-gnu/usr/include/c++/13.2/cerrno:42,
                 from /usr/aarch64-linux-gnu/usr/include/c++/13.2/ext/string_conversions.h:46,
                 from /usr/aarch64-linux-gnu/usr/include/c++/13.2/bits/basic_string.h:4097,
                 from /usr/aarch64-linux-gnu/usr/include/c++/13.2/string:54,
                 from /builddir/gcc-13.2.0/libcody/cody.hh:25,
                 from /builddir/gcc-13.2.0/libcody/internal.hh:5,
                 from /builddir/gcc-13.2.0/libcody/packet.cc:6:
/usr/aarch64-linux-gnu/usr/include/bits/errno.h:26:11: fatal error: linux/errno.h: No such file or directory
   26 | # include <linux/errno.h>
      |           ^~~~~~~~~~~~~~~
compilation terminated.`

Afterwards, the package fails to build (presumably from the above error):

`checking how to run the C preprocessor... aarch64-linux-gnu-cpp
configure: error: in '/builddir/gcc-13.2.0/build/gmp':
configure: error: C preprocessor "aarch64-linux-gnu-cpp" fails sanity check
See 'config.log' for more details
make[1]: *** [Makefile:5075: configure-gmp] Error 1
make[1]: Leaving directory '/builddir/gcc-13.2.0/build'
make: *** [Makefile:1051: all] Error 2
=> ERROR: gcc-13.2.0_2: do_build: 'make ${makejobs}' exited with 2
=> ERROR:   in do_build() at srcpkgs/gcc/template:340`

### Steps to reproduce

1. Run `./xbps-src binary-bootstrap`
2. Run  `./xbps-src -a aarch64 -N pkg gcc`
3. Error thrown

**Comment by oreo639** [comment]
Builds fine for me.

**Comment by joe-albanese** [comment]
must have been fixed with an update. It's working for me now
