### ISSUE TITLE
filelight 24.02.2_1 segmentation fault

### ISSUE THREAD

**Issue by summrum** [void-linux/void-packages#50443]
### Is this a new report?

Yes

### System Info

Void 6.6.31_1 x86_64 GenuineIntel uptodate rrmFFFFFFFFFF

### Package(s) Affected

filelight-24.02.2_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

I am unable to find any similar issue for this package.

### Expected behaviour

Attempting to launch filelight from application launcher, from within file manager or from terminal emulator should result in filelight opening.

### Actual behaviour

Filelight does not launch from Rofi application launcher or from Dolphin file manager. Attempting to launch filelight from terminal emulator results only in the following output:

```
QQmlComponent: Component is not ready
Failed to load component: "qrc:/ui/Action.qml:8 Type Kirigami.Action unavailable\nfile:///usr/lib/qt6/qml/org/kde/kirigami/Action.qml:-1 module \"org.kde.desktop\" is not installed\n"
Segmentation fault
```

### Steps to reproduce

1. Update filelight from 23.08.5_1 to 24.02.2_1
2. Attempt to launch filelight from terminal emulator
3. Filelight crashes with error output provided

**Comment by sgn** [comment]
Can you try installing `kf6-qqc2-desktop-style` and try again?

**Comment by summrum** [comment]
I added a pull request for the missing dependency [50451](https://github.com/void-linux/void-packages/pull/50451). Thanks again for your quick response.
