### ISSUE TITLE
qtcreator  mime freedesktop.org.xml

### ISSUE THREAD

**Issue by dinama** [void-linux/void-packages#5044]
### System

* xuname:   Void 4.18.19_1 x86_64 GenuineIntel uptodate rF
* package:  qtcreator
build-date: 2018-11-02 
install-date: 2018-11-23 
pkgver: qtcreator-4.7.2_1
repository: https://alpha.de.repo.voidlinux.org/current

### Expected behavior

load any text file formats

### Actual behavior

load only files with  c|c++ extentions

### Steps to reproduce the behavior

`echo hello > /tmp/1.txt `
`qtcreator /tmp/1.txt`
`qt5ct: using qt5ct plugin`
`qt5ct: D-Bus global menu: no`
`MimeDatabase: Error loading :/qt-project.org/qmime/freedesktop.org.xml`
`Cannot open :/qt-project.org/qmime/freedesktop.org.xml: No such file or directory`

and final ui message: 

`Could not open "/tmp/1.txt": Cannot open files of type "".`

===

` find  / 2> /dev/null | grep freedesktop.org.xml  `
`/usr/share/mime/packages/freedesktop.org.xml`

**Comment by dinama** [comment]
` export XDG_DATA_DIRS=/usr/share;qtcreator /tmp/1.txt `

have some effect

**Comment by pullmoll** [comment]
Since I used to open other files with qtcreator, I think it needs to be rebuilt for qt5-5.11.2 update.
Will do that now.

**Comment by dinama** [comment]
> Since I used to open other files with qtcreator, I think it needs to be rebuilt for qt5-5.11.2 update.
> Will do that now.

```qtcreator -version```

> qt5ct: using qt5ct plugin
> Qt Creator 4.7.2 based on Qt 5.11.2

do wait qtcreator rebuilding?

**Comment by pullmoll** [comment]
Well, AFAIR qtcreator uses private headers of Qt5 and as such needs to be rebuilt after a Qt5 update. The version info is not telling against which version qtcreator was built but just the current version. The most recent rebuild was on Nov 2nd before the qt5 update.

**Comment by dinama** [comment]
> So it should be solved once qtcreator is rebuil

yes, rebuilding qtcreator from package source - resolve this problem

**Comment by maxice8** [comment]
qtcreator was rebuilt during llvm bump done yesterday, i'm closing this and if it isn't solved please re-open
