### ISSUE TITLE
Please add texinfo package as a dependency of octave

### ISSUE THREAD

**Issue by LinArcX** [void-linux/void-packages#50442]
### Is this a new report?

Yes

### System Info

Void 6.6.31_1 x86_64 GenuineIntel notuptodate hold rrmFFF

### Package(s) Affected

octave

### Expected behaviour

when you type: `help <FOO>` you should not receive any error. 

### Actual behaviour

Currently, if you try to see the documentation for different functions and built-in variables in octave you will receive this error:
![screenshot_2024_05_20_18_29_31](https://github.com/void-linux/void-packages/assets/10884422/39af396f-e035-45ab-b4e9-52c75b3005a2)

### Steps to reproduce

I just installed the __texinfo__ package and now I can use the `help` command in gnu octave.

**Comment by tornaria** [comment]
Fixed by #50807.
