### ISSUE TITLE
Signal-Desktop package out of date

### ISSUE THREAD

**Issue by okawo80085** [void-linux/void-packages#50481]
### Is this a new report?

Yes

### System Info

Void 6.6.31_1 x86_64 AuthenticAMD notuptodate rrrrmmnFFFFFFF

### Package(s) Affected

Signal-Desktop-6.48.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

I wasn't able to find any recent (as in this year or newer) ones

### Expected behaviour

Signal starts up and works without any issues, messages can be sent, received, etc

### Actual behaviour

Signal starts up, but version expired warning is shown and it makes it impossible to send any messages
![image](https://github.com/void-linux/void-packages/assets/43695253/c37dc96a-834f-423e-aa87-f5163300e766)

### Steps to reproduce

1) Open Signal-Desktop app
2) Observe red pop up in the window warning that the current version expired
![image](https://github.com/void-linux/void-packages/assets/43695253/37ec0285-640b-4e6f-aa8f-fd35979e8cf4)

3) Try to send any messages
4) Get another pop up in the left bottom corner saying the same thing
![image](https://github.com/void-linux/void-packages/assets/43695253/14a3d2a8-0e12-42cf-8952-7592bfe15119)

**Comment by MIvanchev** [comment]
#50479

**Comment by okawo80085** [comment]
Oh perfect

**Comment by MIvanchev** [comment]
@okawo80085 Keep in mind I haven't tested this, maybe you could help :)

**Comment by okawo80085** [comment]
Yeah i'd be more than happy to test it :)

**Comment by okawo80085** [comment]
Yup, the 7.10.0_1 version of the Signal-Desktop package fixes this issue :)
It should probably still be updated to either patch the node version miss match or the node package should be updated, as for the security implications, it'll probably be better to ask someone working on Signal because node is not my fortune xd

**Comment by MIvanchev** [comment]
Thanks @okawo80085. We should definitely patch Node ASAP for the security implications.
