### ISSUE TITLE
pandoc package way out of date, should be V 3.2

### ISSUE THREAD

**Issue by lukeflo** [void-linux/void-packages#50500]
### Is this a new report?

Yes

### System Info

Void 6.6.31_1 x86_64 GenuineIntel uptodate rrFFF

### Package(s) Affected

pandoc-2.17.1.1_1

### Expected behaviour

Convert between document formats using the up-to-date functions of `pandoc`, such as the renewed AST in combination with Lua filters.

### Actual behaviour

Some of my Lua filters which use the new AST Figure elements are not working as expected, since the old `pandoc` version can't handle its syntax. Surely there are other drawbacks which I didn't encounter so far.

### Steps to reproduce

1. Install the `pandoc` package from void repo
2. For example, use my [GitLab Repo](https://gitlab.com/lukeflo/dailatex/-/tree/main/test-files?ref_type=heads) which contains my publication workflow and run `pandoc -t native cls-dai.md` after cloning. The resulting AST don't show a Figure block as it should.
3. Maybe try running the `makefile` and check the resulting `.tex` file, the changes which the filters should handle are not there.
4. If don't want to use a custom repo, this can be reproduced with running `pandoc -t native` on any `.md` file containing Pandoc's Markdown syntax for images/figures or exporting to LaTeX using some Lua filter acting on the [Figure element](https://pandoc.org/lua-filters.html#pandoc.figure).

**Comment by classabbyamp** [comment]
> Please don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.

**Comment by ahesford** [comment]
Please don't open issues to tell us packages are out of date. We have automated systems that tell us this. If the package hasn't been updated, either nobody has found the time, or there are unseen challenges that need to be addressed.

PRs to update outdated packages are most welcome.

**Comment by classabbyamp** [comment]
see also: https://github.com/void-linux/void-packages/pull/49557

**Comment by lukeflo** [comment]
> > Please don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.

Allright, I wasn't aware of that. Sorry for the inconveniences. Next time I'll try opening a PR or similar.
