### ISSUE TITLE
Package request: Distrobox

### ISSUE THREAD

**Issue by zukas97** [void-linux/void-packages#50512]
### Package name

distrobox

### Package homepage

https://github.com/89luca89/distrobox

### Description

Distrobox is a wrapper around docker, podman, or lilipod that allows you to export apps installed on linux distros installed in containers

### Does the requested package meet the package requirements?

System, Required

### Is the requested package released?

Yes

**Comment by blacklightpy** [comment]
Duplicate of #36341
