### ISSUE TITLE
Checksum mismatch for vscode

### ISSUE THREAD

**Issue by shutosheep** [void-linux/void-packages#50525]
### Is this a new report?

Yes

### System Info

Void 6.6.31_1 x86_64 GenuineIntel uptodate FFF

### Package(s) Affected

vscode-1.89.0_1

### Expected behaviour

Build the package without error.

### Actual behaviour

Verifying checksum will fail.

```
=> vscode-1.89.0_1: verifying checksum for distfile '1.89.0.tar.gz'...
=> ERROR: SHA256 mismatch for '1.89.0.tar.gz:'
624774ec364a6d65880192ff62f6d8c49087b2db90399790e4c64a61dd4fae18
=> ERROR: vscode-1.89.0_1: couldn't verify distfiles, exiting...
```

When I manually modified the template file it solved for me.

```
# checksum=7b4652b00a0e0b75b0d7123427c28e5ecfb982bfebbe67ed9af29eb672c655b6
checksum=624774ec364a6d65880192ff62f6d8c49087b2db90399790e4c64a61dd4fae18
```

### Steps to reproduce

1. Get latest void-packages repo
2. `./xbps-src pkg vscode`

**Comment by cinerea0** [comment]
Seems to be fixed with 1.89.1; closing.
