### ISSUE TITLE
gcompris-qt won't launch

### ISSUE THREAD

**Issue by jarbowski** [void-linux/void-packages#5052]
Cannot mix incompatible Qt library (version 0x50a01) with this library (version 0x50b02)

probably needs a rebuild since the qt5 update (good news since gcompris needs qt5.11 to work properly)
thanks

**Comment by Johnnynator** [comment]
@jarbowski Are you using `qt5-styleplugins` , if yes this issue should be resolved once https://github.com/void-linux/void-packages/commit/aa33e8f92692141a8164fd71f7adce43d4282d75 has laned in the binary repo.

**Comment by jarbowski** [comment]
@Johnnynator 
you were right, everything is okay.
thanks
