### ISSUE TITLE
Samba package includes broken runit service files.

### ISSUE THREAD

**Issue by TorMFinn** [void-linux/void-packages#50524]
### Is this a new report?

Yes

### System Info

Void 6.6.31_1 x86_64 GenuineIntel uptodate rrmFFFFF

### Package(s) Affected

samba-4.20.1_1

### Expected behaviour

smbd and nmbd should launch correctly by symlinking the service files in /etc/sv to /var/service

### Actual behaviour

Fails to launch where both smbd and nmbd complains about wrong command line arguments.

[sambalogs.txt](https://github.com/void-linux/void-packages/files/15446915/sambalogs.txt)

### Steps to reproduce

install samba
ln -s /etc/sv/smbd /var/service
ln -s /etc/sv/nmbd /var/service
svlogtail

**Comment by meator** [comment]
Can reproduce. A workaround would be to create files `/etc/sv/nmbd/conf` and `/etc/sv/smbd/conf` both containing the following line:

```bash
OPTS=-d1
```

cc @otommod

@TorMFinn Would you mind testing #50526? This should fix the issue. [You can look here if you don't know how to try out a pull request.](https://xbps-src-tutorials.github.io/pr-testing-tutorial.html)
