### ISSUE TITLE
Package request: PWAsForFirefox

### ISSUE THREAD

**Issue by blacklightpy** [void-linux/void-packages#50533]
### Package name

firefoxpwa

### Package homepage

https://pwasforfirefox.filips.si/

### Description

A tool to install, manage and use Progressive Web Apps (PWAs) in Mozilla Firefox.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by blacklightpy** [comment]
In musl, you have to edit the Makefile.toml to add `"--features" "static linked-runtime"` in args, and then install the runtime with `firefoxpwa runtime install --link`.

**Comment by classabbyamp** [comment]
duplicate #44251
