### ISSUE TITLE
Package request: Fastfetch

### ISSUE THREAD

**Issue by duskull88** [void-linux/void-packages#50532]
### Package name

Fastfetch

### Package homepage

https://github.com/fastfetch-cli/fastfetch

### Description

Fastfetch is a neofetch-like tool for fetching system information and displaying them in a pretty way. It is written mainly in C, with performance and customizability in mind. Currently, Linux, Android, FreeBSD, MacOS and Windows 7+ are supported.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by hervyqa** [comment]
@duskull88 please, look at the existing PR first before creating a new issue. #50201
closed issue: #38293 #43461 #50293
