### ISSUE TITLE
Vulkan glitching out on some applications since a recent Void-Linux update ?

### ISSUE THREAD

**Issue by SpidFightFR** [void-linux/void-packages#50545]
### Is this a new report?

Yes

### System Info

Void 6.9.1_1 x86_64 AuthenticAMD uptodate rrmFFFFFFFF

### Package(s) Affected

vulkan-loader-1.3.261.1_2 mesa-vulkan-radeon-24.0.7_1 (?)

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

I didn't find such a report. Devs and I agree on the fact that it doesn't come from the mod, since i tested this version already, before updating my system, and everything worked.
It's only recently that this issue happened, i took a wild blind guess at vulkan-loader but i legit don't know.

### Expected behaviour

The test were based on the latest release of the Vulkanmod for minecraft (version 0.4.2 - stable, which i tested in the past, without any issues).
It should work normally.

### Actual behaviour

The screen glitches out with the app running in fullscreen.
[video sample](https://pub-933bfc621bd04d93ab1b82361d7baa1a.r2.dev/vkmod%20bug.mp4)

### Steps to reproduce

1. Update Void with the latest packages to this day
2. Run Minecraft with vulkanmod

**Comment by SpidFightFR** [comment]
Sorry for the poor issue quality... I'm not going to lie, we tested things with the devs, and the issue doesn't happen to them, most of them run bleeding edge distros (Arch) and it doesn't happen... So out of lack of knowledge i tried to ask for help here.

**Comment by Luciogi** [comment]
I dont want have minecraft to test, Ask devs how to get logs

**Comment by SpidFightFR** [comment]
> I dont want have minecraft to test, Ask devs how to get logs

We got logs, even vulkzn validation layers.
Nothing weird here

**Comment by Luciogi** [comment]
FPS counter is from MangoHud?

**Comment by SpidFightFR** [comment]
> FPS counter is from MangoHud?

Yep. But the settings menu ingame is having the same stroke, we can hardly see that in the video i linked...

**Comment by SpidFightFR** [comment]
I also tried vkcube wayland with mangohud as well, i don't have the same issue.

**Comment by Luciogi** [comment]
I tried Minecraft on my machine, it has intel gpu , it does have any issue related to graphics glitches

**Comment by SpidFightFR** [comment]
> I tried Minecraft on my machine, it has intel gpu , it does not have any issue related to graphics glitches

Can you try with the latest release of vulkanmod? (Requires fabric modloader and the vulkanmod itself in the mods files).

If you use Prismlauncher it's a piece of cake.

**Comment by SpidFightFR** [comment]
Imma try witv my laptop as soon as possible, to see if it's related to my pc

**Comment by SpidFightFR** [comment]
> > > I tried Minecraft on my machine, it has intel gpu , it does not have any issue related to graphics glitches
> > 
> > 
> > Can you try with the latest release of vulkanmod? (Requires fabric modloader and the vulkanmod itself in the mods files).
> > EDIT: Cuz regular Minecraft uses Opengl, and it runs fine on my machine as well.
> > If you use Prismlauncher it's a piece of cake.
> 
> i used TLauncher, with Fabric + Vulkanmod

That's weird as hell i need to try again

**Comment by SpidFightFR** [comment]
It ain't flatpak, is it?

**Comment by Luciogi** [comment]
> It ain't flatpak, is it?

no, i downloaded java binary from their website

**Comment by SpidFightFR** [comment]
i just tried on my void laptop, it works as well, what the hell is going on...?

**Comment by SpidFightFR** [comment]
literally nothing changed... except if it's amdvlk going crazy with mesa

**Comment by SpidFightFR** [comment]
Okay so even without amdvlk installed, it still goes crazy... I don't even know where to look for, logs are the same than on my laptop that runs fine.

**Comment by SpidFightFR** [comment]
It also happens with Q2RTX, can it be SDL ???

**Comment by SpidFightFR** [comment]
after a few tests:

It happens on both minecraft vulkanmod & Quake2RTX (native wayland - both), but not with gamescope.
Can it be plasma ?

**Comment by SpidFightFR** [comment]
Bro i can't... it literally solved itself. :no_mouth: 
What kind of problem is that...

**Comment by SpidFightFR** [comment]
No it's still on after a reboot, nvm.

**Comment by Dr64h** [comment]
> after a few tests:
> 
> It happens on both minecraft vulkanmod & Quake2RTX (native wayland - both), but not with gamescope. Can it be plasma ?

About a week and a half ago, I had artifacts with RX570 when opening games in plasma, but they were not specifically related to Vulkan and they disappeared after the update.

**Comment by SpidFightFR** [comment]
> > after a few tests:
> > It happens on both minecraft vulkanmod & Quake2RTX (native wayland - both), but not with gamescope. Can it be plasma ?
> 
> About a week and a half ago, I had blinking artifacts with RX570 when opening games in plasma, but they were not specifically related to Vulkan and they disappeared after the update.

which update ?

**Comment by SpidFightFR** [comment]
> > > > after a few tests:
> > > > It happens on both minecraft vulkanmod & Quake2RTX (native wayland - both), but not with gamescope. Can it be plasma ?
> > > 
> > > 
> > > About a week and a half ago, I had blinking artifacts with RX570 when opening games in plasma, but they were not specifically related to Vulkan and they disappeared after the update.
> > 
> > 
> > which update ?
> 
> KDE components update, i don't know exactly which component is responsible for this artifacts, i think it's something with kwin and screen synchronization.
> 
> When you turn on the "full screen" mode the game is responsible for screen sync, and when you change it to "window mode" or "borderless full screen window", then the kwin is responsible for screen sync. But it doesn't mean that exactly the screen sync is responsible for this artifacts, it can be another different graphics things, effects, which turns on/off when you change window modes.
> 
> Check this, maybe it close to your issue: https://bugs.kde.org/show_bug.cgi?id=487780

i'll keep an eye out on it, it's not exactly my issue but i'll check just in case.

Thanks

**Comment by SpidFightFR** [comment]
I close this issue as it's a DRM bug with scanout:

https://gitlab.freedesktop.org/drm/amd/-/issues/3402#note_2438198
