### ISSUE TITLE
change from  vokoscreen to vokoscreenNG

### ISSUE THREAD

**Issue by 1is7ac3** [void-linux/void-packages#50549]
upgrade to 4.0.0 without changing package name or adding new package.
Corretamete works in x11 and wayland in experimental development.
# Template file for 'vokoscreen'
pkgname=vokoscreen
version=4.0.0
revision=1
build_style=qmake
configure_args="PREFIX=/usr src/vokoscreenNG.pro"
hostmakedepends="pkg-config qt6-tools-devel qt6-base-devel"
makedepends="alsa-lib-devel libX11-devel libXrandr-devel wayland-devel
 gstreamer1-devel gst-plugins-base1-devel pulseaudio-devel qt6-multimedia-devel
 gstreamer1-pipewire"
depends="ffmpeg gstreamer1-pipewire gst-plugins-ugly1 gst-libav"
short_desc="Easy to use screencast creator"
maintainer="Duncaen <duncaen@voidlinux.org>"
license="GPL-2.0-only"
homepage="http://linuxecke.volkoh.de/vokoscreen/vokoscreen.html"
distfiles="https://github.com/vkohaupt/${pkgname}NG/archive/${version}.tar.gz"
checksum=78e40de635da968befc85c85103387ec97dce8c8d5e3de226c9a61a6afd22b97

do_install()
{
	vbin vokoscreenNG
	vinstall src/applications/${pkgname}NG.desktop 755 usr/share/applications
	vinstall src/applications/${pkgname}NG.png 644 usr/share/pixmaps
}

**Comment by classabbyamp** [comment]
this belongs in a PR, not an issue
