### ISSUE TITLE
Package Request: deepin-desktop 

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#5055]
Continuation of https://github.com/voidlinux/void-packages/issues/13284

Deepin GitHub Repo: https://github.com/linuxdeepin

Work Fork https://github.com/Johnnynator/void-packages/tree/deepin

CC @mar1n3r0

**Comment by mar1n3r0** [comment]
Postponing a bit, the repo looks overwhelming in terms of dependencies. Even if we do succeed in porting it I don't think a single person can maintain it up to date.

**Comment by Johnnynator** [comment]
> Postponing a bit, the repo looks overwhelming in terms of dependencies. Even if we do succeed in porting it I don't think a single person can maintain it up to date.

I maintain KDE Plasma more or less alone atm which is more packages. It is always a question of code and build system quality of upstream. (Ok KDE is far better in this then Deepin, the few Deepin Apps that are already here in the main Repo like to break from time to time.). But generally Maintaining packages is far less Time consuming then the initial Port, so I wouldn't bother with thinking about maintenance burdens yet.

**Comment by mar1n3r0** [comment]
Yeah you are right, Plasma has full guidelines and documentation on building from source though... I ported Budgie but am not at the level to port something that complex without any understanding of it's structure and dependencies...

**Comment by silvernode** [comment]
Was just about to post this on the new tracker, thanks for saving me some time. Recently I have been using deepin proper, and I love it. Would be nice to eventually have the desktop and tools working on Void.

**Comment by Johnnynator** [comment]
Currently fully on hold, since `mongodb` got dropped which was needed for `treefrog-framework` which was a dep of `deepin-file-manager` (Not that I did any work on it the last few month :)))

**Comment by HeraKumi** [comment]
any update on the file manager? @Johnnynator

**Comment by Johnnynator** [comment]
the lib that was needed for `treefrog-framework` was not affected by the licensing change, so we didn't had to drop it. Otherwise no updates so far.

**Comment by anarchomoh** [comment]
Is there a way I can donate to progress this package? I'm a non-coder 🙂.

**Comment by marcosroot** [comment]
Some update?

**Comment by flexibeast** [comment]
@marcosroot: 

See [this Reddit comment](https://old.reddit.com/r/voidlinux/comments/chwn9b/a_few_reasons_that_didnt_make_me_like_void_so_much/euypdbn/) by @Johnnynator:

> Regarding Deepin: it is a real Pain to package and maintain and I currently don't have any interest at continuing the work I started some time ago.

followed by [this comment](https://old.reddit.com/r/voidlinux/comments/chwn9b/a_few_reasons_that_didnt_make_me_like_void_so_much/ev0sbdd/):

> There are multiple parts that make Deepin annoying to package compared to e.g. KDE Plasma.
>
> KDE is a matured environment with decent documentation and rules about what depends on what. So creating a KDE (Plasma) Package is comparably straightforward, a few qt deps maybe some kde-framework deps and setting build-style to cmake and it will most likely work.
>
> For Deepin you have a mess of multiple build systems (sometimes they are even chained which nearly always breaks cross compiling), multiple GUI kits are used (Vala, Gtk, Qt), broken Makefiles (especially for cross-compiling). Also they have a few packages that are forked and patched version of different mainly Gnome projects that conflict with the original one deepin-{mutter,cogl,clutter}. And probably some other parts that got me annoyed while trying to package it the first time.

**Comment by THEk1tchenS1NK** [comment]
i also request the deepin de repo be added i love the de so more a interest bump

**Comment by rwt3k** [comment]
I think it would be more interesting to recruit people interested in maintaining or adding new desktop environments. It would be less work and things would go faster.

**Comment by LinArcX** [comment]
@Johnnynator There is no relation between treefrog-framework or mongodb with deepin-file-manager:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/deepin-file-manager

**Comment by rapha8l** [comment]
any news ?
