### ISSUE TITLE
Vulkan-Headers missing symbolic links inside /usr/lib

### ISSUE THREAD

**Issue by Norman-Normandy** [void-linux/void-packages#50601]
### Is this a new report?

Yes

### System Info

Void 6.9.2_1 x86_64 AuthenticAMD uptodate rrrmmnFFFFFFFFF

### Package(s) Affected

Vulkan-Headers

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Similar issues: https://github.com/void-linux/void-packages/issues/44317 https://github.com/void-linux/void-packages/issues/18105 https://github.com/void-linux/void-packages/issues/44317

### Expected behaviour

The symbolic links should be:
/usr/lib/libvulkan.so -> libvulkan.so.1
/usr/lib/libvulkan.so.1 -> libvulkan.so.1.3.261
/usr/lib/libvulkan.so.1.3.261

### Actual behaviour

But instead found:
/usr/lib/libvulkan.so.1 -> libvulkan.so.1.3.261
/usr/lib/libvulkan.so.1.3.261

### Steps to reproduce

xbps-install -Su Vulkan-Headers

And see missing final symbolic link inside /usr/lib

Tried: "xbps-install -f" along with removing the package and removing orphans *Weren't any* and reinstalling.

I also tried xbps-reconfigure. Not sure if this is something on my end or effecting everyone.
In-fact other libraries are also missing their final symbolic links.

Running "xbps-pkgdb -a" gives:                     
ERROR: libksane6: unexistent file /usr/share/icons/hicolor/16x16/actions/black-white.png.
ERROR: libksane6: unexistent file /usr/share/icons/hicolor/16x16/actions/color.png.
ERROR: libksane6: unexistent file /usr/share/icons/hicolor/16x16/actions/gray-scale.png.
ERROR: libksane6: unexistent file /usr/share/locale/hne/LC_MESSAGES/libksane.mo.
ERROR: libksane6: unexistent file /usr/share/locale/ml/LC_MESSAGES/libksane.mo.
ERROR: libksane6: unexistent file /usr/share/locale/oc/LC_MESSAGES/libksane.mo.
ERROR: libksane6: unexistent file /usr/share/locale/pa/LC_MESSAGES/libksane.mo.
ERROR: libksane6: unexistent file /usr/share/locale/ug/LC_MESSAGES/libksane.mo.
ERROR: libksane6: files check FAILED.
ERROR: ksanecore6: unexistent file /usr/share/locale/ar/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/bg/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/ca/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/ca@valencia/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/cs/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/de/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/en_GB/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/eo/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/es/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/eu/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/fi/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/fr/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/gl/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/hi/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/it/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/ja/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/ka/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/ko/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/lt/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/nl/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/nn/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/pl/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/pt/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/pt_BR/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/ru/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/sk/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/sl/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/sv/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/tr/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/uk/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: unexistent file /usr/share/locale/zh_TW/LC_MESSAGES/ksanecore.mo.
ERROR: ksanecore6: files check FAILED.

Have not ever touched the /usr/lib directory manually. Only used xbps cli tools 
and only once for this occasion to fix the issue temporarily by creating the final symbolic link after doing "xbps-pkgdb -a".

**Comment by classabbyamp** [comment]
none of those files are in Vulkan-Headers
```
$ xlocate libvulkan.so
vulkan-loader-1.3.261.1_2                   /usr/lib/libvulkan.so.1 -> /usr/lib/libvulkan.so.1.3.261
vulkan-loader-1.3.261.1_2                   /usr/lib/libvulkan.so.1.3.261
vulkan-loader-devel-1.3.261.1_2             /usr/lib/libvulkan.so -> /usr/lib/libvulkan.so.1
```
