### ISSUE TITLE
Package request:  Mullvad browser

### ISSUE THREAD

**Issue by rxmmah** [void-linux/void-packages#50622]
### Package name

Mullvad-browser

### Package homepage

https://github.com/mullvad/mullvad-browser

### Description

The Mullvad Browser is a privacy-focused web browser developed in a collaboration between [Mullvad VPN](https://mullvad.net/) and the [Tor Project](https://www.torproject.org/).

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by ethamck** [comment]
see also https://github.com/void-linux/void-packages/issues/24393#issuecomment-922327135
