### ISSUE TITLE
Package request: Gnome 46.2

### ISSUE THREAD

**Issue by fisuri** [void-linux/void-packages#50625]
### Package name

gnome

### Package homepage

https://www.gnome.org

### Description

GNOME meta-package for Void Linux

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
Please don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt).

it's also in progress already

**Comment by fisuri** [comment]
I didn't know, thanks for the information

**Comment by fisuri** [comment]
> [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt).

When will the script merge? There is still an old gnome in the repository

**Comment by classabbyamp** [comment]
the script doesn't merge anything, it notifies maintainers that there are new versions available (and thus we don't need issues requesting updates)
