### ISSUE TITLE
audit-3.0.3_6: Package does not build due to missing `linux/ipx.h` header.

### ISSUE THREAD

**Issue by techflashYT** [void-linux/void-packages#50646]
### Is this a new report?

Yes

### System Info

Void 6.6.31_1 x86_64 GenuineIntel/VM uptodate FF

### Package(s) Affected

audit-3.0.3_6

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

If there is, I can't find any that's strictly related.

### Expected behaviour

The package should build successfully.

### Actual behaviour

The package does not build successfully due to Linux kernel header errors.

### Steps to reproduce

1. Get a Void host (I tested mine on x86_64 in QEMU, however I can also reproduce elsewhere)
2. Fresh clone `void-packages` with no packages built.
3. `./xbps-src binary-bootstrap`
4. `./xbps-src pkg audit`
5. The build fails.

**Comment by MIvanchev** [comment]
Audit is also quite outdated in Void's repos.

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/pull/50666
