### ISSUE TITLE
python3-pyside2 build fails, requires qt5 patch

### ISSUE THREAD

**Issue by zlice** [void-linux/void-packages#50673]
### Is this a new report?

Yes

### System Info

Void 6.9.0 x86_64 AuthenticAMD notuptodate rFFFFFFFFFFFFFF

### Package(s) Affected

python3-pyside2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270715

### Expected behaviour

python3-pyside2 builds

### Actual behaviour

Something along the lines of

```
DragMove
/usr/local/include/qt5/QtCore/qcoreevent.h:107:9: note: 'DragMove' declared here
        DragMove = 61,                          // drag moves in 
```

### Steps to reproduce

- `./xbps-src pkg python3-pyside2`

fix in link applies to `qt5`. after rebuilding qt and dependencies, this allowed pyside2 to build. not sure if there's a way to patch pyside2 instead, or need to revbump everything for qt5

[qtbase-5.15.9-work-around-pyside2-brokenness.txt](https://github.com/user-attachments/files/15540784/qtbase-5.15.9-work-around-pyside2-brokenness.txt)

**Comment by classabbyamp** [comment]
feel free to open a PR if you have a patch

**Comment by zlice** [comment]
will do. revbump everything that needs qt5-devel or no?

**Comment by classabbyamp** [comment]
not necessary unless it breaks things otherwise

**Comment by zlice** [comment]
i'll have to test on another machine then

**Comment by zlice** [comment]
https://github.com/void-linux/void-packages/pull/50693
