### ISSUE TITLE
vscode: "Open with..." action opens vscode with no workspace

### ISSUE THREAD

**Issue by deimonn** [void-linux/void-packages#50682]
### Is this a new report?

Yes

### System Info

Void 6.6.32_1 x86_64 AuthenticAMD uptodate rFFF

### Package(s) Affected

vscode-1.89.1_1

### Expected behaviour

Right-clicking a folder and selecting "**Open with... > Code - OSS**" should open vscode with the folder as "workspace".

### Actual behaviour

A vscode instance opens but it just shows the home screen.

### Steps to reproduce

1. Open Nautilus (I'm on GNOME) and right-click on any directory.
2. Click the "Open with..." option on the context menu.
3. Select "Code - OSS" and press "Open".

**Comment by deimonn** [comment]
I also wish to note that I hacked a fix for this issue by going into the `/usr/share/applications/code-oss.desktop` file and removing the `--unity-launch` argument from `Exec`:

```diff
[Desktop Entry]
Name=Code - OSS
Comment=Code Editing. Redefined.
GenericName=Text Editor
- Exec=/usr/lib/code-oss/bin/code-oss --unity-launch %F
+ Exec=/usr/lib/code-oss/bin/code-oss %F
Icon=code-oss
Type=Application
...
```

I do not know what the `--unity-launch` argument is meant to do, but this fixed the behavior described above at least.

**Comment by djaonline** [comment]
Void linux, kde6, dolphin. I can confirm the same issue. "Open folder with" context menu item doesn't contain "code-oss".
