### ISSUE TITLE
python3-adblock FTBFS 

### ISSUE THREAD

**Issue by ahesford** [void-linux/void-packages#50697]
### Is this a new report?

Yes

### System Info

void-packages v1.0

### Package(s) Affected

python3-adblock

### Expected behaviour

The package should build.

### Actual behaviour

`cargo` complains that it can't find the necessary version of `rmp-serde`, which was yanked from crates.io.

### Steps to reproduce

Try to build the package.

**Comment by cinerea0** [comment]
Switching the distfile to `https://github.com/ArniDagur/python-adblock/archive/refs/tags/${version}.tar.gz` seems to fix the build with no additional patching required. Not sure if the built library is functionally identical.

**Comment by ahesford** [comment]
Thanks! https://github.com/void-linux/void-packages/commit/e69d70b394dd936997ecac48757b13454a247b5f
