### ISSUE TITLE
Package Request: podman

### ISSUE THREAD

**Issue by jcgruenhage** [void-linux/void-packages#5073]
> ## Podman
> Manage pods, containers, and container images.

It's basically a replacement of docker, intended to be usable with `alias docker="podman"`, but without having a big fat daemon running in the background all the time. It also has some more dependencies that are not packaged for void yet, see details here: https://github.com/containers/libpod/blob/master/docs/tutorials/podman_tutorial.md

**Comment by CameronNemo** [comment]
See #1431

**Comment by knusbaum** [comment]
I'm working on this. It seems not to be too difficult, but does require a few new packages.

**Comment by knusbaum** [comment]
I went ahead and put up a PR for podman #5185 
Hopefully the cri-o PR will be merged for the next release

**Comment by CameronNemo** [comment]
Go bits:

- [ ] containernetworking/cni
- [ ] containernetworking/plugins
- [ ] cri-o
- [ ] podman

Python bits:

- [ ] python-varlink
- [ ] python3-podman
- [ ] [python-humanize](https://github.com/luckydonald-forks/humanize)
- [ ] pypodman

**Comment by CameronNemo** [comment]
Is cri-o? From what I can tell its not necessary.

**Comment by knusbaum** [comment]
Yes, it appears so. The `cri-o` package provides the `conmon` binary, which `podman` uses directly.

**Comment by CameronNemo** [comment]
Yes they should be a separate package. In fact, I think it would be simpler if they were a separate source package entirely. I can handle that portion if you would prefer.

**Comment by knusbaum** [comment]
I've already gotten them pulled out in the podman template. I can fairly easily separate them into their own template. I also have templates going for the other python deps. They will be dependencies of podman anyway, though, since the pypodman executable depends on them.

**Comment by CameronNemo** [comment]
For now, don't worry too much about the python bits. We can circle back to it later.

**Comment by knusbaum** [comment]
I'm having trouble getting pypodman to work properly anyway. The main podman binary seems to work pretty well.

**Comment by CameronNemo** [comment]
Yes the python bits should be completely separate. Sorry if I was not clear.

**Comment by knusbaum** [comment]
Including the executable - Gotcha.

**Comment by knusbaum** [comment]
Ok, Removed the python from that PR.

**Comment by maxice8** [comment]
in repo
