### ISSUE TITLE
KDE Plasma 6 Desktop Icons Reset

### ISSUE THREAD

**Issue by Norman-Normandy** [void-linux/void-packages#50764]
### Is this a new report?

Yes

### System Info

Void 6.9.3_1 x86_64 AuthenticAMD notuptodate rrrmmnFFFFFFFFF

### Package(s) Affected

kde5-6.0.5_1, kde5-baseapps-24.02.0_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Similar issues: https://bugs.kde.org/show_bug.cgi?id=486113

### Expected behaviour

When pinning or unpinning task manager widget icons they should persist after re-login. Changing positions of Desktop files should also persist.

### Actual behaviour

When pinning or unpinning icons onto the task manager widget they will reset after every login. This includes the Plasmashell Background Desktop files on the wallpaper. The positions will always reset. However manually editing "plasma-org.kde.plasma.desktop-appletsrc" allows pinned icons to persist. In other words it's not being written to for some reason.

This applies to both X11 and Wayland.

### Steps to reproduce

1. Follow the void manual for installing KDE Plasma.
2. Try and pin something to task manager widget
3. Move a Desktop file to a different position.
4. Re-login and see they did not persist.

Edit: Found a temporary "fix". After making any desktop changes run the command "kquitapp6 plasmashell && plasmashell". This will make changes persist after re-login.

**Comment by Luciogi** [comment]
Can you reproduce issue on newly created user?

**Comment by Norman-Normandy** [comment]
> Can you reproduce issue on newly created user?

Same result. 
Is it different for you?

**Comment by Luciogi** [comment]
bug is reproduce-able here too.

**Comment by Luciogi** [comment]
bug report already exist: https://bugs.kde.org/show_bug.cgi?id=486113

**Comment by Luciogi** [comment]
as for workaround, you should drag icon into taskbar

**Comment by Norman-Normandy** [comment]
> bug report already exist: https://bugs.kde.org/show_bug.cgi?id=486113

I've edited it into similar issues. But it only talks about the task manager widget and is reproduced on KDE neon.

> as for workaround, you should drag icon into taskbar

Doesn't make a difference. Also I already added a work around in an edit.

**Comment by triallax** [comment]
this should be fixed in kde 6.1

meanwhile, backporting https://invent.kde.org/plasma/libplasma/-/commit/3bc199d92402e316541d6dec00af9fee66afc341 to libplasma should fix the issue

**Comment by Norman-Normandy** [comment]
The libplasma backport changes seem to have fixed the two issues, 
after doing the usual "xbps-install -Su" **and** a full restart.

I'd say the issue is fixed from the void-linux side.

I'm closing the issue for now.
