### ISSUE TITLE
FFmpeg image file support in AVIF format - update

### ISSUE THREAD

**Issue by tuxslack** [void-linux/void-packages#50792]
$ ffmpeg -version
**ffmpeg version 4.4.4**

**FFmpeg  6.1.1-4+b2 (Debian)**

ffmpeg -formats | grep -i avif
  
libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
  **E avif            AVIF**

**Comment by tuxslack** [comment]
Why was this package update request closed?

**Comment by classabbyamp** [comment]
Please don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.
