### ISSUE TITLE
GNU Make package doesn't make a symlink for /usr/bin/gmake

### ISSUE THREAD

**Issue by rudzik8** [void-linux/void-packages#50812]
### Is this a new report?

Yes

### System Info

Void 6.6.32_1 x86_64 AuthenticAMD notuptodate rFFF

### Package(s) Affected

make-4.4.1_1

### Expected behaviour

Since our `make` implementation is GNU Make, it is really weird for it to not include a symlink for `gmake`.

For example, this is the output of `ls -l /usr/bin/ | grep "make"` on an Ubuntu system with `make` package installed is:
```
lrwxrwxrwx 1 root root           4 Feb 15  2022 gmake -> make
-rwxr-xr-x 1 root root      255696 Feb 15  2022 make
-rwxr-xr-x 1 root root        4905 Feb 15  2022 make-first-existing-target
```
And all `gmake` commands resolve without any problems there.

### Actual behaviour

CMake checks for `gmake` don't pass, its "simple test program" to verify `cc` doesn't compile (because it expects `gmake` to exist, and doesn't find it), and nobody's happy. :(

This is, however, easily fixed by doing `sudo ln -s /usr/bin/make /usr/bin/gmake`.

### Steps to reproduce

Try CMake'ing anything on a new Void install with `make` and `gcc` installed. [In my case, it was Minetest (+ its deps ofc)](https://github.com/minetest/minetest/issues/14746)

**Comment by ahesford** [comment]
Why would we make a symlink? The package installs itself as `make` and it's the default and expected version of make in a Void development environment. Also note that we have a metric ton of CMake packages in the repo, and they all build fine with our make.

Your CMake scripts are broken (and probably aimed at some BSD) if they demand to find GNU make as `gmake`.

**Comment by classabbyamp** [comment]
```
$ cat /usr/share/cmake-3.27/Modules/CMakeUnixFindMake.cmake
...
find_program(CMAKE_MAKE_PROGRAM NAMES gmake make smake)
...
```
pretty sure cmake should find `make` just fine without it being called `gmake`. what's the *exact* cmake output where this occurs?

**Comment by sgn** [comment]
> Your CMake scripts are broken (and probably aimed at some BSD) if they demand to find GNU make as `gmake`.
> 

If a CMake scripts care about its backend, or assuming its backend is Make, it's broken.

If a CMake scripts want GNU Make, it's very broken. If it  wants specially gmake, it shouldn't be existed.
