### ISSUE TITLE
Cannot update bash: REMOVE script failed to execute pre ACTION

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#50847]
### Is this a new report?

Yes

### System Info

Void 6.1.83_1 aarch64 Unknown notuptodate rFFFFFFF

### Package(s) Affected

bash-5.2.21_2

### Expected behaviour

It should be possible to update bash from bash-5.2.21_1 to bash-5.2.21_2.

### Actual behaviour

Errors out with

```
bash-5.2.21_1: updating to 5.2.21_2 ...
ERROR: bash-5.2.21_2: [remove] REMOVE script failed to execute pre ACTION: No such file or directory
ERROR: bash-5.2.21_2: failed to remove package: No such file or directory
ERROR: bash-5.2.21_2: [trans] failed to update package `No such file or directory'
Transaction failed! see above for errors.
```

### Steps to reproduce

1. Run `xbps-install -Su`
2. Receive error

**Comment by Anachron** [comment]
It seems like this issue only happens when running the update from remote, `ssh`ing into the machine and running `xbps-install -Su` works.

**Comment by Anachron** [comment]
Closing for now, as a workaround exists. Could be related to https://github.com/void-linux/void-packages/commit/c8e0c3dc98fd051c397d654f2bc05df0e12c5133

**Comment by Duncaen** [comment]
Probably related to `$TMPDIR`.

**Comment by Anachron** [comment]
Oh wow, yes I do set up that variable when `sshing` into the host. 

Thanks!

**Comment by Duncaen** [comment]
It should fallback to some tempdir defined by libc.
```

**Comment by Anachron** [comment]
No, my `$TMPDIR` is not empty, thus it will not default to the `libc` defined one.

I did not know XBPS uses the `TMPDIR` env. I am going to rename the var in my scripts to avoid future issues.
