### ISSUE TITLE
stellarium-0.18.0_1 dies with `free() invalid pointer`

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#509]
### System

* xuname:  
  *Void 4.16.14_1 x86_64 AuthenticAMD uptodate rrrdFFFFFF*
* package:  
  *stellarium-0.18.0_1*
  *mesa-ati-dri-17.3.3_5*

### Expected behavior
Start up and display GUI.
### Actual behavior
Exits during startup due to try to free() invalid pointer.
### Steps to reproduce the behavior

Try to run stellarium on a Void `x86_64` install with `mesa-ati-dri` for GL shader implementation. Here's a backtrace of a [gdb run with debug libs installed](https://gist.github.com/pullmoll/b682c26dd3ef9e4b96899c6db778c2fd).

I don't see where the problem arises from.

**Comment by newbluemoon** [comment]
I think this might be the same problem as https://github.com/voidlinux/void-packages/issues/13161 in the old repo.
A possible cause was pointed out in [this post](https://github.com/voidlinux/void-packages/issues/13161#issuecomment-378128149).

**Comment by pullmoll** [comment]
Thank you for pointing me in that direction.
I'm looking at that `void-qt5-anticrash.c` and thinking about how what it does can perhaps be applied before packaging apps like `stellarium`.

**Comment by mvf** [comment]
This is an issue with our Qt5 libraries, so patching apps with `void-qt5-anticrash` during packaging is not a solution IMO. Even if we could be sure that removing the versioning always has the desired effect, programs built outside of `xbps-src` could still crash.

It looks like at least the `libQt5Location` and `libQt5Positioning` SOs export the symbol. They shouldn't. It has to be globally unique, hence its `STB_GNU_UNIQUE` binding. I'm not sure what happens if an application that links against both uses `std::string`, because then there will be _two_ `Qt5` symbol versions on top of the `GLIBCXX_3.4` one.

IMHO we should:
- Find out why those rogue `_S_empty_rep_storage` exports exist in the first place
- Fix the relevant `qt5-*` package(s), e.g. `qt5-location`
- Rebuild dependent packages

**Comment by pullmoll** [comment]
I agree @mvf - I just don't know yet why we face this problem at all. It seems Void is the only distro with this kind of problem and as such it's maybe my overly complicated(?) `srcpkgs/qt5/template` causing it.

I think that perhaps linking with `-Wl,-F,libstdc++` could solve the problem, i.e. make the linker filter symbols found in `libstdc++` from the object files. But I may have misunderstood how `-F` works with `ld.bfd` and/or `ld.gold`.

**Comment by travankor** [comment]
I also think it is related to Void's specific build of qt, but I'm not sure. This would be a good thing to check/look for when it's time to update to qt 5.11.x.

In the mean time, try this as quick hack.

` ~/.stellarium/config.ini`:
```
[plugins_load_at_startup]
...
Satellites                             = false
...
```

**Comment by cr6git** [comment]
Just to see, this morning I compiled the latest [release](https://github.com/Stellarium/stellarium/releases) v0.18.1, but doesn't work:
````
*** Error in `stellarium': free(): invalid pointer: 0x00005613ce991300 ***
Abandon
````

**Comment by newbluemoon** [comment]
Despite the template saying

    only_for_archs="i686 i686-musl x86_64 x86_64-musl"

I was able to successfully (cross-)compile stellarium for armv7l-musl. Only `CMakeLists.txt` had to be tweaked a little:

```
--- CMakeLists.txt.orig	2018-07-01 08:04:19.000000000 +0200
+++ CMakeLists.txt	2018-07-17 08:52:24.193931980 +0200
@@ -418,24 +418,6 @@
      ADD_DEFINITIONS(-DUSE_OLD_QGLWIDGET)
 ENDIF()
 
-# Since Qt 5.4, linking to OpenGL is basically not required anymore,
-# because the QtGui module re-implements the GL functions, and perhaps even
-# dispatches the calls to a dynamically selected GL library.
-#
-# The only exception where this does not work with CMake is for
-# ES2-only/ANGLE-only builds, which are seemingly not included in
-# official Qt downloads, but may be required as a custom build
-# for some embedded systems. Interestingly, this works with qmake,
-# but CMake needs an explicit link definition.
-# See also this bug: https://bugreports.qt.io/browse/QTBUG-29132
-
-# Check if we have a GLES-only build
-# On dynamic builds, this property is also "GL"
-IF(${Qt5Gui_OPENGL_IMPLEMENTATION} MATCHES "GLES")
-     MESSAGE(STATUS "Building an OpenGL ES build (${Qt5Gui_OPENGL_IMPLEMENTATION})")
-     SET(STEL_GLES_LIBS Qt5::Gui_EGL Qt5::Gui_GLESv2)
-ENDIF()
-
 
 # Tell CMake to run moc when necessary:
 SET(CMAKE_AUTOMOC ON)
```

No idea where to find Qt5::Gui_EGL/GLESv2, but by not linking to them everything is just fine.

But now to the point I’m trying to make: When I run it on my RPi there are no problems with invalid pointers, no crashes, etc. It just works!

So could this problem be compiler related? I think the main difference between the native and cross compilers is that the former still use `--with-default-libstdcxx-abi=gcc4-compatible"` and the latter don’t. Maybe this is just by accident, however, I thought it might be worth mentioning. ;)

**Comment by newbluemoon** [comment]
And BTW: SuperCollider is working on my rpi without invalid pointer errors in sclang, too.

**Comment by pullmoll** [comment]
Oops! qt5-5.11.1 cannot be built with libressl. It requires openssl 1.1.x which libressl does not (yet fully?) support.
So I'm going to test removal of `-fno-delete-null-pointer-checks` here.

**Comment by mvf** [comment]
Awesome, @newbluemoon, looks like you found it! Indeed, at least on `x86_64`, removing `--with-default-libstdcxx-abi=gcc4-compatible` from the `gcc` build makes the nasty symbol disappear from the `qt5-location` SOs! I also checked all packaged binaries except the `aarch64`es, and only natively built binaries were broken. This includes `x86_64-musl`, but that doesn't crash, presumably because there the symbol is `STB_WEAK` instead of `STB_GNU_UNIQUE`.

**Comment by pullmoll** [comment]
Oh, looks like it's about time to drop gcc4 compatibility then.
Good to know the true source of all the problems.
I'm going to try locally and push an update for gcc then.

**Comment by Gottox** [comment]
@pullmoll Is there a plan how we rebuild everything without loading both old and new ABI in the same address space?

**Comment by pullmoll** [comment]
My hope is that only few packages will actually exhibit this difference between the CXX11 ABI being enabled or not. Now `libGL` is the first candidate to try to get to cleanly compile without setting `-D_GLIBCXX_USE_CXX11_ABI=0`.

I'll try to determine locally which of the libGL dependencies needs to be rebuilt with gcc-7.4.0_4 to avoid the need to disable the CXX11 ABI for it to link.

Other than that I have no plan yet, no, as I don't know where else it may be required to select either ABI. The goal definitely is to get rid of the gcc4 compatibility (i.e. CXX11 ABI disabling) in all packages where it is causing problems.

My box is busy around the clock building packages and I'm observing the results. I think we should use #983 to keep track of the issues and fix them. We have some users who are also able to test and fix packages and this will help to settle the issue methinks.

**Comment by cr6git** [comment]
> `-fno-delete-null-pointer-checks` ... IIRC it was required for gcc-6.x as a workaround for some problem (don't recall which, though)

I remember having seen this -flag on some other templates...
For example [firefox-esr](https://github.com/void-linux/void-packages/blob/master/srcpkgs/firefox-esr/template#L84) and [icecat](https://github.com/void-linux/void-packages/blob/master/srcpkgs/icecat/template#L27).

**Comment by pullmoll** [comment]
Issue is fixed.
