### ISSUE TITLE
Video playback makes the screen go blank for a second on a Wayland session

### ISSUE THREAD

**Issue by espectalll** [void-linux/void-packages#5098]
### System

* xuname:  
  Void 4.19.3_1 x86_64 GenuineIntel uptodate rFFFFF
* package:  
  no idea lol

### Expected behavior
Starting the reproduction of a video keeps the display on and starts playing such video.

### Actual behavior
Starting to reproduce a video makes the screen go blank for a period of about ~1-2 seconds.

### Steps to reproduce the behavior
Have an up-to-date installation of Void Linux with a Wayland session (my issue started after upgrading yesterday, November 24th 2018, in particular). My computer has an Nvidia Geforce 9400M with Nouveau (Intel Core 2 Duo without iGPU, so no dual GPU setup), which may be related. Start playing any video on (at least) Firefox, Totem, VLC, GNOME Web or `ffplay`. The issue isn't affecting video playback with at least `mpv` or Rage.

**Comment by Cogitri** [comment]
This is entirely on GNOME, if you want to keep the screen on during video playback (and fullscreen applications) you have to use extensions like https://extensions.gnome.org/extension/517/caffeine/.

**Comment by espectalll** [comment]
The issue is about the screen going off and on for about a second immediately after starting playing and has nothing to do with regular screen dimming/powering off.

**Comment by CameronNemo** [comment]
Are you still experiencing this issue?

**Comment by espectalll** [comment]
No, it's no longer happening! I think it's fair to close the ticket now
