### ISSUE TITLE
postfix - wrong runtime version of libssl

### ISSUE THREAD

**Issue by dezifit** [void-linux/void-packages#50987]
### Is this a new report?

Yes

### System Info

Void 6.6.35_1 x86_64-glibc

### Package(s) Affected

postfix-3.8.5_1, libssl3-3.3.0_1

### Expected behaviour

would be nice if postfix won't log a version mismatch warning on every incoming mail and could handle TLS connections

### Actual behaviour

postfix immediately complains about a version mismatch:
```
warning: run-time library vs. compile-time header version mismatch: OpenSSL 3.3.0 may not be compatible with OpenSSL 3.1.0
```

and fails to accept TLS connections
```
connect from internet.nl[62.204.66.10]
SSL_accept error from internet.nl[62.204.66.10]: -1
warning: TLS library problem: error:0A000102:SSL routines::unsupported protocol:ssl/statem/statem_srvr.c:1743:
lost connection after STARTTLS from internet.nl[62.204.66.10]

connect from internet.nl[62.204.66.10]
SSL_accept error from internet.nl[62.204.66.10]: -1
warning: TLS library problem: error:0A00018C:SSL routines::version too low:ssl/statem/statem_srvr.c:1743:
lost connection after STARTTLS from internet.nl[62.204.66.10]
```
which may be related to the version issue

### Steps to reproduce

just check the pkg versions or install and configure everything to see the log messages yourself

**Comment by MIvanchev** [comment]
@benalb maybe a rebuild against the current libssl is needed?
