### ISSUE TITLE
Incus fails to allow forwarded ports on Void due to systemd expectations....

### ISSUE THREAD

**Issue by acidvegas** [void-linux/void-packages#51015]
### Is this a new report?

Yes

### System Info

Void

### Package(s) Affected

incus

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/lxc/incus/issues/625

tldr; the solution is to run:
```
mkdir /sys/fs/cgroup/systemd
mount -t cgroup -o none,name=systemd systemd /sys/fs/cgroup/systemd 
```

and then you can start your containers......I guess incus on void is expecting systemd mounts in the cgroup

Classic case of devs only making things catered to ubuntu/debian builds

Reporting this here, doubt anyone is going to fix it.

Cheers

### Expected behaviour

Containers running

### Actual behaviour

Containers wont run and bind to forwarded ports.

### Steps to reproduce

read the linked issue

**Comment by ahesford** [comment]
Try changing `CGROUP_MODE` to `unified` in `/etc/rc.conf`, reboot, and see if the problem goes away without the extra mount.

**Comment by acidvegas** [comment]
> Try changing `CGROUP_MODE` to `unified` in `/etc/rc.conf`, reboot, and see if the problem goes away without the extra mount.

no dice.

```
[brandon@paloaltonetworks ~]$ incus start elasticsearch-container
Error: Error occurred when starting proxy device: Error: No such file or directory - Failed to safely open namespace file descriptor based on pidfd 3
```

**Comment by dkwo** [comment]
How exactly can I reproduce this?
With `unified` setup, I can run e.g. Ubuntu containers (without the mkdir/mount thing that was also in lxd runit service)
```
$ incus launch images:ubuntu/24.04 u1t
Launching u1t
$ incus list
+------+---------+--------------------+------+-----------+-----------+
| NAME |  STATE  |        IPV4        | IPV6 |   TYPE    | SNAPSHOTS |
+------+---------+--------------------+------+-----------+-----------+
| u1t  | RUNNING | 10.60.1.240 (eth0) |      | CONTAINER | 0         |
+------+---------+--------------------+------+-----------+-----------+
```

**Comment by classabbyamp** [comment]
if i had to guess this cgroup mount is done by elogind

**Comment by rekh127** [comment]
I'm also not seeing this with unified and no /sys/fs/cgroup/systemd maybe it's fixed in later versions of incus?
