### ISSUE TITLE
Gedit 47.0 does not change the language to pt_BR

### ISSUE THREAD

**Issue by tuxslack** [void-linux/void-packages#51022]
### Is this a new report?

Yes

### System Info

Void Linux kernel 6.6.35_1 x86_64

### Package(s) Affected

gedit 47.0 

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

gedit 47.0 does not change the language to pt_BR

Problem starts after updating in void linux

$ xbps-query -i gedit 
architecture: x86_64
changelog: https://gitlab.gnome.org/GNOME/gedit/-/raw/47.0/NEWS
filename-sha256: 80e8fcc131dd18f0631de7b4384bc044ae0921f9869d69757c028963a36b463b
filename-size: 2181KB
homepage: https://wiki.gnome.org/Apps/Gedit
install-date: 2024-06-26 23:17 -03
install-script: 1302B
installed_size: 12MB
license: GPL-2.0-or-later
maintainer: Orphaned <orphan@voidlinux.org>
metafile-sha256: a7c0ccd08fdc080e9c23c5b927c9823357fa7399c3c954dabe39a1105336cb33
pkgname: gedit
pkgver: gedit-47.0_1
remove-script: 1416B
repository: https://repo-default.voidlinux.org/current
run_depends:
	desktop-file-utils>=0
	gsettings-desktop-schemas>=0
	iso-codes>=0
	glib>=2.80.0_1
	gtk+3>=3.0.0_1
	pango>=1.24.0_1
	libgedit-tepl>=6.10.0_1
	libpeas>=1.0.0_2
	glibc>=2.39_1
	gdk-pixbuf>=2.22.0_1
	libgedit-gtksourceview>=299.2.1_1
	gspell>=1.8.0_1
	cairo>=1.8.6_1
	libgedit-amtk>=5.8.0_1
	libgedit-gfls>=0.1.0_1
	libgirepository>=1.30_1
shlib-provides:
	libgedit-47.so
shlib-requires:
	libc.so.6
	libcairo.so.2
	libgdk-3.so.0
	libgdk_pixbuf-2.0.so.0
	libgedit-amtk-5.so.0
	libgedit-gfls-1.so.0
	libgedit-gtksourceview-300.so.1
	libgedit-tepl-6.so.0
	libgio-2.0.so.0
	libgirepository-1.0.so.1
	libglib-2.0.so.0
	libgobject-2.0.so.0
	libgspell-1.so.2
	libgtk-3.so.0
	libm.so.6
	libpango-1.0.so.0
	libpeas-1.0.so.0
	libpeas-gtk-1.0.so.0
short_desc: Text editor for GNOME
source-revisions: gedit:d690dc78d25
state: installed

$ locale -a
C
C.utf8
POSIX
en_US.utf8
pt_BR.utf8

$ locale 
LANG=pt_BR.UTF-8
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE=C
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER="pt_BR.UTF-8"
LC_NAME="pt_BR.UTF-8"
LC_ADDRESS="pt_BR.UTF-8"
LC_TELEPHONE="pt_BR.UTF-8"
LC_MEASUREMENT="pt_BR.UTF-8"
LC_IDENTIFICATION="pt_BR.UTF-8"
LC_ALL=

### Expected behaviour

Gedit is in Brazilian Portuguese.

Currently, even changing it to pt_BR it returns to en in Gedit.

### Actual behaviour

When opening Gedit it does not identify the system language. It is always in English.

Even changing gedit to pt_BR.UTF-8 doesn't work.

### Steps to reproduce

$ gedit

**Comment by classabbyamp** [comment]
https://gitlab.gnome.org/GNOME/gedit/-/issues/593

**Comment by tuxslack** [comment]
> https://gitlab.gnome.org/GNOME/gedit/-/issues/593

Could the problem be in the gedit.mo file?

$ ls -lh /usr/share/locale/pt_BR/LC_MESSAGES/gedit.mo 
-rw-r--r-- 1 root root 68K jun 25 17:39 /usr/share/locale/pt_BR/LC_MESSAGES/gedit.mo

**Comment by tuxslack** [comment]
Do you know if the problem has been resolved?

**palliative solution:** Pluma

**Comment by oreo639** [comment]
> Do you know if the problem has been resolved?

Yes.
