### ISSUE TITLE
kodi build errors

### ISSUE THREAD

**Issue by ACR-Jeff** [void-linux/void-packages#51033]
### Is this a new report?

Yes

### System Info

Void 6.6.35_1 x86_64 AuthenticAMD uptodate hold rmFFFFFFFFF

### Package(s) Affected

kodi-19.4_9

### Expected behaviour

Expecting src-pkgs to install

### Actual behaviour

`../xbmc/windowing/X11/GLContext.h:30:11: error: 'uint64_t' does not name a type
   30 |   virtual uint64_t GetVblankTiming(uint64_t &msc, uint64_t &interval) { return 0; };
      |           ^~~~~~~~
../xbmc/windowing/X11/GLContext.h:14:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   13 | #include <X11/Xlib.h>
  +++ |+#include <cstdint>
   14 | 
[152/1719] Building CXX object build/windowing/X11/CMakeFiles/windowing_X11.dir/X11DPMSSupport.cpp.o
[153/1719] Building CXX object build/windowing/X11/CMakeFiles/windowing_X11.dir/WinSystemX11.cpp.o
In file included from ../xbmc/input/InputManager.h:19,
                 from ../xbmc/windowing/X11/WinSystemX11.cpp:18:
../xbmc/utils/Observer.h:47:23: warning: 'virtual Observable& Observable::operator=(const Observable&)' was hidden [-Woverloaded-virtual=]
   47 |   virtual Observable &operator=(const Observable &observable);
      |                       ^~~~~~~~
../xbmc/input/InputManager.h:69:24: note:   by 'const CInputManager& CInputManager::operator=(const CInputManager&)'
   69 |   CInputManager const& operator=(CInputManager const&) = delete;
      |                        ^~~~~~~~
../xbmc/utils/Observer.h:47:23: warning: 'virtual Observable& Observable::operator=(const Observable&)' was hidden [-Woverloaded-virtual=]
   47 |   virtual Observable &operator=(const Observable &observable);
      |                       ^~~~~~~~
In file included from ../xbmc/windowing/X11/WinSystemX11.cpp:20:
../xbmc/settings/DisplaySettings.h:147:21: note:   by 'CDisplaySettings& CDisplaySettings::operator=(const CDisplaySettings&)'
  147 |   CDisplaySettings& operator=(CDisplaySettings const&) = delete;
      |                     ^~~~~~~~
[154/1719] Building CXX object build/windowing/X11/CMakeFiles/windowing_X11.dir/WinEventsX11.cpp.o
In file included from ../xbmc/input/InputManager.h:19,
                 from ../xbmc/windowing/X11/WinEventsX11.cpp:17:
../xbmc/utils/Observer.h:47:23: warning: 'virtual Observable& Observable::operator=(const Observable&)' was hidden [-Woverloaded-virtual=]
   47 |   virtual Observable &operator=(const Observable &observable);
      |                       ^~~~~~~~
../xbmc/input/InputManager.h:69:24: note:   by 'const CInputManager& CInputManager::operator=(const CInputManager&)'
   69 |   CInputManager const& operator=(CInputManager const&) = delete;
      |                        ^~~~~~~~
[155/1719] Building CXX object build/windowing/X11/CMakeFiles/windowing_X11.dir/GLContextEGL.cpp.o
[156/1719] Building CXX object build/windowing/X11/CMakeFiles/windowing_X11.dir/VideoSyncGLX.cpp.o
[157/1719] Building CXX object build/windowing/X11/CMakeFiles/windowing_X11.dir/XRandR.cpp.o
ninja: build stopped: subcommand failed.
=> ERROR: kodi-19.4_9: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 1
=> ERROR:   in do_build() at common/build-style/cmake.sh:95`

### Steps to reproduce

cd /path/to/void-packages
./xbps-src pkg kodi
while building errors are presented

**Comment by meator** [comment]
This issue is indirectly resolved by #50183  (see https://github.com/void-linux/void-packages/pull/50183/files#diff-e773acf9a4e8390c3709adf717c186f6856c69ed5c2a6b5850260212d0ba7b98)

**Comment by ACR-Jeff** [comment]
> This issue is indirectly resolved by #50183 (see https://github.com/void-linux/void-packages/pull/50183/files#diff-e773acf9a4e8390c3709adf717c186f6856c69ed5c2a6b5850260212d0ba7b98)

Thank you, 
I read the Handling-Patches Man page https://github.com/void-linux/void-packages/blob/master/Manual.md#handling-patches
Read through https://github.com/void-linux/void-packages/pull/50183
Followed through with adding the patch you've posted above in reference 
https://github.com/void-linux/void-packages/pull/50183/files#diff-e773acf9a4e8390c3709adf717c186f6856c69ed5c2a6b5850260212d0ba7b98
But the same issue occurred, 
1. I proceeded to removing any previous build attempts from /hostdir/sources to be sure not to contaminate any further builds
2. ./xbps-src pkg kodi
3. Same issue occurred
Am I doing something incorrect or missing something to apply the patch, Etc?

**Comment by meator** [comment]
Try following https://xbps-src-tutorials.github.io/pr-testing-tutorial.html with pull request #50183

The primary focus of this pull request is spdlog and fmtlib, the Kodi fix there is ancillary.

Alternatively, you could copy the patch manually as you were (I assume) trying to do previously. You can copy [the raw patch](https://raw.githubusercontent.com/Calandracas606/void-packages/fmt-and-spdlog-update/srcpkgs/kodi/patches/cstdint.patch) to `srcpkgs/kodi/patches/cstdint.patch` in your void-packages clone. You can then proceed with building Kodi.

**Comment by ACR-Jeff** [comment]
> Try following https://xbps-src-tutorials.github.io/pr-testing-tutorial.html with pull request #50183
> 
> The primary focus of this pull request is spdlog and fmtlib, the Kodi fix there is ancillary.
> 
> Alternatively, you could copy the patch manually as you were (I assume) trying to do previously. You can copy [the raw patch](https://raw.githubusercontent.com/Calandracas606/void-packages/fmt-and-spdlog-update/srcpkgs/kodi/patches/cstdint.patch) to `srcpkgs/kodi/patches/cstdint.patch` in your void-packages clone. You can then proceed with building Kodi.

Thank you, 
I have never done a PR before so this may take some trial and error.

**Comment by sgn** [comment]
I suggest you update kodi to v21 ínstead.

**Comment by ACR-Jeff** [comment]
> I suggest you update kodi to v21 ínstead.

How do you update from srcpkgs not built or installed? I have followed the quick start guide, I've read everything I can think of on the table of contents, Couldn't find anything that actually updated a scrpkg from one version to another. The version of Kodi in the template is 19.4 no matter what I attempt.

I have attempted to work with the PR yet it crashed my system due to using up all of my 32gb of ram. Possibly something I have done incorrectly.

**Comment by ACR-Jeff** [comment]
Well I tried everything I can think of and going to call it on this one for now, I may come back to it in the future when I do some more learning on the PR route, Etc. Thank you for your time and information.
