### ISSUE TITLE
Steam creashing

### ISSUE THREAD

**Issue by zukas97** [void-linux/void-packages#51043]
### Is this a new report?

Yes

### System Info

Void 6.6.35_1 x86_64 GenuineIntel uptodate rrrmFFFFF

### Package(s) Affected

steam-1.0.0.79_1, glibc-32bit-2.39_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://bbs.archlinux.org/viewtopic.php?id=295425

### Expected behaviour

open steam

### Actual behaviour

steam crashes before opening

based on the thread from arch, The problem is probably because of the version of glibc-32bit being used. 

Error found in log:
```
src/vgui2/src/surface_linux.cpp (1954) : glXChooseVisual failed
src/vgui2/src/surface_linux.cpp (1954) : glXChooseVisual failed
src/vgui2/src/surface_linux.cpp (1954) : Fatal assert; application exiting
src/vgui2/src/surface_linux.cpp (1954) : Fatal assert; application exiting
06/29 20:11:43 Init: Installing breakpad exception handler for appid(steam)/version(1718904662)/tid(3827)
assert_20240629201143_8.dmp[3906]: Uploading dump (out-of-process)
/tmp/dumps/assert_20240629201143_8.dmp
[zukas@zukas-pc ~]$ assert_20240629201143_8.dmp[3906]: Finished uploading minidump (out-of-process): success = yes
assert_20240629201143_8.dmp[3906]: response: CrashID=bp-b41348a8-2427-4c9f-a22f-326132240629
assert_20240629201143_8.dmp[3906]: file ''/tmp/dumps/assert_20240629201143_8.dmp'', upload yes: ''CrashID=bp-b41348a8-2427-4c9f-a22f-326132240629''
```

### Steps to reproduce

1.Install steam and it's dependancies
2.try to run steam

**Comment by zukas97** [comment]
according to the post on the arch forum, this is fixed in glibc-32bit-2.39_4

**Comment by classabbyamp** [comment]
the `-4` refers to an arch-specific change, not an upstream one, so it's not comparable to void's `_3`

the fix mentioned is: https://gitlab.archlinux.org/archlinux/packaging/packages/glibc/-/commit/374116c315e3326ae245f724539cf8723b141a90

**Comment by oreo639** [comment]
It would be helpful if anyone can provide a backtrace of the crash on Void (not Arch).

**Comment by zukas97** [comment]
> It would be helpful if anyone can provide a backtrace of the crash on Void (not Arch).

I edited the post and added the errors.

**Comment by classabbyamp** [comment]
what's in the dmp file?

**Comment by zukas97** [comment]
> what's in the dmp file?

Just the same thing that was outputed to the terminal

**Comment by zukas97** [comment]
This was resolved after removing and reinstalling mesa-dri-32bit. not sure what the problem was.

**Comment by zukas97** [comment]
This was resolved after removing and reinstalling mesa-dri-32bit. not sure what the problem was.
