### ISSUE TITLE
Package Request: zen-kernel

### ISSUE THREAD

**Issue by espectalll** [void-linux/void-packages#5105]
An old package request, first at voidlinux/void-packages#2814

**Comment by espectalll** [comment]
I understand mainline is already enough work, but I would like to leave it in case there's a maintainer which would like to give it a try

**Comment by maxice8** [comment]
Sorry but we do not support Linux patchsets.

**Comment by agausmann** [comment]
I am currently maintaining a zen-kernel package [in my own repo](https://github.com/agausmann/void-packages/tree/master/srcpkgs/zen-kernel), but I won't be providing public builds
