### ISSUE TITLE
net-snmp: snmpconf is missing?

### ISSUE THREAD

**Issue by SpidFightFR** [void-linux/void-packages#51105]
### Is this a new report?

Yes

### System Info

Void 6.9.5_1 x86_64 GenuineIntel/VM uptodate rF

### Package(s) Affected

net-snmp-5.9.1_5

### Expected behaviour

A binary named `snmpconf` is provided by net-snmp, written in perl, allows to create a default config (see `snmpd.conf(5)`).

### Actual behaviour

This binary is absent. :(
I can't find a config to edit for snmpd

### Steps to reproduce

1. Install net-snmp
2. Run snmpd
3. (Nothing happens)

**Comment by Piraty** [comment]
would this work for you?
```
--- a/srcpkgs/net-snmp/template
+++ b/srcpkgs/net-snmp/template
@@ -38,2 +38,6 @@ do_install() {
 
+post_install() {
+	vsconf EXAMPLE.conf
+}
+
 libnet-snmp_package() {
```
i am hesitant to make net-snmp depend on perl simply for the script

**Comment by Piraty** [comment]
a630adc19ec9517ab4b48283cbe4026aba20606e
