### ISSUE TITLE
Possible memory leak in Gnome 46

### ISSUE THREAD

**Issue by piekay** [void-linux/void-packages#51135]
### Is this a new report?

Yes

### System Info

Void 6.6.37_1 x86_64 AuthenticAMD uptodate rrFFFFFF

### Package(s) Affected

gnome-core-46.0_1

### Expected behaviour

Memory usage shouldn't increase over time

### Actual behaviour

Memory usage increases over time

### Steps to reproduce

1. boot into the Gnome Desktop on Void Linux
2. Let it run for a few hours/days

**Comment by piekay** [comment]
Today my computer froze due to a memory overflow. After rebooting memory usage went back to ~6GB without any GUI applications running. The only weird thing is that the memory usage reported by tools like top is only 150MB and adding them all up doesn't even get close to the amount of memory used, even when being run as root.

**Comment by ahesford** [comment]
This isn't an actionable bug report. You haven't even presented evidence that `gnome-core` is the culprit here. Do you have any more relevant information that can help diagnose the problem?

**Comment by piekay** [comment]
Yeah, that was just anecdotal since it started around the Gnome 46 update, I should've tested it more before that. I now killed and deactivated all services / programs except for runit and the default agetty-ttys. I still have 4.16GB of used memory according to free -m and htop

**Comment by piekay** [comment]
I tested this very extensibly and noticed that it is not gnome, so I will close this issue and open a new issue for the application that causes this issue
