### ISSUE TITLE
c-ares package missing

### ISSUE THREAD

**Issue by okawo80085** [void-linux/void-packages#51141]
### Is this a new report?

Yes

### System Info

Void 6.6.37_1 x86_64 AuthenticAMD notuptodate rrrrmmnFFFFFFF

### Package(s) Affected

c-ares

### Expected behaviour

`xbps-install c-ares`  installs the package

### Actual behaviour

Install fails to find the package `c-ares-1.32.0_1`
```
xbps-install c-ares    

Name   Action    Version           New version            Download size
c-ares update    1.31.0_1          1.32.0_1               87KB 

Size to download:               87KB
Size required on disk:         183KB
Space available on disk:       702GB

Do you want to continue? [Y/n] 

[*] Downloading packages
ERROR: [trans] failed to download `c-ares-1.32.0_1' signature from `https://repo-fastly.voidlinux.org//current': Not Found
Transaction failed! see above for errors.

```
Most annoying part is that it breaks `base-chroot` package because it has `c-ares` as a dependency

### Steps to reproduce

`xbps-install c-ares`

**Comment by classabbyamp** [comment]
it's probably still syncing, try again in a bit

**Comment by okawo80085** [comment]
I noticed that the template for this package was updated only 3 hours ago, could it be that the new build of the version didn't propagate yet?

**Comment by okawo80085** [comment]
Ah yup, gonna try in a bit

**Comment by okawo80085** [comment]
Yeah its fine now, thx
