### ISSUE TITLE
mbpfan: Improve advice on install

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#51179]
### Is this a new report?

Yes

### System Info

Void 6.6.37_1 x86 64 GenuineIntel uptodate rFF

### Package(s) Affected

mbpfan-2.2.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/linux-on-mac/mbpfan/issues/190

### Expected behaviour

I installed void in a macbook pro. I got advice to run `sudo mbpfan -t`.
I expected it to work and mbpfan to enable the fan.

I suggest changing the advice to something like "edit /etc/mbpfan.conf"

### Actual behaviour

```
$ sudo mbpfan -t
Starting the tests..
It is normal for them to take a bit to finish.
Error: max_fan_speed value is not 6200
Tests run: 5
```

### Steps to reproduce

1. Install void on a macbook air.
2. Install mbpfan
3. run `sudo mbpfan -t`

**Comment by ahesford** [comment]
Seems like this is working as expected, and the behavior change should be considered upstream.
