### ISSUE TITLE
epiphany: Missing "Save as Web Application".

### ISSUE THREAD

**Issue by Eloitor** [void-linux/void-packages#51218]
### Is this a new report?

Yes

### System Info

Void 6.6.37_1 x86_64 GenuineIntel uptodate FFFFFFFFF

### Package(s) Affected

epiphany-46.1_1

### Expected behaviour

From the documentation: https://help.gnome.org/users/epiphany/stable/browse-webapps.html.en
I expect to see a menu item "Save as Web Application…".

I have epiphany-46.1 installed in alpine linux and it appears.

### Actual behaviour

The item "Save as Web Application…" is missing.

### Steps to reproduce

1. Install an run epiphany
2. Go to a website that is a web application, for example https://excalidraw.com/
3. Open the hamburger menu, and see that the item "Save as Web Application…" is missing.

**Comment by oreo639** [comment]
"Install as Web Application" shows and works for me in epiphany.

**Comment by Eloitor** [comment]
![imatge](https://github.com/user-attachments/assets/05ea350e-2083-4d8b-b1c3-0f1e86ab17ff)

**Comment by oreo639** [comment]
https://gitlab.gnome.org/GNOME/epiphany/-/issues/1981

The setting won't be visible if your currently running xdg-desktop-portal implementation doesn't provide `org.freedesktop.portal.DynamicLauncher`. What desktop are you using?

**Comment by oreo639** [comment]
xdg-desktop-portal-gtk should be enough to provide DynamicLauncher btw.

**Comment by Eloitor** [comment]
> What desktop are you using?
xfce

**Comment by Eloitor** [comment]
Yup it worked, should this be added as dependency to xfce or epiphany?

**Comment by oreo639** [comment]
If it needed to be added, it would probably be xfce since the portal implementations are DE specific (`xdg-desktop-portal-gtk` is relatively portable though) and epiphany works fine without DynamicLauncher, just missing features.
