### ISSUE TITLE
Package update: Please update postrgeSQL to version 10 (or 11)

### ISSUE THREAD

**Issue by revington** [void-linux/void-packages#5123]
PostgreSQL v. 10 was released on 2017-10-05
PostgreSQL v. 11 was released on 2018-10-18 (current stable)

**Comment by Hoshpak** [comment]
The versions have been detected by the [update check](https://alpha.de.repo.voidlinux.org/void-updates/void-updates_2018-11-26.txt). There's no need to open an issue.
