### ISSUE TITLE
PHP: Extension GD not built with JPEG support

### ISSUE THREAD

**Issue by ILadis** [void-linux/void-packages#51237]
### Is this a new report?

Yes

### System Info

Void 6.6.35_1 armv7l Unknown uptodate hold rFFFFF

### Package(s) Affected

php-8.3_1, php-gd-8.3_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No

### Expected behaviour

I've enabling the `gd` extension in my `php.ini`. By doing so **I could previously** parse JPEG images using [`imagecreatefromstring`](https://www.php.net/manual/en/function.imagecreatefromstring.php) for example.

The `gd` library still seems to have support for JPEG images because I could [compile and run their C example](https://libgd.github.io/manuals/2.3.3/files/preamble-txt.html) which outputs a JPEG test image.

My guess is that some update to the `php8.3` or `php8.3-gd` package broke the support for JPEG images.

### Actual behaviour

Now the following error is thrown:

```sh
$ php -r 'imagecreatefromstring(file_get_contents("test.jpg"));'
imagecreatefromstring(): No JPEG support in this PHP build
```

Also `gd_info()` mentions no support for JPEG images:

```sh
$ php -r 'print_r(gd_info());'
Array
(
    [GD Version] => 2.3.3
    [FreeType Support] => 1
    [FreeType Linkage] => with freetype
    [GIF Read Support] => 1
    [GIF Create Support] => 1
    [JPEG Support] => 
    [PNG Support] => 
    [WBMP Support] => 1
    [XPM Support] => 
    [XBM Support] => 1
    [WebP Support] => 
    [BMP Support] => 
    [AVIF Support] => 
    [TGA Read Support] => 
    [JIS-mapped Japanese Font Support] => 
)
```

### Steps to reproduce

The following command should not output an error message (provided that `test.jpg` exists):

```sh
php -r 'imagecreatefromstring(file_get_contents("test.jpg"));'
```

**Comment by classabbyamp** [comment]
cc @TinfoilSubmarine

**Comment by ILadis** [comment]
Thanks for fixing, can confirm it's working again.
