### ISSUE TITLE
Contributing guide doesn't mention 80 char commit descriptions

### ISSUE THREAD

**Issue by popey** [void-linux/void-packages#51252]
I did a small [pr](https://github.com/void-linux/void-packages/pull/51219), which failed CI due to my commit description being over 80 characters. This was my first contribution, so I wasn't aware of this. I went looking to see which documentation I'd missed and couldn't find a reference to it.

There's no reference to it in [CONTRIBUTING.md](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md), which was the main document I used. 

Perhaps a one-line in there might be useful, so others don't hit this in future?

**Comment by Bnyro** [comment]
It does ask you to run `xlint template`, which does in fact report if the `short_desc` is too long.

So you probably didn't really read `CONTRIBUTING.md` properly, otherwise you would have caught that error before submitting the PR.

**Comment by classabbyamp** [comment]
this is the general convention in all of git, not just void

**Comment by ahesford** [comment]
What would others "hit"? The lint check exists to enforce conventions, and the messages teach you what we expect.
