### ISSUE TITLE
Lazarus package is outdated (v2.2.0 while Lazarus last release is 3.4)

### ISSUE THREAD

**Issue by Alexey-T** [void-linux/void-packages#51288]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/lazarus/template
the text shows that it is 2.2.0.
Can you pls update it to 3.x latest?

**Comment by classabbyamp** [comment]
Please don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.
