### ISSUE TITLE
"xbps-remove -oO" just removed xf86-video-intel and libXvMC resulting in the gui login no longer being available

### ISSUE THREAD

**Issue by gc-user** [void-linux/void-packages#51291]
Not sure where this issue originated from, thus I chose the free from report.

After updating packages using
`xbps-install -Su`

I, as usual, used
`xbps-remove -oO`

to clean up the cache.  There was a promt to remove the packages removed **xf86-video-intel** and **libXvMC**. I assumed it would be ok, thinking that the just updated / installed package "xorg-video-drivers" might  replace what xf86-video-intel provided.

But when the system didn't come back to the gui login screen after standby and didn't boot to the gui logn screen after forced shotdown and new boot, I learned that something went wrong. Thanks to zfs and a different BE I was able to figure out the correct name of the xf86-video-intel package and was able to force-reinstall it on the working BE in order to get the package downloaded (and installed) into the xbps-cache folder from which is was missing even though it was installed. This process also downloaded and installed libXvMC along with the former package - luckily, because I couldn't remember the name correctly and thus find it. It also was not in the xbps-cache folder, also even though it was installed on that BE.

That helped me the get the package names and be able to reinstall them on the main BE and thus be able to get back the gui login screen.

I have no idea why those packages were prompted to be removed. I also son't know why package files are removed from the cache folder even though they are still installed.

**Comment by classabbyamp** [comment]
xf86-video-intel is not recommended[^1] for most intel GPUs anymore (and hasn't been for a long time), so it was removed from the dependencies of `xorg-video-drivers` in 74e7debd163c881d12c3ac8c3bf02ccd98c30453. you can still install it manually or mark it as manually installed (`xbps-pkgdb -m manual xf86-video-intel`).

[^1]: "For newer Intel chipsets, the [DDX](https://docs.voidlinux.org/config/graphical-session/xorg.html#ddx) drivers may interfere with correct operation. This is characterized by graphical acceleration not working and general graphical instability. If this is the case, try removing all `xf86-video-*` packages." (https://docs.voidlinux.org/config/graphical-session/graphics-drivers/intel.html#troubleshooting)

**Comment by classabbyamp** [comment]
I would also recommend not doing `xbps-remove -O` until you confirm your system is working, and to read the list of packages to be removed by `xbps-remove -o` carefully. Run these command separately, and do not be afraid to press `n` and mark a package as manual if you don't want it uninstalled.

**Comment by classabbyamp** [comment]
Additionally, `libXvMC` is probably unrelated to this, and you didn't have to go to another BE to fix this, you could just switch to a tty and install the package

**Comment by gc-user** [comment]
> xf86-video-intel is not recommended[1](#user-content-fn-1-d723bcd5715b506480ea6fc6e5ea050b) for most intel GPUs anymore (and hasn't been for a long time), so it was removed from the dependencies of `xorg-video-drivers` in [74e7deb](https://github.com/void-linux/void-packages/commit/74e7debd163c881d12c3ac8c3bf02ccd98c30453). you can still install it manually or mark it as manually installed (`xbps-pkgdb -m manual xf86-video-intel`).
> 
> ## Footnotes
> 1. "For newer Intel chipsets, the [DDX](https://docs.voidlinux.org/config/graphical-session/xorg.html#ddx) drivers may interfere with correct operation. This is characterized by graphical acceleration not working and general graphical instability. If this is the case, try removing all `xf86-video-*` packages." (https://docs.voidlinux.org/config/graphical-session/graphics-drivers/intel.html#troubleshooting) [↩](#user-content-fnref-1-d723bcd5715b506480ea6fc6e5ea050b)

That explains why the package was marked "orphaned" and to be removed.

I wonder why my Kaby Lake system needed at least one of the two packages for work properly if libva-intel-driver, linux-firmware-intel, mesa-vulkan-intel and mesa-dri are all installed and should suffice according to the void docs...

**Comment by classabbyamp** [comment]
did you do any configuration in `/etc/X11/xorg.conf.d`?

**Comment by gc-user** [comment]
> I would also recommend not doing `xbps-remove -O` until you confirm your system is working, and to read the list of packages to be removed by `xbps-remove -o` carefully. Run these command separately, and do not be afraid to press `n` and mark a package as manual if you don't want it uninstalled.

The -oO option was "introduced" by the Trident folk back then into my routine...

The "problem" of pressing `n` is that it will come back the next time again. :-) But I noticed that "reinstalling" / forced-installing such a package would remove it from that list. Probably the same effect as your command for marking it as manually installed.

**Comment by gc-user** [comment]
> Additionally, `libXvMC` is probably unrelated to this, and you didn't have to go to another BE to fix this, you could just switch to a tty and install the package

Well, as I didn't remember the name of the package, I had to check via the other BE... :-)

**Comment by gc-user** [comment]
> did you do any configuration in `/etc/X11/xorg.conf.d`?

Yep, there's a monitor.conf and a keyboard.conf

**Comment by classabbyamp** [comment]
what's in those confs?

**Comment by gc-user** [comment]
> what's in those confs?

The keyboard.conf sets locale for the keyboard, apparently. Not sure if I created that. I only remember setting locale via rc.conf

The monitor.conf contains definitions for `monitors` (internal and external), `devices` (cards, I guess, also for internal and external) and `screen` (resolution for internal and external monitor, which differ from each other). And then there's `ServerLayout` and `ServerFlags`.

**Comment by classabbyamp** [comment]
exact contents, not a summary

**Comment by gc-user** [comment]
> exact contents, not a summary

Ahh, ok.

Monitor.conf:

```
Section "Monitor"
    Identifier     "External"
    VendorName     "Sony"
    ModelName      "Sony"
    
    HorizSync    28.0-78.0
    VertRefresh  50.0-76.0
	
    Option "DPMS" "false"
EndSection

Section "Monitor"
    Identifier     "Internal"
    VendorName     "Lenovo"
    ModelName      "Lenovo"
    
    HorizSync    28.0-78.0
    VertRefresh  50.0-76.0
	
    Option "DPMS" "false"
EndSection

Section "ServerFlags"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "0"
    Option "BlankTime" "0"
EndSection

Section "ServerLayout"
    Identifier "ServerLayout0"
EndSection

Section "Device"
    Identifier      "Card0"
    Screen           0
EndSection

Section "Device"
    Identifier      "Card0"
    Screen           1
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Card0"
    Monitor        "External"
    DefaultDepth   24
    SubSection     "Display"
        Depth      24 
        Modes      "2560x1440"
    EndSubSection
EndSection

Section "Screen"
    Identifier     "Screen1"
    Device         "Card1"
    Monitor        "Internal"
    DefaultDepth   24
    SubSection     "Display"
        Depth      24 
        Modes      "1920x1080"
    EndSubSection
EndSection
```


Keyboard.conf:

```
Section "InputClass"
	Identifier "set keyboard locale"
	MatchIsKeyboard "on"	# Limit these settings to keyboards
#	Driver "libinput"
	# Keyboard layout - comma-separated list for multiple layouts
	Option "XkbLayout" "en"
	# Keyboard variant - comma-separated list matching XkbLayout line
# 	Option "XkbVariant" "qwerty"
EndSection

```

**Comment by classabbyamp** [comment]
don't see anything obviously related to the DDX driver (`xf86-video-intel`), but maybe something in the xorg log would show, if you want to remove the package again and test. or if not, whatever.

**Comment by gc-user** [comment]
> don't see anything obviously related to the DDX driver (`xf86-video-intel`), but maybe something in the xorg log would show, if you want to remove the package again and test. or if not, whatever.

I just uninstalled `xf86-video-intel` again because I couldn't find the xorg error message from earlier in the xorg log file.

This is what is says (same as earlier) - when executing startx from tty:
(Note: machine time stamps at the beginning of the lines removed to declutter)


```
Current version of pixman: 0.43.4
Before reporting problems, check http://wiki.x.org to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Tue Jul 16 19:39:41 2024
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(==) ServerLayout "ServerLayout0"
(**) |-->Screen "Screen0" (0)
(**) |   |-->Monitor "External"
(**) |   |-->Device "Card0"
(**) |   |-->GPUDevice "Card0"
(**) Option "BlankTime" "0"
(**) Option "StandbyTime" "0"
(**) Option "SuspendTime" "0"
(**) Option "OffTime" "0"
(**) Allowing byte-swapped clients
(==) Automatically adding devices
(==) Automatically enabling devices
(==) Automatically adding GPU devices
(==) Automatically binding GPU devices
(==) Max clients allowed: 256, resource mask: 0x1fffff
(WW) The directory "/usr/share/fonts/X11/OTF" does not exist.
 	Entry deleted from font path.
(==) FontPath set to:
	/usr/share/fonts/X11/misc,
	/usr/share/fonts/X11/TTF,
	/usr/share/fonts/X11/Type1,
	/usr/share/fonts/X11/100dpi,
	/usr/share/fonts/X11/75dpi
(==) ModulePath set to "/usr/lib64/xorg/modules"
(II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
(II) Module ABI versions:
	X.Org ANSI C Emulation: 0.4
	X.Org Video Driver: 25.2
	X.Org XInput driver : 24.4
	X.Org Server Extension : 10.0
(II) xfree86: Adding drm device (/dev/dri/card0)
(II) Platform probe for /sys/devices/pci0000:00/0000:00:02.0/drm/card0
(--) PCI:*(0@0:2:0) 8086:5916:17aa:5062 rev 2, Mem @ 0xe0000000/16777216, 0xc0000000/536870912, I/O @ 0x0000e000/64, BIOS @ 0x????????/131072
(II) Open ACPI successful (/var/run/acpid.socket)
(II) LoadModule: "glx"
(II) Loading /usr/lib64/xorg/modules/extensions/libglx.so
(II) Module glx: vendor="X.Org Foundation"
	compiled for 1.21.1.13, module version = 1.0.0
	ABI class: X.Org Server Extension, version 10.0
(==) Matched intel as autoconfigured driver 0
(==) Matched modesetting as autoconfigured driver 1
(==) Matched fbdev as autoconfigured driver 2
(==) Matched vesa as autoconfigured driver 3
(==) Assigned the driver to the xf86ConfigLayout
(II) LoadModule: "intel"
(WW) Warning, couldn't open module intel
(EE) Failed to load module "intel" (module does not exist, 0)
(EE) No drivers available.
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
```

**Comment by classabbyamp** [comment]
well, definitely something wrong without it, but I'm not sure what and why. i guess keep using `xft86-video-intel` if it works for your

**Comment by gc-user** [comment]
> well, definitely something wrong without it, but I'm not sure what and why. i guess keep using `xft86-video-intel` if it works for you

That's what I'll do... :-)
To me it reads as if in `xf86-video-intel` contains some driver that the system / xorg misses / needs - at least when monitor.conf tells it to look for / load a Intel Module.

Thanks for your support and patience!

**Comment by gc-user** [comment]
Ok, so, I did another test with uninstalling `xf86-video-intel` **and** renaming /etc/X11/xorg.conf.d/monitor.conf to /etc/X11/xorg.conf.d/monitor.conf**x** so that the file isn't recognized as a conf file anymore and isn't taken notice of by xorg, there is no problem with getting to the login gui after standby. Apparently, if a monitor.conf file is present (and has content, I assume) `xf86-video-intel` still seems to be necessary. For whatever reason.

**Comment by classabbyamp** [comment]
it's something in the file that's causing it, maybe the device sections

**Comment by gc-user** [comment]
I'll try some "bisecting" of the file... :-)

**Comment by gc-user** [comment]
Yeah, it's the device section. But I learned that even though it the gui login screen works fine with the section either commented-out or made sane by reducing the two section to one and instead adding 2 options, it screws up my monitor setup.

So far, the only way to get the monitor setup correct is by leaving the monitor.conf as it is and leave `xf86-video-intel` installed. Although I haven't tested yet the alternative monitor.conf modification with `xf86-video-intel` installed, only with it uninstalled.

I'd have to do more testing. For now I just leave it as it is.

Thanks again for your help and input!

**Comment by Vinfall** [comment]
While LightDM login screen/lightdm-gtk-greeter works for me, removing `xf86-video-intel` broke my dual display layout and I could only use the primary display after reboot. Installing the package solves the problem immediately without a reboot.

From the linked troubleshooting page, I think it's related to Broadwell (gen 5) iGPU, not sure how it affects my Mesa Iris Xe in gen 11 NUC.

**Comment by gc-user** [comment]
> While LightDM login screen/lightdm-gtk-greeter works for me, removing `xf86-video-intel` broke my dual display layout and I could only use the primary display after reboot. Installing the package solves the problem immediately without a reboot.
> 
> From the linked troubleshooting page, I think it's related to Broadwell (gen 5) iGPU, not sure how it affects my Mesa Iris Xe in gen 11 NUC.

For me it's on a KabyLake. So, maybe Intel iGPU in general or at least several generations that share some feature(s).
