### ISSUE TITLE
`nix` is very very out of date (v2.11 was released almost 2 years ago!!)

### ISSUE THREAD

**Issue by arnu515** [void-linux/void-packages#51311]
### Is this a new report?

Yes

### System Info

Void 6.6.40_1 x86_64 AuthenticAMD uptodate F  

### Package(s) Affected

nix-2.11.0_10

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No, this issue is specific to void

### Expected behaviour

The latest version of the package should be available.

Nix v2.11 is very old (2 years old!), and since then, many changes have been made to nix. 

I know your issue template mentions to not request package updates, but according to [this link](https://repo-default.voidlinux.org/void-updates/void-updates.txt), it seems that the nix package is orphaned.

I would request for someone to please update this version. I tried to do it myself, but I wasn't able to figure it out.

Thanks!

### Actual behaviour

This version of nix is not able to build any nixpkgs, or run any nix files.

The latest version is 2.23

### Steps to reproduce

1. Install nix
2. Try running a flake.nix file
3. It fails

**Comment by Chocimier** [comment]
However, a quality pull request may help.
