### ISSUE TITLE
Missing xdg-shell-client-protocol.h???

### ISSUE THREAD

**Issue by pudiva** [void-linux/void-packages#51366]
### Is this a new report?

Yes

### System Info

Void 6.6.41_1 x86_64 GenuineIntel uptodate rrrrmdFFFFFFF

### Package(s) Affected

???

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

* https://github.com/raysan5/raylib/issues/2473
* https://github.com/go-gl/glfw/issues/278

### Expected behaviour

`xlocate xdg-shell-client-protocol.h` should give me some package with the header file? This is required to build GLFW

### Actual behaviour

`xlocate xdg-shell-client-protocol.h` only gives me a QT package with this file bundled in as private like this

```
qt6-wayland-private-devel-6.7.2_2  /usr/include/qt6/QtWaylandClient/6.7.2/QtWaylandClient/private/wayland-xdg-shell-client-protocol.h
```

### Steps to reproduce

`xlocate xdg-shell-client-protocol.h`

**Comment by classabbyamp** [comment]
there is no package with that file in it because it's supposed to be generated: https://github.com/glfw/glfw/issues/2261#issuecomment-1410574884

**Comment by pudiva** [comment]
I just found out that `make clean all` doesn't work, but `make clean && make all` does... 🤷‍
