### ISSUE TITLE
README.md: Insert `--depth 1` for clone instruction

### ISSUE THREAD

**Issue by vishalpaudel** [void-linux/void-packages#51400]
`--depth=1` signifies that we only care about the most recent commits, which should be the case for `void-packages`. This should make the `git clone` a little bit faster.

This would also require the user to `git pull --depth 1`. So I would expect this issue to be unimportant and potentially confusing. Nevertheless, raising this issue to learn.

**Comment by classabbyamp** [comment]
that isn't the case for most usage of void-packages, and a [treeless or blobless clone](https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/) would be better than `--depth 1`

**Comment by vishalpaudel** [comment]
makes sense
