### ISSUE TITLE
Package request: Hyprland

### ISSUE THREAD

**Issue by polyrtm** [void-linux/void-packages#51414]
### Package name

hyprland

### Package homepage

https://hyprland.org

### Description

Hyprland is an independent, highly customizable, dynamic tiling Wayland compositor that doesn't sacrifice on its looks. It was [denied in the past](https://github.com/void-linux/void-packages/issues/37544) for using its own packaged wlroots version that was incompatible with the one in the repo, but it was recently rewritten and no longer depends on wlroots, so it may be easier to add now.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/issues/50824

**Comment by polyrtm** [comment]
I'm aware it was marked as not planned, but the reason given for that decision no longer applies to the package. I even linked the issue in which this was discussed in my original post.

**Comment by polyrtm** [comment]
Whoops, I misread.
