### ISSUE TITLE
OBS tries to load built-in plugins twice then crashes on exit.

### ISSUE THREAD

**Issue by KynikossDragonn** [void-linux/void-packages#51434]
### Is this a new report?

Yes

### System Info

Void 6.6.41_1 x86_64 GenuineIntel uptodate hold rrmDFFFFFFFFFFFFFF

### Package(s) Affected

obs-30.2.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/obsproject/obs-studio/issues/11029

### Expected behaviour

OBS should not be trying to load the built-in plugins twice, and it definitely should not double free on exit.

This was not a problem when I was using 30.1.2 and I can't see anything wrong with the template as to why this is messed up now.

### Actual behaviour

OBS is attempting to load the built-in plugins more than once and when exiting it will result in a double free or other memory corruption error and will throw a SIGABRT which will prevent OBS from even producing it's own crash log.

I've attached terminal output from running it under GDB:
[obs_gdb.txt.gz](https://github.com/user-attachments/files/16368895/obs_gdb.txt.gz)

### Steps to reproduce

1. Open OBS
2. Attempt to close OBS

**Comment by sgn** [comment]
https://github.com/obsproject/obs-studio/issues/11029#issuecomment-2249747587
