### ISSUE TITLE
deluge-gtk broken dependency to python3-cryptography #2

### ISSUE THREAD

**Issue by tommyalatalo** [void-linux/void-packages#51438]
### Is this a new report?

Yes

### System Info

Void 6.8.12_2 x86_64 AuthenticAMD uptodate rrrmFFFFFFF

### Package(s) Affected

deluge-gtk

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No

### Expected behaviour

The package should install and run properly

### Actual behaviour

The package crashes on launch

### Steps to reproduce

Install `deluge-gtk` and try to run it.

(this issue is a new instance of https://github.com/void-linux/void-packages/issues/48600)

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/7da93c4af4a7c7405e92935e916b46de891ad544
