### ISSUE TITLE
PHP and Composer: Class 'Phar' not found (stale php.ini)

### ISSUE THREAD

**Issue by amalcolm-wikia** [void-linux/void-packages#5145]
### System

* xuname:  
  `xuname: command not found`

* uname -a
  `Linux Nabu 4.19.4_1 #1 SMP PREEMPT Sun Nov 25 06:26:34 UTC 2018 x86_64 GNU/Linux`

* package(s):  
 php 7.2.12_1
 composer 1.7.3_1

### Expected behavior
Composer should work (should install project dependencies).

### Actual behavior
Composer doesn't work, because phar cannot be found:
```
PHP Fatal error:  Uncaught Error: Class 'Phar' not found in /usr/bin/composer:23
Stack trace:
#0 {main}
  thrown in /usr/bin/composer on line 23
```

### Steps to reproduce the behavior
Attempt to install PHP dependencies with composer

**Comment by amalcolm-wikia** [comment]
OK, so, it appears the following needs to be added to `/etc/php/php.ini`:
`extension=phar`

And, the `open_basedir` line needs to be edited or replaced:
```
;open_basedir = /srv/www/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/
open_basedir = /srv/www/:/home/:/tmp/:/usr/share/pear/:/usr/bin/composer:/usr/share/webapps/
```

Not sure how this should be handled, really.
If phar is enabled, via `srcpkgs/php/template`, it probably makes sense to add it to `/etc/php/php.ini`, or at least check for it, when installing composer, as well as the `open_basedir` line. We can probably use `sed`, to do so. It appears we are simply copying a default `php.ini` on package install, rather than adjusting it to meet compile time args (i.e., also noticing openssl isn't enabled, in `php.ini`, and there is no /srv directory, after installing Void (though, this can be added, and I do so, myself)).

**Comment by Cogitri** [comment]
IMHO we shouldn't add all of those modules to php.ini, adding them means that they will be loaded when php is started, which is unnecessary when one doesn't need those extensions (and can lead to quite some memory wasted if one runs multiple php instances (e.g. via php-fpm) and loads more code which can potentially contain vulnerabilities). We do have to add them to the template so that the user _can_ enable them during run time though.

**Comment by amalcolm-wikia** [comment]
Except that, in the case of composer and phar, the user is _installing compose, which does not work without phar_.
Else, what would be the point of installation?
No, we probably shouldn't add _all_ of the modules, but a few are a bit of common sense, I think.

**Comment by amalcolm-wikia** [comment]
Sooo, any word on this?

**Comment by vitorhugomattos** [comment]
PHP Phar is enabled by default since PHP 5.3.0. Idk why it is disabled in the Void package, don't make sense to me.

**Comment by maxice8** [comment]
> Not sure how this should be handled, really.

By your local system administrator

automagically modifying files listed in conf_files is a huge no-no

**Comment by amalcolm-wikia** [comment]
> > Not sure how this should be handled, really.
> 
> By your local system administrator
> 
> automagically modifying files listed in conf_files is a huge no-no

Is simple dogma, i.e., _not a sound technical reason_ (and _completely evades_ stating one).
There are plenty of examples of XBPS installing packages which modify config files.
There's nothing "automagic" about it.

**Comment by maxice8** [comment]
fixed, feel free to open PR if it wasn't solved properly.
