### ISSUE TITLE
Handbrake issue. Incompatable Libraries?

### ISSUE THREAD

**Issue by ACR-Jeff** [void-linux/void-packages#51478]
### Is this a new report?

Yes

### System Info

handbrake 1.6.1_1

### Package(s) Affected

handbrake-1.6.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/HandBrake/HandBrake/issues/6178

### Expected behaviour

Previewing a video plays the video with audio using the chosen preset to have an idea of the quality, Etc

### Actual behaviour

The preview is showing 4 images side by side without preview working at all, The 4 images side by side are shown like a still image without playing the video, Audio is the only thing that plays in the background with a delay.

### Steps to reproduce

Open source (Video)
Choose a preset
You can instantly see the 4 images side by side in the Summary
Click `Preview` in the top right
Play the Preview
The Preview doesn't play, Only audio plays in the background with a delay.
Followed with a popup error message: 
![Handbrake-Issue](https://github.com/user-attachments/assets/6ef93df6-d10a-47b9-9fc0-05e5b5831b77)

**Comment by classabbyamp** [comment]
can you run it in a terminal to get a log?

**Comment by ACR-Jeff** [comment]
Terminal output showing
`libdvdread: Can't open file VIDEO_TS.IFO.`

Handbrake logs from config directory
[Activity.log](https://github.com/user-attachments/files/16397076/Activity.log)

**Comment by zlice** [comment]
@classabbyamp good to close
