### ISSUE TITLE
Missing module/shared-object in latest libvirt update

### ISSUE THREAD

**Issue by TeusLollo** [void-linux/void-packages#51481]
### Is this a new report?

Yes

### System Info

Void 6.6.41_1 x86_64 GenuineIntel notuptodate rFFFF

### Package(s) Affected

`libvirt-10.5.0_1` `libvirt-python3-10.5.0_1`

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

None known.

### Expected behaviour

`libvirt-10.5.0_1` & `libvirt-python3-10.5.0_1` are minor version bumps which would not be expected to produce major incompatibilities with pre-existing KVM/QEMU setups, but here we are. 

### Actual behaviour

After updating `libvirt-10.3.0_1` & `libvirt-python3-10.3.0_1` to `libvirt-10.5.0_1` https://github.com/void-linux/void-packages/pull/51316/commits/d442991b988553ec1d02e29da26274b464bba404 & `libvirt-python3-10.5.0_1` https://github.com/void-linux/void-packages/pull/51316/commits/119097b9809f471a19f660a43ed2680876c1c769 respectively, one of my boxes running a KVM/QEMU setup begun throwing the following error while failing to launch virtual machines that were previously working: 

```
Error starting domain: internal error: Failed to load module '/usr/lib64/libvirt/storage-file/libvirt_storage_file_fs.so': /usr/lib/libvirt.so.0: version `LIBVIRT_PRIVATE_10.5.0' not found (required by /usr/lib64/libvirt/storage-file/libvirt_storage_file_fs.so)

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
    self._backend.create()
  File "/usr/lib/python3.12/site-packages/libvirt.py", line 1379, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: Failed to load module '/usr/lib64/libvirt/storage-file/libvirt_storage_file_fs.so': /usr/lib/libvirt.so.0: version `LIBVIRT_PRIVATE_10.5.0' not found (required by /usr/lib64/libvirt/storage-file/libvirt_storage_file_fs.so)
`
```

Such an error could be reversed by using the following commands:
```
xbps-rindex -a /var/cache/xbps/libvirt-10.3.0_1.x86_64.xbps
xbps-install -R /var/cache/xbps/ -f libvirt-10.3.0_1
xbps-rindex -a /var/cache/xbps/libvirt-python3-10.3.0_1.x86_64.xbps
xbps-install -R /var/cache/xbps/ -f libvirt-python3-10.3.0_1
```
After reboot, the KVM/QEMU setup was back in working shape. 

Given error output, I would have to guess something got lost either at compile time or at packaging time, unless some major feature was somehow dropped during a minor version bump. Given output, this error may only happen if virtual machines under a KVM/QEMU setup also have storage files attached. 

### Steps to reproduce

1. You may need a pre-existing KVM/QEMU setup that was previously reported working, possibly with attached storage files, although creating one ex-novo may also bring up that error, possibly. 

2. After updating `libvirt-10.3.0_1` & `libvirt-python3-10.3.0_1` to `libvirt-10.5.0_1` & `libvirt-python3-10.5.0_1` respectively, you may experience the aforementioned failure.

**Comment by classabbyamp** [comment]
I can't reproduce this with
```
[*] libvirt-10.5.0_1         Virtualization API for controlling virtualization engines
[*] libvirt-devel-10.5.0_1   Virtualization API for controlling virtualization engines - development files
[*] libvirt-glib-5.0.0_1     Glib integration with libvirt
[*] libvirt-python3-10.5.0_1 Libvirt virtualization API Python3 binding
```

**Comment by classabbyamp** [comment]
it probably requires a service restart, you can use `xcheckrestart` from xtools to find programs/services that need to be restarted
