### ISSUE TITLE
rpi5-kernel-6.6.42_1 seems to believe it is actually 6.1.77_1

### ISSUE THREAD

**Issue by hhvn-uk** [void-linux/void-packages#51565]
### Is this a new report?

Yes

### System Info

Void 6.1.77_1 aarch64 Unknown uptodate rF

### Package(s) Affected

rpi5-kernel-6.6.42_1 (and some before it)

### Expected behaviour

I am not exactly sure when this started happening, but I know it started about a month ago, and I thought I'd wait a bit and see if a new kernel version would fix it.

I would expect that `uname -a` would give the installed kernel version, and the modules for the current kernel version would be loaded.

I would also expect wireguard to work.

### Actual behaviour

I updated all packages and then restarted the system.

```
$ uname -a
Linux hhvn.uk 6.1.77_1 #1 SMP PREEMPT Thu Mar  7 16:31:46 UTC 2024 aarch64 GNU/Linux
```

I used xbps-query -f on rpi5-kernel and it seems that the kernel is stored at /boot/kernel8.img.

```
$ stat /boot/kernel8.img
  File: /boot/kernel8.img
  Size: 10587261        Blocks: 20680      IO Block: 2048   regular file
Device: 8,17    Inode: 1211        Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-07-31 01:00:00.000000000 +0100
Modify: 2024-07-27 04:30:00.000000000 +0100
Change: 2024-07-27 04:30:00.000000000 +0100
 Birth: 2024-07-31 10:25:19.240000000 +0100
```

Weirdly the modification date is shown as being in the past, however I also tried moving the file, and using xbps-install -f to replace it. After another reboot, the system *still* thinks it is running 6.1.77_1.

This means that modprobe is unable to load any modules during bootup:
```
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/6.1.77_1
```

dmesg also reports the kernel being 6.1.77_1
```
$ doas cat /var/log/dmesg.log | grep 'Linux'
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x414fd0b1]
[    0.000000] Linux version 6.1.77_1 (void-buildslave@void) (aarch64-linux-gnu-gcc (GCC) 13.2.0, GNU ld (GNU Binutils) 2.41) #1 SMP PREEMPT Thu Mar  7 16:31:46 UTC 2024
[    0.645518] pps_core: LinuxPPS API ver. 1 registered
[    0.882320] usb usb1: Manufacturer: Linux 6.1.77_1 xhci-hcd
[    0.882594] usb usb2: Manufacturer: Linux 6.1.77_1 xhci-hcd
[    0.883564] usb usb3: Manufacturer: Linux 6.1.77_1 xhci-hcd
[    0.883788] usb usb4: Manufacturer: Linux 6.1.77_1 xhci-hcd
```

Whenever I attempt to bring up a wireguard interface, this happens:
```
$ doas wg-quick up hhvn
[#] ip link add hhvn type wireguard
Error: Unknown device type.
Unable to access interface: Protocol not supported
[#] ip link delete dev hhvn
Cannot find device "hhvn"
```

I would expect that even if the kernel *was* 6.1.77_1 it would still support wireguard? This whole situation is very strange to me.

I at one point attempted to use rpi-kernel instead, and ran into the same situation.

### Steps to reproduce

I don't have a spare rpi to test this out on.

I installed it via one of @classabbyamp's images.

I suppose install rpi5-kernel on an rpi5 and then check what uname outputs?

Happy to give any more info that may be relevant if this proves hard to reproduce.

**Comment by Duncaen** [comment]
Are you sure you mounted the boot partition?

**Comment by hhvn-uk** [comment]
Good pointer. /boot in fstab wasn't what was being used.
