### ISSUE TITLE
Package request: systemd-boot

### ISSUE THREAD

**Issue by Calandracas606** [void-linux/void-packages#51578]
### Package name

systemd-boot

### Package homepage

https://www.freedesktop.org/wiki/Software/systemd/systemd-boot/

### Description

systemd-boot is a UEFI boot manager which executes configured EFI images.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
if you want to adapt the systemd-boot-efistub package and take it over, fine by me. I only needed the efistub so i only packaged that and ukify
