### ISSUE TITLE
Package request: ueberzug

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#51573]
### Package name

ueberzug

### Package homepage

https://github.com/ueber-devel/ueberzug

### Description

Überzug is a CLI program which draws images on terminals. This is a replacement of the abandoned project with the same name.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by icp1994** [comment]
Also https://github.com/void-linux/void-packages/issues/45368
