### ISSUE TITLE
libcaca compiled with no imlib2 support?

### ISSUE THREAD

**Issue by Vintodrimmer** [void-linux/void-packages#5159]
### System

* xuname:  
  *Void 4.19.4-chrysalis x86_64 GenuineIntel uptodate rFFFFFFF*
* package:  
  *libcaca-0.99.beta19_8*

### Expected behavior
Being able to view almost any image in the ASCII format.

### Actual behavior
Errors that img2txt is unable to open files and messages that only BMP format is supported.

### Steps to reproduce the behavior
1. Install libcaca
2. run `img2txt` on any image

If I'm not mistaken, `libcaca` should be compiled with `--with-imlib2` flag to support all the other formats.
I see it in `makehostdepends` but not sure it works without explicit definition.

Or is there some error on my end?

**Comment by newbluemoon** [comment]
It’s optional so that all the X11 stuff isn’t pulled in automatically. You have to build it with xbps-src yourself, like

    ./xbps-src -o x11 pkg libcaca

**Comment by frstrikerman** [comment]
I'm sorry to necrobump this issue but you can build libcaca without x11 support and with imlib2

**Comment by LinArcX** [comment]
I have the same issue. Is it normal behavior?
