### ISSUE TITLE
`ranger` requires `tmux` to be installed

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#516]
### System

* xuname:  
`Void 4.16.14_1 x86_64 GenuineIntel uptodate rF`
* package:  
`ranger-1.9.1_1`

### Expected behavior
`ranger` starts correctly.

### Actual behavior
`ranger` fails to start, the terminal is messed up, because the `tmux` binary is not found.

### Steps to reproduce the behavior
Install `ranger` on a system that don't have `tmux` installed.

**Comment by Duncaen** [comment]
Thats not correct https://github.com/ranger/ranger/issues/1042.

**Comment by notramo** [comment]
It has been fixed in upstream. Until the next release, a workaround is setting the `update_tmux_title` config option to `false` if `tmux` is not installed, so I will close the issue.
@Duncaen thanks for referencing the upstream issue.
