### ISSUE TITLE
Package request: scenefx

### ISSUE THREAD

**Issue by shmishtopher** [void-linux/void-packages#51600]
### Package name

scenefx

### Package homepage

https://github.com/wlrfx/scenefx

### Description

A drop-in replacement for the wlroots scene API that allows wayland compositors to render surfaces with eye-candy effects.  `scenefx` is used in the latest (`0.4`) release of swayFX, which is currently packaged by void.  `scenefx` provides the following warning:

> while SceneFX is in use by SwayFX version 0.4, it is not yet ready for usage by other compositors. Please refer to the [1.0 milestone](https://github.com/wlrfx/scenefx/milestone/2) to track the remaining tasks for our stable 1.0 release

This may be an issue for packaging into void, but will also be a blocker for updating swayFX (`0.3.2 -> 0.4`).

Pinging @sgn, @rehanzo 

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
#51020

**Comment by classabbyamp** [comment]
if a package is a new dependency for an existing package, just add it to the PR with the update
