### ISSUE TITLE
initramfs hook is not run by xbps [linux 6.10.3 update]

### ISSUE THREAD

**Issue by dkwo** [void-linux/void-packages#51627]
### Is this a new report?

Yes

### System Info

Void 6.10.2_1 x86_64 GenuineIntel uptodate rFFFFFFFFFFFF

### Package(s) Affected

linux 6.10, xbps

### Expected behaviour

the hook is run

### Actual behaviour

```
$ pacc 
[*] Updating repository `https://repo-fastly.voidlinux.org/current/x86_64-repodata' ...
x86_64-repodata: 1892KB [avg rate: 8033MB/s]
[*] Updating repository `https://repo-de.voidlinux.org/current/nonfree/x86_64-repodata' ...

Name      Action    Version           New version            Download size
linux6.10 update    6.10.2_1          6.10.3_1               152MB 

Size to download:              152MB
Size required on disk:         157MB
Space available on disk:      4946MB

Do you want to continue? [Y/n] 

[*] Downloading packages
linux6.10-6.10.3_1.x86_64.xbps.sig2: 512B [avg rate: 2890KB/s]
linux6.10-6.10.3_1.x86_64.xbps: 152MB [avg rate: 4651KB/s]
linux6.10-6.10.3_1: verifying RSA signature...

[*] Collecting package files
linux6.10-6.10.3_1: collecting files...
linux6.10-6.10.2_1: collecting files...

[*] Unpacking packages
linux6.10-6.10.2_1: updating to 6.10.3_1 ...
linux6.10-6.10.3_1: unpacking ...

[*] Configuring unpacked packages
linux6.10-6.10.3_1: configuring ...
linux6.10-6.10.3_1: updated successfully.

1 downloaded, 0 installed, 1 updated, 1 configured, 0 removed.
```
but no initram or uki present:
```
$ ls /boot 
config-6.10.2_1  config-6.10.3_1  config-6.6.43_1  linux-6.10.2_1.efi  linux-6.6.43_1.efi  vmlinuz-6.10.2_1  vmlinuz-6.10.3_1  vmlinuz-6.6.43_1
$ ls -la /etc/kernel.d/post-install/10-uki
-rwxr-xr-x 1 root root 1363 Jul 31 09:02 /etc/kernel.d/post-install/10-uki
```

### Steps to reproduce

`xbps-install -S linux6.10`

**Comment by dkwo** [comment]
@classabbyamp The recent update https://github.com/void-linux/void-packages/commit/9ab1405894fd5310a940382b80c178ea299f4a81 made a bunch of things not executable, among which stuff in
`srcpkgs/xbps-triggers/`. Do you think this could be related?

**Comment by manfred3000** [comment]
Same here using `mkinitcpio`...

**Comment by classabbyamp** [comment]
1. xbps triggers are made executable in the template: https://github.com/void-linux/void-packages/blob/master/srcpkgs/xbps-triggers/template#L16
2. xbps-triggers hasn't even been rebuilt since then

I made sure everything gets the necessary execute bit in the template when making that commit

**Comment by dkwo** [comment]
I see. Then this might be specific to linux6.10.
With `doas xbps-reconfigure -f linux6.6` the hook gets executed correctly.
