### ISSUE TITLE
Package request: mbed-tls

### ISSUE THREAD

**Issue by OHNONOTAMOTH** [void-linux/void-packages#51641]
### Package name

mbed-tls

### Package homepage

https://www.trustedfirmware.org/projects/mbed-tls/

### Description

A portable TLS library.  It is required for Neko, which is required for Haxe which I am trying to create a package for.  My attempt to make a package for it and I have no idea why.  Someone more experienced might have more success or be able to help.

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/blob/master/srcpkgs/mbedtls/template

**Comment by OHNONOTAMOTH** [comment]
god, why didn't i see that.  that's embarrassing
