### ISSUE TITLE
NVIDIA driver symlink not updated.

### ISSUE THREAD

**Issue by atisharma** [void-linux/void-packages#51704]
### Is this a new report?

Yes

### System Info

Void 6.6.43_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFF

### Package(s) Affected

nvidia-libs-550.107.02_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No.

### Expected behaviour

This symlink should be made to the new library file:

```
/usr/lib/libnvidia-nvvm.so.4 -> /usr/lib/libnvidia-nvvm.so.550.107.02
```

### Actual behaviour

The symlink is not made, leaving the old version behind pointing to a previous driver library:

```
/usr/lib/libnvidia-nvvm.so.4` -> libnvidia-nvvm.so.525.105.17
```

The broken symlink breaks software looking for the library, including `nvidia-container-toolkit`.

### Steps to reproduce

1. update drivers to 550
2. try to launch a docker container using gpus via nvidia-container-toolkit
3. it crashes as follows:

```
/home/ati # docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: detection error: open failed: /usr/lib/libnvidia-nvvm.so.525.105.17: no such file or directory: unknown.
```

Manually updating the symlink to the new library file fixes the issue.

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/pull/51688
