### ISSUE TITLE
Package Request: Cockpit

### ISSUE THREAD

**Issue by husho** [void-linux/void-packages#5174]
> The easy-to-use, integrated, glanceable, and open web-based interface for your servers

[https://cockpit-project.org/](https://cockpit-project.org/)

**Comment by CameronNemo** [comment]
Much of this is basically a wrapper around systemd. Not sure how useful it would be on void, unless you can connect to a remote system or a VM?

**Comment by Anachron** [comment]
I‘d rather use something like netdata.

**Comment by CameronNemo** [comment]
Does netdata do admin.? Not that I want a gui for admin, but that seems like the main sell of cockpit.

**Comment by maxice8** [comment]
Closing as we can't provide this package, reasons described above.
