### ISSUE TITLE
Sway: add dmenu as optional dependency

### ISSUE THREAD

**Issue by o-alquimista** [void-linux/void-packages#51779]
### Is this a new report?

Yes

### System Info

Void 6.6.44_1 x86_64 GenuineIntel notuptodate rrrrmdFFFFFFF

### Package(s) Affected

sway-1.9_1

### Expected behaviour

The default Sway configuration relies on the package `dmenu` being installed in order to provide a fully functional `wmenu` program.

[Arch Linux made the change](https://gitlab.archlinux.org/archlinux/packaging/packages/sway/-/issues/3). You can see it listed in the [package](https://archlinux.org/packages/extra/x86_64/sway/) dependency list.
> **dmenu** (optional) - dmenu_path support (used alongside wmenu in default $menu)

### Actual behaviour

For more context, see this bug report upstream: https://github.com/swaywm/sway/issues/8286

### Steps to reproduce

1. Install Sway and its default menu `wmenu`, then start a session. Keep default config file.
2. Use the keybinding to open the menu (`$mod+d`). You should be able to see that suggestions don't show up as you type — the top bar is mostly empty.
3. Install `dmenu`, reload Sway config, and the menu should now work as expected.

**Comment by Luciogi** [comment]
xbps does not support optional dependency management at the time

**Comment by o-alquimista** [comment]
Would it be possible to add it as a "normal" dependency for now?

It's not a critical thing, but it can be a source of confusion (took me a while to find out).

**Comment by manfred3000** [comment]
> It's not a critical thing, but it can be a source of confusion (took me a while to find out).
So you found a solution to a minor problem. This is kind of expected running Void, imho.

It's unlikely that package templates will be inflated unnecessarily as long as the core dependencies are met - everything beyond that is part of your own choice/liking/responsibility and the "defaults" proposed by a given WM are just that - you could pick any of the many alternatives provided by Void...
