### ISSUE TITLE
Request: Split qemu-system-* packages

### ISSUE THREAD

**Issue by voidbert** [void-linux/void-packages#51804]
### Current situation

QEMU system and user emulators are currently packaged into a single monopackage, [`qemu`](https://github.com/void-linux/void-packages/tree/master/srcpkgs/qemu).

### The problem

It's hard for me to believe most people who download this package use most of the provided emulators. For example, I mostly use `qemu-system-x86_64`, and `qemu-system-arm` only occasionally. Thus, I am wasting storage space on programs I'll never use. I see this being particularly problematic in the following cases:

 - Environments with limited storage space (such as a RPi with an SD card);
 - Void Linux container images, that become large if QEMU needs to be installed.

### Proposed solution

I would like to suggest that the `qemu` package be split into many packages, one for each emulator architecture (`qemu-x86_64`, `qemu-arm`, `qemu-mips`, ...). This has already been done, as other distros have adopted similar packaging schemes:
 - [Alpine](https://pkgs.alpinelinux.org/packages?name=qemu-system-*&branch=edge&arch=x86_64);
 - [Arch Linux](https://archlinux.org/packages/?q=qemu-system);
 - [Debian](https://packages.debian.org/search?keywords=qemu-system-&searchon=names&suite=stable).

**Comment by classabbyamp** [comment]
you can use a [noextract rule](https://man.voidlinux.org/xbps.d#noextract=pattern) like:
```
noextract=/usr/bin/qemu-system-*
noextract=!/usr/bin/qemu-system-x86_64
noextract=!/usr/bin/qemu-system-arm
```

**Comment by voidbert** [comment]
> you can use a [noextract rule](https://man.voidlinux.org/xbps.d#noextract=pattern) like:
> 
> ```
> noextract=/usr/bin/qemu-system-*
> noextract=!/usr/bin/qemu-system-x86_64
> noextract=!/usr/bin/qemu-system-arm
> ```

Thank you for the tip! I'll start using it! Still, I believe that, for most users, having separate packages would be great. Another option would be to add this to Void's libvirt documentation (not just xbps').
