### ISSUE TITLE
ffmpeg-devel-32bit incorrectly has 64-bit dependencies

### ISSUE THREAD

**Issue by Headwind81** [void-linux/void-packages#5194]
### System

* xuname:  
  bash: xuname: command not found
* package:  
  ffmpeg-devel-32bit-4.1_1

### Expected behavior
'xbps-install ffmpeg-devel-32bit' should install 32-bit dependencies.

### Actual behavior
It instead incorrectly installs 64-bit dependencies.

### Steps to reproduce the behavior
Running 'xbps-query -Rx ffmpeg-devel', then 'xbps-query -Rx ffmpeg-devel-32bit', shows the same outputs (they each depend on the same 64-bit packages). Presumably the 32-bit version should have 32-bit dependencies. It's my understanding that the -32bit packages are generated automatically, and therefore that automation must have failed in this case.

**Comment by Headwind81** [comment]
[ian@ianhost mtgadir]$ sudo xuname
Void 4.19.4 x86_64 GenuineIntel notuptodate FFF

**Comment by Headwind81** [comment]
Apparently my binutils was out of date when I ran that, was 2.31.1_1 and not 2.31.1_2.

**Comment by ericonr** [comment]
This bug still exists.
