### ISSUE TITLE
`dzen2` fails to run

### ISSUE THREAD

**Issue by zenny** [void-linux/void-packages#51943]
### Is this a new report?

Yes

### System Info

Void 6.1.104_1 x86_64 GenuineIntel notuptodate rrrrmmnFFFFFFFFF

### Package(s) Affected

dzen2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/herbstluftwm/herbstluftwm/issues/1595

### Expected behaviour

`dzen2` xbps package should run as it should which was the case in the past except crashes without any debugging reasons. But it worked when compiled from the same upstream source of the xbps package manaully.

### Actual behaviour

The `dzen2` stopped working to launch the herbstluftwm's `panel.sh`. Details are reported in https://github.com/herbstluftwm/herbstluftwm/issues/1595

However , when I pulled the repo from https://github.com/robm/dzen and compiled manually, it works as it should. So it seems like the xbps packaging issue or some breaking changes that make the packages behave very odd (another is emacs package as reported in https://github.com/void-linux/void-packages/issues/51727), imho.

### Steps to reproduce

1. `dzen2 --help`
2. Error: `zsh: command not found: dzen2`
3. `panel.sh` cannot be loaded which depends on `dzen2`

Caveats:

1. dzen2 binary exists:
```
$ which dzen2
/usr/bin/dzen2
```

2. Voidlinux-specific query shows it exists:
```
$ xbps-query -v -Rs dzen2
[*] dzen2-20130923_2 X notification utility
```
3. Force installation does not work, too:

```
# xbps-install -Sf dzen2
[*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/nonfree/x86_64-repodata' ...

Name  Action    Version           New version            Download size
dzen2 reinstall 20130923_2        20130923_2             -

Size required on disk:         120KB
Space available on disk:        11GB

Do you want to continue? [Y/n] y

[*] Downloading packages
dzen2-20130923_2.x86_64.xbps.sig2: 512B [avg rate: 20MB/s]
dzen2-20130923_2.x86_64.xbps: 29KB [avg rate: 465MB/s]
dzen2-20130923_2: verifying RSA signature...

[*] Collecting package files
dzen2-20130923_2: collecting files...

[*] Unpacking packages
dzen2-20130923_2: unpacking ...

[*] Configuring unpacked packages
dzen2-20130923_2: configuring ...
dzen2-20130923_2: installed successfully.

0 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.
```

4. Despite force reinstallation, the panel.sh (https://github.com/herbstluftwm/herbstluftwm/blob/master/share/panel.sh):
```
$ ~/.config/herbstluftwm/panel.sh
/home/zenny/.config/herbstluftwm/panel.sh: line 194: /usr/bin/dzen2: cannot execute: required file not found
```

5. Despite having the following intact:

```
$ /bin/ls -alt `which dzen2`
-rwxr-xr-x 1 root root 56320 Nov 25  2018 /usr/bin/dzen2

$ ldd /usr/bin/dzen2
        linux-vdso.so.1 (0x00007ffd849fe000)
        libXpm.so.4 => /usr/lib/libXpm.so.4 (0x00007fefb2c8e000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x00007fefb2b49000)
        libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x00007fefb2b44000)
        libXft.so.2 => /usr/lib/libXft.so.2 (0x00007fefb2b2a000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fefb2940000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007fefb2916000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x00007fefb28ff000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007fefb28b4000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007fefb27f9000)
        libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007fefb27ec000)
        /lib/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fefb2d6a000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x00007fefb27e7000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007fefb27df000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007fefb27b2000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007fefb2798000)
        libbz2.so.1 => /usr/lib/libbz2.so.1 (0x00007fefb2785000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007fefb274f000)
        libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x00007fefb2741000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fefb265d000)
        libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x00007fefb263a000)
```

**Comment by tranzystorekk** [comment]
Could not reproduce, installing dzen2 correctly provided the binary on my side, are you sure it's not a problem somewhere in your `panel.sh` script?

**Comment by zenny** [comment]
> Could not reproduce, installing dzen2 correctly provided the (working) binary on my side, are you sure it's not a problem somewhere in your `panel.sh` script?

Nope. As I already stated in OT, it worked flawlessly with the manually compiled dzen2 with the same panel.sh script, fyi.

**Comment by zenny** [comment]
A recent upgrade of voidlinux caused a garbled linking including with the /lib --> /usr/lib and wrong hashes that caused problems as above with many applications. Thanks to #voidlinux IRC that the problem was solved by running the following:

```
xbps-reconfigure -a
xbps-pkgdb -a
xbps-install -f base-files
```
Thus, it seems like something to do with xbps-upstream.
