### ISSUE TITLE
Oilshell renamed `oil` as `ysh`, but package still uses old name

### ISSUE THREAD

**Issue by sogaiu** [void-linux/void-packages#51951]
### Is this a new report?

Yes

### System Info

Void 6.6.47_1 x86_64 GenuineIntel uptodate FFFF

### Package(s) Affected

oil-0.22.0_1

### Expected behaviour

Being able to invoke `ysh` successfully.

### Actual behaviour

Attempting to invoke `ysh` leads to a message that ends `ysh: command not found`.

### Steps to reproduce

0. `sudo xbps-install -Su`
1. `sudo xbps-install -S oil` # ...and answer appropriately until installation is complete
2. `ysh`

Regarding the renaming, please see [this](https://www.oilshell.org/blog/2023/03/rename.html#what-are-the-new-names).

**Comment by classabbyamp** [comment]
@bugcrazy

**Comment by tranzystorekk** [comment]
According to https://github.com/oils-for-unix/oils/wiki/Oils-Packaging-Guidelines we can migrate the package to the `oils-for-linux` version

**Comment by bugcrazy** [comment]
I created this PR that renames the old names, ysh command, it had the old name oil, I also renamed the package name to oils, making things easier: https://github.com/void-linux/void-packages/pull/51964

**Comment by bugcrazy** [comment]
> According to https://github.com/oils-for-unix/oils/wiki/Oils-Packaging-Guidelines we can migrate the package to the `oils-for-unix` version

"The oils-for-unix tarball is the fast shell in C++, completed in 2024. The distro package should be called oils-for-unix."

Package currently uses CPython version, I changed the package name to oils, to make it easier, although the author does not recommend it, the oils-for-unix version is faster, but has bugs than the CPython version, as it was only completed this year, the CPython version is more tested and old.

**Comment by sogaiu** [comment]
Hmm, I assumed that folks who are interested in using the oilshell-related stuff at this point are more inclined to using the more recent release.  At least that is the case for me -- the whole project is quite oriented toward testing and I think they'd appreciate getting feedback from users for their more recent efforts.

Just my two cents.

**Comment by icp1994** [comment]
I agree it makes more sense to build from the oils-for-unix-${version}.tar.gz - especially considering the instructions under 'Packaging' in https://www.oilshell.org/release/0.22.0

Also a new version was "tagged" yesterday [upstream](https://github.com/oils-for-unix/oils/commit/66a80ffc810084bbb2c2917228c4764305fd8786) so could also incorporate the changes in an update PR.

**Comment by bugcrazy** [comment]
Updated to version 0.23, waiting for merge!

**Comment by bugcrazy** [comment]
Update has been merged, I believe the ticket can be closed.

**Comment by sogaiu** [comment]
There is also now #52218 which is also referencing this issue.

Should I close anyway?

**Comment by bugcrazy** [comment]
> There is also now #52218 which is also referencing this issue.
> 
> Should I close anyway?

The question is a shell command, it was oil and went to ysh with an update to the default package in the repository, oils-for-unix is ​​a PR for a new package.

**Comment by sogaiu** [comment]
> oils-for-unix is ​​a PR for a new package.

Yes.

The opening text for that PR is:

> closes https://github.com/void-linux/void-packages/issues/51951

Perhaps that should be modified then?

In any case, I'm fine with closing this and will do so.
