### ISSUE TITLE
unresolvable shlib with RubyMine

### ISSUE THREAD

**Issue by xhyrom** [void-linux/void-packages#51971]
### Is this a new report?

Yes

### System Info

Void 6.6.47_1 x86_64 AuthenticAMD uptodate rrFFFFF

### Package(s) Affected

RubyMine

### Expected behaviour

The RubyMine package should install fine.

### Actual behaviour

When trying to install `RubyMine-2020.1.4_1` I get an error:
```
RubyMine-2020.1.4_1: broken, unresolvable shlib `ld-linux.so.2'
Transaction aborted due to unresolved shlibs.
```

after updating the template with new version `2024.2.0.1`, i'm getting:
```
RubyMine-2024.2.0.1_1: broken, unresolvable shlib `ld-linux-aarch64.so.1'
Transaction aborted due to unresolved shlibs.
```

I want to update the RubyMine package, however, it's not possible due to this error.

### Steps to reproduce

1. Build the `RubyMine` package
2. run `xi RubyMine`
3. unresolved shlibs

if you want to try it with latest RubyMine,
change the version to `2024.2.0.1` and checksum to `9e3ca43d2cd0c22b254033c9fea4c54707310a39a2b4b1ff270a480b53fd3518` (https://download.jetbrains.com/ruby/RubyMine-2024.2.0.1.tar.gz.sha256)

**Comment by pondichys** [comment]
Hello,
I just tested it on my build machine and it is installing correctly (log file in attachment if you want to have a look).
[20240825_test_install_RubyMine.log](https://github.com/user-attachments/files/16740144/20240825_test_install_RubyMine.log)

You can check SO name to package mapping by having a look at [common/shlibs](https://github.com/void-linux/void-packages/blob/master/common/shlibs) file in this repository.
A quick check shows that you should have **glibc-2.39_1** for this package to work. My question to you would be what version of Void are you running: **glibc** or **musl** ? If you're running **musl**, you won't be able to run this software like that. You could try the flatpak version but beware that it is not officially packaged by Jetbrains ...

I hope it helps.

**Comment by xhyrom** [comment]
Thanks for response! I'm running on glibc. Output of xbps-query:

```
02:52 ~ xbps-query -l | grep -i glibc
ii glibc-2.39_4                               GNU C library
ii glibc-devel-2.39_4                         GNU C library - development files
ii glibc-locales-2.39_4                       GNU C library - locale data files
```

**Comment by pondichys** [comment]
Revision 4 is ok (this is what I have installed on my system).

The error messages you report do mention `ld-linux.so.2` and `ld-linux-aarch64.so.1`. Looking at [shlibs](https://github.com/void-linux/void-packages/blob/master/common/shlibs) file those SO names refer to 2 different architectures (i686 and aarch64)

```
ld-linux-x86-64.so.2 glibc-2.39_1 x86_64
ld-linux.so.2 glibc-2.39_1 i686
ld-linux.so.3 glibc-2.39_1 armv5tel
ld-linux-aarch64.so.1 glibc-2.39_1 aarch64
```

It seems you run a x86_64 AMD cpu thus the install should look for `ld-linux-x86_64.so.2`. What is the binary bootstrap that you use to build the package ?

**Comment by xhyrom** [comment]
> Revision 4 is ok (this is what I have installed on my system).
> 
> The error messages you report do mention `ld-linux.so.2` and `ld-linux-aarch64.so.1`. Looking at [shlibs](https://github.com/void-linux/void-packages/blob/master/common/shlibs) file those SO names refer to 2 different architectures (i686 and aarch64)
> 
> ```
> ld-linux-x86-64.so.2 glibc-2.39_1 x86_64
> ld-linux.so.2 glibc-2.39_1 i686
> ld-linux.so.3 glibc-2.39_1 armv5tel
> ld-linux-aarch64.so.1 glibc-2.39_1 aarch64
> ```
> 
> It seems you run a x86_64 AMD cpu thus the install should look for `ld-linux-x86_64.so.2`. What is the binary bootstrap that you use to build the package ?

I just ran `./xbps-src binary-bootstrap`, what exactly do you mean?

**Comment by pondichys** [comment]
Go to your local clone of the void-package repository and check that you have a directory called masterdir-**x86_64**.
If yes then I have no more idea on what's going on. Would be nice to have a log of the commands you run from start to error. My curiosity is triggered on that one.

**Comment by Chocimier** [comment]
There are some precompiled binaries for various archs in updated upstream tarball, they need to be removed, see CLion template.

**Comment by xhyrom** [comment]
> Go to your local clone of the void-package repository and check that you have a directory called masterdir-**x86_64**. If yes then I have no more idea on what's going on. Would be nice to have a log of the commands you run from start to error. My curiosity is triggered on that one.

![image](https://github.com/user-attachments/assets/3e285876-bfd7-4fd7-a17b-735c49acd731)
yes i have :D

**Comment by xhyrom** [comment]
> There are some precompiled binaries for various archs in updated upstream tarball, they need to be removed, see CLion template.

Gonna try it.

**Comment by xhyrom** [comment]
it works, thanks guys!
