### ISSUE TITLE
Suggestion: Link against libcardiacarrest instead of libpulse

### ISSUE THREAD

**Issue by archfan** [void-linux/void-packages#5206]
"Many apps can be built with PulseAudio support, many people want that support, many other people (e.g. me) freak out at the single mention of linking against PulseAudio libraries (see below).

This project provides a way to produce software artifacts that work for both camps without building two different versions of everything."

See: https://github.com/oxij/libcardiacarrest

**Comment by Hoshpak** [comment]
I don't think that would be a good idea. Linking against a specific shared library doesn't hurt. I just takes a small amount of disk space and memory. There are many libraries linked whose functionality people might not need. If I look at my system, there are package linked against libelogind, pulseaudio and apparmor. I use neither of them however the mere existence of these libraries doesn't bother me at all. libpulse does a good job at gracefully failing so it doesn't get in my way.

If you prefer a specific way to build packages and want to avoid certain libraries, I suggest either recompiling the packages you use locally or look into Gentoo or funtoo. It should be relatively easy to get a system without any pulseaudio dependencies after setting the right USE flags.

**Comment by maxice8** [comment]
It "works" as much as you have to ask pulseaudio users to override LD_LIBRARY_PATH For stuff.

So no thanks, we are not going to break 100% of pulseaudio users because people don't like libpulse in their systems.
