### ISSUE TITLE
Chromium registers unrelated mime-types

### ISSUE THREAD

**Issue by return42** [void-linux/void-packages#52077]
When installing chromium, several unrelated mime-types are registered, e.g. `application/pdf` or `image/jpeg`,`image/png` and more.

A patch could be: `chrome/installer/linux/common/desktop.template` :

```diff
114c114
< MimeType=application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;
---
> MimeType=text/html;text/xml;application/xhtml+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
```
The patch above is based on the mime-types from the initial Chromium commit 44d9409 [srcpkgs/chromium/files/chromium.desktop: line 113](https://github.com/void-linux/void-packages/commit/44d9409d6b66d33b81343d4bd00b40cc18bc1faf#diff-dc24d4b01344deff228dad299c337b5179a2e8d58205111737eed0872b439b48R111-R113)

**Comment by classabbyamp** [comment]
but chromium can act as an image or pdf viewer?

**Comment by return42** [comment]
Yes, it can ... but without any user interaction Chromium is used as the “first” default image or PDF viewer / which IMO is not the best default option.  I noticed this after I installed Chromium and then the PDFs were displayed in Chrome instead of the PDF Viewer (same with images).

**Comment by ahesford** [comment]
We shouldn't be patching out upstream desktop specs. Convince the chromium team that they shouldn't be specifying these extra MIME types.

**Comment by classabbyamp** [comment]
you can use [`xdg-mime`](https://man.voidlinux.org/xdg-mime) to set the default application for each mime type
