### ISSUE TITLE
mime database broken after update, manual intervention required.  gtk2 apps broken

### ISSUE THREAD

**Issue by Veyrdite** [void-linux/void-packages#5209]
* xuname:  Void 4.18.18_1 x86_64 GenuineIntel uptodate rrrmmnFFFFFFFFFFF

Uncertain which package this should be tied to, I updated yesterday and only noticed the problem this morning.

## Symptoms

Various gtk applications (eg inkscape) refuse to start.  Others run but are missing most/all of their icons (eg lxappearance, thunderbird).

## Solution

As per  #5186 :  

```
update-mime-database /usr/share/mime
```

## Cause

There is a package somewhere that needs to run this command post install, but isn't doing so.  Uncertain which.  

EDIT: possible guesses based on what's new in my /var/cache/xbps/ folder:

* gtk2-engines-2.21.0_4.x86_64.xbps

**Comment by xtraeme** [comment]
unless you provide more details I declare this a non issue
