### ISSUE TITLE
gscan2pdf: Unable to locate Magick.pm 

### ISSUE THREAD

**Issue by nezos** [void-linux/void-packages#52096]
### Is this a new report?

Yes

### System Info

Void 6.10.7_1 x86_64 AuthenticAMD uptodate hold rrrrmdFFFFFFFFFF

### Package(s) Affected

gscan2pdf-2.13.4_1, libmagick-perl-7.1.1.36_1

### Expected behaviour

Run gscan2pdf

### Actual behaviour

$ gscan2pdf
```
Can't locate Image/Magick.pm in @INC (you may need to install the Image::Magick module) (@INC entries checked: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/share/perl5/vendor_perl/Gscan2pdf/Page.pm line 10.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/Gscan2pdf/Page.pm line 10.
Compilation failed in require at /usr/share/perl5/vendor_perl/Gscan2pdf/Document.pm line 11.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/Gscan2pdf/Document.pm line 11.
Compilation failed in require at /usr/share/perl5/vendor_perl/Gscan2pdf/Dialog/Renumber.pm line 7.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/Gscan2pdf/Dialog/Renumber.pm line 7.
Compilation failed in require at /bin/gscan2pdf line 59.
BEGIN failed--compilation aborted at /bin/gscan2pdf line 59.
```
Image/Magick.pm is provided by libmagick-perl but it is located at: /usr/lib/perl5/x86_64-linux/Image/Magick.pm

### Steps to reproduce

1. Run gscan2pdf
2. See error messages

**Comment by biopsin** [comment]
##### xlocate Magic.pm
gnupod-0.99.8_4             /usr/share/perl5/vendor_perl/GNUpod/FileMagic.pm
perl-File-MimeInfo-0.35_1   /usr/share/perl5/vendor_perl/File/MimeInfo/Magic.pm
perl-Variable-Magic-0.63_1  /usr/lib/perl5/vendor_perl/Variable/Magic.pm

**Comment by nezos** [comment]
None of these packages help to solve the issue (I tried installing them) as the location of Magic.pm is different then the one gscan2pdf searches (see error message):

/usr/lib/perl5/site_perl
/usr/share/perl5/site_perl
/usr/lib/perl5/vendor_perl
/usr/share/perl5/vendor_perl
/usr/lib/perl5/core_perl
/usr/share/perl5/core_perl
