### ISSUE TITLE
Snapper complains about unset locale on musl.

### ISSUE THREAD

**Issue by sww1235** [void-linux/void-packages#5212]
### System

* xuname:  
 xuname was taking forever to run and not outputting anything. x86_64 musl, kernel: 4.19.5_1
* package:  
  snapper-0.7.2.1

### Expected behavior

when running commands, for it to not give errors about the locale not being set

```
$ snapper list-configs
Config | Subvolume
-------+-----------
```
### Actual behavior

```
$ snapper list-configs
Failed to set locale. Fix your system.
Config | Subvolume
-------+-----------
```

### Steps to reproduce the behavior

install snapper from xbps
run snapper list-configs

### potential fix

manually setting `LC_ALL=C` fixed the issue. Not certain how this would actually be fixed by void since it would be shell specific.

**Comment by Mek101** [comment]
Up. The bug is still here

**Comment by ericonr** [comment]
Not really a bug we can fix simply. See https://www.openwall.com/lists/musl/2020/11/30/6 and the surrounding discussion.

**Comment by ericonr** [comment]
WONTFIX on our side, should be fixed by `libstdc++`.
