### ISSUE TITLE
GIMP is missing AVIF image support

### ISSUE THREAD

**Issue by o-alquimista** [void-linux/void-packages#52134]
### Is this a new report?

Yes

### System Info

Void 6.6.48_1 x86_64 GenuineIntel uptodate rrrmdFFFFFFF

### Package(s) Affected

gimp-2.10.38_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

A GIMP team member on _r/GIMP_ said I should report this here, as it seems to be a packaging issue.

https://www.reddit.com/r/GIMP/comments/17tgjfx/comment/llucazo/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

### Expected behaviour

Info extracted from the [reddit post](https://www.reddit.com/r/GIMP/comments/17tgjfx/comment/k8x1hk1/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button):

#### schumaml said:

[GIMP 2.10.22 added support for AVIF](https://www.gimp.org/news/2020/10/07/gimp-2-10-22-released/#heif-improved-heic-and-newly-added-avif-support), provided that you have a libheif with AVIF support (this is checked for in https://gitlab.gnome.org/GNOME/gimp/-/blob/gimp-2-10/configure.ac?ref_type=heads#L1841 ff.)

#### I replied:

I have GIMP 2.10.38 and still get "Unknown file type" when opening an `.avif` file.
```
$ pkg-config --variable=builtin_avif_decoder libheif; echo $?

0
$ pkg-config --variable=builtin_h265_decoder libheif; echo $?

0
```
I'm on Void Linux (amd64, glibc), and GIMP was installed with the XBPS package manager. I had to manually install `libheif-devel` to satisfy the `pkg-config` commands above (`libheif` was already installed).

The image is this: https://img.olympics.com/images/image/private//f_auto/primary/fdixrotyst8gdp85hmqq

I was able to open and convert the AVIF image into PNG using Inkscape.

### Steps to reproduce

1. Download the image from https://img.olympics.com/images/image/private//f_auto/primary/fdixrotyst8gdp85hmqq
2. Open it with GIMP (see error "Unknown file type").

**Comment by classabbyamp** [comment]
#52043
