### ISSUE TITLE
Package request: caff

### ISSUE THREAD

**Issue by leahneukirchen** [void-linux/void-packages#5216]
https://wiki.debian.org/caff

> caff is a synonym for "CA - fire and forget". It's a Perl script that helps you to automate the whole bunch of manual steps you have to do for every single key you want to sign after a key signing party.

**Comment by nocriw** [comment]
Should we build the whole signing-party package like debian does or only caff? 
https://salsa.debian.org/debian/signing-party/tree/debian/master

**Comment by leahneukirchen** [comment]
I guess one package with all the scripts is good.

**Comment by zen0bit** [comment]
Can be closed I think, already merged here?
https://github.com/void-linux/void-packages/pull/31552
