### ISSUE TITLE
Yazi: Missing the command-line interface tool

### ISSUE THREAD

**Issue by sxyazi** [void-linux/void-packages#52176]
### Is this a new report?

Yes

### System Info

N/A

### Package(s) Affected

yazi

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/sxyazi/yazi/issues/1634

### Expected behaviour

Includes the CLI tool, which is a necessary dependency introduced in Yazi 0.3, see https://github.com/sxyazi/yazi/issues/1046#issuecomment-2255993749

### Actual behaviour

Doesn't include it

### Steps to reproduce

Install Yazi via the system package manager

**Comment by tranzystorekk** [comment]
Ping @Bnyro
