### ISSUE TITLE
Package request: tinysparql

### ISSUE THREAD

**Issue by Jaymz665** [void-linux/void-packages#52233]
### Package name

tinysparql

### Package homepage

https://download.gnome.org/sources/tinysparql

### Description

Low-footprint RDF triple store library with SPARQL 1.1 interface
Required for future versions of packages:
brasero 
gnome-applets 
gnome-boxes 
gnome-games 
gnome-music 
gnome-notes 
gnome-usage 
grilo-plugins 
gtk3 
gtk4
localsearch
nautilus
polari 
rygel 
rygel
foliate 

### Does the requested package meet the package requirements?

Required

### Is the requested package released?

No

**Comment by chrysos349** [comment]
read [here](https://blogs.gnome.org/carlosg/2024/07/14/goodbye-tracker-hello-tinysparql-and-localsearch/)
```
– The Tracker SPARQL library will now be known as TinySPARQL
– The Tracker Miners indexer will now be known as LocalSearch, or GNOME LocalSearch if you prefer.
```

**Comment by Jaymz665** [comment]
@chrysos349  I built the entire gnome-core 47 locally (glibc x86_64 works fine), there is still a question with several packages like Nautilus.

It's not very successful so far, I'm still learning =)

**Comment by Jaymz665** [comment]
```
# Template file for 'tinysparql'
pkgname=tinysparql
version=3.8.0
revision=1
build_style=meson
#build_helper="gir qemu"
configure_args="-Dsystemd_user_services=false"
hostmakedepends="pkg-config cmake glib-devel bash-completion asciidoc"
makedepends="glib-devel gobject-introspection avahi-libs-devel icu-devel python3-devel vala-devel json-glib-devel libxml2-devel sqlite-devel libsoup3-devel avahi-glib-libs-devel python3-gobject-devel"
#checkdepends="dbus tar python3-gobject"
short_desc="Personal search tool and storage system"
maintainer="Orphaned <orphan@voidlinux.org>"
license="GPL-2.0-or-later, LGPL-2.1-or-later"
homepage="https://wiki.gnome.org/Projects/tinysparql"
changelog="https://gitlab.gnome.org/GNOME/tinysparql/-/raw/master/NEWS"
distfiles="${GNOME_SITE}/tinysparql/${version%.*}/tinysparql-${version}.tar.xz"
checksum=a86aa73a72f56d81f4b9f0eec6aefbc45ab35f9a8433c47722d8380b6637c475

tinysparql-devel_package() {
	short_desc+=" - shared libraries"
	pkg_install() {
		vmove "usr/lib/*.so.*"
		vmove usr/lib/girepository-1.0
	}
}
```

**Comment by chrysos349** [comment]
#52252

**Comment by nonchip** [comment]
yeah would be nice if libtracker wouldn't still try to provide those files tho, preventing any update.

**Comment by classabbyamp** [comment]
@oreo639

there just needs to be a transitional package for the multilib package(s)
