### ISSUE TITLE
[Dependency missing]: python3-ropgadget requires distutils to run

### ISSUE THREAD

**Issue by stdStudent** [void-linux/void-packages#52489]
### Is this a new report?

Yes

### System Info

Void 6.1.106 x86_64-glibc

### Package(s) Affected

python3-ropgadget-7.4_1

### Expected behaviour

Once [python3-ropgadget](https://github.com/void-linux/void-packages/tree/master/srcpkgs/python3-ropgadget) is installed, it should run successfully with `ROPGadget --help`.

### Actual behaviour

It says it's missing `distutils` module.

### Steps to reproduce

1. Clean Void Linux install (bare minimum).
2. Install package (`xi python3-ropgadget`).
3. Logout and login back.
4. Try to run `ROPGadget --help`.

It executed successfully after I installed [python3-distlib](https://github.com/void-linux/void-packages/tree/master/srcpkgs/python3-distlib) and [python3-distutils-extra](https://github.com/void-linux/void-packages/tree/master/srcpkgs/python3-distutils-extra).

**Comment by chrysos349** [comment]
what it actually requires is `python3-setuptools`
