### ISSUE TITLE
Package request: fyi

### ISSUE THREAD

**Issue by manfred3000** [void-linux/void-packages#52495]
### Package name

fyi

### Package homepage

https://codeberg.org/dnkl/fyi

### Description

FYI (for your information) is a command line utility to send desktop notifications to the user via a notification daemon implementing XDG desktop notifications.

It is almost a notify-send clone, with the following differences:

- notify-send does not implement --close.
- notify-send does not expose activation tokens (needed for window focus/activation) in any meaningful way. It prints it as a debug message when G_MESSAGES_DEBUG=all; fyi prints it when you use --print-token.
- fyi has consistent syntax in its --action and --hintoptions.
- fyi can print the reason a notification was closed, with --print-reason.
- fyi can query the notification daemon for its name and version information.
- fyi can query the notification daemon for its capabilities.
- fyi has shell completions (bash and [fish](https://fishshell.com/)).
- fyi has a single run-time dependency: [dbus](https://www.freedesktop.org/wiki/Software/dbus/) (the original D-Bus implementation).

NOTE: `fyi` exposes a bug in `fnott` (<=1.7.0), which has already been fixed [upstream](https://codeberg.org/dnkl/fnott/commit/6456f646a697963c08706c61d750b9e95a129586), so in case there's interest in adding `fyi` to the repo, maybe we should wait until the next version of `fnott` is released (@travankor).

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by Bnyro** [comment]
https://github.com/void-linux/void-packages/pull/51828
