### ISSUE TITLE
mate-panel clock applet: 12-hour time format broken on musl

### ISSUE THREAD

**Issue by alterae** [void-linux/void-packages#52494]
### Is this a new report?

Yes

### System Info

Void 6.6.52_1 x86_64-musl GenuineIntel uptodate rrnFFF

### Package(s) Affected

mate-panel-1.28.2_1 musl-1.1.24_21

### Expected behaviour

When the `12-hour` time format option is selected in the Clock applet, it should display the time in a 12-hour format with an am/pm marker.

### Actual behaviour

When the `12-hour` time format option is selected in the Clock applet, it should displays `???`.

This appears to be a result of discrepancies between glibc and musl libc `strftime` specifiers, possibly the `%P` specifier which is a [GNU extension](https://sourceware.org/glibc/manual/latest/html_mono/libc.html#Formatting-Calendar-Time-1) and is not present in musl's implementation.

### Steps to reproduce

1. Right click the Clock applet in the MATE panel.
2. Select "preferences".
3. Toggle the time formatting option from 24-hour to 12-hour time.

**Comment by MIvanchev** [comment]
@alterae Maybe you should report this to the mate-panel crew, this doesn't sound like a Void issue.

**Comment by sgn** [comment]
What is your display language? I see no `%P` in mate-panel source code!

**Comment by sgn** [comment]
It's `%l` not `%P`

**Comment by sgn** [comment]
Please test this https://github.com/void-linux/void-packages/pull/52506

**Comment by MIvanchev** [comment]
@sgn be advised there is a small semantic difference here. `%I` is defined in the C standard while `%l` is not but they are *not* the same representation. According to https://www.man7.org/linux/man-pages/man3/strftime.3.html, when `%l` is used  `single digits are preceded by a blank` so your patch likely needs to include additional processing.

**Comment by sgn** [comment]
I know

**Comment by sgn** [comment]
> @sgn be advised there is a small semantic difference here. `%I` is defined in the C standard while `%l` is not but they are *not* the same representation. According to https://www.man7.org/linux/man-pages/man3/strftime.3.html, when `%l` is used  `single digits are preceded by a blank` so your patch likely needs to include additional processing. 

I know and I dont care. It is still 12 hours format.

**Comment by sgn** [comment]
> @sgn be advised there is a small semantic difference here. `%I` is defined in the C standard while `%l` is not but they are *not* the same representation. According to https://www.man7.org/linux/man-pages/man3/strftime.3.html, when `%l` is used  `single digits are preceded by a blank` so your patch likely needs to include additional processing. 

And if you really read my patch, you will see that I documented the leading zero, which specifically meant I didn't care about the leading zero.

**Comment by alterae** [comment]
if desired i believe the leading zero can be trimmed using `%-I` instead of `%I`, and that does seem to work on musl

**Comment by MIvanchev** [comment]
I only took a quick glance yes and this wasn't intended as a negative personal remark, just wanted to point out that it introduces a change in behavior.

**Comment by sgn** [comment]
> I only took a quick glance yes and this wasn't intended as a negative personal remark, just wanted to point out that it introduces a change in behavior.

Which behaviour is changed? It is used to not work on musl, now it works?

**Comment by sgn** [comment]
> if desired i believe the leading zero can be trimmed using `%-I` instead of `%I`, and that does seem to work on musl

I reckon that would break some layout. Since `%l` is padding with space, `%I` is padding with zero, `%-I` doesn't pad with anything.

Please test and report.

**Comment by sgn** [comment]
`%_I` seems to be correct implementation

**Comment by MIvanchev** [comment]
It worked on musl with different visual result from `%l` but now we have identical behavior.
