### ISSUE TITLE
Wine 9.19 fails to build on buildbot for i686, but builds fine locally.

### ISSUE THREAD

**Issue by fvalasiad** [void-linux/void-packages#52547]
### Is this a new report?

Yes

### System Info

Void 6.6.52_1 i686 AuthenticAMD/VM notuptodate rFF

### Package(s) Affected

wine-9.19-1

### Expected behaviour

It should be building it without issues.

### Actual behaviour

https://build.voidlinux.org/?#/builders/9/builds/103

### Steps to reproduce

Build the package on buildbot

**Comment by fvalasiad** [comment]
I am able to build it locally, so I am thinking maybe it's an issue with the new buildbot.

**Comment by classabbyamp** [comment]
it's not failing on buildbot, i fixed it yesterday. inode numbers were > 2^32
