### ISSUE TITLE
ZFS module loading fails on newer kernels in BIOS mode

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#52618]
### Is this a new report?

Yes

### System Info

Void 6.1.106_1 x86_64-musl GenuineIntel uptodate rrnFF

### Package(s) Affected

linux

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

no

### Expected behaviour

System boots successfully on ZFS root with BIOS mode, and lockdown active. I don't know if BIOS is a cause, or it would fail also on UEFI.

### Actual behaviour

ZFS module loading fails because the DKMS-built module is not signed.

`linux-lts` works even with lockdown.

### Steps to reproduce

Install ZFS, and try to load it on newer-than-lts kernels.

**Comment by Duncaen** [comment]
Its not supposed to work with lockdown.

**Comment by notramo** [comment]
@Duncaen, Lockdown is a very useful tool, module signing enforcement is only a small part of it. I guess all DKMS modules are forbidden when it's enabled. Is there a way to work around only the signing, but keep all the lockdown features?

**Comment by Duncaen** [comment]
You might be able to disable just module signing with `module.sig_enforce=0` on the kernel cmdline, not sure about that though.
Otherwise maybe enrolling your keys and enable signing in dkms. https://wiki.debian.org/SecureBoot
