### ISSUE TITLE
Update streamlink to 6.11.0

### ISSUE THREAD

**Issue by bastimeyer** [void-linux/void-packages#52636]
### Package name

streamlink

### Package homepage

https://streamlink.github.io/

### Description

I'm the maintainer of Streamlink, so I regularly check its packaging status on various Linux distros.

Void Linux's `streamlink` package has been outdated for a while now, almost half a year.
https://github.com/void-linux/void-packages/tree/a8d1f7949eb3b4684c090033e193085d99c22164/srcpkgs/streamlink

Applications like Streamlink which rely on unstable 3rd party APIs/websites require constant updates. There have been 8 new releases since Void Linux stopped updating the package.
https://streamlink.github.io/changelog.html

So I'm asking maintainers of Void's `streamlink` package to have a look at packaging the most recent version, which currently is `6.11.0` (`7.0.0` coming up).

If the lack of package updates was caused by build issues of Streamlink's dependencies, then those should've been resolved ([`trio>=0.25`](https://github.com/python-trio/trio/releases/tag/v0.25.0) / [`trio-websocket`](https://github.com/python-trio/trio-websocket/commit/f5fd6d77db16a7b527d670c4045fa1d53e621c35)). I'll be glad to help if you run into any packaging issues.

I am not a user of Void, I'm just interested in having my application updated to the latest version.

Thanks.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by tranzystorekk** [comment]
As per our contributing guidelines, package bump requests are generally not useful, we have update scripts reminding about outdated packages every day. Contributing an update PR has a much better chance of success.

**Comment by bastimeyer** [comment]
> I am not a user of Void, I'm just interested in having my application updated to the latest version.
