### ISSUE TITLE
Package request:  update wlroots to 0.18

### ISSUE THREAD

**Issue by i0rxg** [void-linux/void-packages#52759]
### Package name

wlroots

### Package homepage

https://gitlab.freedesktop.org/wlroots/wlroots

### Description

wlroots is a modular Wayland compositor library that provides the building blocks necessary to develop a Wayland compositor. It handles much of the low-level work required for Wayland compositors, abstracting away complexities such as input handling, output management, and dealing with graphics like EGL, OpenGL, and Vulkan.

### Does the requested package meet the package requirements?

System, Compiled, Required

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
Please don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help.
