### ISSUE TITLE
Missing build dependency in Thunar causes 8-second delay when loading the XFCE desktop

### ISSUE THREAD

**Issue by Kerberoge** [void-linux/void-packages#52766]
_This issue is even present in the official XFCE live image._

The XFCE desktop environment in started by running `startxfce4`. This launches `xfce4-session`, which in turn launches the following programs, in this order: `xfwm4`, `xfsettingsd`, `xfce4-panel`, `Thunar --daemon`, and `xfdesktop`.

Currently, when launching the XFCE desktop environment on a Void Linux system, the loading of the wallpaper is delayed by 8 seconds. This is because `Thunar --daemon` somehow fails to start due to being incorrectly compiled, and thus this causes the `xfdesktop` background process, which is responsible for the wallpaper, to be delayed as well. As stated above, this issue can even be observed when booting the official Void Linux XFCE live image.

The delay can be fixed by adding the missing build dependency to the Thunar template file, namely `xorg-server-devel`. Presumably the `configure` script is automatically disabling some important option when it detects that the relevant Xorg development files are not present, which happens to impede Thunar from properly starting as a daemon process.

**Comment by sgn** [comment]
I hope 94d0d1b1f16 fixed your problem. If not, please voice!

**Comment by Kerberoge** [comment]
That commit did indeed fix the problem. Thanks!
