### ISSUE TITLE
Package request: TailScale update

### ISSUE THREAD

**Issue by internet-catte** [void-linux/void-packages#52772]
### Package name

tailscale

### Package homepage

https://tailscale.com

### Description

TailScale 1.76.3 is available, please update it!

see https://github.com/tailscale/tailscale/tags

### Does the requested package meet the package requirements?

System, Compiled, Required

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
Please don't request an update of a package, [We have a script for that](https://repo-default.voidlinux.org/void-updates/void-updates.txt). However, a quality pull request may help. 

also, see the changelog:

https://tailscale.com/changelog#2024-10-16

> Note: v1.76.2 includes fixes for Android TV devices only, and is exclusively released for Android.

> Note: v1.76.3 includes fixes for Windows devices only, and is exclusively released for Windows.

**Comment by internet-catte** [comment]
oh ok... I didn't know
