### ISSUE TITLE
pinctrl-alderlake

### ISSUE THREAD

**Issue by onuronsekiz** [void-linux/void-packages#52795]
It seems there are some missing intel modules in Void Linux kernel. Particularly intel's _**pinctrl-alderlake**_ module is essential because its absence cause some new generation cpu's issues. Touchpad not working, wifi drops, acpi problems, etc. I have encountered it on a laptop. On Arch touchpad works, on Void it doesn't. When a kernel is compiled from source, touchpad started to work on Void too because now it has _**pinctrl-alderlake**_ module loaded.

**Comment by sgn** [comment]
122c049b418542ea47178902562f44174f67fcb3
They will be built with new kernel release.

In the meantime, use `linux6.1` version `6.1.114`
