### ISSUE TITLE
Linux Kernel MT7925E and MT7925U modules

### ISSUE THREAD

**Issue by aadi58002** [void-linux/void-packages#52949]
### Is this a new report?

Yes

### System Info

Void 6.11.6_1 x86_64 AuthenticAMD uptodate rFF

### Package(s) Affected

linux6.11

### Expected behaviour

Wifi being detected and working

### Actual behaviour

Missing modules. Hence motherboard wifi is not detected.

**Comment by aadi58002** [comment]
https://github.com/void-linux/void-packages/blob/ec03eb747cff32b73e974781f1659a630534e0ca/srcpkgs/linux6.11/files/x86_64-dotconfig#L3944

I assume the above kernel modules needs to be enabled to address the issue.

Are there any guideline for issue on how to request addition of kernel modules ?

**Comment by classabbyamp** [comment]
added to `linux6.12`:
https://github.com/void-linux/void-packages/blob/6ab6b05a274ec412815e3bf804e805b5b58841fe/srcpkgs/linux6.12/files/x86_64-dotconfig#L3983-L3985
