### ISSUE TITLE
ThinkPad P14s Gen 2i doesn't boot after updating linux from 6.6.57_1 to 6.6.59_1

### ISSUE THREAD

**Issue by pudiva** [void-linux/void-packages#53144]
### Is this a new report?

Yes

### System Info

Void 6.6.57_1 x86_64 GenuineIntel notuptodate rrFFF

### Package(s) Affected

linux6.6-6.6.59_1 linux6.6-6.6.61_1 

### Expected behaviour

System boots normally.

### Actual behaviour

System freezes forever showing Lenovo logo after selecting kernel on grub. I got no error messages or any other useful output. System boots fine with the older 6.6.57_1 kernel I still have installed, but not with 6.6.59_1 or 6.6.61_1.

### Steps to reproduce

On a ThinkPad P14s Gen 2i:

1. update linux from 6.6.57_1 to 6.6.59_1 or 6.6.61_1
2. reboot
3. see the system freeze after grub

**Comment by classabbyamp** [comment]
do you have a separate boot partition? is it full?

**Comment by pudiva** [comment]
@classabbyamp wow... maybe it is? what do you think?

```
$ df -h
...
/dev/nvme0n1p2                  448M  364M   56M  87% /boot
...
```

**Comment by pudiva** [comment]
@classabbyamp I just realised that there's no `initramfs-6.6.*.img` for the versions I just reported...

**Comment by classabbyamp** [comment]
ok try running [vkpurge](https://man.voidlinux.org/vkpurge) then `xbps-reconfigure -f linux6.6`
