### ISSUE TITLE
Applications not showing up in Brisk Menu after being installed

### ISSUE THREAD

**Issue by leeminusminus** [void-linux/void-packages#53307]
### Is this a new report?

Yes

### System Info

Void 6.6.63 x86_64

### Package(s) Affected

brisk-menu 0.6.2_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

No.

### Expected behaviour

Brisk Menu refreshes all application shortcuts and shows newly installed ones

### Actual behaviour

The application does not immediately appear in the Brisk Menu. NOTE: It does appear after restarting the session or creating a new Brisk Menu, but doesn't show automatically like it should. It also doesn't affect Flatpaks.

### Steps to reproduce

In terminal, type "sudo xbps-install -S {application}"
Open Brisk Menu and search for app
App isn't found

**Comment by ahesford** [comment]
This is almost certainly not a Void issue. It may be an upstream bug, or may require some integration tasks that are not performed automatically on Void. I suggest you consult upstream for debugging and advice.

If you uncover a definitive packaging issue here, please let us know.

**Comment by leeminusminus** [comment]
I tested this on Debian and I have previously used Arch. Neither had this problem with the brisk menu. This is most likely a void issue.

**Comment by leeminusminus** [comment]
> This is almost certainly not a Void issue. It may be an upstream bug, or may require some integration tasks that are not performed automatically on Void. I suggest you consult upstream for debugging and advice.
> 
> If you uncover a definitive packaging issue here, please let us know.

Okay, so I may have found some sort of solution to the problem.

https://github.com/getsolus/brisk-menu

![image](https://github.com/user-attachments/assets/01cbd7d4-d3a8-446b-a106-dcccc14f23cf)

I tried installing it from source. The first (plain) version had the same problems, but the second (debugoptimized) worked as expected. This might lead to a solution, I think.
