### ISSUE TITLE
Package request: btpd

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#5341]
https://github.com/btpd/btpd

**Comment by CameronNemo** [comment]
Last release was 8 years ago. Any reason you want this instead of another torrent daemon?

**Comment by Bumbadawg** [comment]
@maxice8 Hi, it got updated 3 months ago, it's minimalist and won't jump on any new trendy features. Please add it.

**Comment by maxice8** [comment]
I'm not a Void Linux developer/contributor anymore, I suggest you open a
new issue to see if someone wants to add it for you.

**Comment by Bumbadawg** [comment]
alright @maxice8 , i actually won't bother since it doesn't support magnets (hue) and went with transmission-daemon.
But your word to the wise shall prevail

**Comment by Duncaen** [comment]
Please stop bumping package requests, there are no news if nobody posts them.
