### ISSUE TITLE
fftw CLOCK_SGI_CYCLE invalid argument (hanging up gqrx and others) 

### ISSUE THREAD

**Issue by paigeadelethompson** [void-linux/void-packages#53417]
### Is this a new report?

Yes

### System Info

aarch64-musl

### Package(s) Affected

fftw

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/FFTW/fftw3/issues/122

### Expected behaviour

working

### Actual behaviour

not working

### Steps to reproduce

not sure what the deal is with this, or why that `CLOCK_SGI_CYCLE` is getting enabled (it shouldn't be) but other people were having problems with this and there was a fix issued for it however I don't know, I downloaded the source tarball and just removed the define that enabled the tick counter for `CLOCK_SGI_CYCLE` from the source because it seemed like it might be getting enabled anyway but maybe all this package needs is a version bump

**Comment by paigeadelethompson** [comment]
https://www.youtube.com/shorts/HMNndHLQ3Zs

It does work but the reason it works might be because I deleted this to make sure it would: 

https://github.com/FFTW/fftw3/blob/187045ea647ba19c55db5f503d11bd811ee6b56e/kernel/cycle.h#L441

It might have also been unnecessary, I just downloaded the source from https://www.fftw.org/download.html `3.3.10`

**Comment by paigeadelethompson** [comment]
Yeah I just looked at https://github.com/void-linux/void-packages/blob/master/srcpkgs/fftw/template#L3 and its the same version so I'm really not sure why on aarch64-musl that is getting enabled but it is and it will fail because it's some option specific to SGI's platform.. seems like other people have had this problem though too and they tried to fix it but apparently they didn't..

**Comment by gmbeard** [comment]
Upstream doesn't appear to be in any rush to address the issues / PRs that others have raised, so maybe the best option would be to just patch out the SGI/Irix check in our build completely. All the other Void architectures seem to be supported by the remaining checks.

**Comment by paigeadelethompson** [comment]
Yeah that's along the lines of what I was hoping you would say if nothing else, would it help if I sent you a PR?

**Comment by paigeadelethompson** [comment]
I created a patch and tested the build for `aarch64-musl` really quick and it seemed to build fine just as before, PR sent in https://github.com/void-linux/void-packages/pull/53442
