### ISSUE TITLE
Whiptail free(): invalid pointer error

### ISSUE THREAD

**Issue by marty-thane** [void-linux/void-packages#53427]
### Is this a new report?

Yes

### System Info

Void 6.6.63_1 x86_64 GenuineIntel uptodate FF

### Package(s) Affected

newt-0.52.21_7

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1022052;msg=26
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1706930.html

### Expected behaviour

Using `whiptail`'s `--menu` option and selecting one of the items, `whiptail` should print selected item's tag to `stdout` with exit code `0`.

### Actual behaviour

Upon selecting one of the items, `whiptail` prints:
```
free(): invalid pointer
Aborted
```
with exit code `134`.

### Steps to reproduce

1. Run `whiptail --menu 'select item:' 0 0 0 'foo' 'bar'`.
2. Select item.
3. Get error.

**Comment by gmbeard** [comment]
I'm able to replicate this issue, and can confirm that version `0.52.24` fixes it (PR #53500)

**Comment by gmbeard** [comment]
This should now be fixed as of https://github.com/void-linux/void-packages/commit/a5175314a5f30a8980b160088ae979be3e9abca9
