### ISSUE TITLE
Request: enable javascript feature in mpv

### ISSUE THREAD

**Issue by S-u-m-u-n** [void-linux/void-packages#53474]
### Package name

mpv

### Package homepage

https://mpv.io/

### Description

**mpv** is already in the repository, but does not have javascript enabled. This can be verified with `mpv -v | grep "List of enabled features:"`. Therefore, custom mpv js scripts can not be used with the Void Linux mpv package.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

Yes

**Comment by Vinfall** [comment]
Should be resolved with https://github.com/void-linux/void-packages/commit/d1b9706f01706790b78a98ed6caed0917d91fc14.

```sh
$ mpv -v | grep "List of enabled features:" | grep javascript
[cplayer] List of enabled features: alsa build-date cdda cplugins dmabuf-interop-gl dmabuf-wayland drm dvbin dvdnav egl egl-drm egl-wayland egl-x11 ffmpeg gbm gl glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libplacebo linux-fstatfs lua memfd-create memrchr pipewire posix posix-shm ppoll pthread-condattr-setclock pulse rubberband rubberband-3 sndio sndio-1-9 uchardet vaapi vaapi-drm vaapi-wayland vaapi-x11 vdpau vector vk-khr-display vt.h vulkan wayland wayland-protocols-1-32 x11 xv zlib
```
