### ISSUE TITLE
sddm: shutdown, suspend and restart not working

### ISSUE THREAD

**Issue by joshuakraemer** [void-linux/void-packages#535]
### System

* xuname:
Void 4.16.14_1 x86_64 GenuineIntel uptodate rF
* package:
sddm-0.15.0_2
elogind-238.1_1
dbus-1.12.8_1

### Expected behavior
The buttons to shutdown, suspend and restart should work after booting.

### Actual behavior
After booting, the buttons are not shown or they are disabled (depending on the theme). When sddm service is restarted, the buttons work.

### Steps to reproduce the behavior
`sudo xbps-install -R sddm dbus elogind polkit-elogind`
`sudo ln -s /etc/sv/sddm /var/service/`
`sudo ln -s /etc/sv/dbus /var/service/`
reboot
try to click the shutdown/suspend/restart buttons in sddm
`sudo sv restart sddm`
try to click the shutdown/suspend/restart buttons in sddm again

I think this is a race condition with elogind. This has also been reported upstream: https://github.com/sddm/sddm/issues/978

I think the sddm service should wait for elogind to start. But I do not know how to add a check for elogind, because there are no service files for elogind. It seems to be started by some other mechanism than runit.

**Comment by CameronNemo** [comment]
elogind is started by the dbus-daemon. sddm should add a check for dbus-daemon, like NetworkManager has.

    sv check dbus >/dev/null || exit 1

**Comment by CameronNemo** [comment]
Any update on whether this is still an issue or not?

**Comment by joshuakraemer** [comment]
This is still an issue, unfortunately.

**Comment by dsanmartins** [comment]
I have the same problem.

**Comment by dezifit** [comment]
Same here (sddm-0.18.0_2, elogind-239.3_1). The related upstream issue sddm/sddm#978 (race condition) is closed now, but sddm still doesn't find the logind interface on the first start (log message " Logind interface found").

**Comment by Duncaen** [comment]
The issue was "solved" by making sure that sddm starts after the `systemd-logind.service`, which is something we can't really do.

Maybe the last command in https://dbus.freedesktop.org/doc/system-activation.txt could be added to the `run` script, but then it would explicitly depend on elogind.

**Comment by dezifit** [comment]
Is a condition acceptable in runit scripts? The following code (thanks for the link) does work for me:
```
sv check dbus >/dev/null || exit 1

if [ -f /etc/elogind/logind.conf ]; then
        dbus-send --system --print-reply --dest=org.freedesktop.DBus \
                /org/freedesktop/DBus                           \
                org.freedesktop.DBus.StartServiceByName         \
                string:org.freedesktop.login1 uint32:0
fi
```
This code solves the issue for me.

**Comment by joshuakraemer** [comment]
Thank you for solving this, it works now.
