### ISSUE TITLE
Cinnamon 6.4.2 some DE windows don't display properly

### ISSUE THREAD

**Issue by tre-flip** [void-linux/void-packages#53513]
### Is this a new report?

Yes

### System Info

Void 6.6.65_1 x86_64 AuthenticAMD uptodate rF

### Package(s) Affected

cinnamon-6.4.2_2

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

After the update to 6.4.2, OSD and some dialogs display poorly. OSDs have no backgrounds and indicator bars, "logout", "shutdown" and other Cinnamon dialogs also have no backgrounds, and the buttons are much smaller.

An example of an OSD without background and indicators is at the very bottom of the screen in the attached screenshot.
![2024-12-14_00-08](https://github.com/user-attachments/assets/363672ac-096c-42e4-a192-b0a2c92342a2)
![2024-12-14_01-14](https://github.com/user-attachments/assets/7f5f948b-79e0-4eb3-8151-274496dc5801)

### Expected behaviour

OSD should have indicator bars. Cinnamon dialogs should have larger buttons. OSD and Cinnamon dialogs should have backgrounds.

### Actual behaviour

OSD don't have indicator bars. Cinnamon dialogs don't have larger buttons. OSD and dialogs don't have backgrounds.

### Steps to reproduce

Try to change volume or screen brightness using media keys, try to log out or restart the system using cinnamon panel menu.

**Comment by toadwastoast** [comment]
I'm pretty sure that the issue here is that on 6.4 Cinnamon changed the default look of the desktop theme and old themes just aren't compatible. See if changing to the default cinnamon theme fixes it.

**Comment by tre-flip** [comment]
> I'm pretty sure that the issue here is that on 6.4 Cinnamon changed the default look of the desktop theme and old themes just aren't compatible. See if changing to the default cinnamon theme fixes it.

Yes, you're right. That's sad. Thanks anyway! Now I'll try to figure out how to port my favorite theme to the new version.

**Comment by tre-flip** [comment]
> I'm pretty sure that the issue here is that on 6.4 Cinnamon changed the default look of the desktop theme and old themes just aren't compatible. See if changing to the default cinnamon theme fixes it.

Yes, you're right. That's sad. Thanks anyway! Now I'll try to figure out how to port my favorite theme to the new version.
