### ISSUE TITLE
Can't crossbuild zstd to i686-musl

### ISSUE THREAD

**Issue by xeroxslayer** [void-linux/void-packages#53532]
### Is this a new report?

Yes

### System Info

Void 6.6.65_1 x86_64 GenuineIntel uptodate rrrmFFFFFFFFF

### Package(s) Affected

cross-vpkg-dummy-0.40_1, zstd-1.5.6_1

### Expected behaviour

Crossbuild zstd to i686-musl.

### Actual behaviour

It doesn't corssbuild.

### Steps to reproduce

Try to crossbuild zstd from i686/x86_64/x86_64-musl to i686-musl.

````
=> ERROR: zstd-1.5.6_1: failed to install target dependencies! (error 11)
CONFLICT: cross-vpkg-dummy-0.40_1 with musl-1.1.24_22 in transaction (matched by musl>=0)
````

**Comment by classabbyamp** [comment]
don't cross build, do it natively with -A

**Comment by xeroxslayer** [comment]
You can't build the binary bootstrap natively.

**Comment by sgn** [comment]
It reports that `MISSING: musl>=1.1.24_7` which should be provided by `cross-vpkg-dummy`, not sure what is going on here!

**Comment by sgn** [comment]
OK, `cross-vpkg-dummy` doesn't have `provides`

**Comment by sgn** [comment]
MCVE for other *supported* receipts:

```sh
./xbps-src zap
./xbps-src binary-bootstrap
./xbps-src -a armv7l-musl pkg cross-vpkg-dummy
./xbps-src -a armv7l-musl build zstd
```

**Comment by sgn** [comment]
Fixed, please:

```sh
./xbps-src zap
./xbps-src binary-bootstrap
./xbps-src -a i686-musl pkg cross-vpkg-dummy
```
and try again

**Comment by xeroxslayer** [comment]
@sgn The same is reported again.

````
=> ERROR: zstd-1.5.6_1: failed to install target dependencies! (error 11)
CONFLICT: cross-vpkg-dummy-0.40_1 with musl-1.1.24_22 in transaction (matched by musl>=0)
Transaction aborted due to conflicting packages.
=> ERROR: Please see above for the real error, exiting...
````
