### ISSUE TITLE
ranger bulk rename not working

### ISSUE THREAD

**Issue by marty-thane** [void-linux/void-packages#53543]
### Is this a new report?

Yes

### System Info

Void 6.6.63_1 x86_64 GenuineIntel notuptodate FF

### Package(s) Affected

ranger-1.9.4_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

https://github.com/ranger/ranger/issues/2934

### Expected behaviour

After editing filenames with `:bulkrename` and saving, ranger should rename the files and return to normal view.

### Actual behaviour

Saving and quitting results in ranger crashing with `endwin() returned ERR` error message.

### Steps to reproduce

1. Open ranger
2. Select any number of files
3. type `:bulkrename` and hit Enter
4. Make any changes to filenames
5. Save and quit
6. Get error/crash

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/f5ba14434f21b7bd62bc34243b468bdf2af69f89
