### ISSUE TITLE
emacs missing for aarch64-musl (build succeeds, tested but package is not present in repository) 

### ISSUE THREAD

**Issue by paigeadelethompson** [void-linux/void-packages#53565]
### Is this a new report?

Yes

### System Info

aarch64-musl

### Package(s) Affected

emacs

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

This may be related but I'm unsure how https://github.com/void-linux/void-packages/issues/21483

### Expected behaviour

The package is available in x86_64-musl: https://voidlinux.org/packages/?arch=x86_64-musl&q=emacs

### Actual behaviour

The package is not available in aarch64-musl: https://voidlinux.org/packages/?arch=aarch64-musl&q=emacs but I can build it with `xbps-src pkg` on `aarch64-musl` and I can install it and it runs just fine: 

```
bash-5.2# xbps-install --repository=hostdir/binpkgs/emacs/ emacs
Package `emacs' already installed.
bash-5.2# emacs --version
GNU Emacs 29.4
Copyright (C) 2024 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
bash-5.2#
```

### Steps to reproduce

not applicable

**Comment by leahneukirchen** [comment]
Emacs cannot be cross compiled as it needs to start to dump the image.

aarch64 is only supported via cross-compilation, so you need to keep building it yourself.

**Comment by paigeadelethompson** [comment]
Cool, what about using something like qemu-user-binfmt or something then as a build dependency to dump the image? To be honest I don't really know what else qemu-user-binfmt is good for if not that, I actually use it to help build a Void Linux image for the uConsole: https://github.com/Ravenhammer-Research/void-uconsole/blob/master/.github/workflows/build.yml#L82

it doesn't need to be that complicated, though just install it and register the binfmt hooks (I think someone made a runit svc that runs a script but it's simple: https://docs.kernel.org/admin-guide/binfmt-misc.html

On Void the two packages needed are `binfmt-support` and `qemu-user-aarch64`

**Comment by paigeadelethompson** [comment]
.... @gmbeard what do you think ?

**Comment by gmbeard** [comment]
I don't have any experience with emacs, let alone building it. leahneukirchen is the pkg maintainer (and a void team member) so I'd have to defer to their better judgement.

**Comment by classabbyamp** [comment]
yes it could be possible to use qemu-user (we use it sometimes already for small things like running binaries that generate completions), but it's *very* slow and can be hard to integrate into build systems.

**Comment by paigeadelethompson** [comment]
>  but it's _very_ slow and can be hard to integrate into build systems.

totally aware, https://github.com/Ravenhammer-Research/void-uconsole/blob/master/.github/workflows/build.yml the kernel fortunately cross compiles fairly easily otherwise I probably wouldn't have been able to build the entire image for this device in one action runner; the kernel is cross-compiled on-host and the rest of the OS is put together with a Dockerfile then exported to a filesystem mounted via `losetup`. This all works well, you can download the image that it builds from the releases page, I'm using it on my own uConsole:

![IMG_3471](https://github.com/user-attachments/assets/6796e516-3610-422f-a864-ea50af5460f5)

The image is obviously not this advanced on its own; you need an Ansible playbook to build up to this: https://github.com/paigeadelethompson/paige-ansible-uconsole but the image does provide everything you need including Ansible. TLDR though yeah I know I made this look way easier than it was (I made it for a friend but I already had experience doing this with debootstrap previously.) Anyway, I did it as a favor for a friend and later he offered to get me one for myself and I figured well I've already got the Void image for it so it's given me an excuse to do a bit more than admire Void from a distance (I like Void I've just never been able to justify getting into it and using it for anything to myself because there's so many other things that I already know how to use.)
