### ISSUE TITLE
Linux 6.12 compression algorithms and zram.

### ISSUE THREAD

**Issue by eskeletor97** [void-linux/void-packages#53580]
### Is this a new report?

Yes

### System Info

Void 6.12.4_1 x86_64 AuthenticAMD uptodate rrrmmnFFFFFFFFFFF

### Package(s) Affected

linux6.12-6.12.4_1, zramen-0.7.0_1

### Expected behaviour

Upgrading from 6.6 to 6.12 shouldn't yield any problems.

### Actual behaviour

After upgrading from 6.6 to 6.12 everything went fine except zramen gave error on boot. I tried to enable it manually and it gave the following error: `zramctl: /dev/zram0: failed to set algorithm: Invalid argument`.
I checked available algorithms using `cat /sys/block/zram0/comp_algorithm`. It only output `lzo-rle [lzo]`.
Back on 6.6: `[lzo] lzo-rle lz4 lz4hc 842 zstd`.

### Steps to reproduce

1. Install zramen on linux6.12.
2. Enable zram service.
3. zramen fails because by default it expects lz4.

**Comment by yoshiyoshyosh** [comment]
can replicate on `linux6.12-6.12.6_1`. downgrading to `linux6.11-6.11.11_1` fixes the issue.

**Comment by yoshiyoshyosh** [comment]
digging into it some and found a gentoo report https://bugs.gentoo.org/946547

seems like they're actually using those `CONFIG_ZRAM_BACKEND` parameters now
