### ISSUE TITLE
Remove newt-python from repo index

### ISSUE THREAD

**Issue by gmbeard** [void-linux/void-packages#53589]
The `newt-python` package seems to still be present in some of the repos despite being added to `removed-packages` some time ago. This package has a dependency on Python2.7 so is unusable.

This also appears to be blocking a package update PR - #53500

**Comment by classabbyamp** [comment]
done. packages aren't automatically removed from the repo indexes by `removed-packages`, only from users' systems.

**Comment by gmbeard** [comment]
Thank you!

Yes, I figured there must be an additional process to remove these pkgs from the repo.
