### ISSUE TITLE
Signal Desktop v7.34 and v7.36 packages are missing program icons

### ISSUE THREAD

**Issue by gc-user** [void-linux/void-packages#53612]
### Is this a new report?

Yes

### System Info

Void 6.6.67_1 x86_64 GenuineIntel uptodate hold rrmDDDDDDDFFFFFFFFF

### Package(s) Affected

Signal-Desktop-7.36.1_1.x86_64

### Expected behaviour

There should be an icon shown for the application in the menu but there isn't.

### Actual behaviour

In the start / program menu the signal program icon is missing because the package is missing /usr/share/icons.
This was already the case in the package for v7.34 of signal desktop.

Not sure why since v7.34 the [respective code](https://github.com/void-linux/void-packages/commit/3f40bc263e1b04deddce4ac5d777103f66a08527) to install (or even include into the package) the icons was removed from the template.

### Steps to reproduce

1. Install v7.36 (or v7.34) xbps package for Signal Desktop
2. Notice missing icon in the menu or the missing /usr/share/icons in the package itself.

**Comment by classabbyamp** [comment]
@voidisnull

**Comment by voidisnull** [comment]
@gc-user 
As of v7.34 the upstream has removed the hicolor icons from the release package

Therefore, I removed it from the template

**Comment by gc-user** [comment]
> @gc-user ~As of v7.34 the upstream has removed the icons from the release package~
> ~Therefore, I removed it from the template~
Understand, makes sense. Strange upstream decision...

Seem like they moved the icons to /build/icons/png.

**Comment by voidisnull** [comment]
I have added this to the do_install() to fix the issue 

```
for size in 16 24 32 64 128 256 512 1024; do
                vinstall build/icons/png/${size}x${size}.png 644 usr/share/icons/hicolor/${size}x${size}/apps signal-desktop.png
done
```

And it's giving me an error while building, I don't know what am I doing wrong.
So someone can please help me out here
<br/>
Error
```
[build:release     ]   • skipping "afterSign" hook as no signing occurred, perhaps you intended "afterPack"?
[build:release     ]   • building        target=deb arch=x64 file=release/signal-desktop_7.36.1_amd64.deb
[build:release     ]   • adding autoupdate files for: deb. (Beta feature)  resourceDir=/builddir/Signal-Desktop-7.36.1/release/linux-unpacked/resources
[build:release     ]   ⨯ cannot execute  cause=fork/exec /tmp/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm: exec format error
[build:release     ]                     command=/tmp/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/fpm -s dir --force -t deb -d libnotify4 -d libxtst6 -d libnss3 -d libasound2 -d libpulse0 -d libxss1 -d 'libc6 (>= 2.31)' -d libgtk-3-0 -d libgbm1 -d libx11-xcb1 --deb-recommends libappindicator3-1 --deb-compression xz --architecture amd64 --after-install /tmp/t-EHlozy/0-after-install --after-remove /tmp/t-EHlozy/1-after-remove --description '
[build:release     ]      Private messaging from your desktop' --version 7.36.1 --package /builddir/Signal-Desktop-7.36.1/release/signal-desktop_7.36.1_amd64.deb --name signal-desktop --maintainer 'Signal Messenger, LLC <support@signal.org>' --url 'https://github.com/signalapp/Signal-Desktop#readme' --vendor 'Signal Messenger, LLC <support@signal.org>' --deb-priority optional --license AGPL-3.0-only /builddir/Signal-Desktop-7.36.1/release/linux-unpacked/=/opt/Signal /builddir/Signal-Desktop-7.36.1/build/icons/png/16x16.png=/usr/share/icons/hicolor/16x16/apps/signal-desktop.png /builddir/Signal-Desktop-7.36.1/build/icons/png/24x24.png=/usr/share/icons/hicolor/24x24/apps/signal-desktop.png /builddir/Signal-Desktop-7.36.1/build/icons/png/32x32.png=/usr/share/icons/hicolor/32x32/apps/signal-desktop.png /builddir/Signal-Desktop-7.36.1/build/icons/png/48x48.png=/usr/share/icons/hicolor/48x48/apps/signal-desktop.png /builddir/Signal-Desktop-7.36.1/build/icons/png/64x64.png=/usr/share/icons/hicolor/64x64/apps/signal-desktop.png /builddir/Signal-Desktop-7.36.1/build/icons/png/128x128.png=/usr/share/icons/hicolor/128x128/apps/signal-desktop.png /builddir/Signal-Desktop-7.36.1/build/icons/png/256x256.png=/usr/share/icons/hicolor/256x256/apps/signal-desktop.png /builddir/Signal-Desktop-7.36.1/build/icons/png/512x512.png=/usr/share/icons/hicolor/512x512/apps/signal-desktop.png /builddir/Signal-Desktop-7.36.1/build/icons/png/1024x1024.png=/usr/share/icons/hicolor/1024x1024/apps/signal-desktop.png /tmp/t-EHlozy/2-Signal.desktop=/usr/share/applications/signal-desktop.desktop
[build:release     ]                     workingDir=
ERROR: "build:release" exited with 1.
=> ERROR: Signal-Desktop-7.36.1_2: do_build: 'npm run build' exited with 1
=> ERROR:   in do_build() at srcpkgs/Signal-Desktop/template:43
```

**Comment by gc-user** [comment]
I certainly don't know what's wrong, but I noticed that you didn't mention you added the line

`vmkdir usr/share/icons/hicolor`

also back into the template. Not sure if that was missing it would / could cause the process to fail a few lines earlier... at line 43: ` do_build: 'npm run build'`

**Comment by voidisnull** [comment]
> I certainly don't know what's wrong, but I noticed that you didn't mention if you added the line
> 
> `vmkdir usr/share/icons/hicolor`

This won't make any difference I have checked it before
> 
> also back into the template. Not sure if that was missing it would / could cause the process to fail a few lines earlier... at line 43: ` do_build: 'npm run build'`
> 

I'm sorry but I don't quite understand what do you mean by this

> Also, in the old template it was [...]`/apps signal-desktop.png`, now it's [...]`/apps/ signal-desktop.png`. Not sure if that (the additional "/" after `apps`) makes any difference at all.

This too won't cause any problems either, we're just mentioning the path

**Comment by MIvanchev** [comment]
@voidisnull maybe share the PR here so we can help debugging.

**Comment by MIvanchev** [comment]
One thing is see missing is `depends="desktop-file-utils hicolor-icon-theme"`

**Comment by classabbyamp** [comment]
that shouldn't matter

**Comment by MIvanchev** [comment]
So I managed to build successfully with [these changes](https://github.com/MIvanchev/void-packages/commit/b3c59a616d0ad1f839fd1628163def99685dc00d)

**Comment by voidisnull** [comment]
Thanks @MIvanchev for helping out!!

**Comment by gc-user** [comment]
@MIvanchev Thanks for the help and the fix!

**Comment by MIvanchev** [comment]
Have good times in Signal y'all!
