### ISSUE TITLE
 python3-pyasyncore 

### ISSUE THREAD

**Issue by petarzmaj** [void-linux/void-packages#53628]
### Is this a new report?

Yes

### System Info

Void Linux glibc

### Package(s) Affected

 python3-pyasyncore 

### Expected behaviour

Playonlinux.

### Actual behaviour

Hello Void. After last python3 update playonlinux not work. Always is problem with python3-pyasyncore. Playonlinux don't start and run.

### Steps to reproduce

Crash.

**Comment by classabbyamp** [comment]
do you have logs?
