### ISSUE TITLE
Package request: QAdwaitaDecorations

### ISSUE THREAD

**Issue by Jaymz665** [void-linux/void-packages#53629]
### Package name

QAdwaitaDecorations

### Package homepage

https://github.com/FedoraQt/QAdwaitaDecorations

### Description

Qt decoration plugin implementing Adwaita-like client-side decorations.

Since adwaita-qt is outdated morally, and adwaita-qt6 no longer has an effect on the window title, it would not be bad to have an updated package for decorations.

### Does the requested package meet the package requirements?

Compiled

### Is the requested package released?

No

**Comment by Jaymz665** [comment]
@fanyx @chrysos349 @oreo639 @elbachir-one 
I apologize in advance for bothering you all, but I may not find more experienced and interested people.

**Comment by fanyx** [comment]
If it's just a cmake package, i could tinker around
Can't test it tho, i don't use Qt applications a lot.

**Comment by Jaymz665** [comment]
> If it's just a cmake package, i could tinker around Can't test it tho, i don't use Qt applications a lot.

If anything, I'll always be happy to check it out =)

**Comment by classabbyamp** [comment]
please don't spam pings at random people. these are package *requests*. if someone feels interested in a package, they might choose to work on it
