### ISSUE TITLE
Package request: update granite7 to 7.6.0

### ISSUE THREAD

**Issue by tre-flip** [void-linux/void-packages#53677]
### Package name

granite7

### Package homepage

https://github.com/elementary/granite

### Description

New versions of elementary OS software require granite7 to be at least 7.2.0 to build. Updating granite7 would be a good start for packaging Elementary OS apps and components of Pantheon desktop environment for Void.

### Does the requested package meet the package requirements?

System

### Is the requested package released?

Yes

**Comment by MIvanchev** [comment]
@tre-flip I updated the package but maybe you can test it.

**Comment by tre-flip** [comment]
@MIvanchev Sure. 

I tested it with io.elementary.music, it works without any problems. There are not many applications in the repo that depend on granite7 so far. Also, I successfully built this https://github.com/elementary/dock. Should I test something else?

**Comment by tre-flip** [comment]
We updated granite7 to 7.6.0 and I built the dock successfully. But it doesn't work properly. I'm using Cinnamon desktop environment. Does the new Elementary OS dock expects Gala as a window manager now?

**Comment by MIvanchev** [comment]
@tre-flip I think this is enough :) Thanks! I just didn't want to test it locally (one of the requirements for submitting PRs) because I have no idea what it is.

**Comment by tre-flip** [comment]
Thanks for updating it!

**Comment by tranzystorekk** [comment]
Please do not open package bump requests, they're considered not useful in general.
