### ISSUE TITLE
Missing dependencies for eolie

### ISSUE THREAD

**Issue by SirSputnikWiki** [void-linux/void-packages#53681]
### Is this a new report?

Yes

### System Info

Void 6.12.6_3 x86_64 AuthenticAMD notuptodate rrmFFFFFFFFFFFFFF

### Package(s) Affected

eolie-0.9.101_3

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

The eolie browser fails to start if libhandy1 is not installed.  Installing it fixes the problem indicating it should probably be a dependency of the package.

### Expected behaviour

The browser launches as normal.

### Actual behaviour

It instead errors out with the following error message.

Traceback (most recent call last):
  File "/usr/bin/eolie", line 20, in <module>
    from eolie.application import Application
  File "/usr/lib/python3.13/site-packages/eolie/application.py", line 19, in <module>
    gi.require_version("Handy", "1")
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Handy not available


### Steps to reproduce

Attempt to run eolie in an environment where libhandy1 is not installed.

**Comment by classabbyamp** [comment]
this fix will be stuck in the queue behind a big set of packages, so you could also fix it by `xbps-install -A libhandy1`
