### ISSUE TITLE
Cyclic Build-Time Dependency for `python3-numpy`

### ISSUE THREAD

**Issue by Clos3y** [void-linux/void-packages#53720]
### Is this a new report?

Yes

### System Info

Void 6.12.6_3 x86_64 AuthenticAMD uptodate rrrmFFFFFF

### Package(s) Affected

python3-numpy-2.2.1_1 python3-hypothesis-6.123.0_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Not that I can see, no.

### Expected behaviour

`python3-numpy` is successfully built for running a package check

### Actual behaviour

```
=> ERROR: Build-time cyclic dependency python3-numpy(host), python3-hypothesis(host), python3-numpy(host) detected.
```

### Steps to reproduce

1. `$ ./xbps-src pkg -K [PACKAGE WITH python3-numpy AS A CHECKDEPENDS]`

I'm making a template file for cadabra, and it needs `python3-numpy` to pass the checks. This is my current template file.

```Bash
# Template file for 'cadabra'
pkgname=cadabra
version=2.5.10
revision=1
build_style=cmake
hostmakedepends="python3-devel pkg-config glibmm-devel sqlite-devel boost-devel openssl-devel gmp-devel gmpxx-devel gtkmm-devel git"
checkdepends="python3-gmpy2 python3-sympy python3-numpy"
short_desc="A field-theory motivated approach to computer algebra"
maintainer="clos3y <sam.w.close@gmail.com>"
license="GPL-3.0-or-later"
homepage="https://cadabra.science"
changelog="https://cadabra.science/changelog.html"
distfiles="https://github.com/kpeeters/cadabra2/archive/refs/tags/${version}.tar.gz"
checksum=d08bc3a159c677263a4e7ec6823b8e7cef04d540e1a540e1da1ef70c16f6abc7
```

**EDIT** This happens more generally. If you have `python3-numpy` as a *depends and add either `-K/-Q` this will occur.

**Comment by Johnnynator** [comment]
I don't think there is a sane way to solve this in a way that allows to run the check stage while compiling for the first time. `python3-hypothesis` (or `python3-numpy`) have to be build first without `-Q` / `XBPS_CHECK_PKGS` before the tests can be run.

**Comment by Clos3y** [comment]
> I don't think there is a sane way to solve this

I guess a semi-sane way would be to patch out the troublesome tests? It's only a handful of tests that require `numpy`, but it feels like a bit of a stop-gap solution.

**Comment by Clos3y** [comment]
> I guess a semi-sane way would be to patch out the troublesome tests? It's only a handful of tests that require `numpy`, but it feels like a bit of a stop-gap solution.

Yeah scratch that, this is something that probably needs fixing in general.

**Comment by ahesford** [comment]
As noted, just pre-build all the `checkdepends` for the package you wish to check. Avoid cycles in testing environments will never be possible.
