### ISSUE TITLE
Package request: Common Desktop Environment (CDE)

### ISSUE THREAD

**Issue by G00d-Syst3m** [void-linux/void-packages#53724]
### Package name

cde-desktop (or cdesktopenv)

### Package homepage

https://cdesktopenv.sourceforge.io/

### Description

Common Desktop Environment (CDE) is a desktop environment, based on the Motif widget toolkit.

### Does the requested package meet the package requirements?

System, Compiled

### Is the requested package released?

Yes

**Comment by classabbyamp** [comment]
duplicate of #25839
