### ISSUE TITLE
Updates from December 20, 2024 caused numerous problems in the Python environment

### ISSUE THREAD

**Issue by 81909ce2298f99ddafa37936ba43eaac** [void-linux/void-packages#53748]
### Is this a new report?

Yes

### System Info

Void 6.6.66-0-lts x86_64 AuthenticAMD uptodate rFF

### Package(s) Affected

python3-3.13.1_1 and several python3 libraries

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

Partly (please see "Actual behaviour")

### Expected behaviour

All python programs should run fine and it should be possible to reinstall them by using "pip".

### Actual behaviour

Starting several python programs or trying to reinstall them is not possible anymore. The update from December 20, 2024 caused numerous problems in the Python environment. Three components are already affected on my systems:

1. Synapse (this problem has been described and resolved here: https://github.com/void-linux/void-packages/issues/53595)

2. Telegram bridge (the problem was described here and has not been resolved because it is no longer possible to compile the source code even with asyncpg 0.30: https://github.com/mautrix/telegram/issues/986)

3. policyd-spf (for Postfix). There is no bug report for this, but here too the problem is due to the update of the Python environment.

Notes: 
- The programs under points 2 and 3 were installed via "pip".
- The reference in point 1 shows a list of all updated programs and libraries on December 20, 2024

I think that this update should be checked more thoroughly. To me it looks like the update is causing a lot of incompatibilities.

### Steps to reproduce

Please see the 2 other reports beeing mentioned above.

**Comment by sgn** [comment]
I don't think we have support for third-party managed software, including and not limited to pip.

**Comment by 81909ce2298f99ddafa37936ba43eaac** [comment]
I understand that. But if the Python environment is updated via package management, I don't think applications should break one after the other. And it didn't just affect manually installed Python applications, but also Synapse, which is also provided by package management.

**Comment by ahesford** [comment]
Virtual environments break when you replace the system Python. It's an unavoidable problem. If you're installing packages with pip outside of a virtual environment, against the explicity advice we provide when you try to do so, you'll have even bigger problems.

Void ships exactly one version of Python 3 for general consumption. We have not found a suitable way to support multiple versions. The version is updated when a team member (generally me) finds time to undertake the effort, and there are no major objections from the rest of the team. Although we try to ensure major software continues to operate, some compatibility issues are bound to appear in lesser used or more complex Python packages (which often do things they shouldn't and are very slow to move away from deprecated interfaces).

If you want stability, you should use a distribution that aims for stable versioning. Rolling releases roll on with or without you.
