### ISSUE TITLE
Nvidia470 dkms fails to build on kernel 6.12

### ISSUE THREAD

**Issue by netkv** [void-linux/void-packages#53759]
### Is this a new report?

Yes

### System Info

Void 6.1.114_2 x86_64 GenuineIntel uptodate rrmmnFFFFF

### Package(s) Affected

nvidia470-470.239.06_1 nvidia470-dkms-470.239.06_1 linux6.12-6.12.7_1

### Does a report exist for this bug with the project's home (upstream) and/or another distro?

not sure if applicable but https://aur.archlinux.org/packages/nvidia-470xx-dkms

### Expected behaviour

When installing linux 6.12 DKMS is built without issues

### Actual behaviour

DKMS fails to build
![obrazek](https://github.com/user-attachments/assets/33f6a68e-9955-49a0-a6a5-e17e74b76663)

[make.log](https://github.com/user-attachments/files/18273355/make.log)

### Steps to reproduce

Try install nvidia470 on linux6.12
xbps will try to build dkms but fails

/var/lib/dkms/nvidia/470.239.06/build/make.log
```
make[2]: *** [/usr/src/kernel-headers-6.12.7_1/Makefile:1937: /var/lib/dkms/nvidia/470.239.06/build] Chyba 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/kernel-headers-6.12.7_1'
make: *** [Makefile:80: modules] Error 2
```

**Comment by ahesford** [comment]
The 470 series predates Linux 6.12 by several years, so it isn't surprising that it will eventually fail to compile. Either upgrade to a newer driver or use an older kernel.
