### ISSUE TITLE
Package request: Parsec

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#5382]
Hi
Could I please request Parsec to be packaged for Void?
The Github link is: https://github.com/Kozova1/parsec-fedora
The website is at: https://support.parsecgaming.com/hc/en-us/articles/115003477771-Using-Parsec-With-other-Linux-Distros
Thanks.

**Comment by maxice8** [comment]
Please use our issue naming scheme

**Comment by maxice8** [comment]
> Could I please request Parsec to be packaged for Void?

Don't ask to ask, just ask

**Comment by anarchomoh** [comment]
Thanks, will do in future.

**Comment by maxice8** [comment]
We tried packaging it but we can't due to the lack of a downloadable link with version attached.

**Comment by anarchomoh** [comment]
Hi Maxice, will the Ubuntu .Deb file work?  It's here:

https://s3.amazonaws.com/parsec-build/package/parsec-linux.deb

**Comment by maxice8** [comment]
On Wed, Feb 20, 2019 at 03:45:39AM -0800, anarchomoh wrote:
> Hi Maxice, will the Ubuntu .Deb file work?  It's here:
> 
> https://s3.amazonaws.com/parsec-build/package/parsec-linux.deb
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/5382#issuecomment-465541647

No it is not versioned, we need the distfile to have a version otherwise it will be changed underneath us and break the build.

it is **ABSOLUTELY** necessary.

**Comment by anarchomoh** [comment]
Thanks Maxice, I understand.  Much appreciated.

**Comment by Kozova1** [comment]
I've submitted a PR with a template for parsec.
