### ISSUE TITLE
ca-certificates problem

### ISSUE THREAD

**Issue by vitorhugomattos** [void-linux/void-packages#5384]
### System

* xuname:  
  can't install xuname :P
* package:  
  ca-certificates-20180409_2

### Expected behavior
 Use xbps as usual
### Actual behavior
 Can't update nor install nothing. It returns

`Certificate verification failed for /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
SSL_connect returned 1
ERROR: [reposync] failed to fetch file …`

### Steps to reproduce the behavior
 Just download and run the new live base image (i686, no DE) and try something with xbps

**Comment by CameronNemo** [comment]
It may help to know what repositories you have configured. Please run `xbps-query -L` and paste the output here.

**Comment by Hoshpak** [comment]
Please check your system time. Such errors are usually not caused by ca-certificates but by the system time not being set correctly so the libraries can't check the validity of certificates.

**Comment by vitorhugomattos** [comment]
omg, system time is wrog 'cause BIOS battery is dead, thank u. closing issue.
