### ISSUE TITLE
rustup broken

### ISSUE THREAD

**Issue by ebfe** [void-linux/void-packages#5398]
b079cb8f64452d4adf4a3faf45a58bf5595dac30 doesn't work as rustup as packaged
apparently doesn't create links in `.cargo/bin` in an clean environment:

```
$ rm -rf .rustup/ .cargo/bin/*
$ xbps-install rustup
$ sudo xbps-install rustup
Name   Action    Version           New version            Download size
rustup install   -                 1.15.0_1               - 
[...]
0 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.
$ . /etc/profile.d/rustup.sh 
$ rustup default stable
[...]
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu installed - rustc 1.30.1 (1433507eb 2018-11-07)

$ ls ~/.cargo/bin/
$ rustc
-bash: rustc: command not found
$ rustup which rustc
$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc

```

cc @Cogitri

**Comment by Cogitri** [comment]
Hum, I guess we'll have to keep the symlinks (for the core stuff) then in addition to the profile.d script (for stuff installed via rustup add component/cargo install).

**Comment by ebfe** [comment]
> Hum, I guess we'll have to keep the symlinks (for the core stuff) then
> in addition to the profile.d script (for stuff installed via rustup
> add component/cargo install). 

The profile stuff seems wrong anyways. This should be $CARGO_HOME/bin
which probably isn't set by the time /etc/profile.d/* is sourced.

**Comment by ebfe** [comment]
> Well, I suppose we should follow upstream than and just install rustup-init...

The upstream way is to have it's own update mechanism and to copy itself
to CARGO_HOME/bin. To prevent that the template compiles with
`--feature no-self-update`. But this also means you have to setup the
links that proxy `rustc` etc through `rustup` yourself.

**Comment by Cogitri** [comment]
> The upstream way is to have it's own update mechanism and to copy itself to CARGO_HOME/bin. To prevent that the template compiles with `--feature no-self-update`

The `no-self-update` feature is only a switch to determine if rustup should update itself from upstream's distfiles. Setting it only disables `rustup-init upgrade`  and `rustup init uninstall` but not `rustup-init install`
