### ISSUE TITLE
docker does not create systemd cgroup

### ISSUE THREAD

**Issue by go2null** [void-linux/void-packages#5402]
### System

* xuname:  
  - `Void 4.19.6_1 x86_64 GenuineIntel uptodate FF`
* package:  
  - `docker-18.09.0_1`

### Expected behavior

`docker` package should install all dependencies and make system changes as required.

### Actual behavior

`docker` fails to run.  This is a reposting of the same issue from the old repo (https://github.com/voidlinux/void-packages/issues/9811).

### Steps to reproduce the behavior

```
$ docker run hello-world
docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.
ERRO[0000] error waiting for container: context canceled
```

### Workaround/Solution

```sh
file='/etc/runit/core-services/02-docker-systemd.sh'
if [ ! -e "$file" ] || ! grep 'cgroup/systemd' '/etc/fstab' >/dev/null; then
	cat <<-EOF > "$file"
		msg "Creating systemd cgroup mountpoint for docker ..."
		mkdir -p /sys/fs/cgroup/systemd
		grep "/sys/fs/cgroup/systemd" /etc/fstab >/dev/null \
			|| echo 'cgroup /sys/fs/cgroup/systemd cgroup none,name=systemd 0 0' \
			>> /etc/fstab
	EOF
	sh "$file"
	mount -a
fi
```

**Comment by kh4ydn** [comment]
I figure the culprit is cgmanager.  After I do `sudo rm /var/service/cgmanager` and reboot, docker works for me.
I've enabled cgmanager recently and it broke docker

**Comment by CameronNemo** [comment]
@kh4ydn what pulls in cgmanager for you? or why are you using it? I say this because cgmanager is in maintenance mode and pretty much a dead project. cgroups2 wasn't as bad as they thought it might be.

**Comment by kh4ydn** [comment]
@CameronNemo cgmanager was pulled in as I followed this wiki to set up pulseaudio https://wiki.voidlinux.eu/PulseAudio
I figured I don't really need cgmanager.

**Comment by go2null** [comment]
on my system
```
$ xbps-query -X cgmanager
ConsoleKit2-1.2.1_2
$ xbps-query -X ConsoleKit2
lxdm-0.5.3_3
xfce4-4.12.0_7
```
