### ISSUE TITLE
wpa_supplicant 2.7 update breaks WPA2 Enterprise network

### ISSUE THREAD

**Issue by svenper** [void-linux/void-packages#5413]
### System

* xuname:  
  Void 4.14.85_1 x86_64-musl GenuineIntel notuptodate hold rDFFFFFF
* package:  
  wpa_supplicant-2.7_1

### Expected behavior

wpa_supplicant connects to WPA2 Enterprise networks like it did in 2.6_12.

### Actual behavior

WPA2 Personal network functions but not WPA2 Enterprise.

[syslog for WPA2 Enterprise for both versions of wpa_supplicant](https://gist.githubusercontent.com/svenper/a79c350b52d9c5941a4cf49f5fa595b0/raw/ff3d9307f55c526882a1e791dbd022c34dfd39f2/wpa_supplicant%25202.7)

### Steps to reproduce the behavior

Install the new version and restart the network kernel module and wpa_supplicant service.

```
ping -c 1 8.8.8.8
```

Install the old version and do the same.

### Speculation

Some patches were removed in the update. Are all of them unnecessary now?

**Comment by maxice8** [comment]
> Some patches were removed in the update. Are all of them unnecessary now?

all patches remove didn't apply anymore, i think all but one were from the KRACK vulnerability
