### ISSUE TITLE
Bash completions in /etc/bash_completion.d/

### ISSUE THREAD

**Issue by chneukirchen** [void-linux/void-packages#5463]
These packages have bash completions in /etc, they should go to
/usr/share/bash-completion/completions instead:

- [x] MEGAcmd-1.0.0_3
- [x] darcs-2.14.1_2
- [x] icinga2-2.9.2_3
- [x] ldc-1.11.0_1
- [x] opensc-0.19.0_2
- [x] quilt-0.65_2
- [x] trace-cmd-2.7_1
- [x] uftrace-0.9.1_1

**Comment by CameronNemo** [comment]
https://github.com/ldc-developers/ldc/blob/master/CMakeLists.txt#L893

**Comment by CameronNemo** [comment]
Yeah that was done recently. Thanks Leah.

**Comment by ndowens** [comment]
@CameronNemo MEGAcmd may be in wrong location(/usr/share/bash-completions/completions); all the other bash-completions seem to be in /usr/share/bash-completion/completions
