### ISSUE TITLE
KiCAD simulation with ngspice

### ISSUE THREAD

**Issue by the-wrench99** [void-linux/void-packages#5513]
### System

* xuname:  
  Void 4.19.6_1 x86_64 GenuineIntel notuptodate F
* packages:  
  * kicad-5.0.1_3
  * ngspice-28_2

### Expected behavior
KiCAD expects libngspice to be named libngspice.so when using the "simulate" feature in eeschema, produces an error message and SEGFAULTs.

### Actual behavior
Ngspice does not provide a file named libngspice.so, but only provides libngspice.so.0 and libngspice.so.0.0.0 in /usr/lib/

### Steps to reproduce the behavior
* open EEschema
* click on "Simulator" under the Tools tab in the menu bar
* error message `libngspice.so: cannot open shared object file: No such file or directory` shows up
* acknowledge error message by clicking "ok" button
* second error message `Missing ngspice shared library` opens up
* acknowledge again by clicking "ok" button
* EEschema crashes

Workaround: symlink libngspice.so.0.0.0 to libngspice.so

**Comment by maxice8** [comment]
Kicad is broken if it relies on /usr/lib/libngspice.so, the .so symlink is there only for linking.

The correct approach is make it use `libngspice.so.0`

[Debian fix](https://sources.debian.org/data/main/k/kicad/5.0.1+dfsg1-3/debian/patches/fixes/Use-fixed-version-for-libngspice.so.0.patch)
