### ISSUE TITLE
Package Request: ttf-linux-libertine

### ISSUE THREAD

**Issue by hemerno** [void-linux/void-packages#5554]
Widely used serif font.

[Website](www.linuxlibertine.org)
[SourceForge](https://sourceforge.net/projects/linuxlibertine/)
[Wikipedia](https://en.wikipedia.org/wiki/Linux_Libertine)

License: GPL / OFL
Format: OpenType(.otf) and TrueType(.ttf)
Repositories: [Arch](https://www.archlinux.org/packages/extra/any/ttf-linux-libertine/), [Debian](https://packages.debian.org/stretch/fonts-linuxlibertine), [Ubuntu](https://packages.ubuntu.com/bionic/fonts-linuxlibertine)

**Comment by Chocimier** [comment]
Included in `libreoffice-fonts`

**Comment by hemerno** [comment]
> Included in `libreoffice-fonts`

"Linux Libertine G" is included in there. This "G" is important for websites. For example Wikipedia uses "Linux Libertine" for headings by default. 
![voidlibertine](https://user-images.githubusercontent.com/31391652/49691194-008c0f80-fb4e-11e8-9747-856ca4a6881e.png)
