### ISSUE TITLE
Package request: libsynctex(-devel)

### ISSUE THREAD

**Issue by xaltsc** [void-linux/void-packages#5602]
Providing this package would likely require to rethink how Void offers LaTeX, but it's such a pain somewhere in your body to work on >100 without having  backward and forward search on your favourite pdf reader...

References:
[1] https://github.com/voidlinux/void-packages/issues/7022
[2] @svenper has a nice template here: https://gitlab.com/svenper/home-bin/tree/master/patches/templates, but I couldn't manage to build it.
[3] Rémy Oudompheng has a pretty straightforward PKGBUILD on the AUR (https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/texlive-bin) but again to change the way VoidLinux offers TexLive.

**Comment by svenper** [comment]
I have not pushed the templates recently, but now they are updated ([`705b7db`](https://gitlab.com/svenper/home-bin/commit/705b7db760116fdbf413090b2f4646d31daf01a0)).

There are [errors building dvisvgm](https://github.com/mgieseki/dvisvgm/issues/98) currently. This can be worked around by not using the system Ghostscript library, i.e. removing these lines from the *-exec template:
```
configure_args+=" --with-system-libgs"      ; makedepends+=" ghostscript-devel"
:                                           ; makedepends+=" ghostscript"
```

asymptote requires disabling gc in the same way, removing this line:
```
_asymptote_args+=" --enable-gc=system"      ; makedepends+=" gc-devel"
```

Keeping the hundreds of texlive programs in sync with system shared libraries is a challenge, especially with the frequent poppler updates breaking things. I working on adding build options to disable some programs, which is rather flexible with the various --disable-*$program* options to the configure script, which could reduce library dependencies (e.g. [luatex no longer needs poppler](https://github.com/TeX-Live/texlive-source/commit/9d318e98af3abcdb61d0f2eef0aba507770457bc#diff-00d67a073569e40cdb02e68defaa78d2L53)).

**Comment by svenper** [comment]
Thought I might offer a progress update. Since TeX Live started offering musl binaries and maintaining several poppler versions, fewer issues sneak through, which is encouraging!

At this point in time on musl, [my templates @7820d75](https://github.com/svenper/void-packages/commit/7820d75b22a94986749609e4a02a24121b8c6864) can build every single package offered with TeX Live, using all of the main system shared libraries, including gs and gd. Only dvisvgm uses some explicit libraries in addition to those that appear to be modified from their external sources.

Considering whether I should start a pull request for suggestions.

**Comment by stuart-little** [comment]
For what it's worth, this came up in the [now 404'd](https://github.com/voidlinux/void-packages/issues/7022) original GitHub discussion: there are ways around this headache short of templating. 

What worked for me with the latest [zathura](https://github.com/pwmt/zathura) (namely 0.4.4) was the following procedure:

- got the latest libsynctex [arch package](https://www.archlinux.org/packages/extra/x86_64/libsynctex/)
- untarred it and populated the respective directories as shown in the corresponding [file list](https://www.archlinux.org/packages/extra/x86_64/libsynctex/files/)

That was pretty much it, as far as steps specific to `synctex` go. I then cloned the `zathura` repo, built and installed to a local directory `dir`, say. The `zathura` build system saw the `libsynctex` libraries and built in the `synctex` support as expected. 

I then made an xbps package out of the local installation directory with 

```
# xbps-create -n "zathura-0.4.4_1" -s "document viewer" -A "x86_64" <dir>
```
This will create that package in your `/root/` folder, and you can then install it with 
```
# xdowngrade zathura-0.4.4_1.x86_64.xbps
```
This second part will differ depending on your pdf viewer, but in any case, the first half of this, pertaining to `libsynctex` itself, should work and be fairly easily scriptable.

**Comment by xtraeme** [comment]
Rofl nice 👌

**Comment by stuart-little** [comment]
And actually, there's no reason why you wouldn't make your own `xbps` package out of the arch `libsynctex` binary too, for easier package management. I tried it just now:

Once you untar [the archive](https://www.archlinux.org/packages/extra/x86_64/libsynctex/) to some `<dir>` just run
```
# xbps-create -n libsynctex-2019.51075_1 -s "libsynctex" -A x86_64 <dir>
```
and then install the resulting package with `xdowngrade`, as in the [previous post](https://github.com/void-linux/void-packages/issues/5602#issuecomment-542799893).

**Comment by xtraeme** [comment]
👌

**Comment by l4s8g** [comment]
> And actually, there's no reason why you wouldn't make your own `xbps` package out of the arch `libsynctex` binary too, for easier package management. I tried it just now:
> 
> Once you untar [the archive](https://www.archlinux.org/packages/extra/x86_64/libsynctex/) to some `<dir>` (so the directory tree structure is `<dir>/usr/...`) just run
> 
> ```
> # xbps-create -n libsynctex-2019.51075_1 -s "libsynctex" -A x86_64 <dir>
> ```
> 
> and then install the resulting package with `xdowngrade`, as in the [previous post](https://github.com/void-linux/void-packages/issues/5602#issuecomment-542799893).

I installed libsynctex like you described, then changed the "configure_args" line in the template of zathura to `"-Dsynctex=enabled -Dtest=disabled"`. I also tried to add `libsynctex` to the hostmakedepends or makedepends. I'm getting the following error:
`=> ERROR: zathura-0.4.5_1: target dependency 'libsynctex' does not exist!`

**Comment by stuart-little** [comment]
I wouldn't know what that's about: I am building `zathura` from source too (not through void's template system).

This means I cloned the `zathura` [repo](https://github.com/pwmt/zathura) and followed the build instructions in the `README` therein.

This has worked for me for a long time. In fact, I just built the latest `0.4.5` days ago. I can get back with a precise list of all of the steps I'm taking if you like, but again, this won't be via `void` templating.

**Comment by l4s8g** [comment]
Thank you, i 'd like to take you up on your offer. 
The meson build output currently looks like this:
![image](https://user-images.githubusercontent.com/26022993/72221652-eac0f900-355c-11ea-9ff2-71428262d8f5.png)
From my understanding it looks fine, only libsynctex is missing. As already mentioned, i installed it using xdowngrade. 
`xbps-query libsnctex`-output:
![image](https://user-images.githubusercontent.com/26022993/72221807-4475f300-355e-11ea-8e7c-e5659c5c21be.png)
Thank you for your time.

**Comment by stuart-little** [comment]
Hmm.. OK, so you have `pkg-config`, which in turn the `meson` build system will use to look for dependencies. Can you find the `pkg-config` file for `libsynctex`? Try something like

```
find /usr/ -name *.pc |grep synctex
```
What does that return? For me it finds 

```
/usr/lib/pkgconfig/synctex.pc
```

I have checked that if I move that file out of the way temporarily, then running

```
meson --prefix /usr build
```
in the root folder of the `zathura` repo will fail to find `synctex`, just as in your case. If I move it back that command *will* find it.

**Comment by l4s8g** [comment]
Interestingly `find /usr/ -name "*.pc" | grep synctex` returns
/usr/lib/pkgconfig/synctex.pc

**Comment by stuart-little** [comment]
I'm a bit stumped, but perhaps the `prefix` option might have something to do with it?

I notice your package-finding executables (`cmake`, `pkg-config`) are directly in `/bin/`. For me they're in `/usr/bin/`.

Maybe run 

```
meson --prefix /usr build
```
specifying the `prefix`?

On my system `/bin/` is a symlink to `/usr/bin/`, but the `meson` system actually resolves the path to `pkg-config` to the full `/usr`-prefixed directory, so there's clearly some such difference between our two systems..

**Comment by stuart-little** [comment]
I've also just tried this:

- moved 'synctex.pc' to some random directory I made up (say '/boo');

- set the `PKG_CONFIG_PATH` environment variable to that directory:

```
export PKG_CONFIG_PATH=/boo
```

- ran the `meson` command as before:

```
meson --prefix /usr build
```
It find `synctex`! So you can add directories to whatever search path is already built into `meson` for `pkg-config`. In your case maybe try something like

```
export PKG_CONFIG_PATH=/usr/lib/pkgconfig
```
before running the `meson` command.

**Comment by xtraeme** [comment]
Right, but pkgconfig files should always go to `/usr/lib/pkgconfig/`

**Comment by stuart-little** [comment]
Certainly, but in this case that file is not found for some reason. I'm grasping at straws anyway, so was just suggesting something concrete to try.

**Comment by stuart-little** [comment]
So this might be barking up the wrong tree, but here's what I suspect happened.

The fact that `meson` locates executables in `/bin/` rather than `/usr/bin/` makes me think that perhaps on this system (`musl` vs. `glibc`?) these are built with `--prefix=""` instead of `--prefix=/usr`.

This would apply to `pkg-config`, which would then presumably be configured to search `/lib/` but not `/usr/lib`. Similarly, all other packages would install their respective `*.pc` files to `/lib/pkgconfig` instead of `/usr/lib/pkgconfig`.

This custom-made `synctex` package borrowed from `arch`, though, installs *its* `*.pc` file in `/usr/lib/pkgconfig`, where the system's `pkg-config` doesn't know to look for it.

For that reason, you might want to help `pkg-config` out as suggested, by running 

```
export PKG_CONFIG_PATH=/usr/lib/pkgconfig
```
I may well be off-track, but we won't know until @l4s8g gives it a go.

**Comment by l4s8g** [comment]
Thank you guys, lots of permission issues, yet again. libsynctex.pc was not readable by group and others. I then installed zathura-pdf-mupdf using `sudo xbps-install zathura-pdf-mupdf`. Again, a folder had wrong permissions so i could not display the pdf files. I had to change permissions of the file /usr/local/lib/zathura/libpdf-mupdf.so and of the folder containing this file. Are these permission issues specific to my setup? I would be happy to investigate and help out to contribute something back.

**Comment by stuart-little** [comment]
Is it `libsynctex.pc` or just plain `synctex.pc`? It's the latter for me..

Does `meson` find it if you make it readable by everyone?

**Comment by l4s8g** [comment]
I'm sorry, i guess i wasn't clear in my last comment, i got zathura working with forward and backward search now., after changing the permissions of the files. These permission problems are really bugging me though and i haven't experienced anything like this before. That's why i asked if others also experience permission issues. 

> Is it libsynctex.pc or just plain synctex.pc? It's the latter for me..
-> synctex.pc
> All of my /usr/lib/*.pc files have 644 permissions, so are universally readable.
I have to set 644 permissions myself for new .pc files. Also for new folders.

**Comment by svenper** [comment]
Folders typically need exec permissions as well, e.g. 755 here

**Comment by fosslinux** [comment]
Provided by the new `texlive` package, can be closed.
