### ISSUE TITLE
Package Request: CalculiX

### ISSUE THREAD

**Issue by luzpaz** [void-linux/void-packages#5603]
Three-Dimensional Structural Finite Element Program

[Homepage](http://www.calculix.de)

Packages on other distros:
AUR: https://aur.archlinux.org/packages/calculix ([PKGbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=calculix))
FreeBSD: https://www.freshports.org/cad/calculix

**Comment by luzpaz** [comment]
someone please make this happen

**Comment by Phicem** [comment]
Hello,
I am currently trying to make a calculix package. It does seem to work for x86_64, but cannot yet be built for other architectures.
The code is available at: [https://github.com/Phicem/void-packages/releases/tag/calculix_wip_2022_08_03](https://github.com/Phicem/void-packages/releases/tag/calculix_wip_2022_08_03)

I'm waiting to fix cross-compiling issues before making a pull request. Any feedback about theses packages is most welcome.

**Comment by luzpaz** [comment]
Didn't look at the change but JFYI, v0.20 was just released http://www.dhondt.de/

**Comment by Phicem** [comment]
Thank you for pointing out the new version.

I updated the packages and made a pull request: https://github.com/void-linux/void-packages/pull/39984

**Comment by CtrlC-Root** [comment]
I would also want this especially to have it available in FreeCAD. I may circle back to this in a few weeks if no one else beats me to it. It looks like @Phicem 's pull request was pretty far along and close to being merged.
