### ISSUE TITLE
Update opencascade to 7.3

### ISSUE THREAD

**Issue by luzpaz** [void-linux/void-packages#5605]
Please update opencascade to [7.3.0](https://www.opencascade.com/content/latest-release)
 
https://github.com/void-linux/void-packages/tree/master/srcpkgs/occt  
https://github.com/void-linux/void-packages/blob/master/srcpkgs/occt-devel

**Comment by Hoshpak** [comment]
@Piraty

**Comment by maxice8** [comment]
Fixed update check

**Comment by Piraty** [comment]
https://github.com/void-linux/void-packages/pull/1215
