### ISSUE TITLE
Suggestion: monit → change default monitrc location

### ISSUE THREAD

**Issue by Ypnose** [void-linux/void-packages#5640]
Hi there folks,

On Void, the default ```monitrc``` location is inside ```/etc/monit/```. By default, ```monit``` use ```/etc/monitrc``` after ```~/.monitrc```. It coud be a good idea to keep it as upstream.

If one wants to use ```/etc/monit/``` directory, it is possible to do it with ```include /etc/monit.d/*``` inside ```monitrc```.

Sincerely

**Comment by Ypnose** [comment]
Thanks to you, guys! :beers:

**Comment by maxice8** [comment]
it is done

**Comment by Ypnose** [comment]
Thanks @maxice8 :beers:
