### ISSUE TITLE
Version Bump: keepalived-2.0.5

### ISSUE THREAD

**Issue by ArmedAviator** [void-linux/void-packages#568]
keepalived-1.4 branch seems to be no longer maintained and all development and bug fixes go into 2.0 branch.  keepalived-2.0 was released in May of this year and is receiving regular updates.  If 2.0 is still too new for the repo maintainers to consider it stable, please update keepalived to 1.4.5.

**Comment by CameronNemo** [comment]
Is there any potential for breakage? Why did they bump the version to 2.0? Any incompatibilities or major behavior changes? From a quick survey, Debian is still on 1.3.9 for their unstable branch (lol), Arch is on the 2.0 branch, and gentoo is [more complicated](https://packages.gentoo.org/packages/sys-cluster/keepalived).
