### ISSUE TITLE
tracking: libglvnd support

### ISSUE THREAD

**Issue by maxice8** [void-linux/void-packages#578]
Implementation: https://github.com/maxice8/UnlimitedPullRequestWorks/tree/libglvnd

Needs to fix crashes on musl libc: 
```
bash-4.4$ mpv --hwdec=vaapi --vo=opengl https://www.youtube.com/watch?v=wCrBLe3CB7s
Playing: https://www.youtube.com/watch?v=wCrBLe3CB7s
 (+) Video --vid=1 (*) (vp9 1280x720 30.000fps)
 (+) Audio --aid=1 --alang=eng (*) 'DASH audio' (opus 2ch 48000Hz) (external)
[vo/opengl] GLX not found.
[vo/opengl] GLX not found.
[vo/opengl] GLX not found.
[vo/opengl] Could not initialize EGL.
[vo/opengl] GLX not found.
[vo/opengl/wayland] failed to connect to a wayland server: check if a wayland compositor is running
[vo/opengl] VT_GETMODE failed: Not a tty
[vo/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
i965_dri.so does not support the 0xffffffff PCI ID.
[vo/opengl] Failed to get EGL display.
[vo/opengl] Failed to setup EGL.
[vo/opengl] 'drm-egl' is deprecated, use 'drm' instead.
[vo/opengl] Can't handle VT release - signal already used
[vo/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
i965_dri.so does not support the 0xffffffff PCI ID.
[vo/opengl] Failed to get EGL display.
[vo/opengl] Failed to setup EGL.
Failed to open VDPAU backend Error loading shared library libvdpau_va_gl.so: No such file or directory
[vo/opengl] Error when calling vdp_device_create_x11: 1
Error opening/initializing the selected video_out (--vo) device.
Video: no video


Exiting... (Errors when loading file)
bash-4.4$ 
```

**Comment by maxice8** [comment]
cc parties of interest @Johnnynator @Gottox

**Comment by Johnnynator** [comment]
@maxice8 Shouldn't it be possible to make libglvnd a meta package on musl that depends on libGL? This way we could circumvent the shlibs problem.

**Comment by maxice8** [comment]
On Thu, Jul 19, 2018 at 03:55:04PM -0700, John Zimmermann wrote:
> @maxice8 Shouldn't it be possible to make libglvnd a meta package on musl that depends on libGL? This way we could circumvent the shlibs problem.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/578#issuecomment-406438759

take with a grain of salt i only tought about your suggestion for 3 minutes

could work

**Comment by maxice8** [comment]
I got no interest in this, i use glibc and Intel GPU.

someone else can do it.

**Comment by MagicRB** [comment]
I am sorry, for re-opening this rather old issue in advance, but I really think that this should be solved, I'm not familiar with the musl issue you've described, but i think that a special nvidia-optimus package which installs all the libs without overwriting any Intel libs, while providing a simple switch script could work. I don't know if this is a acceptable solution, but it's solution...
