### ISSUE TITLE
Package Request: pharos-cluster

### ISSUE THREAD

**Issue by jcgruenhage** [void-linux/void-packages#5868]
It's a simple kubernetes cluster management and bootstrapping tool, licensed under the Apache 2 license.
https://github.com/kontena/pharos-cluster is the source.

**Comment by maxice8** [comment]
Written in ruby but not in Rubygems ? 

Makes it much harder for me to package with `tmplgen`

**Comment by jcgruenhage** [comment]
It does have a gemspec

**Comment by maxice8** [comment]
On Fri, Dec 14, 2018 at 11:40:29AM -0800, Jan Christian Grünhage wrote:
> It does have a gemspec
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/5868#issuecomment-447432885

I'd rather it be on rubygems since it can be automatically generated with tmplgen including the dependencies.

**Comment by maxice8** [comment]
On Tue, Dec 18, 2018 at 07:28:32AM -0800, Jan Christian Grünhage wrote:
> I've played around with it a bit more and with other kubernetes cluster management tools and came to the conclusion that I prefer Kubespray, so I'm not interested anymore. Should I keep this issue open anyway?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/5868#issuecomment-448259489

no
