### ISSUE TITLE
Package Request: Qomui

### ISSUE THREAD

**Issue by bless-9** [void-linux/void-packages#5912]
Qomui (Qt OpenVPN Management UI) is an easy-to-use OpenVPN/WireGuard gui for GNU/Linux with some unique features such as provider-independent support for double-hop connections. Qomui supports multiple providers with added convenience when using AirVPN, PIA, ProtonVPN, Windscribe or Mullvad.

github: https://github.com/corrad1nho/qomui

aur: https://aur.archlinux.org/packages/qomui/
Fedora, Debian, Ubuntu & OpenSuse:
https://software.opensuse.org//download.html?project=home%3Acorrad1nho&package=qomui

**Comment by youngjinpark20** [comment]
If nobody else is taking a stab at this I'll go ahead and try :)

**Comment by youngjinpark20** [comment]
https://github.com/void-linux/void-packages/pull/6648
