### ISSUE TITLE
Qt5-5.11.3 GLIBC kernels older than 4.11.0: error while loading shared libraries: libQt5Core.so.5:

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#5916]
### System

* xuname:  
  *Void 4.9.0-8-amd64 x86_64  uptodate F* (Debian Kernel, since chroot in Debian system)
* package:  
  *Qt5-5.11.3*

### Expected behavior
`libQt5Core.so.5` should be loadable.

### Actual behavior
`/usr/lib/qt5/bin/qdbusxml2cpp: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory`

### Steps to reproduce the behavior
Still to figure out Travis breaks reliably: e.g. https://www.travis-ci.com/Johnnynator/void-packages/jobs/165426726

**Comment by Johnnynator** [comment]
```
Displaying notes found in: .note.ABI-tag
  Owner                 Data size       Description
  GNU                  0x00000010       NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 4.11.0
```
ABI 4.11.0 does not sound good, Older kernel that still are in the repo should be supported

**Comment by Johnnynator** [comment]
```
#if QT_CONFIG(statx)
#  define MINLINUX_MAJOR        4
#  define MINLINUX_MINOR        11
#  define MINLINUX_PATCH        0
#elif QT_CONFIG(getentropy)
#  define MINLINUX_MAJOR        3
#  define MINLINUX_MINOR        17
#  define MINLINUX_PATCH        0
#elif QT_CONFIG(renameat2)
...
```
Disableing statx would lower the Minimum kernel version to 3.17.0

**Comment by pullmoll** [comment]
It seems we need to patch the statx detection then.
I see no file in qtbase/config.tests/* looking for statx so it probably is in qtbase/configure... but I don't see it :-P

**Comment by Johnnynator** [comment]
> FWIW it works for me, but I'm on kernel 4.19 anyway.
> 
> It seems we need to patch the statx detection to support old kernels. I see no file in qtbase/config.tests/* looking for statx so it probably is in qtbase/configure... but I don't see it :-P
> 
> Perhaps all that's needed is a `CONFIG -= statx` for the qmake call.
> 
> Or let's patch the lines with `4` and `11` to what we need. 3.16. is the lowest kernel version we have.
> But then old kernels won't have the statx syscall, no?

Older kernels don't have it. I'm currently trying to figure out how much of it still works after 
https://github.com/qt/qtbase/commit/b7887f9b4faad2227691a2af589e9d7680d6ae08
Also it is set in `qtbase/src/corelib/global/qconfig-bootstrapped.h`
