### ISSUE TITLE
qt5-devel broken on ARM?

### ISSUE THREAD

**Issue by Kistelini** [void-linux/void-packages#6038]
### System

* package:  
  qt5-devel-5.11.3_1

On x86_64 the content of `/usr/lib/cmake/Qt5Core/Qt5CoreConfigExtrasMkspecDir.cmake` is
`set(_qt5_corelib_extra_includes "${_qt5Core_install_prefix}/lib/qt5//mkspecs/linux-g++")`
 but on aarch64-musl it's
`set(_qt5_corelib_extra_includes "${_qt5Core_install_prefix}/../usr/lib/qt5//mkspecs/linux-g++")`.
This path is wrong and breaks the build of the unstable release of scribus on ARM: https://travis-ci.org/void-linux/void-packages/jobs/470413822
If I change it manually the build works. I don't understand where this difference comes from.

**Comment by Cogitri** [comment]
Ah, also encountered that, but it happens due to not/wrongly setting QTROOT usually. Please try setting it like this: https://github.com/void-linux/void-packages/blob/master/srcpkgs/plex-media-player/template#L8

**Comment by Kistelini** [comment]
Scribus doesn't use a QTROOT variable. Wouldn't it be better to fix qt5-devel than do work-arounds in packages that depend on it?

**Comment by Johnnynator** [comment]
../use/lib ist the same as just lib. The problem is that `_qt5Core_install_prefix` is set wrongly.

**Comment by Kistelini** [comment]
No, `/a/../b` would become `/b`.

**Comment by Johnnynator** [comment]
the lib folder is always in a usr directory, so `../usr/lib` is `lib` in these cases.

**Comment by Kistelini** [comment]
No, folder structure works from left to right. `usr/../lib` would get `lib`.

**Comment by Johnnynator** [comment]
> No, folder structure works from left to right. `usr/../lib` would get `lib`.

Yes `../usr/lib` is not equal to `lib`, I just wanted to say that `_qt5Core_install_prefix` should normally end with `usr` so it doesn't make a difference if you add `lib` or `../usr/lib`. The problem seems to be that in you case that `_qt5Core_install_prefix` is `${XBPS_CROSS_BASE}` and not `${XBPS_CROSS_BASE}/usr` which it ideally should be.

**Comment by Kistelini** [comment]
Issue seems to be in scribus, not this package.
