### ISSUE TITLE
Package Request: Radarr

### ISSUE THREAD

**Issue by anarchomoh** [void-linux/void-packages#6073]
The website is: https://radarr.video/
The Github link is: https://github.com/Radarr/Radarr
Thanks!

**Comment by Cogitri** [comment]
I'm curious as to why you want both Sonarr and Radarr included in the Void repos?

**Comment by DirectorX** [comment]
I strongly recommend using these software inside a docker container.

**Comment by Ingvix** [comment]
> I strongly recommend using these software inside a docker container.

Why though?
