### ISSUE TITLE
Packge Fix: Add "server" to taskd

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#6074]
### System

* xuname:  
Void 4.19.5_1 x86_64 GenuineIntel notuptodate rF
* package:  
taskd-1.1.0_3

### Expected behavior
`sv start taskd` should run the task server

### Actual behavior
Nothing happens, service starts to fail

### Steps to reproduce the behavior
`sv start taskd`

### Fix for this issue
Replace the line https://github.com/void-linux/void-packages/blob/4a00d41d3d4757f443b56899010f420f718a4672/srcpkgs/taskd/files/taskd/run#L6 with `exec chpst -u ${TASKDUSER} taskd server --data ${TASKDDATA}`

**Comment by ndowens** [comment]
Taking a look

**Comment by ndowens** [comment]
The problem is the data dir, if I change it to a different dir I made, it works with adding server
