### ISSUE TITLE
Package Request: GNUnet

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#6084]
Name: GNUnet
Publisher: GNU
Upstream: https://gnunet.org/
Download: https://gnunet.org/downloads

> GNUnet is an alternative network stack for building secure, decentralized and privacy-preserving distributed applications. Our goal is to replace the old insecure Internet protocol stack. Starting from an application for secure publication of files, it has grown to include all kinds of basic protocol components and applications towards the creation of a GNU internet.

**Comment by ndowens** [comment]
Working on this, may take a little while to have it ready

**Comment by 0x0f0f0f** [comment]
I would love to try it too but I couldn't get it to build correctly on a 64 bit musl system. Has anybody built it on void?

**Comment by Anachron** [comment]
I'm packaging it for Void Linux right now.

**Comment by Anachron** [comment]
The PR https://github.com/void-linux/void-packages/pull/13167 is open now.

**Comment by Anachron** [comment]
PR is already merged.
