### ISSUE TITLE
[FTBFS] stack for glibc

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#6100]
For glibc stack fails to build due to what looks like a missing `#include <sys/sysmacros.h>` somewhere:
```
[ 44 of 125] Compiling Stack.Constants  ( src/Stack/Constants.hs, dist/build/Stack/Constants.o )
<command line>: can't load .so/.DLL for: /builddir/stack-1.7.1/.cabal-sandbox/lib/i386-linux-ghc-8.4.4/libHSunix-compat-0.5.0.1-7wHKrmu7kXH9utvYTrCCyN-ghc8.4.4.so (/builddir/stack-1.7.1/.cabal-sandbox/lib/i386-linux-ghc-8.4.4/libHSunix-compat-0.5.0.1-7wHKrmu7kXH9utvYTrCCyN-ghc8.4.4.so: undefined symbol: major)
=> ERROR: stack-1.7.1_1: do_build: 'cabal build ${makejobs}' exited with 1
```
It seems that a missing definition for the macro `major` leads to `gcc` or `g++` assuming an external function `int major(...)`, which of course does not exist.

**Comment by maxice8** [comment]
needs to add sys/sysmacros.h in any files that make use of `major` `minor` and `makedev`

**Comment by maxice8** [comment]
common problem that appeared on glibc >= 2.28

**Comment by pullmoll** [comment]
Yeah, I just don't know which package actually needs a patch. Is it ghc or is it stack?
I'll leave that to the maintainers... recently I'm becoming lazy like hell :)

**Comment by ericonr** [comment]
Stack has been buildable recently.
