### ISSUE TITLE
small patch for nginx template

### ISSUE THREAD

**Issue by wes1138** [void-linux/void-packages#6136]
I don't think there is a `--without-http_geoip_module` option, so `vopt_if`
should be used instead of `vopt_with` in the template:

    @@ -68,7 +68,7 @@ do_configure() {
             --with-http_realip_module \
             --with-http_ssl_module \
             --with-http_stub_status_module \
    -        $(vopt_with geoip http_geoip_module)
    +        $(vopt_if geoip --with-http_geoip_module)

(Note: there *is* a `--without-http_geo_module`, but that is for a different
feature.)

**Comment by maxice8** [comment]
Please submit a PR if you want credit

**Comment by wes1138** [comment]
I don't need credit, but I would be honored to be a part of the project.  I'll make a PR.
