### ISSUE TITLE
Package Request: n30f

### ISSUE THREAD

**Issue by snarkyllama** [void-linux/void-packages#6156]
`n30f is a quick hack to display a png in a borderless and transparent non-wm-managed window`

github repo: https://github.com/sdhand/n30f

**Comment by maxice8** [comment]
remove good first issue label due to being taken

**Comment by bobertlo** [comment]
Closed by https://github.com/void-linux/void-packages/pull/6300/commits/2f9a3e1c085e4abff8c7e99c7f6955f6a5480ef7
