### ISSUE TITLE
chromium/widevine broken for Netflix

### ISSUE THREAD

**Issue by acobaugh** [void-linux/void-packages#6164]
### System

* xuname:  
`Void 4.19.8_1 x86_64 GenuineIntel notuptodate rrDDFFF`

* package:  
chromium and chromium-widevine 70.0.3538.110_1 <- WORKING
chromium and chromium-widevine 71.0.3578.98_1 <- NOT WORKING

### Expected behavior

widevine should work

### Actual behavior

widevine does not appear to work. Netflix shows an error indicating the widevine cdm was not found. Additionally, lsof does not show that chromium has loaded `libwidevinecdm.so`

### Steps to reproduce the behavior

Install chromium(-widevine)-71.0.3578.98_1. Start chromium and attempt to use Netflix. Also observe that lsof is not showing libwidevinecdm.so being loaded. 

Something broke between these two versions. I did see that there were changes to the widevine patches, but I haven't had a chance to dig into this to see if this is the cause, or if chromium 71 is just broken.

**Comment by Cogitri** [comment]
Hum, is there any website where I can test this without a paid account?

**Comment by acobaugh** [comment]
Hmm, this might work. Works in the downgraded chromium I'm running right now: https://bitmovin.com/demos/drm

**Comment by Cogitri** [comment]
Thanks, will test tomorrow.

**Comment by Cogitri** [comment]
#6207 should fix this. I doubt that it's going to be merged now though - a new chromium version will be published soon and merging LLVM7 should be more important than building chromium again. If you want to I can build it myself though, or you could just use google-chrome for now.

**Comment by Cogitri** [comment]
> Looks like it needs the cdm

Which is provided by chromium-widevine

**Comment by Cogitri** [comment]
FWIW, Widevine works just fine for me with chromium-71.0.3578.98_2 and chromium-widevine-71.0.3578.98_1


![screenshot from 2018-12-31 14-56-41](https://user-images.githubusercontent.com/8766773/50561576-5fd3de80-0d0c-11e9-95d3-613b9a6cdcc4.png)

**Comment by JohnHolmesII** [comment]
There must be some error. I think that having both packages installed is causing some false positives. I just cleared every cache/config folder for chromium i could find and reinstalled chromium and neither that demo nor Netflix is able to find widevine. I think that since chromium uses so many different folders, both are able to use widevine by reading from the same folder.

And FWIW, I'm on musl repos, and chromium-widevine is not available in a repo and is not buildable, though perhaps that should be a separate issue.

**Comment by Cogitri** [comment]
Ah, widevine won't ever work on musl due to it being proprietary and only built for glibc by Google.
