### ISSUE TITLE
ddclient service keeps respawning

### ISSUE THREAD

**Issue by sineemore** [void-linux/void-packages#6170]
ddclient is started from `run` with `-foreground` option which prevents it from forking. But without the `-daemon` option ddclient exits shortly after success and keeps respawning once a second.

In my local setup I've used `use=cmd, cmd=wget ...` setting in /etc/ddclient/ddclient.conf to query my external IP address. So `wget` was executed roughly once per second.

My point here is that `run` should have `-daemon` option with some sane default to keep ddclient actually running and prevent its respawning.

**Comment by CameronNemo** [comment]
I have looked into this and I believe your ddclient configuration is incomplete. I have added the line `daemon=5m` to my config and the ddclient behaves as a daemon. Since the interval should be user configurable, I am not sure adding the daemon option in run is the best idea.

Thoughts?

**Comment by sineemore** [comment]
The runit service won't behave like a normal daemon until that option is added.

Maybe we should provide a basic config with `daemon=5m`, a relevant comment and leave the service file as is?

Also it is possible to have a separate conf file in service directory to specify daemon option interval, similar to wpa_supplicant service.

I guess ddclient should have separate `interval` and `daemon` options, but this belongs to upstream.
