### ISSUE TITLE
sh: 1: clear: not found

### ISSUE THREAD

**Issue by am11** [void-linux/void-packages#6199]
### System

* xuname:  
  *Void 4.9.125-linuxkit x86_64-musl GenuineIntel/HyperV notuptodate F*
* package:  
  *sh* (Bourne Again Shell)

### Expected behavior
`clear` command is available.

### Actual behavior
`clear` command is not available.

### Steps to reproduce the behavior
In Windows 10 with docker, use `docker run -it voidlinux/voidlinux-musl /bin/sh` to enter the official Void docker, followed by:

```sh
# try `clear` command
clear

# results in:
#=>  sh: 1: clear: not found
```

**Comment by Hoshpak** [comment]
`/usr/bin/clear` is provided by the `ncurses` package which is a dependency of `base-voidstrap` so it should be there. Can you confirm that the package is missing from your container? Is `base-voidstrap` installed?

**Comment by am11** [comment]
Thanks! There was only ncurses-libs package installed:

```sh
xbps-query -l | grep ncurses
ii ncurses-libs-6.1_2          A System V Release 4.0 curses emulation library -- shared libraries
```

With `xbps-install ncurses` it installed `clear` command (along with `ncurses-base` package).

**Comment by am11** [comment]
@Hoshpak, a slightly related issue I encountered in bash. If i press up arrow (alt code 24) in shell, it shows the command from history (as expected). However, when I press multiple times, it appends to the text of previously rendered command (does not clear the row):

```sh
# run following commands in order:
pwd
ls
cd
touch

# press Up arrow
touch
# press Up arrow again
touchcd
# press Up arrow again
touchcd ls
# press Up arrow again
touchcd lspwd
```

![image](https://user-images.githubusercontent.com/3840695/50426693-5de9c580-089d-11e9-88e7-45b7f8d4f65b.png)


Do you know which component is missing from base chroot that could be installed to make bash work normally?
