### ISSUE TITLE
bug: glib 2.58.2 - (chroot) sandfox - palemoon browser

### ISSUE THREAD

**Issue by biopsin** [void-linux/void-packages#6228]
### System
No issue running palemoon outside chroot

* xuname:  
  Void  4.9.147_1 x86_64 GenuineIntel
* package:  
  custom PaleMoon 2.8.2.2 in chroot ( sandfox )

### Expected behavior
preference -> General -> Download: Set file to -> browse ( any directory )

### Actual behavior
preference -> ... -> Set file to -> browse ( any directory ) -> open

(pale moon:30708): GLib-GIO-CRITICAL **: 14:53:35.855: g_unix_is_system_fs_type: assertion 'fs_type != NULL && *fs_type != '\0'' failed
(pale moon:30708): GLib-GIO-CRITICAL **: 14:53:35.856: g_unix_is_system_device_path: assertion 'device_path != NULL && *device_path != '\0'' failed

### Steps to reproduce the behavior
Run PaleMoon in sandfox and change download directory in GUI -> crash

Tested: working ok with glib 2.57.3, 2.58.1 and 2.59.0

**Comment by maxice8** [comment]
Does this affect any of the web browsers we ship ?

**Comment by maxice8** [comment]
Please re-open in case this can be reproduced with any browser we ship
