### ISSUE TITLE
KDE/QT5 dependencies

### ISSUE THREAD

**Issue by dezifit** [void-linux/void-packages#6286]
### System

* uname:  
  Linux void 4.19.12_1 x86_64
* package:  
  kde5 -> qt5_tools -> clang

### Expected behavior
  It should be possible to install a base KDE/QT5 system without forced dependeny to QT5 designer and clang compiler

### Actual behavior
  qt5-tools contains QT5 designer (with dependency to clang) as well as libQt5Help.so, which is required by the kde5 base system.

### Steps to reproduce the behavior
  Try to install a minimal KDE5 desktop without QT designer or clang.
  xbps-query -X qt5-tools

**Comment by maxice8** [comment]
@pullmoll

**Comment by pullmoll** [comment]
KDE is nothing I know much about and thus can't tell whether or why the dependency of kde5 on qt5-tools is required. Fwd @Johnnynator
