### ISSUE TITLE
Building Emacs with ImageMagick support

### ISSUE THREAD

**Issue by emacsomancer** [void-linux/void-packages#6383]
### System

* xuname:  
  *Void 4.19.12_1 x86_64 GenuineIntel uptodate FFFFFFFF*
* package:  
  *emacs 26.1.5*

### Expected behavior
Building Emacs with e.g. `./xbps-src -o imagemagick pkg emacs-x11` followed by `xi emacs-x11` should install a version of Emacs that can resize images via ImageMagick.
### Actual behavior
Emacs still claims it needs ImageMagick support to resize images.
### Steps to reproduce the behavior
git clone the void-packages repo, install the bootstrap via ` ./xbps-src binary-bootstrap`, and then try to build emacs with `./xbps-src -o imagemagick pkg emacs-x11` followed by `xi emacs-x11`. Similar results occur if `emacs-x11` is substituted by `emacs-gtk3`. Similarly, even editing the template directly to make `imagemagick` a default option produces the same results.

**Comment by maxice8** [comment]
Tried changing to ImageMagick6 ?

```
Configured for 'x86_64-unknown-linux-gnu'.
  Does Emacs use imagemagick (version 6)?                 no
```

**Comment by emacsomancer** [comment]
You mean installing ImageMagick6 on my machine? It conflicts with ImageMagick(7). I certainly have Emacs with ImageMagick support working on other machines/distros without having ImageMagick6 installed.

**Comment by transitracer** [comment]
Okay, so I've been working on sorting out this same thing and I've gotten to the point where I can clear this up I think.

There are two problems here.

The first one, is that you need to install `libmagick6`, not `ImageMagick6`. `libmagick6` does not conflict.

The second one, is that changes to the package must be made to use `libmagick6-devel` instead of `libmagick-devel`

I'm futzing around with sorting the problem out now, I should be able to toss in a fix for the package soon.

**Comment by obunden** [comment]
Did you manage to fix the issue? Is it still relevant with up to date packages right now?

**Comment by emacsomancer** [comment]
This still remains an issue with 26.3. 

When 27 is released, it should cease to be an issue, as Emacs 27 can handle image manipulation internally, without needing Imagemagick.

**Comment by liketechnik** [comment]
Did somebody figure out the issue? I locally switched the dependency to `libmagick6(-devel)` and made sure the configure section contained 
```
Configured for 'x86_64-unknown-linux-gnu'.
  Does Emacs use imagemagick (version 6)?                 yes
```
Nevertheless emacs claims it wouldn't have imagemagick support.

**Comment by emacsomancer** [comment]
In the soon to be released version 27, Emacs won't need imagemagick any more to resize images &c., so probably the easiest thing is just to wait for the next version (which'll be along soon).

**Comment by ericonr** [comment]
Emacs 27.1 has been merged.

**Comment by ericonr** [comment]
However, the option is still there and might still be broken.

**Comment by ericonr** [comment]
emacs-gtk3 when built with `imagemagick` option ends up linked against libmagick, so I will consider this solved.

**Comment by AtomicNess123** [comment]
Is there somewhere explaining how to get/build Emacs with ImageMagick support for a newbie? Thanks.

**Comment by ericonr** [comment]
Follow the quick start guide (https://github.com/void-linux/void-packages#quick-start) but when building do `./xbps-src -o imagemagick pkg emacs`

**Comment by AtomicNess123** [comment]
Thanks so much. This won't affect my current Prelude configuation of emacs?
