### ISSUE TITLE
[TRACKING] XBPS_GCC_* usage

### ISSUE THREAD

**Issue by maxice8** [void-linux/void-packages#6406]
Packages that use XBPS_GCC_*

- [x] firebird
- [x] ruby
- [x] anjuta
- [x] brasero
- [x] codeblocks
- [x] espeak
- [x] irrlicht
- [x] libpagemaker
- [x] nautilus-sendto
- [x] openjdk
- [x] openssh
- [x] fbreader

**Comment by maxice8** [comment]
@Vaelatern can you handle `openjdk` ?
@pullmoll likewise for `firebird`

ruby will be fixed once #6201 is done, it just needs the vagrant people to update

**Comment by Vaelatern** [comment]
I will look at `openjdk`.

**Comment by maxice8** [comment]
only `openjdk` remains
