### ISSUE TITLE
Can't customize XMonad

### ISSUE THREAD

**Issue by non-Jedi** [void-linux/void-packages#6414]
### System

* xuname: Void 4.19.12_1 x86_64 GenuineIntel uptodate rrrmFFFFFF
* package: xmonad-0.15_1, xmonad-contrib-0.15_1

### Expected behavior

When below is in `~/.xmonad/xmonad.hs`, `xmonad --recompile` should give no output and successfully compile (https://hackage.haskell.org/package/xmonad-contrib-0.15/docs/XMonad-Doc-Configuring.html).

```haskell
   import XMonad

   main = xmonad $ def
       { borderWidth        = 2
       , terminal           = "urxvt"
       , normalBorderColor  = "#cccccc"
       , focusedBorderColor = "#cd8b00" }
```

Additionally, the `xmonad-contrib` package should have more files in it than just the license.

### Actual behavior

With haskell snippet above in `~/.xmonad/xmonad.hs`:

```
$ xmonad --recompile
XMonad will use ghc to recompile, because "/home/adam/.xmonad/build" does not exist.
Error detected while loading xmonad configuration file: /home/adam/.xmonad/xmonad.hs

xmonad.hs:1:1: error:
    Could not find module ‘XMonad’
    Use -v to see a list of the files searched for.
  |
1 | import XMonad
  | ^^^^^^^^^^^^^

Please check the file for errors.
```

And the files in xmonad-contrib are:

```
$ xbps-query -Rf xmonad-contrib
/usr/share/licenses/xmonad-contrib/LICENSE
```

Any ideas @xaltsc?

### Steps to reproduce the behavior

1. Install xmonad.
2. Create `~/.xmonad/xmonad.hs` with config shown above.
3. `xmonad --recompile`

**Comment by Dosprogs** [comment]
As a temporary fix you could install it from [source](https://github.com/xmonad/xmonad) (quick and easy) or use "cabal install xmonad && cabal install xmonad-contrib".

**Comment by obunden** [comment]
This is still a problem. xmonad-contrib builds the files but doesn't install anything expect the license file as non-Jedi reported. xmonad uses the stackage version from the package template, but xmonad-contrib takes that info from it's own stack.yaml file. Don't know if that can be relevant to the issue.

**Comment by Rex-Official** [comment]
Xmonad isn't reading its configuration file from .xmonad/xmonad.hs help.

**Comment by chilledfrogs** [comment]
I second this, facing the same issue, would like to switch back to XMonad and not have to deal with `cabal` for this (which still somehow doesn't actually seem to fix the issue at hand anyway, I tried)...

**Comment by jchook** [comment]
According to the [cabal docs](https://cabal.readthedocs.io/en/3.4/developing-packages.html#kinds-of-package-cabal-vs-ghc-vs-system)

> Library packages have to be registered with GHC for them to be available in GHCi or to be used when compiling other programs or packages.

> When you build and install a Cabal package containing a library then it gets registered with GHC automatically.

This automatic registration **does not happen** on Void, whether installed via XBPS or a `ghcup`.

Cabal silently fails to add libraries to the package database, even when I explicitly specify a package db. None of these works:

```sh
cabal install xmonad
cabal install --lib xmonad
cabal install --lib --user xmonad
cabal install --lib --global xmonad
cabal install --lib --package-db=user xmonad
cabal install --lib --package-db=$HOME/.local/share/ghcup/ghc/8.8.4/lib/ghc-8.8.4/package.conf.d xmonad
cabal install --lib --package-db=$HOME/.local/share/ghcup/ghc/8.8.4/lib/ghc-8.8.4/package.conf.d/package.cache xmonad
```

Setting `package-db` in `~/.cabal/config` has no effect. `ghc-pkg recache` did not help.

Following https://github.com/haskell/cabal/issues/6262#issuecomment-733919670, I successfully installed xmonad using `cabal v1-install xmonad`, and it properly registered in a new package known to `ghc-pkg list`. However the package installs "hidden" by default. `ghc-pkg expose xmonad` exposed it, but running `xmonad --recompile` still fails with all the same errors. *sigh*.

So far this seems like a cabal bug. It appears to silently fail to register with GHC.

- Void musl
- Linux 5.9.16
- x86_64
- GHC v8.8.4
- Cabal v3.2.0.0

**Comment by jchook** [comment]
For a temporary workaround until `xmonad-contrib` issue is fixed, I got it all to install via cabal with the following:

```sh
xbps-install -y xorg dmenu xmonad cabal-install libX11-devel libXinerama-devel libXext-devel libXrandr-devel libXScrnSaver-devel ncurses-libtinfo-devel pkg-config
cabal update
cabal install xmonad xmonad-contrib
```

**Comment by ericonr** [comment]
@xaltsc ?

**Comment by xaltsc** [comment]
I propose that either someone adopts the package or that it (and xmonad-contrib) be removed. I used to think that it worked, but this was my first package I think, I didn't do proper testing and I never managed to get it working.

**Comment by Chocimier** [comment]
xmonad got removed. Introducing it again with issues resolved, possibly by getting away with recompilation by making it restricted and asking to rebuild with `xbps-src` is still an option.

**Comment by riseekrthakur** [comment]
> The xmonad-contrib template seems to compile the package successfully, but it doesn't install the files.
> 
> Ideally it would be a simple fix for someone familiar with xbps-src.

I'd appreciate it if you elaborate a bit further. AFAIK void-src is used for foreign packages, right? I already attempted more than twice, and it's frustrating it won't work even implementing both methods cabal and stack. Although I'd tried on Fedora and it's work great but in Void Linux, I see some missing files.

**Comment by jchook** [comment]
@riseekrthakur `./xbps-src` is used to [build XBPS packages](https://github.com/void-linux/void-packages#quick-start).

I successfully installed xmonad and xmonad-contrib in Void Linux via cabal. See https://github.com/void-linux/void-packages/issues/6414#issuecomment-760591521

**Comment by riseekrthakur** [comment]
Installation is not a headache on my end either, the only problem I'm running into is that it won't create a build directory inside the ~/.config/xmonad and so on it complaining about "Could not find the module $NAMED" also a hard time in recompiling xmonad.
