### ISSUE TITLE
package request: guile 2.2

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [void-linux/void-packages#6418]
It looks void has guile 2.0.14 in repos. If it is not difficult, can someone add guile 2.2 maybe with the name guile22 or something. Thank you.

**Comment by bobertlo** [comment]
Would this be better updated in the main package, and possibly adding a guile2.0 if there is demand? A glance at the dependencies and it looks like they should work fine on 2.2.

**Comment by Cogitri** [comment]
Yeah, that's not a problem, some stuff has changed in the way guile is packaged though, could you test that if I provide you a PR @AlexanderKoshkarov?

**Comment by bobertlo** [comment]
Well, I have #6524 up. Waiting because `gc-8.0.2` breaks both guile-2.0 in tree and guile-2.2.4 cross compiling. This is about all I can do on this without a committer interested in fixing it.

**Comment by nihilismus** [comment]
Hi everyone.

What's the status of guile package in Void? Currently its package version is `2.0.14` (from **2017**) but `3.0.4` is [available in its website](https://www.gnu.org/software/guile/download/) (**2020**).

**Comment by flexibeast** [comment]
@nihilismus: Refer to #23056.

**Comment by logenkain** [comment]
We have guile-2.2.7 now.

Shouldn't we close this?

**Comment by ericonr** [comment]
Yup, thank you!
