### ISSUE TITLE
Removal procedure flaw

### ISSUE THREAD

**Issue by Chocimier** [void-linux/void-packages#6443]
In current removal procedure I find deceitful to remove programs from user system as revbump.
Can it be made more descriptive, e.g. by appending `removed` to version string?
That will make updates more reliable and give user possibility to delay system update unlit one find alternative for removed program.
That didn't strike me yet, but I would like to prevent such trouble.

**Comment by maxice8** [comment]
That breaks re-adding a package via a revbump (see touchegg).

**Comment by Chocimier** [comment]
`reverts=` can be used for re-adding then.

**Comment by the-maldridge** [comment]
Resolved by the passage of time.
