### ISSUE TITLE
dmd-bootstrap can't build most recent dmd anymore

### ISSUE THREAD

**Issue by yshui** [void-linux/void-packages#6550]
Maybe it is time to include dmd in distfiles?

**Comment by yshui** [comment]
@ndowens dmd-bootstrap itself builds, dmd-bootstrap _can_ build dmd-2.081 (the one in the repo). But this most recent version of dmd is 2.084, which dmd-bootstrap cannot build.

**Comment by ndowens** [comment]
I wonder if dmd-bootstrap has to be updated, before it can build a newer dmd?

**Comment by yshui** [comment]
@ndowens I already tried that. Doesn't work.

Maybe we can do a multiple stage bootstrap in the dmd package itself. It doesn't really take much time to build anyway.
