### ISSUE TITLE
Claws dependancies

### ISSUE THREAD

**Issue by ErinVoid** [void-linux/void-packages#6560]
### System

* xuname:  
Void 4.19.13_1 x86_64-musl AuthenticAMD uptodate rF
* package:  
  *affected package(s) including the version*
claws-mail-3.17.3_2 

### Expected behavior
Not to pull in lots of deps.  If it is the plugins, can these be spun off into separate packages please?

### Actual behavior
```
Name                  Action    Version           New version            Download size
libvoikko             install   -                 4.2_2                  123KB 
aspell                install   -                 0.60.6.1_10            517KB 
enchant2              install   -                 2.2.3_4                31KB 
libetpan              install   -                 1.9.2_1                247KB 
libproxy              install   -                 0.4.15_1               54KB 
glib-networking       install   -                 2.58.0_1               90KB 
libpsl                install   -                 0.20.2_1               13KB 
libsoup               install   -                 2.64.2_1               254KB 
json-glib             install   -                 1.4.4_1                106KB 
liboauth              install   -                 1.0.3_3                - 
libsoup-gnome         install   -                 2.64.2_1               4220B 
rest                  install   -                 0.8.1_1                39KB 
libxslt               install   -                 1.1.32_1               131KB 
libwoff2common1.0.2   install   -                 1.0.2_1                - 
brotli                install   -                 1.0.7_1                - 
libwoff2dec1.0.2      install   -                 1.0.2_1                - 
gstreamer1            install   -                 1.14.4_1               1086KB 
libGLES               install   -                 18.3.1_2               - 
libcdparanoia         install   -                 10.2_13                39KB 
libvisual             install   -                 0.4.0_9                - 
gst-plugins-base1     install   -                 1.14.4_1               1593KB 
libwebp               install   -                 1.0.1_1                - 
hyphen                install   -                 2.8.8_2                49KB 
webkit2gtk            install   -                 2.22.5_1               - 
gnome-online-accounts install   -                 3.30.0_1               434KB 
libgdata              install   -                 0.17.9_1               358KB 
libical               install   -                 3.0.4_1                255KB 
libcanberra           install   -                 0.30_10                - 
libcanberra-gtk       install   -                 0.30_10                13KB 
claws-mail            install   -                 3.17.3_2               2744KB 
```
### Steps to reproduce the behavior
xbps-install claws-mail

**Comment by laserbat** [comment]
Agreed, but I'm not sure if maintainers will agree to split this package. Also, if you are looking for a minimal mail client, take a look at sylpheed, original project that was forked by claws-mail. It is way less bloated.

**Comment by ErinVoid** [comment]
The annoyance is pulling in what is unnecessary for all users. Once the templates are made, surely any updates are just automagically pulled in. It is a similar argument for why Libreoffice packages are separated out. Debian has each plugin split into its own package not that it is necessarily the best or correct way. However, it does improve user choices.

**Comment by laserbat** [comment]
I will provide a pull request splitting plugins that have dependencies into a separate package later today or tomorrow. 

I see it as a reasonable compromise, since it will avoid creating lots of plugin packages and will provide option not to install "heavy/bloated" ones.

**Comment by maxice8** [comment]
I'd be willing to accept a split on whatever packages depends on webkit2gtk since that is the primary contributor to the problem you're having.

**Comment by maxice8** [comment]
ping, status ?

**Comment by laserbat** [comment]
I haven't been able to start working on this yet, but I'll try to find some time asap.

**Comment by maxice8** [comment]
ping, status ?

**Comment by laserbat** [comment]
I don't think I will be able to work on this issue. I'm dealing with some serious IRL problems at the moment and I'm not even sure when I'll have ability to continue contributing. 

I'm really sorry.
