### ISSUE TITLE
xlocate

### ISSUE THREAD

**Issue by ErinVoid** [void-linux/void-packages#6561]
### System

* xuname:  
Void 4.19.13_1 x86_64-musl AuthenticAMD uptodate rF
* package:  
  *affected package(s) including the version*
xtools-0.54_1  

### Expected behavior
xlocate to pull against current repo

### Actual behavior
Tries, and fails, to pull in old .eu repo.

### Steps to reproduce the behavior
Install and run it. Needs the inbuilt variable to be altered.

**Comment by bobertlo** [comment]
It looks like this has been fixed, it might be still working through the builders? `void-packages` has 0.54 with the fix in it. I'm pulling 0.53 locally.

**Comment by bobertlo** [comment]
You could build this locally from void-packages if you need it right now.

**Comment by maxice8** [comment]
Fixed in https://github.com/chneukirchen/xtools/commit/9f4faddbc8ed328cca1f092e48df3c334090f1c4
