### ISSUE TITLE
bootstrap fails due to chroot-distcc dependency on automake

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#6562]
The recent update of `chroot-distcc` (7af2100686719e35ceead3286b7124d00b326dfe) introduced dependencies on `automake` and `libtool` neither of which is `bootstrap=yes`.

We need to either build `chroot-distcc` without `pre_configure()` and instead import its `configure` through a distfile, or remove `chroot-distcc` from the `base-chroot` and `base-chroot-musl` meta packages; or rather altogether.

IMO very few people, if any, will use `distcc` while bootstrapping `x86_64` which is why I would suggest to do the latter: remove `chroot-distcc`.

**Comment by pullmoll** [comment]
@maxice8 you're used to the remove pkg schedule so may I ask you to take this step, i.e. remove chroot-distcc and remove it from base-chroot{,-musl}? Or should I just remove it at once? Noone of @void-linux/pkg-committers  seems to object.

**Comment by maxice8** [comment]
On Thu, Jan 10, 2019 at 11:40:56AM -0800, Jürgen Buchmüller wrote:
> @maxice8 you're used to the remove pkg schedule so may I ask you to take this step, i.e. remove chroot-distcc and remove it from base-chroot{,-musl}? Or should I just remove it at once? Noone of @void-linux/pkg-committers  seems to object.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/6562#issuecomment-453226947

chroot- packages are meant only for internal usage for xbps-src i don't think there is harm in just removing it.

**Comment by pullmoll** [comment]
True, I'll just remove it then.

**Comment by pullmoll** [comment]
Removed from base-chroot{,-musl} so bootstrapping is possible again.
