### ISSUE TITLE
Package request: hydroxide

### ISSUE THREAD

**Issue by DirectorX** [void-linux/void-packages#6580]
https://github.com/emersion/hydroxide

# hydroxide

A third-party, open-source ProtonMail bridge. For power users only, designed to run on a server.

hydroxide supports CardDAV, IMAP and SMTP.

Rationale:

    No GUI, only a CLI (so it runs in headless environments)
    Standard-compliant (we don't care about Microsoft Outlook)
    Fully open-source

**Comment by maxice8** [comment]
has no releases, please ask upstream to tag a release.

**Comment by Cogitri** [comment]
Oh neat, I'm using the official PM bridge right now, ping me if there's something to test or smth

**Comment by DirectorX** [comment]
@maxice8

https://github.com/emersion/hydroxide/releases/tag/v0.1.0

**Comment by emersion** [comment]
>I would package this but I have no knowledge about go apps right now.

Note that `go mod` should simplify a lot packaging.

1. Clone the repo
2. `go build ./cmd/hydroxide`
3. Profit
