### ISSUE TITLE
hplip cannot find networked devices

### ISSUE THREAD

**Issue by ErinVoid** [void-linux/void-packages#6587]
### System

* xuname:  
  *Void 4.19.13_1 x86_64-musl AuthenticAMD uptodate rF*
  *HP Officejet Pro 8620, hpcups 3.18.12 on wired network*

* package:  
  *hplip-3.18.12_1     HP Linux Imaging and Printing*

### Expected behavior
Find networked HP printers.  However, uninstalling and installing `hplip-gui-3.18.12_1`, going into the advanced options and specifying the IP address does work. Then the -gui version can be uninstalled and the non-gui version reinstalled.

### Actual behavior
Fails to find a printer, even if URI is specified.

### Steps to reproduce the behavior
Install hplip, run `sudo hp-setup -i `with / without an IP address or URI.

### Notes
It may be an HP software issue and not Void at all.  Installing the gui version permits a workaround. The uninstalling the gui version and installing the non-gui version means there is a working printer.

**Comment by Hoshpak** [comment]
Do you have `avahi` installed and running? I think the last time I worked with networked HP printers, discovery relied on mDNS and would not work without avahi.

**Comment by ErinVoid** [comment]
As per the OP, with the advanced options in the gui version, it works correctly. mDNS/avahi were not installed and Bonjour is switched off in the printer anyhow. According to the HP support pages, SPL is the discovery method.

**Comment by ericonr** [comment]
Maybe can be fixed in documentation?
