### ISSUE TITLE
webkit2gtk: update

### ISSUE THREAD

**Issue by DirectorX** [void-linux/void-packages#669]
currently void uses `2.20.0` but there are `2.20.3` (stable) and `2.21.4` (unstable). those version are patched against known security vulnerabilities described [here](https://www.webkitgtk.org/security/WSA-2018-0005.html).

list of package that uses webkit2gtk:

- FeedReader
- atril
- bijiben
- cinnamon-screensaver
- devhelp
- emacs
- empathy
- epiphany
- evolution-data-server
- evolution-ews
- evolution
- geary
- gitg
- gnome-boxes
- gnome-documents
- gnome-initial-setup
- gnome-online-accounts
- gthumb
- libgepub
- liferea
- luakit
- midori
- shotwell
- surf
- sushi
- vimb
- xreader
- yelp
- zenity

**Comment by travankor** [comment]
I tried building this, but I an error like this:
https://www.mail-archive.com/blfs-support@lists.linuxfromscratch.org/msg05118.html

Maybe it is a problem with my xbps setup, I don't know.

**Comment by travankor** [comment]
@DirectorX closed by https://github.com/void-linux/void-packages/commit/42e055d2bbae6792af727493131d0a2a185d9f59
