### ISSUE TITLE
Firefox-61.0_2 update crashes with NPAPI Adobe Flash plugin

### ISSUE THREAD

**Issue by ruegerjr** [void-linux/void-packages#670]
NPAPI plugin was working for Void’s firefox-60.0_2 package. But the up-to-date Flash version (30.0.0.113) crashes on firefox-61.0_2 Void package. Something similar happened around firefox version 57, but started working after that.  **Firefox 61.0_2 compiled directly from source with default flags (pulseaudio dependent) still works with the NPAPI plugin**.  As an aside, The PPAPI plugin and Freshplayer have not worked for me with any "Quantum" Firefox release, but unnecessary if the NPAPI plugin can still work.

Firefox behaves correctly unless attempting to play flash content, which sometimes crashes Flash plugin only, or sometimes brings down Firefox entirely. am running Void x86_64 glibc kernel 4.16.14_1

**Comment by maxice8** [comment]
still broken with current firefox ?

**Comment by ruegerjr** [comment]
I had not tried the void package in a while since compiling from source with pulseaudio support has worked well for me, but your question prompted me to give it a try.  Still broken for me.  With void firefox-64.0_1 package, kernel linux-4.19_1, and NPAPI Flash plugin 31.0.0.153 I, Flash crashes with console messages similar to:

(/usr/lib/firefox/plugin-container:5712): Gdk-WARNING **: 20:30:26.527: The GDK_NATIVE_WINDOWS environment variable is not supported in GTK3.
See the documentation for gdk_window_ensure_native() on how to get native windows.
[Parent 5370, Gecko_IOThread] WARNING: pipe error (177): Connection reset by peer: file /builddir/firefox-64.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 363

(/usr/lib/firefox/plugin-container:5712): GLib-GObject-WARNING **: 20:30:26.597: cannot register existing type 'GdkDisplay'

(/usr/lib/firefox/plugin-container:5712): GLib-CRITICAL **: 20:30:26.597: g_once_init_leave: assertion 'result != 0' failed

(/usr/lib/firefox/plugin-container:5712): Gdk-CRITICAL **: 20:30:26.597: IA__gdk_pixmap_foreign_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
[Child 5480, Chrome_ChildThread] WARNING: pipe error (21): Connection reset by peer: file /builddir/firefox-64.0/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 363

###!!! [Parent][MessageChannel] Error: (msgtype=0x60000A,name=PPluginModule::Msg_PPluginInstanceConstructor) Channel error: cannot send/recv

**Comment by obunden** [comment]
@Johnnynator @Hoshpak 
Firefox themselves stopped officially supporting NPAPI over a year ago. Think this can be closed since supporting old deprecated interfaces that has security issues is not good in the first place.

**Comment by Hoshpak** [comment]
Indeed, let's close.
