### ISSUE TITLE
Package Request: cloudfuse

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#683]
https://github.com/redbo/cloudfuse

Cloudfuse is a FUSE application which provides access to Rackspace's
Cloud Files (or any installation of Swift).

You'll need libcurl, fuse, libssl, and libxml2 (and probably their dev
    packages) installed to build it.  From a base Debian or Ubuntu install,
    this should get you to a point you can build and run it. 

Looks like an easy to package application.

**Comment by cr6git** [comment]
@maxice8 :+1:

**Comment by Anachron** [comment]
@cr6git @maxice8 thank you guys!
