### ISSUE TITLE
Package Request: NextCloud Client

### ISSUE THREAD

**Issue by Floppybobby** [void-linux/void-packages#6854]
https://nextcloud.com/install/#install-clients
The OwnCloud client is already there. I think we should show NextCloud some love too.

**Comment by Hoshpak** [comment]
unfortunately it still doesn't support libressl.

**Comment by maxice8** [comment]
#4456 is the PR for nextcloudclient , it doesn't support LibreSSL.

Please help the nextcloud devs show some love for LibreSSL, help us help you.
