### ISSUE TITLE
Unable to locate 'gegl' in repository pool.

### ISSUE THREAD

**Issue by biopsin** [void-linux/void-packages#687]
### System
glibc x86_64

* package:  
  gegl-04.4_1

### Expected behavior
able to install from repo

### Actual behavior
Unable to locate 'gegl' in repository pool.

### Steps to reproduce the behavior
xbps-install -S gegl

**Comment by cr6git** [comment]
From which repository?
No problem for me.

**Comment by biopsin** [comment]
Oops, my bad had it set manualy and forgot to cleanup older versions
