### ISSUE TITLE
Weechat aspell

### ISSUE THREAD

**Issue by ErinVoid** [void-linux/void-packages#6883]
### System
* xuname:  
  *Void 4.19.13_1 x86_64-musl AuthenticAMD uptodate rF*
* package:  
  *weechat-2.3_1*
  *weechat-aspell-2.3_1*
  *aspell-0.60.6.1_10*
  *aspell-en-2018.04.16_1*
  *aspell-fr-0.50.3_2*

### Expected behavior
Suggest spelling mistakes as per Weechat manual/wiki etc.

### Actual behavior
Spelling does not work and all words are highlighted as being correct.  The following messages are in the "Freenode" window:
```
13:35:23  weechat     | aspell: warning: dictionary "en" is not available on your system
13:35:23  weechat    | aspell: error: unable to create speller for lang "en"
13:35:26  weechat    | aspell: error: unable to create speller for lang ""en"
```
### Steps to reproduce the behavior
Install above packages, enable aspell and type.  It potentially is solely a musl based issue as discussion in the irc channel suggests that the glibc version works correctly.  Information on the Internet could link the problem to setting a locale or lack of!

**Comment by ErinVoid** [comment]
This has been reported by multiple users [IRC] and is also listed in weechat's [Github](https://github.com/weechat/weechat/issues/1290) where is has been assigned "bug".

**Comment by Cogitri** [comment]
Could you run `aspell dump dicts` to make sure aspell actually does work?

**Comment by ErinVoid** [comment]
Both dictionaries are fine as is running `aspell check my.txt`

**Comment by natrys** [comment]
The weechat-aspell plugin, contrary to what its name suggests, actually uses enchant, which is a unifying front-end for various existing spell checkers.

Enchant does support aspell too, but it's [disabled](https://github.com/void-linux/void-packages/blob/0fa5daec81e52284c1e74da86d2ec90edec7dd9a/srcpkgs/enchant/template) in Void because aspell is old and buggy. Basically, installing `hunspell` and one of its dictionaries is what you need to do as aspell itself is irrelevant here.

**Comment by ralphee** [comment]
> ......installing `hunspell` and one of its dictionaries is what you need to do as aspell itself is irrelevant here....

.....that did the trick...working perfectly now....

**Comment by ErinVoid** [comment]
Working for me on a glibc machine, need to check when I get to the musl machine it works correctly then will close. Thanks for the assistance from all.

**Comment by maxice8** [comment]
ping, status ?

**Comment by ErinVoid** [comment]
So back with other laptop. Works as described. Should it be documented somewhere, i.e. xpbs message during install, does not work with aspell?

**Comment by Cogitri** [comment]
Maybe weechat-aspell should just depend on hunspell, since that's required for it to work

**Comment by ErinVoid** [comment]
Upstream are renaming the package away from ["aspell"](https://github.com/weechat/weechat/issues/1299) so there is less ambiguity. It is also a wish that xbps packages eventually contain a long note section to detail issues such as these that can be queried on the command line.

**Comment by ErinVoid** [comment]
Too frequently the INSTALL messages whizz past and are impossible to read. Even inclusion of that message so it can be viewed by a switch in xbps-query would be a bonus. For "weechat-aspell" it could have been as simple as "aspell not supported, use hunspell or similar".

**Comment by Cogitri** [comment]
Or we just make it depend on hunspell, since it needs that to be functional

**Comment by ErinVoid** [comment]
For weechat-aspell, soon to be weechat-spell, or course but for the bigger picture, longer text somewhere would be a bonus. I'll close this issue and open a new one in xbps.
