### ISSUE TITLE
iwd failing because of missing kernel options

### ISSUE THREAD

**Issue by codingHahn** [void-linux/void-packages#6887]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
Void 4.19.13_1 x86_64 GenuineIntel notuptodate rrrmFFFFFFFF
* package:  
  *affected package(s) including the version*
iwd 0.13_1

### Expected behavior
When I start the iwd daemon, it should start.

### Actual behavior
It errors with this
```
No Diffie-Hellman support found, WPS will not be available
No asymmetric key support found.
TLS based WPA-Enterprise authentication methods will not function.
Kernel 4.20+ is required for this feature.
The following options are missing in the kernel:
	CONFIG_ASYMMETRIC_KEY_TYPE
	CONFIG_KEY_DH_OPERATIONS
	CONFIG_ASYMMETRIC_PUBLIC_KEY_SUBTYPE
	CONFIG_PKCS7_MESSAGE_PARSER
	CONFIG_X509_CERTIFICATE_PARSER
	CONFIG_PKCS8_PRIVATE_KEY_PARSER
Wireless daemon version 0.13
Skipping optional configuration file /etc/iwd/main.conf
Name request failed
D-Bus disconnected, quitting...

```

### Steps to reproduce the behavior

Install iwd and try to start with:
```
[void@void ~]$ sudo /usr/libexec/iwd
```

**Comment by Johnnynator** [comment]
> Kernel 4.20+ is required for this feature.

Have you tried with a 4.20 kernel

**Comment by codingHahn** [comment]
I think this

> > Kernel 4.20+ is required for this feature.
> 
> Have you tried with a 4.20 kernel

is only required for 



> TLS based WPA-Enterprise authentication methods will not function. Kernel 4.20+ is required for this feature.

. Dbus should be running, I can launch applications through dbus with dbus-launch...

**Comment by Hoshpak** [comment]
The only one truly missing was `CONFIG_KEY_DH_OPERATIONS` which is not enabled except for arm kernels currently. I updated the kernel configuration for 4.19 and 4.20 in https://github.com/void-linux/void-packages/commit/8f018d63f268e94a1556c21e2c03705b14c6d9e3 and https://github.com/void-linux/void-packages/commit/38263ba1d567ccad27b9b377090d05af1df9d640 . The next time the kernels are updated, they will be built with that option.

**Comment by Hoshpak** [comment]
4.20 has been updated and 4.19 is currently compiling with the new configuration.
