### ISSUE TITLE
octoxbps no means to get admin credentials

### ISSUE THREAD

**Issue by chriscamacho** [void-linux/void-packages#6892]
I have both gksu and kdesu packages installed, unfortunately the gksu package no has no files in it and is slated for removal, and octoxbps doesn't seem to recognise that kdesu is installed.

This is a shame as despite octoxbps not being viewed favourably by some devs, it is the only means for none technical people to keep their system up to date, I'm hoping that I won't have to find a new distro for my wife and sister as even run by a none techie their systems need very minimal maintenance from me since being on Void.

attempting to run octoxbps as root is prevented by the application itself

**Comment by Johnnynator** [comment]
You need the afaik `kde-cli-tools` package the kdesu package one does only contain kdesud and not `/usr/bin/kdesu`

**Comment by chriscamacho** [comment]
73 extra packages installed !!! it sort of works requiring root password instead of users twice to do an update, wonder what I'm going to do for the sister and wife when kdesu goes away....

**Comment by Johnnynator** [comment]
> 73 extra packages installed !!! it sort of works requiring root password instead of users twice to do an update, wonder what I'm going to do for the sister and wife when kdesu goes away....

I will split the package up later, I'm aware that it pulls in quite a lot package that are not needed at all.

**Comment by chriscamacho** [comment]
@Johnnynator I had a quick hack at the source of octoxbps, commenting out the check for root in main.cpp seems to work okay (other package managers run like this) this would allow it to be run with pkexec or and explicit choice of graphical sudo (as opposed to su) from the command line - worth a thought....

**Comment by chriscamacho** [comment]
no you can't run it as root, and octoxbps tends to favour su when looking for a way to get admin rights when it gets them.
I'll have a look at octopi (never heard of it)

**Comment by Johnnynator** [comment]
> no you can't run it as root, and octoxbps tends to favour su when looking for a way to get admin rights when it gets them.
> I'll have a look at octopi (never heard of it)

It is nearly the same codebase but for pacman (Arch). It e.g. use `lxqt-sudo -d` instead if `lxqt-sudo -s`, so sudo instead of su in this case.

**Comment by chriscamacho** [comment]
I did try replacing -s with -d in QString WMHelper::getLXQTSUCommand() however this fails saying it can't find the command, not sure whats going on, but like I say if you by pass the root check block in main then it never bothers with su/sudo
I'm not familiar enough with xbps-src to provide a pull request, but line 86+ of main.cpp
`  if (UnixCommand::isRootRunning() && !WMHelper::isKDERunning()){
    QMessageBox::critical( 0, StrConstants::getApplicationName(), StrConstants::getErrorRunningWithRoot());
    return ( -2 );
  }`
if you comment out this section of code, then it can work with sudo or pkexec etc... which also means that people can modify the desktop file to use whatever graphical rights granting tool they like

**Comment by chriscamacho** [comment]
oh couldn't find octopi ?

**Comment by Johnnynator** [comment]
https://github.com/aarnt/octopi/pull/356/files <- Both change for e.g. lxqt and the octopi repo

**Comment by chriscamacho** [comment]
I did try a similar modification with octoxbps but it failed saying it couldn't find the command (xbps-install)
