### ISSUE TITLE
dhcpcd service outputs to standard error

### ISSUE THREAD

**Issue by zacharied** [void-linux/void-packages#6948]
### System
* xuname:  
  * `Void 4.18.17_1 x86_64-musl GenuineIntel notuptodate rF`
* package:  
  * `dhcpcd 7.0.8_1`

### Expected behavior

Loggers like `svlogd` and `vlogger` only read from stdin, not stderr. Services compensate for this by redirecting stderr to stdin in the command. Expected behavior is that `dhcpcd` outputs to standard input (as long as the `OPTS` are overridden to avoid writing to `syslog`).

### Actual behavior

`dhcpcd` outputs to stderr.

### Steps to reproduce the behavior

Run the `dhcpcd` service along with a logging service linked to `vlogger`. `vlogger` is designed to only receive stdin, so it will not log anything for `dhcpcd`.

### Fix for the issue

Replace the line

https://github.com/void-linux/void-packages/blob/4a00d41d3d4757f443b56899010f420f718a4672/srcpkgs/dhcpcd/files/dhcpcd/run#L3

with `exec dhcpcd -B ${OPTS:=-M} 2>&1`.

**Comment by CameronNemo** [comment]
I am fairly sure this is by design. Is there any reason you want to use logger or svlogd instead of simply using dhcpcd built in logging options (syslog, log file)?

**Comment by zacharied** [comment]
@CameronNemo It would just be nice to have the logging behavior be consistent with other applications. It's kind of a pain to remember where to look for logs for all these different services. It's also much easier for me to automate if all programs log in the same way.

**Comment by CameronNemo** [comment]
All fair points, however note that:

* some people value consistency in the opposite direction (all services logging to syslog)
* I could not find a way to disable dhcpcd logging to syslog... this would likely be a good idea if the service file is changed to include svlogd logging.

**Comment by Duncaen** [comment]
This is the idea of [vlogger(8)](http://man.voidlinux.org/vlogger.8), it uses runits logging mechanism to log to syslog by default, fixing the brokeness of `logger(1)` without systemd, but also makes it easy to switch from the default to use svlogd or any other logging mechanism.

dhcpcd itself doesn't log to syslog if `--logfile` is given, but it fopen("a") the file, maybe `--logfile /dev/stdout` works.
The hooks look like they to use `logger(1)` and stdout.
