### ISSUE TITLE
MuseScore pulls whole clang as an indirect dependency

### ISSUE THREAD

**Issue by laserbat** [void-linux/void-packages#6949]
### System

* xuname:  
  *xuname: Void 4.20.1_1 x86_64 AuthenticAMD uptodate rrrmFFFFFFFF*
* package:  
  *musescore-3.0_1*
  *qt5-tools-5.11.3_3*

I'm not sure if this issue will be taken seriously, but it seems pretty bizarre for me, especially since void is positioned as minimalist linux distro.

As far as I can understand the issue, clang should be optional dependency of qt5-tools, like it is in arch linux, since it's a very big package and is unnecessary for most functionality of qt5-tools. Since xbps has no support for optional dependencies, I suggest splitting  clang-dependant part of qt5-tools into a separate package, like qt5-tools-qdoc

If maintainers agree to this decision, I'd be happy to provide a pull-request to split qt5-tools.

```
>>> xbps-query -x musescore
qt5-plugin-sqlite>=0
libvorbis>=1.2.1rc1_1
libsndfile>=1.0.20_1
alsa-lib>=1.0.20_1
qt5>=5.6.0_1
qt5-xmlpatterns>=5.6.0_1
qt5-svg>=5.6.0_1
qt5-tools>=5.6.0_1
qt5-webengine>=5.6.0_1
zlib>=1.2.3_1
glibc>=2.28_1
portaudio>=19.20140130_1
portmidi>=217_1
libpulseaudio>=1.0_1
qt5-declarative>=5.6.0_1
libstdc++>=4.4.0_1
libgcc>=4.4.0_1
>>> xbps-query -x qt5-tools
qt5-translations>=0
desktop-file-utils>=0
hicolor-icon-theme>=0
qt5-declarative-5.11.3_3
qt5>=5.6.0_1
libstdc++>=4.4.0_1
glibc>=2.28_1
clang>=7.0.0_1
```

**Comment by Cogitri** [comment]
@pullmoll I guess

**Comment by pullmoll** [comment]
I have no idea why the dependency on qt5-tools is in MuseScore. Perhaps we need to split the libraries (libQt5Designer, libQt5DesignerComponents, libQt5Help) to a new subpackage qt5-tools-libs to not depend on clang. The binaries in qt5-tools are required by packages actually building qt5 help files or plugins for linguist or assistant etc. and I think they are what creates the dependency on clang.
Currently I'm busy with other things, so I can't help now.

**Comment by ndowens** [comment]
So far, I am test building qt5 without clang, so far as I type this, it is building fine

**Comment by abenson** [comment]
Is this still an issue?

`libclang` has been split off now.

```
% xbps-query -Rx qt5-tools | grep clang
libclang>=10.0.0_3
```

**Comment by pullmoll** [comment]
AFAICT this is solved, thus closing the issue.
