### ISSUE TITLE
Package Request: LiteIDE

### ISSUE THREAD

**Issue by hsandor** [void-linux/void-packages#6998]
Please consider adding package LiteIDE. It's a very good IDE for Golang. Thank you.
License: LGPL-2.1
Source: https://github.com/visualfc/liteide
Installing: https://github.com/visualfc/liteide/blob/master/liteidex/deploy/welcome/en/install.md

**Comment by ndowens** [comment]
Working on this

**Comment by ndowens** [comment]
# Template file for 'liteide'
pkgname=liteide
version=35.3
wrksrc=liteide-x${version}
build_wrksrc=liteidex
build_style=qmake
revision=1
hostmakedepends="qt5-qmake"
makedepends="qt5-tools-devel"
depends="go"
short_desc="Simple, open source, cross-platform Go IDE"
maintainer="Nathan Owens <ndowens04@gmail.com>"
license="LGPL-2.1-or-later"
homepage="https://github.com/visualfc/liteide"
distfiles="https://github.com/visualfc/liteide/archive/x35.3.tar.gz"
checksum=b48604ecc9c0e1a654043b9c18e4ff0cd0015a35f1846d585f5119d23fba724b

liteide-devel_package() {
	depends="${sourcepkg}>=${version}_${revision}"
	short_desc+=" - development files"
		pkg_install() {
			vmove "usr/lib/liteide/*.a"
			vmove "usr/lib/liteide/*.so.*"
		}
}

**Comment by ndowens** [comment]
Try that, I tried it and for some reason I could not create a file. So I have no idea what is going on with it
