### ISSUE TITLE
Okular doesn't install

### ISSUE THREAD

**Issue by spOOn3113** [void-linux/void-packages#6999]
### System

* xuname:  
  Void 4.19.13_1 x86_64 GenuineIntel uptodate FFF
* package:  
  okular-18.12.0_1
  libkexiv25-18.12.0_1

### Expected behavior
Package successfully install.

### Actual behavior

-bash-4.4# xbps-install -S okular
[*] Updating `http://mirror.aarnet.edu.au/pub/voidlinux/current/x86_64-repodata' ...
libkexiv25-18.12.0_1: broken, unresolvable shlib `libexiv2.so.26'
Transaction aborted due to unresolved shlibs.

### Steps to reproduce the behavior

xbps-install -S okular

**Comment by Johnnynator** [comment]
You should sync the repo before trying to install a package. The libkexiv25 version you are trying to install is not the one in the repo

**Comment by spOOn3113** [comment]
Hi @Johnnynator,

Thnaks for that.

I'm new to void, but it was my understanding that's what the -S in xbps-install did?

The command I'm using is xbps-install -S okular

Is there something else I should be doing?

https://wiki.voidlinux.org/XBPS#Synchronize_remote_repository_data seems to suggest this should do the trick....

**Comment by spOOn3113** [comment]
Well, I guess I'm not seeing the later version in the repo then...

-bash-4.4# xbps-install -Su okular
[*] Updating `http://mirror.aarnet.edu.au/pub/voidlinux/current/x86_64-repodata' ...
[*] Updating `http://mirror.aarnet.edu.au/pub/voidlinux/current/multilib//x86_64-repodata' ...
libkexiv25-18.12.0_1: broken, unresolvable shlib `libexiv2.so.26'
Transaction aborted due to unresolved shlibs.
-bash-4.4# xbps-install -S okular
[*] Updating `http://mirror.aarnet.edu.au/pub/voidlinux/current/x86_64-repodata' ...
[*] Updating `http://mirror.aarnet.edu.au/pub/voidlinux/current/multilib//x86_64-repodata' ...
libkexiv25-18.12.0_1: broken, unresolvable shlib `libexiv2.so.26'
Transaction aborted due to unresolved shlibs.

Is it likely the mirror I'm using isn't up to date?

xbps-query is only showing 18.12.0_1:

-bash-4.4# xbps-query -Rs libkexiv25
[-] libkexiv25-18.12.0_1             A library to manipulate pictures metadata
[-] libkexiv25-devel-18.12.0_1       A library to manipulate pictures metadata - development files
[-] libkexiv25-32bit-18.12.0_1       A library to manipulate pictures metadata (32bit)
[-] libkexiv25-devel-32bit-18.12.0_1 A library to manipulate pictures metadata - development files (32bit)

Would I be correct in saying the version I'm looking for is 18.12.0_2 (which I think I can see in the git repo?)

**Comment by Johnnynator** [comment]
Sounds like the mirror you are using is not in sync.

**Comment by spOOn3113** [comment]
@Johnnynator 

Thanks for the help, I've pointed to http://alpha.de.repo.voidlinux.org and Okular now installs.

Sorry for all the bother.
