### ISSUE TITLE
clang: libgcc-8.2.0_8 (update) breaks installed pkg `libstdc++-8.2.0_5'

### ISSUE THREAD

**Issue by mcandre** [void-linux/void-packages#7011]
When I run `sudo xbps-install -uSy clang` on a fresh Void Linux virtual machine, it complains that libgc8.2.0_8 would break libstdc++-8.2.0_5.

As a workaround, I can use gcc for some projects, though other projects do specifically require clang/llvm, and are unable to build in Void Linux Live now.

**Comment by Hoshpak** [comment]
Trying to update a single package without updating the others may cause such issues. Try to update the whole system with `xbps-install -Su`, that should properly update the dependencies and thus not lead to unresolved shlibs.

**Comment by maxice8** [comment]
Ping, issue still present ?

**Comment by maxice8** [comment]
stale, closing
