### ISSUE TITLE
KNewStuff can't fetch metadata / locks up applications

### ISSUE THREAD

**Issue by Fyrenic** [void-linux/void-packages#703]
### System

* xuname: Void 4.16.14_1 x86_64 GenuineIntel uptodate rrrrmmn
* package: knewstuff-5.43.0_1 (probably affecting all versions)

### Expected Behavior

knewstuff should fetch metadata to display themes and icons from store.kde.org.

### Actual Behavior

knewstuff freezes and therefore locks up any program that calls it (like Yakuake).

**This only happens, when the computer is connected to the internet.** When it is not connected to the internet, the `Addon Installer` opens up as it should and it does not lock up.

### Steps to reproduce the behavior

* Install `yakuake`
* Run `yakuake` and open the `Configure` Window
* Go to `Appearance` and click on `Get new Skins`
* Application locks up

**Comment by Chocimier** [comment]
Does it work in any other distro?

**Comment by Fyrenic** [comment]
Yes.
I just tested it on the newest KDE Neon (ver. 20180705) and it works there as it should.
It fetches the data from the store and then displays a list of available addons.

**Comment by Chocimier** [comment]
That needs `/usr/lib/qt5/plugins/attica_kde.so` from `plasma-desktop`.

**Comment by maxice8** [comment]
@Johnnynator

**Comment by ericonr** [comment]
Hi there, is this issue still happening?

**Comment by MPC7500** [comment]
Could be closed then, I guess?

**Comment by ericonr** [comment]
It seems we still lack any `attica_kde` files, so maybe not?
