### ISSUE TITLE
Bug: gpg-server complains about being too old

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#704]
### System

* xuname:  Void 4.16.12_1 x86_64 GenuineIntel uptodate rrrmFFFFF
* package:  `gpg`, `gpg-server`, `pass`

### Expected behavior
gpg-server not complaining that it's too old

### Actual behavior
when being invoked gpg complains about being older than the server:
`gpg: WARNING: server 'gpg-agent' is older than us (2.2.7 < 2.2.8)`

### Steps to reproduce the behavior
try to use gpg-server to encrypt/decrypt stuff

**Comment by m-cz** [comment]
Try ````gpgconf --kill gpg-agent````

**Comment by Anachron** [comment]
Silly me ... that was it! Thanks.
