### ISSUE TITLE
hardinfo: rebuild or?

### ISSUE THREAD

**Issue by whoizit** [void-linux/void-packages#7117]
just launch `hardinfo`, click in app `Computer->Summary` and gettin this:
```
$ hardinfo
hardinfo: symbol lookup error: /usr/lib/hardinfo/modules/computer.so: undefined symbol: size_human_readable
```

**Comment by maxice8** [comment]
Please use the issue format provided

**Comment by maxice8** [comment]
plus hardinfo works here, we are going to need more information from you
