### ISSUE TITLE
Error trying to build vscode with xbps-src.

### ISSUE THREAD

**Issue by iyyel** [void-linux/void-packages#718]
Hi!

I'm having a problem building vscode. The error I'm getting can be seen on the screenshot below.

![kwbazln](https://user-images.githubusercontent.com/25253378/42411656-b98014aa-81ff-11e8-87ef-0a8c09e53026.png)

This is how I'm trying to build the package:

`git clone https://github.com/void-linux/void-packages`
`cd void-packages`
`./xbps-src binary-bootstrap`
`echo XBPS_ALLOW_RESTRICTED=yes > etc/conf`
`./xbps-src pkg vscode` (*)

(*) is the command where the error occurs. At first I thought it was an issue with the _ARCH variable not being set correctly, but that was not the issue. It seems something goes wrong during the linking process with node.js.

All this is happening on a x64, fully up to date void linux installation on a ThinkPad 13, running kernel 4.16.14_1 x86_64. To reproduce this, try to build the package. I have only tested this on one machine, since I don't have others running void. 

Any ideas or suggestions?

Thank you.

**Comment by maxice8** [comment]
Can't recreate the error here with current vscode, please re-open in case it still fails.
