### ISSUE TITLE
Package Request: fcitx-googlepinyin

### ISSUE THREAD

**Issue by kevinbogao** [void-linux/void-packages#7184]
Void Linux currently doesn't have any Chinese input method engine, so please consider adding the fcitx-googlepinyin package. 

url: https://github.com/fcitx/fcitx-googlepinyin
Installing: https://github.com/fcitx/fcitx-googlepinyin/blob/master/INSTALL
Source: https://download.fcitx-im.org/fcitx-googlepinyin/

**Comment by ndowens** [comment]
Is there any others you'd consider, seems upstream may be dead, last commit was in 2017

**Comment by kevinbogao** [comment]
There are other Chinese input engines for fcitx, but all of them seem to be in the same situation as googlepinyin unfortunately.

**Comment by pobetiger** [comment]
I had a hard time getting fcitx working. I have placed a pull request with ibus-libpinyin: https://github.com/void-linux/void-packages/pull/6423 up for review. I have been away and unable to make amends to that commit, it says it's closed. Not sure if it's merged.

**Comment by pobetiger** [comment]
@maxice8 Thank you. I can confirm that it can be installed from `xbps-install` now. I guess it takes a couple of days from merge to being in the repo. @kevinbogao, does ibus satisfy your requirement?

**Comment by kevinbogao** [comment]
Sorry for the delayed response, but yes, ibus will work for me. Thank you very much!

**Comment by maxice8** [comment]
No release in 7 years
