### ISSUE TITLE
linux: Kernel is missing modules required to boot LVM/LUKS

### ISSUE THREAD

**Issue by lluixhi** [void-linux/void-packages#720]
### System

* xuname:  
`Void 4.17.4 x86_64 GenuineIntel uptodate rrrmF`
* package:  
`linux-4.16_1`

### Expected behavior
At boot time, the kernel has the modules necessary to mount an LVM/LUKS system without issue.
### Actual behavior
At boot time, an error is thrown saying the module "dm_crypt" is not found, and dracut complains about missing AES functions, despite the "crypt" module being loaded and grub successfully decrypting the boot partition.
### Steps to reproduce the behavior
1. Install void linux to an encrypted root partition
2. Attempt to boot

Can the kernel that's distributed by void include the requisite modules? It's troublesome to have to compile a kernel manually in order to boot my system.

This issue was previously reported at https://github.com/voidlinux/void-packages/issues/15177

**Comment by Anachron** [comment]
What happens if you `reconfigure -f linux-4.16` and reboot? Same issue?

**Comment by abenson** [comment]
What changes do you make in the kernel you build?

**Comment by newbluemoon** [comment]
How did you verify that the crypt module was loaded? Did you explicitly use `add_dracutmodules`?

If not, this sounds similar to a [recent forum thread](https://forum.voidlinux.eu/t/solved-dracut-no-longer-finds-lvm-luks-partition-with-4-16-update/6119/) where the solution was to create (e.g.) `/etc/dracut.conf.d/modules.conf` which contains a line

    add_dracutmodules+=" crypt "

and then

    xbps-reconfigure -f linux4.16

**Comment by abenson** [comment]
@lluixhi In addition to what we've already said so far, can you provide more information about your setup? I have luks+lvm in a VM and on a number of physical systems, and we've yet to have any issues with the stock kernel, so maybe it's something specific to your setup.

**Comment by lluixhi** [comment]
Okay so first of all in the OP post I'm actually using a version of 4.17.4 that I built myself because I can't get the binary versions to get past decrypt of my rootfs.

After the update to kernel 4.17.4_1 the problem persists so I'm once again using the version I built.

Because I'm on bare metal, here's what my screen shows typed out with the distro kernel.
```
modprobe: FATAL: Module dm_crypt not found in directory /lib/modules/4.17.4_1
Enter passphrase for /dev/sda6:
device-mapper: table: 254:0: crypt: unknown target type
device-mapper: reload ioctl on  failed: Invalid argument
Failed to setup dm-crypt key mapping for device /dev/sda6
Check that the kernel supports aes-xts-plain64 cipher (check syslog for more info).
Wrong password
```
I don't currently have `add_dracutmodules+="crypt"` listed in a config in my dracut.conf.d because the initial ramdisk already says the crypt module is included in the ramdisk image, and dracut should be able to autodetect that I'm using LUKS if I'm using `hostonly`, especially because I don't have the same issue with my normal kernel, no?

That said, in my kernel I have the aes and dm-crypt modules built into my kernel instead of as modules -- should this make a difference?

I'll try adding the dracutmodules line and if the issue is fixed, close this..

**Comment by lluixhi** [comment]
Adding `add_dracutmodules+="crypt"` in a file in `dracut.conf.d` and running `xbps-reconfigure -f linux4.17` still doesn't include the required module in the initramfs, but I can't say I'm surprised because with or without that line, dracut includes the "crypt" module, but not the "dm-crypt" and aes kernel modules.

**Comment by lluixhi** [comment]
Attempting to forcibly add the dm-crypt module using the `--add-driver` option fails because dracut looks for the wrong module, apparently??
`dracut --force --add-driver dm-crypt /boot/initramfs-4.17.4_1.img`
```
...
dracut-install: ERROR: installing 'dm_crypt'
...
```

**Comment by Anachron** [comment]
I am not sure what's going on here. I use LVM on LUKS and I don't have these issues with the `linux-4.16` or `linux-4.17` kernel. I think the setup you followed is bad. Can you upload your configs (grub, dracut, fstab, crypttab) and `lsblk`?

**Comment by newbluemoon** [comment]
When using `add_dracutmodules` the extra spaces are vital: `add_dracutmodules+=" crypt "`

**Comment by lluixhi** [comment]
@newbluemoon didn't make a difference
@Anachron where should I upload them?

**Comment by Anachron** [comment]
@lluixhi depends on what you are familiar with. Make a gist or upload it to http://ptpb.pw I'd say.

**Comment by xtraeme** [comment]
not an issue, you need to tell dracut to load the appropiate modules
