### ISSUE TITLE
Where is new forums?

### ISSUE THREAD

**Issue by karl-k** [void-linux/void-packages#723]
Hi, it looks like your forum is locked down or in "read-only mode", where can I find the new forums page? I am sorry but this is only place I know where to ask, I am getting an error when trying to update Void musl, been like this for a while, must we change the repos that xbps tries to connect to? I heard that you guys lost control of a lot of parts of Void Linux because the primary owner disappeared, but don't know much else.

**Comment by Johnnynator** [comment]
It is just in maintanance currently. Should be usable soon again.

**Comment by Johnnynator** [comment]
Also the musl repo is not fully uptodate since the builder crashed and isn't back yet (sadly since days).

**Comment by maxice8** [comment]
@Johnnynator explained it.

You can also join #voidlinux on freenode if you have more questions

**Comment by karl-k** [comment]
Thank you both. I figured you guys were moving forums because of the recent problems & the read-only mode.
