### ISSUE TITLE
Package Issue: PlayOnLinux cant find OpenGL libs

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#7316]
### System

* xuname:  
Void 4.19.15_1 x86_64 GenuineIntel uptodate rrrmFFFFF
* package:  
playonlinux-4.3.4_1

### Expected behavior
PlayOnLinux to launch

### Actual behavior
Starting PlayOnLinux causes the following error-messages to appear (as Popup-Dialog):
```
Failed to load 32bit OpenGL graphics library
Failed to load 64bit OpenGL graphics library
```
Manually invoking wine or using wine through Lutris works however.

### Steps to reproduce the behavior
1. Install PlayOnLinux
2. Launch it

**Comment by Hoshpak** [comment]
How to reproduce? It doesn't show the warning on any of my systems.

Am 17. Januar 2019 11:09:25 MEZ schrieb Anachron <notifications@github.com>:

**Comment by Anachron** [comment]
Are you having dual graphics? 

My setup:
```
lspci | grep 'VGA\|Display'
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
01:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Topaz XT [Radeon R7 M260/M265 / M340/M360 / M440/M445] (rev c3)

glxinfo | grep -i "opengl renderer"
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)

DRI_PRIME=1 glxinfo | grep -i "opengl renderer"
OpenGL renderer string: AMD ICELAND (DRM 3.27.0, 4.19.15_1, LLVM 7.0.1)
```

What else do you need?

**Comment by Hoshpak** [comment]
No, I just have integrated Intel graphics which works fine. So this is something comparable to OPTIMUS/Bumblebee? I've got no experience with that.

Am 17. Januar 2019 12:04:45 MEZ schrieb Anachron <notifications@github.com>:

**Comment by Hoshpak** [comment]
So it seems that POL uses two binary files located in `/usr/share/playonlinux/bin` to check for OpenGL. Since these binaries are shipped with the source code and not compiled while building the package, it could be that these are linked against libraries that are not installed on your system. You could grab the bz2 archives and try to execute them manually or check if all libraries they are linked against are available on your system.

I will check if I can find the source code for theses binaries to properly integrate them into the build process instead of using pre-compiled ones.

**Comment by Hoshpak** [comment]
I've found the source for the binaries but to compile it, we would have to also install 32bit packages in the build environment so this is a no-go. For now I think I will revoke the noarch status of the package and restrict it to glibc intel architectures. #7328

**Comment by Hoshpak** [comment]
In case other people are interested in this: The source file is at https://github.com/PlayOnLinux/POL-POM-4/blob/master/src/check_direct_rendering.c . It uses libX11 and libGL to check if direct rendering is enabled.

**Comment by Anachron** [comment]
@Hoshpak that is a nice analyze!

That check_direct_rendering looks terrible. Why did they decide to use their own instead of letting wine handle the job?

Anyway, I guess I'll leave this open and see who else jumps in.

**Comment by Anachron** [comment]
I'm using Lutris for now, closing.
