### ISSUE TITLE
No setup information found for GHC

### ISSUE THREAD

**Issue by alexjacobson95** [void-linux/void-packages#7403]
### System
* xuname:  
  *Void 4.19.15_1 x86_64 GenuineIntel uptodate rmFFFFF*
* package:  
  *stack-1.9.3_1*

### Expected behavior
When running stack setup, I expect it to download ghc and other haskel tools.

### Actual behavior
$ stack setup
No setup information found for ghc-8.6.3 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-ncurses6'.
Supported versions: ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2

### Steps to reproduce the behavior
stack new test-project
cd test-project
stack setup

**Comment by alexjacobson95** [comment]
This also seems related: 
https://github.com/commercialhaskell/stack/issues/4034

**Comment by rektrex** [comment]
I too have the same problem. I have tried the potential solutions, including the correct solution in the [link](https://github.com/commercialhaskell/stack/issues/4034) in the previous comment.

**Comment by beta-phenylethylamine** [comment]
Also running into this issue, also on Void

**Comment by beta-phenylethylamine** [comment]
Linking `/usr/lib/libncurses.so.6.1` to `/usr/lib/libtinfo.so.6` seems to have fixed it for me

reading more, seems to possibly be an issue with ncurses packaging since tinfo (AFAICT) seems to be just the low-level interface to ncursus so the symlink is safe and valid?

**Comment by vinnyA3** [comment]
Thanks @beta-phenylethylamine for the helpful link.
In addition to linking `/usr/lib/libncurses.so.6.1` to `/usr/lib/libtinfo.so.6`, I also had to link `/usr/lib64/libgmp.so.10` to `/usr/lib64/libgmp.so` for ghc to work.  However, creating the symlinks seemed to way too hacky and terrible for maintenance (what happens if you get an update for libgmp?).  Ultimately, installing the `gmp-devel` package fixed the linking issue in a saner manner.

**Comment by CameronNemo** [comment]
@vinnyA3 sounds like a separate issue. please file a report.

**Comment by CameronNemo** [comment]
@beta-phenylethylamine is there a ticket with haskell / ghc sources?

**Comment by transitracer** [comment]
@CameronNemo sorry, not that I'm aware of. I'm currently poking around in different sources here and there to see if I can figure out whether the fault lies in stack or ghc itself. Will update when I sort it out

**Comment by transitracer** [comment]
Seems to be at the stackage level, in regards to generating bindists? 

The response is "most distros have standardised on either providing or linking libtinfo.so.6, so there's no bindists that link to ncurses6", so it seems the only solution for stackage compatibility is to change our ncurses packaging as suggested earlier, or somehow convince them to build generic ncurses6 bindists.

https://github.com/commercialhaskell/stack/issues/4711

**Comment by malyutinegor** [comment]
Any progress on this?

**Comment by malyutinegor** [comment]
If someone will need this: you can try to run `stack build --system-ghc`, on my machine it works

**Comment by mihaimaruseac** [comment]
That workaround keeps you using the GHC that void linux provides, but that might not be the newest one

**Comment by fuszenecker** [comment]
Same happens on Raspberry Pi 3:

```fuszenecker@raspberrypi:~ $ stack build
No setup information found for ghc-8.6.5 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux-armv7', 'linux-armv7-ncurses6', 'linux-armv7-tinfo6'.
Supported versions: ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2, ghInstalling GHC ...```

**Comment by transitracer** [comment]
@fuszenecker This is a separate issue of Stack not having a GHC 8.6.5 bindist for armv7, I believe. Stack seems to be detecting that you do indeed have libtinfo as indicated by `linux-armv7-tinfo6` being listed in the OS keys being searched for.

**Comment by MarleDK** [comment]
This should be fixed by installing `ncurses-libtinfo-libs` now, I will also look into making it a prerequisite for stack. If it does not break something else. 
See #21409

**Comment by slotThe** [comment]
Well, what about _making_ stack depend on `ncurses-libtinfo-libs`?  @MarleDK
