### ISSUE TITLE
`ibus-setup-hangul` requires python3-gobject

### ISSUE THREAD

**Issue by avoidr** [void-linux/void-packages#7415]
Same problem as #3156.

```
$ ibus-setup-hangul
Traceback (most recent call last):
  File "/usr/share/ibus-hangul/setup/main.py", line 23, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```

Package: `ibus-hangul-1.5.1_2`

**Comment by maxice8** [comment]
Can you test #7421 ?

**Comment by avoidr** [comment]
Yes, I will try. Thank you.

But why force python3? It wants to use python3 in the first place, and the solution for ibus-setup was to force it to use python2. Merely installing python3-gobject already works.

**Comment by maxice8** [comment]
On Sat, Jan 19, 2019 at 07:45:16AM -0800, avoidr wrote:
> Yes, I will try. Thank you.
> 
> But why force python3? It wants to use python3 in the first place, and the solution for ibus-setup was to force it to use python2. Merely installing python3-gobject already works.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/7415#issuecomment-455790916

It actually didn't, it used /usr/bin/python which by default was python3, if you modified your /usr/bin/python symlink with xbps-alternatives to python2 then it would work with python-gobject.

I think it is worthwhile to make stuff work with python3 by default.

**Comment by avoidr** [comment]
>I think it is worthwhile to make stuff work with python3 by default.

That's why I was confused why ibus-setup was forced to use python2.

Your patch works, thank you!
