### ISSUE TITLE
anki does not display anything

### ISSUE THREAD

**Issue by avoidr** [void-linux/void-packages#7416]
I don't know where the problem is, and I don't know where to report it upstream (found no contact anywhere and issues on its repo are disabled), but anki is dysfunctional for me.

I already recently had reinstalled the whole system and the problem didn't change.

```
$ anki
qt: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-user'
qt: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-user'
webview proxy use disabled
```

xuname: `Void 4.19.14_1 x86_64-musl AuthenticAMD uptodate rF`
Package: `anki-2.1.8_1`

**Comment by avoidr** [comment]
[Here is how it looks](https://ibb.co/gmskWCF)

**Comment by benalb** [comment]
Do not know if it will help, I do not use anki, but with other programs using Qt (specifically with qutebrowser) deleting the qtshadercache dir in ~/.cache would fix the problem.

**Comment by avoidr** [comment]
Thank you for your suggestion, but I don't even have that directory.

**Comment by CameronNemo** [comment]
I am unable to reproduce! With and without XDG_RUNTIME_DIR set...

**Comment by avoidr** [comment]
That's strange and unfortunate. It must have something to do with musl, then, maybe?

**Comment by Johnnynator** [comment]
> That's strange and unfortunate. It must have something to do with musl, then, maybe?

Yes, qt5-webview is broken currently on musl.

**Comment by avoidr** [comment]
While getting anki to run in a glibc-chroot, I found that it won't start without dbus installed. It tries to access `/var/lib/dbus/machine-id`.

**Comment by CameronNemo** [comment]
You may be able to get by by just copying the file over...

**Comment by avoidr** [comment]
That's not the problem though. Just noticing it seems to be a dependency, but it's not in the template. It's unrelated to the original problem.

It will also refuse to be run as root. Just taking notes.

**Comment by sud7535** [comment]
I am facing the similar issue. Has anyone found any fix yet?

**Comment by PaperMountainStudio** [comment]
I am not able to reproduce this on musl.

**Comment by avoidr** [comment]
I couldn't even run it this time. Some missing qt library. I guess this template is incomplete. I'll look again once FF unbreaks (they share a library).

Thanks for the update, @PaperMountainStudio!

**Comment by PaperMountainStudio** [comment]
In the meantime, you can use flatpak.

**Comment by PaperMountainStudio** [comment]
Hmm, I tried this in a VM with only xorg, st and dwm. And still I can't replicate it.

**Comment by avoidr** [comment]
Hey, it seems to work now! Awesome!
@PaperMountainStudio, thanks for reminding me.
