### ISSUE TITLE
caps: cannot be loaded because of undefined symbol

### ISSUE THREAD

**Issue by joshuakraemer** [void-linux/void-packages#7436]
### System

* xuname:  Void 4.19.16_1 x86_64 GenuineIntel uptodate rrrrmmnFFFFF
* package:  caps-0.9.26_1

### Description of the issue

If I try to use the caps Eq10 equalizer with alsaequal, I get the following error message:

`Failed to load plugin "/usr/lib/ladspa/caps.so": /usr/lib/ladspa/caps.so: undefined symbol: __gxx_personality_v0`

Maybe it is not compiled with g++? If I compile and install caps manually (make && sudo make install), it works as expected.

### Steps to reproduce the behavior

1. Install alsa and alsaequal (https://github.com/bassdr/alsaequal)
2. Create an alsaequal device in ~/.asoundrc:
```
pcm {
	equalizer {
		type equal
		library "/usr/lib/ladspa/caps.so"
		slave {
			pcm "plughw:0,0"
		}
	}
}

```
3. Play something on the equalizer device: `speaker-test -D equalizer`

**Comment by maxice8** [comment]
Should be fixed by the new caps update, we compiled with $CC which disabled the CXX extension __gxx_personality_v0
