### ISSUE TITLE
Package Fix: PHP and PHP-Devel packages

### ISSUE THREAD

**Issue by The-BigDaddy** [void-linux/void-packages#745]
**xuname:** Void 4.16.14_1 x86_64 GenuineIntel notuptodate rrrmF
**current package(s) and version(s):** php: 7.2.7_1; php-devel: 7.2.7_1

So I somewhat mentioned this already: [#590](https://github.com/void-linux/void-packages/issues/590)

When ever you try running `php` (version 7.2.7_1) with anything, you'll get

    PHP Warning:  stream_wrapper_register(): class 'PHP_Archive' is undefined in /usr/bin/phar.phar on line 6
    PHP Warning:  include(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in /usr/bin/phar.phar on line 9
    PHP Warning:  include(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in /usr/bin/phar.phar on line 9
    PHP Warning:  include(phar:///usr/bin/phar.phar/phar.inc): failed to open stream: No such file or directory in /usr/bin/phar.phar on line 9
    PHP Warning:  include(): Failed opening 'phar:///usr/bin/phar.phar/phar.inc' for inclusion (include_path='.:/usr/share/pear') in /usr/bin/phar.phar on line 9
    Neither Extension Phar nor class PHP_Archive are available.

I've tried seeing if there's anything I need to do in the `/etc/php/php.ini` file; nothing.

Tried seeing if there's a specfic module missing; nothing. 

Looking in the file, the warnings are mentioning these lines:

```
#!/usr/bin/php
<?php if (!class_exists('PHP_Archive')) {
?><?php
}
if (!in_array('phar', stream_get_wrappers())) {
	stream_wrapper_register('phar', 'PHP_Archive');
}
if (!class_exists('Phar',0)) {
	include 'phar://'.__FILE__.'/phar.inc';
}
?><?php

/** @file phar.php
 * @ingroup Phar
 * @brief class CLICommand
 * @author  Marcus Boerger
 * @date    2007 - 2008
 *
 * Phar Command
 */

if (!extension_loaded('phar'))
{
	if (!class_exists('PHP_Archive', 0)) {
		echo "Neither Extension Phar nor class PHP_Archive are available.\n";
		exit(1);
	}
	if (!in_array('phar', stream_get_wrappers())) {
		stream_wrapper_register('phar', 'PHP_Archive');
	}
	if (!class_exists('Phar',0)) {
		require 'phar://'.__FILE__.'/phar.inc';
	}
}
```
I'm assuming (I wouldn't really know) that the php package was built from source...but...without enabling PHAR? Or that this "phar.inc" file is placed somewhere that isn't being referred to in this script, or doesn't actually exist because of...something. A fix would be appreciated.

**Comment by The-BigDaddy** [comment]
Found [this](https://secure.php.net/manual/en/phar.installation.php) in the PHP manual.

> The Phar extension is bundled with PHP as of PHP version 5.3.0, and enabled by default. To disable Phar support, use --disable-phar .

And then 

> Phar may be installed via the PECL extension with previous PHP versions, and the » Phar PECL page contains further information and history. 

So I guess for now I can manually install Phar with PECL, but I'm not sure why it seems like it was specficially left out of the PHP Void package...

**Comment by Piraty** [comment]
nothing wrong with php's config regarding phar, see https://github.com/void-linux/void-packages/blob/master/srcpkgs/php/template#L47

Also, you mention
> When ever you try running php (version 7.2.7_1) with anything, you'll get <...>

Which is very vague... ("with anything", what does that even mean?)

This works as expected from my home folder:
``` 
echo "<?php echo 'This should be printed\n'; ?>" | php
```

I must say this bug report is not helpful if you don't provide steps to reproduce your issue, please provide such commands to replicate the behaviour.

**Comment by The-BigDaddy** [comment]
@Piraty 

"with anything" was indeed not helpful.

This all started with when I was trying to install Composer. The error regarding PHAR was exactly as shown

    PHP Warning:  stream_wrapper_register(): class 'PHP_Archive' is undefined in /usr/bin/phar.phar on line 6
    PHP Warning:  include(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in /usr/bin/phar.phar on line 9
    PHP Warning:  include(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in /usr/bin/phar.phar on line 9
    PHP Warning:  include(phar:///usr/bin/phar.phar/phar.inc): failed to open stream: No such file or directory in /usr/bin/phar.phar on line 9
    PHP Warning:  include(): Failed opening 'phar:///usr/bin/phar.phar/phar.inc' for inclusion (include_path='.:/usr/share/pear') in /usr/bin/phar.phar on line 9
    Neither Extension Phar nor class PHP_Archive are available.

While the argument to enable PHAR with PHP was passed, in order to enable Phar and be able to use it one needs to add the line `extension=phar` to `/etc/php/php.ini`. Then in order to install any third-party extensions (like PHPUnit, Phan, Psalms, Psysh, etc), or to install Composer, to directories like `/usr/local/bin` one needs to add that path to the `openbase_dir` variable in `/etc/php/php.ini`, like so 

    open_basedir = /srv/www/:/home/:/tmp/:/usr/share/pear/:/usr/loca/bin/:/usr/share/webapps/

I don't have any PHP extensions in `/usr/local/bin` aside from Composer, every extension is in my users home directory inside another directory where only I can execute it, or in `~/.config/composer/vendor/bin` if I passed `global` to composer. Running `composer [require, install]` will still toss a warning saying X directory isn't apart of `open_basedir`, but if you're using composer to have anything be somewhere under `/home/your_user/` it will still work normally.

In regards to PHAR; the `php` command works, but if PHAR is needed you have to enable it as an extension in your `/etc/php/php.ini`, even though it's supposedly "built-in" when passing `--enable-phar`, according to the PHP manual.

**Comment by maxice8** [comment]
So add it to /etc/php/php.ini , we won't touch stuff in conf_files automagically.
