### ISSUE TITLE
autofs undefined symbol error

### ISSUE THREAD

**Issue by xaltsc** [void-linux/void-packages#7473]
This error was reported on the old repo, and is still relevant in 2019.

Folks at NixOS seem to have find a patch, in the second referenced issue.

https://github.com/voidlinux/void-packages/issues/7615

https://github.com/NixOS/nixpkgs/issues/28282

Exeriencing the issue on Raspberry Pi 3 (aarch64) with autofs 5.1.4_1.

Output of `xbps-query autofs`:

```
> xbps-query autofs
architecture: aarch64
build-date: 2017-12-28 15:29 CET
conf_files:
	/etc/autofs/auto.master
	/etc/autofs/auto.misc
	/etc/autofs/auto.net
	/etc/autofs/auto.smb
	/etc/autofs/autofs.conf
	/etc/autofs/autofs_ldap_auth.conf
filename-sha256: 4fa787f84f913e93f66cfd5a1aaeb6b72a8ff2a4eda977a2d10a56ae81efaa44
filename-size: 386KB
homepage: https://www.kernel.org/pub/linux/daemons/autofs
install-date: 2019-01-20 14:43 UTC
installed_size: 2761KB
license: GPL-2
maintainer: Juan RP <xtraeme@voidlinux.eu>
metafile-sha256: c3f7b1fe18e3a26ca1ce7e443942b06aa1640f5e2f4cc166435485e469fe4dab
pkgver: autofs-5.1.4_1
repository: https://alpha.de.repo.voidlinux.org/current/aarch64
shlib-requires:
	libpthread.so.0
	libc.so.6
	ld-linux-aarch64.so.1
	libtirpc.so.3
	libnsl.so.1
	libldap-2.4.so.2
	liblber-2.4.so.2
	libresolv.so.2
	libxml2.so.2
	libsasl2.so.3
	libkrb5.so.3
	libdl.so.2
short_desc: A kernel-based automounter for Linux
source-revisions: autofs:606a58e4b8
state: installed
```

**Comment by Hoshpak** [comment]
Please add the version of the autofs package and the architecture you are experiencing the issue on.

**Comment by xaltsc** [comment]
Updated.

**Comment by Hoshpak** [comment]
The package is outdated because `tevent` is set nocross so the builders can't cross-compile the package any more. The current version is `autofs-5.1.5_1`. Could you maybe try to build the current version locally and see if it still has the issue?

**Comment by Hoshpak** [comment]
Actually getting the package to cross-compile again was rather easy. You can now pull the current version from the repository to test if it still is affected by the issue.

**Comment by Hoshpak** [comment]
So just to ensure I unbderstand correctly, this is with version `autofs-5.1.5_1`?

**Comment by xaltsc** [comment]
Yes

**Comment by Hoshpak** [comment]
Thanks, I'm currently looking into it further. It is a bit difficult for me since I don't have a system to test it on (it works fine on i686 and x86_64).

**Comment by xaltsc** [comment]
Yes it works for me as well on my main computer.
I will try in the evening the fix proposed on the NixOS issue if I find the time.

**Comment by Hoshpak** [comment]
@xsaltc I merged the PR. Please update the package and confirm if the issue is fixed for you.

**Comment by xaltsc** [comment]
The issue is fixed with this, thanks!

On a side note, whatever the architecture may be, the package is shipped with bad defaults: conf files are not coherent and the service does not use the provided auto.master.
