### ISSUE TITLE
linux4.19: missing module nct6683

### ISSUE THREAD

**Issue by dezifit** [void-linux/void-packages#7475]
I'm missing this driver for the hardware monitoring functionality of my MB. Any special reason why it isn't enabled in the default kernel config?

**Comment by Hoshpak** [comment]
probably just an oversight. What kind of MB is it so on which CPU architectures would the module be needed? Currently it's only enabled for aarch64 (assuming we're talking about `CONFIG_SENSORS_NCT6683`).

**Comment by dezifit** [comment]
It's an Intel MB (Haswell generation) used with arch  i686 and x86_64. lm-sensors has detected a Nuvoton NCT6683D (yes, CONFIG_SENSORS_NCT6683).
