### ISSUE TITLE
Bump gstreamer to 1.15.1

### ISSUE THREAD

**Issue by luzpaz** [void-linux/void-packages#7517]
https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.15.1.tar.xz
https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.15.1.tar.xz.sha256sum

https://github.com/void-linux/void-packages/tree/master/srcpkgs/gstreamer1

**Comment by Hoshpak** [comment]
we only package stable releases.
