### ISSUE TITLE
Package Request: Wayfire

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [void-linux/void-packages#7521]
https://github.com/WayfireWM/wayfire

> Wayfire is a wayland compositor based on wlroots. It aims to create a customizable, extendable and lightweight environment without sacrificing its appearance.

**Comment by youngjinpark20** [comment]
working on

**Comment by youngjinpark20** [comment]
I'ma wait just a little longer until wlroots 0.3 comes out as that has the library that is needed for wayfire.

**Comment by AlmightyFloppyFish** [comment]
@youngjinpark20 I assume this is why I've had so much trouble getting it to build?

**Comment by youngjinpark20** [comment]
Yeah, you need an include header that's not yet in the release version of wlroots

**Comment by AlmightyFloppyFish** [comment]
@youngjinpark20 
Good news, wlroots 3.1 is now in the void repos. Bad news? I'm unable to build wayfire with it, maybe you could give it a try? First I'm getting "Dependency wlroots found: NO (tried pkgconfig and cmake)" and if i manually specify PKG_CONFIG_PATH to the folder where wlroots.pc is i just get "Dependency wlroots found: NO (tried cmake)" (same but with the "tried pkgconfig" part removed)

**Comment by youngjinpark20** [comment]
I've got it packaged, however there seems to be a bug within the source
itself because the source depends on systemd-logind. I don't have the time
right now to look into it but I'm on it.

**Comment by AlmightyFloppyFish** [comment]
The source shouldn't depend on systemd-login if you have elogind installed

**Comment by youngjinpark20** [comment]
You're right, it works with elogind. I didn't add it as a dependency but as a recommendation in the INSTALL.msg https://github.com/void-linux/void-packages/pull/8474
