### ISSUE TITLE
btrfs-progs update broke snapper

### ISSUE THREAD

**Issue by sww1235** [void-linux/void-packages#7540]
it looks like the 4.20 version of btrfs-progs that was pushed in commit 43a3d9e3b1b00e98584c1254eb65b19a73c79930 broke snapper. I just updated and now am getting errors about missing symbols in /lib/libbtrfs.so.0 whenever I run snapper.

It looks like opensuse is still on 4.19: https://software.opensuse.org/package/btrfsprogs

Is there any way we can verify that snapper works with a upgraded version of btrfs?

**Comment by maxice8** [comment]
reverted to 4.19.1

**Comment by sww1235** [comment]
thanks maxice

**Comment by maxice8** [comment]
On Mon, Jan 21, 2019 at 06:10:42PM -0800, Stephen Walker-Weinshenker wrote:
> thanks maxice
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/7540#issuecomment-456246785

don't forget the 8, it is very important

**Comment by prspkt** [comment]
> it looks like the 4.20 version of btrfs-progs that was pushed in commit [43a3d9e](https://github.com/void-linux/void-packages/commit/43a3d9e3b1b00e98584c1254eb65b19a73c79930) broke snapper. I just updated and now am getting errors about missing symbols in /lib/libbtrfs.so.0 whenever I run snapper.
> 
> It looks like opensuse is still on 4.19: https://software.opensuse.org/package/btrfsprogs
> 
> Is there any way we can verify that snapper works with a upgraded version of btrfs?

Sorry about that, although i use btrfs i don't use snapper to manage snapshots.

**Comment by sww1235** [comment]
no problem. I blame opensuse 😛
