### ISSUE TITLE
Problem with gcc-ada calling function not in musl

### ISSUE THREAD

**Issue by dachshund7** [void-linux/void-packages#7541]
### System

* xuname:  
  Void 4.19.16_2 x86_64-musl AuthenticAMD uptodate rrnFFF
* package:  
  gcc-ada-8.2.0_8

I was trying to compile gprbuild, and I ran into the same problem Alpine Linux did with this [bug](https://bugs.alpinelinux.org/issues/9389).

```sh
$ ld -lgnarl-8 -lgnat-8
ld: warning: cannot find entry symbol _start; not setting start address
ld: /lib/libgnarl-8.so: undefined reference to `pthread_mutexattr_setprioceiling'
ld: /lib/libgnarl-8.so: undefined reference to `pthread_rwlockattr_setkind_np'
```

Could we adopt their [patch](https://github.com/alpinelinux/aports/pull/5642) to fix things?

**Comment by pullmoll** [comment]
7ecbe5d902a38c03f14d338fe43a0b083b40d116
