### ISSUE TITLE
speedcrunch: depends on qt5-tools (clang)

### ISSUE THREAD

**Issue by dezifit** [void-linux/void-packages#7561]
### System

* xuname:  
  Void 4.19.12_1 x86_64 GenuineIntel
* package: 
  speedcrunch (0.12.0_1) -> libQt5Help.so -> qt5-tools (5.11.3_3) -> clang

### Expected behavior
Installation of a desktop calculator should not require installation of a compiler infrastructure.

### Actual behavior
Runtime package for desktop calculator depends on 380MB development environment.

### Steps to reproduce the behavior
xbps-query -X speedcrunch

Related to https://github.com/void-linux/void-packages/issues/6286

**Comment by Johnnynator** [comment]
See #6949 for discussion.

**Comment by Johnnynator** [comment]
Not an issue anymore since libclang was split out of clang.
