### ISSUE TITLE
Package request: Iridium Browser

### ISSUE THREAD

**Issue by jcgruenhage** [void-linux/void-packages#7562]
Iridium Browser is a fork of chromium that does not rely on libraries with questionable license situations and patches a lot of privacy issues of chromium. See https://iridiumbrowser.de/

**Comment by Hoshpak** [comment]
it's not quite dead yet just slow to publish releases but it's the same situation as with other Chromium or Firefox forks.

**Comment by Cogitri** [comment]
Eh, for browsers a 3 month release window is dead to me. It's regularly lagging multiple major releases behind upstream Chromium which (IMO) is unacceptable for something as security critical (and vulnerable) as a browser.

**Comment by jcgruenhage** [comment]
Okay. Thanks for the feedback!
