### ISSUE TITLE
GCC plugins again?

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#7588]
I just now wondered when after updating my laptops failed to build some DKMS for their WLAN adapters: didn't we have GCC plugins disabled for the kernels? As it is, building e.g. broadcom-wl-dkms is failing after the gcc update.

**Comment by jnbr** [comment]
there were plans to disable them but it never happened

**Comment by pullmoll** [comment]
Obviously ;-P IMO it's a bad idea to keep them because it will regularly break user's systems the way it is now. You cannot have a modular update of gcc and kernels at the same time, there's always some time gap...

**Comment by PB-repo** [comment]
After update nvidia-dkms building failed.
