### ISSUE TITLE
Update pivy to 0.6.4

### ISSUE THREAD

**Issue by luzpaz** [void-linux/void-packages#7609]
https://bitbucket.org/Coin3D/pivy/downloads/?tab=tags
https://bitbucket.org/Coin3D/pivy/commits/a84100beff22
https://bitbucket.org/Coin3D/pivy/get/0.6.4.tar.gz

https://github.com/void-linux/void-packages/tree/master/srcpkgs/python-pivy

**Comment by maxice8** [comment]
Fixed update-check, please open a PR updating it
