### ISSUE TITLE
Package request: blueberry

### ISSUE THREAD

**Issue by dawidpotocki** [void-linux/void-packages#7636]
"Official" bluetooth manager for cinnamon desktop. It is really simple, nice application and I kinda miss it on Void.

https://github.com/linuxmint/blueberry

> A Bluetooth configuration tool. Depends on gnome-bluetooth 3.14.

**Comment by Cogitri** [comment]
Will look into it today.

**Comment by Cogitri** [comment]
Nevermind, its build system is basically nonexistent and it needs https://github.com/khvzak/bluez-tools which doesn't have a tagged release and is abandoned.

**Comment by Cogitri** [comment]
FWIW, here's a template for it, but you'll have to install bluez-tools yourself. https://gist.github.com/124af25218af231757f5e2747013d836
