### ISSUE TITLE
ZFS packaging issue

### ISSUE THREAD

**Issue by ndowens** [void-linux/void-packages#7643]
### System

* xuname:  
Void 4.19.16_2 x86_64 GenuineIntel uptodate rFFFFFFF
* package:  
zfs-0.7.12

### Expected behavior
zfs packaging to not give error
### Actual behavior
https://pastebin.com/erPJZtkL
### Steps to reproduce the behavior
./xbps-src pkg zfs

@Vaelatern

**Comment by Vaelatern** [comment]
This is a known issue with upstream. We can't move the files.

@q66 how did you work around the problem for now?

**Comment by q66** [comment]
I did not; I decided to wait for next release, where they changed the build system stuff so that it can be patched in a simple manner; I did not find enough time to look into fixing it right now.

**Comment by Vaelatern** [comment]
Let's wait then.

**Comment by ndowens** [comment]
Ah, sorry didn't know this was a known issue.

**Comment by jnbr** [comment]
workaround in 3af1c02801f44176842cc340912b9b79267d3fe5
