### ISSUE TITLE
Package request: Transmission

### ISSUE THREAD

**Issue by theBusterben** [void-linux/void-packages#768]
i kindly like to request transmission , gnome 3 styled
how it looks like:
 [transmission-gtk](https://i.imgur.com/SzGeUil.png) -> [transmission-csd](https://i.redd.it/7o997shzjxjx.jpg)

<del>[source link](https://github.com/derekstavis/transmission/)<del>

**Comment by Johnnynator** [comment]
https://github.com/transmission/transmission/tree/wip/gtk-3.14
^ This would be the up to date one. Also I personally would wait until it gets relased before packaging it.

**Comment by theBusterben** [comment]
thanks Johnny for providing the link. gotcha. ill wait then seeing its up in the official github
