### ISSUE TITLE
More sndio support

### ISSUE THREAD

**Issue by Kistelini** [void-linux/void-packages#7707]
Most packages with upstream sndio support already have it enabled in Void, but a lot of packages don't support sndio by default. I'd like to port some patches from OpenBSD's ports tree to Void, but don't want to work on that if they can't be included.

Do we want (nearly) full sndio support in Void Linux?

**Comment by Kistelini** [comment]
There's https://github.com/void-linux/void-packages/pull/5168 and https://github.com/void-linux/void-packages/pull/5160 for example. Most packages have sndio as an option which is enabled by default, maybe all packages should have sndio as an option so users can disable it.

**Comment by maxice8** [comment]
> Do we want (nearly) full sndio support in Void Linux?

Put it upstream, i'm not really keen on holding patches that are not upstream, it is more work.

**Comment by Kistelini** [comment]
I don't think they'll go upstream, SDL1 e.g. won't get any updates.
