### ISSUE TITLE
osg: update to 3.6.3

### ISSUE THREAD

**Issue by luzpaz** [void-linux/void-packages#7729]
https://github.com/openscenegraph/OpenSceneGraph/releases/tag/OpenSceneGraph-3.6.3  
https://github.com/void-linux/void-packages/tree/master/srcpkgs/osg

**Comment by Johnnynator** [comment]
Literally every dependency requires osg 3.4.x, so we can't update now.

**Comment by luzpaz** [comment]
Can you please create another port for 3.6.3 then ? (and just rename the ticket?)

**Comment by HadetTheUndying** [comment]
Is this still the case? It's been 2 years now. I tried packaging this myself as I need it to work with some VR stuff and it fails to build.
