### ISSUE TITLE
package request: fbpanel

### ISSUE THREAD

**Issue by aGaTHoS** [void-linux/void-packages#7766]
http://aanatoly.github.io/fbpanel/

fbpanel is a lightweight, NETWM compliant desktop panel. It works with any NETWM compliant window manager (eg xfwm4, sawfish, openbox, metacity, kde wm )

**Comment by ndowens** [comment]
Tried to package this, but there is build issues with it

**Comment by aGaTHoS** [comment]
the aur package from archlinux seems quite straightforward

**Comment by Anachron** [comment]
Arch Linux doesn‘t compile for musl and ARM though.

**Comment by aGaTHoS** [comment]
but im not using arm nor musl with void

**Comment by Hoshpak** [comment]
Then you are free to compile fbpanel yourself any time. Packages added to the repository are held to a somewhat higher standard.

**Comment by philipgg** [comment]
https://github.com/philipgg/void-packages/blob/fbpanel/srcpkgs/fbpanel/template

@aGaTHoS how about this template?

**Comment by biopsin** [comment]
Is this still interesting, there are other panel/bar in repo that are maintained and just as customizeble,
this one has not seen updates in 6 years..

**Comment by ericonr** [comment]
It's also GTK 2 only, which is not an option for us. Closing.
