### ISSUE TITLE
[FTBFS] Qemu: firmware files in /usr/share

### ISSUE THREAD

**Issue by youngjinpark20** [void-linux/void-packages#7777]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *affected package(s) including the version*

### Expected behavior
- smbd support
- build

### Actual behavior
- No smbd support
- Doesn't build

### Steps to reproduce the behavior
- either just try to build qemu
- add the --smbd line and build

Doesn't build because of new post-install 11 hook that screens for ELF binaries in /usr/share

**Comment by youngjinpark20** [comment]
Even though it *is* really bad practice to put ELF files in `/usr/share`, I think maybe having a `skip_elf` option or something like that might be nice to fix packages in the meantime.

**Comment by Hoshpak** [comment]
@maxice8 what would be the proper path to put foreign-arch firmware files into?

**Comment by youngjinpark20** [comment]
Oh and I realize that the reason that smbd wasn't working is that samba haven't been updated in a while...
