### ISSUE TITLE
Firefox + alsa = trouble

### ISSUE THREAD

**Issue by grapeli** [void-linux/void-packages#7889]
No sound especially when decoding streams with the "properiaty" aac codec.
https://www.olympicchannel.com/en/video/detail/yuzuru-hanyu-performs-to-chopin-s-ballade-no-1-music-mondays/
https://cdn.index.hm/f/rHkX0jIzMjFlMWM4ZjMyY/10.wav.aac
After installing pulseaudio, everything plays as it should.

Maybe it's time to consider pulseaudio as a necessary package when installing firefox. It saves time and nerves for many users. It would be best to extract libpulse from the pulseaudio package. As it is in Arch Linux.
https://www.archlinux.org/packages/extra/x86_64/libpulse/

**Comment by Kistelini** [comment]
Firefox works fine with jack and sndio, too. There's already a package for the library only, it's called `libpulseaudio` in Void.

**Comment by grapeli** [comment]
I had the libpulseaudio installed  (I did not even know about it). Alone is not enough. Unfortunately pulseaudio is needed. Apulse does not help either.
I have not tested sndio and jack. These are generally layers as unnecessary to me as pulsaudio.

I get such messages with alsa.
[Child 519, MediaPlayback #1] WARNING: 9a3ffaf0 OpenCubeb() failed to init cubeb: file /builddir/firefox-64.0.2/dom/media/AudioStream.cpp, line 397
[Child 519, MediaPlayback #1] WARNING: Decoder=9bedec10 [OnMediaSinkAudioError]: file /builddir/firefox-64.0.2/dom/media/MediaDecoderStateMachine.cpp, line 3793
[Child 519, MediaPlayback #1] WARNING: Decoder=9bedec10 Decode error: NS_ERROR_DOM_MEDIA_MEDIASINK_ERR (0x806e000b) - OnMediaSinkAudioError: file /builddir/firefox-64.0.2/dom/media/MediaDecoderStateMachine.cpp, line 3434

**Comment by Anachron** [comment]
Must be specific to your setup then, I use sndio with firefox and alsa (no pulse) and it works here.

**Comment by grapeli** [comment]
It's possible that there is a problem with my configuration. Although I can not diagnose in any way. Firefox running only with alsa under Arch Linux (x86_64) works completely properly. In the case of Void Linux (i686), the problems with the lack of sound on many pages have begun from version 59 or 60 (I do not remember exactly, they were initially associated with a sandbox).

The first thing that caught my attention after the pulseaudio installation is that youtube playback has stopped being smooth. My equipment has a very small power reserve. I do not want a pulse.

The first attempt to integrate sndio did not bring success.

**Comment by grapeli** [comment]
The topic can be closed. Problem solved. Firefox did not like my .asoundrc.

pcm.dmix0 {
    type dmix
    ipc_key 673138
    ipc_key_add_uid true
    slave {
        pcm "hw:0,0"
        rate 48000
        period_time 0
        period_size 4096
        buffer_size 32768
    }
    bindings {
        0 0
        1 1
    }
}
cat /proc/asound/cards
0 [VT82xx         ]: HDA-Intel - HDA VIA VT82xx
cat /proc/asound/pcm
00-00: ALC260 Analog : ALC260 Analog : playback 1 : capture 1
