### ISSUE TITLE
Package Request: solvespace 

### ISSUE THREAD

**Issue by imrn** [void-linux/void-packages#8037]
Solvespace is an ultra compact and handy parametric CAD
software which helps keeping the CAD model consistent via
contraints while it is being modified/developed.

**Homepage**
http://solvespace.com
https://github.com/solvespace/solvespace

**Package on other linux distributions**
https://aur.archlinux.org/packages/solvespace/ v2.3
https://aur.archlinux.org/packages/solvespace-git/
https://packages.debian.org/sid/solvespace

**Other Notes**
Github page provides simple build directives.
I've compiled git version without any issues.

However, gui binary has the following problem on my system:
https://github.com/solvespace/solvespace/issues/374
We couldn't determine if it is specific to my system or
VoidLinux in general.

**Comment by bobertlo** [comment]
I'm really not liking the libdxfrw dependency from git. If there were a release I could pull and package, then maybe.

**Comment by imrn** [comment]
Latest official release is 2.3 and extracted debian package just works on voidlinux.
Does it of any help for an initial package on void?

**Comment by bobertlo** [comment]
I'm getting into some build issues with this now. I'm very bad at reading very angry C++ errors that overflow my scroll buffer. I may come back to this but I am out of time for now.

**Comment by imrn** [comment]
I've installed the package from repository and it works without any
issue. Thanks for the effort.

This is my first package request. Shall I close the issue now?

**Comment by bobertlo** [comment]
yes it seems to be resolved :)

**Comment by imrn** [comment]
Closing. And one more thing:
What is void's convention for updating a package to new
release version? Should I open an issue again?
