### ISSUE TITLE
protonmail-bridge

### ISSUE THREAD

**Issue by malankee** [void-linux/void-packages#8051]
#Package Request
 Sorry I'm new to void and am completely stuck. This is as far as i got and it of course won't compile. Notice the depend "ttf-dejavu" isn't in repos.

# Template file for 'protonmail-bridge'
pkgname=protonmail-bridge 1.1.0.1-1
version=
revision=1
#wrksrc=
#create_wrksrc=yes
#only_for_archs="i686 x86_64"
build_style=gnu-configure
#configure_args=""
#make_build_args=""
#make_install_args=""
#conf_files=""
#make_dirs="/var/log/dir 0755 root root"
#hostmakedepends=""
#makedepends=""
depends="libsecret, gnome-keyring, gt5-svg, qt5-declarative, qt5-multimedia, ttf-dejavu"
short_desc="Application to use Imap/SMTP with your paid ProtonMail account"
maintainer=""
license="GPL-3.0-or-later"
homepage="https://protonmail.com/bridge/"
distfiles="https://protonmail.com/download/protonmail-bridge_1.1.0.1-1_amd64.deb"
checksum=

1.1.0.1-1_package() {
	pkg_install() {
		#vmove path
	}
}

**Comment by bobertlo** [comment]
You're trying to use a deb file, which is a binary package for a different distribution.

This appears to be a closed source program also.

**Comment by malankee** [comment]
OK thanks for your time. It is possible to compile it for the AUR though.

**Comment by Cogitri** [comment]
Yeah, I'm not sure if we're really allowed to redistribute this though

**Comment by bobertlo** [comment]
I found the eula, it's not redistributable.

**Comment by Cogitri** [comment]
Figured so.

We have https://github.com/void-linux/void-packages/blob/3e6a6f200a805782a0b47dccfac5d69a0c737d94/srcpkgs/hydroxide/template though if that works for you, @malankee

**Comment by malankee** [comment]
That's fine and thanks for your time. I'll give hydroxide a try.
