### ISSUE TITLE
Firefox and Qutebrowser segfault at start

### ISSUE THREAD

**Issue by maciozo** [void-linux/void-packages#8081]
### System

* xuname:  
  ```
    dmesg: read kernel buffer failed: No such file or directory
    Void 4.19.19_1 x86_64-musl GenuineIntel uptodate rF
    ```
* package:  
  * firefox-65.0_1
  * qutebrowser-1.5.2_1

### Expected behavior
Running `firefox` or `qutebrowser` should start the respective browsers.

### Actual behavior
Near-immediate segmentation fault

### Steps to reproduce the behavior
1. Install `firefox` or `qutebrowser`
2. Run `firefox` or `qutebrowser`

Chromium runs fine.
Changing the stack size, as suggested by @Johnnynator using `sudo chelf -s 1048576 /usr/lib/firefox/firefox` seems to fix the issue, but is not a suitable permanent solution.

**Comment by Johnnynator** [comment]
This should be resolved by https://github.com/void-linux/void-packages/commit/f970f7dbd85f9ae8ce0612990a08c6659e26f4b0
@maciozo Can you verify that Firefox and qutebrowser no work without using chelf ( just reinstall them with `xbps-install -f` if they are modified)

**Comment by Johnnynator** [comment]
Sry I forget, qt5-webengine is borked either way on musl and not related to the firefox issue. #2368

**Comment by stef** [comment]
i mananged to fix this on alpine linux using this: https://github.com/alpinelinux/aports/pull/11922
