### ISSUE TITLE
Package request: Guake

### ISSUE THREAD

**Issue by Vlad-Romanov** [void-linux/void-packages#809]
Re-creating package request for Guake created by guilmm
https://github.com/voidlinux/void-packages/issues/13295

"Guake is a drop-down terminal for GNOME.

http://guake-project.org/
https://github.com/Guake/guake

Thanks!"

It appear that GUAKE work with simple make && make install on Void MUSL but no GLIBC...

This is latest template that is posted to original thread, with a bit of updating.

#Template file for 'guake'
pkgname=guake
version=3.3.0
revision=1
build_style=python3-module
hostmakedepends="python3-setuptools python3-pbr python3-pip"
makedepends="python3-devel"
#checkdepends="flake8 python3-pylint"
checkdepends="python3-flake8 python3-pylint python3-pytest"
noarch="yes"
depends="python3 python3-cairo python3-dbus python3-gobject gtk+3 libkeybinder3"
pycompile_module="$pkgname"
short_desc="Drop-down terminal for GNOME"
maintainer=""
license="GPL-2"
homepage="http://guake-project.org/"
distfiles="https://github.com/${pkgname}/${pkgname}/archive/${version}.tar.gz"
checksum=36447cd32daf4cb74ac4ebec386d20b659f02e5c7d66315b1078f6da2b894cfd

pre_build() {
	pip3 install pipenv
	pip3 install pipenv_to_requirements
}

do_build() {
	make build
}

do_install() {
	make install prefix="/usr/" COMPILE_SCHEMA=0
}

do_check() {
	make test
}

**Comment by Vlad-Romanov** [comment]
`#Template file for 'guake'
pkgname=guake
version=3.3.0
revision=1
build_style=python3-module
hostmakedepends="python3-setuptools python3-pbr python3-pip"
makedepends="python3-devel"
#checkdepends="flake8 python3-pylint"
checkdepends="python3-flake8 python3-pylint python3-pytest"
noarch="yes"
depends="python3 python3-cairo python3-dbus python3-gobject gtk+3 libkeybinder3"
pycompile_module="$pkgname"
short_desc="Drop-down terminal for GNOME"
maintainer=""
license="GPL-2"
homepage="http://guake-project.org/"
distfiles="https://github.com/${pkgname}/${pkgname}/archive/${version}.tar.gz"
checksum=36447cd32daf4cb74ac4ebec386d20b659f02e5c7d66315b1078f6da2b894cfd

pre_build() {
	pip3 install pipenv
	pip3 install pipenv_to_requirements
}

do_build() {
	make build
}

do_install() {
	make install prefix="/usr/" COMPILE_SCHEMA=0
}

do_check() {
	make test
}`

**Comment by Johnnynator** [comment]
Pr is open now. It should work fine for both GLIBC and Musl.
