### ISSUE TITLE
Package Request: powerkit

### ISSUE THREAD

**Issue by imrn** [void-linux/void-packages#8093]
Powerkit is a lightweight desktop independent full featured power manager, originally created for Slackware 

https://github.com/rodlie/powerkit

https://slackbuilds.org/repository/14.2/system/powerkit/

**Comment by abenson** [comment]
It's only pre-release right now. I have a template built and it seems to work. I'll do some more testing, and when the project hits 1.0 *release* I'll submit the PR.

**Comment by CameronNemo** [comment]
@abenson you could push a commit with the template to your forked repo of void-packages, and write 'closes #8093' somewhere in the commit message. Then others can test it while we wait for a release.

**Comment by CameronNemo** [comment]
Bump. A release has been made.
