### ISSUE TITLE
./xbps-src binary-bootstrap doesn't use mirror

### ISSUE THREAD

**Issue by yjp20** [void-linux/void-packages#8125]
### System

* xuname:  
  * Void 4.20.6_1 x86_64 GenuineIntel notuptodate rrrmDDFFFFF

### Expected behavior
- Binary bootstrap should use mirrors defined in the repos-local configuration

### Actual behavior
- Binary bootstrap uses repositories from XBPS_INSTALL_ARGS in defaults.conf

**Comment by bobertlo** [comment]
#8138

**Comment by xtraeme** [comment]
Fixed long ago, see `void-packages/etc/xbps.d/repo*`
