### ISSUE TITLE
Package request: Singularity

### ISSUE THREAD

**Issue by notramo** [void-linux/void-packages#8135]
https://www.sylabs.io/singularity/

**Comment by maxice8** [comment]
Template

```
# Template file for 'singularity'
pkgname=singularity
version=3.1.1
revision=1
wrksrc=singularity
build_style=go
go_import_path=github.com/sylabs/singularity
go_package="${go_import_path}/cmd/singularity"
short_desc="Application containers for Linux"
maintainer="maxice8 <thinkabit.ukim@gmail.com>"
license="BSD-3-Clause"
homepage="https://www.sylabs.io/singularity"
distfiles="https://github.com/sylabs/singularity/releases/download/v${version}/singularity-${version}.tar.gz"
checksum=7f0df46458d8894ba0c2071b0848895304ae6b1137d3d4630f1600ed8eddf1a4
```

**Comment by notramo** [comment]
@maxice8 Why isn't it a PR?

**Comment by notramo** [comment]
There is a working version, based on yours.
I'm not sure it is a correct template:
- Should `depends` contain the runtime versions of all `makedepends`?
- Singularity requires `/var/singularity/mnt/session` to exist in runtime. Should it be included in the package, or created in the install script?
Otherwise, it works. If the above two questions are solved, it could be packaged.
```bash
# Template file for 'singularity'
pkgname=singularity
version=3.2.0
revision=1
wrksrc=singularity
build_style=go
makedepends="gpgme-devel libressl-devel libuuid-devel libseccomp-devel pkg-config"
depends="gpgme squashfs-tools"
go_import_path=github.com/sylabs/singularity
go_package="${go_import_path}/cmd/singularity"
short_desc="Application containers for Linux"
maintainer="maxice8 <thinkabit.ukim@gmail.com>"
license="BSD-3-Clause"
homepage="https://www.sylabs.io/singularity"
distfiles="https://github.com/sylabs/singularity/releases/download/v${version}/singularity-${version}.tar.gz"
checksum=037e442c3e0e9d7999f83056deb659e9488f3b61ee2dc3358dcf66939b49deca

do_configure() {
  ./mconfig --sysconfdir=/etc --localstatedir=/var --runstatedir=/run --prefix=/usr
}

do_build() {
  cd builddir
  make
}

do_install() {
  cd builddir
  make DESTDIR=$DESTDIR install 

  mkdir -p $DESTDIR/usr/share/bash-completion/
  mv $DESTDIR/etc/bash_completion.d $DESTDIR/usr/share/bash-completion/completions

  # Singularity requires this directory to exist in runtime.
  mkdir -p $DESTDIR/var/singularity/mnt/session
}
```

**Comment by Chocimier** [comment]
> * Should `depends` contain the runtime versions of all `makedepends`?

No, xbps-src automatically adds packages of shared objects that are linked against, look for `generate-runtime-deps` in build log.

> * Singularity requires `/var/singularity/mnt/session` to exist in runtime. Should it be included in the package, or created in the install script?

`make_dirs` should be set as empty directories are removed during creating package.

**Comment by emi80** [comment]
Hi all, are there any news on this?

I am new to void and xbps and I was looking for a singularity package. I found this issue and, taking inspiration from the templates above, I managed to create a working package.

Can I submit a pull request and mention this issue from there? Of course I don't want to take over anybody. @maxice8, @notramo do you have any progress on this?

Thanks a lot

**Comment by maxice8** [comment]
I left void a long time ago

**Comment by notramo** [comment]
I don't use Singularity since a while ago, but I can try packaging it.
