### ISSUE TITLE
Package Request: acme-client

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#8141]
Homepage: https://github.com/onur/acme-client
>  Yet another Let's Encrypt client and library written in Rust. 

Name clashes with https://github.com/void-linux/void-packages/blob/7ad5eeb1e28cdc25c701f8d409d1513c05555596/srcpkgs/acme-client/template but since it's not developed anymore I thought we could slowly replace it? 

https://github.com/kristapsdz/acme-client-portable
> Attention acme-client-portable is no longer maintained. Since acme-client made its way into OpenBSD, I've only been using the base version.

**Comment by CameronNemo** [comment]
Unless the command has the same interface you should rename it and notify the developer of the conflict. acme-client-portable may become maintained again in the future.

**Comment by Anachron** [comment]
Closing in favor of #10588
