### ISSUE TITLE
Package request: Paraview

### ISSUE THREAD

**Issue by luzpaz** [void-linux/void-packages#8187]
**Parallel Visualization application using VTK**
Website: https://www.paraview.org  

> ParaView is an open-source, multi-platform data analysis and visualization application. ParaView users can quickly build visualizations to analyze their data using qualitative and quantitative techniques. The data exploration can be done interactively in 3D or programmatically using ParaView’s batch processing capabilities.

**Comment by abenson** [comment]
I was working on it, but I won't be able to proceed until [ipsc](https://github.com/void-linux/void-packages/commit/0c93507d8f79647c330331ec020eaed3b642b934) is fixed.

**Comment by biopsin** [comment]
@ericonr  https://github.com/void-linux/void-packages/pull/13879
Request merged a while ago

> // Erico, hope I'm not flooding you with these mop ups..
