### ISSUE TITLE
Can void-packages import existing pre-built binary toochain?

### ISSUE THREAD

**Issue by wuhanck** [void-linux/void-packages#8205]
Is it possible to import an existing pre-built binary toolchain, and use it to build the void-linux?

There are 3rd-party toolchains as linaro, Codesourcery or SOC-vendor(as hisi) provided binary toolchains.
These chains provide the sysroot and other features as the one built from GNU_SITE.

I have tried to fake install(using vinstall from FILES DIR) but it dosn't work...

Is it possible and where can I start?

**Comment by bobertlo** [comment]
I believe xbps-src is designed to only use canonical tool-chains. The reasoning for this is consistency. Each package is built inside a chroot, providing every dependency requested, as provided by void's packages, and *nothing else* to ensure a homogeneous build environment.

If you would like to build the void package templates in another environment, you are welcome to try, but it is not supported in this environment.

**Comment by wuhanck** [comment]
thank you for your info. @bobertlo 
I will check the layout of the toolchains and find some luck.
