### ISSUE TITLE
stale -dbg packages

### ISSUE THREAD

**Issue by jnbr** [void-linux/void-packages#8232]
These -dbg packaged are outdated and not needed anymore because their associated packages do not hold any binaries anymore. They should be removed from the debug repos.

- boost-dbg-1.68.0_3
- llvm-dbg-6.0.1_3
- readline-dbg-7.0.005_2

**Comment by Johnnynator** [comment]
Sry for highjacking this thread,
These two pacakges also net removal from the repos.
* firefox-esr-52.9.0_5.armv6l.xbps
* firefox-esr-52.9.0_5.armv6l-musl.xbps

Furthermore it seems that the musl repo does not clean itself.

**Comment by CameronNemo** [comment]
We should have a tracking ticket for this, or we could prune noarch debug packages somehow.

**Comment by CameronNemo** [comment]
Johnnynator, those are not dbg packages?

**Comment by Johnnynator** [comment]
Nope. just wanted to mention packages that also need manual removal

**Comment by jnbr** [comment]
I think those packages are cleaned from the repos now.
