### ISSUE TITLE
xbps-src does not translate XBPS_MASTERDIR in chroot stages

### ISSUE THREAD

**Issue by yopito** [void-linux/void-packages#8282]
### System

* xuname:  `Void 4.19.19_1 x86_64 GenuineIntel notuptodate rFF`
* package:  `xbps-src` tool

### Expected behavior
no error message on `binary-bootstrap` : `XBPS_MASTERDIR` should be recomputed in chroot mode.

### Actual behavior  and steps to reproduce

Version used:
```
$ git log -1 xbps-src  | grep -E "^commit|^Date"
commit 2e108ebfdf189e294d98cc8224230679cfea89d7
Date:   Tue Feb 5 12:40:59 2019 +0100
```

Let's clean and populate my mastedir:
```
$ ./xbps-src -m /build/packages/masterdir zap
[...]
Removing directory /build/packages/masterdir/builddir ...
Removing directory /build/packages/masterdir/destdir ...
/build/packages/masterdir masterdir cleaned up.

$ ./xbps-src  -m /build/packages/masterdir binary-bootstrap
[...]
=> xbps-src: cleaning up masterdir...
chmod: cannot access '/void-packages/masterdir/builddir': No such file or directory
```
=> mastedir has not been correctly "translated" in chroot mode

Same behaviour if `XBPS_MASTERDIR` is exported from shell:

```
$ export XBPS_MASTERDIR=/build/packages/masterdir
$ ./xbps-src zap
[...]
Removing directory /build/packages/masterdir/builddir ...
Removing directory /build/packages/masterdir/destdir ...
/build/packages/masterdir masterdir cleaned up.

$ ./xbps-src  binary-bootstrap
[...]
=> xbps-src: cleaning up masterdir...
chmod: cannot access '/void-packages/masterdir/builddir': No such file or directory

```

I've also saw these messages on `binary-bootstrap` stage with XBPS_MASTERDIR settled, altought I don't remember exactly where:
```
touch: cannot touch '/void-packages/masterdir/.xbps_chroot_configured': No such file or directory
/void-packages/common/xbps-src/shutils/pkgtarget.sh: line 46: cd: /void-packages/masterdir: No such file or directory
```

**Comment by Duncaen** [comment]
I think we should revert the latest changes to xbps-src, `bootstrap-update` was also broken https://github.com/void-linux/void-packages/commit/2e108ebfdf189e294d98cc8224230679cfea89d7.
