### ISSUE TITLE
Virt-manager Could not connect

### ISSUE THREAD

**Issue by Anex007** [void-linux/void-packages#8338]
### System

* xuname:  
  Void 4.19.20_1 x86_64-musl GenuineIntel notuptodate rF
* package:  
  virt-manager-2.1.0_2

### Expected behavior
I should be able to create VM's and get everything working

### Actual behavior
It gets stuck in this stage
![virt-issue1](https://user-images.githubusercontent.com/26581820/52458469-6d745380-2b57-11e9-94cb-59129f02a7ae.png)

i ran it with ``virt-manager --debug`` to see debugging information and this is what i got, something internal got errored idk why

![virt-issue2](https://user-images.githubusercontent.com/26581820/52458491-8bda4f00-2b57-11e9-964b-4dfb8da4cfe0.png)

### Steps to reproduce the behavior
I installed this package then installed qemu and i did reboot

**Comment by CameronNemo** [comment]
Please ensure that the bus service is running. You may also need additional services enabled: libvirtd, virtlockd.

**Comment by Anex007** [comment]
Still not working after i started those services 
this is the debug output after starting the service
![virt-issue3](https://user-images.githubusercontent.com/26581820/52497779-dea31d80-2bce-11e9-9fcd-2a4bd6cb56f2.png)

and i did reboot

**Comment by ivstefn** [comment]
I notced that too today. 

workaround: 

* `virsh` works as it should. 
* for virt-manager, click File->Add Connection->(whatever hypervisor, QEMU/KVM for me)->Connect.

That worked for me, but you need to do that every time you start virt-manager.

**Comment by jnbr** [comment]
> That worked for me, but you need to do that every time you start virt-manager.

Edit -> Connection Details -> Autoconnect

**Comment by Anex007** [comment]
Still not working after i started those services 
this is the debug output after starting the service
![virt-issue3](https://user-images.githubusercontent.com/26581820/52497779-dea31d80-2bce-11e9-9fcd-2a4bd6cb56f2.png)

and i did reboot 

> I notced that too today.
> 
> workaround:
> 
>     * `virsh` works as it should.
> 
>     * for virt-manager, click File->Add Connection->(whatever hypervisor, QEMU/KVM for me)->Connect.
> 
> 
> That worked for me, but you need to do that every time you start virt-manager.

This worked for me too Thanks, it seems like some python syntax error when it tries to connect the first time

**Comment by Anex007** [comment]
This issue has been reported and fixed in https://bugzilla.redhat.com/show_bug.cgi?id=1674040
just need to update it in void repo
