### ISSUE TITLE
Stupid behavior with tmux when dbus enabled.

### ISSUE THREAD

**Issue by Vaelatern** [void-linux/void-packages#8346]
Command:

```
ssh -t $myhost tmux
```
disconnect from tmux (default: `ctrl-b d`)
```
ssh -t $myhost tmux a
```
And that should succeed, and does to some machines.

When dbus is enabled, the second command fails with  `no sessions`, and yes, tmux+dbus will happily kill off whatever I have running in tmux at the time, including other connected sessions (another terminal with `ssh -t $myhost tmux a`)

**Comment by the-maldridge** [comment]
I can't replicate this, and my host has a system dbus running.

**Comment by Vaelatern** [comment]
Trying to replicate on an additional host

**Comment by Vaelatern** [comment]
Thanks to @Gottox for fixing this!
