### ISSUE TITLE
Package Issue: base-files causes invalid /usr/lib/lib link

### ISSUE THREAD

**Issue by Anachron** [void-linux/void-packages#8349]
### System

* xuname:  
Void 4.19.19_2 x86_64 GenuineIntel uptodate rrrmFFFFF
* package:  
base-files (any version)

https://github.com/void-linux/void-packages/blob/master/srcpkgs/base-files/INSTALL#L50-L63

The base-files `INSTALL` script does not check whether the symlinks actually exist.
This causes a new symlink inside this already existing symlink. (Because is the default behavior of `ln -s`)

To be specific:
https://github.com/void-linux/void-packages/blob/master/srcpkgs/base-files/INSTALL#L52
```
cd usr && ln -sf lib lib64 && cd ..
```
The lib64-folder is already a symlink, such creating a new lib-file there.

### Expected behavior

The package `base-files` should not create invalid symbolic links.

### Actual behavior

The package `base-files` creates invalid symbolic links.

### Debugging

```
# ls -lisa /usr/lib/lib
402148 0 lrwxrwxrwx 1 root root 3 17. Jan 09:51 /usr/lib/lib -> lib

# xilog | grep '2019-01-17'
base-files-0.139_12                    : 2019-01-17 09:51 CET
dracut-048_4                           : 2019-01-17 09:51 CET
pam-base-0.3_4                         : 2019-01-17 09:51 CET
shadow-4.6_2                           : 2019-01-17 09:51 CET
---
libXdamage-32bit-1.1.4_6               : 2019-01-17 10:03 CET
libXxf86vm-32bit-1.1.4_3               : 2019-01-17 10:03 CET
libpciaccess-32bit-0.14_2              : 2019-01-17 10:03 CET
libxshmfence-32bit-1.3_2               : 2019-01-17 10:03 CET
libXv-32bit-1.0.11_2                   : 2019-01-17 10:20 CET
libXvMC-32bit-1.0.10_2                 : 2019-01-17 10:20 CET
wayland-32bit-1.16.0_1 : 2019-01-17 10:20 CET
```

**Comment by CameronNemo** [comment]
There is also one in lib32.
