### ISSUE TITLE
Initial PPC Support

### ISSUE THREAD

**Issue by foxlet** [void-linux/void-packages#8375]
This issue is to track changes and discussion intended for initial PPC support.

## Bootable Media (mklive)
- [X] rootfs https://github.com/void-linux/void-mklive/commit/4d817473872572896c7f50f196e71d37f6d996dd
- [ ] livecd

## Bootloader
- [X] grub 1450c2fb876de48b8b24d61286655cea54709b40

## Kernel
- [ ] Linux Metapackage
- [x] Linux 4.x 3f8e90cfcb91e46153ada8bd28a97b27b92ef01b

**Comment by stenstorp** [comment]
Linux kernel configurations have been committed and Linux metapackage configured: https://github.com/void-linux/void-packages/commit/3f8e90cfcb91e46153ada8bd28a97b27b92ef01b
livecd patches in void-power fork, PR soon?: https://github.com/void-power/void-mklive/commit/2c6d1c9ba5b170a6b0efab1fe8daeedbdfaa1fa1

**Comment by jnbr** [comment]
PPC support is way beyond "initial" by now, closing.
