### ISSUE TITLE
mpop links against libidn2 on musl

### ISSUE THREAD

**Issue by Johnnynator** [void-linux/void-packages#8428]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package:  
  *mpop-1.4.2_1*

### Expected behavior
It should link against the same libidn version on musl and glibc

### Actual behavior
glibc one links against libidn and musl against libidn2

**Comment by chneukirchen** [comment]
This happens because gnutls pulls in idn2, I'll move to idn2.

**Comment by chneukirchen** [comment]
actually glibc one uses glibc idn and no libidn.

**Comment by Johnnynator** [comment]
Mkay, I only noticed that libidn-devel was in `makedepends`. So it never get used?

**Comment by chneukirchen** [comment]
b9f32e02d1
