### ISSUE TITLE
lutris-0.5.0.1_1: missing dependency webkit2gtk

### ISSUE THREAD

**Issue by whoizit** [void-linux/void-packages#8429]
### System

* xuname:  
Void 4.19.20_1 x86_64 AuthenticAMD uptodate rFFFFFFFFF
* package:  
lutris-0.5.0.1_1
### Actual behavior
```
$ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 31, in <module>
    from lutris.gui.application import Application
  File "/usr/lib/python3.6/site-packages/lutris/gui/application.py", line 34, in <module>
    from lutris.game import Game
  File "/usr/lib/python3.6/site-packages/lutris/game.py", line 14, in <module>
    from lutris.runners import import_runner, InvalidRunner, wine
  File "/usr/lib/python3.6/site-packages/lutris/runners/wine.py", line 10, in <module>
    from lutris.gui.dialogs import FileDialog
  File "/usr/lib/python3.6/site-packages/lutris/gui/dialogs/__init__.py", line 12, in <module>
    gi.require_version("WebKit2", "4.0")
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available

```

**Comment by whoizit** [comment]
Can we highlight the maintainer or how it works?

**Comment by maxice8** [comment]
I marked this as a good first issue so newcomers to void can come to this and get to solve an issue that is easy and gets them over the little hump of first contributing.

Anyone that needs this fixed with urgency are recommended to make a pull request fixing it.

**Comment by whoizit** [comment]
I mean we have the field `maintainer: Jan Wey. <email@address.tld>`

Does not he have to fix it?

**Comment by maxice8** [comment]
On Mon, Feb 11, 2019 at 02:15:46PM -0800, whoami wrote:
> I mean we have the field `maintainer: Jan Wey. <email@address.tld>`
> 
> Does not he have to fix it?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/void-linux/void-packages/issues/8429#issuecomment-462516736

Please open a PR if it is so urgent.

**Comment by whoizit** [comment]
Question not about fix it, but about how it works. Why we have maintainer field, if mainteiner not accompany it? Not even highlight him.

**Comment by Johnnynator** [comment]
> Question not about fix it, but about how it works. Why we have maintainer field, if mainteiner not accompany it? Not even highlight him.

The main problem with the maintainer field is that it never gets updated, Jan Wey only made this one contribution to void in 2015 and never contributed afterwards, so it is outdated over 3 years.
