### ISSUE TITLE
Please set CONFIG_PINCTRL_CANNONLAKE=m in the linux package

### ISSUE THREAD

**Issue by thomas-t-w** [void-linux/void-packages#8478]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
* package: linux
  *affected package(s) including the version* linux 4.20

### Expected behavior
Whiskey lake would work properly. In my case, SD card reader is not working using sdhci_pci.
### Actual behavior
SD Card reader not initializing.
### Steps to reproduce the behavior
Boot kernel without module on affected systems.
I fixed this by editing the config in files for x86_64 and building the package. I opened an issue for it because I am not sure if it should be also enabled for i386 other kernels etc and honestly I just don't feel experienced enough/comfortable editing the kernel package. Thanks.

**Comment by maxice8** [comment]
@Hoshpak fixed ?

**Comment by Hoshpak** [comment]
I enabled the module in the kernel configs for 4.14, 4.19 and 4.20. However since the builders were busy, I didn't rebuild the package. I will close the issue once 4.20 gets rebuilt.

**Comment by Hoshpak** [comment]
linux4.20-4.20.7_2 with the module included will be available in the repositories in a few hours.
