### ISSUE TITLE
Java free Libreoffice

### ISSUE THREAD

**Issue by ErinVoid** [void-linux/void-packages#8486]
### System

* xuname:  
  *Void 4.19.18_1 x86_64 GenuineIntel uptodate rF*
* package:  
  *Libreoffice 6.1.4.2 and all other glibc versions tried*

### Expected behavior
To install sans Java or have an option to be Java free. The musl variant is Java free and works without any noticeable downsides. It would be ideal to have a glibc version without too.
### Actual behavior
Installing pulls in openjdk-jre.
### Steps to reproduce the behavior
xbps-install Libreoffice.

**Comment by Cogitri** [comment]
FWIW, libreoffice already has a java build option

**Comment by Hoshpak** [comment]
Indeed, we are definitely not going to provide two versions of the package. If you want your libreoffice without Java, please use the build option to build it yourself.

**Comment by ErinVoid** [comment]
Why can it not be built without the hard Java dependency and leave it as an option post-install?

**Comment by pullmoll** [comment]
The dependency on java is not defined by an `depends="openjdk"` but a result of building LO with `hostmakedepends+=" apache-ant openjdk"`. So we can not remove the dependency and at the same time support Java for x86_64. The Java support depends on the host's make dependencies.
It's not that I myself was interested in adding Java support.
It was added by request of a user who needed it.
We cannot dance at two weddings at the same time ;-P

**Comment by Johnnynator** [comment]
> The dependency on java is not defined by an `depends="openjdk"` but a result of building LO with `hostmakedepends+=" apache-ant openjdk"`. So we can not remove the dependency and at the same time support Java for x86_64. The Java support depends on the host's make dependencies.
> It's not that I myself was interested in adding Java support.
> It was added by request of a user who needed it.
> We cannot dance at two weddings at the same time ;-P

Shouldn't it be possible to split the java part into ti's own subpackage? I can take a look at it tomorrow/at the weekend.

**Comment by pullmoll** [comment]
If you can find a way to make the one build produce two variants that may be viable.
I do however fear that it requires running and entire configure / build cycle which takes a *little time*.

**Comment by pullmoll** [comment]
Indeed: if you take a look at `ldd /usr/lib/libreoffice/program/*.so|less` and search for `libjvm` you will see dependencies in many if not almost all shared libraries.

**Comment by Johnnynator** [comment]
Yep, but libofficebeans is the only file that links against openjdk and nothing linnks against it. We just need to make sure that nothing breaks when it is not installed.

**Comment by pullmoll** [comment]
Great! If you know a way to solve this PR that's good news and certainly appreciated by Void users.
