### ISSUE TITLE
Join opencontainers security list

### ISSUE THREAD

**Issue by CameronNemo** [void-linux/void-packages#8552]
Following the recent runc vulnerability, there has been an opencontainers security list established. Void should join the list.

https://github.com/opencontainers/org/blob/master/security.md

**Comment by maxice8** [comment]
We don't have 0, 2 and 6.

**Comment by chneukirchen** [comment]
IMO we should deal with this same as distros@, i.e. skip it.

**Comment by CameronNemo** [comment]
Putting a pin in this for now.
