### ISSUE TITLE
Package Request: openeuphoria

### ISSUE THREAD

**Issue by silvernode** [void-linux/void-packages#8570]
# OpenEuphoria [![](https://openeuphoria.org/logos/80x84-mongoose-color-lite.png)](https://openeuphoria.org)
Here's a pretty obscure programming language that no other distribution has (to my knowledge). It's a pretty old language (1993) that has gained a niche following since it became open source over a decade ago. I tried packaging it a few years back and gave up after a week of trying. I thought it would be neat to have it in the repos and maybe it will get a few users that way. 

### Features:  

* General purpose
* Generate C code
* Extensive SFML support
* Extensive Gtk support
* Native IDE
* An active friendly community
* Easy to learn syntax
* Procedural
* Performance focused 
* 4 data types

### Code Example:
**_FizzBuzz_**
```
include std/console.e  
integer a = 3  
integer b = 5  
integer c = 100  
  
for i = 1 to c do   
	if    remainder(i,a * b) = 0 then display("FizzBuzz")  
	elsif remainder(i,a) = 0     then display("Fizz")  
	elsif remainder(i,b) = 0     then display("Buzz")  
	else                              display(i)  
	end if  
end for
```
### Stats:

**Current Release Version:** 4.0.5 (2012)
**Current Beta Version:** 4.1.0 (available on sourceforge)
**Last Github Commit:** Oct 22, 2018
### Links:
[Official Website](https://openeuphoria.org/)
[Wikipedia](https://en.wikipedia.org/wiki/Euphoria_(programming_language))
[Github](https://github.com/OpenEuphoria/euphoria)
[SourceForge (seems deprecated)](https://sourceforge.net/projects/rapideuphoria/)
[License](https://github.com/OpenEuphoria/euphoria/blob/master/License.txt)

### Notes:
You may have to build 4.1.0 from sourceforge (or pull from master on github) since 4.0.5 is very old.

**Comment by youngjinpark20** [comment]
4.1.0 is a newer version, but it's beta, so we would most likely package the stable release (4.0.5)
