### ISSUE TITLE
GDM doesnt load profile file

### ISSUE THREAD

**Issue by glats** [void-linux/void-packages#8613]
### System

* xuname: ``Void 4.19.20_1 x86_64 GenuineIntel notuptodate rFF``
* package:  gdm-3.30.2_1

### Expected behavior
 Load properly /etc/profile.d/*.sh files
### Actual behavior
 It doesnt load files
### Steps to reproduce the behavior
After install gnome and gdm then you logged in, the variables in /etc/profile.d/ will load in your user environment and it doenst.

example after login:
https://gist.githubusercontent.com/glats/d9d1defe2d9a1b104ae93638d8bc2868/raw/d1e71d148c7873b8615c7f4c194216b98a655249/log.txt

after login and sourcing /etc/profile manually:
https://gist.githubusercontent.com/glats/0455d5f3078f613221128ad612a9d587/raw/72f717ac567be3bdb3ecc1bb81105077acbe4220/log2.txt

As you can see theres many variables that doenst load like MOZ_USE_XINPUT2

So after a bit research gdm, has a file called Xsession that can load profile files properly.
I took a Xession file from my laptop that has Archlinux and I put it in my /etc/gdm/Xsession on my VoidLinux laptop then rebooted and all my vars appears

Void Xsession then:
```
#!/bin/sh
exec $@
```

Xession now:
https://gist.githubusercontent.com/glats/4f536dfedc70ca9d900e04dd685327a3/raw/4666f7e1808f6c4bb1489bf5d44aa9c0d6297344/Xsession

How i said before copy paste i have all my environment variables loaded correctly

Thnks for advanced

**Comment by Cogitri** [comment]
Seems like this is pretty much identical to what Debian and Ubuntu do, so I don't have anything against switching over to different Xsession file (although the one you've linked and that Debian&Friends use is too complicated for my taste). I do have to say that I'm curious what you need this for though :)

**Comment by glats** [comment]
> Seems like this is pretty much identical to what Debian and Ubuntu do, so I don't have anything against switching over to different Xsession file (although the one you've linked and that Debian&Friends use is too complicated for my taste). I do have to say that I'm curious what you need this for though :)

I think the same. The file I copied its too much "sophisticated/complex" and It would be great one more simple.
As I said I need that file to get the variables inside /etc/profile.d/ for user. Without that kind of configuration the variables doesnt load on login through gdm. With this I can get MOZ_USE_XINPUT2 as a global variable for my user can work with firefox in my tablet to scroll webpages with my fingers.

For some weird reason after login through gdm it doesnt source /etc/profile with all variables inside /etc/profile.d/*.sh properly. Thats the issue.

I hope to be clear. Thanks for response

**Comment by Cogitri** [comment]
May I ask what shell you're using? At least BASH and DASH (the default) shouldn't need this (and source everything in /etc/profile.d correctly)

**Comment by glats** [comment]
Yeah. Im using BASH :D

**Comment by Cogitri** [comment]
Alright, will add this in the process of making GNOME cross-able

**Comment by glats** [comment]
Thanks. 
Here there is more information about what I'm talking https://unix.stackexchange.com/a/2963/234090

**Comment by Cogitri** [comment]
Alright, that only works with Xorg sessions and not for Wayland sessions, see https://lwn.net/Articles/709769/. We either have to add it to https://www.freedesktop.org/software/systemd/man/environment.d.html (via elogind) or to /usr/share/gdm/env.d

**Comment by glats** [comment]
Ok. that sounds perfect.
Thnks for your work!

**Comment by glats** [comment]
@Cogitri I think i found something or maybe not.
It appears the umask changed.
I did two tests: one before installing gnome and one after.
In a fresh installation I installed nodejs and then i ran: ```sudo npm i -g @angular/cli``` and ng performed well.
Then I installed gnome and i ran ```sudo npm -i g http-server``` then i ran:
```
$ http-server
bash: command not found
```
```
$ /usr/bin/http-server
bash: /usr/bin/http-server: Permission denied
```
then I checked both binaries and their permissions and thats show up:
```
$ sudo ls -ls /usr/bin/ng
0 lrwxrwxrwx 1 root root 39 Feb 27 01:21 /usr/bin/ng -> ../lib/node_modules/@angular/cli/bin/ng

$ sudo ls -l /usr/lib/node_modules/@angular/cli/bin/ng
-rwxr-xr-x 1 root root 881 Oct 26  1985 /usr/lib/node_modules/@angular/cli/bin/ng
```
```
$ sudo ls -l /usr/bin/http-server
lrwxrwxrwx 1 root root 47 Feb 27 01:43 /usr/bin/http-server -> ../lib/node_modules/http-server/bin/http-server

$ sudo ls -l /usr/lib/node_modules/http-server/bin/http-server
-rwxr-x--- 1 glats glats 5001 Jan 10  2018 /usr/lib/node_modules/http-server/bin/http-server
```
as you can see permissions and owners are totally messed up after gnome get into the game.
I dont know if is related with this bec. i didnt test before merge happened.

Thanks for advanced!

**Comment by Cogitri** [comment]
Hum, I don't use npm, but at least when running stuff like `doas ninja -C build install` to install test builds of gxi that appears to work fine. Could you run `umask` and tell us the output?

**Comment by glats** [comment]
My umask in gnome is 0007 :S
and my umask in tty is 0022
oh! so you do use doas.. i dont know if there's a difference between doas and sudo in this case.

**Comment by Cogitri** [comment]
Hum, this is weird. My umask is messed up when using GNOME terminal too (0007), but when using Tilix or Alacritty it's fine (0022). Will look into it, thanks for reporting

**Comment by glats** [comment]
Thnks very much @Cogitri !
