### ISSUE TITLE
lxc fails to start after recent CVE patch

### ISSUE THREAD

**Issue by Piraty** [void-linux/void-packages#8629]
### System

* xuname:  `Void 4.20.7_3 x86_64 GenuineIntel/VMware notuptodate hold rDF`
* package:  `lxc-3.0.3_3`

### Expected behavior
lxc can start containers
### Actual behavior
lxc cannot start containers
0d0d6a75c01f1b073fddaa9e26a909ee171cde49 (#8561) by @CameronNemo added a CVE patch (that is upstream) that fixes the CVE in Void by containers not starting ;-)
### Steps to reproduce the behavior
```
lxc launch images:debian/stretch mycontainer
Creating mycontainer
Starting mycontainer
Error: Failed to run: /memfd:liblxc (deleted) forkstart mycontainer /var/lib/lxd/containers /var/log/lxd/mycontainer/lxc.conf: 
Try `lxc info --show-log local:mycontainer` for more info
```
The mentioned log command doesn't help, and `/var/log/lxd/mycontainer/` doesn't show more than above.

**Comment by bra1nwave** [comment]
This  [commit/patch](https://github.com/lxc/lxc/commit/b091c341d5131e54ed4152855439b7a188d371dc.patch) should fix it

**Comment by CameronNemo** [comment]
Sorry I did not think to test LXD... that patch should be pulled in AFAICT. I will do a test once I get to an unmetered connection.
