### ISSUE TITLE
Package Request: bluez-rfcomm and bluez-hcitool

### ISSUE THREAD

**Issue by johnche** [void-linux/void-packages#8640]
Quote from archwiki:

    "they provide certain functionality which is missing from newer tools."

Source: https://wiki.archlinux.org/index.php/Bluetooth#Bluetooth_serial
I am guessing newer tools here refers to bluetoothctl. 

My motivation with this tool (rfcomm) is to bind a bluetooth mac address to a tty in /dev for interfacing in python (pyserial). Could also be generally useful for bluetooth usage.

I am not sure if this provides rfcomm: http://www.bluez.org/download/
https://aur.archlinux.org/packages/bluez-rfcomm/
https://aur.archlinux.org/packages/bluez-hcitool/

**Comment by benalb** [comment]
I do not think that neither of both tools can be packaged, as the sources are in the AUR git repo, with no releases, license, that I think are required in every void package. 

But, on the bright side, you can just clone the repos, install libbluetooth-devel and
do as says in their PKGBUILD. 

gcc rfcomm.c -lbluetooth -o rfcomm -DVERSION=5.45 
gcc hcitool.c oui.c -lbluetooth -o hcitool -DVERSION=5.45

In my system they compile and create executable. Then, I do not read C, so I can say if these executables will do what they should do, or are taking my machine to a evil botnet.  :)

**Comment by johnche** [comment]
I see. You're right, I cloned and compiled it without any hitch, thanks. Though, I went back and had a look at what bluez.org provided, and it seems its all in bluez-utils package. The license is also included in "COPYING". I'll compile this myself for my own use, though not sure if there is still an interest in having this as void package.

Sorry, I should have looked closed before posting this issue.

http://bluez.sf.net/download/bluez-utils-3.36.tar.gz

**Comment by Anachron** [comment]
@benalb the source actually has these tools included in the latest release:
https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/tools

I've manually downloaded and extracted it to find out that even in there the tools are provided.
http://www.kernel.org/pub/linux/bluetooth/bluez-5.50.tar.xz

We should only have to fix our package template.

**Comment by benalb** [comment]
@Anachron awesome! I will try to get the template fixed and PR.

**Comment by benalb** [comment]
https://github.com/void-linux/void-packages/pull/8730

**Comment by Anachron** [comment]
This can be closed, it has been merged.
