### ISSUE TITLE
mpv vulkan support

### ISSUE THREAD

**Issue by Vintodrimmer** [void-linux/void-packages#865]
### System

* xuname:  
  *Void 4.17.6-chrysalis x86_64 GenuineIntel uptodate rrFFFF*
* package:  
  *mpv-0.28.2_1*

### Expected behavior
Be able to set and use `gpu-api=vulkan` and `vulkan-async=yes`

### Actual behavior
```
Error parsing option gpu-api (option parameter could not be parsed)
/home/eichhorn/.config/mpv/mpv.conf:3: setting option gpu-api='vulkan' failed.
Error parsing option vulkan-async (option not found)
/home/eichhorn/.config/mpv/mpv.conf:4: setting option vulkan-async='yes' failed.
```
```
➤ mpv -gpu-api=help
GPU APIs (contexts):
    auto (autodetect)
    opengl (x11probe)
    opengl (x11egl)
    opengl (x11)
    opengl (wayland)
    opengl (drm)
    opengl (vdpauglx)
```

### Steps to reproduce the behavior
1. Set the aforementioned setting in the configuration file
2. Launch MPV

Is there no support for Vulkan due to some peculiarities of Void itself or is there some other reason?

**Comment by maxice8** [comment]
Requires Vulkan-Headers to be packaged https://github.com/void-linux/void-packages/pull/793/files

**Comment by maxice8** [comment]
Ok, `Vulkan-Headers` was added, `Vulkan-Tools` was added, `vulkan-loader` was updated.

**Comment by maxice8** [comment]
@Vintodrimmer @5nefarious  if you want to get MPV with vulkan faster into void you can help by testing https://github.com/void-linux/void-packages/pull/1468 (please give feedback)

**Comment by Vintodrimmer** [comment]
Thanks!
