### ISSUE TITLE
ufw does not work (missing dependency)

### ISSUE THREAD

**Issue by philipgg** [void-linux/void-packages#8685]
### System

* xuname:  `Void 4.19.20_2 i686 GenuineIntel uptodate rF`
  *output of ``xuname`` (part of xtools)*
* package:  `[*] ufw-0.36_1 Uncomplicated Firewall`
  *affected package(s) including the version*

### Expected behavior
The firewall should work...
### Actual behavior
Missing `python3` dependency.
### Steps to reproduce the behavior
````
# ln -s /etc/sv/ufw /var/service

# ufw status
/usr/bin/env: « /usr/bin/python3 »: Aucun fichier ou dossier de ce type
````

@maxice8 your commit was wrong:
https://github.com/void-linux/void-packages/commit/c82951d8a5ec91611f41e0efdf36b48959449729

**Comment by maxice8** [comment]
Commit is not mine.

@CameronNemo

**Comment by philipgg** [comment]
> Commit is not mine.

?

I can see: maxice8 committed on Dec 15, 2018

**Comment by maxice8** [comment]
Poor reading, check who authored.
