### ISSUE TITLE
gambit: missing static libraries

### ISSUE THREAD

**Issue by gravicappa** [void-linux/void-packages#8693]
`gambit-4.9.3_1` package on x86_64 is missing static libraries `/usr/lib/gambit/libgambit*.a`.
Probably `./configure` flags should contain `--enable-static`.

**Comment by bobertlo** [comment]
I attempted to spin off a gambit-devel package with static libraries and include files, but their configure script seems to treat static and shared libraries as mutually exclusive.

**Comment by gravicappa** [comment]
I looked into my old scripts for building gambit package (unrelated to void). I noticed that I used neither `--enable-static` nor `--enable-shared` configure flags and it successfully provided both `*.so` and `*.a` libraries.

**Comment by maxice8** [comment]
Passed none enables only .a but we want .so files as well.

If someone knows a fix a PR can be opened.
