### ISSUE TITLE
Kodi: add binary addons

### ISSUE THREAD

**Issue by teldra** [void-linux/void-packages#8728]
https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md#5-build-binary-add-ons
Because I don't know, how to merge this with srcpkgs/kodi/template, I raise this issue.

**Comment by teldra** [comment]
Since the method in the link above pulls addons from the master branch of the respective repos, and the addons are developed faster than Kodi, i could not imagine a way to package this with our packagemanager. A spot check shows, the addons get releases in theire repos.
@Hoshpak do you have an idea?

**Comment by Hoshpak** [comment]
I didn't have time to look into this. I will probably get to it next week.

**Comment by Hoshpak** [comment]
Since I had some time today, I looked into it. It indeed seems to be impractical to use the script in the kodi archive since it violates the policy of only packaging stable software, would reduce in completely non-deterministic builds and possibly deliver outdated addons to the users.

I checked a few of the addons and it seems they are usually maintained in their own separate git repositories and are properly versioned. So it should be possible to create a kodi-devel package to make it possible to build software against it and package the addons separately (possibly offering a meta-package to install all of them) however maintaining all of them seems to be a lot of work. Perhaps it would be feasible to start with a few selected ones and add more as people (pull) request them?

Do you have specific addons in mind that would be useful to you? I haven't noticed any missing functionality in the new kodi version yet so I'm not sure if I would install any of the binary addons at all.

**Comment by teldra** [comment]
That sounds awesome. I was looking for the new feature of libretro integration and the zattoo plugin: https://github.com/rbuehlma/pvr.zattoo and https://github.com/xbmc/repo-binary-addons/tree/master/game.libretro but I think https://github.com/xbmc/repo-binary-addons/tree/master/peripheral.joystick, https://github.com/xbmc/repo-binary-addons/tree/master/inputstream.rtmp, https://github.com/xbmc/repo-binary-addons/tree/master/inputstream.adaptive, https://github.com/xbmc/repo-binary-addons/tree/master/pvr.hts and https://github.com/xbmc/repo-binary-addons/tree/master/vfs.nfs can be very useful too.

**Comment by Hoshpak** [comment]
@teldra Could you please test #8728 ?

**Comment by teldra** [comment]
It seems to be the right. Kodi finds plugin and with logincredentials I get the channellist.
I had to manually select (in the preferences of zattoo addon) "hls" stream. Preconfigured was dash, that gave me this (iirc dash will be supported in near future):

> 14:00:34.999 T:140296165505728   DEBUG: CPlayerGUIInfo::InitCurrentItem(pvr://channels/tv/All channels/pvr.zattoo_136260.pvr)
> 14:00:34.999 T:140296165480192   DEBUG: CAnnouncementManager - Announcement: OnChanged from xbmc
> 14:00:34.999 T:140296165480192   DEBUG: GOT ANNOUNCEMENT, type: 1024, from xbmc, message OnChanged
> 14:00:34.999 T:140296165480192   DEBUG: CAnnouncementManager - Announcement: OnPlay from xbmc
> 14:00:34.999 T:140296165480192   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnPlay
> 14:00:35.151 T:140294569850624   DEBUG: Thread FileCache start, auto delete: false
> 14:00:35.151 T:140295255496448  NOTICE: Creating Demuxer
> 14:00:35.152 T:140294569850624    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
> 14:00:35.206 T:140295255496448   ERROR: Open - error probing input format, http://fr5-0-dash-live.zahs.tv/ZDF/manifest.mpd?z32=OVZWK4S7NFSD2OJRGYZDENJQEZWWS3TSMF2GKPJWGAYCM3LBPBZGC5DFHUYTKMBREZZWSZZ5MUZGKMTEGBSDCMRZHAZTEYTBHA2DCYZTMU3WIY3EGIYTSMDBHBRCMY3TNFSD2MJVHA2DEQRXHA2DSOBYHA4TOQJNGM2TQNBVGQZDMMZRIJBDENRZHETGS3TJORUWC3DSMF2GKPJQ
> 14:00:35.206 T:140295255496448   ERROR: OpenDemuxStream - Error creating demuxer
> 14:00:35.206 T:140295255496448  NOTICE: CVideoPlayer::OnExit()
> 14:00:35.208 T:140294569850624   DEBUG: Thread FileCache 140294569850624 terminating
> 14:00:35.209 T:140295535601408   DEBUG: OnPlayBackStopped: CApplication::OnPlayBackStopped
> 14:00:35.209 T:140295255496448   DEBUG: Thread VideoPlayer 140295255496448 terminating
> 14:00:35.248 T:140296165480192   DEBUG: CAnnouncementManager - Announcement: OnStop from xbmc
> 14:00:35.248 T:140296165480192   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnStop
> 14:00:35.262 T:140296165505728  NOTICE: CVideoPlayer::CloseFile()
> 14:00:35.262 T:140296165505728  NOTICE: VideoPlayer: waiting for threads to exit
> 14:00:35.262 T:140296165505728  NOTICE: VideoPlayer: finished waiting
> 14:00:35.262 T:140296165505728   DEBUG: DeleteRenderer - deleting renderer
> 14:00:35.262 T:140296165505728   DEBUG: LinuxRendererGL: Cleaning up GL resources

And on top, it seems, a template for a binary plugin is not that complex. I will look into it!
Thank you very much!

**Comment by teldra** [comment]
I close this issue for now. I think it is clear, that someone, who needs a plugin, should raise an issue or just do it. :)
