### ISSUE TITLE
Package Request: MEGAsync

### ISSUE THREAD

**Issue by cebecifaruk** [void-linux/void-packages#8731]
Mega Cloud Storage Desktop Client

Source Code : [https://github.com/meganz/MEGAsync](https://github.com/meganz/MEGAsync)

**Comment by Johnnynator** [comment]
We can't redistribute the binary. There is already a template in the repo if you want to build it yourself https://github.com/void-linux/void-packages/blob/master/srcpkgs/MEGAsync/template
