### ISSUE TITLE
Libreoffice installs all dictionaries by default

### ISSUE THREAD

**Issue by ralphee** [void-linux/void-packages#8756]
### System

* xuname:  
Void 4.19.23_1 x86_64 GenuineIntel uptodate rFFF
 
* package:  
  LibreOffice Version: 6.1.4.2

### Expected behavior
Only main Dictionary/ies to be installed 

### Actual behavior
All dictionaries from Afrikaans to zulu are being installed

### Steps to reproduce the behavior
doas xbps-install -S libreoffice
open libreoffice
tools -> extension manager

**Comment by Johnnynator** [comment]
These are only the dictionaries and not the full language package, but I think it probably makes sense to split them.

**Comment by Anachron** [comment]
It should only have https://github.com/void-linux/void-packages/blob/ed0a601b653907335fe5f29459ee848512aac400/srcpkgs/libreoffice/template#L39-L46 and not every available language. Can you confirm this?

**Comment by ralphee** [comment]
```
# Add the previously installed default languages as well
depends+=" libreoffice-i18n-en-US>=${version}_${revision}"
depends+=" libreoffice-i18n-de>=${version}_${revision}"
depends+=" libreoffice-i18n-es>=${version}_${revision}"
depends+=" libreoffice-i18n-fr>=${version}_${revision}"
depends+=" libreoffice-i18n-it>=${version}_${revision}"
depends+=" libreoffice-i18n-pl>=${version}_${revision}"
depends+=" libreoffice-i18n-pt>=${version}_${revision}"
```
I even think the user should be able to define these to their specific needs

**Comment by Johnnynator** [comment]
@ralphee You can, `libreoffice` is just the meta package that pulls in everything. If someone only needs a subset of that, then they can install the needed packages manually.

**Comment by ralphee** [comment]
> @ralphee You can, `libreoffice` is just the meta package that pulls in everything. If someone only needs a subset of that, then they can install the needed packages manually.

even with subset you get the A-Z dictionaries....very painful if you actually use libreoffice and spellcheck

**Comment by Johnnynator** [comment]
> even with subset you get the A-Z dictionaries....very painful if you actually use libreoffice and spellcheck

As I said in the first comment, I will look into splitting the dictionary files. The default languages will stay as they are for now.

**Comment by Johnnynator** [comment]
@pullmoll What do you say, Imo we should look into getting some more hunspell dictionaries into the repo and disable the internal dict of LibreOffice.

**Comment by pullmoll** [comment]
@Johnnynator I don't care as long as I can have some dictionary for German ;-P
If you think disabling the internal dictionaries is okay, just do it.

**Comment by ericonr** [comment]
Ping @Johnnynator
