### ISSUE TITLE
st  segmentaion fault

### ISSUE THREAD

**Issue by ralphee** [void-linux/void-packages#8758]
### System

* xuname:  
Void 4.19.23_1 x86_64 GenuineIntel uptodate rFFF

* package:  
st
/usr/local/bin/st

### Expected behavior
st  to launch
### Actual behavior
segmentation fault 
### Steps to reproduce the behavior
doas xbps-install -S xst or compile from source (0.8.1)
launch st

**Comment by Johnnynator** [comment]
st is not sterm. 
`/usr/bin/st` is either provided by `st` or `xst` and `/usr/bin/sterm` by `sterm`. Pls make one bug report per package and make clear what package exactly is affected.

**Comment by CameronNemo** [comment]
usr/local/bin/st it seems as though you are using a site specific binary, perhaps from a previous manual install from source.

**Comment by ralphee** [comment]
> usr/local/bin/st it seems as though you are using a site specific binary, perhaps from a previous manual install from source. Please invoke the version in usr/bin.

just as an FYI all other suckless tools dmenu,dwm,slock,slstatus all use /usr/local/bin path when compiling directly from suckless source and all work without any issues. 

I now  installed st from xbps directly &  working without any issues
