### ISSUE TITLE
Package Request : banshee

### ISSUE THREAD

**Issue by bbleble** [void-linux/void-packages#8789]
I'm really like this media player.
I use this on other distributions.
Hope to see it on Void Linux.

Source = http://banshee.fm/download/

**Comment by Cogitri** [comment]
Needs gstreamer0.10 to work which we don't provide anymore.

**Comment by bbleble** [comment]
Ok thanks 😀😃

**Comment by Cogitri** [comment]
Hum, might be a good idea to look for a new audio player, I doubt banshee's going to make it into Void.
