### ISSUE TITLE
powertop 2.10 

### ISSUE THREAD

**Issue by ralphee** [void-linux/void-packages#8791]
### System
Void 4.19.23_1 x86_64 GenuineIntel uptodate rFFF

* package:  
 powertop 2.10
kernel 4.19.23_1

### Expected behavior
powertop launches

### Actual behavior
segmentation fault

### Steps to reproduce the behavior
xbps-install -S powertop
doas powertop

**Comment by Hoshpak** [comment]
https://lists.01.org/pipermail/powertop/2019-February/002029.html

**Comment by steinex** [comment]
Fixed in 4.19.24 / 4.20.11

**Comment by Hoshpak** [comment]
4.20.11 has hit the repositories, 4.19.24 will be available in a few hours.
