### ISSUE TITLE
Package Request : lirios/shell

### ISSUE THREAD

**Issue by needyGarry** [void-linux/void-packages#8796]
Hello,

Gnome and KDE are the only proper stacking Wayland compositors available in voidlinux. The problem is they consume a lot of system resources so, I think it would be cool to have
[Liri Shell](https://github.com/lirios/shell) as an alternative lightweight Wayland compositor.

**Comment by Cogitri** [comment]
Oh my. That looks incredibly interesting, will starts working on it in a bit!

**Comment by Cogitri** [comment]
Alright, nevermind. It uses qbs as build system (which is a massive pain and deprecated) and hasn't had a release for over a year.
