### ISSUE TITLE
mesa-ati-dri-18 breaks xf86-video-ati-18.0.1_2

### ISSUE THREAD

**Issue by ncmprhnsbl** [void-linux/void-packages#880]
### System

* xuname:  
  Void 4.14.52_1 x86_64 GenuineIntel notuptodate rDFFF
* package:  
 xf86-video-ati-18.0.1_2

libgbm-18.1.3_1
mesa-ati-dri-18.1.3_1
libEGL-18.1.3_1
libGL-18.1.3_1 
libglapi-18.1.3_1 
libGLES-18.1.3_1

### Expected behavior
X should start

### Actual behavior
X is seriously messed up
lxdm log says:
```
radeon: The kernel rejected CS, see dmesg for more information (-22).
```

/var/log/socklog/kernel:
```
kern.err: [  124.543286] radeon 0000:01:00.0: ring 0 stalled for more than 10057msec
...
 kern.err: [  126.367192] [drm:r600_ib_test [radeon]] *ERROR* radeon: fence wait timed out.
 kern.err: [  126.367348] [drm:radeon_ib_ring_tests [radeon]] *ERROR* radeon: failed testing IB on GFX ring (-110).
```
### Steps to reproduce the behavior
downgrading those (mesa) packages (not xf86-video-ati-18.0.1_2) fixes the problem

**Comment by ncmprhnsbl** [comment]
tried updating to the *-18.1.4_1 versions of the mesa/libGL packages, but the result is the same..

**Comment by ncmprhnsbl** [comment]
okay, mesa/libGL etc 18.1.4_3 seems to be working now,  thanks..

**Comment by ncmprhnsbl** [comment]
reopening because i am getting the same error with newer kernels >4.14.52_1
some inconsistency though:
booted 4.14.55 -- was okay
rebooted to 4.17-4  -- broken as per above (this kernel panics on shutdown for me)
booted 4.14.56 -- broken as per above
reboot to 4.14.55 -- now broken as per above  ??
back to 4.14.52_1 -- okay again..

**Comment by bugcrazy** [comment]
This issue is duplicated #169  and already has patches, now the package maintainer should apply the patches!

**Comment by ncmprhnsbl** [comment]
indeed,  the linked bug report describes it exactly
ie. screen corruption: https://bugs.freedesktop.org/attachment.cgi?id=138054
and turning off compositor(compton in autostart) helps(workaround)

**Comment by bugcrazy** [comment]
@ncmprhnsbl You can use xbps-src, to generate a package and you even apply the patches or expect maintainer to patch the package in the repository!

**Comment by ncmprhnsbl** [comment]
> You can use xbps-src, to generate a package and you even apply the patches
that sounds much easier than it was ;)
but after many attempts :   
1. edit paths in the patches
2.add host/make depends because of patches(automake m4 perl autoconf xorg-util-macros) (possibly overkill)
3. trick xbps-src into using aclocal-1.16 (wanted 1.15 for some reason)
i now have X working correctly :+1: 
i'll leave this open, until the repo package is patched or upstream get around to releasing a new version

**Comment by bugcrazy** [comment]
I used xbps-src, to generate package with patches xf86-video-ati-18.0.1_3, I edited the makefiles to use aclocal-1.16 and automake-1.16.
Add automake m4 perl autoconf xorg-util-macros and changed checksum in template file.
This is my compilation log [here](https://gist.github.com/bugcrazy/519b655bd74780dde4691df23aab1dd9)
I added two more patches [https://patchwork.freedesktop.org/patch/241377/](https://patchwork.freedesktop.org/patch/241377/) and [https://patchwork.freedesktop.org/patch/239365/](https://patchwork.freedesktop.org/patch/239365/
List of patches applied to fix the bug:
01-10-Drop-unused-drmmode_create_bo_pixmap-surface-parameter.patch
02-10-EXA-Remove-old-RADEONEXACreatePixmap-hook.patch
03-10-Only-initialize-libdrm_radeon-surface-manager-for-R600.patch
04-10-glamor-Don-t-store-radeon_surfaces-in-pixmaps.patch
05-10-Factor-out-radeon_surface_initialize-helper.patch
06-10-Move-flush-from-radeon_scanout_do_update-to-its-callers.patch
07-10-Remove-throttling-from-radeon_dri2_copy_region2.patch
08-10-Refactor-radeon_finish-helper.patch
09-10-Add-struct-radeon_buffer.patch
10-10-glamor-Use-GBM-for-BO-allocation-when-possible.patch
glamor-Invalidate-cached-GEM-handle-in-radeon_set_pixmap_bo.patch
v2-glamor-Use-glamor_egl_create_textured_pixmap_from_gbm_bo-when-possible.patch

**Comment by ncmprhnsbl** [comment]
cool, thanks :)
