### ISSUE TITLE
Update gmic to 2.4.5

### ISSUE THREAD

**Issue by luzpaz** [void-linux/void-packages#8801]
Latest stable 2.4.5
https://gmic.eu/files/source/gmic_2.4.5.tar.gz

https://github.com/void-linux/void-packages/blob/master/srcpkgs/gmic/template

**Comment by maxice8** [comment]
Make a PR if you need it, we have void-updates to notify us of updates.

**Comment by luzpaz** [comment]
void-update is way behind though.

**Comment by maxice8** [comment]
No.

![image](https://user-images.githubusercontent.com/30738253/52902248-8a62f380-31f5-11e9-9b27-487b5e63405b.png)

**Comment by luzpaz** [comment]
![image](https://user-images.githubusercontent.com/4140247/52903299-37833f00-31e9-11e9-98b0-0997f65d2571.png)

**Comment by luzpaz** [comment]
Oh, ok, my apologies

**Comment by luzpaz** [comment]
No update still, current stable is 2.6.7  
[![Packaging status](https://repology.org/badge/vertical-allrepos/gmic.svg?header=gmic)](https://repology.org/project/gmic/versions)

**Comment by luzpaz** [comment]
@maxice8 please please update to 2.6.7
