### ISSUE TITLE
cmake build broken due to libuv

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#889]
Trying to build cmake fails with:
```
-- Could NOT find LibUV: Found unsuitable version "", but required is at least "1.10.0" (found /usr/lib/libuv.so)
CMake Error at CMakeLists.txt:551 (message):
  CMAKE_USE_SYSTEM_LIBUV is ON but a libuv is not found!
Call Stack (most recent call first):
  CMakeLists.txt:682 (CMAKE_BUILD_UTILITIES)


-- Configuring incomplete, errors occurred!
See also "/builddir/cmake-3.11.4/CMakeFiles/CMakeOutput.log".
See also "/builddir/cmake-3.11.4/CMakeFiles/CMakeError.log".
---------------------------------------------
Error when bootstrapping CMake:
Problem while running initial CMake
---------------------------------------------
```
Was there perhaps a FindLibUV.cmake before?
Even after adding `pkg-config` to hostmakedepends it seems that `pkg-config` does not look for `/usr/lib/pkgconfig/libuv.pc` to find the version number.
The logfiles do not have further information AFAICT.

Building with `--no-system-libuv` works, but I'd rather have it keep using the system library.

**Comment by maxice8** [comment]
https://gitlab.kitware.com/cmake/cmake/commit/889033b5c6847cf1f7bd789384405d59dc333bf6

**Comment by maxice8** [comment]
> Was there perhaps a FindLibUV.cmake before?

FindLibUV.cmake is in Source/Modules
