### ISSUE TITLE
Request: RDMA/RoCE Support

### ISSUE THREAD

**Issue by ArmedAviator** [void-linux/void-packages#8901]
I'm doing some research into RDMA and RDMA-over-Converged-Ethernet (RoCE) to increase my Void Linux cluster performance over a 10GbE network.  I'm using Mellanox ConnectX-2 and ConnectX-3 10Gbit NICs.  There appears to be no packages/libraries in Void yet to enable RDMA support, atleast that I can tell.

I'm going off of this Howto, explaining what packages to install in Ubuntu or RHEL:
https://community.mellanox.com/s/article/howto-enable--verify-and-troubleshoot-rdma

**Comment by jnbr** [comment]
Can you tell which packages you actually need?

**Comment by ArmedAviator** [comment]
The best I can tell, based on other distros, the following will be required:

1. In Kernel config, enable CONFIG_RDS_RDMA (RDS is a module of RDMA, that is optional, but would be useful to have).

2. Packages include:

-    libibcm
-    libibverbs
-    libibverbs-utils
-    librdmacm
-    librdmacm-utils
-    rdma
-    dapl
-    ibacm
-    ibutils
-    libcxgb3
-    libcxgb4
-    libibmad
-    libibumad
-    libipathverbs
-    libmlx4
-    libmlx5
-    libmthca
-    libnes
-    ofed
-    mstflint

Most of the above packages can be retrieved from [Open Fabics Alliance](http://www.openfabrics.org/downloads/).

[Here](https://www.recitalsoftware.com/blogs/32-howto-getting-started-with-infiniband-on-redhat-centos-linux) is a good description of what the packages are used for.

**Comment by ArmedAviator** [comment]
Here's a start to some of the libraries:
https://github.com/void-linux/void-packages/pull/9004
