### ISSUE TITLE
Package Request: Mailspring

### ISSUE THREAD

**Issue by EmirEg** [void-linux/void-packages#8923]
## Description:
Boost your productivity and send better email with Mailspring, the best mail client for Mac, Linux, and Windows.

## URL:
https://getmailspring.com/

## Source:
https://github.com/Foundry376/Mailspring

## Use cases:
Has nice interface and I think it will be a nice addition for e-mail client.

**Comment by akhiljalagam** [comment]
manual method using deb package

1. download deb package from https://updates.getmailspring.com/download?platform=linuxDeb
2. extract it using `ar x mailspring-*-amd64.deb`
3. now extract data using `tar xf data.tar.xz`
4. `sudo chown root:root usr/`
5.`cd usr`
6.`sudo rsync -avh bin share /usr`

done.
now you can open mailspring and use it.
