### ISSUE TITLE
Compilation issue of sway-1.0-rc3 with musl

### ISSUE THREAD

**Issue by Derriick** [void-linux/void-packages#8962]
### System

* xuname:  
Void 4.19.19_1 x86_64-musl GenuineIntel notuptodate rF
* package:  
elogind-devel
[sway-1.0-rc3](https://github.com/Derriick/void-packages/blob/62e512de15a4ab4b162e6326a0e193875a9619ed/srcpkgs/sway/template)

### Actual behavior

When I try to build sway (1.0-rc2 and 1.0-rc3) with musl, meson stops saying that `"_POSIX_C_SOURCE" is not defined`. Here is my [template](https://github.com/Derriick/void-packages/blob/sway-1.0-rc3/srcpkgs/sway/template).

I tried to comment the `-Wundef` line in meson.build with a patch. This worked for version 1.0-rc1 but not for versions rc2 and rc3 of sway.
I tried to add `configure_args="-D_POSIX_C_SOURCE=xxxxxx"` to the template, then define it directly in /include/swaybar/tray/tray.h, but I get the same error.

Here is the output of xbps-src:
```
[255/272] Compiling C object 'swaybar/cf785bf@@swaybar@exe/main.c.o'.
[256/272] Compiling C object 'swaybar/cf785bf@@swaybar@exe/render.c.o'.
[257/272] Compiling C object 'swaybar/cf785bf@@swaybar@exe/status_line.c.o'.
[258/272] Compiling C object 'swaybar/cf785bf@@swaybar@exe/tray_host.c.o'.
[259/272] Compiling C object 'swaybar/cf785bf@@swaybar@exe/tray_tray.c.o'.
FAILED: swaybar/cf785bf@@swaybar@exe/tray_tray.c.o
cc -Iswaybar/cf785bf@@swaybar@exe -Iswaybar -I../swaybar -Iinclude -I../include -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/json-c -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/elogind -flto -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Werror -std=c11 '-DSWAY_SRC_DIR="/builddir/sway-1.0-rc3"' -DWL_HIDE_DEPRECATED -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-unused-result -Wundef -Wvla '-DSYSCONFDIR="//etc"' '-DSWAY_VERSION="1.0"' -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pthread  -MD -MQ 'swaybar/cf785bf@@swaybar@exe/tray_tray.c.o' -MF 'swaybar/cf785bf@@swaybar@exe/tray_tray.c.o.d' -o 'swaybar/cf785bf@@swaybar@exe/tray_tray.c.o' -c ../swaybar/tray/tray.c
In file included from /usr/include/elogind/systemd/sd-bus.h:26,
                 from ../include/swaybar/tray/tray.h:6,
                 from ../include/swaybar/tray/item.h:7,
                 from ../swaybar/tray/tray.c:9:
/usr/include/elogind/systemd/sd-event.h:74:28: error: "_POSIX_C_SOURCE" is not defined, evaluates to 0 [-Werror=undef]
 #if defined _GNU_SOURCE || _POSIX_C_SOURCE >= 199309L
                            ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
=> ERROR: sway-1.0+rc3_1: do_build: '${make_cmd} -C ${meson_builddir} ${makejobs} ${make_build_args} ${make_build_target}' exited with 1
=> ERROR:   in do_build() at common/build-style/meson.sh:126
```

The only solution I found was to add a patch to _elogind-devel_, which is a dependency of _wlroots-devel_, required to build sway (pull request: https://github.com/void-linux/void-packages/pull/8928).

### Steps to reproduce the behavior

Here is my current template for sway-1.0-rc3: https://github.com/Derriick/void-packages/blob/62e512de15a4ab4b162e6326a0e193875a9619ed/srcpkgs/sway/template
Just try to build it on a musl system.

**Comment by Johnnynator** [comment]
What about using smth like this instead
` #if defined _GNU_SOURCE || defined _POSIX_C_SOURCE && _POSIX_C_SOURCE >= 199309L`

**Comment by Derriick** [comment]
> 
> 
> What about using smth like this instead
> ` #if defined _GNU_SOURCE || defined _POSIX_C_SOURCE && _POSIX_C_SOURCE >= 199309L`

Why not, I will test it this evening.

**Comment by Derriick** [comment]
It works, thank you !

**Comment by CameronNemo** [comment]
@Johnnynator do we not want parentheses?

` #if defined _GNU_SOURCE || (defined _POSIX_C_SOURCE && _POSIX_C_SOURCE >= 199309L)`

**Comment by Derriick** [comment]
It works without them, but I added them just in case

**Comment by Johnnynator** [comment]
> @Johnnynator do we not want parentheses?
> 
> ` #if defined _GNU_SOURCE || (defined _POSIX_C_SOURCE && _POSIX_C_SOURCE >= 199309L)`

`&&` should take precedence over `||`. but adding parantheses shouldn't hurt.
