### ISSUE TITLE
Cant update - MEGAsync package broken

### ISSUE THREAD

**Issue by necronoise** [void-linux/void-packages#8964]
### System

* xuname:  MEGAsync-3.7.1.0_6: broken, unresolvable shlib `libmega.so.30406'
Transaction aborted due to unresolved shlibs.
Void 4.19.23_1 x86_64 GenuineIntel uptodate rrrmFFFFF

* package:  MEGAsync-3.7.1.0_6

### Expected behavior
Simple update the system.
### Actual behavior
I cant actually update because of the package. The way to fix it is everytime I update I need to remove the MEGAsync package first, update, and then install it again with xbps-src.

### Steps to reproduce the behavior
First install the MEGAsync with xbps-src:
`./xbps-src binary-bootstrap`
`./xbps-src pkg MEGAsync`

Wait it to compile and then:
`xbps-install --repository=hostdir/binpkgs MEGAsync`

Then update the system.
`sudo xbps-install -Suvy`

**Comment by Johnnynator** [comment]
Everything working as intended :D. MEGAsync is a restricted package and therefore not in the binary repository, every time `MEGAsdk` gets an update MEGAsync needs to be recompiled. The way you should do this is:
```
cd void-packages
git pull
./xbps-src binary-bootstrap
./xbps-src pkg MEGAsync
xbps-install --repository=hostdir/binpkgs -Suvy
```
There is no need to remove and reinstall `MEGAsync`

**Comment by necronoise** [comment]
It worked, thank you for your attention.
