### ISSUE TITLE
noarch=yes ignored in subpkgs?

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#9016]
I wondered why my local builds of e.g. `wesnoth` resulted in `wesnoth-data` subpackages for all architectures despite the `noarch=yes` in the `wesnoth-data_package()` function.
Is it possible the recent `archs=…` change does not provide a fallback for the old syntax for subpackages?

FWIW: changing the line to `archs=noarch` creates a `wesnoth-data-*.noarch.xbps` here.

Or perhaps I had a chroot with some intermediate state because the arch wesnoth-data packages were built between 2019-01-16 and 2019-01-18.

**Comment by Johnnynator** [comment]
I can reproduce this behaviour with Wesnoth.

**Comment by pullmoll** [comment]
Just double checked and confirmed:
With `noarch=yes` in the subpackage `wesnoth-data` then `./xbps-src pkg wesnoth` creates a `wesnoth-data-*.x86_64.xbps` and with `-a <somearch>` also `wesnoth-data-*.<somearch>.xbps` files.
WIth `archs=noarch` it works as expected.

**Comment by Johnnynator** [comment]
Yes, dopkg the compatibility workaround @Gottox did was only for the basepackage, and does not work in the do-pkg stage for subpackages.

**Comment by Johnnynator** [comment]
We should check the repo for a list of noarch packages that are now arch specific.

**Comment by pullmoll** [comment]
How do you check the files in the repo? The website no longer lists the files but prints a warning `Too many files! This will crash your browser, so we're serving you this page instead.` ;-P

**Comment by jnbr** [comment]
`XBPS_ARCH=<arch> xbps-query --repository=https://alpha.de.repo.voidlinux.org/current/ -M <pkg>`
or
`rsync --list-only rsync://alpha.de.repo.voidlinux.org/voidmirror/current/*`

**Comment by Johnnynator** [comment]
```
=> ERROR: notmuch-emacs arch missmatch
=> ERROR: notmuch-mutt arch missmatch
=> ERROR: postgresql-doc arch missmatch
```
Only these 3 seem to be affected.

**Comment by mcandre** [comment]
Same behavior for a single package with xbps-src today.

Specifying `noarch` in `template` for simple shell script packages, results in `x86_64-musl` in the final .xbps basename.

Using ghcr.io/void-linux/void-musl.

**Comment by sgn** [comment]
We no longer provide support for noarch.
