### ISSUE TITLE
Package Request: GRUB patch, XFS: accept filesystem with sparse inodes.

### ISSUE THREAD

**Issue by tykonin** [void-linux/void-packages#9023]
This is the patch: 
https://patchwork.kernel.org/patch/10401911/

I was testing the new ISOs and grub couldn't install on XFS partition formatted using defaults. (Using `mkfs.xfs -i sparse=0 /dev/sdX` works)

Is there chance to get this applied or we are waiting for the next GRUB release?

**Comment by Cogitri** [comment]
Seems like Upstream will merge it soon and that this has become the default for XFS, so +1 from me
