### ISSUE TITLE
 Package request: Nitroshare

### ISSUE THREAD

**Issue by manipuladordedados** [void-linux/void-packages#9033]
Lan file sharing.
https://nitroshare.net/

**Comment by whoizit** [comment]
seems like they are re-invented `uftp`

**Comment by whoizit** [comment]
what about wdt? https://github.com/facebook/wdt

**Comment by zayuim** [comment]
Does anybody know the Void equivalent of these Debian packages?

- qtbase5-dev
- libgtk2.0-dev (optional)

I need them to build the software.

P.S. seeing how I'm new to Void Linux and packaging, How would I go about installing dependencies? Will the regular `xbps-install -S` be enough?

**Comment by Johnnynator** [comment]
https://github.com/void-linux/void-packages/pull/9124 @zayuim Check this template for nitroshare
