### ISSUE TITLE
bluez-alsa is unable to start

### ISSUE THREAD

**Issue by amak79** [void-linux/void-packages#9127]
runit reports that the service is up but no `bluealsa` process is started.  The following error floods syslog:
```
bluealsa: Couldn't initialize controller thread: Bad file descriptor
```
It appears that commit [ecc7b9f1](https://github.com/void-linux/void-packages/commit/ecc7b9f11c74d5af5598e0ace376042d72611dc5) broke the run script. The commit uses `vinstall` to create `/run/bluealsa`, but `vinstall` it's not available on my system. Reverting the commit allows bluez-alsa to start.

**Comment by Cogitri** [comment]
@maxice8
