### ISSUE TITLE
[FTBFS] geoip-data

### ISSUE THREAD

**Issue by pullmoll** [void-linux/void-packages#9151]
```
=> geoip-data-20171002_2: running do_fetch ...
looking up geolite.maxmind.com
connecting to geolite.maxmind.com:80
requesting http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz: Not Found
```
It seems legacy data is available only through [geoipupdate](https://dev.maxmind.com/geoip/geoipupdate/) and I have no idea how to deal with it.

**Comment by q66** [comment]
yeah, ran into this just today when building some packages for musl...

**Comment by pullmoll** [comment]
I simply took https://alpha.de.repo.voidlinux.org/current/geoip-data-20171002_2.noarch.xbps and added it to my repodata with `xbps-rindex -a` for all target architectures.

**Comment by q66** [comment]
yeah, I ended up just taking it from my glibc repo, since it's noarch...

**Comment by the-maldridge** [comment]
As geoip-data is no longer distributable or buildable, I'm going to close this.
