### ISSUE TITLE
Firefox-61.0_2 Segfaults on startup without pulseaudio installed

### ISSUE THREAD

**Issue by syncorpus** [void-linux/void-packages#918]
### System

* xuname:  
  Void 4.17.6_1 x86_64-musl GenuineIntel uptodate r 
* package:  
  firefox-61.0_2

### Expected behavior
Firefox to launch as normal
### Actual behavior
segfaults before it even draws the window
### Steps to reproduce the behavior
Be on Musl build, install firefox, run firefox

### Fix
Install pulseaudio (in my case I also installed alsa-plugins-pulseaudio although I'm unsure if that helps or not)  this is also a good time to mention that installing pulseaudio will create ~/.config/pulse and associated files as root owned files(ie not world read/write-able) and directories meaning you have to manually chown them to your user and group.
  
[firefox-strace.txt](https://github.com/void-linux/void-packages/files/2195847/firefox-strace.txt)

**Comment by Duncaen** [comment]
The trace is not really useful as it only traces one process.

**Comment by syncorpus** [comment]
ehh I'mma close the issue anyway (due to the pulse one being closed for nonrepro) maybe my installs wonky not sure, first time running void although long time linux user.
