### ISSUE TITLE
Package Request: QGIS

### ISSUE THREAD

**Issue by zayuim** [void-linux/void-packages#9180]
QGIS: An open source GIS software, used for viewing/editing geospacial data.

[Build Instructions](https://github.com/qgis/QGIS/blob/master/INSTALL)

Building this package seems quite complicated, I'd say it's above my skill. Also I have never packaged a Linux app before, let alone used XBPS. I hope someone else can figure it out.

**Comment by bobertlo** [comment]
I used to use this, and it doesn't look that hard. I'm taking a shot at it.

**Comment by bobertlo** [comment]
I got stuck on getting Qscintilla PyQt5 packages building. I'll get back to this sometime, but I've been super busy.

**Comment by maxice8** [comment]
ping

**Comment by bobertlo** [comment]
I got super stuck on that Qscintilla package. I looked at some other distro packages and called the build scripts for the PyQt portion and it just hangs. I don't have time to look into this further ATM.

**Comment by cheinu-mike** [comment]
How far did you get? I'm completely new to contributing so I may not get every far myself but I definitely would like QGIS to be available in the repo.

**Comment by SimoneSchwarz** [comment]
Habe das hier gefunden:
[https://github.com/Monkey-7-12/monkeys-void-packages/compare/master...boson-at:WIP-qgis-test](url)
[https://github.com/Monkey-7-12/monkeys-void-packages/blob/master/srcpkgs/qscintilla-qt5/template](url)

**Comment by SimoneSchwarz** [comment]
repository=https://solanum.fblog.ch/repository/void-linux/experimental
repository=https://solanum.fblog.ch/repository/void-linux/testing
xbps-install -S qgis-test ???

**Comment by ndgnuh** [comment]
Bumping. Is anyone working on this?

([new build instruction's link](https://github.com/qgis/QGIS/blob/master/INSTALL.md))

**Comment by Nyx70** [comment]
> Bumping. Is anyone working on this?
> 
> ([new build instruction's link](https://github.com/qgis/QGIS/blob/master/INSTALL.md))

[https://github.com/void-linux/void-packages/pull/27041](https://github.com/void-linux/void-packages/pull/27041)


[https://nýx.ch/prj/qgis/](https://nýx.ch/prj/qgis/)

**Comment by classabbyamp** [comment]
https://github.com/void-linux/void-packages/commit/148ff09105157173a9e4f1de83ced59c86ec01e4
