### ISSUE TITLE
Rename all packages with "gtk+" to "gtk"

### ISSUE THREAD

**Issue by zayuim** [void-linux/void-packages#9181]
I believe that the GTK community have [finally decided](https://mail.gnome.org/archives/gtk-devel-list/2019-February/msg00000.html) to drop the plus from the name.

What is the viability of renaming "gtk+" packages to simply "gtk"?

**Comment by CameronNemo** [comment]
Seems like a lot of work for a single character.

**Comment by maxice8** [comment]
No, gtk+2 and gtk+3 are still and will always be '+', gtk4 is being done by @Cogitri and he already removed the '+' as upstream did too.

Once gtk4 is released it will be released with gtk4 not gtk+4. Refer to pull request https://github.com/void-linux/void-packages/pull/8803
