### ISSUE TITLE
Package Update Request: OBS

### ISSUE THREAD

**Issue by HeraKumi** [void-linux/void-packages#9184]
https://github.com/obsproject/obs-studio/releases

**Comment by maxice8** [comment]
We have the [void-updates](https://a-hel-fi.m.voidlinux.org/void-updates/void-updates.txt) system to keep us up-to-date with new software releases.

Thanks for your enthusiasm but making update requests are not required unless the update system doesn't catch the new update, in which case it is better to fix it altogether (see the `update` files).

If you really need the new obs the most effective way of getting it in is contributing it yourself (also has the nice bonus of helping everyone else that needs it).
