### ISSUE TITLE
firefox: crash on start without libvpx

### ISSUE THREAD

**Issue by svenper** [void-linux/void-packages#9188]
### System

* xuname:  
  `Void 4.14.95_1 x86_64-musl GenuineIntel uptodate hold rrnFFFFFFFFFFF`
* package:  
  `firefox-65.0.1_1` (with xbps-src build options `~dbus,~pulseaudio`)

### Expected behavior

Either the program doesn't crash at start without libvpx, or the package depends on it.

### Actual behavior

```text
$ /usr/bin/firefox
XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
Error loading shared library libvpx.so.5: No such file or directory (needed by /
usr/lib/firefox/libxul.so)
Couldn't load XPCOM.
```

### Steps to reproduce the behavior

```text
# xbps-remove libvpx
$ firefox
# xbps-install -S libvpx
$ firefox
```

**Comment by maxice8** [comment]
I see

we actually depend on libvpx5 (correctly) but libvpx is still present.

libvpx5 should have a replaces=

**Comment by maxice8** [comment]
thanks for finding it out, i'll push a fix soon

**Comment by eraserewind** [comment]
How can this be fixed ? i'm having the same issue and can't find a way to use Firefox now.

**Comment by eraserewind** [comment]
`ln -s /usr/lib/libvpx.so.5.0.0 /usr/lib/libvpx.so.5` worked as a "workaround" but...

**Comment by Duncaen** [comment]
I think this triggered [a bug in xbps](https://github.com/voidlinux/xbps/issues/190), reinstalling libvpx5 should solve this.

**Comment by eraserewind** [comment]
This seems to have worked. Thanks! :heart:

**Comment by leandroramos** [comment]
> I think this triggered [a bug in xbps](https://github.com/voidlinux/xbps/issues/190), reinstalling libvpx5 should solve this.

Thank you, @Duncaen

**Comment by leandroramos** [comment]
> `ln -s /usr/lib/libvpx.so.5.0.0 /usr/lib/libvpx.so.5` worked as a "workaround" but...

Thank you, @eraserewind

**Comment by sleibrock** [comment]
This error is still present unfortunately, just ran into it myself. Will be using @eraserewind 's workaround.

**Comment by SACViper** [comment]
@eraserewind solution is not working i tried reinstalling library and firefox and symlink again still no avail
