### ISSUE TITLE
pulseaudio-12.0_1 user ~/.config/pulse files installed as root owned   

### ISSUE THREAD

**Issue by syncorpus** [void-linux/void-packages#919]
### System

* xuname:  
  Void 4.17.6_1 x86_64-musl GenuineIntel uptodate r 
* package:  
  pulseaudio-12.0_1

### Expected behavior
 User config files should be user owned so programs can read configuration

### Actual behavior
 User config files installed as root leading to segfaults and program crashes
### Steps to reproduce the behavior
Install pulseaudio, launch a dependent program like firefox and it will crash until ~/.config/pulse is chowned to your user:group or chmod'd to be world read/write

**Comment by Duncaen** [comment]
There is nothing in xbps that installs files into home directories.

**Comment by Vaelatern** [comment]
Can't replicate.
