### ISSUE TITLE
dub and dtools need libphobos>=2.084.1

### ISSUE THREAD

**Issue by The-BigDaddy** [void-linux/void-packages#9245]
This has been an issue for a bit, but the Dlang standard runtime library (libphobos) needs to be updated in order to update the packages `dub` and `dtools`.

`xbps-install -Svu` specfically says

```
Found dtools-2.084.1_1 (update) in repository https://alpha.de.repo.voidlinux.org/current
Found dub-1.13.0_1 (update) in repository https://alpha.de.repo.voidlinux.org/current
MISSING: libphobos>=2.084.1
Transaction aborted due to unresolved dependencies.
```

**Comment by The-BigDaddy** [comment]
Still an issue. It's been an issue about...3 weeks now.

**Comment by maxice8** [comment]
Fixed in https://github.com/void-linux/void-packages/commit/92777573fc11fc7c193f1382758fccfe7b1dd6ee
