### ISSUE TITLE
gitea configuration file overwritten when updating

### ISSUE THREAD

**Issue by scaramacai** [void-linux/void-packages#9260]
### System

* xuname:  
  *Void 4.9.158_1 i686 GenuineIntel uptodate rFF*
* package:  
  *gitea 1.7.3*

### Expected behavior
upgrade from 1.7.2 should not change /etc/sv/gitea/run
### Actual behavior
/etc/sv/gitea/run is overwritten
### Steps to reproduce the behavior
upgrade from 1.7.2

**Comment by Duncaen** [comment]
This is expected, all service scripts are not marked as configuration files.
`run` scripts should follow the pattern of sourcing a `conf` file to allow users to change the behavior.

So the the real fix would be to add `[ -r  ./conf ] && . ./conf` to the gitea service script or to use xbps's `preserve` feature: `echo "preserve=/etc/sv/gitea/run" > /etc/xbps.d/gitea.conf`.

**Comment by maxice8** [comment]
> `run` scripts should follow the pattern of sourcing a `conf` file to allow users to change the behavior

We problably need a section on Manual.md for all those requirements.

- Only create directories in temporary places
- Source 'conf'

**Comment by scaramacai** [comment]
This is my first attempt to use Void on a real "production" machine and I was not fully aware of the policies about files in /etc. Anyway this behavior is ok to me, so I'm now closing this issue.
Thank you for your prompt reply.
