### ISSUE TITLE
Package Request: Jetbrains IDEs

### ISSUE THREAD

**Issue by soullivaneuh** [void-linux/void-packages#9299]
It would be great to add a way to simply install it with the void package manager as it's done for snap: https://snapcraft.io/phpstorm

A lot of developers are using those products.

**Comment by Johnnynator** [comment]
We have a few already. ( `pycharm-community` and `intellij-idea-community-edition` ). I assume you want to have phpstorm?

**Comment by soullivaneuh** [comment]
@Johnnynator I'm indeed especially interested by PHPStorm and also Goland, but I don't think the installation way is different, so why not add them all? :+1:

**Comment by Johnnynator** [comment]
> so why not add them all? 👍
 intellij and pycharm are both the free community edition. For any other jetbrains ide we would pack a Proprietary version (which I don't know the exact licensing and if we are allowed to redistribute it). The Communit Editions are `Apache-2.0`

**Comment by soullivaneuh** [comment]
I see. Well, package from snap seems to be directly managed by jetbrains: https://snapcraft.io/phpstorm

Before using snap, I did the install with a script and the tar.gz is accessible from the website with a simple wget, without license agreement etc... So I'm note sure it will be a problem, am I wrong? :thinking:

**Comment by Hoshpak** [comment]
Jetbrains is allowed to offer their software as a snap or any other way they like as they own the copyright. Without permission to redistribute their copyrighted software, standard copyright applies which means we are not allowed to redistribute. The package could only be added as an restricted package which means it would not end up in the repository but you could create a package for your personal use yourself using xbps-src.

**Comment by Cogitri** [comment]
FWIW it might be a better idea to just use the `Jetbrains Toolbox` or just the IDE's update tool directly for their proprietary IDEs (works fine for CLion for me).

**Comment by soullivaneuh** [comment]
@Cogitri same question then, can we distribute `Jetbrains Toolbox` according to the licences? :thinking:

**Comment by Cogitri** [comment]
No, just install it from their website.

**Comment by soullivaneuh** [comment]
If distribution is the only problen, can they be added as a restricted package then? 

The tar.gz can be downloaded from jetbrains direct links.

**Comment by Cogitri** [comment]
Sure, we can package it as restricted package, but I don't quite see the advantage of that. You just lose the automatic updating capabilities of the Jetbrains Toolkit.

**Comment by soullivaneuh** [comment]
@Cogitri I don't want another mini-tools that installs thing for me and I want more custom automation on my void setup. :-)

**Comment by sburris0** [comment]
Current status is that there is now a GoLand package, and this open PR for PhpStorm:
https://github.com/void-linux/void-packages/pull/12670

**Comment by 2asoft** [comment]
Another status update.

The following currently already exist as restricted packages:
CLion (`CLion`)
GoLand (`GoLand`)
RubyMine (`RubyMine`)
WebStorm (`WebStorm`)
IntelliJ Ultimate (`intellij-idea-ultimate-edition`)

Pending approval:
DataGrip (`DataGrip`) #17447 
The aforementioned PhpStorm (`PhpStorm`) #12670

**Comment by Logarithmus** [comment]
@2asoft Hello, please, can you explain why is **intellij-idea-community-edition** marked as nonfree? AFAIK, IDEA belongs to Apache 2.0 license.
Also why those other IDE's like CLion, WebStorm, etc. are marked as **restricted**, but not just **nonfree**? I've tried hard to find any info on JetBrains' website about them banning the redistribution of binary packages, but had no luck.
I'm sorry, if I'm asking about too obvious things, but I really just don't get it.

**Comment by 2asoft** [comment]
> can you explain why is **intellij-idea-community-edition** marked as nonfree? AFAIK, IDEA belongs to Apache 2.0 license.

I didn't add the community edition and am not aware why it was marked `nonfree`.

> why those other IDE's like CLion, WebStorm, etc. are marked as **restricted**, but not just **nonfree**? I've tried hard to find any info on JetBrains' website about them banning the redistribution of binary packages, but had no luck.

I believe Void prohibits destribution of binary-only software.
As a guess, since most commercial licensed software has some kind of restriction on redistribution, it is difficult to ensure that an agreement to redistribute is obtained and kept for legal purposes later on, so it is often easier to simply not redistribute.

**Comment by virus-found** [comment]
> I believe Void prohibits distribution of binary-only software.
I don't think so. There is a spotify-1.1.26_1 package in Void.

**Comment by 2asoft** [comment]
> I don't think so. There is a spotify-1.1.26_1 package in Void.

The current version of the `spotify` package in Void is 1.1.26_2.
1.1.26_1 is the last non-restricted version and it is available for installation still.
It became restricted as of #23576. Per PR description, it is expected that the currently available version will be removed from the repos at some point.

**Comment by ericonr** [comment]
We have many IDEs as restricted packages. If you need a new one, it should be simple to include it.
