### ISSUE TITLE
Package Request: Discord

### ISSUE THREAD

**Issue by soullivaneuh** [void-linux/void-packages#9311]
https://discordapp.com/download

Download like: https://discordapp.com/api/download?platform=linux&format=tar.gz

**Comment by Duncaen** [comment]
Its already there as [restricted package](https://docs.voidlinux.org/xbps/repositories/restricted.html), the license doesn't allow redistribution, you have to "build" the package yourself if you want to install it with xbps.

**Comment by soullivaneuh** [comment]
Thanks for the link, I'll look at it.

**Comment by soullivaneuh** [comment]
Just for curiosity, why can we see it in snap then? https://snapcraft.io/discord

Maybe they got the authorization?

**Comment by Duncaen** [comment]
The old discussion/issue about it: https://github.com/voidlinux/void-packages/pull/4104

In short, they there are some "permissions" but they are not binding and there are many open questions about the legality.

We are no lawyers and we can't say for sure if a email from the discord support counts as legal  "written permission". Repository mirrors would also redistribute the binaries, this makes it even more complicated, do we need written permissions for each mirror? etc.

Without a clear license that allows redistribution software like this can't be included.

**Comment by soullivaneuh** [comment]
Fair enough, thanks for your time!
