### ISSUE TITLE
OBS-studio: Didn't auto-update to next version/new features involved

### ISSUE THREAD

**Issue by HeraKumi** [void-linux/void-packages#9322]
Obs currently has a newer version at 23.0.1 but with a lot of changes which included vaapi support so, I don't know if the package should be rebuilt from scratch.

https://github.com/obsproject/obs-studio/releases

Thanks

**Comment by Hoshpak** [comment]
Updates don't happen automatically in Void, someone has to do it. Feel free to create a PR if you need the new version. Opening issues is not necessary since the package is covered by the automtic update check so people are aware that a newer version is available.
