### ISSUE TITLE
Package Request: gogglesmm

### ISSUE THREAD

**Issue by jarbowski** [void-linux/void-packages#9358]
Goggles Music Manager is probably the best music player and manager non based on gstreamer.
Since it now includes a copy of updated fox-devel, it's easier to distribute.
Thanks

https://github.com/gogglesmm/gogglesmm

**Comment by jarbowski** [comment]
template proposal:

# Template file for 'gogglesmm'
pkgname=gogglesmm
version=1.2.1
revision=1
build_style=cmake
hostmakedepends="pkg-config"
makedepends="desktop-file-utils faad2-devel glu-devel libepoxy-devel libmad-devel pulseaudio-devel opus-devel sqlite-devel taglib-devel zlib-devel libflac-devel libvorbis-devel"
depends="hicolor-icon-theme"
short_desc="Music Manager and Player"
homepage="http://gogglesmm.github.io/"
maintainer=""
license="GPL3"
distfiles="https://github.com/$pkgname/$pkgname/archive/$version.tar.gz"
checksum="f068667e0a825ac792eda344cbe94c29fe8668ddbdd269c094e5bf168acd2380"

**Comment by maxice8** [comment]
Please make a PR if you want the template to be properly reviewed

**Comment by jarbowski** [comment]
ok, did a pr:
https://github.com/void-linux/void-packages/pull/9392

it works at home but travis doesn't agree
help is welcome

**Comment by jarbowski** [comment]
https://github.com/void-linux/void-packages/pull/9392
