### ISSUE TITLE
nonfree repo breaks firefox

### ISSUE THREAD

**Issue by foratseif** [void-linux/void-packages#9408]
### System
Void 4.19.26_1 x86_64 GenuineIntel uptodate rrFFFF
firefox-65.0.1_2

### Expected behavior
I should be able to install chromium-widevine or firefox

### Actual behavior
Output:
```
firefox-65.0.1_2: broken, unresolvable shlib `libvpx.so.5'
Transaction aborted due to unresolved shlibs.
``` 

### Steps to reproduce the behavior
Tied installing using the clone of this repo:
```sudo xbps-install --repository=hostdir/binpkgs/nonfree chromium-widevine```

And also tried following this guide:
[https://wiki.voidlinux.org/Chromium-widevine](https://wiki.voidlinux.org/Chromium-widevine)

**Comment by abenson** [comment]
Have you tried `xbps-install -Syu` before installing?

**Comment by maxice8** [comment]
I made libvpx depend on libvpx5, please update your system and try again
