### ISSUE TITLE
GHC requires `gmp-devel` package

### ISSUE THREAD

**Issue by vinnyA3** [void-linux/void-packages#9416]
### System

* xuname:  
`Void 4.19.26_1 x86_64 GenuineIntel notuptodate rFFF`
* package:  `stack-1.9.3_1`

### Expected behavior

With stack installed, I expect to be able to run `stack ghci` to run the interpreter.

### Actual behavior

Receiving the following error:

```
GHCi, version 8.6.3: http://www.haskell.org/ghc/  :? for help
Configuring GHCi with the following packages:
<command line>: can't load .so/.DLL for: libgmp.so (libgmp.so: cannot open shared object file: No such file or directory)
```

### Steps to reproduce the behavior

- `stack ghci`

----

**Note**: 
 - In order to get stack to install, I needed to create a libcurses symlink - *issue*: #7403 
 - Installing the `gmp-devel` package ultimately solved the issue

**Comment by transitracer** [comment]
This shouldn't require the -devel version of the package, no? Since you aren't building ghc, you're installing a bindist
