### ISSUE TITLE
Package Request: mednaffe

### ISSUE THREAD

**Issue by Vlad-Romanov** [void-linux/void-packages#944]
Hope you guys do not mind all the package requests I am making, these templates work & I have no problem maintaining them. I have want to make these for long time, am just getting the handle of English :D 

```
# Template file for 'mednaffe'
pkgname=mednaffe
version=0.8.8
revision=1
wrksrc="${pkgname}-${version}"
build_style=gnu-configure
configure_args="--enable-gtk3"
hostmakedepends="autoconf pkg-config"
makedepends="gtk+3-devel"
depends="mednafen"
short_desc="a front-end for the Mednafen emulator"
maintainer="VladTheImpaler <vladimir-romanov-ii@yandex.com>"
license="GPL-3"
homepage="https://github.com/AmatCoder/mednaffe"
distfiles="https://github.com/AmatCoder/${pkgname}/archive/${version}.tar.gz"
checksum=ec5b3db0d83d747ce6ad0c3b0cf4483914b2308aa089ec52dd9d45d5b093acb7

pre_configure() {
autoconf
}
```

**Comment by Johnnynator** [comment]
You should make a Pull Request instead of an issue.

**Comment by Vlad-Romanov** [comment]
ohh, okay. Sorry, I will do this from now.

**Comment by Vlad-Romanov** [comment]
I must fork the repo to do a pull request? I am not very savvy with github, am sure I will figure it out...

**Comment by Johnnynator** [comment]
Yep, the wiki has an short guide how to set some stuff up. https://wiki.voidlinux.eu/Xbps-src

**Comment by Vlad-Romanov** [comment]
I do one pull request for all packages, or should I do a pull request for each package?

**Comment by Vlad-Romanov** [comment]
Looks like all is done at once, I shall make some more templates & then do pull request, I suppose this is the best way to do it?

**Comment by Johnnynator** [comment]
Always do one Pull Request per package.

**Comment by Vlad-Romanov** [comment]
Ohh ok... I did not know how to do that, will have to keep trying.

**Comment by Vlad-Romanov** [comment]
Am having trouble understanding how to do pull request for one file per pull.. :(

**Comment by Vlad-Romanov** [comment]
I guess is official, I cannot figure this out.... How does one make one pull request per file? It want to do them all at once...

**Comment by Vlad-Romanov** [comment]
thank you Chocimier, I have figure it out. Make branch when doing commit, and then can do pull request from that.

**Comment by cr6git** [comment]
@Vlad-Romanov done.
