### ISSUE TITLE
gmrun-0.9.2_4  Segmentation fault

### ISSUE THREAD

**Issue by Manchotix** [void-linux/void-packages#9454]
### System

* xuname:  Void 4.19.27_1 x86_64 GenuineIntel uptodate rrFFF
* package:  gmrun-0.9.2_4

### Expected behavior
That is run without Segmentation fault
(Bug-Fix for: 
https://sourceforge.net/p/gmrun/bugs/8/
https://sourceforge.net/p/gmrun/bugs/9/
)
### Actual behavior
$ gmrun 
Segmentation fault
### Steps to reproduce the behavior
Install gmrun with:
$ xbps-install gmrun
Run the command in Terminal
$ gmrun
### possible solution
Can we build 'gmrun' from a fork Repo?
https://github.com/wdlkmpx/gmrun
This is a fork from gmrun that fix the open issues from the gmrun on Source-Forge.
This repo is also used at Archlinux.

**Comment by maxice8** [comment]
the fork still segfaults
