### ISSUE TITLE
Vim crashing (in the way described in RedHat / Fedora Bug 1671222)

### ISSUE THREAD

**Issue by datenwolf** [void-linux/void-packages#9516]
### System

* xuname:  

    Void 4.19.26_1 x86_64 GenuineIntel uptodate rrrrrmmdnFFFFFFFF

* package:  

    vim{,-common,-x11}-8.1.0800_1

### Expected behavior

Vim not unexpectedly crashing

### Actual behavior

Vim crashing with output

    free(): double free detected in tcache 2
    Vim: Caught deadly signal ABRT
    Vim: preserving files...
    Vim: Finished.

The behavior is exactly as reported to the RedHat / Fedora project in bug 1671222 https://bugzilla.redhat.com/show_bug.cgi?format=multiple&id=1671222

### Steps to reproduce the behavior

Perform system update, work with Vim for a couple of minutes, observe vim crashing.

Suggested workaround of deinstalling plugins didn't resolve the issue.

**Comment by leahneukirchen** [comment]
I updated to 8.1.1002 (d712a97c25) and there was a double free fix in 8.1.917.

Please reopen if the issue still appears.

**Comment by Piraty** [comment]
isn't that why you should be using neovim instead? :point_up_2: :smiley:

**Comment by datenwolf** [comment]
Let's just say, that I've tried Neovim several times, and there are some features in it which I really desire. But unfortunately it still misses non-Qt X11 integration (selection/clipboard, EWMH for improved interaction with programmable window managers). And whenever I tried it I found neovim-qt to be so-la-la… I guess I can improve the situation by aggressive application of patience.
