### ISSUE TITLE
Package Request : ufetch

### ISSUE THREAD

**Issue by bbleble** [void-linux/void-packages#9579]
This program is an alternative to neofetch.

https://gitlab.com/jschx/ufetch

**Comment by maxice8** [comment]
Please ask the ufetch project to tag a release otherwise we can't package it.

**Comment by maxice8** [comment]
Plus neofetch exists and works wonderfully

**Comment by bbleble** [comment]
Ok thanks.

**Comment by bbleble** [comment]
Sure, I'll ask them. Thanks for your help.
Really appreciate.
And, sorry for a lot of my package requests.

**Comment by humaidq** [comment]
ufetch is much faster than neofetch (~3x faster), which is why I prefer it.

**Comment by Kozova1** [comment]
I've put in a PR with a ufetch template
