### ISSUE TITLE
Package Request: Typora

### ISSUE THREAD

**Issue by xerxeslins** [void-linux/void-packages#9585]
Typora is available for Debian, NixOS, Mint and Ubuntu. It would be great to have it on Void.

Typora: A minimal markdown editor.

http://support.typora.io/Typora-on-Linux/

**Comment by maxice8** [comment]
Seems to be proprietary.

**Comment by Johnnynator** [comment]
```
Copyright (c) 2015~2019 Abner Lee

All Rights Reserved.

-----

Typora is powered by Electron (MIT License, Github Inc) and several open source project

See `Help` -> `Credits` for full license text
````
Doesn't seem to allow us to redistribute

**Comment by maxice8** [comment]
Sorry but considering all distros just pull in the .deb and cannibalize it for their own distro it means we have no control over the libraries and updates on our provided libraries can completely screw users of this without a chance of fixing it properly. (See discord and freetype).

**Comment by CameronNemo** [comment]
I will point out that there is no particular shortage of open source markdown editors packaged and not packaged in Void. Please file a request in the latter case.

**Comment by xerxeslins** [comment]
Thank you very much for your consideration.
