### ISSUE TITLE
rxvt-unicode: fix terminfo for minimal install

### ISSUE THREAD

**Issue by lemmi** [void-linux/void-packages#9615]
### System

* package:  
  * `rxvt-unicode-terminfo-9.22_9`

### Expected behavior
`/usr/share/terminfo/r/` to be populated
### Actual behavior
* Install script fails
### Steps to reproduce the behavior
* Install void with `base-minimal`
* Install `rxvt-unicode-terminfo`
* use `urxvt` from remote host (ssh, run that minimal install in a container) and set `TERM=rxvt-unicode-256color`
* Check weird behaviour:
  * can't use backspace in terminal
  * htop won't work
  * ...

So `rxvt-unicode-terminfo` ships with this install script:
```
case "${ACTION}" in
post)
	tic -s usr/share/terminfo/r/rxvt-unicode.terminfo
	;;
esac
```
It uses `tic`, but that's contained in `ncurses`, which is not a dependency of `rxvt-unicode-terminfo`.
The obvious solution is to add `ncurses` as a dependency to `rxvt-unicode-terminfo`. But I wanted to ask If we can just compile the files during build and get rid of the scripts.

**Comment by maxice8** [comment]
please check #9633

**Comment by maxice8** [comment]
We can certainly do that, Alpine and Arch Linux do it.

**Comment by Duncaen** [comment]
I think ncurses should be a dependency of `base-minimal`, like it is in `base-system`.

**Comment by am11** [comment]
> I think ncurses should be a dependency of base-minimal, like it is in base-system.

Yes please. At least, `nano` and `bash` do not function properly in Void's docker container without ncurses present.

<ins>Bash:</ins>
It took me a while to figure out why pressing [BACKSPACE] was printing [SPACE] in the interactive shell space and ←, → arrow keys were not doing anything.

<ins>Nano:</ins>
in a fresh VoidLinux docker container, after installing nano when i ran it, it reported:
`Error opening terminal: xterm.`.

Just installing `ncurses` fixed both of these issues. (everything else mentioned on google, `check the output of $TERM`, `output of stty -a` etc. was in accord; I have tested it couple of times just to be sure). :)
