### ISSUE TITLE
Package request: powerline-font

### ISSUE THREAD

**Issue by soullivaneuh** [void-linux/void-packages#9705]
Already provided by some OS: https://powerline.readthedocs.io/en/master/installation/linux.html

**Comment by JasMich** [comment]
Yes, please package!

**Comment by sgn** [comment]
Font is unlikely accepted

**Comment by LamaRaz** [comment]
In case you don't know. nerd-fonts have awesome and powerline patched into everything. So if you need the powerline triangles just use "Firacode Nerd Font" for example.

**Comment by bitmeise** [comment]
> Font is unlikely accepted

Okay, but why?
