### ISSUE TITLE
GNOME-Terminal gets umask wrong

### ISSUE THREAD

**Issue by Cogitri** [void-linux/void-packages#9707]
It appears that after #9126 GNOME-Terminal gets the umask wrong, defaulting to 0007. Sourcing /etc/profile fixes that, but I'm not exactly sure why because we already source that via gnome-session.

@glats

**Comment by Cogitri** [comment]
Seems like this even happens when I uncomment the line in gnome-session which source profile..hmm

**Comment by glats** [comment]
Sorry for the lack of time! but yeah. doesnt work etheir :(

**Comment by glats** [comment]
actually a did try to put ```umask 0022``` in /etc/gnome-session and didnt work :S

**Comment by Cogitri** [comment]
Mind trying it again but checking 'Run as login command' in GNOME-Terminal->Settings->Profile->Command?

**Comment by glats** [comment]
oh yes! thats work fine.
maybe we need put this configuration in the void wiki.

**Comment by Cogitri** [comment]
See the PR, that makes it the default for new profiles.

**Comment by glats** [comment]
Nice. you are the best dude!

**Comment by glats** [comment]
Last version works fine. Thnks
