### ISSUE TITLE
dockerd: failed to find runc binary

### ISSUE THREAD

**Issue by shizonic** [void-linux/void-packages#9717]
### System

* xuname:  
  * Void 4.20.15_1 x86_64 GenuineIntel uptodate rrFFFFFFFFFFFFFFFFFFFF
* package:  
  * docker
  * runc

### Expected behavior
runc binary should be existing.

### Actual behavior
runc binary does not exist.

### Steps to reproduce the behavior
Install docker and start service log into log files. Or just run dockerd in shell.

**Comment by shizonic** [comment]
Force reinstalling runc fixes this issue.

**Comment by Duncaen** [comment]
Probably the bug again, where `runc` is unpackaged before `docker`, provides the `/usr/bin/runc` then docker is installed, removing `/usr/bin/runc` because it was owned by docker before the update.
https://github.com/voidlinux/xbps/issues/190

**Comment by shizonic** [comment]
this makes sense. so actually it's not fixed?

**Comment by Duncaen** [comment]
Well its not fixed but its a known bug and void-packages/xbps-src can't fix it.

**Comment by shizonic** [comment]
Okay. But maybe it would be possible to add something like multi owns. So multiple packages can own a file and therefore it only gets removed if no other packages is installed that owns it... Just some thoughts...

**Comment by Duncaen** [comment]
Yes, there would be ways to fix it but that is for xbps to do. I don't think multiple packages owning the same file is not a good idea because checksums are potentially different etc.

**Comment by shizonic** [comment]
Okay I see. But is there someone working on it?
