### ISSUE TITLE
Package request: Termite

### ISSUE THREAD

**Issue by soullivaneuh** [void-linux/void-packages#9769]
https://github.com/thestinger/termite

BTW, if you have a good replacement as basic as `URxvt` that supports emoji waiting the package, I'll be glad to hear about it. :+1:

**Comment by Hoshpak** [comment]
https://github.com/voidlinux/void-packages/issues/5760

**Comment by soullivaneuh** [comment]
Oh right, sorry about that!

**Comment by maxice8** [comment]
This package depends on a patched version of vte3 used by various terminals, notably gnome-terminal.

The patches aren't upstream and they claim the same soname.

**Comment by unihernandez22** [comment]
Why isn't termite in void's repositories?
