### ISSUE TITLE
Package Request: x2goclient

### ISSUE THREAD

**Issue by purpurrot** [void-linux/void-packages#9779]
Qt-based X2Go Client

https://wiki.x2go.org/doku.php/sources:start

**Comment by purpurrot** [comment]
`
diff --git a/Makefile b/Makefile
index a87b21f..6100334 100755
--- a/Makefile
+++ b/Makefile
@@ -20,8 +20,8 @@ ETCDIR=/etc/x2go
 BINDIR=$(PREFIX)/bin
 SHAREDIR=$(PREFIX)/share
 MANDIR=$(SHAREDIR)/man
-QMAKE_BINARY=qmake-qt4
-LRELEASE_BINARY=lrelease-qt4
+QMAKE_BINARY=qmake
+LRELEASE_BINARY=lrelease
 QMAKE_OPTS=
 
 LDFLAGS+=-lldap -lcups -lX11 -lXpm
diff --git a/src/printwidget.cpp b/src/printwidget.cpp
index 58a8af7..52cf547 100644
--- a/src/printwidget.cpp
+++ b/src/printwidget.cpp
@@ -23,6 +23,7 @@
 #include "x2gosettings.h"
 #include "x2gologdebug.h"
 #include <QDir>
+#include <QtWidgets>
 #ifdef Q_OS_WIN
 #include "wapi.h"
 #endif
diff --git a/x2goclient.pro b/x2goclient.pro
index f628fa3..bb4e86f 100644
--- a/x2goclient.pro
+++ b/x2goclient.pro
@@ -132,7 +132,7 @@ SOURCES += src/sharewidget.cpp \
            src/compat.cpp \
            src/pulsemanager.cpp
 
-LIBS += -lssh -lssh_threads
+LIBS += -lssh
 win32:LIBS += -lAdvAPI32 -lshell32 -lUser32
 
 RC_FILE = res/x2goclient.rc
`

**Comment by purpurrot** [comment]
Above is a patch for building the x2goclient with qt5.

**Comment by Anachron** [comment]
There is already someone who did this but didn't submit a PR yet: https://github.com/renatoaguiar/void-packages/tree/x2goclient

**Comment by codesections** [comment]
I would also be interested in seeing this merged.  Would it be considered bad form to merge this in without a PR from the original author?  Or is there a different way to see some forward progress on this, given that it's been 5+ months since last movement?

**Comment by eoli3n** [comment]
any update on this ?
