### ISSUE TITLE
Package request: radicle

### ISSUE THREAD

**Issue by whoizit** [void-linux/void-packages#9791]
decentralized git platform based on IPFS

https://github.com/radicle-dev/radicle
http://radicle.xyz/docs/index.html#what-is-radicle

**Comment by whoizit** [comment]
Ooops... not released yet. Сan we leave it open?

**Comment by maxice8** [comment]
it will conflict with the radicale we have in the repos.

**Comment by Anachron** [comment]
Yes the names are very similar but how exactly would the conflict? They share no binaries or config files.

**Comment by maxice8** [comment]
> Yes the names are very similar but how exactly would the conflict? They share no binaries or config files.

read it wrong

**Comment by ericonr** [comment]
No releases yet, this can be reopened once that happens. We can't track all upstreams.
