### ISSUE TITLE
evtest missing in the repos?

### ISSUE THREAD

**Issue by shumvgolove** [void-linux/void-packages#9807]
`Unable to locate 'evtest' in repository pool.` but there is template file for the **evtest** in the repos: [template](https://github.com/void-linux/void-packages/blob/4a00d41d3d4757f443b56899010f420f718a4672/srcpkgs/evtest/template).

**Comment by maxice8** [comment]
Thanks for bringing attention to it, sometimes our builders end up forgoing a package if it fails to build too many times.
