### ISSUE TITLE
Package request: Textadept

### ISSUE THREAD

**Issue by teldra** [void-linux/void-packages#9812]
https://foicica.com/textadept/

I even don't find out how to download sources from mercurial.

**Comment by rgieseke** [comment]
Release downloads are here: https://foicica.com/textadept/CHANGELOG.html

Or from hg tip: https://foicica.com/hg/textadept/archive/tip.zip

**Comment by Johnnynator** [comment]
> Release downloads are here: https://foicica.com/textadept/CHANGELOG.html
> 
> Or from hg tip: https://foicica.com/hg/textadept/archive/tip.zip

What would be the download link for the src of a release? I only see the binary releases there.

**Comment by rgieseke** [comment]
The tgz file is an archive with Makefile i think:

https://foicica.com/textadept/download/textadept_10.3.x86_64.tgz

**Comment by teldra** [comment]
Trying since mentioned but xbps-src can not download that file.

**Comment by Johnnynator** [comment]
> Trying since mentioned but xbps-src can not download that file.

Mh... `xbps-uhelper fetch` doesn't seem to be able to fetch but wget can, to lazy to debug it, you can add `wget` to `hostamakedepends` and set `fetch_cmd="wget"` in the template.

**Comment by teldra** [comment]
Since it is another scintilla-based clone and I need to add some obscure scintilla libs, I abandon this.
