### ISSUE TITLE
/var is not readable by 'others' by default

### ISSUE THREAD

**Issue by pltrz** [void-linux/void-packages#9856]
Not sure if this was intentional or not, but I noticed the change in behaviour.

### System

* xuname: `Void 5.0.1_1 x86_64 GenuineIntel uptodate rFFFFF`
  *output of ``xuname`` (part of xtools)*

* package: `base-files`?
  *affected package(s) including the version*

### Expected behavior
```
$ xbps-install -S -R <repo> -r /mnt base-system
$ ls -l /mnt | grep var
drwxr-xr-x  13 root root  4096 Mar 11 13:25 var
```

### Actual behavior
```
$ xbps-install -S -R <repo> -r /mnt base-system
$ ls -l /mnt | grep var
drwxr-x--- 12 root root 4096 Mar 15 07:18 var
```

**Comment by CameronNemo** [comment]
Is your umask set to 022 or 027 when you call xbps-install?

**Comment by pltrz** [comment]
Huh, yes umask was set to 0027 instead of 0022. Not sure what would have changed it from the default though
