### ISSUE TITLE
Package request: font-simpleicons

### ISSUE THREAD

**Issue by soullivaneuh** [void-linux/void-packages#9862]
https://simpleicons.org/

Not sure about this one. It listed as a [possibility for Polybar](https://github.com/jaagr/polybar/wiki/Fonts#icon-fonts) but only SVG are provided.

Shall we compile them to ttf our self?

**Comment by pltrz** [comment]
It's not a font, it's an iconset. And I think you may be mistaken as I don't believe it to be listed on that polybar page.

**Comment by pltrz** [comment]
This can be closed as it can’t be packaged. Sorry @soullivaneuh :/
