### ISSUE TITLE
PHP does not ship with the json extension by default, and the extension is not avalabe as an extra package

### ISSUE THREAD

**Issue by nojusr** [void-linux/void-packages#9865]
### System

* xuname:  
  *Void 4.19.24_1 x86_64 GenuineIntel notuptodate rFF*
* package:  
  *php-7.3.3_2*

### Expected behavior
PHP is able to use various json functions such as json_encode(); and json_decode();

### Actual behavior
said functions don't work, running php returns this:
`
PHP Warning:  PHP Startup: Unable to load dynamic library 'json' (tried: /usr/lib/php/modules/json (/usr/lib/php/modules/json: cannot open shared object file: No such file or directory), /usr/lib/php/modules/json.so (/usr/lib/php/modules/json.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
`

### Steps to reproduce the behavior
1. install PHP
2. add 'extension=json' to /etc/php/php.ini to try to enable the json extension
3. try to run said functions, which are supposed to return an object, but instead return NULL

**Comment by Hoshpak** [comment]
As https://www.php.net/manual/en/json.requirements.php states:

```
There is no installation needed to use these functions; they are part of the PHP core.
```

And indeed the functions work with our php package without installing additional modules. Just remove the non-exisiting extension from your php.ini.
