### ISSUE TITLE
easyrsa apparently supports LibreSSL now, should we re-add that package?

### ISSUE THREAD

**Issue by AGausmann** [void-linux/void-packages#9867]
Related to the [prior issue](https://github.com/voidlinux/void-packages/issues/7478) regarding easyrsa not supporting libressl, but I made a new one here to avoid using old channels.

About a month after that issue was closed, citing some kind of wontfix from the OpenVPN developers, they had apparently [resolved](https://github.com/OpenVPN/easy-rsa/issues/76#issuecomment-415586859) the [issue](https://github.com/OpenVPN/easy-rsa/commit/93b0f2e74bb600c7f05c20eaa97f7b12fb7ba670) upstream, and they officially support LibreSSL now, from what I can tell.

Given this, can we re-introduce the easyrsa package?

**Comment by AGausmann** [comment]
I've updated the previous package template with the new version of EasyRSA and have submitted a pull request: #10090

**Comment by Hoshpak** [comment]
resolved by #10090
