### ISSUE TITLE
Building ffmpeg with AV1 support is broken

### ISSUE THREAD

**Issue by recod4** [void-linux/void-packages#9874]
### System

* xuname:  
Void 5.0.2_1 x86_64 GenuineIntel uptodate rrrmFFFF
* package:  
 ffmpeg 4.1.1_1

### Expected behavior
Building ffmpeg with AV1 support via xbps-src should work.

### Actual behavior
Tried to build ffmpeg with AV1 support, got this error:
ERROR: aom >= 1.0.0 not found using pkg-config
 
### Steps to reproduce the behavior
try to build ffmpeg from xbps-src with aom build option

**Comment by jnbr** [comment]
The problem is that the pkgconfig file of `libaom-1.0.0.1` has Version set to `0.1.0`.
Not sure if this should be changed to be `1.0.0` or fixed in ffmpeg or not at all.
@maxice8 do you have an opinion?

**Comment by maxice8** [comment]
well ffmpeg is the only consumer of libaom.

Do whichever you want we can fix it later if we end up doing the wrong choice.

**Comment by jnbr** [comment]
fixed with 0a2700d232e20cb27a55102fc158665abe0c7433
