### ISSUE TITLE
Package request: PopOS icon theme

### ISSUE THREAD

**Issue by soullivaneuh** [void-linux/void-packages#9875]
Just another icon theme: https://github.com/pop-os/icon-theme

**Comment by Johnnynator** [comment]
It doesn't have any tagged release

**Comment by soullivaneuh** [comment]
@Johnnynator What about this? https://github.com/pop-os/icon-theme/releases :thinking:

**Comment by Johnnynator** [comment]
They are Papirus Icon releases, PopOS icons is a fork of them.

**Comment by soullivaneuh** [comment]
According to the description, it's a combination of two icon sets.

**Comment by maxice8** [comment]
Please ask upstream for a release

**Comment by soullivaneuh** [comment]
Oh right, I didn't see it was the release of the forked repo, sorry.

**Comment by soullivaneuh** [comment]
@jnbr I think you targeted the wrong issue.

**Comment by jnbr** [comment]
yes, sorry

**Comment by Clos3y** [comment]
If still of interest, they have now made a [release](https://github.com/pop-os/icon-theme/releases/tag/v3.3.0).
