### ISSUE TITLE
Add tracker-miners dependency to nautilus

### ISSUE THREAD

**Issue by Roswell-1947** [void-linux/void-packages#9911]
### System

* xuname:  
  Void 4.19.29_1 x86_64 AuthenticAMD uptodate rrrmFFF
* package:  
  nautilus-3.32.0_1

### Expected behavior
nautilus launches without issues.

### Actual behavior
nautilus complains about missing tracker-miners in terminal and fails to launch.

### Steps to reproduce the behavior
After updating nautilus to 3.32.0 it fails to launch without tracker-miners installed. Remains an issue even after completely reinstalling Void. Not sure if we should add it as a dependency or wait for an upstream response.

Here's the issue filed upstream: https://gitlab.gnome.org/GNOME/nautilus/issues/943

**Comment by Cogitri** [comment]
Thanks for notifying here, sadly upstream failed to communicate that in the README

**Comment by crater2150** [comment]
Nautilus still fails to launch for me with
```
(org.gnome.Nautilus:671): Tracker-ERROR **: 10:50:01.055: Unable to find default domain ontology rule /usr/share/tracker/domain-ontologies/default.rule                                                         
```
This is fixed by installing `tracker. From a short test, it looks like both `tracker` and `tracker-miners` are required.

**Comment by Cogitri** [comment]
Not on PC right now, but I'm pretty sure that Nautilus links against tracker, that's why I haven't added it to its deps.

**Comment by crater2150** [comment]
There is also a package `libtracker`, which is pulled in by nautilus, but the missing file that causes the error is included in `tracker`, which is not pulled in as a dependency.

**Comment by crater2150** [comment]
Nautilus does not seem to depend on the `tracker` executable, maybe an alternative is to move the files in `/usr/share/tracker` to the `libtracker` subpackage
