### ISSUE TITLE
Package Requests: elementary-xfce / green-recorder

### ISSUE THREAD

**Issue by ghost** [void-linux/void-packages#9975]
Hello :)

**elementary-xfce**: Xubuntu icons that go well with Greybird theme.
https://github.com/shimmerproject/elementary-xfce

~~**lynis**: Auditing scripts, very useful and complete.
https://github.com/CISOfy/lynis~~ done

**green-recorder**: Screencast software in GTK3.
https://github.com/foss-project/green-recorder

Thanks!

**Comment by newbluemoon** [comment]
I made a template for the elementary-xfce icons once and use them myself, but because icon themes are somewhat discouraged I didn’t open a PR. If you’re interested it’s here:
https://github.com/newbluemoon/void-packages/tree/elementary-xfce-icon-theme/srcpkgs/elementary-xfce-icon-theme/

**Comment by jcgruenhage** [comment]
Wouldn't it make sense to split those up into different issues? I'd like to :+1: the lynis request.
