### ISSUE TITLE
When MESA gets updated...

### ISSUE THREAD

**Issue by Vlad-Romanov** [void-linux/void-packages#998]
Void 4.17.6_1 x86_64-musl GenuineIntel uptodate rrnDDDDDDDF

Last few times MESA has gotten update I have to delete & recreate user account to make Falkon work... have tried delete .config & .local but still falkon do not work until user account deleted & recreated. I hope this will help in solving issues, maybe it gives clue? I have done twice now & each time has solved issue of falkon not working.

**Comment by Gottox** [comment]
`rm ~/.cache/mesa_shader_cache/` solves the problem.

**Comment by Gottox** [comment]
Also... PLEASE stick to the template. It really helps to understand and locate issues.
